In [2]:
pip install pandas openpyxl tokenizers sentencepiece transformers tqdm numpy

Requirement already satisfied: pandas in ./lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: openpyxl in ./lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: tokenizers in ./lib/python3.12/site-packages (0.15.2)
Requirement already satisfied: sentencepiece in ./lib/python3.12/site-packages (0.1.99)
Requirement already satisfied: transformers in ./lib/python3.12/site-packages (4.36.2)
Requirement already satisfied: tqdm in ./lib/python3.12/site-packages (4.67.1)
Requirement already satisfied: numpy in ./lib/python3.12/site-packages (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in ./lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: huggingface_hub<1.0,>=0.16.4 in ./lib/python3.12/site-packages (from tokenizers) (0.31.4)
Requirement already satisfied: filelock in ./lib/python3.12/site-packages (from transformers) (3.18.0)
Requirement already satisfied: packaging>=20.0 in ./lib/python3.12/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in ./lib/python3.12/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in ./lib/python3.12/site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in ./lib/python3.12/site-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.3.1 in ./lib/python3.12/site-packages (from transformers) (0.5.3)
Requirement already satisfied: fsspec>=2023.5.0 in ./lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers) (2023.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers) (4.13.2)
Requirement already satisfied: six>=1.5 in ./lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib/python3.12/site-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.12/site-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./lib/python3.12/site-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.12/site-packages (from requests->transformers) (2025.4.26)
DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip install pandas datasets transformers torch evaluate sentencepiece tokenizers accelerate openpyxl

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: pandas in ./lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: datasets in ./lib/python3.12/site-packages (2.16.1)
Requirement already satisfied: transformers in ./lib/python3.12/site-packages (4.36.2)
Requirement already satisfied: torch in ./lib/python3.12/site-packages (2.4.0+cu124)
Requirement already satisfied: evaluate in ./lib/python3.12/site-packages (0.4.3)
Requirement already satisfied: sentencepiece in ./lib/python3.12/site-packages (0.1.99)
Requirement already satisfied: tokenizers in ./lib/python3.12/site-packages (0.15.2)
Requirement already satisfied: accelerate in ./lib/python3.12/site-packages (0.25.0)
Requirement already satisfied: openpyxl in ./lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in ./lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: filelock in ./lib/python3.12/site-packages (from datasets) (3.18.0)
Requirement already satisfied: pyarrow>=8.0.0 in ./lib/python3.12/site-packages (from datasets) (20.0.0)
Requirement already satisfied: pyarrow-hotfix in ./lib/python3.12/site-packages (from datasets) (0.7)
Requirement already satisfied: dill<0.3.8,>=0.3.0 in ./lib/python3.12/site-packages (from datasets) (0.3.7)
Requirement already satisfied: requests>=2.19.0 in ./lib/python3.12/site-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in ./lib/python3.12/site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in ./lib/python3.12/site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess in ./lib/python3.12/site-packages (from datasets) (0.70.15)
Requirement already satisfied: fsspec<=2023.10.0,>=2023.1.0 in ./lib/python3.12/site-packages (from fsspec[http]<=2023.10.0,>=2023.1.0->datasets) (2023.10.0)
Requirement already satisfied: aiohttp in ./lib/python3.12/site-packages (from datasets) (3.12.0)
Requirement already satisfied: huggingface-hub>=0.19.4 in ./lib/python3.12/site-packages (from datasets) (0.31.4)
Requirement already satisfied: packaging in ./lib/python3.12/site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in ./lib/python3.12/site-packages (from datasets) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in ./lib/python3.12/site-packages (from transformers) (2024.11.6)
Requirement already satisfied: safetensors>=0.3.1 in ./lib/python3.12/site-packages (from transformers) (0.5.3)
Requirement already satisfied: typing-extensions>=4.8.0 in ./lib/python3.12/site-packages (from torch) (4.13.2)
Requirement already satisfied: sympy in ./lib/python3.12/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx in ./lib/python3.12/site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in ./lib/python3.12/site-packages (from torch) (3.1.6)
Requirement already satisfied: setuptools in ./lib/python3.12/site-packages (from torch) (80.8.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in ./lib/python3.12/site-packages (from torch) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.2.65 in ./lib/python3.12/site-packages (from torch) (12.4.2.65)
Requirement already satisfied: nvidia-cufft-cu12==11.2.0.44 in ./lib/python3.12/site-packages (from torch) (11.2.0.44)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.119 in ./lib/python3.12/site-packages (from torch) (10.3.5.119)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.0.99 in ./lib/python3.12/site-packages (from torch) (11.6.0.99)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.0.142 in ./lib/python3.12/site-packages (from torch) (12.3.0.142)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in ./lib/python3.12/site-packages (from torch) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: triton==3.0.0 in ./lib/python3.12/site-packages (from torch) (3.0.0)
Requirement already satisfied: psutil in ./lib/python3.12/site-packages (from accelerate) (7.0.0)
Requirement already satisfied: et-xmlfile in ./lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./lib/python3.12/site-packages (from aiohttp->datasets) (6.4.4)
Requirement already satisfied: propcache>=0.2.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.20.0)
Requirement already satisfied: six>=1.5 in ./lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (2025.4.26)
Requirement already satisfied: MarkupSafe>=2.0 in ./lib/python3.12/site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./lib/python3.12/site-packages (from sympy->torch) (1.3.0)
DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pandas datasets transformers torch evaluate sentencepiece tokenizers accelerate openpyxl

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: pandas in ./lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: datasets in ./lib/python3.12/site-packages (2.16.1)
Requirement already satisfied: transformers in ./lib/python3.12/site-packages (4.36.2)
Requirement already satisfied: torch in ./lib/python3.12/site-packages (2.4.0+cu124)
Requirement already satisfied: evaluate in ./lib/python3.12/site-packages (0.4.3)
Requirement already satisfied: sentencepiece in ./lib/python3.12/site-packages (0.1.99)
Requirement already satisfied: tokenizers in ./lib/python3.12/site-packages (0.15.2)
Requirement already satisfied: accelerate in ./lib/python3.12/site-packages (0.25.0)
Requirement already satisfied: openpyxl in ./lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in ./lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: filelock in ./lib/python3.12/site-packages (from datasets) (3.18.0)
Requirement already satisfied: pyarrow>=8.0.0 in ./lib/python3.12/site-packages (from datasets) (20.0.0)
Requirement already satisfied: pyarrow-hotfix in ./lib/python3.12/site-packages (from datasets) (0.7)
Requirement already satisfied: dill<0.3.8,>=0.3.0 in ./lib/python3.12/site-packages (from datasets) (0.3.7)
Requirement already satisfied: requests>=2.19.0 in ./lib/python3.12/site-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in ./lib/python3.12/site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in ./lib/python3.12/site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess in ./lib/python3.12/site-packages (from datasets) (0.70.15)
Requirement already satisfied: fsspec<=2023.10.0,>=2023.1.0 in ./lib/python3.12/site-packages (from fsspec[http]<=2023.10.0,>=2023.1.0->datasets) (2023.10.0)
Requirement already satisfied: aiohttp in ./lib/python3.12/site-packages (from datasets) (3.12.0)
Requirement already satisfied: huggingface-hub>=0.19.4 in ./lib/python3.12/site-packages (from datasets) (0.31.4)
Requirement already satisfied: packaging in ./lib/python3.12/site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in ./lib/python3.12/site-packages (from datasets) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in ./lib/python3.12/site-packages (from transformers) (2024.11.6)
Requirement already satisfied: safetensors>=0.3.1 in ./lib/python3.12/site-packages (from transformers) (0.5.3)
Requirement already satisfied: typing-extensions>=4.8.0 in ./lib/python3.12/site-packages (from torch) (4.13.2)
Requirement already satisfied: sympy in ./lib/python3.12/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx in ./lib/python3.12/site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in ./lib/python3.12/site-packages (from torch) (3.1.6)
Requirement already satisfied: setuptools in ./lib/python3.12/site-packages (from torch) (80.8.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in ./lib/python3.12/site-packages (from torch) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.2.65 in ./lib/python3.12/site-packages (from torch) (12.4.2.65)
Requirement already satisfied: nvidia-cufft-cu12==11.2.0.44 in ./lib/python3.12/site-packages (from torch) (11.2.0.44)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.119 in ./lib/python3.12/site-packages (from torch) (10.3.5.119)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.0.99 in ./lib/python3.12/site-packages (from torch) (11.6.0.99)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.0.142 in ./lib/python3.12/site-packages (from torch) (12.3.0.142)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in ./lib/python3.12/site-packages (from torch) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: triton==3.0.0 in ./lib/python3.12/site-packages (from torch) (3.0.0)
Requirement already satisfied: psutil in ./lib/python3.12/site-packages (from accelerate) (7.0.0)
Requirement already satisfied: et-xmlfile in ./lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./lib/python3.12/site-packages (from aiohttp->datasets) (6.4.4)
Requirement already satisfied: propcache>=0.2.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.20.0)
Requirement already satisfied: six>=1.5 in ./lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (2025.4.26)
Requirement already satisfied: MarkupSafe>=2.0 in ./lib/python3.12/site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./lib/python3.12/site-packages (from sympy->torch) (1.3.0)
DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Note: you may need to restart the kernel to use updated packages.

In [1]:
# fine tuning nllb. 
#!/usr/bin/env python3
# Fine-tune NLLB-200 for 2 supported low-resource Indic languages (excluding Meitei Mayek).
#Uses all training data. 

import os
import pandas as pd
from datasets import Dataset
from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    DataCollatorForSeq2Seq,
)
import torch

# ==================== CONFIGURATION ====================
DATA_DIR = "/home/dingku/Desktop/WMT26/WMT26/Cat1/"
MODEL_NAME = "facebook/nllb-200-distilled-600M"
OUTPUT_BASE_DIR = "/home/dingku/Desktop/finetuned_nllb_indic/"

LANGUAGES = [
    {"name": "Assamese", "code": "asm_Beng", "file": "English-AssameseTrainingData2026.xlsx", "col": "as"},
    {"name": "Manipuri", "code": "mni_Mtei", "file": "English-ManipuriTrainingData2026.xlsx", "col": "mni"},
    #{"name": "Mizo",     "code": "lus_Latn", "file": "English-MizoTraningData2026.xlsx", "col": "mz"},
]

# Hyperparameters
BATCH_SIZE = 4
LEARNING_RATE = 2e-5
EPOCHS = 3
MAX_LENGTH = 128

# ==================== DATA LOADING ====================
def load_and_prepare_data(file_path, lang_code, target_col):
    """Load Excel, clean NaNs, add language prefixes, return Dataset."""
    full_path = os.path.join(DATA_DIR, file_path)
    df = pd.read_excel(full_path)

    # Identify English column
    if 'en' in df.columns:
        eng_col = 'en'
    else:
        eng_candidates = [c for c in df.columns if 'english' in c.lower()]
        eng_col = eng_candidates[0] if eng_candidates else df.columns[0]

    # Rename
    df = df.rename(columns={eng_col: 'en', target_col: 'target'})
    df = df[['en', 'target']].dropna()
    df['en'] = df['en'].astype(str).str.strip()
    df['target'] = df['target'].astype(str).str.strip()
    df = df[(df['en'] != '') & (df['target'] != '')]

    # Add language prefixes
    df['source'] = "eng_Latn " + df['en']
    df['target'] = f"{lang_code} " + df['target']

    print(f"  Loaded {len(df)} valid pairs for {lang_code}")
    return Dataset.from_dict({
        'source': df['source'].tolist(),
        'target': df['target'].tolist()
    })

# ==================== TOKENIZATION ====================
def tokenize_function(examples, tokenizer, lang_code):
    tokenizer.src_lang = "eng_Latn"
    source_inputs = tokenizer(
        examples['source'],
        max_length=MAX_LENGTH,
        truncation=True,
        padding=False,
    )
    tokenizer.tgt_lang = lang_code
    target_inputs = tokenizer(
        examples['target'],
        max_length=MAX_LENGTH,
        truncation=True,
        padding=False,
    )
    source_inputs['labels'] = target_inputs['input_ids']
    return source_inputs

# ==================== TRAINING ====================
def train_for_language(lang_config):
    print(f"\n{'='*50}")
    print(f"Training {lang_config['name']} (code: {lang_config['code']})")
    print(f"{'='*50}")

    dataset = load_and_prepare_data(
        lang_config['file'],
        lang_config['code'],
        lang_config['col']
    )

    print("  Loading NLLB model & tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
    model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

    print("  Tokenizing dataset...")
    tokenized_dataset = dataset.map(
        lambda x: tokenize_function(x, tokenizer, lang_config['code']),
        batched=True,
        remove_columns=dataset.column_names
    )

    output_dir = os.path.join(OUTPUT_BASE_DIR, lang_config['name'])
    training_args = Seq2SeqTrainingArguments(
        output_dir=output_dir,
        evaluation_strategy="no",
        save_strategy="epoch",
        learning_rate=LEARNING_RATE,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        weight_decay=0.01,
        num_train_epochs=EPOCHS,
        predict_with_generate=True,
        generation_max_length=MAX_LENGTH,
        logging_dir=os.path.join(output_dir, 'logs'),
        logging_steps=50,
        save_total_limit=2,
        fp16=torch.cuda.is_available(),
        report_to="none",
    )

    data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)
    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset,
        tokenizer=tokenizer,
        data_collator=data_collator,
    )

    print("  Starting training...")
    trainer.train()
    trainer.save_model(output_dir)
    tokenizer.save_pretrained(output_dir)
    print(f"  Model saved to {output_dir}\n")

# ==================== MAIN ====================
def main():
    os.makedirs(OUTPUT_BASE_DIR, exist_ok=True)
    for lang in LANGUAGES:
        try:
            train_for_language(lang)
        except Exception as e:
            print(f"!!! ERROR for {lang['name']}: {e}")
            import traceback
            traceback.print_exc()

if __name__ == "__main__":
    main()

/home/dingku/jupyter_env/lib/python3.12/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.4.0) or chardet (7.4.3)/charset_normalizer (3.4.2) doesn't match a supported version!
  warnings.warn(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(

==================================================
Training Assamese (code: asm_Beng)
==================================================
  Loaded 54000 valid pairs for asm_Beng
  Loading NLLB model & tokenizer...

/home/dingku/jupyter_env/lib/python3.12/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/modeling_utils.py:519: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(checkpoint_file, map_location=map_location)

  Tokenizing dataset...

Map:   0%|          | 0/54000 [00:00<?, ? examples/s]

/home/dingku/jupyter_env/lib/python3.12/site-packages/accelerate/accelerator.py:439: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)
You're using a NllbTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

  Starting training...

  Model saved to /home/dingku/Desktop/finetuned_nllb_indic/Assamese


==================================================
Training Manipuri (code: mni_Mtei)
==================================================
  Loaded 23687 valid pairs for mni_Mtei
  Loading NLLB model & tokenizer...

/home/dingku/jupyter_env/lib/python3.12/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/modeling_utils.py:519: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(checkpoint_file, map_location=map_location)

  Tokenizing dataset...

Map:   0%|          | 0/23687 [00:00<?, ? examples/s]

/home/dingku/jupyter_env/lib/python3.12/site-packages/accelerate/accelerator.py:439: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)

  Starting training...

You're using a NllbTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

  Model saved to /home/dingku/Desktop/finetuned_nllb_indic/Manipuri


==================================================
Training Mizo (code: lus_Latn)
==================================================
  Loaded 49958 valid pairs for lus_Latn
  Loading NLLB model & tokenizer...

/home/dingku/jupyter_env/lib/python3.12/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/modeling_utils.py:519: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(checkpoint_file, map_location=map_location)

  Tokenizing dataset...

Map:   0%|          | 0/49958 [00:00<?, ? examples/s]

/home/dingku/jupyter_env/lib/python3.12/site-packages/accelerate/accelerator.py:439: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)
You're using a NllbTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

  Starting training...
!!! ERROR for Mizo: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 15.89 GiB of which 17.38 MiB is free. Including non-PyTorch memory, this process has 15.87 GiB memory in use. Of the allocated memory 15.40 GiB is allocated by PyTorch, and 185.03 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

Traceback (most recent call last):
  File "/tmp/ipykernel_28140/2351792362.py", line 149, in main
    train_for_language(lang)
  File "/tmp/ipykernel_28140/2351792362.py", line 139, in train_for_language
    trainer.train()
  File "/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/trainer.py", line 1902, in _inner_training_loop
    self.optimizer.step()
  File "/home/dingku/jupyter_env/lib/python3.12/site-packages/accelerate/optimizer.py", line 132, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 454, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/amp/grad_scaler.py", line 352, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dingku/jupyter_env/lib/python3.12/site-packages/accelerate/optimizer.py", line 185, in patched_step
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/optim/lr_scheduler.py", line 130, in wrapper
    return func.__get__(opt, opt.__class__)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/optim/optimizer.py", line 484, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/optim/optimizer.py", line 89, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/optim/adamw.py", line 227, in step
    adamw(
  File "/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/optim/optimizer.py", line 161, in maybe_fallback
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/optim/adamw.py", line 767, in adamw
    func(
  File "/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/optim/adamw.py", line 600, in _multi_tensor_adamw
    exp_avg_sq_sqrt = torch._foreach_sqrt(device_exp_avg_sqs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 15.89 GiB of which 17.38 MiB is free. Including non-PyTorch memory, this process has 15.87 GiB memory in use. Of the allocated memory 15.40 GiB is allocated by PyTorch, and 185.03 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [2]:
#!/usr/bin/env python3
"""
Fine-tune NLLB-200 for Manipuri (mni_Beng) using all training data.
"""

import os
import pandas as pd
from datasets import Dataset
from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    DataCollatorForSeq2Seq,
)
import torch

# ==================== CONFIGURATION ====================
DATA_DIR = "/home/dingku/Desktop/WMT26/WMT26/Cat1/"
MODEL_NAME = "facebook/nllb-200-distilled-600M"
OUTPUT_DIR = "/home/dingku/Desktop/finetuned_nllb_indic/Manipuri_Beng"

# Manipuri specific
LANG_CODE = "mni_Beng"          # Bengali script
FILE_NAME = "English-ManipuriTrainingData2026.xlsx"
TARGET_COL = "mni"              # column name in Excel

# Hyperparameters
BATCH_SIZE = 4
LEARNING_RATE = 2e-5
EPOCHS = 3
MAX_LENGTH = 128

# ==================== DATA LOADING ====================
def load_and_prepare_data():
    full_path = os.path.join(DATA_DIR, FILE_NAME)
    df = pd.read_excel(full_path)

    # Identify English column
    if 'en' in df.columns:
        eng_col = 'en'
    else:
        eng_candidates = [c for c in df.columns if 'english' in c.lower()]
        eng_col = eng_candidates[0] if eng_candidates else df.columns[0]

    # Rename to standard names
    df = df.rename(columns={eng_col: 'en', TARGET_COL: 'target'})
    df = df[['en', 'target']].dropna()
    df['en'] = df['en'].astype(str).str.strip()
    df['target'] = df['target'].astype(str).str.strip()
    df = df[(df['en'] != '') & (df['target'] != '')]

    # Add language prefixes
    df['source'] = "eng_Latn " + df['en']
    df['target'] = f"{LANG_CODE} " + df['target']

    print(f"Loaded {len(df)} valid pairs for Manipuri ({LANG_CODE})")
    return Dataset.from_dict({
        'source': df['source'].tolist(),
        'target': df['target'].tolist()
    })

# ==================== TOKENIZATION ====================
def tokenize_function(examples, tokenizer):
    tokenizer.src_lang = "eng_Latn"
    source_inputs = tokenizer(
        examples['source'],
        max_length=MAX_LENGTH,
        truncation=True,
        padding=False,
    )
    tokenizer.tgt_lang = LANG_CODE
    target_inputs = tokenizer(
        examples['target'],
        max_length=MAX_LENGTH,
        truncation=True,
        padding=False,
    )
    source_inputs['labels'] = target_inputs['input_ids']
    return source_inputs

# ==================== MAIN TRAINING ====================
def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # 1. Load data
    dataset = load_and_prepare_data()

    # 2. Load model and tokenizer
    print("Loading NLLB model & tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
    model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

    # 3. Tokenize dataset
    print("Tokenizing dataset...")
    tokenized_dataset = dataset.map(
        lambda x: tokenize_function(x, tokenizer),
        batched=True,
        remove_columns=dataset.column_names
    )

    # 4. Training arguments
    training_args = Seq2SeqTrainingArguments(
        output_dir=OUTPUT_DIR,
        evaluation_strategy="no",
        save_strategy="epoch",
        learning_rate=LEARNING_RATE,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        weight_decay=0.01,
        num_train_epochs=EPOCHS,
        predict_with_generate=True,
        generation_max_length=MAX_LENGTH,
        logging_dir=os.path.join(OUTPUT_DIR, 'logs'),
        logging_steps=50,
        save_total_limit=2,
        fp16=torch.cuda.is_available(),
        report_to="none",
    )

    # 5. Trainer
    data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)
    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset,
        tokenizer=tokenizer,
        data_collator=data_collator,
    )

    # 6. Train and save
    print("Starting training...")
    trainer.train()
    trainer.save_model(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    print(f"Model saved to {OUTPUT_DIR}")

if __name__ == "__main__":
    main()

Loaded 23687 valid pairs for Manipuri (mni_Beng)
Loading NLLB model & tokenizer...

/home/dingku/jupyter_env/lib/python3.12/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/modeling_utils.py:519: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(checkpoint_file, map_location=map_location)

Tokenizing dataset...

Map:   0%|          | 0/23687 [00:00<?, ? examples/s]

/home/dingku/jupyter_env/lib/python3.12/site-packages/accelerate/accelerator.py:439: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)
You're using a NllbTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

Starting training...

Model saved to /home/dingku/Desktop/finetuned_nllb_indic/Manipuri_Beng

In [2]:
#!/usr/bin/env python3
#Real-time translation using fine-tuned NLLB models for Assamese and Manipuri.
#Reads English sentences from Excel files, translates, displays progress, saves results.

import os
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from tqdm import tqdm
import time

# ============================================================
# CONFIGURATION
# ============================================================

# Paths to your fine-tuned models
MODEL_PATHS = {
    "asm": "/home/dingku/Desktop/finetuned_nllb_indic/Assamese",
    "mni": "/home/dingku/Desktop/finetuned_nllb_indic/Manipuri_Beng"
}

# Input Excel files
INPUT_FILES = {
    "asm": "/home/dingku/Desktop/WMT 2026 IndicMT Test Data/Category 1/English - Assamese/en-as Test.xlsx",
    "mni": "/home/dingku/Desktop/WMT 2026 IndicMT Test Data/Category 1/English - Manipuri/en-mni Test.xlsx"
}

# Output text files (saved on Desktop)
OUTPUT_FILES = {
    "asm": "/home/dingku/Desktop/translated_assamese.txt",
    "mni": "/home/dingku/Desktop/translated_manipuri.txt"
}

# Column name containing English sentences
EN_COL = "English Sentences"

# Device: use GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ============================================================
# LOAD MODELS
# ============================================================

def load_model(lang_code):
    """Load tokenizer and model for given language."""
    model_path = MODEL_PATHS[lang_code]
    print(f"\nLoading {lang_code.upper()} model from {model_path} ...")
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_path)
    model.to(device)
    model.eval()
    return tokenizer, model

# Load both models
tokenizers = {}
models = {}
for lang in ["asm", "mni"]:
    tok, mdl = load_model(lang)
    tokenizers[lang] = tok
    models[lang] = mdl

# ============================================================
# TRANSLATION FUNCTION
# ============================================================

def translate_sentences(lang_code, sentences, batch_size=8):
    """
    Translate a list of English sentences into the target language.
    Yields (original, translation) one by one for real-time display.
    """
    tokenizer = tokenizers[lang_code]
    model = models[lang_code]
    
    # Process in batches for efficiency, but yield after each sentence
    for i, sent in enumerate(tqdm(sentences, desc=f"Translating {lang_code.upper()}")):
        if not isinstance(sent, str) or not sent.strip():
            yield sent, ""
            continue
        
        # Tokenize
        inputs = tokenizer(sent, return_tensors="pt", truncation=True, max_length=512)
        inputs = {k: v.to(device) for k, v in inputs.items()}
        
        # Generate translation
        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_length=512,
                num_beams=4,
                early_stopping=True
            )
        translation = tokenizer.decode(outputs[0], skip_special_tokens=True)
        yield sent, translation

# ============================================================
# MAIN TRANSLATION LOOP
# ============================================================

def translate_and_save(lang_code, input_excel, output_txt):
    """Read Excel, translate each sentence, save results, show in real time."""
    print(f"\n{'='*60}")
    print(f"Processing {lang_code.upper()} translation")
    print(f"Input:  {input_excel}")
    print(f"Output: {output_txt}")
    print(f"{'='*60}\n")
    
    # Read Excel
    df = pd.read_excel(input_excel)
    if EN_COL not in df.columns:
        raise ValueError(f"Column '{EN_COL}' not found in {input_excel}")
    
    english_sentences = df[EN_COL].tolist()
    print(f"Total sentences to translate: {len(english_sentences)}")
    
    # Open output file
    with open(output_txt, "w", encoding="utf-8") as f_out:
        f_out.write(f"Translations from English to {lang_code.upper()}\n")
        f_out.write(f"Model: {MODEL_PATHS[lang_code]}\n")
        f_out.write("-" * 80 + "\n\n")
        
        # Translate one by one and display
        for idx, (orig, trans) in enumerate(translate_sentences(lang_code, english_sentences), start=1):
            # Real-time print to console
            print(f"\n[{idx}/{len(english_sentences)}]")
            print(f"EN: {orig}")
            print(f"{lang_code.upper()}: {trans}")
            print("-" * 50)
            
            # Write to file
            f_out.write(f"Original ({idx}): {orig}\n")
            f_out.write(f"Translated: {trans}\n")
            f_out.write("-" * 50 + "\n")
            f_out.flush()  # ensure immediate write
    
    print(f"\n✅ Translation saved to: {output_txt}")

# ============================================================
# RUN TRANSLATIONS
# ============================================================

if __name__ == "__main__":
    # Translate Assamese
    translate_and_save("asm", INPUT_FILES["asm"], OUTPUT_FILES["asm"])
    
    # Translate Manipuri
    translate_and_save("mni", INPUT_FILES["mni"], OUTPUT_FILES["mni"])
    
    print("\n🎉 All translations completed successfully!")

Using device: cuda

Loading ASM model from /home/dingku/Desktop/finetuned_nllb_indic/Assamese ...

Loading MNI model from /home/dingku/Desktop/finetuned_nllb_indic/Manipuri_Beng ...

============================================================
Processing ASM translation
Input:  /home/dingku/Desktop/WMT 2026 IndicMT Test Data/Category 1/English - Assamese/en-as Test.xlsx
Output: /home/dingku/Desktop/translated_assamese.txt
============================================================

Total sentences to translate: 1000

Translating ASM:   0%|                         | 1/1000 [00:00<09:12,  1.81it/s]

[1/1000]
EN: NDTV has learnt from sources that the T20 World Cup 2026 match between India and Pakistan is ON.
ASM: এনডিটিভিয়ে সূত্ৰৰ পৰা জানিব পাৰিছে যে ভাৰত আৰু পাকিস্তানৰ মাজত টি২০ বিশ্বকাপ ২০২৬ৰ মেচ অন ।
--------------------------------------------------

Translating ASM:   0%|                         | 2/1000 [00:00<07:13,  2.30it/s]

[2/1000]
EN: The PCB placed several demands before the ICC.
ASM: পিচবিটিয়ে আইচিচিৰ আগত কেইবাটাও দাবী দাখিল কৰিছিল ।
--------------------------------------------------

Translating ASM:   0%|                         | 3/1000 [00:01<07:59,  2.08it/s]

[3/1000]
EN: The PCB pushed for ICC intervention to facilitate a bilateral series between India and Pakistan.
ASM: ভাৰত আৰু পাকিস্তানৰ মাজত দ্বিপাক্ষিক শৃংখলাৰ বাবে আই চি চিৰ হস্তক্ষেপৰ বাবে পি চি বিয়ে হেঁচা দিছিল ।
--------------------------------------------------

Translating ASM:   0%|                         | 4/1000 [00:02<10:01,  1.66it/s]

[4/1000]
EN: Virat Kohli and Rohit Sharma have been demoted to Grade B in BCCI's central contract list for 2025-26.
ASM: বিটিচিআইৰ ২০২৫-২৬ বৰ্ষৰ কেন্দ্ৰীয় চুক্তিৰ তালিকাত বিৰাট কোহলী আৰু ৰোহিত শৰ্মাক গ্ৰেড বিলৈ নামানি দিয়া হৈছে ।
--------------------------------------------------

Translating ASM:   0%|▏                        | 5/1000 [00:02<10:08,  1.63it/s]

[5/1000]
EN: Thirty senior men's cricketers have been awarded central contracts, with the BCCI doing away with the A+ grade.
ASM: ৩০ জন জ্যেষ্ঠ পুৰুষ ক্ৰিকেটাৰক কেন্দ্ৰীয় চুক্তি প্ৰদান কৰা হৈছে, বি চি চি আইয়ে এ+ গ্ৰেডৰ পৰা আঁতৰি আছে ।
--------------------------------------------------

Translating ASM:   1%|▏                        | 6/1000 [00:03<09:55,  1.67it/s]

[6/1000]
EN: As per the 2024-25 BCCI contracts, any player in Grade A would receive Rs 5 crore annually.
ASM: ২০২৪-২৫ বি চি চি আই চুক্তি অনুসৰি গ্ৰেড এৰ যিকোনো খেলুৱৈয়ে বছৰি ৫ কোটি টকা লাভ কৰিব ।
--------------------------------------------------

Translating ASM:   1%|▏                        | 7/1000 [00:03<08:27,  1.96it/s]

[7/1000]
EN: Grade B players would get Rs 3 crore, while
ASM: গ্ৰেড বিৰ খেলুৱৈসকলে লাভ কৰিব ৩ কোটি টকা, আনহাতে
--------------------------------------------------

Translating ASM:   1%|▏                        | 8/1000 [00:04<07:15,  2.28it/s]

[8/1000]
EN: Grade C players would get Rs 1 crore.
ASM: চি গ্ৰেডৰ খেলুৱৈসকলে লাভ কৰিব ১ কোটি টকা ।
--------------------------------------------------

Translating ASM:   1%|▏                        | 9/1000 [00:04<08:22,  1.97it/s]

[9/1000]
EN: Earlier, Grade A+ players (Kohli, Rohit, Jasprit Bumrah, Ravindra Jadeja) used to receive Rs 7 crore.
ASM: ইয়াৰ পূৰ্বে গ্ৰেড এ+ খেলুৱৈ (কোহলি, ৰোহিত, যশপ্ৰীত বুমৰাহ, ৰবীন্দ্ৰ জাডেজা) সকলে ৭ কোটি টকা লাভ কৰিছিল ।
--------------------------------------------------

Translating ASM:   1%|▏                       | 10/1000 [00:05<08:52,  1.86it/s]

[10/1000]
EN: The BCCI has not yet officially declared whether the payment structure for 2025-26 will be any different.
ASM: বিচিচিআইয়ে এতিয়াও আনুষ্ঠানিকভাৱে ঘোষণা কৰা নাই যে ২০২৫-২৬ৰ বাবে পৰিশোধৰ গাঁথনি কিবা বেলেগ হ'ব নেকি ।
--------------------------------------------------

Translating ASM:   1%|▎                       | 11/1000 [00:05<07:58,  2.07it/s]

[11/1000]
EN: 21 women cricketers classified in Grade A, B and C.
ASM: গ্ৰেড এ, বি আৰু চিত শ্ৰেণীবদ্ধ ২১ গৰাকী মহিলা ক্ৰিকেটাৰ ।
--------------------------------------------------

Translating ASM:   1%|▎                       | 12/1000 [00:06<09:11,  1.79it/s]

[12/1000]
EN: Harmanpreet Kaur, Smriti Mandhana, Deepti Sharma and Jemimah Rodrigues are the four players to be included in Grade A.
ASM: গ্ৰেড এত অন্তৰ্ভুক্ত হবলগীয়া চাৰিগৰাকী খেলুৱৈ হল হৰমনপ্রীত কৌৰ, স্মৃতি মান্না, দীপ্তি শৰ্মা আৰু জেমিমা ৰড্ৰিগেছ ।
--------------------------------------------------

Translating ASM:   1%|▎                       | 13/1000 [00:06<08:33,  1.92it/s]

[13/1000]
EN: The cycle for new central contract is based on performance and volume of games played during the preceding season.
ASM: নতুন কেন্দ্ৰীয় চুক্তিৰ চক্র পূৰ্বৰ ছিজনত খেলা খেলৰ প্ৰদৰ্শন আৰু পৰিমাণৰ ওপৰত আধাৰিত ।
--------------------------------------------------

Translating ASM:   1%|▎                       | 14/1000 [00:07<08:02,  2.05it/s]

[14/1000]
EN: Pakistan and Bangladesh's demands from the International Cricket Council (ICC) have just grown bigger.
ASM: আন্তঃৰাষ্ট্ৰীয় ক্ৰিকেট পৰিষদ (আইচিচি) ৰ পৰা পাকিস্তান আৰু বাংলাদেশৰ দাবী মাত্ৰ ডাঙৰ হৈছে ।
--------------------------------------------------

Translating ASM:   2%|▎                       | 15/1000 [00:07<07:05,  2.31it/s]

[15/1000]
EN: The 2031 edition of the ODI World Cup is set to be played in India and Bangladesh.
ASM: ভাৰত আৰু বাংলাদেশত ২০৩১ চনত অনুষ্ঠিত হবলগীয়া এদিনীয়া বিশ্বকাপ ।
--------------------------------------------------

Translating ASM:   2%|▍                       | 16/1000 [00:07<06:24,  2.56it/s]

[16/1000]
EN: At present, the hybrid model is applicable until 2027.
ASM: বৰ্তমান এই হাইব্ৰীড মডেলটো ২০২৭ লৈকে প্ৰযোজ্য ।
--------------------------------------------------

Translating ASM:   2%|▍                       | 17/1000 [00:08<06:17,  2.61it/s]

[17/1000]
EN: The extension would allow Bangladesh and Pakistan to play all their matches in Bangladesh and not India.
ASM: এই সম্প্ৰসাৰণৰ ফলত বাংলাদেশ আৰু পাকিস্তানে তেওঁলোকৰ সকলো মেচ বাংলাদেশত খেলিব পাৰিব আৰু ভাৰতত নহয় ।
--------------------------------------------------

Translating ASM:   2%|▍                       | 18/1000 [00:08<07:20,  2.23it/s]

[18/1000]
EN: The BCB was represented by its head Aminul Islam Bulbul while PCB chairman Mohsin Naqvi was also present.
ASM: বি চি বিৰ প্ৰতিনিধি আছিল ইয়াৰ মুৰব্বী আমিনুল ইছলাম বুলবুল আৰু পি চি বিৰ অধ্যক্ষ মোহচিন নকভিও উপস্থিত আছিল ।
--------------------------------------------------

Translating ASM:   2%|▍                       | 19/1000 [00:09<06:35,  2.48it/s]

[19/1000]
EN: ICC's deputy chairman Imran Khawaja was present in the meeting.
ASM: বৈঠকত আই চি চিৰ উপাধ্যক্ষ ইমৰান খোৱাজা উপস্থিত আছিল ।
--------------------------------------------------

Translating ASM:   2%|▍                       | 20/1000 [00:09<06:11,  2.64it/s]

[20/1000]
EN: No joint declaration was issued after the four-hour meeting.
ASM: চাৰি ঘণ্টীয়া বৈঠকৰ পাছত কোনো যুটীয়া ঘোষণাপত্ৰ জাৰী কৰা হোৱা নাছিল ।
--------------------------------------------------

Translating ASM:   2%|▌                       | 21/1000 [00:09<06:59,  2.33it/s]

[21/1000]
EN: The hybrid model arrangement was introduced after India refused to tour Pakistan for the 2025 Champions Trophy.
ASM: ভাৰতে ২০২৫ৰ চেম্পিয়নছ ট্ৰফীৰ বাবে পাকিস্তান ভ্ৰমণ কৰিবলৈ অস্বীকাৰ কৰাৰ পিছত হাইব্ৰীড মডেল ব্যৱস্থাটো প্ৰৱৰ্তন কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:   2%|▌                       | 22/1000 [00:10<06:28,  2.52it/s]

[22/1000]
EN: After extensive negotiations, a hybrid model was accepted by all parties, including the ICC.
ASM: ব্যাপক আলোচনাৰ পিছত আইচিচিকে ধৰি সকলো পক্ষই হাইব্ৰীড মডেল গ্ৰহণ কৰে ।
--------------------------------------------------

Translating ASM:   2%|▌                       | 23/1000 [00:10<06:32,  2.49it/s]

[23/1000]
EN: The second part of the arrangement states that Pakistan will not travel to India for the 2026 T20 World Cup.
ASM: ব্যৱস্থাৰ দ্বিতীয় অংশত কোৱা হৈছে যে ২০২৬ৰ টি২০ বিশ্বকাপৰ বাবে পাকিস্তান ভাৰতলৈ নাযাব ।
--------------------------------------------------

Translating ASM:   2%|▌                       | 24/1000 [00:11<06:46,  2.40it/s]

[24/1000]
EN: As a result, all of Pakistan's matches (even if they reach the final) will be played in Sri Lanka.
ASM: ফলস্বৰূপে পাকিস্তানৰ সকলো মেচ (যদিও তেওঁলোকে ফাইনেলত প্ৰৱেশ কৰে) শ্ৰীলংকাত খেলা হব ।
--------------------------------------------------

Translating ASM:   2%|▌                       | 25/1000 [00:11<05:54,  2.75it/s]

[25/1000]
EN: Bangladesh, Pakistan, and India must be treated the same.
ASM: বাংলাদেশ, পাকিস্তান আৰু ভাৰতক একেদৰেই ব্যৱহাৰ কৰা উচিত ।
--------------------------------------------------

Translating ASM:   3%|▌                       | 26/1000 [00:11<05:41,  2.85it/s]

[26/1000]
EN: Now, Gavaskar has taken an indirect jibe at Hussain
ASM: এতিয়া হুছেইনৰ ওপৰত পৰোক্ষভাৱে গৱেষণা কৰিছে গাভাষ্কাৰে ।
--------------------------------------------------

Translating ASM:   3%|▋                       | 27/1000 [00:12<06:50,  2.37it/s]

[27/1000]
EN: He went on to give the example of the 2003 World Cup, when England refused to tour Zimbabwe in protest against Robert Mugabe's regime.
ASM: তেওঁ ২০০৩ চনত ইংলেণ্ডে ৰবাৰ্ট মুগাবেৰ শাসনৰ প্ৰতিবাদত জিম্বাবুৱে ভ্ৰমণ কৰিবলৈ অস্বীকাৰ কৰা বিশ্বকাপৰ উদাহৰণ দাঙি ধৰিলে ।
--------------------------------------------------

Translating ASM:   3%|▋                       | 28/1000 [00:12<06:41,  2.42it/s]

[28/1000]
EN: Samson's knock was full of intent but fell short in effectiveness quotient.
ASM: চিম্চোনৰ ধাক্কা উদ্দেশ্যৰে পৰিপূৰ্ণ আছিল কিন্তু কাৰ্যকৰীতা অনুপাতত কম আছিল ।
--------------------------------------------------

Translating ASM:   3%|▋                       | 29/1000 [00:13<07:02,  2.30it/s]

[29/1000]
EN: With this win, India overtook Pakistan at the summit of Group A courtesy of a superior net run-rate.
ASM: এই বিজয়ৰ জৰিয়তে ভাৰতে শ্ৰেষ্ঠ নেট ৰান ৰেটৰ সৌজন্যত গ্ৰুপ এৰ শীৰ্ষত পাকিস্তানক পিছ পেলাইছিল ।
--------------------------------------------------

Translating ASM:   3%|▋                       | 30/1000 [00:13<07:59,  2.02it/s]

[30/1000]
EN: India batter Abhishek Sharma will take no part in the T20 World Cup 2026 clash against Namibia in New Delhi on Thursday.
ASM: বৃহস্পতিবাৰে নতুন দিল্লীত নামিবিয়াৰ বিৰুদ্ধে অনুষ্ঠিত হবলগীয়া টি২০ বিশ্বকাপ ২০২৬ৰ সংঘৰ্ষত অংশ লব নোৱাৰিব ভাৰতীয় বেটাৰ অভিষেক শৰ্মা ।
--------------------------------------------------

Translating ASM:   3%|▊                       | 32/1000 [00:14<05:39,  2.85it/s]

[31/1000]
EN: Abhishek isn't fine still, might take one or two games.
ASM: অভিষেক এতিয়াও ভাল নহয়, এটা বা দুটা মেচ লাগিব পাৰে ।
--------------------------------------------------

[32/1000]
EN: Samson comes in.
ASM: চিম্চোন ভিতৰলৈ আহিল ।
--------------------------------------------------

Translating ASM:   3%|▊                       | 33/1000 [00:14<05:30,  2.93it/s]

[33/1000]
EN: Bumrah comes in for Siraj," said Suryakumar at the toss.
ASM: ছিৰাজৰ বাবে বুমৰাহ আহে, টছত সূৰ্যকুমাৰে কয় ।
--------------------------------------------------

Translating ASM:   3%|▊                       | 34/1000 [00:15<06:11,  2.60it/s]

[34/1000]
EN: Defending with dew will build our confidence. Hope our batters entertain the crowd.
ASM: বৰষুণেৰে সুৰক্ষা দিয়াটোৱে আমাৰ আত্মবিশ্বাস গঢ়ি তুলিব । আশা কৰো আমাৰ বেটাৰসকলে ভিৰটোক মনোৰঞ্জন দিব ।
--------------------------------------------------

Translating ASM:   4%|▊                       | 35/1000 [00:15<05:45,  2.79it/s]

[35/1000]
EN: It's a big tournament, dew will be a big factor.
ASM: ই এটা ডাঙৰ টুৰ্ণামেণ্ট, বৰষুণ এটা ডাঙৰ কাৰক হ'ব ।
--------------------------------------------------

Translating ASM:   4%|▊                       | 36/1000 [00:15<06:00,  2.68it/s]

[36/1000]
EN: India made two changes to the side that beat the USA on the opening day of the tournament.
ASM: টুৰ্ণামেণ্টৰ উদ্বোধনী দিনা আমেৰিকা যুক্তৰাষ্ট্ৰক পৰাস্ত কৰা দলটোৰ দুটা পৰিৱৰ্তন কৰিলে ভাৰতে ।
--------------------------------------------------

Translating ASM:   4%|▉                       | 37/1000 [00:16<06:49,  2.35it/s]

[37/1000]
EN: Sanju Samson replaced Abhishek, while Jasprit Bumrah replaced Mohammed Siraj in the India XI.
ASM: ভাৰতীয় একাদশত সংজু চিমছনে অভিষেকৰ স্থান লয়, আনহাতে যশপ্ৰীত বুমৰাহে মহম্মদ চিৰাজৰ স্থান লয় ।
--------------------------------------------------

Translating ASM:   4%|▉                       | 38/1000 [00:16<06:59,  2.29it/s]

[38/1000]
EN: India take on Pakistan next, with the team set to travel to Colombo for the game on February 15.
ASM: ভাৰতে পৰৱৰ্তী সময়ত পাকিস্তানৰ বিৰুদ্ধে খেলিব আৰু দলটোৱে ১৫ ফেব্ৰুৱাৰীত খেলৰ বাবে কলম্বোৰ ভ্ৰমণ কৰিব ।
--------------------------------------------------

Translating ASM:   4%|▉                       | 39/1000 [00:17<06:27,  2.48it/s]

[39/1000]
EN: The cabinet agreed with certain conditions as per the Cunha report.
ASM: কুনহা প্ৰতিবেদনৰ অনুসৰি কেবিনেটে কিছুমান চৰ্তত সন্মতি প্ৰকাশ কৰে ।
--------------------------------------------------

Translating ASM:   4%|▉                       | 40/1000 [00:17<05:56,  2.69it/s]

[40/1000]
EN: He mentioned in the report a maximum of 35,000 people and other conditions.
ASM: তেওঁ প্ৰতিবেদনত সৰ্বাধিক ৩৫ হাজাৰ লোক আৰু অন্যান্য পৰিস্থিতিৰ কথা উল্লেখ কৰে ।
--------------------------------------------------

Translating ASM:   4%|▉                       | 41/1000 [00:17<06:51,  2.33it/s]

[41/1000]
EN: India reached the 100-run mark in just 6.5 overs - the fastest team hundred in T20 World Cup history.
ASM: মাত্ৰ ৬.৫ অভাৰতত ১০০ৰানৰ লক্ষ্যত উপনীত ভাৰত- টি২০ বিশ্বকাপৰ ইতিহাসত সৰ্ব্বোচ্চ দ্ৰুতগামী দল শতক ।
--------------------------------------------------

Translating ASM:   4%|█                       | 42/1000 [00:18<06:45,  2.36it/s]

[42/1000]
EN: After being asked to bat first, India were off to a decent start, making 8/0 in the first over.
ASM: প্ৰথমে বেটিং কৰিবলৈ কোৱা হোৱাৰ পিছত প্ৰথম ওভাৰত ৮-০ গৰাকী কৰি শলাগ লৈছিল ভাৰতে ।
--------------------------------------------------

Translating ASM:   4%|█                       | 43/1000 [00:18<07:11,  2.22it/s]

[43/1000]
EN: After four overs, the defending champions reached 43/1, with Ishan Kishan finding a couple of boundaries.
ASM: চাৰি অভাৰৰ পিছত প্ৰতিদ্বন্দ্বী চেম্পিয়নসকলে ৪৩/১ত উপনীত হোৱাৰ লগতে ঈশান কিশনে দুটা সীমা বিচাৰি উলিয়ালে ।
--------------------------------------------------

Translating ASM:   4%|█                       | 44/1000 [00:19<07:59,  1.99it/s]

[44/1000]
EN: On the first ball of the 11th over, spinner Bernard Scholtz dismissed captain Suryakumar Yadav for just 12.
ASM: ১১তম ওভাৰৰ প্ৰথমটো বলত স্পিনাৰ বাৰ্ণাৰ্ড শলটেছে মাত্ৰ ১২ টাৰ বাবে অধিনায়ক সূৰ্যকুমাৰ যাদৱক নিলম্বন কৰিলে ।
--------------------------------------------------

Translating ASM:   4%|█                       | 45/1000 [00:20<08:53,  1.79it/s]

[45/1000]
EN: India lost another wicket quickly when Tilak Varma was removed for 25 by Namibia skipper Erasmus in the 12th over.
ASM: নামিবিয়াৰ অধিনায়ক ইৰেছামছে দ্বাদশ ওভাৰত ২৫ ৰানত তিলক বৰ্মাক আঁতৰ কৰাত ভাৰতে দ্ৰুতভাৱে আন এটা উইকেট হেৰুৱালে ।
--------------------------------------------------

Translating ASM:   5%|█                       | 46/1000 [00:20<09:31,  1.67it/s]

[46/1000]
EN: Shivam Dube and Hardik Pandya then combined to hammer 24 runs off Bernard Scholtz as India raced to 168/4.
ASM: শিৱম ডুবে আৰু হাৰ্দিক পাণ্ডিয়াই তাৰ পিছত সংযুক্ত হৈ বাৰ্ণাৰ্ড শোল্টচৰ পৰা ২৪ ৰান হেমাৰ কৰিছিল কিয়নো ভাৰতে ১৬৮/৪ লৈ দৌৰিছিল ।
--------------------------------------------------

Translating ASM:   5%|█▏                      | 47/1000 [00:21<08:40,  1.83it/s]

[47/1000]
EN: By the end of the 18th over, India had reached 199/4 with Pandya and Dube going strong.
ASM: ১৮তম ওভাৰৰ শেষত পণ্ডিয়া আৰু দুবে শক্তিশালী হৈ ১৯৯/৪ত উপনীত হৈছিল ভাৰতে ।
--------------------------------------------------

Translating ASM:   5%|█▏                      | 48/1000 [00:21<08:57,  1.77it/s]

[48/1000]
EN: On the first ball of the 19th over, Pandya completed his fifty off 27 deliveries as India crossed the 200-run mark.
ASM: ১৯তম ওভাৰৰ প্ৰথম বলত পণ্ডিয়াই ২৭টা ডেলিভাৰীৰে নিজৰ পঞ্চাশটা সমাপ্তি অৰ্জন কৰাৰ লগে লগে ভাৰতে ২০০ৰান অতিক্ৰম কৰে ।
--------------------------------------------------

Translating ASM:   5%|█▏                      | 49/1000 [00:22<08:13,  1.93it/s]

[49/1000]
EN: Shivam Dube was run out for 23 after a mix-up with Rinku Singh.
ASM: ৰিংকু সিঙৰ সৈতে মিশ্ৰণৰ পিছত শিৱম দুবে ২৩ ৰান আউট ।
--------------------------------------------------

Translating ASM:   5%|█▏                      | 50/1000 [00:22<08:29,  1.86it/s]

[50/1000]
EN: India then lost Rinku Singh (1) and Arshdeep Singh (2) in the final over, finishing at 209/9.
ASM: ইয়াৰ পিছত ভাৰতে ৰিংকু সিং (১ ) আৰু অৰ্জ্জ্বীপ সিঙ (২ )ক ফাইনেল ওভাৰত পৰাস্ত কৰি ২০৯/৯ত শেষ কৰে ।
--------------------------------------------------

Translating ASM:   5%|█▏                      | 51/1000 [00:23<10:11,  1.55it/s]

[51/1000]
EN: ICC Men’s T20 World Cup 2026 began on February 7, 2026, at Sinhalese Sports Club Ground with Pakistan playing Netherlands in the opening match.
ASM: আই চি চি পুৰুষৰ টি২০ বিশ্বকাপ ২০২৬ৰ আৰম্ভণি ৭ ফেব্ৰুৱাৰী ২০২৬ত ছিংগালাইজ স্পৰ্টছ ক্লাব গ্ৰাউণ্ডত আৰম্ভ হয় আৰু মুকলি মেচত নেদাৰলেণ্ডছৰ বিৰুদ্ধে খেলিছিল পাকিস্তানে ।
--------------------------------------------------

Translating ASM:   5%|█▏                      | 52/1000 [00:24<10:10,  1.55it/s]

[52/1000]
EN: Bangladesh national cricket team faced the India men's national cricket team in an opening match reported ahead of the 2026 T20 tournament.
ASM: ২০২৬ৰ টি২০ টুৰ্ণামেণ্টৰ পূৰ্বেই ৰিপৰ্ট কৰা মুকলি মেচত বাংলাদেশ ৰাষ্ট্ৰীয় ক্ৰিকেট দলে মুখামুখি হল ভাৰতীয় পুৰুষ ৰাষ্ট্ৰীয় ক্ৰিকেট দলৰ বিৰুদ্ধে ।
--------------------------------------------------

Translating ASM:   5%|█▎                      | 53/1000 [00:24<08:30,  1.86it/s]

[53/1000]
EN: Ishan Kishan struck a rapid half-century.
ASM: ইচন কিষণে দ্ৰুতভাৱে অৰ্ধশতক অৰ্জন কৰে ।
--------------------------------------------------

Translating ASM:   5%|█▎                      | 54/1000 [00:25<08:43,  1.81it/s]

[54/1000]
EN: Faf du Plessis scored a half-century and Mitchell Starc took a five-wicket haul in the same match report.
ASM: ফেফ ডু প্লেছিছে অৰ্ধশতক অৰ্জন কৰে আৰু মিচেল ষ্টাৰ্কে একেটা মেচৰ ৰিপৰ্টত পাঁচ উইকেট দখল কৰে ।
--------------------------------------------------

Translating ASM:   6%|█▎                      | 55/1000 [00:25<08:42,  1.81it/s]

[55/1000]
EN: Jasprit Bumrah and Ravindra Jadeja were reported to have been demoted in the 2025–26 central contracts discussion.
ASM: ২০২৫২৬ চনৰ কেন্দ্ৰীয় চুক্তিৰ আলোচনাত যশপ্ৰিত বুমৰাহ আৰু ৰবীন্দ্ৰ জাডেজাক নিম্নগামী কৰা বুলি কোৱা হৈছিল ।
--------------------------------------------------

Translating ASM:   6%|█▎                      | 56/1000 [00:26<07:55,  1.98it/s]

[56/1000]
EN: Rohit Sharma carried the men’s T20 World Cup trophy during a promotional appearance.
ASM: প্ৰচাৰৰ সময়ত পুৰুষৰ টি২০ বিশ্বকাপ ট্ৰফী কঢ়িয়াই নিলে ৰোহিত শৰ্মাই ।
--------------------------------------------------

Translating ASM:   6%|█▎                      | 57/1000 [00:26<08:31,  1.84it/s]

[57/1000]
EN: The International Cricket Council update said a high-profile match involving Pakistan would go ahead on February 15, 2026, in Colombo.
ASM: আন্তঃৰাষ্ট্ৰীয় ক্ৰিকেট পৰিষদৰ আপডেটে কৈছে যে পাকিস্তান জড়িত থকা এক উচ্চ প্ৰফাইলৰ খেল ২০২৬ চনৰ ১৫ ফেব্ৰুৱাৰীত কলম্বোত অনুষ্ঠিত হ'ব ।
--------------------------------------------------

Translating ASM:   6%|█▍                      | 58/1000 [00:27<08:00,  1.96it/s]

[58/1000]
EN: The New Zealand national cricket team lost the first ODI by four wickets to the India men's national cricket team.
ASM: প্ৰথম এদিনীয়াত চাৰি উইকেটত পৰাস্ত নিউজিলেণ্ডৰ ৰাষ্ট্ৰীয় ক্ৰিকেট দল ভাৰতীয় পুৰুষ ৰাষ্ট্ৰীয় ক্ৰিকেট দলৰ হাতত ।
--------------------------------------------------

Translating ASM:   6%|█▍                      | 59/1000 [00:27<08:25,  1.86it/s]

[59/1000]
EN: Australia national cricket team ended day one at 67 for seven in reply to 150 by the India men's national cricket team in a Test match post.
ASM: টেষ্ট মেচ পষ্টত ভাৰতীয় পুৰুষ ৰাষ্ট্ৰীয় ক্ৰিকেট দলৰ ১৫০ ৰ উত্তৰত সাতাৰৰ বিপৰীতে ৬৭ত এদিনীয়া শেষ অষ্ট্ৰেলিয়াৰ ৰাষ্ট্ৰীয় ক্ৰিকেট দল ।
--------------------------------------------------

Translating ASM:   6%|█▍                      | 60/1000 [00:28<09:27,  1.66it/s]

[60/1000]
EN: The India national under-19 cricket team won the ICC U19 World Cup final by 100 runs against the England national under-19 cricket team in Harare.
ASM: হাৰাৰেত ইংলেণ্ডৰ ৰাষ্ট্ৰীয় ১৯ অনূৰ্ধ্ব ক্ৰিকেট দলৰ বিৰুদ্ধে ১০০ ৰানত আই চি চি অনূৰ্ধ্ব ১৯ বিশ্বকাপৰ ফাইনেলত জয় ভাৰতৰ ৰাষ্ট্ৰীয় ১৯ অনূৰ্ধ্ব ক্ৰিকেট দল ।
--------------------------------------------------

Translating ASM:   6%|█▍                      | 61/1000 [00:29<08:41,  1.80it/s]

[61/1000]
EN: Members of the India women's national cricket team were given a grand welcome after their title-winning campaign.
ASM: ভাৰতীয় মহিলা ৰাষ্ট্ৰীয় ক্ৰিকেট দলৰ সদস্যসকলক তেওঁলোকৰ খিতাপ বিজয়ী অভিযানৰ পিছত আকৰ্ষণীয় আদৰণি জনোৱা হয় ।
--------------------------------------------------

Translating ASM:   6%|█▍                      | 62/1000 [00:29<08:15,  1.89it/s]

[62/1000]
EN: The India women's national cricket team lifting the ICC Women’s World Cup as one of the year’s landmark moments.
ASM: আই চি চি মহিলা বিশ্বকাপ উত্তোলন ভাৰতীয় মহিলা ৰাষ্ট্ৰীয় ক্ৰিকেট দলৰ এবছৰৰ অন্যতম ঐতিহাসিক মুহূৰ্ত হিচাপে বিবেচিত হৈছে ।
--------------------------------------------------

Translating ASM:   6%|█▌                      | 63/1000 [00:30<08:53,  1.76it/s]

[63/1000]
EN: The Indian Premier League season in 2025 was reported as suspended indefinitely amid escalating India–Pakistan military tensions.
ASM: ভাৰত-পাকিস্তানৰ মাজত বৃদ্ধি হোৱা সামৰিক উত্তেজনাৰ মাজত ২০২৫ চনত ইণ্ডিয়ান প্ৰিমিয়াৰ লীগ ছিজন অনিৰ্দিষ্টকালৰ বাবে স্থগিত ৰখা বুলি ৰিপৰ্ট কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:   6%|█▌                      | 64/1000 [00:30<08:12,  1.90it/s]

[64/1000]
EN: The Eden Gardens hosted the opening spectacle for the 18th edition of the Indian Premier League.
ASM: ইণ্ডিয়ান প্ৰিমিয়াৰ লীগৰ ১৮ সংখ্যক সংস্কৰণৰ উদ্বোধনী অনুষ্ঠান ইডেন গাৰ্ডেনছত অনুষ্ঠিত হয় ।
--------------------------------------------------

Translating ASM:   6%|█▌                      | 65/1000 [00:31<08:34,  1.82it/s]

[65/1000]
EN: Royal Challengers Bengaluru named Rajat Patidar as captain for the season starting March 21.
ASM: ২১ মাৰ্চৰ পৰা আৰম্ভ হবলগীয়া ছিজনটোৰ বাবে ৰয়েল চেলেঞ্জাৰ্ছ বেংগালুৰুয়ে ৰাজত পাটিদাৰক অধিনায়ক হিচাপে নিযুক্তি দিছে ।
--------------------------------------------------

Translating ASM:   7%|█▌                      | 66/1000 [00:31<08:46,  1.77it/s]

[66/1000]
EN: Chennai Super Kings posted their lowest home total and suffered a fifth straight loss.
ASM: চেন্নাই চুপাৰ কিংছে নিজৰ সৰ্বনিম্ন ঘৰুৱা সৰ্বমুঠ ৰেকৰ্ড দাঙি ধৰিছে আৰু একেৰাহে পঞ্চমটো পৰাস্ত হৈছে ।
--------------------------------------------------

Translating ASM:   7%|█▌                      | 67/1000 [00:32<08:37,  1.80it/s]

[67/1000]
EN: A Dharamsala fixture involving Punjab Kings and Delhi Capitals was called off after a blackout.
ASM: ব্লেকআউটৰ পিছত পঞ্জাৱ কিংছ আৰু দিল্লী কেপিটেলছৰ সৈতে জড়িত ধৰ্মশালা ফিক্সচাৰ বাতিল কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:   7%|█▋                      | 68/1000 [00:32<08:11,  1.90it/s]

[68/1000]
EN: Punjab Kings defeated Mumbai Indians in Jaipur to secure a top-two league finish.
ASM: জয়পুৰত মুম্বাই ইণ্ডিয়ানছক পৰাস্ত পঞ্জাৱ কিংছে টপ টু লীগ ফাইনেল নিশ্চিত কৰিলে ।
--------------------------------------------------

Translating ASM:   7%|█▋                      | 69/1000 [00:33<07:43,  2.01it/s]

[69/1000]
EN: KL Rahul became the fastest Indian to 8,000 T20 runs after an unbeaten 112.
ASM: অপৰাজেয় ১১২ ৰানৰ পিছত ৮০০০ টি২০ ৰানত বেগী ভাৰতীয় হৈ পৰিছিল কে এল ৰাহুল ।
--------------------------------------------------

Translating ASM:   7%|█▋                      | 70/1000 [00:33<07:26,  2.08it/s]

[70/1000]
EN: Virat Kohli spoke about the June 4 stampede linked to his franchise’s celebrations.
ASM: বিৰাট কোহলীয়ে তেওঁৰ ফ্ৰাঞ্চাইচিৰ উদযাপনৰ সৈতে জড়িত ৪ জুনৰ ধুমুহাৰ কথা কৈছিল ।
--------------------------------------------------

Translating ASM:   7%|█▋                      | 71/1000 [00:34<07:30,  2.06it/s]

[71/1000]
EN: The uncertainty over player retention created suspense ahead of the next Indian Premier League season.
ASM: খেলুৱৈৰ ধাৰণৰ ওপৰত অনিশ্চয়তাই পৰৱৰ্তী ইণ্ডিয়ান প্ৰিমিয়াৰ লীগ ছিজনৰ পূৰ্বে উত্তেজনা সৃষ্টি কৰিছিল ।
--------------------------------------------------

Translating ASM:   7%|█▋                      | 72/1000 [00:34<06:33,  2.36it/s]

[72/1000]
EN: Rafael Nadal announced he would retire.
ASM: ৰাফায়েল নাডালে ঘোষণা কৰিলে যে তেওঁ অৱসৰ লব ।
--------------------------------------------------

Translating ASM:   7%|█▊                      | 73/1000 [00:35<06:46,  2.28it/s]

[73/1000]
EN: Carlos Alcaraz beat Novak Djokovic to win his first major title.
ASM: কাৰ্লছ অলকাৰাজে নোভাক জকভিচক পৰাস্ত কৰি নিজৰ প্ৰথমটো মুখ্য খিতাপ অৰ্জন কৰে ।
--------------------------------------------------

Translating ASM:   7%|█▊                      | 74/1000 [00:35<07:07,  2.17it/s]

[74/1000]
EN: Alexander Zverev lost a marathon match to Carlos Alcaraz in a five-set battle.
ASM: পাঁচ ছেট যুঁজত কাৰ্লছ অলকাৰাজৰ হাতত মাৰাথন মেচত পৰাস্ত আলেকজেণ্ডাৰ জভেৰেভ ।
--------------------------------------------------

Translating ASM:   8%|█▊                      | 75/1000 [00:35<06:23,  2.41it/s]

[75/1000]
EN: Rohan Bopanna announced his retirement from professional tennis.
ASM: বৃত্তিগত টেনিছৰ পৰা অৱসৰ ঘোষণা ৰোহন বোপান্নাৰ ।
--------------------------------------------------

Translating ASM:   8%|█▊                      | 76/1000 [00:36<06:43,  2.29it/s]

[76/1000]
EN: A 14-place leap that signaled an upswing for India Davis Cup team in international tennis standings.
ASM: আন্তঃৰাষ্ট্ৰীয় টেনিছ শৃংখলাত ভাৰতৰ ডেভিছ কাপ দলৰ বাবে ১৪টা স্থানৰ জঁপিয়াই উঠাৰ সংকেত ।
--------------------------------------------------

Translating ASM:   8%|█▊                      | 77/1000 [00:36<07:21,  2.09it/s]

[77/1000]
EN: Elena Rybakina overcame Aryna Sabalenka to win the 2026 Australian Open final.
ASM: ২০২৬ চনৰ অষ্ট্ৰেলিয়ান অপেনৰ ফাইনেলত বিজয়ী হবলৈ এলেনা ৰিবাকিনাই আৰিনা চাবালেনকাক পৰাস্ত কৰিলে ।
--------------------------------------------------

Translating ASM:   8%|█▊                      | 78/1000 [00:37<07:38,  2.01it/s]

[78/1000]
EN: Novak Djokovic became the first player to reach 400 Grand Slam singles match wins in the Open Era.
ASM: নোভাক জকোভিচ হৈছে ওপেন এৰাত ৪০০ গ্ৰেণ্ড চ্লেম ছিংগলছ মেচত জয়ী হোৱা প্ৰথমগৰাকী খেলুৱৈ ।
--------------------------------------------------

Translating ASM:   8%|█▉                      | 79/1000 [00:37<07:18,  2.10it/s]

[79/1000]
EN: The India men's national field hockey team and its Olympic bronze-medal campaign in a dedicated post.
ASM: সমৰ্পিত পদত ভাৰতীয় পুৰুষ ৰাষ্ট্ৰীয় ফিল্ড হকী দল আৰু ইয়াৰ অলিম্পিক ব্ৰঞ্জৰ পদক প্ৰচাৰ ।
--------------------------------------------------

Translating ASM:   8%|█▉                      | 80/1000 [00:38<06:16,  2.44it/s]

[80/1000]
EN:  The India men's national field hockey team across major tournaments.
ASM: প্ৰধান প্ৰতিযোগিতাসমূহত ভাৰতীয় পুৰুষ ৰাষ্ট্ৰীয় ফিল্ড হকী দল ।
--------------------------------------------------

Translating ASM:   8%|█▉                      | 81/1000 [00:38<06:52,  2.23it/s]

[81/1000]
EN: The India men's national field hockey team beat South Korea men's national field hockey team 4–1 in a match update.
ASM: মেচ আপডেটত দক্ষিণ কোৰিয়াৰ পুৰুষৰ ৰাষ্ট্ৰীয় ফিল্ড হকী দলক ৪-১ গলত পৰাস্ত ভাৰতীয় পুৰুষৰ ৰাষ্ট্ৰীয় ফিল্ড হকী দল ।
--------------------------------------------------

Translating ASM:   8%|█▉                      | 82/1000 [00:39<06:31,  2.35it/s]

[82/1000]
EN: The house of K. D. Singh Babu would be developed as a tourist attraction.
ASM: কে ডি সিং বাবুৰ ঘৰটো পৰ্যটকৰ আকৰ্ষণ হিচাপে বিকশিত কৰা হব ।
--------------------------------------------------

Translating ASM:   8%|█▉                      | 83/1000 [00:39<05:44,  2.67it/s]

[83/1000]
EN: Lakshya Sen finished fourth in a tournament.
ASM: এখন টুৰ্ণামেণ্টত চতুৰ্থ স্থান লাভ লক্ষ্য সেনৰ ।
--------------------------------------------------

Translating ASM:   8%|██                      | 84/1000 [00:39<05:31,  2.76it/s]

[84/1000]
EN: Saina Nehwal confirmed her retirement from competitive badminton.
ASM: প্ৰতিযোগিতামূলক বেডমিণ্টনৰ পৰা অৱসৰ নিশ্চিত চাইনা নেহৱালৰ ।
--------------------------------------------------

Translating ASM:   8%|██                      | 85/1000 [00:39<05:27,  2.80it/s]

[85/1000]
EN: R. Vaishali won the FIDE Women’s Grand Swiss.
ASM: এফআইডিই মহিলা গ্ৰেণ্ড ছুইজাৰলেণ্ডৰ বিজয়ী আৰ বৈশালীৰ ।
--------------------------------------------------

Translating ASM:   9%|██                      | 86/1000 [00:40<05:10,  2.94it/s]

[86/1000]
EN: R. Praggnanandhaa came from behind to win a game.
ASM: এটা মেচ জয় কৰিবলৈ পিছফালৰ পৰা আহিছিল আৰ.প্ৰাগ্নানন্দ ।
--------------------------------------------------

Translating ASM:   9%|██                      | 87/1000 [00:40<04:55,  3.09it/s]

[87/1000]
EN: D. Gukesh as the youngest world chess champion in history.
ASM: ইতিহাসৰ কনিষ্ঠতম বিশ্ব চেম্পিয়ন হিচাপে ডি গুকেশ ।
--------------------------------------------------

Translating ASM:   9%|██                      | 88/1000 [00:40<05:13,  2.91it/s]

[88/1000]
EN: D. Gukesh secured his first win at Tata Steel Chess Masters 2026.
ASM: টাটা ষ্টীল চেছ মাষ্টাৰ্ছ ২০২৬ত ডি গুকেশে নিজৰ প্ৰথমটো জয় নিশ্চিত কৰে ।
--------------------------------------------------

Translating ASM:   9%|██▏                     | 89/1000 [00:41<06:37,  2.29it/s]

[89/1000]
EN: Avinash Sable became the first Indian man to qualify for the men’s 3000m steeplechase final at Paris Olympics 2024.
ASM: ২০২৪ চনৰ পেৰিছ অলিম্পিকত পুৰুষৰ ৩০০০ মিটাৰ ষ্টীপ্লেকেছ ফাইনেলত যোগ্যতা অৰ্জন কৰা প্ৰথমগৰাকী ভাৰতীয় হিচাবে অভিষেক সাবেল ।
--------------------------------------------------

Translating ASM:   9%|██▏                     | 90/1000 [00:42<06:29,  2.34it/s]

[90/1000]
EN: Mirabai Chanu returned to competition as she prepared for upcoming international events.
ASM: আগন্তুক আন্তঃৰাষ্ট্ৰীয় প্ৰতিযোগিতাৰ বাবে প্ৰস্তুতি চলাই প্ৰতিযোগিতালৈ উভতি আহিল মীৰাবাই চানু ।
--------------------------------------------------

Translating ASM:   9%|██▏                     | 91/1000 [00:42<06:46,  2.24it/s]

[91/1000]
EN: Manu Bhaker and Harmanpreet Singh among athletes highlighted in a sports-honours post.
ASM: খেলুৱৈসকলৰ মাজত মনু ভাকৰ আৰু হৰমনপ্ৰীত সিঙক ক্ৰীড়া সন্মানৰ পদত আলোকপাত কৰা হয় ।
--------------------------------------------------

Translating ASM:   9%|██▏                     | 92/1000 [00:43<07:43,  1.96it/s]

[92/1000]
EN: At the Milan–Cortina Winter Olympics 2026, Ilia Malinin landed a backflip on one skate in an Olympics moment.
ASM: মিলানকৰ্টিনা শীতকালীন অলিম্পিক ২০২৬ত ইলিয়া মালিনিনে অলিম্পিক মুহূৰ্তত এটা স্কেটত বেকফ্লিপ অৱস্থিত কৰিছিল ।
--------------------------------------------------

Translating ASM:   9%|██▏                     | 93/1000 [00:43<07:40,  1.97it/s]

[93/1000]
EN:  Anastasiia Gubanova delivered a performance featuring Indian cultural elements on the ice in Milan.
ASM: মিলানত আইচত ভাৰতীয় সাংস্কৃতিক উপাদানসমূহৰ সৈতে এক প্ৰদৰ্শনী প্ৰদান কৰে আনাষ্টেচিয়া গুবাণোভাই ।
--------------------------------------------------

Translating ASM:   9%|██▎                     | 94/1000 [00:44<07:41,  1.96it/s]

[94/1000]
EN: Formula One World Championship could return to Indian soil after a 13-year gap as policy issues are addressed.
ASM: ফৰ্মুলা ৱান বিশ্ব চেম্পিয়নশ্বিপ ১৩ বছৰৰ ব্যৱধানৰ পিছত ভাৰতীয় মাটিত উভতি আহিব পাৰে কিয়নো নীতিগত সমস্যাসমূহ সমাধান কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  10%|██▎                     | 95/1000 [00:44<07:56,  1.90it/s]

[95/1000]
EN: Nikhat Zareen won 5–0 over Guo Yi Xuan in a bout described as a commanding victory.
ASM: নিখাত জাৰেনে গৌ ই ঝুৱানৰ বিৰুদ্ধে ৫-০ গলত জয়লাভ কৰে এক যুঁজত এক আকৰ্ষণীয় বিজয় বুলি বৰ্ণনা কৰে ।
--------------------------------------------------

Translating ASM:  10%|██▎                     | 96/1000 [00:45<08:49,  1.71it/s]

[96/1000]
EN: Minakshi Hooda and Jaismine Lamboria upset Paris Olympics medallists and top seeds in a major boxing event.
ASM: প্ৰধান বক্সিং ইভেণ্টত পেৰিছ অলিম্পিকৰ পদকবিজয়ী আৰু শীৰ্ষ বীজত বিৰক্ত মিনাক্ষী হুডা আৰু জয়মীন লাম্বোৰিয়া ।
--------------------------------------------------

Translating ASM:  10%|██▎                     | 97/1000 [00:45<08:06,  1.86it/s]

[97/1000]
EN: Vinesh Phogat announced a return to wrestling on December 12, 2025.
ASM: বিনেশ ফোগটে ১২ ডিচেম্বৰ ২০২৫ তাৰিখে কুস্ত্ৰীবাজলৈ উভতি যোৱাৰ কথা ঘোষণা কৰে ।
--------------------------------------------------

Translating ASM:  10%|██▎                     | 98/1000 [00:46<07:17,  2.06it/s]

[98/1000]
EN: Village spectators watching a kabaddi match organised at a makeshift arena.
ASM: অস্থায়ী খেলপথাৰত আয়োজন কৰা কাবাড্ডি মেচ চোৱা গাঁৱৰ দৰ্শক ।
--------------------------------------------------

Translating ASM:  10%|██▍                     | 99/1000 [00:46<06:55,  2.17it/s]

[99/1000]
EN: The 21st Tata Mumbai Marathon took place with large-scale participation in Mumbai.
ASM: মুম্বাইত বৃহৎ অংশগ্ৰহণেৰে ২১ সংখ্যক টাটা মুম্বাই মাৰাথন অনুষ্ঠিত হয় ।
--------------------------------------------------

Translating ASM:  10%|██▎                    | 100/1000 [00:47<07:02,  2.13it/s]

[100/1000]
EN: The first-ever Formula 4 car show on Marina Beach was held on the banks of the sea in Chennai.
ASM: চেন্নাইৰ সমুদ্ৰৰ পাৰত মৰিনা বিচত প্ৰথমবাৰৰ বাবে ফৰ্মুলা ৪ গাড়ী প্ৰদৰ্শনী অনুষ্ঠিত হয় ।
--------------------------------------------------

Translating ASM:  10%|██▎                    | 101/1000 [00:47<07:01,  2.13it/s]

[101/1000]
EN: Tilak Varma said India felt ready for the high-stakes Pakistan match in Colombo.
ASM: তিলক বৰ্মাই কয় যে কলম্বোত অনুষ্ঠিত হবলগীয়া পাকিস্তান খেলৰ বাবে ভাৰতে নিজকে প্ৰস্তুত অনুভৱ কৰিছে ।
--------------------------------------------------

Translating ASM:  10%|██▎                    | 102/1000 [00:48<06:56,  2.16it/s]

[102/1000]
EN: Tilak Varma said the India squad had entered a focused “match zone” mindset.
ASM: তিলক বৰ্মাই কয় যে ভাৰতীয় দলটোৱে এক কেন্দ্ৰিত মেচ জোন মানসিকতাত প্ৰৱেশ কৰিছে ।
--------------------------------------------------

Translating ASM:  10%|██▎                    | 103/1000 [00:48<06:58,  2.14it/s]

[103/1000]
EN: Tilak Varma described the India–Pakistan fixture as a major highlight of the tournament.
ASM: টিলক বৰ্মাই ভাৰত-পাকিস্তানৰ ফিক্টিংক টুৰ্ণামেণ্টৰ মুখ্য হাইলাইট বুলি বৰ্ণনা কৰে ।
--------------------------------------------------

Translating ASM:  10%|██▍                    | 104/1000 [00:48<06:46,  2.20it/s]

[104/1000]
EN: Tilak Varma emphasized preparation and intensity for India ahead of the Pakistan clash.
ASM: তিলক বৰ্মাই পাকিস্তানৰ সংঘৰ্ষৰ পূৰ্বে ভাৰতৰ বাবে প্ৰস্তুতি আৰু তীব্ৰতাৰ ওপৰত গুৰুত্ব আৰোপ কৰে ।
--------------------------------------------------

Translating ASM:  10%|██▍                    | 105/1000 [00:49<06:44,  2.21it/s]

[105/1000]
EN: Tilak Varma framed the Pakistan game as a test of temperament and execution.
ASM: তিলক বৰ্মাই পাকিস্তানৰ খেলখন বৌদ্ধিকতা আৰু কার্যকৰী কৰাৰ পৰীক্ষা হিচাপে প্ৰদৰ্শন কৰিছিল ।
--------------------------------------------------

Translating ASM:  11%|██▍                    | 106/1000 [00:49<06:56,  2.15it/s]

[106/1000]
EN: Delhi Metro extended operating hours to support fans travelling for the India–Namibia match.
ASM: ভাৰতনামিবিয়া মেচৰ বাবে ভ্ৰমণ কৰা অনুৰাগীসকলক সমৰ্থন কৰিবলৈ দিল্লী মেট্ৰোৱে কাৰ্যকাল বৃদ্ধি কৰিছে ।
--------------------------------------------------

Translating ASM:  11%|██▍                    | 107/1000 [00:50<07:09,  2.08it/s]

[107/1000]
EN: Delhi Metro added services to manage crowd flow before and after the India–Namibia game.
ASM: ভাৰতনামিবিয়া খেলৰ পূৰ্বে আৰু পিছত ভিৰ প্ৰবাহ ব্যৱস্থাপনাৰ বাবে দিল্লী মেট্ৰোৱে সেৱা যোগ কৰে ।
--------------------------------------------------

Translating ASM:  11%|██▍                    | 108/1000 [00:50<07:18,  2.04it/s]

[108/1000]
EN: City transport officials coordinated services to reduce congestion around the India–Namibia fixture.
ASM: চহৰৰ পৰিবহণ বিষয়াসকলে ভাৰত-নামিবিয়া ফিক্স্টাৰৰ চাৰিওফালে যানজঁট হ্ৰাস কৰিবলৈ সেৱা সমন্বয় কৰিছিল ।
--------------------------------------------------

Translating ASM:  11%|██▌                    | 109/1000 [00:51<07:23,  2.01it/s]

[109/1000]
EN: Extended metro services aimed to make stadium travel easier for cricket spectators in Delhi.
ASM: দিল্লীৰ ক্ৰিকেট দৰ্শকসকলৰ বাবে ষ্টেডিয়াম ভ্ৰমণ সহজ কৰাৰ লক্ষ্যৰে মেট্ৰ সেৱা সম্প্ৰসাৰিত কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  11%|██▌                    | 110/1000 [00:51<07:34,  1.96it/s]

[110/1000]
EN: Additional trains were planned to handle the match-day rush for the India–Namibia crowd.
ASM: ভাৰতনামিবিয়া দৰ্শকৰ বাবে মেচ-দিনৰ ধুমুহাৰ মোকাবিলা কৰিবলৈ অতিৰিক্ত ৰেলৰ পৰিকল্পনা কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  11%|██▌                    | 111/1000 [00:52<07:15,  2.04it/s]

[111/1000]
EN: Rohit Sharma warned India that confidence alone would not win against Pakistan.
ASM: ৰোহিত শৰ্মাই ভাৰতক সতৰ্ক কৰিছিল যে কেৱল আস্থাই পাকিস্তানৰ বিৰুদ্ধে জয়লাভ কৰিব নোৱাৰে ।
--------------------------------------------------

Translating ASM:  11%|██▌                    | 112/1000 [00:52<07:06,  2.08it/s]

[112/1000]
EN: Rohit Sharma urged India to approach Pakistan with discipline, planning, and composure.
ASM: ৰোহিত শৰ্মাই ভাৰতক অনুশাসন, পৰিকল্পনা আৰু সংযমৰ সৈতে পাকিস্তানৰ কাষ চাপিবলৈ আহ্বান জনায় ।
--------------------------------------------------

Translating ASM:  11%|██▌                    | 113/1000 [00:53<07:11,  2.06it/s]

[113/1000]
EN: Rohit Sharma cautioned that India–Pakistan games can ignore rankings and recent form.
ASM: ৰোহিত শৰ্মাই সতৰ্ক কৰি দিয়ে যে ভাৰত-পাকিস্তানৰ খেলবোৰে ৰেংকিং আৰু শেহতীয়া ফৰ্ম উপেক্ষা কৰিব পাৰে ।
--------------------------------------------------

Translating ASM:  11%|██▌                    | 114/1000 [00:53<06:37,  2.23it/s]

[114/1000]
EN: Rohit Sharma stressed mental readiness for India before the Pakistan contest.
ASM: ৰোহিত শৰ্মাই পাকিস্তান প্ৰতিযোগিতাৰ পূৰ্বে ভাৰতৰ বাবে মানসিক প্ৰস্তুতিৰ ওপৰত জোৰ দিয়ে ।
--------------------------------------------------

Translating ASM:  12%|██▋                    | 115/1000 [00:54<06:27,  2.28it/s]

[115/1000]
EN: Rohit Sharma advised India to avoid underestimating Pakistan in the World Cup clash.
ASM: বিশ্বকাপৰ সংঘৰ্ষত পাকিস্তানক অৱমূল্যায়ন নকৰিবলৈ ভাৰতক পৰামৰ্শ ৰোহিত শৰ্মাৰ ।
--------------------------------------------------

Translating ASM:  12%|██▋                    | 116/1000 [00:54<06:37,  2.22it/s]

[116/1000]
EN: Virat Kohli congratulated India’s Under-19 team after the World Cup final victory.
ASM: বিশ্বকাপৰ ফাইনেলত জয়লাভ কৰা ভাৰতীয় ১৯ অনুৰ্দ্ধৰ দলক অভিনন্দন বিৰাট কোহলীৰ ।
--------------------------------------------------

Translating ASM:  12%|██▋                    | 117/1000 [00:55<07:04,  2.08it/s]

[117/1000]
EN: India’s Under-19 team won the ICC Under-19 Cricket World Cup final by 100 runs against England.
ASM: ইংলেণ্ডৰ বিৰুদ্ধে ১০০ ৰানত আই চি চি অনূৰ্ধ্ব১৯ ক্ৰিকেট বিশ্বকাপৰ ফাইনেলত জয় ভাৰতৰ ১৯ অনুৰ্ধৰ দল ।
--------------------------------------------------

Translating ASM:  12%|██▋                    | 118/1000 [00:55<07:05,  2.07it/s]

[118/1000]
EN: India secured a sixth Under-19 World Cup title with a commanding final performance.
ASM: ফাইনেলত আকৰ্ষণীয় প্ৰদৰ্শনেৰে ষষ্ঠ অনূৰ্ধ্ব১৯ বিশ্বকাপৰ খিতাপ নিশ্চিত কৰিলে ভাৰতে ।
--------------------------------------------------

Translating ASM:  12%|██▋                    | 119/1000 [00:56<06:43,  2.19it/s]

[119/1000]
EN: Celebrations followed India’s Under-19 World Cup triumph over England in the title match.
ASM: টাইটেল মেচত ইংলেণ্ডৰ বিৰুদ্ধে ভাৰতৰ ১৯ অনুৰ্দ্ধৰ বিশ্বকাপৰ জয়ৰ পিছতে উদযাপন ।
--------------------------------------------------

Translating ASM:  12%|██▊                    | 120/1000 [00:56<06:38,  2.21it/s]

[120/1000]
EN: India’s Under-19 success drew praise from senior players across Indian cricket.
ASM: ভাৰতৰ ১৯ বছৰ অনূৰ্ধ্বৰ সাফল্যই ভাৰতীয় ক্ৰিকেটৰ জ্যেষ্ঠ খেলুৱৈসকলৰ প্ৰশংসা লাভ কৰে ।
--------------------------------------------------

Translating ASM:  12%|██▊                    | 121/1000 [00:57<06:43,  2.18it/s]

[121/1000]
EN: Dhakshineswar Suresh sparked optimism by delivering a breakthrough stretch for Indian tennis.
ASM: ভাৰতীয় টেনিছৰ বাবে এক অৱক্ষয়মূলক প্ৰসাৰ প্ৰদান কৰি ধাক্কেশ্বৰ সুৰেশে আশাবাদ জগাই তোলে ।
--------------------------------------------------

Translating ASM:  12%|██▊                    | 122/1000 [00:57<07:00,  2.09it/s]

[122/1000]
EN: Dhakshineswar Suresh’s rise has renewed ambition among Indian tennis fans and young players.
ASM: ধাক্কেশ্বৰ সুৰেশৰ উত্থানে ভাৰতীয় টেনিছ অনুৰাগী আৰু যুৱ খেলুৱৈসকলৰ মাজত অভিলাষ পুনৰুজ্জীৱিত কৰিছে ।
--------------------------------------------------

Translating ASM:  12%|██▊                    | 123/1000 [00:58<07:04,  2.06it/s]

[123/1000]
EN: Dhakshineswar Suresh’s recent results were described as a turning point for Indian tennis.
ASM: ধাক্কেশ্বৰ সুৰেশৰ শেহতীয়া ফলাফলক ভাৰতীয় টেনিছৰ বাবে এক টাৰ্ণ পইণ্ট বুলি বৰ্ণনা কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  12%|██▊                    | 124/1000 [00:58<06:50,  2.13it/s]

[124/1000]
EN: Dhakshineswar Suresh’s performances lifted expectations for Indian tennis on bigger stages.
ASM: ঢাক্শীনেশ্বৰ সুৰেশৰ প্ৰদৰ্শনে ডাঙৰ মঞ্চত ভাৰতীয় টেনিছৰ বাবে আশা বৃদ্ধি কৰিছিল ।
--------------------------------------------------

Translating ASM:  12%|██▉                    | 125/1000 [00:58<06:35,  2.21it/s]

[125/1000]
EN: Dhakshineswar Suresh’s run created fresh belief about India’s potential in men’s tennis.
ASM: পুৰুষ টেনিছত ভাৰতৰ সম্ভাৱনাক লৈ ধাক্কেশ্বৰ সুৰেশৰ দৌৰে এক নতুন বিশ্বাস জন্মাইছিল ।
--------------------------------------------------

Translating ASM:  13%|██▉                    | 126/1000 [00:59<06:47,  2.14it/s]

[126/1000]
EN: India’s men’s team exited in the quarterfinals at the Badminton Asia Team Championships.
ASM: বেডমিণ্টন এছিয়া টীম চেম্পিয়নশ্বিপৰ কোৱাৰ্টাৰ ফাইনেলত প্ৰস্থান ভাৰতীয় পুৰুষৰ দল ।
--------------------------------------------------

Translating ASM:  13%|██▉                    | 127/1000 [00:59<06:42,  2.17it/s]

[127/1000]
EN: India’s women’s team exited in the quarterfinals at the Badminton Asia Team Championships.
ASM: বেডমিণ্টন এছিয়া টীম চেম্পিয়নশ্বিপত কোৱাৰ্টাৰ ফাইনেলত প্ৰস্থান ভাৰতীয় মহিলা দল ।
--------------------------------------------------

Translating ASM:  13%|██▉                    | 128/1000 [01:00<06:48,  2.14it/s]

[128/1000]
EN: India failed to defend titles after a double quarterfinal exit in the team championships.
ASM: দলীয় চেম্পিয়নশ্বিপত দুবাৰকৈ কোৱাৰ্টাৰ ফাইনেলত প্ৰস্থান কৰাৰ পিছত খিতাপ প্ৰতিৰক্ষাত ব্যৰ্থ ভাৰত ।
--------------------------------------------------

Translating ASM:  13%|██▉                    | 129/1000 [01:00<06:50,  2.12it/s]

[129/1000]
EN: Strong opposition ended India’s campaign early at the Badminton Asia Team Championships.
ASM: বেডমিণ্টন এছিয়া টীম চেম্পিয়নশ্বিপত শক্তিশালী বিৰোধীয়ে প্ৰাৰম্ভিকতে ভাৰতৰ অভিযান সামৰিলে ।
--------------------------------------------------

Translating ASM:  13%|██▉                    | 130/1000 [01:01<06:40,  2.17it/s]

[130/1000]
EN: The quarterfinal losses ended India’s hopes of a title defence at the event.
ASM: কোৱাৰ্টাৰ ফাইনেলত পৰাজয়ৰ ফলত ইভেণ্টত খিতাপৰ প্ৰতিৰক্ষাৰ আশা শেষ হয় ।
--------------------------------------------------

Translating ASM:  13%|███                    | 131/1000 [01:01<06:26,  2.25it/s]

[131/1000]
EN: Sumit Nagal was scheduled to open his tournament campaign against Guy Den Ouden.
ASM: গায় ডেন উডেনৰ বিৰুদ্ধে নিজৰ টুৰ্ণামেণ্ট প্ৰচাৰ আৰম্ভ কৰাৰ কথা আছিল সুমিত নাগালৰ ।
--------------------------------------------------

Translating ASM:  13%|███                    | 132/1000 [01:02<06:32,  2.21it/s]

[132/1000]
EN: Sumit Nagal drew Dutch player Guy Den Ouden in an opening-round matchup.
ASM: মুকলি ৰাউণ্ডৰ মেচআপত ডাচ খেলুৱৈ গায় ডেন উডেনক ড্ৰ কৰিলে সুমিত নাগলে ।
--------------------------------------------------

Translating ASM:  13%|███                    | 133/1000 [01:02<06:32,  2.21it/s]

[133/1000]
EN: Sumit Nagal’s first-round pairing set up an early test against Guy Den Ouden.
ASM: গায় ডেন উডেনৰ বিৰুদ্ধে প্ৰথম ৰাউণ্ডৰ পেৰিঙৰ প্ৰাৰম্ভিক পৰীক্ষণ স্থাপন সুমিত নাগালৰ ।
--------------------------------------------------

Translating ASM:  13%|███                    | 134/1000 [01:03<06:37,  2.18it/s]

[134/1000]
EN: Sumit Nagal prepared for a fresh challenge against Guy Den Ouden in round one.
ASM: প্ৰথম ৰাউণ্ডত গাই ডেন উডেনৰ বিৰুদ্ধে নতুন প্ৰত্যাহ্বানৰ বাবে সাজু হল সুমিত নাগালে ।
--------------------------------------------------

Translating ASM:  14%|███                    | 135/1000 [01:03<06:21,  2.27it/s]

[135/1000]
EN: Sumit Nagal began a new event with an opening match against Guy Den Ouden.
ASM: গাই ডেন উডেনৰ বিৰুদ্ধে উদ্বোধনী মেচত নতুন ইভেণ্ট আৰম্ভ কৰিলে সুমিত নাগলে ।
--------------------------------------------------

Translating ASM:  14%|███▏                   | 136/1000 [01:03<06:35,  2.19it/s]

[136/1000]
EN: An analysis said T20 cricket keeps evolving through new strategies and fast-changing trends.
ASM: এক বিশ্লেষণত কোৱা হৈছিল যে টি২০ ক্ৰিকেটে নতুন কৌশল আৰু দ্ৰুত পৰিৱৰ্তনশীল প্ৰবণতাৰ জৰিয়তে বিকশিত হৈ আছে ।
--------------------------------------------------

Translating ASM:  14%|███▏                   | 137/1000 [01:04<06:35,  2.18it/s]

[137/1000]
EN: A feature noted the ICC Men's T20 World Cup returned to India after a decade-long gap.
ASM: এটা বৈশিষ্ট্য উল্লেখ কৰা হৈছে যে আইচিচি পুৰুষৰ টি২০ বিশ্বকাপটো দহ বছৰৰ ব্যৱধানৰ পিছত ভাৰতলৈ উভটি আহিল ।
--------------------------------------------------

Translating ASM:  14%|███▏                   | 138/1000 [01:04<06:50,  2.10it/s]

[138/1000]
EN: T20 cricket was described as a format that continually reinvents tactics and team plans.
ASM: টি২০ ক্ৰিকেটক এটা ফৰমেট বুলি বৰ্ণনা কৰা হৈছিল যি নিৰন্তৰে কৌশল আৰু দলৰ পৰিকল্পনা পুনৰ আৱিষ্কাৰ কৰে ।
--------------------------------------------------

Translating ASM:  14%|███▏                   | 139/1000 [01:05<06:26,  2.23it/s]

[139/1000]
EN: A commentary highlighted how technology and data shape modern T20 decision-making.
ASM: এক মন্তব্যত আলোকপাত কৰা হৈছিল যে কেনেকৈ প্ৰযুক্তি আৰু ডাটা আধুনিক টি২০ সিদ্ধান্ত গ্ৰহণক আকৃতি প্ৰদান কৰে ।
--------------------------------------------------

Translating ASM:  14%|███▏                   | 140/1000 [01:05<06:33,  2.19it/s]

[140/1000]
EN: A tournament preview underlined T20 cricket’s cultural impact and mass appeal in India.
ASM: টুৰ্ণামেণ্টৰ প্ৰাকদৰ্শনীয়ে ভাৰতত টি২০ ক্ৰিকেটৰ সাংস্কৃতিক প্ৰভাৱ আৰু জনপ্ৰিয়তাৰ ওপৰত আলোকপাত কৰিছিল ।
--------------------------------------------------

Translating ASM:  14%|███▏                   | 141/1000 [01:06<06:48,  2.10it/s]

[141/1000]
EN: Kapil Dev was listed among participants at the PM Rungta Memorial Golf Cup in Jaipur.
ASM: জয়পুৰত অনুষ্ঠিত পিএম ৰুংটা মেমৰিয়েল গল্ফ কাপত অংশগ্ৰহণকাৰীসকলৰ তালিকাত কপিল দেৱ আছিল ।
--------------------------------------------------

Translating ASM:  14%|███▎                   | 142/1000 [01:06<06:58,  2.05it/s]

[142/1000]
EN: Madan Lal was listed among participants at the PM Rungta Memorial Golf Cup in Jaipur.
ASM: জয়পুৰত অনুষ্ঠিত পিএম ৰুংটা মেমৰিয়েল গল্ফ কাপত অংশগ্ৰহণকাৰীসকলৰ তালিকাত মদন লালক অন্তৰ্ভুক্ত কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  14%|███▎                   | 143/1000 [01:07<06:54,  2.07it/s]

[143/1000]
EN: The PM Rungta Memorial Golf Cup was scheduled for February 8, 2026 in Jaipur.
ASM: ২০২৬ চনৰ ৮ ফেব্ৰুৱাৰীত জয়পুৰত পিএম ৰুংটা মেমৰিয়েল গল্ফ কাপ অনুষ্ঠিত হোৱাৰ কথা আছিল ।
--------------------------------------------------

Translating ASM:  14%|███▎                   | 144/1000 [01:07<06:44,  2.11it/s]

[144/1000]
EN: Rambagh Golf Club was named as the venue for the memorial golf tournament.
ASM: ৰামবাগ গল্ফ ক্লাবক স্মৃতি গল্ফ টুৰ্ণামেণ্টৰ স্থান হিচাপে মনোনীত কৰা হয় ।
--------------------------------------------------

Translating ASM:  14%|███▎                   | 145/1000 [01:08<07:14,  1.97it/s]

[145/1000]
EN: Organisers said the golf cup used a Stableford Single Peoria format for inclusive competition.
ASM: আয়োজকসকলে কৈছিল যে গল্ফ কাপটোৱে অন্তৰ্ভুক্তিমূলক প্ৰতিযোগিতাৰ বাবে ষ্টেবলফৰ্ড একক পিয়ৰিয়া ফৰমেট ব্যৱহাৰ কৰিছিল ।
--------------------------------------------------

Translating ASM:  15%|███▎                   | 146/1000 [01:08<07:39,  1.86it/s]

[146/1000]
EN: A schedule note said United States would face Netherlands in Chennai to close February 13’s action.
ASM: এটা সময়সূচী নোটত কোৱা হৈছিল যে ১৩ ফেব্ৰুৱাৰীত কৰা কাৰ্য বন্ধ কৰিবলৈ আমেৰিকা যুক্তৰাষ্ট্ৰই চেন্নাইত নেদাৰলেণ্ডৰ বিৰুদ্ধে মুখামুখি হ'ব ।
--------------------------------------------------

Translating ASM:  15%|███▍                   | 147/1000 [01:09<07:17,  1.95it/s]

[147/1000]
EN: The USA–Netherlands match was presented as important for points and pride in the group.
ASM: পইণ্ট আৰু দলটোৰ গৌৰৱৰ বাবে ইউ এছ এনেদাৰলেণ্ডছ মেচটো গুৰুত্বপূৰ্ণ বুলি উপস্থাপন কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  15%|███▍                   | 148/1000 [01:09<07:09,  1.98it/s]

[148/1000]
EN: A match preview framed USA against Netherlands as a tight contest between associate nations.
ASM: সংযোগী ৰাষ্ট্ৰসমূহৰ মাজত তীব্ৰ প্ৰতিযোগিতা হিচাপে নেদাৰলেণ্ডছৰ বিৰুদ্ধে আমেৰিকা যুক্তৰাষ্ট্ৰক ফ্ৰেম কৰা এখন খেলৰ প্ৰাকদৰ্শন ।
--------------------------------------------------

Translating ASM:  15%|███▍                   | 149/1000 [01:10<07:21,  1.93it/s]

[149/1000]
EN: A schedule roundup highlighted February 13 fixtures as key for shaping group standings.
ASM: গ্ৰুপ শৃংখলা গঢ়ি তোলাৰ বাবে ফেব্ৰুৱাৰী ১৩ তাৰিখৰ ফিক্সচাৰবোৰক এটা সূচী ৰাউণ্ডআপে আলোকপাত কৰিছিল ।
--------------------------------------------------

Translating ASM:  15%|███▍                   | 150/1000 [01:10<07:21,  1.92it/s]

[150/1000]
EN: A preview said the final February 13 match would be played at MA Chidambaram Stadium.
ASM: প্ৰাকদৰ্শনীত কোৱা হৈছিল যে ১৩ ফেব্ৰুৱাৰীত চূড়ান্ত খেল এম এ চিদাম্বৰম ষ্টেডিয়ামত খেলা হ'ব ।
--------------------------------------------------

Translating ASM:  15%|███▍                   | 151/1000 [01:11<07:13,  1.96it/s]

[151/1000]
EN: Indian Super League clubs requested a pause on relegation for three to five years.
ASM: ইণ্ডিয়ান ছুপাৰ লীগ ক্লাবসমূহে ৰেলিগেছনৰ ক্ষেত্ৰত তিনিৰ পৰা পাঁচ বছৰৰ বাবে বন্ধৰ বাবে অনুৰোধ জনাইছে ।
--------------------------------------------------

Translating ASM:  15%|███▍                   | 152/1000 [01:11<07:20,  1.93it/s]

[152/1000]
EN: ISL clubs argued that pausing relegation would provide stability for long-term planning.
ASM: আই এছ এল ক্লাবসমূহে যুক্তি দিছিল যে ৰেলেগেশ্বন বন্ধ কৰিলে দীৰ্ঘম্যাদী পৰিকল্পনাৰ বাবে স্থিতিশীলতা প্ৰদান কৰিব ।
--------------------------------------------------

Translating ASM:  15%|███▌                   | 153/1000 [01:12<07:01,  2.01it/s]

[153/1000]
EN: Several ISL teams asked administrators to consider a temporary relegation freeze.
ASM: আই এছ এলৰ কেইবাটাও দলে প্ৰশাসকসকলক অস্থায়ী ৰেলেগেশ্বন হিমশীতল কৰাৰ কথা বিবেচনা কৰিবলৈ কৈছিল ।
--------------------------------------------------

Translating ASM:  15%|███▌                   | 154/1000 [01:12<06:28,  2.18it/s]

[154/1000]
EN: The request on relegation was framed as a measure to protect club investments.
ASM: নামনিৰ বাবে কৰা অনুৰোধক ক্লাবৰ বিনিয়োগ সুৰক্ষাৰ এক ব্যৱস্থা হিচাপে গঢ়ি তোলা হৈছিল ।
--------------------------------------------------

Translating ASM:  16%|███▌                   | 155/1000 [01:13<06:58,  2.02it/s]

[155/1000]
EN: ISL stakeholders debated relegation rules while seeking clarity for the 2025–26 season.
ASM: আই এছ এলৰ স্টেকহোল্ডাৰসকলে ২০২৫২৬ বৰ্ষৰ বাবে স্পষ্টতা বিচৰা সময়ছোৱাত ৰেলিগেছনৰ নিয়মক লৈ বিতৰ্ক কৰিছিল ।
--------------------------------------------------

Translating ASM:  16%|███▌                   | 156/1000 [01:13<06:59,  2.01it/s]

[156/1000]
EN: India produced a 3–2 win over Netherlands in Davis Cup Qualifiers Round 1.
ASM: ডেভিছ কাপ কোৱালিফায়াৰছৰ প্ৰথম ৰাউণ্ডত নেদাৰলেণ্ডৰ বিৰুদ্ধে ৩-২ ব্যৱধানত জয়লাভ কৰিলে ভাৰতে ।
--------------------------------------------------

Translating ASM:  16%|███▌                   | 157/1000 [01:14<07:06,  1.97it/s]

[157/1000]
EN: India advanced to the second Davis Cup qualifying round after beating Netherlands 3–2.
ASM: নেদাৰলেণ্ডছক ৩-২ ব্যৱধানত পৰাস্ত কৰি দ্বিতীয় ডেভিছ কাপ কোৱালিফায়িং ৰাউণ্ডত প্ৰৱেশ কৰিলে ভাৰতে ।
--------------------------------------------------

Translating ASM:  16%|███▋                   | 158/1000 [01:14<06:56,  2.02it/s]

[158/1000]
EN: India’s Davis Cup team was described as thriving against higher-ranked opponents recently.
ASM: ভাৰতৰ ডেভিছ কাপ দলক শেহতীয়াকৈ উচ্চ স্থানৰ প্ৰতিদ্বন্দ্বীৰ বিৰুদ্ধে সমৃদ্ধিশালী বুলি বৰ্ণনা কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  16%|███▋                   | 159/1000 [01:15<06:46,  2.07it/s]

[159/1000]
EN: The Davis Cup tie at SM Krishna Tennis Stadium went down to the wire.
ASM: এছ এম কৃষ্ণা টেনিছ ষ্টেডিয়ামত ডেভিছ কাপৰ টী তললৈ নামি গল ।
--------------------------------------------------

Translating ASM:  16%|███▋                   | 160/1000 [01:15<06:31,  2.15it/s]

[160/1000]
EN: India’s Davis Cup success followed an earlier victory over Switzerland in Biel last year.
ASM: যোৱা বছৰ বেলত ছুইজাৰলেণ্ডক পৰাস্ত কৰাৰ পিছত ভাৰতৰ ডেভিছ কাপত সফলতা লাভ কৰে ভাৰতে ।
--------------------------------------------------

Translating ASM:  16%|███▋                   | 161/1000 [01:16<06:40,  2.09it/s]

[161/1000]
EN: The India Open was kept as a Super 750 tournament for the 2027–2030 cycle.
ASM: ২০২৭২০৩০ চক্রৰ বাবে ইণ্ডিয়া অপেনক চুপাৰ ৭৫০ টুৰ্ণামেণ্ট হিচাপে ৰখা হৈছিল ।
--------------------------------------------------

Translating ASM:  16%|███▋                   | 162/1000 [01:16<07:09,  1.95it/s]

[162/1000]
EN: Players criticised conditions, yet organisers retained the India Open’s Super 750 status.
ASM: খেলুৱৈসকলে চৰ্তবোৰ সমালোচনা কৰিছিল, তথাপিও আয়োজকসকলে ইণ্ডিয়া অপেনৰ ছুপাৰ ৭৫০ স্থিতি বজাই ৰাখিছিল ।
--------------------------------------------------

Translating ASM:  16%|███▋                   | 163/1000 [01:17<07:15,  1.92it/s]

[163/1000]
EN: Badminton World Federation announced a revamped World Tour structure with six tournament levels.
ASM: বেডমিণ্টন বিশ্ব ফেডাৰেচনে ছটা টুৰ্ণামেণ্ট স্তৰৰ সৈতে এক নতুনকৈ গঢ়ি তোলা বিশ্ব ভ্ৰমণ কাঠামো ঘোষণা কৰে ।
--------------------------------------------------

Translating ASM:  16%|███▊                   | 164/1000 [01:17<07:15,  1.92it/s]

[164/1000]
EN: The BWF updated World Tour plan included 36 tournaments across multiple tiers.
ASM: বিডব্লিউএফৰ আপডেট কৰা বিশ্ব ভ্ৰমণ পৰিকল্পনাত একাধিক স্তৰৰ ৩৬ টা টুৰ্ণামেণ্ট অন্তৰ্ভুক্ত আছিল ।
--------------------------------------------------

Translating ASM:  16%|███▊                   | 165/1000 [01:18<07:12,  1.93it/s]

[165/1000]
EN: The BWF said annual World Tour prize money would rise to about 26.9 million dollars.
ASM: বি ডব্লিউ এফে কৈছিল যে বাৰ্ষিক বিশ্ব ভ্ৰমণৰ পুৰস্কাৰৰ ধন প্ৰায় ২৬.৯ মিলিয়ন ডলাৰলৈ বৃদ্ধি হ'ব ।
--------------------------------------------------

Translating ASM:  17%|███▊                   | 166/1000 [01:18<07:14,  1.92it/s]

[166/1000]
EN: A schedule preview listed Sri Lanka against Oman as a February 12 group-stage fixture.
ASM: এটা সূচী পূৰ্বদৃশ্যই শ্ৰীলংকাৰ বিৰুদ্ধে ওমানক ১২ ফেব্ৰুৱাৰী গ্ৰুপ-ষ্টেজ ফিক্স হিচাপে তালিকাভুক্ত কৰিছিল ।
--------------------------------------------------

Translating ASM:  17%|███▊                   | 167/1000 [01:19<07:16,  1.91it/s]

[167/1000]
EN: A schedule preview listed Nepal against Italy as a February 12 group-stage fixture.
ASM: এটা সূচী পূৰ্বদৃশ্যই নেপালক ইটালীৰ বিৰুদ্ধে ১২ ফেব্ৰুৱাৰী গ্ৰুপ-ষ্টেজ ফিক্স হিচাপে তালিকাভুক্ত কৰিছিল ।
--------------------------------------------------

Translating ASM:  17%|███▊                   | 168/1000 [01:19<07:10,  1.93it/s]

[168/1000]
EN: A schedule preview listed India against Namibia as a February 12 group-stage fixture.
ASM: এটা সূচী পূৰ্বদৃশ্যই ভাৰত বনাম নামিবিয়াৰ বিৰুদ্ধে ১২ ফেব্ৰুৱাৰী গ্ৰুপ-ষ্টেজ খেল হিচাপে তালিকাভুক্ত কৰিছিল ।
--------------------------------------------------

Translating ASM:  17%|███▉                   | 169/1000 [01:20<06:24,  2.16it/s]

[169/1000]
EN: Wanindu Hasaranga was ruled out of the World Cup due to an injury setback.
ASM: আঘাতৰ পিছ পৰি বিশ্বকাপৰ পৰা বাদ পৰিল ৱানিন্দু হাছাৰঙা ।
--------------------------------------------------

Translating ASM:  17%|███▉                   | 170/1000 [01:20<06:28,  2.14it/s]

[170/1000]
EN: Sri Lanka named Dushan Hemantha as a replacement after Wanindu Hasaranga’s injury.
ASM: ৱানিন্দু হাছাৰঙাৰ আঘাতৰ পিছত শ্ৰীলংকাই প্ৰতিস্থাপক হিচাপে দুশন হেমন্তক মনোনীত কৰে ।
--------------------------------------------------

Translating ASM:  17%|███▉                   | 171/1000 [01:21<06:16,  2.20it/s]

[171/1000]
EN: The Indian Super League season was announced to begin on February 14, 2026.
ASM: ২০২৬ চনৰ ১৪ ফেব্ৰুৱাৰীত ইণ্ডিয়ান ছুপাৰ লীগ ছিজন আৰম্ভ হব বুলি ঘোষণা কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  17%|███▉                   | 172/1000 [01:21<06:11,  2.23it/s]

[172/1000]
EN: Sports minister Mansukh Mandaviya announced an ISL start date of February 14.
ASM: ক্ৰীড়া মন্ত্ৰী মনসুখ মান্দভিয়াই ১৪ ফেব্ৰুৱাৰীত আই এছ এলৰ আৰম্ভণিৰ তাৰিখ ঘোষণা কৰে ।
--------------------------------------------------

Translating ASM:  17%|███▉                   | 173/1000 [01:22<06:00,  2.29it/s]

[173/1000]
EN: All 14 clubs agreed to participate in the Indian Super League season, according to reports.
ASM: বাতৰি অনুসৰি সকলো ১৪টা ক্লাবই ইণ্ডিয়ান ছুপাৰ লীগ ছিজনত অংশগ্ৰহণ কৰিবলৈ সন্মত হয় ।
--------------------------------------------------

Translating ASM:  17%|████                   | 174/1000 [01:22<06:07,  2.25it/s]

[174/1000]
EN: The ISL decision followed meetings between the sports ministry and the All India Football Federation.
ASM: ক্ৰীড়া মন্ত্ৰালয় আৰু সৰ্বভাৰতীয় ফুটবল ফেডাৰেশ্যনৰ মাজত হোৱা বৈঠকৰ পিছত আই এছ এলৰ এই সিদ্ধান্ত লোৱা হয় ।
--------------------------------------------------

Translating ASM:  18%|████                   | 175/1000 [01:22<06:09,  2.23it/s]

[175/1000]
EN: Indian football’s top-tier season moved forward after clubs accepted the participation plan.
ASM: অংশগ্ৰহণ পৰিকল্পনাক ক্লাববোৰে গ্ৰহণ কৰাৰ পিছত ভাৰতীয় ফুটবলৰ শীৰ্ষ স্তৰৰ ছিজন আগুৱাই গল ।
--------------------------------------------------

Translating ASM:  18%|████                   | 176/1000 [01:23<06:43,  2.04it/s]

[176/1000]
EN: India’s women lost 0–3 to China in the Badminton Asia Team Championships quarterfinals.
ASM: বেডমিণ্টন এছিয়া টীম চেম্পিয়নশ্বিপৰ কোৱাৰ্টাৰ ফাইনেলত চীনৰ হাতত ০-৩ গলত পৰাস্ত ভাৰতৰ মহিলা ।
--------------------------------------------------

Translating ASM:  18%|████                   | 177/1000 [01:23<06:32,  2.09it/s]

[177/1000]
EN: P. V. Sindhu missed the team quarterfinal because of a minor injury, according to reports.
ASM: বাতৰি অনুসৰি পি ভি সিন্ধুৱে সামান্য আঘাতৰ বাবে দলীয় কোৱাৰ্টাৰ ফাইনেলত পৰাস্ত হয় ।
--------------------------------------------------

Translating ASM:  18%|████                   | 178/1000 [01:24<06:18,  2.17it/s]

[178/1000]
EN: India’s women struggled to defend the 2024 title without PV Sindhu in the lineup.
ASM: পি ভি সিন্ধুৰ অবিহনে ২০২৪ৰ খিতাপ ৰক্ষা কৰিবলৈ সংগ্ৰাম কৰিলে ভাৰতৰ মহিলাসকলে ।
--------------------------------------------------

Translating ASM:  18%|████                   | 179/1000 [01:24<06:34,  2.08it/s]

[179/1000]
EN: China ended India’s women’s title defence with a straight 3–0 quarterfinal win.
ASM: কোৱাৰ্টাৰ ফাইনেলত একেৰাহে ৩-০ ব্যৱধানত জয় লাভ কৰি ভাৰতৰ মহিলা খিতাপৰ প্ৰতিৰক্ষা সামৰিলে চীনে ।
--------------------------------------------------

Translating ASM:  18%|████▏                  | 180/1000 [01:25<06:55,  1.98it/s]

[180/1000]
EN: The quarterfinal defeat closed India’s women’s campaign at the Badminton Asia Team Championships.
ASM: কোৱাৰ্টাৰ ফাইনেলত পৰাজয়ৰ ফলত বেডমিণ্টন এছিয়া টীম চেম্পিয়নশ্বিপত ভাৰতৰ মহিলা প্ৰচাৰ বন্ধ হয় ।
--------------------------------------------------

Translating ASM:  18%|████▏                  | 181/1000 [01:26<07:14,  1.88it/s]

[181/1000]
EN: Devika Sihag won the Thailand Masters 2026 to claim a BWF Super 300 title.
ASM: ডব্লিউডব্লিউএফ ছুপাৰ ৩০০ খিতাপ দাবী কৰিবলৈ দেৱিকা ছিহগে থাইলেণ্ড মাষ্টাৰ্ছ ২০২৬ত জয়লাভ কৰে ।
--------------------------------------------------

Translating ASM:  18%|████▏                  | 182/1000 [01:26<07:12,  1.89it/s]

[182/1000]
EN: Devika Sihag became the youngest Indian woman to win a BWF Super 300 singles title.
ASM: বি ডব্লিউ এফ চুপাৰ ৩০০ ছিংগলছৰ খিতাপ জয় কৰা দেৱিকা চিহাগ হৈছে আটাইতকৈ কনিষ্ঠ ভাৰতীয় মহিলা ।
--------------------------------------------------

Translating ASM:  18%|████▏                  | 183/1000 [01:27<07:08,  1.90it/s]

[183/1000]
EN: Devika Sihag joined Saina Nehwal and PV Sindhu in an exclusive Indian milestone list.
ASM: একচেটিয়া ভাৰতীয় মাইলৰ খুঁটা তালিকাত চাইনা নেহৱাল আৰু পি ভি সিন্ধুৰ সৈতে যোগ দিলে দেৱিকা চিহগে ।
--------------------------------------------------

Translating ASM:  18%|████▏                  | 184/1000 [01:27<06:43,  2.02it/s]

[184/1000]
EN: Devika Sihag’s Bangkok celebration marked a breakthrough moment for Indian women’s singles.
ASM: দেৱিকা চিহাগৰ বেংকক উদযাপন ভাৰতীয় মহিলা এককসকলৰ বাবে এক গুৰুত্বপূৰ্ণ মুহূৰ্ত চিহ্নিত কৰে ।
--------------------------------------------------

Translating ASM:  18%|████▎                  | 185/1000 [01:28<06:31,  2.08it/s]

[185/1000]
EN: Devika Sihag’s title was described as a quiet announcement of a new Indian badminton star.
ASM: দেৱিকা চিহাগৰ খিতাপক এগৰাকী নতুন ভাৰতীয় বেডমিণ্টন তাৰকাৰ শান্ত ঘোষণা হিচাপে বৰ্ণনা কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  19%|████▎                  | 186/1000 [01:28<06:38,  2.04it/s]

[186/1000]
EN: A matchday note listed Afghanistan against South Africa in Ahmedabad on February 11.
ASM: ১১ ফেব্ৰুৱাৰীত আহমেদাবাদত দক্ষিণ আফ্ৰিকাৰ বিৰুদ্ধে আফগানিস্তানৰ তালিকা এখন মেচডে নোটত তালিকাভুক্ত কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  19%|████▎                  | 187/1000 [01:29<06:56,  1.95it/s]

[187/1000]
EN: A matchday note listed Australia against Ireland as another February 11 group-stage fixture.
ASM: মেচডেই নোটত আয়াৰলেণ্ডৰ বিৰুদ্ধে অষ্ট্ৰেলিয়াৰ তালিকাভুক্ত কৰা হৈছে ১১ ফেব্ৰুৱাৰীৰ গ্ৰুপ-ষ্টেজৰ আন এটা খেল ।
--------------------------------------------------

Translating ASM:  19%|████▎                  | 188/1000 [01:29<06:59,  1.94it/s]

[188/1000]
EN: A matchday note listed England against West Indies as a February 11 evening fixture.
ASM: ১১ ফেব্ৰুৱাৰীত সন্ধিয়া খেল হিচাপে ৱেষ্টইণ্ডিজৰ বিৰুদ্ধে ইংলেণ্ডৰ তালিকা এখন মেচডে নোটত প্ৰকাশ পাইছে ।
--------------------------------------------------

Translating ASM:  19%|████▎                  | 189/1000 [01:30<06:43,  2.01it/s]

[189/1000]
EN: Afghanistan sought a rebound after losing their opener against New Zealand, according to reports.
ASM: বাতৰি অনুসৰি আফগানিস্তানে নিউজিলেণ্ডৰ বিৰুদ্ধে তেওঁলোকৰ ওপেনাৰ হেৰুওৱাৰ পিছত পুনৰুত্থান বিচাৰিছিল ।
--------------------------------------------------

Translating ASM:  19%|████▎                  | 190/1000 [01:30<07:08,  1.89it/s]

[190/1000]
EN: The February 11 schedule mixed former champions, contenders, and dangerous underdogs in group play.
ASM: ১১ ফেব্ৰুৱাৰীৰ সূচীটোৱে গ্ৰুপ প্লেত প্ৰাক্তন চেম্পিয়ন, প্ৰতিদ্বন্দ্বী আৰু বিপদজনক আণ্ডাৰডগক মিশ্ৰিত কৰিছিল ।
--------------------------------------------------

Translating ASM:  19%|████▍                  | 191/1000 [01:31<07:23,  1.83it/s]

[191/1000]
EN: Baichung Bhutia blamed administration after Churchill Brothers were not added to ISL 2025–26.
ASM: আই এছ এল ২০২৫২৬ত চৰ্চিল ব্ৰাদাৰ্ছ যোগ নকৰাৰ পিছত বাইচুং ভূটীয়াই প্ৰশাসনক দোষাৰোপ কৰে ।
--------------------------------------------------

Translating ASM:  19%|████▍                  | 192/1000 [01:31<07:46,  1.73it/s]

[192/1000]
EN: Churchill Brothers were not included in ISL 2025–26, prompting criticism from Baichung Bhutia.
ASM: চৰ্চিল ব্ৰাদাৰ্ছক আই এছ এল ২০২৫২৬ত অন্তৰ্ভুক্ত কৰা হোৱা নাছিল, যাৰ বাবে বাইচুং ভূটীয়াৰ পৰা সমালোচনা হৈছিল ।
--------------------------------------------------

Translating ASM:  19%|████▍                  | 193/1000 [01:32<07:16,  1.85it/s]

[193/1000]
EN: Baichung Bhutia called the Churchill Brothers exclusion a clear administrative failure.
ASM: বাইচুং ভূটীয়াই চৰ্চিল ব্ৰাদাৰ্ছক বাদ দিয়াটো এটা স্পষ্ট প্ৰশাসনিক বিফলতা বুলি অভিহিত কৰে ।
--------------------------------------------------

Translating ASM:  19%|████▍                  | 194/1000 [01:32<06:40,  2.01it/s]

[194/1000]
EN: The Churchill Brothers decision raised questions about the league’s selection and governance.
ASM: চর্চিল ব্ৰাদাৰ্ছ সিদ্ধান্তই লীগৰ নিৰ্বাচন আৰু প্ৰশাসনৰ ওপৰত প্ৰশ্ন উত্থাপন কৰিছিল ।
--------------------------------------------------

Translating ASM:  20%|████▍                  | 195/1000 [01:33<06:31,  2.06it/s]

[195/1000]
EN: The ISL debate intensified after the Churchill Brothers issue surfaced in public comments.
ASM: চৰ্চিল ব্ৰাদাৰ্ছ বিষয়টো ৰাজহুৱা মন্তব্যত উদয় হোৱাৰ পিছত আই এছ এলৰ বিতৰ্ক তীব্ৰ হৈ উঠিছিল ।
--------------------------------------------------

Translating ASM:  20%|████▌                  | 196/1000 [01:33<06:34,  2.04it/s]

[196/1000]
EN: India–Netherlands Davis Cup tie tightened after Sumit Nagal suffered a setback.
ASM: ভাৰত-নেদাৰলেণ্ডছ ডেভিছ কাপৰ টায় টান হল সুমিত নাগলৰ পিছ পৰি যোৱাৰ পিছত ।
--------------------------------------------------

Translating ASM:  20%|████▌                  | 197/1000 [01:34<06:59,  1.91it/s]

[197/1000]
EN: Sumit Nagal’s result added pressure as the Davis Cup tie moved toward a tense finish.
ASM: ডেভিছ কাপৰ টায়াৰ উত্তেজনাপূৰ্ণ ফাইনেলৰ দিশে অগ্ৰসৰ হোৱাৰ লগে লগে সুমিত নাগালৰ ফলাফলই চাপৰ সৃষ্টি কৰে ।
--------------------------------------------------

Translating ASM:  20%|████▌                  | 198/1000 [01:34<06:46,  1.97it/s]

[198/1000]
EN: India and Netherlands remained locked in a close Davis Cup contest after the Nagal match.
ASM: নাগালেণ্ডৰ খেলৰ পিছত ভাৰত আৰু নেদাৰলেণ্ডছ বন্ধ ডেভিছ কাপ প্ৰতিযোগিতাত লকডাউন হৈ আছিল ।
--------------------------------------------------

Translating ASM:  20%|████▌                  | 199/1000 [01:35<06:32,  2.04it/s]

[199/1000]
EN: The Davis Cup tie needed late composure after the Sumit Nagal setback, according to reports.
ASM: বাতৰি অনুসৰি ডেভিছ কাপ টাইৰ বাবে সুমিত নাগলৰ বিফলতাৰ পিছত বিলম্বিত স্থিতিৰ প্ৰয়োজন আছিল ।
--------------------------------------------------

Translating ASM:  20%|████▌                  | 200/1000 [01:35<06:44,  1.98it/s]

[200/1000]
EN: The Bengaluru Davis Cup atmosphere stayed intense as India fought Netherlands in a tight tie.
ASM: নেদাৰলেণ্ডছৰ বিৰুদ্ধে টান টানেৰে যুঁজ দিয়াৰ লগে লগে বেংগালুৰু ডেভিছ কাপৰ পৰিৱেশ তীব্ৰ হৈ পৰিল ।
--------------------------------------------------

Translating ASM:  20%|████▌                  | 201/1000 [01:36<06:39,  2.00it/s]

[201/1000]
EN: International Cricket Council confirmed the 2026 Men’s T20 World Cup starts on February 7.
ASM: আন্তঃৰাষ্ট্ৰীয় ক্ৰিকেট পৰিষদে নিশ্চিত কৰিলে ২০২৬ পুৰুষৰ টি২০ বিশ্বকাপ ৭ ফেব্ৰুৱাৰীত আৰম্ভ হব ।
--------------------------------------------------

Translating ASM:  20%|████▋                  | 202/1000 [01:36<06:24,  2.08it/s]

[202/1000]
EN: India were placed in Group A alongside Pakistan, Netherlands, USA, and Namibia.
ASM: পাকিস্তান, নেদাৰলেণ্ডছ, আমেৰিকা যুক্তৰাষ্ট্ৰ আৰু নামিবিয়াৰ লগতে ভাৰতক গ্ৰুপ এত স্থান দিয়া হৈছিল ।
--------------------------------------------------

Translating ASM:  20%|████▋                  | 203/1000 [01:37<06:14,  2.13it/s]

[203/1000]
EN: Sri Lanka hosted several matches as the tournament ran across India and Sri Lanka venues.
ASM: ভাৰত আৰু শ্ৰীলংকাৰ স্থানত টুৰ্ণামেণ্টখন চলি থকাৰ বাবে শ্ৰীলংকাই কেইবাখনো মেচ আয়োজন কৰিছিল ।
--------------------------------------------------

Translating ASM:  20%|████▋                  | 204/1000 [01:37<06:08,  2.16it/s]

[204/1000]
EN: India played the opening match against the USA at Wankhede Stadium in Mumbai.
ASM: মুম্বাইৰ ৱাংখেদে ষ্টেডিয়ামত উদ্বোধনী মেচত আমেৰিকা যুক্তৰাষ্ট্ৰৰ বিৰুদ্ধে খেলিছিল ভাৰতে ।
--------------------------------------------------

Translating ASM:  20%|████▋                  | 205/1000 [01:38<06:15,  2.12it/s]

[205/1000]
EN: India faced Namibia on February 12 at Arun Jaitley Stadium in New Delhi.
ASM: নতুন দিল্লীৰ অৰুণ জেটলী ষ্টেডিয়ামত ১২ ফেব্ৰুৱাৰীত নামিবিয়াৰ বিৰুদ্ধে মুখামুখি হল ভাৰত ।
--------------------------------------------------

Translating ASM:  21%|████▋                  | 206/1000 [01:38<05:56,  2.23it/s]

[206/1000]
EN: India travelled to Colombo to play Pakistan in a group-stage match.
ASM: দলীয় পৰ্যায়ৰ খেলত পাকিস্তানৰ বিৰুদ্ধে খেলিবলৈ কলম্বোৰ অভিমুখে যাত্ৰা কৰিলে ভাৰতে ।
--------------------------------------------------

Translating ASM:  21%|████▊                  | 207/1000 [01:38<05:56,  2.22it/s]

[207/1000]
EN: Pakistan versus Netherlands was listed as a Group A fixture on February 7.
ASM: ৭ ফেব্ৰুৱাৰীত পাকিস্তান বনাম নেদাৰলেণ্ডছক গ্ৰুপ এ খেল হিচাপে তালিকাভুক্ত কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  21%|████▊                  | 208/1000 [01:39<05:45,  2.29it/s]

[208/1000]
EN: India versus USA was scheduled as a Group A match on February 7.
ASM: ভাৰত বনাম আমেৰিকা যুক্তৰাষ্ট্ৰ ৭ ফেব্ৰুৱাৰীত গ্ৰুপ এ মেচ হিচাপে নিৰ্ধাৰিত আছিল ।
--------------------------------------------------

Translating ASM:  21%|████▊                  | 209/1000 [01:39<05:57,  2.21it/s]

[209/1000]
EN: Group D fixtures began with Afghanistan playing New Zealand on February 8 in Chennai.
ASM: চেন্নাইত ৮ ফেব্ৰুৱাৰীত নিউজিলেণ্ডৰ বিৰুদ্ধে আফগানিস্তানৰ সৈতে গ্ৰুপ ডি ফিক্সচাৰ আৰম্ভ হৈছিল ।
--------------------------------------------------

Translating ASM:  21%|████▊                  | 210/1000 [01:40<06:08,  2.14it/s]

[210/1000]
EN: Canada played South Africa on February 9 at Narendra Modi Stadium in Ahmedabad.
ASM: কানাডাই ৯ ফেব্ৰুৱাৰীত আহমেদাবাদৰ নৰেন্দ্ৰ মোডী ষ্টেডিয়ামত দক্ষিণ আফ্ৰিকাৰ বিৰুদ্ধে খেলিছিল ।
--------------------------------------------------

Translating ASM:  21%|████▊                  | 211/1000 [01:40<05:46,  2.28it/s]

[211/1000]
EN: Ishan Kishan smashed 61 off 24 balls against Namibia in New Delhi.
ASM: নতুন দিল্লীত নামিবিয়াৰ বিৰুদ্ধে ২৪ টা বলত ৬১ টা ভাঙিলে ঈশান কিশনে ।
--------------------------------------------------

Translating ASM:  21%|████▉                  | 212/1000 [01:41<05:50,  2.25it/s]

[212/1000]
EN: Hardik Pandya featured prominently as India posted 209 for nine against Namibia.
ASM: নামিবিয়াৰ বিৰুদ্ধে নম্বাৰ বাবে ভাৰতে ২০৯ পষ্ট কৰাৰ লগে লগে হাৰ্দিক পাণ্ডিয়াই বিশেষ স্থান লাভ কৰে ।
--------------------------------------------------

Translating ASM:  21%|████▉                  | 213/1000 [01:41<05:55,  2.22it/s]

[213/1000]
EN: Varun Chakaravarthy took three wickets as India beat Namibia by 93 runs.
ASM: নেমিবিয়াক ৯৩ ৰানত পৰাস্ত কৰি ভাৰতে তিনিটা উইকেট দখল কৰিলে বৰুণ চাকৰবৰ্ঠীয়ে ।
--------------------------------------------------

Translating ASM:  21%|████▉                  | 214/1000 [01:41<05:32,  2.36it/s]

[214/1000]
EN: India bundled out Namibia for 116 while defending a target of 210.
ASM: ২১০ ৰ লক্ষ্য ৰক্ষা কৰি ১১৬ ৰানত নামিবিয়াক আউট কৰিলে ভাৰতে ।
--------------------------------------------------

Translating ASM:  22%|████▉                  | 215/1000 [01:42<05:35,  2.34it/s]

[215/1000]
EN: Namibia captain Gerhard Erasmus won the toss and chose to bat first.
ASM: নামিবিয়াৰ অধিনায়ক গেৰহার্ড ইৰাছামে টছটো জয় কৰি প্ৰথম বেটিং কৰিবলৈ বাছি লৈছিল ।
--------------------------------------------------

Translating ASM:  22%|████▉                  | 216/1000 [01:42<05:28,  2.38it/s]

[216/1000]
EN: India versus Namibia started at 7:00 PM IST at Arun Jaitley Stadium.
ASM: অৰুণ জেটলী ষ্টেডিয়ামত সন্ধিয়া ৭টাত আৰম্ভ ভাৰত বনাম নামিবিয়া ।
--------------------------------------------------

Translating ASM:  22%|████▉                  | 217/1000 [01:43<04:59,  2.62it/s]

[217/1000]
EN: India’s first match was a win against the USA in Mumbai.
ASM: মুম্বাইত আমেৰিকা যুক্তৰাষ্ট্ৰৰ বিৰুদ্ধে ভাৰতৰ প্ৰথমখন মেচত জয়লাভ ।
--------------------------------------------------

Translating ASM:  22%|█████                  | 218/1000 [01:43<04:45,  2.74it/s]

[218/1000]
EN: India versus Namibia was labelled as game 18 of the tournament.
ASM: ভাৰত বনাম নামিবিয়া টুৰ্ণামেণ্টৰ খেল ১৮ হিচাপে চিহ্নিত কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  22%|█████                  | 219/1000 [01:43<04:49,  2.70it/s]

[219/1000]
EN: Suryakumar Yadav led India against Namibia in the ongoing T20 World Cup.
ASM: চলিত টি২০ বিশ্বকাপত নামিবিয়াৰ বিৰুদ্ধে ভাৰতক নেতৃত্ব দিলে সূৰ্যকুমাৰ যাদৱে ।
--------------------------------------------------

Translating ASM:  22%|█████                  | 220/1000 [01:44<04:45,  2.73it/s]

[220/1000]
EN: India entered the Namibia match after beating the USA in their opener.
ASM: উন্মোচনত আমেৰিকাক পৰাস্ত কৰি নামিবিয়া মেচত প্ৰৱেশ কৰিলে ভাৰতে ।
--------------------------------------------------

Translating ASM:  22%|█████                  | 221/1000 [01:44<04:34,  2.84it/s]

[221/1000]
EN: The Pakistan government allowed the Pakistan team to play India on February 15.
ASM: পাকিস্তানৰ চৰকাৰে পাকিস্তান দলক ১৫ ফেব্ৰুৱাৰীত ভাৰতৰ বিৰুদ্ধে খেলিবলৈ অনুমতি দিছিল ।
--------------------------------------------------

Translating ASM:  22%|█████                  | 222/1000 [01:44<04:36,  2.81it/s]

[222/1000]
EN: India versus Pakistan was scheduled for Colombo after weeks of uncertainty.
ASM: সপ্তাহৰ অনিশ্চয়তাৰ পিছত ভাৰত বনাম পাকিস্তান কলম্বোৰ বাবে নিৰ্ধাৰিত আছিল ।
--------------------------------------------------

Translating ASM:  22%|█████▏                 | 223/1000 [01:45<04:42,  2.75it/s]

[223/1000]
EN: India versus Pakistan was described as a group-stage match in Colombo.
ASM: কলম্বোত ভাৰত বনাম পাকিস্তানক গ্ৰুপ পৰ্যায়ৰ মেচ বুলি বৰ্ণনা কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  22%|█████▏                 | 224/1000 [01:45<04:47,  2.70it/s]

[224/1000]
EN: The tournament was listed as featuring 55 matches across India and Sri Lanka.
ASM: ভাৰত আৰু শ্ৰীলংকাৰ ৫৫খন খেলৰ তালিকাখন এই টুৰ্ণামেণ্টত অন্তৰ্ভুক্ত কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  22%|█████▏                 | 225/1000 [01:46<05:29,  2.35it/s]

[225/1000]
EN: The schedule included Delhi, Kolkata, Ahmedabad, Chennai, Mumbai, Colombo, and Kandy venues.
ASM: তালিকাত দিল্লী, কলকাতা, আহমেদাবাদ, চেন্নাই, মুম্বাই, কলম্বো আৰু কান্দিৰ স্থানসমূহ অন্তৰ্ভুক্ত আছিল ।
--------------------------------------------------

Translating ASM:  23%|█████▏                 | 226/1000 [01:46<05:54,  2.18it/s]

[226/1000]
EN: Afghanistan faced New Zealand at M. A. Chidambaram Stadium with an 11:00 AM start.
ASM: পুৱা ১১ বজাৰ পৰা আৰম্ভণিতে এম এ চিদাম্বৰম ষ্টেডিয়ামত আফগানিস্তানে নিউজিলেণ্ডৰ মুখামুখি হৈছিল ।
--------------------------------------------------

Translating ASM:  23%|█████▏                 | 227/1000 [01:47<06:11,  2.08it/s]

[227/1000]
EN: New Zealand played UAE on February 10 at M. A. Chidambaram Stadium.
ASM: নিউজিলেণ্ডে ১০ ফেব্ৰুৱাৰীত এম এ চিদাম্বৰম ষ্টেডিয়ামত সংযুক্ত আৰব আমিৰাত খেলিছিল ।
--------------------------------------------------

Translating ASM:  23%|█████▏                 | 228/1000 [01:47<06:47,  1.89it/s]

[228/1000]
EN: Group D included UAE, New Zealand, South Africa, Afghanistan, and Canada in one pool.
ASM: একেটা পুলত সংযুক্ত আৰব আমিৰাত, নিউজিলেণ্ড, দক্ষিণ আফ্ৰিকা, আফগানিস্তান আৰু কানাডাক গ্ৰুপ ডিত অন্তৰ্ভুক্ত কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  23%|█████▎                 | 229/1000 [01:48<06:24,  2.00it/s]

[229/1000]
EN: India’s group-stage route moved from Mumbai to Delhi and then Colombo.
ASM: ভাৰতৰ গোট পৰ্যায়ৰ পথটো মুম্বাইৰ পৰা দিল্লী আৰু তাৰ পিছত কলম্বোলৈ স্থানান্তৰিত হৈছিল ।
--------------------------------------------------

Translating ASM:  23%|█████▎                 | 230/1000 [01:48<06:41,  1.92it/s]

[230/1000]
EN: The India versus Namibia match preview named Gerhard Erasmus as Namibia’s captain.
ASM: ভাৰত বনাম নামিবিয়া মেচৰ প্ৰাকদৰ্শনীৰ নামত গেৰহার্ড ইৰাছামছ নামিবিয়াৰ অধিনায়ক ।
--------------------------------------------------

Translating ASM:  23%|█████▎                 | 231/1000 [01:49<06:28,  1.98it/s]

[231/1000]
EN: A report said Abhishek Sharma underwent checks for a stomach bug in New Delhi.
ASM: এক প্ৰতিবেদনত কোৱা হৈছিল যে নতুন দিল্লীত অভিশেক শৰ্মাই পেটৰ বাগৰ বাবে পৰীক্ষা কৰিছিল ।
--------------------------------------------------

Translating ASM:  23%|█████▎                 | 232/1000 [01:49<06:46,  1.89it/s]

[232/1000]
EN: The same report said Abhishek Sharma missed India’s Namibia game despite hospital discharge.
ASM: একেটা প্ৰতিবেদনত কোৱা হৈছিল যে অভিশেক শৰ্মাই চিকিৎসালয়ৰ পৰা অব্যাহতি দিয়াৰ স্বত্ত্বেও ভাৰতৰ নামিবিয়া খেলত অনুপস্থিত হৈছিল ।
--------------------------------------------------

Translating ASM:  23%|█████▎                 | 233/1000 [01:50<06:34,  1.94it/s]

[233/1000]
EN: Sanju Samson’s World Cup debut was described as lasting only eight deliveries.
ASM: সঞ্জু চিম্চোনৰ বিশ্বকাপৰ অভিষেক কেৱল আঠটা ডেলিভাৰীহে স্থায়ী বুলি বৰ্ণনা কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  23%|█████▍                 | 234/1000 [01:50<05:59,  2.13it/s]

[234/1000]
EN: The tournament’s Group A opened across venues in India and Sri Lanka.
ASM: টুৰ্ণামেণ্টৰ গ্ৰুপ এ ভাৰত আৰু শ্ৰীলংকাৰ বিভিন্ন স্থানত আৰম্ভ হৈছিল ।
--------------------------------------------------

Translating ASM:  24%|█████▍                 | 235/1000 [01:51<05:31,  2.31it/s]

[235/1000]
EN: India’s match against Namibia was played on Thursday, February 12.
ASM: ১২ ফেব্ৰুৱাৰী বৃহস্পতিবাৰে নামিবিয়াৰ বিৰুদ্ধে ভাৰতৰ মেচখন খেলিছিল ।
--------------------------------------------------

Translating ASM:  24%|█████▍                 | 236/1000 [01:51<05:44,  2.22it/s]

[236/1000]
EN: Nepal versus Italy appeared as a live-score fixture during the T20 World Cup schedule.
ASM: টি২০ বিশ্বকাপ কাৰ্যসূচীৰ সময়ত নেপাল বনাম ইটালী লাইভ-স্কোৰ ফিক্স্টাৰ হিচাপে পৰিগণিত হৈছিল ।
--------------------------------------------------

Translating ASM:  24%|█████▍                 | 237/1000 [01:52<06:09,  2.06it/s]

[237/1000]
EN: Australia versus Zimbabwe appeared as a live-score fixture on the Indian Express cricket feed.
ASM: ইণ্ডিয়ান এক্সপ্ৰেছ ক্ৰিকেট ফিডত অষ্ট্ৰেলিয়া বনাম জিম্বাবুৱে লাইভ স্কোৰ ফিক্স্টাৰ হিচাপে পৰিগণিত হৈছিল ।
--------------------------------------------------

Translating ASM:  24%|█████▍                 | 238/1000 [01:52<06:05,  2.09it/s]

[238/1000]
EN: The Indian Express sports section highlighted India’s 93-run win over Namibia.
ASM: ইণ্ডিয়ান এক্সপ্ৰেছ ক্ৰীড়া শাখাই নামিবিয়াৰ বিৰুদ্ধে ভাৰতৰ ৯৩ ৰাণীয়া বিজয়ৰ আলোকপাত কৰে ।
--------------------------------------------------

Translating ASM:  24%|█████▍                 | 239/1000 [01:53<05:50,  2.17it/s]

[239/1000]
EN: The match report said India’s bowling attack dismantled Namibia during the chase.
ASM: খেলৰ প্ৰতিবেদনত কোৱা হৈছিল যে ভাৰতৰ বলিং আক্ৰমণে খেদৰ সময়ত নামিবিয়াক বিচ্ছিন্ন কৰিছিল ।
--------------------------------------------------

Translating ASM:  24%|█████▌                 | 240/1000 [01:53<06:02,  2.10it/s]

[240/1000]
EN: The India versus Namibia highlights credited Ishan Kishan’s 61 with driving India’s total.
ASM: ভাৰত বনাম নামিবিয়াৰ হাইলাইট ক্ৰেডিট কৰা ঈশান কিষাণৰ ৬১ গৰাকীয়ে ভাৰতৰ মুঠ ড্ৰাইভিং কৰে ।
--------------------------------------------------

Translating ASM:  24%|█████▌                 | 241/1000 [01:54<06:03,  2.09it/s]

[241/1000]
EN: ISL 2025–26 fixtures began on February 14 with a double-header format.
ASM: আই এছ এল ২০২৫২৬ ফিক্সচাৰ ১৪ ফেব্ৰুৱাৰীত দ্বৈত হেডাৰ ফৰমেটৰে আৰম্ভ হৈছিল ।
--------------------------------------------------

Translating ASM:  24%|█████▌                 | 242/1000 [01:54<06:09,  2.05it/s]

[242/1000]
EN: Mohun Bagan Super Giant faced Kerala Blasters in the season opener in Kolkata.
ASM: কলিকতাত ছিজন অপেনাৰত কেৰালা ব্লাষ্টাৰ্ছৰ মুখামুখি মহুন বাগান ছুপাৰ জায়েণ্ট ।
--------------------------------------------------

Translating ASM:  24%|█████▌                 | 243/1000 [01:55<06:03,  2.08it/s]

[243/1000]
EN: FC Goa hosted Inter Kashi at Fatorda Stadium on February 14.
ASM: ১৪ ফেব্ৰুৱাৰীত ফাটাৰ্ডা ষ্টেডিয়ামত এফ চি গোৱাৰ আয়োজক আছিল ইন্টাৰ কাশী ।
--------------------------------------------------

Translating ASM:  24%|█████▌                 | 244/1000 [01:55<05:26,  2.32it/s]

[244/1000]
EN: The first match on double-header days started at 5:00 PM IST.
ASM: দ্বৈত হেডাৰ দিনত প্ৰথমখন মেচ সন্ধিয়া ৫ বজাতে আৰম্ভ হয় ।
--------------------------------------------------

Translating ASM:  24%|█████▋                 | 245/1000 [01:55<05:09,  2.44it/s]

[245/1000]
EN: The second match on double-header days started at 7:30 PM IST.
ASM: দ্বৈত হেডাৰ দিনত দ্বিতীয়খন মেচ সন্ধিয়া ৭.৩০ বজাত আৰম্ভ হয় ।
--------------------------------------------------

Translating ASM:  25%|█████▋                 | 246/1000 [01:56<05:25,  2.31it/s]

[246/1000]
EN: A report said the ISL season would use a single-leg home-and-away format.
ASM: এটা প্ৰতিবেদনত কোৱা হৈছিল যে আইএছএল ছিজনটোৱে একক লেগৰ হোম এণ্ড আৱে ফৰমেট ব্যৱহাৰ কৰিব ।
--------------------------------------------------

Translating ASM:  25%|█████▋                 | 247/1000 [01:56<05:48,  2.16it/s]

[247/1000]
EN: The Indian Express football page reported FanCode won exclusive ISL media rights.
ASM: ইণ্ডিয়ান এক্সপ্ৰেছ ফুটবল পেজটোৱে ৰিপৰ্ট কৰিছিল যে ফেনকোডে একচেটিয়া আই এছ এলৰ মিডিয়া অধিকাৰ লাভ কৰিছিল ।
--------------------------------------------------

Translating ASM:  25%|█████▋                 | 248/1000 [01:57<05:39,  2.21it/s]

[248/1000]
EN: The same report said ISL per-match valuation dropped by about 95 percent.
ASM: একেটা প্ৰতিবেদনত কোৱা হৈছিল যে আইএছএল প্ৰতি মেচৰ মূল্যায়ন প্ৰায় ৯৫ শতাংশ হ্ৰাস পাইছে ।
--------------------------------------------------

Translating ASM:  25%|█████▋                 | 249/1000 [01:57<05:36,  2.23it/s]

[249/1000]
EN: The ISL report described a truncated season with pay cuts at multiple clubs.
ASM: আই এছ এলৰ প্ৰতিবেদনত একাধিক ক্লাবত দৰমহা হ্ৰাসৰ সৈতে এটা চুটি ঋতু বৰ্ণনা কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  25%|█████▊                 | 250/1000 [01:58<05:57,  2.10it/s]

[250/1000]
EN: Real Madrid CF hoped a La Liga surge was boosted by a team dinner.
ASM: ৰিয়েল মাড্ৰিড চি এফে আশা কৰিছিল যে এটা দলীয় ডিনাৰৰ দ্বাৰা লা লিগা বৃদ্ধি বৃদ্ধি কৰা হ'ব ।
--------------------------------------------------

Translating ASM:  25%|█████▊                 | 251/1000 [01:58<06:15,  1.99it/s]

[251/1000]
EN: The Real Madrid dinner was reportedly paid for by Vinícius Júnior and Kylian Mbappé.
ASM: ৰিয়েল মাড্ৰিডৰ ডিনাৰৰ বাবে বিনেচিয়াছ জুনিয়ৰ আৰু কিলিয়ান এমবাপেৰে ধন খৰচ কৰিছিল বুলি জানিব পৰা গৈছে ।
--------------------------------------------------

Translating ASM:  25%|█████▊                 | 252/1000 [01:59<05:57,  2.09it/s]

[252/1000]
EN: Barcelona aimed for a fourth straight league win against Girona in La Liga.
ASM: লা লিগত জিৰোনাৰ বিৰুদ্ধে একেৰাহে চতুৰ্থটো লীগ জয়ৰ লক্ষ্য বাৰাচেলোনাৰ ।
--------------------------------------------------

Translating ASM:  25%|█████▊                 | 253/1000 [01:59<06:07,  2.03it/s]

[253/1000]
EN: Barcelona visited Atlético Madrid for a Copa del Rey first-leg clash.
ASM: কপা দেল ৰায়ৰ প্ৰথম লেগৰ সংঘৰ্ষৰ বাবে বাৰ্চেলোনাই এট্লেটিক মেড্ৰিড ভ্ৰমণ কৰে ।
--------------------------------------------------

Translating ASM:  25%|█████▊                 | 254/1000 [02:00<06:05,  2.04it/s]

[254/1000]
EN: Barcelona entered the Atlético Madrid match after winning 17 of 18 matches.
ASM: ১৮ খন খেলৰ ১৭ খনত জয়লাভ কৰি এট্লেটিক মেড্ৰিডৰ খেলত প্ৰৱেশ বাৰ্ছেলোনাৰ ।
--------------------------------------------------

Translating ASM:  26%|█████▊                 | 255/1000 [02:00<05:52,  2.11it/s]

[255/1000]
EN: Real Madrid and UEFA announced an agreement ending the Super League project.
ASM: ৰিয়েল মাড্ৰিড আৰু য়ু ই এফে ছুপাৰ লীগ প্ৰকল্প সমাপ্ত কৰাৰ বাবে এক চুক্তি ঘোষণা কৰে ।
--------------------------------------------------

Translating ASM:  26%|█████▉                 | 256/1000 [02:01<05:49,  2.13it/s]

[256/1000]
EN: Barcelona formally pulled out of the Super League days before the agreement.
ASM: চুক্তিৰ কেইদিনমান পূৰ্বেই ছুপাৰ লীগৰ পৰা আনুষ্ঠানিকভাৱে আঁতৰি গল বাৰ্চেলোনা ।
--------------------------------------------------

Translating ASM:  26%|█████▉                 | 257/1000 [02:01<06:39,  1.86it/s]

[257/1000]
EN: Tottenham Hotspur reportedly sacked Thomas Frank after a 2–1 loss to Newcastle United.
ASM: নিউয়াকাল্ট য়ুনাইটেডৰ হাতত ২-১ ব্যৱধানত পৰাস্ত হোৱাৰ পিছত টটেনহাম হটস্পৰে থমাছ ফ্ৰাংকক নিলম্বন কৰা বুলি জানিব পৰা গৈছে ।
--------------------------------------------------

Translating ASM:  26%|█████▉                 | 258/1000 [02:02<06:07,  2.02it/s]

[258/1000]
EN: The Tottenham report said the club still had no league win in 2026.
ASM: টটেনহামৰ প্ৰতিবেদনত কোৱা হৈছিল যে ২০২৬ চনত ক্লাবটোৰ এতিয়াও লীগ জয় হোৱা নাছিল ।
--------------------------------------------------

Translating ASM:  26%|█████▉                 | 259/1000 [02:02<05:56,  2.08it/s]

[259/1000]
EN: Wayne Rooney said Arsenal looked mentally stronger in the Premier League title race.
ASM: ৱেইন ৰুনিয়ে কয় যে প্ৰিমিয়াৰ লীগ খিতাপৰ দৌৰত আৰ্ছেনেল মানসিকভাৱে অধিক শক্তিশালী লাগিছিল ।
--------------------------------------------------

Translating ASM:  26%|█████▉                 | 260/1000 [02:03<06:02,  2.04it/s]

[260/1000]
EN: Rooney noted Arsenal last won the Premier League title in the 2003–04 season.
ASM: ৰুনিয়ে উল্লেখ কৰে যে ২০০৩-০৪ৰ ছিজনত আৰ্ছেলে প্ৰিমিয়াৰ লীগ খিতাপ অন্তিমবাৰ জয় কৰিছিল ।
--------------------------------------------------

Translating ASM:  26%|██████                 | 261/1000 [02:03<06:09,  2.00it/s]

[261/1000]
EN: Rooney said Arsenal led Manchester City by six points with 13 games remaining.
ASM: ৰুনিয়ে কয় যে ১৩ খন খেল বাকী থকাৰ লগে লগে আৰ্ছেনেলে ছটা পইণ্টেৰে মেনচেষ্টাৰ চিটীক নেতৃত্ব দিছিল ।
--------------------------------------------------

Translating ASM:  26%|██████                 | 262/1000 [02:04<06:12,  1.98it/s]

[262/1000]
EN: Cristiano Ronaldo missed a second straight Saudi Pro League match for Al-Nassr.
ASM: আল-নছৰৰ হৈ ক্ৰিষ্টিয়ান ৰল্ডোৱে একেৰাহে দ্বিতীয়বাৰ ছৌডি প্ৰ লীগৰ মেচ হেৰুৱালে ।
--------------------------------------------------

Translating ASM:  26%|██████                 | 263/1000 [02:04<06:41,  1.84it/s]

[263/1000]
EN: Al-Nassr beat Al-Ittihad 2–0 despite Cristiano Ronaldo’s continued absence.
ASM: ক্ৰিষ্টিয়ানো ৰনাল্ডোৰ অবিৰত অনুপস্থিতিৰ স্বত্ত্বেও আল-নাছৰে আল-ইট্টিহাদক ২-০ গলত পৰাস্ত কৰে ।
--------------------------------------------------

Translating ASM:  26%|██████                 | 264/1000 [02:05<06:43,  1.82it/s]

[264/1000]
EN: Sadio Mané and Angelo Gabriel scored for Al-Nassr in the win over Al-Ittihad.
ASM: আল-ইট্টিহাদৰ বিৰুদ্ধে বিজয়ত আল-নছৰৰ হৈ গল ছাদিঅ মেনে আৰু এঞ্জেল গেব্ৰিয়েল ।
--------------------------------------------------

Translating ASM:  26%|██████                 | 265/1000 [02:05<06:32,  1.87it/s]

[265/1000]
EN: Sumit Nagal headlined the Delhi Open 2026 at the DLTA Complex.
ASM: ডিএলটিএ কমপ্লেক্ছত অনুষ্ঠিত দিল্লী অপেন ২০২৬ৰ শীৰ্ষস্থান দখল কৰিলে সুমিত নাগলে ।
--------------------------------------------------

Translating ASM:  27%|██████                 | 266/1000 [02:06<06:09,  1.98it/s]

[266/1000]
EN: The Delhi Open 2026 tournament was scheduled for February 16 to 22.
ASM: দিল্লী অপেন ২০২৬ টুৰ্ণামেণ্ট ১৬ৰ পৰা ২২ ফেব্ৰুৱাৰীলৈ নিৰ্ধাৰিত আছিল ।
--------------------------------------------------

Translating ASM:  27%|██████▏                | 267/1000 [02:06<06:17,  1.94it/s]

[267/1000]
EN: Britain’s Jay Clarke was named as a leading overseas entrant for Delhi Open 2026.
ASM: দিল্লী অপেন ২০২৬ৰ বাবে আগশাৰীৰ বিদেশী প্ৰৱেশকাৰী হিচাপে নামকৰণ কৰা হৈছে ব্ৰিটেইনৰ জে ক্লাৰ্কক ।
--------------------------------------------------

Translating ASM:  27%|██████▏                | 268/1000 [02:07<05:55,  2.06it/s]

[268/1000]
EN: The Delhi Open note said Sumit Nagal gained direct entry into the main draw.
ASM: দিল্লী অপেন নোটত কোৱা হৈছিল যে মুখ্য ড্ৰত সুমিত নাগলে প্ৰত্যক্ষ প্ৰৱেশ লাভ কৰিছিল ।
--------------------------------------------------

Translating ASM:  27%|██████▏                | 269/1000 [02:07<05:41,  2.14it/s]

[269/1000]
EN: India beat the Netherlands 3–2 in Davis Cup competition to move closer.
ASM: ডেভিছ কাপ প্ৰতিযোগিতাত নেদাৰলেণ্ডক ৩-২ গলত পৰাস্ত কৰি আগবাঢ়ি আহিল ভাৰত ।
--------------------------------------------------

Translating ASM:  27%|██████▏                | 270/1000 [02:08<05:42,  2.13it/s]

[270/1000]
EN: Dhakshineswar Suresh featured prominently during India’s Davis Cup tie against the Netherlands.
ASM: নেদাৰলেণ্ডৰ বিৰুদ্ধে ভাৰতৰ ডেভিছ কাপৰ টী সময়ত দাক্ষিনেশ্বৰ সুৰেশক বিশেষ আকৰ্ষণ ।
--------------------------------------------------

Translating ASM:  27%|██████▏                | 271/1000 [02:08<05:45,  2.11it/s]

[271/1000]
EN: India’s doubles pair beat David Pel and Sander Arends in a tight five-setter.
ASM: টান ফাইভ ছেটাৰত ডেভিদ পেল আৰু ছান্ডাৰ এৰেণ্ডক পৰাস্ত কৰিলে ভাৰতৰ ডব্লিছ পেৰে ।
--------------------------------------------------

Translating ASM:  27%|██████▎                | 272/1000 [02:09<05:38,  2.15it/s]

[272/1000]
EN: The doubles win was described as India’s first in five playoff ties versus Europeans.
ASM: ডাবলছ বিজয়ক ইউৰোপীয়ানৰ বিৰুদ্ধে পাঁচখন প্লেঅফ ড্ৰত ভাৰতৰ প্ৰথমটো জয় বুলি বৰ্ণনা কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  27%|██████▎                | 273/1000 [02:09<05:44,  2.11it/s]

[273/1000]
EN: The same report said Sumit Nagal failed to seal the tie in reverse singles.
ASM: একেটা প্ৰতিবেদনত কোৱা হৈছিল যে ৰিভাৰ্ছ ছিংগলছত সমতা ছীল কৰাত সুমিত নাগলে বিফল হৈছিল ।
--------------------------------------------------

Translating ASM:  27%|██████▎                | 274/1000 [02:10<05:44,  2.11it/s]

[274/1000]
EN: Novak Djokovic said he still wanted to represent Serbia in Davis Cup.
ASM: ডেভিছ কাপত চাৰ্বিয়াৰ হৈ প্ৰতিনিধিত্ব কৰিবলৈ এতিয়াও ইচ্ছা আছে বুলি জানিবলৈ দিয়ে নোভাক জকোভিচে ।
--------------------------------------------------

Translating ASM:  28%|██████▎                | 275/1000 [02:10<05:58,  2.02it/s]

[275/1000]
EN: Serbia captain Viktor Troicki described Novak Djokovic as a major team figure.
ASM: ছাৰ্বিয়াৰ অধিনায়ক ভিক্টৰ ট্ৰয়িক্কে নোভাক জকোভিচক এটা মুখ্য দলীয় ব্যক্তি বুলি বৰ্ণনা কৰে ।
--------------------------------------------------

Translating ASM:  28%|██████▎                | 276/1000 [02:11<06:09,  1.96it/s]

[276/1000]
EN: Novak Djokovic withdrew from a 2025 Davis Cup qualifier due to a hamstring injury.
ASM: হামষ্ট্ৰিং আঘাতৰ বাবে ২০২৫ চনৰ ডেভিছ কাপ কোৱালিফায়াৰৰ পৰা আঁতৰি গল নোভাক জকোভিচ ।
--------------------------------------------------

Translating ASM:  28%|██████▎                | 277/1000 [02:11<06:28,  1.86it/s]

[277/1000]
EN: Carlos Alcaraz beat Alexander Zverev in a five-hour, 27-minute Australian Open semifinal.
ASM: পাঁচ ঘণ্টা ২৭ মিনিটত অষ্ট্ৰেলিয়ান অপেনৰ ছেমিফাইনেলত আলেকজেণ্ডাৰ জেভেৰভক পৰাস্ত কাৰ্লছ অলকাৰাজ ।
--------------------------------------------------

Translating ASM:  28%|██████▍                | 278/1000 [02:12<06:27,  1.86it/s]

[278/1000]
EN: Carlos Alcaraz won the Australian Open final after facing Novak Djokovic.
ASM: নোভাক জকভিচৰ মুখামুখি হৈ অষ্ট্ৰেলিয়ান অপেনৰ ফাইনেলত জয় কাৰ্লছ অলকাৰাজৰ ।
--------------------------------------------------

Translating ASM:  28%|██████▍                | 279/1000 [02:12<06:15,  1.92it/s]

[279/1000]
EN: Jannik Sinner was described as holding five straight wins over Novak Djokovic.
ASM: জাননিক সীনাৰক নোভাক জকভিচৰ বিৰুদ্ধে একেৰাহে পাঁচখন জয় দখল কৰা বুলি বৰ্ণনা কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  28%|██████▍                | 280/1000 [02:13<06:44,  1.78it/s]

[280/1000]
EN: The Djokovic–Sinner preview said Djokovic reached semifinals aided by a walkover and retirement.
ASM: জকভিকৰ সিনাৰ প্ৰিভিউত কোৱা হৈছিল যে জকভিকে ৱাকঅভাৰ আৰু অৱসৰৰ সহায়ত ছেমিফাইনেলত প্ৰৱেশ কৰিছিল ।
--------------------------------------------------

Translating ASM:  28%|██████▍                | 281/1000 [02:13<06:50,  1.75it/s]

[281/1000]
EN: An Australian Open report said extreme heat forced temporary suspensions on outside courts.
ASM: অষ্ট্ৰেলিয়ান অপেনৰ এটা প্ৰতিবেদনত কোৱা হৈছিল যে অতিমাত্ৰা গৰমে বাহিৰৰ আদালতবোৰত অস্থায়ীভাৱে স্থগিত ৰাখিবলৈ বাধ্য কৰিছিল ।
--------------------------------------------------

Translating ASM:  28%|██████▍                | 282/1000 [02:14<06:28,  1.85it/s]

[282/1000]
EN: The same report said organisers issued heat warnings for players and spectators.
ASM: একেটা প্ৰতিবেদনত কোৱা হৈছিল যে আয়োজকসকলে খেলুৱৈ আৰু দৰ্শকসকলৰ বাবে তাপ সতৰ্কবাণী জাৰি কৰিছিল ।
--------------------------------------------------

Translating ASM:  28%|██████▌                | 283/1000 [02:15<06:35,  1.81it/s]

[283/1000]
EN: Jannik Sinner beat Eliot Spizzirri 4–6, 6–3, 6–4, 6–4 in Melbourne.
ASM: মেলবৰ্ণত এলিয়ট স্পিজিৰিৰীক ৪-৬, ৬-৩, ৬-৪, ৬-৪ গলত পৰাস্ত জাননিক সিনাৰ ।
--------------------------------------------------

Translating ASM:  28%|██████▌                | 284/1000 [02:15<06:28,  1.84it/s]

[284/1000]
EN: A tennis feature said Fangran Tian was coached by Chennai’s Mangal Sriram since age 12.
ASM: এটা টেনিছ ফিচাৰৰ মতে ফাংৰাণ টিয়ানক ১২ বছৰ বয়সৰ পৰাই চেন্নাইৰ মঙ্গলশ্ৰীৰমে প্ৰশিক্ষণ দিছিল ।
--------------------------------------------------

Translating ASM:  28%|██████▌                | 285/1000 [02:16<06:34,  1.81it/s]

[285/1000]
EN: Badminton World Federation demoted Syed Modi International from Super 300 to Super 100.
ASM: বেডমিণ্টন বিশ্ব ফেডাৰেশ্যনে ছায়দ মোডী আন্তঃৰাষ্ট্ৰীয় ছুপাৰ ৩০০ৰ পৰা ছুপাৰ ১০০লৈ নামিলে ।
--------------------------------------------------

Translating ASM:  29%|██████▌                | 286/1000 [02:16<06:38,  1.79it/s]

[286/1000]
EN: The same report said India Open retained Super 750 status for the 2027–2030 cycle.
ASM: একেটা প্ৰতিবেদনত কোৱা হৈছিল যে ইণ্ডিয়া অপেন ২০২৭২০৩০ চক্রৰ বাবে ছুপাৰ ৭৫০ স্থিতি বজাই ৰাখিছে ।
--------------------------------------------------

Translating ASM:  29%|██████▌                | 287/1000 [02:17<06:33,  1.81it/s]

[287/1000]
EN: A badminton reforms report said World Championships and five Super 1000s will run 11 days.
ASM: বেডমিণ্টন সংস্কাৰৰ এক প্ৰতিবেদনত কোৱা হৈছিল যে বিশ্ব চেম্পিয়নশ্বিপ আৰু পাঁচটা ছুপাৰ ১০০০ ১১ দিনত চলিব ।
--------------------------------------------------

Translating ASM:  29%|██████▌                | 288/1000 [02:17<06:40,  1.78it/s]

[288/1000]
EN: The Indian Express said BWF’s AGM 2026 would vote on a 3×15 scoring format.
ASM: ইণ্ডিয়ান এক্সপ্ৰেছে কয় যে বিডব্লিউএফৰ এজিএম ২০২৬ 3x১৫ স্কোৰিং ফৰমেটত ভোট দিব ।
--------------------------------------------------

Translating ASM:  29%|██████▋                | 289/1000 [02:18<06:28,  1.83it/s]

[289/1000]
EN: A Badminton Asia Team report said India lost 3–2 to Japan in men’s ties.
ASM: বেডমিণ্টন এছিয়া দলৰ এক প্ৰতিবেদনত কোৱা হৈছে যে পুৰুষৰ টাইত ভাৰতে জাপানৰ হাতত ৩-২ ব্যৱধানত পৰাস্ত হৈছে ।
--------------------------------------------------

Translating ASM:  29%|██████▋                | 290/1000 [02:18<06:11,  1.91it/s]

[290/1000]
EN: The same report said India lost to Thailand in women’s ties at the team event.
ASM: একেটা প্ৰতিবেদনত কোৱা হৈছিল যে দলীয় ইভেণ্টত মহিলাৰ টাইত ভাৰতে থাইলেণ্ডৰ হাতত পৰাস্ত হৈছিল ।
--------------------------------------------------

Translating ASM:  29%|██████▋                | 291/1000 [02:19<06:02,  1.96it/s]

[291/1000]
EN: A selection report said Tanvi Sharma would play first singles after Unnati Hooda was out.
ASM: এটা নিৰ্বাচনী প্ৰতিবেদনত কোৱা হৈছিল যে অননতি হুডাৰ আউট হোৱাৰ পিছত তনভি শৰ্মাই প্ৰথম ছিংগেল খেলিব ।
--------------------------------------------------

Translating ASM:  29%|██████▋                | 292/1000 [02:19<06:21,  1.85it/s]

[292/1000]
EN: An India Open report said “nest materials” halted a women’s doubles semifinal in Delhi.
ASM: এখন ইণ্ডিয়া অপেন ৰিপোৰ্টত কোৱা হৈছিল যে নেষ্ট মেট্ৰিয়েলে দিল্লীত মহিলা ডাবলছৰ ছেমি ফাইনেলত বাধা দিছিল ।
--------------------------------------------------

Translating ASM:  29%|██████▋                | 293/1000 [02:20<06:01,  1.96it/s]

[293/1000]
EN: A feature said An Se-young won 94.8 percent of her matches in 2025.
ASM: এটা বৈশিষ্ট্যত কোৱা হৈছিল যে আন চে-ইংয়ে ২০২৫ চনত তেওঁৰ ৯৪.৮ শতাংশ মেচত জয়লাভ কৰিছিল ।
--------------------------------------------------

Translating ASM:  29%|██████▊                | 294/1000 [02:20<05:47,  2.03it/s]

[294/1000]
EN: The same feature said An Se-young began 2026 with two titles in two weeks.
ASM: একে বৈশিষ্ট্যটোৱে কৈছিল যে আন চে-ইংয়ে ২০২৬ চনত দুসপ্তাহৰ ভিতৰত দুটা খিতাপৰ সৈতে আৰম্ভ কৰিছিল ।
--------------------------------------------------

Translating ASM:  30%|██████▊                | 295/1000 [02:21<06:06,  1.93it/s]

[295/1000]
EN: Lin Chun-yi beat Jonatan Christie 21–10, 21–18 in the India Open final.
ASM: ইণ্ডিয়া অপেন ফাইনেলত ২১-১০, ২১-১৮ গলত জোনাটান ক্ৰিষ্টিক পৰাস্ত লিন চান-ইৰ ।
--------------------------------------------------

Translating ASM:  30%|██████▊                | 296/1000 [02:21<06:12,  1.89it/s]

[296/1000]
EN: Devika Sihag beat Navya Kanderi 21–10, 21–13 to win in Baku.
ASM: নাৱিয়া কান্দেৰীক ২১-১০, ২১-১৩ ব্যৱধানত পৰাস্ত কৰি বাকুত বিজয়ী হল দেৱিকা শিহগ ।
--------------------------------------------------

Translating ASM:  30%|██████▊                | 297/1000 [02:22<06:17,  1.86it/s]

[297/1000]
EN: Radhika Sharma won her first mixed doubles title partnering Sathwik Reddy.
ASM: সতৱিক ৰেড্ডীৰ সৈতে অংশীদাৰীত্বত ৰাধিকা শৰ্মাই নিজৰ প্ৰথমখন মিশ্ৰিত দ্বৈত খিতাপ অৰ্জন কৰিলে ।
--------------------------------------------------

Translating ASM:  30%|██████▊                | 298/1000 [02:23<06:34,  1.78it/s]

[298/1000]
EN: Ankur Bhattacharjee upset world-ranked opponent Bourrassaud 3–1 at WTT Chennai.
ASM: ডব্লিউটিটি চেন্নাইত বিশ্বমানৰ প্ৰতিদ্বন্দ্বী বৰাছৌড ৩-১ গলত অসন্তুষ্ট আনকুৰ ভট্টাচাৰ্য ।
--------------------------------------------------

Translating ASM:  30%|██████▉                | 299/1000 [02:23<06:26,  1.81it/s]

[299/1000]
EN: FIFA president Gianni Infantino faced criticism over high-priced tickets for the 2026 World Cup.
ASM: ২০২৬ৰ বিশ্বকাপলৈ ব্যয়বহুল টিকটৰ বাবে সমালোচনাৰ সন্মুখীন হৈছিল ফিফা সভাপতি জিয়াননী ইনফান্টিনো ।
--------------------------------------------------

Translating ASM:  30%|██████▉                | 300/1000 [02:24<06:20,  1.84it/s]

[300/1000]
EN: India lost 1-3 to Belgium in the FIH Pro League opener at Rourkela.
ASM: ৰৌৰকেলাত অনুষ্ঠিত এফআইএইচ প্ৰ লীগ উদ্বোধনী খেলত বেলজিয়ামৰ হাতত ভাৰত ১-৩ গলত পৰাস্ত ।
--------------------------------------------------

Translating ASM:  30%|██████▉                | 301/1000 [02:24<06:02,  1.93it/s]

[301/1000]
EN: Craig Fulton said India’s defensive structure did not deliver in the Pro League opener.
ASM: ক্ৰেইগ ফুল্টনে কয় যে ভাৰতৰ প্ৰতিৰক্ষামূলক গাঁথনিয়ে প্ৰ লীগ উদ্বোধনত প্ৰদান কৰা নাছিল ।
--------------------------------------------------

Translating ASM:  30%|██████▉                | 302/1000 [02:25<05:55,  1.96it/s]

[302/1000]
EN: India then suffered a 0-8 loss to Argentina in the next Pro League match.
ASM: তাৰ পিছত পৰৱৰ্তী প্ৰ লীগ মেচত ভাৰতে আৰ্জেণ্টিনাৰ হাতত ০-৮ ব্যৱধানত পৰাস্ত হৈছিল ।
--------------------------------------------------

Translating ASM:  30%|██████▉                | 303/1000 [02:25<05:44,  2.03it/s]

[303/1000]
EN: India’s 0-8 defeat was described as a systematic demolition by Argentina.
ASM: ভাৰতৰ ০-৮ত পৰাজয়ক আৰ্জেণ্টিনাই এক পদ্ধতিগত ভাঙি পেলোৱা বুলি বৰ্ণনা কৰিছিল ।
--------------------------------------------------

Translating ASM:  30%|██████▉                | 304/1000 [02:26<05:34,  2.08it/s]

[304/1000]
EN: India’s 0-8 loss matched the joint third-worst defeat in India’s hockey history.
ASM: ভাৰতৰ ০-৮ৰ পৰাজয় ভাৰতৰ হকী ইতিহাসৰ তৃতীয় সৰ্ব্বনাশৰ যুটীয়া পৰাজয়ৰ সমতুল্য ।
--------------------------------------------------

Translating ASM:  30%|███████                | 305/1000 [02:26<05:25,  2.13it/s]

[305/1000]
EN: India’s other 0-8 losses came in 1985 versus Netherlands and 2010 versus Australia.
ASM: ভাৰতৰ অন্য ০-৮ পৰাজয় ১৯৮৫ চনত নেদাৰলেণ্ডৰ বিৰুদ্ধে আৰু ২০১০ চনত অষ্ট্ৰেলিয়াৰ বিৰুদ্ধে হৈছিল ।
--------------------------------------------------

Translating ASM:  31%|███████                | 306/1000 [02:26<05:19,  2.17it/s]

[306/1000]
EN: Argentina’s Tomas Domene scored four goals in the 0-8 win over India.
ASM: ভাৰতৰ বিৰুদ্ধে ০-৮ গলত চাৰিটা গল অৰ্জন আৰ্জেণ্টিনাৰ টমাছ ডোমেনৰ ।
--------------------------------------------------

Translating ASM:  31%|███████                | 307/1000 [02:27<05:00,  2.31it/s]

[307/1000]
EN: Tomas Domene scored at 15th, 20th, 26th and 60th minutes against India.
ASM: ভাৰতৰ বিৰুদ্ধে ১৫, ২০, ২৬ আৰু ৬০ মিনিটত গল টমাছ ডোমেনৰ ।
--------------------------------------------------

Translating ASM:  31%|███████                | 308/1000 [02:27<05:50,  1.98it/s]

[308/1000]
EN: Tomas Ruiz, Lucio Mendez, Ignacio Ibarra, and Nicolas della Torre also scored for Argentina.
ASM: টমাছ ৰুইজ, লুচিয়ো মেণ্ডেজ, ইগনাচিয়ো ইবাৰ্ৰা, আৰু নিকোলাস দেলা টৰেও আৰ্জেণ্টিনাৰ হৈ গল ।
--------------------------------------------------

Translating ASM:  31%|███████                | 309/1000 [02:28<05:26,  2.11it/s]

[309/1000]
EN: India’s third quarter without conceding a goal looked like an anomaly in the match.
ASM: গল নিদিয়াকৈয়ে ভাৰতৰ তৃতীয় কোৱাৰ্টাৰ মেচত অস্বাভাৱিক যেন লাগিছিল ।
--------------------------------------------------

Translating ASM:  31%|███████▏               | 310/1000 [02:28<05:30,  2.08it/s]

[310/1000]
EN: Player-of-the-Match Tomas Domene said Argentina played the whole game at 100 percent.
ASM: খেলৰ শ্ৰেষ্ঠ খেলুৱৈ টমাছ ডোমেইনে কয় যে আৰ্জেণ্টিনাই সমগ্ৰ খেলটো ১০০ শতাংশত খেলিছিল ।
--------------------------------------------------

Translating ASM:  31%|███████▏               | 311/1000 [02:29<05:40,  2.02it/s]

[311/1000]
EN: Tomas Domene said Argentina were disappointed after losing 3-5 to Belgium previously.
ASM: টমাছ ডোমেনে কয় যে আগৰ বেলজিয়ামৰ হাতত ৩-৫ ব্যৱধানত পৰাস্ত হোৱাৰ পিছত আৰ্জেণ্টিনা নিৰাশ হৈছে ।
--------------------------------------------------

Translating ASM:  31%|███████▏               | 312/1000 [02:29<05:14,  2.19it/s]

[312/1000]
EN: Argentina scored two quick goals at the end of the first quarter.
ASM: প্ৰথম কোৱাৰ্টাৰৰ শেষত আৰ্জেণ্টিনাই দুটা দ্ৰুত গল অৰ্জন কৰে ।
--------------------------------------------------

Translating ASM:  31%|███████▏               | 313/1000 [02:30<04:52,  2.35it/s]

[313/1000]
EN: Argentina scored five goals in 10 minutes during the second quarter.
ASM: দ্বিতীয় কোৱাৰ্টাৰত ১০ মিনিটৰ ভিতৰত পাঁচটা গল অৰ্জন আৰ্জেণ্টিনাই ।
--------------------------------------------------

Translating ASM:  31%|███████▏               | 314/1000 [02:30<04:56,  2.31it/s]

[314/1000]
EN: Harmanpreet Singh missed two penalty strokes in the match against Argentina.
ASM: আৰ্জেণ্টিনাৰ বিৰুদ্ধে খেলত দুটাকৈ পেনেলটি ষ্ট্ৰোক হেৰুৱালে হৰমনপ্ৰীত সিঙে ।
--------------------------------------------------

Translating ASM:  32%|███████▏               | 315/1000 [02:31<05:10,  2.21it/s]

[315/1000]
EN: India missed three penalty corners during the 0-8 defeat against Argentina.
ASM: আৰ্জেণ্টিনাৰ বিৰুদ্ধে ০-৮ ব্যৱধানত পৰাস্ত ভাৰতৰ তিনিখন পেনেলটি কৰ্ণাৰ্ণ হেৰুৱালে ভাৰতে ।
--------------------------------------------------

Translating ASM:  32%|███████▎               | 316/1000 [02:31<05:00,  2.28it/s]

[316/1000]
EN: India goalkeepers Suraj Karkera and Pawan looked completely out of place.
ASM: ভাৰতৰ গলকীপাৰ সুৰজ কাৰ্কেৰা আৰু পৱন সম্পূৰ্ণৰূপে স্থানৰ পৰা আঁতৰি পৰিছিল ।
--------------------------------------------------

Translating ASM:  32%|███████▎               | 317/1000 [02:31<05:09,  2.21it/s]

[317/1000]
EN: Argentina dominated possession and toyed with India’s midfield and defence.
ASM: আৰ্জেণ্টিনাই অধিকাৰত আধিপত্য বিস্তাৰ কৰিছিল আৰু ভাৰতৰ মিডফিল্ড আৰু প্ৰতিৰক্ষাৰ সৈতে খেলিছিল ।
--------------------------------------------------

Translating ASM:  32%|███████▎               | 318/1000 [02:32<04:51,  2.34it/s]

[318/1000]
EN: Argentina’s win catapulted them to fourth in the nine-team standings.
ASM: আৰ্জেণ্টিনাৰ জয়ই তেওঁলোকক নটা দলৰ তালিকাত চতুৰ্থ স্থানলৈ উন্নীত কৰে ।
--------------------------------------------------

Translating ASM:  32%|███████▎               | 319/1000 [02:32<05:06,  2.22it/s]

[319/1000]
EN: India next faced world No.2 Belgium again after the heavy Argentina loss.
ASM: ভাৰতে পৰৱৰ্তী সময়ত আৰ্জেণ্টিনাৰ গধুৰ পৰাস্তিৰ পিছত পুনৰ বিশ্ব নং ২ বেলজিয়ামৰ মুখামুখি হৈছিল ।
--------------------------------------------------

Translating ASM:  32%|███████▎               | 320/1000 [02:33<05:37,  2.01it/s]

[320/1000]
EN: Macklin Celebrini scored early to spark Canada’s 5-0 win over Czech Republic.
ASM: চেক ৰিপাব্লিকৰ বিৰুদ্ধে কানাডাৰ ৫-০ ব্যৱধানত জয়ী হবলৈ ম্যাক্লেন চেলেব্ৰিনিয়ে প্ৰাৰম্ভিকভাৱে গল ।
--------------------------------------------------

Translating ASM:  32%|███████▍               | 321/1000 [02:33<05:23,  2.10it/s]

[321/1000]
EN: Macklin Celebrini scored with just over five seconds left in the first period.
ASM: প্ৰথম পৰ্যায়ত পাঁচ ছেকেণ্ডতকৈ অলপ বেছি বাকী থকাৰ লগে লগে মেকলিন চেলেব্ৰিনিয়ে গল ।
--------------------------------------------------

Translating ASM:  32%|███████▍               | 322/1000 [02:34<05:38,  2.01it/s]

[322/1000]
EN: Mark Stone, Bo Horvat, Nathan MacKinnon and Nick Suzuki scored in Canada’s opener.
ASM: কানাডাৰ ওপেনাৰত গল মাৰক ষ্টোন, ব হৰভেট, নাথান মেককিনন আৰু নিক ছুজুকীৰ ।
--------------------------------------------------

Translating ASM:  32%|███████▍               | 323/1000 [02:34<05:35,  2.02it/s]

[323/1000]
EN: Connor McDavid recorded three assists in Canada’s 5-0 Olympic win.
ASM: কানাৰ মেকডেভিডে কানাডাৰ ৫-০ৰ অলিম্পিক জয়ত তিনিটা এচিষ্ট ৰেকৰ্ড কৰে ।
--------------------------------------------------

Translating ASM:  32%|███████▍               | 324/1000 [02:35<05:41,  1.98it/s]

[324/1000]
EN: Sidney Crosby said Celebrini’s first Olympic goal was huge to get Canada going.
ASM: চেলিব্ৰিনীৰ প্ৰথমটো অলিম্পিকৰ গল কানাডাক আগুৱাই নিয়াৰ বাবে বৃহৎ বুলি চিডনী ক্ৰছ্বিয়ে কয় ।
--------------------------------------------------

Translating ASM:  32%|███████▍               | 325/1000 [02:35<05:22,  2.09it/s]

[325/1000]
EN: Jon Cooper said Macklin Celebrini plays the game well beyond his years.
ASM: জোন কুপাৰে কয় যে মেকলিন চেলিব্ৰিনি তেওঁৰ বয়সতকৈ বহু বেছি খেলিছে ।
--------------------------------------------------

Translating ASM:  33%|███████▍               | 326/1000 [02:36<05:07,  2.19it/s]

[326/1000]
EN: Canada planned to face Switzerland at the Milano Arena the next day.
ASM: কানাডাই পিছদিনা মিলান এৰানাত ছুইজাৰলেণ্ডৰ মুখামুখি হোৱাৰ পৰিকল্পনা কৰিছিল ।
--------------------------------------------------

Translating ASM:  33%|███████▌               | 327/1000 [02:36<05:24,  2.08it/s]

[327/1000]
EN: Choi Ga-on won women’s snowboard halfpipe gold after recovering from a first-run crash.
ASM: প্ৰথম ৰাণৰ দুৰ্ঘটনাৰ পৰা আৰোগ্য লাভ কৰি মহিলা স্নোবোৰ্ডৰ হাফ পাইপ স্বৰ্ণ পদক অৰ্জন কৰিলে চোই গা-অনে ।
--------------------------------------------------

Translating ASM:  33%|███████▌               | 328/1000 [02:37<05:09,  2.17it/s]

[328/1000]
EN: Chloe Kim took silver and Mitsuki Ono won bronze in the halfpipe event.
ASM: হাব পাইপ ইভেণ্টত ক্লোই কিমে ৰূপ আৰু মিচুকী ওনোৱে ব্ৰঞ্জ অৰ্জন কৰে ।
--------------------------------------------------

Translating ASM:  33%|███████▌               | 329/1000 [02:37<05:22,  2.08it/s]

[329/1000]
EN: Choi Ga-on scored 90.25 to beat Chloe Kim’s leading 88 score.
ASM: চোই গা-অনে ৯০.২৫ৰ স্কৰ কৰি খ্লোই কিমৰ শীৰ্ষস্থানীয় ৮৮ স্কৰক পৰাস্ত কৰে ।
--------------------------------------------------

Translating ASM:  33%|███████▌               | 330/1000 [02:38<05:17,  2.11it/s]

[330/1000]
EN: Arsenal reached the League Cup final after Kai Havertz secured a 1-0 win.
ASM: কাই হাভাৰ্জে ১-০ ব্যৱধানত বিজয় নিশ্চিত কৰাৰ পিছত আৰ্ছেনেলে লীগ কাপ ফাইনেলত প্ৰৱেশ ।
--------------------------------------------------

Translating ASM:  33%|███████▌               | 331/1000 [02:38<05:30,  2.02it/s]

[331/1000]
EN: Kai Havertz came off the bench to finish Arsenal’s 4-2 aggregate semi-final victory.
ASM: আৰ্ছেনালৰ ৪-২ সংযোজনীয় ছেমি ফাইনেলৰ জয় সমাপ্ত কৰিবলৈ বেঞ্চৰ পৰা নামি আহিল কাই হাভাৰটছ ।
--------------------------------------------------

Translating ASM:  33%|███████▋               | 332/1000 [02:39<05:34,  2.00it/s]

[332/1000]
EN: Arsenal will face Manchester City or Newcastle at Wembley on March 22.
ASM: ২২ মাৰ্চত ৱেম্বলিত আৰ্ছেনেলে মুখামুখি হব মেনচেষ্টাৰ চিটি বা নিউকেষ্টেলৰ বিৰুদ্ধে ।
--------------------------------------------------

Translating ASM:  33%|███████▋               | 333/1000 [02:39<05:22,  2.07it/s]

[333/1000]
EN: Manchester City held a 2-0 lead over Newcastle ahead of the second leg.
ASM: দ্বিতীয় লেগৰ পূৰ্বেই নিউয়াকাল্ডৰ বিৰুদ্ধে ২-০ ব্যৱধানত আগভাগ লৈছিল ম্যানচেষ্টাৰ চিটিয়ে ।
--------------------------------------------------

Translating ASM:  33%|███████▋               | 334/1000 [02:39<04:50,  2.29it/s]

[334/1000]
EN: Arsenal have not won the League Cup since 1993, according to the report.
ASM: প্ৰতিবেদনৰ মতে ১৯৯৩ চনৰ পৰা আৰ্ছেনেলে লীগ কাপ জয় কৰা নাই ।
--------------------------------------------------

Translating ASM:  34%|███████▋               | 335/1000 [02:40<05:01,  2.20it/s]

[335/1000]
EN: The Football Association of Ireland confirmed Ireland will fulfil Nations League fixtures against Israel.
ASM: আয়াৰলেণ্ডৰ ফুটবল সন্থাই নিশ্চিত কৰিলে যে আয়াৰলেণ্ডে ইজৰাইলৰ বিৰুদ্ধে নেচছ লীগ ফিক্সচাৰ পূৰণ কৰিব ।
--------------------------------------------------

Translating ASM:  34%|███████▋               | 336/1000 [02:40<05:04,  2.18it/s]

[336/1000]
EN: Ireland and Israel were drawn with Austria and Kosovo in Nations League League B.
ASM: নেচছ লীগ লীগ বিত আয়াৰলেণ্ড আৰু ইজৰাইল অষ্ট্ৰিয়া আৰু কছোভোৰ সৈতে ড্ৰ খেলিছিল ।
--------------------------------------------------

Translating ASM:  34%|███████▊               | 337/1000 [02:41<04:58,  2.22it/s]

[337/1000]
EN: Ireland must play Israel home and away between September and November.
ASM: আইৰলেণ্ডে ছেপ্তেম্বৰ আৰু নৱেম্বৰৰ মাজত গৃহ আৰু বাহিৰত ইজৰাইলৰ বিৰুদ্ধে খেলিব লাগিব ।
--------------------------------------------------

Translating ASM:  34%|███████▊               | 338/1000 [02:41<05:14,  2.11it/s]

[338/1000]
EN: The FAI warned refusal could mean forfeiture and possible disqualification under UEFA regulations.
ASM: এফএআইয়ে সতৰ্ক কৰিছিল যে অস্বীকাৰ কৰাৰ অৰ্থ হ'ব পাৰে জব্দ আৰু ইউইএফএ নিয়মাৱলীৰ অধীনত সম্ভাৱ্য অযোগ্যতা ।
--------------------------------------------------

Translating ASM:  34%|███████▊               | 339/1000 [02:42<05:32,  1.99it/s]

[339/1000]
EN: The FAI said it requested Israel’s UEFA ban in November after an internal vote.
ASM: এফএআইয়ে কৈছিল যে ইয়ে নৱেম্বৰত আভ্যন্তৰীণ ভোটৰ পিছত ইজৰাইলৰ য়ু ই এ নিষেধাজ্ঞাৰ বাবে অনুৰোধ কৰিছিল ।
--------------------------------------------------

Translating ASM:  34%|███████▊               | 340/1000 [02:43<06:00,  1.83it/s]

[340/1000]
EN: Novak Djokovic beat Jannik Sinner 3-6, 6-3, 4-6, 6-4, 6-4 in Melbourne.
ASM: মেলবৰ্ণত জাননিক সীনাৰক ৩-৬, ৬-৩, ৪-৬, ৬-৪, ৬-৪ গলত পৰাস্ত নোভাক জকভিকে ।
--------------------------------------------------

Translating ASM:  34%|███████▊               | 341/1000 [02:43<06:13,  1.76it/s]

[341/1000]
EN: Novak Djokovic’s win over Jannik Sinner set up an Australian Open final against Carlos Alcaraz.
ASM: জাননিক সীনাৰৰ বিৰুদ্ধে নোভাক জকোভিচৰ জয়ই কাৰ্লছ অলকাৰাজৰ বিৰুদ্ধে অষ্ট্ৰেলিয়ান অপেনৰ ফাইনেলত স্থান লাভ কৰিলে ।
--------------------------------------------------

Translating ASM:  34%|███████▊               | 342/1000 [02:44<06:31,  1.68it/s]

[342/1000]
EN: Novak Djokovic reached his 11th Australian Open final after ending four straight semi-final exits.
ASM: একেৰাহে চাৰিটা ছেমি ফাইনেলৰ প্ৰস্থান সমাপ্ত কৰি অষ্ট্ৰেলিয়ান অপেনৰ ১১ সংখ্যক ফাইনেলত উপনীত হৈছে নোভাক জকোভিচ ।
--------------------------------------------------

Translating ASM:  34%|███████▉               | 343/1000 [02:44<06:14,  1.75it/s]

[343/1000]
EN: Carlos Alcaraz reached his first Melbourne Park title match, the report said.
ASM: প্ৰতিবেদনত কোৱা হৈছে যে কাৰ্লছ অলকাৰাজে তেওঁৰ প্ৰথম মেলবৰ্ণ পাৰ্ক খিতাপৰ মেচত উপনীত হৈছিল ।
--------------------------------------------------

Translating ASM:  34%|███████▉               | 344/1000 [02:45<06:09,  1.78it/s]

[344/1000]
EN: Lorenzo Musetti retired mid-match after suffering a suspected upper leg tear.
ASM: লৰেঞ্চো মুছেটি নামৰ খেলুৱৈজনে ওপৰৰ ভৰিৰ কঁকাল ভঙা হোৱাৰ সন্দেহ কৰি খেলৰ মাজ ভাগত অৱসৰ গ্ৰহণ কৰে ।
--------------------------------------------------

Translating ASM:  34%|███████▉               | 345/1000 [02:45<05:57,  1.83it/s]

[345/1000]
EN: Lorenzo Musetti withdrew after winning the first two sets against Novak Djokovic.
ASM: নোভাক জকভিচৰ বিৰুদ্ধে প্ৰথম দুটা ছেটত জয়লাভ কৰাৰ পিছত লৰেঞ্চ মুছেটি আঁতৰি গল ।
--------------------------------------------------

Translating ASM:  35%|███████▉               | 346/1000 [02:46<05:57,  1.83it/s]

[346/1000]
EN: Alexander Zverev rallied from losing the first set to beat Gabriel Diallo in four sets.
ASM: প্ৰথম ছেটত পৰাস্ত হৈ চাৰিটা ছেটত গ্যাব্ৰিয়েল ডিয়েল্লোক পৰাস্ত কৰিলে আলেকজেণ্ডাৰ জভেৰেৱে ।
--------------------------------------------------

Translating ASM:  35%|███████▉               | 347/1000 [02:47<06:26,  1.69it/s]

[347/1000]
EN: Alexander Zverev won 6-7(1), 6-1, 6-4, 6-2 against Gabriel Diallo at Rod Laver Arena.
ASM: ৰাড লাভাৰ আৰেনাত গেব্ৰিয়েল ডিয়েল্লোৰ বিৰুদ্ধে আলেকজেণ্ডাৰ জভেৰেভ বিজয়ী ৬-৭১, ৬-১, ৬-৪, ৬-২ ।
--------------------------------------------------

Translating ASM:  35%|████████               | 348/1000 [02:47<06:31,  1.66it/s]

[348/1000]
EN: An Australian Open report noted fans were unhappy about long queues and a ticket sales halt.
ASM: অষ্ট্ৰেলিয়ান অপেনৰ এটা প্ৰতিবেদনত উল্লেখ কৰা হৈছিল যে দীঘলীয়া শাৰী আৰু টিকট বিক্ৰী বন্ধ হোৱাৰ বাবে অনুৰাগীসকল অসন্তুষ্ট আছিল ।
--------------------------------------------------

Translating ASM:  35%|████████               | 349/1000 [02:48<06:18,  1.72it/s]

[349/1000]
EN: A Hindustan Times column said tennis needs rivalries to elevate players and the sport.
ASM: হিন্দুস্তান টাইমছৰ এটা স্তম্ভই কয় যে খেলুৱৈ আৰু ক্ৰীড়াৰ উন্নতি কৰিবলৈ টেনিছক প্ৰতিদ্বন্দ্বীৰ প্ৰয়োজন ।
--------------------------------------------------

Translating ASM:  35%|████████               | 350/1000 [02:48<06:02,  1.79it/s]

[350/1000]
EN: A Hindustan Times column said Jannik Sinner and Carlos Alcaraz are improving every year.
ASM: হিন্দুস্তান টাইমছৰ এটা স্তম্ভত জাননিক সিনাৰ আৰু কাৰ্লছ অলকাৰাজৰ প্ৰতিবছৰে উন্নতি হৈছে বুলি কোৱা হৈছিল ।
--------------------------------------------------

Translating ASM:  35%|████████               | 351/1000 [02:49<05:41,  1.90it/s]

[351/1000]
EN: The same column said Sinner and Alcaraz already play at a level above most players.
ASM: একেটা স্তম্ভই কৈছিল যে সিনাৰ আৰু অলকাৰাজে ইতিমধ্যে বেছিভাগ খেলুৱৈৰ ওপৰৰ স্তৰত খেলিছে ।
--------------------------------------------------

Translating ASM:  35%|████████               | 352/1000 [02:49<05:41,  1.90it/s]

[352/1000]
EN: The column said Federer, Nadal and Djokovic gave men’s tennis a tribal feel for two decades.
ASM: এই স্তম্ভটোত কোৱা হৈছিল যে ফেডাৰেৰ, নাডাল আৰু জকোভিকে পুৰুষৰ টেনিছক দুই দশকৰ বাবে জনজাতীয় অনুভৱ দিছিল ।
--------------------------------------------------

Translating ASM:  35%|████████               | 353/1000 [02:50<05:54,  1.83it/s]

[353/1000]
EN: A report said Alexander Zverev began a bid for a maiden Australian Open title.
ASM: এক প্ৰতিবেদনত কোৱা হৈছিল যে আলেকজেণ্ডাৰ জভেৰেৱে প্ৰথমবাৰৰ বাবে অষ্ট্ৰেলিয়ান অপেন খিতাপৰ বাবে নিবিদা আৰম্ভ কৰিছিল ।
--------------------------------------------------

Translating ASM:  35%|████████▏              | 354/1000 [02:51<06:24,  1.68it/s]

[354/1000]
EN: Carlos Alcaraz defeated Alexander Zverev 6-3, 3-6, 6-1, 6-2 at the Australian Open.
ASM: কাৰ্লছ অলকাৰাজে অষ্ট্ৰেলিয়ান অপেনত আলেকজেণ্ডাৰ জভেৰেভক ৬-৩-৩-৬, ৬-১-৬-২ ব্যৱধানত পৰাস্ত কৰে ।
--------------------------------------------------

Translating ASM:  36%|████████▏              | 355/1000 [02:51<05:45,  1.87it/s]

[355/1000]
EN: Carlos Alcaraz won in two hours and 26 minutes, according to the match report.
ASM: মেচৰ ৰিপোৰ্ট অনুসৰি কাৰ্লছ অলকাৰাজে দুঘণ্টা ২৬ মিনিটত জয়লাভ কৰে ।
--------------------------------------------------

Translating ASM:  36%|████████▏              | 356/1000 [02:51<05:24,  1.98it/s]

[356/1000]
EN: The same report said Zverev received a time-violation warning during the match.
ASM: একেটা বাতৰিয়ে কৈছিল যে জভেৰেভক মেচৰ সময়ত সময় উলংঘনৰ সতৰ্কবাণী লাভ কৰিছিল ।
--------------------------------------------------

Translating ASM:  36%|████████▏              | 357/1000 [02:52<05:19,  2.01it/s]

[357/1000]
EN: The report said Alcaraz requested a meeting with the supervisor after the time warning.
ASM: প্ৰতিবেদনত কোৱা হৈছে যে সময় সতৰ্কবাণীৰ পিছত অলকাৰাজে তত্বাৱধায়কজনৰ সৈতে এখন বৈঠকৰ বাবে অনুৰোধ কৰিছিল ।
--------------------------------------------------

Translating ASM:  36%|████████▏              | 358/1000 [02:52<05:18,  2.02it/s]

[358/1000]
EN: The report said Alcaraz complained about the length of Zverev’s breaks between points.
ASM: প্ৰতিবেদনত কোৱা হৈছিল যে অলকাৰাজে জেভেৰভৰ পইণ্টৰ মাজত বিৰতিৰ দৈৰ্ঘ্যৰ বিষয়ে অভিযোগ কৰিছিল ।
--------------------------------------------------

Translating ASM:  36%|████████▎              | 359/1000 [02:53<04:53,  2.18it/s]

[359/1000]
EN: Carlos Alcaraz said he also wanted to know the limit for the time between points.
ASM: কাৰ্লছ অলকাৰাজে কৈছিল যে তেওঁ পইণ্টবোৰৰ মাজত সময়ৰ সীমাটো জনাটোও বিচাৰে ।
--------------------------------------------------

Translating ASM:  36%|████████▎              | 360/1000 [02:53<04:59,  2.14it/s]

[360/1000]
EN: R Praggnanandhaa sealed a 2026 Candidates berth by winning the FIDE Circuit 2025.
ASM: আৰ প্ৰাগ্নানন্দই ২০২৫ চনৰ ফিডে চাৰ্কিট জয় কৰি ২০২৬গৰাকী প্ৰাৰ্থীৰ স্থান ছীল কৰিলে ।
--------------------------------------------------

Translating ASM:  36%|████████▎              | 361/1000 [02:54<04:44,  2.25it/s]

[361/1000]
EN: The Candidates Tournament will determine the challenger to world champion D Gukesh.
ASM: প্ৰাৰ্থী প্ৰতিযোগিতাই নিৰ্ণয় লব বিশ্ব চেম্পিয়ন ডি গুকেচৰ প্ৰতিদ্বন্দ্বী ।
--------------------------------------------------

Translating ASM:  36%|████████▎              | 362/1000 [02:54<04:55,  2.16it/s]

[362/1000]
EN: R Praggnanandhaa overtook Ding Liren in May to lead the FIDE Circuit race.
ASM: এফ আই ডি চাৰ্কিট দৌৰত নেতৃত্ব দিবলৈ আৰ প্ৰাগ্নানন্দই মে'ত ডিং লীৰেনক পিছ পেলাইছিল ।
--------------------------------------------------

Translating ASM:  36%|████████▎              | 363/1000 [02:55<04:48,  2.21it/s]

[363/1000]
EN: Praggnanandhaa thanked supporters on X after earning a place in the 2026 Candidates.
ASM: ২০২৬ৰ প্ৰাৰ্থীত স্থান অৰ্জন কৰাৰ পিছত প্ৰাগ্নানন্দই এক্সত সমৰ্থকসকলক ধন্যবাদ জনায় ।
--------------------------------------------------

Translating ASM:  36%|████████▎              | 364/1000 [02:55<05:10,  2.05it/s]

[364/1000]
EN: A report said only Nodirbek Abdusattorov had a theoretical chance to catch Praggnanandhaa.
ASM: এটা ৰিপৰ্টত কোৱা হৈছিল যে কেৱল নোদিৰবেক আব্দুছেটৰভৰহে প্ৰাগ্নানন্দক ধৰিবলৈ তাত্ত্বিক সুযোগ আছিল ।
--------------------------------------------------

Translating ASM:  36%|████████▍              | 365/1000 [02:56<05:15,  2.01it/s]

[365/1000]
EN: D Gukesh withdrew from Tata Steel Chess India Rapid and Blitz for personal reasons.
ASM: ব্যক্তিগত কাৰণত টাটা ষ্টীল চেছ ইণ্ডিয়া ৰেপিড আৰু ব্লিটজৰ পৰা আঁতৰি গল ডি গুকেশ ।
--------------------------------------------------

Translating ASM:  37%|████████▍              | 366/1000 [02:56<05:29,  1.93it/s]

[366/1000]
EN: Tata Steel Chess India Rapid and Blitz was scheduled in Kolkata from January 7 to 11.
ASM: টাটা ষ্টীল চেছ ইণ্ডিয়া ৰেপিড এণ্ড ব্লিৎজ কলকাতাতাত ৭ জানুৱাৰীৰ পৰা ১১ জানুৱাৰীলৈ অনুষ্ঠিত হব ।
--------------------------------------------------

Translating ASM:  37%|████████▍              | 367/1000 [02:57<05:09,  2.05it/s]

[367/1000]
EN: Nihal Sarin replaced D Gukesh in the Tata Steel Chess India event.
ASM: টাটা ষ্টীল চেছ ইণ্ডিয়া ইভেণ্টত ডি গুকেশৰ ঠাইত নিহল সৰিন ।
--------------------------------------------------

Translating ASM:  37%|████████▍              | 368/1000 [02:57<05:14,  2.01it/s]

[368/1000]
EN: Dibyendu Barua called D Gukesh’s withdrawal a big setback for organisers and fans.
ASM: ডি গুকেশৰ প্ৰত্যাহাৰক সংগঠক আৰু অনুৰাগীসকলৰ বাবে এক ডাঙৰ বিফলতা বুলি অভিহিত দিবীন্দু বৰুৱা ।
--------------------------------------------------

Translating ASM:  37%|████████▍              | 369/1000 [02:58<05:01,  2.09it/s]

[369/1000]
EN: Viswanathan Anand returned to play Tata Steel Chess India after six years away.
ASM: ছবছৰ বিদায়ৰ পিছত টাটা ষ্টীল চেছ ইণ্ডিয়া খেলিবলৈ উভতি আহিল বিশ্বনাথন আনন্দ ।
--------------------------------------------------

Translating ASM:  37%|████████▌              | 370/1000 [02:58<05:01,  2.09it/s]

[370/1000]
EN: Viswanathan Anand said “It was exhausting not playing” while explaining his return.
ASM: বিশ্বনাথন আনন্দই তেওঁৰ প্ৰত্যাৱৰ্তনৰ বিষয়ে বৰ্ণনা কৰি কয় যে ক্ৰীড়া নকৰাই ক্লান্তিদায়ক আছিল ।
--------------------------------------------------

Translating ASM:  37%|████████▌              | 371/1000 [02:59<04:45,  2.20it/s]

[371/1000]
EN: Viswanathan Anand was set to open against Wesley So in the seventh edition.
ASM: বিশ্বনাথন আনন্দ সপ্তম সংস্কৰণত ৱেছলি ছোৰ বিৰুদ্ধে খোলাৰ বাবে সাজু আছিল ।
--------------------------------------------------

Translating ASM:  37%|████████▌              | 372/1000 [02:59<04:51,  2.16it/s]

[372/1000]
EN: The tournament director said Tata Steel Chess India will be held in January going forward.
ASM: টুৰ্ণামেণ্ট সঞ্চালকে কয় যে আগলৈ জানুৱাৰী মাহত টাটা ষ্টীল চেছ ইণ্ডিয়া অনুষ্ঠিত হ'ব ।
--------------------------------------------------

Translating ASM:  37%|████████▌              | 373/1000 [03:00<04:59,  2.09it/s]

[373/1000]
EN: The Tata Steel Chess India event offered equal prize purses of $41,500 in open and women’s.
ASM: টাটা ষ্টীল চেছ ইণ্ডিয়া ইভেণ্টত খোলা আৰু মহিলাৰ ৪১,৫০০ ডলাৰৰ সমান পুৰস্কাৰ প্ৰদান কৰা হয় ।
--------------------------------------------------

Translating ASM:  37%|████████▌              | 374/1000 [03:00<04:59,  2.09it/s]

[374/1000]
EN: Viswanathan Anand backed the Total Chess World Championship Tour approved by FIDE.
ASM: বিশ্বনাথন আনন্দই ফিডে অনুমোদন দিয়া মুঠ চেছ বিশ্ব চেম্পিয়নশ্বিপ টুৰ সমৰ্থন কৰে ।
--------------------------------------------------

Translating ASM:  38%|████████▋              | 375/1000 [03:01<05:22,  1.94it/s]

[375/1000]
EN: The Total Chess World Championship Tour will crown a new “FIDE World Combined” champion.
ASM: টটেল চেছ ৱৰ্ল্ড চেম্পিয়নশ্বিপ টুৰ নতুন ফাইড বিশ্ব সংযুক্ত চেম্পিয়নক মুকুট দিব ।
--------------------------------------------------

Translating ASM:  38%|████████▋              | 376/1000 [03:01<05:08,  2.02it/s]

[376/1000]
EN: The tour will be held across fast classic, rapid and blitz formats.
ASM: দ্ৰুত শাস্ত্ৰীয়, দ্ৰুত আৰু ব্লিটজ ফৰমেটত এই ভ্ৰমণ অনুষ্ঠিত হব ।
--------------------------------------------------

Translating ASM:  38%|████████▋              | 377/1000 [03:01<04:56,  2.10it/s]

[377/1000]
EN: Anand said Norway Chess has a serious long-term proposal for the new tour.
ASM: আনন্দই কয় যে নতুন ভ্ৰমণৰ বাবে নৰৱে চেছৰ এক গুৰুতৰ দীৰ্ঘম্যাদী প্ৰস্তাৱ আছে ।
--------------------------------------------------

Translating ASM:  38%|████████▋              | 378/1000 [03:02<04:50,  2.14it/s]

[378/1000]
EN: Anand said the sport benefits when Magnus Carlsen competes in major events.
ASM: আনন্দই কয় যে যেতিয়া মেগনছ কাৰ্লছেনে প্ৰধান ইভেণ্টত প্ৰতিযোগিতা কৰে তেতিয়া খেলৰ লাভ হয় ।
--------------------------------------------------

Translating ASM:  38%|████████▋              | 379/1000 [03:02<04:46,  2.17it/s]

[379/1000]
EN: Wesley So said he proposed a draw against Praggnanandhaa, not the arbiters.
ASM: ৱেছলি ছোৱে কৈছিল যে তেওঁ প্ৰাগ্নানন্দৰ বিৰুদ্ধে ড্ৰ প্ৰস্তাৱ দিছিল, মধ্যস্থতাকাৰীসকলৰ বিৰুদ্ধে নহয় ।
--------------------------------------------------

Translating ASM:  38%|████████▋              | 380/1000 [03:03<04:33,  2.26it/s]

[380/1000]
EN: Praggnanandhaa had one second left before stopping the clock to call the arbiter.
ASM: দণ্ড বন্ধ কৰাৰ আগতে প্ৰশাসকক মাতিবলৈ প্ৰাগ্নানন্দৰ এটা ছেকেণ্ড বাকী আছিল ।
--------------------------------------------------

Translating ASM:  38%|████████▊              | 381/1000 [03:03<04:53,  2.11it/s]

[381/1000]
EN: Nihal Sarin won the 2026 Tata Steel Chess India Rapid Tournament in Kolkata.
ASM: কলকাতাত অনুষ্ঠিত ২০২৬ চনৰ টাটা ষ্টীল চেছ ইণ্ডিয়া ৰেপিড টুৰ্ণামেণ্টত বিজয়ী হল নিহল সৰিন ।
--------------------------------------------------

Translating ASM:  38%|████████▊              | 382/1000 [03:04<04:48,  2.14it/s]

[382/1000]
EN: Ian Nepomniachtchi criticised hotel conditions during the 2025 Chess World Cup in Goa.
ASM: গোৱাত ২০২৫ চনৰ চেছ বিশ্বকাপৰ সময়ত ইয়ান নেপমনিয়াচ্চিয়ে হোটেলৰ পৰিস্থিতিৰ সমালোচনা কৰে ।
--------------------------------------------------

Translating ASM:  38%|████████▊              | 383/1000 [03:04<04:48,  2.14it/s]

[383/1000]
EN: Ian Nepomniachtchi said organisers chose one of the worst hotels for the Goa event.
ASM: ইয়ান নেপমনিয়াচ্চিয়ে কৈছিল যে আয়োজকসকলে গোৱা ইভেণ্টৰ বাবে আটাইতকৈ বেয়া হোটেলবোৰৰ এটা নিৰ্বাচন কৰিছিল ।
--------------------------------------------------

Translating ASM:  38%|████████▊              | 384/1000 [03:05<04:33,  2.25it/s]

[384/1000]
EN: Nepomniachtchi lost to Diptayan Ghosh after receiving a bye into round two.
ASM: দ্বিতীয় ৰাউণ্ডলৈ বাই লাভ কৰি ডিপ্টান ঘোষৰ হাতত পৰাস্ত নেপমনিয়াচ্চি ।
--------------------------------------------------

Translating ASM:  38%|████████▊              | 385/1000 [03:05<04:50,  2.12it/s]

[385/1000]
EN: PGTI’s 2026 schedule was drawn up only till March-end, featuring six events.
ASM: পিজিটিআইৰ ২০২৬ৰ সময়সূচী মাৰ্চৰ শেষলৈকে প্ৰস্তুত কৰা হৈছিল, য'ত ছয়টা ইভেন্ট অন্তৰ্ভুক্ত আছিল ।
--------------------------------------------------

Translating ASM:  39%|████████▉              | 386/1000 [03:06<04:57,  2.06it/s]

[386/1000]
EN: PGTI planned no more than 25 tournaments in 2026 after holding 36 events last year.
ASM: পিজিটিআইয়ে যোৱা বছৰ ৩৬টা ইভেন্ট অনুষ্ঠিত কৰাৰ পিছত ২০২৬ চনত ২৫টাতকৈ অধিক টুৰ্ণামেণ্ট অনুষ্ঠিত কৰাৰ পৰিকল্পনা কৰা নাছিল ।
--------------------------------------------------

Translating ASM:  39%|████████▉              | 387/1000 [03:06<05:05,  2.01it/s]

[387/1000]
EN: PGTI’s main tour offered ₹35 crore prize money in 2025, up from ₹24 crore.
ASM: পিজিটিআইৰ মুখ্য ভ্ৰমণে ২০২৫ চনত ৩৫ কোটি পুৰস্কাৰৰ ধন আগবঢ়াইছিল, যিটো ২৪ কোটি আছিল ।
--------------------------------------------------

Translating ASM:  39%|████████▉              | 388/1000 [03:07<05:25,  1.88it/s]

[388/1000]
EN: OWGR granted LIV Golf accreditation for the first time, awarding points to top-10 finishers.
ASM: অডব্লিউজিআৰে প্ৰথমবাৰৰ বাবে লিভ গল্ফ স্বীকৃতি প্ৰদান কৰি শীৰ্ষ-১০ গৰাকী ফাইনিছকাৰক পইণ্ট প্ৰদান কৰে ।
--------------------------------------------------

Translating ASM:  39%|████████▉              | 389/1000 [03:07<05:25,  1.88it/s]

[389/1000]
EN: LIV Golf expanded tournaments from 54 to 72 holes in 2026, paving the approval.
ASM: লিভ গল্ফে ২০২৬ চনত টুৰ্ণামেণ্টসমূহ ৫৪ ৰ পৰা ৭২ খন হোললৈ সম্প্ৰসাৰিত কৰি অনুমোদন প্ৰদান কৰে ।
--------------------------------------------------

Translating ASM:  39%|████████▉              | 390/1000 [03:08<05:16,  1.93it/s]

[390/1000]
EN: OWGR said LIV Golf did not meet all eligibility standards under its requirements.
ASM: ওডব্লিউজিআৰে কৈছিল যে লিভ গল্ফে ইয়াৰ প্ৰয়োজনীয়তাৰ অধীনত সকলো যোগ্যতাৰ মানদণ্ড পূৰণ কৰা নাছিল ।
--------------------------------------------------

Translating ASM:  39%|████████▉              | 391/1000 [03:08<05:08,  1.98it/s]

[391/1000]
EN: LIV Golf’s season-opening event in Riyadh was set to start with 57 players.
ASM: ৰিয়াদত লিভ গল্ফৰ ছিজন উদ্বোধনী ইভেণ্ট ৫৭ জন খেলুৱৈৰ সৈতে আৰম্ভ হব ।
--------------------------------------------------

Translating ASM:  39%|█████████              | 392/1000 [03:09<05:21,  1.89it/s]

[392/1000]
EN: International Series India was expected to move from DLF Golf and Country Club to Bengaluru.
ASM: ডি এল এফ গল্ফ এণ্ড কান্ট্ৰী ক্লাবৰ পৰা বাংগালুৰুলৈ আন্তঃৰাষ্ট্ৰীয় ছিৰিজ ইণ্ডিয়া স্থানান্তৰ হোৱাৰ সম্ভাৱনা আছিল ।
--------------------------------------------------

Translating ASM:  39%|█████████              | 393/1000 [03:09<05:15,  1.92it/s]

[393/1000]
EN: Bryson DeChambeau and Joaquin Niemann were key draws at International Series India 2025.
ASM: আন্তঃৰাষ্ট্ৰীয় ছিৰিজ ইণ্ডিয়া ২০২৫ত ব্ৰাইছন ডিচেম্বাও আৰু জোএকুইন নিমন মূল ড্ৰ আছিল ।
--------------------------------------------------

Translating ASM:  39%|█████████              | 394/1000 [03:10<05:28,  1.85it/s]

[394/1000]
EN: Ollie Schniederjans won International Series India 2025 by four shots in Gurugram.
ASM: গুৰুগ্ৰামত চাৰিটা শ্বটত জয় লাভ কৰিলে ইণ্টাৰনেচনেল ছিৰিজ ইণ্ডিয়া ২০২৫ত অলি শ্নিদেৰঞ্জে ।
--------------------------------------------------

Translating ASM:  40%|█████████              | 395/1000 [03:11<05:19,  1.89it/s]

[395/1000]
EN: Rahul Singh said International Series organisers remained committed to returning to India.
ASM: ৰাহুল সিঙে কয় যে আন্তঃৰাষ্ট্ৰীয় শৃংখলাৰ আয়োজকসকলে ভাৰতলৈ উভতি অহাৰ প্ৰতিশ্ৰুতিবদ্ধ হৈ আছে ।
--------------------------------------------------

Translating ASM:  40%|█████████              | 396/1000 [03:11<05:24,  1.86it/s]

[396/1000]
EN: PGTI launched a league with six franchises, with each franchise buying 10 players.
ASM: পিজিটিআইয়ে ছয়টা ফ্ৰাঞ্চিজৰ সৈতে এটা লীগ আৰম্ভ কৰিছিল, প্ৰতিটো ফ্ৰাঞ্চিজে ১০ জন খেলুৱৈ ক্ৰয় কৰিছিল ।
--------------------------------------------------

Translating ASM:  40%|█████████▏             | 397/1000 [03:12<05:06,  1.97it/s]

[397/1000]
EN: The PGTI league’s first edition was planned across three courses in Delhi-NCR.
ASM: দিল্লী-এনচিআৰত তিনিটা কৰছত পিজিটিআই লীগৰ প্ৰথম সংস্কৰণৰ পৰিকল্পনা কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  40%|█████████▏             | 398/1000 [03:12<04:55,  2.04it/s]

[398/1000]
EN: Shubhankar Sharma missed cuts in 21 of 28 events in 2025, the report said.
ASM: ২০২৫ চনত ২৮ টা ইভেন্টৰ ২১ টাতে কাট হেৰুৱালে শুভংকৰ শৰ্মাই বুলি প্ৰতিবেদনত কোৱা হৈছে ।
--------------------------------------------------

Translating ASM:  40%|█████████▏             | 399/1000 [03:12<04:52,  2.06it/s]

[399/1000]
EN: Shubhankar Sharma regained playing rights for 2026 via Q-School, finishing tied-second.
ASM: কিউ-স্কুলৰ জৰিয়তে ২০২৬ৰ বাবে খেলৰ অধিকাৰ পুনৰ লাভ শুভংকৰ শৰ্মাৰ, সমতল দ্বিতীয়ত সমাপ্ত ।
--------------------------------------------------

Translating ASM:  40%|█████████▏             | 400/1000 [03:13<04:33,  2.19it/s]

[400/1000]
EN: Vietnam targets 22 to 25 million international visitors by 2026.
ASM: ভিয়েটনামে ২০২৬ চনৰ ভিতৰত ২২ ৰ পৰা ২৫ নিযুত আন্তঃৰাষ্ট্ৰীয় পৰ্যটকক লক্ষ্য কৰিছে ।
--------------------------------------------------

Translating ASM:  40%|█████████▏             | 401/1000 [03:13<04:15,  2.34it/s]

[401/1000]
EN: Operations teams monitor weather to minimize passenger inconvenience.
ASM: যাত্ৰীসকলৰ অসুবিধা হ্ৰাস কৰিবলৈ অপাৰেশ্যন দলবোৰে বতৰ নিৰীক্ষণ কৰে ।
--------------------------------------------------

Translating ASM:  40%|█████████▏             | 402/1000 [03:14<04:24,  2.26it/s]

[402/1000]
EN: IndiGo announces Amsterdam debut as first long-haul European destination.
ASM: ইণ্ডিগোৱে আমষ্টাৰডাম প্ৰথম দীঘলীয়া ইউৰোপীয়ান গন্তব্যস্থান হিচাপে আত্মপ্ৰকাশ কৰাৰ ঘোষণা কৰিছে ।
--------------------------------------------------

Translating ASM:  40%|█████████▎             | 403/1000 [03:14<04:23,  2.27it/s]

[403/1000]
EN: Air India crash committee investigates Boeing 787-8 Ahmedabad tragedy.
ASM: এয়াৰ ইণ্ডিয়া দুৰ্ঘটনা সমিতিয়ে বয়িং ৭৮৭-৮ আহমেদাবাদ দুৰ্যোগৰ তদন্ত কৰিছে ।
--------------------------------------------------

Translating ASM:  40%|█████████▎             | 404/1000 [03:15<04:22,  2.27it/s]

[404/1000]
EN: IndiGo aims for forty percent international capacity share by 2030.
ASM: ইণ্ডিগৰ লক্ষ্য হৈছে ২০৩০ চনৰ ভিতৰত ৪০ শতাংশ আন্তঃৰাষ্ট্ৰীয় সামৰ্থ্যৰ অংশীদাৰিত্ব ।
--------------------------------------------------

Translating ASM:  40%|█████████▎             | 405/1000 [03:15<04:12,  2.35it/s]

[405/1000]
EN: One survivor rescued from Air India crash site in Ahmedabad.
ASM: আহমেদাবাদত এয়াৰ ইণ্ডিয়াৰ দুৰ্ঘটনাগ্ৰস্ত স্থানৰ পৰা এজন জীৱিত লোকক উদ্ধাৰ কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  41%|█████████▎             | 406/1000 [03:15<04:03,  2.44it/s]

[406/1000]
EN: Jetstar Asia closure frees five hundred million dollars for Qantas.
ASM: জেটষ্টাৰ এছিয়া বন্ধে কান্টাৰ বাবে পাঁচশ মিলিয়ন ডলাৰ মুকলি কৰে ।
--------------------------------------------------

Translating ASM:  41%|█████████▎             | 407/1000 [03:16<03:58,  2.49it/s]

[407/1000]
EN: Qantas Group announces closure of Singapore-based Jetstar Asia.
ASM: কানটাছ গ্ৰুপে ছিংগাপুৰ ভিত্তিক জেটষ্টাৰ এছিয়া বন্ধ কৰাৰ ঘোষণা কৰিছে ।
--------------------------------------------------

Translating ASM:  41%|█████████▍             | 408/1000 [03:16<03:50,  2.57it/s]

[408/1000]
EN: IndiGo launches Mumbai-Manchester flights using Norse aircraft.
ASM: ইণ্ডিগোৱে নৰ্ছ বিমান ব্যৱহাৰ কৰি মুম্বাই-মাঞ্চেষ্টাৰ বিমান আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  41%|█████████▍             | 409/1000 [03:17<04:12,  2.34it/s]

[409/1000]
EN: IndiGo transitions to A350-900 aircraft for European expansion by 2027.
ASM: ইণ্ডিগই ২০২৭ চনৰ ভিতৰত ইউৰোপীয় সম্প্ৰসাৰণৰ বাবে এ৩৫০-৯০০ বিমানলৈ পৰিৱৰ্তন কৰিছে ।
--------------------------------------------------

Translating ASM:  41%|█████████▍             | 410/1000 [03:17<04:02,  2.44it/s]

[410/1000]
EN: Air India Ahmedabad crash claims 242 lives including Vijay Rupani.
ASM: এয়াৰ ইণ্ডিয়া আহমেদাবাদ দুৰ্ঘটনাত বিজয় ৰূপানীকে ধৰি 242 জন লোকৰ মৃত্যু হয় ।
--------------------------------------------------

Translating ASM:  41%|█████████▍             | 411/1000 [03:17<04:08,  2.37it/s]

[411/1000]
EN: Thirteen Jetstar Asia A320s redeployed to Australia and New Zealand.
ASM: তেৰখন জেটষ্টাৰ এছিয়া এ৩২০ অষ্ট্ৰেলিয়া আৰু নিউজিলেণ্ডলৈ পুনৰ স্থাপন কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  41%|█████████▍             | 412/1000 [03:18<03:57,  2.47it/s]

[412/1000]
EN: IndiGo issues fog advisory for Delhi and northern India passengers.
ASM: ইণ্ডিগোৱে দিল্লী আৰু উত্তৰ ভাৰতৰ যাত্ৰীসকলৰ বাবে কুঁৱলী পৰামৰ্শ জাৰি কৰিছে ।
--------------------------------------------------

Translating ASM:  41%|█████████▍             | 413/1000 [03:18<04:07,  2.37it/s]

[413/1000]
EN: DGCA imposes ₹2 crore fine on Air India for safety lapses.
ASM: ডিজিচিএয়ে নিৰাপত্তাৰ অৱহেলাৰ বাবে এয়াৰ ইণ্ডিয়ালৈ ২ কোটি টকাৰ জৰিমনা আৰোপ কৰিছে ।
--------------------------------------------------

Translating ASM:  41%|█████████▌             | 414/1000 [03:19<03:49,  2.55it/s]

[414/1000]
EN: Sixteen intra-Asia routes lose only non-stop Changi connections.
ASM: ১৬ টা আন্তঃআছিয়া পথত কেৱল অস্থায়ী চেঙী সংযোগ হেৰাই যায় ।
--------------------------------------------------

Translating ASM:  42%|█████████▌             | 415/1000 [03:19<03:59,  2.44it/s]

[415/1000]
EN: Bengaluru airport opens second runway to handle growing traffic.
ASM: বেংগালুৰু বিমানবন্দৰে ক্ৰমবৰ্ধিত যান-বাহন ব্যৱস্থাপনৰ বাবে দ্বিতীয় ৰানৱে মুকলি কৰে ।
--------------------------------------------------

Translating ASM:  42%|█████████▌             | 416/1000 [03:19<04:03,  2.40it/s]

[416/1000]
EN: Air India Express pilot assaults passenger at Delhi airport terminal.
ASM: দিল্লী বিমানবন্দৰৰ টাৰ্মিনেলত যাত্ৰীক আক্ৰমণ এয়াৰ ইণ্ডিয়া এক্সপ্ৰেছৰ পাইলটৰ ।
--------------------------------------------------

Translating ASM:  42%|█████████▌             | 417/1000 [03:20<03:55,  2.48it/s]

[417/1000]
EN: Mumbai airport witnesses record passenger footfall during festive week.
ASM: মুম্বাই বিমানবন্দৰে উৎসৱ সপ্তাহত ৰেকৰ্ড যাত্ৰী পদচৰণ প্ৰত্যক্ষ কৰে ।
--------------------------------------------------

Translating ASM:  42%|█████████▌             | 418/1000 [03:20<03:42,  2.61it/s]

[418/1000]
EN: Dense fog disrupts IndiGo flight operations across North India.
ASM: ঘন কুঁৱলীয়ে উত্তৰ ভাৰতত ইণ্ডিগো বিমানৰ কাম-কাজ ব্যাহত কৰিছে ।
--------------------------------------------------

Translating ASM:  42%|█████████▋             | 419/1000 [03:20<03:38,  2.66it/s]

[419/1000]
EN: Go First insolvency resolution extends to third consecutive month.
ASM: প্ৰথমটো পলাতকতা নিষ্পত্তি একেৰাহে তৃতীয় মাহলৈ সম্প্ৰসাৰিত হয় ।
--------------------------------------------------

Translating ASM:  42%|█████████▋             | 420/1000 [03:21<03:43,  2.59it/s]

[420/1000]
EN: Akasa Air orders additional Boeing 737 Max aircraft for expansion.
ASM: আকাছা এয়াৰে সম্প্ৰসাৰণৰ বাবে অতিৰিক্ত বোয়িং ৭৩৭ মেক্স বিমানৰ আদেশ দিছে ।
--------------------------------------------------

Translating ASM:  42%|█████████▋             | 421/1000 [03:21<03:49,  2.52it/s]

[421/1000]
EN: Air India pilots union raises concerns over rest period violations.
ASM: এয়াৰ ইণ্ডিয়া পাইলট ইউনিয়নে বিশ্ৰাম কালৰ উলংঘন সন্দৰ্ভত উদ্বেগ উত্থাপন কৰিছে ।
--------------------------------------------------

Translating ASM:  42%|█████████▋             | 422/1000 [03:22<04:02,  2.38it/s]

[422/1000]
EN: EU launches Entry-Exit System campaign for non-EU travellers.
ASM: ইইউয়ে ইউৰোপীয় সংঘৰ বাহিৰৰ ভ্ৰমণকাৰীসকলৰ বাবে প্ৰৱেশ-প্ৰস্থান প্ৰণালী অভিযান আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  42%|█████████▋             | 423/1000 [03:22<04:13,  2.27it/s]

[423/1000]
EN: SpiceJet secures funding to revive grounded fleet operations soon.
ASM: স্পাইচজেটে শীঘ্ৰেই ভূগৰ্ভস্থ বহীবাহিনীৰ কাম-কাজ পুনৰুজ্জীৱিত কৰিবলৈ পুঁজি নিশ্চিত কৰে ।
--------------------------------------------------

Translating ASM:  42%|█████████▊             | 424/1000 [03:23<04:05,  2.34it/s]

[424/1000]
EN: Bulgaria adopts Euro as legal tender from January first 2026.
ASM: ২০২৬ৰ প্ৰথম জানুৱাৰীৰ পৰা বুলগেৰিয়াই য়ুৰোক বৈধ মূল্য হিচাপে গ্ৰহণ কৰে ।
--------------------------------------------------

Translating ASM:  42%|█████████▊             | 425/1000 [03:23<04:04,  2.35it/s]

[425/1000]
EN: Vietnam grants forty-five day visa-free entry to twelve European nations.
ASM: ভিয়েটনামে বাৰখন ইউৰোপীয়ান ৰাষ্ট্ৰলৈ পঁয়ত্ৰিশ দিনৰ ভিছা মুক্ত প্ৰৱেশ প্ৰদান কৰে ।
--------------------------------------------------

Translating ASM:  43%|█████████▊             | 426/1000 [03:23<03:41,  2.59it/s]

[426/1000]
EN: Indian government reverses ban on Sikh pilgrimages to Pakistan.
ASM: পাকিস্তানলৈ শিখ তীৰ্থযাত্ৰাৰ নিষেধাজ্ঞা বাতিল কৰিলে ভাৰত চৰকাৰে ।
--------------------------------------------------

Translating ASM:  43%|█████████▊             | 427/1000 [03:24<03:27,  2.76it/s]

[427/1000]
EN: Pakistan High Commission issues visas to twenty-one hundred Sikh pilgrims.
ASM: পাকিস্তানৰ উচ্চ আয়োগে একৈশ শিখ তীৰ্থযাত্ৰীক ভিছা প্ৰদান কৰে ।
--------------------------------------------------

Translating ASM:  43%|█████████▊             | 428/1000 [03:24<03:37,  2.63it/s]

[428/1000]
EN: TSA ends shoe removal rule at domestic United States airports.
ASM: টিএছএয়ে ঘৰুৱা আমেৰিকা যুক্তৰাষ্ট্ৰৰ বিমানবন্দৰবোৰত জোতা আঁতৰোৱাৰ নিয়ম শেষ কৰে ।
--------------------------------------------------

Translating ASM:  43%|█████████▊             | 429/1000 [03:25<03:58,  2.40it/s]

[429/1000]
EN: Real ID enforcement charges tourists forty-five dollars for domestic flights.
ASM: প্ৰকৃত পৰিচয় প্ৰয়োগে পৰ্যটকসকলক ঘৰুৱা বিমানৰ বাবে পঁয়ত্ৰিশ ডলাৰ মাচুল দিয়ে ।
--------------------------------------------------

Translating ASM:  43%|█████████▉             | 430/1000 [03:25<03:54,  2.43it/s]

[430/1000]
EN: United States government shutdown causes forty-three day travel chaos.
ASM: আমেৰিকা যুক্তৰাষ্ট্ৰৰ চৰকাৰী শাটডাউনে চল্লিশ তিনিদিনীয়া ভ্ৰমণ বিশৃংখলাৰ সৃষ্টি কৰে ।
--------------------------------------------------

Translating ASM:  43%|█████████▉             | 431/1000 [03:25<03:36,  2.63it/s]

[431/1000]
EN: Government considers hotel industry infrastructure status for tax benefits.
ASM: চৰকাৰে কৰ লাভৰ বাবে হোটেল উদ্যোগৰ আন্তঃগাঁথনিৰ স্থিতি বিবেচনা কৰে ।
--------------------------------------------------

Translating ASM:  43%|█████████▉             | 432/1000 [03:26<03:37,  2.61it/s]

[432/1000]
EN: Gajendra Singh Shekhawat announces infrastructure status proposal for hotels.
ASM: গেজেন্দ্ৰ সিং শইকীয়াই হোটেলৰ বাবে আন্তঃগাঁথনিৰ স্থিতিৰ প্ৰস্তাৱ ঘোষণা কৰে ।
--------------------------------------------------

Translating ASM:  43%|█████████▉             | 433/1000 [03:26<03:34,  2.64it/s]

[433/1000]
EN: Tourism Ministry reboots Incredible India campaign with AI focus.
ASM: পৰ্যটন মন্ত্ৰালয়ে এআই ফোকাসৰ সৈতে অবিশ্বাস্য ভাৰত অভিযান পুনৰ আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  43%|█████████▉             | 434/1000 [03:26<03:34,  2.64it/s]

[434/1000]
EN: Suman Billa confirms new digital-centric Incredible India strategy.
ASM: ডিজিটেলকেন্দ্ৰিক নতুন ইনক্ৰিবেল ইণ্ডিয়া কৌশলৰ কথা নিশ্চিত কৰিছে সুমন বিলাই ।
--------------------------------------------------

Translating ASM:  44%|██████████             | 435/1000 [03:27<03:28,  2.71it/s]

[435/1000]
EN: India targets one trillion dollar tourism economy by 2047.
ASM: ভাৰতে 2047 চনৰ ভিতৰত এটা ট্ৰিলিয়ন ডলাৰৰ পৰ্যটন অৰ্থনীতিৰ লক্ষ্য ৰাখে ।
--------------------------------------------------

Translating ASM:  44%|██████████             | 436/1000 [03:27<03:35,  2.61it/s]

[436/1000]
EN: Centre sanctions fifty destinations for challenge mode tourism development.
ASM: চেলেঞ্জ মোড পৰ্যটন বিকাশৰ বাবে কেন্দ্ৰই পঞ্চাশটা গন্তব্যস্থান অনুমোদন জনাইছে ।
--------------------------------------------------

Translating ASM:  44%|██████████             | 437/1000 [03:28<03:29,  2.69it/s]

[437/1000]
EN: Telangana adopts Sarathi portal for online RTA services.
ASM: তেলেংগানাই অনলাইন আৰটিএ সেৱাৰ বাবে চাৰথি পৰ্টেল গ্ৰহণ কৰিছে ।
--------------------------------------------------

Translating ASM:  44%|██████████             | 438/1000 [03:28<03:19,  2.82it/s]

[438/1000]
EN: Ministry announces twelve thousand crore rupees for new tourism destinations.
ASM: মন্ত্ৰালয়ে নতুন পৰ্যটন গন্তব্যস্থানসমূহৰ বাবে বাৰ হাজাৰ কোটি টকা ঘোষণা কৰিছে ।
--------------------------------------------------

Translating ASM:  44%|██████████             | 439/1000 [03:28<03:23,  2.75it/s]

[439/1000]
EN: Government allocates 1.34 billion dollars for tourism infrastructure development.
ASM: চৰকাৰে পৰ্যটন আন্তঃগাঁথনি উন্নয়নৰ বাবে ১.৩৪ বিলিয়ন ডলাৰ আৱণ্টন কৰিছে ।
--------------------------------------------------

Translating ASM:  44%|██████████             | 440/1000 [03:29<03:22,  2.77it/s]

[440/1000]
EN: India plans 2030 Commonwealth Games hosting to boost tourism.
ASM: ভাৰতে পৰ্যটন বৃদ্ধিত ২০৩০ কমনৱেলথ গেমছ আয়োজন কৰাৰ পৰিকল্পনা কৰিছে ।
--------------------------------------------------

Translating ASM:  44%|██████████▏            | 441/1000 [03:29<03:14,  2.87it/s]

[441/1000]
EN: Census self-enumeration trial begins for digital population count.
ASM: ডিজিটেল জনসংখ্যা গণনাৰ বাবে নাগৰিকপঞ্জী স্ব-সংখ্যা পৰীক্ষা আৰম্ভ হয় ।
--------------------------------------------------

Translating ASM:  44%|██████████▏            | 442/1000 [03:29<03:18,  2.81it/s]

[442/1000]
EN: European Commission launches biometric border system awareness campaign.
ASM: ইউৰোপীয় আয়োগে বায়মেট্ৰিক সীমান্ত প্ৰণালীৰ সজাগতা অভিযান আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  44%|██████████▏            | 443/1000 [03:30<03:27,  2.69it/s]

[443/1000]
EN: Non-EU travellers face new digital border checks from October.
ASM: ইউৰোপীয় সংঘৰ বাহিৰৰ ভ্ৰমণকাৰীসকলে অক্টোবৰৰ পৰা নতুন ডিজিটেল সীমা পৰীক্ষা কৰাৰ সন্মুখীন হ'ব ।
--------------------------------------------------

Translating ASM:  44%|██████████▏            | 444/1000 [03:30<03:33,  2.61it/s]

[444/1000]
EN: Dover ferry passengers register first for EU entry-exit system.
ASM: ডভাৰ ফেৰী যাত্ৰীসকলে প্ৰথমতে ইইউ প্ৰৱেশ-প্ৰস্থান ব্যৱস্থাৰ বাবে পঞ্জীয়ন কৰে ।
--------------------------------------------------

Translating ASM:  44%|██████████▏            | 445/1000 [03:31<03:44,  2.47it/s]

[445/1000]
EN: Eurostar business travellers gradually included in EES rollout.
ASM: ইউৰোষ্টাৰ ব্যৱসায়িক ভ্ৰমণকাৰীসকলক লাহে লাহে ইএছএছ ৰোলআউটত অন্তৰ্ভুক্ত কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  45%|██████████▎            | 446/1000 [03:31<03:26,  2.68it/s]

[446/1000]
EN: India extends e-visa facility to citizens of five more nations.
ASM: ভাৰতে আৰু পাঁচখন দেশৰ নাগৰিকলৈ ই-ভিছা সুবিধা আগবঢ়াইছে ।
--------------------------------------------------

Translating ASM:  45%|██████████▎            | 447/1000 [03:31<03:18,  2.79it/s]

[447/1000]
EN: Karnataka announces tourism policy targeting fifty billion dollar investment
ASM: কৰ্ণাটকে পঞ্চাশ বিলিয়ন ডলাৰৰ বিনিয়োগৰ লক্ষ্যৰে পৰ্যটন নীতি ঘোষণা কৰিছে
--------------------------------------------------

Translating ASM:  45%|██████████▎            | 448/1000 [03:32<03:26,  2.67it/s]

[448/1000]
EN: GST Council reduces tax on hotel rooms below seven thousand five hundred rupees.
ASM: জিএছটি পৰিষদে সাত হাজাৰ পাঁচশ টকাৰ তলৰ হোটেলৰ কোঠালিৰ ওপৰত কৰ হ্ৰাস কৰিছে ।
--------------------------------------------------

Translating ASM:  45%|██████████▎            | 449/1000 [03:32<03:29,  2.63it/s]

[449/1000]
EN: Ministry of Tourism launches Swadesh Darshan 3.0 for sustainable tourism.
ASM: পৰ্যটন মন্ত্ৰালয়ে বহনক্ষম পৰ্যটনৰ বাবে স্বদেশ দৰ্শন ৩০ মুকলি কৰিছে ।
--------------------------------------------------

Translating ASM:  45%|██████████▎            | 450/1000 [03:32<03:31,  2.61it/s]

[450/1000]
EN: Civil Aviation Ministry orders probe into Delhi airport assault case.
ASM: দিল্লী বিমানবন্দৰৰ আক্ৰমণৰ ঘটনাৰ তদন্তৰ নিৰ্দেশ দিলে অসামৰিক বিমান পৰিবহন মন্ত্ৰালয়ে ।
--------------------------------------------------

Translating ASM:  45%|██████████▎            | 451/1000 [03:33<03:30,  2.61it/s]

[451/1000]
EN: Government approves UDAN 5.0 with focus on helicopter services.
ASM: হেলিকপ্টাৰ সেৱাৰ ওপৰত গুৰুত্ব আৰোপ কৰি চৰকাৰে উদান ৫.০ অনুমোদন জনাইছে ।
--------------------------------------------------

Translating ASM:  45%|██████████▍            | 452/1000 [03:33<03:25,  2.67it/s]

[452/1000]
EN: Kerala declares tourism as industry status for hotels and resorts.
ASM: কেৰালাই পৰ্যটনক হোটেল আৰু ৰিজৰ্টৰ বাবে উদ্যোগ হিচাপে ঘোষণা কৰিছে ।
--------------------------------------------------

Translating ASM:  45%|██████████▍            | 453/1000 [03:33<03:13,  2.82it/s]

[453/1000]
EN: West Bengal secures second rank in foreign tourist arrivals.
ASM: বিদেশী পৰ্যটকৰ আগমনৰ ক্ষেত্ৰত পশ্চিমবংগৰ দ্বিতীয় স্থান নিশ্চিত হৈছে ।
--------------------------------------------------

Translating ASM:  45%|██████████▍            | 454/1000 [03:34<03:26,  2.65it/s]

[454/1000]
EN: Mamata Banerjee hails West Bengal's international tourism milestone.
ASM: মমতা বেনাৰ্জীয়ে পশ্চিমবংগৰ আন্তঃৰাষ্ট্ৰীয় পৰ্যটনৰ মাইলৰ খুঁটি প্ৰশংসা কৰে ।
--------------------------------------------------

Translating ASM:  46%|██████████▍            | 455/1000 [03:34<03:42,  2.44it/s]

[455/1000]
EN: Maharashtra leads foreign tourist arrivals with 3.71 million visitors.
ASM: মহাৰাষ্ট্ৰ ৩.৭১ নিযুত দৰ্শনাৰ্থীৰ সৈতে বিদেশী পৰ্যটকৰ আগমনৰ শীৰ্ষস্থানত আছে ।
--------------------------------------------------

Translating ASM:  46%|██████████▍            | 456/1000 [03:35<03:49,  2.37it/s]

[456/1000]
EN: West Bengal records 3.12 million foreign tourist visits nationwide.
ASM: পশ্চিমবংগত দেশজুৰি ৩.১২ নিযুত বিদেশী পৰ্যটকে ভ্ৰমণ কৰিছে ।
--------------------------------------------------

Translating ASM:  46%|██████████▌            | 457/1000 [03:35<04:05,  2.21it/s]

[457/1000]
EN: Uttar Pradesh tops domestic tourism with 646.81 million visitors.
ASM: ৬৪৬.৮১ মিলিয়ন দৰ্শনাৰ্থীৰ সৈতে উত্তৰ প্ৰদেশ ঘৰুৱা পৰ্যটনৰ শীৰ্ষস্থানত আছে ।
--------------------------------------------------

Translating ASM:  46%|██████████▌            | 458/1000 [03:36<04:10,  2.17it/s]

[458/1000]
EN: Tamil Nadu records 306.84 million domestic tourist footfall.
ASM: তামিলনাডুত ৩০৬.৮৪ মিলিয়ন ঘৰুৱা পৰ্যটকৰ ভ্ৰমণ ৰেকৰ্ড কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  46%|██████████▌            | 459/1000 [03:36<03:53,  2.32it/s]

[459/1000]
EN: India receives 2,948.19 million domestic tourists during 2024.
ASM: ভাৰতে ২০২৪ চনত ২৯৪৮.১৯ মিলিয়ন ঘৰুৱা পৰ্যটক গ্ৰহণ কৰিব ।
--------------------------------------------------

Translating ASM:  46%|██████████▌            | 460/1000 [03:37<03:42,  2.42it/s]

[460/1000]
EN: Foreign tourist visits to India touch 20.94 million in 2024.
ASM: ২০২৪ চনত ভাৰতত বিদেশী পৰ্যটকৰ ভ্ৰমণ ২০.৯৪ মিলিয়ন স্পৰ্শ কৰে ।
--------------------------------------------------

Translating ASM:  46%|██████████▌            | 461/1000 [03:37<03:34,  2.51it/s]

[461/1000]
EN: Domestic tourism records 17.51 percent growth over previous year.
ASM: যোৱা বছৰৰ তুলনাত ঘৰুৱা পৰ্যটনৰ ১৭.৫১ শতাংশ বৃদ্ধি হৈছে ।
--------------------------------------------------

Translating ASM:  46%|██████████▋            | 462/1000 [03:37<03:24,  2.63it/s]

[462/1000]
EN: International tourist arrivals grow 8.84 percent in 2024.
ASM: ২০২৪ চনত আন্তঃৰাষ্ট্ৰীয় পৰ্যটকৰ আগমন ৮.৮৪ শতাংশ বৃদ্ধি পাব ।
--------------------------------------------------

Translating ASM:  46%|██████████▋            | 463/1000 [03:38<03:34,  2.51it/s]

[463/1000]
EN: Maha Kumbh Mela attracts 663 million visits across forty-five days.
ASM: পঁয়ত্ৰিশ দিনত মহা কুম্ভ মেলাত ৬৬৩ নিযুত দৰ্শনাৰ্থী আকৰ্ষিত হয় ।
--------------------------------------------------

Translating ASM:  46%|██████████▋            | 464/1000 [03:38<03:33,  2.52it/s]

[464/1000]
EN: Prayagraj witnesses 660 million pilgrims at Sangam confluence.
ASM: সংগ্ৰাম সন্মিলনত প্ৰয়াগৰাজে ৬৬০ নিযুত তীৰ্থযাত্ৰীক প্ৰত্যক্ষ কৰে ।
--------------------------------------------------

Translating ASM:  46%|██████████▋            | 465/1000 [03:39<03:37,  2.46it/s]

[465/1000]
EN: Vietnam welcomes 1.73 million international visitors during October 2025.
ASM: ২০২৫ চনৰ অক্টোবৰত ভিয়েটনামে ১.৭৩ মিলিয়ন আন্তঃৰাষ্ট্ৰীয় পৰ্যটকক স্বাগতম জনাইছে ।
--------------------------------------------------

Translating ASM:  47%|██████████▋            | 466/1000 [03:39<03:50,  2.32it/s]

[466/1000]
EN: Vietnam records 13.8 percent monthly growth in foreign tourist arrivals.
ASM: ভিয়েটনামে বিদেশী পৰ্যটক আগমনৰ ক্ষেত্ৰত ১৩.৮ শতাংশ মাসিক বৃদ্ধিৰ অভিলেখ গঢ়ি তুলিছে ।
--------------------------------------------------

Translating ASM:  47%|██████████▋            | 467/1000 [03:39<03:47,  2.34it/s]

[467/1000]
EN: India attracts only ten million international tourists annually currently.
ASM: ভাৰতে বৰ্তমান বছৰি মাত্ৰ দহ নিযুত আন্তৰ্জাতিক পৰ্যটকক আকৰ্ষিত কৰে ।
--------------------------------------------------

Translating ASM:  47%|██████████▊            | 468/1000 [03:40<03:51,  2.30it/s]

[468/1000]
EN: France welcomes ninety million tourists against India's ten million.
ASM: ভাৰতৰ দহ নিযুত লোকৰ বিপৰীতে ফ্ৰান্সত ৯০ নিযুত পৰ্যটকক স্বাগতম জনোৱা হৈছে ।
--------------------------------------------------

Translating ASM:  47%|██████████▊            | 469/1000 [03:40<03:39,  2.42it/s]

[469/1000]
EN: Spain receives eighty-four million international visitors annually.
ASM: স্পেইনে বছৰি ৮৪ নিযুত আন্তৰ্জাতিক পৰ্যটকক গ্ৰহণ কৰে ।
--------------------------------------------------

Translating ASM:  47%|██████████▊            | 470/1000 [03:41<03:22,  2.61it/s]

[470/1000]
EN: United States hosts eighty million foreign tourists every year.
ASM: আমেৰিকা যুক্তৰাষ্ট্ৰত প্ৰতিবছৰে আঠ কোটি বিদেশী পৰ্যটক আহে ।
--------------------------------------------------

Translating ASM:  47%|██████████▊            | 471/1000 [03:41<03:21,  2.63it/s]

[471/1000]
EN: India's pre-Covid tourist arrival figures remain unmatched after six years.
ASM: ছবছৰ পিছত ভাৰতৰ প্ৰাক কোভিড পৰ্যটকৰ আগমনৰ সংখ্যা অতুলনীয় হৈ আছে ।
--------------------------------------------------

Translating ASM:  47%|██████████▊            | 472/1000 [03:41<03:11,  2.75it/s]

[472/1000]
EN: Tourism contributes 5.2 percent to India's current GDP.
ASM: ভাৰতৰ বৰ্তমানৰ জিডিপিত পৰ্যটনৰ ৫.২ শতাংশ অৱদান আছে ।
--------------------------------------------------

Translating ASM:  47%|██████████▉            | 473/1000 [03:42<03:07,  2.81it/s]

[473/1000]
EN: Tourism sector supports 84 million livelihoods across India.
ASM: পৰ্যটন খণ্ডটোৱে সমগ্ৰ ভাৰতত ৮৪ নিযুত লোকৰ জীৱিকাক সমৰ্থন কৰিছে ।
--------------------------------------------------

Translating ASM:  47%|██████████▉            | 474/1000 [03:42<03:16,  2.67it/s]

[474/1000]
EN: FICCI predicts 250 billion dollar tourism opportunity by 2030.
ASM: ফিক্কিই ২০৩০ চনৰ ভিতৰত ২৫০ বিলিয়ন ডলাৰৰ পৰ্যটন সুযোগৰ ভৱিষ্যতবাণী কৰিছে ।
--------------------------------------------------

Translating ASM:  48%|██████████▉            | 475/1000 [03:42<03:28,  2.52it/s]

[475/1000]
EN: ICRA reports hotel demand to exceed supply in coming years.
ASM: আইচিআৰএয়ে ৰিপৰ্ট কৰিছে যে অহা বছৰবোৰত হোটেলৰ চাহিদা যোগানতকৈ অধিক হ'ব ।
--------------------------------------------------

Translating ASM:  48%|██████████▉            | 476/1000 [03:43<03:26,  2.54it/s]

[476/1000]
EN: Global travel industry generates 10.9 trillion dollars for economies.
ASM: বিশ্বব্যাপী ভ্ৰমণ উদ্যোগে অৰ্থনীতিৰ বাবে ১০.৯ ট্ৰিলিয়ন ডলাৰ উপাৰ্জন কৰে ।
--------------------------------------------------

Translating ASM:  48%|██████████▉            | 477/1000 [03:43<03:16,  2.66it/s]

[477/1000]
EN: Travel and tourism accounts for ten percent of global GDP.
ASM: ভ্ৰমণ আৰু পৰ্যটনে বিশ্বব্যাপী জিডিপিৰ দহ শতাংশ বহন কৰে ।
--------------------------------------------------

Translating ASM:  48%|██████████▉            | 478/1000 [03:44<03:24,  2.55it/s]

[478/1000]
EN: Vietnam targets 22 to 26 million international visitors by 2026.
ASM: ভিয়েটনামে ২০২৬ চনৰ ভিতৰত ২২ ৰ পৰা ২৬ নিযুত আন্তঃৰাষ্ট্ৰীয় পৰ্যটকক লক্ষ্য কৰিছে ।
--------------------------------------------------

Translating ASM:  48%|███████████            | 479/1000 [03:44<03:22,  2.58it/s]

[479/1000]
EN: Belgium citizens enjoy forty-five day visa-free Vietnam travel.
ASM: বেলজিয়ামৰ নাগৰিকসকলে পঁয়ত্ৰিশ দিনৰ ভিছামুক্ত ভিয়েটনাম ভ্ৰমণ উপভোগ কৰে ।
--------------------------------------------------

Translating ASM:  48%|███████████            | 480/1000 [03:44<03:20,  2.59it/s]

[480/1000]
EN: Poland nationals receive visa-free entry to Vietnam under new scheme.
ASM: পোলিশ নাগৰিকসকলে নতুন আঁচনিৰ অধীনত ভিয়েটনামত ভিছা-মুক্ত প্ৰৱেশ লাভ কৰে ।
--------------------------------------------------

Translating ASM:  48%|███████████            | 481/1000 [03:45<03:34,  2.42it/s]

[481/1000]
EN: Swiss passport holders travel visa-free to Vietnam for forty-five days.
ASM: ছুইজাৰলেণ্ডৰ পাছপোৰ্টধাৰীসকলে পঁয়ত্ৰিশ দিনৰ বাবে ভিছা নথকা ভিয়েটনামত ভ্ৰমণ কৰে ।
--------------------------------------------------

Translating ASM:  48%|███████████            | 482/1000 [03:45<03:29,  2.47it/s]

[482/1000]
EN: Saudi Red Sea Authority issues twelve marine tourism licences.
ASM: ছৌডি ৰেড চি অথৰিটিয়ে বাৰটা সামুদ্রিক পৰ্যটন অনুজ্ঞাপত্ৰ জাৰী কৰে ।
--------------------------------------------------

Translating ASM:  48%|███████████            | 483/1000 [03:46<03:25,  2.51it/s]

[483/1000]
EN: Red Sea Cruises receives approval under Cruise Saudi brand.
ASM: ৰেড চি ক্ৰুজছে ক্ৰুজ ছৌডি ব্ৰেণ্ডৰ অধীনত অনুমোদন লাভ কৰিছে ।
--------------------------------------------------

Translating ASM:  48%|███████████▏           | 484/1000 [03:46<03:31,  2.44it/s]

[484/1000]
EN: Sindalah Marina in NEOM secures Saudi marine tourism licence.
ASM: এনইঅ'এমৰ ছিণ্ডালা মেৰিনাই ছৌডি মাৰিন পৰ্যটন অনুজ্ঞাপত্ৰ সুৰক্ষিত কৰে ।
--------------------------------------------------

Translating ASM:  48%|███████████▏           | 485/1000 [03:46<03:26,  2.49it/s]

[485/1000]
EN: Dolphin Beach Resort Marina obtains Yanbu operating approval.
ASM: ডলফিন বিচ ৰিজ ৰ্ট মেৰিনাই য়ানবু অপাৰেটিং অনুমোদন লাভ কৰে ।
--------------------------------------------------

Translating ASM:  49%|███████████▏           | 486/1000 [03:47<03:28,  2.46it/s]

[486/1000]
EN: Jeddah Municipality Marina included in Saudi licensing round.
ASM: ছৌডি অনুজ্ঞাপত্ৰ ৰাউণ্ডত জেদ্দা পৌৰসভা মাৰিনা অন্তৰ্ভুক্ত কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  49%|███████████▏           | 487/1000 [03:47<03:32,  2.42it/s]

[487/1000]
EN: Deep Seas Shipping Agency gains tourism shipping agent licence.
ASM: ডীপ চিজ শিপিং এজেন্সিয়ে পৰ্যটন শিপিং এজেণ্টৰ অনুজ্ঞাপত্ৰ লাভ কৰে ।
--------------------------------------------------

Translating ASM:  49%|███████████▏           | 488/1000 [03:48<03:26,  2.48it/s]

[488/1000]
EN: Venice extends day-tripper entrance fee to sixty days.
ASM: ভেনিচেছ এদিনীয়া ভ্ৰমণকাৰীৰ প্ৰৱেশৰ মাচুল ষাঠি দিনলৈ বৃদ্ধি কৰিছে ।
--------------------------------------------------

Translating ASM:  49%|███████████▏           | 489/1000 [03:48<03:39,  2.33it/s]

[489/1000]
EN: Venice charges day-trippers from Friday to Sunday between April and July.
ASM: এপ্ৰিল আৰু জুলাইৰ মাজৰ শুকুৰবাৰৰ পৰা দেওবাৰলৈ ভেনচিয়ে এদিনীয়া ভ্ৰমণকাৰীক মাচুল দিয়ে ।
--------------------------------------------------

Translating ASM:  49%|███████████▎           | 490/1000 [03:49<03:52,  2.19it/s]

[490/1000]
EN: Simone Venturini calls Venice entry fee tangible innovation tool.
ASM: চিমোন ভেণ্টুৰিনিয়ে ভেনিচ প্ৰৱেশ মাচুলক স্পৰ্শকাতৰ উদ্ভাৱন সঁজুলি বুলি কয় ।
--------------------------------------------------

Translating ASM:  49%|███████████▎           | 491/1000 [03:49<03:56,  2.15it/s]

[491/1000]
EN: Amsterdam introduces tourist fees to fight overtourism congestion.
ASM: আমষ্টাৰডামে অতিৰিক্ত পৰ্যটন জৰিতাৰ বিৰুদ্ধে যুঁজিবলৈ পৰ্যটন মাচুল প্ৰৱৰ্তন কৰে ।
--------------------------------------------------

Translating ASM:  49%|███████████▎           | 492/1000 [03:50<03:50,  2.20it/s]

[492/1000]
EN: Greece passes laws limiting visitor numbers to popular islands.
ASM: গ্ৰীচ চৰকাৰে জনপ্ৰিয় দ্বীপসমূহৰ বাবে দৰ্শনাৰ্থীৰ সংখ্যা সীমিত কৰি ৰাখিবলৈ আইন প্ৰণয়ন কৰিছে ।
--------------------------------------------------

Translating ASM:  49%|███████████▎           | 493/1000 [03:50<03:36,  2.34it/s]

[493/1000]
EN: Japan implements tourist fees to manage overcrowding at sites.
ASM: জাপানে স্থানসমূহত অত্যধিক ভিৰ ব্যৱস্থাপনাৰ বাবে পৰ্যটন ফি ৰূপায়ণ কৰে ।
--------------------------------------------------

Translating ASM:  49%|███████████▎           | 494/1000 [03:50<03:25,  2.46it/s]

[494/1000]
EN: Hurricane Melissa devastates Jamaica's tourism infrastructure.
ASM: হৰিকেন মেলিছাই জামাইকাৰ পৰ্যটন আন্তঃগাঁথনি ধ্বংস কৰিছে ।
--------------------------------------------------

Translating ASM:  50%|███████████▍           | 495/1000 [03:51<03:21,  2.50it/s]

[495/1000]
EN: Jamaica opens for business after Hurricane Melissa recovery.
ASM: হৰিকেন মেলিছাৰ পুনৰুদ্ধাৰৰ পিছত জামাইকা ব্যৱসায়ৰ বাবে মুকলি হৈছে ।
--------------------------------------------------

Translating ASM:  50%|███████████▍           | 496/1000 [03:51<02:56,  2.85it/s]

[496/1000]
EN: Canadian visitation to United States continues to plummet.
ASM: কানাডাৰ আমেৰিকা যুক্তৰাষ্ট্ৰৰ ভ্ৰমণ অব্যাহত আছে ।
--------------------------------------------------

Translating ASM:  50%|███████████▍           | 497/1000 [03:51<02:49,  2.97it/s]

[497/1000]
EN: Sean Duffy focuses on America's ailing air travel system.
ASM: ছোন ডফিয়ে আমেৰিকাৰ অসুস্থ বিমান ভ্ৰমণ ব্যৱস্থাৰ ওপৰত গুৰুত্ব আৰোপ কৰে ।
--------------------------------------------------

Translating ASM:  50%|███████████▍           | 498/1000 [03:52<02:53,  2.90it/s]

[498/1000]
EN: Trump administration policies impact travel both positively and negatively.
ASM: ট্ৰাম্প প্ৰশাসনৰ নীতিসমূহে ভ্ৰমণ ইতিবাচক আৰু ঋণাত্মক দুয়োটাতে প্ৰভাৱিত কৰে ।
--------------------------------------------------

Translating ASM:  50%|███████████▍           | 499/1000 [03:52<03:00,  2.78it/s]

[499/1000]
EN: Sri Lanka regime change attributed to poor governance by Ajit Doval.
ASM: শ্ৰীলংকাৰ শাসনৰ পৰিৱৰ্তন অজিত দোভালৰ দুৰ্বল প্ৰশাসনৰ বাবে দায়ী ।
--------------------------------------------------

Translating ASM:  50%|███████████▌           | 500/1000 [03:52<02:56,  2.83it/s]

[500/1000]
EN: Bangladesh leadership transition results from poor governance failures.
ASM: বাংলাদেশৰ নেতৃত্বৰ পৰিৱৰ্তনৰ পৰিণাম হৈছে দৰিদ্ৰ প্ৰশাসন বিফলতা ।
--------------------------------------------------

Translating ASM:  50%|███████████▌           | 501/1000 [03:53<02:48,  2.95it/s]

[501/1000]
EN: Nepal government change linked to governance issues says Doval.
ASM: নেপাল চৰকাৰৰ পৰিৱৰ্তন প্ৰশাসন বিষয়ৰ সৈতে জড়িত বুলি কয় দোৱালে ।
--------------------------------------------------

Translating ASM:  50%|███████████▌           | 502/1000 [03:53<02:58,  2.78it/s]

[502/1000]
EN: Thailand launches five year multiple entry tourist visa scheme.
ASM: থাইলেণ্ডে পাঁচ বছৰীয়া একাধিক প্ৰৱেশ পৰ্যটন ভিছা আঁচনি আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  50%|███████████▌           | 503/1000 [03:53<02:47,  2.98it/s]

[503/1000]
EN: Sri Lanka grants free visa to seven countries including India.
ASM: শ্ৰীলংকাই ভাৰতকে ধৰি সাতখন দেশলৈ বিনামূলীয়া ভিছা প্ৰদান কৰিছে ।
--------------------------------------------------

Translating ASM:  50%|███████████▌           | 504/1000 [03:54<03:01,  2.74it/s]

[504/1000]
EN: Maldives lifts emergency but tourism recovery remains sluggish.
ASM: মালদ্বীপে জৰুৰীকালীন অৱস্থা উত্তোলন কৰে কিন্তু পৰ্যটন পুনৰুদ্ধাৰ ধীৰ হৈ আছে ।
--------------------------------------------------

Translating ASM:  50%|███████████▌           | 505/1000 [03:54<02:55,  2.81it/s]

[505/1000]
EN: UAE announces five year multiple entry visa for Indian nationals.
ASM: সংযুক্ত আৰৱ আমিৰাটে ভাৰতীয় নাগৰিকসকলৰ বাবে পাঁচ বছৰীয়া একাধিক প্ৰৱেশ ভিছা ঘোষণা কৰিছে ।
--------------------------------------------------

Translating ASM:  51%|███████████▋           | 506/1000 [03:54<03:01,  2.72it/s]

[506/1000]
EN: Schengen visa fees increase from eighty to ninety Euros globally.
ASM: শ্বেংজেন ভিছা মাচুল বিশ্বব্যাপী আশীৰ পৰা নব্বৈ য়ুৰোলৈ বৃদ্ধি পাইছে ।
--------------------------------------------------

Translating ASM:  51%|███████████▋           | 507/1000 [03:55<02:57,  2.77it/s]

[507/1000]
EN: Japan resumes short term tourist visa processing for Indians.
ASM: জাপানে ভাৰতীয়সকলৰ বাবে স্বল্পমেয়াদী পৰ্যটন ভিছা প্ৰক্ৰিয়া পুনৰ আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  51%|███████████▋           | 508/1000 [03:55<02:55,  2.81it/s]

[508/1000]
EN: India operates 127 airports with ten new cruise terminals.
ASM: ভাৰতত ১২৭টা বিমানবন্দৰ আৰু দহটা নতুন ক্ৰুজ টাৰ্মিনেল আছে ।
--------------------------------------------------

Translating ASM:  51%|███████████▋           | 509/1000 [03:55<02:43,  3.00it/s]

[509/1000]
EN: Government constructs 150,000 kilometres of new national highways.
ASM: চৰকাৰে ১৫০ হাজাৰ কিলোমিটাৰ নতুন ৰাষ্ট্ৰীয় ঘাইপথ নিৰ্মাণ কৰিছে ।
--------------------------------------------------

Translating ASM:  51%|███████████▋           | 510/1000 [03:56<02:48,  2.90it/s]

[510/1000]
EN: India develops 38 national waterways for inland cruise tourism.
ASM: ভাৰতে অন্তৰ্দেশীয় ক্ৰুজ পৰ্যটনৰ বাবে ৩৮টা ৰাষ্ট্ৰীয় জলপথ বিকশিত কৰিছে ।
--------------------------------------------------

Translating ASM:  51%|███████████▊           | 511/1000 [03:56<02:58,  2.74it/s]

[511/1000]
EN: Metro rail network expands 10,000 kilometres across 23 cities.
ASM: মেট্ৰ ৰেল নেটৱৰ্ক ২৩ খন চহৰত ১০,০০০ কিলোমিটাৰ বিস্তৃত ।
--------------------------------------------------

Translating ASM:  51%|███████████▊           | 512/1000 [03:57<02:58,  2.73it/s]

[512/1000]
EN: Swadesh Darshan 2.0 develops tourism sites to global standards.
ASM: স্বদেশ দৰ্শন ২.০য়ে পৰ্যটন ক্ষেত্ৰসমূহক বিশ্ব মানদণ্ডলৈ বিকশিত কৰিছে ।
--------------------------------------------------

Translating ASM:  51%|███████████▊           | 513/1000 [03:57<03:02,  2.66it/s]

[513/1000]
EN: PRASHAD scheme enhances pilgrimage tourism infrastructure across India.
ASM: প্ৰসাদ যোজনাই সমগ্ৰ ভাৰতত তীৰ্থযাত্ৰা পৰ্যটনৰ আন্তঃগাঁথনি উন্নত কৰিব ।
--------------------------------------------------

Translating ASM:  51%|███████████▊           | 514/1000 [03:57<03:15,  2.49it/s]

[514/1000]
EN: Saudi Red Sea authority enforces international safety standards for marine tourism.
ASM: ছৌডি ৰেড চি কৰ্তৃপক্ষই সামুদ্ৰিক পৰ্যটনৰ বাবে আন্তঃৰাষ্ট্ৰীয় সুৰক্ষা মানদণ্ড বলৱৎ কৰে ।
--------------------------------------------------

Translating ASM:  52%|███████████▊           | 515/1000 [03:58<03:20,  2.42it/s]

[515/1000]
EN: Saudi marine regulations protect Red Sea coral reef ecosystems.
ASM: ছৌডি সামুদ্ৰিক নিয়মাৱলীয়ে ৰঙা সাগৰৰ প্ৰবাল শিলা বাস্তুতন্ত্ৰক সুৰক্ষা প্ৰদান কৰে ।
--------------------------------------------------

Translating ASM:  52%|███████████▊           | 516/1000 [03:58<03:10,  2.54it/s]

[516/1000]
EN: Saudi Red Sea tourism to add 85 billion riyals to GDP.
ASM: ছৌডি ৰেড চি পৰ্যটনে জিডিপিলৈ ৮৫ বিলিয়ন ৰিয়াল যোগ কৰিব ।
--------------------------------------------------

Translating ASM:  52%|███████████▉           | 517/1000 [03:59<03:08,  2.56it/s]

[517/1000]
EN: Red Sea tourism creates 210,000 Saudi jobs by 2030.
ASM: ৰঙা সাগৰ পৰ্যটনে ২০৩০ চনৰ ভিতৰত ২১০,০০০ ছৌডি চাকৰি সৃষ্টি কৰিব ।
--------------------------------------------------

Translating ASM:  52%|███████████▉           | 518/1000 [03:59<02:58,  2.70it/s]

[518/1000]
EN: Indian Railways recovers only fraction of 4,087 crore dues.
ASM: ভাৰতীয় ৰেলৱে ৪০৮৭ কোটি কৰৰ মাত্ৰ এটা অংশহে ঘূৰাই পাইছে ।
--------------------------------------------------

Translating ASM:  52%|███████████▉           | 519/1000 [03:59<03:01,  2.65it/s]

[519/1000]
EN: RLDA develops only fraction of railway land for commercial use.
ASM: আৰএলডিএয়ে কেৱল বাণিজ্যিক ব্যৱহাৰৰ বাবে ৰেলপথৰ ভূমিৰ এটা অংশহে বিকশিত কৰে ।
--------------------------------------------------

Translating ASM:  52%|███████████▉           | 520/1000 [04:00<03:02,  2.63it/s]

[520/1000]
EN: Central Railway announces train diversions for Dasara and Diwali.
ASM: দশাৰা আৰু দীপাৱলীৰ বাবে কেন্দ্ৰীয় ৰেলৱেয়ে ৰেলৰ পৰিৱৰ্তনৰ ঘোষণা কৰিছে ।
--------------------------------------------------

Translating ASM:  52%|███████████▉           | 521/1000 [04:00<02:55,  2.74it/s]

[521/1000]
EN: SCR cancels 69 trains due to operational requirements.
ASM: এছচিআৰে অপাৰেশ্বনেল প্ৰয়োজনীয়তাৰ বাবে ৬৯ খন ৰেল বাতিল কৰিছে ।
--------------------------------------------------

Translating ASM:  52%|████████████           | 522/1000 [04:00<02:53,  2.75it/s]

[522/1000]
EN: South Central Railway diverts 29 trains for festival management.
ASM: দক্ষিণ কেন্দ্ৰীয় ৰেলৱে উৎসৱ পৰিচালনাৰ বাবে ২৯খন ৰেল চলাচল কৰে ।
--------------------------------------------------

Translating ASM:  52%|████████████           | 523/1000 [04:01<02:47,  2.85it/s]

[523/1000]
EN: Indian Railways announces 18 partially cancelled train services.
ASM: ভাৰতীয় ৰেলৱেই আংশিকভাৱে বাতিল কৰা ১৮টা ৰেল সেৱা ঘোষণা কৰিছে ।
--------------------------------------------------

Translating ASM:  52%|████████████           | 524/1000 [04:01<02:51,  2.77it/s]

[524/1000]
EN: Three trains rescheduled by South Central Railway authority.
ASM: দক্ষিণ কেন্দ্ৰীয় ৰেলৱে কৰ্তৃপক্ষৰ দ্বাৰা তিনিখন ৰেল পুনৰ শিডিউল কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  52%|████████████           | 525/1000 [04:01<02:45,  2.87it/s]

[525/1000]
EN: SCR cancels total 119 train services during peak season.
ASM: এছচিআৰে শিখৰকালত মুঠ ১১৯ টা ৰে'ল সেৱা বাতিল কৰে ।
--------------------------------------------------

Translating ASM:  53%|████████████           | 526/1000 [04:02<02:46,  2.84it/s]

[526/1000]
EN: Disney Cruise Line debuts Disney Destiny vessel in 2025.
ASM: ডিজনি ক্ৰুজ লাইনে ২০২৫ চনত ডিজনি ডেষ্টিনি জাহাজত আত্মপ্ৰকাশ কৰে ।
--------------------------------------------------

Translating ASM:  53%|████████████           | 527/1000 [04:02<02:52,  2.73it/s]

[527/1000]
EN: Norwegian Cruise Line adds Norwegian Aqua to fleet.
ASM: নৰৱেজীয়ান ক্ৰুজ লাইনে নৰৱেজীয়ান এক্ৱা বাহিনীত যোগ কৰে ।
--------------------------------------------------

Translating ASM:  53%|████████████▏          | 528/1000 [04:03<02:50,  2.76it/s]

[528/1000]
EN: Royal Caribbean launches Star of the Seas cruise ship.
ASM: ৰয়েল কেৰিবিয়ানছে ষ্টাৰ অৱ দ্য চিজ ক্ৰুজ জাহাজ মুকলি কৰে ।
--------------------------------------------------

Translating ASM:  53%|████████████▏          | 529/1000 [04:03<03:04,  2.55it/s]

[529/1000]
EN: Varanasi airport expands terminal to handle five million passengers.
ASM: বাৰাণসী বিমানবন্দৰে পাঁচ নিযুত যাত্ৰীক সামৰি লবলৈ টাৰ্মিনেলটো সম্প্ৰসাৰিত কৰিছে ।
--------------------------------------------------

Translating ASM:  53%|████████████▏          | 530/1000 [04:03<03:00,  2.61it/s]

[530/1000]
EN: Kashmir Railway line reaches Baramulla for all weather connectivity.
ASM: সকলো ধৰণৰ জলবায়ু সংযোগৰ বাবে কাশ্মীৰ ৰেল লাইন বাৰামুল্লালৈ যায় ।
--------------------------------------------------

Translating ASM:  53%|████████████▏          | 531/1000 [04:04<02:52,  2.72it/s]

[531/1000]
EN: Ayodhya airport commences commercial flight operations for pilgrims.
ASM: তীৰ্থযাত্ৰীসকলৰ বাবে অযোধ্যাৰ বিমানবন্দৰে বাণিজ্যিক বিমান সেৱা আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  53%|████████████▏          | 532/1000 [04:04<03:05,  2.52it/s]

[532/1000]
EN: Chennai metro phase two extension connects airport to city centre.
ASM: চেন্নাই মেট্ৰৰ দ্বিতীয় পৰ্যায়ৰ সম্প্ৰসাৰণে বিমানবন্দৰ আৰু চহৰৰ মাজত সংযোগ স্থাপন কৰিব ।
--------------------------------------------------

Translating ASM:  53%|████████████▎          | 533/1000 [04:05<03:06,  2.50it/s]

[533/1000]
EN: Mumbai Trans Harbour Link reduces travel time to Navi Mumbai airport.
ASM: মুম্বাই ট্ৰেন্স হাৰ্বাৰ লিংকে নাভি মুম্বাই বিমানবন্দৰলৈ ভ্ৰমণৰ সময় হ্ৰাস কৰে ।
--------------------------------------------------

Translating ASM:  53%|████████████▎          | 534/1000 [04:05<03:00,  2.58it/s]

[534/1000]
EN: Kashi Vishwanath corridor transforms pilgrimage experience in Varanasi.
ASM: কাশী বিশ্বনাথ কৰিডৰে বাৰাণসীত তীৰ্থযাত্ৰাৰ অভিজ্ঞতা পৰিৱৰ্তন কৰিছে ।
--------------------------------------------------

Translating ASM:  54%|████████████▎          | 535/1000 [04:05<02:43,  2.84it/s]

[535/1000]
EN: Hyatt completes acquisition of Playa Hotels and Resorts.
ASM: হাইএটে প্লেয়া হোটেল এণ্ড ৰিজৰ্টৰ অধিগ্ৰহণ সম্পূৰ্ণ কৰিছে ।
--------------------------------------------------

Translating ASM:  54%|████████████▎          | 536/1000 [04:06<02:51,  2.71it/s]

[536/1000]
EN: Hyatt adds fifteen beachfront properties across Mexico and Jamaica.
ASM: হাইটে মেক্সিকো আৰু জামাইকা জুৰি পোন্ধৰটা বিচফ্ৰণ্ট সম্পত্তি যোগ কৰিছে ।
--------------------------------------------------

Translating ASM:  54%|████████████▎          | 537/1000 [04:06<02:54,  2.65it/s]

[537/1000]
EN: Hyatt acquires Secrets La Romana in Dominican Republic.
ASM: হাইটে ডমিনিকান ৰিপাব্লিকত ৰহস্য লা ৰোমানা অধিগ্ৰহণ কৰে ।
--------------------------------------------------

Translating ASM:  54%|████████████▎          | 538/1000 [04:06<03:04,  2.50it/s]

[538/1000]
EN: Dreams La Romana joins Hyatt portfolio through Playa acquisition.
ASM: ড্ৰীমছ লা ৰোমানাই প্লেয়া অধিগ্ৰহণৰ জৰিয়তে হায়াট পৰ্টফোলিঅ'ত যোগদান কৰে ।
--------------------------------------------------

Translating ASM:  54%|████████████▍          | 539/1000 [04:07<03:02,  2.53it/s]

[539/1000]
EN: Dreams Rose Hall in Montego Bay transfers to Hyatt ownership.
ASM: মন্টেগ বেত থকা ড্ৰীমছ ৰজ হল হৱাইট সম্পত্তিলৈ স্থানান্তৰিত হয় ।
--------------------------------------------------

Translating ASM:  54%|████████████▍          | 540/1000 [04:07<02:54,  2.63it/s]

[540/1000]
EN: Hyatt Vivid Playa del Carmen added to hotel collection.
ASM: হোটেল সংগ্ৰহলৈ হাইয়াট ভিভিড প্লেয়া ডেল কাৰ্মেন সংযোজন কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  54%|████████████▍          | 541/1000 [04:08<02:47,  2.73it/s]

[541/1000]
EN: Sunscape Cancun becomes Hyatt property after Playa deal.
ASM: প্লেয়া চুক্তিৰ পিছত ছানস্কেপ কানকুন হৱাইট সম্পত্তি হৈ পৰে ।
--------------------------------------------------

Translating ASM:  54%|████████████▍          | 542/1000 [04:08<02:46,  2.75it/s]

[542/1000]
EN: Hotel infrastructure status unlocks private investment says Shekhawat.
ASM: হোটেলৰ আন্তঃগাঁথনিৰ স্থিতিয়ে ব্যক্তিগত বিনিয়োগ মুকলি কৰে বুলি শইকীয়াই কয় ।
--------------------------------------------------

Translating ASM:  54%|████████████▍          | 543/1000 [04:08<02:43,  2.79it/s]

[543/1000]
EN: FICCI annual general meeting discusses tourism growth strategy.
ASM: ফিক্কিৰ বাৰ্ষিক সাধাৰণ সভাত পৰ্যটন বিকাশৰ কৌশল সন্দৰ্ভত আলোচনা কৰা হয় ।
--------------------------------------------------

Translating ASM:  54%|████████████▌          | 544/1000 [04:09<02:47,  2.73it/s]

[544/1000]
EN: Harsh Vardhan Agarwal highlights tourism as economic driver.
ASM: হৰ্ষবৰ্ধন আগৰৱলে পৰ্যটনক অৰ্থনৈতিক চালক হিচাপে আলোকপাত কৰে ।
--------------------------------------------------

Translating ASM:  55%|████████████▌          | 545/1000 [04:09<02:43,  2.78it/s]

[545/1000]
EN: Anant Goenka praises Swadesh Darshan and PRASHAD initiatives.
ASM: অনন্ত গোয়েংকাই স্বদেশ দৰ্শন আৰু প্ৰসাদৰ প্ৰচেষ্টাক প্ৰশংসা কৰে ।
--------------------------------------------------

Translating ASM:  55%|████████████▌          | 546/1000 [04:09<02:34,  2.93it/s]

[546/1000]
EN: Indian hotel industry seeks infrastructure status for tax benefits.
ASM: ভাৰতীয় হোটেল উদ্যোগে কৰ লাভৰ বাবে আন্তঃগাঁথনিৰ স্থিতি বিচাৰে ।
--------------------------------------------------

Translating ASM:  55%|████████████▌          | 547/1000 [04:10<03:01,  2.49it/s]

[547/1000]
EN: Shangri-La Bengaluru hosts Chef Simone Loisi Italian culinary residency.
ASM: ছাংগ্ৰি-লা বেংগালুৰুত চেফ চিমোন লুইচি ইটালিয়ান কুলিনাৰী ৰেচিডেন্সি আয়োজিত হয় ।
--------------------------------------------------

Translating ASM:  55%|████████████▌          | 548/1000 [04:10<03:04,  2.45it/s]

[548/1000]
EN: Chef Simone Loisi brings Southern Italian cuisine to Bangalore.
ASM: চেফ চিমোন লুইচীয়ে বাংগালোৰলৈ দক্ষিণ ইটালিয়ান ৰন্ধনপ্ৰণালী লৈ আহে ।
--------------------------------------------------

Translating ASM:  55%|████████████▋          | 549/1000 [04:11<03:20,  2.25it/s]

[549/1000]
EN: Waterfall Ristorante Italiano chef showcases cuisine at Shangri-La.
ASM: ৱাটাৰফ্ল ৰেষ্টুৰেণ্ট ইটালিয়ানো চেফে ছাংগ্ৰি-লাত ৰন্ধনপ্ৰণালী প্ৰদৰ্শন কৰে ।
--------------------------------------------------

Translating ASM:  55%|████████████▋          | 550/1000 [04:11<03:13,  2.32it/s]

[550/1000]
EN: Four Seasons Bengaluru transforms for Halloween 2025 celebrations.
ASM: হ্যালোইন ২০২৫ উদযাপনৰ বাবে চাৰিটা ঋতু বেংগালুৰু পৰিৱৰ্তন হৈছে ।
--------------------------------------------------

Translating ASM:  55%|████████████▋          | 551/1000 [04:12<03:08,  2.38it/s]

[551/1000]
EN: CUR8 hosts family friendly Halloween evening in Bengaluru.
ASM: চিইআৰ৮য়ে বেংগালুৰুত পৰিয়াল বান্ধৱী হ্যালোইন সন্ধিয়া আয়োজন কৰে ।
--------------------------------------------------

Translating ASM:  55%|████████████▋          | 552/1000 [04:12<03:00,  2.49it/s]

[552/1000]
EN: Copitas bar ranks in Asia's 50 Best Bars list.
ASM: কপিটাছ বাৰ এছিয়াৰ ৫০ টা শ্ৰেষ্ঠ বাৰ তালিকাত স্থান লাভ কৰিছে ।
--------------------------------------------------

Translating ASM:  55%|████████████▋          | 553/1000 [04:12<02:59,  2.50it/s]

[553/1000]
EN: Four Seasons Bengaluru hosts Día de Muertos Halloween party.
ASM: চাৰিটা ঋতু বেংগালুৰুত দে দে মৰেটছ হ্যালোইন পাৰ্টীৰ আয়োজন কৰা হয় ।
--------------------------------------------------

Translating ASM:  55%|████████████▋          | 554/1000 [04:13<03:01,  2.46it/s]

[554/1000]
EN: Sheraton Hyderabad invites guests to Feast Halloween buffet.
ASM: শ্বেৰাটন হায়দৰাবাদে অতিথিসকলক ফেষ্ট হ্যালোইন বুফেটলৈ আমন্ত্ৰণ কৰে ।
--------------------------------------------------

Translating ASM:  56%|████████████▊          | 555/1000 [04:13<03:11,  2.32it/s]

[555/1000]
EN: Chef Yugal Sharma represents North West Frontier cuisine at ITC.
ASM: চিফ য়ুগল শৰ্মাই আইটিচিত নৰ্থ ৱেষ্ট ফ্ৰণ্টিয়াৰ ৰন্ধনপ্ৰণালীক প্ৰতিনিধিত্ব কৰে ।
--------------------------------------------------

Translating ASM:  56%|████████████▊          | 556/1000 [04:14<03:11,  2.31it/s]

[556/1000]
EN: Royal Afghan assistant master chef promotes rustic Indian cuisine.
ASM: ৰাজকীয় আফগানিস্তানৰ সহকাৰী মাষ্টাৰ চেফে দেশীয় ভাৰতীয় খাদ্যৰ প্ৰচাৰ কৰে ।
--------------------------------------------------

Translating ASM:  56%|████████████▊          | 557/1000 [04:14<03:18,  2.23it/s]

[557/1000]
EN: The Leela Hyderabad hosts Chef Picched three-day Thai culinary showcase.
ASM: লীলা হায়দৰাবাদত চেফ পিকচ্ডৰ তিনিদিনীয়া থাই ৰন্ধনপ্ৰণালী প্ৰদৰ্শনী অনুষ্ঠিত হয় ।
--------------------------------------------------

Translating ASM:  56%|████████████▊          | 558/1000 [04:15<03:09,  2.33it/s]

[558/1000]
EN: Chef Picched Paoleng brings authentic Bangkok cuisine to Hyderabad.
ASM: চেফ পিকচ্ড পাওলঙে হায়দৰাবাদলৈ প্ৰকৃত বেংককৰ খাদ্য সামগ্ৰী লৈ আহে ।
--------------------------------------------------

Translating ASM:  56%|████████████▊          | 559/1000 [04:15<03:18,  2.22it/s]

[559/1000]
EN: Marriott Executive Apartments Bengaluru unveils Madras Kitchen restaurant.
ASM: মাৰিয়ট এক্সিকিউটিভ এপাৰ্টমেণ্ট বেংগালুৰুয়ে মাদ্ৰাজ কিচেন ৰেষ্টুৰেণ্ট উন্মোচন কৰে ।
--------------------------------------------------

Translating ASM:  56%|████████████▉          | 560/1000 [04:15<03:11,  2.30it/s]

[560/1000]
EN: Madras Kitchen pays homage to South Indian gastronomic heritage.
ASM: মাদ্ৰাছ কিচনে দক্ষিণ ভাৰতীয় গ্যাষ্ট্ৰোনমিক ঐতিহ্যৰ প্ৰতি শ্ৰদ্ধাঞ্জলি জ্ঞাপন কৰে ।
--------------------------------------------------

Translating ASM:  56%|████████████▉          | 561/1000 [04:16<03:12,  2.28it/s]

[561/1000]
EN: ITC Grand Bharat chef shares Diwali festive dinner hosting tips.
ASM: আইটিচি গ্ৰেণ্ড ভাৰত চেফে দীপাৱলী উৎসৱ ডিনাৰ হোস্টিংৰ টিপছ শ্বেয়াৰ কৰে ।
--------------------------------------------------

Translating ASM:  56%|████████████▉          | 562/1000 [04:16<03:15,  2.25it/s]

[562/1000]
EN: Marriott Executive Apartments Hyderabad celebrates Hyderabadi dessert heritage.
ASM: মৰিয়ট এক্সিকিউটিভ এপাৰ্টমেণ্ট হায়দৰাবাদে হায়দৰাবাদৰ মিঠা ঐতিহ্য উদযাপন কৰে ।
--------------------------------------------------

Translating ASM:  56%|████████████▉          | 563/1000 [04:17<03:11,  2.28it/s]

[563/1000]
EN: 4Note culinary hot spot opens with four kitchens concept.
ASM: ৪নোট ৰন্ধনপ্ৰণালী হটস্পট চাৰিটা ৰন্ধনশালাৰ ধাৰণাৰ সৈতে মুকলি হয় ।
--------------------------------------------------

Translating ASM:  56%|████████████▉          | 564/1000 [04:17<03:06,  2.34it/s]

[564/1000]
EN: Zuma Abu Dhabi maintains global legacy restaurant standards.
ASM: জুমা আবু ধাবীয়ে বিশ্বব্যাপী ঐতিহ্যপূৰ্ণ ৰেষ্টুৰেণ্ট মান বজাই ৰাখিছে ।
--------------------------------------------------

Translating ASM:  56%|████████████▉          | 565/1000 [04:18<03:02,  2.39it/s]

[565/1000]
EN: Dubai chocolate craze triggers global pistachio shortage crisis.
ASM: দুবাই চকলেটৰ উন্মাদনায়ে বিশ্বব্যাপী পিষ্টচিৰ অভাৱৰ সংকট সৃষ্টি কৰিছে ।
--------------------------------------------------

Translating ASM:  57%|█████████████          | 566/1000 [04:18<02:54,  2.49it/s]

[566/1000]
EN: Indian Hotels Company signs new Taj property in Lucknow.
ASM: ইণ্ডিয়ান হোটেল কোম্পানীয়ে লক্ষ্ণৌত নতুন তাজ সম্পত্তিৰ বাবে স্বাক্ষৰ কৰিছে ।
--------------------------------------------------

Translating ASM:  57%|█████████████          | 567/1000 [04:18<02:54,  2.48it/s]

[567/1000]
EN: Oberoi Group announces luxury resort opening in Ranthambhore.
ASM: ওবেৰয় গ্ৰুপে ৰন্ধাম্বোৰত বিলাসী ৰিজ ৰ্ট খোলাৰ কথা ঘোষণা কৰিছে ।
--------------------------------------------------

Translating ASM:  57%|█████████████          | 568/1000 [04:19<03:00,  2.40it/s]

[568/1000]
EN: Lemon Tree Hotels expands northeast presence with Guwahati property.
ASM: লেমুন ট্ৰী হোটেলসমূহে গুৱাহাটী সম্পত্তিৰ সৈতে উত্তৰ-পূবৰ উপস্থিতি সম্প্ৰসাৰিত কৰিছে ।
--------------------------------------------------

Translating ASM:  57%|█████████████          | 569/1000 [04:19<02:53,  2.48it/s]

[569/1000]
EN: Marriott International to open 50th property in India by 2026.
ASM: ২০২৬ চনৰ ভিতৰত ভাৰতত ৫০ সংখ্যক প্ৰকল্প মুকলি কৰিব মাৰিয়ট ইন্টাৰনেশ্যনেলে ।
--------------------------------------------------

Translating ASM:  57%|█████████████          | 570/1000 [04:20<02:49,  2.54it/s]

[570/1000]
EN: Radisson Hotel Group targets 200 hotels across India by 2027.
ASM: ৰেডিছন হোটেল গ্ৰুপে ২০২৭ চনৰ ভিতৰত সমগ্ৰ ভাৰতত ২০০ টা হোটেলৰ লক্ষ্য নিৰ্ধাৰণ কৰিছে ।
--------------------------------------------------

Translating ASM:  57%|█████████████▏         | 571/1000 [04:20<02:50,  2.51it/s]

[571/1000]
EN: OYO announces international expansion into Vietnam and Indonesia.
ASM: অইওয়ে ভিয়েটনাম আৰু ইণ্ডোনেছিয়াত আন্তঃৰাষ্ট্ৰীয় সম্প্ৰসাৰণৰ কথা ঘোষণা কৰিছে ।
--------------------------------------------------

Translating ASM:  57%|█████████████▏         | 572/1000 [04:20<02:58,  2.40it/s]

[572/1000]
EN: MakeMyTrip partners with IHCL for exclusive holiday packages.
ASM: নিৰ্দ্দিষ্ট ছুটী পেকেজৰ বাবে মেক মাইট্ৰিপৰ সৈতে আইএইচচিএলৰ অংশীদাৰিত্ব আছে ।
--------------------------------------------------

Translating ASM:  57%|█████████████▏         | 573/1000 [04:21<02:43,  2.60it/s]

[573/1000]
EN: Maha Kumbh Mela creates one million jobs for local families.
ASM: মহাকুম্ব মেলাই স্থানীয় পৰিয়ালসমূহৰ বাবে এক লাখ চাকৰি সৃষ্টি কৰিব ।
--------------------------------------------------

Translating ASM:  57%|█████████████▏         | 574/1000 [04:21<02:40,  2.66it/s]

[574/1000]
EN: Boat services at Kumbh earn families collective 30 crore rupees.
ASM: কুম্ভত নৌকা সেৱাৰ বাবে পৰিয়ালসমূহে সামূহিকভাৱে ৩০ কোটি টকা উপাৰ্জন কৰে ।
--------------------------------------------------

Translating ASM:  57%|█████████████▏         | 575/1000 [04:21<02:49,  2.51it/s]

[575/1000]
EN: The Guardian describes Prayagraj Kumbh as pop-up megacity.
ASM: গাৰ্ডিয়ান আলোচনীয়ে প্ৰয়াগৰাজ কুম্ভক পপ-আপ মেগা চহৰ বুলি বৰ্ণনা কৰিছে ।
--------------------------------------------------

Translating ASM:  58%|█████████████▏         | 576/1000 [04:22<02:37,  2.69it/s]

[576/1000]
EN: Maharashtra Economic Council reports Kumbh employment generation.
ASM: মহাৰাষ্ট্ৰ অৰ্থনৈতিক পৰিষদে কুম্ভ নিয়োগ সৃষ্টিৰ প্ৰতিবেদন দিছে ।
--------------------------------------------------

Translating ASM:  58%|█████████████▎         | 577/1000 [04:22<02:45,  2.56it/s]

[577/1000]
EN: FIFA Club World Cup 2025 brings global visitors to host cities.
ASM: ফিফা ক্লাব বিশ্বকাপ ২০২৫ বিশ্বব্যাপী দৰ্শনাৰ্থীক আয়োজক চহৰলৈ লৈ আহে ।
--------------------------------------------------

Translating ASM:  58%|█████████████▎         | 578/1000 [04:23<02:44,  2.57it/s]

[578/1000]
EN: Wimbledon 2025 witnesses global unity through international tennis.
ASM: আন্তৰ্জাতিক টেনিছৰ জৰিয়তে বিশ্বব্যাপী ঐক্যৰ সাক্ষী উইম্বলডন ২০২৫ ।
--------------------------------------------------

Translating ASM:  58%|█████████████▎         | 579/1000 [04:23<02:38,  2.65it/s]

[579/1000]
EN: Sikh pilgrims receive Pakistani visas after Operation Sindoor.
ASM: শিখ তীৰ্থযাত্ৰীসকলে অপাৰেশ্যন ছিন্দুৰৰ পিছত পাকিস্তানী ভিছা লাভ কৰে ।
--------------------------------------------------

Translating ASM:  58%|█████████████▎         | 580/1000 [04:23<02:42,  2.59it/s]

[580/1000]
EN: Harjindarpal Singh secures passport and Pakistan visa for pilgrimage.
ASM: হাৰ্জিন্দাৰপাল সিঙে তীৰ্থযাত্ৰাৰ বাবে পাছপোৰ্ট আৰু পাকিস্তান ভিছা নিশ্চিত কৰে ।
--------------------------------------------------

Translating ASM:  58%|█████████████▎         | 581/1000 [04:24<02:33,  2.72it/s]

[581/1000]
EN: First Sikh Jathas travel to Pakistan post visa ban reversal.
ASM: ভিছা নিষেধাজ্ঞা প্ৰত্যাৱৰ্তনৰ পিছত প্ৰথম শিখ যাত্ৰীয়ে পাকিস্তান ভ্ৰমণ কৰে ।
--------------------------------------------------

Translating ASM:  58%|█████████████▍         | 582/1000 [04:24<02:32,  2.74it/s]

[582/1000]
EN: FIDE names World Chess Cup trophy after Viswanathan Anand.
ASM: বিশ্বনাথন আনন্দৰ নামত বিশ্ব চেছ কাপ ট্ৰফীৰ নাম দিলে ফিডে ।
--------------------------------------------------

Translating ASM:  58%|█████████████▍         | 583/1000 [04:24<02:23,  2.90it/s]

[583/1000]
EN: Panjim hosts FIDE World Chess Cup with Anand trophy.
ASM: আনন্দ ট্ৰফীৰ সৈতে ফিডে বিশ্ব চেছ কাপ আয়োজন পাঞ্জিমৰ ।
--------------------------------------------------

Translating ASM:  58%|█████████████▍         | 584/1000 [04:25<02:34,  2.69it/s]

[584/1000]
EN: Krishna Janmashtami procession turns tragic in Ramanthapur.
ASM: ৰামাণ্টপুৰত কৃষ্ণ জনমষ্টমীৰ শোভাযাত্ৰা দুর্যোগপূৰ্ণ হৈ পৰিছে ।
--------------------------------------------------

Translating ASM:  58%|█████████████▍         | 585/1000 [04:25<02:29,  2.78it/s]

[585/1000]
EN: Ten-foot chariot touches live wire killing five devotees.
ASM: দহ ফুট দীঘল ৰথৰ স্পৰ্শত পাঁচজন ভক্তৰ মৃত্যু হয় ।
--------------------------------------------------

Translating ASM:  59%|█████████████▍         | 586/1000 [04:25<02:30,  2.75it/s]

[586/1000]
EN: Hyderabad celebrates Ganesh festival with large screen displays.
ASM: হায়দৰাবাদত গণেশ মহোৎসৱ বৃহৎ স্ক্ৰীণ প্ৰদৰ্শন কৰি উদযাপন কৰা হয় ।
--------------------------------------------------

Translating ASM:  59%|█████████████▌         | 587/1000 [04:26<02:32,  2.70it/s]

[587/1000]
EN: Begum Bazaar jam-packed for night long festival celebrations.
ASM: বেগম বজাৰত ৰাতিৰ দীঘলীয়া উৎসৱ উদযাপনৰ বাবে জামৰে ভৰি আছে ।
--------------------------------------------------

Translating ASM:  59%|█████████████▌         | 588/1000 [04:26<02:29,  2.76it/s]

[588/1000]
EN: Muslim leader Sadeq Siraj organizes eye camp for community.
ASM: মুছলমান নেতা ছাদিক ছিৰাজে সম্প্ৰদায়ৰ বাবে চকু শিবিৰ আয়োজন কৰে ।
--------------------------------------------------

Translating ASM:  59%|█████████████▌         | 589/1000 [04:27<02:34,  2.66it/s]

[589/1000]
EN: Hyderabad pandals adopt traditional themes for Ganesh Chaturthi.
ASM: হায়দৰাবাদৰ পণ্ডলসকলে গণেশ চতুৰ্থীৰ বাবে পৰম্পৰাগত বিষয়বস্তু গ্ৰহণ কৰে ।
--------------------------------------------------

Translating ASM:  59%|█████████████▌         | 590/1000 [04:27<02:34,  2.66it/s]

[590/1000]
EN: Shuja Ifteqari requests Chief Minister Revanth Reddy for arrangements.
ASM: শুজা ইফটেক্কাৰীয়ে মুখ্যমন্ত্ৰী ৰেভন্ত ৰেড্ডীক ব্যৱস্থা কৰিবলৈ অনুৰোধ জনাইছে ।
--------------------------------------------------

Translating ASM:  59%|█████████████▌         | 591/1000 [04:27<02:41,  2.53it/s]

[591/1000]
EN: SOCIAL Hyderabad hosts She's a Phataka Diwali celebration bash.
ASM: ছচিয়েল হায়দৰাবাদৰ আয়োজক তেওঁ ফটকা দীপাৱলী উদযাপন বাছ ।
--------------------------------------------------

Translating ASM:  59%|█████████████▌         | 592/1000 [04:28<02:35,  2.62it/s]

[592/1000]
EN: Hyderabad soaked in festival fervour with rain showers.
ASM: হায়দৰাবাদত বৰষুণৰ বৰষুণেৰে উৎসৱৰ উৎসাহ জন্মালে ।
--------------------------------------------------

Translating ASM:  59%|█████████████▋         | 593/1000 [04:28<02:28,  2.74it/s]

[593/1000]
EN: Dasara trains diverted to manage two lakh passenger footfall.
ASM: দুই লাখ যাত্ৰী ভ্ৰমণ ব্যৱস্থাপনাৰ বাবে বদলি কৰা হল দশাৰা ৰেল ।
--------------------------------------------------

Translating ASM:  59%|█████████████▋         | 594/1000 [04:28<02:26,  2.77it/s]

[594/1000]
EN: New passenger routes planned for Dasara and Diwali travel.
ASM: দশাৰা আৰু দীপাৱলী ভ্ৰমণৰ বাবে নতুন যাত্ৰীবাহী পথৰ পৰিকল্পনা কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  60%|█████████████▋         | 595/1000 [04:29<02:38,  2.55it/s]

[595/1000]
EN: Hyderabad kiosks offer Ganesh idols across every street.
ASM: হায়দৰাবাদৰ কিঅস্কে প্ৰত্যেকটো আলিৰ সিপাৰে গণেশৰ প্ৰতিমূৰ্তি প্ৰদৰ্শন কৰে ।
--------------------------------------------------

Translating ASM:  60%|█████████████▋         | 596/1000 [04:29<02:34,  2.61it/s]

[596/1000]
EN: Indian Navy monitors every Chinese vessel in Indian Ocean.
ASM: ভাৰতীয় নৌসেনাই ভাৰতীয় মহাসাগৰত থকা প্ৰতিটো চীনা জাহাজক নিৰীক্ষণ কৰি আছে ।
--------------------------------------------------

Translating ASM:  60%|█████████████▋         | 597/1000 [04:30<02:37,  2.55it/s]

[597/1000]
EN: Vice Admiral Sanjay Vatsayan confirms continuous maritime surveillance.
ASM: ভাইচ এডমাইৰেল সঞ্জয় ৱাটছায়ানে অব্যাহত সামুদ্ৰিক নিৰীক্ষণ নিশ্চিত কৰে ।
--------------------------------------------------

Translating ASM:  60%|█████████████▊         | 598/1000 [04:30<02:28,  2.71it/s]

[598/1000]
EN: Goa tourism department announces calendar of winter festivals.
ASM: গোৱা পৰ্যটন বিভাগে শীতকালীন উৎসৱৰ কেলেণ্ডাৰ ঘোষণা কৰিছে ।
--------------------------------------------------

Translating ASM:  60%|█████████████▊         | 599/1000 [04:30<02:31,  2.66it/s]

[599/1000]
EN: Jaipur Literature Festival attracts 50,000 book lovers from abroad.
ASM: জয়পুৰ সাহিত্য মহোৎসৱে বিদেশৰ পৰা ৫০ হাজাৰ গ্ৰন্থপ্ৰেমীক আকৰ্ষণ কৰে ।
--------------------------------------------------

Translating ASM:  60%|█████████████▊         | 600/1000 [04:31<02:26,  2.74it/s]

[600/1000]
EN: Rann Utsav begins in Kutch with tent city bookings full.
ASM: তম্বু চহৰৰ বুকিং সম্পূৰ্ণ কৰি কচ্চত ৰান উটছাও আৰম্ভ হয় ।
--------------------------------------------------

Translating ASM:  60%|█████████████▊         | 601/1000 [04:31<02:30,  2.65it/s]

[601/1000]
EN: Hornbill Festival showcases Naga heritage in Kisama heritage village.
ASM: হৰ্ণবিল উৎসৱত কিচামা ঐতিহ্য গাঁৱত নাগা ঐতিহ্য প্ৰদৰ্শন কৰা হয় ।
--------------------------------------------------

Translating ASM:  60%|█████████████▊         | 602/1000 [04:32<02:37,  2.53it/s]

[602/1000]
EN: Ganga Aarti at Varanasi draws record international tourist attendance.
ASM: বাৰাণসীত গংগা আৰ্তিয়ে অভিলেখ সংখ্যক আন্তঃৰাষ্ট্ৰীয় পৰ্যটকৰ উপস্থিতি আকৰ্ষণ কৰে ।
--------------------------------------------------

Translating ASM:  60%|█████████████▊         | 603/1000 [04:32<02:35,  2.56it/s]

[603/1000]
EN: Pahalgam terror attack kills twenty-six tourists including foreigners.
ASM: পহালগাম সন্ত্ৰাসবাদী আক্ৰমণত বিদেশীকে ধৰি ছয়িশজন পৰ্যটক নিহত হয় ।
--------------------------------------------------

Translating ASM:  60%|█████████████▉         | 604/1000 [04:32<02:39,  2.49it/s]

[604/1000]
EN: Terrorists attack Baisaran meadows killing twenty-six civilian tourists.
ASM: সন্ত্ৰাসবাদীয়ে বৈসৰণ ময়দানত আক্ৰমণ কৰি ছয়িশজন অসামৰিক পৰ্যটকক হত্যা কৰে ।
--------------------------------------------------

Translating ASM:  60%|█████████████▉         | 605/1000 [04:33<02:30,  2.62it/s]

[605/1000]
EN: Two foreign tourists among twenty-six dead in Pahalgam attack.
ASM: পহালগাম আক্ৰমণত ২৬ জন নিহতৰ ভিতৰত দুজন বিদেশী পৰ্যটক ।
--------------------------------------------------

Translating ASM:  61%|█████████████▉         | 606/1000 [04:33<02:32,  2.59it/s]

[606/1000]
EN: Operation Sindoor launched following deadly Pahalgam tourist attack.
ASM: পহালগাম পৰ্যটকৰ মাৰাত্মক আক্ৰমণৰ পিছত অপাৰেচন ছিণ্ডুৰ আৰম্ভ কৰা হয় ।
--------------------------------------------------

Translating ASM:  61%|█████████████▉         | 607/1000 [04:34<02:33,  2.56it/s]

[607/1000]
EN: Saudi Arabia minister Adel Al-Jubeir arrives in Delhi post Operation Sindoor.
ASM: ছৌডি আৰৱৰ মন্ত্ৰী আদেল আল-জুবেয়াৰ অপাৰেচন ছিণ্ডুৰৰ পিছত দিল্লীত উপস্থিত হয় ।
--------------------------------------------------

Translating ASM:  61%|█████████████▉         | 608/1000 [04:34<02:32,  2.57it/s]

[608/1000]
EN: Iranian Foreign Minister Araghchi visits New Delhi amid tensions.
ASM: উত্তেজনাৰ মাজতে নতুন দিল্লী ভ্ৰমণ কৰে ইৰানৰ বৈদেশিক মন্ত্ৰী আৰাগচিয়ে ।
--------------------------------------------------

Translating ASM:  61%|██████████████         | 609/1000 [04:34<02:28,  2.64it/s]

[609/1000]
EN: Delhi Red Fort blast leaves fourteen dead and several injured.
ASM: দিল্লী ৰেড ফৰ্ট বিস্ফোৰণত ১৪ জন নিহত আৰু কেইবাজনো আহত হয় ।
--------------------------------------------------

Translating ASM:  61%|██████████████         | 610/1000 [04:35<02:24,  2.71it/s]

[610/1000]
EN: High intensity explosion outside Red Fort kills fourteen people.
ASM: ৰেড ফৰ্টৰ বাহিৰত উচ্চ তীব্ৰতাসম্পন্ন বিস্ফোৰণত ১৪ জন লোকৰ মৃত্যু ।
--------------------------------------------------

Translating ASM:  61%|██████████████         | 611/1000 [04:35<02:28,  2.62it/s]

[611/1000]
EN: Supreme Court upholds Christian Army officer Samuel Kamalesan dismissal.
ASM: উচ্চতম ন্যায়ালয়ে খ্ৰীষ্টান সেনাৰ বিষয়া চমুৱেল কমলেছনৰ নিলম্বনক সমৰ্থন কৰে ।
--------------------------------------------------

Translating ASM:  61%|██████████████         | 612/1000 [04:35<02:22,  2.73it/s]

[612/1000]
EN: Army officer refuses temple pooja entry leading to dismissal.
ASM: সেনা বিষয়াজনে মন্দিৰ পূজাৰ প্ৰৱেশ অস্বীকাৰ কৰাৰ ফলত নিলম্বন কৰা হয় ।
--------------------------------------------------

Translating ASM:  61%|██████████████         | 613/1000 [04:36<02:30,  2.58it/s]

[613/1000]
EN: Chief Justice Surya Kant terms refusal grossest kind of indiscipline.
ASM: মুখ্য ন্যায়াধীশ সূৰ্য্য কান্তে অস্বীকাৰক আটাইতকৈ চৰম ধৰণৰ অনিয়ম বুলি অভিহিত কৰে ।
--------------------------------------------------

Translating ASM:  61%|██████████████         | 614/1000 [04:36<02:32,  2.53it/s]

[614/1000]
EN: Saif Ali Khan undergoes surgery after knife attack at residence.
ASM: ছাইফ আলী খানৰ বাসগৃহত ছুৰীৰে আক্ৰমণ কৰাৰ পিছত অস্ত্ৰোপচাৰ কৰা হয় ।
--------------------------------------------------

Translating ASM:  62%|██████████████▏        | 615/1000 [04:37<02:32,  2.53it/s]

[615/1000]
EN: Intruder attacks Bollywood actor Saif Ali Khan in Mumbai.
ASM: মুম্বাইত বলীউডৰ অভিনেতা ছাইফ আলি খানৰ ওপৰত আক্ৰমণ অনুপ্ৰৱেশকাৰীৰ ।
--------------------------------------------------

Translating ASM:  62%|██████████████▏        | 616/1000 [04:37<02:27,  2.60it/s]

[616/1000]
EN: Mumbai police identify accused in Saif Ali Khan attack case.
ASM: ছাইফ আলী খান আক্ৰমণৰ গোচৰত মুম্বাই আৰক্ষীয়ে অভিযুক্তক চিনাক্ত কৰে ।
--------------------------------------------------

Translating ASM:  62%|██████████████▏        | 617/1000 [04:37<02:27,  2.60it/s]

[617/1000]
EN: Actor discharged five days after hospitalization following attack.
ASM: আক্ৰমণৰ পিছত চিকিৎসালয়ত ভৰ্তি হোৱাৰ পাঁচ দিনৰ পিছতে অভিনেতাজনক ঘৰলৈ যাবলৈ দিয়া হয় ।
--------------------------------------------------

Translating ASM:  62%|██████████████▏        | 618/1000 [04:38<02:34,  2.47it/s]

[618/1000]
EN: Tihar jail probe reveals racket charging for free inmate meetings.
ASM: তিহাৰ কাৰাগাৰৰ অনুসন্ধানত প্ৰকাশ পাইছে বিনামূলীয়া বন্দীসকলৰ সভাবোৰৰ বাবে ৰেকেট চাৰ্জিং ।
--------------------------------------------------

Translating ASM:  62%|██████████████▏        | 619/1000 [04:38<02:24,  2.63it/s]

[619/1000]
EN: Undercover officials exposed illegal mulakat charges at Tihar.
ASM: গোপন বিষয়াসকলে তিহাৰত অবৈধ মুলাট অভিযোগ উন্মোচন কৰিছিল ।
--------------------------------------------------

Translating ASM:  62%|██████████████▎        | 620/1000 [04:38<02:20,  2.70it/s]

[620/1000]
EN: Tihar transfers twenty-five data entry operators after tout investigation.
ASM: থিহাৰে তদন্তৰ পিছত পঁচিশটা ডাটা এন্ট্ৰী অপাৰেটৰ স্থানান্তৰ কৰে ।
--------------------------------------------------

Translating ASM:  62%|██████████████▎        | 621/1000 [04:39<02:18,  2.73it/s]

[621/1000]
EN: Biometric authentication introduced at Tihar Jail for security.
ASM: নিৰাপত্তাৰ বাবে তিহাৰ কাৰাগাৰত বায়মেট্ৰিক প্ৰমাণপত্ৰ প্ৰৱৰ্তন কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  62%|██████████████▎        | 622/1000 [04:39<02:19,  2.71it/s]

[622/1000]
EN: Supreme Court declines virtual appearance exemption for chief secretaries.
ASM: মুখ্য সচিবসকলৰ বাবে ভাৰ্চুৱেল চেহেৰাৰ ৰেহাই উচ্চতম ন্যায়ালয়ে অস্বীকাৰ কৰিছে ।
--------------------------------------------------

Translating ASM:  62%|██████████████▎        | 623/1000 [04:40<02:20,  2.68it/s]

[623/1000]
EN: States sleeping over stray dog sterilization orders says Supreme Court.
ASM: বিচৰণকাৰী কুকুৰ বন্ধ্যাত্বৰ আদেশৰ ওপৰত ৰাজ্যবোৰ টোপনি গৈছে বুলি উচ্চতম ন্যায়ালয়ে কৈছে ।
--------------------------------------------------

Translating ASM:  62%|██████████████▎        | 624/1000 [04:40<02:12,  2.83it/s]

[624/1000]
EN: Passenger forced to write letter after Delhi airport assault.
ASM: দিল্লী বিমানবন্দৰৰ আক্ৰমণৰ পিছত যাত্ৰীয়ে চিঠি লিখিবলৈ বাধ্য হৈছিল ।
--------------------------------------------------

Translating ASM:  62%|██████████████▍        | 625/1000 [04:40<02:08,  2.91it/s]

[625/1000]
EN: Passenger claims pressure to avoid police complaint filing.
ASM: যাত্ৰীজনে আৰক্ষীৰ অভিযোগ দাখিল কৰাৰ পৰা আঁতৰি থাকিবলৈ চাপৰ দাবী কৰে ।
--------------------------------------------------

Translating ASM:  63%|██████████████▍        | 626/1000 [04:41<02:24,  2.59it/s]

[626/1000]
EN: US forces seize oil tanker off Venezuela for narco-terrorism.
ASM: আমেৰিকান বাহিনীয়ে ড্ৰাগছ সন্ত্ৰাসবাদৰ বাবে ভেনেজুয়েলা উপকূলৰ পৰা তেল টেংকাৰ জব্দ কৰে ।
--------------------------------------------------

Translating ASM:  63%|██████████████▍        | 627/1000 [04:41<02:29,  2.49it/s]

[627/1000]
EN: US Coast Guard apprehends tanker with Department of Defense backing.
ASM: আমেৰিকা যুক্তৰাষ্ট্ৰৰ উপকূলীয় নিৰাপত্তাৰক্ষীয়ে প্ৰতিৰক্ষা বিভাগৰ সমৰ্থনত টেংকাৰক আটক কৰে ।
--------------------------------------------------

Translating ASM:  63%|██████████████▍        | 628/1000 [04:42<02:28,  2.50it/s]

[628/1000]
EN: Supreme Court denies relief to mosque seeking loudspeaker permission.
ASM: উচ্চতম ন্যায়ালয়ে লাউডস্পীকাৰৰ অনুমতি বিচাৰি মছজিদলৈ সাহায্য বিচাৰি অস্বীকাৰ কৰিছে ।
--------------------------------------------------

Translating ASM:  63%|██████████████▍        | 629/1000 [04:42<02:32,  2.43it/s]

[629/1000]
EN: Nagpur bench rules no religion mandates prayers with amplifiers.
ASM: নাগপুৰ বেঞ্চে কোনো ধৰ্ম্মক নিয়ন্ত্ৰণ নকৰে এম্প্লিফায়াৰৰ সৈতে প্ৰাৰ্থনা কৰিবলৈ বাধ্যতামূলক কৰে ।
--------------------------------------------------

Translating ASM:  63%|██████████████▍        | 630/1000 [04:42<02:29,  2.47it/s]

[630/1000]
EN: Cruise Saudi brand operations commence with Red Sea licences.
ASM: ক্ৰুজ ছৌডি ব্ৰেণ্ডৰ কাম-কাজ ৰেড চি লাইচেন্সৰ সৈতে আৰম্ভ হয় ।
--------------------------------------------------

Translating ASM:  63%|██████████████▌        | 631/1000 [04:43<02:28,  2.49it/s]

[631/1000]
EN: Marina services added to Saudi marine tourism portfolio.
ASM: মৰিনা সেৱা ছৌডি সামুদ্ৰিক পৰ্যটন পৰ্টফোলিওত যোগ কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  63%|██████████████▌        | 632/1000 [04:43<02:30,  2.45it/s]

[632/1000]
EN: Recreational marine activities licensed by Saudi Red Sea Authority.
ASM: ছৌডি ৰেড চি অথৰিটিৰ দ্বাৰা অনুজ্ঞাপত্ৰপ্ৰাপ্ত মনোৰঞ্জন সামুদ্ৰিক কাৰ্যকলাপ ।
--------------------------------------------------

Translating ASM:  63%|██████████████▌        | 633/1000 [04:44<02:31,  2.42it/s]

[633/1000]
EN: Saudi Arabia enforces qualified crews for marine tourism operations.
ASM: ছৌডি আৰবে সামুদ্ৰিক পৰ্যটন কাৰ্যকলাপৰ বাবে যোগ্যতাসম্পন্ন কৰ্মীসকলক বলৱৎ কৰে ।
--------------------------------------------------

Translating ASM:  63%|██████████████▌        | 634/1000 [04:44<02:31,  2.42it/s]

[634/1000]
EN: Red Sea unregulated maritime activity concerns addressed by licences.
ASM: ৰেড চিৰ নিয়ন্ত্রিত নোহোৱা সামুদ্ৰিক কাৰ্যকলাপৰ বিষয়সমূহ লাইচেন্সৰ দ্বাৰা সমাধান কৰা হয় ।
--------------------------------------------------

Translating ASM:  64%|██████████████▌        | 635/1000 [04:44<02:24,  2.52it/s]

[635/1000]
EN: Indian cruise tourism gets boost with ten new terminals.
ASM: দহটা নতুন টাৰ্মিনেলৰ সৈতে ভাৰতীয় ক্ৰুজ পৰ্যটনৰ বৃদ্ধি পাইছে ।
--------------------------------------------------

Translating ASM:  64%|██████████████▋        | 636/1000 [04:45<02:17,  2.64it/s]

[636/1000]
EN: Disney Destiny becomes marquee cruise debut of 2025.
ASM: ডিজনি ডেষ্টিনি ২০২৫ চনৰ মাৰকুই ক্ৰুজ ডেবিট হয় ।
--------------------------------------------------

Translating ASM:  64%|██████████████▋        | 637/1000 [04:45<02:21,  2.57it/s]

[637/1000]
EN: Norwegian Aqua adds fleet capacity to Norwegian Cruise Line.
ASM: নৰৱেজীয়ান আক্কাৱে নৰৱেজীয়ান ক্ৰুজ লাইনত ফ্লেট ক্ষমতা যোগ কৰিছে ।
--------------------------------------------------

Translating ASM:  64%|██████████████▋        | 638/1000 [04:46<02:18,  2.62it/s]

[638/1000]
EN: Royal Caribbean Star of the Seas enters service in 2025.
ASM: ৰয়েল কেৰিবিয়ান ষ্টাৰ অৱ দ্য চিজ ২০২৫ চনত সেৱা গ্ৰহণ কৰিব ।
--------------------------------------------------

Translating ASM:  64%|██████████████▋        | 639/1000 [04:46<02:14,  2.68it/s]

[639/1000]
EN: Cordelia Cruises announces Lakshadweep itineraries from Kochi.
ASM: কৰ্ডেলিয়া ক্ৰুইজে কোচীৰ পৰা লক্ষ্ধ্বীপ যাত্ৰাৰ কথা ঘোষণা কৰে ।
--------------------------------------------------

Translating ASM:  64%|██████████████▋        | 640/1000 [04:46<02:09,  2.77it/s]

[640/1000]
EN: Water metro connectivity boosts tourism in Kochi backwaters.
ASM: পানীৰ মেট্ৰোৰ সংযোগে কোচিৰ পিছপৰা পানীত পৰ্যটন বৃদ্ধি কৰে ।
--------------------------------------------------

Translating ASM:  64%|██████████████▋        | 641/1000 [04:47<02:16,  2.64it/s]

[641/1000]
EN: Mumbai cruise terminal handles record 100,000 passengers this year.
ASM: মুম্বাই ক্ৰুজ টাৰ্মিনেলটোৱে এই বছৰ অভিলেখ 100,000 যাত্ৰীৰ ব্যৱস্থা কৰে ।
--------------------------------------------------

Translating ASM:  64%|██████████████▊        | 642/1000 [04:47<02:13,  2.68it/s]

[642/1000]
EN: Ganga Vilas luxury cruise completes successful Brahmaputra season.
ASM: গংগা বিলাসী ক্ৰুজৰ সফল ব্ৰহ্মপুত্ৰ ঋতু সম্পূৰ্ণ হৈছে ।
--------------------------------------------------

Translating ASM:  64%|██████████████▊        | 643/1000 [04:47<02:14,  2.65it/s]

[643/1000]
EN: Kerala houseboat registrations cross one thousand operational vessels.
ASM: কেৰালাৰ হাউচবোট পঞ্জীয়ন এক হাজাৰ কাৰ্যকৰী জাহাজ অতিক্ৰম কৰে ।
--------------------------------------------------

Translating ASM:  64%|██████████████▊        | 644/1000 [04:48<02:12,  2.69it/s]

[644/1000]
EN: Andaman and Nicobar receive approval for international cruise tourism.
ASM: আন্দামান আৰু নিকোবৰ আন্তঃৰাষ্ট্ৰীয় ক্ৰুজ পৰ্যটনৰ বাবে অনুমোদন লাভ কৰিছে ।
--------------------------------------------------

Translating ASM:  64%|██████████████▊        | 645/1000 [04:48<02:04,  2.86it/s]

[645/1000]
EN: Airbnb relaunches experiences feature for bookings and services.
ASM: এয়াৰবিএনবিয়ে বুকিং আৰু সেৱাৰ বাবে অভিজ্ঞতা বৈশিষ্ট্য পুনৰ আৰম্ভ কৰে ।
--------------------------------------------------

Translating ASM:  65%|██████████████▊        | 646/1000 [04:48<02:06,  2.80it/s]

[646/1000]
EN: Brian Chesky announces Airbnb services complementing home rentals.
ASM: ব্ৰায়ান চেস্কিয়ে গৃহ ভাড়াৰ পৰিপূৰক এয়াৰবিএনবি সেৱা ঘোষণা কৰে ।
--------------------------------------------------

Translating ASM:  65%|██████████████▉        | 647/1000 [04:49<02:18,  2.55it/s]

[647/1000]
EN: Olympic speed skater Arianna Fontana leads Airbnb training rides.
ASM: অলিম্পিকৰ স্পিড স্কেটাৰ অৰিয়ানা ফণ্টানাই এয়াৰবিএনবিৰ প্ৰশিক্ষণ যাত্ৰাৰ নেতৃত্ব দিয়ে ।
--------------------------------------------------

Translating ASM:  65%|██████████████▉        | 648/1000 [04:49<02:21,  2.49it/s]

[648/1000]
EN: Airbnb offers Alpine hikes with athlete guides in Italy.
ASM: এয়াৰবিএনবিয়ে ইটালীত এথলীট গাইডৰ সৈতে আলপাইন হাইকিং অফাৰ কৰে ।
--------------------------------------------------

Translating ASM:  65%|██████████████▉        | 649/1000 [04:50<02:21,  2.47it/s]

[649/1000]
EN: K-pop band SEVENTEEN curates music sessions for Airbnb.
ASM: কে-পপ বেণ্ড ছেভেনিয়ে এয়াৰবিএনবিৰ বাবে সংগীত অধিবেশন কৰ্পৰেট কৰে ।
--------------------------------------------------

Translating ASM:  65%|██████████████▉        | 650/1000 [04:50<02:22,  2.46it/s]

[650/1000]
EN: Chance the Rapper partners with Airbnb for exclusive experiences.
ASM: একচেটিয়া অভিজ্ঞতাৰ বাবে ৰেপাৰ এয়াৰবিএনবিৰ সৈতে অংশীদাৰিত্ব কৰে ।
--------------------------------------------------

Translating ASM:  65%|██████████████▉        | 651/1000 [04:50<02:16,  2.55it/s]

[651/1000]
EN: Economic uncertainty shifts traveller behaviour toward price sensitivity.
ASM: অৰ্থনৈতিক অনিশ্চয়তাই ভ্ৰমণকাৰীৰ আচৰণ মূল্য সংবেদনশীলতাৰ দিশে স্থানান্তৰ কৰে ।
--------------------------------------------------

Translating ASM:  65%|██████████████▉        | 652/1000 [04:51<02:23,  2.42it/s]

[652/1000]
EN: Tourists choose off-the-beaten-path destinations influenced by social media.
ASM: পৰ্যটকসকলে ছচিয়েল মিডিয়াৰ প্ৰভাৱত পৰা পথৰ পৰা আঁতৰি থকা গন্তব্যস্থানবোৰ বাছনি কৰে ।
--------------------------------------------------

Translating ASM:  65%|███████████████        | 653/1000 [04:51<02:20,  2.46it/s]

[653/1000]
EN: Travelers turn to AI-powered tools for trip planning.
ASM: ভ্ৰমণ পৰিকল্পনাৰ বাবে ভ্ৰমণকাৰীসকলে এআই চালিত সঁজুলিৰ সন্ধান কৰে ।
--------------------------------------------------

Translating ASM:  65%|███████████████        | 654/1000 [04:52<02:11,  2.63it/s]

[654/1000]
EN: Sustainable tourism gains traction among mindful travellers.
ASM: বহনক্ষম পৰ্যটনে সচেতন ভ্ৰমণকাৰীসকলৰ মাজত আকৰ্ষণ লাভ কৰে ।
--------------------------------------------------

Translating ASM:  66%|███████████████        | 655/1000 [04:52<02:01,  2.83it/s]

[655/1000]
EN: Responsible travel interest grows among conscious tourists.
ASM: সচেতন পৰ্যটকসকলৰ মাজত দায়িত্বশীল ভ্ৰমণৰ আগ্ৰহ বৃদ্ধি পাইছে ।
--------------------------------------------------

Translating ASM:  66%|███████████████        | 656/1000 [04:52<02:14,  2.56it/s]

[656/1000]
EN: Less-crowded destinations attract visitors avoiding overtourism.
ASM: কম ভিৰ থকা গন্তব্যস্থলবোৰে অতিৰিক্ত পৰ্যটনৰ পৰা আঁতৰি থকা পৰ্যটকসকলক আকৰ্ষিত কৰে ।
--------------------------------------------------

Translating ASM:  66%|███████████████        | 657/1000 [04:53<02:12,  2.60it/s]

[657/1000]
EN: Business travel spending reaches 1.57 trillion dollars in 2025.
ASM: ব্যৱসায়িক ভ্ৰমণ ব্যয় ২০২৫ চনত ১.৫৭ ট্ৰিলিয়ন ডলাৰত উপনীত হ'ব ।
--------------------------------------------------

Translating ASM:  66%|███████████████▏       | 658/1000 [04:53<02:13,  2.57it/s]

[658/1000]
EN: Bleisure travel surge drives business trip extensions for leisure.
ASM: ব্লেচিউৰ ভ্ৰমণৰ বৃদ্ধিয়ে বিনোদনৰ বাবে ব্যৱসায়িক ভ্ৰমণৰ সম্প্ৰসাৰণ সাধন কৰে ।
--------------------------------------------------

Translating ASM:  66%|███████████████▏       | 659/1000 [04:54<02:12,  2.57it/s]

[659/1000]
EN: Luxury travel shifts toward immersive experience based vacations.
ASM: বিলাসী ভ্ৰমণে নিবিড় অভিজ্ঞতাৰ ওপৰত আধাৰিত ছুটীৰ দিশে স্থানান্তৰ কৰে ।
--------------------------------------------------

Translating ASM:  66%|███████████████▏       | 660/1000 [04:54<02:09,  2.63it/s]

[660/1000]
EN: Travvy Awards recognize top industry suppliers in November.
ASM: ট্ৰাভি বঁটা নৱেম্বৰত শীৰ্ষ উদ্যোগৰ যোগান ধৰাসকলক স্বীকৃতি দিয়ে ।
--------------------------------------------------

Translating ASM:  66%|███████████████▏       | 661/1000 [04:54<02:04,  2.73it/s]

[661/1000]
EN: TravelPulse announces 40 Under 40 honorees for second year.
ASM: ট্ৰেভেলপুলছে দ্বিতীয় বছৰৰ বাবে 40 40 তলৰ সন্মানীয়সকলক ঘোষণা কৰিছে ।
--------------------------------------------------

Translating ASM:  66%|███████████████▏       | 662/1000 [04:55<02:00,  2.81it/s]

[662/1000]
EN: Travel Executive of the Year awarded at Travvy gala.
ASM: ট্ৰাভি গেলাত বছৰৰ ট্ৰেভেল এক্সিকিউটিভ বঁটা প্ৰদান কৰা হয় ।
--------------------------------------------------

Translating ASM:  66%|███████████████▏       | 663/1000 [04:55<01:57,  2.86it/s]

[663/1000]
EN: New members inducted into Travel Hall of Fame 2025.
ASM: নতুন সদস্যসকলক ট্ৰেভেল হল অৱ ফেম ২০২৫ত সন্নিবিষ্ট কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  66%|███████████████▎       | 664/1000 [04:55<01:49,  3.07it/s]

[664/1000]
EN: Young professionals recognized for innovation and leadership.
ASM: উদ্ভাৱন আৰু নেতৃত্বৰ বাবে স্বীকৃত যুৱ বিশেষজ্ঞ ।
--------------------------------------------------

Translating ASM:  66%|███████████████▎       | 665/1000 [04:56<01:54,  2.94it/s]

[665/1000]
EN: FIFA World Cup 2025 travel bookings exceed host city expectations.
ASM: ফিফা বিশ্বকাপ ২০২৫ ভ্ৰমণ বুকিংয়ে আয়োজক চহৰৰ আশা অতিক্ৰম কৰিছে ।
--------------------------------------------------

Translating ASM:  67%|███████████████▎       | 666/1000 [04:56<01:52,  2.97it/s]

[666/1000]
EN: Solo female travel bookings increase forty percent year on year.
ASM: মহিলাৰ একক ভ্ৰমণ বুকিং বছৰে বছৰে চল্লিশ শতাংশ বৃদ্ধি পাইছে ।
--------------------------------------------------

Translating ASM:  67%|███████████████▎       | 667/1000 [04:56<02:01,  2.74it/s]

[667/1000]
EN: Wellness tourism emerges as fastest growing travel segment globally.
ASM: সুস্থতা পৰ্যটন বিশ্বব্যাপী আটাইতকৈ দ্ৰুতগতিত বিকশিত হোৱা ভ্ৰমণ খণ্ড হিচাপে উদীয়মান হৈছে ।
--------------------------------------------------

Translating ASM:  67%|███████████████▎       | 668/1000 [04:57<02:01,  2.73it/s]

[668/1000]
EN: Indian millennials prefer experiential travel over shopping vacations.
ASM: ভাৰতীয় সহস্ৰাব্দীসকলে শ্বপিং ছুটীত অভিজ্ঞতাৰ ভ্ৰমণ পছন্দ কৰে ।
--------------------------------------------------

Translating ASM:  67%|███████████████▍       | 669/1000 [04:57<02:06,  2.61it/s]

[669/1000]
EN: Workation packages gain popularity among remote corporate employees.
ASM: দূৰৱৰ্তী কৰ্পৰেট কৰ্মচাৰীসকলৰ মাজত ৱৰ্কেশ্যন পেকেজবোৰ জনপ্ৰিয়তা লাভ কৰে ।
--------------------------------------------------

Translating ASM:  67%|███████████████▍       | 670/1000 [04:57<02:04,  2.66it/s]

[670/1000]
EN: Culinary tourism drives foodies to regional Indian destinations.
ASM: ৰন্ধন পৰ্যটনে খাদ্যপ্ৰেমীসকলক আঞ্চলিক ভাৰতীয় গন্তব্যস্থানলৈ লৈ যায় ।
--------------------------------------------------

Translating ASM:  67%|███████████████▍       | 671/1000 [04:58<02:00,  2.72it/s]

[671/1000]
EN: Night tourism initiatives launched by Maharashtra and Karnataka.
ASM: মহাৰাষ্ট্ৰ আৰু কৰ্ণাটকৰ দ্বাৰা নিশা পৰ্যটন প্ৰচেষ্টা আৰম্ভ কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  67%|███████████████▍       | 672/1000 [04:58<02:03,  2.66it/s]

[672/1000]
EN: Astro tourism gains ground with dark sky parks in Ladakh.
ASM: লাডাখৰ ডাৰ্ক স্কাই পাৰ্কসমূহৰ সৈতে এষ্ট্ৰ ট্যুৰিজমে ভূমি লাভ কৰিছে ।
--------------------------------------------------

Translating ASM:  67%|███████████████▍       | 673/1000 [04:59<02:04,  2.63it/s]

[673/1000]
EN: Film induced tourism boosts Kashmir valley hotel occupancy.
ASM: চলচ্চিত্ৰ প্ৰেৰিত পৰ্যটনে কাশ্মীৰ উপত্যকাৰ হোটেল আৱাস বৃদ্ধি কৰে ।
--------------------------------------------------

Translating ASM:  67%|███████████████▌       | 674/1000 [04:59<01:57,  2.76it/s]

[674/1000]
EN: Wedding tourism contributes five billion dollars to Indian economy.
ASM: বিয়াৰ পৰ্যটনে ভাৰতীয় অৰ্থনীতিত পাঁচ বিলিয়ন ডলাৰ বৰঙণি আগবঢ়ায় ।
--------------------------------------------------

Translating ASM:  68%|███████████████▌       | 675/1000 [04:59<01:53,  2.86it/s]

[675/1000]
EN: India promotes MICE tourism for meetings and exhibitions.
ASM: বৈঠক আৰু প্ৰদৰ্শনীৰ বাবে ভাৰতে মাইচ পৰ্যটনক উৎসাহিত কৰে ।
--------------------------------------------------

Translating ASM:  68%|███████████████▌       | 676/1000 [05:00<01:55,  2.81it/s]

[676/1000]
EN: West Bengal develops MICE tourism segments under Mamata Banerjee.
ASM: মমতা বেনাৰ্জীৰ অধীনত পশ্চিমবংগত মাইচ পৰ্যটন খণ্ড বিকশিত হৈছে ।
--------------------------------------------------

Translating ASM:  68%|███████████████▌       | 677/1000 [05:00<01:48,  2.96it/s]

[677/1000]
EN: India positions itself as medical value travel destination.
ASM: ভাৰতে নিজকে চিকিৎসা মূল্যৰ ভ্ৰমণ গন্তব্যস্থান হিচাপে স্থিতি লৈছে ।
--------------------------------------------------

Translating ASM:  68%|███████████████▌       | 678/1000 [05:00<01:48,  2.98it/s]

[678/1000]
EN: Wellness tourism positions India as holistic healing leader.
ASM: সুস্থতা পৰ্যটনে ভাৰতক সামগ্ৰিক আৰোগ্য ক্ষেত্ৰত নেতৃত্ব প্ৰদান কৰিছে ।
--------------------------------------------------

Translating ASM:  68%|███████████████▌       | 679/1000 [05:01<01:54,  2.80it/s]

[679/1000]
EN: Concert tourism attracts international visitors to Indian music festivals.
ASM: কনচার্ট পৰ্যটনে ভাৰতীয় সংগীত উৎসৱলৈ আন্তৰ্জাতিক দৰ্শনাৰ্থীক আকৰ্ষিত কৰে ।
--------------------------------------------------

Translating ASM:  68%|███████████████▋       | 680/1000 [05:01<01:54,  2.79it/s]

[680/1000]
EN: Gajendra Shekhawat highlights India's concert tourism potential.
ASM: গজেন্দ্ৰ শইকীয়াই ভাৰতৰ সংগীত পৰ্যটনৰ সম্ভাৱনীয়তাৰ ওপৰত আলোকপাত কৰে ।
--------------------------------------------------

Translating ASM:  68%|███████████████▋       | 681/1000 [05:01<01:50,  2.88it/s]

[681/1000]
EN: India promotes integrated rehabilitation pathways for medical tourists.
ASM: ভাৰতে চিকিৎসা পৰ্যটকৰ বাবে সংহত পুনৰুদ্ধাৰ পথ প্ৰচাৰ কৰে ।
--------------------------------------------------

Translating ASM:  68%|███████████████▋       | 682/1000 [05:02<01:41,  3.13it/s]

[682/1000]
EN: Business travel makes significant comeback post pandemic.
ASM: ব্যৱসায়িক ভ্ৰমণে মহামাৰীৰ পিছত গুৰুত্বপূৰ্ণ প্ৰত্যাৱৰ্তন কৰে ।
--------------------------------------------------

Translating ASM:  68%|███████████████▋       | 683/1000 [05:02<01:45,  3.02it/s]

[683/1000]
EN: Companies increase trip volumes and expand travel budgets.
ASM: কোম্পানীসমূহে ভ্ৰমণৰ পৰিমাণ বৃদ্ধি কৰে আৰু ভ্ৰমণৰ বাজেট সম্প্ৰসাৰিত কৰে ।
--------------------------------------------------

Translating ASM:  68%|███████████████▋       | 684/1000 [05:02<01:44,  3.01it/s]

[684/1000]
EN: In-person collaboration demand drives business travel recovery.
ASM: ব্যক্তিগত সহযোগিতাৰ চাহিদাই ব্যৱসায়িক ভ্ৰমণৰ পুনৰুদ্ধাৰ ঘটাব ।
--------------------------------------------------

Translating ASM:  68%|███████████████▊       | 685/1000 [05:03<01:47,  2.93it/s]

[685/1000]
EN: Hyderabad International Convention Centre hosts global pharmaceutical summit.
ASM: হায়দৰাবাদ আন্তঃৰাষ্ট্ৰীয় সন্মিলন কেন্দ্ৰই বিশ্ব ঔষধ সন্মিলনৰ আয়োজন কৰিছে ।
--------------------------------------------------

Translating ASM:  69%|███████████████▊       | 686/1000 [05:03<01:51,  2.82it/s]

[686/1000]
EN: Bharat Mandapam witnesses record MICE bookings for fiscal year.
ASM: ভাৰত মণ্ডপামে বিত্তীয় বৰ্ষৰ বাবে ৰেকৰ্ড এমআইচিএছ বুকিং প্ৰত্যক্ষ কৰে ।
--------------------------------------------------

Translating ASM:  69%|███████████████▊       | 687/1000 [05:03<01:53,  2.75it/s]

[687/1000]
EN: Medical tourism arrivals cross pre-Covid levels with six lakh visitors.
ASM: ছয় লাখ দৰ্শনাৰ্থীৰ সৈতে চিকিৎসা পৰ্যটনৰ আগমন পূৰ্ব-কোভিড স্তৰ অতিক্ৰম কৰিছে ।
--------------------------------------------------

Translating ASM:  69%|███████████████▊       | 688/1000 [05:04<01:59,  2.62it/s]

[688/1000]
EN: AYUSH wellness centres attract foreign tourists for traditional treatments.
ASM: পৰম্পৰাগত চিকিৎসাৰ বাবে আয়ুষ সুস্থতা কেন্দ্ৰসমূহে বিদেশী পৰ্যটকক আকৰ্ষিত কৰে ।
--------------------------------------------------

Translating ASM:  69%|███████████████▊       | 689/1000 [05:04<02:06,  2.47it/s]

[689/1000]
EN: Delhi NCR hotels report seventy percent occupancy from corporate travellers.
ASM: দিল্লী এনচিআৰ হোটেলবোৰে কৰ্পৰেট ভ্ৰমণকাৰীৰ পৰা সত্তৰ শতাংশ আৱাসৰ প্ৰতিবেদন দিছে ।
--------------------------------------------------

Translating ASM:  69%|███████████████▊       | 690/1000 [05:05<02:04,  2.48it/s]

[690/1000]
EN: Maha Kumbh infrastructure delivers long-term tourism economic benefits.
ASM: মহা কুম্ভ আন্তঃগাঁথনিয়ে দীৰ্ঘম্যাদী পৰ্যটনৰ অৰ্থনৈতিক লাভালাভ প্ৰদান কৰে ।
--------------------------------------------------

Translating ASM:  69%|███████████████▉       | 691/1000 [05:05<02:10,  2.37it/s]

[691/1000]
EN: Venice entry fee revenues fund city upkeep and travel management.
ASM: ভেনিচ প্ৰৱেশ মাচুলৰ ৰাজহ চহৰৰ ৰক্ষণাবেক্ষণ আৰু ভ্ৰমণ ব্যৱস্থাপনা পুঁজি যোগায় ।
--------------------------------------------------

Translating ASM:  69%|███████████████▉       | 692/1000 [05:06<02:11,  2.34it/s]

[692/1000]
EN: Critics question Venice day-tripper fee effectiveness for crowd control.
ASM: সমালোচকসকলে ভিৰ নিয়ন্ত্ৰণৰ বাবে ভেনিচ ডে ট্রিপাৰ ফি ফলপ্ৰসূতাৰ ওপৰত প্ৰশ্ন উত্থাপন কৰে ।
--------------------------------------------------

Translating ASM:  69%|███████████████▉       | 693/1000 [05:06<02:12,  2.32it/s]

[693/1000]
EN: Bulgaria joins Eurozone as twenty-first member on January 1 2026.
ASM: ২০২৬ চনৰ ১ জানুৱাৰীত বুলগেৰিয়া একৈশ সংখ্যক সদস্য হিচাপে য়ুৰোজোনত যোগদান কৰে ।
--------------------------------------------------

Translating ASM:  69%|███████████████▉       | 694/1000 [05:06<02:05,  2.44it/s]

[694/1000]
EN: Both Lev and Euro accepted in Bulgaria during January transition.
ASM: জানুৱাৰী পৰিৱৰ্তনৰ সময়ত বুলগেৰিয়াত লেভ আৰু য়ুৰো দুয়োখন গ্ৰহণ কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  70%|███████████████▉       | 695/1000 [05:07<02:16,  2.24it/s]

[695/1000]
EN: Lufthansa announces daily Frankfurt-Bengaluru flights starting March 2026.
ASM: লুফ্থানচাই ২০২৬ চনৰ মাৰ্চৰ পৰা দৈনিক ফ্ৰাংকফুৰ্ট-বেংগালুৰু বিমানৰ কথা ঘোষণা কৰে ।
--------------------------------------------------

Translating ASM:  70%|████████████████       | 696/1000 [05:07<02:06,  2.40it/s]

[696/1000]
EN: Alliance Air introduces direct flights from Delhi to Darbhanga.
ASM: এলায়েন্স এয়েৰে দিল্লীৰ পৰা দৰভঙ্গালৈ প্ৰত্যক্ষ বিমান সেৱা আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  70%|████████████████       | 697/1000 [05:08<02:08,  2.36it/s]

[697/1000]
EN: Emirates deploys A380 on Ahmedabad-Dubai route for winter season.
ASM: এমিৰেটেছে শীতকালৰ বাবে আহমেদাবাদ-দুবাই পথত এ৩৮০ মোতায়েন কৰিছে ।
--------------------------------------------------

Translating ASM:  70%|████████████████       | 698/1000 [05:08<02:04,  2.43it/s]

[698/1000]
EN: fly91 commences operations from Goa to Hyderabad and Pune.
ASM: ফ্লাই৯১ য়ে গোৱাৰ পৰা হায়দৰাবাদ আৰু পুনেলৈ যাত্ৰা আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  70%|████████████████       | 699/1000 [05:09<02:02,  2.47it/s]

[699/1000]
EN: British Airways resumes London-Chennai service after four-year hiatus.
ASM: চাৰি বছৰৰ বিৰতিৰ পিছত ব্ৰিটিছ এয়াৰৱেজে লণ্ডন-চেন্নাই সেৱা পুনৰ আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  70%|████████████████       | 700/1000 [05:09<02:05,  2.39it/s]

[700/1000]
EN: Go First employees protest outside NCLT over unpaid salaries.
ASM: বেচ নোপোৱা দৰমহাৰ বাবে এনচিএলটিৰ বাহিৰত গ ফাৰ্ষ্ট কৰ্মচাৰীৰ প্ৰতিবাদ ।
--------------------------------------------------

Translating ASM:  70%|████████████████       | 701/1000 [05:09<02:13,  2.25it/s]

[701/1000]
EN: Saudi carrier Flynas plans direct Riyadh-Lucknow operations by April.
ASM: ছৌডি কেৰিয়াৰ ফ্লাইনাছে এপ্ৰিলৰ ভিতৰত ৰিয়াদ-লুকনৌৰ পৰা প্ৰত্যক্ষ অভিযান চলোৱাৰ পৰিকল্পনা কৰিছে ।
--------------------------------------------------

Translating ASM:  70%|████████████████▏      | 702/1000 [05:10<02:08,  2.32it/s]

[702/1000]
EN: Flybig announces daily flights from Guwahati to Imphal and Agartala.
ASM: ফ্লাইবিগে গুৱাহাটীৰ পৰা ইম্ফল আৰু আগৰতলালৈ দৈনিক বিমান সেৱা আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  70%|████████████████▏      | 703/1000 [05:10<02:08,  2.32it/s]

[703/1000]
EN: Kolkata airport wins cleanest airport award in 15-25 million category.
ASM: ১৫-২৫ মিলিয়ন শ্ৰেণীত কলকাতা বিমানবন্দৰ আটাইতকৈ পৰিষ্কাৰ বিমানবন্দৰ বঁটা বিজয়ী ।
--------------------------------------------------

Translating ASM:  70%|████████████████▏      | 704/1000 [05:11<02:08,  2.31it/s]

[704/1000]
EN: Patna airport's new terminal to handle forty lakh passengers annually.
ASM: পাটনা বিমানবন্দৰৰ নতুন টাৰ্মিনেলটোৱে বছৰি চল্লিশ লাখ যাত্ৰীক সামৰি লব ।
--------------------------------------------------

Translating ASM:  70%|████████████████▏      | 705/1000 [05:11<02:09,  2.28it/s]

[705/1000]
EN: Fog forces thirty-two flight diversions at Chandigarh airport.
ASM: ধুমুহাই চণ্ডীগড় বিমানবন্দৰত ত্ৰিশখন বিমানৰ বিচলিতকৰণ ঘটায় ।
--------------------------------------------------

Translating ASM:  71%|████████████████▏      | 706/1000 [05:12<02:02,  2.40it/s]

[706/1000]
EN: Ethiopian Airlines considers Mumbai and Delhi as new African hub.
ASM: ইথিওপিয়ান এয়াৰলাইনছে মুম্বাই আৰু দিল্লীক নতুন আফ্ৰিকান কেন্দ্ৰ হিচাপে বিবেচনা কৰে ।
--------------------------------------------------

Translating ASM:  71%|████████████████▎      | 707/1000 [05:12<02:01,  2.41it/s]

[707/1000]
EN: IndiGo passenger dies aboard Delhi-Bengaluru flight mid-air.
ASM: দিল্লী-বেংগালুৰু বিমানৰ বিমানত ইণ্ডিগোৰ যাত্ৰীগৰাকীৰ মৃত্যু ।
--------------------------------------------------

Translating ASM:  71%|████████████████▎      | 708/1000 [05:12<01:59,  2.45it/s]

[708/1000]
EN: VietJet Air announces daily Hanoi-Ahmedabad service from December.
ASM: ভিয়েটজেট এয়ে ডিচেম্বৰৰ পৰা দৈনিক হনোই-আহমেদাবাদ সেৱা ঘোষণা কৰিছে ।
--------------------------------------------------

Translating ASM:  71%|████████████████▎      | 709/1000 [05:13<01:55,  2.52it/s]

[709/1000]
EN: Odisha government approves ten new tourism circuits for development.
ASM: ওড়িশা চৰকাৰে উন্নয়নৰ বাবে দহখন নতুন পৰ্যটন চক্ৰ অনুমোদন জনাইছে ।
--------------------------------------------------

Translating ASM:  71%|████████████████▎      | 710/1000 [05:13<01:53,  2.55it/s]

[710/1000]
EN: Madhya Pradesh unveils film tourism policy with 25 percent subsidy.
ASM: মধ্যপ্ৰদেশে ২৫ শতাংশ ৰাজসাহায্যৰে চলচিত্ৰ পৰ্যটন নীতি উন্মোচন কৰিছে ।
--------------------------------------------------

Translating ASM:  71%|████████████████▎      | 711/1000 [05:13<01:51,  2.60it/s]

[711/1000]
EN: Gujarat grants industry status to homestays and farmstays.
ASM: গুজৰাটে হোমষ্টাই আৰু ফাৰ্মষ্টাইক ঔদ্যোগিক স্থিতি প্ৰদান কৰে ।
--------------------------------------------------

Translating ASM:  71%|████████████████▍      | 712/1000 [05:14<01:51,  2.58it/s]

[712/1000]
EN: Himachal Pradesh caps tourist entry to Manali and Rohtang Pass.
ASM: হিমাচল প্ৰদেশে মানালী আৰু ৰোহটাং পাছলৈ পৰ্যটকৰ প্ৰৱেশ সীমাবদ্ধ কৰিছে ।
--------------------------------------------------

Translating ASM:  71%|████████████████▍      | 713/1000 [05:14<01:50,  2.59it/s]

[713/1000]
EN: Kerala launches responsible tourism mission for waste-free destinations.
ASM: কেৰালাই আৱৰ্জনামুক্ত গন্তব্যস্থানসমূহৰ বাবে দায়বদ্ধ পৰ্যটন অভিযান আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  71%|████████████████▍      | 714/1000 [05:15<01:55,  2.47it/s]

[714/1000]
EN: Australia removes minimum bank balance requirement for Indian student visas.
ASM: ভাৰতীয় শিক্ষাৰ্থী ভিছাৰ বাবে অষ্ট্ৰেলিয়াই ন্যূনতম বেংক অৱশিষ্টৰ প্ৰয়োজনীয়তা আঁতৰ কৰিছে ।
--------------------------------------------------

Translating ASM:  72%|████████████████▍      | 715/1000 [05:15<01:57,  2.42it/s]

[715/1000]
EN: UK introduces Electronic Travel Authorisation for Indian passport holders.
ASM: ব্ৰিটেইনে ভাৰতীয় পাছপোৰ্টধাৰীসকলৰ বাবে ইলেক্ট্ৰনিক ভ্ৰমণ অনুমোদন প্ৰৱৰ্তন কৰিছে ।
--------------------------------------------------

Translating ASM:  72%|████████████████▍      | 716/1000 [05:16<01:59,  2.37it/s]

[716/1000]
EN: Saudi Arabia extends stopover visa validity from four to ninety-six hours.
ASM: ছৌডি আৰবে ষ্টপঅভাৰ ভিছাৰ বৈধতা চাৰি বজাৰ পৰা ছব্বৈছঘণ্টালৈ বৃদ্ধি কৰিছে ।
--------------------------------------------------

Translating ASM:  72%|████████████████▍      | 717/1000 [05:16<01:54,  2.46it/s]

[717/1000]
EN: Malaysia grants thirty-day visa-free entry to Indian nationals till December.
ASM: মালয়েছিয়াই ভাৰতীয় নাগৰিকসকলক ডিচেম্বৰলৈকে ত্ৰিশ দিনৰ ভিছা মুক্ত প্ৰৱেশ প্ৰদান কৰিছে ।
--------------------------------------------------

Translating ASM:  72%|████████████████▌      | 718/1000 [05:16<01:55,  2.44it/s]

[718/1000]
EN: Thailand extends visa-free stay for Indians from thirty to sixty days.
ASM: থাইলেণ্ডে ভাৰতীয়সকলৰ বাবে ভিছামুক্ত ভ্ৰমণ ত্ৰিশ দিনৰ পৰা ষাঠি দিনলৈ বৃদ্ধি কৰিছে ।
--------------------------------------------------

Translating ASM:  72%|████████████████▌      | 719/1000 [05:17<02:00,  2.33it/s]

[719/1000]
EN: Indonesia proposes visa-free entry for Indian tourists to boost Bali arrivals.
ASM: ইণ্ডোনেছিয়াই ভাৰতীয় পৰ্যটকৰ বাবে বালিৰ আগমন বৃদ্ধি কৰিবলৈ ভিছা মুক্ত প্ৰৱেশৰ প্ৰস্তাৱ দিছে ।
--------------------------------------------------

Translating ASM:  72%|████████████████▌      | 720/1000 [05:17<02:12,  2.12it/s]

[720/1000]
EN: European Parliament approves ETIAS system launch for mid-2026.
ASM: ইউৰোপীয় সংসদে ২০২৬ চনৰ মাজভাগলৈ ইটিআইএএএছ প্ৰণালীৰ শুভাৰম্ভক অনুমোদন জনাইছে ।
--------------------------------------------------

Translating ASM:  72%|████████████████▌      | 721/1000 [05:18<02:10,  2.13it/s]

[721/1000]
EN: Sri Lanka cabinet approves visa-free entry for nationals of thirty-five countries.
ASM: শ্ৰীলংকাৰ কেবিনেটে পঁয়ত্ৰিশখন দেশৰ নাগৰিকসকলৰ বাবে ভিছা মুক্ত প্ৰৱেশত অনুমোদন জনাইছে ।
--------------------------------------------------

Translating ASM:  72%|████████████████▌      | 722/1000 [05:18<02:00,  2.32it/s]

[722/1000]
EN: Waives visa fees for Indian senior citizens above sixty-five years.
ASM: ৬৫ বছৰৰ ওপৰৰ ভাৰতীয় জ্যেষ্ঠ নাগৰিকসকলৰ বাবে ভিছা মাচুল আঁতৰ কৰে ।
--------------------------------------------------

Translating ASM:  72%|████████████████▋      | 723/1000 [05:19<01:51,  2.49it/s]

[723/1000]
EN: Bhutan revises Sustainable Development Fee to one thousand two hundred rupees.
ASM: ভূটানে বহনক্ষম উন্নয়ন মাচুল এক হাজাৰ দুশ টকালৈ সংশোধন কৰে ।
--------------------------------------------------

Translating ASM:  72%|████████████████▋      | 724/1000 [05:19<01:51,  2.47it/s]

[724/1000]
EN: Nepal allows Indian tourists to pay in rupees at immigration checkpoints.
ASM: নেপালত ভাৰতীয় পৰ্যটকসকলে ইমিগ্ৰেচন চেকপইণ্টত টকা পৰিশোধ কৰিবলৈ অনুমতি দিয়ে ।
--------------------------------------------------

Translating ASM:  72%|████████████████▋      | 725/1000 [05:19<01:49,  2.52it/s]

[725/1000]
EN: Myanmar junta extends e-visa facility for Indian travellers.
ASM: ম্যানমাৰৰ জণ্টাই ভাৰতীয় ভ্ৰমণকাৰীৰ বাবে ই-ভিছা সুবিধা সম্প্ৰসাৰিত কৰিছে ।
--------------------------------------------------

Translating ASM:  73%|████████████████▋      | 726/1000 [05:20<01:52,  2.44it/s]

[726/1000]
EN: Mauritius scraps PCR test requirement for fully vaccinated Indian visitors.
ASM: মৰিছাছে সম্পূৰ্ণৰূপে টিকাকৰণ কৰা ভাৰতীয় দৰ্শনাৰ্থীৰ বাবে পিচিআৰ পৰীক্ষাৰ প্ৰয়োজনীয়তা বাতিল কৰিছে ।
--------------------------------------------------

Translating ASM:  73%|████████████████▋      | 727/1000 [05:20<01:49,  2.49it/s]

[727/1000]
EN: Kenya removes visa requirement for all Indian passport holders.
ASM: কেনিয়াই সকলো ভাৰতীয় পাছপোৰ্টধাৰীসকলৰ বাবে ভিছাৰ প্ৰয়োজনীয়তা আঁতৰ কৰে ।
--------------------------------------------------

Translating ASM:  73%|████████████████▋      | 728/1000 [05:20<01:44,  2.60it/s]

[728/1000]
EN: Rajasthan government launches mobile app for heritage hotel bookings.
ASM: ৰাজস্থান চৰকাৰে ঐতিহ্যবাহী হোটেলৰ বুকিংৰ বাবে ম'বাইল এপ মুকলি কৰিছে ।
--------------------------------------------------

Translating ASM:  73%|████████████████▊      | 729/1000 [05:21<01:41,  2.67it/s]

[729/1000]
EN: Assam receives fifty-five lakh domestic tourists during 2024-2025.
ASM: ২০২৪-২০২৫ বৰ্ষত অসমত ৫৫ লাখ দেশীয় পৰ্যটক আহে ।
--------------------------------------------------

Translating ASM:  73%|████████████████▊      | 730/1000 [05:21<01:43,  2.62it/s]

[730/1000]
EN: Hemanta Biswa Sarma credits improved law and order for tourism growth.
ASM: হেমন্ত বিশ্বাস সৰ্মা ক্ৰেডিটে পৰ্যটনৰ বিকাশৰ বাবে আইন শৃংখলা উন্নত কৰিছিল ।
--------------------------------------------------

Translating ASM:  73%|████████████████▊      | 731/1000 [05:22<01:41,  2.64it/s]

[731/1000]
EN: Madhya Pradesh records 112.1 million tourist visits in 2024.
ASM: মধ্য প্ৰদেশে ২০২৪ চনত ১১২.১ মিলিয়ন পৰ্যটক দৰ্শন ৰেকৰ্ড কৰিছে ।
--------------------------------------------------

Translating ASM:  73%|████████████████▊      | 732/1000 [05:22<01:38,  2.71it/s]

[732/1000]
EN: Meghalaya welcomes twenty-one lakh visitors crossing pre-pandemic figures.
ASM: মেঘালয়ত একৈশ লাখ দৰ্শনাৰ্থীয়ে প্ৰাক মহামাৰীৰ সংখ্যা অতিক্ৰম কৰিছে ।
--------------------------------------------------

Translating ASM:  73%|████████████████▊      | 733/1000 [05:22<01:38,  2.71it/s]

[733/1000]
EN: Jammu and Kashmir registers two crore tourist footfall in 2025.
ASM: ২০২৫ চনত জম্মু আৰু কাশ্মীৰত দুকোটি পৰ্যটকৰ ভ্ৰমণ আছে ।
--------------------------------------------------

Translating ASM:  73%|████████████████▉      | 734/1000 [05:23<01:45,  2.53it/s]

[734/1000]
EN: LG Manoj Sinha announces highest ever tourist arrival in Kashmir Valley.
ASM: এল জি মনোজ সিনহাই কাশ্মীৰ উপত্যকাত এতিয়ালৈকে সৰ্বাধিক পৰ্যটক আগমনৰ ঘোষণা কৰিছে ।
--------------------------------------------------

Translating ASM:  74%|████████████████▉      | 735/1000 [05:23<01:42,  2.59it/s]

[735/1000]
EN: Lakshadweep receives eighty-three thousand visitors after PM Modi visit.
ASM: প্ৰধানমন্ত্ৰী মোডীৰ ভ্ৰমণৰ পিছত লক্ষদ্বীপে ৮৩ হাজাৰ দৰ্শনাৰ্থীক গ্ৰহণ কৰিছে ।
--------------------------------------------------

Translating ASM:  74%|████████████████▉      | 736/1000 [05:24<01:42,  2.57it/s]

[736/1000]
EN: Uttarakhand witnesses five crore pilgrim visits to Char Dham shrines.
ASM: উত্তৰাখণ্ডত পাঁচ কোটি তীৰ্থযাত্ৰীয়ে চাৰ ধাম মন্দিৰ দৰ্শন কৰে ।
--------------------------------------------------

Translating ASM:  74%|████████████████▉      | 737/1000 [05:24<01:43,  2.54it/s]

[737/1000]
EN: Pushkar fair attracts fifteen lakh tourists including thirty thousand foreigners.
ASM: পুষ্কাৰ মেলাত ত্ৰিশ হাজাৰ বিদেশীকে ধৰি পোন্ধৰ লাখ পৰ্যটক আকৰ্ষিত হয় ।
--------------------------------------------------

Translating ASM:  74%|████████████████▉      | 738/1000 [05:24<01:50,  2.37it/s]

[738/1000]
EN: Surajkund Mela records forty-eight percent increase in international participation.
ASM: সূৰ্যকুণ্ড মেলাত আন্তঃৰাষ্ট্ৰীয় অংশগ্ৰহণত আঠচল্লিশ শতাংশ বৃদ্ধিৰ ৰেকৰ্ড আছে ।
--------------------------------------------------

Translating ASM:  74%|████████████████▉      | 739/1000 [05:25<01:51,  2.34it/s]

[739/1000]
EN: Singapore welcomes 1.2 million Indian visitors becoming top source market.
ASM: ছিংগাপুৰে ১.২ মিলিয়ন ভাৰতীয় দৰ্শনাৰ্থীক শীৰ্ষ উত্স বজাৰ হিচাপে স্বাগতম জনাইছে ।
--------------------------------------------------

Translating ASM:  74%|█████████████████      | 740/1000 [05:25<01:52,  2.32it/s]

[740/1000]
EN: Dubai hosts record 2.1 million Indian tourists in first half 2025.
ASM: দুবাইয়ে ২০২৫ চনৰ প্ৰথমাৰ্ধত ৰেকৰ্ড ২.১ মিলিয়ন ভাৰতীয় পৰ্যটকক আয়োজিত কৰে ।
--------------------------------------------------

Translating ASM:  74%|█████████████████      | 741/1000 [05:26<01:53,  2.28it/s]

[741/1000]
EN: Thailand receives 1.8 million Indian travellers during January-October period.
ASM: থাইলেণ্ডে জানুৱাৰী-অক্টোবৰৰ সময়ছোৱাত ১.৮ নিযুত ভাৰতীয় ভ্ৰমণকাৰীক গ্ৰহণ কৰে ।
--------------------------------------------------

Translating ASM:  74%|█████████████████      | 742/1000 [05:26<01:51,  2.31it/s]

[742/1000]
EN: Maldives sees forty percent drop in Indian tourist arrivals amid diplomatic row.
ASM: কূটনৈতিক বিবাদৰ মাজত মালদ্বীপে ভাৰতীয় পৰ্যটকৰ আগমনত চল্লিশ শতাংশ হ্ৰাস পাইছে ।
--------------------------------------------------

Translating ASM:  74%|█████████████████      | 743/1000 [05:27<01:48,  2.38it/s]

[743/1000]
EN: Nepal earns 110 billion rupees from Indian tourists in fiscal year.
ASM: বিত্তীয় বৰ্ষত নেপালে ভাৰতীয় পৰ্যটকৰ পৰা ১১০ বিলিয়ন টকা উপাৰ্জন কৰে ।
--------------------------------------------------

Translating ASM:  74%|█████████████████      | 744/1000 [05:27<01:46,  2.41it/s]

[744/1000]
EN: Turkey welcomes three lakh Indian tourists targeting five lakh by year-end.
ASM: তুৰ্কীয়ে বছৰৰ শেষৰফালে পাঁচ লাখ টকাৰ লক্ষ্যৰে তিনি লাখ ভাৰতীয় পৰ্যটকক আদৰণি জনাইছে ।
--------------------------------------------------

Translating ASM:  74%|█████████████████▏     | 745/1000 [05:27<01:39,  2.57it/s]

[745/1000]
EN: Egypt reports 1.5 lakh Indian arrivals aiming for three lakh target.
ASM: ইজিপ্তে তিনি লাখ লক্ষ্যৰে ১.৫ লাখ ভাৰতীয় আগমনৰ প্ৰতিবেদন দিছে ।
--------------------------------------------------

Translating ASM:  75%|█████████████████▏     | 746/1000 [05:28<01:39,  2.54it/s]

[746/1000]
EN: Azerbaijan attracts two lakh Indian visitors visa-free policy credited.
ASM: আজাৰবাইজানে দুই লাখ ভাৰতীয় পৰ্যটকক ভিছা মুক্ত নীতিৰ বাবে আকৰ্ষিত কৰে ।
--------------------------------------------------

Translating ASM:  75%|█████████████████▏     | 747/1000 [05:28<01:45,  2.40it/s]

[747/1000]
EN: Georgia registers 1.75 lakh Indian tourist arrivals between January-September.
ASM: জৰ্জিয়াই জানুৱাৰী-ছেপ্তেম্বৰ মাহৰ ভিতৰত ১.৭৫ লাখ ভাৰতীয় পৰ্যটক আগমন পঞ্জীয়ন কৰে ।
--------------------------------------------------

Translating ASM:  75%|█████████████████▏     | 748/1000 [05:29<01:41,  2.49it/s]

[748/1000]
EN: Kenya targets one lakh Indian tourists with aggressive marketing campaign.
ASM: কেনিয়াই এক লাখ ভাৰতীয় পৰ্যটকক আক্ৰমণাত্মক বিপণন অভিযানৰ লক্ষ্য কৰি লৈছে ।
--------------------------------------------------

Translating ASM:  75%|█████████████████▏     | 749/1000 [05:29<01:39,  2.52it/s]

[749/1000]
EN: Udaipur airport gets new terminal building costing five hundred crore rupees.
ASM: উদয়পুৰ বিমানবন্দৰত পাঁচশ কোটি টকাৰ নতুন টাৰ্মিনেল ভৱন নিৰ্মাণ কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  75%|█████████████████▎     | 750/1000 [05:29<01:37,  2.57it/s]

[750/1000]
EN: Rajkot airport renamed after former Prime Minister Morarji Desai.
ASM: ৰাজকোট বিমানবন্দৰৰ নাম প্ৰাক্তন প্ৰধানমন্ত্ৰী মৰাৰজী দেশাইৰ নামত ৰখা হৈছে ।
--------------------------------------------------

Translating ASM:  75%|█████████████████▎     | 751/1000 [05:30<01:37,  2.55it/s]

[751/1000]
EN: Noida International Airport to begin flight operations by April 2026.
ASM: ২০২৬ চনৰ এপ্ৰিল মাহৰ ভিতৰত নয়ডা আন্তঃৰাষ্ট্ৰীয় বিমানবন্দৰৰ বিমান চলাচল আৰম্ভ হব ।
--------------------------------------------------

Translating ASM:  75%|█████████████████▎     | 752/1000 [05:30<01:34,  2.64it/s]

[752/1000]
EN: Chennai airport opens dedicated lounge for transiting international passengers.
ASM: চেন্নাই বিমানবন্দৰে আন্তঃৰাষ্ট্ৰীয় যাত্ৰীসকলৰ বাবে বিশেষ লাউজ মুকলি কৰিছে ।
--------------------------------------------------

Translating ASM:  75%|█████████████████▎     | 753/1000 [05:31<01:40,  2.45it/s]

[753/1000]
EN: Guwahati-Rohingya railway project completes tunneling work in Mizoram.
ASM: গুৱাহাটী-ৰোহিংগীয়া ৰেল প্ৰকল্পই মিজোৰামত সুৰংগ নিৰ্মাণৰ কাম সম্পূৰ্ণ কৰিছে ।
--------------------------------------------------

Translating ASM:  75%|█████████████████▎     | 754/1000 [05:31<01:44,  2.36it/s]

[754/1000]
EN: Katra-Delhi Vande Bharat Express reduces travel time by three hours.
ASM: কাট্ৰা-দিল্লি বান্দী ভাৰত এক্সপ্ৰেছে ভ্ৰমণৰ সময় তিনি ঘণ্টা হ্ৰাস কৰিছে ।
--------------------------------------------------

Translating ASM:  76%|█████████████████▎     | 755/1000 [05:31<01:37,  2.52it/s]

[755/1000]
EN: Mumbai-Ahmedabad bullet train project completes fifty percent of viaduct work.
ASM: মুম্বাই-আহমেদাবাদ বুলেট ট্ৰেইন প্ৰকল্পত ৫০ শতাংশ কাম সম্পূৰ্ণ হৈছে ।
--------------------------------------------------

Translating ASM:  76%|█████████████████▍     | 756/1000 [05:32<01:41,  2.40it/s]

[756/1000]
EN: Indian Railways introduces 200 superfast trains for summer rush.
ASM: ভাৰতীয় ৰেলৱে গ্ৰীষ্মকালীন ব্যস্ততাৰ বাবে ২০০টা চুপাৰফাষ্ট ৰেল মুকলি কৰিছে ।
--------------------------------------------------

Translating ASM:  76%|█████████████████▍     | 757/1000 [05:32<01:41,  2.39it/s]

[757/1000]
EN: Kochi water metro adds four new routes connecting Vypin and Goshree islands.
ASM: কোচি ৱাটাৰ মেট্ৰোৱে ভাইপিন আৰু গোশ্ৰী দ্বীপপুঞ্জক সংযোগ কৰা চাৰিটা নতুন পথ যোগ কৰিছে ।
--------------------------------------------------

Translating ASM:  76%|█████████████████▍     | 758/1000 [05:33<01:37,  2.49it/s]

[758/1000]
EN: Ayodhya's Ram Path revamp completed ahead of Pran Pratishtha anniversary.
ASM: প্ৰাণপ্ৰতিষ্ঠা বৰ্ষপূৰ্তিৰ পূৰ্বেই অযোধ্যাৰ ৰাম পথৰ সংস্কাৰ সম্পূৰ্ণ ।
--------------------------------------------------

Translating ASM:  76%|█████████████████▍     | 759/1000 [05:33<01:34,  2.55it/s]

[759/1000]
EN: Kedarnath ropeway project gets environmental clearance from ministry.
ASM: কেডাৰনাথ ৰোপৱে প্ৰকল্পটো মন্ত্ৰালয়ৰ পৰা পৰিৱেশ অনুমোদন লাভ কৰে ।
--------------------------------------------------

Translating ASM:  76%|█████████████████▍     | 760/1000 [05:33<01:32,  2.59it/s]

[760/1000]
EN: Hemkund Sahib helicopter service fares capped at five thousand rupees.
ASM: হেমকুণ্ড চাহিব হেলিকপ্টাৰ সেৱাৰ ভাড়া পাঁচ হাজাৰ টকালৈ বৃদ্ধি কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  76%|█████████████████▌     | 761/1000 [05:34<01:29,  2.67it/s]

[761/1000]
EN: Statue of Unity adds laser show and sound and light attraction.
ASM: ষ্টেচু অৱ ইউনিটীয়ে লেজাৰ শো আৰু শব্দ আৰু পোহৰৰ আকৰ্ষণ যোগ কৰে ।
--------------------------------------------------

Translating ASM:  76%|█████████████████▌     | 762/1000 [05:34<01:33,  2.56it/s]

[762/1000]
EN: Khajuraho airport receives international status for charter operations.
ASM: খাজুৰাহো বিমানবন্দৰে চাৰ্টাৰ অপাৰেশ্বনৰ বাবে আন্তঃৰাষ্ট্ৰীয় স্থিতি লাভ কৰে ।
--------------------------------------------------

Translating ASM:  76%|█████████████████▌     | 763/1000 [05:35<01:37,  2.44it/s]

[763/1000]
EN: Puducherry tourism department renovates French War Memorial promenade.
ASM: পুডুচেৰী পৰ্যটন বিভাগে ফ্ৰান্স ৱাৰ মেমৰিয়েল প্ৰমেনেড নৱনিৰ্মাণ কৰিছে ।
--------------------------------------------------

Translating ASM:  76%|█████████████████▌     | 764/1000 [05:35<01:37,  2.42it/s]

[764/1000]
EN: Dal Lake restoration project includes de-weeding and island development.
ASM: দাল হ্ৰদৰ পুনঃনিৰ্মাণ প্ৰকল্পত ডী ৱেইডিং আৰু দ্বীপ উন্নয়ন অন্তৰ্ভুক্ত আছে ।
--------------------------------------------------

Translating ASM:  76%|█████████████████▌     | 765/1000 [05:35<01:32,  2.54it/s]

[765/1000]
EN: Hampi gets world-class interpretation centre showcasing Vijayanagara heritage.
ASM: বিজয়নাগৰ ঐতিহ্য প্ৰদৰ্শন কৰা বিশ্বমানৰ ব্যাখ্যা কেন্দ্ৰ হাম্পি লাভ কৰে ।
--------------------------------------------------

Translating ASM:  77%|█████████████████▌     | 766/1000 [05:36<01:37,  2.39it/s]

[766/1000]
EN: Mahabalipuram shoreline monument gets LED lighting for night viewing.
ASM: মহাবলিপুৰম উপকূলীয় স্মৃতিসৌধত নিশা দৰ্শন কৰাৰ বাবে এলইডি লাইটিং পোৱা যায় ।
--------------------------------------------------

Translating ASM:  77%|█████████████████▋     | 767/1000 [05:36<01:41,  2.31it/s]

[767/1000]
EN: Ajanta-Ellora caves introduce audio guides in ten international languages.
ASM: অজন্তা-ইল্লোৰা গুহাত দহটা আন্তঃৰাষ্ট্ৰীয় ভাষাত অডিঅ গাইডবোৰ প্ৰচলিত হয় ।
--------------------------------------------------

Translating ASM:  77%|█████████████████▋     | 768/1000 [05:37<01:33,  2.48it/s]

[768/1000]
EN: Kaziranga opens additional safari routes for tourists.
ASM: কাজিৰঙাই পৰ্যটকৰ বাবে অতিৰিক্ত চাফাৰী পথ মুকলি কৰে ।
--------------------------------------------------

Translating ASM:  77%|█████████████████▋     | 769/1000 [05:37<01:35,  2.41it/s]

[769/1000]
EN: Radisson Blu opens two hundred key property in Amritsar near Golden Temple.
ASM: ৰ্যাডিছন ব্লুৱে সোণালী মন্দিৰৰ কাষত অমৃতসৰত দুশটা মূল সম্পত্তি মুকলি কৰে ।
--------------------------------------------------

Translating ASM:  77%|█████████████████▋     | 770/1000 [05:38<01:38,  2.33it/s]

[770/1000]
EN: IHCL launches Ginger brand hotel in Siliguri for Dooars travellers.
ASM: আইএইচচিএলে ডুৱাৰছ ভ্ৰমণকাৰীৰ বাবে শিলিগুৰিৰ জিঞ্জাৰ ব্ৰেণ্ড হোটেল মুকলি কৰে ।
--------------------------------------------------

Translating ASM:  77%|█████████████████▋     | 771/1000 [05:38<01:33,  2.45it/s]

[771/1000]
EN: Hyatt Regency debuts in Dehradun with mountain view rooms.
ASM: পাহাৰীয়া দৃশ্যৰ কক্ষৰ সৈতে হায়াট ৰিজেন্সি ডেৰাডুনত আত্মপ্ৰকাশ কৰিছে ।
--------------------------------------------------

Translating ASM:  77%|█████████████████▊     | 772/1000 [05:38<01:29,  2.56it/s]

[772/1000]
EN: Taj Fort Aguada completes fifty years in Goa announces renovation.
ASM: গোৱাত তাজ দুৰ্গ আগুড়াই পঞ্চাশ বছৰ সম্পূৰ্ণ কৰিলে সংস্কাৰৰ ঘোষণা ।
--------------------------------------------------

Translating ASM:  77%|█████████████████▊     | 773/1000 [05:39<01:36,  2.35it/s]

[773/1000]
EN: Novotel Visakhapatnam opens with three sixty degree sea view rooms.
ASM: তিনিটা ষাঠি ডিগ্ৰী সমুদ্ৰ দৰ্শন কক্ষৰ সৈতে নভোটেল বিশাখাপট্টনম খোলা হয় ।
--------------------------------------------------

Translating ASM:  77%|█████████████████▊     | 774/1000 [05:39<01:34,  2.38it/s]

[774/1000]
EN: Roseate House Delhi appoints Kunal Kumar as new general manager.
ASM: ৰজেইট হাউচ দিল্লীয়ে নতুন জেনেৰেল মেনেজাৰ হিচাপে নিয়োগ কৰিলে কুনাল কুমাৰক ।
--------------------------------------------------

Translating ASM:  78%|█████████████████▊     | 775/1000 [05:40<01:32,  2.43it/s]

[775/1000]
EN: ITC Hotels launches Mementoes brand with Jaipur property opening.
ASM: আইটিচি হোটেলসমূহে জয়পুৰ সম্পত্তি উদ্বোধনৰ সৈতে স্মাৰক ব্ৰেণ্ড মুকলি কৰে ।
--------------------------------------------------

Translating ASM:  78%|█████████████████▊     | 776/1000 [05:40<01:32,  2.41it/s]

[776/1000]
EN: Marriott Kathmandu opens Indian restaurant specializing in Awadhi cuisine.
ASM: মাৰিয়ট কাঠমাণ্ডুৱে আৱোধী ৰন্ধনপ্ৰণালীত বিশেষজ্ঞ ভাৰতীয় ৰেষ্টুৰেণ্ট মুকলি কৰে ।
--------------------------------------------------

Translating ASM:  78%|█████████████████▊     | 777/1000 [05:40<01:34,  2.35it/s]

[777/1000]
EN: Sarovar Hotels signs new property in Darjeeling with heritage status.
ASM: চাৰোভাৰ হোটেলসমূহে ঐতিহ্যমণ্ডিত দাৰ্জিলিংত নতুন সম্পত্তিৰ স্বাক্ষৰ কৰিছে ।
--------------------------------------------------

Translating ASM:  78%|█████████████████▉     | 778/1000 [05:41<01:35,  2.33it/s]

[778/1000]
EN: The Park Kolkata celebrates seventy-fifth anniversary with heritage walks.
ASM: কলিকতাৰ উদ্যানখনত ঐতিহ্যমণ্ডিত পদযাত্ৰাৰে ৭৫সংখ্যক বৰ্ষপূৰ্তি উদযাপন কৰা হয় ।
--------------------------------------------------

Translating ASM:  78%|█████████████████▉     | 779/1000 [05:41<01:34,  2.34it/s]

[779/1000]
EN: Ambassador Ajmera joins Indian Hotel Company board as independent director.
ASM: ভাৰতীয় হোটেল কোম্পানীৰ বোৰ্ডত স্বতন্ত্ৰ সঞ্চালক হিচাপে যোগদান কৰিলে ৰাষ্ট্ৰদূত আজমিৰাই ।
--------------------------------------------------

Translating ASM:  78%|█████████████████▉     | 780/1000 [05:42<01:32,  2.39it/s]

[780/1000]
EN: Chai Sutta Bar founder Anubhav Dubey opens tourist cafe in Udaipur.
ASM: চাই সূতা বাৰ প্ৰতিষ্ঠাপক অনুভৱ দুবেই উদয়পুৰত মুকলি কৰিলে পৰ্যটন কেফে ।
--------------------------------------------------

Translating ASM:  78%|█████████████████▉     | 781/1000 [05:42<01:24,  2.59it/s]

[781/1000]
EN: Aman Resorts to launch first Indian property in Alwar district.
ASM: আলৱাৰ জিলাত প্ৰথম ভাৰতীয় সম্পত্তি মুকলি কৰিব আমান ৰিজৰ্টে ।
--------------------------------------------------

Translating ASM:  78%|█████████████████▉     | 782/1000 [05:42<01:26,  2.51it/s]

[782/1000]
EN: Soneva Fushi Maldives introduces all-inclusive plan for Indian honeymooners.
ASM: সোণভা ফুছি মালদ্বীপে ভাৰতীয় মধুচন্দ্ৰযাত্ৰীসকলৰ বাবে সৰ্বব্যাপী পৰিকল্পনা প্ৰৱৰ্তন কৰিছে ।
--------------------------------------------------

Translating ASM:  78%|██████████████████     | 783/1000 [05:43<01:30,  2.41it/s]

[783/1000]
EN: CII tourism committee chairman K.B. Kachru calls for single window clearance.
ASM: চিআইআই পৰ্যটন সমিতিৰ অধ্যক্ষ কে.বি. কাচ্চুৱে একক উইণ্ড ক্লিয়াৰেন্সৰ আহ্বান জনাইছে ।
--------------------------------------------------

Translating ASM:  78%|██████████████████     | 784/1000 [05:43<01:32,  2.33it/s]

[784/1000]
EN: Ladakh bans motorbike rallies to protect fragile Himalayan ecosystem.
ASM: লাডাখত সংবেদনশীল হিমালয়ান পৰিবেশ ব্যৱস্থাক সুৰক্ষিত কৰিবলৈ মটৰচাইকেল ৰেলী নিষিদ্ধ কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  78%|██████████████████     | 785/1000 [05:44<01:27,  2.45it/s]

[785/1000]
EN: Meghalaya introduces living root bridge trekking festival in November.
ASM: মেঘালয়ত নৱেম্বৰত লাইভ ৰাট ব্ৰিজ ট্ৰেকিং উৎসৱ আৰম্ভ কৰা হয় ।
--------------------------------------------------

Translating ASM:  79%|██████████████████     | 786/1000 [05:44<01:23,  2.56it/s]

[786/1000]
EN: Spiti valley opens for tourists after six-month winter closure.
ASM: ছয় মাহৰ শীতকালীন বন্ধৰ পিছত স্পিটি উপত্যকা পৰ্যটকৰ বাবে মুকলি হয় ।
--------------------------------------------------

Translating ASM:  79%|██████████████████     | 787/1000 [05:44<01:18,  2.70it/s]

[787/1000]
EN: Andaman administration permits night camping on Neil Island.
ASM: আন্দামান প্ৰশাসনে নীল দ্বীপত নিশা শিবিৰ ৰখাৰ অনুমতি দিছে ।
--------------------------------------------------

Translating ASM:  79%|██████████████████     | 788/1000 [05:45<01:16,  2.78it/s]

[788/1000]
EN: Gujarat forest department opens Gir interpretation zone for lion safaris.
ASM: গুজৰাট বন বিভাগে সিংহ চাফাৰীৰ বাবে গিৰ ব্যাখ্যা অঞ্চল মুকলি কৰিছে ।
--------------------------------------------------

Translating ASM:  79%|██████████████████▏    | 789/1000 [05:45<01:22,  2.54it/s]

[789/1000]
EN: Jim Corbett tiger reserve reports 1.75 lakh tourists in peak season.
ASM: জিম কৰ্বেট টাইগাৰ ৰিজাৰ্ভে শিখৰ ঋতুত ১.৭৫ লাখ পৰ্যটকক ৰিপৰ্ট কৰে ।
--------------------------------------------------

Translating ASM:  79%|██████████████████▏    | 790/1000 [05:46<01:22,  2.53it/s]

[790/1000]
EN: Periyar sanctuary introduces bamboo rafting in Thekkady lake.
ASM: পেৰিয়াৰ অভয়াৰণ্যে ঠেক্কাড়ী হ্ৰদত বাঁহৰ ৰফটিং প্ৰৱৰ্তন কৰে ।
--------------------------------------------------

Translating ASM:  79%|██████████████████▏    | 791/1000 [05:46<01:17,  2.68it/s]

[791/1000]
EN: Sundarbans tourism restricted during tiger breeding season.
ASM: বাঘ প্ৰজনন ঋতুত চুন্দাৰবানৰ পৰ্যটন সীমিত কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  79%|██████████████████▏    | 792/1000 [05:46<01:16,  2.73it/s]

[792/1000]
EN: Ranthambore bans private vehicles inside core zone from December.
ASM: ৰন্ধাম্বুৰত ডিচেম্বৰৰ পৰা মূল অঞ্চলৰ ভিতৰত ব্যক্তিগত বাহন নিষিদ্ধ কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  79%|██████████████████▏    | 793/1000 [05:47<01:18,  2.65it/s]

[793/1000]
EN: Kerala tourism launches monsoon packages for Ayurveda treatments.
ASM: কেৰালাৰ পৰ্যটনে আয়ুৰ্বেদিক চিকিৎসাৰ বাবে বাৰিষাৰ পেকেজ মুকলি কৰিছে ।
--------------------------------------------------

Translating ASM:  79%|██████████████████▎    | 794/1000 [05:47<01:18,  2.63it/s]

[794/1000]
EN: Kutch Rann Utsav extends tent city duration by forty-five days.
ASM: কচ্চ ৰান উটচৱে তম্বু চহৰৰ সময়কাল পঁয়ত্ৰিশ দিনলৈ বৃদ্ধি কৰিছে ।
--------------------------------------------------

Translating ASM:  80%|██████████████████▎    | 795/1000 [05:47<01:18,  2.62it/s]

[795/1000]
EN: Telangana government promotes Yadadri temple as integrated pilgrimage hub.
ASM: তেলেংগানা চৰকাৰে যাদড়ী মন্দিৰক এক সংহত তীৰ্থযাত্ৰা কেন্দ্ৰ হিচাপে প্ৰচাৰ কৰে ।
--------------------------------------------------

Translating ASM:  80%|██████████████████▎    | 796/1000 [05:48<01:22,  2.46it/s]

[796/1000]
EN: Mysore Dasara procession draws eight lakh visitors on Vijayadashami day.
ASM: বিজয় দশমী দিৱসত মহীশূৰ দশাৰা শোভাযাত্ৰাই আঠ লাখ দৰ্শনাৰ্থীক আকৰ্ষণ কৰে ।
--------------------------------------------------

Translating ASM:  80%|██████████████████▎    | 797/1000 [05:48<01:20,  2.51it/s]

[797/1000]
EN: Konark Sun Temple to get 3D projection mapping experience.
ASM: ৩ডি প্ৰজেকশ্বন মেপিং অভিজ্ঞতা লাভ কৰিব কনাৰ্ক ছান মন্দিৰে ।
--------------------------------------------------

Translating ASM:  80%|██████████████████▎    | 798/1000 [05:49<01:25,  2.37it/s]

[798/1000]
EN: Elephanta Caves introduce Portuguese audio guide for visitors.
ASM: ইলিফেণ্টা গুহাত পৰ্যটকৰ বাবে পৰ্টুগীজ অডিঅ গাইড প্ৰদৰ্শন কৰা হয় ।
--------------------------------------------------

Translating ASM:  80%|██████████████████▍    | 799/1000 [05:49<01:26,  2.31it/s]

[799/1000]
EN: Golconda Fort light and sound show revamped in Telugu and English.
ASM: তেলুগু আৰু ইংৰাজী ভাষাত গলকন্দা ফৰ্ট লাইট এণ্ড ছাউণ্ড শ্ব ৰ পুনৰ নিৰ্মাণ ।
--------------------------------------------------

Translating ASM:  80%|██████████████████▍    | 800/1000 [05:50<01:21,  2.46it/s]

[800/1000]
EN: Five regional medical hubs to be set up to boost medical tourism in country
ASM: দেশত চিকিৎসা পৰ্যটন বৃদ্ধিৰ বাবে পাঁচটা আঞ্চলিক চিকিৎসা কেন্দ্ৰ স্থাপন কৰা হব ।
--------------------------------------------------

Translating ASM:  80%|██████████████████▍    | 801/1000 [05:50<01:15,  2.65it/s]

[801/1000]
EN: Union Budget 2026 announces NIMHANS for north India
ASM: কেন্দ্ৰীয় বাজেট ২০২৬ত উত্তৰ ভাৰতৰ বাবে নিমহানছ ঘোষণা কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  80%|██████████████████▍    | 802/1000 [05:50<01:12,  2.72it/s]

[802/1000]
EN: Centre forms expert panel on healthcare for transgender persons
ASM: কেন্দ্ৰটোৱে ট্ৰেন্সজেণ্ডাৰ ব্যক্তিসকলৰ বাবে স্বাস্থ্যসেৱাৰ বিশেষজ্ঞৰ এটা পেনেল গঠন কৰে ।
--------------------------------------------------

Translating ASM:  80%|██████████████████▍    | 803/1000 [05:51<01:14,  2.66it/s]

[803/1000]
EN: Stem cell therapy cannot be offered as a clinical service for autism
ASM: স্টেম চেল থেৰাপি অটিজম ৰোগৰ বাবে এটা ক্লিনিকেল সেৱা হিচাপে আগবঢ়োৱা নহয়
--------------------------------------------------

Translating ASM:  80%|██████████████████▍    | 804/1000 [05:51<01:09,  2.83it/s]

[804/1000]
EN: AI helps doctors spot breast cancer in scans
ASM: এআইয়ে চিকিৎসকসকলক স্কানত স্তনৰ কৰ্কট চিনাক্ত কৰাত সহায় কৰে
--------------------------------------------------

Translating ASM:  80%|██████████████████▌    | 805/1000 [05:51<01:18,  2.48it/s]

[805/1000]
EN: Every family today knows someone with cancer and It is no longer a disease that happens to an ageing parent or relative
ASM: আজি প্ৰত্যেকটো পৰিয়ালতে কেন্সাৰ ৰোগত আক্ৰান্ত এজন ব্যক্তিক জনা যায় আৰু ই কোনো বৃদ্ধ পিতৃ-মাতৃ বা আত্মীয়ৰ বাবে হোৱা ৰোগ নহয় ।
--------------------------------------------------

Translating ASM:  81%|██████████████████▌    | 806/1000 [05:52<01:14,  2.60it/s]

[806/1000]
EN: Government imposes import curbs on three pharma ingredients for one year
ASM: চৰকাৰে এবছৰৰ বাবে তিনিটা ফাৰ্মা উপাদান আমদানিৰ ক্ষেত্ৰত নিষেধাজ্ঞা আৰোপ কৰিছে ।
--------------------------------------------------

Translating ASM:  81%|██████████████████▌    | 807/1000 [05:52<01:11,  2.69it/s]

[807/1000]
EN: Menstrual health in schools is integral to right to life, says the Supreme Court
ASM: স্কুলত ঋতুস্ৰাৱ স্বাস্থ্য জীৱনৰ অধিকাৰৰ অবিচ্ছেদ্য বুলি উচ্চতম ন্যায়ালয়ে কয়
--------------------------------------------------

Translating ASM:  81%|██████████████████▌    | 808/1000 [05:52<01:09,  2.75it/s]

[808/1000]
EN: WHO sees low risk of Nipah virus spreading beyond India
ASM: বিশ্ব স্বাস্থ্য সংস্থাই নিপা ভাইৰাছ ভাৰতৰ বাহিৰত বিয়পি পৰাৰ নিম্ন সম্ভাৱনা দেখিবলৈ পাইছে
--------------------------------------------------

Translating ASM:  81%|██████████████████▌    | 809/1000 [05:53<01:14,  2.58it/s]

[809/1000]
EN: Economic Survey calls for tackling rising digital addiction and screen-related mental health problems
ASM: অৰ্থনৈতিক সমীক্ষাত ডিজিটেল আসক্তি বৃদ্ধি আৰু স্ক্ৰীণ সম্পৰ্কীয় মানসিক স্বাস্থ্য সমস্যাসমূহৰ সৈতে মোকাবিলা কৰিবলৈ আহ্বান জনোৱা হৈছে
--------------------------------------------------

Translating ASM:  81%|██████████████████▋    | 810/1000 [05:53<01:15,  2.51it/s]

[810/1000]
EN: 188 million children and adolescents living with obesity worldwide
ASM: বিশ্বজুৰি ১৮৮ নিযুত শিশু আৰু কিশোৰ-কিশোৰী স্থূলতা ৰোগত ভুগিছে ।
--------------------------------------------------

Translating ASM:  81%|██████████████████▋    | 811/1000 [05:54<01:07,  2.80it/s]

[811/1000]
EN: 60% of mental disorders found in patients below 35 years
ASM: ৩৫ বছৰৰ তলৰ ৰোগীৰ ৬০% মানসিক বিকাৰ পোৱা যায়
--------------------------------------------------

Translating ASM:  81%|██████████████████▋    | 812/1000 [05:54<01:09,  2.71it/s]

[812/1000]
EN: Obesity impacts on brain may depend on how fat is distributed across body
ASM: শৰীৰত চৰ্বি কেনেকৈ বিতৰণ কৰা হয় তাৰ ওপৰত মগজুত স্থূলতাৰ প্ৰভাৱ নিৰ্ভৰ কৰিব পাৰে
--------------------------------------------------

Translating ASM:  81%|██████████████████▋    | 813/1000 [05:55<01:21,  2.31it/s]

[813/1000]
EN: Maharashtra, Karnataka, Tamil Nadu have highest number of vacancies under the NEET-PG 2025-26
ASM: এনইইটি-পিজি ২০২৫-২৬ৰ অধীনত মহাৰাষ্ট্ৰ, কৰ্ণাটক আৰু তামিলনাডুত সৰ্বাধিক খালী পদ আছে ।
--------------------------------------------------

Translating ASM:  81%|██████████████████▋    | 814/1000 [05:55<01:27,  2.13it/s]

[814/1000]
EN: Only two Nipah virus disease cases reported in West Bengal since December 2025, says Health Ministry
ASM: স্বাস্থ্য মন্ত্ৰালয়ে কৈছে যে ২০২৫ চনৰ ডিচেম্বৰৰ পৰা পশ্চিম বংগত কেৱল দুটা নিপা ভাইৰাছ ৰোগৰ ঘটনাহে ৰিপৰ্ট কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  82%|██████████████████▋    | 815/1000 [05:55<01:22,  2.25it/s]

[815/1000]
EN: Health impacts due to plastics worldwide may double by 2040
ASM: ২০৪০ চনৰ ভিতৰত প্লাষ্টিকৰ দ্বাৰা বিশ্বজুৰি স্বাস্থ্যৰ ওপৰত হোৱা প্ৰভাৱ দুগুণ হব পাৰে
--------------------------------------------------

Translating ASM:  82%|██████████████████▊    | 816/1000 [05:56<01:16,  2.40it/s]

[816/1000]
EN: China halts sale of Sun Pharma drug used to treat dementia
ASM: চীনত ডেমেনচিয়াৰ চিকিৎসাৰ বাবে ব্যৱহাৰ কৰা ছান ফাৰ্মা ঔষধৰ বিক্ৰী বন্ধ
--------------------------------------------------

Translating ASM:  82%|██████████████████▊    | 817/1000 [05:56<01:24,  2.17it/s]

[817/1000]
EN: T.N. govt. scheme improves access to diabetes, hypertension care for women as rural residents
ASM: তামিলনাডু চৰকাৰৰ আঁচনিয়ে গ্ৰামাঞ্চলৰ বাসিন্দা হিচাপে মহিলাসকলৰ বাবে ডায়েবেটিছ, উচ্চ ৰক্তচাপৰ যত্নৰ সুবিধা উন্নত কৰে ।
--------------------------------------------------

Translating ASM:  82%|██████████████████▊    | 818/1000 [05:57<01:42,  1.77it/s]

[818/1000]
EN: Karnataka farmers urge Union Government to recommend to WHO to re-classify arecanut from ‘carcinogenic’ to ‘possibly carcinogenic to humans’
ASM: কৰ্ণাটকৰ কৃষকসকলে কেন্দ্ৰীয় চৰকাৰক ডব্লিউএইচঅ'ক কেন্সাৰজেনিকৰ পৰা মানুহৰ বাবে সম্ভৱতঃ কেন্সাৰজেনিকলৈ কেন্সাৰজেনিক পুনৰ শ্ৰেণীবদ্ধ কৰিবলৈ পৰামৰ্শ দিবলৈ আহ্বান জনাইছে ।
--------------------------------------------------

Translating ASM:  82%|██████████████████▊    | 819/1000 [05:58<01:38,  1.84it/s]

[819/1000]
EN: Study discovers stress-reducing role of natural molecule in body, may help with metabolic disorders
ASM: অধ্যয়নে শৰীৰত প্ৰাকৃতিক আণুৰ চাপ হ্ৰাস কৰা ভূমিকা আৱিষ্কাৰ কৰে, মেটাবোলিক ব্যাধিৰ সৈতে সহায় কৰিব পাৰে
--------------------------------------------------

Translating ASM:  82%|██████████████████▊    | 820/1000 [05:58<01:25,  2.10it/s]

[820/1000]
EN: Keeping your spine healthy with small, everyday changes
ASM: দৈনন্দিন ক্ষুদ্ৰ পৰিৱৰ্তন কৰি মঙহটো সুস্থ কৰি ৰাখা
--------------------------------------------------

Translating ASM:  82%|██████████████████▉    | 821/1000 [05:58<01:16,  2.34it/s]

[821/1000]
EN: What is behind the increasing number of heart attacks in pregnancy?
ASM: গৰ্ভধাৰণৰ সময়ত হৃদযন্ত্ৰৰ দ্বাৰা আক্ৰান্ত হোৱাৰ কাৰণ কি?
--------------------------------------------------

Translating ASM:  82%|██████████████████▉    | 822/1000 [05:59<01:08,  2.61it/s]

[822/1000]
EN: Can India eliminate malaria by 2030?
ASM: ভাৰতে ২০৩০ চনৰ ভিতৰত মেলেৰিয়া নিৰ্মূল কৰিব পাৰিবনে?
--------------------------------------------------

Translating ASM:  82%|██████████████████▉    | 823/1000 [05:59<01:15,  2.35it/s]

[823/1000]
EN: Tamil Nadu government seeks IIT-M’s assistance to study ill effects of microplastics on human health
ASM: মানুহৰ স্বাস্থ্যৰ ওপৰত মাইক্ৰোপ্লাষ্টিকৰ ক্ষতিকাৰক প্ৰভাৱ অধ্যয়ন কৰিবলৈ তামিলনাডু চৰকাৰে আইআইটি-এমৰ সহায় বিচাৰিছে
--------------------------------------------------

Translating ASM:  82%|██████████████████▉    | 824/1000 [05:59<01:09,  2.52it/s]

[824/1000]
EN: Goa seeks to grow as a wellness and medical tourism hub in India
ASM: গোৱা ভাৰতৰ সুস্থতা আৰু চিকিৎসা পৰ্যটনৰ কেন্দ্ৰ হিচাপে বিকশিত হবলৈ বিচাৰিছে
--------------------------------------------------

Translating ASM:  82%|██████████████████▉    | 825/1000 [06:00<01:15,  2.32it/s]

[825/1000]
EN: Borewell found contaminated, pipelines being probed as eight remain in hospital in Madhya Pradesh's Mhow
ASM: মধ্যপ্ৰদেশৰ মহৌত আঠজন ৰোগী চিকিৎসালয়ত থকাৰ বাবে বৰেৱেল দূষিত পোৱা গৈছে, পাইপলাইন পৰীক্ষা কৰি থকা হৈছে ।
--------------------------------------------------

Translating ASM:  83%|██████████████████▉    | 826/1000 [06:00<01:17,  2.23it/s]

[826/1000]
EN: Uttar Pradesh youth amputates foot to seek disability quota in admission to medical college
ASM: মেডিকেল কলেজত নামভৰ্তিৰ বাবে অক্ষমতা কোটা বিচাৰি উত্তৰ প্ৰদেশৰ যুৱক-যুৱতীয়ে ভৰি কাটিলে
--------------------------------------------------

Translating ASM:  83%|███████████████████    | 827/1000 [06:01<01:18,  2.21it/s]

[827/1000]
EN: Police investigate software engineer’s death in Chennai lodge linked to bug repellent fumes
ASM: বাগ প্ৰতিৰোধক ধোঁৱাৰ সৈতে জড়িত চেন্নাই লজত ছফটৱেৰ অভিযন্তাৰ মৃত্যুৰ তদন্ত কৰিছে আৰক্ষীয়ে ।
--------------------------------------------------

Translating ASM:  83%|███████████████████    | 828/1000 [06:01<01:12,  2.37it/s]

[828/1000]
EN: Regularly engaging in varied physical activities could extend lifespan
ASM: নিয়মীয়াকৈ বিভিন্ন শাৰীৰিক কাৰ্য্যকলাপ কৰা কাৰ্য্যই জীৱনৰ আয়ুস বৃদ্ধি কৰিব পাৰে
--------------------------------------------------

Translating ASM:  83%|███████████████████    | 829/1000 [06:02<01:15,  2.26it/s]

[829/1000]
EN: Study relates ADHD traits in childhood with physical health problems in mid-life
ASM: গৱেষণাত শিশু অৱস্থাত হোৱা এডিএইচডি আৰু মধ্যবয়সত হোৱা শাৰীৰিক স্বাস্থ্যজনিত সমস্যাৰ সৈতে সম্পৰ্ক আছে
--------------------------------------------------

Translating ASM:  83%|███████████████████    | 830/1000 [06:02<01:04,  2.62it/s]

[830/1000]
EN: U.S. completes withdrawal from World Health Organization
ASM: আমেৰিকা যুক্তৰাষ্ট্ৰই বিশ্ব স্বাস্থ্য সংস্থাৰ পৰা প্ৰত্যাহাৰ সম্পূৰ্ণ কৰিছে
--------------------------------------------------

Translating ASM:  83%|███████████████████    | 831/1000 [06:02<01:04,  2.63it/s]

[831/1000]
EN: Punjab health scheme offers free hospital care worth ₹10 lakh to every family
ASM: পঞ্জাৱ স্বাস্থ্য আঁচনিয়ে প্ৰতিখন পৰিয়ালক ১০ লাখ টকাৰ বিনামূলীয়া চিকিৎসালয়ৰ চিকিৎসা প্ৰদান কৰিছে ।
--------------------------------------------------

Translating ASM:  83%|███████████████████▏   | 832/1000 [06:03<01:07,  2.49it/s]

[832/1000]
EN: Snapchat launches new Family Center safety tools for teens and parents
ASM: চনাপচাটে কিশোৰী আৰু অভিভাৱকৰ বাবে নতুন ফেমিলি চেণ্টাৰ সুৰক্ষা সঁজুলি মুকলি কৰিছে
--------------------------------------------------

Translating ASM:  83%|███████████████████▏   | 833/1000 [06:03<01:11,  2.33it/s]

[833/1000]
EN: 167 drug samples flagged as ‘not of standard quality’ in December 2025
ASM: ২০২৫ৰ ডিচেম্বৰত ১৬৭টা ঔষধৰ নমুনাক মানৰ মানদণ্ডৰ নহয় বুলি চিহ্নিত কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  83%|███████████████████▏   | 834/1000 [06:04<01:08,  2.44it/s]

[834/1000]
EN: Tamil Nadu issues guidelines as chikungunya cases rise in State
ASM: ৰাজ্যত চিকুনগুনিয়া ঘটনা বৃদ্ধি হোৱাৰ লগে লগে তামিলনাডুৱে নিৰ্দেশনা জাৰি কৰিছে
--------------------------------------------------

Translating ASM:  84%|███████████████████▏   | 835/1000 [06:04<01:07,  2.44it/s]

[835/1000]
EN: Researchers develop tool to simplify nutritional tracking of Indian meals
ASM: গৱেষকসকলে ভাৰতীয় খাদ্যৰ পুষ্টিগত ট্ৰেকিং সৰল কৰাৰ বাবে এটা সঁজুলি প্ৰস্তুত কৰিছে ।
--------------------------------------------------

Translating ASM:  84%|███████████████████▏   | 836/1000 [06:04<01:06,  2.48it/s]

[836/1000]
EN: Shingles vaccine may also slow down biological ageing in older adults
ASM: শিংগলছ ভেকছিনে বয়স্ক লোকৰ জৈৱিক বয়স বৃদ্ধিকো ধীৰ কৰিব পাৰে
--------------------------------------------------

Translating ASM:  84%|███████████████████▎   | 837/1000 [06:05<01:07,  2.42it/s]

[837/1000]
EN: Gates and OpenAI team up for AI health push in African countries
ASM: আফ্ৰিকাৰ দেশসমূহত এআই স্বাস্থ্যৰ প্ৰসাৰৰ বাবে গেটছ আৰু অপেনএআইয়ে একত্ৰিত হৈছে
--------------------------------------------------

Translating ASM:  84%|███████████████████▎   | 838/1000 [06:05<01:03,  2.54it/s]

[838/1000]
EN: ASHA workers protest in Kolkata for ₹15,000 monthly honorarium
ASM: মাহিলি ১৫ হাজাৰ টকাৰ সন্মানৰ দাবীত কলিকতাত আশা কৰ্মীৰ প্ৰতিবাদ
--------------------------------------------------

Translating ASM:  84%|███████████████████▎   | 839/1000 [06:06<01:08,  2.34it/s]

[839/1000]
EN: Bloodless heart surgery performed on patient with rare blood group at Kauvery Hospital
ASM: কেভেৰী চিকিৎসালয়ত বিৰল ৰক্ত গোষ্ঠী থকা ৰোগীৰ ওপৰত তেজৰ অবিহনে হৃদযন্ত্ৰৰ অস্ত্ৰোপচাৰ কৰা হয়
--------------------------------------------------

Translating ASM:  84%|███████████████████▎   | 840/1000 [06:06<01:09,  2.30it/s]

[840/1000]
EN: Centre sanctions 50-bed AYUSH hospital for Tenali, says A.P. Minister
ASM: টেনালীৰ বাবে কেন্দ্ৰই অনুমোদন জনাইছে ৫০ খন বিচনাযুক্ত আয়ুষ চিকিৎসালয়, কয় উপমন্ত্ৰীয়ে
--------------------------------------------------

Translating ASM:  84%|███████████████████▎   | 841/1000 [06:07<01:17,  2.05it/s]

[841/1000]
EN: NIMS Hyderabad opens Stem Cell Centre of Excellence as India battles rising burden of lifestyle diseases
ASM: ভাৰতৰ জীৱনশৈলী ৰোগৰ ক্ৰমবৰ্ধিত ভাৰৰ সৈতে যুঁজ দি এনআইএমএছ হায়দৰাবাদে উৎকৃষ্ট ষ্টেম চেল কেন্দ্ৰ মুকলি কৰিছে
--------------------------------------------------

Translating ASM:  84%|███████████████████▎   | 842/1000 [06:07<01:21,  1.94it/s]

[842/1000]
EN: The Ministry of Health and Family Welfare launched a nationwide campaign to improve early detection of non-communicable diseases in rural India.
ASM: স্বাস্থ্য আৰু পৰিয়াল কল্যান মন্ত্ৰালয়ে গ্ৰামাঞ্চলত অনা-সংক্ৰামক ৰোগৰ প্ৰাৰম্ভিক চিনাক্তকৰণ উন্নত কৰিবলৈ এখন দেশব্যাপী অভিযান আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  84%|███████████████████▍   | 843/1000 [06:08<01:13,  2.13it/s]

[843/1000]
EN: The Government of India announced an increase in funding for public hospitals under the National Health Mission.
ASM: ভাৰত চৰকাৰে ৰাষ্ট্ৰীয় স্বাস্থ্য অভিযানৰ অধীনত ৰাজহুৱা চিকিৎসালয়সমূহৰ বাবে পুঁজি বৃদ্ধি কৰাৰ কথা ঘোষণা কৰে ।
--------------------------------------------------

Translating ASM:  84%|███████████████████▍   | 844/1000 [06:08<01:15,  2.05it/s]

[844/1000]
EN: Indian researchers developed a low-cost diagnostic kit to detect tuberculosis with higher accuracy.
ASM: ভাৰতীয় গৱেষকসকলে উচ্চ নির্ভুলতাৰে যক্ষ্মা ৰোগ চিনাক্ত কৰিবলৈ এটা কম খৰচৰ ডায়েগনষ্টিক কিট প্ৰস্তুত কৰিছিল ।
--------------------------------------------------

Translating ASM:  84%|███████████████████▍   | 845/1000 [06:09<01:13,  2.12it/s]

[845/1000]
EN: The Indian Council of Medical Research issued updated guidelines for the treatment of dengue fever.
ASM: ভাৰতীয় চিকিৎসা গৱেষণা পৰিষদে ডেংগু জ্বৰৰ চিকিৎসাৰ বাবে আপডেট গাইডলাইন জাৰি কৰিছে ।
--------------------------------------------------

Translating ASM:  85%|███████████████████▍   | 846/1000 [06:09<01:10,  2.19it/s]

[846/1000]
EN: A new government medical college was inaugurated in Assam to strengthen healthcare education in the northeastern region.
ASM: উত্তৰ-পূব অঞ্চলত স্বাস্থ্যসেৱা শিক্ষা শক্তিশালী কৰিবলৈ অসমত এখন নতুন চৰকাৰী চিকিৎসা মহাবিদ্যালয় মুকলি কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  85%|███████████████████▍   | 847/1000 [06:10<01:08,  2.24it/s]

[847/1000]
EN: The Union Health Minister reviewed the progress of Ayushman Bharat services across multiple states.
ASM: কেন্দ্ৰীয় স্বাস্থ্য মন্ত্ৰীগৰাকীয়ে একাধিক ৰাজ্যত আয়ুষ্মান ভাৰতৰ সেৱাৰ অগ্ৰগতিৰ পৰ্যালোচনা কৰে ।
--------------------------------------------------

Translating ASM:  85%|███████████████████▌   | 848/1000 [06:10<01:06,  2.30it/s]

[848/1000]
EN: India reported a decline in maternal mortality rates due to improved institutional delivery services.
ASM: ভাৰতে উন্নত প্ৰতিষ্ঠানগত প্ৰসৱ সেৱাৰ বাবে মাতৃৰ মৃত্যুৰ হাৰ হ্ৰাস হোৱা বুলি ৰিপৰ্ট কৰিছিল ।
--------------------------------------------------

Translating ASM:  85%|███████████████████▌   | 849/1000 [06:11<01:09,  2.16it/s]

[849/1000]
EN: The Drug Controller General of India approved a new vaccine for preventing cervical cancer.
ASM: ভাৰতৰ ড্ৰাগ কন্ট্ৰোলাৰ জেনেৰেলই গৰ্ভবৃত্ত কৰ্কট প্ৰতিৰোধৰ বাবে এটা নতুন ভেকছিন অনুমোদন জনাইছে ।
--------------------------------------------------

Translating ASM:  85%|███████████████████▌   | 850/1000 [06:11<01:05,  2.28it/s]

[850/1000]
EN: Several state governments expanded free dialysis services in district hospitals.
ASM: কেইবাখনো ৰাজ্য চৰকাৰে জিলা চিকিৎসালয়ত বিনামূলীয়া ডায়েলিচ সেৱা সম্প্ৰসাৰিত কৰিছে ।
--------------------------------------------------

Translating ASM:  85%|███████████████████▌   | 851/1000 [06:11<01:05,  2.28it/s]

[851/1000]
EN: The World Health Organization praised India’s efforts in polio eradication during a regional health summit.
ASM: বিশ্ব স্বাস্থ্য সংস্থাই এক আঞ্চলিক স্বাস্থ্য সন্মিলনত পোলিঅ নির্মূলৰ ক্ষেত্ৰত ভাৰতৰ প্ৰচেষ্টাক প্ৰশংসা কৰে ।
--------------------------------------------------

Translating ASM:  85%|███████████████████▌   | 852/1000 [06:12<01:12,  2.03it/s]

[852/1000]
EN: A public health survey revealed improved vaccination coverage among children in urban slum areas.
ASM: এটা ৰাজহুৱা স্বাস্থ্য সমীক্ষাত প্ৰকাশ পাইছে যে চহৰৰ আৱৰ্জনাপূৰ্ণ এলেকাবোৰত লৰা-ছোৱালীৰ মাজত উন্নত টিকাকৰণ কভাৰেজ আছে ।
--------------------------------------------------

Translating ASM:  85%|███████████████████▌   | 853/1000 [06:13<01:15,  1.95it/s]

[853/1000]
EN: The Ministry of AYUSH promoted traditional medicine research through newly funded clinical studies.
ASM: আয়ুষ মন্ত্ৰালয়ে নতুনকৈ পুঁজি যোগান ধৰা ক্লিনিকেল অধ্যয়নৰ জৰিয়তে পৰম্পৰাগত ঔষধৰ গৱেষণাক উৎসাহিত কৰিছে ।
--------------------------------------------------

Translating ASM:  85%|███████████████████▋   | 854/1000 [06:13<01:16,  1.90it/s]

[854/1000]
EN: Indian hospitals adopted artificial intelligence tools to assist doctors in early cancer detection.
ASM: ভাৰতীয় চিকিৎসালয়সমূহে কৃত্ৰিম বুদ্ধিমত্তাৰ সঁজুলি গ্ৰহণ কৰি চিকিৎসকসকলক কেন্সাৰৰ প্ৰাৰম্ভিক চিনাক্তকৰণত সহায় কৰে ।
--------------------------------------------------

Translating ASM:  86%|███████████████████▋   | 855/1000 [06:13<01:09,  2.07it/s]

[855/1000]
EN: The National Medical Commission introduced revised norms for undergraduate medical education.
ASM: ৰাষ্ট্ৰীয় চিকিৎসা আয়োগে স্নাতকোত্তৰ চিকিৎসা শিক্ষাৰ বাবে সংশোধিত মানদণ্ড প্ৰৱৰ্তন কৰে ।
--------------------------------------------------

Translating ASM:  86%|███████████████████▋   | 856/1000 [06:14<01:05,  2.20it/s]

[856/1000]
EN: A shortage of specialist doctors was reported in government hospitals across rural districts.
ASM: গ্ৰাম্য জিলাসমূহৰ চৰকাৰী চিকিৎসালয়ত বিশেষজ্ঞ চিকিৎসকৰ অভাৱৰ খবৰ পোৱা গৈছিল ।
--------------------------------------------------

Translating ASM:  86%|███████████████████▋   | 857/1000 [06:14<01:03,  2.25it/s]

[857/1000]
EN: The central government launched a digital health ID system to streamline patient medical records.
ASM: কেন্দ্ৰীয় চৰকাৰে ৰোগীৰ চিকিৎসা নথিপত্ৰ সৰলীকৰণৰ বাবে এটা ডিজিটেল স্বাস্থ্য পৰিচয় প্ৰণালী আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  86%|███████████████████▋   | 858/1000 [06:15<01:00,  2.34it/s]

[858/1000]
EN: India’s pharmaceutical exports increased due to rising global demand for generic medicines.
ASM: বিশ্বব্যাপী জেনেৰিক ঔষধৰ চাহিদা বৃদ্ধি হোৱাৰ বাবে ভাৰতৰ ঔষধৰ ৰপ্তানি বৃদ্ধি পাইছে ।
--------------------------------------------------

Translating ASM:  86%|███████████████████▊   | 859/1000 [06:15<01:00,  2.33it/s]

[859/1000]
EN: The Supreme Court of India directed states to improve healthcare infrastructure in tribal areas.
ASM: ভাৰতীয় উচ্চতম ন্যায়ালয়ে জনজাতীয় অঞ্চলৰ স্বাস্থ্যসেৱা আন্তঃগাঁথনি উন্নত কৰিবলৈ ৰাজ্যসমূহক নিৰ্দেশ দিছিল ।
--------------------------------------------------

Translating ASM:  86%|███████████████████▊   | 860/1000 [06:16<01:01,  2.27it/s]

[860/1000]
EN: A government report highlighted gaps in mental health services in public healthcare facilities.
ASM: এখন চৰকাৰী প্ৰতিবেদনত ৰাজহুৱা স্বাস্থ্যসেৱা সুবিধাসমূহত মানসিক স্বাস্থ্য সেৱাৰ ব্যৱধানৰ ওপৰত আলোকপাত কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  86%|███████████████████▊   | 861/1000 [06:16<00:59,  2.32it/s]

[861/1000]
EN: Several private hospitals partnered with state governments to offer affordable cardiac care.
ASM: কেইবাখনো ব্যক্তিগত চিকিৎসালয়ে ৰাজ্য চৰকাৰৰ সৈতে সহযোগিতা কৰি সুলভ মূল্যত হৃদযন্ত্ৰৰ যত্ন আগবঢ়াইছে ।
--------------------------------------------------

Translating ASM:  86%|███████████████████▊   | 862/1000 [06:16<01:00,  2.29it/s]

[862/1000]
EN: The Indian Institute of Public Health conducted a study on air pollution-related respiratory diseases.
ASM: ভাৰতীয় ৰাজহুৱা স্বাস্থ্য প্ৰতিষ্ঠানটোৱে বায়ু প্ৰদূষণ সম্পৰ্কীয় শ্বাসযন্ত্ৰৰ ৰোগৰ ওপৰত এক অধ্যয়ন কৰিছিল ।
--------------------------------------------------

Translating ASM:  86%|███████████████████▊   | 863/1000 [06:17<00:55,  2.48it/s]

[863/1000]
EN: Health officials initiated a special drive to control the spread of seasonal influenza.
ASM: স্বাস্থ্য বিষয়াসকলে মৌসুমী ফ্লুৰ বিস্তাৰ নিয়ন্ত্ৰণ কৰিবলৈ এক বিশেষ অভিযান আৰম্ভ কৰিছিল ।
--------------------------------------------------

Translating ASM:  86%|███████████████████▊   | 864/1000 [06:17<00:56,  2.40it/s]

[864/1000]
EN: The Ministry of Health strengthened surveillance systems to monitor emerging infectious diseases.
ASM: স্বাস্থ্য মন্ত্ৰালয়ে নতুনকৈ উদ্ভৱ হোৱা সংক্ৰামক ৰোগৰ নিৰীক্ষণৰ বাবে নিৰীক্ষণ প্ৰণালী শক্তিশালী কৰিছে ।
--------------------------------------------------

Translating ASM:  86%|███████████████████▉   | 865/1000 [06:18<00:58,  2.32it/s]

[865/1000]
EN: India recorded a steady rise in organ donation registrations through national awareness campaigns.
ASM: ভাৰতে ৰাষ্ট্ৰীয় সজাগতা অভিযানসমূহৰ জৰিয়তে অঙ্গদানৰ পঞ্জীয়নৰ ধাৰাবাহিক বৃদ্ধিৰ অভিলেখ গঢ়ি তুলিছে ।
--------------------------------------------------

Translating ASM:  87%|███████████████████▉   | 866/1000 [06:18<00:58,  2.28it/s]

[866/1000]
EN: A new telemedicine platform was introduced to improve access to healthcare in remote villages.
ASM: দূৰৱৰ্তী গাওঁসমূহত স্বাস্থ্যসেৱাৰ সুবিধা বৃদ্ধিৰ বাবে এটা নতুন টেলিমেডিচিন প্লেটফৰ্ম প্ৰৱৰ্তন কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  87%|███████████████████▉   | 867/1000 [06:19<00:57,  2.31it/s]

[867/1000]
EN: The National AIDS Control Organisation reported a decline in new HIV infections.
ASM: ৰাষ্ট্ৰীয় এইডছ নিয়ন্ত্ৰণ সংস্থাই নতুন এইচআইভি সংক্ৰমণৰ হ্ৰাস হোৱা বুলি ৰিপৰ্ট কৰিছিল ।
--------------------------------------------------

Translating ASM:  87%|███████████████████▉   | 868/1000 [06:19<00:57,  2.30it/s]

[868/1000]
EN: Government hospitals increased the availability of free essential medicines for outpatients.
ASM: চৰকাৰী চিকিৎসালয়সমূহে বহনক্ষম ৰোগীসকলৰ বাবে বিনামূলীয়া অত্যাৱশ্যকীয় ঔষধৰ উপলব্ধতা বৃদ্ধি কৰিছে ।
--------------------------------------------------

Translating ASM:  87%|███████████████████▉   | 869/1000 [06:19<00:59,  2.21it/s]

[869/1000]
EN: A policy review emphasized the need for more nursing staff in public healthcare institutions.
ASM: এক নীতি পৰ্যালোচনাত ৰাজহুৱা স্বাস্থ্যসেৱা প্ৰতিষ্ঠানসমূহত অধিক নাৰ্চিং কৰ্মচাৰীৰ প্ৰয়োজনীয়তাৰ ওপৰত গুৰুত্ব আৰোপ কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  87%|████████████████████   | 870/1000 [06:20<00:53,  2.45it/s]

[870/1000]
EN: The Indian government signed a health cooperation agreement with a neighboring country.
ASM: ভাৰত চৰকাৰে এখন চুবুৰীয়া দেশৰ সৈতে স্বাস্থ্য সহযোগিতাৰ চুক্তি স্বাক্ষৰ কৰিছে ।
--------------------------------------------------

Translating ASM:  87%|████████████████████   | 871/1000 [06:20<00:53,  2.40it/s]

[871/1000]
EN: Researchers from an Indian medical institute published findings on antibiotic resistance trends.
ASM: এটা ভাৰতীয় চিকিৎসা প্ৰতিষ্ঠানৰ গৱেষকসকলে এণ্টিবায়টিক প্ৰতিৰোধৰ প্ৰবণতা সম্পৰ্কে ফলাফল প্ৰকাশ কৰিছে ।
--------------------------------------------------

Translating ASM:  87%|████████████████████   | 872/1000 [06:21<00:50,  2.53it/s]

[872/1000]
EN: The Health Ministry issued advisories to states following a rise in heat-related illnesses.
ASM: তাপ সম্পৰ্কীয় ৰোগ বৃদ্ধিৰ পিছত স্বাস্থ্য মন্ত্ৰালয়ে ৰাজ্যসমূহক পৰামৰ্শ জাৰি কৰিছিল ।
--------------------------------------------------

Translating ASM:  87%|████████████████████   | 873/1000 [06:21<00:55,  2.29it/s]

[873/1000]
EN: India expanded its emergency ambulance network to improve response times in rural regions.
ASM: ভাৰতে গ্ৰাম্য অঞ্চলৰ প্ৰতিক্ৰিয়া সময় উন্নত কৰিবলৈ নিজৰ জৰুৰীকালীন এম্বুলেন্স নেটৱৰ্ক সম্প্ৰসাৰিত কৰিছে ।
--------------------------------------------------

Translating ASM:  87%|████████████████████   | 874/1000 [06:21<00:51,  2.44it/s]

[874/1000]
EN: The National Digital Health Mission aimed to improve transparency in healthcare service delivery.
ASM: ৰাষ্ট্ৰীয় ডিজিটেল স্বাস্থ্য অভিযানৰ লক্ষ্য হৈছে স্বাস্থ্যসেৱা সেৱাৰ বিতৰণত স্বচ্ছতা বৃদ্ধি কৰা ।
--------------------------------------------------

Translating ASM:  88%|████████████████████▏  | 875/1000 [06:22<00:55,  2.26it/s]

[875/1000]
EN: A public-private partnership model was introduced to upgrade district-level hospitals.
ASM: জিলা পৰ্যায়ৰ চিকিৎসালয়সমূহৰ উন্নতিৰ বাবে এখন ৰাজহুৱা-বেচৰকাৰী অংশীদাৰিত্বৰ মডেল প্ৰৱৰ্তন কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  88%|████████████████████▏  | 876/1000 [06:22<00:53,  2.31it/s]

[876/1000]
EN: The government launched a mental health helpline to support individuals during medical emergencies.
ASM: চৰকাৰে চিকিৎসা জৰুৰীকালীন অৱস্থাত ব্যক্তিসকলক সমৰ্থন কৰিবলৈ এটা মানসিক স্বাস্থ্য হেল্পলাইন মুকলি কৰিছে ।
--------------------------------------------------

Translating ASM:  88%|████████████████████▏  | 877/1000 [06:23<00:50,  2.43it/s]

[877/1000]
EN: India’s medical tourism sector showed growth due to affordable treatment options.
ASM: সুলভ চিকিৎসা বিকল্পৰ বাবে ভাৰতৰ চিকিৎসা পৰ্যটন খণ্ডই বিকাশ দেখুৱালে ।
--------------------------------------------------

Translating ASM:  88%|████████████████████▏  | 878/1000 [06:23<00:51,  2.37it/s]

[878/1000]
EN: A parliamentary committee reviewed the implementation of healthcare schemes in backward districts.
ASM: এটা সংসদীয় সমিতিয়ে পিছপৰা জিলাসমূহত স্বাস্থ্যসেৱা আঁচনিৰ ৰূপায়ণৰ পৰ্যালোচনা কৰে ।
--------------------------------------------------

Translating ASM:  88%|████████████████████▏  | 879/1000 [06:24<00:48,  2.51it/s]

[879/1000]
EN: The Ministry of Health emphasized preventive healthcare during a national policy meeting.
ASM: স্বাস্থ্য মন্ত্ৰালয়ে ৰাষ্ট্ৰীয় নীতিমালা বৈঠকত প্ৰতিৰোধমূলক স্বাস্থ্যসেৱাৰ ওপৰত গুৰুত্ব আৰোপ কৰে ।
--------------------------------------------------

Translating ASM:  88%|████████████████████▏  | 880/1000 [06:24<00:48,  2.47it/s]

[880/1000]
EN: Indian scientists developed a wearable device to monitor heart health in elderly patients.
ASM: ভাৰতীয় বিজ্ঞানীসকলে বৃদ্ধ ৰোগীসকলৰ হৃদৰোগৰ স্বাস্থ্য নিৰীক্ষণ কৰিবলৈ এটা পিন্ধা যন্ত্ৰ প্ৰস্তুত কৰিছে ।
--------------------------------------------------

Translating ASM:  88%|████████████████████▎  | 881/1000 [06:24<00:47,  2.48it/s]

[881/1000]
EN: A national survey assessed nutritional deficiencies among children under five years of age.
ASM: এক ৰাষ্ট্ৰীয় সমীক্ষাত পাঁচ বছৰৰ তলৰ শিশুসকলৰ মাজত পুষ্টিৰ অভাৱৰ মূল্যায়ন কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  88%|████████████████████▎  | 882/1000 [06:25<00:46,  2.56it/s]

[882/1000]
EN: The government increased insurance coverage limits under Ayushman Bharat for critical illnesses.
ASM: চৰকাৰে গুৰুতৰ ৰোগৰ বাবে আয়ুষ্মান ভাৰতৰ অধীনত বীমা সুৰক্ষাৰ সীমা বৃদ্ধি কৰে ।
--------------------------------------------------

Translating ASM:  88%|████████████████████▎  | 883/1000 [06:25<00:49,  2.37it/s]

[883/1000]
EN: Health authorities conducted vaccination drives to prevent outbreaks of measles and rubella.
ASM: স্বাস্থ্য কৰ্তৃপক্ষই জ্বৰ আৰু ৰোবেলা ৰোগৰ প্ৰাদুৰ্ভাৱ প্ৰতিৰোধ কৰিবলৈ টিকাকৰণ অভিযান চলাইছিল ।
--------------------------------------------------

Translating ASM:  88%|████████████████████▎  | 884/1000 [06:26<00:45,  2.53it/s]

[884/1000]
EN: India strengthened laboratory capacity to improve disease surveillance and diagnosis.
ASM: ভাৰতে ৰোগ নিৰীক্ষণ আৰু নিৰীক্ষণ উন্নত কৰাৰ বাবে পৰীক্ষাগাৰৰ ক্ষমতা শক্তিশালী কৰিছে ।
--------------------------------------------------

Translating ASM:  88%|████████████████████▎  | 885/1000 [06:26<00:46,  2.46it/s]

[885/1000]
EN: A state health department launched mobile clinics to serve remote tribal communities.
ASM: এটা ৰাজ্যিক স্বাস্থ্য বিভাগে দূৰত্বৰ জনজাতীয় সম্প্ৰদায়ক সেৱা কৰিবলৈ ম'বাইল ক্লিনিক মুকলি কৰিছিল ।
--------------------------------------------------

Translating ASM:  89%|████████████████████▍  | 886/1000 [06:26<00:46,  2.47it/s]

[886/1000]
EN: The National Health Authority upgraded its data systems to enhance patient safety.
ASM: ৰাষ্ট্ৰীয় স্বাস্থ্য কৰ্তৃপক্ষই ৰোগীৰ সুৰক্ষা বৃদ্ধিৰ বাবে ইয়াৰ ডাটা ছিষ্টেম আপগ্রেড কৰিছে ।
--------------------------------------------------

Translating ASM:  89%|████████████████████▍  | 887/1000 [06:27<00:44,  2.53it/s]

[887/1000]
EN: Indian doctors highlighted the need for early screening of lifestyle-related diseases.
ASM: ভাৰতীয় চিকিৎসকসকলে জীৱনশৈলী সম্পৰ্কীয় ৰোগৰ অগ্ৰগতিৰ প্ৰয়োজনীয়তাৰ ওপৰত আলোকপাত কৰে ।
--------------------------------------------------

Translating ASM:  89%|████████████████████▍  | 888/1000 [06:27<00:42,  2.62it/s]

[888/1000]
EN: The Ministry of Health released new guidelines for hospital waste management.
ASM: স্বাস্থ্য মন্ত্ৰালয়ে চিকিৎসালয় আৱৰ্জনা ব্যৱস্থাপনাৰ বাবে নতুন নিৰ্দেশনা জাৰি কৰিছে ।
--------------------------------------------------

Translating ASM:  89%|████████████████████▍  | 889/1000 [06:27<00:43,  2.53it/s]

[889/1000]
EN: Several states reported improvements in primary healthcare access through wellness centers.
ASM: কেইবাখনো ৰাজ্যই সুস্থতা কেন্দ্ৰৰ জৰিয়তে প্ৰাথমিক স্বাস্থ্যসেৱাৰ প্ৰবেশৰ উন্নতিৰ বাতৰি প্ৰকাশ কৰিছে ।
--------------------------------------------------

Translating ASM:  89%|████████████████████▍  | 890/1000 [06:28<00:40,  2.69it/s]

[890/1000]
EN: India’s public health expenditure showed a gradual increase in the latest budget.
ASM: শেহতীয়া বাজেটত ভাৰতৰ ৰাজহুৱা স্বাস্থ্য ব্যয় ক্ৰমান্বয়ে বৃদ্ধি পাইছে ।
--------------------------------------------------

Translating ASM:  89%|████████████████████▍  | 891/1000 [06:28<00:41,  2.62it/s]

[891/1000]
EN: A new online portal was launched to track the availability of hospital beds.
ASM: চিকিৎসালয়ৰ বিচনাৰ উপলব্ধতা নিৰীক্ষণৰ বাবে এটা নতুন অনলাইন পৰ্টেল মুকলি কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  89%|████████████████████▌  | 892/1000 [06:29<00:42,  2.56it/s]

[892/1000]
EN: Health experts in India raised concerns about rising cases of diabetes among young adults.
ASM: ভাৰতৰ স্বাস্থ্য বিশেষজ্ঞসকলে যুৱ প্ৰাপ্তবয়স্কসকলৰ মাজত ডায়েবেটিছৰ ঘটনা বৃদ্ধি হোৱাৰ বিষয়ে উদ্বেগ প্ৰকাশ কৰে ।
--------------------------------------------------

Translating ASM:  89%|████████████████████▌  | 893/1000 [06:29<00:43,  2.47it/s]

[893/1000]
EN: The government initiated training programs to improve emergency care skills among paramedics.
ASM: চৰকাৰে পেৰামেডিকসকলৰ মাজত জৰুৰীকালীন যত্নৰ দক্ষতা উন্নত কৰিবলৈ প্ৰশিক্ষণ কাৰ্যসূচী আৰম্ভ কৰিছিল ।
--------------------------------------------------

Translating ASM:  89%|████████████████████▌  | 894/1000 [06:29<00:43,  2.42it/s]

[894/1000]
EN: Indian pharmaceutical companies invested in research for affordable cancer medicines.
ASM: ভাৰতীয় ঔষধ কোম্পানীসমূহে সুলভ মূল্যত কৰ্কট ৰোগৰ ঔষধ গৱেষণাত বিনিয়োগ কৰিছে ।
--------------------------------------------------

Translating ASM:  90%|████████████████████▌  | 895/1000 [06:30<00:44,  2.38it/s]

[895/1000]
EN: A national task force was formed to address antimicrobial resistance.
ASM: অ্যান্টিমাইক্ৰবিক প্ৰতিৰোধৰ মোকাবিলা কৰিবলৈ এখন ৰাষ্ট্ৰীয় টাস্ক ফৰ্চ গঠন কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  90%|████████████████████▌  | 896/1000 [06:30<00:40,  2.54it/s]

[896/1000]
EN: The Health Ministry conducted audits to improve quality standards in government hospitals.
ASM: স্বাস্থ্য মন্ত্ৰালয়ে চৰকাৰী চিকিৎসালয়সমূহৰ গুণগত মান উন্নত কৰিবলৈ অডিট কৰিছিল ।
--------------------------------------------------

Translating ASM:  90%|████████████████████▋  | 897/1000 [06:31<00:42,  2.40it/s]

[897/1000]
EN: India expanded maternal nutrition programs to reduce anemia among pregnant women.
ASM: ভাৰতে গৰ্ভৱতী মহিলাসকলৰ মাজত এনিমিয়া হ্ৰাস কৰিবলৈ মাতৃ পুষ্টি কাৰ্যসূচী সম্প্ৰসাৰিত কৰিছিল ।
--------------------------------------------------

Translating ASM:  90%|████████████████████▋  | 898/1000 [06:31<00:37,  2.69it/s]

[898/1000]
EN: A state government announced free health checkups for senior citizens.
ASM: এখন ৰাজ্য চৰকাৰে জ্যেষ্ঠ নাগৰিকসকলৰ বাবে বিনামূলীয়া স্বাস্থ্য পৰীক্ষা ঘোষণা কৰিছিল ।
--------------------------------------------------

Translating ASM:  90%|████████████████████▋  | 899/1000 [06:31<00:39,  2.53it/s]

[899/1000]
EN: Indian healthcare startups focused on digital solutions for chronic disease management.
ASM: ভাৰতীয় স্বাস্থ্যসেৱা ষ্টাৰ্টআপসমূহে চিৰস্থায়ী ৰোগ ব্যৱস্থাপনাৰ বাবে ডিজিটেল সমাধানৰ ওপৰত গুৰুত্ব আৰোপ কৰিছে ।
--------------------------------------------------

Translating ASM:  90%|████████████████████▋  | 900/1000 [06:32<00:39,  2.56it/s]

[900/1000]
EN: The National Health Policy emphasized universal access to affordable healthcare services.
ASM: ৰাষ্ট্ৰীয় স্বাস্থ্য নীতিত সুলভ মূল্যত স্বাস্থ্যসেৱাৰ সর্বজনীন প্ৰবেশৰ ওপৰত গুৰুত্ব আৰোপ কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  90%|████████████████████▋  | 901/1000 [06:32<00:41,  2.39it/s]

[901/1000]
EN: Public health officials promoted lifestyle changes to reduce cardiovascular disease risks.
ASM: ৰাজহুৱা স্বাস্থ্য বিষয়াসকলে হৃদৰোগজনিত ৰোগৰ আশংকা হ্ৰাস কৰিবলৈ জীৱনশৈলীৰ পৰিৱৰ্তনক প্ৰচাৰ কৰিছিল ।
--------------------------------------------------

Translating ASM:  90%|████████████████████▋  | 902/1000 [06:33<00:42,  2.32it/s]

[902/1000]
EN: India improved cold chain infrastructure to ensure vaccine safety and effectiveness.
ASM: ভাৰতে ভেকছিনৰ সুৰক্ষা আৰু কাৰ্যকাৰিতা নিশ্চিত কৰিবলৈ কোল্ড চেিন আন্তঃগাঁথনি উন্নত কৰিছিল ।
--------------------------------------------------

Translating ASM:  90%|████████████████████▊  | 903/1000 [06:33<00:41,  2.36it/s]

[903/1000]
EN: A medical research institute in India studied long-term effects of COVID-19 infections.
ASM: ভাৰতৰ এটা চিকিৎসা গৱেষণা প্ৰতিষ্ঠানে কোভিড-১৯ সংক্ৰমণৰ দীৰ্ঘকালীন প্ৰভাৱ অধ্যয়ন কৰিছিল ।
--------------------------------------------------

Translating ASM:  90%|████████████████████▊  | 904/1000 [06:34<00:39,  2.43it/s]

[904/1000]
EN: The government strengthened referral systems between primary and tertiary healthcare centers.
ASM: চৰকাৰে প্ৰাথমিক আৰু উচ্চতৰ মাধ্যমিক স্বাস্থ্যসেৱা কেন্দ্ৰসমূহৰ মাজত প্ৰসংগ প্ৰণালীক শক্তিশালী কৰিছিল ।
--------------------------------------------------

Translating ASM:  90%|████████████████████▊  | 905/1000 [06:34<00:36,  2.58it/s]

[905/1000]
EN: Health workers received additional training to improve immunization coverage.
ASM: স্বাস্থ্য কৰ্মীসকলে প্ৰতিষেধক সুৰক্ষা উন্নত কৰিবলৈ অতিৰিক্ত প্ৰশিক্ষণ লাভ কৰিছিল ।
--------------------------------------------------

Translating ASM:  91%|████████████████████▊  | 906/1000 [06:34<00:35,  2.64it/s]

[906/1000]
EN: India expanded newborn care units to reduce infant mortality rates.
ASM: ভাৰতে শিশু মৃত্যুৰ হাৰ হ্ৰাস কৰিবলৈ নৱজাতকৰ যত্ন গোট সম্প্ৰসাৰিত কৰিছিল ।
--------------------------------------------------

Translating ASM:  91%|████████████████████▊  | 907/1000 [06:35<00:35,  2.60it/s]

[907/1000]
EN: The Ministry of Health collaborated with states to improve sanitation and hygiene practices.
ASM: স্বাস্থ্য মন্ত্ৰালয়ে ৰাজ্যসমূহৰ সৈতে অনাময় আৰু স্বাস্থ্য ব্যৱস্থাৰ উন্নতিৰ বাবে সহযোগিতা কৰিছে ।
--------------------------------------------------

Translating ASM:  91%|████████████████████▉  | 908/1000 [06:35<00:34,  2.65it/s]

[908/1000]
EN: Indian hospitals increased investment in critical care facilities.
ASM: ভাৰতীয় চিকিৎসালয়সমূহে জৰুৰীকালীন চিকিৎসা সুবিধাসমূহত বিনিয়োগ বৃদ্ধি কৰিছে ।
--------------------------------------------------

Translating ASM:  91%|████████████████████▉  | 909/1000 [06:35<00:32,  2.76it/s]

[909/1000]
EN: A health awareness campaign encouraged working professionals to undergo regular health screenings.
ASM: এটা স্বাস্থ্য সজাগতা অভিযানে কৰ্মৰত বিশেষজ্ঞসকলক নিয়মীয়াকৈ স্বাস্থ্য পৰীক্ষা কৰিবলৈ উৎসাহিত কৰিছিল ।
--------------------------------------------------

Translating ASM:  91%|████████████████████▉  | 910/1000 [06:36<00:30,  2.92it/s]

[910/1000]
EN: The government introduced reforms to regulate private healthcare pricing.
ASM: চৰকাৰে ব্যক্তিগত স্বাস্থ্যসেৱাৰ মূল্য নিয়ন্ত্ৰণৰ বাবে সংস্কাৰ প্ৰৱৰ্তন কৰিছিল ।
--------------------------------------------------

Translating ASM:  91%|████████████████████▉  | 911/1000 [06:36<00:30,  2.89it/s]

[911/1000]
EN: India enhanced its disease reporting systems to improve outbreak preparedness.
ASM: ভাৰতে প্ৰাদুৰ্ভাৱৰ প্ৰস্তুতি উন্নত কৰিবলৈ ইয়াৰ ৰোগ প্ৰতিবেদন প্ৰণালীক উন্নত কৰিছিল ।
--------------------------------------------------

Translating ASM:  91%|████████████████████▉  | 912/1000 [06:36<00:29,  2.96it/s]

[912/1000]
EN: Health experts recommended increased funding for mental health research in India.
ASM: স্বাস্থ্য বিশেষজ্ঞসকলে ভাৰতত মানসিক স্বাস্থ্য গৱেষণাৰ বাবে পুঁজি বৃদ্ধিৰ পৰামৰ্শ দিছে ।
--------------------------------------------------

Translating ASM:  91%|████████████████████▉  | 913/1000 [06:37<00:29,  2.91it/s]

[913/1000]
EN: The National Health Authority reviewed feedback to improve beneficiary services.
ASM: ৰাষ্ট্ৰীয় স্বাস্থ্য কৰ্তৃপক্ষই হিতাধিকাৰী সেৱা উন্নত কৰিবলৈ মতামত পৰ্যালোচনা কৰে ।
--------------------------------------------------

Translating ASM:  91%|█████████████████████  | 914/1000 [06:37<00:30,  2.80it/s]

[914/1000]
EN: India strengthened disaster preparedness in hospitals for medical emergencies.
ASM: ভাৰতে চিকিৎসা জৰুৰীকালীন অৱস্থাৰ বাবে চিকিৎসালয়সমূহত দুৰ্যোগৰ প্রস্তুতি শক্তিশালী কৰিছে ।
--------------------------------------------------

Translating ASM:  92%|█████████████████████  | 915/1000 [06:37<00:30,  2.76it/s]

[915/1000]
EN: A state government launched a nutrition program for school children.
ASM: এখন ৰাজ্য চৰকাৰে স্কুলীয়া লৰা-ছোৱালীৰ বাবে পুষ্টিমূলক কাৰ্যসূচী আৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  92%|█████████████████████  | 916/1000 [06:38<00:31,  2.63it/s]

[916/1000]
EN: The Health Ministry emphasized community participation in strengthening public healthcare systems.
ASM: স্বাস্থ্য মন্ত্ৰালয়ে ৰাজহুৱা স্বাস্থ্যসেৱা ব্যৱস্থাক শক্তিশালী কৰাত সম্প্ৰদায়ৰ অংশগ্ৰহণৰ ওপৰত গুৰুত্ব আৰোপ কৰে ।
--------------------------------------------------

Translating ASM:  92%|█████████████████████  | 917/1000 [06:38<00:35,  2.34it/s]

[917/1000]
EN: The Union Budget 2026 increased the healthcare allocation to 1,06,530 crore rupees for the Ministry of Health and Family Welfare.
ASM: কেন্দ্ৰীয় বাজেট ২০২৬ত স্বাস্থ্য আৰু পৰিয়াল কল্যান মন্ত্ৰালয়ৰ বাবে স্বাস্থ্যসেৱা আৱণ্টন বৃদ্ধি কৰি ১০৬,৫৩০ কোটি টকা কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  92%|█████████████████████  | 918/1000 [06:39<00:35,  2.29it/s]

[918/1000]
EN: Finance Minister Nirmala Sitharaman announced a 10 percent hike in the health budget compared to the previous fiscal year.
ASM: বিত্তমন্ত্ৰী নিৰ্মলা সীতাৰমণে পূৰ্বৰ বিত্তীয় বৰ্ষৰ তুলনাত স্বাস্থ্য বাজেট ১০ শতাংশ বৃদ্ধি কৰাৰ কথা ঘোষণা কৰে ।
--------------------------------------------------

Translating ASM:  92%|█████████████████████▏ | 919/1000 [06:39<00:34,  2.33it/s]

[919/1000]
EN: The Government of India launched the Biopharma SHAKTI initiative with an outlay of 10,000 crore rupees over five years.
ASM: ভাৰত চৰকাৰে পাঁচ বছৰত ১০ হাজাৰ কোটি টকা ব্যয় কৰি বায়োফাৰ্মা শাক্তি প্ৰচেষ্টাৰ শুভাৰম্ভ কৰিছে ।
--------------------------------------------------

Translating ASM:  92%|█████████████████████▏ | 920/1000 [06:40<00:36,  2.17it/s]

[920/1000]
EN: The Biopharma SHAKTI scheme aims to strengthen the domestic production of biologics and biosimilars in India.
ASM: বায়ফাৰ্মা শাক্তি আঁচনিৰ লক্ষ্য হৈছে ভাৰতত জৈৱিক পদাৰ্থ আৰু জৈৱসদৃশ্য পদাৰ্থৰ ঘৰুৱা উৎপাদন শক্তিশালী কৰা ।
--------------------------------------------------

Translating ASM:  92%|█████████████████████▏ | 921/1000 [06:40<00:36,  2.14it/s]

[921/1000]
EN: The Ministry of Health will support states in establishing five new regional medical hubs through private-sector partnerships.
ASM: স্বাস্থ্য মন্ত্ৰালয়ে ব্যক্তিগত খণ্ডৰ অংশীদাৰিত্বৰ জৰিয়তে পাঁচটা নতুন আঞ্চলিক চিকিৎসা কেন্দ্ৰ স্থাপনত ৰাজ্যসমূহক সমৰ্থন কৰিব ।
--------------------------------------------------

Translating ASM:  92%|█████████████████████▏ | 922/1000 [06:41<00:36,  2.11it/s]

[922/1000]
EN: These five regional medical hubs will combine medical services, educational facilities, and research centers under one roof.
ASM: এই পাঁচটা আঞ্চলিক চিকিৎসা কেন্দ্ৰই চিকিৎসা সেৱা, শৈক্ষিক সুবিধা আৰু গৱেষণা কেন্দ্ৰক একেটা ছাদৰ তলত একত্ৰিত কৰিব ।
--------------------------------------------------

Translating ASM:  92%|█████████████████████▏ | 923/1000 [06:41<00:37,  2.04it/s]

[923/1000]
EN: The Union Budget 2026 proposed the establishment of NIMHANS 2.0 in North India to address mental health needs.
ASM: কেন্দ্ৰীয় বাজেট ২০২৬ত উত্তৰ ভাৰতত মানসিক স্বাস্থ্যৰ প্ৰয়োজনীয়তা পূৰণৰ বাবে নিমহান্স ২.০ স্থাপনৰ প্ৰস্তাৱ দাখিল কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  92%|█████████████████████▎ | 924/1000 [06:42<00:36,  2.06it/s]

[924/1000]
EN: The Government plans to upgrade the National Mental Health Institutes in Ranchi and Tezpur into regional apex institutions.
ASM: চৰকাৰে ৰাঁচী আৰু তেজপুৰত থকা ৰাষ্ট্ৰীয় মানসিক স্বাস্থ্য প্ৰতিষ্ঠানসমূহক আঞ্চলিক শীৰ্ষ প্ৰতিষ্ঠানলৈ উন্নীত কৰাৰ পৰিকল্পনা কৰিছে ।
--------------------------------------------------

Translating ASM:  92%|█████████████████████▎ | 925/1000 [06:42<00:35,  2.10it/s]

[925/1000]
EN: The Ministry of Health allocated 3,477 crore rupees to the National AIDS and STD Control Programme.
ASM: স্বাস্থ্য মন্ত্ৰালয়ে ৰাষ্ট্ৰীয় এইডছ আৰু এছটিডি নিয়ন্ত্ৰণ কাৰ্যসূচীৰ বাবে ৩৪৭৭ কোটি টকা আৱণ্টন কৰিছে ।
--------------------------------------------------

Translating ASM:  93%|█████████████████████▎ | 926/1000 [06:43<00:35,  2.08it/s]

[926/1000]
EN: The Union Budget 2026 provided a full customs duty exemption on 17 essential cancer-related drugs.
ASM: কেন্দ্ৰীয় বাজেট ২০২৬ত কৰ সম্পৰ্কীয় ১৭টা অত্যাৱশ্যকীয় ঔষধৰ ওপৰত সম্পূৰ্ণ শুল্ক ৰেহাই প্ৰদান কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  93%|█████████████████████▎ | 927/1000 [06:43<00:34,  2.09it/s]

[927/1000]
EN: Seven additional rare diseases were added to the list for easier personal import of life-saving medicines.
ASM: জীৱন-ৰক্ষক ঔষধৰ সহজ ব্যক্তিগত আমদানিৰ বাবে অতিৰিক্ত সাতটা বিৰল ৰোগ তালিকাত অন্তৰ্ভুক্ত কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  93%|█████████████████████▎ | 928/1000 [06:44<00:33,  2.13it/s]

[928/1000]
EN: The Government announced a 50 percent expansion in emergency and trauma care capacity at district hospitals.
ASM: চৰকাৰে জিলা চিকিৎসালয়সমূহত জৰুৰীকালীন আৰু আঘাতৰ যত্নৰ ক্ষমতা ৫০ শতাংশ বৃদ্ধি কৰাৰ কথা ঘোষণা কৰে ।
--------------------------------------------------

Translating ASM:  93%|█████████████████████▎ | 929/1000 [06:44<00:33,  2.15it/s]

[929/1000]
EN: The Ministry of Health intends to establish dedicated emergency and trauma care centers in every district hospital.
ASM: স্বাস্থ্য মন্ত্ৰালয়ে প্ৰতিখন জিলা চিকিৎসালয়ত বিশেষ জৰুৰীকালীন আৰু আঘাতৰ যত্ন কেন্দ্ৰ স্থাপনৰ পৰিকল্পনা কৰিছে ।
--------------------------------------------------

Translating ASM:  93%|█████████████████████▍ | 930/1000 [06:45<00:33,  2.12it/s]

[930/1000]
EN: The Pradhan Mantri Jan Arogya Yojana received an increased allocation of 9,500 crore rupees to expand coverage.
ASM: প্ৰধানমন্ত্ৰী জন আৰোগ্য যোজনাৰ পৰিসৰ সম্প্ৰসাৰণৰ বাবে ৯৫০০ কোটি টকাৰ বৰ্দ্ধিত আৱণ্টন লাভ কৰিছে ।
--------------------------------------------------

Translating ASM:  93%|█████████████████████▍ | 931/1000 [06:45<00:32,  2.15it/s]

[931/1000]
EN: The National Health Mission was allocated 39,390 crore rupees to enhance primary healthcare delivery across states.
ASM: ৰাষ্ট্ৰীয় স্বাস্থ্য অভিযানত ৰাজ্যসমূহত প্ৰাথমিক স্বাস্থ্যসেৱা প্ৰদান বৃদ্ধিৰ বাবে ৩৯,৩৯০ কোটি টকা ধাৰ্য কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  93%|█████████████████████▍ | 932/1000 [06:45<00:28,  2.35it/s]

[932/1000]
EN: The Government proposed a plan to add 100,000 allied health professionals over the next five years.
ASM: চৰকাৰে পৰৱৰ্তী পাঁচ বছৰত ১০০ হাজাৰ স্বাস্থ্য কৰ্মী যোগ কৰাৰ পৰিকল্পনা প্ৰস্তাৱ আগবঢ়ায় ।
--------------------------------------------------

Translating ASM:  93%|█████████████████████▍ | 933/1000 [06:46<00:28,  2.33it/s]

[933/1000]
EN: The Ministry of Health will upgrade existing institutions for allied health professionals to improve training standards.
ASM: স্বাস্থ্য মন্ত্ৰালয়ে প্ৰশিক্ষণৰ মান উন্নত কৰাৰ বাবে সংশ্লিষ্ট স্বাস্থ্য কৰ্মীসকলৰ বাবে বিদ্যমান প্ৰতিষ্ঠানসমূহৰ উন্নতি কৰিব ।
--------------------------------------------------

Translating ASM:  93%|█████████████████████▍ | 934/1000 [06:46<00:28,  2.34it/s]

[934/1000]
EN: The Union Budget 2026 earmarked 4,821 crore rupees specifically for the Department of Health Research.
ASM: কেন্দ্ৰীয় বাজেট ২০২৬ত স্বাস্থ্য গৱেষণা বিভাগৰ বাবে ৪৮২১ কোটি টকা ধাৰ্য কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  94%|█████████████████████▌ | 935/1000 [06:47<00:29,  2.20it/s]

[935/1000]
EN: Finance Minister Nirmala Sitharaman proposed the creation of three new All India Institutes of Ayurveda.
ASM: বিত্তমন্ত্ৰী নিৰ্মলা সীতাৰমণে তিনিটা নতুন অল ইণ্ডিয়া ইনষ্টিটিউট অৱ আয়ুৰ্বেদ স্থাপনৰ প্ৰস্তাৱ আগবঢ়ায় ।
--------------------------------------------------

Translating ASM:  94%|█████████████████████▌ | 936/1000 [06:47<00:29,  2.17it/s]

[936/1000]
EN: The Government plans to train 1.5 lakh caregivers in allied skills such as geriatric care and yoga.
ASM: চৰকাৰে ১.৫ লাখ পৰিচৰকক জ্যেষ্ঠ চিকিৎসক আৰু যোগৰ দৰে আনুষংগিক দক্ষতাত প্ৰশিক্ষণ দিয়াৰ পৰিকল্পনা কৰিছে ।
--------------------------------------------------

Translating ASM:  94%|█████████████████████▌ | 937/1000 [06:48<00:29,  2.12it/s]

[937/1000]
EN: The Ayushman Bharat Digital Mission received 350 crore rupees to improve digital health record interoperability.
ASM: ডিজিটেল স্বাস্থ্য ৰেকৰ্ডৰ আন্তঃগাঁথনি উন্নত কৰাৰ বাবে আয়ুষ্মান ভাৰত ডিজিটেল মিছনে ৩৫০ কোটি টকা লাভ কৰিছে ।
--------------------------------------------------

Translating ASM:  94%|█████████████████████▌ | 938/1000 [06:48<00:30,  2.05it/s]

[938/1000]
EN: The Ministry of Health aims to reduce import dependence by supporting the domestic manufacturing of high-value biopharmaceuticals.
ASM: স্বাস্থ্য মন্ত্ৰালয়ে উচ্চ মূল্যৰ জৈৱ ঔষধৰ দেশীয় উৎপাদনক সমৰ্থন কৰি আমদানিৰ ওপৰত নিৰ্ভৰশীলতা হ্ৰাস কৰাৰ লক্ষ্য লৈছে ।
--------------------------------------------------

Translating ASM:  94%|█████████████████████▌ | 939/1000 [06:49<00:31,  1.93it/s]

[939/1000]
EN: The Union Budget 2026 focus shifted from a curative model to a prevention-first and holistic wellness approach.
ASM: ২০২৬ চনৰ কেন্দ্ৰীয় বাজেটত এটা আৰোগ্যমূলক আৰ্হিৰ পৰা এটা প্ৰতিৰোধ-প্ৰথম আৰু সামগ্ৰিক সুস্থতা পদ্ধতিৰ ওপৰত গুৰুত্ব আৰোপ কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  94%|█████████████████████▌ | 940/1000 [06:49<00:32,  1.87it/s]

[940/1000]
EN: The Government will establish 1,000 accredited clinical trial sites to position India as a global research destination.
ASM: ভাৰতক এক বৈশ্বিক গৱেষণা গন্তব্য স্থান হিচাপে গঢ়ি তোলাৰ বাবে চৰকাৰে ১ হাজাৰ অনুমোদিত ক্লিনিক্যাল ট্ৰায়েল ছাইট স্থাপন কৰিব ।
--------------------------------------------------

Translating ASM:  94%|█████████████████████▋ | 941/1000 [06:50<00:29,  2.00it/s]

[941/1000]
EN: The Central Drugs Standard Control Organisation will receive more specialized personnel to improve regulatory efficiency.
ASM: কেন্দ্ৰীয় ড্ৰাগছ ষ্টেণ্ডাৰ্ড নিয়ন্ত্ৰণ সংস্থাই নিয়ন্ত্ৰণ দক্ষতা উন্নত কৰিবলৈ অধিক বিশেষজ্ঞ কৰ্মচাৰী লাভ কৰিব ।
--------------------------------------------------

Translating ASM:  94%|█████████████████████▋ | 942/1000 [06:50<00:31,  1.87it/s]

[942/1000]
EN: Artificial Intelligence is now being used by Indian radiologists to detect early signs of lung cancer from medical images.
ASM: কৃত্ৰিম বুদ্ধিমত্তাক এতিয়া ভাৰতীয় ৰেডিঅ'লজিষ্টসকলে চিকিৎসা ছবিৰ পৰা ফুসফুৰৰ কৰ্কট ৰোগৰ প্ৰাৰম্ভিক লক্ষণ চিনাক্ত কৰিবলৈ ব্যৱহাৰ কৰি আছে ।
--------------------------------------------------

Translating ASM:  94%|█████████████████████▋ | 943/1000 [06:51<00:31,  1.81it/s]

[943/1000]
EN: Qure.ai implemented AI-driven imaging solutions to facilitate faster diagnosis of strokes in rural Indian hospitals.
ASM: গ্ৰামাঞ্চলৰ ভাৰতীয় চিকিৎসালয়সমূহত ষ্ট্ৰোকৰ দ্ৰুত নিৰীক্ষণৰ বাবে কুইৰ ডট এয়ে এআই চালিত ইমেজিং সমাধান ৰূপায়ণ কৰিছিল ।
--------------------------------------------------

Translating ASM:  94%|█████████████████████▋ | 944/1000 [06:52<00:32,  1.74it/s]

[944/1000]
EN: Indian healthcare providers are adopting "Actionable AI" to provide predictive health roadmaps instead of simple lab reports.
ASM: ভাৰতীয় স্বাস্থ্যসেৱা প্ৰদানকাৰীসকলে সহজ লেব ৰিপৰ্টৰ পৰিৱৰ্তে ভৱিষ্যতবাণীমূলক স্বাস্থ্য ৰোডমেপ প্ৰদান কৰিবলৈ এক্টেবল এআই গ্ৰহণ কৰি আছে ।
--------------------------------------------------

Translating ASM:  94%|█████████████████████▋ | 945/1000 [06:52<00:33,  1.65it/s]

[945/1000]
EN: The use of wearables in India is evolving from basic fitness tracking to clinical-grade monitoring of heart rhythm.
ASM: ভাৰতত পিন্ধা সামগ্ৰীৰ ব্যৱহাৰ মৌলিক ফিটনেছ ট্ৰেকিংৰ পৰা হৃদযন্ত্ৰৰ গতিৰ ক্লিনিকেল-গ্ৰেড নিৰীক্ষণলৈ বিকশিত হৈছে ।
--------------------------------------------------

Translating ASM:  95%|█████████████████████▊ | 946/1000 [06:53<00:32,  1.64it/s]

[946/1000]
EN: Medical technology startups in India are developing microfluidic devices that conduct complex tests on a single drop of blood.
ASM: ভাৰতত চিকিৎসা প্ৰযুক্তিৰ ষ্টাৰ্টআপসমূহে মাইক্ৰফ্লুইডিক ডিভাইচ বিকশিত কৰি আছে যিবোৰে এক টোপাল তেজৰ জটিল পৰীক্ষা কৰে ।
--------------------------------------------------

Translating ASM:  95%|█████████████████████▊ | 947/1000 [06:54<00:32,  1.66it/s]

[947/1000]
EN: The Indian MedTech sector is projected to reach a market value of 50 billion dollars by the end of 2026.
ASM: ভাৰতীয় মেডটেক খণ্ডটো ২০২৬ চনৰ শেষৰফালে ৫০ বিলিয়ন ডলাৰৰ বজাৰ মূল্যত উপনীত হ'ব বুলি অনুমান কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  95%|█████████████████████▊ | 948/1000 [06:54<00:31,  1.65it/s]

[948/1000]
EN: Hospitals in Tier 2 cities are using predictive analytics to optimize patient flow and reduce waiting times.
ASM: স্তৰ 2 চহৰত থকা চিকিৎসালয়সমূহে ৰোগীৰ প্ৰবাহ অনুকূল কৰিবলৈ আৰু অপেক্ষাৰ সময় হ্ৰাস কৰিবলৈ ভৱিষ্যতবাণীমূলক বিশ্লেষণ ব্যৱহাৰ কৰি আছে ।
--------------------------------------------------

Translating ASM:  95%|█████████████████████▊ | 949/1000 [06:55<00:29,  1.74it/s]

[949/1000]
EN: Telemedicine services are expanding in remote regions to connect rural patients with specialists in metropolitan cities.
ASM: গ্ৰামাঞ্চলৰ ৰোগীসকলক মহানগৰখনৰ বিশেষজ্ঞসকলৰ সৈতে সংযোগ কৰিবলৈ দূৰৱৰ্তী অঞ্চলত টেলিমেডিচিন সেৱা সম্প্ৰসাৰিত হৈছে ।
--------------------------------------------------

Translating ASM:  95%|█████████████████████▊ | 950/1000 [06:55<00:29,  1.71it/s]

[950/1000]
EN: The Ayushman Bharat Health Account (ABHA) system allows patients to share digital health records securely with doctors.
ASM: আয়ুষ্মান ভাৰত স্বাস্থ্য একাউণ্ট (এবিএইচএ) ব্যৱস্থাই ৰোগীসকলক চিকিৎসকৰ সৈতে ডিজিটেল স্বাস্থ্য ৰেকৰ্ড সুৰক্ষিতভাৱে শ্বেয়াৰ কৰিবলৈ অনুমতি দিয়ে ।
--------------------------------------------------

Translating ASM:  95%|█████████████████████▊ | 951/1000 [06:56<00:27,  1.81it/s]

[951/1000]
EN: Robotic-assisted surgery is becoming more common in private Indian hospitals for complex urological procedures.
ASM: জটিল মূত্ৰবিজ্ঞান পদ্ধতিৰ বাবে বেচৰকাৰী ভাৰতীয় চিকিৎসালয়ত ৰবট সহায়ক অস্ত্ৰোপচাৰ অধিক প্ৰচলিত হৈ আছে ।
--------------------------------------------------

Translating ASM:  95%|█████████████████████▉ | 952/1000 [06:56<00:26,  1.80it/s]

[952/1000]
EN: Many Indian diagnostic labs are now using genomic testing as a primary triage tool for chronic diseases.
ASM: বহুতো ভাৰতীয় ডায়াগনষ্টিক পৰীক্ষাগাৰে এতিয়া চিৰস্থায়ী ৰোগৰ বাবে প্ৰাথমিক ট্ৰায়েজ সঁজুলি হিচাপে জেনেমিক পৰীক্ষা ব্যৱহাৰ কৰি আছে ।
--------------------------------------------------

Translating ASM:  95%|█████████████████████▉ | 953/1000 [06:57<00:26,  1.76it/s]

[953/1000]
EN: Healthcare organizations are deploying AI agents to handle administrative tasks like insurance pre-authorizations and billing.
ASM: স্বাস্থ্যসেৱা সংস্থাসমূহে বীমা প্ৰাক-অনুমোদন আৰু বিলিংৰ দৰে প্ৰশাসনিক কামবোৰ মোকাবিলা কৰিবলৈ এআই এজেন্ট নিয়োগ কৰি আছে ।
--------------------------------------------------

Translating ASM:  95%|█████████████████████▉ | 954/1000 [06:57<00:26,  1.73it/s]

[954/1000]
EN: Smart sensors in Indian ICUs are reducing unplanned admissions by providing continuous real-time monitoring of vitals.
ASM: ভাৰতীয় আইচিইউত থকা স্মাৰ্ট ছেন্সৰে নিৰন্তৰ ৰিয়েল টাইম মনিটৰিঙৰ জৰিয়তে অপ্ৰত্যাশিত ভৰ্তি হ্ৰাস কৰিছে ।
--------------------------------------------------

Translating ASM:  96%|█████████████████████▉ | 955/1000 [06:58<00:24,  1.82it/s]

[955/1000]
EN: The digital transformation of clinical trials in India is enabling remote patient monitoring through mobile devices.
ASM: ভাৰতত ক্লিনিকাল ট্ৰায়েলৰ ডিজিটেল ৰূপান্তৰে মোবাইল ডিভাইছৰ জৰিয়তে ৰোগীৰ ৰিমোট মনিটৰিঙৰ সুবিধা প্ৰদান কৰিছে ।
--------------------------------------------------

Translating ASM:  96%|█████████████████████▉ | 956/1000 [06:59<00:24,  1.78it/s]

[956/1000]
EN: Indian pharmaceutical companies are integrating AI into their quality control systems to ensure paperless and compliant workflows.
ASM: ভাৰতীয় ঔষধ কোম্পানীসমূহে তেওঁলোকৰ গুণগত নিয়ন্ত্ৰণ ব্যৱস্থাত এআইক সংহত কৰি কাগজবিহীন আৰু অনুকূল কাম প্ৰবাহ সুনিশ্চিত কৰিছে ।
--------------------------------------------------

Translating ASM:  96%|██████████████████████ | 957/1000 [06:59<00:23,  1.84it/s]

[957/1000]
EN: Low-cost needle-free drug delivery technologies are gaining traction for vaccine administration in pediatric clinics.
ASM: শিশু চিকিৎসালয়ত ভেকছিন প্ৰশাসনৰ বাবে কম খৰচী সুই মুক্ত ঔষধ বিতৰণ প্ৰযুক্তিয়ে আকৰ্ষণ লাভ কৰিছে ।
--------------------------------------------------

Translating ASM:  96%|██████████████████████ | 958/1000 [07:00<00:22,  1.91it/s]

[958/1000]
EN: Public health experts launched India's first Public Health Monitor to track real-time health outcomes across states.
ASM: জনস্বাস্থ্য বিশেষজ্ঞসকলে ৰাজ্যসমূহত স্বাস্থ্যৰ ফলাফল ৰিয়েল টাইমত ট্ৰেক কৰিবলৈ ভাৰতৰ প্ৰথমটো জনস্বাস্থ্য নিৰীক্ষণ আৰম্ভ কৰে ।
--------------------------------------------------

Translating ASM:  96%|██████████████████████ | 959/1000 [07:00<00:19,  2.09it/s]

[959/1000]
EN: Specialized medical tourism facilitation centers will be integrated into the new regional medical hubs.
ASM: নতুন আঞ্চলিক চিকিৎসা কেন্দ্ৰসমূহত বিশেষ চিকিৎসা পৰ্যটন সুবিধা কেন্দ্ৰসমূহ সংহত কৰা হব ।
--------------------------------------------------

Translating ASM:  96%|██████████████████████ | 960/1000 [07:00<00:19,  2.10it/s]

[960/1000]
EN: Indian doctors are using hyper-personalized medicine to tailor treatments based on the genetic profile of individual patients.
ASM: ভাৰতীয় চিকিৎসকসকলে অতি-ব্যক্তিগত ঔষধ ব্যৱহাৰ কৰি ৰোগীৰ জেনেটিক প্ৰফাইলৰ ওপৰত আধাৰিত চিকিৎসাৰ ব্যৱস্থা কৰিছে ।
--------------------------------------------------

Translating ASM:  96%|██████████████████████ | 961/1000 [07:01<00:18,  2.17it/s]

[961/1000]
EN: The adoption of 5G technology is improving the speed and reliability of remote robotic surgeries in India.
ASM: ৫জি প্ৰযুক্তিৰ গ্রহণে ভাৰতত দূৰৱৰ্তী ৰবোটিক অস্ত্ৰোপচাৰৰ গতি আৰু বিশ্বাসযোগ্যতা উন্নত কৰিছে ।
--------------------------------------------------

Translating ASM:  96%|██████████████████████▏| 962/1000 [07:01<00:18,  2.02it/s]

[962/1000]
EN: 20 All India Institutes of Medical Sciences signed a memorandum to form a pan-India research consortium.
ASM: ২০ সৰ্বভাৰতীয় চিকিৎসা বিজ্ঞান প্ৰতিষ্ঠানসমূহে এখন সৰ্বভাৰতীয় গৱেষণা সন্মিলন গঠনৰ বাবে এক স্মাৰকপত্ৰত স্বাক্ষৰ কৰিছে ।
--------------------------------------------------

Translating ASM:  96%|██████████████████████▏| 963/1000 [07:02<00:18,  1.96it/s]

[963/1000]
EN: The AIIMS research consortium will focus on multicentric clinical trials for low-cost cancer treatments.
ASM: এইমছ গৱেষণা সমিতিয়ে কম খৰচত কৰ্কট ৰোগৰ চিকিৎসাৰ বাবে বহুকেন্দ্ৰীয় ক্লিনিকেল পৰীক্ষণত গুৰুত্ব দিব ।
--------------------------------------------------

Translating ASM:  96%|██████████████████████▏| 964/1000 [07:02<00:18,  1.94it/s]

[964/1000]
EN: A medical student at the Dharwad Institute of Mental Health unfortunately committed suicide in early February.
ASM: ধাৰৱাদ ইনষ্টিটিউট অৱ মেণ্টেল হেল্থৰ এগৰাকী চিকিৎসা শিক্ষাৰ্থীয়ে দুৰ্ভাগ্যজনকভাৱে ফেব্ৰুৱাৰীৰ আৰম্ভণিতে আত্মহত্যা কৰিছিল ।
--------------------------------------------------

Translating ASM:  96%|██████████████████████▏| 965/1000 [07:03<00:17,  1.98it/s]

[965/1000]
EN: The Maharashtra University of Health Sciences revoked the affiliation of Sinhgad Dental College over regulatory violations.
ASM: নিয়ম উলংঘনৰ বাবে মহাৰাষ্ট্ৰ বিশ্ববিদ্যালয় অৱ হেল্থ ছায়েন্সে ছিংগাড ডেণ্টেল কলেজৰ অনুমোদন বাতিল কৰে ।
--------------------------------------------------

Translating ASM:  97%|██████████████████████▏| 966/1000 [07:03<00:17,  1.98it/s]

[966/1000]
EN: A 40-year-old urologist suffered a cardiac arrest while speaking at an international conference in Indore.
ASM: ইন্দোৰত এখন আন্তঃৰাষ্ট্ৰীয় সন্মিলনত ভাষণ দিওঁতে এগৰাকী ৪০ বছৰীয়া মূত্ৰবিজ্ঞানী হৃদযন্ত্ৰৰোগত আক্ৰান্ত হৈছিল ।
--------------------------------------------------

Translating ASM:  97%|██████████████████████▏| 967/1000 [07:04<00:17,  1.93it/s]

[967/1000]
EN: The District Consumer Commission in Kannur held a surgeon liable for negligence in a varicose vein treatment.
ASM: কাননুৰ জিলা উপভোক্তা আয়োগে ভেৰিচ ভেনৰ চিকিৎসাত অৱহেলাৰ বাবে এজন চাৰ্জনক দায়বদ্ধ কৰিছিল ।
--------------------------------------------------

Translating ASM:  97%|██████████████████████▎| 968/1000 [07:04<00:16,  1.97it/s]

[968/1000]
EN: Two government doctors in Bhopal were sentenced to prison for securing medical seats with fake domicile certificates.
ASM: ভূপালৰ দুটা চৰকাৰী চিকিৎসকক ভুৱা আবাস প্ৰমাণপত্ৰৰ সৈতে চিকিৎসা আসন সুৰক্ষিত কৰাৰ বাবে কাৰাদণ্ড বিহা হৈছিল ।
--------------------------------------------------

Translating ASM:  97%|██████████████████████▎| 969/1000 [07:05<00:16,  1.85it/s]

[969/1000]
EN: Authorities in Maharashtra are seeking action against a pathologist for signing lab reports without proper registration.
ASM: মহাৰাষ্ট্ৰৰ কৰ্তৃপক্ষই সঠিক পঞ্জীয়নৰ অবিহনে পৰীক্ষাগাৰৰ ৰিপৰ্টত স্বাক্ষৰ কৰাৰ বাবে এজন পেথলজিষ্টৰ বিৰুদ্ধে ব্যৱস্থা বিচাৰিছে ।
--------------------------------------------------

Translating ASM:  97%|██████████████████████▎| 970/1000 [07:06<00:16,  1.80it/s]

[970/1000]
EN: The Central Council for Research in Ayurvedic Sciences signed an agreement to digitize rare Ayurveda manuscripts.
ASM: আয়ুৰ্বেদিক বিজ্ঞানৰ গৱেষণা কেন্দ্ৰীয় পৰিষদে বিৰল আয়ুৰ্বেদিক হস্তাক্ষৰবোৰ ডিজিটেল কৰাৰ বাবে এক চুক্তিত স্বাক্ষৰ কৰিছে ।
--------------------------------------------------

Translating ASM:  97%|██████████████████████▎| 971/1000 [07:06<00:16,  1.79it/s]

[971/1000]
EN: Apollo Hospitals Chairman Dr. Prathap Reddy stated that the 2026 budget strengthens the vision of a healthier India.
ASM: এপলো চিকিৎসালয়ৰ অধ্যক্ষ ড০ প্ৰতাপ ৰেড্ডীয়ে কয় যে ২০২৬ চনৰ বাজেটে এখন সুস্থ ভাৰত গঢ়াৰ দৃষ্টিশক্তি শক্তিশালী কৰে ।
--------------------------------------------------

Translating ASM:  97%|██████████████████████▎| 972/1000 [07:07<00:15,  1.78it/s]

[972/1000]
EN: Max Healthcare plans to expand its robotic-assisted surgery program across its network of hospitals.
ASM: মেক্স হেল্থকেয়াৰে ইয়াৰ চিকিৎসালয়ৰ নেটৱৰ্কত ৰবট সহায়ক অস্ত্ৰোপচাৰ কাৰ্যসূচী সম্প্ৰসাৰিত কৰাৰ পৰিকল্পনা কৰিছে ।
--------------------------------------------------

Translating ASM:  97%|██████████████████████▍| 973/1000 [07:07<00:14,  1.81it/s]

[973/1000]
EN: Health experts warned that the unorganized diagnostic sector in India will face consolidation due to stricter quality norms.
ASM: স্বাস্থ্য বিশেষজ্ঞসকলে সতৰ্ক কৰিছিল যে ভাৰতত অসংগঠিত ৰোগ নিৰ্ণয় খণ্ডটো কঠোৰ মানদণ্ডৰ বাবে একত্ৰিত হোৱাৰ সন্মুখীন হ'ব ।
--------------------------------------------------

Translating ASM:  97%|██████████████████████▍| 974/1000 [07:08<00:13,  1.97it/s]

[974/1000]
EN: The Indian Council of Medical Research received 4,000 crore rupees to bolster indigenous medical research.
ASM: ভাৰতীয় চিকিৎসা গৱেষণা পৰিষদে দেশীয় চিকিৎসা গৱেষণাক শক্তিশালী কৰিবলৈ ৪০০০ কোটি টকা লাভ কৰিছে ।
--------------------------------------------------

Translating ASM:  98%|██████████████████████▍| 975/1000 [07:08<00:12,  2.00it/s]

[975/1000]
EN: Public health officials are drafting a new Planetary Health Policy Framework to address climate-linked diseases.
ASM: জনস্বাস্থ্য বিষয়াসকলে জলবায়ু সম্পৰ্কীয় ৰোগৰ মোকাবিলা কৰিবলৈ এখন নতুন গ্ৰহ স্বাস্থ্য নীতিৰ কাঠামো প্ৰস্তুত কৰি আছে ।
--------------------------------------------------

Translating ASM:  98%|██████████████████████▍| 976/1000 [07:09<00:12,  1.99it/s]

[976/1000]
EN: The Food Safety and Standards Authority of India is working to make healthy food more affordable than unhealthy options.
ASM: ভাৰতৰ খাদ্য সুৰক্ষা আৰু মানদণ্ড কৰ্তৃপক্ষই অস্বাস্থ্যকৰ বিকল্পতকৈ স্বাস্থ্যকৰ খাদ্যক সুলভ কৰি তোলাৰ বাবে কাম কৰি আছে ।
--------------------------------------------------

Translating ASM:  98%|██████████████████████▍| 977/1000 [07:09<00:11,  2.04it/s]

[977/1000]
EN: Researchers at AIIMS Delhi are investigating the use of AI to reduce hospital-acquired infections.
ASM: দিল্লী এইমছৰ গৱেষকসকলে চিকিৎসালয়ত পোৱা সংক্ৰমণ হ্ৰাস কৰিবলৈ এআইৰ ব্যৱহাৰৰ বিষয়ে অনুসন্ধান কৰি আছে ।
--------------------------------------------------

Translating ASM:  98%|██████████████████████▍| 978/1000 [07:10<00:10,  2.01it/s]

[978/1000]
EN: The National AIDS Control Organisation is upgrading blood transfusion services to ensure nationwide safety and availability.
ASM: ৰাষ্ট্ৰীয় এইডছ নিয়ন্ত্ৰণ সংস্থাটোৱে সমগ্ৰ দেশতে সুৰক্ষা আৰু উপলব্ধতা সুনিশ্চিত কৰিবলৈ তেজ সংৰক্ষণ সেৱা উন্নীতকৰণ কৰি আছে ।
--------------------------------------------------

Translating ASM:  98%|██████████████████████▌| 979/1000 [07:10<00:10,  2.02it/s]

[979/1000]
EN: Indian pediatricians noted a rise in parental awareness regarding neurodivergence and behavioral health issues.
ASM: ভাৰতীয় শিশু চিকিৎসকসকলে নিউৰডিভাৰ্জেন্স আৰু আচৰণগত স্বাস্থ্য সমস্যা সন্দৰ্ভত পিতৃ-মাতৃৰ সজাগতাৰ বৃদ্ধিৰ কথা উল্লেখ কৰে ।
--------------------------------------------------

Translating ASM:  98%|██████████████████████▌| 980/1000 [07:11<00:09,  2.08it/s]

[980/1000]
EN: Medical value tourism in India is expected to grow as the government streamlines visa processes for international patients.
ASM: চৰকাৰে আন্তঃৰাষ্ট্ৰীয় ৰোগীসকলৰ বাবে ভিছা প্ৰক্ৰিয়া সৰল কৰাৰ লগে লগে ভাৰতত চিকিৎসা মূল্য পৰ্যটন বৃদ্ধি হোৱাৰ আশা কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  98%|██████████████████████▌| 981/1000 [07:11<00:10,  1.80it/s]

[981/1000]
EN: The WHO Global Traditional Medicine Centre in Jamnagar is being upgraded to improve evidence-based research.
ASM: ডব্লিউএইচঅৰ জামনগৰত থকা গ্লোবাল ট্ৰাডিচনেল মেডিচিন চেণ্টাৰৰ উন্নতি ঘটোৱা হৈছে যাতে প্ৰমাণভিত্তিক গৱেষণা উন্নত কৰিব পৰা যায় ।
--------------------------------------------------

Translating ASM:  98%|██████████████████████▌| 982/1000 [07:12<00:09,  1.85it/s]

[982/1000]
EN: Indian generic manufacturers are preparing for the patent expiry of several major global obesity medications.
ASM: ভাৰতীয় জেনেৰিক নিৰ্মাতাসকলে কেইবাটাও প্ৰধান বিশ্বব্যাপী স্থূলতা ঔষধৰ পেটেণ্টৰ ম্যাদ শেষ হোৱাৰ বাবে প্ৰস্তুতি চলাই আছে ।
--------------------------------------------------

Translating ASM:  98%|██████████████████████▌| 983/1000 [07:12<00:09,  1.83it/s]

[983/1000]
EN: A new digital curriculum was introduced to train public health leaders in epidemiology and modern technology.
ASM: মহামাৰীবিজ্ঞান আৰু আধুনিক প্ৰযুক্তিৰ ক্ষেত্ৰত জনস্বাস্থ্য নেতৃবৃন্দক প্ৰশিক্ষণ দিয়াৰ বাবে এটা নতুন ডিজিটেল পাঠ্যক্ৰম প্ৰৱৰ্তন কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  98%|██████████████████████▋| 984/1000 [07:13<00:08,  1.92it/s]

[984/1000]
EN: The government is upgrading AYUSH pharmacies to ensure higher quality standards for traditional medicines.
ASM: চৰকাৰে পৰম্পৰাগত ঔষধৰ উচ্চ মানদণ্ড সুনিশ্চিত কৰিবলৈ আয়ুষ ঔষধসমূহৰ উন্নতি কৰিছে ।
--------------------------------------------------

Translating ASM:  98%|██████████████████████▋| 985/1000 [07:13<00:07,  1.95it/s]

[985/1000]
EN: Several district hospitals in Uttar Pradesh are now equipped with 24/7 emergency care and trauma units.
ASM: উত্তৰ প্ৰদেশৰ কেইবাখনো জিলা চিকিৎসালয়ত এতিয়া ২৪/৭ জৰুৰীকালীন যত্ন আৰু ট্ৰমা ইউনিট আছে ।
--------------------------------------------------

Translating ASM:  99%|██████████████████████▋| 986/1000 [07:14<00:06,  2.00it/s]

[986/1000]
EN: Private healthcare providers are increasing investments in Tier 3 cities to capture the growing rural market.
ASM: বেচৰকাৰী স্বাস্থ্যসেৱা প্ৰদানকাৰী প্ৰতিষ্ঠানসমূহে গ্ৰাম্য বজাৰ দখল কৰিবলৈ তৃতীয় পৰ্যায়ৰ চহৰসমূহত বিনিয়োগ বৃদ্ধি কৰিছে ।
--------------------------------------------------

Translating ASM:  99%|██████████████████████▋| 987/1000 [07:14<00:06,  2.04it/s]

[987/1000]
EN: The Indian healthcare workforce is being upskilled through new digital certifications in allied health disciplines.
ASM: ভাৰতীয় স্বাস্থ্যসেৱা কৰ্মচাৰীসকলক নতুন ডিজিটেল প্ৰমাণপত্ৰৰ জৰিয়তে সংশ্লিষ্ট স্বাস্থ্য বিদ্যাসমূহত দক্ষতা বৃদ্ধি কৰা হৈছে ।
--------------------------------------------------

Translating ASM:  99%|██████████████████████▋| 988/1000 [07:15<00:05,  2.05it/s]

[988/1000]
EN: Public health summits in 2026 emphasized the importance of data-driven decision-making for epidemic prevention.
ASM: ২০২৬ চনত জনস্বাস্থ্য সন্মিলনত মহামাৰী প্ৰতিৰোধৰ বাবে তথ্যভিত্তিক সিদ্ধান্ত গ্ৰহণৰ ওপৰত গুৰুত্ব আৰোপ কৰা হৈছিল ।
--------------------------------------------------

Translating ASM:  99%|██████████████████████▋| 989/1000 [07:15<00:05,  1.95it/s]

[989/1000]
EN: Hospitals in Mumbai are reporting a shift toward integrated care models for chronic lifestyle diseases.
ASM: মুম্বাইৰ চিকিৎসালয়সমূহে চিৰস্থায়ী জীৱনশৈলী ৰোগৰ বাবে সংহত যত্ন মডেলৰ দিশে এক পৰিৱৰ্তন হোৱাৰ বাতৰি দিছে ।
--------------------------------------------------

Translating ASM:  99%|██████████████████████▊| 990/1000 [07:16<00:05,  1.93it/s]

[990/1000]
EN: The Ministry of Health is focusing on improving the nurse-to-patient ratio in public hospitals through new recruitment drives.
ASM: স্বাস্থ্য মন্ত্ৰালয়ে নতুন নিয়োগ প্ৰচেষ্টাৰ জৰিয়তে ৰাজহুৱা চিকিৎসালয়সমূহত নাৰ্ছৰ পৰা ৰোগীৰ অনুপাত উন্নত কৰাৰ ওপৰত গুৰুত্ব আৰোপ কৰিছে ।
--------------------------------------------------

Translating ASM:  99%|██████████████████████▊| 991/1000 [07:16<00:04,  1.96it/s]

[991/1000]
EN: India is positioning itself as a global hub for the manufacturing of affordable biologics and specialized therapies.
ASM: ভাৰতে সুলভ মূল্যত জৈৱিক পদাৰ্থ আৰু বিশেষ চিকিৎসাৰ উৎপাদনৰ এক গ্লোবাল হাব হিচাপে নিজকে প্ৰতিষ্ঠা কৰিছে ।
--------------------------------------------------

Translating ASM:  99%|██████████████████████▊| 992/1000 [07:17<00:03,  2.07it/s]

[992/1000]
EN: PGIMER doctors achieve major breakthrough in deadly Celphos poisoning
ASM: মাৰাত্মক চেলফছ বিষাক্তকৰণত পিজিআইএমইআৰ চিকিৎসকে বৃহৎ সাফল্য অৰ্জন কৰিছে
--------------------------------------------------

Translating ASM:  99%|██████████████████████▊| 993/1000 [07:17<00:03,  2.22it/s]

[993/1000]
EN: What a 12-hour work day can do to your metabolic, mental and reproductive health
ASM: ১২ ঘণ্টীয়া কৰ্মদিবসে আপোনাৰ বিপাকীয়, মানসিক আৰু প্ৰজনন স্বাস্থ্যৰ বাবে কি কৰিব পাৰে
--------------------------------------------------

Translating ASM:  99%|██████████████████████▊| 994/1000 [07:18<00:02,  2.19it/s]

[994/1000]
EN: Healthcare services disrupted as doctors across states protest Kolkata colleague’s rape-murder
ASM: কলিকতা সহকৰ্মী ধৰ্ষণ-হত্যাৰ প্ৰতিবাদত ৰাজ্যজুৰি চিকিৎসকসকলৰ বাবে স্বাস্থ্যসেৱা সেৱা ব্যাহত হৈছে
--------------------------------------------------

Translating ASM: 100%|██████████████████████▉| 995/1000 [07:18<00:02,  2.27it/s]

[995/1000]
EN: Manmohan Singh unveils multi-crore healthcare plan for paramilitary forces
ASM: অৰ্ধসামৰিক বাহিনীৰ বাবে বহু কোটি টকাৰ স্বাস্থ্যসেৱা পৰিকল্পনা উন্মোচন মনমোহন সিঙৰ
--------------------------------------------------

Translating ASM: 100%|██████████████████████▉| 996/1000 [07:19<00:01,  2.15it/s]

[996/1000]
EN: US Senate Hearing Explodes After Senator Questions Indian Origin Doctor on Men’s Pregnancy
ASM: পুৰুষৰ গৰ্ভধাৰণ সন্দৰ্ভত ভাৰতীয় বংশোদ্ভৱ চিকিৎসকক সিনেটৰ প্ৰশ্নৰ পিছত আমেৰিকা যুক্তৰাষ্ট্ৰৰ চিনেটৰ শুনানি বিস্ফোৰিত
--------------------------------------------------

Translating ASM: 100%|██████████████████████▉| 997/1000 [07:19<00:01,  2.20it/s]

[997/1000]
EN: Dr. D N gupta addresses the lack of awareness surrounding Vitamin D deficiency.
ASM: ড০ ডি এন গুপ্তাই ভিটামিন ডিৰ ঘাটিৰ বিষয়ে সজাগতাৰ অভাৱক সম্বোধন কৰে ।
--------------------------------------------------

Translating ASM: 100%|██████████████████████▉| 998/1000 [07:20<00:01,  1.85it/s]

[998/1000]
EN: Oncologist shares case of non-tobacco related cancer in 21-year-old man with ‘sharp teeth,’ says ‘It could have been identified’
ASM: এটা অনকোলজিষ্টৰ মতে ২১ বছৰীয়া এজন ব্যক্তিৰ তামাক নথকা কৰ্কট ৰোগত উজলীয়া দাঁত থকা এজন ব্যক্তিয়ে কৈছিল যে এয়া চিনাক্ত কৰিব পাৰিলেহেঁতেন
--------------------------------------------------

Translating ASM: 100%|██████████████████████▉| 999/1000 [07:20<00:00,  1.96it/s]

[999/1000]
EN: Nutritionist says pineapple and cinnamon may help reduce period cramps naturally
ASM: পুষ্টিবিদে কয় যে অন্নাপল আৰু চিনেমনে প্ৰাকৃতিকভাৱে ঋতুস্ৰাৱ হ্ৰাস কৰাত সহায় কৰিব পাৰে
--------------------------------------------------

Translating ASM: 100%|██████████████████████| 1000/1000 [07:21<00:00,  2.27it/s]

[1000/1000]
EN: Don’t brush before bed? Your heart might pay the price
ASM: বিছনাৰ আগেয়ে পোনপটীয়াকৈ গোটাব নালাগেনে?
--------------------------------------------------

✅ Translation saved to: /home/dingku/Desktop/translated_assamese.txt

============================================================
Processing MNI translation
Input:  /home/dingku/Desktop/WMT 2026 IndicMT Test Data/Category 1/English - Manipuri/en-mni Test.xlsx
Output: /home/dingku/Desktop/translated_manipuri.txt
============================================================

Total sentences to translate: 1000

Translating MNI:   0%|                         | 1/1000 [00:00<12:16,  1.36it/s]

[1/1000]
EN: NDTV has learnt from sources that the T20 World Cup 2026 match between India and Pakistan is ON.
MNI: ভারত অমসুং পাকিস্তানগী মরক্তা পাংথোক্কদৌরিবা টি২০ ৱার্ল্দ কপ ২০২৬গী মেটচ অদু ওন ওইরে হায়না এনদিতিভিনা সোর্সশিংদগী খংলে।
--------------------------------------------------

Translating MNI:   0%|                         | 2/1000 [00:01<07:54,  2.10it/s]

[2/1000]
EN: The PCB placed several demands before the ICC.
MNI: পিসিবিনা আইসিসিদা দিমান্দ কয়া থমখি।
--------------------------------------------------

Translating MNI:   0%|                         | 3/1000 [00:01<08:37,  1.93it/s]

[3/1000]
EN: The PCB pushed for ICC intervention to facilitate a bilateral series between India and Pakistan.
MNI: ভারত অমসুং পাকিস্থানগী মরক্তা বাইলেতরেল সিরিজ অমা শেমগৎনবা আইসিসিগী মতেং পীননবা পিসিবিনা খোংজেল য়াংখি।
--------------------------------------------------

Translating MNI:   0%|                         | 4/1000 [00:02<09:48,  1.69it/s]

[4/1000]
EN: Virat Kohli and Rohit Sharma have been demoted to Grade B in BCCI's central contract list for 2025-26.
MNI: বিরাত কোহলি অমসুং রোহিৎ শর্মাবু ২০২৫-২৬গী সেন্ত্রেল কন্ত্রেক্ত লিস্ততা বি.সি.সি.আই.গী গ্রেদ বিদা হন্থহনখ্রে।
--------------------------------------------------

Translating MNI:   0%|▏                        | 5/1000 [00:02<09:24,  1.76it/s]

[5/1000]
EN: Thirty senior men's cricketers have been awarded central contracts, with the BCCI doing away with the A+ grade.
MNI: সেনিয়র মেনস ক্রিকেতর ৩০দা সেন্ত্রেল কন্ত্রেক্তশিং পীখ্রে অমসুং বিসিসিআইনা এ+ গ্রেদ লৌথোকখ্রে।
--------------------------------------------------

Translating MNI:   1%|▏                        | 6/1000 [00:03<09:54,  1.67it/s]

[6/1000]
EN: As per the 2024-25 BCCI contracts, any player in Grade A would receive Rs 5 crore annually.
MNI: ২০২৪-২৫গী বিসিসিআই কন্ত্রেক্তশিংগী মতুংইন্না গ্রেদ এগী প্লেয়র অমহেক্তনা চহিদা লুপা কোতি ৫ ফংগনি।
--------------------------------------------------

Translating MNI:   1%|▏                        | 7/1000 [00:03<08:34,  1.93it/s]

[7/1000]
EN: Grade B players would get Rs 3 crore, while
MNI: গ্রেদ বিগী শান্নরোইশিংনা লুপা কোতি ৩ ফংগনি ।
--------------------------------------------------

Translating MNI:   1%|▏                        | 8/1000 [00:04<07:34,  2.18it/s]

[8/1000]
EN: Grade C players would get Rs 1 crore.
MNI: গ্রেদ সিগী শান্নরোইশিংনা লুপা কোতি ১ ফংগনি।
--------------------------------------------------

Translating MNI:   1%|▏                        | 9/1000 [00:04<09:10,  1.80it/s]

[9/1000]
EN: Earlier, Grade A+ players (Kohli, Rohit, Jasprit Bumrah, Ravindra Jadeja) used to receive Rs 7 crore.
MNI: মমাংদা গ্রেদ A+গী শান্নরোইশিং ( কোহলি, রোহিৎ, জাসপ্রীত বুমরাহ, রবিন্দ্রা জাদেজা ) না লুপা কোতি ৭ ফংগনি।
--------------------------------------------------

Translating MNI:   1%|▏                       | 10/1000 [00:05<09:43,  1.70it/s]

[10/1000]
EN: The BCCI has not yet officially declared whether the payment structure for 2025-26 will be any different.
MNI: ২০২৫-২৬গী পেমেন্ত ষ্ট্রকচর অসি তোঙান-তোঙানবা ওইরব্রা হায়বদু বিসিসিআইনা হৌজিক ফাওবা ওফিসিয়েল ওইনা লাউথোক্ত্রি।
--------------------------------------------------

Translating MNI:   1%|▎                       | 11/1000 [00:05<08:28,  1.95it/s]

[11/1000]
EN: 21 women cricketers classified in Grade A, B and C.
MNI: গ্রেদ A, B অমসুং Cদা ক্লাসিফাই তৌরবা নুপী ক্রিকেতর ২১
--------------------------------------------------

Translating MNI:   1%|▎                       | 12/1000 [00:06<09:29,  1.73it/s]

[12/1000]
EN: Harmanpreet Kaur, Smriti Mandhana, Deepti Sharma and Jemimah Rodrigues are the four players to be included in Grade A.
MNI: গ্রেদ Aদা য়াওরিবা শান্নরোই মরি অদু হর্মনপ্রীত কৌর, স্মৃতী মান্দনা, দীপ্তি শর্মা অমসুং জেমিমা রোদ্রিগসনি।
--------------------------------------------------

Translating MNI:   1%|▎                       | 13/1000 [00:07<09:46,  1.68it/s]

[13/1000]
EN: The cycle for new central contract is based on performance and volume of games played during the preceding season.
MNI: অনৌবা সেন্ত্রেল কন্ত্রেক্তকী সাইকল অসি মমাংগী সিজনদা শান্নখিবা গেমশিংগী পর্ফোমেন্স অমসুং ভোল্যুমদা য়ুম্ফম ওইগনি।
--------------------------------------------------

Translating MNI:   1%|▎                       | 14/1000 [00:07<09:36,  1.71it/s]

[14/1000]
EN: Pakistan and Bangladesh's demands from the International Cricket Council (ICC) have just grown bigger.
MNI: ইন্তর্নেস্নেল ক্রিকেৎ কাউন্সিল ( আই সি সি ) দগী পাকিস্থান অমসুং বঙ্গলাদেশকী দিমান্দশিং হেনগৎলক্লি।
--------------------------------------------------

Translating MNI:   2%|▎                       | 15/1000 [00:08<09:02,  1.82it/s]

[15/1000]
EN: The 2031 edition of the ODI World Cup is set to be played in India and Bangladesh.
MNI: ওদিআই ৱার্ল্দ কপগী ২০৩১গী এদিসন অসি ভারত অমসুং বঙ্গলাদেশতা শান্নগনি।
--------------------------------------------------

Translating MNI:   2%|▍                       | 16/1000 [00:08<08:05,  2.03it/s]

[16/1000]
EN: At present, the hybrid model is applicable until 2027.
MNI: হৌজিক্কী ওইনা হায়ব্রিদ মোদেল অসি ২০২৭ ফাওবা চৎনগনি।
--------------------------------------------------

Translating MNI:   2%|▍                       | 17/1000 [00:09<08:35,  1.91it/s]

[17/1000]
EN: The extension would allow Bangladesh and Pakistan to play all their matches in Bangladesh and not India.
MNI: মতম শাংদোকপনা বঙ্গলাদেশ অমসুং পাকিস্থাননা মখোয়গী মেচ পুম্নমক ভারত্তা নত্তনা বঙ্গলাদেশতা শান্নবা য়াহনগনি।
--------------------------------------------------

Translating MNI:   2%|▍                       | 18/1000 [00:10<09:39,  1.69it/s]

[18/1000]
EN: The BCB was represented by its head Aminul Islam Bulbul while PCB chairman Mohsin Naqvi was also present.
MNI: বি.স.বি.গী মীহুৎ মকোক অমিনুল ইস্লাম বল্বুল ওইখি অমসুং পিসিবিগী চিয়ারমেন মোহসিন নক্বীসু শরুক য়াখি।
--------------------------------------------------

Translating MNI:   2%|▍                       | 19/1000 [00:10<08:57,  1.82it/s]

[19/1000]
EN: ICC's deputy chairman Imran Khawaja was present in the meeting.
MNI: মীফম অদুদা আইসিসিগী উপ চিয়ারমেন ইমরান খ্বাজাসু শরুক য়াখি।
--------------------------------------------------

Translating MNI:   2%|▍                       | 20/1000 [00:10<08:25,  1.94it/s]

[20/1000]
EN: No joint declaration was issued after the four-hour meeting.
MNI: পুং মরি চত্থখিবা মীফম অদুগী মতুংদা জোইন্ত দিক্লারেসন অমত্তা ইসু তৌখিদে।
--------------------------------------------------

Translating MNI:   2%|▌                       | 21/1000 [00:11<09:13,  1.77it/s]

[21/1000]
EN: The hybrid model arrangement was introduced after India refused to tour Pakistan for the 2025 Champions Trophy.
MNI: ইং ২০২৫গী চেম্পিয়ন্স ত্রোফিগীদমক ভারতনা পাকিস্থানদা চৎপা য়াদ্রবা মতুংদা হায়ব্রাইদ মোদেল এরেঞ্জমেন্ত অসি হৌদোকখি।
--------------------------------------------------

Translating MNI:   2%|▌                       | 22/1000 [00:12<09:16,  1.76it/s]

[22/1000]
EN: After extensive negotiations, a hybrid model was accepted by all parties, including the ICC.
MNI: পাক-চাউনা ৱারি শান্নরবা মতুংদা আই সি সি য়াউনা পার্টি পুম্নমক্না হাইব্রীদ মোদেল অমা য়াখি।
--------------------------------------------------

Translating MNI:   2%|▌                       | 23/1000 [00:12<09:38,  1.69it/s]

[23/1000]
EN: The second part of the arrangement states that Pakistan will not travel to India for the 2026 T20 World Cup.
MNI: এরেঞ্জমেন্তকী অনিশুবা শরুক্না হায়রি মদুদি ২০২৬গী টি-২০ ৱার্ল্দ কপকীদমক পাকিস্থাননা ভারত্তা চৎকদবনি।
--------------------------------------------------

Translating MNI:   2%|▌                       | 24/1000 [00:13<09:02,  1.80it/s]

[24/1000]
EN: As a result, all of Pakistan's matches (even if they reach the final) will be played in Sri Lanka.
MNI: মসিগী ফল ওইনা, পাকিস্থানগী মেচ পুম্নমক ( ফাইনেল য়ৌরবসু ) শ্রীলঙ্কাদা শান্নগনি।
--------------------------------------------------

Translating MNI:   2%|▌                       | 25/1000 [00:13<08:06,  2.01it/s]

[25/1000]
EN: Bangladesh, Pakistan, and India must be treated the same.
MNI: বঙ্গলাদেশ, পাকিস্থান অমসুং ভারতপু চপ মান্ননা য়েংশিনগদবনি।
--------------------------------------------------

Translating MNI:   3%|▌                       | 26/1000 [00:14<07:27,  2.18it/s]

[26/1000]
EN: Now, Gavaskar has taken an indirect jibe at Hussain
MNI: হৌজিক্তি গভাস্কারনা হুসেন্দা অকায়-অতোয়না ৱা ঙাংখ্রে ।
--------------------------------------------------

Translating MNI:   3%|▋                       | 27/1000 [00:14<08:55,  1.82it/s]

[27/1000]
EN: He went on to give the example of the 2003 World Cup, when England refused to tour Zimbabwe in protest against Robert Mugabe's regime.
MNI: মহাক্না ইং ২০০৩কী ৱার্ল্দ কপকী খুদম পীখি, ইংলেন্দনা রোবর্ত মুগাবেগী রেজিমগী প্রোতেষ্ট ওইনা জিম্বাবুৱেগী তুর থাদোকপা য়াখিদে।
--------------------------------------------------

Translating MNI:   3%|▋                       | 28/1000 [00:15<08:55,  1.82it/s]

[28/1000]
EN: Samson's knock was full of intent but fell short in effectiveness quotient.
MNI: সিমসনগী খোংবাল অদু ইন্তেন্তনা মেনশিনখি অদুবু ইফেক্টিভনেস কোতিয়েন্ততা তাথখি।
--------------------------------------------------

Translating MNI:   3%|▋                       | 29/1000 [00:15<08:52,  1.82it/s]

[29/1000]
EN: With this win, India overtook Pakistan at the summit of Group A courtesy of a superior net run-rate.
MNI: মায় পাকপগা লোয়ননা ভারতনা গ্রুপ Aগী সমিৎতা পাকিস্থানবু হেন্না ফবা নেট রন-রেৎ অমগী খুত্থাংদা মায় পাকখি।
--------------------------------------------------

Translating MNI:   3%|▋                       | 30/1000 [00:16<09:38,  1.68it/s]

[30/1000]
EN: India batter Abhishek Sharma will take no part in the T20 World Cup 2026 clash against Namibia in New Delhi on Thursday.
MNI: অনৌবা দিল্লীদা পাংথোক্কদৌরিবা টি-২০ ৱার্ল্দ কপ ২০২৬গী মায়োক্নবদা ভারতকী বেটর অভিশেক শর্মা শরুক য়ারোই।
--------------------------------------------------

Translating MNI:   3%|▊                       | 32/1000 [00:17<06:35,  2.45it/s]

[31/1000]
EN: Abhishek isn't fine still, might take one or two games.
MNI: অভিশেক অসি হৌজিকসু ফজনা লৈতে, মেচ অমা নত্ত্রগা অনি লৌবা য়াই।
--------------------------------------------------

[32/1000]
EN: Samson comes in.
MNI: Samson comes in.
--------------------------------------------------

Translating MNI:   3%|▊                       | 33/1000 [00:17<06:26,  2.50it/s]

[33/1000]
EN: Bumrah comes in for Siraj," said Suryakumar at the toss.
MNI: সিরাজগীদমক বুমরা লাক্লি, সুর্যকুমারনা টোসতা হায়খি।
--------------------------------------------------

Translating MNI:   3%|▊                       | 34/1000 [00:17<05:56,  2.71it/s]

[34/1000]
EN: Defending with dew will build our confidence. Hope our batters entertain the crowd.
MNI: ঈচাউনা ঙাকথোকপনা ঐখোয়গী থাজবা হেনগৎহনগনি ।
--------------------------------------------------

Translating MNI:   4%|▊                       | 35/1000 [00:18<06:08,  2.62it/s]

[35/1000]
EN: It's a big tournament, dew will be a big factor.
MNI: মসি অচৌবা টুর্নামেন্ত অমনি, ঈচাউনা অচৌবা ফেক্টর অমা ওইগনি।
--------------------------------------------------

Translating MNI:   4%|▊                       | 36/1000 [00:18<06:49,  2.35it/s]

[36/1000]
EN: India made two changes to the side that beat the USA on the opening day of the tournament.
MNI: টুর্নামেন্ত হৌদোকপগী নুমিত্তা ভারতনা য়ু এস এবু মায়থীবা মায়কৈদা অহোংবা অনি তৌখি।
--------------------------------------------------

Translating MNI:   4%|▉                       | 37/1000 [00:19<08:03,  1.99it/s]

[37/1000]
EN: Sanju Samson replaced Abhishek, while Jasprit Bumrah replaced Mohammed Siraj in the India XI.
MNI: সঞ্জু সামসন্না অভিশেকগী মহুৎ শিনখি অমসুং ইন্দিয়া ইলেভেনদা জাসপ্রিত বুমরাহনা মোহমদ সিরাজগী মহুৎ শিনখি।
--------------------------------------------------

Translating MNI:   4%|▉                       | 38/1000 [00:19<08:02,  1.99it/s]

[38/1000]
EN: India take on Pakistan next, with the team set to travel to Colombo for the game on February 15.
MNI: তুংদা ভারতনা পাকিস্থান মায়োক্নগনি অমসুং ফেব্রুৱারী ১৫দা শান্নবগীদমক টিম অদু কোলোম্বোদা চৎকনি।
--------------------------------------------------

Translating MNI:   4%|▉                       | 39/1000 [00:20<07:44,  2.07it/s]

[39/1000]
EN: The cabinet agreed with certain conditions as per the Cunha report.
MNI: কুনহা রিপোর্তকী মতুংইন্না কেবিনেৎনা অকক্নবা কন্দিসনশিং য়ানখি।
--------------------------------------------------

Translating MNI:   4%|▉                       | 40/1000 [00:20<07:20,  2.18it/s]

[40/1000]
EN: He mentioned in the report a maximum of 35,000 people and other conditions.
MNI: রিপোর্ত অদুদা মহাক্না য়াম্লবদা মীওই ৩৫,০০০ অমসুং অতৈ কন্দিসনশিং পনখি।
--------------------------------------------------

Translating MNI:   4%|▉                       | 41/1000 [00:21<08:19,  1.92it/s]

[41/1000]
EN: India reached the 100-run mark in just 6.5 overs - the fastest team hundred in T20 World Cup history.
MNI: ভারতনা মাত্র ৬.৫ ওভরদা রন ১০০গী মার্ক য়ৌখি  টি২০ ৱার্ল্দ কপকী পুৱারীদা খ্বাইদগী য়াংবা টিম সেন্তর ওইখি।
--------------------------------------------------

Translating MNI:   4%|█                       | 42/1000 [00:21<08:17,  1.93it/s]

[42/1000]
EN: After being asked to bat first, India were off to a decent start, making 8/0 in the first over.
MNI: অহানবদা বেৎ তৌনবা খংহল্লবা মতুংদা ভারতনা অহানবা ওভরদা ৮/০ ওইদুনা মওং চুম্না হৌখি।
--------------------------------------------------

Translating MNI:   4%|█                       | 43/1000 [00:22<08:25,  1.89it/s]

[43/1000]
EN: After four overs, the defending champions reached 43/1, with Ishan Kishan finding a couple of boundaries.
MNI: ওভর মরিগী মতুংদা দিফেন্দিং চেম্পিয়নশিংনা ৪৩/১ য়ৌখি অমসুং ইশান কিশন্না বোদরি পীরকখি।
--------------------------------------------------

Translating MNI:   4%|█                       | 44/1000 [00:23<09:05,  1.75it/s]

[44/1000]
EN: On the first ball of the 11th over, spinner Bernard Scholtz dismissed captain Suryakumar Yadav for just 12.
MNI: ১১শুবা ওভরগী অহানবা বলদা স্পিনর বার্নার্দ শোল্তজনা কেপ্টেন সুর্যকুমার যাদবপু মাত্র ১২গীদমক দিসমিৎ তৌখি।
--------------------------------------------------

Translating MNI:   4%|█                       | 45/1000 [00:23<09:28,  1.68it/s]

[45/1000]
EN: India lost another wicket quickly when Tilak Varma was removed for 25 by Namibia skipper Erasmus in the 12th over.
MNI: নামিবিয়াগী স্কাইপর ইরাসমসনা ১২শুবা ওভরদা তিলক বার্মাবু ২৫দা লৌথোক্তুনা ভারতনা ৱিকেট অমা য়াম্না থুনা মাংখি।
--------------------------------------------------

Translating MNI:   5%|█                       | 46/1000 [00:24<10:32,  1.51it/s]

[46/1000]
EN: Shivam Dube and Hardik Pandya then combined to hammer 24 runs off Bernard Scholtz as India raced to 168/4.
MNI: শিবাম দ্যুবে অমসুং হার্দিক পান্দ্যানা হার্দিক পান্দ্যাগা পুন্সিল্লদুনা বার্নার্দ সোল্তজদগী রন ২৪ লৌথোকখি অমসুং ভারতনা ১৬৮/৪দা রেন তৌখি।
--------------------------------------------------

Translating MNI:   5%|█▏                      | 47/1000 [00:25<10:22,  1.53it/s]

[47/1000]
EN: By the end of the 18th over, India had reached 199/4 with Pandya and Dube going strong.
MNI: ১৮শুবা ওভর লোইদ্রিঙৈদা ভারতনা পন্দ্যা অমসুং দ্যুবপু মপাঙ্গল কনখৎহন্দুনা ৯৯/৪ য়ৌখি।
--------------------------------------------------

Translating MNI:   5%|█▏                      | 48/1000 [00:26<10:54,  1.45it/s]

[48/1000]
EN: On the first ball of the 19th over, Pandya completed his fifty off 27 deliveries as India crossed the 200-run mark.
MNI: ১৯ শুবা ওভরগী অহানবা বলদা পান্দ্যানা ভারতনা রন ২০০গী মার্ক ক্রোস তৌরগা দেলিভরি ২৭গী মনুংদা মঙাশুবা মপুং ফাহল্লকখি।
--------------------------------------------------

Translating MNI:   5%|█▏                      | 49/1000 [00:26<09:44,  1.63it/s]

[49/1000]
EN: Shivam Dube was run out for 23 after a mix-up with Rinku Singh.
MNI: রিনকু সিংহগা ৱারি শান্নরবা মতুংদা শিবাম দুবে অসি ২৩ রন আউট ওইখি।
--------------------------------------------------

Translating MNI:   5%|█▏                      | 50/1000 [00:27<09:48,  1.61it/s]

[50/1000]
EN: India then lost Rinku Singh (1) and Arshdeep Singh (2) in the final over, finishing at 209/9.
MNI: মসিগী মতুংদা ভারতনা ফাইনেল ওভরদা রিনকু সিংহ (1) অমসুং অর্শদীপ সিংহ (2) মাংখি অমসুং মখোয়না 209/9তা ফাইনিস তৌখি।
--------------------------------------------------

Translating MNI:   5%|█▏                      | 51/1000 [00:28<11:30,  1.37it/s]

[51/1000]
EN: ICC Men’s T20 World Cup 2026 began on February 7, 2026, at Sinhalese Sports Club Ground with Pakistan playing Netherlands in the opening match.
MNI: আই সি সি মেনস টি ২০২৬ ৱার্ল্দ কপ ২০২৬ অসি ইং ২০২৬গী ফেব্রুৱারী ৭দা সিহালাইস স্পোর্তস ক্লব গ্রাউন্দদা হৌদোকপগী মেটচতা পাকিস্থাননা নেদরলেন্দশিংগা লোয়ননা শান্নবা হৌখি।
--------------------------------------------------

Translating MNI:   5%|█▏                      | 52/1000 [00:28<12:20,  1.28it/s]

[52/1000]
EN: Bangladesh national cricket team faced the India men's national cricket team in an opening match reported ahead of the 2026 T20 tournament.
MNI: বাঙ্গলাদেশকী নেস্নেল ক্রিকেৎ তীমনা ইং ২০২৬গী টি২০ টুর্নামেন্তকী মমাংদা পাংথোক্কদবা ওপনিং মেটচ অমদা ভারতকী নুপাগী নেস্নেল ক্রিকেৎ তীমগা মায়োক্নখি।
--------------------------------------------------

Translating MNI:   5%|█▎                      | 53/1000 [00:29<10:14,  1.54it/s]

[53/1000]
EN: Ishan Kishan struck a rapid half-century.
MNI: ইশান কিশাননা য়াম্না থুনা সেঞ্চুরি তংখায়খি।
--------------------------------------------------

Translating MNI:   5%|█▎                      | 54/1000 [00:29<10:18,  1.53it/s]

[54/1000]
EN: Faf du Plessis scored a half-century and Mitchell Starc took a five-wicket haul in the same match report.
MNI: ফেফ দু প্লেসিসনা সেঞ্চুরি তংখায়খি অমসুং মিচেল স্তার্কনা চপ মান্নবা মেটচ রিপোর্ত অদুদা ৱিকেট মঙা লৌখি।
--------------------------------------------------

Translating MNI:   6%|█▎                      | 55/1000 [00:30<11:08,  1.41it/s]

[55/1000]
EN: Jasprit Bumrah and Ravindra Jadeja were reported to have been demoted in the 2025–26 central contracts discussion.
MNI: জাসপ্রীৎ বুমরা অমসুং রবিন্দ্রা জাদেজা অসি ২০২৫২৬গী সেন্ত্রেল কন্ত্রেক্তশিংগী খন্ন-নৈনবদা হন্থহনখিবনি হায়না রিপোর্ত তৌখি।
--------------------------------------------------

Translating MNI:   6%|█▎                      | 56/1000 [00:31<10:58,  1.43it/s]

[56/1000]
EN: Rohit Sharma carried the men’s T20 World Cup trophy during a promotional appearance.
MNI: প্রোমোসনগী থৌরম অমদা রোহিত শর্মানা নুপাগী টি২০ ৱার্ল্দ কপ ত্রোফি পুথোকখি।
--------------------------------------------------

Translating MNI:   6%|█▎                      | 57/1000 [00:32<12:07,  1.30it/s]

[57/1000]
EN: The International Cricket Council update said a high-profile match involving Pakistan would go ahead on February 15, 2026, in Colombo.
MNI: ইন্তর্নেস্নেল ক্রিকেৎ কাউন্সিলগী অপদেৎনা হায়খি মদুদি ২০২৬গী ফেব্রুৱারী ১৫দা কোলোম্বোদা পাকিস্থান য়াওবা হাই-প্রোফাইল মেটচ অমা পাংথোক্কনি।
--------------------------------------------------

Translating MNI:   6%|█▍                      | 58/1000 [00:33<11:45,  1.34it/s]

[58/1000]
EN: The New Zealand national cricket team lost the first ODI by four wickets to the India men's national cricket team.
MNI: ন্যু জিলেন্দ নেসনেল ক্রিকেৎ তীমনা অহানবা ওদিআইদা ভারতকী নুপাগী নেসনেল ক্রিকেৎ তীমদা ৱিকেট মরিনা মাংখি।
--------------------------------------------------

Translating MNI:   6%|█▍                      | 59/1000 [00:34<12:39,  1.24it/s]

[59/1000]
EN: Australia national cricket team ended day one at 67 for seven in reply to 150 by the India men's national cricket team in a Test match post.
MNI: অষ্ট্রেলিয়া নেস্নেল ক্রিকেৎ তীমনা ভারতকী নুপাগী নেস্নেল ক্রিকেৎ তীমনা টেস্ত মেচ পোস্ত অমদা পাউখুম পীদুনা নোংমগী অহানবা নুমীৎ অদু 67দা তরেৎকী ওইনা লোইশিনখি।
--------------------------------------------------

Translating MNI:   6%|█▍                      | 60/1000 [00:34<13:16,  1.18it/s]

[60/1000]
EN: The India national under-19 cricket team won the ICC U19 World Cup final by 100 runs against the England national under-19 cricket team in Harare.
MNI: ভারতকী নেস্নেল অনন্দর-১৯ ক্রিকেৎ তীমনা হরারেদা ইংলেন্দ নেস্নেল অনন্দর-১৯ ক্রিকেৎ তীম মায়োক্নদুনা আইসিসি য়ু১৯ ৱার্ল্দ কপ ফাইনেল রন ১০০ দা মায় পাকখি।
--------------------------------------------------

Translating MNI:   6%|█▍                      | 61/1000 [00:35<11:53,  1.32it/s]

[61/1000]
EN: Members of the India women's national cricket team were given a grand welcome after their title-winning campaign.
MNI: ভারতকী ৱুমেন নেস্নেল ক্রিকেৎ তীমগী মেম্বরশিং মখোয়গী তাইটল ফংলবা কেম্পেইনগী মতুংদা তরাম্না ওকখি।
--------------------------------------------------

Translating MNI:   6%|█▍                      | 62/1000 [00:36<11:29,  1.36it/s]

[62/1000]
EN: The India women's national cricket team lifting the ICC Women’s World Cup as one of the year’s landmark moments.
MNI: ভারতকী ৱুমেন্স নেসনেল ক্রিকেৎ তীমনা আইসিসি ৱুমেন্স ৱার্ল্দ কপ অসি চহি অসিগী লেন্দমার্ক মোমন্তশিংগী মনুংদা অমনি হায়না লৌরি।
--------------------------------------------------

Translating MNI:   6%|█▌                      | 63/1000 [00:37<12:14,  1.28it/s]

[63/1000]
EN: The Indian Premier League season in 2025 was reported as suspended indefinitely amid escalating India–Pakistan military tensions.
MNI: ইং ২০২৫দা ইন্দিয়ান প্রিমিয়র লীগ সিজন অসি ইন্দিয়াপাকিস্থান মিলিতরী টেনসন হেনগৎলকপগা লোয়ননা মতম অমত্তগী লেপথোক্তুনা থমখিবনি হায়না রিপোর্ট তৌরি।
--------------------------------------------------

Translating MNI:   6%|█▌                      | 64/1000 [00:37<11:12,  1.39it/s]

[64/1000]
EN: The Eden Gardens hosted the opening spectacle for the 18th edition of the Indian Premier League.
MNI: ইদেন গার্দেনসতা ইন্দিয়ান প্রিমিয়র লীগকী ১৮শুবা এদিসন হৌদোকপগী থৌরম পাংথোকখি।
--------------------------------------------------

Translating MNI:   6%|█▌                      | 65/1000 [00:38<10:30,  1.48it/s]

[65/1000]
EN: Royal Challengers Bengaluru named Rajat Patidar as captain for the season starting March 21.
MNI: রয়েল চেলেঞ্জর্স বেঙ্গালুরুনা মার্চ ২১দগী হৌগদবা সিজন অসিগীদমক রাজত পতিদারবু কেপ্তেন ওইনা খনবা হৌখি।
--------------------------------------------------

Translating MNI:   7%|█▌                      | 66/1000 [00:38<09:54,  1.57it/s]

[66/1000]
EN: Chennai Super Kings posted their lowest home total and suffered a fifth straight loss.
MNI: চেন্নাই সুপর কিংসনা মখোয়গী খ্বাইদগী নেমথবা য়ুমগী অপুনবা পনখি অমসুং মথং মথং ৫শুবা পনখি।
--------------------------------------------------

Translating MNI:   7%|█▌                      | 67/1000 [00:39<09:17,  1.67it/s]

[67/1000]
EN: A Dharamsala fixture involving Punjab Kings and Delhi Capitals was called off after a blackout.
MNI: ব্লেক আউট অমগী মতুংদা পঞ্জাব কিংস অমসুং দিল্লী কেপিতেলস য়াওবা ধর্মসালা ফিক্সচর অমা লেপখি।
--------------------------------------------------

Translating MNI:   7%|█▋                      | 68/1000 [00:39<09:09,  1.70it/s]

[68/1000]
EN: Punjab Kings defeated Mumbai Indians in Jaipur to secure a top-two league finish.
MNI: পঞ্জাব কিংসনা জয়পুরদা মুম্বাই ইন্দিয়ান্সপু মায়থীবা পীদুনা লিগগী মকোক অনি ফংবা ঙমখি।
--------------------------------------------------

Translating MNI:   7%|█▋                      | 69/1000 [00:40<09:08,  1.70it/s]

[69/1000]
EN: KL Rahul became the fastest Indian to 8,000 T20 runs after an unbeaten 112.
MNI: কেএল রাহুলনা অপন-অরাক লৈতবা ১১২গী মতুংদা টি২০ রন ৮০০০ রন তৌবা খ্বাইদগী য়াংবা ভারত মচা ওইখি।
--------------------------------------------------

Translating MNI:   7%|█▋                      | 70/1000 [00:41<08:57,  1.73it/s]

[70/1000]
EN: Virat Kohli spoke about the June 4 stampede linked to his franchise’s celebrations.
MNI: বিরাত কোহলীনা মহাক্কী ফ্রাঞ্চাইজিগী থৌরমশিংগা মরি লৈনবা জুন ৪গী থৌদোক অদুগী মতাংদা ঙাংখি।
--------------------------------------------------

Translating MNI:   7%|█▋                      | 71/1000 [00:41<09:15,  1.67it/s]

[71/1000]
EN: The uncertainty over player retention created suspense ahead of the next Indian Premier League season.
MNI: প্লেয়র রিতেন্সনগী মরমদা লৈরকপা অকিবা অসিনা ইন্দিয়ান প্রিমিয়র লীগগী মথংগী সিজনগী মমাংদা সস্পেন্স লৈহল্লে।
--------------------------------------------------

Translating MNI:   7%|█▋                      | 72/1000 [00:42<08:21,  1.85it/s]

[72/1000]
EN: Rafael Nadal announced he would retire.
MNI: রফায়েল নাদলনা মহাক্না রিটায়ার তৌরগনি হায়না লাউথোকখি।
--------------------------------------------------

Translating MNI:   7%|█▊                      | 73/1000 [00:42<08:15,  1.87it/s]

[73/1000]
EN: Carlos Alcaraz beat Novak Djokovic to win his first major title.
MNI: কার্লোস অলকারাজনা নোভাক জোকোভিকপু মায়থীবা পীদুনা মহাক্কী অহানবা মেজর তাইটল লৌখি।
--------------------------------------------------

Translating MNI:   7%|█▊                      | 74/1000 [00:43<08:33,  1.81it/s]

[74/1000]
EN: Alexander Zverev lost a marathon match to Carlos Alcaraz in a five-set battle.
MNI: এলেক্সান্দর জভেরভনা মেরাথোন মেটচ অমা সেট মঙাগী মায়োক্নবদা কার্লোস অলকারাজতা মাংখি।
--------------------------------------------------

Translating MNI:   8%|█▊                      | 75/1000 [00:43<08:33,  1.80it/s]

[75/1000]
EN: Rohan Bopanna announced his retirement from professional tennis.
MNI: রোহন বোপান্না প্রোফেসনেল তেনিসতগী রিটায়ার তৌরে হায়না লাউথোকখি।
--------------------------------------------------

Translating MNI:   8%|█▊                      | 76/1000 [00:44<09:05,  1.69it/s]

[76/1000]
EN: A 14-place leap that signaled an upswing for India Davis Cup team in international tennis standings.
MNI: ইন্তর্নেস্নেল তেনিস স্তেন্দিংদা ইন্দিয়া দেভিস কপ তীমগীদমক অপসৱিং অমা ওইহন্নবা মফম ১৪গী খোংজেল অমা লৌখি।
--------------------------------------------------

Translating MNI:   8%|█▊                      | 77/1000 [00:45<09:06,  1.69it/s]

[77/1000]
EN: Elena Rybakina overcame Aryna Sabalenka to win the 2026 Australian Open final.
MNI: ইলেনা রিবাকিনানা অরিনা সবালেনকাবু মায়থীবা পীদুনা ইং ২০২৬গী ওস্ত্রেলিয়ান ওপন ফাইনেল মায় পাকখি।
--------------------------------------------------

Translating MNI:   8%|█▊                      | 78/1000 [00:45<09:01,  1.70it/s]

[78/1000]
EN: Novak Djokovic became the first player to reach 400 Grand Slam singles match wins in the Open Era.
MNI: ওপন ইরাদা গ্রান্দ স্লাম সিঙ্গলস মেচ ৪০০ মায় পাকখিবা নোভাক জোকোবিক অসি অহানবা শান্নরোই ওইখি।
--------------------------------------------------

Translating MNI:   8%|█▉                      | 79/1000 [00:46<09:10,  1.67it/s]

[79/1000]
EN: The India men's national field hockey team and its Olympic bronze-medal campaign in a dedicated post.
MNI: ভারতকী নুপাশিংগী নেস্নেল ফিল্দ হোকী তীম অমসুং মসিগী ওলিম্পিক ব্রোঞ্জ মেদল কেম্পেইনদা কৎথোকপা পোস্ত অমদা পনখি।
--------------------------------------------------

Translating MNI:   8%|█▉                      | 80/1000 [00:46<08:10,  1.88it/s]

[80/1000]
EN:  The India men's national field hockey team across major tournaments.
MNI: মরুওইবা টুর্নামেন্তশিংদা ভারতকী নুপাগী নেস্নেল ফিল্দ হোকী তীম
--------------------------------------------------

Translating MNI:   8%|█▉                      | 81/1000 [00:47<09:15,  1.65it/s]

[81/1000]
EN: The India men's national field hockey team beat South Korea men's national field hockey team 4–1 in a match update.
MNI: মেচ অপদেৎ অমদা ভারতকী নুপাশিংগী নেস্নেল ফিল্দ হোকী তীমনা সাউথ কোরিয়াগী নুপাশিংগী নেস্নেল ফিল্দ হোকী তীমবু ৪-১না মায়থীবা পীখি।
--------------------------------------------------

Translating MNI:   8%|█▉                      | 82/1000 [00:47<08:28,  1.81it/s]

[82/1000]
EN: The house of K. D. Singh Babu would be developed as a tourist attraction.
MNI: কে.দি. সিংহ বাবুগী য়ুম অসি তুরিস্ত এত্রেক্সন অমা ওইনা শেমগৎকনি।
--------------------------------------------------

Translating MNI:   8%|█▉                      | 83/1000 [00:48<07:28,  2.04it/s]

[83/1000]
EN: Lakshya Sen finished fourth in a tournament.
MNI: লক্ষ্য সেননা টুর্নামেন্ত অমদা মরিশুবা ওইনা ফমখি।
--------------------------------------------------

Translating MNI:   8%|██                      | 84/1000 [00:48<07:33,  2.02it/s]

[84/1000]
EN: Saina Nehwal confirmed her retirement from competitive badminton.
MNI: সাইনা নেহৱালনা কম্পিতিতিব বেদমিন্তনদগী মহাক্কী রিটায়ারমেন্ত অদু কনফার্ম তৌখি।
--------------------------------------------------

Translating MNI:   8%|██                      | 85/1000 [00:49<07:09,  2.13it/s]

[85/1000]
EN: R. Vaishali won the FIDE Women’s Grand Swiss.
MNI: আর. বৈশালিনা ফিদে ৱুমেন গ্রান্দ সুইসকী তকমান লৌখি।
--------------------------------------------------

Translating MNI:   9%|██                      | 86/1000 [00:49<06:34,  2.32it/s]

[86/1000]
EN: R. Praggnanandhaa came from behind to win a game.
MNI: র. প্রগনানন্দনা মেক অমা মায় পাক্নবা তুংদা লাকখি।
--------------------------------------------------

Translating MNI:   9%|██                      | 87/1000 [00:49<06:35,  2.31it/s]

[87/1000]
EN: D. Gukesh as the youngest world chess champion in history.
MNI: দি. গুকেশনা পুৱারীদা খ্বাইদগী নহা ওইরবা ৱার্ল্দ চেসম্পিয়ন ওইখি।
--------------------------------------------------

Translating MNI:   9%|██                      | 88/1000 [00:50<06:37,  2.30it/s]

[88/1000]
EN: D. Gukesh secured his first win at Tata Steel Chess Masters 2026.
MNI: দি. গুকেশনা টাটা স্তীল চেস মাস্তর্স ২০২৬দা মহাক্কী অহানবা মায় পাকপা ফংখি।
--------------------------------------------------

Translating MNI:   9%|██▏                     | 89/1000 [00:50<07:45,  1.96it/s]

[89/1000]
EN: Avinash Sable became the first Indian man to qualify for the men’s 3000m steeplechase final at Paris Olympics 2024.
MNI: পেরিস ওলিম্পিক ২০২৪দা নুপাগী মিটর ৩০০০গী স্তিপ্লেকেজ ফাইনেলগী ক্বালিফাই তৌরকপা অহানবা ভারতকী নুপা ওইখি।
--------------------------------------------------

Translating MNI:   9%|██▏                     | 90/1000 [00:51<08:11,  1.85it/s]

[90/1000]
EN: Mirabai Chanu returned to competition as she prepared for upcoming international events.
MNI: মীরাবাই চানুনা লাক্কদৌরিবা ইন্তর্নেস্নেল ইভেন্তশিংগীদমক শেম-শাবা হৌদুনা কম্পিতিসনদা হল্লকখি।
--------------------------------------------------

Translating MNI:   9%|██▏                     | 91/1000 [00:52<08:33,  1.77it/s]

[91/1000]
EN: Manu Bhaker and Harmanpreet Singh among athletes highlighted in a sports-honours post.
MNI: স্পোর্তস-অনর্স পোস্ত অমদা হাইলাইত তৌখিবা এথলেৎশিংগী মরক্তা মানু ভাকার অমসুং হারমনপ্রীত সিংহ য়াওরি।
--------------------------------------------------

Translating MNI:   9%|██▏                     | 92/1000 [00:52<08:59,  1.68it/s]

[92/1000]
EN: At the Milan–Cortina Winter Olympics 2026, Ilia Malinin landed a backflip on one skate in an Olympics moment.
MNI: মিলানকোর্তিনা ৱিনতর ওলিম্পিক ২০২৬দা ইলিয়া মালিনিননা ওলিম্পিক্কী মতম অমদা স্কেট অমদা বেকফ্লিপ অমা লেন্দ তৌখি।
--------------------------------------------------

Translating MNI:   9%|██▏                     | 93/1000 [00:53<08:43,  1.73it/s]

[93/1000]
EN:  Anastasiia Gubanova delivered a performance featuring Indian cultural elements on the ice in Milan.
MNI: মিলানদা আইসতা ভারতকী কলচরেল ইলিমেন্তশিং য়াওবা পর্ফোমেন্স অমা অনস্তাসিয়া গুবানোভানা পীখি।
--------------------------------------------------

Translating MNI:   9%|██▎                     | 94/1000 [00:54<09:30,  1.59it/s]

[94/1000]
EN: Formula One World Championship could return to Indian soil after a 13-year gap as policy issues are addressed.
MNI: পোলিসীগী ইসুশিং কোকহন্দুনা ফোরমুলা ৱান ৱার্ল্দ চেম্পিয়নশিপ অসি চহি ১৩ শুরবা মতুংদা ভারতকী লৈহাউদা হল্লকপা য়াই।
--------------------------------------------------

Translating MNI:  10%|██▎                     | 95/1000 [00:54<09:15,  1.63it/s]

[95/1000]
EN: Nikhat Zareen won 5–0 over Guo Yi Xuan in a bout described as a commanding victory.
MNI: নিখাত জারিননা গুও ই শুয়ানবু ৫-০না মায় পাকখি ।
--------------------------------------------------

Translating MNI:  10%|██▎                     | 96/1000 [00:55<10:20,  1.46it/s]

[96/1000]
EN: Minakshi Hooda and Jaismine Lamboria upset Paris Olympics medallists and top seeds in a major boxing event.
MNI: মরুওইবা বোক্সিং ইভেন্ত অমদা মিনাক্সি হুদা অমসুং জয়সমীন লাম্বোরিয়ানা পেরিস ওলিম্পিককী মেদল্লিশীং অমসুং শক্নাইরবশিং অৱাবা ফোংদোকখি।
--------------------------------------------------

Translating MNI:  10%|██▎                     | 97/1000 [00:56<09:20,  1.61it/s]

[97/1000]
EN: Vinesh Phogat announced a return to wrestling on December 12, 2025.
MNI: বিনেশ ফোগতনা ইং ২০২৫গী দিসেম্বর ১২দা ৱ্রিসলিংদা হল্লকপগী লাউথোকখি।
--------------------------------------------------

Translating MNI:  10%|██▎                     | 98/1000 [00:56<08:52,  1.69it/s]

[98/1000]
EN: Village spectators watching a kabaddi match organised at a makeshift arena.
MNI: মেকশিফত এরেনা অমদা পাংথোকপা কাব্দী মেচ অমা য়েংবা খুঙ্গংগী মীৎয়েং থম্বা মীওইশিং ।
--------------------------------------------------

Translating MNI:  10%|██▍                     | 99/1000 [00:57<08:08,  1.84it/s]

[99/1000]
EN: The 21st Tata Mumbai Marathon took place with large-scale participation in Mumbai.
MNI: ২১শুবা টাটা মুম্বাই মেরাতোন অসি মুম্বাইদা পাক-চাউবা শরুক য়াদুনা পাংথোকখি।
--------------------------------------------------

Translating MNI:  10%|██▎                    | 100/1000 [00:57<08:10,  1.83it/s]

[100/1000]
EN: The first-ever Formula 4 car show on Marina Beach was held on the banks of the sea in Chennai.
MNI: মেরিনা সৈকততা পাংথোকখিবা অহানবা ফোর্ম্যুলা ৪ কার শোয় অসি চেন্নাইগী সমুদ্রতীংবাদা পাংথোকখি।
--------------------------------------------------

Translating MNI:  10%|██▎                    | 101/1000 [00:58<08:39,  1.73it/s]

[101/1000]
EN: Tilak Varma said India felt ready for the high-stakes Pakistan match in Colombo.
MNI: কোলোম্বোদা পাংথোক্কদৌরিবা হাই-ষ্টেক্স পাকিস্থান মেৎচকীদমক ভারতনা শেম-শাদুনা লৈরে হায়না তিলক বার্মানা হায়খি।
--------------------------------------------------

Translating MNI:  10%|██▎                    | 102/1000 [00:58<08:43,  1.72it/s]

[102/1000]
EN: Tilak Varma said the India squad had entered a focused “match zone” mindset.
MNI: তিলক বার্মানা হায়খি মদুদি ইন্দিয়া স্কৱাদনা ফোকস তৌরবা মেচ জোন মাইন্দসেত্তা চংশিল্লে।
--------------------------------------------------

Translating MNI:  10%|██▎                    | 103/1000 [00:59<08:44,  1.71it/s]

[103/1000]
EN: Tilak Varma described the India–Pakistan fixture as a major highlight of the tournament.
MNI: তিলক বার্মানা ইন্দিয়াপাকস্থান ফিক্সচর অসি টুর্নামেন্ত অসিগী মরুওইবা হায়লাইট অমনি হায়না ফোংদোকখি।
--------------------------------------------------

Translating MNI:  10%|██▍                    | 104/1000 [00:59<08:35,  1.74it/s]

[104/1000]
EN: Tilak Varma emphasized preparation and intensity for India ahead of the Pakistan clash.
MNI: তিলক বার্মানা পাকিস্থান থেংনদ্রিঙৈ মমাংদা ভারতকীদমক শেম-শাবা অমসুং অকনবা থৌরাং তৌনবা অকনবা ৱাফম থমখি।
--------------------------------------------------

Translating MNI:  10%|██▍                    | 105/1000 [01:00<08:31,  1.75it/s]

[105/1000]
EN: Tilak Varma framed the Pakistan game as a test of temperament and execution.
MNI: তিলক বার্মানা পাকিস্থান গেম অসি মীনুংশীং অমসুং ইকজেক্সনগী চাংয়েং অমগুম্না ফ্রেম তৌখি।
--------------------------------------------------

Translating MNI:  11%|██▍                    | 106/1000 [01:01<08:53,  1.67it/s]

[106/1000]
EN: Delhi Metro extended operating hours to support fans travelling for the India–Namibia match.
MNI: দিল্লি মেত্রোনা ইন্দিয়ানামিবিয়া মেৎচকীদমক চৎলিবা ফেনশিংবু সপোর্ত তৌনবা ওপরেতিং হোর্স শাংদোকখি।
--------------------------------------------------

Translating MNI:  11%|██▍                    | 107/1000 [01:01<08:52,  1.68it/s]

[107/1000]
EN: Delhi Metro added services to manage crowd flow before and after the India–Namibia game.
MNI: দিল্লি মেত্রোনা ইন্দিয়ানামিবিয়া গেমগী মমাং অমসুং মতুংদা ভিদ ফ্লো মেনেজ তৌনবা সর্বিসশিং হাপচিল্লে।
--------------------------------------------------

Translating MNI:  11%|██▍                    | 108/1000 [01:02<09:22,  1.59it/s]

[108/1000]
EN: City transport officials coordinated services to reduce congestion around the India–Namibia fixture.
MNI: সিতি ত্রান্সপোর্ত ওফিসিয়েলশিংনা ইন্দিয়ানামিবিয়া ফিক্সচরগী অকোয়বদা লম্বী চেনবা হন্থহন্নবা সর্বিসশিং কোওর্দিনেৎ তৌখি।
--------------------------------------------------

Translating MNI:  11%|██▌                    | 109/1000 [01:03<09:05,  1.63it/s]

[109/1000]
EN: Extended metro services aimed to make stadium travel easier for cricket spectators in Delhi.
MNI: দিল্লীগী ক্রিকেৎ য়েংবশিংগীদমক স্তেদিয়ম চৎপা হেন্না লায়থোকহন্নবা মেত্রো সর্বিস পাকথোক চাউথোকহনগনি।
--------------------------------------------------

Translating MNI:  11%|██▌                    | 110/1000 [01:03<08:46,  1.69it/s]

[110/1000]
EN: Additional trains were planned to handle the match-day rush for the India–Namibia crowd.
MNI: ইন্দিয়ানামিবিয়াগী মীয়ামগীদমক মেচ-দে রস হেন্দল তৌনবা অহেনবা ত্রেনশিং প্লান তৌরি।
--------------------------------------------------

Translating MNI:  11%|██▌                    | 111/1000 [01:04<08:40,  1.71it/s]

[111/1000]
EN: Rohit Sharma warned India that confidence alone would not win against Pakistan.
MNI: রোহিত শর্মানা ভারতপু থাজবা অমখক্তনা পাকিস্থানগী মায়োক্তা মায় পাক্লোই হায়না থাজবা পীখি।
--------------------------------------------------

Translating MNI:  11%|██▌                    | 112/1000 [01:04<08:37,  1.72it/s]

[112/1000]
EN: Rohit Sharma urged India to approach Pakistan with discipline, planning, and composure.
MNI: রোহিৎ শর্মানা ভারতপু দিসিপ্লিন, প্লানিং অমসুং কম্পোজরগা লোয়ননা পাকিস্থানদা য়ৌনবা তকশিনখি।
--------------------------------------------------

Translating MNI:  11%|██▌                    | 113/1000 [01:05<08:51,  1.67it/s]

[113/1000]
EN: Rohit Sharma cautioned that India–Pakistan games can ignore rankings and recent form.
MNI: রোহিত শর্মানা হায়খি মদুদি ইন্দিয়াপাকস্থান গেমসনা রেঙ্কিং অমসুং হন্দক্কী ফোর্ম অদু য়েংখিদে।
--------------------------------------------------

Translating MNI:  11%|██▌                    | 114/1000 [01:05<08:29,  1.74it/s]

[114/1000]
EN: Rohit Sharma stressed mental readiness for India before the Pakistan contest.
MNI: রোহিত শর্মানা পাকিস্থান কম্পিতিসনগী মমাংদা ভারতকীদমক মেন্তেল রেদনেসতা অকনবা ৱাফম থমখি।
--------------------------------------------------

Translating MNI:  12%|██▋                    | 115/1000 [01:06<08:43,  1.69it/s]

[115/1000]
EN: Rohit Sharma advised India to avoid underestimating Pakistan in the World Cup clash.
MNI: রোহিৎ শর্মানা ভারতপু ৱার্ল্দ কপ ক্লেশতা পাকিস্থানবু অপুনবা মওংদা য়েংহন্দনবা পাউতাক পীখি।
--------------------------------------------------

Translating MNI:  12%|██▋                    | 116/1000 [01:07<08:49,  1.67it/s]

[116/1000]
EN: Virat Kohli congratulated India’s Under-19 team after the World Cup final victory.
MNI: ৱার্ল্দ কপ ফাইনেল মাই পাক্লবা মতুংদা বিরাত কোহলীনা ভারতকী অনন্দর-১৯ তীমদা নুংঙাইবা ফোংদোকখি।
--------------------------------------------------

Translating MNI:  12%|██▋                    | 117/1000 [01:07<09:19,  1.58it/s]

[117/1000]
EN: India’s Under-19 team won the ICC Under-19 Cricket World Cup final by 100 runs against England.
MNI: ইংলন্দ মায়োক্নবদা ভারতকী অনন্দর-১৯ তীমনা আইসিসি অনন্দর-১৯ ক্রিকেৎ ৱার্ল্দ কপ ফাইনেল রন ১০০ দা মায় পাকখি।
--------------------------------------------------

Translating MNI:  12%|██▋                    | 118/1000 [01:08<09:19,  1.58it/s]

[118/1000]
EN: India secured a sixth Under-19 World Cup title with a commanding final performance.
MNI: ভারতনা অন্দর-১৯ ৱার্ল্দ কপকী তরুকশুবা তাইতল অমা ফাইনেল পর্ফোমেন্স অমগা লোয়ননা ফংখি।
--------------------------------------------------

Translating MNI:  12%|██▋                    | 119/1000 [01:09<09:42,  1.51it/s]

[119/1000]
EN: Celebrations followed India’s Under-19 World Cup triumph over England in the title match.
MNI: তাইটল মেৎচতা ইংলেন্দতগী মায়োক্নখিবা ভারতকী অন্দর-১৯ ৱার্ল্দ কপকী ত্রিম্পহকী মতুংদা থৌরম পাংথোকখি।
--------------------------------------------------

Translating MNI:  12%|██▊                    | 120/1000 [01:09<09:10,  1.60it/s]

[120/1000]
EN: India’s Under-19 success drew praise from senior players across Indian cricket.
MNI: ভারতকী অন্দর-১৯গী মায়পাকপগীদমক ভারতকী ক্রিকেত্তা লৈরিবা সেনিয়র প্লেয়রশিংনা থাগৎপা ফোংদোকখি।
--------------------------------------------------

Translating MNI:  12%|██▊                    | 121/1000 [01:10<08:40,  1.69it/s]

[121/1000]
EN: Dhakshineswar Suresh sparked optimism by delivering a breakthrough stretch for Indian tennis.
MNI: ভারতকী তেনিসকীদমক খোংজেল য়াংহন্দুনা ধাক্সিনেশ্বর সুরেশনা অপাম্বা ফোংদোকখি।
--------------------------------------------------

Translating MNI:  12%|██▊                    | 122/1000 [01:10<09:05,  1.61it/s]

[122/1000]
EN: Dhakshineswar Suresh’s rise has renewed ambition among Indian tennis fans and young players.
MNI: ধাক্সিনেশ্বর সুরেশগী ৱাংখৎলকপনা ভারতকী তেনিস ফেনশিং অমসুং নহা ওইরিবা শান্নরোইশিংগী মরক্তা অপাম্বা নৌহৌনা ফগৎহল্লে।
--------------------------------------------------

Translating MNI:  12%|██▊                    | 123/1000 [01:12<11:53,  1.23it/s]

[123/1000]
EN: Dhakshineswar Suresh’s recent results were described as a turning point for Indian tennis.
MNI: প্রধান মন্ত্রী শ্রী নরেন্দ্র মোদীনা হায়খি মদুদি প্রধান মন্ত্রী শ্রী নরেন্দ্র মোদীনা প্রধান মন্ত্রী শ্রী নরেন্দ্র মোদীগা লোয়ননা প্রধান মন্ত্রী শ্রী নরেন্দ্র মোদীগা লোইননা প্রধান মন্ত্রী শ্রী নরেন্দ্র মোদীগা লোইননা প্রধান মন্ত্রী শ্রী নরেন্দ্র মোদীগা লোইননা প্রধান মন্ত্রী শ্রী নরেন্দ্র মোদীগা লোইননা প্রধান মন্ত্রী শ্রী নরেন্দ্র মোদীগা লোয়নখি ।
--------------------------------------------------

Translating MNI:  12%|██▊                    | 124/1000 [01:12<10:38,  1.37it/s]

[124/1000]
EN: Dhakshineswar Suresh’s performances lifted expectations for Indian tennis on bigger stages.
MNI: ধাক্সিনেশ্বর সুরেশকী পর্ফোমেন্সনা হেন্না চাউবা থাকশিংদা ভারতকী তেনিসকীদমক থাজবা হেনগৎহল্লে।
--------------------------------------------------

Translating MNI:  12%|██▉                    | 125/1000 [01:13<09:58,  1.46it/s]

[125/1000]
EN: Dhakshineswar Suresh’s run created fresh belief about India’s potential in men’s tennis.
MNI: ধাক্সিনেশ্বর সুরেশগী রননা নুপাগী তেনিসতা ভারতকী পোতেন্সিয়েলগী মতাংদা অনৌবা থাজবা অমা শেমখি।
--------------------------------------------------

Translating MNI:  13%|██▉                    | 126/1000 [01:13<09:29,  1.54it/s]

[126/1000]
EN: India’s men’s team exited in the quarterfinals at the Badminton Asia Team Championships.
MNI: বেদমিন্তন এসিয়া তীম চেম্পিয়নশিপতা ভারতকী নুপাগী তীম্না ক্বার্তর ফাইনেলদা চত্থখি।
--------------------------------------------------

Translating MNI:  13%|██▉                    | 127/1000 [01:14<09:02,  1.61it/s]

[127/1000]
EN: India’s women’s team exited in the quarterfinals at the Badminton Asia Team Championships.
MNI: বেদমিন্তন এসিয়া তীম চেম্পিয়নশিপতা ভারতকী নুপীগী তীম্না ক্বার্তর ফাইনেলদা ৱাংখৎখি।
--------------------------------------------------

Translating MNI:  13%|██▉                    | 128/1000 [01:15<08:59,  1.62it/s]

[128/1000]
EN: India failed to defend titles after a double quarterfinal exit in the team championships.
MNI: টিম চেম্পিয়নশিপতা ভারতনা দবল ক্বার্তর ফাইনেল এসিৎ তৌরবা মতুংদা তাইতল ঙাকথোকপা ঙমখিদ্রে।
--------------------------------------------------

Translating MNI:  13%|██▉                    | 129/1000 [01:15<08:26,  1.72it/s]

[129/1000]
EN: Strong opposition ended India’s campaign early at the Badminton Asia Team Championships.
MNI: বেদমিন্তন এসিয়া তীম চেম্পিয়নশিপতা ভারতকী কেম্পেইন অদু অকনবা ওপোজিসননা লোইশিনখি।
--------------------------------------------------

Translating MNI:  13%|██▉                    | 130/1000 [01:16<08:08,  1.78it/s]

[130/1000]
EN: The quarterfinal losses ended India’s hopes of a title defence at the event.
MNI: ক্বার্তর ফাইনেলদা মাংখিবা অসিনা ইভেন্ত অসিদা ভারতকী তাইটল দিফেন্সকী থাজবা লোইশিনখি।
--------------------------------------------------

Translating MNI:  13%|███                    | 131/1000 [01:16<07:39,  1.89it/s]

[131/1000]
EN: Sumit Nagal was scheduled to open his tournament campaign against Guy Den Ouden.
MNI: গাই দেন উদনগী মায়োক্তা সুমিৎ নাগালনা মহাক্কী তর্নামেন্ত কেম্পেইন হৌদোক্কনি।
--------------------------------------------------

Translating MNI:  13%|███                    | 132/1000 [01:17<07:44,  1.87it/s]

[132/1000]
EN: Sumit Nagal drew Dutch player Guy Den Ouden in an opening-round matchup.
MNI: সুমিত নাগালনা ওফনিং-রাউন্দ মেচ অপ অমদা দচকী শান্নরোই গাই দেন ওউদনবু দ্রো তৌখি।
--------------------------------------------------

Translating MNI:  13%|███                    | 133/1000 [01:17<07:54,  1.83it/s]

[133/1000]
EN: Sumit Nagal’s first-round pairing set up an early test against Guy Den Ouden.
MNI: সুমিত নাগলগী ফার্ষ্ত-রাউন্দ পেয়রিংনা গাই দেন উদনগী মায়োক্তা অঙনবা চাংয়েং অমা শেমখি।
--------------------------------------------------

Translating MNI:  13%|███                    | 134/1000 [01:18<07:40,  1.88it/s]

[134/1000]
EN: Sumit Nagal prepared for a fresh challenge against Guy Den Ouden in round one.
MNI: গুয় দেন উদেন্না মায়োক্ননবা অহানবা রাউন্দদা সুমিৎ নাগালনা অনৌবা চেলেঞ্জ অমা শেম শারি।
--------------------------------------------------

Translating MNI:  14%|███                    | 135/1000 [01:18<07:08,  2.02it/s]

[135/1000]
EN: Sumit Nagal began a new event with an opening match against Guy Den Ouden.
MNI: গায় দেন উদেন্না মায়োক্নদুনা সুমিৎ নাগলনা অনৌবা থৌরম অমা হৌদোকখি।
--------------------------------------------------

Translating MNI:  14%|███▏                   | 136/1000 [01:19<08:05,  1.78it/s]

[136/1000]
EN: An analysis said T20 cricket keeps evolving through new strategies and fast-changing trends.
MNI: এনালাইসিস অমনা হায়খি মদুদি টি২০ ক্রিকেত্তা অনৌবা স্ত্রেতেজিশিং অমসুং খোংজেল য়াংনা হোংলক্লিবা ত্রেন্দশিংগী খুত্থাংদা ইভোলুসন লৈরি।
--------------------------------------------------

Translating MNI:  14%|███▏                   | 137/1000 [01:19<08:14,  1.75it/s]

[137/1000]
EN: A feature noted the ICC Men's T20 World Cup returned to India after a decade-long gap.
MNI: আই সি সি মেনস টি২০ ৱার্ল্দ কপ অসি ভারততা চহী তরা শুরবা মতুংদা অমুক হন্না লাক্লে হায়না ফিচর অমনা ফোংদোকখি।
--------------------------------------------------

Translating MNI:  14%|███▏                   | 138/1000 [01:20<08:04,  1.78it/s]

[138/1000]
EN: T20 cricket was described as a format that continually reinvents tactics and team plans.
MNI: টি২০ ক্রিকেত্তা লেপ্তনা তেক্টিক্স অমসুং তীম প্লানশিং নৌনা শেমগৎলিবা ফোর্মেৎ অমা ওইনা শন্দোক্না তাক্লি।
--------------------------------------------------

Translating MNI:  14%|███▏                   | 139/1000 [01:21<08:33,  1.68it/s]

[139/1000]
EN: A commentary highlighted how technology and data shape modern T20 decision-making.
MNI: তেক্নোলোজী অমসুং দেতানা মোদর্ন টি২০গী ৱারেপ লৌবদা মতৌ করম্না মওং-মতৌ পীবগে হায়বগী মতাংদা কমমেন্তরী অমদা পনখি।
--------------------------------------------------

Translating MNI:  14%|███▏                   | 140/1000 [01:21<08:25,  1.70it/s]

[140/1000]
EN: A tournament preview underlined T20 cricket’s cultural impact and mass appeal in India.
MNI: টুর্নামেন্তকী প্রিভিয়ু অমনা ভারত্তা টি২০ ক্রিকেৎকী কলচরেল ইম্পেক্ত অমসুং মীয়ামগী অপীল অদু পনখি।
--------------------------------------------------

Translating MNI:  14%|███▏                   | 141/1000 [01:22<08:29,  1.69it/s]

[141/1000]
EN: Kapil Dev was listed among participants at the PM Rungta Memorial Golf Cup in Jaipur.
MNI: জয়পুরদা পাংথোকপা প্রধান মন্ত্রী রুংতা মেমোরিয়েল গোল্ফ কপতা শরুক য়ারিবশিংগী মরক্তা কপিল দেবসু য়াওখি।
--------------------------------------------------

Translating MNI:  14%|███▎                   | 142/1000 [01:22<08:51,  1.61it/s]

[142/1000]
EN: Madan Lal was listed among participants at the PM Rungta Memorial Golf Cup in Jaipur.
MNI: মদন লাল অসি জয়পুরদা পাংথোকপা প্রধান মন্ত্রী রুংতা মেমোরিয়েল গোল্ফ কপতা শরুক য়ারিবশিংগী মরক্তা য়াওখি।
--------------------------------------------------

Translating MNI:  14%|███▎                   | 143/1000 [01:23<08:40,  1.65it/s]

[143/1000]
EN: The PM Rungta Memorial Golf Cup was scheduled for February 8, 2026 in Jaipur.
MNI: প্রধান মন্ত্রী রুংতা মেমোরিয়েল গোল্ফ কপ অসি ২০২৬গী ফেব্রুৱারী ৮দা জয়পুরদা পাংথোক্কনি।
--------------------------------------------------

Translating MNI:  14%|███▎                   | 144/1000 [01:24<08:16,  1.73it/s]

[144/1000]
EN: Rambagh Golf Club was named as the venue for the memorial golf tournament.
MNI: রামবাগ গোল্ফ ক্লব অসি মেমোরিয়েল গোল্ফ তুর্নামেন্তকী মফম ওইনা কৌখি।
--------------------------------------------------

Translating MNI:  14%|███▎                   | 145/1000 [01:24<08:57,  1.59it/s]

[145/1000]
EN: Organisers said the golf cup used a Stableford Single Peoria format for inclusive competition.
MNI: ওর্গানাইজরশিংনা হায়খি মদুদি গোল্ফ কপ অসিনা ইনক্লুসিব কম্পিতিসনগীদমক স্তেবলফোর্দ সিঙ্গল পেরিয়া ফোর্মেৎ অমা শিজিন্নখি।
--------------------------------------------------

Translating MNI:  15%|███▎                   | 146/1000 [01:25<09:29,  1.50it/s]

[146/1000]
EN: A schedule note said United States would face Netherlands in Chennai to close February 13’s action.
MNI: ফেব্রুৱারী ১৩দা পাংথোকখিবা এক্সন লোইশিন্নবা চেন্নাইদা য়ুনাইতেদ স্তেৎসনা নেদরলেন্দসকা মায়োক্নগনি হায়না সেদ্যুল নোৎ অমদা হায়খি।
--------------------------------------------------

Translating MNI:  15%|███▍                   | 147/1000 [01:26<08:59,  1.58it/s]

[147/1000]
EN: The USA–Netherlands match was presented as important for points and pride in the group.
MNI: য়ু এস এনেদর্লেন্দ মেৎচ অসি পোইন্তকীদমক মরুওইবা অমসুং গ্রুপ অসিদা চাউথোকচবা অমনি হায়না উৎখি।
--------------------------------------------------

Translating MNI:  15%|███▍                   | 148/1000 [01:26<09:04,  1.56it/s]

[148/1000]
EN: A match preview framed USA against Netherlands as a tight contest between associate nations.
MNI: মেটচ প্রিভিউ অমনা য়ু এস এ অমসুং নেদর্লেন্দগী মরক্তা মরী লৈনবা লৈবাকশিংগী মরক্তা শাথীনা শান্নবা অমা ওইনা ফ্রেম তৌখি।
--------------------------------------------------

Translating MNI:  15%|███▍                   | 149/1000 [01:27<08:37,  1.65it/s]

[149/1000]
EN: A schedule roundup highlighted February 13 fixtures as key for shaping group standings.
MNI: সেদ্যুল রাউন্দঅপ অমনা গ্রুপ স্তেন্দিং শেপ্পদা মরুওইবা ওইনা ফেব্রুৱারী ১৩গী ফিক্সচরশিং উৎখি।
--------------------------------------------------

Translating MNI:  15%|███▍                   | 150/1000 [01:27<08:32,  1.66it/s]

[150/1000]
EN: A preview said the final February 13 match would be played at MA Chidambaram Stadium.
MNI: ফাইনেল মেচ ফেব্রুৱারী ১৩ অসি এম এ চিদাম্বরম স্তেদিয়মদা পাংথোক্কনি হায়না প্রিভিউ অমনা হায়খি।
--------------------------------------------------

Translating MNI:  15%|███▍                   | 151/1000 [01:28<08:19,  1.70it/s]

[151/1000]
EN: Indian Super League clubs requested a pause on relegation for three to five years.
MNI: ইন্দিয়ান সুপর লীগ ক্লবশিংনা রিলিগেসনদা চহি অহুমদগী মঙাদ ফাউবা থমজিনবা হায়জখি।
--------------------------------------------------

Translating MNI:  15%|███▍                   | 152/1000 [01:29<08:15,  1.71it/s]

[152/1000]
EN: ISL clubs argued that pausing relegation would provide stability for long-term planning.
MNI: আইএসএল ক্লবশিংনা হায়খি মদুদি রিলিগেসন লেপহনবনা অশাংবা মতমগী প্লানিংগীদমক লেপ্পা লৈতবা লৈহল্লগনি।
--------------------------------------------------

Translating MNI:  15%|███▌                   | 153/1000 [01:29<07:56,  1.78it/s]

[153/1000]
EN: Several ISL teams asked administrators to consider a temporary relegation freeze.
MNI: আইএসএলগী টিম কয়ানা এদমিনিস্ত্রেতরশিংদা তেম্পরেরি রিলেগেসন ফ্রিজ অমা খন্ননবা হায়খি।
--------------------------------------------------

Translating MNI:  15%|███▌                   | 154/1000 [01:30<07:48,  1.81it/s]

[154/1000]
EN: The request on relegation was framed as a measure to protect club investments.
MNI: রিলিগেসনগী রিক্বেস্ত অসি ক্লব ইনভেস্তমেন্তশিং ঙাকথোক্নবা খোংথাং অমা ওইনা শেমখি।
--------------------------------------------------

Translating MNI:  16%|███▌                   | 155/1000 [01:30<08:27,  1.67it/s]

[155/1000]
EN: ISL stakeholders debated relegation rules while seeking clarity for the 2025–26 season.
MNI: ২০২৫২৬গী সিজনগী মতাংদা খংহন্নবা হোৎনরিঙৈদা আইএসএলগী স্তেকহোল্দরশিংনা রিলেগেসন রুলসতা খন্ন-নৈনখি।
--------------------------------------------------

Translating MNI:  16%|███▌                   | 156/1000 [01:31<08:08,  1.73it/s]

[156/1000]
EN: India produced a 3–2 win over Netherlands in Davis Cup Qualifiers Round 1.
MNI: দেবিস কপ ক্বালিফায়রস রাউন্দ ১দা নেদর্লেন্দগী মায়োক্নবদা ভারতনা ৩২ মায় পাকখি।
--------------------------------------------------

Translating MNI:  16%|███▌                   | 157/1000 [01:31<08:30,  1.65it/s]

[157/1000]
EN: India advanced to the second Davis Cup qualifying round after beating Netherlands 3–2.
MNI: নেদর্লেন্দসপু ৩-২না মায়থীবা পীদুনা ভারতনা অনিশুবা দেবিস কপ ক্বালিফাইয়িং রাউন্দতা চংশিল্লি।
--------------------------------------------------

Translating MNI:  16%|███▋                   | 158/1000 [01:32<08:36,  1.63it/s]

[158/1000]
EN: India’s Davis Cup team was described as thriving against higher-ranked opponents recently.
MNI: হন্দক্তা ভারতকী দেভিস কপ তীম অসি হেন্না ৱাংখৎপা ওপোনেন্তশিংগী মায়োক্তা মায় পাক্লি হায়না ফোংদোকখি।
--------------------------------------------------

Translating MNI:  16%|███▋                   | 159/1000 [01:33<08:44,  1.60it/s]

[159/1000]
EN: The Davis Cup tie at SM Krishna Tennis Stadium went down to the wire.
MNI: এস.এম.কৃষ্ণ তেনিস স্তেদিয়মদা পাংথোকখিবা দেভিস কপকী শান্নখিবা অদু ৱায়রদা লৈখিদ্রে।
--------------------------------------------------

Translating MNI:  16%|███▋                   | 160/1000 [01:33<08:27,  1.65it/s]

[160/1000]
EN: India’s Davis Cup success followed an earlier victory over Switzerland in Biel last year.
MNI: ভারতনা দেবিস কপ মায় পাকখিবা অসি মমাংগী চহিদা বাইলদা সুইৎজারলেন্দগী মায় পাকখিবা অদুগী মতুংদা ওইখি।
--------------------------------------------------

Translating MNI:  16%|███▋                   | 161/1000 [01:34<08:10,  1.71it/s]

[161/1000]
EN: The India Open was kept as a Super 750 tournament for the 2027–2030 cycle.
MNI: ইন্দিয়া ওপন অসি ২০২৭২০৩০গী সাইকলগী সুপর ৭৫০ টুর্নামেন্ত অমা ওইনা থমখি।
--------------------------------------------------

Translating MNI:  16%|███▋                   | 162/1000 [01:34<08:22,  1.67it/s]

[162/1000]
EN: Players criticised conditions, yet organisers retained the India Open’s Super 750 status.
MNI: শান্নরোইশিংনা কন্দিসনশিং অদু কন্ত্রাইক্ত তৌখি অদুবু ওর্গানাইজরশিংনা ইন্দিয়া ওপনগী সুপর ৭৫০ স্তেতস অদু লেংদনা থমখি।
--------------------------------------------------

Translating MNI:  16%|███▋                   | 163/1000 [01:35<08:42,  1.60it/s]

[163/1000]
EN: Badminton World Federation announced a revamped World Tour structure with six tournament levels.
MNI: বেদমিন্তন ৱার্ল্দ ফেদরেসননা তুরনমেন্ত লেভেল তরুক য়াওনা নৌনা শেমদোক্লবা ৱার্ল্দ তুর স্ত্রকচর অমা লাউথোকখি।
--------------------------------------------------

Translating MNI:  16%|███▊                   | 164/1000 [01:36<08:33,  1.63it/s]

[164/1000]
EN: The BWF updated World Tour plan included 36 tournaments across multiple tiers.
MNI: বি দবল্যু এফনা অপদেৎ তৌরবা ৱার্ল্দ তুর প্লানদা মল্তিপল তেরশিংদা টুর্নামেন্ত ৩৬ য়াউখি।
--------------------------------------------------

Translating MNI:  16%|███▊                   | 165/1000 [01:36<08:46,  1.59it/s]

[165/1000]
EN: The BWF said annual World Tour prize money would rise to about 26.9 million dollars.
MNI: বি দবল্যু এফনা হায়খি মদুদি চহিগী ৱার্ল্দ তুর প্রাইজ মনি অসি চাউরাক্না দোল্লর মিলিয়ন ২৬.৯দা হেনগৎলক্কনি।
--------------------------------------------------

Translating MNI:  17%|███▊                   | 166/1000 [01:37<08:32,  1.63it/s]

[166/1000]
EN: A schedule preview listed Sri Lanka against Oman as a February 12 group-stage fixture.
MNI: সেদ্যুল প্রিভিউ অমনা শ্রীলঙ্কাবু ওমানগী মায়োক্তা ফেব্রুৱারী ১২গী গ্রুপ-ষ্টেজ ফিক্সচর অমা ওইনা পনখি।
--------------------------------------------------

Translating MNI:  17%|███▊                   | 167/1000 [01:38<08:21,  1.66it/s]

[167/1000]
EN: A schedule preview listed Nepal against Italy as a February 12 group-stage fixture.
MNI: সেদ্যুল প্রিভিউ অমনা নেপালবু ইতালিগী মায়োক্তা ফেব্রুৱারী ১২গী গ্রুপ-ষ্টেজ ফিক্সচর অমা ওইনা পনখি।
--------------------------------------------------

Translating MNI:  17%|███▊                   | 168/1000 [01:38<08:07,  1.71it/s]

[168/1000]
EN: A schedule preview listed India against Namibia as a February 12 group-stage fixture.
MNI: সেদ্যুল প্রিভিউ অমনা ভারতনা নামিবিয়াগী মায়োক্তা ফেব্রুৱারী ১২গী গ্রুপ-স্তেজ ফিক্সচর অমা ওইনা পনখি।
--------------------------------------------------

Translating MNI:  17%|███▉                   | 169/1000 [01:39<07:34,  1.83it/s]

[169/1000]
EN: Wanindu Hasaranga was ruled out of the World Cup due to an injury setback.
MNI: অশোক-অপন থোক্তবনা মরম ওইদুনা ৱানিন্দু হসরঙ্গা ৱার্ল্দ কপতা য়াওখিদ্রে।
--------------------------------------------------

Translating MNI:  17%|███▉                   | 170/1000 [01:39<07:47,  1.77it/s]

[170/1000]
EN: Sri Lanka named Dushan Hemantha as a replacement after Wanindu Hasaranga’s injury.
MNI: ৱানিন্দু হসরঙ্গাগী অশোক-অপনগী মতুংদা শ্রীলঙ্কানা দুশান হেমান্থাবু মহুৎ শিনবা ওইনা মমিং থোনখি।
--------------------------------------------------

Translating MNI:  17%|███▉                   | 171/1000 [01:40<07:09,  1.93it/s]

[171/1000]
EN: The Indian Super League season was announced to begin on February 14, 2026.
MNI: ইন্দিয়ান সুপর লীগ সিজন অসি ফেব্রুৱারী ১৪, ২০২৬দা হৌগনি হায়না লাউথোকখি।
--------------------------------------------------

Translating MNI:  17%|███▉                   | 172/1000 [01:40<06:56,  1.99it/s]

[172/1000]
EN: Sports minister Mansukh Mandaviya announced an ISL start date of February 14.
MNI: স্পোর্ত মন্ত্রী মনসুখ মন্দাবিয়ানা ফেব্রুৱরী ১৪দা আইএসএল হৌদোকপগী তাং লাউথোকখি।
--------------------------------------------------

Translating MNI:  17%|███▉                   | 173/1000 [01:41<07:05,  1.95it/s]

[173/1000]
EN: All 14 clubs agreed to participate in the Indian Super League season, according to reports.
MNI: ক্লব ১৪ পুম্নমক্না ইন্দিয়ান সুপর লীগ সিজনদা শরুক য়ানবা য়ানখি হায়না রিপোর্তশিংগী মতুংইন্না হায়খি।
--------------------------------------------------

Translating MNI:  17%|████                   | 174/1000 [01:41<07:23,  1.86it/s]

[174/1000]
EN: The ISL decision followed meetings between the sports ministry and the All India Football Federation.
MNI: আইএসএলগী ৱারেপ অসি স্পোর্ত মন্ত্রালয় অমসুং ওল ইন্দিয়া ফুটবোল ফেদরেসনগী মরক্তা পাংথোকপা মীফমগী মতুংদা লাকখি।
--------------------------------------------------

Translating MNI:  18%|████                   | 175/1000 [01:42<07:24,  1.86it/s]

[175/1000]
EN: Indian football’s top-tier season moved forward after clubs accepted the participation plan.
MNI: পার্তিসিপেসন প্লান অদু ক্লবশিংনা য়াবা মতুংদা ইন্দিয়ান ফুটবোলগী মকোক থোংবা সিজন অসি মখা চত্থখি।
--------------------------------------------------

Translating MNI:  18%|████                   | 176/1000 [01:42<07:34,  1.81it/s]

[176/1000]
EN: India’s women lost 0–3 to China in the Badminton Asia Team Championships quarterfinals.
MNI: বেদমিন্তন এসিয়া তীম চেম্পিয়নশিপকী ক্বাতর ফাইনেলদা ভারতকী নুপীশিংনা চাইনাদা ০৩না মাংখি।
--------------------------------------------------

Translating MNI:  18%|████                   | 177/1000 [01:43<07:44,  1.77it/s]

[177/1000]
EN: P. V. Sindhu missed the team quarterfinal because of a minor injury, according to reports.
MNI: রিপোর্তশিংগী মতুংইন্না অপিকপা অশোক-অপন অমা লৈবনা মরম ওইদুনা পি ভি সিন্ধুনা তীম ক্বাতর ফাইনেল মাংখি।
--------------------------------------------------

Translating MNI:  18%|████                   | 178/1000 [01:43<07:00,  1.96it/s]

[178/1000]
EN: India’s women struggled to defend the 2024 title without PV Sindhu in the lineup.
MNI: ভারতকী নুপীশিংনা পিভি সিন্ধু য়াওদনা ২০২৪গী তাইটল ঙাকথোক্নবা হোৎনখি।
--------------------------------------------------

Translating MNI:  18%|████                   | 179/1000 [01:44<06:53,  1.99it/s]

[179/1000]
EN: China ended India’s women’s title defence with a straight 3–0 quarterfinal win.
MNI: চাইনানা ভারতকী ৱুমেন তাইটল দিফেন্স অসি ক্বাতর ফাইনেল ৩০গী মায় পাকপগা লোইশিনখি।
--------------------------------------------------

Translating MNI:  18%|████▏                  | 180/1000 [01:44<07:11,  1.90it/s]

[180/1000]
EN: The quarterfinal defeat closed India’s women’s campaign at the Badminton Asia Team Championships.
MNI: ক্বার্তর ফাইনেল মায়থীবা অসিনা বেদমিন্তন এসিয়া তীম চেম্পিয়নশিপতা ভারতকী নুপীগী কেম্পেইন লোইশিনখি।
--------------------------------------------------

Translating MNI:  18%|████▏                  | 181/1000 [01:45<07:20,  1.86it/s]

[181/1000]
EN: Devika Sihag won the Thailand Masters 2026 to claim a BWF Super 300 title.
MNI: দেবিকা সিহাগনা থাইলেন্দ মাস্তর্স ২০২৬ মায় পাক্লদুনা বি দবল্যু এফ সুপর ৩০০গী তাইটল অমা লৌখি।
--------------------------------------------------

Translating MNI:  18%|████▏                  | 182/1000 [01:45<07:24,  1.84it/s]

[182/1000]
EN: Devika Sihag became the youngest Indian woman to win a BWF Super 300 singles title.
MNI: দেবিকা সিহাগ অসি বি দবল্যু এফ সুপর ৩০০ সিঙ্গলসকী তাইটল অমা লৌখিবা খ্বাইদগী নহা ওইরবা ভারতকী নুপী ওইখি।
--------------------------------------------------

Translating MNI:  18%|████▏                  | 183/1000 [01:46<07:54,  1.72it/s]

[183/1000]
EN: Devika Sihag joined Saina Nehwal and PV Sindhu in an exclusive Indian milestone list.
MNI: দেবিকা সিহাগনা সাইনা নেহৱাল অমসুং পিভি সিন্ধুগা লোয়ননা এক্স্ক্লুসিভ ওইবা ভারতকী মাইলস্তোন লিস্ত অমদা শরুক য়াখি।
--------------------------------------------------

Translating MNI:  18%|████▏                  | 184/1000 [01:47<07:43,  1.76it/s]

[184/1000]
EN: Devika Sihag’s Bangkok celebration marked a breakthrough moment for Indian women’s singles.
MNI: দেবিকা সিহাগকী বেঙ্গকোক থৌরমনা ভারতকী নুপী সিঙ্গলসকীদমক্তা খোংচৎ অমা ওইখি।
--------------------------------------------------

Translating MNI:  18%|████▎                  | 185/1000 [01:47<08:05,  1.68it/s]

[185/1000]
EN: Devika Sihag’s title was described as a quiet announcement of a new Indian badminton star.
MNI: দেবিকা সিহাগগী শক্লোন অসি অনৌবা ভারতকী বেদমিন্তন ষ্টার অমা শিংথানীংঙাই ওইহন্দুনা লাউথোকখিবনি হায়না ফোংদোকখি।
--------------------------------------------------

Translating MNI:  19%|████▎                  | 186/1000 [01:48<08:07,  1.67it/s]

[186/1000]
EN: A matchday note listed Afghanistan against South Africa in Ahmedabad on February 11.
MNI: ফেব্রুৱারী ১১দা অহমেদাবাদতা পাংথোকখিবা মেচ দে নোট অমদা অফগানিস্থাননা সাউথ আফ্রিকাগী মায়োক্তা শান্নখি।
--------------------------------------------------

Translating MNI:  19%|████▎                  | 187/1000 [01:49<08:10,  1.66it/s]

[187/1000]
EN: A matchday note listed Australia against Ireland as another February 11 group-stage fixture.
MNI: মেচ দে নোট অমদা ওস্ত্রেলিয়ানা আইরলেন্দগী মায়োক্নবদা ফেব্রুৱারী ১১গী গ্রুপ-ষ্টেজ ফিক্সচর অমা ওইনা পনখি।
--------------------------------------------------

Translating MNI:  19%|████▎                  | 188/1000 [01:49<08:04,  1.68it/s]

[188/1000]
EN: A matchday note listed England against West Indies as a February 11 evening fixture.
MNI: মেচ দে নোট অমদা ইংলেন্দনা ৱেস্ত ইন্দিজগী মায়োক্তা ফেব্রুৱরী ১১গী নুমিদাংৱাইরমগী ফিক্তচর অমা ওইনা পনখি।
--------------------------------------------------

Translating MNI:  19%|████▎                  | 189/1000 [01:50<08:02,  1.68it/s]

[189/1000]
EN: Afghanistan sought a rebound after losing their opener against New Zealand, according to reports.
MNI: রিপোর্টশিংগী মতুংইন্না আফগানিস্থাননা মখোয়গী ওপনর অদু ন্যু জিলেন্দগী মায়থীবা পীরবা মতুংদা রিবাউন্দ অমা পামখি।
--------------------------------------------------

Translating MNI:  19%|████▎                  | 190/1000 [01:50<08:21,  1.62it/s]

[190/1000]
EN: The February 11 schedule mixed former champions, contenders, and dangerous underdogs in group play.
MNI: ফেব্রুৱারী ১১গী সেদ্যুলদা গ্রুপ প্লেদা হান্নগী চেম্পিয়নশিং, কন্তেনদরশিং অমসুং খুদোংথীনিঙাই ওইবা ওন্দরদোগশিং য়াওখি।
--------------------------------------------------

Translating MNI:  19%|████▍                  | 191/1000 [01:51<08:33,  1.58it/s]

[191/1000]
EN: Baichung Bhutia blamed administration after Churchill Brothers were not added to ISL 2025–26.
MNI: চর্চিল ব্রাদরসনা আইএসএল ২০২৫২৬দা হাপচিন্দ্রবা মতুংদা বাইচুং ভুতিয়ানা এদমিনিস্ত্রেসনবু মায়োক্নখি।
--------------------------------------------------

Translating MNI:  19%|████▍                  | 192/1000 [01:52<08:25,  1.60it/s]

[192/1000]
EN: Churchill Brothers were not included in ISL 2025–26, prompting criticism from Baichung Bhutia.
MNI: চর্চিল ব্রাদরস অসি আইএসএল ২০২৫২৬দা য়াউখিদে মরম অদুনা বাইচুং ভুতীয়াগী মায়কৈদগী ক্রিতিক লাকখি।
--------------------------------------------------

Translating MNI:  19%|████▍                  | 193/1000 [01:52<08:22,  1.61it/s]

[193/1000]
EN: Baichung Bhutia called the Churchill Brothers exclusion a clear administrative failure.
MNI: বাইচুং ভুতিয়ানা চর্চিল ব্রাদরসবু মপান্দা থাদোকপদু ময়েক শেংবা এদমিনিস্ত্রেতিব ফেসেল অমনি হায়না লৌখি।
--------------------------------------------------

Translating MNI:  19%|████▍                  | 194/1000 [01:53<07:58,  1.68it/s]

[194/1000]
EN: The Churchill Brothers decision raised questions about the league’s selection and governance.
MNI: চর্চিল ব্রাদর্সকী ৱারেপ অসিনা লীগ অসিগী সেলেক্সন অমসুং গবর্নান্সকী মতাংদা ৱাহংশীং কয়া থোরকখি।
--------------------------------------------------

Translating MNI:  20%|████▍                  | 195/1000 [01:53<08:00,  1.67it/s]

[195/1000]
EN: The ISL debate intensified after the Churchill Brothers issue surfaced in public comments.
MNI: চর্চিল ব্রাদর্স ইসু অসি মীয়ামগী কমেন্টশিংদা থোরকপা মতুংদা আইএসএলগী খন্ন-নৈনবশিং অদু হেন্না চেৎশিল্লকখি।
--------------------------------------------------

Translating MNI:  20%|████▌                  | 196/1000 [01:54<07:58,  1.68it/s]

[196/1000]
EN: India–Netherlands Davis Cup tie tightened after Sumit Nagal suffered a setback.
MNI: ভারতনেদর্লেন্দস দেবিস কপকী শান্নরোই ওইবগী চাং অসি সুমিত নাগলনা মায়োক্নরকপদগী হেন্না চেৎশিল্লকখি।
--------------------------------------------------

Translating MNI:  20%|████▌                  | 197/1000 [01:55<07:44,  1.73it/s]

[197/1000]
EN: Sumit Nagal’s result added pressure as the Davis Cup tie moved toward a tense finish.
MNI: সুমিৎ নাগলগী রিজল্তনা দেবিস কপকী টাই অদু মওং চুম্না ফাই ওইরকপগা লোয়ননা প্রেসর হেঙ্গৎহল্লে।
--------------------------------------------------

Translating MNI:  20%|████▌                  | 198/1000 [01:55<07:24,  1.80it/s]

[198/1000]
EN: India and Netherlands remained locked in a close Davis Cup contest after the Nagal match.
MNI: নেদরলেন্দ অমসুং ভারতনা নাগাল মেৎচ মতুংদা দেভিস কপকী কন্তেক্স অমগা লোইননা শান্নখিদে।
--------------------------------------------------

Translating MNI:  20%|████▌                  | 199/1000 [01:56<07:29,  1.78it/s]

[199/1000]
EN: The Davis Cup tie needed late composure after the Sumit Nagal setback, according to reports.
MNI: রিপোর্তশিংগী মতুংইন্না সুমিত নাগলগী সেতবেককী মতুংদা দেভিস কপকী টাই অদু লেট কম্পোজরগী মথৌ তাখি।
--------------------------------------------------

Translating MNI:  20%|████▌                  | 200/1000 [01:56<07:11,  1.85it/s]

[200/1000]
EN: The Bengaluru Davis Cup atmosphere stayed intense as India fought Netherlands in a tight tie.
MNI: নেদর্লেন্দসকা থেংনখিবা অদুদা বেঙ্গালুরু দেভিস কপকী ফিভম অসি য়াম্না শাথীনা লৈখি।
--------------------------------------------------

Translating MNI:  20%|████▌                  | 201/1000 [01:57<07:29,  1.78it/s]

[201/1000]
EN: International Cricket Council confirmed the 2026 Men’s T20 World Cup starts on February 7.
MNI: ইন্তর্নেস্নেল ক্রিকেৎ কাউন্সিলনা ফেব্রুৱারী ৭দা ২০২৬ মেনস টি২০ ৱার্ল্দ কপ হৌরগনি হায়না কনফার্ম তৌখ্রে।
--------------------------------------------------

Translating MNI:  20%|████▋                  | 202/1000 [01:57<06:55,  1.92it/s]

[202/1000]
EN: India were placed in Group A alongside Pakistan, Netherlands, USA, and Namibia.
MNI: ভারত অসি পাকিস্থান, নেদর্লেন্দস, য়ু এস এ অমসুং নামিবিয়াগা লোয়ননা গ্রুপ এদা থমখি।
--------------------------------------------------

Translating MNI:  20%|████▋                  | 203/1000 [01:58<06:47,  1.95it/s]

[203/1000]
EN: Sri Lanka hosted several matches as the tournament ran across India and Sri Lanka venues.
MNI: ভারত অমসুং শ্রীলঙ্কাগী মফম কয়াদা টুর্নামেন্ত অসি পাংথোকপদা শ্রীলঙ্কানা মেচ কয়া শান্নখি।
--------------------------------------------------

Translating MNI:  20%|████▋                  | 204/1000 [01:58<06:41,  1.98it/s]

[204/1000]
EN: India played the opening match against the USA at Wankhede Stadium in Mumbai.
MNI: ভারতনা মুম্বাইগী ৱাঙ্খেদে স্তেদিয়মদা হৌদোকপগী মেটচ অদু য়ু এস এগী মায়োক্তা শান্নখি।
--------------------------------------------------

Translating MNI:  20%|████▋                  | 205/1000 [01:59<06:34,  2.02it/s]

[205/1000]
EN: India faced Namibia on February 12 at Arun Jaitley Stadium in New Delhi.
MNI: ভারতনা ন্যু দিল্লীগী অরুন জেতলী স্তেদিয়মদা ফেব্রুৱারী ১২দা নামিবিয়াগা মায়োক্নখি।
--------------------------------------------------

Translating MNI:  21%|████▋                  | 206/1000 [01:59<06:07,  2.16it/s]

[206/1000]
EN: India travelled to Colombo to play Pakistan in a group-stage match.
MNI: গ্রুপ-স্তেজ মেৎচ অমদা ভারতনা পাকিস্থান মায়োক্ননবা কোলোম্বোদা চৎখি।
--------------------------------------------------

Translating MNI:  21%|████▊                  | 207/1000 [01:59<06:03,  2.18it/s]

[207/1000]
EN: Pakistan versus Netherlands was listed as a Group A fixture on February 7.
MNI: ফেব্রুৱারী ৭দা পাকিস্থান বনাম নেদর্লেন্দস অসি গ্রুপ এ ফিক্সচর অমা ওইনা লিস্ত তৌখি।
--------------------------------------------------

Translating MNI:  21%|████▊                  | 208/1000 [02:00<06:00,  2.20it/s]

[208/1000]
EN: India versus USA was scheduled as a Group A match on February 7.
MNI: ফেব্রুৱারী ৭দা গ্রুপ এগী মেটচ অমা ওইনা ভারত অমসুং য়ু এস এগী মায়োক্ননবা সেদ্যুল তৌরি।
--------------------------------------------------

Translating MNI:  21%|████▊                  | 209/1000 [02:00<06:10,  2.13it/s]

[209/1000]
EN: Group D fixtures began with Afghanistan playing New Zealand on February 8 in Chennai.
MNI: গ্রুপ Dগী ফিক্সচরশিং ফেব্রুৱারী ৮দা চেন্নাইদা অফগানিস্থাননা ন্যু জিলেন্দ মায়োক্নদুনা হৌখি।
--------------------------------------------------

Translating MNI:  21%|████▊                  | 210/1000 [02:01<06:23,  2.06it/s]

[210/1000]
EN: Canada played South Africa on February 9 at Narendra Modi Stadium in Ahmedabad.
MNI: কানাদানা ফেব্রুৱারী ৯দা অহমেদাবাদকী নরেন্দ্র মোদী স্তেদিয়মদা সাউথ আফ্রিকা থেংনখি।
--------------------------------------------------

Translating MNI:  21%|████▊                  | 211/1000 [02:01<06:08,  2.14it/s]

[211/1000]
EN: Ishan Kishan smashed 61 off 24 balls against Namibia in New Delhi.
MNI: নই দিল্লীদা নমিবিয়া মায়োক্নবদা ইশান কিশন্না বোল ২৪গী মনুংদা ৬১ থুগাইখি।
--------------------------------------------------

Translating MNI:  21%|████▉                  | 212/1000 [02:02<06:12,  2.11it/s]

[212/1000]
EN: Hardik Pandya featured prominently as India posted 209 for nine against Namibia.
MNI: ভারতনা নামিবিয়াগী মায়োক্তা শান্নখিবা অদুদা হার্দিক পান্দ্যানা ২০৯ ফাউবা শান্নখি।
--------------------------------------------------

Translating MNI:  21%|████▉                  | 213/1000 [02:02<06:18,  2.08it/s]

[213/1000]
EN: Varun Chakaravarthy took three wickets as India beat Namibia by 93 runs.
MNI: ভারতনা নামিবিয়াবু রন ৯৩ রন্না মায়থীবা পীদুনা বরুণ চাকরবর্থিনা ৱিকেট অহুম লৌখি।
--------------------------------------------------

Translating MNI:  21%|████▉                  | 214/1000 [02:03<05:55,  2.21it/s]

[214/1000]
EN: India bundled out Namibia for 116 while defending a target of 210.
MNI: ভারতনা নামিবিয়াবু ১১৬দা পুথোকখি অমসুং ২১০গী টার্গেৎ অমা ঙাকথোকখি।
--------------------------------------------------

Translating MNI:  22%|████▉                  | 215/1000 [02:03<06:12,  2.11it/s]

[215/1000]
EN: Namibia captain Gerhard Erasmus won the toss and chose to bat first.
MNI: নমিবিয়াগী কেপ্তেন জেরহার্দ ইরাস্মাসনা টোসতা মায় পাকখি অমসুং অহানবদা বেৎ তৌখি।
--------------------------------------------------

Translating MNI:  22%|████▉                  | 216/1000 [02:04<06:31,  2.01it/s]

[216/1000]
EN: India versus Namibia started at 7:00 PM IST at Arun Jaitley Stadium.
MNI: ভারত বনাম নামিবিয়ানা অরুন জেতলী স্তেদিয়মদা নুমিদাংৱাইরম পুং ৭ তাবা মতমদা শান্নবা হৌরগনি।
--------------------------------------------------

Translating MNI:  22%|████▉                  | 217/1000 [02:04<06:03,  2.15it/s]

[217/1000]
EN: India’s first match was a win against the USA in Mumbai.
MNI: মুম্বাইদা পাংথোকখিবা ভারতকী অহানবা মেটচ অদুদা য়ু এস এ মায়োক্নখি।
--------------------------------------------------

Translating MNI:  22%|█████                  | 218/1000 [02:05<05:35,  2.33it/s]

[218/1000]
EN: India versus Namibia was labelled as game 18 of the tournament.
MNI: ভারত বনাম নামিবিয়া অসি টুর্নামেন্ত অসিগী মেজ ১৮নি হায়না লেবেল তৌখি।
--------------------------------------------------

Translating MNI:  22%|█████                  | 219/1000 [02:05<06:00,  2.17it/s]

[219/1000]
EN: Suryakumar Yadav led India against Namibia in the ongoing T20 World Cup.
MNI: হৌজিক চত্থরিবা টি২০ ৱার্ল্দ কপতা ভারতনা নামিবিয়া মায়োক্নবদা সুর্যকুমার যাদবনা লুচিংখি।
--------------------------------------------------

Translating MNI:  22%|█████                  | 220/1000 [02:06<05:54,  2.20it/s]

[220/1000]
EN: India entered the Namibia match after beating the USA in their opener.
MNI: ভারতনা মখোয়গী ওপনরদা য়ু এস এবু মায়থীবা পীদুনা নামিবিয়া মেটচতা শরুক য়াখি।
--------------------------------------------------

Translating MNI:  22%|█████                  | 221/1000 [02:06<05:46,  2.25it/s]

[221/1000]
EN: The Pakistan government allowed the Pakistan team to play India on February 15.
MNI: ফেব্রুৱারী ১৫দা ভারতকা শান্ননবা পাকিস্থান সরকারনা পাকিস্থানগী তীমগী অয়াবা পীখি।
--------------------------------------------------

Translating MNI:  22%|█████                  | 222/1000 [02:06<05:59,  2.17it/s]

[222/1000]
EN: India versus Pakistan was scheduled for Colombo after weeks of uncertainty.
MNI: চয়োল কয়াগী অচেৎপা ৱারোলগী মতুংদা কোলোম্বোদা ভারত বনস পাকিস্থান শান্নগনি হায়না থৌরাং তৌরি।
--------------------------------------------------

Translating MNI:  22%|█████▏                 | 223/1000 [02:07<06:16,  2.06it/s]

[223/1000]
EN: India versus Pakistan was described as a group-stage match in Colombo.
MNI: কোলোম্বোদা পাংথোক্কদৌরিবা গ্রুপ-ষ্টেজ মেটচ অমগুম্না ভারতনা পাকিস্থান মায়োক্নখি হায়না ফোংদোকখি।
--------------------------------------------------

Translating MNI:  22%|█████▏                 | 224/1000 [02:07<05:59,  2.16it/s]

[224/1000]
EN: The tournament was listed as featuring 55 matches across India and Sri Lanka.
MNI: টুর্নামেন্ত অসিদা ভারত অমসুং শ্রীলঙ্কাগী মফম কয়াদা মেচ ৫৫ য়াওরি হায়না খংদোকখি।
--------------------------------------------------

Translating MNI:  22%|█████▏                 | 225/1000 [02:08<06:19,  2.04it/s]

[225/1000]
EN: The schedule included Delhi, Kolkata, Ahmedabad, Chennai, Mumbai, Colombo, and Kandy venues.
MNI: সেদ্যুল অসিদা দিল্লী, কোলকতা, অহমেদাবাদ, চেন্নাই, মুম্বাই, কোলোম্বো অমসুং কান্দিগী মফমশিং য়াওরি।
--------------------------------------------------

Translating MNI:  23%|█████▏                 | 226/1000 [02:08<06:31,  1.98it/s]

[226/1000]
EN: Afghanistan faced New Zealand at M. A. Chidambaram Stadium with an 11:00 AM start.
MNI: অফগানিস্থাননা এম.এ. চিদাম্বরম স্তেদিয়মদা ন্যু জিলেন্দকা পুং ১১.০০দা শান্নখি।
--------------------------------------------------

Translating MNI:  23%|█████▏                 | 227/1000 [02:09<06:38,  1.94it/s]

[227/1000]
EN: New Zealand played UAE on February 10 at M. A. Chidambaram Stadium.
MNI: ন্যু জিলেন্দনা ফেব্রুৱারী ১০দা এম. এ. চিদাম্বরম স্তেদিয়মদা য়ু.এ.ই.
--------------------------------------------------

Translating MNI:  23%|█████▏                 | 228/1000 [02:10<06:31,  1.97it/s]

[228/1000]
EN: Group D included UAE, New Zealand, South Africa, Afghanistan, and Canada in one pool.
MNI: গ্রুপ Dগী মনুংদা য়ুএই, ন্যু জিলেন্দ, সাউথ আফ্রিকা, অফগানিস্থান অমসুং কানাদা য়াওরি।
--------------------------------------------------

Translating MNI:  23%|█████▎                 | 229/1000 [02:10<06:12,  2.07it/s]

[229/1000]
EN: India’s group-stage route moved from Mumbai to Delhi and then Colombo.
MNI: ভারতকী গ্রুপ-স্তেজ রুত অসি মুম্বাইদগী দিল্লী অমসুং মদুগী মতুংদা কোলোম্বোদা চৎখি।
--------------------------------------------------

Translating MNI:  23%|█████▎                 | 230/1000 [02:10<06:30,  1.97it/s]

[230/1000]
EN: The India versus Namibia match preview named Gerhard Erasmus as Namibia’s captain.
MNI: ইন্দিয়া বনাম নামিবিয়া মেৎচ প্রিভিউনা জেরহার্দ ইরাসমাসপু নামিবিয়াগী কেপ্তেন ওইনা খনবা ঙমখি।
--------------------------------------------------

Translating MNI:  23%|█████▎                 | 231/1000 [02:11<06:28,  1.98it/s]

[231/1000]
EN: A report said Abhishek Sharma underwent checks for a stomach bug in New Delhi.
MNI: রিপোর্ত অমনা হায়খি মদুদি নই দিল্লীদা অভিশেক শর্মাদা স্তোমেচ বগ অমা লৈব্রা হায়বদু চেক তৌখি।
--------------------------------------------------

Translating MNI:  23%|█████▎                 | 232/1000 [02:12<07:05,  1.80it/s]

[232/1000]
EN: The same report said Abhishek Sharma missed India’s Namibia game despite hospital discharge.
MNI: চপ মান্নবা রিপোর্ত অদুদা হায়খি মদুদি হোস্পিতালদা দিসচার্জ তৌরবসু অভিশেক শর্মানা ভারতকী নামিবিয়াগী মেচ মাংখি।
--------------------------------------------------

Translating MNI:  23%|█████▎                 | 233/1000 [02:12<07:04,  1.81it/s]

[233/1000]
EN: Sanju Samson’s World Cup debut was described as lasting only eight deliveries.
MNI: সঞ্জু স্যামসনগী ৱার্ল্দ কপ দেবিউ অসি দেলিভরি নিপালখক্তমক শাংনা পাংথোকখিবনি হায়না ফোংদোকখি।
--------------------------------------------------

Translating MNI:  23%|█████▍                 | 234/1000 [02:13<06:19,  2.02it/s]

[234/1000]
EN: The tournament’s Group A opened across venues in India and Sri Lanka.
MNI: টুর্নামেন্ত অসিগী গ্রুপ A অসি ভারত অমসুং শ্রীলঙ্কাগী মফম কয়াদা হাংদোকখি।
--------------------------------------------------

Translating MNI:  24%|█████▍                 | 235/1000 [02:13<06:14,  2.04it/s]

[235/1000]
EN: India’s match against Namibia was played on Thursday, February 12.
MNI: নেমিবিয়ানা মায়োক্নরিবা ভারতকী মেটচ অদু ফেব্রুৱারী ১২, বৃহস্পতিবারদা শান্নখি।
--------------------------------------------------

Translating MNI:  24%|█████▍                 | 236/1000 [02:14<06:25,  1.98it/s]

[236/1000]
EN: Nepal versus Italy appeared as a live-score fixture during the T20 World Cup schedule.
MNI: টি২০ ৱার্ল্দ কপ সেদ্যুলগী মতমদা নেপাল বনস ইতলী অসি লাইভ-স্কোর ফিক্সতর অমা ওইনা উবা ফংখি।
--------------------------------------------------

Translating MNI:  24%|█████▍                 | 237/1000 [02:14<06:33,  1.94it/s]

[237/1000]
EN: Australia versus Zimbabwe appeared as a live-score fixture on the Indian Express cricket feed.
MNI: ইন্দিয়ান এক্সপ্রেস ক্রিকেৎ ফিদতা অষ্ট্রেলিয়া বনাম জিম্বাবুৱাই অসি লাইভ-স্কোর ফিক্সচর অমা ওইনা উবা ফংখি।
--------------------------------------------------

Translating MNI:  24%|█████▍                 | 238/1000 [02:15<06:36,  1.92it/s]

[238/1000]
EN: The Indian Express sports section highlighted India’s 93-run win over Namibia.
MNI: ইন্দিয়ান এক্সপ্রেস স্পোর্তস সেক্সননা নামিবিয়াগী মায়োক্তা ভারতকী রন ৯৩ মায় পাকখিবগী মতাংদা পনখি।
--------------------------------------------------

Translating MNI:  24%|█████▍                 | 239/1000 [02:15<06:40,  1.90it/s]

[239/1000]
EN: The match report said India’s bowling attack dismantled Namibia during the chase.
MNI: মেটচ রিপোর্ত অদুদা হায়খি মদুদি ভারতনা বোলিং এটেক তৌবনা নেমিবিয়াবু হুরানখিবা মতমদা মাংহনখি।
--------------------------------------------------

Translating MNI:  24%|█████▌                 | 240/1000 [02:16<06:46,  1.87it/s]

[240/1000]
EN: The India versus Namibia highlights credited Ishan Kishan’s 61 with driving India’s total.
MNI: ইন্দিয়া বনাম নামিবিয়ানা ইশান কিশানগী ক্রেদিতেদ ৬১ দা ভারতকী অপুনবা দ্রাইভ তৌখি।
--------------------------------------------------

Translating MNI:  24%|█████▌                 | 241/1000 [02:16<06:29,  1.95it/s]

[241/1000]
EN: ISL 2025–26 fixtures began on February 14 with a double-header format.
MNI: আইএসএল ২০২৫২৬গী ফিক্সচরশিং ফেব্রুৱারী ১৪দা দবল হেদর ফোর্মেত্তা হৌখি।
--------------------------------------------------

Translating MNI:  24%|█████▌                 | 242/1000 [02:17<06:40,  1.89it/s]

[242/1000]
EN: Mohun Bagan Super Giant faced Kerala Blasters in the season opener in Kolkata.
MNI: কোলকতাদা পাংথোকপা সিজন ওপনরদা মোহন বাগন সুপর জাইন্তনা কেরলা ব্লাস্তর্সকা মায়োক্নখি।
--------------------------------------------------

Translating MNI:  24%|█████▌                 | 243/1000 [02:17<06:28,  1.95it/s]

[243/1000]
EN: FC Goa hosted Inter Kashi at Fatorda Stadium on February 14.
MNI: ফেব্রুৱারী ১৪দা ফেতোর্দা স্তেদিয়মদা এফসি গোৱানা ইন্টর কাশীবু হোস্ত তৌখি।
--------------------------------------------------

Translating MNI:  24%|█████▌                 | 244/1000 [02:18<06:33,  1.92it/s]

[244/1000]
EN: The first match on double-header days started at 5:00 PM IST.
MNI: দবল-হেদরগী নুমিৎশিংদা অহানবা মেটচ অসি ইস্তেৎকী নুমিদাংৱাইরম পুং ৫ তাবা মতমদা হৌখি।
--------------------------------------------------

Translating MNI:  24%|█████▋                 | 245/1000 [02:18<06:51,  1.84it/s]

[245/1000]
EN: The second match on double-header days started at 7:30 PM IST.
MNI: দবল-হেদরগী নুমিৎশিংদা অনিশুবা মেটচ অসি ইস্তিতীগী নুমিদাংৱাইরম পুং ৭.৩০ তাবা মতমদা হৌখি।
--------------------------------------------------

Translating MNI:  25%|█████▋                 | 246/1000 [02:19<06:40,  1.88it/s]

[246/1000]
EN: A report said the ISL season would use a single-leg home-and-away format.
MNI: রিপোর্ত অমনা হায়খি মদুদি আইএসএল সিজন অসিদা সিঙ্গল-লেগ হোম-এন্দ-ৱায় ফোর্মেৎ অমা শিজিন্নগনি।
--------------------------------------------------

Translating MNI:  25%|█████▋                 | 247/1000 [02:19<06:53,  1.82it/s]

[247/1000]
EN: The Indian Express football page reported FanCode won exclusive ISL media rights.
MNI: ইন্দিয়ান এক্সপ্রেস ফুটবোল পেজনা ফেনকোদনা এক্স্ক্লুসিভ আইএসএল মিদিয়া রাইট লৌখি হায়না রিপোর্ট তৌখি।
--------------------------------------------------

Translating MNI:  25%|█████▋                 | 248/1000 [02:20<06:30,  1.93it/s]

[248/1000]
EN: The same report said ISL per-match valuation dropped by about 95 percent.
MNI: চপ মান্নবা রিপোর্ত অদুদা হায়খি মদুদি আইএসএলগী ভেল্যুয়েসন অসি চাদা ৯৫ হন্থখি।
--------------------------------------------------

Translating MNI:  25%|█████▋                 | 249/1000 [02:20<06:20,  1.97it/s]

[249/1000]
EN: The ISL report described a truncated season with pay cuts at multiple clubs.
MNI: আই.এস.এল.গী রিপোর্তনা ক্লব কয়ামরুমদা শেল মাংহনখিবা মতম অমা শন্দোক্না তাক্লি।
--------------------------------------------------

Translating MNI:  25%|█████▊                 | 250/1000 [02:21<06:35,  1.90it/s]

[250/1000]
EN: Real Madrid CF hoped a La Liga surge was boosted by a team dinner.
MNI: রিয়েল মাদ্রিদ সি.এফ.না লা লিগা হেনগৎলকপদা টিম দিনর অমনা পুক্নিং থৌগৎলগনি হায়না থাজবা থমখি।
--------------------------------------------------

Translating MNI:  25%|█████▊                 | 251/1000 [02:22<06:47,  1.84it/s]

[251/1000]
EN: The Real Madrid dinner was reportedly paid for by Vinícius Júnior and Kylian Mbappé.
MNI: রিয়েল মাদ্রিদ দিনর অদু ভিনিসিয়স জুনিয়র অমসুং কিলিয়ান এমবাপ্পেনা শেল পীখিবনি হায়না রিপোর্ট তৌরি।
--------------------------------------------------

Translating MNI:  25%|█████▊                 | 252/1000 [02:22<06:25,  1.94it/s]

[252/1000]
EN: Barcelona aimed for a fourth straight league win against Girona in La Liga.
MNI: Barcelona aimed for a fourth straight league win over Girona in La Liga.
--------------------------------------------------

Translating MNI:  25%|█████▊                 | 253/1000 [02:23<06:33,  1.90it/s]

[253/1000]
EN: Barcelona visited Atlético Madrid for a Copa del Rey first-leg clash.
MNI: কোপা দেল রে ফার্ষ্ট-লেগ ক্লেশ অমা পাংথোক্নবা বার্সেলোনা এত্তলেতিকো মাদ্রিদতা লাকখি।
--------------------------------------------------

Translating MNI:  25%|█████▊                 | 254/1000 [02:23<06:26,  1.93it/s]

[254/1000]
EN: Barcelona entered the Atlético Madrid match after winning 17 of 18 matches.
MNI: বার্সেলোনানা মেটচ ১৮গী মনুংদা ১৭ মায় পাক্লবা মতুংদা এটলেতিকো মাদ্রিদ মেটচতা শরুক য়াখি।
--------------------------------------------------

Translating MNI:  26%|█████▊                 | 255/1000 [02:24<06:22,  1.95it/s]

[255/1000]
EN: Real Madrid and UEFA announced an agreement ending the Super League project.
MNI: রিয়েল মাদ্রিদ অমসুং য়ু ই এনা সুপর লীগ প্রোজেক্ত লোইশিনবা য়ানা চেরোল অমা লাওথোকখি।
--------------------------------------------------

Translating MNI:  26%|█████▉                 | 256/1000 [02:24<06:10,  2.01it/s]

[256/1000]
EN: Barcelona formally pulled out of the Super League days before the agreement.
MNI: এগ্রিমেন্ত অদুগী নুমিৎ খরনিগী মমাংদা বার্সেলোনাসু সুপর লিগদগী ফোর্মেল ওইনা তোকখি।
--------------------------------------------------

Translating MNI:  26%|█████▉                 | 257/1000 [02:25<06:47,  1.82it/s]

[257/1000]
EN: Tottenham Hotspur reportedly sacked Thomas Frank after a 2–1 loss to Newcastle United.
MNI: ন্যুকাসল য়ুনাইতেদতা ২-১না মাংখিবা মতুংদা টোটেনহাম হোটস্পুরনা থোমাস ফ্রাঙ্কপু থাদোকখি হায়না রিপোর্ট তৌরি।
--------------------------------------------------

Translating MNI:  26%|█████▉                 | 258/1000 [02:25<06:27,  1.91it/s]

[258/1000]
EN: The Tottenham report said the club still had no league win in 2026.
MNI: টোত্তেনহামগী রিপোর্তনা হায়খি মদুদি ক্লব অসিনা ইং ২০২৬তা লিগ অমত্তা মায় পাকখিদে।
--------------------------------------------------

Translating MNI:  26%|█████▉                 | 259/1000 [02:26<06:42,  1.84it/s]

[259/1000]
EN: Wayne Rooney said Arsenal looked mentally stronger in the Premier League title race.
MNI: ৱেন রুনিনা হায়খি মদুদি প্রিমিয়র লীগকী মকোক থোংবা রেসতা আর্সেনেল অসি হেন্না ময়েক শেংবা মওংদা উরি।
--------------------------------------------------

Translating MNI:  26%|█████▉                 | 260/1000 [02:26<06:46,  1.82it/s]

[260/1000]
EN: Rooney noted Arsenal last won the Premier League title in the 2003–04 season.
MNI: রুনিনা ফোংদোকখি মদুদি অরসনেলনা অরোইবা ওইনা প্রিমিয়র লিগকী মনা অসি ইং ২০০৩০৪গী সিজনদা ফংখি।
--------------------------------------------------

Translating MNI:  26%|██████                 | 261/1000 [02:27<07:00,  1.76it/s]

[261/1000]
EN: Rooney said Arsenal led Manchester City by six points with 13 games remaining.
MNI: রুনিনা হায়খি মদুদি আর্সেনেলনা মেচ ১৩ শান্নরগা মেনচেস্তর সিতীবু পোইন্ট তরুক্না লুচিংখি।
--------------------------------------------------

Translating MNI:  26%|██████                 | 262/1000 [02:28<06:58,  1.76it/s]

[262/1000]
EN: Cristiano Ronaldo missed a second straight Saudi Pro League match for Al-Nassr.
MNI: ক্রিস্তিয়ানো রোনালদোনা অল-নসরগীদমক সাউদী প্রো লিগগী অনিশুবা মথং মথং মেটচ অমা মাংখি।
--------------------------------------------------

Translating MNI:  26%|██████                 | 263/1000 [02:28<06:54,  1.78it/s]

[263/1000]
EN: Al-Nassr beat Al-Ittihad 2–0 despite Cristiano Ronaldo’s continued absence.
MNI: ক্রিস্তিয়ানো রোনাল্দোনা লেপ্তনা লৈত্রবসু অল-নসরনা অল-ইতিহাদবু ২-০না মায়থীবা পীখি।
--------------------------------------------------

Translating MNI:  26%|██████                 | 264/1000 [02:29<06:48,  1.80it/s]

[264/1000]
EN: Sadio Mané and Angelo Gabriel scored for Al-Nassr in the win over Al-Ittihad.
MNI: অল-ইতিহাদ মায়োক্নবদা সাদিও মেনে অমসুং এঞ্জেলো গ্যাব্রিয়েলনা অল-নসরগীদমক গোল তৌখি।
--------------------------------------------------

Translating MNI:  26%|██████                 | 265/1000 [02:29<06:52,  1.78it/s]

[265/1000]
EN: Sumit Nagal headlined the Delhi Open 2026 at the DLTA Complex.
MNI: দি এল তি এ কমপ্লেক্সতা পাংথোক্কদৌরিবা দিল্লি ওপন ২০২৬গী হেদলাইন্দা সুমিত নাগলনা শকখঙখি।
--------------------------------------------------

Translating MNI:  27%|██████                 | 266/1000 [02:30<06:21,  1.92it/s]

[266/1000]
EN: The Delhi Open 2026 tournament was scheduled for February 16 to 22.
MNI: দিল্লি ওপন ২০২৬ টুর্নামেন্ত অসি ফেব্রুৱারী ১৬দগী ২২ ফাওবা পাংথোক্কনি।
--------------------------------------------------

Translating MNI:  27%|██████▏                | 267/1000 [02:30<06:30,  1.88it/s]

[267/1000]
EN: Britain’s Jay Clarke was named as a leading overseas entrant for Delhi Open 2026.
MNI: দিল্লি ওপন ২০২৬গী মকোক থোংবা ওভরসিজ এন্তরন্ত অমা ওইনা ব্রিতেন্সকী জে ক্লার্কপু মমিং থারকখি।
--------------------------------------------------

Translating MNI:  27%|██████▏                | 268/1000 [02:31<06:14,  1.96it/s]

[268/1000]
EN: The Delhi Open note said Sumit Nagal gained direct entry into the main draw.
MNI: দিল্লী ওপন নোটতা হায়খি মদুদি সুমিৎ নাগালনা মেইন দ্রোদা হকথেংননা শরুক য়াখি।
--------------------------------------------------

Translating MNI:  27%|██████▏                | 269/1000 [02:31<06:08,  1.99it/s]

[269/1000]
EN: India beat the Netherlands 3–2 in Davis Cup competition to move closer.
MNI: দেবিস কপ কম্পিতিসনদা ভারতনা নেদরলেন্দ ৩-২না মায়থীবা পীদুনা হেন্না নকশিল্লকখি।
--------------------------------------------------

Translating MNI:  27%|██████▏                | 270/1000 [02:32<06:27,  1.88it/s]

[270/1000]
EN: Dhakshineswar Suresh featured prominently during India’s Davis Cup tie against the Netherlands.
MNI: নেদর্লেন্দগী মায়োক্নবদা ভারতকী দেবিস কপ থেংনখিবা মতমদা ধাক্সিনেশ্বর সুরেশনা মশক থোক্না শরুক য়াখি।
--------------------------------------------------

Translating MNI:  27%|██████▏                | 271/1000 [02:32<06:37,  1.83it/s]

[271/1000]
EN: India’s doubles pair beat David Pel and Sander Arends in a tight five-setter.
MNI: ভারতকী দবলস পেরনা দেবিদ পেল অমসুং সান্দর আরেন্দসপু শাথীবা ফাইভ সেত্তর অমদা মায়থীবা পীখি।
--------------------------------------------------

Translating MNI:  27%|██████▎                | 272/1000 [02:33<06:30,  1.87it/s]

[272/1000]
EN: The doubles win was described as India’s first in five playoff ties versus Europeans.
MNI: দবলস ৱিন অসি ভারতনা য়ুরোপিয়ানশিংগী মায়োক্নবগী প্লেঅফ তাই মঙাদা অহানবা ওইরে হায়না ফোংদোকখি।
--------------------------------------------------

Translating MNI:  27%|██████▎                | 273/1000 [02:33<06:13,  1.95it/s]

[273/1000]
EN: The same report said Sumit Nagal failed to seal the tie in reverse singles.
MNI: রিপোর্ত অদুদা হায়খি মদুদি সুমিত নাগলনা রিভর্স সিঙ্গলসতা শান্নবা ঙমখিদ্রে।
--------------------------------------------------

Translating MNI:  27%|██████▎                | 274/1000 [02:34<06:12,  1.95it/s]

[274/1000]
EN: Novak Djokovic said he still wanted to represent Serbia in Davis Cup.
MNI: নোবাক জোকোভিকনা হায়খি মদুদি মহাক্না হৌজিকসু দেভিস কপতা সর্বিয়াগী মীহুৎ ওইনবা পাম্মি।
--------------------------------------------------

Translating MNI:  28%|██████▎                | 275/1000 [02:34<06:28,  1.87it/s]

[275/1000]
EN: Serbia captain Viktor Troicki described Novak Djokovic as a major team figure.
MNI: সর্বিয়াগী কেপ্টেন ভিক্তর ত্রোইক্কিনা নোভাক জোকোভিকপু মরুওইবা তীম ফিগর অমা ওইনা ফোংদোকখি।
--------------------------------------------------

Translating MNI:  28%|██████▎                | 276/1000 [02:35<06:44,  1.79it/s]

[276/1000]
EN: Novak Djokovic withdrew from a 2025 Davis Cup qualifier due to a hamstring injury.
MNI: হেমষ্ট্রিং অশোক-অপন অমা লৈবনা মরম ওইদুনা নোভাক জোকোভিচনা ২০২৫ দাভিস কপ ক্বালিফায়রদগী লৌথোকখি।
--------------------------------------------------

Translating MNI:  28%|██████▎                | 277/1000 [02:36<07:15,  1.66it/s]

[277/1000]
EN: Carlos Alcaraz beat Alexander Zverev in a five-hour, 27-minute Australian Open semifinal.
MNI: কার্লোস অলকারাজনা পুং মঙা অমসুং মিনট ২৭ চংনা ওস্ত্রেলিয়ান ওপন সেমিফাইনেলদা আলেকজান্দর জভেরভপু মায়থীবা পীখি।
--------------------------------------------------

Translating MNI:  28%|██████▍                | 278/1000 [02:36<06:58,  1.73it/s]

[278/1000]
EN: Carlos Alcaraz won the Australian Open final after facing Novak Djokovic.
MNI: কার্লোস অলকারাজনা ওস্ত্রেলিয়ান ওপনগী ফাইনেলদা নোভাক জোকোভিককা মায়োক্নরবা মতুংদা মায় পাকখি।
--------------------------------------------------

Translating MNI:  28%|██████▍                | 279/1000 [02:37<06:40,  1.80it/s]

[279/1000]
EN: Jannik Sinner was described as holding five straight wins over Novak Djokovic.
MNI: জানিক সিনরনা নোভাক জোকোবিকপু মথং মথং মাইপাকপা মঙা লৌখিবনি হায়না ফোংদোকখি।
--------------------------------------------------

Translating MNI:  28%|██████▍                | 280/1000 [02:37<07:07,  1.69it/s]

[280/1000]
EN: The Djokovic–Sinner preview said Djokovic reached semifinals aided by a walkover and retirement.
MNI: জোকোভিক্সিনর প্রিভিউনা হায়খি মদুদি জোকোভিকনা ৱাকওভর অমসুং রিটায়ারমেন্তনা মতেং পাংদুনা সেমিফাইনেল য়ৌখি।
--------------------------------------------------

Translating MNI:  28%|██████▍                | 281/1000 [02:38<06:54,  1.73it/s]

[281/1000]
EN: An Australian Open report said extreme heat forced temporary suspensions on outside courts.
MNI: ওস্ত্রেলিয়ান ওপনগী রিপোর্ত অমনা হায়খি মদুদি অকনবা হিটনা মপানগী কোর্টশিংদা মতম খরগী ওইনা সস্পেন্সন তৌখি।
--------------------------------------------------

Translating MNI:  28%|██████▍                | 282/1000 [02:38<06:54,  1.73it/s]

[282/1000]
EN: The same report said organisers issued heat warnings for players and spectators.
MNI: চপ মান্নবা রিপোর্ত অদুদা হায়খি মদুদি ওর্গানাইজরশিংনা শান্নরোইশিং অমসুং য়েংবশিংগীদমক হিৎ ৱার্নিং ইসু তৌখি।
--------------------------------------------------

Translating MNI:  28%|██████▌                | 283/1000 [02:39<07:06,  1.68it/s]

[283/1000]
EN: Jannik Sinner beat Eliot Spizzirri 4–6, 6–3, 6–4, 6–4 in Melbourne.
MNI: মেলবোর্নদা জানিক সিনরনা ইলিয়োৎ স্পিজিরিবু ৪৬, ৬৩, ৬৪, ৬৪না মায়থীবা পীখি।
--------------------------------------------------

Translating MNI:  28%|██████▌                | 284/1000 [02:40<06:48,  1.75it/s]

[284/1000]
EN: A tennis feature said Fangran Tian was coached by Chennai’s Mangal Sriram since age 12.
MNI: টেনিস ফিচর অমনা হায়খি মদুদি ফঙ্গরান তিয়ান অসি চেন্নাইগী মঙ্গল সিরামনা চহি ১২দগী কোচ ওইরকখি।
--------------------------------------------------

Translating MNI:  28%|██████▌                | 285/1000 [02:40<06:49,  1.75it/s]

[285/1000]
EN: Badminton World Federation demoted Syed Modi International from Super 300 to Super 100.
MNI: বেদমিন্তন ৱার্ল্দ ফেদরেসননা সাইদ মোদী ইন্তর্নেস্নেলবু সুপর ৩০০ দগী সুপর ১০০দা হন্থহল্লে।
--------------------------------------------------

Translating MNI:  29%|██████▌                | 286/1000 [02:41<06:49,  1.74it/s]

[286/1000]
EN: The same report said India Open retained Super 750 status for the 2027–2030 cycle.
MNI: রিপোর্ত অদুদা হায়খি মদুদি ২০২৭২০৩০গী সাইকলগী ওইনা ইন্দিয়া ওপননা সুপর ৭৫০গী থাক অদু লেপখি।
--------------------------------------------------

Translating MNI:  29%|██████▌                | 287/1000 [02:41<06:56,  1.71it/s]

[287/1000]
EN: A badminton reforms report said World Championships and five Super 1000s will run 11 days.
MNI: বেদমিন্তোন রিফোর্মস রিপোর্ত অমনা হায়খি মদুদি ৱার্ল্দ চেম্পিয়নশিপ অমসুং সুপর ১০০০ মঙাদি নুমিৎ ১১ চৎকনি।
--------------------------------------------------

Translating MNI:  29%|██████▌                | 288/1000 [02:42<06:54,  1.72it/s]

[288/1000]
EN: The Indian Express said BWF’s AGM 2026 would vote on a 3×15 scoring format.
MNI: ইন্দিয়ান এক্সপ্রেসনা হায়খি মদুদি বি দবল্যু এফগী এ জি এম ২০২৬না ৩×১৫ স্কোর তৌবগী ফোর্মেত্তা ভোট পীগনি।
--------------------------------------------------

Translating MNI:  29%|██████▋                | 289/1000 [02:43<06:44,  1.76it/s]

[289/1000]
EN: A Badminton Asia Team report said India lost 3–2 to Japan in men’s ties.
MNI: বেদমিন্তোন এসিয়া তীম রিপোর্ত অমনা হায়খি মদুদি ভারতনা নুপাগী টাইদা জাপানদগী ৩২দা মাংখি।
--------------------------------------------------

Translating MNI:  29%|██████▋                | 290/1000 [02:43<06:31,  1.81it/s]

[290/1000]
EN: The same report said India lost to Thailand in women’s ties at the team event.
MNI: চপ মান্নবা রিপোর্ত অদুদা হায়খি মদুদি ভারতনা তীম ইভেন্ত অদুদা থাইলেন্দতগী নুপীগী টাইদা মাংখি।
--------------------------------------------------

Translating MNI:  29%|██████▋                | 291/1000 [02:44<06:44,  1.75it/s]

[291/1000]
EN: A selection report said Tanvi Sharma would play first singles after Unnati Hooda was out.
MNI: সেলেক্সন রিপোর্ত অমগী মতুংইন্না তনবী শর্মানা উননি হুদানা মপান থোক্লবা মতুংদা অহানবা সিঙ্গলস শান্নগনি হায়খি।
--------------------------------------------------

Translating MNI:  29%|██████▋                | 292/1000 [02:44<07:07,  1.66it/s]

[292/1000]
EN: An India Open report said “nest materials” halted a women’s doubles semifinal in Delhi.
MNI: ইন্দিয়া ওপন রিপোর্ত অমনা হায়খি মদুদি দিল্লীদা পাংথোকপা ৱুমেনস দবলস সেমিফাইনেল অমা নেস্ত মেটরিএলসনা থীংখি।
--------------------------------------------------

Translating MNI:  29%|██████▋                | 293/1000 [02:45<06:36,  1.78it/s]

[293/1000]
EN: A feature said An Se-young won 94.8 percent of her matches in 2025.
MNI: ২০২৫দা অন সে-য়ুংনা মহাক্কী মেচশিংগী চাদা ৯৪.৮ মায় পাকখি হায়না ফিচর অমনা হায়খি।
--------------------------------------------------

Translating MNI:  29%|██████▊                | 294/1000 [02:45<06:27,  1.82it/s]

[294/1000]
EN: The same feature said An Se-young began 2026 with two titles in two weeks.
MNI: চপ মান্নবা ফিচর অসিনা হায়খি মদুদি অন সে-য়ুংনা ২০২৬দা চয়োল অনিগী মনুংদা তাইতল অনি হৌখি।
--------------------------------------------------

Translating MNI:  30%|██████▊                | 295/1000 [02:46<06:38,  1.77it/s]

[295/1000]
EN: Lin Chun-yi beat Jonatan Christie 21–10, 21–18 in the India Open final.
MNI: ইন্দিয়া ওপন ফাইনেলদা লিন চুন-ইনা জোনাতান ক্রিষ্টি ২১-১০, ২১-১৮ মায়থীবা পীখি।
--------------------------------------------------

Translating MNI:  30%|██████▊                | 296/1000 [02:47<06:51,  1.71it/s]

[296/1000]
EN: Devika Sihag beat Navya Kanderi 21–10, 21–13 to win in Baku.
MNI: দেবিকা সিহাগনা বাকুদা নব্য কন্দেরীবু ২১-১০, ২১-১৩ দা মায়থীবা পীদুনা মায় পাকখি।
--------------------------------------------------

Translating MNI:  30%|██████▊                | 297/1000 [02:47<06:33,  1.79it/s]

[297/1000]
EN: Radhika Sharma won her first mixed doubles title partnering Sathwik Reddy.
MNI: রাধিকা শর্মানা মহাক্কী অহানবা মিক্স দবলস তাইটল পার্তনর ওইরিবা সত্যিক রেদ্দীনা মায় পাকখি।
--------------------------------------------------

Translating MNI:  30%|██████▊                | 298/1000 [02:48<06:57,  1.68it/s]

[298/1000]
EN: Ankur Bhattacharjee upset world-ranked opponent Bourrassaud 3–1 at WTT Chennai.
MNI: ৱি তি তি চেন্নাইদা অনকুর ভট্টাচারজীনা ৱার্ল্দ-রেঙ্ক ওইরিবা ওপোনেন্ত বোরাসৌদ ৩১না অৱাবা পোকখি।
--------------------------------------------------

Translating MNI:  30%|██████▉                | 299/1000 [02:48<07:32,  1.55it/s]

[299/1000]
EN: FIFA president Gianni Infantino faced criticism over high-priced tickets for the 2026 World Cup.
MNI: ফিফাগী প্রসিদেন্ত জিয়ানি ইনফান্তিনোনা ২০২৬গী ৱার্ল্দ কপকী অৱাংবা মমল লৈবা টিক্তকী মরমদা ক্রিতিক্সকী মায়োক্তা মায়োক্নখি।
--------------------------------------------------

Translating MNI:  30%|██████▉                | 300/1000 [02:49<07:08,  1.63it/s]

[300/1000]
EN: India lost 1-3 to Belgium in the FIH Pro League opener at Rourkela.
MNI: রুরকেলাদা পাংথোকপা এফআইঐচ প্রো লীগ ওপনরদা ভারতনা বেলজিয়মদা ১-৩ দা মাংখি।
--------------------------------------------------

Translating MNI:  30%|██████▉                | 301/1000 [02:50<06:42,  1.74it/s]

[301/1000]
EN: Craig Fulton said India’s defensive structure did not deliver in the Pro League opener.
MNI: ক্রিগ ফুলতন্না হায়খি মদুদি ভারতকী দিফেন্সিব ষ্ট্রকচরনা প্রো লীগ ওপনরদা ফংখিদে।
--------------------------------------------------

Translating MNI:  30%|██████▉                | 302/1000 [02:50<06:15,  1.86it/s]

[302/1000]
EN: India then suffered a 0-8 loss to Argentina in the next Pro League match.
MNI: মসিগী মতুংদা ভারতনা মথংগী প্রো লীগ মেটচতা আর্জেন্তিনাগী মায়োক্তা ০-৮ দা মাংখি।
--------------------------------------------------

Translating MNI:  30%|██████▉                | 303/1000 [02:50<06:10,  1.88it/s]

[303/1000]
EN: India’s 0-8 defeat was described as a systematic demolition by Argentina.
MNI: ভারতনা ০-৮ দা মাংখিবা অদু আর্জেন্তিনানা সিস্তেমেতিক ওইবা মওংদা মাংহনখিবনি হায়না ফোংদোকখি।
--------------------------------------------------

Translating MNI:  30%|██████▉                | 304/1000 [02:51<06:20,  1.83it/s]

[304/1000]
EN: India’s 0-8 loss matched the joint third-worst defeat in India’s hockey history.
MNI: ভারতনা ০-৮ দা মাংখিবা অসি ভারতকী হোকীগী পুৱারীদা খ্বাইদগী শাথীবা অহুমশুবা অপুনবা মাইপাকপগা মান্নৈ।
--------------------------------------------------

Translating MNI:  30%|███████                | 305/1000 [02:52<06:37,  1.75it/s]

[305/1000]
EN: India’s other 0-8 losses came in 1985 versus Netherlands and 2010 versus Australia.
MNI: ইং ১৯৮৫দা নেদর্লেন্দগী মায়োক্তা অমসুং ইং ২০১০দা ওস্ত্রেলিয়াগী মায়োক্তা ভারতনা ০-৮দা মাংখি।
--------------------------------------------------

Translating MNI:  31%|███████                | 306/1000 [02:52<06:22,  1.82it/s]

[306/1000]
EN: Argentina’s Tomas Domene scored four goals in the 0-8 win over India.
MNI: আর্জেন্তিনাগী টোমাস দোমেননা ভারতকী মায়পাকপদা গোল ০-৮ দা গোল মরি স্কোর তৌখি।
--------------------------------------------------

Translating MNI:  31%|███████                | 307/1000 [02:53<06:27,  1.79it/s]

[307/1000]
EN: Tomas Domene scored at 15th, 20th, 26th and 60th minutes against India.
MNI: টোমাস দোমেননা ভারতকী মায়োক্তা ১৫শুবা, ২০শুবা, ২৬শুবা অমসুং ৬০শুবা মিনিত্তা গোল তৌখি।
--------------------------------------------------

Translating MNI:  31%|███████                | 308/1000 [02:53<06:42,  1.72it/s]

[308/1000]
EN: Tomas Ruiz, Lucio Mendez, Ignacio Ibarra, and Nicolas della Torre also scored for Argentina.
MNI: Tomas Ruiz, Lucio Mendez, Ignacio Ibarra, and Nicolas della Torre also scored for Argentina.
--------------------------------------------------

Translating MNI:  31%|███████                | 309/1000 [02:54<06:34,  1.75it/s]

[309/1000]
EN: India’s third quarter without conceding a goal looked like an anomaly in the match.
MNI: ভারতকী অহুমশুবা ক্বার্তর অদু গোল অমত্তা পীরক্তনা মেটচ অসিদা অওনোমালি অমা ওইনা উরি।
--------------------------------------------------

Translating MNI:  31%|███████▏               | 310/1000 [02:55<06:41,  1.72it/s]

[310/1000]
EN: Player-of-the-Match Tomas Domene said Argentina played the whole game at 100 percent.
MNI: প্লেয়র ওফ দি মেচ টোমাস দোমেননা হায়খি মদুদি আর্জেন্তিনানা মপুংফাবা মেক অদু চাদা ১০০দা শান্নখি।
--------------------------------------------------

Translating MNI:  31%|███████▏               | 311/1000 [02:55<07:08,  1.61it/s]

[311/1000]
EN: Tomas Domene said Argentina were disappointed after losing 3-5 to Belgium previously.
MNI: তোমাস দোমেননা হায়খি মদুদি আর্জেন্তিনা অসি হান্নগী বেলজিয়মদা ৩-৫না মাংখিবা অদুদা পুক্নিং নুংঙাইতবা ফোংদোকখি।
--------------------------------------------------

Translating MNI:  31%|███████▏               | 312/1000 [02:56<06:30,  1.76it/s]

[312/1000]
EN: Argentina scored two quick goals at the end of the first quarter.
MNI: আর্জেন্তিনানা অহানবা ক্বার্তর লোইরবা মতুংদা অথুবা গোল অনি স্কোর তৌখি।
--------------------------------------------------

Translating MNI:  31%|███████▏               | 313/1000 [02:56<06:05,  1.88it/s]

[313/1000]
EN: Argentina scored five goals in 10 minutes during the second quarter.
MNI: আর্জেন্তিনানা অনিশুবা ক্বার্টরদা মিনট ১০তা গোল মঙা স্কোর তৌখি।
--------------------------------------------------

Translating MNI:  31%|███████▏               | 314/1000 [02:57<05:55,  1.93it/s]

[314/1000]
EN: Harmanpreet Singh missed two penalty strokes in the match against Argentina.
MNI: অর্জেন্তিনা মায়োক্নবদা হারমনপ্রীত সিংহনা পেনেলতি ষ্ট্রোক অনি মাংখি।
--------------------------------------------------

Translating MNI:  32%|███████▏               | 315/1000 [02:57<05:54,  1.93it/s]

[315/1000]
EN: India missed three penalty corners during the 0-8 defeat against Argentina.
MNI: আর্জেন্তিনাগী মায়োক্তা শান্নখিবা 0-8গী মায়থীবা অদুদা ভারতনা পেনেলতি কোর্নর অহুম মাংখি।
--------------------------------------------------

Translating MNI:  32%|███████▎               | 316/1000 [02:58<05:40,  2.01it/s]

[316/1000]
EN: India goalkeepers Suraj Karkera and Pawan looked completely out of place.
MNI: ভারতকী গোলকিপর সুরজ কারকেরা অমসুং পবন্না মপুংফানা মফম চাদনা উরম্মী।
--------------------------------------------------

Translating MNI:  32%|███████▎               | 317/1000 [02:58<05:39,  2.01it/s]

[317/1000]
EN: Argentina dominated possession and toyed with India’s midfield and defence.
MNI: আর্জেন্তিনানা পোসেসনদা দোমিনেৎ তৌখি অমসুং ভারতকী মিদফিল্দ অমসুং দিফেন্সকা শান্নখি।
--------------------------------------------------

Translating MNI:  32%|███████▎               | 318/1000 [02:59<05:28,  2.08it/s]

[318/1000]
EN: Argentina’s win catapulted them to fourth in the nine-team standings.
MNI: আর্জেন্তিনাগী মাইপাক্না মখোয়বু টিম তরেৎকী থাক্তা মরিশুবা মফমদা পুরকখি।
--------------------------------------------------

Translating MNI:  32%|███████▎               | 319/1000 [02:59<05:36,  2.02it/s]

[319/1000]
EN: India next faced world No.2 Belgium again after the heavy Argentina loss.
MNI: আর্জেন্তিনাদা কন্না মাংখিবা মতুংদা ভারতনা ৱার্ল্দ নম্বর ২ বেলজিয়মগী মায়োক্তা অমুক হন্না থেংনখি।
--------------------------------------------------

Translating MNI:  32%|███████▎               | 320/1000 [03:00<05:37,  2.01it/s]

[320/1000]
EN: Macklin Celebrini scored early to spark Canada’s 5-0 win over Czech Republic.
MNI: মেকলিন সেলেব্রিনিনা অঙনবা মতমদা স্কোর তৌদুনা চেক রিপব্লিকতা কানাদানা ৫-০না মায় পাকখি।
--------------------------------------------------

Translating MNI:  32%|███████▍               | 321/1000 [03:00<05:43,  1.98it/s]

[321/1000]
EN: Macklin Celebrini scored with just over five seconds left in the first period.
MNI: মেকলিন সেলেব্রিনিনা অহানবা পেরিওদতা সেকেন্দ মঙা হেন্দোক্তুনা গোল তৌখি।
--------------------------------------------------

Translating MNI:  32%|███████▍               | 322/1000 [03:01<05:43,  1.97it/s]

[322/1000]
EN: Mark Stone, Bo Horvat, Nathan MacKinnon and Nick Suzuki scored in Canada’s opener.
MNI: কানাদাগী ওপনরদা মার্ক স্তোন, বো হোর্বেৎ, নাথান মেকিনন অমসুং নিক সুজুকিনা গোল তৌখি।
--------------------------------------------------

Translating MNI:  32%|███████▍               | 323/1000 [03:01<05:47,  1.95it/s]

[323/1000]
EN: Connor McDavid recorded three assists in Canada’s 5-0 Olympic win.
MNI: কোনর মেকদেবিনা কানাদাগী ৫-০না ওলিম্পিকতা মায় পাকখিবা অদুদা এসিস্ত অহুম রেকোর্দ তৌখি।
--------------------------------------------------

Translating MNI:  32%|███████▍               | 324/1000 [03:02<06:00,  1.87it/s]

[324/1000]
EN: Sidney Crosby said Celebrini’s first Olympic goal was huge to get Canada going.
MNI: সিদ্নি ক্রোসবিনা হায়খি মদুদি সেলেব্রিনিগী অহানবা ওলিম্পিককী পান্দম অসি কানাদা চৎপদা অচৌবা অমনি।
--------------------------------------------------

Translating MNI:  32%|███████▍               | 325/1000 [03:02<05:36,  2.00it/s]

[325/1000]
EN: Jon Cooper said Macklin Celebrini plays the game well beyond his years.
MNI: জোন কোপরনা হায়খি মদুদি মেকলিন সেলেব্রিনিনা মহাক্কী চহিদগী হেন্না গেম অসি শান্নৈ।
--------------------------------------------------

Translating MNI:  33%|███████▍               | 326/1000 [03:03<05:40,  1.98it/s]

[326/1000]
EN: Canada planned to face Switzerland at the Milano Arena the next day.
MNI: মথংগী নুমীৎতা মিলানো এরিনাদা সুইজারলেন্দগী মায়োক্ননবা কানাদানা থৌরাং তৌরম্মি।
--------------------------------------------------

Translating MNI:  33%|███████▌               | 327/1000 [03:03<06:00,  1.87it/s]

[327/1000]
EN: Choi Ga-on won women’s snowboard halfpipe gold after recovering from a first-run crash.
MNI: চোই গা-ওন্না অহানবা রন ক্রাশতগী ফগৎলক্লবা মতুংদা নুপীশিংগী স্নোবোর্দ হাফপাইপ সনাগী তকমান লৌখি।
--------------------------------------------------

Translating MNI:  33%|███████▌               | 328/1000 [03:04<06:03,  1.85it/s]

[328/1000]
EN: Chloe Kim took silver and Mitsuki Ono won bronze in the halfpipe event.
MNI: হফপাইপ ইভেন্ততা ক্লোই কিমনা সিলভর অমসুং মিচুকী ওনোনা ব্রোঞ্জ লৌখি।
--------------------------------------------------

Translating MNI:  33%|███████▌               | 329/1000 [03:04<05:18,  2.11it/s]

[329/1000]
EN: Choi Ga-on scored 90.25 to beat Chloe Kim’s leading 88 score.
MNI: Choi Ga-on scored 90.25 to beat Chloe Kim's leading 88 score.
--------------------------------------------------

Translating MNI:  33%|███████▌               | 330/1000 [03:05<05:26,  2.05it/s]

[330/1000]
EN: Arsenal reached the League Cup final after Kai Havertz secured a 1-0 win.
MNI: কাই হাভর্ৎজনা ১-০না মায় পাক্লবা মতুংদা আর্সেনেলনা লীগ কপ ফাইনেল য়ৌখি।
--------------------------------------------------

Translating MNI:  33%|███████▌               | 331/1000 [03:05<05:00,  2.22it/s]

[331/1000]
EN: Kai Havertz came off the bench to finish Arsenal’s 4-2 aggregate semi-final victory.
MNI: Kai Havertz came off the bench to finish Arsenal's 4-2 aggregate semi-final victory.
--------------------------------------------------

Translating MNI:  33%|███████▋               | 332/1000 [03:06<05:15,  2.12it/s]

[332/1000]
EN: Arsenal will face Manchester City or Newcastle at Wembley on March 22.
MNI: আর্সেনেলনা মার্চ ২২দা ৱেমব্লিদা মনচেস্তর সিতী নত্ত্রগা ন্যুকাসলগা মায়োক্নগনি।
--------------------------------------------------

Translating MNI:  33%|███████▋               | 333/1000 [03:06<05:20,  2.08it/s]

[333/1000]
EN: Manchester City held a 2-0 lead over Newcastle ahead of the second leg.
MNI: অনিশুবা লেগগী মমাংদা ম্যানচেষ্টর সিতীনা ন্যুকাসেলদা ২-০না মায় পাকখি।
--------------------------------------------------

Translating MNI:  33%|███████▋               | 334/1000 [03:06<05:02,  2.20it/s]

[334/1000]
EN: Arsenal have not won the League Cup since 1993, according to the report.
MNI: রিপোর্ত অদুগী মতুংইন্না আর্সেনেলনা ইং 1993দগী লীগ কপ লৌখিদে।
--------------------------------------------------

Translating MNI:  34%|███████▋               | 335/1000 [03:07<05:52,  1.89it/s]

[335/1000]
EN: The Football Association of Ireland confirmed Ireland will fulfil Nations League fixtures against Israel.
MNI: আইরলেন্দগী ফুটবোল এসোসিয়েসননা ইজরেলগী মায়োক্তা আইরলেন্দনা নেসন্স লীগ ফিক্সচরশিং মপুং ফাহল্লগনি হায়না কনফার্ম তৌখি।
--------------------------------------------------

Translating MNI:  34%|███████▋               | 336/1000 [03:08<05:49,  1.90it/s]

[336/1000]
EN: Ireland and Israel were drawn with Austria and Kosovo in Nations League League B.
MNI: নেসন্স লীগ লীগ বিদা আইরলেন্দ অমসুং ইজরেল অসি ওস্ত্রিয়া অমসুং কোসোবোগা লোয়ননা দ্রো ওইখি ।
--------------------------------------------------

Translating MNI:  34%|███████▊               | 337/1000 [03:08<05:40,  1.95it/s]

[337/1000]
EN: Ireland must play Israel home and away between September and November.
MNI: আইরলেন্দনা সেপ্তেম্বর অমসুং নবেম্বরগী মরক্তা ইজরেলগী হোম অমসুং ওফতা শান্নবা তাই।
--------------------------------------------------

Translating MNI:  34%|███████▊               | 338/1000 [03:09<06:32,  1.69it/s]

[338/1000]
EN: The FAI warned refusal could mean forfeiture and possible disqualification under UEFA regulations.
MNI: এফ.এ.আই.না হায়খি মদুদি রিফেস তৌরবদি য়ু.ই.এফ.এ.গী রিগুলেসনগী মখাদা ফোরফিচর অমসুং দিস্ক্বালিফিকেসন ওইরকপা য়াই ।
--------------------------------------------------

Translating MNI:  34%|███████▊               | 339/1000 [03:10<07:02,  1.56it/s]

[339/1000]
EN: The FAI said it requested Israel’s UEFA ban in November after an internal vote.
MNI: এফ.এ.আই.না হায়খি মদুদি ইজরেলগী য়ু.ই.এফ.এ.
--------------------------------------------------

Translating MNI:  34%|███████▊               | 340/1000 [03:10<07:25,  1.48it/s]

[340/1000]
EN: Novak Djokovic beat Jannik Sinner 3-6, 6-3, 4-6, 6-4, 6-4 in Melbourne.
MNI: মেলবোর্নদা নোভাক জোকোভিকনা জনিক সিনরবু ৩-৬, ৬-৩, ৪-৬, ৬-৪, ৬-৪না মায়থীবা পীখি।
--------------------------------------------------

Translating MNI:  34%|███████▊               | 341/1000 [03:11<07:12,  1.52it/s]

[341/1000]
EN: Novak Djokovic’s win over Jannik Sinner set up an Australian Open final against Carlos Alcaraz.
MNI: জানিক সিনরদা নোভাক জোকোভিককী মায় পাকপনা কার্লোস অলকারাজ মায়োক্নদুনা ওস্ত্রেলিয়ান ওপনগী ফাইনেল অমা শেমখি।
--------------------------------------------------

Translating MNI:  34%|███████▊               | 342/1000 [03:12<07:21,  1.49it/s]

[342/1000]
EN: Novak Djokovic reached his 11th Australian Open final after ending four straight semi-final exits.
MNI: নোভাক জোকোবিকনা মহাক্কী ১১শুবা ওস্ত্রেলিয়ান ওপন ফাইনেলদা চপ মান্ননা সেমি ফাইনেলগী এক্সিত মরি লোইরবা মতুংদা য়ৌখি।
--------------------------------------------------

Translating MNI:  34%|███████▉               | 343/1000 [03:12<06:56,  1.58it/s]

[343/1000]
EN: Carlos Alcaraz reached his first Melbourne Park title match, the report said.
MNI: রিপোর্ত অদুদা হায়খি মদুদি কার্লোস অলকারাজনা মহাক্কী অহানবা মেলবোর্ন পার্ক তাইটল মেচতা য়ৌখি।
--------------------------------------------------

Translating MNI:  34%|███████▉               | 344/1000 [03:13<06:54,  1.58it/s]

[344/1000]
EN: Lorenzo Musetti retired mid-match after suffering a suspected upper leg tear.
MNI: লোরেঞ্জো মুসেতিনা মেটচ অদুগী মরক্তা মথক্কী খোং অদুদা ঈচাউ অমা লৈরে হায়না চিংনরবা মতুংদা রিটায়ার তৌখি।
--------------------------------------------------

Translating MNI:  34%|███████▉               | 345/1000 [03:13<06:32,  1.67it/s]

[345/1000]
EN: Lorenzo Musetti withdrew after winning the first two sets against Novak Djokovic.
MNI: লোর্ঞ্জো মুসেতিনা নোভাক জোকোভিককা মায়োক্নখিবা অহানবা সেৎ অনি মায় পাক্লবা মতুংদা হন্থখি।
--------------------------------------------------

Translating MNI:  35%|███████▉               | 346/1000 [03:14<06:38,  1.64it/s]

[346/1000]
EN: Alexander Zverev rallied from losing the first set to beat Gabriel Diallo in four sets.
MNI: আলেকজান্দর জভেরভনা অহানবা সেততা মাংখিবা অদুদগী সেত মরিদা গ্যাব্রিয়েল দাইওলোবু মায়থীবা পীখি।
--------------------------------------------------

Translating MNI:  35%|███████▉               | 347/1000 [03:15<06:48,  1.60it/s]

[347/1000]
EN: Alexander Zverev won 6-7(1), 6-1, 6-4, 6-2 against Gabriel Diallo at Rod Laver Arena.
MNI: রোদ লেভর এরিনাদা গ্যাব্রিয়েল দাইল্লোগী মায়োক্তা আলেক্সান্দর জভেরেবনা 6-7(1), 6-1, 6-4, 6-2 দা মায় পাকখি।
--------------------------------------------------

Translating MNI:  35%|████████               | 348/1000 [03:15<06:43,  1.62it/s]

[348/1000]
EN: An Australian Open report noted fans were unhappy about long queues and a ticket sales halt.
MNI: ওস্ত্রেলিয়ান ওপন রিপোর্ত অমদা ফেনশিংনা অশাংবা ক্যু অমসুং টিক্ত সেলস লেপখিবা অদুগী মরমদা নুংঙাইতবা ফোংদোকখি।
--------------------------------------------------

Translating MNI:  35%|████████               | 349/1000 [03:16<06:51,  1.58it/s]

[349/1000]
EN: A Hindustan Times column said tennis needs rivalries to elevate players and the sport.
MNI: হিন্দুস্তান টাইমসকী কলম অমনা হায়খি মদুদি শান্নরোইশিং অমসুং স্পোর্ত অসি ৱাংখৎহন্নবা টেনিসনা মায়পাক্নবা মথৌ তাই।
--------------------------------------------------

Translating MNI:  35%|████████               | 350/1000 [03:17<06:42,  1.62it/s]

[350/1000]
EN: A Hindustan Times column said Jannik Sinner and Carlos Alcaraz are improving every year.
MNI: হিন্দুস্তান টাইমসকী কলম অমনা হায়খি মদুদি জননিক সিনর অমসুং কার্লোস অলকারাজ অসি চহি খুদিংগী ফগৎলক্লি।
--------------------------------------------------

Translating MNI:  35%|████████               | 351/1000 [03:17<06:42,  1.61it/s]

[351/1000]
EN: The same column said Sinner and Alcaraz already play at a level above most players.
MNI: চপ মান্নবা কলম অদুদা হায়খি মদুদি সিনর অমসুং অলকারাজনা হান্ননা অয়াম্বা শান্নরোইশিংগী মথক্তা লেভেল অমদা শান্নরি।
--------------------------------------------------

Translating MNI:  35%|████████               | 352/1000 [03:18<06:53,  1.57it/s]

[352/1000]
EN: The column said Federer, Nadal and Djokovic gave men’s tennis a tribal feel for two decades.
MNI: কলম অদুদা হায়খি মদুদি ফেদরররর, নাদাল অমসুং জোকোভিকনা চহি তরাগী ওইনা নুপাগী তেনিসতা ত্রাইবেল ফিল অমা পীখি।
--------------------------------------------------

Translating MNI:  35%|████████               | 353/1000 [03:19<06:55,  1.56it/s]

[353/1000]
EN: A report said Alexander Zverev began a bid for a maiden Australian Open title.
MNI: রিপোর্ত অমনা হায়খি মদুদি আলেকজান্দর জভেরভনা ওস্ত্রেলিয়ান ওপনগী নুপীমচা অমা ওইনবগীদমক শান্নবা হৌখি।
--------------------------------------------------

Translating MNI:  35%|████████▏              | 354/1000 [03:19<07:14,  1.49it/s]

[354/1000]
EN: Carlos Alcaraz defeated Alexander Zverev 6-3, 3-6, 6-1, 6-2 at the Australian Open.
MNI: কার্লোস অলকারাজনা ওস্ত্রেলিয়ান ওপন্দা আলেকজান্দর জভেরভপু ৬-৩, ৩-৬, ৬-১, ৬-২না মায়থীবা পীখি।
--------------------------------------------------

Translating MNI:  36%|████████▏              | 355/1000 [03:20<06:45,  1.59it/s]

[355/1000]
EN: Carlos Alcaraz won in two hours and 26 minutes, according to the match report.
MNI: মেটচ রিপোর্টকী মতুংইন্না কার্লোস অলকারাজনা পুং অনি অমসুং মিনট ২৬তা মায় পাকখি।
--------------------------------------------------

Translating MNI:  36%|████████▏              | 356/1000 [03:20<06:47,  1.58it/s]

[356/1000]
EN: The same report said Zverev received a time-violation warning during the match.
MNI: চপ মান্নবা রিপোর্ত অদুদা হায়খি মদুদি মেটচ অদুগী মনুংদা জভেরভনা টাইম-বিয়োলেসন ৱার্নিং অমা ফংবা ঙমখি।
--------------------------------------------------

Translating MNI:  36%|████████▏              | 357/1000 [03:21<06:41,  1.60it/s]

[357/1000]
EN: The report said Alcaraz requested a meeting with the supervisor after the time warning.
MNI: রিপোর্ত অদুদা হায়খি মদুদি অলকারাজনা মতমগী ৱার্নিং অদুগী মতুংদা সুপরভাইসরগা উননবা হায়জখি।
--------------------------------------------------

Translating MNI:  36%|████████▏              | 358/1000 [03:22<06:39,  1.61it/s]

[358/1000]
EN: The report said Alcaraz complained about the length of Zverev’s breaks between points.
MNI: রিপোর্ত অদুদা হায়খি মদুদি অলকারাজনা পোইন্তকী মরক্তা জভেরভকী ব্রেককী মতম অদুগী মতাংদা কমপ্লেন্ত তৌখি।
--------------------------------------------------

Translating MNI:  36%|████████▎              | 359/1000 [03:22<06:23,  1.67it/s]

[359/1000]
EN: Carlos Alcaraz said he also wanted to know the limit for the time between points.
MNI: কার্লোস অলকারাজনা হায়খি মদুদি মহাক্না পোইন্তকী মরক্তা লৈরিবা মতমগী লিমিৎ অদুসু খংবা পাম্মি।
--------------------------------------------------

Translating MNI:  36%|████████▎              | 360/1000 [03:23<06:14,  1.71it/s]

[360/1000]
EN: R Praggnanandhaa sealed a 2026 Candidates berth by winning the FIDE Circuit 2025.
MNI: আর প্রগনানন্দনা ফিদে সর্ক্যুইৎ ২০২৫ মায় পাক্লদুনা ২০২৬গী কেন্দিদেৎশিংগী মফম অমা সিল তৌখি।
--------------------------------------------------

Translating MNI:  36%|████████▎              | 361/1000 [03:23<06:02,  1.77it/s]

[361/1000]
EN: The Candidates Tournament will determine the challenger to world champion D Gukesh.
MNI: কেন্দিদেৎস তুর্নামেন্তনা ৱার্ল্দ চেম্পিয়ন দি গুকেশকী চেলেঞ্জর অদু লেপকনি।
--------------------------------------------------

Translating MNI:  36%|████████▎              | 362/1000 [03:24<05:57,  1.79it/s]

[362/1000]
EN: R Praggnanandhaa overtook Ding Liren in May to lead the FIDE Circuit race.
MNI: এফ আই দি সর্ক্যুইৎ রেস লুচিংনবা মে থাদা দিং লিরেনবু আর প্রগনন্ধনা মায় পাকখি।
--------------------------------------------------

Translating MNI:  36%|████████▎              | 363/1000 [03:24<05:58,  1.78it/s]

[363/1000]
EN: Praggnanandhaa thanked supporters on X after earning a place in the 2026 Candidates.
MNI: ২০২৬গী কেন্দিদেৎতা মফম অমা ফংলবা মতুংদা প্রগনানন্দানা এক্সতা সপোর্তরশিংদা থাগৎপা ফোংদোকখি।
--------------------------------------------------

Translating MNI:  36%|████████▎              | 364/1000 [03:25<06:08,  1.73it/s]

[364/1000]
EN: A report said only Nodirbek Abdusattorov had a theoretical chance to catch Praggnanandhaa.
MNI: রিপোর্ত অমগী মতুংইন্না নোদিরবেক অব্দুসাততোরোবখক্তনা প্রগনানন্দাবু ফংবা ঙমখি।
--------------------------------------------------

Translating MNI:  36%|████████▍              | 365/1000 [03:26<05:59,  1.76it/s]

[365/1000]
EN: D Gukesh withdrew from Tata Steel Chess India Rapid and Blitz for personal reasons.
MNI: দি গুকেশনা তেতা স্তীল চেস ইন্দিয়া রেপিদ অমসুং ব্লিৎজদগী পর্সোনেল ওইবা মরমশিংদগী লৌথোকখি।
--------------------------------------------------

Translating MNI:  37%|████████▍              | 366/1000 [03:26<05:57,  1.77it/s]

[366/1000]
EN: Tata Steel Chess India Rapid and Blitz was scheduled in Kolkata from January 7 to 11.
MNI: টাটা স্তীল চেস ইন্দিয়া রেপিদ এন্দ ব্লিৎজ অসি জনুৱারী ৭দগী ১১ ফাওবা কলকতাদা পাংথোক্কনি।
--------------------------------------------------

Translating MNI:  37%|████████▍              | 367/1000 [03:27<05:36,  1.88it/s]

[367/1000]
EN: Nihal Sarin replaced D Gukesh in the Tata Steel Chess India event.
MNI: তেতা স্তিল চেস ইন্দিয়া ইভেন্ততা নিহল সরিননা দি গুকেশকী মহুৎ শিনখি।
--------------------------------------------------

Translating MNI:  37%|████████▍              | 368/1000 [03:27<05:56,  1.77it/s]

[368/1000]
EN: Dibyendu Barua called D Gukesh’s withdrawal a big setback for organisers and fans.
MNI: দিবিয়েন্দু বরুৱানা দি গুকেশনা লৌথোকপা অসি ওর্গানাইজরশিং অমসুং ফেনশিংগী অচৌবা সেতবেক অমনি হায়না লৌখি।
--------------------------------------------------

Translating MNI:  37%|████████▍              | 369/1000 [03:28<05:48,  1.81it/s]

[369/1000]
EN: Viswanathan Anand returned to play Tata Steel Chess India after six years away.
MNI: বিশ্বনাথন অনন্দনা চহি তরুক শুরবা মতুংদা টাটা স্তীল চেস ইন্দিয়াদা শান্নবা হল্লকখি।
--------------------------------------------------

Translating MNI:  37%|████████▌              | 370/1000 [03:28<05:53,  1.78it/s]

[370/1000]
EN: Viswanathan Anand said “It was exhausting not playing” while explaining his return.
MNI: বিশ্বনাথন অনন্দনা মহাক্কী রিতর্ন অদু শন্দোক্না তাক্লদুনা হায়খি মদুদি মহাক্না শান্নবা য়ারোইদবনি ।
--------------------------------------------------

Translating MNI:  37%|████████▌              | 371/1000 [03:29<05:31,  1.90it/s]

[371/1000]
EN: Viswanathan Anand was set to open against Wesley So in the seventh edition.
MNI: বিশ্বনাথন অনন্দ অসি ৭শুবা এদিসনদা ৱেসলী সোগী মায়োক্তা ওপন তৌগনি।
--------------------------------------------------

Translating MNI:  37%|████████▌              | 372/1000 [03:29<05:36,  1.86it/s]

[372/1000]
EN: The tournament director said Tata Steel Chess India will be held in January going forward.
MNI: টুর্নামেন্ত দাইরেক্তরনা হায়খি মদুদি তাতা স্তিল চেস ইন্দিয়া অসি জনুৱারী থাদা পাংথোক্কনি।
--------------------------------------------------

Translating MNI:  37%|████████▌              | 373/1000 [03:30<05:59,  1.75it/s]

[373/1000]
EN: The Tata Steel Chess India event offered equal prize purses of $41,500 in open and women’s.
MNI: টাটা স্তিল চেস ইন্দিয়া ইভেন্তনা ওপন অমসুং ৱুমেনগী ওইনা দোল্লর ৪১,৫০০গী মান্নবা প্রাইজ পেকেজশিং পীখি।
--------------------------------------------------

Translating MNI:  37%|████████▌              | 374/1000 [03:31<06:00,  1.74it/s]

[374/1000]
EN: Viswanathan Anand backed the Total Chess World Championship Tour approved by FIDE.
MNI: বিশ্বনাথন অনন্দনা ফাইদেনা এপ্রুভ তৌরবা টোতেল চেস ৱার্ল্দ চেম্পিয়নশিপ তুরবু শৌগৎখি।
--------------------------------------------------

Translating MNI:  38%|████████▋              | 375/1000 [03:31<06:28,  1.61it/s]

[375/1000]
EN: The Total Chess World Championship Tour will crown a new “FIDE World Combined” champion.
MNI: টোতেল চেস ৱার্ল্দ চেম্পিয়নশিপ তুরনা অনৌবা ফিদে ৱার্ল্দ কোম্বিনেদ চেম্পিয়ন অমা মুকোন শেৎলগনি।
--------------------------------------------------

Translating MNI:  38%|████████▋              | 376/1000 [03:32<05:55,  1.76it/s]

[376/1000]
EN: The tour will be held across fast classic, rapid and blitz formats.
MNI: তুর অসি ফাস্ত ক্লাসিক, রেপিদ অমসুং ব্লিৎজ ফোর্মেতশিংদা পাংথোক্কনি।
--------------------------------------------------

Translating MNI:  38%|████████▋              | 377/1000 [03:32<05:45,  1.80it/s]

[377/1000]
EN: Anand said Norway Chess has a serious long-term proposal for the new tour.
MNI: নোর্ৱী চেসনা অনৌবা তুর অসিগীদমক শাথীবা মতমগী ওইবা প্রোপোজেল অমা লৈরে হায়না অনন্দনা হায়খি।
--------------------------------------------------

Translating MNI:  38%|████████▋              | 378/1000 [03:33<05:42,  1.82it/s]

[378/1000]
EN: Anand said the sport benefits when Magnus Carlsen competes in major events.
MNI: মেজর ইভেন্তশিংদা মেগনস কার্লসেন্না শরুক য়াবা মতমদা স্পোর্ত অসিনা কান্নবা ফংই হায়না অনন্দনা হায়খি।
--------------------------------------------------

Translating MNI:  38%|████████▋              | 379/1000 [03:33<06:00,  1.72it/s]

[379/1000]
EN: Wesley So said he proposed a draw against Praggnanandhaa, not the arbiters.
MNI: ৱেসলী সোনা হায়খি মদুদি মহাক্না প্রগনানন্দাগী মায়োক্তা দ্রো অমা তৌনবা প্রপোজ তৌখি অদুবু আর্বিটরশিং অদুগী মায়োক্তা তৌখিদে।
--------------------------------------------------

Translating MNI:  38%|████████▋              | 380/1000 [03:34<05:44,  1.80it/s]

[380/1000]
EN: Praggnanandhaa had one second left before stopping the clock to call the arbiter.
MNI: প্রগনানন্দনা দাইরেক্তর অদু কৌনবা ক্লোক থিংদ্রিঙৈ মমাংদা সেকেন্দ অমা লৈখি।
--------------------------------------------------

Translating MNI:  38%|████████▊              | 381/1000 [03:35<05:55,  1.74it/s]

[381/1000]
EN: Nihal Sarin won the 2026 Tata Steel Chess India Rapid Tournament in Kolkata.
MNI: কোলকতাদা পাংথোকপা ২০২৬তা তাটা স্তীল চেস ইন্দিয়া রেপিদ তুর্নামেন্ততা নিহল সরিননা মায় পাকখি।
--------------------------------------------------

Translating MNI:  38%|████████▊              | 382/1000 [03:35<06:55,  1.49it/s]

[382/1000]
EN: Ian Nepomniachtchi criticised hotel conditions during the 2025 Chess World Cup in Goa.
MNI: গোৱাদা পাংথোক্কদৌরিবা ২০২৫ দা পাংথোক্কদৌরিবা চেস ৱার্ল্দ কপকী মনুংদা ওইরিবা হোতেলগী ফিভমশিং ইয়ান নেপমনিয়াচিনা কন্ত্রাইক্ত তৌখি।
--------------------------------------------------

Translating MNI:  38%|████████▊              | 383/1000 [03:36<06:31,  1.58it/s]

[383/1000]
EN: Ian Nepomniachtchi said organisers chose one of the worst hotels for the Goa event.
MNI: গোৱা ইভেন্তকীদমক ওর্গানাইজরশিংনা খ্বাইদগী ফবা হোতেলশিংগী মনুংদা অমা খনখি হায়না ইয়ন নেপমনিয়াচিনা হায়খি।
--------------------------------------------------

Translating MNI:  38%|████████▊              | 384/1000 [03:37<06:05,  1.69it/s]

[384/1000]
EN: Nepomniachtchi lost to Diptayan Ghosh after receiving a bye into round two.
MNI: অনিশুবা রাউন্দদা বাই অমা ফংলবা মতুংদা নেপমনিয়াচকী দিপতান ঘোসতা মাংখি।
--------------------------------------------------

Translating MNI:  38%|████████▊              | 385/1000 [03:37<05:59,  1.71it/s]

[385/1000]
EN: PGTI’s 2026 schedule was drawn up only till March-end, featuring six events.
MNI: পি জি তি আইগী ২০২৬গী সেদ্যুল অসি ইভেন্ত তরুক য়াওনা মার্চকী অরোইবা ফাউবা শেমখি।
--------------------------------------------------

Translating MNI:  39%|████████▉              | 386/1000 [03:38<06:10,  1.66it/s]

[386/1000]
EN: PGTI planned no more than 25 tournaments in 2026 after holding 36 events last year.
MNI: হৌখিবা চহিদা ইভেন্ত ৩৬ পাংথোক্লবা মতুংদা পি জি তি আইনা ২০২৬দা টুর্নামেন্ত ২৫দগী হেন্না পাংথোক্তনবা পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  39%|████████▉              | 387/1000 [03:38<06:09,  1.66it/s]

[387/1000]
EN: PGTI’s main tour offered ₹35 crore prize money in 2025, up from ₹24 crore.
MNI: পি জি তি আইগী মপুং ওইবা তুরনা ২০২৫দা লুপা ক্রোর ২৪দগী লুপা ক্রোর ৩৫গী প্রাইজ মনি পীখি।
--------------------------------------------------

Translating MNI:  39%|████████▉              | 388/1000 [03:39<06:37,  1.54it/s]

[388/1000]
EN: OWGR granted LIV Golf accreditation for the first time, awarding points to top-10 finishers.
MNI: ও.দবল্যু.জি.আর.না অহানবা ওইনা লিভ গোল্ফ এক্রেদিতেসন পীখি অমসুং মকোক থোংবা মপুং ১০ ফারবা মীওইশিংদা পোইন্তশিং পীখি।
--------------------------------------------------

Translating MNI:  39%|████████▉              | 389/1000 [03:40<06:29,  1.57it/s]

[389/1000]
EN: LIV Golf expanded tournaments from 54 to 72 holes in 2026, paving the approval.
MNI: লিভ গোল্ফনা ২০২৬দা টুর্নামেন্ত ৫৪ দগী ৭২দা পাকথোক চাউথোকহনখি অমসুং মসিগী অয়াবা পীখি।
--------------------------------------------------

Translating MNI:  39%|████████▉              | 390/1000 [03:40<06:44,  1.51it/s]

[390/1000]
EN: OWGR said LIV Golf did not meet all eligibility standards under its requirements.
MNI: ও.দবল্যু.জি.আর.না হায়খি মদুদি লিভ গোল্ফনা মসিগী মথৌ তাবশিংগী মখাদা ইলিজিবিলিতি স্তেন্দর্দ পুম্নমক ফংদে।
--------------------------------------------------

Translating MNI:  39%|████████▉              | 391/1000 [03:41<06:28,  1.57it/s]

[391/1000]
EN: LIV Golf’s season-opening event in Riyadh was set to start with 57 players.
MNI: রিয়াধতা পাংথোক্কদৌরিবা লিভ গোল্ফকী সিজন ওপনিং ইভেন্ত অসি শান্নরোই ৫৭গা লোয়ননা হৌদোক্কনি।
--------------------------------------------------

Translating MNI:  39%|█████████              | 392/1000 [03:42<06:34,  1.54it/s]

[392/1000]
EN: International Series India was expected to move from DLF Golf and Country Club to Bengaluru.
MNI: ইন্তর্নেস্নেল সিরিজ ইন্দিয়া অসি দি.এল.এফ. গোল্ফ এন্দ কন্ত্রী ক্লবতগী বেঙ্গালুরুদা চৎকনি হায়না পানরি।
--------------------------------------------------

Translating MNI:  39%|█████████              | 393/1000 [03:42<06:24,  1.58it/s]

[393/1000]
EN: Bryson DeChambeau and Joaquin Niemann were key draws at International Series India 2025.
MNI: ইন্তর্নেস্নেল সিরিজ ইন্দিয়া ২০২৫দা ব্রাইসন দেচেমৌ অমসুং জোঅকিন নিমন্না মরুওইবা দ্রো ওইখি।
--------------------------------------------------

Translating MNI:  39%|█████████              | 394/1000 [03:43<06:12,  1.63it/s]

[394/1000]
EN: Ollie Schniederjans won International Series India 2025 by four shots in Gurugram.
MNI: ওলি স্নিদর্জন্না ইন্তর্নেস্নেল সিরিজ ইন্দিয়া ২০২৫বু গুরুগ্রামদা শোট মরিনা মায় পাকখি।
--------------------------------------------------

Translating MNI:  40%|█████████              | 395/1000 [03:43<06:05,  1.65it/s]

[395/1000]
EN: Rahul Singh said International Series organisers remained committed to returning to India.
MNI: রাহুল সিংহনা হায়খি মদুদি ইন্তর্নেস্নেল সিরিজ ওর্গানাইজরশিংনা ভারত্তা হল্লক্নবা অয়াবা থম্লি।
--------------------------------------------------

Translating MNI:  40%|█████████              | 396/1000 [03:44<06:12,  1.62it/s]

[396/1000]
EN: PGTI launched a league with six franchises, with each franchise buying 10 players.
MNI: পি জি তি আইনা ফ্রাঞ্চাইজি তরুক য়াওনা লীগ অমা হৌদোকখি অমসুং ফ্রাঞ্চাইজি খুদিংমক্না শান্নরোই ১০ লৌখি।
--------------------------------------------------

Translating MNI:  40%|█████████▏             | 397/1000 [03:45<05:47,  1.73it/s]

[397/1000]
EN: The PGTI league’s first edition was planned across three courses in Delhi-NCR.
MNI: পি জি তি আই লীগগী অহানবা এদিসন অসি দিল্লী-এন সি আরদা কোর্স অহুমদা প্লান তৌরি।
--------------------------------------------------

Translating MNI:  40%|█████████▏             | 398/1000 [03:45<05:57,  1.68it/s]

[398/1000]
EN: Shubhankar Sharma missed cuts in 21 of 28 events in 2025, the report said.
MNI: রিপোর্ত অদুদা হায়খি মদুদি ইং ২০২৫দা পাংথোক্কদবা ইভেন্ত ২৮গী মনুংদা ২১দা শুভঙ্কর শর্মানা ক্ত তৌখিদে।
--------------------------------------------------

Translating MNI:  40%|█████████▏             | 399/1000 [03:46<06:10,  1.62it/s]

[399/1000]
EN: Shubhankar Sharma regained playing rights for 2026 via Q-School, finishing tied-second.
MNI: ক্যু-স্কুলগী খুত্থাংদা শুভঙ্কর শর্মানা ২০২৬কীদমক শান্নবগী অধিকার অমুক হন্না ফংবা ঙমখি অমসুং অনিশুবদা লোইশিনখি।
--------------------------------------------------

Translating MNI:  40%|█████████▏             | 400/1000 [03:46<05:52,  1.70it/s]

[400/1000]
EN: Vietnam targets 22 to 25 million international visitors by 2026.
MNI: ভিয়েতনামনা ২০২৬ ফাওবদা ইন্তরনেস্নেল ভিজিটর মিলিয়ন ২২ দগী ২৫ ফাউবা পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  40%|█████████▏             | 401/1000 [03:47<05:34,  1.79it/s]

[401/1000]
EN: Operations teams monitor weather to minimize passenger inconvenience.
MNI: পেসেঞ্জরশিংগী খুদোংচাদবা হন্থহন্নবা ওপরেসনগী তীমশিংনা ৱেদর মোনিটর তৌই।
--------------------------------------------------

Translating MNI:  40%|█████████▏             | 402/1000 [03:47<05:36,  1.78it/s]

[402/1000]
EN: IndiGo announces Amsterdam debut as first long-haul European destination.
MNI: ইন্দিগোনা ওমস্তর্দামদা অহানবা লোং-হেল য়ুরোপকী গন্তব্য ওইনা দেবিৎ তৌনবা লাউথোকখ্রে।
--------------------------------------------------

Translating MNI:  40%|█████████▎             | 403/1000 [03:48<05:40,  1.76it/s]

[403/1000]
EN: Air India crash committee investigates Boeing 787-8 Ahmedabad tragedy.
MNI: এয়র ইন্দিয়া ক্রাশ কমিতিনা বোইং ৭৮৭-৮ অহমেদাবাদ ত্রাজেদিগী মতাংদা ইনভেষ্টিগেসন তৌরি।
--------------------------------------------------

Translating MNI:  40%|█████████▎             | 404/1000 [03:49<05:33,  1.78it/s]

[404/1000]
EN: IndiGo aims for forty percent international capacity share by 2030.
MNI: ইন্দিগোনা ইং ২০৩০ ফাওবদা ইন্তর্নেস্নেল কেপাসিতি সেয়ার চাদা ৪০ ফংহন্নবা পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  40%|█████████▎             | 405/1000 [03:49<05:14,  1.89it/s]

[405/1000]
EN: One survivor rescued from Air India crash site in Ahmedabad.
MNI: অহমেদাবাদতা লৈবা এয়র ইন্দিয়াগী ক্রাশ সাইটদগী হিংলিবা মীওই অমা রেস্ক্যু তৌখ্রে।
--------------------------------------------------

Translating MNI:  41%|█████████▎             | 406/1000 [03:50<05:03,  1.96it/s]

[406/1000]
EN: Jetstar Asia closure frees five hundred million dollars for Qantas.
MNI: জেতস্তার এসিয়া ক্লোজরনা কন্তাসকীদমক দোল্লর মিলিয়ন মঙা ফ্রি তৌরি।
--------------------------------------------------

Translating MNI:  41%|█████████▎             | 407/1000 [03:50<04:58,  1.99it/s]

[407/1000]
EN: Qantas Group announces closure of Singapore-based Jetstar Asia.
MNI: কন্তাস গ্রুপনা শিঙ্গাপুরদা য়ুম্ফম ওইবা জেৎস্তার এসিয়া ক্লোজ তৌরগনি হায়না লাউথোকখ্রে।
--------------------------------------------------

Translating MNI:  41%|█████████▍             | 408/1000 [03:50<04:45,  2.08it/s]

[408/1000]
EN: IndiGo launches Mumbai-Manchester flights using Norse aircraft.
MNI: ইন্দিগোনা নোর্স এয়রক্রাফ শিজিন্নদুনা মুম্বাই-মানচেস্তর ফ্লাইৎ হৌদোক্লে।
--------------------------------------------------

Translating MNI:  41%|█████████▍             | 409/1000 [03:51<05:06,  1.93it/s]

[409/1000]
EN: IndiGo transitions to A350-900 aircraft for European expansion by 2027.
MNI: ইন্দিগোনা ২০২৭ ফাওবদা য়ুরোপিয়ান এক্সপেন্সনগীদমক এ৩৫০-৯০০ এয়রক্রাফতগী ত্রান্সসিসন তৌগনি।
--------------------------------------------------

Translating MNI:  41%|█████████▍             | 410/1000 [03:51<04:50,  2.03it/s]

[410/1000]
EN: Air India Ahmedabad crash claims 242 lives including Vijay Rupani.
MNI: এয়র ইন্দিয়া অহেমদবাদ ক্রাশনা বিজয় রুপানি য়াওনা মীওই ২৪২বু শিহল্লে।
--------------------------------------------------

Translating MNI:  41%|█████████▍             | 411/1000 [03:52<04:44,  2.07it/s]

[411/1000]
EN: Thirteen Jetstar Asia A320s redeployed to Australia and New Zealand.
MNI: জেৎস্তার এসিয়া এ৩২০ ১৩ ওস্ত্রেলিয়া অমসুং ন্যু জিলেন্দদা রিদিলোপ তৌখ্রে।
--------------------------------------------------

Translating MNI:  41%|█████████▍             | 412/1000 [03:52<04:50,  2.02it/s]

[412/1000]
EN: IndiGo issues fog advisory for Delhi and northern India passengers.
MNI: ইন্দিগোনা দিল্লী অমসুং অৱাং ভারতকী পেসেঞ্জরশিংগীদমক নেগ এদভাইজরি ইসু তৌরি।
--------------------------------------------------

Translating MNI:  41%|█████████▍             | 413/1000 [03:53<04:56,  1.98it/s]

[413/1000]
EN: DGCA imposes ₹2 crore fine on Air India for safety lapses.
MNI: দিজিসিএনা সেফতী লেপসকীদমক এয়র ইন্দিয়াদা লুপা ক্রোর ২গী ফাইন পীরি।
--------------------------------------------------

Translating MNI:  41%|█████████▌             | 414/1000 [03:53<04:51,  2.01it/s]

[414/1000]
EN: Sixteen intra-Asia routes lose only non-stop Changi connections.
MNI: ইন্ত্রা-এসিয়াগী লম্বী তরামঙাদা নন-স্তোপ চাংজি কনেক্সনখক্তমক মাংখি।
--------------------------------------------------

Translating MNI:  42%|█████████▌             | 415/1000 [03:54<04:49,  2.02it/s]

[415/1000]
EN: Bengaluru airport opens second runway to handle growing traffic.
MNI: বেঙ্গালুরু এয়রপোর্তনা অহেনবা ত্রাফিক হেন্দল তৌনবা অনিশুবা রনৱে হাংদোক্লে।
--------------------------------------------------

Translating MNI:  42%|█████████▌             | 416/1000 [03:55<05:09,  1.89it/s]

[416/1000]
EN: Air India Express pilot assaults passenger at Delhi airport terminal.
MNI: দিল্লী এয়রপোর্ত তর্মিনেলদা এয়র ইন্দিয়া এক্সপ্রেস পাইলোতনা পেসেঞ্জর অমা খুৎলায় চেনখি।
--------------------------------------------------

Translating MNI:  42%|█████████▌             | 417/1000 [03:55<05:04,  1.92it/s]

[417/1000]
EN: Mumbai airport witnesses record passenger footfall during festive week.
MNI: কুম্মৈগী চয়োলগী মনুংদা মুম্বাইগী এয়রপোর্ততা পেসেঞ্জরগী খোং হাম্বা রেকোর্দ ওইরে।
--------------------------------------------------

Translating MNI:  42%|█████████▌             | 418/1000 [03:56<05:04,  1.91it/s]

[418/1000]
EN: Dense fog disrupts IndiGo flight operations across North India.
MNI: অৱাং-নোংপোক ভারতকী মফম কয়াদা ইন্দিগোগী ফ্লাইৎ ওপরেসনশিং লেপ্তনা লৈহল্লে।
--------------------------------------------------

Translating MNI:  42%|█████████▋             | 419/1000 [03:56<04:59,  1.94it/s]

[419/1000]
EN: Go First insolvency resolution extends to third consecutive month.
MNI: গো ফার্ষ্ত ইনসোলভেন্সী রিজোলুসন অসি মথং মথং অহুমশুবা থাগী ওইনা শাংদোক্লে।
--------------------------------------------------

Translating MNI:  42%|█████████▋             | 420/1000 [03:57<05:03,  1.91it/s]

[420/1000]
EN: Akasa Air orders additional Boeing 737 Max aircraft for expansion.
MNI: একাসা এয়রনা এক্সপেন্সনগীদমক অহেনবা বোইং ৭৩৭ মেক্স এয়রক্রাফ ওর্দর তৌরি।
--------------------------------------------------

Translating MNI:  42%|█████████▋             | 421/1000 [03:57<05:07,  1.88it/s]

[421/1000]
EN: Air India pilots union raises concerns over rest period violations.
MNI: এয়র ইন্দিয়া পাইলোৎস য়ুনিয়ননা রেস্ত পেরিওদ ভিল্যুএসনগী মতাংদা পুক্নিং থৌগৎলি।
--------------------------------------------------

Translating MNI:  42%|█████████▋             | 422/1000 [03:58<05:20,  1.80it/s]

[422/1000]
EN: EU launches Entry-Exit System campaign for non-EU travellers.
MNI: য়ু.ই.না নন-ইয়ু.ই.গী ত্রেভেলরশিংগীদমক এন্ত্রি-এক্সিৎ সিস্তেম কেম্পেন হৌদোক্লে।
--------------------------------------------------

Translating MNI:  42%|█████████▋             | 423/1000 [03:58<05:09,  1.87it/s]

[423/1000]
EN: SpiceJet secures funding to revive grounded fleet operations soon.
MNI: স্পাইসজেৎনা অথুবা মতমদা গ্রাউন্দ ফ্লিত ওপরেসনশিং অমুক হন্না হৌদোক্নবা ফন্দ ফংহল্লি।
--------------------------------------------------

Translating MNI:  42%|█████████▊             | 424/1000 [03:59<05:04,  1.89it/s]

[424/1000]
EN: Bulgaria adopts Euro as legal tender from January first 2026.
MNI: বুলগেরিয়ানা ২০২৬গী জনুৱারী অহানবাদগী য়ুরো অসি লিগেল টেন্দর ওইনা চৎনহনগনি।
--------------------------------------------------

Translating MNI:  42%|█████████▊             | 425/1000 [03:59<05:06,  1.88it/s]

[425/1000]
EN: Vietnam grants forty-five day visa-free entry to twelve European nations.
MNI: ভিয়েতনামনা য়ুরোপকী লৈবাক তরানিপালদা নুমিৎ কুন মঙা ভিজা য়াউদনা চৎপা য়াহনখ্রে।
--------------------------------------------------

Translating MNI:  43%|█████████▊             | 426/1000 [04:00<04:44,  2.02it/s]

[426/1000]
EN: Indian government reverses ban on Sikh pilgrimages to Pakistan.
MNI: ভারত সরকারনা পাকিস্থানদা শিখশিংনা খুরুমজিনবগী অথীংবা লৌথোকখ্রে।
--------------------------------------------------

Translating MNI:  43%|█████████▊             | 427/1000 [04:00<04:43,  2.02it/s]

[427/1000]
EN: Pakistan High Commission issues visas to twenty-one hundred Sikh pilgrims.
MNI: পাকিস্থান হাই কম্মিসননা শিখ তীর্থগ্রামী চামচা হুম্লিশীংদা ভিজা ইসু তৌরি।
--------------------------------------------------

Translating MNI:  43%|█████████▊             | 428/1000 [04:01<04:35,  2.08it/s]

[428/1000]
EN: TSA ends shoe removal rule at domestic United States airports.
MNI: টিএসএনা য়ুনাইতেদ স্তেতস এয়রপোর্তশিংদা পায়খুম লৌথোকপগী নিয়ম লোইশিনখ্রে।
--------------------------------------------------

Translating MNI:  43%|█████████▊             | 429/1000 [04:01<04:47,  1.99it/s]

[429/1000]
EN: Real ID enforcement charges tourists forty-five dollars for domestic flights.
MNI: রিএল আইদি এনফোর্সমেন্তনা দোমেষ্টিক ফ্লাইতশিংগীদমক তুরিস্তশিংদা দোল্লর ৪৫ চার্জ তৌই।
--------------------------------------------------

Translating MNI:  43%|█████████▉             | 430/1000 [04:02<04:51,  1.96it/s]

[430/1000]
EN: United States government shutdown causes forty-three day travel chaos.
MNI: য়ুনাইটেদ ষ্টেটস গবর্ণমেন্টনা শাটদাউন তৌবনা নুমিৎ চাম্লিশীং চৎপগী থৌদোক থোকহল্লি।
--------------------------------------------------

Translating MNI:  43%|█████████▉             | 431/1000 [04:02<04:52,  1.94it/s]

[431/1000]
EN: Government considers hotel industry infrastructure status for tax benefits.
MNI: সরকারনা তেক্সকী কান্নবশিংগীদমক হোতেল ইন্দস্ত্রীগী ইনফ্রাস্ত্রকচরগী থাক অদু খন্নরি।
--------------------------------------------------

Translating MNI:  43%|█████████▉             | 432/1000 [04:03<04:47,  1.97it/s]

[432/1000]
EN: Gajendra Singh Shekhawat announces infrastructure status proposal for hotels.
MNI: গজেন্দ্র সিংহ শেখবতনা হোতেলশিংগীদমক ইনফ্রাস্ত্রকচর স্তেতস প্রপোজেল লাওথোকখ্রে।
--------------------------------------------------

Translating MNI:  43%|█████████▉             | 433/1000 [04:03<04:48,  1.96it/s]

[433/1000]
EN: Tourism Ministry reboots Incredible India campaign with AI focus.
MNI: তুরিজম মন্ত্রালয়না এ আইদা মীৎয়েং থমদুনা ইক্রেদিবেল ইন্দিয়া কেম্পেন রিবুৎ তৌরি।
--------------------------------------------------

Translating MNI:  43%|█████████▉             | 434/1000 [04:04<04:46,  1.98it/s]

[434/1000]
EN: Suman Billa confirms new digital-centric Incredible India strategy.
MNI: সুমন বিলানা অনৌবা দিজিতেল সেন্ত্রিক ইক্রেদিবেল ইন্দিয়া স্ত্রেতেজী কনফার্ম তৌরি।
--------------------------------------------------

Translating MNI:  44%|██████████             | 435/1000 [04:04<04:47,  1.97it/s]

[435/1000]
EN: India targets one trillion dollar tourism economy by 2047.
MNI: ২০৪৭ ফাওবদা ভারতনা দোল্লর ত্রিলিয়ন অমগী তুরিজম ইকোনোমী পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  44%|██████████             | 436/1000 [04:05<04:35,  2.04it/s]

[436/1000]
EN: Centre sanctions fifty destinations for challenge mode tourism development.
MNI: চেলেঞ্জ মোদ তুরিজম দিবেলপমেন্তকীদমক কেন্দ্রনা দস্তিনেসন মঙা সেঙ্কসন তৌখ্রে।
--------------------------------------------------

Translating MNI:  44%|██████████             | 437/1000 [04:05<04:23,  2.14it/s]

[437/1000]
EN: Telangana adopts Sarathi portal for online RTA services.
MNI: তেলঙ্গানানা ওনলাইন আরতিএ সর্বিসশিংগীদমক সরথি পোর্তেল হৌদোক্লে।
--------------------------------------------------

Translating MNI:  44%|██████████             | 438/1000 [04:06<04:23,  2.13it/s]

[438/1000]
EN: Ministry announces twelve thousand crore rupees for new tourism destinations.
MNI: মন্ত্রালয়না অনৌবা তুরিজম দস্তিনেসনশিংগীদমক লুপা কোতি লিশিং তরাগী শেনফম লাওথোকখ্রে।
--------------------------------------------------

Translating MNI:  44%|██████████             | 439/1000 [04:06<04:29,  2.08it/s]

[439/1000]
EN: Government allocates 1.34 billion dollars for tourism infrastructure development.
MNI: সরকারনা তুরিজম ইনফ্রাস্ত্রকচর দিবেলপমেন্তকীদমক দোল্লর বিলিয়ন ১.৩৪ পীরি।
--------------------------------------------------

Translating MNI:  44%|██████████             | 440/1000 [04:07<04:25,  2.11it/s]

[440/1000]
EN: India plans 2030 Commonwealth Games hosting to boost tourism.
MNI: তুরিজম হেনগৎহন্নবা ভারতনা কমনৱেল্থ গেম্স ২০৩০ হোস্ত তৌনবা পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  44%|██████████▏            | 441/1000 [04:07<04:31,  2.06it/s]

[441/1000]
EN: Census self-enumeration trial begins for digital population count.
MNI: দিজিতেল পোপুলেসন কাউন্তকীদমক্তা সেন্সস সেল্ফ-ইনুমরেসন ত্রাইএল হৌই।
--------------------------------------------------

Translating MNI:  44%|██████████▏            | 442/1000 [04:08<04:35,  2.02it/s]

[442/1000]
EN: European Commission launches biometric border system awareness campaign.
MNI: য়ুরোপিয়ান কম্মিসননা বাইওমেত্রিক বোর্দর সিস্তেম এৱারনেস কেম্পেন হৌদোকখ্রে।
--------------------------------------------------

Translating MNI:  44%|██████████▏            | 443/1000 [04:08<04:46,  1.95it/s]

[443/1000]
EN: Non-EU travellers face new digital border checks from October.
MNI: ইয়ুরোপিয়ান য়ুনিয়নগী ওইদবা মীওইশিংনা ওক্তোবরদগী অনৌবা দিজিতেল বোর্দর চেকশিং থেংনগনি।
--------------------------------------------------

Translating MNI:  44%|██████████▏            | 444/1000 [04:09<05:00,  1.85it/s]

[444/1000]
EN: Dover ferry passengers register first for EU entry-exit system.
MNI: দোবর ফেরি পেসেঞ্জরশিংনা ইয়ু এন্ত্রি-ইক্সিৎ সিস্তেমগীদমক অহানবদা রেজিস্তার তৌগনি।
--------------------------------------------------

Translating MNI:  44%|██████████▏            | 445/1000 [04:09<05:01,  1.84it/s]

[445/1000]
EN: Eurostar business travellers gradually included in EES rollout.
MNI: ইওরোস্তার ব্যুজিনেস ত্রেভেলরশিং তপ্না তপ্না ইইএস রোল্লাউত্তা য়াওখি।
--------------------------------------------------

Translating MNI:  45%|██████████▎            | 446/1000 [04:10<04:30,  2.05it/s]

[446/1000]
EN: India extends e-visa facility to citizens of five more nations.
MNI: ভারতনা লৈবাক মঙাগী নাগরিকশিংদা ই-ভিজাগী খুদোংচাবা পীরি।
--------------------------------------------------

Translating MNI:  45%|██████████▎            | 447/1000 [04:10<04:34,  2.02it/s]

[447/1000]
EN: Karnataka announces tourism policy targeting fifty billion dollar investment
MNI: কর্নাতকানা দোল্লর বিলিয়ন মঙাগী ইনভেস্তমেন্ত পান্দম থমদুনা তুরিজম পোলিসী লাওথোকখ্রে
--------------------------------------------------

Translating MNI:  45%|██████████▎            | 448/1000 [04:11<04:34,  2.01it/s]

[448/1000]
EN: GST Council reduces tax on hotel rooms below seven thousand five hundred rupees.
MNI: জিএসতি কাউন্সিলনা হোতেল রুমশিংদা লুপা লিশিং তরাদগী হন্থবা তেক্স হন্থহল্লে।
--------------------------------------------------

Translating MNI:  45%|██████████▎            | 449/1000 [04:11<04:28,  2.05it/s]

[449/1000]
EN: Ministry of Tourism launches Swadesh Darshan 3.0 for sustainable tourism.
MNI: তুরিজম মন্ত্রালয়না সস্তেনেবল তুরিজমগীদমক স্বদেশ দর্শন ৩.০ হৌদোকখ্রে।
--------------------------------------------------

Translating MNI:  45%|██████████▎            | 450/1000 [04:12<04:41,  1.95it/s]

[450/1000]
EN: Civil Aviation Ministry orders probe into Delhi airport assault case.
MNI: সিভিল এভিয়েসন মিনিস্ত্রীনা দিল্লী এয়রপোর্ত এসোল্ত কেসতা প্রোবেস তৌনবা ওর্দর পীরি।
--------------------------------------------------

Translating MNI:  45%|██████████▎            | 451/1000 [04:12<04:30,  2.03it/s]

[451/1000]
EN: Government approves UDAN 5.0 with focus on helicopter services.
MNI: হেলিকোপ্তর সর্বিসশিংদা মীৎয়েং থমদুনা সরকারনা উদান ৫.০ অয়াবা পীরে।
--------------------------------------------------

Translating MNI:  45%|██████████▍            | 452/1000 [04:13<04:32,  2.01it/s]

[452/1000]
EN: Kerala declares tourism as industry status for hotels and resorts.
MNI: হোতেল অমসুং রিসোর্তশিংগীদমক টুরিজম অসি ইন্দস্ত্রী স্তেতস অমা ওইনা কেরলানা লাউথোকখ্রে।
--------------------------------------------------

Translating MNI:  45%|██████████▍            | 453/1000 [04:13<04:15,  2.14it/s]

[453/1000]
EN: West Bengal secures second rank in foreign tourist arrivals.
MNI: মপান্দগী লাকপা তুরিস্তশিংগী মনুংদা ৱেস্ত বেঙ্গল অনিশুবা মফমদা লৈরি।
--------------------------------------------------

Translating MNI:  45%|██████████▍            | 454/1000 [04:14<04:17,  2.12it/s]

[454/1000]
EN: Mamata Banerjee hails West Bengal's international tourism milestone.
MNI: মমতা বেনর্জীনা ৱেস্ত বেঙ্গলগী ইন্তরনেস্নেল তুরিজম মাইলস্তোন অদু তরাম্না ওকখি।
--------------------------------------------------

Translating MNI:  46%|██████████▍            | 455/1000 [04:14<04:23,  2.07it/s]

[455/1000]
EN: Maharashtra leads foreign tourist arrivals with 3.71 million visitors.
MNI: মহারাস্ত্রানা ভিজিটর মিলিয়ন ৩.৭১গা লোয়ননা মপাল লৈবাক্কী তুরিস্তশিং লাকপদা মকোক থোংবা লৈরি।
--------------------------------------------------

Translating MNI:  46%|██████████▍            | 456/1000 [04:15<04:23,  2.07it/s]

[456/1000]
EN: West Bengal records 3.12 million foreign tourist visits nationwide.
MNI: ৱেস্ত বেঙ্গলনা লৈবাক শিনবা থুংনা মপান লৈবাক্কী তুরিস্ত মিলিয়ন ৩.১২ লাকপগী রেকোর্দ লৈরি।
--------------------------------------------------

Translating MNI:  46%|██████████▌            | 457/1000 [04:15<04:42,  1.92it/s]

[457/1000]
EN: Uttar Pradesh tops domestic tourism with 646.81 million visitors.
MNI: উত্তর প্রদেশনা দোমেস্তিক তুরিজমদা মীশিং মিল্লিয়ন ৬৪৬.৮১গা লোয়ননা মকোক থোংবা মফম অমা ওইরি।
--------------------------------------------------

Translating MNI:  46%|██████████▌            | 458/1000 [04:16<04:31,  1.99it/s]

[458/1000]
EN: Tamil Nadu records 306.84 million domestic tourist footfall.
MNI: তামিল নাদুদা দোমেষ্টিক তুরিস্ত ফুটফোল মিলিয়ন ৩০৬.৮৪ রেকোর্দ তৌরি।
--------------------------------------------------

Translating MNI:  46%|██████████▌            | 459/1000 [04:16<04:20,  2.07it/s]

[459/1000]
EN: India receives 2,948.19 million domestic tourists during 2024.
MNI: ২০২৪দা ভারতনা দোমেস্তিক তুরিস্ত মিলিয়ন ২,৯৪৮.১৯ ফংগনি।
--------------------------------------------------

Translating MNI:  46%|██████████▌            | 460/1000 [04:17<04:12,  2.14it/s]

[460/1000]
EN: Foreign tourist visits to India touch 20.94 million in 2024.
MNI: ইং ২০২৪দা ভারত্তা লাকপা মপাল লৈবাক্কী তুরিস্তশিংনা মিলিয়ন ২০.৯৪ য়ৌখ্রে।
--------------------------------------------------

Translating MNI:  46%|██████████▌            | 461/1000 [04:17<04:10,  2.15it/s]

[461/1000]
EN: Domestic tourism records 17.51 percent growth over previous year.
MNI: মমাংগী চহিগা চাংদম্নবদা দোমেস্তিক তুরিজমনা চাদা ১৭.৫১ হেনগৎলে।
--------------------------------------------------

Translating MNI:  46%|██████████▋            | 462/1000 [04:17<04:05,  2.19it/s]

[462/1000]
EN: International tourist arrivals grow 8.84 percent in 2024.
MNI: ২০২৪দা ইন্তর্নেস্নেল তুরিস্ত এরিবেলশিং চাদা ৮.৮৪ হেনগৎলগনি।
--------------------------------------------------

Translating MNI:  46%|██████████▋            | 463/1000 [04:18<03:53,  2.30it/s]

[463/1000]
EN: Maha Kumbh Mela attracts 663 million visits across forty-five days.
MNI: মহা কুম্ভ মেলানা নুমিৎ ৪৫নিগী মনুংদা মীওই মিলিয়ন ৬৬৩ লাকখি।
--------------------------------------------------

Translating MNI:  46%|██████████▋            | 464/1000 [04:18<04:02,  2.21it/s]

[464/1000]
EN: Prayagraj witnesses 660 million pilgrims at Sangam confluence.
MNI: প্রয়াগরাজনা সঙ্গম কনফ্লুএন্সতা লাই খুরুমজবশিং মিলিয়ন ৬৬০ উরি।
--------------------------------------------------

Translating MNI:  46%|██████████▋            | 465/1000 [04:19<04:16,  2.09it/s]

[465/1000]
EN: Vietnam welcomes 1.73 million international visitors during October 2025.
MNI: ভিয়েতনামনা ওক্তোবর ২০২৫দা ইন্তরনেস্নেল ভিজিটর মিলিয়ন ১.৭৩বু তরাম্না ওকখি।
--------------------------------------------------

Translating MNI:  47%|██████████▋            | 466/1000 [04:19<04:11,  2.13it/s]

[466/1000]
EN: Vietnam records 13.8 percent monthly growth in foreign tourist arrivals.
MNI: ভিয়েতনামনা মপানগী তুরিস্তশিং লাকপদা থাগী ওইনা চাদা ১৩.৮ হেনগৎলক্লি।
--------------------------------------------------

Translating MNI:  47%|██████████▋            | 467/1000 [04:20<04:06,  2.17it/s]

[467/1000]
EN: India attracts only ten million international tourists annually currently.
MNI: হৌজিক্কী ওইনা ভারত্তা চহি খুদিংগী ইন্তরনেস্নেল তুরিস্ত মিলিয়ন তরাখক্তমক লাকই।
--------------------------------------------------

Translating MNI:  47%|██████████▊            | 468/1000 [04:20<03:59,  2.22it/s]

[468/1000]
EN: France welcomes ninety million tourists against India's ten million.
MNI: ভারতকী মিলিয়ন তরাদা ফ্রান্সনা তুরিস্ত মিলিয়ন তরাগী তরাম্না ওক্লি।
--------------------------------------------------

Translating MNI:  47%|██████████▊            | 469/1000 [04:20<03:44,  2.36it/s]

[469/1000]
EN: Spain receives eighty-four million international visitors annually.
MNI: স্পেননা চহি খুদিংগী ইন্টরনেসনেল ভিজিটর মিলিয়ন ৮৪ ফংগনি।
--------------------------------------------------

Translating MNI:  47%|██████████▊            | 470/1000 [04:21<03:50,  2.30it/s]

[470/1000]
EN: United States hosts eighty million foreign tourists every year.
MNI: য়ুনাইতেদ স্তেৎসতা চহি খুদিংগী মপানগী তুরিষ্ট মিলিয়ন ৮০ লাকই।
--------------------------------------------------

Translating MNI:  47%|██████████▊            | 471/1000 [04:21<03:56,  2.24it/s]

[471/1000]
EN: India's pre-Covid tourist arrival figures remain unmatched after six years.
MNI: ভারতকী প্রি-কোবিদ তুরিস্ত এরিবেলগী মশিং অসি চহি তরুককী মতুংদা মান্নদবা লৈতে।
--------------------------------------------------

Translating MNI:  47%|██████████▊            | 472/1000 [04:22<03:49,  2.30it/s]

[472/1000]
EN: Tourism contributes 5.2 percent to India's current GDP.
MNI: তুরিজমনা ভারতকী হৌজিক্কী জিদিপিদা চাদা ৫.২গী কন্ত্রিব্যুসন পীরি।
--------------------------------------------------

Translating MNI:  47%|██████████▉            | 473/1000 [04:22<03:48,  2.30it/s]

[473/1000]
EN: Tourism sector supports 84 million livelihoods across India.
MNI: তুরিজম সেক্তরনা ভারত শিনবা থুংনা লিভলিহুদ মিলিয়ন ৮৪ সপোর্ত তৌরি।
--------------------------------------------------

Translating MNI:  47%|██████████▉            | 474/1000 [04:23<04:13,  2.08it/s]

[474/1000]
EN: FICCI predicts 250 billion dollar tourism opportunity by 2030.
MNI: ফিক্সিনা ইং ২০৩০ ফাওবদা দোল্লর বিলিয়ন ২৫০গী তুরিজমগী খুদোংচাবা ফংহনগনি হায়না পানরি।
--------------------------------------------------

Translating MNI:  48%|██████████▉            | 475/1000 [04:23<04:17,  2.04it/s]

[475/1000]
EN: ICRA reports hotel demand to exceed supply in coming years.
MNI: লাক্কদৌরিবা চহিশিংদা হোতেলগী দিমান্দ অসি সপ্লাইদগী হেনগৎলগনি হায়না আইসিআরএনা রিপোর্ট তৌরি।
--------------------------------------------------

Translating MNI:  48%|██████████▉            | 476/1000 [04:24<04:18,  2.03it/s]

[476/1000]
EN: Global travel industry generates 10.9 trillion dollars for economies.
MNI: গ্লোবেল ত্রেভেল ইন্দস্ত্রীনা ইকোনোমীশিংগীদমক দোল্লর ত্রিলিয়ন ১০.৯ পুথোকই।
--------------------------------------------------

Translating MNI:  48%|██████████▉            | 477/1000 [04:24<04:03,  2.15it/s]

[477/1000]
EN: Travel and tourism accounts for ten percent of global GDP.
MNI: ত্রেভেল অমসুং তুরিজমনা মালেমগী জিদিপিগী চাদা তরা ওইরি।
--------------------------------------------------

Translating MNI:  48%|██████████▉            | 478/1000 [04:25<04:11,  2.07it/s]

[478/1000]
EN: Vietnam targets 22 to 26 million international visitors by 2026.
MNI: ভিয়েতনামনা ২০২৬ ফাওবদা ইন্তরনেস্নেল ভিজিটর মিলিয়ন ২২ দগী ২৬ ফাউবা পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  48%|███████████            | 479/1000 [04:25<04:07,  2.10it/s]

[479/1000]
EN: Belgium citizens enjoy forty-five day visa-free Vietnam travel.
MNI: বেলজিয়মগী নাগরিকশিংনা নুমিৎ মঙাগী ভিজা য়াউদনা ভিয়েতনাম চৎপা য়াই।
--------------------------------------------------

Translating MNI:  48%|███████████            | 480/1000 [04:26<04:06,  2.11it/s]

[480/1000]
EN: Poland nationals receive visa-free entry to Vietnam under new scheme.
MNI: অনৌবা স্কিমগী মখাদা ভিয়েতনামদা পোলেন্দগী নাগরিকশিংনা ভিজা য়াউদনা চৎপা য়াগনি।
--------------------------------------------------

Translating MNI:  48%|███████████            | 481/1000 [04:26<04:10,  2.07it/s]

[481/1000]
EN: Swiss passport holders travel visa-free to Vietnam for forty-five days.
MNI: সুইস পাসপোর্ট হোল্ডরশিংনা নুমিৎ চাম্লিশা ভিজা য়াউদনা ভিয়েতনামদা চৎলি।
--------------------------------------------------

Translating MNI:  48%|███████████            | 482/1000 [04:27<04:06,  2.10it/s]

[482/1000]
EN: Saudi Red Sea Authority issues twelve marine tourism licences.
MNI: সাউদী রেদ সি ওথোরিতীনা মেরিন তুরিজম লাইসেন্স তরানিপাল ইসু তৌরি।
--------------------------------------------------

Translating MNI:  48%|███████████            | 483/1000 [04:27<03:52,  2.22it/s]

[483/1000]
EN: Red Sea Cruises receives approval under Cruise Saudi brand.
MNI: রেদ সি ক্রুইজনা ক্রুইজ সাউদী ব্রান্দগী মখাদা অয়াবা ফংলে।
--------------------------------------------------

Translating MNI:  48%|███████████▏           | 484/1000 [04:28<04:00,  2.15it/s]

[484/1000]
EN: Sindalah Marina in NEOM secures Saudi marine tourism licence.
MNI: নিওমদা লৈবা সিন্দালা মেরিনানা সাউদী মেরিন তুরিজম লাইসেন্স সেক্যুওর তৌরি।
--------------------------------------------------

Translating MNI:  48%|███████████▏           | 485/1000 [04:28<04:00,  2.14it/s]

[485/1000]
EN: Dolphin Beach Resort Marina obtains Yanbu operating approval.
MNI: দোলফিন বিচ রিসোর্ট মেরিনানা ইয়ানবু ওপরেতিং এপ্রুভেল ফংলে।
--------------------------------------------------

Translating MNI:  49%|███████████▏           | 486/1000 [04:29<04:00,  2.14it/s]

[486/1000]
EN: Jeddah Municipality Marina included in Saudi licensing round.
MNI: জেদ্দা ম্যুনিসিপালিতী মেরিনা অসি সাউদী লাইসেন্সিং রাউন্দতা য়াওরি।
--------------------------------------------------

Translating MNI:  49%|███████████▏           | 487/1000 [04:29<03:56,  2.17it/s]

[487/1000]
EN: Deep Seas Shipping Agency gains tourism shipping agent licence.
MNI: দিপ সিজ শিপ্পিং এজেন্সিনা তুরিজম শিপ্পিং এজেন্ত লাইসেন্স ফংলে।
--------------------------------------------------

Translating MNI:  49%|███████████▏           | 488/1000 [04:29<04:00,  2.13it/s]

[488/1000]
EN: Venice extends day-tripper entrance fee to sixty days.
MNI: ভেনিসনা দে-ত্রাইপর এন্ত্রেস ফিশীং নুমিৎ তরানিপালদা শাংদোক্লে।
--------------------------------------------------

Translating MNI:  49%|███████████▏           | 489/1000 [04:30<04:21,  1.96it/s]

[489/1000]
EN: Venice charges day-trippers from Friday to Sunday between April and July.
MNI: ভেনিসনা এপ্রিল অমসুং জুলাইগী মরক্তা শুক্রাইদগী নোংমাইজিং ফাওবা নুমিৎকী খোংচৎ চৎপদা চার্জ লৌই।
--------------------------------------------------

Translating MNI:  49%|███████████▎           | 490/1000 [04:31<04:12,  2.02it/s]

[490/1000]
EN: Simone Venturini calls Venice entry fee tangible innovation tool.
MNI: সিমোন ভেন্তুরিনিনা ভেনিস এন্ত্রি ফিবু টেনিবল ইনোভেসন টুল হায়না কৌই।
--------------------------------------------------

Translating MNI:  49%|███████████▎           | 491/1000 [04:31<04:00,  2.11it/s]

[491/1000]
EN: Amsterdam introduces tourist fees to fight overtourism congestion.
MNI: ওভরতুরিজম কোজেসন থেংননবা আমস্তর্দম্না তুরিস্ত ফিশিং হৌদোকখি।
--------------------------------------------------

Translating MNI:  49%|███████████▎           | 492/1000 [04:31<03:53,  2.18it/s]

[492/1000]
EN: Greece passes laws limiting visitor numbers to popular islands.
MNI: গ্রিসনা মীয়াম তিনবা ইথৎশিংদা ভিজিটরগী মশিং হন্থহন্নবা আইনশিং পাস তৌরি।
--------------------------------------------------

Translating MNI:  49%|███████████▎           | 493/1000 [04:32<04:00,  2.11it/s]

[493/1000]
EN: Japan implements tourist fees to manage overcrowding at sites.
MNI: জাপাননা সাইটশীংদা ওভরক্রাউদিং মেনেজ তৌনবগীদমক তুরিষ্ট ফিশীং ইমপ্লিমেন্ত তৌই।
--------------------------------------------------

Translating MNI:  49%|███████████▎           | 494/1000 [04:32<04:02,  2.09it/s]

[494/1000]
EN: Hurricane Melissa devastates Jamaica's tourism infrastructure.
MNI: হুরাইকেন মেলিসানা জামাইকাগী তুরিজম ইনফ্রাস্ত্রকচর মাংহনখ্রে।
--------------------------------------------------

Translating MNI:  50%|███████████▍           | 495/1000 [04:33<04:10,  2.02it/s]

[495/1000]
EN: Jamaica opens for business after Hurricane Melissa recovery.
MNI: হুরাইকেন মেলিসা রিকোভরি তৌরবা মতুংদা জামাইকা অসি ব্যুজিনেসকীদমক্তা হাংদোকখ্রে।
--------------------------------------------------

Translating MNI:  50%|███████████▍           | 496/1000 [04:33<03:59,  2.10it/s]

[496/1000]
EN: Canadian visitation to United States continues to plummet.
MNI: য়ুনাইতেদ স্তেতসতা কানাদাগী ভিজিতাইজেসন মখা তানা হন্থরক্লি।
--------------------------------------------------

Translating MNI:  50%|███████████▍           | 497/1000 [04:34<04:02,  2.07it/s]

[497/1000]
EN: Sean Duffy focuses on America's ailing air travel system.
MNI: শোন দফিনা অমেরিকাগী অনাবা এয়র ত্রাভেল সিস্তেমদা মীৎয়েং থম্লি।
--------------------------------------------------

Translating MNI:  50%|███████████▍           | 498/1000 [04:34<04:19,  1.93it/s]

[498/1000]
EN: Trump administration policies impact travel both positively and negatively.
MNI: ত্রম্প এদমিনিস্ত্রেসনগী পোলিসীশিংনা ত্রেভেলদা পোজিতিব অমসুং নেগেতিব অনিমক ইম্পেক্ট তৌই।
--------------------------------------------------

Translating MNI:  50%|███████████▍           | 499/1000 [04:35<04:16,  1.95it/s]

[499/1000]
EN: Sri Lanka regime change attributed to poor governance by Ajit Doval.
MNI: শ্রীলঙ্কাগী রেজিম চেঞ্জ অসি অজিত দোবালনা ফত্তবা গবর্নান্সনা মরম ওইখি ।
--------------------------------------------------

Translating MNI:  50%|███████████▌           | 500/1000 [04:35<04:21,  1.91it/s]

[500/1000]
EN: Bangladesh leadership transition results from poor governance failures.
MNI: বঙ্গলাদেশকী লুচিংবশিংগী ত্রান্সসিসন অসি লায়রবা গবর্নান্সনা মায়থীবা পীরি।
--------------------------------------------------

Translating MNI:  50%|███████████▌           | 501/1000 [04:36<04:14,  1.96it/s]

[501/1000]
EN: Nepal government change linked to governance issues says Doval.
MNI: গবর্নান্সকী ইসুশিংগা মরি লৈননা নেপাল গবর্নমেন্ত হোংদোক্লে হায়না দোবেলনা হায়রি।
--------------------------------------------------

Translating MNI:  50%|███████████▌           | 502/1000 [04:36<04:04,  2.04it/s]

[502/1000]
EN: Thailand launches five year multiple entry tourist visa scheme.
MNI: থাইলেন্দনা চহি মঙাগী মল্তিপল এন্ত্রি তুরিস্ত ভিজা স্কিম হৌদোক্লে।
--------------------------------------------------

Translating MNI:  50%|███████████▌           | 503/1000 [04:37<03:43,  2.23it/s]

[503/1000]
EN: Sri Lanka grants free visa to seven countries including India.
MNI: শ্রীলঙ্কানা ভারত য়াওনা লৈবাক তরেৎতা ভিজা লেম্না পীরি।
--------------------------------------------------

Translating MNI:  50%|███████████▌           | 504/1000 [04:37<03:48,  2.17it/s]

[504/1000]
EN: Maldives lifts emergency but tourism recovery remains sluggish.
MNI: মালদিবসনা এমর্জেন্সি লৌথোক্লে অদুবু তুরিজমগী রিকোভরি অদু লেপ্তনা লৈরি।
--------------------------------------------------

Translating MNI:  50%|███████████▌           | 505/1000 [04:38<04:01,  2.05it/s]

[505/1000]
EN: UAE announces five year multiple entry visa for Indian nationals.
MNI: য়ু.এ.ই.না ভারতকী নাগরিকশিংগীদমক চহি মঙাগী মল্তিপল এন্ত্রি ভিজা লাওথোকখ্রে।
--------------------------------------------------

Translating MNI:  51%|███████████▋           | 506/1000 [04:38<03:55,  2.10it/s]

[506/1000]
EN: Schengen visa fees increase from eighty to ninety Euros globally.
MNI: শেনগন ভিসাগী ফি অসি মালেমগী ওইনা য়ুরো ৮০ দগী ৯০ ফাউবা হেনগৎলে।
--------------------------------------------------

Translating MNI:  51%|███████████▋           | 507/1000 [04:39<03:57,  2.08it/s]

[507/1000]
EN: Japan resumes short term tourist visa processing for Indians.
MNI: জাপাননা ভারত মচাশিংগীদমক অতেনবা মতমগী তুরিস্ত ভিজা প্রোসেসিং অমুক হন্না হৌদোক্লে।
--------------------------------------------------

Translating MNI:  51%|███████████▋           | 508/1000 [04:39<03:45,  2.18it/s]

[508/1000]
EN: India operates 127 airports with ten new cruise terminals.
MNI: অনৌবা ক্রুজ তর্মিনেল তরাগা লোয়ননা ভারত্তা এয়রপোর্ত ১২৭ লৈরি।
--------------------------------------------------

Translating MNI:  51%|███████████▋           | 509/1000 [04:39<03:30,  2.34it/s]

[509/1000]
EN: Government constructs 150,000 kilometres of new national highways.
MNI: সরকারনা অনৌবা নেস্নেল হাইৱে কিলোমীতর ১৫০,০০০ শাগৎলি।
--------------------------------------------------

Translating MNI:  51%|███████████▋           | 510/1000 [04:40<03:32,  2.31it/s]

[510/1000]
EN: India develops 38 national waterways for inland cruise tourism.
MNI: ভারতনা ইনলেন্দ ক্রুজ তুরিজমগীদমক নেস্নেল ৱাতরৱে ৩৮ দিবেলপ তৌরি।
--------------------------------------------------

Translating MNI:  51%|███████████▊           | 511/1000 [04:40<03:36,  2.26it/s]

[511/1000]
EN: Metro rail network expands 10,000 kilometres across 23 cities.
MNI: মেত্রো রেল নেটৱার্ক অসি সহর ২৩দা কিলোমীতর ১০,০০০ পাকথোক চাউথোকহল্লি।
--------------------------------------------------

Translating MNI:  51%|███████████▊           | 512/1000 [04:41<03:42,  2.20it/s]

[512/1000]
EN: Swadesh Darshan 2.0 develops tourism sites to global standards.
MNI: স্বদেশ দর্শন ২.০না গ্লোবেল স্তেন্দর্দকী মতুংইন্না তুরিজম সাইটশিং দিবেলপ তৌরি।
--------------------------------------------------

Translating MNI:  51%|███████████▊           | 513/1000 [04:41<03:53,  2.09it/s]

[513/1000]
EN: PRASHAD scheme enhances pilgrimage tourism infrastructure across India.
MNI: প্রসাদ স্কিমনা ভারত শিনবা থুংনা পিলগ্রিমেজ তুরিজম ইনফ্রাস্ত্রকচর হেঙ্গৎহল্লি।
--------------------------------------------------

Translating MNI:  51%|███████████▊           | 514/1000 [04:42<04:08,  1.95it/s]

[514/1000]
EN: Saudi Red Sea authority enforces international safety standards for marine tourism.
MNI: সাউদী রেদ সি ওথোরিতীনা মেরিন তুরিজমগীদমক ইন্তর্নেস্নেল সেফতী স্তেন্দর্দশিং চৎনহল্লি।
--------------------------------------------------

Translating MNI:  52%|███████████▊           | 515/1000 [04:42<04:00,  2.01it/s]

[515/1000]
EN: Saudi marine regulations protect Red Sea coral reef ecosystems.
MNI: সাউদীগী মেরিন রিগুলেসনশিংনা রেদ সি কোরেল রিফ ইকোসিস্তেমশিং ঙাকথোক্লি।
--------------------------------------------------

Translating MNI:  52%|███████████▊           | 516/1000 [04:43<03:47,  2.13it/s]

[516/1000]
EN: Saudi Red Sea tourism to add 85 billion riyals to GDP.
MNI: সাউদী রেদ সি তুরিজমনা জিদিপিদা রিএল বিলিয়ন ৮৫ হাপচিনগনি।
--------------------------------------------------

Translating MNI:  52%|███████████▉           | 517/1000 [04:43<03:41,  2.18it/s]

[517/1000]
EN: Red Sea tourism creates 210,000 Saudi jobs by 2030.
MNI: রেদ সি তুরিজমনা ইং ২০৩০ ফাওবদা সাউদীদা থবক ২১০,০০০ ফংহল্লগনি।
--------------------------------------------------

Translating MNI:  52%|███████████▉           | 518/1000 [04:44<03:40,  2.19it/s]

[518/1000]
EN: Indian Railways recovers only fraction of 4,087 crore dues.
MNI: ইন্দিয়ান রেলৱেজনা কোতি ৪,০৮৭গী শেনফমগী শরুক খক্তমক ফগৎলে।
--------------------------------------------------

Translating MNI:  52%|███████████▉           | 519/1000 [04:44<03:43,  2.15it/s]

[519/1000]
EN: RLDA develops only fraction of railway land for commercial use.
MNI: আর.এল.দি.এ.না কমর্সিয়েল ওইনা শিজিন্ননবগীদমক রেলৱেগী লম খরখক্তমক দিবেলপ তৌই।
--------------------------------------------------

Translating MNI:  52%|███████████▉           | 520/1000 [04:45<03:37,  2.20it/s]

[520/1000]
EN: Central Railway announces train diversions for Dasara and Diwali.
MNI: সেন্ত্রেল রেলৱেনা দশারা অমসুং দীৱালীগীদমক ত্রেন দিভর্সনশিং লাউথোকখ্রে।
--------------------------------------------------

Translating MNI:  52%|███████████▉           | 521/1000 [04:45<03:32,  2.26it/s]

[521/1000]
EN: SCR cancels 69 trains due to operational requirements.
MNI: এস.সি.আর.না ত্রেন ৬৯ অপরেস্নেলগী মথৌ তাবদগী কেন্সেল তৌখ্রে।
--------------------------------------------------

Translating MNI:  52%|████████████           | 522/1000 [04:46<03:34,  2.23it/s]

[522/1000]
EN: South Central Railway diverts 29 trains for festival management.
MNI: সাউথ সেন্ত্রেল রেলৱেনা ফেস্তিবেল মেনেজমেন্তকীদমক ত্রেন ২৯ দিভর্ট তৌরি।
--------------------------------------------------

Translating MNI:  52%|████████████           | 523/1000 [04:46<03:25,  2.32it/s]

[523/1000]
EN: Indian Railways announces 18 partially cancelled train services.
MNI: ইন্দিয়ান রেলৱেজনা ত্রেন সর্বিস ১৮ কন্সেল তৌখ্রে হায়না লাউথোকখ্রে।
--------------------------------------------------

Translating MNI:  52%|████████████           | 524/1000 [04:46<03:24,  2.33it/s]

[524/1000]
EN: Three trains rescheduled by South Central Railway authority.
MNI: সাউথ সেন্ত্রেল রেলৱে ওথোরিতিনা ত্রেন অহুম অমুক হন্না সেদ্যুল তৌখ্রে।
--------------------------------------------------

Translating MNI:  52%|████████████           | 525/1000 [04:47<03:20,  2.36it/s]

[525/1000]
EN: SCR cancels total 119 train services during peak season.
MNI: এস সি আরনা পিক সিজনগী মনুংদা অপুনবা ত্রেন সর্বিস ১১৯ কেন্সেল তৌখ্রে।
--------------------------------------------------

Translating MNI:  53%|████████████           | 526/1000 [04:47<03:27,  2.28it/s]

[526/1000]
EN: Disney Cruise Line debuts Disney Destiny vessel in 2025.
MNI: দিজনী ক্রুজ লাইননা দিজনী দেস্তিনিগী মপান্দা ইং ২০২৫দা দিবেৎ তৌরি।
--------------------------------------------------

Translating MNI:  53%|████████████           | 527/1000 [04:48<03:23,  2.32it/s]

[527/1000]
EN: Norwegian Cruise Line adds Norwegian Aqua to fleet.
MNI: নোর্বেজিয়ান ক্রুজ লাইননা নোর্বেজিয়ান এক্বা ফ্লিৎতা হাপচিল্লে।
--------------------------------------------------

Translating MNI:  53%|████████████▏          | 528/1000 [04:48<03:17,  2.40it/s]

[528/1000]
EN: Royal Caribbean launches Star of the Seas cruise ship.
MNI: রোইল কেরিবিয়াননা স্তার ওফ দি সিজ ক্রুইজ শিপ হৌদোকখ্রে।
--------------------------------------------------

Translating MNI:  53%|████████████▏          | 529/1000 [04:49<03:28,  2.26it/s]

[529/1000]
EN: Varanasi airport expands terminal to handle five million passengers.
MNI: বরানসী এয়রপোর্তনা তর্মিনেল পাকথোক চাউথোকহন্দুনা পেসেঞ্জর মিলিয়ন মঙা হেন্দল্লি।
--------------------------------------------------

Translating MNI:  53%|████████████▏          | 530/1000 [04:49<03:35,  2.18it/s]

[530/1000]
EN: Kashmir Railway line reaches Baramulla for all weather connectivity.
MNI: কাশ্মীর রেলৱে লাইননা মেতর কনেক্তিবিতীগীদমক বারামুল্লাদা য়ৌরি।
--------------------------------------------------

Translating MNI:  53%|████████████▏          | 531/1000 [04:50<03:37,  2.15it/s]

[531/1000]
EN: Ayodhya airport commences commercial flight operations for pilgrims.
MNI: অয়োধ্যা এয়রপোর্তনা লাইচৎ চৎলবশিংগীদমক কমর্সিয়েল ফ্লাইৎ ওপরেসনশিং হৌদোক্লে।
--------------------------------------------------

Translating MNI:  53%|████████████▏          | 532/1000 [04:50<03:40,  2.12it/s]

[532/1000]
EN: Chennai metro phase two extension connects airport to city centre.
MNI: চেন্নাই মেত্রো ফেজ অনিগী এক্সতেন্সননা এয়রপোর্ত অসি সহর সেন্তরগা শম্নহল্লি।
--------------------------------------------------

Translating MNI:  53%|████████████▎          | 533/1000 [04:50<03:35,  2.17it/s]

[533/1000]
EN: Mumbai Trans Harbour Link reduces travel time to Navi Mumbai airport.
MNI: মুম্বাই ত্রান্স হার্বর লিঙ্কনা নাবি মুম্বাই এয়রপোর্ততা চৎপগী মতম হন্থহল্লি।
--------------------------------------------------

Translating MNI:  53%|████████████▎          | 534/1000 [04:51<03:35,  2.17it/s]

[534/1000]
EN: Kashi Vishwanath corridor transforms pilgrimage experience in Varanasi.
MNI: কাশী বিশ্বনাথ কোরিদোরনা বরানসীদা তীর্থ চৎপগী এক্সপিরিএন্স হোংদোক্লে।
--------------------------------------------------

Translating MNI:  54%|████████████▎          | 535/1000 [04:51<03:18,  2.35it/s]

[535/1000]
EN: Hyatt completes acquisition of Playa Hotels and Resorts.
MNI: হায়াতনা প্লেয়া হোতেল অমসুং রিসোর্তশিং লৌশিনবা লোইশিনখ্রে।
--------------------------------------------------

Translating MNI:  54%|████████████▎          | 536/1000 [04:52<03:31,  2.19it/s]

[536/1000]
EN: Hyatt adds fifteen beachfront properties across Mexico and Jamaica.
MNI: হাইএত্তনা মেক্সিকো অমসুং জামাইকা শিনবা থুংনা সমুদ্র খোংবালগী লম তরামঙা হাপচিল্লে।
--------------------------------------------------

Translating MNI:  54%|████████████▎          | 537/1000 [04:52<03:25,  2.25it/s]

[537/1000]
EN: Hyatt acquires Secrets La Romana in Dominican Republic.
MNI: হায়এত্তনা দোমিনিকান রিপব্লিকতা সেক্রেতস লা রোমানা লৌখি।
--------------------------------------------------

Translating MNI:  54%|████████████▎          | 538/1000 [04:53<03:36,  2.13it/s]

[538/1000]
EN: Dreams La Romana joins Hyatt portfolio through Playa acquisition.
MNI: দ্রিমস লা রোমানানা প্লেয়া এক্বিজিশনগী খুত্থাংদা হায়এৎ পোর্তফোলিওদা য়াওরি।
--------------------------------------------------

Translating MNI:  54%|████████████▍          | 539/1000 [04:53<03:40,  2.09it/s]

[539/1000]
EN: Dreams Rose Hall in Montego Bay transfers to Hyatt ownership.
MNI: মোন্তেগো বেদা লৈবা দ্রিমস রোজ হোলনা হায়এত্তকী মপু ওইনদি ত্রান্সফর তৌখি।
--------------------------------------------------

Translating MNI:  54%|████████████▍          | 540/1000 [04:54<03:31,  2.18it/s]

[540/1000]
EN: Hyatt Vivid Playa del Carmen added to hotel collection.
MNI: হায়এৎ ভিভিদ প্লেয়া দেল কারমেন অসি হোতেল কলেক্সন্দা হাপচিল্লে।
--------------------------------------------------

Translating MNI:  54%|████████████▍          | 541/1000 [04:54<03:34,  2.14it/s]

[541/1000]
EN: Sunscape Cancun becomes Hyatt property after Playa deal.
MNI: সানস্কেপ কানকুন অসি প্লেয়া দিলগী মতুংদা হায়এৎ প্রোপর্টি ওইরকখি।
--------------------------------------------------

Translating MNI:  54%|████████████▍          | 542/1000 [04:55<03:44,  2.04it/s]

[542/1000]
EN: Hotel infrastructure status unlocks private investment says Shekhawat.
MNI: হোতেলগী ইনফ্রাস্ত্রকচরগী থাক অসিনা প্রাইভেৎ ইনভেস্তমেন্ত মুত্থৎহল্লি হায়না শেখবৎনা হায়রি।
--------------------------------------------------

Translating MNI:  54%|████████████▍          | 543/1000 [04:55<03:46,  2.02it/s]

[543/1000]
EN: FICCI annual general meeting discusses tourism growth strategy.
MNI: ফিক্কিগী চহিগী জেনরেল মীফমদা তুরিজম গ্রোথ স্ত্রেতেজীগী মতাংদা খন্ন-নৈনখি।
--------------------------------------------------

Translating MNI:  54%|████████████▌          | 544/1000 [04:56<03:43,  2.04it/s]

[544/1000]
EN: Harsh Vardhan Agarwal highlights tourism as economic driver.
MNI: হর্শ বর্ধন অগরৱালনা তুরিজমবু ইকোনোমিক দ্রাইভর অমা ওইনা ফোংদোক্লি।
--------------------------------------------------

Translating MNI:  55%|████████████▌          | 545/1000 [04:56<03:42,  2.05it/s]

[545/1000]
EN: Anant Goenka praises Swadesh Darshan and PRASHAD initiatives.
MNI: অনন্ত গোয়েঙ্কানা স্বদেশ দর্শন অমসুং প্রসাদ ইনিসিয়েতিবশিং অদু থাগৎপা ফোংদোকখি।
--------------------------------------------------

Translating MNI:  55%|████████████▌          | 546/1000 [04:57<03:45,  2.01it/s]

[546/1000]
EN: Indian hotel industry seeks infrastructure status for tax benefits.
MNI: ভারতকী হোতেল ইন্দস্ত্রীনা তেক্সকী কান্নবা ফংনবগীদমক ইনফ্রাস্ত্রকচরগী থাক লৌনবা হোৎনরি।
--------------------------------------------------

Translating MNI:  55%|████████████▌          | 547/1000 [04:57<03:48,  1.99it/s]

[547/1000]
EN: Shangri-La Bengaluru hosts Chef Simone Loisi Italian culinary residency.
MNI: শঙ্গ্রি-লা বেঙ্গালুরুদা শেফ সিমোন লোসি ইতালিয়ান কুলিনরি রেসিদেন্সি লৈরি।
--------------------------------------------------

Translating MNI:  55%|████████████▌          | 548/1000 [04:58<03:42,  2.03it/s]

[548/1000]
EN: Chef Simone Loisi brings Southern Italian cuisine to Bangalore.
MNI: শেফ সিমোন লোসিনা সাউথরন ইতালিয়ান কুক্সনবু বেঙ্গলোরদা পুরকখি।
--------------------------------------------------

Translating MNI:  55%|████████████▋          | 549/1000 [04:58<03:45,  2.00it/s]

[549/1000]
EN: Waterfall Ristorante Italiano chef showcases cuisine at Shangri-La.
MNI: ৱাতরফোল রিস্তোরেন্ত ইতালিয়ানো শেফনা শঙ্গ্রি-লাদা থোংবা চিঞ্জাক উৎলি।
--------------------------------------------------

Translating MNI:  55%|████████████▋          | 550/1000 [04:59<03:39,  2.05it/s]

[550/1000]
EN: Four Seasons Bengaluru transforms for Halloween 2025 celebrations.
MNI: ফোর সিজন বেঙ্গালুরুনা হেরোলোইন ২০২৫ পাংথোক্নবগীদমক অহোংবা পুরক্লি।
--------------------------------------------------

Translating MNI:  55%|████████████▋          | 551/1000 [04:59<03:37,  2.06it/s]

[551/1000]
EN: CUR8 hosts family friendly Halloween evening in Bengaluru.
MNI: সিয়ুআর৮না বেঙ্গালুরুদা ফেমিলি ফ্রেন্দলি হোল্লোইন ইভেন্ত হোস্ত তৌরি।
--------------------------------------------------

Translating MNI:  55%|████████████▋          | 552/1000 [04:59<03:20,  2.24it/s]

[552/1000]
EN: Copitas bar ranks in Asia's 50 Best Bars list.
MNI: কোপিটাস বার অসি এসিয়াগী বেস্ত বার ৫০গী লিস্ততা য়াওরি।
--------------------------------------------------

Translating MNI:  55%|████████████▋          | 553/1000 [05:00<03:15,  2.28it/s]

[553/1000]
EN: Four Seasons Bengaluru hosts Día de Muertos Halloween party.
MNI: ফোর সিজন বেঙ্গালুরুদা দে দে মর্টোস হেরোলোইন পার্টি পাংথোকই।
--------------------------------------------------

Translating MNI:  55%|████████████▋          | 554/1000 [05:00<03:20,  2.23it/s]

[554/1000]
EN: Sheraton Hyderabad invites guests to Feast Halloween buffet.
MNI: শেরাতোন হায়দ্রবাদনা গেস্তশিংবু ফেস্ত হেরোলোইন বুফেদা লাক্নবা তকশিনখ্রে।
--------------------------------------------------

Translating MNI:  56%|████████████▊          | 555/1000 [05:01<03:32,  2.09it/s]

[555/1000]
EN: Chef Yugal Sharma represents North West Frontier cuisine at ITC.
MNI: শেফ য়ুগল শর্মানা আইতিসিদা অৱাং নোংপোক ফ্রোন্তিয়র ক্যুজেনগী মীহুৎ ওইরি।
--------------------------------------------------

Translating MNI:  56%|████████████▊          | 556/1000 [05:01<03:37,  2.04it/s]

[556/1000]
EN: Royal Afghan assistant master chef promotes rustic Indian cuisine.
MNI: রয়েল অফগান এসিস্তেন্ত মাস্তর শেফনা ভারতকী পাক-চাউবা প্রোমোৎ তৌই।
--------------------------------------------------

Translating MNI:  56%|████████████▊          | 557/1000 [05:02<03:41,  2.00it/s]

[557/1000]
EN: The Leela Hyderabad hosts Chef Picched three-day Thai culinary showcase.
MNI: লীলা হায়দ্রবাদতা সেফ পিকচেতনা নুমিৎ অহুমগী ওইবা থাই কুলিনরি শোকেস পাংথোক্কনি।
--------------------------------------------------

Translating MNI:  56%|████████████▊          | 558/1000 [05:02<03:47,  1.94it/s]

[558/1000]
EN: Chef Picched Paoleng brings authentic Bangkok cuisine to Hyderabad.
MNI: শেফ পিকচেদ পওলিংনা হায়দ্রবাদতা ওথেন্টিকেল ওইবা বেঙ্গোক্কী থোং-থাকপা পুরক্লে।
--------------------------------------------------

Translating MNI:  56%|████████████▊          | 559/1000 [05:03<04:03,  1.81it/s]

[559/1000]
EN: Marriott Executive Apartments Bengaluru unveils Madras Kitchen restaurant.
MNI: মেরিয়োৎ এক্সেক্যুতিব এপার্টমেন্তস বেঙ্গালুরুনা মাদ্রাজ কিচেন রেস্তোরান্ত মায়খুম হাংদোকখ্রে।
--------------------------------------------------

Translating MNI:  56%|████████████▉          | 560/1000 [05:04<03:55,  1.87it/s]

[560/1000]
EN: Madras Kitchen pays homage to South Indian gastronomic heritage.
MNI: মাদ্রাজ কিচেননা খা ভারতকী গ্যাসত্রোনোমিক হেরিতেজদা ইকায় খুম্নবা উৎলি।
--------------------------------------------------

Translating MNI:  56%|████████████▉          | 561/1000 [05:04<03:56,  1.85it/s]

[561/1000]
EN: ITC Grand Bharat chef shares Diwali festive dinner hosting tips.
MNI: আই তি সি গ্রান্দ ভারত শেফনা দিৱালী ফেস্তিবেল দিনর হোস্তিংগী পাউতাকশিং শেয়র তৌরি।
--------------------------------------------------

Translating MNI:  56%|████████████▉          | 562/1000 [05:05<04:10,  1.75it/s]

[562/1000]
EN: Marriott Executive Apartments Hyderabad celebrates Hyderabadi dessert heritage.
MNI: মেরিয়োৎ এক্সেক্যুতিব এপার্টমেন্তস হায়দ্রবাদনা হায়দ্রাবাদকী দ্রেসর্ত হেরিতেজ সেলেব্রেৎ তৌরি।
--------------------------------------------------

Translating MNI:  56%|████████████▉          | 563/1000 [05:05<03:56,  1.85it/s]

[563/1000]
EN: 4Note culinary hot spot opens with four kitchens concept.
MNI: 4নোট কুলিনরী হোট স্পোৎ অসি কিচেন মরিগী কন্সেপ্টগা লোয়ননা হাংদোক্লে।
--------------------------------------------------

Translating MNI:  56%|████████████▉          | 564/1000 [05:06<03:46,  1.93it/s]

[564/1000]
EN: Zuma Abu Dhabi maintains global legacy restaurant standards.
MNI: জুমা আবু ধাবীনা গ্লোবেল লেগেসি রেস্তোরান্ত স্তেন্দর্দ ঙাক্লি।
--------------------------------------------------

Translating MNI:  56%|████████████▉          | 565/1000 [05:06<03:36,  2.01it/s]

[565/1000]
EN: Dubai chocolate craze triggers global pistachio shortage crisis.
MNI: দুবাইদা চোকোলেট লৈরকপদগী গ্লোবেল পিষ্টেচিয়ুগী অৱাৎপা লৈরক্লি।
--------------------------------------------------

Translating MNI:  57%|█████████████          | 566/1000 [05:07<03:27,  2.10it/s]

[566/1000]
EN: Indian Hotels Company signs new Taj property in Lucknow.
MNI: ইন্দিয়ান হোটেল কম্পেনীনা লখনৌদা অনৌবা তাজ প্রোপর্তী খুৎয়েক পীনখ্রে।
--------------------------------------------------

Translating MNI:  57%|█████████████          | 567/1000 [05:07<03:22,  2.14it/s]

[567/1000]
EN: Oberoi Group announces luxury resort opening in Ranthambhore.
MNI: ওবরোই গ্রুপনা রান্থাম্বোরদা লাক্সরি রিসোর্ত হাংদোকপগী লাউথোকখ্রে।
--------------------------------------------------

Translating MNI:  57%|█████████████          | 568/1000 [05:08<03:20,  2.15it/s]

[568/1000]
EN: Lemon Tree Hotels expands northeast presence with Guwahati property.
MNI: লিমোন ত্রি হোটেলশিংনা গুৱাহাতিগী প্রোপর্তীগা লোয়ননা অৱাং নোংপোক্তা লৈরি।
--------------------------------------------------

Translating MNI:  57%|█████████████          | 569/1000 [05:08<03:21,  2.14it/s]

[569/1000]
EN: Marriott International to open 50th property in India by 2026.
MNI: ২০২৬ ফাওবদা ভারত্তা মেরিয়োৎ ইন্তর্নেস্নেলনা ৫০শুবা প্রোপর্তী হাংদোক্কনি।
--------------------------------------------------

Translating MNI:  57%|█████████████          | 570/1000 [05:08<03:22,  2.13it/s]

[570/1000]
EN: Radisson Hotel Group targets 200 hotels across India by 2027.
MNI: রেদিসন হোতেল গ্রুপনা ২০২৭ ফাওবদা ভারত শিনবা থুংনা হোতেল ২০০ পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  57%|█████████████▏         | 571/1000 [05:09<03:27,  2.06it/s]

[571/1000]
EN: OYO announces international expansion into Vietnam and Indonesia.
MNI: ও.আই.ও.না ভিয়েতনাম অমসুং ইন্দোনেসিয়াদা ইন্টরনেস্নেল এক্সপেন্সনগী লাওথোকখি।
--------------------------------------------------

Translating MNI:  57%|█████████████▏         | 572/1000 [05:10<03:39,  1.95it/s]

[572/1000]
EN: MakeMyTrip partners with IHCL for exclusive holiday packages.
MNI: এক্সক্লুসিভ ভেলিদে পেকেজশিংগীদমক মাইত্রিপ অসি আই.ঐচ.সি.এল.গা পার্তনর ওইহল্লু।
--------------------------------------------------

Translating MNI:  57%|█████████████▏         | 573/1000 [05:10<03:20,  2.13it/s]

[573/1000]
EN: Maha Kumbh Mela creates one million jobs for local families.
MNI: মহা কুম্ভ মেলানা লোকেল ইমুংশিংগীদমক থবক লাখ অমা শেমগৎলি।
--------------------------------------------------

Translating MNI:  57%|█████████████▏         | 574/1000 [05:10<03:14,  2.19it/s]

[574/1000]
EN: Boat services at Kumbh earn families collective 30 crore rupees.
MNI: কুম্ভকী বোট সর্বিসশিংনা ইমুং মনুংশিংবু অপুনবা ওইনা লুপা কোতি ৩০ ফংহল্লি।
--------------------------------------------------

Translating MNI:  57%|█████████████▏         | 575/1000 [05:11<03:13,  2.19it/s]

[575/1000]
EN: The Guardian describes Prayagraj Kumbh as pop-up megacity.
MNI: গার্দিয়াননা প্রয়াগরাজ কুম্ভবু পোপ-অপ মেগাসিতি হায়না শন্দোক্না তাক্লি।
--------------------------------------------------

Translating MNI:  58%|█████████████▏         | 576/1000 [05:11<03:13,  2.19it/s]

[576/1000]
EN: Maharashtra Economic Council reports Kumbh employment generation.
MNI: মহারাষ্ট্র ইকোনোমিক কাউন্সিলনা কুম্ভ ইমপ্লোয়মেন্ট জেনেরেসনগী রিপোর্ত পীরি।
--------------------------------------------------

Translating MNI:  58%|█████████████▎         | 577/1000 [05:12<03:17,  2.14it/s]

[577/1000]
EN: FIFA Club World Cup 2025 brings global visitors to host cities.
MNI: ফিফা ক্লব ৱার্ল্দ কপ ২০২৫না হোস্ত সিতিশিংদা গ্লোবেল ভিজিতরশিং পুরক্লি।
--------------------------------------------------

Translating MNI:  58%|█████████████▎         | 578/1000 [05:12<03:27,  2.04it/s]

[578/1000]
EN: Wimbledon 2025 witnesses global unity through international tennis.
MNI: ৱিম্বলদোন ২০২৫না ইন্টরনেস্নেল তেনিসকী খুত্থাংদা মালেমগী অপুনবগী খুদম ওইরি।
--------------------------------------------------

Translating MNI:  58%|█████████████▎         | 579/1000 [05:13<03:21,  2.09it/s]

[579/1000]
EN: Sikh pilgrims receive Pakistani visas after Operation Sindoor.
MNI: সিখ তীর্থগ্রামশিংনা ওপরেসন সিন্দুরগী মতুংদা পাকিস্থানগী ভিজা ফংগনি।
--------------------------------------------------

Translating MNI:  58%|█████████████▎         | 580/1000 [05:13<03:17,  2.13it/s]

[580/1000]
EN: Harjindarpal Singh secures passport and Pakistan visa for pilgrimage.
MNI: হর্জিন্দরপল সিংহনা লাইচৎকীদমক পাসপোর্ত অমসুং পাকিস্থান ভিজা ফংখি।
--------------------------------------------------

Translating MNI:  58%|█████████████▎         | 581/1000 [05:14<03:07,  2.23it/s]

[581/1000]
EN: First Sikh Jathas travel to Pakistan post visa ban reversal.
MNI: ভিসা বেন্দ রিভর্স তৌরবা মতুংদা শিখ জথশিংনা অহানবা ওইনা পাকিস্থান চৎখি।
--------------------------------------------------

Translating MNI:  58%|█████████████▍         | 582/1000 [05:14<03:11,  2.18it/s]

[582/1000]
EN: FIDE names World Chess Cup trophy after Viswanathan Anand.
MNI: ফিদেনা ৱার্ল্দ চেস কপ ত্রোফি অসি বিশ্বনাথন অনন্দগী মমীংদা কৌখ্রে।
--------------------------------------------------

Translating MNI:  58%|█████████████▍         | 583/1000 [05:15<03:09,  2.20it/s]

[583/1000]
EN: Panjim hosts FIDE World Chess Cup with Anand trophy.
MNI: পঞ্জীমনা এনান্দ ত্রোফিগা লোয়ননা ফিদে ৱার্ল্দ চেস কপ হোস্ত তৌরি।
--------------------------------------------------

Translating MNI:  58%|█████████████▍         | 584/1000 [05:15<02:59,  2.31it/s]

[584/1000]
EN: Krishna Janmashtami procession turns tragic in Ramanthapur.
MNI: রামন্তপুরদা কৃষ্ণ জনমাষ্টমী প্রোসেসন অসি অৱাবা থোকহল্লে।
--------------------------------------------------

Translating MNI:  58%|█████████████▍         | 585/1000 [05:15<02:55,  2.37it/s]

[585/1000]
EN: Ten-foot chariot touches live wire killing five devotees.
MNI: ফুট তরাগী রথ অমনা লাইভ ৱায়র খুৎশিন্দুনা ভক্ত মঙা শিহনখি।
--------------------------------------------------

Translating MNI:  59%|█████████████▍         | 586/1000 [05:16<02:56,  2.35it/s]

[586/1000]
EN: Hyderabad celebrates Ganesh festival with large screen displays.
MNI: হায়দ্রবাদনা গণেশ কুম্মৈ অসি অচৌবা স্ক্রিন দিসপ্লেশিংগা লোয়ননা পাংথোকই।
--------------------------------------------------

Translating MNI:  59%|█████████████▌         | 587/1000 [05:16<03:18,  2.09it/s]

[587/1000]
EN: Begum Bazaar jam-packed for night long festival celebrations.
MNI: নুমিৎ শাংনা পাংথোক্কদবা কুম্মৈ পাংথোক্নবগীদমক বেগম বাজারদা জাম মরাং কায়না থম্মী।
--------------------------------------------------

Translating MNI:  59%|█████████████▌         | 588/1000 [05:17<03:21,  2.05it/s]

[588/1000]
EN: Muslim leader Sadeq Siraj organizes eye camp for community.
MNI: মুস্লিম লুচিংবা সাদিক সিরাজনা কম্যুনিতিগীদমক মীৎয়েং কেম্প অমা শানখ্রে।
--------------------------------------------------

Translating MNI:  59%|█████████████▌         | 589/1000 [05:17<03:21,  2.04it/s]

[589/1000]
EN: Hyderabad pandals adopt traditional themes for Ganesh Chaturthi.
MNI: হায়দ্রবাদকী পান্দলশিংনা গণেশ চতুর্থীগী ত্রেদিস্নেল থীমশিং এদোপ্ট তৌরি।
--------------------------------------------------

Translating MNI:  59%|█████████████▌         | 590/1000 [05:18<03:14,  2.10it/s]

[590/1000]
EN: Shuja Ifteqari requests Chief Minister Revanth Reddy for arrangements.
MNI: শুজা ইফতেকারিনা মুখ্য মন্ত্রী রবন্ত রেদ্দীদা থৌরাং তৌনবা হায়জরি।
--------------------------------------------------

Translating MNI:  59%|█████████████▌         | 591/1000 [05:18<02:59,  2.27it/s]

[591/1000]
EN: SOCIAL Hyderabad hosts She's a Phataka Diwali celebration bash.
MNI: সোসিএল হায়দ্রবাদনা মহাক্না ফটকা দীৱালী থৌরম পাংথোক্কনি ।
--------------------------------------------------

Translating MNI:  59%|█████████████▌         | 592/1000 [05:19<02:59,  2.27it/s]

[592/1000]
EN: Hyderabad soaked in festival fervour with rain showers.
MNI: হায়দ্রবাদতা ঈচাউগী ঈচাউগা লোয়ননা কুম্মৈগী ঈচাউ লাকখি।
--------------------------------------------------

Translating MNI:  59%|█████████████▋         | 593/1000 [05:19<03:00,  2.26it/s]

[593/1000]
EN: Dasara trains diverted to manage two lakh passenger footfall.
MNI: পেসেঞ্জর লাখ অনিগী ফুটফোল মেনেজ তৌনবা দাসারা ত্রেনশিং দিভর্ট তৌখি।
--------------------------------------------------

Translating MNI:  59%|█████████████▋         | 594/1000 [05:20<02:58,  2.27it/s]

[594/1000]
EN: New passenger routes planned for Dasara and Diwali travel.
MNI: দাসারা অমসুং দীৱালীগী খোংচৎকীদমক অনৌবা পেসেঞ্জর রুৎশিং প্লান তৌরি।
--------------------------------------------------

Translating MNI:  60%|█████████████▋         | 595/1000 [05:20<02:55,  2.30it/s]

[595/1000]
EN: Hyderabad kiosks offer Ganesh idols across every street.
MNI: হায়দ্রবাদকী কিওস্কশিংদা লম্বী খুদিংমক্তা গণেশগী মীতমশিং থম্মী।
--------------------------------------------------

Translating MNI:  60%|█████████████▋         | 596/1000 [05:20<03:04,  2.19it/s]

[596/1000]
EN: Indian Navy monitors every Chinese vessel in Indian Ocean.
MNI: ইন্দিয়ান নেভীনা ভারত মহাসাগরদা লৈরিবা চাইনাগী লান্মী খুদিংমক মোনিটর তৌরি।
--------------------------------------------------

Translating MNI:  60%|█████████████▋         | 597/1000 [05:21<03:19,  2.02it/s]

[597/1000]
EN: Vice Admiral Sanjay Vatsayan confirms continuous maritime surveillance.
MNI: ভাইস এদমিরেল সঞ্জয় ভটসায়ন্না লেপ্তনা মেরিতাইম সর্ভিলেন্স তৌরি হায়না কনফার্ম তৌখ্রে।
--------------------------------------------------

Translating MNI:  60%|█████████████▊         | 598/1000 [05:21<03:14,  2.07it/s]

[598/1000]
EN: Goa tourism department announces calendar of winter festivals.
MNI: গোৱা তুরিজম দিপার্তমেন্তনা ৱিনতর ফেস্তিবেলশিংগী কেলেন্দর লাউথোকখ্রে।
--------------------------------------------------

Translating MNI:  60%|█████████████▊         | 599/1000 [05:22<03:09,  2.11it/s]

[599/1000]
EN: Jaipur Literature Festival attracts 50,000 book lovers from abroad.
MNI: জয়পুর লিটরেচর ফেস্তিবেলনা মপাল লৈবাক্কী লাইরিক পাম্বৈ ৫০,০০০ থাগৎলি।
--------------------------------------------------

Translating MNI:  60%|█████████████▊         | 600/1000 [05:22<03:07,  2.13it/s]

[600/1000]
EN: Rann Utsav begins in Kutch with tent city bookings full.
MNI: রন উৎসব অসি কচ্ছদা মপুং ফানা টেন্ট সিতি বুকিং তৌদুনা হৌই।
--------------------------------------------------

Translating MNI:  60%|█████████████▊         | 601/1000 [05:23<03:09,  2.11it/s]

[601/1000]
EN: Hornbill Festival showcases Naga heritage in Kisama heritage village.
MNI: হোর্নবিল ফেস্তিবেলনা কিসামা হেরিতেজ ভিলেজদা নাগা হেরিতেজ উৎলি।
--------------------------------------------------

Translating MNI:  60%|█████████████▊         | 602/1000 [05:23<03:24,  1.95it/s]

[602/1000]
EN: Ganga Aarti at Varanasi draws record international tourist attendance.
MNI: বরানসীদা পাংথোকপা গঙ্গা আর্তিনা রেকোর্দ ওইবা ইন্তর্নেস্নেল তুরিস্ত এটেন্দেন্স লৈরে।
--------------------------------------------------

Translating MNI:  60%|█████████████▊         | 603/1000 [05:24<03:22,  1.96it/s]

[603/1000]
EN: Pahalgam terror attack kills twenty-six tourists including foreigners.
MNI: পহালগম তেরোর এটেকতা মপাল লৈবাক্কী মীওইশিং য়াওনা তুরিস্ত তরানিপাল শিখি।
--------------------------------------------------

Translating MNI:  60%|█████████████▉         | 604/1000 [05:25<03:32,  1.87it/s]

[604/1000]
EN: Terrorists attack Baisaran meadows killing twenty-six civilian tourists.
MNI: তেরোরিস্তশিংনা বাইসরান মৈদা হামদোক্তুনা সিভিলিয়ান তুরিস্ত ২৬ শিহনখি।
--------------------------------------------------

Translating MNI:  60%|█████████████▉         | 605/1000 [05:25<03:31,  1.87it/s]

[605/1000]
EN: Two foreign tourists among twenty-six dead in Pahalgam attack.
MNI: পহালগমগী থৌদোক্তা শিখিবা মীওই ২৬ অদুগী মনুংদা মপাল লৈবাক্কী তুরিস্ত অনি লৈখি।
--------------------------------------------------

Translating MNI:  61%|█████████████▉         | 606/1000 [05:26<03:58,  1.65it/s]

[606/1000]
EN: Operation Sindoor launched following deadly Pahalgam tourist attack.
MNI: খুদোংথীনিঙাই ওইরবা পহালগম তুরিস্ত এটেককী মতুংদা ওপরেসন সিন্দুর হৌদোকখি।
--------------------------------------------------

Translating MNI:  61%|█████████████▉         | 607/1000 [05:27<04:22,  1.50it/s]

[607/1000]
EN: Saudi Arabia minister Adel Al-Jubeir arrives in Delhi post Operation Sindoor.
MNI: সাউদী অরাবিয়াগী মন্ত্রী অদেল অল-জুবীর ওপরেসন সিন্দুরগী মতুংদা দিল্লীদা থুংলখ্রে।
--------------------------------------------------

Translating MNI:  61%|█████████████▉         | 608/1000 [05:27<04:02,  1.62it/s]

[608/1000]
EN: Iranian Foreign Minister Araghchi visits New Delhi amid tensions.
MNI: ইরানগী ফোরেন মিনিস্তর অরাঘি অসি টেনসনগী মরক্তা নই দিল্লীদা চৎখ্রে।
--------------------------------------------------

Translating MNI:  61%|██████████████         | 609/1000 [05:28<03:45,  1.74it/s]

[609/1000]
EN: Delhi Red Fort blast leaves fourteen dead and several injured.
MNI: দিল্লি রেদ ফোর্ৎ ব্লেজনা শিবা ১৪ অমসুং অশোক-অপন কয়া থোকহল্লে।
--------------------------------------------------

Translating MNI:  61%|██████████████         | 610/1000 [05:28<03:46,  1.72it/s]

[610/1000]
EN: High intensity explosion outside Red Fort kills fourteen people.
MNI: রেদ ফোর্ৎকী মপান্দা অৱাংবা থাক্তা থোকখিবা এক্সপ্লোজননা মীওই তরানিপাল শিহনখি।
--------------------------------------------------

Translating MNI:  61%|██████████████         | 611/1000 [05:29<03:45,  1.73it/s]

[611/1000]
EN: Supreme Court upholds Christian Army officer Samuel Kamalesan dismissal.
MNI: সুপ্রিম কোর্তনা খৃস্তিয়ন আর্মি ওফিসর সেম্যুয়েল কমলেসনবু থাদোকপদা অয়াবা পীখ্রে।
--------------------------------------------------

Translating MNI:  61%|██████████████         | 612/1000 [05:29<03:34,  1.81it/s]

[612/1000]
EN: Army officer refuses temple pooja entry leading to dismissal.
MNI: আর্মি ওফিসর অমনা টেম্পল পুজা এন্ত্রি তৌবদা য়াদে অমসুং মসিনা দিসমিসেল ওইহল্লি।
--------------------------------------------------

Translating MNI:  61%|██████████████         | 613/1000 [05:30<03:33,  1.81it/s]

[613/1000]
EN: Chief Justice Surya Kant terms refusal grossest kind of indiscipline.
MNI: চিফ জস্তিস সুর্য কান্তনা রিফুসেল অসি খ্বাইদগী অরুবা মখলগী ইন্দিসিপ্লিন হায়না খংনখি।
--------------------------------------------------

Translating MNI:  61%|██████████████         | 614/1000 [05:30<03:06,  2.07it/s]

[614/1000]
EN: Saif Ali Khan undergoes surgery after knife attack at residence.
MNI: Saif Ali Khan undergoes surgery after a knife attack at his residence.
--------------------------------------------------

Translating MNI:  62%|██████████████▏        | 615/1000 [05:31<03:04,  2.09it/s]

[615/1000]
EN: Intruder attacks Bollywood actor Saif Ali Khan in Mumbai.
MNI: মুম্বাইদা বলীৱুদ এক্তর সাইফ আলী খানবু ইন্ত্রোদর অমনা এটেক তৌখ্রে।
--------------------------------------------------

Translating MNI:  62%|██████████████▏        | 616/1000 [05:31<03:06,  2.06it/s]

[616/1000]
EN: Mumbai police identify accused in Saif Ali Khan attack case.
MNI: মুম্বাই পুলিসনা সাইফ আলি খানগী থৌদোক্তা চেরোল লৌরিবা মীওই অদু মশক খংদোকখি।
--------------------------------------------------

Translating MNI:  62%|██████████████▏        | 617/1000 [05:32<03:17,  1.94it/s]

[617/1000]
EN: Actor discharged five days after hospitalization following attack.
MNI: থৌদোক অদুগী মতুংদা হোস্পিটালদা থম্বদগী নুমিৎ মঙাগী মতুংদা এক্তর অদু দিসচার্জ তৌখি।
--------------------------------------------------

Translating MNI:  62%|██████████████▏        | 618/1000 [05:32<03:10,  2.01it/s]

[618/1000]
EN: Tihar jail probe reveals racket charging for free inmate meetings.
MNI: তিহার জেল প্রোবেসনা ফ্রি ইনমেৎ মীফমগীদমক রেকেৎ চার্জ লৌবগী খুদম উৎখি।
--------------------------------------------------

Translating MNI:  62%|██████████████▏        | 619/1000 [05:33<03:09,  2.01it/s]

[619/1000]
EN: Undercover officials exposed illegal mulakat charges at Tihar.
MNI: অন্দরকভর ওফিসিয়েলশিংনা তিহারদা আইন্না য়াদবা মুলাতকী চার্জশিং ফোংদোকখি।
--------------------------------------------------

Translating MNI:  62%|██████████████▎        | 620/1000 [05:33<03:04,  2.06it/s]

[620/1000]
EN: Tihar transfers twenty-five data entry operators after tout investigation.
MNI: থিদোক্লবা মতুংদা তিহারনা দেতা এন্ত্রি ওপরেতর ২৫ ত্রান্সফর তৌখি।
--------------------------------------------------

Translating MNI:  62%|██████████████▎        | 621/1000 [05:34<02:59,  2.11it/s]

[621/1000]
EN: Biometric authentication introduced at Tihar Jail for security.
MNI: সেক্যুরিতীগীদমক তিহার জেলদা বাইওমেত্রিক ওথেন্তিকেসন হৌদোকখ্রে।
--------------------------------------------------

Translating MNI:  62%|██████████████▎        | 622/1000 [05:34<03:03,  2.06it/s]

[622/1000]
EN: Supreme Court declines virtual appearance exemption for chief secretaries.
MNI: সুপ্রিম কোর্তনা চীফ সেক্রেতরীশিংগীদমক ভর্চুএল এপ্পরেন্স ইস্পেন্সন য়াখিদে।
--------------------------------------------------

Translating MNI:  62%|██████████████▎        | 623/1000 [05:35<03:23,  1.85it/s]

[623/1000]
EN: States sleeping over stray dog sterilization orders says Supreme Court.
MNI: সুপ্রিম কোর্তনা হায়খি মদুদি ষ্টেটশীংনা লম্বী থোংবা মচাশীং ষ্টেরিলাইজেসন তৌনবা ওর্দর পীবনা মরম ওইদুনা তুমদুনা লৈরি ।
--------------------------------------------------

Translating MNI:  62%|██████████████▎        | 624/1000 [05:35<03:23,  1.85it/s]

[624/1000]
EN: Passenger forced to write letter after Delhi airport assault.
MNI: দিল্লী এয়রপোর্ততা চত্থখিবা থৌদোক অদুগী মতুংদা পেসেঞ্জর অমনা লেটর ইবা তাই।
--------------------------------------------------

Translating MNI:  62%|██████████████▍        | 625/1000 [05:36<03:02,  2.05it/s]

[625/1000]
EN: Passenger claims pressure to avoid police complaint filing.
MNI: পেসেঞ্জরনা পুলিসকী কমপ্লেন্ত ফাইল তৌদনবা প্রেসর তৌনবা হায়খি।
--------------------------------------------------

Translating MNI:  63%|██████████████▍        | 626/1000 [05:36<03:07,  2.00it/s]

[626/1000]
EN: US forces seize oil tanker off Venezuela for narco-terrorism.
MNI: নার্কো-তেরোরিজমগীদমক য়ুএস ফোর্সশিংনা ভেনেজুয়েলাদগী থাউগী টেঙ্কর লৌখি।
--------------------------------------------------

Translating MNI:  63%|██████████████▍        | 627/1000 [05:37<03:11,  1.95it/s]

[627/1000]
EN: US Coast Guard apprehends tanker with Department of Defense backing.
MNI: দিপার্তমেন্ত ওফ দিফেন্সনা বেক তৌদুনা য়ু.এস. কোস্ত গার্দনা টেঙ্কর লৌরে।
--------------------------------------------------

Translating MNI:  63%|██████████████▍        | 628/1000 [05:37<03:14,  1.91it/s]

[628/1000]
EN: Supreme Court denies relief to mosque seeking loudspeaker permission.
MNI: সুপ্রিম কোর্তনা লাউদস্পিকরগী অয়াবা লৌরকপা মসজিদ অদুদা রিলিফ পীবা য়াদে।
--------------------------------------------------

Translating MNI:  63%|██████████████▍        | 629/1000 [05:38<03:13,  1.92it/s]

[629/1000]
EN: Nagpur bench rules no religion mandates prayers with amplifiers.
MNI: নাগপুর বেঞ্চনা হায়রি মদুদি ধর্ম লৈতে অমসুং এম্প্লিফায়রগা লোয়ননা লাইশোন চত্থবা মথৌ তাদে।
--------------------------------------------------

Translating MNI:  63%|██████████████▍        | 630/1000 [05:38<03:04,  2.01it/s]

[630/1000]
EN: Cruise Saudi brand operations commence with Red Sea licences.
MNI: ক্রুজ সাউদী ব্রান্দ ওপরেসনশিং রেদ সি লাইসেন্সশিংদগী হৌরি।
--------------------------------------------------

Translating MNI:  63%|██████████████▌        | 631/1000 [05:39<02:59,  2.06it/s]

[631/1000]
EN: Marina services added to Saudi marine tourism portfolio.
MNI: সৌদি মেরিন তুরিজম পোর্তফোলিওদা মেরিনা সর্বিসশিং হাপচিল্লে।
--------------------------------------------------

Translating MNI:  63%|██████████████▌        | 632/1000 [05:39<02:59,  2.05it/s]

[632/1000]
EN: Recreational marine activities licensed by Saudi Red Sea Authority.
MNI: সাউদী রেদ সি ওথোরিতীনা লাইসেন্স পীবা রিক্রীএসনেল মেরিন এক্তিবিতীশিং
--------------------------------------------------

Translating MNI:  63%|██████████████▌        | 633/1000 [05:40<03:02,  2.01it/s]

[633/1000]
EN: Saudi Arabia enforces qualified crews for marine tourism operations.
MNI: সাউদী অরাবিয়ানা মেরিন তুরিজম ওপরেসনশিংগীদমক ক্বালিফাই তৌরবা ক্র্যুশিং চৎনহল্লি।
--------------------------------------------------

Translating MNI:  63%|██████████████▌        | 634/1000 [05:40<02:58,  2.06it/s]

[634/1000]
EN: Red Sea unregulated maritime activity concerns addressed by licences.
MNI: রেদ সিগী অনরেগুলেত মেরিতাইম এক্তিবিতীগী মতাংদা লাইসেন্সশিংনা খংহল্লি।
--------------------------------------------------

Translating MNI:  64%|██████████████▌        | 635/1000 [05:41<02:48,  2.17it/s]

[635/1000]
EN: Indian cruise tourism gets boost with ten new terminals.
MNI: অনৌবা তর্মিনেল তরাগা লোয়ননা ইন্দিয়ান ক্রুজ তুরিজমদা ইনোৎ পীরি।
--------------------------------------------------

Translating MNI:  64%|██████████████▋        | 636/1000 [05:41<02:38,  2.30it/s]

[636/1000]
EN: Disney Destiny becomes marquee cruise debut of 2025.
MNI: দিজনী দেস্তিনি অসি ইং ২০২৫গী মার্কি ক্রুইজ দিবেৎ ওইরে ।
--------------------------------------------------

Translating MNI:  64%|██████████████▋        | 637/1000 [05:41<02:44,  2.21it/s]

[637/1000]
EN: Norwegian Aqua adds fleet capacity to Norwegian Cruise Line.
MNI: নোর্বেজিয়ান এক্বানা নোর্বেজিয়ান ক্রুজ লাইনদা ফ্লিৎ কেপাসিতি হাপচিল্লে।
--------------------------------------------------

Translating MNI:  64%|██████████████▋        | 638/1000 [05:42<02:45,  2.19it/s]

[638/1000]
EN: Royal Caribbean Star of the Seas enters service in 2025.
MNI: রোয়েল কেরিবিয়ন স্তার ওফ দি সিজ অসি ইং ২০২৫দা সর্বিসতা চংগনি।
--------------------------------------------------

Translating MNI:  64%|██████████████▋        | 639/1000 [05:42<02:44,  2.19it/s]

[639/1000]
EN: Cordelia Cruises announces Lakshadweep itineraries from Kochi.
MNI: কোচিদগী কোর্দেলিয়া ক্রুইজনা লক্ষদ্বীপকী লম্বীশিং লাউথোকখ্রে।
--------------------------------------------------

Translating MNI:  64%|██████████████▋        | 640/1000 [05:43<02:46,  2.16it/s]

[640/1000]
EN: Water metro connectivity boosts tourism in Kochi backwaters.
MNI: ৱাতর মেত্রো কনেক্তিবিতীনা কোচি বেকৱাতরশিংদা তুরিজম হেনগৎহল্লি।
--------------------------------------------------

Translating MNI:  64%|██████████████▋        | 641/1000 [05:43<02:43,  2.20it/s]

[641/1000]
EN: Mumbai cruise terminal handles record 100,000 passengers this year.
MNI: মুম্বাই ক্রুজ তর্মিনেলনা চহি অসিদা পেসেঞ্জর লাখ ১০০গী রেকোর্দ হেন্দল তৌরি।
--------------------------------------------------

Translating MNI:  64%|██████████████▊        | 642/1000 [05:44<02:45,  2.16it/s]

[642/1000]
EN: Ganga Vilas luxury cruise completes successful Brahmaputra season.
MNI: গঙ্গা ভিলাস লাক্সরি ক্রুজনা মায়পাক্লবা ব্রহ্মপুত্র সিজন লোইশিনখ্রে।
--------------------------------------------------

Translating MNI:  64%|██████████████▊        | 643/1000 [05:44<02:46,  2.15it/s]

[643/1000]
EN: Kerala houseboat registrations cross one thousand operational vessels.
MNI: কেরলাগী হাউসবোৎ রেজিস্ত্রেসনশিংনা ওপরেস্নেল ভেসেল লিশিং অমা কোকই।
--------------------------------------------------

Translating MNI:  64%|██████████████▊        | 644/1000 [05:45<02:42,  2.18it/s]

[644/1000]
EN: Andaman and Nicobar receive approval for international cruise tourism.
MNI: আন্দামান অমসুং নিকোবরনা ইন্তর্নেস্নেল ক্রুজ তুরিজমগীদমক অয়াবা ফংলে।
--------------------------------------------------

Translating MNI:  64%|██████████████▊        | 645/1000 [05:45<02:41,  2.19it/s]

[645/1000]
EN: Airbnb relaunches experiences feature for bookings and services.
MNI: এয়ারবিএনবিনা বুকিং অমসুং সর্বিসশিংগীদমক এক্সপিরিএন্স ফিচর অমুক হন্না হৌদোক্লে।
--------------------------------------------------

Translating MNI:  65%|██████████████▊        | 646/1000 [05:46<02:58,  1.99it/s]

[646/1000]
EN: Brian Chesky announces Airbnb services complementing home rentals.
MNI: ব্রায়ান চেস্কিনা হোম রেন্তেলশিং মপুং ফাহন্নবগীদমক এআরবিএনবি সর্বিসশিং লাওথোকখ্রে।
--------------------------------------------------

Translating MNI:  65%|██████████████▉        | 647/1000 [05:46<03:03,  1.93it/s]

[647/1000]
EN: Olympic speed skater Arianna Fontana leads Airbnb training rides.
MNI: ওলিম্পিক স্পিদ স্কেতর অরিয়ানা ফোন্থানা এআরবিএনবি ত্রেনিং রাইদশিং লুচিংই।
--------------------------------------------------

Translating MNI:  65%|██████████████▉        | 648/1000 [05:47<02:58,  1.97it/s]

[648/1000]
EN: Airbnb offers Alpine hikes with athlete guides in Italy.
MNI: এআরবিএনবিনা ইতলীদা এথলেৎ গাইদশীংগা লোয়ননা অলপাইন হাইকিং পাংথোকই।
--------------------------------------------------

Translating MNI:  65%|██████████████▉        | 649/1000 [05:47<02:55,  2.00it/s]

[649/1000]
EN: K-pop band SEVENTEEN curates music sessions for Airbnb.
MNI: কে-পোপ ব্যান্ড সপ্তেননা এয়রবিএনবিগীদমক ম্যুজিক সেসনশিং ক্যুরেৎ তৌরি।
--------------------------------------------------

Translating MNI:  65%|██████████████▉        | 650/1000 [05:48<03:05,  1.89it/s]

[650/1000]
EN: Chance the Rapper partners with Airbnb for exclusive experiences.
MNI: এক্স্ক্লুসিভ এক্সপিরিএন্সশিংগীদমক রেপর অসি এয়রবিএনবিগা পার্তনর ওইনবা খুদোংচাবা পীরি।
--------------------------------------------------

Translating MNI:  65%|██████████████▉        | 651/1000 [05:49<03:18,  1.75it/s]

[651/1000]
EN: Economic uncertainty shifts traveller behaviour toward price sensitivity.
MNI: ইকোনোমিক অনিংশীং অসিনা প্রাইস সেন্সিতিভিতিগী মায়কৈদা ত্রাভেলরগী লমচৎ-শাজৎ হোংহল্লি।
--------------------------------------------------

Translating MNI:  65%|██████████████▉        | 652/1000 [05:49<03:03,  1.89it/s]

[652/1000]
EN: Tourists choose off-the-beaten-path destinations influenced by social media.
MNI: তুরিস্তশিংনা সোসিএল মিদিয়াগী ইথীলদগী কান্নবা ফংদবা গন্তব্যশিং খনৈ।
--------------------------------------------------

Translating MNI:  65%|███████████████        | 653/1000 [05:49<02:56,  1.97it/s]

[653/1000]
EN: Travelers turn to AI-powered tools for trip planning.
MNI: ত্রাভেলরশিংনা ত্রিপ প্লানিংগীদমক এ আই-পৱার তৌরবা খুৎলাইশিং শিজিন্নৈ।
--------------------------------------------------

Translating MNI:  65%|███████████████        | 654/1000 [05:50<03:00,  1.91it/s]

[654/1000]
EN: Sustainable tourism gains traction among mindful travellers.
MNI: সস্তেনেবল তুরিজমনা মীৎয়েং চংবা ত্রেস্নেলশিংগী মরক্তা ত্রেক্সন ফংহল্লি।
--------------------------------------------------

Translating MNI:  66%|███████████████        | 655/1000 [05:50<02:55,  1.96it/s]

[655/1000]
EN: Responsible travel interest grows among conscious tourists.
MNI: রিস্পোন্সিবল ত্রিভেল ইন্তরেস্ত অসি ৱাখল তাবা তুরিস্তশিংগী মরক্তা হেনগৎলক্লি।
--------------------------------------------------

Translating MNI:  66%|███████████████        | 656/1000 [05:51<02:51,  2.01it/s]

[656/1000]
EN: Less-crowded destinations attract visitors avoiding overtourism.
MNI: মী য়াম্না লৈতবা গন্তব্যশিংনা ভিজিটরশিংবু ওভরতুরিজমদগী লাপ্না লৈহল্লি।
--------------------------------------------------

Translating MNI:  66%|███████████████        | 657/1000 [05:52<02:56,  1.94it/s]

[657/1000]
EN: Business travel spending reaches 1.57 trillion dollars in 2025.
MNI: ২০২৫দা ব্যুজিনেস ত্রেভেল স্পেন্দিং অসি দোল্লর ত্রিলিয়ন ১.৫৭ য়ৌরক্কনি।
--------------------------------------------------

Translating MNI:  66%|███████████████▏       | 658/1000 [05:52<02:58,  1.92it/s]

[658/1000]
EN: Bleisure travel surge drives business trip extensions for leisure.
MNI: ব্লেসিয়র ত্রাভেল সর্জনা লেজরিগীদমক ব্যুজিনেস ত্রিপ এক্সতেন্সনশিং পায়খৎলি।
--------------------------------------------------

Translating MNI:  66%|███████████████▏       | 659/1000 [05:53<03:06,  1.83it/s]

[659/1000]
EN: Luxury travel shifts toward immersive experience based vacations.
MNI: লাক্সরি ত্রেভেলনা ইম্মর্সিভ এক্সপিরিএন্সতা য়ুম্ফম ওইবা ভেকেসনগী মায়কৈদা অহোংবা পুরক্লি।
--------------------------------------------------

Translating MNI:  66%|███████████████▏       | 660/1000 [05:53<03:05,  1.83it/s]

[660/1000]
EN: Travvy Awards recognize top industry suppliers in November.
MNI: ত্রাভি এৱার্দশিংনা নবেম্বর থাদা ইন্দস্ত্রীগী মকোক থোংবা সপ্লাইয়রশিংবু শকখংলগনি।
--------------------------------------------------

Translating MNI:  66%|███████████████▏       | 661/1000 [05:54<02:55,  1.93it/s]

[661/1000]
EN: TravelPulse announces 40 Under 40 honorees for second year.
MNI: ত্রাভেলপলসনা অনিশুবা চহিগী ওইনা ইং ৪০গী মখাদা ফংলবা মীওই ৪০বু লাউথোকখ্রে।
--------------------------------------------------

Translating MNI:  66%|███████████████▏       | 662/1000 [05:54<02:49,  1.99it/s]

[662/1000]
EN: Travel Executive of the Year awarded at Travvy gala.
MNI: ত্রাভি গেলাদা ত্রাভেল ইকজেক্যুতিব ওফ দি ইয়ারগী এৱার্দ পীখ্রে।
--------------------------------------------------

Translating MNI:  66%|███████████████▏       | 663/1000 [05:54<02:34,  2.18it/s]

[663/1000]
EN: New members inducted into Travel Hall of Fame 2025.
MNI: অনৌবা মেম্বরশিং ত্রাভেল হোল ওফ ফেম ২০২৫দা য়াউখ্রে।
--------------------------------------------------

Translating MNI:  66%|███████████████▎       | 664/1000 [05:55<02:31,  2.22it/s]

[664/1000]
EN: Young professionals recognized for innovation and leadership.
MNI: নহা ওইরিবা প্রোফেসনেলশিংবু ইনোভেসন অমসুং লিদরশিপকীদমক শকখংলগনি।
--------------------------------------------------

Translating MNI:  66%|███████████████▎       | 665/1000 [05:55<02:40,  2.09it/s]

[665/1000]
EN: FIFA World Cup 2025 travel bookings exceed host city expectations.
MNI: ফিফা ৱার্ল্দ কপ ২০২৫গী ত্রেভেল বুকিংশিং অসি হোস্ত সিতিগী ওইনদি হেন্না ৱাংই।
--------------------------------------------------

Translating MNI:  67%|███████████████▎       | 666/1000 [05:56<02:34,  2.16it/s]

[666/1000]
EN: Solo female travel bookings increase forty percent year on year.
MNI: সোলো নুপীগী ওইবা ত্রেভেল বুকিংশিং চহিগী মতুং চহিদা চাদা মরি হেনগৎলক্লে।
--------------------------------------------------

Translating MNI:  67%|███████████████▎       | 667/1000 [05:56<02:34,  2.15it/s]

[667/1000]
EN: Wellness tourism emerges as fastest growing travel segment globally.
MNI: ৱেলনেস তুরিজম অসি মালেমগী ওইনা খ্বাইদগী য়াংনা চাউখৎলক্লিবা ত্রেভেল সেগমেন্ত অমা ওইরে।
--------------------------------------------------

Translating MNI:  67%|███████████████▎       | 668/1000 [05:57<02:36,  2.12it/s]

[668/1000]
EN: Indian millennials prefer experiential travel over shopping vacations.
MNI: ভারতকী মিলিনিয়েলশিংনা শোপ্পিং ভেকেসনগী মথক্তা এক্সপিরিএন্সিএল ত্রেভেল হেন্না পাম্মী।
--------------------------------------------------

Translating MNI:  67%|███████████████▍       | 669/1000 [05:57<02:36,  2.11it/s]

[669/1000]
EN: Workation packages gain popularity among remote corporate employees.
MNI: ৱার্কেশন পেকেজশিং অসি রিমোট কোর্পোরেৎ ইমপ্লোয়িশীংগী মরক্তা মীয়াম্না পাম্নরকই।
--------------------------------------------------

Translating MNI:  67%|███████████████▍       | 670/1000 [05:58<02:36,  2.11it/s]

[670/1000]
EN: Culinary tourism drives foodies to regional Indian destinations.
MNI: কুলিনরী তুরিজমনা ফুদীশিংবু রিজনেল ইন্দিয়াগী দিস্তিনেসনশিংদা থুংহল্লি।
--------------------------------------------------

Translating MNI:  67%|███████████████▍       | 671/1000 [05:58<02:27,  2.23it/s]

[671/1000]
EN: Night tourism initiatives launched by Maharashtra and Karnataka.
MNI: মহারাষ্ট্র অমসুং কর্নাতকানা হৌদোকখিবা নাইৎ তুরিজম ইনিসিয়েতিবশিং
--------------------------------------------------

Translating MNI:  67%|███████████████▍       | 672/1000 [05:59<02:23,  2.29it/s]

[672/1000]
EN: Astro tourism gains ground with dark sky parks in Ladakh.
MNI: এস্ত্রো তুরিজমনা লদাখতা দার্ক স্কাই পার্কশিংগা লোয়ননা লম কনবা ঙম্লে।
--------------------------------------------------

Translating MNI:  67%|███████████████▍       | 673/1000 [05:59<02:25,  2.25it/s]

[673/1000]
EN: Film induced tourism boosts Kashmir valley hotel occupancy.
MNI: ফিল্ম ইন্দুস তৌরবা তুরিজমনা কাশ্মীর ভেল্লী হোতেলগী থবক হেনগৎহল্লি।
--------------------------------------------------

Translating MNI:  67%|███████████████▌       | 674/1000 [06:00<02:29,  2.18it/s]

[674/1000]
EN: Wedding tourism contributes five billion dollars to Indian economy.
MNI: লুহোংবগী তুরিজমনা ভারতকী ইকোনোমীদা দোল্লর বিলিয়ন মঙা কন্ত্রিব্যুস তৌরি।
--------------------------------------------------

Translating MNI:  68%|███████████████▌       | 675/1000 [06:00<02:21,  2.30it/s]

[675/1000]
EN: India promotes MICE tourism for meetings and exhibitions.
MNI: মীফমশিং অমসুং একজিবিসনশিংগীদমক ভারতনা মাইস তুরিজম প্রমোত তৌই।
--------------------------------------------------

Translating MNI:  68%|███████████████▌       | 676/1000 [06:00<02:23,  2.25it/s]

[676/1000]
EN: West Bengal develops MICE tourism segments under Mamata Banerjee.
MNI: ৱেস্ত বেঙ্গলনা মমতা বেনর্জীগী মখাদা মাইস তুরিজম সেগমেন্তশিং দিবেলপ তৌরি।
--------------------------------------------------

Translating MNI:  68%|███████████████▌       | 677/1000 [06:01<02:19,  2.32it/s]

[677/1000]
EN: India positions itself as medical value travel destination.
MNI: ভারতনা মশামকপু মেদিকেল ভেল্যু ত্রেভেল দেস্তিনেসন অমা ওইনা লৈরি।
--------------------------------------------------

Translating MNI:  68%|███████████████▌       | 678/1000 [06:01<02:15,  2.38it/s]

[678/1000]
EN: Wellness tourism positions India as holistic healing leader.
MNI: ৱেলনেস তুরিজমনা ভারতপু হোলিস্তিক হিলিং লিদর অমা ওইনা থম্লি।
--------------------------------------------------

Translating MNI:  68%|███████████████▌       | 679/1000 [06:02<02:20,  2.28it/s]

[679/1000]
EN: Concert tourism attracts international visitors to Indian music festivals.
MNI: কনসর্ৎ তুরিজমনা ভারতকী ম্যুজিক ফেস্তিবেলশিংদা ইন্তর্নেস্নেল ভিজিটরশিং থাগৎলি।
--------------------------------------------------

Translating MNI:  68%|███████████████▋       | 680/1000 [06:02<02:17,  2.32it/s]

[680/1000]
EN: Gajendra Shekhawat highlights India's concert tourism potential.
MNI: গজেন্দ্র শেখবৎনা ভারতকী কনসর্ৎ তুরিজম পোতেন্সিয়েল অদু ফোংদোকখি।
--------------------------------------------------

Translating MNI:  68%|███████████████▋       | 681/1000 [06:03<02:24,  2.20it/s]

[681/1000]
EN: India promotes integrated rehabilitation pathways for medical tourists.
MNI: ভারতনা মেদিকেল তুরিস্তশিংগীদমক ইন্তিগ্রেতেদ রিহেবিলিতেসনগী লম্বীশিং প্রমোত তৌরি।
--------------------------------------------------

Translating MNI:  68%|███████████████▋       | 682/1000 [06:03<02:19,  2.28it/s]

[682/1000]
EN: Business travel makes significant comeback post pandemic.
MNI: ব্যুজিনেস ত্রেভেলনা লাইচৎকী মতুংদা য়াম্না চাউনা লাকখি।
--------------------------------------------------

Translating MNI:  68%|███████████████▋       | 683/1000 [06:03<02:22,  2.23it/s]

[683/1000]
EN: Companies increase trip volumes and expand travel budgets.
MNI: কম্পেনীশিংনা ত্রিপ ভোল্যুম হেনগৎহল্লি অমসুং ত্রিপ বজেৎ হেঙ্গৎহল্লি।
--------------------------------------------------

Translating MNI:  68%|███████████████▋       | 684/1000 [06:04<02:27,  2.14it/s]

[684/1000]
EN: In-person collaboration demand drives business travel recovery.
MNI: ইন-পর্সন কোলাবোরেসনগী দিমান্দনা ব্যুজিনেস ত্রেভেল রিকভরি পুরকই।
--------------------------------------------------

Translating MNI:  68%|███████████████▊       | 685/1000 [06:04<02:30,  2.09it/s]

[685/1000]
EN: Hyderabad International Convention Centre hosts global pharmaceutical summit.
MNI: হায়দ্রবাদ ইন্তর্নেস্নেল কনভেন্সন সেন্তরনা গ্লোবেল ফার্মাসুতিকেল সমিৎ হোস্ত তৌরি।
--------------------------------------------------

Translating MNI:  69%|███████████████▊       | 686/1000 [06:05<02:20,  2.24it/s]

[686/1000]
EN: Bharat Mandapam witnesses record MICE bookings for fiscal year.
MNI: ভারত মন্দাপমনা শেনবা চহিগী মাইস বুকিং রেকোর্দ ওইরে ।
--------------------------------------------------

Translating MNI:  69%|███████████████▊       | 687/1000 [06:05<02:10,  2.40it/s]

[687/1000]
EN: Medical tourism arrivals cross pre-Covid levels with six lakh visitors.
MNI: মেদিকেল তুরিজম লাকপা মীওই লাখ তরুক্না কোবিদকী মমাংগী থাক্তা লাকখি।
--------------------------------------------------

Translating MNI:  69%|███████████████▊       | 688/1000 [06:06<02:20,  2.22it/s]

[688/1000]
EN: AYUSH wellness centres attract foreign tourists for traditional treatments.
MNI: আয়ুশ ৱেলনেস সেন্তরশিংনা ত্রেদিস্নেল ত্রিৎমেন্তশিংগীদমক মপাল লৈবাক্কী তুরিস্তশিংবু থাগৎলি।
--------------------------------------------------

Translating MNI:  69%|███████████████▊       | 689/1000 [06:06<02:28,  2.09it/s]

[689/1000]
EN: Delhi NCR hotels report seventy percent occupancy from corporate travellers.
MNI: দিল্লী এনসিআর হোতেলশিংনা করপোরেৎ ত্রেভেলরশিংদগী চাদা তরেৎ কোকপা রিপোর্ত তৌরি।
--------------------------------------------------

Translating MNI:  69%|███████████████▊       | 690/1000 [06:07<02:27,  2.10it/s]

[690/1000]
EN: Maha Kumbh infrastructure delivers long-term tourism economic benefits.
MNI: মহা কুম্ভ ইনফ্রাস্ত্রকচরনা অশাংবা মতমগী তুরিজম ইকোনোমিক কান্নবশিং ফংহল্লি।
--------------------------------------------------

Translating MNI:  69%|███████████████▉       | 691/1000 [06:07<02:25,  2.12it/s]

[691/1000]
EN: Venice entry fee revenues fund city upkeep and travel management.
MNI: ভেনিস এন্ত্রি ফি রেভেন্যুসনা সিটি অপকিপ অমসুং ত্রাভেল মেনেজমেন্ত ফন্দ তৌই ।
--------------------------------------------------

Translating MNI:  69%|███████████████▉       | 692/1000 [06:08<02:29,  2.06it/s]

[692/1000]
EN: Critics question Venice day-tripper fee effectiveness for crowd control.
MNI: ভিদ কন্ত্রোলগীদমক ভেনিস দে-ত্রাইপর ফি ইফেক্টিভ ওইব্রা হায়না ক্রিতিকশিংনা ৱাহং চংই।
--------------------------------------------------

Translating MNI:  69%|███████████████▉       | 693/1000 [06:08<02:36,  1.97it/s]

[693/1000]
EN: Bulgaria joins Eurozone as twenty-first member on January 1 2026.
MNI: জেনুৱারী ১, ২০২৬দা বুলগেরিয়ানা য়ুরোজোনগী মপুং-মরৈ অনিশুবা মেম্বর ওইনা য়াউখি।
--------------------------------------------------

Translating MNI:  69%|███████████████▉       | 694/1000 [06:09<02:27,  2.08it/s]

[694/1000]
EN: Both Lev and Euro accepted in Bulgaria during January transition.
MNI: জানুৱারী ত্রাঞ্জিসন মনুংদা বুলগেরিয়াদা লেভ অমসুং য়ুরো অনিমক য়াখি।
--------------------------------------------------

Translating MNI:  70%|███████████████▉       | 695/1000 [06:09<02:42,  1.88it/s]

[695/1000]
EN: Lufthansa announces daily Frankfurt-Bengaluru flights starting March 2026.
MNI: লুফথান্সানা ২০২৬গী মার্চদগী হৌদুনা ফ্রেঙ্কফোর্তবেঙ্গালুরুগী নুমিৎ খুদিংগী ওইবা ফ্লাইটশিং লাওথোকখ্রে।
--------------------------------------------------

Translating MNI:  70%|████████████████       | 696/1000 [06:10<02:31,  2.00it/s]

[696/1000]
EN: Alliance Air introduces direct flights from Delhi to Darbhanga.
MNI: এলাইন্স এয়রনা দিল্লীদগী দারভঙ্গা ফাওবগী দাইরেক্ত ফ্লাইটশিং হৌদোক্লে।
--------------------------------------------------

Translating MNI:  70%|████████████████       | 697/1000 [06:10<02:30,  2.01it/s]

[697/1000]
EN: Emirates deploys A380 on Ahmedabad-Dubai route for winter season.
MNI: ইমরাইতেসনা অহেমদবাদ-দুবাই রুৎতা অথেংবা মতমগীদমক এ৩৮০ শীজিন্নরি।
--------------------------------------------------

Translating MNI:  70%|████████████████       | 698/1000 [06:11<02:20,  2.16it/s]

[698/1000]
EN: fly91 commences operations from Goa to Hyderabad and Pune.
MNI: ফ্লাই ৯১না গোৱাদগী হায়দ্রবাদ অমসুং পুনে ফাওবা ওপরেসন হৌদোক্লে ।
--------------------------------------------------

Translating MNI:  70%|████████████████       | 699/1000 [06:11<02:28,  2.03it/s]

[699/1000]
EN: British Airways resumes London-Chennai service after four-year hiatus.
MNI: ব্রিতিশ এয়রৱেজনা চহি মরিগী হায়াতুগী মতুংদা লন্দন-চেন্নাই সর্বিস অমুক হন্না হৌদোক্লে।
--------------------------------------------------

Translating MNI:  70%|████████████████       | 700/1000 [06:12<02:35,  1.93it/s]

[700/1000]
EN: Go First employees protest outside NCLT over unpaid salaries.
MNI: গো ফার্ষ্ট ইমপ্লোয়িশীংনা এনসিএলতিগী মপান্দা শেল পীদ্রিবশিংগী মরমদা বিক্ষোভ তৌরি।
--------------------------------------------------

Translating MNI:  70%|████████████████       | 701/1000 [06:12<02:44,  1.82it/s]

[701/1000]
EN: Saudi carrier Flynas plans direct Riyadh-Lucknow operations by April.
MNI: সাউদী কেরিয়র ফ্লাইনাসনা এপ্রিল ফাউবগী মনুংদা রিয়াদ-লখনৌদা হকথেংননা থবক পায়খৎনবা পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  70%|████████████████▏      | 702/1000 [06:13<02:46,  1.79it/s]

[702/1000]
EN: Flybig announces daily flights from Guwahati to Imphal and Agartala.
MNI: ফ্লাইবিগনা গুৱাহাতিদগী ইম্ফাল অমসুং অগরতলাদা নোংমগী ওইবা ফ্লাইটশিং লাওথোকখ্রে।
--------------------------------------------------

Translating MNI:  70%|████████████████▏      | 703/1000 [06:14<02:51,  1.73it/s]

[703/1000]
EN: Kolkata airport wins cleanest airport award in 15-25 million category.
MNI: কলকাতা এয়রপোর্তনা কেতেগোরি মিলিয়ন ১৫-২৫দা খ্বাইদগী লু-নান্না লৈবা এয়রপোর্তকী এৱার্দ লৌখি।
--------------------------------------------------

Translating MNI:  70%|████████████████▏      | 704/1000 [06:14<02:46,  1.77it/s]

[704/1000]
EN: Patna airport's new terminal to handle forty lakh passengers annually.
MNI: পতনা এয়রপোর্তকী অনৌবা তর্মিনেল অসিনা চহি খুদিংগী পেসেঞ্জর লাখ চল্লিশিবু হেন্দল তৌগনি।
--------------------------------------------------

Translating MNI:  70%|████████████████▏      | 705/1000 [06:15<02:43,  1.80it/s]

[705/1000]
EN: Fog forces thirty-two flight diversions at Chandigarh airport.
MNI: চান্দিগর এয়রপোর্ততা ফ্লাইত দিভর্সিন ৩২ থোরকপগী থৌরাং তৌরি।
--------------------------------------------------

Translating MNI:  71%|████████████████▏      | 706/1000 [06:15<02:31,  1.94it/s]

[706/1000]
EN: Ethiopian Airlines considers Mumbai and Delhi as new African hub.
MNI: ইথিওপিয়ান এয়রলাইন্সনা মুম্বাই অমসুং দিল্লীবু অনৌবা অফ্রিকাগী হব ওইনা লৌরি।
--------------------------------------------------

Translating MNI:  71%|████████████████▎      | 707/1000 [06:16<02:30,  1.95it/s]

[707/1000]
EN: IndiGo passenger dies aboard Delhi-Bengaluru flight mid-air.
MNI: ইন্দিগোগী পেসেঞ্জর অমা দিল্লী-বেঙ্গালুরু ফ্লাইতকী ময়াই থংবা এয়রদা লৈখিদ্রে।
--------------------------------------------------

Translating MNI:  71%|████████████████▎      | 708/1000 [06:16<02:39,  1.83it/s]

[708/1000]
EN: VietJet Air announces daily Hanoi-Ahmedabad service from December.
MNI: ভিয়েতজেৎ এয়রনা দিসেম্বরদগী হান্নোই-অহমেদাবাদকী নুমিৎ খুদিংগী সর্বিস লাওথোক্কনি।
--------------------------------------------------

Translating MNI:  71%|████████████████▎      | 709/1000 [06:17<02:31,  1.91it/s]

[709/1000]
EN: Odisha government approves ten new tourism circuits for development.
MNI: ওরিশা সরকারনা দিবেলপমেন্তকীদমক অনৌবা তুরিজম সর্কিৎ তরা অয়াবা পীরে।
--------------------------------------------------

Translating MNI:  71%|████████████████▎      | 710/1000 [06:17<02:26,  1.99it/s]

[710/1000]
EN: Madhya Pradesh unveils film tourism policy with 25 percent subsidy.
MNI: মধ্য প্রদেশনা চাদা ২৫গী সবসিদিগা লোয়ননা ফিল্ম তুরিজম পোলিসী মায়খুম হাংদোকখ্রে।
--------------------------------------------------

Translating MNI:  71%|████████████████▎      | 711/1000 [06:18<02:18,  2.09it/s]

[711/1000]
EN: Gujarat grants industry status to homestays and farmstays.
MNI: গুজরাতনা হোমস্তাই অমসুং ফার্মস্তাইদা ইন্দস্ত্রীগী থাক পীরি।
--------------------------------------------------

Translating MNI:  71%|████████████████▍      | 712/1000 [06:18<02:15,  2.13it/s]

[712/1000]
EN: Himachal Pradesh caps tourist entry to Manali and Rohtang Pass.
MNI: হিমাচল প্রদেশনা মানালি অমসুং রোহতাং পাসতা তুরিস্ত এন্ত্রি কপ তৌরে।
--------------------------------------------------

Translating MNI:  71%|████████████████▍      | 713/1000 [06:18<02:14,  2.14it/s]

[713/1000]
EN: Kerala launches responsible tourism mission for waste-free destinations.
MNI: কেরলানা অরেম-অপা লৈতবা মফমশিংগীদমক দায়ত্ব লৈবা তুরিজম মিসন হৌদোক্লে।
--------------------------------------------------

Translating MNI:  71%|████████████████▍      | 714/1000 [06:19<02:12,  2.15it/s]

[714/1000]
EN: Australia removes minimum bank balance requirement for Indian student visas.
MNI: ভারতকী ছাত্র ভিজাগীদমক অষ্ট্রেলিয়ানা মিনিমম বেঙ্ক বেলেন্সকী মথৌ তাবদু লৌথোকখ্রে।
--------------------------------------------------

Translating MNI:  72%|████████████████▍      | 715/1000 [06:19<02:17,  2.08it/s]

[715/1000]
EN: UK introduces Electronic Travel Authorisation for Indian passport holders.
MNI: য়ু কেনা ইলেক্ত্রোনিক ত্রেভেল ওথোরাইজেসন ভারতকী পাসপোর্ত হোল্দরশিংগীদমক হৌদোকখ্রে।
--------------------------------------------------

Translating MNI:  72%|████████████████▍      | 716/1000 [06:20<02:33,  1.84it/s]

[716/1000]
EN: Saudi Arabia extends stopover visa validity from four to ninety-six hours.
MNI: সাউদী অরাবিয়ানা স্তোপওবর ভিজাগী ভেলিদিতি পুং ৪ দগী পুং ৯৬ ফাউবা শাংদোকখ্রে।
--------------------------------------------------

Translating MNI:  72%|████████████████▍      | 717/1000 [06:21<02:29,  1.90it/s]

[717/1000]
EN: Malaysia grants thirty-day visa-free entry to Indian nationals till December.
MNI: মালয়েসিয়ানা ভারতকী নাগরিকশিংদা দিসেম্বর ফাউবা নুমিৎ তরাগী ভিজা ফ্রি এন্ত্রি পীরি।
--------------------------------------------------

Translating MNI:  72%|████████████████▌      | 718/1000 [06:21<02:28,  1.90it/s]

[718/1000]
EN: Thailand extends visa-free stay for Indians from thirty to sixty days.
MNI: থাইলেন্দনা ভারত মচাশিংগী ভিজা ফ্রি লৈবগী মতম নুমিৎ তরাতগী তরুক ফাওবা শাংদোক্লে।
--------------------------------------------------

Translating MNI:  72%|████████████████▌      | 719/1000 [06:22<02:33,  1.83it/s]

[719/1000]
EN: Indonesia proposes visa-free entry for Indian tourists to boost Bali arrivals.
MNI: ইন্দোনেসিয়ানা ভারতকী তুরিস্তশিংগীদমক বালিদা লাকপা হেনগৎহন্নবা ভিজা য়াউদবা এন্ত্রি প্রপোজ তৌরি।
--------------------------------------------------

Translating MNI:  72%|████████████████▌      | 720/1000 [06:22<02:33,  1.82it/s]

[720/1000]
EN: European Parliament approves ETIAS system launch for mid-2026.
MNI: ২০২৬গী মরক্তা ইতিয়াস সিস্তেম হৌদোকপদা য়ুরোপিয়ান পার্লিয়ামেন্তনা অয়াবা পীরে ।
--------------------------------------------------

Translating MNI:  72%|████████████████▌      | 721/1000 [06:23<02:25,  1.92it/s]

[721/1000]
EN: Sri Lanka cabinet approves visa-free entry for nationals of thirty-five countries.
MNI: শ্রীলঙ্কাগী মন্ত্রীমন্দলনা লৈবাক ৩৫গী নাগরিকশিংগী ভিজা ফ্রি এন্ত্রিদা অয়াবা পীখ্রে।
--------------------------------------------------

Translating MNI:  72%|████████████████▌      | 722/1000 [06:23<02:21,  1.96it/s]

[722/1000]
EN: Waives visa fees for Indian senior citizens above sixty-five years.
MNI: চহি তরানিপাল মঙাগী মথক্তা লৈবা ভারতকী সেনিয়র সিতিজনশিংগীদমক ভিসা ফিশীং লৌথোকই।
--------------------------------------------------

Translating MNI:  72%|████████████████▋      | 723/1000 [06:24<02:15,  2.05it/s]

[723/1000]
EN: Bhutan revises Sustainable Development Fee to one thousand two hundred rupees.
MNI: ভুতাননা সস্তেনেবল দিবেলপমেন্ত ফি অসি লুপা লিশিং অনিদা রিভাইস তৌখ্রে।
--------------------------------------------------

Translating MNI:  72%|████████████████▋      | 724/1000 [06:24<02:12,  2.09it/s]

[724/1000]
EN: Nepal allows Indian tourists to pay in rupees at immigration checkpoints.
MNI: নেপালনা ইমিগ্রেশন চেক পোইন্তশিংদা ভারতকী তুরিস্তশিংদা লুপা ওইনা শেল পীবা য়াহল্লি।
--------------------------------------------------

Translating MNI:  72%|████████████████▋      | 725/1000 [06:25<02:11,  2.10it/s]

[725/1000]
EN: Myanmar junta extends e-visa facility for Indian travellers.
MNI: ম্যানমার জন্তানা ভারতকী ত্রেভেলরশিংগীদমক ই-ভিজাগী খুদোংচাবা হেঙ্গৎহল্লে।
--------------------------------------------------

Translating MNI:  73%|████████████████▋      | 726/1000 [06:25<02:21,  1.94it/s]

[726/1000]
EN: Mauritius scraps PCR test requirement for fully vaccinated Indian visitors.
MNI: মোরিসিয়সনা মপুং ফানা ভেক্সিন কাপ্লবা ভারতকী ভিজিটরশিংগীদমক পি.সি.আর.
--------------------------------------------------

Translating MNI:  73%|████████████████▋      | 727/1000 [06:26<02:13,  2.04it/s]

[727/1000]
EN: Kenya removes visa requirement for all Indian passport holders.
MNI: কেনিয়ানা ভারতকী পাসপোর্ত লৈবা মীওই পুম্নমক্কী ভিসাগী মথৌ তাবদু লৌথোকখ্রে।
--------------------------------------------------

Translating MNI:  73%|████████████████▋      | 728/1000 [06:26<02:01,  2.25it/s]

[728/1000]
EN: Rajasthan government launches mobile app for heritage hotel bookings.
MNI: রাজস্থান সরকারনা হেরিতেজ হোতেল বুকিংগীদমক মোবাইল এপ হৌদোক্লে।
--------------------------------------------------

Translating MNI:  73%|████████████████▊      | 729/1000 [06:26<02:01,  2.23it/s]

[729/1000]
EN: Assam receives fifty-five lakh domestic tourists during 2024-2025.
MNI: ২০২৪-২০২৫গী মনুংদা অসামদা দোমেষ্টিক তুরিস্ত লাখ ৫৫ লাক্কনি।
--------------------------------------------------

Translating MNI:  73%|████████████████▊      | 730/1000 [06:27<01:56,  2.32it/s]

[730/1000]
EN: Hemanta Biswa Sarma credits improved law and order for tourism growth.
MNI: টুরিজমগী গ্রোথকীদমক হেমন্ত বিশ্ব সরমানা আইন অমসুং অরোনবা ফগৎহল্লে ।
--------------------------------------------------

Translating MNI:  73%|████████████████▊      | 731/1000 [06:27<01:55,  2.32it/s]

[731/1000]
EN: Madhya Pradesh records 112.1 million tourist visits in 2024.
MNI: মধ্য প্রদেশনা ইং ২০২৪দা তুরিস্ত মিল্লিয়ন ১১২.১গী ভিজিট রেকোর্দ তৌরি।
--------------------------------------------------

Translating MNI:  73%|████████████████▊      | 732/1000 [06:28<01:53,  2.36it/s]

[732/1000]
EN: Meghalaya welcomes twenty-one lakh visitors crossing pre-pandemic figures.
MNI: মেঘালয়াদা লাইচৎকী মমাংদা লাক্লিবশিং লাখ ২১ লাক্লিবশিং তরাম্না ওক্লি।
--------------------------------------------------

Translating MNI:  73%|████████████████▊      | 733/1000 [06:28<01:58,  2.26it/s]

[733/1000]
EN: Jammu and Kashmir registers two crore tourist footfall in 2025.
MNI: জম্মু অমসুং কশ্মীরনা ইং ২০২৫দা তুরিস্ত ক্রোর অনিগী খোঙচৎ রেজিস্তার তৌরি।
--------------------------------------------------

Translating MNI:  73%|████████████████▉      | 734/1000 [06:29<02:04,  2.13it/s]

[734/1000]
EN: LG Manoj Sinha announces highest ever tourist arrival in Kashmir Valley.
MNI: এল জি মনোজ সিনহানা কাশ্মীর ভেলীদা হৌজিক ফাওবগী খ্বাইদগী ৱাংবা তুরিস্তশিং লাকপগী লাউথোকখ্রে।
--------------------------------------------------

Translating MNI:  74%|████████████████▉      | 735/1000 [06:29<02:00,  2.20it/s]

[735/1000]
EN: Lakshadweep receives eighty-three thousand visitors after PM Modi visit.
MNI: প্রধান মন্ত্রী মোদীগী খোংচৎ মতুংদা লক্ষদ্বীপতা ভিজিটর লিশিং ৮৩ ফংগনি।
--------------------------------------------------

Translating MNI:  74%|████████████████▉      | 736/1000 [06:30<01:58,  2.24it/s]

[736/1000]
EN: Uttarakhand witnesses five crore pilgrim visits to Char Dham shrines.
MNI: উত্তরাখন্দদা চার ধাম লাইশঙশিংদা হুরানবী ক্রোর মঙা চৎলি।
--------------------------------------------------

Translating MNI:  74%|████████████████▉      | 737/1000 [06:30<01:55,  2.28it/s]

[737/1000]
EN: Pushkar fair attracts fifteen lakh tourists including thirty thousand foreigners.
MNI: পুস্কর মেলাদা মপানগী মীওই লিশিং তরা য়াওনা তুরিস্ত লাখ তরা লাকই।
--------------------------------------------------

Translating MNI:  74%|████████████████▉      | 738/1000 [06:30<01:56,  2.25it/s]

[738/1000]
EN: Surajkund Mela records forty-eight percent increase in international participation.
MNI: সুরজকন্দ মেলাদা ইন্তরনেস্নেল পার্তিসিপেসন চাদা ৪৮ হেনগৎলে।
--------------------------------------------------

Translating MNI:  74%|████████████████▉      | 739/1000 [06:31<02:01,  2.15it/s]

[739/1000]
EN: Singapore welcomes 1.2 million Indian visitors becoming top source market.
MNI: সিঙ্গাপুরনা ভারতকী ভিজিটর মিলিয়ন ১.২বু তরাম্না ওক্লি অমসুং মসিনা খ্বাইদগী ফবা সোর্স মার্কেৎ ওইরে ।
--------------------------------------------------

Translating MNI:  74%|█████████████████      | 740/1000 [06:31<01:58,  2.19it/s]

[740/1000]
EN: Dubai hosts record 2.1 million Indian tourists in first half 2025.
MNI: ২০২৫গী অহানবা শরুক্তা দুবাইদা ভারতকী তুরিস্ত মিলিয়ন ২.১গী রেকোর্দ লৈরি।
--------------------------------------------------

Translating MNI:  74%|█████████████████      | 741/1000 [06:32<02:01,  2.14it/s]

[741/1000]
EN: Thailand receives 1.8 million Indian travellers during January-October period.
MNI: থাইলেন্দনা জনুৱারী-ওক্তোবরগী মনুংদা ভারতকী ত্রেভেলর মিলিয়ন ১.৮ ফংগনি।
--------------------------------------------------

Translating MNI:  74%|█████████████████      | 742/1000 [06:32<02:10,  1.97it/s]

[742/1000]
EN: Maldives sees forty percent drop in Indian tourist arrivals amid diplomatic row.
MNI: দিপ্লোমেতিক ওইবা ৱারি-ৱাতাইগী মনুংদা মালদিব্সতা ভারতকী তুরিস্তশিং য়ৌরকপদা চাদা ৪০ হন্থরক্লি।
--------------------------------------------------

Translating MNI:  74%|█████████████████      | 743/1000 [06:33<02:01,  2.11it/s]

[743/1000]
EN: Nepal earns 110 billion rupees from Indian tourists in fiscal year.
MNI: শেনবা চহি অসিদা নেপালনা ভারতকী তুরিস্তশিংদগী লুপা বিলিয়ন ১১০ ফংগনি।
--------------------------------------------------

Translating MNI:  74%|█████████████████      | 744/1000 [06:33<02:01,  2.11it/s]

[744/1000]
EN: Turkey welcomes three lakh Indian tourists targeting five lakh by year-end.
MNI: তর্কিনা চহিগী অরোইবা ফাউবদা ভারতকী তুরিস্ত লাখ মঙা লাকপদা তরাম্না ওক্লি।
--------------------------------------------------

Translating MNI:  74%|█████████████████▏     | 745/1000 [06:34<01:59,  2.13it/s]

[745/1000]
EN: Egypt reports 1.5 lakh Indian arrivals aiming for three lakh target.
MNI: মিসরনা লাখ অহুমগী পান্দমদা ভারতকী মীওই লাখ ১.৫ লাকপগী রিপোর্ত পীরি।
--------------------------------------------------

Translating MNI:  75%|█████████████████▏     | 746/1000 [06:34<02:03,  2.06it/s]

[746/1000]
EN: Azerbaijan attracts two lakh Indian visitors visa-free policy credited.
MNI: আজারবাইজাননা ভিজা য়াউদবা পোলিসীগী ক্রেদিৎ লৌদুনা ভারতকী ভিজিটর লাখ অনি থাগৎলি।
--------------------------------------------------

Translating MNI:  75%|█████████████████▏     | 747/1000 [06:35<02:05,  2.02it/s]

[747/1000]
EN: Georgia registers 1.75 lakh Indian tourist arrivals between January-September.
MNI: জর্জিয়ানা জনুৱারী-সেপ্তেম্বরগী মরক্তা ভারতকী তুরিস্ত লাখ ১.৭৫ লাকখি।
--------------------------------------------------

Translating MNI:  75%|█████████████████▏     | 748/1000 [06:35<02:01,  2.07it/s]

[748/1000]
EN: Kenya targets one lakh Indian tourists with aggressive marketing campaign.
MNI: কেনিয়াগী মার্কেতিং কেম্পেইননা ভারতকী তুরিস্ত লাখ অমা পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  75%|█████████████████▏     | 749/1000 [06:36<01:58,  2.11it/s]

[749/1000]
EN: Udaipur airport gets new terminal building costing five hundred crore rupees.
MNI: উদিপুর এয়রপোর্তনা লুপা ক্রোর মঙা চংগদবা অনৌবা তর্মিনেল বিলদিং ফংলে।
--------------------------------------------------

Translating MNI:  75%|█████████████████▎     | 750/1000 [06:36<02:00,  2.08it/s]

[750/1000]
EN: Rajkot airport renamed after former Prime Minister Morarji Desai.
MNI: রাজকোট এয়রপোর্ত অদু হান্নগী প্রধান মন্ত্রী মোরাজী দেশাইগী মমীংদা নৌনা মমিং থোনখি।
--------------------------------------------------

Translating MNI:  75%|█████████████████▎     | 751/1000 [06:37<02:02,  2.04it/s]

[751/1000]
EN: Noida International Airport to begin flight operations by April 2026.
MNI: নোইদা ইন্তরনেস্নেল এয়রপোর্তনা এপ্রিল ২০২৬ ফাওবদা ফ্লাইট ওপরেসন হৌরগনি।
--------------------------------------------------

Translating MNI:  75%|█████████████████▎     | 752/1000 [06:37<02:09,  1.92it/s]

[752/1000]
EN: Chennai airport opens dedicated lounge for transiting international passengers.
MNI: চেন্নাই এয়রপোর্তনা ইন্টরনেস্নেল পেসেঞ্জরশিং ত্রান্সিৎ তৌনবগীদমক দেদিকেতেদ লোঞ্জ হাংদোক্লে।
--------------------------------------------------

Translating MNI:  75%|█████████████████▎     | 753/1000 [06:38<02:06,  1.95it/s]

[753/1000]
EN: Guwahati-Rohingya railway project completes tunneling work in Mizoram.
MNI: গুৱাহাতি-রোহিংজয়া রেলৱে প্রোজেক্তনা মিজোরামদা তনেলিংগী থবক লোইশিনখ্রে।
--------------------------------------------------

Translating MNI:  75%|█████████████████▎     | 754/1000 [06:38<01:59,  2.06it/s]

[754/1000]
EN: Katra-Delhi Vande Bharat Express reduces travel time by three hours.
MNI: কত্রা-দেলি বন্দে ভারত এক্সপ্রেসনা চৎপগী মতম পুং অহুম হন্থহল্লি।
--------------------------------------------------

Translating MNI:  76%|█████████████████▎     | 755/1000 [06:39<01:59,  2.05it/s]

[755/1000]
EN: Mumbai-Ahmedabad bullet train project completes fifty percent of viaduct work.
MNI: মুম্বাই-অহমেদাবাদ বুলেৎ ত্রেন প্রোজেক্তনা ভায়াদক্তকী থবক চাদা মঙা লোইশিনখ্রে।
--------------------------------------------------

Translating MNI:  76%|█████████████████▍     | 756/1000 [06:39<01:57,  2.07it/s]

[756/1000]
EN: Indian Railways introduces 200 superfast trains for summer rush.
MNI: ইন্দিয়ান রেলৱেজনা অৱাং-নুংথংবা মতমগীদমক সুপরফেস্ত ত্রেন ২০০ হৌদোক্লে।
--------------------------------------------------

Translating MNI:  76%|█████████████████▍     | 757/1000 [06:40<02:00,  2.01it/s]

[757/1000]
EN: Kochi water metro adds four new routes connecting Vypin and Goshree islands.
MNI: কোচি ৱাতর মেত্রোনা ভাইপিন অমসুং গোশ্রী ইথৎশিং শম্নহন্নবা অনৌবা লম্বী মরি হাপচিল্লে।
--------------------------------------------------

Translating MNI:  76%|█████████████████▍     | 758/1000 [06:40<01:56,  2.08it/s]

[758/1000]
EN: Ayodhya's Ram Path revamp completed ahead of Pran Pratishtha anniversary.
MNI: অয়োধ্যার রাম পাথ রিভাইস অসি প্রধান মন্ত্রীগী মপোক কুমওন লাকপদা লোইশিনখ্রে।
--------------------------------------------------

Translating MNI:  76%|█████████████████▍     | 759/1000 [06:41<01:54,  2.10it/s]

[759/1000]
EN: Kedarnath ropeway project gets environmental clearance from ministry.
MNI: কেদরনাথ রোপৱে প্রোজেক্তনা মিনিস্ত্রীদগী এনভাইরোনমেন্ত ক্লিয়ারেন্স ফংগনি।
--------------------------------------------------

Translating MNI:  76%|█████████████████▍     | 760/1000 [06:41<01:52,  2.13it/s]

[760/1000]
EN: Hemkund Sahib helicopter service fares capped at five thousand rupees.
MNI: হেমকুন্দ সাহিব হেলিকোপ্তর সর্বিসকী মমল লুপা লিশিং মঙাদা লেপখ্রে।
--------------------------------------------------

Translating MNI:  76%|█████████████████▌     | 761/1000 [06:42<01:52,  2.13it/s]

[761/1000]
EN: Statue of Unity adds laser show and sound and light attraction.
MNI: ষ্টেচু ওফ য়ুনিতীনা লেজর শোয় অমসুং সাউন্দ অমসুং লাইৎ এত্রেক্সন হাপচিল্লি।
--------------------------------------------------

Translating MNI:  76%|█████████████████▌     | 762/1000 [06:42<01:52,  2.11it/s]

[762/1000]
EN: Khajuraho airport receives international status for charter operations.
MNI: খাজুরাহো এয়রপোর্তনা চার্তর ওপরেসনশিংগীদমক ইন্তর্নেস্নেল স্তেতস ফংগনি।
--------------------------------------------------

Translating MNI:  76%|█████████████████▌     | 763/1000 [06:43<01:56,  2.03it/s]

[763/1000]
EN: Puducherry tourism department renovates French War Memorial promenade.
MNI: পুদুচেরী তুরিজম দিপার্তমেন্তনা ফ্রেন্স ৱার মেমোরিয়েল প্রমোরেদ নৌনা শেমগৎলে।
--------------------------------------------------

Translating MNI:  76%|█████████████████▌     | 764/1000 [06:43<01:53,  2.08it/s]

[764/1000]
EN: Dal Lake restoration project includes de-weeding and island development.
MNI: দাল লেক রিস্টোরেসন প্রোজেক্ততা দি-ৱীদিং অমসুং আইলেন্দ দিবেলপমেন্ত য়াওরি।
--------------------------------------------------

Translating MNI:  76%|█████████████████▌     | 765/1000 [06:44<01:56,  2.01it/s]

[765/1000]
EN: Hampi gets world-class interpretation centre showcasing Vijayanagara heritage.
MNI: বিজয়নাগরগী হেরিতেজ উৎলিবা ৱার্ল্দ ক্লাস ইন্তর্পর্তেসন সেন্তর অমা হাম্পিনা ফংগনি।
--------------------------------------------------

Translating MNI:  77%|█████████████████▌     | 766/1000 [06:44<01:56,  2.01it/s]

[766/1000]
EN: Mahabalipuram shoreline monument gets LED lighting for night viewing.
MNI: মহাবালিপুরম কোস্তরলাইন মোন্যুমেন্তনা নুমিদাং য়েংবগীদমক এলইদি লাইন্ত ফংলগনি।
--------------------------------------------------

Translating MNI:  77%|█████████████████▋     | 767/1000 [06:45<01:55,  2.02it/s]

[767/1000]
EN: Ajanta-Ellora caves introduce audio guides in ten international languages.
MNI: অজন্তা-এল্লোরা গুহাশিংনা ইন্টরনেস্নেল লোল তরাদা ওদিও গাইদশিং পুথোকখি।
--------------------------------------------------

Translating MNI:  77%|█████████████████▋     | 768/1000 [06:45<01:48,  2.14it/s]

[768/1000]
EN: Kaziranga opens additional safari routes for tourists.
MNI: কাজিরঙ্গানা তুরিস্তশিংগীদমক অহেনবা সাফারি রুৎশিং হাংদোক্লে।
--------------------------------------------------

Translating MNI:  77%|█████████████████▋     | 769/1000 [06:45<01:50,  2.08it/s]

[769/1000]
EN: Radisson Blu opens two hundred key property in Amritsar near Golden Temple.
MNI: রেদিসন ব্লুনা গোল্দন তেম্পলগী মনাক নকপা অমৃতসরদা মরুওইবা প্রোপর্তী ২০০ হাংদোকখ্রে।
--------------------------------------------------

Translating MNI:  77%|█████████████████▋     | 770/1000 [06:46<02:08,  1.79it/s]

[770/1000]
EN: IHCL launches Ginger brand hotel in Siliguri for Dooars travellers.
MNI: আই.ঐচ.সি.এল.না দুয়ার্স ত্রাভেলরশিংগীদমক সিলীগুরিদা জিঞ্জর ব্রান্দ হোতেল হৌদোকখ্রে।
--------------------------------------------------

Translating MNI:  77%|█████████████████▋     | 771/1000 [06:47<02:05,  1.83it/s]

[771/1000]
EN: Hyatt Regency debuts in Dehradun with mountain view rooms.
MNI: হায়াত রেজেন্সিনা দেহরাদুনদা মাউন্তেন ভিউ রুমশিংগা লোয়ননা দেব্যু তৌরি।
--------------------------------------------------

Translating MNI:  77%|█████████████████▊     | 772/1000 [06:47<02:09,  1.76it/s]

[772/1000]
EN: Taj Fort Aguada completes fifty years in Goa announces renovation.
MNI: গোৱাদা তাজ ফোর্ট অগুদানা চহি মঙা মপুং ফারকপদা রিনোবেসন তৌরে হায়না লাওথোকখি।
--------------------------------------------------

Translating MNI:  77%|█████████████████▊     | 773/1000 [06:48<02:13,  1.70it/s]

[773/1000]
EN: Novotel Visakhapatnam opens with three sixty degree sea view rooms.
MNI: নোভোতেল বিশাখাপত্তনমনা দিগ্রি ৬০গী সমুদ্র য়েংবা রুম অহুমগা লোয়ননা হাংদোক্লে।
--------------------------------------------------

Translating MNI:  77%|█████████████████▊     | 774/1000 [06:48<02:04,  1.81it/s]

[774/1000]
EN: Roseate House Delhi appoints Kunal Kumar as new general manager.
MNI: রোজেত হাউস দিল্লীনা কুনাল কুমারবু অনৌবা জেনেরেল মেনেজর ওইনা খল্লকখি।
--------------------------------------------------

Translating MNI:  78%|█████████████████▊     | 775/1000 [06:49<02:03,  1.83it/s]

[775/1000]
EN: ITC Hotels launches Mementoes brand with Jaipur property opening.
MNI: আই তি সি হোতেলশিংনা জয়পুর প্রোপর্তী হাংদোকপগা লোয়ননা মেমন্তোস ব্রান্দ হৌদোকখ্রে।
--------------------------------------------------

Translating MNI:  78%|█████████████████▊     | 776/1000 [06:50<02:03,  1.82it/s]

[776/1000]
EN: Marriott Kathmandu opens Indian restaurant specializing in Awadhi cuisine.
MNI: মেরিয়োৎ কাথমান্দুনা অৱাধি রন্ধন-থৌরাংদা অখন্নবা ভারতকী রেস্তোরান্ত হাংদোকখ্রে।
--------------------------------------------------

Translating MNI:  78%|█████████████████▊     | 777/1000 [06:50<02:01,  1.83it/s]

[777/1000]
EN: Sarovar Hotels signs new property in Darjeeling with heritage status.
MNI: সরোবর হোতেলশিংনা দার্জিলিংদা হেরিতেজ স্তেতসকী অনৌবা প্রোপর্তী খুৎয়েক পীনখ্রে।
--------------------------------------------------

Translating MNI:  78%|█████████████████▉     | 778/1000 [06:51<01:56,  1.90it/s]

[778/1000]
EN: The Park Kolkata celebrates seventy-fifth anniversary with heritage walks.
MNI: পার্ক কলকাতানা হেরিতেজ ৱাকশিংগা লোয়ননা ৭৫শুবা মপোক কুমওন পাংথোক্লি।
--------------------------------------------------

Translating MNI:  78%|█████████████████▉     | 779/1000 [06:51<02:02,  1.80it/s]

[779/1000]
EN: Ambassador Ajmera joins Indian Hotel Company board as independent director.
MNI: এম্বেসেদর অজমেরা ইন্দিয়ান হোতেল কম্পেনিগী বোর্দতা ইন্দিপেন্দেন্ত দাইরেক্তর ওইনা শরুক য়াখ্রে।
--------------------------------------------------

Translating MNI:  78%|█████████████████▉     | 780/1000 [06:52<02:02,  1.79it/s]

[780/1000]
EN: Chai Sutta Bar founder Anubhav Dubey opens tourist cafe in Udaipur.
MNI: চাই সত্তা বারগী ফাউন্দর অনুভব দুবেনা উদিপুরদা তুরিস্ত কেফে হাংদোকখ্রে।
--------------------------------------------------

Translating MNI:  78%|█████████████████▉     | 781/1000 [06:52<01:55,  1.90it/s]

[781/1000]
EN: Aman Resorts to launch first Indian property in Alwar district.
MNI: অমান রিসোর্তসনা অলৱার জিলাদা অহানবা ভারতকী প্রোপর্তি হৌদোক্কনি।
--------------------------------------------------

Translating MNI:  78%|█████████████████▉     | 782/1000 [06:53<01:58,  1.85it/s]

[782/1000]
EN: Soneva Fushi Maldives introduces all-inclusive plan for Indian honeymooners.
MNI: সোনেবা ফুশী মালদিবসনা ভারতকী হোনলমুনরশিংগীদমক ওল-ইনক্লুসিভ প্লান হৌদোক্লে।
--------------------------------------------------

Translating MNI:  78%|██████████████████     | 783/1000 [06:53<01:58,  1.83it/s]

[783/1000]
EN: CII tourism committee chairman K.B. Kachru calls for single window clearance.
MNI: সি আই আই তুরিজম কমিতিগী চিয়ারমেন কে বি কচরুনা সিঙ্গল ৱিন্দো ক্লিয়ারেন্স তৌনবা হায়জরি।
--------------------------------------------------

Translating MNI:  78%|██████████████████     | 784/1000 [06:54<01:58,  1.83it/s]

[784/1000]
EN: Ladakh bans motorbike rallies to protect fragile Himalayan ecosystem.
MNI: লদাখনা হিমালায়ান ইকোসিস্তেম ঙাকথোক্নবগীদমক মোতোর বাইক রেলী থিংখ্রে।
--------------------------------------------------

Translating MNI:  78%|██████████████████     | 785/1000 [06:54<01:57,  1.83it/s]

[785/1000]
EN: Meghalaya introduces living root bridge trekking festival in November.
MNI: মেঘালয়না নবেম্বর থাদা লিভিং রুট ব্রিজ ত্রেকিং ফেস্তিবেল হৌদোক্লে।
--------------------------------------------------

Translating MNI:  79%|██████████████████     | 786/1000 [06:55<01:53,  1.89it/s]

[786/1000]
EN: Spiti valley opens for tourists after six-month winter closure.
MNI: স্পিতি ভেলী অসি থা তরুক ৱিন্দর ক্লোজ তৌরবা মতুংদা তুরিস্তশিংগীদমক হাংদোক্লে।
--------------------------------------------------

Translating MNI:  79%|██████████████████     | 787/1000 [06:55<01:49,  1.94it/s]

[787/1000]
EN: Andaman administration permits night camping on Neil Island.
MNI: অন্দমান এদমিনিস্ত্রেসননা নীল আইলেন্দতা নাইৎ কেম্পিং তৌনবা অয়াবা পীরে।
--------------------------------------------------

Translating MNI:  79%|██████████████████     | 788/1000 [06:56<01:53,  1.87it/s]

[788/1000]
EN: Gujarat forest department opens Gir interpretation zone for lion safaris.
MNI: গুজরাত ফোরেস্ত দিপার্তমেন্তনা লাইওন সাফারিশিংগীদমক গির ইন্তর্পর্তেসন জোন হাংদোকখ্রে।
--------------------------------------------------

Translating MNI:  79%|██████████████████▏    | 789/1000 [06:57<01:52,  1.88it/s]

[789/1000]
EN: Jim Corbett tiger reserve reports 1.75 lakh tourists in peak season.
MNI: জিম কোরবেৎ টাইগর রিজর্ভনা পিক সিজনদা তুরিস্ত লাখ ১.৭৫ লাকপা রিপোর্ত তৌরি।
--------------------------------------------------

Translating MNI:  79%|██████████████████▏    | 790/1000 [06:57<01:47,  1.95it/s]

[790/1000]
EN: Periyar sanctuary introduces bamboo rafting in Thekkady lake.
MNI: পেরিয়র সেঙ্কচুওরিনা তেক্কেদী লেকতা বাম্বু রাফটিং হৌদোকখি।
--------------------------------------------------

Translating MNI:  79%|██████████████████▏    | 791/1000 [06:57<01:38,  2.12it/s]

[791/1000]
EN: Sundarbans tourism restricted during tiger breeding season.
MNI: টাইগর ব্রিদিং সিজনগী মনুংদা সুরবানগী তুরিজম অথীংবা থমখ্রে।
--------------------------------------------------

Translating MNI:  79%|██████████████████▏    | 792/1000 [06:58<01:34,  2.19it/s]

[792/1000]
EN: Ranthambore bans private vehicles inside core zone from December.
MNI: রান্তহম্বোরনা দিসেম্বরদগী কোর জোনগী মনুংদা প্রাইভেৎ গারিশিং থিংখ্রে।
--------------------------------------------------

Translating MNI:  79%|██████████████████▏    | 793/1000 [06:58<01:33,  2.22it/s]

[793/1000]
EN: Kerala tourism launches monsoon packages for Ayurveda treatments.
MNI: কেরলা তুরিজমনা আয়ুর্বেদ ত্রিতমেন্তশিংগীদমক মোনসুন পেকেজশিং হৌদোক্লে।
--------------------------------------------------

Translating MNI:  79%|██████████████████▎    | 794/1000 [06:59<01:28,  2.32it/s]

[794/1000]
EN: Kutch Rann Utsav extends tent city duration by forty-five days.
MNI: কচ্ছ রন উৎসৱনা তম্বু শহরগী মতম নুমিৎ ৪৫ শাংদোক্লে।
--------------------------------------------------

Translating MNI:  80%|██████████████████▎    | 795/1000 [06:59<01:37,  2.11it/s]

[795/1000]
EN: Telangana government promotes Yadadri temple as integrated pilgrimage hub.
MNI: তেলঙ্গনা সরকারনা যাদদ্রী লাইশংবু ইন্তিগ্রেতেদ পিলগ্রিমেজ হব অমা ওইনা প্রোমোৎ তৌরি।
--------------------------------------------------

Translating MNI:  80%|██████████████████▎    | 796/1000 [07:00<01:34,  2.15it/s]

[796/1000]
EN: Mysore Dasara procession draws eight lakh visitors on Vijayadashami day.
MNI: বিজয় দশমী নুমিত্তা মাইসোর দসারা প্রোসেসননা ভিজিটর লাখ নিপাল থাগৎলি।
--------------------------------------------------

Translating MNI:  80%|██████████████████▎    | 797/1000 [07:00<01:32,  2.20it/s]

[797/1000]
EN: Konark Sun Temple to get 3D projection mapping experience.
MNI: কোনার্ক সুন তেম্পলনা 3D প্রোজেক্সন মেপ্পিং এক্সপিরিএন্স ফংলগনি ।
--------------------------------------------------

Translating MNI:  80%|██████████████████▎    | 798/1000 [07:01<01:30,  2.23it/s]

[798/1000]
EN: Elephanta Caves introduce Portuguese audio guide for visitors.
MNI: ইলেফান্তা গুহাশিংনা ভিজিটরশিংগীদমক পোর্তুগিজগী ওদিও গাইদ হৌদোক্লি ।
--------------------------------------------------

Translating MNI:  80%|██████████████████▍    | 799/1000 [07:01<01:31,  2.21it/s]

[799/1000]
EN: Golconda Fort light and sound show revamped in Telugu and English.
MNI: গোলকন্দা ফোর্ট লাইৎ এন্দ সাউন্দ শো অসি তেলুগু অমসুং ইংলিসতা নৌনা শেমদোক্লে।
--------------------------------------------------

Translating MNI:  80%|██████████████████▍    | 800/1000 [07:01<01:31,  2.19it/s]

[800/1000]
EN: Five regional medical hubs to be set up to boost medical tourism in country
MNI: লৈবাক অসিদা মেদিকেল তুরিজম হেনগৎহন্নবা রিজনেল মেদিকেল হব মঙা লিংখৎকনি ।
--------------------------------------------------

Translating MNI:  80%|██████████████████▍    | 801/1000 [07:02<01:28,  2.26it/s]

[801/1000]
EN: Union Budget 2026 announces NIMHANS for north India
MNI: কেন্দ্রগী বজেৎ ২০২৬না অৱাং ভারত্তা নিমহান্স লাওথোকখ্রে
--------------------------------------------------

Translating MNI:  80%|██████████████████▍    | 802/1000 [07:02<01:29,  2.20it/s]

[802/1000]
EN: Centre forms expert panel on healthcare for transgender persons
MNI: ত্রান্সজেন্দর পর্সনশিংগী হেল্থকেয়রগী মতাংদা সেন্তরনা এক্সপার্ত পেনেল অমা শেম্মী ।
--------------------------------------------------

Translating MNI:  80%|██████████████████▍    | 803/1000 [07:03<01:30,  2.18it/s]

[803/1000]
EN: Stem cell therapy cannot be offered as a clinical service for autism
MNI: স্তেম সেল থেরাপী অসি ওটিজমগী ক্লিনিকেল সর্ভিস অমগুম্না পীবা য়ারোই ।
--------------------------------------------------

Translating MNI:  80%|██████████████████▍    | 804/1000 [07:03<01:30,  2.17it/s]

[804/1000]
EN: AI helps doctors spot breast cancer in scans
MNI: এ আইনা দোক্টরশীংবু স্তেষ্ট কেন্সর স্কেন্দা খংদোকপদা মতেং পাংই ।
--------------------------------------------------

Translating MNI:  80%|██████████████████▌    | 805/1000 [07:04<01:41,  1.93it/s]

[805/1000]
EN: Every family today knows someone with cancer and It is no longer a disease that happens to an ageing parent or relative
MNI: ঙসিগী ইমুং খুদিংমক্না কেন্সরগা নাবা মীওই অমা খংই অমসুং মসি অহল ওইরক্লিবা মমা-মপা নত্ত্রগা মরি-মতা অমদা থোকপা লায়না নত্তে ।
--------------------------------------------------

Translating MNI:  81%|██████████████████▌    | 806/1000 [07:04<01:36,  2.01it/s]

[806/1000]
EN: Government imposes import curbs on three pharma ingredients for one year
MNI: সরকারনা ফার্মাগী ইন্ত্রিবিয়ন্ত অহুম চহি অমগী ওইনা ইম্পোর্ত কন্ত্রিব্যুসন চৎনহল্লে ।
--------------------------------------------------

Translating MNI:  81%|██████████████████▌    | 807/1000 [07:05<01:33,  2.07it/s]

[807/1000]
EN: Menstrual health in schools is integral to right to life, says the Supreme Court
MNI: সুপ্রিম কোর্তনা হায়খি মদুদি স্কুলশিংদা থাগী ওইবা হকশেল অসি পুন্সিগী অধিকারগী শরুক অমনি ।
--------------------------------------------------

Translating MNI:  81%|██████████████████▌    | 808/1000 [07:05<01:33,  2.05it/s]

[808/1000]
EN: WHO sees low risk of Nipah virus spreading beyond India
MNI: দবল্যু ঐচ ওনা নিপা ভাইরসনা ভারতকী মপান্দা শন্দোরকপগী রিস্ক হন্থরে হায়না লৌরি ।
--------------------------------------------------

Translating MNI:  81%|██████████████████▌    | 809/1000 [07:06<01:43,  1.84it/s]

[809/1000]
EN: Economic Survey calls for tackling rising digital addiction and screen-related mental health problems
MNI: ইকোনোমিক সর্ভেনা হেনগৎলক্লিবা দিজিতেল এদিক্সন অমসুং স্ক্রিনগা মরি লৈনবা মেন্তেল হেল্থ প্রোব্লেমশিং থেংননবা হায়জরি ।
--------------------------------------------------

Translating MNI:  81%|██████████████████▋    | 810/1000 [07:06<01:36,  1.96it/s]

[810/1000]
EN: 188 million children and adolescents living with obesity worldwide
MNI: মালেম শিনবা থুংনা ওবেসিটিগা নারবা অঙাং অমসুং ইনখৎলক্লিবশীং মিলিয়ন 188 লৈ ।
--------------------------------------------------

Translating MNI:  81%|██████████████████▋    | 811/1000 [07:07<01:33,  2.03it/s]

[811/1000]
EN: 60% of mental disorders found in patients below 35 years
MNI: মেন্টেল দিসওর্দরগী 60%দি চহি 35গী মখাদা লৈবা পেসেন্টশীংদা থেংনৈ ।
--------------------------------------------------

Translating MNI:  81%|██████████████████▋    | 812/1000 [07:07<01:38,  1.90it/s]

[812/1000]
EN: Obesity impacts on brain may depend on how fat is distributed across body
MNI: ওবেসিটিনা ব্রেনদা থোকহনবা ইনফেক্ট অসি হকচাংদা ফেত মতৌ করম্না য়েন্থোকপগে হায়বদুদা মখা পোল্লি ।
--------------------------------------------------

Translating MNI:  81%|██████████████████▋    | 813/1000 [07:08<01:44,  1.80it/s]

[813/1000]
EN: Maharashtra, Karnataka, Tamil Nadu have highest number of vacancies under the NEET-PG 2025-26
MNI: নীৎ-পিজি ২০২৫-২৬গী মখাদা খ্বাইদগী হেন্না ভেকেন্সীগী মশিং অসি মহারাস্ত্রা, কর্নাতকা, তামিল নাদুদা লৈরি।
--------------------------------------------------

Translating MNI:  81%|██████████████████▋    | 814/1000 [07:09<01:49,  1.70it/s]

[814/1000]
EN: Only two Nipah virus disease cases reported in West Bengal since December 2025, says Health Ministry
MNI: হেল্থ মিনিস্ত্রীনা হায়খি মদুদি ইং ২০২৫গী দিসেম্বরদগী হৌদুনা ৱেস্ত বেঙ্গলদা নিপা ভাইরস লায়নাগী কেস অনিখক্তমক থেংনরে ।
--------------------------------------------------

Translating MNI:  82%|██████████████████▋    | 815/1000 [07:09<01:47,  1.73it/s]

[815/1000]
EN: Health impacts due to plastics worldwide may double by 2040
MNI: ২০৪০ ফাওবদা প্লাস্তিকনা মালেমদা থোকহনবা হকশেলগী ওইবা শাফু শরুক অনি হেনগৎহনবা য়াই ।
--------------------------------------------------

Translating MNI:  82%|██████████████████▊    | 816/1000 [07:10<01:39,  1.85it/s]

[816/1000]
EN: China halts sale of Sun Pharma drug used to treat dementia
MNI: দিমেন্সিয়া লায়েংবদা শিজিন্নরিবা সুন ফার্মা দ্রগ য়োনবা চিনা লেপখ্রে ।
--------------------------------------------------

Translating MNI:  82%|██████████████████▊    | 817/1000 [07:10<01:44,  1.74it/s]

[817/1000]
EN: T.N. govt. scheme improves access to diabetes, hypertension care for women as rural residents
MNI: টি.এন. সরকারগী স্কিমনা রুরেল রেসিদেন্ত ওইনা নুপীশিংগীদমক দাইএবেটিজ, হায়পরতেন্সন কেয়রগী এক্সেস ফগৎহল্লি ।
--------------------------------------------------

Translating MNI:  82%|██████████████████▊    | 818/1000 [07:11<02:07,  1.43it/s]

[818/1000]
EN: Karnataka farmers urge Union Government to recommend to WHO to re-classify arecanut from ‘carcinogenic’ to ‘possibly carcinogenic to humans’
MNI: কর্নাতকাগী লৌমীশিংনা য়ুনিয়ন গবর্নমেন্তপু ৱেল্থ ওথোরিতীদা কার্সিনোজেনিক ( কার্সিনোজেনিক ) দগী মীওইবদা কার্সিনোজেনিক ওইবা য়াবা ) দা অমুক হন্না রেকমেন্দ তৌনবা খংহনখ্রে ।
--------------------------------------------------

Translating MNI:  82%|██████████████████▊    | 819/1000 [07:12<02:06,  1.44it/s]

[819/1000]
EN: Study discovers stress-reducing role of natural molecule in body, may help with metabolic disorders
MNI: ষ্টদি অসিনা হকচাংদা নেচরেল মোলেক্যুলগী স্ত্রেস হন্থহনবগী থৌদাং অদু ফোংদোকখি অমসুং মসিনা মেটাবোলিক দিসওর্দরশীংদা মতেং পাংবা য়াই ।
--------------------------------------------------

Translating MNI:  82%|██████████████████▊    | 820/1000 [07:13<01:54,  1.57it/s]

[820/1000]
EN: Keeping your spine healthy with small, everyday changes
MNI: নুমিৎ খুদিংগী পাংথোকপা অপিকপা অহোংবশীংগা লোয়ননা নহাক্কী স্পেইন অদু হকশেল ফনা থম্বা
--------------------------------------------------

Translating MNI:  82%|██████████████████▉    | 821/1000 [07:13<01:41,  1.76it/s]

[821/1000]
EN: What is behind the increasing number of heart attacks in pregnancy?
MNI: মীরোল্লিঙৈদা হার্ট এটেককী মশিং হেনগৎলকপগী মরম করিনো?
--------------------------------------------------

Translating MNI:  82%|██████████████████▉    | 822/1000 [07:13<01:29,  1.99it/s]

[822/1000]
EN: Can India eliminate malaria by 2030?
MNI: ২০৩০ ফাওবদা ভারতনা মেলেরিয়া মুত্থৎপা ঙমগদ্রা?
--------------------------------------------------

Translating MNI:  82%|██████████████████▉    | 823/1000 [07:14<01:38,  1.79it/s]

[823/1000]
EN: Tamil Nadu government seeks IIT-M’s assistance to study ill effects of microplastics on human health
MNI: মাইক্রোপ্লাস্তিকশিংনা মীওইবগী হকশেলদা থোকহনবা মাং-তাক্নিংঙাই ওইবা ইফেক্টশিং নৈননবা তামিল নাদু সরকারনা আইআইতি-এমগী মতেং লৌরি
--------------------------------------------------

Translating MNI:  82%|██████████████████▉    | 824/1000 [07:14<01:31,  1.93it/s]

[824/1000]
EN: Goa seeks to grow as a wellness and medical tourism hub in India
MNI: গোৱানা ভারত্তা ৱেলনেস অমসুং মেদিকেল তুরিজম হব অমা ওইনা চাউখৎনবা পান্দম থম্লি ।
--------------------------------------------------

Translating MNI:  82%|██████████████████▉    | 825/1000 [07:15<01:37,  1.79it/s]

[825/1000]
EN: Borewell found contaminated, pipelines being probed as eight remain in hospital in Madhya Pradesh's Mhow
MNI: মধ্য প্রদেশকী মহৌদা লৈরিবা হোস্পিতালদা নিপাল লৈরিঙৈদা বোরেৱেলনা কন্তাষ্টেন্দেৎ ওইরে অমসুং পাইপলাইনশিং প্রোবেদ তৌরি ।
--------------------------------------------------

Translating MNI:  83%|██████████████████▉    | 826/1000 [07:16<01:38,  1.78it/s]

[826/1000]
EN: Uttar Pradesh youth amputates foot to seek disability quota in admission to medical college
MNI: মেদিকেল কোলেজগী এদমিসনদা দিসএবিলিতী কোতা লৌনবগীদমক উত্তর প্রদেশকী নহারোলশিংনা মখোয়গী মখুৎ কাথোকখি ।
--------------------------------------------------

Translating MNI:  83%|███████████████████    | 827/1000 [07:16<01:42,  1.69it/s]

[827/1000]
EN: Police investigate software engineer’s death in Chennai lodge linked to bug repellent fumes
MNI: পুলিসনা বগ রিপেলেন্ত ফ্যুমগা মরি লৈননা চেন্নাইগী লোজদা সোফটৱায়র ইঞ্জিনীয়র অমা শিখিবগী মতাংদা ইনভেষ্টিগেসন তৌরি ।
--------------------------------------------------

Translating MNI:  83%|███████████████████    | 828/1000 [07:17<01:35,  1.80it/s]

[828/1000]
EN: Regularly engaging in varied physical activities could extend lifespan
MNI: ফিজিকেল এক্তিবিতী কয়া চাং নাইনা পাংথোকপনা পুন্সি মতম শাংদোকপা ঙম্মী ।
--------------------------------------------------

Translating MNI:  83%|███████████████████    | 829/1000 [07:18<01:41,  1.68it/s]

[829/1000]
EN: Study relates ADHD traits in childhood with physical health problems in mid-life
MNI: ষ্টদি অসিনা অঙাং ওইরিঙৈদা লৈবা এদিএইচদিগী মওং-মতৌ অমসুং ময়াই ওইবা পুন্সিদা লৈবা হকশেলগী প্রোব্লেমশীংগা মরি লৈনরি ।
--------------------------------------------------

Translating MNI:  83%|███████████████████    | 830/1000 [07:18<01:32,  1.85it/s]

[830/1000]
EN: U.S. completes withdrawal from World Health Organization
MNI: ৱার্ল্দ হেল্থ ওর্গনাইজেসনদগী য়ু.এস.না লৌথোকপা লোইশিনখ্রে
--------------------------------------------------

Translating MNI:  83%|███████████████████    | 831/1000 [07:18<01:28,  1.90it/s]

[831/1000]
EN: Punjab health scheme offers free hospital care worth ₹10 lakh to every family
MNI: পঞ্জাব হেল্থ স্কিমনা ইমুং খুদিংমক্তা লুপা লাখ ১০গী ফ্রী হোস্পিতাল কেয়র পীরি ।
--------------------------------------------------

Translating MNI:  83%|███████████████████▏   | 832/1000 [07:19<01:29,  1.87it/s]

[832/1000]
EN: Snapchat launches new Family Center safety tools for teens and parents
MNI: ইনখৎলক্লিবশিং অমসুং মমা-মপাশিংগীদমক অনৌবা ফেমিলি সেন্তর সেফতী টুলশিং স্নেপচাটনা হৌদোক্লে ।
--------------------------------------------------

Translating MNI:  83%|███████████████████▏   | 833/1000 [07:20<01:30,  1.84it/s]

[833/1000]
EN: 167 drug samples flagged as ‘not of standard quality’ in December 2025
MNI: দিসেম্বর 2025দা ষ্টেন্দর্দ ক্বালিটি লৈতবা হায়না ফ্লেগ তৌখিবা দ্রগ সেম্পল 167
--------------------------------------------------

Translating MNI:  83%|███████████████████▏   | 834/1000 [07:20<01:28,  1.87it/s]

[834/1000]
EN: Tamil Nadu issues guidelines as chikungunya cases rise in State
MNI: রাজ্য অসিদা চিকুনগুনিয়াগী কেসশিং হেনগৎলকপগা লোয়ননা তামিল নাদুনা গাইদলাইনশিং ইসু তৌরি ।
--------------------------------------------------

Translating MNI:  84%|███████████████████▏   | 835/1000 [07:21<01:30,  1.82it/s]

[835/1000]
EN: Researchers develop tool to simplify nutritional tracking of Indian meals
MNI: রিসর্স তৌরিবশিংনা ভারতকী চানবা চিঞ্জাকশিংগী ন্যুত্রিসনেল ত্রেকিং লায়থোকহন্নবা খুৎলাই শেমগৎলে ।
--------------------------------------------------

Translating MNI:  84%|███████████████████▏   | 836/1000 [07:21<01:27,  1.87it/s]

[836/1000]
EN: Shingles vaccine may also slow down biological ageing in older adults
MNI: শিংলস ভেক্সিননা অহল ওইরবা মীওইশীংদসু বাইওলোজিকেল এজিং হন্থহনবা য়াই ।
--------------------------------------------------

Translating MNI:  84%|███████████████████▎   | 837/1000 [07:22<01:25,  1.90it/s]

[837/1000]
EN: Gates and OpenAI team up for AI health push in African countries
MNI: গেত্স অমসুং ওপন এ আইনা আফ্রিকান লৈবাকশিংদা এ আই হেল্থ পম্পগীদমক পুন্না থবক তৌমিন্নরি ।
--------------------------------------------------

Translating MNI:  84%|███████████████████▎   | 838/1000 [07:22<01:26,  1.88it/s]

[838/1000]
EN: ASHA workers protest in Kolkata for ₹15,000 monthly honorarium
MNI: থাগী ওইনা লুপা ১৫,০০০গী ওনোরেরিয়মগীদমক কলকাতাদা আশা ৱার্করশিংনা বিক্ষোভ তৌরি
--------------------------------------------------

Translating MNI:  84%|███████████████████▎   | 839/1000 [07:23<01:25,  1.89it/s]

[839/1000]
EN: Bloodless heart surgery performed on patient with rare blood group at Kauvery Hospital
MNI: কাবরি হোস্পিতালদা রের ব্লদ গ্রুপ লৈবা পেসেন্তশিংদা ব্লদলেস হার্ট সর্জরি পাংথোকখি ।
--------------------------------------------------

Translating MNI:  84%|███████████████████▎   | 840/1000 [07:23<01:26,  1.85it/s]

[840/1000]
EN: Centre sanctions 50-bed AYUSH hospital for Tenali, says A.P. Minister
MNI: অ.পি. মিনিস্তরনা হায়খি মদুদি টেনালিগীদমক কেন্দ্রনা বেদ ৫০ লৈবা আয়ুশ হোস্পিতাল সেঙ্কসন তৌরে ।
--------------------------------------------------

Translating MNI:  84%|███████████████████▎   | 841/1000 [07:24<01:37,  1.64it/s]

[841/1000]
EN: NIMS Hyderabad opens Stem Cell Centre of Excellence as India battles rising burden of lifestyle diseases
MNI: ভারতনা লাইফস্তাইল লায়নাগী অহেনবা বোর্দ লান্থেংনরকপগা লোয়ননা এনআইএমএস হায়দ্রবাদনা স্তেম সেল সেন্তর ওফ এক্সেলেন্স হাংদোকখ্রে ।
--------------------------------------------------

Translating MNI:  84%|███████████████████▎   | 842/1000 [07:25<01:50,  1.43it/s]

[842/1000]
EN: The Ministry of Health and Family Welfare launched a nationwide campaign to improve early detection of non-communicable diseases in rural India.
MNI: রুরেল ইন্দিয়াদা লায়না-লাংথক য়াদবা লায়নাশিং ঙন্না খংদোকপদা হেন্না ফগৎহন্নবা হেল্থ এন্দ ফেমিলি ৱেলফেয়র মন্ত্রালয়না লৈবাক শীনবা থুংনা কেম্পেইন অমা হৌদোকখ্রে।
--------------------------------------------------

Translating MNI:  84%|███████████████████▍   | 843/1000 [07:25<01:41,  1.54it/s]

[843/1000]
EN: The Government of India announced an increase in funding for public hospitals under the National Health Mission.
MNI: নেস্নেল হেল্থ মিসনগী মখাদা পব্লিক হোস্পিতালশিংগী ফন্দ হেঙ্গৎহনগনি হায়না ভারত সরকারনা লাওথোকখি।
--------------------------------------------------

Translating MNI:  84%|███████████████████▍   | 844/1000 [07:26<01:47,  1.46it/s]

[844/1000]
EN: Indian researchers developed a low-cost diagnostic kit to detect tuberculosis with higher accuracy.
MNI: ভারতকী রিসর্সর্সশিংনা ট্যুবরকুলোসিসবু হেন্না অচুম্বা মওংদা খংদোক্নবগীদমক মমল হন্থবা দাইএগ্নোষ্টিক কিৎ অমা দিবেলপ তৌখি।
--------------------------------------------------

Translating MNI:  84%|███████████████████▍   | 845/1000 [07:27<01:42,  1.51it/s]

[845/1000]
EN: The Indian Council of Medical Research issued updated guidelines for the treatment of dengue fever.
MNI: ইন্দিয়ান কাউন্সিল ওফ মেদিকেল রিসর্সনা দেঙ্গু লাইহৌ লায়েংনবা অপদেৎ তৌরবা গাইদলাইনশিং ইসু তৌখ্রে।
--------------------------------------------------

Translating MNI:  85%|███████████████████▍   | 846/1000 [07:28<01:43,  1.48it/s]

[846/1000]
EN: A new government medical college was inaugurated in Assam to strengthen healthcare education in the northeastern region.
MNI: অৱাং নোংপোক লমদমদা হেল্থকেয়র এজুকেসন মপাঙ্গল কনখৎহন্নবা অসামদা অনৌবা গবর্নমেন্ত মেদিকেল কোলেজ অমা শঙ্গাখ্রে।
--------------------------------------------------

Translating MNI:  85%|███████████████████▍   | 847/1000 [07:28<01:34,  1.62it/s]

[847/1000]
EN: The Union Health Minister reviewed the progress of Ayushman Bharat services across multiple states.
MNI: কেন্দ্রগী হকশেল মন্ত্রীনা রাজ্য কয়াদা আয়ুশ্মান ভারত সর্বিসকী প্রোগ্রেস য়েংশিনখি।
--------------------------------------------------

Translating MNI:  85%|███████████████████▌   | 848/1000 [07:29<01:31,  1.66it/s]

[848/1000]
EN: India reported a decline in maternal mortality rates due to improved institutional delivery services.
MNI: ইনস্তিত্যুসনেল দেলিভরি সর্বিস ফগৎহন্দুনা ভারতনা মমা মোর্তেলিতি রেৎ হন্থরে হায়না রিপোর্ট তৌরি।
--------------------------------------------------

Translating MNI:  85%|███████████████████▌   | 849/1000 [07:29<01:28,  1.70it/s]

[849/1000]
EN: The Drug Controller General of India approved a new vaccine for preventing cervical cancer.
MNI: ভারতকী দ্রগ কন্ত্রোলর জেনরেলনা সর্ভিকেল কেন্সর থীংনবা অনৌবা ভেক্সিন অমা অয়াবা পীখ্রে।
--------------------------------------------------

Translating MNI:  85%|███████████████████▌   | 850/1000 [07:30<01:24,  1.79it/s]

[850/1000]
EN: Several state governments expanded free dialysis services in district hospitals.
MNI: রাজ্য সরকার কয়ানা দিস্ত্রিক্ত হোস্পিতালশিংদা ফ্রী দাইএলাইসিস সর্বিসশিং পাকথোক চাউথোকহল্লে।
--------------------------------------------------

Translating MNI:  85%|███████████████████▌   | 851/1000 [07:30<01:24,  1.76it/s]

[851/1000]
EN: The World Health Organization praised India’s efforts in polio eradication during a regional health summit.
MNI: রিজনেল হেল্থ সমিৎ অমদা ৱার্ল্দ হেল্থ ওর্গনাইজেসননা পোলিও মুত্থৎনবা ভারতনা হোৎনরিবশিং অদু থাগৎখি।
--------------------------------------------------

Translating MNI:  85%|███████████████████▌   | 852/1000 [07:31<01:28,  1.68it/s]

[852/1000]
EN: A public health survey revealed improved vaccination coverage among children in urban slum areas.
MNI: পব্লিক হেল্থ সর্ভে অমনা অর্বান স্লম এরিয়াশিংদা লৈবা অঙাংশিংগী মরক্তা ভেক্সিন কাপ্পদা হেন্না ফগৎলকপা উরেপ উয়ুং তমখি।
--------------------------------------------------

Translating MNI:  85%|███████████████████▌   | 853/1000 [07:32<01:29,  1.65it/s]

[853/1000]
EN: The Ministry of AYUSH promoted traditional medicine research through newly funded clinical studies.
MNI: নৌনা ফন্দ পীবা ক্লিনিকেল স্তদীশিংগী থোংদা আয়ুশ মন্ত্রালয়না ত্রেদিস্নেল মেদিসিন রিসর্স প্রমোত তৌখি।
--------------------------------------------------

Translating MNI:  85%|███████████████████▋   | 854/1000 [07:32<01:31,  1.59it/s]

[854/1000]
EN: Indian hospitals adopted artificial intelligence tools to assist doctors in early cancer detection.
MNI: ভারতকী হোস্পিতালশিংনা দোক্তরশিংদা কেন্সর অঙনবা মতমদা খংদোকপদা মতেং পাংনবা আর্তিফিসিয়েল ইন্তেলিজেন্স খুৎলাইশিং শিজিন্নখি।
--------------------------------------------------

Translating MNI:  86%|███████████████████▋   | 855/1000 [07:33<01:29,  1.62it/s]

[855/1000]
EN: The National Medical Commission introduced revised norms for undergraduate medical education.
MNI: নেস্নেল মেদিকেল কম্মিসননা অন্দরগ্রেজুয়েত মেদিকেল এজুকেসনগীদমক রিভাইস তৌরবা নোর্মশিং হৌদোকখি।
--------------------------------------------------

Translating MNI:  86%|███████████████████▋   | 856/1000 [07:33<01:24,  1.70it/s]

[856/1000]
EN: A shortage of specialist doctors was reported in government hospitals across rural districts.
MNI: খুঙ্গংগী জিলাশিংদা সরকারগী হোস্পিতালশিংদা অখন্নবা দোক্তরশিংগী অৱাৎপা লৈরে হায়না রিপোর্ত তৌরি।
--------------------------------------------------

Translating MNI:  86%|███████████████████▋   | 857/1000 [07:34<01:21,  1.74it/s]

[857/1000]
EN: The central government launched a digital health ID system to streamline patient medical records.
MNI: পেসেন্ত মেদিকেল রেকোর্দশিং লাইথোকহন্নবা সেন্ত্রেল সরকারনা দিজিতেল হেল্থ আইদি সিস্তেম অমা হৌদোকখি।
--------------------------------------------------

Translating MNI:  86%|███████████████████▋   | 858/1000 [07:34<01:22,  1.72it/s]

[858/1000]
EN: India’s pharmaceutical exports increased due to rising global demand for generic medicines.
MNI: জেনেরিক মেদিসিনশিংগী গ্লোবেল দিমান্দ হেনগৎলকপনা মরম ওইদুনা ভারতকী ফার্মাসুতিকেল এক্সপোর্ত হেনগৎলক্লি।
--------------------------------------------------

Translating MNI:  86%|███████████████████▊   | 859/1000 [07:35<01:22,  1.71it/s]

[859/1000]
EN: The Supreme Court of India directed states to improve healthcare infrastructure in tribal areas.
MNI: ভারতকী সুপ্রিম কোর্তনা ত্রাইবেল এরিয়াশিংদা হেল্থকেয়র ইনফ্রাস্ত্রকচর ফগৎহন্নবা রাজ্যশিংদা খঙহনখি।
--------------------------------------------------

Translating MNI:  86%|███████████████████▊   | 860/1000 [07:36<01:23,  1.68it/s]

[860/1000]
EN: A government report highlighted gaps in mental health services in public healthcare facilities.
MNI: সরকারগী রিপোর্ত অমনা পব্লিক হেল্থকেয়র ফেসিলিতীশিংদা মেন্তেল হেল্থ সর্বিসশিংদা লৈরক্লিবা খোংজেলশিং অদু পনখি।
--------------------------------------------------

Translating MNI:  86%|███████████████████▊   | 861/1000 [07:36<01:24,  1.64it/s]

[861/1000]
EN: Several private hospitals partnered with state governments to offer affordable cardiac care.
MNI: প্রাইভেৎ হোস্পিতাল কয়ানা রাজ্য সরকারশিংগা লোয়ননা শেল চংদবা মমলদা কার্দিয়াক কেয়র ফংহন্নবা পার্তনর ওইরি।
--------------------------------------------------

Translating MNI:  86%|███████████████████▊   | 862/1000 [07:37<01:29,  1.54it/s]

[862/1000]
EN: The Indian Institute of Public Health conducted a study on air pollution-related respiratory diseases.
MNI: ইন্দিয়ান ইন্সতিত্যুৎ ওফ পব্লিক হেল্থনা এয়র পোলুসনগা মরি লৈনবা রেস্পিরেতরি লায়নাশিংগী মতাংদা স্তদি অমা পাংথোকখি।
--------------------------------------------------

Translating MNI:  86%|███████████████████▊   | 863/1000 [07:38<01:29,  1.53it/s]

[863/1000]
EN: Health officials initiated a special drive to control the spread of seasonal influenza.
MNI: সেজোনগী ইনফ্লুএঞ্জা শন্দোরকপা কন্ত্রোল তৌনবা হেল্থ ওফিসিয়েলশিংনা অখন্নবা দ্রাইব অমা হৌদোকখি।
--------------------------------------------------

Translating MNI:  86%|███████████████████▊   | 864/1000 [07:38<01:27,  1.55it/s]

[864/1000]
EN: The Ministry of Health strengthened surveillance systems to monitor emerging infectious diseases.
MNI: হেল্থ মিনিস্ত্রীনা অনৌবা ইনফেক্সিয়স দিজিজশিং মোনিটর তৌনবগীদমক সর্ভিলেন্স সিস্তেম মপাঙ্গল কনখৎহল্লে।
--------------------------------------------------

Translating MNI:  86%|███████████████████▉   | 865/1000 [07:39<01:24,  1.60it/s]

[865/1000]
EN: India recorded a steady rise in organ donation registrations through national awareness campaigns.
MNI: নেস্নেল এৱারনেস কেম্পেইনশিংগী খুত্থাংদা ওর্গান দোনেসন রেজিস্ত্রেসনগী চাং লেপ্তনা হেনগৎলক্লি।
--------------------------------------------------

Translating MNI:  87%|███████████████████▉   | 866/1000 [07:39<01:19,  1.68it/s]

[866/1000]
EN: A new telemedicine platform was introduced to improve access to healthcare in remote villages.
MNI: অরাপ্পা খুঙ্গংশীংদা হেল্থকেয়র ফংহন্নবা অনৌবা তেলিমেদিসিন প্লেৎফোর্ম অমা হৌদোকখি।
--------------------------------------------------

Translating MNI:  87%|███████████████████▉   | 867/1000 [07:40<01:17,  1.72it/s]

[867/1000]
EN: The National AIDS Control Organisation reported a decline in new HIV infections.
MNI: নেস্নেল এইদস কন্ত্রোল ওর্গনাইজেসননা অনৌবা ঐচ আই ভি ইনফেক্সনগী চাং হন্থরে হায়না রিপোর্ট তৌরি।
--------------------------------------------------

Translating MNI:  87%|███████████████████▉   | 868/1000 [07:41<01:15,  1.74it/s]

[868/1000]
EN: Government hospitals increased the availability of free essential medicines for outpatients.
MNI: সরকারগী হোস্পিতালশিংনা আউতোপেসিয়েন্তশিংগীদমক্তা ফ্রি ওইবা তঙাইফদবা হিদাক-লাংথক ফংহল্লে।
--------------------------------------------------

Translating MNI:  87%|███████████████████▉   | 869/1000 [07:41<01:16,  1.71it/s]

[869/1000]
EN: A policy review emphasized the need for more nursing staff in public healthcare institutions.
MNI: পোলিসী রিভিয়ু অমনা পব্লিক হেল্থকেয়র ইনষ্টিট্যুসনশিংদা হেন্না নর্সিং ষ্টাফগী মথৌ তাবদু পনখি।
--------------------------------------------------

Translating MNI:  87%|████████████████████   | 870/1000 [07:42<01:11,  1.83it/s]

[870/1000]
EN: The Indian government signed a health cooperation agreement with a neighboring country.
MNI: ভারত সরকারনা য়ুমলোন্নবা লৈবাক অমগা লোয়ননা হেল্থ কোওপরেসন এগ্রীমেন্ত অমা খুৎয়েক পীনখ্রে।
--------------------------------------------------

Translating MNI:  87%|████████████████████   | 871/1000 [07:42<01:15,  1.70it/s]

[871/1000]
EN: Researchers from an Indian medical institute published findings on antibiotic resistance trends.
MNI: ভারতকী মেদিকেল ইন্সতিত্যুৎ অমগী রিসর্চ তৌরিবশিংনা এন্টিবাইওতিক রেসিস্তেন্সকী ত্রেন্দশিং অদু ফোংদোকখি।
--------------------------------------------------

Translating MNI:  87%|████████████████████   | 872/1000 [07:43<01:13,  1.75it/s]

[872/1000]
EN: The Health Ministry issued advisories to states following a rise in heat-related illnesses.
MNI: হিটকা মরি লৈনবা অনাবশিং হেনগৎলকপগী মতুংইন্না হকশেল মন্ত্রালয়না রাজ্যশিংদা এদভাইজরিশিং ইসু তৌখি।
--------------------------------------------------

Translating MNI:  87%|████████████████████   | 873/1000 [07:43<01:12,  1.76it/s]

[873/1000]
EN: India expanded its emergency ambulance network to improve response times in rural regions.
MNI: ভারতনা খুঙ্গংগী লমদমশিংদা রেস্পোন্স মতম ফগৎহন্নবা মসিগী এমর্জেন্সি এম্বুলেন্স নেটৱার্ক পাকথোক চাউথোকহল্লে।
--------------------------------------------------

Translating MNI:  87%|████████████████████   | 874/1000 [07:44<01:12,  1.74it/s]

[874/1000]
EN: The National Digital Health Mission aimed to improve transparency in healthcare service delivery.
MNI: নেস্নেল দিজিতেল হেল্থ মিসন অসিনা হেল্থকেয়র সর্বিস দেলিভরিদা ত্রান্সপরেন্সি ফগৎহন্নবা পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  88%|████████████████████▏  | 875/1000 [07:45<01:13,  1.71it/s]

[875/1000]
EN: A public-private partnership model was introduced to upgrade district-level hospitals.
MNI: দিস্ত্রিক্ত লেভেল হোস্পিতালশিং অপগ্রেদ তৌনবা পব্লিক-প্রাইবেৎ পার্তনরশিপ মোদেল অমা হৌদোকখি।
--------------------------------------------------

Translating MNI:  88%|████████████████████▏  | 876/1000 [07:45<01:08,  1.81it/s]

[876/1000]
EN: The government launched a mental health helpline to support individuals during medical emergencies.
MNI: মেদিকেল এমর্জেন্সিগী মতমদা মীওইশিংদা মতেং পাংনবা সরকারনা মেন্তেল হেল্থ হেল্পলাইন অমা হৌদোকখি।
--------------------------------------------------

Translating MNI:  88%|████████████████████▏  | 877/1000 [07:46<01:06,  1.84it/s]

[877/1000]
EN: India’s medical tourism sector showed growth due to affordable treatment options.
MNI: ভারতকী মেদিকেল তুরিজম সেক্তরনা শেল চংদবা ত্রিৎমেন্ত ওপশনশিংনা মরম ওইদুনা গ্রোথ উৎখি।
--------------------------------------------------

Translating MNI:  88%|████████████████████▏  | 878/1000 [07:46<01:07,  1.81it/s]

[878/1000]
EN: A parliamentary committee reviewed the implementation of healthcare schemes in backward districts.
MNI: পার্লিয়ামেন্তরী কমিতি অমনা লেংদবা জিলাশিংদা হেল্থকেয়র স্কিমশিং ইমপ্লিমেন্ত তৌরিবা অদু য়েংশিনখি।
--------------------------------------------------

Translating MNI:  88%|████████████████████▏  | 879/1000 [07:47<01:06,  1.83it/s]

[879/1000]
EN: The Ministry of Health emphasized preventive healthcare during a national policy meeting.
MNI: নেস্নেল পোলিসী মীফম অমদা হেল্থ মন্ত্রালয়না প্রিভেন্তিব হেল্থকেয়রদা অকনবা ৱাফম থমখি।
--------------------------------------------------

Translating MNI:  88%|████████████████████▏  | 880/1000 [07:47<01:06,  1.80it/s]

[880/1000]
EN: Indian scientists developed a wearable device to monitor heart health in elderly patients.
MNI: ভারতকী সাইন্তিস্তশিংনা অহল ওইরবা পেসেন্তশিংগী হার্ট হেল্থ মোনিটর তৌনবা ৱেরএবল দিভাইস অমা দিবেলপ তৌরে।
--------------------------------------------------

Translating MNI:  88%|████████████████████▎  | 881/1000 [07:48<01:06,  1.78it/s]

[881/1000]
EN: A national survey assessed nutritional deficiencies among children under five years of age.
MNI: নেস্নেল সর্ভে অমনা চহি মঙাগী মখাদা লৈবা অঙাংশীংদা ন্যুত্রিসনগী কান্নবশিং য়েংশিনখি।
--------------------------------------------------

Translating MNI:  88%|████████████████████▎  | 882/1000 [07:48<01:07,  1.75it/s]

[882/1000]
EN: The government increased insurance coverage limits under Ayushman Bharat for critical illnesses.
MNI: সরকারনা আয়ুশ্মান ভারতকী মখাদা শাথীবা অনাবশিংগীদমক ইন্সুরেন্স কোভরেজ লিমিৎ হেঙ্গৎহল্লে।
--------------------------------------------------

Translating MNI:  88%|████████████████████▎  | 883/1000 [07:49<01:08,  1.71it/s]

[883/1000]
EN: Health authorities conducted vaccination drives to prevent outbreaks of measles and rubella.
MNI: মিজলস অমসুং রুবেলাগী লাইচৎ থীংনবা হেল্থ ওথোরিতিশিংনা ভেক্সিনেসন দ্রাইবশিং পাংথোকখি।
--------------------------------------------------

Translating MNI:  88%|████████████████████▎  | 884/1000 [07:50<01:09,  1.67it/s]

[884/1000]
EN: India strengthened laboratory capacity to improve disease surveillance and diagnosis.
MNI: দিজিজ সর্বিলেন্স অমসুং দাইএগ্নোসিস ফগৎহন্নবা ভারতনা লেবোরেতরি কেপাসিতি মপাঙ্গল কনখৎহল্লে।
--------------------------------------------------

Translating MNI:  88%|████████████████████▎  | 885/1000 [07:50<01:07,  1.70it/s]

[885/1000]
EN: A state health department launched mobile clinics to serve remote tribal communities.
MNI: রাজ্যগী হেল্থ দিপার্তমেন্ত অমনা রিমোত ত্রাইবেল কম্যুনিতিশিংদা সর্বিস তৌনবা মোবাইল ক্লিনিকশিং হৌদোকখি।
--------------------------------------------------

Translating MNI:  89%|████████████████████▍  | 886/1000 [07:51<01:08,  1.68it/s]

[886/1000]
EN: The National Health Authority upgraded its data systems to enhance patient safety.
MNI: পেসেন্ত সেফতী হেঙ্গৎহন্নবা নেস্নেল হেল্থ ওথোরিতীনা মসিগী দেতা সিস্তেমশিং অপগ্রেদ তৌখ্রে।
--------------------------------------------------

Translating MNI:  89%|████████████████████▍  | 887/1000 [07:51<01:05,  1.73it/s]

[887/1000]
EN: Indian doctors highlighted the need for early screening of lifestyle-related diseases.
MNI: ভারতকী দোক্তরশিংনা লাইফস্তাইলগা মরি লৈনবা লায়নাশিং ঙন্না স্ক্রিন তৌবগী মথৌ তাবদু পনখি।
--------------------------------------------------

Translating MNI:  89%|████████████████████▍  | 888/1000 [07:52<01:00,  1.86it/s]

[888/1000]
EN: The Ministry of Health released new guidelines for hospital waste management.
MNI: হকশেল মন্ত্রালয়না হোস্পিতাল ৱেস্ত মেনেজমেন্তকীদমক অনৌবা গাইদলাইনশিং ফোংদোকখি।
--------------------------------------------------

Translating MNI:  89%|████████████████████▍  | 889/1000 [07:52<01:00,  1.82it/s]

[889/1000]
EN: Several states reported improvements in primary healthcare access through wellness centers.
MNI: ৱেলনেস সেন্তরশিংগী খুত্থাংদা প্রাইমারি হেল্থকেয়র এক্সেস হেঙ্গৎহল্লে হায়না রাজ্য কয়ানা রিপোর্ত তৌরি।
--------------------------------------------------

Translating MNI:  89%|████████████████████▍  | 890/1000 [07:53<00:57,  1.91it/s]

[890/1000]
EN: India’s public health expenditure showed a gradual increase in the latest budget.
MNI: ভারতকী পব্লিক হেল্থ এক্সপেন্দিচরনা খ্বাইদগী নৌবা বজেৎতা তপ্না তপ্না হেনগৎলক্লি।
--------------------------------------------------

Translating MNI:  89%|████████████████████▍  | 891/1000 [07:53<00:55,  1.96it/s]

[891/1000]
EN: A new online portal was launched to track the availability of hospital beds.
MNI: হোস্পিতালগী ফমুংশিং ফংলব্রা হায়বদু ত্রেক তৌনবা অনৌবা ওনলাইন পোর্তেল অমা হৌদোকখি।
--------------------------------------------------

Translating MNI:  89%|████████████████████▌  | 892/1000 [07:54<00:59,  1.81it/s]

[892/1000]
EN: Health experts in India raised concerns about rising cases of diabetes among young adults.
MNI: ভারত্তা লৈরিবা হেল্থ এক্সপার্তশিংনা নহা ওইরবা মীওইশিংগী মরক্তা দাইএবেটিজগী কেস হেনগৎলকপগী মতাংদা পুক্নিং থৌগৎলি।
--------------------------------------------------

Translating MNI:  89%|████████████████████▌  | 893/1000 [07:55<00:57,  1.86it/s]

[893/1000]
EN: The government initiated training programs to improve emergency care skills among paramedics.
MNI: সরকারনা পেরামেদিকশিংগী মরক্তা এমর্জেন্সি কেয়র স্কিল ফগৎহন্নবা ত্রেনিং প্রোগ্রামশিং হৌদোকখি।
--------------------------------------------------

Translating MNI:  89%|████████████████████▌  | 894/1000 [07:55<00:58,  1.80it/s]

[894/1000]
EN: Indian pharmaceutical companies invested in research for affordable cancer medicines.
MNI: ভারতকী ফার্মাসিতিকেল কম্পেনীশিংনা মমল চংদবা কেন্সরগী হিদাক-লাংথকশিংগী রিসর্সতা ইনভেস্ত তৌরি।
--------------------------------------------------

Translating MNI:  90%|████████████████████▌  | 895/1000 [07:56<00:55,  1.88it/s]

[895/1000]
EN: A national task force was formed to address antimicrobial resistance.
MNI: এন্টিমাইক্রোবিয়েল রেসিস্তেন্স থেংননবা নেস্নেল টাস্ক ফোর্স অমা শেমখি।
--------------------------------------------------

Translating MNI:  90%|████████████████████▌  | 896/1000 [07:56<00:54,  1.90it/s]

[896/1000]
EN: The Health Ministry conducted audits to improve quality standards in government hospitals.
MNI: সরকারগী হোস্পিতালশিংদা ক্বালিতি স্তেন্দর্দ ফগৎহন্নবা হেল্থ মন্ত্রালয়না ওদিৎশিং পাংথোকখি।
--------------------------------------------------

Translating MNI:  90%|████████████████████▋  | 897/1000 [07:57<00:53,  1.91it/s]

[897/1000]
EN: India expanded maternal nutrition programs to reduce anemia among pregnant women.
MNI: ভারতনা মীরোনবী নুপীশিংগী মরক্তা এনেমিয়া হন্থহন্নবা মেটরনেল ন্যুত্রিসন প্রোগ্রামশিং পাকথোক চাউথোকহল্লে।
--------------------------------------------------

Translating MNI:  90%|████████████████████▋  | 898/1000 [07:57<00:49,  2.06it/s]

[898/1000]
EN: A state government announced free health checkups for senior citizens.
MNI: রাজ্য সরকার অমনা অহল ওইরবা নাগরিকশিংগীদমক ফ্রি হেল্থ চেকঅপশিং লাওথোকখি।
--------------------------------------------------

Translating MNI:  90%|████████████████████▋  | 899/1000 [07:58<00:54,  1.85it/s]

[899/1000]
EN: Indian healthcare startups focused on digital solutions for chronic disease management.
MNI: ভারতকী হেল্থকেয়র স্তার্তঅপশিংনা ক্রোনিক দিজিজ মেনেজমেন্তকীদমক দিজিতেল সোল্যুসনশিংদা মীৎয়েং থম্লি।
--------------------------------------------------

Translating MNI:  90%|████████████████████▋  | 900/1000 [07:58<00:56,  1.76it/s]

[900/1000]
EN: The National Health Policy emphasized universal access to affordable healthcare services.
MNI: নেস্নেল হেল্থ পোলিসীদা মমল চংদবা হেল্থকেয়র সর্বিসশিংগী য়ুনিভর্সেল এক্সেসতা অহেনবা মীৎয়েং থমখি।
--------------------------------------------------

Translating MNI:  90%|████████████████████▋  | 901/1000 [07:59<00:58,  1.68it/s]

[901/1000]
EN: Public health officials promoted lifestyle changes to reduce cardiovascular disease risks.
MNI: কার্দিওভাস্কুলার দিজিজ রিস্ক হন্থহন্নবা পব্লিক হেল্থ ওফিসিয়েলশিংনা পুন্সি মহিং হোংদোকপা প্রোমোত তৌখি।
--------------------------------------------------

Translating MNI:  90%|████████████████████▋  | 902/1000 [08:00<00:57,  1.71it/s]

[902/1000]
EN: India improved cold chain infrastructure to ensure vaccine safety and effectiveness.
MNI: ভেক্সিন সেফতী অমসুং ইফেক্টিভ ওইহন্নবা ভারতনা কোল্দ চেন ইনফ্রাস্ত্রকচর ফগৎহল্লে।
--------------------------------------------------

Translating MNI:  90%|████████████████████▊  | 903/1000 [08:00<00:58,  1.66it/s]

[903/1000]
EN: A medical research institute in India studied long-term effects of COVID-19 infections.
MNI: ভারত্তা লৈবা মেদিকেল রিসর্স ইন্সতিত্যুৎ অমনা কোবিদ-১৯ ইনফেক্সনগী অশাংবা মতমগী ইফেক্টশিং নৈনখি।
--------------------------------------------------

Translating MNI:  90%|████████████████████▊  | 904/1000 [08:01<00:57,  1.67it/s]

[904/1000]
EN: The government strengthened referral systems between primary and tertiary healthcare centers.
MNI: সরকারনা প্রাইমারি অমসুং তর্সিয়রী হেল্থকেয়র সেন্তরশিংগী মরক্তা রিফরেল সিস্তেম হেন্না মপাঙ্গল কনখৎহল্লে।
--------------------------------------------------

Translating MNI:  90%|████████████████████▊  | 905/1000 [08:01<00:51,  1.83it/s]

[905/1000]
EN: Health workers received additional training to improve immunization coverage.
MNI: হেল্থ ৱার্করশিংনা ইম্মুনাইজেসন কোভরেজ ফগৎহন্নবা অহেনবা ত্রেনিং ফংখি।
--------------------------------------------------

Translating MNI:  91%|████████████████████▊  | 906/1000 [08:02<00:52,  1.78it/s]

[906/1000]
EN: India expanded newborn care units to reduce infant mortality rates.
MNI: ইনফেন্ত মোর্তেলিতি রেৎ হন্থহন্নবা ভারতনা নৌনা পোকপা অঙাংশিংগী কেয়র য়ুনিৎশিং পাকথোক চাউথোকহল্লে।
--------------------------------------------------

Translating MNI:  91%|████████████████████▊  | 907/1000 [08:02<00:51,  1.82it/s]

[907/1000]
EN: The Ministry of Health collaborated with states to improve sanitation and hygiene practices.
MNI: সেনিতেসন অমসুং হায়জিন প্রাক্টিসশিং ফগৎহন্নবা হকশেল মন্ত্রালয়না রাজ্যশিংগা পুন্না থবক তৌমিন্নখি।
--------------------------------------------------

Translating MNI:  91%|████████████████████▉  | 908/1000 [08:03<00:48,  1.91it/s]

[908/1000]
EN: Indian hospitals increased investment in critical care facilities.
MNI: ভারতকী হোস্পিতালশিংনা ক্রিতিকেল কেয়র ফেসিলিতীশিংদা ইনভেস্তমেন্ত হেনগৎহল্লে।
--------------------------------------------------

Translating MNI:  91%|████████████████████▉  | 909/1000 [08:03<00:50,  1.79it/s]

[909/1000]
EN: A health awareness campaign encouraged working professionals to undergo regular health screenings.
MNI: হেল্থ এৱারনেস কেম্পেইন অমনা থবক তৌরিবা প্রোফেসনেলশিংদা চাং নাইনা হেল্থ স্ক্রিনিং পাংথোক্নবা পুক্নিং থৌগৎখি।
--------------------------------------------------

Translating MNI:  91%|████████████████████▉  | 910/1000 [08:04<00:48,  1.86it/s]

[910/1000]
EN: The government introduced reforms to regulate private healthcare pricing.
MNI: সরকারনা প্রাইবেৎ হেল্থকেয়র প্রাইসিং রিগুলেত তৌনবা রিফোর্মশিং হৌদোকখি।
--------------------------------------------------

Translating MNI:  91%|████████████████████▉  | 911/1000 [08:04<00:47,  1.87it/s]

[911/1000]
EN: India enhanced its disease reporting systems to improve outbreak preparedness.
MNI: ভারতনা লাইচৎকী শেম-শাবা ফগৎহন্নবা মসিগী লায়না রিপোর্তিং সিস্তেমশিং হেনগৎহল্লে।
--------------------------------------------------

Translating MNI:  91%|████████████████████▉  | 912/1000 [08:05<00:46,  1.88it/s]

[912/1000]
EN: Health experts recommended increased funding for mental health research in India.
MNI: হেল্থ এক্সপার্তশিংনা ভারত্তা মেন্তেল হেল্থ রিসর্সকীদমক ফন্দ হেনগৎহন্নবা রিকমেন্দ তৌরি।
--------------------------------------------------

Translating MNI:  91%|████████████████████▉  | 913/1000 [08:06<00:47,  1.81it/s]

[913/1000]
EN: The National Health Authority reviewed feedback to improve beneficiary services.
MNI: নেস্নেল হেল্থ ওথোরিতীনা বেনেফিসরী সর্বিসশিং ফগৎহন্নবা ফিদবেক রিভিয়ু তৌখি।
--------------------------------------------------

Translating MNI:  91%|█████████████████████  | 914/1000 [08:06<00:45,  1.88it/s]

[914/1000]
EN: India strengthened disaster preparedness in hospitals for medical emergencies.
MNI: ভারতনা মেদিকেল এমর্জেন্সিগীদমক হোস্পিতালশিংদা দিজাস্তরগী শেম-শাবা হেনগৎহল্লে।
--------------------------------------------------

Translating MNI:  92%|█████████████████████  | 915/1000 [08:06<00:39,  2.13it/s]

[915/1000]
EN: A state government launched a nutrition program for school children.
MNI: রাজ্য সরকার অমনা স্কুলগী অঙাংশীংগীদমক ন্যুত্রিসন প্রোগ্রাম অমা হৌদোকখি।
--------------------------------------------------

Translating MNI:  92%|█████████████████████  | 916/1000 [08:07<00:44,  1.89it/s]

[916/1000]
EN: The Health Ministry emphasized community participation in strengthening public healthcare systems.
MNI: পব্লিক হেল্থকেয়র সিস্তেমশিং মপাঙ্গল কনখৎহন্নবা কম্যুনিতি পার্তিসিপেসনদা হকশেল মন্ত্রালয়না অকনবা ৱাফম থমখি।
--------------------------------------------------

Translating MNI:  92%|█████████████████████  | 917/1000 [08:08<00:49,  1.69it/s]

[917/1000]
EN: The Union Budget 2026 increased the healthcare allocation to 1,06,530 crore rupees for the Ministry of Health and Family Welfare.
MNI: কেন্দ্রগী বজেৎ ২০২৬না হেল্থ অমসুং ফেমিলি ৱেলফেয়র মন্ত্রালয়গী ওইনা হেল্থকেয়র এলোকেসন লুপা কোতি ১০৬,৫৩০দা হেনগৎহল্লে।
--------------------------------------------------

Translating MNI:  92%|█████████████████████  | 918/1000 [08:08<00:50,  1.61it/s]

[918/1000]
EN: Finance Minister Nirmala Sitharaman announced a 10 percent hike in the health budget compared to the previous fiscal year.
MNI: শেল-থুম মন্ত্রী নির্মলা সীতারমন্না মমাংগী শেনবা চহিগা চাংদম্নবদা হকশেলগী বজেৎ চাদা ১০ হেনগৎহনগনি হায়না লাউথোকখি।
--------------------------------------------------

Translating MNI:  92%|█████████████████████▏ | 919/1000 [08:09<00:50,  1.60it/s]

[919/1000]
EN: The Government of India launched the Biopharma SHAKTI initiative with an outlay of 10,000 crore rupees over five years.
MNI: ভারত সরকারনা চহি মঙাগী মনুংদা লুপা কোতি ১০,০০০গী আউতলেগা লোয়ননা বাইওফার্মা শাক্তি ইনিসিয়েতিব হৌদোকখি।
--------------------------------------------------

Translating MNI:  92%|█████████████████████▏ | 920/1000 [08:10<00:51,  1.54it/s]

[920/1000]
EN: The Biopharma SHAKTI scheme aims to strengthen the domestic production of biologics and biosimilars in India.
MNI: বাইওফার্মা শক্তী স্কিম অসিনা ভারত্তা বাইওলিক্স অমসুং বাইওসিমিলরশিংগী দোমেস্তিক প্রদক্সন মপাঙ্গল কনখৎহন্নবা পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  92%|█████████████████████▏ | 921/1000 [08:11<00:53,  1.47it/s]

[921/1000]
EN: The Ministry of Health will support states in establishing five new regional medical hubs through private-sector partnerships.
MNI: প্রাইভেৎ সেক্তর পার্তনরশিপকী থোংদা অনৌবা রিজনেল মেদিকেল হব মঙা লিংখৎপদা হকশেল মন্ত্রালয়না রাজ্যশিংদা মতেং পাংগনি।
--------------------------------------------------

Translating MNI:  92%|█████████████████████▏ | 922/1000 [08:11<00:54,  1.44it/s]

[922/1000]
EN: These five regional medical hubs will combine medical services, educational facilities, and research centers under one roof.
MNI: রিজনেল মেদিকেল হব মঙা অসিনা মেদিকেল সর্বিসশিং, এজুকেসনেল ফেসিলিতীশিং অমসুং রিসর্স সেন্তরশিং য়ুম অমগী মখাদা পুন্সিনগনি।
--------------------------------------------------

Translating MNI:  92%|█████████████████████▏ | 923/1000 [08:12<00:52,  1.47it/s]

[923/1000]
EN: The Union Budget 2026 proposed the establishment of NIMHANS 2.0 in North India to address mental health needs.
MNI: মেন্তেল হেল্থগী মথৌ তাবশিং কোকহন্নবা অৱাং ভারত্তা নিমহান্স ২.০ লিংখৎনবা কেন্দ্রগী বজেৎ ২০২৬না প্রপোজ তৌখি।
--------------------------------------------------

Translating MNI:  92%|█████████████████████▎ | 924/1000 [08:13<00:52,  1.44it/s]

[924/1000]
EN: The Government plans to upgrade the National Mental Health Institutes in Ranchi and Tezpur into regional apex institutions.
MNI: সরকারনা রাঞ্চী অমসুং তেজপুরদা লৈবা নেস্নেল মেন্তেল হেল্থ ইন্সতিত্যুৎশিং রিজনেল এপেক্স ইনষ্টিট্যুসনশিংদা অপগ্রেদ তৌনবা পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  92%|█████████████████████▎ | 925/1000 [08:13<00:48,  1.54it/s]

[925/1000]
EN: The Ministry of Health allocated 3,477 crore rupees to the National AIDS and STD Control Programme.
MNI: নেস্নেল এইদস এন্দ এসতিদি কন্ত্রোল প্রোগ্রামদা হকশেল মন্ত্রালয়না লুপা কোতি ৩৪৭৭ কায়থোকখি।
--------------------------------------------------

Translating MNI:  93%|█████████████████████▎ | 926/1000 [08:14<00:49,  1.49it/s]

[926/1000]
EN: The Union Budget 2026 provided a full customs duty exemption on 17 essential cancer-related drugs.
MNI: কেন্দ্রগী বজেৎ ২০২৬না কেন্সরগা মরি লৈনবা তঙাইফদবা হিদাক-লাংথক ১৭দা মপুংফাবা কস্তমস দ্যুত ইস্পেন্সন অমা পীরি।
--------------------------------------------------

Translating MNI:  93%|█████████████████████▎ | 927/1000 [08:15<00:47,  1.55it/s]

[927/1000]
EN: Seven additional rare diseases were added to the list for easier personal import of life-saving medicines.
MNI: পুন্সি কনবা হিদাক-লাংথকশিং হেন্না লায়থোকহন্নবগীদমক অতৈ লায়না তরেৎ অসি লিস্ত অসিদা হাপচিল্লে।
--------------------------------------------------

Translating MNI:  93%|█████████████████████▎ | 928/1000 [08:15<00:46,  1.54it/s]

[928/1000]
EN: The Government announced a 50 percent expansion in emergency and trauma care capacity at district hospitals.
MNI: দিস্ত্রিক্ত হোস্পিতালশিংদা এমর্জেন্সি অমসুং ত্রোমা কেয়র কেপাসিতী চাদা ৫০ পাকথোক চাউথোকহন্নবা সরকারনা লাওথোকখি।
--------------------------------------------------

Translating MNI:  93%|█████████████████████▎ | 929/1000 [08:16<00:47,  1.51it/s]

[929/1000]
EN: The Ministry of Health intends to establish dedicated emergency and trauma care centers in every district hospital.
MNI: হকশেল মন্ত্রালয়না দিস্ত্রিক্ত হোস্পিতাল খুদিংমক্তা দেদিকেতেদ এমর্জেন্সি অমসুং ত্রোমা কেয়র সেন্তরশিং লিংখৎনবা পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  93%|█████████████████████▍ | 930/1000 [08:16<00:44,  1.58it/s]

[930/1000]
EN: The Pradhan Mantri Jan Arogya Yojana received an increased allocation of 9,500 crore rupees to expand coverage.
MNI: প্রধান মন্ত্রী জন অরোগ্যা য়োজনাদা কোভরেজ পাকথোক চাউথোকহন্নবা লুপা কোতি ৯৫০০গী অহেনবা এলোকেসন ফংখি।
--------------------------------------------------

Translating MNI:  93%|█████████████████████▍ | 931/1000 [08:17<00:44,  1.55it/s]

[931/1000]
EN: The National Health Mission was allocated 39,390 crore rupees to enhance primary healthcare delivery across states.
MNI: রাজ্য কয়াদা প্রাইমারি হেল্থকেয়র দেলিভরি হেঙ্গৎহন্নবা নেস্নেল হেল্থ মিসনদা লুপা কোতি ৩৯,৩৯০ কায়থোকখ্রে।
--------------------------------------------------

Translating MNI:  93%|█████████████████████▍ | 932/1000 [08:18<00:41,  1.65it/s]

[932/1000]
EN: The Government proposed a plan to add 100,000 allied health professionals over the next five years.
MNI: সরকারনা মথংগী চহি মঙাদা মরী লৈনবা হেল্থ প্রোফেস্নেল ১০০,০০০ হাপচিন্নবা প্লান অমা প্রপোজ তৌখি।
--------------------------------------------------

Translating MNI:  93%|█████████████████████▍ | 933/1000 [08:18<00:40,  1.67it/s]

[933/1000]
EN: The Ministry of Health will upgrade existing institutions for allied health professionals to improve training standards.
MNI: ত্রেনিং স্তেন্দর্দ ফগৎহন্নবা হেল্থ মন্ত্রালয়না হৌজিক লৈরিবা হেল্থ প্রোফেস্নেলশিংগী ইনষ্টিট্যুসনশিং অপগ্রেদ তৌরগনি।
--------------------------------------------------

Translating MNI:  93%|█████████████████████▍ | 934/1000 [08:19<00:39,  1.67it/s]

[934/1000]
EN: The Union Budget 2026 earmarked 4,821 crore rupees specifically for the Department of Health Research.
MNI: কেন্দ্রগী বজেৎ ২০২৬না দিপার্তমেন্ত ওফ হেল্থ রিসর্সকীদমক লুপা কোতি ৪৮২১ অখন্ননা কায়থোকখি।
--------------------------------------------------

Translating MNI:  94%|█████████████████████▌ | 935/1000 [08:19<00:39,  1.67it/s]

[935/1000]
EN: Finance Minister Nirmala Sitharaman proposed the creation of three new All India Institutes of Ayurveda.
MNI: অর্থমন্ত্রী নির্মলা সীতারমন্না অনৌবা ওল ইন্দিয়া ইন্সতিত্যুৎ ওফ আয়ুর্বেদ অহুম লিংখৎনবা প্রপোজ তৌখি।
--------------------------------------------------

Translating MNI:  94%|█████████████████████▌ | 936/1000 [08:20<00:40,  1.59it/s]

[936/1000]
EN: The Government plans to train 1.5 lakh caregivers in allied skills such as geriatric care and yoga.
MNI: গবর্নমেন্তনা য়েংশিনবীরিবা মীওই লাখ ১.৫বু জেরিএত্রিক কেয়র অমসুং যোগকুম্বা মরী লৈনবা স্কিলশিংদা ত্রেনিং পীবা পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  94%|█████████████████████▌ | 937/1000 [08:21<00:40,  1.57it/s]

[937/1000]
EN: The Ayushman Bharat Digital Mission received 350 crore rupees to improve digital health record interoperability.
MNI: দিজিতেল হেল্থ রেকোর্দ ইন্তরওপরেবিলিতী ফগৎহন্নবা আয়ুশ্মান ভারত দিজিতেল মিসননা লুপা কোতি ৩৫০ ফংখি।
--------------------------------------------------

Translating MNI:  94%|█████████████████████▌ | 938/1000 [08:22<00:42,  1.47it/s]

[938/1000]
EN: The Ministry of Health aims to reduce import dependence by supporting the domestic manufacturing of high-value biopharmaceuticals.
MNI: হকশেল মন্ত্রালয়না হায়-ভেল্যু বাইওফার্মাসুতিকেলশিংগী দোমেস্তিক মেন্যুফেকচরিং সপোর্ত তৌদুনা ইম্পোর্ত দিপেন্দেন্স হন্থহন্নবা পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  94%|█████████████████████▌ | 939/1000 [08:22<00:42,  1.42it/s]

[939/1000]
EN: The Union Budget 2026 focus shifted from a curative model to a prevention-first and holistic wellness approach.
MNI: কেন্দ্রগী বজেৎ ২০২৬না ক্যুরেতিব মোদেল অমদগী প্রিভেন্সন-ফার্ষ্ত অমসুং হোলিস্তিক ৱেলনেস এপ্রোচ অমদা মীৎয়েং থমখি।
--------------------------------------------------

Translating MNI:  94%|█████████████████████▌ | 940/1000 [08:23<00:41,  1.45it/s]

[940/1000]
EN: The Government will establish 1,000 accredited clinical trial sites to position India as a global research destination.
MNI: ভারত অসি গ্লোবেল রিসার্স দেস্তিনেসন অমা ওইনা লৈহন্নবগীদমক সরকারনা এক্রেদিতেদ ক্লিনিক ত্রাইএল সাইট ১,০০০ লিংখৎকনি।
--------------------------------------------------

Translating MNI:  94%|█████████████████████▋ | 941/1000 [08:24<00:42,  1.40it/s]

[941/1000]
EN: The Central Drugs Standard Control Organisation will receive more specialized personnel to improve regulatory efficiency.
MNI: সেন্ত্রেল দ্রগস স্তেন্দর্দ কন্ত্রোল ওর্গনাইজেসননা রিগুলেতরী ইফিসিএন্সি হেঙ্গৎহন্নবা হেন্না স্পেসিয়েলাইজ তৌরবা পর্সোনেল ফংলগনি।
--------------------------------------------------

Translating MNI:  94%|█████████████████████▋ | 942/1000 [08:25<00:42,  1.37it/s]

[942/1000]
EN: Artificial Intelligence is now being used by Indian radiologists to detect early signs of lung cancer from medical images.
MNI: আর্তিফিসিয়েল ইন্তেলিজেন্স অসি হৌজিক্তি ভারতকী রেদিওলোজিস্তশিংনা মেদিকেল ইমেজশিংদগী লংস কেন্সরগী অঙনবা খুদমশিং খংদোক্নবগীদমক শীজিন্নরি।
--------------------------------------------------

Translating MNI:  94%|█████████████████████▋ | 943/1000 [08:25<00:44,  1.29it/s]

[943/1000]
EN: Qure.ai implemented AI-driven imaging solutions to facilitate faster diagnosis of strokes in rural Indian hospitals.
MNI: ভারতকী খুঙ্গংগী হোস্পিতালশিংদা ষ্ট্রোককী হেন্না থুনা দাইএগ্নোসিস তৌবা ঙমহন্নবা কুর.আই.না এ.আই.দা চলাইবা ইমেজিং সোলুসনশিং ইমপ্লিমেন্ত তৌরি।
--------------------------------------------------

Translating MNI:  94%|█████████████████████▋ | 944/1000 [08:26<00:44,  1.27it/s]

[944/1000]
EN: Indian healthcare providers are adopting "Actionable AI" to provide predictive health roadmaps instead of simple lab reports.
MNI: ভারতকী হেল্থকেয়র প্রোভাইদরশিংনা অচম্বা লেব রিপোর্তশিংগী মহুত্তা প্রেদিক্তিব হেল্থ রোদমেপশিং পীনবা এক্তোনেবল এ আই এদোপ্ত তৌরি।
--------------------------------------------------

Translating MNI:  94%|█████████████████████▋ | 945/1000 [08:27<00:41,  1.31it/s]

[945/1000]
EN: The use of wearables in India is evolving from basic fitness tracking to clinical-grade monitoring of heart rhythm.
MNI: ভারত্তা ৱেরাবল শীজিন্নবা অসি বেসিক ফিৎনেস ত্রেকিংদগী হৌরগা হার্ট রাইথমগী ক্লিনিকেল গ্রেদ মোনিতরিং ফাওবা হৌরক্লি।
--------------------------------------------------

Translating MNI:  95%|█████████████████████▊ | 946/1000 [08:28<00:42,  1.27it/s]

[946/1000]
EN: Medical technology startups in India are developing microfluidic devices that conduct complex tests on a single drop of blood.
MNI: ভারত্তা লৈরিবা মেদিকেল তেক্নোলোজী স্তার্তঅপশিংনা মাইক্রোফ্লুইদিক দিভাইসশিং দিবেলপ তৌরি অমসুং মখোয়না ঈ অমখক্তদা কমপ্লেক্স ওইবা তেস্তশিং পাংথোকই।
--------------------------------------------------

Translating MNI:  95%|█████████████████████▊ | 947/1000 [08:28<00:39,  1.35it/s]

[947/1000]
EN: The Indian MedTech sector is projected to reach a market value of 50 billion dollars by the end of 2026.
MNI: ইন্দিয়ান মেদতেক সেক্তর অসি ইং ২০২৬গী অরোইবা ফাউবদা দোল্লর বিলিয়ন ৫০গী মার্কেৎ ভেল্যুদা য়ৌগনি হায়না পানরি।
--------------------------------------------------

Translating MNI:  95%|█████████████████████▊ | 948/1000 [08:29<00:38,  1.35it/s]

[948/1000]
EN: Hospitals in Tier 2 cities are using predictive analytics to optimize patient flow and reduce waiting times.
MNI: টায়র ২গী সহরশিংদা লৈরিবা হোস্পিতালশিংনা পেসেন্ত ফ্লো ওপ্তিমাইজ তৌনবা অমসুং ৱেইত তৌবগী মতম হন্থহন্নবা প্রিদেক্টিভ এনালাইতিক্স শিজিন্নরি।
--------------------------------------------------

Translating MNI:  95%|█████████████████████▊ | 949/1000 [08:30<00:38,  1.32it/s]

[949/1000]
EN: Telemedicine services are expanding in remote regions to connect rural patients with specialists in metropolitan cities.
MNI: মেত্রোপোলিতান সহরশিংদা লৈরিবা স্পেসিয়েলিস্তশিংগা খুঙ্গংগী অনাবশিং শম্নহন্নবা রিমোত রিজনেলশিংদা তেলিমেদিসিন সর্বিসশিং পাকথোক চাউথোকহল্লি।
--------------------------------------------------

Translating MNI:  95%|█████████████████████▊ | 950/1000 [08:31<00:39,  1.26it/s]

[950/1000]
EN: The Ayushman Bharat Health Account (ABHA) system allows patients to share digital health records securely with doctors.
MNI: আয়ুশ্মান ভারত হেল্থ একাউন্ত সিস্তেমনা পেসেন্তশিংদা দোক্তরশিংগা দিজিতেল হেল্থ রেকোর্দশিং সেক্যুওর ওইনা শেয়র তৌনবগী খুদোংচাবা পীরি।
--------------------------------------------------

Translating MNI:  95%|█████████████████████▊ | 951/1000 [08:32<00:42,  1.16it/s]

[951/1000]
EN: Robotic-assisted surgery is becoming more common in private Indian hospitals for complex urological procedures.
MNI: কমপ্লেক্স ওইবা য়ুরোলোজিকেল প্রোসিদ্যুওরশিংগীদমক রোবোত-এসিস্তেদ সর্জরী অসি প্রাইভেৎ ইন্দিয়ান হোস্পিতালশিংদা হেন্না কমন ওইরক্লি।
--------------------------------------------------

Translating MNI:  95%|█████████████████████▉ | 952/1000 [08:33<00:43,  1.12it/s]

[952/1000]
EN: Many Indian diagnostic labs are now using genomic testing as a primary triage tool for chronic diseases.
MNI: হৌজিক্তি ভারতকী দাইএগ্নোস্তিক লেব কয়া অমনা ক্রোনিক লায়নাশিংগী প্রাইমারি ত্রাইএজ টুল অমা ওইনা জেনোমিক তেস্তিং শিজিন্নরি।
--------------------------------------------------

Translating MNI:  95%|█████████████████████▉ | 953/1000 [08:34<00:46,  1.02it/s]

[953/1000]
EN: Healthcare organizations are deploying AI agents to handle administrative tasks like insurance pre-authorizations and billing.
MNI: হেল্থকেয়র ওর্গানাইজেসনশিংনা ইন্সুরেন্স প্রি-ওথোরাইজেসনশিং অমসুং বিলিংগুম্বা এদমিনিস্ত্রেতিব তাস্কশিং হেন্দল তৌনবা এ আই এজেন্তশিং শীজিন্নরি।
--------------------------------------------------

Translating MNI:  95%|█████████████████████▉ | 954/1000 [08:35<00:46,  1.02s/it]

[954/1000]
EN: Smart sensors in Indian ICUs are reducing unplanned admissions by providing continuous real-time monitoring of vitals.
MNI: ভারতকী আইসিয়ুশিংদা লৈরিবা স্মার্ত সেন্সরশিংনা মরুওইবা ফিভমশিং লেপ্তনা রিএল-তাইম মোনিতর তৌদুনা প্লান তৌদবা এদমিসন হন্থহল্লি।
--------------------------------------------------

Translating MNI:  96%|█████████████████████▉ | 955/1000 [08:36<00:44,  1.00it/s]

[955/1000]
EN: The digital transformation of clinical trials in India is enabling remote patient monitoring through mobile devices.
MNI: ভারত্তা ক্লিনিক ত্রাইএলগী দিজিতেল ত্রান্সফোর্মেসননা মোবাইল দিভাইসশিংগী খুত্থাংদা রিমোৎ পেসেন্ত মোনিতরিং তৌবা ঙমহল্লে।
--------------------------------------------------

Translating MNI:  96%|█████████████████████▉ | 956/1000 [08:37<00:45,  1.03s/it]

[956/1000]
EN: Indian pharmaceutical companies are integrating AI into their quality control systems to ensure paperless and compliant workflows.
MNI: ভারতকী ফার্মাসিতিকেল কম্পেনীশিংনা মখোয়গী ক্বালিতি কন্ত্রোল সিস্তেমশিংদা আই.আই.বু পুন্সিন্নদুনা পেপরলেস অমসুং কমপ্লাইএন্ত ৱার্কফ্লো লৈহন্নবা হোৎনরি।
--------------------------------------------------

Translating MNI:  96%|██████████████████████ | 957/1000 [08:38<00:42,  1.00it/s]

[957/1000]
EN: Low-cost needle-free drug delivery technologies are gaining traction for vaccine administration in pediatric clinics.
MNI: পেরিএত্রিক ক্লিনিকশিংদা ভেক্সিন এদমিনিস্ত্রেসনগীদমক্তা লো-কোস্ত ইদল-ফ্রি দ্রগ দেলিভরি তেক্নোলোজীশিংনা ত্রেক্সন ফগৎলক্লি।
--------------------------------------------------

Translating MNI:  96%|██████████████████████ | 958/1000 [08:39<00:38,  1.08it/s]

[958/1000]
EN: Public health experts launched India's first Public Health Monitor to track real-time health outcomes across states.
MNI: পব্লিক হেল্থ এক্সপার্তশিংনা ভারতকী অহানবা পব্লিক হেল্থ মোনিতর হৌদোকখি ।
--------------------------------------------------

Translating MNI:  96%|██████████████████████ | 959/1000 [08:39<00:34,  1.20it/s]

[959/1000]
EN: Specialized medical tourism facilitation centers will be integrated into the new regional medical hubs.
MNI: স্পেসিয়েলাইজ তৌরবা মেদিকেল তুরিজম ফেসিলিতেসন সেন্তরশিং অনৌবা রিজনেল মেদিকেল হবশিংদা পুন্সিন্নগনি।
--------------------------------------------------

Translating MNI:  96%|██████████████████████ | 960/1000 [08:40<00:32,  1.23it/s]

[960/1000]
EN: Indian doctors are using hyper-personalized medicine to tailor treatments based on the genetic profile of individual patients.
MNI: ভারতকী দোক্তরশিংনা পেসেন্তশিংগী জিনেতিকেল প্রোফাইলদা য়ুম্ফম ওইদুনা লাইয়েং তৌনবা হায়পর-পর্সোনেলাইজ মেদিসিন শীজিন্নরি।
--------------------------------------------------

Translating MNI:  96%|██████████████████████ | 961/1000 [08:41<00:29,  1.30it/s]

[961/1000]
EN: The adoption of 5G technology is improving the speed and reliability of remote robotic surgeries in India.
MNI: ৫জি তেক্নোলোজী শিজিন্নবনা ভারত্তা রিমোত রোবোতিক সর্জরীগী স্পিদ অমসুং রিলেএবিলিতী হেঙ্গৎহল্লে।
--------------------------------------------------

Translating MNI:  96%|██████████████████████▏| 962/1000 [08:42<00:31,  1.20it/s]

[962/1000]
EN: 20 All India Institutes of Medical Sciences signed a memorandum to form a pan-India research consortium.
MNI: ২০ ওল ইন্দিয়া ইন্সতিত্যুৎ ওফ মেদিকেল সাইন্সেসনা পেন-ইন্দিয়া রিসর্স কনসোর্সিয়ম অমা শেম্নবা মেমোরেন্দম অমা খুৎয়েক পীনখ্রে।
--------------------------------------------------

Translating MNI:  96%|██████████████████████▏| 963/1000 [08:43<00:31,  1.19it/s]

[963/1000]
EN: The AIIMS research consortium will focus on multicentric clinical trials for low-cost cancer treatments.
MNI: এ আই আই এম এস রিসর্স কনসোর্সিয়মনা লোল কোস্ত কেন্সর ত্রিৎমেন্তকীদমক্তা মল্তিসেন্ত্রিক ক্লিনিক ত্রাইএলশিংদা মীৎয়েং থমগনি।
--------------------------------------------------

Translating MNI:  96%|██████████████████████▏| 964/1000 [08:44<00:30,  1.18it/s]

[964/1000]
EN: A medical student at the Dharwad Institute of Mental Health unfortunately committed suicide in early February.
MNI: ফেব্রুৱরীগী অঙনবা শরুক্তা ধর্ৱাদ ইন্সতিত্যুৎ ওফ মেন্তেল হেল্থকী মেদিকেল ছাত্র অমনা খুদোংথীনিঙাই ওইরে ।
--------------------------------------------------

Translating MNI:  96%|██████████████████████▏| 965/1000 [08:44<00:29,  1.19it/s]

[965/1000]
EN: The Maharashtra University of Health Sciences revoked the affiliation of Sinhgad Dental College over regulatory violations.
MNI: মহারাস্ত্রা য়ুনিবর্সিতী ওফ হেল্থ সাইন্সেসনা রিগুলেতরি লান্না থুগাইবদগী সিঙ্গগদ দেন্তেল কোলেজগী এফিলিয়েসন লৌথোকখি।
--------------------------------------------------

Translating MNI:  97%|██████████████████████▏| 966/1000 [08:45<00:27,  1.23it/s]

[966/1000]
EN: A 40-year-old urologist suffered a cardiac arrest while speaking at an international conference in Indore.
MNI: ইন্দোরদা পাংথোকপা ইন্তর্নেস্নেল কনফরেন্স অমদা ৱা ঙাংলদুনা চহি ৪০ শুরবা য়ুরোলোজিস্ত অমা কার্দিয়াক এরেষ্ট অমা থেংনখি।
--------------------------------------------------

Translating MNI:  97%|██████████████████████▏| 967/1000 [08:46<00:26,  1.24it/s]

[967/1000]
EN: The District Consumer Commission in Kannur held a surgeon liable for negligence in a varicose vein treatment.
MNI: কন্নুরদা লৈরিবা দিস্ত্রিক্ত কঞ্জ্যুমর কমিসননা সর্জন অমা ভেরাইকোজ ভেন ত্রিৎমেন্ত অমদা মীৎয়েং চংহন্দবগীদমক দায়ত্ব লৌখি।
--------------------------------------------------

Translating MNI:  97%|██████████████████████▎| 968/1000 [08:47<00:25,  1.26it/s]

[968/1000]
EN: Two government doctors in Bhopal were sentenced to prison for securing medical seats with fake domicile certificates.
MNI: ভোপালদা লৈরিবা সরকারগী দোক্তর অনিবু মেদিকেল সিৎশিং ফাজিল্লবা দোমিসাইল সর্টিফিকেটকা লোয়ননা সেক্যুওর তৌবগীদমক জেলদা থম্বগী চৈরাক পীখ্রে।
--------------------------------------------------

Translating MNI:  97%|██████████████████████▎| 969/1000 [08:48<00:25,  1.21it/s]

[969/1000]
EN: Authorities in Maharashtra are seeking action against a pathologist for signing lab reports without proper registration.
MNI: মহারাস্ত্রাগী ওথোরিতিশিংনা লেব রিপোর্তশিং মওং চুম্না রেজিস্ত্রেসন তৌদনা খুৎয়েক পীনবগীদমক পেথোলোজিস্ত অমগী মায়োক্তা থবক লৌখৎনবা খংজরি।
--------------------------------------------------

Translating MNI:  97%|██████████████████████▎| 970/1000 [08:49<00:25,  1.18it/s]

[970/1000]
EN: The Central Council for Research in Ayurvedic Sciences signed an agreement to digitize rare Ayurveda manuscripts.
MNI: সেন্ত্রেল কাউন্সিল ফোর রিসর্স ইন আয়ুর্বেদিক সাইন্সেসনা অরুবা আয়ুর্বেদ মেনস্ক্রিপ্তশিং দিজিতেজ তৌনবা য়ানচে অমা খুৎয়েক পীনখ্রে।
--------------------------------------------------

Translating MNI:  97%|██████████████████████▎| 971/1000 [08:50<00:25,  1.12it/s]

[971/1000]
EN: Apollo Hospitals Chairman Dr. Prathap Reddy stated that the 2026 budget strengthens the vision of a healthier India.
MNI: এপোলো হোস্পিতালগী চেয়রমেন দা. প্রতাপ রেদ্দীনা হায়খি মদুদি ২০২৬গী বজেৎনা হেন্না মশা মউ ফবা ভারত অমগী মীৎয়েং অদু মপাঙ্গল কনখৎহল্লি।
--------------------------------------------------

Translating MNI:  97%|██████████████████████▎| 972/1000 [08:50<00:25,  1.11it/s]

[972/1000]
EN: Max Healthcare plans to expand its robotic-assisted surgery program across its network of hospitals.
MNI: মেক্স হেল্থকেয়রনা মসিগী হোস্পিতালগী নেটৱার্ক পুম্নমক্তা রোবোতিক-এসিস্তেদ সর্জরি প্রোগ্রাম পাকথোক চাউথোকহন্নবা পান্দম থম্লি।
--------------------------------------------------

Translating MNI:  97%|██████████████████████▍| 973/1000 [08:52<00:26,  1.02it/s]

[973/1000]
EN: Health experts warned that the unorganized diagnostic sector in India will face consolidation due to stricter quality norms.
MNI: হেল্থ এক্সপার্তশিংনা তকশিনখি মদুদি ভারত্তা অনওর্গানাইজ দাইএগ্নোস্তিক সেক্তর অসি ক্বালিতি নোর্মশিং হেন্না কনবা মরম্না কন্সোলিদেসনগী মায়োক্তা থেংনরক্কনি।
--------------------------------------------------

Translating MNI:  97%|██████████████████████▍| 974/1000 [08:52<00:24,  1.07it/s]

[974/1000]
EN: The Indian Council of Medical Research received 4,000 crore rupees to bolster indigenous medical research.
MNI: ইন্দিয়ান কাউন্সিল ওফ মেদিকেল রিসর্সনা ইন্দিজেনস মেদিকেল রিসর্স হেঙ্গৎহন্নবা লুপা কোতি ৪০০০ ফংখি।
--------------------------------------------------

Translating MNI:  98%|██████████████████████▍| 975/1000 [08:53<00:21,  1.15it/s]

[975/1000]
EN: Public health officials are drafting a new Planetary Health Policy Framework to address climate-linked diseases.
MNI: পব্লিক হেল্থ ওফিসিয়েলশিংনা ক্লাইমেৎগা মরি লৈনবা লায়নাশিং থেংননবা অনৌবা প্লানেতরী হেল্থ পোলিসী ফ্রেমৱার্ক অমা শেমগৎলি।
--------------------------------------------------

Translating MNI:  98%|██████████████████████▍| 976/1000 [08:54<00:20,  1.17it/s]

[976/1000]
EN: The Food Safety and Standards Authority of India is working to make healthy food more affordable than unhealthy options.
MNI: ফুদ সেফতী এন্দ স্তেন্দর্দস ওথোরিতী ওফ ইন্দিয়ানা হকশেল ফবা মচি ওইবা চিঞ্জাকশিং অসি হকশেল ফত্তবা ওপশনশিংদগী হেন্না শেল চংহন্নবা থবক তৌরি।
--------------------------------------------------

Translating MNI:  98%|██████████████████████▍| 977/1000 [08:55<00:18,  1.26it/s]

[977/1000]
EN: Researchers at AIIMS Delhi are investigating the use of AI to reduce hospital-acquired infections.
MNI: দিল্লীগী এ আই আই এম এসকী রিসর্চ তৌরিবশিংনা হোস্পিতালদগী ইনফেক্সন হন্থহন্নবা এ আই শিজিন্নবগী মতাংদা ইনভেস্ত তৌরি।
--------------------------------------------------

Translating MNI:  98%|██████████████████████▍| 978/1000 [08:55<00:16,  1.31it/s]

[978/1000]
EN: The National AIDS Control Organisation is upgrading blood transfusion services to ensure nationwide safety and availability.
MNI: নেস্নেল এইদস কন্ত্রোল ওর্গনাইজেসননা লৈবাক শিনবা থুংনা শাফবা অমসুং ফংহন্নবা ব্লদ ত্রান্সফুজন সর্বিসশিং অপগ্রেদ তৌরি।
--------------------------------------------------

Translating MNI:  98%|██████████████████████▌| 979/1000 [08:56<00:16,  1.29it/s]

[979/1000]
EN: Indian pediatricians noted a rise in parental awareness regarding neurodivergence and behavioral health issues.
MNI: ন্যুরোদিভর্জেন্স অমসুং লমচৎ-শাজৎকী হকশেলগী ইসুশিংগা মরি লৈননা পেরন্তেল এৱারনেস হেনগৎলক্লি হায়না ভারতকী পেরিএত্রিশীংনা ফোংদোকখি।
--------------------------------------------------

Translating MNI:  98%|██████████████████████▌| 980/1000 [08:57<00:14,  1.37it/s]

[980/1000]
EN: Medical value tourism in India is expected to grow as the government streamlines visa processes for international patients.
MNI: ভারতকী মেদিকেল ভেল্যু তুরিজম অসি সরকারনা ইন্তর্নেস্নেল পেসেন্তশিংগী ভিজা প্রোসেসশিং লাইথোকহন্দুনা চাউখৎহনগনি হায়না পানরি।
--------------------------------------------------

Translating MNI:  98%|██████████████████████▌| 981/1000 [08:57<00:13,  1.36it/s]

[981/1000]
EN: The WHO Global Traditional Medicine Centre in Jamnagar is being upgraded to improve evidence-based research.
MNI: জামনগরদা লৈবা ৱ্লোস গ্লোবেল ত্রেদিস্নেল মেদিসিন সেন্তর অসি প্রমাণদা য়ুম্ফম ওইবা রিসর্স ফগৎহন্নবা অপগ্রেদ তৌরি।
--------------------------------------------------

Translating MNI:  98%|██████████████████████▌| 982/1000 [08:58<00:13,  1.36it/s]

[982/1000]
EN: Indian generic manufacturers are preparing for the patent expiry of several major global obesity medications.
MNI: ভারতকী জেনেরিক মেন্যুফেকচররশিংনা মরুওইবা গ্লোবেল ওবেসিতিগী হিদাক-লাংথক কয়াগী পেতেন্ত এক্সপিরীগীদমক শেম-শাদুনা লৈরি।
--------------------------------------------------

Translating MNI:  98%|██████████████████████▌| 983/1000 [08:59<00:12,  1.37it/s]

[983/1000]
EN: A new digital curriculum was introduced to train public health leaders in epidemiology and modern technology.
MNI: ইপিদিমিয়োলোজি অমসুং মোদর্ন তেক্নোলোজীদা পব্লিক হেল্থ লিদরশিং ত্রেন তৌনবা অনৌবা দিজিতেল করিকুলম অমা হৌদোকখি।
--------------------------------------------------

Translating MNI:  98%|██████████████████████▋| 984/1000 [09:00<00:11,  1.43it/s]

[984/1000]
EN: The government is upgrading AYUSH pharmacies to ensure higher quality standards for traditional medicines.
MNI: ত্রেদিস্নেল মেদিসিনশিংগী হেন্না ৱাংবা ক্বালিতি স্তেন্দর্দ লৈহন্নবা সরকারনা আয়ুশ ফার্মেসীশিং অপগ্রেদ তৌরি।
--------------------------------------------------

Translating MNI:  98%|██████████████████████▋| 985/1000 [09:00<00:09,  1.51it/s]

[985/1000]
EN: Several district hospitals in Uttar Pradesh are now equipped with 24/7 emergency care and trauma units.
MNI: উত্তর প্রদেশকী দিস্ত্রিক্ত হোস্পিতাল কয়াদা হৌজিক্তি ৭/৭ এমর্জেন্সি কেয়র অমসুং ত্রোমা য়ুনিৎশিং ফংহল্লে।
--------------------------------------------------

Translating MNI:  99%|██████████████████████▋| 986/1000 [09:01<00:09,  1.50it/s]

[986/1000]
EN: Private healthcare providers are increasing investments in Tier 3 cities to capture the growing rural market.
MNI: প্রাইবেৎ হেল্থকেয়র প্রোভাইদরশিংনা চাউখৎলক্লিবা রুরেল মার্কেত অদু ফগৎহন্নবা তায়র ৩ সিতিশিংদা ইনভেস্তমেন্ত হেনগৎহল্লি।
--------------------------------------------------

Translating MNI:  99%|██████████████████████▋| 987/1000 [09:01<00:08,  1.51it/s]

[987/1000]
EN: The Indian healthcare workforce is being upskilled through new digital certifications in allied health disciplines.
MNI: ভারতকী হেল্থকেয়র ৱার্কফোর্স অসি হেল্থ দিসিপ্লিনশিংদা অনৌবা দিজিতেল সর্তিফিকেসনশিংগী খুত্থাংদা অপস্কিলে তৌরি।
--------------------------------------------------

Translating MNI:  99%|██████████████████████▋| 988/1000 [09:02<00:08,  1.46it/s]

[988/1000]
EN: Public health summits in 2026 emphasized the importance of data-driven decision-making for epidemic prevention.
MNI: ২০২৬তা পাংথোক্কদৌরিবা পব্লিক হেল্থ সমিৎশিংনা লাইচৎ থীংনবা দেতাদা য়ুম্ফম ওইবা ৱারেপ লৌবগী মরুওইবা অদু পনখি।
--------------------------------------------------

Translating MNI:  99%|██████████████████████▋| 989/1000 [09:03<00:07,  1.45it/s]

[989/1000]
EN: Hospitals in Mumbai are reporting a shift toward integrated care models for chronic lifestyle diseases.
MNI: মুম্বাইগী হোস্পিতালশিংনা ক্রোনিক লাইফস্তাইল লায়নাশিংগী ইন্তিগ্রেতেদ কেয়র মোদেলগী মায়কৈদা অহোংবা অমা লৈরে হায়না রিপোর্ত তৌরি।
--------------------------------------------------

Translating MNI:  99%|██████████████████████▊| 990/1000 [09:04<00:07,  1.39it/s]

[990/1000]
EN: The Ministry of Health is focusing on improving the nurse-to-patient ratio in public hospitals through new recruitment drives.
MNI: অনৌবা রিক্রুইতমেন্ত দ্রাইবশিংগী থোংদা পব্লিক হোস্পিতালশিংদা নর্স-ত্যু-পেসেন্ত রেসিও ফগৎহন্নবা হেল্থ মন্ত্রালয়না মীৎয়েং থম্লি।
--------------------------------------------------

Translating MNI:  99%|██████████████████████▊| 991/1000 [09:04<00:06,  1.45it/s]

[991/1000]
EN: India is positioning itself as a global hub for the manufacturing of affordable biologics and specialized therapies.
MNI: ভারতনা মশামকপু মমল চংদবা বাইওলোজী অমসুং স্পেসিয়েলাইজ তৌরবা থেরাপীশিং পুথোক্নবগী গ্লোবেল হব অমা ওইনা শেমগৎলি।
--------------------------------------------------

Translating MNI:  99%|██████████████████████▊| 992/1000 [09:05<00:05,  1.56it/s]

[992/1000]
EN: PGIMER doctors achieve major breakthrough in deadly Celphos poisoning
MNI: পি জি আই এম ই আর দোক্তরশিংনা শাথীবা সেলফোস পোইজনিংদা অচৌবা খোংথাং অমা ফংলে ।
--------------------------------------------------

Translating MNI:  99%|██████████████████████▊| 993/1000 [09:05<00:04,  1.66it/s]

[993/1000]
EN: What a 12-hour work day can do to your metabolic, mental and reproductive health
MNI: পুং ১২গী থবক নুমিৎ অমনা নহাক্কী মেটাবোলিক, মেন্টেল অমসুং রিপ্রদক্টিভ হেল্থদা করি তৌবা য়াবগে
--------------------------------------------------

Translating MNI:  99%|██████████████████████▊| 994/1000 [09:06<00:03,  1.62it/s]

[994/1000]
EN: Healthcare services disrupted as doctors across states protest Kolkata colleague’s rape-murder
MNI: রাজ্য কয়াগী দোক্তরশিংনা কোলকাতাগী কোলাগা রেপ-মর্দরদা প্রোতেষ্ট তৌরগা হেল্থকেয়র সর্বিসশিং লেপখি ।
--------------------------------------------------

Translating MNI: 100%|██████████████████████▉| 995/1000 [09:07<00:03,  1.65it/s]

[995/1000]
EN: Manmohan Singh unveils multi-crore healthcare plan for paramilitary forces
MNI: মনমোহন সিংহনা পেরামিলিতরী ফোর্সশিংগীদমক কোতি কয়াগী হেল্থকেয়র প্লান মায়খুম হাংদোকখ্রে
--------------------------------------------------

Translating MNI: 100%|██████████████████████▉| 996/1000 [09:07<00:02,  1.53it/s]

[996/1000]
EN: US Senate Hearing Explodes After Senator Questions Indian Origin Doctor on Men’s Pregnancy
MNI: নুপাগী মীরোনবগী মতাংদা সেনেটরনা ইন্দিয়ান ওরিজিন দোক্তরদা ৱাহং পীরবা মতুংদা য়ু.এস. সেনেটকী হিয়ারিংদা থৌদোক থোকখি ।
--------------------------------------------------

Translating MNI: 100%|██████████████████████▉| 997/1000 [09:08<00:01,  1.60it/s]

[997/1000]
EN: Dr. D N gupta addresses the lack of awareness surrounding Vitamin D deficiency.
MNI: ভিটামিন দি দিফিসিএন্সিগী মতাংদা মীৎয়েং লৈতবা অদু দা. দি.এন. গুপ্তা ফোংদোকখি।
--------------------------------------------------

Translating MNI: 100%|██████████████████████▉| 998/1000 [09:09<00:01,  1.53it/s]

[998/1000]
EN: Oncologist shares case of non-tobacco related cancer in 21-year-old man with ‘sharp teeth,’ says ‘It could have been identified’
MNI: ওঙ্কোলোজিস্তনা চহি ২১ শুরবা শর্প দেন্ত লৈবা নুপা অমদা মৈখু নত্তনা ক্যান্সরগা মরি লৈনবা কেস অমা শন্দোক্না তাক্লি ।
--------------------------------------------------

Translating MNI: 100%|██████████████████████▉| 999/1000 [09:09<00:00,  1.52it/s]

[999/1000]
EN: Nutritionist says pineapple and cinnamon may help reduce period cramps naturally
MNI: ন্যুত্রিসনিষ্টনা হায়, এনিয়াপল অমসুং সিনেমোননা মহৌশাগী মওংদা পেরিওদ ক্রাম্প হন্থহনবদা মতেং পাংই ।
--------------------------------------------------

Translating MNI: 100%|██████████████████████| 1000/1000 [09:10<00:00,  1.82it/s]

[1000/1000]
EN: Don’t brush before bed? Your heart might pay the price
MNI: তুমদ্রিঙৈদা ব্রশ তৌরোইদবনি ।
--------------------------------------------------

✅ Translation saved to: /home/dingku/Desktop/translated_manipuri.txt

🎉 All translations completed successfully!

In [2]:
#Finetuned IT2 1B

In [3]:
pip install transformers datasets peft pandas openpyxl accelerate bitsandbytes

Requirement already satisfied: transformers in ./lib/python3.12/site-packages (5.12.0)
Requirement already satisfied: datasets in ./lib/python3.12/site-packages (2.16.1)
Requirement already satisfied: peft in ./lib/python3.12/site-packages (0.7.1)
Requirement already satisfied: pandas in ./lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: openpyxl in ./lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: accelerate in ./lib/python3.12/site-packages (0.25.0)
Requirement already satisfied: bitsandbytes in ./lib/python3.12/site-packages (0.49.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in ./lib/python3.12/site-packages (from transformers) (1.19.0)
Requirement already satisfied: numpy>=1.17 in ./lib/python3.12/site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in ./lib/python3.12/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in ./lib/python3.12/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in ./lib/python3.12/site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./lib/python3.12/site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in ./lib/python3.12/site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in ./lib/python3.12/site-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.60 in ./lib/python3.12/site-packages (from transformers) (4.67.1)
Requirement already satisfied: filelock in ./lib/python3.12/site-packages (from datasets) (3.18.0)
Requirement already satisfied: pyarrow>=8.0.0 in ./lib/python3.12/site-packages (from datasets) (20.0.0)
Requirement already satisfied: pyarrow-hotfix in ./lib/python3.12/site-packages (from datasets) (0.7)
Requirement already satisfied: dill<0.3.8,>=0.3.0 in ./lib/python3.12/site-packages (from datasets) (0.3.7)
Requirement already satisfied: requests>=2.19.0 in ./lib/python3.12/site-packages (from datasets) (2.32.3)
Requirement already satisfied: xxhash in ./lib/python3.12/site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess in ./lib/python3.12/site-packages (from datasets) (0.70.15)
Requirement already satisfied: fsspec<=2023.10.0,>=2023.1.0 in ./lib/python3.12/site-packages (from fsspec[http]<=2023.10.0,>=2023.1.0->datasets) (2023.10.0)
Requirement already satisfied: aiohttp in ./lib/python3.12/site-packages (from datasets) (3.12.0)
Requirement already satisfied: psutil in ./lib/python3.12/site-packages (from peft) (7.0.0)
Requirement already satisfied: torch>=1.13.0 in ./lib/python3.12/site-packages (from peft) (2.4.0+cu124)
Requirement already satisfied: python-dateutil>=2.8.2 in ./lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in ./lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./lib/python3.12/site-packages (from aiohttp->datasets) (6.4.4)
Requirement already satisfied: propcache>=0.2.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.20.0)
Requirement already satisfied: click>=8.4.0 in ./lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in ./lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in ./lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in ./lib/python3.12/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.13.2)
Requirement already satisfied: six>=1.5 in ./lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (2025.4.26)
Requirement already satisfied: sympy in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (3.4.2)
Requirement already satisfied: jinja2 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: setuptools in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (80.8.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (12.4.99)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (12.4.99)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (12.4.99)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.2.65 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (12.4.2.65)
Requirement already satisfied: nvidia-cufft-cu12==11.2.0.44 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (11.2.0.44)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.119 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (10.3.5.119)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.0.99 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (11.6.0.99)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.0.142 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (12.3.0.142)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (12.4.99)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (12.4.99)
Requirement already satisfied: triton==3.0.0 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft) (3.0.0)
Requirement already satisfied: shellingham>=1.3.0 in ./lib/python3.12/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in ./lib/python3.12/site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in ./lib/python3.12/site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in ./lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.9.0)
Requirement already satisfied: httpcore==1.* in ./lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers) (2.19.1)
Requirement already satisfied: MarkupSafe>=2.0 in ./lib/python3.12/site-packages (from jinja2->torch>=1.13.0->peft) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./lib/python3.12/site-packages (from sympy->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in ./lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: sniffio>=1.1 in ./lib/python3.12/site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.1)
DEPRECATION: omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of omegaconf or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Note: you may need to restart the kernel to use updated packages.

In [3]:
import subprocess, sys

def run(cmd):
    subprocess.check_call(cmd)

# Upgrade pip
run([sys.executable, "-m", "pip", "install", "--upgrade", "pip"])

# Uninstall conflicting packages
run([sys.executable, "-m", "pip", "uninstall", "-y", "transformers", "tokenizers", "accelerate", "peft"])

# First install a tokenizers version that has a prebuilt wheel for Python 3.12
run([sys.executable, "-m", "pip", "install", "tokenizers==0.15.1", "--only-binary=:all:"])

# Now install transformers 4.36.0 (uses the already installed tokenizers)
run([sys.executable, "-m", "pip", "install", "transformers==4.36.0"])

# Other required packages
run([sys.executable, "-m", "pip", "install", "accelerate==0.25.0"])
run([sys.executable, "-m", "pip", "install", "sentencepiece"])
run([sys.executable, "-m", "pip", "install", "peft==0.7.0"])
run([sys.executable, "-m", "pip", "install", "datasets"])
run([sys.executable, "-m", "pip", "install", "pandas", "openpyxl"])

print("✅ All packages installed. Please restart the kernel (Kernel → Restart) and then run the training script.")

Requirement already satisfied: pip in ./lib/python3.12/site-packages (26.1.2)

WARNING: Error parsing dependencies of omegaconf: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
WARNING: Skipping transformers as it is not installed.
WARNING: Skipping tokenizers as it is not installed.
WARNING: Skipping accelerate as it is not installed.

Found existing installation: peft 0.4.0
Uninstalling peft-0.4.0:
  Successfully uninstalled peft-0.4.0
Collecting tokenizers==0.15.1
  Downloading tokenizers-0.15.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: huggingface_hub<1.0,>=0.16.4 in ./lib/python3.12/site-packages (from tokenizers==0.15.1) (0.36.2)
Requirement already satisfied: filelock in ./lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers==0.15.1) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in ./lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers==0.15.1) (2023.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers==0.15.1) (1.5.1)
Requirement already satisfied: packaging>=20.9 in ./lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers==0.15.1) (25.0)
Requirement already satisfied: pyyaml>=5.1 in ./lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers==0.15.1) (6.0.2)
Requirement already satisfied: requests in ./lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers==0.15.1) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in ./lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers==0.15.1) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./lib/python3.12/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers==0.15.1) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib/python3.12/site-packages (from requests->huggingface_hub<1.0,>=0.16.4->tokenizers==0.15.1) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.12/site-packages (from requests->huggingface_hub<1.0,>=0.16.4->tokenizers==0.15.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./lib/python3.12/site-packages (from requests->huggingface_hub<1.0,>=0.16.4->tokenizers==0.15.1) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.12/site-packages (from requests->huggingface_hub<1.0,>=0.16.4->tokenizers==0.15.1) (2025.4.26)
Downloading tokenizers-0.15.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 4.3 MB/s  0:00:00m 5.2 MB/s eta 0:00:01

WARNING: Error parsing dependencies of omegaconf: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^

Installing collected packages: tokenizers
Successfully installed tokenizers-0.15.1
Collecting transformers==4.36.0
  Using cached transformers-4.36.0-py3-none-any.whl.metadata (126 kB)
Requirement already satisfied: filelock in ./lib/python3.12/site-packages (from transformers==4.36.0) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in ./lib/python3.12/site-packages (from transformers==4.36.0) (0.36.2)
Requirement already satisfied: numpy>=1.17 in ./lib/python3.12/site-packages (from transformers==4.36.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in ./lib/python3.12/site-packages (from transformers==4.36.0) (25.0)
Requirement already satisfied: pyyaml>=5.1 in ./lib/python3.12/site-packages (from transformers==4.36.0) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in ./lib/python3.12/site-packages (from transformers==4.36.0) (2026.5.9)
Requirement already satisfied: requests in ./lib/python3.12/site-packages (from transformers==4.36.0) (2.32.3)
Requirement already satisfied: tokenizers<0.19,>=0.14 in ./lib/python3.12/site-packages (from transformers==4.36.0) (0.15.1)
Requirement already satisfied: safetensors>=0.3.1 in ./lib/python3.12/site-packages (from transformers==4.36.0) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in ./lib/python3.12/site-packages (from transformers==4.36.0) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in ./lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.0) (2023.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.0) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.0) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib/python3.12/site-packages (from requests->transformers==4.36.0) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.12/site-packages (from requests->transformers==4.36.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./lib/python3.12/site-packages (from requests->transformers==4.36.0) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.12/site-packages (from requests->transformers==4.36.0) (2025.4.26)
Using cached transformers-4.36.0-py3-none-any.whl (8.2 MB)

WARNING: Error parsing dependencies of omegaconf: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^

Installing collected packages: transformers

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
unbabel-comet 2.2.6 requires protobuf<5.0.0,>=4.24.4, but you have protobuf 5.29.2 which is incompatible.
unbabel-comet 2.2.6 requires sentencepiece<0.3.0,>=0.2.0, but you have sentencepiece 0.1.99 which is incompatible.

Successfully installed transformers-4.36.0
Collecting accelerate==0.25.0
  Using cached accelerate-0.25.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: numpy>=1.17 in ./lib/python3.12/site-packages (from accelerate==0.25.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in ./lib/python3.12/site-packages (from accelerate==0.25.0) (25.0)
Requirement already satisfied: psutil in ./lib/python3.12/site-packages (from accelerate==0.25.0) (7.0.0)
Requirement already satisfied: pyyaml in ./lib/python3.12/site-packages (from accelerate==0.25.0) (6.0.2)
Requirement already satisfied: torch>=1.10.0 in ./lib/python3.12/site-packages (from accelerate==0.25.0) (2.4.0+cu124)
Requirement already satisfied: huggingface-hub in ./lib/python3.12/site-packages (from accelerate==0.25.0) (0.36.2)
Requirement already satisfied: safetensors>=0.3.1 in ./lib/python3.12/site-packages (from accelerate==0.25.0) (0.5.3)
Requirement already satisfied: filelock in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (3.18.0)
Requirement already satisfied: typing-extensions>=4.8.0 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (4.13.2)
Requirement already satisfied: sympy in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (1.14.0)
Requirement already satisfied: networkx in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (3.4.2)
Requirement already satisfied: jinja2 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (3.1.6)
Requirement already satisfied: fsspec in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (2023.10.0)
Requirement already satisfied: setuptools in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (80.8.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (12.4.99)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (12.4.99)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (12.4.99)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.2.65 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (12.4.2.65)
Requirement already satisfied: nvidia-cufft-cu12==11.2.0.44 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (11.2.0.44)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.119 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (10.3.5.119)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.0.99 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (11.6.0.99)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.0.142 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (12.3.0.142)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (12.4.99)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (12.4.99)
Requirement already satisfied: triton==3.0.0 in ./lib/python3.12/site-packages (from torch>=1.10.0->accelerate==0.25.0) (3.0.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./lib/python3.12/site-packages (from huggingface-hub->accelerate==0.25.0) (1.5.1)
Requirement already satisfied: requests in ./lib/python3.12/site-packages (from huggingface-hub->accelerate==0.25.0) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in ./lib/python3.12/site-packages (from huggingface-hub->accelerate==0.25.0) (4.67.1)
Requirement already satisfied: MarkupSafe>=2.0 in ./lib/python3.12/site-packages (from jinja2->torch>=1.10.0->accelerate==0.25.0) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib/python3.12/site-packages (from requests->huggingface-hub->accelerate==0.25.0) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.12/site-packages (from requests->huggingface-hub->accelerate==0.25.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./lib/python3.12/site-packages (from requests->huggingface-hub->accelerate==0.25.0) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.12/site-packages (from requests->huggingface-hub->accelerate==0.25.0) (2025.4.26)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./lib/python3.12/site-packages (from sympy->torch>=1.10.0->accelerate==0.25.0) (1.3.0)
Using cached accelerate-0.25.0-py3-none-any.whl (265 kB)

WARNING: Error parsing dependencies of omegaconf: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^

Installing collected packages: accelerate
Successfully installed accelerate-0.25.0
Requirement already satisfied: sentencepiece in ./lib/python3.12/site-packages (0.1.99)

WARNING: Error parsing dependencies of omegaconf: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^

Collecting peft==0.7.0
  Downloading peft-0.7.0-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: numpy>=1.17 in ./lib/python3.12/site-packages (from peft==0.7.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in ./lib/python3.12/site-packages (from peft==0.7.0) (25.0)
Requirement already satisfied: psutil in ./lib/python3.12/site-packages (from peft==0.7.0) (7.0.0)
Requirement already satisfied: pyyaml in ./lib/python3.12/site-packages (from peft==0.7.0) (6.0.2)
Requirement already satisfied: torch>=1.13.0 in ./lib/python3.12/site-packages (from peft==0.7.0) (2.4.0+cu124)
Requirement already satisfied: transformers in ./lib/python3.12/site-packages (from peft==0.7.0) (4.36.0)
Requirement already satisfied: tqdm in ./lib/python3.12/site-packages (from peft==0.7.0) (4.67.1)
Requirement already satisfied: accelerate>=0.21.0 in ./lib/python3.12/site-packages (from peft==0.7.0) (0.25.0)
Requirement already satisfied: safetensors in ./lib/python3.12/site-packages (from peft==0.7.0) (0.5.3)
Requirement already satisfied: huggingface-hub>=0.17.0 in ./lib/python3.12/site-packages (from peft==0.7.0) (0.36.2)
Requirement already satisfied: filelock in ./lib/python3.12/site-packages (from huggingface-hub>=0.17.0->peft==0.7.0) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in ./lib/python3.12/site-packages (from huggingface-hub>=0.17.0->peft==0.7.0) (2023.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./lib/python3.12/site-packages (from huggingface-hub>=0.17.0->peft==0.7.0) (1.5.1)
Requirement already satisfied: requests in ./lib/python3.12/site-packages (from huggingface-hub>=0.17.0->peft==0.7.0) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./lib/python3.12/site-packages (from huggingface-hub>=0.17.0->peft==0.7.0) (4.13.2)
Requirement already satisfied: sympy in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (1.14.0)
Requirement already satisfied: networkx in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (3.4.2)
Requirement already satisfied: jinja2 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (3.1.6)
Requirement already satisfied: setuptools in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (80.8.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (12.4.99)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (12.4.99)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (12.4.99)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.2.65 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (12.4.2.65)
Requirement already satisfied: nvidia-cufft-cu12==11.2.0.44 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (11.2.0.44)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.119 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (10.3.5.119)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.0.99 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (11.6.0.99)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.0.142 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (12.3.0.142)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (12.4.99)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (12.4.99)
Requirement already satisfied: triton==3.0.0 in ./lib/python3.12/site-packages (from torch>=1.13.0->peft==0.7.0) (3.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./lib/python3.12/site-packages (from jinja2->torch>=1.13.0->peft==0.7.0) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib/python3.12/site-packages (from requests->huggingface-hub>=0.17.0->peft==0.7.0) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.12/site-packages (from requests->huggingface-hub>=0.17.0->peft==0.7.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./lib/python3.12/site-packages (from requests->huggingface-hub>=0.17.0->peft==0.7.0) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.12/site-packages (from requests->huggingface-hub>=0.17.0->peft==0.7.0) (2025.4.26)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./lib/python3.12/site-packages (from sympy->torch>=1.13.0->peft==0.7.0) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in ./lib/python3.12/site-packages (from transformers->peft==0.7.0) (2026.5.9)
Requirement already satisfied: tokenizers<0.19,>=0.14 in ./lib/python3.12/site-packages (from transformers->peft==0.7.0) (0.15.1)
Downloading peft-0.7.0-py3-none-any.whl (168 kB)

WARNING: Error parsing dependencies of omegaconf: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^

Installing collected packages: peft
Successfully installed peft-0.7.0
Requirement already satisfied: datasets in ./lib/python3.12/site-packages (2.12.0)
Requirement already satisfied: numpy>=1.17 in ./lib/python3.12/site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=8.0.0 in ./lib/python3.12/site-packages (from datasets) (20.0.0)
Requirement already satisfied: dill<0.3.7,>=0.3.0 in ./lib/python3.12/site-packages (from datasets) (0.3.6)
Requirement already satisfied: pandas in ./lib/python3.12/site-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in ./lib/python3.12/site-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in ./lib/python3.12/site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in ./lib/python3.12/site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess in ./lib/python3.12/site-packages (from datasets) (0.70.14)
Requirement already satisfied: fsspec>=2021.11.1 in ./lib/python3.12/site-packages (from fsspec[http]>=2021.11.1->datasets) (2023.10.0)
Requirement already satisfied: aiohttp in ./lib/python3.12/site-packages (from datasets) (3.12.0)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.11.0 in ./lib/python3.12/site-packages (from datasets) (0.36.2)
Requirement already satisfied: packaging in ./lib/python3.12/site-packages (from datasets) (25.0)
Requirement already satisfied: responses<0.19 in ./lib/python3.12/site-packages (from datasets) (0.18.0)
Requirement already satisfied: pyyaml>=5.1 in ./lib/python3.12/site-packages (from datasets) (6.0.2)
Requirement already satisfied: filelock in ./lib/python3.12/site-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (3.18.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./lib/python3.12/site-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./lib/python3.12/site-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (4.13.2)
Requirement already satisfied: urllib3>=1.25.10 in ./lib/python3.12/site-packages (from responses<0.19->datasets) (2.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.12/site-packages (from requests>=2.19.0->datasets) (2025.4.26)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./lib/python3.12/site-packages (from aiohttp->datasets) (6.4.4)
Requirement already satisfied: propcache>=0.2.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.20.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./lib/python3.12/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./lib/python3.12/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./lib/python3.12/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in ./lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

WARNING: Error parsing dependencies of omegaconf: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^

Requirement already satisfied: pandas in ./lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: openpyxl in ./lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in ./lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in ./lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in ./lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
✅ All packages installed. Please restart the kernel (Kernel → Restart) and then run the training script.

WARNING: Error parsing dependencies of omegaconf: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^

In [3]:
pip install torch transformers datasets pandas openpyxl tqdm peft accelerate

Requirement already satisfied: torch in ./lib/python3.12/site-packages (2.4.0+cu124)
Requirement already satisfied: transformers in ./lib/python3.12/site-packages (4.36.0)
Requirement already satisfied: datasets in ./lib/python3.12/site-packages (2.12.0)
Requirement already satisfied: pandas in ./lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: openpyxl in ./lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: tqdm in ./lib/python3.12/site-packages (4.67.1)
Requirement already satisfied: peft in ./lib/python3.12/site-packages (0.7.0)
Requirement already satisfied: accelerate in ./lib/python3.12/site-packages (0.25.0)
Requirement already satisfied: filelock in ./lib/python3.12/site-packages (from torch) (3.18.0)
Requirement already satisfied: typing-extensions>=4.8.0 in ./lib/python3.12/site-packages (from torch) (4.13.2)
Requirement already satisfied: sympy in ./lib/python3.12/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx in ./lib/python3.12/site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in ./lib/python3.12/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in ./lib/python3.12/site-packages (from torch) (2023.10.0)
Requirement already satisfied: setuptools in ./lib/python3.12/site-packages (from torch) (80.8.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in ./lib/python3.12/site-packages (from torch) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.2.65 in ./lib/python3.12/site-packages (from torch) (12.4.2.65)
Requirement already satisfied: nvidia-cufft-cu12==11.2.0.44 in ./lib/python3.12/site-packages (from torch) (11.2.0.44)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.119 in ./lib/python3.12/site-packages (from torch) (10.3.5.119)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.0.99 in ./lib/python3.12/site-packages (from torch) (11.6.0.99)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.0.142 in ./lib/python3.12/site-packages (from torch) (12.3.0.142)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in ./lib/python3.12/site-packages (from torch) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.99 in ./lib/python3.12/site-packages (from torch) (12.4.99)
Requirement already satisfied: triton==3.0.0 in ./lib/python3.12/site-packages (from torch) (3.0.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in ./lib/python3.12/site-packages (from transformers) (0.36.2)
Requirement already satisfied: numpy>=1.17 in ./lib/python3.12/site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in ./lib/python3.12/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in ./lib/python3.12/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in ./lib/python3.12/site-packages (from transformers) (2026.5.9)
Requirement already satisfied: requests in ./lib/python3.12/site-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.19,>=0.14 in ./lib/python3.12/site-packages (from transformers) (0.15.1)
Requirement already satisfied: safetensors>=0.3.1 in ./lib/python3.12/site-packages (from transformers) (0.5.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.19.3->transformers) (1.5.1)
Requirement already satisfied: pyarrow>=8.0.0 in ./lib/python3.12/site-packages (from datasets) (20.0.0)
Requirement already satisfied: dill<0.3.7,>=0.3.0 in ./lib/python3.12/site-packages (from datasets) (0.3.6)
Requirement already satisfied: xxhash in ./lib/python3.12/site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess in ./lib/python3.12/site-packages (from datasets) (0.70.14)
Requirement already satisfied: aiohttp in ./lib/python3.12/site-packages (from datasets) (3.12.0)
Requirement already satisfied: responses<0.19 in ./lib/python3.12/site-packages (from datasets) (0.18.0)
Requirement already satisfied: urllib3>=1.25.10 in ./lib/python3.12/site-packages (from responses<0.19->datasets) (2.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib/python3.12/site-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.12/site-packages (from requests->transformers) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.12/site-packages (from requests->transformers) (2025.4.26)
Requirement already satisfied: python-dateutil>=2.8.2 in ./lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in ./lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: psutil in ./lib/python3.12/site-packages (from peft) (7.0.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./lib/python3.12/site-packages (from aiohttp->datasets) (6.4.4)
Requirement already satisfied: propcache>=0.2.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./lib/python3.12/site-packages (from aiohttp->datasets) (1.20.0)
Requirement already satisfied: six>=1.5 in ./lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./lib/python3.12/site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./lib/python3.12/site-packages (from sympy->torch) (1.3.0)
WARNING: Error parsing dependencies of omegaconf: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Note: you may need to restart the kernel to use updated packages.

In [4]:
#!/usr/bin/env python3

#Convert Excel training files into the official IndicTrans2 folder structure: en-indic-exp/

import os
import pandas as pd

BASE_DIR = "/home/dingku/Desktop/en-indic-exp"
TRAIN_DIR = os.path.join(BASE_DIR, "train")
DEV_DIR   = os.path.join(BASE_DIR, "dev")
os.makedirs(TRAIN_DIR, exist_ok=True)
os.makedirs(DEV_DIR, exist_ok=True)

# Map language codes to target folders and column names
LANG_CONFIG = {
    "asm_Beng": {
        "file": "/home/dingku/Desktop/WMT26/WMT26/Cat1/English-AssameseTrainingData2026.xlsx",
        "en_col": "en",
        "tgt_col": "as",
        "folder": "eng_Latn-asm_Beng"
    },
    "mni_Beng": {
        "file": "/home/dingku/Desktop/WMT26/WMT26/Cat1/English-ManipuriTrainingData2026.xlsx",
        "en_col": "en",
        "tgt_col": "mni",
        "folder": "eng_Latn-mni_Beng"
    },
    "mni_Mtei": {
        "file": "/home/dingku/Desktop/WMT26/WMT26/Cat1/English-Meitei-MayekTransiningData2026.xlsx",
        "en_col": "en",
        "tgt_col": "mtei",
        "folder": "eng_Latn-mni_Mtei"
    },
    "brx_Deva": {
        "file": "/home/dingku/Desktop/WMT26/WMT26/Cat2/English-BodoTrainingData2026.xlsx",
        "en_col": "en",
        "tgt_col": "bo",
        "folder": "eng_Latn-brx_Deva"
    }
}

for lang, cfg in LANG_CONFIG.items():
    print(f"Processing {lang} ...")
    df = pd.read_excel(cfg["file"])
    en_sentences = df[cfg["en_col"]].astype(str).tolist()
    tgt_sentences = df[cfg["tgt_col"]].astype(str).tolist()

    # Remove empty rows
    pairs = [(e, t) for e, t in zip(en_sentences, tgt_sentences) if e.strip() and t.strip()]
    print(f"  Total valid pairs: {len(pairs)}")

    # Create folder for this language pair
    folder_path = os.path.join(TRAIN_DIR, cfg["folder"])
    os.makedirs(folder_path, exist_ok=True)

    # Write English sentences (train.eng_Latn)
    en_path = os.path.join(folder_path, "train.eng_Latn")
    with open(en_path, "w", encoding="utf-8") as f:
        for e, _ in pairs:
            f.write(e + "\n")

    # Write target sentences (train.<tgt_lang>)
    tgt_path = os.path.join(folder_path, f"train.{lang}")
    with open(tgt_path, "w", encoding="utf-8") as f:
        for _, t in pairs:
            f.write(t + "\n")

    print(f"  ✅ Saved to {folder_path}")

print("\n🎉 All files created. You can now use the official IndicTrans2 training script.")

Processing asm_Beng ...
  Total valid pairs: 54000
  ✅ Saved to /home/dingku/Desktop/en-indic-exp/train/eng_Latn-asm_Beng
Processing mni_Beng ...
  Total valid pairs: 23687
  ✅ Saved to /home/dingku/Desktop/en-indic-exp/train/eng_Latn-mni_Beng
Processing mni_Mtei ...
  Total valid pairs: 17000
  ✅ Saved to /home/dingku/Desktop/en-indic-exp/train/eng_Latn-mni_Mtei
Processing brx_Deva ...
  Total valid pairs: 15215
  ✅ Saved to /home/dingku/Desktop/en-indic-exp/train/eng_Latn-brx_Deva

🎉 All files created. You can now use the official IndicTrans2 training script.

In [1]:
#!/usr/bin/env python3

#Fine‑tune IndicTrans2 (1.1B) with LoRA for English‑Assamese, English‑Manipuri (Bengali & Meitei Mayek), English‑Bodo.
#Fixed AMP error: use float32 (or fp16) instead of bfloat16.
#Shows real‑time progress and estimated remaining time.

import os
import time
from datetime import timedelta
import torch
from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    DataCollatorForSeq2Seq
)
from peft import LoraConfig, get_peft_model, TaskType
from datasets import Dataset, DatasetDict
from tqdm.auto import tqdm
from transformers.trainer_callback import TrainerCallback

# ============================================================
# CONFIGURATION
# ============================================================

DATA_ROOT = "/home/dingku/Desktop/en-indic-exp"
LANG_PAIRS = [
    "eng_Latn-asm_Beng",
    "eng_Latn-mni_Beng",
    "eng_Latn-mni_Mtei",
    "eng_Latn-brx_Deva"
]

BASE_MODEL = "ai4bharat/indictrans2-en-indic-1B"
OUTPUT_BASE = "/home/dingku/Desktop/FTIT26"

# LoRA hyperparameters
LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.1
LORA_TARGET_MODULES = ["q_proj", "k_proj"]

# Training hyperparameters
BATCH_SIZE = 2
GRAD_ACCUM = 4
LEARNING_RATE = 2e-4
EPOCHS = 3
MAX_LENGTH = 512
EVAL_STEPS = 500
SAVE_STEPS = 500
LOGGING_STEPS = 50

# Mixed precision: set to True for fp16 (faster), False for float32 (stable)
USE_FP16 = False   # Change to True if your GPU supports fp16 and you want speed
USE_BF16 = False   # Keep False to avoid the scaler error

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


# ============================================================
# CUSTOM CALLBACK FOR REMAINING TIME
# ============================================================
class TimeEstimateCallback(TrainerCallback):
    def __init__(self):
        self.start_time = time.time()

    def on_step_end(self, args, state, control, **kwargs):
        if state.global_step % 50 == 0:
            elapsed = time.time() - self.start_time
            steps_done = state.global_step
            if steps_done > 0:
                time_per_step = elapsed / steps_done
                steps_remaining = state.max_steps - steps_done
                eta = timedelta(seconds=int(time_per_step * steps_remaining))
                tqdm.write(
                    f"Step {steps_done}/{state.max_steps}  |  "
                    f"Elapsed: {timedelta(seconds=int(elapsed))}  |  "
                    f"ETA: {eta}"
                )


# ============================================================
# DATA LOADER
# ============================================================
def load_data_for_pair(pair_name):
    train_dir = os.path.join(DATA_ROOT, "train", pair_name)
    dev_dir   = os.path.join(DATA_ROOT, "dev", pair_name)

    src_lang, tgt_lang = pair_name.split("-")

    # Load training files
    with open(os.path.join(train_dir, f"train.{src_lang}"), "r", encoding="utf-8") as f:
        src_lines = [line.strip() for line in f if line.strip()]
    with open(os.path.join(train_dir, f"train.{tgt_lang}"), "r", encoding="utf-8") as f:
        tgt_lines = [line.strip() for line in f if line.strip()]

    assert len(src_lines) == len(tgt_lines), "Mismatch in training data"
    train_data = [{"en": s, "tgt": t} for s, t in zip(src_lines, tgt_lines)]

    # Load or split dev data
    if os.path.exists(dev_dir):
        with open(os.path.join(dev_dir, f"dev.{src_lang}"), "r", encoding="utf-8") as f:
            dev_src = [line.strip() for line in f if line.strip()]
        with open(os.path.join(dev_dir, f"dev.{tgt_lang}"), "r", encoding="utf-8") as f:
            dev_tgt = [line.strip() for line in f if line.strip()]
        dev_data = [{"en": s, "tgt": t} for s, t in zip(dev_src, dev_tgt)]
    else:
        split = int(len(train_data) * 0.9)
        dev_data = train_data[split:]
        train_data = train_data[:split]

    print(f"  Train samples: {len(train_data):,}  |  Dev samples: {len(dev_data):,}")
    return DatasetDict({
        "train": Dataset.from_list(train_data),
        "validation": Dataset.from_list(dev_data)
    })


# ============================================================
# TOKENIZE FUNCTION (FIXED FOR INDICTRANS2)
# ============================================================
def preprocess_function(examples, tokenizer, src_lang, tgt_lang):
    """
    Encoder input:   f"{src_lang} {tgt_lang} {sentence}"
    Decoder input:   f"{tgt_lang} {translation}"  (as text_target)
    """
    inputs = [f"{src_lang} {tgt_lang} {ex}" for ex in examples["en"]]
    targets = [f"{tgt_lang} {ex}" for ex in examples["tgt"]]

    model_inputs = tokenizer(
        inputs, max_length=MAX_LENGTH, truncation=True, padding=False
    )
    # Use text_target argument (modern way, avoids deprecated as_target_tokenizer)
    labels = tokenizer(
        text_target=targets, max_length=MAX_LENGTH, truncation=True, padding=False
    )
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs


# ============================================================
# FINE‑TUNING FUNCTION
# ============================================================
def fine_tune_pair(pair_name):
    print("\n" + "=" * 70)
    print(f"🚀 Fine‑tuning for {pair_name}")
    print("=" * 70)

    # 1. Prepare dataset
    dataset = load_data_for_pair(pair_name)

    # 2. Load tokenizer and base model (float32 to avoid bfloat16 scaler issues)
    print("\n📥 Loading tokenizer and base model...")
    tokenizer = AutoTokenizer.from_pretrained(
        BASE_MODEL,
        trust_remote_code=True,
        use_fast=True
    )
    model = AutoModelForSeq2SeqLM.from_pretrained(
        BASE_MODEL,
        trust_remote_code=True,
        torch_dtype=torch.float32   # Use float32 (stable)
    )
    # Enable gradient checkpointing to save memory
    model.gradient_checkpointing_enable()
    model.to(device)

    # 3. Add LoRA adapters
    print("🔧 Adding LoRA adapters...")
    lora_config = LoraConfig(
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        target_modules=LORA_TARGET_MODULES,
        lora_dropout=LORA_DROPOUT,
        bias="none",
        task_type=TaskType.SEQ_2_SEQ_LM,
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    # 4. Tokenize datasets
    print("\n📝 Tokenizing datasets...")
    src_lang, tgt_lang = pair_name.split("-")
    tokenized_ds = dataset.map(
        lambda x: preprocess_function(x, tokenizer, src_lang, tgt_lang),
        batched=True,
        remove_columns=dataset["train"].column_names,
    )

    # 5. Data collator
    data_collator = DataCollatorForSeq2Seq(
        tokenizer, model=model, padding=True
    )

    # 6. Training arguments
    output_dir = os.path.join(OUTPUT_BASE, pair_name)
    os.makedirs(output_dir, exist_ok=True)

    training_args = Seq2SeqTrainingArguments(
        output_dir=output_dir,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRAD_ACCUM,
        learning_rate=LEARNING_RATE,
        num_train_epochs=EPOCHS,
        evaluation_strategy="steps",
        eval_steps=EVAL_STEPS,
        save_steps=SAVE_STEPS,
        logging_steps=LOGGING_STEPS,
        report_to="none",                # disable wandb / tensorboard
        predict_with_generate=True,
        generation_max_length=MAX_LENGTH,
        fp16=USE_FP16,
        bf16=USE_BF16,
        push_to_hub=False,
        save_total_limit=2,
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
    )

    # 7. Trainer with time‑estimate callback
    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_ds["train"],
        eval_dataset=tokenized_ds["validation"],
        data_collator=data_collator,
        tokenizer=tokenizer,
        callbacks=[TimeEstimateCallback()],
    )

    # 8. Train
    print("\n🏋️ Starting training...\n")
    trainer.train()

    # 9. Save the final LoRA adapter
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    print(f"\n✅ Model saved to {output_dir}\n")


# ============================================================
# RUN
# ============================================================
if __name__ == "__main__":
    os.makedirs(OUTPUT_BASE, exist_ok=True)

    for pair in LANG_PAIRS:
        fine_tune_pair(pair)

    print("\n🎉 All models have been fine‑tuned successfully!")

/home/dingku/jupyter_env/lib/python3.12/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.4.0) or chardet (7.4.3)/charset_normalizer (3.4.2) doesn't match a supported version!
  warnings.warn(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(

Using device: cuda

======================================================================
🚀 Fine‑tuning for eng_Latn-asm_Beng
======================================================================
  Train samples: 48,600  |  Dev samples: 5,400

📥 Loading tokenizer and base model...

/home/dingku/jupyter_env/lib/python3.12/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.

🔧 Adding LoRA adapters...
trainable params: 3,538,944 || all params: 1,119,082,496 || trainable%: 0.3162362035550952

📝 Tokenizing datasets...

Map:   0%|          | 0/48600 [00:00<?, ? examples/s]

Map:   0%|          | 0/5400 [00:00<?, ? examples/s]

🏋️ Starting training...

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 50/18225  |  Elapsed: 0:00:47  |  ETA: 4:50:14
Step 100/18225  |  Elapsed: 0:01:34  |  ETA: 4:46:58
Step 150/18225  |  Elapsed: 0:02:21  |  ETA: 4:44:41
Step 200/18225  |  Elapsed: 0:03:09  |  ETA: 4:44:40
Step 250/18225  |  Elapsed: 0:04:00  |  ETA: 4:48:05
Step 300/18225  |  Elapsed: 0:04:52  |  ETA: 4:50:53
Step 350/18225  |  Elapsed: 0:05:40  |  ETA: 4:49:37
Step 400/18225  |  Elapsed: 0:06:28  |  ETA: 4:48:14
Step 450/18225  |  Elapsed: 0:07:16  |  ETA: 4:47:08
Step 500/18225  |  Elapsed: 0:08:03  |  ETA: 4:45:54

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 550/18225  |  Elapsed: 0:12:04  |  ETA: 6:28:10
Step 600/18225  |  Elapsed: 0:12:54  |  ETA: 6:19:06
Step 650/18225  |  Elapsed: 0:13:43  |  ETA: 6:10:55
Step 700/18225  |  Elapsed: 0:14:30  |  ETA: 6:03:15
Step 750/18225  |  Elapsed: 0:15:18  |  ETA: 5:56:39
Step 800/18225  |  Elapsed: 0:16:06  |  ETA: 5:51:00
Step 850/18225  |  Elapsed: 0:16:54  |  ETA: 5:45:44
Step 900/18225  |  Elapsed: 0:17:43  |  ETA: 5:41:05
Step 950/18225  |  Elapsed: 0:18:31  |  ETA: 5:36:59
Step 1000/18225  |  Elapsed: 0:19:19  |  ETA: 5:32:50

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 1050/18225  |  Elapsed: 0:23:25  |  ETA: 6:23:10
Step 1100/18225  |  Elapsed: 0:24:12  |  ETA: 6:16:50
Step 1150/18225  |  Elapsed: 0:25:00  |  ETA: 6:11:12
Step 1200/18225  |  Elapsed: 0:25:47  |  ETA: 6:05:58
Step 1250/18225  |  Elapsed: 0:26:34  |  ETA: 6:00:54
Step 1300/18225  |  Elapsed: 0:27:23  |  ETA: 5:56:34
Step 1350/18225  |  Elapsed: 0:28:11  |  ETA: 5:52:22
Step 1400/18225  |  Elapsed: 0:28:59  |  ETA: 5:48:23
Step 1450/18225  |  Elapsed: 0:29:46  |  ETA: 5:44:33
Step 1500/18225  |  Elapsed: 0:30:34  |  ETA: 5:40:59

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 1550/18225  |  Elapsed: 0:34:35  |  ETA: 6:12:11
Step 1600/18225  |  Elapsed: 0:35:22  |  ETA: 6:07:34
Step 1650/18225  |  Elapsed: 0:36:08  |  ETA: 6:03:08
Step 1700/18225  |  Elapsed: 0:36:55  |  ETA: 5:58:56
Step 1750/18225  |  Elapsed: 0:37:42  |  ETA: 5:55:00
Step 1800/18225  |  Elapsed: 0:38:28  |  ETA: 5:51:04
Step 1850/18225  |  Elapsed: 0:39:14  |  ETA: 5:47:24
Step 1900/18225  |  Elapsed: 0:40:01  |  ETA: 5:43:51
Step 1950/18225  |  Elapsed: 0:40:47  |  ETA: 5:40:27
Step 2000/18225  |  Elapsed: 0:41:34  |  ETA: 5:37:15

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 2050/18225  |  Elapsed: 0:45:29  |  ETA: 5:58:59
Step 2100/18225  |  Elapsed: 0:46:15  |  ETA: 5:55:14
Step 2150/18225  |  Elapsed: 0:47:04  |  ETA: 5:51:58
Step 2200/18225  |  Elapsed: 0:47:54  |  ETA: 5:48:55
Step 2250/18225  |  Elapsed: 0:48:46  |  ETA: 5:46:17
Step 2300/18225  |  Elapsed: 0:49:33  |  ETA: 5:43:04
Step 2350/18225  |  Elapsed: 0:50:22  |  ETA: 5:40:18
Step 2400/18225  |  Elapsed: 0:51:11  |  ETA: 5:37:32
Step 2450/18225  |  Elapsed: 0:52:00  |  ETA: 5:34:53
Step 2500/18225  |  Elapsed: 0:52:47  |  ETA: 5:32:04

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 2550/18225  |  Elapsed: 0:56:42  |  ETA: 5:48:36
Step 2600/18225  |  Elapsed: 0:57:29  |  ETA: 5:45:31
Step 2650/18225  |  Elapsed: 0:58:16  |  ETA: 5:42:27
Step 2700/18225  |  Elapsed: 0:59:02  |  ETA: 5:39:31
Step 2750/18225  |  Elapsed: 0:59:49  |  ETA: 5:36:38
Step 2800/18225  |  Elapsed: 1:00:37  |  ETA: 5:33:56
Step 2850/18225  |  Elapsed: 1:01:25  |  ETA: 5:31:19
Step 2900/18225  |  Elapsed: 1:02:11  |  ETA: 5:28:38
Step 2950/18225  |  Elapsed: 1:02:58  |  ETA: 5:26:05
Step 3000/18225  |  Elapsed: 1:03:45  |  ETA: 5:23:34

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 3050/18225  |  Elapsed: 1:07:42  |  ETA: 5:36:51
Step 3100/18225  |  Elapsed: 1:08:29  |  ETA: 5:34:08
Step 3150/18225  |  Elapsed: 1:09:15  |  ETA: 5:31:26
Step 3200/18225  |  Elapsed: 1:10:02  |  ETA: 5:28:49
Step 3250/18225  |  Elapsed: 1:10:48  |  ETA: 5:26:17
Step 3300/18225  |  Elapsed: 1:11:38  |  ETA: 5:23:59
Step 3350/18225  |  Elapsed: 1:12:28  |  ETA: 5:21:46
Step 3400/18225  |  Elapsed: 1:13:16  |  ETA: 5:19:32
Step 3450/18225  |  Elapsed: 1:14:04  |  ETA: 5:17:16
Step 3500/18225  |  Elapsed: 1:14:52  |  ETA: 5:14:59

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 3550/18225  |  Elapsed: 1:18:47  |  ETA: 5:25:43
Step 3600/18225  |  Elapsed: 1:19:35  |  ETA: 5:23:22
Step 3650/18225  |  Elapsed: 1:20:23  |  ETA: 5:21:02
Step 3700/18225  |  Elapsed: 1:21:11  |  ETA: 5:18:44
Step 3750/18225  |  Elapsed: 1:21:59  |  ETA: 5:16:31
Step 3800/18225  |  Elapsed: 1:22:47  |  ETA: 5:14:15
Step 3850/18225  |  Elapsed: 1:23:34  |  ETA: 5:12:03
Step 3900/18225  |  Elapsed: 1:24:21  |  ETA: 5:09:52
Step 3950/18225  |  Elapsed: 1:25:09  |  ETA: 5:07:44
Step 4000/18225  |  Elapsed: 1:25:58  |  ETA: 5:05:46

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 4050/18225  |  Elapsed: 1:29:57  |  ETA: 5:14:52
Step 4100/18225  |  Elapsed: 1:30:48  |  ETA: 5:12:50
Step 4150/18225  |  Elapsed: 1:31:38  |  ETA: 5:10:50
Step 4200/18225  |  Elapsed: 1:32:29  |  ETA: 5:08:49
Step 4250/18225  |  Elapsed: 1:33:18  |  ETA: 5:06:48
Step 4300/18225  |  Elapsed: 1:34:06  |  ETA: 5:04:44
Step 4350/18225  |  Elapsed: 1:34:52  |  ETA: 5:02:37
Step 4400/18225  |  Elapsed: 1:35:39  |  ETA: 5:00:32
Step 4450/18225  |  Elapsed: 1:36:25  |  ETA: 4:58:30
Step 4500/18225  |  Elapsed: 1:37:12  |  ETA: 4:56:30

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 4550/18225  |  Elapsed: 1:41:08  |  ETA: 5:03:58
Step 4600/18225  |  Elapsed: 1:41:56  |  ETA: 5:01:57
Step 4650/18225  |  Elapsed: 1:42:43  |  ETA: 4:59:52
Step 4700/18225  |  Elapsed: 1:43:30  |  ETA: 4:57:51
Step 4750/18225  |  Elapsed: 1:44:18  |  ETA: 4:55:54
Step 4800/18225  |  Elapsed: 1:45:04  |  ETA: 4:53:54
Step 4850/18225  |  Elapsed: 1:45:51  |  ETA: 4:51:54
Step 4900/18225  |  Elapsed: 1:46:37  |  ETA: 4:49:58
Step 4950/18225  |  Elapsed: 1:47:24  |  ETA: 4:48:02
Step 5000/18225  |  Elapsed: 1:48:10  |  ETA: 4:46:07

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 5050/18225  |  Elapsed: 1:52:09  |  ETA: 4:52:36
Step 5100/18225  |  Elapsed: 1:53:00  |  ETA: 4:50:49
Step 5150/18225  |  Elapsed: 1:53:47  |  ETA: 4:48:53
Step 5200/18225  |  Elapsed: 1:54:34  |  ETA: 4:46:58
Step 5250/18225  |  Elapsed: 1:55:21  |  ETA: 4:45:06
Step 5300/18225  |  Elapsed: 1:56:07  |  ETA: 4:43:12
Step 5350/18225  |  Elapsed: 1:56:54  |  ETA: 4:41:20
Step 5400/18225  |  Elapsed: 1:57:40  |  ETA: 4:39:28
Step 5450/18225  |  Elapsed: 1:58:27  |  ETA: 4:37:40
Step 5500/18225  |  Elapsed: 1:59:14  |  ETA: 4:35:53

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 5550/18225  |  Elapsed: 2:03:10  |  ETA: 4:41:18
Step 5600/18225  |  Elapsed: 2:03:57  |  ETA: 4:39:27
Step 5650/18225  |  Elapsed: 2:04:43  |  ETA: 4:37:36
Step 5700/18225  |  Elapsed: 2:05:29  |  ETA: 4:35:45
Step 5750/18225  |  Elapsed: 2:06:18  |  ETA: 4:34:02
Step 5800/18225  |  Elapsed: 2:07:05  |  ETA: 4:32:15
Step 5850/18225  |  Elapsed: 2:07:51  |  ETA: 4:30:27
Step 5900/18225  |  Elapsed: 2:08:37  |  ETA: 4:28:42
Step 5950/18225  |  Elapsed: 2:09:24  |  ETA: 4:26:59
Step 6000/18225  |  Elapsed: 2:10:11  |  ETA: 4:25:15

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 6050/18225  |  Elapsed: 2:14:07  |  ETA: 4:29:55
Step 6100/18225  |  Elapsed: 2:14:57  |  ETA: 4:28:15
Step 6150/18225  |  Elapsed: 2:15:47  |  ETA: 4:26:36
Step 6200/18225  |  Elapsed: 2:16:35  |  ETA: 4:24:54
Step 6250/18225  |  Elapsed: 2:17:21  |  ETA: 4:23:10
Step 6300/18225  |  Elapsed: 2:18:07  |  ETA: 4:21:27
Step 6350/18225  |  Elapsed: 2:18:54  |  ETA: 4:19:46
Step 6400/18225  |  Elapsed: 2:19:42  |  ETA: 4:18:07
Step 6450/18225  |  Elapsed: 2:20:29  |  ETA: 4:16:28
Step 6500/18225  |  Elapsed: 2:21:16  |  ETA: 4:14:49

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 6550/18225  |  Elapsed: 2:25:13  |  ETA: 4:18:51
Step 6600/18225  |  Elapsed: 2:26:02  |  ETA: 4:17:13
Step 6650/18225  |  Elapsed: 2:26:53  |  ETA: 4:15:40
Step 6700/18225  |  Elapsed: 2:27:41  |  ETA: 4:14:02
Step 6750/18225  |  Elapsed: 2:28:28  |  ETA: 4:12:23
Step 6800/18225  |  Elapsed: 2:29:15  |  ETA: 4:10:46
Step 6850/18225  |  Elapsed: 2:30:06  |  ETA: 4:09:15
Step 6900/18225  |  Elapsed: 2:30:54  |  ETA: 4:07:41
Step 6950/18225  |  Elapsed: 2:31:40  |  ETA: 4:06:04
Step 7000/18225  |  Elapsed: 2:32:27  |  ETA: 4:04:28

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 7050/18225  |  Elapsed: 2:36:27  |  ETA: 4:07:59
Step 7100/18225  |  Elapsed: 2:37:13  |  ETA: 4:06:21
Step 7150/18225  |  Elapsed: 2:38:00  |  ETA: 4:04:45
Step 7200/18225  |  Elapsed: 2:38:47  |  ETA: 4:03:09
Step 7250/18225  |  Elapsed: 2:39:35  |  ETA: 4:01:36
Step 7300/18225  |  Elapsed: 2:40:23  |  ETA: 4:00:03
Step 7350/18225  |  Elapsed: 2:41:11  |  ETA: 3:58:30
Step 7400/18225  |  Elapsed: 2:42:01  |  ETA: 3:57:01
Step 7450/18225  |  Elapsed: 2:42:52  |  ETA: 3:55:34
Step 7500/18225  |  Elapsed: 2:43:42  |  ETA: 3:54:06

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 7550/18225  |  Elapsed: 2:47:39  |  ETA: 3:57:03
Step 7600/18225  |  Elapsed: 2:48:26  |  ETA: 3:55:28
Step 7650/18225  |  Elapsed: 2:49:15  |  ETA: 3:53:58
Step 7700/18225  |  Elapsed: 2:50:04  |  ETA: 3:52:28
Step 7750/18225  |  Elapsed: 2:50:53  |  ETA: 3:50:58
Step 7800/18225  |  Elapsed: 2:51:40  |  ETA: 3:49:27
Step 7850/18225  |  Elapsed: 2:52:28  |  ETA: 3:47:56
Step 7900/18225  |  Elapsed: 2:53:14  |  ETA: 3:46:25
Step 7950/18225  |  Elapsed: 2:54:01  |  ETA: 3:44:55
Step 8000/18225  |  Elapsed: 2:54:48  |  ETA: 3:43:25

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 8050/18225  |  Elapsed: 2:58:51  |  ETA: 3:46:04
Step 8100/18225  |  Elapsed: 2:59:40  |  ETA: 3:44:36
Step 8150/18225  |  Elapsed: 3:00:30  |  ETA: 3:43:08
Step 8200/18225  |  Elapsed: 3:01:18  |  ETA: 3:41:39
Step 8250/18225  |  Elapsed: 3:02:05  |  ETA: 3:40:10
Step 8300/18225  |  Elapsed: 3:02:55  |  ETA: 3:38:44
Step 8350/18225  |  Elapsed: 3:03:43  |  ETA: 3:37:17
Step 8400/18225  |  Elapsed: 3:04:29  |  ETA: 3:35:47
Step 8450/18225  |  Elapsed: 3:05:20  |  ETA: 3:34:24
Step 8500/18225  |  Elapsed: 3:06:10  |  ETA: 3:33:00

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 8550/18225  |  Elapsed: 3:10:10  |  ETA: 3:35:11
Step 8600/18225  |  Elapsed: 3:10:58  |  ETA: 3:33:43
Step 8650/18225  |  Elapsed: 3:11:44  |  ETA: 3:32:15
Step 8700/18225  |  Elapsed: 3:12:32  |  ETA: 3:30:47
Step 8750/18225  |  Elapsed: 3:13:20  |  ETA: 3:29:21
Step 8800/18225  |  Elapsed: 3:14:06  |  ETA: 3:27:53
Step 8850/18225  |  Elapsed: 3:14:52  |  ETA: 3:26:26
Step 8900/18225  |  Elapsed: 3:15:40  |  ETA: 3:25:01
Step 8950/18225  |  Elapsed: 3:16:29  |  ETA: 3:23:37
Step 9000/18225  |  Elapsed: 3:17:17  |  ETA: 3:22:13

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 9050/18225  |  Elapsed: 3:21:14  |  ETA: 3:24:01
Step 9100/18225  |  Elapsed: 3:22:01  |  ETA: 3:22:34
Step 9150/18225  |  Elapsed: 3:22:48  |  ETA: 3:21:08
Step 9200/18225  |  Elapsed: 3:23:35  |  ETA: 3:19:42
Step 9250/18225  |  Elapsed: 3:24:22  |  ETA: 3:18:17
Step 9300/18225  |  Elapsed: 3:25:12  |  ETA: 3:16:56
Step 9350/18225  |  Elapsed: 3:26:00  |  ETA: 3:15:32
Step 9400/18225  |  Elapsed: 3:26:47  |  ETA: 3:14:08
Step 9450/18225  |  Elapsed: 3:27:34  |  ETA: 3:12:44
Step 9500/18225  |  Elapsed: 3:28:23  |  ETA: 3:11:23

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 9550/18225  |  Elapsed: 3:32:22  |  ETA: 3:12:54
Step 9600/18225  |  Elapsed: 3:33:09  |  ETA: 3:11:30
Step 9650/18225  |  Elapsed: 3:33:57  |  ETA: 3:10:07
Step 9700/18225  |  Elapsed: 3:34:45  |  ETA: 3:08:44
Step 9750/18225  |  Elapsed: 3:35:35  |  ETA: 3:07:23
Step 9800/18225  |  Elapsed: 3:36:25  |  ETA: 3:06:03
Step 9850/18225  |  Elapsed: 3:37:14  |  ETA: 3:04:42
Step 9900/18225  |  Elapsed: 3:38:01  |  ETA: 3:03:20
Step 9950/18225  |  Elapsed: 3:38:48  |  ETA: 3:01:58
Step 10000/18225  |  Elapsed: 3:39:35  |  ETA: 3:00:36

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 10050/18225  |  Elapsed: 3:43:31  |  ETA: 3:01:49
Step 10100/18225  |  Elapsed: 3:44:19  |  ETA: 3:00:27
Step 10150/18225  |  Elapsed: 3:45:06  |  ETA: 2:59:05
Step 10200/18225  |  Elapsed: 3:45:54  |  ETA: 2:57:44
Step 10250/18225  |  Elapsed: 3:46:42  |  ETA: 2:56:23
Step 10300/18225  |  Elapsed: 3:47:31  |  ETA: 2:55:04
Step 10350/18225  |  Elapsed: 3:48:18  |  ETA: 2:53:42
Step 10400/18225  |  Elapsed: 3:49:05  |  ETA: 2:52:22
Step 10450/18225  |  Elapsed: 3:49:52  |  ETA: 2:51:01
Step 10500/18225  |  Elapsed: 3:50:38  |  ETA: 2:49:41

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 10550/18225  |  Elapsed: 3:54:33  |  ETA: 2:50:38
Step 10600/18225  |  Elapsed: 3:55:19  |  ETA: 2:49:16
Step 10650/18225  |  Elapsed: 3:56:06  |  ETA: 2:47:56
Step 10700/18225  |  Elapsed: 3:56:53  |  ETA: 2:46:35
Step 10750/18225  |  Elapsed: 3:57:40  |  ETA: 2:45:15
Step 10800/18225  |  Elapsed: 3:58:26  |  ETA: 2:43:55
Step 10850/18225  |  Elapsed: 3:59:12  |  ETA: 2:42:36
Step 10900/18225  |  Elapsed: 3:59:58  |  ETA: 2:41:16
Step 10950/18225  |  Elapsed: 4:00:47  |  ETA: 2:39:58
Step 11000/18225  |  Elapsed: 4:01:37  |  ETA: 2:38:42

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 11050/18225  |  Elapsed: 4:05:36  |  ETA: 2:39:28
Step 11100/18225  |  Elapsed: 4:06:26  |  ETA: 2:38:11
Step 11150/18225  |  Elapsed: 4:07:16  |  ETA: 2:36:53
Step 11200/18225  |  Elapsed: 4:08:03  |  ETA: 2:35:35
Step 11250/18225  |  Elapsed: 4:08:49  |  ETA: 2:34:16
Step 11300/18225  |  Elapsed: 4:09:35  |  ETA: 2:32:57
Step 11350/18225  |  Elapsed: 4:10:21  |  ETA: 2:31:39
Step 11400/18225  |  Elapsed: 4:11:08  |  ETA: 2:30:20
Step 11450/18225  |  Elapsed: 4:11:54  |  ETA: 2:29:03
Step 11500/18225  |  Elapsed: 4:12:42  |  ETA: 2:27:46

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 11550/18225  |  Elapsed: 4:16:40  |  ETA: 2:28:20
Step 11600/18225  |  Elapsed: 4:17:28  |  ETA: 2:27:02
Step 11650/18225  |  Elapsed: 4:18:15  |  ETA: 2:25:45
Step 11700/18225  |  Elapsed: 4:19:00  |  ETA: 2:24:27
Step 11750/18225  |  Elapsed: 4:19:48  |  ETA: 2:23:10
Step 11800/18225  |  Elapsed: 4:20:34  |  ETA: 2:21:53
Step 11850/18225  |  Elapsed: 4:21:21  |  ETA: 2:20:36
Step 11900/18225  |  Elapsed: 4:22:07  |  ETA: 2:19:19
Step 11950/18225  |  Elapsed: 4:22:52  |  ETA: 2:18:02
Step 12000/18225  |  Elapsed: 4:23:38  |  ETA: 2:16:45

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 12050/18225  |  Elapsed: 4:27:33  |  ETA: 2:17:06
Step 12100/18225  |  Elapsed: 4:28:20  |  ETA: 2:15:50
Step 12150/18225  |  Elapsed: 4:29:09  |  ETA: 2:14:34
Step 12200/18225  |  Elapsed: 4:29:56  |  ETA: 2:13:18
Step 12250/18225  |  Elapsed: 4:30:44  |  ETA: 2:12:03
Step 12300/18225  |  Elapsed: 4:31:32  |  ETA: 2:10:48
Step 12350/18225  |  Elapsed: 4:32:20  |  ETA: 2:09:33
Step 12400/18225  |  Elapsed: 4:33:08  |  ETA: 2:08:18
Step 12450/18225  |  Elapsed: 4:33:56  |  ETA: 2:07:04
Step 12500/18225  |  Elapsed: 4:34:42  |  ETA: 2:05:49

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 12550/18225  |  Elapsed: 4:38:44  |  ETA: 2:06:02
Step 12600/18225  |  Elapsed: 4:39:32  |  ETA: 2:04:47
Step 12650/18225  |  Elapsed: 4:40:21  |  ETA: 2:03:33
Step 12700/18225  |  Elapsed: 4:41:10  |  ETA: 2:02:19
Step 12750/18225  |  Elapsed: 4:41:59  |  ETA: 2:01:05
Step 12800/18225  |  Elapsed: 4:42:45  |  ETA: 1:59:50
Step 12850/18225  |  Elapsed: 4:43:33  |  ETA: 1:58:36
Step 12900/18225  |  Elapsed: 4:44:19  |  ETA: 1:57:21
Step 12950/18225  |  Elapsed: 4:45:06  |  ETA: 1:56:08
Step 13000/18225  |  Elapsed: 4:45:52  |  ETA: 1:54:54

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 13050/18225  |  Elapsed: 4:49:49  |  ETA: 1:54:55
Step 13100/18225  |  Elapsed: 4:50:36  |  ETA: 1:53:41
Step 13150/18225  |  Elapsed: 4:51:26  |  ETA: 1:52:28
Step 13200/18225  |  Elapsed: 4:52:13  |  ETA: 1:51:14
Step 13250/18225  |  Elapsed: 4:53:00  |  ETA: 1:50:01
Step 13300/18225  |  Elapsed: 4:53:49  |  ETA: 1:48:48
Step 13350/18225  |  Elapsed: 4:54:38  |  ETA: 1:47:35
Step 13400/18225  |  Elapsed: 4:55:29  |  ETA: 1:46:23
Step 13450/18225  |  Elapsed: 4:56:17  |  ETA: 1:45:11
Step 13500/18225  |  Elapsed: 4:57:06  |  ETA: 1:43:59

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 13550/18225  |  Elapsed: 5:01:03  |  ETA: 1:43:52
Step 13600/18225  |  Elapsed: 5:01:49  |  ETA: 1:42:38
Step 13650/18225  |  Elapsed: 5:02:36  |  ETA: 1:41:25
Step 13700/18225  |  Elapsed: 5:03:25  |  ETA: 1:40:13
Step 13750/18225  |  Elapsed: 5:04:13  |  ETA: 1:39:00
Step 13800/18225  |  Elapsed: 5:05:00  |  ETA: 1:37:48
Step 13850/18225  |  Elapsed: 5:05:46  |  ETA: 1:36:35
Step 13900/18225  |  Elapsed: 5:06:33  |  ETA: 1:35:23
Step 13950/18225  |  Elapsed: 5:07:19  |  ETA: 1:34:10
Step 14000/18225  |  Elapsed: 5:08:05  |  ETA: 1:32:58

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 14050/18225  |  Elapsed: 5:12:03  |  ETA: 1:32:43
Step 14100/18225  |  Elapsed: 5:12:53  |  ETA: 1:31:32
Step 14150/18225  |  Elapsed: 5:13:44  |  ETA: 1:30:21
Step 14200/18225  |  Elapsed: 5:14:34  |  ETA: 1:29:09
Step 14250/18225  |  Elapsed: 5:15:23  |  ETA: 1:27:58
Step 14300/18225  |  Elapsed: 5:16:12  |  ETA: 1:26:47
Step 14350/18225  |  Elapsed: 5:17:02  |  ETA: 1:25:36
Step 14400/18225  |  Elapsed: 5:17:51  |  ETA: 1:24:25
Step 14450/18225  |  Elapsed: 5:18:40  |  ETA: 1:23:15
Step 14500/18225  |  Elapsed: 5:19:31  |  ETA: 1:22:04

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 14550/18225  |  Elapsed: 5:23:27  |  ETA: 1:21:41
Step 14600/18225  |  Elapsed: 5:24:13  |  ETA: 1:20:30
Step 14650/18225  |  Elapsed: 5:25:00  |  ETA: 1:19:18
Step 14700/18225  |  Elapsed: 5:25:46  |  ETA: 1:18:07
Step 14750/18225  |  Elapsed: 5:26:36  |  ETA: 1:16:56
Step 14800/18225  |  Elapsed: 5:27:25  |  ETA: 1:15:46
Step 14850/18225  |  Elapsed: 5:28:11  |  ETA: 1:14:35
Step 14900/18225  |  Elapsed: 5:29:00  |  ETA: 1:13:25
Step 14950/18225  |  Elapsed: 5:29:47  |  ETA: 1:12:14
Step 15000/18225  |  Elapsed: 5:30:34  |  ETA: 1:11:04

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 15050/18225  |  Elapsed: 5:34:30  |  ETA: 1:10:34
Step 15100/18225  |  Elapsed: 5:35:17  |  ETA: 1:09:23
Step 15150/18225  |  Elapsed: 5:36:04  |  ETA: 1:08:12
Step 15200/18225  |  Elapsed: 5:36:50  |  ETA: 1:07:02
Step 15250/18225  |  Elapsed: 5:37:39  |  ETA: 1:05:52
Step 15300/18225  |  Elapsed: 5:38:26  |  ETA: 1:04:42
Step 15350/18225  |  Elapsed: 5:39:13  |  ETA: 1:03:32
Step 15400/18225  |  Elapsed: 5:39:58  |  ETA: 1:02:22
Step 15450/18225  |  Elapsed: 5:40:45  |  ETA: 1:01:12
Step 15500/18225  |  Elapsed: 5:41:32  |  ETA: 1:00:02

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 15550/18225  |  Elapsed: 5:45:33  |  ETA: 0:59:26
Step 15600/18225  |  Elapsed: 5:46:20  |  ETA: 0:58:16
Step 15650/18225  |  Elapsed: 5:47:07  |  ETA: 0:57:06
Step 15700/18225  |  Elapsed: 5:47:53  |  ETA: 0:55:57
Step 15750/18225  |  Elapsed: 5:48:40  |  ETA: 0:54:47
Step 15800/18225  |  Elapsed: 5:49:26  |  ETA: 0:53:38
Step 15850/18225  |  Elapsed: 5:50:12  |  ETA: 0:52:28
Step 15900/18225  |  Elapsed: 5:50:59  |  ETA: 0:51:19
Step 15950/18225  |  Elapsed: 5:51:46  |  ETA: 0:50:10
Step 16000/18225  |  Elapsed: 5:52:33  |  ETA: 0:49:01

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 16050/18225  |  Elapsed: 5:56:28  |  ETA: 0:48:18
Step 16100/18225  |  Elapsed: 5:57:17  |  ETA: 0:47:09
Step 16150/18225  |  Elapsed: 5:58:05  |  ETA: 0:46:00
Step 16200/18225  |  Elapsed: 5:58:52  |  ETA: 0:44:51
Step 16250/18225  |  Elapsed: 5:59:39  |  ETA: 0:43:42
Step 16300/18225  |  Elapsed: 6:00:26  |  ETA: 0:42:34
Step 16350/18225  |  Elapsed: 6:01:13  |  ETA: 0:41:25
Step 16400/18225  |  Elapsed: 6:02:00  |  ETA: 0:40:17
Step 16450/18225  |  Elapsed: 6:02:49  |  ETA: 0:39:08
Step 16500/18225  |  Elapsed: 6:03:39  |  ETA: 0:38:01

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 16550/18225  |  Elapsed: 6:07:38  |  ETA: 0:37:12
Step 16600/18225  |  Elapsed: 6:08:25  |  ETA: 0:36:03
Step 16650/18225  |  Elapsed: 6:09:13  |  ETA: 0:34:55
Step 16700/18225  |  Elapsed: 6:10:01  |  ETA: 0:33:47
Step 16750/18225  |  Elapsed: 6:10:47  |  ETA: 0:32:39
Step 16800/18225  |  Elapsed: 6:11:34  |  ETA: 0:31:31
Step 16850/18225  |  Elapsed: 6:12:21  |  ETA: 0:30:23
Step 16900/18225  |  Elapsed: 6:13:08  |  ETA: 0:29:15
Step 16950/18225  |  Elapsed: 6:13:54  |  ETA: 0:28:07
Step 17000/18225  |  Elapsed: 6:14:41  |  ETA: 0:26:59

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 17050/18225  |  Elapsed: 6:18:37  |  ETA: 0:26:05
Step 17100/18225  |  Elapsed: 6:19:25  |  ETA: 0:24:57
Step 17150/18225  |  Elapsed: 6:20:11  |  ETA: 0:23:49
Step 17200/18225  |  Elapsed: 6:20:58  |  ETA: 0:22:42
Step 17250/18225  |  Elapsed: 6:21:44  |  ETA: 0:21:34
Step 17300/18225  |  Elapsed: 6:22:30  |  ETA: 0:20:27
Step 17350/18225  |  Elapsed: 6:23:16  |  ETA: 0:19:19
Step 17400/18225  |  Elapsed: 6:24:04  |  ETA: 0:18:12
Step 17450/18225  |  Elapsed: 6:24:51  |  ETA: 0:17:05
Step 17500/18225  |  Elapsed: 6:25:37  |  ETA: 0:15:58

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 17550/18225  |  Elapsed: 6:29:33  |  ETA: 0:14:58
Step 17600/18225  |  Elapsed: 6:30:20  |  ETA: 0:13:51
Step 17650/18225  |  Elapsed: 6:31:08  |  ETA: 0:12:44
Step 17700/18225  |  Elapsed: 6:31:57  |  ETA: 0:11:37
Step 17750/18225  |  Elapsed: 6:32:47  |  ETA: 0:10:30
Step 17800/18225  |  Elapsed: 6:33:33  |  ETA: 0:09:23
Step 17850/18225  |  Elapsed: 6:34:20  |  ETA: 0:08:17
Step 17900/18225  |  Elapsed: 6:35:07  |  ETA: 0:07:10
Step 17950/18225  |  Elapsed: 6:35:53  |  ETA: 0:06:03
Step 18000/18225  |  Elapsed: 6:36:39  |  ETA: 0:04:57

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 18050/18225  |  Elapsed: 6:40:36  |  ETA: 0:03:53
Step 18100/18225  |  Elapsed: 6:41:26  |  ETA: 0:02:46
Step 18150/18225  |  Elapsed: 6:42:15  |  ETA: 0:01:39
Step 18200/18225  |  Elapsed: 6:43:05  |  ETA: 0:00:33

✅ Model saved to /home/dingku/Desktop/FTIT26/eng_Latn-asm_Beng


======================================================================
🚀 Fine‑tuning for eng_Latn-mni_Beng
======================================================================
  Train samples: 21,318  |  Dev samples: 2,369

📥 Loading tokenizer and base model...

/home/dingku/jupyter_env/lib/python3.12/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.

🔧 Adding LoRA adapters...
trainable params: 3,538,944 || all params: 1,119,082,496 || trainable%: 0.3162362035550952

📝 Tokenizing datasets...

Map:   0%|          | 0/21318 [00:00<?, ? examples/s]

Map:   0%|          | 0/2369 [00:00<?, ? examples/s]

🏋️ Starting training...

Step 50/7992  |  Elapsed: 0:00:51  |  ETA: 2:15:25
Step 100/7992  |  Elapsed: 0:01:38  |  ETA: 2:09:16
Step 150/7992  |  Elapsed: 0:02:25  |  ETA: 2:06:48
Step 200/7992  |  Elapsed: 0:03:14  |  ETA: 2:06:20
Step 250/7992  |  Elapsed: 0:04:01  |  ETA: 2:04:39
Step 300/7992  |  Elapsed: 0:04:51  |  ETA: 2:04:29
Step 350/7992  |  Elapsed: 0:05:41  |  ETA: 2:04:14
Step 400/7992  |  Elapsed: 0:06:31  |  ETA: 2:03:45
Step 450/7992  |  Elapsed: 0:07:18  |  ETA: 2:02:36
Step 500/7992  |  Elapsed: 0:08:06  |  ETA: 2:01:28

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 550/7992  |  Elapsed: 0:10:26  |  ETA: 2:21:17
Step 600/7992  |  Elapsed: 0:11:18  |  ETA: 2:19:22
Step 650/7992  |  Elapsed: 0:12:06  |  ETA: 2:16:51
Step 700/7992  |  Elapsed: 0:12:56  |  ETA: 2:14:45
Step 750/7992  |  Elapsed: 0:13:45  |  ETA: 2:12:54
Step 800/7992  |  Elapsed: 0:14:32  |  ETA: 2:10:46
Step 850/7992  |  Elapsed: 0:15:20  |  ETA: 2:08:55
Step 900/7992  |  Elapsed: 0:16:12  |  ETA: 2:07:44
Step 950/7992  |  Elapsed: 0:17:04  |  ETA: 2:06:31
Step 1000/7992  |  Elapsed: 0:17:54  |  ETA: 2:05:12

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 1050/7992  |  Elapsed: 0:20:11  |  ETA: 2:13:30
Step 1100/7992  |  Elapsed: 0:20:59  |  ETA: 2:11:31
Step 1150/7992  |  Elapsed: 0:21:48  |  ETA: 2:09:43
Step 1200/7992  |  Elapsed: 0:22:37  |  ETA: 2:08:00
Step 1250/7992  |  Elapsed: 0:23:26  |  ETA: 2:06:26
Step 1300/7992  |  Elapsed: 0:24:18  |  ETA: 2:05:08
Step 1350/7992  |  Elapsed: 0:25:07  |  ETA: 2:03:38
Step 1400/7992  |  Elapsed: 0:25:56  |  ETA: 2:02:06
Step 1450/7992  |  Elapsed: 0:26:45  |  ETA: 2:00:43
Step 1500/7992  |  Elapsed: 0:27:33  |  ETA: 1:59:14

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 1550/7992  |  Elapsed: 0:29:47  |  ETA: 2:03:50
Step 1600/7992  |  Elapsed: 0:30:38  |  ETA: 2:02:24
Step 1650/7992  |  Elapsed: 0:31:28  |  ETA: 2:00:58
Step 1700/7992  |  Elapsed: 0:32:19  |  ETA: 1:59:39
Step 1750/7992  |  Elapsed: 0:33:08  |  ETA: 1:58:11
Step 1800/7992  |  Elapsed: 0:33:57  |  ETA: 1:56:49
Step 1850/7992  |  Elapsed: 0:34:47  |  ETA: 1:55:29
Step 1900/7992  |  Elapsed: 0:35:36  |  ETA: 1:54:08
Step 1950/7992  |  Elapsed: 0:36:24  |  ETA: 1:52:49
Step 2000/7992  |  Elapsed: 0:37:14  |  ETA: 1:51:33

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 2050/7992  |  Elapsed: 0:39:28  |  ETA: 1:54:24
Step 2100/7992  |  Elapsed: 0:40:20  |  ETA: 1:53:10
Step 2150/7992  |  Elapsed: 0:41:12  |  ETA: 1:51:56
Step 2200/7992  |  Elapsed: 0:42:04  |  ETA: 1:50:45
Step 2250/7992  |  Elapsed: 0:42:55  |  ETA: 1:49:33
Step 2300/7992  |  Elapsed: 0:43:47  |  ETA: 1:48:22
Step 2350/7992  |  Elapsed: 0:44:38  |  ETA: 1:47:11
Step 2400/7992  |  Elapsed: 0:45:27  |  ETA: 1:45:55
Step 2450/7992  |  Elapsed: 0:46:14  |  ETA: 1:44:36
Step 2500/7992  |  Elapsed: 0:47:03  |  ETA: 1:43:22

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 2550/7992  |  Elapsed: 0:49:17  |  ETA: 1:45:11
Step 2600/7992  |  Elapsed: 0:50:07  |  ETA: 1:43:56
Step 2650/7992  |  Elapsed: 0:50:55  |  ETA: 1:42:39
Step 2700/7992  |  Elapsed: 0:51:45  |  ETA: 1:41:26
Step 2750/7992  |  Elapsed: 0:52:32  |  ETA: 1:40:09
Step 2800/7992  |  Elapsed: 0:53:19  |  ETA: 1:38:52
Step 2850/7992  |  Elapsed: 0:54:06  |  ETA: 1:37:38
Step 2900/7992  |  Elapsed: 0:54:55  |  ETA: 1:36:25
Step 2950/7992  |  Elapsed: 0:55:43  |  ETA: 1:35:14
Step 3000/7992  |  Elapsed: 0:56:30  |  ETA: 1:34:02

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 3050/7992  |  Elapsed: 0:58:44  |  ETA: 1:35:11
Step 3100/7992  |  Elapsed: 0:59:33  |  ETA: 1:33:58
Step 3150/7992  |  Elapsed: 1:00:20  |  ETA: 1:32:45
Step 3200/7992  |  Elapsed: 1:01:07  |  ETA: 1:31:32
Step 3250/7992  |  Elapsed: 1:01:55  |  ETA: 1:30:21
Step 3300/7992  |  Elapsed: 1:02:43  |  ETA: 1:29:10
Step 3350/7992  |  Elapsed: 1:03:31  |  ETA: 1:28:01
Step 3400/7992  |  Elapsed: 1:04:19  |  ETA: 1:26:52
Step 3450/7992  |  Elapsed: 1:05:07  |  ETA: 1:25:44
Step 3500/7992  |  Elapsed: 1:05:56  |  ETA: 1:24:38

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 3550/7992  |  Elapsed: 1:08:13  |  ETA: 1:25:21
Step 3600/7992  |  Elapsed: 1:09:01  |  ETA: 1:24:13
Step 3650/7992  |  Elapsed: 1:09:49  |  ETA: 1:23:03
Step 3700/7992  |  Elapsed: 1:10:37  |  ETA: 1:21:55
Step 3750/7992  |  Elapsed: 1:11:28  |  ETA: 1:20:51
Step 3800/7992  |  Elapsed: 1:12:17  |  ETA: 1:19:44
Step 3850/7992  |  Elapsed: 1:13:06  |  ETA: 1:18:38
Step 3900/7992  |  Elapsed: 1:13:55  |  ETA: 1:17:33
Step 3950/7992  |  Elapsed: 1:14:43  |  ETA: 1:16:28
Step 4000/7992  |  Elapsed: 1:15:30  |  ETA: 1:15:21

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 4050/7992  |  Elapsed: 1:17:42  |  ETA: 1:15:38
Step 4100/7992  |  Elapsed: 1:18:30  |  ETA: 1:14:31
Step 4150/7992  |  Elapsed: 1:19:22  |  ETA: 1:13:28
Step 4200/7992  |  Elapsed: 1:20:13  |  ETA: 1:12:26
Step 4250/7992  |  Elapsed: 1:21:05  |  ETA: 1:11:23
Step 4300/7992  |  Elapsed: 1:21:55  |  ETA: 1:10:20
Step 4350/7992  |  Elapsed: 1:22:44  |  ETA: 1:09:16
Step 4400/7992  |  Elapsed: 1:23:33  |  ETA: 1:08:12
Step 4450/7992  |  Elapsed: 1:24:21  |  ETA: 1:07:09
Step 4500/7992  |  Elapsed: 1:25:11  |  ETA: 1:06:06

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 4550/7992  |  Elapsed: 1:27:23  |  ETA: 1:06:06
Step 4600/7992  |  Elapsed: 1:28:11  |  ETA: 1:05:01
Step 4650/7992  |  Elapsed: 1:28:59  |  ETA: 1:03:57
Step 4700/7992  |  Elapsed: 1:29:49  |  ETA: 1:02:54
Step 4750/7992  |  Elapsed: 1:30:37  |  ETA: 1:01:51
Step 4800/7992  |  Elapsed: 1:31:23  |  ETA: 1:00:46
Step 4850/7992  |  Elapsed: 1:32:12  |  ETA: 0:59:44
Step 4900/7992  |  Elapsed: 1:33:00  |  ETA: 0:58:41
Step 4950/7992  |  Elapsed: 1:33:49  |  ETA: 0:57:39
Step 5000/7992  |  Elapsed: 1:34:36  |  ETA: 0:56:36

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 5050/7992  |  Elapsed: 1:36:48  |  ETA: 0:56:23
Step 5100/7992  |  Elapsed: 1:37:35  |  ETA: 0:55:20
Step 5150/7992  |  Elapsed: 1:38:23  |  ETA: 0:54:18
Step 5200/7992  |  Elapsed: 1:39:12  |  ETA: 0:53:16
Step 5250/7992  |  Elapsed: 1:40:04  |  ETA: 0:52:16
Step 5300/7992  |  Elapsed: 1:40:53  |  ETA: 0:51:14
Step 5350/7992  |  Elapsed: 1:41:44  |  ETA: 0:50:14
Step 5400/7992  |  Elapsed: 1:42:36  |  ETA: 0:49:15
Step 5450/7992  |  Elapsed: 1:43:28  |  ETA: 0:48:15
Step 5500/7992  |  Elapsed: 1:44:20  |  ETA: 0:47:16

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 5550/7992  |  Elapsed: 1:46:36  |  ETA: 0:46:54
Step 5600/7992  |  Elapsed: 1:47:28  |  ETA: 0:45:54
Step 5650/7992  |  Elapsed: 1:48:18  |  ETA: 0:44:53
Step 5700/7992  |  Elapsed: 1:49:05  |  ETA: 0:43:51
Step 5750/7992  |  Elapsed: 1:49:54  |  ETA: 0:42:51
Step 5800/7992  |  Elapsed: 1:50:44  |  ETA: 0:41:51
Step 5850/7992  |  Elapsed: 1:51:34  |  ETA: 0:40:51
Step 5900/7992  |  Elapsed: 1:52:22  |  ETA: 0:39:50
Step 5950/7992  |  Elapsed: 1:53:11  |  ETA: 0:38:50
Step 6000/7992  |  Elapsed: 1:54:00  |  ETA: 0:37:50

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 6050/7992  |  Elapsed: 1:56:15  |  ETA: 0:37:19
Step 6100/7992  |  Elapsed: 1:57:05  |  ETA: 0:36:18
Step 6150/7992  |  Elapsed: 1:57:53  |  ETA: 0:35:18
Step 6200/7992  |  Elapsed: 1:58:43  |  ETA: 0:34:19
Step 6250/7992  |  Elapsed: 1:59:31  |  ETA: 0:33:18
Step 6300/7992  |  Elapsed: 2:00:19  |  ETA: 0:32:19
Step 6350/7992  |  Elapsed: 2:01:07  |  ETA: 0:31:19
Step 6400/7992  |  Elapsed: 2:01:55  |  ETA: 0:30:19
Step 6450/7992  |  Elapsed: 2:02:46  |  ETA: 0:29:21
Step 6500/7992  |  Elapsed: 2:03:38  |  ETA: 0:28:22

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 6550/7992  |  Elapsed: 2:05:53  |  ETA: 0:27:42
Step 6600/7992  |  Elapsed: 2:06:43  |  ETA: 0:26:43
Step 6650/7992  |  Elapsed: 2:07:35  |  ETA: 0:25:44
Step 6700/7992  |  Elapsed: 2:08:25  |  ETA: 0:24:45
Step 6750/7992  |  Elapsed: 2:09:14  |  ETA: 0:23:46
Step 6800/7992  |  Elapsed: 2:10:03  |  ETA: 0:22:47
Step 6850/7992  |  Elapsed: 2:10:52  |  ETA: 0:21:49
Step 6900/7992  |  Elapsed: 2:11:41  |  ETA: 0:20:50
Step 6950/7992  |  Elapsed: 2:12:29  |  ETA: 0:19:51
Step 7000/7992  |  Elapsed: 2:13:16  |  ETA: 0:18:53

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 7050/7992  |  Elapsed: 2:15:28  |  ETA: 0:18:06
Step 7100/7992  |  Elapsed: 2:16:15  |  ETA: 0:17:07
Step 7150/7992  |  Elapsed: 2:17:03  |  ETA: 0:16:08
Step 7200/7992  |  Elapsed: 2:17:51  |  ETA: 0:15:09
Step 7250/7992  |  Elapsed: 2:18:39  |  ETA: 0:14:11
Step 7300/7992  |  Elapsed: 2:19:32  |  ETA: 0:13:13
Step 7350/7992  |  Elapsed: 2:20:23  |  ETA: 0:12:15
Step 7400/7992  |  Elapsed: 2:21:10  |  ETA: 0:11:17
Step 7450/7992  |  Elapsed: 2:21:59  |  ETA: 0:10:19
Step 7500/7992  |  Elapsed: 2:22:47  |  ETA: 0:09:22

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 7550/7992  |  Elapsed: 2:25:01  |  ETA: 0:08:29
Step 7600/7992  |  Elapsed: 2:25:48  |  ETA: 0:07:31
Step 7650/7992  |  Elapsed: 2:26:35  |  ETA: 0:06:33
Step 7700/7992  |  Elapsed: 2:27:23  |  ETA: 0:05:35
Step 7750/7992  |  Elapsed: 2:28:10  |  ETA: 0:04:37
Step 7800/7992  |  Elapsed: 2:28:58  |  ETA: 0:03:40
Step 7850/7992  |  Elapsed: 2:29:47  |  ETA: 0:02:42
Step 7900/7992  |  Elapsed: 2:30:36  |  ETA: 0:01:45
Step 7950/7992  |  Elapsed: 2:31:23  |  ETA: 0:00:47

✅ Model saved to /home/dingku/Desktop/FTIT26/eng_Latn-mni_Beng


======================================================================
🚀 Fine‑tuning for eng_Latn-mni_Mtei
======================================================================
  Train samples: 15,300  |  Dev samples: 1,700

📥 Loading tokenizer and base model...

/home/dingku/jupyter_env/lib/python3.12/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.

🔧 Adding LoRA adapters...
trainable params: 3,538,944 || all params: 1,119,082,496 || trainable%: 0.3162362035550952

📝 Tokenizing datasets...

Map:   0%|          | 0/15300 [00:00<?, ? examples/s]

Map:   0%|          | 0/1700 [00:00<?, ? examples/s]

🏋️ Starting training...

Step 50/5736  |  Elapsed: 0:00:43  |  ETA: 1:22:40
Step 100/5736  |  Elapsed: 0:01:25  |  ETA: 1:20:23
Step 150/5736  |  Elapsed: 0:02:13  |  ETA: 1:22:34
Step 200/5736  |  Elapsed: 0:03:01  |  ETA: 1:23:53
Step 250/5736  |  Elapsed: 0:03:50  |  ETA: 1:24:17
Step 300/5736  |  Elapsed: 0:04:37  |  ETA: 1:23:48
Step 350/5736  |  Elapsed: 0:05:19  |  ETA: 1:22:03
Step 400/5736  |  Elapsed: 0:06:03  |  ETA: 1:20:49
Step 450/5736  |  Elapsed: 0:06:47  |  ETA: 1:19:41
Step 500/5736  |  Elapsed: 0:07:31  |  ETA: 1:18:47

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 550/5736  |  Elapsed: 0:09:09  |  ETA: 1:26:24
Step 600/5736  |  Elapsed: 0:09:52  |  ETA: 1:24:29
Step 650/5736  |  Elapsed: 0:10:34  |  ETA: 1:22:42
Step 700/5736  |  Elapsed: 0:11:16  |  ETA: 1:21:07
Step 750/5736  |  Elapsed: 0:11:59  |  ETA: 1:19:45
Step 800/5736  |  Elapsed: 0:12:43  |  ETA: 1:18:31
Step 850/5736  |  Elapsed: 0:13:29  |  ETA: 1:17:32
Step 900/5736  |  Elapsed: 0:14:17  |  ETA: 1:16:49
Step 950/5736  |  Elapsed: 0:15:01  |  ETA: 1:15:43
Step 1000/5736  |  Elapsed: 0:15:45  |  ETA: 1:14:39

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 1050/5736  |  Elapsed: 0:17:19  |  ETA: 1:17:19
Step 1100/5736  |  Elapsed: 0:18:01  |  ETA: 1:15:58
Step 1150/5736  |  Elapsed: 0:18:43  |  ETA: 1:14:39
Step 1200/5736  |  Elapsed: 0:19:25  |  ETA: 1:13:26
Step 1250/5736  |  Elapsed: 0:20:07  |  ETA: 1:12:13
Step 1300/5736  |  Elapsed: 0:20:49  |  ETA: 1:11:04
Step 1350/5736  |  Elapsed: 0:21:31  |  ETA: 1:09:57
Step 1400/5736  |  Elapsed: 0:22:14  |  ETA: 1:08:52
Step 1450/5736  |  Elapsed: 0:22:56  |  ETA: 1:07:48
Step 1500/5736  |  Elapsed: 0:23:38  |  ETA: 1:06:46

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 1550/5736  |  Elapsed: 0:25:11  |  ETA: 1:08:03
Step 1600/5736  |  Elapsed: 0:25:53  |  ETA: 1:06:56
Step 1650/5736  |  Elapsed: 0:26:34  |  ETA: 1:05:49
Step 1700/5736  |  Elapsed: 0:27:17  |  ETA: 1:04:47
Step 1750/5736  |  Elapsed: 0:27:59  |  ETA: 1:03:46
Step 1800/5736  |  Elapsed: 0:28:41  |  ETA: 1:02:44
Step 1850/5736  |  Elapsed: 0:29:25  |  ETA: 1:01:49
Step 1900/5736  |  Elapsed: 0:30:12  |  ETA: 1:00:58
Step 1950/5736  |  Elapsed: 0:30:56  |  ETA: 1:00:04
Step 2000/5736  |  Elapsed: 0:31:39  |  ETA: 0:59:09

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 2050/5736  |  Elapsed: 0:33:18  |  ETA: 0:59:54
Step 2100/5736  |  Elapsed: 0:34:03  |  ETA: 0:58:57
Step 2150/5736  |  Elapsed: 0:34:47  |  ETA: 0:58:01
Step 2200/5736  |  Elapsed: 0:35:32  |  ETA: 0:57:07
Step 2250/5736  |  Elapsed: 0:36:16  |  ETA: 0:56:12
Step 2300/5736  |  Elapsed: 0:37:01  |  ETA: 0:55:18
Step 2350/5736  |  Elapsed: 0:37:45  |  ETA: 0:54:24
Step 2400/5736  |  Elapsed: 0:38:30  |  ETA: 0:53:31
Step 2450/5736  |  Elapsed: 0:39:13  |  ETA: 0:52:37
Step 2500/5736  |  Elapsed: 0:39:57  |  ETA: 0:51:43

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 2550/5736  |  Elapsed: 0:41:31  |  ETA: 0:51:53
Step 2600/5736  |  Elapsed: 0:42:13  |  ETA: 0:50:56
Step 2650/5736  |  Elapsed: 0:42:55  |  ETA: 0:49:59
Step 2700/5736  |  Elapsed: 0:43:37  |  ETA: 0:49:03
Step 2750/5736  |  Elapsed: 0:44:18  |  ETA: 0:48:07
Step 2800/5736  |  Elapsed: 0:45:01  |  ETA: 0:47:12
Step 2850/5736  |  Elapsed: 0:45:44  |  ETA: 0:46:19
Step 2900/5736  |  Elapsed: 0:46:27  |  ETA: 0:45:26
Step 2950/5736  |  Elapsed: 0:47:09  |  ETA: 0:44:32
Step 3000/5736  |  Elapsed: 0:47:51  |  ETA: 0:43:38

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 3050/5736  |  Elapsed: 0:49:25  |  ETA: 0:43:31
Step 3100/5736  |  Elapsed: 0:50:09  |  ETA: 0:42:39
Step 3150/5736  |  Elapsed: 0:50:53  |  ETA: 0:41:46
Step 3200/5736  |  Elapsed: 0:51:35  |  ETA: 0:40:52
Step 3250/5736  |  Elapsed: 0:52:17  |  ETA: 0:40:00
Step 3300/5736  |  Elapsed: 0:53:02  |  ETA: 0:39:09
Step 3350/5736  |  Elapsed: 0:53:52  |  ETA: 0:38:21
Step 3400/5736  |  Elapsed: 0:54:38  |  ETA: 0:37:32
Step 3450/5736  |  Elapsed: 0:55:23  |  ETA: 0:36:41
Step 3500/5736  |  Elapsed: 0:56:08  |  ETA: 0:35:52

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 3550/5736  |  Elapsed: 0:57:42  |  ETA: 0:35:32
Step 3600/5736  |  Elapsed: 0:58:24  |  ETA: 0:34:39
Step 3650/5736  |  Elapsed: 0:59:06  |  ETA: 0:33:46
Step 3700/5736  |  Elapsed: 0:59:54  |  ETA: 0:32:57
Step 3750/5736  |  Elapsed: 1:00:36  |  ETA: 0:32:06
Step 3800/5736  |  Elapsed: 1:01:21  |  ETA: 0:31:15
Step 3850/5736  |  Elapsed: 1:02:05  |  ETA: 0:30:24
Step 3900/5736  |  Elapsed: 1:02:49  |  ETA: 0:29:34
Step 3950/5736  |  Elapsed: 1:03:32  |  ETA: 0:28:43
Step 4000/5736  |  Elapsed: 1:04:13  |  ETA: 0:27:52

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 4050/5736  |  Elapsed: 1:05:50  |  ETA: 0:27:24
Step 4100/5736  |  Elapsed: 1:06:33  |  ETA: 0:26:33
Step 4150/5736  |  Elapsed: 1:07:16  |  ETA: 0:25:42
Step 4200/5736  |  Elapsed: 1:08:01  |  ETA: 0:24:52
Step 4250/5736  |  Elapsed: 1:08:45  |  ETA: 0:24:02
Step 4300/5736  |  Elapsed: 1:09:29  |  ETA: 0:23:12
Step 4350/5736  |  Elapsed: 1:10:12  |  ETA: 0:22:22
Step 4400/5736  |  Elapsed: 1:10:58  |  ETA: 0:21:32
Step 4450/5736  |  Elapsed: 1:11:46  |  ETA: 0:20:44
Step 4500/5736  |  Elapsed: 1:12:28  |  ETA: 0:19:54

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 4550/5736  |  Elapsed: 1:14:08  |  ETA: 0:19:19
Step 4600/5736  |  Elapsed: 1:14:57  |  ETA: 0:18:30
Step 4650/5736  |  Elapsed: 1:15:45  |  ETA: 0:17:41
Step 4700/5736  |  Elapsed: 1:16:32  |  ETA: 0:16:52
Step 4750/5736  |  Elapsed: 1:17:20  |  ETA: 0:16:03
Step 4800/5736  |  Elapsed: 1:18:06  |  ETA: 0:15:13
Step 4850/5736  |  Elapsed: 1:18:50  |  ETA: 0:14:24
Step 4900/5736  |  Elapsed: 1:19:32  |  ETA: 0:13:34
Step 4950/5736  |  Elapsed: 1:20:18  |  ETA: 0:12:45
Step 5000/5736  |  Elapsed: 1:21:00  |  ETA: 0:11:55

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 5050/5736  |  Elapsed: 1:22:34  |  ETA: 0:11:13
Step 5100/5736  |  Elapsed: 1:23:16  |  ETA: 0:10:23
Step 5150/5736  |  Elapsed: 1:23:59  |  ETA: 0:09:33
Step 5200/5736  |  Elapsed: 1:24:41  |  ETA: 0:08:43
Step 5250/5736  |  Elapsed: 1:25:22  |  ETA: 0:07:54
Step 5300/5736  |  Elapsed: 1:26:05  |  ETA: 0:07:04
Step 5350/5736  |  Elapsed: 1:26:47  |  ETA: 0:06:15
Step 5400/5736  |  Elapsed: 1:27:30  |  ETA: 0:05:26
Step 5450/5736  |  Elapsed: 1:28:17  |  ETA: 0:04:38
Step 5500/5736  |  Elapsed: 1:29:01  |  ETA: 0:03:49

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 5550/5736  |  Elapsed: 1:30:34  |  ETA: 0:03:02
Step 5600/5736  |  Elapsed: 1:31:18  |  ETA: 0:02:13
Step 5650/5736  |  Elapsed: 1:32:00  |  ETA: 0:01:24
Step 5700/5736  |  Elapsed: 1:32:43  |  ETA: 0:00:35

✅ Model saved to /home/dingku/Desktop/FTIT26/eng_Latn-mni_Mtei


======================================================================
🚀 Fine‑tuning for eng_Latn-brx_Deva
======================================================================

AssertionError: Mismatch in training data

In [1]:
#!/usr/bin/env python3

#Continue fine‑tuning Bodo (eng_Latn-brx_Deva) only.
#Assamese, Manipuri (Bengali), Manipuri (Meitei Mayek) are already done.

import os
import time
from datetime import timedelta
import torch
from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    DataCollatorForSeq2Seq
)
from peft import LoraConfig, get_peft_model, TaskType
from datasets import Dataset, DatasetDict
from tqdm.auto import tqdm
from transformers.trainer_callback import TrainerCallback

# ============================================================
# CONFIGURATION – BODO ONLY
# ============================================================

DATA_ROOT = "/home/dingku/Desktop/en-indic-exp"
LANG_PAIRS = ["eng_Latn-brx_Deva"]          # <-- only Bodo

BASE_MODEL = "ai4bharat/indictrans2-en-indic-1B"
OUTPUT_BASE = "/home/dingku/Desktop/FTIT26"

LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.1
LORA_TARGET_MODULES = ["q_proj", "k_proj"]

BATCH_SIZE = 2
GRAD_ACCUM = 4
LEARNING_RATE = 2e-4
EPOCHS = 3
MAX_LENGTH = 512
EVAL_STEPS = 500
SAVE_STEPS = 500
LOGGING_STEPS = 50

USE_FP16 = False
USE_BF16 = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


# ============================================================
# TIME ESTIMATE CALLBACK
# ============================================================
class TimeEstimateCallback(TrainerCallback):
    def __init__(self):
        self.start_time = time.time()

    def on_step_end(self, args, state, control, **kwargs):
        if state.global_step % 50 == 0:
            elapsed = time.time() - self.start_time
            steps_done = state.global_step
            if steps_done > 0:
                time_per_step = elapsed / steps_done
                steps_remaining = state.max_steps - steps_done
                eta = timedelta(seconds=int(time_per_step * steps_remaining))
                tqdm.write(
                    f"Step {steps_done}/{state.max_steps}  |  "
                    f"Elapsed: {timedelta(seconds=int(elapsed))}  |  "
                    f"ETA: {eta}"
                )


# ============================================================
# ROBUST DATA LOADER (truncates mismatched lines)
# ============================================================
def load_data_for_pair(pair_name):
    train_dir = os.path.join(DATA_ROOT, "train", pair_name)
    dev_dir   = os.path.join(DATA_ROOT, "dev", pair_name)

    src_lang, tgt_lang = pair_name.split("-")

    with open(os.path.join(train_dir, f"train.{src_lang}"), "r", encoding="utf-8") as f:
        src_lines = [line.strip() for line in f if line.strip()]
    with open(os.path.join(train_dir, f"train.{tgt_lang}"), "r", encoding="utf-8") as f:
        tgt_lines = [line.strip() for line in f if line.strip()]

    # Truncate to the smaller length if they differ
    min_len = min(len(src_lines), len(tgt_lines))
    if len(src_lines) != len(tgt_lines):
        print(f"  ⚠️ Mismatch: src={len(src_lines)}, tgt={len(tgt_lines)}. Truncating to {min_len}.")
        src_lines = src_lines[:min_len]
        tgt_lines = tgt_lines[:min_len]

    assert len(src_lines) == len(tgt_lines), "Mismatch after truncation"
    train_data = [{"en": s, "tgt": t} for s, t in zip(src_lines, tgt_lines)]

    # Dev set (if exists)
    if os.path.exists(dev_dir):
        with open(os.path.join(dev_dir, f"dev.{src_lang}"), "r", encoding="utf-8") as f:
            dev_src = [line.strip() for line in f if line.strip()]
        with open(os.path.join(dev_dir, f"dev.{tgt_lang}"), "r", encoding="utf-8") as f:
            dev_tgt = [line.strip() for line in f if line.strip()]
        min_dev = min(len(dev_src), len(dev_tgt))
        if len(dev_src) != len(dev_tgt):
            print(f"  ⚠️ Dev mismatch: src={len(dev_src)}, tgt={len(dev_tgt)}. Truncating to {min_dev}.")
            dev_src = dev_src[:min_dev]
            dev_tgt = dev_tgt[:min_dev]
        dev_data = [{"en": s, "tgt": t} for s, t in zip(dev_src, dev_tgt)]
    else:
        split = int(len(train_data) * 0.9)
        dev_data = train_data[split:]
        train_data = train_data[:split]

    print(f"  Train samples: {len(train_data):,}  |  Dev samples: {len(dev_data):,}")
    return DatasetDict({
        "train": Dataset.from_list(train_data),
        "validation": Dataset.from_list(dev_data)
    })


# ============================================================
# TOKENIZE
# ============================================================
def preprocess_function(examples, tokenizer, src_lang, tgt_lang):
    inputs = [f"{src_lang} {tgt_lang} {ex}" for ex in examples["en"]]
    targets = [f"{tgt_lang} {ex}" for ex in examples["tgt"]]

    model_inputs = tokenizer(
        inputs, max_length=MAX_LENGTH, truncation=True, padding=False
    )
    labels = tokenizer(
        text_target=targets, max_length=MAX_LENGTH, truncation=True, padding=False
    )
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs


# ============================================================
# FINE‑TUNE BODO
# ============================================================
def fine_tune_pair(pair_name):
    print("\n" + "=" * 70)
    print(f"🚀 Fine‑tuning for {pair_name}")
    print("=" * 70)

    dataset = load_data_for_pair(pair_name)

    print("\n📥 Loading tokenizer and base model...")
    tokenizer = AutoTokenizer.from_pretrained(
        BASE_MODEL,
        trust_remote_code=True,
        use_fast=True
    )
    model = AutoModelForSeq2SeqLM.from_pretrained(
        BASE_MODEL,
        trust_remote_code=True,
        torch_dtype=torch.float32
    )
    model.gradient_checkpointing_enable()
    model.to(device)

    print("🔧 Adding LoRA adapters...")
    lora_config = LoraConfig(
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        target_modules=LORA_TARGET_MODULES,
        lora_dropout=LORA_DROPOUT,
        bias="none",
        task_type=TaskType.SEQ_2_SEQ_LM,
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    print("\n📝 Tokenizing datasets...")
    src_lang, tgt_lang = pair_name.split("-")
    tokenized_ds = dataset.map(
        lambda x: preprocess_function(x, tokenizer, src_lang, tgt_lang),
        batched=True,
        remove_columns=dataset["train"].column_names,
    )

    data_collator = DataCollatorForSeq2Seq(
        tokenizer, model=model, padding=True
    )

    output_dir = os.path.join(OUTPUT_BASE, pair_name)
    os.makedirs(output_dir, exist_ok=True)

    training_args = Seq2SeqTrainingArguments(
        output_dir=output_dir,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRAD_ACCUM,
        learning_rate=LEARNING_RATE,
        num_train_epochs=EPOCHS,
        evaluation_strategy="steps",
        eval_steps=EVAL_STEPS,
        save_steps=SAVE_STEPS,
        logging_steps=LOGGING_STEPS,
        report_to="none",
        predict_with_generate=True,
        generation_max_length=MAX_LENGTH,
        fp16=USE_FP16,
        bf16=USE_BF16,
        push_to_hub=False,
        save_total_limit=2,
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_ds["train"],
        eval_dataset=tokenized_ds["validation"],
        data_collator=data_collator,
        tokenizer=tokenizer,
        callbacks=[TimeEstimateCallback()],
    )

    print("\n🏋️ Starting training...\n")
    trainer.train()

    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    print(f"\n✅ Model saved to {output_dir}\n")


# ============================================================
# RUN (ONLY BODO)
# ============================================================
if __name__ == "__main__":
    os.makedirs(OUTPUT_BASE, exist_ok=True)

    for pair in LANG_PAIRS:
        fine_tune_pair(pair)

    print("\n🎉 Bodo model fine‑tuned successfully!")
    print("Assamese, Manipuri (Bengali), Manipuri (Meitei Mayek) are already done.")

/home/dingku/jupyter_env/lib/python3.12/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.4.0) or chardet (7.4.3)/charset_normalizer (3.4.2) doesn't match a supported version!
  warnings.warn(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(

Using device: cuda

======================================================================
🚀 Fine‑tuning for eng_Latn-brx_Deva
======================================================================
  ⚠️ Mismatch: src=15235, tgt=15232. Truncating to 15232.
  Train samples: 13,708  |  Dev samples: 1,524

📥 Loading tokenizer and base model...

/home/dingku/jupyter_env/lib/python3.12/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.

🔧 Adding LoRA adapters...
trainable params: 3,538,944 || all params: 1,119,082,496 || trainable%: 0.3162362035550952

📝 Tokenizing datasets...

Map:   0%|          | 0/13708 [00:00<?, ? examples/s]

Map:   0%|          | 0/1524 [00:00<?, ? examples/s]

🏋️ Starting training...

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 50/5139  |  Elapsed: 0:00:46  |  ETA: 1:18:17
Step 100/5139  |  Elapsed: 0:01:27  |  ETA: 1:13:51
Step 150/5139  |  Elapsed: 0:02:09  |  ETA: 1:11:52
Step 200/5139  |  Elapsed: 0:02:49  |  ETA: 1:09:52
Step 250/5139  |  Elapsed: 0:03:30  |  ETA: 1:08:41
Step 300/5139  |  Elapsed: 0:04:11  |  ETA: 1:07:40
Step 350/5139  |  Elapsed: 0:04:54  |  ETA: 1:07:14
Step 400/5139  |  Elapsed: 0:05:42  |  ETA: 1:07:42
Step 450/5139  |  Elapsed: 0:06:28  |  ETA: 1:07:30
Step 500/5139  |  Elapsed: 0:07:17  |  ETA: 1:07:35

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 550/5139  |  Elapsed: 0:08:40  |  ETA: 1:12:19
Step 600/5139  |  Elapsed: 0:09:22  |  ETA: 1:10:57
Step 650/5139  |  Elapsed: 0:10:05  |  ETA: 1:09:42
Step 700/5139  |  Elapsed: 0:10:49  |  ETA: 1:08:37
Step 750/5139  |  Elapsed: 0:11:37  |  ETA: 1:08:04
Step 800/5139  |  Elapsed: 0:12:25  |  ETA: 1:07:25
Step 850/5139  |  Elapsed: 0:13:13  |  ETA: 1:06:41
Step 900/5139  |  Elapsed: 0:14:01  |  ETA: 1:06:03
Step 950/5139  |  Elapsed: 0:14:49  |  ETA: 1:05:21
Step 1000/5139  |  Elapsed: 0:15:36  |  ETA: 1:04:35

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 1050/5139  |  Elapsed: 0:16:52  |  ETA: 1:05:44
Step 1100/5139  |  Elapsed: 0:17:34  |  ETA: 1:04:32
Step 1150/5139  |  Elapsed: 0:18:15  |  ETA: 1:03:18
Step 1200/5139  |  Elapsed: 0:18:55  |  ETA: 1:02:05
Step 1250/5139  |  Elapsed: 0:19:36  |  ETA: 1:00:59
Step 1300/5139  |  Elapsed: 0:20:19  |  ETA: 1:00:01
Step 1350/5139  |  Elapsed: 0:21:03  |  ETA: 0:59:06
Step 1400/5139  |  Elapsed: 0:21:46  |  ETA: 0:58:10
Step 1450/5139  |  Elapsed: 0:22:30  |  ETA: 0:57:14
Step 1500/5139  |  Elapsed: 0:23:13  |  ETA: 0:56:19

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 1550/5139  |  Elapsed: 0:24:39  |  ETA: 0:57:05
Step 1600/5139  |  Elapsed: 0:25:22  |  ETA: 0:56:07
Step 1650/5139  |  Elapsed: 0:26:03  |  ETA: 0:55:05
Step 1700/5139  |  Elapsed: 0:26:44  |  ETA: 0:54:04
Step 1750/5139  |  Elapsed: 0:27:25  |  ETA: 0:53:06
Step 1800/5139  |  Elapsed: 0:28:06  |  ETA: 0:52:08
Step 1850/5139  |  Elapsed: 0:28:46  |  ETA: 0:51:08
Step 1900/5139  |  Elapsed: 0:29:25  |  ETA: 0:50:09
Step 1950/5139  |  Elapsed: 0:30:05  |  ETA: 0:49:12
Step 2000/5139  |  Elapsed: 0:30:44  |  ETA: 0:48:15

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 2050/5139  |  Elapsed: 0:32:05  |  ETA: 0:48:21
Step 2100/5139  |  Elapsed: 0:32:44  |  ETA: 0:47:22
Step 2150/5139  |  Elapsed: 0:33:23  |  ETA: 0:46:25
Step 2200/5139  |  Elapsed: 0:34:05  |  ETA: 0:45:32
Step 2250/5139  |  Elapsed: 0:34:48  |  ETA: 0:44:41
Step 2300/5139  |  Elapsed: 0:35:30  |  ETA: 0:43:49
Step 2350/5139  |  Elapsed: 0:36:13  |  ETA: 0:42:58
Step 2400/5139  |  Elapsed: 0:36:55  |  ETA: 0:42:08
Step 2450/5139  |  Elapsed: 0:37:37  |  ETA: 0:41:18
Step 2500/5139  |  Elapsed: 0:38:19  |  ETA: 0:40:27

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 2550/5139  |  Elapsed: 0:39:32  |  ETA: 0:40:09
Step 2600/5139  |  Elapsed: 0:40:12  |  ETA: 0:39:15
Step 2650/5139  |  Elapsed: 0:40:51  |  ETA: 0:38:22
Step 2700/5139  |  Elapsed: 0:41:30  |  ETA: 0:37:30
Step 2750/5139  |  Elapsed: 0:42:10  |  ETA: 0:36:38
Step 2800/5139  |  Elapsed: 0:42:51  |  ETA: 0:35:48
Step 2850/5139  |  Elapsed: 0:43:32  |  ETA: 0:34:57
Step 2900/5139  |  Elapsed: 0:44:16  |  ETA: 0:34:10
Step 2950/5139  |  Elapsed: 0:45:04  |  ETA: 0:33:26
Step 3000/5139  |  Elapsed: 0:45:53  |  ETA: 0:32:43

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 3050/5139  |  Elapsed: 0:47:18  |  ETA: 0:32:23
Step 3100/5139  |  Elapsed: 0:48:07  |  ETA: 0:31:39
Step 3150/5139  |  Elapsed: 0:48:57  |  ETA: 0:30:54
Step 3200/5139  |  Elapsed: 0:49:42  |  ETA: 0:30:07
Step 3250/5139  |  Elapsed: 0:50:24  |  ETA: 0:29:18
Step 3300/5139  |  Elapsed: 0:51:13  |  ETA: 0:28:32
Step 3350/5139  |  Elapsed: 0:52:00  |  ETA: 0:27:46
Step 3400/5139  |  Elapsed: 0:52:44  |  ETA: 0:26:58
Step 3450/5139  |  Elapsed: 0:53:30  |  ETA: 0:26:11
Step 3500/5139  |  Elapsed: 0:54:10  |  ETA: 0:25:22

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 3550/5139  |  Elapsed: 0:55:29  |  ETA: 0:24:50
Step 3600/5139  |  Elapsed: 0:56:12  |  ETA: 0:24:01
Step 3650/5139  |  Elapsed: 0:56:54  |  ETA: 0:23:13
Step 3700/5139  |  Elapsed: 0:57:37  |  ETA: 0:22:24
Step 3750/5139  |  Elapsed: 0:58:17  |  ETA: 0:21:35
Step 3800/5139  |  Elapsed: 0:58:58  |  ETA: 0:20:46
Step 3850/5139  |  Elapsed: 0:59:36  |  ETA: 0:19:57
Step 3900/5139  |  Elapsed: 1:00:17  |  ETA: 0:19:09
Step 3950/5139  |  Elapsed: 1:00:57  |  ETA: 0:18:20
Step 4000/5139  |  Elapsed: 1:01:38  |  ETA: 0:17:33

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 4050/5139  |  Elapsed: 1:02:53  |  ETA: 0:16:54
Step 4100/5139  |  Elapsed: 1:03:33  |  ETA: 0:16:06
Step 4150/5139  |  Elapsed: 1:04:14  |  ETA: 0:15:18
Step 4200/5139  |  Elapsed: 1:04:55  |  ETA: 0:14:30
Step 4250/5139  |  Elapsed: 1:05:35  |  ETA: 0:13:43
Step 4300/5139  |  Elapsed: 1:06:17  |  ETA: 0:12:56
Step 4350/5139  |  Elapsed: 1:06:57  |  ETA: 0:12:08
Step 4400/5139  |  Elapsed: 1:07:36  |  ETA: 0:11:21
Step 4450/5139  |  Elapsed: 1:08:15  |  ETA: 0:10:34
Step 4500/5139  |  Elapsed: 1:08:56  |  ETA: 0:09:47

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 4550/5139  |  Elapsed: 1:10:10  |  ETA: 0:09:05
Step 4600/5139  |  Elapsed: 1:10:49  |  ETA: 0:08:17
Step 4650/5139  |  Elapsed: 1:11:28  |  ETA: 0:07:31
Step 4700/5139  |  Elapsed: 1:12:07  |  ETA: 0:06:44
Step 4750/5139  |  Elapsed: 1:12:46  |  ETA: 0:05:57
Step 4800/5139  |  Elapsed: 1:13:25  |  ETA: 0:05:11
Step 4850/5139  |  Elapsed: 1:14:04  |  ETA: 0:04:24
Step 4900/5139  |  Elapsed: 1:14:43  |  ETA: 0:03:38
Step 4950/5139  |  Elapsed: 1:15:23  |  ETA: 0:02:52
Step 5000/5139  |  Elapsed: 1:16:03  |  ETA: 0:02:06

/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:600: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/home/dingku/jupyter_env/lib/python3.12/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

Step 5050/5139  |  Elapsed: 1:17:16  |  ETA: 0:01:21
Step 5100/5139  |  Elapsed: 1:17:56  |  ETA: 0:00:35

✅ Model saved to /home/dingku/Desktop/FTIT26/eng_Latn-brx_Deva


🎉 Bodo model fine‑tuned successfully!
Assamese, Manipuri (Bengali), Manipuri (Meitei Mayek) are already done.

In [2]:
#Fixed

In [1]:
#!/usr/bin/env python3
import os
import torch
import pandas as pd
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from peft import PeftModel
from tqdm import tqdm

EXCEL_PATH = "/home/dingku/Desktop/WMT 2026 IndicMT Test Data/Category 1/English - Meitei/en-mni-Mtei Test.xlsx"
OUTPUT_TXT = "/home/dingku/Desktop/manipuri_meitei_translations.txt"
MODEL_PATH = "/home/dingku/Desktop/FTIT26/eng_Latn-mni_Mtei"
BASE_MODEL = "ai4bharat/indictrans2-en-indic-1B"
COLUMN_NAME = "English Sentences"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
MAX_NEW_TOKENS = 200

print("Loading base model and tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
base_model = AutoModelForSeq2SeqLM.from_pretrained(
    BASE_MODEL,
    trust_remote_code=True,
    torch_dtype=torch.float32
).to(DEVICE)

print("Loading LoRA adapter...")
model = PeftModel.from_pretrained(base_model, MODEL_PATH)
model.eval()

src_lang = "eng_Latn"
tgt_lang = "mni_Mtei"

df = pd.read_excel(EXCEL_PATH)
sentences = df[COLUMN_NAME].dropna().astype(str).tolist()
print(f"Found {len(sentences)} sentences to translate.")

translations = []

for i, sent in enumerate(tqdm(sentences, desc="Translating"), start=1):
    if not sent.strip():
        translations.append("")
        continue

    input_text = f"{src_lang} {tgt_lang} {sent}"
    inputs = tokenizer(
        input_text,
        return_tensors="pt",
        truncation=True,
        max_length=512
    ).to(DEVICE)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=MAX_NEW_TOKENS,
            num_beams=4,
            early_stopping=True,
            no_repeat_ngram_size=2,
            repetition_penalty=2.0,
            length_penalty=1.0,
            do_sample=False,
            temperature=1.0,
            pad_token_id=tokenizer.eos_token_id
        )

    translation = tokenizer.decode(outputs[0], skip_special_tokens=True)
    if translation.startswith(tgt_lang):
        translation = translation[len(tgt_lang):].strip()

    translations.append(translation)
    print(f"\n[{i}/{len(sentences)}]\nEN: {sent}\nMT: {translation}\n" + "-"*50)

with open(OUTPUT_TXT, "w", encoding="utf-8") as f:
    for trans in translations:
        f.write(trans + "\n")

print(f"\n✅ Translations saved to: {OUTPUT_TXT}")

/home/dingku/jupyter_env/lib/python3.12/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.4.0) or chardet (7.4.3)/charset_normalizer (3.4.2) doesn't match a supported version!
  warnings.warn(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/dingku/jupyter_env/lib/python3.12/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/dingku/jupyter_env/lib/python3.12/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Loading base model and tokenizer...
Loading LoRA adapter...
Found 1000 sentences to translate.

Translating:   0%|                             | 1/1000 [00:01<25:50,  1.55s/it]

[1/1000]
EN: NDTV has learnt from sources that the T20 World Cup 2026 match between India and Pakistan is ON.
MT: ꯑꯦꯟꯗꯤꯇꯤꯚꯥꯏꯅꯥ ꯁꯣꯔꯁꯤꯡꯗꯒꯤ ꯈꯪꯂꯦ ꯃꯗꯨꯗꯤ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯃꯔꯛꯇ ꯇꯤ20 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞ 2026ꯒꯤ ꯃꯦꯆ ꯑꯗꯨ ꯑꯣꯅ
--------------------------------------------------

Translating:   0%|                             | 2/1000 [00:02<15:14,  1.09it/s]

[2/1000]
EN: The PCB placed several demands before the ICC.
MT: ꯄꯤ ꯁꯤ ꯕꯤꯅꯥ ꯑꯥꯏ ꯁꯤ ꯁꯤ ꯗꯥ ꯗꯤꯃꯥꯟ ꯀꯌꯥ ꯊꯝꯈꯤ ꯫
--------------------------------------------------

Translating:   0%|                             | 3/1000 [00:02<14:50,  1.12it/s]

[3/1000]
EN: The PCB pushed for ICC intervention to facilitate a bilateral series between India and Pakistan.
MT: ꯄꯤ ꯁꯤ ꯕꯤꯅꯥ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯃꯔꯛꯇꯥ ꯕꯥꯏꯂꯦꯇꯔꯦꯜ ꯁꯤꯔꯤꯖ ꯑꯃ ꯁꯦꯝꯅꯕꯒꯤꯗꯃꯛ ꯑꯥꯏ ꯁꯤ ꯁꯤꯒꯤ ꯃꯇꯦꯡ ꯄꯥꯡꯅꯕ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯈꯤ ꯫
--------------------------------------------------

Translating:   0%|                             | 4/1000 [00:04<17:06,  1.03s/it]

[4/1000]
EN: Virat Kohli and Rohit Sharma have been demoted to Grade B in BCCI's central contract list for 2025-26.
MT: ꯕꯤꯔꯥꯇ ꯀꯣꯍꯂꯤ ꯑꯃꯁꯨꯡ ꯔꯣꯍꯤꯇ ꯁꯔꯃꯥꯕꯨ ꯏꯪꯁꯣꯛ 2025-26 ꯒꯤ ꯕꯤ ꯁꯤ ꯁꯤ ꯑꯥꯏ ꯒꯤ ꯁꯦꯟꯇꯜ ꯀꯟꯇꯛꯇ ꯂꯤꯁꯇꯗꯥ ꯒꯗ ꯕꯤ ꯗꯥ ꯗꯤꯃꯣꯇ ꯇꯧ
--------------------------------------------------

Translating:   0%|▏                            | 5/1000 [00:05<19:04,  1.15s/it]

[5/1000]
EN: Thirty senior men's cricketers have been awarded central contracts, with the BCCI doing away with the A+ grade.
MT: ꯑꯦ+ ꯒꯗ ꯂꯧꯊꯣꯛꯄꯥ ꯕꯤ ꯁꯤ ꯁꯤ ꯑꯥꯏꯒꯥ ꯂꯣꯏꯅꯅ ꯁꯦꯅꯤꯌꯔ ꯃꯦꯟꯁꯀꯤ ꯀꯀꯤꯇꯔ ꯑꯍꯨꯝꯅꯥ ꯁꯦꯟꯇꯦꯜ ꯀꯟꯇꯛꯇꯁꯤꯡ ꯐꯪ
--------------------------------------------------

Translating:   1%|▏                            | 6/1000 [00:06<19:53,  1.20s/it]

[6/1000]
EN: As per the 2024-25 BCCI contracts, any player in Grade A would receive Rs 5 crore annually.
MT: ꯏꯪꯁꯣꯛ- ꯕꯤ ꯁꯤ ꯁꯤ ꯑꯥꯏ ꯀꯟꯇꯛꯇꯁꯤꯡꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯒꯗ ꯑꯦꯗꯥ ꯂꯩꯕ ꯁꯥꯟꯅꯔꯣꯏ ꯑꯃꯍꯦꯛꯇꯅꯥ ꯆꯍꯤꯒꯤ ꯑꯣꯏꯅ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯐꯪꯒꯅꯤ ꯫
--------------------------------------------------

Translating:   1%|▏                            | 7/1000 [00:07<17:14,  1.04s/it]

[7/1000]
EN: Grade B players would get Rs 3 crore, while
MT: ꯒꯗ ꯕꯤꯒꯤ ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡꯅ ꯂꯨꯄꯥ ꯀꯔꯣꯔ 3 ꯐꯪꯒꯅꯤ ꯫
--------------------------------------------------

Translating:   1%|▏                            | 8/1000 [00:08<15:24,  1.07it/s]

[8/1000]
EN: Grade C players would get Rs 1 crore.
MT: ꯒꯗ ꯁꯤꯒꯤ ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡꯅꯥ ꯂꯨꯄꯥ ꯀꯔꯣꯔ 1 ꯐꯪꯒꯅꯤ ꯫
--------------------------------------------------

Translating:   1%|▎                            | 9/1000 [00:09<18:22,  1.11s/it]

[9/1000]
EN: Earlier, Grade A+ players (Kohli, Rohit, Jasprit Bumrah, Ravindra Jadeja) used to receive Rs 7 crore.
MT: ꯃꯃꯥꯡꯗ ꯒꯗ ꯑꯦ+ ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡ (ꯀꯣꯍꯂꯤ, ꯔꯣꯍꯤꯇ, ꯖꯁꯄꯤꯇ ꯕꯨꯔꯃꯔꯥ, ꯔꯕꯤꯟꯗ ꯖꯗꯦꯖꯥꯅꯥ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯐꯪꯂꯝꯃꯤ ꯫
--------------------------------------------------

Translating:   1%|▎                           | 10/1000 [00:10<18:54,  1.15s/it]

[10/1000]
EN: The BCCI has not yet officially declared whether the payment structure for 2025-26 will be any different.
MT: ꯏꯪꯁꯣꯛ 2025-26 ꯒꯤ ꯄꯦꯃꯦꯟꯇꯁꯇꯆꯔ ꯑꯗꯨ ꯈꯦꯠꯅꯒꯗ ꯍꯥꯏꯕꯗꯨ ꯕꯤ ꯁꯤ ꯁꯤ ꯑꯥꯏꯅꯥ ꯍꯧꯖꯤꯛ ꯐꯥꯎꯕ ꯑꯣꯐꯤꯁꯤꯌꯦꯜ ꯑꯣꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:   1%|▎                           | 11/1000 [00:11<17:37,  1.07s/it]

[11/1000]
EN: 21 women cricketers classified in Grade A, B and C.
MT: ꯒꯗ ꯑꯦ, ꯕꯤ ꯑꯃꯁꯨꯡ ꯁꯤ ꯗꯥ ꯀꯥꯡꯂꯨꯞ ꯈꯥꯏꯗꯣꯛꯄ ꯅꯨꯄꯤꯀꯇꯔ
--------------------------------------------------

Translating:   1%|▎                           | 12/1000 [00:13<19:54,  1.21s/it]

[12/1000]
EN: Harmanpreet Kaur, Smriti Mandhana, Deepti Sharma and Jemimah Rodrigues are the four players to be included in Grade A.
MT: ꯗ ꯑꯦꯗꯥ ꯌꯥꯎꯕꯥ ꯁꯥꯟꯅꯔꯣꯏ ꯃꯔꯤꯗꯤ ꯍꯔꯃꯄꯇ ꯀꯣꯔ,ꯃꯇꯤ ꯃꯟꯙꯅꯥ, ꯗꯤꯞꯇꯤ ꯁꯔꯃꯥ ꯑꯃꯁꯨꯡ ꯖꯦꯃꯤꯃꯥꯍ ꯔꯣꯗꯒꯦꯁꯅꯤ ꯫
--------------------------------------------------

Translating:   1%|▎                           | 13/1000 [00:14<20:21,  1.24s/it]

[13/1000]
EN: The cycle for new central contract is based on performance and volume of games played during the preceding season.
MT: ꯑꯅꯧꯕ ꯁꯦꯟꯇꯜ ꯀꯟꯇꯛꯇꯀꯤ ꯁꯥꯏꯀꯜ ꯑꯁꯤ ꯍꯥꯟꯅꯒꯤ ꯁꯤꯖꯟꯗꯥ ꯁꯥꯟꯅꯔꯤꯕꯥ ꯒꯦꯝꯁꯤꯡꯒꯤ ꯄꯔꯐꯣꯃꯔꯃꯦꯟꯁ ꯑꯃꯁꯨꯡ ꯃꯈꯣꯜꯗꯥ ꯌꯨꯝꯐꯝ ꯑꯣꯏ ꯫
--------------------------------------------------

Translating:   1%|▍                           | 14/1000 [00:15<20:13,  1.23s/it]

[14/1000]
EN: Pakistan and Bangladesh's demands from the International Cricket Council (ICC) have just grown bigger.
MT: ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯀꯥꯎꯟꯁꯤꯜ ( ꯑꯥꯏ ꯁꯤ ꯁꯤ ) ꯗꯒꯤ ꯄꯥꯀꯤꯁꯇꯥꯟ ꯑꯃꯁꯨꯡ ꯕꯪꯒꯂꯦꯁꯀꯤ ꯗꯤꯃꯥꯟꯁꯤꯡ ꯑꯗꯨ ꯍꯧꯖꯤꯛꯃꯛ ꯆꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:   2%|▍                           | 15/1000 [00:16<19:26,  1.18s/it]

[15/1000]
EN: The 2031 edition of the ODI World Cup is set to be played in India and Bangladesh.
MT: ꯑꯣꯗꯤꯑꯥꯏ ꯋꯥꯔꯂꯗ ꯀꯞꯀꯤ ꯏꯗꯤꯁꯟ 2031 ꯑꯁꯤ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡ ꯕꯪꯒꯂꯥꯗꯦꯁꯇꯥ ꯁꯥꯟꯅꯒꯅꯤ ꯫
--------------------------------------------------

Translating:   2%|▍                           | 16/1000 [00:17<17:25,  1.06s/it]

[16/1000]
EN: At present, the hybrid model is applicable until 2027.
MT: ꯍꯧꯖꯤꯛ ꯍꯥꯏꯥꯏꯗ ꯃꯣꯗꯦꯜ ꯑꯁꯤ ꯏꯪꯁꯣꯛ 2027 ꯐꯥꯎꯕꯥ ꯆꯠꯅꯔꯦ ꯫
--------------------------------------------------

Translating:   2%|▍                           | 17/1000 [00:18<18:22,  1.12s/it]

[17/1000]
EN: The extension would allow Bangladesh and Pakistan to play all their matches in Bangladesh and not India.
MT: ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯄꯥ ꯑꯁꯤꯅ ꯕꯪꯒꯂꯦꯁ ꯑꯃꯁꯨꯡ ꯄꯥꯀꯤꯁꯇꯥꯟꯅꯥ ꯃꯈꯣꯏꯒꯤ ꯃꯦꯆ ꯄꯨꯝꯅꯃꯛ ꯕꯪꯒꯥꯂꯗꯦꯁꯇꯥ ꯁꯥꯟꯅꯕꯒꯤ ꯑꯌꯥꯕ ꯄꯤꯒꯅꯤ ꯑꯃꯁꯨꯡ ꯚꯥꯔꯠꯇꯥ ꯅꯠꯇꯦ ꯫
--------------------------------------------------

Translating:   2%|▌                           | 18/1000 [00:20<18:52,  1.15s/it]

[18/1000]
EN: The BCB was represented by its head Aminul Islam Bulbul while PCB chairman Mohsin Naqvi was also present.
MT: ꯕꯤ ꯁꯤ ꯕꯤ ꯒꯤ ꯃꯤꯍꯨꯠ ꯑꯣꯏꯅ ꯃꯁꯤꯒꯤ ꯃꯀꯣꯛ ꯑꯃꯤꯅꯨꯂ ꯏꯁꯂꯥꯃ ꯕꯨꯂꯕꯨꯜ ꯌꯥꯎꯈꯤ ꯑꯗꯨꯒ ꯄꯤ ꯁꯤ ꯚꯤꯒꯤ ꯆꯦꯌꯔꯃꯦꯟ ꯃꯣꯁꯤꯟ ꯅꯀꯚꯤꯁꯨ ꯌꯥꯎꯈꯤ ꯫
--------------------------------------------------

Translating:   2%|▌                           | 19/1000 [00:21<17:22,  1.06s/it]

[19/1000]
EN: ICC's deputy chairman Imran Khawaja was present in the meeting.
MT: ꯃꯤꯐꯝ ꯑꯗꯨꯗ ꯑꯥꯏ ꯁꯤ ꯁꯤꯒꯤ ꯗꯤꯄꯨꯇꯤ ꯆꯦꯌꯔꯃꯦꯟ ꯑꯃꯔꯃꯟ ꯈꯋꯥꯖꯥꯁꯨ ꯌꯥꯎꯈꯤ ꯫
--------------------------------------------------

Translating:   2%|▌                           | 20/1000 [00:21<15:51,  1.03it/s]

[20/1000]
EN: No joint declaration was issued after the four-hour meeting.
MT: ꯄꯨꯡ ꯃꯔꯤꯒꯤ ꯃꯤꯇꯤꯡ ꯑꯗꯨꯒꯤ ꯃꯇꯨꯡꯗ ꯄꯨꯟꯅ ꯂꯥꯎꯊꯣꯛꯄꯥ ꯑꯃꯠꯇ ꯊꯣꯛꯈꯤꯗꯦ ꯫
--------------------------------------------------

Translating:   2%|▌                           | 21/1000 [00:23<17:16,  1.06s/it]

[21/1000]
EN: The hybrid model arrangement was introduced after India refused to tour Pakistan for the 2025 Champions Trophy.
MT: ꯏꯪꯁꯣꯛ 2025ꯒꯤ ꯆꯦꯝꯄꯐꯤꯒꯤꯗꯃꯛ ꯚꯥꯔꯠꯅ ꯄꯥꯀꯤꯁꯇꯥꯟꯗꯥ ꯀꯣꯏꯕ ꯌꯥꯗꯕꯒꯤ ꯃꯇꯨꯡꯗ ꯍꯥꯏꯕꯗ ꯃꯣꯗꯦꯜ ꯑꯦꯔꯦꯟꯖꯃꯦꯟꯇ ꯑꯁꯤ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:   2%|▌                           | 22/1000 [00:23<16:22,  1.00s/it]

[22/1000]
EN: After extensive negotiations, a hybrid model was accepted by all parties, including the ICC.
MT: ꯄꯥꯛ ꯁꯟꯅ ꯋꯥꯔꯤ ꯁꯥꯔꯕ ꯃꯇꯨꯡꯗ, ꯑꯥꯏ ꯁꯤ ꯁꯤ ꯌꯥꯎꯅ ꯄꯥꯔꯇꯤ ꯄꯨꯝꯅꯃꯛꯅꯥ ꯍꯥꯏꯕꯗ ꯃꯣꯗꯦꯜ ꯑꯃ ꯑꯌꯥꯕ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:   2%|▋                           | 23/1000 [00:25<16:45,  1.03s/it]

[23/1000]
EN: The second part of the arrangement states that Pakistan will not travel to India for the 2026 T20 World Cup.
MT: ꯊꯧꯔꯥꯡ ꯑꯗꯨꯒꯤ ꯑꯅꯤ ꯁꯨꯕ ꯁꯔꯨꯛ ꯑꯁꯤꯅ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯄꯥꯀꯤꯁꯇꯥꯟꯅꯥ ꯏꯪ 2026 ꯒꯤ ꯇꯤ20 ꯋꯥꯔꯂꯗ ꯀꯞꯀꯤꯗꯃꯛ ꯏꯟꯗꯤꯌꯥꯗꯥ ꯆꯠꯂꯣꯏ ꯫
--------------------------------------------------

Translating:   2%|▋                           | 24/1000 [00:26<16:34,  1.02s/it]

[24/1000]
EN: As a result, all of Pakistan's matches (even if they reach the final) will be played in Sri Lanka.
MT: ꯃꯁꯤꯒꯤ ꯃꯍꯩ ꯑꯣꯏꯅ, ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯃꯦꯆ ꯄꯨꯝꯅꯃꯛ ( ꯀꯔꯤꯒꯨꯝꯕ ꯃꯈꯣꯏꯅ ꯐꯥꯏꯅꯦꯜꯗ ꯌꯧꯔꯕꯁꯨ ) ꯑꯁꯤꯂꯡꯀꯥꯗꯥ ꯁꯥꯟꯅꯒꯅꯤ ꯫
--------------------------------------------------

Translating:   2%|▋                           | 25/1000 [00:26<15:04,  1.08it/s]

[25/1000]
EN: Bangladesh, Pakistan, and India must be treated the same.
MT: ꯕꯪꯒꯂꯦꯁ, ꯄꯥꯀꯤꯁꯇꯥꯟ ꯑꯃꯁꯨꯡ ꯚꯥꯔꯠꯄꯨ ꯆꯞ ꯃꯥꯟꯅꯅꯥ ꯌꯦꯡꯁꯤꯟꯒꯗꯕꯅꯤ ꯫
--------------------------------------------------

Translating:   3%|▋                           | 26/1000 [00:27<13:51,  1.17it/s]

[26/1000]
EN: Now, Gavaskar has taken an indirect jibe at Hussain
MT: ꯍꯧꯖꯤꯛ ꯒꯥꯚꯥꯁꯀꯔꯅ ꯍꯨꯁꯦꯟꯗꯥ ꯍꯛꯊꯦꯡꯅꯅ ꯌꯦꯠꯂꯤ ꯫
--------------------------------------------------

Translating:   3%|▊                           | 27/1000 [00:28<15:45,  1.03it/s]

[27/1000]
EN: He went on to give the example of the 2003 World Cup, when England refused to tour Zimbabwe in protest against Robert Mugabe's regime.
MT: ꯃꯍꯥꯛꯅ ꯃꯈꯥ ꯇꯥꯅ ꯏꯪ 2003ꯒꯤ ꯋꯥꯔꯂꯗ ꯀꯞꯀꯤ ꯈꯨꯗꯝ ꯄꯤꯈꯤ, ꯃꯇꯝ ꯑꯗꯨꯗ ꯏꯪꯂꯦꯟꯅꯥ ꯔꯣꯕꯔꯇ ꯃꯨꯒꯥꯕꯦꯒꯤ ꯂꯩꯉꯥꯛꯀꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯖꯤꯝꯕꯥꯕꯦꯗꯥ ꯀꯣꯏꯕ ꯌꯥꯈꯤꯗꯦ ꯫
--------------------------------------------------

Translating:   3%|▊                           | 28/1000 [00:29<15:34,  1.04it/s]

[28/1000]
EN: Samson's knock was full of intent but fell short in effectiveness quotient.
MT: ꯁꯦꯝꯁꯣꯟꯒꯤ ꯈꯣꯡꯕ ꯑꯗꯨ ꯏꯟꯇꯦꯟꯇꯅ ꯊꯜꯂꯝꯃꯤ ꯑꯗꯨꯕꯨ ꯑꯦꯐꯦꯛꯇꯤꯚꯦꯟꯁꯤ ꯀꯣꯠꯌꯦꯟꯇꯗꯥ ꯍꯟꯊꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:   3%|▊                           | 29/1000 [00:30<17:06,  1.06s/it]

[29/1000]
EN: With this win, India overtook Pakistan at the summit of Group A courtesy of a superior net run-rate.
MT: ꯃꯁꯤꯒꯤ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯑꯁꯤꯒꯥ ꯂꯣꯏꯅꯅ ꯚꯥꯔꯠꯅꯄ ꯑꯦꯒꯤ ꯁꯝꯑꯦꯝꯇꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯕꯨ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯈꯤꯕꯁꯤ ꯍꯦꯟꯅ ꯐꯕ ꯅꯦꯠ ꯔꯟ-ꯔꯦꯇ ꯂꯩꯕꯅꯅꯤ ꯫
--------------------------------------------------

Translating:   3%|▊                           | 30/1000 [00:32<18:19,  1.13s/it]

[30/1000]
EN: India batter Abhishek Sharma will take no part in the T20 World Cup 2026 clash against Namibia in New Delhi on Thursday.
MT: ꯚꯥꯔꯠꯀꯤ ꯕꯦꯇꯇꯔ ꯑꯚꯥꯁꯤꯛ ꯁꯔꯃꯥꯅꯥ ꯇꯤ20 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞ 2026ꯗꯥ ꯁꯨꯔꯦꯁꯥ ꯅꯨꯃꯤꯠꯇ ꯅ ꯗꯤꯜꯂꯤꯗꯥ ꯅꯥꯏꯃꯤꯕꯥꯒ ꯂꯥꯟꯊꯦꯡꯅꯕꯗ ꯁꯔꯨꯛ ꯌꯥꯔꯣꯏ ꯫
--------------------------------------------------

Translating:   3%|▊                           | 31/1000 [00:33<16:39,  1.03s/it]

[31/1000]
EN: Abhishek isn't fine still, might take one or two games.
MT: ꯑꯕꯤꯆꯦꯛ ꯑꯁꯤ ꯍꯧꯖꯤꯛꯁꯨ ꯐꯗ, ꯒꯦꯝ ꯑꯃ ꯅꯠꯇꯒꯥ ꯑꯅꯤ ꯂꯧꯕ ꯌꯥꯏ ꯫
--------------------------------------------------

Translating:   3%|▉                           | 32/1000 [00:33<13:42,  1.18it/s]

[32/1000]
EN: Samson comes in.
MT: ꯁꯦꯝꯁꯣꯟ ꯆꯪꯁꯤꯜꯂꯛꯏ ꯫
--------------------------------------------------

Translating:   3%|▉                           | 33/1000 [00:34<13:51,  1.16it/s]

[33/1000]
EN: Bumrah comes in for Siraj," said Suryakumar at the toss.
MT: ꯕꯔꯥꯅꯥ ꯁꯤꯔꯥꯖꯒꯤ ꯃꯍꯨꯠꯇ ꯆꯪꯁꯤꯜꯂꯛꯏ ꯍꯥꯏꯅ ꯁꯨꯔꯌꯀꯨꯃꯔꯅꯥ ꯇꯣꯁ ꯇꯧꯕ ꯃꯇꯝꯗ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:   3%|▉                           | 34/1000 [00:35<15:10,  1.06it/s]

[34/1000]
EN: Defending with dew will build our confidence. Hope our batters entertain the crowd.
MT: ꯆꯣꯠ-ꯆꯣꯠꯅꯥ ꯉꯥꯛꯊꯣꯛꯄꯥ ꯑꯁꯤꯅ ꯑꯩꯈꯣꯏꯒꯤ ꯊꯥꯖꯕ ꯍꯦꯟꯒꯠꯍꯟꯒꯅꯤ ꯫ ꯑꯥꯁꯥ ꯂꯩ ꯃꯗꯨꯗꯤꯕꯥ ꯕꯦꯠꯇꯔꯁꯤꯡꯅ ꯃꯤꯌꯥꯝꯕꯨ ꯅꯨꯡꯉꯥꯏꯍꯟ
--------------------------------------------------

Translating:   4%|▉                           | 35/1000 [00:36<13:53,  1.16it/s]

[35/1000]
EN: It's a big tournament, dew will be a big factor.
MT: ꯃꯁꯤ ꯑꯆꯧꯕ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯃꯅꯤ, ꯗ ꯑꯁꯤ ꯑꯆꯧꯕ ꯐꯦꯛꯇꯔ ꯑꯃ ꯑꯣꯏꯒꯅꯤ ꯫
--------------------------------------------------

Translating:   4%|█                           | 36/1000 [00:37<14:21,  1.12it/s]

[36/1000]
EN: India made two changes to the side that beat the USA on the opening day of the tournament.
MT: ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯁꯤꯒꯤ ꯑꯍꯥꯟꯕꯥ ꯅꯨꯃꯤꯠꯗꯥ ꯌꯨꯑꯦꯁꯑꯦꯕꯨ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯔꯕꯥ ꯁꯥꯏꯗ ꯑꯁꯤꯗ ꯚꯥꯔꯠꯅ ꯑꯅꯤ ꯍꯣꯡꯗꯣꯛ
--------------------------------------------------

Translating:   4%|█                           | 37/1000 [00:38<15:54,  1.01it/s]

[37/1000]
EN: Sanju Samson replaced Abhishek, while Jasprit Bumrah replaced Mohammed Siraj in the India XI.
MT: ꯑꯕꯤꯆꯦꯛꯀꯤ ꯃꯐꯝꯗꯥ ꯁꯟꯖꯨ ꯁꯦꯝꯁꯣꯟ ꯑꯃꯁꯨꯡ ꯏꯟꯗꯤꯌꯥ XI ꯗꯥ ꯃꯣꯍꯝꯃꯗ ꯁꯤꯔꯥꯖꯒꯤ ꯃꯐꯝꯗ ꯖꯁꯄꯤꯇ ꯕꯃꯔꯥꯅ ꯐꯝ ꯂꯧ
--------------------------------------------------

Translating:   4%|█                           | 38/1000 [00:39<16:16,  1.02s/it]

[38/1000]
EN: India take on Pakistan next, with the team set to travel to Colombo for the game on February 15.
MT: ꯚꯥꯔꯠꯅ ꯃꯊꯪꯗꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯥ ꯂꯝꯕꯥ ꯇꯧꯒꯅꯤ, ꯇꯤꯝ ꯑꯁꯤ ꯐꯕꯋꯥꯔꯤꯗꯥ ꯃꯁꯥꯟꯅ ꯑꯁꯤꯒꯤꯗꯃꯛ ꯀꯣꯂꯝꯕꯣꯗꯥ ꯆꯠꯀꯅꯤ ꯫
--------------------------------------------------

Translating:   4%|█                           | 39/1000 [00:40<15:03,  1.06it/s]

[39/1000]
EN: The cabinet agreed with certain conditions as per the Cunha report.
MT: ꯀꯨꯅꯍꯥ ꯔꯤꯄꯣꯔꯇꯀꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯀꯦꯕꯤꯅꯦꯠꯅꯥ ꯑꯀꯛꯅꯕ ꯀꯟꯗꯤꯁꯟꯁꯤꯡ ꯌꯥꯅꯈꯤ ꯫
--------------------------------------------------

Translating:   4%|█                           | 40/1000 [00:40<13:46,  1.16it/s]

[40/1000]
EN: He mentioned in the report a maximum of 35,000 people and other conditions.
MT: ꯃꯍꯥꯛꯅ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯗ ꯃꯤ 35,000 ꯑꯃꯁꯨꯡ ꯑꯇꯩ ꯐꯤꯚꯝꯁꯤꯡ ꯄꯟꯈꯤ ꯫
--------------------------------------------------

Translating:   4%|█▏                          | 41/1000 [00:42<16:12,  1.01s/it]

[41/1000]
EN: India reached the 100-run mark in just 6.5 overs - the fastest team hundred in T20 World Cup history.
MT: ꯚꯥꯔꯠꯅ ꯑꯣꯚꯔ ꯈꯛꯇꯗꯥ ꯔꯟꯒꯤ ꯃꯥꯔꯛ ꯌꯧꯈꯤ - ꯃꯁꯤ ꯇꯤ20 ꯋꯥꯔꯜꯗ ꯀꯞꯀꯤ ꯍꯤꯁꯇꯔꯤꯗꯥ ꯊꯨꯅ ꯇꯧꯕ ꯇꯤꯝ ꯁꯦꯟꯆꯨꯔꯤ
--------------------------------------------------

Translating:   4%|█▏                          | 42/1000 [00:43<15:40,  1.02it/s]

[42/1000]
EN: After being asked to bat first, India were off to a decent start, making 8/0 in the first over.
MT: ꯑꯍꯥꯟꯕꯗꯥ ꯕꯦꯇ ꯇꯧꯅꯕ ꯍꯥꯏꯔꯕ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯅ ꯑꯍꯥꯟꯕꯥ ꯑꯣꯚꯔꯗꯥ/0 ꯂꯧꯗꯨꯅ ꯐꯖꯅ ꯍꯧ
--------------------------------------------------

Translating:   4%|█▏                          | 43/1000 [00:44<16:05,  1.01s/it]

[43/1000]
EN: After four overs, the defending champions reached 43/1, with Ishan Kishan finding a couple of boundaries.
MT: ꯑꯣꯚꯔ ꯃꯔꯤꯒꯤ ꯃꯇꯨꯡꯗ, ꯗꯤꯐꯟꯗꯤꯡ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯡꯅ 43/1 ꯌꯧꯈꯤ, ꯏꯁꯥꯟ ꯀꯤꯁꯟꯅ ꯐꯥꯎꯟꯗꯔꯤ ꯑꯅꯤ ꯐꯪ
--------------------------------------------------

Translating:   4%|█▏                          | 44/1000 [00:45<17:49,  1.12s/it]

[44/1000]
EN: On the first ball of the 11th over, spinner Bernard Scholtz dismissed captain Suryakumar Yadav for just 12.
MT: 11 ꯁꯨꯕꯥ ꯑꯣꯚꯔꯒꯤ ꯑꯍꯥꯟꯕꯥ ꯕꯣꯂꯗꯥ ꯁꯄꯤꯅꯔ ꯕꯔꯅꯥꯗ ꯁꯀꯣꯜꯇꯖꯅ ꯀꯦꯞꯇꯦꯟ ꯁꯨꯔꯌꯀꯨꯃꯔ ꯌꯥꯗꯕꯕꯨ 12 ꯈꯛꯇꯗꯥ ꯕꯣꯜ ꯂꯧꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:   4%|█▎                          | 45/1000 [00:46<19:19,  1.21s/it]

[45/1000]
EN: India lost another wicket quickly when Tilak Varma was removed for 25 by Namibia skipper Erasmus in the 12th over.
MT: ꯇꯤꯂꯛ ꯕꯔꯃꯥꯕꯨ ꯅꯤꯃꯤꯕꯥꯒꯤ ꯀꯦꯞꯇꯦꯟ ꯏꯔꯥꯁꯃꯁꯅꯥ 12 ꯁꯨꯕꯥ ꯑꯣꯚꯔꯗꯥ 25 ꯗꯥ ꯑꯥꯎꯠ ꯇꯧꯈꯤꯕꯗꯒꯤ ꯚꯥꯔꯠꯅ ꯑꯇꯣꯞꯄ ꯋꯤꯀꯦꯇ ꯑꯃ ꯊꯨꯅ ꯃꯥꯡꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▎                          | 46/1000 [00:48<19:56,  1.25s/it]

[46/1000]
EN: Shivam Dube and Hardik Pandya then combined to hammer 24 runs off Bernard Scholtz as India raced to 168/4.
MT: ꯃꯗꯨꯒꯤ ꯃꯇꯨꯡꯗ ꯁꯤꯚꯝ ꯗꯨꯕꯦ ꯑꯃꯁꯨꯡ ꯍꯔꯗꯤꯛ ꯄꯥꯟꯗꯅꯥ ꯕꯔꯅꯥꯔ ꯁꯀꯣꯜꯇꯖꯗꯥ ꯔꯟ 24 ꯆꯡꯗꯨꯅ ꯚꯥꯔꯠꯇꯥ/ ꯗꯥ ꯆꯪꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▎                          | 47/1000 [00:49<18:54,  1.19s/it]

[47/1000]
EN: By the end of the 18th over, India had reached 199/4 with Pandya and Dube going strong.
MT: 18 ꯁꯨꯕꯥ ꯑꯣꯚꯔ ꯂꯣꯏꯔꯛꯄꯗꯥ ꯄꯥꯟꯗ ꯑꯃꯁꯨꯡ ꯗꯨꯕꯦꯅꯥ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯄꯥꯒ ꯂꯣꯏꯅꯅꯥ ꯚꯥꯔꯠꯅ/ ꯌꯧꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▎                          | 48/1000 [00:50<19:00,  1.20s/it]

[48/1000]
EN: On the first ball of the 19th over, Pandya completed his fifty off 27 deliveries as India crossed the 200-run mark.
MT: 19 ꯁꯨꯕꯥ ꯑꯣꯚꯔꯒꯤ ꯑꯍꯥꯟꯕꯥ ꯕꯣꯂꯗꯥ ꯄꯥꯟꯗꯌꯥꯅꯥ ꯃꯍꯥꯛꯀꯤ ꯐꯤꯐꯇꯤ ꯑꯗꯨ 27 ꯗꯥ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯑꯃꯁꯨꯡ ꯚꯥꯔꯠꯅ ꯔꯟ 200 ꯄꯥꯊꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▎                          | 49/1000 [00:51<17:33,  1.11s/it]

[49/1000]
EN: Shivam Dube was run out for 23 after a mix-up with Rinku Singh.
MT: ꯁꯤꯚꯝ ꯗꯨꯕꯦ ꯔꯤꯟꯀꯨ ꯁꯤꯡꯍꯒꯥ ꯌꯥꯟꯁꯤꯟꯅꯔꯕꯥ ꯃꯇꯨꯡꯗ 23 ꯗꯥ ꯔꯟꯑꯥꯎꯇ ꯑꯣꯏꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▍                          | 50/1000 [00:52<18:31,  1.17s/it]

[50/1000]
EN: India then lost Rinku Singh (1) and Arshdeep Singh (2) in the final over, finishing at 209/9.
MT: ꯃꯗꯨꯒꯤ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯅ ꯑꯔꯣꯏꯕ ꯑꯣꯚꯔꯗꯥ ꯔꯤꯟꯀꯨ ꯁꯤꯡꯍ (1 ) ꯑꯃꯁꯨꯡ ꯑꯥꯔꯁꯗꯤꯄ ꯁꯤꯡꯍꯕꯨ (2 ) ꯃꯥꯡꯈꯤ, ꯃꯗꯨꯅ/9 ꯗꯥ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▍                          | 51/1000 [00:54<21:31,  1.36s/it]

[51/1000]
EN: ICC Men’s T20 World Cup 2026 began on February 7, 2026, at Sinhalese Sports Club Ground with Pakistan playing Netherlands in the opening match.
MT: ꯑꯥꯏ ꯁꯤ ꯁꯤ ꯃꯦꯟꯒꯤ ꯇꯤ20 ꯋꯥꯔꯂꯗ ꯀꯞ 2026 ꯑꯁꯤ ꯏꯪꯁꯣꯛ ꯒꯤ ꯐꯦꯕꯋꯥꯔꯤ ꯗꯥ ꯁꯤꯟꯍꯥꯂꯤꯁꯄꯣꯔꯇꯕꯥꯎꯟꯗꯗꯥ ꯍꯧꯈꯤ ꯑꯃꯁꯨꯡ ꯑꯍꯥꯟꯕ ꯃꯦꯆ ꯑꯗꯨꯗ ꯅꯦꯗꯔꯂꯦꯟꯗꯁꯀ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯥ ꯁꯥꯟꯅꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▍                          | 52/1000 [00:56<22:04,  1.40s/it]

[52/1000]
EN: Bangladesh national cricket team faced the India men's national cricket team in an opening match reported ahead of the 2026 T20 tournament.
MT: ꯏꯪꯁꯣꯛ 2026 ꯒꯤ ꯇꯤ20 ꯇꯣꯔꯅꯥꯃꯦꯟꯇꯒꯤ ꯃꯃꯥꯡꯗ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯑꯍꯥꯟꯕꯥ ꯃꯦꯆ ꯑꯃꯗ ꯕꯪꯒꯂꯦꯁ ꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯇꯤꯝꯅꯥ ꯏꯟꯗꯤꯌꯥ ꯃꯦꯟ ꯭ ꯁ ꯅꯦꯁꯅꯦꯜꯀꯦꯇ ꯇꯤꯝꯒꯥ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▍                          | 53/1000 [00:56<18:38,  1.18s/it]

[53/1000]
EN: Ishan Kishan struck a rapid half-century.
MT: ꯏꯁꯥꯟ ꯀꯤꯁꯟꯅ ꯌꯥꯝꯅ ꯊꯨꯅ ꯁꯦꯟꯆꯨꯔꯤ ꯍꯥꯐ ꯂꯧꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▌                          | 54/1000 [00:58<18:49,  1.19s/it]

[54/1000]
EN: Faf du Plessis scored a half-century and Mitchell Starc took a five-wicket haul in the same match report.
MT: ꯐꯐ ꯗꯨꯂꯤꯁ ꯍꯥꯐ-ꯆꯦꯟꯆꯨꯔꯤ ꯑꯃꯥ ꯂꯧꯈꯤ ꯑꯃꯁꯨꯡ ꯃꯤꯆꯦꯜꯔꯀꯅꯥ ꯃꯦꯆ ꯑꯁꯤꯒꯤ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯃꯛꯇꯗꯥ ꯋꯤꯀꯦꯇ ꯃꯉꯥ ꯂꯧ
--------------------------------------------------

Translating:   6%|█▌                          | 55/1000 [00:59<20:23,  1.29s/it]

[55/1000]
EN: Jasprit Bumrah and Ravindra Jadeja were reported to have been demoted in the 2025–26 central contracts discussion.
MT: ꯖꯁꯄꯤꯇ ꯕꯃꯔꯥ ꯑꯃꯁꯨꯡ ꯔꯕꯤꯟꯗ ꯖꯗꯦꯖꯥ ꯑꯁꯤ ꯏꯪ 2025-26 ꯒꯤ ꯁꯦꯟꯇꯦꯜ ꯀꯟꯇꯛꯇꯁꯤꯡꯒꯤ ꯈꯟꯅ-ꯆꯠꯇꯗꯥ ꯗꯤꯃꯣꯇ ꯇꯧ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝꯈꯤ ꯫
--------------------------------------------------

Translating:   6%|█▌                          | 56/1000 [01:00<19:35,  1.25s/it]

[56/1000]
EN: Rohit Sharma carried the men’s T20 World Cup trophy during a promotional appearance.
MT: ꯔꯣꯍꯤꯇ ꯁꯔꯃꯥꯅꯥ ꯅꯨꯄꯥꯁꯤꯡꯒꯤ ꯇꯤ20 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞꯀꯤ ꯇꯐꯤ ꯑꯗꯨ ꯄꯃꯣꯁꯅꯦꯜꯒꯤ ꯊꯧꯔꯝ ꯑꯃꯗ ꯄꯥꯏ
--------------------------------------------------

Translating:   6%|█▌                          | 57/1000 [01:02<20:32,  1.31s/it]

[57/1000]
EN: The International Cricket Council update said a high-profile match involving Pakistan would go ahead on February 15, 2026, in Colombo.
MT: ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯀꯥꯎꯟꯁꯤꯜ ꯑꯞꯇꯦꯠꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯄꯥꯀꯤꯁꯇꯥꯟ ꯌꯥꯎꯕꯥ ꯑꯋꯥꯡꯕ ꯊꯥꯛꯀꯤ ꯃꯦꯆ ꯑꯃꯥ ꯏꯪꯁꯣꯛꯒꯤ ꯐꯦꯕꯋꯥꯔꯤꯗꯥ ꯀꯣꯂꯝꯕꯣꯗꯥ ꯄꯥꯡꯊꯣꯛꯀꯅꯤ ꯫
--------------------------------------------------

Translating:   6%|█▌                          | 58/1000 [01:03<20:13,  1.29s/it]

[58/1000]
EN: The New Zealand national cricket team lost the first ODI by four wickets to the India men's national cricket team.
MT: ꯅꯌꯨ ꯖꯤꯂꯦꯟꯗ ꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯇꯤꯝ ꯑꯁꯤ ꯑꯍꯥꯟꯕ ꯑꯣꯗꯤꯑꯥꯏ ꯑꯗꯨ ꯏꯟꯗꯤꯌꯥ ꯃꯦꯟ ꯭ ꯁ ꯅꯦꯁꯅꯦꯜꯀꯦꯇ ꯇꯤꯝꯗꯥ ꯋꯤꯀꯇꯤꯠ ꯃꯔꯤꯅꯥ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:   6%|█▋                          | 59/1000 [01:05<22:09,  1.41s/it]

[59/1000]
EN: Australia national cricket team ended day one at 67 for seven in reply to 150 by the India men's national cricket team in a Test match post.
MT: ꯑꯣꯁꯇꯂꯤꯌꯥ ꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯇꯤꯝꯅꯥ ꯇꯦꯁꯇ ꯃꯦꯆ ꯄꯣꯁ ꯭ ꯠ ꯑꯃꯗ ꯏꯟꯗꯤꯌꯥ ꯃꯦꯟ ꯭ ꯁ ꯅꯦꯁꯅꯦꯜ ꯀꯔꯦꯀꯦꯠ ꯇꯤꯝꯅ ꯄꯤꯈꯤꯕ 150 ꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯑꯍꯥꯟꯕ ꯅꯨꯃꯤꯠꯗꯥ ꯁꯇꯦꯅꯗ ꯂꯧ
--------------------------------------------------

Translating:   6%|█▋                          | 60/1000 [01:06<24:33,  1.57s/it]

[60/1000]
EN: The India national under-19 cricket team won the ICC U19 World Cup final by 100 runs against the England national under-19 cricket team in Harare.
MT: ꯚꯥꯔꯠꯀꯤ ꯅꯦꯁꯅꯦꯜ ꯑꯟꯗꯔ-19 ꯀꯀꯦꯠ ꯇꯤꯝꯅꯥ ꯍꯔꯥꯔꯦꯗꯥ ꯄꯥꯡꯊꯣꯛꯂꯤꯕꯥ ꯑꯥꯏ ꯁꯤ ꯁꯤ ꯎꯅ 19 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞꯀꯤ ꯐꯥꯏꯅꯦꯜꯗꯥ ꯏꯡꯒꯂꯦꯟꯗ ꯅꯦꯁꯅꯦꯜ ꯑꯥꯟꯗꯔ-ꯀꯤꯠ ꯇꯤꯝꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯔꯟ ꯆꯥꯅꯥ ꯃꯥꯏꯄꯥꯛ
--------------------------------------------------

Translating:   6%|█▋                          | 61/1000 [01:08<22:15,  1.42s/it]

[61/1000]
EN: Members of the India women's national cricket team were given a grand welcome after their title-winning campaign.
MT: ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯇꯤꯝꯒꯤ ꯃꯤꯍꯨꯠꯁꯤꯡꯕꯨ ꯃꯈꯣꯏꯒꯤ ꯇꯥꯏꯇꯜ ꯃꯥꯏ ꯄꯥꯛꯄꯥ ꯀꯝꯄꯦꯟꯒꯤ ꯃꯇꯨꯡꯗ ꯆꯥꯎꯔꯕꯥ ꯃꯅꯥ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:   6%|█▋                          | 62/1000 [01:09<21:20,  1.37s/it]

[62/1000]
EN: The India women's national cricket team lifting the ICC Women’s World Cup as one of the year’s landmark moments.
MT: ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯇꯤꯝꯅꯥ ꯑꯥꯏ ꯁꯤ ꯁꯤ ꯅꯨꯄꯤꯒꯤ ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞ ꯑꯁꯤ ꯆꯍꯤ ꯑꯁꯤꯒꯤ ꯃꯁꯛ ꯊꯣꯛꯄ ꯃꯨꯅꯇꯁꯤꯡꯒꯤ ꯃꯅꯨꯡꯗ ꯑꯃꯥ ꯑꯣꯏꯅ ꯄꯥꯏꯈꯠꯂꯤ ꯫
--------------------------------------------------

Translating:   6%|█▊                          | 63/1000 [01:10<20:59,  1.34s/it]

[63/1000]
EN: The Indian Premier League season in 2025 was reported as suspended indefinitely amid escalating India–Pakistan military tensions.
MT: ꯏꯪꯁꯣꯛ 2025 ꯗꯥ ꯏꯟꯗꯤꯌꯟꯃꯤꯌꯔ ꯂꯤꯒ ꯁꯤꯖꯟ ꯑꯁꯤ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯃꯤꯂꯤꯇꯔꯤ ꯇꯦꯟꯁꯟꯁꯤꯡ ꯍꯦꯟꯒꯠꯂꯛꯄꯒꯤ ꯃꯔꯛꯇ ꯃꯇꯝ ꯈꯔꯒꯤ ꯑꯣꯏꯅ ꯂꯦꯞꯈꯤ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝꯈꯤ ꯫
--------------------------------------------------

Translating:   6%|█▊                          | 64/1000 [01:11<19:46,  1.27s/it]

[64/1000]
EN: The Eden Gardens hosted the opening spectacle for the 18th edition of the Indian Premier League.
MT: ꯏꯟꯗꯤꯌꯟꯃꯤꯌꯔ ꯂꯤꯒꯀꯤ 18 ꯁꯨꯕꯥ ꯑꯦꯗꯤꯁꯟ ꯑꯁꯤꯒꯤ ꯑꯍꯥꯟꯕꯥ ꯃꯃꯤ ꯀꯨꯝꯍꯩ ꯑꯗꯨ ꯏꯗꯦꯟ ꯒꯥꯔꯗꯦꯟꯁꯅꯥ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:   6%|█▊                          | 65/1000 [01:12<19:15,  1.24s/it]

[65/1000]
EN: Royal Challengers Bengaluru named Rajat Patidar as captain for the season starting March 21.
MT: ꯔꯣꯌꯦꯜ ꯆꯦꯂꯦꯟꯖꯔ ꯕꯦꯡꯂꯨꯨꯔꯥꯅꯥ ꯃꯥꯔꯗꯒꯤ ꯍꯧꯕꯥ ꯁꯤꯖꯟ ꯑꯁꯤꯒꯤ ꯀꯦꯞꯇꯦꯟ ꯑꯣꯏꯅ ꯔꯥꯖꯥꯇ ꯄꯥꯇꯤꯗꯥꯔꯕꯨ ꯈꯟꯈꯤ ꯫
--------------------------------------------------

Translating:   7%|█▊                          | 66/1000 [01:13<18:34,  1.19s/it]

[66/1000]
EN: Chennai Super Kings posted their lowest home total and suffered a fifth straight loss.
MT: ꯆꯦꯟꯅꯥꯏ ꯁꯨꯄꯔ ꯀꯤꯡꯁꯅ ꯃꯈꯣꯏꯒꯤ ꯅꯦꯝꯕꯥ ꯍꯣꯝ ꯇꯣꯇꯥꯜ ꯄꯣꯁ ꯭ ꯠ ꯇꯧꯈꯤ ꯑꯃꯁꯨꯡ ꯃꯊꯪꯅꯥ ꯃꯉꯥꯁꯨꯕꯗꯥ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:   7%|█▉                          | 67/1000 [01:15<19:12,  1.24s/it]

[67/1000]
EN: A Dharamsala fixture involving Punjab Kings and Delhi Capitals was called off after a blackout.
MT: ꯄꯟꯖꯥꯕ ꯀꯤꯡꯁ ꯑꯃꯁꯨꯡ ꯗꯤꯜꯂꯤ ꯀꯦꯄꯤꯇꯦꯜꯁꯤꯡ ꯌꯥꯎꯕꯥ ꯙꯔꯃꯁꯥꯂꯥ ꯐꯤꯆꯆꯔ ꯑꯃ ꯕꯦꯛꯑꯥꯎꯇ ꯑꯃꯒꯤ ꯃꯇꯨꯡꯗ ꯊꯤꯡꯖꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:   7%|█▉                          | 68/1000 [01:16<17:46,  1.14s/it]

[68/1000]
EN: Punjab Kings defeated Mumbai Indians in Jaipur to secure a top-two league finish.
MT: ꯄꯟꯖꯥꯕ ꯀꯤꯡꯁꯅ ꯃꯨꯝꯕꯥꯏ ꯏꯟꯗꯤꯌꯟꯁꯄꯨ ꯖꯦꯄꯨꯔꯗꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯗꯨꯅ ꯇꯣꯞ-ꯇꯧꯄ ꯂꯤꯒ ꯂꯣꯏꯁꯤꯟ
--------------------------------------------------

Translating:   7%|█▉                          | 69/1000 [01:17<19:14,  1.24s/it]

[69/1000]
EN: KL Rahul became the fastest Indian to 8,000 T20 runs after an unbeaten 112.
MT: ꯀꯦ ꯑꯦꯜ ꯔꯥꯍꯨꯜꯅꯥ ꯑꯇꯤꯇꯥꯏꯕ ꯇꯧꯗꯕꯥ ꯔꯟ 112 ꯂꯧꯔꯕꯥ ꯃꯇꯨꯡꯗ ꯇꯤ20 ꯗꯥ ꯔꯅ 8,000 ꯂꯧꯕꯥ ꯈ ꯭ ꯋꯥꯏꯗꯒꯤ ꯊꯨꯅ ꯇꯧꯕ ꯏꯟꯗꯤꯌꯟ ꯑꯣꯏꯈꯤ ꯫
--------------------------------------------------

Translating:   7%|█▉                          | 70/1000 [01:18<19:15,  1.24s/it]

[70/1000]
EN: Virat Kohli spoke about the June 4 stampede linked to his franchise’s celebrations.
MT: ꯕꯤꯔꯥꯇ ꯀꯣꯍꯂꯤꯅꯥ ꯖꯨꯟꯇꯥ ꯃꯍꯥꯛꯀꯤ ꯐꯔꯦꯟꯆꯥꯏꯖꯤꯒꯤ ꯊꯧꯔꯝꯒꯥ ꯃꯔꯤ ꯂꯩꯅꯅ ꯊꯣꯛꯈꯤꯕ ꯁꯀꯦꯝꯄꯤꯗꯦꯒꯤ ꯃꯇꯥꯡꯗ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:   7%|█▉                          | 71/1000 [01:19<18:23,  1.19s/it]

[71/1000]
EN: The uncertainty over player retention created suspense ahead of the next Indian Premier League season.
MT: ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡ ꯊꯝꯕꯗꯥ ꯑꯔꯦꯞꯄ ꯂꯩꯇꯕꯥ ꯑꯁꯤꯅ ꯃꯊꯪꯒꯤ ꯏꯟꯗꯤꯌꯟꯃꯤꯌꯔ ꯂꯤꯒ ꯁꯤꯖꯟ ꯑꯁꯤꯒꯤ ꯃꯃꯥꯡꯗ ꯁꯁꯄꯦꯟꯁ ꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:   7%|██                          | 72/1000 [01:20<15:52,  1.03s/it]

[72/1000]
EN: Rafael Nadal announced he would retire.
MT: ꯔꯥꯐꯦꯜ ꯅꯥꯗꯥꯜꯅꯥ ꯃꯍꯥꯛꯅ ꯔꯤꯇꯔ ꯇꯧꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:   7%|██                          | 73/1000 [01:21<16:05,  1.04s/it]

[73/1000]
EN: Carlos Alcaraz beat Novak Djokovic to win his first major title.
MT: ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯅꯣꯕꯥꯛ ꯖꯣꯀꯣꯚꯤꯀꯄꯨ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯗꯨꯅ ꯃꯍꯥꯛꯀꯤ ꯑꯍꯥꯟꯕꯥ ꯃꯦꯒꯔ ꯇꯥꯏꯇꯥꯜ ꯑꯗꯨ ꯐꯪ
--------------------------------------------------

Translating:   7%|██                          | 74/1000 [01:22<16:22,  1.06s/it]

[74/1000]
EN: Alexander Zverev lost a marathon match to Carlos Alcaraz in a five-set battle.
MT: ꯑꯂꯦꯛꯖꯦꯟꯗꯔ ꯖꯚꯦꯔꯦꯚꯅꯥ ꯁꯦꯇ ꯃꯉꯥꯒꯤ ꯂꯥꯟꯗꯥ ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯒꯥ ꯃꯥꯔꯥꯊꯣꯟ ꯃꯦꯆ ꯑꯃ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:   8%|██                          | 75/1000 [01:23<15:36,  1.01s/it]

[75/1000]
EN: Rohan Bopanna announced his retirement from professional tennis.
MT: ꯔꯣꯍꯟ ꯕꯣꯄꯟꯅꯥꯅꯥ ꯄꯐꯦꯁꯅꯦꯜ ꯇꯦꯅꯤꯁꯇꯒꯤ ꯃꯍꯥꯛꯀꯤ ꯔꯤꯑꯥꯏꯇꯔꯃꯦꯟꯠ ꯑꯗꯨ ꯂꯥꯎꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:   8%|██▏                         | 76/1000 [01:24<16:09,  1.05s/it]

[76/1000]
EN: A 14-place leap that signaled an upswing for India Davis Cup team in international tennis standings.
MT: ꯏꯟꯗꯤꯌꯥ ꯗꯦꯚꯤꯁ ꯀꯄ ꯇꯤꯝꯒꯤꯗꯃꯛ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯇꯦꯅꯤꯁ ꯁꯇꯦꯟꯗꯤꯡꯗꯥ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯕꯒꯤ ꯈꯨꯗꯝ ꯄꯤꯔꯕꯥ ꯃꯐꯝ 14ꯒꯤ ꯂꯤꯞ ꯑꯃꯥ
--------------------------------------------------

Translating:   8%|██▏                         | 77/1000 [01:26<16:57,  1.10s/it]

[77/1000]
EN: Elena Rybakina overcame Aryna Sabalenka to win the 2026 Australian Open final.
MT: ꯑꯦꯂꯦꯅꯥ ꯔꯥꯏꯕꯥꯀꯤꯅꯥꯅꯥ ꯑꯔꯅꯥ ꯁꯕꯥꯂꯦꯟꯀꯥꯕꯨ ꯃꯥꯏꯊꯤꯗꯨꯅꯥ ꯏꯪꯁꯣꯛ 2026 ꯑꯣꯁꯇꯂꯤꯌꯥ ꯑꯣꯄꯟ ꯐꯥꯏꯅꯦꯜꯗꯥ ꯃꯥꯏꯄꯥꯛ
--------------------------------------------------

Translating:   8%|██▏                         | 78/1000 [01:27<16:58,  1.10s/it]

[78/1000]
EN: Novak Djokovic became the first player to reach 400 Grand Slam singles match wins in the Open Era.
MT: ꯑꯣꯄꯟ ꯏꯔꯥꯗꯥ ꯅꯣꯕꯥꯛ ꯖꯣꯀꯣꯚꯤꯀꯅꯥꯥꯟꯗ ꯁꯂꯥꯝ ꯁꯤꯡꯒꯜꯁ ꯃꯦꯆ 400 ꯃꯥꯏ ꯄꯥꯛꯄꯥ ꯑꯍꯥꯟꯕ ꯁꯥꯟꯅꯔꯣꯏ ꯑꯣꯏꯈꯤ ꯫
--------------------------------------------------

Translating:   8%|██▏                         | 79/1000 [01:28<16:50,  1.10s/it]

[79/1000]
EN: The India men's national field hockey team and its Olympic bronze-medal campaign in a dedicated post.
MT: ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯥꯁꯤꯡꯒꯤ ꯅꯦꯁꯅꯦꯜ ꯐꯤꯜꯗ ꯍꯣꯀꯤ ꯇꯤꯝ ꯑꯃꯁꯨꯡ ꯃꯁꯤꯒꯤ ꯑꯣꯂꯤꯝꯄꯤꯛꯣꯟꯖ-ꯃꯦꯗꯦꯜ ꯀꯦꯝꯄꯦꯟ ꯑꯁꯤ ꯀꯠꯊꯣꯛꯂꯕ ꯄꯣꯇ ꯑꯃꯗ
--------------------------------------------------

Translating:   8%|██▏                         | 80/1000 [01:29<15:09,  1.01it/s]

[80/1000]
EN:  The India men's national field hockey team across major tournaments.
MT: ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯥꯁꯤꯡꯒꯤ ꯅꯦꯁꯅꯦꯜ ꯐꯤꯜꯗ ꯍꯣꯀꯤ ꯇꯤꯝꯅꯥ ꯑꯆꯧꯕ ꯇꯨꯔꯥꯅꯃꯦꯟꯇꯁꯤꯡ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:   8%|██▎                         | 81/1000 [01:30<16:13,  1.06s/it]

[81/1000]
EN: The India men's national field hockey team beat South Korea men's national field hockey team 4–1 in a match update.
MT: ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯥꯁꯤꯡꯒꯤ ꯅꯦꯁꯅꯦꯜ ꯐꯤꯜꯗ ꯍꯣꯀꯤ ꯇꯤꯝꯅꯥ ꯃꯦꯆ ꯑꯞꯇꯦꯠ ꯑꯃꯗ ꯁꯥꯎꯊ ꯀꯣꯔꯤꯌꯥ ꯃꯦꯟꯁꯀꯤ ꯅꯦꯁꯅꯦꯜ ꯐꯤꯜꯗ ꯍꯣꯛꯀꯤ ꯇꯤꯝ 4/1 ꯗꯥ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:   8%|██▎                         | 82/1000 [01:31<15:14,  1.00it/s]

[82/1000]
EN: The house of K. D. Singh Babu would be developed as a tourist attraction.
MT: ꯀꯦ. ꯗꯤ. ꯁꯤꯡꯍ ꯕꯥꯕꯨꯒꯤ ꯌꯨꯝ ꯑꯁꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯟꯅꯤꯡꯉꯥꯏ ꯑꯣꯏꯕ ꯃꯐꯝ ꯑꯃ ꯑꯣꯏꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:   8%|██▎                         | 83/1000 [01:31<13:40,  1.12it/s]

[83/1000]
EN: Lakshya Sen finished fourth in a tournament.
MT: ꯂꯛꯁꯌ ꯁꯦꯟꯅ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯃꯗ ꯃꯔꯤ ꯁꯨꯕꯥ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:   8%|██▎                         | 84/1000 [01:32<13:58,  1.09it/s]

[84/1000]
EN: Saina Nehwal confirmed her retirement from competitive badminton.
MT: ꯁꯥꯏꯅꯥ ꯅꯦꯍꯋꯥꯜꯅ ꯃꯍꯥꯛ ꯀꯝꯄꯤꯇꯦꯇꯤꯚ ꯕꯦꯗꯃꯤꯟꯇꯟꯗꯒꯤ ꯔꯤꯇꯔꯥꯏꯑꯃꯦꯟꯠ ꯂꯧꯔꯦ ꯍꯥꯏꯕ ꯈꯪ
--------------------------------------------------

Translating:   8%|██▍                         | 85/1000 [01:33<13:17,  1.15it/s]

[85/1000]
EN: R. Vaishali won the FIDE Women’s Grand Swiss.
MT: ꯑꯥꯔ ꯕꯩꯁꯥꯂꯤꯅꯥ ꯐꯤꯗꯦ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯒꯥꯔꯦꯟꯗꯋꯤꯁ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:   9%|██▍                         | 86/1000 [01:34<12:25,  1.23it/s]

[86/1000]
EN: R. Praggnanandhaa came from behind to win a game.
MT: ꯑꯥꯔ ꯄꯒꯅꯥꯅꯟꯗꯅꯥ ꯇꯨꯡꯗꯒꯤ ꯒꯦꯝ ꯑꯃ ꯃꯥꯏ ꯄꯥꯛꯄꯥ ꯂꯥꯛ
--------------------------------------------------

Translating:   9%|██▍                         | 87/1000 [01:35<12:58,  1.17it/s]

[87/1000]
EN: D. Gukesh as the youngest world chess champion in history.
MT: ꯗꯤ. ꯒꯨꯀꯦꯁ ꯑꯁꯤ ꯍꯤꯁꯇꯔꯤꯗꯥ ꯈ ꯭ ꯋꯥꯏꯗꯒꯤ ꯅꯧꯕ ꯋꯥꯔꯜꯗ ꯆꯦꯁ ꯆꯦꯝꯄꯌꯣꯟ ꯑꯣꯏ
--------------------------------------------------

Translating:   9%|██▍                         | 88/1000 [01:36<13:35,  1.12it/s]

[88/1000]
EN: D. Gukesh secured his first win at Tata Steel Chess Masters 2026.
MT: ꯗꯤ. ꯒꯨꯀꯦꯁꯅ ꯇꯥꯇꯥꯇꯤꯜ ꯆꯦꯁ ꯃꯥꯇꯔꯁ 2026 ꯗꯥ ꯃꯍꯥꯛꯀꯤ ꯑꯍꯥꯟꯕꯥ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯑꯗꯨ ꯐꯪ
--------------------------------------------------

Translating:   9%|██▍                         | 89/1000 [01:37<15:29,  1.02s/it]

[89/1000]
EN: Avinash Sable became the first Indian man to qualify for the men’s 3000m steeplechase final at Paris Olympics 2024.
MT: ꯑꯕꯤꯅꯥꯁ ꯁꯦꯕꯂꯦꯅ ꯄꯦꯔꯤꯁ ꯑꯣꯂꯤꯝꯄꯤꯛꯁ 2024 ꯗꯥ ꯅꯨꯄꯥꯁꯤꯡꯒꯤ ꯃꯤꯇꯔ 3000 ꯁꯇꯤꯄꯂꯆꯦꯁ ꯐꯥꯏꯅꯦꯜꯒꯤꯗꯃꯛꯋꯥꯂꯤꯐꯥꯏ ꯇꯧꯕ ꯑꯍꯥꯟꯕ ꯏꯟꯗꯤꯌꯟ ꯃꯦꯟ ꯑꯣꯏꯈꯤ ꯫
--------------------------------------------------

Translating:   9%|██▌                         | 90/1000 [01:38<15:46,  1.04s/it]

[90/1000]
EN: Mirabai Chanu returned to competition as she prepared for upcoming international events.
MT: ꯃꯤꯔꯥꯕꯥꯏ ꯆꯅꯨꯅꯥ ꯂꯥꯛꯀꯗꯧꯔꯤꯕ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯏꯚꯦꯟꯇꯁꯤꯡꯒꯤꯗꯃꯛ ꯁꯦꯝ ꯁꯥꯗꯨꯅ ꯂꯩꯕꯗꯒꯤ ꯀꯝꯄꯤꯇꯤꯁꯟꯗꯥ ꯍꯜꯂꯛꯈꯤ ꯫
--------------------------------------------------

Translating:   9%|██▌                         | 91/1000 [01:39<16:48,  1.11s/it]

[91/1000]
EN: Manu Bhaker and Harmanpreet Singh among athletes highlighted in a sports-honours post.
MT: ꯃꯅꯨ ꯚꯦꯛꯔ ꯑꯃꯁꯨꯡ ꯍꯔꯃꯟꯄꯤꯇ ꯁꯤꯡꯍ ꯑꯁꯤ ꯑꯦꯇꯦꯂꯤꯇꯁꯤꯡꯒꯤ ꯃꯔꯛꯇꯥꯄꯣꯔ ꯭ ꯠꯁ-ꯍꯣꯔꯣꯔ ꯄꯣꯇ ꯑꯃꯗ ꯃꯁꯛ ꯇꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:   9%|██▌                         | 92/1000 [01:41<17:42,  1.17s/it]

[92/1000]
EN: At the Milan–Cortina Winter Olympics 2026, Ilia Malinin landed a backflip on one skate in an Olympics moment.
MT: ꯃꯤꯂꯥꯟꯒꯤ ꯀꯣꯔꯇꯤꯅꯥ ꯋꯤꯟꯇꯔ ꯑꯣꯂꯤꯝꯄꯤꯛꯁ 2026 ꯗꯥ ꯏꯂꯤꯌꯥ ꯃꯥꯂꯤꯅꯤꯟꯅ ꯑꯣꯂꯤꯝꯄꯤꯛꯁꯀꯤ ꯃꯇꯝꯗꯥ ꯁꯀꯦꯇ ꯑꯃꯗ ꯕꯦꯛꯐꯂꯤꯄ ꯑꯃ ꯂꯦꯟꯗ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:   9%|██▌                         | 93/1000 [01:42<17:12,  1.14s/it]

[93/1000]
EN:  Anastasiia Gubanova delivered a performance featuring Indian cultural elements on the ice in Milan.
MT: ꯑꯅꯥꯁꯇꯥꯁꯤꯌꯥ ꯒꯨꯕꯥꯅꯣꯚꯥꯅꯥ ꯃꯤꯂꯥꯟꯗꯥ ꯂꯩꯕ ꯎꯟꯁꯥꯗꯥ ꯚꯥꯔꯠꯀꯤ ꯅꯥꯠꯀꯤ ꯑꯣꯏꯕ ꯃꯆꯥꯛꯁꯤꯡ ꯎꯠꯄꯥ ꯄꯔꯐꯣꯃꯦꯟꯁ ꯑꯃꯥ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:   9%|██▋                         | 94/1000 [01:43<17:10,  1.14s/it]

[94/1000]
EN: Formula One World Championship could return to Indian soil after a 13-year gap as policy issues are addressed.
MT: ꯐꯣꯔꯃꯨꯂꯥ ꯋꯥꯅ ꯋꯥꯔꯜꯗ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯄ ꯑꯁꯤ ꯆꯍꯤ 13ꯒꯤ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯗ ꯑꯃꯨꯛ ꯍꯜꯂꯛꯄ ꯌꯥꯏ ꯃꯔꯝꯗꯤ ꯄꯣꯂꯤꯁꯤꯒꯤ ꯋꯥꯐꯝꯁꯤꯡ ꯌꯦꯡꯁꯤꯟ
--------------------------------------------------

Translating:  10%|██▋                         | 95/1000 [01:44<17:33,  1.16s/it]

[95/1000]
EN: Nikhat Zareen won 5–0 over Guo Yi Xuan in a bout described as a commanding victory.
MT: ꯅꯤꯈꯥꯇ ꯖꯔꯤꯟꯅꯥ ꯒꯨꯑꯣ ꯌꯤ ꯁꯨꯌꯥꯅꯕꯨ ꯃꯥꯏꯊꯤꯕꯥ ꯃꯥꯏꯄꯥꯛꯄꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯄ ꯕꯥꯎꯇ ꯑꯃꯗ. ꯗ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  10%|██▋                         | 96/1000 [01:45<18:39,  1.24s/it]

[96/1000]
EN: Minakshi Hooda and Jaismine Lamboria upset Paris Olympics medallists and top seeds in a major boxing event.
MT: ꯃꯤꯅꯥꯛꯁꯤ ꯍꯨꯗꯥ ꯑꯃꯁꯨꯡ ꯖꯦꯏꯁꯃꯤꯟꯅ ꯂꯦꯝꯕꯣꯔꯤꯌꯥꯅꯥ ꯄꯦꯔꯤꯁ ꯑꯣꯂꯤꯝꯄꯤꯛꯁꯀꯤ ꯃꯦꯂꯥꯗ ꯃꯥꯏ ꯄꯥꯛꯄꯥꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯇꯣꯞ ꯁꯤꯗꯁꯤꯡꯕꯨ ꯑꯆꯧꯕ ꯕꯣꯛꯁꯤꯡ ꯏꯚꯦꯟꯇ ꯑꯃꯗ ꯃꯥꯏꯊꯤꯕ ꯄꯤ
--------------------------------------------------

Translating:  10%|██▋                         | 97/1000 [01:46<16:53,  1.12s/it]

[97/1000]
EN: Vinesh Phogat announced a return to wrestling on December 12, 2025.
MT: ꯚꯤꯅꯦꯁ ꯐꯣꯒꯥꯠꯅ ꯏꯪ 2025ꯒꯤ ꯗꯤꯁꯦꯝꯕꯔꯗꯥ ꯔꯦꯁꯠꯂꯤꯡꯗꯥ ꯑꯃꯨꯛ ꯍꯟꯅ ꯂꯥꯛꯀꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  10%|██▋                         | 98/1000 [01:47<15:38,  1.04s/it]

[98/1000]
EN: Village spectators watching a kabaddi match organised at a makeshift arena.
MT: ꯈꯨꯡꯒꯪꯒꯤ ꯑꯌꯦꯡꯕꯁꯤꯡꯅ ꯃꯇꯝ ꯈꯔꯒꯤ ꯑꯣꯏꯕ ꯑꯦꯔꯤꯅꯥ ꯑꯃꯗ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯀꯕꯥꯗꯤ ꯃꯦꯆ ꯑꯃ ꯌꯦꯡ
--------------------------------------------------

Translating:  10%|██▊                         | 99/1000 [01:48<14:31,  1.03it/s]

[99/1000]
EN: The 21st Tata Mumbai Marathon took place with large-scale participation in Mumbai.
MT: 21 ꯁꯨꯕꯥ ꯇꯥꯇꯥ ꯃꯨꯝꯕꯥꯏ ꯃꯥꯔꯥꯊꯣꯟ ꯑꯁꯤ ꯑꯆꯧꯕ ꯆꯥꯡꯗꯥ ꯁꯔꯨꯛ ꯌꯥꯗꯨꯅꯥ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  10%|██▋                        | 100/1000 [01:49<14:31,  1.03it/s]

[100/1000]
EN: The first-ever Formula 4 car show on Marina Beach was held on the banks of the sea in Chennai.
MT: ꯃꯦꯔꯤꯅꯥ ꯕꯤꯆꯇꯥ ꯑꯍꯥꯟꯕ ꯐꯣꯔꯃꯨꯂꯥ 4 ꯀꯥꯔ ꯁꯣ ꯑꯁꯤ ꯆꯦꯟꯅꯥꯏꯒꯤ ꯁꯃꯨꯗ ꯇꯣꯔꯕꯥꯟꯗ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  10%|██▋                        | 101/1000 [01:50<14:54,  1.00it/s]

[101/1000]
EN: Tilak Varma said India felt ready for the high-stakes Pakistan match in Colombo.
MT: ꯇꯤꯂꯛ ꯕꯔꯃꯥꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯀꯣꯂꯝꯕꯣꯗꯥ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯑꯋꯥꯡꯕ ꯊꯥꯛꯀꯤ ꯄꯥꯀꯤꯁꯇꯥꯟ ꯃꯦꯆ ꯑꯁꯤꯒꯤꯗꯃꯛ ꯚꯥꯔꯠꯅ ꯁꯦꯝ ꯁꯥꯅꯕ ꯐꯥꯎꯈꯤ ꯫
--------------------------------------------------

Translating:  10%|██▊                        | 102/1000 [01:51<15:21,  1.03s/it]

[102/1000]
EN: Tilak Varma said the India squad had entered a focused “match zone” mindset.
MT: ꯇꯤꯂꯛ ꯕꯔꯃꯥꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯏꯟꯗꯤꯌꯥꯋꯥꯗ ꯑꯁꯤ ꯐꯣꯀꯁ ꯇꯧꯕ ꯃꯦꯆ ꯖꯣꯟꯒꯤ ꯃꯥꯏꯟꯗꯦꯁꯇꯇꯥ ꯆꯪꯁꯤꯜꯂꯦ ꯫
--------------------------------------------------

Translating:  10%|██▊                        | 103/1000 [01:52<16:06,  1.08s/it]

[103/1000]
EN: Tilak Varma described the India–Pakistan fixture as a major highlight of the tournament.
MT: ꯇꯤꯂꯛ ꯕꯔꯃꯥꯅꯥ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯃꯔꯛꯇ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯃꯁꯥꯟꯅ ꯑꯁꯤ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯁꯤꯒꯤ ꯊꯣꯏꯗꯣꯛꯍꯦꯟꯗꯣꯛꯄ ꯑꯃꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  10%|██▊                        | 104/1000 [01:53<15:59,  1.07s/it]

[104/1000]
EN: Tilak Varma emphasized preparation and intensity for India ahead of the Pakistan clash.
MT: ꯇꯤꯂꯛ ꯕꯔꯃꯥꯅꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯗꯥ ꯊꯦꯡꯅꯕ ꯃꯃꯥꯡꯗ ꯚꯥꯔꯠꯀꯤꯗꯃꯛ ꯁꯦꯝ-ꯁꯥꯕꯥ ꯑꯃꯁꯨꯡ ꯍꯛꯆꯤꯟꯅꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  10%|██▊                        | 105/1000 [01:54<14:51,  1.00it/s]

[105/1000]
EN: Tilak Varma framed the Pakistan game as a test of temperament and execution.
MT: ꯇꯤꯂꯛ ꯕꯔꯃꯥꯅꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯃꯁꯥꯟꯅ ꯑꯁꯤ ꯃꯒꯨꯟ ꯑꯃꯁꯨꯡ ꯊꯕꯛ ꯄꯥꯡꯊꯣꯛꯄꯒꯤ ꯆꯥꯡꯌꯦꯡ ꯑꯃ ꯑꯣꯏꯅ ꯁꯦꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  11%|██▊                        | 106/1000 [01:55<15:15,  1.02s/it]

[106/1000]
EN: Delhi Metro extended operating hours to support fans travelling for the India–Namibia match.
MT: ꯏꯟꯗꯤꯌꯥ, ꯅꯥꯃꯤꯕꯤꯌꯥ ꯃꯦꯆꯀꯤꯗꯃꯛ ꯂꯝꯀꯣꯏꯕꯥ ꯐꯦꯟꯁꯤꯡꯕꯨ ꯃꯇꯦꯡ ꯄꯥꯡꯅꯕ ꯗꯤꯜꯂꯤ ꯃꯦꯇꯅꯥ ꯊꯕꯛ ꯄꯥꯡꯊꯣꯛꯄꯒꯤ ꯃꯇꯝ ꯍꯦꯟꯒꯠꯍꯟ
--------------------------------------------------

Translating:  11%|██▉                        | 107/1000 [01:56<15:14,  1.02s/it]

[107/1000]
EN: Delhi Metro added services to manage crowd flow before and after the India–Namibia game.
MT: ꯗꯤꯜꯂꯤ ꯃꯦꯇꯥ ꯏꯟꯗꯤꯌꯥ ꯅꯥꯃꯤꯕꯤꯌꯥ ꯒꯦꯝꯒꯤ ꯃꯃꯥꯡꯗ ꯑꯃꯁꯨꯡ ꯃꯇꯨꯡꯗ ꯃꯤ ꯌꯥꯝꯅ ꯆꯨꯡꯁꯤꯟꯕꯥ ꯁꯤꯟꯗꯣꯛꯅꯕ ꯁꯔꯕꯤꯁꯁꯤꯡ ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  11%|██▉                        | 108/1000 [01:58<16:24,  1.10s/it]

[108/1000]
EN: City transport officials coordinated services to reduce congestion around the India–Namibia fixture.
MT: ꯁꯤꯇꯤ ꯇ ꯭ ꯔꯥꯟꯁꯄꯣꯔꯇ ꯑꯣꯐꯤꯁꯌꯦꯜꯁꯤꯡꯅꯥ ꯏꯟꯗꯤꯌꯥ, ꯅꯥꯃꯤꯕꯤꯌꯥ ꯃꯐꯝ ꯑꯁꯤꯒꯤ ꯑꯀꯣꯏꯕꯗ ꯇꯤꯟꯅꯕꯒꯤ ꯆꯥꯡ ꯍꯟꯊꯍꯟꯅꯕ ꯁꯔꯕꯤꯁꯁꯤꯡ ꯀꯣꯑꯣꯔꯗꯤꯅꯦꯠ ꯇꯧ
--------------------------------------------------

Translating:  11%|██▉                        | 109/1000 [01:59<17:47,  1.20s/it]

[109/1000]
EN: Extended metro services aimed to make stadium travel easier for cricket spectators in Delhi.
MT: ꯗꯤꯜꯂꯤꯗꯥ ꯂꯩꯕ ꯀꯀꯦꯠ ꯌꯦꯡꯂꯤꯕꯁꯤꯡꯒꯤꯗꯃꯛꯇꯗꯃꯤꯌꯥꯃ ꯇꯚꯦꯜ ꯍꯦꯟꯅ ꯂꯥꯏꯕ ꯑꯣꯏꯍꯟꯅꯕ ꯄꯥꯟꯗꯝ ꯊꯝꯂꯤꯕꯥ ꯃꯦꯣ ꯁꯔꯕꯤꯁꯁꯤꯡ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  11%|██▉                        | 110/1000 [02:00<17:00,  1.15s/it]

[110/1000]
EN: Additional trains were planned to handle the match-day rush for the India–Namibia crowd.
MT: ꯚꯥꯔꯠꯀꯤ ꯅꯥꯃꯤꯕꯤꯌꯥꯒꯤ ꯃꯤꯐꯝꯒꯤ ꯃꯦꯆ - ꯗꯦꯒꯤ ꯃꯤ ꯌꯥꯝꯅ ꯆꯨꯡꯁꯤꯟꯕꯒꯤꯗꯃꯛꯇ ꯑꯍꯦꯟꯕꯦꯟꯁꯤꯡ ꯊꯧꯔꯥꯡ ꯇꯧ
--------------------------------------------------

Translating:  11%|██▉                        | 111/1000 [02:01<16:59,  1.15s/it]

[111/1000]
EN: Rohit Sharma warned India that confidence alone would not win against Pakistan.
MT: ꯔꯣꯍꯤꯇ ꯁꯔꯃꯥꯅꯥ ꯚꯥꯔꯠꯇꯥ ꯆꯦꯛꯁꯤꯟꯋꯥ ꯄꯤꯔꯝꯃꯤ ꯃꯗꯨꯗꯤ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯀꯟꯐꯦꯁꯇ ꯈꯛꯇꯅꯥ ꯃꯥꯏ ꯄꯥꯛꯄ ꯉꯝꯂꯣꯏ ꯫
--------------------------------------------------

Translating:  11%|███                        | 112/1000 [02:02<17:01,  1.15s/it]

[112/1000]
EN: Rohit Sharma urged India to approach Pakistan with discipline, planning, and composure.
MT: ꯔꯣꯍꯤꯇ ꯁꯔꯃꯥꯅꯥ ꯚꯥꯔꯠꯇꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯗꯥ ꯗꯤꯁꯤꯄꯂꯤꯟ, ꯄꯅꯤꯡ, ꯑꯃꯁꯨꯡ ꯀꯝꯄꯣꯖꯔꯒ ꯂꯣꯏꯅꯅꯥ ꯆꯪꯁꯤꯟꯕꯥ ꯍꯥꯏ
--------------------------------------------------

Translating:  11%|███                        | 113/1000 [02:03<17:20,  1.17s/it]

[113/1000]
EN: Rohit Sharma cautioned that India–Pakistan games can ignore rankings and recent form.
MT: ꯔꯣꯍꯤꯇ ꯁꯔꯃꯥꯅꯥ ꯚꯥꯔꯠꯇꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯗꯥ ꯁꯥꯟꯅꯔꯤꯕ ꯃꯁꯥꯟꯅꯁꯤꯡ ꯑꯁꯤꯅ ꯔꯦꯡꯀꯤꯡ ꯑꯃꯁꯨꯡ ꯑꯅꯧꯕ ꯃꯑꯣꯡ ꯑꯗꯨ ꯃꯥꯡꯍꯟꯕꯥ ꯌꯥꯏ ꯍꯥꯏꯅ ꯆꯦꯛꯁꯤꯟꯋꯥ ꯄꯤ
--------------------------------------------------

Translating:  11%|███                        | 114/1000 [02:05<16:40,  1.13s/it]

[114/1000]
EN: Rohit Sharma stressed mental readiness for India before the Pakistan contest.
MT: ꯔꯣꯍꯤꯇ ꯁꯔꯃꯥꯅꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯗꯒꯤ ꯍꯦꯟꯗꯥꯟꯅꯕꯒꯤ ꯃꯃꯥꯡꯗ ꯚꯥꯔꯠꯀꯤꯗꯃꯛ ꯋꯥꯈꯜꯒꯤ ꯑꯣꯏꯕ ꯁꯦꯝ-ꯁꯥꯕꯒꯤ ꯋꯥꯐꯝ ꯊꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███                        | 115/1000 [02:06<16:04,  1.09s/it]

[115/1000]
EN: Rohit Sharma advised India to avoid underestimating Pakistan in the World Cup clash.
MT: ꯔꯣꯍꯤꯇ ꯁꯔꯃꯥꯅꯥ ꯚꯥꯔꯠꯇꯥ ꯋꯥꯔꯜꯗ ꯀꯄ ꯀꯂꯦꯁꯇꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯕꯨ ꯇꯥꯟꯅꯕꯒꯤ ꯄꯥꯎꯇꯥꯛ ꯄꯤ
--------------------------------------------------

Translating:  12%|███▏                       | 116/1000 [02:07<15:51,  1.08s/it]

[116/1000]
EN: Virat Kohli congratulated India’s Under-19 team after the World Cup final victory.
MT: ꯋꯜꯗ ꯀꯞꯀꯤ ꯐꯥꯏꯅꯦꯜ ꯃꯥꯏ ꯄꯥꯛꯂꯕ ꯃꯇꯨꯡꯗ ꯕꯤꯔꯥꯇ ꯀꯣꯍꯂꯤꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯑꯟꯗꯔ-19 ꯇꯤꯝꯕꯨ ꯊꯥꯒꯠꯄ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███▏                       | 117/1000 [02:08<17:06,  1.16s/it]

[117/1000]
EN: India’s Under-19 team won the ICC Under-19 Cricket World Cup final by 100 runs against England.
MT: ꯚꯥꯔꯠꯀꯤ ꯑꯟꯗꯔ-19 ꯇꯤꯝꯅꯥ ꯑꯥꯏ ꯁꯤ ꯁꯤ ꯑꯟꯗ- ꯀꯀꯦꯠ ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞꯀꯤ ꯐꯥꯏꯅꯦꯜꯗꯥ ꯏꯪꯂꯦꯟꯗꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯔꯟ 100ꯅ ꯃꯥꯏꯄꯥꯛ
--------------------------------------------------

Translating:  12%|███▏                       | 118/1000 [02:09<16:58,  1.16s/it]

[118/1000]
EN: India secured a sixth Under-19 World Cup title with a commanding final performance.
MT: ꯀꯃꯥꯟꯗꯤꯡ ꯐꯥꯏꯅꯦꯜ ꯄꯔꯐꯣꯃꯔꯃꯦꯟꯁ ꯑꯃꯒ ꯂꯣꯏꯅꯅꯥ ꯚꯥꯔꯠꯅ 6 ꯁꯨꯕ ꯑꯟꯗꯔ-19 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞꯀꯤ ꯇꯥꯏꯇꯜ ꯑꯃ ꯐꯪ
--------------------------------------------------

Translating:  12%|███▏                       | 119/1000 [02:10<16:38,  1.13s/it]

[119/1000]
EN: Celebrations followed India’s Under-19 World Cup triumph over England in the title match.
MT: ꯇꯥꯏꯇꯜ ꯃꯦꯆ ꯑꯗꯨꯗ ꯚꯥꯔꯠꯅ ꯏꯡꯂꯦꯟꯗꯄꯨ ꯃꯥꯏꯊꯤꯅꯥ ꯑꯟꯗꯔ-19 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞꯇ ꯃꯥꯏ ꯄꯥꯛꯄꯥ ꯑꯗꯨ ꯄꯥꯡꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███▏                       | 120/1000 [02:11<15:46,  1.08s/it]

[120/1000]
EN: India’s Under-19 success drew praise from senior players across Indian cricket.
MT: ꯚꯥꯔꯠꯀꯤ ꯑꯟꯗꯔ-19ꯒꯤ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯑꯁꯤ ꯚꯥꯔꯠꯀꯤ ꯀꯀꯦꯠ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯂꯩꯕ ꯁꯦꯅꯤꯌꯔ ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡꯗꯒꯤ ꯊꯥꯒꯠꯄ ꯐꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███▎                       | 121/1000 [02:12<15:25,  1.05s/it]

[121/1000]
EN: Dhakshineswar Suresh sparked optimism by delivering a breakthrough stretch for Indian tennis.
MT: ꯙꯛꯁꯤꯅꯦꯁ ꯁꯨꯔꯦꯁꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯇꯦꯅꯤꯁꯀꯤꯗꯃꯛ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯈꯣꯡꯊꯥꯡ ꯑꯃ ꯄꯤꯔꯗꯨꯅ ꯑꯥꯀꯥꯁꯕꯥ ꯎꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███▎                       | 122/1000 [02:13<15:34,  1.06s/it]

[122/1000]
EN: Dhakshineswar Suresh’s rise has renewed ambition among Indian tennis fans and young players.
MT: ꯙꯛꯁꯤꯅꯦꯁ ꯁꯨꯔꯦꯁꯀꯤ ꯆꯥꯎꯈꯠꯂꯛꯄ ꯑꯁꯤꯅ ꯚꯥꯔꯠꯀꯤ ꯇꯦꯅꯤꯁ ꯄꯥꯝꯖꯕꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯅꯍꯥ ꯑꯣꯏꯔꯤꯕ ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯑꯅꯤꯡꯕꯥ ꯑꯃꯨꯛ ꯍꯟꯅ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███▎                       | 123/1000 [02:14<15:28,  1.06s/it]

[123/1000]
EN: Dhakshineswar Suresh’s recent results were described as a turning point for Indian tennis.
MT: ꯙꯛꯁꯤꯅꯦꯁ ꯁꯨꯔꯦꯁꯀꯤ ꯍꯟꯗꯛꯀꯤ ꯐꯜꯁꯤꯡ ꯑꯁꯤ ꯏꯟꯗꯤꯌꯟ ꯇꯦꯅꯤꯁꯀꯤ ꯃꯔꯨꯑꯣꯏꯕ ꯈꯣꯡꯊꯥꯡ ꯑꯃꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███▎                       | 124/1000 [02:15<15:23,  1.05s/it]

[124/1000]
EN: Dhakshineswar Suresh’s performances lifted expectations for Indian tennis on bigger stages.
MT: ꯙꯛꯁꯤꯅꯦꯁ ꯁꯨꯔꯦꯁꯀꯤ ꯄꯔꯐꯣꯃꯦꯟꯁꯁꯤꯡ ꯑꯁꯤꯅ ꯚꯥꯔꯠꯀꯤ ꯇꯦꯅꯤꯁꯇꯒꯤ ꯑꯆꯧꯕ ꯇꯥꯡꯀꯛꯁꯤꯡꯗ ꯊꯥꯖꯕ ꯍꯦꯟꯒꯠꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███▍                       | 125/1000 [02:16<15:06,  1.04s/it]

[125/1000]
EN: Dhakshineswar Suresh’s run created fresh belief about India’s potential in men’s tennis.
MT: ꯙꯛꯁꯤꯅꯦꯁ ꯁꯨꯔꯦꯁꯀꯤ ꯂꯝꯖꯦꯜ ꯑꯁꯤꯅ ꯅꯨꯄꯥꯒꯤ ꯇꯦꯅꯤꯁꯇ ꯚꯥꯔꯠꯀꯤ ꯑꯣꯏꯊꯣꯛꯄ ꯌꯥꯕꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯑꯅꯧꯕ ꯊꯥꯖꯕ ꯁꯦꯝꯒꯠ
--------------------------------------------------

Translating:  13%|███▍                       | 126/1000 [02:17<15:09,  1.04s/it]

[126/1000]
EN: India’s men’s team exited in the quarterfinals at the Badminton Asia Team Championships.
MT: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯑꯦꯁꯤꯌꯥ ꯇꯤꯝ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯄꯇ ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯥꯒꯤ ꯇꯤꯝ ꯑꯁꯤ ꯀ ꯭ ꯋꯥꯇꯔꯐꯥꯏꯂꯔꯇꯥ ꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  13%|███▍                       | 127/1000 [02:18<15:10,  1.04s/it]

[127/1000]
EN: India’s women’s team exited in the quarterfinals at the Badminton Asia Team Championships.
MT: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯑꯦꯁꯤꯌꯥ ꯇꯤꯝ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯄꯇ ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯇꯤꯝ ꯑꯁꯤ ꯀ ꯭ ꯋꯥꯇꯔꯐꯥꯏꯂꯔꯇꯥ ꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  13%|███▍                       | 128/1000 [02:20<15:41,  1.08s/it]

[128/1000]
EN: India failed to defend titles after a double quarterfinal exit in the team championships.
MT: ꯇꯤꯝ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯄ ꯑꯁꯤꯗ ꯗꯕꯜꯋꯥꯇꯔ ꯐꯥꯏꯅꯦꯜꯗꯒꯤ ꯅꯥꯟꯊꯣꯛꯂꯕ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯅ ꯇꯥꯏꯇꯥꯜꯁꯤꯡ ꯉꯥꯛꯊꯣꯛꯄꯗꯥ ꯃꯥꯏ ꯄꯥꯛꯈꯤꯗꯦ ꯫
--------------------------------------------------

Translating:  13%|███▍                       | 129/1000 [02:21<16:03,  1.11s/it]

[129/1000]
EN: Strong opposition ended India’s campaign early at the Badminton Asia Team Championships.
MT: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯑꯦꯁꯤꯌꯥ ꯇꯤꯝ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯞ ꯑꯁꯤꯗ ꯃꯥꯏ ꯄꯥꯛꯅꯥ ꯑꯣꯄꯖꯤꯁꯟ ꯇꯧꯔꯕꯥ ꯚꯥꯔꯠꯀꯤ ꯀꯦꯝꯄꯤꯌꯟ ꯑꯗꯨ ꯉꯟꯅ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  13%|███▌                       | 130/1000 [02:22<15:51,  1.09s/it]

[130/1000]
EN: The quarterfinal losses ended India’s hopes of a title defence at the event.
MT: ꯋꯥꯔꯇꯔ ꯐꯥꯏꯅꯦꯜꯗꯥ ꯃꯥꯏꯊꯤꯕꯥ ꯑꯁꯤꯅ ꯊꯧꯔꯝ ꯑꯁꯤꯗ ꯇꯥꯏꯇꯥꯜ ꯗꯤꯐꯦꯟꯁ ꯑꯃ ꯑꯣꯏꯅꯕ ꯚꯥꯔꯠꯀꯤ ꯊꯥꯖꯕ ꯑꯗꯨ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  13%|███▌                       | 131/1000 [02:23<15:44,  1.09s/it]

[131/1000]
EN: Sumit Nagal was scheduled to open his tournament campaign against Guy Den Ouden.
MT: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯅꯥ ꯒꯥꯏ ꯗꯦꯅ ꯑꯣꯎꯗꯦꯟꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯃꯍꯥꯛꯀꯤ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯀꯦꯝꯄꯦꯟ ꯍꯥꯡꯗꯣꯛꯅꯕꯒꯤ ꯊꯧꯔꯥꯡ ꯇꯧꯔꯝꯃꯤ ꯫
--------------------------------------------------

Translating:  13%|███▌                       | 132/1000 [02:24<16:11,  1.12s/it]

[132/1000]
EN: Sumit Nagal drew Dutch player Guy Den Ouden in an opening-round matchup.
MT: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯅꯥ ꯑꯣꯄꯦꯅꯤꯡ-ꯔꯥꯎꯟꯗ ꯃꯦꯆꯑꯄ ꯑꯃꯗ ꯗꯠꯆꯀꯤ ꯁꯥꯟꯅꯔꯣꯏ ꯒꯥꯏ ꯗꯦꯅ ꯑꯣꯎꯗꯦꯟꯕꯨ ꯗ ꯇꯧ
--------------------------------------------------

Translating:  13%|███▌                       | 133/1000 [02:25<16:36,  1.15s/it]

[133/1000]
EN: Sumit Nagal’s first-round pairing set up an early test against Guy Den Ouden.
MT: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯒꯤ ꯐꯔꯁꯠ-ꯔꯥꯎꯟꯗ ꯄꯦꯌꯔꯤꯡꯅꯥ ꯒꯥꯏ ꯗꯦꯅ ꯑꯣꯎꯗꯦꯟꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯉꯟꯅꯕꯥ ꯇꯦꯁꯇ ꯑꯃ ꯁꯦꯝ
--------------------------------------------------

Translating:  13%|███▌                       | 134/1000 [02:26<16:39,  1.15s/it]

[134/1000]
EN: Sumit Nagal prepared for a fresh challenge against Guy Den Ouden in round one.
MT: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯅꯥ ꯒꯥꯏ ꯗꯦꯅ ꯑꯣꯎꯗꯦꯟꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯔꯥꯎꯟꯗ ꯋꯥꯟꯗꯥ ꯑꯅꯧꯕ ꯆꯂꯦꯟꯖ ꯑꯃꯒꯤꯗꯃꯛ ꯁꯦꯝ ꯁꯥ
--------------------------------------------------

Translating:  14%|███▋                       | 135/1000 [02:28<16:26,  1.14s/it]

[135/1000]
EN: Sumit Nagal began a new event with an opening match against Guy Den Ouden.
MT: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯅꯥ ꯒꯥꯏ ꯗꯦꯅ ꯑꯣꯎꯗꯦꯟꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯑꯍꯥꯟꯕꯥ ꯃꯦꯆ ꯑꯃꯒ ꯂꯣꯏꯅꯅꯥ ꯑꯅꯧꯕ ꯏꯚꯦꯟꯇ ꯑꯃ ꯍꯧ
--------------------------------------------------

Translating:  14%|███▋                       | 136/1000 [02:29<16:43,  1.16s/it]

[136/1000]
EN: An analysis said T20 cricket keeps evolving through new strategies and fast-changing trends.
MT: ꯑꯦꯅꯥꯂꯥꯏꯁꯤꯁ ꯑꯃꯥꯅꯥ ꯍꯥꯏ ꯃꯗꯨꯗꯤ ꯇꯤ20 ꯀꯀꯦꯠ ꯑꯁꯤ ꯑꯅꯧꯕꯇꯖꯤꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯊꯨꯅ ꯍꯣꯡꯂꯛꯂꯤꯕꯦꯟꯗꯁꯤꯡꯒꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯆꯥꯎꯈꯠꯂꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  14%|███▋                       | 137/1000 [02:30<16:22,  1.14s/it]

[137/1000]
EN: A feature noted the ICC Men's T20 World Cup returned to India after a decade-long gap.
MT: ꯑꯥꯏ ꯁꯤ ꯁꯤ ꯃꯦꯟ ꯭ ꯁ ꯇꯤ20 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯄ ꯑꯁꯤ ꯆꯍꯤ ꯇꯔꯥꯒꯤ ꯈꯨꯖꯤꯡ ꯀꯌꯥꯒꯤ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯇ ꯍꯜꯂꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  14%|███▋                       | 138/1000 [02:31<15:59,  1.11s/it]

[138/1000]
EN: T20 cricket was described as a format that continually reinvents tactics and team plans.
MT: ꯇꯤ20 ꯀꯀꯦꯠ ꯑꯁꯤ ꯃꯈꯥ ꯇꯥꯅ ꯇꯦꯛꯇꯤꯛꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯇꯤꯝꯒꯤ ꯊꯧꯔꯥꯡꯁꯤꯡ ꯑꯃꯨꯛ ꯍꯟꯅ ꯁꯦꯝꯒꯠꯄꯥ ꯐꯣꯔꯃꯦꯇ ꯑꯃꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  14%|███▊                       | 139/1000 [02:32<16:19,  1.14s/it]

[139/1000]
EN: A commentary highlighted how technology and data shape modern T20 decision-making.
MT: ꯀꯃꯦꯟꯇꯔꯤ ꯑꯃꯅ ꯀꯔꯝꯅꯥ ꯇꯦꯛꯅꯣꯂꯣꯖꯤ ꯑꯃꯁꯨꯡ ꯗꯦꯇꯥꯅꯥ ꯃꯣꯗꯔꯟ ꯇꯤ20 ꯗꯤꯁꯤꯁꯟ - ꯃꯦꯀꯤꯡ ꯁꯦꯝꯒꯦ ꯍꯥꯏꯕꯗꯨ ꯍꯥꯏꯂꯥꯏꯇ ꯇꯧ
--------------------------------------------------

Translating:  14%|███▊                       | 140/1000 [02:33<16:04,  1.12s/it]

[140/1000]
EN: A tournament preview underlined T20 cricket’s cultural impact and mass appeal in India.
MT: ꯇꯣꯔꯅꯥꯃꯦꯟꯇꯚ ꯭ ꯌꯨ ꯑꯃꯅ ꯚꯥꯔꯠꯇ ꯇꯤ20 ꯀꯀꯦꯠꯀꯤ ꯅꯥꯠꯀꯤ ꯑꯣꯏꯕ ꯏꯊꯤꯜ ꯑꯃꯁꯨꯡ ꯃꯤꯌꯥꯝꯒꯤ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯟꯅꯤꯡꯉꯥꯏ ꯑꯣꯏꯕꯒꯤ ꯃꯁꯛ ꯇꯥꯛ
--------------------------------------------------

Translating:  14%|███▊                       | 141/1000 [02:34<16:11,  1.13s/it]

[141/1000]
EN: Kapil Dev was listed among participants at the PM Rungta Memorial Golf Cup in Jaipur.
MT: ꯀꯄꯤꯜ ꯗꯦꯕ ꯑꯁꯤ ꯖꯦꯄꯨꯔꯗꯥ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯄꯤꯑꯦꯝ ꯔꯨꯡꯒꯇꯥ ꯃꯦꯃꯣꯔꯤꯌꯦꯜ ꯒꯣꯜꯐ ꯀꯞꯇ ꯁꯔꯨꯛ ꯌꯥꯔꯤꯕꯁꯤꯡꯒꯤ ꯃꯅꯨꯡꯗ
--------------------------------------------------

Translating:  14%|███▊                       | 142/1000 [02:35<15:58,  1.12s/it]

[142/1000]
EN: Madan Lal was listed among participants at the PM Rungta Memorial Golf Cup in Jaipur.
MT: ꯃꯗꯟ ꯂꯥꯜ ꯑꯁꯤ ꯖꯦꯄꯨꯔꯗꯥ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯄꯤꯑꯦꯝ ꯔꯨꯡꯒꯇꯥ ꯃꯦꯃꯣꯔꯤꯌꯦꯜ ꯒꯣꯜꯐ ꯀꯞꯇ ꯁꯔꯨꯛ ꯌꯥꯔꯤꯕꯁꯤꯡꯒꯤ ꯃꯅꯨꯡꯗ
--------------------------------------------------

Translating:  14%|███▊                       | 143/1000 [02:36<15:31,  1.09s/it]

[143/1000]
EN: The PM Rungta Memorial Golf Cup was scheduled for February 8, 2026 in Jaipur.
MT: ꯄꯤ ꯑꯦꯝ ꯔꯨꯡꯇꯥ ꯃꯦꯃꯣꯔꯤꯌꯦꯜ ꯒꯣꯜꯐ ꯀꯞ ꯑꯁꯤ ꯖꯦꯄꯨꯔꯗꯥ ꯐꯕꯋꯥꯔꯤ 8,2026 ꯗꯥ ꯄꯥꯡꯊꯣꯛꯀꯗꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  14%|███▉                       | 144/1000 [02:37<14:32,  1.02s/it]

[144/1000]
EN: Rambagh Golf Club was named as the venue for the memorial golf tournament.
MT: ꯔꯥꯝꯕꯥꯒ ꯒꯣꯜꯐ ꯀꯂꯕ ꯑꯁꯤ ꯃꯦꯃꯣꯔꯤꯌꯦꯜ ꯒꯣꯜꯐꯥꯅꯃꯦꯟꯇ ꯑꯁꯤꯒꯤ ꯃꯐꯝ ꯍꯥꯏꯅ ꯃꯤꯡꯊꯣꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  14%|███▉                       | 145/1000 [02:39<16:08,  1.13s/it]

[145/1000]
EN: Organisers said the golf cup used a Stableford Single Peoria format for inclusive competition.
MT: ꯒꯣꯜꯐ ꯀꯄ ꯑꯁꯤꯗ ꯁꯇꯦꯕꯜꯐꯣꯔꯗ ꯁꯤꯡꯒꯜ ꯄꯤꯑꯣꯔꯤꯌꯥ ꯐꯣꯔꯃꯦꯇ ꯑꯁꯤ ꯏꯟꯀꯨꯚꯦꯜ ꯀꯝꯄꯤꯇꯤꯁꯟꯒꯤꯗꯃꯛ ꯁꯤꯖꯤꯟꯅꯈꯤ ꯍꯥꯏꯅ ꯑꯣꯔꯖꯦꯟꯥꯏꯖꯔꯁꯤꯡꯅ ꯍꯥꯏ
--------------------------------------------------

Translating:  15%|███▉                       | 146/1000 [02:40<16:23,  1.15s/it]

[146/1000]
EN: A schedule note said United States would face Netherlands in Chennai to close February 13’s action.
MT: ꯁꯦꯗꯜ ꯅꯣꯇ ꯑꯃꯗ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯌꯨꯅꯥꯏꯇꯦꯗꯁꯅ ꯆꯦꯟꯅꯥꯏꯗꯥ ꯅꯦꯗꯔꯂꯦꯟꯗꯁꯀ ꯃꯥꯌꯣꯛꯅꯔꯒ ꯐꯦꯕꯋꯥꯔꯤ 13ꯒꯤ ꯑꯦꯛꯁꯟ ꯂꯣꯏꯁꯤꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  15%|███▉                       | 147/1000 [02:41<15:41,  1.10s/it]

[147/1000]
EN: The USA–Netherlands match was presented as important for points and pride in the group.
MT: ꯌꯨ ꯑꯦꯁ ꯑꯦ ꯑꯃꯁꯨꯡ ꯅꯦꯗꯔꯂꯦꯟꯗꯁꯀꯤ ꯃꯦꯆ ꯑꯁꯤ ꯄꯣꯏꯟꯇꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯒꯄ ꯑꯁꯤꯗ ꯏꯀꯥꯏꯈꯨꯝꯅꯕꯒꯤ ꯃꯔꯨꯑꯣꯏꯕ ꯑꯃ ꯑꯣꯏꯅ ꯎꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  15%|███▉                       | 148/1000 [02:42<16:20,  1.15s/it]

[148/1000]
EN: A match preview framed USA against Netherlands as a tight contest between associate nations.
MT: ꯃꯦꯆꯚꯋꯥꯅꯥ ꯌꯨꯑꯦꯁꯑꯦꯕꯨ ꯅꯦꯗꯔꯂꯦꯟꯁꯀꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯑꯦꯁꯣꯁꯤꯑꯦꯠ ꯅꯦꯁꯟꯒꯤ ꯃꯔꯛꯀꯤ ꯑꯔꯨꯕꯥ ꯍꯦꯟꯗꯥꯟꯅꯕ ꯑꯃꯥ ꯑꯣꯏꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  15%|████                       | 149/1000 [02:43<16:36,  1.17s/it]

[149/1000]
EN: A schedule roundup highlighted February 13 fixtures as key for shaping group standings.
MT: ꯁꯦꯗꯜ ꯔꯥꯎꯟꯗꯑꯞ ꯑꯃꯥꯅꯥ ꯐꯦꯕꯋꯥꯔꯤ 13ꯒꯤ ꯐꯤꯛꯆꯔꯁꯤꯡ ꯑꯁꯤ ꯒꯄꯟꯗꯤꯡꯁꯤꯡ ꯁꯦꯝꯕꯒꯤ ꯃꯔꯨ ꯑꯣꯏ ꯍꯥꯏꯅ ꯃꯁꯛ ꯇꯥꯛ
--------------------------------------------------

Translating:  15%|████                       | 150/1000 [02:44<15:45,  1.11s/it]

[150/1000]
EN: A preview said the final February 13 match would be played at MA Chidambaram Stadium.
MT: ꯐꯕꯋꯥꯔꯤ ꯇꯥꯡ 13ꯒꯤ ꯐꯥꯏꯅꯦꯜ ꯃꯦꯆ ꯑꯗꯨ ꯑꯦꯝ ꯑꯦ ꯆꯤꯗꯝꯕꯔꯝꯗꯤꯌꯝꯗꯥ ꯁꯥꯟꯅꯒꯅꯤ ꯍꯥꯏꯅꯚ ꯭ ꯌꯨ ꯑꯃꯥꯅꯥ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  15%|████                       | 151/1000 [02:45<13:52,  1.02it/s]

[151/1000]
EN: Indian Super League clubs requested a pause on relegation for three to five years.
MT: ꯏꯟꯗꯤꯌꯟ ꯁꯨꯄꯔ ꯂꯤꯒ ꯀꯂꯒꯁꯤꯡꯅ ꯆꯍꯤ ꯑꯍꯨꯝꯗꯒꯤ ꯃꯉꯥ ꯐꯥꯎꯕꯒꯤ ꯑꯣꯏꯅ ꯔꯦꯂꯤꯒꯦꯁꯟ ꯂꯦꯞꯅꯕ ꯍꯥꯏꯖ
--------------------------------------------------

Translating:  15%|████                       | 152/1000 [02:46<13:12,  1.07it/s]

[152/1000]
EN: ISL clubs argued that pausing relegation would provide stability for long-term planning.
MT: ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯀꯂꯒꯁꯤꯡꯅ ꯋꯥꯐꯝ ꯊꯝꯈꯤ ꯃꯗꯨꯗꯤ ꯔꯦꯂꯤꯒꯦꯁꯟ ꯂꯦꯞꯄꯅꯥ ꯂꯣꯡ-ꯇꯔꯃꯅꯤꯡꯒꯤꯗꯃꯛ ꯁꯇꯦꯕꯤꯂꯤꯇꯤ ꯄꯤꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  15%|████▏                      | 153/1000 [02:47<12:31,  1.13it/s]

[153/1000]
EN: Several ISL teams asked administrators to consider a temporary relegation freeze.
MT: ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯇꯤꯝ ꯀꯌꯥꯅ ꯑꯦꯗꯃꯤꯅꯤꯁꯇꯥꯔꯁꯤꯡꯗ ꯃꯇꯝ ꯈꯔꯒꯤ ꯑꯣꯏꯅ ꯔꯦꯂꯤꯒꯦꯁꯟ ꯐꯖ ꯑꯃ ꯈꯟꯅꯅꯕ ꯍꯥꯏ
--------------------------------------------------

Translating:  15%|████▏                      | 154/1000 [02:47<12:04,  1.17it/s]

[154/1000]
EN: The request on relegation was framed as a measure to protect club investments.
MT: ꯔꯤꯂꯤꯒꯦꯁꯟ ꯇꯧꯅꯕ ꯍꯥꯏꯖꯕ ꯑꯁꯤ ꯀꯂꯕ ꯏꯟꯚꯦꯁꯇꯃꯦꯟꯇꯁꯤꯡ ꯉꯥꯛꯁꯦꯟꯕꯒꯤ ꯈꯣꯡꯊꯥꯡ ꯑꯃ ꯑꯣꯏꯅ ꯁꯦꯝꯈꯤꯕꯅꯤ ꯫
--------------------------------------------------

Translating:  16%|████▏                      | 155/1000 [02:48<12:40,  1.11it/s]

[155/1000]
EN: ISL stakeholders debated relegation rules while seeking clarity for the 2025–26 season.
MT: ꯏꯪꯁꯣꯛ 2025/26 ꯒꯤ ꯁꯤꯖꯟꯒꯤꯗꯃꯛ ꯃꯌꯦꯛ ꯁꯦꯡꯕꯥ ꯊꯤꯔꯤꯉꯩꯗ ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯁ ꯭ ꯇꯦꯀꯜꯁꯤꯡꯅ ꯔꯦꯂꯤꯒꯦꯁꯟ ꯔꯣꯂꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯋꯥꯊꯣꯛ ꯆꯠꯊꯈꯤ ꯫
--------------------------------------------------

Translating:  16%|████▏                      | 156/1000 [02:49<12:04,  1.17it/s]

[156/1000]
EN: India produced a 3–2 win over Netherlands in Davis Cup Qualifiers Round 1.
MT: ꯗꯦꯚꯤꯁ ꯀꯄꯋꯥꯂꯤꯐꯌꯔ ꯔꯥꯎꯟꯗ 1 ꯗꯥ ꯅꯦꯗꯔꯂꯦꯟꯁꯇ ꯚꯥꯔꯠꯅ 2. ꯗ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  16%|████▏                      | 157/1000 [02:50<12:18,  1.14it/s]

[157/1000]
EN: India advanced to the second Davis Cup qualifying round after beating Netherlands 3–2.
MT: ꯅꯦꯗꯔꯂꯦꯟ ꯭ ꯁꯄꯨ 3. ꯗ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯔꯕꯥ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯅ ꯑꯅꯤꯁꯨꯕ ꯗꯦꯚꯤꯁ ꯀꯞꯀꯤ ꯀꯋꯥꯂꯤꯐꯥꯏꯡ ꯔꯥꯎꯟꯗꯗꯥ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯈꯤ ꯫
--------------------------------------------------

Translating:  16%|████▎                      | 158/1000 [02:51<11:31,  1.22it/s]

[158/1000]
EN: India’s Davis Cup team was described as thriving against higher-ranked opponents recently.
MT: ꯍꯟꯗꯛꯇ ꯚꯥꯔꯠꯀꯤ ꯗꯦꯚꯤꯁ ꯀꯄ ꯇꯤꯝ ꯑꯁꯤ ꯑꯋꯥꯡꯕ ꯊꯥꯛꯇ ꯂꯩꯕ ꯌꯦꯛꯅꯕꯁꯤꯡꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯆꯥꯎꯈꯠꯂꯛꯂꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  16%|████▎                      | 159/1000 [02:51<10:58,  1.28it/s]

[159/1000]
EN: The Davis Cup tie at SM Krishna Tennis Stadium went down to the wire.
MT: ꯑꯦꯁ. ꯑꯦꯝ. ꯀꯅꯥ ꯇꯦꯅꯤꯁꯗꯤꯌꯝꯗꯥ ꯄꯥꯡꯊꯣꯛꯂꯤꯕꯥ ꯗꯦꯚꯤꯁ ꯀꯄ ꯇꯥꯏ ꯑꯗꯨ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  16%|████▎                      | 160/1000 [02:52<10:59,  1.27it/s]

[160/1000]
EN: India’s Davis Cup success followed an earlier victory over Switzerland in Biel last year.
MT: ꯚꯥꯔꯠꯀꯤ ꯗꯦꯚꯤꯁ ꯀꯞꯀꯤ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯑꯁꯤ ꯍꯧꯈꯤꯕ ꯆꯍꯤ ꯕꯤꯌꯦꯜꯗꯥꯏꯠꯖꯔꯂꯦꯟꯗꯄꯨ ꯃꯥꯏꯊꯤꯕꯥ ꯐꯪꯂꯕ ꯃꯇꯨꯡꯗꯅꯤ ꯫
--------------------------------------------------

Translating:  16%|████▎                      | 161/1000 [02:53<10:30,  1.33it/s]

[161/1000]
EN: The India Open was kept as a Super 750 tournament for the 2027–2030 cycle.
MT: ꯏꯟꯗꯤꯌꯥ ꯑꯣꯄꯟ ꯑꯁꯤ ꯏꯪ 20272030 ꯒꯤ ꯁꯥꯏꯀꯜꯒꯤꯗꯃꯛ ꯁꯨꯄꯔ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯃ ꯑꯣꯏꯅ ꯊꯝ
--------------------------------------------------

Translating:  16%|████▎                      | 162/1000 [02:54<10:37,  1.31it/s]

[162/1000]
EN: Players criticised conditions, yet organisers retained the India Open’s Super 750 status.
MT: ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡꯅ ꯀꯟꯗꯤꯁꯟꯁꯤꯡ ꯌꯦꯠꯂꯝꯃꯤ ꯑꯗꯨꯕꯨ ꯑꯣꯔꯒꯥꯅꯔꯁꯤꯡꯅ ꯏꯟꯗꯤꯌꯥ ꯑꯣꯄꯟꯒꯤ ꯁꯨꯄꯔ ꯁꯇꯥꯇꯁ ꯑꯗꯨ ꯂꯦꯞ
--------------------------------------------------

Translating:  16%|████▍                      | 163/1000 [02:55<11:13,  1.24it/s]

[163/1000]
EN: Badminton World Federation announced a revamped World Tour structure with six tournament levels.
MT: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯋꯥꯔꯜꯗ ꯐꯦꯗꯔꯦꯁꯟꯅ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯂꯦꯚꯦꯜ ꯇꯔꯨꯛꯀꯤ ꯃꯋꯣꯡ ꯁꯦꯝꯖꯤꯟꯕꯥ ꯋꯥꯔꯂꯗ ꯇꯨꯔ ꯁꯆꯔ ꯑꯃ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  16%|████▍                      | 164/1000 [02:55<11:01,  1.26it/s]

[164/1000]
EN: The BWF updated World Tour plan included 36 tournaments across multiple tiers.
MT: ꯕꯤ.ꯑꯐꯀꯤ ꯑꯞꯗꯦꯇ ꯇꯧꯔꯕꯥ ꯋꯥꯔꯜꯗ ꯇꯨꯔ ꯄꯂꯥꯟ ꯑꯁꯤꯗ ꯃꯈꯜ ꯀꯌꯥꯒꯤ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ 36 ꯌꯥꯎ
--------------------------------------------------

Translating:  16%|████▍                      | 165/1000 [02:56<11:32,  1.21it/s]

[165/1000]
EN: The BWF said annual World Tour prize money would rise to about 26.9 million dollars.
MT: ꯆꯍꯤꯗꯥ ꯋꯥꯔꯜꯗ ꯇꯨꯔꯥꯏꯖ ꯃꯅꯤ ꯑꯁꯤ ꯆꯥꯎꯔꯥꯛꯅ ꯗꯣꯂꯔ ꯃꯤꯂꯌꯟ. ꯐꯥꯎꯕ ꯍꯦꯟꯒꯠꯂꯛꯀꯅꯤ ꯍꯥꯏꯅ ꯕꯤ.ꯕꯤ.ꯑꯦꯐ.ꯅꯥ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  17%|████▍                      | 166/1000 [02:57<12:31,  1.11it/s]

[166/1000]
EN: A schedule preview listed Sri Lanka against Oman as a February 12 group-stage fixture.
MT: ꯁꯦꯗꯜꯚ ꯭ ꯌꯨꯗ ꯑꯃꯗ ꯁ ꯂꯡꯀꯥꯕꯨ ꯑꯣꯃꯥꯟꯒ ꯂꯥꯟꯊꯦꯡꯅꯕꯗ ꯐꯕꯋꯥꯔꯤ ꯒꯤ ꯒꯨꯞ-ꯦꯖ ꯐꯤꯆꯆꯔ ꯑꯣꯏꯅ ꯂꯤꯁꯠ ꯇꯧ
--------------------------------------------------

Translating:  17%|████▌                      | 167/1000 [02:58<12:45,  1.09it/s]

[167/1000]
EN: A schedule preview listed Nepal against Italy as a February 12 group-stage fixture.
MT: ꯁꯦꯗꯜꯚꯨꯅ ꯅꯦꯄꯥꯜꯕꯨ ꯏꯇꯂꯤꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯐꯦꯕꯋꯥꯔꯤ ꯒꯤ ꯒꯨꯞ-ꯦꯖ ꯐꯤꯆꯆꯔ ꯑꯣꯏꯅ ꯂꯤꯁꯠ ꯇꯧ
--------------------------------------------------

Translating:  17%|████▌                      | 168/1000 [02:59<12:44,  1.09it/s]

[168/1000]
EN: A schedule preview listed India against Namibia as a February 12 group-stage fixture.
MT: ꯁꯦꯗꯨꯜꯚꯋꯥ ꯑꯃꯗ ꯅꯦꯃꯤꯕꯥꯒ ꯂꯥꯟꯊꯦꯡꯅꯕꯗ ꯚꯥꯔꯠꯇꯥ ꯐꯕꯋꯥꯔꯤ ꯒꯤ ꯒꯨꯞ-ꯦꯖ ꯐꯤꯆꯆꯔ ꯑꯃ
--------------------------------------------------

Translating:  17%|████▌                      | 169/1000 [03:00<12:15,  1.13it/s]

[169/1000]
EN: Wanindu Hasaranga was ruled out of the World Cup due to an injury setback.
MT: ꯋꯥꯅꯤꯟꯗꯨ ꯍꯥꯁꯔꯥꯡꯒꯥ ꯑꯁꯤ ꯏꯟꯖꯨꯔꯤꯇꯤ ꯕꯦꯛꯕꯀꯒꯤ ꯃꯔꯝꯅꯥ ꯋꯥꯔꯂꯗ ꯀꯞꯇꯒꯤ ꯅꯥꯟꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  17%|████▌                      | 170/1000 [03:01<12:00,  1.15it/s]

[170/1000]
EN: Sri Lanka named Dushan Hemantha as a replacement after Wanindu Hasaranga’s injury.
MT: ꯋꯥꯅꯤꯟꯗꯨ ꯍꯥꯁꯔꯥꯡꯒꯥꯅ ꯁꯣꯛꯍꯜꯂꯕ ꯃꯇꯨꯡꯗ ꯁ ꯂꯡꯀꯅꯥ ꯗꯨꯁꯟ ꯍꯦꯃꯟꯊꯥꯕꯨ ꯑꯇꯣꯞꯄ ꯑꯃ ꯑꯣꯏꯅ ꯈꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  17%|████▌                      | 171/1000 [03:02<11:10,  1.24it/s]

[171/1000]
EN: The Indian Super League season was announced to begin on February 14, 2026.
MT: ꯏꯟꯗꯤꯌꯟ ꯁꯨꯄꯔ ꯂꯤꯒ ꯁꯤꯖꯟ ꯑꯁꯤ ꯏꯪꯁꯣꯛ ꯒꯤ ꯐꯦꯕꯋꯥꯔꯤꯗꯒꯤ ꯍꯧꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  17%|████▋                      | 172/1000 [03:02<11:11,  1.23it/s]

[172/1000]
EN: Sports minister Mansukh Mandaviya announced an ISL start date of February 14.
MT: ꯄꯣꯔꯇꯁꯀꯤ ꯃꯟꯇ ꯃꯟꯁꯨꯈ ꯃꯟꯗꯚꯤꯌꯥꯅꯥ ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯑꯁꯤ ꯐꯦꯕꯋꯥꯔꯤꯗꯒꯤ ꯍꯧꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  17%|████▋                      | 173/1000 [03:03<10:41,  1.29it/s]

[173/1000]
EN: All 14 clubs agreed to participate in the Indian Super League season, according to reports.
MT: ꯔꯤꯄꯣꯔꯠꯁꯤꯡꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯀꯂꯕ ꯄꯨꯝꯅꯃꯛ ꯏꯟꯗꯤꯌꯟ ꯁꯨꯄꯔ ꯂꯤꯒ ꯁꯤꯖꯟꯗꯥ ꯁꯔꯨꯛ ꯌꯥꯅꯕ ꯌꯥꯈꯤ ꯫
--------------------------------------------------

Translating:  17%|████▋                      | 174/1000 [03:04<11:19,  1.22it/s]

[174/1000]
EN: The ISL decision followed meetings between the sports ministry and the All India Football Federation.
MT: ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯒꯤ ꯋꯥꯔꯦꯞ ꯑꯁꯤꯄꯣꯔꯇ ꯭ ꯁ ꯃꯟꯇ ꯑꯃꯁꯨꯡ ꯑꯣꯜ ꯏꯟꯗꯤꯌꯥ ꯐꯨꯇꯕꯣꯜ ꯐꯦꯗꯔꯦꯁꯟꯒꯤ ꯃꯔꯛꯇ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯃꯤꯐꯝꯁꯤꯡꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯂꯧꯈꯤꯕꯅꯤ ꯫
--------------------------------------------------

Translating:  18%|████▋                      | 175/1000 [03:05<11:15,  1.22it/s]

[175/1000]
EN: Indian football’s top-tier season moved forward after clubs accepted the participation plan.
MT: ꯚꯥꯔꯠꯀꯤ ꯐꯨꯇꯕꯣꯜꯒꯤ ꯇꯣꯞ-ꯇꯤꯌꯔ ꯁꯤꯖꯟ ꯑꯁꯤ ꯀꯕꯁꯤꯡꯅꯥ ꯁꯔꯨꯛ ꯌꯥꯕꯒꯤ ꯊꯧꯔꯥꯡ ꯑꯗꯨ ꯑꯌꯥꯕ ꯄꯤꯔꯕꯥ ꯃꯇꯨꯡꯗ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯈꯤ ꯫
--------------------------------------------------

Translating:  18%|████▊                      | 176/1000 [03:06<11:49,  1.16it/s]

[176/1000]
EN: India’s women lost 0–3 to China in the Badminton Asia Team Championships quarterfinals.
MT: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯑꯦꯁꯤꯌꯥ ꯇꯤꯝ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯞꯁꯤꯡꯒꯤ ꯀ ꯭ ꯋꯥꯇꯔꯐꯥꯏꯂꯔꯇꯥ ꯆꯥꯏꯅꯥꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯅ 0/3 ꯇꯥ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  18%|████▊                      | 177/1000 [03:07<12:12,  1.12it/s]

[177/1000]
EN: P. V. Sindhu missed the team quarterfinal because of a minor injury, according to reports.
MT: ꯄꯤ. ꯚꯤ. ꯁꯤꯟꯙꯨꯅ ꯇꯤꯝꯒꯤ ꯀꯋꯥꯔꯇꯔ ꯐꯥꯏꯅꯥꯜ ꯑꯗꯨ ꯑꯄꯤꯛꯄ ꯑꯅꯥꯕꯥ ꯑꯃꯥꯅ ꯃꯔꯝ ꯑꯣꯏꯔꯒ ꯃꯥꯏꯊꯤꯈꯤ ꯍꯥꯏꯅ ꯔꯤꯄꯣꯔꯇꯁꯤꯡꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯍꯥꯏꯔꯤ ꯫
--------------------------------------------------

Translating:  18%|████▊                      | 178/1000 [03:07<11:39,  1.18it/s]

[178/1000]
EN: India’s women struggled to defend the 2024 title without PV Sindhu in the lineup.
MT: ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯅ ꯏꯪ 2024 ꯒꯤ ꯇꯥꯏꯇꯥꯜ ꯑꯗꯨ ꯄꯤ.ꯚꯤ. ꯁꯤꯟꯙꯨ ꯌꯥꯎꯗꯅ ꯂꯥꯏꯟꯑꯞꯇ ꯉꯥꯛꯊꯣꯛꯅꯕ ꯀꯟꯅ ꯍꯣꯠꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  18%|████▊                      | 179/1000 [03:08<11:44,  1.17it/s]

[179/1000]
EN: China ended India’s women’s title defence with a straight 3–0 quarterfinal win.
MT: ꯆꯥꯏꯅꯥꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯇꯥꯏꯇꯥꯜ ꯗꯤꯐꯦꯟꯁ ꯑꯗꯨ ꯀ ꯭ ꯋꯥꯇꯔꯐꯥꯏꯅꯦꯜꯗꯥ ꯍꯛꯊꯦꯡꯅꯅ 3:0 ꯃꯥꯏ ꯄꯥꯛꯄꯥꯒ ꯂꯣꯏꯅꯅꯥ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  18%|████▊                      | 180/1000 [03:09<11:52,  1.15it/s]

[180/1000]
EN: The quarterfinal defeat closed India’s women’s campaign at the Badminton Asia Team Championships.
MT: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯑꯦꯁꯤꯌꯥ ꯇꯤꯝ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯄꯇꯋꯥꯇꯔ ꯐꯥꯏꯅꯦꯜꯗꯥ ꯃꯥꯏꯊꯤꯕꯥ ꯑꯁꯤꯅ ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯀꯦꯝꯄꯤꯌꯟ ꯑꯗꯨ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  18%|████▉                      | 181/1000 [03:10<12:16,  1.11it/s]

[181/1000]
EN: Devika Sihag won the Thailand Masters 2026 to claim a BWF Super 300 title.
MT: ꯗꯦꯕꯤꯀꯥ ꯁꯤꯍꯥꯒꯅꯥ ꯊꯥꯏꯂꯦꯟꯗ ꯃꯥꯇꯔꯁ 2026ꯇ ꯃꯥꯏ ꯄꯥꯛꯂꯗꯨꯅ ꯕꯤ. ꯗꯕꯜꯌꯨ. ꯑꯦꯐ. ꯁꯨꯄꯔ ꯇꯥꯏꯇꯥꯜ ꯑꯃꯥ ꯂꯧ
--------------------------------------------------

Translating:  18%|████▉                      | 182/1000 [03:11<12:24,  1.10it/s]

[182/1000]
EN: Devika Sihag became the youngest Indian woman to win a BWF Super 300 singles title.
MT: ꯗꯦꯕꯤꯀꯥ ꯁꯤꯍꯥꯒꯅꯥ ꯕꯤ. ꯗꯕꯜꯌꯨ.ꯐ. ꯁꯨꯄꯔ 300 ꯁꯤꯡꯒꯜꯁ ꯇꯥꯏꯇꯥꯜ ꯐꯪꯕꯥ ꯈ ꯭ ꯋꯥꯏꯗꯒꯤ ꯅꯧꯕ ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤ ꯑꯣꯏ
--------------------------------------------------

Translating:  18%|████▉                      | 183/1000 [03:12<12:43,  1.07it/s]

[183/1000]
EN: Devika Sihag joined Saina Nehwal and PV Sindhu in an exclusive Indian milestone list.
MT: ꯗꯦꯕꯤꯀꯥ ꯁꯤꯍꯥꯒꯅꯥ ꯁꯥꯏꯅꯥ ꯅꯦꯍꯋꯥꯜ ꯑꯃꯁꯨꯡ ꯄꯤ.ꯚꯤ. ꯁꯤꯟꯙꯨꯒꯥ ꯑꯦꯛꯁꯁꯤꯋꯦꯜ ꯏꯟꯗꯤꯌꯟ ꯃꯥꯏꯜꯆꯣꯟ ꯂꯤꯁꯇꯗꯥ ꯌꯥꯎ
--------------------------------------------------

Translating:  18%|████▉                      | 184/1000 [03:13<11:57,  1.14it/s]

[184/1000]
EN: Devika Sihag’s Bangkok celebration marked a breakthrough moment for Indian women’s singles.
MT: ꯗꯦꯕꯤꯀꯥ ꯁꯤꯍꯥꯒꯅꯥ ꯕꯦꯡꯀꯣꯛꯇ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯊꯧꯔꯝ ꯑꯁꯤ ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯁꯤꯡꯒꯜꯁꯗꯥ ꯃꯔꯨ ꯑꯣꯏ
--------------------------------------------------

Translating:  18%|████▉                      | 185/1000 [03:14<11:59,  1.13it/s]

[185/1000]
EN: Devika Sihag’s title was described as a quiet announcement of a new Indian badminton star.
MT: ꯗꯦꯕꯤꯀꯥ ꯁꯤꯍꯥꯒꯀꯤ ꯇꯥꯏꯇꯥꯂ ꯑꯁꯤ ꯚꯥꯔꯠꯀꯤ ꯑꯅꯧꯕ ꯕꯦꯗꯃꯤꯟꯇꯟ ꯁꯔ ꯑꯃ ꯑꯣꯏꯔꯛꯄꯒꯤ ꯁꯣꯏꯅꯥ ꯂꯥꯎꯊꯣꯛꯄꯥ ꯑꯃꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  19%|█████                      | 186/1000 [03:15<11:53,  1.14it/s]

[186/1000]
EN: A matchday note listed Afghanistan against South Africa in Ahmedabad on February 11.
MT: ꯃꯦꯆ ꯗꯦ ꯅꯣꯇ ꯑꯃꯗ ꯑꯐꯒꯥꯅꯤꯁꯇꯥꯟꯕꯨ ꯐꯕꯋꯥꯔꯤ 11 ꯗꯥ ꯑꯍꯃꯗꯕꯥꯗꯇꯥ ꯁꯥꯎꯊ ꯑꯐꯀꯥꯒ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  19%|█████                      | 187/1000 [03:16<12:33,  1.08it/s]

[187/1000]
EN: A matchday note listed Australia against Ireland as another February 11 group-stage fixture.
MT: ꯃꯦꯆ ꯗꯦ ꯅꯣꯇ ꯑꯃꯥꯅꯥ ꯑꯣꯁꯇꯂꯤꯌꯥꯕꯨ ꯑꯥꯏꯔꯂꯦꯟꯗꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯐꯕꯕꯋꯥꯔꯤ 11 ꯒꯤ ꯒꯄ-ꯦꯖ ꯐꯤꯛꯆꯔ ꯑꯣꯏꯅ ꯂꯤꯁꯠ ꯇꯧ
--------------------------------------------------

Translating:  19%|█████                      | 188/1000 [03:16<12:14,  1.11it/s]

[188/1000]
EN: A matchday note listed England against West Indies as a February 11 evening fixture.
MT: ꯃꯦꯆ ꯗꯦ ꯅꯣꯇ ꯑꯃꯗ ꯏꯪꯂꯦꯟꯗꯄꯨ ꯋꯇ ꯏꯟꯗꯤꯖꯒ ꯂꯥꯟꯊꯦꯡꯅꯕꯗ ꯐꯕꯋꯥꯔꯤꯒꯤ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯐꯤꯛꯆꯔꯅꯤ ꯍꯥꯏꯅ ꯄꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  19%|█████                      | 189/1000 [03:17<12:05,  1.12it/s]

[189/1000]
EN: Afghanistan sought a rebound after losing their opener against New Zealand, according to reports.
MT: ꯔꯤꯄꯣꯔꯠꯁꯤꯡꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯑꯐꯒꯥꯅꯤꯁꯇꯥꯟꯅꯥ ꯃꯈꯣꯏꯒꯤ ꯑꯣꯄꯦꯅꯔ ꯑꯗꯨꯖꯤꯂꯦꯟꯗꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯃꯥꯏꯊꯤꯔꯕ ꯃꯇꯨꯡꯗ ꯔꯤꯕꯥꯎꯟꯗ ꯇꯧꯅꯕ ꯍꯣꯠꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  19%|█████▏                     | 190/1000 [03:18<12:35,  1.07it/s]

[190/1000]
EN: The February 11 schedule mixed former champions, contenders, and dangerous underdogs in group play.
MT: ꯐꯦꯕꯋꯥꯔꯤ 11ꯒꯤ ꯁꯦꯗꯜꯗꯥ ꯍꯥꯟꯅꯒꯤ ꯆꯦꯝꯄꯌꯟꯁꯤꯡ, ꯀꯟꯇꯦꯟꯗꯦꯟꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯑꯔꯨꯕꯥ ꯑꯟꯗꯔꯗꯣꯒꯁꯤꯡꯕꯨ ꯒꯞꯂꯦꯗꯥ ꯌꯥꯟꯁꯤꯟꯅ
--------------------------------------------------

Translating:  19%|█████▏                     | 191/1000 [03:19<13:02,  1.03it/s]

[191/1000]
EN: Baichung Bhutia blamed administration after Churchill Brothers were not added to ISL 2025–26.
MT: ꯆꯔꯆꯤꯜ ꯕꯗꯔꯁꯁꯤꯡ ꯑꯁꯤ ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ 2025/26 ꯗꯥ ꯌꯥꯎꯍꯟꯗꯕꯥ ꯃꯇꯨꯡꯗ ꯕꯥꯏꯆꯨꯡ ꯚꯨꯇꯤꯌꯥꯅꯥ ꯑꯦꯗꯃꯤꯅꯤꯁꯇꯦꯁꯟꯒꯤ ꯃꯔꯥꯜ ꯁꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  19%|█████▏                     | 192/1000 [03:20<12:56,  1.04it/s]

[192/1000]
EN: Churchill Brothers were not included in ISL 2025–26, prompting criticism from Baichung Bhutia.
MT: ꯆꯔꯆꯤꯜ ꯕꯗꯔꯁꯁꯤꯡ ꯑꯁꯤ ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ 2025/26 ꯗꯥ ꯌꯥꯎꯈꯤꯗꯦ, ꯃꯁꯤꯅ ꯕꯥꯏꯆꯨꯡ ꯚꯨꯇꯤꯌꯥꯗꯒꯤ ꯀꯇꯥꯏꯖꯦꯁꯟ ꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  19%|█████▏                     | 193/1000 [03:21<12:38,  1.06it/s]

[193/1000]
EN: Baichung Bhutia called the Churchill Brothers exclusion a clear administrative failure.
MT: ꯕꯥꯏꯆꯨꯡ ꯚꯨꯇꯤꯌꯥꯅꯥ ꯆꯔꯆꯤꯜ ꯕꯗꯔꯁꯁꯤꯡ ꯂꯧꯊꯣꯛꯄꯥ ꯑꯁꯤ ꯃꯌꯦꯛ ꯁꯦꯡꯕꯥ ꯂꯩꯉꯥꯛꯀꯤ ꯃꯥꯏꯊꯤꯕꯥ ꯑꯃꯅꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  19%|█████▏                     | 194/1000 [03:22<11:28,  1.17it/s]

[194/1000]
EN: The Churchill Brothers decision raised questions about the league’s selection and governance.
MT: ꯆꯔꯆꯤꯜ ꯕꯗꯔꯁꯀꯤ ꯋꯥꯔꯦꯞ ꯑꯁꯤꯅ ꯂꯤꯒ ꯑꯁꯤꯒꯤ ꯈꯟꯕꯒꯤ ꯑꯃꯁꯨꯡ ꯂꯩꯉꯥꯛꯄꯒꯤ ꯃꯇꯥꯡꯗ ꯆꯤꯡꯅꯕꯁꯤꯡ ꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  20%|█████▎                     | 195/1000 [03:23<10:59,  1.22it/s]

[195/1000]
EN: The ISL debate intensified after the Churchill Brothers issue surfaced in public comments.
MT: ꯆꯔꯆꯤꯜ ꯕꯗꯔꯁꯀꯤ ꯋꯥꯐꯝ ꯑꯁꯤ ꯃꯤꯌꯥꯝꯗꯥ ꯐꯣꯡꯗꯣꯛꯄꯗꯒꯤ ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯒꯤ ꯌꯦꯠꯅꯕ ꯑꯗꯨ ꯍꯦꯟꯅ ꯍꯦꯟꯒꯠꯂꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  20%|█████▎                     | 196/1000 [03:23<10:48,  1.24it/s]

[196/1000]
EN: India–Netherlands Davis Cup tie tightened after Sumit Nagal suffered a setback.
MT: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯥꯂꯅꯥ ꯃꯥꯏꯊꯤꯕꯥ ꯑꯃ ꯐꯪꯂꯕ ꯃꯇꯨꯡꯗ ꯏꯟꯗꯤꯌꯥ, ꯅꯦꯗꯔꯂꯦꯟꯗꯁ ꯗꯦꯚꯤꯁ ꯀꯄ ꯇꯥꯏ ꯑꯗꯨ ꯀꯟꯅ
--------------------------------------------------

Translating:  20%|█████▎                     | 197/1000 [03:24<10:52,  1.23it/s]

[197/1000]
EN: Sumit Nagal’s result added pressure as the Davis Cup tie moved toward a tense finish.
MT: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯒꯤ ꯐꯜꯅꯥ ꯗꯦꯚꯤꯁ ꯀꯄ ꯇꯥꯏ ꯑꯁꯤ ꯇꯦꯟꯁ ꯐꯤꯅꯤꯁꯀꯤ ꯃꯥꯏꯀꯩꯗ ꯆꯪꯁꯤꯜꯂꯛꯄꯗꯒꯤ ꯄꯁꯔ ꯍꯦꯟꯒꯠꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  20%|█████▎                     | 198/1000 [03:25<10:28,  1.28it/s]

[198/1000]
EN: India and Netherlands remained locked in a close Davis Cup contest after the Nagal match.
MT: ꯅꯥꯒꯥꯂ ꯃꯦꯆꯀꯤ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡ ꯅꯦꯗꯔꯂꯦꯟꯗꯁꯅ ꯗꯦꯚꯤꯁ ꯀꯄ ꯀꯟꯇꯦꯁꯇ ꯑꯗꯨ ꯂꯣꯏꯁꯤꯟ
--------------------------------------------------

Translating:  20%|█████▎                     | 199/1000 [03:26<10:43,  1.25it/s]

[199/1000]
EN: The Davis Cup tie needed late composure after the Sumit Nagal setback, according to reports.
MT: ꯄꯥꯎꯗꯝꯁꯤꯡꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯁꯨꯃꯤꯇ ꯅꯥꯒꯥꯂꯅꯥ ꯃꯥꯏꯊꯤꯔꯕ ꯃꯇꯨꯡꯗ ꯗꯦꯚꯤꯁ ꯀꯄ ꯇꯥꯏꯗꯥ ꯃꯇꯝ ꯀꯨꯏꯅ ꯆꯡꯖꯕꯥ ꯃꯊꯧ ꯇꯥꯈꯤ ꯫
--------------------------------------------------

Translating:  20%|█████▍                     | 200/1000 [03:27<11:05,  1.20it/s]

[200/1000]
EN: The Bengaluru Davis Cup atmosphere stayed intense as India fought Netherlands in a tight tie.
MT: ꯕꯦꯡꯂꯨꯨꯔꯨ ꯗꯦꯚꯤꯁ ꯀꯞꯀꯤ ꯑꯦꯠꯃꯣꯁꯐꯤꯌꯔ ꯑꯗꯨ ꯚꯥꯔꯠꯅ ꯅꯦꯗꯔꯂꯦꯟꯗꯁꯀ ꯆꯞ ꯆꯥꯕ ꯇꯥꯏꯗꯥ ꯂꯥꯟꯊꯦꯡꯅꯈꯤꯕꯅꯥ ꯀꯟꯅ ꯂꯦꯞ
--------------------------------------------------

Translating:  20%|█████▍                     | 201/1000 [03:28<11:45,  1.13it/s]

[201/1000]
EN: International Cricket Council confirmed the 2026 Men’s T20 World Cup starts on February 7.
MT: ꯏꯪꯁꯣꯛ 2026 ꯒꯤ ꯅꯨꯄꯥꯁꯤꯡꯒꯤ ꯇꯤ20 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞ ꯑꯁꯤ ꯐꯦꯕꯋꯥꯔꯤꯗꯥ ꯍꯧꯒꯅꯤ ꯍꯥꯏꯅ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯀꯥꯎꯟꯁꯤꯜꯅ ꯀꯟꯐꯔꯃꯦꯠ ꯇꯧ
--------------------------------------------------

Translating:  20%|█████▍                     | 202/1000 [03:28<11:10,  1.19it/s]

[202/1000]
EN: India were placed in Group A alongside Pakistan, Netherlands, USA, and Namibia.
MT: ꯚꯥꯔꯠꯄꯨ ꯄꯥꯀꯤꯁꯇꯥꯟ, ꯅꯦꯗꯔꯂꯦꯟꯁ, ꯌꯨ ꯑꯦꯁ ꯑꯦ ꯑꯃꯁꯨꯡ ꯅꯥꯃꯤꯕꯤꯌꯥꯒꯥ ꯂꯣꯏꯅꯅꯥ ꯒꯨꯞ ꯑꯦꯗꯥ ꯊꯝ
--------------------------------------------------

Translating:  20%|█████▍                     | 203/1000 [03:29<11:01,  1.20it/s]

[203/1000]
EN: Sri Lanka hosted several matches as the tournament ran across India and Sri Lanka venues.
MT: ꯂꯡꯀꯥꯅꯥ ꯃꯦꯆ ꯀꯌꯥ ꯑꯃ ꯄꯥꯡꯊꯣꯛꯈꯤ ꯃꯔꯝꯗꯤ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯁꯤ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡꯜꯂꯡꯀꯥꯒꯤ ꯃꯐꯝ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯆꯠꯊꯈꯤ ꯫
--------------------------------------------------

Translating:  20%|█████▌                     | 204/1000 [03:30<10:28,  1.27it/s]

[204/1000]
EN: India played the opening match against the USA at Wankhede Stadium in Mumbai.
MT: ꯚꯥꯔꯠꯅ ꯑꯍꯥꯟꯕ ꯃꯦꯆ ꯑꯗꯨ ꯃꯨꯝꯕꯥꯏꯒꯤ ꯋꯥꯡꯀꯦꯗꯦꯗꯤꯌꯝꯗꯥ ꯌꯨ ꯑꯦꯁ ꯑꯦꯒꯥ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  20%|█████▌                     | 205/1000 [03:31<10:10,  1.30it/s]

[205/1000]
EN: India faced Namibia on February 12 at Arun Jaitley Stadium in New Delhi.
MT: ꯚꯥꯔꯠꯅ ꯅꯕꯦꯝꯕꯔꯗꯥ ꯅꯤꯌꯨ ꯗꯤꯜꯂꯤꯒꯤ ꯑꯔꯨꯅ ꯖꯦꯇꯂꯤꯗꯤꯌꯝꯗꯥ ꯅꯥꯏꯃꯤꯕꯤꯌꯥꯒꯥ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  21%|█████▌                     | 206/1000 [03:31<09:46,  1.35it/s]

[206/1000]
EN: India travelled to Colombo to play Pakistan in a group-stage match.
MT: ꯚꯥꯔꯠꯅ ꯀꯂꯝꯕꯣꯗꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯥ ꯒꯄ-ꯦꯖ ꯃꯦꯆ ꯑꯃꯗ ꯁꯥꯟꯅꯅꯕ ꯆꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  21%|█████▌                     | 207/1000 [03:32<09:51,  1.34it/s]

[207/1000]
EN: Pakistan versus Netherlands was listed as a Group A fixture on February 7.
MT: ꯄꯥꯀꯤꯁꯇꯥꯟ ꯑꯃꯁꯨꯡ ꯅꯦꯗꯔꯂꯦꯟꯁ ꯑꯁꯤ ꯐꯦꯕꯋꯥꯔꯤꯗꯥ ꯒꯄ ꯑꯦꯒꯤ ꯐꯤꯛꯆꯔ ꯑꯃꯥ ꯑꯣꯏꯅ ꯂꯤꯁꯠ ꯇꯧ
--------------------------------------------------

Translating:  21%|█████▌                     | 208/1000 [03:33<09:33,  1.38it/s]

[208/1000]
EN: India versus USA was scheduled as a Group A match on February 7.
MT: ꯐꯕꯋꯥꯔꯤꯗꯥ ꯏꯟꯗꯤꯌꯥ ꯚꯔꯁ ꯌꯨ ꯑꯦꯁ ꯑꯦ ꯑꯁꯤ ꯒꯄ ꯑꯦꯒꯤ ꯃꯦꯆ ꯑꯃ ꯑꯣꯏꯅ ꯂꯦꯞꯈꯤ ꯫
--------------------------------------------------

Translating:  21%|█████▋                     | 209/1000 [03:34<10:01,  1.32it/s]

[209/1000]
EN: Group D fixtures began with Afghanistan playing New Zealand on February 8 in Chennai.
MT: ꯒꯄ ꯗꯤ ꯐꯤꯛꯆꯔꯁꯤꯡ ꯑꯁꯤ ꯑꯐꯒꯥꯅꯤꯁꯇꯥꯟꯅꯥ ꯅꯌꯨ ꯖꯤꯂꯦꯟꯗꯀ ꯁꯥꯟꯅꯗꯨꯅꯥ ꯐꯕꯋꯥꯔꯤꯗꯥ ꯆꯦꯟꯅꯥꯏꯗꯥ ꯍꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  21%|█████▋                     | 210/1000 [03:34<10:12,  1.29it/s]

[210/1000]
EN: Canada played South Africa on February 9 at Narendra Modi Stadium in Ahmedabad.
MT: ꯀꯦꯅꯥꯗꯥꯅꯥ ꯐꯕꯋꯥꯔꯤ ꯗꯥ ꯑꯍꯃꯗꯕꯥꯗꯀꯤ ꯅꯔꯦꯟ ꯃꯣꯗꯤꯗꯤꯌꯝꯗꯥ ꯁꯥꯎꯊ ꯑꯐꯀꯥꯗꯥ ꯁꯥꯟꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  21%|█████▋                     | 211/1000 [03:35<09:51,  1.33it/s]

[211/1000]
EN: Ishan Kishan smashed 61 off 24 balls against Namibia in New Delhi.
MT: ꯏꯁꯥꯟ ꯀꯤꯁꯟꯅ ꯅꯤꯌꯨ ꯗꯤꯜꯂꯤꯗꯥ ꯅꯥꯏꯃꯤꯕꯥꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯕꯣꯜꯗꯥ 61 ꯔꯟ ꯂꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  21%|█████▋                     | 212/1000 [03:36<10:03,  1.31it/s]

[212/1000]
EN: Hardik Pandya featured prominently as India posted 209 for nine against Namibia.
MT: ꯍꯔꯗꯤꯛ ꯄꯥꯟꯗꯌꯅꯥ ꯃꯁꯛ ꯊꯣꯛꯄ ꯁꯛꯇꯝ ꯂꯥꯡꯈꯤ ꯃꯔꯝꯗꯤ ꯚꯥꯔꯠꯅ ꯅꯥꯏꯃꯤꯕꯥꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯃꯥꯄꯟꯗ ꯄꯣꯂ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  21%|█████▊                     | 213/1000 [03:37<10:02,  1.31it/s]

[213/1000]
EN: Varun Chakaravarthy took three wickets as India beat Namibia by 93 runs.
MT: ꯋꯥꯔꯨꯟ ꯆꯀꯔꯥꯚꯔꯊꯤꯅꯥ ꯋꯤꯀꯦꯠ ꯑꯍꯨꯝ ꯂꯧꯈꯤꯕꯗꯒꯤ ꯚꯥꯔꯠꯅ ꯅꯥꯏꯃꯤꯕꯤꯌꯥꯕꯨ ꯔꯟ 93ꯅꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤ
--------------------------------------------------

Translating:  21%|█████▊                     | 214/1000 [03:37<09:39,  1.36it/s]

[214/1000]
EN: India bundled out Namibia for 116 while defending a target of 210.
MT: ꯚꯥꯔꯠꯅ ꯅꯤꯃꯤꯕꯤꯌꯥꯕꯨ ꯏꯪ ꯒꯤ ꯇꯔꯀꯦꯇ ꯑꯃ ꯉꯥꯛꯊꯣꯛꯂꯗꯨꯅ ꯏꯪ 116 ꯗꯥ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  22%|█████▊                     | 215/1000 [03:38<09:59,  1.31it/s]

[215/1000]
EN: Namibia captain Gerhard Erasmus won the toss and chose to bat first.
MT: ꯅꯦꯃꯤꯕꯥꯒꯤ ꯀꯦꯞꯇꯦꯟ ꯒꯥꯔꯍꯥꯔꯗ ꯏꯔꯥꯁꯃꯁꯅ ꯇꯣꯁ ꯑꯗꯨ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯑꯃꯁꯨꯡ ꯑꯍꯥꯟꯕꯗꯥ ꯕꯦꯇꯤꯡ ꯇꯧꯅꯕ ꯈꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  22%|█████▊                     | 216/1000 [03:39<09:42,  1.35it/s]

[216/1000]
EN: India versus Namibia started at 7:00 PM IST at Arun Jaitley Stadium.
MT: ꯏꯟꯗꯤꯌꯥ ꯚꯔꯁ नमꯕꯤꯕꯥ ꯑꯁꯤ ꯑꯔꯨꯅ ꯖꯦꯇꯂꯤꯗꯤꯌꯝꯗꯥ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯄꯨꯡ ꯗꯥ ꯍꯧ
--------------------------------------------------

Translating:  22%|█████▊                     | 217/1000 [03:40<09:09,  1.43it/s]

[217/1000]
EN: India’s first match was a win against the USA in Mumbai.
MT: ꯚꯥꯔꯠꯀꯤ ꯑꯍꯥꯟꯕꯥ ꯃꯦꯆ ꯑꯗꯨ ꯃꯨꯝꯕꯥꯏꯗ ꯌꯨ ꯑꯦꯁ ꯑꯦꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯃꯥꯏꯄꯥꯛꯄꯥ
--------------------------------------------------

Translating:  22%|█████▉                     | 218/1000 [03:40<08:36,  1.51it/s]

[218/1000]
EN: India versus Namibia was labelled as game 18 of the tournament.
MT: ꯏꯟꯗꯤꯌꯥ ꯚꯔꯁꯠ ꯅꯥꯃꯤꯕꯤꯌꯥ ꯑꯁꯤ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯁꯤꯒꯤ ꯒꯦꯝ ꯍꯥꯏꯅ ꯂꯦꯕꯦꯜ ꯇꯧ
--------------------------------------------------

Translating:  22%|█████▉                     | 219/1000 [03:41<09:10,  1.42it/s]

[219/1000]
EN: Suryakumar Yadav led India against Namibia in the ongoing T20 World Cup.
MT: ꯍꯧꯖꯤꯛ ꯆꯠꯊꯔꯤꯕ ꯇꯤ20 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯄꯇꯥ ꯅꯤꯃꯤꯕꯥꯒ ꯂꯥꯟꯊꯦꯡꯅꯕꯗ ꯁꯨꯔꯌꯀꯨꯃꯔ ꯌꯥꯗꯕꯅꯥ ꯚꯥꯔꯠꯄꯨ ꯂꯨꯆꯤꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  22%|█████▉                     | 220/1000 [03:42<09:01,  1.44it/s]

[220/1000]
EN: India entered the Namibia match after beating the USA in their opener.
MT: ꯚꯥꯔꯠꯅ ꯃꯈꯣꯏꯒꯤ ꯑꯣꯄꯦꯅꯔꯗꯥ ꯌꯨ ꯑꯦꯁ ꯑꯦꯕꯨ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯔꯕꯥ ꯃꯇꯨꯡꯗ ꯅꯥꯏꯃꯤꯕꯥ ꯃꯦꯆꯇꯥ ꯆꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  22%|█████▉                     | 221/1000 [03:42<08:25,  1.54it/s]

[221/1000]
EN: The Pakistan government allowed the Pakistan team to play India on February 15.
MT: ꯄꯥꯀꯤꯁꯇꯥꯟ ꯁꯔꯀꯥꯔꯅꯥ ꯐꯕꯋꯥꯔꯤꯗꯥ ꯚꯥꯔꯠꯇꯥ ꯁꯥꯟꯅꯕꯒꯤ ꯑꯌꯥꯕ ꯄꯤ
--------------------------------------------------

Translating:  22%|█████▉                     | 222/1000 [03:43<08:36,  1.51it/s]

[222/1000]
EN: India versus Pakistan was scheduled for Colombo after weeks of uncertainty.
MT: ꯆꯌꯣꯜ ꯀꯌꯥꯒꯤ ꯑꯔꯦꯞꯄ ꯂꯩꯇꯕꯥ ꯃꯇꯨꯡꯗ ꯏꯟꯗꯤꯌꯥ ꯚꯔꯁꯠ ꯄꯥꯀꯤꯁꯇꯥꯟ ꯑꯁꯤ ꯀꯣꯂꯝꯕꯣꯗꯥ ꯄꯥꯡꯊꯣꯛꯀꯗꯧꯔꯝꯃꯤ ꯫
--------------------------------------------------

Translating:  22%|██████                     | 223/1000 [03:44<08:47,  1.47it/s]

[223/1000]
EN: India versus Pakistan was described as a group-stage match in Colombo.
MT: ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡ ꯄꯥꯀꯤꯁꯇꯥꯟ ꯑꯁꯤ ꯀꯣꯂꯝꯕꯣꯗꯥ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯒꯨꯞ-ꯦꯖ ꯃꯦꯆꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  22%|██████                     | 224/1000 [03:44<08:50,  1.46it/s]

[224/1000]
EN: The tournament was listed as featuring 55 matches across India and Sri Lanka.
MT: ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯁꯤ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡꯂꯡꯀꯥ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯃꯦꯆ 55 ꯄꯥꯡꯊꯣꯛꯈꯤ ꯍꯥꯏꯅ ꯂꯤꯁꯠ ꯇꯧ
--------------------------------------------------

Translating:  22%|██████                     | 225/1000 [03:45<09:38,  1.34it/s]

[225/1000]
EN: The schedule included Delhi, Kolkata, Ahmedabad, Chennai, Mumbai, Colombo, and Kandy venues.
MT: ꯁꯦꯗꯜ ꯑꯁꯤꯗ ꯗꯤꯜꯂꯤ, ꯀꯣꯜꯀꯥꯇꯥ, ꯑꯍꯃꯗꯕꯥꯗ, ꯆꯦꯟꯅꯥꯏ, ꯃꯨꯝꯕꯥꯏ, ꯀꯣꯂꯝꯕꯣ ꯑꯃꯁꯨꯡ ꯀꯟꯗꯤꯒꯤ ꯃꯐꯝꯁꯤꯡ ꯌꯥꯎ
--------------------------------------------------

Translating:  23%|██████                     | 226/1000 [03:46<10:16,  1.26it/s]

[226/1000]
EN: Afghanistan faced New Zealand at M. A. Chidambaram Stadium with an 11:00 AM start.
MT: ꯑꯦꯝ. ꯑꯦ. ꯆꯤꯗꯝꯕꯔꯝꯗꯤꯌꯝꯗꯥ ꯑꯌꯨꯛ ꯄꯨꯡꯗꯒꯤ ꯍꯧꯕꯥ ꯃꯇꯝꯗꯥ ꯑꯐꯒꯥꯅꯤꯁꯇꯥꯟꯅꯥ ꯅꯖꯤꯂꯦꯟꯗꯀ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  23%|██████▏                    | 227/1000 [03:47<10:17,  1.25it/s]

[227/1000]
EN: New Zealand played UAE on February 10 at M. A. Chidambaram Stadium.
MT: ꯐꯕꯋꯥꯔꯤ ꯗꯥ ꯑꯦꯝ. ꯑꯦ. ꯆꯤꯗꯝꯕꯔꯝꯗꯤꯌꯝꯗꯥꯖꯤꯂꯦꯟꯗꯅꯥ ꯌꯨ.ꯑꯦ. ꯏ.ꯒꯥ ꯁꯥꯟꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  23%|██████▏                    | 228/1000 [03:48<10:33,  1.22it/s]

[228/1000]
EN: Group D included UAE, New Zealand, South Africa, Afghanistan, and Canada in one pool.
MT: ꯒꯄ ꯗꯤꯗꯥ ꯄꯨꯂ ꯑꯃꯗ ꯌꯨ ꯑꯦ ꯏ ꯅ ꯭ ꯌꯨ ꯖꯤꯂꯦꯟꯗ ꯈꯥ ꯑꯐꯀꯥ ꯑꯐꯒꯥꯅꯤꯁꯇꯥꯟ ꯑꯃꯁꯨꯡ ꯀꯅꯥꯗꯥ ꯌꯥꯎ
--------------------------------------------------

Translating:  23%|██████▏                    | 229/1000 [03:48<09:58,  1.29it/s]

[229/1000]
EN: India’s group-stage route moved from Mumbai to Delhi and then Colombo.
MT: ꯚꯥꯔꯠꯀꯤ ꯒꯄ-ꯦꯖ ꯂꯝꯕꯤ ꯑꯁꯤ ꯃꯨꯝꯕꯥꯏꯗꯒꯤ ꯗꯤꯜꯂꯤ ꯑꯃꯁꯨꯡ ꯃꯗꯨꯒꯤ ꯃꯇꯨꯡꯗ ꯀꯣꯂꯝꯕꯣꯗꯥ ꯍꯣꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  23%|██████▏                    | 230/1000 [03:49<10:13,  1.25it/s]

[230/1000]
EN: The India versus Namibia match preview named Gerhard Erasmus as Namibia’s captain.
MT: ꯏꯟꯗꯤꯌꯥ ꯚꯔꯁ ꯅꯥꯏꯃꯤꯕꯤꯌꯥ ꯃꯦꯆꯚꯗꯥ ꯅꯦꯃꯤꯕꯤꯌꯥꯒꯤ ꯀꯦꯞꯇꯦꯟ ꯑꯣꯏꯅ ꯒꯥꯔꯍꯥꯔꯗ ꯏꯔꯥꯁꯃꯁ ꯈꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  23%|██████▏                    | 231/1000 [03:50<10:09,  1.26it/s]

[231/1000]
EN: A report said Abhishek Sharma underwent checks for a stomach bug in New Delhi.
MT: ꯔꯤꯄꯣꯔꯇ ꯑꯃꯥꯅꯥ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯑꯚꯥꯁꯤꯛ ꯁꯔꯃꯥꯅꯥ ꯅ ꯗꯤꯜꯂꯤꯗꯥ ꯄꯣꯇꯥꯁꯒꯤ ꯕꯒ ꯑꯃ ꯆꯦꯛ ꯇꯧ
--------------------------------------------------

Translating:  23%|██████▎                    | 232/1000 [03:51<10:42,  1.20it/s]

[232/1000]
EN: The same report said Abhishek Sharma missed India’s Namibia game despite hospital discharge.
MT: ꯍꯣꯁꯄꯤꯇꯥꯜꯗꯒꯤ ꯗꯤꯁꯆꯥꯔꯖ ꯇꯧꯔꯕꯁꯨ ꯑꯚꯥꯁꯤꯛ ꯁꯔꯃꯥꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯅꯥꯃꯤꯕꯤꯌꯥ ꯒꯦꯝ ꯑꯗꯨ ꯃꯥꯡꯈꯤ ꯍꯥꯏꯅ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯃꯛꯇꯗꯥ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  23%|██████▎                    | 233/1000 [03:52<10:03,  1.27it/s]

[233/1000]
EN: Sanju Samson’s World Cup debut was described as lasting only eight deliveries.
MT: ꯁꯟꯖꯨ ꯁꯦꯝꯁꯣꯟꯒꯤ ꯑꯍꯥꯟꯕ ꯋꯥꯔꯂꯗ ꯀꯄ ꯑꯗꯨ ꯃꯇꯝ ꯅꯤꯄꯥꯜ ꯈꯛꯇꯃꯛ ꯂꯦꯞꯈꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  23%|██████▎                    | 234/1000 [03:52<09:28,  1.35it/s]

[234/1000]
EN: The tournament’s Group A opened across venues in India and Sri Lanka.
MT: ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯁꯤꯒꯤ ꯒꯄ ꯑꯦ ꯑꯁꯤ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡꯂꯡꯀꯥꯒꯤ ꯃꯐꯝ ꯄꯨꯝꯅꯃꯛꯇ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  24%|██████▎                    | 235/1000 [03:53<08:47,  1.45it/s]

[235/1000]
EN: India’s match against Namibia was played on Thursday, February 12.
MT: ꯅꯦꯃꯤꯕꯥꯒ ꯚꯥꯔꯇꯀꯤ ꯃꯦꯆ ꯑꯁꯤ ꯐꯦꯕꯋꯥꯔꯤ ꯇꯥꯡ ꯁꯨꯔꯦꯁꯟꯗ ꯁꯥꯟꯅ
--------------------------------------------------

Translating:  24%|██████▎                    | 236/1000 [03:54<09:41,  1.31it/s]

[236/1000]
EN: Nepal versus Italy appeared as a live-score fixture during the T20 World Cup schedule.
MT: ꯇꯤ20 ꯋꯥꯔꯂꯗ ꯀꯞꯀꯤ ꯁꯦꯗꯜꯗꯥ ꯅꯦꯄꯥꯜ ꯑꯃꯁꯨꯡ ꯏꯇꯂꯤꯒꯤ ꯃꯔꯛꯇ ꯂꯥꯏꯕ-ꯁꯣꯀꯔ ꯐꯤꯆꯆꯔ ꯑꯃ ꯑꯣꯏꯅ ꯎꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  24%|██████▍                    | 237/1000 [03:55<10:35,  1.20it/s]

[237/1000]
EN: Australia versus Zimbabwe appeared as a live-score fixture on the Indian Express cricket feed.
MT: ꯏꯟꯗꯤꯌꯟ ꯑꯦꯛꯁꯄꯦꯁ ꯀꯀꯦꯠ ꯐꯤꯗꯇꯥ ꯑꯣꯁꯇꯂꯤꯌꯥ ꯑꯃꯁꯨꯡ ꯖꯤꯝꯕꯥꯕꯦꯒꯤ ꯃꯔꯛꯇ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯑꯁꯤ ꯂꯥꯏꯚ-ꯁꯀꯣꯔ ꯐꯤꯛꯆꯔ ꯑꯃ ꯑꯣꯏꯅ ꯎꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  24%|██████▍                    | 238/1000 [03:56<10:27,  1.21it/s]

[238/1000]
EN: The Indian Express sports section highlighted India’s 93-run win over Namibia.
MT: ꯏꯟꯗꯤꯌꯟ ꯑꯦꯛꯁꯄꯔꯁꯄꯣꯔꯇꯁ ꯁꯦꯛꯁꯟ ꯑꯁꯤꯅ ꯅꯦꯃꯤꯕꯥꯕꯨ ꯚꯥꯔꯠꯅ ꯔꯟ 93ꯅꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯕꯒꯤ ꯃꯁꯛ ꯇꯥꯛ
--------------------------------------------------

Translating:  24%|██████▍                    | 239/1000 [03:56<10:13,  1.24it/s]

[239/1000]
EN: The match report said India’s bowling attack dismantled Namibia during the chase.
MT: ꯃꯦꯆ ꯔꯤꯄꯣꯔꯇꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯚꯥꯔꯠꯀꯤ ꯕꯣꯜꯂꯤꯡ ꯑꯦꯇꯦꯛꯅꯥ ꯇꯥꯟꯅꯕꯒꯤ ꯃꯇꯝꯗꯥ ꯅꯥꯏꯃꯤꯕꯤꯌꯥꯕꯨ ꯃꯥꯡꯍꯟ ꯇꯥꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  24%|██████▍                    | 240/1000 [03:57<10:02,  1.26it/s]

[240/1000]
EN: The India versus Namibia highlights credited Ishan Kishan’s 61 with driving India’s total.
MT: ꯏꯟꯗꯤꯌꯥ ꯚꯔꯁ ꯅꯦꯃꯤꯕꯤꯌꯥꯅꯥ ꯏꯁꯥꯟ ꯀꯤꯁꯥꯟꯒꯤ 61ꯅ ꯚꯥꯔꯠꯀꯤ ꯑꯄꯨꯟꯕꯕꯨ ꯊꯧꯒꯠꯈꯤ ꯍꯥꯏꯕ ꯑꯗꯨ ꯊꯣꯏꯗꯣꯛ ꯍꯦꯟꯗꯣꯛꯄ
--------------------------------------------------

Translating:  24%|██████▌                    | 241/1000 [03:58<09:54,  1.28it/s]

[241/1000]
EN: ISL 2025–26 fixtures began on February 14 with a double-header format.
MT: ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ 2025,26 ꯐꯤꯛꯆꯔꯁꯤꯡ ꯑꯁꯤ ꯗꯕꯜ-ꯍꯦꯗꯔ ꯐꯣꯔꯃꯦꯇ ꯑꯃꯒ ꯂꯣꯏꯅꯅ ꯐꯦꯕꯋꯥꯔꯤꯗꯥ ꯍꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  24%|██████▌                    | 242/1000 [03:59<10:08,  1.25it/s]

[242/1000]
EN: Mohun Bagan Super Giant faced Kerala Blasters in the season opener in Kolkata.
MT: ꯀꯣꯜꯀꯥꯇꯥꯗꯥ ꯁꯤꯖꯟ ꯑꯣꯄꯦꯅꯔꯗꯥ ꯃꯣꯍꯣꯟ ꯕꯥꯒꯥꯟ ꯁꯨꯄꯔ ꯖꯥꯏꯅꯇꯅ ꯀꯦꯔꯂꯥ ꯕꯁꯇꯔꯁꯀ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  24%|██████▌                    | 243/1000 [03:59<09:43,  1.30it/s]

[243/1000]
EN: FC Goa hosted Inter Kashi at Fatorda Stadium on February 14.
MT: ꯑꯦꯐ ꯁꯤ ꯒꯣꯋꯥꯅꯥ ꯐꯦꯕꯨꯋꯥꯔꯤꯗꯥ ꯐꯇꯣꯔꯗꯥꯗꯤꯌꯝꯗꯥ ꯏꯟꯇꯔ ꯀꯥꯁꯤ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  24%|██████▌                    | 244/1000 [04:00<09:05,  1.38it/s]

[244/1000]
EN: The first match on double-header days started at 5:00 PM IST.
MT: ꯗꯕꯜ-ꯍꯦꯗꯔ ꯗꯦꯗꯥ ꯑꯍꯥꯟꯕ ꯃꯦꯆ ꯑꯁꯤ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯄꯨꯡ ꯗꯥ ꯍꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  24%|██████▌                    | 245/1000 [04:01<08:39,  1.45it/s]

[245/1000]
EN: The second match on double-header days started at 7:30 PM IST.
MT: ꯗꯕꯜ-ꯍꯦꯗꯔ ꯗꯦꯗꯥ ꯑꯅꯤꯁꯨꯕ ꯃꯦꯆ ꯑꯁꯤ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯄꯨꯡ ꯗꯥ ꯍꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  25%|██████▋                    | 246/1000 [04:01<09:15,  1.36it/s]

[246/1000]
EN: A report said the ISL season would use a single-leg home-and-away format.
MT: ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯁꯤꯖꯟ ꯑꯁꯤꯗ ꯁꯤꯡꯒꯜ-ꯂꯦꯒ ꯍꯣꯝ- ꯑꯦꯟꯗ-ꯑꯋꯦ ꯐꯣꯔꯃꯦꯇ ꯑꯃ ꯁꯤꯖꯤꯟꯅꯒꯅꯤ ꯍꯥꯏꯅ ꯔꯤꯄꯣꯔꯇ ꯑꯃꯥꯅꯥ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  25%|██████▋                    | 247/1000 [04:02<10:10,  1.23it/s]

[247/1000]
EN: The Indian Express football page reported FanCode won exclusive ISL media rights.
MT: ꯏꯟꯗꯤꯌꯟ ꯑꯦꯛꯁꯄꯦꯁꯀꯤ ꯐꯨꯇꯕꯣꯜ ꯄꯦꯖꯗꯥ ꯐꯥꯟꯀꯣꯗꯅ ꯑꯦꯛꯁꯁꯤꯋꯦꯜ ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯃꯤꯗꯤꯌꯥ ꯔꯥꯏꯇꯁꯤꯡ ꯐꯪꯂꯦ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  25%|██████▋                    | 248/1000 [04:03<09:57,  1.26it/s]

[248/1000]
EN: The same report said ISL per-match valuation dropped by about 95 percent.
MT: ꯆꯞ ꯃꯥꯟꯅꯕ ꯔꯤꯄꯣꯔꯇ ꯑꯁꯤꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯄꯔ-ꯃꯦꯆ ꯚꯦꯜꯌꯨꯑꯦꯁꯟ ꯑꯁꯤ ꯆꯥꯎꯔꯥꯛꯅ ꯆꯥꯗ ꯍꯟꯊꯔꯦ ꯫
--------------------------------------------------

Translating:  25%|██████▋                    | 249/1000 [04:04<09:57,  1.26it/s]

[249/1000]
EN: The ISL report described a truncated season with pay cuts at multiple clubs.
MT: ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯒꯤ ꯔꯤꯄꯣꯔꯇ ꯑꯁꯤꯅ ꯀꯂꯕ ꯀꯌꯥꯗꯥ ꯄꯦ ꯀꯛꯊꯕꯥꯒ ꯂꯣꯏꯅꯅꯥ ꯁꯤꯖꯟ ꯑꯃ ꯀꯛꯊꯣꯛꯈꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  25%|██████▊                    | 250/1000 [04:05<10:14,  1.22it/s]

[250/1000]
EN: Real Madrid CF hoped a La Liga surge was boosted by a team dinner.
MT: ꯔꯦꯌꯦꯜ ꯃꯦꯗꯔꯤꯗ ꯁꯤꯐꯅꯥ ꯂꯥ ꯂꯤꯒꯥꯒꯤ ꯆꯥꯡ ꯍꯦꯟꯒꯠꯂꯛꯄ ꯑꯁꯤ ꯇꯤꯝꯒꯤ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯆꯤꯟꯖꯥꯛ ꯑꯃꯅ ꯍꯦꯟꯒꯠꯍꯟꯒꯅꯤ ꯍꯥꯏꯅ ꯊꯥꯖꯈꯤ ꯫
--------------------------------------------------

Translating:  25%|██████▊                    | 251/1000 [04:06<10:20,  1.21it/s]

[251/1000]
EN: The Real Madrid dinner was reportedly paid for by Vinícius Júnior and Kylian Mbappé.
MT: ꯔꯦꯌꯦꯜ ꯃꯦꯗꯗꯀꯤ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯆꯤꯟꯖꯥꯛ ꯑꯗꯨ ꯚꯤꯅꯤꯁꯤꯌꯁ ꯖꯨꯅꯤꯌꯔ ꯑꯃꯁꯨꯡ ꯀꯥꯏꯂꯤꯌꯟ ꯑꯦꯝꯕꯥꯄꯦꯅꯥ ꯄꯤꯈꯤꯕꯅꯤ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  25%|██████▊                    | 252/1000 [04:07<10:28,  1.19it/s]

[252/1000]
EN: Barcelona aimed for a fourth straight league win against Girona in La Liga.
MT: ꯕꯥꯔꯁꯤꯂꯣꯅꯥꯅꯥ ꯂꯥ ꯂꯤꯒꯥꯗꯥ ꯖꯤꯔꯣꯅꯥꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯃꯊꯪ-ꯇꯣꯉꯛꯄꯥ ꯃꯔꯤꯁꯨꯕ ꯂꯤꯒꯇ ꯃꯥꯏ ꯄꯥꯛꯄꯒꯤ ꯄꯥꯟꯗꯝ ꯊꯝ
--------------------------------------------------

Translating:  25%|██████▊                    | 253/1000 [04:07<10:33,  1.18it/s]

[253/1000]
EN: Barcelona visited Atlético Madrid for a Copa del Rey first-leg clash.
MT: ꯕꯥꯔꯁꯤꯂꯣꯅꯥꯅꯥ ꯑꯦꯇꯦꯇꯤꯀꯣ ꯃꯦꯗꯗꯇꯥ ꯀꯣꯄꯥ ꯗꯦꯂ ꯔꯦꯒꯤ ꯐꯔꯁꯠ ꯂꯦꯒ ꯀꯂꯦꯁꯀꯤꯗꯃꯛ ꯆꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  25%|██████▊                    | 254/1000 [04:08<10:32,  1.18it/s]

[254/1000]
EN: Barcelona entered the Atlético Madrid match after winning 17 of 18 matches.
MT: ꯕꯥꯔꯁꯤꯂꯣꯅꯥꯅꯥ ꯑꯦꯇꯦꯇꯤꯀꯣ ꯃꯦꯗꯗ ꯃꯦꯆꯇ ꯆꯪꯈꯤ ꯑꯃꯁꯨꯡ ꯃꯦꯊꯆ 18ꯒꯤ ꯃꯅꯨꯡꯗ 17 ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  26%|██████▉                    | 255/1000 [04:09<10:02,  1.24it/s]

[255/1000]
EN: Real Madrid and UEFA announced an agreement ending the Super League project.
MT: ꯔꯤꯌꯦꯜ ꯃꯦꯗꯗ ꯑꯃꯁꯨꯡ ꯌꯨ ꯏ ꯑꯦꯐ ꯑꯦꯅꯥ ꯁꯨꯄꯔ ꯂꯤꯒꯖꯦꯛꯇ ꯂꯣꯏꯁꯤꯟꯕꯥ ꯌꯥꯅꯕ ꯑꯃ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  26%|██████▉                    | 256/1000 [04:10<09:36,  1.29it/s]

[256/1000]
EN: Barcelona formally pulled out of the Super League days before the agreement.
MT: ꯌꯥꯅꯕ ꯑꯗꯨꯒꯤ ꯅꯨꯃꯤꯠ ꯈꯔꯅꯤꯒꯤ ꯃꯃꯥꯡꯗ ꯕꯥꯔꯁꯤꯂꯣꯅꯥꯅꯥ ꯁꯨꯄꯔ ꯂꯤꯒꯇꯒꯤ ꯐꯣꯔꯃꯦꯂꯤ ꯑꯣꯏꯅ ꯂꯧꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  26%|██████▉                    | 257/1000 [04:11<10:10,  1.22it/s]

[257/1000]
EN: Tottenham Hotspur reportedly sacked Thomas Frank after a 2–1 loss to Newcastle United.
MT: ꯇꯣꯇꯦꯅꯍꯃ ꯍꯣꯠꯁꯄꯨꯔꯅꯥ ꯇꯣꯃꯥꯁ ꯐꯦꯡꯀꯕꯨ ꯅꯀꯥꯁꯦꯜ ꯌꯨꯅꯤꯇꯦꯗꯇꯥ 2/1 ꯃꯥꯏꯊꯤꯔꯕ ꯃꯇꯨꯡꯗ ꯂꯧꯊꯣꯛꯈꯤ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  26%|██████▉                    | 258/1000 [04:11<09:55,  1.25it/s]

[258/1000]
EN: The Tottenham report said the club still had no league win in 2026.
MT: ꯇꯣꯇꯦꯅꯍꯝꯒꯤ ꯔꯤꯄꯣꯔꯇꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯏꯪꯁꯣꯛꯗꯥ ꯀꯂꯕ ꯑꯁꯤꯅ ꯍꯧꯖꯤꯛ ꯐꯥꯎꯕ ꯂꯤꯒ ꯃꯥꯏ ꯄꯥꯛꯄ ꯉꯝ
--------------------------------------------------

Translating:  26%|██████▉                    | 259/1000 [04:12<09:49,  1.26it/s]

[259/1000]
EN: Wayne Rooney said Arsenal looked mentally stronger in the Premier League title race.
MT: ꯋꯩꯅ ꯔꯨꯅꯤꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤꯃꯤꯌꯔ ꯂꯤꯒ ꯇꯥꯏꯇꯦꯜ ꯔꯦꯁꯇꯥ ꯑꯥꯔꯁꯅꯦꯜꯅꯥ ꯋꯥꯈꯜꯒꯤ ꯑꯣꯏꯅ ꯍꯦꯟꯅ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  26%|███████                    | 260/1000 [04:13<10:28,  1.18it/s]

[260/1000]
EN: Rooney noted Arsenal last won the Premier League title in the 2003–04 season.
MT: ꯔꯨꯅꯤꯅ ꯑꯔꯁꯦꯟꯜꯅꯥ ꯑꯔꯣꯏꯕ ꯑꯣꯏꯅ 2003/04 ꯁꯤꯖꯟꯗꯥꯃꯤꯌꯔ ꯂꯤꯒꯀꯤ ꯇꯥꯏꯇꯜ ꯐꯪꯈꯤ ꯍꯥꯏꯅ ꯈꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  26%|███████                    | 261/1000 [04:14<11:09,  1.10it/s]

[261/1000]
EN: Rooney said Arsenal led Manchester City by six points with 13 games remaining.
MT: ꯔꯨꯅꯤꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯑꯔꯁꯦꯟꯜꯅꯥ ꯃꯥꯟꯆꯦꯁꯇꯔ ꯁꯤꯇꯤꯕꯨ ꯄꯣꯏꯟꯇ ꯇꯔꯨꯛꯇꯥ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯈꯤ ꯑꯗꯨꯒ ꯒꯦꯝ 13 ꯂꯩ
--------------------------------------------------

Translating:  26%|███████                    | 262/1000 [04:15<11:33,  1.06it/s]

[262/1000]
EN: Cristiano Ronaldo missed a second straight Saudi Pro League match for Al-Nassr.
MT: ꯀꯇꯤꯌꯥꯅꯣ ꯔꯣꯅꯥꯂꯣꯅꯥ ꯑꯜ-ꯅꯥꯁꯔꯒꯤꯗꯃꯛ ꯑꯅꯤ ꯁꯨꯕꯥ ꯁꯎꯗꯤ ꯂꯤꯒ ꯃꯦꯆ ꯑꯃ ꯃꯥꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  26%|███████                    | 263/1000 [04:16<12:33,  1.02s/it]

[263/1000]
EN: Al-Nassr beat Al-Ittihad 2–0 despite Cristiano Ronaldo’s continued absence.
MT: ꯀꯇꯤꯌꯥꯅꯣ ꯔꯣꯅꯥꯂꯣꯅꯥ ꯃꯈꯥ ꯇꯥꯅ ꯌꯥꯎꯗꯕꯥꯁꯨ ꯑꯜ-ꯅꯥꯁꯔꯅꯥ ꯑꯂ-ꯏꯇꯤꯍꯥꯗ 2. ꯗ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  26%|███████▏                   | 264/1000 [04:18<13:27,  1.10s/it]

[264/1000]
EN: Sadio Mané and Angelo Gabriel scored for Al-Nassr in the win over Al-Ittihad.
MT: ꯁꯥꯗꯤꯌꯣ ꯃꯥꯅꯦ ꯑꯃꯁꯨꯡ ꯑꯦꯟꯖꯦꯂꯣ ꯒꯕꯦꯔꯤꯌꯦꯜꯅꯥ ꯑꯜ-ꯏꯇꯤꯍꯥꯗꯄꯨ ꯃꯥꯏꯊꯤꯕꯥ ꯄꯤꯔꯗꯨꯅꯥ ꯑꯂ-ꯅꯥꯁꯔꯒꯤꯗꯃꯛ ꯒꯣꯜ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  26%|███████▏                   | 265/1000 [04:19<12:43,  1.04s/it]

[265/1000]
EN: Sumit Nagal headlined the Delhi Open 2026 at the DLTA Complex.
MT: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯅꯥ ꯗꯤ ꯑꯦꯜ ꯇꯤ ꯑꯦ ꯀꯝꯄꯂꯦꯛꯁꯗꯥ ꯗꯤꯜꯂꯤ ꯑꯣꯄꯟ 2026 ꯗꯥ ꯂꯨꯆꯤꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  27%|███████▏                   | 266/1000 [04:19<11:47,  1.04it/s]

[266/1000]
EN: The Delhi Open 2026 tournament was scheduled for February 16 to 22.
MT: ꯗꯤꯜꯂꯤ ꯑꯣꯄꯟ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯁꯤ ꯐꯦꯕꯋꯥꯔꯤ ꯗꯒꯤ ꯐꯥꯎꯕ ꯄꯥꯡꯊꯣꯛꯀꯅꯤ ꯍꯥꯏꯅ ꯂꯦꯞ
--------------------------------------------------

Translating:  27%|███████▏                   | 267/1000 [04:20<12:08,  1.01it/s]

[267/1000]
EN: Britain’s Jay Clarke was named as a leading overseas entrant for Delhi Open 2026.
MT: ꯕꯇꯦꯟꯒꯤ ꯖꯦ ꯀꯂꯔꯀ ꯑꯁꯤ ꯗꯤꯜꯂꯤ ꯑꯣꯄꯟ 2026 ꯒꯤꯗꯃꯛ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯇ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯕꯥ ꯃꯤꯑꯣꯏ ꯑꯃ ꯑꯣꯏꯅ ꯈꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  27%|███████▏                   | 268/1000 [04:21<11:41,  1.04it/s]

[268/1000]
EN: The Delhi Open note said Sumit Nagal gained direct entry into the main draw.
MT: ꯗꯤꯜꯂꯤ ꯑꯣꯄꯟ ꯅꯣꯠꯇꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯅꯥ ꯃꯦꯟ ꯗꯗꯥ ꯍꯛꯊꯦꯡꯅꯅ ꯆꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  27%|███████▎                   | 269/1000 [04:22<12:23,  1.02s/it]

[269/1000]
EN: India beat the Netherlands 3–2 in Davis Cup competition to move closer.
MT: ꯗꯦꯚꯤꯁ ꯀꯄ ꯀꯝꯄꯤꯇꯤꯁꯟꯗꯥ ꯚꯥꯔꯠꯅ ꯅꯦꯗꯔꯂꯦꯟꯗꯁꯄꯨ 3. ꯗ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯗꯨꯅ ꯍꯦꯟꯅ ꯅꯛꯅꯕ ꯈꯣꯡꯊꯥꯡꯗ ꯆꯪꯁꯤꯜꯂꯛ
--------------------------------------------------

Translating:  27%|███████▎                   | 270/1000 [04:24<12:31,  1.03s/it]

[270/1000]
EN: Dhakshineswar Suresh featured prominently during India’s Davis Cup tie against the Netherlands.
MT: ꯅꯦꯗꯔꯂꯦꯟ ꯭ ꯁꯀ ꯃꯥꯏꯊꯤꯕꯥ ꯚꯥꯔꯠꯀꯤ ꯗꯦꯚꯤꯁ ꯀꯄ ꯇꯥꯏꯗꯥ ꯙꯛꯁꯤꯅꯦꯁ ꯁꯨꯔꯦꯁꯅ ꯃꯁꯛ ꯊꯣꯛꯄ ꯁꯛꯇꯝ ꯂꯥꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  27%|███████▎                   | 271/1000 [04:24<12:17,  1.01s/it]

[271/1000]
EN: India’s doubles pair beat David Pel and Sander Arends in a tight five-setter.
MT: ꯚꯥꯔꯠꯀꯤ ꯗꯕꯜꯁ ꯖꯌꯨꯔꯅꯥ ꯗꯦꯚꯤꯗ ꯄꯦꯂ ꯑꯃꯁꯨꯡ ꯁꯦꯟꯗꯔ ꯑꯦꯔꯦꯟꯗꯦꯁꯄꯨ ꯁꯦꯠ ꯃꯉꯥꯗꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  27%|███████▎                   | 272/1000 [04:25<12:10,  1.00s/it]

[272/1000]
EN: The doubles win was described as India’s first in five playoff ties versus Europeans.
MT: ꯗꯕꯜꯁ ꯃꯥꯏ ꯄꯥꯛꯄꯥ ꯑꯁꯤ ꯌꯨꯔꯣꯄꯤꯌꯟꯁꯤꯡꯒ ꯊꯦꯡꯅꯕꯂꯣꯐ ꯇꯥꯏ ꯃꯉꯥꯗꯥ ꯚꯥꯔꯠꯀꯤ ꯑꯍꯥꯟꯕꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  27%|███████▎                   | 273/1000 [04:26<12:06,  1.00it/s]

[273/1000]
EN: The same report said Sumit Nagal failed to seal the tie in reverse singles.
MT: ꯍꯥꯏꯔꯤꯕ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯃꯛꯇꯗꯥ ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯅꯥ ꯔꯤꯕꯔꯁ ꯁꯤꯡꯒꯜꯁꯗꯥ ꯇꯥꯏ ꯑꯗꯨ ꯁꯤꯜ ꯇꯧꯕ ꯉꯝꯈꯤꯗꯦ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  27%|███████▍                   | 274/1000 [04:27<11:55,  1.01it/s]

[274/1000]
EN: Novak Djokovic said he still wanted to represent Serbia in Davis Cup.
MT: ꯅꯣꯚꯥꯀ ꯖꯣꯀꯣꯚꯤꯀꯅꯥ ꯃꯍꯥꯛꯅ ꯍꯧꯖꯤꯛꯁꯨ ꯗꯦꯚꯤꯁ ꯀꯞꯇ ꯁꯦꯔꯕꯌꯥꯒꯤ ꯃꯤꯍꯨꯠ ꯑꯣꯏꯅꯕ ꯄꯥꯝꯃꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▍                   | 275/1000 [04:29<12:33,  1.04s/it]

[275/1000]
EN: Serbia captain Viktor Troicki described Novak Djokovic as a major team figure.
MT: ꯁꯦꯔꯕꯌꯥꯒꯤ ꯀꯦꯞꯇꯦꯟ ꯚꯤꯛꯇꯣꯔ ꯇꯣꯏꯀꯤꯅꯥ ꯅꯣꯕꯥꯛ ꯖꯣꯀꯣꯚꯤꯀ ꯑꯁꯤ ꯑꯆꯧꯕ ꯇꯤꯝꯒꯤ ꯃꯤꯑꯣꯏ ꯑꯃꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▍                   | 276/1000 [04:30<13:06,  1.09s/it]

[276/1000]
EN: Novak Djokovic withdrew from a 2025 Davis Cup qualifier due to a hamstring injury.
MT: ꯅꯣꯕꯥꯛ ꯖꯣꯀꯣꯚꯤꯀꯅꯥ ꯍꯦꯝꯁꯇꯤꯡꯗ ꯁꯣꯛꯄꯥ ꯃꯔꯝꯗꯥ ꯏꯪ 2025 ꯗꯥ ꯗꯦꯚꯤꯁ ꯀꯄꯋꯥꯂꯤꯐꯌꯔꯗꯒꯤ ꯂꯧꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▍                   | 277/1000 [04:31<13:55,  1.16s/it]

[277/1000]
EN: Carlos Alcaraz beat Alexander Zverev in a five-hour, 27-minute Australian Open semifinal.
MT: ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯑꯂꯦꯛꯖꯦꯟꯗꯔ ꯖꯚꯦꯔꯦꯚꯄꯨ ꯄꯨꯡ ꯃꯉꯥꯒꯤ ꯃꯤꯅꯤꯇ 27ꯀꯤ ꯑꯣꯁꯇꯂꯤꯌꯟ ꯑꯣꯄꯟ ꯁꯦꯃꯤꯐꯥꯏꯅꯦꯜꯗꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▌                   | 278/1000 [04:32<13:43,  1.14s/it]

[278/1000]
EN: Carlos Alcaraz won the Australian Open final after facing Novak Djokovic.
MT: ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯑꯣꯁꯇꯂꯤꯌꯥ ꯑꯣꯄꯟ ꯐꯥꯏꯅꯦꯜ ꯑꯗꯨ ꯅꯣꯚꯥꯀ ꯖꯣꯀꯣꯚꯤꯀꯒꯥ ꯃꯥꯌꯣꯛꯅꯔꯒ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▌                   | 279/1000 [04:33<13:24,  1.12s/it]

[279/1000]
EN: Jannik Sinner was described as holding five straight wins over Novak Djokovic.
MT: ꯖꯅꯤꯛ ꯁꯤꯟꯅꯔ ꯑꯁꯤ ꯅꯣꯕꯥꯛ ꯖꯣꯀꯣꯚꯤꯀꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯂꯦꯞꯇꯅ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯃꯉꯥ ꯐꯪ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▌                   | 280/1000 [04:35<14:43,  1.23s/it]

[280/1000]
EN: The Djokovic–Sinner preview said Djokovic reached semifinals aided by a walkover and retirement.
MT: ꯖꯣꯀꯣꯚꯤꯛ ꯁꯤꯟꯅꯔꯚꯨꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯖꯀꯣꯚꯤꯀꯅ ꯋꯥꯀꯣꯚꯔ ꯑꯃꯁꯨꯡ ꯔꯤꯑꯥꯏꯇꯔꯃꯦꯟꯠ ꯑꯃꯒꯤ ꯃꯇꯦꯡꯅꯥ ꯁꯦꯃꯤꯐꯥꯏꯅꯦꯜꯗ ꯌꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▌                   | 281/1000 [04:36<14:16,  1.19s/it]

[281/1000]
EN: An Australian Open report said extreme heat forced temporary suspensions on outside courts.
MT: ꯑꯣꯁꯇꯂꯤꯌꯥꯟ ꯑꯣꯄꯟ ꯔꯤꯄꯣꯔꯇ ꯑꯃꯅ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯌꯥꯝꯅ ꯁꯥꯊꯤꯕ ꯑꯁꯥꯕꯅ ꯀꯣꯔꯠꯁꯤꯡꯒꯤ ꯃꯄꯥꯟꯗꯥ ꯃꯇꯝ ꯈꯔꯒꯤ ꯑꯣꯏꯅ ꯁꯁꯄꯦꯟꯁꯟ ꯇꯧꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▌                   | 282/1000 [04:37<13:38,  1.14s/it]

[282/1000]
EN: The same report said organisers issued heat warnings for players and spectators.
MT: ꯍꯥꯏꯔꯤꯕ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯃꯛꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯑꯣꯔꯖꯦꯟꯁꯔꯁꯤꯡꯅꯥ ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯌꯦꯡꯂꯤꯕꯁꯤꯡꯒꯤꯗꯃꯛꯇ ꯍꯤꯇ ꯋꯥꯔꯅꯤꯡꯁꯤꯡ ꯄꯤ
--------------------------------------------------

Translating:  28%|███████▋                   | 283/1000 [04:38<14:01,  1.17s/it]

[283/1000]
EN: Jannik Sinner beat Eliot Spizzirri 4–6, 6–3, 6–4, 6–4 in Melbourne.
MT: ꯖꯅꯤꯛ ꯁꯤꯟꯅꯔꯅ ꯏꯂꯤꯑꯣꯇꯄꯤꯖꯤꯔꯤꯕꯨ ꯃꯦꯜꯕꯣꯔꯟꯗ 4,6,6,3,6,4/6 ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▋                   | 284/1000 [04:40<15:12,  1.27s/it]

[284/1000]
EN: A tennis feature said Fangran Tian was coached by Chennai’s Mangal Sriram since age 12.
MT: ꯇꯦꯅꯤꯁ ꯐꯤꯆꯔ ꯑꯃꯥꯅꯥ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯐꯥꯡꯒꯔꯥꯅ ꯇꯤꯌꯥꯅ ꯑꯁꯤ ꯆꯍꯤꯗꯒꯤ ꯆꯦꯟꯅꯥꯏꯒꯤ ꯃꯡꯒꯜ ꯁꯔꯤꯔꯥꯃꯅ ꯀꯣꯆ ꯇꯧꯔꯝꯃꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▋                   | 285/1000 [04:41<14:53,  1.25s/it]

[285/1000]
EN: Badminton World Federation demoted Syed Modi International from Super 300 to Super 100.
MT: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯋꯥꯔ ꯐꯦꯗꯔꯦꯁꯟꯅꯥ ꯁꯥꯏꯗ ꯃꯣꯗꯤ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜꯕꯨ ꯁꯨꯄꯔꯗꯒꯤ ꯁꯨꯄꯔꯗꯥ ꯍꯟꯊꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  29%|███████▋                   | 286/1000 [04:42<14:27,  1.21s/it]

[286/1000]
EN: The same report said India Open retained Super 750 status for the 2027–2030 cycle.
MT: ꯏꯪꯁꯣꯛ 20272030 ꯒꯤꯗꯃꯛ ꯏꯟꯗꯤꯌꯥ ꯑꯣꯄꯟꯅꯥ ꯁꯨꯄꯔ ꯁꯇꯥꯇꯁ ꯊꯝꯃꯤ ꯍꯥꯏꯅ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯃꯛꯅꯥ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  29%|███████▋                   | 287/1000 [04:43<15:10,  1.28s/it]

[287/1000]
EN: A badminton reforms report said World Championships and five Super 1000s will run 11 days.
MT: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯔꯤꯐꯣꯔꯃ ꯔꯤꯄꯣꯔꯇꯥ ꯋꯜꯗ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯞ ꯑꯃꯁꯨꯡ ꯁꯨꯄꯔ 1000 ꯃꯉꯥꯅꯥ ꯅꯨꯃꯤꯠ 11ꯅꯤ ꯆꯂꯥꯏꯒꯅꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  29%|███████▊                   | 288/1000 [04:45<15:54,  1.34s/it]

[288/1000]
EN: The Indian Express said BWF’s AGM 2026 would vote on a 3×15 scoring format.
MT: ꯏꯟꯗꯤꯌꯟ ꯑꯦꯛꯁꯄꯦꯁꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯕꯤ.ꯎ.ꯑꯦꯐ.ꯒꯤ ꯑꯦ.ꯖꯤ.ꯑꯦꯝ. 2026ꯅꯥ 3. ꯁꯀꯣꯔꯤꯡ ꯐꯣꯔꯃꯦꯇ ꯑꯃꯗ ꯚꯣꯠ ꯄꯤꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  29%|███████▊                   | 289/1000 [04:46<15:01,  1.27s/it]

[289/1000]
EN: A Badminton Asia Team report said India lost 3–2 to Japan in men’s ties.
MT: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯑꯦꯁꯤꯌꯥ ꯇꯤꯝꯒꯤ ꯔꯤꯄꯣꯔꯇꯥ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯅꯨꯄꯥꯒꯤ ꯇꯥꯏꯗꯥ ꯚꯥꯔꯠꯅ ꯖꯄꯥꯟꯗꯥ 3. ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  29%|███████▊                   | 290/1000 [04:47<13:50,  1.17s/it]

[290/1000]
EN: The same report said India lost to Thailand in women’s ties at the team event.
MT: ꯇꯤꯝ ꯏꯚꯦꯟꯇ ꯑꯁꯤꯗ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯇꯥꯏꯗꯥ ꯚꯥꯔꯠꯅ ꯊꯥꯏꯂꯦꯟꯗꯇꯥ ꯃꯥꯏꯊꯤꯈꯤ ꯍꯥꯏꯅ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯃꯛꯅꯥ ꯍꯥꯏ
--------------------------------------------------

Translating:  29%|███████▊                   | 291/1000 [04:48<13:46,  1.17s/it]

[291/1000]
EN: A selection report said Tanvi Sharma would play first singles after Unnati Hooda was out.
MT: ꯁꯦꯂꯦꯀꯁꯟ ꯔꯤꯄꯣꯔꯇ ꯑꯃꯗ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯎꯟꯅꯥꯇꯤ ꯍꯨꯗꯥ ꯑꯥꯎꯠ ꯇꯧꯔꯕꯥ ꯃꯇꯨꯡꯗ ꯇꯥꯟꯚꯤ ꯁꯔꯃꯥꯅꯥ ꯑꯍꯥꯟꯕ ꯁꯤꯡꯒꯜꯁ ꯁꯥꯟꯅꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  29%|███████▉                   | 292/1000 [04:49<13:46,  1.17s/it]

[292/1000]
EN: An India Open report said “nest materials” halted a women’s doubles semifinal in Delhi.
MT: ꯏꯟꯗꯤꯌꯥ ꯑꯣꯄꯟ ꯔꯤꯄꯣꯔꯇꯥ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯅꯦ ꯃꯦꯇꯦꯜꯅꯥ ꯗꯤꯜꯂꯤꯗꯥ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯗꯕꯜꯁ ꯁꯦꯃꯤꯐꯥꯏꯅꯦꯜ ꯑꯃ ꯊꯤꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  29%|███████▉                   | 293/1000 [04:50<13:09,  1.12s/it]

[293/1000]
EN: A feature said An Se-young won 94.8 percent of her matches in 2025.
MT: ꯏꯪ 2025 ꯗꯥ ꯑꯦꯟ ꯁꯦ-ꯌꯨꯡꯅꯥ ꯃꯍꯥꯛꯀꯤ ꯃꯦꯆꯁꯤꯡꯒꯤ ꯆꯥꯗ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯍꯥꯏꯅ ꯐꯤꯆꯔ ꯑꯃꯅ ꯍꯥꯏ
--------------------------------------------------

Translating:  29%|███████▉                   | 294/1000 [04:51<12:45,  1.08s/it]

[294/1000]
EN: The same feature said An Se-young began 2026 with two titles in two weeks.
MT: ꯆꯞ ꯃꯥꯟꯅꯕ ꯐꯤꯆꯔ ꯑꯁꯤꯅ ꯍꯥꯏꯔꯝꯃꯤ ꯃꯗꯨꯗꯤ ꯑꯦꯟ ꯁꯦ-ꯌꯨꯡ ꯑꯁꯤ ꯆꯌꯣꯜ ꯑꯅꯤꯒꯤ ꯃꯅꯨꯡꯗ ꯇꯥꯏꯇꯦꯜ ꯑꯅꯤꯒ ꯂꯣꯏꯅꯅꯥ ꯏꯪ 2026ꯗꯥ ꯍꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|███████▉                   | 295/1000 [04:52<12:35,  1.07s/it]

[295/1000]
EN: Lin Chun-yi beat Jonatan Christie 21–10, 21–18 in the India Open final.
MT: ꯏꯟꯗꯤꯌꯥ ꯑꯣꯄꯟ ꯐꯥꯏꯅꯦꯜꯗꯥ ꯂꯤꯅ ꯆꯨꯅ-ꯌꯤꯅꯥ ꯖꯣꯅꯥꯇꯟꯇꯤꯕꯨ 21,10,21,18 ꯗꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|███████▉                   | 296/1000 [04:53<12:15,  1.05s/it]

[296/1000]
EN: Devika Sihag beat Navya Kanderi 21–10, 21–13 to win in Baku.
MT: ꯗꯦꯕꯤꯀꯥ ꯁꯤꯍꯥꯒꯅꯥ ꯕꯥꯀꯨꯗꯥ ꯅꯥꯚꯌ ꯀꯟꯗꯦꯔꯤꯕꯨ 21,10,2113 ꯗꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯗꯨꯅ ꯃꯥꯏꯄꯥꯛ
--------------------------------------------------

Translating:  30%|████████                   | 297/1000 [04:54<12:36,  1.08s/it]

[297/1000]
EN: Radhika Sharma won her first mixed doubles title partnering Sathwik Reddy.
MT: ꯔꯥꯙꯤꯀꯥ ꯁꯔꯃꯥꯅꯥ ꯃꯍꯥꯛꯀꯤ ꯑꯍꯥꯟꯕꯥ ꯃꯤꯛꯁꯗ ꯗꯕꯜꯁ ꯇꯥꯏꯇꯥꯜ ꯑꯁꯤ ꯁꯥꯊꯋꯤꯀ ꯔꯦꯗꯤꯒꯥ ꯁꯔꯨꯛ ꯌꯥꯗꯨꯅ ꯐꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|████████                   | 298/1000 [04:56<13:38,  1.17s/it]

[298/1000]
EN: Ankur Bhattacharjee upset world-ranked opponent Bourrassaud 3–1 at WTT Chennai.
MT: ꯗꯕꯜꯌꯨꯇꯤꯇꯤ ꯆꯦꯟꯅꯥꯏꯗꯥ ꯑꯡꯀꯨꯔ ꯚꯠꯇꯥꯆꯥꯔꯖꯤꯅꯥ ꯋꯜꯗ-ꯔꯦꯟꯀꯀꯤ ꯌꯦꯛꯅꯕ ꯕꯣꯔꯔꯥꯁꯣꯗ 3/1 ꯗꯥ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|████████                   | 299/1000 [04:57<14:46,  1.26s/it]

[299/1000]
EN: FIFA president Gianni Infantino faced criticism over high-priced tickets for the 2026 World Cup.
MT: ꯐꯤꯐꯥꯒꯤꯁꯤꯗꯦꯟꯇ ꯖꯤꯌꯥꯅꯤ ꯏꯟꯐꯦꯟꯇꯤꯅꯣꯅꯥ ꯏꯪꯁꯣꯛ 2026 ꯒꯤ ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞꯀꯤ ꯃꯃꯜ ꯋꯥꯡꯕꯥ ꯇꯤꯀꯦꯠꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯌꯦꯠꯅꯕ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|████████                   | 300/1000 [04:59<14:34,  1.25s/it]

[300/1000]
EN: India lost 1-3 to Belgium in the FIH Pro League opener at Rourkela.
MT: ꯔꯧꯔꯀꯦꯂꯥꯗꯥ ꯄꯥꯡꯊꯣꯛꯂꯤꯕꯥ ꯑꯦꯐ ꯑꯥꯏ ꯑꯩꯆ ꯂꯤꯒ ꯑꯣꯄꯦꯅꯔꯗꯥ ꯚꯥꯔꯠꯅ ꯕꯦꯜꯖꯤꯌꯝꯗꯥ 1- ꯗ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|████████▏                  | 301/1000 [05:00<14:17,  1.23s/it]

[301/1000]
EN: Craig Fulton said India’s defensive structure did not deliver in the Pro League opener.
MT: ꯏꯒ ꯐꯜꯇꯟꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯚꯥꯔꯠꯀꯤ ꯗꯤꯐꯦꯟꯁꯤꯚꯁꯇꯆꯔꯅꯥ ꯂꯤꯒ ꯑꯣꯄꯦꯅꯔꯗꯥ ꯃꯄꯨꯡ ꯐꯥꯍꯟꯗꯦ ꯫
--------------------------------------------------

Translating:  30%|████████▏                  | 302/1000 [05:01<13:12,  1.14s/it]

[302/1000]
EN: India then suffered a 0-8 loss to Argentina in the next Pro League match.
MT: ꯃꯗꯨꯒꯤ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯅ ꯃꯊꯪꯒꯤ ꯂꯤꯒ ꯃꯦꯆꯇꯥ ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯗꯥ 0-8 ꯗ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|████████▏                  | 303/1000 [05:02<12:51,  1.11s/it]

[303/1000]
EN: India’s 0-8 defeat was described as a systematic demolition by Argentina.
MT: ꯚꯥꯔꯠꯇꯥ ꯃꯥꯏꯊꯤꯕꯥ 0-8 ꯑꯁꯤ ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯅꯥ ꯁꯤꯁꯇꯦꯃꯦꯇꯤꯛ ꯗꯤꯃꯣꯂꯦꯁꯟꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|████████▏                  | 304/1000 [05:03<12:58,  1.12s/it]

[304/1000]
EN: India’s 0-8 loss matched the joint third-worst defeat in India’s hockey history.
MT: ꯚꯥꯔꯠꯀꯤ ꯍꯣꯀꯤꯒꯤ ꯍꯤꯁꯇꯔꯤꯗꯥ ꯚꯥꯔꯠꯅ- ꯗ ꯃꯥꯏꯊꯤꯕꯥ ꯑꯁꯤ ꯄꯨꯟꯅ ꯑꯍꯨꯝꯁꯨꯕꯗꯥ ꯈ ꯭ ꯋꯥꯏꯗꯒꯤ ꯁꯥꯊꯤꯕ ꯃꯥꯏꯊꯤꯕ ꯑꯗꯨꯒ ꯃꯥꯟꯅ
--------------------------------------------------

Translating:  30%|████████▏                  | 305/1000 [05:04<13:44,  1.19s/it]

[305/1000]
EN: India’s other 0-8 losses came in 1985 versus Netherlands and 2010 versus Australia.
MT: ꯏꯪꯁꯣꯛ ꯗꯥ ꯅꯦꯗꯔꯂꯦꯟꯗꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯚꯥꯔꯠꯅ 0- ꯗ ꯃꯥꯏꯊꯤꯈꯤ ꯑꯃꯁꯨꯡ 2010 ꯗꯥ ꯑꯣꯁꯇꯦꯂꯤꯌꯥꯒꯤ ꯃꯥꯏꯄꯥꯛꯇꯥ ꯃꯥꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▎                  | 306/1000 [05:05<12:50,  1.11s/it]

[306/1000]
EN: Argentina’s Tomas Domene scored four goals in the 0-8 win over India.
MT: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯒꯤ ꯇꯣꯃꯥꯁ ꯗꯣꯃꯤꯅꯦꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ 0-8 ꯒꯤ ꯃꯥꯏꯄꯥꯛꯄꯗ ꯒꯣꯜ ꯃꯔꯤ ꯂꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▎                  | 307/1000 [05:06<12:27,  1.08s/it]

[307/1000]
EN: Tomas Domene scored at 15th, 20th, 26th and 60th minutes against India.
MT: ꯇꯣꯃꯥꯁ ꯗꯣꯃꯤꯅꯦꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯃꯥꯌꯣꯛꯇꯥ 15 ꯁꯨꯕ, 20ꯁꯨꯕ, 26ꯁꯨꯕ ꯑꯃꯁꯨꯡ 60ꯁꯨꯕ ꯃꯤꯅꯤꯇꯗꯥꯣꯔ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▎                  | 308/1000 [05:07<13:25,  1.16s/it]

[308/1000]
EN: Tomas Ruiz, Lucio Mendez, Ignacio Ibarra, and Nicolas della Torre also scored for Argentina.
MT: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯒꯤꯗꯃꯛ ꯇꯣꯃꯥꯁ ꯔꯨꯏꯖ, ꯂꯨꯁꯤꯑꯣ ꯃꯦꯟꯗꯦꯁ, ꯏꯒꯅꯥꯁꯤꯌꯣ ꯏꯕꯥꯔꯥ ꯑꯃꯁꯨꯡ ꯅꯤꯀꯣꯂꯥꯁ ꯗꯦꯂꯥ ꯇꯣꯔꯦꯅꯥꯁꯨꯣꯜ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▎                  | 309/1000 [05:08<12:53,  1.12s/it]

[309/1000]
EN: India’s third quarter without conceding a goal looked like an anomaly in the match.
MT: ꯚꯥꯔꯠꯀꯤ ꯑꯍꯨꯝꯁꯨꯕ ꯀ ꯭ ꯋꯥꯇꯔꯗꯥ ꯒꯣꯜ ꯑꯃꯠꯇ ꯄꯤꯗꯕꯅꯥ ꯃꯦꯆ ꯑꯗꯨꯗ ꯑꯅꯣꯃꯂꯤ ꯑꯃ ꯑꯣꯏꯅ ꯎꯕ ꯐꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▎                  | 310/1000 [05:09<12:32,  1.09s/it]

[310/1000]
EN: Player-of-the-Match Tomas Domene said Argentina played the whole game at 100 percent.
MT: ꯃꯦꯆꯀꯤ ꯁꯥꯟꯅꯔꯣꯏ ꯇꯣꯃꯥꯁ ꯗꯣꯃꯤꯅꯦꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯅꯥꯅ ꯒꯦꯝ ꯄꯨꯝꯅꯃꯛ ꯆꯥꯗꯗꯥ ꯁꯥꯟꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▍                  | 311/1000 [05:11<13:22,  1.16s/it]

[311/1000]
EN: Tomas Domene said Argentina were disappointed after losing 3-5 to Belgium previously.
MT: ꯇꯣꯃꯥꯁ ꯗꯣꯃꯤꯅꯦꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯑꯔꯖꯦꯟꯇꯤꯅꯥ ꯑꯁꯤ ꯃꯃꯥꯡꯗ ꯕꯦꯜꯖꯤꯌꯝꯗꯥ- ꯗ ꯃꯥꯏꯊꯤꯔꯕꯥꯗꯒꯤ ꯅꯤꯡꯉꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▍                  | 312/1000 [05:12<13:07,  1.15s/it]

[312/1000]
EN: Argentina scored two quick goals at the end of the first quarter.
MT: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯅꯥ ꯑꯍꯥꯟꯕꯥ ꯀꯋꯥꯔꯇꯔ ꯂꯣꯏꯔꯛꯄꯗꯥꯀꯤꯛ ꯒꯣꯜ ꯑꯅꯤ ꯂꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▍                  | 313/1000 [05:13<11:57,  1.04s/it]

[313/1000]
EN: Argentina scored five goals in 10 minutes during the second quarter.
MT: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯅꯥ ꯑꯅꯤꯁꯨꯕ ꯀ ꯭ ꯋꯥꯇꯔꯗꯥ ꯃꯤꯅꯤꯇꯗꯥ ꯒꯣꯜ ꯃꯉꯥ ꯂꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▍                  | 314/1000 [05:14<14:04,  1.23s/it]

[314/1000]
EN: Harmanpreet Singh missed two penalty strokes in the match against Argentina.
MT: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯃꯦꯆ ꯑꯗꯨꯗ ꯍꯔꯃꯟꯄꯤꯇ ꯁꯤꯡꯍꯅꯥ ꯄꯦꯅꯥꯜꯇꯤ ꯁꯣꯛ ꯑꯅꯤ ꯃꯥꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▌                  | 315/1000 [05:16<14:43,  1.29s/it]

[315/1000]
EN: India missed three penalty corners during the 0-8 defeat against Argentina.
MT: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ 0-8 ꯗꯥ ꯃꯥꯏꯊꯤꯕꯥ ꯃꯇꯝꯗ ꯚꯥꯔꯠꯅ ꯄꯦꯅꯥꯜꯇꯤ ꯀꯣꯔꯅꯔ ꯑꯍꯨꯝ ꯃꯥꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▌                  | 316/1000 [05:17<13:33,  1.19s/it]

[316/1000]
EN: India goalkeepers Suraj Karkera and Pawan looked completely out of place.
MT: ꯚꯥꯔꯠꯀꯤ ꯒꯣꯜꯀꯤꯄꯔ ꯁꯨꯔꯖ ꯀꯥꯔꯀꯦꯔꯥ ꯑꯃꯁꯨꯡ ꯄꯋꯅ ꯑꯁꯤ ꯃꯄꯨꯡꯐꯥꯅꯥ ꯂꯝꯕꯥ ꯉꯝ
--------------------------------------------------

Translating:  32%|████████▌                  | 317/1000 [05:18<13:44,  1.21s/it]

[317/1000]
EN: Argentina dominated possession and toyed with India’s midfield and defence.
MT: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯅꯥ ꯄꯣꯖꯦꯁꯟꯗ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯈꯤ ꯑꯃꯁꯨꯡ ꯚꯥꯔꯠꯀꯤ ꯃꯤꯗꯐꯤꯜꯗ ꯑꯃꯁꯨꯡ ꯗꯤꯐꯦꯟꯁꯒꯥ ꯁꯥꯟꯅ
--------------------------------------------------

Translating:  32%|████████▌                  | 318/1000 [05:19<12:54,  1.14s/it]

[318/1000]
EN: Argentina’s win catapulted them to fourth in the nine-team standings.
MT: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯒꯤ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯑꯁꯤꯅ ꯃꯈꯣꯏꯕꯨ ꯇꯤꯝ ꯃꯥꯄꯟꯒꯤꯟꯗꯤꯡꯗꯥ ꯃꯔꯤ ꯁꯨꯕꯥ ꯃꯐꯝꯗ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▌                  | 319/1000 [05:20<13:02,  1.15s/it]

[319/1000]
EN: India next faced world No.2 Belgium again after the heavy Argentina loss.
MT: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯗꯥ ꯑꯆꯧꯕ ꯃꯥꯏꯊꯤꯕꯥ ꯐꯪꯂꯕ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯅ ꯃꯊꯪꯗꯥ ꯃꯥꯂꯦꯝꯒꯤ ꯅꯝꯕꯔ 2ꯒꯤ ꯕꯦꯜꯖꯤꯌꯝꯒꯥ ꯑꯃꯨꯛ ꯍꯟꯅ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▋                  | 320/1000 [05:21<13:38,  1.20s/it]

[320/1000]
EN: Macklin Celebrini scored early to spark Canada’s 5-0 win over Czech Republic.
MT: ꯃꯦꯀꯂꯤꯟ ꯁꯦꯂꯦꯕꯅꯤꯅꯥ ꯑꯍꯥꯟꯕꯥ ꯃꯇꯝꯗ ꯒꯣꯜ ꯇꯧꯗꯨꯅ ꯀꯅꯥꯗꯥꯒꯤ ꯆꯦꯛ ꯔꯤꯄꯕꯂꯤꯛꯀꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ- ꯗ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▋                  | 321/1000 [05:23<13:26,  1.19s/it]

[321/1000]
EN: Macklin Celebrini scored with just over five seconds left in the first period.
MT: ꯃꯦꯀꯂꯤꯟ ꯁꯦꯂꯦꯕꯅꯤꯅꯥ ꯑꯍꯥꯟꯕꯥ ꯄꯦꯔꯤꯑꯣꯗꯗꯥ ꯁꯦꯀꯦꯟꯗ ꯃꯉꯥꯗꯒꯤ ꯈꯔ ꯍꯦꯟꯅ ꯂꯩꯔꯒꯣꯔ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▋                  | 322/1000 [05:24<14:07,  1.25s/it]

[322/1000]
EN: Mark Stone, Bo Horvat, Nathan MacKinnon and Nick Suzuki scored in Canada’s opener.
MT: ꯃꯥꯔꯛꯣꯟ, ꯕꯣ ꯍꯣꯔꯚꯇ, ꯅꯥꯊꯥꯟ ꯃꯦꯛꯀꯤꯅꯣꯟ ꯑꯃꯁꯨꯡ ꯅꯤꯛ ꯁꯨꯖꯨꯀꯤꯅꯥ ꯀꯅꯥꯗꯥꯒꯤ ꯑꯣꯄꯦꯅꯔꯗꯥ ꯒꯣꯜ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▋                  | 323/1000 [05:25<13:14,  1.17s/it]

[323/1000]
EN: Connor McDavid recorded three assists in Canada’s 5-0 Olympic win.
MT: ꯀꯣꯅꯣꯔ ꯃꯛꯗꯥꯚꯤꯗꯅ ꯀꯅꯥꯗꯥꯒꯤ- ꯑꯣꯂꯤꯝꯄꯤꯛ ꯃꯥꯏ ꯄꯥꯛꯄꯗ ꯑꯦꯁꯤꯇ ꯑꯍꯨꯝ ꯔꯦꯀꯣꯔꯗ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▋                  | 324/1000 [05:26<13:11,  1.17s/it]

[324/1000]
EN: Sidney Crosby said Celebrini’s first Olympic goal was huge to get Canada going.
MT: ꯁꯤꯗꯅꯤ ꯀꯁꯕꯤꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯁꯦꯂꯦꯕꯅꯤꯒꯤ ꯑꯍꯥꯟꯕꯥ ꯑꯣꯂꯤꯝꯄꯤꯛ ꯒꯣꯜ ꯑꯁꯤꯅ ꯀꯅꯥꯗꯥꯕꯨ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯍꯟꯕꯥ
--------------------------------------------------

Translating:  32%|████████▊                  | 325/1000 [05:27<12:45,  1.13s/it]

[325/1000]
EN: Jon Cooper said Macklin Celebrini plays the game well beyond his years.
MT: ꯖꯣꯟ ꯀꯨꯄꯔꯅꯥ ꯍꯥꯏꯔꯝꯃꯤ ꯃꯗꯨꯗꯤ ꯃꯦꯀꯂꯤꯟ ꯁꯦꯂꯦꯕꯅꯤꯅꯥ ꯃꯍꯥꯛꯀꯤ ꯆꯍꯤ ꯀꯌꯥꯒꯤ ꯃꯊꯛꯇꯁꯨ ꯒꯦꯝ ꯑꯗꯨ ꯐꯖꯅ ꯁꯥꯟꯅꯩ ꯫
--------------------------------------------------

Translating:  33%|████████▊                  | 326/1000 [05:28<12:09,  1.08s/it]

[326/1000]
EN: Canada planned to face Switzerland at the Milano Arena the next day.
MT: ꯀꯅꯥꯗꯥꯅꯥ ꯃꯊꯪꯒꯤ ꯅꯨꯃꯤꯠꯇ ꯃꯤꯂꯥꯅꯣ ꯑꯦꯔꯤꯅꯥꯗꯥꯏꯠꯖꯔꯂꯦꯟꯗꯀ ꯃꯥꯌꯣꯛꯅꯅꯕ ꯊꯧꯔꯥꯡ ꯇꯧ
--------------------------------------------------

Translating:  33%|████████▊                  | 327/1000 [05:30<13:01,  1.16s/it]

[327/1000]
EN: Choi Ga-on won women’s snowboard halfpipe gold after recovering from a first-run crash.
MT: ꯆꯣꯏ ꯒꯥ-ꯣꯟꯅꯥ ꯅꯨꯄꯤꯁꯤꯡꯒꯤꯣꯟꯕꯣꯔ ꯭ ꯗ ꯍꯥꯐꯄꯄꯤꯄ ꯒꯣꯜꯗ ꯑꯁꯤ ꯐꯔꯁꯠ-ꯔꯟ ꯀꯁ ꯑꯃꯗꯒꯤ ꯐꯒꯠꯂꯛꯄꯒꯤ ꯃꯇꯨꯡꯗ ꯃꯥꯏꯄꯥꯛ
--------------------------------------------------

Translating:  33%|████████▊                  | 328/1000 [05:31<12:25,  1.11s/it]

[328/1000]
EN: Chloe Kim took silver and Mitsuki Ono won bronze in the halfpipe event.
MT: ꯍꯥꯐꯄꯤꯄ ꯏꯚꯦꯟꯇꯗꯥꯂꯣ ꯀꯤꯝꯅ ꯂꯨꯄꯥ ꯑꯃꯁꯨꯡ ꯃꯤꯠꯁꯨꯀꯤ ꯑꯣꯅꯣꯅꯥꯣꯟꯖ ꯂꯧ
--------------------------------------------------

Translating:  33%|████████▉                  | 329/1000 [05:32<13:02,  1.17s/it]

[329/1000]
EN: Choi Ga-on scored 90.25 to beat Chloe Kim’s leading 88 score.
MT: ꯆꯣꯏ ꯒꯥ-ꯣꯟꯅꯥ 25 ꯁꯀꯣꯔ ꯂꯧꯗꯨꯅ ꯆꯣꯂꯤ ꯀꯤꯝꯒꯤ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯔꯤꯕ 88ꯕꯨ ꯃꯥꯏꯊꯤꯕ ꯄꯤ
--------------------------------------------------

Translating:  33%|████████▉                  | 330/1000 [05:33<12:37,  1.13s/it]

[330/1000]
EN: Arsenal reached the League Cup final after Kai Havertz secured a 1-0 win.
MT: ꯀꯥꯏ ꯍꯥꯚꯔꯇꯖꯅ 1- ꯒꯤ ꯃꯥꯏꯄꯥꯛꯄ ꯑꯃ ꯐꯪꯂꯕ ꯃꯇꯨꯡꯗ ꯑꯥꯔꯁꯅꯦꯜꯅꯥ ꯂꯤꯒ ꯀꯞꯀꯤ ꯐꯥꯏꯅꯦꯜꯗ ꯌꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  33%|████████▉                  | 331/1000 [05:34<13:00,  1.17s/it]

[331/1000]
EN: Kai Havertz came off the bench to finish Arsenal’s 4-2 aggregate semi-final victory.
MT: ꯀꯥꯏ ꯍꯥꯚꯔꯇꯖꯅ ꯑꯥꯔꯁꯦꯅꯦꯜꯒꯤ- ꯒꯤ ꯑꯄꯨꯟꯕ ꯁꯦꯃꯤ-ꯐꯥꯏꯅꯦꯜ ꯃꯥꯏ ꯄꯥꯛꯄ ꯑꯗꯨ ꯂꯣꯏꯁꯤꯟꯅꯕ ꯕꯦꯆꯇꯒꯤ ꯂꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  33%|████████▉                  | 332/1000 [05:35<13:12,  1.19s/it]

[332/1000]
EN: Arsenal will face Manchester City or Newcastle at Wembley on March 22.
MT: ꯃꯥꯔꯗꯥ ꯋꯦꯝꯕꯦꯂꯤꯗꯥ ꯑꯔꯁꯦꯟꯜꯅꯥ ꯃꯥꯟꯆꯦꯁꯇꯔ ꯁꯤꯇꯤ ꯅꯠꯇꯒꯥ ꯅꯀꯁꯦꯜꯒꯥ ꯃꯥꯌꯣꯛꯅꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  33%|████████▉                  | 333/1000 [05:36<12:39,  1.14s/it]

[333/1000]
EN: Manchester City held a 2-0 lead over Newcastle ahead of the second leg.
MT: ꯃꯥꯟꯆꯦꯁꯇꯔ ꯁꯤꯇꯤꯅꯥ ꯑꯅꯤꯁꯨꯕ ꯂꯦꯒꯀꯤ ꯃꯃꯥꯡꯗ ꯅꯀꯁꯦꯜꯒꯤ ꯃꯊꯛꯇ- ꯒꯤ ꯂꯨꯆꯤꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  33%|█████████                  | 334/1000 [05:37<11:42,  1.05s/it]

[334/1000]
EN: Arsenal have not won the League Cup since 1993, according to the report.
MT: ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯏꯪ 1993ꯗꯒꯤ ꯍꯧꯅ ꯑꯥꯔꯁꯅꯦꯜꯅꯥ ꯂꯤꯒ ꯀꯞꯇ ꯃꯥꯏ ꯄꯥꯛꯄ ꯉꯝ
--------------------------------------------------

Translating:  34%|█████████                  | 335/1000 [05:39<13:11,  1.19s/it]

[335/1000]
EN: The Football Association of Ireland confirmed Ireland will fulfil Nations League fixtures against Israel.
MT: ꯑꯥꯌꯔꯂꯦꯟꯗꯒꯤ ꯐꯨꯇꯕꯣꯜ ꯑꯦꯁꯣꯁꯤꯑꯦꯁꯟꯅꯥ ꯑꯥꯏꯌꯔꯂꯦꯟꯗꯅꯥ ꯏꯖꯔꯥꯦꯜꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯅꯦꯁꯟꯁ ꯂꯤꯒꯀꯤ ꯐꯤꯛꯆꯔꯁꯤꯡ ꯃꯄꯨꯡ ꯐꯥꯍꯟꯒꯅꯤ ꯍꯥꯏꯅ ꯀꯟꯐꯥꯔꯝ ꯇꯧ
--------------------------------------------------

Translating:  34%|█████████                  | 336/1000 [05:40<12:46,  1.15s/it]

[336/1000]
EN: Ireland and Israel were drawn with Austria and Kosovo in Nations League League B.
MT: ꯑꯥꯏꯔꯂꯦꯟꯗ ꯑꯃꯁꯨꯡ ꯏꯖꯔꯥꯦꯜ ꯑꯁꯤ ꯑꯣꯁꯇꯌꯥ ꯑꯃꯁꯨꯡ ꯀꯣꯁꯣꯚꯣꯒꯥ ꯂꯣꯏꯅꯅꯥ ꯅꯦꯁꯟꯁ ꯂꯤꯒ ꯕꯤꯗꯥ ꯗ ꯇꯧ
--------------------------------------------------

Translating:  34%|█████████                  | 337/1000 [05:41<11:42,  1.06s/it]

[337/1000]
EN: Ireland must play Israel home and away between September and November.
MT: ꯁꯦꯞꯇꯦꯝꯕꯔ ꯑꯃꯁꯨꯡ ꯅꯕꯦꯝꯕꯔꯒꯤ ꯃꯔꯛꯇ ꯑꯥꯏꯔꯂꯦꯟꯗꯅꯥ ꯏꯖꯔꯥꯦꯜꯒ ꯌꯨꯝ ꯑꯃꯁꯨꯡ ꯃꯄꯥꯟꯗ ꯁꯥꯟꯅꯒꯗꯕꯅꯤ ꯫
--------------------------------------------------

Translating:  34%|█████████▏                 | 338/1000 [05:42<13:10,  1.19s/it]

[338/1000]
EN: The FAI warned refusal could mean forfeiture and possible disqualification under UEFA regulations.
MT: ꯑꯦꯐꯑꯦꯑꯥꯏꯅꯥ ꯌꯥꯗꯕꯒꯤ ꯑꯔꯊꯗꯤ ꯌꯨꯑꯏꯐꯦꯑꯦ ꯔꯦꯒꯨꯂꯦꯁꯟꯁꯤꯡꯒꯤ ꯃꯈꯥꯗ ꯂꯧꯊꯣꯛꯄ ꯑꯃꯁꯨꯡ ꯑꯣꯏꯊꯣꯛꯄ ꯌꯥꯕ ꯗꯤꯀꯂꯤꯚꯤꯐꯤꯀꯦꯁꯟ ꯍꯥꯏꯕꯅꯤ ꯍꯥꯏꯅ ꯆꯦꯛꯁꯤꯟꯋꯥ ꯄꯤ
--------------------------------------------------

Translating:  34%|█████████▏                 | 339/1000 [05:43<13:08,  1.19s/it]

[339/1000]
EN: The FAI said it requested Israel’s UEFA ban in November after an internal vote.
MT: ꯑꯦꯟꯇꯔꯅꯦꯜ ꯚꯣꯠ ꯑꯃꯒꯤ ꯃꯇꯨꯡꯗ ꯅꯕꯦꯝꯕꯔꯗꯥ ꯑꯦꯐꯑꯦꯑꯥꯏꯅꯥ ꯏꯖꯔꯥꯦꯜꯒꯤ ꯌꯨꯑꯐꯑꯦꯕꯨ ꯊꯤꯡꯅꯕ ꯍꯥꯏꯖꯈꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  34%|█████████▏                 | 340/1000 [05:45<14:52,  1.35s/it]

[340/1000]
EN: Novak Djokovic beat Jannik Sinner 3-6, 6-3, 4-6, 6-4, 6-4 in Melbourne.
MT: ꯃꯦꯜꯕꯣꯔꯟꯗ ꯅꯣꯚꯥꯀ ꯖꯣꯀꯣꯚꯤꯛꯅ ꯖꯅꯤꯛ ꯁꯤꯟꯅꯔꯕꯨ 3-6,6-, 4- 6, 6-4,-4 ꯗ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  34%|█████████▏                 | 341/1000 [05:47<15:10,  1.38s/it]

[341/1000]
EN: Novak Djokovic’s win over Jannik Sinner set up an Australian Open final against Carlos Alcaraz.
MT: ꯅꯣꯕꯥꯛ ꯖꯣꯀꯣꯚꯤꯀꯅ ꯖꯅꯤꯛ ꯁꯤꯟꯅꯔꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯑꯁꯤꯅ ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯒꯤ ꯃꯥꯏꯄꯥꯛꯗꯥ ꯑꯣꯁꯇꯂꯤꯌꯥ ꯑꯣꯄꯟ ꯐꯥꯏꯅꯦꯜ ꯑꯃ ꯁꯦꯝ
--------------------------------------------------

Translating:  34%|█████████▏                 | 342/1000 [05:48<15:51,  1.45s/it]

[342/1000]
EN: Novak Djokovic reached his 11th Australian Open final after ending four straight semi-final exits.
MT: ꯅꯣꯕꯥꯛ ꯖꯣꯀꯣꯚꯤꯀꯅ ꯁꯦꯃꯤ-ꯐꯥꯏꯅꯦꯜꯗꯒꯤ ꯃꯊꯪ-ꯃꯇꯥ ꯂꯣꯏꯁꯤꯜꯂꯛꯄꯒꯤ ꯃꯇꯨꯡꯗ ꯃꯍꯥꯛꯀꯤ 11 ꯁꯨꯕ ꯑꯣꯁꯇꯂꯤꯌꯟ ꯑꯣꯄꯟ ꯐꯥꯏꯅꯦꯜꯗ ꯌꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  34%|█████████▎                 | 343/1000 [05:49<14:58,  1.37s/it]

[343/1000]
EN: Carlos Alcaraz reached his first Melbourne Park title match, the report said.
MT: ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯃꯍꯥꯛꯀꯤ ꯑꯍꯥꯟꯕꯥ ꯃꯦꯜꯕꯣꯔꯟ ꯄꯥꯔꯛ ꯇꯥꯏꯇꯥꯜ ꯃꯦꯆꯇ ꯌꯧꯈꯤ ꯍꯥꯏꯅ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯗ ꯍꯥꯏ
--------------------------------------------------

Translating:  34%|█████████▎                 | 344/1000 [05:50<14:19,  1.31s/it]

[344/1000]
EN: Lorenzo Musetti retired mid-match after suffering a suspected upper leg tear.
MT: ꯂꯣꯔꯣꯟꯖꯣ ꯃꯨꯁꯦꯇꯤꯅ ꯑꯞꯄꯔ ꯂꯦꯒ ꯇꯤꯌꯔꯅꯤ ꯍꯥꯏꯅ ꯆꯤꯡꯅꯕꯗꯒꯤ ꯃꯦꯆꯀꯤ ꯃꯌꯥꯏꯗꯥ ꯔꯤꯇꯤꯑꯥꯔ ꯇꯧ
--------------------------------------------------

Translating:  34%|█████████▎                 | 345/1000 [05:52<13:34,  1.24s/it]

[345/1000]
EN: Lorenzo Musetti withdrew after winning the first two sets against Novak Djokovic.
MT: ꯂꯣꯔꯦꯟꯖꯣ ꯃꯨꯁꯦꯇꯤꯅ ꯅꯣꯚꯥꯀ ꯖꯣꯀꯣꯚꯤꯀꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯑꯍꯥꯟꯕ ꯁꯦꯇ ꯑꯅꯤ ꯃꯥꯏ ꯄꯥꯛꯂꯕ ꯃꯇꯨꯡꯗ ꯂꯧꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  35%|█████████▎                 | 346/1000 [05:53<14:43,  1.35s/it]

[346/1000]
EN: Alexander Zverev rallied from losing the first set to beat Gabriel Diallo in four sets.
MT: ꯑꯂꯦꯛꯖꯦꯟꯗꯔ ꯖꯚꯦꯔꯦꯚꯅꯥ ꯑꯍꯥꯟꯕ ꯁꯦꯇ ꯑꯗꯨ ꯃꯥꯏꯊꯤꯕꯥꯗꯒꯤ ꯔꯦꯂꯤ ꯇꯧꯔꯗꯨꯅ ꯒꯕꯦꯔꯤꯌꯦꯜ ꯗꯤꯌꯥꯂꯣꯕꯨ ꯁꯦꯠ ꯃꯔꯤꯗꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  35%|█████████▎                 | 347/1000 [05:55<15:30,  1.43s/it]

[347/1000]
EN: Alexander Zverev won 6-7(1), 6-1, 6-4, 6-2 against Gabriel Diallo at Rod Laver Arena.
MT: ꯑꯂꯦꯛꯖꯦꯟꯗꯔ ꯖꯚꯦꯔꯦꯚꯅꯥ ꯔꯣꯗ ꯂꯦꯕꯔ ꯑꯦꯔꯤꯅꯥꯗꯥ ꯒꯕꯦꯔꯤꯌꯦꯜ ꯗꯤꯌꯥꯂꯣꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ-,./% ꯑꯃꯁꯨꯡ-2 ꯂꯧ
--------------------------------------------------

Translating:  35%|█████████▍                 | 348/1000 [05:56<14:15,  1.31s/it]

[348/1000]
EN: An Australian Open report noted fans were unhappy about long queues and a ticket sales halt.
MT: ꯑꯣꯁꯇꯂꯤꯌꯥꯟ ꯑꯣꯄꯟ ꯔꯤꯄꯣꯔꯇ ꯑꯃꯗ ꯐꯦꯟꯁꯤꯡꯅ ꯑꯁꯥꯡꯕ ꯄꯔꯤꯡꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯇꯤꯀꯦꯠ ꯌꯣꯟꯕ ꯂꯦꯞꯈꯤꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯅꯨꯡꯉꯥꯏꯈꯤꯗꯦ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  35%|█████████▍                 | 349/1000 [05:57<13:41,  1.26s/it]

[349/1000]
EN: A Hindustan Times column said tennis needs rivalries to elevate players and the sport.
MT: ꯍꯤꯟꯗꯨꯁꯇꯥꯟ ꯇꯥꯏꯃꯁꯀꯤ ꯀꯣꯂꯝ ꯑꯃꯗ ꯇꯦꯅꯤꯁꯅꯥ ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡ ꯑꯃꯁꯨꯡꯄꯣꯔꯇꯄꯨ ꯆꯥꯎꯈꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯌꯦꯛꯅꯕ ꯃꯊꯧ ꯇꯥꯏ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  35%|█████████▍                 | 350/1000 [05:58<13:38,  1.26s/it]

[350/1000]
EN: A Hindustan Times column said Jannik Sinner and Carlos Alcaraz are improving every year.
MT: ꯍꯤꯟꯗꯨꯁꯇꯥꯟ ꯇꯥꯏꯃꯁꯀꯤ ꯀꯣꯂꯝ ꯑꯃꯗ ꯖꯅꯤꯛ ꯁꯤꯟꯅꯔ ꯑꯃꯁꯨꯡ ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖ ꯑꯁꯤ ꯆꯍꯤ ꯈꯨꯗꯤꯡꯒꯤ ꯐꯒꯠꯂꯛꯂꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  35%|█████████▍                 | 351/1000 [05:59<12:49,  1.18s/it]

[351/1000]
EN: The same column said Sinner and Alcaraz already play at a level above most players.
MT: ꯁꯤꯟꯅꯔ ꯑꯃꯁꯨꯡ ꯑꯜꯀꯥꯔꯖ ꯑꯁꯤ ꯍꯥꯟꯅꯅꯥ ꯁꯥꯟꯅꯔꯣꯏ ꯑꯌꯥꯝꯕꯒꯤ ꯃꯊꯛꯇ ꯂꯩꯕ ꯊꯥꯛꯇꯥ ꯁꯥꯟꯅ ꯍꯥꯏꯅ ꯆꯞ ꯃꯥꯟꯅꯕ ꯀꯣꯂꯝꯗꯥ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  35%|█████████▌                 | 352/1000 [06:01<13:40,  1.27s/it]

[352/1000]
EN: The column said Federer, Nadal and Djokovic gave men’s tennis a tribal feel for two decades.
MT: ꯀꯣꯂꯝ ꯑꯁꯤꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯐꯦꯗꯔꯔ, ꯅꯥꯗꯥꯜ ꯑꯃꯁꯨꯡ ꯖꯣꯀꯣꯚꯤꯀꯅꯥ ꯅꯨꯄꯥꯒꯤ ꯇꯦꯅꯤꯁ ꯑꯁꯤ ꯆꯍꯤ ꯇꯔꯥꯒꯤ ꯈꯨꯖꯤꯡ ꯑꯅꯤꯗꯒꯤ ꯇꯥꯏꯕꯦꯜꯒꯤ ꯃꯒꯨꯟ ꯑꯃ ꯄꯤ
--------------------------------------------------

Translating:  35%|█████████▌                 | 353/1000 [06:02<13:26,  1.25s/it]

[353/1000]
EN: A report said Alexander Zverev began a bid for a maiden Australian Open title.
MT: ꯔꯤꯄꯣꯔꯇ ꯑꯃꯥꯅꯥ ꯍꯥꯏ ꯃꯗꯨꯗꯤ ꯑꯂꯦꯛꯖꯦꯟꯗꯔ ꯖꯚꯦꯔꯦꯚꯅꯥ ꯑꯍꯥꯟꯕ ꯑꯣꯁꯇꯂꯤꯌꯥ ꯑꯣꯄꯟ ꯇꯥꯏꯇꯥꯜ ꯑꯃꯥ ꯐꯪꯅꯕꯒꯤ ꯕꯤꯗ ꯑꯃ ꯍꯧ
--------------------------------------------------

Translating:  35%|█████████▌                 | 354/1000 [06:03<14:09,  1.31s/it]

[354/1000]
EN: Carlos Alcaraz defeated Alexander Zverev 6-3, 3-6, 6-1, 6-2 at the Australian Open.
MT: ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯑꯂꯦꯛꯖꯦꯟꯗꯔ ꯖꯚꯦꯔꯦꯚꯄꯨ ꯑꯣꯁꯇꯂꯤꯌꯥ ꯑꯣꯄꯟꯗꯥ 6-, 3 - 6,6-1, ꯗ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▌                 | 355/1000 [06:04<13:10,  1.23s/it]

[355/1000]
EN: Carlos Alcaraz won in two hours and 26 minutes, according to the match report.
MT: ꯃꯦꯆ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯄꯨꯡ ꯑꯅꯤ ꯑꯃꯁꯨꯡ ꯃꯤꯅꯤꯠ 26 ꯗꯥ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▌                 | 356/1000 [06:06<13:00,  1.21s/it]

[356/1000]
EN: The same report said Zverev received a time-violation warning during the match.
MT: ꯆꯞ ꯃꯥꯟꯅꯕ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯗ ꯖꯚꯦꯔꯦꯚꯅꯥ ꯃꯦꯆ ꯑꯗꯨꯒꯤ ꯃꯅꯨꯡꯗ ꯇꯥꯏꯃ-ꯚꯤꯑꯣꯂꯦꯁꯟ ꯋꯥꯔꯅꯤꯡ ꯑꯃ ꯐꯪꯈꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▋                 | 357/1000 [06:06<11:51,  1.11s/it]

[357/1000]
EN: The report said Alcaraz requested a meeting with the supervisor after the time warning.
MT: ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯗ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯃꯇꯝ ꯑꯗꯨꯒꯤ ꯆꯦꯛꯁꯤꯟꯋꯥ ꯄꯤꯔꯕ ꯃꯇꯨꯡꯗ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯁꯨꯚꯥꯏꯖꯔꯒꯥ ꯎꯅꯅꯕ ꯍꯥꯏꯖꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▋                 | 358/1000 [06:07<11:06,  1.04s/it]

[358/1000]
EN: The report said Alcaraz complained about the length of Zverev’s breaks between points.
MT: ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯗ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯖꯚꯦꯔꯦꯚꯒꯤ ꯄꯣꯏꯟꯇꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯂꯩꯕ ꯕꯦꯛꯁꯤꯡꯒꯤ ꯑꯁꯥꯡꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯋꯥꯀꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▋                 | 359/1000 [06:08<10:39,  1.00it/s]

[359/1000]
EN: Carlos Alcaraz said he also wanted to know the limit for the time between points.
MT: ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯃꯍꯥꯛꯅ ꯄꯣꯏꯟꯇꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯂꯩꯕ ꯃꯇꯝ ꯑꯗꯨꯒꯤ ꯂꯤꯃꯤꯇ ꯑꯗꯨꯁꯨ ꯈꯪꯕ ꯄꯥꯝꯃꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▋                 | 360/1000 [06:09<10:30,  1.01it/s]

[360/1000]
EN: R Praggnanandhaa sealed a 2026 Candidates berth by winning the FIDE Circuit 2025.
MT: ꯑꯥꯔꯒꯅꯅꯥꯟꯙꯥꯅꯥ ꯐꯤꯗꯦ ꯁꯔꯀꯏꯇ 2025 ꯃꯥꯏ ꯄꯥꯛꯂꯗꯨꯅ ꯀꯦꯟꯗꯤꯗꯦꯠꯁ ꯕꯦꯔꯊ 2026 ꯑꯃ ꯁꯤꯜ ꯇꯧ
--------------------------------------------------

Translating:  36%|█████████▋                 | 361/1000 [06:10<10:29,  1.01it/s]

[361/1000]
EN: The Candidates Tournament will determine the challenger to world champion D Gukesh.
MT: ꯀꯦꯟꯗꯤꯇꯦꯁ ꯇꯨꯔꯅꯥꯃꯦꯟꯇꯅꯥ ꯋꯜꯗ ꯆꯦꯝꯄꯌꯟ ꯗꯤ ꯒꯨꯀꯦꯁꯇꯥ ꯆꯂꯦꯟꯖꯔ ꯑꯗꯨ ꯂꯦꯞꯀꯅꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▊                 | 362/1000 [06:11<09:56,  1.07it/s]

[362/1000]
EN: R Praggnanandhaa overtook Ding Liren in May to lead the FIDE Circuit race.
MT: ꯑꯥꯔꯒꯅꯅꯥꯟꯗꯅꯥ ꯃꯦꯗꯥ ꯐꯤꯗꯦ ꯁꯔꯀꯏꯇ ꯂꯝꯖꯦꯜ ꯂꯨꯆꯤꯡꯕꯥ ꯗꯤꯡ ꯂꯤꯔꯦꯟꯕꯨ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▊                 | 363/1000 [06:12<09:50,  1.08it/s]

[363/1000]
EN: Praggnanandhaa thanked supporters on X after earning a place in the 2026 Candidates.
MT: ꯄꯒꯅꯅꯥꯟꯙꯥꯅꯥ ꯏꯪꯁꯣꯛ 2026 ꯒꯤ ꯀꯦꯟꯗꯤꯇꯦꯗꯗꯥ ꯃꯐꯝ ꯑꯃ ꯐꯪꯂꯕ ꯃꯇꯨꯡꯗ ꯑꯦꯛꯁꯇ ꯁꯧꯒꯠꯄꯁꯤꯡꯕꯨ ꯊꯥꯒꯠꯄ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▊                 | 364/1000 [06:13<10:12,  1.04it/s]

[364/1000]
EN: A report said only Nodirbek Abdusattorov had a theoretical chance to catch Praggnanandhaa.
MT: ꯔꯤꯄꯣꯔꯇ ꯑꯃꯥꯅꯥ ꯍꯥꯏꯔꯝꯃꯤ ꯃꯗꯨꯗꯤ ꯅꯣꯗꯤꯔꯕꯦꯛ ꯑꯕꯗꯨꯁꯥꯠꯇꯣꯔꯣꯚ ꯈꯛꯇꯅꯥꯒꯅꯅꯥꯟꯙꯥ ꯐꯥꯕꯒꯤ ꯊꯤꯑꯣꯔꯦꯇꯤꯀꯦꯜ ꯑꯣꯏꯕ ꯇꯥꯟꯖꯥ ꯑꯃ ꯂꯩꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▊                 | 365/1000 [06:14<09:52,  1.07it/s]

[365/1000]
EN: D Gukesh withdrew from Tata Steel Chess India Rapid and Blitz for personal reasons.
MT: ꯗꯤ ꯒꯨꯀꯦꯁꯅ ꯇꯥꯇꯥꯇꯦꯜ ꯆꯦꯁ ꯏꯟꯗꯤꯌꯥ ꯔꯦꯄꯤꯗ ꯑꯃꯁꯨꯡ ꯕꯂꯤꯇꯖꯗꯒꯤ ꯂꯅꯥꯏꯒꯤ ꯑꯣꯏꯕ ꯃꯔꯝꯁꯤꯡ ꯂꯩꯔꯗꯨꯅ ꯂꯧꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  37%|█████████▉                 | 366/1000 [06:15<09:34,  1.10it/s]

[366/1000]
EN: Tata Steel Chess India Rapid and Blitz was scheduled in Kolkata from January 7 to 11.
MT: ꯇꯥꯇꯥꯇꯤꯜ ꯆꯦꯁ ꯏꯟꯗꯤꯌꯥ ꯔꯦꯄꯤꯗ ꯑꯃꯁꯨꯡ ꯕꯂꯤꯇꯖ ꯑꯁꯤ ꯀꯣꯜꯀꯥꯇꯥꯗꯥ ꯖꯅꯨꯋꯥꯔꯤ ꯗꯒꯤ ꯐꯥꯎꯕ ꯄꯥꯡꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  37%|█████████▉                 | 367/1000 [06:15<09:04,  1.16it/s]

[367/1000]
EN: Nihal Sarin replaced D Gukesh in the Tata Steel Chess India event.
MT: ꯅꯤꯍꯥꯜ ꯁꯥꯔꯤꯟꯅꯥ ꯇꯥꯇꯥꯇꯦꯜ ꯆꯦꯁ ꯏꯟꯗꯤꯌꯥ ꯏꯚꯦꯟꯇꯗꯥ ꯗꯤ ꯒꯨꯀꯦꯁꯀꯤ ꯃꯐꯝ ꯂꯧ
--------------------------------------------------

Translating:  37%|█████████▉                 | 368/1000 [06:16<09:24,  1.12it/s]

[368/1000]
EN: Dibyendu Barua called D Gukesh’s withdrawal a big setback for organisers and fans.
MT: ꯗꯤꯕꯌꯦꯟꯗꯨ ꯕꯔꯨꯋꯥꯅꯥ ꯗꯤ ꯒꯨꯀꯦꯁꯀꯤ ꯂꯧꯊꯣꯛꯄꯥ ꯑꯁꯤ ꯑꯣꯔꯖꯦꯟꯖꯔꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯐꯦꯟꯁꯤꯡꯒꯤ ꯑꯆꯧꯕ ꯃꯥꯏꯊꯤꯅꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  37%|█████████▉                 | 369/1000 [06:17<09:14,  1.14it/s]

[369/1000]
EN: Viswanathan Anand returned to play Tata Steel Chess India after six years away.
MT: ꯕꯤꯁꯋꯥꯅꯥꯊꯅ ꯑꯥꯅꯟꯗꯅꯥ ꯆꯍꯤ ꯇꯥꯔꯨꯛꯀꯤ ꯃꯇꯨꯡꯗ ꯇꯥꯇꯥꯇꯦꯜ ꯆꯦꯁ ꯏꯟꯗꯤꯌꯥ ꯁꯥꯟꯅꯅꯕ ꯍꯜꯂꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  37%|█████████▉                 | 370/1000 [06:18<09:23,  1.12it/s]

[370/1000]
EN: Viswanathan Anand said “It was exhausting not playing” while explaining his return.
MT: ꯕꯤꯁꯋꯥꯅꯥꯊꯅ ꯑꯥꯅꯟꯅ ꯍꯥꯏꯈꯤ  " ꯃꯍꯥꯛꯀꯤ ꯍꯜꯂꯛꯄꯒꯤ ꯃꯇꯥꯡꯗ ꯁꯟꯗꯣꯛꯅ ꯇꯥꯛꯂꯗꯨꯅ, ꯁꯥꯟꯅꯗꯕꯁꯤ ꯑꯋꯥꯕꯅꯤ ꯫
--------------------------------------------------

Translating:  37%|██████████                 | 371/1000 [06:19<09:21,  1.12it/s]

[371/1000]
EN: Viswanathan Anand was set to open against Wesley So in the seventh edition.
MT: ꯕꯤꯁꯋꯥꯅꯥꯊꯅ ꯑꯥꯅꯟꯅꯥ ꯋꯦꯁꯂꯤ ꯁꯣꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ 7 ꯁꯨꯕꯥ ꯑꯦꯗꯤꯁꯟꯗꯥ ꯑꯣꯄꯟ ꯇꯧꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯦꯞ
--------------------------------------------------

Translating:  37%|██████████                 | 372/1000 [06:20<08:49,  1.18it/s]

[372/1000]
EN: The tournament director said Tata Steel Chess India will be held in January going forward.
MT: ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯗꯤꯔꯦꯛꯇꯔꯅꯥ ꯍꯥꯏ ꯃꯗꯨꯗꯤ ꯇꯥꯇꯥꯇꯦꯜ ꯆꯦꯁ ꯏꯟꯗꯤꯌꯥ ꯑꯁꯤ ꯃꯈꯥ ꯇꯥꯅ ꯖꯅꯨꯋꯥꯔꯤꯗꯥ ꯄꯥꯡꯊꯣꯛꯀꯅꯤ ꯫
--------------------------------------------------

Translating:  37%|██████████                 | 373/1000 [06:21<10:01,  1.04it/s]

[373/1000]
EN: The Tata Steel Chess India event offered equal prize purses of $41,500 in open and women’s.
MT: ꯇꯥꯇꯥꯇꯦꯜ ꯆꯦꯁ ꯏꯟꯗꯤꯌꯥ ꯏꯚꯦꯟꯇꯅꯥ ꯑꯣꯄꯟ ꯑꯃꯁꯨꯡ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯗꯣꯜꯂꯔ 41,500ꯒꯤ ꯃꯥꯟꯅꯕ ꯄꯔꯁꯁꯤꯡ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  37%|██████████                 | 374/1000 [06:22<10:31,  1.01s/it]

[374/1000]
EN: Viswanathan Anand backed the Total Chess World Championship Tour approved by FIDE.
MT: ꯐꯤꯗꯦꯅꯥ ꯑꯌꯥꯕ ꯄꯤꯔꯕꯥ ꯇꯣꯇꯥꯜ ꯆꯦꯁ ꯋꯥꯔꯜꯗ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯞ ꯇꯨꯔ ꯑꯁꯤ ꯕꯤꯁꯋꯥꯅꯥꯊꯅ ꯑꯥꯅꯟꯅ ꯁꯧꯒꯠ
--------------------------------------------------

Translating:  38%|██████████▏                | 375/1000 [06:23<11:21,  1.09s/it]

[375/1000]
EN: The Total Chess World Championship Tour will crown a new “FIDE World Combined” champion.
MT: ꯇꯣꯇꯥꯜ ꯆꯦꯁ ꯋꯥꯔꯜꯗ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯞ ꯇꯨꯔꯅꯥ ꯑꯅꯧꯕ ꯐꯤꯗꯦ ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯝꯕꯥꯏꯟꯗ ꯀꯝꯃꯤꯄꯌꯥꯟ ꯑꯃ ꯑꯣꯏꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▏                | 376/1000 [06:24<10:37,  1.02s/it]

[376/1000]
EN: The tour will be held across fast classic, rapid and blitz formats.
MT: ꯇꯨꯔ ꯑꯁꯤ ꯐꯥꯁꯀꯥꯁꯤꯛ, ꯔꯦꯄꯤꯗ ꯑꯃꯁꯨꯡ ꯕꯂꯤꯇꯖ ꯐꯣꯔꯃꯦꯇꯁꯤꯡꯗ ꯄꯥꯡꯊꯣꯛꯀꯅꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▏                | 377/1000 [06:25<09:51,  1.05it/s]

[377/1000]
EN: Anand said Norway Chess has a serious long-term proposal for the new tour.
MT: ꯑꯥꯅꯟꯅ ꯍꯥꯏ ꯃꯗꯨꯗꯤ ꯅꯣꯔꯋꯦ ꯆꯦꯁꯅꯥ ꯑꯅꯧꯕ ꯇꯨꯔ ꯑꯁꯤꯒꯤꯗꯃꯛ ꯌꯥꯝꯅ ꯂꯨꯕꯥ ꯃꯇꯝ ꯆꯨꯞꯄꯒꯤ ꯋꯥꯐꯝ ꯑꯃ ꯊꯝ
--------------------------------------------------

Translating:  38%|██████████▏                | 378/1000 [06:26<09:11,  1.13it/s]

[378/1000]
EN: Anand said the sport benefits when Magnus Carlsen competes in major events.
MT: ꯑꯥꯅꯟꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯃꯦꯒꯅꯁ ꯀꯥꯔꯂꯁꯦꯟꯅꯥ ꯑꯆꯧꯕ ꯊꯧꯔꯝꯁꯤꯡꯗ ꯁꯔꯨꯛ ꯌꯥꯔꯕꯥ ꯃꯇꯝꯗꯄꯣꯔꯇ ꯑꯁꯤꯅ ꯀꯥꯟꯅꯕ ꯐꯪꯉꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▏                | 379/1000 [06:27<09:07,  1.13it/s]

[379/1000]
EN: Wesley So said he proposed a draw against Praggnanandhaa, not the arbiters.
MT: ꯋꯦꯁꯂꯤ ꯁꯣꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯃꯍꯥꯛꯅ ꯑꯔꯕꯤꯇꯔꯁꯤꯡ ꯅꯠꯇꯅꯥꯒꯥ ꯄꯒꯅꯅꯥꯟꯙꯥꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯗꯀꯤ ꯋꯥꯐꯝ ꯊꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▎                | 380/1000 [06:27<08:59,  1.15it/s]

[380/1000]
EN: Praggnanandhaa had one second left before stopping the clock to call the arbiter.
MT: ꯋꯥꯔꯣꯏꯁꯤꯟꯂꯣꯏ ꯑꯗꯨꯕꯨ ꯐꯣꯟ ꯇꯧꯅꯕ ꯄꯨꯡ ꯑꯗꯨ ꯂꯦꯞꯇꯉꯩꯗꯒꯅꯅꯥꯟꯙꯥꯗꯥ ꯁꯦꯀꯦꯟꯗ ꯑꯃ ꯂꯩꯔꯝ
--------------------------------------------------

Translating:  38%|██████████▎                | 381/1000 [06:28<09:23,  1.10it/s]

[381/1000]
EN: Nihal Sarin won the 2026 Tata Steel Chess India Rapid Tournament in Kolkata.
MT: ꯅꯤꯍꯥꯜ ꯁꯥꯔꯤꯟꯅ ꯀꯣꯜꯀꯥꯇꯥꯗꯥ ꯄꯥꯡꯊꯣꯛꯂꯤꯕꯥ ꯇꯥꯇꯥꯇꯦꯜ ꯆꯦꯁ ꯏꯟꯗꯤꯌꯥ ꯔꯦꯄꯤꯗ ꯇꯨꯔꯅꯥꯃꯦꯟꯇ 2026 ꯑꯗꯨ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▎                | 382/1000 [06:30<09:41,  1.06it/s]

[382/1000]
EN: Ian Nepomniachtchi criticised hotel conditions during the 2025 Chess World Cup in Goa.
MT: ꯏꯌꯥꯟ ꯅꯦꯄꯣꯃꯅꯤꯌꯥꯆꯇꯆꯤꯅꯥ ꯒꯣꯋꯥꯗꯥ ꯄꯥꯡꯊꯣꯛꯂꯤꯕꯥ ꯏꯪꯁꯣꯛ 2025ꯒꯤ ꯆꯦꯁ ꯋꯥꯔꯂꯗ ꯀꯞꯀꯤ ꯃꯇꯝꯗ ꯍꯣꯇꯦꯜꯒꯤ ꯐꯤꯚꯝꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯈꯟꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▎                | 383/1000 [06:30<09:29,  1.08it/s]

[383/1000]
EN: Ian Nepomniachtchi said organisers chose one of the worst hotels for the Goa event.
MT: ꯏꯌꯥꯟ ꯅꯦꯄꯣꯃꯅꯤꯌꯥꯆꯠꯆꯤꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯒꯣꯋꯥꯒꯤ ꯊꯧꯔꯝꯒꯤꯗꯃꯛ ꯊꯧꯔꯥꯡ ꯇꯧꯕꯁꯤꯡꯅ ꯂꯥꯏꯔꯕ ꯍꯣꯇꯦꯜ ꯑꯃ ꯈꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▎                | 384/1000 [06:31<09:04,  1.13it/s]

[384/1000]
EN: Nepomniachtchi lost to Diptayan Ghosh after receiving a bye into round two.
MT: ꯅꯦꯄꯣꯃꯅꯤꯌꯥꯆꯠꯆꯤ ꯑꯁꯤ ꯔꯥꯎꯟꯗ ꯑꯅꯤꯗꯥ ꯕꯥꯏ ꯑꯃ ꯐꯪꯂꯕ ꯃꯇꯨꯡꯗ ꯗꯤꯄꯇꯌꯟ ꯒꯣꯁꯥꯇꯥ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▍                | 385/1000 [06:32<08:44,  1.17it/s]

[385/1000]
EN: PGTI’s 2026 schedule was drawn up only till March-end, featuring six events.
MT: ꯄꯤ ꯖꯤ ꯇꯤ ꯑꯥꯏ ꯒꯤ ꯁꯦꯗꯜ 2026 ꯑꯁꯤ ꯃꯥꯔꯀꯤ ꯑꯔꯣꯏꯕꯥ ꯐꯥꯎꯕꯗ ꯏꯚꯦꯟꯇ ꯇꯔꯨꯛ ꯌꯥꯎꯅꯥ ꯁꯦꯝ
--------------------------------------------------

Translating:  39%|██████████▍                | 386/1000 [06:33<08:28,  1.21it/s]

[386/1000]
EN: PGTI planned no more than 25 tournaments in 2026 after holding 36 events last year.
MT: ꯄꯤ ꯖꯤ ꯇꯤ ꯑꯥꯏꯅꯥ ꯍꯧꯈꯤꯕ ꯆꯍꯤꯗ ꯊꯧꯔꯝ 36 ꯄꯥꯡꯊꯣꯛꯂꯕ ꯃꯇꯨꯡꯗ ꯏꯪꯁꯣꯛ 2026 ꯗꯥ ꯇꯣꯔꯅꯥꯃꯦꯟꯇꯗꯒꯤ ꯍꯦꯟꯕꯥ ꯊꯧꯔꯥꯡ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  39%|██████████▍                | 387/1000 [06:34<08:37,  1.18it/s]

[387/1000]
EN: PGTI’s main tour offered ₹35 crore prize money in 2025, up from ₹24 crore.
MT: ꯄꯤ ꯖꯤ ꯇꯤ ꯑꯥꯏ ꯒꯤ ꯃꯔꯨ ꯑꯣꯏꯕ ꯇꯨꯔꯅꯥ ꯏꯪ 2025 ꯗꯥ ꯂꯨꯄꯥ ꯀꯔꯣꯔ 35 ꯒꯤ ꯄꯥꯏꯖ ꯃꯅꯤ ꯄꯤꯈꯤ, ꯃꯁꯤ ꯂꯨꯄꯥ ꯀꯣꯔꯣꯔ ꯗꯒꯤ ꯍꯦꯟꯒꯠ
--------------------------------------------------

Translating:  39%|██████████▍                | 388/1000 [06:35<10:02,  1.02it/s]

[388/1000]
EN: OWGR granted LIV Golf accreditation for the first time, awarding points to top-10 finishers.
MT: ꯑꯣ.ꯑꯣ.ꯖꯤ.ꯑꯥꯔ.ꯅꯥ ꯑꯍꯥꯟꯕ ꯑꯣꯏꯅ ꯑꯦꯜ. ꯑꯥꯏ.ꯚꯤ. ꯒꯣꯜꯐ ꯑꯦꯀꯗꯤꯇꯦꯁꯟ ꯄꯤꯈꯤ, ꯇꯣꯄ10 ꯐꯥꯏꯅꯤꯁꯔꯁꯤꯡꯗ ꯄꯣꯏꯟꯇꯁꯤꯡ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  39%|██████████▌                | 389/1000 [06:36<10:21,  1.02s/it]

[389/1000]
EN: LIV Golf expanded tournaments from 54 to 72 holes in 2026, paving the approval.
MT: ꯏꯪꯁꯣꯛ ꯗꯥ ꯑꯦꯜ.ꯑꯥꯏ.ꯚꯤ. ꯒꯣꯜꯐꯅꯥ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ 54ꯗꯒꯤ ꯍꯣꯜ ꯐꯥꯎꯕ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯈꯤ, ꯃꯗꯨꯅ ꯑꯌꯥꯕ ꯄꯤ
--------------------------------------------------

Translating:  39%|██████████▌                | 390/1000 [06:37<10:16,  1.01s/it]

[390/1000]
EN: OWGR said LIV Golf did not meet all eligibility standards under its requirements.
MT: ꯑꯣ.ꯑꯣ.ꯖꯤ.ꯑꯥꯔ.ꯅꯥ ꯍꯥꯏ ꯃꯗꯨꯗꯤ ꯑꯦꯜ. ꯑꯥꯏ.ꯚꯤ. ꯒꯣꯜꯐꯅꯥ ꯃꯁꯤꯒꯤ ꯃꯊꯧ ꯇꯥꯕꯥ ꯑꯦꯂꯤꯖꯤꯕꯤꯂꯤꯇꯤꯦꯟꯗꯗꯔ ꯄꯨꯝꯅꯃꯛ ꯐꯪꯗꯦ ꯫
--------------------------------------------------

Translating:  39%|██████████▌                | 391/1000 [06:38<09:26,  1.07it/s]

[391/1000]
EN: LIV Golf’s season-opening event in Riyadh was set to start with 57 players.
MT: ꯂꯤꯚ ꯒꯣꯜꯐꯀꯤ ꯁꯤꯖꯟ - ꯑꯣꯄꯦꯅꯤꯡ ꯏꯚꯦꯟꯇ ꯑꯁꯤ ꯔꯤꯌꯥꯗꯗꯥ ꯁꯥꯟꯅꯔꯣꯏ 57ꯒꯥ ꯂꯣꯏꯅꯅ ꯍꯧꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  39%|██████████▌                | 392/1000 [06:39<10:20,  1.02s/it]

[392/1000]
EN: International Series India was expected to move from DLF Golf and Country Club to Bengaluru.
MT: ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯁꯤꯔꯤꯖ ꯏꯟꯗꯤꯌꯥ ꯑꯁꯤ ꯗꯤ ꯑꯦꯜ ꯑꯦꯐ ꯒꯣꯜꯐ ꯑꯃꯁꯨꯡ ꯀꯟꯇ ꯀꯂꯕꯇꯒꯤ ꯕꯦꯡꯒꯂꯨꯔꯨꯗ ꯆꯠꯀꯅꯤ ꯍꯥꯏꯅ ꯄꯥꯅꯔꯤ ꯫
--------------------------------------------------

Translating:  39%|██████████▌                | 393/1000 [06:40<10:07,  1.00s/it]

[393/1000]
EN: Bryson DeChambeau and Joaquin Niemann were key draws at International Series India 2025.
MT: ꯕꯁꯟ ꯗꯤꯆꯝꯕꯦꯎ ꯑꯃꯁꯨꯡ ꯖꯣꯑꯀ ꯭ ꯋꯤꯟ ꯅꯤꯃꯦꯅꯅꯥ ꯏꯪ 2025 ꯗꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯁꯤꯔꯤꯖ ꯏꯟꯗꯤꯌꯥꯗꯥ ꯃꯔꯨꯑꯣꯏꯕ ꯗꯁꯤꯡ ꯑꯣꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  39%|██████████▋                | 394/1000 [06:41<09:49,  1.03it/s]

[394/1000]
EN: Ollie Schniederjans won International Series India 2025 by four shots in Gurugram.
MT: ꯑꯣꯂꯤꯅꯤꯗꯦꯔꯖꯟꯁꯅꯥ ꯒꯒꯣꯔꯥꯃꯗꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯁꯤꯔꯤꯖ ꯏꯟꯗꯤꯌꯥ 2025 ꯑꯁꯤ ꯁꯣꯠ ꯃꯔꯤꯅꯥ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  40%|██████████▋                | 395/1000 [06:42<09:20,  1.08it/s]

[395/1000]
EN: Rahul Singh said International Series organisers remained committed to returning to India.
MT: ꯔꯍꯨꯜ ꯁꯤꯡꯍꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯁꯤꯔꯤꯖ ꯑꯣꯔꯖꯦꯟꯖꯔꯁꯤꯡꯅ ꯚꯥꯔꯠꯇ ꯍꯜꯂꯛꯄꯗꯥ ꯂꯦꯞ
--------------------------------------------------

Translating:  40%|██████████▋                | 396/1000 [06:43<09:44,  1.03it/s]

[396/1000]
EN: PGTI launched a league with six franchises, with each franchise buying 10 players.
MT: ꯄꯤꯖꯤꯇꯤꯑꯥꯏꯅꯥ ꯐꯥꯟꯆꯥꯏꯖꯤ ꯇꯔꯨꯛꯀꯤ ꯂꯤꯒ ꯑꯃ ꯍꯥꯡꯗꯣꯛꯈꯤ, ꯃꯁꯤꯗ ꯐꯇꯟꯆꯏꯖꯤ ꯈꯨꯗꯤꯡꯃꯛꯅ ꯁꯥꯟꯅꯔꯣꯏ 10 ꯂꯧ
--------------------------------------------------

Translating:  40%|██████████▋                | 397/1000 [06:43<09:00,  1.12it/s]

[397/1000]
EN: The PGTI league’s first edition was planned across three courses in Delhi-NCR.
MT: ꯄꯤ ꯖꯤ ꯇꯤ ꯑꯥꯏ ꯂꯤꯒꯀꯤ ꯑꯍꯥꯟꯕꯥ ꯑꯦꯗꯤꯁꯟ ꯑꯁꯤ ꯗꯤꯜꯂꯤ- ꯑꯦꯟ ꯁꯤ ꯑꯥꯔ ꯒꯤ ꯀꯣꯔꯁ ꯑꯍꯨꯝꯗꯥ ꯊꯧꯔꯥꯡ ꯇꯧ
--------------------------------------------------

Translating:  40%|██████████▋                | 398/1000 [06:44<08:54,  1.13it/s]

[398/1000]
EN: Shubhankar Sharma missed cuts in 21 of 28 events in 2025, the report said.
MT: ꯁꯨꯚꯥꯟꯀꯔ ꯁꯔꯃꯥꯅꯥ ꯏꯪꯁꯣꯛ 2025 ꯗꯥ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯊꯧꯔꯝꯒꯤ ꯃꯅꯨꯡꯗ 21ꯗꯥ ꯀꯠꯁꯤꯡ ꯃꯥꯡꯈꯤ ꯍꯥꯏꯅ ꯔꯤꯄꯣꯔꯇ ꯑꯁꯤꯅ ꯍꯥꯏ
--------------------------------------------------

Translating:  40%|██████████▊                | 399/1000 [06:45<09:23,  1.07it/s]

[399/1000]
EN: Shubhankar Sharma regained playing rights for 2026 via Q-School, finishing tied-second.
MT: ꯁꯨꯚꯥꯟꯀꯔ ꯁꯔꯃꯥꯅꯥ ꯏꯪꯁꯣꯛ ꯒꯤꯗꯃꯛ ꯀ-ꯨꯜꯒꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯁꯥꯟꯅꯕꯒꯤ ꯍꯛꯁꯤꯡ ꯑꯃꯨꯛ ꯍꯟꯅ ꯂꯧꯁꯤꯟꯈꯤ, ꯇꯥꯏ-ꯁꯦꯀꯦꯟꯗ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  40%|██████████▊                | 400/1000 [06:46<09:11,  1.09it/s]

[400/1000]
EN: Vietnam targets 22 to 25 million international visitors by 2026.
MT: ꯚꯤꯇꯦꯝꯅꯥ ꯏꯪꯁꯣꯛ 2026 ꯐꯥꯎꯕꯗ ꯃꯥꯂꯦꯝꯒꯤ ꯑꯣꯏꯕ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈꯗꯒꯤ ꯐꯥꯎꯕ ꯂꯥꯛꯀꯗꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  40%|██████████▊                | 401/1000 [06:47<08:20,  1.20it/s]

[401/1000]
EN: Operations teams monitor weather to minimize passenger inconvenience.
MT: ꯑꯣꯄꯔꯦꯁꯟ ꯇꯤꯝꯁꯤꯡꯅꯥ ꯄꯦꯁꯦꯟꯖꯔꯁꯤꯡꯒꯤ ꯑꯋꯥꯕꯥ ꯍꯟꯊꯍꯟꯅꯕ ꯋꯦꯗꯔ ꯌꯦꯡꯁꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  40%|██████████▊                | 402/1000 [06:48<08:26,  1.18it/s]

[402/1000]
EN: IndiGo announces Amsterdam debut as first long-haul European destination.
MT: ꯏꯟꯗꯤꯒꯣꯅꯥ ꯑꯍꯥꯟꯕ ꯂꯥꯡ-ꯍꯣꯜ ꯌꯨꯔꯣꯄꯤꯌꯟ ꯗꯦꯁꯇꯤꯅꯦꯁꯟ ꯑꯣꯏꯅ ꯑꯝꯁꯇꯔꯗꯦꯃꯇꯗꯥ ꯗꯦꯕꯌꯨ ꯇꯧꯔꯦ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  40%|██████████▉                | 403/1000 [06:48<07:58,  1.25it/s]

[403/1000]
EN: Air India crash committee investigates Boeing 787-8 Ahmedabad tragedy.
MT: ꯑꯦꯔ ꯏꯟꯗꯤꯌꯥꯦꯁ ꯀꯝꯃꯤꯇꯤꯅ ꯕꯣꯏꯡ 787-8 ꯑꯍꯃꯗꯕꯥꯗ ꯇꯖꯦꯟꯗꯤ ꯊꯤꯖꯤꯟ
--------------------------------------------------

Translating:  40%|██████████▉                | 404/1000 [06:49<07:32,  1.32it/s]

[404/1000]
EN: IndiGo aims for forty percent international capacity share by 2030.
MT: ꯏꯟꯗꯤꯒꯣꯅꯥ ꯏꯪ 2030 ꯐꯥꯎꯕꯗ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯀꯦꯄꯦꯁꯤꯇꯤ ꯁꯦꯌꯔ ꯆꯥꯗꯥ 40 ꯑꯣꯏꯍꯟꯅꯕ ꯄꯥꯟꯗꯝ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  40%|██████████▉                | 405/1000 [06:50<07:13,  1.37it/s]

[405/1000]
EN: One survivor rescued from Air India crash site in Ahmedabad.
MT: ꯑꯍꯃꯗꯕꯥꯗꯇꯥ ꯂꯩꯕ ꯑꯦꯔ ꯏꯟꯗꯤꯌꯥ ꯀꯁ ꯁꯥꯏꯇꯗꯒꯤ ꯍꯤꯡꯕꯥ ꯃꯤꯑꯣꯏ ꯑꯃ ꯉꯥꯛꯊꯣꯛ
--------------------------------------------------

Translating:  41%|██████████▉                | 406/1000 [06:50<06:56,  1.43it/s]

[406/1000]
EN: Jetstar Asia closure frees five hundred million dollars for Qantas.
MT: ꯖꯦꯇꯁꯇꯥꯔ ꯑꯦꯁꯤꯌꯥ ꯀꯂꯣꯁꯔꯅꯥ ꯀꯋꯥꯟꯇꯥꯁꯀꯤ ꯗꯣꯂꯔ ꯃꯤꯂꯌꯟ ꯃꯉꯥ ꯐ
--------------------------------------------------

Translating:  41%|██████████▉                | 407/1000 [06:51<06:48,  1.45it/s]

[407/1000]
EN: Qantas Group announces closure of Singapore-based Jetstar Asia.
MT: ꯀꯋꯥꯟꯇꯥꯁ ꯒꯨꯞꯅ ꯁꯤꯡꯒꯥꯄꯨꯔꯗꯥ ꯂꯩꯕ ꯖꯦꯇꯁꯇꯥꯔ ꯑꯦꯁꯤꯌꯥ ꯊꯤꯡꯖꯤꯟꯅꯕꯥ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  41%|███████████                | 408/1000 [06:52<07:06,  1.39it/s]

[408/1000]
EN: IndiGo launches Mumbai-Manchester flights using Norse aircraft.
MT: ꯏꯟꯗꯤꯒꯣꯅꯥ ꯅꯣꯔ ꯭ ꯁ ꯑꯦꯔꯀꯐꯇ ꯁꯤꯖꯤꯟꯅꯕꯥ ꯃꯨꯝꯕꯥꯏ-ꯃꯥꯟꯆꯦꯁꯇꯔ ꯐꯂꯥꯏꯇꯁꯤꯡ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  41%|███████████                | 409/1000 [06:53<07:28,  1.32it/s]

[409/1000]
EN: IndiGo transitions to A350-900 aircraft for European expansion by 2027.
MT: ꯏꯪꯁꯣꯛ 2027 ꯐꯥꯎꯕꯗ ꯌꯨꯔꯣꯄꯤꯌꯟ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯅꯕ ꯏꯟꯗꯤꯒꯣꯅꯥ ꯑꯦ350-900 ꯑꯦꯌꯔꯀꯐꯇꯗꯥ ꯍꯣꯡꯗꯣꯛꯄꯥ ꯫
--------------------------------------------------

Translating:  41%|███████████                | 410/1000 [06:53<07:08,  1.38it/s]

[410/1000]
EN: Air India Ahmedabad crash claims 242 lives including Vijay Rupani.
MT: ꯑꯦꯔ ꯏꯟꯗꯤꯌꯥ ꯑꯍꯃꯗꯕꯥꯗ ꯀꯦꯁꯇꯥ ꯕꯤꯖꯌ ꯔꯨꯄꯥꯅꯤ ꯌꯥꯎꯅ ꯃꯤꯑꯣꯏ ꯁꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  41%|███████████                | 411/1000 [06:54<07:10,  1.37it/s]

[411/1000]
EN: Thirteen Jetstar Asia A320s redeployed to Australia and New Zealand.
MT: ꯖꯦꯇꯁꯇꯥꯔ ꯑꯦꯁꯤꯌꯥ ꯑꯦ 13 ꯑꯁꯤ ꯑꯣꯁꯇꯂꯤꯌꯥ ꯑꯃꯁꯨꯡ ꯅ ꯭ ꯌꯨ ꯖꯤꯂꯦꯟꯗꯗꯥ ꯑꯃꯨꯛ ꯍꯟꯅ ꯁꯤꯟꯅ
--------------------------------------------------

Translating:  41%|███████████                | 412/1000 [06:55<07:01,  1.40it/s]

[412/1000]
EN: IndiGo issues fog advisory for Delhi and northern India passengers.
MT: ꯏꯟꯗꯤꯒꯣꯅꯥ ꯗꯤꯜꯂꯤ ꯑꯃꯁꯨꯡ ꯑꯋꯥꯡ ꯚꯥꯔꯠꯀꯤ ꯄꯦꯁꯦꯟꯖꯔꯁꯤꯡꯒꯤꯗꯃꯛ ꯐꯒ ꯑꯦꯗꯚꯥꯏꯖꯔꯤꯁꯤꯡ ꯏꯁꯨ ꯇꯧ
--------------------------------------------------

Translating:  41%|███████████▏               | 413/1000 [06:55<06:52,  1.42it/s]

[413/1000]
EN: DGCA imposes ₹2 crore fine on Air India for safety lapses.
MT: ꯁꯦꯐꯇꯤ ꯂꯥꯄꯁꯤꯡꯒꯤꯗꯃꯛ ꯗꯤ ꯖꯤ ꯁꯤ ꯑꯦꯅꯥ ꯑꯦꯌꯔ ꯏꯟꯗꯤꯌꯥꯗꯥ ꯂꯨꯄꯥ ꯀꯔꯣꯔ 2 ꯐꯥꯏꯅ ꯇꯧ
--------------------------------------------------

Translating:  41%|███████████▏               | 414/1000 [06:56<07:04,  1.38it/s]

[414/1000]
EN: Sixteen intra-Asia routes lose only non-stop Changi connections.
MT: ꯏꯟ-ꯑꯦꯁꯤꯌꯥ ꯔꯨꯠ ꯇꯔꯥꯃꯥꯖꯅꯥ ꯅꯟ-ꯁꯇꯣꯄ ꯆꯪꯒꯤ ꯀꯟꯀꯁꯟꯁꯤꯡ ꯈꯛꯇꯃꯛ ꯃꯥꯡ
--------------------------------------------------

Translating:  42%|███████████▏               | 415/1000 [06:57<07:14,  1.35it/s]

[415/1000]
EN: Bengaluru airport opens second runway to handle growing traffic.
MT: ꯍꯦꯟꯒꯠꯂꯛꯂꯤꯕ ꯇꯐꯤꯛ ꯁꯤꯟꯗꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯕꯦꯡꯂꯨꯨꯔꯨ ꯑꯦꯌꯔꯄꯣꯔꯇꯅꯥ ꯑꯅꯤꯁꯨꯕ ꯔꯥꯟꯋꯦ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  42%|███████████▏               | 416/1000 [06:58<07:31,  1.29it/s]

[416/1000]
EN: Air India Express pilot assaults passenger at Delhi airport terminal.
MT: ꯑꯦꯔ ꯏꯟꯗꯤꯌꯥ ꯑꯦꯛꯁꯄꯦꯁꯀꯤ ꯄꯥꯏꯂꯣꯠꯅꯥ ꯗꯤꯜꯂꯤ ꯑꯦꯌꯔꯄꯣꯔꯇ ꯇꯔꯃꯤꯅꯦꯜꯗꯥ ꯄꯦꯁꯦꯟꯖꯔꯕꯨ ꯂꯥꯟꯗꯥꯈꯤ ꯫
--------------------------------------------------

Translating:  42%|███████████▎               | 417/1000 [06:59<07:13,  1.35it/s]

[417/1000]
EN: Mumbai airport witnesses record passenger footfall during festive week.
MT: ꯃꯨꯝꯕꯥꯏ ꯑꯦꯌꯔꯄꯣꯔꯇꯗꯥ ꯀꯨꯝꯍꯩꯒꯤ ꯆꯌꯣꯜꯗꯥ ꯄꯦꯁꯦꯟꯖꯔꯁꯤꯡꯒꯤ ꯃꯁꯤꯡ ꯍꯟꯊꯔꯛꯄꯒꯤ ꯈꯨꯗꯝ
--------------------------------------------------

Translating:  42%|███████████▎               | 418/1000 [06:59<07:22,  1.31it/s]

[418/1000]
EN: Dense fog disrupts IndiGo flight operations across North India.
MT: ꯑꯋꯥꯡ ꯚꯥꯔꯠ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯀꯨꯡꯈꯠꯂꯛꯄꯥ ꯎꯔꯨꯝꯅꯥ ꯏꯟꯗꯤꯒꯣ ꯐꯥꯏꯇ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡꯗ ꯑꯀꯥꯏꯕꯥ ꯄꯤ
--------------------------------------------------

Translating:  42%|███████████▎               | 419/1000 [07:00<07:18,  1.33it/s]

[419/1000]
EN: Go First insolvency resolution extends to third consecutive month.
MT: ꯒꯣ ꯐꯔꯁꯠ ꯏꯟꯁꯣꯜꯚꯦꯟꯁꯤ ꯔꯤꯖꯂꯨꯁꯟ ꯑꯁꯤ ꯃꯊꯪ ꯃꯅꯥꯎ ꯅꯥꯏꯅ ꯊꯥ ꯑꯍꯨꯝ ꯐꯥꯎꯕ ꯁꯟꯗꯣꯛ
--------------------------------------------------

Translating:  42%|███████████▎               | 420/1000 [07:01<07:26,  1.30it/s]

[420/1000]
EN: Akasa Air orders additional Boeing 737 Max aircraft for expansion.
MT: ꯑꯀꯥꯁꯥ ꯑꯦꯌꯔꯅꯥ ꯑꯍꯦꯟꯕ ꯕꯣꯏꯡ 737 ꯃꯦꯛꯁ ꯑꯦꯌꯔꯀꯐꯇ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯅꯕ ꯑꯣꯔꯗꯔ ꯄꯤ
--------------------------------------------------

Translating:  42%|███████████▎               | 421/1000 [07:02<07:12,  1.34it/s]

[421/1000]
EN: Air India pilots union raises concerns over rest period violations.
MT: ꯑꯦꯔ ꯏꯟꯗꯤꯌꯥ ꯄꯥꯏꯂꯣꯠꯁ ꯌꯨꯅꯤꯌꯟꯅ ꯔꯤꯁꯇꯥꯏꯗ ꯋꯥꯂꯥꯏꯟ ꯇꯧꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯆꯤꯡꯅꯕ ꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  42%|███████████▍               | 422/1000 [07:02<07:08,  1.35it/s]

[422/1000]
EN: EU launches Entry-Exit System campaign for non-EU travellers.
MT: ꯏꯌꯨ ꯅꯟ-ꯏꯌꯨ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯑꯦꯟꯇꯤ-ꯑꯦꯛꯖꯤꯠ ꯁꯤꯁꯇꯦꯝ ꯀꯦꯝꯄꯦꯅ ꯍꯧ
--------------------------------------------------

Translating:  42%|███████████▍               | 423/1000 [07:03<07:31,  1.28it/s]

[423/1000]
EN: SpiceJet secures funding to revive grounded fleet operations soon.
MT: ꯁꯥꯏꯖ ꯖꯦꯇꯅꯥ ꯊꯨꯅꯃꯛ ꯂꯩꯅꯨꯡꯗ ꯂꯩꯕ ꯐꯂꯤꯇ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡ ꯑꯃꯨꯛ ꯍꯟꯅ ꯍꯤꯡꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯁꯦꯜ ꯐꯪꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  42%|███████████▍               | 424/1000 [07:04<07:14,  1.32it/s]

[424/1000]
EN: Bulgaria adopts Euro as legal tender from January first 2026.
MT: ꯏꯪꯁꯣꯛ ꯒꯤ ꯖꯅꯨꯋꯥꯔꯤꯗꯒꯤ ꯕꯂꯒꯦꯔꯤꯌꯥꯅꯥ ꯌꯨꯔꯣꯕꯨ ꯂꯦꯖꯤꯀꯦꯜ ꯇꯦꯟꯗꯔ ꯑꯣꯏꯅ ꯂꯧ
--------------------------------------------------

Translating:  42%|███████████▍               | 425/1000 [07:05<07:12,  1.33it/s]

[425/1000]
EN: Vietnam grants forty-five day visa-free entry to twelve European nations.
MT: ꯚꯤꯇꯦꯝꯅꯥ ꯌꯨꯔꯣꯄꯤꯌꯟ ꯂꯩꯕꯥꯛ ꯇꯔꯥꯃꯥꯖꯗꯥ ꯅꯨꯃꯤꯠ ꯃꯔꯤ - ꯃꯉꯥꯒꯤ ꯚꯤꯖꯥ-ꯐ ꯑꯦꯟꯔꯤ ꯄꯤ
--------------------------------------------------

Translating:  43%|███████████▌               | 426/1000 [07:05<06:41,  1.43it/s]

[426/1000]
EN: Indian government reverses ban on Sikh pilgrimages to Pakistan.
MT: ꯚꯥꯔꯠ ꯁꯔꯀꯥꯔꯅꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯗꯥ ꯁꯤꯈ ꯂꯥꯏꯅꯤꯡꯐꯝ ꯆꯠꯄꯗꯥ ꯂꯦꯞꯈꯤꯕꯗꯨ ꯍꯟꯗꯣꯛ
--------------------------------------------------

Translating:  43%|███████████▌               | 427/1000 [07:06<06:32,  1.46it/s]

[427/1000]
EN: Pakistan High Commission issues visas to twenty-one hundred Sikh pilgrims.
MT: ꯄꯥꯀꯤꯁꯇꯥꯟ ꯍꯥꯏ ꯀꯝꯃꯤꯁꯟꯅꯥ ꯁꯤꯈ ꯂꯥꯏꯅꯤꯡꯐꯝ ꯆꯥꯃ ꯆꯥꯗꯥ ꯚꯤꯖꯥ ꯄꯤ
--------------------------------------------------

Translating:  43%|███████████▌               | 428/1000 [07:07<06:33,  1.45it/s]

[428/1000]
EN: TSA ends shoe removal rule at domestic United States airports.
MT: ꯇꯤ ꯑꯦꯁ ꯑꯦꯅꯥ ꯗꯣꯃꯦꯁꯇꯤꯛ ꯌꯨꯅꯥꯏꯇꯦꯗ ꯑꯦꯔꯄꯣꯔꯇꯗꯥ ꯁꯨ ꯔꯤꯃꯣꯕꯦꯜ ꯔꯨꯜ ꯂꯣꯏꯁꯤꯟ
--------------------------------------------------

Translating:  43%|███████████▌               | 429/1000 [07:07<06:44,  1.41it/s]

[429/1000]
EN: Real ID enforcement charges tourists forty-five dollars for domestic flights.
MT: ꯔꯤꯌꯦꯜ ꯑꯥꯏꯗꯤ ꯑꯦꯟꯐꯔꯁꯃꯦꯟꯇꯅꯥ ꯗꯣꯃꯦꯁꯇꯤꯛꯂꯥꯏꯇꯁꯤꯡꯒꯤꯗꯃꯛ ꯂꯝꯀꯣꯏꯕꯥꯁꯤꯡꯗꯒꯤ ꯗꯣꯂꯔ ꯃꯔꯤ - ꯃꯉꯥ ꯂꯧꯏ ꯫
--------------------------------------------------

Translating:  43%|███████████▌               | 430/1000 [07:08<06:41,  1.42it/s]

[430/1000]
EN: United States government shutdown causes forty-three day travel chaos.
MT: ꯌꯨꯅꯥꯏꯇꯦꯗꯁ ꯒꯕꯔꯃꯦꯟꯇ ꯁꯇꯗꯟ ꯇꯧꯕꯅꯥ ꯅꯨꯃꯤꯠ ꯃꯔꯤ - ꯑꯍꯨꯝꯒꯤ ꯂꯝꯀꯣꯏꯕꯒꯤ ꯑꯋꯥꯕ ꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  43%|███████████▋               | 431/1000 [07:09<06:51,  1.38it/s]

[431/1000]
EN: Government considers hotel industry infrastructure status for tax benefits.
MT: ꯁꯔꯀꯥꯔꯅꯥ ꯇꯦꯛꯁ ꯕꯦꯅꯤꯐꯤꯇꯁꯤꯡꯒꯤꯗꯃꯛ ꯍꯣꯇꯦꯜ ꯏꯟꯗꯁꯇꯒꯤ ꯏꯟꯐꯁꯇ ꯭ ꯔꯛꯆꯔꯇꯦꯁ ꯈꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  43%|███████████▋               | 432/1000 [07:10<06:52,  1.38it/s]

[432/1000]
EN: Gajendra Singh Shekhawat announces infrastructure status proposal for hotels.
MT: ꯒꯖꯦꯟꯗ ꯁꯤꯡ ꯁꯦꯈꯥꯋꯥꯠꯅ ꯍꯣꯇꯦꯜꯁꯤꯡꯒꯤ ꯏꯟꯐꯁꯇꯛꯆꯔꯇꯦꯁꯄꯣꯖꯦꯜ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  43%|███████████▋               | 433/1000 [07:10<06:54,  1.37it/s]

[433/1000]
EN: Tourism Ministry reboots Incredible India campaign with AI focus.
MT: ꯇꯨꯔꯤꯖꯝ ꯃꯟꯇꯅꯥ ꯑꯦꯑꯏ ꯃꯤꯠꯌꯦꯡ ꯊꯝꯕꯥ ꯏꯟꯀꯗꯤꯕꯜ ꯏꯟꯗꯤꯌꯥ ꯀꯦꯝꯄꯦꯟ ꯔꯤꯕꯨꯇ ꯇꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  43%|███████████▋               | 434/1000 [07:11<07:09,  1.32it/s]

[434/1000]
EN: Suman Billa confirms new digital-centric Incredible India strategy.
MT: ꯁꯨꯃꯟ ꯕꯤꯂꯥꯅꯥ ꯑꯅꯧꯕ ꯗꯤꯖꯤꯇꯦꯜ ꯀꯦꯟꯗ ꯑꯣꯏꯕ ꯏꯟꯀꯗꯤꯕꯜ ꯏꯟꯗꯤꯌꯥꯇꯔꯦꯖꯤ ꯑꯗꯨ ꯀꯟꯐꯥꯔꯃ ꯇꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  44%|███████████▋               | 435/1000 [07:12<06:47,  1.39it/s]

[435/1000]
EN: India targets one trillion dollar tourism economy by 2047.
MT: ꯚꯥꯔꯠꯅ ꯐꯥꯎꯕꯗ ꯗꯣꯂꯔ ꯇꯂꯤꯌꯟ ꯑꯃ ꯇꯨꯔꯤꯖꯝ ꯑꯦꯀꯅꯣꯃꯤꯒꯤ ꯄꯥꯟꯗꯝ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  44%|███████████▊               | 436/1000 [07:12<06:57,  1.35it/s]

[436/1000]
EN: Centre sanctions fifty destinations for challenge mode tourism development.
MT: ꯁꯦꯟꯅꯥ ꯆꯦꯂꯦꯟꯖ ꯃꯣꯗ ꯇꯨꯔꯤꯖꯝ ꯗꯤꯚꯂꯞꯃꯦꯟꯇꯒꯤꯗꯃꯛ ꯗꯦꯁꯇꯤꯅꯦꯁꯟ ꯃꯉꯥ ꯌꯥꯍꯟ
--------------------------------------------------

Translating:  44%|███████████▊               | 437/1000 [07:13<06:46,  1.38it/s]

[437/1000]
EN: Telangana adopts Sarathi portal for online RTA services.
MT: ꯇꯦꯂꯪꯒꯥꯅꯥꯅꯥ ꯑꯣꯟꯂꯥꯏꯟ ꯑꯥꯔꯇꯤꯑꯦ ꯁꯔꯕꯤꯁꯁꯤꯡꯒꯤꯗꯃꯛ ꯁꯥꯔꯥꯊꯤ ꯄꯣꯔꯇꯦꯜ ꯂꯧ
--------------------------------------------------

Translating:  44%|███████████▊               | 438/1000 [07:14<06:30,  1.44it/s]

[438/1000]
EN: Ministry announces twelve thousand crore rupees for new tourism destinations.
MT: ꯃꯟꯇꯅꯥ ꯑꯅꯧꯕ ꯇꯨꯔꯤꯖꯝ ꯗꯦꯁꯇꯤꯅꯦꯁꯟꯁꯤꯡꯒꯤꯗꯃꯛ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯂꯤꯁꯤꯡ ꯇꯔꯥꯃꯥꯖ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  44%|███████████▊               | 439/1000 [07:15<06:40,  1.40it/s]

[439/1000]
EN: Government allocates 1.34 billion dollars for tourism infrastructure development.
MT: ꯁꯔꯀꯥꯔꯅꯥ ꯇꯨꯔꯤꯖꯝ ꯏꯟꯐꯁꯇꯛꯆꯔ ꯗꯤꯚꯂꯞꯃꯦꯟꯇꯒꯤꯗꯃꯛ ꯗꯣꯂꯔ ꯕꯤꯂꯤꯌꯟ ꯊꯥꯖꯤꯟ
--------------------------------------------------

Translating:  44%|███████████▉               | 440/1000 [07:15<06:32,  1.43it/s]

[440/1000]
EN: India plans 2030 Commonwealth Games hosting to boost tourism.
MT: ꯇꯨꯔꯤꯖꯝ ꯍꯦꯟꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯚꯥꯔꯠꯅ 2030 ꯒꯤ ꯀꯃꯟꯋꯦꯜꯊ ꯒꯦꯝꯁ ꯄꯥꯡꯊꯣꯛꯅꯕ ꯊꯧꯔꯥꯡ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  44%|███████████▉               | 441/1000 [07:16<06:38,  1.40it/s]

[441/1000]
EN: Census self-enumeration trial begins for digital population count.
MT: ꯗꯤꯖꯤꯇꯦꯜ ꯄꯣꯄꯨꯂꯦꯁꯟ ꯀꯥꯎꯟꯠꯀꯤ ꯁꯦꯟꯁꯁ ꯁꯦꯜꯐ- ꯑꯦꯅꯨꯃꯦꯔꯦꯁꯟꯌꯦꯜ ꯍꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  44%|███████████▉               | 442/1000 [07:17<06:39,  1.40it/s]

[442/1000]
EN: European Commission launches biometric border system awareness campaign.
MT: ꯌꯨꯔꯣꯄꯤꯌꯟ ꯀꯃꯤꯁꯟꯅꯥ ꯕꯥꯏꯌꯣꯃꯦꯇ ꯕꯔꯗꯔ ꯁꯤꯁꯇꯦꯝ ꯑꯦꯚꯦꯌꯔꯦꯟꯁ ꯀꯦꯝꯄꯦꯅ ꯍꯧ
--------------------------------------------------

Translating:  44%|███████████▉               | 443/1000 [07:17<06:21,  1.46it/s]

[443/1000]
EN: Non-EU travellers face new digital border checks from October.
MT: ꯏꯌꯨ ꯅꯠꯇꯕꯥ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯅ ꯑꯣꯛꯇꯣꯕꯔꯗꯒꯤ ꯑꯅꯧꯕ ꯗꯤꯖꯤꯇꯦꯜ ꯕꯔꯗꯔ ꯆꯦꯛꯁꯤꯡ ꯊꯦꯡꯅꯩ ꯫
--------------------------------------------------

Translating:  44%|███████████▉               | 444/1000 [07:18<06:40,  1.39it/s]

[444/1000]
EN: Dover ferry passengers register first for EU entry-exit system.
MT: ꯗꯣꯚꯔ ꯐꯦꯔꯤ ꯄꯦꯁꯦꯟꯖꯔꯁꯤꯡꯅꯌꯨ ꯑꯦꯟꯇꯤ-ꯑꯦꯛꯖꯤꯠ ꯁꯤꯁꯇꯦꯝꯒꯤꯗꯃꯛ ꯑꯍꯥꯟꯕꯗꯥ ꯔꯦꯖꯤꯁꯇꯔ ꯇꯧ
--------------------------------------------------

Translating:  44%|████████████               | 445/1000 [07:19<06:46,  1.37it/s]

[445/1000]
EN: Eurostar business travellers gradually included in EES rollout.
MT: ꯌꯨꯔꯣꯁꯇꯥꯔ ꯕꯤꯖꯤꯅꯦꯁ ꯇꯚꯦꯂꯔꯁꯤꯡ ꯑꯁꯤ ꯏ ꯏ ꯑꯦꯁ ꯔꯣꯜꯥꯎꯇꯗꯥ ꯇꯞꯅ-ꯃꯠꯇ ꯌꯥꯎ
--------------------------------------------------

Translating:  45%|████████████               | 446/1000 [07:20<06:28,  1.43it/s]

[446/1000]
EN: India extends e-visa facility to citizens of five more nations.
MT: ꯚꯥꯔꯠꯇꯥ ꯏ-ꯚꯤꯖꯥ ꯐꯦꯁꯤꯂꯤꯇꯤ ꯑꯁꯤ ꯂꯩꯕꯥꯛ ꯃꯉꯥꯒꯤ ꯃꯤꯌꯣꯏꯁꯤꯡꯗ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  45%|████████████               | 447/1000 [07:20<06:30,  1.42it/s]

[447/1000]
EN: Karnataka announces tourism policy targeting fifty billion dollar investment
MT: ꯀꯔꯅꯥꯇꯀꯥꯅꯥ ꯗꯣꯂꯔ ꯕꯤꯂꯤꯌꯟ ꯃꯉꯥꯒꯤ ꯏꯟꯚꯦꯁꯇꯃꯦꯟꯇ ꯇꯥꯔꯀꯦꯇ ꯇꯧꯕ ꯇꯨꯔꯤꯖꯝ ꯄꯣꯂꯤꯁꯤ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  45%|████████████               | 448/1000 [07:21<06:27,  1.42it/s]

[448/1000]
EN: GST Council reduces tax on hotel rooms below seven thousand five hundred rupees.
MT: ꯖꯤ ꯑꯦꯁ ꯇꯤ ꯀꯥꯎꯟꯁꯜꯅꯥ ꯍꯣꯇꯦꯜ ꯀꯥꯁꯤꯡꯒꯤ ꯇꯦꯛꯁ ꯑꯁꯤ ꯂꯨꯄꯥ ꯆꯥꯗꯥ ꯂꯤꯁꯤꯡ ꯃꯉꯥꯒꯤ ꯃꯈꯥꯗ ꯍꯟꯊꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  45%|████████████               | 449/1000 [07:22<06:36,  1.39it/s]

[449/1000]
EN: Ministry of Tourism launches Swadesh Darshan 3.0 for sustainable tourism.
MT: ꯇꯨꯔꯤꯖꯝ ꯃꯟꯇꯅꯥ ꯁꯁꯇꯦꯕꯦꯅꯤꯌꯦꯜ ꯇꯨꯔꯤꯖꯝꯒꯤꯗꯃꯛꯋꯥꯗꯦꯁ ꯗꯔꯁꯟ ꯂꯣꯆ ꯇꯧ
--------------------------------------------------

Translating:  45%|████████████▏              | 450/1000 [07:22<06:38,  1.38it/s]

[450/1000]
EN: Civil Aviation Ministry orders probe into Delhi airport assault case.
MT: ꯁꯤꯚꯤꯜ ꯑꯦꯚꯤꯌꯦꯁꯟ ꯃꯟꯇꯅꯥ ꯗꯤꯜꯂꯤ ꯑꯦꯌꯔꯄꯣꯔꯇ ꯑꯦꯁꯣꯂꯇ ꯀꯦꯁ ꯊꯤꯖꯤꯟꯕꯒꯤ ꯑꯣꯔꯗꯔ ꯄꯤ
--------------------------------------------------

Translating:  45%|████████████▏              | 451/1000 [07:23<06:37,  1.38it/s]

[451/1000]
EN: Government approves UDAN 5.0 with focus on helicopter services.
MT: ꯍꯦꯂꯤꯀꯣꯞꯇꯔ ꯁꯔꯕꯤꯁꯁꯤꯡꯗ ꯃꯤꯠꯌꯦꯡ ꯊꯝꯗꯨꯅꯥ ꯒꯚꯔꯃꯦꯟꯇꯅꯥ ꯎꯗꯥꯅ ꯑꯌꯥꯕ ꯄꯤꯔꯦ ꯫
--------------------------------------------------

Translating:  45%|████████████▏              | 452/1000 [07:24<06:36,  1.38it/s]

[452/1000]
EN: Kerala declares tourism as industry status for hotels and resorts.
MT: ꯀꯦꯔꯂꯥꯅꯥ ꯇꯨꯔꯤꯖꯝ ꯑꯁꯤ ꯍꯣꯇꯦꯜ ꯑꯃꯁꯨꯡ ꯔꯤꯖꯣꯔꯇꯁꯤꯡꯒꯤ ꯏꯟꯗꯁꯇꯒꯤ ꯊꯥꯛꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  45%|████████████▏              | 453/1000 [07:25<06:23,  1.43it/s]

[453/1000]
EN: West Bengal secures second rank in foreign tourist arrivals.
MT: ꯋꯇ ꯕꯦꯡꯒꯣꯜꯅꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯂꯝꯀꯣꯏꯕꯥ ꯂꯥꯛꯄꯥꯁꯤꯡꯒꯤ ꯃꯅꯨꯡꯗ ꯑꯅꯤ ꯁꯨꯕꯥ ꯔꯦꯡꯀ ꯐꯪ
--------------------------------------------------

Translating:  45%|████████████▎              | 454/1000 [07:25<06:32,  1.39it/s]

[454/1000]
EN: Mamata Banerjee hails West Bengal's international tourism milestone.
MT: ꯃꯃꯇꯥ ꯕꯦꯅꯖꯔꯤꯅꯥ ꯋꯇ ꯕꯦꯡꯒꯜꯒꯤ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯇꯨꯔꯤꯖꯝ ꯃꯥꯏꯜꯆꯣꯠꯅꯤ ꯍꯥꯏꯅ ꯊꯥꯒꯠ
--------------------------------------------------

Translating:  46%|████████████▎              | 455/1000 [07:26<06:39,  1.36it/s]

[455/1000]
EN: Maharashtra leads foreign tourist arrivals with 3.71 million visitors.
MT: ꯃꯍꯥꯔꯥꯁꯇꯗꯥ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈꯒ ꯂꯣꯏꯅꯅꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯇꯒꯤ ꯂꯥꯛꯄꯥ ꯂꯝꯀꯣꯏꯕꯁꯤꯡ ꯑꯁꯤ ꯃꯥꯡꯖꯤꯜ ꯊꯥ
--------------------------------------------------

Translating:  46%|████████████▎              | 456/1000 [07:27<06:35,  1.37it/s]

[456/1000]
EN: West Bengal records 3.12 million foreign tourist visits nationwide.
MT: ꯋꯇ ꯕꯦꯡꯒꯜꯅꯥ ꯂꯩꯕꯥꯛ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯂꯥꯛꯄꯒꯤ ꯔꯦꯀꯣꯔ
--------------------------------------------------

Translating:  46%|████████████▎              | 457/1000 [07:28<06:40,  1.36it/s]

[457/1000]
EN: Uttar Pradesh tops domestic tourism with 646.81 million visitors.
MT: ꯎꯠꯇꯔꯗꯥ ꯂꯝꯀꯣꯏꯕ ꯃꯤ ꯂꯥꯈ.81 ꯄꯨꯗꯨꯅ ꯗꯣꯃꯦꯁꯇꯤꯛ ꯇꯨꯔꯤꯖꯝꯗꯥ ꯃꯥꯡꯖꯤꯜ ꯊꯥ
--------------------------------------------------

Translating:  46%|████████████▎              | 458/1000 [07:28<06:29,  1.39it/s]

[458/1000]
EN: Tamil Nadu records 306.84 million domestic tourist footfall.
MT: ꯇꯥꯃꯤꯜ ꯅꯥꯗꯨꯗ ꯗꯣꯃꯦꯁꯇꯤꯛ ꯇꯨꯔꯤꯁꯇ ꯀꯂꯌꯟ. ꯔꯦꯀꯣꯔ ꯇꯧ
--------------------------------------------------

Translating:  46%|████████████▍              | 459/1000 [07:29<06:39,  1.36it/s]

[459/1000]
EN: India receives 2,948.19 million domestic tourists during 2024.
MT: ꯏꯪꯁꯣꯛ ꯒꯤ ꯃꯅꯨꯡꯗ ꯚꯥꯔꯠꯇꯥ ꯗꯣꯃꯦꯁꯇꯤꯛ ꯇꯨꯔꯤꯁꯇ ꯃꯤꯂꯌꯟꯒꯤ ꯃꯁꯤꯡ948.19 ꯐꯪ
--------------------------------------------------

Translating:  46%|████████████▍              | 460/1000 [07:30<06:33,  1.37it/s]

[460/1000]
EN: Foreign tourist visits to India touch 20.94 million in 2024.
MT: ꯏꯪꯁꯣꯛ ꯗꯥ ꯚꯥꯔꯠꯇꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯅ ꯂꯥꯛꯄꯥ ꯃꯁꯤꯡ ꯑꯁꯤ. ꯌꯣꯟ
--------------------------------------------------

Translating:  46%|████████████▍              | 461/1000 [07:30<06:20,  1.42it/s]

[461/1000]
EN: Domestic tourism records 17.51 percent growth over previous year.
MT: ꯗꯣꯃꯦꯁꯇꯤꯛ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯍꯧꯈꯤꯕ ꯆꯍꯤꯒꯥ ꯆꯥꯡꯗꯝꯅꯕꯗ ꯆꯥꯗ. ꯍꯦꯟꯒꯠꯂꯛ
--------------------------------------------------

Translating:  46%|████████████▍              | 462/1000 [07:31<05:57,  1.50it/s]

[462/1000]
EN: International tourist arrivals grow 8.84 percent in 2024.
MT: ꯏꯪ 2024 ꯗꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯇꯨꯔꯤꯁꯇ ꯂꯥꯛꯄꯥ ꯑꯁꯤ ꯆꯥꯗ ꯍꯦꯟꯒꯠꯂꯛꯀꯅꯤ ꯫
--------------------------------------------------

Translating:  46%|████████████▌              | 463/1000 [07:32<06:02,  1.48it/s]

[463/1000]
EN: Maha Kumbh Mela attracts 663 million visits across forty-five days.
MT: ꯃꯍꯥ ꯀꯨꯝꯚ ꯃꯦꯂꯥꯗꯥ ꯅꯨꯃꯤꯠ ꯃꯔꯤ - ꯃꯉꯥꯅꯤꯒꯤ ꯃꯅꯨꯡꯗ ꯃꯤ ꯂꯥꯈ ꯂꯥꯛꯄꯥ ꯂꯥꯛꯏ ꯫
--------------------------------------------------

Translating:  46%|████████████▌              | 464/1000 [07:32<06:07,  1.46it/s]

[464/1000]
EN: Prayagraj witnesses 660 million pilgrims at Sangam confluence.
MT: ꯄꯌꯥꯒꯔꯥꯖꯗꯥ ꯁꯡꯒꯥꯃ ꯁꯝꯐꯝꯗꯥ ꯂꯥꯏ ꯆꯠꯄꯥ ꯃꯤꯑꯣꯏ ꯂꯥꯈ ꯌꯦꯡ
--------------------------------------------------

Translating:  46%|████████████▌              | 465/1000 [07:33<06:26,  1.38it/s]

[465/1000]
EN: Vietnam welcomes 1.73 million international visitors during October 2025.
MT: ꯏꯪꯁꯣꯛ 2025ꯒꯤ ꯑꯣꯛꯇꯣꯕꯔ ꯊꯥꯗꯥ ꯚꯤꯇꯦꯝꯅꯥ ꯃꯤꯌꯣꯏ ꯂꯥꯈꯕꯨ ꯑꯥꯀꯥꯁꯕꯥ ꯄꯤ
--------------------------------------------------

Translating:  47%|████████████▌              | 466/1000 [07:34<06:27,  1.38it/s]

[466/1000]
EN: Vietnam records 13.8 percent monthly growth in foreign tourist arrivals.
MT: ꯚꯤꯇꯦꯝꯅꯥ ꯐꯣꯔꯦꯟ ꯇꯨꯔꯤꯁꯇ ꯂꯥꯛꯄꯥꯁꯤꯡꯒꯤ ꯊꯥ ꯈꯨꯗꯤꯡꯒꯤ ꯆꯥꯗ. ꯍꯦꯟꯒꯠꯂꯛꯄꯒꯤ ꯔꯦꯀꯣꯔ ꯇꯧ
--------------------------------------------------

Translating:  47%|████████████▌              | 467/1000 [07:34<06:05,  1.46it/s]

[467/1000]
EN: India attracts only ten million international tourists annually currently.
MT: ꯚꯥꯔꯠꯇꯥ ꯍꯧꯖꯤꯛ ꯆꯍꯤꯗꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯇꯨꯔꯤꯁꯇ ꯀꯂꯌꯟ ꯇꯔꯥ ꯈꯛꯇꯃꯛ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  47%|████████████▋              | 468/1000 [07:35<06:28,  1.37it/s]

[468/1000]
EN: France welcomes ninety million tourists against India's ten million.
MT: ꯐꯟꯁꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯃꯤꯌꯣꯏ ꯀꯌꯥꯒ ꯌꯦꯡꯅꯕꯗ ꯂꯝꯀꯣꯏꯕ ꯃꯤꯌꯦꯂꯟ ꯇꯔꯥꯃꯨꯛꯄꯨ ꯍꯥꯟꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  47%|████████████▋              | 469/1000 [07:36<06:18,  1.40it/s]

[469/1000]
EN: Spain receives eighty-four million international visitors annually.
MT: ꯁꯄꯦꯟꯗ ꯆꯍꯤꯗꯥ ꯃꯤꯌꯣꯏ ꯂꯥꯈ ꯂꯥꯛꯄꯥ ꯂꯥꯛꯏ ꯫
--------------------------------------------------

Translating:  47%|████████████▋              | 470/1000 [07:37<06:04,  1.45it/s]

[470/1000]
EN: United States hosts eighty million foreign tourists every year.
MT: ꯌꯨꯅꯥꯏꯇꯦꯠꯁꯇ ꯆꯍꯤ ꯈꯨꯗꯤꯡꯒꯤ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ 80 ꯂꯥꯛꯏ ꯫
--------------------------------------------------

Translating:  47%|████████████▋              | 471/1000 [07:37<05:47,  1.52it/s]

[471/1000]
EN: India's pre-Covid tourist arrival figures remain unmatched after six years.
MT: ꯚꯥꯔꯠꯀꯤ-ꯀꯣꯕꯤꯗ ꯂꯝꯀꯣꯏꯕꯥ ꯂꯥꯛꯄꯥ ꯃꯁꯤꯡ ꯑꯁꯤ ꯆꯍꯤ ꯇꯔꯨꯛꯀꯤ ꯃꯇꯨꯡꯗꯁꯨ ꯃꯥꯟꯅ
--------------------------------------------------

Translating:  47%|████████████▋              | 472/1000 [07:38<05:30,  1.60it/s]

[472/1000]
EN: Tourism contributes 5.2 percent to India's current GDP.
MT: ꯚꯥꯔꯠꯀꯤ ꯍꯧꯖꯤꯛ ꯂꯩꯔꯤꯕ ꯖꯤꯗꯤꯄꯤꯗꯥ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯆꯥꯗ ꯁꯔꯨꯛ ꯄꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  47%|████████████▊              | 473/1000 [07:38<05:52,  1.50it/s]

[473/1000]
EN: Tourism sector supports 84 million livelihoods across India.
MT: ꯇꯨꯔꯤꯖꯝ ꯁꯦꯛꯇꯔꯅ ꯚꯥꯔꯠ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯍꯤꯡꯐꯝ ꯂꯥꯈ ꯁꯧꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  47%|████████████▊              | 474/1000 [07:39<06:07,  1.43it/s]

[474/1000]
EN: FICCI predicts 250 billion dollar tourism opportunity by 2030.
MT: ꯐꯤꯆꯤꯑꯥꯏꯅꯥ ꯐꯥꯎꯕꯗ ꯗꯣꯂꯔ ꯕꯤꯂꯤꯌꯟ ꯇꯨꯔꯤꯖꯝꯒꯤ ꯈꯨꯗꯣꯡꯆꯥꯕꯥ ꯐꯪꯒꯅꯤ ꯍꯥꯏꯅ ꯄꯥꯅꯔꯤ ꯫
--------------------------------------------------

Translating:  48%|████████████▊              | 475/1000 [07:40<06:21,  1.38it/s]

[475/1000]
EN: ICRA reports hotel demand to exceed supply in coming years.
MT: ꯂꯥꯛꯀꯗꯧꯔꯤꯕ ꯆꯍꯤꯁꯤꯡ ꯑꯁꯤꯗ ꯍꯣꯇꯦꯜ ꯗꯤꯃꯥꯟꯗꯅ ꯁꯄꯂꯥꯏꯗꯒꯤ ꯍꯦꯟꯒꯅꯤ ꯍꯥꯏꯅ ꯑꯥꯏ ꯁꯤ ꯑꯥꯔ ꯑꯦꯅꯥ ꯔꯤꯄꯣꯔꯇ ꯇꯧ
--------------------------------------------------

Translating:  48%|████████████▊              | 476/1000 [07:41<06:21,  1.38it/s]

[476/1000]
EN: Global travel industry generates 10.9 trillion dollars for economies.
MT: ꯒ ꯭ ꯂꯣꯕꯦꯜꯚꯦꯜ ꯏꯟꯗꯁꯇꯅꯥ ꯗꯣꯂꯔ ꯇꯂꯤꯌꯟ ꯏꯀꯣꯅꯣꯃꯤꯁꯁꯤꯡ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  48%|████████████▉              | 477/1000 [07:41<05:52,  1.48it/s]

[477/1000]
EN: Travel and tourism accounts for ten percent of global GDP.
MT: ꯂꯝꯀꯣꯏꯕ ꯑꯃꯁꯨꯡ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯃꯥꯂꯦꯝꯒꯤ ꯖꯤꯗꯤꯄꯤꯗꯥ ꯆꯥꯗ ꯇꯔꯥ ꯑꯣꯏ
--------------------------------------------------

Translating:  48%|████████████▉              | 478/1000 [07:42<06:10,  1.41it/s]

[478/1000]
EN: Vietnam targets 22 to 26 million international visitors by 2026.
MT: ꯚꯤꯇꯦꯝꯅꯥ ꯏꯪꯁꯣꯛ 2026 ꯐꯥꯎꯕꯗ ꯃꯥꯂꯦꯝꯒꯤ ꯑꯣꯏꯕ ꯂꯝꯀꯣꯏꯕ ꯃꯤꯌꯣꯏꯗꯒꯤ ꯐꯥꯎꯕ ꯂꯥꯛꯀꯗꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  48%|████████████▉              | 479/1000 [07:43<06:32,  1.33it/s]

[479/1000]
EN: Belgium citizens enjoy forty-five day visa-free Vietnam travel.
MT: ꯕꯦꯂꯖꯤꯌꯝꯒꯤ ꯃꯤꯌꯣꯏꯁꯤꯡꯅ ꯅꯨꯃꯤꯠ ꯃꯔꯤ - ꯃꯉꯥꯅꯤꯒꯤ ꯚꯤꯖꯥ ꯌꯥꯎꯗꯕꯥ ꯚꯤꯇꯦꯝ ꯇꯚꯦꯜꯒꯤ ꯅꯨꯡꯉꯥꯏꯕꯥ ꯐꯪ
--------------------------------------------------

Translating:  48%|████████████▉              | 480/1000 [07:44<06:30,  1.33it/s]

[480/1000]
EN: Poland nationals receive visa-free entry to Vietnam under new scheme.
MT: ꯄꯣꯂꯦꯟꯗ ꯅꯦꯁꯇꯤꯅꯦꯁꯟꯅ ꯚꯤꯇꯦꯅꯥꯝꯗꯥ ꯑꯅꯧꯕꯀꯤꯝ ꯃꯈꯥꯗ ꯚꯤꯖꯥ-ꯐ ꯑꯦꯟꯔꯤ ꯐꯪ
--------------------------------------------------

Translating:  48%|████████████▉              | 481/1000 [07:44<06:22,  1.36it/s]

[481/1000]
EN: Swiss passport holders travel visa-free to Vietnam for forty-five days.
MT: ꯁ ꯄꯥꯁꯄꯣꯔꯇ ꯂꯩꯕ ꯃꯤꯑꯣꯏꯁꯤꯡꯅ ꯚꯤꯇꯦꯅꯥꯝꯗꯥ ꯅꯨꯃꯤꯠ ꯃꯔꯤ - ꯃꯉꯥꯅꯤ ꯚꯤꯖꯥ ꯌꯥꯎꯗꯅ ꯆꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  48%|█████████████              | 482/1000 [07:45<06:05,  1.42it/s]

[482/1000]
EN: Saudi Red Sea Authority issues twelve marine tourism licences.
MT: ꯁꯧꯗꯤ ꯔꯦꯗ ꯁꯤ ꯑꯣꯊꯣꯔꯤꯇꯤꯅꯥ ꯃꯦꯔꯤꯅ ꯇꯨꯔꯤꯖꯝ ꯂꯥꯏꯁꯦꯟꯁ ꯇꯔꯥꯃꯥꯖ ꯄꯤ
--------------------------------------------------

Translating:  48%|█████████████              | 483/1000 [07:46<05:40,  1.52it/s]

[483/1000]
EN: Red Sea Cruises receives approval under Cruise Saudi brand.
MT: ꯁꯥꯎꯗꯤ ꯕꯦꯟꯗꯀꯤ ꯃꯈꯥꯗ ꯔꯦꯗ ꯁꯤ ꯀꯨꯏꯖꯁꯅ ꯑꯌꯥꯕ ꯐꯪ
--------------------------------------------------

Translating:  48%|█████████████              | 484/1000 [07:46<05:46,  1.49it/s]

[484/1000]
EN: Sindalah Marina in NEOM secures Saudi marine tourism licence.
MT: ꯅꯤꯑꯣꯑꯦꯝꯗꯥ ꯂꯩꯕ ꯁꯤꯟꯗꯂꯥꯍ ꯃꯦꯔꯤꯅꯥꯅꯥ ꯁꯧꯗꯤ ꯃꯦꯔꯤꯅ ꯇꯨꯔꯤꯖꯝ ꯂꯥꯏꯁꯦꯟꯁ ꯐꯪ
--------------------------------------------------

Translating:  48%|█████████████              | 485/1000 [07:47<05:57,  1.44it/s]

[485/1000]
EN: Dolphin Beach Resort Marina obtains Yanbu operating approval.
MT: ꯗꯣꯜꯐꯤꯅ ꯕꯤꯆ ꯔꯤꯖꯣꯔꯇ ꯃꯦꯔꯤꯅꯥꯗꯥ ꯌꯥꯟꯕꯨ ꯑꯣꯄꯔꯦꯇꯤꯡ ꯑꯦꯄꯂꯨꯑꯦꯁꯟ ꯐꯪ
--------------------------------------------------

Translating:  49%|█████████████              | 486/1000 [07:48<05:59,  1.43it/s]

[486/1000]
EN: Jeddah Municipality Marina included in Saudi licensing round.
MT: ꯖꯦꯗꯥꯍ ꯃꯅꯤꯁꯤꯄꯥꯂꯤꯇꯤ ꯃꯦꯔꯤꯅꯥ ꯑꯁꯤ ꯁꯥꯎꯗꯤ ꯂꯥꯏꯁꯦꯟꯁꯤꯡ ꯔꯥꯎꯟꯗꯗꯥ ꯌꯥꯎ
--------------------------------------------------

Translating:  49%|█████████████▏             | 487/1000 [07:48<05:58,  1.43it/s]

[487/1000]
EN: Deep Seas Shipping Agency gains tourism shipping agent licence.
MT: ꯗꯤꯄ ꯁꯤꯖ ꯁꯤꯞꯄꯤꯡ ꯑꯦꯖꯦꯟꯁꯤꯅ ꯇꯨꯔꯤꯖꯝ ꯁꯤꯞꯇ ꯑꯦꯖꯦꯟꯇ ꯂꯥꯏꯁꯦꯟꯁ ꯐꯪ
--------------------------------------------------

Translating:  49%|█████████████▏             | 488/1000 [07:49<05:45,  1.48it/s]

[488/1000]
EN: Venice extends day-tripper entrance fee to sixty days.
MT: ꯋꯦꯅꯤꯁꯅꯥ ꯗꯦ-ꯥꯏꯄꯔ ꯑꯦꯟꯇꯔꯦꯟꯁ ꯐꯤ ꯑꯁꯤ ꯅꯨꯃꯤꯠ ꯆꯥꯗꯥ ꯍꯦꯟꯒꯠ
--------------------------------------------------

Translating:  49%|█████████████▏             | 489/1000 [07:50<06:15,  1.36it/s]

[489/1000]
EN: Venice charges day-trippers from Friday to Sunday between April and July.
MT: ꯚꯤꯅꯤꯁꯅꯥ ꯑꯦꯄꯜ ꯑꯃꯁꯨꯡ ꯖꯨꯂꯥꯏꯒꯤ ꯃꯔꯛꯇ ꯁꯨꯈ ꯅꯨꯃꯤꯠꯇꯗꯒꯤ ꯅꯣꯡꯃꯥꯏꯖꯤꯡ ꯐꯥꯎꯕ ꯗꯦ-ꯇꯄꯤꯄꯔꯁꯤꯡ ꯂꯧꯏ ꯫
--------------------------------------------------

Translating:  49%|█████████████▏             | 490/1000 [07:51<06:17,  1.35it/s]

[490/1000]
EN: Simone Venturini calls Venice entry fee tangible innovation tool.
MT: ꯁꯤꯃꯣꯟ ꯚꯦꯟꯇꯨꯔꯤꯅꯤꯅ ꯚꯦꯅꯤꯁ ꯑꯦꯟ ꯐꯤ ꯇꯦꯟꯖꯤꯕꯜ ꯏꯟꯅꯣꯚꯦꯁꯟ ꯇꯨꯜ ꯍꯥꯏꯅ ꯀꯧ
--------------------------------------------------

Translating:  49%|█████████████▎             | 491/1000 [07:52<06:27,  1.31it/s]

[491/1000]
EN: Amsterdam introduces tourist fees to fight overtourism congestion.
MT: ꯑꯝꯁꯇꯔꯗꯝꯅꯥ ꯑꯣꯚꯔꯇꯨꯔꯤꯖꯝ ꯀꯟꯖꯦꯁꯟ ꯊꯦꯡꯅꯅꯕ ꯇꯨꯔꯤꯁꯇ ꯐꯤ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  49%|█████████████▎             | 492/1000 [07:52<06:07,  1.38it/s]

[492/1000]
EN: Greece passes laws limiting visitor numbers to popular islands.
MT: ꯒꯅꯥ ꯃꯤꯌꯥꯝꯅ ꯄꯥꯝꯅꯕ ꯏꯊꯠꯁꯤꯡ ꯑꯁꯤꯗ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯃꯁꯤꯡ ꯍꯟꯊꯍꯟꯅꯕ ꯑꯥꯏꯟꯁꯤꯡ ꯆꯠꯅꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  49%|█████████████▎             | 493/1000 [07:53<05:45,  1.47it/s]

[493/1000]
EN: Japan implements tourist fees to manage overcrowding at sites.
MT: ꯖꯄꯥꯟꯅꯥ ꯁꯥꯏꯇꯁꯤꯡꯗ ꯃꯤ ꯌꯥꯝꯅ ꯇꯤꯟꯕ ꯂꯥꯛꯅꯕꯒꯤꯗꯃꯛ ꯇꯨꯔꯤꯁꯇ ꯐꯤꯁꯤꯡ ꯆꯠꯅꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  49%|█████████████▎             | 494/1000 [07:54<05:59,  1.41it/s]

[494/1000]
EN: Hurricane Melissa devastates Jamaica's tourism infrastructure.
MT: ꯍꯔꯤꯀꯦꯟ ꯃꯦꯂꯤꯁꯥꯅꯥ ꯖꯃꯥꯏꯀꯥꯒꯤ ꯇꯨꯔꯤꯖꯝ ꯏꯟꯐꯁꯇꯛꯆꯔ ꯃꯥꯡꯍꯟ ꯇꯥꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  50%|█████████████▎             | 495/1000 [07:54<06:00,  1.40it/s]

[495/1000]
EN: Jamaica opens for business after Hurricane Melissa recovery.
MT: ꯖꯃꯥꯏꯀꯥ ꯑꯁꯤ ꯍꯔꯤꯀꯦꯟ ꯃꯦꯂꯤꯁꯥ ꯔꯤꯀꯥꯎꯔꯤꯒꯤ ꯃꯇꯨꯡꯗ ꯂꯂꯣꯟ-ꯎꯕꯒꯤꯗꯃꯛꯇ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  50%|█████████████▍             | 496/1000 [07:55<05:25,  1.55it/s]

[496/1000]
EN: Canadian visitation to United States continues to plummet.
MT: ꯌꯨꯅꯥꯏꯇꯦꯗꯇꯥ ꯀꯦꯅꯥꯗꯥꯒꯤ ꯈꯣꯡꯆꯠ ꯑꯁꯤ ꯃꯈꯥ ꯇꯥꯅ ꯍꯟꯊꯔꯛ
--------------------------------------------------

Translating:  50%|█████████████▍             | 497/1000 [07:55<05:19,  1.57it/s]

[497/1000]
EN: Sean Duffy focuses on America's ailing air travel system.
MT: ꯁꯤꯅ ꯗꯐꯤꯅꯥ ꯑꯃꯦꯔꯤꯀꯥꯒꯤ ꯂꯥꯏꯔꯕ ꯑꯦꯔꯚꯦꯜ ꯁꯤꯁꯇꯦꯝꯗꯥ ꯃꯤꯠꯌꯦꯡ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  50%|█████████████▍             | 498/1000 [07:56<05:55,  1.41it/s]

[498/1000]
EN: Trump administration policies impact travel both positively and negatively.
MT: ꯇꯝꯞ ꯑꯦꯗꯃꯤꯅꯤꯁꯇꯦꯁꯟꯒꯤ ꯄꯣꯂꯤꯁꯤꯁꯤꯡꯅ ꯄꯣꯖꯤꯇꯤꯕ ꯑꯃꯁꯨꯡ ꯅꯦꯒꯦꯇꯤꯕ ꯑꯅꯤꯃꯛꯀꯤ ꯑꯣꯏꯕ ꯂꯝꯀꯣꯏꯕꯒꯤ ꯏꯊꯤꯜ ꯄꯤ ꯫
--------------------------------------------------

Translating:  50%|█████████████▍             | 499/1000 [07:57<05:59,  1.40it/s]

[499/1000]
EN: Sri Lanka regime change attributed to poor governance by Ajit Doval.
MT: ꯂꯡꯀꯥꯒꯤ ꯂꯩꯉꯥꯛ ꯍꯣꯡꯂꯛꯄꯥ ꯑꯁꯤ ꯑꯖꯤꯠ ꯗꯣꯚꯜꯒꯤ ꯂꯥꯏꯔꯕ ꯒꯕꯔꯅꯦꯟꯁꯅꯥ ꯃꯔꯝ ꯑꯣꯏ
--------------------------------------------------

Translating:  50%|█████████████▌             | 500/1000 [07:58<05:55,  1.41it/s]

[500/1000]
EN: Bangladesh leadership transition results from poor governance failures.
MT: ꯕꯪꯒꯂꯥꯗꯦꯁꯀꯤ ꯂꯨꯆꯤꯡꯕꯒꯤ ꯍꯣꯡꯗꯣꯛꯄꯒꯤ ꯃꯍꯩ ꯑꯁꯤ ꯂꯥꯏꯔꯕ ꯒꯕꯔꯅꯦꯟꯁ ꯃꯥꯏꯊꯤꯕꯥꯁꯤꯡꯗꯒꯤꯅꯤ ꯫
--------------------------------------------------

Translating:  50%|█████████████▌             | 501/1000 [07:58<05:51,  1.42it/s]

[501/1000]
EN: Nepal government change linked to governance issues says Doval.
MT: ꯅꯦꯄꯥꯜ ꯁꯔꯀꯥꯔꯅꯥ ꯒꯕꯔꯅꯦꯟꯁ ꯏꯁꯁꯤꯡꯒ ꯃꯔꯤ ꯂꯩꯅꯅ ꯍꯣꯡꯂꯛꯏ ꯍꯥꯏꯅ ꯗꯣꯚꯥꯂꯅꯥ ꯍꯥꯏ ꯫
--------------------------------------------------

Translating:  50%|█████████████▌             | 502/1000 [07:59<05:58,  1.39it/s]

[502/1000]
EN: Thailand launches five year multiple entry tourist visa scheme.
MT: ꯊꯥꯏꯂꯦꯟꯗꯅꯥ ꯆꯍꯤ ꯃꯉꯥꯒꯤ ꯃꯜꯇꯤꯄꯜ ꯑꯦꯟꯇ ꯇꯨꯔꯤꯁꯇ ꯚꯤꯖꯥꯀꯤꯝ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  50%|█████████████▌             | 503/1000 [08:00<05:33,  1.49it/s]

[503/1000]
EN: Sri Lanka grants free visa to seven countries including India.
MT: ꯁꯔꯤꯂꯪꯀꯥꯅꯥ ꯚꯥꯔꯠ ꯌꯥꯎꯅ ꯂꯩꯕꯥꯛ 7ꯇꯥ ꯐ ꯚꯤꯖꯥ ꯄꯤ ꯫
--------------------------------------------------

Translating:  50%|█████████████▌             | 504/1000 [08:00<05:54,  1.40it/s]

[504/1000]
EN: Maldives lifts emergency but tourism recovery remains sluggish.
MT: ꯃꯜꯗꯤꯚꯦꯁꯅ ꯏꯃꯔꯖꯦꯟꯁꯤ ꯂꯧꯊꯣꯛꯈꯤ ꯑꯗꯨꯕꯨ ꯇꯨꯔꯤꯖꯝ ꯔꯤꯀꯥꯎꯔꯤ ꯑꯁꯤ ꯁꯣꯠꯊ
--------------------------------------------------

Translating:  50%|█████████████▋             | 505/1000 [08:01<05:51,  1.41it/s]

[505/1000]
EN: UAE announces five year multiple entry visa for Indian nationals.
MT: ꯌꯨ ꯑꯦ ꯏ ꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯅꯦꯁ ꯭ ꯅꯦꯜꯁꯤꯡꯒꯤꯗꯃꯛ ꯆꯍꯤ ꯃꯉꯥꯒꯤ ꯃꯜꯇꯤꯄꯜ ꯑꯦꯟꯇꯤ ꯚꯤꯖꯥ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  51%|█████████████▋             | 506/1000 [08:02<05:45,  1.43it/s]

[506/1000]
EN: Schengen visa fees increase from eighty to ninety Euros globally.
MT: ꯁꯆꯦꯟꯖꯦꯟ ꯚꯤꯖꯥ ꯐꯤ ꯑꯁꯤ ꯃꯥꯂꯦꯝ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯌꯨꯔꯣ 80ꯗꯒꯤ 90 ꯐꯥꯎꯕ ꯍꯦꯟꯒꯠ
--------------------------------------------------

Translating:  51%|█████████████▋             | 507/1000 [08:03<05:54,  1.39it/s]

[507/1000]
EN: Japan resumes short term tourist visa processing for Indians.
MT: ꯖꯄꯥꯟꯅꯥ ꯚꯥꯔꯠ ꯃꯆꯥꯁꯤꯡꯒꯤꯗꯃꯛ ꯃꯇꯝ ꯈꯔꯒꯤ ꯑꯣꯏꯕ ꯇꯨꯔꯤꯁꯇ ꯚꯤꯖꯥꯁꯦꯁꯡ ꯑꯃꯨꯛ ꯍꯟꯅ ꯍꯧ
--------------------------------------------------

Translating:  51%|█████████████▋             | 508/1000 [08:03<06:00,  1.37it/s]

[508/1000]
EN: India operates 127 airports with ten new cruise terminals.
MT: ꯚꯥꯔꯠꯇꯥ ꯑꯦꯔꯄꯣꯔꯇ ꯑꯁꯤ ꯑꯅꯧꯕ ꯀꯖ ꯇꯔꯃꯤꯅꯦꯜ ꯇꯔꯥꯒꯥ ꯂꯣꯏꯅꯅ ꯑꯣꯄꯔꯦꯇ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  51%|█████████████▋             | 509/1000 [08:04<05:20,  1.53it/s]

[509/1000]
EN: Government constructs 150,000 kilometres of new national highways.
MT: ꯁꯔꯀꯥꯔꯅꯥ ꯑꯅꯧꯕ ꯅꯦꯁꯅꯦꯜ ꯍꯥꯏꯋꯦꯁꯤꯡꯒꯤ ꯀꯤꯂꯣꯃꯤꯇꯔ 150,000 ꯁꯦꯝꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  51%|█████████████▊             | 510/1000 [08:04<05:17,  1.54it/s]

[510/1000]
EN: India develops 38 national waterways for inland cruise tourism.
MT: ꯏꯟꯗꯤꯌꯥꯅꯥ ꯏꯟꯂꯦꯟꯗ ꯀꯖ ꯇꯨꯔꯤꯖꯝꯒꯤꯗꯃꯛ ꯅꯦꯁꯅꯦꯜ ꯋꯥꯇꯔꯋꯦ 38 ꯁꯦꯝꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  51%|█████████████▊             | 511/1000 [08:05<05:19,  1.53it/s]

[511/1000]
EN: Metro rail network expands 10,000 kilometres across 23 cities.
MT: ꯃꯦꯇ ꯔꯦꯜ ꯅꯦꯠꯋꯥꯔꯛꯅꯥ ꯁꯍꯔ 23ꯗꯥ ꯀꯤꯂꯣꯃꯤꯇꯔ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  51%|█████████████▊             | 512/1000 [08:06<05:04,  1.60it/s]

[512/1000]
EN: Swadesh Darshan 2.0 develops tourism sites to global standards.
MT: ꯋꯥꯗꯦꯁ ꯗꯔꯁꯟ 2.ꯅ ꯂꯝꯀꯣꯏꯕꯒꯤ ꯃꯐꯝꯁꯤꯡꯕꯨ ꯃꯥꯂꯦꯝꯒꯤ ꯊꯥꯛꯇ ꯁꯦꯝꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  51%|█████████████▊             | 513/1000 [08:07<05:36,  1.45it/s]

[513/1000]
EN: PRASHAD scheme enhances pilgrimage tourism infrastructure across India.
MT: ꯄꯁꯥꯗꯀꯤꯝꯅꯥ ꯚꯥꯔꯠ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯊꯔꯤꯊꯝ ꯇꯨꯔꯤꯖꯝ ꯏꯟꯐꯁꯇꯛꯆꯔ ꯍꯦꯟꯒꯠꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  51%|█████████████▉             | 514/1000 [08:07<05:49,  1.39it/s]

[514/1000]
EN: Saudi Red Sea authority enforces international safety standards for marine tourism.
MT: ꯁꯧꯗꯤ ꯔꯦꯗ ꯁꯤ ꯑꯣꯊꯣꯔꯤꯇꯤꯅꯥ ꯃꯦꯔꯤꯅ ꯇꯨꯔꯤꯖꯝꯒꯤꯗꯃꯛ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯁꯦꯐꯇꯤꯦꯟꯗꯗꯔꯁꯤꯡ ꯆꯠꯅꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  52%|█████████████▉             | 515/1000 [08:08<05:44,  1.41it/s]

[515/1000]
EN: Saudi marine regulations protect Red Sea coral reef ecosystems.
MT: ꯁꯥꯎꯗꯤ ꯃꯦꯔꯤꯅ ꯔꯦꯒꯨꯂꯦꯁꯟꯅꯥ ꯔꯦꯗ ꯁꯤ ꯀꯣꯔꯦꯜ ꯔꯤꯐ ꯏꯀꯣꯁꯇꯤꯃꯁꯤꯡꯕꯨ ꯉꯥꯛꯁꯦꯟ
--------------------------------------------------

Translating:  52%|█████████████▉             | 516/1000 [08:09<05:37,  1.43it/s]

[516/1000]
EN: Saudi Red Sea tourism to add 85 billion riyals to GDP.
MT: ꯁꯥꯎꯗꯤ ꯔꯦꯗ ꯁꯤ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯖꯤꯗꯤꯄꯤꯗꯥ ꯔꯤꯌꯥꯜ ꯕꯤꯂꯤꯌꯟ 85 ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  52%|█████████████▉             | 517/1000 [08:09<05:15,  1.53it/s]

[517/1000]
EN: Red Sea tourism creates 210,000 Saudi jobs by 2030.
MT: ꯔꯦꯗ ꯁꯤ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯏꯪ 2030 ꯐꯥꯎꯕꯗ ꯁꯧꯗꯤꯒꯤ ꯊꯕꯛ 2,00,000 ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  52%|█████████████▉             | 518/1000 [08:10<05:09,  1.56it/s]

[518/1000]
EN: Indian Railways recovers only fraction of 4,087 crore dues.
MT: ꯏꯟꯗꯤꯌꯟ ꯔꯦꯜꯋꯦꯁꯅ ꯁꯦꯟꯐꯝ ꯀꯔꯣꯔꯒꯤ ꯁꯔꯨꯛ ꯈꯔꯈꯛꯇꯃꯛ ꯔꯤꯀꯣꯚꯔ ꯇꯧ
--------------------------------------------------

Translating:  52%|██████████████             | 519/1000 [08:11<05:32,  1.44it/s]

[519/1000]
EN: RLDA develops only fraction of railway land for commercial use.
MT: ꯑꯥꯔ. ꯑꯦꯜ. ꯗꯤ. ꯑꯦ.ꯅꯥ ꯔꯦꯜꯋꯦꯒꯤ ꯂꯝꯒꯤ ꯁꯔꯨꯛ ꯈꯔꯈꯛꯇꯃꯛ ꯂꯜꯂꯣꯟꯏꯇꯤꯛꯀꯤ ꯑꯣꯏꯅ ꯁꯤꯖꯤꯟꯅꯅꯕꯒꯤꯗꯃꯛ ꯁꯦꯝꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  52%|██████████████             | 520/1000 [08:11<05:37,  1.42it/s]

[520/1000]
EN: Central Railway announces train diversions for Dasara and Diwali.
MT: ꯁꯦꯟꯇꯦꯜ ꯔꯦꯜꯋꯦꯅꯥ ꯗꯥꯁꯥꯔꯥ ꯑꯃꯁꯨꯡ ꯗꯤꯋꯥꯂꯤꯒꯤꯗꯃꯛ ꯇꯔꯦꯟ ꯗꯥꯏꯚꯔꯁꯟꯁꯤꯡ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  52%|██████████████             | 521/1000 [08:12<06:00,  1.33it/s]

[521/1000]
EN: SCR cancels 69 trains due to operational requirements.
MT: ꯑꯣꯄꯔꯦꯁꯟꯦꯜꯒꯤ ꯃꯊꯧ ꯇꯥꯕꯒꯤ ꯃꯔꯝꯅꯥ ꯑꯦꯁ ꯁꯤ ꯑꯥꯔꯅꯥ ꯇꯦꯟ 69 ꯀꯛꯊꯠ
--------------------------------------------------

Translating:  52%|██████████████             | 522/1000 [08:13<06:44,  1.18it/s]

[522/1000]
EN: South Central Railway diverts 29 trains for festival management.
MT: ꯁꯥꯎꯊ ꯁꯦꯟꯇꯜ ꯔꯦꯜꯋꯦꯅꯥ ꯇꯦꯟ 29 ꯑꯁꯤ ꯐꯦꯁꯇꯤꯕꯦꯜ ꯃꯦꯟꯗꯃꯦꯟꯇꯒꯤꯗꯃꯛ ꯗꯥꯏꯚꯔꯠ ꯇꯧ
--------------------------------------------------

Translating:  52%|██████████████             | 523/1000 [08:14<06:26,  1.23it/s]

[523/1000]
EN: Indian Railways announces 18 partially cancelled train services.
MT: ꯏꯟꯗꯤꯌꯟ ꯔꯦꯜꯋꯦꯁꯅ ꯁꯔꯨꯛ ꯈꯔ ꯀꯛꯊꯠꯂꯕ ꯇꯔꯦꯟ ꯁꯔꯕꯤꯁ 18 ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  52%|██████████████▏            | 524/1000 [08:15<06:12,  1.28it/s]

[524/1000]
EN: Three trains rescheduled by South Central Railway authority.
MT: ꯁꯥꯎꯊ ꯁꯦꯟꯦꯜ ꯔꯦꯜꯋꯦ ꯑꯣꯊꯣꯔꯤꯇꯤꯅꯥ ꯇꯦꯟ ꯑꯍꯨꯝ ꯑꯃꯨꯛ ꯍꯟꯅ ꯁꯦꯗꯜ ꯇꯧ
--------------------------------------------------

Translating:  52%|██████████████▏            | 525/1000 [08:15<05:38,  1.40it/s]

[525/1000]
EN: SCR cancels total 119 train services during peak season.
MT: ꯑꯦꯁ ꯁꯤ ꯑꯥꯔꯅꯥ ꯄꯤꯛ ꯁꯤꯖꯟ ꯃꯇꯝꯗ ꯑꯄꯨꯟꯕꯦꯟ ꯁꯔꯕꯤꯁ 119 ꯀꯛꯁꯤꯟ
--------------------------------------------------

Translating:  53%|██████████████▏            | 526/1000 [08:16<05:52,  1.34it/s]

[526/1000]
EN: Disney Cruise Line debuts Disney Destiny vessel in 2025.
MT: ꯏꯪꯁꯣꯛ 2025 ꯗꯥ ꯗꯤꯁꯅꯤ ꯀꯎꯏꯖ ꯂꯥꯏꯟꯅꯥ ꯗꯤꯖꯅꯤ ꯗꯦꯁꯇꯤꯅꯤ ꯚꯦꯁꯦꯜ ꯑꯁꯤ ꯍꯧꯒꯠꯂꯦ ꯫
--------------------------------------------------

Translating:  53%|██████████████▏            | 527/1000 [08:17<05:42,  1.38it/s]

[527/1000]
EN: Norwegian Cruise Line adds Norwegian Aqua to fleet.
MT: ꯅꯣꯔꯚꯦꯒꯤ ꯀꯎꯖ ꯂꯥꯏꯟꯅ ꯅꯣꯔꯕꯦꯒꯤ ꯑꯦꯀꯋꯥ ꯑꯁꯤ ꯐꯂꯤꯠꯇꯥ ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  53%|██████████████▎            | 528/1000 [08:17<05:23,  1.46it/s]

[528/1000]
EN: Royal Caribbean launches Star of the Seas cruise ship.
MT: ꯔꯣꯌꯦꯜ ꯀꯦꯔꯤꯕꯥꯌꯟꯅꯥ ꯁꯥꯔ ꯑꯣꯐ ꯗꯤ ꯁꯤꯖ ꯀꯖ ꯁꯤꯞ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  53%|██████████████▎            | 529/1000 [08:18<05:44,  1.37it/s]

[529/1000]
EN: Varanasi airport expands terminal to handle five million passengers.
MT: ꯕꯥꯔꯥꯅꯥꯁꯤ ꯑꯦꯌꯔꯄꯣꯔꯇꯅꯥ ꯇꯔꯃꯅꯦꯜ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯗꯨꯅ ꯄꯦꯁꯦꯟꯖꯔ ꯃꯤꯌꯣꯏ ꯂꯥꯈ ꯃꯉꯥ ꯍꯦꯟꯗꯜ ꯇꯧ
--------------------------------------------------

Translating:  53%|██████████████▎            | 530/1000 [08:19<05:46,  1.36it/s]

[530/1000]
EN: Kashmir Railway line reaches Baramulla for all weather connectivity.
MT: ꯀꯁꯃꯤꯔ ꯔꯦꯜꯋꯦ ꯂꯥꯏꯟꯅꯥ ꯕꯥꯔꯥꯃꯨꯂꯥꯗꯥ ꯑꯏꯪ-ꯑꯁꯥ ꯄꯨꯝꯅꯃꯛ ꯁꯝꯅꯕꯒꯤꯗꯃꯛ ꯌꯧꯏ ꯫
--------------------------------------------------

Translating:  53%|██████████████▎            | 531/1000 [08:20<05:46,  1.35it/s]

[531/1000]
EN: Ayodhya airport commences commercial flight operations for pilgrims.
MT: ꯑꯥꯌꯣꯙ ꯑꯦꯌꯔꯄꯣꯔꯇꯅꯥ ꯊꯍꯤꯠꯁꯤꯡꯒꯤꯗꯃꯛꯇ ꯀꯝꯃꯔꯁꯦꯜ ꯐꯥꯏꯇ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡ ꯍꯧ
--------------------------------------------------

Translating:  53%|██████████████▎            | 532/1000 [08:20<05:31,  1.41it/s]

[532/1000]
EN: Chennai metro phase two extension connects airport to city centre.
MT: ꯆꯦꯟꯅꯥꯏ ꯃꯦꯇ ꯐꯦꯖ ꯑꯅꯤꯒꯤ ꯑꯦꯛꯁꯇꯦꯟꯁꯟꯅꯥ ꯑꯦꯌꯔꯄꯣꯔꯇ ꯑꯁꯤ ꯁꯤꯇꯤ ꯁꯦꯟꯇꯔꯒꯥ ꯁꯝꯅꯩ ꯫
--------------------------------------------------

Translating:  53%|██████████████▍            | 533/1000 [08:21<05:33,  1.40it/s]

[533/1000]
EN: Mumbai Trans Harbour Link reduces travel time to Navi Mumbai airport.
MT: ꯃꯨꯝꯕꯥꯏ ꯇ ꯭ ꯔꯥꯟꯁ ꯍꯔꯕꯔ ꯂꯤꯡꯀꯅꯥ ꯅꯚꯤ ꯑꯦꯌꯔꯄꯣꯔꯇꯇꯥ ꯆꯠꯄꯒꯤ ꯃꯇꯝ ꯍꯟꯊꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  53%|██████████████▍            | 534/1000 [08:22<05:36,  1.38it/s]

[534/1000]
EN: Kashi Vishwanath corridor transforms pilgrimage experience in Varanasi.
MT: ꯀꯥꯁꯤ ꯕꯤꯁ ꯭ ꯋꯅꯥꯊ ꯀꯣꯔꯤꯗꯣꯔꯅꯥ ꯕꯥꯔꯥꯅꯁꯤꯒꯤ ꯂꯥꯏꯐꯝ ꯆꯠꯄꯒꯤ ꯃꯋꯣꯡ ꯍꯣꯡꯍꯟ
--------------------------------------------------

Translating:  54%|██████████████▍            | 535/1000 [08:22<05:23,  1.44it/s]

[535/1000]
EN: Hyatt completes acquisition of Playa Hotels and Resorts.
MT: ꯍꯌꯥꯇꯅꯥ ꯄꯌꯥ ꯍꯣꯇꯦꯜ ꯑꯃꯁꯨꯡ ꯔꯤꯖꯣꯔꯇꯁꯤꯡ ꯂꯧꯁꯤꯟꯕ ꯂꯣꯏꯔꯦ ꯫
--------------------------------------------------

Translating:  54%|██████████████▍            | 536/1000 [08:23<05:46,  1.34it/s]

[536/1000]
EN: Hyatt adds fifteen beachfront properties across Mexico and Jamaica.
MT: ꯍꯌꯥꯇꯅꯥ ꯃꯦꯛꯁꯤꯀꯣ ꯑꯃꯁꯨꯡ ꯖꯃꯥꯏꯀꯥ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯕꯤꯆ ꯐꯟꯇꯄꯥꯔꯇꯤꯁꯤꯡ ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  54%|██████████████▍            | 537/1000 [08:24<05:36,  1.37it/s]

[537/1000]
EN: Hyatt acquires Secrets La Romana in Dominican Republic.
MT: ꯍꯌꯥꯇꯅꯥ ꯗꯣꯃꯤꯅꯤꯀꯥꯟ ꯔꯤꯄꯕꯂꯤꯛꯀꯤ ꯁꯦꯀꯇ ꯂꯥ ꯔꯣꯃꯥꯅꯥ ꯂꯧ
--------------------------------------------------

Translating:  54%|██████████████▌            | 538/1000 [08:25<05:52,  1.31it/s]

[538/1000]
EN: Dreams La Romana joins Hyatt portfolio through Playa acquisition.
MT: ꯗꯃꯤꯁ ꯂꯥ ꯔꯣꯃꯥꯅꯥꯅꯥꯂꯥꯌꯥ ꯑꯦꯀꯚꯤꯖꯦꯁꯟꯒꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯍꯌꯥꯇ ꯄꯣꯔꯇꯤꯐꯣꯂꯤꯑꯣꯗꯥ ꯌꯥꯎ
--------------------------------------------------

Translating:  54%|██████████████▌            | 539/1000 [08:26<06:04,  1.26it/s]

[539/1000]
EN: Dreams Rose Hall in Montego Bay transfers to Hyatt ownership.
MT: ꯃꯣꯟꯇꯦꯒꯣ ꯕꯦꯗꯥ ꯂꯩꯕ ꯗꯃꯤꯁ ꯔꯣꯖ ꯍꯣꯜ ꯑꯁꯤ ꯍꯌꯥꯇ ꯑꯣꯅꯣꯔꯁꯤꯌꯦꯟꯁꯤꯇꯥ ꯍꯣꯡꯗꯣꯛ
--------------------------------------------------

Translating:  54%|██████████████▌            | 540/1000 [08:26<05:56,  1.29it/s]

[540/1000]
EN: Hyatt Vivid Playa del Carmen added to hotel collection.
MT: ꯍꯌꯥꯇ ꯚꯤꯚꯤꯗꯂꯥꯌ ꯗꯦꯜ ꯀꯥꯔꯃꯦꯅ ꯑꯁꯤ ꯍꯣꯇꯦꯜ ꯀꯂꯦꯀꯦꯁꯟꯗ ꯌꯥꯎꯍꯟ
--------------------------------------------------

Translating:  54%|██████████████▌            | 541/1000 [08:27<05:48,  1.32it/s]

[541/1000]
EN: Sunscape Cancun becomes Hyatt property after Playa deal.
MT: ꯁꯟꯁꯀꯦꯞ ꯀꯦꯟꯀꯟ ꯑꯁꯤꯌꯥ ꯗꯤꯜꯒꯤ ꯃꯇꯨꯡꯗ ꯍꯌꯥꯇꯄꯣꯔꯇꯤ ꯑꯣꯏꯔꯦ ꯫
--------------------------------------------------

Translating:  54%|██████████████▋            | 542/1000 [08:28<06:10,  1.24it/s]

[542/1000]
EN: Hotel infrastructure status unlocks private investment says Shekhawat.
MT: ꯁꯦꯈꯥꯋꯥꯠꯅ ꯍꯥꯏ ꯃꯗꯨꯗꯤ ꯍꯣꯇꯦꯜ ꯏꯟꯐꯁꯇꯛꯆꯔꯇꯦꯁꯁꯅꯥꯏꯚꯦꯠ ꯏꯟꯚꯦꯁꯇꯃꯦꯟꯇ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  54%|██████████████▋            | 543/1000 [08:29<06:03,  1.26it/s]

[543/1000]
EN: FICCI annual general meeting discusses tourism growth strategy.
MT: ꯐꯤꯆꯤꯒꯤ ꯆꯍꯤꯒꯤ ꯃꯤꯐꯝꯗꯥ ꯇꯨꯔꯤꯖꯝ ꯒꯊꯇꯦꯖꯤꯒꯤ ꯃꯇꯥꯡꯗ ꯈꯟꯅꯩ ꯫
--------------------------------------------------

Translating:  54%|██████████████▋            | 544/1000 [08:30<06:07,  1.24it/s]

[544/1000]
EN: Harsh Vardhan Agarwal highlights tourism as economic driver.
MT: ꯍꯔꯁ ꯕꯔꯙꯟ ꯑꯒꯔꯋꯥꯜꯅ ꯇꯨꯔꯤꯖꯝꯕꯨ ꯁꯦꯟꯊꯨꯝꯒꯤ ꯗꯥꯏꯚꯔ ꯑꯣꯏꯅ ꯃꯁꯛ ꯇꯥꯛ
--------------------------------------------------

Translating:  55%|██████████████▋            | 545/1000 [08:31<06:07,  1.24it/s]

[545/1000]
EN: Anant Goenka praises Swadesh Darshan and PRASHAD initiatives.
MT: ꯑꯅꯟꯇ ꯒꯣꯌꯟꯀꯥꯅꯥꯋꯥꯗꯦꯁ ꯗꯔꯁꯟ ꯑꯃꯁꯨꯡꯁꯥꯗ ꯏꯅꯤꯁꯤꯌꯦꯇꯤꯕꯁꯤꯡ ꯊꯥꯒꯠ
--------------------------------------------------

Translating:  55%|██████████████▋            | 546/1000 [08:31<06:13,  1.22it/s]

[546/1000]
EN: Indian hotel industry seeks infrastructure status for tax benefits.
MT: ꯚꯥꯔꯠꯀꯤ ꯍꯣꯇꯦꯜ ꯏꯟꯗꯁꯇꯅꯥ ꯇꯦꯛꯁ ꯕꯦꯅꯤꯐꯤꯇꯁꯤꯡꯒꯤꯗꯃꯛ ꯏꯟꯐꯁꯇ ꯭ ꯔꯛꯆꯔꯇꯦꯁ ꯊꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  55%|██████████████▊            | 547/1000 [08:32<06:25,  1.18it/s]

[547/1000]
EN: Shangri-La Bengaluru hosts Chef Simone Loisi Italian culinary residency.
MT: ꯁꯥꯟꯒꯔꯤ-ꯂꯥ ꯕꯦꯡꯂꯨꯔꯥꯅꯥ ꯁꯦꯐ ꯁꯤꯃꯣꯅꯦ ꯂꯣꯏꯁꯤ ꯏꯇꯥꯂꯤꯌꯟꯒꯤ ꯆꯤꯛꯅꯤꯔꯤ ꯔꯦꯁꯤꯗꯦꯟꯁꯤ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  55%|██████████████▊            | 548/1000 [08:33<05:59,  1.26it/s]

[548/1000]
EN: Chef Simone Loisi brings Southern Italian cuisine to Bangalore.
MT: ꯁꯦꯐ ꯁꯤꯃꯣꯅꯦ ꯂꯣꯏꯁꯤꯅꯥ ꯈꯥ ꯊꯪꯕ ꯏꯇꯥꯂꯤꯒꯤ ꯆꯤꯟꯖꯥꯛꯁꯤꯡ ꯕꯦꯡꯒꯂꯣꯔꯗꯥ ꯄꯨꯔꯛ
--------------------------------------------------

Translating:  55%|██████████████▊            | 549/1000 [08:34<05:50,  1.29it/s]

[549/1000]
EN: Waterfall Ristorante Italiano chef showcases cuisine at Shangri-La.
MT: ꯋꯥꯇꯔꯐꯣꯜ ꯔꯤꯁꯇꯣꯔꯥꯟꯇꯦ ꯏꯇꯥꯂꯤꯌꯣ ꯁꯦꯐꯅꯥ ꯁꯥꯡ-ꯂꯥꯗꯥ ꯆꯤꯟꯖꯥꯛꯁꯤꯡ ꯎꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  55%|██████████████▊            | 550/1000 [08:35<05:59,  1.25it/s]

[550/1000]
EN: Four Seasons Bengaluru transforms for Halloween 2025 celebrations.
MT: ꯏꯪꯁꯣꯛ 2025 ꯒꯤ ꯍꯦꯂꯣꯋꯤꯟꯒꯤꯗꯃꯛ ꯁꯤꯖꯟꯁ ꯃꯔꯤ ꯕꯦꯡꯒꯂꯨꯔꯨ ꯇ ꯭ ꯔꯥꯟꯁꯐꯣꯔꯝ ꯇꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  55%|██████████████▉            | 551/1000 [08:35<06:07,  1.22it/s]

[551/1000]
EN: CUR8 hosts family friendly Halloween evening in Bengaluru.
MT: ꯁꯤꯌꯨ ꯑꯥꯔ8ꯅꯥ ꯕꯦꯡꯂꯨꯨꯔꯨꯗ ꯏꯃꯨꯡ ꯃꯅꯨꯡ ꯐꯦꯟꯗꯂꯤ ꯍꯦꯂꯣꯋꯤꯟꯒꯤ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯊꯧꯔꯝ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  55%|██████████████▉            | 552/1000 [08:36<05:38,  1.32it/s]

[552/1000]
EN: Copitas bar ranks in Asia's 50 Best Bars list.
MT: ꯀꯣꯄꯤꯇꯥꯁ ꯕꯥꯔ ꯑꯁꯤ ꯑꯦꯁꯤꯌꯥꯒꯤ ꯐꯕ ꯕꯥꯔꯁꯀꯤ ꯂꯤꯁꯠꯗꯥ
--------------------------------------------------

Translating:  55%|██████████████▉            | 553/1000 [08:37<05:39,  1.32it/s]

[553/1000]
EN: Four Seasons Bengaluru hosts Día de Muertos Halloween party.
MT: ꯁꯤꯖꯟꯁ ꯃꯔꯤ ꯕꯦꯡꯂꯨꯨꯔꯥꯅꯥ ꯗꯤꯌꯥ ꯗꯦ ꯃꯨꯔꯇꯣꯁ ꯍꯦꯂꯣꯋꯤꯅ ꯄꯥꯔꯇꯤ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  55%|██████████████▉            | 554/1000 [08:38<05:41,  1.30it/s]

[554/1000]
EN: Sheraton Hyderabad invites guests to Feast Halloween buffet.
MT: ꯁꯦꯔꯥꯇꯟ ꯍꯥꯏꯗꯕꯥꯗꯅ ꯃꯤꯊꯨꯡꯂꯣꯏꯁꯤꯡꯕꯨ ꯐꯦꯁꯇ ꯍꯦꯂꯣꯋꯤꯅ ꯕꯨꯐꯦꯇꯥ ꯀꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  56%|██████████████▉            | 555/1000 [08:38<05:48,  1.28it/s]

[555/1000]
EN: Chef Yugal Sharma represents North West Frontier cuisine at ITC.
MT: ꯁꯦꯐ ꯌꯨꯒꯜ ꯁꯔꯃꯥꯅꯥ ꯑꯥꯏ ꯇꯤ ꯁꯤ ꯗꯥ ꯅꯣꯔꯊ ꯋꯇ ꯐꯅꯇꯤꯌꯔꯒꯤ ꯆꯤꯟꯖꯥꯛꯀꯤ ꯃꯁꯛ ꯇꯥꯛ
--------------------------------------------------

Translating:  56%|███████████████            | 556/1000 [08:39<05:31,  1.34it/s]

[556/1000]
EN: Royal Afghan assistant master chef promotes rustic Indian cuisine.
MT: ꯔꯣꯌꯦꯜ ꯑꯐꯒꯥꯟ ꯑꯦꯁꯤꯁꯇꯦꯟꯇ ꯃꯥꯁꯇꯔ ꯁꯦꯐꯅꯥ ꯂꯩꯕꯥꯛ ꯑꯁꯤꯒꯤ ꯚꯥꯔꯠꯀꯤ ꯆꯤꯟꯖꯥꯛꯄꯨ ꯌꯣꯛꯈꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  56%|███████████████            | 557/1000 [08:40<05:35,  1.32it/s]

[557/1000]
EN: The Leela Hyderabad hosts Chef Picched three-day Thai culinary showcase.
MT: ꯂꯤꯂꯥ ꯍꯥꯏꯗꯕꯥꯗꯗꯥ ꯁꯦꯐ ꯄꯤꯛꯆꯇ ꯊꯥꯏꯒꯤ ꯅꯨꯃꯤꯠ ꯑꯍꯨꯝꯅꯤ ꯆꯥꯅꯅꯕ ꯆꯤꯟꯖꯥꯛꯀꯤ ꯊꯧꯔꯝ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  56%|███████████████            | 558/1000 [08:41<05:35,  1.32it/s]

[558/1000]
EN: Chef Picched Paoleng brings authentic Bangkok cuisine to Hyderabad.
MT: ꯁꯦꯐ ꯄꯤꯆꯗ ꯄꯥꯑꯣꯂꯦꯡꯅꯥ ꯍꯥꯏꯗꯕꯥꯗꯇꯥ ꯑꯆꯨꯝꯕ ꯕꯦꯡꯀꯣꯛꯀꯤ ꯆꯤꯟꯖꯥꯛ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  56%|███████████████            | 559/1000 [08:41<05:54,  1.24it/s]

[559/1000]
EN: Marriott Executive Apartments Bengaluru unveils Madras Kitchen restaurant.
MT: ꯃꯦꯔꯤꯑꯣꯇ ꯑꯦꯛꯖꯤꯀ ꯭ ꯌꯨꯇꯤꯕ ꯑꯦꯄꯥꯔꯇꯃꯦꯟꯇ ꯕꯦꯡꯂꯨꯔꯥꯅꯥ ꯃꯗꯖ ꯀꯤꯆꯟ ꯔꯦꯁꯇꯣꯔꯦꯟꯇ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  56%|███████████████            | 560/1000 [08:42<05:40,  1.29it/s]

[560/1000]
EN: Madras Kitchen pays homage to South Indian gastronomic heritage.
MT: ꯃꯗꯖ ꯀꯤꯆꯟꯅ ꯈꯥ ꯚꯥꯔꯠꯀꯤ ꯒꯅꯣꯃꯤꯛ ꯍꯦꯔꯤꯇꯦꯖꯗꯥ ꯏꯀꯥꯏꯈꯨꯝꯅꯕ ꯎꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  56%|███████████████▏           | 561/1000 [08:43<05:45,  1.27it/s]

[561/1000]
EN: ITC Grand Bharat chef shares Diwali festive dinner hosting tips.
MT: ꯑꯥꯏ ꯇꯤ ꯁꯤ ꯒꯥꯟꯗ ꯚꯥꯔꯠ ꯁꯦꯐꯅꯥ ꯗꯤꯋꯥꯂꯤ ꯐꯦꯁꯇꯤꯚ ꯗꯤꯅꯔ ꯍꯣꯁꯠ ꯇꯧꯕ ꯇꯤꯞꯁꯤꯡ ꯁꯦꯌꯔ ꯇꯧ
--------------------------------------------------

Translating:  56%|███████████████▏           | 562/1000 [08:44<06:18,  1.16it/s]

[562/1000]
EN: Marriott Executive Apartments Hyderabad celebrates Hyderabadi dessert heritage.
MT: ꯃꯦꯔꯤꯑꯣꯇ ꯑꯦꯛꯖꯤꯀ ꯭ ꯌꯨꯇꯤꯕ ꯑꯦꯄꯥꯔꯇꯃꯦꯟꯇ ꯍꯥꯏꯗꯕꯥꯗꯅꯥ ꯍꯦꯔꯤꯇꯦꯖ ꯑꯣꯏꯔꯕꯥ ꯍꯥꯏꯗꯦꯕꯥꯗꯤꯒꯤ ꯑꯊꯨꯝꯕꯒꯤ ꯊꯧꯔꯝ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  56%|███████████████▏           | 563/1000 [08:45<05:47,  1.26it/s]

[563/1000]
EN: 4Note culinary hot spot opens with four kitchens concept.
MT: 4 ꯅꯣꯇ ꯀꯨꯂꯤꯅꯔꯤ ꯍꯣꯠꯣꯠ ꯑꯁꯤ ꯀꯤꯆꯟ ꯃꯔꯤꯒꯤ ꯋꯥꯈꯜꯂꯣꯟꯒꯥ ꯂꯣꯏꯅꯅ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  56%|███████████████▏           | 564/1000 [08:45<05:43,  1.27it/s]

[564/1000]
EN: Zuma Abu Dhabi maintains global legacy restaurant standards.
MT: ꯖꯨꯃꯥ ꯑꯕꯨ ꯙꯥꯕꯤꯅꯥ ꯒ ꯭ ꯂꯣꯕꯦꯜ ꯂꯦꯖꯤꯁꯤ ꯔꯦꯁꯇꯣꯔꯦꯟꯇꯦꯟꯗꯗꯔꯁꯤꯡ ꯊꯝꯃꯤ ꯫
--------------------------------------------------

Translating:  56%|███████████████▎           | 565/1000 [08:46<05:37,  1.29it/s]

[565/1000]
EN: Dubai chocolate craze triggers global pistachio shortage crisis.
MT: ꯗꯨꯕꯥꯏ ꯆꯣꯀꯣꯂꯦꯠꯀꯤ ꯅꯨꯡꯁꯤꯠꯅ ꯃꯥꯂꯦꯝꯒꯤ ꯑꯣꯏꯅ ꯄꯤꯁꯇꯥꯆꯤꯑꯣ ꯋꯥꯠꯄꯒꯤ ꯑꯋꯥꯕ ꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  57%|███████████████▎           | 566/1000 [08:47<05:27,  1.33it/s]

[566/1000]
EN: Indian Hotels Company signs new Taj property in Lucknow.
MT: ꯏꯟꯗꯤꯌꯟ ꯍꯣꯇꯦꯜꯁ ꯀꯝꯄꯅꯤꯅꯥ ꯂꯈꯅꯧꯗꯥ ꯑꯅꯧꯕ ꯇꯥꯖꯄꯣꯔꯇꯤ ꯈꯨꯠꯌꯦꯛ ꯄꯤꯁꯤꯟ
--------------------------------------------------

Translating:  57%|███████████████▎           | 567/1000 [08:48<05:28,  1.32it/s]

[567/1000]
EN: Oberoi Group announces luxury resort opening in Ranthambhore.
MT: ꯑꯣꯕꯦꯔꯣꯏꯨꯞꯅꯥ ꯔꯟꯊꯝꯚꯣꯔꯗꯥ ꯂꯛꯁꯔꯤ ꯔꯤꯖꯣꯔꯇ ꯍꯥꯡꯗꯣꯛꯂꯦ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  57%|███████████████▎           | 568/1000 [08:49<05:41,  1.27it/s]

[568/1000]
EN: Lemon Tree Hotels expands northeast presence with Guwahati property.
MT: ꯂꯤꯃꯣꯟ ꯍꯣꯇꯦꯜꯁꯤꯡ ꯑꯁꯤꯅ ꯑꯋꯥꯡ ꯅꯣꯡꯄꯣꯛꯀꯤ ꯃꯐꯝ ꯑꯁꯤ ꯒꯨꯋꯥꯍꯥꯇꯤ ꯄꯄꯔꯇꯤꯒ ꯂꯣꯏꯅꯅꯥ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  57%|███████████████▎           | 569/1000 [08:49<05:33,  1.29it/s]

[569/1000]
EN: Marriott International to open 50th property in India by 2026.
MT: ꯃꯦꯔꯤꯑꯣꯇ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜꯅꯥ ꯏꯪꯁꯣꯛ ꯐꯥꯎꯕꯗ ꯚꯥꯔꯠꯇꯥꯁꯨꯕꯄꯣꯔꯇꯤ ꯍꯥꯡꯗꯣꯛꯀꯅꯤ ꯫
--------------------------------------------------

Translating:  57%|███████████████▍           | 570/1000 [08:50<05:35,  1.28it/s]

[570/1000]
EN: Radisson Hotel Group targets 200 hotels across India by 2027.
MT: ꯔꯦꯗꯤꯁꯟ ꯍꯣꯇꯦꯜ ꯒꯨꯞꯅ ꯏꯪꯁꯣꯛ ꯐꯥꯎꯕꯗ ꯚꯥꯔꯠ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯍꯣꯇꯜꯒꯤ ꯄꯥꯟꯗꯝ ꯊꯝ
--------------------------------------------------

Translating:  57%|███████████████▍           | 571/1000 [08:51<05:32,  1.29it/s]

[571/1000]
EN: OYO announces international expansion into Vietnam and Indonesia.
MT: ꯑꯣꯑꯥꯏꯑꯣꯅꯥ ꯚꯤꯇꯦꯝ ꯑꯃꯁꯨꯡ ꯏꯟꯗꯣꯅꯦꯁꯤꯌꯥꯗꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜꯗ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  57%|███████████████▍           | 572/1000 [08:52<05:42,  1.25it/s]

[572/1000]
EN: MakeMyTrip partners with IHCL for exclusive holiday packages.
MT: ꯏꯀꯁꯤꯋꯦꯜ ꯍꯣꯂꯤꯗꯦ ꯄꯦꯀꯦꯖꯁꯤꯡꯒꯤꯗꯃꯛ ꯑꯥꯏ ꯑꯩꯆ ꯁꯤ ꯑꯦꯜꯒꯥ ꯃꯦꯛꯃꯥꯏꯞ ꯄꯥꯔꯇꯥꯅꯔꯁꯤꯡ ꯑꯣꯏ ꯫
--------------------------------------------------

Translating:  57%|███████████████▍           | 573/1000 [08:52<05:29,  1.30it/s]

[573/1000]
EN: Maha Kumbh Mela creates one million jobs for local families.
MT: ꯃꯍꯥ ꯀꯨꯝꯚ ꯃꯦꯂꯥꯅꯥ ꯂꯣꯀꯦꯜ ꯐꯦꯃꯤꯂꯤꯁꯤꯡꯒꯤꯗꯃꯛ ꯊꯕꯛ ꯃꯤꯌꯣꯏ ꯑꯃ ꯁꯦꯝ
--------------------------------------------------

Translating:  57%|███████████████▍           | 574/1000 [08:53<05:07,  1.39it/s]

[574/1000]
EN: Boat services at Kumbh earn families collective 30 crore rupees.
MT: ꯀꯨꯝꯚꯗꯥ ꯍꯤ ꯁꯔꯕꯤꯁ ꯇꯧꯕꯗꯒꯤ ꯏꯃꯨꯡ ꯃꯅꯨꯡꯅꯥ ꯑꯄꯨꯟꯕ ꯑꯣꯏꯅ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯐꯪ
--------------------------------------------------

Translating:  57%|███████████████▌           | 575/1000 [08:54<05:15,  1.35it/s]

[575/1000]
EN: The Guardian describes Prayagraj Kumbh as pop-up megacity.
MT: ꯗ ꯒꯥꯔꯗꯤꯌꯟꯅꯥꯌꯥꯒꯔꯥꯖ ꯀꯨꯝꯚꯕꯨ ꯄꯣꯄ-ꯑꯞ ꯃꯦꯒꯥꯁꯤꯇꯤ ꯍꯥꯏꯅ ꯇꯥꯛ
--------------------------------------------------

Translating:  58%|███████████████▌           | 576/1000 [08:54<04:55,  1.43it/s]

[576/1000]
EN: Maharashtra Economic Council reports Kumbh employment generation.
MT: ꯃꯍꯥꯔꯥꯁꯇ ꯑꯦꯀꯅꯣꯃꯤꯛ ꯀꯥꯎꯟꯁꯤꯜꯅ ꯀꯨꯝꯚꯒꯤ ꯊꯕꯛ ꯐꯪꯍꯟꯕꯒꯤ ꯔꯤꯄꯣꯔꯠ ꯄꯤ ꯫
--------------------------------------------------

Translating:  58%|███████████████▌           | 577/1000 [08:55<05:15,  1.34it/s]

[577/1000]
EN: FIFA Club World Cup 2025 brings global visitors to host cities.
MT: ꯐꯤꯐꯥ ꯀꯂꯕ ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞ 2025ꯅꯥ ꯃꯥꯂꯦꯝ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯂꯥꯛꯄꯥ ꯃꯤꯌꯣꯏꯁꯤꯡꯕꯨ ꯁꯍꯔꯁꯤꯡ ꯍꯣꯁꯠ ꯇꯧꯅꯕ ꯄꯨꯔꯛꯏ ꯫
--------------------------------------------------

Translating:  58%|███████████████▌           | 578/1000 [08:56<05:07,  1.37it/s]

[578/1000]
EN: Wimbledon 2025 witnesses global unity through international tennis.
MT: ꯋꯤꯝꯕꯜꯗꯟ 2025 ꯗꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯇꯦꯅꯤꯁꯀꯤ ꯈꯨꯊꯥꯡꯗꯥ ꯒ ꯭ ꯂꯣꯕꯦꯜ ꯌꯨꯅꯤꯇꯤ ꯎꯔꯦ ꯫
--------------------------------------------------

Translating:  58%|███████████████▋           | 579/1000 [08:57<04:53,  1.43it/s]

[579/1000]
EN: Sikh pilgrims receive Pakistani visas after Operation Sindoor.
MT: ꯁꯤꯈ ꯂꯥꯏꯅꯤꯡꯕꯁꯤꯡꯅ ꯑꯣꯄꯔꯦꯁꯟ ꯁꯤꯟꯗꯨꯔꯒꯤ ꯃꯇꯨꯡꯗ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯚꯤꯖꯥ ꯐꯪ
--------------------------------------------------

Translating:  58%|███████████████▋           | 580/1000 [08:57<05:01,  1.39it/s]

[580/1000]
EN: Harjindarpal Singh secures passport and Pakistan visa for pilgrimage.
MT: ꯍꯔꯖꯤꯟꯗꯔꯄꯥꯜ ꯁꯤꯡꯍꯅꯥ ꯄꯥꯁꯄꯣꯔꯇ ꯑꯃꯁꯨꯡ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯚꯤꯖꯥ ꯐꯪ
--------------------------------------------------

Translating:  58%|███████████████▋           | 581/1000 [08:58<04:50,  1.44it/s]

[581/1000]
EN: First Sikh Jathas travel to Pakistan post visa ban reversal.
MT: ꯑꯍꯥꯟꯕ ꯁꯤꯈ ꯖꯥꯊꯥꯁꯤꯡꯅ ꯚꯤꯖꯥ ꯕꯦꯟ ꯔꯤꯚꯔꯁꯦꯜ ꯇꯧꯔꯕꯥ ꯃꯇꯨꯡꯗ ꯄꯥꯀꯤꯁꯇꯥꯟꯗ ꯆꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  58%|███████████████▋           | 582/1000 [08:59<05:02,  1.38it/s]

[582/1000]
EN: FIDE names World Chess Cup trophy after Viswanathan Anand.
MT: ꯐꯤꯗꯦꯅꯥ ꯋꯜꯗ ꯆꯦꯁ ꯀꯄ ꯇꯐꯤ ꯑꯁꯤ ꯕꯤꯁꯋꯥꯅꯥꯊꯅ ꯑꯥꯅꯟꯗꯒꯤ ꯃꯃꯤꯡ ꯂꯧꯔꯒ ꯀꯧ
--------------------------------------------------

Translating:  58%|███████████████▋           | 583/1000 [08:59<04:57,  1.40it/s]

[583/1000]
EN: Panjim hosts FIDE World Chess Cup with Anand trophy.
MT: ꯄꯥꯟꯖꯤꯃꯅꯥ ꯑꯥꯅꯟꯗ ꯇꯐꯤꯒꯥ ꯂꯣꯏꯅꯅ ꯐꯤꯗꯦ ꯋꯥꯔꯂ ꯭ ꯗ ꯆꯦꯁ ꯀꯄ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  58%|███████████████▊           | 584/1000 [09:00<04:50,  1.43it/s]

[584/1000]
EN: Krishna Janmashtami procession turns tragic in Ramanthapur.
MT: ꯀꯅꯥ ꯖꯅꯃꯁꯇꯃꯤꯒꯤ ꯈꯣꯡꯆꯠ ꯑꯁꯤ ꯔꯥꯃꯟꯊꯥꯄꯨꯔꯗꯥ ꯑꯋꯥꯕꯥ ꯑꯣꯏꯔꯦ ꯫
--------------------------------------------------

Translating:  58%|███████████████▊           | 585/1000 [09:01<04:37,  1.49it/s]

[585/1000]
EN: Ten-foot chariot touches live wire killing five devotees.
MT: ꯈꯣꯡꯌꯨꯡ ꯇꯔꯥꯅꯥ ꯂꯥꯏꯕ ꯋꯥꯏꯔ ꯁꯣꯛꯄꯥꯗꯥ ꯂꯥꯏꯅꯤꯡꯕꯥ ꯃꯉꯥ ꯁꯤ
--------------------------------------------------

Translating:  59%|███████████████▊           | 586/1000 [09:01<04:42,  1.47it/s]

[586/1000]
EN: Hyderabad celebrates Ganesh festival with large screen displays.
MT: ꯍꯥꯏꯗꯕꯥꯗꯅ ꯒꯅꯦꯁ ꯐꯦꯁꯇꯤꯕꯦꯜ ꯑꯁꯤ ꯑꯆꯧꯕꯔꯤꯅ ꯗꯤꯁꯄꯁꯤꯡꯒ ꯂꯣꯏꯅꯅ ꯄꯥꯡꯊꯣꯛꯏ ꯫
--------------------------------------------------

Translating:  59%|███████████████▊           | 587/1000 [09:02<04:52,  1.41it/s]

[587/1000]
EN: Begum Bazaar jam-packed for night long festival celebrations.
MT: ꯕꯦꯒꯃ ꯕꯖꯥꯔꯗꯥ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯃꯇꯝ ꯆꯨꯞꯄꯥ ꯀꯨꯝꯍꯩꯒꯤ ꯊꯧꯔꯝꯁꯤꯡ ꯄꯥꯡꯊꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯊꯥꯎ-ꯊꯣꯠꯄ
--------------------------------------------------

Translating:  59%|███████████████▉           | 588/1000 [09:03<04:41,  1.46it/s]

[588/1000]
EN: Muslim leader Sadeq Siraj organizes eye camp for community.
MT: ꯃꯨꯁꯂꯤꯝ ꯂꯨꯆꯤꯡꯕ ꯁꯥꯗꯦꯀ ꯁꯤꯔꯥꯖꯅ ꯀꯝꯃꯅꯤꯇꯤꯒꯤꯗꯃꯛ ꯑꯥꯏ ꯀꯦꯝꯄ ꯄꯥꯡꯊꯣꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  59%|███████████████▉           | 589/1000 [09:04<04:54,  1.40it/s]

[589/1000]
EN: Hyderabad pandals adopt traditional themes for Ganesh Chaturthi.
MT: ꯍꯥꯏꯗꯕꯥꯗ ꯄꯟꯗꯜꯁꯤꯡꯅꯥ ꯒꯅꯦꯁ ꯆꯇꯨꯔꯊꯤꯒꯤꯗꯃꯛ ꯆꯠꯅꯕꯤꯒꯤ ꯑꯣꯏꯕ ꯊꯤꯃꯁꯤꯡ ꯂꯧ
--------------------------------------------------

Translating:  59%|███████████████▉           | 590/1000 [09:04<04:58,  1.37it/s]

[590/1000]
EN: Shuja Ifteqari requests Chief Minister Revanth Reddy for arrangements.
MT: ꯁꯨꯖꯥ ꯏꯐꯇꯦꯀꯔꯤꯅꯥ ꯃꯨꯈꯌ ꯃꯟꯇ ꯔꯦꯚꯟꯊ ꯔꯦꯗꯗꯤꯗꯥ ꯊꯧꯔꯥꯡ ꯇꯧꯅꯕ ꯍꯥꯏꯖ
--------------------------------------------------

Translating:  59%|███████████████▉           | 591/1000 [09:05<04:53,  1.39it/s]

[591/1000]
EN: SOCIAL Hyderabad hosts She's a Phataka Diwali celebration bash.
MT: ꯁꯣꯁꯤꯌꯥꯜ ꯍꯥꯏꯗꯕꯥꯗꯅ ꯁꯦ ꯏꯖ ꯑꯦ ꯐꯥꯇꯀꯥ ꯗꯤꯋꯥꯂꯤꯒꯤ ꯊꯧꯔꯝ ꯄꯥꯡꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  59%|███████████████▉           | 592/1000 [09:06<04:41,  1.45it/s]

[592/1000]
EN: Hyderabad soaked in festival fervour with rain showers.
MT: ꯍꯥꯏꯗꯕꯥꯗ ꯑꯁꯤ ꯅꯣꯡ ꯆꯨꯕꯥꯒ ꯂꯣꯏꯅꯅꯥ ꯀꯨꯝꯍꯩꯒꯤ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  59%|████████████████           | 593/1000 [09:06<04:49,  1.41it/s]

[593/1000]
EN: Dasara trains diverted to manage two lakh passenger footfall.
MT: ꯄꯦꯁꯦꯟꯖꯔ ꯂꯥꯈ ꯑꯅꯤꯒꯤ ꯐꯨꯗꯐꯣꯜ ꯁꯤꯟꯗꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯗꯥꯁꯥꯔꯥ ꯇꯦꯟꯁꯤꯡ ꯗꯥꯏꯚꯔꯇ ꯇꯧ
--------------------------------------------------

Translating:  59%|████████████████           | 594/1000 [09:07<04:45,  1.42it/s]

[594/1000]
EN: New passenger routes planned for Dasara and Diwali travel.
MT: ꯗꯥꯁꯥꯔꯥ ꯑꯃꯁꯨꯡ ꯗꯤꯋꯥꯂꯤ ꯇꯚꯦꯜꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯄꯦꯁꯦꯟꯖꯔ ꯔꯨꯠꯁꯤꯡ ꯊꯧꯔꯥꯡ ꯇꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  60%|████████████████           | 595/1000 [09:08<04:47,  1.41it/s]

[595/1000]
EN: Hyderabad kiosks offer Ganesh idols across every street.
MT: ꯍꯥꯏꯗꯕꯥꯗꯀꯤ ꯀꯤꯑꯣꯁ ꯭ ꯛꯁꯤꯡꯗ ꯒꯅꯦꯁꯀꯤ ꯃꯨꯔꯠꯇꯤꯁꯤꯡ ꯁꯇ ꯈꯨꯗꯤꯡꯃꯛꯇ ꯄꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  60%|████████████████           | 596/1000 [09:08<04:28,  1.51it/s]

[596/1000]
EN: Indian Navy monitors every Chinese vessel in Indian Ocean.
MT: ꯚꯥꯔꯠꯀꯤ ꯁꯃꯨꯗꯗꯥ ꯂꯩꯕ ꯆꯥꯏꯅꯥꯒꯤ ꯍꯤ ꯈꯨꯗꯤꯡꯃꯛ ꯏꯟꯗꯤꯌꯟ ꯅꯦꯚꯤꯅꯥ ꯌꯦꯡꯁꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  60%|████████████████           | 597/1000 [09:09<04:41,  1.43it/s]

[597/1000]
EN: Vice Admiral Sanjay Vatsayan confirms continuous maritime surveillance.
MT: ꯚꯥꯏꯁ ꯑꯦꯗꯃꯤꯔꯦꯜ ꯁꯟꯖꯦ ꯚꯇꯁꯥꯌꯟꯅ ꯃꯈꯥ ꯇꯥꯅ ꯁꯃꯨꯗꯗꯥ ꯌꯦꯡꯁꯤꯟꯕꯒꯤ ꯊꯕꯛ ꯆꯠꯊꯔꯤ ꯍꯥꯏꯕ ꯈꯪꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  60%|████████████████▏          | 598/1000 [09:10<04:39,  1.44it/s]

[598/1000]
EN: Goa tourism department announces calendar of winter festivals.
MT: ꯒꯣꯋꯥ ꯇꯨꯔꯤꯖꯝ ꯗꯤꯄꯥꯔꯇꯃꯦꯟꯇꯅꯥ ꯅꯤꯡꯊꯝꯊꯥꯒꯤ ꯀꯨꯝꯍꯩꯁꯤꯡꯒꯤ ꯀꯦꯂꯦꯟꯗꯔ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  60%|████████████████▏          | 599/1000 [09:11<04:46,  1.40it/s]

[599/1000]
EN: Jaipur Literature Festival attracts 50,000 book lovers from abroad.
MT: ꯖꯦꯄꯨꯔ ꯂꯤꯇꯔꯦꯆꯔ ꯐꯦꯁꯇꯤꯕꯦꯜꯅꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯇꯒꯤ ꯂꯥꯏꯔꯤꯛ ꯄꯥꯝꯖꯕ ꯃꯤꯑꯣꯏ ꯒꯤ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  60%|████████████████▏          | 600/1000 [09:11<04:45,  1.40it/s]

[600/1000]
EN: Rann Utsav begins in Kutch with tent city bookings full.
MT: ꯇꯦꯟꯇ ꯁꯤꯇꯤ ꯕꯨꯀꯤꯡ ꯃꯄꯨꯡ ꯐꯥꯕꯥꯒ ꯂꯣꯏꯅꯅꯥ ꯔꯟ ꯎꯇꯁꯥꯚ ꯑꯁꯤ ꯀꯨꯇꯆꯇꯥ ꯍꯧ
--------------------------------------------------

Translating:  60%|████████████████▏          | 601/1000 [09:12<04:46,  1.39it/s]

[601/1000]
EN: Hornbill Festival showcases Naga heritage in Kisama heritage village.
MT: ꯍꯣꯔꯟꯕꯤꯜ ꯐꯦꯁꯇꯤꯕꯦꯜꯅꯥ ꯀꯤꯁꯥꯃꯥ ꯍꯦꯔꯤꯇꯦꯖ ꯈꯨꯡꯒꯪꯗꯥ ꯅꯥꯒꯥꯒꯤ ꯍꯦꯔꯤꯇꯤꯖ ꯎꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  60%|████████████████▎          | 602/1000 [09:13<04:55,  1.34it/s]

[602/1000]
EN: Ganga Aarti at Varanasi draws record international tourist attendance.
MT: ꯕꯥꯔꯥꯅꯥꯁꯤꯗ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯒꯪꯒꯥ ꯑꯥꯔꯇꯤꯗꯥ ꯑꯇꯔꯖꯥꯇꯤꯒꯤ ꯂꯝꯀꯣꯏꯕꯥꯁꯤꯡꯒꯤ ꯁꯔꯨꯛ ꯌꯥꯕꯒꯤ ꯂꯥꯆꯟ
--------------------------------------------------

Translating:  60%|████████████████▎          | 603/1000 [09:14<04:43,  1.40it/s]

[603/1000]
EN: Pahalgam terror attack kills twenty-six tourists including foreigners.
MT: ꯄꯍꯥꯜꯒꯥꯝ ꯇꯦꯔꯣꯔꯤ ꯑꯦꯇꯦꯛ ꯇꯧꯕꯗꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯃꯤꯑꯣꯏꯁꯤꯡ ꯌꯥꯎꯅꯥ ꯂꯝꯀꯣꯏꯕꯥ 26 ꯁꯤ
--------------------------------------------------

Translating:  60%|████████████████▎          | 604/1000 [09:14<04:34,  1.44it/s]

[604/1000]
EN: Terrorists attack Baisaran meadows killing twenty-six civilian tourists.
MT: ꯇꯦꯔꯣꯔꯤꯁꯇꯁꯤꯡꯅ ꯕꯥꯏꯁꯥꯔꯥꯟꯒꯤ ꯂꯝꯈꯩꯁꯤꯡꯗ ꯂꯥꯟꯗꯥꯗꯨꯅ ꯃꯤꯆꯝꯒꯤ ꯂꯝꯀꯣꯏꯕ 26 ꯁꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  60%|████████████████▎          | 605/1000 [09:15<04:20,  1.52it/s]

[605/1000]
EN: Two foreign tourists among twenty-six dead in Pahalgam attack.
MT: ꯄꯍꯥꯜꯒꯥꯝ ꯑꯦꯇꯦꯛꯗꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯑꯅꯤꯒ ꯂꯣꯏꯅꯅꯥ ꯃꯤꯑꯣꯏ 26 ꯁꯤ
--------------------------------------------------

Translating:  61%|████████████████▎          | 606/1000 [09:15<04:15,  1.54it/s]

[606/1000]
EN: Operation Sindoor launched following deadly Pahalgam tourist attack.
MT: ꯄꯍꯥꯜꯒꯥꯃ ꯇꯨꯔꯤꯁꯇ ꯑꯦꯇꯦꯛꯀꯤ ꯃꯇꯨꯡꯗ ꯑꯣꯄꯔꯦꯁꯟ ꯁꯤꯟꯗꯨꯔ ꯍꯧ
--------------------------------------------------

Translating:  61%|████████████████▍          | 607/1000 [09:16<04:25,  1.48it/s]

[607/1000]
EN: Saudi Arabia minister Adel Al-Jubeir arrives in Delhi post Operation Sindoor.
MT: ꯁꯧꯗꯤ ꯑꯔꯕꯒꯤ ꯃꯟꯇ ꯑꯗꯦꯜ ꯑꯜ-ꯖꯨꯕꯦꯔ ꯑꯣꯄꯔꯦꯁꯟ ꯁꯤꯟꯗꯨꯔꯒꯤ ꯃꯇꯨꯡꯗ ꯗꯤꯜꯂꯤꯗꯥ ꯂꯥꯛ
--------------------------------------------------

Translating:  61%|████████████████▍          | 608/1000 [09:17<04:23,  1.49it/s]

[608/1000]
EN: Iranian Foreign Minister Araghchi visits New Delhi amid tensions.
MT: ꯏꯔꯥꯅꯤꯌꯟꯒꯤ ꯐꯣꯔꯦꯟ ꯃꯟꯇ ꯑꯔꯥꯘꯆꯤꯅꯥ ꯇꯦꯟꯁꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯅ ꯗꯤꯜꯂꯤꯗꯥ ꯆꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  61%|████████████████▍          | 609/1000 [09:17<04:19,  1.51it/s]

[609/1000]
EN: Delhi Red Fort blast leaves fourteen dead and several injured.
MT: ꯗꯤꯜꯂꯤꯒꯤ ꯔꯦꯗ ꯐꯣꯔꯇ ꯄꯣꯈꯥꯏꯕꯒꯤ ꯊꯧꯗꯣꯛꯗꯥ ꯃꯤꯑꯣꯏ 14 ꯁꯤꯈꯤ ꯑꯃꯁꯨꯡ ꯀꯌꯥ ꯑꯃꯥ ꯅꯥꯟꯊꯣꯛ
--------------------------------------------------

Translating:  61%|████████████████▍          | 610/1000 [09:18<04:09,  1.57it/s]

[610/1000]
EN: High intensity explosion outside Red Fort kills fourteen people.
MT: ꯔꯦꯗ ꯐꯣꯔꯇ ꯃꯄꯥꯟꯗ ꯍꯥꯏ ꯏꯟꯇꯦꯟꯁꯤꯇꯤ ꯄꯣꯈꯥꯏꯕꯅ ꯃꯤꯑꯣꯏ 14 ꯁꯤ
--------------------------------------------------

Translating:  61%|████████████████▍          | 611/1000 [09:19<04:24,  1.47it/s]

[611/1000]
EN: Supreme Court upholds Christian Army officer Samuel Kamalesan dismissal.
MT: ꯁꯨꯄꯝ ꯀꯣꯔꯇꯅꯥ ꯈꯌꯥꯅ ꯑꯥꯔꯃꯤ ꯑꯣꯐꯤꯁꯔ ꯁꯦꯃꯜ ꯀꯥꯃꯥꯂꯦꯁꯟꯕꯨ ꯂꯧꯊꯣꯛꯄꯥ ꯂꯦꯞꯈꯤ ꯫
--------------------------------------------------

Translating:  61%|████████████████▌          | 612/1000 [09:19<04:24,  1.46it/s]

[612/1000]
EN: Army officer refuses temple pooja entry leading to dismissal.
MT: ꯑꯥꯔꯃꯤ ꯑꯣꯐꯤꯁꯔꯅꯥ ꯂꯥꯏꯁꯪꯗꯥ ꯄꯨꯖꯥ ꯌꯥꯎꯕꯥ ꯌꯥꯈꯤꯗꯦ ꯃꯗꯨꯅ ꯃꯔꯝ ꯑꯣꯏꯔꯒ ꯐꯝ ꯊꯥꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  61%|████████████████▌          | 613/1000 [09:20<04:31,  1.42it/s]

[613/1000]
EN: Chief Justice Surya Kant terms refusal grossest kind of indiscipline.
MT: ꯆꯤꯐ ꯖꯇꯤꯁ ꯁꯨꯔꯌꯥ ꯀꯟꯇꯅꯥ ꯌꯥꯗꯕꯒꯤ ꯋꯥꯐꯝ ꯑꯁꯤ ꯈ ꯭ ꯋꯥꯏꯗꯒꯤ ꯆꯥꯎꯔꯕ ꯅꯤꯌꯝ ꯅꯥꯏꯗꯕ ꯑꯃꯅꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  61%|████████████████▌          | 614/1000 [09:21<04:13,  1.52it/s]

[614/1000]
EN: Saif Ali Khan undergoes surgery after knife attack at residence.
MT: ꯁꯥꯏꯐ ꯑꯂꯤ ꯈꯥꯟꯒꯤ ꯌꯨꯝꯗꯥ ꯆꯤꯊꯤꯅ ꯂꯥꯟꯗꯥꯕꯥ ꯃꯇꯨꯡꯗ ꯁꯔꯖꯔꯤ ꯇꯧ
--------------------------------------------------

Translating:  62%|████████████████▌          | 615/1000 [09:21<04:10,  1.53it/s]

[615/1000]
EN: Intruder attacks Bollywood actor Saif Ali Khan in Mumbai.
MT: ꯏꯟꯇꯨꯗꯔꯅ ꯕꯣꯂꯤꯋꯨꯗ ꯑꯦꯛꯇꯔ ꯁꯥꯏꯐ ꯑꯂꯤ ꯈꯥꯟꯗꯥ ꯃꯨꯝꯕꯥꯏꯗ ꯂꯥꯟꯗꯥ
--------------------------------------------------

Translating:  62%|████████████████▋          | 616/1000 [09:22<04:12,  1.52it/s]

[616/1000]
EN: Mumbai police identify accused in Saif Ali Khan attack case.
MT: ꯃꯨꯝꯕꯥꯏ ꯄꯨꯂꯤꯁꯅꯥ ꯁꯥꯏꯐ ꯑꯂꯤ ꯈꯥꯟ ꯑꯦꯇꯦꯛ ꯀꯦꯁꯗꯥ ꯃꯔꯥꯜ ꯂꯩꯕꯁꯤꯡ ꯃꯁꯛ ꯈꯪꯗꯣꯛ
--------------------------------------------------

Translating:  62%|████████████████▋          | 617/1000 [09:23<04:23,  1.45it/s]

[617/1000]
EN: Actor discharged five days after hospitalization following attack.
MT: ꯑꯦꯇꯦꯛ ꯇꯧꯔꯕ ꯃꯇꯨꯡ ꯍꯣꯁꯄꯤꯇꯥꯜ ꯑꯣꯏꯔꯛꯄꯒꯤ ꯅꯨꯃꯤꯠ ꯃꯉꯥꯅꯤꯒꯤ ꯃꯇꯨꯡꯗ ꯑꯦꯛꯇꯔ ꯑꯗꯨꯕꯨ ꯗꯤꯁꯆꯥꯔꯖ ꯇꯧ
--------------------------------------------------

Translating:  62%|████████████████▋          | 618/1000 [09:24<04:44,  1.34it/s]

[618/1000]
EN: Tihar jail probe reveals racket charging for free inmate meetings.
MT: ꯇꯤꯍꯥꯔ ꯖꯦꯜꯒꯤ ꯊꯤꯖꯤꯟ- ꯍꯨꯝꯖꯤꯟꯕꯒꯤ ꯊꯕꯛ ꯑꯁꯤꯅ ꯐ ꯏꯟꯃꯤꯇ ꯃꯤꯇꯤꯡꯁꯤꯡꯒꯤꯗꯃꯛ ꯔꯦꯀꯦꯇ ꯁꯦꯜ ꯂꯧꯈꯤꯕꯗꯨ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  62%|████████████████▋          | 619/1000 [09:25<04:51,  1.31it/s]

[619/1000]
EN: Undercover officials exposed illegal mulakat charges at Tihar.
MT: ꯑꯟꯗꯔꯀꯚꯔ ꯑꯣꯐꯤꯁꯌꯦꯜꯁꯤꯡꯅꯥ ꯇꯤꯍꯥꯔꯗꯥ ꯑꯥꯏꯟꯅ ꯌꯥꯗꯕ ꯃꯨꯂꯥꯀꯇ ꯆꯥꯔꯖꯁꯤꯡ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  62%|████████████████▋          | 620/1000 [09:25<05:10,  1.23it/s]

[620/1000]
EN: Tihar transfers twenty-five data entry operators after tout investigation.
MT: ꯊꯤꯍꯔꯅꯥ ꯊꯤꯖꯟ ꯍꯨꯝꯖꯟꯕ ꯂꯣꯏꯔꯕꯥ ꯗꯦꯇꯥ ꯑꯦꯟ ꯑꯣꯄꯔꯦꯇꯔ ꯃꯉꯥ ꯍꯣꯡꯗꯣꯛꯏ ꯫
--------------------------------------------------

Translating:  62%|████████████████▊          | 621/1000 [09:26<05:22,  1.17it/s]

[621/1000]
EN: Biometric authentication introduced at Tihar Jail for security.
MT: ꯁꯦꯀꯇꯤꯒꯤꯗꯃꯛ ꯇꯤꯍꯥꯔ ꯖꯦꯂꯗꯥ ꯕꯥꯏꯑꯣꯃꯦꯇ ꯑꯣꯊꯦꯟꯇꯤꯀꯦꯁꯟ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  62%|████████████████▊          | 622/1000 [09:28<05:52,  1.07it/s]

[622/1000]
EN: Supreme Court declines virtual appearance exemption for chief secretaries.
MT: ꯁꯨꯄꯝ ꯀꯣꯔꯇꯅꯥ ꯆꯤꯐ ꯁꯦꯀꯇꯔꯤꯁꯤꯡꯒꯤ ꯚꯔꯆ ꯭ ꯌꯨꯑꯦꯜ ꯑꯦꯄꯦꯔꯦꯟꯁ ꯑꯦꯛꯁꯀꯃꯦꯟꯁꯟ ꯌꯥꯗꯦ ꯫
--------------------------------------------------

Translating:  62%|████████████████▊          | 623/1000 [09:29<06:22,  1.01s/it]

[623/1000]
EN: States sleeping over stray dog sterilization orders says Supreme Court.
MT: ꯁꯝ ꯀꯣꯔꯇꯅꯥ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯂꯝꯕꯤ ꯅꯥꯏꯗꯕ ꯗꯣꯒꯦꯔꯤꯂꯥꯏꯖꯦꯁꯟꯒꯤ ꯑꯣꯔꯗꯔꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯔꯥꯖꯁꯤꯡ ꯁꯨꯄ
--------------------------------------------------

Translating:  62%|████████████████▊          | 624/1000 [09:30<06:13,  1.01it/s]

[624/1000]
EN: Passenger forced to write letter after Delhi airport assault.
MT: ꯗꯤꯜꯂꯤ ꯑꯦꯌꯔꯄꯣꯔꯇ ꯑꯦꯁꯣꯂꯇ ꯇꯧꯔꯕꯥ ꯃꯇꯨꯡꯗ ꯄꯦꯁꯦꯟꯖꯔꯅꯥ ꯆꯤꯊꯤ ꯏꯕꯥ ꯇꯥꯍꯟ
--------------------------------------------------

Translating:  62%|████████████████▉          | 625/1000 [09:31<06:01,  1.04it/s]

[625/1000]
EN: Passenger claims pressure to avoid police complaint filing.
MT: ꯄꯦꯁꯦꯟꯒꯔꯅꯥ ꯄꯨꯂꯤꯁ ꯀꯝꯄꯂꯦꯟꯇ ꯐꯥꯏꯂꯤꯡ ꯊꯤꯡꯅꯕꯁꯔ ꯄꯤꯅꯕ ꯍꯥꯏꯔꯤ ꯫
--------------------------------------------------

Translating:  63%|████████████████▉          | 626/1000 [09:32<06:18,  1.01s/it]

[626/1000]
EN: US forces seize oil tanker off Venezuela for narco-terrorism.
MT: ꯌꯨ ꯑꯦꯁ ꯐꯣꯔꯦꯁꯁꯅ ꯅꯦꯔꯀꯣ-ꯇꯦꯔꯣꯔꯤꯖꯝꯒꯤꯗꯃꯛ ꯚꯦꯅꯦꯖꯦꯂꯨꯂꯥꯗꯒꯤ ꯊꯥꯎꯒꯤ ꯇꯦꯡꯀꯔ ꯂꯧꯁꯤꯟ
--------------------------------------------------

Translating:  63%|████████████████▉          | 627/1000 [09:33<06:19,  1.02s/it]

[627/1000]
EN: US Coast Guard apprehends tanker with Department of Defense backing.
MT: ꯌꯨ ꯑꯦꯁ ꯀꯣꯠ ꯒꯥꯔꯗꯅ ꯗꯤꯄꯥꯔꯇꯃꯦꯟꯇ ꯑꯣꯐ ꯗꯤꯐꯦꯟꯁꯀꯤ ꯃꯇꯦꯡꯒ ꯂꯣꯏꯅꯅꯥ ꯇꯦꯡꯀꯔ ꯐꯥ
--------------------------------------------------

Translating:  63%|████████████████▉          | 628/1000 [09:34<06:29,  1.05s/it]

[628/1000]
EN: Supreme Court denies relief to mosque seeking loudspeaker permission.
MT: ꯂꯥꯎꯗꯄꯤꯀꯔꯒꯤ ꯑꯌꯥꯕꯥ ꯂꯧꯕ ꯃꯖꯁꯤꯗꯀꯤꯗꯃꯛ ꯁꯨꯄꯝ ꯀꯣꯔꯠꯅ ꯔꯤꯂꯥꯏꯐ ꯄꯤꯅꯕ ꯌꯥꯗꯦ ꯫
--------------------------------------------------

Translating:  63%|████████████████▉          | 629/1000 [09:35<06:35,  1.07s/it]

[629/1000]
EN: Nagpur bench rules no religion mandates prayers with amplifiers.
MT: ꯅꯥꯒꯄꯨꯔ ꯕꯦꯟꯆꯅꯥ ꯙꯔꯃ ꯑꯃꯠꯇꯅ ꯑꯝꯄꯂꯤꯐꯥꯏꯌꯔꯁꯤꯡꯒ ꯂꯣꯏꯅꯅ ꯂꯥꯏ ꯊꯥꯕꯒꯤ ꯑꯌꯥꯕ ꯄꯤꯗꯦ ꯍꯥꯏꯅ ꯆꯠꯅꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  63%|█████████████████          | 630/1000 [09:36<06:21,  1.03s/it]

[630/1000]
EN: Cruise Saudi brand operations commence with Red Sea licences.
MT: ꯁꯥꯎꯗꯤ ꯕꯥꯟꯗꯀꯤ ꯀꯌꯨꯖ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡ ꯑꯁꯤ ꯔꯦꯗ ꯁꯤ ꯂꯥꯏꯁꯦꯟꯁꯁꯤꯡꯗꯒꯤ ꯍꯧꯏ ꯫
--------------------------------------------------

Translating:  63%|█████████████████          | 631/1000 [09:37<06:08,  1.00it/s]

[631/1000]
EN: Marina services added to Saudi marine tourism portfolio.
MT: ꯁꯥꯎꯗꯤ ꯃꯦꯔꯤꯅ ꯇꯨꯔꯤꯖꯝ ꯄꯣꯔꯇꯐꯣꯂꯤꯑꯣꯗꯥ ꯃꯦꯔꯤꯅꯥ ꯁꯔꯕꯤꯁꯁꯤꯡ ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  63%|█████████████████          | 632/1000 [09:38<06:00,  1.02it/s]

[632/1000]
EN: Recreational marine activities licensed by Saudi Red Sea Authority.
MT: ꯁꯥꯎꯗꯤ ꯔꯦꯗ ꯁꯤ ꯑꯣꯊꯣꯔꯤꯇꯤꯅꯥ ꯂꯥꯏꯁꯦꯟꯁ ꯄꯤꯔꯕꯥ ꯔꯤꯀꯦꯁꯅꯦꯜ ꯃꯦꯔꯤꯅ ꯑꯦꯛꯇꯤꯚꯤꯇꯤꯁꯤꯡ
--------------------------------------------------

Translating:  63%|█████████████████          | 633/1000 [09:39<06:00,  1.02it/s]

[633/1000]
EN: Saudi Arabia enforces qualified crews for marine tourism operations.
MT: ꯁꯧꯗꯤ ꯑꯔꯕꯤꯌꯥꯅꯥ ꯃꯦꯔꯤꯅ ꯇꯨꯔꯤꯖꯝ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡꯒꯤꯗꯃꯛ ꯀꯂꯤꯐꯤꯀꯥꯏꯗꯎꯁꯤꯡ ꯆꯠꯅꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  63%|█████████████████          | 634/1000 [09:40<06:00,  1.02it/s]

[634/1000]
EN: Red Sea unregulated maritime activity concerns addressed by licences.
MT: ꯔꯦꯗ ꯁꯤ ꯑꯟꯔꯦꯒꯨꯂꯦꯇꯦꯗ ꯃꯦꯔꯤꯇꯥꯏꯃ ꯑꯦꯛꯇꯤꯚꯤꯇꯤꯒꯤ ꯋꯥꯐꯝꯁꯤꯡ ꯑꯁꯤ ꯂꯥꯏꯁꯦꯟꯁꯁꯤꯡꯅ ꯋꯥꯔꯣꯏꯁꯤꯟ ꯄꯤ
--------------------------------------------------

Translating:  64%|█████████████████▏         | 635/1000 [09:41<05:45,  1.06it/s]

[635/1000]
EN: Indian cruise tourism gets boost with ten new terminals.
MT: ꯏꯟꯗꯤꯌꯟ ꯀꯖ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯑꯅꯧꯕ ꯇꯔꯃꯤꯅꯦꯜ ꯇꯔꯥꯒ ꯂꯣꯏꯅꯅꯥ ꯆꯥꯎꯈꯠꯄ ꯐꯪ
--------------------------------------------------

Translating:  64%|█████████████████▏         | 636/1000 [09:42<05:47,  1.05it/s]

[636/1000]
EN: Disney Destiny becomes marquee cruise debut of 2025.
MT: ꯗꯤꯁꯅꯤ ꯗꯦꯁꯇꯤꯅꯤ ꯑꯁꯤ ꯏꯪꯁꯣꯛ 2025 ꯒꯤ ꯃꯥꯔꯀꯨꯏ ꯀꯖ ꯗꯦꯕꯇ ꯑꯣꯏꯔꯦ ꯫
--------------------------------------------------

Translating:  64%|█████████████████▏         | 637/1000 [09:43<05:56,  1.02it/s]

[637/1000]
EN: Norwegian Aqua adds fleet capacity to Norwegian Cruise Line.
MT: ꯅꯣꯔꯋꯦꯒꯤ ꯑꯦꯀꯋꯥꯅꯥ ꯅꯣꯔꯕꯦꯒꯤ ꯀꯖ ꯂꯥꯏꯅꯗꯥ ꯐꯂꯤꯇ ꯀꯦꯄꯦꯁꯤꯇꯤ ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  64%|█████████████████▏         | 638/1000 [09:43<05:43,  1.05it/s]

[638/1000]
EN: Royal Caribbean Star of the Seas enters service in 2025.
MT: ꯔꯣꯌꯦꯜ ꯀꯦꯔꯤꯕꯤꯌꯟ ꯁꯥꯔ ꯑꯣꯐ ꯗꯤ ꯁꯤꯖꯅꯥ ꯏꯪ 2025 ꯗꯥ ꯊꯕꯛꯇ ꯆꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  64%|█████████████████▎         | 639/1000 [09:44<05:39,  1.06it/s]

[639/1000]
EN: Cordelia Cruises announces Lakshadweep itineraries from Kochi.
MT: ꯀꯣꯔꯗꯦꯂꯤꯌꯥ ꯀꯨꯏꯖꯦꯁꯅ ꯀꯣꯆꯤꯗꯒꯤ ꯂꯛꯁꯗꯞꯀꯤ ꯂꯝꯕꯤꯁꯤꯡ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  64%|█████████████████▎         | 640/1000 [09:45<05:39,  1.06it/s]

[640/1000]
EN: Water metro connectivity boosts tourism in Kochi backwaters.
MT: ꯋꯥꯇꯔ ꯃꯦꯇ ꯀꯣꯟꯇꯦꯛꯇꯤꯚꯤꯇꯤꯅ ꯀꯣꯆꯤꯒꯤ ꯕꯦꯀꯋꯥꯇꯔꯗꯥ ꯇꯨꯔꯤꯖꯝ ꯍꯦꯟꯒꯠꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  64%|█████████████████▎         | 641/1000 [09:46<05:47,  1.03it/s]

[641/1000]
EN: Mumbai cruise terminal handles record 100,000 passengers this year.
MT: ꯃꯨꯝꯕꯥꯏ ꯀꯖ ꯇꯔꯃꯤꯅꯦꯜꯅꯥ ꯆꯍꯤ ꯑꯁꯤꯗ ꯄꯦꯁꯦꯟꯖꯔ 100, 000 ꯔꯦꯀꯣꯔ ꯇꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  64%|█████████████████▎         | 642/1000 [09:47<05:46,  1.03it/s]

[642/1000]
EN: Ganga Vilas luxury cruise completes successful Brahmaputra season.
MT: ꯒꯪꯒꯥ ꯚꯤꯂꯥꯁ ꯂꯛꯁꯨꯔꯤ ꯀꯖꯅꯥ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯕꯍꯃꯄꯨꯇ ꯁꯤꯖꯟ ꯂꯣꯏꯁꯤꯟ
--------------------------------------------------

Translating:  64%|█████████████████▎         | 643/1000 [09:48<05:17,  1.12it/s]

[643/1000]
EN: Kerala houseboat registrations cross one thousand operational vessels.
MT: ꯀꯦꯔꯂꯥꯒꯤ ꯍꯥꯎꯁꯕꯣꯠ ꯔꯦꯖꯤꯁꯇꯦꯁꯟꯅꯥ ꯑꯣꯄꯔꯦꯁꯅꯦꯜ ꯚꯦꯁꯦꯜ ꯂꯤꯁꯤꯡ ꯑꯃ ꯂꯣꯏꯔꯦ ꯫
--------------------------------------------------

Translating:  64%|█████████████████▍         | 644/1000 [09:49<04:58,  1.19it/s]

[644/1000]
EN: Andaman and Nicobar receive approval for international cruise tourism.
MT: ꯑꯟꯗꯃꯥꯟ ꯑꯃꯁꯨꯡ ꯅꯤꯀꯣꯕꯥꯔꯅꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯀꯖ ꯇꯨꯔꯤꯖꯝꯒꯤꯗꯃꯛ ꯑꯦꯄꯂꯨꯑꯦꯁꯟ ꯐꯪ
--------------------------------------------------

Translating:  64%|█████████████████▍         | 645/1000 [09:49<04:44,  1.25it/s]

[645/1000]
EN: Airbnb relaunches experiences feature for bookings and services.
MT: ꯑꯦꯔ ꯕꯤ ꯑꯦꯟ ꯕꯤꯅꯥ ꯕꯨꯀꯤꯡ ꯑꯃꯁꯨꯡ ꯁꯔꯕꯤꯁꯁꯤꯡꯒꯤ ꯑꯦꯛꯁꯄꯤꯌꯔꯦꯟꯁ ꯐꯤꯆꯔ ꯑꯃꯨꯛ ꯍꯟꯅ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  65%|█████████████████▍         | 646/1000 [09:50<04:59,  1.18it/s]

[646/1000]
EN: Brian Chesky announces Airbnb services complementing home rentals.
MT: ꯕꯌꯥꯟ ꯆꯦꯁꯀꯤꯅꯥ ꯑꯦꯔꯕꯤꯟꯕꯤ ꯁꯔꯕꯤꯁꯁ ꯑꯁꯤ ꯌꯨꯝꯒꯤ ꯔꯦꯟꯇꯦꯜꯁꯤꯡ ꯀꯝꯄꯂꯤꯃꯦꯟꯇ ꯇꯧꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  65%|█████████████████▍         | 647/1000 [09:51<05:01,  1.17it/s]

[647/1000]
EN: Olympic speed skater Arianna Fontana leads Airbnb training rides.
MT: ꯑꯣꯂꯤꯝꯄꯤꯛ ꯁꯄꯤꯗꯀꯦꯇꯔ ꯑꯔꯤꯌꯥꯅꯥ ꯐꯣꯟꯇꯥꯅꯥꯅꯥ ꯑꯦꯔ ꯕꯤ ꯑꯦꯟ ꯕꯤ ꯇꯅꯤꯡ ꯔꯥꯏꯗꯁꯤꯡꯒꯤ ꯂꯨꯆꯤꯡꯏ ꯫
--------------------------------------------------

Translating:  65%|█████████████████▍         | 648/1000 [09:52<04:55,  1.19it/s]

[648/1000]
EN: Airbnb offers Alpine hikes with athlete guides in Italy.
MT: ꯑꯦꯔ ꯕꯤ ꯑꯦꯟ ꯕꯤꯅꯥ ꯏꯇꯂꯤꯗꯥ ꯑꯦꯊꯂꯤꯇ ꯒꯤꯗꯁꯤꯡꯒ ꯂꯣꯏꯅꯅ ꯑꯜꯄꯥꯏꯅ ꯍꯥꯏꯀꯁꯤꯡꯒꯤ ꯈꯨꯗꯣꯡꯆꯥꯕꯥ ꯄꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  65%|█████████████████▌         | 649/1000 [09:53<04:48,  1.22it/s]

[649/1000]
EN: K-pop band SEVENTEEN curates music sessions for Airbnb.
MT: ꯑꯦꯔ ꯕꯤ ꯑꯦꯟ ꯕꯤ ꯒꯤꯗꯃꯛ ꯀꯦ-ꯄꯣꯄ ꯕꯦꯟꯗ ꯁꯦꯚꯦꯟꯇꯤꯟꯅꯥ ꯏꯁꯩꯒꯤ ꯊꯧꯔꯝꯁꯤꯡ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  65%|█████████████████▌         | 650/1000 [09:54<04:50,  1.20it/s]

[650/1000]
EN: Chance the Rapper partners with Airbnb for exclusive experiences.
MT: ꯑꯦꯛꯁꯁꯤꯋꯦꯜ ꯑꯦꯛꯁꯄꯤꯌꯔꯦꯟꯁꯀꯤꯗꯃꯛ ꯑꯦꯔ ꯕꯤ ꯑꯦꯟ ꯕꯤꯒꯥ ꯂꯣꯏꯅꯅ ꯔꯦꯄꯔ ꯄꯥꯔꯇꯦꯅꯔꯁꯤꯡꯒꯤ ꯇꯥꯟꯖ ꯂꯧꯕꯤꯌꯨ ꯫
--------------------------------------------------

Translating:  65%|█████████████████▌         | 651/1000 [09:55<04:46,  1.22it/s]

[651/1000]
EN: Economic uncertainty shifts traveller behaviour toward price sensitivity.
MT: ꯁꯦꯟꯊꯨꯝꯒꯤ ꯑꯔꯦꯞꯄ ꯂꯩꯇꯕꯥ ꯑꯁꯤꯅ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯃꯑꯣꯡ-ꯃꯇꯥꯎꯕꯨ ꯃꯃꯜꯒꯤ ꯃꯇꯥꯡꯗ ꯈꯡꯅꯕ ꯉꯝꯕꯒꯤ ꯃꯥꯏꯀꯩꯗ ꯍꯣꯡꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  65%|█████████████████▌         | 652/1000 [09:55<04:28,  1.30it/s]

[652/1000]
EN: Tourists choose off-the-beaten-path destinations influenced by social media.
MT: ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯅ ꯁꯣꯁꯤꯌꯦꯜ ꯃꯤꯗꯤꯌꯥꯅꯥ ꯏꯊꯤꯜ ꯄꯤꯔꯕꯥ ꯂꯝꯈꯩꯒꯤ ꯃꯄꯥꯟꯗ ꯂꯩꯕ ꯃꯐꯝꯁꯤꯡ ꯈꯟ
--------------------------------------------------

Translating:  65%|█████████████████▋         | 653/1000 [09:56<04:22,  1.32it/s]

[653/1000]
EN: Travelers turn to AI-powered tools for trip planning.
MT: ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯅ ꯇꯞꯂꯥꯏꯅꯤꯡꯒꯤꯗꯃꯛ ꯑꯦꯑꯏ-ꯄꯋꯥꯔ ꯇꯧꯔꯕꯥ ꯇꯨꯜꯁꯤꯡ ꯁꯤꯖꯤꯟꯅ
--------------------------------------------------

Translating:  65%|█████████████████▋         | 654/1000 [09:57<04:12,  1.37it/s]

[654/1000]
EN: Sustainable tourism gains traction among mindful travellers.
MT: ꯁꯁꯇꯦꯅꯦꯕꯜ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯔꯕꯥ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯟꯅꯤꯡꯉꯥꯏ ꯑꯣꯏ
--------------------------------------------------

Translating:  66%|█████████████████▋         | 655/1000 [09:57<03:52,  1.48it/s]

[655/1000]
EN: Responsible travel interest grows among conscious tourists.
MT: ꯈꯪꯍꯧꯔꯕꯥ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯊꯧꯗꯥꯡ ꯂꯧꯔꯕ ꯂꯝꯀꯣꯏꯕꯒꯤ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯄ ꯍꯦꯟꯒꯠꯂꯛ
--------------------------------------------------

Translating:  66%|█████████████████▋         | 656/1000 [09:58<03:49,  1.50it/s]

[656/1000]
EN: Less-crowded destinations attract visitors avoiding overtourism.
MT: ꯃꯤ ꯌꯥꯝꯗꯕ ꯂꯝꯈꯩꯁꯤꯡ ꯑꯁꯤꯅ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯟꯅꯤꯡꯉꯥꯏ ꯑꯣꯏ
--------------------------------------------------

Translating:  66%|█████████████████▋         | 657/1000 [09:59<03:57,  1.44it/s]

[657/1000]
EN: Business travel spending reaches 1.57 trillion dollars in 2025.
MT: ꯏꯪꯁꯣꯛ 2025 ꯗꯥ ꯕꯤꯖꯤꯅꯦꯁ ꯇꯚꯦꯜ ꯆꯥꯗꯤꯡ ꯑꯁꯤ ꯗꯣꯂꯔꯂꯌꯟ ꯌꯧ
--------------------------------------------------

Translating:  66%|█████████████████▊         | 658/1000 [09:59<04:10,  1.37it/s]

[658/1000]
EN: Bleisure travel surge drives business trip extensions for leisure.
MT: ꯏꯖꯔ ꯇꯚꯦꯜꯒꯤ ꯆꯥꯡ ꯍꯦꯟꯒꯠꯂꯛꯄꯅꯥ ꯕꯤꯖꯤꯅꯦꯁꯀꯤ ꯈꯣꯡꯆꯠꯁꯤꯡ ꯃꯇꯝ ꯂꯦꯟꯕꯒꯤꯗꯃꯛꯇ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  66%|█████████████████▊         | 659/1000 [10:00<04:17,  1.33it/s]

[659/1000]
EN: Luxury travel shifts toward immersive experience based vacations.
MT: ꯂꯛꯁꯔꯤ ꯇꯚꯦꯜ ꯑꯁꯤ ꯏꯃꯔꯁꯤꯚ ꯑꯦꯛꯁꯄꯤꯌꯔꯦꯟꯁꯇ ꯌꯨꯝꯐꯝ ꯑꯣꯏꯕ ꯁꯨꯇꯤꯁꯤꯡꯒꯤ ꯃꯥꯏꯀꯩꯗ ꯍꯣꯡꯂꯛꯏ ꯫
--------------------------------------------------

Translating:  66%|█████████████████▊         | 660/1000 [10:01<04:18,  1.31it/s]

[660/1000]
EN: Travvy Awards recognize top industry suppliers in November.
MT: ꯇꯚꯚꯤ ꯑꯦꯋꯥꯔꯗꯅ ꯅꯕꯦꯝꯕꯔꯗꯥ ꯇꯣꯞ ꯏꯟꯗꯁꯇꯒꯤ ꯁꯄꯂꯥꯏꯌꯔꯁꯤꯡꯕꯨ ꯃꯁꯛ ꯈꯪꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  66%|█████████████████▊         | 661/1000 [10:02<04:09,  1.36it/s]

[661/1000]
EN: TravelPulse announces 40 Under 40 honorees for second year.
MT: ꯇꯚꯦꯜꯄꯜꯁꯅꯥ ꯑꯅꯤꯁꯨꯕ ꯆꯍꯤꯒꯤꯗꯃꯛ ꯑꯟꯗꯔ ꯑꯣꯅꯣꯔꯤ 40 ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  66%|█████████████████▊         | 662/1000 [10:02<04:05,  1.38it/s]

[662/1000]
EN: Travel Executive of the Year awarded at Travvy gala.
MT: ꯇꯚꯚꯤ ꯒꯂꯥꯗꯥ ꯏꯌꯔꯒꯤꯚꯦꯕꯦꯜ ꯑꯦꯛꯖꯤꯀꯇꯤꯕꯀꯤ ꯃꯅꯥ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  66%|█████████████████▉         | 663/1000 [10:03<03:52,  1.45it/s]

[663/1000]
EN: New members inducted into Travel Hall of Fame 2025.
MT: 2025 ꯗꯥ ꯇꯚꯦꯜ ꯍꯣꯜ ꯑꯣꯐ ꯐꯦꯝꯗꯥ ꯑꯅꯧꯕ ꯃꯤꯍꯨꯠꯁꯤꯡ ꯌꯥꯎꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  66%|█████████████████▉         | 664/1000 [10:04<03:46,  1.49it/s]

[664/1000]
EN: Young professionals recognized for innovation and leadership.
MT: ꯏꯟꯚꯣꯚꯦꯁꯟ ꯑꯃꯁꯨꯡ ꯂꯤꯗꯔꯁꯤꯞꯀꯤꯗꯃꯛ ꯃꯁꯛ ꯈꯪꯂꯕ ꯌꯨꯕꯥꯐꯦꯁꯅꯦꯜꯁꯤꯡ
--------------------------------------------------

Translating:  66%|█████████████████▉         | 665/1000 [10:04<03:57,  1.41it/s]

[665/1000]
EN: FIFA World Cup 2025 travel bookings exceed host city expectations.
MT: ꯐꯤꯐꯥ ꯋꯥꯔꯂꯗ ꯀꯞ 2025 ꯒꯤ ꯇꯚꯦꯜ ꯕꯨꯀꯤꯡꯅꯥ ꯍꯣꯁꯇ ꯁꯤꯇꯤꯗꯥ ꯄꯥꯝꯖꯕꯗꯒꯤ ꯍꯦꯟ
--------------------------------------------------

Translating:  67%|█████████████████▉         | 666/1000 [10:05<03:55,  1.42it/s]

[666/1000]
EN: Solo female travel bookings increase forty percent year on year.
MT: ꯁꯣꯂꯣ ꯚꯤꯃꯦꯅ ꯇꯚꯦꯜ ꯕꯨꯀꯤꯡꯁꯤꯡ ꯑꯁꯤ ꯆꯍꯤꯗꯥ ꯆꯥꯗ ꯃꯔꯤ ꯍꯦꯟꯒꯠꯂꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  67%|██████████████████         | 667/1000 [10:06<04:10,  1.33it/s]

[667/1000]
EN: Wellness tourism emerges as fastest growing travel segment globally.
MT: ꯋꯦꯂꯅꯦꯁ ꯇꯨꯔꯤꯖꯝ ꯑꯁꯤ ꯃꯥꯂꯦꯝ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯊꯨꯅ ꯆꯥꯎꯈꯠꯂꯛꯂꯤꯕ ꯇꯚꯦꯜ ꯁꯦꯒꯃꯦꯟꯇ ꯑꯃ ꯑꯣꯏꯔꯛ
--------------------------------------------------

Translating:  67%|██████████████████         | 668/1000 [10:07<04:00,  1.38it/s]

[668/1000]
EN: Indian millennials prefer experiential travel over shopping vacations.
MT: ꯚꯥꯔꯠꯀꯤ ꯃꯤꯂꯦꯅꯤꯌꯦꯜꯁꯤꯡꯅ ꯁꯣꯄꯤꯡ ꯁꯨꯇꯤꯁꯤꯡꯒꯤ ꯃꯍꯨꯠꯇ ꯆꯥꯡꯌꯦꯡꯒꯤ ꯑꯣꯏꯕ ꯂꯝꯀꯣꯏꯕꯁꯤꯡ ꯄꯥꯝꯏ ꯫
--------------------------------------------------

Translating:  67%|██████████████████         | 669/1000 [10:07<04:03,  1.36it/s]

[669/1000]
EN: Workation packages gain popularity among remote corporate employees.
MT: ꯋꯥꯔꯀꯦꯁꯟ ꯄꯦꯀꯦꯖꯁꯤꯡ ꯑꯁꯤ ꯔꯤꯃꯣꯠ ꯀꯣꯔꯄꯣꯔꯦꯠ ꯑꯦꯝꯄꯂꯥꯏꯁꯤꯡꯒꯤ ꯃꯔꯛꯇꯥ ꯃꯤꯌꯥꯝꯅ ꯄꯥꯝꯅꯕ ꯑꯣꯏ ꯫
--------------------------------------------------

Translating:  67%|██████████████████         | 670/1000 [10:08<04:05,  1.34it/s]

[670/1000]
EN: Culinary tourism drives foodies to regional Indian destinations.
MT: ꯀꯨꯂꯤꯅꯔꯤ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯆꯤꯟꯖꯥꯛ ꯄꯥꯝꯖꯕꯁꯤꯡꯕꯨ ꯔꯤꯖꯅꯦꯜ ꯏꯟꯗꯤꯌꯟ ꯗꯦꯇꯤꯁꯟꯁꯤꯡꯗ ꯄꯨꯁꯤꯜꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  67%|██████████████████         | 671/1000 [10:09<03:48,  1.44it/s]

[671/1000]
EN: Night tourism initiatives launched by Maharashtra and Karnataka.
MT: ꯃꯍꯥꯔꯥꯁꯇ ꯑꯃꯁꯨꯡ ꯀꯔꯅꯥꯇꯀꯥꯅꯥ ꯅꯥꯏꯇ ꯇꯨꯔꯤꯖꯝ ꯊꯧꯔꯥꯡꯁꯤꯡ ꯍꯧꯒꯠ
--------------------------------------------------

Translating:  67%|██████████████████▏        | 672/1000 [10:09<03:54,  1.40it/s]

[672/1000]
EN: Astro tourism gains ground with dark sky parks in Ladakh.
MT: ꯂꯗꯥꯈꯀꯤ ꯗꯔꯀꯥꯔꯥꯏ ꯄꯥꯔꯛꯁꯤꯡ ꯂꯩꯕꯅꯥ ꯑꯦꯁꯇ ꯇꯨꯔꯤꯖꯝꯗ ꯀꯥꯟꯅꯕ ꯐꯪ
--------------------------------------------------

Translating:  67%|██████████████████▏        | 673/1000 [10:10<03:56,  1.38it/s]

[673/1000]
EN: Film induced tourism boosts Kashmir valley hotel occupancy.
MT: ꯐꯤꯜꯃ ꯏꯟꯗꯁ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯀꯁꯃꯤꯔ ꯚꯦꯂꯤ ꯍꯣꯇꯦꯜ ꯑꯣꯀꯦꯟꯁꯤ ꯍꯦꯟꯒꯠꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  67%|██████████████████▏        | 674/1000 [10:11<03:50,  1.41it/s]

[674/1000]
EN: Wedding tourism contributes five billion dollars to Indian economy.
MT: ꯋꯦꯗꯤꯡ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯑꯦꯀꯣꯅꯣꯃꯤꯗꯥ ꯗꯣꯂꯔ ꯕꯤꯂꯤꯌꯟ ꯃꯉꯥ ꯄꯤ
--------------------------------------------------

Translating:  68%|██████████████████▏        | 675/1000 [10:12<03:47,  1.43it/s]

[675/1000]
EN: India promotes MICE tourism for meetings and exhibitions.
MT: ꯃꯤꯇꯤꯡꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯑꯦꯛꯖꯤꯕꯤꯁꯟꯁꯤꯡꯒꯤꯗꯃꯛ ꯚꯥꯔꯠꯅ ꯃꯥꯏꯁꯤ ꯇꯨꯔꯤꯖꯝꯕꯨ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▎        | 676/1000 [10:12<03:53,  1.39it/s]

[676/1000]
EN: West Bengal develops MICE tourism segments under Mamata Banerjee.
MT: ꯋꯇ ꯕꯦꯡꯒꯜꯅꯥ ꯃꯃꯇꯥ ꯕꯦꯅꯖꯔꯤꯒꯤ ꯃꯈꯥꯗ ꯃꯥꯏꯁꯤ ꯇꯨꯔꯤꯖꯝ ꯁꯦꯒꯃꯦꯟꯇꯁꯤꯡ ꯁꯦꯝꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▎        | 677/1000 [10:13<03:58,  1.36it/s]

[677/1000]
EN: India positions itself as medical value travel destination.
MT: ꯚꯥꯔꯠꯅ ꯃꯁꯥ ꯃꯊꯟꯇ ꯃꯦꯗꯤꯀꯦꯜ ꯚꯦꯜꯌꯨ ꯇꯚꯦꯜ ꯗꯦꯁꯇꯤꯅꯦꯁꯇ ꯑꯣꯏꯔꯦ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▎        | 678/1000 [10:14<03:46,  1.42it/s]

[678/1000]
EN: Wellness tourism positions India as holistic healing leader.
MT: ꯋꯥꯏꯜꯅꯦꯁ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯚꯥꯔꯠꯄꯨ ꯍꯣꯂꯤꯁꯇꯤꯛ ꯍꯤꯂꯤꯡ ꯂꯤꯗꯔ ꯑꯣꯏꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▎        | 679/1000 [10:15<04:17,  1.25it/s]

[679/1000]
EN: Concert tourism attracts international visitors to Indian music festivals.
MT: ꯀꯟꯖꯇ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯃꯖꯤꯀ ꯐꯦꯁꯇꯤꯕꯦꯜꯗꯥ ꯂꯥꯛꯄ ꯃꯤꯌꯣꯏꯁꯤꯡꯕꯨ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▎        | 680/1000 [10:16<04:23,  1.21it/s]

[680/1000]
EN: Gajendra Shekhawat highlights India's concert tourism potential.
MT: ꯒꯖꯦꯟꯗ ꯁꯦꯈꯥꯋꯥꯠꯅ ꯚꯥꯔꯠꯀꯤ ꯏꯁꯩ-ꯆꯥꯔꯣꯡꯒꯤ ꯇꯨꯔꯤꯖꯝꯒꯤ ꯑꯣꯏꯊꯣꯛꯄ ꯌꯥꯕ ꯑꯗꯨ ꯃꯁꯛ ꯇꯥꯛ
--------------------------------------------------

Translating:  68%|██████████████████▍        | 681/1000 [10:17<04:31,  1.18it/s]

[681/1000]
EN: India promotes integrated rehabilitation pathways for medical tourists.
MT: ꯚꯥꯔꯠꯅ ꯃꯦꯗꯤꯀꯦꯜ ꯇꯨꯔꯤꯁꯇꯁꯤꯡꯒꯤꯗꯃꯛ ꯏꯟꯇꯤꯒꯇꯦꯗ ꯔꯤꯍꯦꯕꯂꯤꯇꯦꯁꯟ ꯄꯥꯊꯋꯦꯁꯤꯡ ꯌꯣꯛꯈꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▍        | 682/1000 [10:17<04:09,  1.27it/s]

[682/1000]
EN: Business travel makes significant comeback post pandemic.
MT: ꯄꯦꯟꯗꯃꯤꯛ ꯂꯥꯛꯂꯕ ꯃꯇꯨꯡꯗ ꯕꯤꯖꯤꯅꯦꯁ ꯇꯚꯦꯜꯅꯥ ꯃꯁꯛ ꯊꯣꯛꯄ ꯃꯑꯣꯡꯗ ꯑꯃꯨꯛ ꯍꯜꯂꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▍        | 683/1000 [10:18<04:18,  1.22it/s]

[683/1000]
EN: Companies increase trip volumes and expand travel budgets.
MT: ꯀꯝꯄꯅꯤꯁꯤꯡꯅ ꯇꯄꯀꯤ ꯆꯥꯡ ꯍꯦꯟꯒꯠꯍꯜꯂꯤ ꯑꯃꯁꯨꯡ ꯂꯝꯀꯣꯏꯕꯒꯤ ꯁꯦꯟꯐꯝꯁꯤꯡ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▍        | 684/1000 [10:19<04:30,  1.17it/s]

[684/1000]
EN: In-person collaboration demand drives business travel recovery.
MT: ꯏꯟ-ꯄꯔꯁꯟ ꯀꯣꯂꯣꯕꯥꯔꯦꯁꯟ ꯗꯤꯃꯥꯟꯗꯅ ꯕꯤꯖꯤꯅꯦꯁ ꯇꯚꯦꯜ ꯔꯤꯀꯥꯎꯔꯤ ꯊꯧꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▍        | 685/1000 [10:20<04:39,  1.13it/s]

[685/1000]
EN: Hyderabad International Convention Centre hosts global pharmaceutical summit.
MT: ꯍꯥꯏꯗꯕꯥꯗ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯀꯟꯚꯦꯟꯁꯟ ꯁꯦꯟꯇꯔꯅꯥ ꯒ ꯭ ꯂꯣꯕꯦꯜ ꯐꯥꯔꯃꯥꯁꯤꯌꯨꯇꯤꯀꯦꯜ ꯁꯝꯃꯤꯠ ꯄꯥꯡꯊꯣꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  69%|██████████████████▌        | 686/1000 [10:21<04:29,  1.17it/s]

[686/1000]
EN: Bharat Mandapam witnesses record MICE bookings for fiscal year.
MT: ꯚꯥꯔꯠ ꯃꯟꯗꯄꯃꯗꯥ ꯁꯦꯜ-ꯊꯨꯝꯒꯤ ꯆꯍꯤꯒꯤꯗꯃꯛ ꯃꯥꯏꯁꯤ ꯕꯨꯀꯤꯡꯁꯤꯡ ꯔꯦꯀꯣꯔ ꯇꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  69%|██████████████████▌        | 687/1000 [10:22<05:02,  1.04it/s]

[687/1000]
EN: Medical tourism arrivals cross pre-Covid levels with six lakh visitors.
MT: ꯃꯦꯗꯤꯀꯦꯜ ꯇꯨꯔꯤꯖꯝ ꯂꯥꯛꯄꯥꯁꯤꯡꯅ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯇꯔꯨꯛ ꯄꯨꯗꯨꯅ-ꯀꯣꯕꯤꯗ ꯂꯦꯚꯦꯜꯁꯤꯡ ꯐꯥꯎ
--------------------------------------------------

Translating:  69%|██████████████████▌        | 688/1000 [10:23<04:44,  1.10it/s]

[688/1000]
EN: AYUSH wellness centres attract foreign tourists for traditional treatments.
MT: ꯑꯥꯌꯨꯁ ꯋꯦꯜꯅꯦꯁ ꯁꯦꯟꯇꯔꯁꯤꯡ ꯑꯁꯤꯅ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯕꯨ ꯊꯥꯏꯅꯗꯒꯤ ꯆꯠꯅꯔꯕꯥ ꯂꯥꯌꯦꯡꯁꯤꯡꯒꯤꯗꯃꯛꯇ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  69%|██████████████████▌        | 689/1000 [10:24<04:34,  1.13it/s]

[689/1000]
EN: Delhi NCR hotels report seventy percent occupancy from corporate travellers.
MT: ꯗꯤꯜꯂꯤ ꯑꯦꯟ ꯁꯤ ꯑꯥꯔ ꯍꯣꯇꯦꯜꯁꯤꯡꯅꯥ ꯀꯣꯔꯄꯣꯔꯦꯠ ꯇꯚꯦꯂꯔꯁꯤꯡꯗꯒꯤ ꯆꯥꯗꯥ 70 ꯑꯣꯀꯦꯟꯁꯤ ꯐꯪꯉꯤ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝ
--------------------------------------------------

Translating:  69%|██████████████████▋        | 690/1000 [10:24<04:27,  1.16it/s]

[690/1000]
EN: Maha Kumbh infrastructure delivers long-term tourism economic benefits.
MT: ꯃꯍꯥ ꯀꯨꯝꯚ ꯏꯟꯐꯁꯇꯛꯆꯔꯅꯥ ꯂꯥꯡ-ꯇꯔꯃ ꯇꯨꯔꯤꯖꯝ ꯏꯀꯅꯣꯃꯤꯀꯦꯜ ꯕꯦꯅꯤꯐꯤꯇꯁꯤꯡ ꯄꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  69%|██████████████████▋        | 691/1000 [10:25<04:20,  1.19it/s]

[691/1000]
EN: Venice entry fee revenues fund city upkeep and travel management.
MT: ꯚꯦꯅꯤꯁ ꯑꯦꯟꯇꯤ ꯐꯤ ꯔꯦꯚꯤꯅꯁ ꯐꯟꯗ ꯁꯤꯇꯤ ꯎꯄꯄꯤꯅꯦꯟꯇ ꯑꯃꯁꯨꯡ ꯇꯚꯦꯜ ꯃꯦꯅꯦꯃꯦꯅꯇ
--------------------------------------------------

Translating:  69%|██████████████████▋        | 692/1000 [10:26<04:24,  1.16it/s]

[692/1000]
EN: Critics question Venice day-tripper fee effectiveness for crowd control.
MT: ꯚꯤꯅꯤꯁ ꯗꯦ-ꯥꯏꯄꯔ ꯐꯤ ꯑꯦꯐꯦꯛꯇꯤꯚꯦꯟꯁꯤꯕꯨ ꯀꯥꯎꯗ ꯀꯟꯇꯣꯜ ꯇꯧꯅꯕꯒꯤꯗꯃꯛꯇꯤꯛꯁꯅꯥ ꯈꯟꯅ
--------------------------------------------------

Translating:  69%|██████████████████▋        | 693/1000 [10:27<04:11,  1.22it/s]

[693/1000]
EN: Bulgaria joins Eurozone as twenty-first member on January 1 2026.
MT: ꯏꯪꯁꯣꯛꯒꯤ ꯖꯅꯨꯋꯥꯔꯤꯗꯥ ꯕꯂꯒꯦꯔꯤꯌꯥꯅꯥ ꯌꯨꯔꯣꯖꯣꯅꯗꯥ ꯑꯍꯥꯟꯕ ꯃꯦꯝꯕꯔ ꯑꯣꯏꯅ ꯌꯥꯎ
--------------------------------------------------

Translating:  69%|██████████████████▋        | 694/1000 [10:27<04:00,  1.27it/s]

[694/1000]
EN: Both Lev and Euro accepted in Bulgaria during January transition.
MT: ꯂꯦꯚ ꯑꯃꯁꯨꯡ ꯌꯨꯔꯣ ꯑꯅꯤꯃꯛꯅ ꯖꯅꯨꯋꯥꯔꯤ ꯇꯥꯟꯖꯤꯁꯟꯒꯤ ꯃꯇꯝꯗ ꯕꯂꯒꯦꯔꯤꯌꯥꯗꯥ ꯑꯌꯥꯕ ꯄꯤ
--------------------------------------------------

Translating:  70%|██████████████████▊        | 695/1000 [10:29<04:21,  1.17it/s]

[695/1000]
EN: Lufthansa announces daily Frankfurt-Bengaluru flights starting March 2026.
MT: ꯂꯨꯐꯊꯥꯟꯁꯥꯅꯥ ꯏꯪꯁꯣꯛꯒꯤ ꯃꯥꯔꯗꯒꯤ ꯅꯨꯃꯤꯠ ꯈꯨꯗꯤꯡꯒꯤ ꯐꯟꯐꯔꯇ- ꯕꯦꯡꯒꯂꯨꯔꯨꯗꯥ ꯄꯥꯏꯔꯛꯀꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  70%|██████████████████▊        | 696/1000 [10:29<04:00,  1.27it/s]

[696/1000]
EN: Alliance Air introduces direct flights from Delhi to Darbhanga.
MT: ꯑꯦꯂꯥꯏꯟꯁ ꯑꯦꯌꯔꯅꯥ ꯗꯤꯜꯂꯤꯗꯒꯤ ꯗꯥꯔꯚꯪꯒꯥ ꯐꯥꯎꯕ ꯍꯛꯊꯦꯡꯅꯅ ꯐꯥꯏꯇꯁꯤꯡ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  70%|██████████████████▊        | 697/1000 [10:30<03:53,  1.30it/s]

[697/1000]
EN: Emirates deploys A380 on Ahmedabad-Dubai route for winter season.
MT: ꯑꯦꯃꯤꯔꯦꯠꯁꯅ ꯅꯤꯡꯊꯝꯊꯥꯒꯤꯗꯃꯛ ꯑꯍꯃꯗꯕꯥꯗ- ꯗꯨꯕꯥꯏ ꯂꯝꯕꯤꯗꯥ ꯑꯦ380 ꯁꯤꯖꯤꯟꯅ
--------------------------------------------------

Translating:  70%|██████████████████▊        | 698/1000 [10:31<03:40,  1.37it/s]

[698/1000]
EN: fly91 commences operations from Goa to Hyderabad and Pune.
MT: ꯂꯥꯏ91 ꯑꯁꯤ ꯒꯣꯋꯥꯗꯒꯤ ꯍꯥꯏꯗꯕꯥꯗ ꯑꯃꯁꯨꯡ ꯄꯨꯅꯦ ꯐꯥꯎꯕꯒꯤ ꯊꯕꯛ ꯍꯧ
--------------------------------------------------

Translating:  70%|██████████████████▊        | 699/1000 [10:31<03:37,  1.39it/s]

[699/1000]
EN: British Airways resumes London-Chennai service after four-year hiatus.
MT: ꯕꯇꯤꯁ ꯑꯦꯌꯔꯋꯦꯖꯅ ꯆꯍꯤ ꯃꯔꯤꯒꯤ ꯃꯇꯨꯡꯗ ꯂꯟꯗꯟ-ꯆꯦꯟꯅꯥꯏ ꯁꯔꯕꯤꯁ ꯑꯃꯨꯛ ꯍꯟꯅ ꯍꯧ
--------------------------------------------------

Translating:  70%|██████████████████▉        | 700/1000 [10:32<03:42,  1.35it/s]

[700/1000]
EN: Go First employees protest outside NCLT over unpaid salaries.
MT: ꯒꯣ ꯐꯔꯁꯠ ꯏꯝꯄꯂꯥꯏꯖꯅꯥ ꯑꯦꯟ.ꯁꯤ. ꯑꯦꯜ.ꯇꯤ.ꯒꯤ ꯃꯄꯥꯟꯗ ꯁꯦꯜ ꯊꯤꯗꯕꯗꯥ ꯋꯥꯀꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  70%|██████████████████▉        | 701/1000 [10:33<04:00,  1.24it/s]

[701/1000]
EN: Saudi carrier Flynas plans direct Riyadh-Lucknow operations by April.
MT: ꯁꯧꯗꯤ ꯀꯦꯔꯤꯌꯔ ꯐꯅꯥꯏꯅꯥꯁꯅꯥ ꯑꯦꯄꯜ ꯐꯥꯎꯕꯗ ꯔꯤꯌꯥꯗ-ꯂꯀꯅꯣ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡ ꯗꯥꯏꯔꯦꯛꯇ ꯇꯧꯅꯕ ꯊꯧꯔꯥꯡ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  70%|██████████████████▉        | 702/1000 [10:34<03:58,  1.25it/s]

[702/1000]
EN: Flybig announces daily flights from Guwahati to Imphal and Agartala.
MT: ꯂꯥꯏꯕꯤꯒꯅꯥ ꯒꯨꯋꯥꯍꯥꯇꯤꯗꯒꯤ ꯏꯝꯐꯣꯜ ꯑꯃꯁꯨꯡ ꯑꯒꯔꯇꯂꯥ ꯐꯥꯎꯕꯒꯤ ꯅꯨꯃꯤꯠ ꯈꯨꯗꯤꯡꯒꯤ ꯐꯥꯏꯇꯁꯤꯡ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  70%|██████████████████▉        | 703/1000 [10:35<04:14,  1.17it/s]

[703/1000]
EN: Kolkata airport wins cleanest airport award in 15-25 million category.
MT: ꯀꯣꯜꯀꯥꯇꯥ ꯑꯦꯌꯔꯄꯣꯔꯇꯅꯥ ꯀꯦꯇꯦꯒꯣꯔꯤ ꯃꯤꯂ ꯭ ꯌꯟ- ꯐꯥꯎꯕ ꯑꯣꯏꯔꯗꯨꯅ ꯀꯂꯦꯅꯦꯁꯇ ꯑꯦꯔꯕꯥꯣꯔꯇ ꯑꯦꯋꯥꯔ ꯐꯪ
--------------------------------------------------

Translating:  70%|███████████████████        | 704/1000 [10:35<04:05,  1.20it/s]

[704/1000]
EN: Patna airport's new terminal to handle forty lakh passengers annually.
MT: ꯆꯍꯤꯗꯥ ꯄꯇꯅꯥ ꯑꯦꯌꯔꯄꯣꯔꯇꯀꯤ ꯑꯅꯧꯕ ꯇꯔꯃꯤꯅꯦꯜꯅꯥ ꯄꯦꯁꯦꯟꯖꯔ ꯂꯥꯈ ꯍꯦꯟꯗꯜ ꯇꯧꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  70%|███████████████████        | 705/1000 [10:36<03:52,  1.27it/s]

[705/1000]
EN: Fog forces thirty-two flight diversions at Chandigarh airport.
MT: ꯆꯟꯗꯤꯒꯔ ꯑꯦꯌꯔꯄꯣꯔꯇꯇꯥ ꯐꯥꯏꯇ ꯑꯍꯨꯝꯂꯛ ꯗꯤꯚꯔꯁꯟ ꯇꯧꯍꯟꯕꯥ ꯃꯊꯧ ꯇꯥꯔꯤ ꯫
--------------------------------------------------

Translating:  71%|███████████████████        | 706/1000 [10:37<03:48,  1.29it/s]

[706/1000]
EN: Ethiopian Airlines considers Mumbai and Delhi as new African hub.
MT: ꯏꯊꯤꯑꯣꯄꯤꯌꯥꯟ ꯑꯦꯌꯔꯂꯥꯏꯟꯁꯅꯥ ꯃꯨꯝꯕꯥꯏ ꯑꯃꯁꯨꯡ ꯗꯤꯜꯂꯤꯕꯨ ꯑꯐꯀꯥꯒꯤ ꯑꯍꯥꯟꯕꯥ ꯃꯐꯝ ꯑꯃ ꯑꯣꯏꯅ ꯂꯧ
--------------------------------------------------

Translating:  71%|███████████████████        | 707/1000 [10:38<03:42,  1.31it/s]

[707/1000]
EN: IndiGo passenger dies aboard Delhi-Bengaluru flight mid-air.
MT: ꯗꯤꯜꯂꯤ- ꯕꯦꯡ ꯭ ꯒꯂꯨꯔꯨ ꯐꯥꯏꯇꯗꯥ ꯏꯟꯗꯤꯒꯣ ꯄꯦꯁꯦꯟꯖꯔ ꯁꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  71%|███████████████████        | 708/1000 [10:38<03:39,  1.33it/s]

[708/1000]
EN: VietJet Air announces daily Hanoi-Ahmedabad service from December.
MT: ꯚꯤꯌꯦꯇꯖꯦꯠ ꯑꯦꯌꯔꯅꯥ ꯗꯤꯁꯦꯝꯕꯔꯗꯒꯤ ꯍꯅꯣꯏ-ꯍꯃꯦꯗꯥꯕꯥꯗ ꯅꯨꯃꯤꯠ ꯈꯨꯗꯤꯡꯒꯤ ꯁꯔꯕꯤꯁ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  71%|███████████████████▏       | 709/1000 [10:39<03:24,  1.42it/s]

[709/1000]
EN: Odisha government approves ten new tourism circuits for development.
MT: ꯑꯣꯔꯤꯁꯥ ꯁꯔꯀꯥꯔꯅꯥ ꯆꯥꯎꯈꯠꯅꯕꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯇꯨꯔꯤꯖꯝ ꯁꯔꯀꯤꯇ ꯇꯔꯥ ꯑꯌꯥꯕ ꯄꯤꯔꯦ ꯫
--------------------------------------------------

Translating:  71%|███████████████████▏       | 710/1000 [10:40<03:16,  1.48it/s]

[710/1000]
EN: Madhya Pradesh unveils film tourism policy with 25 percent subsidy.
MT: ꯃꯙꯅꯥ ꯁꯕꯁꯤꯗꯤ ꯆꯥꯗꯒꯥ ꯂꯣꯏꯅꯅ ꯐꯤꯜꯃ ꯇꯨꯔꯤꯖꯝ ꯄꯣꯂꯤꯁꯤ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  71%|███████████████████▏       | 711/1000 [10:40<03:10,  1.51it/s]

[711/1000]
EN: Gujarat grants industry status to homestays and farmstays.
MT: ꯒꯨꯖꯔꯥꯠꯅ ꯍꯣꯝꯇꯦ ꯑꯃꯁꯨꯡ ꯐꯥꯔꯃꯇꯦꯗ ꯏꯟꯗꯁꯇꯇꯤꯒꯤ ꯊꯥꯛ ꯄꯤ ꯫
--------------------------------------------------

Translating:  71%|███████████████████▏       | 712/1000 [10:41<03:09,  1.52it/s]

[712/1000]
EN: Himachal Pradesh caps tourist entry to Manali and Rohtang Pass.
MT: ꯍꯤꯃꯥꯁꯥꯜꯗꯒꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯅ ꯃꯅꯥꯂꯤ ꯑꯃꯁꯨꯡ ꯔꯣꯍꯇꯥꯡ ꯄꯥꯁꯇ ꯆꯪꯁꯤꯜꯂꯛ
--------------------------------------------------

Translating:  71%|███████████████████▎       | 713/1000 [10:42<03:16,  1.46it/s]

[713/1000]
EN: Kerala launches responsible tourism mission for waste-free destinations.
MT: ꯀꯦꯔꯂꯥꯅꯥ ꯋꯇ-ꯐ ꯗꯦꯅꯦꯁꯟꯒꯤꯗꯃꯛ ꯔꯦꯖꯤꯄꯂꯦꯇꯤꯕ ꯇꯨꯔꯤꯖꯝ ꯃꯤꯁꯟ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  71%|███████████████████▎       | 714/1000 [10:42<03:25,  1.39it/s]

[714/1000]
EN: Australia removes minimum bank balance requirement for Indian student visas.
MT: ꯑꯣꯁꯇꯂꯤꯌꯥꯅꯥ ꯏꯟꯗꯤꯌꯟꯗꯦꯟꯇ ꯚꯤꯖꯥꯒꯤ ꯃꯤꯅꯤꯃꯃꯜ ꯕꯦꯡꯀ ꯕꯦꯂꯦꯟꯁꯀꯤ ꯃꯊꯧ ꯇꯥꯕꯥ ꯑꯗꯨ ꯂꯧꯊꯣꯛ
--------------------------------------------------

Translating:  72%|███████████████████▎       | 715/1000 [10:43<03:33,  1.33it/s]

[715/1000]
EN: UK introduces Electronic Travel Authorisation for Indian passport holders.
MT: ꯌꯨꯀꯦꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯄꯥꯁꯄꯣꯔꯇ ꯍꯣꯜꯗꯔꯁꯤꯡꯒꯤꯗꯃꯛ ꯏꯂꯦꯛꯇꯅꯤꯛ ꯇꯚꯦꯜ ꯑꯣꯊꯔꯤꯖꯦꯁꯟ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  72%|███████████████████▎       | 716/1000 [10:44<03:32,  1.33it/s]

[716/1000]
EN: Saudi Arabia extends stopover visa validity from four to ninety-six hours.
MT: ꯁꯧꯗꯤ ꯑꯔꯦꯕꯤꯌꯥꯅꯥ ꯁꯇꯣꯞꯑꯣꯚꯔ ꯚꯤꯖꯥꯒꯤ ꯕꯦꯂꯤꯗꯤꯇꯤ ꯄꯨꯡ ꯃꯔꯤꯗꯒꯤ 95 ꯐꯥꯎꯕ ꯍꯦꯟꯒꯠ
--------------------------------------------------

Translating:  72%|███████████████████▎       | 717/1000 [10:45<03:31,  1.34it/s]

[717/1000]
EN: Malaysia grants thirty-day visa-free entry to Indian nationals till December.
MT: ꯃꯂꯦꯁꯤꯌꯥꯅꯥ ꯗꯤꯁꯦꯝꯕꯔ ꯐꯥꯎꯕꯗ ꯚꯥꯔꯠꯀꯤ ꯅꯦꯁ ꯭ ꯅꯦꯜꯁꯤꯡꯗ ꯅꯨꯃꯤꯠ ꯑꯍꯨꯝꯅꯤꯒꯤ ꯚꯤꯖꯥ-ꯐ ꯑꯦꯟꯔꯤ ꯄꯤ
--------------------------------------------------

Translating:  72%|███████████████████▍       | 718/1000 [10:45<03:23,  1.39it/s]

[718/1000]
EN: Thailand extends visa-free stay for Indians from thirty to sixty days.
MT: ꯊꯥꯏꯂꯦꯟꯗꯅꯥ ꯚꯥꯔꯠ ꯃꯆꯥꯁꯤꯡꯒꯤ ꯚꯤꯖꯥ ꯌꯥꯎꯗꯅ ꯂꯩꯕꯒꯤ ꯃꯇꯝ ꯑꯁꯤ ꯅꯨꯃꯤꯠ ꯑꯍꯨꯝꯗꯒꯤ ꯇꯔꯥꯃꯥꯇꯤ ꯐꯥꯎꯕ ꯍꯦꯟꯒꯠ
--------------------------------------------------

Translating:  72%|███████████████████▍       | 719/1000 [10:46<03:26,  1.36it/s]

[719/1000]
EN: Indonesia proposes visa-free entry for Indian tourists to boost Bali arrivals.
MT: ꯏꯟꯗꯣꯅꯦꯁꯤꯌꯥꯅꯥ ꯕꯥꯂꯤꯗꯒꯤ ꯂꯥꯛꯄ ꯍꯦꯟꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯚꯤꯖꯥ ꯌꯥꯎꯗꯅ ꯆꯪꯐꯝ ꯁꯦꯝꯅꯕ ꯋꯥꯐꯝ ꯊꯝ
--------------------------------------------------

Translating:  72%|███████████████████▍       | 720/1000 [10:47<03:34,  1.31it/s]

[720/1000]
EN: European Parliament approves ETIAS system launch for mid-2026.
MT: ꯌꯨꯔꯣꯄꯤꯌꯟ ꯄꯥꯔꯂꯤꯌꯥꯃꯦꯟꯇꯅꯥ ꯏꯪꯁꯣꯛꯒꯤ ꯃꯌꯥꯏ ꯆꯜꯂꯛꯄꯗ ꯏꯇꯤꯑꯦꯑꯦꯁ ꯁꯤꯁꯇꯦꯝ ꯂꯣꯆ ꯇꯧꯕ ꯌꯥꯔꯦ ꯫
--------------------------------------------------

Translating:  72%|███████████████████▍       | 721/1000 [10:48<03:41,  1.26it/s]

[721/1000]
EN: Sri Lanka cabinet approves visa-free entry for nationals of thirty-five countries.
MT: ꯂꯡꯀꯥ ꯀꯦꯕꯤꯅꯦꯠꯅꯥ ꯂꯩꯕꯥꯛ 35ꯒꯤ ꯅꯦꯁ ꯭ ꯅꯦꯜꯁꯤꯡꯒꯤꯗꯃꯛ ꯚꯤꯖꯥ-ꯐ ꯑꯦꯟꯇ ꯑꯌꯥꯕ ꯄꯤꯔꯦ ꯫
--------------------------------------------------

Translating:  72%|███████████████████▍       | 722/1000 [10:48<03:26,  1.35it/s]

[722/1000]
EN: Waives visa fees for Indian senior citizens above sixty-five years.
MT: ꯆꯍꯤ ꯇꯔꯨꯛ- ꯃꯉꯥꯒꯤ ꯃꯊꯛꯇ ꯂꯩꯕ ꯏꯟꯗꯤꯌꯟ ꯁꯦꯅꯤꯌꯔ ꯁꯤꯇꯤꯖꯟꯁꯤꯡꯒꯤ ꯚꯤꯖꯥ ꯐꯤꯁꯤꯡ ꯂꯧꯊꯣꯛꯏ ꯫
--------------------------------------------------

Translating:  72%|███████████████████▌       | 723/1000 [10:49<03:30,  1.31it/s]

[723/1000]
EN: Bhutan revises Sustainable Development Fee to one thousand two hundred rupees.
MT: ꯚꯨꯇꯥꯟꯅ ꯁꯁꯇꯦꯅꯦꯁꯇꯦꯕꯜ ꯗꯦꯚꯂꯞꯃꯦꯟꯇ ꯐꯤ ꯑꯁꯤ ꯂꯨꯄꯥ ꯆꯥꯃ ꯂꯤꯁꯤꯡ ꯑꯅꯤꯗ ꯔꯤꯚꯥꯏꯖ ꯇꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  72%|███████████████████▌       | 724/1000 [10:50<03:26,  1.33it/s]

[724/1000]
EN: Nepal allows Indian tourists to pay in rupees at immigration checkpoints.
MT: ꯅꯦꯄꯥꯜꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯕꯨ ꯏꯃꯤꯒꯦꯁꯟ ꯆꯦꯛꯄꯣꯏꯟꯇꯁꯤꯡꯗ ꯂꯨꯄꯥꯗꯥ ꯁꯦꯜ ꯄꯤꯕꯒꯤ ꯑꯌꯥꯕ ꯄꯤ
--------------------------------------------------

Translating:  72%|███████████████████▌       | 725/1000 [10:51<03:22,  1.36it/s]

[725/1000]
EN: Myanmar junta extends e-visa facility for Indian travellers.
MT: ꯃ ꯭ ꯌꯥꯟꯃꯥꯔ ꯖꯟꯇꯥꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯏ-ꯚꯤꯖꯥ ꯐꯦꯁꯤꯂꯤꯇꯤ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  73%|███████████████████▌       | 726/1000 [10:52<03:30,  1.30it/s]

[726/1000]
EN: Mauritius scraps PCR test requirement for fully vaccinated Indian visitors.
MT: ꯃꯣꯔꯤꯁꯁꯅ ꯃꯄꯨꯡꯐꯥꯅꯥ ꯕꯦꯛꯁꯤꯅꯦꯁꯟ ꯇꯧꯔꯕꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯄꯤ ꯁꯤ ꯑꯥꯔ ꯇꯦꯁꯇ ꯃꯊꯧ ꯇꯥꯕ ꯑꯗꯨ ꯂꯧꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  73%|███████████████████▋       | 727/1000 [10:52<03:27,  1.32it/s]

[727/1000]
EN: Kenya removes visa requirement for all Indian passport holders.
MT: ꯀꯦꯅꯦꯌꯥꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯄꯥꯁꯄꯣꯔꯇ ꯍꯣꯜꯗꯔ ꯄꯨꯝꯅꯃꯛꯀꯤ ꯚꯤꯖꯥ ꯃꯊꯧ ꯇꯥꯕꯥ ꯂꯧꯊꯣꯛ
--------------------------------------------------

Translating:  73%|███████████████████▋       | 728/1000 [10:53<03:23,  1.33it/s]

[728/1000]
EN: Rajasthan government launches mobile app for heritage hotel bookings.
MT: ꯔꯥꯖꯁꯊꯥꯟ ꯁꯔꯀꯥꯔꯅꯥ ꯍꯦꯔꯤꯇꯦꯖ ꯍꯣꯇꯦꯜ ꯕꯨꯀꯤꯡꯒꯤꯗꯃꯛ ꯃꯣꯕꯥꯏꯜ ꯑꯦꯞ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  73%|███████████████████▋       | 729/1000 [10:54<03:22,  1.34it/s]

[729/1000]
EN: Assam receives fifty-five lakh domestic tourists during 2024-2025.
MT: ꯏꯪꯁꯣꯛ- ꯒꯤ ꯃꯅꯨꯡꯗ ꯑꯁꯥꯝꯗꯥ ꯗꯣꯃꯦꯁꯇꯤꯛ ꯇꯨꯔꯤꯁꯇ ꯂꯥꯈ ꯃꯉꯥ ꯐꯪ
--------------------------------------------------

Translating:  73%|███████████████████▋       | 730/1000 [10:55<03:26,  1.31it/s]

[730/1000]
EN: Hemanta Biswa Sarma credits improved law and order for tourism growth.
MT: ꯍꯦꯃꯟꯇ ꯕꯤꯁꯋꯥ ꯁꯔꯃꯥꯅꯥ ꯇꯨꯔꯤꯖꯝ ꯆꯥꯎꯈꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯂꯣ ꯑꯃꯁꯨꯡ ꯑꯣꯔꯗꯔ ꯐꯒꯠꯍꯟꯈꯤꯕꯒꯤ ꯃꯅꯥ ꯄꯤ
--------------------------------------------------

Translating:  73%|███████████████████▋       | 731/1000 [10:55<03:16,  1.37it/s]

[731/1000]
EN: Madhya Pradesh records 112.1 million tourist visits in 2024.
MT: ꯃꯙ ꯄꯗꯥ ꯏꯪ 2024 ꯗꯥ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯂꯥꯛꯄꯥ ꯆꯦꯖꯟ
--------------------------------------------------

Translating:  73%|███████████████████▊       | 732/1000 [10:56<03:17,  1.35it/s]

[732/1000]
EN: Meghalaya welcomes twenty-one lakh visitors crossing pre-pandemic figures.
MT: ꯃꯦꯘꯂꯌꯅꯥ ꯄꯦꯟꯗꯃꯤꯛ ꯃꯃꯥꯡꯗ ꯂꯥꯛꯄꯥ ꯃꯁꯤꯡ ꯂꯥꯈ 21 ꯐꯥꯎꯕꯥ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯕꯨ ꯊꯥꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  73%|███████████████████▊       | 733/1000 [10:57<03:16,  1.36it/s]

[733/1000]
EN: Jammu and Kashmir registers two crore tourist footfall in 2025.
MT: ꯏꯪꯁꯣꯛ 2025 ꯗꯥ ꯖꯝꯃꯨ ꯑꯃꯁꯨꯡ ꯀꯁꯃꯤꯔꯗꯥ ꯂꯝꯀꯣꯏꯕ ꯀꯔꯣꯔ ꯑꯅꯤ ꯂꯥꯛ
--------------------------------------------------

Translating:  73%|███████████████████▊       | 734/1000 [10:58<03:24,  1.30it/s]

[734/1000]
EN: LG Manoj Sinha announces highest ever tourist arrival in Kashmir Valley.
MT: ꯑꯦꯜ.ꯖꯤ. ꯃꯅꯣꯖ ꯁꯤꯟꯍꯥꯅꯥ ꯀꯁꯃꯤꯔ ꯋꯥꯂꯤꯗꯥ ꯍꯧꯖꯤꯛ ꯐꯥꯎꯕꯗ ꯋꯥꯡꯕꯥ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯛꯂꯦ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  74%|███████████████████▊       | 735/1000 [10:58<03:23,  1.30it/s]

[735/1000]
EN: Lakshadweep receives eighty-three thousand visitors after PM Modi visit.
MT: ꯙꯥꯟ ꯃꯟꯇ ꯃꯣꯗꯤꯒꯤ ꯈꯣꯡꯆꯠꯀꯤ ꯃꯇꯨꯡꯗ ꯂꯛꯁꯗꯄꯇꯥ ꯂꯝꯀꯣꯏꯕ ꯂꯤꯁꯤꯡ 80- ꯐꯪ
--------------------------------------------------

Translating:  74%|███████████████████▊       | 736/1000 [10:59<03:29,  1.26it/s]

[736/1000]
EN: Uttarakhand witnesses five crore pilgrim visits to Char Dham shrines.
MT: ꯎꯠꯇꯔꯥꯈꯟꯗꯗꯥ ꯆꯔ ꯙꯥꯃ ꯂꯥꯏꯁꯡꯗꯥ ꯂꯥꯏꯐꯝ ꯆꯠꯄꯒꯤ ꯃꯤꯑꯣꯏ ꯀꯔꯣꯔ ꯃꯉꯥ ꯂꯥꯛꯄꯥ ꯎ
--------------------------------------------------

Translating:  74%|███████████████████▉       | 737/1000 [11:00<03:26,  1.28it/s]

[737/1000]
EN: Pushkar fair attracts fifteen lakh tourists including thirty thousand foreigners.
MT: ꯄꯨꯁꯀꯔ ꯃꯦꯂꯥꯅꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯃꯤꯑꯣꯏ ꯂꯤꯁꯤꯡ ꯑꯍꯨꯝꯃꯨꯛ ꯌꯥꯎꯅ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ 15 ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  74%|███████████████████▉       | 738/1000 [11:01<03:22,  1.30it/s]

[738/1000]
EN: Surajkund Mela records forty-eight percent increase in international participation.
MT: ꯁꯨꯔꯖꯀꯨꯟꯗ ꯃꯦꯂꯥꯅꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯁꯔꯨꯛ ꯌꯥꯕꯒꯤ ꯆꯥꯡ ꯆꯥꯗ 48 ꯍꯦꯟꯒꯠꯂꯛꯄꯒꯤ ꯔꯦꯀꯣꯔ
--------------------------------------------------

Translating:  74%|███████████████████▉       | 739/1000 [11:01<03:25,  1.27it/s]

[739/1000]
EN: Singapore welcomes 1.2 million Indian visitors becoming top source market.
MT: ꯁꯤꯡꯒꯥꯄꯨꯔꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈꯕꯨ ꯑꯍꯥꯟꯕꯥ ꯁꯣꯁꯔ ꯃꯥꯔꯀꯦꯇ ꯑꯣꯏꯔꯛꯄꯗꯥ ꯊꯥꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  74%|███████████████████▉       | 740/1000 [11:02<03:21,  1.29it/s]

[740/1000]
EN: Dubai hosts record 2.1 million Indian tourists in first half 2025.
MT: ꯏꯪꯁꯣꯛ 2025 ꯒꯤ ꯑꯍꯥꯟꯕ ꯁꯔꯨꯛꯗꯥ ꯗꯕꯥꯏꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯒꯤ ꯔꯦꯀꯣꯔ ꯇꯧ
--------------------------------------------------

Translating:  74%|████████████████████       | 741/1000 [11:03<03:13,  1.34it/s]

[741/1000]
EN: Thailand receives 1.8 million Indian travellers during January-October period.
MT: ꯊꯥꯏꯂꯦꯟꯗꯗꯥ ꯖꯅꯨꯋꯥꯔꯤꯗꯒꯤ ꯑꯣꯛꯇꯣꯕꯔ ꯐꯥꯎꯕꯒꯤ ꯃꯅꯨꯡꯗ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯐꯪ
--------------------------------------------------

Translating:  74%|████████████████████       | 742/1000 [11:04<03:22,  1.27it/s]

[742/1000]
EN: Maldives sees forty percent drop in Indian tourist arrivals amid diplomatic row.
MT: ꯃꯜꯗꯤꯕꯁꯇ ꯗꯤꯄꯇꯣꯃꯤꯀꯦꯜ ꯔꯥꯎꯒꯤ ꯃꯔꯛꯗꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕꯥ ꯂꯥꯛꯄꯥ ꯃꯁꯤꯡ ꯆꯥꯗ 40 ꯍꯟꯊꯔꯦ ꯫
--------------------------------------------------

Translating:  74%|████████████████████       | 743/1000 [11:04<03:09,  1.36it/s]

[743/1000]
EN: Nepal earns 110 billion rupees from Indian tourists in fiscal year.
MT: ꯅꯦꯄꯥꯜꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯗꯒꯤ ꯁꯦꯟꯐꯝ ꯆꯍꯤꯗꯥ ꯂꯨꯄꯥ ꯕꯤꯂꯤꯌꯟ ꯐꯪ
--------------------------------------------------

Translating:  74%|████████████████████       | 744/1000 [11:05<03:07,  1.37it/s]

[744/1000]
EN: Turkey welcomes three lakh Indian tourists targeting five lakh by year-end.
MT: ꯇꯔꯀꯤꯅꯥ ꯆꯍꯤ ꯂꯣꯏꯔꯛꯄꯗꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯃꯉꯥꯒꯤ ꯄꯥꯟꯗꯝ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  74%|████████████████████       | 745/1000 [11:06<03:02,  1.40it/s]

[745/1000]
EN: Egypt reports 1.5 lakh Indian arrivals aiming for three lakh target.
MT: ꯏꯖꯞꯇꯅꯥ ꯚꯥꯔꯠꯇꯥ ꯂꯥꯛꯄꯥ ꯃꯤꯑꯣꯏ ꯂꯥꯈ ꯒꯤ ꯄꯥꯟꯗꯝ ꯊꯝꯃꯤ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝ
--------------------------------------------------

Translating:  75%|████████████████████▏      | 746/1000 [11:07<03:14,  1.31it/s]

[746/1000]
EN: Azerbaijan attracts two lakh Indian visitors visa-free policy credited.
MT: ꯑꯖꯔꯕꯥꯏꯖꯥꯟꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯚꯤꯖꯤꯇꯔ ꯂꯥꯈ ꯑꯅꯤꯒꯤ ꯚꯤꯖꯥ-ꯐ ꯄꯣꯂꯤꯁꯤ ꯀꯗꯤꯇ ꯂꯧ
--------------------------------------------------

Translating:  75%|████████████████████▏      | 747/1000 [11:07<03:15,  1.30it/s]

[747/1000]
EN: Georgia registers 1.75 lakh Indian tourist arrivals between January-September.
MT: ꯖꯣꯔꯖꯤꯌꯥꯅꯥ ꯖꯅꯨꯋꯥꯔꯤꯗꯒꯤ ꯁꯦꯞꯇꯦꯝꯕꯔ ꯐꯥꯎꯕꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯂꯥꯛꯄꯥ ꯔꯦꯖꯤꯁꯇꯔ ꯇꯧ
--------------------------------------------------

Translating:  75%|████████████████████▏      | 748/1000 [11:08<03:15,  1.29it/s]

[748/1000]
EN: Kenya targets one lakh Indian tourists with aggressive marketing campaign.
MT: ꯀꯦꯅꯦꯌꯥꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯑꯃ ꯃꯥꯡꯖꯧꯅꯅ ꯃꯥꯔꯀꯦꯇꯤꯡ ꯀꯦꯝꯄꯦꯅ ꯇꯧꯅꯕ ꯄꯥꯟꯗꯝ ꯊꯝ
--------------------------------------------------

Translating:  75%|████████████████████▏      | 749/1000 [11:09<03:16,  1.28it/s]

[749/1000]
EN: Udaipur airport gets new terminal building costing five hundred crore rupees.
MT: ꯎꯗꯦꯄꯨꯔ ꯑꯦꯌꯔꯄꯣꯔꯇꯥ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯆꯥꯝꯃ ꯃꯉꯥ ꯆꯪꯕꯥ ꯑꯅꯧꯕ ꯇꯔꯃꯤꯅꯦꯜ ꯕꯤꯜꯗꯤꯡ ꯐꯪ
--------------------------------------------------

Translating:  75%|████████████████████▎      | 750/1000 [11:10<03:20,  1.25it/s]

[750/1000]
EN: Rajkot airport renamed after former Prime Minister Morarji Desai.
MT: ꯔꯥꯖꯀꯣꯠ ꯑꯦꯌꯔꯄꯣꯔꯇ ꯑꯁꯤ ꯍꯥꯟꯅꯒꯤꯙꯥꯟ ꯃꯟꯇ ꯃꯣꯔꯥꯔꯖꯤ ꯗꯦꯁꯥꯏꯒꯤ ꯃꯃꯤꯡ ꯂꯧꯔꯒ ꯑꯃꯨꯛ ꯍꯟꯅ ꯃꯤꯡꯊꯣꯟ
--------------------------------------------------

Translating:  75%|████████████████████▎      | 751/1000 [11:11<03:29,  1.19it/s]

[751/1000]
EN: Noida International Airport to begin flight operations by April 2026.
MT: ꯏꯪꯁꯣꯛ ꯒꯤ ꯑꯦꯄꯜ ꯐꯥꯎꯕꯗ ꯅꯣꯏꯗꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯑꯦꯌꯔꯄꯣꯔꯇꯅꯥ ꯐꯥꯏꯇ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡ ꯍꯧꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  75%|████████████████████▎      | 752/1000 [11:12<03:23,  1.22it/s]

[752/1000]
EN: Chennai airport opens dedicated lounge for transiting international passengers.
MT: ꯆꯦꯟꯅꯥꯏ ꯑꯦꯌꯔꯄꯣꯔꯇꯅꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯄꯦꯁꯦꯟꯖꯔꯁꯤꯡꯒꯤꯗꯃꯛꯇ ꯗꯦꯗꯤꯀꯦꯇꯦꯗ ꯂꯥꯎꯟꯖ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  75%|████████████████████▎      | 753/1000 [11:12<03:25,  1.20it/s]

[753/1000]
EN: Guwahati-Rohingya railway project completes tunneling work in Mizoram.
MT: ꯒꯨꯋꯥꯍꯥꯇꯤ-ꯔꯣꯍꯤꯡꯌꯥ ꯔꯦꯜꯋꯦꯖꯦꯛꯇꯅꯥ ꯃꯤꯖꯣꯔꯥꯃꯗꯥ ꯇꯅꯦꯜꯒꯤ ꯊꯕꯛ ꯂꯣꯏꯁꯤꯟ
--------------------------------------------------

Translating:  75%|████████████████████▎      | 754/1000 [11:13<03:15,  1.26it/s]

[754/1000]
EN: Katra-Delhi Vande Bharat Express reduces travel time by three hours.
MT: ꯀꯇ-ꯗꯦꯂꯤ ꯚꯥꯟꯗꯦ ꯚꯥꯔꯠ ꯑꯦꯛꯁꯄꯦꯁꯅ ꯂꯝꯀꯣꯏꯕꯒꯤ ꯃꯇꯝ ꯄꯨꯡ ꯑꯍꯨꯝ ꯍꯟꯊꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  76%|████████████████████▍      | 755/1000 [11:14<03:20,  1.22it/s]

[755/1000]
EN: Mumbai-Ahmedabad bullet train project completes fifty percent of viaduct work.
MT: ꯃꯨꯝꯕꯥꯏ-ꯑꯍꯃꯦꯗꯥꯕꯥꯗ ꯕꯨꯂꯦꯇꯦꯟꯖꯦꯛꯇꯅꯥ ꯚꯤꯌꯥꯗꯛꯇꯀꯤ ꯊꯕꯛ ꯆꯥꯗ ꯂꯣꯏ
--------------------------------------------------

Translating:  76%|████████████████████▍      | 756/1000 [11:15<03:18,  1.23it/s]

[756/1000]
EN: Indian Railways introduces 200 superfast trains for summer rush.
MT: ꯚꯥꯔꯠꯀꯤ ꯔꯦꯜꯋꯦꯅꯥ ꯀꯥꯂꯦꯟꯊꯥꯒꯤ ꯃꯤ ꯌꯥꯝꯅ ꯆꯨꯡꯅꯅꯕꯒꯤꯗꯃꯛꯇ ꯁꯨꯄꯔꯐꯥꯁꯇꯦꯟ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  76%|████████████████████▍      | 757/1000 [11:16<03:18,  1.22it/s]

[757/1000]
EN: Kochi water metro adds four new routes connecting Vypin and Goshree islands.
MT: ꯀꯣꯆꯤ ꯋꯥꯇꯔ ꯃꯦꯇꯅꯥ ꯚꯥꯏꯄꯤꯅ ꯑꯃꯁꯨꯡ ꯒꯣꯁ ꯏꯊꯠꯁꯤꯡ ꯁꯝꯅꯕ ꯑꯅꯧꯕ ꯂꯝꯕꯤ ꯃꯔꯤ ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  76%|████████████████████▍      | 758/1000 [11:16<03:15,  1.24it/s]

[758/1000]
EN: Ayodhya's Ram Path revamp completed ahead of Pran Pratishtha anniversary.
MT: ꯑꯥꯌꯣꯙꯌꯥꯒꯤ ꯔꯥꯝ ꯄꯥꯊ ꯔꯤꯚꯦꯝꯄ ꯑꯁꯤꯥꯟꯇꯤꯁꯊꯥꯒꯤ ꯆꯍꯤꯒꯤ ꯃꯃꯥꯡꯗ ꯂꯣꯏꯁꯤꯟ
--------------------------------------------------

Translating:  76%|████████████████████▍      | 759/1000 [11:17<03:16,  1.22it/s]

[759/1000]
EN: Kedarnath ropeway project gets environmental clearance from ministry.
MT: ꯀꯦꯗꯥꯔꯅꯥꯊ ꯔꯣꯄꯋꯦꯖꯦꯛꯇꯅꯥ ꯃꯟꯇꯗꯒꯤ ꯑꯦꯟꯚꯥꯏꯔꯟꯃꯦꯟꯇꯦꯜ ꯀꯂꯤꯑꯔꯦꯟꯁ ꯐꯪ
--------------------------------------------------

Translating:  76%|████████████████████▌      | 760/1000 [11:18<03:08,  1.27it/s]

[760/1000]
EN: Hemkund Sahib helicopter service fares capped at five thousand rupees.
MT: ꯍꯦꯝꯀꯨꯟꯗ ꯁꯥꯍꯤꯕ ꯍꯦꯂꯤꯀꯣꯞꯇꯔ ꯁꯔꯕꯤꯁ ꯀꯤ ꯃꯃꯜ ꯑꯁꯤ ꯂꯨꯄꯥ ꯂꯤꯁꯤꯡ ꯃꯉꯥꯗꯥ ꯂꯦꯞ
--------------------------------------------------

Translating:  76%|████████████████████▌      | 761/1000 [11:19<03:03,  1.31it/s]

[761/1000]
EN: Statue of Unity adds laser show and sound and light attraction.
MT: ꯇꯨ ꯑꯣꯐ ꯌꯨꯅꯤꯇꯤꯅ ꯂꯦꯖꯔ ꯁꯣ ꯑꯃꯁꯨꯡ ꯁꯥꯎꯟꯗ ꯑꯃꯁꯨꯡ ꯂꯥꯏꯇ ꯑꯦꯇꯦꯁꯟ ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  76%|████████████████████▌      | 762/1000 [11:19<02:58,  1.33it/s]

[762/1000]
EN: Khajuraho airport receives international status for charter operations.
MT: ꯈꯥꯖꯨꯔꯥꯍꯣ ꯑꯦꯌꯔꯄꯣꯔꯇ ꯑꯁꯤ ꯆꯥꯔꯇꯔ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡꯒꯤꯗꯃꯛ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜꯇꯦꯁ ꯐꯪ
--------------------------------------------------

Translating:  76%|████████████████████▌      | 763/1000 [11:20<03:07,  1.26it/s]

[763/1000]
EN: Puducherry tourism department renovates French War Memorial promenade.
MT: ꯄꯨꯗꯨꯆꯦꯔꯤ ꯇꯨꯔꯤꯖꯝ ꯗꯤꯄꯥꯇꯃꯦꯟꯇꯅꯥ ꯐꯔꯦꯟꯁ ꯋꯥꯔ ꯃꯦꯃꯣꯔꯤꯌꯦꯜ ꯄꯃꯦꯅꯦꯗ ꯁꯦꯝꯖꯤꯟꯈ
--------------------------------------------------

Translating:  76%|████████████████████▋      | 764/1000 [11:21<03:01,  1.30it/s]

[764/1000]
EN: Dal Lake restoration project includes de-weeding and island development.
MT: ꯗꯥꯂ ꯂꯦꯛ ꯔꯤꯁꯇꯣꯔꯦꯁꯟꯖꯦꯛꯇꯗꯥ ꯎꯅꯥ ꯃꯨꯠꯊꯠꯄ ꯑꯃꯁꯨꯡ ꯏꯊꯠꯀꯤ ꯆꯥꯎꯈꯠꯄꯥ ꯌꯥꯎꯔꯤ ꯫
--------------------------------------------------

Translating:  76%|████████████████████▋      | 765/1000 [11:22<03:03,  1.28it/s]

[765/1000]
EN: Hampi gets world-class interpretation centre showcasing Vijayanagara heritage.
MT: ꯍꯝꯄꯤꯗꯥ ꯕꯤꯖꯌꯥꯅꯒꯔꯒꯤ ꯍꯦꯔꯤꯇꯦꯖ ꯎꯠꯄꯥ ꯋꯥꯔꯜꯗ-ꯀꯂꯥꯁ ꯏꯟꯇꯔꯄꯦꯇꯦꯁꯟ ꯁꯦꯟꯇꯔ ꯐꯪ
--------------------------------------------------

Translating:  77%|████████████████████▋      | 766/1000 [11:23<03:04,  1.27it/s]

[766/1000]
EN: Mahabalipuram shoreline monument gets LED lighting for night viewing.
MT: ꯃꯍꯥꯕꯥꯂꯤꯄꯨꯔꯝ ꯁꯣꯔꯂꯥꯏꯟ ꯃꯣꯅꯨꯃꯦꯟꯇꯗꯥ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯌꯦꯡꯅꯕꯒꯤꯗꯃꯛ ꯑꯦꯜ. ꯏ. ꯗꯤ. ꯂꯥꯏꯇꯤꯡ ꯐꯪ
--------------------------------------------------

Translating:  77%|████████████████████▋      | 767/1000 [11:23<03:00,  1.29it/s]

[767/1000]
EN: Ajanta-Ellora caves introduce audio guides in ten international languages.
MT: ꯑꯖꯥꯟꯇꯥ- ꯏꯜꯂꯣꯔꯥ ꯒꯨꯍꯥꯁꯤꯡꯅꯖꯥꯇꯤꯒꯤ ꯂꯣꯟ ꯇꯔꯥꯗꯥ ꯑꯣꯗꯤꯑꯣ ꯒꯥꯏꯗꯁꯤꯡ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  77%|████████████████████▋      | 768/1000 [11:24<02:48,  1.38it/s]

[768/1000]
EN: Kaziranga opens additional safari routes for tourists.
MT: ꯀꯥꯖꯤꯔꯪꯒꯥꯅꯥ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤꯗꯃꯛ ꯑꯍꯦꯟꯕ ꯁꯐꯥꯔꯤ ꯂꯝꯕꯤꯁꯤꯡ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  77%|████████████████████▊      | 769/1000 [11:25<02:54,  1.32it/s]

[769/1000]
EN: Radisson Blu opens two hundred key property in Amritsar near Golden Temple.
MT: ꯑꯝꯔꯤꯠꯁꯔꯗꯥ ꯒꯣꯜꯗꯦꯟ ꯇꯦꯝꯄꯜ ꯃꯅꯥꯛꯇ ꯔꯦꯗꯤꯁꯟꯂꯨꯅꯥ ꯃꯔꯨꯑꯣꯏꯕ ꯂꯝ ꯆꯥꯃ ꯑꯅꯤ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  77%|████████████████████▊      | 770/1000 [11:26<02:57,  1.29it/s]

[770/1000]
EN: IHCL launches Ginger brand hotel in Siliguri for Dooars travellers.
MT: ꯑꯥꯏ ꯑꯩꯆ ꯁꯤ ꯑꯦꯜꯅꯥ ꯗꯨꯌꯥꯔ ꯂꯝꯀꯣꯏꯕꯥꯁꯤꯡꯒꯤꯗꯃꯛ ꯁꯤꯂꯤꯒꯨꯔꯤꯗꯥ ꯖꯤꯟꯖꯔꯥꯟꯗ ꯍꯣꯇꯦꯜ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  77%|████████████████████▊      | 771/1000 [11:26<02:56,  1.30it/s]

[771/1000]
EN: Hyatt Regency debuts in Dehradun with mountain view rooms.
MT: ꯍꯥꯏꯌꯥꯇ ꯔꯤꯖꯦꯟꯁꯤ ꯑꯁꯤ ꯗꯦꯍꯔꯥꯗꯨꯟꯗꯥ ꯃꯥꯎꯟꯇꯦꯟ ꯚꯤꯎ ꯀꯥꯁꯤꯡꯒ ꯂꯣꯏꯅꯅ ꯑꯍꯥꯟꯕ ꯑꯣꯏꯔꯛ
--------------------------------------------------

Translating:  77%|████████████████████▊      | 772/1000 [11:27<02:59,  1.27it/s]

[772/1000]
EN: Taj Fort Aguada completes fifty years in Goa announces renovation.
MT: ꯇꯥꯖ ꯐꯣꯔꯇ ꯑꯒꯨꯋꯥꯗꯥꯅꯥ ꯒꯣꯋꯥꯒꯤ ꯆꯍꯤ ꯆꯥꯝꯈꯥꯏ ꯂꯣꯏꯔꯦ ꯑꯃꯁꯨꯡ ꯑꯃꯨꯛ ꯍꯟꯅ ꯁꯦꯝꯖꯤꯟꯈꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  77%|████████████████████▊      | 773/1000 [11:28<02:55,  1.29it/s]

[773/1000]
EN: Novotel Visakhapatnam opens with three sixty degree sea view rooms.
MT: ꯅꯣꯚꯣꯇꯦꯜ ꯚꯤꯁꯥꯀꯇꯥꯅꯝ ꯑꯁꯤ ꯗꯤꯒꯇꯤ ꯁꯤ ꯚꯤꯎ ꯀꯥ ꯑꯍꯨꯝꯒꯥ ꯂꯣꯏꯅꯅ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  77%|████████████████████▉      | 774/1000 [11:29<02:44,  1.37it/s]

[774/1000]
EN: Roseate House Delhi appoints Kunal Kumar as new general manager.
MT: ꯔꯣꯖꯦꯇ ꯍꯥꯎꯁ ꯗꯤꯜꯂꯤꯅꯥ ꯀꯨꯅꯜ ꯀꯨꯃꯥꯔꯕꯨ ꯑꯅꯧꯕ ꯖꯦꯅꯔꯦꯜ ꯃꯦꯅꯦꯖꯔ ꯑꯣꯏꯅ ꯍꯥꯞ
--------------------------------------------------

Translating:  78%|████████████████████▉      | 775/1000 [11:29<02:43,  1.38it/s]

[775/1000]
EN: ITC Hotels launches Mementoes brand with Jaipur property opening.
MT: ꯑꯥꯏ ꯇꯤ ꯁꯤ ꯍꯣꯇꯦꯜꯅꯥ ꯖꯦꯄꯨꯔꯄꯣꯔꯇꯤ ꯍꯥꯡꯗꯣꯛꯄꯒꯥ ꯂꯣꯏꯅꯅ ꯃꯦꯃꯦꯟꯇꯣꯁꯥꯟꯗ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  78%|████████████████████▉      | 776/1000 [11:30<02:45,  1.35it/s]

[776/1000]
EN: Marriott Kathmandu opens Indian restaurant specializing in Awadhi cuisine.
MT: ꯃꯦꯔꯤꯑꯣꯇ ꯀꯊꯃꯟꯗꯨꯅꯥ ꯑꯋꯥꯙꯤ ꯀꯤꯖꯟꯗꯥ ꯊꯣꯏꯗꯣꯛ ꯍꯦꯟꯗꯣꯛꯄ ꯏꯟꯗꯤꯌꯟ ꯔꯦꯁꯇꯣꯔꯦꯟꯇ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  78%|████████████████████▉      | 777/1000 [11:31<02:43,  1.36it/s]

[777/1000]
EN: Sarovar Hotels signs new property in Darjeeling with heritage status.
MT: ꯗꯥꯔꯖꯤꯂꯤꯡꯗꯥ ꯍꯦꯔꯤꯇꯦꯖꯇꯦꯁꯀ ꯂꯣꯏꯅꯅ ꯁꯥꯔꯣꯚꯔ ꯍꯣꯇꯦꯜꯁꯤꯡꯅ ꯑꯅꯧꯕꯄꯣꯔꯇꯤ ꯈꯨꯠꯌꯦꯛ ꯄꯤꯁꯤꯟ
--------------------------------------------------

Translating:  78%|█████████████████████      | 778/1000 [11:31<02:36,  1.42it/s]

[778/1000]
EN: The Park Kolkata celebrates seventy-fifth anniversary with heritage walks.
MT: ꯄꯥꯔꯛ ꯀꯣꯜꯀꯥꯇꯥꯅꯥ ꯍꯦꯔꯤꯇꯦꯖ ꯋꯥꯀꯒ ꯂꯣꯏꯅꯅꯥ ꯆꯍꯤ ꯆꯥ 75 ꯁꯨꯕꯥ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  78%|█████████████████████      | 779/1000 [11:32<02:43,  1.35it/s]

[779/1000]
EN: Ambassador Ajmera joins Indian Hotel Company board as independent director.
MT: ꯑꯦꯝꯕꯦꯁꯦꯗꯔ ꯑꯖꯃꯦꯔꯥꯅꯥ ꯏꯟꯗꯤꯌꯟ ꯍꯣꯇꯦꯜ ꯀꯝꯄꯅꯤꯒꯤ ꯕꯣꯔꯗꯥ ꯏꯟꯗꯄꯦꯟꯗꯦꯟꯇ ꯗꯥꯏꯔꯦꯛꯇꯔ ꯑꯣꯏꯅ ꯌꯥꯎ
--------------------------------------------------

Translating:  78%|█████████████████████      | 780/1000 [11:33<02:47,  1.31it/s]

[780/1000]
EN: Chai Sutta Bar founder Anubhav Dubey opens tourist cafe in Udaipur.
MT: ꯆꯥꯏ ꯁꯨꯠꯇꯥ ꯕꯥꯔ ꯂꯤꯡꯈꯠꯄꯥ ꯃꯤꯑꯣꯏ ꯑꯅꯨꯚꯕ ꯗꯨꯕꯦꯅꯥ ꯎꯗꯦꯄꯨꯔꯗꯥ ꯇꯨꯔꯤꯁꯇ ꯀꯦꯐꯦ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  78%|█████████████████████      | 781/1000 [11:34<02:37,  1.39it/s]

[781/1000]
EN: Aman Resorts to launch first Indian property in Alwar district.
MT: ꯑꯃꯟ ꯔꯤꯖꯣꯔꯇꯁꯅ ꯑꯥꯂꯋꯥꯔ ꯖꯤꯂꯥꯗꯥ ꯑꯍꯥꯟꯕ ꯚꯥꯔꯠꯀꯤꯄꯣꯔꯇꯤ ꯍꯥꯡꯗꯣꯛꯀꯅꯤ
--------------------------------------------------

Translating:  78%|█████████████████████      | 782/1000 [11:35<02:43,  1.33it/s]

[782/1000]
EN: Soneva Fushi Maldives introduces all-inclusive plan for Indian honeymooners.
MT: ꯁꯣꯅꯦꯚꯥ ꯐꯨꯁꯤ ꯃꯥꯜꯗꯤꯚꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯍꯅꯤꯃꯨꯅꯔꯁꯤꯡꯒꯤꯗꯃꯛ ꯑꯣꯜ-ꯏꯟꯀꯨꯁꯤꯕꯂꯥꯟ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 783/1000 [11:35<02:50,  1.27it/s]

[783/1000]
EN: CII tourism committee chairman K.B. Kachru calls for single window clearance.
MT: ꯁꯤ ꯑꯥꯏ ꯑꯥꯏ ꯇꯨꯔꯤꯖꯝ ꯀꯝꯃꯤꯇꯤꯒꯤ ꯆꯦꯌꯔꯃꯦꯟ ꯀꯦ ꯕꯤ ꯀꯥꯆꯔꯨꯅꯥ ꯁꯤꯡꯒꯜ ꯋꯤꯟꯗꯣ ꯀꯂꯥꯌꯔꯦꯟꯁ ꯄꯤꯅꯕ ꯍꯥꯏ
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 784/1000 [11:36<02:51,  1.26it/s]

[784/1000]
EN: Ladakh bans motorbike rallies to protect fragile Himalayan ecosystem.
MT: ꯂꯗꯥꯈꯅꯥ ꯑꯁꯣꯏꯕꯥ ꯍꯤꯃꯥꯂꯌꯟꯒꯤ ꯑꯦꯀꯣꯁꯃꯤꯇ ꯉꯥꯛꯁꯦꯟꯕꯒꯤꯗꯃꯛ ꯃꯣꯇꯣꯔꯕꯥꯏꯀ ꯔꯦꯂꯤꯁꯤꯡ ꯊꯤꯡ
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 785/1000 [11:37<02:49,  1.27it/s]

[785/1000]
EN: Meghalaya introduces living root bridge trekking festival in November.
MT: ꯃꯦꯘꯂꯌꯅꯥ ꯅꯕꯦꯝꯕꯔꯗꯥ ꯂꯤꯚꯤꯡ ꯔꯨꯠ ꯕꯖꯦꯛꯀꯤꯡ ꯐꯦꯁꯇꯤꯕꯦꯜ ꯍꯧꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  79%|█████████████████████▏     | 786/1000 [11:38<02:45,  1.29it/s]

[786/1000]
EN: Spiti valley opens for tourists after six-month winter closure.
MT: ꯊꯥ ꯇꯔꯨꯛꯀꯤ ꯅꯤꯡꯊꯝꯊꯥꯒꯤ ꯃꯇꯝꯗ ꯊꯤꯡꯖꯤꯟꯈꯕꯥ ꯃꯇꯨꯡꯗ ꯁꯄꯤꯇꯤ ꯋꯥꯂꯤ ꯑꯁꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤꯗꯃꯛ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  79%|█████████████████████▏     | 787/1000 [11:38<02:38,  1.34it/s]

[787/1000]
EN: Andaman administration permits night camping on Neil Island.
MT: ꯅꯤꯂ ꯑꯥꯏꯂꯦꯟꯗꯗꯥ ꯑꯟꯗꯃꯥꯟ ꯑꯦꯗꯃꯤꯅꯤꯁꯇꯦꯁꯟꯅ ꯅꯥꯏꯇ ꯀꯦꯝꯄꯤꯡ ꯇꯧꯅꯕꯒꯤ ꯑꯌꯥꯕ ꯄꯤ
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 788/1000 [11:39<02:42,  1.30it/s]

[788/1000]
EN: Gujarat forest department opens Gir interpretation zone for lion safaris.
MT: ꯒꯨꯖꯔꯥꯇ ꯐꯣꯔꯦꯁꯇ ꯗꯤꯄꯥꯇꯃꯦꯟꯇꯅꯥ ꯂꯥꯏꯅ ꯁꯐꯔꯤꯁꯤꯡꯒꯤ ꯒꯤꯔ ꯏꯟꯇꯔꯄꯦꯇꯦꯁꯟ ꯖꯣꯟ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 789/1000 [11:40<02:39,  1.32it/s]

[789/1000]
EN: Jim Corbett tiger reserve reports 1.75 lakh tourists in peak season.
MT: ꯖꯤꯃ ꯀꯣꯔꯕꯦꯇ ꯇꯥꯏꯒꯔ ꯔꯤꯖꯔꯚꯅꯥ ꯄꯥꯎꯗꯝꯂꯤ ꯃꯗꯨꯗꯤ ꯄꯤꯛ ꯁꯤꯖꯟꯗꯥ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 790/1000 [11:41<02:31,  1.39it/s]

[790/1000]
EN: Periyar sanctuary introduces bamboo rafting in Thekkady lake.
MT: ꯄꯦꯔꯤꯌꯥꯔ ꯁꯦꯡꯆꯨꯑꯔꯤꯅꯥ ꯊꯦꯛꯀꯥꯗꯤ ꯄꯥꯠꯗꯥ ꯋꯥꯒꯤ ꯔꯥꯐꯇꯤꯡ ꯍꯧꯍꯟ
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 791/1000 [11:41<02:16,  1.53it/s]

[791/1000]
EN: Sundarbans tourism restricted during tiger breeding season.
MT: ꯀꯩ ꯄꯣꯛꯄꯥ ꯃꯇꯝꯗ ꯁꯨꯟꯗꯔꯕꯥꯟ ꯇꯨꯔꯤꯖꯝ ꯊꯤꯡꯉꯤ ꯫
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 792/1000 [11:42<02:17,  1.51it/s]

[792/1000]
EN: Ranthambore bans private vehicles inside core zone from December.
MT: ꯔꯟꯊꯝꯕꯣꯔꯅꯥ ꯗꯤꯁꯦꯝꯕꯔꯗꯒꯤ ꯀꯣꯔ ꯖꯣꯟꯒꯤ ꯃꯅꯨꯡꯗꯚꯥꯏꯇ ꯒꯥꯔꯤꯁꯤꯡ ꯊꯤꯡꯖꯜꯂꯨ ꯫
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 793/1000 [11:42<02:17,  1.51it/s]

[793/1000]
EN: Kerala tourism launches monsoon packages for Ayurveda treatments.
MT: ꯀꯦꯔꯂꯥ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯑꯥꯌꯨꯔꯕꯦꯗ ꯂꯥꯏꯌꯦꯡꯒꯤꯗꯃꯛ ꯃꯣꯟꯁꯨꯅ ꯄꯦꯀꯦꯖꯁꯤꯡ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 794/1000 [11:43<02:18,  1.49it/s]

[794/1000]
EN: Kutch Rann Utsav extends tent city duration by forty-five days.
MT: ꯀꯨꯇꯆ ꯔꯟ ꯎꯇꯁꯥꯚꯅꯥ ꯇꯦꯟꯇ ꯁꯤꯇꯤꯒꯤ ꯃꯇꯝ ꯑꯁꯤ ꯅꯨꯃꯤꯠ ꯃꯔꯤ - ꯃꯉꯥꯅꯤ ꯍꯦꯟꯒꯠ
--------------------------------------------------

Translating:  80%|█████████████████████▍     | 795/1000 [11:44<02:31,  1.35it/s]

[795/1000]
EN: Telangana government promotes Yadadri temple as integrated pilgrimage hub.
MT: ꯇꯦꯂꯪꯒꯥꯅꯥ ꯒꯚꯔꯃꯦꯟꯇꯅꯥ ꯌꯥꯗꯔꯤ ꯂꯥꯏꯁꯪ ꯑꯁꯤ ꯏꯟꯇꯤꯒꯇꯦꯗ ꯄꯤꯔꯊꯂꯤꯖꯝ ꯍꯕꯥꯇ ꯑꯣꯏꯍꯟ
--------------------------------------------------

Translating:  80%|█████████████████████▍     | 796/1000 [11:45<02:30,  1.36it/s]

[796/1000]
EN: Mysore Dasara procession draws eight lakh visitors on Vijayadashami day.
MT: ꯃꯥꯏꯁꯣꯔ ꯗꯁꯥꯔꯥꯒꯤ ꯈꯣꯡꯆꯠꯅꯥ ꯚꯤꯖꯦꯗꯁꯥꯃꯤꯒꯤ ꯅꯨꯃꯤꯠꯗꯥ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯅꯤꯄꯥꯟ ꯄꯨ
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 797/1000 [11:46<02:28,  1.37it/s]

[797/1000]
EN: Konark Sun Temple to get 3D projection mapping experience.
MT: ꯀꯣꯅꯥꯔꯛ ꯁꯨꯅ ꯇꯦꯝꯄꯜꯅꯥ 3Dꯖꯦꯛꯁꯟ ꯃꯦꯄꯤꯡ ꯑꯦꯛꯁꯄꯤꯌꯔꯦꯟꯁ ꯐꯪꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 798/1000 [11:46<02:26,  1.38it/s]

[798/1000]
EN: Elephanta Caves introduce Portuguese audio guide for visitors.
MT: ꯑꯦꯂꯤꯐꯦꯟꯇꯥ ꯀꯦꯚꯁꯅꯥ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤꯗꯃꯛꯇ ꯄꯨꯔꯇꯨꯒꯤꯖꯒꯤ ꯑꯣꯗꯤꯑꯣ ꯒꯥꯏꯗ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 799/1000 [11:47<02:25,  1.38it/s]

[799/1000]
EN: Golconda Fort light and sound show revamped in Telugu and English.
MT: ꯇꯦꯂꯨꯒꯨ ꯑꯃꯁꯨꯡ ꯏꯪꯂꯤꯁꯇꯥ ꯒꯣꯂꯀꯣꯟꯗꯥ ꯐꯣꯔꯇ ꯂꯥꯏꯇ ꯑꯦꯟ ꯁꯥꯎꯟꯗ ꯁꯣ ꯁꯦꯝꯖꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 800/1000 [11:48<02:24,  1.39it/s]

[800/1000]
EN: Five regional medical hubs to be set up to boost medical tourism in country
MT: ꯂꯩꯕꯥꯛ ꯑꯁꯤꯗ ꯃꯦꯗꯤꯀꯦꯜ ꯇꯨꯔꯤꯖꯝ ꯍꯦꯟꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯔꯤꯖꯅꯦꯜ ꯃꯦꯗꯗꯤꯀꯦꯜ ꯍꯕ ꯃꯉꯥ ꯁꯦꯝꯒꯅꯤ
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 801/1000 [11:48<02:15,  1.47it/s]

[801/1000]
EN: Union Budget 2026 announces NIMHANS for north India
MT: ꯌꯨꯅꯤꯌꯟ ꯕꯖꯦꯇ 2026ꯅꯥ ꯑꯋꯥꯡ ꯚꯥꯔꯠꯀꯤ ꯅꯤꯝꯍꯥꯟꯁ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 802/1000 [11:49<02:18,  1.43it/s]

[802/1000]
EN: Centre forms expert panel on healthcare for transgender persons
MT: ꯁꯦꯟꯇꯔꯅꯥ ꯑꯦꯛꯁꯄꯥꯔꯇ ꯄꯦꯅꯦꯜ ꯑꯣꯟ ꯍꯦꯜꯊꯦꯀꯦꯌꯔ ꯐꯣꯔꯖꯦꯟꯗꯔ ꯄꯔꯁꯟꯁꯤꯡ ꯁꯦꯝꯂꯦ
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 803/1000 [11:50<02:19,  1.41it/s]

[803/1000]
EN: Stem cell therapy cannot be offered as a clinical service for autism
MT: ꯃꯦ ꯁꯦꯜ ꯊꯦꯔꯥꯄꯤ ꯑꯁꯤ ꯑꯣꯇꯤꯖꯝꯒꯤꯗꯃꯛ ꯀꯂꯤꯅꯤꯀꯦꯜ ꯁꯔꯕꯤꯁ ꯑꯃ ꯑꯣꯏꯅ ꯄꯤꯕ ꯌꯥꯔꯣꯏ ꯫
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 804/1000 [11:50<02:18,  1.42it/s]

[804/1000]
EN: AI helps doctors spot breast cancer in scans
MT: ꯑꯦꯑꯏꯅꯥ ꯗꯣꯛꯇꯔꯁꯤꯡꯕꯨ ꯁꯀꯦꯟꯗꯥ ꯕꯦꯁꯇ ꯀꯦꯟꯁꯔ ꯈꯪꯗꯣꯛꯄꯗꯥ ꯃꯇꯦꯡ ꯄꯥꯡꯉꯤ ꯫
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 805/1000 [11:51<02:32,  1.28it/s]

[805/1000]
EN: Every family today knows someone with cancer and It is no longer a disease that happens to an ageing parent or relative
MT: ꯉꯁꯤꯗꯤ ꯏꯃꯨꯡ ꯈꯨꯗꯤꯡꯃꯛꯅ ꯀꯦꯟꯁꯔ ꯅꯥꯔꯕ ꯃꯤꯑꯣꯏ ꯑꯃ ꯈꯪꯂꯦ ꯑꯃꯁꯨꯡ ꯃꯁꯤ ꯆꯍꯤ ꯆꯥꯎꯔꯕ ꯃꯃꯥ-ꯃꯕꯥ ꯅꯠꯇꯒꯥ ꯃꯔꯤ ꯂꯩꯅꯕ ꯑꯃꯗ ꯊꯣꯛꯄꯥ ꯂꯥꯏꯅꯥ ꯑꯃ ꯑꯣꯏꯔꯛꯇ
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 806/1000 [11:52<02:18,  1.40it/s]

[806/1000]
EN: Government imposes import curbs on three pharma ingredients for one year
MT: ꯁꯔꯀꯥꯔꯅꯥ ꯐꯥꯔꯃꯥꯒꯤ ꯃꯆꯥꯛ ꯑꯍꯨꯝ ꯄꯨꯁꯤꯜꯂꯛꯄꯗꯥ ꯆꯍꯤ ꯑꯃꯒꯤꯗꯃꯛ ꯊꯤꯡꯖꯜꯍꯟ
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 807/1000 [11:53<02:18,  1.40it/s]

[807/1000]
EN: Menstrual health in schools is integral to right to life, says the Supreme Court
MT: ꯜꯁꯤꯡꯗ ꯊꯥꯒꯤ ꯑꯣꯏꯕ ꯍꯛꯁꯦꯜ ꯑꯁꯤ ꯍꯤꯡꯕꯒꯤ ꯍꯛꯗꯥ ꯃꯄꯨꯡ ꯐꯥꯕ ꯍꯥꯏꯅ ꯁꯨꯄꯝ ꯀꯣꯔꯠꯅ ꯍꯥꯏ
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 808/1000 [11:53<02:22,  1.35it/s]

[808/1000]
EN: WHO sees low risk of Nipah virus spreading beyond India
MT: ꯗꯕꯂꯌꯨꯑꯍꯑꯣꯅꯥ ꯅꯤꯄꯥꯍ ꯚꯥꯏꯔꯁ ꯑꯁꯤ ꯚꯥꯔꯠꯀꯤ ꯃꯄꯥꯟꯗ ꯁꯟꯗꯣꯛꯄꯒꯤ ꯔꯤꯁꯀ ꯍꯟꯊꯔꯦ ꯍꯥꯏꯅ ꯎꯔꯦ
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 809/1000 [11:54<02:34,  1.24it/s]

[809/1000]
EN: Economic Survey calls for tackling rising digital addiction and screen-related mental health problems
MT: ꯏꯀꯅꯣꯃꯤꯛ ꯁꯔꯚꯦꯅꯥ ꯍꯦꯟꯒꯠꯂꯛꯂꯤꯕ ꯗꯤꯖꯤꯇꯦꯜ ꯑꯦꯗꯤꯛꯁꯟ ꯑꯃꯁꯨꯡꯅꯤꯜꯒꯥ ꯃꯔꯤ ꯂꯩꯅꯕ ꯃꯦꯟꯇꯦꯜ ꯍꯦꯜꯊꯃꯣꯜꯁꯤꯡ ꯊꯦꯡꯅꯅꯕ ꯍꯥꯏꯔꯤ
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 810/1000 [11:55<02:25,  1.31it/s]

[810/1000]
EN: 188 million children and adolescents living with obesity worldwide
MT: ꯃꯥꯂꯦꯝ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯑꯣꯕꯣꯁꯤꯇꯤꯒ ꯂꯣꯏꯅꯅꯥ ꯍꯤꯡꯂꯤꯕ ꯑꯉꯥꯡ ꯑꯃꯁꯨꯡ ꯑꯦꯂꯣꯖꯦꯟꯇ ꯀꯔꯣꯔ
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 811/1000 [11:56<02:20,  1.34it/s]

[811/1000]
EN: 60% of mental disorders found in patients below 35 years
MT: ꯃꯦꯟꯇꯥꯜ ꯗꯤꯁꯑꯣꯔꯗꯔꯁꯤꯡꯒꯤ%ꯗꯤ ꯆꯍꯤ 35ꯒꯤ ꯃꯈꯥꯗ ꯂꯩꯕ ꯑꯅꯥꯕꯥꯁꯤꯡꯗ ꯐꯪꯉꯤ ꯫
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 812/1000 [11:57<02:28,  1.26it/s]

[812/1000]
EN: Obesity impacts on brain may depend on how fat is distributed across body
MT: ꯕꯦꯟꯗ ꯑꯣꯕꯦꯁꯤꯇꯤꯒꯤ ꯏꯄꯦꯛꯠꯁꯤꯡ ꯑꯁꯤ ꯍꯛꯆꯥꯡ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯐꯦꯠ ꯑꯁꯤ ꯀꯔꯝꯅꯥ ꯁꯟꯗꯣꯛꯀꯗꯒꯦ ꯍꯥꯏꯕꯒꯤ ꯃꯈꯥ ꯄꯣꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 813/1000 [11:58<02:32,  1.22it/s]

[813/1000]
EN: Maharashtra, Karnataka, Tamil Nadu have highest number of vacancies under the NEET-PG 2025-26
MT: ꯃꯍꯥꯔꯥꯁꯇ ꯭ ꯔ, ꯀꯔꯅꯥꯇꯀꯥ, ꯇꯥꯃꯤꯜ ꯅꯥꯗꯨꯗ ꯅꯤꯑꯏꯇꯤ-ꯄꯤꯖꯤ 2025-26 ꯒꯤ ꯃꯈꯥꯗ ꯑꯍꯦꯟꯕꯥ ꯚꯦꯛꯁꯤꯅꯦꯁꯟꯁꯤꯡ ꯂꯩ ꯫
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 814/1000 [11:58<02:39,  1.17it/s]

[814/1000]
EN: Only two Nipah virus disease cases reported in West Bengal since December 2025, says Health Ministry
MT: ꯏꯪꯁꯣꯛ 2025 ꯒꯤ ꯗꯤꯁꯦꯝꯕꯔꯗꯒꯤ ꯋꯇ ꯕꯦꯡꯒꯣꯜꯗꯥ ꯅꯤꯄꯥꯍ ꯚꯥꯏꯔꯁ ꯂꯥꯏꯅꯥꯒꯤ ꯀꯦꯁ ꯑꯅꯤ ꯈꯛꯇꯃꯛ ꯔꯤꯄꯣꯔꯠ ꯇꯧꯔꯦ ꯍꯥꯏꯅ ꯍꯦꯜꯊ ꯃꯟꯇꯅꯥ ꯍꯥꯏ ꯫
--------------------------------------------------

Translating:  82%|██████████████████████     | 815/1000 [11:59<02:38,  1.17it/s]

[815/1000]
EN: Health impacts due to plastics worldwide may double by 2040
MT: ꯃꯥꯂꯦꯝ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥꯁꯇꯤꯛꯁꯤꯡ ꯑꯁꯤꯅ ꯊꯣꯛꯍꯟꯕ ꯍꯛꯁꯦꯜꯒꯤ ꯏꯚꯦꯛꯠꯁꯤꯡ ꯑꯁꯤ ꯏꯪ 2040 ꯐꯥꯎꯕꯗ ꯁꯔꯨꯛ ꯑꯅꯤ ꯍꯦꯟꯒꯠꯂꯛꯄ ꯌꯥꯏ ꯫
--------------------------------------------------

Translating:  82%|██████████████████████     | 816/1000 [12:00<02:25,  1.27it/s]

[816/1000]
EN: China halts sale of Sun Pharma drug used to treat dementia
MT: ꯆꯥꯏꯅꯥꯅꯥ ꯗꯤꯃꯦꯅꯁꯤꯌꯥ ꯂꯥꯏꯌꯦꯡꯕꯗ ꯁꯤꯖꯤꯟꯅꯕ ꯁꯟ ꯐꯥꯔꯃꯥꯒꯤ ꯍꯤꯗꯥꯛ ꯌꯣꯟꯕ ꯊꯤꯡ
--------------------------------------------------

Translating:  82%|██████████████████████     | 817/1000 [12:01<02:38,  1.15it/s]

[817/1000]
EN: T.N. govt. scheme improves access to diabetes, hypertension care for women as rural residents
MT: ꯇꯤ. ꯑꯦꯟ. ꯒꯚꯔꯃꯦꯟꯇꯀꯤꯝꯅꯥ ꯗꯥꯏꯑꯦꯕꯦꯇꯤꯁ, ꯍꯥꯏꯞꯇꯔꯦꯟꯁꯟ ꯀꯦꯌꯔ ꯐꯣꯔ ꯋꯤꯃꯦꯅꯕꯨ ꯔꯨꯔꯦꯜ ꯔꯦꯁꯤꯗꯦꯟꯇꯁꯤꯡ ꯑꯣꯏꯍꯟꯕꯗꯥ ꯐꯒꯠꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  82%|██████████████████████     | 818/1000 [12:03<03:15,  1.07s/it]

[818/1000]
EN: Karnataka farmers urge Union Government to recommend to WHO to re-classify arecanut from ‘carcinogenic’ to ‘possibly carcinogenic to humans’
MT: ꯀꯔꯅꯥꯇꯀꯥꯒꯤ ꯂꯧꯃꯤꯁꯤꯡꯅ ꯀꯦꯟꯗ ꯒꯕꯔꯃꯦꯟꯇꯇꯥ ꯑꯦꯔꯦꯀꯅꯨꯠꯄꯨ ꯀꯥꯔꯁꯤꯅꯣꯖꯦꯅꯤꯛꯗꯒꯤ ′′ꯑꯃꯗꯥ ꯀꯥꯔꯁꯤꯅꯣꯁꯖꯦꯟꯦꯅꯤꯛ ꯑꯣꯏꯍꯟꯕꯥ ꯔꯤ-ꯀꯁꯤꯐꯥꯏ ꯇꯧꯅꯕ ꯗꯕꯂꯌꯨꯑꯍꯣꯗꯥ ꯔꯤꯀꯃꯦꯟꯗ ꯇꯧꯅꯅꯕ ꯍꯥꯏꯔꯤ ꯫
--------------------------------------------------

Translating:  82%|██████████████████████     | 819/1000 [12:04<03:17,  1.09s/it]

[819/1000]
EN: Study discovers stress-reducing role of natural molecule in body, may help with metabolic disorders
MT: ꯍꯛꯆꯥꯡꯗꯥ ꯅꯦꯆꯔꯦꯜ ꯃꯂꯦꯀꯜꯒꯤ ꯁꯦꯁ-ꯔꯤꯗꯨꯀꯤꯡ ꯔꯣꯜ ꯑꯗꯨ ꯊꯤꯖꯤꯜꯂꯤ, ꯃꯦꯇꯥꯕꯂꯤꯛ ꯗꯤꯁꯑꯣꯔꯗꯔꯁꯤꯡꯗ ꯃꯇꯦꯡ ꯄꯥꯡꯕ ꯌꯥꯏ ꯫
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 820/1000 [12:04<02:50,  1.06it/s]

[820/1000]
EN: Keeping your spine healthy with small, everyday changes
MT: ꯑꯄꯤꯛꯄ, ꯅꯨꯃꯤꯠ ꯈꯨꯗꯤꯡꯒꯤ ꯍꯣꯡꯂꯛꯄꯁꯤꯡꯒ ꯂꯣꯏꯅꯅ ꯅꯍꯥꯛꯀꯤ ꯁꯄꯤꯟ ꯑꯗꯨ ꯍꯛꯊꯦꯡꯅꯅ ꯊꯝꯕꯥ
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 821/1000 [12:05<02:32,  1.17it/s]

[821/1000]
EN: What is behind the increasing number of heart attacks in pregnancy?
MT: ꯃꯤꯔꯣꯜꯂꯤꯉꯩ ꯃꯇꯝꯗ ꯍꯥꯔꯇ ꯑꯦꯇꯦꯛ ꯃꯁꯤꯡ ꯍꯦꯟꯒꯠꯂꯛꯄꯒꯤ ꯃꯔꯝ ꯀꯔꯤꯅꯣ?
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 822/1000 [12:06<02:15,  1.31it/s]

[822/1000]
EN: Can India eliminate malaria by 2030?
MT: ꯏꯪꯁꯣꯛ 2030 ꯐꯥꯎꯕꯗ ꯚꯥꯔꯠꯅ ꯃꯦꯂꯦꯔꯤꯌꯥ ꯃꯨꯠꯊꯠꯄ ꯌꯥꯒꯗꯔꯥ?
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 823/1000 [12:06<02:26,  1.21it/s]

[823/1000]
EN: Tamil Nadu government seeks IIT-M’s assistance to study ill effects of microplastics on human health
MT: ꯇꯥꯃꯤꯜ ꯅꯥꯗꯨ ꯁꯔꯀꯥꯔꯅꯥ ꯃꯤꯌꯣꯏꯒꯤ ꯍꯛꯁꯦꯜꯗꯥ ꯃꯥꯏꯀꯄꯂꯥꯁꯇꯤꯛꯁꯤꯡꯒꯤ ꯑꯁꯣꯏꯕꯥ ꯃꯍꯩꯁꯤꯡ ꯅꯩꯅꯕꯗꯥ ꯑꯥꯏ ꯑꯥꯏ ꯇꯤ-ꯑꯦꯝ ꯒꯤ ꯃꯇꯦꯡ ꯊꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 824/1000 [12:07<02:17,  1.28it/s]

[824/1000]
EN: Goa seeks to grow as a wellness and medical tourism hub in India
MT: ꯒꯣꯋꯥꯅꯥ ꯚꯥꯔꯠꯇꯥ ꯋꯥꯏꯜꯅꯦꯁ ꯑꯃꯁꯨꯡ ꯃꯦꯗꯤꯀꯦꯜ ꯇꯨꯔꯤꯖꯝꯒꯤ ꯃꯐꯝ ꯑꯃ ꯑꯣꯏꯅ ꯆꯥꯎꯈꯠꯄꯥ ꯄꯥꯝꯃꯤ
--------------------------------------------------

Translating:  82%|██████████████████████▎    | 825/1000 [12:08<02:36,  1.12it/s]

[825/1000]
EN: Borewell found contaminated, pipelines being probed as eight remain in hospital in Madhya Pradesh's Mhow
MT: ꯕꯣꯔꯦꯋꯦꯜ ꯑꯁꯤ ꯄꯠꯊꯔꯛꯄꯥ ꯐꯡꯈꯤ, ꯃꯙꯒꯤ ꯃꯍꯥꯎꯒꯤ ꯍꯣꯁꯄꯤꯇꯥꯂꯗꯥ ꯅꯤꯄꯥꯜ ꯂꯩꯔꯗꯨꯅ ꯂꯩꯕꯗꯒꯤ ꯄꯥꯏꯄꯂꯥꯏꯟꯁꯤꯡ ꯊꯤꯖꯤꯟꯕꯒꯤ ꯊꯕꯛ ꯆꯠꯊꯔꯤ ꯫
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 826/1000 [12:09<02:32,  1.14it/s]

[826/1000]
EN: Uttar Pradesh youth amputates foot to seek disability quota in admission to medical college
MT: ꯎꯠꯇꯔꯒꯤ ꯌꯨꯋꯟꯅꯥ ꯃꯦꯗꯤꯀꯦꯜ ꯀꯣꯂꯦꯖ ꯑꯦꯃꯁꯇꯦꯁꯟꯗꯥ ꯗꯤꯖꯤꯕꯂꯤꯇꯤ ꯀꯣꯇꯥ ꯂꯧꯅꯕꯒꯤꯗꯃꯛ ꯈꯣꯡ ꯀꯛꯊꯠꯂꯤ
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 827/1000 [12:10<02:41,  1.07it/s]

[827/1000]
EN: Police investigate software engineer’s death in Chennai lodge linked to bug repellent fumes
MT: ꯄꯨꯂꯤꯁꯅꯥ ꯆꯦꯟꯅꯥꯏ ꯂꯣꯖꯗꯥ ꯁꯣꯐꯇꯋꯦꯌꯔ ꯏꯟꯖꯤꯅꯤꯌꯔꯒꯤ ꯁꯤꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯊꯤꯖꯤꯜꯂꯤ ꯃꯁꯤ ꯕꯒ ꯔꯤꯄꯦꯂꯦꯟꯇ ꯃꯩꯁꯥꯒꯥ ꯃꯔꯤ ꯂꯩꯅꯩ ꯫
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 828/1000 [12:11<02:24,  1.19it/s]

[828/1000]
EN: Regularly engaging in varied physical activities could extend lifespan
MT: ꯆꯥꯡ ꯅꯥꯏꯅ ꯃꯈꯜ ꯀꯌꯥꯒꯤ ꯐꯤꯖꯤꯀꯦꯜ ꯑꯦꯛꯇꯤꯚꯤꯇꯤꯁꯤꯡꯗ ꯁꯔꯨꯛ ꯌꯥꯕꯅ ꯍꯤꯡꯕꯒꯤ ꯃꯇꯝ ꯍꯦꯟꯒꯠꯍꯟꯕ ꯉꯝꯃꯤ ꯫
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 829/1000 [12:12<02:29,  1.14it/s]

[829/1000]
EN: Study relates ADHD traits in childhood with physical health problems in mid-life
MT: ꯁꯗꯤꯅꯥ ꯑꯉꯥꯡ ꯑꯣꯏꯔꯤꯉꯩ ꯑꯦꯗꯤꯑꯍꯗꯤꯥꯏꯇꯁꯤꯡ ꯑꯁꯤ ꯃꯤꯗ-ꯂꯥꯏꯐꯗꯥ ꯐꯤꯖꯤꯀꯦꯜ ꯍꯦꯜꯊꯄꯂꯝꯁꯤꯡꯒ ꯃꯔꯤ ꯂꯩꯅꯩ ꯫
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 830/1000 [12:12<02:17,  1.24it/s]

[830/1000]
EN: U.S. completes withdrawal from World Health Organization
MT: ꯌꯨ. ꯑꯦꯁ.ꯅꯥ ꯋꯥꯔꯂ ꯭ ꯗ ꯍꯦꯜꯊ ꯑꯣꯔꯒꯅꯥꯏꯖꯦꯁꯟꯗꯒꯤ ꯂꯧꯊꯣꯛꯄ ꯂꯣꯏꯔꯦ
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 831/1000 [12:13<02:15,  1.25it/s]

[831/1000]
EN: Punjab health scheme offers free hospital care worth ₹10 lakh to every family
MT: ꯄꯟꯖꯥꯕ ꯍꯦꯜꯊꯀꯤꯝꯅꯥ ꯏꯃꯨꯡ ꯈꯨꯗꯤꯡꯗꯥ ꯂꯨꯄꯥ ꯂꯥꯈ 10ꯒꯤ ꯍꯣꯁꯄꯤꯇꯥꯜ ꯀꯦꯌꯔ ꯐ
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 832/1000 [12:14<02:11,  1.27it/s]

[832/1000]
EN: Snapchat launches new Family Center safety tools for teens and parents
MT: ꯁꯅꯞꯆꯦꯇꯅꯥ ꯇꯦꯟꯗꯦꯁ ꯑꯃꯁꯨꯡ ꯃꯃꯥ - ꯃꯄꯥꯁꯤꯡꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯐꯦꯃꯤꯂꯤ ꯁꯦꯟꯇꯔ ꯁꯦꯐꯇꯤ ꯇꯨꯜꯁꯤꯡ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 833/1000 [12:15<02:18,  1.21it/s]

[833/1000]
EN: 167 drug samples flagged as ‘not of standard quality’ in December 2025
MT: ꯏꯪꯁꯣꯛꯒꯤ ꯗꯤꯁꯦꯝꯕꯔꯗꯥ ꯗꯒ ꯁꯦꯝꯕꯦꯂ 167 ꯑꯁꯤ ꯅꯗꯔꯗ ꯀꯋꯥꯂꯤꯇꯤꯒꯤ ꯑꯣꯏꯗꯦ ꯍꯥꯏꯅ ꯐ ꯭ ꯂꯦꯒ ꯇꯧ
--------------------------------------------------

Translating:  83%|██████████████████████▌    | 834/1000 [12:16<02:10,  1.27it/s]

[834/1000]
EN: Tamil Nadu issues guidelines as chikungunya cases rise in State
MT: ꯇꯥꯃꯤꯜ ꯅꯥꯗꯨꯗ ꯆꯤꯀꯨꯡꯒꯨꯅꯒꯤ ꯀꯦꯁꯁꯤꯡ ꯍꯦꯟꯒꯠꯂꯛꯄꯗꯒꯤ ꯅꯤꯌꯝꯁꯤꯡ ꯐꯣꯡꯈꯤ
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 835/1000 [12:16<02:07,  1.29it/s]

[835/1000]
EN: Researchers develop tool to simplify nutritional tracking of Indian meals
MT: ꯊꯤꯖꯟ ꯍꯨꯝꯖꯟꯕꯁꯤꯡꯅ ꯚꯥꯔꯠꯀꯤ ꯆꯤꯟꯖꯥꯛꯁꯤꯡꯒꯤꯇꯦꯜ ꯇꯀꯤꯡ ꯂꯥꯏꯊꯣꯛꯍꯟꯅꯕ ꯇꯨꯜ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 836/1000 [12:17<02:03,  1.33it/s]

[836/1000]
EN: Shingles vaccine may also slow down biological ageing in older adults
MT: ꯁꯤꯡꯒꯜꯁ ꯚꯦꯛꯁꯤꯟꯅꯥ ꯃꯄꯨꯡ ꯐꯥꯔꯕꯥ ꯃꯤꯑꯣꯏꯁꯤꯡꯒꯤ बाइओलोजिकेल ꯑꯦꯖꯤꯡꯖꯀꯤ ꯆꯥꯡꯁꯨ ꯍꯟꯊꯍꯟꯕ ꯌꯥꯏ ꯫
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 837/1000 [12:18<02:04,  1.30it/s]

[837/1000]
EN: Gates and OpenAI team up for AI health push in African countries
MT: ꯑꯐꯀꯥꯒꯤ ꯂꯩꯕꯥꯛꯁꯤꯡꯗ ꯑꯦꯑꯏ ꯍꯛꯁꯦꯜ ꯍꯦꯟꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯒꯦꯠꯁ ꯑꯃꯁꯨꯡ ꯑꯣꯄꯟꯑꯦꯑꯥꯏ ꯇꯤꯃ ꯑꯞ ꯇꯧꯔꯦ
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 838/1000 [12:19<01:58,  1.37it/s]

[838/1000]
EN: ASHA workers protest in Kolkata for ₹15,000 monthly honorarium
MT: ꯀꯣꯜꯀꯥꯇꯥꯗꯥ ꯊꯥ ꯈꯨꯗꯤꯡꯒꯤ ꯑꯣꯅꯣꯔꯦꯔꯤꯌꯝꯒꯤꯗꯃꯛ ꯑꯥꯁꯥ ꯋꯥꯔꯀꯔꯁꯤꯡꯅ ꯋꯥꯀꯠ
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 839/1000 [12:19<02:05,  1.29it/s]

[839/1000]
EN: Bloodless heart surgery performed on patient with rare blood group at Kauvery Hospital
MT: ꯀꯥꯋꯦꯔꯤ ꯍꯣꯁꯄꯤꯇꯥꯜꯗꯥ ꯇꯥꯡꯕꯥ ꯕꯗ ꯒꯄ ꯂꯩꯕ ꯑꯅꯥꯕꯥ ꯑꯗꯨꯒꯤ ꯏ ꯌꯥꯎꯗꯕ ꯍꯥꯔꯇ ꯁꯔꯖꯔꯤ ꯄꯥꯡꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 840/1000 [12:20<02:12,  1.21it/s]

[840/1000]
EN: Centre sanctions 50-bed AYUSH hospital for Tenali, says A.P. Minister
MT: ꯀꯦꯟꯗꯅꯥ ꯇꯦꯅꯥꯂꯤꯒꯤꯗꯃꯛ ꯕꯦꯗ ꯂꯩꯕ ꯑꯥꯌꯨꯁ ꯍꯣꯁꯄꯤꯇꯥꯜ ꯑꯌꯥꯕ ꯄꯤꯔꯦ ꯍꯥꯏꯅ ꯑꯦ.ꯄꯤ. ꯃꯟꯇꯅ ꯍꯥꯏ
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 841/1000 [12:21<02:20,  1.13it/s]

[841/1000]
EN: NIMS Hyderabad opens Stem Cell Centre of Excellence as India battles rising burden of lifestyle diseases
MT: ꯅꯤꯃꯁ ꯍꯥꯏꯗꯕꯥꯗꯅ ꯁꯇꯦꯃ ꯁꯦꯜ ꯁꯦꯟꯇꯔ ꯑꯣꯐ ꯑꯦꯛꯁꯂꯦꯟꯁ ꯍꯥꯡꯗꯣꯛꯂꯦ ꯃꯔꯝꯗꯤ ꯚꯥꯔꯠꯇꯥ ꯍꯤꯡꯕꯒꯤ ꯃꯑꯣꯡꯒꯤ ꯂꯥꯏꯅꯥꯁꯤꯡ ꯍꯦꯟꯒꯠꯂꯛꯄꯒ ꯂꯥꯟꯊꯦꯡꯅꯔꯤ ꯫
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 842/1000 [12:22<02:31,  1.04it/s]

[842/1000]
EN: The Ministry of Health and Family Welfare launched a nationwide campaign to improve early detection of non-communicable diseases in rural India.
MT: ꯍꯛꯁꯦꯜ ꯑꯃꯁꯨꯡ ꯏꯃꯨꯡ-ꯃꯅꯥꯏꯒꯤ ꯋꯥꯜꯐꯦꯌꯔ ꯃꯟꯇꯅꯥ ꯈꯨꯡꯒꯪꯒꯤ ꯚꯥꯔꯠꯇꯥ ꯅꯟ-ꯀꯃ ꯭ ꯌꯨꯅꯤꯀꯦꯕꯜ ꯂꯥꯏꯅꯥꯁꯤꯡ ꯉꯟꯅ ꯈꯪꯗꯣꯛꯅꯕ ꯂꯩꯕꯥꯛ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯈꯣꯡꯖꯪ ꯑꯃ ꯍꯧ
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 843/1000 [12:23<02:21,  1.11it/s]

[843/1000]
EN: The Government of India announced an increase in funding for public hospitals under the National Health Mission.
MT: ꯚꯥꯔꯠ ꯁꯔꯀꯥꯔꯅꯥ ꯅꯦꯁꯅꯦꯜ ꯍꯦꯜꯊ ꯃꯤꯁꯟꯒꯤ ꯃꯈꯥꯗ ꯂꯩꯕ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯒꯤ ꯐꯟꯗꯤꯡ ꯍꯦꯟꯒꯠꯍꯟꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 844/1000 [12:24<02:20,  1.11it/s]

[844/1000]
EN: Indian researchers developed a low-cost diagnostic kit to detect tuberculosis with higher accuracy.
MT: ꯚꯥꯔꯠꯀꯤ ꯊꯤꯖꯟ ꯍꯨꯝꯖꯟꯕꯁꯤꯡꯅ ꯍꯦꯟꯅ ꯑꯆꯨꯝꯕꯒ ꯂꯣꯏꯅꯅ ꯇꯤꯕꯔꯀꯂꯣꯁꯤꯁ ꯈꯪꯗꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯃꯃꯜ ꯌꯥꯝꯗꯕ ꯗꯥꯏꯒꯅꯣꯁꯇꯤꯛ ꯀꯤꯇ ꯑꯃ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 845/1000 [12:25<02:18,  1.12it/s]

[845/1000]
EN: The Indian Council of Medical Research issued updated guidelines for the treatment of dengue fever.
MT: ꯏꯟꯗꯤꯌꯟ ꯀꯥꯎꯟꯁꯤꯜ ꯑꯣꯐ ꯃꯦꯗꯤꯀꯦꯜ ꯔꯤꯁꯔꯆꯅꯥ ꯗꯦꯡꯒꯨ ꯐꯤꯕꯔ ꯂꯥꯏꯌꯦꯡꯕꯒꯤ ꯑꯞꯗꯦꯇꯦꯗ ꯒꯥꯏꯗꯂꯥꯏꯟꯁꯤꯡ ꯏꯁꯨ ꯇꯧ
--------------------------------------------------

Translating:  85%|██████████████████████▊    | 846/1000 [12:26<02:15,  1.13it/s]

[846/1000]
EN: A new government medical college was inaugurated in Assam to strengthen healthcare education in the northeastern region.
MT: ꯑꯋꯥꯡ- ꯅꯣꯡꯄꯣꯛ ꯂꯝꯗꯝꯗꯥ ꯍꯦꯜꯊꯦꯀꯥꯔ ꯑꯦꯖꯨꯀꯦꯁꯟ ꯑꯗꯨ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯅꯕ ꯑꯁꯥꯝꯗ ꯑꯅꯧꯕ ꯒꯚꯔꯃꯦꯟꯇ ꯃꯦꯗꯤꯀꯦꯜ ꯀꯣꯂꯦꯖ ꯑꯃ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  85%|██████████████████████▊    | 847/1000 [12:27<02:19,  1.10it/s]

[847/1000]
EN: The Union Health Minister reviewed the progress of Ayushman Bharat services across multiple states.
MT: ꯀꯦꯟꯗꯒꯤ ꯍꯛꯁꯦꯜ ꯃꯟꯇꯅꯥ ꯇꯣꯉꯥꯟ-ꯇꯣꯉꯥꯟꯕꯇꯥ ꯑꯥꯌꯨꯁꯃꯟ ꯚꯥꯔꯠ ꯁꯔꯕꯤꯁꯦꯁꯀꯤ ꯄꯒꯁ ꯔꯤꯚ ꯇꯧ
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 848/1000 [12:28<02:19,  1.09it/s]

[848/1000]
EN: India reported a decline in maternal mortality rates due to improved institutional delivery services.
MT: ꯏꯟꯁꯇꯤꯇꯁꯅꯦꯜ ꯗꯦꯂꯤꯚꯔꯤ ꯁꯔꯕꯤꯁꯁꯤꯡ ꯐꯒꯠꯂꯛꯄꯅꯥ ꯃꯔꯝ ꯑꯣꯏꯗꯨꯅ ꯚꯥꯔꯠꯇꯥ ꯃꯦꯇꯔꯅꯦꯜ ꯃꯣꯔꯇꯥꯂꯤꯇꯤ ꯔꯦꯠ ꯍꯟꯊꯔꯛꯄꯒꯤ ꯄꯥꯎ ꯄꯤ
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 849/1000 [12:29<02:14,  1.12it/s]

[849/1000]
EN: The Drug Controller General of India approved a new vaccine for preventing cervical cancer.
MT: ꯗꯒ ꯀꯟꯇꯜꯂꯔ ꯖꯦꯅꯔꯦꯜ ꯑꯣꯐ ꯏꯟꯗꯤꯌꯥꯅꯥ ꯁꯔꯚꯤꯀꯦꯜ ꯀꯦꯟꯁꯔ ꯊꯤꯡꯅꯕꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯕꯦꯛꯁꯤꯟ ꯑꯃ ꯑꯌꯥꯕ ꯄꯤ
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 850/1000 [12:30<02:13,  1.12it/s]

[850/1000]
EN: Several state governments expanded free dialysis services in district hospitals.
MT: ꯇ ꯒꯕꯔꯅꯃꯦꯟꯇ ꯀꯌꯥꯅꯥ ꯗꯤꯁꯇꯛꯇ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯗ ꯐ ꯗꯥꯏꯂꯥꯏꯁꯤꯁ ꯁꯔꯕꯤꯁꯁꯤꯡ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 851/1000 [12:30<02:17,  1.09it/s]

[851/1000]
EN: The World Health Organization praised India’s efforts in polio eradication during a regional health summit.
MT: ꯋꯥꯔꯂ ꯭ ꯗ ꯍꯦꯜꯊ ꯑꯣꯔꯒꯥꯅꯥꯏꯖꯦꯁꯟꯅꯥ ꯔꯤꯖꯅꯦꯜ ꯍꯦꯂꯊ ꯁꯝꯃꯤꯠ ꯑꯃꯗ ꯄꯣꯂꯤꯑꯣ ꯃꯨꯠꯊꯠꯄꯗꯥ ꯚꯥꯔꯠꯅ ꯍꯣꯠꯅꯔꯤꯕꯁꯤꯡ ꯑꯗꯨ ꯊꯥꯒꯠ
--------------------------------------------------

Translating:  85%|███████████████████████    | 852/1000 [12:31<02:13,  1.11it/s]

[852/1000]
EN: A public health survey revealed improved vaccination coverage among children in urban slum areas.
MT: ꯄ ꯍꯦꯜꯊ ꯁꯔꯚꯦ ꯑꯃꯅ ꯑꯔꯕꯟ ꯁꯜꯃ ꯑꯦꯔꯤꯌꯥꯁꯤꯡꯒꯤ ꯑꯉꯥꯡꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯕꯦꯛꯁꯤꯅꯦꯁꯟ ꯀꯚꯔꯦꯖ ꯐꯒꯠꯍꯟꯕꯥ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  85%|███████████████████████    | 853/1000 [12:32<02:14,  1.09it/s]

[853/1000]
EN: The Ministry of AYUSH promoted traditional medicine research through newly funded clinical studies.
MT: ꯑꯥꯌꯨꯁ ꯃꯟꯇꯅꯥ ꯑꯅꯧꯕ ꯁꯦꯜ ꯊꯥꯗꯕ ꯀꯂꯤꯅꯤꯀꯦꯜꯗꯤꯖꯁꯤꯡꯒꯤ ꯈꯨꯠꯊꯥꯡꯗꯗꯤꯁꯅꯦꯜ ꯃꯦꯗꯤꯁꯤꯟ ꯔꯤꯁꯔꯆꯄꯨ ꯄ ꯭ ꯔꯣꯃꯣꯇ ꯇꯧ
--------------------------------------------------

Translating:  85%|███████████████████████    | 854/1000 [12:33<02:16,  1.07it/s]

[854/1000]
EN: Indian hospitals adopted artificial intelligence tools to assist doctors in early cancer detection.
MT: ꯀꯦꯟꯁꯔ ꯑꯁꯤ ꯉꯟꯅ ꯈꯪꯗꯣꯛꯄꯗꯥ ꯗꯣꯛꯇꯔꯁꯤꯡꯕꯨ ꯃꯇꯦꯡ ꯄꯥꯡꯅꯕ ꯏꯟꯗꯤꯌꯟ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯅ ꯑꯥꯔꯇꯤꯐꯤꯁꯦꯜ ꯏꯟꯇꯦꯂꯤꯖꯦꯟꯁꯀꯤ ꯇꯨꯜꯁꯤꯡ ꯁꯤꯖꯤꯟꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████    | 855/1000 [12:34<02:20,  1.03it/s]

[855/1000]
EN: The National Medical Commission introduced revised norms for undergraduate medical education.
MT: ꯅꯦꯁꯅꯦꯜ ꯃꯦꯗꯤꯀꯦꯜ ꯀꯃꯤꯁꯟꯅꯥ ꯑꯡꯒꯖꯨꯑꯦꯠ ꯃꯦꯗꯗꯤꯀꯦꯜ ꯑꯦꯖꯨꯀꯦꯁꯟꯒꯤꯗꯃꯛ ꯔꯤꯚꯥꯏꯖ ꯇꯧꯔꯕꯥ ꯅꯤꯌꯝꯁꯤꯡ ꯆꯠꯅꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████    | 856/1000 [12:35<02:18,  1.04it/s]

[856/1000]
EN: A shortage of specialist doctors was reported in government hospitals across rural districts.
MT: ꯈꯨꯡꯒꯪꯒꯤ ꯖꯤꯂꯥꯁꯤꯡ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯂꯩꯕ ꯁꯔꯀꯥꯔꯒꯤ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯗ ꯁꯄꯁꯤꯌꯦꯂꯤꯁꯇ ꯗꯣꯛꯇꯔꯁꯤꯡꯒꯤ ꯑꯋꯥꯠꯄ ꯂꯩ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 857/1000 [12:36<02:16,  1.05it/s]

[857/1000]
EN: The central government launched a digital health ID system to streamline patient medical records.
MT: ꯀꯦꯟꯗ ꯁꯔꯀꯥꯔꯅꯥ ꯑꯅꯥꯕꯥꯁꯤꯡꯒꯤ ꯃꯦꯗꯤꯀꯦꯜ ꯔꯦꯀꯣꯔꯗꯁꯤꯡ ꯁꯃꯂꯥꯏꯟ ꯇꯧꯅꯕꯒꯤꯗꯃꯛ ꯗꯤꯖꯤꯇꯦꯜ ꯍꯦꯜꯊ ꯑꯥꯏꯗꯤ ꯁꯤꯁꯇꯦꯝ ꯑꯃ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 858/1000 [12:37<02:13,  1.07it/s]

[858/1000]
EN: India’s pharmaceutical exports increased due to rising global demand for generic medicines.
MT: ꯖꯦꯅꯦꯔꯤꯛ ꯍꯤꯗꯥꯛ-ꯃꯇꯥꯏꯁꯤꯡꯒꯤ ꯒ ꯭ ꯂꯣꯕꯦꯜ ꯗꯤꯃꯥꯟꯗ ꯍꯦꯟꯒꯠꯂꯛꯄꯗꯒꯤ ꯚꯥꯔꯠꯀꯤ ꯐꯥꯔꯃꯥꯁꯤꯌꯨꯇꯤꯀꯦꯜ ꯑꯦꯛꯁꯄꯣꯔꯇꯁꯤꯡ ꯍꯦꯟꯒꯠꯂꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 859/1000 [12:38<02:11,  1.08it/s]

[859/1000]
EN: The Supreme Court of India directed states to improve healthcare infrastructure in tribal areas.
MT: ꯚꯥꯔꯠꯀꯤ ꯁꯨꯄꯝ ꯀꯣꯔꯠꯅꯇꯁꯤꯡꯗ ꯇꯥꯏꯕꯦꯜ ꯑꯦꯔꯤꯌꯥꯁꯤꯡꯒꯤ ꯍꯛꯁꯦꯜꯒꯤ ꯏꯟꯐꯁꯇꯛꯆꯔ ꯐꯒꯠꯍꯟꯅꯕ ꯂꯝꯖꯤꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 860/1000 [12:39<02:07,  1.10it/s]

[860/1000]
EN: A government report highlighted gaps in mental health services in public healthcare facilities.
MT: ꯒꯚꯔꯃꯦꯟꯇ ꯔꯤꯄꯣꯔꯇ ꯑꯃꯅ ꯍꯦꯜꯊꯦꯌꯔ ꯐꯦꯁꯤꯂꯤꯇꯤꯁꯤꯡꯗ ꯃꯦꯟꯇꯥꯜ ꯍꯦꯜꯊ ꯁꯔꯕꯤꯁꯁꯤꯡꯒꯤ ꯑꯍꯥꯡꯕꯁꯤꯡ ꯎꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 861/1000 [12:40<02:05,  1.10it/s]

[861/1000]
EN: Several private hospitals partnered with state governments to offer affordable cardiac care.
MT: ꯂꯅꯥꯏꯒꯤ ꯍꯣꯁꯄꯤꯇꯥꯜ ꯀꯌꯥꯅꯥꯇ ꯒꯚꯔꯃꯦꯟꯇꯁꯤꯡꯒ ꯂꯣꯏꯅꯅꯥ ꯃꯃꯜ ꯌꯥꯝꯗꯕ ꯀꯥꯔꯗꯤꯑꯦꯛ ꯀꯦꯌꯔ ꯄꯤꯅꯕ ꯁꯔꯨꯛ ꯌꯥꯔꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 862/1000 [12:41<02:08,  1.08it/s]

[862/1000]
EN: The Indian Institute of Public Health conducted a study on air pollution-related respiratory diseases.
MT: ꯏꯟꯗꯤꯌꯟ ꯏꯟꯁꯇꯤꯇꯇ ꯑꯣꯐ ꯄ ꯍꯦꯜꯊꯅꯥ ꯅꯨꯡꯁꯤꯠꯀꯤ ꯄꯨꯂꯨꯁꯟꯒ ꯃꯔꯤ ꯂꯩꯅꯕ ꯁꯄꯔꯦꯇꯔꯤ ꯗꯤꯖꯤꯖꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯊꯤꯖꯤꯟꯕꯒꯤ ꯊꯕꯛ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 863/1000 [12:42<02:06,  1.09it/s]

[863/1000]
EN: Health officials initiated a special drive to control the spread of seasonal influenza.
MT: ꯍꯛꯁꯦꯜꯒꯤ ꯑꯣꯐꯤꯁꯌꯦꯜꯁꯤꯡꯅ ꯁꯤꯖꯅꯦꯜ ꯏꯟꯐꯂꯨꯑꯦꯟꯖꯥ ꯁꯟꯗꯣꯛꯄꯥ ꯀꯟꯇꯣꯜ ꯇꯧꯅꯕꯒꯤꯗꯃꯛ ꯊꯣꯏꯗꯣꯛꯍꯦꯟꯗꯣꯛꯄ ꯊꯧꯁꯤꯜ ꯑꯃ ꯍꯧ
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 864/1000 [12:43<02:06,  1.08it/s]

[864/1000]
EN: The Ministry of Health strengthened surveillance systems to monitor emerging infectious diseases.
MT: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥ ꯍꯧꯒꯠꯂꯛꯄꯥ ꯏꯟꯐꯦꯛꯁ ꯭ ꯌꯦꯁ ꯑꯣꯏꯕ ꯂꯥꯏꯅꯥꯁꯤꯡ ꯌꯦꯡꯁꯤꯟꯅꯕ ꯌꯦꯡꯁꯤꯟꯕꯒꯤ ꯁꯤꯁꯇꯦꯝꯁꯤꯡ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 865/1000 [12:43<02:03,  1.09it/s]

[865/1000]
EN: India recorded a steady rise in organ donation registrations through national awareness campaigns.
MT: ꯚꯥꯔꯠꯇꯥ ꯅꯦꯁꯅꯦꯜ ꯑꯦꯚꯦꯌꯔꯅꯦꯁ ꯀꯦꯝꯄꯦꯟꯁꯤꯡꯒꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯑꯣꯒꯅꯥ ꯗꯣꯅꯦꯁꯟ ꯔꯦꯖꯤꯁꯇꯦꯁꯟꯁꯤꯡ ꯆꯥꯡ ꯅꯥꯏꯅ ꯍꯦꯟꯒꯠꯂꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 866/1000 [12:44<01:57,  1.14it/s]

[866/1000]
EN: A new telemedicine platform was introduced to improve access to healthcare in remote villages.
MT: ꯂꯥꯞꯊꯣꯛꯂꯕ ꯈꯨꯡꯒꯪꯁꯤꯡꯗ ꯍꯛꯁꯦꯜꯒꯤ ꯈꯨꯗꯣꯡꯆꯥꯕꯥ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯇꯦꯂꯤꯃꯦꯗꯤꯁꯤꯟꯇꯐꯣꯔꯝ ꯑꯃ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 867/1000 [12:45<01:56,  1.14it/s]

[867/1000]
EN: The National AIDS Control Organisation reported a decline in new HIV infections.
MT: ꯅꯦꯁꯅꯦꯜ ꯑꯦꯗꯁ ꯀꯟꯇꯣꯜ ꯑꯣꯔꯒꯥꯅꯥꯏꯖꯦꯁꯟꯅꯥ ꯑꯅꯧꯕ ꯑꯩꯆꯑꯥꯏꯚꯤ ꯏꯟꯐꯦꯛꯁꯟꯁꯤꯡ ꯍꯟꯊꯔꯛꯄꯒꯤ ꯄꯥꯎꯗꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 868/1000 [12:46<01:56,  1.13it/s]

[868/1000]
EN: Government hospitals increased the availability of free essential medicines for outpatients.
MT: ꯒꯚꯔꯃꯦꯟꯇ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡ ꯑꯁꯤꯅ ꯑꯥꯎꯇꯄꯦꯇꯤꯌꯦꯟꯇꯁꯤꯡꯒꯤꯗꯃꯛ ꯇꯉꯥꯏꯐꯗꯕ ꯍꯤꯗꯥꯛꯁꯤꯡ ꯐꯪꯍꯟꯕꯥ ꯍꯦꯟꯒꯠꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 869/1000 [12:47<01:58,  1.10it/s]

[869/1000]
EN: A policy review emphasized the need for more nursing staff in public healthcare institutions.
MT: ꯄꯣꯂꯤꯁꯤ ꯔꯤꯚꯤꯎ ꯑꯃꯥꯅꯥ ꯄ ꯍꯦꯜꯊꯦꯌꯔ ꯏꯟꯁꯇꯤꯇꯁꯟꯁꯤꯡꯗ ꯅꯔꯁꯤꯡꯐ ꯍꯦꯟꯅ ꯃꯊꯧ ꯇꯥꯕꯒꯤ ꯃꯔꯝꯗꯥ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 870/1000 [12:48<01:52,  1.16it/s]

[870/1000]
EN: The Indian government signed a health cooperation agreement with a neighboring country.
MT: ꯚꯥꯔꯠ ꯁꯔꯀꯥꯔꯅꯥ ꯌꯨꯝꯂꯣꯟꯅꯕ ꯂꯩꯕꯥꯛ ꯑꯃꯒ ꯍꯦꯜꯊ ꯀꯣꯑꯣꯄꯔꯦꯁꯟ ꯑꯦꯒꯃꯦꯟꯇ ꯑꯃ ꯈꯨꯠꯌꯦꯛ ꯄꯤꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 871/1000 [12:49<01:54,  1.13it/s]

[871/1000]
EN: Researchers from an Indian medical institute published findings on antibiotic resistance trends.
MT: ꯏꯟꯗꯤꯌꯟ ꯃꯦꯗꯤꯀꯦꯜ ꯏꯟꯁꯇꯤꯇꯠꯇꯒꯤ ꯊꯤꯖꯟ ꯍꯨꯝꯖꯟꯕꯁꯤꯡꯅ ꯑꯦꯟꯇꯤꯕꯥꯏꯑꯣꯇꯤꯛ ꯔꯦꯖꯤꯁꯇꯦꯟꯁꯦꯟꯗꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯊꯤꯒꯠꯄꯁꯤꯡ ꯐꯣꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 872/1000 [12:50<01:50,  1.16it/s]

[872/1000]
EN: The Health Ministry issued advisories to states following a rise in heat-related illnesses.
MT: ꯍꯛꯁꯦꯜ ꯃꯟꯇꯅꯥ ꯃꯩꯁꯥꯒꯥ ꯃꯔꯤ ꯂꯩꯅꯕ ꯂꯥꯏꯅꯥꯁꯤꯡ ꯍꯦꯟꯒꯠꯂꯛꯄꯗꯒꯤ ꯔꯥꯖꯁꯤꯡꯗ ꯑꯦꯗꯚꯥꯏꯖꯔꯤꯁꯤꯡ ꯄꯤ
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 873/1000 [12:50<01:52,  1.13it/s]

[873/1000]
EN: India expanded its emergency ambulance network to improve response times in rural regions.
MT: ꯚꯥꯔꯠꯅ ꯃꯈꯣꯏꯒꯤ ꯏꯃꯔꯖꯦꯟꯁꯤ ꯑꯦꯝꯕꯂꯦꯟꯁ ꯅꯦꯠꯋꯥꯔꯛ ꯑꯗꯨ ꯈꯨꯡꯒꯪꯒꯤ ꯂꯝꯗꯝꯁꯤꯡꯗ ꯔꯤꯄꯣꯟꯁ ꯇꯥꯏꯝꯁꯤꯡ ꯐꯒꯠꯍꯟꯅꯕ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 874/1000 [12:51<01:49,  1.15it/s]

[874/1000]
EN: The National Digital Health Mission aimed to improve transparency in healthcare service delivery.
MT: ꯅꯦꯁꯅꯦꯜ ꯗꯤꯖꯤꯇꯦꯜ ꯍꯦꯜꯊ ꯃꯤꯁꯟ ꯑꯁꯤꯅ ꯍꯦꯜꯊꯦꯌꯔ ꯁꯔꯕꯤꯁ ꯗꯤꯂꯤꯚꯔꯤꯗꯥꯄꯔꯦꯟꯁꯤꯇꯤ ꯐꯒꯠꯍꯟꯅꯕ ꯄꯥꯟꯗꯝ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 875/1000 [12:53<02:04,  1.01it/s]

[875/1000]
EN: A public-private partnership model was introduced to upgrade district-level hospitals.
MT: ꯗꯤꯁꯇꯛꯇ-ꯂꯦꯚꯦꯜ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡ ꯑꯒꯗ ꯇꯧꯅꯕꯒꯤꯗꯃꯛ ꯄꯕꯀꯜ-ꯄꯥꯏꯚꯦꯇ ꯄꯔꯅꯥꯇꯔꯁꯤꯞ ꯃꯣꯗꯦꯜ ꯑꯃ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 876/1000 [12:53<01:58,  1.05it/s]

[876/1000]
EN: The government launched a mental health helpline to support individuals during medical emergencies.
MT: ꯁꯔꯀꯥꯔꯅꯥ ꯃꯦꯗꯤꯀꯦꯜ ꯏꯃꯔꯖꯦꯟꯁꯤꯁꯤꯡꯒꯤ ꯃꯇꯝꯗ ꯃꯤꯌꯣꯏꯁꯤꯡꯕꯨ ꯃꯇꯦꯡ ꯄꯥꯡꯅꯕ ꯃꯦꯟꯇꯦꯜ ꯍꯦꯜꯊꯂꯥꯏꯟ ꯑꯃ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 877/1000 [12:54<01:51,  1.10it/s]

[877/1000]
EN: India’s medical tourism sector showed growth due to affordable treatment options.
MT: ꯚꯥꯔꯠꯀꯤ ꯃꯦꯗꯤꯀꯦꯜ ꯇꯨꯔꯤꯖꯝ ꯁꯦꯛꯇꯔꯅ ꯃꯃꯜ ꯅꯥꯏꯕꯥ ꯂꯥꯏꯌꯦꯡꯒꯤ ꯑꯣꯞꯁꯟꯁꯤꯡ ꯂꯩꯕꯅ ꯃꯔꯝ ꯑꯣꯏꯗꯨꯅ ꯆꯥꯎꯈꯠꯂꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 878/1000 [12:55<01:53,  1.08it/s]

[878/1000]
EN: A parliamentary committee reviewed the implementation of healthcare schemes in backward districts.
MT: ꯄꯥꯔꯂꯤꯌꯥꯃꯦꯟꯇꯀꯤ ꯀꯝꯃꯤꯇꯤ ꯑꯃꯅ ꯕꯦꯀꯋꯥꯔꯗ ꯗꯤꯁꯇꯛꯇꯁꯤꯡꯗ ꯍꯦꯜꯊꯦꯌꯔꯀꯤꯝꯁꯤꯡ ꯆꯠꯅꯍꯟꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯔꯤꯚ ꯇꯧ
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 879/1000 [12:56<01:48,  1.11it/s]

[879/1000]
EN: The Ministry of Health emphasized preventive healthcare during a national policy meeting.
MT: ꯅꯦꯁꯅꯦꯜ ꯄꯣꯂꯤꯁꯤ ꯃꯤꯇꯤꯡ ꯑꯃꯗ ꯍꯛꯁꯦꯜ ꯃꯟꯇꯅꯥ ꯄꯇꯤꯚꯦꯟꯇꯋꯦꯜ ꯍꯦꯜꯊꯦꯌꯔꯗꯥ ꯄꯨꯛꯅꯤꯡ ꯆꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 880/1000 [12:57<01:48,  1.11it/s]

[880/1000]
EN: Indian scientists developed a wearable device to monitor heart health in elderly patients.
MT: ꯚꯥꯔꯠꯀꯤ ꯁꯥꯏꯅꯇꯤꯁꯁꯤꯡꯅ ꯆꯍꯤ ꯋꯥꯡꯕꯥ ꯑꯅꯥꯕꯥꯁꯤꯡꯒꯤ ꯍꯔꯇ ꯍꯦꯜꯊ ꯌꯦꯡꯁꯤꯟꯅꯕ ꯌꯦꯔꯦꯑꯦꯕꯜ ꯗꯤꯚꯥꯏꯁ ꯑꯃ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 881/1000 [12:58<01:40,  1.18it/s]

[881/1000]
EN: A national survey assessed nutritional deficiencies among children under five years of age.
MT: ꯅꯦꯁꯅꯦꯜ ꯁꯔꯚꯦ ꯑꯃꯅ ꯆꯍꯤ ꯃꯉꯥꯒꯤ ꯃꯈꯥꯗ ꯂꯩꯕ ꯑꯉꯥꯡꯁꯤꯡꯒꯤꯇꯦꯜ ꯗꯤꯐꯤꯁꯤꯟꯁꯤꯁꯤꯡ ꯌꯦꯡꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 882/1000 [12:59<01:40,  1.18it/s]

[882/1000]
EN: The government increased insurance coverage limits under Ayushman Bharat for critical illnesses.
MT: ꯁꯔꯀꯥꯔꯅꯥ ꯀꯇꯤꯀꯦꯜ ꯏꯂꯥꯏꯟꯁꯁꯤꯡꯒꯤꯗꯃꯛ ꯑꯥꯌꯨꯁꯃꯟ ꯚꯥꯔꯠꯀꯤ ꯃꯈꯥꯗ ꯏꯟꯁꯨꯔꯦꯟꯁ ꯀꯣꯚꯔꯦꯖ ꯂꯤꯃꯤꯇꯁꯤꯡ ꯍꯦꯟꯒꯠꯍꯟ
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 883/1000 [12:59<01:37,  1.20it/s]

[883/1000]
EN: Health authorities conducted vaccination drives to prevent outbreaks of measles and rubella.
MT: ꯍꯛꯁꯦꯜꯒꯤ ꯊꯧꯗꯥꯡꯂꯣꯏꯁꯤꯡꯅ ꯃꯤꯖꯜꯁ ꯑꯃꯁꯨꯡ ꯔꯨꯕꯦꯂꯥ ꯁꯟꯗꯣꯛꯇꯅꯕ ꯕꯦꯛꯁꯤꯅꯦꯁꯟ ꯗꯚꯁꯤꯡ ꯄꯥꯡꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 884/1000 [13:00<01:37,  1.19it/s]

[884/1000]
EN: India strengthened laboratory capacity to improve disease surveillance and diagnosis.
MT: ꯚꯥꯔꯠꯅ ꯂꯥꯏꯅꯥ ꯌꯦꯡꯁꯤꯟꯕ ꯑꯃꯁꯨꯡ ꯂꯥꯏꯑꯣꯡ ꯈꯪꯗꯣꯛꯄꯒꯤ ꯐꯤꯕꯝ ꯐꯒꯠꯍꯟꯅꯕ ꯂꯦꯕꯣꯔꯦꯇꯔꯤ ꯀꯦꯄꯦꯁꯤꯇꯤ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▉   | 885/1000 [13:01<01:45,  1.09it/s]

[885/1000]
EN: A state health department launched mobile clinics to serve remote tribal communities.
MT: ꯔꯥꯖꯒꯤ ꯍꯛꯁꯦꯜ ꯗꯤꯄꯥꯔꯇꯃꯦꯟꯇ ꯑꯃꯅ ꯂꯥꯞꯊꯣꯛꯂꯕ ꯇꯥꯏꯕꯦꯜ ꯀꯝꯃꯅꯤꯇꯤꯁꯤꯡꯒꯤ ꯁꯦꯕꯥ ꯇꯧꯅꯕꯒꯤꯗꯃꯛ ꯃꯣꯕꯥꯏꯜ ꯀꯂꯤꯅꯤꯛꯁꯤꯡ ꯍꯥꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 886/1000 [13:02<01:42,  1.12it/s]

[886/1000]
EN: The National Health Authority upgraded its data systems to enhance patient safety.
MT: ꯅꯦꯁꯅꯦꯜ ꯍꯦꯜꯊ ꯑꯣꯊꯣꯔꯤꯇꯤꯅꯥ ꯃꯈꯣꯏꯒꯤ ꯗꯦꯇꯥ ꯁꯤꯁꯇꯦꯝꯁꯤꯡ ꯑꯁꯤ ꯑꯅꯥꯕꯥꯁꯤꯡꯒꯤ ꯁꯦꯐꯇꯤ ꯍꯦꯟꯒꯠꯍꯟꯅꯕ ꯑꯞꯒꯗ ꯇꯧ
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 887/1000 [13:03<01:38,  1.15it/s]

[887/1000]
EN: Indian doctors highlighted the need for early screening of lifestyle-related diseases.
MT: ꯚꯥꯔꯠꯀꯤ ꯗꯣꯛꯇꯔꯁꯤꯡꯅ ꯍꯤꯡꯕꯒꯤ ꯃꯑꯣꯡꯒ ꯃꯔꯤ ꯂꯩꯅꯕ ꯂꯥꯏꯅꯥꯁꯤꯡ ꯉꯟꯅ ꯁꯅꯤꯡ ꯇꯧꯕꯒꯤ ꯃꯊꯧ ꯇꯥꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯍꯥꯏꯂꯥꯏꯇ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 888/1000 [13:04<01:35,  1.17it/s]

[888/1000]
EN: The Ministry of Health released new guidelines for hospital waste management.
MT: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥ ꯍꯣꯁꯄꯤꯇꯥꯜ ꯋꯇ ꯃꯦꯅꯖꯃꯦꯟꯇꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯅꯤꯌꯝꯁꯤꯡ ꯐꯣꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  89%|████████████████████████   | 889/1000 [13:04<01:29,  1.24it/s]

[889/1000]
EN: Several states reported improvements in primary healthcare access through wellness centers.
MT: ꯔꯥꯖ ꯀꯌꯥꯅꯥ ꯋꯦꯜꯅꯦꯁ ꯁꯦꯟꯇꯔꯁꯤꯡꯒꯤ ꯈꯨꯠꯊꯥꯡꯗꯥꯏꯃꯔꯤ ꯍꯦꯜꯊꯀꯦꯌꯔ ꯑꯦꯛꯁꯦꯁꯇ ꯐꯒꯠꯂꯛꯄꯒꯤ ꯄꯥꯎꯗꯝ
--------------------------------------------------

Translating:  89%|████████████████████████   | 890/1000 [13:05<01:26,  1.28it/s]

[890/1000]
EN: India’s public health expenditure showed a gradual increase in the latest budget.
MT: ꯚꯥꯔꯠꯀꯤꯍꯦꯜꯊ ꯆꯥꯗꯤꯡꯅꯥ ꯈ ꯭ ꯋꯥꯏꯗꯒꯤ ꯅꯧꯕ ꯕꯖꯦꯇꯗꯥ ꯃꯊꯪ-ꯃꯇꯥ ꯍꯦꯟꯒꯠꯂꯛꯄ ꯎꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  89%|████████████████████████   | 891/1000 [13:06<01:23,  1.30it/s]

[891/1000]
EN: A new online portal was launched to track the availability of hospital beds.
MT: ꯍꯣꯁꯄꯤꯇꯥꯜꯒꯤ ꯕꯦꯗꯁꯤꯡ ꯐꯪꯕꯥ ꯇꯦꯛ ꯇꯧꯅꯕꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯑꯣꯟꯂꯥꯏꯟ ꯄꯣꯔꯇꯦꯜ ꯑꯃ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  89%|████████████████████████   | 892/1000 [13:07<01:25,  1.26it/s]

[892/1000]
EN: Health experts in India raised concerns about rising cases of diabetes among young adults.
MT: ꯚꯥꯔꯠꯀꯤ ꯍꯦꯜꯊ ꯑꯦꯛꯁꯄꯥꯔꯇꯁꯤꯡꯅꯥ ꯑꯉꯥꯡ ꯑꯣꯏꯔꯕꯥ ꯃꯤꯑꯣꯏꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯗꯥꯏꯑꯦꯕꯦꯇꯤꯁꯀꯤ ꯀꯦꯁꯁꯤꯡ ꯍꯦꯟꯒꯠꯂꯛꯄꯒꯤ ꯃꯇꯥꯡꯗ ꯋꯥꯈꯜ ꯋꯥꯊꯣꯛ ꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  89%|████████████████████████   | 893/1000 [13:08<01:28,  1.21it/s]

[893/1000]
EN: The government initiated training programs to improve emergency care skills among paramedics.
MT: ꯁꯔꯀꯥꯔꯅꯥ ꯄꯦꯔꯥꯃꯦꯗꯤꯛꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯏꯃꯔꯖꯦꯟꯁꯤ ꯀꯦꯌꯔꯒꯤ ꯍꯩꯁꯤꯡꯕꯁꯤꯡ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛꯅꯤꯡꯒꯔꯥꯝꯁꯤꯡ ꯍꯧꯍꯟ
--------------------------------------------------

Translating:  89%|████████████████████████▏  | 894/1000 [13:09<01:32,  1.15it/s]

[894/1000]
EN: Indian pharmaceutical companies invested in research for affordable cancer medicines.
MT: ꯚꯥꯔꯠꯀꯤ ꯐꯥꯔꯃꯥꯁꯤꯌꯨꯇꯤꯀꯦꯜ ꯀꯝꯄꯅꯤꯁꯤꯡꯅꯥ ꯀꯦꯟꯁꯔꯒꯤ ꯍꯤꯗꯥꯛ-ꯃꯊꯛꯀꯤ ꯔꯤꯁꯔꯆꯗꯥ ꯁꯦꯜ ꯊꯥꯗ
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 895/1000 [13:09<01:25,  1.22it/s]

[895/1000]
EN: A national task force was formed to address antimicrobial resistance.
MT: ꯑꯦꯟꯇꯤꯃꯥꯏꯀꯕꯥꯏꯜ ꯔꯦꯖꯤꯁꯇꯦꯟꯁ ꯀꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯅꯦꯁꯅꯦꯜ ꯇꯛꯁ ꯐꯣꯔꯁ ꯑꯃ ꯁꯦꯝ
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 896/1000 [13:10<01:26,  1.20it/s]

[896/1000]
EN: The Health Ministry conducted audits to improve quality standards in government hospitals.
MT: ꯍꯛꯁꯦꯜ ꯃꯟꯇꯅꯥ ꯒꯚꯔꯃꯦꯟꯇ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯒꯤ ꯀꯋꯥꯂꯤꯇꯤꯦꯟꯗꯗꯔ ꯐꯒꯠꯍꯟꯅꯕ ꯑꯣꯗꯤꯇꯁꯤꯡ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 897/1000 [13:11<01:27,  1.17it/s]

[897/1000]
EN: India expanded maternal nutrition programs to reduce anemia among pregnant women.
MT: ꯃꯤꯔꯣꯜꯂꯤꯕꯤ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯏꯅꯤꯃꯤꯌꯥ ꯍꯟꯊꯍꯟꯅꯕ ꯚꯥꯔꯠꯅ ꯃꯦꯇꯔꯅꯦꯜ ꯅꯇꯁꯟꯒꯔꯥꯝꯁꯤꯡ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 898/1000 [13:12<01:23,  1.22it/s]

[898/1000]
EN: A state government announced free health checkups for senior citizens.
MT: ꯁꯇ ꯒꯚꯔꯃꯦꯟꯇꯅꯥ ꯁꯦꯅꯤꯌꯔ ꯁꯤꯇꯤꯖꯟꯁꯤꯡꯒꯤ ꯐ ꯍꯦꯜꯊ ꯆꯦꯛꯑꯞꯁꯤꯡ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 899/1000 [13:13<01:31,  1.11it/s]

[899/1000]
EN: Indian healthcare startups focused on digital solutions for chronic disease management.
MT: ꯀꯅꯤꯛ ꯗꯤꯖꯤꯖ ꯃꯦꯅꯖꯃꯦꯟꯇꯒꯤꯗꯃꯛ ꯏꯟꯗꯤꯌꯟ ꯍꯦꯜꯊꯀꯦꯌꯔꯇꯥꯔꯇꯑꯞꯁꯅ ꯗꯤꯖꯦꯇꯤꯜ ꯁꯂꯨꯁꯟꯁꯤꯡꯗ ꯃꯤꯠꯌꯦꯡ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 900/1000 [13:14<01:29,  1.12it/s]

[900/1000]
EN: The National Health Policy emphasized universal access to affordable healthcare services.
MT: ꯅꯦꯁꯅꯦꯜ ꯍꯦꯜꯊ ꯄꯣꯂꯤꯁꯤꯅꯥ ꯃꯃꯜ ꯅꯥꯏꯕꯥ ꯍꯦꯜꯊꯦꯌꯔ ꯁꯔꯕꯤꯁꯁꯤꯡꯒꯤ ꯌꯨꯅꯤꯚꯦꯁꯜ ꯑꯦꯛꯁꯦꯁꯇ ꯄꯨꯛꯅꯤꯡ ꯆꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 901/1000 [13:15<01:28,  1.12it/s]

[901/1000]
EN: Public health officials promoted lifestyle changes to reduce cardiovascular disease risks.
MT: ꯍꯦꯜꯊ ꯑꯣꯐꯤꯁꯌꯦꯜꯁꯤꯡꯅ ꯀꯥꯔꯗꯤꯑꯣꯁꯀꯦꯜ ꯗꯤꯖꯤꯖ ꯔꯤꯁꯀꯁꯤꯡ ꯍꯟꯊꯍꯟꯅꯕ ꯍꯤꯡꯕꯒꯤ ꯃꯑꯣꯡ ꯍꯣꯡꯗꯣꯛꯅꯕ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 902/1000 [13:16<01:27,  1.12it/s]

[902/1000]
EN: India improved cold chain infrastructure to ensure vaccine safety and effectiveness.
MT: ꯚꯥꯔꯠꯅ ꯕꯦꯛꯁꯤꯟ ꯁꯦꯐꯇꯤ ꯑꯃꯁꯨꯡ ꯑꯦꯐꯦꯛꯇꯤꯚꯦꯟꯁꯤꯇꯤ ꯐꯪꯍꯟꯅꯕ ꯀꯣꯜꯗ ꯆꯦꯟ ꯏꯟꯐꯁꯇꯛꯆꯔ ꯐꯒꯠꯍꯟ
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 903/1000 [13:17<01:28,  1.10it/s]

[903/1000]
EN: A medical research institute in India studied long-term effects of COVID-19 infections.
MT: ꯚꯥꯔꯠꯀꯤ ꯃꯦꯗꯤꯀꯦꯜ ꯔꯤꯁꯔꯆ ꯏꯟꯁꯇꯤꯇꯇ ꯑꯃꯅ ꯀꯣꯋꯤꯗ-19 ꯏꯟꯐꯦꯛꯁꯟꯁꯤꯡꯒꯤ ꯂꯣꯡ-ꯇꯔꯃ ꯏꯐꯦꯛꯠꯁꯤꯡ ꯇꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 904/1000 [13:17<01:25,  1.13it/s]

[904/1000]
EN: The government strengthened referral systems between primary and tertiary healthcare centers.
MT: ꯁꯔꯀꯥꯔꯅꯥꯃꯤꯔꯤ ꯑꯃꯁꯨꯡ ꯇꯔꯁꯤꯌꯔꯤ ꯍꯦꯜꯊꯦꯌꯔ ꯁꯦꯟꯇꯔꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯔꯤꯐꯔꯦꯜ ꯁꯤꯁꯇꯦꯝꯁꯤꯡ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 905/1000 [13:18<01:18,  1.21it/s]

[905/1000]
EN: Health workers received additional training to improve immunization coverage.
MT: ꯏꯃꯨꯅꯥꯏꯖꯦꯁꯟ ꯀꯚꯔꯦꯖ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯍꯦꯜꯊ ꯋꯥꯔꯀꯔꯁꯤꯡꯅꯥ ꯑꯍꯦꯟꯕꯅꯤꯡ ꯐꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  91%|████████████████████████▍  | 906/1000 [13:19<01:14,  1.26it/s]

[906/1000]
EN: India expanded newborn care units to reduce infant mortality rates.
MT: ꯑꯉꯥꯡ ꯁꯤꯕꯒꯤ ꯆꯥꯡ ꯍꯟꯊꯍꯟꯅꯕ ꯚꯥꯔꯠꯅ ꯅꯕꯥꯟꯗ ꯀꯦꯌꯔ ꯌꯨꯅꯤꯇꯁꯤꯡ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  91%|████████████████████████▍  | 907/1000 [13:20<01:14,  1.25it/s]

[907/1000]
EN: The Ministry of Health collaborated with states to improve sanitation and hygiene practices.
MT: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥ ꯁꯦꯅꯦꯇꯦꯁꯟ ꯑꯃꯁꯨꯡ ꯍꯥꯏꯖꯦꯟꯦꯛꯇꯤꯁ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯔꯥꯖꯁꯤꯡꯒ ꯄꯨꯟꯅ ꯊꯕꯛ ꯇꯧ
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 908/1000 [13:20<01:13,  1.26it/s]

[908/1000]
EN: Indian hospitals increased investment in critical care facilities.
MT: ꯚꯥꯔꯠꯀꯤ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯅꯥꯇꯤꯀꯦꯜ ꯀꯦꯌꯔ ꯐꯦꯁꯤꯂꯤꯇꯤꯗꯥ ꯏꯟꯚꯦꯁꯇꯃꯦꯟꯠ ꯍꯦꯟꯒꯠꯍꯟ
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 909/1000 [13:21<01:20,  1.13it/s]

[909/1000]
EN: A health awareness campaign encouraged working professionals to undergo regular health screenings.
MT: ꯍꯦꯜꯊ ꯑꯦꯚꯦꯌꯔꯅꯦꯁ ꯀꯦꯝꯄꯦꯅ ꯑꯃꯅ ꯊꯕꯛ ꯇꯧꯔꯤꯕꯐꯦꯁꯅꯦꯜꯁꯤꯡꯕꯨ ꯔꯦꯒꯨꯂꯔ ꯍꯦꯂꯊꯅꯤꯡ ꯇꯧꯅꯕ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 910/1000 [13:22<01:16,  1.17it/s]

[910/1000]
EN: The government introduced reforms to regulate private healthcare pricing.
MT: ꯁꯔꯀꯥꯔꯅꯥꯚꯥꯏꯇ ꯍꯦꯜꯊꯦꯌꯔꯥꯏꯁꯤꯡ ꯔꯦꯒꯨꯂꯦꯇ ꯇꯧꯅꯕꯒꯤꯗꯃꯛ ꯔꯤꯐꯣꯔꯝꯁꯤꯡ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 911/1000 [13:23<01:13,  1.20it/s]

[911/1000]
EN: India enhanced its disease reporting systems to improve outbreak preparedness.
MT: ꯚꯥꯔꯠꯅ ꯃꯁꯤꯒꯤ ꯗꯤꯖꯤꯖ ꯔꯤꯄꯣꯔꯇꯤꯡ ꯁꯤꯁꯇꯦꯝꯁꯤꯡ ꯑꯁꯤ ꯂꯥꯏꯆꯠ ꯊꯣꯛꯄꯒꯤ ꯁꯦꯝ-ꯁꯥꯕꯒꯤ ꯐꯤꯕꯝ ꯐꯒꯠꯍꯟꯅꯕ ꯍꯦꯟꯒꯠꯍꯟ
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 912/1000 [13:24<01:14,  1.19it/s]

[912/1000]
EN: Health experts recommended increased funding for mental health research in India.
MT: ꯍꯦꯜꯊ ꯑꯦꯛꯁꯄꯥꯔꯇꯁꯤꯡꯅ ꯚꯥꯔꯠꯇ ꯃꯦꯟꯇꯥꯜ ꯍꯦꯜꯊ ꯔꯤꯁꯔꯆꯀꯤꯗꯃꯛ ꯁꯦꯜ ꯊꯥꯗꯕ ꯍꯦꯟꯒꯠꯍꯟꯕꯥ ꯔꯤꯀꯃꯦꯟꯗ ꯇꯧ
--------------------------------------------------

Translating:  91%|████████████████████████▋  | 913/1000 [13:25<01:11,  1.23it/s]

[913/1000]
EN: The National Health Authority reviewed feedback to improve beneficiary services.
MT: ꯅꯦꯁꯅꯦꯜ ꯍꯦꯜꯊ ꯑꯣꯊꯣꯔꯤꯇꯤꯅꯥ ꯕꯦꯅꯤꯐꯤꯁꯔꯤ ꯁꯔꯕꯤꯁ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯐꯤꯗꯕꯦꯛ ꯔꯤꯚ ꯇꯧ
--------------------------------------------------

Translating:  91%|████████████████████████▋  | 914/1000 [13:26<01:12,  1.18it/s]

[914/1000]
EN: India strengthened disaster preparedness in hospitals for medical emergencies.
MT: ꯚꯥꯔꯠꯅ ꯃꯦꯗꯤꯀꯦꯜ ꯏꯃꯔꯖꯦꯟꯁꯤꯁꯤꯡꯒꯤꯗꯃꯛ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯗ ꯗꯤꯖꯥꯁꯇ ꯔꯦꯄꯔꯦꯗꯤꯑꯦꯁꯟꯁꯤꯡ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  92%|████████████████████████▋  | 915/1000 [13:26<01:06,  1.27it/s]

[915/1000]
EN: A state government launched a nutrition program for school children.
MT: ꯇ ꯒꯚꯔꯃꯦꯟꯇ ꯑꯃꯅꯜꯒꯤ ꯑꯉꯥꯡꯁꯤꯡꯒꯤꯗꯃꯛ ꯅꯦꯁꯟꯒꯔꯥꯝ ꯑꯃ ꯍꯧ
--------------------------------------------------

Translating:  92%|████████████████████████▋  | 916/1000 [13:27<01:10,  1.19it/s]

[916/1000]
EN: The Health Ministry emphasized community participation in strengthening public healthcare systems.
MT: ꯍꯦꯜꯊ ꯃꯟꯇꯅꯥ ꯃꯤꯌꯥꯝꯒꯤ ꯍꯦꯜꯊꯦꯌꯔ ꯁꯤꯁꯇꯦꯝꯁꯤꯡ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯕꯗꯥ ꯀꯝꯃꯅꯤꯇꯤ ꯁꯔꯨꯛ ꯌꯥꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 917/1000 [13:28<01:16,  1.08it/s]

[917/1000]
EN: The Union Budget 2026 increased the healthcare allocation to 1,06,530 crore rupees for the Ministry of Health and Family Welfare.
MT: ꯌꯨꯅꯤꯌꯟ ꯕꯖꯦꯇ ꯗꯥ ꯍꯛꯁꯦꯜ ꯑꯃꯁꯨꯡ ꯏꯃꯨꯡ-ꯃꯄꯨ ꯆꯥꯎꯈꯠꯍꯟꯅꯕ ꯃꯟꯇꯒꯤꯗꯃꯛ ꯍꯛꯊꯦꯡꯅꯅ ꯁꯦꯜ ꯊꯥꯗꯕ ꯑꯁꯤ ꯂꯨꯄꯥ ꯀꯔꯣꯔ 1,06,530 ꯗꯥ ꯍꯦꯟꯒꯠꯍꯟ
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 918/1000 [13:29<01:19,  1.04it/s]

[918/1000]
EN: Finance Minister Nirmala Sitharaman announced a 10 percent hike in the health budget compared to the previous fiscal year.
MT: ꯐꯥꯏꯅꯥꯟꯁ ꯃꯟꯇ ꯅꯤꯔꯃꯂꯥ ꯁꯤꯔꯇꯥꯃꯟꯅꯥ ꯍꯧꯈꯤꯕ ꯁꯦꯟꯐꯝꯒꯤ ꯆꯍꯤꯒꯥ ꯆꯥꯡꯗꯝꯅꯕꯗ ꯍꯦꯜꯊ ꯕꯖꯦꯠꯇꯥ ꯆꯥꯗ ꯍꯦꯟꯒꯠꯍꯟꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 919/1000 [13:30<01:18,  1.03it/s]

[919/1000]
EN: The Government of India launched the Biopharma SHAKTI initiative with an outlay of 10,000 crore rupees over five years.
MT: ꯚꯥꯔꯠ ꯁꯔꯀꯥꯔꯅꯥ ꯆꯍꯤ ꯃꯉꯥꯒꯤ ꯃꯅꯨꯡꯗ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯒꯤ ꯁꯦꯜ ꯊꯥꯗꯕꯒ ꯂꯣꯏꯅꯅꯥ ꯕꯤꯑꯣꯐꯥꯔꯃꯥ ꯁꯛꯇꯤ ꯏꯅꯤꯁꯤꯌꯦꯇꯤꯕ ꯍꯧ
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 920/1000 [13:32<01:21,  1.02s/it]

[920/1000]
EN: The Biopharma SHAKTI scheme aims to strengthen the domestic production of biologics and biosimilars in India.
MT: ꯕꯥꯏꯑꯣꯐꯥꯔꯃꯥ ꯁꯛꯇꯤꯀꯤꯝ ꯑꯁꯤꯅ ꯚꯥꯔꯠꯇꯥ ꯕꯣꯂꯣꯖꯤꯛꯁ ꯑꯃꯁꯨꯡ ꯕꯥꯏꯌꯣꯁꯤꯃꯤꯂꯔꯁꯤꯡꯒꯤ ꯗꯣꯃꯦꯁꯇꯤꯛꯗꯛꯁꯟ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯕꯥ ꯄꯥꯟꯗꯝ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 921/1000 [13:33<01:20,  1.02s/it]

[921/1000]
EN: The Ministry of Health will support states in establishing five new regional medical hubs through private-sector partnerships.
MT: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥꯥꯏꯕꯦꯠ-ꯁꯦꯛꯇꯔ ꯄꯔꯅꯥꯇꯔꯁꯤꯞꯀꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯑꯅꯧꯕ ꯔꯤꯖꯅꯦꯜ ꯃꯦꯗꯤꯀꯦꯜ ꯍꯕ ꯃꯉꯥ ꯂꯤꯡꯈꯠꯄꯗ ꯔꯥꯖꯁꯤꯡꯕꯨ ꯃꯇꯦꯡ ꯄꯥꯡꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 922/1000 [13:34<01:22,  1.05s/it]

[922/1000]
EN: These five regional medical hubs will combine medical services, educational facilities, and research centers under one roof.
MT: ꯃꯁꯤꯒꯤ ꯔꯤꯖꯅꯦꯜ ꯃꯦꯗꯤꯀꯦꯜ ꯍꯕ ꯃꯉꯥ ꯑꯁꯤꯅ ꯍꯤꯗꯥꯛ-ꯃꯊꯛꯀꯤ ꯁꯔꯕꯤꯁꯁꯤꯡ, ꯑꯦꯖꯨꯀꯦꯁꯟ ꯐꯦꯁꯤꯂꯤꯇꯤꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯔꯤꯁꯔꯆ ꯁꯦꯟꯇꯔꯁꯤꯡ ꯑꯁꯤ ꯌꯨꯝꯕꯤ ꯑꯃꯒꯤ ꯃꯈꯥꯗ ꯄꯨꯟꯁꯤꯜꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 923/1000 [13:35<01:24,  1.10s/it]

[923/1000]
EN: The Union Budget 2026 proposed the establishment of NIMHANS 2.0 in North India to address mental health needs.
MT: ꯌꯨꯅꯤꯌꯟ ꯕꯖꯦꯇ 2026ꯅꯥ ꯑꯋꯥꯡ ꯚꯥꯔꯠꯇ ꯅꯤꯝꯍꯥꯟꯁ ꯂꯤꯡꯈꯠꯄꯥ ꯑꯁꯤ ꯃꯦꯟꯇꯥꯜ ꯍꯦꯜꯊꯀꯤ ꯃꯊꯧ ꯇꯥꯕꯁꯤꯡ ꯊꯦꯡꯅꯅꯕ ꯋꯥꯐꯝ ꯊꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 924/1000 [13:36<01:24,  1.11s/it]

[924/1000]
EN: The Government plans to upgrade the National Mental Health Institutes in Ranchi and Tezpur into regional apex institutions.
MT: ꯁꯔꯀꯥꯔꯅꯥ ꯔꯥꯟꯆꯤ ꯑꯃꯁꯨꯡ ꯇꯦꯖꯄꯨꯔꯗꯥ ꯂꯩꯕ ꯅꯦꯁꯅꯦꯜ ꯃꯦꯟꯇꯦꯜ ꯍꯦꯜꯊ ꯏꯟꯁꯇꯤꯇꯇꯨꯁꯤꯡꯕꯨ ꯔꯤꯖꯅꯦꯜ ꯑꯦꯄꯤꯛ ꯏꯟꯁꯇꯤꯇ ꯭ ꯌꯨꯁꯟꯁꯤꯡ ꯑꯣꯏꯍꯟꯅꯕ ꯊꯧꯔꯥꯡ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 925/1000 [13:37<01:19,  1.06s/it]

[925/1000]
EN: The Ministry of Health allocated 3,477 crore rupees to the National AIDS and STD Control Programme.
MT: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥ ꯅꯦꯁꯅꯦꯜ ꯑꯦꯗꯁ ꯑꯃꯁꯨꯡ ꯑꯦꯁ.ꯇꯤ.ꯗꯤ. ꯀꯟꯇꯣꯜꯒꯔꯝꯗꯥ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯊꯥꯖꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  93%|█████████████████████████  | 926/1000 [13:38<01:19,  1.08s/it]

[926/1000]
EN: The Union Budget 2026 provided a full customs duty exemption on 17 essential cancer-related drugs.
MT: ꯌꯨꯅꯤꯌꯟ ꯕꯖꯦꯇ 2026ꯅꯥ ꯀꯦꯟꯁꯔꯒꯥ ꯃꯔꯤ ꯂꯩꯅꯕ ꯇꯉꯥꯏꯐꯗꯕ ꯗꯒ 17ꯗꯥ ꯃꯄꯨꯡꯐꯥꯅ ꯀꯁꯇꯝꯁ ꯗꯌꯨꯇꯤ ꯊꯥꯗꯣꯛꯄꯥ ꯑꯃ ꯄꯤ
--------------------------------------------------

Translating:  93%|█████████████████████████  | 927/1000 [13:39<01:17,  1.06s/it]

[927/1000]
EN: Seven additional rare diseases were added to the list for easier personal import of life-saving medicines.
MT: ꯂꯥꯏꯐ-ꯁꯦꯚꯤꯡ ꯃꯦꯗꯤꯁꯤꯟꯁꯤꯡ ꯂꯅꯥꯏꯗꯥ ꯄꯨꯁꯤꯜꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯂꯤꯁꯠ ꯑꯁꯤꯗ ꯑꯍꯦꯟꯕ ꯇꯥꯡꯕꯥ ꯂꯥꯏꯅꯥ 7 ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  93%|█████████████████████████  | 928/1000 [13:40<01:14,  1.04s/it]

[928/1000]
EN: The Government announced a 50 percent expansion in emergency and trauma care capacity at district hospitals.
MT: ꯁꯔꯀꯥꯔꯅꯥ ꯗꯤꯁꯇꯛꯇ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯗ ꯏꯃꯔꯖꯦꯟꯁꯤ ꯑꯃꯁꯨꯡ ꯇꯃꯥ ꯀꯦꯌꯔ ꯀꯦꯄꯦꯁꯤꯇꯤ ꯆꯥꯗ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  93%|█████████████████████████  | 929/1000 [13:41<01:17,  1.09s/it]

[929/1000]
EN: The Ministry of Health intends to establish dedicated emergency and trauma care centers in every district hospital.
MT: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥ ꯗꯤꯁꯇꯛꯇ ꯍꯣꯁꯄꯤꯇꯥꯜ ꯈꯨꯗꯤꯡꯃꯛꯇ ꯗꯦꯗꯤꯀꯦꯇꯦꯗ ꯏꯃꯔꯖꯦꯟꯁꯤ ꯑꯃꯁꯨꯡ ꯇꯃꯥ ꯀꯦꯌꯔ ꯁꯦꯟꯇꯔꯁꯤꯡ ꯂꯤꯡꯈꯠꯄꯥ ꯄꯥꯝꯃꯤ ꯫
--------------------------------------------------

Translating:  93%|█████████████████████████  | 930/1000 [13:43<01:19,  1.14s/it]

[930/1000]
EN: The Pradhan Mantri Jan Arogya Yojana received an increased allocation of 9,500 crore rupees to expand coverage.
MT: ꯙꯥꯟ ꯃꯟꯇ ꯖꯅ ꯑꯔꯣꯒ ꯌꯣꯖꯅꯥꯅꯥ ꯀꯚꯔꯦꯖ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯍꯦꯟꯒꯠꯄꯥ ꯑꯦꯂꯣꯀꯦꯁꯟ ꯑꯃ ꯐꯪ
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 931/1000 [13:44<01:16,  1.10s/it]

[931/1000]
EN: The National Health Mission was allocated 39,390 crore rupees to enhance primary healthcare delivery across states.
MT: ꯅꯦꯁꯅꯦꯜ ꯍꯦꯜꯊ ꯃꯤꯁꯟ ꯑꯁꯤ ꯔꯥꯖ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥꯥꯏꯃꯔꯤ ꯍꯦꯜꯊꯦꯌꯔ ꯗꯤꯂꯤꯚꯔꯤ ꯍꯦꯟꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯂꯨꯄꯥ ꯀꯔꯣꯔ 39,390 ꯄꯤ
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 932/1000 [13:44<01:07,  1.00it/s]

[932/1000]
EN: The Government proposed a plan to add 100,000 allied health professionals over the next five years.
MT: ꯁꯔꯀꯥꯔꯅꯥ ꯃꯊꯪꯒꯤ ꯆꯍꯤ ꯃꯉꯥꯒꯤ ꯃꯅꯨꯡꯗ ꯑꯦꯂꯥꯏꯗ ꯍꯦꯜꯊꯐꯦꯐꯦꯁꯅꯦꯜ 100,000 ꯍꯥꯞꯆꯤꯟꯅꯕ ꯊꯧꯔꯥꯡ ꯑꯃ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 933/1000 [13:45<01:08,  1.02s/it]

[933/1000]
EN: The Ministry of Health will upgrade existing institutions for allied health professionals to improve training standards.
MT: ꯍꯛꯁꯦꯜ ꯃꯟꯇꯅꯥ ꯍꯧꯖꯤꯛ ꯂꯩꯔꯤꯕ ꯏꯟꯁꯇꯤꯇꯁꯟꯁꯤꯡ ꯑꯁꯤ ꯑꯦꯂꯥꯏꯗ ꯍꯦꯜꯊꯐꯦꯁꯅꯦꯜꯁꯤꯡꯒꯤꯗꯃꯛꯅꯤꯡꯦꯟꯗꯗꯔꯁ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯑꯒꯗ ꯇꯧꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 934/1000 [13:46<01:02,  1.06it/s]

[934/1000]
EN: The Union Budget 2026 earmarked 4,821 crore rupees specifically for the Department of Health Research.
MT: ꯌꯨꯅꯤꯌꯟ ꯕꯖꯦꯇ 2026 ꯗꯥ ꯍꯛꯁꯦꯜ ꯔꯤꯁꯔꯆ ꯗꯤꯄꯥꯇꯃꯦꯟꯇꯒꯤꯗꯃꯛ ꯃꯔꯨꯑꯣꯏꯅ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯊꯝ
--------------------------------------------------

Translating:  94%|█████████████████████████▏ | 935/1000 [13:47<01:00,  1.07it/s]

[935/1000]
EN: Finance Minister Nirmala Sitharaman proposed the creation of three new All India Institutes of Ayurveda.
MT: ꯐꯥꯏꯅꯥꯟꯁ ꯃꯟꯇ ꯅꯤꯔꯃꯂꯥ ꯁꯤꯔꯇꯥꯃꯟꯅꯥ ꯑꯥꯌꯨꯔꯕꯦꯗꯥꯒꯤ ꯑꯅꯧꯕ ꯑꯣꯜ ꯏꯟꯗꯤꯌꯥ ꯏꯟꯁꯇꯤꯇꯇ ꯑꯍꯨꯝ ꯁꯦꯝꯕꯒꯤ ꯋꯥꯐꯝ ꯊꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 936/1000 [13:48<01:01,  1.05it/s]

[936/1000]
EN: The Government plans to train 1.5 lakh caregivers in allied skills such as geriatric care and yoga.
MT: ꯒꯕꯔꯃꯦꯟꯇꯅꯥ ꯖꯦꯔꯤꯌꯥꯇ ꯀꯦꯌꯔ ꯑꯃꯁꯨꯡ ꯌꯣꯒꯥꯒꯨꯝꯕ ꯑꯦꯂꯥꯏꯗꯀꯤꯜꯁꯤꯡꯗ ꯀꯦꯌꯥꯔꯒꯤꯚꯔ ꯂꯥꯈ ꯇꯅꯤꯡ ꯄꯤꯅꯕ ꯊꯧꯔꯥꯡ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 937/1000 [13:49<01:00,  1.04it/s]

[937/1000]
EN: The Ayushman Bharat Digital Mission received 350 crore rupees to improve digital health record interoperability.
MT: ꯗꯤꯖꯤꯇꯦꯜ ꯍꯦꯜꯊ ꯔꯦꯀꯣꯔ ꯏꯟꯇꯔꯑꯣꯄꯔꯦꯕꯤꯂꯤꯇꯤ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯑꯥꯌꯨꯁꯃꯟ ꯚꯥꯔꯠ ꯗꯤꯖꯇꯤꯇꯦꯜ ꯃꯤꯁꯟꯅꯥ ꯂꯨꯄꯥ ꯀꯔꯣꯔ 350 ꯐꯪ
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 938/1000 [13:50<01:04,  1.03s/it]

[938/1000]
EN: The Ministry of Health aims to reduce import dependence by supporting the domestic manufacturing of high-value biopharmaceuticals.
MT: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥ ꯍꯥꯏ-ꯚꯂꯨ ꯕꯌꯣ ꯐꯥꯔꯃꯥꯁꯤꯌꯨꯇꯤꯀꯦꯜꯁꯤꯡꯒꯤ ꯗꯣꯃꯦꯁꯇꯤꯛ ꯃꯦꯅꯛꯄꯨꯆꯔꯗ ꯃꯇꯦꯡ ꯄꯥꯡꯗꯨꯅ ꯏꯝꯄꯣꯔꯇ ꯗꯤꯄꯦꯟꯗꯦꯟꯁ ꯍꯟꯊꯍꯟꯅꯕ ꯄꯥꯟꯗꯝ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 939/1000 [13:51<01:03,  1.04s/it]

[939/1000]
EN: The Union Budget 2026 focus shifted from a curative model to a prevention-first and holistic wellness approach.
MT: ꯌꯨꯅꯤꯌꯟ ꯕꯖꯦꯇ 2026 ꯒꯤ ꯃꯤꯠꯌꯦꯡ ꯑꯁꯤ ꯀ ꯭ ꯌꯨꯔꯦꯇꯤꯕ ꯃꯣꯗꯦꯜ ꯑꯃꯗꯒꯤꯚꯤꯖꯟ-ꯐꯔꯁꯠ ꯑꯃꯁꯨꯡ ꯍꯣꯂꯤꯁꯇꯤꯛ ꯋꯦꯜꯅꯦꯁ ꯑꯦꯞꯔꯣꯆ ꯑꯃꯗ ꯍꯣꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 940/1000 [13:52<01:01,  1.03s/it]

[940/1000]
EN: The Government will establish 1,000 accredited clinical trial sites to position India as a global research destination.
MT: ꯒꯚꯔꯃꯦꯟꯇꯅꯥ ꯚꯥꯔꯠꯄꯨꯋꯦꯜ ꯔꯤꯁꯔꯆ ꯗꯦꯁꯇꯤꯅꯦꯁꯟ ꯑꯃ ꯑꯣꯏꯍꯟꯅꯕ ꯑꯦꯀꯗꯤꯇꯦꯗ ꯀꯂꯤꯅꯤꯀꯦꯜꯥꯏꯂ ꯁꯥꯏꯇ 1000 ꯂꯤꯡꯈꯠꯀꯅꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 941/1000 [13:54<01:04,  1.10s/it]

[941/1000]
EN: The Central Drugs Standard Control Organisation will receive more specialized personnel to improve regulatory efficiency.
MT: ꯁꯦꯟꯇꯜ ꯗꯒꯁꯦꯟꯗꯗꯔꯗ ꯀꯟꯇꯣꯜ ꯑꯣꯔꯒꯥꯅꯥꯏꯖꯦꯁꯟꯅꯥ ꯔꯦꯒꯨꯂꯦꯇꯔꯤ ꯑꯦꯐꯤꯁꯤꯑꯦꯟꯁꯤ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯍꯦꯟꯅ ꯁꯄꯁꯤꯌꯦꯂꯤꯁꯇ ꯄꯔꯁꯣꯅꯦꯜ ꯐꯪꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 942/1000 [13:55<01:04,  1.11s/it]

[942/1000]
EN: Artificial Intelligence is now being used by Indian radiologists to detect early signs of lung cancer from medical images.
MT: ꯑꯔꯇꯤꯐꯤꯁꯦꯜ ꯏꯟꯇꯤꯂꯤꯖꯦꯟꯁ ꯑꯁꯤ ꯍꯧꯖꯤꯛ ꯚꯥꯔꯠꯀꯤ ꯔꯦꯗꯤꯑꯣꯂꯣꯖꯤꯁꯇꯁꯤꯡꯅꯥ ꯃꯦꯗꯤꯀꯦꯜ ꯏꯃꯤꯖꯁꯤꯡꯗꯒꯤ ꯂꯡꯒ ꯀꯦꯟꯁꯔꯒꯤ ꯑꯍꯥꯟꯕꯥ ꯈꯨꯗꯝꯁꯤꯡ ꯈꯪꯗꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯁꯤꯖꯤꯟꯅꯔꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 943/1000 [13:56<01:06,  1.17s/it]

[943/1000]
EN: Qure.ai implemented AI-driven imaging solutions to facilitate faster diagnosis of strokes in rural Indian hospitals.
MT: ꯀ ꯭ ꯌꯨꯔꯦ.ꯑꯦꯏꯅꯥ ꯈꯨꯡꯒꯪꯒꯤ ꯚꯥꯔꯠꯀꯤ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯗꯣꯛꯁꯤꯡ ꯊꯨꯅ ꯂꯥꯏꯑꯣꯡ ꯈꯪꯗꯣꯛꯅꯕꯒꯤ ꯈꯨꯗꯣꯡꯆꯥꯕꯥ ꯄꯤꯅꯕ ꯑꯦꯑꯏ-ꯗꯚꯟ ꯏꯃꯦꯖꯤꯡ ꯁꯣꯂꯨꯁꯟꯁꯤꯡ ꯆꯠꯅꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 944/1000 [13:57<01:04,  1.16s/it]

[944/1000]
EN: Indian healthcare providers are adopting "Actionable AI" to provide predictive health roadmaps instead of simple lab reports.
MT: ꯚꯥꯔꯠꯀꯤ ꯍꯦꯜꯊꯦꯌꯔꯚꯥꯏꯗꯔꯁꯤꯡꯅ ꯁꯤꯝꯄꯦꯜ ꯂꯦꯕ ꯔꯤꯄꯣꯔꯠꯁꯤꯡꯒꯤ ꯃꯍꯨꯠꯇꯗꯤꯇꯤꯕ ꯍꯦꯜꯊ ꯔꯣꯗꯃꯦꯄꯁꯤꯡ ꯄꯤꯅꯕ "ꯑꯦꯛꯁꯟꯑꯦꯕꯜ ꯑꯦꯑꯏ ꯂꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▌ | 945/1000 [13:58<01:02,  1.14s/it]

[945/1000]
EN: The use of wearables in India is evolving from basic fitness tracking to clinical-grade monitoring of heart rhythm.
MT: ꯚꯥꯔꯠꯇꯥ ꯌꯦꯔꯦꯑꯦꯕꯜꯁꯤꯡ ꯁꯤꯖꯤꯟꯅꯕꯁꯤ ꯕꯦꯁꯤꯛ ꯐꯤꯇꯅꯤꯁ ꯇꯀꯤꯡꯗꯒꯤ ꯍꯔꯇ ꯔꯤꯊꯝꯒꯤ ꯀꯂꯤꯅꯤꯀꯦꯜ-ꯒꯗ ꯃꯣꯅꯤꯇꯦꯔꯤꯡ ꯐꯥꯎꯕ ꯆꯥꯎꯈꯠꯂꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 946/1000 [14:00<01:04,  1.20s/it]

[946/1000]
EN: Medical technology startups in India are developing microfluidic devices that conduct complex tests on a single drop of blood.
MT: ꯚꯥꯔꯠꯇꯥ ꯃꯦꯗꯤꯀꯦꯜ ꯇꯦꯛꯅꯣꯂꯣꯖꯤ ꯁꯇꯥꯔꯇꯑꯞꯁꯤꯡ ꯑꯁꯤꯅ ꯃꯥꯏꯀꯐꯂꯨꯏꯗꯤꯛ ꯗꯤꯚꯥꯏꯁꯁꯤꯡ ꯁꯦꯝꯒꯠꯂꯤ ꯃꯗꯨꯗ ꯏꯒꯤ ꯁꯤꯡꯒꯜ ꯗꯄ ꯑꯃꯗ ꯀꯝꯄꯂ ꯭ ꯁ ꯇꯦꯁꯇꯁꯤꯡ ꯄꯥꯡꯊꯣꯛꯏ ꯫
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 947/1000 [14:01<00:59,  1.12s/it]

[947/1000]
EN: The Indian MedTech sector is projected to reach a market value of 50 billion dollars by the end of 2026.
MT: ꯚꯥꯔꯠꯀꯤ ꯃꯦꯗꯇꯦꯛ ꯁꯦꯛꯇꯔ ꯑꯁꯤ ꯏꯪꯁꯣꯛ ꯂꯣꯏꯔꯛꯄꯗꯥ ꯗꯣꯂꯔ ꯕꯤꯂꯤꯌꯟꯒꯤ ꯃꯥꯔꯀꯦꯠ ꯚꯦꯜꯌꯨ ꯌꯧꯔꯛꯀꯅꯤ ꯍꯥꯏꯅ ꯄꯥꯅꯔꯤ ꯫
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 948/1000 [14:02<00:57,  1.10s/it]

[948/1000]
EN: Hospitals in Tier 2 cities are using predictive analytics to optimize patient flow and reduce waiting times.
MT: ꯇꯤꯌꯔ ꯁꯍꯔꯁꯤꯡꯒꯤ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡ ꯑꯁꯤꯅ ꯑꯅꯥꯕꯁꯤꯡꯒꯤ ꯏꯊꯣꯛꯑꯁꯥ ꯍꯦꯟꯒꯠꯍꯟꯅꯕ ꯑꯃꯁꯨꯡ ꯉꯥꯏꯕꯒꯤ ꯃꯇꯝ ꯍꯟꯊꯍꯟꯅꯕꯗꯤꯇꯤꯕ ꯑꯦꯅꯥꯂꯤꯇꯤꯛꯁ ꯁꯤꯖꯤꯟꯅ
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 949/1000 [14:03<00:55,  1.09s/it]

[949/1000]
EN: Telemedicine services are expanding in remote regions to connect rural patients with specialists in metropolitan cities.
MT: ꯇꯦꯂꯤꯃꯦꯗꯤꯁꯤꯟ ꯁꯔꯕꯤꯁꯁꯤꯡ ꯑꯁꯤ ꯃꯦꯇꯄꯣꯂꯤꯇꯥꯟ ꯁꯤꯇꯤꯁꯤꯡꯒꯤ ꯁꯄꯁꯤꯑꯦꯂꯤꯁꯇꯁꯤꯡꯒ ꯈꯨꯡꯒꯪꯒꯤ ꯑꯅꯥꯕꯁꯤꯡ ꯁꯝꯅꯕ ꯂꯥꯞꯊꯣꯛꯂꯕ ꯂꯝꯗꯝꯁꯤꯡꯗ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 950/1000 [14:04<00:56,  1.13s/it]

[950/1000]
EN: The Ayushman Bharat Health Account (ABHA) system allows patients to share digital health records securely with doctors.
MT: ꯑꯥꯌꯨꯁꯃꯟ ꯚꯥꯔꯠ ꯍꯦꯜꯊ ꯑꯦꯀꯥꯎꯟꯇ (ꯑꯦꯕꯤꯑꯍꯑꯦ ) ꯁꯤꯁꯇꯦꯝ ꯑꯁꯤꯅ ꯑꯅꯥꯕꯥꯁꯤꯡꯕꯨ ꯗꯤꯖꯤꯇꯦꯜ ꯍꯦꯜꯊ ꯔꯦꯀꯣꯔꯗꯁꯤꯡ ꯗꯣꯛꯇꯔꯁꯤꯡꯒ ꯁꯣꯏꯗꯅ ꯁꯦꯌꯔ ꯇꯧꯕ ꯌꯥꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 951/1000 [14:05<00:56,  1.14s/it]

[951/1000]
EN: Robotic-assisted surgery is becoming more common in private Indian hospitals for complex urological procedures.
MT: ꯀꯝꯄꯂꯦꯛꯁ ꯌꯨꯔꯣꯂꯣꯖꯤꯀꯦꯜꯁꯤꯖꯨꯑꯣꯔꯁꯤꯡꯒꯤꯗꯃꯛꯇꯥꯏꯚꯦꯠ ꯏꯟꯗꯤꯌꯟ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯗ ꯔꯣꯕꯣꯇꯤꯛ-ꯑꯦꯁꯦꯁꯇꯦꯗ ꯁꯔꯖꯔꯤ ꯑꯁꯤ ꯍꯦꯟꯅ ꯇꯣꯏꯅ ꯊꯣꯛꯂꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 952/1000 [14:06<00:52,  1.10s/it]

[952/1000]
EN: Many Indian diagnostic labs are now using genomic testing as a primary triage tool for chronic diseases.
MT: ꯚꯥꯔꯠꯀꯤ ꯗꯥꯏꯒꯅꯣꯁꯇꯤꯛ ꯂꯦꯕ ꯀꯌꯥꯅꯥ ꯍꯧꯖꯤꯛ ꯖꯤꯅꯣꯃꯤꯛ ꯇꯦꯁꯇꯤꯡ ꯑꯁꯤꯅꯤꯛ ꯗꯤꯖꯤꯖꯁꯤꯡꯒꯤꯥꯏꯔꯤꯌꯦꯖ ꯇꯨꯜ ꯑꯃꯥ ꯑꯣꯏꯅ ꯁꯤꯖꯤꯟꯅ
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 953/1000 [14:07<00:54,  1.16s/it]

[953/1000]
EN: Healthcare organizations are deploying AI agents to handle administrative tasks like insurance pre-authorizations and billing.
MT: ꯍꯦꯜꯊꯦꯌꯔ ꯑꯣꯔꯒꯥꯅꯥꯏꯖꯦꯁꯟꯁꯤꯡꯅ ꯏꯟꯁꯨꯔꯦꯟꯁ-ꯑꯣꯊꯔꯤꯖꯦꯁꯟ ꯑꯃꯁꯨꯡ ꯕꯤꯂꯤꯡꯒꯨꯝꯕ ꯑꯦꯗꯃꯤꯅꯤꯁꯇꯇꯤꯕ ꯇꯁꯀꯁꯤꯡ ꯁꯤꯟꯗꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯑꯦꯑꯏ ꯑꯦꯖꯦꯟꯇꯁꯤꯡ ꯗꯤꯄꯂꯥꯏ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  95%|█████████████████████████▊ | 954/1000 [14:08<00:52,  1.15s/it]

[954/1000]
EN: Smart sensors in Indian ICUs are reducing unplanned admissions by providing continuous real-time monitoring of vitals.
MT: ꯚꯥꯔꯠꯀꯤ ꯑꯥꯏ ꯁꯤ ꯌꯨꯁꯤꯡꯗ ꯂꯩꯕꯃꯔꯇ ꯁꯦꯟꯁꯔꯁꯤꯡꯅ ꯚꯤꯇꯥꯜꯁꯤꯡꯒꯤ ꯃꯈꯥ ꯇꯥꯅ ꯔꯤꯌꯦꯜ-ꯇꯥꯏꯃ ꯃꯣꯅꯤꯇꯦꯔꯤꯡ ꯄꯤꯗꯨꯅ ꯑꯟꯄꯂꯥꯟꯗ ꯑꯦꯗꯃꯤꯁꯟꯁꯤꯡ ꯍꯟꯊꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 955/1000 [14:10<00:50,  1.12s/it]

[955/1000]
EN: The digital transformation of clinical trials in India is enabling remote patient monitoring through mobile devices.
MT: ꯚꯥꯔꯠꯇ ꯀꯂꯤꯅꯤꯀꯦꯜꯌꯦꯜꯁꯤꯡꯒꯤ ꯗꯤꯖꯤꯇꯦꯜ ꯇ ꯭ ꯔꯥꯟꯁꯐꯣꯔꯃꯦꯁꯟ ꯑꯁꯤꯅ ꯃꯣꯕꯥꯏꯜ ꯗꯤꯚꯥꯏꯁꯁꯤꯡꯒꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯔꯤꯃꯣꯠ ꯄꯦꯁꯤꯗꯦꯟꯇ ꯃꯣꯅꯤꯇꯦꯔꯤꯡ ꯇꯧꯕ ꯉꯝꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 956/1000 [14:11<00:51,  1.17s/it]

[956/1000]
EN: Indian pharmaceutical companies are integrating AI into their quality control systems to ensure paperless and compliant workflows.
MT: ꯚꯥꯔꯠꯀꯤ ꯐꯥꯔꯃꯥꯁꯤꯌꯨꯇꯤꯀꯦꯜ ꯀꯝꯄꯅꯤꯁꯤꯡꯅ ꯑꯦꯑꯏꯕꯨ ꯃꯈꯣꯏꯒꯤ ꯀꯋꯥꯂꯤꯇꯤ ꯀꯟꯇꯣꯜ ꯁꯤꯁꯇꯦꯝꯁꯤꯡꯗ ꯄꯦꯄꯔ ꯂꯦꯁ ꯑꯃꯁꯨꯡ ꯀꯝꯄꯂꯥꯏꯟꯇ ꯋꯥꯔꯛꯐꯂꯣꯁꯤꯡ ꯁꯣꯏꯗꯅ ꯐꯪꯍꯟꯅꯕ ꯏꯟꯇꯤꯒꯦꯠ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 957/1000 [14:12<00:50,  1.18s/it]

[957/1000]
EN: Low-cost needle-free drug delivery technologies are gaining traction for vaccine administration in pediatric clinics.
MT: ꯄꯦꯗꯤꯌꯦꯇ ꯀꯂꯤꯅꯤꯛꯁꯤꯡꯗ ꯕꯦꯛꯁꯤꯟ ꯑꯦꯗꯃꯤꯅꯤꯁꯇꯦꯁꯟꯒꯤꯗꯃꯛ ꯃꯃꯜ ꯌꯥꯝꯗꯕ ꯅꯤꯂꯤ-ꯐ ꯗꯒ ꯗꯤꯂꯤꯚꯔꯤ ꯇꯦꯛꯅꯣꯂꯣꯖꯤꯁꯤꯡꯅ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯟꯅꯤꯡꯉꯥꯏ ꯑꯣꯏꯔꯦ ꯫
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 958/1000 [14:13<00:50,  1.20s/it]

[958/1000]
EN: Public health experts launched India's first Public Health Monitor to track real-time health outcomes across states.
MT: ꯄꯍꯦꯜꯊ ꯑꯦꯛꯁꯄꯥꯔꯇꯁꯤꯡꯅ ꯔꯥꯖ ꯈꯨꯗꯤꯡꯗꯥ ꯔꯤꯌꯦꯜ-ꯇꯥꯏꯃ ꯍꯦꯜꯊ ꯑꯣꯛꯇꯀꯝꯁꯤꯡ ꯇꯦꯛ ꯇꯧꯅꯕ ꯚꯥꯔꯠꯀꯤ ꯑꯍꯥꯟꯕꯥ ꯄꯕꯂꯍꯦꯂꯊ ꯃꯣꯅꯤꯇꯔ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 959/1000 [14:14<00:47,  1.16s/it]

[959/1000]
EN: Specialized medical tourism facilitation centers will be integrated into the new regional medical hubs.
MT: ꯑꯍꯥꯟꯕꯥ ꯔꯤꯖꯅꯦꯜ ꯃꯦꯗꯤꯀꯦꯜ ꯍꯕꯁꯤꯡ ꯑꯁꯤꯗꯁꯤꯑꯦꯂꯥꯏꯖ ꯇꯧꯔꯕꯥ ꯃꯦꯗꯗꯤꯀꯦꯜ ꯇꯨꯔꯤꯖꯝ ꯐꯦꯁꯤꯂꯤꯇꯦꯁꯟ ꯁꯦꯟꯇꯔꯁꯤꯡ ꯏꯟꯇꯤꯒꯦꯠ ꯇꯧꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 960/1000 [14:15<00:43,  1.10s/it]

[960/1000]
EN: Indian doctors are using hyper-personalized medicine to tailor treatments based on the genetic profile of individual patients.
MT: ꯚꯥꯔꯠꯀꯤ ꯗꯣꯛꯇꯔꯁꯤꯡꯅ ꯑꯅꯥꯕꯁꯤꯡꯒꯤ ꯖꯤꯅꯦꯇꯤꯛꯐꯥꯏꯜꯗ ꯌꯨꯝꯐꯝ ꯑꯣꯏꯔꯒ ꯂꯥꯏꯌꯦꯡꯁꯤꯡ ꯁꯦꯝꯅꯕ ꯍꯥꯏꯄꯔ-ꯄꯔꯁꯅꯥꯂꯥꯏꯖ ꯃꯦꯗꯤꯁꯤꯟ ꯁꯤꯖꯤꯟꯅ
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 961/1000 [14:16<00:39,  1.02s/it]

[961/1000]
EN: The adoption of 5G technology is improving the speed and reliability of remote robotic surgeries in India.
MT: 5G ꯇꯦꯛꯅꯣꯂꯣꯖꯤ ꯁꯤꯖꯤꯟꯅꯕꯅꯥ ꯚꯥꯔꯠꯇ ꯔꯤꯃꯣꯠ ꯔꯣꯕꯣꯇꯤꯛ ꯁꯔꯖꯔꯤꯁꯤꯡꯒꯤꯗ ꯑꯃꯁꯨꯡ ꯔꯦꯂꯤꯑꯦꯕꯂꯤꯇꯤ ꯐꯒꯠꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 962/1000 [14:17<00:39,  1.04s/it]

[962/1000]
EN: 20 All India Institutes of Medical Sciences signed a memorandum to form a pan-India research consortium.
MT: ꯑꯣꯜ ꯏꯟꯗꯤꯌꯥ ꯏꯟꯁꯇꯤꯇ ꯭ ꯌꯨꯇ ꯑꯣꯐ ꯃꯦꯗꯤꯀꯦꯜ ꯁꯥꯏꯟꯁꯦꯁ 20ꯅꯥ ꯄꯥꯟ- ꯏꯟꯗꯤꯌꯥ ꯔꯤꯁꯔꯆ ꯀꯟꯁꯣꯔꯇꯤꯌꯝ ꯑꯃ ꯁꯦꯝꯅꯕꯒꯤꯗꯃꯛ ꯃꯦꯃꯣꯔꯦꯟꯗꯝ ꯑꯃꯗ ꯈꯨꯠꯌꯦꯛ ꯄꯤꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  96%|██████████████████████████ | 963/1000 [14:18<00:38,  1.05s/it]

[963/1000]
EN: The AIIMS research consortium will focus on multicentric clinical trials for low-cost cancer treatments.
MT: ꯑꯦꯑꯥꯏꯑꯏꯑꯦꯝꯁ ꯔꯤꯁꯔꯆ ꯀꯟꯁꯣꯔꯇꯤꯌꯝꯅꯥ ꯃꯃꯜ ꯌꯥꯝꯗꯕ ꯀꯦꯟꯁꯔ ꯂꯥꯏꯌꯦꯡꯒꯤꯗꯃꯛ ꯃꯜꯇꯤꯁꯦꯟꯇ ꯀꯂꯤꯅꯤꯀꯦꯜ ꯇꯌꯦꯜꯁꯤꯡꯗ ꯃꯤꯠꯌꯦꯡ ꯊꯝꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  96%|██████████████████████████ | 964/1000 [14:19<00:37,  1.04s/it]

[964/1000]
EN: A medical student at the Dharwad Institute of Mental Health unfortunately committed suicide in early February.
MT: ꯙꯔꯋꯥꯗ ꯏꯟꯁꯇꯤꯇꯇ ꯑꯣꯐ ꯃꯦꯟꯇꯥꯜ ꯍꯦꯜꯊꯀꯤ ꯃꯦꯗꯤꯀꯦꯜꯒꯤ ꯃꯍꯩꯔꯣꯏ ꯑꯃꯅ ꯂꯥꯏꯔꯕꯅꯥ ꯐꯦꯕꯋꯥꯔꯤꯒꯤ ꯑꯉꯟꯕꯗꯥ ꯃꯁꯥ ꯃꯊꯟꯇ ꯍꯥꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  96%|██████████████████████████ | 965/1000 [14:20<00:35,  1.03s/it]

[965/1000]
EN: The Maharashtra University of Health Sciences revoked the affiliation of Sinhgad Dental College over regulatory violations.
MT: ꯃꯍꯥꯔꯥꯁꯇ ꯌꯨꯅꯤꯚꯔꯁꯤꯇꯤ ꯑꯣꯐ ꯍꯦꯜꯊ ꯁꯥꯏꯟꯁꯦꯁꯅ ꯁꯤꯟꯍꯒꯗ ꯗꯦꯟꯇꯦꯜ ꯀꯣꯂꯦꯖꯒꯤ ꯑꯦꯐꯤꯂꯤꯑꯦꯁꯟ ꯑꯗꯨ ꯔꯦꯒꯨꯂꯦꯇꯔꯤ ꯋꯥꯂꯥꯏꯟꯁꯤꯡꯒꯤ ꯃꯔꯝꯗꯥ ꯂꯧꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████ | 966/1000 [14:21<00:34,  1.02s/it]

[966/1000]
EN: A 40-year-old urologist suffered a cardiac arrest while speaking at an international conference in Indore.
MT: ꯏꯟꯗꯣꯔꯗ ꯄꯥꯡꯊꯣꯛꯂꯤꯕꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯀꯟꯐꯔꯦꯟꯁ ꯑꯃꯗ ꯋꯥ ꯍꯥꯏꯔꯤꯕꯥ ꯃꯇꯝꯗ ꯆꯍꯤ 40 ꯁꯨꯔꯕꯥ ꯌꯨꯔꯣꯂꯣꯖꯤꯁꯇ ꯑꯃꯥꯅ ꯀꯥꯔꯗꯤꯑꯦꯛ ꯑꯦꯔꯦꯁꯇ ꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████ | 967/1000 [14:22<00:33,  1.02s/it]

[967/1000]
EN: The District Consumer Commission in Kannur held a surgeon liable for negligence in a varicose vein treatment.
MT: ꯀꯟꯅꯨꯔꯗꯥ ꯂꯩꯕ ꯗꯤꯁꯇꯛꯇ ꯀꯟꯖꯨꯃꯔ ꯀꯃꯤꯁꯟꯅꯥ ꯚꯦꯔꯤꯀꯣꯖ ꯚꯤꯅ ꯇꯇꯤꯃꯦꯟꯇ ꯑꯃꯗ ꯆꯦꯛꯁꯤꯟꯗꯕꯒꯤꯗꯃꯛ ꯁꯔꯖꯟ ꯑꯃꯥ ꯂꯧ
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 968/1000 [14:23<00:33,  1.05s/it]

[968/1000]
EN: Two government doctors in Bhopal were sentenced to prison for securing medical seats with fake domicile certificates.
MT: ꯚꯣꯄꯥꯜꯗꯥ ꯂꯩꯕ ꯒꯚꯔꯃꯦꯟꯇ ꯗꯣꯛꯇꯔ ꯑꯅꯤꯕꯨ ꯑꯔꯥꯟꯕ ꯗꯣꯃꯤꯁꯥꯏꯂ ꯁꯔꯇꯤꯐꯤꯀꯦꯠꯁꯤꯡꯒ ꯂꯣꯏꯅꯅ ꯃꯦꯗꯤꯀꯦꯜ ꯁꯤꯇꯁꯤꯡ ꯐꯪꯍꯟꯕꯒꯤꯗꯃꯛ ꯖꯦꯜꯗ ꯊꯝ
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 969/1000 [14:24<00:32,  1.06s/it]

[969/1000]
EN: Authorities in Maharashtra are seeking action against a pathologist for signing lab reports without proper registration.
MT: ꯃꯍꯥꯔꯥꯁꯇꯗꯥ ꯂꯩꯕ ꯑꯣꯊꯣꯔꯤꯇꯤꯁꯤꯡꯅ ꯃꯇꯤꯛ ꯆꯥꯕ ꯔꯦꯖꯤꯁꯇꯦꯁꯟ ꯌꯥꯎꯗꯅ ꯂꯦꯕ ꯔꯤꯄꯣꯔꯇꯁꯤꯡ ꯈꯨꯠꯌꯦꯛ ꯄꯤꯁꯤꯟꯕꯒꯤꯗꯃꯛ ꯄꯦꯊꯣꯂꯣꯖꯤꯁꯇ ꯑꯃꯒꯤ ꯃꯥꯌꯣꯛꯇ ꯑꯦꯛꯁꯟ ꯊꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 970/1000 [14:26<00:34,  1.15s/it]

[970/1000]
EN: The Central Council for Research in Ayurvedic Sciences signed an agreement to digitize rare Ayurveda manuscripts.
MT: ꯁꯦꯟꯇꯜ ꯀꯥꯎꯟꯁꯜ ꯐꯣꯔ ꯔꯤꯁꯔꯆ ꯏꯟ ꯑꯥꯌꯨꯔꯕꯦꯗꯤꯛ ꯁꯥꯏꯟꯁꯦꯁꯅ ꯇꯥꯡꯅꯥ ꯐꯪꯕ ꯑꯥꯌꯔꯕꯦꯗ ꯃꯅꯀꯄꯨꯇꯁꯤꯡ ꯗꯤꯖꯤꯇꯤꯂꯥꯏꯖ ꯇꯧꯅꯕ ꯑꯦꯒꯃꯦꯟꯇ ꯑꯃ ꯈꯨꯠꯌꯦꯛ ꯄꯤꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 971/1000 [14:27<00:33,  1.15s/it]

[971/1000]
EN: Apollo Hospitals Chairman Dr. Prathap Reddy stated that the 2026 budget strengthens the vision of a healthier India.
MT: ꯑꯦꯄꯣꯂꯣ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯀꯤ ꯆꯦꯌꯔꯃꯦꯟ ꯗꯥ.ꯊꯥꯄ ꯔꯦꯗꯤꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯏꯪ 2026 ꯒꯤ ꯕꯖꯦꯠ ꯑꯁꯤꯅ ꯍꯛꯊꯦꯡꯅꯅ ꯍꯤꯡꯕꯥ ꯚꯥꯔꯠꯀꯤ ꯋꯥꯈꯜꯂꯣꯟ ꯑꯗꯨ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 972/1000 [14:28<00:32,  1.15s/it]

[972/1000]
EN: Max Healthcare plans to expand its robotic-assisted surgery program across its network of hospitals.
MT: ꯃꯦꯛꯁ ꯍꯦꯜꯊꯦꯌꯔꯅꯥ ꯃꯈꯣꯏꯒꯤ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯒꯤ ꯅꯦꯠꯋꯥꯔꯛ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯃꯁꯤꯒꯤ ꯔꯣꯕꯣꯇꯤꯛ-ꯑꯦꯁꯦꯁꯇꯦꯗ ꯁꯔꯖꯔꯤꯒꯔꯥꯝ ꯑꯗꯨ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯅꯕ ꯊꯧꯔꯥꯡ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████▎| 973/1000 [14:29<00:32,  1.20s/it]

[973/1000]
EN: Health experts warned that the unorganized diagnostic sector in India will face consolidation due to stricter quality norms.
MT: ꯍꯛꯁꯦꯜꯒꯤ ꯑꯦꯛꯁꯄꯥꯔꯇꯁꯤꯡꯅꯥ ꯆꯦꯛꯁꯤꯟꯋꯥ ꯄꯤꯔꯝꯃꯤ ꯃꯗꯨꯗꯤ ꯀꯋꯥꯂꯤꯇꯤ ꯅꯤꯌꯝꯁꯤꯡ ꯀꯟꯅꯕꯒꯤ ꯃꯔꯝꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯑꯟꯑꯣꯔꯒꯅꯥꯏꯖꯗ ꯗꯥꯏꯒꯅꯣꯁꯇꯤꯛ ꯁꯦꯛꯇꯔ ꯑꯁꯤ ꯀꯣꯟꯁꯣꯂꯤꯗꯤꯌꯦꯁꯟ ꯇꯧꯔꯛꯀꯅꯤ ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████▎| 974/1000 [14:30<00:29,  1.14s/it]

[974/1000]
EN: The Indian Council of Medical Research received 4,000 crore rupees to bolster indigenous medical research.
MT: ꯏꯟꯗꯤꯌꯟ ꯀꯥꯎꯟꯁꯤꯜ ꯑꯣꯐ ꯃꯦꯗꯤꯀꯦꯜ ꯔꯤꯁꯔꯆꯅꯥ ꯏꯗꯤꯖꯦꯟꯁꯤ ꯃꯦꯗꯗꯤꯀꯦꯜ ꯔꯤꯁꯔꯆꯄꯨ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯅꯕ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯐꯪ
--------------------------------------------------

Translating:  98%|██████████████████████████▎| 975/1000 [14:32<00:28,  1.13s/it]

[975/1000]
EN: Public health officials are drafting a new Planetary Health Policy Framework to address climate-linked diseases.
MT: ꯍꯦꯜꯊ ꯑꯣꯐꯤꯁꯌꯦꯜꯁꯤꯡꯅ ꯀꯂꯥꯏꯃꯦꯠ-ꯂꯤꯀꯗ ꯗꯤꯖꯤꯖꯁꯤꯡ ꯀꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯑꯅꯧꯕꯅꯦꯇꯔꯤ ꯍꯦꯜꯊ ꯄꯣꯂꯤꯁꯤ ꯐꯃꯋꯥꯔꯀ ꯑꯃ ꯁꯦꯝꯗꯣꯛ
--------------------------------------------------

Translating:  98%|██████████████████████████▎| 976/1000 [14:33<00:26,  1.11s/it]

[976/1000]
EN: The Food Safety and Standards Authority of India is working to make healthy food more affordable than unhealthy options.
MT: ꯐꯨꯗ ꯁꯦꯐꯇꯤ ꯑꯦꯟꯗꯔꯗꯁ ꯑꯣꯊꯣꯔꯤꯇꯤ ꯑꯣꯐ ꯏꯟꯗꯤꯌꯥꯅꯥ ꯍꯛꯆꯥꯡ ꯐꯔꯕ ꯆꯤꯟꯖꯥꯛꯁꯤꯡ ꯑꯁꯤ ꯑꯅꯥꯕꯥ ꯂꯩꯕꯒꯤ ꯑꯣꯞꯁꯟꯁꯤꯡꯗꯒꯤ ꯍꯦꯟꯅ ꯃꯃꯜ ꯌꯥꯝꯕꯥ ꯑꯣꯏꯍꯟꯅꯕ ꯊꯕꯛ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 977/1000 [14:34<00:25,  1.09s/it]

[977/1000]
EN: Researchers at AIIMS Delhi are investigating the use of AI to reduce hospital-acquired infections.
MT: ꯑꯦꯑꯥꯏꯑꯦꯝꯁ ꯗꯤꯜꯂꯤꯒꯤ ꯊꯤꯖꯟ ꯍꯨꯝꯖꯟꯕꯁꯤꯡꯅ ꯍꯣꯁꯄꯤꯇꯥꯜꯅ ꯐꯪꯕꯥ ꯏꯟꯐꯦꯛꯁꯟꯁꯤꯡ ꯍꯟꯊꯍꯟꯅꯕ ꯑꯦꯑꯦ ꯁꯤꯖꯤꯟꯅꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯊꯤꯖꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 978/1000 [14:35<00:24,  1.10s/it]

[978/1000]
EN: The National AIDS Control Organisation is upgrading blood transfusion services to ensure nationwide safety and availability.
MT: ꯅꯦꯁꯅꯦꯜ ꯑꯦꯗꯁ ꯀꯟꯇꯣꯜ ꯑꯣꯔꯒꯥꯅꯥꯏꯖꯦꯁꯟꯅꯥ ꯂꯩꯕꯥꯛ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯁꯦꯐꯇꯤ ꯑꯃꯁꯨꯡ ꯐꯪꯍꯟꯕꯥ ꯉꯝꯅꯕ ꯕꯗ ꯇꯥꯟꯁꯐꯨꯖꯟ ꯁꯔꯕꯤꯁ ꯑꯞꯒꯦꯠ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 979/1000 [14:36<00:23,  1.11s/it]

[979/1000]
EN: Indian pediatricians noted a rise in parental awareness regarding neurodivergence and behavioral health issues.
MT: ꯚꯥꯔꯠꯀꯤ ꯄꯦꯗꯤꯌꯦꯁꯤꯌꯟꯁꯤꯡꯅ ꯅꯣꯗꯥꯏꯚꯔꯖꯦꯟꯁ ꯑꯃꯁꯨꯡ ꯕꯤꯚꯦꯌꯨꯔꯦꯜ ꯍꯦꯜꯊ ꯏꯁꯨꯖꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯃꯄꯥ-ꯃꯅꯥꯏꯒꯤ ꯑꯦꯚꯦꯌꯔ ꯍꯦꯟꯒꯠꯂꯛꯄ ꯑꯗꯨ ꯈꯪ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 980/1000 [14:37<00:22,  1.11s/it]

[980/1000]
EN: Medical value tourism in India is expected to grow as the government streamlines visa processes for international patients.
MT: ꯚꯥꯔꯠꯇꯥ ꯃꯦꯗꯤꯀꯦꯜ ꯚꯦꯜꯌꯨ ꯇꯨꯔꯤꯖꯝ ꯆꯥꯎꯈꯠꯂꯛꯀꯅꯤ ꯍꯥꯏꯅ ꯄꯥꯅꯔꯤ ꯃꯔꯝꯗꯤ ꯒꯚꯔꯃꯦꯟꯇꯅꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯄꯇꯤꯇꯁꯤꯡꯒꯤ ꯚꯤꯖꯥꯁꯦꯁꯁꯤꯡ ꯁꯃꯂꯥꯏꯟ ꯇꯧ
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 981/1000 [14:38<00:21,  1.12s/it]

[981/1000]
EN: The WHO Global Traditional Medicine Centre in Jamnagar is being upgraded to improve evidence-based research.
MT: ꯖꯝꯅꯒꯔꯗꯥ ꯂꯩꯕ ꯗ ꯌꯨꯑꯍꯣ ꯒ ꯭ ꯂꯣꯕꯦꯜ ꯇꯗꯤꯁꯅꯦꯜ ꯃꯦꯗꯤꯁꯤꯟ ꯁꯦꯟꯇꯔ ꯑꯁꯤ ꯑꯦꯚꯥꯏꯟꯗ-ꯕꯦꯗ ꯔꯤꯁꯔꯆ ꯐꯒꯠꯍꯟꯅꯕ ꯑꯞꯒꯗ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 982/1000 [14:39<00:19,  1.06s/it]

[982/1000]
EN: Indian generic manufacturers are preparing for the patent expiry of several major global obesity medications.
MT: ꯚꯥꯔꯠꯀꯤ ꯖꯦꯅꯦꯔꯤꯛ ꯃꯦꯅꯛꯆꯔꯁꯤꯡꯅ ꯑꯆꯧꯕ ꯒ ꯭ ꯂꯣꯕꯦꯜ ꯑꯣꯕꯦꯁꯤꯇꯤ ꯍꯤꯗꯥꯛ ꯀꯌꯥ ꯑꯃꯒꯤ ꯄꯦꯇꯦꯅꯇ ꯂꯣꯏꯁꯤꯟꯕꯒꯤ ꯁꯦꯝ-ꯁꯥꯔꯤ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 983/1000 [14:40<00:17,  1.05s/it]

[983/1000]
EN: A new digital curriculum was introduced to train public health leaders in epidemiology and modern technology.
MT: ꯑꯦꯄꯤꯗꯦꯃꯤꯌꯣꯂꯣꯖꯤ ꯑꯃꯁꯨꯡ ꯃꯣꯗꯔꯟ ꯇꯦꯛꯅꯣꯂꯣꯖꯤꯗꯥ ꯄ ꯍꯦꯜꯊ ꯂꯤꯗꯔꯁꯤꯡꯕꯨꯦꯟ ꯇꯧꯅꯕꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯗꯤꯖꯤꯇꯦꯜ ꯀꯔꯤꯀꯂꯝ ꯑꯃ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 984/1000 [14:41<00:16,  1.00s/it]

[984/1000]
EN: The government is upgrading AYUSH pharmacies to ensure higher quality standards for traditional medicines.
MT: ꯁꯔꯀꯥꯔꯅꯥ ꯑꯥꯌꯨꯁ ꯐꯥꯔꯃꯥꯁꯤꯁꯤꯡꯕꯨ ꯇꯗꯤꯁꯅꯦꯜ ꯃꯦꯗꯤꯁꯤꯟꯁꯤꯡꯒꯤ ꯑꯋꯥꯡꯕ ꯊꯥꯛꯀꯤꯦꯟꯗꯗꯔꯁꯤꯡ ꯐꯪꯍꯟꯅꯕ ꯑꯒꯕꯥꯗ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 985/1000 [14:42<00:15,  1.02s/it]

[985/1000]
EN: Several district hospitals in Uttar Pradesh are now equipped with 24/7 emergency care and trauma units.
MT: ꯎꯠꯇꯔꯗꯥ ꯂꯩꯕ ꯗꯤꯁꯇꯛꯇ ꯍꯣꯁꯄꯤꯇꯥꯂ ꯀꯌꯥ ꯑꯁꯤ ꯍꯧꯖꯤꯛ 24/7 ꯒꯤ ꯏꯃꯔꯖꯦꯟꯁꯤ ꯀꯦꯌꯔ ꯑꯃꯁꯨꯡ ꯇꯃꯥ ꯌꯨꯅꯤꯇꯁꯤꯡ ꯐꯪ
--------------------------------------------------

Translating:  99%|██████████████████████████▌| 986/1000 [14:43<00:14,  1.03s/it]

[986/1000]
EN: Private healthcare providers are increasing investments in Tier 3 cities to capture the growing rural market.
MT: ꯆꯥꯎꯈꯠꯂꯛꯂꯤꯕ ꯈꯨꯡꯒꯪꯒꯤ ꯀꯩꯊꯦꯜ ꯑꯗꯨ ꯂꯧꯁꯤꯟꯅꯕ ꯇꯤꯌꯔ ꯁꯍꯔꯁꯤꯡꯗꯥꯏꯚꯦꯠ ꯍꯦꯜꯊꯀꯦꯌꯔ ꯄꯋꯦꯗꯔꯁꯤꯡꯅ ꯏꯟꯚꯦꯁꯇꯃꯦꯟꯠꯁꯤꯡ ꯍꯦꯟꯒꯠꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 987/1000 [14:44<00:13,  1.04s/it]

[987/1000]
EN: The Indian healthcare workforce is being upskilled through new digital certifications in allied health disciplines.
MT: ꯑꯦꯂꯥꯏꯗ ꯍꯦꯜꯊ ꯗꯤꯄꯄꯤꯂꯟꯁꯤꯡꯗ ꯚꯥꯔꯠꯀꯤ ꯍꯦꯜꯊꯦꯌꯔ ꯋꯥꯔꯛꯁꯣꯐ ꯑꯁꯤ ꯑꯅꯧꯕ ꯗꯤꯖꯤꯇꯦꯜ ꯁꯔꯇꯤꯐꯤꯀꯦꯠꯁꯤꯡꯒꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯑꯞꯁꯀꯤꯜ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 988/1000 [14:45<00:12,  1.07s/it]

[988/1000]
EN: Public health summits in 2026 emphasized the importance of data-driven decision-making for epidemic prevention.
MT: ꯏꯪꯁꯣꯛ 2026 ꯗꯥ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯍꯦꯜꯊ ꯁꯝꯃꯤꯠꯁꯤꯡ ꯑꯁꯤꯅ ꯂꯥꯏꯆꯠ ꯉꯥꯛꯊꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯗꯦꯇꯥ-ꯗꯚꯟ ꯗꯤꯁꯤꯁꯟ-ꯃꯦꯀꯤꯡꯒꯤ ꯃꯔꯨꯑꯣꯏꯕ ꯑꯗꯨꯗ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 989/1000 [14:46<00:11,  1.03s/it]

[989/1000]
EN: Hospitals in Mumbai are reporting a shift toward integrated care models for chronic lifestyle diseases.
MT: ꯃꯨꯝꯕꯥꯏꯒꯤ ꯍꯣꯁꯄꯤꯇꯥꯂꯁꯤꯡꯅꯅꯤꯛ ꯂꯥꯏꯅꯥꯁꯤꯡꯒꯤ ꯏꯟꯇꯤꯒꯇꯦꯗ ꯀꯦꯌꯔ ꯃꯣꯗꯦꯜꯁꯤꯡꯗ ꯍꯣꯡꯂꯛꯄꯒꯤ ꯄꯥꯎ ꯄꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 990/1000 [14:47<00:10,  1.06s/it]

[990/1000]
EN: The Ministry of Health is focusing on improving the nurse-to-patient ratio in public hospitals through new recruitment drives.
MT: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥ ꯑꯅꯧꯕ ꯔꯦꯀꯨꯠꯃꯦꯟꯇ ꯗꯚꯁꯤꯡꯒꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯄ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯗ ꯅꯔꯁ-ꯇ-ꯄꯦꯇꯤꯦꯟꯇ ꯔꯦꯁꯤꯑꯣ ꯐꯒꯠꯍꯟꯕꯗꯥ ꯃꯤꯠꯌꯦꯡ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 991/1000 [14:48<00:09,  1.03s/it]

[991/1000]
EN: India is positioning itself as a global hub for the manufacturing of affordable biologics and specialized therapies.
MT: ꯚꯥꯔꯠꯅ ꯃꯁꯥ ꯃꯊꯟꯇꯕꯨ ꯃꯃꯜ ꯅꯥꯏꯕꯥ ꯕꯥꯏꯑꯣꯂꯣꯖꯤꯛꯁꯤꯡ ꯑꯃꯁꯨꯡꯁꯤꯑꯦꯂꯤꯁꯇ ꯊꯦꯔꯥꯄꯤꯁꯤꯡ ꯄꯨꯊꯣꯛꯄꯒꯤ ꯒ ꯭ ꯂꯣꯕꯦꯜ ꯍꯕ ꯑꯃ ꯑꯣꯏꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 992/1000 [14:49<00:07,  1.04it/s]

[992/1000]
EN: PGIMER doctors achieve major breakthrough in deadly Celphos poisoning
MT: ꯄꯤꯖꯤꯑꯥꯏꯑꯦꯝ ꯏ ꯑꯥꯔ ꯗꯣꯛꯇꯔꯁꯤꯡꯅ ꯁꯤꯔꯕ ꯁꯦꯜꯐꯣꯁ ꯄꯣꯏꯖꯅꯤꯡꯗꯥ ꯑꯆꯧꯕ ꯃꯥꯏ ꯄꯥꯛꯄ ꯐꯪ
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 993/1000 [14:50<00:06,  1.08it/s]

[993/1000]
EN: What a 12-hour work day can do to your metabolic, mental and reproductive health
MT: ꯄꯨꯡ 12ꯒꯤ ꯊꯕꯛꯀꯤ ꯅꯨꯃꯤꯠ ꯑꯃꯅ ꯅꯍꯥꯛꯀꯤ ꯃꯦꯇꯥꯕꯥꯂꯤꯛ, ꯃꯦꯟꯇꯦꯜ ꯑꯃꯁꯨꯡ ꯔꯤꯄꯗꯦꯛꯇꯤꯕ ꯍꯛꯁꯦꯜꯗꯥ ꯀꯔꯤ ꯀꯔꯤ ꯇꯧꯒꯅꯤ
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 994/1000 [14:51<00:05,  1.02it/s]

[994/1000]
EN: Healthcare services disrupted as doctors across states protest Kolkata colleague’s rape-murder
MT: ꯀꯣꯜꯀꯥꯇꯥꯒꯤ ꯂꯣꯏꯅꯕꯤꯕꯨ ꯃꯤꯍꯥꯠ-ꯃꯇꯥꯏꯕꯒꯤ ꯊꯧꯗꯣꯛ ꯑꯗꯨꯗ ꯔꯥꯖ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯗꯣꯛꯇꯔꯁꯤꯡꯅꯥ ꯋꯥꯀꯠꯂꯛꯄꯗꯒꯤ ꯍꯦꯜꯊꯦꯌꯔ ꯁꯔꯕꯤꯁꯁꯤꯡꯗ ꯑꯀꯥꯏꯕ ꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating: 100%|██████████████████████████▊| 995/1000 [14:52<00:04,  1.06it/s]

[995/1000]
EN: Manmohan Singh unveils multi-crore healthcare plan for paramilitary forces
MT: ꯃꯟꯃꯣꯍꯟ ꯁꯤꯡꯍꯅꯥ ꯄꯦꯔꯥꯃꯤꯂꯤꯇꯔꯤ ꯐꯣꯔꯁꯁꯤꯡꯒꯤꯗꯃꯛ ꯀꯔꯣꯔ ꯀꯌꯥꯃꯨꯛꯀꯤ ꯍꯛꯁꯦꯜꯒꯤ ꯊꯧꯔꯥꯡ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 996/1000 [14:53<00:03,  1.03it/s]

[996/1000]
EN: US Senate Hearing Explodes After Senator Questions Indian Origin Doctor on Men’s Pregnancy
MT: ꯌꯨꯑꯦꯁ ꯁꯦꯅꯦꯠꯀꯤ ꯍꯤꯌꯔꯤꯡ ꯑꯁꯤ ꯁꯦꯅꯦꯇꯔꯅꯥ ꯏꯟꯗꯤꯌꯟ ꯑꯣꯔꯤꯖꯦꯟ ꯗꯣꯛꯇꯔꯗꯥ ꯅꯨꯄꯥꯒꯤ ꯄꯒꯦꯟꯁꯤꯒꯤ ꯃꯇꯥꯡꯗ ꯍꯪꯂꯛꯄꯒꯤ ꯃꯇꯨꯡꯗ ꯄꯣꯈꯥꯏꯈꯤ
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 997/1000 [14:54<00:02,  1.04it/s]

[997/1000]
EN: Dr. D N gupta addresses the lack of awareness surrounding Vitamin D deficiency.
MT: ꯗꯥ. ꯗꯤ ꯑꯦꯟ ꯒꯨꯞꯇꯥꯅꯥ ꯚꯤꯇꯥꯃꯤꯟ ꯗꯤ ꯋꯥꯠꯄꯒꯤ ꯑꯀꯣꯏꯕꯗ ꯂꯩꯕ ꯑꯦꯚꯥꯔꯦꯟꯁꯤ ꯋꯥꯠꯄꯗꯥ ꯋꯥꯐꯝ ꯊꯝ
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 998/1000 [14:55<00:02,  1.07s/it]

[998/1000]
EN: Oncologist shares case of non-tobacco related cancer in 21-year-old man with ‘sharp teeth,’ says ‘It could have been identified’
MT: ꯑꯣꯡꯀꯣꯂꯣꯖꯤꯁꯇꯅꯥ ꯆꯍꯤ 21 ꯁꯨꯔꯕꯥ ꯅꯨꯄꯥꯗꯥ "ꯄꯥꯔꯄ ꯗꯊꯁꯤꯡ ꯂꯩꯕ ꯅꯟ-ꯇꯣꯕꯦꯀꯣ ꯔꯤꯂꯦꯃꯦꯇ ꯀꯦꯟꯁꯔꯒꯤ ꯀꯦꯁ ꯁꯦꯌꯔ ꯇꯧꯔꯦ, ꯍꯥꯏꯔꯤ  ꯃꯁꯤ ꯃꯁꯛ ꯈꯪꯗꯣꯛꯄꯥ ꯉꯝꯒꯅꯤ ꯫
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 999/1000 [14:56<00:01,  1.04s/it]

[999/1000]
EN: Nutritionist says pineapple and cinnamon may help reduce period cramps naturally
MT: ꯅꯇꯁꯤꯁꯇꯅꯥ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯑꯅꯤꯄꯂ ꯑꯃꯁꯨꯡ ꯁꯤꯅꯥꯃꯣꯅꯥ ꯃꯍꯧꯁꯥꯒꯤ ꯑꯣꯏꯕ ꯃꯑꯣꯡꯗ ꯄꯤꯔꯨꯗ ꯀ ꯭ ꯔꯦꯝꯄꯁꯤꯡ ꯍꯟꯊꯍꯟꯕꯗꯥ ꯃꯇꯦꯡ ꯄꯥꯡꯕ ꯌꯥꯏ ꯫
--------------------------------------------------

Translating: 100%|██████████████████████████| 1000/1000 [14:57<00:00,  1.11it/s]

[1000/1000]
EN: Don’t brush before bed? Your heart might pay the price
MT: ꯅꯨꯡꯊꯤꯜꯒꯤ ꯃꯃꯥꯡꯗ ꯕꯁ ꯇꯧꯔꯣꯏꯗꯕꯅꯤ ꯫ ꯅꯍꯥꯛꯀꯤ ꯊꯝꯃꯣꯏꯅ ꯃꯃꯜ ꯊꯤꯕꯥ ꯌꯥꯏ ꯫
--------------------------------------------------

✅ Translations saved to: /home/dingku/Desktop/manipuri_meitei_translations.txt

In [2]:
#!/usr/bin/env python3

#Finetuned IndicTrans2 transalating the test data.

import os
import torch
import pandas as pd
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from peft import PeftModel
from tqdm import tqdm

# ============================================================
# CONFIGURATION
# ============================================================
LANG_CONFIG = {
    "asm": {
        "excel": "/home/dingku/Desktop/WMT 2026 IndicMT Test Data/Category 1/English - Assamese/en-as Test.xlsx",
        "output": "/home/dingku/Desktop/assamese_translations.txt",
        "model": "/home/dingku/Desktop/FTIT26/eng_Latn-asm_Beng",
        "tgt_tag": "asm_Beng"
    },
    "mni_beng": {
        "excel": "/home/dingku/Desktop/WMT 2026 IndicMT Test Data/Category 1/English - Manipuri/en-mni Test.xlsx",
        "output": "/home/dingku/Desktop/manipuri_bengali_translations.txt",
        "model": "/home/dingku/Desktop/FTIT26/eng_Latn-mni_Beng",
        "tgt_tag": "mni_Beng"
    },
    "mni_mtei": {
        "excel": "/home/dingku/Desktop/WMT 2026 IndicMT Test Data/Category 1/English - Meitei/en-mni-Mtei Test.xlsx",
        "output": "/home/dingku/Desktop/manipuri_meitei_translations.txt",
        "model": "/home/dingku/Desktop/FTIT26/eng_Latn-mni_Mtei",
        "tgt_tag": "mni_Mtei"
    },
    "brx": {
        "excel": "/home/dingku/Desktop/WMT 2026 IndicMT Test Data/Category 2/English - Bodo/en-bodo Test.xlsx",
        "output": "/home/dingku/Desktop/bodo_translations.txt",
        "model": "/home/dingku/Desktop/FTIT26/eng_Latn-brx_Deva",
        "tgt_tag": "brx_Deva"
    }
}

BASE_MODEL = "ai4bharat/indictrans2-en-indic-1B"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
COLUMN_NAME = "English Sentences"
MAX_NEW_TOKENS = 200

# Generation parameters that work for Meitei Mayek
GEN_KWARGS = {
    "num_beams": 4,
    "early_stopping": True,
    "no_repeat_ngram_size": 2,
    "repetition_penalty": 2.0,
    "length_penalty": 1.0,
    "do_sample": False,
    "temperature": 1.0,
    "pad_token_id": None  # will be set later
}

# ============================================================
# LOAD MODEL & TOKENIZER
# ============================================================
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
base_model = AutoModelForSeq2SeqLM.from_pretrained(
    BASE_MODEL,
    trust_remote_code=True,
    torch_dtype=torch.float32
).to(DEVICE)

# ============================================================
# TRANSLATE FUNCTION
# ============================================================
def translate(lang_code, config):
    print(f"\n{'='*60}\nTranslating {lang_code}...\n{'='*60}")
    
    # Load adapter
    model = PeftModel.from_pretrained(base_model, config["model"])
    model.eval()
    
    # Optionally merge (uncomment if needed)
    # model = model.merge_and_unload()
    
    # Read Excel
    df = pd.read_excel(config["excel"])
    sentences = df[COLUMN_NAME].dropna().astype(str).tolist()
    print(f"Found {len(sentences)} sentences.")
    
    src_tag = "eng_Latn"
    tgt_tag = config["tgt_tag"]
    
    translations = []
    for i, sent in enumerate(tqdm(sentences, desc="Translating"), start=1):
        if not sent.strip():
            translations.append("")
            continue
        
        input_text = f"{src_tag} {tgt_tag} {sent}"
        inputs = tokenizer(
            input_text,
            return_tensors="pt",
            truncation=True,
            max_length=512
        ).to(DEVICE)
        
        gen_kwargs = GEN_KWARGS.copy()
        gen_kwargs["pad_token_id"] = tokenizer.eos_token_id
        
        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=MAX_NEW_TOKENS,
                **gen_kwargs
            )
        
        translation = tokenizer.decode(outputs[0], skip_special_tokens=True)
        # Remove any language tag that might appear at start
        if translation.startswith(tgt_tag):
            translation = translation[len(tgt_tag):].strip()
        
        translations.append(translation)
        print(f"\n[{i}/{len(sentences)}]\nEN: {sent}\n{lang_code.upper()}: {translation}\n" + "-"*50)
    
    # Save
    with open(config["output"], "w", encoding="utf-8") as f:
        for trans in translations:
            f.write(trans + "\n")
    print(f"✅ Saved to {config['output']}")

# ============================================================
# RUN
# ============================================================
if __name__ == "__main__":
    for lang in ["asm", "mni_beng", "mni_mtei", "brx"]:
        translate(lang, LANG_CONFIG[lang])
    print("\n🎉 All translations attempted.")

/home/dingku/jupyter_env/lib/python3.12/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

============================================================
Translating asm...
============================================================
Found 1000 sentences.

Translating:   0%|                             | 1/1000 [00:01<26:13,  1.57s/it]

[1/1000]
EN: NDTV has learnt from sources that the T20 World Cup 2026 match between India and Pakistan is ON.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 5 2026 а : ?
--------------------------------------------------

Translating:   0%|                             | 2/1000 [00:02<24:37,  1.48s/it]

[2/1000]
EN: The PCB placed several demands before the ICC.
ASM: দৰে জাৰি বিরীৰ লিলাৰ ৰাদেৰা বাৰু.
--------------------------------------------------

Translating:   0%|                             | 3/1000 [00:04<25:40,  1.55s/it]

[3/1000]
EN: The PCB pushed for ICC intervention to facilitate a bilateral series between India and Pakistan.
ASM: দৰে জাৰি বিরীৰ লিৱাৰৰ লাৰ্দে,.
--------------------------------------------------

Translating:   0%|                             | 4/1000 [00:06<30:01,  1.81s/it]

[4/1000]
EN: Virat Kohli and Rohit Sharma have been demoted to Grade B in BCCI's central contract list for 2025-26.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি মিন্দৰা লাৰু а-ᱹ :  )
--------------------------------------------------

Translating:   0%|▏                            | 5/1000 [00:08<29:56,  1.81s/it]

[5/1000]
EN: Thirty senior men's cricketers have been awarded central contracts, with the BCCI doing away with the A+ grade.
ASM: দেৱাৰ বিজৰ ৰর্দৰে. : ?
--------------------------------------------------

Translating:   1%|▏                            | 6/1000 [00:10<28:45,  1.74s/it]

[6/1000]
EN: As per the 2024-25 BCCI contracts, any player in Grade A would receive Rs 5 crore annually.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে 5 - 25 লাৰি জেৰা মিৰু яৰ 11 а : ?
--------------------------------------------------

Translating:   1%|▏                            | 7/1000 [00:11<25:18,  1.53s/it]

[7/1000]
EN: Grade B players would get Rs 3 crore, while
ASM: . দেৱাৰ বিজৰ 3 র্দৰে জীৱaৰ ৰালে ।
--------------------------------------------------

Translating:   1%|▏                            | 8/1000 [00:12<22:40,  1.37s/it]

[8/1000]
EN: Grade C players would get Rs 1 crore.
ASM: . দেৱাৰ বির্জে 1 জীৱaৰ ৰালা ।
--------------------------------------------------

Translating:   1%|▎                            | 9/1000 [00:13<21:46,  1.32s/it]

[9/1000]
EN: Earlier, Grade A+ players (Kohli, Rohit, Jasprit Bumrah, Ravindra Jadeja) used to receive Rs 7 crore.
ASM: জাৰে বির্দৰী দেৱাৰৰ বাৰি লালিৰ ৰামি, āh्लॆ а.
--------------------------------------------------

Translating:   1%|▎                           | 10/1000 [00:15<24:45,  1.50s/it]

[10/1000]
EN: The BCCI has not yet officially declared whether the payment structure for 2025-26 will be any different.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে জিলে, মিলাৰি বাৰু а 2025-26 ।
--------------------------------------------------

Translating:   1%|▎                           | 11/1000 [00:17<25:16,  1.53s/it]

[11/1000]
EN: 21 women cricketers classified in Grade A, B and C.
ASM: দেৱাৰ বির্জে জীৱে ৰালি, লাৰি বাৰে 1 মি ) ।
--------------------------------------------------

Translating:   1%|▎                           | 12/1000 [00:18<26:45,  1.62s/it]

[12/1000]
EN: Harmanpreet Kaur, Smriti Mandhana, Deepti Sharma and Jemimah Rodrigues are the four players to be included in Grade A.
ASM: দেৱাৰ বির্জে.
--------------------------------------------------

Translating:   1%|▎                           | 13/1000 [00:20<26:29,  1.61s/it]

[13/1000]
EN: The cycle for new central contract is based on performance and volume of games played during the preceding season.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:   1%|▍                           | 14/1000 [00:22<27:07,  1.65s/it]

[14/1000]
EN: Pakistan and Bangladesh's demands from the International Cricket Council (ICC) have just grown bigger.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰিলাৰ ) রিন্দৰা പ്ৰু  कावलি विरोधी  एतेऩुम् bjি्लॆ āৰ तिकिल् ял ।
--------------------------------------------------

Translating:   2%|▍                           | 15/1000 [00:23<25:44,  1.57s/it]

[15/1000]
EN: The 2031 edition of the ODI World Cup is set to be played in India and Bangladesh.
ASM: . দৰে জাৰি বিরীৱাৰৰ ৰালাৰ মিৰ্লে, বাৰা āৰু а : ?
--------------------------------------------------

Translating:   2%|▍                           | 16/1000 [00:25<25:31,  1.56s/it]

[16/1000]
EN: At present, the hybrid model is applicable until 2027.
ASM: . দেৱাৰ বির্জীৰ ৰালাৰে লিমি জিৰি, বাৰা പ്ৰু а 2027 :
--------------------------------------------------

Translating:   2%|▍                           | 17/1000 [00:25<21:46,  1.33s/it]

[17/1000]
EN: The extension would allow Bangladesh and Pakistan to play all their matches in Bangladesh and not India.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:   2%|▌                           | 18/1000 [00:27<22:33,  1.38s/it]

[18/1000]
EN: The BCB was represented by its head Aminul Islam Bulbul while PCB chairman Mohsin Naqvi was also present.
ASM: দেৱাৰ বিজৰ ৰর্দৰে জীৱে,.
--------------------------------------------------

Translating:   2%|▌                           | 19/1000 [00:28<19:44,  1.21s/it]

[19/1000]
EN: ICC's deputy chairman Imran Khawaja was present in the meeting.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:   2%|▌                           | 20/1000 [00:29<19:04,  1.17s/it]

[20/1000]
EN: No joint declaration was issued after the four-hour meeting.
ASM: দেৱাৰ বির্জে জীৱে, āৰি লিমিৰ ৰালা ।
--------------------------------------------------

Translating:   2%|▌                           | 21/1000 [00:30<20:37,  1.26s/it]

[21/1000]
EN: The hybrid model arrangement was introduced after India refused to tour Pakistan for the 2025 Champions Trophy.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰা লাৰি কৰa പ് 2017 : ायो-ᱹ.
--------------------------------------------------

Translating:   2%|▌                           | 22/1000 [00:32<22:30,  1.38s/it]

[22/1000]
EN: After extensive negotiations, a hybrid model was accepted by all parties, including the ICC.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:   2%|▋                           | 23/1000 [00:34<23:34,  1.45s/it]

[23/1000]
EN: The second part of the arrangement states that Pakistan will not travel to India for the 2026 T20 World Cup.
ASM: . দৰিরে জাৱাৰ বিৰে, লিীৰ ৰালাৰ্দেৰা বাৰু মি्लॆ āৰ तिकिल् а 2022 : ?
--------------------------------------------------

Translating:   2%|▋                           | 24/1000 [00:36<25:57,  1.60s/it]

[24/1000]
EN: As a result, all of Pakistan's matches (even if they reach the final) will be played in Sri Lanka.
ASM: দেৱাৰ বির্জে. : ायो-, বাৰে ৰালাৰী জিলে ; āৰি মি কিৰা ।
--------------------------------------------------

Translating:   2%|▋                           | 25/1000 [00:37<23:46,  1.46s/it]

[25/1000]
EN: Bangladesh, Pakistan, and India must be treated the same.
ASM: দেৱাৰ বির্জীৱে জিমি লাৰে ৰালে ।
--------------------------------------------------

Translating:   3%|▋                           | 26/1000 [00:38<23:59,  1.48s/it]

[26/1000]
EN: Now, Gavaskar has taken an indirect jibe at Hussain
ASM: দেৱাৰ  বির্জীৱে বাৰি জিলে ।
--------------------------------------------------

Translating:   3%|▊                           | 27/1000 [00:40<24:22,  1.50s/it]

[27/1000]
EN: He went on to give the example of the 2003 World Cup, when England refused to tour Zimbabwe in protest against Robert Mugabe's regime.
ASM: . দেৱাৰ বিজৰ ৰারে জীৱিৰ্দৰিলা বাৰে, লিমি्लॆ āৰু а 2003 : ायो-.
--------------------------------------------------

Translating:   3%|▊                           | 28/1000 [00:41<23:44,  1.47s/it]

[28/1000]
EN: Samson's knock was full of intent but fell short in effectiveness quotient.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:   3%|▊                           | 29/1000 [00:42<23:19,  1.44s/it]

[29/1000]
EN: With this win, India overtook Pakistan at the summit of Group A courtesy of a superior net run-rate.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:   3%|▊                           | 30/1000 [00:44<24:31,  1.52s/it]

[30/1000]
EN: India batter Abhishek Sharma will take no part in the T20 World Cup 2026 clash against Namibia in New Delhi on Thursday.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 5 2026 а : ?
--------------------------------------------------

Translating:   3%|▊                           | 31/1000 [00:45<23:25,  1.45s/it]

[31/1000]
EN: Abhishek isn't fine still, might take one or two games.
ASM: . দৰে বির্জাৰ জীৱাৰৰ লিমি লাৰি, বাৰা क्कूटি ৰাদে ।
--------------------------------------------------

Translating:   3%|▉                           | 32/1000 [00:46<18:54,  1.17s/it]

[32/1000]
EN: Samson comes in.
ASM: .
--------------------------------------------------

Translating:   3%|▉                           | 33/1000 [00:47<20:01,  1.24s/it]

[33/1000]
EN: Bumrah comes in for Siraj," said Suryakumar at the toss.
ASM: . দেৱাৰ বির্জীৱে জিলে, মি লাৰে ৰাদৰা বাৰি विरोधी āৰু яৰ )
--------------------------------------------------

Translating:   3%|▉                           | 34/1000 [00:49<19:57,  1.24s/it]

[34/1000]
EN: Defending with dew will build our confidence. Hope our batters entertain the crowd.
ASM: দৰি জেৱাৰ বির্লে, মিীৰে বাৰা রিলাৰ ৰাদে ;.
--------------------------------------------------

Translating:   4%|▉                           | 35/1000 [00:50<20:52,  1.30s/it]

[35/1000]
EN: It's a big tournament, dew will be a big factor.
ASM: দেৱাৰ বির্জে.
--------------------------------------------------

Translating:   4%|█                           | 36/1000 [00:52<22:15,  1.39s/it]

[36/1000]
EN: India made two changes to the side that beat the USA on the opening day of the tournament.
ASM: দেৱাৰ বির্জীৱে জিৰিলে,.
--------------------------------------------------

Translating:   4%|█                           | 37/1000 [00:53<22:09,  1.38s/it]

[37/1000]
EN: Sanju Samson replaced Abhishek, while Jasprit Bumrah replaced Mohammed Siraj in the India XI.
ASM: দৰি জেৱাৰ বিরীৰে. : ?
--------------------------------------------------

Translating:   4%|█                           | 38/1000 [00:55<24:24,  1.52s/it]

[38/1000]
EN: India take on Pakistan next, with the team set to travel to Colombo for the game on February 15.
ASM: . বিৰে দৰি জাৰী র্দেৱাৰৰ ৰালাৰ মিলে ।
--------------------------------------------------

Translating:   4%|█                           | 39/1000 [00:56<21:45,  1.36s/it]

[39/1000]
EN: The cabinet agreed with certain conditions as per the Cunha report.
ASM: দেৱাৰ বির্জে জীৱলৰ ৰাদৰে, বাৰি.
--------------------------------------------------

Translating:   4%|█                           | 40/1000 [00:58<23:08,  1.45s/it]

[40/1000]
EN: He mentioned in the report a maximum of 35,000 people and other conditions.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে লাৰি 5, 000 জিমি яৰু āৰা маৰ तिक ।
--------------------------------------------------

Translating:   4%|█▏                          | 41/1000 [00:59<22:06,  1.38s/it]

[41/1000]
EN: India reached the 100-run mark in just 6.5 overs - the fastest team hundred in T20 World Cup history.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 5 : ?-ᱹ.
--------------------------------------------------

Translating:   4%|█▏                          | 42/1000 [01:00<23:14,  1.46s/it]

[42/1000]
EN: After being asked to bat first, India were off to a decent start, making 8/0 in the first over.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে মি জিৰি विरोधी লাৰু പ് а : ?
--------------------------------------------------

Translating:   4%|█▏                          | 43/1000 [01:02<24:05,  1.51s/it]

[43/1000]
EN: After four overs, the defending champions reached 43/1, with Ishan Kishan finding a couple of boundaries.
ASM: . দেৱাৰ বির্জীৰ ৰিলে লাৰি জিৰে, মিন্দৰা বাৰু āৰ ) রি विरोधी പ് तिकिल् а- : ?
--------------------------------------------------

Translating:   4%|█▏                          | 44/1000 [01:04<23:55,  1.50s/it]

[44/1000]
EN: On the first ball of the 11th over, spinner Bernard Scholtz dismissed captain Suryakumar Yadav for just 12.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে মি জিৰি 11 āৰা লাৰু яৰ विरोधी а : ?
--------------------------------------------------

Translating:   4%|█▎                          | 45/1000 [01:05<24:08,  1.52s/it]

[45/1000]
EN: India lost another wicket quickly when Tilak Varma was removed for 25 by Namibia skipper Erasmus in the 12th over.
ASM: . বিৰে দৰি জাৰী রেৱাৰৰ ৰালাৰ লে, মি विरोधी বাৰু പ് āৰ্দেৰা а : ?
--------------------------------------------------

Translating:   5%|█▎                          | 46/1000 [01:07<25:22,  1.60s/it]

[46/1000]
EN: Shivam Dube and Hardik Pandya then combined to hammer 24 runs off Bernard Scholtz as India raced to 168/4.
ASM: . দেৱাৰ বির্জীৰ ৰালে, মিৰে লাৰি বাৰা জি्लॆ āৰু аᱹ о м : ?- )
--------------------------------------------------

Translating:   5%|█▎                          | 47/1000 [01:08<24:48,  1.56s/it]

[47/1000]
EN: By the end of the 18th over, India had reached 199/4 with Pandya and Dube going strong.
ASM: . জেৱাৰ বিদৰে রীৱিলে, বাৰি দ্লাৰ ৰামি 1 99/4 ।
--------------------------------------------------

Translating:   5%|█▎                          | 48/1000 [01:10<24:46,  1.56s/it]

[48/1000]
EN: On the first ball of the 19th over, Pandya completed his fifty off 27 deliveries as India crossed the 200-run mark.
ASM: . দেৱাৰ বির্জীৰ ৰালাৰে মি জিৰিলে, а :  )-,ᱹ ; বাৰা പ്.. ।
--------------------------------------------------

Translating:   5%|█▎                          | 49/1000 [01:12<25:30,  1.61s/it]

[49/1000]
EN: Shivam Dube was run out for 23 after a mix-up with Rinku Singh.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰিলাৰু āৰা রিন্দৰ ; а : ?
--------------------------------------------------

Translating:   5%|█▍                          | 50/1000 [01:14<28:32,  1.80s/it]

[50/1000]
EN: India then lost Rinku Singh (1) and Arshdeep Singh (2) in the final over, finishing at 209/9.
ASM: . দেৱাৰ বির্জীৱে জিলে ( 1 ), বাৰি লাৰে ৰাদৰা মিৰু রিন্দি विरोधी āৰ तिक പ്ৰराज ायो bjিদat  गोंधळ्लॆ ab ।
--------------------------------------------------

Translating:   5%|█▍                          | 51/1000 [01:16<30:19,  1.92s/it]

[51/1000]
EN: ICC Men’s T20 World Cup 2026 began on February 7, 2026, at Sinhalese Sports Club Ground with Pakistan playing Netherlands in the opening match.
ASM: 2026 জেৱাৰ বিদৰে রীৱিলাৰ ৰালে, বাৰি মি विरोधी দ্দেৰুৱa പ്ৰা āৰ तिकिल् яৰ ) а.-. : ायोᱹ ;  वसूल समारंभ घटन b |
--------------------------------------------------

Translating:   5%|█▍                          | 52/1000 [01:18<29:07,  1.84s/it]

[52/1000]
EN: Bangladesh national cricket team faced the India men's national cricket team in an opening match reported ahead of the 2026 T20 tournament.
ASM: . বিৰে দৰি জাৰী র্দেৱাৰৰ ৰিলে, বাৰু মিলাৰ а 202220 яৰ तिकৰা āৰ रा तनक घटनुप 492-ᱹ ab ।
--------------------------------------------------

Translating:   5%|█▍                          | 53/1000 [01:19<27:16,  1.73s/it]

[53/1000]
EN: Ishan Kishan struck a rapid half-century.
ASM: দেৱাৰ বির্জীৱে বাৰি জিলে, মিৰে ৰাদৰা লাৰু яৰ तिक.
--------------------------------------------------

Translating:   5%|█▌                          | 54/1000 [01:21<28:00,  1.78s/it]

[54/1000]
EN: Faf du Plessis scored a half-century and Mitchell Starc took a five-wicket haul in the same match report.
ASM: দেৱাৰ বিজৰ ৰর্দৰে জীৱে,.
--------------------------------------------------

Translating:   6%|█▌                          | 55/1000 [01:23<28:38,  1.82s/it]

[55/1000]
EN: Jasprit Bumrah and Ravindra Jadeja were reported to have been demoted in the 2025–26 central contracts discussion.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মিৰি লাৰু জিন্দৰা  गळिल् പ्लॆ : ाय़-ᱹ ;
--------------------------------------------------

Translating:   6%|█▌                          | 56/1000 [01:25<27:38,  1.76s/it]

[56/1000]
EN: Rohit Sharma carried the men’s T20 World Cup trophy during a promotional appearance.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে জিৰি লাৰু মি 5 āৰা а : ?-ᱹ.
--------------------------------------------------

Translating:   6%|█▌                          | 57/1000 [01:27<29:37,  1.88s/it]

[57/1000]
EN: The International Cricket Council update said a high-profile match involving Pakistan would go ahead on February 15, 2026, in Colombo.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে āৰি লাৰু মিৰা а- 2026 জিন্দৰ तिकिल् яৰ ) പ്ৰরি विरोधी  गळ नृি्लॆ  वसूल वरकु ।
--------------------------------------------------

Translating:   6%|█▌                          | 58/1000 [01:28<27:24,  1.75s/it]

[58/1000]
EN: The New Zealand national cricket team lost the first ODI by four wickets to the India men's national cricket team.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:   6%|█▋                          | 59/1000 [01:30<26:56,  1.72s/it]

[59/1000]
EN: Australia national cricket team ended day one at 67 for seven in reply to 150 by the India men's national cricket team in a Test match post.
ASM: . দেৱাৰ বির্জীৰ ৰালে জিৰি লাৰে, বাৰু মিন্দৰা പ्लॆ : ?
--------------------------------------------------

Translating:   6%|█▋                          | 60/1000 [01:32<27:33,  1.76s/it]

[60/1000]
EN: The India national under-19 cricket team won the ICC U19 World Cup final by 100 runs against the England national under-19 cricket team in Harare.
ASM: . দেৱাৰ বির্জীৰ ৰালাৰে লিমি জিৰি 1 :-, ; বাৰু പ് - ) а.
--------------------------------------------------

Translating:   6%|█▋                          | 61/1000 [01:33<26:10,  1.67s/it]

[61/1000]
EN: Members of the India women's national cricket team were given a grand welcome after their title-winning campaign.
ASM: দেৱাৰ বির্জীৱে,.
--------------------------------------------------

Translating:   6%|█▋                          | 62/1000 [01:35<24:47,  1.59s/it]

[62/1000]
EN: The India women's national cricket team lifting the ICC Women’s World Cup as one of the year’s landmark moments.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:   6%|█▊                          | 63/1000 [01:36<25:49,  1.65s/it]

[63/1000]
EN: The Indian Premier League season in 2025 was reported as suspended indefinitely amid escalating India–Pakistan military tensions.
ASM: দেৱাৰ  2025 বির্জীৰ ৰালে, বাৰে জিৰি মিন্দৰা লাৰু яৰ विरोधी атি समारंभ миৰ तिक āৰat ।
--------------------------------------------------

Translating:   6%|█▊                          | 64/1000 [01:38<24:37,  1.58s/it]

[64/1000]
EN: The Eden Gardens hosted the opening spectacle for the 18th edition of the Indian Premier League.
ASM: . দেৱাৰ বিজৰ ৰারে জীৱে, বাৰি লিৰু মিলাৰ্দৰেৰা പ് : ?
--------------------------------------------------

Translating:   6%|█▊                          | 65/1000 [01:40<26:02,  1.67s/it]

[65/1000]
EN: Royal Challengers Bengaluru named Rajat Patidar as captain for the season starting March 21.
ASM: . দেৱাৰ বিজৰ ৰার্দৰে জীৱেৰি লালে, মি विरोधी বাৰু āৰা പ്ৰ तिकिल् а : ?
--------------------------------------------------

Translating:   7%|█▊                          | 66/1000 [01:42<28:12,  1.81s/it]

[66/1000]
EN: Chennai Super Kings posted their lowest home total and suffered a fifth straight loss.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:   7%|█▉                          | 67/1000 [01:43<26:47,  1.72s/it]

[67/1000]
EN: A Dharamsala fixture involving Punjab Kings and Delhi Capitals was called off after a blackout.
ASM: দেৱাৰ বির্জে বাৰে, জীৱি লিলাৰ ৰামি विरोधी āৰি কৰা ।.
--------------------------------------------------

Translating:   7%|█▉                          | 68/1000 [01:44<23:13,  1.50s/it]

[68/1000]
EN: Punjab Kings defeated Mumbai Indians in Jaipur to secure a top-two league finish.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:   7%|█▉                          | 69/1000 [01:46<24:41,  1.59s/it]

[69/1000]
EN: KL Rahul became the fastest Indian to 8,000 T20 runs after an unbeaten 112.
ASM: . দেৱাৰ বির্জীৰ ৰালে, 1120 বাৰে লাৰি 5,20 āৰু জিমি а : ?
--------------------------------------------------

Translating:   7%|█▉                          | 70/1000 [01:49<28:29,  1.84s/it]

[70/1000]
EN: Virat Kohli spoke about the June 4 stampede linked to his franchise’s celebrations.
ASM: দেৱাৰ বির্জীৱে বাৰি জিলে, মিৰে ৰাদৰা লাৰু রি्लॆ പ്ৰ तिकिल् āৰचर  वसूल समारंभ ন্দatৰराज घटनुपूत яৰ 11 ।
--------------------------------------------------

Translating:   7%|█▉                          | 71/1000 [01:51<29:20,  1.89s/it]

[71/1000]
EN: The uncertainty over player retention created suspense ahead of the next Indian Premier League season.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:   7%|██                          | 72/1000 [01:51<24:37,  1.59s/it]

[72/1000]
EN: Rafael Nadal announced he would retire.
ASM: দেৱাৰ বির্জীৰ ৰিলে.
--------------------------------------------------

Translating:   7%|██                          | 73/1000 [01:53<25:23,  1.64s/it]

[73/1000]
EN: Carlos Alcaraz beat Novak Djokovic to win his first major title.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:   7%|██                          | 74/1000 [01:55<26:34,  1.72s/it]

[74/1000]
EN: Alexander Zverev lost a marathon match to Carlos Alcaraz in a five-set battle.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:   8%|██                          | 75/1000 [01:57<26:45,  1.74s/it]

[75/1000]
EN: Rohan Bopanna announced his retirement from professional tennis.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লাৰু āৰা মিন্দৰ स्बराज ।
--------------------------------------------------

Translating:   8%|██▏                         | 76/1000 [01:59<30:10,  1.96s/it]

[76/1000]
EN: A 14-place leap that signaled an upswing for India Davis Cup team in international tennis standings.
ASM: দৰি জেৱাৰ  বির্দীৰে মিলে, বাৰু লা तिकৰা āৰायला ৰান্দেৰ ) പ്ৰचरᱶাৰৰ ोप करुतৰat ्रॆি विरोधी  वसूल समारंभ яৰ কৰ शेवट ।
--------------------------------------------------

Translating:   8%|██▏                         | 77/1000 [02:02<32:47,  2.13s/it]

[77/1000]
EN: Elena Rybakina overcame Aryna Sabalenka to win the 2026 Australian Open final.
ASM: . দেৱাৰ বিজৰ ৰার্দৰে জীৱেৰি লিমি, বাৰু লাৰা āৰ तिकৰायला а 2026 яৰ 11  गोंधळर्न  तीर्क्क ।
--------------------------------------------------

Translating:   8%|██▏                         | 78/1000 [02:04<31:59,  2.08s/it]

[78/1000]
EN: Novak Djokovic became the first player to reach 400 Grand Slam singles match wins in the Open Era.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি মি 400 লাৰু āৰা রিন্দৰ स्बराज ;
--------------------------------------------------

Translating:   8%|██▏                         | 79/1000 [02:06<31:24,  2.05s/it]

[79/1000]
EN: The India men's national field hockey team and its Olympic bronze-medal campaign in a dedicated post.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:   8%|██▏                         | 80/1000 [02:08<30:38,  2.00s/it]

[80/1000]
EN:  The India men's national field hockey team across major tournaments.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:   8%|██▎                         | 81/1000 [02:10<31:15,  2.04s/it]

[81/1000]
EN: The India men's national field hockey team beat South Korea men's national field hockey team 4–1 in a match update.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে মি জিৰি 1  तिकৰা লাৰু āৰat പ്ৰরি विरोधी яৰ ) а : ?
--------------------------------------------------

Translating:   8%|██▎                         | 82/1000 [02:12<30:29,  1.99s/it]

[82/1000]
EN: The house of K. D. Singh Babu would be developed as a tourist attraction.
ASM: দেৱাৰ বির্জীৰ ৰিলে, বাৰে জেৰি লাৰু মিৰা রিন্দৰ तिक āৰat ।
--------------------------------------------------

Translating:   8%|██▎                         | 83/1000 [02:13<26:24,  1.73s/it]

[83/1000]
EN: Lakshya Sen finished fourth in a tournament.
ASM: দেৱাৰ বির্জে জীৱaৰ ৰালে ।
--------------------------------------------------

Translating:   8%|██▎                         | 84/1000 [02:14<25:48,  1.69s/it]

[84/1000]
EN: Saina Nehwal confirmed her retirement from competitive badminton.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:   8%|██▍                         | 85/1000 [02:16<25:25,  1.67s/it]

[85/1000]
EN: R. Vaishali won the FIDE Women’s Grand Swiss.
ASM: দেৱাৰ বির্জে. : ?
--------------------------------------------------

Translating:   9%|██▍                         | 86/1000 [02:17<23:02,  1.51s/it]

[86/1000]
EN: R. Praggnanandhaa came from behind to win a game.
ASM: দেৱাৰ বিজৰ ৰার্দৰী,.
--------------------------------------------------

Translating:   9%|██▍                         | 87/1000 [02:18<20:30,  1.35s/it]

[87/1000]
EN: D. Gukesh as the youngest world chess champion in history.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:   9%|██▍                         | 88/1000 [02:20<23:03,  1.52s/it]

[88/1000]
EN: D. Gukesh secured his first win at Tata Steel Chess Masters 2026.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে মি জিৰা লাৰু āৰিন্দৰ ) а.-ᱹ.
--------------------------------------------------

Translating:   9%|██▍                         | 89/1000 [02:22<24:29,  1.61s/it]

[89/1000]
EN: Avinash Sable became the first Indian man to qualify for the men’s 3000m steeplechase final at Paris Olympics 2024.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি्लॆ লা तिकৰা പ് 2024 :-ᱹ.
--------------------------------------------------

Translating:   9%|██▌                         | 90/1000 [02:23<22:34,  1.49s/it]

[90/1000]
EN: Mirabai Chanu returned to competition as she prepared for upcoming international events.
ASM: দৰিরে জাৱাৰ  : বিলে, ायो.
--------------------------------------------------

Translating:   9%|██▌                         | 91/1000 [02:25<26:08,  1.73s/it]

[91/1000]
EN: Manu Bhaker and Harmanpreet Singh among athletes highlighted in a sports-honours post.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:   9%|██▌                         | 92/1000 [02:28<29:59,  1.98s/it]

[92/1000]
EN: At the Milan–Cortina Winter Olympics 2026, Ilia Malinin landed a backflip on one skate in an Olympics moment.
ASM: . বিৰে দেৱাৰ জরীৱিলাৰ ৰালে ।
--------------------------------------------------

Translating:   9%|██▌                         | 93/1000 [02:30<28:36,  1.89s/it]

[93/1000]
EN:  Anastasiia Gubanova delivered a performance featuring Indian cultural elements on the ice in Milan.
ASM: দেৱাৰ বির্জীৱে জিলাৰ ৰালে,.
--------------------------------------------------

Translating:   9%|██▋                         | 94/1000 [02:32<29:01,  1.92s/it]

[94/1000]
EN: Formula One World Championship could return to Indian soil after a 13-year gap as policy issues are addressed.
ASM: দেৱাৰ বির্জীৰ ৰালে জিলাৰে, বাৰি মিৰা āৰু রিন্দৰ तिक പ്ৰराज а : ?-.
--------------------------------------------------

Translating:  10%|██▋                         | 95/1000 [02:34<31:26,  2.08s/it]

[95/1000]
EN: Nikhat Zareen won 5–0 over Guo Yi Xuan in a bout described as a commanding victory.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে 5 : ?
--------------------------------------------------

Translating:  10%|██▋                         | 96/1000 [02:36<31:25,  2.09s/it]

[96/1000]
EN: Minakshi Hooda and Jaismine Lamboria upset Paris Olympics medallists and top seeds in a major boxing event.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  10%|██▋                         | 97/1000 [02:38<30:35,  2.03s/it]

[97/1000]
EN: Vinesh Phogat announced a return to wrestling on December 12, 2025.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মিলাৰি জিদৰা āৰু аᱹ 2025 яৰ 11 мо तिक ।
--------------------------------------------------

Translating:  10%|██▋                         | 98/1000 [02:39<25:44,  1.71s/it]

[98/1000]
EN: Village spectators watching a kabaddi match organised at a makeshift arena.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  10%|██▊                         | 99/1000 [02:41<27:22,  1.82s/it]

[99/1000]
EN: The 21st Tata Mumbai Marathon took place with large-scale participation in Mumbai.
ASM: দেৱাৰ বির্জীৰ ৰিলে, বাৰে মিৰি লাৰু জিদৰা রি विरोधी പ്ৰ तिकिल्  गोंधळर्न āৰायला ।
--------------------------------------------------

Translating:  10%|██▋                        | 100/1000 [02:44<30:00,  2.00s/it]

[100/1000]
EN: The first-ever Formula 4 car show on Marina Beach was held on the banks of the sea in Chennai.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 4 লাৰু āৰা яৰ तिकৰायला атিন্দৰ सब?
--------------------------------------------------

Translating:  10%|██▋                        | 101/1000 [02:45<25:43,  1.72s/it]

[101/1000]
EN: Tilak Varma said India felt ready for the high-stakes Pakistan match in Colombo.
ASM: দৰে জাৰি বির্রীৰ লালে,.
--------------------------------------------------

Translating:  10%|██▊                        | 102/1000 [02:47<27:00,  1.80s/it]

[102/1000]
EN: Tilak Varma said the India squad had entered a focused “match zone” mindset.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি কিদৰা লাৰু āৰ तिकिल् ्रॆक्कারি विरोधी പ്ৰরে?
--------------------------------------------------

Translating:  10%|██▊                        | 103/1000 [02:48<23:13,  1.55s/it]

[103/1000]
EN: Tilak Varma described the India–Pakistan fixture as a major highlight of the tournament.
ASM: দেৱাৰ বির্জীৰ ৰালা,.
--------------------------------------------------

Translating:  10%|██▊                        | 104/1000 [02:49<22:59,  1.54s/it]

[104/1000]
EN: Tilak Varma emphasized preparation and intensity for India ahead of the Pakistan clash.
ASM: দেৱাৰ বির্জীৰ ৰিলে, লাৰে বাৰি জিমিৰু. : ?
--------------------------------------------------

Translating:  10%|██▊                        | 105/1000 [02:50<21:28,  1.44s/it]

[105/1000]
EN: Tilak Varma framed the Pakistan game as a test of temperament and execution.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  11%|██▊                        | 106/1000 [02:52<24:27,  1.64s/it]

[106/1000]
EN: Delhi Metro extended operating hours to support fans travelling for the India–Namibia match.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  11%|██▉                        | 107/1000 [02:55<26:36,  1.79s/it]

[107/1000]
EN: Delhi Metro added services to manage crowd flow before and after the India–Namibia game.
ASM: দেৱাৰ বির্জি.
--------------------------------------------------

Translating:  11%|██▉                        | 108/1000 [02:57<29:29,  1.98s/it]

[108/1000]
EN: City transport officials coordinated services to reduce congestion around the India–Namibia fixture.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  11%|██▉                        | 109/1000 [02:59<28:33,  1.92s/it]

[109/1000]
EN: Extended metro services aimed to make stadium travel easier for cricket spectators in Delhi.
ASM: দেৱাৰ বিজৰ ৰার্দৰে জীৱে,.
--------------------------------------------------

Translating:  11%|██▉                        | 110/1000 [03:01<28:36,  1.93s/it]

[110/1000]
EN: Additional trains were planned to handle the match-day rush for the India–Namibia crowd.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  11%|██▉                        | 111/1000 [03:03<29:20,  1.98s/it]

[111/1000]
EN: Rohit Sharma warned India that confidence alone would not win against Pakistan.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  11%|███                        | 112/1000 [03:05<28:58,  1.96s/it]

[112/1000]
EN: Rohit Sharma urged India to approach Pakistan with discipline, planning, and composure.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  11%|███                        | 113/1000 [03:07<30:29,  2.06s/it]

[113/1000]
EN: Rohit Sharma cautioned that India–Pakistan games can ignore rankings and recent form.
ASM: . জেৱাৰ বিদৰে র্দেলি দীৱেৰিলাৰ ৰামি्लॆ বারে, āৰু പ്ৰা ्रॆक्कुपিৰचर яৰ ) а : ायो- ; ?
--------------------------------------------------

Translating:  11%|███                        | 114/1000 [03:08<26:40,  1.81s/it]

[114/1000]
EN: Rohit Sharma stressed mental readiness for India before the Pakistan contest.
ASM: দেৱাৰ বির্জীৰ ৰালাৰে জিলে,.
--------------------------------------------------

Translating:  12%|███                        | 115/1000 [03:10<26:37,  1.80s/it]

[115/1000]
EN: Rohit Sharma advised India to avoid underestimating Pakistan in the World Cup clash.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰিলাৰু. : ?
--------------------------------------------------

Translating:  12%|███▏                       | 116/1000 [03:12<26:13,  1.78s/it]

[116/1000]
EN: Virat Kohli congratulated India’s Under-19 team after the World Cup final victory.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰা লাৰি्लॆ а : ?
--------------------------------------------------

Translating:  12%|███▏                       | 117/1000 [03:13<23:48,  1.62s/it]

[117/1000]
EN: India’s Under-19 team won the ICC Under-19 Cricket World Cup final by 100 runs against England.
ASM: দেৱাৰ বির্জীৰ ৰিলে, বাৰে 1 - 1-.
--------------------------------------------------

Translating:  12%|███▏                       | 118/1000 [03:15<24:15,  1.65s/it]

[118/1000]
EN: India secured a sixth Under-19 World Cup title with a commanding final performance.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰিলাৰু āৰা а : ?-.
--------------------------------------------------

Translating:  12%|███▏                       | 119/1000 [03:17<27:09,  1.85s/it]

[119/1000]
EN: Celebrations followed India’s Under-19 World Cup triumph over England in the title match.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মিৰি লাৰু āৰা а - яৰ विरोधी জেৰ तिकिल् പवे 49 রিন্দৰ स्बराज ।
--------------------------------------------------

Translating:  12%|███▏                       | 120/1000 [03:19<27:04,  1.85s/it]

[120/1000]
EN: India’s Under-19 success drew praise from senior players across Indian cricket.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি विरोधी লাৰু പ്ৰা āৰचर а : ?
--------------------------------------------------

Translating:  12%|███▎                       | 121/1000 [03:21<26:52,  1.83s/it]

[121/1000]
EN: Dhakshineswar Suresh sparked optimism by delivering a breakthrough stretch for Indian tennis.
ASM: দৰি জেৱাৰ বিরীৰ ৰালে,.
--------------------------------------------------

Translating:  12%|███▎                       | 122/1000 [03:22<24:31,  1.68s/it]

[122/1000]
EN: Dhakshineswar Suresh’s rise has renewed ambition among Indian tennis fans and young players.
ASM: দৰে জাৰি বিরীৱাৰৰ লিলাৰ মি,.
--------------------------------------------------

Translating:  12%|███▎                       | 123/1000 [03:24<24:41,  1.69s/it]

[123/1000]
EN: Dhakshineswar Suresh’s recent results were described as a turning point for Indian tennis.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  12%|███▎                       | 124/1000 [03:26<26:20,  1.80s/it]

[124/1000]
EN: Dhakshineswar Suresh’s performances lifted expectations for Indian tennis on bigger stages.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  12%|███▍                       | 125/1000 [03:28<27:21,  1.88s/it]

[125/1000]
EN: Dhakshineswar Suresh’s run created fresh belief about India’s potential in men’s tennis.
ASM: দেৱাৰ বির্জীৱে. :  )-, ; লাৰিলি বাৰে ৰাদৰা জুৱিৰম പ്ः ायोᱹ ā ।
--------------------------------------------------

Translating:  13%|███▍                       | 126/1000 [03:30<27:16,  1.87s/it]

[126/1000]
EN: India’s men’s team exited in the quarterfinals at the Badminton Asia Team Championships.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  13%|███▍                       | 127/1000 [03:32<27:07,  1.86s/it]

[127/1000]
EN: India’s women’s team exited in the quarterfinals at the Badminton Asia Team Championships.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  13%|███▍                       | 128/1000 [03:33<23:54,  1.65s/it]

[128/1000]
EN: India failed to defend titles after a double quarterfinal exit in the team championships.
ASM: দেৱাৰ বির্জীৱে জিৰি ৰালে,.
--------------------------------------------------

Translating:  13%|███▍                       | 129/1000 [03:34<23:14,  1.60s/it]

[129/1000]
EN: Strong opposition ended India’s campaign early at the Badminton Asia Team Championships.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  13%|███▌                       | 130/1000 [03:35<21:45,  1.50s/it]

[130/1000]
EN: The quarterfinal losses ended India’s hopes of a title defence at the event.
ASM: দেৱাৰ বিজৰ ৰর্দৰে.
--------------------------------------------------

Translating:  13%|███▌                       | 131/1000 [03:36<18:56,  1.31s/it]

[131/1000]
EN: Sumit Nagal was scheduled to open his tournament campaign against Guy Den Ouden.
ASM: দেৱাৰ বির্জে জীৱaৰ ৰিলে,.
--------------------------------------------------

Translating:  13%|███▌                       | 132/1000 [03:37<16:27,  1.14s/it]

[132/1000]
EN: Sumit Nagal drew Dutch player Guy Den Ouden in an opening-round matchup.
ASM: দেৱাৰ বির্জীৰ ৰিলা জিৰি,.
--------------------------------------------------

Translating:  13%|███▌                       | 133/1000 [03:38<17:33,  1.21s/it]

[133/1000]
EN: Sumit Nagal’s first-round pairing set up an early test against Guy Den Ouden.
ASM: দেৱাৰ বির্জীৱে,.
--------------------------------------------------

Translating:  13%|███▌                       | 134/1000 [03:40<17:34,  1.22s/it]

[134/1000]
EN: Sumit Nagal prepared for a fresh challenge against Guy Den Ouden in round one.
ASM: দেৱাৰ বির্জে বাৰে, জীৱি লিলাৰ ৰাদৰা. : ?
--------------------------------------------------

Translating:  14%|███▋                       | 135/1000 [03:40<15:34,  1.08s/it]

[135/1000]
EN: Sumit Nagal began a new event with an opening match against Guy Den Ouden.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  14%|███▋                       | 136/1000 [03:42<16:38,  1.16s/it]

[136/1000]
EN: An analysis said T20 cricket keeps evolving through new strategies and fast-changing trends.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মি 5 জিৰি লাৰু āৰা яৰचर а : ?
--------------------------------------------------

Translating:  14%|███▋                       | 137/1000 [03:43<17:51,  1.24s/it]

[137/1000]
EN: A feature noted the ICC Men's T20 World Cup returned to India after a decade-long gap.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে মি জিৰি 20 লাৰু яৰ ) атиৰা мо : ?
--------------------------------------------------

Translating:  14%|███▋                       | 138/1000 [03:45<21:34,  1.50s/it]

[138/1000]
EN: T20 cricket was described as a format that continually reinvents tactics and team plans.
ASM: দেৱাৰ বির্জীৰ ৰিলে জিৰে, বাৰি মি 5 লাৰু яৰ ) атиৰা меৰ तिक  गोंधळরি विरोधी āৰचर പ്ৰराज ন্দatৰ सब ।
--------------------------------------------------

Translating:  14%|███▊                       | 139/1000 [03:47<21:14,  1.48s/it]

[139/1000]
EN: A commentary highlighted how technology and data shape modern T20 decision-making.
ASM: . দৰে জাৰি বিরীৱাৰৰ লিমি 20 ৰালাৰ বাৰ্দে, яৰ स्बराज ;
--------------------------------------------------

Translating:  14%|███▊                       | 140/1000 [03:48<21:32,  1.50s/it]

[140/1000]
EN: A tournament preview underlined T20 cricket’s cultural impact and mass appeal in India.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 20 লাৰু яৰ ) атеৰা мо : ?
--------------------------------------------------

Translating:  14%|███▊                       | 141/1000 [03:50<22:35,  1.58s/it]

[141/1000]
EN: Kapil Dev was listed among participants at the PM Rungta Memorial Golf Cup in Jaipur.
ASM: দেৱাৰ বির্জীৱে বাৰে, লিৰি জিমিলাৰ ৰাদৰা āৰু  तिकुपিন্দ ) क्कूटি्लॆ маꯔꯤ яৰ विरोधी  गोंधळরি কৰat ।
--------------------------------------------------

Translating:  14%|███▊                       | 142/1000 [03:51<21:33,  1.51s/it]

[142/1000]
EN: Madan Lal was listed among participants at the PM Rungta Memorial Golf Cup in Jaipur.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  14%|███▊                       | 143/1000 [03:53<20:55,  1.46s/it]

[143/1000]
EN: The PM Rungta Memorial Golf Cup was scheduled for February 8, 2026 in Jaipur.
ASM: জেৱাৰ বিদৰে রীৱিলাৰ ৰালে ।
--------------------------------------------------

Translating:  14%|███▉                       | 144/1000 [03:54<20:20,  1.43s/it]

[144/1000]
EN: Rambagh Golf Club was named as the venue for the memorial golf tournament.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  14%|███▉                       | 145/1000 [03:55<17:29,  1.23s/it]

[145/1000]
EN: Organisers said the golf cup used a Stableford Single Peoria format for inclusive competition.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  15%|███▉                       | 146/1000 [03:56<18:04,  1.27s/it]

[146/1000]
EN: A schedule note said United States would face Netherlands in Chennai to close February 13’s action.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি्लॆ লাৰু പ് а : ?
--------------------------------------------------

Translating:  15%|███▉                       | 147/1000 [03:58<18:47,  1.32s/it]

[147/1000]
EN: The USA–Netherlands match was presented as important for points and pride in the group.
ASM: দেৱাৰ বির্জি  :  ) বাৰে জীৱলৰ ৰামি, লাৰ तिकৰা āৰু പ്ৰিন্দিৰ रा चॆप्टम्पर् ма :
--------------------------------------------------

Translating:  15%|███▉                       | 148/1000 [03:58<16:23,  1.15s/it]

[148/1000]
EN: A match preview framed USA against Netherlands as a tight contest between associate nations.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  15%|████                       | 149/1000 [04:00<18:40,  1.32s/it]

[149/1000]
EN: A schedule roundup highlighted February 13 fixtures as key for shaping group standings.
ASM: দেৱাৰ বির্জীৰ ৰালি 13 বাৰে মি জিৰিলাৰু āৰা പ്রে, яৰ 11  एतेऩुम् ма वरकु ।
--------------------------------------------------

Translating:  15%|████                       | 150/1000 [04:02<20:42,  1.46s/it]

[150/1000]
EN: A preview said the final February 13 match would be played at MA Chidambaram Stadium.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মি 13 জিৰি লাৰু āৰা রিন্দৰ ) പ്ৰ तिकिल् атеৰ ।
--------------------------------------------------

Translating:  15%|████                       | 151/1000 [04:03<20:00,  1.41s/it]

[151/1000]
EN: Indian Super League clubs requested a pause on relegation for three to five years.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  15%|████                       | 152/1000 [04:05<19:51,  1.41s/it]

[152/1000]
EN: ISL clubs argued that pausing relegation would provide stability for long-term planning.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  15%|████▏                      | 153/1000 [04:06<19:57,  1.41s/it]

[153/1000]
EN: Several ISL teams asked administrators to consider a temporary relegation freeze.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  15%|████▏                      | 154/1000 [04:07<19:46,  1.40s/it]

[154/1000]
EN: The request on relegation was framed as a measure to protect club investments.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  16%|████▏                      | 155/1000 [04:09<19:16,  1.37s/it]

[155/1000]
EN: ISL stakeholders debated relegation rules while seeking clarity for the 2025–26 season.
ASM: . দেৱাৰ বির্জীৰ ৰালাৰে লিমি জিৰি কৰা ।
--------------------------------------------------

Translating:  16%|████▏                      | 156/1000 [04:09<16:52,  1.20s/it]

[156/1000]
EN: India produced a 3–2 win over Netherlands in Davis Cup Qualifiers Round 1.
ASM: দেৱাৰ বিরী 1 ৰাজে 3 : ?-.
--------------------------------------------------

Translating:  16%|████▏                      | 157/1000 [04:11<17:45,  1.26s/it]

[157/1000]
EN: India advanced to the second Davis Cup qualifying round after beating Netherlands 3–2.
ASM: . দেৱাৰ বির্জী 3 জিৰে বাৰি লিমিলাৰ ৰাদৰুৱে, āৰা а : ?
--------------------------------------------------

Translating:  16%|████▎                      | 158/1000 [04:12<18:35,  1.33s/it]

[158/1000]
EN: India’s Davis Cup team was described as thriving against higher-ranked opponents recently.
ASM: দেৱাৰ বিজৰ ৰারে.
--------------------------------------------------

Translating:  16%|████▎                      | 159/1000 [04:14<18:14,  1.30s/it]

[159/1000]
EN: The Davis Cup tie at SM Krishna Tennis Stadium went down to the wire.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  16%|████▎                      | 160/1000 [04:15<19:22,  1.38s/it]

[160/1000]
EN: India’s Davis Cup success followed an earlier victory over Switzerland in Biel last year.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  16%|████▎                      | 161/1000 [04:17<19:43,  1.41s/it]

[161/1000]
EN: The India Open was kept as a Super 750 tournament for the 2027–2030 cycle.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মিৰি জেৰা লাৰু പ് 2027 ाय़-2030 ।
--------------------------------------------------

Translating:  16%|████▎                      | 162/1000 [04:18<20:51,  1.49s/it]

[162/1000]
EN: Players criticised conditions, yet organisers retained the India Open’s Super 750 status.
ASM: . দেৱাৰ বির্জীৱে জিমি লাৰিলে ।
--------------------------------------------------

Translating:  16%|████▍                      | 163/1000 [04:20<20:21,  1.46s/it]

[163/1000]
EN: Badminton World Federation announced a revamped World Tour structure with six tournament levels.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  16%|████▍                      | 164/1000 [04:21<19:26,  1.40s/it]

[164/1000]
EN: The BWF updated World Tour plan included 36 tournaments across multiple tiers.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লামি ; а : ?
--------------------------------------------------

Translating:  16%|████▍                      | 165/1000 [04:23<21:23,  1.54s/it]

[165/1000]
EN: The BWF said annual World Tour prize money would rise to about 26.9 million dollars.
ASM: . দৰিরে জাৱাৰ বিলে, মিৰীৰে ৰাদেৰ্লাৰ কৰা বাৰু রিন্দ ) പ्लॆक्कूटে विरोधी а 69.9 लाख ।
--------------------------------------------------

Translating:  17%|████▍                      | 166/1000 [04:25<22:20,  1.61s/it]

[166/1000]
EN: A schedule preview listed Sri Lanka against Oman as a February 12 group-stage fixture.
ASM: . দৰে জাৰি বিরীৱাৰৰ লালে, а : ?
--------------------------------------------------

Translating:  17%|████▌                      | 167/1000 [04:26<22:45,  1.64s/it]

[167/1000]
EN: A schedule preview listed Nepal against Italy as a February 12 group-stage fixture.
ASM: . দৰে জাৰি বিরীৱাৰৰ ৰালাৰ মিলি, а বাৰা яৰ্দেৰু āৰat घटनुप 49 রিন্দিৰ तिक  एतेऩुम् 1 : ?
--------------------------------------------------

Translating:  17%|████▌                      | 168/1000 [04:28<21:33,  1.55s/it]

[168/1000]
EN: A schedule preview listed India against Namibia as a February 12 group-stage fixture.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 1 লাৰ तिकৰা а : ?
--------------------------------------------------

Translating:  17%|████▌                      | 169/1000 [04:29<21:22,  1.54s/it]

[169/1000]
EN: Wanindu Hasaranga was ruled out of the World Cup due to an injury setback.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  17%|████▌                      | 170/1000 [04:31<20:51,  1.51s/it]

[170/1000]
EN: Sri Lanka named Dushan Hemantha as a replacement after Wanindu Hasaranga’s injury.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  17%|████▌                      | 171/1000 [04:32<20:20,  1.47s/it]

[171/1000]
EN: The Indian Super League season was announced to begin on February 14, 2026.
ASM: দেৱাৰ বিজৰ ৰারে লাৰিলে, জীৱিৰ্দৰা বাৰু মি āৰে ; а- 2026 ।
--------------------------------------------------

Translating:  17%|████▋                      | 172/1000 [04:33<20:13,  1.47s/it]

[172/1000]
EN: Sports minister Mansukh Mandaviya announced an ISL start date of February 14.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লাৰু মি विरोधी āৰা রি्लॆ  वसूल समारंभ പ് : ?
--------------------------------------------------

Translating:  17%|████▋                      | 173/1000 [04:35<20:34,  1.49s/it]

[173/1000]
EN: All 14 clubs agreed to participate in the Indian Super League season, according to reports.
ASM: দেৱাৰ বির্জীৰ ৰিলে জিৰে, āৰি লাৰু মি विरोधी বাদৰা яৰ्लॆ പ് 14 маꯔꯤ ।
--------------------------------------------------

Translating:  17%|████▋                      | 174/1000 [04:37<22:32,  1.64s/it]

[174/1000]
EN: The ISL decision followed meetings between the sports ministry and the All India Football Federation.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  18%|████▋                      | 175/1000 [04:39<22:32,  1.64s/it]

[175/1000]
EN: Indian football’s top-tier season moved forward after clubs accepted the participation plan.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  18%|████▊                      | 176/1000 [04:40<20:15,  1.48s/it]

[176/1000]
EN: India’s women lost 0–3 to China in the Badminton Asia Team Championships quarterfinals.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি 0 : ?
--------------------------------------------------

Translating:  18%|████▊                      | 177/1000 [04:41<20:35,  1.50s/it]

[177/1000]
EN: P. V. Sindhu missed the team quarterfinal because of a minor injury, according to reports.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  18%|████▊                      | 178/1000 [04:43<20:35,  1.50s/it]

[178/1000]
EN: India’s women struggled to defend the 2024 title without PV Sindhu in the lineup.
ASM: . দেৱাৰ বিজৰ ৰার্দৰে জীৱa লালে, বাৰি মিৰা āৰু а 2024 яৰ तिकৰक्क мо : ?
--------------------------------------------------

Translating:  18%|████▊                      | 179/1000 [04:44<20:14,  1.48s/it]

[179/1000]
EN: China ended India’s women’s title defence with a straight 3–0 quarterfinal win.
ASM: . দেৱাৰ বিজৰী র্দৰে বাৰি লি, জিমিলাৰ ৰান্দ ) ।
--------------------------------------------------

Translating:  18%|████▊                      | 180/1000 [04:46<19:47,  1.45s/it]

[180/1000]
EN: The quarterfinal defeat closed India’s women’s campaign at the Badminton Asia Team Championships.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  18%|████▉                      | 181/1000 [04:47<19:01,  1.39s/it]

[181/1000]
EN: Devika Sihag won the Thailand Masters 2026 to claim a BWF Super 300 title.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 3 2026 а : ?
--------------------------------------------------

Translating:  18%|████▉                      | 182/1000 [04:48<19:13,  1.41s/it]

[182/1000]
EN: Devika Sihag became the youngest Indian woman to win a BWF Super 300 singles title.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি 3 300 āৰি জিৰা লাৰু яৰ्लॆ а : ?
--------------------------------------------------

Translating:  18%|████▉                      | 183/1000 [04:49<17:56,  1.32s/it]

[183/1000]
EN: Devika Sihag joined Saina Nehwal and PV Sindhu in an exclusive Indian milestone list.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  18%|████▉                      | 184/1000 [04:51<18:52,  1.39s/it]

[184/1000]
EN: Devika Sihag’s Bangkok celebration marked a breakthrough moment for Indian women’s singles.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  18%|████▉                      | 185/1000 [04:53<20:06,  1.48s/it]

[185/1000]
EN: Devika Sihag’s title was described as a quiet announcement of a new Indian badminton star.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  19%|█████                      | 186/1000 [04:54<20:18,  1.50s/it]

[186/1000]
EN: A matchday note listed Afghanistan against South Africa in Ahmedabad on February 11.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি 11 মি লাৰু রিন্দৰা  वसूल विरोधी āৰायला പ് तिक ।
--------------------------------------------------

Translating:  19%|█████                      | 187/1000 [04:55<19:11,  1.42s/it]

[187/1000]
EN: A matchday note listed Australia against Ireland as another February 11 group-stage fixture.
ASM: দেৱাৰ বির্জীৱেৰে বাৰি জিলে, লামি 11 а.
--------------------------------------------------

Translating:  19%|█████                      | 188/1000 [04:57<18:28,  1.37s/it]

[188/1000]
EN: A matchday note listed England against West Indies as a February 11 evening fixture.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মি 11 জিৰি লাৰু āৰা а : ?
--------------------------------------------------

Translating:  19%|█████                      | 189/1000 [04:58<19:40,  1.46s/it]

[189/1000]
EN: Afghanistan sought a rebound after losing their opener against New Zealand, according to reports.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  19%|█████▏                     | 190/1000 [05:00<21:45,  1.61s/it]

[190/1000]
EN: The February 11 schedule mixed former champions, contenders, and dangerous underdogs in group play.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মি 11 জিৰি লাৰু яৰ ) атি समारंभ āৰা പ് तिकिल्आ?
--------------------------------------------------

Translating:  19%|█████▏                     | 191/1000 [05:02<20:25,  1.51s/it]

[191/1000]
EN: Baichung Bhutia blamed administration after Churchill Brothers were not added to ISL 2025–26.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মিলাৰি জিন্দৰা а 2025 : ?
--------------------------------------------------

Translating:  19%|█████▏                     | 192/1000 [05:03<19:30,  1.45s/it]

[192/1000]
EN: Churchill Brothers were not included in ISL 2025–26, prompting criticism from Baichung Bhutia.
ASM: . দৰিরে জাৱাৰ বিলে, মিীৰে ৰাদেৰ্লা বাৰু а : ?
--------------------------------------------------

Translating:  19%|█████▏                     | 193/1000 [05:04<17:58,  1.34s/it]

[193/1000]
EN: Baichung Bhutia called the Churchill Brothers exclusion a clear administrative failure.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  19%|█████▏                     | 194/1000 [05:05<18:21,  1.37s/it]

[194/1000]
EN: The Churchill Brothers decision raised questions about the league’s selection and governance.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  20%|█████▎                     | 195/1000 [05:07<19:42,  1.47s/it]

[195/1000]
EN: The ISL debate intensified after the Churchill Brothers issue surfaced in public comments.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  20%|█████▎                     | 196/1000 [05:09<21:25,  1.60s/it]

[196/1000]
EN: India–Netherlands Davis Cup tie tightened after Sumit Nagal suffered a setback.
ASM: দেৱাৰ বির্জীৱে বাৰে, লিমি জিলাৰ ৰাদৰা āৰি কৰু яৰ ) പवेৰ तिकिल् атি्लॆ ন্দিৰরি विरोधी омিावन  गोंधळরে?
--------------------------------------------------

Translating:  20%|█████▎                     | 197/1000 [05:10<20:12,  1.51s/it]

[197/1000]
EN: Sumit Nagal’s result added pressure as the Davis Cup tie moved toward a tense finish.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  20%|█████▎                     | 198/1000 [05:12<19:18,  1.44s/it]

[198/1000]
EN: India and Netherlands remained locked in a close Davis Cup contest after the Nagal match.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  20%|█████▎                     | 199/1000 [05:13<19:58,  1.50s/it]

[199/1000]
EN: The Davis Cup tie needed late composure after the Sumit Nagal setback, according to reports.
ASM: দেৱাৰ বির্জীৱে,.
--------------------------------------------------

Translating:  20%|█████▍                     | 200/1000 [05:15<19:13,  1.44s/it]

[200/1000]
EN: The Bengaluru Davis Cup atmosphere stayed intense as India fought Netherlands in a tight tie.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে লাৰি মিৰু জিন্দৰা. : ?
--------------------------------------------------

Translating:  20%|█████▍                     | 201/1000 [05:16<17:58,  1.35s/it]

[201/1000]
EN: International Cricket Council confirmed the 2026 Men’s T20 World Cup starts on February 7.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে 5 20 লাৰি а : ?
--------------------------------------------------

Translating:  20%|█████▍                     | 202/1000 [05:17<18:40,  1.40s/it]

[202/1000]
EN: India were placed in Group A alongside Pakistan, Netherlands, USA, and Namibia.
ASM: . দৰে জাৰি বিরীৱাৰৰ লিমিলাৰ বাৰ্দেৰা പ്ৰু āৰat яৰ तिक а : .-,ᱹ.
--------------------------------------------------

Translating:  20%|█████▍                     | 203/1000 [05:19<19:35,  1.47s/it]

[203/1000]
EN: Sri Lanka hosted several matches as the tournament ran across India and Sri Lanka venues.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  20%|█████▌                     | 204/1000 [05:20<18:29,  1.39s/it]

[204/1000]
EN: India played the opening match against the USA at Wankhede Stadium in Mumbai.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  20%|█████▌                     | 205/1000 [05:21<16:58,  1.28s/it]

[205/1000]
EN: India faced Namibia on February 12 at Arun Jaitley Stadium in New Delhi.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে а : ?-.
--------------------------------------------------

Translating:  21%|█████▌                     | 206/1000 [05:22<17:15,  1.30s/it]

[206/1000]
EN: India travelled to Colombo to play Pakistan in a group-stage match.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  21%|█████▌                     | 207/1000 [05:24<17:32,  1.33s/it]

[207/1000]
EN: Pakistan versus Netherlands was listed as a Group A fixture on February 7.
ASM: . দেৱাৰ বির্জীৰ ৰালা জিলে, বাৰে а : ?
--------------------------------------------------

Translating:  21%|█████▌                     | 208/1000 [05:25<17:38,  1.34s/it]

[208/1000]
EN: India versus USA was scheduled as a Group A match on February 7.
ASM: . দেৱাৰ বির্জে বাৰি জীৱaৰ ৰালে ।
--------------------------------------------------

Translating:  21%|█████▋                     | 209/1000 [05:27<18:44,  1.42s/it]

[209/1000]
EN: Group D fixtures began with Afghanistan playing New Zealand on February 8 in Chennai.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি 8 জিৰি লাৰু āৰা রিন্দৰ तिकिल् атি्लॆ?
--------------------------------------------------

Translating:  21%|█████▋                     | 210/1000 [05:28<17:10,  1.31s/it]

[210/1000]
EN: Canada played South Africa on February 9 at Narendra Modi Stadium in Ahmedabad.
ASM: . দৰিরে জাৱাৰ বীৱেৰে, а : ?
--------------------------------------------------

Translating:  21%|█████▋                     | 211/1000 [05:30<18:51,  1.43s/it]

[211/1000]
EN: Ishan Kishan smashed 61 off 24 balls against Namibia in New Delhi.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে মিৰি লাৰু জেৰা പ് : ?
--------------------------------------------------

Translating:  21%|█████▋                     | 212/1000 [05:31<20:09,  1.53s/it]

[212/1000]
EN: Hardik Pandya featured prominently as India posted 209 for nine against Namibia.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে জিৰিমি লাৰ तिकৰা āৰু а : я- ) ।
--------------------------------------------------

Translating:  21%|█████▊                     | 213/1000 [05:33<20:48,  1.59s/it]

[213/1000]
EN: Varun Chakaravarthy took three wickets as India beat Namibia by 93 runs.
ASM: দেৱাৰ বিজৰ ৰর্দৰে জীৱেৰিলে, বাৰু লাৰা মি āৰ विरोधी а : ?
--------------------------------------------------

Translating:  21%|█████▊                     | 214/1000 [05:35<22:26,  1.71s/it]

[214/1000]
EN: India bundled out Namibia for 116 while defending a target of 210.
ASM: . দৰিরে জাৱাৰ বীৱেৰে, аᱹ ab ।
--------------------------------------------------

Translating:  22%|█████▊                     | 215/1000 [05:37<22:30,  1.72s/it]

[215/1000]
EN: Namibia captain Gerhard Erasmus won the toss and chose to bat first.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  22%|█████▊                     | 216/1000 [05:38<22:10,  1.70s/it]

[216/1000]
EN: India versus Namibia started at 7:00 PM IST at Arun Jaitley Stadium.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মিলাৰি জিদৰা പ് : ?
--------------------------------------------------

Translating:  22%|█████▊                     | 217/1000 [05:40<23:21,  1.79s/it]

[217/1000]
EN: India’s first match was a win against the USA in Mumbai.
ASM: . দেৱাৰ বির্জীৰ ৰালা জিলে, বাৰে মি āৰি विरोधी яৰু പ്ৰা क्कूटি्लॆ  वसूल ج ) ।
--------------------------------------------------

Translating:  22%|█████▉                     | 218/1000 [05:42<21:33,  1.65s/it]

[218/1000]
EN: India versus Namibia was labelled as game 18 of the tournament.
ASM: . দেৱাৰ বিজৰ ৰারে জীৱিলা বাৰিলে, মি 18 :
--------------------------------------------------

Translating:  22%|█████▉                     | 219/1000 [05:44<22:21,  1.72s/it]

[219/1000]
EN: Suryakumar Yadav led India against Namibia in the ongoing T20 World Cup.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি 20 মি विरोधी লাৰু яৰ तिकिल् āৰা а : ?
--------------------------------------------------

Translating:  22%|█████▉                     | 220/1000 [05:45<21:03,  1.62s/it]

[220/1000]
EN: India entered the Namibia match after beating the USA in their opener.
ASM: দেৱাৰ বির্জীৱে লি ৰাদৰে, বাৰি জিমিৰু...
--------------------------------------------------

Translating:  22%|█████▉                     | 221/1000 [05:47<21:15,  1.64s/it]

[221/1000]
EN: The Pakistan government allowed the Pakistan team to play India on February 15.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 15 : ?
--------------------------------------------------

Translating:  22%|█████▉                     | 222/1000 [05:48<21:17,  1.64s/it]

[222/1000]
EN: India versus Pakistan was scheduled for Colombo after weeks of uncertainty.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  22%|██████                     | 223/1000 [05:49<19:06,  1.48s/it]

[223/1000]
EN: India versus Pakistan was described as a group-stage match in Colombo.
ASM: দৰি জেৱাৰ বির্রীৰ ৰালা,.
--------------------------------------------------

Translating:  22%|██████                     | 224/1000 [05:51<20:05,  1.55s/it]

[224/1000]
EN: The tournament was listed as featuring 55 matches across India and Sri Lanka.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে а : ?
--------------------------------------------------

Translating:  22%|██████                     | 225/1000 [05:53<20:46,  1.61s/it]

[225/1000]
EN: The schedule included Delhi, Kolkata, Ahmedabad, Chennai, Mumbai, Colombo, and Kandy venues.
ASM: দেৱাৰ  জির্বিলৰ ৰালাৰে বাৰি মি, ्रॆীৱেৰা āৰু яৰ ) а...
--------------------------------------------------

Translating:  23%|██████                     | 226/1000 [05:55<22:44,  1.76s/it]

[226/1000]
EN: Afghanistan faced New Zealand at M. A. Chidambaram Stadium with an 11:00 AM start.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মিৰি লাৰু জিন্দৰ )  गळिल् āৰা а 11:00 ।
--------------------------------------------------

Translating:  23%|██████▏                    | 227/1000 [05:57<23:46,  1.85s/it]

[227/1000]
EN: New Zealand played UAE on February 10 at M. A. Chidambaram Stadium.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে বাৰি লি, а জিমি विरोधी লাৰু яৰ तिकৰা क्कूटা ।
--------------------------------------------------

Translating:  23%|██████▏                    | 228/1000 [05:59<24:58,  1.94s/it]

[228/1000]
EN: Group D included UAE, New Zealand, South Africa, Afghanistan, and Canada in one pool.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  23%|██████▏                    | 229/1000 [06:01<22:43,  1.77s/it]

[229/1000]
EN: India’s group-stage route moved from Mumbai to Delhi and then Colombo.
ASM: দৰে জাৰি বিরীৰ. : ायो-, লাৰ ৰালিম ।
--------------------------------------------------

Translating:  23%|██████▏                    | 230/1000 [06:03<24:02,  1.87s/it]

[230/1000]
EN: The India versus Namibia match preview named Gerhard Erasmus as Namibia’s captain.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  23%|██████▏                    | 231/1000 [06:05<25:12,  1.97s/it]

[231/1000]
EN: A report said Abhishek Sharma underwent checks for a stomach bug in New Delhi.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  23%|██████▎                    | 232/1000 [06:07<26:20,  2.06s/it]

[232/1000]
EN: The same report said Abhishek Sharma missed India’s Namibia game despite hospital discharge.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  23%|██████▎                    | 233/1000 [06:09<23:45,  1.86s/it]

[233/1000]
EN: Sanju Samson’s World Cup debut was described as lasting only eight deliveries.
ASM: দেৱাৰ বির্জে.
--------------------------------------------------

Translating:  23%|██████▎                    | 234/1000 [06:10<22:52,  1.79s/it]

[234/1000]
EN: The tournament’s Group A opened across venues in India and Sri Lanka.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  24%|██████▎                    | 235/1000 [06:12<21:15,  1.67s/it]

[235/1000]
EN: India’s match against Namibia was played on Thursday, February 12.
ASM: . দেৱাৰ বির্জীৱিলাৰ ৰালে, বাৰে জিমি āৰি 1 а : ?
--------------------------------------------------

Translating:  24%|██████▎                    | 236/1000 [06:13<20:50,  1.64s/it]

[236/1000]
EN: Nepal versus Italy appeared as a live-score fixture during the T20 World Cup schedule.
ASM: . দৰিরে জাৱাৰ বীৱেৰে, লিলাৰ ৰামি বাৰু āৰা abি विरोधी 20 яৰ तिकৰ্ बिरोधी а : ?
--------------------------------------------------

Translating:  24%|██████▍                    | 237/1000 [06:15<20:23,  1.60s/it]

[237/1000]
EN: Australia versus Zimbabwe appeared as a live-score fixture on the Indian Express cricket feed.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  24%|██████▍                    | 238/1000 [06:17<21:11,  1.67s/it]

[238/1000]
EN: The Indian Express sports section highlighted India’s 93-run win over Namibia.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে বাৰি জিলে, а-ᱹ āৰু লা तिकৰা মি विरोधी яৰ ) ।
--------------------------------------------------

Translating:  24%|██████▍                    | 239/1000 [06:18<20:22,  1.61s/it]

[239/1000]
EN: The match report said India’s bowling attack dismantled Namibia during the chase.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  24%|██████▍                    | 240/1000 [06:20<20:43,  1.64s/it]

[240/1000]
EN: The India versus Namibia highlights credited Ishan Kishan’s 61 with driving India’s total.
ASM: . দেৱাৰ বির্জীৰ ৰিলে জিৰে, বাৰি মি विरोधी লাৰু রিন্দৰা പ്ৰ तिकिल् āৰचर а : ?
--------------------------------------------------

Translating:  24%|██████▌                    | 241/1000 [06:21<19:47,  1.57s/it]

[241/1000]
EN: ISL 2025–26 fixtures began on February 14 with a double-header format.
ASM: . দৰিরে জাৱাৰ বিলে, বাৰে ৰালাৰী പ് : ायो-ᱹ ;
--------------------------------------------------

Translating:  24%|██████▌                    | 242/1000 [06:22<18:45,  1.48s/it]

[242/1000]
EN: Mohun Bagan Super Giant faced Kerala Blasters in the season opener in Kolkata.
ASM: দৰে জাৰি বিরীৱাৰৰ লিমিৰ.
--------------------------------------------------

Translating:  24%|██████▌                    | 243/1000 [06:24<18:44,  1.49s/it]

[243/1000]
EN: FC Goa hosted Inter Kashi at Fatorda Stadium on February 14.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লাৰু মিक्कूटেৰা āৰचर പ്ৰ विरोधी а : ?
--------------------------------------------------

Translating:  24%|██████▌                    | 244/1000 [06:25<19:17,  1.53s/it]

[244/1000]
EN: The first match on double-header days started at 5:00 PM IST.
ASM: . দৰে জিৱাৰ বিরীৰ ৰালে ।
--------------------------------------------------

Translating:  24%|██████▌                    | 245/1000 [06:27<18:46,  1.49s/it]

[245/1000]
EN: The second match on double-header days started at 7:30 PM IST.
ASM: . দৰে জাৰি বিরীৱাৰৰ লিমি, লাৰ্দেৰ বাৰু āৰা রে ৰা समारंभ а : ?
--------------------------------------------------

Translating:  25%|██████▋                    | 246/1000 [06:28<18:38,  1.48s/it]

[246/1000]
EN: A report said the ISL season would use a single-leg home-and-away format.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  25%|██████▋                    | 247/1000 [06:30<19:01,  1.52s/it]

[247/1000]
EN: The Indian Express football page reported FanCode won exclusive ISL media rights.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  25%|██████▋                    | 248/1000 [06:31<18:50,  1.50s/it]

[248/1000]
EN: The same report said ISL per-match valuation dropped by about 95 percent.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে а 95 জিমি  तिकৰিলা ।
--------------------------------------------------

Translating:  25%|██████▋                    | 249/1000 [06:32<16:21,  1.31s/it]

[249/1000]
EN: The ISL report described a truncated season with pay cuts at multiple clubs.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  25%|██████▊                    | 250/1000 [06:34<16:30,  1.32s/it]

[250/1000]
EN: Real Madrid CF hoped a La Liga surge was boosted by a team dinner.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  25%|██████▊                    | 251/1000 [06:35<17:40,  1.42s/it]

[251/1000]
EN: The Real Madrid dinner was reportedly paid for by Vinícius Júnior and Kylian Mbappé.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰা লাৰি কৰু রিন্দৰ तिक āৰat क्कूटি्लॆ яৰराज ;  :  ).
--------------------------------------------------

Translating:  25%|██████▊                    | 252/1000 [06:37<17:26,  1.40s/it]

[252/1000]
EN: Barcelona aimed for a fourth straight league win against Girona in La Liga.
ASM: দেৱাৰ বির্জে,.
--------------------------------------------------

Translating:  25%|██████▊                    | 253/1000 [06:38<17:06,  1.37s/it]

[253/1000]
EN: Barcelona visited Atlético Madrid for a Copa del Rey first-leg clash.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  25%|██████▊                    | 254/1000 [06:39<17:12,  1.38s/it]

[254/1000]
EN: Barcelona entered the Atlético Madrid match after winning 17 of 18 matches.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে বাৰি লিমি 17 লাৰু জিৰatৰ तिक āৰা а : ?
--------------------------------------------------

Translating:  26%|██████▉                    | 255/1000 [06:41<16:21,  1.32s/it]

[255/1000]
EN: Real Madrid and UEFA announced an agreement ending the Super League project.
ASM: দেৱাৰ বির্জীৱে বাৰি জিলে,.
--------------------------------------------------

Translating:  26%|██████▉                    | 256/1000 [06:42<17:30,  1.41s/it]

[256/1000]
EN: Barcelona formally pulled out of the Super League days before the agreement.
ASM: দৰে জাৰি বিরীৰ লিলাৰ ৰাদে,.
--------------------------------------------------

Translating:  26%|██████▉                    | 257/1000 [06:44<17:57,  1.45s/it]

[257/1000]
EN: Tottenham Hotspur reportedly sacked Thomas Frank after a 2–1 loss to Newcastle United.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে 1 জিৰি মিন্দৰা লাৰ तिकिल् āৰু  कावलি विरोधी а 2. ।
--------------------------------------------------

Translating:  26%|██████▉                    | 258/1000 [06:45<18:07,  1.47s/it]

[258/1000]
EN: The Tottenham report said the club still had no league win in 2026.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মিৰি লাৰু জিন্দৰা പ് 2026 ।
--------------------------------------------------

Translating:  26%|██████▉                    | 259/1000 [06:46<16:18,  1.32s/it]

[259/1000]
EN: Wayne Rooney said Arsenal looked mentally stronger in the Premier League title race.
ASM: দেৱাৰ বির্জে জীৱলৰ ৰালা বাৰে,.
--------------------------------------------------

Translating:  26%|███████                    | 260/1000 [06:48<17:12,  1.40s/it]

[260/1000]
EN: Rooney noted Arsenal last won the Premier League title in the 2003–04 season.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি 0 4 জিৰি লাৰু яৰ ) а-ᱹ : ?
--------------------------------------------------

Translating:  26%|███████                    | 261/1000 [06:49<17:00,  1.38s/it]

[261/1000]
EN: Rooney said Arsenal led Manchester City by six points with 13 games remaining.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লামি 13 āৰু а : ?
--------------------------------------------------

Translating:  26%|███████                    | 262/1000 [06:51<17:31,  1.43s/it]

[262/1000]
EN: Cristiano Ronaldo missed a second straight Saudi Pro League match for Al-Nassr.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  26%|███████                    | 263/1000 [06:52<18:20,  1.49s/it]

[263/1000]
EN: Al-Nassr beat Al-Ittihad 2–0 despite Cristiano Ronaldo’s continued absence.
ASM: . দেৱাৰ বির্জীৱে বাৰে 2 জিলে, а : ?
--------------------------------------------------

Translating:  26%|███████▏                   | 264/1000 [06:53<17:02,  1.39s/it]

[264/1000]
EN: Sadio Mané and Angelo Gabriel scored for Al-Nassr in the win over Al-Ittihad.
ASM: দেৱাৰ বির্জীৰ ৰালে, মি জিৰে লাৰি ;.
--------------------------------------------------

Translating:  26%|███████▏                   | 265/1000 [06:55<17:22,  1.42s/it]

[265/1000]
EN: Sumit Nagal headlined the Delhi Open 2026 at the DLTA Complex.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰিলাৰ ) പ് 2026 а : ?
--------------------------------------------------

Translating:  27%|███████▏                   | 266/1000 [06:56<16:11,  1.32s/it]

[266/1000]
EN: The Delhi Open 2026 tournament was scheduled for February 16 to 22.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে বাৰি 16 জিলে ।
--------------------------------------------------

Translating:  27%|███████▏                   | 267/1000 [06:58<17:18,  1.42s/it]

[267/1000]
EN: Britain’s Jay Clarke was named as a leading overseas entrant for Delhi Open 2026.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে লাৰি জিমিৰু പ്ᱹ а 2026 : ?
--------------------------------------------------

Translating:  27%|███████▏                   | 268/1000 [06:59<18:30,  1.52s/it]

[268/1000]
EN: The Delhi Open note said Sumit Nagal gained direct entry into the main draw.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  27%|███████▎                   | 269/1000 [07:01<18:03,  1.48s/it]

[269/1000]
EN: India beat the Netherlands 3–2 in Davis Cup competition to move closer.
ASM: . দেৱাৰ বির্জীৰ ৰালে 3, বাৰে জিমিৰি লা तिकৰা а : ?
--------------------------------------------------

Translating:  27%|███████▎                   | 270/1000 [07:02<18:02,  1.48s/it]

[270/1000]
EN: Dhakshineswar Suresh featured prominently during India’s Davis Cup tie against the Netherlands.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  27%|███████▎                   | 271/1000 [07:04<17:54,  1.47s/it]

[271/1000]
EN: India’s doubles pair beat David Pel and Sander Arends in a tight five-setter.
ASM: দেৱাৰ বির্জে.
--------------------------------------------------

Translating:  27%|███████▎                   | 272/1000 [07:05<17:31,  1.44s/it]

[272/1000]
EN: The doubles win was described as India’s first in five playoff ties versus Europeans.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  27%|███████▎                   | 273/1000 [07:06<15:21,  1.27s/it]

[273/1000]
EN: The same report said Sumit Nagal failed to seal the tie in reverse singles.
ASM: দেৱাৰ বিজৰ ৰার্দৰে জীৱে,.
--------------------------------------------------

Translating:  27%|███████▍                   | 274/1000 [07:08<16:28,  1.36s/it]

[274/1000]
EN: Novak Djokovic said he still wanted to represent Serbia in Davis Cup.
ASM: দেৱাৰ বির্জীৱে বাৰে, লিৰি জিমিলাৰ ৰাদৰা āৰু ्रॆकुपাৰৰ яৰ्लॆ  तिकৰायला ।
--------------------------------------------------

Translating:  28%|███████▍                   | 275/1000 [07:09<15:47,  1.31s/it]

[275/1000]
EN: Serbia captain Viktor Troicki described Novak Djokovic as a major team figure.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  28%|███████▍                   | 276/1000 [07:10<14:58,  1.24s/it]

[276/1000]
EN: Novak Djokovic withdrew from a 2025 Davis Cup qualifier due to a hamstring injury.
ASM: . দৰিরে জাৱাৰ বীৱেৰে ৰিলে, а 2025 : ?
--------------------------------------------------

Translating:  28%|███████▍                   | 277/1000 [07:12<18:30,  1.54s/it]

[277/1000]
EN: Carlos Alcaraz beat Alexander Zverev in a five-hour, 27-minute Australian Open semifinal.
ASM: দেৱাৰ বির্জীৱে জিলে, а --.
--------------------------------------------------

Translating:  28%|███████▌                   | 278/1000 [07:14<18:18,  1.52s/it]

[278/1000]
EN: Carlos Alcaraz won the Australian Open final after facing Novak Djokovic.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  28%|███████▌                   | 279/1000 [07:15<17:35,  1.46s/it]

[279/1000]
EN: Jannik Sinner was described as holding five straight wins over Novak Djokovic.
ASM: দেৱাৰ বির্জে জীৱে,.
--------------------------------------------------

Translating:  28%|███████▌                   | 280/1000 [07:16<16:36,  1.38s/it]

[280/1000]
EN: The Djokovic–Sinner preview said Djokovic reached semifinals aided by a walkover and retirement.
ASM: দেৱাৰ  জির্বিলৰ ৰালাৰে মিীৰি বারে, പ്.
--------------------------------------------------

Translating:  28%|███████▌                   | 281/1000 [07:17<14:25,  1.20s/it]

[281/1000]
EN: An Australian Open report said extreme heat forced temporary suspensions on outside courts.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  28%|███████▌                   | 282/1000 [07:18<14:51,  1.24s/it]

[282/1000]
EN: The same report said organisers issued heat warnings for players and spectators.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  28%|███████▋                   | 283/1000 [07:20<15:56,  1.33s/it]

[283/1000]
EN: Jannik Sinner beat Eliot Spizzirri 4–6, 6–3, 6–4, 6–4 in Melbourne.
ASM: দেৱাৰ বিজৰী র্দৰে বাৰি লি, জিমিলাৰ ৰান্দিৰা ायो ā.- ) яৰ विरोधी а?
--------------------------------------------------

Translating:  28%|███████▋                   | 284/1000 [07:21<16:02,  1.34s/it]

[284/1000]
EN: A tennis feature said Fangran Tian was coached by Chennai’s Mangal Sriram since age 12.
ASM: . দেৱাৰ বির্জীৱে জিলে, মি বাৰে ৰাদৰা লা तिकৰি 1 : ?
--------------------------------------------------

Translating:  28%|███████▋                   | 285/1000 [07:23<16:23,  1.38s/it]

[285/1000]
EN: Badminton World Federation demoted Syed Modi International from Super 300 to Super 100.
ASM: . দেৱাৰ বির্জীৰ 3 300 লিৰে জিলাৰ ৰাদৰা বাৰি, মি 100 āৰু яৰ 11
--------------------------------------------------

Translating:  29%|███████▋                   | 286/1000 [07:24<16:47,  1.41s/it]

[286/1000]
EN: The same report said India Open retained Super 750 status for the 2027–2030 cycle.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে а 2027-2030 ।
--------------------------------------------------

Translating:  29%|███████▋                   | 287/1000 [07:26<18:26,  1.55s/it]

[287/1000]
EN: A badminton reforms report said World Championships and five Super 1000s will run 11 days.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে লাৰি 11 1000 а জিমি āৰু яৰ ) പ്ৰা ab ।
--------------------------------------------------

Translating:  29%|███████▊                   | 288/1000 [07:27<17:53,  1.51s/it]

[288/1000]
EN: The Indian Express said BWF’s AGM 2026 would vote on a 3×15 scoring format.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে বাৰি লালে, 3 মিন্দিৰা പ് 2022 : ?-ᱹ.
--------------------------------------------------

Translating:  29%|███████▊                   | 289/1000 [07:28<15:41,  1.32s/it]

[289/1000]
EN: A Badminton Asia Team report said India lost 3–2 to Japan in men’s ties.
ASM: দেৱাৰ বির্জীৰ ৰালে বাৰে 3 : ?-.
--------------------------------------------------

Translating:  29%|███████▊                   | 290/1000 [07:30<15:47,  1.33s/it]

[290/1000]
EN: The same report said India lost to Thailand in women’s ties at the team event.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  29%|███████▊                   | 291/1000 [07:31<16:06,  1.36s/it]

[291/1000]
EN: A selection report said Tanvi Sharma would play first singles after Unnati Hooda was out.
ASM: দেৱাৰ বির্জীৱে,.
--------------------------------------------------

Translating:  29%|███████▉                   | 292/1000 [07:33<16:42,  1.42s/it]

[292/1000]
EN: An India Open report said “nest materials” halted a women’s doubles semifinal in Delhi.
ASM: . দেৱাৰ বির্জীৱে বাৰে, লিলাৰ ৰামি জিৰি्लॆ яৰু āৰা പ് तिकिल् а : ?- ;
--------------------------------------------------

Translating:  29%|███████▉                   | 293/1000 [07:34<17:28,  1.48s/it]

[293/1000]
EN: A feature said An Se-young won 94.8 percent of her matches in 2025.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰা লাৰি কৰa പ് 94.8 तिकৰু яৰ स्बराज ।
--------------------------------------------------

Translating:  29%|███████▉                   | 294/1000 [07:36<18:26,  1.57s/it]

[294/1000]
EN: The same feature said An Se-young began 2026 with two titles in two weeks.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰা লাৰি्लॆ а 2026?
--------------------------------------------------

Translating:  30%|███████▉                   | 295/1000 [07:37<16:39,  1.42s/it]

[295/1000]
EN: Lin Chun-yi beat Jonatan Christie 21–10, 21–18 in the India Open final.
ASM: দেৱাৰ বির্জীৰ ৰিলে, বাৰে ā 11- 0.
--------------------------------------------------

Translating:  30%|███████▉                   | 296/1000 [07:38<16:00,  1.36s/it]

[296/1000]
EN: Devika Sihag beat Navya Kanderi 21–10, 21–13 to win in Baku.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লাৰু ā 11-.
--------------------------------------------------

Translating:  30%|████████                   | 297/1000 [07:40<15:45,  1.35s/it]

[297/1000]
EN: Radhika Sharma won her first mixed doubles title partnering Sathwik Reddy.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  30%|████████                   | 298/1000 [07:41<16:06,  1.38s/it]

[298/1000]
EN: Ankur Bhattacharjee upset world-ranked opponent Bourrassaud 3–1 at WTT Chennai.
ASM: . দেৱাৰ বির্জী 3, বাৰে লি জিৰি 1 ৰাদৰা মি विरोधी āৰু লাৰ तिकৰ सब?
--------------------------------------------------

Translating:  30%|████████                   | 299/1000 [07:43<16:47,  1.44s/it]

[299/1000]
EN: FIFA president Gianni Infantino faced criticism over high-priced tickets for the 2026 World Cup.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰিলাৰু പ്ৰা āৰायला  गोंधळ्लॆ а 2026 : ?
--------------------------------------------------

Translating:  30%|████████                   | 300/1000 [07:44<17:51,  1.53s/it]

[300/1000]
EN: India lost 1-3 to Belgium in the FIH Pro League opener at Rourkela.
ASM: . দেৱাৰ বির্জীৰ ৰালে, জিৰে মি লাৰু বাৰি কৰা ।
--------------------------------------------------

Translating:  30%|████████▏                  | 301/1000 [07:46<17:27,  1.50s/it]

[301/1000]
EN: Craig Fulton said India’s defensive structure did not deliver in the Pro League opener.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  30%|████████▏                  | 302/1000 [07:47<17:16,  1.48s/it]

[302/1000]
EN: India then suffered a 0-8 loss to Argentina in the next Pro League match.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মি 0 - а.
--------------------------------------------------

Translating:  30%|████████▏                  | 303/1000 [07:49<16:43,  1.44s/it]

[303/1000]
EN: India’s 0-8 defeat was described as a systematic demolition by Argentina.
ASM: দেৱাৰ বির্জীৰ ৰালি, বাৰে জিৰি লাৰু মি 0 - 8 яৰ तिकৰা а.
--------------------------------------------------

Translating:  30%|████████▏                  | 304/1000 [07:50<16:26,  1.42s/it]

[304/1000]
EN: India’s 0-8 loss matched the joint third-worst defeat in India’s hockey history.
ASM: দেৱাৰ বিজৰ ৰার্দৰে জীৱেৰি লালে, বাৰু মি 0 - āৰা а.
--------------------------------------------------

Translating:  30%|████████▏                  | 305/1000 [07:51<15:33,  1.34s/it]

[305/1000]
EN: India’s other 0-8 losses came in 1985 versus Netherlands and 2010 versus Australia.
ASM: . বিৰে দৰি জাৱাৰ র্দেলৰ ৰালাৰ, а 0- 2010 :
--------------------------------------------------

Translating:  31%|████████▎                  | 306/1000 [07:52<14:59,  1.30s/it]

[306/1000]
EN: Argentina’s Tomas Domene scored four goals in the 0-8 win over India.
ASM: দেৱাৰ বির্জীৰ ৰালাৰে মি জিৰিলে ।
--------------------------------------------------

Translating:  31%|████████▎                  | 307/1000 [07:53<14:48,  1.28s/it]

[307/1000]
EN: Tomas Domene scored at 15th, 20th, 26th and 60th minutes against India.
ASM: দেৱাৰ বির্জীৰ ৰিলে, বাৰে মি 5 :  0-.
--------------------------------------------------

Translating:  31%|████████▎                  | 308/1000 [07:55<15:54,  1.38s/it]

[308/1000]
EN: Tomas Ruiz, Lucio Mendez, Ignacio Ibarra, and Nicolas della Torre also scored for Argentina.
ASM: দেৱাৰ বির্জে. :  )-, লাৰী বাৰে ৰালি জিৰিমৰ কৰা āৰু রিন্দৰ तिकिल् а..
--------------------------------------------------

Translating:  31%|████████▎                  | 309/1000 [07:56<14:04,  1.22s/it]

[309/1000]
EN: India’s third quarter without conceding a goal looked like an anomaly in the match.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  31%|████████▎                  | 310/1000 [07:57<14:59,  1.30s/it]

[310/1000]
EN: Player-of-the-Match Tomas Domene said Argentina played the whole game at 100 percent.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 100 লাৰ तिकৰা āৰু রিন্দৰ स्बराज ।
--------------------------------------------------

Translating:  31%|████████▍                  | 311/1000 [07:59<15:09,  1.32s/it]

[311/1000]
EN: Tomas Domene said Argentina were disappointed after losing 3-5 to Belgium previously.
ASM: দেৱাৰ বিজৰ ৰার্দৰে জীৱেৰি লালে, মি 3 - 5 : ?
--------------------------------------------------

Translating:  31%|████████▍                  | 312/1000 [08:00<14:12,  1.24s/it]

[312/1000]
EN: Argentina scored two quick goals at the end of the first quarter.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে লাৰি জিৰা. : ?
--------------------------------------------------

Translating:  31%|████████▍                  | 313/1000 [08:01<13:46,  1.20s/it]

[313/1000]
EN: Argentina scored five goals in 10 minutes during the second quarter.
ASM: দেৱাৰ বির্জীৱে জিৰি 10 লিমি লাৰে, а.
--------------------------------------------------

Translating:  31%|████████▍                  | 314/1000 [08:02<14:14,  1.25s/it]

[314/1000]
EN: Harmanpreet Singh missed two penalty strokes in the match against Argentina.
ASM: দেৱাৰ বির্জীৱে লিলাৰ ৰামি.
--------------------------------------------------

Translating:  32%|████████▌                  | 315/1000 [08:03<13:14,  1.16s/it]

[315/1000]
EN: India missed three penalty corners during the 0-8 defeat against Argentina.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে а 0-.
--------------------------------------------------

Translating:  32%|████████▌                  | 316/1000 [08:04<12:07,  1.06s/it]

[316/1000]
EN: India goalkeepers Suraj Karkera and Pawan looked completely out of place.
ASM: দেৱাৰ বিজৰ ৰারে জীৱে,.
--------------------------------------------------

Translating:  32%|████████▌                  | 317/1000 [08:05<11:21,  1.00it/s]

[317/1000]
EN: Argentina dominated possession and toyed with India’s midfield and defence.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  32%|████████▌                  | 318/1000 [08:07<14:18,  1.26s/it]

[318/1000]
EN: Argentina’s win catapulted them to fourth in the nine-team standings.
ASM: দেৱাৰ বির্জীৰ ৰিলে,  বাৰে লাৰি জিমিৰু āৰা പ്ৰ 49 яৰ विरोधी ्रॆक्कাদৰ तिक маৰ ।
--------------------------------------------------

Translating:  32%|████████▌                  | 319/1000 [08:08<15:41,  1.38s/it]

[319/1000]
EN: India next faced world No.2 Belgium again after the heavy Argentina loss.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি विरोधी লাৰু রিন্দৰা āৰ 4  कावलিावन പ്ৰक्क яৰ 11
--------------------------------------------------

Translating:  32%|████████▋                  | 320/1000 [08:10<17:21,  1.53s/it]

[320/1000]
EN: Macklin Celebrini scored early to spark Canada’s 5-0 win over Czech Republic.
ASM: দেৱাৰ বিজৰ ৰারে জীৱে, লিৰি বাৰে 5 - 0 : ?
--------------------------------------------------

Translating:  32%|████████▋                  | 321/1000 [08:11<15:47,  1.40s/it]

[321/1000]
EN: Macklin Celebrini scored with just over five seconds left in the first period.
ASM: দেৱাৰ বিজৰ ৰার্দৰে জীৱa বাৰি মিলে,.
--------------------------------------------------

Translating:  32%|████████▋                  | 322/1000 [08:13<15:17,  1.35s/it]

[322/1000]
EN: Mark Stone, Bo Horvat, Nathan MacKinnon and Nick Suzuki scored in Canada’s opener.
ASM: দৰে  জাৰি বিরীৱাৰৰ লিমিলাৰ বাৰু āৰ্দে, яৰ ) а : ?.
--------------------------------------------------

Translating:  32%|████████▋                  | 323/1000 [08:14<16:02,  1.42s/it]

[323/1000]
EN: Connor McDavid recorded three assists in Canada’s 5-0 Olympic win.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি 5 জিৰি লা तिकৰু āৰা রিন্দৰ स्बराज ।
--------------------------------------------------

Translating:  32%|████████▋                  | 324/1000 [08:16<16:50,  1.49s/it]

[324/1000]
EN: Sidney Crosby said Celebrini’s first Olympic goal was huge to get Canada going.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  32%|████████▊                  | 325/1000 [08:17<16:03,  1.43s/it]

[325/1000]
EN: Jon Cooper said Macklin Celebrini plays the game well beyond his years.
ASM: দেৱাৰ বির্জে জীৱে,.
--------------------------------------------------

Translating:  33%|████████▊                  | 326/1000 [08:18<14:12,  1.26s/it]

[326/1000]
EN: Canada planned to face Switzerland at the Milano Arena the next day.
ASM: দেৱাৰ বির্জে জীৱিলাৰ ৰালে,.
--------------------------------------------------

Translating:  33%|████████▊                  | 327/1000 [08:19<12:25,  1.11s/it]

[327/1000]
EN: Choi Ga-on won women’s snowboard halfpipe gold after recovering from a first-run crash.
ASM: দেৱাৰ বির্জে জীৱে,.
--------------------------------------------------

Translating:  33%|████████▊                  | 328/1000 [08:20<13:07,  1.17s/it]

[328/1000]
EN: Chloe Kim took silver and Mitsuki Ono won bronze in the halfpipe event.
ASM: দেৱাৰ বির্জে বাৰি মিলে,.
--------------------------------------------------

Translating:  33%|████████▉                  | 329/1000 [08:22<14:01,  1.25s/it]

[329/1000]
EN: Choi Ga-on scored 90.25 to beat Chloe Kim’s leading 88 score.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে মিৰি লাৰু জিন্দৰা പ് : ायो-ᱹ )
--------------------------------------------------

Translating:  33%|████████▉                  | 330/1000 [08:23<14:31,  1.30s/it]

[330/1000]
EN: Arsenal reached the League Cup final after Kai Havertz secured a 1-0 win.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 1 লাৰ तिकৰা āৰু  कावलি विरोधी а : ?
--------------------------------------------------

Translating:  33%|████████▉                  | 331/1000 [08:25<15:34,  1.40s/it]

[331/1000]
EN: Kai Havertz came off the bench to finish Arsenal’s 4-2 aggregate semi-final victory.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 5 - :  ) লাৰু പ്ৰা а- ;
--------------------------------------------------

Translating:  33%|████████▉                  | 332/1000 [08:26<16:45,  1.51s/it]

[332/1000]
EN: Arsenal will face Manchester City or Newcastle at Wembley on March 22.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে বাৰি লি, പ്ᱹ а জিৰা লাৰম ।
--------------------------------------------------

Translating:  33%|████████▉                  | 333/1000 [08:28<16:12,  1.46s/it]

[333/1000]
EN: Manchester City held a 2-0 lead over Newcastle ahead of the second leg.
ASM: দেৱাৰ বির্জীৰ ৰালে.
--------------------------------------------------

Translating:  33%|█████████                  | 334/1000 [08:29<16:17,  1.47s/it]

[334/1000]
EN: Arsenal have not won the League Cup since 1993, according to the report.
ASM: . দৰে জিৱাৰ বির্দীৰ ৰালে, বাৰি লাৰু মিৰা āৰचर а 1993 ोप 49 : ?
--------------------------------------------------

Translating:  34%|█████████                  | 335/1000 [08:30<14:27,  1.30s/it]

[335/1000]
EN: The Football Association of Ireland confirmed Ireland will fulfil Nations League fixtures against Israel.
ASM: দৰে জাৰি বিরীৱাৰৰ লালিৰ মি,.
--------------------------------------------------

Translating:  34%|█████████                  | 336/1000 [08:31<14:11,  1.28s/it]

[336/1000]
EN: Ireland and Israel were drawn with Austria and Kosovo in Nations League League B.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  34%|█████████                  | 337/1000 [08:32<12:49,  1.16s/it]

[337/1000]
EN: Ireland must play Israel home and away between September and November.
ASM: দেৱাৰ বির্জীৱে বাৰি জিলে,.
--------------------------------------------------

Translating:  34%|█████████▏                 | 338/1000 [08:34<13:53,  1.26s/it]

[338/1000]
EN: The FAI warned refusal could mean forfeiture and possible disqualification under UEFA regulations.
ASM: দেৱাৰ বির্জীৱে বাৰে, লিৰি জিমিলাৰ ৰাদৰা āৰু রিন্দ )  तिकुपিक्कूटে ;  :-.
--------------------------------------------------

Translating:  34%|█████████▏                 | 339/1000 [08:35<14:35,  1.32s/it]

[339/1000]
EN: The FAI said it requested Israel’s UEFA ban in November after an internal vote.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  34%|█████████▏                 | 340/1000 [08:37<15:41,  1.43s/it]

[340/1000]
EN: Novak Djokovic beat Jannik Sinner 3-6, 6-3, 4-6, 6-4, 6-4 in Melbourne.
ASM: দেৱাৰ বির্জীৱে লাৰে 3 --. 4 - 2 6-2, оᱹ
--------------------------------------------------

Translating:  34%|█████████▏                 | 341/1000 [08:38<15:52,  1.45s/it]

[341/1000]
EN: Novak Djokovic’s win over Jannik Sinner set up an Australian Open final against Carlos Alcaraz.
ASM: দেৱাৰ বির্জীৱে. :  )-, বাৰি জিলে ৰাদৰা লাৰে ; പ്ः ā..
--------------------------------------------------

Translating:  34%|█████████▏                 | 342/1000 [08:40<16:09,  1.47s/it]

[342/1000]
EN: Novak Djokovic reached his 11th Australian Open final after ending four straight semi-final exits.
ASM: . দৰিরে জাৱাৰ বীৱেৰে, লিলাৰ ৰামি বাৰা র্দে विरोधी പ्लॆ 11 āৰু  तीर्क्क ; а- : ?
--------------------------------------------------

Translating:  34%|█████████▎                 | 343/1000 [08:41<13:53,  1.27s/it]

[343/1000]
EN: Carlos Alcaraz reached his first Melbourne Park title match, the report said.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  34%|█████████▎                 | 344/1000 [08:42<14:14,  1.30s/it]

[344/1000]
EN: Lorenzo Musetti retired mid-match after suffering a suspected upper leg tear.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  34%|█████████▎                 | 345/1000 [08:43<13:12,  1.21s/it]

[345/1000]
EN: Lorenzo Musetti withdrew after winning the first two sets against Novak Djokovic.
ASM: দেৱাৰ বির্জীৰ ৰিলে, জিৰে বাৰি.
--------------------------------------------------

Translating:  35%|█████████▎                 | 346/1000 [08:45<14:38,  1.34s/it]

[346/1000]
EN: Alexander Zverev rallied from losing the first set to beat Gabriel Diallo in four sets.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  35%|█████████▎                 | 347/1000 [08:47<16:00,  1.47s/it]

[347/1000]
EN: Alexander Zverev won 6-7(1), 6-1, 6-4, 6-2 against Gabriel Diallo at Rod Laver Arena.
ASM: - দেৱাৰ বির্জীৰ ৰিলে, বাৰে মি 1 - 6-4...
--------------------------------------------------

Translating:  35%|█████████▍                 | 348/1000 [08:48<16:16,  1.50s/it]

[348/1000]
EN: An Australian Open report noted fans were unhappy about long queues and a ticket sales halt.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  35%|█████████▍                 | 349/1000 [08:50<16:08,  1.49s/it]

[349/1000]
EN: A Hindustan Times column said tennis needs rivalries to elevate players and the sport.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  35%|█████████▍                 | 350/1000 [08:51<15:57,  1.47s/it]

[350/1000]
EN: A Hindustan Times column said Jannik Sinner and Carlos Alcaraz are improving every year.
ASM: দেৱাৰ বির্জে জীৱে,.
--------------------------------------------------

Translating:  35%|█████████▍                 | 351/1000 [08:53<17:35,  1.63s/it]

[351/1000]
EN: The same column said Sinner and Alcaraz already play at a level above most players.
ASM: দেৱাৰ বির্জীৱে,.
--------------------------------------------------

Translating:  35%|█████████▌                 | 352/1000 [08:54<17:10,  1.59s/it]

[352/1000]
EN: The column said Federer, Nadal and Djokovic gave men’s tennis a tribal feel for two decades.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  35%|█████████▌                 | 353/1000 [08:56<16:57,  1.57s/it]

[353/1000]
EN: A report said Alexander Zverev began a bid for a maiden Australian Open title.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  35%|█████████▌                 | 354/1000 [08:57<16:27,  1.53s/it]

[354/1000]
EN: Carlos Alcaraz defeated Alexander Zverev 6-3, 3-6, 6-1, 6-2 at the Australian Open.
ASM: দেৱাৰ বির্জীৱে জিলাৰ ৰালে, বাৰি মিৰু āৰে विरोधी а 3-...
--------------------------------------------------

Translating:  36%|█████████▌                 | 355/1000 [08:59<17:06,  1.59s/it]

[355/1000]
EN: Carlos Alcaraz won in two hours and 26 minutes, according to the match report.
ASM: . দৰে বির্জাৰ জীৱাৰৰ লাৰিলে, বাৰু মি ৰাদেৰা āৰचर പ്ৰ तिकिल् яৰ 11 রেৱি а : ?
--------------------------------------------------

Translating:  36%|█████████▌                 | 356/1000 [09:00<14:40,  1.37s/it]

[356/1000]
EN: The same report said Zverev received a time-violation warning during the match.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  36%|█████████▋                 | 357/1000 [09:01<13:39,  1.28s/it]

[357/1000]
EN: The report said Alcaraz requested a meeting with the supervisor after the time warning.
ASM: দেৱাৰ বিজৰ ৰার্দৰে জীৱে,.
--------------------------------------------------

Translating:  36%|█████████▋                 | 358/1000 [09:02<12:07,  1.13s/it]

[358/1000]
EN: The report said Alcaraz complained about the length of Zverev’s breaks between points.
ASM: দেৱাৰ বির্জীৰ ৰালা,.
--------------------------------------------------

Translating:  36%|█████████▋                 | 359/1000 [09:03<11:31,  1.08s/it]

[359/1000]
EN: Carlos Alcaraz said he also wanted to know the limit for the time between points.
ASM: দেৱাৰ বির্জীৱে লাৰে ৰালে,.
--------------------------------------------------

Translating:  36%|█████████▋                 | 360/1000 [09:05<13:59,  1.31s/it]

[360/1000]
EN: R Praggnanandhaa sealed a 2026 Candidates berth by winning the FIDE Circuit 2025.
ASM: . দৰে জাৰি বিরীৱাৰৰ লালে, মি ৰাদ্দেৰা বাৰু а 2026 яৰ 11 āৰ 49  वसूलিন্দ ) ।
--------------------------------------------------

Translating:  36%|█████████▋                 | 361/1000 [09:06<15:09,  1.42s/it]

[361/1000]
EN: The Candidates Tournament will determine the challenger to world champion D Gukesh.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  36%|█████████▊                 | 362/1000 [09:08<16:25,  1.54s/it]

[362/1000]
EN: R Praggnanandhaa overtook Ding Liren in May to lead the FIDE Circuit race.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  36%|█████████▊                 | 363/1000 [09:10<16:44,  1.58s/it]

[363/1000]
EN: Praggnanandhaa thanked supporters on X after earning a place in the 2026 Candidates.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰা লাৰু āৰি्लॆ аᱹ  तिकुपat ; പ് : ?
--------------------------------------------------

Translating:  36%|█████████▊                 | 364/1000 [09:12<17:23,  1.64s/it]

[364/1000]
EN: A report said only Nodirbek Abdusattorov had a theoretical chance to catch Praggnanandhaa.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  36%|█████████▊                 | 365/1000 [09:13<16:55,  1.60s/it]

[365/1000]
EN: D Gukesh withdrew from Tata Steel Chess India Rapid and Blitz for personal reasons.
ASM: দেৱাৰ বির্জীৰ ৰিলে, বাৰে মি জিৰা লাৰু āৰি विरोधी রিন্দৰ ). : ?
--------------------------------------------------

Translating:  37%|█████████▉                 | 366/1000 [09:15<17:03,  1.61s/it]

[366/1000]
EN: Tata Steel Chess India Rapid and Blitz was scheduled in Kolkata from January 7 to 11.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মিৰি 11 লাৰু জেৰ ) क्कूटি āৰা রি विरोधी പ് तिकिल्आ?
--------------------------------------------------

Translating:  37%|█████████▉                 | 367/1000 [09:16<16:15,  1.54s/it]

[367/1000]
EN: Nihal Sarin replaced D Gukesh in the Tata Steel Chess India event.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  37%|█████████▉                 | 368/1000 [09:17<14:04,  1.34s/it]

[368/1000]
EN: Dibyendu Barua called D Gukesh’s withdrawal a big setback for organisers and fans.
ASM: দেৱাৰ বিজৰ ৰারে জীৱে,.
--------------------------------------------------

Translating:  37%|█████████▉                 | 369/1000 [09:18<12:33,  1.19s/it]

[369/1000]
EN: Viswanathan Anand returned to play Tata Steel Chess India after six years away.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  37%|█████████▉                 | 370/1000 [09:20<15:14,  1.45s/it]

[370/1000]
EN: Viswanathan Anand said “It was exhausting not playing” while explaining his return.
ASM: . দেৱাৰ বির্জীৱে জিলে, মি বাৰে ৰাদৰা লা तिकৰিावन яৰু  एतेऩुम्  तीर्क्कৰचर പ്রি्लॆ ्रॆ पुत्र маৰ ) ।
--------------------------------------------------

Translating:  37%|██████████                 | 371/1000 [09:22<16:21,  1.56s/it]

[371/1000]
EN: Viswanathan Anand was set to open against Wesley So in the seventh edition.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  37%|██████████                 | 372/1000 [09:23<15:39,  1.50s/it]

[372/1000]
EN: The tournament director said Tata Steel Chess India will be held in January going forward.
ASM: দেৱাৰ বির্জে জীৱলৰ ৰামি,.
--------------------------------------------------

Translating:  37%|██████████                 | 373/1000 [09:26<18:48,  1.80s/it]

[373/1000]
EN: The Tata Steel Chess India event offered equal prize purses of $41,500 in open and women’s.
ASM: . দেৱাৰ বির্জীৰ ৰালে, লাৰে বাৰি জিৰু মি ) রিন্দৰা പ്ৰ तिकिल् яৰ কৰa ।
--------------------------------------------------

Translating:  37%|██████████                 | 374/1000 [09:27<18:31,  1.77s/it]

[374/1000]
EN: Viswanathan Anand backed the Total Chess World Championship Tour approved by FIDE.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  38%|██████████▏                | 375/1000 [09:29<17:55,  1.72s/it]

[375/1000]
EN: The Total Chess World Championship Tour will crown a new “FIDE World Combined” champion.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি ) а : ?
--------------------------------------------------

Translating:  38%|██████████▏                | 376/1000 [09:31<17:44,  1.71s/it]

[376/1000]
EN: The tour will be held across fast classic, rapid and blitz formats.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  38%|██████████▏                | 377/1000 [09:33<18:23,  1.77s/it]

[377/1000]
EN: Anand said Norway Chess has a serious long-term proposal for the new tour.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  38%|██████████▏                | 378/1000 [09:34<16:16,  1.57s/it]

[378/1000]
EN: Anand said the sport benefits when Magnus Carlsen competes in major events.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  38%|██████████▏                | 379/1000 [09:36<17:17,  1.67s/it]

[379/1000]
EN: Wesley So said he proposed a draw against Praggnanandhaa, not the arbiters.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  38%|██████████▎                | 380/1000 [09:38<18:55,  1.83s/it]

[380/1000]
EN: Praggnanandhaa had one second left before stopping the clock to call the arbiter.
ASM: দেৱাৰ বির্জীৱে,.
--------------------------------------------------

Translating:  38%|██████████▎                | 381/1000 [09:40<20:09,  1.95s/it]

[381/1000]
EN: Nihal Sarin won the 2026 Tata Steel Chess India Rapid Tournament in Kolkata.
ASM: . দৰে জাৰি বিরীৱাৰৰ ৰালাৰ মিলে, а 2026 বাৰ্দেৰা яৰ तिकৰু āৰat ।
--------------------------------------------------

Translating:  38%|██████████▎                | 382/1000 [09:42<20:56,  2.03s/it]

[382/1000]
EN: Ian Nepomniachtchi criticised hotel conditions during the 2025 Chess World Cup in Goa.
ASM: দেৱাৰ  2025 বির্জীৰ ৰালে, বাৰে জিৰি লা तिकৰা মিন্দৰ सब ।
--------------------------------------------------

Translating:  38%|██████████▎                | 383/1000 [09:44<19:45,  1.92s/it]

[383/1000]
EN: Ian Nepomniachtchi said organisers chose one of the worst hotels for the Goa event.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  38%|██████████▎                | 384/1000 [09:45<16:40,  1.62s/it]

[384/1000]
EN: Nepomniachtchi lost to Diptayan Ghosh after receiving a bye into round two.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  38%|██████████▍                | 385/1000 [09:46<16:08,  1.57s/it]

[385/1000]
EN: PGTI’s 2026 schedule was drawn up only till March-end, featuring six events.
ASM: . দৰে জাৰি বিরীৱাৰৰ লালে, বাৰ্মি ৰা तिकৰা аᱹ : ?
--------------------------------------------------

Translating:  39%|██████████▍                | 386/1000 [09:48<15:17,  1.49s/it]

[386/1000]
EN: PGTI planned no more than 25 tournaments in 2026 after holding 36 events last year.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে জিলে, বাৰি মি 25 লা तिकৰা घटनुप 49 : ?
--------------------------------------------------

Translating:  39%|██████████▍                | 387/1000 [09:49<15:02,  1.47s/it]

[387/1000]
EN: PGTI’s main tour offered ₹35 crore prize money in 2025, up from ₹24 crore.
ASM: . দৰে বির্জাৰী বাৰি জেৱাৰৰ লালে, মি ৰাদেৰা പ് 49 а : ?-ᱹ.
--------------------------------------------------

Translating:  39%|██████████▍                | 388/1000 [09:51<15:17,  1.50s/it]

[388/1000]
EN: OWGR granted LIV Golf accreditation for the first time, awarding points to top-10 finishers.
ASM: দেৱাৰ বিজৰ ৰার্দৰে জীৱেৰি লালে, মিৰা বাৰু яৰ ) പ്ৰ तिकिल् а-. : ?
--------------------------------------------------

Translating:  39%|██████████▌                | 389/1000 [09:52<14:54,  1.46s/it]

[389/1000]
EN: LIV Golf expanded tournaments from 54 to 72 holes in 2026, paving the approval.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মিলাৰি জিদৰা а 2026 പ് : ?-ᱹ.
--------------------------------------------------

Translating:  39%|██████████▌                | 390/1000 [09:53<14:33,  1.43s/it]

[390/1000]
EN: OWGR said LIV Golf did not meet all eligibility standards under its requirements.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  39%|██████████▌                | 391/1000 [09:55<14:01,  1.38s/it]

[391/1000]
EN: LIV Golf’s season-opening event in Riyadh was set to start with 57 players.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 5 লাৰু а : ?
--------------------------------------------------

Translating:  39%|██████████▌                | 392/1000 [09:56<13:07,  1.30s/it]

[392/1000]
EN: International Series India was expected to move from DLF Golf and Country Club to Bengaluru.
ASM: দেৱাৰ বিজৰ ৰার্দৰে জীৱa বাৰিলে,.
--------------------------------------------------

Translating:  39%|██████████▌                | 393/1000 [09:57<13:37,  1.35s/it]

[393/1000]
EN: Bryson DeChambeau and Joaquin Niemann were key draws at International Series India 2025.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে মি জিৰিলাৰ ) রিন্দৰা പ് 2025 : ?
--------------------------------------------------

Translating:  39%|██████████▋                | 394/1000 [09:58<13:24,  1.33s/it]

[394/1000]
EN: Ollie Schniederjans won International Series India 2025 by four shots in Gurugram.
ASM: . দৰিরে জাৱাৰ বিলে, বাৰে ৰালাৰী মি āৰু а 2025 : ?
--------------------------------------------------

Translating:  40%|██████████▋                | 395/1000 [09:59<12:41,  1.26s/it]

[395/1000]
EN: Rahul Singh said International Series organisers remained committed to returning to India.
ASM: দেৱাৰ বিজৰ ৰার্দৰে জীৱিলা. : ?
--------------------------------------------------

Translating:  40%|██████████▋                | 396/1000 [10:01<13:05,  1.30s/it]

[396/1000]
EN: PGTI launched a league with six franchises, with each franchise buying 10 players.
ASM: দেৱাৰ বির্জীৱে জিলে, মি 10 লাৰি বাৰে ৰাদৰা āৰু яৰ ) а.
--------------------------------------------------

Translating:  40%|██████████▋                | 397/1000 [10:02<14:02,  1.40s/it]

[397/1000]
EN: The PGTI league’s first edition was planned across three courses in Delhi-NCR.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  40%|██████████▋                | 398/1000 [10:04<13:57,  1.39s/it]

[398/1000]
EN: Shubhankar Sharma missed cuts in 21 of 28 events in 2025, the report said.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে বাৰি লালে, মি विरोधी জিৰা പ് : ?
--------------------------------------------------

Translating:  40%|██████████▊                | 399/1000 [10:06<15:46,  1.57s/it]

[399/1000]
EN: Shubhankar Sharma regained playing rights for 2026 via Q-School, finishing tied-second.
ASM: . দৰে জিৱাৰ বির্দীৰ ৰালে, বাৰি মিৰু লাৰা āৰायला а 2026 রেৱিন্দেৰ ) ।
--------------------------------------------------

Translating:  40%|██████████▊                | 400/1000 [10:07<14:45,  1.48s/it]

[400/1000]
EN: Vietnam targets 22 to 25 million international visitors by 2026.
ASM: 2026 ৰাদৰে বিজৰ রীৱাৰ্দেৰিলিলা ।
--------------------------------------------------

Translating:  40%|██████████▊                | 401/1000 [10:08<13:08,  1.32s/it]

[401/1000]
EN: Operations teams monitor weather to minimize passenger inconvenience.
ASM: দেৱাৰ বির্জীৱে বাৰি জিলে,.
--------------------------------------------------

Translating:  40%|██████████▊                | 402/1000 [10:09<12:45,  1.28s/it]

[402/1000]
EN: IndiGo announces Amsterdam debut as first long-haul European destination.
ASM: দেৱাৰ বির্জীৰ ৰিলে, বাৰে মি জিৰা লাৰু.
--------------------------------------------------

Translating:  40%|██████████▉                | 403/1000 [10:11<12:48,  1.29s/it]

[403/1000]
EN: Air India crash committee investigates Boeing 787-8 Ahmedabad tragedy.
ASM: .- দেৱাৰ বির্জীৰ ৰালা জিলি বাৰে, а 797- : ā ;
--------------------------------------------------

Translating:  40%|██████████▉                | 404/1000 [10:12<14:03,  1.42s/it]

[404/1000]
EN: IndiGo aims for forty percent international capacity share by 2030.
ASM: . বিৰে দৰি জাৱাৰ রীৱে, লিলাৰ ৰাদেৰা মি विरोधी বাৰ্দিন্দ ) ।
--------------------------------------------------

Translating:  40%|██████████▉                | 405/1000 [10:13<12:44,  1.29s/it]

[405/1000]
EN: One survivor rescued from Air India crash site in Ahmedabad.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  41%|██████████▉                | 406/1000 [10:15<12:56,  1.31s/it]

[406/1000]
EN: Jetstar Asia closure frees five hundred million dollars for Qantas.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  41%|██████████▉                | 407/1000 [10:16<13:00,  1.32s/it]

[407/1000]
EN: Qantas Group announces closure of Singapore-based Jetstar Asia.
ASM: দেৱাৰ বির্জে.
--------------------------------------------------

Translating:  41%|███████████                | 408/1000 [10:17<13:37,  1.38s/it]

[408/1000]
EN: IndiGo launches Mumbai-Manchester flights using Norse aircraft.
ASM: দেৱাৰ বির্জীৰ ৰিলে, লাৰে বাৰি জিমিৰু āৰা ्रॆक्कुप गोठাৰৰ яৰ ) പवेৰ तिक ।
--------------------------------------------------

Translating:  41%|███████████                | 409/1000 [10:19<13:28,  1.37s/it]

[409/1000]
EN: IndiGo transitions to A350-900 aircraft for European expansion by 2027.
ASM: . দেৱাৰ বিজৰ ৰার্দৰে জীৱa বাৰি লিলা 350-900 а, ायो 2027 :
--------------------------------------------------

Translating:  41%|███████████                | 410/1000 [10:20<13:40,  1.39s/it]

[410/1000]
EN: Air India Ahmedabad crash claims 242 lives including Vijay Rupani.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে а 242 জিৰি লাৰু яৰ 11 মিন্দৰ स्बराज ।
--------------------------------------------------

Translating:  41%|███████████                | 411/1000 [10:22<14:25,  1.47s/it]

[411/1000]
EN: Thirteen Jetstar Asia A320s redeployed to Australia and New Zealand.
ASM: . দেৱাৰ বির্জীৰ ৰালে, লাৰে মি 320 āৰি জিৰা বাৰু яৰ ) പ്ৰ तिकिल् маৰat  एतेऩुम् 312 : ?
--------------------------------------------------

Translating:  41%|███████████                | 412/1000 [10:23<12:40,  1.29s/it]

[412/1000]
EN: IndiGo issues fog advisory for Delhi and northern India passengers.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  41%|███████████▏               | 413/1000 [10:25<13:52,  1.42s/it]

[413/1000]
EN: DGCA imposes ₹2 crore fine on Air India for safety lapses.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি विरोधी লাৰু āৰা রিন্দৰ ; പ്ৰ तिकिल्  वसूल समारंभ яৰ ।
--------------------------------------------------

Translating:  41%|███████████▏               | 414/1000 [10:26<14:14,  1.46s/it]

[414/1000]
EN: Sixteen intra-Asia routes lose only non-stop Changi connections.
ASM: দেৱাৰ বির্জে,.
--------------------------------------------------

Translating:  42%|███████████▏               | 415/1000 [10:27<12:41,  1.30s/it]

[415/1000]
EN: Bengaluru airport opens second runway to handle growing traffic.
ASM: দৰি জেৱাৰ বিরীৰে লিলাৰ ৰামি,.
--------------------------------------------------

Translating:  42%|███████████▏               | 416/1000 [10:28<12:38,  1.30s/it]

[416/1000]
EN: Air India Express pilot assaults passenger at Delhi airport terminal.
ASM: বিৰে দৰি জাৰ রীৱাৰৰ.
--------------------------------------------------

Translating:  42%|███████████▎               | 417/1000 [10:29<12:14,  1.26s/it]

[417/1000]
EN: Mumbai airport witnesses record passenger footfall during festive week.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  42%|███████████▎               | 418/1000 [10:30<10:47,  1.11s/it]

[418/1000]
EN: Dense fog disrupts IndiGo flight operations across North India.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  42%|███████████▎               | 419/1000 [10:31<10:09,  1.05s/it]

[419/1000]
EN: Go First insolvency resolution extends to third consecutive month.
ASM: দেৱাৰ বির্জীৰ ৰালে, জিৰে.
--------------------------------------------------

Translating:  42%|███████████▎               | 420/1000 [10:33<11:28,  1.19s/it]

[420/1000]
EN: Akasa Air orders additional Boeing 737 Max aircraft for expansion.
ASM: -. দেৱাৰ বির্জীৰ ৰালি জিৰে, বাৰা লাৰি विरोधी ोपत्यৱে মিন্দৰু яৰ 11 ्रॆ 49 ;
--------------------------------------------------

Translating:  42%|███████████▎               | 421/1000 [10:34<11:03,  1.15s/it]

[421/1000]
EN: Air India pilots union raises concerns over rest period violations.
ASM: দেৱাৰ বির্জীৱে লাৰে ৰালে,.
--------------------------------------------------

Translating:  42%|███████████▍               | 422/1000 [10:35<11:47,  1.22s/it]

[422/1000]
EN: EU launches Entry-Exit System campaign for non-EU travellers.
ASM: দেৱাৰ বির্জীৰ ৰালা,.
--------------------------------------------------

Translating:  42%|███████████▍               | 423/1000 [10:36<11:23,  1.18s/it]

[423/1000]
EN: SpiceJet secures funding to revive grounded fleet operations soon.
ASM: দেৱাৰ বির্জে জীৱaৰ ৰিলে, বাৰি লামিৰু.
--------------------------------------------------

Translating:  42%|███████████▍               | 424/1000 [10:38<12:04,  1.26s/it]

[424/1000]
EN: Bulgaria adopts Euro as legal tender from January first 2026.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি লাৰি विरोधी জিদৰা āৰ 49 2026 ;
--------------------------------------------------

Translating:  42%|███████████▍               | 425/1000 [10:39<12:24,  1.29s/it]

[425/1000]
EN: Vietnam grants forty-five day visa-free entry to twelve European nations.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  43%|███████████▌               | 426/1000 [10:40<11:03,  1.16s/it]

[426/1000]
EN: Indian government reverses ban on Sikh pilgrimages to Pakistan.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  43%|███████████▌               | 427/1000 [10:41<10:18,  1.08s/it]

[427/1000]
EN: Pakistan High Commission issues visas to twenty-one hundred Sikh pilgrims.
ASM: দেৱাৰ বির্জীৰ ৰিলে জিৰে,.
--------------------------------------------------

Translating:  43%|███████████▌               | 428/1000 [10:42<10:23,  1.09s/it]

[428/1000]
EN: TSA ends shoe removal rule at domestic United States airports.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  43%|███████████▌               | 429/1000 [10:43<09:34,  1.01s/it]

[429/1000]
EN: Real ID enforcement charges tourists forty-five dollars for domestic flights.
ASM: দৰি জেৱাৰ বিরীৰ ৰালে,.
--------------------------------------------------

Translating:  43%|███████████▌               | 430/1000 [10:44<09:26,  1.01it/s]

[430/1000]
EN: United States government shutdown causes forty-three day travel chaos.
ASM: দেৱাৰ বির্জে জীৱলৰ ৰামি বাৰে,.
--------------------------------------------------

Translating:  43%|███████████▋               | 431/1000 [10:44<09:00,  1.05it/s]

[431/1000]
EN: Government considers hotel industry infrastructure status for tax benefits.
ASM: দেৱাৰ বির্জীৱে লাৰে ৰালে,.
--------------------------------------------------

Translating:  43%|███████████▋               | 432/1000 [10:45<08:24,  1.13it/s]

[432/1000]
EN: Gajendra Singh Shekhawat announces infrastructure status proposal for hotels.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  43%|███████████▋               | 433/1000 [10:46<08:05,  1.17it/s]

[433/1000]
EN: Tourism Ministry reboots Incredible India campaign with AI focus.
ASM: দেৱাৰ বির্জে জীৱিলাৰ ৰিলে ।
--------------------------------------------------

Translating:  43%|███████████▋               | 434/1000 [10:47<08:52,  1.06it/s]

[434/1000]
EN: Suman Billa confirms new digital-centric Incredible India strategy.
ASM: দেৱাৰ বির্জে জীৱে,.
--------------------------------------------------

Translating:  44%|███████████▋               | 435/1000 [10:48<09:46,  1.04s/it]

[435/1000]
EN: India targets one trillion dollar tourism economy by 2047.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে মি জিৰি 5 49 ;
--------------------------------------------------

Translating:  44%|███████████▊               | 436/1000 [10:50<10:49,  1.15s/it]

[436/1000]
EN: Centre sanctions fifty destinations for challenge mode tourism development.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  44%|███████████▊               | 437/1000 [10:51<10:10,  1.08s/it]

[437/1000]
EN: Telangana adopts Sarathi portal for online RTA services.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  44%|███████████▊               | 438/1000 [10:52<10:58,  1.17s/it]

[438/1000]
EN: Ministry announces twelve thousand crore rupees for new tourism destinations.
ASM: দেৱাৰ বির্জীৱে বাৰে, মিৰি জিলে ৰাদৰা লাৰু яৰ ) রিন্দি विरोधी. ।
--------------------------------------------------

Translating:  44%|███████████▊               | 439/1000 [10:54<12:08,  1.30s/it]

[439/1000]
EN: Government allocates 1.34 billion dollars for tourism infrastructure development.
ASM: দেৱাৰ বির্জীৰ ৰালাৰে লিমি জিৰি 1.., а-ᱹ ;
--------------------------------------------------

Translating:  44%|███████████▉               | 440/1000 [10:55<12:35,  1.35s/it]

[440/1000]
EN: India plans 2030 Commonwealth Games hosting to boost tourism.
ASM: . দেৱাৰ জির্বিলাৰীৰ ৰালে, বাৰে মিৰি āৰা പ്ৰু घटनुपি्लॆ а.-ᱹ ;
--------------------------------------------------

Translating:  44%|███████████▉               | 441/1000 [10:56<12:12,  1.31s/it]

[441/1000]
EN: Census self-enumeration trial begins for digital population count.
ASM: দেৱাৰ বির্জীৱে লিৰে, বাৰি জিমিলাৰ ৰাদৰা. : ?
--------------------------------------------------

Translating:  44%|███████████▉               | 442/1000 [10:57<11:11,  1.20s/it]

[442/1000]
EN: European Commission launches biometric border system awareness campaign.
ASM: দেৱাৰ বির্জীৱে বাৰি জিলে,.
--------------------------------------------------

Translating:  44%|███████████▉               | 443/1000 [10:58<10:06,  1.09s/it]

[443/1000]
EN: Non-EU travellers face new digital border checks from October.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  44%|███████████▉               | 444/1000 [10:59<10:17,  1.11s/it]

[444/1000]
EN: Dover ferry passengers register first for EU entry-exit system.
ASM: দেৱাৰ বির্জীৱে জিলাৰ ৰালে, বাৰি মিৰা. : ?
--------------------------------------------------

Translating:  44%|████████████               | 445/1000 [11:00<09:57,  1.08s/it]

[445/1000]
EN: Eurostar business travellers gradually included in EES rollout.
ASM: দেৱাৰ বির্জে জীৱaৰ ৰালে, বাৰি.
--------------------------------------------------

Translating:  45%|████████████               | 446/1000 [11:01<10:03,  1.09s/it]

[446/1000]
EN: India extends e-visa facility to citizens of five more nations.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি মিলাৰু..
--------------------------------------------------

Translating:  45%|████████████               | 447/1000 [11:02<09:54,  1.08s/it]

[447/1000]
EN: Karnataka announces tourism policy targeting fifty billion dollar investment
ASM: দৰি জেৱাৰ বিরীৰে লিমিলাৰ ৰাদে,.
--------------------------------------------------

Translating:  45%|████████████               | 448/1000 [11:04<10:32,  1.15s/it]

[448/1000]
EN: GST Council reduces tax on hotel rooms below seven thousand five hundred rupees.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে লাৰি জিমিৰু. : ?
--------------------------------------------------

Translating:  45%|████████████               | 449/1000 [11:05<10:03,  1.09s/it]

[449/1000]
EN: Ministry of Tourism launches Swadesh Darshan 3.0 for sustainable tourism.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে 3 : ?
--------------------------------------------------

Translating:  45%|████████████▏              | 450/1000 [11:06<09:10,  1.00s/it]

[450/1000]
EN: Civil Aviation Ministry orders probe into Delhi airport assault case.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  45%|████████████▏              | 451/1000 [11:07<09:57,  1.09s/it]

[451/1000]
EN: Government approves UDAN 5.0 with focus on helicopter services.
ASM: . দেৱাৰ বিরী 5, জিলে মিৰি বালাৰে ৰাদ্দৰা яৰু  एतेऩुम्.
--------------------------------------------------

Translating:  45%|████████████▏              | 452/1000 [11:08<11:01,  1.21s/it]

[452/1000]
EN: Kerala declares tourism as industry status for hotels and resorts.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  45%|████████████▏              | 453/1000 [11:10<12:18,  1.35s/it]

[453/1000]
EN: West Bengal secures second rank in foreign tourist arrivals.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  45%|████████████▎              | 454/1000 [11:11<12:35,  1.38s/it]

[454/1000]
EN: Mamata Banerjee hails West Bengal's international tourism milestone.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  46%|████████████▎              | 455/1000 [11:13<13:04,  1.44s/it]

[455/1000]
EN: Maharashtra leads foreign tourist arrivals with 3.71 million visitors.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে а.ᱹ জিৰি লাৰু āৰা মিন্দৰ स्बराज ।
--------------------------------------------------

Translating:  46%|████████████▎              | 456/1000 [11:14<12:43,  1.40s/it]

[456/1000]
EN: West Bengal records 3.12 million foreign tourist visits nationwide.
ASM: . দেৱাৰ জির্বিলাৰী 5, বাৰে а : я-?
--------------------------------------------------

Translating:  46%|████████████▎              | 457/1000 [11:16<13:01,  1.44s/it]

[457/1000]
EN: Uttar Pradesh tops domestic tourism with 646.81 million visitors.
ASM: 0.81 দৰে জাৰি বিরীৱাৰৰ ৰালাৰ লি, বাৰ্মিন্দেৰা പ जून् 11
--------------------------------------------------

Translating:  46%|████████████▎              | 458/1000 [11:17<13:00,  1.44s/it]

[458/1000]
EN: Tamil Nadu records 306.84 million domestic tourist footfall.
ASM: . দেৱাৰ বির্জীৰ ৰালাৰে লিমি জিৰিন্দৰা বারে, аᱹ ाय़ : ?
--------------------------------------------------

Translating:  46%|████████████▍              | 459/1000 [11:19<12:32,  1.39s/it]

[459/1000]
EN: India receives 2,948.19 million domestic tourists during 2024.
ASM: . দৰে জাৰিরীৰ বিলিলাৰ ৰাৱা বাৰ্দে, ाय़ 498.19ৰ टवॆ चार а 2024?
--------------------------------------------------

Translating:  46%|████████████▍              | 460/1000 [11:20<12:53,  1.43s/it]

[460/1000]
EN: Foreign tourist visits to India touch 20.94 million in 2024.
ASM: . দৰিরে জাৱাৰ বিলিৰ্লাৰ ৰাদেৰে, аᱹ বাৰীৰ ) মি പप 49.4 2024?
--------------------------------------------------

Translating:  46%|████████████▍              | 461/1000 [11:21<12:33,  1.40s/it]

[461/1000]
EN: Domestic tourism records 17.51 percent growth over previous year.
ASM: . দেৱাৰ বির্জীৰ ৰালি লাৰে জিৰি, বাৰমি 17.51?
--------------------------------------------------

Translating:  46%|████████████▍              | 462/1000 [11:23<12:01,  1.34s/it]

[462/1000]
EN: International tourist arrivals grow 8.84 percent in 2024.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে а 2024 লাৰি জিমি विरोधी പ്.
--------------------------------------------------

Translating:  46%|████████████▌              | 463/1000 [11:24<11:52,  1.33s/it]

[463/1000]
EN: Maha Kumbh Mela attracts 663 million visits across forty-five days.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে জিলে, বাৰি মিলাৰু പ് : ?
--------------------------------------------------

Translating:  46%|████████████▌              | 464/1000 [11:25<11:44,  1.31s/it]

[464/1000]
EN: Prayagraj witnesses 660 million pilgrims at Sangam confluence.
ASM: . দেৱাৰ বির্জীৰ ৰালা, বাৰে লিমি জিৰি 660 а : ?
--------------------------------------------------

Translating:  46%|████████████▌              | 465/1000 [11:27<11:46,  1.32s/it]

[465/1000]
EN: Vietnam welcomes 1.73 million international visitors during October 2025.
ASM: . দেৱাৰ বির্জীৰ ৰালা, বাৰে аᱹ জিমি লি 1 973  तिकৰायला ।
--------------------------------------------------

Translating:  47%|████████████▌              | 466/1000 [11:28<11:33,  1.30s/it]

[466/1000]
EN: Vietnam records 13.8 percent monthly growth in foreign tourist arrivals.
ASM: দৰে জাৰি বিরীৱাৰৰ লিমিলাৰ বাৰ্দেৰা а..
--------------------------------------------------

Translating:  47%|████████████▌              | 467/1000 [11:29<11:00,  1.24s/it]

[467/1000]
EN: India attracts only ten million international tourists annually currently.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  47%|████████████▋              | 468/1000 [11:30<11:33,  1.30s/it]

[468/1000]
EN: France welcomes ninety million tourists against India's ten million.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  47%|████████████▋              | 469/1000 [11:32<11:23,  1.29s/it]

[469/1000]
EN: Spain receives eighty-four million international visitors annually.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  47%|████████████▋              | 470/1000 [11:33<11:19,  1.28s/it]

[470/1000]
EN: United States hosts eighty million foreign tourists every year.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  47%|████████████▋              | 471/1000 [11:34<09:57,  1.13s/it]

[471/1000]
EN: India's pre-Covid tourist arrival figures remain unmatched after six years.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  47%|████████████▋              | 472/1000 [11:35<11:00,  1.25s/it]

[472/1000]
EN: Tourism contributes 5.2 percent to India's current GDP.
ASM: . দেৱাৰ বির্জীৰ ৰালি, বাৰে জিৰি লাৰু মিন্দৰা āৰ विरोधी പ്ৰ तिकिल् ाय़ ।
--------------------------------------------------

Translating:  47%|████████████▊              | 473/1000 [11:37<11:50,  1.35s/it]

[473/1000]
EN: Tourism sector supports 84 million livelihoods across India.
ASM: . দৰে জাৰি বিরীৱাৰৰ ৰালাৰ লিৰ্দেৰা বাৰু মি কৰat ।
--------------------------------------------------

Translating:  47%|████████████▊              | 474/1000 [11:38<11:56,  1.36s/it]

[474/1000]
EN: FICCI predicts 250 billion dollar tourism opportunity by 2030.
ASM: . দৰে বির্জাৰ জীৱাৰৰ লাৰিলে, মি 25 2030 :
--------------------------------------------------

Translating:  48%|████████████▊              | 475/1000 [11:39<11:17,  1.29s/it]

[475/1000]
EN: ICRA reports hotel demand to exceed supply in coming years.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে লাৰি জিমি ;.
--------------------------------------------------

Translating:  48%|████████████▊              | 476/1000 [11:41<11:04,  1.27s/it]

[476/1000]
EN: Global travel industry generates 10.9 trillion dollars for economies.
ASM: দৰে জাৰি বিরীৰ লিলাৱাৰৰ ৰামিৰ্দে, বাৰা പप 49..
--------------------------------------------------

Translating:  48%|████████████▉              | 477/1000 [11:41<09:59,  1.15s/it]

[477/1000]
EN: Travel and tourism accounts for ten percent of global GDP.
ASM: দৰে জাৰি বিরীৰ লি ৰালা,.
--------------------------------------------------

Translating:  48%|████████████▉              | 478/1000 [11:43<10:14,  1.18s/it]

[478/1000]
EN: Vietnam targets 22 to 26 million international visitors by 2026.
ASM: 2026 ৰাদৰে বিজৰ রীৱাৰ্দেৰিলিলা ।
--------------------------------------------------

Translating:  48%|████████████▉              | 479/1000 [11:43<09:05,  1.05s/it]

[479/1000]
EN: Belgium citizens enjoy forty-five day visa-free Vietnam travel.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  48%|████████████▉              | 480/1000 [11:45<10:02,  1.16s/it]

[480/1000]
EN: Poland nationals receive visa-free entry to Vietnam under new scheme.
ASM: দৰে জাৰি বিরীৰ. :  )-, লাৰ্লৰ ৰাৱাৰৰ বামিৰু പ്ः ायो ;
--------------------------------------------------

Translating:  48%|████████████▉              | 481/1000 [11:46<10:02,  1.16s/it]

[481/1000]
EN: Swiss passport holders travel visa-free to Vietnam for forty-five days.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  48%|█████████████              | 482/1000 [11:47<10:01,  1.16s/it]

[482/1000]
EN: Saudi Red Sea Authority issues twelve marine tourism licences.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  48%|█████████████              | 483/1000 [11:48<09:56,  1.15s/it]

[483/1000]
EN: Red Sea Cruises receives approval under Cruise Saudi brand.
ASM: দৰে জাৰি বিরীৰ লিৱাৰৰ মি ৰালাৰ तिक বাৰ্দেৰা. : ?
--------------------------------------------------

Translating:  48%|█████████████              | 484/1000 [11:49<09:25,  1.10s/it]

[484/1000]
EN: Sindalah Marina in NEOM secures Saudi marine tourism licence.
ASM: দেৱাৰ বির্জে জীৱেৰে ৰালাৰ,.
--------------------------------------------------

Translating:  48%|█████████████              | 485/1000 [11:50<09:23,  1.09s/it]

[485/1000]
EN: Dolphin Beach Resort Marina obtains Yanbu operating approval.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  49%|█████████████              | 486/1000 [11:52<09:39,  1.13s/it]

[486/1000]
EN: Jeddah Municipality Marina included in Saudi licensing round.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  49%|█████████████▏             | 487/1000 [11:53<10:16,  1.20s/it]

[487/1000]
EN: Deep Seas Shipping Agency gains tourism shipping agent licence.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  49%|█████████████▏             | 488/1000 [11:54<09:55,  1.16s/it]

[488/1000]
EN: Venice extends day-tripper entrance fee to sixty days.
ASM: দৰে জাৰি বিরীৰ লিলাৰ ৰাদে,.
--------------------------------------------------

Translating:  49%|█████████████▏             | 489/1000 [11:55<09:47,  1.15s/it]

[489/1000]
EN: Venice charges day-trippers from Friday to Sunday between April and July.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  49%|█████████████▏             | 490/1000 [11:56<08:54,  1.05s/it]

[490/1000]
EN: Simone Venturini calls Venice entry fee tangible innovation tool.
ASM: দৰে জাৰি বিরীৰ লিমি,.
--------------------------------------------------

Translating:  49%|█████████████▎             | 491/1000 [11:57<09:06,  1.07s/it]

[491/1000]
EN: Amsterdam introduces tourist fees to fight overtourism congestion.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰিলাৰু. : ?
--------------------------------------------------

Translating:  49%|█████████████▎             | 492/1000 [11:58<09:19,  1.10s/it]

[492/1000]
EN: Greece passes laws limiting visitor numbers to popular islands.
ASM: দৰি জেৱাৰ বিরীৰে লিৰ্দেৰা বাৰু মি ৰালাৰ तिक. : ?
--------------------------------------------------

Translating:  49%|█████████████▎             | 493/1000 [11:59<08:26,  1.00it/s]

[493/1000]
EN: Japan implements tourist fees to manage overcrowding at sites.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  49%|█████████████▎             | 494/1000 [12:00<09:37,  1.14s/it]

[494/1000]
EN: Hurricane Melissa devastates Jamaica's tourism infrastructure.
ASM: দেৱাৰ বির্জীৰ ৰালা,.
--------------------------------------------------

Translating:  50%|█████████████▎             | 495/1000 [12:01<08:47,  1.05s/it]

[495/1000]
EN: Jamaica opens for business after Hurricane Melissa recovery.
ASM: দৰি জেৱাৰ বিরীৰ ৰালা,.
--------------------------------------------------

Translating:  50%|█████████████▍             | 496/1000 [12:02<08:31,  1.02s/it]

[496/1000]
EN: Canadian visitation to United States continues to plummet.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  50%|█████████████▍             | 497/1000 [12:04<09:56,  1.19s/it]

[497/1000]
EN: Sean Duffy focuses on America's ailing air travel system.
ASM: দৰে জাৰি বিরীৰ. : ?
--------------------------------------------------

Translating:  50%|█████████████▍             | 498/1000 [12:05<10:24,  1.24s/it]

[498/1000]
EN: Trump administration policies impact travel both positively and negatively.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  50%|█████████████▍             | 499/1000 [12:06<09:44,  1.17s/it]

[499/1000]
EN: Sri Lanka regime change attributed to poor governance by Ajit Doval.
ASM: দেৱাৰ বির্জীৱে লিমি জিৰে,.
--------------------------------------------------

Translating:  50%|█████████████▌             | 500/1000 [12:07<09:08,  1.10s/it]

[500/1000]
EN: Bangladesh leadership transition results from poor governance failures.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  50%|█████████████▌             | 501/1000 [12:08<08:44,  1.05s/it]

[501/1000]
EN: Nepal government change linked to governance issues says Doval.
ASM: দেৱাৰ বির্জে জীৱিলাৰ ৰালে,.
--------------------------------------------------

Translating:  50%|█████████████▌             | 502/1000 [12:10<10:12,  1.23s/it]

[502/1000]
EN: Thailand launches five year multiple entry tourist visa scheme.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  50%|█████████████▌             | 503/1000 [12:10<09:07,  1.10s/it]

[503/1000]
EN: Sri Lanka grants free visa to seven countries including India.
ASM: দেৱাৰ বির্জীৰ ৰালা,.
--------------------------------------------------

Translating:  50%|█████████████▌             | 504/1000 [12:12<10:25,  1.26s/it]

[504/1000]
EN: Maldives lifts emergency but tourism recovery remains sluggish.
ASM: দৰি জেৱাৰ বিরীৰে.
--------------------------------------------------

Translating:  50%|█████████████▋             | 505/1000 [12:14<11:08,  1.35s/it]

[505/1000]
EN: UAE announces five year multiple entry visa for Indian nationals.
ASM: দৰি জেৱাৰ বিরীৰে. : ?
--------------------------------------------------

Translating:  51%|█████████████▋             | 506/1000 [12:14<09:49,  1.19s/it]

[506/1000]
EN: Schengen visa fees increase from eighty to ninety Euros globally.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  51%|█████████████▋             | 507/1000 [12:15<08:40,  1.06s/it]

[507/1000]
EN: Japan resumes short term tourist visa processing for Indians.
ASM: দৰিরে জাৱাৰ বিৰে,.
--------------------------------------------------

Translating:  51%|█████████████▋             | 508/1000 [12:17<10:20,  1.26s/it]

[508/1000]
EN: India operates 127 airports with ten new cruise terminals.
ASM: . বিৰে দৰা জরীৱাৰ লিলাৰ ৰাদে, বাৰি মিন্দ্ৰু āৰचर রেৱি विरोधी പ് तिकिल् аᱹ о  तीर्क्क ।
--------------------------------------------------

Translating:  51%|█████████████▋             | 509/1000 [12:18<10:44,  1.31s/it]

[509/1000]
EN: Government constructs 150,000 kilometres of new national highways.
ASM: . দেৱাৰ বির্জীৰ ৰালাৰে লিমি জিৰি 1, 000 150,000?
--------------------------------------------------

Translating:  51%|█████████████▊             | 510/1000 [12:20<10:57,  1.34s/it]

[510/1000]
EN: India develops 38 national waterways for inland cruise tourism.
ASM: দৰি জেৱাৰ বিরীৰে লাৰ্লিৰ ৰাদে, বাৰা মি 3 āৰু а : я-.
--------------------------------------------------

Translating:  51%|█████████████▊             | 511/1000 [12:21<11:01,  1.35s/it]

[511/1000]
EN: Metro rail network expands 10,000 kilometres across 23 cities.
ASM: . বিৰে দৰি জাৱাৰীৰ র্দেলৰ ৰালাৰ 11, 000 āৰা বাৰু а പ് : ?
--------------------------------------------------

Translating:  51%|█████████████▊             | 512/1000 [12:23<11:44,  1.44s/it]

[512/1000]
EN: Swadesh Darshan 2.0 develops tourism sites to global standards.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে বাৰি লি, জিমি 2 লাৰু āৰা атিৰat яৰ ) പ് तिकिल् विरोधी мо : ?
--------------------------------------------------

Translating:  51%|█████████████▊             | 513/1000 [12:24<11:19,  1.39s/it]

[513/1000]
EN: PRASHAD scheme enhances pilgrimage tourism infrastructure across India.
ASM: দেৱাৰ বির্জীৱে বাৰে, লিৰি জিলাৰ ৰাদৰা মি কৰa ;  :  ).
--------------------------------------------------

Translating:  51%|█████████████▉             | 514/1000 [12:25<11:02,  1.36s/it]

[514/1000]
EN: Saudi Red Sea authority enforces international safety standards for marine tourism.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  52%|█████████████▉             | 515/1000 [12:27<10:39,  1.32s/it]

[515/1000]
EN: Saudi marine regulations protect Red Sea coral reef ecosystems.
ASM: দেৱাৰ বির্জীৱেৰে.
--------------------------------------------------

Translating:  52%|█████████████▉             | 516/1000 [12:28<10:57,  1.36s/it]

[516/1000]
EN: Saudi Red Sea tourism to add 85 billion riyals to GDP.
ASM: . জিৰে দৰা বিরীৱাৰ লিলাৰ ৰাদেৰি বাৰু মি्लॆ പ് āৰ্দ ) ।
--------------------------------------------------

Translating:  52%|█████████████▉             | 517/1000 [12:29<10:18,  1.28s/it]

[517/1000]
EN: Red Sea tourism creates 210,000 Saudi jobs by 2030.
ASM: 0. দৰে বির্জাৰীৰ জেৱাৰৰ লাৰিলে ।
--------------------------------------------------

Translating:  52%|█████████████▉             | 518/1000 [12:30<10:06,  1.26s/it]

[518/1000]
EN: Indian Railways recovers only fraction of 4,087 crore dues.
ASM: , দেৱাৰ বির্জীৰ ৰিলে লাৰি জিমি विरोधी বাৰে ;
--------------------------------------------------

Translating:  52%|██████████████             | 519/1000 [12:32<10:06,  1.26s/it]

[519/1000]
EN: RLDA develops only fraction of railway land for commercial use.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  52%|██████████████             | 520/1000 [12:32<08:51,  1.11s/it]

[520/1000]
EN: Central Railway announces train diversions for Dasara and Diwali.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  52%|██████████████             | 521/1000 [12:34<09:30,  1.19s/it]

[521/1000]
EN: SCR cancels 69 trains due to operational requirements.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লাৰু মি विरोधी āৰা а : ?
--------------------------------------------------

Translating:  52%|██████████████             | 522/1000 [12:35<09:34,  1.20s/it]

[522/1000]
EN: South Central Railway diverts 29 trains for festival management.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জেৰি പ 29 লাৰু а : ?
--------------------------------------------------

Translating:  52%|██████████████             | 523/1000 [12:36<09:45,  1.23s/it]

[523/1000]
EN: Indian Railways announces 18 partially cancelled train services.
ASM: দৰি জেৱাৰ বিরীৰে লিমি 18 ৰালাৰ্দেৰা বাৰু āৰ तिकिल् а.
--------------------------------------------------

Translating:  52%|██████████████▏            | 524/1000 [12:38<09:40,  1.22s/it]

[524/1000]
EN: Three trains rescheduled by South Central Railway authority.
ASM: দৰে জাৰি বিরীৱাৰৰ ৰালাৰ লিমি विरोधी র্দেৱেৰা বাৰু. : ?
--------------------------------------------------

Translating:  52%|██████████████▏            | 525/1000 [12:39<09:56,  1.26s/it]

[525/1000]
EN: SCR cancels total 119 train services during peak season.
ASM: . দৰে জিৱাৰ বিরীৰ ৰালে, বাৰি লাৰ্দেৰা মি 1 119 പ് а?
--------------------------------------------------

Translating:  53%|██████████████▏            | 526/1000 [12:40<10:00,  1.27s/it]

[526/1000]
EN: Disney Cruise Line debuts Disney Destiny vessel in 2025.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লাৰু মি विरोधी а 2025 :
--------------------------------------------------

Translating:  53%|██████████████▏            | 527/1000 [12:41<09:25,  1.20s/it]

[527/1000]
EN: Norwegian Cruise Line adds Norwegian Aqua to fleet.
ASM: দেৱাৰ বিজৰী র্দৰে বাৰি জিলে,.
--------------------------------------------------

Translating:  53%|██████████████▎            | 528/1000 [12:42<08:23,  1.07s/it]

[528/1000]
EN: Royal Caribbean launches Star of the Seas cruise ship.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  53%|██████████████▎            | 529/1000 [12:43<08:20,  1.06s/it]

[529/1000]
EN: Varanasi airport expands terminal to handle five million passengers.
ASM: দেৱাৰ বির্জীৰ ৰিলে, বাৰে লাৰি জিৰা.
--------------------------------------------------

Translating:  53%|██████████████▎            | 530/1000 [12:44<07:55,  1.01s/it]

[530/1000]
EN: Kashmir Railway line reaches Baramulla for all weather connectivity.
ASM: দৰে জাৰি বিরীৰ লিলাৰ ৰামি,.
--------------------------------------------------

Translating:  53%|██████████████▎            | 531/1000 [12:45<07:20,  1.07it/s]

[531/1000]
EN: Ayodhya airport commences commercial flight operations for pilgrims.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  53%|██████████████▎            | 532/1000 [12:46<07:22,  1.06it/s]

[532/1000]
EN: Chennai metro phase two extension connects airport to city centre.
ASM: দেৱাৰ বির্জীৰ ৰালাৰে বাৰি জিলে,.
--------------------------------------------------

Translating:  53%|██████████████▍            | 533/1000 [12:46<07:00,  1.11it/s]

[533/1000]
EN: Mumbai Trans Harbour Link reduces travel time to Navi Mumbai airport.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  53%|██████████████▍            | 534/1000 [12:48<07:54,  1.02s/it]

[534/1000]
EN: Kashi Vishwanath corridor transforms pilgrimage experience in Varanasi.
ASM: দেৱাৰ বির্জীৱে বাৰে, লি জিৰি ৰাদৰা মিলাৰু. : ?
--------------------------------------------------

Translating:  54%|██████████████▍            | 535/1000 [12:49<07:38,  1.01it/s]

[535/1000]
EN: Hyatt completes acquisition of Playa Hotels and Resorts.
ASM: দেৱাৰ বির্জে জীৱa বাৰি.
--------------------------------------------------

Translating:  54%|██████████████▍            | 536/1000 [12:50<08:39,  1.12s/it]

[536/1000]
EN: Hyatt adds fifteen beachfront properties across Mexico and Jamaica.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  54%|██████████████▍            | 537/1000 [12:51<08:32,  1.11s/it]

[537/1000]
EN: Hyatt acquires Secrets La Romana in Dominican Republic.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  54%|██████████████▌            | 538/1000 [12:52<07:56,  1.03s/it]

[538/1000]
EN: Dreams La Romana joins Hyatt portfolio through Playa acquisition.
ASM: দেৱাৰ বির্জে বাৰি মিৰে,.
--------------------------------------------------

Translating:  54%|██████████████▌            | 539/1000 [12:53<07:58,  1.04s/it]

[539/1000]
EN: Dreams Rose Hall in Montego Bay transfers to Hyatt ownership.
ASM: দেৱাৰ বির্জে জীৱে, লিলাৰ ৰামি বাৰে ;.
--------------------------------------------------

Translating:  54%|██████████████▌            | 540/1000 [12:54<08:02,  1.05s/it]

[540/1000]
EN: Hyatt Vivid Playa del Carmen added to hotel collection.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  54%|██████████████▌            | 541/1000 [12:55<08:34,  1.12s/it]

[541/1000]
EN: Sunscape Cancun becomes Hyatt property after Playa deal.
ASM: দৰিরে জাৱাৰ বিলে,.
--------------------------------------------------

Translating:  54%|██████████████▋            | 542/1000 [12:56<08:02,  1.05s/it]

[542/1000]
EN: Hotel infrastructure status unlocks private investment says Shekhawat.
ASM: দেৱাৰ বির্জীৱে জিলাৰ ৰালে ।
--------------------------------------------------

Translating:  54%|██████████████▋            | 543/1000 [12:57<07:49,  1.03s/it]

[543/1000]
EN: FICCI annual general meeting discusses tourism growth strategy.
ASM: দৰি জেৱাৰ বিরীৰে লিৰ্দেৰা.
--------------------------------------------------

Translating:  54%|██████████████▋            | 544/1000 [12:58<07:42,  1.01s/it]

[544/1000]
EN: Harsh Vardhan Agarwal highlights tourism as economic driver.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  55%|██████████████▋            | 545/1000 [13:00<09:04,  1.20s/it]

[545/1000]
EN: Anant Goenka praises Swadesh Darshan and PRASHAD initiatives.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  55%|██████████████▋            | 546/1000 [13:01<08:09,  1.08s/it]

[546/1000]
EN: Indian hotel industry seeks infrastructure status for tax benefits.
ASM: দৰি জেৱাৰ বিৰ্রীৰ ৰালে,.
--------------------------------------------------

Translating:  55%|██████████████▊            | 547/1000 [13:01<07:32,  1.00it/s]

[547/1000]
EN: Shangri-La Bengaluru hosts Chef Simone Loisi Italian culinary residency.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  55%|██████████████▊            | 548/1000 [13:02<07:02,  1.07it/s]

[548/1000]
EN: Chef Simone Loisi brings Southern Italian cuisine to Bangalore.
ASM: দৰে জাৰি বিরীৱাৰৰ ৰালাৰ.
--------------------------------------------------

Translating:  55%|██████████████▊            | 549/1000 [13:04<08:13,  1.10s/it]

[549/1000]
EN: Waterfall Ristorante Italiano chef showcases cuisine at Shangri-La.
ASM: দৰিরে জাৱাৰ বিৰে,.
--------------------------------------------------

Translating:  55%|██████████████▊            | 550/1000 [13:05<09:08,  1.22s/it]

[550/1000]
EN: Four Seasons Bengaluru transforms for Halloween 2025 celebrations.
ASM: . দৰে জাৰি বিরীৱাৰৰ লিলাৰ а 2025 ৰাদেৰা বাৰু яৰ্ बिरोधी মি ।
--------------------------------------------------

Translating:  55%|██████████████▉            | 551/1000 [13:07<10:11,  1.36s/it]

[551/1000]
EN: CUR8 hosts family friendly Halloween evening in Bengaluru.
ASM: দেৱাৰ বির্জীৰ ৰাদৰে বাৰি 8 লি জিমিৰ 4 লাৰ 11 āৰু क्कूटেৰা яৰ ) ।
--------------------------------------------------

Translating:  55%|██████████████▉            | 552/1000 [13:08<10:00,  1.34s/it]

[552/1000]
EN: Copitas bar ranks in Asia's 50 Best Bars list.
ASM: দেৱাৰ বির্জীৰ ৰালি, বাৰে জিৰি 50 লাৰু মি.
--------------------------------------------------

Translating:  55%|██████████████▉            | 553/1000 [13:10<10:22,  1.39s/it]

[553/1000]
EN: Four Seasons Bengaluru hosts Día de Muertos Halloween party.
ASM: দেৱাৰ বির্জে জীৱaৰ ৰালে, বাৰি লাৰে विरोधी মিৰা রিন্দৰু āৰ तिक  एतेऩुम्ाकिब ।
--------------------------------------------------

Translating:  55%|██████████████▉            | 554/1000 [13:11<09:52,  1.33s/it]

[554/1000]
EN: Sheraton Hyderabad invites guests to Feast Halloween buffet.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰিলাৰু. : ?
--------------------------------------------------

Translating:  56%|██████████████▉            | 555/1000 [13:12<09:04,  1.22s/it]

[555/1000]
EN: Chef Yugal Sharma represents North West Frontier cuisine at ITC.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  56%|███████████████            | 556/1000 [13:13<08:41,  1.17s/it]

[556/1000]
EN: Royal Afghan assistant master chef promotes rustic Indian cuisine.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  56%|███████████████            | 557/1000 [13:14<08:47,  1.19s/it]

[557/1000]
EN: The Leela Hyderabad hosts Chef Picched three-day Thai culinary showcase.
ASM: দেৱাৰ বির্জীৰ ৰালে, জিৰি লাৰে বাৰু মিন্দৰা. : ?
--------------------------------------------------

Translating:  56%|███████████████            | 558/1000 [13:16<09:43,  1.32s/it]

[558/1000]
EN: Chef Picched Paoleng brings authentic Bangkok cuisine to Hyderabad.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  56%|███████████████            | 559/1000 [13:17<09:38,  1.31s/it]

[559/1000]
EN: Marriott Executive Apartments Bengaluru unveils Madras Kitchen restaurant.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  56%|███████████████            | 560/1000 [13:18<08:51,  1.21s/it]

[560/1000]
EN: Madras Kitchen pays homage to South Indian gastronomic heritage.
ASM: দেৱাৰ বির্জীৱে জিমিৰে,.
--------------------------------------------------

Translating:  56%|███████████████▏           | 561/1000 [13:19<08:53,  1.21s/it]

[561/1000]
EN: ITC Grand Bharat chef shares Diwali festive dinner hosting tips.
ASM: দেৱাৰ জির্বিলাৰী.
--------------------------------------------------

Translating:  56%|███████████████▏           | 562/1000 [13:21<09:17,  1.27s/it]

[562/1000]
EN: Marriott Executive Apartments Hyderabad celebrates Hyderabadi dessert heritage.
ASM: দেৱাৰ বির্জীৱে জিলি.
--------------------------------------------------

Translating:  56%|███████████████▏           | 563/1000 [13:22<10:05,  1.38s/it]

[563/1000]
EN: 4Note culinary hot spot opens with four kitchens concept.
ASM: দৰে বির্জাৰ জীৱাৰৰ লিলাৰ ৰামি বাৰি, রিন্দেৰা പ 29 क्कूटি्लॆ āৰ तिक ।
--------------------------------------------------

Translating:  56%|███████████████▏           | 564/1000 [13:24<09:56,  1.37s/it]

[564/1000]
EN: Zuma Abu Dhabi maintains global legacy restaurant standards.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  56%|███████████████▎           | 565/1000 [13:25<09:44,  1.34s/it]

[565/1000]
EN: Dubai chocolate craze triggers global pistachio shortage crisis.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  57%|███████████████▎           | 566/1000 [13:26<08:39,  1.20s/it]

[566/1000]
EN: Indian Hotels Company signs new Taj property in Lucknow.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  57%|███████████████▎           | 567/1000 [13:27<07:53,  1.09s/it]

[567/1000]
EN: Oberoi Group announces luxury resort opening in Ranthambhore.
ASM: দেৱাৰ বির্জে জীৱaৰ ৰালে,.
--------------------------------------------------

Translating:  57%|███████████████▎           | 568/1000 [13:27<07:12,  1.00s/it]

[568/1000]
EN: Lemon Tree Hotels expands northeast presence with Guwahati property.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  57%|███████████████▎           | 569/1000 [13:29<07:24,  1.03s/it]

[569/1000]
EN: Marriott International to open 50th property in India by 2026.
ASM: দেৱাৰ., জির্বিলাৰীৰ ৰালে ।
--------------------------------------------------

Translating:  57%|███████████████▍           | 570/1000 [13:30<07:46,  1.09s/it]

[570/1000]
EN: Radisson Hotel Group targets 200 hotels across India by 2027.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে লাৰি 200 জিমি а 2027?
--------------------------------------------------

Translating:  57%|███████████████▍           | 571/1000 [13:31<07:07,  1.00it/s]

[571/1000]
EN: OYO announces international expansion into Vietnam and Indonesia.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  57%|███████████████▍           | 572/1000 [13:32<07:38,  1.07s/it]

[572/1000]
EN: MakeMyTrip partners with IHCL for exclusive holiday packages.
ASM: দেৱাৰ বির্জীৱে, লাৰে বাৰি জিলিৰ ৰাদৰা. : ?
--------------------------------------------------

Translating:  57%|███████████████▍           | 573/1000 [13:33<07:59,  1.12s/it]

[573/1000]
EN: Maha Kumbh Mela creates one million jobs for local families.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  57%|███████████████▍           | 574/1000 [13:34<08:10,  1.15s/it]

[574/1000]
EN: Boat services at Kumbh earn families collective 30 crore rupees.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে লাৰি 30 জিমি а : ?
--------------------------------------------------

Translating:  57%|███████████████▌           | 575/1000 [13:35<07:17,  1.03s/it]

[575/1000]
EN: The Guardian describes Prayagraj Kumbh as pop-up megacity.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  58%|███████████████▌           | 576/1000 [13:36<06:56,  1.02it/s]

[576/1000]
EN: Maharashtra Economic Council reports Kumbh employment generation.
ASM: দেৱাৰ বির্জে জিলে,.
--------------------------------------------------

Translating:  58%|███████████████▌           | 577/1000 [13:37<07:36,  1.08s/it]

[577/1000]
EN: FIFA Club World Cup 2025 brings global visitors to host cities.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে বাৰি জিলে, মিৰা লাৰু പ് 2025 ) ।
--------------------------------------------------

Translating:  58%|███████████████▌           | 578/1000 [13:38<07:43,  1.10s/it]

[578/1000]
EN: Wimbledon 2025 witnesses global unity through international tennis.
ASM: . দৰে জাৰি বিরীৱাৰৰ বালাৰ্লিৰ аᱹ я : ?
--------------------------------------------------

Translating:  58%|███████████████▋           | 579/1000 [13:40<07:53,  1.12s/it]

[579/1000]
EN: Sikh pilgrims receive Pakistani visas after Operation Sindoor.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  58%|███████████████▋           | 580/1000 [13:41<08:41,  1.24s/it]

[580/1000]
EN: Harjindarpal Singh secures passport and Pakistan visa for pilgrimage.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  58%|███████████████▋           | 581/1000 [13:42<08:06,  1.16s/it]

[581/1000]
EN: First Sikh Jathas travel to Pakistan post visa ban reversal.
ASM: দেৱাৰ বির্জীৰ ৰালাৰে বাৰি জিলে ।
--------------------------------------------------

Translating:  58%|███████████████▋           | 582/1000 [13:43<08:26,  1.21s/it]

[582/1000]
EN: FIDE names World Chess Cup trophy after Viswanathan Anand.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  58%|███████████████▋           | 583/1000 [13:44<07:40,  1.11s/it]

[583/1000]
EN: Panjim hosts FIDE World Chess Cup with Anand trophy.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  58%|███████████████▊           | 584/1000 [13:45<07:00,  1.01s/it]

[584/1000]
EN: Krishna Janmashtami procession turns tragic in Ramanthapur.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  58%|███████████████▊           | 585/1000 [13:47<08:05,  1.17s/it]

[585/1000]
EN: Ten-foot chariot touches live wire killing five devotees.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  59%|███████████████▊           | 586/1000 [13:47<07:17,  1.06s/it]

[586/1000]
EN: Hyderabad celebrates Ganesh festival with large screen displays.
ASM: দেৱাৰ বির্জীৰ ৰাদৰে.
--------------------------------------------------

Translating:  59%|███████████████▊           | 587/1000 [13:48<06:42,  1.03it/s]

[587/1000]
EN: Begum Bazaar jam-packed for night long festival celebrations.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  59%|███████████████▉           | 588/1000 [13:49<06:41,  1.02it/s]

[588/1000]
EN: Muslim leader Sadeq Siraj organizes eye camp for community.
ASM: দেৱাৰ বিজৰ ৰার্দৰী জিলে,.
--------------------------------------------------

Translating:  59%|███████████████▉           | 589/1000 [13:51<07:47,  1.14s/it]

[589/1000]
EN: Hyderabad pandals adopt traditional themes for Ganesh Chaturthi.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  59%|███████████████▉           | 590/1000 [13:52<08:10,  1.20s/it]

[590/1000]
EN: Shuja Ifteqari requests Chief Minister Revanth Reddy for arrangements.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  59%|███████████████▉           | 591/1000 [13:53<07:17,  1.07s/it]

[591/1000]
EN: SOCIAL Hyderabad hosts She's a Phataka Diwali celebration bash.
ASM: দেৱাৰ বির্জে জীৱaৰ ৰিলে,.
--------------------------------------------------

Translating:  59%|███████████████▉           | 592/1000 [13:54<06:59,  1.03s/it]

[592/1000]
EN: Hyderabad soaked in festival fervour with rain showers.
ASM: দেৱাৰ বির্জে জীৱaৰ ৰালে,.
--------------------------------------------------

Translating:  59%|████████████████           | 593/1000 [13:55<07:29,  1.10s/it]

[593/1000]
EN: Dasara trains diverted to manage two lakh passenger footfall.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে জেৰি লাৰু মিৰা রিন্দৰ स्बराज ।
--------------------------------------------------

Translating:  59%|████████████████           | 594/1000 [13:56<08:18,  1.23s/it]

[594/1000]
EN: New passenger routes planned for Dasara and Diwali travel.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লাৰু মি विरोधी яৰ ) āৰা атিন্দৰ तिकिल् घटनुपি ।
--------------------------------------------------

Translating:  60%|████████████████           | 595/1000 [13:58<08:31,  1.26s/it]

[595/1000]
EN: Hyderabad kiosks offer Ganesh idols across every street.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  60%|████████████████           | 596/1000 [13:59<08:05,  1.20s/it]

[596/1000]
EN: Indian Navy monitors every Chinese vessel in Indian Ocean.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে জেৰি লাৰু.
--------------------------------------------------

Translating:  60%|████████████████           | 597/1000 [14:00<07:17,  1.09s/it]

[597/1000]
EN: Vice Admiral Sanjay Vatsayan confirms continuous maritime surveillance.
ASM: দেৱাৰ জির্বিলাৰীৰ ৰিলে,.
--------------------------------------------------

Translating:  60%|████████████████▏          | 598/1000 [14:01<07:48,  1.17s/it]

[598/1000]
EN: Goa tourism department announces calendar of winter festivals.
ASM: বিৰে দৰি জাৰ রীৱাৰৰ.
--------------------------------------------------

Translating:  60%|████████████████▏          | 599/1000 [14:03<08:43,  1.30s/it]

[599/1000]
EN: Jaipur Literature Festival attracts 50,000 book lovers from abroad.
ASM: . দেৱাৰ জির্বিলাৰীৰ ৰালে, বাৰে মি āৰি 5 000 क्कूटিৰু বেৰা ।
--------------------------------------------------

Translating:  60%|████████████████▏          | 600/1000 [14:04<09:31,  1.43s/it]

[600/1000]
EN: Rann Utsav begins in Kutch with tent city bookings full.
ASM: দেৱাৰ বির্জিলা,.
--------------------------------------------------

Translating:  60%|████████████████▏          | 601/1000 [14:06<10:12,  1.54s/it]

[601/1000]
EN: Hornbill Festival showcases Naga heritage in Kisama heritage village.
ASM: দৰে জাৰি বিরীৱাৰৰ ৰালাৰ.
--------------------------------------------------

Translating:  60%|████████████████▎          | 602/1000 [14:08<10:25,  1.57s/it]

[602/1000]
EN: Ganga Aarti at Varanasi draws record international tourist attendance.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  60%|████████████████▎          | 603/1000 [14:09<08:51,  1.34s/it]

[603/1000]
EN: Pahalgam terror attack kills twenty-six tourists including foreigners.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  60%|████████████████▎          | 604/1000 [14:10<08:40,  1.31s/it]

[604/1000]
EN: Terrorists attack Baisaran meadows killing twenty-six civilian tourists.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  60%|████████████████▎          | 605/1000 [14:11<09:15,  1.41s/it]

[605/1000]
EN: Two foreign tourists among twenty-six dead in Pahalgam attack.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে লাৰি জেৰা মিৰু রিন্দ ) क्कूटি्लॆ āৰat ्रॆक्कা तिक ।
--------------------------------------------------

Translating:  61%|████████████████▎          | 606/1000 [14:13<09:37,  1.47s/it]

[606/1000]
EN: Operation Sindoor launched following deadly Pahalgam tourist attack.
ASM: দৰি জেৱাৰ বিরীৰে.
--------------------------------------------------

Translating:  61%|████████████████▍          | 607/1000 [14:14<08:43,  1.33s/it]

[607/1000]
EN: Saudi Arabia minister Adel Al-Jubeir arrives in Delhi post Operation Sindoor.
ASM: দেৱাৰ বির্জীৰ ৰিলে. : ?
--------------------------------------------------

Translating:  61%|████████████████▍          | 608/1000 [14:15<07:53,  1.21s/it]

[608/1000]
EN: Iranian Foreign Minister Araghchi visits New Delhi amid tensions.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  61%|████████████████▍          | 609/1000 [14:16<08:00,  1.23s/it]

[609/1000]
EN: Delhi Red Fort blast leaves fourteen dead and several injured.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  61%|████████████████▍          | 610/1000 [14:17<07:54,  1.22s/it]

[610/1000]
EN: High intensity explosion outside Red Fort kills fourteen people.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  61%|████████████████▍          | 611/1000 [14:19<08:53,  1.37s/it]

[611/1000]
EN: Supreme Court upholds Christian Army officer Samuel Kamalesan dismissal.
ASM: দৰি জেৱাৰ বিরীৰে. : ?
--------------------------------------------------

Translating:  61%|████████████████▌          | 612/1000 [14:20<07:52,  1.22s/it]

[612/1000]
EN: Army officer refuses temple pooja entry leading to dismissal.
ASM: দেৱাৰ বিজৰ ৰারে জীৱে,.
--------------------------------------------------

Translating:  61%|████████████████▌          | 613/1000 [14:21<07:02,  1.09s/it]

[613/1000]
EN: Chief Justice Surya Kant terms refusal grossest kind of indiscipline.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  61%|████████████████▌          | 614/1000 [14:22<07:30,  1.17s/it]

[614/1000]
EN: Saif Ali Khan undergoes surgery after knife attack at residence.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  62%|████████████████▌          | 615/1000 [14:23<07:05,  1.10s/it]

[615/1000]
EN: Intruder attacks Bollywood actor Saif Ali Khan in Mumbai.
ASM: দেৱাৰ বির্জে জীৱিৰ ৰালা,.
--------------------------------------------------

Translating:  62%|████████████████▋          | 616/1000 [14:24<06:44,  1.05s/it]

[616/1000]
EN: Mumbai police identify accused in Saif Ali Khan attack case.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  62%|████████████████▋          | 617/1000 [14:25<07:14,  1.13s/it]

[617/1000]
EN: Actor discharged five days after hospitalization following attack.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  62%|████████████████▋          | 618/1000 [14:27<07:53,  1.24s/it]

[618/1000]
EN: Tihar jail probe reveals racket charging for free inmate meetings.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  62%|████████████████▋          | 619/1000 [14:28<07:35,  1.19s/it]

[619/1000]
EN: Undercover officials exposed illegal mulakat charges at Tihar.
ASM: দেৱাৰ বির্জে জীৱলৰ ৰামি,.
--------------------------------------------------

Translating:  62%|████████████████▋          | 620/1000 [14:29<06:51,  1.08s/it]

[620/1000]
EN: Tihar transfers twenty-five data entry operators after tout investigation.
ASM: দৰে জাৰি বিরীৰ লাৱাৰৰ ৰিলে,.
--------------------------------------------------

Translating:  62%|████████████████▊          | 621/1000 [14:30<06:19,  1.00s/it]

[621/1000]
EN: Biometric authentication introduced at Tihar Jail for security.
ASM: দেৱাৰ বির্জে.
--------------------------------------------------

Translating:  62%|████████████████▊          | 622/1000 [14:30<05:58,  1.05it/s]

[622/1000]
EN: Supreme Court declines virtual appearance exemption for chief secretaries.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  62%|████████████████▊          | 623/1000 [14:31<05:57,  1.05it/s]

[623/1000]
EN: States sleeping over stray dog sterilization orders says Supreme Court.
ASM: দেৱাৰ বির্জীৱে লিমি লাৰে,.
--------------------------------------------------

Translating:  62%|████████████████▊          | 624/1000 [14:32<05:59,  1.04it/s]

[624/1000]
EN: Passenger forced to write letter after Delhi airport assault.
ASM: দৰে জাৰি বিরীৱাৰৰ ৰালাৰ লিমি,.
--------------------------------------------------

Translating:  62%|████████████████▉          | 625/1000 [14:33<05:40,  1.10it/s]

[625/1000]
EN: Passenger claims pressure to avoid police complaint filing.
ASM: দৰে জাৰি বিরীৱাৰৰ ৰিলা,.
--------------------------------------------------

Translating:  63%|████████████████▉          | 626/1000 [14:35<06:28,  1.04s/it]

[626/1000]
EN: US forces seize oil tanker off Venezuela for narco-terrorism.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  63%|████████████████▉          | 627/1000 [14:35<05:58,  1.04it/s]

[627/1000]
EN: US Coast Guard apprehends tanker with Department of Defense backing.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  63%|████████████████▉          | 628/1000 [14:36<05:46,  1.07it/s]

[628/1000]
EN: Supreme Court denies relief to mosque seeking loudspeaker permission.
ASM: দেৱাৰ বির্জীৱে লাৰে ৰালে ।
--------------------------------------------------

Translating:  63%|████████████████▉          | 629/1000 [14:37<06:11,  1.00s/it]

[629/1000]
EN: Nagpur bench rules no religion mandates prayers with amplifiers.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  63%|█████████████████          | 630/1000 [14:38<05:37,  1.10it/s]

[630/1000]
EN: Cruise Saudi brand operations commence with Red Sea licences.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  63%|█████████████████          | 631/1000 [14:39<06:15,  1.02s/it]

[631/1000]
EN: Marina services added to Saudi marine tourism portfolio.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  63%|█████████████████          | 632/1000 [14:40<05:52,  1.04it/s]

[632/1000]
EN: Recreational marine activities licensed by Saudi Red Sea Authority.
ASM: দৰি জেৱাৰ বিরীৰ ৰালা,.
--------------------------------------------------

Translating:  63%|█████████████████          | 633/1000 [14:42<07:09,  1.17s/it]

[633/1000]
EN: Saudi Arabia enforces qualified crews for marine tourism operations.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  63%|█████████████████          | 634/1000 [14:43<07:40,  1.26s/it]

[634/1000]
EN: Red Sea unregulated maritime activity concerns addressed by licences.
ASM: দৰে জাৰি বিরীৰ. : ?
--------------------------------------------------

Translating:  64%|█████████████████▏         | 635/1000 [14:44<06:56,  1.14s/it]

[635/1000]
EN: Indian cruise tourism gets boost with ten new terminals.
ASM: দৰে জাৰি বিরীৱাৰৰ লাৰ্লিৰ.
--------------------------------------------------

Translating:  64%|█████████████████▏         | 636/1000 [14:45<07:20,  1.21s/it]

[636/1000]
EN: Disney Destiny becomes marquee cruise debut of 2025.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 25 2025 ;
--------------------------------------------------

Translating:  64%|█████████████████▏         | 637/1000 [14:47<07:47,  1.29s/it]

[637/1000]
EN: Norwegian Aqua adds fleet capacity to Norwegian Cruise Line.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  64%|█████████████████▏         | 638/1000 [14:48<07:56,  1.32s/it]

[638/1000]
EN: Royal Caribbean Star of the Seas enters service in 2025.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মিৰি লাৰু জিন্দৰা പ് 2025 : ?
--------------------------------------------------

Translating:  64%|█████████████████▎         | 639/1000 [14:49<06:58,  1.16s/it]

[639/1000]
EN: Cordelia Cruises announces Lakshadweep itineraries from Kochi.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  64%|█████████████████▎         | 640/1000 [14:50<06:28,  1.08s/it]

[640/1000]
EN: Water metro connectivity boosts tourism in Kochi backwaters.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  64%|█████████████████▎         | 641/1000 [14:52<07:11,  1.20s/it]

[641/1000]
EN: Mumbai cruise terminal handles record 100,000 passengers this year.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লাৰু মি 1, 00, 000?
--------------------------------------------------

Translating:  64%|█████████████████▎         | 642/1000 [14:52<06:35,  1.10s/it]

[642/1000]
EN: Ganga Vilas luxury cruise completes successful Brahmaputra season.
ASM: দেৱাৰ বির্জীৱে,.
--------------------------------------------------

Translating:  64%|█████████████████▎         | 643/1000 [14:53<06:14,  1.05s/it]

[643/1000]
EN: Kerala houseboat registrations cross one thousand operational vessels.
ASM: দেৱাৰ বির্জীৱে বাৰি জিলে,.
--------------------------------------------------

Translating:  64%|█████████████████▍         | 644/1000 [14:54<06:11,  1.04s/it]

[644/1000]
EN: Andaman and Nicobar receive approval for international cruise tourism.
ASM: দৰে জাৰি বিরীৱাৰৰ ৰালাৰ লিমি,.
--------------------------------------------------

Translating:  64%|█████████████████▍         | 645/1000 [14:55<05:54,  1.00it/s]

[645/1000]
EN: Airbnb relaunches experiences feature for bookings and services.
ASM: দেৱাৰ বির্জীৱে লাৰে ৰালে,.
--------------------------------------------------

Translating:  65%|█████████████████▍         | 646/1000 [14:56<05:42,  1.03it/s]

[646/1000]
EN: Brian Chesky announces Airbnb services complementing home rentals.
ASM: দৰে জাৰি বিরীৰ লিৱা,.
--------------------------------------------------

Translating:  65%|█████████████████▍         | 647/1000 [14:58<06:30,  1.11s/it]

[647/1000]
EN: Olympic speed skater Arianna Fontana leads Airbnb training rides.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  65%|█████████████████▍         | 648/1000 [14:59<07:10,  1.22s/it]

[648/1000]
EN: Airbnb offers Alpine hikes with athlete guides in Italy.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  65%|█████████████████▌         | 649/1000 [15:01<07:51,  1.34s/it]

[649/1000]
EN: K-pop band SEVENTEEN curates music sessions for Airbnb.
ASM: দৰে জাৰি বিরীৰ. : ?
--------------------------------------------------

Translating:  65%|█████████████████▌         | 650/1000 [15:01<06:55,  1.19s/it]

[650/1000]
EN: Chance the Rapper partners with Airbnb for exclusive experiences.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  65%|█████████████████▌         | 651/1000 [15:02<06:33,  1.13s/it]

[651/1000]
EN: Economic uncertainty shifts traveller behaviour toward price sensitivity.
ASM: দেৱাৰ বির্জীৱে বাৰি জিলে,.
--------------------------------------------------

Translating:  65%|█████████████████▌         | 652/1000 [15:03<05:59,  1.03s/it]

[652/1000]
EN: Tourists choose off-the-beaten-path destinations influenced by social media.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  65%|█████████████████▋         | 653/1000 [15:04<05:35,  1.03it/s]

[653/1000]
EN: Travelers turn to AI-powered tools for trip planning.
ASM: দৰি জেৱাৰ বিরীৰ ৰালে ।
--------------------------------------------------

Translating:  65%|█████████████████▋         | 654/1000 [15:05<05:19,  1.08it/s]

[654/1000]
EN: Sustainable tourism gains traction among mindful travellers.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  66%|█████████████████▋         | 655/1000 [15:06<05:09,  1.12it/s]

[655/1000]
EN: Responsible travel interest grows among conscious tourists.
ASM: দৰিরে জাৱাৰ বীৱেৰে,.
--------------------------------------------------

Translating:  66%|█████████████████▋         | 656/1000 [15:07<05:06,  1.12it/s]

[656/1000]
EN: Less-crowded destinations attract visitors avoiding overtourism.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  66%|█████████████████▋         | 657/1000 [15:08<05:47,  1.01s/it]

[657/1000]
EN: Business travel spending reaches 1.57 trillion dollars in 2025.
ASM: . দৰিরে জাৱাৰ বিলিৰীৰ্দেৰে, ाय़ᱹ а : я- ;
--------------------------------------------------

Translating:  66%|█████████████████▊         | 658/1000 [15:10<06:55,  1.21s/it]

[658/1000]
EN: Bleisure travel surge drives business trip extensions for leisure.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  66%|█████████████████▊         | 659/1000 [15:11<06:21,  1.12s/it]

[659/1000]
EN: Luxury travel shifts toward immersive experience based vacations.
ASM: দেৱাৰ বিজৰ ৰার্দৰে জীৱে,.
--------------------------------------------------

Translating:  66%|█████████████████▊         | 660/1000 [15:11<05:53,  1.04s/it]

[660/1000]
EN: Travvy Awards recognize top industry suppliers in November.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  66%|█████████████████▊         | 661/1000 [15:13<07:39,  1.35s/it]

[661/1000]
EN: TravelPulse announces 40 Under 40 honorees for second year.
ASM: . দৰে জাৰি বিরীৰ লিলাৰ ৰামি 40 āৰ্দে, বাৰা घटनৱাৰৰ яৰ ) പ്ৰু а : ायो- ;
--------------------------------------------------

Translating:  66%|█████████████████▊         | 662/1000 [15:15<07:27,  1.32s/it]

[662/1000]
EN: Travel Executive of the Year awarded at Travvy gala.
ASM: দেৱাৰ বিজৰ ৰার্দৰে জীৱে,.
--------------------------------------------------

Translating:  66%|█████████████████▉         | 663/1000 [15:16<07:30,  1.34s/it]

[663/1000]
EN: New members inducted into Travel Hall of Fame 2025.
ASM: . দৰিরে জাৱাৰ বীৱেৰে ৰিলে ।
--------------------------------------------------

Translating:  66%|█████████████████▉         | 664/1000 [15:17<06:35,  1.18s/it]

[664/1000]
EN: Young professionals recognized for innovation and leadership.
ASM: দৰি জেৱাৰ বিৰ্রীৰ,.
--------------------------------------------------

Translating:  66%|█████████████████▉         | 665/1000 [15:18<06:57,  1.25s/it]

[665/1000]
EN: FIFA World Cup 2025 travel bookings exceed host city expectations.
ASM: . দেৱাৰ বির্জীৰ ৰালাৰে লিমি জিন্দৰা বাৰি्लॆ а 2025 : म्ः-, ;
--------------------------------------------------

Translating:  67%|█████████████████▉         | 666/1000 [15:20<07:01,  1.26s/it]

[666/1000]
EN: Solo female travel bookings increase forty percent year on year.
ASM: দেৱাৰ বিজৰ ৰারে জীৱে,.
--------------------------------------------------

Translating:  67%|██████████████████         | 667/1000 [15:21<07:06,  1.28s/it]

[667/1000]
EN: Wellness tourism emerges as fastest growing travel segment globally.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  67%|██████████████████         | 668/1000 [15:22<06:51,  1.24s/it]

[668/1000]
EN: Indian millennials prefer experiential travel over shopping vacations.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লা तिकৰা. : ?
--------------------------------------------------

Translating:  67%|██████████████████         | 669/1000 [15:23<06:14,  1.13s/it]

[669/1000]
EN: Workation packages gain popularity among remote corporate employees.
ASM: দৰি জেৱাৰ বিরীৰ ৰালে,.
--------------------------------------------------

Translating:  67%|██████████████████         | 670/1000 [15:24<06:10,  1.12s/it]

[670/1000]
EN: Culinary tourism drives foodies to regional Indian destinations.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  67%|██████████████████         | 671/1000 [15:25<05:53,  1.07s/it]

[671/1000]
EN: Night tourism initiatives launched by Maharashtra and Karnataka.
ASM: দেৱাৰ বির্জীৱে জিলাৰ ৰালে ।
--------------------------------------------------

Translating:  67%|██████████████████▏        | 672/1000 [15:26<05:28,  1.00s/it]

[672/1000]
EN: Astro tourism gains ground with dark sky parks in Ladakh.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  67%|██████████████████▏        | 673/1000 [15:27<05:14,  1.04it/s]

[673/1000]
EN: Film induced tourism boosts Kashmir valley hotel occupancy.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  67%|██████████████████▏        | 674/1000 [15:28<05:11,  1.05it/s]

[674/1000]
EN: Wedding tourism contributes five billion dollars to Indian economy.
ASM: দেৱাৰ বির্জে জীৱলৰ ৰাদৰে,.
--------------------------------------------------

Translating:  68%|██████████████████▏        | 675/1000 [15:29<05:30,  1.02s/it]

[675/1000]
EN: India promotes MICE tourism for meetings and exhibitions.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  68%|██████████████████▎        | 676/1000 [15:30<05:10,  1.04it/s]

[676/1000]
EN: West Bengal develops MICE tourism segments under Mamata Banerjee.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  68%|██████████████████▎        | 677/1000 [15:31<05:18,  1.01it/s]

[677/1000]
EN: India positions itself as medical value travel destination.
ASM: দৰি জেৱাৰ বিরীৰে লিলাৰ ৰামিৰ্দে,.
--------------------------------------------------

Translating:  68%|██████████████████▎        | 678/1000 [15:32<05:25,  1.01s/it]

[678/1000]
EN: Wellness tourism positions India as holistic healing leader.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  68%|██████████████████▎        | 679/1000 [15:33<05:52,  1.10s/it]

[679/1000]
EN: Concert tourism attracts international visitors to Indian music festivals.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  68%|██████████████████▎        | 680/1000 [15:34<05:20,  1.00s/it]

[680/1000]
EN: Gajendra Shekhawat highlights India's concert tourism potential.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  68%|██████████████████▍        | 681/1000 [15:35<05:34,  1.05s/it]

[681/1000]
EN: India promotes integrated rehabilitation pathways for medical tourists.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  68%|██████████████████▍        | 682/1000 [15:36<06:11,  1.17s/it]

[682/1000]
EN: Business travel makes significant comeback post pandemic.
ASM: দেৱাৰ বির্জীৱে বাৰি জিলে ।
--------------------------------------------------

Translating:  68%|██████████████████▍        | 683/1000 [15:38<06:33,  1.24s/it]

[683/1000]
EN: Companies increase trip volumes and expand travel budgets.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  68%|██████████████████▍        | 684/1000 [15:39<06:08,  1.17s/it]

[684/1000]
EN: In-person collaboration demand drives business travel recovery.
ASM: দৰি জেৱাৰ বির্লাীৰ ৰালে,.
--------------------------------------------------

Translating:  68%|██████████████████▍        | 685/1000 [15:40<05:21,  1.02s/it]

[685/1000]
EN: Hyderabad International Convention Centre hosts global pharmaceutical summit.
ASM: দেৱাৰ বির্জে.
--------------------------------------------------

Translating:  69%|██████████████████▌        | 686/1000 [15:41<05:32,  1.06s/it]

[686/1000]
EN: Bharat Mandapam witnesses record MICE bookings for fiscal year.
ASM: দেৱাৰ বির্জীৰ ৰিলে, বাৰে লাৰি জিমি विरोधी...
--------------------------------------------------

Translating:  69%|██████████████████▌        | 687/1000 [15:42<05:59,  1.15s/it]

[687/1000]
EN: Medical tourism arrivals cross pre-Covid levels with six lakh visitors.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  69%|██████████████████▌        | 688/1000 [15:43<05:25,  1.04s/it]

[688/1000]
EN: AYUSH wellness centres attract foreign tourists for traditional treatments.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  69%|██████████████████▌        | 689/1000 [15:44<06:04,  1.17s/it]

[689/1000]
EN: Delhi NCR hotels report seventy percent occupancy from corporate travellers.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  69%|██████████████████▋        | 690/1000 [15:45<05:30,  1.07s/it]

[690/1000]
EN: Maha Kumbh infrastructure delivers long-term tourism economic benefits.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  69%|██████████████████▋        | 691/1000 [15:46<05:58,  1.16s/it]

[691/1000]
EN: Venice entry fee revenues fund city upkeep and travel management.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  69%|██████████████████▋        | 692/1000 [15:47<05:22,  1.05s/it]

[692/1000]
EN: Critics question Venice day-tripper fee effectiveness for crowd control.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  69%|██████████████████▋        | 693/1000 [15:49<05:47,  1.13s/it]

[693/1000]
EN: Bulgaria joins Eurozone as twenty-first member on January 1 2026.
ASM: 2026 দৰে জাৰি বিরীৱাৰৰ লিমিলাৰ বাৰ্দেৰা āৰু яৰ 11 а.
--------------------------------------------------

Translating:  69%|██████████████████▋        | 694/1000 [15:49<05:21,  1.05s/it]

[694/1000]
EN: Both Lev and Euro accepted in Bulgaria during January transition.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  70%|██████████████████▊        | 695/1000 [15:52<06:50,  1.35s/it]

[695/1000]
EN: Lufthansa announces daily Frankfurt-Bengaluru flights starting March 2026.
ASM: . দৰে জাৰি বিরীৱাৰৰ লিমি ৰালাৰ বাৰু а 2026 āৰ্দে, яৰ ) ।
--------------------------------------------------

Translating:  70%|██████████████████▊        | 696/1000 [15:53<06:44,  1.33s/it]

[696/1000]
EN: Alliance Air introduces direct flights from Delhi to Darbhanga.
ASM: দেৱাৰ বির্জিলা,.
--------------------------------------------------

Translating:  70%|██████████████████▊        | 697/1000 [15:54<06:52,  1.36s/it]

[697/1000]
EN: Emirates deploys A380 on Ahmedabad-Dubai route for winter season.
ASM: . দেৱাৰ বিজৰ ৰার্দৰে জীৱে, বাৰি 380 লিমি লাৰ तिकৰু яৰ ) ।
--------------------------------------------------

Translating:  70%|██████████████████▊        | 698/1000 [15:56<07:05,  1.41s/it]

[698/1000]
EN: fly91 commences operations from Goa to Hyderabad and Pune.
ASM: দেৱাৰ বিজৰ ৰারে জীৱa বাৰে, লাৰি লিমি 1 99 āৰু яৰ ) ।
--------------------------------------------------

Translating:  70%|██████████████████▊        | 699/1000 [15:57<06:46,  1.35s/it]

[699/1000]
EN: British Airways resumes London-Chennai service after four-year hiatus.
ASM: দেৱাৰ বির্জীৰ ৰালে, জিৰে বাৰি মি विरोधी লাৰু. : ?
--------------------------------------------------

Translating:  70%|██████████████████▉        | 700/1000 [15:58<06:03,  1.21s/it]

[700/1000]
EN: Go First employees protest outside NCLT over unpaid salaries.
ASM: দেৱাৰ বির্জে জীৱলৰ ৰামি,.
--------------------------------------------------

Translating:  70%|██████████████████▉        | 701/1000 [15:59<05:29,  1.10s/it]

[701/1000]
EN: Saudi carrier Flynas plans direct Riyadh-Lucknow operations by April.
ASM: দেৱাৰ বিজৰ ৰারে জীৱে,.
--------------------------------------------------

Translating:  70%|██████████████████▉        | 702/1000 [15:59<04:57,  1.00it/s]

[702/1000]
EN: Flybig announces daily flights from Guwahati to Imphal and Agartala.
ASM: দেৱাৰ বির্জীৰ ৰালা,.
--------------------------------------------------

Translating:  70%|██████████████████▉        | 703/1000 [16:01<05:30,  1.11s/it]

[703/1000]
EN: Kolkata airport wins cleanest airport award in 15-25 million category.
ASM: -. দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লাৰু মিন্দৰা പ് : ?
--------------------------------------------------

Translating:  70%|███████████████████        | 704/1000 [16:02<05:46,  1.17s/it]

[704/1000]
EN: Patna airport's new terminal to handle forty lakh passengers annually.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  70%|███████████████████        | 705/1000 [16:03<05:15,  1.07s/it]

[705/1000]
EN: Fog forces thirty-two flight diversions at Chandigarh airport.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  71%|███████████████████        | 706/1000 [16:04<04:45,  1.03it/s]

[706/1000]
EN: Ethiopian Airlines considers Mumbai and Delhi as new African hub.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  71%|███████████████████        | 707/1000 [16:05<05:01,  1.03s/it]

[707/1000]
EN: IndiGo passenger dies aboard Delhi-Bengaluru flight mid-air.
ASM: দেৱাৰ বির্জে বাৰি.
--------------------------------------------------

Translating:  71%|███████████████████        | 708/1000 [16:06<05:13,  1.07s/it]

[708/1000]
EN: VietJet Air announces daily Hanoi-Ahmedabad service from December.
ASM: দৰে জাৰি বিরীৱাৰৰ ৰালাৰ.
--------------------------------------------------

Translating:  71%|███████████████████▏       | 709/1000 [16:07<05:31,  1.14s/it]

[709/1000]
EN: Odisha government approves ten new tourism circuits for development.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  71%|███████████████████▏       | 710/1000 [16:09<05:56,  1.23s/it]

[710/1000]
EN: Madhya Pradesh unveils film tourism policy with 25 percent subsidy.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে লাৰি 25 জিমি āৰু яৰ ) ।
--------------------------------------------------

Translating:  71%|███████████████████▏       | 711/1000 [16:10<06:20,  1.32s/it]

[711/1000]
EN: Gujarat grants industry status to homestays and farmstays.
ASM: দেৱাৰ বির্জীৰ ৰিলে, বাৰে জিৰি লাৰু মিন্দৰা āৰायला яৰ ) রি विरोधी പ് तिक ।
--------------------------------------------------

Translating:  71%|███████████████████▏       | 712/1000 [16:11<05:54,  1.23s/it]

[712/1000]
EN: Himachal Pradesh caps tourist entry to Manali and Rohtang Pass.
ASM: দেৱাৰ বির্জীৰ ৰিলে, লাৰে বাৰি মিৰু.
--------------------------------------------------

Translating:  71%|███████████████████▎       | 713/1000 [16:13<05:58,  1.25s/it]

[713/1000]
EN: Kerala launches responsible tourism mission for waste-free destinations.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  71%|███████████████████▎       | 714/1000 [16:14<05:45,  1.21s/it]

[714/1000]
EN: Australia removes minimum bank balance requirement for Indian student visas.
ASM: দৰে জাৰি বির্দেীৰ লালে,.
--------------------------------------------------

Translating:  72%|███████████████████▎       | 715/1000 [16:15<06:21,  1.34s/it]

[715/1000]
EN: UK introduces Electronic Travel Authorisation for Indian passport holders.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  72%|███████████████████▎       | 716/1000 [16:16<05:55,  1.25s/it]

[716/1000]
EN: Saudi Arabia extends stopover visa validity from four to ninety-six hours.
ASM: দৰে জাৰি বিরীৰ লিৱাৰৰ র্দেলাৰ ৰামি,.
--------------------------------------------------

Translating:  72%|███████████████████▎       | 717/1000 [16:18<05:48,  1.23s/it]

[717/1000]
EN: Malaysia grants thirty-day visa-free entry to Indian nationals till December.
ASM: দৰে জাৰি বিরীৰ লিলাৱাৰৰ বার্দেৰা. : ?
--------------------------------------------------

Translating:  72%|███████████████████▍       | 718/1000 [16:19<05:55,  1.26s/it]

[718/1000]
EN: Thailand extends visa-free stay for Indians from thirty to sixty days.
ASM: দেৱাৰ বির্জীৰ ৰালে জিৰে, বাৰি মি विरोधी লাৰু রিন্দৰা. : ?
--------------------------------------------------

Translating:  72%|███████████████████▍       | 719/1000 [16:20<06:05,  1.30s/it]

[719/1000]
EN: Indonesia proposes visa-free entry for Indian tourists to boost Bali arrivals.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  72%|███████████████████▍       | 720/1000 [16:22<06:06,  1.31s/it]

[720/1000]
EN: European Parliament approves ETIAS system launch for mid-2026.
ASM: . দৰে জাৰি বিরীৱাৰৰ বাৰ্লাৰ লিমিৰ ৰাদে, പ്ৰু а : ?
--------------------------------------------------

Translating:  72%|███████████████████▍       | 721/1000 [16:22<05:22,  1.16s/it]

[721/1000]
EN: Sri Lanka cabinet approves visa-free entry for nationals of thirty-five countries.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  72%|███████████████████▍       | 722/1000 [16:23<05:10,  1.12s/it]

[722/1000]
EN: Waives visa fees for Indian senior citizens above sixty-five years.
ASM: দেৱাৰ বির্জি, জীৱে লিলাৰ ৰামি.
--------------------------------------------------

Translating:  72%|███████████████████▌       | 723/1000 [16:25<05:36,  1.21s/it]

[723/1000]
EN: Bhutan revises Sustainable Development Fee to one thousand two hundred rupees.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  72%|███████████████████▌       | 724/1000 [16:26<05:11,  1.13s/it]

[724/1000]
EN: Nepal allows Indian tourists to pay in rupees at immigration checkpoints.
ASM: দেৱাৰ বির্জীৱে লাৰে ৰালে,.
--------------------------------------------------

Translating:  72%|███████████████████▌       | 725/1000 [16:27<04:50,  1.05s/it]

[725/1000]
EN: Myanmar junta extends e-visa facility for Indian travellers.
ASM: দেৱাৰ বিজৰী র্দৰে,.
--------------------------------------------------

Translating:  73%|███████████████████▌       | 726/1000 [16:28<05:31,  1.21s/it]

[726/1000]
EN: Mauritius scraps PCR test requirement for fully vaccinated Indian visitors.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  73%|███████████████████▋       | 727/1000 [16:29<05:13,  1.15s/it]

[727/1000]
EN: Kenya removes visa requirement for all Indian passport holders.
ASM: দৰে জাৰি বিরীৱাৰৰ ৰালাৰ লিমি,.
--------------------------------------------------

Translating:  73%|███████████████████▋       | 728/1000 [16:31<05:51,  1.29s/it]

[728/1000]
EN: Rajasthan government launches mobile app for heritage hotel bookings.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  73%|███████████████████▋       | 729/1000 [16:32<05:53,  1.30s/it]

[729/1000]
EN: Assam receives fifty-five lakh domestic tourists during 2024-2025.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লাৰু মি्लॆ а 2024 : ?
--------------------------------------------------

Translating:  73%|███████████████████▋       | 730/1000 [16:34<06:07,  1.36s/it]

[730/1000]
EN: Hemanta Biswa Sarma credits improved law and order for tourism growth.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  73%|███████████████████▋       | 731/1000 [16:35<05:59,  1.34s/it]

[731/1000]
EN: Madhya Pradesh records 112.1 million tourist visits in 2024.
ASM: . বিৰে দৰা জীৱাৰ র্লালৰ ৰাম 11.1ৰি а, āᱹ
--------------------------------------------------

Translating:  73%|███████████████████▊       | 732/1000 [16:37<06:17,  1.41s/it]

[732/1000]
EN: Meghalaya welcomes twenty-one lakh visitors crossing pre-pandemic figures.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  73%|███████████████████▊       | 733/1000 [16:38<06:15,  1.41s/it]

[733/1000]
EN: Jammu and Kashmir registers two crore tourist footfall in 2025.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে, বাৰিলে জিমি লাৰু а 2025 ।
--------------------------------------------------

Translating:  73%|███████████████████▊       | 734/1000 [16:39<05:25,  1.22s/it]

[734/1000]
EN: LG Manoj Sinha announces highest ever tourist arrival in Kashmir Valley.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  74%|███████████████████▊       | 735/1000 [16:41<06:02,  1.37s/it]

[735/1000]
EN: Lakshadweep receives eighty-three thousand visitors after PM Modi visit.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  74%|███████████████████▊       | 736/1000 [16:42<05:57,  1.35s/it]

[736/1000]
EN: Uttarakhand witnesses five crore pilgrim visits to Char Dham shrines.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  74%|███████████████████▉       | 737/1000 [16:43<05:44,  1.31s/it]

[737/1000]
EN: Pushkar fair attracts fifteen lakh tourists including thirty thousand foreigners.
ASM: দেৱাৰ বির্জীৱে,.
--------------------------------------------------

Translating:  74%|███████████████████▉       | 738/1000 [16:44<05:08,  1.18s/it]

[738/1000]
EN: Surajkund Mela records forty-eight percent increase in international participation.
ASM: দৰি জেৱাৰ বির্রীৰ ৰালা,.
--------------------------------------------------

Translating:  74%|███████████████████▉       | 739/1000 [16:46<05:38,  1.30s/it]

[739/1000]
EN: Singapore welcomes 1.2 million Indian visitors becoming top source market.
ASM: . দেৱাৰ জির্বিলাৰীৰ ৰালে, বাৰে মিৰি  तीर्क्क ; а..
--------------------------------------------------

Translating:  74%|███████████████████▉       | 740/1000 [16:47<05:24,  1.25s/it]

[740/1000]
EN: Dubai hosts record 2.1 million Indian tourists in first half 2025.
ASM: . দৰিরে জাৱাৰ বিৰে, লাৰী ৰিলে ; а 2025?
--------------------------------------------------

Translating:  74%|████████████████████       | 741/1000 [16:48<05:35,  1.30s/it]

[741/1000]
EN: Thailand receives 1.8 million Indian travellers during January-October period.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মিৰি লাৰু জিন্দৰ ) പ് : ?
--------------------------------------------------

Translating:  74%|████████████████████       | 742/1000 [16:50<05:46,  1.34s/it]

[742/1000]
EN: Maldives sees forty percent drop in Indian tourist arrivals amid diplomatic row.
ASM: দেৱাৰ বির্জীৰ ৰালা,.
--------------------------------------------------

Translating:  74%|████████████████████       | 743/1000 [16:51<05:57,  1.39s/it]

[743/1000]
EN: Nepal earns 110 billion rupees from Indian tourists in fiscal year.
ASM: দেৱাৰ  বিজৰ ৰার্দৰে জীৱa āৰিলে ।
--------------------------------------------------

Translating:  74%|████████████████████       | 744/1000 [16:52<05:58,  1.40s/it]

[744/1000]
EN: Turkey welcomes three lakh Indian tourists targeting five lakh by year-end.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে লাৰি জিমিৰা āৰু রিন্দৰ ;.
--------------------------------------------------

Translating:  74%|████████████████████       | 745/1000 [16:54<05:34,  1.31s/it]

[745/1000]
EN: Egypt reports 1.5 lakh Indian arrivals aiming for three lakh target.
ASM: দেৱাৰ বিজৰী র্দৰে বাৰি জিলে,.
--------------------------------------------------

Translating:  75%|████████████████████▏      | 746/1000 [16:54<04:56,  1.17s/it]

[746/1000]
EN: Azerbaijan attracts two lakh Indian visitors visa-free policy credited.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  75%|████████████████████▏      | 747/1000 [16:56<05:30,  1.31s/it]

[747/1000]
EN: Georgia registers 1.75 lakh Indian tourist arrivals between January-September.
ASM: দৰিরে জাৱাৰ বীৱেৰে, লিলাৰ ৰামি বাৰু āৰ্দেন্দিৰ ) പ്ৰা  गोंधळরি्लॆ а..
--------------------------------------------------

Translating:  75%|████████████████████▏      | 748/1000 [16:57<04:53,  1.16s/it]

[748/1000]
EN: Kenya targets one lakh Indian tourists with aggressive marketing campaign.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  75%|████████████████████▏      | 749/1000 [16:58<04:25,  1.06s/it]

[749/1000]
EN: Udaipur airport gets new terminal building costing five hundred crore rupees.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  75%|████████████████████▎      | 750/1000 [16:59<05:00,  1.20s/it]

[750/1000]
EN: Rajkot airport renamed after former Prime Minister Morarji Desai.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  75%|████████████████████▎      | 751/1000 [17:01<05:26,  1.31s/it]

[751/1000]
EN: Noida International Airport to begin flight operations by April 2026.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে বাৰি লালে, জিমিৰা а 2026?
--------------------------------------------------

Translating:  75%|████████████████████▎      | 752/1000 [17:02<05:04,  1.23s/it]

[752/1000]
EN: Chennai airport opens dedicated lounge for transiting international passengers.
ASM: দেৱাৰ বিজৰী র্দৰে জিলে,.
--------------------------------------------------

Translating:  75%|████████████████████▎      | 753/1000 [17:03<05:04,  1.23s/it]

[753/1000]
EN: Guwahati-Rohingya railway project completes tunneling work in Mizoram.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  75%|████████████████████▎      | 754/1000 [17:04<04:27,  1.09s/it]

[754/1000]
EN: Katra-Delhi Vande Bharat Express reduces travel time by three hours.
ASM: দৰিরে জাৱাৰ বীৱে,.
--------------------------------------------------

Translating:  76%|████████████████████▍      | 755/1000 [17:05<04:05,  1.00s/it]

[755/1000]
EN: Mumbai-Ahmedabad bullet train project completes fifty percent of viaduct work.
ASM: দৰি জেৱাৰ বিরীৰে লি,.
--------------------------------------------------

Translating:  76%|████████████████████▍      | 756/1000 [17:06<04:46,  1.17s/it]

[756/1000]
EN: Indian Railways introduces 200 superfast trains for summer rush.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লাৰু মি विरोधी 200 āৰা яৰ )
--------------------------------------------------

Translating:  76%|████████████████████▍      | 757/1000 [17:07<04:19,  1.07s/it]

[757/1000]
EN: Kochi water metro adds four new routes connecting Vypin and Goshree islands.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  76%|████████████████████▍      | 758/1000 [17:08<04:14,  1.05s/it]

[758/1000]
EN: Ayodhya's Ram Path revamp completed ahead of Pran Pratishtha anniversary.
ASM: দৰি জেৱাৰ বির্রীৰ ৰালাৰে লি,.
--------------------------------------------------

Translating:  76%|████████████████████▍      | 759/1000 [17:09<03:55,  1.02it/s]

[759/1000]
EN: Kedarnath ropeway project gets environmental clearance from ministry.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  76%|████████████████████▌      | 760/1000 [17:10<04:13,  1.06s/it]

[760/1000]
EN: Hemkund Sahib helicopter service fares capped at five thousand rupees.
ASM: দেৱাৰ বির্জে জীৱে,.
--------------------------------------------------

Translating:  76%|████████████████████▌      | 761/1000 [17:11<04:08,  1.04s/it]

[761/1000]
EN: Statue of Unity adds laser show and sound and light attraction.
ASM: দেৱাৰ বির্জে বাৰি জীৱaৰ ৰালে ।
--------------------------------------------------

Translating:  76%|████████████████████▌      | 762/1000 [17:12<04:31,  1.14s/it]

[762/1000]
EN: Khajuraho airport receives international status for charter operations.
ASM: দেৱাৰ বিজৰ ৰারে জীৱে,.
--------------------------------------------------

Translating:  76%|████████████████████▌      | 763/1000 [17:14<04:44,  1.20s/it]

[763/1000]
EN: Puducherry tourism department renovates French War Memorial promenade.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  76%|████████████████████▋      | 764/1000 [17:15<05:06,  1.30s/it]

[764/1000]
EN: Dal Lake restoration project includes de-weeding and island development.
ASM: দেৱাৰ বির্জীৱে বাৰে, লি জিৰিলাৰ ৰাদৰা মি विरोधी āৰু яৰ ) রিন্দatৰ ।
--------------------------------------------------

Translating:  76%|████████████████████▋      | 765/1000 [17:16<04:45,  1.21s/it]

[765/1000]
EN: Hampi gets world-class interpretation centre showcasing Vijayanagara heritage.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  77%|████████████████████▋      | 766/1000 [17:18<04:52,  1.25s/it]

[766/1000]
EN: Mahabalipuram shoreline monument gets LED lighting for night viewing.
ASM: দৰি জেৱাৰ  : র্বিীৰ ৰালে, বাৰে লাৰু āৰা പ്ः а-.
--------------------------------------------------

Translating:  77%|████████████████████▋      | 767/1000 [17:19<05:12,  1.34s/it]

[767/1000]
EN: Ajanta-Ellora caves introduce audio guides in ten international languages.
ASM: দৰে বির্জাৰ জীৱাৰৰ.
--------------------------------------------------

Translating:  77%|████████████████████▋      | 768/1000 [17:20<04:38,  1.20s/it]

[768/1000]
EN: Kaziranga opens additional safari routes for tourists.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  77%|████████████████████▊      | 769/1000 [17:21<04:49,  1.25s/it]

[769/1000]
EN: Radisson Blu opens two hundred key property in Amritsar near Golden Temple.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  77%|████████████████████▊      | 770/1000 [17:23<04:53,  1.27s/it]

[770/1000]
EN: IHCL launches Ginger brand hotel in Siliguri for Dooars travellers.
ASM: দেৱাৰ বির্জে বাৰে, জীৱি লিমিৰ ৰালাৰ तिक. : ?
--------------------------------------------------

Translating:  77%|████████████████████▊      | 771/1000 [17:24<04:47,  1.26s/it]

[771/1000]
EN: Hyatt Regency debuts in Dehradun with mountain view rooms.
ASM: দেৱাৰ বির্জীৰ ৰিলে, লাৰে বাৰি মিৰু জিন্দৰা. : ?
--------------------------------------------------

Translating:  77%|████████████████████▊      | 772/1000 [17:25<04:29,  1.18s/it]

[772/1000]
EN: Taj Fort Aguada completes fifty years in Goa announces renovation.
ASM: দেৱাৰ বির্জীৰ ৰিলা জিৰিলে,.
--------------------------------------------------

Translating:  77%|████████████████████▊      | 773/1000 [17:26<04:48,  1.27s/it]

[773/1000]
EN: Novotel Visakhapatnam opens with three sixty degree sea view rooms.
ASM: দেৱাৰ বির্জীৰ ৰিলে, বাৰে জেৰি লাৰু মিৰা রিন্দৰ ) яৰ तिक āৰ 49?
--------------------------------------------------

Translating:  77%|████████████████████▉      | 774/1000 [17:27<04:15,  1.13s/it]

[774/1000]
EN: Roseate House Delhi appoints Kunal Kumar as new general manager.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  78%|████████████████████▉      | 775/1000 [17:28<03:53,  1.04s/it]

[775/1000]
EN: ITC Hotels launches Mementoes brand with Jaipur property opening.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  78%|████████████████████▉      | 776/1000 [17:29<03:56,  1.06s/it]

[776/1000]
EN: Marriott Kathmandu opens Indian restaurant specializing in Awadhi cuisine.
ASM: দেৱাৰ বির্জীৱে, বাৰে মি জিৰিলে ;.
--------------------------------------------------

Translating:  78%|████████████████████▉      | 777/1000 [17:31<04:22,  1.18s/it]

[777/1000]
EN: Sarovar Hotels signs new property in Darjeeling with heritage status.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  78%|█████████████████████      | 778/1000 [17:31<03:58,  1.08s/it]

[778/1000]
EN: The Park Kolkata celebrates seventy-fifth anniversary with heritage walks.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  78%|█████████████████████      | 779/1000 [17:32<03:36,  1.02it/s]

[779/1000]
EN: Ambassador Ajmera joins Indian Hotel Company board as independent director.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  78%|█████████████████████      | 780/1000 [17:34<04:05,  1.12s/it]

[780/1000]
EN: Chai Sutta Bar founder Anubhav Dubey opens tourist cafe in Udaipur.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  78%|█████████████████████      | 781/1000 [17:35<03:46,  1.03s/it]

[781/1000]
EN: Aman Resorts to launch first Indian property in Alwar district.
ASM: দৰে জাৰি বিরীৰ লি,.
--------------------------------------------------

Translating:  78%|█████████████████████      | 782/1000 [17:36<04:20,  1.19s/it]

[782/1000]
EN: Soneva Fushi Maldives introduces all-inclusive plan for Indian honeymooners.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 783/1000 [17:38<04:41,  1.30s/it]

[783/1000]
EN: CII tourism committee chairman K.B. Kachru calls for single window clearance.
ASM: দৰিরে জাৱাৰ., বিৰে ৰালাৰী লিমি বাৰ্দেৰা āৰু яৰat പ്ৰ तिकৰायला а : ?
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 784/1000 [17:39<04:27,  1.24s/it]

[784/1000]
EN: Ladakh bans motorbike rallies to protect fragile Himalayan ecosystem.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 785/1000 [17:40<04:48,  1.34s/it]

[785/1000]
EN: Meghalaya introduces living root bridge trekking festival in November.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  79%|█████████████████████▏     | 786/1000 [17:41<04:20,  1.22s/it]

[786/1000]
EN: Spiti valley opens for tourists after six-month winter closure.
ASM: দেৱাৰ বির্জে জীৱaৰ ৰিলে,.
--------------------------------------------------

Translating:  79%|█████████████████████▏     | 787/1000 [17:42<04:12,  1.18s/it]

[787/1000]
EN: Andaman administration permits night camping on Neil Island.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 788/1000 [17:43<03:49,  1.08s/it]

[788/1000]
EN: Gujarat forest department opens Gir interpretation zone for lion safaris.
ASM: দেৱাৰ বির্জে জীৱি.
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 789/1000 [17:45<04:23,  1.25s/it]

[789/1000]
EN: Jim Corbett tiger reserve reports 1.75 lakh tourists in peak season.
ASM: . দেৱাৰ বির্জীৰ ৰালা, বাৰে লিমি জিৰি 1..
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 790/1000 [17:46<04:28,  1.28s/it]

[790/1000]
EN: Periyar sanctuary introduces bamboo rafting in Thekkady lake.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 791/1000 [17:47<04:06,  1.18s/it]

[791/1000]
EN: Sundarbans tourism restricted during tiger breeding season.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 792/1000 [17:48<03:38,  1.05s/it]

[792/1000]
EN: Ranthambore bans private vehicles inside core zone from December.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 793/1000 [17:49<03:21,  1.03it/s]

[793/1000]
EN: Kerala tourism launches monsoon packages for Ayurveda treatments.
ASM: বিৰে জাৱাৰ দৰি রীৱে,.
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 794/1000 [17:50<03:34,  1.04s/it]

[794/1000]
EN: Kutch Rann Utsav extends tent city duration by forty-five days.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  80%|█████████████████████▍     | 795/1000 [17:51<04:09,  1.22s/it]

[795/1000]
EN: Telangana government promotes Yadadri temple as integrated pilgrimage hub.
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  80%|█████████████████████▍     | 796/1000 [17:53<04:07,  1.21s/it]

[796/1000]
EN: Mysore Dasara procession draws eight lakh visitors on Vijayadashami day.
ASM: দেৱাৰ বির্জে জীৱে, বাৰি লিমিলাৰ ৰাদৰে ;.
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 797/1000 [17:54<03:51,  1.14s/it]

[797/1000]
EN: Konark Sun Temple to get 3D projection mapping experience.
ASM: . দেৱাৰ বিজৰরী 3 জিলিৰ ৰালা ।
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 798/1000 [17:54<03:30,  1.04s/it]

[798/1000]
EN: Elephanta Caves introduce Portuguese audio guide for visitors.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 799/1000 [17:55<03:18,  1.02it/s]

[799/1000]
EN: Golconda Fort light and sound show revamped in Telugu and English.
ASM: দৰে জাৰি বিরীৱাৰৰ ৰালাৰ.
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 800/1000 [17:57<03:58,  1.19s/it]

[800/1000]
EN: Five regional medical hubs to be set up to boost medical tourism in country
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি মিন্দৰা লাৰু яৰ )
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 801/1000 [17:58<03:57,  1.19s/it]

[801/1000]
EN: Union Budget 2026 announces NIMHANS for north India
ASM: দেৱাৰ বির্জীৱে জিলাৰ ৰালে ।
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 802/1000 [18:00<04:02,  1.23s/it]

[802/1000]
EN: Centre forms expert panel on healthcare for transgender persons
ASM: দেৱাৰ বির্জীৱে লিৰি জিমিলাৰ ৰাদৰা বাৰে, яৰু.
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 803/1000 [18:01<04:29,  1.37s/it]

[803/1000]
EN: Stem cell therapy cannot be offered as a clinical service for autism
ASM: দৰে জিৱাৰ বিরীৰ ৰালে, মিৰি বাৰা লাৰু яৰ तिकৰ্দেৰ )
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 804/1000 [18:02<03:57,  1.21s/it]

[804/1000]
EN: AI helps doctors spot breast cancer in scans
ASM: দেৱাৰ বির্জে জীৱুৱে,.
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 805/1000 [18:04<04:40,  1.44s/it]

[805/1000]
EN: Every family today knows someone with cancer and It is no longer a disease that happens to an ageing parent or relative
ASM: দেৱাৰ বির্জীৱে বাৰে, লিৰি জিমিলাৰ ৰা समारंभ āৰু রিন্দৰা яৰ तिकिल्  तॊटर्च्चि  एतेऩुम् പवेৰराज সatৰ ꯃꯦ  गोंधळরে विरोधी  कावलিদি কৰ शेवट ।
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 806/1000 [18:05<04:27,  1.38s/it]

[806/1000]
EN: Government imposes import curbs on three pharma ingredients for one year
ASM: দৰে জাৰি বির্রীৰ লালে, মি ৰাদেৱাৰৰ বাৰু রিন্দ स्बराज ।
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 807/1000 [18:06<03:59,  1.24s/it]

[807/1000]
EN: Menstrual health in schools is integral to right to life, says the Supreme Court
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 808/1000 [18:07<03:33,  1.11s/it]

[808/1000]
EN: WHO sees low risk of Nipah virus spreading beyond India
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 809/1000 [18:08<03:14,  1.02s/it]

[809/1000]
EN: Economic Survey calls for tackling rising digital addiction and screen-related mental health problems
ASM: দৰে জিৱাৰ বির্রীৰ ৰালা,.
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 810/1000 [18:09<03:28,  1.10s/it]

[810/1000]
EN: 188 million children and adolescents living with obesity worldwide
ASM: . দেৱাৰ বির্জীৰ ৰালা, বাৰে জিৰি লিমি কৰা ।
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 811/1000 [18:10<03:41,  1.17s/it]

[811/1000]
EN: 60% of mental disorders found in patients below 35 years
ASM: . দৰে জাৰি বিরীৱাৰৰ লিমিলাৰ പ്,
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 812/1000 [18:12<04:06,  1.31s/it]

[812/1000]
EN: Obesity impacts on brain may depend on how fat is distributed across body
ASM: দৰে জাৰি বিরীৱাৰৰ লিমি, বাৰ্লাৰ яৰ ৰাদেৰা āৰু রেৱি विरोधी ন্দatৰ तिकिल्  गोंधळরি কৰवे ।
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 813/1000 [18:13<04:11,  1.35s/it]

[813/1000]
EN: Maharashtra, Karnataka, Tamil Nadu have highest number of vacancies under the NEET-PG 2025-26
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মিৰি লাৰু জিন্দৰা പ് 2025-26
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 814/1000 [18:15<04:23,  1.42s/it]

[814/1000]
EN: Only two Nipah virus disease cases reported in West Bengal since December 2025, says Health Ministry
ASM: . দৰে বির্জাৰীৰ জেৱাৰৰ বাৰি লিলাৰ ৰাদে, মিৰু āৰা রিন্দ स्बराज ।
--------------------------------------------------

Translating:  82%|██████████████████████     | 815/1000 [18:16<04:19,  1.40s/it]

[815/1000]
EN: Health impacts due to plastics worldwide may double by 2040
ASM: . দৰে বির্জাৰ জীৱাৰৰ লাৰিলে 2040,
--------------------------------------------------

Translating:  82%|██████████████████████     | 816/1000 [18:18<04:04,  1.33s/it]

[816/1000]
EN: China halts sale of Sun Pharma drug used to treat dementia
ASM: দেৱাৰ বির্জীৱে লিলাৰ ৰাদৰি জিৰে, বাৰা...
--------------------------------------------------

Translating:  82%|██████████████████████     | 817/1000 [18:19<04:22,  1.43s/it]

[817/1000]
EN: T.N. govt. scheme improves access to diabetes, hypertension care for women as rural residents
ASM: . বিৰে দৰা জরীৱাৰ লিমিলাৰ ৰাদে, বাৰি র্দি्लॆ പ്ৰু яৰ तिकिल् ्रॆ 49 ायो āৰ ) ।
--------------------------------------------------

Translating:  82%|██████████████████████     | 818/1000 [18:22<05:05,  1.68s/it]

[818/1000]
EN: Karnataka farmers urge Union Government to recommend to WHO to re-classify arecanut from ‘carcinogenic’ to ‘possibly carcinogenic to humans’
ASM: . দেৱাৰ বির্জীৱে জিলে, মিৰি বাৰে ৰাদৰা লা तिकৰু яৰ स्बराज ्रॆ पुत्र матি्लॆ āৰायला പ്রি विरोधी ন্দatিक्कूटেৰ दु  गळ ओइबा ायो bj ;
--------------------------------------------------

Translating:  82%|██████████████████████     | 819/1000 [18:23<05:04,  1.68s/it]

[819/1000]
EN: Study discovers stress-reducing role of natural molecule in body, may help with metabolic disorders
ASM: দেৱাৰ বির্জীৱে বাৰি জিৰে,.
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 820/1000 [18:24<04:18,  1.43s/it]

[820/1000]
EN: Keeping your spine healthy with small, everyday changes
ASM: . দেৱাৰ বির্জীৱে জিৰিলে ।
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 821/1000 [18:25<03:48,  1.28s/it]

[821/1000]
EN: What is behind the increasing number of heart attacks in pregnancy?
ASM: দেৱাৰ বির্জে জীৱat বাৰে,.
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 822/1000 [18:26<03:43,  1.26s/it]

[822/1000]
EN: Can India eliminate malaria by 2030?
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে বাৰি জিৰা লাৰু লিম ।
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 823/1000 [18:28<04:03,  1.37s/it]

[823/1000]
EN: Tamil Nadu government seeks IIT-M’s assistance to study ill effects of microplastics on human health
ASM: দেৱাৰ বির্জীৱে.
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 824/1000 [18:29<04:16,  1.46s/it]

[824/1000]
EN: Goa seeks to grow as a wellness and medical tourism hub in India
ASM: দৰি জেৱাৰ বির্রীৰ ৰালা, বাৰে মিৰা লি করে ;
--------------------------------------------------

Translating:  82%|██████████████████████▎    | 825/1000 [18:32<04:43,  1.62s/it]

[825/1000]
EN: Borewell found contaminated, pipelines being probed as eight remain in hospital in Madhya Pradesh's Mhow
ASM: দৰিরে জাৱাৰ বিৰে ৰালে,.
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 826/1000 [18:33<04:46,  1.64s/it]

[826/1000]
EN: Uttar Pradesh youth amputates foot to seek disability quota in admission to medical college
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লাৰু মিন্দৰা āৰ तिकिल् яৰ 11
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 827/1000 [18:34<04:18,  1.49s/it]

[827/1000]
EN: Police investigate software engineer’s death in Chennai lodge linked to bug repellent fumes
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 828/1000 [18:36<04:10,  1.46s/it]

[828/1000]
EN: Regularly engaging in varied physical activities could extend lifespan
ASM: দেৱাৰ বির্জীৱে লিমি জিৰে, বাৰি ৰাদৰা লাৰু яৰ )
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 829/1000 [18:37<03:55,  1.38s/it]

[829/1000]
EN: Study relates ADHD traits in childhood with physical health problems in mid-life
ASM: দেৱাৰ বির্জে জীৱিলাৰ ৰালে,.
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 830/1000 [18:38<03:50,  1.35s/it]

[830/1000]
EN: U.S. completes withdrawal from World Health Organization
ASM: . দৰে জাৰি বিরীৰ লিমিলাৰ ৰাৱা ।
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 831/1000 [18:39<03:43,  1.32s/it]

[831/1000]
EN: Punjab health scheme offers free hospital care worth ₹10 lakh to every family
ASM: দেৱাৰ বির্জীৰ ৰালি 10 বাৰে মি জিৰিলাৰ 11 а,
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 832/1000 [18:40<03:19,  1.19s/it]

[832/1000]
EN: Snapchat launches new Family Center safety tools for teens and parents
ASM: দেৱাৰ বির্জীৱে বাৰি জিলে,.
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 833/1000 [18:42<03:25,  1.23s/it]

[833/1000]
EN: 167 drug samples flagged as ‘not of standard quality’ in December 2025
ASM: . দৰে বির্জাৰীৰ লাৰিলৰ ৰাৱা জেৱিৰু মি പ്,
--------------------------------------------------

Translating:  83%|██████████████████████▌    | 834/1000 [18:43<03:18,  1.19s/it]

[834/1000]
EN: Tamil Nadu issues guidelines as chikungunya cases rise in State
ASM: দেৱাৰ বিজৰী র্দৰে লিমি জিৰি,.
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 835/1000 [18:44<03:29,  1.27s/it]

[835/1000]
EN: Researchers develop tool to simplify nutritional tracking of Indian meals
ASM: দৰে জিৱাৰ বির্রীৰ ৰালাৰি.
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 836/1000 [18:45<03:25,  1.25s/it]

[836/1000]
EN: Shingles vaccine may also slow down biological ageing in older adults
ASM: দৰি জেৱাৰ বিরীৰে লিমিলাৰ ৰাদে, বাৰা র্দিৰু..
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 837/1000 [18:46<03:07,  1.15s/it]

[837/1000]
EN: Gates and OpenAI team up for AI health push in African countries
ASM: দেৱাৰ বির্জীৱে জিলাৰ ৰালে ।
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 838/1000 [18:47<03:06,  1.15s/it]

[838/1000]
EN: ASHA workers protest in Kolkata for ₹15,000 monthly honorarium
ASM: . দেৱাৰ বির্জীৰ ৰিলে, ाय़ বাৰে জিৰিলাৰু а 99,000
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 839/1000 [18:49<03:32,  1.32s/it]

[839/1000]
EN: Bloodless heart surgery performed on patient with rare blood group at Kauvery Hospital
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 840/1000 [18:50<03:29,  1.31s/it]

[840/1000]
EN: Centre sanctions 50-bed AYUSH hospital for Tenali, says A.P. Minister
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে 5 - লাৰি জেৰা মি 50 : ?
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 841/1000 [18:52<03:25,  1.29s/it]

[841/1000]
EN: NIMS Hyderabad opens Stem Cell Centre of Excellence as India battles rising burden of lifestyle diseases
ASM: দেৱাৰ বির্জীৱে বাৰে, জিলি লাৰি ৰাদৰা. : ?
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 842/1000 [18:53<03:44,  1.42s/it]

[842/1000]
EN: The Ministry of Health and Family Welfare launched a nationwide campaign to improve early detection of non-communicable diseases in rural India.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে লাৰি জিমিৰু āৰা яৰ ) রিন্দৰ तिक പ് नृি्लॆ атিসatৰ ;  : ?.
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 843/1000 [18:56<04:14,  1.62s/it]

[843/1000]
EN: The Government of India announced an increase in funding for public hospitals under the National Health Mission.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 844/1000 [18:57<03:43,  1.43s/it]

[844/1000]
EN: Indian researchers developed a low-cost diagnostic kit to detect tuberculosis with higher accuracy.
ASM: দৰি জেৱাৰ বিরীৰে লিৰ্লা ৰামি,.
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 845/1000 [18:58<03:43,  1.44s/it]

[845/1000]
EN: The Indian Council of Medical Research issued updated guidelines for the treatment of dengue fever.
ASM: দেৱাৰ বির্জীৰ ৰালে, জিৰি লাৰে মি ) বাৰু āৰা яৰ विरोधी маৰ तिक ।
--------------------------------------------------

Translating:  85%|██████████████████████▊    | 846/1000 [19:00<03:53,  1.52s/it]

[846/1000]
EN: A new government medical college was inaugurated in Assam to strengthen healthcare education in the northeastern region.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  85%|██████████████████████▊    | 847/1000 [19:01<03:45,  1.48s/it]

[847/1000]
EN: The Union Health Minister reviewed the progress of Ayushman Bharat services across multiple states.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 848/1000 [19:02<03:34,  1.41s/it]

[848/1000]
EN: India reported a decline in maternal mortality rates due to improved institutional delivery services.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 849/1000 [19:03<03:12,  1.27s/it]

[849/1000]
EN: The Drug Controller General of India approved a new vaccine for preventing cervical cancer.
ASM: দেৱাৰ বির্জে জীৱলৰ ৰাদৰে,.
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 850/1000 [19:05<03:17,  1.32s/it]

[850/1000]
EN: Several state governments expanded free dialysis services in district hospitals.
ASM: দেৱাৰ বির্জীৱে জিলে, মিৰি লাৰে ৰাদৰা বাৰু яৰ तिकिल् āৰat ।
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 851/1000 [19:07<03:38,  1.47s/it]

[851/1000]
EN: The World Health Organization praised India’s efforts in polio eradication during a regional health summit.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  85%|███████████████████████    | 852/1000 [19:07<03:07,  1.27s/it]

[852/1000]
EN: A public health survey revealed improved vaccination coverage among children in urban slum areas.
ASM: দেৱাৰ বির্জে জীৱে,.
--------------------------------------------------

Translating:  85%|███████████████████████    | 853/1000 [19:09<03:24,  1.39s/it]

[853/1000]
EN: The Ministry of AYUSH promoted traditional medicine research through newly funded clinical studies.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  85%|███████████████████████    | 854/1000 [19:10<02:57,  1.22s/it]

[854/1000]
EN: Indian hospitals adopted artificial intelligence tools to assist doctors in early cancer detection.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  86%|███████████████████████    | 855/1000 [19:11<03:01,  1.25s/it]

[855/1000]
EN: The National Medical Commission introduced revised norms for undergraduate medical education.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  86%|███████████████████████    | 856/1000 [19:12<02:57,  1.23s/it]

[856/1000]
EN: A shortage of specialist doctors was reported in government hospitals across rural districts.
ASM: দেৱাৰ বির্জে জীৱলৰ ৰালাৰ, বাৰি মিৰু. : ?
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 857/1000 [19:14<02:59,  1.25s/it]

[857/1000]
EN: The central government launched a digital health ID system to streamline patient medical records.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 858/1000 [19:15<03:03,  1.29s/it]

[858/1000]
EN: India’s pharmaceutical exports increased due to rising global demand for generic medicines.
ASM: বিৰে দৰা জরীৱাৰ.
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 859/1000 [19:16<03:06,  1.32s/it]

[859/1000]
EN: The Supreme Court of India directed states to improve healthcare infrastructure in tribal areas.
ASM: দেৱাৰ বির্জীৰ ৰিলে, লাৰে বাৰি জিৰা মিন্দৰু. :-% ।
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 860/1000 [19:17<02:52,  1.23s/it]

[860/1000]
EN: A government report highlighted gaps in mental health services in public healthcare facilities.
ASM: দেৱাৰ বির্জীৰ ৰালে জিৰি বাৰে,.
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 861/1000 [19:19<03:24,  1.47s/it]

[861/1000]
EN: Several private hospitals partnered with state governments to offer affordable cardiac care.
ASM: দেৱাৰ বির্জে জীৱিলাৰ ৰালে, মিৰি বাৰা রিন্দৰু āৰে ; яৰ्लॆ घटनॆ  एतेऩुम् क्कूटেৰ तिकिल् ्रॆक्कुपॊ पाति маꯔꯤ ।
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 862/1000 [19:21<03:07,  1.36s/it]

[862/1000]
EN: The Indian Institute of Public Health conducted a study on air pollution-related respiratory diseases.
ASM: দেৱাৰ বির্জীৰ ৰিলে, লাৰে বাৰি জিৰা. : ?
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 863/1000 [19:21<02:44,  1.20s/it]

[863/1000]
EN: Health officials initiated a special drive to control the spread of seasonal influenza.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 864/1000 [19:23<02:51,  1.26s/it]

[864/1000]
EN: The Ministry of Health strengthened surveillance systems to monitor emerging infectious diseases.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 865/1000 [19:24<03:02,  1.35s/it]

[865/1000]
EN: India recorded a steady rise in organ donation registrations through national awareness campaigns.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 866/1000 [19:26<03:14,  1.45s/it]

[866/1000]
EN: A new telemedicine platform was introduced to improve access to healthcare in remote villages.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 867/1000 [19:28<03:13,  1.46s/it]

[867/1000]
EN: The National AIDS Control Organisation reported a decline in new HIV infections.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 868/1000 [19:29<02:54,  1.32s/it]

[868/1000]
EN: Government hospitals increased the availability of free essential medicines for outpatients.
ASM: দেৱাৰ বির্জে জীৱলৰ ৰামি লাৰে,.
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 869/1000 [19:30<02:57,  1.36s/it]

[869/1000]
EN: A policy review emphasized the need for more nursing staff in public healthcare institutions.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 870/1000 [19:31<02:56,  1.36s/it]

[870/1000]
EN: The Indian government signed a health cooperation agreement with a neighboring country.
ASM: দেৱাৰ বির্জীৰ ৰালে, জিৰি লাৰে বাৰু মিন্দৰা রি विरोधी. : ?
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 871/1000 [19:33<02:51,  1.33s/it]

[871/1000]
EN: Researchers from an Indian medical institute published findings on antibiotic resistance trends.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে লাৰি জিমিৰা. : ?
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 872/1000 [19:34<02:46,  1.30s/it]

[872/1000]
EN: The Health Ministry issued advisories to states following a rise in heat-related illnesses.
ASM: দেৱাৰ বির্জীৰ ৰালে, জিৰে বাৰি মিলাৰু. : ?
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 873/1000 [19:35<02:47,  1.32s/it]

[873/1000]
EN: India expanded its emergency ambulance network to improve response times in rural regions.
ASM: বিৰে দৰা জিরীৱাৰ. : ?
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 874/1000 [19:36<02:33,  1.22s/it]

[874/1000]
EN: The National Digital Health Mission aimed to improve transparency in healthcare service delivery.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 875/1000 [19:37<02:22,  1.14s/it]

[875/1000]
EN: A public-private partnership model was introduced to upgrade district-level hospitals.
ASM: দৰে জাৰি বিরীৱাৰৰ ৰালাৰ মিলে,.
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 876/1000 [19:39<02:32,  1.23s/it]

[876/1000]
EN: The government launched a mental health helpline to support individuals during medical emergencies.
ASM: দেৱাৰ বির্জীৱে লিমি জিৰে,.
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 877/1000 [19:40<02:46,  1.36s/it]

[877/1000]
EN: India’s medical tourism sector showed growth due to affordable treatment options.
ASM: দেৱাৰ বির্জি.
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 878/1000 [19:41<02:36,  1.29s/it]

[878/1000]
EN: A parliamentary committee reviewed the implementation of healthcare schemes in backward districts.
ASM: দেৱাৰ বির্জীৱে বাৰি জিলে,.
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 879/1000 [19:43<02:41,  1.33s/it]

[879/1000]
EN: The Ministry of Health emphasized preventive healthcare during a national policy meeting.
ASM: দেৱাৰ বির্জে জীৱলৰ ৰামি. : ?
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 880/1000 [19:44<02:41,  1.35s/it]

[880/1000]
EN: Indian scientists developed a wearable device to monitor heart health in elderly patients.
ASM: দেৱাৰ বির্জে.
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 881/1000 [19:46<02:45,  1.39s/it]

[881/1000]
EN: A national survey assessed nutritional deficiencies among children under five years of age.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 882/1000 [19:47<02:35,  1.32s/it]

[882/1000]
EN: The government increased insurance coverage limits under Ayushman Bharat for critical illnesses.
ASM: দেৱাৰ বির্জীৰ ৰালা,.
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 883/1000 [19:48<02:35,  1.32s/it]

[883/1000]
EN: Health authorities conducted vaccination drives to prevent outbreaks of measles and rubella.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 884/1000 [19:49<02:19,  1.20s/it]

[884/1000]
EN: India strengthened laboratory capacity to improve disease surveillance and diagnosis.
ASM: দেৱাৰ বির্জীৱে লিমি জিৰে,.
--------------------------------------------------

Translating:  88%|███████████████████████▉   | 885/1000 [19:50<02:04,  1.08s/it]

[885/1000]
EN: A state health department launched mobile clinics to serve remote tribal communities.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 886/1000 [19:51<02:02,  1.07s/it]

[886/1000]
EN: The National Health Authority upgraded its data systems to enhance patient safety.
ASM: দেৱাৰ বির্জীৰ ৰালাৰে জিলে,.
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 887/1000 [19:52<02:14,  1.19s/it]

[887/1000]
EN: Indian doctors highlighted the need for early screening of lifestyle-related diseases.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 888/1000 [19:53<01:56,  1.04s/it]

[888/1000]
EN: The Ministry of Health released new guidelines for hospital waste management.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  89%|████████████████████████   | 889/1000 [19:54<01:53,  1.02s/it]

[889/1000]
EN: Several states reported improvements in primary healthcare access through wellness centers.
ASM: দৰি জেৱাৰ বিরীৰে লিমিলাৰ ৰাদে,.
--------------------------------------------------

Translating:  89%|████████████████████████   | 890/1000 [19:55<02:05,  1.14s/it]

[890/1000]
EN: India’s public health expenditure showed a gradual increase in the latest budget.
ASM: দৰে জাৰি বিরীৰ.
--------------------------------------------------

Translating:  89%|████████████████████████   | 891/1000 [19:57<02:13,  1.22s/it]

[891/1000]
EN: A new online portal was launched to track the availability of hospital beds.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি āৰা লাৰু মিন্দৰat রি विरोधी яৰ ) ।
--------------------------------------------------

Translating:  89%|████████████████████████   | 892/1000 [19:58<02:19,  1.29s/it]

[892/1000]
EN: Health experts in India raised concerns about rising cases of diabetes among young adults.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  89%|████████████████████████   | 893/1000 [20:00<02:32,  1.43s/it]

[893/1000]
EN: The government initiated training programs to improve emergency care skills among paramedics.
ASM: দেৱাৰ বির্জীৱে বাৰে, লিলাৰ ৰামি জিৰিন্দৰা āৰু яৰ ) রি तिकुपি विरोधी പ्लॆक्कूटা ।
--------------------------------------------------

Translating:  89%|████████████████████████▏  | 894/1000 [20:01<02:21,  1.33s/it]

[894/1000]
EN: Indian pharmaceutical companies invested in research for affordable cancer medicines.
ASM: দৰে জাৰি বিরীৰ লিলাৰ ৰামিৰ্দেৱাৰৰ বারে,. : ?
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 895/1000 [20:02<02:04,  1.19s/it]

[895/1000]
EN: A national task force was formed to address antimicrobial resistance.
ASM: দেৱাৰ বির্জীৰ ৰিলা জিলে,.
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 896/1000 [20:03<02:11,  1.26s/it]

[896/1000]
EN: The Health Ministry conducted audits to improve quality standards in government hospitals.
ASM: দেৱাৰ বির্জে জীৱaৰ ৰালে,.
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 897/1000 [20:04<02:02,  1.19s/it]

[897/1000]
EN: India expanded maternal nutrition programs to reduce anemia among pregnant women.
ASM: দেৱাৰ বির্জীৰ ৰালি জিৰে,.
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 898/1000 [20:06<02:01,  1.19s/it]

[898/1000]
EN: A state government announced free health checkups for senior citizens.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 899/1000 [20:06<01:47,  1.07s/it]

[899/1000]
EN: Indian healthcare startups focused on digital solutions for chronic disease management.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 900/1000 [20:08<02:01,  1.22s/it]

[900/1000]
EN: The National Health Policy emphasized universal access to affordable healthcare services.
ASM: দেৱাৰ বির্জীৰ ৰালা,.
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 901/1000 [20:09<01:50,  1.12s/it]

[901/1000]
EN: Public health officials promoted lifestyle changes to reduce cardiovascular disease risks.
ASM: দেৱাৰ বির্জীৱে লিৰি জিমি,.
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 902/1000 [20:10<02:03,  1.26s/it]

[902/1000]
EN: India improved cold chain infrastructure to ensure vaccine safety and effectiveness.
ASM: দেৱাৰ বির্জে.
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 903/1000 [20:12<02:00,  1.25s/it]

[903/1000]
EN: A medical research institute in India studied long-term effects of COVID-19 infections.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰিলাৰ ए : ?
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 904/1000 [20:13<01:46,  1.11s/it]

[904/1000]
EN: The government strengthened referral systems between primary and tertiary healthcare centers.
ASM: দেৱাৰ বির্জীৰ ৰালা,.
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 905/1000 [20:14<01:51,  1.17s/it]

[905/1000]
EN: Health workers received additional training to improve immunization coverage.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  91%|████████████████████████▍  | 906/1000 [20:15<01:44,  1.11s/it]

[906/1000]
EN: India expanded newborn care units to reduce infant mortality rates.
ASM: দেৱাৰ বির্জীৱে লিৰে,.
--------------------------------------------------

Translating:  91%|████████████████████████▍  | 907/1000 [20:17<02:01,  1.31s/it]

[907/1000]
EN: The Ministry of Health collaborated with states to improve sanitation and hygiene practices.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে লাৰি জিমি ) রিন্দৰা क्कूटিৰু പ് तिकिल् āৰचर ्रॆक्कাদি्लॆ ятি समारंभ маꯔꯤ ।
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 908/1000 [20:17<01:45,  1.15s/it]

[908/1000]
EN: Indian hospitals increased investment in critical care facilities.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 909/1000 [20:19<01:49,  1.20s/it]

[909/1000]
EN: A health awareness campaign encouraged working professionals to undergo regular health screenings.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 910/1000 [20:20<01:49,  1.22s/it]

[910/1000]
EN: The government introduced reforms to regulate private healthcare pricing.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 911/1000 [20:21<01:52,  1.26s/it]

[911/1000]
EN: India enhanced its disease reporting systems to improve outbreak preparedness.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 912/1000 [20:23<01:51,  1.26s/it]

[912/1000]
EN: Health experts recommended increased funding for mental health research in India.
ASM: দেৱাৰ বির্জীৱে বাৰি জিলে,.
--------------------------------------------------

Translating:  91%|████████████████████████▋  | 913/1000 [20:24<01:53,  1.30s/it]

[913/1000]
EN: The National Health Authority reviewed feedback to improve beneficiary services.
ASM: দেৱাৰ বির্জীৰ ৰিলে, জিৰে বাৰি লাৰু মিন্দৰা яৰ तिक রি विरोधी പ്রে ;.
--------------------------------------------------

Translating:  91%|████████████████████████▋  | 914/1000 [20:25<01:38,  1.15s/it]

[914/1000]
EN: India strengthened disaster preparedness in hospitals for medical emergencies.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  92%|████████████████████████▋  | 915/1000 [20:26<01:29,  1.06s/it]

[915/1000]
EN: A state government launched a nutrition program for school children.
ASM: দৰে জাৰি বিরীৰ লি ৰালাৰ,.
--------------------------------------------------

Translating:  92%|████████████████████████▋  | 916/1000 [20:27<01:34,  1.13s/it]

[916/1000]
EN: The Health Ministry emphasized community participation in strengthening public healthcare systems.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 917/1000 [20:29<01:56,  1.41s/it]

[917/1000]
EN: The Union Budget 2026 increased the healthcare allocation to 1,06,530 crore rupees for the Ministry of Health and Family Welfare.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি লাৰু āৰা মিন্দৰ तिक а 1, 5, 30 яৰ स्बराज പ്ৰ रा  वसूल वरकु ।
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 918/1000 [20:30<01:55,  1.41s/it]

[918/1000]
EN: Finance Minister Nirmala Sitharaman announced a 10 percent hike in the health budget compared to the previous fiscal year.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 10 লাৰু āৰা яৰ तिक а : ?
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 919/1000 [20:32<02:00,  1.49s/it]

[919/1000]
EN: The Government of India launched the Biopharma SHAKTI initiative with an outlay of 10,000 crore rupees over five years.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি 5, 000,-ᱹ লাৰ तिकৰা പ് : ?
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 920/1000 [20:34<02:10,  1.63s/it]

[920/1000]
EN: The Biopharma SHAKTI scheme aims to strengthen the domestic production of biologics and biosimilars in India.
ASM: বিৰে দৰা জরীৱাৰ লিমি,. : ?
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 921/1000 [20:36<02:09,  1.64s/it]

[921/1000]
EN: The Ministry of Health will support states in establishing five new regional medical hubs through private-sector partnerships.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 922/1000 [20:36<01:49,  1.41s/it]

[922/1000]
EN: These five regional medical hubs will combine medical services, educational facilities, and research centers under one roof.
ASM: দৰে জাৰি বিরীৱাৰৰ ৰালাৰ  :-.
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 923/1000 [20:38<01:47,  1.39s/it]

[923/1000]
EN: The Union Budget 2026 proposed the establishment of NIMHANS 2.0 in North India to address mental health needs.
ASM: . দেৱাৰ বিজৰ ৰার্দৰে জীৱেৰিলে, বাৰা লাৰু মি 2 : ?
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 924/1000 [20:39<01:51,  1.46s/it]

[924/1000]
EN: The Government plans to upgrade the National Mental Health Institutes in Ranchi and Tezpur into regional apex institutions.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 925/1000 [20:41<02:00,  1.61s/it]

[925/1000]
EN: The Ministry of Health allocated 3,477 crore rupees to the National AIDS and STD Control Programme.
ASM: , দৰে জাৰি বিরীৱাৰৰ লিমি ৰালাৰ বাৰ্দেৰা āৰু রিন্দ ) а 3, 497 яৰ तिकৰक्क പवेৰराज  वसूल वरकु ।
--------------------------------------------------

Translating:  93%|█████████████████████████  | 926/1000 [20:43<01:54,  1.55s/it]

[926/1000]
EN: The Union Budget 2026 provided a full customs duty exemption on 17 essential cancer-related drugs.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে а জিৰিমি āৰা লাৰু പ് : ?
--------------------------------------------------

Translating:  93%|█████████████████████████  | 927/1000 [20:44<01:50,  1.51s/it]

[927/1000]
EN: Seven additional rare diseases were added to the list for easier personal import of life-saving medicines.
ASM: দৰিরে জাৱাৰ বিৰে, লিীৱে ৰালাৰ্দেৰা বাৰু মি āৰ तिक রিন্দ स्बराज ;.
--------------------------------------------------

Translating:  93%|█████████████████████████  | 928/1000 [20:46<01:53,  1.57s/it]

[928/1000]
EN: The Government announced a 50 percent expansion in emergency and trauma care capacity at district hospitals.
ASM: . দেৱাৰ বির্জীৰ ৰাদৰে বাৰি লি 50 জিৰা লাৰু মি, яৰ ) āৰat പ് तिकिल् а : ?
--------------------------------------------------

Translating:  93%|█████████████████████████  | 929/1000 [20:48<01:54,  1.61s/it]

[929/1000]
EN: The Ministry of Health intends to establish dedicated emergency and trauma care centers in every district hospital.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  93%|█████████████████████████  | 930/1000 [20:49<01:55,  1.66s/it]

[930/1000]
EN: The Pradhan Mantri Jan Arogya Yojana received an increased allocation of 9,500 crore rupees to expand coverage.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, লাৰে বাৰি মিৰু জিন্দৰা āৰचर  एतेऩुम् 5, 500 яৰ तिकৰराज а : ?
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 931/1000 [20:51<01:56,  1.69s/it]

[931/1000]
EN: The National Health Mission was allocated 39,390 crore rupees to enhance primary healthcare delivery across states.
ASM: . দৰিরে জাৱাৰ বিলে, বাৰে ৰাদেৰ্লাৰীৰ तिक মিৰু പ्लॆ 49, 990 а : ?
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 932/1000 [20:53<01:56,  1.72s/it]

[932/1000]
EN: The Government proposed a plan to add 100,000 allied health professionals over the next five years.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি 1, 00, 000 লাৰি জেৰা āৰু яৰ ) রিন্দৰ तिकिल् а : ायो-, ;
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 933/1000 [20:55<01:57,  1.75s/it]

[933/1000]
EN: The Ministry of Health will upgrade existing institutions for allied health professionals to improve training standards.
ASM: দেৱাৰ বির্জীৰ ৰালা,.
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 934/1000 [20:56<01:53,  1.72s/it]

[934/1000]
EN: The Union Budget 2026 earmarked 4,821 crore rupees specifically for the Department of Health Research.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে а 492- ; লাৰি জিমিৰু яৰ ) പवेৰা āৰायला घटनॆ о : ?
--------------------------------------------------

Translating:  94%|█████████████████████████▏ | 935/1000 [20:58<01:44,  1.61s/it]

[935/1000]
EN: Finance Minister Nirmala Sitharaman proposed the creation of three new All India Institutes of Ayurveda.
ASM: দেৱাৰ বির্জীৱে জিৰে ৰালা,.
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 936/1000 [20:59<01:40,  1.57s/it]

[936/1000]
EN: The Government plans to train 1.5 lakh caregivers in allied skills such as geriatric care and yoga.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰিলাৰ ) क्कूटিন্দৰা āৰু а : ?-..
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 937/1000 [21:01<01:42,  1.62s/it]

[937/1000]
EN: The Ayushman Bharat Digital Mission received 350 crore rupees to improve digital health record interoperability.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰি्लॆ লাৰু ोपিন্দৰা āৰचर പ്ৰ तिकिल् яৰ स्बराज ; а- 350 : ?
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 938/1000 [21:03<01:47,  1.73s/it]

[938/1000]
EN: The Ministry of Health aims to reduce import dependence by supporting the domestic manufacturing of high-value biopharmaceuticals.
ASM: দৰিরে জাৱাৰ বিৰে,. : ायो- ; ৰালাৰী মিলি র্দেৱেৰা বাৰু āৰ तिकिल् яৰ ) а..
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 939/1000 [21:05<01:57,  1.92s/it]

[939/1000]
EN: The Union Budget 2026 focus shifted from a curative model to a prevention-first and holistic wellness approach.
ASM: . দেৱাৰ বির্জীৰ ৰালে, বাৰে মি জিৰা লাৰি কৰু রিন্দৰ तिकिल् āৰat പ്ৰ रा चॆप्टम्पर् яৰ ) ।
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 940/1000 [21:07<01:50,  1.84s/it]

[940/1000]
EN: The Government will establish 1,000 accredited clinical trial sites to position India as a global research destination.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে 1, 000 জিৰি লাৰু মিন্দৰা āৰचर а : я-, ;
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 941/1000 [21:08<01:41,  1.72s/it]

[941/1000]
EN: The Central Drugs Standard Control Organisation will receive more specialized personnel to improve regulatory efficiency.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 942/1000 [21:10<01:34,  1.64s/it]

[942/1000]
EN: Artificial Intelligence is now being used by Indian radiologists to detect early signs of lung cancer from medical images.
ASM: দৰিরে জাৱাৰ বিলে,.
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 943/1000 [21:12<01:34,  1.66s/it]

[943/1000]
EN: Qure.ai implemented AI-driven imaging solutions to facilitate faster diagnosis of strokes in rural Indian hospitals.
ASM: দৰিরে জাৱাৰ বিলে,. : ?
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 944/1000 [21:13<01:35,  1.70s/it]

[944/1000]
EN: Indian healthcare providers are adopting "Actionable AI" to provide predictive health roadmaps instead of simple lab reports.
ASM: দেৱাৰ বির্জে জীৱলৰ ৰামি. :  ) বাৰে, লাৰি्लॆ പ്ः я-..
--------------------------------------------------

Translating:  94%|█████████████████████████▌ | 945/1000 [21:15<01:24,  1.53s/it]

[945/1000]
EN: The use of wearables in India is evolving from basic fitness tracking to clinical-grade monitoring of heart rhythm.
ASM: দেৱাৰ বির্জে জীৱে, বাৰে ৰালাৰি মিলে ;.
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 946/1000 [21:16<01:23,  1.55s/it]

[946/1000]
EN: Medical technology startups in India are developing microfluidic devices that conduct complex tests on a single drop of blood.
ASM: দেৱাৰ বির্জীৱে বাৰে, লিৰি জিমিলাৰ ৰাদৰা āৰু রিন্দি्लॆ  तिकुपি विरोधी яৰ কৰa ।
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 947/1000 [21:18<01:19,  1.49s/it]

[947/1000]
EN: The Indian MedTech sector is projected to reach a market value of 50 billion dollars by the end of 2026.
ASM: . দেৱাৰ বির্জীৰ ৰিলে, বাৰে মি জিৰি 5 496 а : ?
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 948/1000 [21:19<01:25,  1.64s/it]

[948/1000]
EN: Hospitals in Tier 2 cities are using predictive analytics to optimize patient flow and reduce waiting times.
ASM: দেৱাৰ বির্জীৱে বাৰে 2 জিলে, মি লাৰি ৰাদৰা āৰু яৰ ) রিন্দatৰ तिक  गोंधळরে 5 маꯔꯤ ।
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 949/1000 [21:21<01:20,  1.57s/it]

[949/1000]
EN: Telemedicine services are expanding in remote regions to connect rural patients with specialists in metropolitan cities.
ASM: দৰিরে জাৱাৰ বিৰে,.
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 950/1000 [21:22<01:16,  1.54s/it]

[950/1000]
EN: The Ayushman Bharat Health Account (ABHA) system allows patients to share digital health records securely with doctors.
ASM: দেৱাৰ বির্জীৱে জিলে,. : ?
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 951/1000 [21:24<01:21,  1.66s/it]

[951/1000]
EN: Robotic-assisted surgery is becoming more common in private Indian hospitals for complex urological procedures.
ASM: দেৱাৰ বির্জীৱে বাৰে, লিৰি জিলাৰ ৰাদৰা মি কৰa āৰু  कावलি्लॆ яৰ ) রি विरोधी ন্দatৰ तिक атিावन мিদ स्बराज ।
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 952/1000 [21:26<01:17,  1.62s/it]

[952/1000]
EN: Many Indian diagnostic labs are now using genomic testing as a primary triage tool for chronic diseases.
ASM: দেৱাৰ বির্জীৱে,.
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 953/1000 [21:28<01:17,  1.64s/it]

[953/1000]
EN: Healthcare organizations are deploying AI agents to handle administrative tasks like insurance pre-authorizations and billing.
ASM: দৰি জেৱাৰ বিরীৰে লিমি,.
--------------------------------------------------

Translating:  95%|█████████████████████████▊ | 954/1000 [21:29<01:16,  1.66s/it]

[954/1000]
EN: Smart sensors in Indian ICUs are reducing unplanned admissions by providing continuous real-time monitoring of vitals.
ASM: দৰি জেৱাৰ বিরীৰে.
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 955/1000 [21:31<01:10,  1.57s/it]

[955/1000]
EN: The digital transformation of clinical trials in India is enabling remote patient monitoring through mobile devices.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে জেৰি লাৰু মিৰা রিন্দৰ ;.
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 956/1000 [21:32<01:04,  1.47s/it]

[956/1000]
EN: Indian pharmaceutical companies are integrating AI into their quality control systems to ensure paperless and compliant workflows.
ASM: দেৱাৰ বির্জীৱে বাৰে, লি জিলাৰ ৰাদৰা মিৰি কৰa ;.
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 957/1000 [21:33<01:02,  1.45s/it]

[957/1000]
EN: Low-cost needle-free drug delivery technologies are gaining traction for vaccine administration in pediatric clinics.
ASM: দৰি জেৱাৰ বির্রীৰ ৰালে,.
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 958/1000 [21:35<01:03,  1.50s/it]

[958/1000]
EN: Public health experts launched India's first Public Health Monitor to track real-time health outcomes across states.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 959/1000 [21:37<01:04,  1.57s/it]

[959/1000]
EN: Specialized medical tourism facilitation centers will be integrated into the new regional medical hubs.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 960/1000 [21:38<01:02,  1.56s/it]

[960/1000]
EN: Indian doctors are using hyper-personalized medicine to tailor treatments based on the genetic profile of individual patients.
ASM: দৰে জাৰি বিরীৱাৰৰ লিমিৰ ৰালাৰ বাৰ্দেৰা āৰু. : ?
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 961/1000 [21:40<01:04,  1.64s/it]

[961/1000]
EN: The adoption of 5G technology is improving the speed and reliability of remote robotic surgeries in India.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে মি 5 জিৰি লাৰু яৰ ) রিন্দৰা āৰ तिकिल्  एतेऩुम् সি्लॆ  गोंधळर्न аदेश ।
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 962/1000 [21:42<01:05,  1.71s/it]

[962/1000]
EN: 20 All India Institutes of Medical Sciences signed a memorandum to form a pan-India research consortium.
ASM: দৰে জাৰি বিরীৱাৰৰ লালে, মি ৰাদেৰা বাৰু āৰ্দিৰ പ്ৰ विरोधी яৰ ) রিন্দatি्लॆ  गोंधळर्न а : ?
--------------------------------------------------

Translating:  96%|██████████████████████████ | 963/1000 [21:43<01:00,  1.63s/it]

[963/1000]
EN: The AIIMS research consortium will focus on multicentric clinical trials for low-cost cancer treatments.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  96%|██████████████████████████ | 964/1000 [21:44<00:52,  1.45s/it]

[964/1000]
EN: A medical student at the Dharwad Institute of Mental Health unfortunately committed suicide in early February.
ASM: দেৱাৰ বির্জীৱে, বাৰে মি জিলাৰ ৰালে ।.
--------------------------------------------------

Translating:  96%|██████████████████████████ | 965/1000 [21:46<00:51,  1.48s/it]

[965/1000]
EN: The Maharashtra University of Health Sciences revoked the affiliation of Sinhgad Dental College over regulatory violations.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  97%|██████████████████████████ | 966/1000 [21:47<00:50,  1.50s/it]

[966/1000]
EN: A 40-year-old urologist suffered a cardiac arrest while speaking at an international conference in Indore.
ASM: দেৱাৰ বির্জীৰ ৰিলে,.
--------------------------------------------------

Translating:  97%|██████████████████████████ | 967/1000 [21:48<00:42,  1.29s/it]

[967/1000]
EN: The District Consumer Commission in Kannur held a surgeon liable for negligence in a varicose vein treatment.
ASM: দেৱাৰ বির্জীৱে লাৰে,.
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 968/1000 [21:50<00:43,  1.35s/it]

[968/1000]
EN: Two government doctors in Bhopal were sentenced to prison for securing medical seats with fake domicile certificates.
ASM: দেৱাৰ বির্জীৰ ৰালে, জিৰে বাৰি মিন্দৰা লাৰু রি्लॆ āৰ तिक ्रॆিদি কৰat ।
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 969/1000 [21:51<00:42,  1.36s/it]

[969/1000]
EN: Authorities in Maharashtra are seeking action against a pathologist for signing lab reports without proper registration.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 970/1000 [21:53<00:42,  1.42s/it]

[970/1000]
EN: The Central Council for Research in Ayurvedic Sciences signed an agreement to digitize rare Ayurveda manuscripts.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে জিৰি মি विरोधी লাৰু āৰা яৰ ) маৰat রিন্দৰ तिक. : ?
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 971/1000 [21:55<00:46,  1.59s/it]

[971/1000]
EN: Apollo Hospitals Chairman Dr. Prathap Reddy stated that the 2026 budget strengthens the vision of a healthier India.
ASM: . দেৱাৰ জির্বিলাৰীৰ ৰিলে, বাৰে মি āৰি কিৰা а 2026 яৰ तिकৰু мিদৰराज പ്ৰ ꯃꯦ  वसूल विरोधी ন্দি समारंभ বেৰ टओৱে ।
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 972/1000 [21:56<00:44,  1.59s/it]

[972/1000]
EN: Max Healthcare plans to expand its robotic-assisted surgery program across its network of hospitals.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  97%|██████████████████████████▎| 973/1000 [21:57<00:39,  1.45s/it]

[973/1000]
EN: Health experts warned that the unorganized diagnostic sector in India will face consolidation due to stricter quality norms.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  97%|██████████████████████████▎| 974/1000 [21:59<00:39,  1.53s/it]

[974/1000]
EN: The Indian Council of Medical Research received 4,000 crore rupees to bolster indigenous medical research.
ASM: . জিৰে দৰা বিরীৱাৰ লিলা, বাৰি ৰামি র্দেৱিন্দ ) പ്ৰু а 4,000 яৰ तिकৰ सब ।
--------------------------------------------------

Translating:  98%|██████████████████████████▎| 975/1000 [22:00<00:32,  1.32s/it]

[975/1000]
EN: Public health officials are drafting a new Planetary Health Policy Framework to address climate-linked diseases.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  98%|██████████████████████████▎| 976/1000 [22:02<00:34,  1.43s/it]

[976/1000]
EN: The Food Safety and Standards Authority of India is working to make healthy food more affordable than unhealthy options.
ASM: দেৱাৰ বির্জীৱে জিলে, মিৰি বাৰে ৰাদৰা লাৰু রিন্দি्लॆ āৰat പ് तिकৰ ꯃꯦ яৰ ) ।
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 977/1000 [22:03<00:34,  1.50s/it]

[977/1000]
EN: Researchers at AIIMS Delhi are investigating the use of AI to reduce hospital-acquired infections.
ASM: দেৱাৰ বির্জীৰ ৰালে, বাৰে জেৰি মিৰু লাৰা āৰायला яৰ ) പ्लॆक्कूटাৰৰ  गळिल् маৰat ।
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 978/1000 [22:05<00:31,  1.43s/it]

[978/1000]
EN: The National AIDS Control Organisation is upgrading blood transfusion services to ensure nationwide safety and availability.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 979/1000 [22:06<00:30,  1.47s/it]

[979/1000]
EN: Indian pediatricians noted a rise in parental awareness regarding neurodivergence and behavioral health issues.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 980/1000 [22:08<00:32,  1.65s/it]

[980/1000]
EN: Medical value tourism in India is expected to grow as the government streamlines visa processes for international patients.
ASM: দেৱাৰ বির্জীৱে জিলে, বাৰি লাৰে ৰাদৰা āৰু মি করে ; яৰ तिकिल् রিন্দ ) ।
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 981/1000 [22:10<00:32,  1.69s/it]

[981/1000]
EN: The WHO Global Traditional Medicine Centre in Jamnagar is being upgraded to improve evidence-based research.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 982/1000 [22:11<00:27,  1.51s/it]

[982/1000]
EN: Indian generic manufacturers are preparing for the patent expiry of several major global obesity medications.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 983/1000 [22:13<00:25,  1.53s/it]

[983/1000]
EN: A new digital curriculum was introduced to train public health leaders in epidemiology and modern technology.
ASM: দেৱাৰ বির্জীৱে লিমি জিৰে, লাৰি ৰাদৰা বাৰু яৰ ) রিন্দি्लॆ āৰ तिक घटनुपিक्कूटা ।
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 984/1000 [22:14<00:24,  1.55s/it]

[984/1000]
EN: The government is upgrading AYUSH pharmacies to ensure higher quality standards for traditional medicines.
ASM: দেৱাৰ বির্জীৰ ৰালে,.
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 985/1000 [22:16<00:24,  1.60s/it]

[985/1000]
EN: Several district hospitals in Uttar Pradesh are now equipped with 24/7 emergency care and trauma units.
ASM: . দেৱাৰ বির্জীৰ ৰিলে বাৰে, а-?
--------------------------------------------------

Translating:  99%|██████████████████████████▌| 986/1000 [22:18<00:24,  1.76s/it]

[986/1000]
EN: Private healthcare providers are increasing investments in Tier 3 cities to capture the growing rural market.
ASM: দেৱাৰ বিরী 3 জিলে, বাৰে মি লাৰ্দৰি ৰা तिकৰা āৰু яৰ ) রিন্দিৰ 4 പ്রে 5 атি्लॆ мিावन क्कूटি কৰat ।
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 987/1000 [22:19<00:21,  1.65s/it]

[987/1000]
EN: The Indian healthcare workforce is being upskilled through new digital certifications in allied health disciplines.
ASM: দেৱাৰ বির্জীৱে বাৰে,.
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 988/1000 [22:21<00:20,  1.69s/it]

[988/1000]
EN: Public health summits in 2026 emphasized the importance of data-driven decision-making for epidemic prevention.
ASM: . দৰিরে জাৱাৰ বীৱেৰে, লিলাৰ ৰামি বাৰা āৰু а 2026 яৰ तिकৰ্ন্দ स्बराज ।
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 989/1000 [22:23<00:17,  1.61s/it]

[989/1000]
EN: Hospitals in Mumbai are reporting a shift toward integrated care models for chronic lifestyle diseases.
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 990/1000 [22:24<00:16,  1.64s/it]

[990/1000]
EN: The Ministry of Health is focusing on improving the nurse-to-patient ratio in public hospitals through new recruitment drives.
ASM: দেৱাৰ বির্জীৱে. : ?
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 991/1000 [22:26<00:14,  1.57s/it]

[991/1000]
EN: India is positioning itself as a global hub for the manufacturing of affordable biologics and specialized therapies.
ASM: দৰে জাৰি বিরীৱাৰৰ লিলাৰ মি,.
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 992/1000 [22:27<00:11,  1.47s/it]

[992/1000]
EN: PGIMER doctors achieve major breakthrough in deadly Celphos poisoning
ASM: দেৱাৰ বির্জীৱে বাৰি জিলে, মিৰে ৰাদৰা লাৰু রিন্দ स्बराज ।
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 993/1000 [22:28<00:10,  1.44s/it]

[993/1000]
EN: What a 12-hour work day can do to your metabolic, mental and reproductive health
ASM: দেৱাৰ বির্জীৰ ৰালিলা, বাৰে মি জিৰি কৰা ।
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 994/1000 [22:30<00:08,  1.44s/it]

[994/1000]
EN: Healthcare services disrupted as doctors across states protest Kolkata colleague’s rape-murder
ASM: দেৱাৰ বির্জীৱে জিলে,.
--------------------------------------------------

Translating: 100%|██████████████████████████▊| 995/1000 [22:31<00:06,  1.28s/it]

[995/1000]
EN: Manmohan Singh unveils multi-crore healthcare plan for paramilitary forces
ASM: দেৱাৰ বির্জীৱে বাৰি জিলে,.
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 996/1000 [22:33<00:05,  1.49s/it]

[996/1000]
EN: US Senate Hearing Explodes After Senator Questions Indian Origin Doctor on Men’s Pregnancy
ASM: দেৱাৰ বির্জীৱে. :-,ःᱹ ; ৰালি বাৰিলা জিৰা āৰে ) মিন্দৰুৱa яৰ तिक রি विरोधी പ്ৰ 49 ोपিদ स्बराज ।
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 997/1000 [22:34<00:04,  1.41s/it]

[997/1000]
EN: Dr. D N gupta addresses the lack of awareness surrounding Vitamin D deficiency.
ASM: দেৱাৰ বির্জে,.
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 998/1000 [22:36<00:02,  1.50s/it]

[998/1000]
EN: Oncologist shares case of non-tobacco related cancer in 21-year-old man with ‘sharp teeth,’ says ‘It could have been identified’
ASM: . দেৱাৰ বিজৰ ৰারে লিৰি জীৱaৰ্দৰে, বাৰু লাৰ तिकिल् মি विरोधी പ് : ?
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 999/1000 [22:37<00:01,  1.41s/it]

[999/1000]
EN: Nutritionist says pineapple and cinnamon may help reduce period cramps naturally
ASM: দৰি জেৱাৰ বিরীৰে লিমি ৰালাৰ,.
--------------------------------------------------

Translating: 100%|██████████████████████████| 1000/1000 [22:38<00:00,  1.36s/it]

[1000/1000]
EN: Don’t brush before bed? Your heart might pay the price
ASM: . দেৱাৰ বির্জীৱিলাৰ ৰালে, বাৰে মি জিৰিন্দৰা क्कूटি কৰat
--------------------------------------------------
✅ Saved to /home/dingku/Desktop/assamese_translations.txt

============================================================
Translating mni_beng...
============================================================

Found 1000 sentences.

Translating:   0%|                             | 1/1000 [00:01<31:18,  1.88s/it]

[1/1000]
EN: NDTV has learnt from sources that the T20 World Cup 2026 match between India and Pakistan is ON.
MNI_BENG: ., জিদের্রী বিলিলারামিন্দ चा я 2026 দিরিশি কিসরর dat ৱিুর 490 ाय़ ;
--------------------------------------------------

Translating:   0%|                             | 2/1000 [00:02<23:13,  1.40s/it]

[2/1000]
EN: The PCB placed several demands before the ICC.
MNI_BENG: জিদের বির্লিলারামিন্দরী ৱিশি কিসরু ।
--------------------------------------------------

Translating:   0%|                             | 3/1000 [00:04<24:16,  1.46s/it]

[3/1000]
EN: The PCB pushed for ICC intervention to facilitate a bilateral series between India and Pakistan.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারুরি्लॆ ята, সি কিনরেশি 1954 ৱিat श्री @ b.
--------------------------------------------------

Translating:   0%|                             | 4/1000 [00:05<21:41,  1.31s/it]

[4/1000]
EN: Virat Kohli and Rohit Sharma have been demoted to Grade B in BCCI's central contract list for 2025-26.
MNI_BENG: 2025-26 দেরিজিবিী  b.া.e.h.্র., লা.
--------------------------------------------------

Translating:   0%|▏                            | 5/1000 [00:06<22:10,  1.34s/it]

[5/1000]
EN: Thirty senior men's cricketers have been awarded central contracts, with the BCCI doing away with the A+ grade.
MNI_BENG: . দেরিজিব্রালারী লিমিন্দ चा ाय़, я.h.e. in.at.a.शय़.
--------------------------------------------------

Translating:   1%|▏                            | 6/1000 [00:08<22:22,  1.35s/it]

[6/1000]
EN: As per the 2024-25 BCCI contracts, any player in Grade A would receive Rs 5 crore annually.
MNI_BENG: -25 জিদের্রী বিলিলারাच्च चा মিন্দর 5 দিরি কিসি तिकिल् я?
--------------------------------------------------

Translating:   1%|▏                            | 7/1000 [00:09<19:19,  1.17s/it]

[7/1000]
EN: Grade B players would get Rs 3 crore, while
MNI_BENG: জিদের. b चा বির্র 3 লি ।
--------------------------------------------------

Translating:   1%|▏                            | 8/1000 [00:09<17:05,  1.03s/it]

[8/1000]
EN: Grade C players would get Rs 1 crore.
MNI_BENG: জিদের 1 বিরী লার্লি ।
--------------------------------------------------

Translating:   1%|▎                            | 9/1000 [00:11<17:45,  1.07s/it]

[9/1000]
EN: Earlier, Grade A+ players (Kohli, Rohit, Jasprit Bumrah, Ravindra Jadeja) used to receive Rs 7 crore.
MNI_BENG: জিরেদ (.h. া. ) বি.ী.্র. in.লা.ল., я.
--------------------------------------------------

Translating:   1%|▎                           | 10/1000 [00:12<19:14,  1.17s/it]

[10/1000]
EN: The BCCI has not yet officially declared whether the payment structure for 2025-26 will be any different.
MNI_BENG: 2025-26 জিরেদ্রলিবিলারামিন্দরী দেরি কিদিশিসর dat, я.
--------------------------------------------------

Translating:   1%|▎                           | 11/1000 [00:13<18:20,  1.11s/it]

[11/1000]
EN: 21 women cricketers classified in Grade A, B and C.
MNI_BENG: জির 21  B দেলা b, বিী C.
--------------------------------------------------

Translating:   1%|▎                           | 12/1000 [00:14<19:58,  1.21s/it]

[12/1000]
EN: Harmanpreet Kaur, Smriti Mandhana, Deepti Sharma and Jemimah Rodrigues are the four players to be included in Grade A.
MNI_BENG: জিদেরী বির্রালিমিলার , দরেন্দ রিস বারুরचर चा  কি्लॆ ाय़ विरोधी  ग्यास я?
--------------------------------------------------

Translating:   1%|▎                           | 13/1000 [00:16<20:13,  1.23s/it]

[13/1000]
EN: The cycle for new central contract is based on performance and volume of games played during the preceding season.
MNI_BENG: জিদেরী বির্রালিন্দিলারিমি কি्लॆ, বারেশিসর dā 49.hant.िल्.at.
--------------------------------------------------

Translating:   1%|▍                           | 14/1000 [00:17<18:43,  1.14s/it]

[14/1000]
EN: Pakistan and Bangladesh's demands from the International Cricket Council (ICC) have just grown bigger.
MNI_BENG: জিদের (.া.h.e. ) বি.ী.্র., লা.
--------------------------------------------------

Translating:   2%|▍                           | 15/1000 [00:18<18:32,  1.13s/it]

[15/1000]
EN: The 2031 edition of the ODI World Cup is set to be played in India and Bangladesh.
MNI_BENG: 2031 দেরিজিবি..ᱹ = ী.া.h.e.m.্র.
--------------------------------------------------

Translating:   2%|▍                           | 16/1000 [00:18<16:23,  1.00it/s]

[16/1000]
EN: At present, the hybrid model is applicable until 2027.
MNI_BENG: 2027 জিদের্রাবিলালি ।
--------------------------------------------------

Translating:   2%|▍                           | 17/1000 [00:19<16:58,  1.04s/it]

[17/1000]
EN: The extension would allow Bangladesh and Pakistan to play all their matches in Bangladesh and not India.
MNI_BENG: জিদের বির্লিলারামিী,.ᱹ 49.at. in.y.h.
--------------------------------------------------

Translating:   2%|▌                           | 18/1000 [00:21<17:04,  1.04s/it]

[18/1000]
EN: The BCB was represented by its head Aminul Islam Bulbul while PCB chairman Mohsin Naqvi was also present.
MNI_BENG: জিদের বির্রালিী.ᱹ.h.at.লা., я.
--------------------------------------------------

Translating:   2%|▌                           | 19/1000 [00:22<16:55,  1.04s/it]

[19/1000]
EN: ICC's deputy chairman Imran Khawaja was present in the meeting.
MNI_BENG: জিদের বির্রালিমিলারী..
--------------------------------------------------

Translating:   2%|▌                           | 20/1000 [00:23<17:03,  1.04s/it]

[20/1000]
EN: No joint declaration was issued after the four-hour meeting.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী я 1954 ।
--------------------------------------------------

Translating:   2%|▌                           | 21/1000 [00:24<16:52,  1.03s/it]

[21/1000]
EN: The hybrid model arrangement was introduced after India refused to tour Pakistan for the 2025 Champions Trophy.
MNI_BENG: জিদের.-, বি.া.লা.ী.h.্র. ) লে.
--------------------------------------------------

Translating:   2%|▌                           | 22/1000 [00:25<19:09,  1.18s/it]

[22/1000]
EN: After extensive negotiations, a hybrid model was accepted by all parties, including the ICC.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिकआ ятал, বারেসি কিশি दक्षिण b चा  बुधबार ।
--------------------------------------------------

Translating:   2%|▋                           | 23/1000 [00:26<17:15,  1.06s/it]

[23/1000]
EN: The second part of the arrangement states that Pakistan will not travel to India for the 2026 T20 World Cup.
MNI_BENG: জিদেরী  2026 T20 বির্রালি.
--------------------------------------------------

Translating:   2%|▋                           | 24/1000 [00:27<19:51,  1.22s/it]

[24/1000]
EN: As a result, all of Pakistan's matches (even if they reach the final) will be played in Sri Lanka.
MNI_BENG: জিদেরা ( বির্রী ) লিলারিমিন্দি কিুরেসিশি, ятаре বার चा  बुधबार ।
--------------------------------------------------

Translating:   2%|▋                           | 25/1000 [00:29<19:15,  1.18s/it]

[25/1000]
EN: Bangladesh, Pakistan, and India must be treated the same.
MNI_BENG: জিদের বির্লিলারামিী, বারেন্দরিসরর dat.
--------------------------------------------------

Translating:   3%|▋                           | 26/1000 [00:30<18:59,  1.17s/it]

[26/1000]
EN: Now, Gavaskar has taken an indirect jibe at Hussain
MNI_BENG: জিদেরী বির্রালিন্দ चा মিলারি्लॆ দিসি কিশিন dat ।
--------------------------------------------------

Translating:   3%|▊                           | 27/1000 [00:31<19:24,  1.20s/it]

[27/1000]
EN: He went on to give the example of the 2003 World Cup, when England refused to tour Zimbabwe in protest against Robert Mugabe's regime.
MNI_BENG: জিরেদ.া.ᱹ, বি.ী.at.a.h.e.্র.লা.ল. দ.ম. in.
--------------------------------------------------

Translating:   3%|▊                           | 28/1000 [00:32<19:39,  1.21s/it]

[28/1000]
EN: Samson's knock was full of intent but fell short in effectiveness quotient.
MNI_BENG: জিদের বির্লিলারান্দরী মি কিুরিশি, я.
--------------------------------------------------

Translating:   3%|▊                           | 29/1000 [00:33<19:18,  1.19s/it]

[29/1000]
EN: With this win, India overtook Pakistan at the summit of Group A courtesy of a superior net run-rate.
MNI_BENG: জিদের বির্রালিমিলাী., я.h.m.at.re. किराम.
--------------------------------------------------

Translating:   3%|▊                           | 30/1000 [00:35<19:29,  1.21s/it]

[30/1000]
EN: India batter Abhishek Sharma will take no part in the T20 World Cup 2026 clash against Namibia in New Delhi on Thursday.
MNI_BENG: জিদের  2026 বির্লিলারামিন্দী, বারুরি्लॆ ाय़.h.e.m. in.िल्.
--------------------------------------------------

Translating:   3%|▊                           | 31/1000 [00:36<19:08,  1.19s/it]

[31/1000]
EN: Abhishek isn't fine still, might take one or two games.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারেসরিশি কিনরর dat.
--------------------------------------------------

Translating:   3%|▉                           | 32/1000 [00:36<15:44,  1.03it/s]

[32/1000]
EN: Samson comes in.
MNI_BENG: জিদের ।
--------------------------------------------------

Translating:   3%|▉                           | 33/1000 [00:38<17:07,  1.06s/it]

[33/1000]
EN: Bumrah comes in for Siraj," said Suryakumar at the toss.
MNI_BENG: জিদের বির্রালিমিলার দরী  तिकाय़, я.
--------------------------------------------------

Translating:   3%|▉                           | 34/1000 [00:39<18:07,  1.13s/it]

[34/1000]
EN: Defending with dew will build our confidence. Hope our batters entertain the crowd.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারিসি কি तिकिल् রেশি किराम, āstra.hant.
--------------------------------------------------

Translating:   4%|▉                           | 35/1000 [00:40<18:25,  1.15s/it]

[35/1000]
EN: It's a big tournament, dew will be a big factor.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দat, я.
--------------------------------------------------

Translating:   4%|█                           | 36/1000 [00:41<18:45,  1.17s/it]

[36/1000]
EN: India made two changes to the side that beat the USA on the opening day of the tournament.
MNI_BENG: জিদের বির্লিলারান্দরী ᱟᱢ, মি কিসরিশিন দিक्कूट 49:च्चि.h.िल्.
--------------------------------------------------

Translating:   4%|█                           | 37/1000 [00:42<18:22,  1.15s/it]

[37/1000]
EN: Sanju Samson replaced Abhishek, while Jasprit Bumrah replaced Mohammed Siraj in the India XI.
MNI_BENG: জিরেদ্রী বিলারালিন্দেমি কেরি तिक bām.hant.at.शय़.
--------------------------------------------------

Translating:   4%|█                           | 38/1000 [00:43<18:08,  1.13s/it]

[38/1000]
EN: India take on Pakistan next, with the team set to travel to Colombo for the game on February 15.
MNI_BENG: জিদের.a.া.ী.h., বি.্র.লা. in.
--------------------------------------------------

Translating:   4%|█                           | 39/1000 [00:45<19:18,  1.21s/it]

[39/1000]
EN: The cabinet agreed with certain conditions as per the Cunha report.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দী বারি কিুরে्लॆ সিশিat ৱিতি तिकिल् ।
--------------------------------------------------

Translating:   4%|█                           | 40/1000 [00:46<17:15,  1.08s/it]

[40/1000]
EN: He mentioned in the report a maximum of 35,000 people and other conditions.
MNI_BENG: জিদের.h..ব্রলা.
--------------------------------------------------

Translating:   4%|█▏                          | 41/1000 [00:47<18:52,  1.18s/it]

[41/1000]
EN: India reached the 100-run mark in just 6.5 overs - the fastest team hundred in T20 World Cup history.
MNI_BENG: .ᱹ জিদের্রাবিলাী লিন্দর 5 : 0- 100, 000 я.h.e.m. in.at. किराम 7.
--------------------------------------------------

Translating:   4%|█▏                          | 42/1000 [00:49<21:32,  1.35s/it]

[42/1000]
EN: After being asked to bat first, India were off to a decent start, making 8/0 in the first over.
MNI_BENG: . দের্জিবিলি, মিরী ালারিন্দর 5 : 0 বারুরেশি কিসরat ाय़ / яᱹ ) ।
--------------------------------------------------

Translating:   4%|█▏                          | 43/1000 [00:51<23:42,  1.49s/it]

[43/1000]
EN: After four overs, the defending champions reached 43/1, with Ishan Kishan finding a couple of boundaries.
MNI_BENG: জিদের /., বির্রালিমী লারিন্দ चा я.
--------------------------------------------------

Translating:   4%|█▏                          | 44/1000 [00:52<21:24,  1.34s/it]

[44/1000]
EN: On the first ball of the 11th over, spinner Bernard Scholtz dismissed captain Suryakumar Yadav for just 12.
MNI_BENG: জিরেদ 11 বিলার্রী লিন্দ.া.h., মa. in. 49.
--------------------------------------------------

Translating:   4%|█▎                          | 45/1000 [00:53<21:03,  1.32s/it]

[45/1000]
EN: India lost another wicket quickly when Tilak Varma was removed for 25 by Namibia skipper Erasmus in the 12th over.
MNI_BENG: জিদের  25 বির্লিলারামিন্দর 5 দিী, ्रॆप.ᱹ я.िल्.h. in.
--------------------------------------------------

Translating:   5%|█▎                          | 46/1000 [00:54<20:42,  1.30s/it]

[46/1000]
EN: Shivam Dube and Hardik Pandya then combined to hammer 24 runs off Bernard Scholtz as India raced to 168/4.
MNI_BENG: /4 দেরিজিব্র 24 লিলারামিন্দরী বারেসির 4.
--------------------------------------------------

Translating:   5%|█▎                          | 47/1000 [00:55<21:04,  1.33s/it]

[47/1000]
EN: By the end of the 18th over, India had reached 199/4 with Pandya and Dube going strong.
MNI_BENG: .ᱹ জিদের 18, বির্র 11/ 49/4 লিলাামিন্দী ।
--------------------------------------------------

Translating:   5%|█▎                          | 48/1000 [00:56<19:39,  1.24s/it]

[48/1000]
EN: On the first ball of the 19th over, Pandya completed his fifty off 27 deliveries as India crossed the 200-run mark.
MNI_BENG: .ᱹ জিদের্রী বিলিমিালার 27 я., 000.
--------------------------------------------------

Translating:   5%|█▎                          | 49/1000 [00:57<17:56,  1.13s/it]

[49/1000]
EN: Shivam Dube was run out for 23 after a mix-up with Rinku Singh.
MNI_BENG: জিদের., বি.ী.া.h.্র.লা.ল.
--------------------------------------------------

Translating:   5%|█▍                          | 50/1000 [00:58<16:55,  1.07s/it]

[50/1000]
EN: India then lost Rinku Singh (1) and Arshdeep Singh (2) in the final over, finishing at 209/9.
MNI_BENG: /9.. দের ( 1.h. ) জি.ী.া., লা.
--------------------------------------------------

Translating:   5%|█▍                          | 51/1000 [01:00<19:33,  1.24s/it]

[51/1000]
EN: ICC Men’s T20 World Cup 2026 began on February 7, 2026, at Sinhalese Sports Club Ground with Pakistan playing Netherlands in the opening match.
MNI_BENG: জিদের  2026 বির্লিলাান্দী ᱟᱢ, মিুরি কিশিন বারেদরचर я..h.e.m.a. in.at.re.िल्. चॆप्टम्पर्.
--------------------------------------------------

Translating:   5%|█▍                          | 52/1000 [01:01<19:54,  1.26s/it]

[52/1000]
EN: Bangladesh national cricket team faced the India men's national cricket team in an opening match reported ahead of the 2026 T20 tournament.
MNI_BENG: জিদেরী.ᱹ বিলা.া., লি.at.্র. in.re.a.h. ম.e.
--------------------------------------------------

Translating:   5%|█▍                          | 53/1000 [01:02<17:52,  1.13s/it]

[53/1000]
EN: Ishan Kishan struck a rapid half-century.
MNI_BENG: জিদের বির্রালি.
--------------------------------------------------

Translating:   5%|█▌                          | 54/1000 [01:03<19:14,  1.22s/it]

[54/1000]
EN: Faf du Plessis scored a half-century and Mitchell Starc took a five-wicket haul in the same match report.
MNI_BENG: জিদের বির্রালিমিলার দরী বারেন্দ রি्लॆ সিন -  কিশিat, āsta. b.िल्.h.
--------------------------------------------------

Translating:   6%|█▌                          | 55/1000 [01:05<19:28,  1.24s/it]

[55/1000]
EN: Jasprit Bumrah and Ravindra Jadeja were reported to have been demoted in the 2025–26 central contracts discussion.
MNI_BENG: .ᱹ জিদের্রী বিলিলারামিন্দ चा ाय़ 2025/26 я.h., দি.
--------------------------------------------------

Translating:   6%|█▌                          | 56/1000 [01:06<20:08,  1.28s/it]

[56/1000]
EN: Rohit Sharma carried the men’s T20 World Cup trophy during a promotional appearance.
MNI_BENG: জিদের , বির্রালিমিলারীя দরিন্দ चा বারুরেসি কিশিতি तिकिल् ाय़?
--------------------------------------------------

Translating:   6%|█▌                          | 57/1000 [01:07<18:26,  1.17s/it]

[57/1000]
EN: The International Cricket Council update said a high-profile match involving Pakistan would go ahead on February 15, 2026, in Colombo.
MNI_BENG: জিদের.h.ᱹ বি.ী.া.্র.ল., লা.
--------------------------------------------------

Translating:   6%|█▌                          | 58/1000 [01:08<19:18,  1.23s/it]

[58/1000]
EN: The New Zealand national cricket team lost the first ODI by four wickets to the India men's national cricket team.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেসি কি्लॆ বারুরचर ā 49.at.शय़.h.िल्..
--------------------------------------------------

Translating:   6%|█▋                          | 59/1000 [01:10<20:36,  1.31s/it]

[59/1000]
EN: Australia national cricket team ended day one at 67 for seven in reply to 150 by the India men's national cricket team in a Test match post.
MNI_BENG: জিদের., বি.া.ী.h.্র.লা.at.re. in.ম.ল.a. বা. 1954. 49. विळैयाट्टु.
--------------------------------------------------

Translating:   6%|█▋                          | 60/1000 [01:12<23:09,  1.48s/it]

[60/1000]
EN: The India national under-19 cricket team won the ICC U19 World Cup final by 100 runs against the England national under-19 cricket team in Harare.
MNI_BENG: - জিদের্রাবিলি, মিরী লারিন্দি কি तिक bच्च चा বারুরেস দরचर ята..ᱹ  बुधबार ।
--------------------------------------------------

Translating:   6%|█▋                          | 61/1000 [01:13<23:00,  1.47s/it]

[61/1000]
EN: Members of the India women's national cricket team were given a grand welcome after their title-winning campaign.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেসর चा ята ) বার चॆप्टम्पर् 2017-िल् ৱিশি কি्लॆ तिक b.
--------------------------------------------------

Translating:   6%|█▋                          | 62/1000 [01:15<22:34,  1.44s/it]

[62/1000]
EN: The India women's national cricket team lifting the ICC Women’s World Cup as one of the year’s landmark moments.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারুরি কি्लॆ দ चा রেশি तिकिल् ाय़.h.at.a.
--------------------------------------------------

Translating:   6%|█▊                          | 63/1000 [01:16<22:03,  1.41s/it]

[63/1000]
EN: The Indian Premier League season in 2025 was reported as suspended indefinitely amid escalating India–Pakistan military tensions.
MNI_BENG: দেরি -ᱹ জিবির্রী লারামিলি, я..h.e.at.y.a. in.
--------------------------------------------------

Translating:   6%|█▊                          | 64/1000 [01:17<19:37,  1.26s/it]

[64/1000]
EN: The Eden Gardens hosted the opening spectacle for the 18th edition of the Indian Premier League.
MNI_BENG: জিদের.ᱹ বিলা.া.ী.h.্র., লি.
--------------------------------------------------

Translating:   6%|█▊                          | 65/1000 [01:18<18:02,  1.16s/it]

[65/1000]
EN: Royal Challengers Bengaluru named Rajat Patidar as captain for the season starting March 21.
MNI_BENG: জিদের  21.. বী.া.লা.h., লি.ম.্র.
--------------------------------------------------

Translating:   7%|█▊                          | 66/1000 [01:19<17:50,  1.15s/it]

[66/1000]
EN: Chennai Super Kings posted their lowest home total and suffered a fifth straight loss.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি तिकिल् দরचर., я.h.at.
--------------------------------------------------

Translating:   7%|█▉                          | 67/1000 [01:20<18:36,  1.20s/it]

[67/1000]
EN: A Dharamsala fixture involving Punjab Kings and Delhi Capitals was called off after a blackout.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী, বারি কিুরেশিসর dā 1954 ।
--------------------------------------------------

Translating:   7%|█▉                          | 68/1000 [01:22<19:01,  1.22s/it]

[68/1000]
EN: Punjab Kings defeated Mumbai Indians in Jaipur to secure a top-two league finish.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারুরি - ята.
--------------------------------------------------

Translating:   7%|█▉                          | 69/1000 [01:22<17:40,  1.14s/it]

[69/1000]
EN: KL Rahul became the fastest Indian to 8,000 T20 runs after an unbeaten 112.
MNI_BENG: জিদের., 000 বিলা.া.ী. in.
--------------------------------------------------

Translating:   7%|█▉                          | 70/1000 [01:24<19:04,  1.23s/it]

[70/1000]
EN: Virat Kohli spoke about the June 4 stampede linked to his franchise’s celebrations.
MNI_BENG: জিদের 4 বির্রী লিমিলারান্দর 5 রিুর चा বারেস দি কিশিat,  तिकराज bā.
--------------------------------------------------

Translating:   7%|█▉                          | 71/1000 [01:25<18:50,  1.22s/it]

[71/1000]
EN: The uncertainty over player retention created suspense ahead of the next Indian Premier League season.
MNI_BENG: জিদের বির্লিলারান্দরী ᱟᱢ, মি কিুরিশি 1954.
--------------------------------------------------

Translating:   7%|██                          | 72/1000 [01:26<16:30,  1.07s/it]

[72/1000]
EN: Rafael Nadal announced he would retire.
MNI_BENG: জিদের বির্রালি.
--------------------------------------------------

Translating:   7%|██                          | 73/1000 [01:27<15:42,  1.02s/it]

[73/1000]
EN: Carlos Alcaraz beat Novak Djokovic to win his first major title.
MNI_BENG: জিদের বির্রালিমিী..ᱹ я.h.m.
--------------------------------------------------

Translating:   7%|██                          | 74/1000 [01:28<17:22,  1.13s/it]

[74/1000]
EN: Alexander Zverev lost a marathon match to Carlos Alcaraz in a five-set battle.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দি्लॆ বারেস яла,  तिकराज ৱিশি কররু ।
--------------------------------------------------

Translating:   8%|██                          | 75/1000 [01:29<17:54,  1.16s/it]

[75/1000]
EN: Rohan Bopanna announced his retirement from professional tennis.
MNI_BENG: জিদের বির্রালালিমিন্দরী দিসরিশি কিুরেন ān 1954 ।
--------------------------------------------------

Translating:   8%|██▏                         | 76/1000 [01:30<17:41,  1.15s/it]

[76/1000]
EN: A 14-place leap that signaled an upswing for India Davis Cup team in international tennis standings.
MNI_BENG: জিরেদ 14..বি.at.া.ী.লা.h., দ্র 11.লে.ম. in.
--------------------------------------------------

Translating:   8%|██▏                         | 77/1000 [01:31<16:54,  1.10s/it]

[77/1000]
EN: Elena Rybakina overcame Aryna Sabalenka to win the 2026 Australian Open final.
MNI_BENG: জিদেরী  2026 বির্রালিমিন্দরলা я..
--------------------------------------------------

Translating:   8%|██▏                         | 78/1000 [01:32<15:57,  1.04s/it]

[78/1000]
EN: Novak Djokovic became the first player to reach 400 Grand Slam singles match wins in the Open Era.
MNI_BENG: জিদের., বিলা.া.্র.ী.লি. 49.
--------------------------------------------------

Translating:   8%|██▏                         | 79/1000 [01:34<16:42,  1.09s/it]

[79/1000]
EN: The India men's national field hockey team and its Olympic bronze-medal campaign in a dedicated post.
MNI_BENG: জিদের বির্লিলারামিন্দী.., দি.at.शय़.h.e.m.a. in.
--------------------------------------------------

Translating:   8%|██▏                         | 80/1000 [01:35<17:48,  1.16s/it]

[80/1000]
EN:  The India men's national field hockey team across major tournaments.
MNI_BENG: জিদের বির্লিলারামিন্দরী দিসরি কি तिकआ ятал, বার चा রেশিक्कूट 49.
--------------------------------------------------

Translating:   8%|██▎                         | 81/1000 [01:36<17:11,  1.12s/it]

[81/1000]
EN: The India men's national field hockey team beat South Korea men's national field hockey team 4–1 in a match update.
MNI_BENG: জিদেরী বির্রালিন্দ.h.., লা. किराम 7.at.
--------------------------------------------------

Translating:   8%|██▎                         | 82/1000 [01:37<16:14,  1.06s/it]

[82/1000]
EN: The house of K. D. Singh Babu would be developed as a tourist attraction.
MNI_BENG: জিদেরী বির্রালি.. b.a.h., লা.
--------------------------------------------------

Translating:   8%|██▎                         | 83/1000 [01:38<15:09,  1.01it/s]

[83/1000]
EN: Lakshya Sen finished fourth in a tournament.
MNI_BENG: জিদের বির্রালি.
--------------------------------------------------

Translating:   8%|██▎                         | 84/1000 [01:39<15:59,  1.05s/it]

[84/1000]
EN: Saina Nehwal confirmed her retirement from competitive badminton.
MNI_BENG: জিদের বির্লিলাামিন্দরী, বারেসরিশিावन দি কিুররचर ята.
--------------------------------------------------

Translating:   8%|██▍                         | 85/1000 [01:39<14:11,  1.08it/s]

[85/1000]
EN: R. Vaishali won the FIDE Women’s Grand Swiss.
MNI_BENG: জিদের.. বি.া.ী.
--------------------------------------------------

Translating:   9%|██▍                         | 86/1000 [01:40<12:49,  1.19it/s]

[86/1000]
EN: R. Praggnanandhaa came from behind to win a game.
MNI_BENG: জিদেরী.a.া.লা.
--------------------------------------------------

Translating:   9%|██▍                         | 87/1000 [01:41<11:50,  1.28it/s]

[87/1000]
EN: D. Gukesh as the youngest world chess champion in history.
MNI_BENG: জিদেরী.ᱹ বি.
--------------------------------------------------

Translating:   9%|██▍                         | 88/1000 [01:42<12:54,  1.18it/s]

[88/1000]
EN: D. Gukesh secured his first win at Tata Steel Chess Masters 2026.
MNI_BENG: .. জিদের বির্রালিী লারিমিন্দি, я.वा.िल्.
--------------------------------------------------

Translating:   9%|██▍                         | 89/1000 [01:43<14:29,  1.05it/s]

[89/1000]
EN: Avinash Sable became the first Indian man to qualify for the men’s 3000m steeplechase final at Paris Olympics 2024.
MNI_BENG: জিদেরী.., বিলা.া.h.e.at.वा.্র. লি.ম. in.
--------------------------------------------------

Translating:   9%|██▌                         | 90/1000 [01:44<15:18,  1.01s/it]

[90/1000]
EN: Mirabai Chanu returned to competition as she prepared for upcoming international events.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারেসরি কিশি 1954 ৱি्लॆ я 543 ।
--------------------------------------------------

Translating:   9%|██▌                         | 91/1000 [01:45<15:17,  1.01s/it]

[91/1000]
EN: Manu Bhaker and Harmanpreet Singh among athletes highlighted in a sports-honours post.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিস - ān.hant. in.at.
--------------------------------------------------

Translating:   9%|██▌                         | 92/1000 [01:46<16:45,  1.11s/it]

[92/1000]
EN: At the Milan–Cortina Winter Olympics 2026, Ilia Malinin landed a backflip on one skate in an Olympics moment.
MNI_BENG: দেরি  2026 জিবির্রলিমালারী विरोधी, বারেন্দ चा ाय़.h.e.. я.िल्.a. in.
--------------------------------------------------

Translating:   9%|██▌                         | 93/1000 [01:48<18:29,  1.22s/it]

[93/1000]
EN:  Anastasiia Gubanova delivered a performance featuring Indian cultural elements on the ice in Milan.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারি কি्लॆ সিশিावन নিুরचर ята, āstha ाय़?
--------------------------------------------------

Translating:   9%|██▋                         | 94/1000 [01:49<17:30,  1.16s/it]

[94/1000]
EN: Formula One World Championship could return to Indian soil after a 13-year gap as policy issues are addressed.
MNI_BENG: জিদের.ᱹ, বিলা.া.লি.্র.ী.h.e. in.
--------------------------------------------------

Translating:  10%|██▋                         | 95/1000 [01:50<18:41,  1.24s/it]

[95/1000]
EN: Nikhat Zareen won 5–0 over Guo Yi Xuan in a bout described as a commanding victory.
MNI_BENG: . জিদের্রী বিলিলারামিন্দর 5.h0, я. in.at.e. b. दक्षिण प्रदेश 11 : 00. विळैयाट्टु.
--------------------------------------------------

Translating:  10%|██▋                         | 96/1000 [01:52<19:59,  1.33s/it]

[96/1000]
EN: Minakshi Hooda and Jaismine Lamboria upset Paris Olympics medallists and top seeds in a major boxing event.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারুরিশি्लॆ দি কিসি तिकिल् রেনরचर क्कूट 49:च्चि.
--------------------------------------------------

Translating:  10%|██▋                         | 97/1000 [01:53<17:20,  1.15s/it]

[97/1000]
EN: Vinesh Phogat announced a return to wrestling on December 12, 2025.
MNI_BENG: জিদের., বি.া.লা.ী.
--------------------------------------------------

Translating:  10%|██▋                         | 98/1000 [01:54<17:26,  1.16s/it]

[98/1000]
EN: Village spectators watching a kabaddi match organised at a makeshift arena.
MNI_BENG: জিদের বির্লিলারান্দরী निश्चित, মি কিসরিावन বারचर দিশি्लॆ я.h.
--------------------------------------------------

Translating:  10%|██▊                         | 99/1000 [01:55<17:48,  1.19s/it]

[99/1000]
EN: The 21st Tata Mumbai Marathon took place with large-scale participation in Mumbai.
MNI_BENG: জিদের 21 বির্রীালি : লারেমিন্দ দিসর 11 বারি কিশিat, क्कूट चाफम ।
--------------------------------------------------

Translating:  10%|██▋                        | 100/1000 [01:57<19:15,  1.28s/it]

[100/1000]
EN: The first-ever Formula 4 car show on Marina Beach was held on the banks of the sea in Chennai.
MNI_BENG: জিদের 4 বির্রী ালারিলিমিন্দর 5 বারুরचर चा ята.
--------------------------------------------------

Translating:  10%|██▋                        | 101/1000 [01:58<19:04,  1.27s/it]

[101/1000]
EN: Tilak Varma said India felt ready for the high-stakes Pakistan match in Colombo.
MNI_BENG: জিদের বির্রালি - লারী মিন্দ चा দিসরি কিুরেশি, ān.िल्.h.
--------------------------------------------------

Translating:  10%|██▊                        | 102/1000 [01:59<18:03,  1.21s/it]

[102/1000]
EN: Tilak Varma said the India squad had entered a focused “match zone” mindset.
MNI_BENG: জিদের বির্লিলারামিী..ᱹ = দি.at.
--------------------------------------------------

Translating:  10%|██▊                        | 103/1000 [02:00<18:08,  1.21s/it]

[103/1000]
EN: Tilak Varma described the India–Pakistan fixture as a major highlight of the tournament.
MNI_BENG: জিদের বির্লিলারামিন্দী, দরি কিশিসিন ān चा я.h.
--------------------------------------------------

Translating:  10%|██▊                        | 104/1000 [02:01<17:52,  1.20s/it]

[104/1000]
EN: Tilak Varma emphasized preparation and intensity for India ahead of the Pakistan clash.
MNI_BENG: জিদের বির্লিলারামিন্দী, দরি কিশিসি b दक्षिणाय़ я.h.
--------------------------------------------------

Translating:  10%|██▊                        | 105/1000 [02:02<17:00,  1.14s/it]

[105/1000]
EN: Tilak Varma framed the Pakistan game as a test of temperament and execution.
MNI_BENG: জিদের বির্লিলারামিন্দ चा রী দরি কি तिक bā.h. in.
--------------------------------------------------

Translating:  11%|██▊                        | 106/1000 [02:03<17:16,  1.16s/it]

[106/1000]
EN: Delhi Metro extended operating hours to support fans travelling for the India–Namibia match.
MNI_BENG: জিদের বির্লিলারামিন্দী ᱟᱢ দরিসি কিावनाय़ বারুরেশি, я. 1954.
--------------------------------------------------

Translating:  11%|██▉                        | 107/1000 [02:04<16:11,  1.09s/it]

[107/1000]
EN: Delhi Metro added services to manage crowd flow before and after the India–Namibia game.
MNI_BENG: জিদের বির্লিলারামিন্দী.a.h.m.at.
--------------------------------------------------

Translating:  11%|██▉                        | 108/1000 [02:05<15:48,  1.06s/it]

[108/1000]
EN: City transport officials coordinated services to reduce congestion around the India–Namibia fixture.
MNI_BENG: জিদের বির্রালালিমিন্দী..ᱹ चा я.h.m.
--------------------------------------------------

Translating:  11%|██▉                        | 109/1000 [02:07<16:31,  1.11s/it]

[109/1000]
EN: Extended metro services aimed to make stadium travel easier for cricket spectators in Delhi.
MNI_BENG: জিদের বির্লিলারামিী, দরিন্দ चा বারেসি কিশিावन क्कूट 49.
--------------------------------------------------

Translating:  11%|██▉                        | 110/1000 [02:08<15:38,  1.05s/it]

[110/1000]
EN: Additional trains were planned to handle the match-day rush for the India–Namibia crowd.
MNI_BENG: জিদের বির্লিলারামি - দরী āst, я.h..
--------------------------------------------------

Translating:  11%|██▉                        | 111/1000 [02:09<17:35,  1.19s/it]

[111/1000]
EN: Rohit Sharma warned India that confidence alone would not win against Pakistan.
MNI_BENG: জিদের বির্লিলারামিন্দরী ৱিশি কিावनরিসরর dat, বারে्लॆ ятали দিक्कूट  बुधबार ।
--------------------------------------------------

Translating:  11%|███                        | 112/1000 [02:10<18:33,  1.25s/it]

[112/1000]
EN: Rohit Sharma urged India to approach Pakistan with discipline, planning, and composure.
MNI_BENG: জিদের বির্লিলারান্দরী, মি করিসররেশি bāsth বারুরचरᱶ নর चा ята.
--------------------------------------------------

Translating:  11%|███                        | 113/1000 [02:12<18:54,  1.28s/it]

[113/1000]
EN: Rohit Sharma cautioned that India–Pakistan games can ignore rankings and recent form.
MNI_BENG: জিদের বির্লিলারামিী, দরেন্দ चा বারি কিশিসর dat b दक्षिणाय़  बुधबार ।
--------------------------------------------------

Translating:  11%|███                        | 114/1000 [02:13<18:29,  1.25s/it]

[114/1000]
EN: Rohit Sharma stressed mental readiness for India before the Pakistan contest.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিসিশি, বারেুরचर चा ाय़ ।
--------------------------------------------------

Translating:  12%|███                        | 115/1000 [02:14<19:07,  1.30s/it]

[115/1000]
EN: Rohit Sharma advised India to avoid underestimating Pakistan in the World Cup clash.
MNI_BENG: জিদের বির্লিলারান্দরী ᱟᱢ, মিশি কিসরিावन দিনররে्लॆ বার चा ята.
--------------------------------------------------

Translating:  12%|███▏                       | 116/1000 [02:16<19:34,  1.33s/it]

[116/1000]
EN: Virat Kohli congratulated India’s Under-19 team after the World Cup final victory.
MNI_BENG: জিদের -, বির্রালিমিী লারেন্দর चा রি কিসিন দিশিावन ān я.h.e.
--------------------------------------------------

Translating:  12%|███▏                       | 117/1000 [02:17<20:22,  1.38s/it]

[117/1000]
EN: India’s Under-19 team won the ICC Under-19 Cricket World Cup final by 100 runs against England.
MNI_BENG: দেরিজিব্র 1- লারালিমির 100 দরীच्च चा বারেস - 19 ятамол, ন্দি কিশিat 0. in.
--------------------------------------------------

Translating:  12%|███▏                       | 118/1000 [02:19<21:10,  1.44s/it]

[118/1000]
EN: India secured a sixth Under-19 World Cup title with a commanding final performance.
MNI_BENG: জিদের - বির্লিলাামিন্দী দরিावन বারেস яте,  কিশিতি किराम चा ्रॆब ।
--------------------------------------------------

Translating:  12%|███▏                       | 119/1000 [02:20<18:51,  1.28s/it]

[119/1000]
EN: Celebrations followed India’s Under-19 World Cup triumph over England in the title match.
MNI_BENG: জিদের -, বির্রালিমিলার 1.hᱹ ী.
--------------------------------------------------

Translating:  12%|███▏                       | 120/1000 [02:21<16:44,  1.14s/it]

[120/1000]
EN: India’s Under-19 success drew praise from senior players across Indian cricket.
MNI_BENG: জিরেদ.া.ী., বি.at.
--------------------------------------------------

Translating:  12%|███▎                       | 121/1000 [02:22<18:15,  1.25s/it]

[121/1000]
EN: Dhakshineswar Suresh sparked optimism by delivering a breakthrough stretch for Indian tennis.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী রিুরचर ятал, বারেস  কিশিावन āsth्लॆ ।
--------------------------------------------------

Translating:  12%|███▎                       | 122/1000 [02:24<19:18,  1.32s/it]

[122/1000]
EN: Dhakshineswar Suresh’s rise has renewed ambition among Indian tennis fans and young players.
MNI_BENG: জিদের বিলার্রালিমিন্দরী দিরি কি तिकआ বারেশিच्चि ৱিসর dat, ята?
--------------------------------------------------

Translating:  12%|███▎                       | 123/1000 [02:25<18:58,  1.30s/it]

[123/1000]
EN: Dhakshineswar Suresh’s recent results were described as a turning point for Indian tennis.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারুরি কি्लॆ দিশিat я.h.िल्.
--------------------------------------------------

Translating:  12%|███▎                       | 124/1000 [02:26<19:36,  1.34s/it]

[124/1000]
EN: Dhakshineswar Suresh’s performances lifted expectations for Indian tennis on bigger stages.
MNI_BENG: জিদের বির্লিলারান্দরী ᱟᱢ, মি्लॆ দি কিুরিশিावन বার चा রেসর dat.
--------------------------------------------------

Translating:  12%|███▍                       | 125/1000 [02:28<20:07,  1.38s/it]

[125/1000]
EN: Dhakshineswar Suresh’s run created fresh belief about India’s potential in men’s tennis.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिकआ বারেস রুর चा ята ),  কি्लॆ শিতিावन at.h.
--------------------------------------------------

Translating:  13%|███▍                       | 126/1000 [02:29<19:45,  1.36s/it]

[126/1000]
EN: India’s men’s team exited in the quarterfinals at the Badminton Asia Team Championships.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেসি কি्लॆ বার सिंगिल् я.hant.at. in.
--------------------------------------------------

Translating:  13%|███▍                       | 127/1000 [02:30<19:30,  1.34s/it]

[127/1000]
EN: India’s women’s team exited in the quarterfinals at the Badminton Asia Team Championships.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, বারুরেস দরचर я.h.at.e. in.
--------------------------------------------------

Translating:  13%|███▍                       | 128/1000 [02:32<19:30,  1.34s/it]

[128/1000]
EN: India failed to defend titles after a double quarterfinal exit in the team championships.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী निश्चित, বারিসি কিশিावन ān तिकिल् ाय़ ।
--------------------------------------------------

Translating:  13%|███▍                       | 129/1000 [02:33<19:19,  1.33s/it]

[129/1000]
EN: Strong opposition ended India’s campaign early at the Badminton Asia Team Championships.
MNI_BENG: জিদের বির্লিলারাী चा মি्लॆ দরিন্দचर বারেশি কিসি तिकिल् ята.
--------------------------------------------------

Translating:  13%|███▌                       | 130/1000 [02:34<19:02,  1.31s/it]

[130/1000]
EN: The quarterfinal losses ended India’s hopes of a title defence at the event.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দী, বারি কিুরেশিসি दक्षिण ओइबाh श्री @ 0. in.
--------------------------------------------------

Translating:  13%|███▌                       | 131/1000 [02:35<18:26,  1.27s/it]

[131/1000]
EN: Sumit Nagal was scheduled to open his tournament campaign against Guy Den Ouden.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দat, বারেসি কিশিন ята.
--------------------------------------------------

Translating:  13%|███▌                       | 132/1000 [02:37<18:01,  1.25s/it]

[132/1000]
EN: Sumit Nagal drew Dutch player Guy Den Ouden in an opening-round matchup.
MNI_BENG: জিদের বির্রালিমিী লারিন্দি দরেস  तिकाय़, я.h.e..
--------------------------------------------------

Translating:  13%|███▌                       | 133/1000 [02:38<16:52,  1.17s/it]

[133/1000]
EN: Sumit Nagal’s first-round pairing set up an early test against Guy Den Ouden.
MNI_BENG: জিদের বির্লিলারামিী.., দি.at.a.h.
--------------------------------------------------

Translating:  13%|███▌                       | 134/1000 [02:39<17:07,  1.19s/it]

[134/1000]
EN: Sumit Nagal prepared for a fresh challenge against Guy Den Ouden in round one.
MNI_BENG: জিদের বির্লিলারামিন্দী, দরি কিুরেশিᱶ বারचर चा я.h.
--------------------------------------------------

Translating:  14%|███▋                       | 135/1000 [02:40<17:11,  1.19s/it]

[135/1000]
EN: Sumit Nagal began a new event with an opening match against Guy Den Ouden.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দat, বারেসি কিশিন āst?
--------------------------------------------------

Translating:  14%|███▋                       | 136/1000 [02:41<16:17,  1.13s/it]

[136/1000]
EN: An analysis said T20 cricket keeps evolving through new strategies and fast-changing trends.
MNI_BENG: জিদেরী..ব্রালিমিলা तिकिल्, я.h.at.e. in.
--------------------------------------------------

Translating:  14%|███▋                       | 137/1000 [02:42<16:52,  1.17s/it]

[137/1000]
EN: A feature noted the ICC Men's T20 World Cup returned to India after a decade-long gap.
MNI_BENG: জিদের , বির্রালিী লারিমিন্দর चा দি तिकिल् я.. b.h. in.at.a.
--------------------------------------------------

Translating:  14%|███▋                       | 138/1000 [02:44<17:15,  1.20s/it]

[138/1000]
EN: T20 cricket was described as a format that continually reinvents tactics and team plans.
MNI_BENG: জিদের , বির্রালিমিী লারিন্দ चा বারেসি কিশি दक्षिण b?
--------------------------------------------------

Translating:  14%|███▊                       | 139/1000 [02:44<15:52,  1.11s/it]

[139/1000]
EN: A commentary highlighted how technology and data shape modern T20 decision-making.
MNI_BENG: জিদের বির্লিলারী., ামি.
--------------------------------------------------

Translating:  14%|███▊                       | 140/1000 [02:45<14:56,  1.04s/it]

[140/1000]
EN: A tournament preview underlined T20 cricket’s cultural impact and mass appeal in India.
MNI_BENG: জিদের., বিলা.ী.া.h.্র. in.ম.
--------------------------------------------------

Translating:  14%|███▊                       | 141/1000 [02:47<15:44,  1.10s/it]

[141/1000]
EN: Kapil Dev was listed among participants at the PM Rungta Memorial Golf Cup in Jaipur.
MNI_BENG: জিদের বির্লিলারামিন্দরী निश्चित रूप বারুরি কি्लॆ  तिकाय़.h.e.m.a.
--------------------------------------------------

Translating:  14%|███▊                       | 142/1000 [02:48<16:25,  1.15s/it]

[142/1000]
EN: Madan Lal was listed among participants at the PM Rungta Memorial Golf Cup in Jaipur.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ, বারুরি কিশি्लॆ দিসরেন я.िल्.h.
--------------------------------------------------

Translating:  14%|███▊                       | 143/1000 [02:49<15:21,  1.08s/it]

[143/1000]
EN: The PM Rungta Memorial Golf Cup was scheduled for February 8, 2026 in Jaipur.
MNI_BENG: জিদের  0. 2026বালার্লি ।
--------------------------------------------------

Translating:  14%|███▉                       | 144/1000 [02:50<17:18,  1.21s/it]

[144/1000]
EN: Rambagh Golf Club was named as the venue for the memorial golf tournament.
MNI_BENG: জিদেরী বির্রালিন্দিলারমি কিসরিশিat, ятал्लॆ বারেুররचर ā 49  तिकाय़ ।
--------------------------------------------------

Translating:  14%|███▉                       | 145/1000 [02:52<17:20,  1.22s/it]

[145/1000]
EN: Organisers said the golf cup used a Stableford Single Peoria format for inclusive competition.
MNI_BENG: জিদের বির্লিলারামিী, দরিন্দিশি কিসরু b दक्षिण चा я.h..
--------------------------------------------------

Translating:  15%|███▉                       | 146/1000 [02:52<15:52,  1.11s/it]

[146/1000]
EN: A schedule note said United States would face Netherlands in Chennai to close February 13’s action.
MNI_BENG: জিদেরী  13..া.বি.্র.
--------------------------------------------------

Translating:  15%|███▉                       | 147/1000 [02:54<16:30,  1.16s/it]

[147/1000]
EN: The USA–Netherlands match was presented as important for points and pride in the group.
MNI_BENG: জিদের বির্লিলারামিন্দরী বারুরিসি কিনরে्लॆ দিশি., я.िल्.
--------------------------------------------------

Translating:  15%|███▉                       | 148/1000 [02:55<17:08,  1.21s/it]

[148/1000]
EN: A match preview framed USA against Netherlands as a tight contest between associate nations.
MNI_BENG: জিদেরী বির্রালিমিলার দরিন্দ चा বারে्लॆ সিশিावन  কিুরat ята ) ।
--------------------------------------------------

Translating:  15%|████                       | 149/1000 [02:56<18:24,  1.30s/it]

[149/1000]
EN: A schedule roundup highlighted February 13 fixtures as key for shaping group standings.
MNI_BENG: জিদের  13 বির্লিলারামিন্দরী দি কিসরিশিat, বারেুর 11 āst चाफम.
--------------------------------------------------

Translating:  15%|████                       | 150/1000 [02:58<17:19,  1.22s/it]

[150/1000]
EN: A preview said the final February 13 match would be played at MA Chidambaram Stadium.
MNI_BENG: জিদের 13 বির্রী লারালিমিন্দ.. ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  15%|████                       | 151/1000 [02:59<17:39,  1.25s/it]

[151/1000]
EN: Indian Super League clubs requested a pause on relegation for three to five years.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কি्लॆ, বারুরেসর dat दक्षिण ओइबाh я 1954 ।
--------------------------------------------------

Translating:  15%|████                       | 152/1000 [03:00<16:53,  1.19s/it]

[152/1000]
EN: ISL clubs argued that pausing relegation would provide stability for long-term planning.
MNI_BENG: জিদের বির্লিলারান্দরী দিমি কি तिक b, я.h.शय़. किराम.
--------------------------------------------------

Translating:  15%|████▏                      | 153/1000 [03:01<18:06,  1.28s/it]

[153/1000]
EN: Several ISL teams asked administrators to consider a temporary relegation freeze.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দ चा দররেসি কি तिक bā 1954 ।
--------------------------------------------------

Translating:  15%|████▏                      | 154/1000 [03:03<17:45,  1.26s/it]

[154/1000]
EN: The request on relegation was framed as a measure to protect club investments.
MNI_BENG: জিদেরী বির্রালিমিন্দ चा লারি কিশি, বারেসিন я.
--------------------------------------------------

Translating:  16%|████▏                      | 155/1000 [03:04<18:25,  1.31s/it]

[155/1000]
EN: ISL stakeholders debated relegation rules while seeking clarity for the 2025–26 season.
MNI_BENG: জিদের  2025.E26ব্রলিমিালারী দিরিন্দ चा সি কিুরেশিতি ꯕ, ята.
--------------------------------------------------

Translating:  16%|████▏                      | 156/1000 [03:05<16:18,  1.16s/it]

[156/1000]
EN: India produced a 3–2 win over Netherlands in Davis Cup Qualifiers Round 1.
MNI_BENG: জিরেদ.া., বি.্র.ী. 1.
--------------------------------------------------

Translating:  16%|████▏                      | 157/1000 [03:06<14:48,  1.05s/it]

[157/1000]
EN: India advanced to the second Davis Cup qualifying round after beating Netherlands 3–2.
MNI_BENG: জিদের  3..h.a.বি.ী.া.
--------------------------------------------------

Translating:  16%|████▎                      | 158/1000 [03:07<15:42,  1.12s/it]

[158/1000]
EN: India’s Davis Cup team was described as thriving against higher-ranked opponents recently.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिक b दक्षिणाय़ ята ) ।
--------------------------------------------------

Translating:  16%|████▎                      | 159/1000 [03:08<16:25,  1.17s/it]

[159/1000]
EN: The Davis Cup tie at SM Krishna Tennis Stadium went down to the wire.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দat, বারুরেস я.
--------------------------------------------------

Translating:  16%|████▎                      | 160/1000 [03:09<16:16,  1.16s/it]

[160/1000]
EN: India’s Davis Cup success followed an earlier victory over Switzerland in Biel last year.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দি्लॆ..ᱹिल् ৱি.at.a.
--------------------------------------------------

Translating:  16%|████▎                      | 161/1000 [03:10<15:17,  1.09s/it]

[161/1000]
EN: The India Open was kept as a Super 750 tournament for the 2027–2030 cycle.
MNI_BENG: জিদের  2027/2030 বিলার্রালি ।
--------------------------------------------------

Translating:  16%|████▎                      | 162/1000 [03:11<14:48,  1.06s/it]

[162/1000]
EN: Players criticised conditions, yet organisers retained the India Open’s Super 750 status.
MNI_BENG: জিদের বির্লিলারী.-, я.া.h. in.
--------------------------------------------------

Translating:  16%|████▍                      | 163/1000 [03:13<16:52,  1.21s/it]

[163/1000]
EN: Badminton World Federation announced a revamped World Tour structure with six tournament levels.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিশি কিসররে्लॆ, ятамон एंज বারचर āst 49:00 ।
--------------------------------------------------

Translating:  16%|████▍                      | 164/1000 [03:14<15:22,  1.10s/it]

[164/1000]
EN: The BWF updated World Tour plan included 36 tournaments across multiple tiers.
MNI_BENG: জিদের  b..া.ী.h., বি.লা.at.্র.
--------------------------------------------------

Translating:  16%|████▍                      | 165/1000 [03:15<17:36,  1.26s/it]

[165/1000]
EN: The BWF said annual World Tour prize money would rise to about 26.9 million dollars.
MNI_BENG: .ᱹ জিদের্রাবিলিলারী b মিন্দ चा বারিরেস দরचर яте 49.
--------------------------------------------------

Translating:  17%|████▍                      | 166/1000 [03:16<16:41,  1.20s/it]

[166/1000]
EN: A schedule preview listed Sri Lanka against Oman as a February 12 group-stage fixture.
MNI_BENG: জিদের.ᱹ বিলা.্র.া.ী.h., লি.at.ম.
--------------------------------------------------

Translating:  17%|████▌                      | 167/1000 [03:17<16:02,  1.16s/it]

[167/1000]
EN: A schedule preview listed Nepal against Italy as a February 12 group-stage fixture.
MNI_BENG: জিদেরী.ᱹ বিলা.া.্র.h.at.e.ল., ম.
--------------------------------------------------

Translating:  17%|████▌                      | 168/1000 [03:19<15:40,  1.13s/it]

[168/1000]
EN: A schedule preview listed India against Namibia as a February 12 group-stage fixture.
MNI_BENG: জিদের.ᱹ বিলা.ী.া.্র.h.at.re.লি.
--------------------------------------------------

Translating:  17%|████▌                      | 169/1000 [03:20<16:03,  1.16s/it]

[169/1000]
EN: Wanindu Hasaranga was ruled out of the World Cup due to an injury setback.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিশি কি्लॆ, я.
--------------------------------------------------

Translating:  17%|████▌                      | 170/1000 [03:21<16:42,  1.21s/it]

[170/1000]
EN: Sri Lanka named Dushan Hemantha as a replacement after Wanindu Hasaranga’s injury.
MNI_BENG: জিদের বির্রালিমিলারী, বারিন্দিস দ चा রেশি কেুরat ाय़ ।
--------------------------------------------------

Translating:  17%|████▌                      | 171/1000 [03:22<14:28,  1.05s/it]

[171/1000]
EN: The Indian Super League season was announced to begin on February 14, 2026.
MNI_BENG: জিদের 14. 2026 বির্লি ।
--------------------------------------------------

Translating:  17%|████▋                      | 172/1000 [03:23<15:37,  1.13s/it]

[172/1000]
EN: Sports minister Mansukh Mandaviya announced an ISL start date of February 14.
MNI_BENG: জিদের , বির্রালিী লারিমিন্দর বারে्लॆ দি কিশিসর 49  तिकिल् ।
--------------------------------------------------

Translating:  17%|████▋                      | 173/1000 [03:24<16:26,  1.19s/it]

[173/1000]
EN: All 14 clubs agreed to participate in the Indian Super League season, according to reports.
MNI_BENG: জিদর 14 বের্রীালিমিলার 11 বারির 49, দেন্দ चा সিুরেশিat я.
--------------------------------------------------

Translating:  17%|████▋                      | 174/1000 [03:26<16:50,  1.22s/it]

[174/1000]
EN: The ISL decision followed meetings between the sports ministry and the All India Football Federation.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী निश्चित रूप से বারিসি কিশিच्चि ৱিat bān.hant.
--------------------------------------------------

Translating:  18%|████▋                      | 175/1000 [03:27<18:00,  1.31s/it]

[175/1000]
EN: Indian football’s top-tier season moved forward after clubs accepted the participation plan.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ দুরিন - ята, বার चा রেশি्लॆ সি কিावनारा  तिक bā.h.िल्.
--------------------------------------------------

Translating:  18%|████▊                      | 176/1000 [03:28<16:28,  1.20s/it]

[176/1000]
EN: India’s women lost 0–3 to China in the Badminton Asia Team Championships quarterfinals.
MNI_BENG: জিদের.h.e.া.a.বি.ী.্র., লা.
--------------------------------------------------

Translating:  18%|████▊                      | 177/1000 [03:29<15:18,  1.12s/it]

[177/1000]
EN: P. V. Sindhu missed the team quarterfinal because of a minor injury, according to reports.
MNI_BENG: জিদের বির্রী.. লিলা.া., দি.
--------------------------------------------------

Translating:  18%|████▊                      | 178/1000 [03:30<14:01,  1.02s/it]

[178/1000]
EN: India’s women struggled to defend the 2024 title without PV Sindhu in the lineup.
MNI_BENG: জিরেদ..ব্রালি, ী.লা.
--------------------------------------------------

Translating:  18%|████▊                      | 179/1000 [03:31<15:35,  1.14s/it]

[179/1000]
EN: China ended India’s women’s title defence with a straight 3–0 quarterfinal win.
MNI_BENG: জিদের  0.ᱹ বির্রালিমিলারী দিন্দ चा বারি কি तिकआ সরেশিावन  3.h.e.
--------------------------------------------------

Translating:  18%|████▊                      | 180/1000 [03:33<16:11,  1.19s/it]

[180/1000]
EN: The quarterfinal defeat closed India’s women’s campaign at the Badminton Asia Team Championships.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিসি কি्लॆ বারুরেশি, я.वा.िल्.h.at.
--------------------------------------------------

Translating:  18%|████▉                      | 181/1000 [03:33<15:00,  1.10s/it]

[181/1000]
EN: Devika Sihag won the Thailand Masters 2026 to claim a BWF Super 300 title.
MNI_BENG: জিদের  2026 বির্লিলারী b WE..
--------------------------------------------------

Translating:  18%|████▉                      | 182/1000 [03:34<14:09,  1.04s/it]

[182/1000]
EN: Devika Sihag became the youngest Indian woman to win a BWF Super 300 singles title.
MNI_BENG: জিদের., বিলা.া.ী.্র.লি.
--------------------------------------------------

Translating:  18%|████▉                      | 183/1000 [03:36<15:32,  1.14s/it]

[183/1000]
EN: Devika Sihag joined Saina Nehwal and PV Sindhu in an exclusive Indian milestone list.
MNI_BENG: জিদেরী বির্রালিন্দিলা মি तिक b्लॆ ānh, я.
--------------------------------------------------

Translating:  18%|████▉                      | 184/1000 [03:37<16:18,  1.20s/it]

[184/1000]
EN: Devika Sihag’s Bangkok celebration marked a breakthrough moment for Indian women’s singles.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কি्लॆ, বারেসর dat दक्षिण ята.
--------------------------------------------------

Translating:  18%|████▉                      | 185/1000 [03:38<16:08,  1.19s/it]

[185/1000]
EN: Devika Sihag’s title was described as a quiet announcement of a new Indian badminton star.
MNI_BENG: জিদের বির্লিলারামিন্দী, দরি কিশিসিন ān 1954-at. 49. विळैयाट्टु.
--------------------------------------------------

Translating:  19%|█████                      | 186/1000 [03:39<14:39,  1.08s/it]

[186/1000]
EN: A matchday note listed Afghanistan against South Africa in Ahmedabad on February 11.
MNI_BENG: জিদের.ᱹ বিলা.ী.া.h., লি.
--------------------------------------------------

Translating:  19%|█████                      | 187/1000 [03:40<15:42,  1.16s/it]

[187/1000]
EN: A matchday note listed Australia against Ireland as another February 11 group-stage fixture.
MNI_BENG: জিদের 11 বির্রী লিমিলারা चा , রিন্দি দর सिंग বারেুর 1..mᱹ я.
--------------------------------------------------

Translating:  19%|█████                      | 188/1000 [03:42<16:15,  1.20s/it]

[188/1000]
EN: A matchday note listed England against West Indies as a February 11 evening fixture.
MNI_BENG: জিদের  11 বির্লিলারী ামিন্দ चा দি কিুরি्लॆ বারেসর 1.
--------------------------------------------------

Translating:  19%|█████                      | 189/1000 [03:43<16:57,  1.25s/it]

[189/1000]
EN: Afghanistan sought a rebound after losing their opener against New Zealand, according to reports.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিসর রে्लॆ ाय़, ятали  बुधबार ।
--------------------------------------------------

Translating:  19%|█████▏                     | 190/1000 [03:45<18:40,  1.38s/it]

[190/1000]
EN: The February 11 schedule mixed former champions, contenders, and dangerous underdogs in group play.
MNI_BENG: জিরেদ 11 বিলিলাা দ্রী মিন্দের বারুরি्लॆ ята ), র चा সিশি কিদর 1 9 ाय़ : 0. in.
--------------------------------------------------

Translating:  19%|█████▏                     | 191/1000 [03:46<18:10,  1.35s/it]

[191/1000]
EN: Baichung Bhutia blamed administration after Churchill Brothers were not added to ISL 2025–26.
MNI_BENG: .ᱹ জিদের্রী বিলিমিলারান্দরু, ाय़ 2025/26 ятам.
--------------------------------------------------

Translating:  19%|█████▏                     | 192/1000 [03:48<19:09,  1.42s/it]

[192/1000]
EN: Churchill Brothers were not included in ISL 2025–26, prompting criticism from Baichung Bhutia.
MNI_BENG: জিদের  2025/26 বির্রালিমিলারীя বারিন্দি কিুরেশিat ৱিতিসর चा ाय़.
--------------------------------------------------

Translating:  19%|█████▏                     | 193/1000 [03:49<18:35,  1.38s/it]

[193/1000]
EN: Baichung Bhutia called the Churchill Brothers exclusion a clear administrative failure.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারুরিসর चा দিশি কিনরचर я.
--------------------------------------------------

Translating:  19%|█████▏                     | 194/1000 [03:50<18:23,  1.37s/it]

[194/1000]
EN: The Churchill Brothers decision raised questions about the league’s selection and governance.
MNI_BENG: জিদের বির্লিলারান্দরী निश्चित, মিশি কিসরিন দিक्कूट 49:च्चि.
--------------------------------------------------

Translating:  20%|█████▎                     | 195/1000 [03:52<18:31,  1.38s/it]

[195/1000]
EN: The ISL debate intensified after the Churchill Brothers issue surfaced in public comments.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিশি কিুরেসat, ятал्लॆ বার चा āsthाय़?
--------------------------------------------------

Translating:  20%|█████▎                     | 196/1000 [03:53<18:09,  1.35s/it]

[196/1000]
EN: India–Netherlands Davis Cup tie tightened after Sumit Nagal suffered a setback.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কি्लॆ, বার चा রেস ānat ाय़?
--------------------------------------------------

Translating:  20%|█████▎                     | 197/1000 [03:54<16:34,  1.24s/it]

[197/1000]
EN: Sumit Nagal’s result added pressure as the Davis Cup tie moved toward a tense finish.
MNI_BENG: জিদের বির্লিলারামিী.. ᱪᱟᱞᱟᱣᱚᱜ, я.h.
--------------------------------------------------

Translating:  20%|█████▎                     | 198/1000 [03:55<15:47,  1.18s/it]

[198/1000]
EN: India and Netherlands remained locked in a close Davis Cup contest after the Nagal match.
MNI_BENG: জিদের বির্লিলারামিন্দরী.h..ᱹ वधवा, я.िल्.
--------------------------------------------------

Translating:  20%|█████▎                     | 199/1000 [03:56<16:09,  1.21s/it]

[199/1000]
EN: The Davis Cup tie needed late composure after the Sumit Nagal setback, according to reports.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী निश्चित, বারিসি কিশিावन.. ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  20%|█████▍                     | 200/1000 [03:57<16:04,  1.21s/it]

[200/1000]
EN: The Bengaluru Davis Cup atmosphere stayed intense as India fought Netherlands in a tight tie.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिक bāst, বারে्लॆ ाय़ चा  बुधबार ।
--------------------------------------------------

Translating:  20%|█████▍                     | 201/1000 [03:59<16:39,  1.25s/it]

[201/1000]
EN: International Cricket Council confirmed the 2026 Men’s T20 World Cup starts on February 7.
MNI_BENG: ., দেরিজিবিলা াল্রী я 2026 ন্দিমি কিরেদর 7ᱹ বারুরचर चा ाय़ ।
--------------------------------------------------

Translating:  20%|█████▍                     | 202/1000 [04:00<16:06,  1.21s/it]

[202/1000]
EN: India were placed in Group A alongside Pakistan, Netherlands, USA, and Namibia.
MNI_BENG: জিদের বির্রালিী লারিন্দ মিস দি কি्लॆ я., বা.at.h.
--------------------------------------------------

Translating:  20%|█████▍                     | 203/1000 [04:01<16:21,  1.23s/it]

[203/1000]
EN: Sri Lanka hosted several matches as the tournament ran across India and Sri Lanka venues.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী निश्चित, বারিসি কিশিावन নিুরে्लॆ ाय़?
--------------------------------------------------

Translating:  20%|█████▌                     | 204/1000 [04:02<16:09,  1.22s/it]

[204/1000]
EN: India played the opening match against the USA at Wankhede Stadium in Mumbai.
MNI_BENG: জিদের বির্রালালি, মিন্দরী দিসি কিুরিশিতিावन я.h. in.
--------------------------------------------------

Translating:  20%|█████▌                     | 205/1000 [04:04<16:30,  1.25s/it]

[205/1000]
EN: India faced Namibia on February 12 at Arun Jaitley Stadium in New Delhi.
MNI_BENG: জিদের , বির্রালিী লারিমিন্দ দিসিশিat ৱি কেদর 12 বারचर चाफम ।
--------------------------------------------------

Translating:  21%|█████▌                     | 206/1000 [04:05<16:34,  1.25s/it]

[206/1000]
EN: India travelled to Colombo to play Pakistan in a group-stage match.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দ चा я 1954 ।
--------------------------------------------------

Translating:  21%|█████▌                     | 207/1000 [04:06<16:26,  1.24s/it]

[207/1000]
EN: Pakistan versus Netherlands was listed as a Group A fixture on February 7.
MNI_BENG: জিদের , বির্রী লিমিলারা चा বারিন্দি.
--------------------------------------------------

Translating:  21%|█████▌                     | 208/1000 [04:07<16:31,  1.25s/it]

[208/1000]
EN: India versus USA was scheduled as a Group A match on February 7.
MNI_BENG: জিদের , বির্রালিী লারিমিন্দর चा я.
--------------------------------------------------

Translating:  21%|█████▋                     | 209/1000 [04:09<17:08,  1.30s/it]

[209/1000]
EN: Group D fixtures began with Afghanistan playing New Zealand on February 8 in Chennai.
MNI_BENG: জিদের , বির্রালিী লারিমিন্দর দি কিুর चा বারেশিावन ्रॆ ।
--------------------------------------------------

Translating:  21%|█████▋                     | 210/1000 [04:10<17:28,  1.33s/it]

[210/1000]
EN: Canada played South Africa on February 9 at Narendra Modi Stadium in Ahmedabad.
MNI_BENG: জিদেরী , বির্রালিমিন্দিলা বারেস দরি কেদ चा র सिंगिल् ята?
--------------------------------------------------

Translating:  21%|█████▋                     | 211/1000 [04:11<15:51,  1.21s/it]

[211/1000]
EN: Ishan Kishan smashed 61 off 24 balls against Namibia in New Delhi.
MNI_BENG: জিদের., বি.ী.া.h.m.্র.লা.
--------------------------------------------------

Translating:  21%|█████▋                     | 212/1000 [04:13<16:41,  1.27s/it]

[212/1000]
EN: Hardik Pandya featured prominently as India posted 209 for nine against Namibia.
MNI_BENG: জিদের  0., বির্রালিী লারিমিন্দ चा দিসি কিুরেশিच्चि ৱিावनाय़ я.h.e.
--------------------------------------------------

Translating:  21%|█████▊                     | 213/1000 [04:13<14:30,  1.11s/it]

[213/1000]
EN: Varun Chakaravarthy took three wickets as India beat Namibia by 93 runs.
MNI_BENG: জিদের.a.া.ী. বি.
--------------------------------------------------

Translating:  21%|█████▊                     | 214/1000 [04:14<14:05,  1.08s/it]

[214/1000]
EN: India bundled out Namibia for 116 while defending a target of 210.
MNI_BENG: ., জিদের্রী বিলিমিলাাच्च चा я.
--------------------------------------------------

Translating:  22%|█████▊                     | 215/1000 [04:16<15:30,  1.19s/it]

[215/1000]
EN: Namibia captain Gerhard Erasmus won the toss and chose to bat first.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দরat, দি কিুরেশিावन বারचरᱶ সর चा ята ) ।
--------------------------------------------------

Translating:  22%|█████▊                     | 216/1000 [04:17<14:21,  1.10s/it]

[216/1000]
EN: India versus Namibia started at 7:00 PM IST at Arun Jaitley Stadium.
MNI_BENG: জিদের.h.m.ᱹ বি.ী.া.্র., লা.
--------------------------------------------------

Translating:  22%|█████▊                     | 217/1000 [04:18<14:34,  1.12s/it]

[217/1000]
EN: India’s first match was a win against the USA in Mumbai.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারুরিশি কিসরেন я.
--------------------------------------------------

Translating:  22%|█████▉                     | 218/1000 [04:19<14:22,  1.10s/it]

[218/1000]
EN: India versus Namibia was labelled as game 18 of the tournament.
MNI_BENG: জিদের , বির্রালিী লারিমিন্দর 18 দি কিসরর 11.
--------------------------------------------------

Translating:  22%|█████▉                     | 219/1000 [04:20<14:50,  1.14s/it]

[219/1000]
EN: Suryakumar Yadav led India against Namibia in the ongoing T20 World Cup.
MNI_BENG: জিদেরী বির্রালিমিলা.ᱹ я.h.m.
--------------------------------------------------

Translating:  22%|█████▉                     | 220/1000 [04:22<17:07,  1.32s/it]

[220/1000]
EN: India entered the Namibia match after beating the USA in their opener.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরat, ятали.
--------------------------------------------------

Translating:  22%|█████▉                     | 221/1000 [04:23<16:17,  1.25s/it]

[221/1000]
EN: The Pakistan government allowed the Pakistan team to play India on February 15.
MNI_BENG: জিরেদ.ᱹ বিলা.ী.া.্র., লি.
--------------------------------------------------

Translating:  22%|█████▉                     | 222/1000 [04:25<17:54,  1.38s/it]

[222/1000]
EN: India versus Pakistan was scheduled for Colombo after weeks of uncertainty.
MNI_BENG: জিদের বির্লিলারামিন্দী, দররিসরেশিावन বার चा রুরat  কি तिक bā 49:00 ।
--------------------------------------------------

Translating:  22%|██████                     | 223/1000 [04:26<18:52,  1.46s/it]

[223/1000]
EN: India versus Pakistan was described as a group-stage match in Colombo.
MNI_BENG: জিদের বির্রালি - লারী মিন্দ चा বারি কি्लॆ, দরেসি दक्षिण я.
--------------------------------------------------

Translating:  22%|██████                     | 224/1000 [04:27<16:49,  1.30s/it]

[224/1000]
EN: The tournament was listed as featuring 55 matches across India and Sri Lanka.
MNI_BENG: জিদেরী.া.বি., লা.
--------------------------------------------------

Translating:  22%|██████                     | 225/1000 [04:29<18:09,  1.41s/it]

[225/1000]
EN: The schedule included Delhi, Kolkata, Ahmedabad, Chennai, Mumbai, Colombo, and Kandy venues.
MNI_BENG: জিদের বির্রালি, মিলারী দিন্দ चा বারিস.h.m.. ৱি.at. in.
--------------------------------------------------

Translating:  23%|██████                     | 226/1000 [04:30<18:19,  1.42s/it]

[226/1000]
EN: Afghanistan faced New Zealand at M. A. Chidambaram Stadium with an 11:00 AM start.
MNI_BENG: .. জিদের্রী বিলিমিলা ারিন্দর দিরचर я : 11:00 ।
--------------------------------------------------

Translating:  23%|██████▏                    | 227/1000 [04:31<16:26,  1.28s/it]

[227/1000]
EN: New Zealand played UAE on February 10 at M. A. Chidambaram Stadium.
MNI_BENG: জিদের 10. বি.া.ী.্র.
--------------------------------------------------

Translating:  23%|██████▏                    | 228/1000 [04:32<16:09,  1.26s/it]

[228/1000]
EN: Group D included UAE, New Zealand, South Africa, Afghanistan, and Canada in one pool.
MNI_BENG: জিদের বির্রালিী.h.. ᱪᱟᱞᱟᱣᱚᱜ লা.
--------------------------------------------------

Translating:  23%|██████▏                    | 229/1000 [04:34<18:29,  1.44s/it]

[229/1000]
EN: India’s group-stage route moved from Mumbai to Delhi and then Colombo.
MNI_BENG: জিদের বির্লিলারামি - দরী ята, বারেন্দ রি्लॆ  কিশিন-সিावनाय़ ā 49.hant.
--------------------------------------------------

Translating:  23%|██████▏                    | 230/1000 [04:36<20:04,  1.56s/it]

[230/1000]
EN: The India versus Namibia match preview named Gerhard Erasmus as Namibia’s captain.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দি কি्लॆ বারে तिक b दक्षिण, সে उद्देशিশিতি किराम चा āst श्री @ я.
--------------------------------------------------

Translating:  23%|██████▏                    | 231/1000 [04:38<20:27,  1.60s/it]

[231/1000]
EN: A report said Abhishek Sharma underwent checks for a stomach bug in New Delhi.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেশি, বারचर चा সি्लॆ ята ) ।
--------------------------------------------------

Translating:  23%|██████▎                    | 232/1000 [04:39<19:23,  1.52s/it]

[232/1000]
EN: The same report said Abhishek Sharma missed India’s Namibia game despite hospital discharge.
MNI_BENG: জিদের বির্রালিমিলা দী.ᱹ, я.h.at.a.
--------------------------------------------------

Translating:  23%|██████▎                    | 233/1000 [04:41<19:20,  1.51s/it]

[233/1000]
EN: Sanju Samson’s World Cup debut was described as lasting only eight deliveries.
MNI_BENG: জিদেরী বির্রালিমিলার দরিন্দ चा বারেশি কি्लॆ, я.िल्.at.
--------------------------------------------------

Translating:  23%|██████▎                    | 234/1000 [04:42<19:41,  1.54s/it]

[234/1000]
EN: The tournament’s Group A opened across venues in India and Sri Lanka.
MNI_BENG: জিদের বির্লিলারামিন্দী , দরি কিুরেশিat ৱিতিসর dā.h.
--------------------------------------------------

Translating:  24%|██████▎                    | 235/1000 [04:44<19:44,  1.55s/it]

[235/1000]
EN: India’s match against Namibia was played on Thursday, February 12.
MNI_BENG: জিদের , বির্রালিী লারিমিন্দি.
--------------------------------------------------

Translating:  24%|██████▎                    | 236/1000 [04:45<18:40,  1.47s/it]

[236/1000]
EN: Nepal versus Italy appeared as a live-score fixture during the T20 World Cup schedule.
MNI_BENG: জিদের বির্লিলারী.ᱹ.া.h.m.शय़.
--------------------------------------------------

Translating:  24%|██████▍                    | 237/1000 [04:47<19:28,  1.53s/it]

[237/1000]
EN: Australia versus Zimbabwe appeared as a live-score fixture on the Indian Express cricket feed.
MNI_BENG: জিদের বির্লিলারামি - দরী निश्चित, বারেন্দ चा রি কিসিশিন-at.h.शय़. ऎळिय.
--------------------------------------------------

Translating:  24%|██████▍                    | 238/1000 [04:49<20:53,  1.64s/it]

[238/1000]
EN: The Indian Express sports section highlighted India’s 93-run win over Namibia.
MNI_BENG: .ᱹ জিদের্রী বিলিমিলারান্দ चा দিরি কিুরেশিন я, ाय़ दक्षिण সিावन  बुधबार ।
--------------------------------------------------

Translating:  24%|██████▍                    | 239/1000 [04:50<20:17,  1.60s/it]

[239/1000]
EN: The match report said India’s bowling attack dismantled Namibia during the chase.
MNI_BENG: জিদের বির্লিলারামিন্দী, বারেসরি কিশি किराम..?
--------------------------------------------------

Translating:  24%|██████▍                    | 240/1000 [04:52<18:58,  1.50s/it]

[240/1000]
EN: The India versus Namibia highlights credited Ishan Kishan’s 61 with driving India’s total.
MNI_BENG: জিদের.ᱹ বিলা.া.h.ী.্র., লি.
--------------------------------------------------

Translating:  24%|██████▌                    | 241/1000 [04:53<17:52,  1.41s/it]

[241/1000]
EN: ISL 2025–26 fixtures began on February 14 with a double-header format.
MNI_BENG: 1954/ জিদের বির্রী 14.া..h.m.e.লা.
--------------------------------------------------

Translating:  24%|██████▌                    | 242/1000 [04:54<18:59,  1.50s/it]

[242/1000]
EN: Mohun Bagan Super Giant faced Kerala Blasters in the season opener in Kolkata.
MNI_BENG: জিদেরী বির্রালিমিলার দরিন্দিশি কিুরেসর चा বার्रॆ, āstha ята ) ।
--------------------------------------------------

Translating:  24%|██████▌                    | 243/1000 [04:56<19:12,  1.52s/it]

[243/1000]
EN: FC Goa hosted Inter Kashi at Fatorda Stadium on February 14.
MNI_BENG: জিদের , বির্রী লারালিন্দিমি কিসি तिक चा বারিশিावन ān ।
--------------------------------------------------

Translating:  24%|██████▌                    | 244/1000 [04:57<17:56,  1.42s/it]

[244/1000]
EN: The first match on double-header days started at 5:00 PM IST.
MNI_BENG: .E.. জিদের্র - বিরালিমিলার 5:00 ।
--------------------------------------------------

Translating:  24%|██████▌                    | 245/1000 [04:58<17:15,  1.37s/it]

[245/1000]
EN: The second match on double-header days started at 7:30 PM IST.
MNI_BENG: .ᱹ জিদের্র - বিরালারীলিমিন্দর : / я.वा.
--------------------------------------------------

Translating:  25%|██████▋                    | 246/1000 [05:00<17:51,  1.42s/it]

[246/1000]
EN: A report said the ISL season would use a single-leg home-and-away format.
MNI_BENG: জিদের বির্লিলাামি - দরী ята ), ন্দিশি কিসরিন-at.h.
--------------------------------------------------

Translating:  25%|██████▋                    | 247/1000 [05:01<17:56,  1.43s/it]

[247/1000]
EN: The Indian Express football page reported FanCode won exclusive ISL media rights.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिक bāst, ाय़.h.िल्.at.a.
--------------------------------------------------

Translating:  25%|██████▋                    | 248/1000 [05:03<17:27,  1.39s/it]

[248/1000]
EN: The same report said ISL per-match valuation dropped by about 95 percent.
MNI_BENG: .ᱹ জিদের্রালিবী লারিমিন্দর - я.h. in.
--------------------------------------------------

Translating:  25%|██████▋                    | 249/1000 [05:05<19:57,  1.59s/it]

[249/1000]
EN: The ISL report described a truncated season with pay cuts at multiple clubs.
MNI_BENG: জিদের বির্লিলারামিন্দরী ৱি কিুরিশি, ятал्लॆ বারেসিতিावन দিच्चि নরचर चा  ग्यासिबꯂ भाइ ।
--------------------------------------------------

Translating:  25%|██████▊                    | 250/1000 [05:06<19:10,  1.53s/it]

[250/1000]
EN: Real Madrid CF hoped a La Liga surge was boosted by a team dinner.
MNI_BENG: জিদের বির্রালারীলিমিন্দি, বারেসরিावन āla.िल्.at.
--------------------------------------------------

Translating:  25%|██████▊                    | 251/1000 [05:08<19:10,  1.54s/it]

[251/1000]
EN: The Real Madrid dinner was reportedly paid for by Vinícius Júnior and Kylian Mbappé.
MNI_BENG: জিদেরী বির্রালিমিলার দিন্দ चा বারি्लॆ.ᱹ 49.at.a.िल्.
--------------------------------------------------

Translating:  25%|██████▊                    | 252/1000 [05:09<18:53,  1.52s/it]

[252/1000]
EN: Barcelona aimed for a fourth straight league win against Girona in La Liga.
MNI_BENG: জিদের বির্রালিী লারিমিন্দ দরেস  तिकाय़, āsta ята ) ।
--------------------------------------------------

Translating:  25%|██████▊                    | 253/1000 [05:11<18:16,  1.47s/it]

[253/1000]
EN: Barcelona visited Atlético Madrid for a Copa del Rey first-leg clash.
MNI_BENG: জিদের বির্রী লিমিলা ারেন্দ দরি तिकa я.h.,.
--------------------------------------------------

Translating:  25%|██████▊                    | 254/1000 [05:12<18:09,  1.46s/it]

[254/1000]
EN: Barcelona entered the Atlético Madrid match after winning 17 of 18 matches.
MNI_BENG: জিরেদ 17 বিলিলা া্র 11 দের 18 মীর 1 ।
--------------------------------------------------

Translating:  26%|██████▉                    | 255/1000 [05:14<18:43,  1.51s/it]

[255/1000]
EN: Real Madrid and UEFA announced an agreement ending the Super League project.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ, বারেসররি কিশি्लॆ я.
--------------------------------------------------

Translating:  26%|██████▉                    | 256/1000 [05:15<19:51,  1.60s/it]

[256/1000]
EN: Barcelona formally pulled out of the Super League days before the agreement.
MNI_BENG: জিদের বির্লিলারামিন্দরী রেুরি কিশিावन বারat, দিতিসরর dाय़ ।
--------------------------------------------------

Translating:  26%|██████▉                    | 257/1000 [05:17<18:06,  1.46s/it]

[257/1000]
EN: Tottenham Hotspur reportedly sacked Thomas Frank after a 2–1 loss to Newcastle United.
MNI_BENG: জিদের.h., বি.ী.া.্র. লা.
--------------------------------------------------

Translating:  26%|██████▉                    | 258/1000 [05:18<17:10,  1.39s/it]

[258/1000]
EN: The Tottenham report said the club still had no league win in 2026.
MNI_BENG: 2026 দেরিজিব্রলিমিলাী ারেন্দর я?
--------------------------------------------------

Translating:  26%|██████▉                    | 259/1000 [05:20<18:58,  1.54s/it]

[259/1000]
EN: Wayne Rooney said Arsenal looked mentally stronger in the Premier League title race.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দি, বারুরেশিावन সি কিনররचर ята ) ।
--------------------------------------------------

Translating:  26%|███████                    | 260/1000 [05:21<17:48,  1.44s/it]

[260/1000]
EN: Rooney noted Arsenal last won the Premier League title in the 2003–04 season.
MNI_BENG: জিদের.-ᱹ বি.ী.া.h.e. in.লা.
--------------------------------------------------

Translating:  26%|███████                    | 261/1000 [05:22<16:36,  1.35s/it]

[261/1000]
EN: Rooney said Arsenal led Manchester City by six points with 13 games remaining.
MNI_BENG: জিদের.ᱹ বিলা.া., লি.ী.্র.
--------------------------------------------------

Translating:  26%|███████                    | 262/1000 [05:24<18:06,  1.47s/it]

[262/1000]
EN: Cristiano Ronaldo missed a second straight Saudi Pro League match for Al-Nassr.
MNI_BENG: জিদের বির্রালিী লারেমি দরি - я 1954 ৱিন্দি ।
--------------------------------------------------

Translating:  26%|███████                    | 263/1000 [05:25<16:46,  1.37s/it]

[263/1000]
EN: Al-Nassr beat Al-Ittihad 2–0 despite Cristiano Ronaldo’s continued absence.
MNI_BENG: জিদের.h.a.া.্র.ী., বি.
--------------------------------------------------

Translating:  26%|███████▏                   | 264/1000 [05:26<16:51,  1.37s/it]

[264/1000]
EN: Sadio Mané and Angelo Gabriel scored for Al-Nassr in the win over Al-Ittihad.
MNI_BENG: জিদের বির্রালি - লারী মিন্দ चा বারি तिक b.h.िल्.a.
--------------------------------------------------

Translating:  26%|███████▏                   | 265/1000 [05:27<14:44,  1.20s/it]

[265/1000]
EN: Sumit Nagal headlined the Delhi Open 2026 at the DLTA Complex.
MNI_BENG: জিদের.ᱹ বি.
--------------------------------------------------

Translating:  27%|███████▏                   | 266/1000 [05:28<14:04,  1.15s/it]

[266/1000]
EN: The Delhi Open 2026 tournament was scheduled for February 16 to 22.
MNI_BENG: জিদের  2026 বি 16- 22 লারী ।
--------------------------------------------------

Translating:  27%|███████▏                   | 267/1000 [05:29<14:25,  1.18s/it]

[267/1000]
EN: Britain’s Jay Clarke was named as a leading overseas entrant for Delhi Open 2026.
MNI_BENG: জিদের  2026 বির্লিলারামিন্দী я..h.e.
--------------------------------------------------

Translating:  27%|███████▏                   | 268/1000 [05:31<16:07,  1.32s/it]

[268/1000]
EN: The Delhi Open note said Sumit Nagal gained direct entry into the main draw.
MNI_BENG: জিদের বির্লিলারান্দরী ᱟᱢ, মি কিসরিावन বারে्लॆ দিশিতি तिकिल् я.h.
--------------------------------------------------

Translating:  27%|███████▎                   | 269/1000 [05:32<14:35,  1.20s/it]

[269/1000]
EN: India beat the Netherlands 3–2 in Davis Cup competition to move closer.
MNI_BENG: জিদের 3.h.া. বি.ী.লা.
--------------------------------------------------

Translating:  27%|███████▎                   | 270/1000 [05:34<17:03,  1.40s/it]

[270/1000]
EN: Dhakshineswar Suresh featured prominently during India’s Davis Cup tie against the Netherlands.
MNI_BENG: জিদের বিলার্রালি, মিরী দরিন্দিশি কিুরে्लॆ বার सिंगिल् র चा সিনরचर я.h.a.
--------------------------------------------------

Translating:  27%|███████▎                   | 271/1000 [05:35<16:17,  1.34s/it]

[271/1000]
EN: India’s doubles pair beat David Pel and Sander Arends in a tight five-setter.
MNI_BENG: জিদের বির্লিালারী.h.., ম.at. in.
--------------------------------------------------

Translating:  27%|███████▎                   | 272/1000 [05:36<16:20,  1.35s/it]

[272/1000]
EN: The doubles win was described as India’s first in five playoff ties versus Europeans.
MNI_BENG: জিদের বির্লিলারামিন্দী.h.. ৱি.at. in.
--------------------------------------------------

Translating:  27%|███████▎                   | 273/1000 [05:38<18:03,  1.49s/it]

[273/1000]
EN: The same report said Sumit Nagal failed to seal the tie in reverse singles.
MNI_BENG: জিদের বির্লিলারান্দী দিমি কিুরিশি, বারে्लॆ সিনর चा ята ) ।
--------------------------------------------------

Translating:  27%|███████▍                   | 274/1000 [05:40<20:10,  1.67s/it]

[274/1000]
EN: Novak Djokovic said he still wanted to represent Serbia in Davis Cup.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দ चा বারেস  কিুর्रॆ, ятали ाय़ the तिकिल् শি्लॆ তিावन নরr ।
--------------------------------------------------

Translating:  28%|███████▍                   | 275/1000 [05:42<20:36,  1.71s/it]

[275/1000]
EN: Serbia captain Viktor Troicki described Novak Djokovic as a major team figure.
MNI_BENG: জিদেরী বির্রালিন্দিলা দরিমি কি तिक, বারचर āিুরেশিন ята.
--------------------------------------------------

Translating:  28%|███████▍                   | 276/1000 [05:44<20:28,  1.70s/it]

[276/1000]
EN: Novak Djokovic withdrew from a 2025 Davis Cup qualifier due to a hamstring injury.
MNI_BENG: জিদের  2025 বির্লিলারী ামি्लॆ দরিন্দি, ānᱹ я..h. in.m.e.
--------------------------------------------------

Translating:  28%|███████▍                   | 277/1000 [05:45<19:15,  1.60s/it]

[277/1000]
EN: Carlos Alcaraz beat Alexander Zverev in a five-hour, 27-minute Australian Open semifinal.
MNI_BENG: জিদের.ᱹ বিলা.া., লি.ী. in.h.্র. я.
--------------------------------------------------

Translating:  28%|███████▌                   | 278/1000 [05:47<19:37,  1.63s/it]

[278/1000]
EN: Carlos Alcaraz won the Australian Open final after facing Novak Djokovic.
MNI_BENG: জিদের বির্রী ালারিলিমিন্দ দরেস ятал, বারুর चा  কিশিावन ाय़?
--------------------------------------------------

Translating:  28%|███████▌                   | 279/1000 [05:48<18:44,  1.56s/it]

[279/1000]
EN: Jannik Sinner was described as holding five straight wins over Novak Djokovic.
MNI_BENG: জিদেরী বির্রালিমিলার দরিন্দিশিावन., я.h.
--------------------------------------------------

Translating:  28%|███████▌                   | 280/1000 [05:50<18:49,  1.57s/it]

[280/1000]
EN: The Djokovic–Sinner preview said Djokovic reached semifinals aided by a walkover and retirement.
MNI_BENG: জিদের বির্লিলারামিন্দরী निश्चित, বারুরিসি কি तिक b्लॆ दक्षिण मरु ओइबाशय़ श्री @ na.h.
--------------------------------------------------

Translating:  28%|███████▌                   | 281/1000 [05:52<19:18,  1.61s/it]

[281/1000]
EN: An Australian Open report said extreme heat forced temporary suspensions on outside courts.
MNI_BENG: জিদের বির্লিলারামিন্দরী দি কিুরিশি, বারেসরचर क्कूट चा ята ) ।
--------------------------------------------------

Translating:  28%|███████▌                   | 282/1000 [05:53<19:37,  1.64s/it]

[282/1000]
EN: The same report said organisers issued heat warnings for players and spectators.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ, বারুরি কিসরে्लॆ দিশিat ৱিावनाय़ ān.h.
--------------------------------------------------

Translating:  28%|███████▋                   | 283/1000 [05:54<17:11,  1.44s/it]

[283/1000]
EN: Jannik Sinner beat Eliot Spizzirri 4–6, 6–3, 6–4, 6–4 in Melbourne.
MNI_BENG: জির 4, 6, 3, 6.h4.দ..ে.া.
--------------------------------------------------

Translating:  28%|███████▋                   | 284/1000 [05:56<18:25,  1.54s/it]

[284/1000]
EN: A tennis feature said Fangran Tian was coached by Chennai’s Mangal Sriram since age 12.
MNI_BENG: জিদের , বির্রালিী লারিমিন্দ चा দি কিুরেদর 11.
--------------------------------------------------

Translating:  28%|███████▋                   | 285/1000 [05:57<16:36,  1.39s/it]

[285/1000]
EN: Badminton World Federation demoted Syed Modi International from Super 300 to Super 100.
MNI_BENG: জিদের., বি.া.ী.h. in.
--------------------------------------------------

Translating:  29%|███████▋                   | 286/1000 [05:58<16:04,  1.35s/it]

[286/1000]
EN: The same report said India Open retained Super 750 status for the 2027–2030 cycle.
MNI_BENG: জিদের  2027/2030 বির্লিলাাী, ाय़ 0..
--------------------------------------------------

Translating:  29%|███████▋                   | 287/1000 [05:59<14:59,  1.26s/it]

[287/1000]
EN: A badminton reforms report said World Championships and five Super 1000s will run 11 days.
MNI_BENG: জিদের 11..া.বি.ী.্র.,.h.লা.
--------------------------------------------------

Translating:  29%|███████▊                   | 288/1000 [06:01<14:43,  1.24s/it]

[288/1000]
EN: The Indian Express said BWF’s AGM 2026 would vote on a 3×15 scoring format.
MNI_BENG: জিদের., বি.ী.া.h.্র. লা. in.
--------------------------------------------------

Translating:  29%|███████▊                   | 289/1000 [06:02<14:03,  1.19s/it]

[289/1000]
EN: A Badminton Asia Team report said India lost 3–2 to Japan in men’s ties.
MNI_BENG: জিদের 3.h.m.ী. বি.া.লা.
--------------------------------------------------

Translating:  29%|███████▊                   | 290/1000 [06:03<14:40,  1.24s/it]

[290/1000]
EN: The same report said India lost to Thailand in women’s ties at the team event.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী.h., я.िल्. in.
--------------------------------------------------

Translating:  29%|███████▊                   | 291/1000 [06:04<14:47,  1.25s/it]

[291/1000]
EN: A selection report said Tanvi Sharma would play first singles after Unnati Hooda was out.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिक b, я.h..
--------------------------------------------------

Translating:  29%|███████▉                   | 292/1000 [06:06<16:07,  1.37s/it]

[292/1000]
EN: An India Open report said “nest materials” halted a women’s doubles semifinal in Delhi.
MNI_BENG: জিদের বির্লিলারামিন্দ..ী.at.a.h.e. in.ᱶ., я.िल्.
--------------------------------------------------

Translating:  29%|███████▉                   | 293/1000 [06:07<16:30,  1.40s/it]

[293/1000]
EN: A feature said An Se-young won 94.8 percent of her matches in 2025.
MNI_BENG: - দেরিজিব্রালিী লারেমির я 1954.8 ন্দ चा ā 49.
--------------------------------------------------

Translating:  29%|███████▉                   | 294/1000 [06:09<16:08,  1.37s/it]

[294/1000]
EN: The same feature said An Se-young began 2026 with two titles in two weeks.
MNI_BENG: .ᱹ দের্জিবিালা - লিমিী я.h.e.at.y.
--------------------------------------------------

Translating:  30%|███████▉                   | 295/1000 [06:10<15:36,  1.33s/it]

[295/1000]
EN: Lin Chun-yi beat Jonatan Christie 21–10, 21–18 in the India Open final.
MNI_BENG: জিদের. : 21.10.e.া.hᱹ বি.্র.ী.
--------------------------------------------------

Translating:  30%|███████▉                   | 296/1000 [06:11<14:13,  1.21s/it]

[296/1000]
EN: Devika Sihag beat Navya Kanderi 21–10, 21–13 to win in Baku.
MNI_BENG: জিদের. : 21/10/ 21.13 বি.
--------------------------------------------------

Translating:  30%|████████                   | 297/1000 [06:12<15:47,  1.35s/it]

[297/1000]
EN: Radhika Sharma won her first mixed doubles title partnering Sathwik Reddy.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিশি কিসিুরর dat, ятали.िल्. in.
--------------------------------------------------

Translating:  30%|████████                   | 298/1000 [06:14<15:04,  1.29s/it]

[298/1000]
EN: Ankur Bhattacharjee upset world-ranked opponent Bourrassaud 3–1 at WTT Chennai.
MNI_BENG: জিদের.া.ᱹ বি.লা.,  3.E.
--------------------------------------------------

Translating:  30%|████████                   | 299/1000 [06:15<14:37,  1.25s/it]

[299/1000]
EN: FIFA president Gianni Infantino faced criticism over high-priced tickets for the 2026 World Cup.
MNI_BENG: জিদের.ᱹ. বি.া.h., লা.ী.্র.
--------------------------------------------------

Translating:  30%|████████                   | 300/1000 [06:16<14:25,  1.24s/it]

[300/1000]
EN: India lost 1-3 to Belgium in the FIH Pro League opener at Rourkela.
MNI_BENG: - জিদের্রী বিলিলাামির 1- 1.
--------------------------------------------------

Translating:  30%|████████▏                  | 301/1000 [06:17<15:15,  1.31s/it]

[301/1000]
EN: Craig Fulton said India’s defensive structure did not deliver in the Pro League opener.
MNI_BENG: জিদের বির্লিলারান্দরী ᱟᱢ, মি्लॆ দি কিুরিসর dat.h.
--------------------------------------------------

Translating:  30%|████████▏                  | 302/1000 [06:19<15:32,  1.34s/it]

[302/1000]
EN: India then suffered a 0-8 loss to Argentina in the next Pro League match.
MNI_BENG: -রিদেজিব্রলিমিলাান্দরী দিরেরুসিশি я..
--------------------------------------------------

Translating:  30%|████████▏                  | 303/1000 [06:21<16:48,  1.45s/it]

[303/1000]
EN: India’s 0-8 defeat was described as a systematic demolition by Argentina.
MNI_BENG: - দেরিজিব্রলিলারী মিরান্দি কিদর dat, ята?
--------------------------------------------------

Translating:  30%|████████▏                  | 304/1000 [06:22<17:45,  1.53s/it]

[304/1000]
EN: India’s 0-8 loss matched the joint third-worst defeat in India’s hockey history.
MNI_BENG: - দেরিজিব্রলিমিলারী ারেন্দ चा я..h.e., 0.-.at.y.a.
--------------------------------------------------

Translating:  30%|████████▏                  | 305/1000 [06:24<18:14,  1.58s/it]

[305/1000]
EN: India’s other 0-8 losses came in 1985 versus Netherlands and 2010 versus Australia.
MNI_BENG: .- জিদের্রী বিলিলারান্দরমি কিরিসি b, я.वा.ᱹ বা.at.e.
--------------------------------------------------

Translating:  31%|████████▎                  | 306/1000 [06:26<18:52,  1.63s/it]

[306/1000]
EN: Argentina’s Tomas Domene scored four goals in the 0-8 win over India.
MNI_BENG: - দেরিজিবিলাাল্রী মিন্দ चा ята, বারেশি কিসিরর dat.
--------------------------------------------------

Translating:  31%|████████▎                  | 307/1000 [06:27<16:08,  1.40s/it]

[307/1000]
EN: Tomas Domene scored at 15th, 20th, 26th and 60th minutes against India.
MNI_BENG: জিদের 15, 20, 26. 60..ী.বি.
--------------------------------------------------

Translating:  31%|████████▎                  | 308/1000 [06:28<17:35,  1.53s/it]

[308/1000]
EN: Tomas Ruiz, Lucio Mendez, Ignacio Ibarra, and Nicolas della Torre also scored for Argentina.
MNI_BENG: জিদের বির্রালিমিন্দ দিলারী বারি तिकआ, রেস яла  কি्लॆ শিच्चििल् āla.h.
--------------------------------------------------

Translating:  31%|████████▎                  | 309/1000 [06:30<18:11,  1.58s/it]

[309/1000]
EN: India’s third quarter without conceding a goal looked like an anomaly in the match.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারুরি কি्लॆ, সরেশিावन я.
--------------------------------------------------

Translating:  31%|████████▎                  | 310/1000 [06:31<17:12,  1.50s/it]

[310/1000]
EN: Player-of-the-Match Tomas Domene said Argentina played the whole game at 100 percent.
MNI_BENG: জিদেরী.ᱹ বিলা.া.h.্র., লি.at. in.
--------------------------------------------------

Translating:  31%|████████▍                  | 311/1000 [06:33<15:44,  1.37s/it]

[311/1000]
EN: Tomas Domene said Argentina were disappointed after losing 3-5 to Belgium previously.
MNI_BENG: জিদের -ব্রালিমিলার 3.
--------------------------------------------------

Translating:  31%|████████▍                  | 312/1000 [06:34<16:12,  1.41s/it]

[312/1000]
EN: Argentina scored two quick goals at the end of the first quarter.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারেসরিশি কেুরর 49:00 ।
--------------------------------------------------

Translating:  31%|████████▍                  | 313/1000 [06:36<16:43,  1.46s/it]

[313/1000]
EN: Argentina scored five goals in 10 minutes during the second quarter.
MNI_BENG: জিদের 10 বির্রী ালিলার 1, মিন্দর 5 দি কিসর 11 : 0 49 я?
--------------------------------------------------

Translating:  31%|████████▍                  | 314/1000 [06:37<17:44,  1.55s/it]

[314/1000]
EN: Harmanpreet Singh missed two penalty strokes in the match against Argentina.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারেসরি কিুরचर দিশিat ৱিতিावनꯂ ।
--------------------------------------------------

Translating:  32%|████████▌                  | 315/1000 [06:39<17:27,  1.53s/it]

[315/1000]
EN: India missed three penalty corners during the 0-8 defeat against Argentina.
MNI_BENG: -রিদেজিব্রলিমিলারীच्च चा ারেন্দি কিসির dat, я..वा.
--------------------------------------------------

Translating:  32%|████████▌                  | 316/1000 [06:40<17:51,  1.57s/it]

[316/1000]
EN: India goalkeepers Suraj Karkera and Pawan looked completely out of place.
MNI_BENG: জিদের বিলার্রালি, মিন্দরী দিরিসর dāf র चा  तिकाय़?
--------------------------------------------------

Translating:  32%|████████▌                  | 317/1000 [06:42<17:56,  1.58s/it]

[317/1000]
EN: Argentina dominated possession and toyed with India’s midfield and defence.
MNI_BENG: জিদের বির্লিলারামিন্দী, বারিসরেশি কিুররat দরचर я.h.
--------------------------------------------------

Translating:  32%|████████▌                  | 318/1000 [06:43<17:06,  1.51s/it]

[318/1000]
EN: Argentina’s win catapulted them to fourth in the nine-team standings.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী ятал, বারিসি কিশিावन क्कूट 49.hant.
--------------------------------------------------

Translating:  32%|████████▌                  | 319/1000 [06:45<16:27,  1.45s/it]

[319/1000]
EN: India next faced world No.2 Belgium again after the heavy Argentina loss.
MNI_BENG: জিদেরী বির্রালি. 2, লারেন্দ चा মি কিুরিশিावन বার सिंगिल् দরat я.hant.
--------------------------------------------------

Translating:  32%|████████▋                  | 320/1000 [06:46<16:12,  1.43s/it]

[320/1000]
EN: Macklin Celebrini scored early to spark Canada’s 5-0 win over Czech Republic.
MNI_BENG: .ᱹ দেরিজিবিলাালি, মির্রী яте : বার चा  बुधबार ।
--------------------------------------------------

Translating:  32%|████████▋                  | 321/1000 [06:47<15:16,  1.35s/it]

[321/1000]
EN: Macklin Celebrini scored with just over five seconds left in the first period.
MNI_BENG: জিদের বির্রালিমিলারী, দরিন্দ चा বারেসর কি तिक bā 1954 ।
--------------------------------------------------

Translating:  32%|████████▋                  | 322/1000 [06:48<13:39,  1.21s/it]

[322/1000]
EN: Mark Stone, Bo Horvat, Nathan MacKinnon and Nick Suzuki scored in Canada’s opener.
MNI_BENG: জিদের বির্রালি,.h.ारा. লা.ী.
--------------------------------------------------

Translating:  32%|████████▋                  | 323/1000 [06:49<13:10,  1.17s/it]

[323/1000]
EN: Connor McDavid recorded three assists in Canada’s 5-0 Olympic win.
MNI_BENG: - দেরিজিব্রী ালিন্দিলারমি কিরেদর я..h.at.
--------------------------------------------------

Translating:  32%|████████▋                  | 324/1000 [06:51<14:12,  1.26s/it]

[324/1000]
EN: Sidney Crosby said Celebrini’s first Olympic goal was huge to get Canada going.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কি्लॆ, বারেসর datᱶ 49.
--------------------------------------------------

Translating:  32%|████████▊                  | 325/1000 [06:52<14:12,  1.26s/it]

[325/1000]
EN: Jon Cooper said Macklin Celebrini plays the game well beyond his years.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ, দরিন্দিশিावन বারেসরুরর কি तिकिल् я 543 ।
--------------------------------------------------

Translating:  33%|████████▊                  | 326/1000 [06:53<14:00,  1.25s/it]

[326/1000]
EN: Canada planned to face Switzerland at the Milano Arena the next day.
MNI_BENG: জিদের বির্লিলারী দামিন্দ चा বারিসি কিুরেশিat ৱি तिकिल् я 1954 ।
--------------------------------------------------

Translating:  33%|████████▊                  | 327/1000 [06:55<14:20,  1.28s/it]

[327/1000]
EN: Choi Ga-on won women’s snowboard halfpipe gold after recovering from a first-run crash.
MNI_BENG: জিদের বির্লিলা - দামিন্দরী ᱟᱢ, বারুরি কি तिक bরেশিন-at.h ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  33%|████████▊                  | 328/1000 [06:56<14:22,  1.28s/it]

[328/1000]
EN: Chloe Kim took silver and Mitsuki Ono won bronze in the halfpipe event.
MNI_BENG: জিদের বির্রালিমিলারী, ন্দরিসর 49:00 चा বারেশি কিনররু.
--------------------------------------------------

Translating:  33%|████████▉                  | 329/1000 [06:57<15:11,  1.36s/it]

[329/1000]
EN: Choi Ga-on scored 90.25 to beat Chloe Kim’s leading 88 score.
MNI_BENG: . জিদেরী বির্রালিম - я 90.25, লারিন্দর 49.
--------------------------------------------------

Translating:  33%|████████▉                  | 330/1000 [06:59<14:53,  1.33s/it]

[330/1000]
EN: Arsenal reached the League Cup final after Kai Havertz secured a 1-0 win.
MNI_BENG: .ᱹ দেরী জিবির্রালিন্দরলা মিুরি কি तिक bā 1954 ।
--------------------------------------------------

Translating:  33%|████████▉                  | 331/1000 [07:00<14:40,  1.32s/it]

[331/1000]
EN: Kai Havertz came off the bench to finish Arsenal’s 4-2 aggregate semi-final victory.
MNI_BENG: - দেরিজিব্রলিমিলারী বারান্দ चा  बुधबार,  दक्षिण ओइबाशय़ সিরেন - я 54.
--------------------------------------------------

Translating:  33%|████████▉                  | 332/1000 [07:01<13:37,  1.22s/it]

[332/1000]
EN: Arsenal will face Manchester City or Newcastle at Wembley on March 22.
MNI_BENG: জিরেদ , বিলিী লার্রান্দেমের я..
--------------------------------------------------

Translating:  33%|████████▉                  | 333/1000 [07:02<14:06,  1.27s/it]

[333/1000]
EN: Manchester City held a 2-0 lead over Newcastle ahead of the second leg.
MNI_BENG: .ᱹ দেরিজিব্রী ালারলিমিন্দ चा সিরেশি কিদর dat, я- 2- 0.h?
--------------------------------------------------

Translating:  33%|█████████                  | 334/1000 [07:03<12:37,  1.14s/it]

[334/1000]
EN: Arsenal have not won the League Cup since 1993, according to the report.
MNI_BENG: জিদের., বি.া.ী.h.e.্র.
--------------------------------------------------

Translating:  34%|█████████                  | 335/1000 [07:05<14:00,  1.26s/it]

[335/1000]
EN: The Football Association of Ireland confirmed Ireland will fulfil Nations League fixtures against Israel.
MNI_BENG: জিদের বির্লিলারামিন্দী b दक्षिण ओइबा्लॆ বারিসি तिकिल् ялате, দরেশিावन क्कूट चाफम ।
--------------------------------------------------

Translating:  34%|█████████                  | 336/1000 [07:06<12:23,  1.12s/it]

[336/1000]
EN: Ireland and Israel were drawn with Austria and Kosovo in Nations League League B.
MNI_BENG: জিদের বির্রী  b.া.লা.h.b.
--------------------------------------------------

Translating:  34%|█████████                  | 337/1000 [07:07<12:05,  1.09s/it]

[337/1000]
EN: Ireland must play Israel home and away between September and November.
MNI_BENG: জিদের বির্লিলারামিন্দরী.ᱹ, я.h.at.
--------------------------------------------------

Translating:  34%|█████████▏                 | 338/1000 [07:08<12:00,  1.09s/it]

[338/1000]
EN: The FAI warned refusal could mean forfeiture and possible disqualification under UEFA regulations.
MNI_BENG: জিদের বির্লিলারামিন্দরী.h.. ᱪᱟᱞᱟᱣᱚᱜ, я.िल्.गद.
--------------------------------------------------

Translating:  34%|█████████▏                 | 339/1000 [07:09<11:38,  1.06s/it]

[339/1000]
EN: The FAI said it requested Israel’s UEFA ban in November after an internal vote.
MNI_BENG: জিদেরী বির্রালিমিলার.a. in.h.िल्.
--------------------------------------------------

Translating:  34%|█████████▏                 | 340/1000 [07:10<12:07,  1.10s/it]

[340/1000]
EN: Novak Djokovic beat Jannik Sinner 3-6, 6-3, 4-6, 6-4, 6-4 in Melbourne.
MNI_BENG: -, 4-6/6-4/ জিদের 6- 6-4 বি 6 - 4. :ᱹ6.4  तिक.h.a.
--------------------------------------------------

Translating:  34%|█████████▏                 | 341/1000 [07:11<13:12,  1.20s/it]

[341/1000]
EN: Novak Djokovic’s win over Jannik Sinner set up an Australian Open final against Carlos Alcaraz.
MNI_BENG: জিদেরী বির্রামিলিলার দরিন্দিস রেুর चा ятал,  तिकराज ৱিশি কি्लॆ  बुधबार ।
--------------------------------------------------

Translating:  34%|█████████▏                 | 342/1000 [07:13<14:31,  1.32s/it]

[342/1000]
EN: Novak Djokovic reached his 11th Australian Open final after ending four straight semi-final exits.
MNI_BENG: জিদের 11 বির্রী , লিলারামিন্দ দরিস বারেুরর चा ята  तिक bā 49  কিশি्लॆ  दक्षिण ओइबाशय़ ।
--------------------------------------------------

Translating:  34%|█████████▎                 | 343/1000 [07:14<14:22,  1.31s/it]

[343/1000]
EN: Carlos Alcaraz reached his first Melbourne Park title match, the report said.
MNI_BENG: জিদের বির্রালিমিলারী, বারেন্দর দ चा রি কিসর dāf ाय़ ।
--------------------------------------------------

Translating:  34%|█████████▎                 | 344/1000 [07:15<13:26,  1.23s/it]

[344/1000]
EN: Lorenzo Musetti retired mid-match after suffering a suspected upper leg tear.
MNI_BENG: জিদের বির্রালিমিলার ী,.h.. ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  34%|█████████▎                 | 345/1000 [07:17<13:46,  1.26s/it]

[345/1000]
EN: Lorenzo Musetti withdrew after winning the first two sets against Novak Djokovic.
MNI_BENG: জিদের বির্রী লারালিন্দ দরিমি কি्लॆ , বারেশিावन সিুরর dat.
--------------------------------------------------

Translating:  35%|█████████▎                 | 346/1000 [07:18<13:37,  1.25s/it]

[346/1000]
EN: Alexander Zverev rallied from losing the first set to beat Gabriel Diallo in four sets.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি्लॆ বারুরেশিावन.ᱹ, я. 54.
--------------------------------------------------

Translating:  35%|█████████▎                 | 347/1000 [07:19<13:44,  1.26s/it]

[347/1000]
EN: Alexander Zverev won 6-7(1), 6-1, 6-4, 6-2 against Gabriel Diallo at Rod Laver Arena.
MNI_BENG: -7/1 6-6-4/6-2 জিদের্রাবিলি ।
--------------------------------------------------

Translating:  35%|█████████▍                 | 348/1000 [07:21<14:28,  1.33s/it]

[348/1000]
EN: An Australian Open report noted fans were unhappy about long queues and a ticket sales halt.
MNI_BENG: জিদের বির্লিলারান্দরী निश्चित, মি কিসরিুর dat दक्षिण मरु ओइबाशय़ বার चा দিশি्लॆ ৱाय़ theबल ā 495 ।
--------------------------------------------------

Translating:  35%|█████████▍                 | 349/1000 [07:22<14:50,  1.37s/it]

[349/1000]
EN: A Hindustan Times column said tennis needs rivalries to elevate players and the sport.
MNI_BENG: জিদের বির্লিলারান্দরী ᱟᱢ, মিুরিশি কিসিावन দিনরचर বারেদat я.
--------------------------------------------------

Translating:  35%|█████████▍                 | 350/1000 [07:23<15:08,  1.40s/it]

[350/1000]
EN: A Hindustan Times column said Jannik Sinner and Carlos Alcaraz are improving every year.
MNI_BENG: জিদের বির্লিলারামিন্দরী দিসরি কিুরে्लॆ ятале, বারचर चा শিक्कूट 49.hant.at.शय़.
--------------------------------------------------

Translating:  35%|█████████▍                 | 351/1000 [07:25<14:38,  1.35s/it]

[351/1000]
EN: The same column said Sinner and Alcaraz already play at a level above most players.
MNI_BENG: জিদের বির্লিলারামিী, ন্দ चा বারি কিুরে्लॆ দিশিসর dat.h..
--------------------------------------------------

Translating:  35%|█████████▌                 | 352/1000 [07:26<13:39,  1.26s/it]

[352/1000]
EN: The column said Federer, Nadal and Djokovic gave men’s tennis a tribal feel for two decades.
MNI_BENG: জিদের বির্রালিমিলারী,  49..at.शय़.h. in.िल्.
--------------------------------------------------

Translating:  35%|█████████▌                 | 353/1000 [07:27<13:58,  1.30s/it]

[353/1000]
EN: A report said Alexander Zverev began a bid for a maiden Australian Open title.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ, বারুরি কিশিावन দিসরে उद्देशिल् ān?
--------------------------------------------------

Translating:  35%|█████████▌                 | 354/1000 [07:28<13:47,  1.28s/it]

[354/1000]
EN: Carlos Alcaraz defeated Alexander Zverev 6-3, 3-6, 6-1, 6-2 at the Australian Open.
MNI_BENG: জিদের 6 - 6/6/ 6-6/11/  6-2 বির্রালি ।
--------------------------------------------------

Translating:  36%|█████████▌                 | 355/1000 [07:29<12:57,  1.21s/it]

[355/1000]
EN: Carlos Alcaraz won in two hours and 26 minutes, according to the match report.
MNI_BENG: জিদের , বির্রালিমিী লারিন্দর 29..
--------------------------------------------------

Translating:  36%|█████████▌                 | 356/1000 [07:30<12:18,  1.15s/it]

[356/1000]
EN: The same report said Zverev received a time-violation warning during the match.
MNI_BENG: জিদের বির্লিলারীামিন্দর.. ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  36%|█████████▋                 | 357/1000 [07:32<12:46,  1.19s/it]

[357/1000]
EN: The report said Alcaraz requested a meeting with the supervisor after the time warning.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দী, বারি কিশি्लॆ সিুরেদর dat दक्षिण я?
--------------------------------------------------

Translating:  36%|█████████▋                 | 358/1000 [07:33<13:08,  1.23s/it]

[358/1000]
EN: The report said Alcaraz complained about the length of Zverev’s breaks between points.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারেসররি কিশি्लॆ āst : / я.h.
--------------------------------------------------

Translating:  36%|█████████▋                 | 359/1000 [07:34<13:07,  1.23s/it]

[359/1000]
EN: Carlos Alcaraz said he also wanted to know the limit for the time between points.
MNI_BENG: জিদের বির্লিলারামিন্দী, দরি কিসররেশি b दक्षिण मरु ओइबाोक ৱরু ।
--------------------------------------------------

Translating:  36%|█████████▋                 | 360/1000 [07:36<13:15,  1.24s/it]

[360/1000]
EN: R Praggnanandhaa sealed a 2026 Candidates berth by winning the FIDE Circuit 2025.
MNI_BENG: জিদের  2026 বির্লিলারামিী निश्चित, ন্দরি 255 বারেস দি কি्लॆ я.
--------------------------------------------------

Translating:  36%|█████████▋                 | 361/1000 [07:36<12:13,  1.15s/it]

[361/1000]
EN: The Candidates Tournament will determine the challenger to world champion D Gukesh.
MNI_BENG: জিদেরী বির্রালিলার..ᱹ я.h.at.
--------------------------------------------------

Translating:  36%|█████████▊                 | 362/1000 [07:37<11:17,  1.06s/it]

[362/1000]
EN: R Praggnanandhaa overtook Ding Liren in May to lead the FIDE Circuit race.
MNI_BENG: জিদের বির্রালিমিী., লা.
--------------------------------------------------

Translating:  36%|█████████▊                 | 363/1000 [07:38<11:07,  1.05s/it]

[363/1000]
EN: Praggnanandhaa thanked supporters on X after earning a place in the 2026 Candidates.
MNI_BENG: 2026 দের্জিবিলিলা ারী মিন্দ चा ाय़.
--------------------------------------------------

Translating:  36%|█████████▊                 | 364/1000 [07:39<11:20,  1.07s/it]

[364/1000]
EN: A report said only Nodirbek Abdusattorov had a theoretical chance to catch Praggnanandhaa.
MNI_BENG: জিদের্রী বিরালিন্দরলা দিমি কি तिक, বারুরিস āsta. b.
--------------------------------------------------

Translating:  36%|█████████▊                 | 365/1000 [07:41<12:41,  1.20s/it]

[365/1000]
EN: D Gukesh withdrew from Tata Steel Chess India Rapid and Blitz for personal reasons.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসর dat, বারেশি्लॆ āstha  bjb दबल ята ) ।
--------------------------------------------------

Translating:  37%|█████████▉                 | 366/1000 [07:42<12:22,  1.17s/it]

[366/1000]
EN: Tata Steel Chess India Rapid and Blitz was scheduled in Kolkata from January 7 to 11.
MNI_BENG: জিদেরী.ᱹ বির্রালি, লারিমিন্দর 11 я.at.e.
--------------------------------------------------

Translating:  37%|█████████▉                 | 367/1000 [07:43<12:45,  1.21s/it]

[367/1000]
EN: Nihal Sarin replaced D Gukesh in the Tata Steel Chess India event.
MNI_BENG: জিদের  বির্রালিমিলাী দরিন্দ चा ята, বারचर সি কিশি्लॆ  दक्षिणाय़ ।
--------------------------------------------------

Translating:  37%|█████████▉                 | 368/1000 [07:44<12:16,  1.17s/it]

[368/1000]
EN: Dibyendu Barua called D Gukesh’s withdrawal a big setback for organisers and fans.
MNI_BENG: জিদের বির্লিলারামী.., দি.at. in.
--------------------------------------------------

Translating:  37%|█████████▉                 | 369/1000 [07:46<12:23,  1.18s/it]

[369/1000]
EN: Viswanathan Anand returned to play Tata Steel Chess India after six years away.
MNI_BENG: জিদের বির্লিলারামিন্দরী রিসি কি्लॆ দিশি तिकिल्, āsta.hant.
--------------------------------------------------

Translating:  37%|█████████▉                 | 370/1000 [07:47<11:42,  1.12s/it]

[370/1000]
EN: Viswanathan Anand said “It was exhausting not playing” while explaining his return.
MNI_BENG: জিদের..বি.ী.া.লা.h.at.e.্র.
--------------------------------------------------

Translating:  37%|██████████                 | 371/1000 [07:48<11:55,  1.14s/it]

[371/1000]
EN: Viswanathan Anand was set to open against Wesley So in the seventh edition.
MNI_BENG: জিদের বির্লিলারামিন্দী, দরিসরুরেশি কি्लॆ ята?
--------------------------------------------------

Translating:  37%|██████████                 | 372/1000 [07:49<12:32,  1.20s/it]

[372/1000]
EN: The tournament director said Tata Steel Chess India will be held in January going forward.
MNI_BENG: জিদের বির্লিলাামিন্দী দরি কি्लॆ, বারেসিন রুরचर चा শিতিावन at ।
--------------------------------------------------

Translating:  37%|██████████                 | 373/1000 [07:51<13:16,  1.27s/it]

[373/1000]
EN: The Tata Steel Chess India event offered equal prize purses of $41,500 in open and women’s.
MNI_BENG: .- জিদের্রাবিলিমিলারী दक्षिण चा বারিরেন্দ দররचर ān, 0 5. 49,500 ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  37%|██████████                 | 374/1000 [07:52<12:24,  1.19s/it]

[374/1000]
EN: Viswanathan Anand backed the Total Chess World Championship Tour approved by FIDE.
MNI_BENG: জিদের বির্লিলারামিন্দরী., দি.
--------------------------------------------------

Translating:  38%|██████████▏                | 375/1000 [07:53<11:50,  1.14s/it]

[375/1000]
EN: The Total Chess World Championship Tour will crown a new “FIDE World Combined” champion.
MNI_BENG: জিদেরী বির্রালিন্দ.h.. ৱি.লা.
--------------------------------------------------

Translating:  38%|██████████▏                | 376/1000 [07:54<12:15,  1.18s/it]

[376/1000]
EN: The tour will be held across fast classic, rapid and blitz formats.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী, ята ) বারি কিুরেসিশি किराम b ।
--------------------------------------------------

Translating:  38%|██████████▏                | 377/1000 [07:55<11:39,  1.12s/it]

[377/1000]
EN: Anand said Norway Chess has a serious long-term proposal for the new tour.
MNI_BENG: জিদের বির্লিলারামিী, দরেন্দ चा я.h.िल्.at.
--------------------------------------------------

Translating:  38%|██████████▏                | 378/1000 [07:56<12:44,  1.23s/it]

[378/1000]
EN: Anand said the sport benefits when Magnus Carlsen competes in major events.
MNI_BENG: জিদের বির্লিলারান্দরী ᱟᱢ, মি কিুরিावन দিশি्लॆ বারেসর सिंगिल् ятали.
--------------------------------------------------

Translating:  38%|██████████▏                | 379/1000 [07:58<12:56,  1.25s/it]

[379/1000]
EN: Wesley So said he proposed a draw against Praggnanandhaa, not the arbiters.
MNI_BENG: জিদের বির্লিলারামিন্দী, দরি কিুরে्लॆ বার चा সিশিावन я.
--------------------------------------------------

Translating:  38%|██████████▎                | 380/1000 [07:59<13:00,  1.26s/it]

[380/1000]
EN: Praggnanandhaa had one second left before stopping the clock to call the arbiter.
MNI_BENG: জিদের বির্লিলারামিী, ন্দররিসরেশি কি्लॆᱶ я.
--------------------------------------------------

Translating:  38%|██████████▎                | 381/1000 [08:00<13:23,  1.30s/it]

[381/1000]
EN: Nihal Sarin won the 2026 Tata Steel Chess India Rapid Tournament in Kolkata.
MNI_BENG: জিদের  2026 বির্রালিমিলারী ᱟᱢ, রিন্দ चा বারেসি কিশিতি दक्षिण ओइबा দররু ।
--------------------------------------------------

Translating:  38%|██████████▎                | 382/1000 [08:02<13:22,  1.30s/it]

[382/1000]
EN: Ian Nepomniachtchi criticised hotel conditions during the 2025 Chess World Cup in Goa.
MNI_BENG: জিদের  2025 বির্রালারী चा লিমিন্দ দি কিুরचर я..h.e. 54. ā.
--------------------------------------------------

Translating:  38%|██████████▎                | 383/1000 [08:03<13:30,  1.31s/it]

[383/1000]
EN: Ian Nepomniachtchi said organisers chose one of the worst hotels for the Goa event.
MNI_BENG: জিদেরী বির্রালিমিলান্দি, দরি কিুরে्लॆ বারचर चा সিশিনat āst 49.hant.
--------------------------------------------------

Translating:  38%|██████████▎                | 384/1000 [08:04<13:03,  1.27s/it]

[384/1000]
EN: Nepomniachtchi lost to Diptayan Ghosh after receiving a bye into round two.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিশিat, বারেসরचरिल् я.h.
--------------------------------------------------

Translating:  38%|██████████▍                | 385/1000 [08:05<12:57,  1.26s/it]

[385/1000]
EN: PGTI’s 2026 schedule was drawn up only till March-end, featuring six events.
MNI_BENG: 2026 জিরেদ্রী বিলারালি - মিন্দের 490 я..h.m.e.
--------------------------------------------------

Translating:  39%|██████████▍                | 386/1000 [08:07<12:46,  1.25s/it]

[386/1000]
EN: PGTI planned no more than 25 tournaments in 2026 after holding 36 events last year.
MNI_BENG: জিদের 25  2026 বির্লি 36 লারামিন্দী ।
--------------------------------------------------

Translating:  39%|██████████▍                | 387/1000 [08:08<12:30,  1.22s/it]

[387/1000]
EN: PGTI’s main tour offered ₹35 crore prize money in 2025, up from ₹24 crore.
MNI_BENG: জিদের.ᱹ, বিলা.া.ী.্র.h.e. in.re.a.िल्.at.y.
--------------------------------------------------

Translating:  39%|██████████▍                | 388/1000 [08:09<11:30,  1.13s/it]

[388/1000]
EN: OWGR granted LIV Golf accreditation for the first time, awarding points to top-10 finishers.
MNI_BENG: জিদের.া.h. বি.ী., লা. in.
--------------------------------------------------

Translating:  39%|██████████▌                | 389/1000 [08:10<10:55,  1.07s/it]

[389/1000]
EN: LIV Golf expanded tournaments from 54 to 72 holes in 2026, paving the approval.
MNI_BENG: .. জিদের্রলি 54/ বিরী 72,  2026. লা.
--------------------------------------------------

Translating:  39%|██████████▌                | 390/1000 [08:11<10:47,  1.06s/it]

[390/1000]
EN: OWGR said LIV Golf did not meet all eligibility standards under its requirements.
MNI_BENG: জিদের বির্লিলারী.া.a.िल्.h.at. in.
--------------------------------------------------

Translating:  39%|██████████▌                | 391/1000 [08:12<10:35,  1.04s/it]

[391/1000]
EN: LIV Golf’s season-opening event in Riyadh was set to start with 57 players.
MNI_BENG: জিরেদ..বিলা.ী.া.h.e.a.্র.
--------------------------------------------------

Translating:  39%|██████████▌                | 392/1000 [08:13<10:13,  1.01s/it]

[392/1000]
EN: International Series India was expected to move from DLF Golf and Country Club to Bengaluru.
MNI_BENG: জিদেরী বির্রালিমিলার., দি.at. in.
--------------------------------------------------

Translating:  39%|██████████▌                | 393/1000 [08:14<10:05,  1.00it/s]

[393/1000]
EN: Bryson DeChambeau and Joaquin Niemann were key draws at International Series India 2025.
MNI_BENG: জিদেরী.ᱹ বি.া.h.e. in.a., লা.
--------------------------------------------------

Translating:  39%|██████████▋                | 394/1000 [08:14<09:57,  1.01it/s]

[394/1000]
EN: Ollie Schniederjans won International Series India 2025 by four shots in Gurugram.
MNI_BENG: জিদের.ᱹ বিলা.া., লি.ী.্র.
--------------------------------------------------

Translating:  40%|██████████▋                | 395/1000 [08:16<10:24,  1.03s/it]

[395/1000]
EN: Rahul Singh said International Series organisers remained committed to returning to India.
MNI_BENG: জিদের বির্লিলারান্দী ᱟᱢ, মিুরিশিावन দরचर āsta.hant.
--------------------------------------------------

Translating:  40%|██████████▋                | 396/1000 [08:17<11:02,  1.10s/it]

[396/1000]
EN: PGTI launched a league with six franchises, with each franchise buying 10 players.
MNI_BENG: জিদেরী বির্রালি, লারিমিন্দর 10 দি কিুরেশিসর dat.
--------------------------------------------------

Translating:  40%|██████████▋                | 397/1000 [08:18<11:40,  1.16s/it]

[397/1000]
EN: The PGTI league’s first edition was planned across three courses in Delhi-NCR.
MNI_BENG: জিদের বির্লিলারামি - রী, বারিন্দর.h.m.at.e. in.
--------------------------------------------------

Translating:  40%|██████████▋                | 398/1000 [08:19<11:11,  1.12s/it]

[398/1000]
EN: Shubhankar Sharma missed cuts in 21 of 28 events in 2025, the report said.
MNI_BENG: জিদের.ᱹ বিলা.া.ী.্র., লি.ম. in.
--------------------------------------------------

Translating:  40%|██████████▊                | 399/1000 [08:20<11:34,  1.16s/it]

[399/1000]
EN: Shubhankar Sharma regained playing rights for 2026 via Q-School, finishing tied-second.
MNI_BENG: -রিদেজিব্রলিলাামিরী দরেন্দ चा ाय़ 2026 я..h.e. বা.a. in.
--------------------------------------------------

Translating:  40%|██████████▊                | 400/1000 [08:21<11:03,  1.11s/it]

[400/1000]
EN: Vietnam targets 22 to 25 million international visitors by 2026.
MNI_BENG: 2026 জিদের 25 বির্রী ালালিমি 22, я.
--------------------------------------------------

Translating:  40%|██████████▊                | 401/1000 [08:23<11:51,  1.19s/it]

[401/1000]
EN: Operations teams monitor weather to minimize passenger inconvenience.
MNI_BENG: জিদের বির্লিলাামিন্দী দরি কিুরেশিat ятал, বার सिंगिल् সরचर चाफम ।
--------------------------------------------------

Translating:  40%|██████████▊                | 402/1000 [08:24<11:44,  1.18s/it]

[402/1000]
EN: IndiGo announces Amsterdam debut as first long-haul European destination.
MNI_BENG: জিদের বির্রালিমিী লারিন্দর - দিসরেশি কিন, я.
--------------------------------------------------

Translating:  40%|██████████▉                | 403/1000 [08:25<11:26,  1.15s/it]

[403/1000]
EN: Air India crash committee investigates Boeing 787-8 Ahmedabad tragedy.
MNI_BENG: - জিদেরী বির্রালিমিন্দ चा লারি तिकिल्  बुधबार ।
--------------------------------------------------

Translating:  40%|██████████▉                | 404/1000 [08:26<10:55,  1.10s/it]

[404/1000]
EN: IndiGo aims for forty percent international capacity share by 2030.
MNI_BENG: জিদর..ᱹ বের্রালি ।
--------------------------------------------------

Translating:  40%|██████████▉                | 405/1000 [08:27<11:20,  1.14s/it]

[405/1000]
EN: One survivor rescued from Air India crash site in Ahmedabad.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসি কিশিat ৱিक्कूट चा বারr ।
--------------------------------------------------

Translating:  41%|██████████▉                | 406/1000 [08:28<11:33,  1.17s/it]

[406/1000]
EN: Jetstar Asia closure frees five hundred million dollars for Qantas.
MNI_BENG: জিদের বির্রালারলি, মিন্দরী দিসরিশিावन বারুরचर  কি्लॆ ।
--------------------------------------------------

Translating:  41%|██████████▉                | 407/1000 [08:30<11:39,  1.18s/it]

[407/1000]
EN: Qantas Group announces closure of Singapore-based Jetstar Asia.
MNI_BENG: জিদের বির্রালিলার - মিন্দরী দিসরিশি কিন-রেদat, я.h.
--------------------------------------------------

Translating:  41%|███████████                | 408/1000 [08:31<11:20,  1.15s/it]

[408/1000]
EN: IndiGo launches Mumbai-Manchester flights using Norse aircraft.
MNI_BENG: জিদের  বির্র - লিলারী ামিন্দ चा দি কি तिक bā..h.
--------------------------------------------------

Translating:  41%|███████████                | 409/1000 [08:32<10:47,  1.10s/it]

[409/1000]
EN: IndiGo transitions to A350-900 aircraft for European expansion by 2027.
MNI_BENG: 2027- জিদের বির্রী ালিমিলার 3, 50-900 я?
--------------------------------------------------

Translating:  41%|███████████                | 410/1000 [08:32<09:36,  1.02it/s]

[410/1000]
EN: Air India Ahmedabad crash claims 242 lives including Vijay Rupani.
MNI_BENG: জিদেরী.ᱹ বি. লা.
--------------------------------------------------

Translating:  41%|███████████                | 411/1000 [08:34<10:07,  1.03s/it]

[411/1000]
EN: Thirteen Jetstar Asia A320s redeployed to Australia and New Zealand.
MNI_BENG: জিদের  320 বির্লিলারামিন্দী দরি কিুরেশিावन я..h.
--------------------------------------------------

Translating:  41%|███████████                | 412/1000 [08:35<10:41,  1.09s/it]

[412/1000]
EN: IndiGo issues fog advisory for Delhi and northern India passengers.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দ चा বারেসি কিশি, я.h. in.
--------------------------------------------------

Translating:  41%|███████████▏               | 413/1000 [08:36<09:50,  1.01s/it]

[413/1000]
EN: DGCA imposes ₹2 crore fine on Air India for safety lapses.
MNI_BENG: জিদের., বি.া.ী.্র.
--------------------------------------------------

Translating:  41%|███████████▏               | 414/1000 [08:37<09:45,  1.00it/s]

[414/1000]
EN: Sixteen intra-Asia routes lose only non-stop Changi connections.
MNI_BENG: জিদের বির্রা - লিমিলারী ᱟᱢ দরিন্, я.h..
--------------------------------------------------

Translating:  42%|███████████▏               | 415/1000 [08:38<10:50,  1.11s/it]

[415/1000]
EN: Bengaluru airport opens second runway to handle growing traffic.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দিসর দরचर বারুরেশি কি तिकिल्, নর विरोधी ята.
--------------------------------------------------

Translating:  42%|███████████▏               | 416/1000 [08:39<11:27,  1.18s/it]

[416/1000]
EN: Air India Express pilot assaults passenger at Delhi airport terminal.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিসি করে्लॆ বার चा শিতি तिकिल्, ята.
--------------------------------------------------

Translating:  42%|███████████▎               | 417/1000 [08:41<12:01,  1.24s/it]

[417/1000]
EN: Mumbai airport witnesses record passenger footfall during festive week.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেসরचर বার चा  কিুরat ята ) ।
--------------------------------------------------

Translating:  42%|███████████▎               | 418/1000 [08:42<12:01,  1.24s/it]

[418/1000]
EN: Dense fog disrupts IndiGo flight operations across North India.
MNI_BENG: জিদের বিলার্রালিমিরী দরিন্দিশি কিসে उद्देशি समारंभ, বার चा क्कूटिल् я?
--------------------------------------------------

Translating:  42%|███████████▎               | 419/1000 [08:43<11:38,  1.20s/it]

[419/1000]
EN: Go First insolvency resolution extends to third consecutive month.
MNI_BENG: জিদের বির্রালিমিী লারেন্দি দরचर я.
--------------------------------------------------

Translating:  42%|███████████▎               | 420/1000 [08:44<11:41,  1.21s/it]

[420/1000]
EN: Akasa Air orders additional Boeing 737 Max aircraft for expansion.
MNI_BENG: জিদের  737 বির্লিলারী ামিন্দ चा বারি কিুরেশি?
--------------------------------------------------

Translating:  42%|███████████▎               | 421/1000 [08:46<12:29,  1.29s/it]

[421/1000]
EN: Air India pilots union raises concerns over rest period violations.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসি तिक dat ятал, क्कूट चा বারr.
--------------------------------------------------

Translating:  42%|███████████▍               | 422/1000 [08:47<10:51,  1.13s/it]

[422/1000]
EN: EU launches Entry-Exit System campaign for non-EU travellers.
MNI_BENG: জিরেদ -..বি.া.ী.
--------------------------------------------------

Translating:  42%|███████████▍               | 423/1000 [08:48<11:06,  1.16s/it]

[423/1000]
EN: SpiceJet secures funding to revive grounded fleet operations soon.
MNI_BENG: জিদের বির্লিলাামিন্দী দরি কিুরেশি 1954 ৱিসat, ята.
--------------------------------------------------

Translating:  42%|███████████▍               | 424/1000 [08:49<11:35,  1.21s/it]

[424/1000]
EN: Bulgaria adopts Euro as legal tender from January first 2026.
MNI_BENG: 2026 জিদের্রাবিলিমিলারীя বারেন্দরিসি কিরचर দিশি्लॆ ।
--------------------------------------------------

Translating:  42%|███████████▍               | 425/1000 [08:50<11:10,  1.17s/it]

[425/1000]
EN: Vietnam grants forty-five day visa-free entry to twelve European nations.
MNI_BENG: জিদের বির্লিলারী ামিস - দরেন্দ я.h..
--------------------------------------------------

Translating:  43%|███████████▌               | 426/1000 [08:52<11:50,  1.24s/it]

[426/1000]
EN: Indian government reverses ban on Sikh pilgrimages to Pakistan.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশিat, বার चा ята.
--------------------------------------------------

Translating:  43%|███████████▌               | 427/1000 [08:53<11:02,  1.16s/it]

[427/1000]
EN: Pakistan High Commission issues visas to twenty-one hundred Sikh pilgrims.
MNI_BENG: জিদের বির্রালিমিলাী.h.m.at. in.
--------------------------------------------------

Translating:  43%|███████████▌               | 428/1000 [08:54<11:03,  1.16s/it]

[428/1000]
EN: TSA ends shoe removal rule at domestic United States airports.
MNI_BENG: জিদের বির্লিলারামিন্দরী দিসি কিুরিশি 1954 ৱিat टय़ ।
--------------------------------------------------

Translating:  43%|███████████▌               | 429/1000 [08:55<11:49,  1.24s/it]

[429/1000]
EN: Real ID enforcement charges tourists forty-five dollars for domestic flights.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী ятал, বারেস রি কিন - শিावन āstha ाय़ ।
--------------------------------------------------

Translating:  43%|███████████▌               | 430/1000 [08:56<11:48,  1.24s/it]

[430/1000]
EN: United States government shutdown causes forty-three day travel chaos.
MNI_BENG: জিদের বির্রালি - মিলারী বারিন্দর দি तिक bā 1954 ।
--------------------------------------------------

Translating:  43%|███████████▋               | 431/1000 [08:58<12:12,  1.29s/it]

[431/1000]
EN: Government considers hotel industry infrastructure status for tax benefits.
MNI_BENG: জিদের বির্লিলারামিন্দরীच्च चा বারি কি तिक bf দিসরেশিावन я.
--------------------------------------------------

Translating:  43%|███████████▋               | 432/1000 [08:59<12:17,  1.30s/it]

[432/1000]
EN: Gajendra Singh Shekhawat announces infrastructure status proposal for hotels.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারুরি কি्लॆ রেশি किराम, সর चॆप्टम्पर् ।
--------------------------------------------------

Translating:  43%|███████████▋               | 433/1000 [09:00<12:13,  1.29s/it]

[433/1000]
EN: Tourism Ministry reboots Incredible India campaign with AI focus.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেশিat, বার सिंगिल् 1954 ।
--------------------------------------------------

Translating:  43%|███████████▋               | 434/1000 [09:02<12:20,  1.31s/it]

[434/1000]
EN: Suman Billa confirms new digital-centric Incredible India strategy.
MNI_BENG: জিদের বির্রালি - লারিমিন্দী দ चा я.
--------------------------------------------------

Translating:  44%|███████████▋               | 435/1000 [09:03<12:17,  1.31s/it]

[435/1000]
EN: India targets one trillion dollar tourism economy by 2047.
MNI_BENG: 47. জিদেরী বির্রামিলিন্দ লারিস দরর রুরেশি কি तिकिल् ।
--------------------------------------------------

Translating:  44%|███████████▊               | 436/1000 [09:05<12:58,  1.38s/it]

[436/1000]
EN: Centre sanctions fifty destinations for challenge mode tourism development.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দররেসি কিুরचरᱶ বার चा āিশিতি.
--------------------------------------------------

Translating:  44%|███████████▊               | 437/1000 [09:06<12:20,  1.32s/it]

[437/1000]
EN: Telangana adopts Sarathi portal for online RTA services.
MNI_BENG: জিদেরী  বির্রালি, মিলারিন্দ चा বারেস দचर я.
--------------------------------------------------

Translating:  44%|███████████▊               | 438/1000 [09:07<12:50,  1.37s/it]

[438/1000]
EN: Ministry announces twelve thousand crore rupees for new tourism destinations.
MNI_BENG: জিদের বির্লিলারামিন্দরী বারেসরি কিুরचर দিশিच्चि ৱিावनाय़ ān तिकिल्, ята?
--------------------------------------------------

Translating:  44%|███████████▊               | 439/1000 [09:09<13:01,  1.39s/it]

[439/1000]
EN: Government allocates 1.34 billion dollars for tourism infrastructure development.
MNI_BENG: .ᱹ দের্জিবিলিালারী মিরিন্দ चा বারেসিদর स्बदेश्वर ्रॆ, ān.
--------------------------------------------------

Translating:  44%|███████████▉               | 440/1000 [09:10<12:32,  1.34s/it]

[440/1000]
EN: India plans 2030 Commonwealth Games hosting to boost tourism.
MNI_BENG: জিদের বির্রালিমিী লারেন্দ দরিावन বারचर সি কি तिक bā 1954 ।
--------------------------------------------------

Translating:  44%|███████████▉               | 441/1000 [09:11<12:16,  1.32s/it]

[441/1000]
EN: Census self-enumeration trial begins for digital population count.
MNI_BENG: জিদের বির্লি - লারিামিন্দী দরেশি কি्लॆ, я.
--------------------------------------------------

Translating:  44%|███████████▉               | 442/1000 [09:12<11:39,  1.25s/it]

[442/1000]
EN: European Commission launches biometric border system awareness campaign.
MNI_BENG: জিদেরী বির্রালিমিলার দরিন্দ चा ān तिक b thera.h.
--------------------------------------------------

Translating:  44%|███████████▉               | 443/1000 [09:13<10:34,  1.14s/it]

[443/1000]
EN: Non-EU travellers face new digital border checks from October.
MNI_BENG: জিদের বির্লিলারামি्लॆ.h.m.ী.
--------------------------------------------------

Translating:  44%|███████████▉               | 444/1000 [09:14<10:01,  1.08s/it]

[444/1000]
EN: Dover ferry passengers register first for EU entry-exit system.
MNI_BENG: জিদের বির্রালি - মিলারী चा বারিন্দি ।
--------------------------------------------------

Translating:  44%|████████████               | 445/1000 [09:15<10:53,  1.18s/it]

[445/1000]
EN: Eurostar business travellers gradually included in EES rollout.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারুরি्लॆ সি কিশি तिकिल्, ята.
--------------------------------------------------

Translating:  45%|████████████               | 446/1000 [09:17<10:52,  1.18s/it]

[446/1000]
EN: India extends e-visa facility to citizens of five more nations.
MNI_BENG: জিদের বির্লি - ালারী মিন্দর দি কিুরি्लॆ я.
--------------------------------------------------

Translating:  45%|████████████               | 447/1000 [09:18<10:58,  1.19s/it]

[447/1000]
EN: Karnataka announces tourism policy targeting fifty billion dollar investment
MNI_BENG: জিদেরী বির্রালিমিলারিন্দ चा দিুরে तिक dat, ятали বার चॆप्टम्पर् ।
--------------------------------------------------

Translating:  45%|████████████               | 448/1000 [09:19<11:23,  1.24s/it]

[448/1000]
EN: GST Council reduces tax on hotel rooms below seven thousand five hundred rupees.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ, বারুরিসি কি तिक bf দিশিच्चि ৱিावनाय़ at?
--------------------------------------------------

Translating:  45%|████████████               | 449/1000 [09:20<09:53,  1.08s/it]

[449/1000]
EN: Ministry of Tourism launches Swadesh Darshan 3.0 for sustainable tourism.
MNI_BENG: জিদের.া.ী.
--------------------------------------------------

Translating:  45%|████████████▏              | 450/1000 [09:21<11:04,  1.21s/it]

[450/1000]
EN: Civil Aviation Ministry orders probe into Delhi airport assault case.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরে तिकाय़ āst, ятал्लॆ বার चा সিশিতি.
--------------------------------------------------

Translating:  45%|████████████▏              | 451/1000 [09:23<10:47,  1.18s/it]

[451/1000]
EN: Government approves UDAN 5.0 with focus on helicopter services.
MNI_BENG: জিদের  5. বির্রালিমিী লারিন্দ দিावन я.
--------------------------------------------------

Translating:  45%|████████████▏              | 452/1000 [09:24<11:32,  1.26s/it]

[452/1000]
EN: Kerala declares tourism as industry status for hotels and resorts.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিশি কিসরে्लॆ, ятамоны.
--------------------------------------------------

Translating:  45%|████████████▏              | 453/1000 [09:25<11:38,  1.28s/it]

[453/1000]
EN: West Bengal secures second rank in foreign tourist arrivals.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারিসি কিুরেশি्लॆ, āst.
--------------------------------------------------

Translating:  45%|████████████▎              | 454/1000 [09:27<12:12,  1.34s/it]

[454/1000]
EN: Mamata Banerjee hails West Bengal's international tourism milestone.
MNI_BENG: জিদের বির্লিলারী ামিন্দর দিশি কিুরি्लॆ বারr, সরেন я?
--------------------------------------------------

Translating:  46%|████████████▎              | 455/1000 [09:28<11:36,  1.28s/it]

[455/1000]
EN: Maharashtra leads foreign tourist arrivals with 3.71 million visitors.
MNI_BENG: .ᱹ জিদের্রী বিলিমিলারান্দ चा ाय़, я.वा. in.
--------------------------------------------------

Translating:  46%|████████████▎              | 456/1000 [09:29<11:39,  1.29s/it]

[456/1000]
EN: West Bengal records 3.12 million foreign tourist visits nationwide.
MNI_BENG: জিদের  3.12 বির্লিলাামিন্দরী দিসরি কিুরেশিावन ān?
--------------------------------------------------

Translating:  46%|████████████▎              | 457/1000 [09:30<11:08,  1.23s/it]

[457/1000]
EN: Uttar Pradesh tops domestic tourism with 646.81 million visitors.
MNI_BENG: .ᱹ জিদের্রী বিলিমিলারান্দ चा ाय़ 646.81 я.
--------------------------------------------------

Translating:  46%|████████████▎              | 458/1000 [09:32<11:04,  1.23s/it]

[458/1000]
EN: Tamil Nadu records 306.84 million domestic tourist footfall.
MNI_BENG: .ᱹ জিদেরী বির্রালিমিলারিন্দি কি तिक bfat, ān 0- ) ।
--------------------------------------------------

Translating:  46%|████████████▍              | 459/1000 [09:33<10:41,  1.19s/it]

[459/1000]
EN: India receives 2,948.19 million domestic tourists during 2024.
MNI_BENG: 1954.49.2 জিরেদা বিলার্রীলি ।
--------------------------------------------------

Translating:  46%|████████████▍              | 460/1000 [09:34<10:25,  1.16s/it]

[460/1000]
EN: Foreign tourist visits to India touch 20.94 million in 2024.
MNI_BENG: জিরেদ.., বিীলার্রালি ।
--------------------------------------------------

Translating:  46%|████████████▍              | 461/1000 [09:35<10:26,  1.16s/it]

[461/1000]
EN: Domestic tourism records 17.51 percent growth over previous year.
MNI_BENG: জিদের.51 বির্লিলারামিন্দি ।
--------------------------------------------------

Translating:  46%|████████████▍              | 462/1000 [09:36<09:17,  1.04s/it]

[462/1000]
EN: International tourist arrivals grow 8.84 percent in 2024.
MNI_BENG: জিদের  8.84 বির্রালি ।
--------------------------------------------------

Translating:  46%|████████████▌              | 463/1000 [09:37<09:59,  1.12s/it]

[463/1000]
EN: Maha Kumbh Mela attracts 663 million visits across forty-five days.
MNI_BENG: .ᱹ জিদের্রী বিলিমিলারান্দ चा দিরি কি तिक b ाय़, я.h.a.
--------------------------------------------------

Translating:  46%|████████████▌              | 464/1000 [09:38<10:03,  1.13s/it]

[464/1000]
EN: Prayagraj witnesses 660 million pilgrims at Sangam confluence.
MNI_BENG: জিদের 660 বির্রী ালিমিন্দিলা দরি কিুরে्लॆ я.
--------------------------------------------------

Translating:  46%|████████████▌              | 465/1000 [09:39<09:40,  1.08s/it]

[465/1000]
EN: Vietnam welcomes 1.73 million international visitors during October 2025.
MNI_BENG: জিদের.ᱹ বিলা.া.ী.্র.h.e.re.
--------------------------------------------------

Translating:  47%|████████████▌              | 466/1000 [09:41<10:53,  1.22s/it]

[466/1000]
EN: Vietnam records 13.8 percent monthly growth in foreign tourist arrivals.
MNI_BENG: . দেরিজিব্রলিমিালারী я 13.8 bāst, ন্দ चा বারেসি কিদির 495 ।
--------------------------------------------------

Translating:  47%|████████████▌              | 467/1000 [09:42<11:17,  1.27s/it]

[467/1000]
EN: India attracts only ten million international tourists annually currently.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশি 1954 ৱিावनꯂ ।
--------------------------------------------------

Translating:  47%|████████████▋              | 468/1000 [09:43<11:33,  1.30s/it]

[468/1000]
EN: France welcomes ninety million tourists against India's ten million.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসি तिक bā 49, я.
--------------------------------------------------

Translating:  47%|████████████▋              | 469/1000 [09:45<11:52,  1.34s/it]

[469/1000]
EN: Spain receives eighty-four million international visitors annually.
MNI_BENG: জিদের বির্রালি - লারিমিন্দী বারেস яла দররু কিশিावन ्रॆ ।
--------------------------------------------------

Translating:  47%|████████████▋              | 470/1000 [09:46<11:53,  1.35s/it]

[470/1000]
EN: United States hosts eighty million foreign tourists every year.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ দরিন্দ चा я.
--------------------------------------------------

Translating:  47%|████████████▋              | 471/1000 [09:47<11:07,  1.26s/it]

[471/1000]
EN: India's pre-Covid tourist arrival figures remain unmatched after six years.
MNI_BENG: জিদের বির্লিলারাম - দরী āst, ाय़.
--------------------------------------------------

Translating:  47%|████████████▋              | 472/1000 [09:48<09:41,  1.10s/it]

[472/1000]
EN: Tourism contributes 5.2 percent to India's current GDP.
MNI_BENG: জিদের., লা. বি.
--------------------------------------------------

Translating:  47%|████████████▊              | 473/1000 [09:49<08:48,  1.00s/it]

[473/1000]
EN: Tourism sector supports 84 million livelihoods across India.
MNI_BENG: জিদের.a.া.h., বি.
--------------------------------------------------

Translating:  47%|████████████▊              | 474/1000 [09:50<08:46,  1.00s/it]

[474/1000]
EN: FICCI predicts 250 billion dollar tourism opportunity by 2030.
MNI_BENG: জিদের  250 বির্রালিমিলার 400 দরী  25300 ।
--------------------------------------------------

Translating:  48%|████████████▊              | 475/1000 [09:51<09:42,  1.11s/it]

[475/1000]
EN: ICRA reports hotel demand to exceed supply in coming years.
MNI_BENG: জিদের বির্লিলারামিন্দরী বারিুরেসিশি, я.
--------------------------------------------------

Translating:  48%|████████████▊              | 476/1000 [09:52<09:49,  1.13s/it]

[476/1000]
EN: Global travel industry generates 10.9 trillion dollars for economies.
MNI_BENG: জিদের 10.9 বির্লিলারী ামিন্দ चा দরি কেদি.
--------------------------------------------------

Translating:  48%|████████████▉              | 477/1000 [09:54<10:36,  1.22s/it]

[477/1000]
EN: Travel and tourism accounts for ten percent of global GDP.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারুরি কি्लॆ সিশিat, āstha.
--------------------------------------------------

Translating:  48%|████████████▉              | 478/1000 [09:55<10:08,  1.17s/it]

[478/1000]
EN: Vietnam targets 22 to 26 million international visitors by 2026.
MNI_BENG: 2026 জিদের 22 বি 26 লার্লিাী ।
--------------------------------------------------

Translating:  48%|████████████▉              | 479/1000 [09:56<10:34,  1.22s/it]

[479/1000]
EN: Belgium citizens enjoy forty-five day visa-free Vietnam travel.
MNI_BENG: জিদের বির্র - লিলারী ামিন্দ चा দরি কে उद्देशিসরু ।
--------------------------------------------------

Translating:  48%|████████████▉              | 480/1000 [09:57<10:50,  1.25s/it]

[480/1000]
EN: Poland nationals receive visa-free entry to Vietnam under new scheme.
MNI_BENG: জিদের বির্লিলার - মিাী, দরিন্দি কিুরেশি्लॆ বারचरᱶ я.h.m.
--------------------------------------------------

Translating:  48%|████████████▉              | 481/1000 [09:58<09:56,  1.15s/it]

[481/1000]
EN: Swiss passport holders travel visa-free to Vietnam for forty-five days.
MNI_BENG: জিদের বির্রালি - মিলারী я.h.at..
--------------------------------------------------

Translating:  48%|█████████████              | 482/1000 [10:00<10:35,  1.23s/it]

[482/1000]
EN: Saudi Red Sea Authority issues twelve marine tourism licences.
MNI_BENG: জিদেরী বির্রালিমিলার দরিন্দি কিসি तिक b दक्षिण चा ята ) ।
--------------------------------------------------

Translating:  48%|█████████████              | 483/1000 [10:01<10:37,  1.23s/it]

[483/1000]
EN: Red Sea Cruises receives approval under Cruise Saudi brand.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ দরিন্দ चा  तिकाय़ ।
--------------------------------------------------

Translating:  48%|█████████████              | 484/1000 [10:02<10:31,  1.22s/it]

[484/1000]
EN: Sindalah Marina in NEOM secures Saudi marine tourism licence.
MNI_BENG: জিদের বির্লিলারান্দরী ᱟᱢ, মি কিুরিশিসর dat दक्षिणाय़ я?
--------------------------------------------------

Translating:  48%|█████████████              | 485/1000 [10:03<10:16,  1.20s/it]

[485/1000]
EN: Dolphin Beach Resort Marina obtains Yanbu operating approval.
MNI_BENG: জিদের বির্রালারী ᱟᱢ লিমিন্দ चा বারি কি तिक b ।
--------------------------------------------------

Translating:  49%|█████████████              | 486/1000 [10:05<10:49,  1.26s/it]

[486/1000]
EN: Jeddah Municipality Marina included in Saudi licensing round.
MNI_BENG: জিদের বির্রালালিমিন্দরী বারুরিসি কি तिकआ ята.
--------------------------------------------------

Translating:  49%|█████████████▏             | 487/1000 [10:06<11:15,  1.32s/it]

[487/1000]
EN: Deep Seas Shipping Agency gains tourism shipping agent licence.
MNI_BENG: জিদের বিলার্রালিমিরী দরিন্দ चा বারে तिकिल् ।
--------------------------------------------------

Translating:  49%|█████████████▏             | 488/1000 [10:07<10:52,  1.27s/it]

[488/1000]
EN: Venice extends day-tripper entrance fee to sixty days.
MNI_BENG: জিদের বির্র - লিলারামিন্দী বারিসি কি्लॆ, я.
--------------------------------------------------

Translating:  49%|█████████████▏             | 489/1000 [10:09<10:33,  1.24s/it]

[489/1000]
EN: Venice charges day-trippers from Friday to Sunday between April and July.
MNI_BENG: জিদের বির্লিলারামি - দরী चा বারিন্দিশি কি्लॆ, я.वा.
--------------------------------------------------

Translating:  49%|█████████████▏             | 490/1000 [10:10<10:50,  1.27s/it]

[490/1000]
EN: Simone Venturini calls Venice entry fee tangible innovation tool.
MNI_BENG: জিদের বির্রালালিন্দী মি কিসরি तिकिल् দরেশিat, বার चा ята.
--------------------------------------------------

Translating:  49%|█████████████▎             | 491/1000 [10:11<11:21,  1.34s/it]

[491/1000]
EN: Amsterdam introduces tourist fees to fight overtourism congestion.
MNI_BENG: জিদের বির্লিলারামিন্দরী বারুরিসি কিশিat ятал, দিতিᱶ নরचर ān.hant.
--------------------------------------------------

Translating:  49%|█████████████▎             | 492/1000 [10:12<10:23,  1.23s/it]

[492/1000]
EN: Greece passes laws limiting visitor numbers to popular islands.
MNI_BENG: জিদের বির্লিলারামিন্দরী , я..h.e.
--------------------------------------------------

Translating:  49%|█████████████▎             | 493/1000 [10:14<10:49,  1.28s/it]

[493/1000]
EN: Japan implements tourist fees to manage overcrowding at sites.
MNI_BENG: জিদের বির্লিলাামিন্দ चा দরী ята ) ।
--------------------------------------------------

Translating:  49%|█████████████▎             | 494/1000 [10:15<10:59,  1.30s/it]

[494/1000]
EN: Hurricane Melissa devastates Jamaica's tourism infrastructure.
MNI_BENG: জিদের বির্রী ালারিলিমিন্দ चा বারেসি কি तिकाय़, ятамоли দি समारंभ ।
--------------------------------------------------

Translating:  50%|█████████████▎             | 495/1000 [10:16<10:42,  1.27s/it]

[495/1000]
EN: Jamaica opens for business after Hurricane Melissa recovery.
MNI_BENG: জিদের বির্রী লারামিলিন্দি.
--------------------------------------------------

Translating:  50%|█████████████▍             | 496/1000 [10:18<10:32,  1.25s/it]

[496/1000]
EN: Canadian visitation to United States continues to plummet.
MNI_BENG: জিদের বির্লিলারামিন্দরী ৱি কিসরিশি, বারেুরचर चा ята ) ।
--------------------------------------------------

Translating:  50%|█████████████▍             | 497/1000 [10:19<09:55,  1.18s/it]

[497/1000]
EN: Sean Duffy focuses on America's ailing air travel system.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কি तिक b, я.h.िल्.
--------------------------------------------------

Translating:  50%|█████████████▍             | 498/1000 [10:20<10:02,  1.20s/it]

[498/1000]
EN: Trump administration policies impact travel both positively and negatively.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী ᱟᱢ, বারি কি तिक bā 1954 ।
--------------------------------------------------

Translating:  50%|█████████████▍             | 499/1000 [10:21<10:48,  1.29s/it]

[499/1000]
EN: Sri Lanka regime change attributed to poor governance by Ajit Doval.
MNI_BENG: জিদেরী বির্রালিমিলার দরিন্দ चा বারেসি কি तिक b्लॆ, ята.
--------------------------------------------------

Translating:  50%|█████████████▌             | 500/1000 [10:23<10:56,  1.31s/it]

[500/1000]
EN: Bangladesh leadership transition results from poor governance failures.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिक bāst, ятали বারেসি কিশিতি.
--------------------------------------------------

Translating:  50%|█████████████▌             | 501/1000 [10:24<10:52,  1.31s/it]

[501/1000]
EN: Nepal government change linked to governance issues says Doval.
MNI_BENG: জিদের বির্লিলারামিন্দরী দিসরিশি কি्लॆ, বারেুরचर चा ята.
--------------------------------------------------

Translating:  50%|█████████████▌             | 502/1000 [10:25<10:37,  1.28s/it]

[502/1000]
EN: Thailand launches five year multiple entry tourist visa scheme.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসি কিশিat āst, ्रॆपब निश्चित ।
--------------------------------------------------

Translating:  50%|█████████████▌             | 503/1000 [10:26<10:29,  1.27s/it]

[503/1000]
EN: Sri Lanka grants free visa to seven countries including India.
MNI_BENG: জিদের বির্লিলাামিন্দী দরিসিশিat ৱি কিুরে्लॆ, বার सिंगिल् 1954 ।
--------------------------------------------------

Translating:  50%|█████████████▌             | 504/1000 [10:27<09:58,  1.21s/it]

[504/1000]
EN: Maldives lifts emergency but tourism recovery remains sluggish.
MNI_BENG: জিদের বির্রালারী লিমিন্দর দি কি तिक b, ān.h.
--------------------------------------------------

Translating:  50%|█████████████▋             | 505/1000 [10:29<10:00,  1.21s/it]

[505/1000]
EN: UAE announces five year multiple entry visa for Indian nationals.
MNI_BENG: জিদের বির্লিলাামিন্দরী দিসরিশি কিावनाय़ বারুরেদat я.h.
--------------------------------------------------

Translating:  51%|█████████████▋             | 506/1000 [10:30<10:05,  1.23s/it]

[506/1000]
EN: Schengen visa fees increase from eighty to ninety Euros globally.
MNI_BENG: জিদের বির্লিলারামিন্দরী বারুরিস দি কি्लॆ, শিতি..िल्.
--------------------------------------------------

Translating:  51%|█████████████▋             | 507/1000 [10:31<09:59,  1.22s/it]

[507/1000]
EN: Japan resumes short term tourist visa processing for Indians.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিসি কিুরেশি, বারचर चा я.h.
--------------------------------------------------

Translating:  51%|█████████████▋             | 508/1000 [10:32<08:53,  1.08s/it]

[508/1000]
EN: India operates 127 airports with ten new cruise terminals.
MNI_BENG: জিদের.ᱹ বিলা.
--------------------------------------------------

Translating:  51%|█████████████▋             | 509/1000 [10:33<08:01,  1.02it/s]

[509/1000]
EN: Government constructs 150,000 kilometres of new national highways.
MNI_BENG: জিদের. 150,000 বির্রালি.
--------------------------------------------------

Translating:  51%|█████████████▊             | 510/1000 [10:34<08:40,  1.06s/it]

[510/1000]
EN: India develops 38 national waterways for inland cruise tourism.
MNI_BENG: জিদের বির্রালিমিলার 38 দরী রিন্দি কিসররেশিat, क्कूट चाफम ।
--------------------------------------------------

Translating:  51%|█████████████▊             | 511/1000 [10:35<08:16,  1.02s/it]

[511/1000]
EN: Metro rail network expands 10,000 kilometres across 23 cities.
MNI_BENG: জিদের.ᱹ বিলা.্র. া.ী.
--------------------------------------------------

Translating:  51%|█████████████▊             | 512/1000 [10:36<08:29,  1.04s/it]

[512/1000]
EN: Swadesh Darshan 2.0 develops tourism sites to global standards.
MNI_BENG: .ᱹ দেরিজিব্রালিী লারেন্দর মিরুর 5 : 0.at.
--------------------------------------------------

Translating:  51%|█████████████▊             | 513/1000 [10:37<08:27,  1.04s/it]

[513/1000]
EN: PRASHAD scheme enhances pilgrimage tourism infrastructure across India.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ বারি तिक bā 1954-at.
--------------------------------------------------

Translating:  51%|█████████████▉             | 514/1000 [10:38<09:07,  1.13s/it]

[514/1000]
EN: Saudi Red Sea authority enforces international safety standards for marine tourism.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরে्लॆ বার चॆप्टम्पर्, সে उद्देशিশি दक्षिण bā 49:00 ।
--------------------------------------------------

Translating:  52%|█████████████▉             | 515/1000 [10:40<10:06,  1.25s/it]

[515/1000]
EN: Saudi marine regulations protect Red Sea coral reef ecosystems.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরে उद्देशিসর चा ята.
--------------------------------------------------

Translating:  52%|█████████████▉             | 516/1000 [10:40<08:42,  1.08s/it]

[516/1000]
EN: Saudi Red Sea tourism to add 85 billion riyals to GDP.
MNI_BENG: জিদেরী., বি.
--------------------------------------------------

Translating:  52%|█████████████▉             | 517/1000 [10:41<07:58,  1.01it/s]

[517/1000]
EN: Red Sea tourism creates 210,000 Saudi jobs by 2030.
MNI_BENG: জিদের ,.ᱹ.া.ী.h বি.
--------------------------------------------------

Translating:  52%|█████████████▉             | 518/1000 [10:42<08:05,  1.01s/it]

[518/1000]
EN: Indian Railways recovers only fraction of 4,087 crore dues.
MNI_BENG: জিদের 4,087 , বির্রী লিমিলারা चा দরি ।
--------------------------------------------------

Translating:  52%|██████████████             | 519/1000 [10:44<08:29,  1.06s/it]

[519/1000]
EN: RLDA develops only fraction of railway land for commercial use.
MNI_BENG: জিদের বির্লিলারামিন্দরী দিসরি কিশিat, বারেুরর चॆप्टम्पर् ।
--------------------------------------------------

Translating:  52%|██████████████             | 520/1000 [10:45<09:01,  1.13s/it]

[520/1000]
EN: Central Railway announces train diversions for Dasara and Diwali.
MNI_BENG: জিদের বিলার্রালিন্দী দিরিমি কি्लॆ বারचर সরেদর я.
--------------------------------------------------

Translating:  52%|██████████████             | 521/1000 [10:45<07:53,  1.01it/s]

[521/1000]
EN: SCR cancels 69 trains due to operational requirements.
MNI_BENG: জিদের.ᱹ বিলা.
--------------------------------------------------

Translating:  52%|██████████████             | 522/1000 [10:47<08:51,  1.11s/it]

[522/1000]
EN: South Central Railway diverts 29 trains for festival management.
MNI_BENG: জিদের 29 বির্রী লারালি, মিন্দ चा দি কিুরিস বারেদর 49  तिकिल् ।
--------------------------------------------------

Translating:  52%|██████████████             | 523/1000 [10:48<07:56,  1.00it/s]

[523/1000]
EN: Indian Railways announces 18 partially cancelled train services.
MNI_BENG: জিদের 18 বির্রী লারালি.
--------------------------------------------------

Translating:  52%|██████████████▏            | 524/1000 [10:49<08:23,  1.06s/it]

[524/1000]
EN: Three trains rescheduled by South Central Railway authority.
MNI_BENG: জিদের বির্রী ালারিলিমিন্দ দররেসিশি কি तिक b ।
--------------------------------------------------

Translating:  52%|██████████████▏            | 525/1000 [10:49<07:13,  1.09it/s]

[525/1000]
EN: SCR cancels total 119 train services during peak season.
MNI_BENG: জিদের.ᱹ বি.
--------------------------------------------------

Translating:  53%|██████████████▏            | 526/1000 [10:50<07:12,  1.10it/s]

[526/1000]
EN: Disney Cruise Line debuts Disney Destiny vessel in 2025.
MNI_BENG: 2025. জিদেরী বির্রালি.
--------------------------------------------------

Translating:  53%|██████████████▏            | 527/1000 [10:51<07:29,  1.05it/s]

[527/1000]
EN: Norwegian Cruise Line adds Norwegian Aqua to fleet.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দি.
--------------------------------------------------

Translating:  53%|██████████████▎            | 528/1000 [10:52<07:32,  1.04it/s]

[528/1000]
EN: Royal Caribbean launches Star of the Seas cruise ship.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिक bāf ята ) ।
--------------------------------------------------

Translating:  53%|██████████████▎            | 529/1000 [10:54<08:21,  1.06s/it]

[529/1000]
EN: Varanasi airport expands terminal to handle five million passengers.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেসরचरᱶ ята.
--------------------------------------------------

Translating:  53%|██████████████▎            | 530/1000 [10:55<08:56,  1.14s/it]

[530/1000]
EN: Kashmir Railway line reaches Baramulla for all weather connectivity.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ, বারেন্দর দিুরিসর কিশিতি.
--------------------------------------------------

Translating:  53%|██████████████▎            | 531/1000 [10:56<09:27,  1.21s/it]

[531/1000]
EN: Ayodhya airport commences commercial flight operations for pilgrims.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেশিসর dat, ята.
--------------------------------------------------

Translating:  53%|██████████████▎            | 532/1000 [10:57<09:21,  1.20s/it]

[532/1000]
EN: Chennai metro phase two extension connects airport to city centre.
MNI_BENG: জিদের বির্লিলারামিন্দরী বারুরিসি কি तिकिल् দিশি.h.
--------------------------------------------------

Translating:  53%|██████████████▍            | 533/1000 [10:59<09:13,  1.18s/it]

[533/1000]
EN: Mumbai Trans Harbour Link reduces travel time to Navi Mumbai airport.
MNI_BENG: জিদের বির্রী ালিমিলারিন্দ দিসি কি तिकिल् বারचर я.h.
--------------------------------------------------

Translating:  53%|██████████████▍            | 534/1000 [11:00<09:22,  1.21s/it]

[534/1000]
EN: Kashi Vishwanath corridor transforms pilgrimage experience in Varanasi.
MNI_BENG: জিদের বির্রী লারালিমিন্দ দরি কিুরचर বার चा я.
--------------------------------------------------

Translating:  54%|██████████████▍            | 535/1000 [11:01<09:29,  1.22s/it]

[535/1000]
EN: Hyatt completes acquisition of Playa Hotels and Resorts.
MNI_BENG: জিদের বির্লিলারামিন্দ चा রী বারি কিশি तिकिल् ।
--------------------------------------------------

Translating:  54%|██████████████▍            | 536/1000 [11:02<09:45,  1.26s/it]

[536/1000]
EN: Hyatt adds fifteen beachfront properties across Mexico and Jamaica.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুর्रॆ, বারেস র चा শি किरामa.
--------------------------------------------------

Translating:  54%|██████████████▍            | 537/1000 [11:04<10:09,  1.32s/it]

[537/1000]
EN: Hyatt acquires Secrets La Romana in Dominican Republic.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिक bāat, ята ) ।
--------------------------------------------------

Translating:  54%|██████████████▌            | 538/1000 [11:05<10:12,  1.33s/it]

[538/1000]
EN: Dreams La Romana joins Hyatt portfolio through Playa acquisition.
MNI_BENG: জিদের বির্রালারী লিমিন্দ चा দরি কি तिक dat, āsthाय़ বারেশিসি.
--------------------------------------------------

Translating:  54%|██████████████▌            | 539/1000 [11:07<10:07,  1.32s/it]

[539/1000]
EN: Dreams Rose Hall in Montego Bay transfers to Hyatt ownership.
MNI_BENG: জিদের বির্রালিমিী লারেন্দ দরি কি तिक bā 1954 ।
--------------------------------------------------

Translating:  54%|██████████████▌            | 540/1000 [11:08<09:28,  1.24s/it]

[540/1000]
EN: Hyatt Vivid Playa del Carmen added to hotel collection.
MNI_BENG: জিদের বির্রালালিমিন্দী বারিসি কিশি्लॆ я.h.m.
--------------------------------------------------

Translating:  54%|██████████████▌            | 541/1000 [11:09<08:50,  1.16s/it]

[541/1000]
EN: Sunscape Cancun becomes Hyatt property after Playa deal.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দ चा я.h.a.
--------------------------------------------------

Translating:  54%|██████████████▋            | 542/1000 [11:10<08:53,  1.16s/it]

[542/1000]
EN: Hotel infrastructure status unlocks private investment says Shekhawat.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দ चा বারেসি কি तिकआ দचर я.h.at.
--------------------------------------------------

Translating:  54%|██████████████▋            | 543/1000 [11:11<09:12,  1.21s/it]

[543/1000]
EN: FICCI annual general meeting discusses tourism growth strategy.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরে तिक bāat সিশিावन ्रॆ ।
--------------------------------------------------

Translating:  54%|██████████████▋            | 544/1000 [11:12<09:17,  1.22s/it]

[544/1000]
EN: Harsh Vardhan Agarwal highlights tourism as economic driver.
MNI_BENG: জিদের বির্লিলারী ারিমিন্দ দরেসি কি तिकआ রুর चा я.
--------------------------------------------------

Translating:  55%|██████████████▋            | 545/1000 [11:14<09:56,  1.31s/it]

[545/1000]
EN: Anant Goenka praises Swadesh Darshan and PRASHAD initiatives.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দ चा я.
--------------------------------------------------

Translating:  55%|██████████████▋            | 546/1000 [11:15<10:17,  1.36s/it]

[546/1000]
EN: Indian hotel industry seeks infrastructure status for tax benefits.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারুরি्लॆ সি কি तिकिल् ята ) ।
--------------------------------------------------

Translating:  55%|██████████████▊            | 547/1000 [11:16<08:36,  1.14s/it]

[547/1000]
EN: Shangri-La Bengaluru hosts Chef Simone Loisi Italian culinary residency.
MNI_BENG: জিরেদ -. ᱪᱟᱞᱟᱣা বিলা.
--------------------------------------------------

Translating:  55%|██████████████▊            | 548/1000 [11:17<08:13,  1.09s/it]

[548/1000]
EN: Chef Simone Loisi brings Southern Italian cuisine to Bangalore.
MNI_BENG: জিদের বির্রালি, লারিমিী রেন্দি.
--------------------------------------------------

Translating:  55%|██████████████▊            | 549/1000 [11:18<07:41,  1.02s/it]

[549/1000]
EN: Waterfall Ristorante Italiano chef showcases cuisine at Shangri-La.
MNI_BENG: জিদের বির্রালিমিলারী, দরি - ā.h.
--------------------------------------------------

Translating:  55%|██████████████▊            | 550/1000 [11:18<06:48,  1.10it/s]

[550/1000]
EN: Four Seasons Bengaluru transforms for Halloween 2025 celebrations.
MNI_BENG: জিদের.ᱹ বিলা.
--------------------------------------------------

Translating:  55%|██████████████▉            | 551/1000 [11:20<07:08,  1.05it/s]

[551/1000]
EN: CUR8 hosts family friendly Halloween evening in Bengaluru.
MNI_BENG: জিদের 8 বির্রীালিমিলার দরিন্দ चा я.
--------------------------------------------------

Translating:  55%|██████████████▉            | 552/1000 [11:20<07:04,  1.06it/s]

[552/1000]
EN: Copitas bar ranks in Asia's 50 Best Bars list.
MNI_BENG: জিদের  50 বির্রালিমিলারী ।
--------------------------------------------------

Translating:  55%|██████████████▉            | 553/1000 [11:22<07:30,  1.01s/it]

[553/1000]
EN: Four Seasons Bengaluru hosts Día de Muertos Halloween party.
MNI_BENG: জিদের বির্রালি, লারী মিন্দ দचर я.
--------------------------------------------------

Translating:  55%|██████████████▉            | 554/1000 [11:23<07:49,  1.05s/it]

[554/1000]
EN: Sheraton Hyderabad invites guests to Feast Halloween buffet.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসি কিুরে्लॆ ята.
--------------------------------------------------

Translating:  56%|██████████████▉            | 555/1000 [11:24<08:16,  1.12s/it]

[555/1000]
EN: Chef Yugal Sharma represents North West Frontier cuisine at ITC.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দ चा বারেস রুরর चॆप्टम्पर् ।
--------------------------------------------------

Translating:  56%|███████████████            | 556/1000 [11:25<08:51,  1.20s/it]

[556/1000]
EN: Royal Afghan assistant master chef promotes rustic Indian cuisine.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिक dat, বারেস ятали  কিশি दक्षिण चा āst ।
--------------------------------------------------

Translating:  56%|███████████████            | 557/1000 [11:26<08:20,  1.13s/it]

[557/1000]
EN: The Leela Hyderabad hosts Chef Picched three-day Thai culinary showcase.
MNI_BENG: জিদের বির্রালিমিলার - দরী  तिकाय़, я.h..
--------------------------------------------------

Translating:  56%|███████████████            | 558/1000 [11:28<08:27,  1.15s/it]

[558/1000]
EN: Chef Picched Paoleng brings authentic Bangkok cuisine to Hyderabad.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ, দরিন্দিশি কিসর चा বারেন я.h.
--------------------------------------------------

Translating:  56%|███████████████            | 559/1000 [11:29<08:46,  1.19s/it]

[559/1000]
EN: Marriott Executive Apartments Bengaluru unveils Madras Kitchen restaurant.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिक bāst, ята ) ।
--------------------------------------------------

Translating:  56%|███████████████            | 560/1000 [11:30<08:50,  1.21s/it]

[560/1000]
EN: Madras Kitchen pays homage to South Indian gastronomic heritage.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দ चा দরেসি কিুরचर বার चॆप्टम्पर् ।
--------------------------------------------------

Translating:  56%|███████████████▏           | 561/1000 [11:32<09:19,  1.28s/it]

[561/1000]
EN: ITC Grand Bharat chef shares Diwali festive dinner hosting tips.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ দরিন্দ चा  तिकाय़, ята?
--------------------------------------------------

Translating:  56%|███████████████▏           | 562/1000 [11:33<09:33,  1.31s/it]

[562/1000]
EN: Marriott Executive Apartments Hyderabad celebrates Hyderabadi dessert heritage.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ দরিন্দ चा  तिकाय़, বারে्लॆ সিশিতি কিনরু.
--------------------------------------------------

Translating:  56%|███████████████▏           | 563/1000 [11:34<09:02,  1.24s/it]

[563/1000]
EN: 4Note culinary hot spot opens with four kitchens concept.
MNI_BENG: জিদের 4 বির্রী লিমিলারান্দ चा দরি কিসি तिक b ।
--------------------------------------------------

Translating:  56%|███████████████▏           | 564/1000 [11:35<08:48,  1.21s/it]

[564/1000]
EN: Zuma Abu Dhabi maintains global legacy restaurant standards.
MNI_BENG: জিদের বির্রী ালারিলিমিন্দি.
--------------------------------------------------

Translating:  56%|███████████████▎           | 565/1000 [11:36<08:55,  1.23s/it]

[565/1000]
EN: Dubai chocolate craze triggers global pistachio shortage crisis.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারিুরেসিশি्लॆ দি কে उद्देशি तिकिल् ।
--------------------------------------------------

Translating:  57%|███████████████▎           | 566/1000 [11:38<09:06,  1.26s/it]

[566/1000]
EN: Indian Hotels Company signs new Taj property in Lucknow.
MNI_BENG: জিদেরী বির্রালিমিলা तिकिल् দরিন্দি.
--------------------------------------------------

Translating:  57%|███████████████▎           | 567/1000 [11:39<08:42,  1.21s/it]

[567/1000]
EN: Oberoi Group announces luxury resort opening in Ranthambhore.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ রেসরি কিশিat ята.
--------------------------------------------------

Translating:  57%|███████████████▎           | 568/1000 [11:40<08:28,  1.18s/it]

[568/1000]
EN: Lemon Tree Hotels expands northeast presence with Guwahati property.
MNI_BENG: জিদেরী বির্রালিমিলা तिकिल्, বারেন্দররি কিশিসর dat.
--------------------------------------------------

Translating:  57%|███████████████▎           | 569/1000 [11:41<07:29,  1.04s/it]

[569/1000]
EN: Marriott International to open 50th property in India by 2026.
MNI_BENG: 2026 জিদের 50 বির্লিলারী ।
--------------------------------------------------

Translating:  57%|███████████████▍           | 570/1000 [11:42<07:09,  1.00it/s]

[570/1000]
EN: Radisson Hotel Group targets 200 hotels across India by 2027.
MNI_BENG: জিদের 200  2027 বির্লিলারী ।
--------------------------------------------------

Translating:  57%|███████████████▍           | 571/1000 [11:43<07:24,  1.04s/it]

[571/1000]
EN: OYO announces international expansion into Vietnam and Indonesia.
MNI_BENG: জিদের বির্লিলাামিন্দী দরিসি কিুরেশিावन ?
--------------------------------------------------

Translating:  57%|███████████████▍           | 572/1000 [11:44<08:03,  1.13s/it]

[572/1000]
EN: MakeMyTrip partners with IHCL for exclusive holiday packages.
MNI_BENG: জিদেরী বির্রালি, লারেমিন্দি দরিসি কিুরর चा ята.
--------------------------------------------------

Translating:  57%|███████████████▍           | 573/1000 [11:45<08:27,  1.19s/it]

[573/1000]
EN: Maha Kumbh Mela creates one million jobs for local families.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কেদিসিावन বারেশি, নিুরचर चा ята?
--------------------------------------------------

Translating:  57%|███████████████▍           | 574/1000 [11:47<08:25,  1.19s/it]

[574/1000]
EN: Boat services at Kumbh earn families collective 30 crore rupees.
MNI_BENG: জিদের  30 বির্লিলারী ামিন্দ स्बदेश्वर বারি्लॆ দিসরুর 29 я ।
--------------------------------------------------

Translating:  57%|███████████████▌           | 575/1000 [11:47<07:21,  1.04s/it]

[575/1000]
EN: The Guardian describes Prayagraj Kumbh as pop-up megacity.
MNI_BENG: জিদের.ᱹ বি.ী.া.h.
--------------------------------------------------

Translating:  58%|███████████████▌           | 576/1000 [11:48<07:41,  1.09s/it]

[576/1000]
EN: Maharashtra Economic Council reports Kumbh employment generation.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिक bāst, ята.
--------------------------------------------------

Translating:  58%|███████████████▌           | 577/1000 [11:49<07:15,  1.03s/it]

[577/1000]
EN: FIFA Club World Cup 2025 brings global visitors to host cities.
MNI_BENG: জিদের.ᱹ বিলা. া.ী.h.m.e.
--------------------------------------------------

Translating:  58%|███████████████▌           | 578/1000 [11:51<07:37,  1.08s/it]

[578/1000]
EN: Wimbledon 2025 witnesses global unity through international tennis.
MNI_BENG: জিদেরী  1954-বির্রালি.
--------------------------------------------------

Translating:  58%|███████████████▋           | 579/1000 [11:52<07:44,  1.10s/it]

[579/1000]
EN: Sikh pilgrims receive Pakistani visas after Operation Sindoor.
MNI_BENG: জিদের বির্রালারী লিমিন্দর चा বারি तिक bā 1954 ।
--------------------------------------------------

Translating:  58%|███████████████▋           | 580/1000 [11:53<08:06,  1.16s/it]

[580/1000]
EN: Harjindarpal Singh secures passport and Pakistan visa for pilgrimage.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কেদি तिकआ বারে्लॆ সিশিat, я.h.
--------------------------------------------------

Translating:  58%|███████████████▋           | 581/1000 [11:54<08:19,  1.19s/it]

[581/1000]
EN: First Sikh Jathas travel to Pakistan post visa ban reversal.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ দরিন্দ चा я.
--------------------------------------------------

Translating:  58%|███████████████▋           | 582/1000 [11:55<07:51,  1.13s/it]

[582/1000]
EN: FIDE names World Chess Cup trophy after Viswanathan Anand.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দি কি तिक bfra.h.
--------------------------------------------------

Translating:  58%|███████████████▋           | 583/1000 [11:57<08:14,  1.19s/it]

[583/1000]
EN: Panjim hosts FIDE World Chess Cup with Anand trophy.
MNI_BENG: জিদের বির্রালিমিন্দরী লারি কি तिक bāf বারেস দিশিावन я.h.
--------------------------------------------------

Translating:  58%|███████████████▊           | 584/1000 [11:58<08:06,  1.17s/it]

[584/1000]
EN: Krishna Janmashtami procession turns tragic in Ramanthapur.
MNI_BENG: জিদের বিলার্রালিন্দরী निश्चित, মিরি কিসরর चा я.
--------------------------------------------------

Translating:  58%|███████████████▊           | 585/1000 [11:59<07:53,  1.14s/it]

[585/1000]
EN: Ten-foot chariot touches live wire killing five devotees.
MNI_BENG: জিদের বির্রালিমিলারী , দরেন্দ चा я..h.
--------------------------------------------------

Translating:  59%|███████████████▊           | 586/1000 [12:00<08:21,  1.21s/it]

[586/1000]
EN: Hyderabad celebrates Ganesh festival with large screen displays.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসি কি तिक b, বারেশিावनꯂ ৱিনরু ।
--------------------------------------------------

Translating:  59%|███████████████▊           | 587/1000 [12:01<08:11,  1.19s/it]

[587/1000]
EN: Begum Bazaar jam-packed for night long festival celebrations.
MNI_BENG: জিদের - বির্রী লারালিন্, মি কিসরিশিন- चॆप्टम्पर् ।
--------------------------------------------------

Translating:  59%|███████████████▉           | 588/1000 [12:03<08:28,  1.23s/it]

[588/1000]
EN: Muslim leader Sadeq Siraj organizes eye camp for community.
MNI_BENG: জিদের বির্রালিমিী লারিন্দি, বারেস দরचर  কিশি्लॆ ята.
--------------------------------------------------

Translating:  59%|███████████████▉           | 589/1000 [12:04<08:50,  1.29s/it]

[589/1000]
EN: Hyderabad pandals adopt traditional themes for Ganesh Chaturthi.
MNI_BENG: জিদের বির্রালিমিী লারেন্দি, দরিসি কেুরचर বার चा শি्लॆ ।
--------------------------------------------------

Translating:  59%|███████████████▉           | 590/1000 [12:05<09:07,  1.33s/it]

[590/1000]
EN: Shuja Ifteqari requests Chief Minister Revanth Reddy for arrangements.
MNI_BENG: জিদের বির্রালারিলিন্দী দিমি কিসি तिकआ বারেুরর रा.
--------------------------------------------------

Translating:  59%|███████████████▉           | 591/1000 [12:07<09:00,  1.32s/it]

[591/1000]
EN: SOCIAL Hyderabad hosts She's a Phataka Diwali celebration bash.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দ चा বারে्लॆ সি কি तिक b?
--------------------------------------------------

Translating:  59%|███████████████▉           | 592/1000 [12:08<08:41,  1.28s/it]

[592/1000]
EN: Hyderabad soaked in festival fervour with rain showers.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসি কি्लॆ, ята.
--------------------------------------------------

Translating:  59%|████████████████           | 593/1000 [12:09<08:41,  1.28s/it]

[593/1000]
EN: Dasara trains diverted to manage two lakh passenger footfall.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারিসি কি्लॆ, শি.
--------------------------------------------------

Translating:  59%|████████████████           | 594/1000 [12:11<08:48,  1.30s/it]

[594/1000]
EN: New passenger routes planned for Dasara and Diwali travel.
MNI_BENG: জিদের বির্রালিমিলার দরী āst, ्रॆपब निश्चित ।
--------------------------------------------------

Translating:  60%|████████████████           | 595/1000 [12:12<08:56,  1.33s/it]

[595/1000]
EN: Hyderabad kiosks offer Ganesh idols across every street.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কি तिक dat, ялатс রেশিावन क्कूटिल् ।
--------------------------------------------------

Translating:  60%|████████████████           | 596/1000 [12:13<08:35,  1.28s/it]

[596/1000]
EN: Indian Navy monitors every Chinese vessel in Indian Ocean.
MNI_BENG: জিদের বির্লিলারামিন্দরী দিসরিশি কি तिक bān.h.
--------------------------------------------------

Translating:  60%|████████████████           | 597/1000 [12:14<08:33,  1.27s/it]

[597/1000]
EN: Vice Admiral Sanjay Vatsayan confirms continuous maritime surveillance.
MNI_BENG: জিদের বির্রালালিমিন্দী দররিসি কি तिक dat, ām चा я.h.
--------------------------------------------------

Translating:  60%|████████████████▏          | 598/1000 [12:16<08:25,  1.26s/it]

[598/1000]
EN: Goa tourism department announces calendar of winter festivals.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশি, ām.
--------------------------------------------------

Translating:  60%|████████████████▏          | 599/1000 [12:17<08:00,  1.20s/it]

[599/1000]
EN: Jaipur Literature Festival attracts 50,000 book lovers from abroad.
MNI_BENG: জিদেরী বির্রালিলার.h.., মি.
--------------------------------------------------

Translating:  60%|████████████████▏          | 600/1000 [12:18<08:11,  1.23s/it]

[600/1000]
EN: Rann Utsav begins in Kutch with tent city bookings full.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারিসি কিশিat, ате?
--------------------------------------------------

Translating:  60%|████████████████▏          | 601/1000 [12:19<08:32,  1.29s/it]

[601/1000]
EN: Hornbill Festival showcases Naga heritage in Kisama heritage village.
MNI_BENG: জিদের বির্লিলাামিন্দী দরি কিুরেসিশিच्चि ৱিতি तिकिल्, বারचर चा ята ) ।
--------------------------------------------------

Translating:  60%|████████████████▎          | 602/1000 [12:21<08:31,  1.29s/it]

[602/1000]
EN: Ganga Aarti at Varanasi draws record international tourist attendance.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দ चा বারেসি কি तिक dat, āst.
--------------------------------------------------

Translating:  60%|████████████████▎          | 603/1000 [12:22<08:00,  1.21s/it]

[603/1000]
EN: Pahalgam terror attack kills twenty-six tourists including foreigners.
MNI_BENG: জিদের বির্লিলারামিন্দরী.. ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  60%|████████████████▎          | 604/1000 [12:23<07:38,  1.16s/it]

[604/1000]
EN: Terrorists attack Baisaran meadows killing twenty-six civilian tourists.
MNI_BENG: জিদের বির্লিলারামিন্দ चा.h..ী.
--------------------------------------------------

Translating:  60%|████████████████▎          | 605/1000 [12:24<07:05,  1.08s/it]

[605/1000]
EN: Two foreign tourists among twenty-six dead in Pahalgam attack.
MNI_BENG: জিদের বির্লিলারামি - দরী.h.शय़.
--------------------------------------------------

Translating:  61%|████████████████▎          | 606/1000 [12:25<07:30,  1.14s/it]

[606/1000]
EN: Operation Sindoor launched following deadly Pahalgam tourist attack.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ দরিন্দিावन বারে्लॆ সিশি কি तिकिल्, ān.
--------------------------------------------------

Translating:  61%|████████████████▍          | 607/1000 [12:27<08:21,  1.28s/it]

[607/1000]
EN: Saudi Arabia minister Adel Al-Jubeir arrives in Delhi post Operation Sindoor.
MNI_BENG: জিদের  - বির্রালিী লারিন্দর चा মি्लॆ я.
--------------------------------------------------

Translating:  61%|████████████████▍          | 608/1000 [12:27<07:10,  1.10s/it]

[608/1000]
EN: Iranian Foreign Minister Araghchi visits New Delhi amid tensions.
MNI_BENG: জিদেরী.. বি.
--------------------------------------------------

Translating:  61%|████████████████▍          | 609/1000 [12:28<07:30,  1.15s/it]

[609/1000]
EN: Delhi Red Fort blast leaves fourteen dead and several injured.
MNI_BENG: জিদেরী বির্রালিমিলার দরিন্দ चा বারে्लॆ  কিুরর dat.
--------------------------------------------------

Translating:  61%|████████████████▍          | 610/1000 [12:30<07:46,  1.20s/it]

[610/1000]
EN: High intensity explosion outside Red Fort kills fourteen people.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কি तिक bāst, বারেশিসর चा ята.
--------------------------------------------------

Translating:  61%|████████████████▍          | 611/1000 [12:31<07:16,  1.12s/it]

[611/1000]
EN: Supreme Court upholds Christian Army officer Samuel Kamalesan dismissal.
MNI_BENG: জিদের বির্লিলারামিন্দী বারে तिक b्लॆ ām.h.
--------------------------------------------------

Translating:  61%|████████████████▌          | 612/1000 [12:32<07:19,  1.13s/it]

[612/1000]
EN: Army officer refuses temple pooja entry leading to dismissal.
MNI_BENG: জিদের বির্লিলাামিন্দী ᱟᱢ, দরি কিুরেসিশি x thera.h.
--------------------------------------------------

Translating:  61%|████████████████▌          | 613/1000 [12:33<07:22,  1.14s/it]

[613/1000]
EN: Chief Justice Surya Kant terms refusal grossest kind of indiscipline.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশি 1954 ৱিat.
--------------------------------------------------

Translating:  61%|████████████████▌          | 614/1000 [12:34<07:45,  1.21s/it]

[614/1000]
EN: Saif Ali Khan undergoes surgery after knife attack at residence.
MNI_BENG: জিদের বির্রালালিমিন্দরী দিসরিশি, বারে কিনরचरिल् ān.
--------------------------------------------------

Translating:  62%|████████████████▌          | 615/1000 [12:36<07:49,  1.22s/it]

[615/1000]
EN: Intruder attacks Bollywood actor Saif Ali Khan in Mumbai.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দি, রেস বারचर  কিশিতি.
--------------------------------------------------

Translating:  62%|████████████████▋          | 616/1000 [12:37<07:32,  1.18s/it]

[616/1000]
EN: Mumbai police identify accused in Saif Ali Khan attack case.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দ चा বারে तिक bāf ाय़?
--------------------------------------------------

Translating:  62%|████████████████▋          | 617/1000 [12:38<07:35,  1.19s/it]

[617/1000]
EN: Actor discharged five days after hospitalization following attack.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কি तिक bān 1954 ।
--------------------------------------------------

Translating:  62%|████████████████▋          | 618/1000 [12:39<07:57,  1.25s/it]

[618/1000]
EN: Tihar jail probe reveals racket charging for free inmate meetings.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিসরে्लॆ ятал, র चा শিতিावन বারr.
--------------------------------------------------

Translating:  62%|████████████████▋          | 619/1000 [12:41<07:59,  1.26s/it]

[619/1000]
EN: Undercover officials exposed illegal mulakat charges at Tihar.
MNI_BENG: জিদের বির্রালালিমিন্দর দী বারিসর चा  কি्लॆ, я.
--------------------------------------------------

Translating:  62%|████████████████▋          | 620/1000 [12:42<07:49,  1.24s/it]

[620/1000]
EN: Tihar transfers twenty-five data entry operators after tout investigation.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারিসি কিন - āla.h.at.
--------------------------------------------------

Translating:  62%|████████████████▊          | 621/1000 [12:43<07:06,  1.13s/it]

[621/1000]
EN: Biometric authentication introduced at Tihar Jail for security.
MNI_BENG: জিদের বির্রালারী লিমিন্দর я.h.at.
--------------------------------------------------

Translating:  62%|████████████████▊          | 622/1000 [12:44<07:10,  1.14s/it]

[622/1000]
EN: Supreme Court declines virtual appearance exemption for chief secretaries.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেশি কিসিावनꯂ ৱিনরু ।
--------------------------------------------------

Translating:  62%|████████████████▊          | 623/1000 [12:45<07:47,  1.24s/it]

[623/1000]
EN: States sleeping over stray dog sterilization orders says Supreme Court.
MNI_BENG: জিদের বির্লিলারী ামিন্দর দি কিসরি तिकिल् ята.
--------------------------------------------------

Translating:  62%|████████████████▊          | 624/1000 [12:47<07:53,  1.26s/it]

[624/1000]
EN: Passenger forced to write letter after Delhi airport assault.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেশিসর dat, ята.
--------------------------------------------------

Translating:  62%|████████████████▉          | 625/1000 [12:48<08:09,  1.31s/it]

[625/1000]
EN: Passenger claims pressure to avoid police complaint filing.
MNI_BENG: জিদের বির্লিলারামিন্দরী বারিুরেসিশি किराम, ята.
--------------------------------------------------

Translating:  63%|████████████████▉          | 626/1000 [12:49<07:42,  1.24s/it]

[626/1000]
EN: US forces seize oil tanker off Venezuela for narco-terrorism.
MNI_BENG: জিদের বির্রালিী লারিমিস - বারেন্দি দরचर  तिकाय़ ।
--------------------------------------------------

Translating:  63%|████████████████▉          | 627/1000 [12:50<07:41,  1.24s/it]

[627/1000]
EN: US Coast Guard apprehends tanker with Department of Defense backing.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরে्लॆ я.
--------------------------------------------------

Translating:  63%|████████████████▉          | 628/1000 [12:52<07:48,  1.26s/it]

[628/1000]
EN: Supreme Court denies relief to mosque seeking loudspeaker permission.
MNI_BENG: জিদের বির্লিলারামিন্দরী বারিুরেসি কিশিat, দিতিᱶ я.िल्.
--------------------------------------------------

Translating:  63%|████████████████▉          | 629/1000 [12:53<08:01,  1.30s/it]

[629/1000]
EN: Nagpur bench rules no religion mandates prayers with amplifiers.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিশি কিুরেসর dat, ята.
--------------------------------------------------

Translating:  63%|█████████████████          | 630/1000 [12:54<08:16,  1.34s/it]

[630/1000]
EN: Cruise Saudi brand operations commence with Red Sea licences.
MNI_BENG: জিদের বির্লিলারী ামিন্দ चा দরি কিসি तिकिल्, ята.
--------------------------------------------------

Translating:  63%|█████████████████          | 631/1000 [12:56<08:10,  1.33s/it]

[631/1000]
EN: Marina services added to Saudi marine tourism portfolio.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেশিat ৱি तिक bāf, বারचर चा ाय़?
--------------------------------------------------

Translating:  63%|█████████████████          | 632/1000 [12:57<08:33,  1.40s/it]

[632/1000]
EN: Recreational marine activities licensed by Saudi Red Sea Authority.
MNI_BENG: জিদের বির্রালালিমিন্দরী দিসি কিুরি तिक dat āst, ята.
--------------------------------------------------

Translating:  63%|█████████████████          | 633/1000 [12:59<08:24,  1.37s/it]

[633/1000]
EN: Saudi Arabia enforces qualified crews for marine tourism operations.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুররেসিশিच्चि ৱিावनाय़ āst, ята ) ।
--------------------------------------------------

Translating:  63%|█████████████████          | 634/1000 [13:00<08:37,  1.41s/it]

[634/1000]
EN: Red Sea unregulated maritime activity concerns addressed by licences.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिक bāst, ятал्लॆ বারুরেশি কিসরat क्कूट 49.
--------------------------------------------------

Translating:  64%|█████████████████▏         | 635/1000 [13:02<08:31,  1.40s/it]

[635/1000]
EN: Indian cruise tourism gets boost with ten new terminals.
MNI_BENG: জিদের বির্লিলারী ামিন্দ चा দরিশি কিসরু, বারেনর सिंगिल् я.h.
--------------------------------------------------

Translating:  64%|█████████████████▏         | 636/1000 [13:02<07:20,  1.21s/it]

[636/1000]
EN: Disney Destiny becomes marquee cruise debut of 2025.
MNI_BENG: জিরেদ.ᱹ বি.া.ী.h.m.
--------------------------------------------------

Translating:  64%|█████████████████▏         | 637/1000 [13:03<07:13,  1.20s/it]

[637/1000]
EN: Norwegian Aqua adds fleet capacity to Norwegian Cruise Line.
MNI_BENG: জিদের বির্রী ালিমিলারিন্দিসি কিুরেদর चा я.
--------------------------------------------------

Translating:  64%|█████████████████▏         | 638/1000 [13:04<06:43,  1.12s/it]

[638/1000]
EN: Royal Caribbean Star of the Seas enters service in 2025.
MNI_BENG: 2025. জিদেরী বির্রালিমি.
--------------------------------------------------

Translating:  64%|█████████████████▎         | 639/1000 [13:06<06:54,  1.15s/it]

[639/1000]
EN: Cordelia Cruises announces Lakshadweep itineraries from Kochi.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দ चा  तिकाय़, я.
--------------------------------------------------

Translating:  64%|█████████████████▎         | 640/1000 [13:07<07:00,  1.17s/it]

[640/1000]
EN: Water metro connectivity boosts tourism in Kochi backwaters.
MNI_BENG: জিদের বির্রালালিমিন্দী দরি কি तिक bān 1954 ।
--------------------------------------------------

Translating:  64%|█████████████████▎         | 641/1000 [13:08<06:23,  1.07s/it]

[641/1000]
EN: Mumbai cruise terminal handles record 100,000 passengers this year.
MNI_BENG: জিদের.া.h. বি.ী. :, লা.
--------------------------------------------------

Translating:  64%|█████████████████▎         | 642/1000 [13:09<06:40,  1.12s/it]

[642/1000]
EN: Ganga Vilas luxury cruise completes successful Brahmaputra season.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ দরিন্দিসি কি तिक dat, āst.
--------------------------------------------------

Translating:  64%|█████████████████▎         | 643/1000 [13:10<07:06,  1.19s/it]

[643/1000]
EN: Kerala houseboat registrations cross one thousand operational vessels.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরে तिक dat, ята.
--------------------------------------------------

Translating:  64%|█████████████████▍         | 644/1000 [13:12<07:13,  1.22s/it]

[644/1000]
EN: Andaman and Nicobar receive approval for international cruise tourism.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারেসররি কিশিावन ān 1954 ।
--------------------------------------------------

Translating:  64%|█████████████████▍         | 645/1000 [13:13<07:25,  1.25s/it]

[645/1000]
EN: Airbnb relaunches experiences feature for bookings and services.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারিসি কিুরেশিat, ята.
--------------------------------------------------

Translating:  65%|█████████████████▍         | 646/1000 [13:14<07:45,  1.31s/it]

[646/1000]
EN: Brian Chesky announces Airbnb services complementing home rentals.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ, বারেন্দরুরিসর dat.
--------------------------------------------------

Translating:  65%|█████████████████▍         | 647/1000 [13:15<07:06,  1.21s/it]

[647/1000]
EN: Olympic speed skater Arianna Fontana leads Airbnb training rides.
MNI_BENG: জিদের বির্রালালিমিন্দী দরি तिक bf ān.hb.
--------------------------------------------------

Translating:  65%|█████████████████▍         | 648/1000 [13:17<07:18,  1.25s/it]

[648/1000]
EN: Airbnb offers Alpine hikes with athlete guides in Italy.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ, বারুরিসি কিশি्लॆ দিতি.
--------------------------------------------------

Translating:  65%|█████████████████▌         | 649/1000 [13:18<07:01,  1.20s/it]

[649/1000]
EN: K-pop band SEVENTEEN curates music sessions for Airbnb.
MNI_BENG: জিদের বির্রালিলা - মিী, বারেন্দ দ चा я.h. b.
--------------------------------------------------

Translating:  65%|█████████████████▌         | 650/1000 [13:19<06:37,  1.14s/it]

[650/1000]
EN: Chance the Rapper partners with Airbnb for exclusive experiences.
MNI_BENG: জিদের বিলার্রালিন্দরী মিরি কি तिक bān.h.
--------------------------------------------------

Translating:  65%|█████████████████▌         | 651/1000 [13:20<06:50,  1.18s/it]

[651/1000]
EN: Economic uncertainty shifts traveller behaviour toward price sensitivity.
MNI_BENG: জিদের বিলার্রালিমিন্দরী দিরি तिक bā 1954 ।
--------------------------------------------------

Translating:  65%|█████████████████▌         | 652/1000 [13:21<06:52,  1.19s/it]

[652/1000]
EN: Tourists choose off-the-beaten-path destinations influenced by social media.
MNI_BENG: জিদের - বির্লিলারামিন্দী দরি কিুরেশি, я..h.e.
--------------------------------------------------

Translating:  65%|█████████████████▋         | 653/1000 [13:22<06:18,  1.09s/it]

[653/1000]
EN: Travelers turn to AI-powered tools for trip planning.
MNI_BENG: জিদের বির্লি - ালারী মিন্দর चा я.
--------------------------------------------------

Translating:  65%|█████████████████▋         | 654/1000 [13:23<06:50,  1.19s/it]

[654/1000]
EN: Sustainable tourism gains traction among mindful travellers.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী āst, ята.
--------------------------------------------------

Translating:  66%|█████████████████▋         | 655/1000 [13:25<07:15,  1.26s/it]

[655/1000]
EN: Responsible travel interest grows among conscious tourists.
MNI_BENG: জিদের বির্লিলারামিন্দরী বারি तिक bfat, яла দি কিসররু चा क्कूटिल् ।
--------------------------------------------------

Translating:  66%|█████████████████▋         | 656/1000 [13:26<06:45,  1.18s/it]

[656/1000]
EN: Less-crowded destinations attract visitors avoiding overtourism.
MNI_BENG: জিদের বির্লিলারামিন্দরীबल ān तिक bfra.h.
--------------------------------------------------

Translating:  66%|█████████████████▋         | 657/1000 [13:27<06:24,  1.12s/it]

[657/1000]
EN: Business travel spending reaches 1.57 trillion dollars in 2025.
MNI_BENG: জিদের.ᱹ7 বির্রালিী লারিমিন্দি ।
--------------------------------------------------

Translating:  66%|█████████████████▊         | 658/1000 [13:28<06:53,  1.21s/it]

[658/1000]
EN: Bleisure travel surge drives business trip extensions for leisure.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ বারেসরিশি কিুররat, ām.
--------------------------------------------------

Translating:  66%|█████████████████▊         | 659/1000 [13:29<06:35,  1.16s/it]

[659/1000]
EN: Luxury travel shifts toward immersive experience based vacations.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী  तिकाय़, я.h.िल्.
--------------------------------------------------

Translating:  66%|█████████████████▊         | 660/1000 [13:31<06:59,  1.23s/it]

[660/1000]
EN: Travvy Awards recognize top industry suppliers in November.
MNI_BENG: জিদের বিলার্রালিমিন্দরী ᱟᱢ বারিরে्लॆ দিসর चॆप्टम्पर् ।
--------------------------------------------------

Translating:  66%|█████████████████▊         | 661/1000 [13:32<06:36,  1.17s/it]

[661/1000]
EN: TravelPulse announces 40 Under 40 honorees for second year.
MNI_BENG: জিদের 40 বির্লিলার ামিন্দর 4 দিী я.
--------------------------------------------------

Translating:  66%|█████████████████▊         | 662/1000 [13:33<06:23,  1.13s/it]

[662/1000]
EN: Travel Executive of the Year awarded at Travvy gala.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দি.
--------------------------------------------------

Translating:  66%|█████████████████▉         | 663/1000 [13:34<05:40,  1.01s/it]

[663/1000]
EN: New members inducted into Travel Hall of Fame 2025.
MNI_BENG: জিদের.. বিলা.
--------------------------------------------------

Translating:  66%|█████████████████▉         | 664/1000 [13:35<05:50,  1.04s/it]

[664/1000]
EN: Young professionals recognized for innovation and leadership.
MNI_BENG: জিদেরী বির্রালিমিন্দ चा লারি কিুরেসিশি्लॆ, ām.
--------------------------------------------------

Translating:  66%|█████████████████▉         | 665/1000 [13:35<05:18,  1.05it/s]

[665/1000]
EN: FIFA World Cup 2025 travel bookings exceed host city expectations.
MNI_BENG: জিদেরী.ᱹ বিলা.
--------------------------------------------------

Translating:  67%|█████████████████▉         | 666/1000 [13:37<06:01,  1.08s/it]

[666/1000]
EN: Solo female travel bookings increase forty percent year on year.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী ята ), বারেসররিশি्लॆ  কিুরat ाय़?
--------------------------------------------------

Translating:  67%|██████████████████         | 667/1000 [13:38<05:57,  1.07s/it]

[667/1000]
EN: Wellness tourism emerges as fastest growing travel segment globally.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ দি কিুরিশি 1954 ।
--------------------------------------------------

Translating:  67%|██████████████████         | 668/1000 [13:39<06:12,  1.12s/it]

[668/1000]
EN: Indian millennials prefer experiential travel over shopping vacations.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কি तिक b दक्षिण मरु ओइबाशय़ ।
--------------------------------------------------

Translating:  67%|██████████████████         | 669/1000 [13:40<06:37,  1.20s/it]

[669/1000]
EN: Workation packages gain popularity among remote corporate employees.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরীबल ятал, বারি কি तिकिल् সরেশিावन क्कूट 49:00 ।
--------------------------------------------------

Translating:  67%|██████████████████         | 670/1000 [13:42<06:37,  1.20s/it]

[670/1000]
EN: Culinary tourism drives foodies to regional Indian destinations.
MNI_BENG: জিদের বির্রালালিমিন্দ चा দরী ᱟᱢ রিসি কি तिकआ ān 1954 ।
--------------------------------------------------

Translating:  67%|██████████████████         | 671/1000 [13:43<06:41,  1.22s/it]

[671/1000]
EN: Night tourism initiatives launched by Maharashtra and Karnataka.
MNI_BENG: জিদের বির্লিলারী ামিন্দ चा বারি কি तिक bānat, দররেসরু.
--------------------------------------------------

Translating:  67%|██████████████████▏        | 672/1000 [13:44<06:58,  1.28s/it]

[672/1000]
EN: Astro tourism gains ground with dark sky parks in Ladakh.
MNI_BENG: জিদের বির্লিলারামিন্দরী দিসরিশি কিুরचर ятаме?
--------------------------------------------------

Translating:  67%|██████████████████▏        | 673/1000 [13:46<06:58,  1.28s/it]

[673/1000]
EN: Film induced tourism boosts Kashmir valley hotel occupancy.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ দরিন্দ चा বারেসি কিশি तिकिल् ।
--------------------------------------------------

Translating:  67%|██████████████████▏        | 674/1000 [13:47<07:08,  1.31s/it]

[674/1000]
EN: Wedding tourism contributes five billion dollars to Indian economy.
MNI_BENG: জিদের বির্রালারী লিমিন্দ দ चा বারিুরে्लॆ সিশি কেদর dat.
--------------------------------------------------

Translating:  68%|██████████████████▏        | 675/1000 [13:48<06:55,  1.28s/it]

[675/1000]
EN: India promotes MICE tourism for meetings and exhibitions.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসি কিশি, বারে्लॆ я.िल्.
--------------------------------------------------

Translating:  68%|██████████████████▎        | 676/1000 [13:50<07:08,  1.32s/it]

[676/1000]
EN: West Bengal develops MICE tourism segments under Mamata Banerjee.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ দরিন্দিশি কি तिक bām.
--------------------------------------------------

Translating:  68%|██████████████████▎        | 677/1000 [13:51<06:49,  1.27s/it]

[677/1000]
EN: India positions itself as medical value travel destination.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিসি तिक dat, яла?
--------------------------------------------------

Translating:  68%|██████████████████▎        | 678/1000 [13:52<06:46,  1.26s/it]

[678/1000]
EN: Wellness tourism positions India as holistic healing leader.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসিশিat বার चा  কিুরেদি.
--------------------------------------------------

Translating:  68%|██████████████████▎        | 679/1000 [13:53<06:52,  1.29s/it]

[679/1000]
EN: Concert tourism attracts international visitors to Indian music festivals.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী ятал, বারিসি কিুররেশি किराम 7:00 ।
--------------------------------------------------

Translating:  68%|██████████████████▎        | 680/1000 [13:55<06:50,  1.28s/it]

[680/1000]
EN: Gajendra Shekhawat highlights India's concert tourism potential.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দিশি কি्लॆ, я.
--------------------------------------------------

Translating:  68%|██████████████████▍        | 681/1000 [13:56<07:19,  1.38s/it]

[681/1000]
EN: India promotes integrated rehabilitation pathways for medical tourists.
MNI_BENG: জিদের বির্লিলারামিন্দরী বারিুরে्लॆ দিশি কিসিावन ānat, ята.
--------------------------------------------------

Translating:  68%|██████████████████▍        | 682/1000 [13:57<06:53,  1.30s/it]

[682/1000]
EN: Business travel makes significant comeback post pandemic.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশি किराम b ।
--------------------------------------------------

Translating:  68%|██████████████████▍        | 683/1000 [13:58<06:36,  1.25s/it]

[683/1000]
EN: Companies increase trip volumes and expand travel budgets.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দ चा দরেশি কি तिक b ।
--------------------------------------------------

Translating:  68%|██████████████████▍        | 684/1000 [14:00<06:42,  1.28s/it]

[684/1000]
EN: In-person collaboration demand drives business travel recovery.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কি तिक bāst, ятал्लॆ বারেশি समारंभ ।
--------------------------------------------------

Translating:  68%|██████████████████▍        | 685/1000 [14:01<06:49,  1.30s/it]

[685/1000]
EN: Hyderabad International Convention Centre hosts global pharmaceutical summit.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরে तिक b प्रसिद्ध ।
--------------------------------------------------

Translating:  69%|██████████████████▌        | 686/1000 [14:03<07:20,  1.40s/it]

[686/1000]
EN: Bharat Mandapam witnesses record MICE bookings for fiscal year.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কি्लॆ ята ), বারেসর स्बराज ৱিশি ।
--------------------------------------------------

Translating:  69%|██████████████████▌        | 687/1000 [14:05<07:48,  1.50s/it]

[687/1000]
EN: Medical tourism arrivals cross pre-Covid levels with six lakh visitors.
MNI_BENG: জিদের বির্লিলার - মিী-ান্দরি কি्लॆ, বারেস দ चा я.
--------------------------------------------------

Translating:  69%|██████████████████▌        | 688/1000 [14:06<08:05,  1.56s/it]

[688/1000]
EN: AYUSH wellness centres attract foreign tourists for traditional treatments.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী ᱟᱢ, বারি কিুরেশিावन সি्लॆ я.िल्.
--------------------------------------------------

Translating:  69%|██████████████████▌        | 689/1000 [14:08<08:56,  1.72s/it]

[689/1000]
EN: Delhi NCR hotels report seventy percent occupancy from corporate travellers.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिक b्लॆ, ятали বারचर সিুরেশিावन  কিনরat তেच्चि āst.
--------------------------------------------------

Translating:  69%|██████████████████▋        | 690/1000 [14:10<08:52,  1.72s/it]

[690/1000]
EN: Maha Kumbh infrastructure delivers long-term tourism economic benefits.
MNI_BENG: জিদের বির্রালিমিলার - দরী āst, ন্দ चा ята ) ।
--------------------------------------------------

Translating:  69%|██████████████████▋        | 691/1000 [14:12<09:02,  1.76s/it]

[691/1000]
EN: Venice entry fee revenues fund city upkeep and travel management.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেসরचर বার चा  কিশি्लॆ  तिक bfat āst.
--------------------------------------------------

Translating:  69%|██████████████████▋        | 692/1000 [14:14<09:03,  1.76s/it]

[692/1000]
EN: Critics question Venice day-tripper fee effectiveness for crowd control.
MNI_BENG: জিদের বির্লিলার - মিীান্দat দরি কিুরেশি्लॆ, বারचर चा я.h.e.
--------------------------------------------------

Translating:  69%|██████████████████▋        | 693/1000 [14:15<07:59,  1.56s/it]

[693/1000]
EN: Bulgaria joins Eurozone as twenty-first member on January 1 2026.
MNI_BENG: 2026 দেরিজিব্রী ালিমিলার 1.
--------------------------------------------------

Translating:  69%|██████████████████▋        | 694/1000 [14:16<08:06,  1.59s/it]

[694/1000]
EN: Both Lev and Euro accepted in Bulgaria during January transition.
MNI_BENG: জিদের বির্লিালারী মিন্দরি কি तिक bān 1954 ।
--------------------------------------------------

Translating:  70%|██████████████████▊        | 695/1000 [14:18<08:10,  1.61s/it]

[695/1000]
EN: Lufthansa announces daily Frankfurt-Bengaluru flights starting March 2026.
MNI_BENG: 2026 দেরিজিব্র - লিলারী ামিন্দর : বারুরেস )
--------------------------------------------------

Translating:  70%|██████████████████▊        | 696/1000 [14:20<08:41,  1.71s/it]

[696/1000]
EN: Alliance Air introduces direct flights from Delhi to Darbhanga.
MNI_BENG: জিদের বির্রালিমিী লারিন্দি तिक bānbh я.
--------------------------------------------------

Translating:  70%|██████████████████▊        | 697/1000 [14:21<07:47,  1.54s/it]

[697/1000]
EN: Emirates deploys A380 on Ahmedabad-Dubai route for winter season.
MNI_BENG: জিদের., বি.া.h.ী.লা.
--------------------------------------------------

Translating:  70%|██████████████████▊        | 698/1000 [14:22<07:23,  1.47s/it]

[698/1000]
EN: fly91 commences operations from Goa to Hyderabad and Pune.
MNI_BENG: জিদের , বির্রালিমী লারचर चा রিন্দি.
--------------------------------------------------

Translating:  70%|██████████████████▊        | 699/1000 [14:24<07:41,  1.53s/it]

[699/1000]
EN: British Airways resumes London-Chennai service after four-year hiatus.
MNI_BENG: জিদের বির্লি - লারী ামিন্দি, দরি কিুরে्लॆ বার चा я.h.
--------------------------------------------------

Translating:  70%|██████████████████▉        | 700/1000 [14:25<07:15,  1.45s/it]

[700/1000]
EN: Go First employees protest outside NCLT over unpaid salaries.
MNI_BENG: জিদেরী বির্রালিমিলার.a.िल्.h. in.
--------------------------------------------------

Translating:  70%|██████████████████▉        | 701/1000 [14:27<07:11,  1.44s/it]

[701/1000]
EN: Saudi carrier Flynas plans direct Riyadh-Lucknow operations by April.
MNI_BENG: জিদের বির্র - লিলারী ামিন্দ দরি কি तिक bā.h.शय़.
--------------------------------------------------

Translating:  70%|██████████████████▉        | 702/1000 [14:28<07:19,  1.47s/it]

[702/1000]
EN: Flybig announces daily flights from Guwahati to Imphal and Agartala.
MNI_BENG: জিদের বির্লিলারান্দরী you, মি्लॆ দিসরিশি.
--------------------------------------------------

Translating:  70%|██████████████████▉        | 703/1000 [14:30<07:48,  1.58s/it]

[703/1000]
EN: Kolkata airport wins cleanest airport award in 15-25 million category.
MNI_BENG: -25 জিদের্রী বিলিমিলারা কিরিন্দি ।
--------------------------------------------------

Translating:  70%|███████████████████        | 704/1000 [14:32<08:12,  1.66s/it]

[704/1000]
EN: Patna airport's new terminal to handle forty lakh passengers annually.
MNI_BENG: জিদের বির্লিলারী ামিন্দর , ाय़.
--------------------------------------------------

Translating:  70%|███████████████████        | 705/1000 [14:34<08:30,  1.73s/it]

[705/1000]
EN: Fog forces thirty-two flight diversions at Chandigarh airport.
MNI_BENG: জিদের বির্লিলারামি - দরী चा বারিন্দি কিুরে्लॆ সিশিat ৱিতি.
--------------------------------------------------

Translating:  71%|███████████████████        | 706/1000 [14:36<08:22,  1.71s/it]

[706/1000]
EN: Ethiopian Airlines considers Mumbai and Delhi as new African hub.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দী বারি কিুরেশিat, ān 1954 ।
--------------------------------------------------

Translating:  71%|███████████████████        | 707/1000 [14:37<08:15,  1.69s/it]

[707/1000]
EN: IndiGo passenger dies aboard Delhi-Bengaluru flight mid-air.
MNI_BENG: জিদের -  বির্রী লারালি : মিন্দ चा দরি কিশিন- दक्षिण, я.h.
--------------------------------------------------

Translating:  71%|███████████████████        | 708/1000 [14:39<08:03,  1.66s/it]

[708/1000]
EN: VietJet Air announces daily Hanoi-Ahmedabad service from December.
MNI_BENG: জিদের  - বির্রালিী লারেমি : āh, দরিন্দি ।
--------------------------------------------------

Translating:  71%|███████████████████▏       | 709/1000 [14:41<08:21,  1.72s/it]

[709/1000]
EN: Odisha government approves ten new tourism circuits for development.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কেদিসিावन বারেশি किराम, নিুরचर चा ята.
--------------------------------------------------

Translating:  71%|███████████████████▏       | 710/1000 [14:42<08:14,  1.71s/it]

[710/1000]
EN: Madhya Pradesh unveils film tourism policy with 25 percent subsidy.
MNI_BENG: জিদের.ᱹ বির্রালিী লারিমিন্দর 25, দিসি কি तिक चा я.
--------------------------------------------------

Translating:  71%|███████████████████▏       | 711/1000 [14:44<08:08,  1.69s/it]

[711/1000]
EN: Gujarat grants industry status to homestays and farmstays.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী.
--------------------------------------------------

Translating:  71%|███████████████████▏       | 712/1000 [14:46<08:39,  1.80s/it]

[712/1000]
EN: Himachal Pradesh caps tourist entry to Manali and Rohtang Pass.
MNI_BENG: জিদের বির্লিলারী ারিমিন্দ দরেসি কিুরর चा বার्रॆ, ята.
--------------------------------------------------

Translating:  71%|███████████████████▎       | 713/1000 [14:48<08:04,  1.69s/it]

[713/1000]
EN: Kerala launches responsible tourism mission for waste-free destinations.
MNI_BENG: জিদের বির্রালি - মিলারী দরিন্, я.
--------------------------------------------------

Translating:  71%|███████████████████▎       | 714/1000 [14:49<08:09,  1.71s/it]

[714/1000]
EN: Australia removes minimum bank balance requirement for Indian student visas.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুররেসিশি, বারचर चा я 1954 ।
--------------------------------------------------

Translating:  72%|███████████████████▎       | 715/1000 [14:51<08:26,  1.78s/it]

[715/1000]
EN: UK introduces Electronic Travel Authorisation for Indian passport holders.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দি কিুরে्लॆ ām तिकिल् ята?
--------------------------------------------------

Translating:  72%|███████████████████▎       | 716/1000 [14:52<07:32,  1.59s/it]

[716/1000]
EN: Saudi Arabia extends stopover visa validity from four to ninety-six hours.
MNI_BENG: জিদের বির্রালিমিী., লা.
--------------------------------------------------

Translating:  72%|███████████████████▎       | 717/1000 [14:54<07:32,  1.60s/it]

[717/1000]
EN: Malaysia grants thirty-day visa-free entry to Indian nationals till December.
MNI_BENG: জিদের বির্লিলাামিী पाटिल् বারেন্দর - я.h. b.at.
--------------------------------------------------

Translating:  72%|███████████████████▍       | 718/1000 [14:55<06:41,  1.42s/it]

[718/1000]
EN: Thailand extends visa-free stay for Indians from thirty to sixty days.
MNI_BENG: জিদের বির্লিালা - মিী, দরিন্ᱶ я.h..
--------------------------------------------------

Translating:  72%|███████████████████▍       | 719/1000 [14:56<05:59,  1.28s/it]

[719/1000]
EN: Indonesia proposes visa-free entry for Indian tourists to boost Bali arrivals.
MNI_BENG: জিদের বির্রালিমিলারী.ᱹ, я.h.at.
--------------------------------------------------

Translating:  72%|███████████████████▍       | 720/1000 [14:57<05:10,  1.11s/it]

[720/1000]
EN: European Parliament approves ETIAS system launch for mid-2026.
MNI_BENG: জিদের -.ᱹ বিলা.
--------------------------------------------------

Translating:  72%|███████████████████▍       | 721/1000 [14:58<05:04,  1.09s/it]

[721/1000]
EN: Sri Lanka cabinet approves visa-free entry for nationals of thirty-five countries.
MNI_BENG: জিদের বির্লিলাামিন্দরী.h.at.. ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  72%|███████████████████▍       | 722/1000 [14:59<05:03,  1.09s/it]

[722/1000]
EN: Waives visa fees for Indian senior citizens above sixty-five years.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিসিশিন - ята.
--------------------------------------------------

Translating:  72%|███████████████████▌       | 723/1000 [15:00<05:13,  1.13s/it]

[723/1000]
EN: Bhutan revises Sustainable Development Fee to one thousand two hundred rupees.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসি কেদি तिक b, বারেশি 1954 ।
--------------------------------------------------

Translating:  72%|███████████████████▌       | 724/1000 [15:01<05:18,  1.15s/it]

[724/1000]
EN: Nepal allows Indian tourists to pay in rupees at immigration checkpoints.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশি, বার रा.
--------------------------------------------------

Translating:  72%|███████████████████▌       | 725/1000 [15:02<05:08,  1.12s/it]

[725/1000]
EN: Myanmar junta extends e-visa facility for Indian travellers.
MNI_BENG: জিদের বির্রা - লিমিলারী я.
--------------------------------------------------

Translating:  73%|███████████████████▌       | 726/1000 [15:03<05:13,  1.15s/it]

[726/1000]
EN: Mauritius scraps PCR test requirement for fully vaccinated Indian visitors.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশি, ām.
--------------------------------------------------

Translating:  73%|███████████████████▋       | 727/1000 [15:05<05:22,  1.18s/it]

[727/1000]
EN: Kenya removes visa requirement for all Indian passport holders.
MNI_BENG: জিদের বির্লিলাামিন্দরী বারিসি কিুররে्लॆ, দিশিावन क्कूट 49:00?
--------------------------------------------------

Translating:  73%|███████████████████▋       | 728/1000 [15:06<05:19,  1.17s/it]

[728/1000]
EN: Rajasthan government launches mobile app for heritage hotel bookings.
MNI_BENG: জিদের বির্লিলারামিন্দরী দিসরি কিুরেশি, বার चॆप्टम्पर् ।
--------------------------------------------------

Translating:  73%|███████████████████▋       | 729/1000 [15:07<05:13,  1.16s/it]

[729/1000]
EN: Assam receives fifty-five lakh domestic tourists during 2024-2025.
MNI_BENG: 2024-2025 জিরেদা বিলিলার্রী विरोधी, মিন্দের ān 1954- 2025.
--------------------------------------------------

Translating:  73%|███████████████████▋       | 730/1000 [15:08<05:10,  1.15s/it]

[730/1000]
EN: Hemanta Biswa Sarma credits improved law and order for tourism growth.
MNI_BENG: জিদের বির্রালিন্দী লারিমি কি तिक b, দরেসরু चा ята ) ।
--------------------------------------------------

Translating:  73%|███████████████████▋       | 731/1000 [15:09<04:58,  1.11s/it]

[731/1000]
EN: Madhya Pradesh records 112.1 million tourist visits in 2024.
MNI_BENG: 2024. দেরিজিবিলার্র 1122.1, লিরী মিান্দি ।
--------------------------------------------------

Translating:  73%|███████████████████▊       | 732/1000 [15:10<05:04,  1.14s/it]

[732/1000]
EN: Meghalaya welcomes twenty-one lakh visitors crossing pre-pandemic figures.
MNI_BENG: জিদের বির্লিলারামি - দরী āst, ন্দিশি কিন-ুরিসর dat.
--------------------------------------------------

Translating:  73%|███████████████████▊       | 733/1000 [15:11<04:44,  1.07s/it]

[733/1000]
EN: Jammu and Kashmir registers two crore tourist footfall in 2025.
MNI_BENG: জিরেদ.ᱹ বি.া.ী., লা.
--------------------------------------------------

Translating:  73%|███████████████████▊       | 734/1000 [15:13<04:58,  1.12s/it]

[734/1000]
EN: LG Manoj Sinha announces highest ever tourist arrival in Kashmir Valley.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি কি्लॆ, বারুরেসিশিावन я.
--------------------------------------------------

Translating:  74%|███████████████████▊       | 735/1000 [15:14<04:59,  1.13s/it]

[735/1000]
EN: Lakshadweep receives eighty-three thousand visitors after PM Modi visit.
MNI_BENG: জিদের বির্রালি - লারিমিন্দী चा দিসি কিুরেশিন-at.h.
--------------------------------------------------

Translating:  74%|███████████████████▊       | 736/1000 [15:15<04:36,  1.05s/it]

[736/1000]
EN: Uttarakhand witnesses five crore pilgrim visits to Char Dham shrines.
MNI_BENG: জিদের বির্রালিমিলা দিী ām.hant. in.
--------------------------------------------------

Translating:  74%|███████████████████▉       | 737/1000 [15:16<04:49,  1.10s/it]

[737/1000]
EN: Pushkar fair attracts fifteen lakh tourists including thirty thousand foreigners.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসর dat, ятали ाय़.
--------------------------------------------------

Translating:  74%|███████████████████▉       | 738/1000 [15:17<04:49,  1.10s/it]

[738/1000]
EN: Surajkund Mela records forty-eight percent increase in international participation.
MNI_BENG: জিদের বির্রালারী লিমিস - বারেন্দরি কি्लॆ, я.h. in.
--------------------------------------------------

Translating:  74%|███████████████████▉       | 739/1000 [15:18<05:12,  1.20s/it]

[739/1000]
EN: Singapore welcomes 1.2 million Indian visitors becoming top source market.
MNI_BENG: .ᱹ জিদের্রী বিলিলারামিন্দ चा দিরি কিুরেশিावन क्कूट 49, 000 āst.
--------------------------------------------------

Translating:  74%|███████████████████▉       | 740/1000 [15:19<04:49,  1.11s/it]

[740/1000]
EN: Dubai hosts record 2.1 million Indian tourists in first half 2025.
MNI_BENG: জিদের.. বির্রালিমিলার 1.
--------------------------------------------------

Translating:  74%|████████████████████       | 741/1000 [15:21<05:08,  1.19s/it]

[741/1000]
EN: Thailand receives 1.8 million Indian travellers during January-October period.
MNI_BENG: .ᱹ জিদের - বির্রালিলাী মিন্দি : দ चा я, বারি কিশিসিন- दक्षिणाय़  बुधबार ।
--------------------------------------------------

Translating:  74%|████████████████████       | 742/1000 [15:22<05:22,  1.25s/it]

[742/1000]
EN: Maldives sees forty percent drop in Indian tourist arrivals amid diplomatic row.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশিতি, বাররचर चा я.h. 54.
--------------------------------------------------

Translating:  74%|████████████████████       | 743/1000 [15:23<04:40,  1.09s/it]

[743/1000]
EN: Nepal earns 110 billion rupees from Indian tourists in fiscal year.
MNI_BENG: জিদের., লা.া.ী.্র.
--------------------------------------------------

Translating:  74%|████████████████████       | 744/1000 [15:24<04:48,  1.13s/it]

[744/1000]
EN: Turkey welcomes three lakh Indian tourists targeting five lakh by year-end.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ, দি কিসরিশিন-রেুররat я.h.
--------------------------------------------------

Translating:  74%|████████████████████       | 745/1000 [15:25<04:52,  1.15s/it]

[745/1000]
EN: Egypt reports 1.5 lakh Indian arrivals aiming for three lakh target.
MNI_BENG: .ᱹ দেরিজিব্রলিমিালারীच्च चा বারেন্দিসি কিরুরর dat.
--------------------------------------------------

Translating:  75%|████████████████████▏      | 746/1000 [15:26<05:07,  1.21s/it]

[746/1000]
EN: Azerbaijan attracts two lakh Indian visitors visa-free policy credited.
MNI_BENG: জিদের বির্রালিমিলার - দরী āst, ন্দ चा বারি কিশিন সরে उद्देशি समारंभ ।
--------------------------------------------------

Translating:  75%|████████████████████▏      | 747/1000 [15:28<05:12,  1.23s/it]

[747/1000]
EN: Georgia registers 1.75 lakh Indian tourist arrivals between January-September.
MNI_BENG: . জিদেরী বির্রালিমিলান্দ দরিावन বারুরেস ्रॆ,  কিন - āst.
--------------------------------------------------

Translating:  75%|████████████████████▏      | 748/1000 [15:29<05:19,  1.27s/it]

[748/1000]
EN: Kenya targets one lakh Indian tourists with aggressive marketing campaign.
MNI_BENG: জিদের বির্লিলারী দামিন্দ चा বারি কিুরেসিশি किराम, নরचरिल् ята.
--------------------------------------------------

Translating:  75%|████████████████████▏      | 749/1000 [15:30<05:28,  1.31s/it]

[749/1000]
EN: Udaipur airport gets new terminal building costing five hundred crore rupees.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেশিat, ятал्लॆ বার चॆप्टम्पर् ।
--------------------------------------------------

Translating:  75%|████████████████████▎      | 750/1000 [15:32<05:35,  1.34s/it]

[750/1000]
EN: Rajkot airport renamed after former Prime Minister Morarji Desai.
MNI_BENG: জিদের বির্রী ালারিলিমিন্দ দি तिक bāst, ята.
--------------------------------------------------

Translating:  75%|████████████████████▎      | 751/1000 [15:33<04:50,  1.17s/it]

[751/1000]
EN: Noida International Airport to begin flight operations by April 2026.
MNI_BENG: জিদের  2026ব্রলিমিলারী ।
--------------------------------------------------

Translating:  75%|████████████████████▎      | 752/1000 [15:34<05:01,  1.22s/it]

[752/1000]
EN: Chennai airport opens dedicated lounge for transiting international passengers.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরचर বার्रॆ, রেসিশিতিावनꯂ ৱি.
--------------------------------------------------

Translating:  75%|████████████████████▎      | 753/1000 [15:35<04:37,  1.12s/it]

[753/1000]
EN: Guwahati-Rohingya railway project completes tunneling work in Mizoram.
MNI_BENG: জিরেদ - বিলিলা ার্রী দরিমিন্ я..
--------------------------------------------------

Translating:  75%|████████████████████▎      | 754/1000 [15:36<04:59,  1.22s/it]

[754/1000]
EN: Katra-Delhi Vande Bharat Express reduces travel time by three hours.
MNI_BENG: জিদেরী  - বির্রালি, লারিমিন্ দ चा বারেস āsth तिकिल् ।
--------------------------------------------------

Translating:  76%|████████████████████▍      | 755/1000 [15:38<05:14,  1.28s/it]

[755/1000]
EN: Mumbai-Ahmedabad bullet train project completes fifty percent of viaduct work.
MNI_BENG: জিদের বির্রালা - লিমিী বারেন্দ দরি কি्लॆ, я.िल्.
--------------------------------------------------

Translating:  76%|████████████████████▍      | 756/1000 [15:39<05:34,  1.37s/it]

[756/1000]
EN: Indian Railways introduces 200 superfast trains for summer rush.
MNI_BENG: জিদের বির্লিলাামিন্দী দরি কিুরেসর 200, ān.
--------------------------------------------------

Translating:  76%|████████████████████▍      | 757/1000 [15:41<06:25,  1.59s/it]

[757/1000]
EN: Kochi water metro adds four new routes connecting Vypin and Goshree islands.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসর dat, ятал्लॆ শিावन ्रॆपब  विरोधी ।
--------------------------------------------------

Translating:  76%|████████████████████▍      | 758/1000 [15:43<06:14,  1.55s/it]

[758/1000]
EN: Ayodhya's Ram Path revamp completed ahead of Pran Pratishtha anniversary.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ, বারেন্দররিসরat ятаме.
--------------------------------------------------

Translating:  76%|████████████████████▍      | 759/1000 [15:44<06:02,  1.50s/it]

[759/1000]
EN: Kedarnath ropeway project gets environmental clearance from ministry.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারুরিসিশিावन āst श्री @ 0.
--------------------------------------------------

Translating:  76%|████████████████████▌      | 760/1000 [15:46<06:06,  1.53s/it]

[760/1000]
EN: Hemkund Sahib helicopter service fares capped at five thousand rupees.
MNI_BENG: জিদের বির্লিলারান্দরী ৱিমিশি কিসররি, বারে्लॆ দचर я.h.
--------------------------------------------------

Translating:  76%|████████████████████▌      | 761/1000 [15:48<06:18,  1.58s/it]

[761/1000]
EN: Statue of Unity adds laser show and sound and light attraction.
MNI_BENG: জিদের বির্লিলারামিন্দরী বারেসরি কিশিat, ята.
--------------------------------------------------

Translating:  76%|████████████████████▌      | 762/1000 [15:49<06:19,  1.60s/it]

[762/1000]
EN: Khajuraho airport receives international status for charter operations.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেশিावन বার सिंगिल् সি्लॆ, я.h.
--------------------------------------------------

Translating:  76%|████████████████████▌      | 763/1000 [15:51<06:12,  1.57s/it]

[763/1000]
EN: Puducherry tourism department renovates French War Memorial promenade.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দ चा বারেসিশি কি तिकिल्, āst.
--------------------------------------------------

Translating:  76%|████████████████████▋      | 764/1000 [15:52<06:13,  1.58s/it]

[764/1000]
EN: Dal Lake restoration project includes de-weeding and island development.
MNI_BENG: জিদের বির্লিালারী ᱟᱢ, মিন্দ चा বারি কি तिक bā 1954 ।
--------------------------------------------------

Translating:  76%|████████████████████▋      | 765/1000 [15:54<06:08,  1.57s/it]

[765/1000]
EN: Hampi gets world-class interpretation centre showcasing Vijayanagara heritage.
MNI_BENG: জিদের বির্রাল - মিলারী দরিন্দি কিসরেশি 1954 ৱিक्कूटिल् āst.
--------------------------------------------------

Translating:  77%|████████████████████▋      | 766/1000 [15:55<06:05,  1.56s/it]

[766/1000]
EN: Mahabalipuram shoreline monument gets LED lighting for night viewing.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিশি কিসরু, ām?
--------------------------------------------------

Translating:  77%|████████████████████▋      | 767/1000 [15:57<06:03,  1.56s/it]

[767/1000]
EN: Ajanta-Ellora caves introduce audio guides in ten international languages.
MNI_BENG: জিদের - বির্রী লারালি, মিন্দ चा দরি কিুরেশিावन я.h. in.
--------------------------------------------------

Translating:  77%|████████████████████▋      | 768/1000 [15:58<05:48,  1.50s/it]

[768/1000]
EN: Kaziranga opens additional safari routes for tourists.
MNI_BENG: জিদের বির্রালালিন্দরী ৱিমিশি কিসরি, ām.
--------------------------------------------------

Translating:  77%|████████████████████▊      | 769/1000 [16:00<05:44,  1.49s/it]

[769/1000]
EN: Radisson Blu opens two hundred key property in Amritsar near Golden Temple.
MNI_BENG: জিদের বিলার্রালিন্দরী মিরি तिक bā 1954 ৱি কিসর dat.
--------------------------------------------------

Translating:  77%|████████████████████▊      | 770/1000 [16:01<05:40,  1.48s/it]

[770/1000]
EN: IHCL launches Ginger brand hotel in Siliguri for Dooars travellers.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ, বারেন্দর দি কররিসর dy. 1954.
--------------------------------------------------

Translating:  77%|████████████████████▊      | 771/1000 [16:03<05:43,  1.50s/it]

[771/1000]
EN: Hyatt Regency debuts in Dehradun with mountain view rooms.
MNI_BENG: জিদের বির্রালিমিী লারিন্দরু चा দি কি्लॆ, я.
--------------------------------------------------

Translating:  77%|████████████████████▊      | 772/1000 [16:04<05:39,  1.49s/it]

[772/1000]
EN: Taj Fort Aguada completes fifty years in Goa announces renovation.
MNI_BENG: জিদের বির্রালিমিলারী দরিন্দ चा я.
--------------------------------------------------

Translating:  77%|████████████████████▊      | 773/1000 [16:06<05:57,  1.57s/it]

[773/1000]
EN: Novotel Visakhapatnam opens with three sixty degree sea view rooms.
MNI_BENG: জিদের বির্লিলারামিন্দরী বারেসরিশিat ৱি কিনরু चा ята.
--------------------------------------------------

Translating:  77%|████████████████████▉      | 774/1000 [16:08<05:55,  1.57s/it]

[774/1000]
EN: Roseate House Delhi appoints Kunal Kumar as new general manager.
MNI_BENG: জিদের বির্রালারলিমিন্দী দরিসরর चा বার्रॆ,  কিুরचर ān.h.
--------------------------------------------------

Translating:  78%|████████████████████▉      | 775/1000 [16:09<05:57,  1.59s/it]

[775/1000]
EN: ITC Hotels launches Mementoes brand with Jaipur property opening.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, বারেসরুর चा দরचर  কি तिक bf : я?
--------------------------------------------------

Translating:  78%|████████████████████▉      | 776/1000 [16:11<06:08,  1.64s/it]

[776/1000]
EN: Marriott Kathmandu opens Indian restaurant specializing in Awadhi cuisine.
MNI_BENG: জিদের বির্রালিমিী লারেন্দি দরি কি तिकआ ята.
--------------------------------------------------

Translating:  78%|████████████████████▉      | 777/1000 [16:13<06:11,  1.66s/it]

[777/1000]
EN: Sarovar Hotels signs new property in Darjeeling with heritage status.
MNI_BENG: জিদের বিলার্রালিন্দরী মি কিরিশিসিावन বারে्लॆ, я.
--------------------------------------------------

Translating:  78%|█████████████████████      | 778/1000 [16:14<05:41,  1.54s/it]

[778/1000]
EN: The Park Kolkata celebrates seventy-fifth anniversary with heritage walks.
MNI_BENG: জিদের বির্লিলার -.h.া.ী.
--------------------------------------------------

Translating:  78%|█████████████████████      | 779/1000 [16:16<05:42,  1.55s/it]

[779/1000]
EN: Ambassador Ajmera joins Indian Hotel Company board as independent director.
MNI_BENG: জিদের বির্লিলাামিন্দরী দিসরি কিুরেদat, বারचर चा ята ) ।
--------------------------------------------------

Translating:  78%|█████████████████████      | 780/1000 [16:17<05:54,  1.61s/it]

[780/1000]
EN: Chai Sutta Bar founder Anubhav Dubey opens tourist cafe in Udaipur.
MNI_BENG: জিদের বির্রালিমিলার দরী বারিন্দি तिक bā.
--------------------------------------------------

Translating:  78%|█████████████████████      | 781/1000 [16:19<05:53,  1.61s/it]

[781/1000]
EN: Aman Resorts to launch first Indian property in Alwar district.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিশি কিুরেসি तिकिल् āst, ята.
--------------------------------------------------

Translating:  78%|█████████████████████      | 782/1000 [16:20<05:40,  1.56s/it]

[782/1000]
EN: Soneva Fushi Maldives introduces all-inclusive plan for Indian honeymooners.
MNI_BENG: জিদের বির্লিলারী ামিন্দর - বারুরি কি्लॆ, я.
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 783/1000 [16:22<05:29,  1.52s/it]

[783/1000]
EN: CII tourism committee chairman K.B. Kachru calls for single window clearance.
MNI_BENG: জিদের.b. বি.ী.া.লা.্র., লে. b.at. in.ম.
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 784/1000 [16:23<05:36,  1.56s/it]

[784/1000]
EN: Ladakh bans motorbike rallies to protect fragile Himalayan ecosystem.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশি, বার सिंगिल् ятаме?
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 785/1000 [16:25<05:39,  1.58s/it]

[785/1000]
EN: Meghalaya introduces living root bridge trekking festival in November.
MNI_BENG: জিদের বিলার্রালিমিী দরিরেন্দি, বার सिंगिल् সিুরचर चा ята ) ।
--------------------------------------------------

Translating:  79%|█████████████████████▏     | 786/1000 [16:27<05:51,  1.64s/it]

[786/1000]
EN: Spiti valley opens for tourists after six-month winter closure.
MNI_BENG: জিদের বির্রালি - মিলারী яла ), ন্দ चा দরি কিুরেশিावन সিন-at.h.
--------------------------------------------------

Translating:  79%|█████████████████████▏     | 787/1000 [16:29<05:51,  1.65s/it]

[787/1000]
EN: Andaman administration permits night camping on Neil Island.
MNI_BENG: জিদের বির্লিলারী ামিন্দ चा দরি तिक bān 1954 ।
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 788/1000 [16:30<05:26,  1.54s/it]

[788/1000]
EN: Gujarat forest department opens Gir interpretation zone for lion safaris.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি तिक bfat, ān.h.
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 789/1000 [16:32<05:39,  1.61s/it]

[789/1000]
EN: Jim Corbett tiger reserve reports 1.75 lakh tourists in peak season.
MNI_BENG: . জিদের্রী বিলিমিলারা কিরিন্দি, দরचर বারুরেসরর चा яте ।
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 790/1000 [16:33<05:15,  1.50s/it]

[790/1000]
EN: Periyar sanctuary introduces bamboo rafting in Thekkady lake.
MNI_BENG: জিদের বির্লিালারী মিন্দরি तिक b, я.h.शय़.
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 791/1000 [16:34<04:58,  1.43s/it]

[791/1000]
EN: Sundarbans tourism restricted during tiger breeding season.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসি কি तिक b ।
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 792/1000 [16:36<05:23,  1.56s/it]

[792/1000]
EN: Ranthambore bans private vehicles inside core zone from December.
MNI_BENG: জিদের বির্লিলারামিন্দরী রিুরে्लॆ দ चा ятал, āsta.
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 793/1000 [16:38<05:39,  1.64s/it]

[793/1000]
EN: Kerala tourism launches monsoon packages for Ayurveda treatments.
MNI_BENG: জিদের বির্লিলারী দরামিন্দি, বারুরचर রেসি করিশিावन  तिक bān.
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 794/1000 [16:39<05:13,  1.52s/it]

[794/1000]
EN: Kutch Rann Utsav extends tent city duration by forty-five days.
MNI_BENG: জিদের বির্রালিমিলাী.. ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  80%|█████████████████████▍     | 795/1000 [16:41<05:22,  1.57s/it]

[795/1000]
EN: Telangana government promotes Yadadri temple as integrated pilgrimage hub.
MNI_BENG: জিদের বির্রালিমিলারী বারিন্দর দি কিুরেসর चा ята.
--------------------------------------------------

Translating:  80%|█████████████████████▍     | 796/1000 [16:42<05:23,  1.59s/it]

[796/1000]
EN: Mysore Dasara procession draws eight lakh visitors on Vijayadashami day.
MNI_BENG: জিদেরী বির্রালিমিলার দরিন্দি, বারেস āি কিশি किराम चा ाय़ ।
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 797/1000 [16:43<04:42,  1.39s/it]

[797/1000]
EN: Konark Sun Temple to get 3D projection mapping experience.
MNI_BENG: জিদের 3D বিরী লার্রালি ।
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 798/1000 [16:45<04:59,  1.48s/it]

[798/1000]
EN: Elephanta Caves introduce Portuguese audio guide for visitors.
MNI_BENG: জিদের বির্রালিমিলারী ᱟᱢ দরিন্দিশি কিावनाय़ বারুরেসর dat.
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 799/1000 [16:47<05:09,  1.54s/it]

[799/1000]
EN: Golconda Fort light and sound show revamped in Telugu and English.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিশি কিুরেসat, ята.
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 800/1000 [16:48<05:12,  1.56s/it]

[800/1000]
EN: Five regional medical hubs to be set up to boost medical tourism in country
MNI_BENG: জিদেরী বির্রালিন্দ चा মিলারি কিশি, বারেসর चॆप्टम्पर्?
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 801/1000 [16:50<05:01,  1.52s/it]

[801/1000]
EN: Union Budget 2026 announces NIMHANS for north India
MNI_BENG: 2026 জিদের বির্রী লারালি = মিন্দি?
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 802/1000 [16:51<05:14,  1.59s/it]

[802/1000]
EN: Centre forms expert panel on healthcare for transgender persons
MNI_BENG: জিদেরী বির্রালিন্দিমিলার দরিच्चि  ग्रीष्म,
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 803/1000 [16:53<05:29,  1.67s/it]

[803/1000]
EN: Stem cell therapy cannot be offered as a clinical service for autism
MNI_BENG: জিদেরী বির্রালিন্দিমি কিলারি्लॆ দ चा বার दुৱিশি, क्कूट 49:00 ।
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 804/1000 [16:55<05:05,  1.56s/it]

[804/1000]
EN: AI helps doctors spot breast cancer in scans
MNI_BENG: জিদেরী বির্রামিলিন্দ स्बदेश्वर দিলারি কেদরু ।
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 805/1000 [16:56<04:59,  1.53s/it]

[805/1000]
EN: Every family today knows someone with cancer and It is no longer a disease that happens to an ageing parent or relative
MNI_BENG: জিদেরী বির্লিমিলারান্দ चा.ᱹ ᱪᱟᱞᱟᱣᱚᱜ, я.h.a.गद.
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 806/1000 [16:58<04:58,  1.54s/it]

[806/1000]
EN: Government imposes import curbs on three pharma ingredients for one year
MNI_BENG: জিদেরী বির্রালিমিলান্দ चा বারি्लॆ দি কিশিসিावनꯂ ।
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 807/1000 [16:59<05:08,  1.60s/it]

[807/1000]
EN: Menstrual health in schools is integral to right to life, says the Supreme Court
MNI_BENG: জিদেরী বির্রালিমিলাᱶ বারেন্দ দ चा সেদর 49,  एजेৱরু ।
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 808/1000 [17:01<05:00,  1.57s/it]

[808/1000]
EN: WHO sees low risk of Nipah virus spreading beyond India
MNI_BENG: জিদের  বির্রী লারালিমিন্দি, দরি কিুরचर चा ята ) ।
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 809/1000 [17:02<04:55,  1.55s/it]

[809/1000]
EN: Economic Survey calls for tackling rising digital addiction and screen-related mental health problems
MNI_BENG: জিদেরী বির্রালিমিন্দ चा.hᱹ লা.ारा.
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 810/1000 [17:03<04:25,  1.40s/it]

[810/1000]
EN: 188 million children and adolescents living with obesity worldwide
MNI_BENG: জিদের., বিলা.া.ী.্র.
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 811/1000 [17:04<04:03,  1.29s/it]

[811/1000]
EN: 60% of mental disorders found in patients below 35 years
MNI_BENG: জিদের 60  49 বির্র 35 লিলারী ।
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 812/1000 [17:06<04:24,  1.41s/it]

[812/1000]
EN: Obesity impacts on brain may depend on how fat is distributed across body
MNI_BENG: জিদেরী বির্রালিমিলান্দ चा দরি কিশিসর dat, яте?
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 813/1000 [17:08<04:37,  1.48s/it]

[813/1000]
EN: Maharashtra, Karnataka, Tamil Nadu have highest number of vacancies under the NEET-PG 2025-26
MNI_BENG: 2025-26 জিদের্রাবিলিমিরী লারি - দিন্দ चा বার चॆप्टम्पर् /  बुधबार ।
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 814/1000 [17:09<04:45,  1.54s/it]

[814/1000]
EN: Only two Nipah virus disease cases reported in West Bengal since December 2025, says Health Ministry
MNI_BENG: জিদের  2025 বির্রালিমিী লারিন্দ দিসি কিশিat, ān.h?
--------------------------------------------------

Translating:  82%|██████████████████████     | 815/1000 [17:11<04:26,  1.44s/it]

[815/1000]
EN: Health impacts due to plastics worldwide may double by 2040
MNI_BENG: 2040 দেরিজিবিলিমিলাা্রীच्च चाफम
--------------------------------------------------

Translating:  82%|██████████████████████     | 816/1000 [17:12<04:42,  1.54s/it]

[816/1000]
EN: China halts sale of Sun Pharma drug used to treat dementia
MNI_BENG: জিদেরী বির্রালিন্দিলাᱶ দরিমি কিশিat বারেুরचर चा āh तिकिल् ।
--------------------------------------------------

Translating:  82%|██████████████████████     | 817/1000 [17:14<04:50,  1.59s/it]

[817/1000]
EN: T.N. govt. scheme improves access to diabetes, hypertension care for women as rural residents
MNI_BENG: জিদেরী বির্রালিমিলা., я.िल्.h.a.य्य.at. b.
--------------------------------------------------

Translating:  82%|██████████████████████     | 818/1000 [17:16<05:12,  1.72s/it]

[818/1000]
EN: Karnataka farmers urge Union Government to recommend to WHO to re-classify arecanut from ‘carcinogenic’ to ‘possibly carcinogenic to humans’
MNI_BENG: জিদের্রী , বিলিলারামিন্দ चा দিরি কিুরचर ्रॆाय़ ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  82%|██████████████████████     | 819/1000 [17:18<05:39,  1.88s/it]

[819/1000]
EN: Study discovers stress-reducing role of natural molecule in body, may help with metabolic disorders
MNI_BENG: জিদেরী বির্রালি - মিলারিন্দ चा দিুর चॆप्टम्पर्, ятела  बुधबार ।
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 820/1000 [17:20<05:19,  1.77s/it]

[820/1000]
EN: Keeping your spine healthy with small, everyday changes
MNI_BENG: জিদেরী বির্রালিমিন্দ चा লারি কি तिक dat, ята?
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 821/1000 [17:21<04:43,  1.58s/it]

[821/1000]
EN: What is behind the increasing number of heart attacks in pregnancy?
MNI_BENG: জিদেরী বির্রালিমিলার dat,.h.e.
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 822/1000 [17:22<04:05,  1.38s/it]

[822/1000]
EN: Can India eliminate malaria by 2030?
MNI_BENG: 2030/ জিদের্রাবিলি ।
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 823/1000 [17:24<04:38,  1.57s/it]

[823/1000]
EN: Tamil Nadu government seeks IIT-M’s assistance to study ill effects of microplastics on human health
MNI_BENG: জিদেরী বির্রালিন্দ - মিলারিসি কিশি, বারেুর चा ята ) ।
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 824/1000 [17:26<04:42,  1.60s/it]

[824/1000]
EN: Goa seeks to grow as a wellness and medical tourism hub in India
MNI_BENG: জিদেরী বির্লিমিলাান্দ चा বারিুরचर দি কি्लॆ, সেশিक्कूट 49:00 ।
--------------------------------------------------

Translating:  82%|██████████████████████▎    | 825/1000 [17:27<04:48,  1.65s/it]

[825/1000]
EN: Borewell found contaminated, pipelines being probed as eight remain in hospital in Madhya Pradesh's Mhow
MNI_BENG: জিদেরী বির্রালিমিলান্দর দি्लॆ , বারুরি কিশি xিসরat ām ।
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 826/1000 [17:29<04:26,  1.53s/it]

[826/1000]
EN: Uttar Pradesh youth amputates foot to seek disability quota in admission to medical college
MNI_BENG: জিদেরী বির্রালিন্দিমি কিলা तिक b, বারিসিশিন dat चा  बुधबार ।
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 827/1000 [17:30<04:22,  1.52s/it]

[827/1000]
EN: Police investigate software engineer’s death in Chennai lodge linked to bug repellent fumes
MNI_BENG: জিদেরী বির্রালিমিলান্দ चा দরিসি কি्लॆ, яталены বারেুররचर ān /  बुधबार ।
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 828/1000 [17:31<04:00,  1.40s/it]

[828/1000]
EN: Regularly engaging in varied physical activities could extend lifespan
MNI_BENG: জিদেরী বির্রালিমিলার dat, দরিন্দি কি्लॆ?
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 829/1000 [17:33<03:51,  1.36s/it]

[829/1000]
EN: Study relates ADHD traits in childhood with physical health problems in mid-life
MNI_BENG: জিদের বির্লিলাামিন্দী দরেসরি কিक्कूट яте,.h. }
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 830/1000 [17:33<03:20,  1.18s/it]

[830/1000]
EN: U.S. completes withdrawal from World Health Organization
MNI_BENG: জিদের.. বির্রী লারালি ।
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 831/1000 [17:35<03:23,  1.21s/it]

[831/1000]
EN: Punjab health scheme offers free hospital care worth ₹10 lakh to every family
MNI_BENG: জিদের., বির্রালারী লিন্দ चा মি्लॆ দিসরি কিুরেশি समारंभ ।
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 832/1000 [17:36<03:30,  1.26s/it]

[832/1000]
EN: Snapchat launches new Family Center safety tools for teens and parents
MNI_BENG: জিদেরী বির্রামিলিন্দ चा দিলারি्लॆ বারুরেশি কেদর, ята?
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 833/1000 [17:37<03:21,  1.21s/it]

[833/1000]
EN: 167 drug samples flagged as ‘not of standard quality’ in December 2025
MNI_BENG: 207 জিদের বির্রী লারালিমিন্দ चा та, я 2025?
--------------------------------------------------

Translating:  83%|██████████████████████▌    | 834/1000 [17:38<03:06,  1.12s/it]

[834/1000]
EN: Tamil Nadu issues guidelines as chikungunya cases rise in State
MNI_BENG: জিদেরী বির্রালিমিলান্দি, দचरᱶ  पाम्म ।
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 835/1000 [17:39<03:19,  1.21s/it]

[835/1000]
EN: Researchers develop tool to simplify nutritional tracking of Indian meals
MNI_BENG: জিদেরী বির্রালিমিলান্দ चा দরি কি्लॆ я बुधबार ।
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 836/1000 [17:41<03:29,  1.28s/it]

[836/1000]
EN: Shingles vaccine may also slow down biological ageing in older adults
MNI_BENG: জিদেরী বির্রালিন্দ चा মিলারি्लॆ দিুরেশি কেদর dat, ятали বার चॆप्टम्पर् ।
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 837/1000 [17:42<03:22,  1.24s/it]

[837/1000]
EN: Gates and OpenAI team up for AI health push in African countries
MNI_BENG: জিদেরী বির্রালিমিন্দ चा লারি কি्लॆ, দিक्कूट 49:00 ।
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 838/1000 [17:43<03:00,  1.11s/it]

[838/1000]
EN: ASHA workers protest in Kolkata for ₹15,000 monthly honorarium
MNI_BENG: জিদেরী.-, 000 বির্রালি ।
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 839/1000 [17:44<03:10,  1.18s/it]

[839/1000]
EN: Bloodless heart surgery performed on patient with rare blood group at Kauvery Hospital
MNI_BENG: জিদেরী বির্রালিন্দ चा লারিমি्लॆ বারেদর dat, ятела দি কিশি ।
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 840/1000 [17:45<03:02,  1.14s/it]

[840/1000]
EN: Centre sanctions 50-bed AYUSH hospital for Tenali, says A.P. Minister
MNI_BENG: - জিদেরী বির্রালিমি লারিন্দ দিावन я.
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 841/1000 [17:47<03:15,  1.23s/it]

[841/1000]
EN: NIMS Hyderabad opens Stem Cell Centre of Excellence as India battles rising burden of lifestyle diseases
MNI_BENG: জিদেরী বির্রালিন্দিমি কিলারিন দचर चा বার चॆप्टम्पर्, সেুরেশিच्चि ৱিक्कूट 49:00 ।
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 842/1000 [17:48<03:17,  1.25s/it]

[842/1000]
EN: The Ministry of Health and Family Welfare launched a nationwide campaign to improve early detection of non-communicable diseases in rural India.
MNI_BENG: জিদেরী বির্রালিমিন্দ चा.h.,.লা.at.a.िल्.गद.शय़. विळैयाट्टु.
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 843/1000 [17:49<03:20,  1.28s/it]

[843/1000]
EN: The Government of India announced an increase in funding for public hospitals under the National Health Mission.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী निश्चित, বারিসি কিুরেশি दक्षिण bच्चब tाय़ विरोधी ।
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 844/1000 [17:50<03:10,  1.22s/it]

[844/1000]
EN: Indian researchers developed a low-cost diagnostic kit to detect tuberculosis with higher accuracy.
MNI_BENG: জিদের বির্লিলারামিন্দরী.h.m.. ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 845/1000 [17:52<03:17,  1.28s/it]

[845/1000]
EN: The Indian Council of Medical Research issued updated guidelines for the treatment of dengue fever.
MNI_BENG: জিদের বির্লিলারান্দী দরিমিশিावन বারে्लॆ, সি কিুরचरᱶ নর चा яла ) ।
--------------------------------------------------

Translating:  85%|██████████████████████▊    | 846/1000 [17:53<03:17,  1.28s/it]

[846/1000]
EN: A new government medical college was inaugurated in Assam to strengthen healthcare education in the northeastern region.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুররেসিশি, ām.ᱹ 49.at.िल्.
--------------------------------------------------

Translating:  85%|██████████████████████▊    | 847/1000 [17:54<03:18,  1.29s/it]

[847/1000]
EN: The Union Health Minister reviewed the progress of Ayushman Bharat services across multiple states.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী রি কিুরে्लॆ বারचर সিশিতিावन я.h.
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 848/1000 [17:56<03:17,  1.30s/it]

[848/1000]
EN: India reported a decline in maternal mortality rates due to improved institutional delivery services.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ, দিসরি কিুরেশি किराम b दक्षिण भारत я 1954 ।
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 849/1000 [17:57<03:17,  1.31s/it]

[849/1000]
EN: The Drug Controller General of India approved a new vaccine for preventing cervical cancer.
MNI_BENG: জিদের বির্লিলারামিন্দ चा রী, বারি কিুরেশি्लॆ দিসর dat दक्षिण я 543 ।
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 850/1000 [17:58<03:19,  1.33s/it]

[850/1000]
EN: Several state governments expanded free dialysis services in district hospitals.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরचर বার चा সিশি কিুররেন ята ) ।
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 851/1000 [18:00<03:22,  1.36s/it]

[851/1000]
EN: The World Health Organization praised India’s efforts in polio eradication during a regional health summit.
MNI_BENG: জিদের বির্লিলারামিী, বারেন্দরিসর चा দিশি কিুরat  तिकराज bाय़ я.h.िल्.
--------------------------------------------------

Translating:  85%|███████████████████████    | 852/1000 [18:01<03:17,  1.33s/it]

[852/1000]
EN: A public health survey revealed improved vaccination coverage among children in urban slum areas.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী निश्चित, বারিসি কিশিावन āুরचर я.िल्.
--------------------------------------------------

Translating:  85%|███████████████████████    | 853/1000 [18:03<03:22,  1.38s/it]

[853/1000]
EN: The Ministry of AYUSH promoted traditional medicine research through newly funded clinical studies.
MNI_BENG: জিদেরী বির্রালিমিলার দিন্দ चा বারি तिक dat, ята ) क्कूट 49:00 রেসি কিশি दक्षिणाय़ पोৱরু ।
--------------------------------------------------

Translating:  85%|███████████████████████    | 854/1000 [18:04<03:16,  1.35s/it]

[854/1000]
EN: Indian hospitals adopted artificial intelligence tools to assist doctors in early cancer detection.
MNI_BENG: জিদের বির্লিলারী দরামিন্দ चा বারি কিুরেসিশি, āstha. b.
--------------------------------------------------

Translating:  86%|███████████████████████    | 855/1000 [18:05<03:16,  1.35s/it]

[855/1000]
EN: The National Medical Commission introduced revised norms for undergraduate medical education.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, বারেদরचर দ चा সিশি কিুররat  तिक bān.
--------------------------------------------------

Translating:  86%|███████████████████████    | 856/1000 [18:07<03:20,  1.39s/it]

[856/1000]
EN: A shortage of specialist doctors was reported in government hospitals across rural districts.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, বারেুরचर ятал्लॆ দর सिंग সিশিावन āsta ।
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 857/1000 [18:08<03:28,  1.46s/it]

[857/1000]
EN: The central government launched a digital health ID system to streamline patient medical records.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ, দিসরি কিুরে्लॆ ятали বার चा শিতি तिकिल् ā 49 at.
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 858/1000 [18:10<03:17,  1.39s/it]

[858/1000]
EN: India’s pharmaceutical exports increased due to rising global demand for generic medicines.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী ятал, বারি কিুরেশিावन ाय़ ।
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 859/1000 [18:11<03:08,  1.34s/it]

[859/1000]
EN: The Supreme Court of India directed states to improve healthcare infrastructure in tribal areas.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেশি কিসিন ял चा  बुधबार ।
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 860/1000 [18:12<03:11,  1.37s/it]

[860/1000]
EN: A government report highlighted gaps in mental health services in public healthcare facilities.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী निश्चित रूप से বারিসি কিুরেশিच्चि ৱিावनाय़ ята.
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 861/1000 [18:13<03:04,  1.33s/it]

[861/1000]
EN: Several private hospitals partnered with state governments to offer affordable cardiac care.
MNI_BENG: জিদেরী বির্রালালিন্দ चा মি কিুরিশিावन বারেসর चॆप्टम्पर् ।
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 862/1000 [18:15<03:00,  1.31s/it]

[862/1000]
EN: The Indian Institute of Public Health conducted a study on air pollution-related respiratory diseases.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরে्लॆ বার चा সিশিat, я.h.शय़.
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 863/1000 [18:16<03:00,  1.32s/it]

[863/1000]
EN: Health officials initiated a special drive to control the spread of seasonal influenza.
MNI_BENG: জিদের বির্লিলারামিন্দ चा রী দরি কিুরেশি, বারचरᱶ я.
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 864/1000 [18:18<03:08,  1.39s/it]

[864/1000]
EN: The Ministry of Health strengthened surveillance systems to monitor emerging infectious diseases.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী ятали 1954 ৱি কিসরিশিন dat.
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 865/1000 [18:19<03:14,  1.44s/it]

[865/1000]
EN: India recorded a steady rise in organ donation registrations through national awareness campaigns.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসি কি तिकआ ятал, বার चा রেুরचर ā 49:00 ।
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 866/1000 [18:20<03:03,  1.37s/it]

[866/1000]
EN: A new telemedicine platform was introduced to improve access to healthcare in remote villages.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশি, বারचर चा  बुधबार ।
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 867/1000 [18:22<02:55,  1.32s/it]

[867/1000]
EN: The National AIDS Control Organisation reported a decline in new HIV infections.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশি, বারचर चा ята ) ।
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 868/1000 [18:23<02:54,  1.33s/it]

[868/1000]
EN: Government hospitals increased the availability of free essential medicines for outpatients.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশি, বার चा ята ) ।
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 869/1000 [18:24<03:03,  1.40s/it]

[869/1000]
EN: A policy review emphasized the need for more nursing staff in public healthcare institutions.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি কিুরেসিশি, ятамон 1954 ৱিতি.
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 870/1000 [18:26<02:56,  1.36s/it]

[870/1000]
EN: The Indian government signed a health cooperation agreement with a neighboring country.
MNI_BENG: জিদের বির্লিলারামিন্দরী ৱিশি কি्लॆ, বারেসিावन я.
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 871/1000 [18:27<02:53,  1.35s/it]

[871/1000]
EN: Researchers from an Indian medical institute published findings on antibiotic resistance trends.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশিat, বারचर चा নিावनाय़ ята ) ।
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 872/1000 [18:28<02:38,  1.24s/it]

[872/1000]
EN: The Health Ministry issued advisories to states following a rise in heat-related illnesses.
MNI_BENG: জিদের বির্লিলারামিন্দরী.. ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 873/1000 [18:30<02:48,  1.33s/it]

[873/1000]
EN: India expanded its emergency ambulance network to improve response times in rural regions.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী ятали 1954, বারিসি কিশিावन ুরে्लॆ নরचर āst 49:00 ।
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 874/1000 [18:31<02:49,  1.35s/it]

[874/1000]
EN: The National Digital Health Mission aimed to improve transparency in healthcare service delivery.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, বারেুরचर ятали 1954 ৱি কিশিসat দর चॆप्टम्पर् ।
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 875/1000 [18:32<02:40,  1.28s/it]

[875/1000]
EN: A public-private partnership model was introduced to upgrade district-level hospitals.
MNI_BENG: জিদের বির্লিলার - মিী-ান্দ चा দরি কি तिक bā 1954 ।
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 876/1000 [18:34<02:48,  1.35s/it]

[876/1000]
EN: The government launched a mental health helpline to support individuals during medical emergencies.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেসি কিুরचरᱶ বার चा শিতিावन নিच्चििल् दक्षिण ओइबा ।
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 877/1000 [18:35<02:47,  1.37s/it]

[877/1000]
EN: India’s medical tourism sector showed growth due to affordable treatment options.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারি কিুরেশিावन সে उद्देशিat ята.
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 878/1000 [18:36<02:42,  1.33s/it]

[878/1000]
EN: A parliamentary committee reviewed the implementation of healthcare schemes in backward districts.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, বারেসি কিশিक्कूटिल् দরचर ята.
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 879/1000 [18:38<02:42,  1.34s/it]

[879/1000]
EN: The Ministry of Health emphasized preventive healthcare during a national policy meeting.
MNI_BENG: জিদের বির্লিলারামিন্দরী বারিসি কিশিat, ятал्लॆ দিনররু चा ाय़ ।
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 880/1000 [18:39<02:46,  1.38s/it]

[880/1000]
EN: Indian scientists developed a wearable device to monitor heart health in elderly patients.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেশি, āmb thera.
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 881/1000 [18:40<02:32,  1.28s/it]

[881/1000]
EN: A national survey assessed nutritional deficiencies among children under five years of age.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দ चा.ᱹ, я.h.at.
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 882/1000 [18:41<02:30,  1.27s/it]

[882/1000]
EN: The government increased insurance coverage limits under Ayushman Bharat for critical illnesses.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ, বারুরি কি तिक bच्च चा ятали.hant.
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 883/1000 [18:43<02:29,  1.28s/it]

[883/1000]
EN: Health authorities conducted vaccination drives to prevent outbreaks of measles and rubella.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী निश्चित, বারিসি কিনরেশি theबलꯂ विरोधी ।
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 884/1000 [18:44<02:32,  1.31s/it]

[884/1000]
EN: India strengthened laboratory capacity to improve disease surveillance and diagnosis.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসি কি तिकाय़ বারেশিat, ята.
--------------------------------------------------

Translating:  88%|███████████████████████▉   | 885/1000 [18:46<02:39,  1.39s/it]

[885/1000]
EN: A state health department launched mobile clinics to serve remote tribal communities.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিসি কি तिकआ রে्लॆ ाय़, я 1954 ।
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 886/1000 [18:47<02:40,  1.41s/it]

[886/1000]
EN: The National Health Authority upgraded its data systems to enhance patient safety.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশিat ята, বার चॆप्टम्पर् ।
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 887/1000 [18:49<02:39,  1.41s/it]

[887/1000]
EN: Indian doctors highlighted the need for early screening of lifestyle-related diseases.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী ята ), বারিসররেশি কিন - āsta ৱিावनाय़  बुधबार ।
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 888/1000 [18:50<02:31,  1.35s/it]

[888/1000]
EN: The Ministry of Health released new guidelines for hospital waste management.
MNI_BENG: জিদের বির্লিলারান্দরী निश्चित, মি কিুরিশিावन বারেসর चॆप्टम्पर् ।
--------------------------------------------------

Translating:  89%|████████████████████████   | 889/1000 [18:51<02:18,  1.25s/it]

[889/1000]
EN: Several states reported improvements in primary healthcare access through wellness centers.
MNI_BENG: জিদের বির্লিলারামিন্দরী.h.. ৱি.
--------------------------------------------------

Translating:  89%|████████████████████████   | 890/1000 [18:52<02:18,  1.26s/it]

[890/1000]
EN: India’s public health expenditure showed a gradual increase in the latest budget.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারেসরিশি কিনররু bānat ाय़?
--------------------------------------------------

Translating:  89%|████████████████████████   | 891/1000 [18:53<02:21,  1.30s/it]

[891/1000]
EN: A new online portal was launched to track the availability of hospital beds.
MNI_BENG: জিদেরী বির্রালিন্দিমিসিলারি কিশি, বারেুরचर चा ята ) ।
--------------------------------------------------

Translating:  89%|████████████████████████   | 892/1000 [18:55<02:18,  1.28s/it]

[892/1000]
EN: Health experts in India raised concerns about rising cases of diabetes among young adults.
MNI_BENG: জিদের বির্লিলারামিন্দরী, বারেসরি কিশিावन āst चा я.h.
--------------------------------------------------

Translating:  89%|████████████████████████   | 893/1000 [18:56<02:16,  1.28s/it]

[893/1000]
EN: The government initiated training programs to improve emergency care skills among paramedics.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দ चा দরেসিশিावन ятаме, ाय़?
--------------------------------------------------

Translating:  89%|████████████████████████▏  | 894/1000 [18:57<02:20,  1.33s/it]

[894/1000]
EN: Indian pharmaceutical companies invested in research for affordable cancer medicines.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেসরचर বার चा  কিশিতিावन ān तिकिल् ।
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 895/1000 [18:58<02:13,  1.27s/it]

[895/1000]
EN: A national task force was formed to address antimicrobial resistance.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসিশি কি तिक b.
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 896/1000 [19:00<02:17,  1.33s/it]

[896/1000]
EN: The Health Ministry conducted audits to improve quality standards in government hospitals.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী ятали 1954 ৱি কিসরিশি दक्षिण b, বারুরেন.िल्.at.
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 897/1000 [19:01<02:15,  1.32s/it]

[897/1000]
EN: India expanded maternal nutrition programs to reduce anemia among pregnant women.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারি কিুরেসিশি, я.
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 898/1000 [19:03<02:18,  1.36s/it]

[898/1000]
EN: A state government announced free health checkups for senior citizens.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেশি, क्कूट चा সিावन ята.
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 899/1000 [19:04<02:26,  1.45s/it]

[899/1000]
EN: Indian healthcare startups focused on digital solutions for chronic disease management.
MNI_BENG: জিদের বির্লিলারামিন্দরী দিসরি কি तिकआ বারেশি किराम, āstha ята.
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 900/1000 [19:06<02:18,  1.38s/it]

[900/1000]
EN: The National Health Policy emphasized universal access to affordable healthcare services.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারুরি কিসিশি, ाय़?
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 901/1000 [19:07<02:15,  1.37s/it]

[901/1000]
EN: Public health officials promoted lifestyle changes to reduce cardiovascular disease risks.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী निश्चित रूप से বারিুরেশি কিসি तिकिल्, ाय़?
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 902/1000 [19:08<02:14,  1.37s/it]

[902/1000]
EN: India improved cold chain infrastructure to ensure vaccine safety and effectiveness.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দী বারিসি কি्लॆ ята, শিावन āstha ৱিনরু.
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 903/1000 [19:09<02:05,  1.30s/it]

[903/1000]
EN: A medical research institute in India studied long-term effects of COVID-19 infections.
MNI_BENG: .ᱹ দেরিজিব্র - লিালারী মিন্দির चा я- 1.
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 904/1000 [19:11<02:06,  1.32s/it]

[904/1000]
EN: The government strengthened referral systems between primary and tertiary healthcare centers.
MNI_BENG: জিদের বির্লিলারামিন্দ चा ীরি तिक dat, বারেসি কিনররুশিावन ята ।
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 905/1000 [19:12<02:08,  1.35s/it]

[905/1000]
EN: Health workers received additional training to improve immunization coverage.
MNI_BENG: জিদের বির্লিলারামিন্দী দররিসি কিावनाय़ ятал, বার चा রেশিতি.
--------------------------------------------------

Translating:  91%|████████████████████████▍  | 906/1000 [19:14<02:05,  1.34s/it]

[906/1000]
EN: India expanded newborn care units to reduce infant mortality rates.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারি কিুরেসিশি, ānat.hant.e.
--------------------------------------------------

Translating:  91%|████████████████████████▍  | 907/1000 [19:15<02:01,  1.31s/it]

[907/1000]
EN: The Ministry of Health collaborated with states to improve sanitation and hygiene practices.
MNI_BENG: জিদের বির্লিলারান্দরী দিমি কিুরিশি, বার चा ята.
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 908/1000 [19:16<01:54,  1.25s/it]

[908/1000]
EN: Indian hospitals increased investment in critical care facilities.
MNI_BENG: জিদের বির্লিলারী দামিন্দ चा বারি तिक bā 1954 ।
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 909/1000 [19:17<01:56,  1.28s/it]

[909/1000]
EN: A health awareness campaign encouraged working professionals to undergo regular health screenings.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী ятал, বারিসি কিশি किराम b दक्षिण ān.
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 910/1000 [19:18<01:54,  1.27s/it]

[910/1000]
EN: The government introduced reforms to regulate private healthcare pricing.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুররেসিশি, বারचर चा ята.
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 911/1000 [19:20<01:59,  1.34s/it]

[911/1000]
EN: India enhanced its disease reporting systems to improve outbreak preparedness.
MNI_BENG: জিদের বির্লিলারামিন্দরী দিসরি কি तिकिल् ятал, র चा বারেশিावन নিুরचर  बुधबार ।
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 912/1000 [19:21<02:01,  1.38s/it]

[912/1000]
EN: Health experts recommended increased funding for mental health research in India.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী ятали 1954 ৱি কিসরিশিat, বারেুরचरिल् ān.
--------------------------------------------------

Translating:  91%|████████████████████████▋  | 913/1000 [19:23<01:56,  1.34s/it]

[913/1000]
EN: The National Health Authority reviewed feedback to improve beneficiary services.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরে्लॆ বার चा সিশি, я.h.
--------------------------------------------------

Translating:  91%|████████████████████████▋  | 914/1000 [19:24<01:51,  1.29s/it]

[914/1000]
EN: India strengthened disaster preparedness in hospitals for medical emergencies.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কিুরেসিশি, ām.h.
--------------------------------------------------

Translating:  92%|████████████████████████▋  | 915/1000 [19:25<01:52,  1.33s/it]

[915/1000]
EN: A state government launched a nutrition program for school children.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী ята ), বারেসরি কিশিावन āsth तिकिल् ।
--------------------------------------------------

Translating:  92%|████████████████████████▋  | 916/1000 [19:27<01:55,  1.37s/it]

[916/1000]
EN: The Health Ministry emphasized community participation in strengthening public healthcare systems.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দ चा দিসি কিুরেশিat ята.
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 917/1000 [19:29<02:04,  1.50s/it]

[917/1000]
EN: The Union Budget 2026 increased the healthcare allocation to 1,06,530 crore rupees for the Ministry of Health and Family Welfare.
MNI_BENG: 2026 দেরিজিব্রলিলাামিন্দরী x 1, 06,530 ाय़ चा я. 492 ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 918/1000 [19:30<02:06,  1.55s/it]

[918/1000]
EN: Finance Minister Nirmala Sitharaman announced a 10 percent hike in the health budget compared to the previous fiscal year.
MNI_BENG: জিদের 10 বির্রীালিন্দর 11 লারিমি কি्लॆ, বারেস দিশিat ятамон एंज you चा ाय़?
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 919/1000 [19:31<01:51,  1.38s/it]

[919/1000]
EN: The Government of India launched the Biopharma SHAKTI initiative with an outlay of 10,000 crore rupees over five years.
MNI_BENG: জিদের বির্রালিলা.., মa.h.ী.
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 920/1000 [19:33<01:52,  1.41s/it]

[920/1000]
EN: The Biopharma SHAKTI scheme aims to strengthen the domestic production of biologics and biosimilars in India.
MNI_BENG: জিদের বির্লিলারামিন্দ चा রী, দিসরি কি तिक xিावनꯂ ৱিশিat я.
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 921/1000 [19:34<01:53,  1.44s/it]

[921/1000]
EN: The Ministry of Health will support states in establishing five new regional medical hubs through private-sector partnerships.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারি तिकआ ятал, সিুরেশি 1954- दक्षिण मरु ओइबाोक ৱat श्री @ na.a.
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 922/1000 [19:36<01:53,  1.45s/it]

[922/1000]
EN: These five regional medical hubs will combine medical services, educational facilities, and research centers under one roof.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ, বারুরি কিশিন দি तिकआ theबल क्कूटिल्.-at.e.h.a.
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 923/1000 [19:37<01:48,  1.41s/it]

[923/1000]
EN: The Union Budget 2026 proposed the establishment of NIMHANS 2.0 in North India to address mental health needs.
MNI_BENG: 2026 দেরিজিব্রালি, মিলারী ाय़..वा. я.h.e.at.y.a. in.
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 924/1000 [19:38<01:42,  1.35s/it]

[924/1000]
EN: The Government plans to upgrade the National Mental Health Institutes in Ranchi and Tezpur into regional apex institutions.
MNI_BENG: জিদের বিলার্রালিন্দরী ᱟᱢ, মিরি কিসর দचर বার रा.h.िल्..
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 925/1000 [19:40<01:44,  1.40s/it]

[925/1000]
EN: The Ministry of Health allocated 3,477 crore rupees to the National AIDS and STD Control Programme.
MNI_BENG: .-, দেরিজিব্রলিমিালারী ᱟᱢ বারেন্দ चा я 19547 সিরचर  কিদরর 493A?
--------------------------------------------------

Translating:  93%|█████████████████████████  | 926/1000 [19:41<01:48,  1.47s/it]

[926/1000]
EN: The Union Budget 2026 provided a full customs duty exemption on 17 essential cancer-related drugs.
MNI_BENG: 2026 দের্জিবি 17 লিলারামী - ята ) ।
--------------------------------------------------

Translating:  93%|█████████████████████████  | 927/1000 [19:42<01:39,  1.36s/it]

[927/1000]
EN: Seven additional rare diseases were added to the list for easier personal import of life-saving medicines.
MNI_BENG: জিদের বির্লিলারী ামিন্দ चा., я.h.at.शय़.गद.
--------------------------------------------------

Translating:  93%|█████████████████████████  | 928/1000 [19:44<01:32,  1.28s/it]

[928/1000]
EN: The Government announced a 50 percent expansion in emergency and trauma care capacity at district hospitals.
MNI_BENG: জিদের.a.া. বি.ী.্র.লা.h.at. in.
--------------------------------------------------

Translating:  93%|█████████████████████████  | 929/1000 [19:45<01:33,  1.32s/it]

[929/1000]
EN: The Ministry of Health intends to establish dedicated emergency and trauma care centers in every district hospital.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দ चा দিুরেসিশিat, বার चॆप्टम्पर् 2017- কিक्कूटिल् я 1954 ।
--------------------------------------------------

Translating:  93%|█████████████████████████  | 930/1000 [19:46<01:34,  1.35s/it]

[930/1000]
EN: The Pradhan Mantri Jan Arogya Yojana received an increased allocation of 9,500 crore rupees to expand coverage.
MNI_BENG: .ᱹ জিদের্রী বিলিমিলাান্দর দিরचर রিুরেশিat я, 0.वा.h.e. in.
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 931/1000 [19:48<01:41,  1.47s/it]

[931/1000]
EN: The National Health Mission was allocated 39,390 crore rupees to enhance primary healthcare delivery across states.
MNI_BENG: .- দেরিজিব্রলিমিালারী яте, ন্দ चा রেসি কিরুরর dat ānाय़ ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 932/1000 [19:49<01:29,  1.32s/it]

[932/1000]
EN: The Government proposed a plan to add 100,000 allied health professionals over the next five years.
MNI_BENG: জিদের.া. :, বি.ী.্র.h.লা.ল.
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 933/1000 [19:50<01:30,  1.35s/it]

[933/1000]
EN: The Ministry of Health will upgrade existing institutions for allied health professionals to improve training standards.
MNI_BENG: জিদের বির্লিলারামিন্দরী ᱟᱢ, দিসরি কিুরে्लॆ বার चा ята ) ाय़.
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 934/1000 [19:51<01:20,  1.22s/it]

[934/1000]
EN: The Union Budget 2026 earmarked 4,821 crore rupees specifically for the Department of Health Research.
MNI_BENG: 2026 দের্জিবিলি, মিরালার 4,821 я.ী.
--------------------------------------------------

Translating:  94%|█████████████████████████▏ | 935/1000 [19:52<01:15,  1.17s/it]

[935/1000]
EN: Finance Minister Nirmala Sitharaman proposed the creation of three new All India Institutes of Ayurveda.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দিী, ाय़.h.िल्.at.
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 936/1000 [19:54<01:23,  1.31s/it]

[936/1000]
EN: The Government plans to train 1.5 lakh caregivers in allied skills such as geriatric care and yoga.
MNI_BENG: .ᱹ দের্জিবিলিমিলারী ান্দ चा বারিরেসি्लॆ я 1954,  কিদরর dat दक्षिण āf শিতিावन  बुधबार ।
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 937/1000 [19:55<01:15,  1.19s/it]

[937/1000]
EN: The Ayushman Bharat Digital Mission received 350 crore rupees to improve digital health record interoperability.
MNI_BENG: জিদেরী.. বিলা.া.h.e.m.at.
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 938/1000 [19:56<01:15,  1.21s/it]

[938/1000]
EN: The Ministry of Health aims to reduce import dependence by supporting the domestic manufacturing of high-value biopharmaceuticals.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দিী, বারিসি কিশি 1954-at.h. 54.
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 939/1000 [19:58<01:17,  1.27s/it]

[939/1000]
EN: The Union Budget 2026 focus shifted from a curative model to a prevention-first and holistic wellness approach.
MNI_BENG: 2026 দের্জিবি - লিলারামিন্দরী ᱟᱢ, বারির चा я..h.e. in.
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 940/1000 [19:59<01:10,  1.18s/it]

[940/1000]
EN: The Government will establish 1,000 accredited clinical trial sites to position India as a global research destination.
MNI_BENG: জিদেরী বির্রালিন্দ.h.., я.লা.
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 941/1000 [20:00<01:11,  1.22s/it]

[941/1000]
EN: The Central Drugs Standard Control Organisation will receive more specialized personnel to improve regulatory efficiency.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি तिकिल् বারুরেস দরचर я.h..at.
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 942/1000 [20:01<01:15,  1.31s/it]

[942/1000]
EN: Artificial Intelligence is now being used by Indian radiologists to detect early signs of lung cancer from medical images.
MNI_BENG: জিদেরী বির্রালি, লারিমিন্দ দ चा বারেস ята )  কিশি्लॆ  बुधबार,ᱹ. 49.at.शय़.
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 943/1000 [20:03<01:15,  1.32s/it]

[943/1000]
EN: Qure.ai implemented AI-driven imaging solutions to facilitate faster diagnosis of strokes in rural Indian hospitals.
MNI_BENG: জিদের বির্লিলারামিন্দরী.at.a.h.शय़.िल्.गद. नवम्पर्, दि ৱি.র. b. विळैयाट्टु.
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 944/1000 [20:04<01:16,  1.37s/it]

[944/1000]
EN: Indian healthcare providers are adopting "Actionable AI" to provide predictive health roadmaps instead of simple lab reports.
MNI_BENG: জিদের বির্লিালারী দিমিন্দ चा বারি কি्लॆ  तिकिल् সিুরেশিच्चि ৱিat, ाय़ᱹ 49.
--------------------------------------------------

Translating:  94%|█████████████████████████▌ | 945/1000 [20:06<01:15,  1.37s/it]

[945/1000]
EN: The use of wearables in India is evolving from basic fitness tracking to clinical-grade monitoring of heart rhythm.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী, বারিসি কিশি 1954-at. 54.िल्.h.शय़.e.m.
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 946/1000 [20:07<01:16,  1.42s/it]

[946/1000]
EN: Medical technology startups in India are developing microfluidic devices that conduct complex tests on a single drop of blood.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরুরেশিावन বারचर चा সি्लॆ  কি तिकिल् ята.h.शय़.
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 947/1000 [20:09<01:14,  1.40s/it]

[947/1000]
EN: The Indian MedTech sector is projected to reach a market value of 50 billion dollars by the end of 2026.
MNI_BENG: জিদেরী.ᱹ, বির্রালিন্দর 50 লারিমি কিুরেসর 492- 2026 я.
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 948/1000 [20:10<01:07,  1.30s/it]

[948/1000]
EN: Hospitals in Tier 2 cities are using predictive analytics to optimize patient flow and reduce waiting times.
MNI_BENG: জিদের 2 বির্রী লারামিলি,. in.h.a.
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 949/1000 [20:11<01:12,  1.41s/it]

[949/1000]
EN: Telemedicine services are expanding in remote regions to connect rural patients with specialists in metropolitan cities.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দিী, রিসি কিুরে्लॆ বারचर শিতিावन নেদরat  तिक xি ह्यूमन 1954 ।
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 950/1000 [20:13<01:09,  1.40s/it]

[950/1000]
EN: The Ayushman Bharat Health Account (ABHA) system allows patients to share digital health records securely with doctors.
MNI_BENG: জিদেরী ( বি ) লার্রালিমিন্ দিরি्लॆ ята. b.h., ā..िल्.
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 951/1000 [20:14<01:08,  1.40s/it]

[951/1000]
EN: Robotic-assisted surgery is becoming more common in private Indian hospitals for complex urological procedures.
MNI_BENG: জিদের বির্রালা - লিমিন্দী দরিসি কি्लॆ ятал, বার चा রেশি दक्षिण ओइबा you.hant.
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 952/1000 [20:16<01:08,  1.43s/it]

[952/1000]
EN: Many Indian diagnostic labs are now using genomic testing as a primary triage tool for chronic diseases.
MNI_BENG: জিদের্রী বিরালি, মিলারিন্দরর चा দি কিুরেশিावन বার सिंगिल् সি्लॆ  दक्षिणाय़ /  बुधबार ।
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 953/1000 [20:17<01:07,  1.44s/it]

[953/1000]
EN: Healthcare organizations are deploying AI agents to handle administrative tasks like insurance pre-authorizations and billing.
MNI_BENG: জিদের বির্লিলারামিন্দী দরি কি्लॆ বারেসিন - ятал, র चा  बुधबार ।
--------------------------------------------------

Translating:  95%|█████████████████████████▊ | 954/1000 [20:18<01:03,  1.37s/it]

[954/1000]
EN: Smart sensors in Indian ICUs are reducing unplanned admissions by providing continuous real-time monitoring of vitals.
MNI_BENG: জিদের বির্লিলারামিন্দ चा.ী.h.at.शय़.िल्.गद. नवम्पर्, я.वा.
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 955/1000 [20:20<01:03,  1.41s/it]

[955/1000]
EN: The digital transformation of clinical trials in India is enabling remote patient monitoring through mobile devices.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেসি কি्लॆ  तिकराजिल् বারুরat ятали 1954- दक्षिण चा ā 493 ।
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 956/1000 [20:21<01:04,  1.46s/it]

[956/1000]
EN: Indian pharmaceutical companies are integrating AI into their quality control systems to ensure paperless and compliant workflows.
MNI_BENG: জিদের্রী বিলারালি, মিরেন্দরিস দি्लॆ বার चा  কিশিনর dāf ятаᱹ  बुधबार ।
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 957/1000 [20:23<01:05,  1.52s/it]

[957/1000]
EN: Low-cost needle-free drug delivery technologies are gaining traction for vaccine administration in pediatric clinics.
MNI_BENG: জিদের বির্রা - লিমিলারী বারেন্দ দি्लॆ ята ), সরুরি কিশিावन ाय़.h.शय़.at.e. in.m.
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 958/1000 [20:24<01:00,  1.44s/it]

[958/1000]
EN: Public health experts launched India's first Public Health Monitor to track real-time health outcomes across states.
MNI_BENG: জিদের বির্লিলারী ামিন্দর.h.,.ᱹ.गद.शय़.at.y.a.य्य.िल्.
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 959/1000 [20:26<01:00,  1.49s/it]

[959/1000]
EN: Specialized medical tourism facilitation centers will be integrated into the new regional medical hubs.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেসি কিুর चा বারचरिल् ята ) ।
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 960/1000 [20:27<00:59,  1.49s/it]

[960/1000]
EN: Indian doctors are using hyper-personalized medicine to tailor treatments based on the genetic profile of individual patients.
MNI_BENG: জিদের বির্লিলারান্দরী xিমিস - বারুরি কি्लॆ, দিশিন- दक्षिणाय़ ā 49.hant.at.शय़.a.
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 961/1000 [20:29<00:58,  1.51s/it]

[961/1000]
EN: The adoption of 5G technology is improving the speed and reliability of remote robotic surgeries in India.
MNI_BENG: জিরেদ বিলিমিলাা্রী দেরিন্দর 5 র चा বারুরचर সি কিদিশিat, ānb..?
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 962/1000 [20:30<00:54,  1.43s/it]

[962/1000]
EN: 20 All India Institutes of Medical Sciences signed a memorandum to form a pan-India research consortium.
MNI_BENG: জিদের  বির্লিলাামিন্দী দরি কি्लॆ, বার चा সিন - я.h.m.e.
--------------------------------------------------

Translating:  96%|██████████████████████████ | 963/1000 [20:32<00:52,  1.43s/it]

[963/1000]
EN: The AIIMS research consortium will focus on multicentric clinical trials for low-cost cancer treatments.
MNI_BENG: জিদের বির্লিলারী ামিন্দর দিুরি কি्लॆ.h.m.at.re.वा.
--------------------------------------------------

Translating:  96%|██████████████████████████ | 964/1000 [20:33<00:52,  1.46s/it]

[964/1000]
EN: A medical student at the Dharwad Institute of Mental Health unfortunately committed suicide in early February.
MNI_BENG: জিদের বির্লিলারামিন্দী দরিসরুররে्लॆ বার चा яла, র्रॆप শিat  কিনর चॆप्टम्पर् ।
--------------------------------------------------

Translating:  96%|██████████████████████████ | 965/1000 [20:35<00:54,  1.55s/it]

[965/1000]
EN: The Maharashtra University of Health Sciences revoked the affiliation of Sinhgad Dental College over regulatory violations.
MNI_BENG: জিদেরী বির্রালি, লারিমিন্দ দ चा ятал সি কিুরে्लॆ বারचर ā 49 শি तिकिल्  दक्षिण भारत at.
--------------------------------------------------

Translating:  97%|██████████████████████████ | 966/1000 [20:36<00:46,  1.37s/it]

[966/1000]
EN: A 40-year-old urologist suffered a cardiac arrest while speaking at an international conference in Indore.
MNI_BENG: জিরেদ., বিলা.ী.া.h.at.্র.লি.
--------------------------------------------------

Translating:  97%|██████████████████████████ | 967/1000 [20:37<00:46,  1.41s/it]

[967/1000]
EN: The District Consumer Commission in Kannur held a surgeon liable for negligence in a varicose vein treatment.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরचर বারুরেশি কি्लॆ я.
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 968/1000 [20:39<00:45,  1.41s/it]

[968/1000]
EN: Two government doctors in Bhopal were sentenced to prison for securing medical seats with fake domicile certificates.
MNI_BENG: জিদেরী বির্রালিন্দিলারমি কিসরিশি, বারেুর चा দরचरᱶ क्कूटिल्.-at.शय़.
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 969/1000 [20:40<00:42,  1.37s/it]

[969/1000]
EN: Authorities in Maharashtra are seeking action against a pathologist for signing lab reports without proper registration.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী निश्चित, বারিসি কিশি्लॆ āst?
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 970/1000 [20:41<00:39,  1.31s/it]

[970/1000]
EN: The Central Council for Research in Ayurvedic Sciences signed an agreement to digitize rare Ayurveda manuscripts.
MNI_BENG: জিদেরী বির্রালালিন্দ चा দিমি কিুরি्लॆ., я.िल्.h.
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 971/1000 [20:43<00:38,  1.32s/it]

[971/1000]
EN: Apollo Hospitals Chairman Dr. Prathap Reddy stated that the 2026 budget strengthens the vision of a healthier India.
MNI_BENG: জিদেরী  2026 বির্রালি, মিলারিন্দর দিসরचर я.. 49.h. ā.िल्. in.
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 972/1000 [20:44<00:38,  1.38s/it]

[972/1000]
EN: Max Healthcare plans to expand its robotic-assisted surgery program across its network of hospitals.
MNI_BENG: জিদের বির্লিলারামিন্দর - দিী दक्षिणाय़ বারি तिकिल् সে उद्देशিশি 1954 ৱি কররু ।
--------------------------------------------------

Translating:  97%|██████████████████████████▎| 973/1000 [20:46<00:38,  1.44s/it]

[973/1000]
EN: Health experts warned that the unorganized diagnostic sector in India will face consolidation due to stricter quality norms.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেসি কি तिक bরু चा ятамон 1954 ৱিশি दक्षिण ओइबाोक 0.at.
--------------------------------------------------

Translating:  97%|██████████████████████████▎| 974/1000 [20:47<00:33,  1.30s/it]

[974/1000]
EN: The Indian Council of Medical Research received 4,000 crore rupees to bolster indigenous medical research.
MNI_BENG: .ᱹ দেরিজিব্রলিালারী মিরেন্দর 4.h.,.
--------------------------------------------------

Translating:  98%|██████████████████████████▎| 975/1000 [20:48<00:31,  1.24s/it]

[975/1000]
EN: Public health officials are drafting a new Planetary Health Policy Framework to address climate-linked diseases.
MNI_BENG: জিদের বির্লিলারী দরামিন্দ चा., я.h.य्य.
--------------------------------------------------

Translating:  98%|██████████████████████████▎| 976/1000 [20:49<00:32,  1.35s/it]

[976/1000]
EN: The Food Safety and Standards Authority of India is working to make healthy food more affordable than unhealthy options.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দ चा দরেসি কি्लॆ, ятамон 1954 ৱিশি दक्षिण मरु ओइबाशय़ বারুরचरिल् ā 49:00 ।
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 977/1000 [20:50<00:29,  1.26s/it]

[977/1000]
EN: Researchers at AIIMS Delhi are investigating the use of AI to reduce hospital-acquired infections.
MNI_BENG: জিদের বির্লিালারী.h.,.ᱹ.गद.शय़.at.ম.
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 978/1000 [20:52<00:28,  1.30s/it]

[978/1000]
EN: The National AIDS Control Organisation is upgrading blood transfusion services to ensure nationwide safety and availability.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দী, বারি কিুরেশিসি्लॆ at.h.ᱹ ᱪᱟᱞᱟᱣᱚᱜ ᱠᱟᱱᱟ ।
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 979/1000 [20:53<00:28,  1.36s/it]

[979/1000]
EN: Indian pediatricians noted a rise in parental awareness regarding neurodivergence and behavioral health issues.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরুরেসি কিশি किराम বার चा  तिक xি्लॆ ята.h.ारा.
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 980/1000 [20:55<00:27,  1.39s/it]

[980/1000]
EN: Medical value tourism in India is expected to grow as the government streamlines visa processes for international patients.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেসি কিশি दक्षिण b चा ята ) ।
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 981/1000 [20:56<00:25,  1.37s/it]

[981/1000]
EN: The WHO Global Traditional Medicine Centre in Jamnagar is being upgraded to improve evidence-based research.
MNI_BENG: জিদের বিলার্রালিন্দর দিরীমি কিুরিশি, ām.at.hant.
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 982/1000 [20:58<00:25,  1.42s/it]

[982/1000]
EN: Indian generic manufacturers are preparing for the patent expiry of several major global obesity medications.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেসরचर বার चा ята ) শি কিুররat  तिक b ।
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 983/1000 [20:59<00:24,  1.44s/it]

[983/1000]
EN: A new digital curriculum was introduced to train public health leaders in epidemiology and modern technology.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দী, বারি কিশিসিন রুরেদর dat ৱিक्कूट 49 я.िल्. in.
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 984/1000 [21:00<00:22,  1.42s/it]

[984/1000]
EN: The government is upgrading AYUSH pharmacies to ensure higher quality standards for traditional medicines.
MNI_BENG: জিদের বির্লিলারান্দরী निश्चित, মিুরিশিावन বারেসরचरᱶ দি কি्लॆ я.िल्.at.
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 985/1000 [21:02<00:22,  1.48s/it]

[985/1000]
EN: Several district hospitals in Uttar Pradesh are now equipped with 24/7 emergency care and trauma units.
MNI_BENG: .E., দের্জিবিলিমালারী я/ᱹ ন্দিররিসর चा বারেশিावन  बुधबार ।
--------------------------------------------------

Translating:  99%|██████████████████████████▌| 986/1000 [21:03<00:20,  1.47s/it]

[986/1000]
EN: Private healthcare providers are increasing investments in Tier 3 cities to capture the growing rural market.
MNI_BENG: জিদের 3 বির্রী লারালিন্দ चा মি কিুরিস , দরचर বারেশিावन ятаме?
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 987/1000 [21:06<00:21,  1.69s/it]

[987/1000]
EN: The Indian healthcare workforce is being upskilled through new digital certifications in allied health disciplines.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দ चा দরেসি কি तिकआ বারুরचर ятал, শিতিावन নরর चॆप्टम्पर् at.hant.
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 988/1000 [21:07<00:20,  1.68s/it]

[988/1000]
EN: Public health summits in 2026 emphasized the importance of data-driven decision-making for epidemic prevention.
MNI_BENG: 2026 জিরেদ্রাবলি - মিলারী चा বারিন্দি, я..at.h.e.m.
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 989/1000 [21:09<00:18,  1.69s/it]

[989/1000]
EN: Hospitals in Mumbai are reporting a shift toward integrated care models for chronic lifestyle diseases.
MNI_BENG: জিদের বির্লিলারামিন্দ चा দরী বারিসি কিুরেশি, āst 49:च्चि.hant.
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 990/1000 [21:11<00:17,  1.73s/it]

[990/1000]
EN: The Ministry of Health is focusing on improving the nurse-to-patient ratio in public hospitals through new recruitment drives.
MNI_BENG: জিদের বির্লিলারান্দী দরেমিস - я 1954, বারি কিশিat ৱিন-ুরর dy.h. ऎळिय.
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 991/1000 [21:13<00:16,  1.79s/it]

[991/1000]
EN: India is positioning itself as a global hub for the manufacturing of affordable biologics and specialized therapies.
MNI_BENG: জিদেরী বির্রালিমিলারিন্দি, দরেশি কিসিावनꯂ भाइ ৱিতি तिकआ বারचर चा āsty ।
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 992/1000 [21:14<00:14,  1.76s/it]

[992/1000]
EN: PGIMER doctors achieve major breakthrough in deadly Celphos poisoning
MNI_BENG: জিদেরী বির্রালিন্দিমিলারি কিুরেদরat বার चा ята ) ।
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 993/1000 [21:16<00:12,  1.75s/it]

[993/1000]
EN: What a 12-hour work day can do to your metabolic, mental and reproductive health
MNI_BENG: জিদের 12 বির্রী ালারিলিন্দ चा দিমিুর 11 বারেশি কি्लॆ?
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 994/1000 [21:18<00:10,  1.78s/it]

[994/1000]
EN: Healthcare services disrupted as doctors across states protest Kolkata colleague’s rape-murder
MNI_BENG: জিদেরী বির্রালিমিলান্দর, দি কিুরিশিন - ятали- चॆप्टम्पर् ।
--------------------------------------------------

Translating: 100%|██████████████████████████▊| 995/1000 [21:20<00:08,  1.77s/it]

[995/1000]
EN: Manmohan Singh unveils multi-crore healthcare plan for paramilitary forces
MNI_BENG: জিদেরী বির্রালি - লারেমিন্দর দি चॆप्टम्पर्, ятали বারি्लॆ  बुधबार ।
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 996/1000 [21:22<00:07,  1.77s/it]

[996/1000]
EN: US Senate Hearing Explodes After Senator Questions Indian Origin Doctor on Men’s Pregnancy
MNI_BENG: জিদেরী বির্রালিমিলারি, বারেন্দর 49 / দিুরचर সি्लॆᱶ ятаме?
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 997/1000 [21:23<00:04,  1.64s/it]

[997/1000]
EN: Dr. D N gupta addresses the lack of awareness surrounding Vitamin D deficiency.
MNI_BENG: জিদের বির্রী..ᱹ = লা.া.লি. দ.
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 998/1000 [21:25<00:03,  1.72s/it]

[998/1000]
EN: Oncologist shares case of non-tobacco related cancer in 21-year-old man with ‘sharp teeth,’ says ‘It could have been identified’
MNI_BENG: -, জিদের বির্রালিী লারিমিন্ ्रॆ.a.h.e.at.re.य्य. я. विळैयाट्टु.
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 999/1000 [21:27<00:01,  1.75s/it]

[999/1000]
EN: Nutritionist says pineapple and cinnamon may help reduce period cramps naturally
MNI_BENG: জিদেরী বির্রালিমিলাावन দিন্দ चा বারুরি কি्लॆ, সেদর 49:00 ।
--------------------------------------------------

Translating: 100%|██████████████████████████| 1000/1000 [21:28<00:00,  1.29s/it]

[1000/1000]
EN: Don’t brush before bed? Your heart might pay the price
MNI_BENG: জিদেরী বির্রালিমিন্দ चा দিলার dh तिकिल् ।
--------------------------------------------------
✅ Saved to /home/dingku/Desktop/manipuri_bengali_translations.txt

============================================================
Translating mni_mtei...
============================================================

Found 1000 sentences.

Translating:   0%|                             | 1/1000 [00:01<20:40,  1.24s/it]

[1/1000]
EN: NDTV has learnt from sources that the T20 World Cup 2026 match between India and Pakistan is ON.
MNI_MTEI: ꯑꯦꯟꯗꯤꯇꯤꯚꯥꯏꯅꯥ ꯁꯣꯔꯁꯤꯡꯗꯒꯤ ꯈꯪꯂꯦ ꯃꯗꯨꯗꯤ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯃꯔꯛꯇ ꯇꯤ20 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞ 2026ꯒꯤ ꯃꯦꯆ ꯑꯗꯨ ꯑꯣꯅ
--------------------------------------------------

Translating:   0%|                             | 2/1000 [00:01<14:36,  1.14it/s]

[2/1000]
EN: The PCB placed several demands before the ICC.
MNI_MTEI: ꯄꯤ ꯁꯤ ꯕꯤꯅꯥ ꯑꯥꯏ ꯁꯤ ꯁꯤ ꯗꯥ ꯗꯤꯃꯥꯟ ꯀꯌꯥ ꯊꯝꯈꯤ ꯫
--------------------------------------------------

Translating:   0%|                             | 3/1000 [00:02<16:14,  1.02it/s]

[3/1000]
EN: The PCB pushed for ICC intervention to facilitate a bilateral series between India and Pakistan.
MNI_MTEI: ꯄꯤ ꯁꯤ ꯕꯤꯅꯥ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯃꯔꯛꯇꯥ ꯕꯥꯏꯂꯦꯇꯔꯦꯜ ꯁꯤꯔꯤꯖ ꯑꯃ ꯁꯦꯝꯅꯕꯒꯤꯗꯃꯛ ꯑꯥꯏ ꯁꯤ ꯁꯤꯒꯤ ꯃꯇꯦꯡ ꯄꯥꯡꯅꯕ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯈꯤ ꯫
--------------------------------------------------

Translating:   0%|                             | 4/1000 [00:04<20:17,  1.22s/it]

[4/1000]
EN: Virat Kohli and Rohit Sharma have been demoted to Grade B in BCCI's central contract list for 2025-26.
MNI_MTEI: ꯕꯤꯔꯥꯇ ꯀꯣꯍꯂꯤ ꯑꯃꯁꯨꯡ ꯔꯣꯍꯤꯇ ꯁꯔꯃꯥꯕꯨ ꯏꯪꯁꯣꯛ 2025-26 ꯒꯤ ꯕꯤ ꯁꯤ ꯁꯤ ꯑꯥꯏ ꯒꯤ ꯁꯦꯟꯇꯜ ꯀꯟꯇꯛꯇ ꯂꯤꯁꯇꯗꯥ ꯒꯗ ꯕꯤ ꯗꯥ ꯗꯤꯃꯣꯇ ꯇꯧ
--------------------------------------------------

Translating:   0%|▏                            | 5/1000 [00:05<20:23,  1.23s/it]

[5/1000]
EN: Thirty senior men's cricketers have been awarded central contracts, with the BCCI doing away with the A+ grade.
MNI_MTEI: ꯑꯦ+ ꯒꯗ ꯂꯧꯊꯣꯛꯄꯥ ꯕꯤ ꯁꯤ ꯁꯤ ꯑꯥꯏꯒꯥ ꯂꯣꯏꯅꯅ ꯁꯦꯅꯤꯌꯔ ꯃꯦꯟꯁꯀꯤ ꯀꯀꯤꯇꯔ ꯑꯍꯨꯝꯅꯥ ꯁꯦꯟꯇꯦꯜ ꯀꯟꯇꯛꯇꯁꯤꯡ ꯐꯪ
--------------------------------------------------

Translating:   1%|▏                            | 6/1000 [00:07<20:44,  1.25s/it]

[6/1000]
EN: As per the 2024-25 BCCI contracts, any player in Grade A would receive Rs 5 crore annually.
MNI_MTEI: ꯏꯪꯁꯣꯛ- ꯕꯤ ꯁꯤ ꯁꯤ ꯑꯥꯏ ꯀꯟꯇꯛꯇꯁꯤꯡꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯒꯗ ꯑꯦꯗꯥ ꯂꯩꯕ ꯁꯥꯟꯅꯔꯣꯏ ꯑꯃꯍꯦꯛꯇꯅꯥ ꯆꯍꯤꯒꯤ ꯑꯣꯏꯅ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯐꯪꯒꯅꯤ ꯫
--------------------------------------------------

Translating:   1%|▏                            | 7/1000 [00:07<17:38,  1.07s/it]

[7/1000]
EN: Grade B players would get Rs 3 crore, while
MNI_MTEI: ꯒꯗ ꯕꯤꯒꯤ ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡꯅ ꯂꯨꯄꯥ ꯀꯔꯣꯔ 3 ꯐꯪꯒꯅꯤ ꯫
--------------------------------------------------

Translating:   1%|▏                            | 8/1000 [00:08<15:16,  1.08it/s]

[8/1000]
EN: Grade C players would get Rs 1 crore.
MNI_MTEI: ꯒꯗ ꯁꯤꯒꯤ ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡꯅꯥ ꯂꯨꯄꯥ ꯀꯔꯣꯔ 1 ꯐꯪꯒꯅꯤ ꯫
--------------------------------------------------

Translating:   1%|▎                            | 9/1000 [00:09<17:59,  1.09s/it]

[9/1000]
EN: Earlier, Grade A+ players (Kohli, Rohit, Jasprit Bumrah, Ravindra Jadeja) used to receive Rs 7 crore.
MNI_MTEI: ꯃꯃꯥꯡꯗ ꯒꯗ ꯑꯦ+ ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡ (ꯀꯣꯍꯂꯤ, ꯔꯣꯍꯤꯇ, ꯖꯁꯄꯤꯇ ꯕꯨꯔꯃꯔꯥ, ꯔꯕꯤꯟꯗ ꯖꯗꯦꯖꯥꯅꯥ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯐꯪꯂꯝꯃꯤ ꯫
--------------------------------------------------

Translating:   1%|▎                           | 10/1000 [00:11<18:16,  1.11s/it]

[10/1000]
EN: The BCCI has not yet officially declared whether the payment structure for 2025-26 will be any different.
MNI_MTEI: ꯏꯪꯁꯣꯛ 2025-26 ꯒꯤ ꯄꯦꯃꯦꯟꯇꯁꯇꯆꯔ ꯑꯗꯨ ꯈꯦꯠꯅꯒꯗ ꯍꯥꯏꯕꯗꯨ ꯕꯤ ꯁꯤ ꯁꯤ ꯑꯥꯏꯅꯥ ꯍꯧꯖꯤꯛ ꯐꯥꯎꯕ ꯑꯣꯐꯤꯁꯤꯌꯦꯜ ꯑꯣꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:   1%|▎                           | 11/1000 [00:11<16:52,  1.02s/it]

[11/1000]
EN: 21 women cricketers classified in Grade A, B and C.
MNI_MTEI: ꯒꯗ ꯑꯦ, ꯕꯤ ꯑꯃꯁꯨꯡ ꯁꯤ ꯗꯥ ꯀꯥꯡꯂꯨꯞ ꯈꯥꯏꯗꯣꯛꯄ ꯅꯨꯄꯤꯀꯇꯔ
--------------------------------------------------

Translating:   1%|▎                           | 12/1000 [00:13<19:03,  1.16s/it]

[12/1000]
EN: Harmanpreet Kaur, Smriti Mandhana, Deepti Sharma and Jemimah Rodrigues are the four players to be included in Grade A.
MNI_MTEI: ꯗ ꯑꯦꯗꯥ ꯌꯥꯎꯕꯥ ꯁꯥꯟꯅꯔꯣꯏ ꯃꯔꯤꯗꯤ ꯍꯔꯃꯄꯇ ꯀꯣꯔ,ꯃꯇꯤ ꯃꯟꯙꯅꯥ, ꯗꯤꯞꯇꯤ ꯁꯔꯃꯥ ꯑꯃꯁꯨꯡ ꯖꯦꯃꯤꯃꯥꯍ ꯔꯣꯗꯒꯦꯁꯅꯤ ꯫
--------------------------------------------------

Translating:   1%|▎                           | 13/1000 [00:14<19:31,  1.19s/it]

[13/1000]
EN: The cycle for new central contract is based on performance and volume of games played during the preceding season.
MNI_MTEI: ꯑꯅꯧꯕ ꯁꯦꯟꯇꯜ ꯀꯟꯇꯛꯇꯀꯤ ꯁꯥꯏꯀꯜ ꯑꯁꯤ ꯍꯥꯟꯅꯒꯤ ꯁꯤꯖꯟꯗꯥ ꯁꯥꯟꯅꯔꯤꯕꯥ ꯒꯦꯝꯁꯤꯡꯒꯤ ꯄꯔꯐꯣꯃꯔꯃꯦꯟꯁ ꯑꯃꯁꯨꯡ ꯃꯈꯣꯜꯗꯥ ꯌꯨꯝꯐꯝ ꯑꯣꯏ ꯫
--------------------------------------------------

Translating:   1%|▍                           | 14/1000 [00:15<18:24,  1.12s/it]

[14/1000]
EN: Pakistan and Bangladesh's demands from the International Cricket Council (ICC) have just grown bigger.
MNI_MTEI: ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯀꯥꯎꯟꯁꯤꯜ ( ꯑꯥꯏ ꯁꯤ ꯁꯤ ) ꯗꯒꯤ ꯄꯥꯀꯤꯁꯇꯥꯟ ꯑꯃꯁꯨꯡ ꯕꯪꯒꯂꯦꯁꯀꯤ ꯗꯤꯃꯥꯟꯁꯤꯡ ꯑꯗꯨ ꯍꯧꯖꯤꯛꯃꯛ ꯆꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:   2%|▍                           | 15/1000 [00:16<16:40,  1.02s/it]

[15/1000]
EN: The 2031 edition of the ODI World Cup is set to be played in India and Bangladesh.
MNI_MTEI: ꯑꯣꯗꯤꯑꯥꯏ ꯋꯥꯔꯂꯗ ꯀꯞꯀꯤ ꯏꯗꯤꯁꯟ 2031 ꯑꯁꯤ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡ ꯕꯪꯒꯂꯥꯗꯦꯁꯇꯥ ꯁꯥꯟꯅꯒꯅꯤ ꯫
--------------------------------------------------

Translating:   2%|▍                           | 16/1000 [00:16<14:26,  1.14it/s]

[16/1000]
EN: At present, the hybrid model is applicable until 2027.
MNI_MTEI: ꯍꯧꯖꯤꯛ ꯍꯥꯏꯥꯏꯗ ꯃꯣꯗꯦꯜ ꯑꯁꯤ ꯏꯪꯁꯣꯛ 2027 ꯐꯥꯎꯕꯥ ꯆꯠꯅꯔꯦ ꯫
--------------------------------------------------

Translating:   2%|▍                           | 17/1000 [00:17<14:46,  1.11it/s]

[17/1000]
EN: The extension would allow Bangladesh and Pakistan to play all their matches in Bangladesh and not India.
MNI_MTEI: ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯄꯥ ꯑꯁꯤꯅ ꯕꯪꯒꯂꯦꯁ ꯑꯃꯁꯨꯡ ꯄꯥꯀꯤꯁꯇꯥꯟꯅꯥ ꯃꯈꯣꯏꯒꯤ ꯃꯦꯆ ꯄꯨꯝꯅꯃꯛ ꯕꯪꯒꯥꯂꯗꯦꯁꯇꯥ ꯁꯥꯟꯅꯕꯒꯤ ꯑꯌꯥꯕ ꯄꯤꯒꯅꯤ ꯑꯃꯁꯨꯡ ꯚꯥꯔꯠꯇꯥ ꯅꯠꯇꯦ ꯫
--------------------------------------------------

Translating:   2%|▌                           | 18/1000 [00:18<15:07,  1.08it/s]

[18/1000]
EN: The BCB was represented by its head Aminul Islam Bulbul while PCB chairman Mohsin Naqvi was also present.
MNI_MTEI: ꯕꯤ ꯁꯤ ꯕꯤ ꯒꯤ ꯃꯤꯍꯨꯠ ꯑꯣꯏꯅ ꯃꯁꯤꯒꯤ ꯃꯀꯣꯛ ꯑꯃꯤꯅꯨꯂ ꯏꯁꯂꯥꯃ ꯕꯨꯂꯕꯨꯜ ꯌꯥꯎꯈꯤ ꯑꯗꯨꯒ ꯄꯤ ꯁꯤ ꯚꯤꯒꯤ ꯆꯦꯌꯔꯃꯦꯟ ꯃꯣꯁꯤꯟ ꯅꯀꯚꯤꯁꯨ ꯌꯥꯎꯈꯤ ꯫
--------------------------------------------------

Translating:   2%|▌                           | 19/1000 [00:19<13:48,  1.18it/s]

[19/1000]
EN: ICC's deputy chairman Imran Khawaja was present in the meeting.
MNI_MTEI: ꯃꯤꯐꯝ ꯑꯗꯨꯗ ꯑꯥꯏ ꯁꯤ ꯁꯤꯒꯤ ꯗꯤꯄꯨꯇꯤ ꯆꯦꯌꯔꯃꯦꯟ ꯑꯃꯔꯃꯟ ꯈꯋꯥꯖꯥꯁꯨ ꯌꯥꯎꯈꯤ ꯫
--------------------------------------------------

Translating:   2%|▌                           | 20/1000 [00:19<12:20,  1.32it/s]

[20/1000]
EN: No joint declaration was issued after the four-hour meeting.
MNI_MTEI: ꯄꯨꯡ ꯃꯔꯤꯒꯤ ꯃꯤꯇꯤꯡ ꯑꯗꯨꯒꯤ ꯃꯇꯨꯡꯗ ꯄꯨꯟꯅ ꯂꯥꯎꯊꯣꯛꯄꯥ ꯑꯃꯠꯇ ꯊꯣꯛꯈꯤꯗꯦ ꯫
--------------------------------------------------

Translating:   2%|▌                           | 21/1000 [00:20<13:23,  1.22it/s]

[21/1000]
EN: The hybrid model arrangement was introduced after India refused to tour Pakistan for the 2025 Champions Trophy.
MNI_MTEI: ꯏꯪꯁꯣꯛ 2025ꯒꯤ ꯆꯦꯝꯄꯐꯤꯒꯤꯗꯃꯛ ꯚꯥꯔꯠꯅ ꯄꯥꯀꯤꯁꯇꯥꯟꯗꯥ ꯀꯣꯏꯕ ꯌꯥꯗꯕꯒꯤ ꯃꯇꯨꯡꯗ ꯍꯥꯏꯕꯗ ꯃꯣꯗꯦꯜ ꯑꯦꯔꯦꯟꯖꯃꯦꯟꯇ ꯑꯁꯤ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:   2%|▌                           | 22/1000 [00:21<12:47,  1.27it/s]

[22/1000]
EN: After extensive negotiations, a hybrid model was accepted by all parties, including the ICC.
MNI_MTEI: ꯄꯥꯛ ꯁꯟꯅ ꯋꯥꯔꯤ ꯁꯥꯔꯕ ꯃꯇꯨꯡꯗ, ꯑꯥꯏ ꯁꯤ ꯁꯤ ꯌꯥꯎꯅ ꯄꯥꯔꯇꯤ ꯄꯨꯝꯅꯃꯛꯅꯥ ꯍꯥꯏꯕꯗ ꯃꯣꯗꯦꯜ ꯑꯃ ꯑꯌꯥꯕ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:   2%|▋                           | 23/1000 [00:22<13:11,  1.23it/s]

[23/1000]
EN: The second part of the arrangement states that Pakistan will not travel to India for the 2026 T20 World Cup.
MNI_MTEI: ꯊꯧꯔꯥꯡ ꯑꯗꯨꯒꯤ ꯑꯅꯤ ꯁꯨꯕ ꯁꯔꯨꯛ ꯑꯁꯤꯅ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯄꯥꯀꯤꯁꯇꯥꯟꯅꯥ ꯏꯪ 2026 ꯒꯤ ꯇꯤ20 ꯋꯥꯔꯂꯗ ꯀꯞꯀꯤꯗꯃꯛ ꯏꯟꯗꯤꯌꯥꯗꯥ ꯆꯠꯂꯣꯏ ꯫
--------------------------------------------------

Translating:   2%|▋                           | 24/1000 [00:23<13:06,  1.24it/s]

[24/1000]
EN: As a result, all of Pakistan's matches (even if they reach the final) will be played in Sri Lanka.
MNI_MTEI: ꯃꯁꯤꯒꯤ ꯃꯍꯩ ꯑꯣꯏꯅ, ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯃꯦꯆ ꯄꯨꯝꯅꯃꯛ ( ꯀꯔꯤꯒꯨꯝꯕ ꯃꯈꯣꯏꯅ ꯐꯥꯏꯅꯦꯜꯗ ꯌꯧꯔꯕꯁꯨ ) ꯑꯁꯤꯂꯡꯀꯥꯗꯥ ꯁꯥꯟꯅꯒꯅꯤ ꯫
--------------------------------------------------

Translating:   2%|▋                           | 25/1000 [00:23<11:59,  1.36it/s]

[25/1000]
EN: Bangladesh, Pakistan, and India must be treated the same.
MNI_MTEI: ꯕꯪꯒꯂꯦꯁ, ꯄꯥꯀꯤꯁꯇꯥꯟ ꯑꯃꯁꯨꯡ ꯚꯥꯔꯠꯄꯨ ꯆꯞ ꯃꯥꯟꯅꯅꯥ ꯌꯦꯡꯁꯤꯟꯒꯗꯕꯅꯤ ꯫
--------------------------------------------------

Translating:   3%|▋                           | 26/1000 [00:24<11:02,  1.47it/s]

[26/1000]
EN: Now, Gavaskar has taken an indirect jibe at Hussain
MNI_MTEI: ꯍꯧꯖꯤꯛ ꯒꯥꯚꯥꯁꯀꯔꯅ ꯍꯨꯁꯦꯟꯗꯥ ꯍꯛꯊꯦꯡꯅꯅ ꯌꯦꯠꯂꯤ ꯫
--------------------------------------------------

Translating:   3%|▊                           | 27/1000 [00:25<12:34,  1.29it/s]

[27/1000]
EN: He went on to give the example of the 2003 World Cup, when England refused to tour Zimbabwe in protest against Robert Mugabe's regime.
MNI_MTEI: ꯃꯍꯥꯛꯅ ꯃꯈꯥ ꯇꯥꯅ ꯏꯪ 2003ꯒꯤ ꯋꯥꯔꯂꯗ ꯀꯞꯀꯤ ꯈꯨꯗꯝ ꯄꯤꯈꯤ, ꯃꯇꯝ ꯑꯗꯨꯗ ꯏꯪꯂꯦꯟꯅꯥ ꯔꯣꯕꯔꯇ ꯃꯨꯒꯥꯕꯦꯒꯤ ꯂꯩꯉꯥꯛꯀꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯖꯤꯝꯕꯥꯕꯦꯗꯥ ꯀꯣꯏꯕ ꯌꯥꯈꯤꯗꯦ ꯫
--------------------------------------------------

Translating:   3%|▊                           | 28/1000 [00:26<12:25,  1.30it/s]

[28/1000]
EN: Samson's knock was full of intent but fell short in effectiveness quotient.
MNI_MTEI: ꯁꯦꯝꯁꯣꯟꯒꯤ ꯈꯣꯡꯕ ꯑꯗꯨ ꯏꯟꯇꯦꯟꯇꯅ ꯊꯜꯂꯝꯃꯤ ꯑꯗꯨꯕꯨ ꯑꯦꯐꯦꯛꯇꯤꯚꯦꯟꯁꯤ ꯀꯣꯠꯌꯦꯟꯇꯗꯥ ꯍꯟꯊꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:   3%|▊                           | 29/1000 [00:27<13:54,  1.16it/s]

[29/1000]
EN: With this win, India overtook Pakistan at the summit of Group A courtesy of a superior net run-rate.
MNI_MTEI: ꯃꯁꯤꯒꯤ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯑꯁꯤꯒꯥ ꯂꯣꯏꯅꯅ ꯚꯥꯔꯠꯅꯄ ꯑꯦꯒꯤ ꯁꯝꯑꯦꯝꯇꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯕꯨ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯈꯤꯕꯁꯤ ꯍꯦꯟꯅ ꯐꯕ ꯅꯦꯠ ꯔꯟ-ꯔꯦꯇ ꯂꯩꯕꯅꯅꯤ ꯫
--------------------------------------------------

Translating:   3%|▊                           | 30/1000 [00:28<14:53,  1.09it/s]

[30/1000]
EN: India batter Abhishek Sharma will take no part in the T20 World Cup 2026 clash against Namibia in New Delhi on Thursday.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯕꯦꯇꯇꯔ ꯑꯚꯥꯁꯤꯛ ꯁꯔꯃꯥꯅꯥ ꯇꯤ20 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞ 2026ꯗꯥ ꯁꯨꯔꯦꯁꯥ ꯅꯨꯃꯤꯠꯇ ꯅ ꯗꯤꯜꯂꯤꯗꯥ ꯅꯥꯏꯃꯤꯕꯥꯒ ꯂꯥꯟꯊꯦꯡꯅꯕꯗ ꯁꯔꯨꯛ ꯌꯥꯔꯣꯏ ꯫
--------------------------------------------------

Translating:   3%|▊                           | 31/1000 [00:28<13:31,  1.19it/s]

[31/1000]
EN: Abhishek isn't fine still, might take one or two games.
MNI_MTEI: ꯑꯕꯤꯆꯦꯛ ꯑꯁꯤ ꯍꯧꯖꯤꯛꯁꯨ ꯐꯗ, ꯒꯦꯝ ꯑꯃ ꯅꯠꯇꯒꯥ ꯑꯅꯤ ꯂꯧꯕ ꯌꯥꯏ ꯫
--------------------------------------------------

Translating:   3%|▉                           | 32/1000 [00:29<11:07,  1.45it/s]

[32/1000]
EN: Samson comes in.
MNI_MTEI: ꯁꯦꯝꯁꯣꯟ ꯆꯪꯁꯤꯜꯂꯛꯏ ꯫
--------------------------------------------------

Translating:   3%|▉                           | 33/1000 [00:30<11:10,  1.44it/s]

[33/1000]
EN: Bumrah comes in for Siraj," said Suryakumar at the toss.
MNI_MTEI: ꯕꯔꯥꯅꯥ ꯁꯤꯔꯥꯖꯒꯤ ꯃꯍꯨꯠꯇ ꯆꯪꯁꯤꯜꯂꯛꯏ ꯍꯥꯏꯅ ꯁꯨꯔꯌꯀꯨꯃꯔꯅꯥ ꯇꯣꯁ ꯇꯧꯕ ꯃꯇꯝꯗ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:   3%|▉                           | 34/1000 [00:30<12:09,  1.32it/s]

[34/1000]
EN: Defending with dew will build our confidence. Hope our batters entertain the crowd.
MNI_MTEI: ꯆꯣꯠ-ꯆꯣꯠꯅꯥ ꯉꯥꯛꯊꯣꯛꯄꯥ ꯑꯁꯤꯅ ꯑꯩꯈꯣꯏꯒꯤ ꯊꯥꯖꯕ ꯍꯦꯟꯒꯠꯍꯟꯒꯅꯤ ꯫ ꯑꯥꯁꯥ ꯂꯩ ꯃꯗꯨꯗꯤꯕꯥ ꯕꯦꯠꯇꯔꯁꯤꯡꯅ ꯃꯤꯌꯥꯝꯕꯨ ꯅꯨꯡꯉꯥꯏꯍꯟ
--------------------------------------------------

Translating:   4%|▉                           | 35/1000 [00:31<11:07,  1.45it/s]

[35/1000]
EN: It's a big tournament, dew will be a big factor.
MNI_MTEI: ꯃꯁꯤ ꯑꯆꯧꯕ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯃꯅꯤ, ꯗ ꯑꯁꯤ ꯑꯆꯧꯕ ꯐꯦꯛꯇꯔ ꯑꯃ ꯑꯣꯏꯒꯅꯤ ꯫
--------------------------------------------------

Translating:   4%|█                           | 36/1000 [00:32<11:31,  1.39it/s]

[36/1000]
EN: India made two changes to the side that beat the USA on the opening day of the tournament.
MNI_MTEI: ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯁꯤꯒꯤ ꯑꯍꯥꯟꯕꯥ ꯅꯨꯃꯤꯠꯗꯥ ꯌꯨꯑꯦꯁꯑꯦꯕꯨ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯔꯕꯥ ꯁꯥꯏꯗ ꯑꯁꯤꯗ ꯚꯥꯔꯠꯅ ꯑꯅꯤ ꯍꯣꯡꯗꯣꯛ
--------------------------------------------------

Translating:   4%|█                           | 37/1000 [00:33<12:44,  1.26it/s]

[37/1000]
EN: Sanju Samson replaced Abhishek, while Jasprit Bumrah replaced Mohammed Siraj in the India XI.
MNI_MTEI: ꯑꯕꯤꯆꯦꯛꯀꯤ ꯃꯐꯝꯗꯥ ꯁꯟꯖꯨ ꯁꯦꯝꯁꯣꯟ ꯑꯃꯁꯨꯡ ꯏꯟꯗꯤꯌꯥ XI ꯗꯥ ꯃꯣꯍꯝꯃꯗ ꯁꯤꯔꯥꯖꯒꯤ ꯃꯐꯝꯗ ꯖꯁꯄꯤꯇ ꯕꯃꯔꯥꯅ ꯐꯝ ꯂꯧ
--------------------------------------------------

Translating:   4%|█                           | 38/1000 [00:34<12:57,  1.24it/s]

[38/1000]
EN: India take on Pakistan next, with the team set to travel to Colombo for the game on February 15.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯃꯊꯪꯗꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯥ ꯂꯝꯕꯥ ꯇꯧꯒꯅꯤ, ꯇꯤꯝ ꯑꯁꯤ ꯐꯕꯋꯥꯔꯤꯗꯥ ꯃꯁꯥꯟꯅ ꯑꯁꯤꯒꯤꯗꯃꯛ ꯀꯣꯂꯝꯕꯣꯗꯥ ꯆꯠꯀꯅꯤ ꯫
--------------------------------------------------

Translating:   4%|█                           | 39/1000 [00:34<12:00,  1.33it/s]

[39/1000]
EN: The cabinet agreed with certain conditions as per the Cunha report.
MNI_MTEI: ꯀꯨꯅꯍꯥ ꯔꯤꯄꯣꯔꯇꯀꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯀꯦꯕꯤꯅꯦꯠꯅꯥ ꯑꯀꯛꯅꯕ ꯀꯟꯗꯤꯁꯟꯁꯤꯡ ꯌꯥꯅꯈꯤ ꯫
--------------------------------------------------

Translating:   4%|█                           | 40/1000 [00:35<11:01,  1.45it/s]

[40/1000]
EN: He mentioned in the report a maximum of 35,000 people and other conditions.
MNI_MTEI: ꯃꯍꯥꯛꯅ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯗ ꯃꯤ 35,000 ꯑꯃꯁꯨꯡ ꯑꯇꯩ ꯐꯤꯚꯝꯁꯤꯡ ꯄꯟꯈꯤ ꯫
--------------------------------------------------

Translating:   4%|█▏                          | 41/1000 [00:36<12:58,  1.23it/s]

[41/1000]
EN: India reached the 100-run mark in just 6.5 overs - the fastest team hundred in T20 World Cup history.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯑꯣꯚꯔ ꯈꯛꯇꯗꯥ ꯔꯟꯒꯤ ꯃꯥꯔꯛ ꯌꯧꯈꯤ - ꯃꯁꯤ ꯇꯤ20 ꯋꯥꯔꯜꯗ ꯀꯞꯀꯤ ꯍꯤꯁꯇꯔꯤꯗꯥ ꯊꯨꯅ ꯇꯧꯕ ꯇꯤꯝ ꯁꯦꯟꯆꯨꯔꯤ
--------------------------------------------------

Translating:   4%|█▏                          | 42/1000 [00:37<12:33,  1.27it/s]

[42/1000]
EN: After being asked to bat first, India were off to a decent start, making 8/0 in the first over.
MNI_MTEI: ꯑꯍꯥꯟꯕꯗꯥ ꯕꯦꯇ ꯇꯧꯅꯕ ꯍꯥꯏꯔꯕ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯅ ꯑꯍꯥꯟꯕꯥ ꯑꯣꯚꯔꯗꯥ/0 ꯂꯧꯗꯨꯅ ꯐꯖꯅ ꯍꯧ
--------------------------------------------------

Translating:   4%|█▏                          | 43/1000 [00:37<12:54,  1.24it/s]

[43/1000]
EN: After four overs, the defending champions reached 43/1, with Ishan Kishan finding a couple of boundaries.
MNI_MTEI: ꯑꯣꯚꯔ ꯃꯔꯤꯒꯤ ꯃꯇꯨꯡꯗ, ꯗꯤꯐꯟꯗꯤꯡ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯡꯅ 43/1 ꯌꯧꯈꯤ, ꯏꯁꯥꯟ ꯀꯤꯁꯟꯅ ꯐꯥꯎꯟꯗꯔꯤ ꯑꯅꯤ ꯐꯪ
--------------------------------------------------

Translating:   4%|█▏                          | 44/1000 [00:39<14:15,  1.12it/s]

[44/1000]
EN: On the first ball of the 11th over, spinner Bernard Scholtz dismissed captain Suryakumar Yadav for just 12.
MNI_MTEI: 11 ꯁꯨꯕꯥ ꯑꯣꯚꯔꯒꯤ ꯑꯍꯥꯟꯕꯥ ꯕꯣꯂꯗꯥ ꯁꯄꯤꯅꯔ ꯕꯔꯅꯥꯗ ꯁꯀꯣꯜꯇꯖꯅ ꯀꯦꯞꯇꯦꯟ ꯁꯨꯔꯌꯀꯨꯃꯔ ꯌꯥꯗꯕꯕꯨ 12 ꯈꯛꯇꯗꯥ ꯕꯣꯜ ꯂꯧꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:   4%|█▎                          | 45/1000 [00:40<15:22,  1.04it/s]

[45/1000]
EN: India lost another wicket quickly when Tilak Varma was removed for 25 by Namibia skipper Erasmus in the 12th over.
MNI_MTEI: ꯇꯤꯂꯛ ꯕꯔꯃꯥꯕꯨ ꯅꯤꯃꯤꯕꯥꯒꯤ ꯀꯦꯞꯇꯦꯟ ꯏꯔꯥꯁꯃꯁꯅꯥ 12 ꯁꯨꯕꯥ ꯑꯣꯚꯔꯗꯥ 25 ꯗꯥ ꯑꯥꯎꯠ ꯇꯧꯈꯤꯕꯗꯒꯤ ꯚꯥꯔꯠꯅ ꯑꯇꯣꯞꯄ ꯋꯤꯀꯦꯇ ꯑꯃ ꯊꯨꯅ ꯃꯥꯡꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▎                          | 46/1000 [00:41<15:50,  1.00it/s]

[46/1000]
EN: Shivam Dube and Hardik Pandya then combined to hammer 24 runs off Bernard Scholtz as India raced to 168/4.
MNI_MTEI: ꯃꯗꯨꯒꯤ ꯃꯇꯨꯡꯗ ꯁꯤꯚꯝ ꯗꯨꯕꯦ ꯑꯃꯁꯨꯡ ꯍꯔꯗꯤꯛ ꯄꯥꯟꯗꯅꯥ ꯕꯔꯅꯥꯔ ꯁꯀꯣꯜꯇꯖꯗꯥ ꯔꯟ 24 ꯆꯡꯗꯨꯅ ꯚꯥꯔꯠꯇꯥ/ ꯗꯥ ꯆꯪꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▎                          | 47/1000 [00:42<14:59,  1.06it/s]

[47/1000]
EN: By the end of the 18th over, India had reached 199/4 with Pandya and Dube going strong.
MNI_MTEI: 18 ꯁꯨꯕꯥ ꯑꯣꯚꯔ ꯂꯣꯏꯔꯛꯄꯗꯥ ꯄꯥꯟꯗ ꯑꯃꯁꯨꯡ ꯗꯨꯕꯦꯅꯥ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯄꯥꯒ ꯂꯣꯏꯅꯅꯥ ꯚꯥꯔꯠꯅ/ ꯌꯧꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▎                          | 48/1000 [00:43<15:23,  1.03it/s]

[48/1000]
EN: On the first ball of the 19th over, Pandya completed his fifty off 27 deliveries as India crossed the 200-run mark.
MNI_MTEI: 19 ꯁꯨꯕꯥ ꯑꯣꯚꯔꯒꯤ ꯑꯍꯥꯟꯕꯥ ꯕꯣꯂꯗꯥ ꯄꯥꯟꯗꯌꯥꯅꯥ ꯃꯍꯥꯛꯀꯤ ꯐꯤꯐꯇꯤ ꯑꯗꯨ 27 ꯗꯥ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯑꯃꯁꯨꯡ ꯚꯥꯔꯠꯅ ꯔꯟ 200 ꯄꯥꯊꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▎                          | 49/1000 [00:43<14:09,  1.12it/s]

[49/1000]
EN: Shivam Dube was run out for 23 after a mix-up with Rinku Singh.
MNI_MTEI: ꯁꯤꯚꯝ ꯗꯨꯕꯦ ꯔꯤꯟꯀꯨ ꯁꯤꯡꯍꯒꯥ ꯌꯥꯟꯁꯤꯟꯅꯔꯕꯥ ꯃꯇꯨꯡꯗ 23 ꯗꯥ ꯔꯟꯑꯥꯎꯇ ꯑꯣꯏꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▍                          | 50/1000 [00:44<14:48,  1.07it/s]

[50/1000]
EN: India then lost Rinku Singh (1) and Arshdeep Singh (2) in the final over, finishing at 209/9.
MNI_MTEI: ꯃꯗꯨꯒꯤ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯅ ꯑꯔꯣꯏꯕ ꯑꯣꯚꯔꯗꯥ ꯔꯤꯟꯀꯨ ꯁꯤꯡꯍ (1 ) ꯑꯃꯁꯨꯡ ꯑꯥꯔꯁꯗꯤꯄ ꯁꯤꯡꯍꯕꯨ (2 ) ꯃꯥꯡꯈꯤ, ꯃꯗꯨꯅ/9 ꯗꯥ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▍                          | 51/1000 [00:46<17:05,  1.08s/it]

[51/1000]
EN: ICC Men’s T20 World Cup 2026 began on February 7, 2026, at Sinhalese Sports Club Ground with Pakistan playing Netherlands in the opening match.
MNI_MTEI: ꯑꯥꯏ ꯁꯤ ꯁꯤ ꯃꯦꯟꯒꯤ ꯇꯤ20 ꯋꯥꯔꯂꯗ ꯀꯞ 2026 ꯑꯁꯤ ꯏꯪꯁꯣꯛ ꯒꯤ ꯐꯦꯕꯋꯥꯔꯤ ꯗꯥ ꯁꯤꯟꯍꯥꯂꯤꯁꯄꯣꯔꯇꯕꯥꯎꯟꯗꯗꯥ ꯍꯧꯈꯤ ꯑꯃꯁꯨꯡ ꯑꯍꯥꯟꯕ ꯃꯦꯆ ꯑꯗꯨꯗ ꯅꯦꯗꯔꯂꯦꯟꯗꯁꯀ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯥ ꯁꯥꯟꯅꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▍                          | 52/1000 [00:47<17:29,  1.11s/it]

[52/1000]
EN: Bangladesh national cricket team faced the India men's national cricket team in an opening match reported ahead of the 2026 T20 tournament.
MNI_MTEI: ꯏꯪꯁꯣꯛ 2026 ꯒꯤ ꯇꯤ20 ꯇꯣꯔꯅꯥꯃꯦꯟꯇꯒꯤ ꯃꯃꯥꯡꯗ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯑꯍꯥꯟꯕꯥ ꯃꯦꯆ ꯑꯃꯗ ꯕꯪꯒꯂꯦꯁ ꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯇꯤꯝꯅꯥ ꯏꯟꯗꯤꯌꯥ ꯃꯦꯟ ꯭ ꯁ ꯅꯦꯁꯅꯦꯜꯀꯦꯇ ꯇꯤꯝꯒꯥ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▍                          | 53/1000 [00:47<14:47,  1.07it/s]

[53/1000]
EN: Ishan Kishan struck a rapid half-century.
MNI_MTEI: ꯏꯁꯥꯟ ꯀꯤꯁꯟꯅ ꯌꯥꯝꯅ ꯊꯨꯅ ꯁꯦꯟꯆꯨꯔꯤ ꯍꯥꯐ ꯂꯧꯈꯤ ꯫
--------------------------------------------------

Translating:   5%|█▌                          | 54/1000 [00:48<14:54,  1.06it/s]

[54/1000]
EN: Faf du Plessis scored a half-century and Mitchell Starc took a five-wicket haul in the same match report.
MNI_MTEI: ꯐꯐ ꯗꯨꯂꯤꯁ ꯍꯥꯐ-ꯆꯦꯟꯆꯨꯔꯤ ꯑꯃꯥ ꯂꯧꯈꯤ ꯑꯃꯁꯨꯡ ꯃꯤꯆꯦꯜꯔꯀꯅꯥ ꯃꯦꯆ ꯑꯁꯤꯒꯤ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯃꯛꯇꯗꯥ ꯋꯤꯀꯦꯇ ꯃꯉꯥ ꯂꯧ
--------------------------------------------------

Translating:   6%|█▌                          | 55/1000 [00:50<16:11,  1.03s/it]

[55/1000]
EN: Jasprit Bumrah and Ravindra Jadeja were reported to have been demoted in the 2025–26 central contracts discussion.
MNI_MTEI: ꯖꯁꯄꯤꯇ ꯕꯃꯔꯥ ꯑꯃꯁꯨꯡ ꯔꯕꯤꯟꯗ ꯖꯗꯦꯖꯥ ꯑꯁꯤ ꯏꯪ 2025-26 ꯒꯤ ꯁꯦꯟꯇꯦꯜ ꯀꯟꯇꯛꯇꯁꯤꯡꯒꯤ ꯈꯟꯅ-ꯆꯠꯇꯗꯥ ꯗꯤꯃꯣꯇ ꯇꯧ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝꯈꯤ ꯫
--------------------------------------------------

Translating:   6%|█▌                          | 56/1000 [00:51<15:35,  1.01it/s]

[56/1000]
EN: Rohit Sharma carried the men’s T20 World Cup trophy during a promotional appearance.
MNI_MTEI: ꯔꯣꯍꯤꯇ ꯁꯔꯃꯥꯅꯥ ꯅꯨꯄꯥꯁꯤꯡꯒꯤ ꯇꯤ20 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞꯀꯤ ꯇꯐꯤ ꯑꯗꯨ ꯄꯃꯣꯁꯅꯦꯜꯒꯤ ꯊꯧꯔꯝ ꯑꯃꯗ ꯄꯥꯏ
--------------------------------------------------

Translating:   6%|█▌                          | 57/1000 [00:52<16:11,  1.03s/it]

[57/1000]
EN: The International Cricket Council update said a high-profile match involving Pakistan would go ahead on February 15, 2026, in Colombo.
MNI_MTEI: ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯀꯥꯎꯟꯁꯤꯜ ꯑꯞꯇꯦꯠꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯄꯥꯀꯤꯁꯇꯥꯟ ꯌꯥꯎꯕꯥ ꯑꯋꯥꯡꯕ ꯊꯥꯛꯀꯤ ꯃꯦꯆ ꯑꯃꯥ ꯏꯪꯁꯣꯛꯒꯤ ꯐꯦꯕꯋꯥꯔꯤꯗꯥ ꯀꯣꯂꯝꯕꯣꯗꯥ ꯄꯥꯡꯊꯣꯛꯀꯅꯤ ꯫
--------------------------------------------------

Translating:   6%|█▌                          | 58/1000 [00:53<15:55,  1.01s/it]

[58/1000]
EN: The New Zealand national cricket team lost the first ODI by four wickets to the India men's national cricket team.
MNI_MTEI: ꯅꯌꯨ ꯖꯤꯂꯦꯟꯗ ꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯇꯤꯝ ꯑꯁꯤ ꯑꯍꯥꯟꯕ ꯑꯣꯗꯤꯑꯥꯏ ꯑꯗꯨ ꯏꯟꯗꯤꯌꯥ ꯃꯦꯟ ꯭ ꯁ ꯅꯦꯁꯅꯦꯜꯀꯦꯇ ꯇꯤꯝꯗꯥ ꯋꯤꯀꯇꯤꯠ ꯃꯔꯤꯅꯥ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:   6%|█▋                          | 59/1000 [00:54<17:24,  1.11s/it]

[59/1000]
EN: Australia national cricket team ended day one at 67 for seven in reply to 150 by the India men's national cricket team in a Test match post.
MNI_MTEI: ꯑꯣꯁꯇꯂꯤꯌꯥ ꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯇꯤꯝꯅꯥ ꯇꯦꯁꯇ ꯃꯦꯆ ꯄꯣꯁ ꯭ ꯠ ꯑꯃꯗ ꯏꯟꯗꯤꯌꯥ ꯃꯦꯟ ꯭ ꯁ ꯅꯦꯁꯅꯦꯜ ꯀꯔꯦꯀꯦꯠ ꯇꯤꯝꯅ ꯄꯤꯈꯤꯕ 150 ꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯑꯍꯥꯟꯕ ꯅꯨꯃꯤꯠꯗꯥ ꯁꯇꯦꯅꯗ ꯂꯧ
--------------------------------------------------

Translating:   6%|█▋                          | 60/1000 [00:55<19:13,  1.23s/it]

[60/1000]
EN: The India national under-19 cricket team won the ICC U19 World Cup final by 100 runs against the England national under-19 cricket team in Harare.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯅꯦꯁꯅꯦꯜ ꯑꯟꯗꯔ-19 ꯀꯀꯦꯠ ꯇꯤꯝꯅꯥ ꯍꯔꯥꯔꯦꯗꯥ ꯄꯥꯡꯊꯣꯛꯂꯤꯕꯥ ꯑꯥꯏ ꯁꯤ ꯁꯤ ꯎꯅ 19 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞꯀꯤ ꯐꯥꯏꯅꯦꯜꯗꯥ ꯏꯡꯒꯂꯦꯟꯗ ꯅꯦꯁꯅꯦꯜ ꯑꯥꯟꯗꯔ-ꯀꯤꯠ ꯇꯤꯝꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯔꯟ ꯆꯥꯅꯥ ꯃꯥꯏꯄꯥꯛ
--------------------------------------------------

Translating:   6%|█▋                          | 61/1000 [00:56<17:21,  1.11s/it]

[61/1000]
EN: Members of the India women's national cricket team were given a grand welcome after their title-winning campaign.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯇꯤꯝꯒꯤ ꯃꯤꯍꯨꯠꯁꯤꯡꯕꯨ ꯃꯈꯣꯏꯒꯤ ꯇꯥꯏꯇꯜ ꯃꯥꯏ ꯄꯥꯛꯄꯥ ꯀꯝꯄꯦꯟꯒꯤ ꯃꯇꯨꯡꯗ ꯆꯥꯎꯔꯕꯥ ꯃꯅꯥ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:   6%|█▋                          | 62/1000 [00:57<16:37,  1.06s/it]

[62/1000]
EN: The India women's national cricket team lifting the ICC Women’s World Cup as one of the year’s landmark moments.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯇꯤꯝꯅꯥ ꯑꯥꯏ ꯁꯤ ꯁꯤ ꯅꯨꯄꯤꯒꯤ ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞ ꯑꯁꯤ ꯆꯍꯤ ꯑꯁꯤꯒꯤ ꯃꯁꯛ ꯊꯣꯛꯄ ꯃꯨꯅꯇꯁꯤꯡꯒꯤ ꯃꯅꯨꯡꯗ ꯑꯃꯥ ꯑꯣꯏꯅ ꯄꯥꯏꯈꯠꯂꯤ ꯫
--------------------------------------------------

Translating:   6%|█▊                          | 63/1000 [00:58<16:26,  1.05s/it]

[63/1000]
EN: The Indian Premier League season in 2025 was reported as suspended indefinitely amid escalating India–Pakistan military tensions.
MNI_MTEI: ꯏꯪꯁꯣꯛ 2025 ꯗꯥ ꯏꯟꯗꯤꯌꯟꯃꯤꯌꯔ ꯂꯤꯒ ꯁꯤꯖꯟ ꯑꯁꯤ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯃꯤꯂꯤꯇꯔꯤ ꯇꯦꯟꯁꯟꯁꯤꯡ ꯍꯦꯟꯒꯠꯂꯛꯄꯒꯤ ꯃꯔꯛꯇ ꯃꯇꯝ ꯈꯔꯒꯤ ꯑꯣꯏꯅ ꯂꯦꯞꯈꯤ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝꯈꯤ ꯫
--------------------------------------------------

Translating:   6%|█▊                          | 64/1000 [00:59<15:28,  1.01it/s]

[64/1000]
EN: The Eden Gardens hosted the opening spectacle for the 18th edition of the Indian Premier League.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟꯃꯤꯌꯔ ꯂꯤꯒꯀꯤ 18 ꯁꯨꯕꯥ ꯑꯦꯗꯤꯁꯟ ꯑꯁꯤꯒꯤ ꯑꯍꯥꯟꯕꯥ ꯃꯃꯤ ꯀꯨꯝꯍꯩ ꯑꯗꯨ ꯏꯗꯦꯟ ꯒꯥꯔꯗꯦꯟꯁꯅꯥ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:   6%|█▊                          | 65/1000 [01:00<15:05,  1.03it/s]

[65/1000]
EN: Royal Challengers Bengaluru named Rajat Patidar as captain for the season starting March 21.
MNI_MTEI: ꯔꯣꯌꯦꯜ ꯆꯦꯂꯦꯟꯖꯔ ꯕꯦꯡꯂꯨꯨꯔꯥꯅꯥ ꯃꯥꯔꯗꯒꯤ ꯍꯧꯕꯥ ꯁꯤꯖꯟ ꯑꯁꯤꯒꯤ ꯀꯦꯞꯇꯦꯟ ꯑꯣꯏꯅ ꯔꯥꯖꯥꯇ ꯄꯥꯇꯤꯗꯥꯔꯕꯨ ꯈꯟꯈꯤ ꯫
--------------------------------------------------

Translating:   7%|█▊                          | 66/1000 [01:01<14:28,  1.07it/s]

[66/1000]
EN: Chennai Super Kings posted their lowest home total and suffered a fifth straight loss.
MNI_MTEI: ꯆꯦꯟꯅꯥꯏ ꯁꯨꯄꯔ ꯀꯤꯡꯁꯅ ꯃꯈꯣꯏꯒꯤ ꯅꯦꯝꯕꯥ ꯍꯣꯝ ꯇꯣꯇꯥꯜ ꯄꯣꯁ ꯭ ꯠ ꯇꯧꯈꯤ ꯑꯃꯁꯨꯡ ꯃꯊꯪꯅꯥ ꯃꯉꯥꯁꯨꯕꯗꯥ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:   7%|█▉                          | 67/1000 [01:02<14:09,  1.10it/s]

[67/1000]
EN: A Dharamsala fixture involving Punjab Kings and Delhi Capitals was called off after a blackout.
MNI_MTEI: ꯄꯟꯖꯥꯕ ꯀꯤꯡꯁ ꯑꯃꯁꯨꯡ ꯗꯤꯜꯂꯤ ꯀꯦꯄꯤꯇꯦꯜꯁꯤꯡ ꯌꯥꯎꯕꯥ ꯙꯔꯃꯁꯥꯂꯥ ꯐꯤꯆꯆꯔ ꯑꯃ ꯕꯦꯛꯑꯥꯎꯇ ꯑꯃꯒꯤ ꯃꯇꯨꯡꯗ ꯊꯤꯡꯖꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:   7%|█▉                          | 68/1000 [01:03<13:25,  1.16it/s]

[68/1000]
EN: Punjab Kings defeated Mumbai Indians in Jaipur to secure a top-two league finish.
MNI_MTEI: ꯄꯟꯖꯥꯕ ꯀꯤꯡꯁꯅ ꯃꯨꯝꯕꯥꯏ ꯏꯟꯗꯤꯌꯟꯁꯄꯨ ꯖꯦꯄꯨꯔꯗꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯗꯨꯅ ꯇꯣꯞ-ꯇꯧꯄ ꯂꯤꯒ ꯂꯣꯏꯁꯤꯟ
--------------------------------------------------

Translating:   7%|█▉                          | 69/1000 [01:04<14:11,  1.09it/s]

[69/1000]
EN: KL Rahul became the fastest Indian to 8,000 T20 runs after an unbeaten 112.
MNI_MTEI: ꯀꯦ ꯑꯦꯜ ꯔꯥꯍꯨꯜꯅꯥ ꯑꯇꯤꯇꯥꯏꯕ ꯇꯧꯗꯕꯥ ꯔꯟ 112 ꯂꯧꯔꯕꯥ ꯃꯇꯨꯡꯗ ꯇꯤ20 ꯗꯥ ꯔꯅ 8,000 ꯂꯧꯕꯥ ꯈ ꯭ ꯋꯥꯏꯗꯒꯤ ꯊꯨꯅ ꯇꯧꯕ ꯏꯟꯗꯤꯌꯟ ꯑꯣꯏꯈꯤ ꯫
--------------------------------------------------

Translating:   7%|█▉                          | 70/1000 [01:04<14:09,  1.09it/s]

[70/1000]
EN: Virat Kohli spoke about the June 4 stampede linked to his franchise’s celebrations.
MNI_MTEI: ꯕꯤꯔꯥꯇ ꯀꯣꯍꯂꯤꯅꯥ ꯖꯨꯟꯇꯥ ꯃꯍꯥꯛꯀꯤ ꯐꯔꯦꯟꯆꯥꯏꯖꯤꯒꯤ ꯊꯧꯔꯝꯒꯥ ꯃꯔꯤ ꯂꯩꯅꯅ ꯊꯣꯛꯈꯤꯕ ꯁꯀꯦꯝꯄꯤꯗꯦꯒꯤ ꯃꯇꯥꯡꯗ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:   7%|█▉                          | 71/1000 [01:05<13:36,  1.14it/s]

[71/1000]
EN: The uncertainty over player retention created suspense ahead of the next Indian Premier League season.
MNI_MTEI: ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡ ꯊꯝꯕꯗꯥ ꯑꯔꯦꯞꯄ ꯂꯩꯇꯕꯥ ꯑꯁꯤꯅ ꯃꯊꯪꯒꯤ ꯏꯟꯗꯤꯌꯟꯃꯤꯌꯔ ꯂꯤꯒ ꯁꯤꯖꯟ ꯑꯁꯤꯒꯤ ꯃꯃꯥꯡꯗ ꯁꯁꯄꯦꯟꯁ ꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:   7%|██                          | 72/1000 [01:06<11:51,  1.30it/s]

[72/1000]
EN: Rafael Nadal announced he would retire.
MNI_MTEI: ꯔꯥꯐꯦꯜ ꯅꯥꯗꯥꯜꯅꯥ ꯃꯍꯥꯛꯅ ꯔꯤꯇꯔ ꯇꯧꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:   7%|██                          | 73/1000 [01:07<12:12,  1.27it/s]

[73/1000]
EN: Carlos Alcaraz beat Novak Djokovic to win his first major title.
MNI_MTEI: ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯅꯣꯕꯥꯛ ꯖꯣꯀꯣꯚꯤꯀꯄꯨ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯗꯨꯅ ꯃꯍꯥꯛꯀꯤ ꯑꯍꯥꯟꯕꯥ ꯃꯦꯒꯔ ꯇꯥꯏꯇꯥꯜ ꯑꯗꯨ ꯐꯪ
--------------------------------------------------

Translating:   7%|██                          | 74/1000 [01:07<12:37,  1.22it/s]

[74/1000]
EN: Alexander Zverev lost a marathon match to Carlos Alcaraz in a five-set battle.
MNI_MTEI: ꯑꯂꯦꯛꯖꯦꯟꯗꯔ ꯖꯚꯦꯔꯦꯚꯅꯥ ꯁꯦꯇ ꯃꯉꯥꯒꯤ ꯂꯥꯟꯗꯥ ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯒꯥ ꯃꯥꯔꯥꯊꯣꯟ ꯃꯦꯆ ꯑꯃ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:   8%|██                          | 75/1000 [01:08<12:06,  1.27it/s]

[75/1000]
EN: Rohan Bopanna announced his retirement from professional tennis.
MNI_MTEI: ꯔꯣꯍꯟ ꯕꯣꯄꯟꯅꯥꯅꯥ ꯄꯐꯦꯁꯅꯦꯜ ꯇꯦꯅꯤꯁꯇꯒꯤ ꯃꯍꯥꯛꯀꯤ ꯔꯤꯑꯥꯏꯇꯔꯃꯦꯟꯠ ꯑꯗꯨ ꯂꯥꯎꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:   8%|██▏                         | 76/1000 [01:09<12:41,  1.21it/s]

[76/1000]
EN: A 14-place leap that signaled an upswing for India Davis Cup team in international tennis standings.
MNI_MTEI: ꯏꯟꯗꯤꯌꯥ ꯗꯦꯚꯤꯁ ꯀꯄ ꯇꯤꯝꯒꯤꯗꯃꯛ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯇꯦꯅꯤꯁ ꯁꯇꯦꯟꯗꯤꯡꯗꯥ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯕꯒꯤ ꯈꯨꯗꯝ ꯄꯤꯔꯕꯥ ꯃꯐꯝ 14ꯒꯤ ꯂꯤꯞ ꯑꯃꯥ
--------------------------------------------------

Translating:   8%|██▏                         | 77/1000 [01:10<13:26,  1.14it/s]

[77/1000]
EN: Elena Rybakina overcame Aryna Sabalenka to win the 2026 Australian Open final.
MNI_MTEI: ꯑꯦꯂꯦꯅꯥ ꯔꯥꯏꯕꯥꯀꯤꯅꯥꯅꯥ ꯑꯔꯅꯥ ꯁꯕꯥꯂꯦꯟꯀꯥꯕꯨ ꯃꯥꯏꯊꯤꯗꯨꯅꯥ ꯏꯪꯁꯣꯛ 2026 ꯑꯣꯁꯇꯂꯤꯌꯥ ꯑꯣꯄꯟ ꯐꯥꯏꯅꯦꯜꯗꯥ ꯃꯥꯏꯄꯥꯛ
--------------------------------------------------

Translating:   8%|██▏                         | 78/1000 [01:11<13:30,  1.14it/s]

[78/1000]
EN: Novak Djokovic became the first player to reach 400 Grand Slam singles match wins in the Open Era.
MNI_MTEI: ꯑꯣꯄꯟ ꯏꯔꯥꯗꯥ ꯅꯣꯕꯥꯛ ꯖꯣꯀꯣꯚꯤꯀꯅꯥꯥꯟꯗ ꯁꯂꯥꯝ ꯁꯤꯡꯒꯜꯁ ꯃꯦꯆ 400 ꯃꯥꯏ ꯄꯥꯛꯄꯥ ꯑꯍꯥꯟꯕ ꯁꯥꯟꯅꯔꯣꯏ ꯑꯣꯏꯈꯤ ꯫
--------------------------------------------------

Translating:   8%|██▏                         | 79/1000 [01:12<13:26,  1.14it/s]

[79/1000]
EN: The India men's national field hockey team and its Olympic bronze-medal campaign in a dedicated post.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯥꯁꯤꯡꯒꯤ ꯅꯦꯁꯅꯦꯜ ꯐꯤꯜꯗ ꯍꯣꯀꯤ ꯇꯤꯝ ꯑꯃꯁꯨꯡ ꯃꯁꯤꯒꯤ ꯑꯣꯂꯤꯝꯄꯤꯛꯣꯟꯖ-ꯃꯦꯗꯦꯜ ꯀꯦꯝꯄꯦꯟ ꯑꯁꯤ ꯀꯠꯊꯣꯛꯂꯕ ꯄꯣꯇ ꯑꯃꯗ
--------------------------------------------------

Translating:   8%|██▏                         | 80/1000 [01:12<12:12,  1.26it/s]

[80/1000]
EN:  The India men's national field hockey team across major tournaments.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯥꯁꯤꯡꯒꯤ ꯅꯦꯁꯅꯦꯜ ꯐꯤꯜꯗ ꯍꯣꯀꯤ ꯇꯤꯝꯅꯥ ꯑꯆꯧꯕ ꯇꯨꯔꯥꯅꯃꯦꯟꯇꯁꯤꯡ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:   8%|██▎                         | 81/1000 [01:13<13:01,  1.18it/s]

[81/1000]
EN: The India men's national field hockey team beat South Korea men's national field hockey team 4–1 in a match update.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯥꯁꯤꯡꯒꯤ ꯅꯦꯁꯅꯦꯜ ꯐꯤꯜꯗ ꯍꯣꯀꯤ ꯇꯤꯝꯅꯥ ꯃꯦꯆ ꯑꯞꯇꯦꯠ ꯑꯃꯗ ꯁꯥꯎꯊ ꯀꯣꯔꯤꯌꯥ ꯃꯦꯟꯁꯀꯤ ꯅꯦꯁꯅꯦꯜ ꯐꯤꯜꯗ ꯍꯣꯛꯀꯤ ꯇꯤꯝ 4/1 ꯗꯥ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:   8%|██▎                         | 82/1000 [01:14<12:17,  1.24it/s]

[82/1000]
EN: The house of K. D. Singh Babu would be developed as a tourist attraction.
MNI_MTEI: ꯀꯦ. ꯗꯤ. ꯁꯤꯡꯍ ꯕꯥꯕꯨꯒꯤ ꯌꯨꯝ ꯑꯁꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯟꯅꯤꯡꯉꯥꯏ ꯑꯣꯏꯕ ꯃꯐꯝ ꯑꯃ ꯑꯣꯏꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:   8%|██▎                         | 83/1000 [01:15<11:01,  1.39it/s]

[83/1000]
EN: Lakshya Sen finished fourth in a tournament.
MNI_MTEI: ꯂꯛꯁꯌ ꯁꯦꯟꯅ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯃꯗ ꯃꯔꯤ ꯁꯨꯕꯥ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:   8%|██▎                         | 84/1000 [01:15<11:15,  1.36it/s]

[84/1000]
EN: Saina Nehwal confirmed her retirement from competitive badminton.
MNI_MTEI: ꯁꯥꯏꯅꯥ ꯅꯦꯍꯋꯥꯜꯅ ꯃꯍꯥꯛ ꯀꯝꯄꯤꯇꯦꯇꯤꯚ ꯕꯦꯗꯃꯤꯟꯇꯟꯗꯒꯤ ꯔꯤꯇꯔꯥꯏꯑꯃꯦꯟꯠ ꯂꯧꯔꯦ ꯍꯥꯏꯕ ꯈꯪ
--------------------------------------------------

Translating:   8%|██▍                         | 85/1000 [01:16<10:43,  1.42it/s]

[85/1000]
EN: R. Vaishali won the FIDE Women’s Grand Swiss.
MNI_MTEI: ꯑꯥꯔ ꯕꯩꯁꯥꯂꯤꯅꯥ ꯐꯤꯗꯦ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯒꯥꯔꯦꯟꯗꯋꯤꯁ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:   9%|██▍                         | 86/1000 [01:17<10:00,  1.52it/s]

[86/1000]
EN: R. Praggnanandhaa came from behind to win a game.
MNI_MTEI: ꯑꯥꯔ ꯄꯒꯅꯥꯅꯟꯗꯅꯥ ꯇꯨꯡꯗꯒꯤ ꯒꯦꯝ ꯑꯃ ꯃꯥꯏ ꯄꯥꯛꯄꯥ ꯂꯥꯛ
--------------------------------------------------

Translating:   9%|██▍                         | 87/1000 [01:17<10:26,  1.46it/s]

[87/1000]
EN: D. Gukesh as the youngest world chess champion in history.
MNI_MTEI: ꯗꯤ. ꯒꯨꯀꯦꯁ ꯑꯁꯤ ꯍꯤꯁꯇꯔꯤꯗꯥ ꯈ ꯭ ꯋꯥꯏꯗꯒꯤ ꯅꯧꯕ ꯋꯥꯔꯜꯗ ꯆꯦꯁ ꯆꯦꯝꯄꯌꯣꯟ ꯑꯣꯏ
--------------------------------------------------

Translating:   9%|██▍                         | 88/1000 [01:18<10:57,  1.39it/s]

[88/1000]
EN: D. Gukesh secured his first win at Tata Steel Chess Masters 2026.
MNI_MTEI: ꯗꯤ. ꯒꯨꯀꯦꯁꯅ ꯇꯥꯇꯥꯇꯤꯜ ꯆꯦꯁ ꯃꯥꯇꯔꯁ 2026 ꯗꯥ ꯃꯍꯥꯛꯀꯤ ꯑꯍꯥꯟꯕꯥ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯑꯗꯨ ꯐꯪ
--------------------------------------------------

Translating:   9%|██▍                         | 89/1000 [01:19<12:25,  1.22it/s]

[89/1000]
EN: Avinash Sable became the first Indian man to qualify for the men’s 3000m steeplechase final at Paris Olympics 2024.
MNI_MTEI: ꯑꯕꯤꯅꯥꯁ ꯁꯦꯕꯂꯦꯅ ꯄꯦꯔꯤꯁ ꯑꯣꯂꯤꯝꯄꯤꯛꯁ 2024 ꯗꯥ ꯅꯨꯄꯥꯁꯤꯡꯒꯤ ꯃꯤꯇꯔ 3000 ꯁꯇꯤꯄꯂꯆꯦꯁ ꯐꯥꯏꯅꯦꯜꯒꯤꯗꯃꯛꯋꯥꯂꯤꯐꯥꯏ ꯇꯧꯕ ꯑꯍꯥꯟꯕ ꯏꯟꯗꯤꯌꯟ ꯃꯦꯟ ꯑꯣꯏꯈꯤ ꯫
--------------------------------------------------

Translating:   9%|██▌                         | 90/1000 [01:20<12:38,  1.20it/s]

[90/1000]
EN: Mirabai Chanu returned to competition as she prepared for upcoming international events.
MNI_MTEI: ꯃꯤꯔꯥꯕꯥꯏ ꯆꯅꯨꯅꯥ ꯂꯥꯛꯀꯗꯧꯔꯤꯕ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯏꯚꯦꯟꯇꯁꯤꯡꯒꯤꯗꯃꯛ ꯁꯦꯝ ꯁꯥꯗꯨꯅ ꯂꯩꯕꯗꯒꯤ ꯀꯝꯄꯤꯇꯤꯁꯟꯗꯥ ꯍꯜꯂꯛꯈꯤ ꯫
--------------------------------------------------

Translating:   9%|██▌                         | 91/1000 [01:21<13:26,  1.13it/s]

[91/1000]
EN: Manu Bhaker and Harmanpreet Singh among athletes highlighted in a sports-honours post.
MNI_MTEI: ꯃꯅꯨ ꯚꯦꯛꯔ ꯑꯃꯁꯨꯡ ꯍꯔꯃꯟꯄꯤꯇ ꯁꯤꯡꯍ ꯑꯁꯤ ꯑꯦꯇꯦꯂꯤꯇꯁꯤꯡꯒꯤ ꯃꯔꯛꯇꯥꯄꯣꯔ ꯭ ꯠꯁ-ꯍꯣꯔꯣꯔ ꯄꯣꯇ ꯑꯃꯗ ꯃꯁꯛ ꯇꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:   9%|██▌                         | 92/1000 [01:22<14:10,  1.07it/s]

[92/1000]
EN: At the Milan–Cortina Winter Olympics 2026, Ilia Malinin landed a backflip on one skate in an Olympics moment.
MNI_MTEI: ꯃꯤꯂꯥꯟꯒꯤ ꯀꯣꯔꯇꯤꯅꯥ ꯋꯤꯟꯇꯔ ꯑꯣꯂꯤꯝꯄꯤꯛꯁ 2026 ꯗꯥ ꯏꯂꯤꯌꯥ ꯃꯥꯂꯤꯅꯤꯟꯅ ꯑꯣꯂꯤꯝꯄꯤꯛꯁꯀꯤ ꯃꯇꯝꯗꯥ ꯁꯀꯦꯇ ꯑꯃꯗ ꯕꯦꯛꯐꯂꯤꯄ ꯑꯃ ꯂꯦꯟꯗ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:   9%|██▌                         | 93/1000 [01:23<13:46,  1.10it/s]

[93/1000]
EN:  Anastasiia Gubanova delivered a performance featuring Indian cultural elements on the ice in Milan.
MNI_MTEI: ꯑꯅꯥꯁꯇꯥꯁꯤꯌꯥ ꯒꯨꯕꯥꯅꯣꯚꯥꯅꯥ ꯃꯤꯂꯥꯟꯗꯥ ꯂꯩꯕ ꯎꯟꯁꯥꯗꯥ ꯚꯥꯔꯠꯀꯤ ꯅꯥꯠꯀꯤ ꯑꯣꯏꯕ ꯃꯆꯥꯛꯁꯤꯡ ꯎꯠꯄꯥ ꯄꯔꯐꯣꯃꯦꯟꯁ ꯑꯃꯥ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:   9%|██▋                         | 94/1000 [01:24<13:46,  1.10it/s]

[94/1000]
EN: Formula One World Championship could return to Indian soil after a 13-year gap as policy issues are addressed.
MNI_MTEI: ꯐꯣꯔꯃꯨꯂꯥ ꯋꯥꯅ ꯋꯥꯔꯜꯗ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯄ ꯑꯁꯤ ꯆꯍꯤ 13ꯒꯤ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯗ ꯑꯃꯨꯛ ꯍꯜꯂꯛꯄ ꯌꯥꯏ ꯃꯔꯝꯗꯤ ꯄꯣꯂꯤꯁꯤꯒꯤ ꯋꯥꯐꯝꯁꯤꯡ ꯌꯦꯡꯁꯤꯟ
--------------------------------------------------

Translating:  10%|██▋                         | 95/1000 [01:25<13:59,  1.08it/s]

[95/1000]
EN: Nikhat Zareen won 5–0 over Guo Yi Xuan in a bout described as a commanding victory.
MNI_MTEI: ꯅꯤꯈꯥꯇ ꯖꯔꯤꯟꯅꯥ ꯒꯨꯑꯣ ꯌꯤ ꯁꯨꯌꯥꯅꯕꯨ ꯃꯥꯏꯊꯤꯕꯥ ꯃꯥꯏꯄꯥꯛꯄꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯄ ꯕꯥꯎꯇ ꯑꯃꯗ. ꯗ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  10%|██▋                         | 96/1000 [01:26<14:54,  1.01it/s]

[96/1000]
EN: Minakshi Hooda and Jaismine Lamboria upset Paris Olympics medallists and top seeds in a major boxing event.
MNI_MTEI: ꯃꯤꯅꯥꯛꯁꯤ ꯍꯨꯗꯥ ꯑꯃꯁꯨꯡ ꯖꯦꯏꯁꯃꯤꯟꯅ ꯂꯦꯝꯕꯣꯔꯤꯌꯥꯅꯥ ꯄꯦꯔꯤꯁ ꯑꯣꯂꯤꯝꯄꯤꯛꯁꯀꯤ ꯃꯦꯂꯥꯗ ꯃꯥꯏ ꯄꯥꯛꯄꯥꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯇꯣꯞ ꯁꯤꯗꯁꯤꯡꯕꯨ ꯑꯆꯧꯕ ꯕꯣꯛꯁꯤꯡ ꯏꯚꯦꯟꯇ ꯑꯃꯗ ꯃꯥꯏꯊꯤꯕ ꯄꯤ
--------------------------------------------------

Translating:  10%|██▋                         | 97/1000 [01:27<13:32,  1.11it/s]

[97/1000]
EN: Vinesh Phogat announced a return to wrestling on December 12, 2025.
MNI_MTEI: ꯚꯤꯅꯦꯁ ꯐꯣꯒꯥꯠꯅ ꯏꯪ 2025ꯒꯤ ꯗꯤꯁꯦꯝꯕꯔꯗꯥ ꯔꯦꯁꯠꯂꯤꯡꯗꯥ ꯑꯃꯨꯛ ꯍꯟꯅ ꯂꯥꯛꯀꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  10%|██▋                         | 98/1000 [01:27<12:33,  1.20it/s]

[98/1000]
EN: Village spectators watching a kabaddi match organised at a makeshift arena.
MNI_MTEI: ꯈꯨꯡꯒꯪꯒꯤ ꯑꯌꯦꯡꯕꯁꯤꯡꯅ ꯃꯇꯝ ꯈꯔꯒꯤ ꯑꯣꯏꯕ ꯑꯦꯔꯤꯅꯥ ꯑꯃꯗ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯀꯕꯥꯗꯤ ꯃꯦꯆ ꯑꯃ ꯌꯦꯡ
--------------------------------------------------

Translating:  10%|██▊                         | 99/1000 [01:28<11:44,  1.28it/s]

[99/1000]
EN: The 21st Tata Mumbai Marathon took place with large-scale participation in Mumbai.
MNI_MTEI: 21 ꯁꯨꯕꯥ ꯇꯥꯇꯥ ꯃꯨꯝꯕꯥꯏ ꯃꯥꯔꯥꯊꯣꯟ ꯑꯁꯤ ꯑꯆꯧꯕ ꯆꯥꯡꯗꯥ ꯁꯔꯨꯛ ꯌꯥꯗꯨꯅꯥ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  10%|██▋                        | 100/1000 [01:29<11:44,  1.28it/s]

[100/1000]
EN: The first-ever Formula 4 car show on Marina Beach was held on the banks of the sea in Chennai.
MNI_MTEI: ꯃꯦꯔꯤꯅꯥ ꯕꯤꯆꯇꯥ ꯑꯍꯥꯟꯕ ꯐꯣꯔꯃꯨꯂꯥ 4 ꯀꯥꯔ ꯁꯣ ꯑꯁꯤ ꯆꯦꯟꯅꯥꯏꯒꯤ ꯁꯃꯨꯗ ꯇꯣꯔꯕꯥꯟꯗ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  10%|██▋                        | 101/1000 [01:30<12:03,  1.24it/s]

[101/1000]
EN: Tilak Varma said India felt ready for the high-stakes Pakistan match in Colombo.
MNI_MTEI: ꯇꯤꯂꯛ ꯕꯔꯃꯥꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯀꯣꯂꯝꯕꯣꯗꯥ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯑꯋꯥꯡꯕ ꯊꯥꯛꯀꯤ ꯄꯥꯀꯤꯁꯇꯥꯟ ꯃꯦꯆ ꯑꯁꯤꯒꯤꯗꯃꯛ ꯚꯥꯔꯠꯅ ꯁꯦꯝ ꯁꯥꯅꯕ ꯐꯥꯎꯈꯤ ꯫
--------------------------------------------------

Translating:  10%|██▊                        | 102/1000 [01:31<12:20,  1.21it/s]

[102/1000]
EN: Tilak Varma said the India squad had entered a focused “match zone” mindset.
MNI_MTEI: ꯇꯤꯂꯛ ꯕꯔꯃꯥꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯏꯟꯗꯤꯌꯥꯋꯥꯗ ꯑꯁꯤ ꯐꯣꯀꯁ ꯇꯧꯕ ꯃꯦꯆ ꯖꯣꯟꯒꯤ ꯃꯥꯏꯟꯗꯦꯁꯇꯇꯥ ꯆꯪꯁꯤꯜꯂꯦ ꯫
--------------------------------------------------

Translating:  10%|██▊                        | 103/1000 [01:31<12:25,  1.20it/s]

[103/1000]
EN: Tilak Varma described the India–Pakistan fixture as a major highlight of the tournament.
MNI_MTEI: ꯇꯤꯂꯛ ꯕꯔꯃꯥꯅꯥ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯃꯔꯛꯇ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯃꯁꯥꯟꯅ ꯑꯁꯤ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯁꯤꯒꯤ ꯊꯣꯏꯗꯣꯛꯍꯦꯟꯗꯣꯛꯄ ꯑꯃꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  10%|██▊                        | 104/1000 [01:32<12:31,  1.19it/s]

[104/1000]
EN: Tilak Varma emphasized preparation and intensity for India ahead of the Pakistan clash.
MNI_MTEI: ꯇꯤꯂꯛ ꯕꯔꯃꯥꯅꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯗꯥ ꯊꯦꯡꯅꯕ ꯃꯃꯥꯡꯗ ꯚꯥꯔꯠꯀꯤꯗꯃꯛ ꯁꯦꯝ-ꯁꯥꯕꯥ ꯑꯃꯁꯨꯡ ꯍꯛꯆꯤꯟꯅꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  10%|██▊                        | 105/1000 [01:33<11:41,  1.28it/s]

[105/1000]
EN: Tilak Varma framed the Pakistan game as a test of temperament and execution.
MNI_MTEI: ꯇꯤꯂꯛ ꯕꯔꯃꯥꯅꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯃꯁꯥꯟꯅ ꯑꯁꯤ ꯃꯒꯨꯟ ꯑꯃꯁꯨꯡ ꯊꯕꯛ ꯄꯥꯡꯊꯣꯛꯄꯒꯤ ꯆꯥꯡꯌꯦꯡ ꯑꯃ ꯑꯣꯏꯅ ꯁꯦꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  11%|██▊                        | 106/1000 [01:34<11:53,  1.25it/s]

[106/1000]
EN: Delhi Metro extended operating hours to support fans travelling for the India–Namibia match.
MNI_MTEI: ꯏꯟꯗꯤꯌꯥ, ꯅꯥꯃꯤꯕꯤꯌꯥ ꯃꯦꯆꯀꯤꯗꯃꯛ ꯂꯝꯀꯣꯏꯕꯥ ꯐꯦꯟꯁꯤꯡꯕꯨ ꯃꯇꯦꯡ ꯄꯥꯡꯅꯕ ꯗꯤꯜꯂꯤ ꯃꯦꯇꯅꯥ ꯊꯕꯛ ꯄꯥꯡꯊꯣꯛꯄꯒꯤ ꯃꯇꯝ ꯍꯦꯟꯒꯠꯍꯟ
--------------------------------------------------

Translating:  11%|██▉                        | 107/1000 [01:35<11:58,  1.24it/s]

[107/1000]
EN: Delhi Metro added services to manage crowd flow before and after the India–Namibia game.
MNI_MTEI: ꯗꯤꯜꯂꯤ ꯃꯦꯇꯥ ꯏꯟꯗꯤꯌꯥ ꯅꯥꯃꯤꯕꯤꯌꯥ ꯒꯦꯝꯒꯤ ꯃꯃꯥꯡꯗ ꯑꯃꯁꯨꯡ ꯃꯇꯨꯡꯗ ꯃꯤ ꯌꯥꯝꯅ ꯆꯨꯡꯁꯤꯟꯕꯥ ꯁꯤꯟꯗꯣꯛꯅꯕ ꯁꯔꯕꯤꯁꯁꯤꯡ ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  11%|██▉                        | 108/1000 [01:36<12:35,  1.18it/s]

[108/1000]
EN: City transport officials coordinated services to reduce congestion around the India–Namibia fixture.
MNI_MTEI: ꯁꯤꯇꯤ ꯇ ꯭ ꯔꯥꯟꯁꯄꯣꯔꯇ ꯑꯣꯐꯤꯁꯌꯦꯜꯁꯤꯡꯅꯥ ꯏꯟꯗꯤꯌꯥ, ꯅꯥꯃꯤꯕꯤꯌꯥ ꯃꯐꯝ ꯑꯁꯤꯒꯤ ꯑꯀꯣꯏꯕꯗ ꯇꯤꯟꯅꯕꯒꯤ ꯆꯥꯡ ꯍꯟꯊꯍꯟꯅꯕ ꯁꯔꯕꯤꯁꯁꯤꯡ ꯀꯣꯑꯣꯔꯗꯤꯅꯦꯠ ꯇꯧ
--------------------------------------------------

Translating:  11%|██▉                        | 109/1000 [01:37<13:25,  1.11it/s]

[109/1000]
EN: Extended metro services aimed to make stadium travel easier for cricket spectators in Delhi.
MNI_MTEI: ꯗꯤꯜꯂꯤꯗꯥ ꯂꯩꯕ ꯀꯀꯦꯠ ꯌꯦꯡꯂꯤꯕꯁꯤꯡꯒꯤꯗꯃꯛꯇꯗꯃꯤꯌꯥꯃ ꯇꯚꯦꯜ ꯍꯦꯟꯅ ꯂꯥꯏꯕ ꯑꯣꯏꯍꯟꯅꯕ ꯄꯥꯟꯗꯝ ꯊꯝꯂꯤꯕꯥ ꯃꯦꯣ ꯁꯔꯕꯤꯁꯁꯤꯡ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  11%|██▉                        | 110/1000 [01:37<12:55,  1.15it/s]

[110/1000]
EN: Additional trains were planned to handle the match-day rush for the India–Namibia crowd.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯅꯥꯃꯤꯕꯤꯌꯥꯒꯤ ꯃꯤꯐꯝꯒꯤ ꯃꯦꯆ - ꯗꯦꯒꯤ ꯃꯤ ꯌꯥꯝꯅ ꯆꯨꯡꯁꯤꯟꯕꯒꯤꯗꯃꯛꯇ ꯑꯍꯦꯟꯕꯦꯟꯁꯤꯡ ꯊꯧꯔꯥꯡ ꯇꯧ
--------------------------------------------------

Translating:  11%|██▉                        | 111/1000 [01:38<13:02,  1.14it/s]

[111/1000]
EN: Rohit Sharma warned India that confidence alone would not win against Pakistan.
MNI_MTEI: ꯔꯣꯍꯤꯇ ꯁꯔꯃꯥꯅꯥ ꯚꯥꯔꯠꯇꯥ ꯆꯦꯛꯁꯤꯟꯋꯥ ꯄꯤꯔꯝꯃꯤ ꯃꯗꯨꯗꯤ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯀꯟꯐꯦꯁꯇ ꯈꯛꯇꯅꯥ ꯃꯥꯏ ꯄꯥꯛꯄ ꯉꯝꯂꯣꯏ ꯫
--------------------------------------------------

Translating:  11%|███                        | 112/1000 [01:39<13:08,  1.13it/s]

[112/1000]
EN: Rohit Sharma urged India to approach Pakistan with discipline, planning, and composure.
MNI_MTEI: ꯔꯣꯍꯤꯇ ꯁꯔꯃꯥꯅꯥ ꯚꯥꯔꯠꯇꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯗꯥ ꯗꯤꯁꯤꯄꯂꯤꯟ, ꯄꯅꯤꯡ, ꯑꯃꯁꯨꯡ ꯀꯝꯄꯣꯖꯔꯒ ꯂꯣꯏꯅꯅꯥ ꯆꯪꯁꯤꯟꯕꯥ ꯍꯥꯏ
--------------------------------------------------

Translating:  11%|███                        | 113/1000 [01:40<13:31,  1.09it/s]

[113/1000]
EN: Rohit Sharma cautioned that India–Pakistan games can ignore rankings and recent form.
MNI_MTEI: ꯔꯣꯍꯤꯇ ꯁꯔꯃꯥꯅꯥ ꯚꯥꯔꯠꯇꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯗꯥ ꯁꯥꯟꯅꯔꯤꯕ ꯃꯁꯥꯟꯅꯁꯤꯡ ꯑꯁꯤꯅ ꯔꯦꯡꯀꯤꯡ ꯑꯃꯁꯨꯡ ꯑꯅꯧꯕ ꯃꯑꯣꯡ ꯑꯗꯨ ꯃꯥꯡꯍꯟꯕꯥ ꯌꯥꯏ ꯍꯥꯏꯅ ꯆꯦꯛꯁꯤꯟꯋꯥ ꯄꯤ
--------------------------------------------------

Translating:  11%|███                        | 114/1000 [01:41<12:56,  1.14it/s]

[114/1000]
EN: Rohit Sharma stressed mental readiness for India before the Pakistan contest.
MNI_MTEI: ꯔꯣꯍꯤꯇ ꯁꯔꯃꯥꯅꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯗꯒꯤ ꯍꯦꯟꯗꯥꯟꯅꯕꯒꯤ ꯃꯃꯥꯡꯗ ꯚꯥꯔꯠꯀꯤꯗꯃꯛ ꯋꯥꯈꯜꯒꯤ ꯑꯣꯏꯕ ꯁꯦꯝ-ꯁꯥꯕꯒꯤ ꯋꯥꯐꯝ ꯊꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███                        | 115/1000 [01:42<12:32,  1.18it/s]

[115/1000]
EN: Rohit Sharma advised India to avoid underestimating Pakistan in the World Cup clash.
MNI_MTEI: ꯔꯣꯍꯤꯇ ꯁꯔꯃꯥꯅꯥ ꯚꯥꯔꯠꯇꯥ ꯋꯥꯔꯜꯗ ꯀꯄ ꯀꯂꯦꯁꯇꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯕꯨ ꯇꯥꯟꯅꯕꯒꯤ ꯄꯥꯎꯇꯥꯛ ꯄꯤ
--------------------------------------------------

Translating:  12%|███▏                       | 116/1000 [01:43<12:35,  1.17it/s]

[116/1000]
EN: Virat Kohli congratulated India’s Under-19 team after the World Cup final victory.
MNI_MTEI: ꯋꯜꯗ ꯀꯞꯀꯤ ꯐꯥꯏꯅꯦꯜ ꯃꯥꯏ ꯄꯥꯛꯂꯕ ꯃꯇꯨꯡꯗ ꯕꯤꯔꯥꯇ ꯀꯣꯍꯂꯤꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯑꯟꯗꯔ-19 ꯇꯤꯝꯕꯨ ꯊꯥꯒꯠꯄ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███▏                       | 117/1000 [01:44<13:28,  1.09it/s]

[117/1000]
EN: India’s Under-19 team won the ICC Under-19 Cricket World Cup final by 100 runs against England.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯑꯟꯗꯔ-19 ꯇꯤꯝꯅꯥ ꯑꯥꯏ ꯁꯤ ꯁꯤ ꯑꯟꯗ- ꯀꯀꯦꯠ ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞꯀꯤ ꯐꯥꯏꯅꯦꯜꯗꯥ ꯏꯪꯂꯦꯟꯗꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯔꯟ 100ꯅ ꯃꯥꯏꯄꯥꯛ
--------------------------------------------------

Translating:  12%|███▏                       | 118/1000 [01:45<13:24,  1.10it/s]

[118/1000]
EN: India secured a sixth Under-19 World Cup title with a commanding final performance.
MNI_MTEI: ꯀꯃꯥꯟꯗꯤꯡ ꯐꯥꯏꯅꯦꯜ ꯄꯔꯐꯣꯃꯔꯃꯦꯟꯁ ꯑꯃꯒ ꯂꯣꯏꯅꯅꯥ ꯚꯥꯔꯠꯅ 6 ꯁꯨꯕ ꯑꯟꯗꯔ-19 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞꯀꯤ ꯇꯥꯏꯇꯜ ꯑꯃ ꯐꯪ
--------------------------------------------------

Translating:  12%|███▏                       | 119/1000 [01:45<13:10,  1.11it/s]

[119/1000]
EN: Celebrations followed India’s Under-19 World Cup triumph over England in the title match.
MNI_MTEI: ꯇꯥꯏꯇꯜ ꯃꯦꯆ ꯑꯗꯨꯗ ꯚꯥꯔꯠꯅ ꯏꯡꯂꯦꯟꯗꯄꯨ ꯃꯥꯏꯊꯤꯅꯥ ꯑꯟꯗꯔ-19 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞꯇ ꯃꯥꯏ ꯄꯥꯛꯄꯥ ꯑꯗꯨ ꯄꯥꯡꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███▏                       | 120/1000 [01:46<12:34,  1.17it/s]

[120/1000]
EN: India’s Under-19 success drew praise from senior players across Indian cricket.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯑꯟꯗꯔ-19ꯒꯤ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯑꯁꯤ ꯚꯥꯔꯠꯀꯤ ꯀꯀꯦꯠ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯂꯩꯕ ꯁꯦꯅꯤꯌꯔ ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡꯗꯒꯤ ꯊꯥꯒꯠꯄ ꯐꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███▎                       | 121/1000 [01:47<12:15,  1.20it/s]

[121/1000]
EN: Dhakshineswar Suresh sparked optimism by delivering a breakthrough stretch for Indian tennis.
MNI_MTEI: ꯙꯛꯁꯤꯅꯦꯁ ꯁꯨꯔꯦꯁꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯇꯦꯅꯤꯁꯀꯤꯗꯃꯛ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯈꯣꯡꯊꯥꯡ ꯑꯃ ꯄꯤꯔꯗꯨꯅ ꯑꯥꯀꯥꯁꯕꯥ ꯎꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███▎                       | 122/1000 [01:48<12:20,  1.19it/s]

[122/1000]
EN: Dhakshineswar Suresh’s rise has renewed ambition among Indian tennis fans and young players.
MNI_MTEI: ꯙꯛꯁꯤꯅꯦꯁ ꯁꯨꯔꯦꯁꯀꯤ ꯆꯥꯎꯈꯠꯂꯛꯄ ꯑꯁꯤꯅ ꯚꯥꯔꯠꯀꯤ ꯇꯦꯅꯤꯁ ꯄꯥꯝꯖꯕꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯅꯍꯥ ꯑꯣꯏꯔꯤꯕ ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯑꯅꯤꯡꯕꯥ ꯑꯃꯨꯛ ꯍꯟꯅ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███▎                       | 123/1000 [01:49<12:18,  1.19it/s]

[123/1000]
EN: Dhakshineswar Suresh’s recent results were described as a turning point for Indian tennis.
MNI_MTEI: ꯙꯛꯁꯤꯅꯦꯁ ꯁꯨꯔꯦꯁꯀꯤ ꯍꯟꯗꯛꯀꯤ ꯐꯜꯁꯤꯡ ꯑꯁꯤ ꯏꯟꯗꯤꯌꯟ ꯇꯦꯅꯤꯁꯀꯤ ꯃꯔꯨꯑꯣꯏꯕ ꯈꯣꯡꯊꯥꯡ ꯑꯃꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███▎                       | 124/1000 [01:49<12:10,  1.20it/s]

[124/1000]
EN: Dhakshineswar Suresh’s performances lifted expectations for Indian tennis on bigger stages.
MNI_MTEI: ꯙꯛꯁꯤꯅꯦꯁ ꯁꯨꯔꯦꯁꯀꯤ ꯄꯔꯐꯣꯃꯦꯟꯁꯁꯤꯡ ꯑꯁꯤꯅ ꯚꯥꯔꯠꯀꯤ ꯇꯦꯅꯤꯁꯇꯒꯤ ꯑꯆꯧꯕ ꯇꯥꯡꯀꯛꯁꯤꯡꯗ ꯊꯥꯖꯕ ꯍꯦꯟꯒꯠꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  12%|███▍                       | 125/1000 [01:50<12:00,  1.21it/s]

[125/1000]
EN: Dhakshineswar Suresh’s run created fresh belief about India’s potential in men’s tennis.
MNI_MTEI: ꯙꯛꯁꯤꯅꯦꯁ ꯁꯨꯔꯦꯁꯀꯤ ꯂꯝꯖꯦꯜ ꯑꯁꯤꯅ ꯅꯨꯄꯥꯒꯤ ꯇꯦꯅꯤꯁꯇ ꯚꯥꯔꯠꯀꯤ ꯑꯣꯏꯊꯣꯛꯄ ꯌꯥꯕꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯑꯅꯧꯕ ꯊꯥꯖꯕ ꯁꯦꯝꯒꯠ
--------------------------------------------------

Translating:  13%|███▍                       | 126/1000 [01:51<12:05,  1.21it/s]

[126/1000]
EN: India’s men’s team exited in the quarterfinals at the Badminton Asia Team Championships.
MNI_MTEI: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯑꯦꯁꯤꯌꯥ ꯇꯤꯝ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯄꯇ ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯥꯒꯤ ꯇꯤꯝ ꯑꯁꯤ ꯀ ꯭ ꯋꯥꯇꯔꯐꯥꯏꯂꯔꯇꯥ ꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  13%|███▍                       | 127/1000 [01:52<12:07,  1.20it/s]

[127/1000]
EN: India’s women’s team exited in the quarterfinals at the Badminton Asia Team Championships.
MNI_MTEI: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯑꯦꯁꯤꯌꯥ ꯇꯤꯝ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯄꯇ ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯇꯤꯝ ꯑꯁꯤ ꯀ ꯭ ꯋꯥꯇꯔꯐꯥꯏꯂꯔꯇꯥ ꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  13%|███▍                       | 128/1000 [01:53<12:32,  1.16it/s]

[128/1000]
EN: India failed to defend titles after a double quarterfinal exit in the team championships.
MNI_MTEI: ꯇꯤꯝ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯄ ꯑꯁꯤꯗ ꯗꯕꯜꯋꯥꯇꯔ ꯐꯥꯏꯅꯦꯜꯗꯒꯤ ꯅꯥꯟꯊꯣꯛꯂꯕ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯅ ꯇꯥꯏꯇꯥꯜꯁꯤꯡ ꯉꯥꯛꯊꯣꯛꯄꯗꯥ ꯃꯥꯏ ꯄꯥꯛꯈꯤꯗꯦ ꯫
--------------------------------------------------

Translating:  13%|███▍                       | 129/1000 [01:54<12:49,  1.13it/s]

[129/1000]
EN: Strong opposition ended India’s campaign early at the Badminton Asia Team Championships.
MNI_MTEI: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯑꯦꯁꯤꯌꯥ ꯇꯤꯝ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯞ ꯑꯁꯤꯗ ꯃꯥꯏ ꯄꯥꯛꯅꯥ ꯑꯣꯄꯖꯤꯁꯟ ꯇꯧꯔꯕꯥ ꯚꯥꯔꯠꯀꯤ ꯀꯦꯝꯄꯤꯌꯟ ꯑꯗꯨ ꯉꯟꯅ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  13%|███▌                       | 130/1000 [01:55<12:32,  1.16it/s]

[130/1000]
EN: The quarterfinal losses ended India’s hopes of a title defence at the event.
MNI_MTEI: ꯋꯥꯔꯇꯔ ꯐꯥꯏꯅꯦꯜꯗꯥ ꯃꯥꯏꯊꯤꯕꯥ ꯑꯁꯤꯅ ꯊꯧꯔꯝ ꯑꯁꯤꯗ ꯇꯥꯏꯇꯥꯜ ꯗꯤꯐꯦꯟꯁ ꯑꯃ ꯑꯣꯏꯅꯕ ꯚꯥꯔꯠꯀꯤ ꯊꯥꯖꯕ ꯑꯗꯨ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  13%|███▌                       | 131/1000 [01:55<12:25,  1.17it/s]

[131/1000]
EN: Sumit Nagal was scheduled to open his tournament campaign against Guy Den Ouden.
MNI_MTEI: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯅꯥ ꯒꯥꯏ ꯗꯦꯅ ꯑꯣꯎꯗꯦꯟꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯃꯍꯥꯛꯀꯤ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯀꯦꯝꯄꯦꯟ ꯍꯥꯡꯗꯣꯛꯅꯕꯒꯤ ꯊꯧꯔꯥꯡ ꯇꯧꯔꯝꯃꯤ ꯫
--------------------------------------------------

Translating:  13%|███▌                       | 132/1000 [01:56<12:49,  1.13it/s]

[132/1000]
EN: Sumit Nagal drew Dutch player Guy Den Ouden in an opening-round matchup.
MNI_MTEI: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯅꯥ ꯑꯣꯄꯦꯅꯤꯡ-ꯔꯥꯎꯟꯗ ꯃꯦꯆꯑꯄ ꯑꯃꯗ ꯗꯠꯆꯀꯤ ꯁꯥꯟꯅꯔꯣꯏ ꯒꯥꯏ ꯗꯦꯅ ꯑꯣꯎꯗꯦꯟꯕꯨ ꯗ ꯇꯧ
--------------------------------------------------

Translating:  13%|███▌                       | 133/1000 [01:57<13:12,  1.09it/s]

[133/1000]
EN: Sumit Nagal’s first-round pairing set up an early test against Guy Den Ouden.
MNI_MTEI: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯒꯤ ꯐꯔꯁꯠ-ꯔꯥꯎꯟꯗ ꯄꯦꯌꯔꯤꯡꯅꯥ ꯒꯥꯏ ꯗꯦꯅ ꯑꯣꯎꯗꯦꯟꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯉꯟꯅꯕꯥ ꯇꯦꯁꯇ ꯑꯃ ꯁꯦꯝ
--------------------------------------------------

Translating:  13%|███▌                       | 134/1000 [01:58<13:15,  1.09it/s]

[134/1000]
EN: Sumit Nagal prepared for a fresh challenge against Guy Den Ouden in round one.
MNI_MTEI: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯅꯥ ꯒꯥꯏ ꯗꯦꯅ ꯑꯣꯎꯗꯦꯟꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯔꯥꯎꯟꯗ ꯋꯥꯟꯗꯥ ꯑꯅꯧꯕ ꯆꯂꯦꯟꯖ ꯑꯃꯒꯤꯗꯃꯛ ꯁꯦꯝ ꯁꯥ
--------------------------------------------------

Translating:  14%|███▋                       | 135/1000 [01:59<13:07,  1.10it/s]

[135/1000]
EN: Sumit Nagal began a new event with an opening match against Guy Den Ouden.
MNI_MTEI: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯅꯥ ꯒꯥꯏ ꯗꯦꯅ ꯑꯣꯎꯗꯦꯟꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯑꯍꯥꯟꯕꯥ ꯃꯦꯆ ꯑꯃꯒ ꯂꯣꯏꯅꯅꯥ ꯑꯅꯧꯕ ꯏꯚꯦꯟꯇ ꯑꯃ ꯍꯧ
--------------------------------------------------

Translating:  14%|███▋                       | 136/1000 [02:00<13:17,  1.08it/s]

[136/1000]
EN: An analysis said T20 cricket keeps evolving through new strategies and fast-changing trends.
MNI_MTEI: ꯑꯦꯅꯥꯂꯥꯏꯁꯤꯁ ꯑꯃꯥꯅꯥ ꯍꯥꯏ ꯃꯗꯨꯗꯤ ꯇꯤ20 ꯀꯀꯦꯠ ꯑꯁꯤ ꯑꯅꯧꯕꯇꯖꯤꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯊꯨꯅ ꯍꯣꯡꯂꯛꯂꯤꯕꯦꯟꯗꯁꯤꯡꯒꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯆꯥꯎꯈꯠꯂꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  14%|███▋                       | 137/1000 [02:01<12:55,  1.11it/s]

[137/1000]
EN: A feature noted the ICC Men's T20 World Cup returned to India after a decade-long gap.
MNI_MTEI: ꯑꯥꯏ ꯁꯤ ꯁꯤ ꯃꯦꯟ ꯭ ꯁ ꯇꯤ20 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯄ ꯑꯁꯤ ꯆꯍꯤ ꯇꯔꯥꯒꯤ ꯈꯨꯖꯤꯡ ꯀꯌꯥꯒꯤ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯇ ꯍꯜꯂꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  14%|███▋                       | 138/1000 [02:02<12:39,  1.14it/s]

[138/1000]
EN: T20 cricket was described as a format that continually reinvents tactics and team plans.
MNI_MTEI: ꯇꯤ20 ꯀꯀꯦꯠ ꯑꯁꯤ ꯃꯈꯥ ꯇꯥꯅ ꯇꯦꯛꯇꯤꯛꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯇꯤꯝꯒꯤ ꯊꯧꯔꯥꯡꯁꯤꯡ ꯑꯃꯨꯛ ꯍꯟꯅ ꯁꯦꯝꯒꯠꯄꯥ ꯐꯣꯔꯃꯦꯇ ꯑꯃꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  14%|███▊                       | 139/1000 [02:03<12:52,  1.11it/s]

[139/1000]
EN: A commentary highlighted how technology and data shape modern T20 decision-making.
MNI_MTEI: ꯀꯃꯦꯟꯇꯔꯤ ꯑꯃꯅ ꯀꯔꯝꯅꯥ ꯇꯦꯛꯅꯣꯂꯣꯖꯤ ꯑꯃꯁꯨꯡ ꯗꯦꯇꯥꯅꯥ ꯃꯣꯗꯔꯟ ꯇꯤ20 ꯗꯤꯁꯤꯁꯟ - ꯃꯦꯀꯤꯡ ꯁꯦꯝꯒꯦ ꯍꯥꯏꯕꯗꯨ ꯍꯥꯏꯂꯥꯏꯇ ꯇꯧ
--------------------------------------------------

Translating:  14%|███▊                       | 140/1000 [02:04<12:42,  1.13it/s]

[140/1000]
EN: A tournament preview underlined T20 cricket’s cultural impact and mass appeal in India.
MNI_MTEI: ꯇꯣꯔꯅꯥꯃꯦꯟꯇꯚ ꯭ ꯌꯨ ꯑꯃꯅ ꯚꯥꯔꯠꯇ ꯇꯤ20 ꯀꯀꯦꯠꯀꯤ ꯅꯥꯠꯀꯤ ꯑꯣꯏꯕ ꯏꯊꯤꯜ ꯑꯃꯁꯨꯡ ꯃꯤꯌꯥꯝꯒꯤ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯟꯅꯤꯡꯉꯥꯏ ꯑꯣꯏꯕꯒꯤ ꯃꯁꯛ ꯇꯥꯛ
--------------------------------------------------

Translating:  14%|███▊                       | 141/1000 [02:05<12:48,  1.12it/s]

[141/1000]
EN: Kapil Dev was listed among participants at the PM Rungta Memorial Golf Cup in Jaipur.
MNI_MTEI: ꯀꯄꯤꯜ ꯗꯦꯕ ꯑꯁꯤ ꯖꯦꯄꯨꯔꯗꯥ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯄꯤꯑꯦꯝ ꯔꯨꯡꯒꯇꯥ ꯃꯦꯃꯣꯔꯤꯌꯦꯜ ꯒꯣꯜꯐ ꯀꯞꯇ ꯁꯔꯨꯛ ꯌꯥꯔꯤꯕꯁꯤꯡꯒꯤ ꯃꯅꯨꯡꯗ
--------------------------------------------------

Translating:  14%|███▊                       | 142/1000 [02:05<12:39,  1.13it/s]

[142/1000]
EN: Madan Lal was listed among participants at the PM Rungta Memorial Golf Cup in Jaipur.
MNI_MTEI: ꯃꯗꯟ ꯂꯥꯜ ꯑꯁꯤ ꯖꯦꯄꯨꯔꯗꯥ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯄꯤꯑꯦꯝ ꯔꯨꯡꯒꯇꯥ ꯃꯦꯃꯣꯔꯤꯌꯦꯜ ꯒꯣꯜꯐ ꯀꯞꯇ ꯁꯔꯨꯛ ꯌꯥꯔꯤꯕꯁꯤꯡꯒꯤ ꯃꯅꯨꯡꯗ
--------------------------------------------------

Translating:  14%|███▊                       | 143/1000 [02:06<12:15,  1.17it/s]

[143/1000]
EN: The PM Rungta Memorial Golf Cup was scheduled for February 8, 2026 in Jaipur.
MNI_MTEI: ꯄꯤ ꯑꯦꯝ ꯔꯨꯡꯇꯥ ꯃꯦꯃꯣꯔꯤꯌꯦꯜ ꯒꯣꯜꯐ ꯀꯞ ꯑꯁꯤ ꯖꯦꯄꯨꯔꯗꯥ ꯐꯕꯋꯥꯔꯤ 8,2026 ꯗꯥ ꯄꯥꯡꯊꯣꯛꯀꯗꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  14%|███▉                       | 144/1000 [02:07<11:30,  1.24it/s]

[144/1000]
EN: Rambagh Golf Club was named as the venue for the memorial golf tournament.
MNI_MTEI: ꯔꯥꯝꯕꯥꯒ ꯒꯣꯜꯐ ꯀꯂꯕ ꯑꯁꯤ ꯃꯦꯃꯣꯔꯤꯌꯦꯜ ꯒꯣꯜꯐꯥꯅꯃꯦꯟꯇ ꯑꯁꯤꯒꯤ ꯃꯐꯝ ꯍꯥꯏꯅ ꯃꯤꯡꯊꯣꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  14%|███▉                       | 145/1000 [02:08<12:47,  1.11it/s]

[145/1000]
EN: Organisers said the golf cup used a Stableford Single Peoria format for inclusive competition.
MNI_MTEI: ꯒꯣꯜꯐ ꯀꯄ ꯑꯁꯤꯗ ꯁꯇꯦꯕꯜꯐꯣꯔꯗ ꯁꯤꯡꯒꯜ ꯄꯤꯑꯣꯔꯤꯌꯥ ꯐꯣꯔꯃꯦꯇ ꯑꯁꯤ ꯏꯟꯀꯨꯚꯦꯜ ꯀꯝꯄꯤꯇꯤꯁꯟꯒꯤꯗꯃꯛ ꯁꯤꯖꯤꯟꯅꯈꯤ ꯍꯥꯏꯅ ꯑꯣꯔꯖꯦꯟꯥꯏꯖꯔꯁꯤꯡꯅ ꯍꯥꯏ
--------------------------------------------------

Translating:  15%|███▉                       | 146/1000 [02:09<13:01,  1.09it/s]

[146/1000]
EN: A schedule note said United States would face Netherlands in Chennai to close February 13’s action.
MNI_MTEI: ꯁꯦꯗꯜ ꯅꯣꯇ ꯑꯃꯗ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯌꯨꯅꯥꯏꯇꯦꯗꯁꯅ ꯆꯦꯟꯅꯥꯏꯗꯥ ꯅꯦꯗꯔꯂꯦꯟꯗꯁꯀ ꯃꯥꯌꯣꯛꯅꯔꯒ ꯐꯦꯕꯋꯥꯔꯤ 13ꯒꯤ ꯑꯦꯛꯁꯟ ꯂꯣꯏꯁꯤꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  15%|███▉                       | 147/1000 [02:10<12:28,  1.14it/s]

[147/1000]
EN: The USA–Netherlands match was presented as important for points and pride in the group.
MNI_MTEI: ꯌꯨ ꯑꯦꯁ ꯑꯦ ꯑꯃꯁꯨꯡ ꯅꯦꯗꯔꯂꯦꯟꯗꯁꯀꯤ ꯃꯦꯆ ꯑꯁꯤ ꯄꯣꯏꯟꯇꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯒꯄ ꯑꯁꯤꯗ ꯏꯀꯥꯏꯈꯨꯝꯅꯕꯒꯤ ꯃꯔꯨꯑꯣꯏꯕ ꯑꯃ ꯑꯣꯏꯅ ꯎꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  15%|███▉                       | 148/1000 [02:11<12:57,  1.10it/s]

[148/1000]
EN: A match preview framed USA against Netherlands as a tight contest between associate nations.
MNI_MTEI: ꯃꯦꯆꯚꯋꯥꯅꯥ ꯌꯨꯑꯦꯁꯑꯦꯕꯨ ꯅꯦꯗꯔꯂꯦꯟꯁꯀꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯑꯦꯁꯣꯁꯤꯑꯦꯠ ꯅꯦꯁꯟꯒꯤ ꯃꯔꯛꯀꯤ ꯑꯔꯨꯕꯥ ꯍꯦꯟꯗꯥꯟꯅꯕ ꯑꯃꯥ ꯑꯣꯏꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  15%|████                       | 149/1000 [02:12<13:09,  1.08it/s]

[149/1000]
EN: A schedule roundup highlighted February 13 fixtures as key for shaping group standings.
MNI_MTEI: ꯁꯦꯗꯜ ꯔꯥꯎꯟꯗꯑꯞ ꯑꯃꯥꯅꯥ ꯐꯦꯕꯋꯥꯔꯤ 13ꯒꯤ ꯐꯤꯛꯆꯔꯁꯤꯡ ꯑꯁꯤ ꯒꯄꯟꯗꯤꯡꯁꯤꯡ ꯁꯦꯝꯕꯒꯤ ꯃꯔꯨ ꯑꯣꯏ ꯍꯥꯏꯅ ꯃꯁꯛ ꯇꯥꯛ
--------------------------------------------------

Translating:  15%|████                       | 150/1000 [02:13<12:52,  1.10it/s]

[150/1000]
EN: A preview said the final February 13 match would be played at MA Chidambaram Stadium.
MNI_MTEI: ꯐꯕꯋꯥꯔꯤ ꯇꯥꯡ 13ꯒꯤ ꯐꯥꯏꯅꯦꯜ ꯃꯦꯆ ꯑꯗꯨ ꯑꯦꯝ ꯑꯦ ꯆꯤꯗꯝꯕꯔꯝꯗꯤꯌꯝꯗꯥ ꯁꯥꯟꯅꯒꯅꯤ ꯍꯥꯏꯅꯚ ꯭ ꯌꯨ ꯑꯃꯥꯅꯥ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  15%|████                       | 151/1000 [02:13<12:00,  1.18it/s]

[151/1000]
EN: Indian Super League clubs requested a pause on relegation for three to five years.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟ ꯁꯨꯄꯔ ꯂꯤꯒ ꯀꯂꯒꯁꯤꯡꯅ ꯆꯍꯤ ꯑꯍꯨꯝꯗꯒꯤ ꯃꯉꯥ ꯐꯥꯎꯕꯒꯤ ꯑꯣꯏꯅ ꯔꯦꯂꯤꯒꯦꯁꯟ ꯂꯦꯞꯅꯕ ꯍꯥꯏꯖ
--------------------------------------------------

Translating:  15%|████                       | 152/1000 [02:14<12:02,  1.17it/s]

[152/1000]
EN: ISL clubs argued that pausing relegation would provide stability for long-term planning.
MNI_MTEI: ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯀꯂꯒꯁꯤꯡꯅ ꯋꯥꯐꯝ ꯊꯝꯈꯤ ꯃꯗꯨꯗꯤ ꯔꯦꯂꯤꯒꯦꯁꯟ ꯂꯦꯞꯄꯅꯥ ꯂꯣꯡ-ꯇꯔꯃꯅꯤꯡꯒꯤꯗꯃꯛ ꯁꯇꯦꯕꯤꯂꯤꯇꯤ ꯄꯤꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  15%|████▏                      | 153/1000 [02:15<11:53,  1.19it/s]

[153/1000]
EN: Several ISL teams asked administrators to consider a temporary relegation freeze.
MNI_MTEI: ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯇꯤꯝ ꯀꯌꯥꯅ ꯑꯦꯗꯃꯤꯅꯤꯁꯇꯥꯔꯁꯤꯡꯗ ꯃꯇꯝ ꯈꯔꯒꯤ ꯑꯣꯏꯅ ꯔꯦꯂꯤꯒꯦꯁꯟ ꯐꯖ ꯑꯃ ꯈꯟꯅꯅꯕ ꯍꯥꯏ
--------------------------------------------------

Translating:  15%|████▏                      | 154/1000 [02:16<11:46,  1.20it/s]

[154/1000]
EN: The request on relegation was framed as a measure to protect club investments.
MNI_MTEI: ꯔꯤꯂꯤꯒꯦꯁꯟ ꯇꯧꯅꯕ ꯍꯥꯏꯖꯕ ꯑꯁꯤ ꯀꯂꯕ ꯏꯟꯚꯦꯁꯇꯃꯦꯟꯇꯁꯤꯡ ꯉꯥꯛꯁꯦꯟꯕꯒꯤ ꯈꯣꯡꯊꯥꯡ ꯑꯃ ꯑꯣꯏꯅ ꯁꯦꯝꯈꯤꯕꯅꯤ ꯫
--------------------------------------------------

Translating:  16%|████▏                      | 155/1000 [02:17<12:39,  1.11it/s]

[155/1000]
EN: ISL stakeholders debated relegation rules while seeking clarity for the 2025–26 season.
MNI_MTEI: ꯏꯪꯁꯣꯛ 2025/26 ꯒꯤ ꯁꯤꯖꯟꯒꯤꯗꯃꯛ ꯃꯌꯦꯛ ꯁꯦꯡꯕꯥ ꯊꯤꯔꯤꯉꯩꯗ ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯁ ꯭ ꯇꯦꯀꯜꯁꯤꯡꯅ ꯔꯦꯂꯤꯒꯦꯁꯟ ꯔꯣꯂꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯋꯥꯊꯣꯛ ꯆꯠꯊꯈꯤ ꯫
--------------------------------------------------

Translating:  16%|████▏                      | 156/1000 [02:18<12:11,  1.15it/s]

[156/1000]
EN: India produced a 3–2 win over Netherlands in Davis Cup Qualifiers Round 1.
MNI_MTEI: ꯗꯦꯚꯤꯁ ꯀꯄꯋꯥꯂꯤꯐꯌꯔ ꯔꯥꯎꯟꯗ 1 ꯗꯥ ꯅꯦꯗꯔꯂꯦꯟꯁꯇ ꯚꯥꯔꯠꯅ 2. ꯗ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  16%|████▏                      | 157/1000 [02:19<12:32,  1.12it/s]

[157/1000]
EN: India advanced to the second Davis Cup qualifying round after beating Netherlands 3–2.
MNI_MTEI: ꯅꯦꯗꯔꯂꯦꯟ ꯭ ꯁꯄꯨ 3. ꯗ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯔꯕꯥ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯅ ꯑꯅꯤꯁꯨꯕ ꯗꯦꯚꯤꯁ ꯀꯞꯀꯤ ꯀꯋꯥꯂꯤꯐꯥꯏꯡ ꯔꯥꯎꯟꯗꯗꯥ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯈꯤ ꯫
--------------------------------------------------

Translating:  16%|████▎                      | 158/1000 [02:19<11:51,  1.18it/s]

[158/1000]
EN: India’s Davis Cup team was described as thriving against higher-ranked opponents recently.
MNI_MTEI: ꯍꯟꯗꯛꯇ ꯚꯥꯔꯠꯀꯤ ꯗꯦꯚꯤꯁ ꯀꯄ ꯇꯤꯝ ꯑꯁꯤ ꯑꯋꯥꯡꯕ ꯊꯥꯛꯇ ꯂꯩꯕ ꯌꯦꯛꯅꯕꯁꯤꯡꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯆꯥꯎꯈꯠꯂꯛꯂꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  16%|████▎                      | 159/1000 [02:20<11:20,  1.24it/s]

[159/1000]
EN: The Davis Cup tie at SM Krishna Tennis Stadium went down to the wire.
MNI_MTEI: ꯑꯦꯁ. ꯑꯦꯝ. ꯀꯅꯥ ꯇꯦꯅꯤꯁꯗꯤꯌꯝꯗꯥ ꯄꯥꯡꯊꯣꯛꯂꯤꯕꯥ ꯗꯦꯚꯤꯁ ꯀꯄ ꯇꯥꯏ ꯑꯗꯨ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  16%|████▎                      | 160/1000 [02:21<11:22,  1.23it/s]

[160/1000]
EN: India’s Davis Cup success followed an earlier victory over Switzerland in Biel last year.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯗꯦꯚꯤꯁ ꯀꯞꯀꯤ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯑꯁꯤ ꯍꯧꯈꯤꯕ ꯆꯍꯤ ꯕꯤꯌꯦꯜꯗꯥꯏꯠꯖꯔꯂꯦꯟꯗꯄꯨ ꯃꯥꯏꯊꯤꯕꯥ ꯐꯪꯂꯕ ꯃꯇꯨꯡꯗꯅꯤ ꯫
--------------------------------------------------

Translating:  16%|████▎                      | 161/1000 [02:22<10:54,  1.28it/s]

[161/1000]
EN: The India Open was kept as a Super 750 tournament for the 2027–2030 cycle.
MNI_MTEI: ꯏꯟꯗꯤꯌꯥ ꯑꯣꯄꯟ ꯑꯁꯤ ꯏꯪ 20272030 ꯒꯤ ꯁꯥꯏꯀꯜꯒꯤꯗꯃꯛ ꯁꯨꯄꯔ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯃ ꯑꯣꯏꯅ ꯊꯝ
--------------------------------------------------

Translating:  16%|████▎                      | 162/1000 [02:22<11:02,  1.26it/s]

[162/1000]
EN: Players criticised conditions, yet organisers retained the India Open’s Super 750 status.
MNI_MTEI: ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡꯅ ꯀꯟꯗꯤꯁꯟꯁꯤꯡ ꯌꯦꯠꯂꯝꯃꯤ ꯑꯗꯨꯕꯨ ꯑꯣꯔꯒꯥꯅꯔꯁꯤꯡꯅ ꯏꯟꯗꯤꯌꯥ ꯑꯣꯄꯟꯒꯤ ꯁꯨꯄꯔ ꯁꯇꯥꯇꯁ ꯑꯗꯨ ꯂꯦꯞ
--------------------------------------------------

Translating:  16%|████▍                      | 163/1000 [02:23<11:31,  1.21it/s]

[163/1000]
EN: Badminton World Federation announced a revamped World Tour structure with six tournament levels.
MNI_MTEI: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯋꯥꯔꯜꯗ ꯐꯦꯗꯔꯦꯁꯟꯅ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯂꯦꯚꯦꯜ ꯇꯔꯨꯛꯀꯤ ꯃꯋꯣꯡ ꯁꯦꯝꯖꯤꯟꯕꯥ ꯋꯥꯔꯂꯗ ꯇꯨꯔ ꯁꯆꯔ ꯑꯃ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  16%|████▍                      | 164/1000 [02:24<11:22,  1.23it/s]

[164/1000]
EN: The BWF updated World Tour plan included 36 tournaments across multiple tiers.
MNI_MTEI: ꯕꯤ.ꯑꯐꯀꯤ ꯑꯞꯗꯦꯇ ꯇꯧꯔꯕꯥ ꯋꯥꯔꯜꯗ ꯇꯨꯔ ꯄꯂꯥꯟ ꯑꯁꯤꯗ ꯃꯈꯜ ꯀꯌꯥꯒꯤ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ 36 ꯌꯥꯎ
--------------------------------------------------

Translating:  16%|████▍                      | 165/1000 [02:25<11:56,  1.17it/s]

[165/1000]
EN: The BWF said annual World Tour prize money would rise to about 26.9 million dollars.
MNI_MTEI: ꯆꯍꯤꯗꯥ ꯋꯥꯔꯜꯗ ꯇꯨꯔꯥꯏꯖ ꯃꯅꯤ ꯑꯁꯤ ꯆꯥꯎꯔꯥꯛꯅ ꯗꯣꯂꯔ ꯃꯤꯂꯌꯟ. ꯐꯥꯎꯕ ꯍꯦꯟꯒꯠꯂꯛꯀꯅꯤ ꯍꯥꯏꯅ ꯕꯤ.ꯕꯤ.ꯑꯦꯐ.ꯅꯥ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  17%|████▍                      | 166/1000 [02:26<13:03,  1.06it/s]

[166/1000]
EN: A schedule preview listed Sri Lanka against Oman as a February 12 group-stage fixture.
MNI_MTEI: ꯁꯦꯗꯜꯚ ꯭ ꯌꯨꯗ ꯑꯃꯗ ꯁ ꯂꯡꯀꯥꯕꯨ ꯑꯣꯃꯥꯟꯒ ꯂꯥꯟꯊꯦꯡꯅꯕꯗ ꯐꯕꯋꯥꯔꯤ ꯒꯤ ꯒꯨꯞ-ꯦꯖ ꯐꯤꯆꯆꯔ ꯑꯣꯏꯅ ꯂꯤꯁꯠ ꯇꯧ
--------------------------------------------------

Translating:  17%|████▌                      | 167/1000 [02:27<13:18,  1.04it/s]

[167/1000]
EN: A schedule preview listed Nepal against Italy as a February 12 group-stage fixture.
MNI_MTEI: ꯁꯦꯗꯜꯚꯨꯅ ꯅꯦꯄꯥꯜꯕꯨ ꯏꯇꯂꯤꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯐꯦꯕꯋꯥꯔꯤ ꯒꯤ ꯒꯨꯞ-ꯦꯖ ꯐꯤꯆꯆꯔ ꯑꯣꯏꯅ ꯂꯤꯁꯠ ꯇꯧ
--------------------------------------------------

Translating:  17%|████▌                      | 168/1000 [02:28<13:14,  1.05it/s]

[168/1000]
EN: A schedule preview listed India against Namibia as a February 12 group-stage fixture.
MNI_MTEI: ꯁꯦꯗꯨꯜꯚꯋꯥ ꯑꯃꯗ ꯅꯦꯃꯤꯕꯥꯒ ꯂꯥꯟꯊꯦꯡꯅꯕꯗ ꯚꯥꯔꯠꯇꯥ ꯐꯕꯋꯥꯔꯤ ꯒꯤ ꯒꯨꯞ-ꯦꯖ ꯐꯤꯆꯆꯔ ꯑꯃ
--------------------------------------------------

Translating:  17%|████▌                      | 169/1000 [02:29<12:43,  1.09it/s]

[169/1000]
EN: Wanindu Hasaranga was ruled out of the World Cup due to an injury setback.
MNI_MTEI: ꯋꯥꯅꯤꯟꯗꯨ ꯍꯥꯁꯔꯥꯡꯒꯥ ꯑꯁꯤ ꯏꯟꯖꯨꯔꯤꯇꯤ ꯕꯦꯛꯕꯀꯒꯤ ꯃꯔꯝꯅꯥ ꯋꯥꯔꯂꯗ ꯀꯞꯇꯒꯤ ꯅꯥꯟꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  17%|████▌                      | 170/1000 [02:30<12:27,  1.11it/s]

[170/1000]
EN: Sri Lanka named Dushan Hemantha as a replacement after Wanindu Hasaranga’s injury.
MNI_MTEI: ꯋꯥꯅꯤꯟꯗꯨ ꯍꯥꯁꯔꯥꯡꯒꯥꯅ ꯁꯣꯛꯍꯜꯂꯕ ꯃꯇꯨꯡꯗ ꯁ ꯂꯡꯀꯅꯥ ꯗꯨꯁꯟ ꯍꯦꯃꯟꯊꯥꯕꯨ ꯑꯇꯣꯞꯄ ꯑꯃ ꯑꯣꯏꯅ ꯈꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  17%|████▌                      | 171/1000 [02:31<11:35,  1.19it/s]

[171/1000]
EN: The Indian Super League season was announced to begin on February 14, 2026.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟ ꯁꯨꯄꯔ ꯂꯤꯒ ꯁꯤꯖꯟ ꯑꯁꯤ ꯏꯪꯁꯣꯛ ꯒꯤ ꯐꯦꯕꯋꯥꯔꯤꯗꯒꯤ ꯍꯧꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  17%|████▋                      | 172/1000 [02:31<11:28,  1.20it/s]

[172/1000]
EN: Sports minister Mansukh Mandaviya announced an ISL start date of February 14.
MNI_MTEI: ꯄꯣꯔꯇꯁꯀꯤ ꯃꯟꯇ ꯃꯟꯁꯨꯈ ꯃꯟꯗꯚꯤꯌꯥꯅꯥ ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯑꯁꯤ ꯐꯦꯕꯋꯥꯔꯤꯗꯒꯤ ꯍꯧꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  17%|████▋                      | 173/1000 [02:32<11:02,  1.25it/s]

[173/1000]
EN: All 14 clubs agreed to participate in the Indian Super League season, according to reports.
MNI_MTEI: ꯔꯤꯄꯣꯔꯠꯁꯤꯡꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯀꯂꯕ ꯄꯨꯝꯅꯃꯛ ꯏꯟꯗꯤꯌꯟ ꯁꯨꯄꯔ ꯂꯤꯒ ꯁꯤꯖꯟꯗꯥ ꯁꯔꯨꯛ ꯌꯥꯅꯕ ꯌꯥꯈꯤ ꯫
--------------------------------------------------

Translating:  17%|████▋                      | 174/1000 [02:33<11:34,  1.19it/s]

[174/1000]
EN: The ISL decision followed meetings between the sports ministry and the All India Football Federation.
MNI_MTEI: ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯒꯤ ꯋꯥꯔꯦꯞ ꯑꯁꯤꯄꯣꯔꯇ ꯭ ꯁ ꯃꯟꯇ ꯑꯃꯁꯨꯡ ꯑꯣꯜ ꯏꯟꯗꯤꯌꯥ ꯐꯨꯇꯕꯣꯜ ꯐꯦꯗꯔꯦꯁꯟꯒꯤ ꯃꯔꯛꯇ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯃꯤꯐꯝꯁꯤꯡꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯂꯧꯈꯤꯕꯅꯤ ꯫
--------------------------------------------------

Translating:  18%|████▋                      | 175/1000 [02:34<11:31,  1.19it/s]

[175/1000]
EN: Indian football’s top-tier season moved forward after clubs accepted the participation plan.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯐꯨꯇꯕꯣꯜꯒꯤ ꯇꯣꯞ-ꯇꯤꯌꯔ ꯁꯤꯖꯟ ꯑꯁꯤ ꯀꯕꯁꯤꯡꯅꯥ ꯁꯔꯨꯛ ꯌꯥꯕꯒꯤ ꯊꯧꯔꯥꯡ ꯑꯗꯨ ꯑꯌꯥꯕ ꯄꯤꯔꯕꯥ ꯃꯇꯨꯡꯗ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯈꯤ ꯫
--------------------------------------------------

Translating:  18%|████▊                      | 176/1000 [02:35<12:04,  1.14it/s]

[176/1000]
EN: India’s women lost 0–3 to China in the Badminton Asia Team Championships quarterfinals.
MNI_MTEI: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯑꯦꯁꯤꯌꯥ ꯇꯤꯝ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯞꯁꯤꯡꯒꯤ ꯀ ꯭ ꯋꯥꯇꯔꯐꯥꯏꯂꯔꯇꯥ ꯆꯥꯏꯅꯥꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯅ 0/3 ꯇꯥ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  18%|████▊                      | 177/1000 [02:36<12:27,  1.10it/s]

[177/1000]
EN: P. V. Sindhu missed the team quarterfinal because of a minor injury, according to reports.
MNI_MTEI: ꯄꯤ. ꯚꯤ. ꯁꯤꯟꯙꯨꯅ ꯇꯤꯝꯒꯤ ꯀꯋꯥꯔꯇꯔ ꯐꯥꯏꯅꯥꯜ ꯑꯗꯨ ꯑꯄꯤꯛꯄ ꯑꯅꯥꯕꯥ ꯑꯃꯥꯅ ꯃꯔꯝ ꯑꯣꯏꯔꯒ ꯃꯥꯏꯊꯤꯈꯤ ꯍꯥꯏꯅ ꯔꯤꯄꯣꯔꯇꯁꯤꯡꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯍꯥꯏꯔꯤ ꯫
--------------------------------------------------

Translating:  18%|████▊                      | 178/1000 [02:37<11:53,  1.15it/s]

[178/1000]
EN: India’s women struggled to defend the 2024 title without PV Sindhu in the lineup.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯅ ꯏꯪ 2024 ꯒꯤ ꯇꯥꯏꯇꯥꯜ ꯑꯗꯨ ꯄꯤ.ꯚꯤ. ꯁꯤꯟꯙꯨ ꯌꯥꯎꯗꯅ ꯂꯥꯏꯟꯑꯞꯇ ꯉꯥꯛꯊꯣꯛꯅꯕ ꯀꯟꯅ ꯍꯣꯠꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  18%|████▊                      | 179/1000 [02:37<11:57,  1.14it/s]

[179/1000]
EN: China ended India’s women’s title defence with a straight 3–0 quarterfinal win.
MNI_MTEI: ꯆꯥꯏꯅꯥꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯇꯥꯏꯇꯥꯜ ꯗꯤꯐꯦꯟꯁ ꯑꯗꯨ ꯀ ꯭ ꯋꯥꯇꯔꯐꯥꯏꯅꯦꯜꯗꯥ ꯍꯛꯊꯦꯡꯅꯅ 3:0 ꯃꯥꯏ ꯄꯥꯛꯄꯥꯒ ꯂꯣꯏꯅꯅꯥ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  18%|████▊                      | 180/1000 [02:38<12:05,  1.13it/s]

[180/1000]
EN: The quarterfinal defeat closed India’s women’s campaign at the Badminton Asia Team Championships.
MNI_MTEI: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯑꯦꯁꯤꯌꯥ ꯇꯤꯝ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯄꯇꯋꯥꯇꯔ ꯐꯥꯏꯅꯦꯜꯗꯥ ꯃꯥꯏꯊꯤꯕꯥ ꯑꯁꯤꯅ ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯀꯦꯝꯄꯤꯌꯟ ꯑꯗꯨ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  18%|████▉                      | 181/1000 [02:39<12:27,  1.10it/s]

[181/1000]
EN: Devika Sihag won the Thailand Masters 2026 to claim a BWF Super 300 title.
MNI_MTEI: ꯗꯦꯕꯤꯀꯥ ꯁꯤꯍꯥꯒꯅꯥ ꯊꯥꯏꯂꯦꯟꯗ ꯃꯥꯇꯔꯁ 2026ꯇ ꯃꯥꯏ ꯄꯥꯛꯂꯗꯨꯅ ꯕꯤ. ꯗꯕꯜꯌꯨ. ꯑꯦꯐ. ꯁꯨꯄꯔ ꯇꯥꯏꯇꯥꯜ ꯑꯃꯥ ꯂꯧ
--------------------------------------------------

Translating:  18%|████▉                      | 182/1000 [02:40<12:35,  1.08it/s]

[182/1000]
EN: Devika Sihag became the youngest Indian woman to win a BWF Super 300 singles title.
MNI_MTEI: ꯗꯦꯕꯤꯀꯥ ꯁꯤꯍꯥꯒꯅꯥ ꯕꯤ. ꯗꯕꯜꯌꯨ.ꯐ. ꯁꯨꯄꯔ 300 ꯁꯤꯡꯒꯜꯁ ꯇꯥꯏꯇꯥꯜ ꯐꯪꯕꯥ ꯈ ꯭ ꯋꯥꯏꯗꯒꯤ ꯅꯧꯕ ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤ ꯑꯣꯏ
--------------------------------------------------

Translating:  18%|████▉                      | 183/1000 [02:41<12:59,  1.05it/s]

[183/1000]
EN: Devika Sihag joined Saina Nehwal and PV Sindhu in an exclusive Indian milestone list.
MNI_MTEI: ꯗꯦꯕꯤꯀꯥ ꯁꯤꯍꯥꯒꯅꯥ ꯁꯥꯏꯅꯥ ꯅꯦꯍꯋꯥꯜ ꯑꯃꯁꯨꯡ ꯄꯤ.ꯚꯤ. ꯁꯤꯟꯙꯨꯒꯥ ꯑꯦꯛꯁꯁꯤꯋꯦꯜ ꯏꯟꯗꯤꯌꯟ ꯃꯥꯏꯜꯆꯣꯟ ꯂꯤꯁꯇꯗꯥ ꯌꯥꯎ
--------------------------------------------------

Translating:  18%|████▉                      | 184/1000 [02:42<12:10,  1.12it/s]

[184/1000]
EN: Devika Sihag’s Bangkok celebration marked a breakthrough moment for Indian women’s singles.
MNI_MTEI: ꯗꯦꯕꯤꯀꯥ ꯁꯤꯍꯥꯒꯅꯥ ꯕꯦꯡꯀꯣꯛꯇ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯊꯧꯔꯝ ꯑꯁꯤ ꯚꯥꯔꯠꯀꯤ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯁꯤꯡꯒꯜꯁꯗꯥ ꯃꯔꯨ ꯑꯣꯏ
--------------------------------------------------

Translating:  18%|████▉                      | 185/1000 [02:43<12:14,  1.11it/s]

[185/1000]
EN: Devika Sihag’s title was described as a quiet announcement of a new Indian badminton star.
MNI_MTEI: ꯗꯦꯕꯤꯀꯥ ꯁꯤꯍꯥꯒꯀꯤ ꯇꯥꯏꯇꯥꯂ ꯑꯁꯤ ꯚꯥꯔꯠꯀꯤ ꯑꯅꯧꯕ ꯕꯦꯗꯃꯤꯟꯇꯟ ꯁꯔ ꯑꯃ ꯑꯣꯏꯔꯛꯄꯒꯤ ꯁꯣꯏꯅꯥ ꯂꯥꯎꯊꯣꯛꯄꯥ ꯑꯃꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  19%|█████                      | 186/1000 [02:44<12:04,  1.12it/s]

[186/1000]
EN: A matchday note listed Afghanistan against South Africa in Ahmedabad on February 11.
MNI_MTEI: ꯃꯦꯆ ꯗꯦ ꯅꯣꯇ ꯑꯃꯗ ꯑꯐꯒꯥꯅꯤꯁꯇꯥꯟꯕꯨ ꯐꯕꯋꯥꯔꯤ 11 ꯗꯥ ꯑꯍꯃꯗꯕꯥꯗꯇꯥ ꯁꯥꯎꯊ ꯑꯐꯀꯥꯒ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  19%|█████                      | 187/1000 [02:45<12:44,  1.06it/s]

[187/1000]
EN: A matchday note listed Australia against Ireland as another February 11 group-stage fixture.
MNI_MTEI: ꯃꯦꯆ ꯗꯦ ꯅꯣꯇ ꯑꯃꯥꯅꯥ ꯑꯣꯁꯇꯂꯤꯌꯥꯕꯨ ꯑꯥꯏꯔꯂꯦꯟꯗꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯐꯕꯕꯋꯥꯔꯤ 11 ꯒꯤ ꯒꯄ-ꯦꯖ ꯐꯤꯛꯆꯔ ꯑꯣꯏꯅ ꯂꯤꯁꯠ ꯇꯧ
--------------------------------------------------

Translating:  19%|█████                      | 188/1000 [02:46<12:25,  1.09it/s]

[188/1000]
EN: A matchday note listed England against West Indies as a February 11 evening fixture.
MNI_MTEI: ꯃꯦꯆ ꯗꯦ ꯅꯣꯇ ꯑꯃꯗ ꯏꯪꯂꯦꯟꯗꯄꯨ ꯋꯇ ꯏꯟꯗꯤꯖꯒ ꯂꯥꯟꯊꯦꯡꯅꯕꯗ ꯐꯕꯋꯥꯔꯤꯒꯤ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯐꯤꯛꯆꯔꯅꯤ ꯍꯥꯏꯅ ꯄꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  19%|█████                      | 189/1000 [02:47<12:15,  1.10it/s]

[189/1000]
EN: Afghanistan sought a rebound after losing their opener against New Zealand, according to reports.
MNI_MTEI: ꯔꯤꯄꯣꯔꯠꯁꯤꯡꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯑꯐꯒꯥꯅꯤꯁꯇꯥꯟꯅꯥ ꯃꯈꯣꯏꯒꯤ ꯑꯣꯄꯦꯅꯔ ꯑꯗꯨꯖꯤꯂꯦꯟꯗꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯃꯥꯏꯊꯤꯔꯕ ꯃꯇꯨꯡꯗ ꯔꯤꯕꯥꯎꯟꯗ ꯇꯧꯅꯕ ꯍꯣꯠꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  19%|█████▏                     | 190/1000 [02:48<12:46,  1.06it/s]

[190/1000]
EN: The February 11 schedule mixed former champions, contenders, and dangerous underdogs in group play.
MNI_MTEI: ꯐꯦꯕꯋꯥꯔꯤ 11ꯒꯤ ꯁꯦꯗꯜꯗꯥ ꯍꯥꯟꯅꯒꯤ ꯆꯦꯝꯄꯌꯟꯁꯤꯡ, ꯀꯟꯇꯦꯟꯗꯦꯟꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯑꯔꯨꯕꯥ ꯑꯟꯗꯔꯗꯣꯒꯁꯤꯡꯕꯨ ꯒꯞꯂꯦꯗꯥ ꯌꯥꯟꯁꯤꯟꯅ
--------------------------------------------------

Translating:  19%|█████▏                     | 191/1000 [02:49<13:12,  1.02it/s]

[191/1000]
EN: Baichung Bhutia blamed administration after Churchill Brothers were not added to ISL 2025–26.
MNI_MTEI: ꯆꯔꯆꯤꯜ ꯕꯗꯔꯁꯁꯤꯡ ꯑꯁꯤ ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ 2025/26 ꯗꯥ ꯌꯥꯎꯍꯟꯗꯕꯥ ꯃꯇꯨꯡꯗ ꯕꯥꯏꯆꯨꯡ ꯚꯨꯇꯤꯌꯥꯅꯥ ꯑꯦꯗꯃꯤꯅꯤꯁꯇꯦꯁꯟꯒꯤ ꯃꯔꯥꯜ ꯁꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  19%|█████▏                     | 192/1000 [02:50<13:17,  1.01it/s]

[192/1000]
EN: Churchill Brothers were not included in ISL 2025–26, prompting criticism from Baichung Bhutia.
MNI_MTEI: ꯆꯔꯆꯤꯜ ꯕꯗꯔꯁꯁꯤꯡ ꯑꯁꯤ ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ 2025/26 ꯗꯥ ꯌꯥꯎꯈꯤꯗꯦ, ꯃꯁꯤꯅ ꯕꯥꯏꯆꯨꯡ ꯚꯨꯇꯤꯌꯥꯗꯒꯤ ꯀꯇꯥꯏꯖꯦꯁꯟ ꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  19%|█████▏                     | 193/1000 [02:51<12:57,  1.04it/s]

[193/1000]
EN: Baichung Bhutia called the Churchill Brothers exclusion a clear administrative failure.
MNI_MTEI: ꯕꯥꯏꯆꯨꯡ ꯚꯨꯇꯤꯌꯥꯅꯥ ꯆꯔꯆꯤꯜ ꯕꯗꯔꯁꯁꯤꯡ ꯂꯧꯊꯣꯛꯄꯥ ꯑꯁꯤ ꯃꯌꯦꯛ ꯁꯦꯡꯕꯥ ꯂꯩꯉꯥꯛꯀꯤ ꯃꯥꯏꯊꯤꯕꯥ ꯑꯃꯅꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  19%|█████▏                     | 194/1000 [02:51<11:45,  1.14it/s]

[194/1000]
EN: The Churchill Brothers decision raised questions about the league’s selection and governance.
MNI_MTEI: ꯆꯔꯆꯤꯜ ꯕꯗꯔꯁꯀꯤ ꯋꯥꯔꯦꯞ ꯑꯁꯤꯅ ꯂꯤꯒ ꯑꯁꯤꯒꯤ ꯈꯟꯕꯒꯤ ꯑꯃꯁꯨꯡ ꯂꯩꯉꯥꯛꯄꯒꯤ ꯃꯇꯥꯡꯗ ꯆꯤꯡꯅꯕꯁꯤꯡ ꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  20%|█████▎                     | 195/1000 [02:52<11:14,  1.19it/s]

[195/1000]
EN: The ISL debate intensified after the Churchill Brothers issue surfaced in public comments.
MNI_MTEI: ꯆꯔꯆꯤꯜ ꯕꯗꯔꯁꯀꯤ ꯋꯥꯐꯝ ꯑꯁꯤ ꯃꯤꯌꯥꯝꯗꯥ ꯐꯣꯡꯗꯣꯛꯄꯗꯒꯤ ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯒꯤ ꯌꯦꯠꯅꯕ ꯑꯗꯨ ꯍꯦꯟꯅ ꯍꯦꯟꯒꯠꯂꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  20%|█████▎                     | 196/1000 [02:53<11:03,  1.21it/s]

[196/1000]
EN: India–Netherlands Davis Cup tie tightened after Sumit Nagal suffered a setback.
MNI_MTEI: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯥꯂꯅꯥ ꯃꯥꯏꯊꯤꯕꯥ ꯑꯃ ꯐꯪꯂꯕ ꯃꯇꯨꯡꯗ ꯏꯟꯗꯤꯌꯥ, ꯅꯦꯗꯔꯂꯦꯟꯗꯁ ꯗꯦꯚꯤꯁ ꯀꯄ ꯇꯥꯏ ꯑꯗꯨ ꯀꯟꯅ
--------------------------------------------------

Translating:  20%|█████▎                     | 197/1000 [02:54<11:09,  1.20it/s]

[197/1000]
EN: Sumit Nagal’s result added pressure as the Davis Cup tie moved toward a tense finish.
MNI_MTEI: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯒꯤ ꯐꯜꯅꯥ ꯗꯦꯚꯤꯁ ꯀꯄ ꯇꯥꯏ ꯑꯁꯤ ꯇꯦꯟꯁ ꯐꯤꯅꯤꯁꯀꯤ ꯃꯥꯏꯀꯩꯗ ꯆꯪꯁꯤꯜꯂꯛꯄꯗꯒꯤ ꯄꯁꯔ ꯍꯦꯟꯒꯠꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  20%|█████▎                     | 198/1000 [02:54<10:43,  1.25it/s]

[198/1000]
EN: India and Netherlands remained locked in a close Davis Cup contest after the Nagal match.
MNI_MTEI: ꯅꯥꯒꯥꯂ ꯃꯦꯆꯀꯤ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡ ꯅꯦꯗꯔꯂꯦꯟꯗꯁꯅ ꯗꯦꯚꯤꯁ ꯀꯄ ꯀꯟꯇꯦꯁꯇ ꯑꯗꯨ ꯂꯣꯏꯁꯤꯟ
--------------------------------------------------

Translating:  20%|█████▎                     | 199/1000 [02:55<10:57,  1.22it/s]

[199/1000]
EN: The Davis Cup tie needed late composure after the Sumit Nagal setback, according to reports.
MNI_MTEI: ꯄꯥꯎꯗꯝꯁꯤꯡꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯁꯨꯃꯤꯇ ꯅꯥꯒꯥꯂꯅꯥ ꯃꯥꯏꯊꯤꯔꯕ ꯃꯇꯨꯡꯗ ꯗꯦꯚꯤꯁ ꯀꯄ ꯇꯥꯏꯗꯥ ꯃꯇꯝ ꯀꯨꯏꯅ ꯆꯡꯖꯕꯥ ꯃꯊꯧ ꯇꯥꯈꯤ ꯫
--------------------------------------------------

Translating:  20%|█████▍                     | 200/1000 [02:56<11:17,  1.18it/s]

[200/1000]
EN: The Bengaluru Davis Cup atmosphere stayed intense as India fought Netherlands in a tight tie.
MNI_MTEI: ꯕꯦꯡꯂꯨꯨꯔꯨ ꯗꯦꯚꯤꯁ ꯀꯞꯀꯤ ꯑꯦꯠꯃꯣꯁꯐꯤꯌꯔ ꯑꯗꯨ ꯚꯥꯔꯠꯅ ꯅꯦꯗꯔꯂꯦꯟꯗꯁꯀ ꯆꯞ ꯆꯥꯕ ꯇꯥꯏꯗꯥ ꯂꯥꯟꯊꯦꯡꯅꯈꯤꯕꯅꯥ ꯀꯟꯅ ꯂꯦꯞ
--------------------------------------------------

Translating:  20%|█████▍                     | 201/1000 [02:57<11:57,  1.11it/s]

[201/1000]
EN: International Cricket Council confirmed the 2026 Men’s T20 World Cup starts on February 7.
MNI_MTEI: ꯏꯪꯁꯣꯛ 2026 ꯒꯤ ꯅꯨꯄꯥꯁꯤꯡꯒꯤ ꯇꯤ20 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞ ꯑꯁꯤ ꯐꯦꯕꯋꯥꯔꯤꯗꯥ ꯍꯧꯒꯅꯤ ꯍꯥꯏꯅ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯀꯀꯦꯠ ꯀꯥꯎꯟꯁꯤꯜꯅ ꯀꯟꯐꯔꯃꯦꯠ ꯇꯧ
--------------------------------------------------

Translating:  20%|█████▍                     | 202/1000 [02:58<11:22,  1.17it/s]

[202/1000]
EN: India were placed in Group A alongside Pakistan, Netherlands, USA, and Namibia.
MNI_MTEI: ꯚꯥꯔꯠꯄꯨ ꯄꯥꯀꯤꯁꯇꯥꯟ, ꯅꯦꯗꯔꯂꯦꯟꯁ, ꯌꯨ ꯑꯦꯁ ꯑꯦ ꯑꯃꯁꯨꯡ ꯅꯥꯃꯤꯕꯤꯌꯥꯒꯥ ꯂꯣꯏꯅꯅꯥ ꯒꯨꯞ ꯑꯦꯗꯥ ꯊꯝ
--------------------------------------------------

Translating:  20%|█████▍                     | 203/1000 [02:59<11:12,  1.18it/s]

[203/1000]
EN: Sri Lanka hosted several matches as the tournament ran across India and Sri Lanka venues.
MNI_MTEI: ꯂꯡꯀꯥꯅꯥ ꯃꯦꯆ ꯀꯌꯥ ꯑꯃ ꯄꯥꯡꯊꯣꯛꯈꯤ ꯃꯔꯝꯗꯤ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯁꯤ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡꯜꯂꯡꯀꯥꯒꯤ ꯃꯐꯝ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯆꯠꯊꯈꯤ ꯫
--------------------------------------------------

Translating:  20%|█████▌                     | 204/1000 [03:00<10:39,  1.24it/s]

[204/1000]
EN: India played the opening match against the USA at Wankhede Stadium in Mumbai.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯑꯍꯥꯟꯕ ꯃꯦꯆ ꯑꯗꯨ ꯃꯨꯝꯕꯥꯏꯒꯤ ꯋꯥꯡꯀꯦꯗꯦꯗꯤꯌꯝꯗꯥ ꯌꯨ ꯑꯦꯁ ꯑꯦꯒꯥ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  20%|█████▌                     | 205/1000 [03:00<10:21,  1.28it/s]

[205/1000]
EN: India faced Namibia on February 12 at Arun Jaitley Stadium in New Delhi.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯅꯕꯦꯝꯕꯔꯗꯥ ꯅꯤꯌꯨ ꯗꯤꯜꯂꯤꯒꯤ ꯑꯔꯨꯅ ꯖꯦꯇꯂꯤꯗꯤꯌꯝꯗꯥ ꯅꯥꯏꯃꯤꯕꯤꯌꯥꯒꯥ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  21%|█████▌                     | 206/1000 [03:01<09:57,  1.33it/s]

[206/1000]
EN: India travelled to Colombo to play Pakistan in a group-stage match.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯀꯂꯝꯕꯣꯗꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯥ ꯒꯄ-ꯦꯖ ꯃꯦꯆ ꯑꯃꯗ ꯁꯥꯟꯅꯅꯕ ꯆꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  21%|█████▌                     | 207/1000 [03:02<10:02,  1.32it/s]

[207/1000]
EN: Pakistan versus Netherlands was listed as a Group A fixture on February 7.
MNI_MTEI: ꯄꯥꯀꯤꯁꯇꯥꯟ ꯑꯃꯁꯨꯡ ꯅꯦꯗꯔꯂꯦꯟꯁ ꯑꯁꯤ ꯐꯦꯕꯋꯥꯔꯤꯗꯥ ꯒꯄ ꯑꯦꯒꯤ ꯐꯤꯛꯆꯔ ꯑꯃꯥ ꯑꯣꯏꯅ ꯂꯤꯁꯠ ꯇꯧ
--------------------------------------------------

Translating:  21%|█████▌                     | 208/1000 [03:02<09:44,  1.35it/s]

[208/1000]
EN: India versus USA was scheduled as a Group A match on February 7.
MNI_MTEI: ꯐꯕꯋꯥꯔꯤꯗꯥ ꯏꯟꯗꯤꯌꯥ ꯚꯔꯁ ꯌꯨ ꯑꯦꯁ ꯑꯦ ꯑꯁꯤ ꯒꯄ ꯑꯦꯒꯤ ꯃꯦꯆ ꯑꯃ ꯑꯣꯏꯅ ꯂꯦꯞꯈꯤ ꯫
--------------------------------------------------

Translating:  21%|█████▋                     | 209/1000 [03:03<10:14,  1.29it/s]

[209/1000]
EN: Group D fixtures began with Afghanistan playing New Zealand on February 8 in Chennai.
MNI_MTEI: ꯒꯄ ꯗꯤ ꯐꯤꯛꯆꯔꯁꯤꯡ ꯑꯁꯤ ꯑꯐꯒꯥꯅꯤꯁꯇꯥꯟꯅꯥ ꯅꯌꯨ ꯖꯤꯂꯦꯟꯗꯀ ꯁꯥꯟꯅꯗꯨꯅꯥ ꯐꯕꯋꯥꯔꯤꯗꯥ ꯆꯦꯟꯅꯥꯏꯗꯥ ꯍꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  21%|█████▋                     | 210/1000 [03:04<10:23,  1.27it/s]

[210/1000]
EN: Canada played South Africa on February 9 at Narendra Modi Stadium in Ahmedabad.
MNI_MTEI: ꯀꯦꯅꯥꯗꯥꯅꯥ ꯐꯕꯋꯥꯔꯤ ꯗꯥ ꯑꯍꯃꯗꯕꯥꯗꯀꯤ ꯅꯔꯦꯟ ꯃꯣꯗꯤꯗꯤꯌꯝꯗꯥ ꯁꯥꯎꯊ ꯑꯐꯀꯥꯗꯥ ꯁꯥꯟꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  21%|█████▋                     | 211/1000 [03:05<10:02,  1.31it/s]

[211/1000]
EN: Ishan Kishan smashed 61 off 24 balls against Namibia in New Delhi.
MNI_MTEI: ꯏꯁꯥꯟ ꯀꯤꯁꯟꯅ ꯅꯤꯌꯨ ꯗꯤꯜꯂꯤꯗꯥ ꯅꯥꯏꯃꯤꯕꯥꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯕꯣꯜꯗꯥ 61 ꯔꯟ ꯂꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  21%|█████▋                     | 212/1000 [03:06<10:14,  1.28it/s]

[212/1000]
EN: Hardik Pandya featured prominently as India posted 209 for nine against Namibia.
MNI_MTEI: ꯍꯔꯗꯤꯛ ꯄꯥꯟꯗꯌꯅꯥ ꯃꯁꯛ ꯊꯣꯛꯄ ꯁꯛꯇꯝ ꯂꯥꯡꯈꯤ ꯃꯔꯝꯗꯤ ꯚꯥꯔꯠꯅ ꯅꯥꯏꯃꯤꯕꯥꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯃꯥꯄꯟꯗ ꯄꯣꯂ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  21%|█████▊                     | 213/1000 [03:06<10:12,  1.29it/s]

[213/1000]
EN: Varun Chakaravarthy took three wickets as India beat Namibia by 93 runs.
MNI_MTEI: ꯋꯥꯔꯨꯟ ꯆꯀꯔꯥꯚꯔꯊꯤꯅꯥ ꯋꯤꯀꯦꯠ ꯑꯍꯨꯝ ꯂꯧꯈꯤꯕꯗꯒꯤ ꯚꯥꯔꯠꯅ ꯅꯥꯏꯃꯤꯕꯤꯌꯥꯕꯨ ꯔꯟ 93ꯅꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤ
--------------------------------------------------

Translating:  21%|█████▊                     | 214/1000 [03:07<09:49,  1.33it/s]

[214/1000]
EN: India bundled out Namibia for 116 while defending a target of 210.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯅꯤꯃꯤꯕꯤꯌꯥꯕꯨ ꯏꯪ ꯒꯤ ꯇꯔꯀꯦꯇ ꯑꯃ ꯉꯥꯛꯊꯣꯛꯂꯗꯨꯅ ꯏꯪ 116 ꯗꯥ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  22%|█████▊                     | 215/1000 [03:08<10:09,  1.29it/s]

[215/1000]
EN: Namibia captain Gerhard Erasmus won the toss and chose to bat first.
MNI_MTEI: ꯅꯦꯃꯤꯕꯥꯒꯤ ꯀꯦꯞꯇꯦꯟ ꯒꯥꯔꯍꯥꯔꯗ ꯏꯔꯥꯁꯃꯁꯅ ꯇꯣꯁ ꯑꯗꯨ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯑꯃꯁꯨꯡ ꯑꯍꯥꯟꯕꯗꯥ ꯕꯦꯇꯤꯡ ꯇꯧꯅꯕ ꯈꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  22%|█████▊                     | 216/1000 [03:09<09:52,  1.32it/s]

[216/1000]
EN: India versus Namibia started at 7:00 PM IST at Arun Jaitley Stadium.
MNI_MTEI: ꯏꯟꯗꯤꯌꯥ ꯚꯔꯁ नमꯕꯤꯕꯥ ꯑꯁꯤ ꯑꯔꯨꯅ ꯖꯦꯇꯂꯤꯗꯤꯌꯝꯗꯥ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯄꯨꯡ ꯗꯥ ꯍꯧ
--------------------------------------------------

Translating:  22%|█████▊                     | 217/1000 [03:09<09:19,  1.40it/s]

[217/1000]
EN: India’s first match was a win against the USA in Mumbai.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯑꯍꯥꯟꯕꯥ ꯃꯦꯆ ꯑꯗꯨ ꯃꯨꯝꯕꯥꯏꯗ ꯌꯨ ꯑꯦꯁ ꯑꯦꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯃꯥꯏꯄꯥꯛꯄꯥ
--------------------------------------------------

Translating:  22%|█████▉                     | 218/1000 [03:10<08:46,  1.48it/s]

[218/1000]
EN: India versus Namibia was labelled as game 18 of the tournament.
MNI_MTEI: ꯏꯟꯗꯤꯌꯥ ꯚꯔꯁꯠ ꯅꯥꯃꯤꯕꯤꯌꯥ ꯑꯁꯤ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯁꯤꯒꯤ ꯒꯦꯝ ꯍꯥꯏꯅ ꯂꯦꯕꯦꯜ ꯇꯧ
--------------------------------------------------

Translating:  22%|█████▉                     | 219/1000 [03:11<09:19,  1.40it/s]

[219/1000]
EN: Suryakumar Yadav led India against Namibia in the ongoing T20 World Cup.
MNI_MTEI: ꯍꯧꯖꯤꯛ ꯆꯠꯊꯔꯤꯕ ꯇꯤ20 ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯄꯇꯥ ꯅꯤꯃꯤꯕꯥꯒ ꯂꯥꯟꯊꯦꯡꯅꯕꯗ ꯁꯨꯔꯌꯀꯨꯃꯔ ꯌꯥꯗꯕꯅꯥ ꯚꯥꯔꯠꯄꯨ ꯂꯨꯆꯤꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  22%|█████▉                     | 220/1000 [03:11<09:11,  1.41it/s]

[220/1000]
EN: India entered the Namibia match after beating the USA in their opener.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯃꯈꯣꯏꯒꯤ ꯑꯣꯄꯦꯅꯔꯗꯥ ꯌꯨ ꯑꯦꯁ ꯑꯦꯕꯨ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯔꯕꯥ ꯃꯇꯨꯡꯗ ꯅꯥꯏꯃꯤꯕꯥ ꯃꯦꯆꯇꯥ ꯆꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  22%|█████▉                     | 221/1000 [03:12<08:35,  1.51it/s]

[221/1000]
EN: The Pakistan government allowed the Pakistan team to play India on February 15.
MNI_MTEI: ꯄꯥꯀꯤꯁꯇꯥꯟ ꯁꯔꯀꯥꯔꯅꯥ ꯐꯕꯋꯥꯔꯤꯗꯥ ꯚꯥꯔꯠꯇꯥ ꯁꯥꯟꯅꯕꯒꯤ ꯑꯌꯥꯕ ꯄꯤ
--------------------------------------------------

Translating:  22%|█████▉                     | 222/1000 [03:13<08:47,  1.48it/s]

[222/1000]
EN: India versus Pakistan was scheduled for Colombo after weeks of uncertainty.
MNI_MTEI: ꯆꯌꯣꯜ ꯀꯌꯥꯒꯤ ꯑꯔꯦꯞꯄ ꯂꯩꯇꯕꯥ ꯃꯇꯨꯡꯗ ꯏꯟꯗꯤꯌꯥ ꯚꯔꯁꯠ ꯄꯥꯀꯤꯁꯇꯥꯟ ꯑꯁꯤ ꯀꯣꯂꯝꯕꯣꯗꯥ ꯄꯥꯡꯊꯣꯛꯀꯗꯧꯔꯝꯃꯤ ꯫
--------------------------------------------------

Translating:  22%|██████                     | 223/1000 [03:13<08:58,  1.44it/s]

[223/1000]
EN: India versus Pakistan was described as a group-stage match in Colombo.
MNI_MTEI: ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡ ꯄꯥꯀꯤꯁꯇꯥꯟ ꯑꯁꯤ ꯀꯣꯂꯝꯕꯣꯗꯥ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯒꯨꯞ-ꯦꯖ ꯃꯦꯆꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  22%|██████                     | 224/1000 [03:14<09:02,  1.43it/s]

[224/1000]
EN: The tournament was listed as featuring 55 matches across India and Sri Lanka.
MNI_MTEI: ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯁꯤ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡꯂꯡꯀꯥ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯃꯦꯆ 55 ꯄꯥꯡꯊꯣꯛꯈꯤ ꯍꯥꯏꯅ ꯂꯤꯁꯠ ꯇꯧ
--------------------------------------------------

Translating:  22%|██████                     | 225/1000 [03:15<09:49,  1.31it/s]

[225/1000]
EN: The schedule included Delhi, Kolkata, Ahmedabad, Chennai, Mumbai, Colombo, and Kandy venues.
MNI_MTEI: ꯁꯦꯗꯜ ꯑꯁꯤꯗ ꯗꯤꯜꯂꯤ, ꯀꯣꯜꯀꯥꯇꯥ, ꯑꯍꯃꯗꯕꯥꯗ, ꯆꯦꯟꯅꯥꯏ, ꯃꯨꯝꯕꯥꯏ, ꯀꯣꯂꯝꯕꯣ ꯑꯃꯁꯨꯡ ꯀꯟꯗꯤꯒꯤ ꯃꯐꯝꯁꯤꯡ ꯌꯥꯎ
--------------------------------------------------

Translating:  23%|██████                     | 226/1000 [03:16<10:28,  1.23it/s]

[226/1000]
EN: Afghanistan faced New Zealand at M. A. Chidambaram Stadium with an 11:00 AM start.
MNI_MTEI: ꯑꯦꯝ. ꯑꯦ. ꯆꯤꯗꯝꯕꯔꯝꯗꯤꯌꯝꯗꯥ ꯑꯌꯨꯛ ꯄꯨꯡꯗꯒꯤ ꯍꯧꯕꯥ ꯃꯇꯝꯗꯥ ꯑꯐꯒꯥꯅꯤꯁꯇꯥꯟꯅꯥ ꯅꯖꯤꯂꯦꯟꯗꯀ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  23%|██████▏                    | 227/1000 [03:17<10:29,  1.23it/s]

[227/1000]
EN: New Zealand played UAE on February 10 at M. A. Chidambaram Stadium.
MNI_MTEI: ꯐꯕꯋꯥꯔꯤ ꯗꯥ ꯑꯦꯝ. ꯑꯦ. ꯆꯤꯗꯝꯕꯔꯝꯗꯤꯌꯝꯗꯥꯖꯤꯂꯦꯟꯗꯅꯥ ꯌꯨ.ꯑꯦ. ꯏ.ꯒꯥ ꯁꯥꯟꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  23%|██████▏                    | 228/1000 [03:18<10:45,  1.20it/s]

[228/1000]
EN: Group D included UAE, New Zealand, South Africa, Afghanistan, and Canada in one pool.
MNI_MTEI: ꯒꯄ ꯗꯤꯗꯥ ꯄꯨꯂ ꯑꯃꯗ ꯌꯨ ꯑꯦ ꯏ ꯅ ꯭ ꯌꯨ ꯖꯤꯂꯦꯟꯗ ꯈꯥ ꯑꯐꯀꯥ ꯑꯐꯒꯥꯅꯤꯁꯇꯥꯟ ꯑꯃꯁꯨꯡ ꯀꯅꯥꯗꯥ ꯌꯥꯎ
--------------------------------------------------

Translating:  23%|██████▏                    | 229/1000 [03:18<10:09,  1.26it/s]

[229/1000]
EN: India’s group-stage route moved from Mumbai to Delhi and then Colombo.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯒꯄ-ꯦꯖ ꯂꯝꯕꯤ ꯑꯁꯤ ꯃꯨꯝꯕꯥꯏꯗꯒꯤ ꯗꯤꯜꯂꯤ ꯑꯃꯁꯨꯡ ꯃꯗꯨꯒꯤ ꯃꯇꯨꯡꯗ ꯀꯣꯂꯝꯕꯣꯗꯥ ꯍꯣꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  23%|██████▏                    | 230/1000 [03:19<10:26,  1.23it/s]

[230/1000]
EN: The India versus Namibia match preview named Gerhard Erasmus as Namibia’s captain.
MNI_MTEI: ꯏꯟꯗꯤꯌꯥ ꯚꯔꯁ ꯅꯥꯏꯃꯤꯕꯤꯌꯥ ꯃꯦꯆꯚꯗꯥ ꯅꯦꯃꯤꯕꯤꯌꯥꯒꯤ ꯀꯦꯞꯇꯦꯟ ꯑꯣꯏꯅ ꯒꯥꯔꯍꯥꯔꯗ ꯏꯔꯥꯁꯃꯁ ꯈꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  23%|██████▏                    | 231/1000 [03:20<10:21,  1.24it/s]

[231/1000]
EN: A report said Abhishek Sharma underwent checks for a stomach bug in New Delhi.
MNI_MTEI: ꯔꯤꯄꯣꯔꯇ ꯑꯃꯥꯅꯥ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯑꯚꯥꯁꯤꯛ ꯁꯔꯃꯥꯅꯥ ꯅ ꯗꯤꯜꯂꯤꯗꯥ ꯄꯣꯇꯥꯁꯒꯤ ꯕꯒ ꯑꯃ ꯆꯦꯛ ꯇꯧ
--------------------------------------------------

Translating:  23%|██████▎                    | 232/1000 [03:21<10:53,  1.18it/s]

[232/1000]
EN: The same report said Abhishek Sharma missed India’s Namibia game despite hospital discharge.
MNI_MTEI: ꯍꯣꯁꯄꯤꯇꯥꯜꯗꯒꯤ ꯗꯤꯁꯆꯥꯔꯖ ꯇꯧꯔꯕꯁꯨ ꯑꯚꯥꯁꯤꯛ ꯁꯔꯃꯥꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯅꯥꯃꯤꯕꯤꯌꯥ ꯒꯦꯝ ꯑꯗꯨ ꯃꯥꯡꯈꯤ ꯍꯥꯏꯅ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯃꯛꯇꯗꯥ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  23%|██████▎                    | 233/1000 [03:22<10:09,  1.26it/s]

[233/1000]
EN: Sanju Samson’s World Cup debut was described as lasting only eight deliveries.
MNI_MTEI: ꯁꯟꯖꯨ ꯁꯦꯝꯁꯣꯟꯒꯤ ꯑꯍꯥꯟꯕ ꯋꯥꯔꯂꯗ ꯀꯄ ꯑꯗꯨ ꯃꯇꯝ ꯅꯤꯄꯥꯜ ꯈꯛꯇꯃꯛ ꯂꯦꯞꯈꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  23%|██████▎                    | 234/1000 [03:22<09:34,  1.33it/s]

[234/1000]
EN: The tournament’s Group A opened across venues in India and Sri Lanka.
MNI_MTEI: ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯁꯤꯒꯤ ꯒꯄ ꯑꯦ ꯑꯁꯤ ꯚꯥꯔꯠ ꯑꯃꯁꯨꯡꯂꯡꯀꯥꯒꯤ ꯃꯐꯝ ꯄꯨꯝꯅꯃꯛꯇ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  24%|██████▎                    | 235/1000 [03:23<08:53,  1.43it/s]

[235/1000]
EN: India’s match against Namibia was played on Thursday, February 12.
MNI_MTEI: ꯅꯦꯃꯤꯕꯥꯒ ꯚꯥꯔꯇꯀꯤ ꯃꯦꯆ ꯑꯁꯤ ꯐꯦꯕꯋꯥꯔꯤ ꯇꯥꯡ ꯁꯨꯔꯦꯁꯟꯗ ꯁꯥꯟꯅ
--------------------------------------------------

Translating:  24%|██████▎                    | 236/1000 [03:24<09:41,  1.31it/s]

[236/1000]
EN: Nepal versus Italy appeared as a live-score fixture during the T20 World Cup schedule.
MNI_MTEI: ꯇꯤ20 ꯋꯥꯔꯂꯗ ꯀꯞꯀꯤ ꯁꯦꯗꯜꯗꯥ ꯅꯦꯄꯥꯜ ꯑꯃꯁꯨꯡ ꯏꯇꯂꯤꯒꯤ ꯃꯔꯛꯇ ꯂꯥꯏꯕ-ꯁꯣꯀꯔ ꯐꯤꯆꯆꯔ ꯑꯃ ꯑꯣꯏꯅ ꯎꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  24%|██████▍                    | 237/1000 [03:25<10:40,  1.19it/s]

[237/1000]
EN: Australia versus Zimbabwe appeared as a live-score fixture on the Indian Express cricket feed.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟ ꯑꯦꯛꯁꯄꯦꯁ ꯀꯀꯦꯠ ꯐꯤꯗꯇꯥ ꯑꯣꯁꯇꯂꯤꯌꯥ ꯑꯃꯁꯨꯡ ꯖꯤꯝꯕꯥꯕꯦꯒꯤ ꯃꯔꯛꯇ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯑꯁꯤ ꯂꯥꯏꯚ-ꯁꯀꯣꯔ ꯐꯤꯛꯆꯔ ꯑꯃ ꯑꯣꯏꯅ ꯎꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  24%|██████▍                    | 238/1000 [03:25<10:34,  1.20it/s]

[238/1000]
EN: The Indian Express sports section highlighted India’s 93-run win over Namibia.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟ ꯑꯦꯛꯁꯄꯔꯁꯄꯣꯔꯇꯁ ꯁꯦꯛꯁꯟ ꯑꯁꯤꯅ ꯅꯦꯃꯤꯕꯥꯕꯨ ꯚꯥꯔꯠꯅ ꯔꯟ 93ꯅꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯕꯒꯤ ꯃꯁꯛ ꯇꯥꯛ
--------------------------------------------------

Translating:  24%|██████▍                    | 239/1000 [03:26<10:28,  1.21it/s]

[239/1000]
EN: The match report said India’s bowling attack dismantled Namibia during the chase.
MNI_MTEI: ꯃꯦꯆ ꯔꯤꯄꯣꯔꯇꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯚꯥꯔꯠꯀꯤ ꯕꯣꯜꯂꯤꯡ ꯑꯦꯇꯦꯛꯅꯥ ꯇꯥꯟꯅꯕꯒꯤ ꯃꯇꯝꯗꯥ ꯅꯥꯏꯃꯤꯕꯤꯌꯥꯕꯨ ꯃꯥꯡꯍꯟ ꯇꯥꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  24%|██████▍                    | 240/1000 [03:27<10:18,  1.23it/s]

[240/1000]
EN: The India versus Namibia highlights credited Ishan Kishan’s 61 with driving India’s total.
MNI_MTEI: ꯏꯟꯗꯤꯌꯥ ꯚꯔꯁ ꯅꯦꯃꯤꯕꯤꯌꯥꯅꯥ ꯏꯁꯥꯟ ꯀꯤꯁꯥꯟꯒꯤ 61ꯅ ꯚꯥꯔꯠꯀꯤ ꯑꯄꯨꯟꯕꯕꯨ ꯊꯧꯒꯠꯈꯤ ꯍꯥꯏꯕ ꯑꯗꯨ ꯊꯣꯏꯗꯣꯛ ꯍꯦꯟꯗꯣꯛꯄ
--------------------------------------------------

Translating:  24%|██████▌                    | 241/1000 [03:28<10:11,  1.24it/s]

[241/1000]
EN: ISL 2025–26 fixtures began on February 14 with a double-header format.
MNI_MTEI: ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ 2025,26 ꯐꯤꯛꯆꯔꯁꯤꯡ ꯑꯁꯤ ꯗꯕꯜ-ꯍꯦꯗꯔ ꯐꯣꯔꯃꯦꯇ ꯑꯃꯒ ꯂꯣꯏꯅꯅ ꯐꯦꯕꯋꯥꯔꯤꯗꯥ ꯍꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  24%|██████▌                    | 242/1000 [03:29<10:26,  1.21it/s]

[242/1000]
EN: Mohun Bagan Super Giant faced Kerala Blasters in the season opener in Kolkata.
MNI_MTEI: ꯀꯣꯜꯀꯥꯇꯥꯗꯥ ꯁꯤꯖꯟ ꯑꯣꯄꯦꯅꯔꯗꯥ ꯃꯣꯍꯣꯟ ꯕꯥꯒꯥꯟ ꯁꯨꯄꯔ ꯖꯥꯏꯅꯇꯅ ꯀꯦꯔꯂꯥ ꯕꯁꯇꯔꯁꯀ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  24%|██████▌                    | 243/1000 [03:29<10:04,  1.25it/s]

[243/1000]
EN: FC Goa hosted Inter Kashi at Fatorda Stadium on February 14.
MNI_MTEI: ꯑꯦꯐ ꯁꯤ ꯒꯣꯋꯥꯅꯥ ꯐꯦꯕꯨꯋꯥꯔꯤꯗꯥ ꯐꯇꯣꯔꯗꯥꯗꯤꯌꯝꯗꯥ ꯏꯟꯇꯔ ꯀꯥꯁꯤ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  24%|██████▌                    | 244/1000 [03:30<09:28,  1.33it/s]

[244/1000]
EN: The first match on double-header days started at 5:00 PM IST.
MNI_MTEI: ꯗꯕꯜ-ꯍꯦꯗꯔ ꯗꯦꯗꯥ ꯑꯍꯥꯟꯕ ꯃꯦꯆ ꯑꯁꯤ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯄꯨꯡ ꯗꯥ ꯍꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  24%|██████▌                    | 245/1000 [03:31<08:59,  1.40it/s]

[245/1000]
EN: The second match on double-header days started at 7:30 PM IST.
MNI_MTEI: ꯗꯕꯜ-ꯍꯦꯗꯔ ꯗꯦꯗꯥ ꯑꯅꯤꯁꯨꯕ ꯃꯦꯆ ꯑꯁꯤ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯄꯨꯡ ꯗꯥ ꯍꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  25%|██████▋                    | 246/1000 [03:32<09:34,  1.31it/s]

[246/1000]
EN: A report said the ISL season would use a single-leg home-and-away format.
MNI_MTEI: ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯁꯤꯖꯟ ꯑꯁꯤꯗ ꯁꯤꯡꯒꯜ-ꯂꯦꯒ ꯍꯣꯝ- ꯑꯦꯟꯗ-ꯑꯋꯦ ꯐꯣꯔꯃꯦꯇ ꯑꯃ ꯁꯤꯖꯤꯟꯅꯒꯅꯤ ꯍꯥꯏꯅ ꯔꯤꯄꯣꯔꯇ ꯑꯃꯥꯅꯥ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  25%|██████▋                    | 247/1000 [03:33<10:30,  1.19it/s]

[247/1000]
EN: The Indian Express football page reported FanCode won exclusive ISL media rights.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟ ꯑꯦꯛꯁꯄꯦꯁꯀꯤ ꯐꯨꯇꯕꯣꯜ ꯄꯦꯖꯗꯥ ꯐꯥꯟꯀꯣꯗꯅ ꯑꯦꯛꯁꯁꯤꯋꯦꯜ ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯃꯤꯗꯤꯌꯥ ꯔꯥꯏꯇꯁꯤꯡ ꯐꯪꯂꯦ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  25%|██████▋                    | 248/1000 [03:33<10:18,  1.22it/s]

[248/1000]
EN: The same report said ISL per-match valuation dropped by about 95 percent.
MNI_MTEI: ꯆꯞ ꯃꯥꯟꯅꯕ ꯔꯤꯄꯣꯔꯇ ꯑꯁꯤꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯄꯔ-ꯃꯦꯆ ꯚꯦꯜꯌꯨꯑꯦꯁꯟ ꯑꯁꯤ ꯆꯥꯎꯔꯥꯛꯅ ꯆꯥꯗ ꯍꯟꯊꯔꯦ ꯫
--------------------------------------------------

Translating:  25%|██████▋                    | 249/1000 [03:34<10:17,  1.22it/s]

[249/1000]
EN: The ISL report described a truncated season with pay cuts at multiple clubs.
MNI_MTEI: ꯑꯥꯏ ꯑꯦꯁ ꯑꯦꯜ ꯒꯤ ꯔꯤꯄꯣꯔꯇ ꯑꯁꯤꯅ ꯀꯂꯕ ꯀꯌꯥꯗꯥ ꯄꯦ ꯀꯛꯊꯕꯥꯒ ꯂꯣꯏꯅꯅꯥ ꯁꯤꯖꯟ ꯑꯃ ꯀꯛꯊꯣꯛꯈꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  25%|██████▊                    | 250/1000 [03:35<10:35,  1.18it/s]

[250/1000]
EN: Real Madrid CF hoped a La Liga surge was boosted by a team dinner.
MNI_MTEI: ꯔꯦꯌꯦꯜ ꯃꯦꯗꯔꯤꯗ ꯁꯤꯐꯅꯥ ꯂꯥ ꯂꯤꯒꯥꯒꯤ ꯆꯥꯡ ꯍꯦꯟꯒꯠꯂꯛꯄ ꯑꯁꯤ ꯇꯤꯝꯒꯤ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯆꯤꯟꯖꯥꯛ ꯑꯃꯅ ꯍꯦꯟꯒꯠꯍꯟꯒꯅꯤ ꯍꯥꯏꯅ ꯊꯥꯖꯈꯤ ꯫
--------------------------------------------------

Translating:  25%|██████▊                    | 251/1000 [03:36<10:42,  1.17it/s]

[251/1000]
EN: The Real Madrid dinner was reportedly paid for by Vinícius Júnior and Kylian Mbappé.
MNI_MTEI: ꯔꯦꯌꯦꯜ ꯃꯦꯗꯗꯀꯤ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯆꯤꯟꯖꯥꯛ ꯑꯗꯨ ꯚꯤꯅꯤꯁꯤꯌꯁ ꯖꯨꯅꯤꯌꯔ ꯑꯃꯁꯨꯡ ꯀꯥꯏꯂꯤꯌꯟ ꯑꯦꯝꯕꯥꯄꯦꯅꯥ ꯄꯤꯈꯤꯕꯅꯤ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  25%|██████▊                    | 252/1000 [03:37<10:58,  1.14it/s]

[252/1000]
EN: Barcelona aimed for a fourth straight league win against Girona in La Liga.
MNI_MTEI: ꯕꯥꯔꯁꯤꯂꯣꯅꯥꯅꯥ ꯂꯥ ꯂꯤꯒꯥꯗꯥ ꯖꯤꯔꯣꯅꯥꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯃꯊꯪ-ꯇꯣꯉꯛꯄꯥ ꯃꯔꯤꯁꯨꯕ ꯂꯤꯒꯇ ꯃꯥꯏ ꯄꯥꯛꯄꯒꯤ ꯄꯥꯟꯗꯝ ꯊꯝ
--------------------------------------------------

Translating:  25%|██████▊                    | 253/1000 [03:38<11:01,  1.13it/s]

[253/1000]
EN: Barcelona visited Atlético Madrid for a Copa del Rey first-leg clash.
MNI_MTEI: ꯕꯥꯔꯁꯤꯂꯣꯅꯥꯅꯥ ꯑꯦꯇꯦꯇꯤꯀꯣ ꯃꯦꯗꯗꯇꯥ ꯀꯣꯄꯥ ꯗꯦꯂ ꯔꯦꯒꯤ ꯐꯔꯁꯠ ꯂꯦꯒ ꯀꯂꯦꯁꯀꯤꯗꯃꯛ ꯆꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  25%|██████▊                    | 254/1000 [03:39<10:58,  1.13it/s]

[254/1000]
EN: Barcelona entered the Atlético Madrid match after winning 17 of 18 matches.
MNI_MTEI: ꯕꯥꯔꯁꯤꯂꯣꯅꯥꯅꯥ ꯑꯦꯇꯦꯇꯤꯀꯣ ꯃꯦꯗꯗ ꯃꯦꯆꯇ ꯆꯪꯈꯤ ꯑꯃꯁꯨꯡ ꯃꯦꯊꯆ 18ꯒꯤ ꯃꯅꯨꯡꯗ 17 ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  26%|██████▉                    | 255/1000 [03:39<10:25,  1.19it/s]

[255/1000]
EN: Real Madrid and UEFA announced an agreement ending the Super League project.
MNI_MTEI: ꯔꯤꯌꯦꯜ ꯃꯦꯗꯗ ꯑꯃꯁꯨꯡ ꯌꯨ ꯏ ꯑꯦꯐ ꯑꯦꯅꯥ ꯁꯨꯄꯔ ꯂꯤꯒꯖꯦꯛꯇ ꯂꯣꯏꯁꯤꯟꯕꯥ ꯌꯥꯅꯕ ꯑꯃ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  26%|██████▉                    | 256/1000 [03:40<09:58,  1.24it/s]

[256/1000]
EN: Barcelona formally pulled out of the Super League days before the agreement.
MNI_MTEI: ꯌꯥꯅꯕ ꯑꯗꯨꯒꯤ ꯅꯨꯃꯤꯠ ꯈꯔꯅꯤꯒꯤ ꯃꯃꯥꯡꯗ ꯕꯥꯔꯁꯤꯂꯣꯅꯥꯅꯥ ꯁꯨꯄꯔ ꯂꯤꯒꯇꯒꯤ ꯐꯣꯔꯃꯦꯂꯤ ꯑꯣꯏꯅ ꯂꯧꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  26%|██████▉                    | 257/1000 [03:41<10:35,  1.17it/s]

[257/1000]
EN: Tottenham Hotspur reportedly sacked Thomas Frank after a 2–1 loss to Newcastle United.
MNI_MTEI: ꯇꯣꯇꯦꯅꯍꯃ ꯍꯣꯠꯁꯄꯨꯔꯅꯥ ꯇꯣꯃꯥꯁ ꯐꯦꯡꯀꯕꯨ ꯅꯀꯥꯁꯦꯜ ꯌꯨꯅꯤꯇꯦꯗꯇꯥ 2/1 ꯃꯥꯏꯊꯤꯔꯕ ꯃꯇꯨꯡꯗ ꯂꯧꯊꯣꯛꯈꯤ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  26%|██████▉                    | 258/1000 [03:42<10:20,  1.20it/s]

[258/1000]
EN: The Tottenham report said the club still had no league win in 2026.
MNI_MTEI: ꯇꯣꯇꯦꯅꯍꯝꯒꯤ ꯔꯤꯄꯣꯔꯇꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯏꯪꯁꯣꯛꯗꯥ ꯀꯂꯕ ꯑꯁꯤꯅ ꯍꯧꯖꯤꯛ ꯐꯥꯎꯕ ꯂꯤꯒ ꯃꯥꯏ ꯄꯥꯛꯄ ꯉꯝ
--------------------------------------------------

Translating:  26%|██████▉                    | 259/1000 [03:43<10:19,  1.20it/s]

[259/1000]
EN: Wayne Rooney said Arsenal looked mentally stronger in the Premier League title race.
MNI_MTEI: ꯋꯩꯅ ꯔꯨꯅꯤꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤꯃꯤꯌꯔ ꯂꯤꯒ ꯇꯥꯏꯇꯦꯜ ꯔꯦꯁꯇꯥ ꯑꯥꯔꯁꯅꯦꯜꯅꯥ ꯋꯥꯈꯜꯒꯤ ꯑꯣꯏꯅ ꯍꯦꯟꯅ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  26%|███████                    | 260/1000 [03:44<10:05,  1.22it/s]

[260/1000]
EN: Rooney noted Arsenal last won the Premier League title in the 2003–04 season.
MNI_MTEI: ꯔꯨꯅꯤꯅ ꯑꯔꯁꯦꯟꯜꯅꯥ ꯑꯔꯣꯏꯕ ꯑꯣꯏꯅ 2003/04 ꯁꯤꯖꯟꯗꯥꯃꯤꯌꯔ ꯂꯤꯒꯀꯤ ꯇꯥꯏꯇꯜ ꯐꯪꯈꯤ ꯍꯥꯏꯅ ꯈꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  26%|███████                    | 261/1000 [03:44<10:07,  1.22it/s]

[261/1000]
EN: Rooney said Arsenal led Manchester City by six points with 13 games remaining.
MNI_MTEI: ꯔꯨꯅꯤꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯑꯔꯁꯦꯟꯜꯅꯥ ꯃꯥꯟꯆꯦꯁꯇꯔ ꯁꯤꯇꯤꯕꯨ ꯄꯣꯏꯟꯇ ꯇꯔꯨꯛꯇꯥ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯈꯤ ꯑꯗꯨꯒ ꯒꯦꯝ 13 ꯂꯩ
--------------------------------------------------

Translating:  26%|███████                    | 262/1000 [03:45<10:03,  1.22it/s]

[262/1000]
EN: Cristiano Ronaldo missed a second straight Saudi Pro League match for Al-Nassr.
MNI_MTEI: ꯀꯇꯤꯌꯥꯅꯣ ꯔꯣꯅꯥꯂꯣꯅꯥ ꯑꯜ-ꯅꯥꯁꯔꯒꯤꯗꯃꯛ ꯑꯅꯤ ꯁꯨꯕꯥ ꯁꯎꯗꯤ ꯂꯤꯒ ꯃꯦꯆ ꯑꯃ ꯃꯥꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  26%|███████                    | 263/1000 [03:46<10:35,  1.16it/s]

[263/1000]
EN: Al-Nassr beat Al-Ittihad 2–0 despite Cristiano Ronaldo’s continued absence.
MNI_MTEI: ꯀꯇꯤꯌꯥꯅꯣ ꯔꯣꯅꯥꯂꯣꯅꯥ ꯃꯈꯥ ꯇꯥꯅ ꯌꯥꯎꯗꯕꯥꯁꯨ ꯑꯜ-ꯅꯥꯁꯔꯅꯥ ꯑꯂ-ꯏꯇꯤꯍꯥꯗ 2. ꯗ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  26%|███████▏                   | 264/1000 [03:47<11:06,  1.10it/s]

[264/1000]
EN: Sadio Mané and Angelo Gabriel scored for Al-Nassr in the win over Al-Ittihad.
MNI_MTEI: ꯁꯥꯗꯤꯌꯣ ꯃꯥꯅꯦ ꯑꯃꯁꯨꯡ ꯑꯦꯟꯖꯦꯂꯣ ꯒꯕꯦꯔꯤꯌꯦꯜꯅꯥ ꯑꯜ-ꯏꯇꯤꯍꯥꯗꯄꯨ ꯃꯥꯏꯊꯤꯕꯥ ꯄꯤꯔꯗꯨꯅꯥ ꯑꯂ-ꯅꯥꯁꯔꯒꯤꯗꯃꯛ ꯒꯣꯜ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  26%|███████▏                   | 265/1000 [03:48<10:24,  1.18it/s]

[265/1000]
EN: Sumit Nagal headlined the Delhi Open 2026 at the DLTA Complex.
MNI_MTEI: ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯅꯥ ꯗꯤ ꯑꯦꯜ ꯇꯤ ꯑꯦ ꯀꯝꯄꯂꯦꯛꯁꯗꯥ ꯗꯤꯜꯂꯤ ꯑꯣꯄꯟ 2026 ꯗꯥ ꯂꯨꯆꯤꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  27%|███████▏                   | 266/1000 [03:49<09:36,  1.27it/s]

[266/1000]
EN: The Delhi Open 2026 tournament was scheduled for February 16 to 22.
MNI_MTEI: ꯗꯤꯜꯂꯤ ꯑꯣꯄꯟ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯑꯁꯤ ꯐꯦꯕꯋꯥꯔꯤ ꯗꯒꯤ ꯐꯥꯎꯕ ꯄꯥꯡꯊꯣꯛꯀꯅꯤ ꯍꯥꯏꯅ ꯂꯦꯞ
--------------------------------------------------

Translating:  27%|███████▏                   | 267/1000 [03:49<09:40,  1.26it/s]

[267/1000]
EN: Britain’s Jay Clarke was named as a leading overseas entrant for Delhi Open 2026.
MNI_MTEI: ꯕꯇꯦꯟꯒꯤ ꯖꯦ ꯀꯂꯔꯀ ꯑꯁꯤ ꯗꯤꯜꯂꯤ ꯑꯣꯄꯟ 2026 ꯒꯤꯗꯃꯛ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯇ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯕꯥ ꯃꯤꯑꯣꯏ ꯑꯃ ꯑꯣꯏꯅ ꯈꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  27%|███████▏                   | 268/1000 [03:50<09:19,  1.31it/s]

[268/1000]
EN: The Delhi Open note said Sumit Nagal gained direct entry into the main draw.
MNI_MTEI: ꯗꯤꯜꯂꯤ ꯑꯣꯄꯟ ꯅꯣꯠꯇꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯅꯥ ꯃꯦꯟ ꯗꯗꯥ ꯍꯛꯊꯦꯡꯅꯅ ꯆꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  27%|███████▎                   | 269/1000 [03:51<09:46,  1.25it/s]

[269/1000]
EN: India beat the Netherlands 3–2 in Davis Cup competition to move closer.
MNI_MTEI: ꯗꯦꯚꯤꯁ ꯀꯄ ꯀꯝꯄꯤꯇꯤꯁꯟꯗꯥ ꯚꯥꯔꯠꯅ ꯅꯦꯗꯔꯂꯦꯟꯗꯁꯄꯨ 3. ꯗ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯗꯨꯅ ꯍꯦꯟꯅ ꯅꯛꯅꯕ ꯈꯣꯡꯊꯥꯡꯗ ꯆꯪꯁꯤꯜꯂꯛ
--------------------------------------------------

Translating:  27%|███████▎                   | 270/1000 [03:52<09:49,  1.24it/s]

[270/1000]
EN: Dhakshineswar Suresh featured prominently during India’s Davis Cup tie against the Netherlands.
MNI_MTEI: ꯅꯦꯗꯔꯂꯦꯟ ꯭ ꯁꯀ ꯃꯥꯏꯊꯤꯕꯥ ꯚꯥꯔꯠꯀꯤ ꯗꯦꯚꯤꯁ ꯀꯄ ꯇꯥꯏꯗꯥ ꯙꯛꯁꯤꯅꯦꯁ ꯁꯨꯔꯦꯁꯅ ꯃꯁꯛ ꯊꯣꯛꯄ ꯁꯛꯇꯝ ꯂꯥꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  27%|███████▎                   | 271/1000 [03:53<09:36,  1.26it/s]

[271/1000]
EN: India’s doubles pair beat David Pel and Sander Arends in a tight five-setter.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯗꯕꯜꯁ ꯖꯌꯨꯔꯅꯥ ꯗꯦꯚꯤꯗ ꯄꯦꯂ ꯑꯃꯁꯨꯡ ꯁꯦꯟꯗꯔ ꯑꯦꯔꯦꯟꯗꯦꯁꯄꯨ ꯁꯦꯠ ꯃꯉꯥꯗꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  27%|███████▎                   | 272/1000 [03:53<09:27,  1.28it/s]

[272/1000]
EN: The doubles win was described as India’s first in five playoff ties versus Europeans.
MNI_MTEI: ꯗꯕꯜꯁ ꯃꯥꯏ ꯄꯥꯛꯄꯥ ꯑꯁꯤ ꯌꯨꯔꯣꯄꯤꯌꯟꯁꯤꯡꯒ ꯊꯦꯡꯅꯕꯂꯣꯐ ꯇꯥꯏ ꯃꯉꯥꯗꯥ ꯚꯥꯔꯠꯀꯤ ꯑꯍꯥꯟꯕꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  27%|███████▎                   | 273/1000 [03:54<09:26,  1.28it/s]

[273/1000]
EN: The same report said Sumit Nagal failed to seal the tie in reverse singles.
MNI_MTEI: ꯍꯥꯏꯔꯤꯕ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯃꯛꯇꯗꯥ ꯁꯨꯃꯤꯇ ꯅꯥꯒꯜꯅꯥ ꯔꯤꯕꯔꯁ ꯁꯤꯡꯒꯜꯁꯗꯥ ꯇꯥꯏ ꯑꯗꯨ ꯁꯤꯜ ꯇꯧꯕ ꯉꯝꯈꯤꯗꯦ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  27%|███████▍                   | 274/1000 [03:55<09:15,  1.31it/s]

[274/1000]
EN: Novak Djokovic said he still wanted to represent Serbia in Davis Cup.
MNI_MTEI: ꯅꯣꯚꯥꯀ ꯖꯣꯀꯣꯚꯤꯀꯅꯥ ꯃꯍꯥꯛꯅ ꯍꯧꯖꯤꯛꯁꯨ ꯗꯦꯚꯤꯁ ꯀꯞꯇ ꯁꯦꯔꯕꯌꯥꯒꯤ ꯃꯤꯍꯨꯠ ꯑꯣꯏꯅꯕ ꯄꯥꯝꯃꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▍                   | 275/1000 [03:56<09:44,  1.24it/s]

[275/1000]
EN: Serbia captain Viktor Troicki described Novak Djokovic as a major team figure.
MNI_MTEI: ꯁꯦꯔꯕꯌꯥꯒꯤ ꯀꯦꯞꯇꯦꯟ ꯚꯤꯛꯇꯣꯔ ꯇꯣꯏꯀꯤꯅꯥ ꯅꯣꯕꯥꯛ ꯖꯣꯀꯣꯚꯤꯀ ꯑꯁꯤ ꯑꯆꯧꯕ ꯇꯤꯝꯒꯤ ꯃꯤꯑꯣꯏ ꯑꯃꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▍                   | 276/1000 [03:57<10:10,  1.19it/s]

[276/1000]
EN: Novak Djokovic withdrew from a 2025 Davis Cup qualifier due to a hamstring injury.
MNI_MTEI: ꯅꯣꯕꯥꯛ ꯖꯣꯀꯣꯚꯤꯀꯅꯥ ꯍꯦꯝꯁꯇꯤꯡꯗ ꯁꯣꯛꯄꯥ ꯃꯔꯝꯗꯥ ꯏꯪ 2025 ꯗꯥ ꯗꯦꯚꯤꯁ ꯀꯄꯋꯥꯂꯤꯐꯌꯔꯗꯒꯤ ꯂꯧꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▍                   | 277/1000 [03:58<10:47,  1.12it/s]

[277/1000]
EN: Carlos Alcaraz beat Alexander Zverev in a five-hour, 27-minute Australian Open semifinal.
MNI_MTEI: ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯑꯂꯦꯛꯖꯦꯟꯗꯔ ꯖꯚꯦꯔꯦꯚꯄꯨ ꯄꯨꯡ ꯃꯉꯥꯒꯤ ꯃꯤꯅꯤꯇ 27ꯀꯤ ꯑꯣꯁꯇꯂꯤꯌꯟ ꯑꯣꯄꯟ ꯁꯦꯃꯤꯐꯥꯏꯅꯦꯜꯗꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▌                   | 278/1000 [03:58<10:39,  1.13it/s]

[278/1000]
EN: Carlos Alcaraz won the Australian Open final after facing Novak Djokovic.
MNI_MTEI: ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯑꯣꯁꯇꯂꯤꯌꯥ ꯑꯣꯄꯟ ꯐꯥꯏꯅꯦꯜ ꯑꯗꯨ ꯅꯣꯚꯥꯀ ꯖꯣꯀꯣꯚꯤꯀꯒꯥ ꯃꯥꯌꯣꯛꯅꯔꯒ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▌                   | 279/1000 [03:59<10:18,  1.17it/s]

[279/1000]
EN: Jannik Sinner was described as holding five straight wins over Novak Djokovic.
MNI_MTEI: ꯖꯅꯤꯛ ꯁꯤꯟꯅꯔ ꯑꯁꯤ ꯅꯣꯕꯥꯛ ꯖꯣꯀꯣꯚꯤꯀꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯂꯦꯞꯇꯅ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯃꯉꯥ ꯐꯪ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▌                   | 280/1000 [04:00<10:52,  1.10it/s]

[280/1000]
EN: The Djokovic–Sinner preview said Djokovic reached semifinals aided by a walkover and retirement.
MNI_MTEI: ꯖꯣꯀꯣꯚꯤꯛ ꯁꯤꯟꯅꯔꯚꯨꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯖꯀꯣꯚꯤꯀꯅ ꯋꯥꯀꯣꯚꯔ ꯑꯃꯁꯨꯡ ꯔꯤꯑꯥꯏꯇꯔꯃꯦꯟꯠ ꯑꯃꯒꯤ ꯃꯇꯦꯡꯅꯥ ꯁꯦꯃꯤꯐꯥꯏꯅꯦꯜꯗ ꯌꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▌                   | 281/1000 [04:01<10:41,  1.12it/s]

[281/1000]
EN: An Australian Open report said extreme heat forced temporary suspensions on outside courts.
MNI_MTEI: ꯑꯣꯁꯇꯂꯤꯌꯥꯟ ꯑꯣꯄꯟ ꯔꯤꯄꯣꯔꯇ ꯑꯃꯅ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯌꯥꯝꯅ ꯁꯥꯊꯤꯕ ꯑꯁꯥꯕꯅ ꯀꯣꯔꯠꯁꯤꯡꯒꯤ ꯃꯄꯥꯟꯗꯥ ꯃꯇꯝ ꯈꯔꯒꯤ ꯑꯣꯏꯅ ꯁꯁꯄꯦꯟꯁꯟ ꯇꯧꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▌                   | 282/1000 [04:02<10:15,  1.17it/s]

[282/1000]
EN: The same report said organisers issued heat warnings for players and spectators.
MNI_MTEI: ꯍꯥꯏꯔꯤꯕ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯃꯛꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯑꯣꯔꯖꯦꯟꯁꯔꯁꯤꯡꯅꯥ ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯌꯦꯡꯂꯤꯕꯁꯤꯡꯒꯤꯗꯃꯛꯇ ꯍꯤꯇ ꯋꯥꯔꯅꯤꯡꯁꯤꯡ ꯄꯤ
--------------------------------------------------

Translating:  28%|███████▋                   | 283/1000 [04:03<10:20,  1.16it/s]

[283/1000]
EN: Jannik Sinner beat Eliot Spizzirri 4–6, 6–3, 6–4, 6–4 in Melbourne.
MNI_MTEI: ꯖꯅꯤꯛ ꯁꯤꯟꯅꯔꯅ ꯏꯂꯤꯑꯣꯇꯄꯤꯖꯤꯔꯤꯕꯨ ꯃꯦꯜꯕꯣꯔꯟꯗ 4,6,6,3,6,4/6 ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▋                   | 284/1000 [04:04<10:52,  1.10it/s]

[284/1000]
EN: A tennis feature said Fangran Tian was coached by Chennai’s Mangal Sriram since age 12.
MNI_MTEI: ꯇꯦꯅꯤꯁ ꯐꯤꯆꯔ ꯑꯃꯥꯅꯥ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯐꯥꯡꯒꯔꯥꯅ ꯇꯤꯌꯥꯅ ꯑꯁꯤ ꯆꯍꯤꯗꯒꯤ ꯆꯦꯟꯅꯥꯏꯒꯤ ꯃꯡꯒꯜ ꯁꯔꯤꯔꯥꯃꯅ ꯀꯣꯆ ꯇꯧꯔꯝꯃꯤ ꯫
--------------------------------------------------

Translating:  28%|███████▋                   | 285/1000 [04:05<10:45,  1.11it/s]

[285/1000]
EN: Badminton World Federation demoted Syed Modi International from Super 300 to Super 100.
MNI_MTEI: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯋꯥꯔ ꯐꯦꯗꯔꯦꯁꯟꯅꯥ ꯁꯥꯏꯗ ꯃꯣꯗꯤ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜꯕꯨ ꯁꯨꯄꯔꯗꯒꯤ ꯁꯨꯄꯔꯗꯥ ꯍꯟꯊꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  29%|███████▋                   | 286/1000 [04:06<10:32,  1.13it/s]

[286/1000]
EN: The same report said India Open retained Super 750 status for the 2027–2030 cycle.
MNI_MTEI: ꯏꯪꯁꯣꯛ 20272030 ꯒꯤꯗꯃꯛ ꯏꯟꯗꯤꯌꯥ ꯑꯣꯄꯟꯅꯥ ꯁꯨꯄꯔ ꯁꯇꯥꯇꯁ ꯊꯝꯃꯤ ꯍꯥꯏꯅ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯃꯛꯅꯥ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  29%|███████▋                   | 287/1000 [04:07<10:46,  1.10it/s]

[287/1000]
EN: A badminton reforms report said World Championships and five Super 1000s will run 11 days.
MNI_MTEI: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯔꯤꯐꯣꯔꯃ ꯔꯤꯄꯣꯔꯇꯥ ꯋꯜꯗ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯞ ꯑꯃꯁꯨꯡ ꯁꯨꯄꯔ 1000 ꯃꯉꯥꯅꯥ ꯅꯨꯃꯤꯠ 11ꯅꯤ ꯆꯂꯥꯏꯒꯅꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  29%|███████▊                   | 288/1000 [04:08<11:22,  1.04it/s]

[288/1000]
EN: The Indian Express said BWF’s AGM 2026 would vote on a 3×15 scoring format.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟ ꯑꯦꯛꯁꯄꯦꯁꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯕꯤ.ꯎ.ꯑꯦꯐ.ꯒꯤ ꯑꯦ.ꯖꯤ.ꯑꯦꯝ. 2026ꯅꯥ 3. ꯁꯀꯣꯔꯤꯡ ꯐꯣꯔꯃꯦꯇ ꯑꯃꯗ ꯚꯣꯠ ꯄꯤꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  29%|███████▊                   | 289/1000 [04:08<10:51,  1.09it/s]

[289/1000]
EN: A Badminton Asia Team report said India lost 3–2 to Japan in men’s ties.
MNI_MTEI: ꯕꯦꯗꯃꯤꯟꯇꯟ ꯑꯦꯁꯤꯌꯥ ꯇꯤꯝꯒꯤ ꯔꯤꯄꯣꯔꯇꯥ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯅꯨꯄꯥꯒꯤ ꯇꯥꯏꯗꯥ ꯚꯥꯔꯠꯅ ꯖꯄꯥꯟꯗꯥ 3. ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  29%|███████▊                   | 290/1000 [04:09<10:06,  1.17it/s]

[290/1000]
EN: The same report said India lost to Thailand in women’s ties at the team event.
MNI_MTEI: ꯇꯤꯝ ꯏꯚꯦꯟꯇ ꯑꯁꯤꯗ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯇꯥꯏꯗꯥ ꯚꯥꯔꯠꯅ ꯊꯥꯏꯂꯦꯟꯗꯇꯥ ꯃꯥꯏꯊꯤꯈꯤ ꯍꯥꯏꯅ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯃꯛꯅꯥ ꯍꯥꯏ
--------------------------------------------------

Translating:  29%|███████▊                   | 291/1000 [04:10<10:12,  1.16it/s]

[291/1000]
EN: A selection report said Tanvi Sharma would play first singles after Unnati Hooda was out.
MNI_MTEI: ꯁꯦꯂꯦꯀꯁꯟ ꯔꯤꯄꯣꯔꯇ ꯑꯃꯗ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯎꯟꯅꯥꯇꯤ ꯍꯨꯗꯥ ꯑꯥꯎꯠ ꯇꯧꯔꯕꯥ ꯃꯇꯨꯡꯗ ꯇꯥꯟꯚꯤ ꯁꯔꯃꯥꯅꯥ ꯑꯍꯥꯟꯕ ꯁꯤꯡꯒꯜꯁ ꯁꯥꯟꯅꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  29%|███████▉                   | 292/1000 [04:11<10:16,  1.15it/s]

[292/1000]
EN: An India Open report said “nest materials” halted a women’s doubles semifinal in Delhi.
MNI_MTEI: ꯏꯟꯗꯤꯌꯥ ꯑꯣꯄꯟ ꯔꯤꯄꯣꯔꯇꯥ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯅꯦ ꯃꯦꯇꯦꯜꯅꯥ ꯗꯤꯜꯂꯤꯗꯥ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯗꯕꯜꯁ ꯁꯦꯃꯤꯐꯥꯏꯅꯦꯜ ꯑꯃ ꯊꯤꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  29%|███████▉                   | 293/1000 [04:12<10:07,  1.16it/s]

[293/1000]
EN: A feature said An Se-young won 94.8 percent of her matches in 2025.
MNI_MTEI: ꯏꯪ 2025 ꯗꯥ ꯑꯦꯟ ꯁꯦ-ꯌꯨꯡꯅꯥ ꯃꯍꯥꯛꯀꯤ ꯃꯦꯆꯁꯤꯡꯒꯤ ꯆꯥꯗ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯍꯥꯏꯅ ꯐꯤꯆꯔ ꯑꯃꯅ ꯍꯥꯏ
--------------------------------------------------

Translating:  29%|███████▉                   | 294/1000 [04:13<09:50,  1.20it/s]

[294/1000]
EN: The same feature said An Se-young began 2026 with two titles in two weeks.
MNI_MTEI: ꯆꯞ ꯃꯥꯟꯅꯕ ꯐꯤꯆꯔ ꯑꯁꯤꯅ ꯍꯥꯏꯔꯝꯃꯤ ꯃꯗꯨꯗꯤ ꯑꯦꯟ ꯁꯦ-ꯌꯨꯡ ꯑꯁꯤ ꯆꯌꯣꯜ ꯑꯅꯤꯒꯤ ꯃꯅꯨꯡꯗ ꯇꯥꯏꯇꯦꯜ ꯑꯅꯤꯒ ꯂꯣꯏꯅꯅꯥ ꯏꯪ 2026ꯗꯥ ꯍꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|███████▉                   | 295/1000 [04:13<09:36,  1.22it/s]

[295/1000]
EN: Lin Chun-yi beat Jonatan Christie 21–10, 21–18 in the India Open final.
MNI_MTEI: ꯏꯟꯗꯤꯌꯥ ꯑꯣꯄꯟ ꯐꯥꯏꯅꯦꯜꯗꯥ ꯂꯤꯅ ꯆꯨꯅ-ꯌꯤꯅꯥ ꯖꯣꯅꯥꯇꯟꯇꯤꯕꯨ 21,10,21,18 ꯗꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|███████▉                   | 296/1000 [04:14<09:17,  1.26it/s]

[296/1000]
EN: Devika Sihag beat Navya Kanderi 21–10, 21–13 to win in Baku.
MNI_MTEI: ꯗꯦꯕꯤꯀꯥ ꯁꯤꯍꯥꯒꯅꯥ ꯕꯥꯀꯨꯗꯥ ꯅꯥꯚꯌ ꯀꯟꯗꯦꯔꯤꯕꯨ 21,10,2113 ꯗꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯗꯨꯅ ꯃꯥꯏꯄꯥꯛ
--------------------------------------------------

Translating:  30%|████████                   | 297/1000 [04:15<09:35,  1.22it/s]

[297/1000]
EN: Radhika Sharma won her first mixed doubles title partnering Sathwik Reddy.
MNI_MTEI: ꯔꯥꯙꯤꯀꯥ ꯁꯔꯃꯥꯅꯥ ꯃꯍꯥꯛꯀꯤ ꯑꯍꯥꯟꯕꯥ ꯃꯤꯛꯁꯗ ꯗꯕꯜꯁ ꯇꯥꯏꯇꯥꯜ ꯑꯁꯤ ꯁꯥꯊꯋꯤꯀ ꯔꯦꯗꯤꯒꯥ ꯁꯔꯨꯛ ꯌꯥꯗꯨꯅ ꯐꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|████████                   | 298/1000 [04:16<10:24,  1.12it/s]

[298/1000]
EN: Ankur Bhattacharjee upset world-ranked opponent Bourrassaud 3–1 at WTT Chennai.
MNI_MTEI: ꯗꯕꯜꯌꯨꯇꯤꯇꯤ ꯆꯦꯟꯅꯥꯏꯗꯥ ꯑꯡꯀꯨꯔ ꯚꯠꯇꯥꯆꯥꯔꯖꯤꯅꯥ ꯋꯜꯗ-ꯔꯦꯟꯀꯀꯤ ꯌꯦꯛꯅꯕ ꯕꯣꯔꯔꯥꯁꯣꯗ 3/1 ꯗꯥ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|████████                   | 299/1000 [04:17<10:55,  1.07it/s]

[299/1000]
EN: FIFA president Gianni Infantino faced criticism over high-priced tickets for the 2026 World Cup.
MNI_MTEI: ꯐꯤꯐꯥꯒꯤꯁꯤꯗꯦꯟꯇ ꯖꯤꯌꯥꯅꯤ ꯏꯟꯐꯦꯟꯇꯤꯅꯣꯅꯥ ꯏꯪꯁꯣꯛ 2026 ꯒꯤ ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞꯀꯤ ꯃꯃꯜ ꯋꯥꯡꯕꯥ ꯇꯤꯀꯦꯠꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯌꯦꯠꯅꯕ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|████████                   | 300/1000 [04:18<10:43,  1.09it/s]

[300/1000]
EN: India lost 1-3 to Belgium in the FIH Pro League opener at Rourkela.
MNI_MTEI: ꯔꯧꯔꯀꯦꯂꯥꯗꯥ ꯄꯥꯡꯊꯣꯛꯂꯤꯕꯥ ꯑꯦꯐ ꯑꯥꯏ ꯑꯩꯆ ꯂꯤꯒ ꯑꯣꯄꯦꯅꯔꯗꯥ ꯚꯥꯔꯠꯅ ꯕꯦꯜꯖꯤꯌꯝꯗꯥ 1- ꯗ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|████████▏                  | 301/1000 [04:19<10:26,  1.12it/s]

[301/1000]
EN: Craig Fulton said India’s defensive structure did not deliver in the Pro League opener.
MNI_MTEI: ꯏꯒ ꯐꯜꯇꯟꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯚꯥꯔꯠꯀꯤ ꯗꯤꯐꯦꯟꯁꯤꯚꯁꯇꯆꯔꯅꯥ ꯂꯤꯒ ꯑꯣꯄꯦꯅꯔꯗꯥ ꯃꯄꯨꯡ ꯐꯥꯍꯟꯗꯦ ꯫
--------------------------------------------------

Translating:  30%|████████▏                  | 302/1000 [04:19<09:40,  1.20it/s]

[302/1000]
EN: India then suffered a 0-8 loss to Argentina in the next Pro League match.
MNI_MTEI: ꯃꯗꯨꯒꯤ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯅ ꯃꯊꯪꯒꯤ ꯂꯤꯒ ꯃꯦꯆꯇꯥ ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯗꯥ 0-8 ꯗ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|████████▏                  | 303/1000 [04:20<09:28,  1.23it/s]

[303/1000]
EN: India’s 0-8 defeat was described as a systematic demolition by Argentina.
MNI_MTEI: ꯚꯥꯔꯠꯇꯥ ꯃꯥꯏꯊꯤꯕꯥ 0-8 ꯑꯁꯤ ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯅꯥ ꯁꯤꯁꯇꯦꯃꯦꯇꯤꯛ ꯗꯤꯃꯣꯂꯦꯁꯟꯅꯤ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  30%|████████▏                  | 304/1000 [04:21<09:38,  1.20it/s]

[304/1000]
EN: India’s 0-8 loss matched the joint third-worst defeat in India’s hockey history.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯍꯣꯀꯤꯒꯤ ꯍꯤꯁꯇꯔꯤꯗꯥ ꯚꯥꯔꯠꯅ- ꯗ ꯃꯥꯏꯊꯤꯕꯥ ꯑꯁꯤ ꯄꯨꯟꯅ ꯑꯍꯨꯝꯁꯨꯕꯗꯥ ꯈ ꯭ ꯋꯥꯏꯗꯒꯤ ꯁꯥꯊꯤꯕ ꯃꯥꯏꯊꯤꯕ ꯑꯗꯨꯒ ꯃꯥꯟꯅ
--------------------------------------------------

Translating:  30%|████████▏                  | 305/1000 [04:22<10:07,  1.14it/s]

[305/1000]
EN: India’s other 0-8 losses came in 1985 versus Netherlands and 2010 versus Australia.
MNI_MTEI: ꯏꯪꯁꯣꯛ ꯗꯥ ꯅꯦꯗꯔꯂꯦꯟꯗꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯚꯥꯔꯠꯅ 0- ꯗ ꯃꯥꯏꯊꯤꯈꯤ ꯑꯃꯁꯨꯡ 2010 ꯗꯥ ꯑꯣꯁꯇꯦꯂꯤꯌꯥꯒꯤ ꯃꯥꯏꯄꯥꯛꯇꯥ ꯃꯥꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▎                  | 306/1000 [04:23<09:27,  1.22it/s]

[306/1000]
EN: Argentina’s Tomas Domene scored four goals in the 0-8 win over India.
MNI_MTEI: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯒꯤ ꯇꯣꯃꯥꯁ ꯗꯣꯃꯤꯅꯦꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ 0-8 ꯒꯤ ꯃꯥꯏꯄꯥꯛꯄꯗ ꯒꯣꯜ ꯃꯔꯤ ꯂꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▎                  | 307/1000 [04:23<09:17,  1.24it/s]

[307/1000]
EN: Tomas Domene scored at 15th, 20th, 26th and 60th minutes against India.
MNI_MTEI: ꯇꯣꯃꯥꯁ ꯗꯣꯃꯤꯅꯦꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯃꯥꯌꯣꯛꯇꯥ 15 ꯁꯨꯕ, 20ꯁꯨꯕ, 26ꯁꯨꯕ ꯑꯃꯁꯨꯡ 60ꯁꯨꯕ ꯃꯤꯅꯤꯇꯗꯥꯣꯔ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▎                  | 308/1000 [04:25<10:04,  1.14it/s]

[308/1000]
EN: Tomas Ruiz, Lucio Mendez, Ignacio Ibarra, and Nicolas della Torre also scored for Argentina.
MNI_MTEI: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯒꯤꯗꯃꯛ ꯇꯣꯃꯥꯁ ꯔꯨꯏꯖ, ꯂꯨꯁꯤꯑꯣ ꯃꯦꯟꯗꯦꯁ, ꯏꯒꯅꯥꯁꯤꯌꯣ ꯏꯕꯥꯔꯥ ꯑꯃꯁꯨꯡ ꯅꯤꯀꯣꯂꯥꯁ ꯗꯦꯂꯥ ꯇꯣꯔꯦꯅꯥꯁꯨꯣꯜ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▎                  | 309/1000 [04:25<09:25,  1.22it/s]

[309/1000]
EN: India’s third quarter without conceding a goal looked like an anomaly in the match.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯑꯍꯨꯝꯁꯨꯕ ꯀ ꯭ ꯋꯥꯇꯔꯗꯥ ꯒꯣꯜ ꯑꯃꯠꯇ ꯄꯤꯗꯕꯅꯥ ꯃꯦꯆ ꯑꯗꯨꯗ ꯑꯅꯣꯃꯂꯤ ꯑꯃ ꯑꯣꯏꯅ ꯎꯕ ꯐꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▎                  | 310/1000 [04:26<09:19,  1.23it/s]

[310/1000]
EN: Player-of-the-Match Tomas Domene said Argentina played the whole game at 100 percent.
MNI_MTEI: ꯃꯦꯆꯀꯤ ꯁꯥꯟꯅꯔꯣꯏ ꯇꯣꯃꯥꯁ ꯗꯣꯃꯤꯅꯦꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯅꯥꯅ ꯒꯦꯝ ꯄꯨꯝꯅꯃꯛ ꯆꯥꯗꯗꯥ ꯁꯥꯟꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▍                  | 311/1000 [04:27<09:23,  1.22it/s]

[311/1000]
EN: Tomas Domene said Argentina were disappointed after losing 3-5 to Belgium previously.
MNI_MTEI: ꯇꯣꯃꯥꯁ ꯗꯣꯃꯤꯅꯦꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯑꯔꯖꯦꯟꯇꯤꯅꯥ ꯑꯁꯤ ꯃꯃꯥꯡꯗ ꯕꯦꯜꯖꯤꯌꯝꯗꯥ- ꯗ ꯃꯥꯏꯊꯤꯔꯕꯥꯗꯒꯤ ꯅꯤꯡꯉꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▍                  | 312/1000 [04:27<08:44,  1.31it/s]

[312/1000]
EN: Argentina scored two quick goals at the end of the first quarter.
MNI_MTEI: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯅꯥ ꯑꯍꯥꯟꯕꯥ ꯀꯋꯥꯔꯇꯔ ꯂꯣꯏꯔꯛꯄꯗꯥꯀꯤꯛ ꯒꯣꯜ ꯑꯅꯤ ꯂꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▍                  | 313/1000 [04:28<08:03,  1.42it/s]

[313/1000]
EN: Argentina scored five goals in 10 minutes during the second quarter.
MNI_MTEI: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯅꯥ ꯑꯅꯤꯁꯨꯕ ꯀ ꯭ ꯋꯥꯇꯔꯗꯥ ꯃꯤꯅꯤꯇꯗꯥ ꯒꯣꯜ ꯃꯉꯥ ꯂꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  31%|████████▍                  | 314/1000 [04:29<08:19,  1.37it/s]

[314/1000]
EN: Harmanpreet Singh missed two penalty strokes in the match against Argentina.
MNI_MTEI: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯃꯦꯆ ꯑꯗꯨꯗ ꯍꯔꯃꯟꯄꯤꯇ ꯁꯤꯡꯍꯅꯥ ꯄꯦꯅꯥꯜꯇꯤ ꯁꯣꯛ ꯑꯅꯤ ꯃꯥꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▌                  | 315/1000 [04:30<08:12,  1.39it/s]

[315/1000]
EN: India missed three penalty corners during the 0-8 defeat against Argentina.
MNI_MTEI: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ 0-8 ꯗꯥ ꯃꯥꯏꯊꯤꯕꯥ ꯃꯇꯝꯗ ꯚꯥꯔꯠꯅ ꯄꯦꯅꯥꯜꯇꯤ ꯀꯣꯔꯅꯔ ꯑꯍꯨꯝ ꯃꯥꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▌                  | 316/1000 [04:30<07:58,  1.43it/s]

[316/1000]
EN: India goalkeepers Suraj Karkera and Pawan looked completely out of place.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯒꯣꯜꯀꯤꯄꯔ ꯁꯨꯔꯖ ꯀꯥꯔꯀꯦꯔꯥ ꯑꯃꯁꯨꯡ ꯄꯋꯅ ꯑꯁꯤ ꯃꯄꯨꯡꯐꯥꯅꯥ ꯂꯝꯕꯥ ꯉꯝ
--------------------------------------------------

Translating:  32%|████████▌                  | 317/1000 [04:31<08:04,  1.41it/s]

[317/1000]
EN: Argentina dominated possession and toyed with India’s midfield and defence.
MNI_MTEI: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯅꯥ ꯄꯣꯖꯦꯁꯟꯗ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯈꯤ ꯑꯃꯁꯨꯡ ꯚꯥꯔꯠꯀꯤ ꯃꯤꯗꯐꯤꯜꯗ ꯑꯃꯁꯨꯡ ꯗꯤꯐꯦꯟꯁꯒꯥ ꯁꯥꯟꯅ
--------------------------------------------------

Translating:  32%|████████▌                  | 318/1000 [04:32<08:03,  1.41it/s]

[318/1000]
EN: Argentina’s win catapulted them to fourth in the nine-team standings.
MNI_MTEI: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯒꯤ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯑꯁꯤꯅ ꯃꯈꯣꯏꯕꯨ ꯇꯤꯝ ꯃꯥꯄꯟꯒꯤꯟꯗꯤꯡꯗꯥ ꯃꯔꯤ ꯁꯨꯕꯥ ꯃꯐꯝꯗ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▌                  | 319/1000 [04:32<08:29,  1.34it/s]

[319/1000]
EN: India next faced world No.2 Belgium again after the heavy Argentina loss.
MNI_MTEI: ꯑꯔꯖꯦꯟꯇꯤꯅꯥꯗꯥ ꯑꯆꯧꯕ ꯃꯥꯏꯊꯤꯕꯥ ꯐꯪꯂꯕ ꯃꯇꯨꯡꯗ ꯚꯥꯔꯠꯅ ꯃꯊꯪꯗꯥ ꯃꯥꯂꯦꯝꯒꯤ ꯅꯝꯕꯔ 2ꯒꯤ ꯕꯦꯜꯖꯤꯌꯝꯒꯥ ꯑꯃꯨꯛ ꯍꯟꯅ ꯃꯥꯌꯣꯛꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▋                  | 320/1000 [04:33<09:18,  1.22it/s]

[320/1000]
EN: Macklin Celebrini scored early to spark Canada’s 5-0 win over Czech Republic.
MNI_MTEI: ꯃꯦꯀꯂꯤꯟ ꯁꯦꯂꯦꯕꯅꯤꯅꯥ ꯑꯍꯥꯟꯕꯥ ꯃꯇꯝꯗ ꯒꯣꯜ ꯇꯧꯗꯨꯅ ꯀꯅꯥꯗꯥꯒꯤ ꯆꯦꯛ ꯔꯤꯄꯕꯂꯤꯛꯀꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ- ꯗ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▋                  | 321/1000 [04:34<09:16,  1.22it/s]

[321/1000]
EN: Macklin Celebrini scored with just over five seconds left in the first period.
MNI_MTEI: ꯃꯦꯀꯂꯤꯟ ꯁꯦꯂꯦꯕꯅꯤꯅꯥ ꯑꯍꯥꯟꯕꯥ ꯄꯦꯔꯤꯑꯣꯗꯗꯥ ꯁꯦꯀꯦꯟꯗ ꯃꯉꯥꯗꯒꯤ ꯈꯔ ꯍꯦꯟꯅ ꯂꯩꯔꯒꯣꯔ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▋                  | 322/1000 [04:35<09:46,  1.16it/s]

[322/1000]
EN: Mark Stone, Bo Horvat, Nathan MacKinnon and Nick Suzuki scored in Canada’s opener.
MNI_MTEI: ꯃꯥꯔꯛꯣꯟ, ꯕꯣ ꯍꯣꯔꯚꯇ, ꯅꯥꯊꯥꯟ ꯃꯦꯛꯀꯤꯅꯣꯟ ꯑꯃꯁꯨꯡ ꯅꯤꯛ ꯁꯨꯖꯨꯀꯤꯅꯥ ꯀꯅꯥꯗꯥꯒꯤ ꯑꯣꯄꯦꯅꯔꯗꯥ ꯒꯣꯜ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▋                  | 323/1000 [04:36<09:19,  1.21it/s]

[323/1000]
EN: Connor McDavid recorded three assists in Canada’s 5-0 Olympic win.
MNI_MTEI: ꯀꯣꯅꯣꯔ ꯃꯛꯗꯥꯚꯤꯗꯅ ꯀꯅꯥꯗꯥꯒꯤ- ꯑꯣꯂꯤꯝꯄꯤꯛ ꯃꯥꯏ ꯄꯥꯛꯄꯗ ꯑꯦꯁꯤꯇ ꯑꯍꯨꯝ ꯔꯦꯀꯣꯔꯗ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  32%|████████▋                  | 324/1000 [04:37<09:25,  1.19it/s]

[324/1000]
EN: Sidney Crosby said Celebrini’s first Olympic goal was huge to get Canada going.
MNI_MTEI: ꯁꯤꯗꯅꯤ ꯀꯁꯕꯤꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯁꯦꯂꯦꯕꯅꯤꯒꯤ ꯑꯍꯥꯟꯕꯥ ꯑꯣꯂꯤꯝꯄꯤꯛ ꯒꯣꯜ ꯑꯁꯤꯅ ꯀꯅꯥꯗꯥꯕꯨ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯍꯟꯕꯥ
--------------------------------------------------

Translating:  32%|████████▊                  | 325/1000 [04:38<09:11,  1.22it/s]

[325/1000]
EN: Jon Cooper said Macklin Celebrini plays the game well beyond his years.
MNI_MTEI: ꯖꯣꯟ ꯀꯨꯄꯔꯅꯥ ꯍꯥꯏꯔꯝꯃꯤ ꯃꯗꯨꯗꯤ ꯃꯦꯀꯂꯤꯟ ꯁꯦꯂꯦꯕꯅꯤꯅꯥ ꯃꯍꯥꯛꯀꯤ ꯆꯍꯤ ꯀꯌꯥꯒꯤ ꯃꯊꯛꯇꯁꯨ ꯒꯦꯝ ꯑꯗꯨ ꯐꯖꯅ ꯁꯥꯟꯅꯩ ꯫
--------------------------------------------------

Translating:  33%|████████▊                  | 326/1000 [04:38<08:44,  1.28it/s]

[326/1000]
EN: Canada planned to face Switzerland at the Milano Arena the next day.
MNI_MTEI: ꯀꯅꯥꯗꯥꯅꯥ ꯃꯊꯪꯒꯤ ꯅꯨꯃꯤꯠꯇ ꯃꯤꯂꯥꯅꯣ ꯑꯦꯔꯤꯅꯥꯗꯥꯏꯠꯖꯔꯂꯦꯟꯗꯀ ꯃꯥꯌꯣꯛꯅꯅꯕ ꯊꯧꯔꯥꯡ ꯇꯧ
--------------------------------------------------

Translating:  33%|████████▊                  | 327/1000 [04:39<09:27,  1.19it/s]

[327/1000]
EN: Choi Ga-on won women’s snowboard halfpipe gold after recovering from a first-run crash.
MNI_MTEI: ꯆꯣꯏ ꯒꯥ-ꯣꯟꯅꯥ ꯅꯨꯄꯤꯁꯤꯡꯒꯤꯣꯟꯕꯣꯔ ꯭ ꯗ ꯍꯥꯐꯄꯄꯤꯄ ꯒꯣꯜꯗ ꯑꯁꯤ ꯐꯔꯁꯠ-ꯔꯟ ꯀꯁ ꯑꯃꯗꯒꯤ ꯐꯒꯠꯂꯛꯄꯒꯤ ꯃꯇꯨꯡꯗ ꯃꯥꯏꯄꯥꯛ
--------------------------------------------------

Translating:  33%|████████▊                  | 328/1000 [04:40<09:03,  1.24it/s]

[328/1000]
EN: Chloe Kim took silver and Mitsuki Ono won bronze in the halfpipe event.
MNI_MTEI: ꯍꯥꯐꯄꯤꯄ ꯏꯚꯦꯟꯇꯗꯥꯂꯣ ꯀꯤꯝꯅ ꯂꯨꯄꯥ ꯑꯃꯁꯨꯡ ꯃꯤꯠꯁꯨꯀꯤ ꯑꯣꯅꯣꯅꯥꯣꯟꯖ ꯂꯧ
--------------------------------------------------

Translating:  33%|████████▉                  | 329/1000 [04:41<09:05,  1.23it/s]

[329/1000]
EN: Choi Ga-on scored 90.25 to beat Chloe Kim’s leading 88 score.
MNI_MTEI: ꯆꯣꯏ ꯒꯥ-ꯣꯟꯅꯥ 25 ꯁꯀꯣꯔ ꯂꯧꯗꯨꯅ ꯆꯣꯂꯤ ꯀꯤꯝꯒꯤ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯔꯤꯕ 88ꯕꯨ ꯃꯥꯏꯊꯤꯕ ꯄꯤ
--------------------------------------------------

Translating:  33%|████████▉                  | 330/1000 [04:42<08:55,  1.25it/s]

[330/1000]
EN: Arsenal reached the League Cup final after Kai Havertz secured a 1-0 win.
MNI_MTEI: ꯀꯥꯏ ꯍꯥꯚꯔꯇꯖꯅ 1- ꯒꯤ ꯃꯥꯏꯄꯥꯛꯄ ꯑꯃ ꯐꯪꯂꯕ ꯃꯇꯨꯡꯗ ꯑꯥꯔꯁꯅꯦꯜꯅꯥ ꯂꯤꯒ ꯀꯞꯀꯤ ꯐꯥꯏꯅꯦꯜꯗ ꯌꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  33%|████████▉                  | 331/1000 [04:43<09:25,  1.18it/s]

[331/1000]
EN: Kai Havertz came off the bench to finish Arsenal’s 4-2 aggregate semi-final victory.
MNI_MTEI: ꯀꯥꯏ ꯍꯥꯚꯔꯇꯖꯅ ꯑꯥꯔꯁꯦꯅꯦꯜꯒꯤ- ꯒꯤ ꯑꯄꯨꯟꯕ ꯁꯦꯃꯤ-ꯐꯥꯏꯅꯦꯜ ꯃꯥꯏ ꯄꯥꯛꯄ ꯑꯗꯨ ꯂꯣꯏꯁꯤꯟꯅꯕ ꯕꯦꯆꯇꯒꯤ ꯂꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  33%|████████▉                  | 332/1000 [04:43<09:32,  1.17it/s]

[332/1000]
EN: Arsenal will face Manchester City or Newcastle at Wembley on March 22.
MNI_MTEI: ꯃꯥꯔꯗꯥ ꯋꯦꯝꯕꯦꯂꯤꯗꯥ ꯑꯔꯁꯦꯟꯜꯅꯥ ꯃꯥꯟꯆꯦꯁꯇꯔ ꯁꯤꯇꯤ ꯅꯠꯇꯒꯥ ꯅꯀꯁꯦꯜꯒꯥ ꯃꯥꯌꯣꯛꯅꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  33%|████████▉                  | 333/1000 [04:44<09:07,  1.22it/s]

[333/1000]
EN: Manchester City held a 2-0 lead over Newcastle ahead of the second leg.
MNI_MTEI: ꯃꯥꯟꯆꯦꯁꯇꯔ ꯁꯤꯇꯤꯅꯥ ꯑꯅꯤꯁꯨꯕ ꯂꯦꯒꯀꯤ ꯃꯃꯥꯡꯗ ꯅꯀꯁꯦꯜꯒꯤ ꯃꯊꯛꯇ- ꯒꯤ ꯂꯨꯆꯤꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  33%|█████████                  | 334/1000 [04:45<08:26,  1.31it/s]

[334/1000]
EN: Arsenal have not won the League Cup since 1993, according to the report.
MNI_MTEI: ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯏꯪ 1993ꯗꯒꯤ ꯍꯧꯅ ꯑꯥꯔꯁꯅꯦꯜꯅꯥ ꯂꯤꯒ ꯀꯞꯇ ꯃꯥꯏ ꯄꯥꯛꯄ ꯉꯝ
--------------------------------------------------

Translating:  34%|█████████                  | 335/1000 [04:46<09:34,  1.16it/s]

[335/1000]
EN: The Football Association of Ireland confirmed Ireland will fulfil Nations League fixtures against Israel.
MNI_MTEI: ꯑꯥꯌꯔꯂꯦꯟꯗꯒꯤ ꯐꯨꯇꯕꯣꯜ ꯑꯦꯁꯣꯁꯤꯑꯦꯁꯟꯅꯥ ꯑꯥꯏꯌꯔꯂꯦꯟꯗꯅꯥ ꯏꯖꯔꯥꯦꯜꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯅꯦꯁꯟꯁ ꯂꯤꯒꯀꯤ ꯐꯤꯛꯆꯔꯁꯤꯡ ꯃꯄꯨꯡ ꯐꯥꯍꯟꯒꯅꯤ ꯍꯥꯏꯅ ꯀꯟꯐꯥꯔꯝ ꯇꯧ
--------------------------------------------------

Translating:  34%|█████████                  | 336/1000 [04:47<09:15,  1.20it/s]

[336/1000]
EN: Ireland and Israel were drawn with Austria and Kosovo in Nations League League B.
MNI_MTEI: ꯑꯥꯏꯔꯂꯦꯟꯗ ꯑꯃꯁꯨꯡ ꯏꯖꯔꯥꯦꯜ ꯑꯁꯤ ꯑꯣꯁꯇꯌꯥ ꯑꯃꯁꯨꯡ ꯀꯣꯁꯣꯚꯣꯒꯥ ꯂꯣꯏꯅꯅꯥ ꯅꯦꯁꯟꯁ ꯂꯤꯒ ꯕꯤꯗꯥ ꯗ ꯇꯧ
--------------------------------------------------

Translating:  34%|█████████                  | 337/1000 [04:47<08:31,  1.29it/s]

[337/1000]
EN: Ireland must play Israel home and away between September and November.
MNI_MTEI: ꯁꯦꯞꯇꯦꯝꯕꯔ ꯑꯃꯁꯨꯡ ꯅꯕꯦꯝꯕꯔꯒꯤ ꯃꯔꯛꯇ ꯑꯥꯏꯔꯂꯦꯟꯗꯅꯥ ꯏꯖꯔꯥꯦꯜꯒ ꯌꯨꯝ ꯑꯃꯁꯨꯡ ꯃꯄꯥꯟꯗ ꯁꯥꯟꯅꯒꯗꯕꯅꯤ ꯫
--------------------------------------------------

Translating:  34%|█████████▏                 | 338/1000 [04:48<09:27,  1.17it/s]

[338/1000]
EN: The FAI warned refusal could mean forfeiture and possible disqualification under UEFA regulations.
MNI_MTEI: ꯑꯦꯐꯑꯦꯑꯥꯏꯅꯥ ꯌꯥꯗꯕꯒꯤ ꯑꯔꯊꯗꯤ ꯌꯨꯑꯏꯐꯦꯑꯦ ꯔꯦꯒꯨꯂꯦꯁꯟꯁꯤꯡꯒꯤ ꯃꯈꯥꯗ ꯂꯧꯊꯣꯛꯄ ꯑꯃꯁꯨꯡ ꯑꯣꯏꯊꯣꯛꯄ ꯌꯥꯕ ꯗꯤꯀꯂꯤꯚꯤꯐꯤꯀꯦꯁꯟ ꯍꯥꯏꯕꯅꯤ ꯍꯥꯏꯅ ꯆꯦꯛꯁꯤꯟꯋꯥ ꯄꯤ
--------------------------------------------------

Translating:  34%|█████████▏                 | 339/1000 [04:49<09:25,  1.17it/s]

[339/1000]
EN: The FAI said it requested Israel’s UEFA ban in November after an internal vote.
MNI_MTEI: ꯑꯦꯟꯇꯔꯅꯦꯜ ꯚꯣꯠ ꯑꯃꯒꯤ ꯃꯇꯨꯡꯗ ꯅꯕꯦꯝꯕꯔꯗꯥ ꯑꯦꯐꯑꯦꯑꯥꯏꯅꯥ ꯏꯖꯔꯥꯦꯜꯒꯤ ꯌꯨꯑꯐꯑꯦꯕꯨ ꯊꯤꯡꯅꯕ ꯍꯥꯏꯖꯈꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  34%|█████████▏                 | 340/1000 [04:50<10:10,  1.08it/s]

[340/1000]
EN: Novak Djokovic beat Jannik Sinner 3-6, 6-3, 4-6, 6-4, 6-4 in Melbourne.
MNI_MTEI: ꯃꯦꯜꯕꯣꯔꯟꯗ ꯅꯣꯚꯥꯀ ꯖꯣꯀꯣꯚꯤꯛꯅ ꯖꯅꯤꯛ ꯁꯤꯟꯅꯔꯕꯨ 3-6,6-, 4- 6, 6-4,-4 ꯗ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  34%|█████████▏                 | 341/1000 [04:51<10:38,  1.03it/s]

[341/1000]
EN: Novak Djokovic’s win over Jannik Sinner set up an Australian Open final against Carlos Alcaraz.
MNI_MTEI: ꯅꯣꯕꯥꯛ ꯖꯣꯀꯣꯚꯤꯀꯅ ꯖꯅꯤꯛ ꯁꯤꯟꯅꯔꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯑꯁꯤꯅ ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯒꯤ ꯃꯥꯏꯄꯥꯛꯗꯥ ꯑꯣꯁꯇꯂꯤꯌꯥ ꯑꯣꯄꯟ ꯐꯥꯏꯅꯦꯜ ꯑꯃ ꯁꯦꯝ
--------------------------------------------------

Translating:  34%|█████████▏                 | 342/1000 [04:52<10:55,  1.00it/s]

[342/1000]
EN: Novak Djokovic reached his 11th Australian Open final after ending four straight semi-final exits.
MNI_MTEI: ꯅꯣꯕꯥꯛ ꯖꯣꯀꯣꯚꯤꯀꯅ ꯁꯦꯃꯤ-ꯐꯥꯏꯅꯦꯜꯗꯒꯤ ꯃꯊꯪ-ꯃꯇꯥ ꯂꯣꯏꯁꯤꯜꯂꯛꯄꯒꯤ ꯃꯇꯨꯡꯗ ꯃꯍꯥꯛꯀꯤ 11 ꯁꯨꯕ ꯑꯣꯁꯇꯂꯤꯌꯟ ꯑꯣꯄꯟ ꯐꯥꯏꯅꯦꯜꯗ ꯌꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  34%|█████████▎                 | 343/1000 [04:53<10:33,  1.04it/s]

[343/1000]
EN: Carlos Alcaraz reached his first Melbourne Park title match, the report said.
MNI_MTEI: ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯃꯍꯥꯛꯀꯤ ꯑꯍꯥꯟꯕꯥ ꯃꯦꯜꯕꯣꯔꯟ ꯄꯥꯔꯛ ꯇꯥꯏꯇꯥꯜ ꯃꯦꯆꯇ ꯌꯧꯈꯤ ꯍꯥꯏꯅ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯗ ꯍꯥꯏ
--------------------------------------------------

Translating:  34%|█████████▎                 | 344/1000 [04:54<10:17,  1.06it/s]

[344/1000]
EN: Lorenzo Musetti retired mid-match after suffering a suspected upper leg tear.
MNI_MTEI: ꯂꯣꯔꯣꯟꯖꯣ ꯃꯨꯁꯦꯇꯤꯅ ꯑꯞꯄꯔ ꯂꯦꯒ ꯇꯤꯌꯔꯅꯤ ꯍꯥꯏꯅ ꯆꯤꯡꯅꯕꯗꯒꯤ ꯃꯦꯆꯀꯤ ꯃꯌꯥꯏꯗꯥ ꯔꯤꯇꯤꯑꯥꯔ ꯇꯧ
--------------------------------------------------

Translating:  34%|█████████▎                 | 345/1000 [04:55<09:44,  1.12it/s]

[345/1000]
EN: Lorenzo Musetti withdrew after winning the first two sets against Novak Djokovic.
MNI_MTEI: ꯂꯣꯔꯦꯟꯖꯣ ꯃꯨꯁꯦꯇꯤꯅ ꯅꯣꯚꯥꯀ ꯖꯣꯀꯣꯚꯤꯀꯒꯤ ꯃꯥꯌꯣꯛꯇꯥ ꯑꯍꯥꯟꯕ ꯁꯦꯇ ꯑꯅꯤ ꯃꯥꯏ ꯄꯥꯛꯂꯕ ꯃꯇꯨꯡꯗ ꯂꯧꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  35%|█████████▎                 | 346/1000 [04:56<09:59,  1.09it/s]

[346/1000]
EN: Alexander Zverev rallied from losing the first set to beat Gabriel Diallo in four sets.
MNI_MTEI: ꯑꯂꯦꯛꯖꯦꯟꯗꯔ ꯖꯚꯦꯔꯦꯚꯅꯥ ꯑꯍꯥꯟꯕ ꯁꯦꯇ ꯑꯗꯨ ꯃꯥꯏꯊꯤꯕꯥꯗꯒꯤ ꯔꯦꯂꯤ ꯇꯧꯔꯗꯨꯅ ꯒꯕꯦꯔꯤꯌꯦꯜ ꯗꯤꯌꯥꯂꯣꯕꯨ ꯁꯦꯠ ꯃꯔꯤꯗꯥ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  35%|█████████▎                 | 347/1000 [04:57<10:52,  1.00it/s]

[347/1000]
EN: Alexander Zverev won 6-7(1), 6-1, 6-4, 6-2 against Gabriel Diallo at Rod Laver Arena.
MNI_MTEI: ꯑꯂꯦꯛꯖꯦꯟꯗꯔ ꯖꯚꯦꯔꯦꯚꯅꯥ ꯔꯣꯗ ꯂꯦꯕꯔ ꯑꯦꯔꯤꯅꯥꯗꯥ ꯒꯕꯦꯔꯤꯌꯦꯜ ꯗꯤꯌꯥꯂꯣꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ-,./% ꯑꯃꯁꯨꯡ-2 ꯂꯧ
--------------------------------------------------

Translating:  35%|█████████▍                 | 348/1000 [04:58<10:15,  1.06it/s]

[348/1000]
EN: An Australian Open report noted fans were unhappy about long queues and a ticket sales halt.
MNI_MTEI: ꯑꯣꯁꯇꯂꯤꯌꯥꯟ ꯑꯣꯄꯟ ꯔꯤꯄꯣꯔꯇ ꯑꯃꯗ ꯐꯦꯟꯁꯤꯡꯅ ꯑꯁꯥꯡꯕ ꯄꯔꯤꯡꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯇꯤꯀꯦꯠ ꯌꯣꯟꯕ ꯂꯦꯞꯈꯤꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯅꯨꯡꯉꯥꯏꯈꯤꯗꯦ ꯍꯥꯏꯅ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  35%|█████████▍                 | 349/1000 [04:59<09:55,  1.09it/s]

[349/1000]
EN: A Hindustan Times column said tennis needs rivalries to elevate players and the sport.
MNI_MTEI: ꯍꯤꯟꯗꯨꯁꯇꯥꯟ ꯇꯥꯏꯃꯁꯀꯤ ꯀꯣꯂꯝ ꯑꯃꯗ ꯇꯦꯅꯤꯁꯅꯥ ꯁꯥꯟꯅꯔꯣꯏꯁꯤꯡ ꯑꯃꯁꯨꯡꯄꯣꯔꯇꯄꯨ ꯆꯥꯎꯈꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯌꯦꯛꯅꯕ ꯃꯊꯧ ꯇꯥꯏ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  35%|█████████▍                 | 350/1000 [05:00<09:39,  1.12it/s]

[350/1000]
EN: A Hindustan Times column said Jannik Sinner and Carlos Alcaraz are improving every year.
MNI_MTEI: ꯍꯤꯟꯗꯨꯁꯇꯥꯟ ꯇꯥꯏꯃꯁꯀꯤ ꯀꯣꯂꯝ ꯑꯃꯗ ꯖꯅꯤꯛ ꯁꯤꯟꯅꯔ ꯑꯃꯁꯨꯡ ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖ ꯑꯁꯤ ꯆꯍꯤ ꯈꯨꯗꯤꯡꯒꯤ ꯐꯒꯠꯂꯛꯂꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  35%|█████████▍                 | 351/1000 [05:00<09:12,  1.18it/s]

[351/1000]
EN: The same column said Sinner and Alcaraz already play at a level above most players.
MNI_MTEI: ꯁꯤꯟꯅꯔ ꯑꯃꯁꯨꯡ ꯑꯜꯀꯥꯔꯖ ꯑꯁꯤ ꯍꯥꯟꯅꯅꯥ ꯁꯥꯟꯅꯔꯣꯏ ꯑꯌꯥꯝꯕꯒꯤ ꯃꯊꯛꯇ ꯂꯩꯕ ꯊꯥꯛꯇꯥ ꯁꯥꯟꯅ ꯍꯥꯏꯅ ꯆꯞ ꯃꯥꯟꯅꯕ ꯀꯣꯂꯝꯗꯥ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  35%|█████████▌                 | 352/1000 [05:02<09:59,  1.08it/s]

[352/1000]
EN: The column said Federer, Nadal and Djokovic gave men’s tennis a tribal feel for two decades.
MNI_MTEI: ꯀꯣꯂꯝ ꯑꯁꯤꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯐꯦꯗꯔꯔ, ꯅꯥꯗꯥꯜ ꯑꯃꯁꯨꯡ ꯖꯣꯀꯣꯚꯤꯀꯅꯥ ꯅꯨꯄꯥꯒꯤ ꯇꯦꯅꯤꯁ ꯑꯁꯤ ꯆꯍꯤ ꯇꯔꯥꯒꯤ ꯈꯨꯖꯤꯡ ꯑꯅꯤꯗꯒꯤ ꯇꯥꯏꯕꯦꯜꯒꯤ ꯃꯒꯨꯟ ꯑꯃ ꯄꯤ
--------------------------------------------------

Translating:  35%|█████████▌                 | 353/1000 [05:02<09:57,  1.08it/s]

[353/1000]
EN: A report said Alexander Zverev began a bid for a maiden Australian Open title.
MNI_MTEI: ꯔꯤꯄꯣꯔꯇ ꯑꯃꯥꯅꯥ ꯍꯥꯏ ꯃꯗꯨꯗꯤ ꯑꯂꯦꯛꯖꯦꯟꯗꯔ ꯖꯚꯦꯔꯦꯚꯅꯥ ꯑꯍꯥꯟꯕ ꯑꯣꯁꯇꯂꯤꯌꯥ ꯑꯣꯄꯟ ꯇꯥꯏꯇꯥꯜ ꯑꯃꯥ ꯐꯪꯅꯕꯒꯤ ꯕꯤꯗ ꯑꯃ ꯍꯧ
--------------------------------------------------

Translating:  35%|█████████▌                 | 354/1000 [05:04<10:26,  1.03it/s]

[354/1000]
EN: Carlos Alcaraz defeated Alexander Zverev 6-3, 3-6, 6-1, 6-2 at the Australian Open.
MNI_MTEI: ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯑꯂꯦꯛꯖꯦꯟꯗꯔ ꯖꯚꯦꯔꯦꯚꯄꯨ ꯑꯣꯁꯇꯂꯤꯌꯥ ꯑꯣꯄꯟꯗꯥ 6-, 3 - 6,6-1, ꯗ ꯃꯥꯏꯊꯤꯕ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▌                 | 355/1000 [05:04<09:36,  1.12it/s]

[355/1000]
EN: Carlos Alcaraz won in two hours and 26 minutes, according to the match report.
MNI_MTEI: ꯃꯦꯆ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯒꯤ ꯃꯇꯨꯡ ꯏꯟꯅ ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯄꯨꯡ ꯑꯅꯤ ꯑꯃꯁꯨꯡ ꯃꯤꯅꯤꯠ 26 ꯗꯥ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▌                 | 356/1000 [05:05<09:18,  1.15it/s]

[356/1000]
EN: The same report said Zverev received a time-violation warning during the match.
MNI_MTEI: ꯆꯞ ꯃꯥꯟꯅꯕ ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯗ ꯖꯚꯦꯔꯦꯚꯅꯥ ꯃꯦꯆ ꯑꯗꯨꯒꯤ ꯃꯅꯨꯡꯗ ꯇꯥꯏꯃ-ꯚꯤꯑꯣꯂꯦꯁꯟ ꯋꯥꯔꯅꯤꯡ ꯑꯃ ꯐꯪꯈꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▋                 | 357/1000 [05:06<09:11,  1.17it/s]

[357/1000]
EN: The report said Alcaraz requested a meeting with the supervisor after the time warning.
MNI_MTEI: ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯗ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯃꯇꯝ ꯑꯗꯨꯒꯤ ꯆꯦꯛꯁꯤꯟꯋꯥ ꯄꯤꯔꯕ ꯃꯇꯨꯡꯗ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯁꯨꯚꯥꯏꯖꯔꯒꯥ ꯎꯅꯅꯕ ꯍꯥꯏꯖꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▋                 | 358/1000 [05:07<09:10,  1.17it/s]

[358/1000]
EN: The report said Alcaraz complained about the length of Zverev’s breaks between points.
MNI_MTEI: ꯔꯤꯄꯣꯔꯇ ꯑꯗꯨꯗ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯖꯚꯦꯔꯦꯚꯒꯤ ꯄꯣꯏꯟꯇꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯂꯩꯕ ꯕꯦꯛꯁꯤꯡꯒꯤ ꯑꯁꯥꯡꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯋꯥꯀꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▋                 | 359/1000 [05:07<08:43,  1.22it/s]

[359/1000]
EN: Carlos Alcaraz said he also wanted to know the limit for the time between points.
MNI_MTEI: ꯀꯥꯔꯂꯣꯁ ꯑꯜꯀꯥꯔꯖꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯃꯍꯥꯛꯅ ꯄꯣꯏꯟꯇꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯂꯩꯕ ꯃꯇꯝ ꯑꯗꯨꯒꯤ ꯂꯤꯃꯤꯇ ꯑꯗꯨꯁꯨ ꯈꯪꯕ ꯄꯥꯝꯃꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▋                 | 360/1000 [05:08<08:53,  1.20it/s]

[360/1000]
EN: R Praggnanandhaa sealed a 2026 Candidates berth by winning the FIDE Circuit 2025.
MNI_MTEI: ꯑꯥꯔꯒꯅꯅꯥꯟꯙꯥꯅꯥ ꯐꯤꯗꯦ ꯁꯔꯀꯏꯇ 2025 ꯃꯥꯏ ꯄꯥꯛꯂꯗꯨꯅ ꯀꯦꯟꯗꯤꯗꯦꯠꯁ ꯕꯦꯔꯊ 2026 ꯑꯃ ꯁꯤꯜ ꯇꯧ
--------------------------------------------------

Translating:  36%|█████████▋                 | 361/1000 [05:09<08:43,  1.22it/s]

[361/1000]
EN: The Candidates Tournament will determine the challenger to world champion D Gukesh.
MNI_MTEI: ꯀꯦꯟꯗꯤꯇꯦꯁ ꯇꯨꯔꯅꯥꯃꯦꯟꯇꯅꯥ ꯋꯜꯗ ꯆꯦꯝꯄꯌꯟ ꯗꯤ ꯒꯨꯀꯦꯁꯇꯥ ꯆꯂꯦꯟꯖꯔ ꯑꯗꯨ ꯂꯦꯞꯀꯅꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▊                 | 362/1000 [05:10<08:44,  1.22it/s]

[362/1000]
EN: R Praggnanandhaa overtook Ding Liren in May to lead the FIDE Circuit race.
MNI_MTEI: ꯑꯥꯔꯒꯅꯅꯥꯟꯗꯅꯥ ꯃꯦꯗꯥ ꯐꯤꯗꯦ ꯁꯔꯀꯏꯇ ꯂꯝꯖꯦꯜ ꯂꯨꯆꯤꯡꯕꯥ ꯗꯤꯡ ꯂꯤꯔꯦꯟꯕꯨ ꯃꯥꯡꯖꯤꯜ ꯊꯥꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▊                 | 363/1000 [05:11<09:07,  1.16it/s]

[363/1000]
EN: Praggnanandhaa thanked supporters on X after earning a place in the 2026 Candidates.
MNI_MTEI: ꯄꯒꯅꯅꯥꯟꯙꯥꯅꯥ ꯏꯪꯁꯣꯛ 2026 ꯒꯤ ꯀꯦꯟꯗꯤꯇꯦꯗꯗꯥ ꯃꯐꯝ ꯑꯃ ꯐꯪꯂꯕ ꯃꯇꯨꯡꯗ ꯑꯦꯛꯁꯇ ꯁꯧꯒꯠꯄꯁꯤꯡꯕꯨ ꯊꯥꯒꯠꯄ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▊                 | 364/1000 [05:12<09:35,  1.11it/s]

[364/1000]
EN: A report said only Nodirbek Abdusattorov had a theoretical chance to catch Praggnanandhaa.
MNI_MTEI: ꯔꯤꯄꯣꯔꯇ ꯑꯃꯥꯅꯥ ꯍꯥꯏꯔꯝꯃꯤ ꯃꯗꯨꯗꯤ ꯅꯣꯗꯤꯔꯕꯦꯛ ꯑꯕꯗꯨꯁꯥꯠꯇꯣꯔꯣꯚ ꯈꯛꯇꯅꯥꯒꯅꯅꯥꯟꯙꯥ ꯐꯥꯕꯒꯤ ꯊꯤꯑꯣꯔꯦꯇꯤꯀꯦꯜ ꯑꯣꯏꯕ ꯇꯥꯟꯖꯥ ꯑꯃ ꯂꯩꯈꯤ ꯫
--------------------------------------------------

Translating:  36%|█████████▊                 | 365/1000 [05:13<09:31,  1.11it/s]

[365/1000]
EN: D Gukesh withdrew from Tata Steel Chess India Rapid and Blitz for personal reasons.
MNI_MTEI: ꯗꯤ ꯒꯨꯀꯦꯁꯅ ꯇꯥꯇꯥꯇꯦꯜ ꯆꯦꯁ ꯏꯟꯗꯤꯌꯥ ꯔꯦꯄꯤꯗ ꯑꯃꯁꯨꯡ ꯕꯂꯤꯇꯖꯗꯒꯤ ꯂꯅꯥꯏꯒꯤ ꯑꯣꯏꯕ ꯃꯔꯝꯁꯤꯡ ꯂꯩꯔꯗꯨꯅ ꯂꯧꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  37%|█████████▉                 | 366/1000 [05:14<09:21,  1.13it/s]

[366/1000]
EN: Tata Steel Chess India Rapid and Blitz was scheduled in Kolkata from January 7 to 11.
MNI_MTEI: ꯇꯥꯇꯥꯇꯤꯜ ꯆꯦꯁ ꯏꯟꯗꯤꯌꯥ ꯔꯦꯄꯤꯗ ꯑꯃꯁꯨꯡ ꯕꯂꯤꯇꯖ ꯑꯁꯤ ꯀꯣꯜꯀꯥꯇꯥꯗꯥ ꯖꯅꯨꯋꯥꯔꯤ ꯗꯒꯤ ꯐꯥꯎꯕ ꯄꯥꯡꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  37%|█████████▉                 | 367/1000 [05:14<08:56,  1.18it/s]

[367/1000]
EN: Nihal Sarin replaced D Gukesh in the Tata Steel Chess India event.
MNI_MTEI: ꯅꯤꯍꯥꯜ ꯁꯥꯔꯤꯟꯅꯥ ꯇꯥꯇꯥꯇꯦꯜ ꯆꯦꯁ ꯏꯟꯗꯤꯌꯥ ꯏꯚꯦꯟꯇꯗꯥ ꯗꯤ ꯒꯨꯀꯦꯁꯀꯤ ꯃꯐꯝ ꯂꯧ
--------------------------------------------------

Translating:  37%|█████████▉                 | 368/1000 [05:15<09:04,  1.16it/s]

[368/1000]
EN: Dibyendu Barua called D Gukesh’s withdrawal a big setback for organisers and fans.
MNI_MTEI: ꯗꯤꯕꯌꯦꯟꯗꯨ ꯕꯔꯨꯋꯥꯅꯥ ꯗꯤ ꯒꯨꯀꯦꯁꯀꯤ ꯂꯧꯊꯣꯛꯄꯥ ꯑꯁꯤ ꯑꯣꯔꯖꯦꯟꯖꯔꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯐꯦꯟꯁꯤꯡꯒꯤ ꯑꯆꯧꯕ ꯃꯥꯏꯊꯤꯅꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  37%|█████████▉                 | 369/1000 [05:16<08:44,  1.20it/s]

[369/1000]
EN: Viswanathan Anand returned to play Tata Steel Chess India after six years away.
MNI_MTEI: ꯕꯤꯁꯋꯥꯅꯥꯊꯅ ꯑꯥꯅꯟꯗꯅꯥ ꯆꯍꯤ ꯇꯥꯔꯨꯛꯀꯤ ꯃꯇꯨꯡꯗ ꯇꯥꯇꯥꯇꯦꯜ ꯆꯦꯁ ꯏꯟꯗꯤꯌꯥ ꯁꯥꯟꯅꯅꯕ ꯍꯜꯂꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  37%|█████████▉                 | 370/1000 [05:17<08:43,  1.20it/s]

[370/1000]
EN: Viswanathan Anand said “It was exhausting not playing” while explaining his return.
MNI_MTEI: ꯕꯤꯁꯋꯥꯅꯥꯊꯅ ꯑꯥꯅꯟꯅ ꯍꯥꯏꯈꯤ  " ꯃꯍꯥꯛꯀꯤ ꯍꯜꯂꯛꯄꯒꯤ ꯃꯇꯥꯡꯗ ꯁꯟꯗꯣꯛꯅ ꯇꯥꯛꯂꯗꯨꯅ, ꯁꯥꯟꯅꯗꯕꯁꯤ ꯑꯋꯥꯕꯅꯤ ꯫
--------------------------------------------------

Translating:  37%|██████████                 | 371/1000 [05:18<08:46,  1.20it/s]

[371/1000]
EN: Viswanathan Anand was set to open against Wesley So in the seventh edition.
MNI_MTEI: ꯕꯤꯁꯋꯥꯅꯥꯊꯅ ꯑꯥꯅꯟꯅꯥ ꯋꯦꯁꯂꯤ ꯁꯣꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ 7 ꯁꯨꯕꯥ ꯑꯦꯗꯤꯁꯟꯗꯥ ꯑꯣꯄꯟ ꯇꯧꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯦꯞ
--------------------------------------------------

Translating:  37%|██████████                 | 372/1000 [05:18<08:22,  1.25it/s]

[372/1000]
EN: The tournament director said Tata Steel Chess India will be held in January going forward.
MNI_MTEI: ꯇꯣꯔꯅꯥꯃꯦꯟꯇ ꯗꯤꯔꯦꯛꯇꯔꯅꯥ ꯍꯥꯏ ꯃꯗꯨꯗꯤ ꯇꯥꯇꯥꯇꯦꯜ ꯆꯦꯁ ꯏꯟꯗꯤꯌꯥ ꯑꯁꯤ ꯃꯈꯥ ꯇꯥꯅ ꯖꯅꯨꯋꯥꯔꯤꯗꯥ ꯄꯥꯡꯊꯣꯛꯀꯅꯤ ꯫
--------------------------------------------------

Translating:  37%|██████████                 | 373/1000 [05:19<08:22,  1.25it/s]

[373/1000]
EN: The Tata Steel Chess India event offered equal prize purses of $41,500 in open and women’s.
MNI_MTEI: ꯇꯥꯇꯥꯇꯦꯜ ꯆꯦꯁ ꯏꯟꯗꯤꯌꯥ ꯏꯚꯦꯟꯇꯅꯥ ꯑꯣꯄꯟ ꯑꯃꯁꯨꯡ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯗꯣꯜꯂꯔ 41,500ꯒꯤ ꯃꯥꯟꯅꯕ ꯄꯔꯁꯁꯤꯡ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  37%|██████████                 | 374/1000 [05:20<08:40,  1.20it/s]

[374/1000]
EN: Viswanathan Anand backed the Total Chess World Championship Tour approved by FIDE.
MNI_MTEI: ꯐꯤꯗꯦꯅꯥ ꯑꯌꯥꯕ ꯄꯤꯔꯕꯥ ꯇꯣꯇꯥꯜ ꯆꯦꯁ ꯋꯥꯔꯜꯗ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯞ ꯇꯨꯔ ꯑꯁꯤ ꯕꯤꯁꯋꯥꯅꯥꯊꯅ ꯑꯥꯅꯟꯅ ꯁꯧꯒꯠ
--------------------------------------------------

Translating:  38%|██████████▏                | 375/1000 [05:21<09:12,  1.13it/s]

[375/1000]
EN: The Total Chess World Championship Tour will crown a new “FIDE World Combined” champion.
MNI_MTEI: ꯇꯣꯇꯥꯜ ꯆꯦꯁ ꯋꯥꯔꯜꯗ ꯆꯦꯝꯄꯤꯌꯟꯁꯤꯞ ꯇꯨꯔꯅꯥ ꯑꯅꯧꯕ ꯐꯤꯗꯦ ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯝꯕꯥꯏꯟꯗ ꯀꯝꯃꯤꯄꯌꯥꯟ ꯑꯃ ꯑꯣꯏꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▏                | 376/1000 [05:22<08:49,  1.18it/s]

[376/1000]
EN: The tour will be held across fast classic, rapid and blitz formats.
MNI_MTEI: ꯇꯨꯔ ꯑꯁꯤ ꯐꯥꯁꯀꯥꯁꯤꯛ, ꯔꯦꯄꯤꯗ ꯑꯃꯁꯨꯡ ꯕꯂꯤꯇꯖ ꯐꯣꯔꯃꯦꯇꯁꯤꯡꯗ ꯄꯥꯡꯊꯣꯛꯀꯅꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▏                | 377/1000 [05:23<08:24,  1.23it/s]

[377/1000]
EN: Anand said Norway Chess has a serious long-term proposal for the new tour.
MNI_MTEI: ꯑꯥꯅꯟꯅ ꯍꯥꯏ ꯃꯗꯨꯗꯤ ꯅꯣꯔꯋꯦ ꯆꯦꯁꯅꯥ ꯑꯅꯧꯕ ꯇꯨꯔ ꯑꯁꯤꯒꯤꯗꯃꯛ ꯌꯥꯝꯅ ꯂꯨꯕꯥ ꯃꯇꯝ ꯆꯨꯞꯄꯒꯤ ꯋꯥꯐꯝ ꯑꯃ ꯊꯝ
--------------------------------------------------

Translating:  38%|██████████▏                | 378/1000 [05:23<08:13,  1.26it/s]

[378/1000]
EN: Anand said the sport benefits when Magnus Carlsen competes in major events.
MNI_MTEI: ꯑꯥꯅꯟꯅ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯃꯦꯒꯅꯁ ꯀꯥꯔꯂꯁꯦꯟꯅꯥ ꯑꯆꯧꯕ ꯊꯧꯔꯝꯁꯤꯡꯗ ꯁꯔꯨꯛ ꯌꯥꯔꯕꯥ ꯃꯇꯝꯗꯄꯣꯔꯇ ꯑꯁꯤꯅ ꯀꯥꯟꯅꯕ ꯐꯪꯉꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▏                | 379/1000 [05:24<08:29,  1.22it/s]

[379/1000]
EN: Wesley So said he proposed a draw against Praggnanandhaa, not the arbiters.
MNI_MTEI: ꯋꯦꯁꯂꯤ ꯁꯣꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯃꯍꯥꯛꯅ ꯑꯔꯕꯤꯇꯔꯁꯤꯡ ꯅꯠꯇꯅꯥꯒꯥ ꯄꯒꯅꯅꯥꯟꯙꯥꯒꯤ ꯃꯥꯏꯌꯣꯛꯇꯥ ꯗꯀꯤ ꯋꯥꯐꯝ ꯊꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▎                | 380/1000 [05:25<08:29,  1.22it/s]

[380/1000]
EN: Praggnanandhaa had one second left before stopping the clock to call the arbiter.
MNI_MTEI: ꯋꯥꯔꯣꯏꯁꯤꯟꯂꯣꯏ ꯑꯗꯨꯕꯨ ꯐꯣꯟ ꯇꯧꯅꯕ ꯄꯨꯡ ꯑꯗꯨ ꯂꯦꯞꯇꯉꯩꯗꯒꯅꯅꯥꯟꯙꯥꯗꯥ ꯁꯦꯀꯦꯟꯗ ꯑꯃ ꯂꯩꯔꯝ
--------------------------------------------------

Translating:  38%|██████████▎                | 381/1000 [05:26<08:44,  1.18it/s]

[381/1000]
EN: Nihal Sarin won the 2026 Tata Steel Chess India Rapid Tournament in Kolkata.
MNI_MTEI: ꯅꯤꯍꯥꯜ ꯁꯥꯔꯤꯟꯅ ꯀꯣꯜꯀꯥꯇꯥꯗꯥ ꯄꯥꯡꯊꯣꯛꯂꯤꯕꯥ ꯇꯥꯇꯥꯇꯦꯜ ꯆꯦꯁ ꯏꯟꯗꯤꯌꯥ ꯔꯦꯄꯤꯗ ꯇꯨꯔꯅꯥꯃꯦꯟꯇ 2026 ꯑꯗꯨ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▎                | 382/1000 [05:27<09:16,  1.11it/s]

[382/1000]
EN: Ian Nepomniachtchi criticised hotel conditions during the 2025 Chess World Cup in Goa.
MNI_MTEI: ꯏꯌꯥꯟ ꯅꯦꯄꯣꯃꯅꯤꯌꯥꯆꯇꯆꯤꯅꯥ ꯒꯣꯋꯥꯗꯥ ꯄꯥꯡꯊꯣꯛꯂꯤꯕꯥ ꯏꯪꯁꯣꯛ 2025ꯒꯤ ꯆꯦꯁ ꯋꯥꯔꯂꯗ ꯀꯞꯀꯤ ꯃꯇꯝꯗ ꯍꯣꯇꯦꯜꯒꯤ ꯐꯤꯚꯝꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯈꯟꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▎                | 383/1000 [05:28<09:12,  1.12it/s]

[383/1000]
EN: Ian Nepomniachtchi said organisers chose one of the worst hotels for the Goa event.
MNI_MTEI: ꯏꯌꯥꯟ ꯅꯦꯄꯣꯃꯅꯤꯌꯥꯆꯠꯆꯤꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯒꯣꯋꯥꯒꯤ ꯊꯧꯔꯝꯒꯤꯗꯃꯛ ꯊꯧꯔꯥꯡ ꯇꯧꯕꯁꯤꯡꯅ ꯂꯥꯏꯔꯕ ꯍꯣꯇꯦꯜ ꯑꯃ ꯈꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▎                | 384/1000 [05:29<08:53,  1.15it/s]

[384/1000]
EN: Nepomniachtchi lost to Diptayan Ghosh after receiving a bye into round two.
MNI_MTEI: ꯅꯦꯄꯣꯃꯅꯤꯌꯥꯆꯠꯆꯤ ꯑꯁꯤ ꯔꯥꯎꯟꯗ ꯑꯅꯤꯗꯥ ꯕꯥꯏ ꯑꯃ ꯐꯪꯂꯕ ꯃꯇꯨꯡꯗ ꯗꯤꯄꯇꯌꯟ ꯒꯣꯁꯥꯇꯥ ꯃꯥꯏꯊꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  38%|██████████▍                | 385/1000 [05:30<08:39,  1.18it/s]

[385/1000]
EN: PGTI’s 2026 schedule was drawn up only till March-end, featuring six events.
MNI_MTEI: ꯄꯤ ꯖꯤ ꯇꯤ ꯑꯥꯏ ꯒꯤ ꯁꯦꯗꯜ 2026 ꯑꯁꯤ ꯃꯥꯔꯀꯤ ꯑꯔꯣꯏꯕꯥ ꯐꯥꯎꯕꯗ ꯏꯚꯦꯟꯇ ꯇꯔꯨꯛ ꯌꯥꯎꯅꯥ ꯁꯦꯝ
--------------------------------------------------

Translating:  39%|██████████▍                | 386/1000 [05:30<08:26,  1.21it/s]

[386/1000]
EN: PGTI planned no more than 25 tournaments in 2026 after holding 36 events last year.
MNI_MTEI: ꯄꯤ ꯖꯤ ꯇꯤ ꯑꯥꯏꯅꯥ ꯍꯧꯈꯤꯕ ꯆꯍꯤꯗ ꯊꯧꯔꯝ 36 ꯄꯥꯡꯊꯣꯛꯂꯕ ꯃꯇꯨꯡꯗ ꯏꯪꯁꯣꯛ 2026 ꯗꯥ ꯇꯣꯔꯅꯥꯃꯦꯟꯇꯗꯒꯤ ꯍꯦꯟꯕꯥ ꯊꯧꯔꯥꯡ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  39%|██████████▍                | 387/1000 [05:31<08:36,  1.19it/s]

[387/1000]
EN: PGTI’s main tour offered ₹35 crore prize money in 2025, up from ₹24 crore.
MNI_MTEI: ꯄꯤ ꯖꯤ ꯇꯤ ꯑꯥꯏ ꯒꯤ ꯃꯔꯨ ꯑꯣꯏꯕ ꯇꯨꯔꯅꯥ ꯏꯪ 2025 ꯗꯥ ꯂꯨꯄꯥ ꯀꯔꯣꯔ 35 ꯒꯤ ꯄꯥꯏꯖ ꯃꯅꯤ ꯄꯤꯈꯤ, ꯃꯁꯤ ꯂꯨꯄꯥ ꯀꯣꯔꯣꯔ ꯗꯒꯤ ꯍꯦꯟꯒꯠ
--------------------------------------------------

Translating:  39%|██████████▍                | 388/1000 [05:32<09:08,  1.12it/s]

[388/1000]
EN: OWGR granted LIV Golf accreditation for the first time, awarding points to top-10 finishers.
MNI_MTEI: ꯑꯣ.ꯑꯣ.ꯖꯤ.ꯑꯥꯔ.ꯅꯥ ꯑꯍꯥꯟꯕ ꯑꯣꯏꯅ ꯑꯦꯜ. ꯑꯥꯏ.ꯚꯤ. ꯒꯣꯜꯐ ꯑꯦꯀꯗꯤꯇꯦꯁꯟ ꯄꯤꯈꯤ, ꯇꯣꯄ10 ꯐꯥꯏꯅꯤꯁꯔꯁꯤꯡꯗ ꯄꯣꯏꯟꯇꯁꯤꯡ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  39%|██████████▌                | 389/1000 [05:33<09:25,  1.08it/s]

[389/1000]
EN: LIV Golf expanded tournaments from 54 to 72 holes in 2026, paving the approval.
MNI_MTEI: ꯏꯪꯁꯣꯛ ꯗꯥ ꯑꯦꯜ.ꯑꯥꯏ.ꯚꯤ. ꯒꯣꯜꯐꯅꯥ ꯇꯣꯔꯅꯥꯃꯦꯟꯇ 54ꯗꯒꯤ ꯍꯣꯜ ꯐꯥꯎꯕ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯈꯤ, ꯃꯗꯨꯅ ꯑꯌꯥꯕ ꯄꯤ
--------------------------------------------------

Translating:  39%|██████████▌                | 390/1000 [05:34<09:38,  1.05it/s]

[390/1000]
EN: OWGR said LIV Golf did not meet all eligibility standards under its requirements.
MNI_MTEI: ꯑꯣ.ꯑꯣ.ꯖꯤ.ꯑꯥꯔ.ꯅꯥ ꯍꯥꯏ ꯃꯗꯨꯗꯤ ꯑꯦꯜ. ꯑꯥꯏ.ꯚꯤ. ꯒꯣꯜꯐꯅꯥ ꯃꯁꯤꯒꯤ ꯃꯊꯧ ꯇꯥꯕꯥ ꯑꯦꯂꯤꯖꯤꯕꯤꯂꯤꯇꯤꯦꯟꯗꯗꯔ ꯄꯨꯝꯅꯃꯛ ꯐꯪꯗꯦ ꯫
--------------------------------------------------

Translating:  39%|██████████▌                | 391/1000 [05:35<09:02,  1.12it/s]

[391/1000]
EN: LIV Golf’s season-opening event in Riyadh was set to start with 57 players.
MNI_MTEI: ꯂꯤꯚ ꯒꯣꯜꯐꯀꯤ ꯁꯤꯖꯟ - ꯑꯣꯄꯦꯅꯤꯡ ꯏꯚꯦꯟꯇ ꯑꯁꯤ ꯔꯤꯌꯥꯗꯗꯥ ꯁꯥꯟꯅꯔꯣꯏ 57ꯒꯥ ꯂꯣꯏꯅꯅ ꯍꯧꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  39%|██████████▌                | 392/1000 [05:36<08:48,  1.15it/s]

[392/1000]
EN: International Series India was expected to move from DLF Golf and Country Club to Bengaluru.
MNI_MTEI: ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯁꯤꯔꯤꯖ ꯏꯟꯗꯤꯌꯥ ꯑꯁꯤ ꯗꯤ ꯑꯦꯜ ꯑꯦꯐ ꯒꯣꯜꯐ ꯑꯃꯁꯨꯡ ꯀꯟꯇ ꯀꯂꯕꯇꯒꯤ ꯕꯦꯡꯒꯂꯨꯔꯨꯗ ꯆꯠꯀꯅꯤ ꯍꯥꯏꯅ ꯄꯥꯅꯔꯤ ꯫
--------------------------------------------------

Translating:  39%|██████████▌                | 393/1000 [05:37<08:54,  1.14it/s]

[393/1000]
EN: Bryson DeChambeau and Joaquin Niemann were key draws at International Series India 2025.
MNI_MTEI: ꯕꯁꯟ ꯗꯤꯆꯝꯕꯦꯎ ꯑꯃꯁꯨꯡ ꯖꯣꯑꯀ ꯭ ꯋꯤꯟ ꯅꯤꯃꯦꯅꯅꯥ ꯏꯪ 2025 ꯗꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯁꯤꯔꯤꯖ ꯏꯟꯗꯤꯌꯥꯗꯥ ꯃꯔꯨꯑꯣꯏꯕ ꯗꯁꯤꯡ ꯑꯣꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  39%|██████████▋                | 394/1000 [05:37<08:42,  1.16it/s]

[394/1000]
EN: Ollie Schniederjans won International Series India 2025 by four shots in Gurugram.
MNI_MTEI: ꯑꯣꯂꯤꯅꯤꯗꯦꯔꯖꯟꯁꯅꯥ ꯒꯒꯣꯔꯥꯃꯗꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯁꯤꯔꯤꯖ ꯏꯟꯗꯤꯌꯥ 2025 ꯑꯁꯤ ꯁꯣꯠ ꯃꯔꯤꯅꯥ ꯃꯥꯏ ꯄꯥꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  40%|██████████▋                | 395/1000 [05:38<08:09,  1.24it/s]

[395/1000]
EN: Rahul Singh said International Series organisers remained committed to returning to India.
MNI_MTEI: ꯔꯍꯨꯜ ꯁꯤꯡꯍꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯁꯤꯔꯤꯖ ꯑꯣꯔꯖꯦꯟꯖꯔꯁꯤꯡꯅ ꯚꯥꯔꯠꯇ ꯍꯜꯂꯛꯄꯗꯥ ꯂꯦꯞ
--------------------------------------------------

Translating:  40%|██████████▋                | 396/1000 [05:39<08:22,  1.20it/s]

[396/1000]
EN: PGTI launched a league with six franchises, with each franchise buying 10 players.
MNI_MTEI: ꯄꯤꯖꯤꯇꯤꯑꯥꯏꯅꯥ ꯐꯥꯟꯆꯥꯏꯖꯤ ꯇꯔꯨꯛꯀꯤ ꯂꯤꯒ ꯑꯃ ꯍꯥꯡꯗꯣꯛꯈꯤ, ꯃꯁꯤꯗ ꯐꯇꯟꯆꯏꯖꯤ ꯈꯨꯗꯤꯡꯃꯛꯅ ꯁꯥꯟꯅꯔꯣꯏ 10 ꯂꯧ
--------------------------------------------------

Translating:  40%|██████████▋                | 397/1000 [05:40<08:03,  1.25it/s]

[397/1000]
EN: The PGTI league’s first edition was planned across three courses in Delhi-NCR.
MNI_MTEI: ꯄꯤ ꯖꯤ ꯇꯤ ꯑꯥꯏ ꯂꯤꯒꯀꯤ ꯑꯍꯥꯟꯕꯥ ꯑꯦꯗꯤꯁꯟ ꯑꯁꯤ ꯗꯤꯜꯂꯤ- ꯑꯦꯟ ꯁꯤ ꯑꯥꯔ ꯒꯤ ꯀꯣꯔꯁ ꯑꯍꯨꯝꯗꯥ ꯊꯧꯔꯥꯡ ꯇꯧ
--------------------------------------------------

Translating:  40%|██████████▋                | 398/1000 [05:41<08:09,  1.23it/s]

[398/1000]
EN: Shubhankar Sharma missed cuts in 21 of 28 events in 2025, the report said.
MNI_MTEI: ꯁꯨꯚꯥꯟꯀꯔ ꯁꯔꯃꯥꯅꯥ ꯏꯪꯁꯣꯛ 2025 ꯗꯥ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯊꯧꯔꯝꯒꯤ ꯃꯅꯨꯡꯗ 21ꯗꯥ ꯀꯠꯁꯤꯡ ꯃꯥꯡꯈꯤ ꯍꯥꯏꯅ ꯔꯤꯄꯣꯔꯇ ꯑꯁꯤꯅ ꯍꯥꯏ
--------------------------------------------------

Translating:  40%|██████████▊                | 399/1000 [05:42<08:41,  1.15it/s]

[399/1000]
EN: Shubhankar Sharma regained playing rights for 2026 via Q-School, finishing tied-second.
MNI_MTEI: ꯁꯨꯚꯥꯟꯀꯔ ꯁꯔꯃꯥꯅꯥ ꯏꯪꯁꯣꯛ ꯒꯤꯗꯃꯛ ꯀ-ꯨꯜꯒꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯁꯥꯟꯅꯕꯒꯤ ꯍꯛꯁꯤꯡ ꯑꯃꯨꯛ ꯍꯟꯅ ꯂꯧꯁꯤꯟꯈꯤ, ꯇꯥꯏ-ꯁꯦꯀꯦꯟꯗ ꯂꯣꯏꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  40%|██████████▊                | 400/1000 [05:42<08:34,  1.17it/s]

[400/1000]
EN: Vietnam targets 22 to 25 million international visitors by 2026.
MNI_MTEI: ꯚꯤꯇꯦꯝꯅꯥ ꯏꯪꯁꯣꯛ 2026 ꯐꯥꯎꯕꯗ ꯃꯥꯂꯦꯝꯒꯤ ꯑꯣꯏꯕ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈꯗꯒꯤ ꯐꯥꯎꯕ ꯂꯥꯛꯀꯗꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  40%|██████████▊                | 401/1000 [05:43<07:51,  1.27it/s]

[401/1000]
EN: Operations teams monitor weather to minimize passenger inconvenience.
MNI_MTEI: ꯑꯣꯄꯔꯦꯁꯟ ꯇꯤꯝꯁꯤꯡꯅꯥ ꯄꯦꯁꯦꯟꯖꯔꯁꯤꯡꯒꯤ ꯑꯋꯥꯕꯥ ꯍꯟꯊꯍꯟꯅꯕ ꯋꯦꯗꯔ ꯌꯦꯡꯁꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  40%|██████████▊                | 402/1000 [05:44<08:03,  1.24it/s]

[402/1000]
EN: IndiGo announces Amsterdam debut as first long-haul European destination.
MNI_MTEI: ꯏꯟꯗꯤꯒꯣꯅꯥ ꯑꯍꯥꯟꯕ ꯂꯥꯡ-ꯍꯣꯜ ꯌꯨꯔꯣꯄꯤꯌꯟ ꯗꯦꯁꯇꯤꯅꯦꯁꯟ ꯑꯣꯏꯅ ꯑꯝꯁꯇꯔꯗꯦꯃꯇꯗꯥ ꯗꯦꯕꯌꯨ ꯇꯧꯔꯦ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  40%|██████████▉                | 403/1000 [05:45<07:44,  1.28it/s]

[403/1000]
EN: Air India crash committee investigates Boeing 787-8 Ahmedabad tragedy.
MNI_MTEI: ꯑꯦꯔ ꯏꯟꯗꯤꯌꯥꯦꯁ ꯀꯝꯃꯤꯇꯤꯅ ꯕꯣꯏꯡ 787-8 ꯑꯍꯃꯗꯕꯥꯗ ꯇꯖꯦꯟꯗꯤ ꯊꯤꯖꯤꯟ
--------------------------------------------------

Translating:  40%|██████████▉                | 404/1000 [05:45<07:23,  1.34it/s]

[404/1000]
EN: IndiGo aims for forty percent international capacity share by 2030.
MNI_MTEI: ꯏꯟꯗꯤꯒꯣꯅꯥ ꯏꯪ 2030 ꯐꯥꯎꯕꯗ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯀꯦꯄꯦꯁꯤꯇꯤ ꯁꯦꯌꯔ ꯆꯥꯗꯥ 40 ꯑꯣꯏꯍꯟꯅꯕ ꯄꯥꯟꯗꯝ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  40%|██████████▉                | 405/1000 [05:46<07:08,  1.39it/s]

[405/1000]
EN: One survivor rescued from Air India crash site in Ahmedabad.
MNI_MTEI: ꯑꯍꯃꯗꯕꯥꯗꯇꯥ ꯂꯩꯕ ꯑꯦꯔ ꯏꯟꯗꯤꯌꯥ ꯀꯁ ꯁꯥꯏꯇꯗꯒꯤ ꯍꯤꯡꯕꯥ ꯃꯤꯑꯣꯏ ꯑꯃ ꯉꯥꯛꯊꯣꯛ
--------------------------------------------------

Translating:  41%|██████████▉                | 406/1000 [05:47<06:53,  1.44it/s]

[406/1000]
EN: Jetstar Asia closure frees five hundred million dollars for Qantas.
MNI_MTEI: ꯖꯦꯇꯁꯇꯥꯔ ꯑꯦꯁꯤꯌꯥ ꯀꯂꯣꯁꯔꯅꯥ ꯀꯋꯥꯟꯇꯥꯁꯀꯤ ꯗꯣꯂꯔ ꯃꯤꯂꯌꯟ ꯃꯉꯥ ꯐ
--------------------------------------------------

Translating:  41%|██████████▉                | 407/1000 [05:47<06:47,  1.46it/s]

[407/1000]
EN: Qantas Group announces closure of Singapore-based Jetstar Asia.
MNI_MTEI: ꯀꯋꯥꯟꯇꯥꯁ ꯒꯨꯞꯅ ꯁꯤꯡꯒꯥꯄꯨꯔꯗꯥ ꯂꯩꯕ ꯖꯦꯇꯁꯇꯥꯔ ꯑꯦꯁꯤꯌꯥ ꯊꯤꯡꯖꯤꯟꯅꯕꯥ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  41%|███████████                | 408/1000 [05:48<07:06,  1.39it/s]

[408/1000]
EN: IndiGo launches Mumbai-Manchester flights using Norse aircraft.
MNI_MTEI: ꯏꯟꯗꯤꯒꯣꯅꯥ ꯅꯣꯔ ꯭ ꯁ ꯑꯦꯔꯀꯐꯇ ꯁꯤꯖꯤꯟꯅꯕꯥ ꯃꯨꯝꯕꯥꯏ-ꯃꯥꯟꯆꯦꯁꯇꯔ ꯐꯂꯥꯏꯇꯁꯤꯡ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  41%|███████████                | 409/1000 [05:49<07:31,  1.31it/s]

[409/1000]
EN: IndiGo transitions to A350-900 aircraft for European expansion by 2027.
MNI_MTEI: ꯏꯪꯁꯣꯛ 2027 ꯐꯥꯎꯕꯗ ꯌꯨꯔꯣꯄꯤꯌꯟ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯅꯕ ꯏꯟꯗꯤꯒꯣꯅꯥ ꯑꯦ350-900 ꯑꯦꯌꯔꯀꯐꯇꯗꯥ ꯍꯣꯡꯗꯣꯛꯄꯥ ꯫
--------------------------------------------------

Translating:  41%|███████████                | 410/1000 [05:50<07:12,  1.36it/s]

[410/1000]
EN: Air India Ahmedabad crash claims 242 lives including Vijay Rupani.
MNI_MTEI: ꯑꯦꯔ ꯏꯟꯗꯤꯌꯥ ꯑꯍꯃꯗꯕꯥꯗ ꯀꯦꯁꯇꯥ ꯕꯤꯖꯌ ꯔꯨꯄꯥꯅꯤ ꯌꯥꯎꯅ ꯃꯤꯑꯣꯏ ꯁꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  41%|███████████                | 411/1000 [05:50<07:15,  1.35it/s]

[411/1000]
EN: Thirteen Jetstar Asia A320s redeployed to Australia and New Zealand.
MNI_MTEI: ꯖꯦꯇꯁꯇꯥꯔ ꯑꯦꯁꯤꯌꯥ ꯑꯦ 13 ꯑꯁꯤ ꯑꯣꯁꯇꯂꯤꯌꯥ ꯑꯃꯁꯨꯡ ꯅ ꯭ ꯌꯨ ꯖꯤꯂꯦꯟꯗꯗꯥ ꯑꯃꯨꯛ ꯍꯟꯅ ꯁꯤꯟꯅ
--------------------------------------------------

Translating:  41%|███████████                | 412/1000 [05:51<07:04,  1.38it/s]

[412/1000]
EN: IndiGo issues fog advisory for Delhi and northern India passengers.
MNI_MTEI: ꯏꯟꯗꯤꯒꯣꯅꯥ ꯗꯤꯜꯂꯤ ꯑꯃꯁꯨꯡ ꯑꯋꯥꯡ ꯚꯥꯔꯠꯀꯤ ꯄꯦꯁꯦꯟꯖꯔꯁꯤꯡꯒꯤꯗꯃꯛ ꯐꯒ ꯑꯦꯗꯚꯥꯏꯖꯔꯤꯁꯤꯡ ꯏꯁꯨ ꯇꯧ
--------------------------------------------------

Translating:  41%|███████████▏               | 413/1000 [05:52<06:53,  1.42it/s]

[413/1000]
EN: DGCA imposes ₹2 crore fine on Air India for safety lapses.
MNI_MTEI: ꯁꯦꯐꯇꯤ ꯂꯥꯄꯁꯤꯡꯒꯤꯗꯃꯛ ꯗꯤ ꯖꯤ ꯁꯤ ꯑꯦꯅꯥ ꯑꯦꯌꯔ ꯏꯟꯗꯤꯌꯥꯗꯥ ꯂꯨꯄꯥ ꯀꯔꯣꯔ 2 ꯐꯥꯏꯅ ꯇꯧ
--------------------------------------------------

Translating:  41%|███████████▏               | 414/1000 [05:52<07:02,  1.39it/s]

[414/1000]
EN: Sixteen intra-Asia routes lose only non-stop Changi connections.
MNI_MTEI: ꯏꯟ-ꯑꯦꯁꯤꯌꯥ ꯔꯨꯠ ꯇꯔꯥꯃꯥꯖꯅꯥ ꯅꯟ-ꯁꯇꯣꯄ ꯆꯪꯒꯤ ꯀꯟꯀꯁꯟꯁꯤꯡ ꯈꯛꯇꯃꯛ ꯃꯥꯡ
--------------------------------------------------

Translating:  42%|███████████▏               | 415/1000 [05:53<07:03,  1.38it/s]

[415/1000]
EN: Bengaluru airport opens second runway to handle growing traffic.
MNI_MTEI: ꯍꯦꯟꯒꯠꯂꯛꯂꯤꯕ ꯇꯐꯤꯛ ꯁꯤꯟꯗꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯕꯦꯡꯂꯨꯨꯔꯨ ꯑꯦꯌꯔꯄꯣꯔꯇꯅꯥ ꯑꯅꯤꯁꯨꯕ ꯔꯥꯟꯋꯦ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  42%|███████████▏               | 416/1000 [05:54<07:27,  1.31it/s]

[416/1000]
EN: Air India Express pilot assaults passenger at Delhi airport terminal.
MNI_MTEI: ꯑꯦꯔ ꯏꯟꯗꯤꯌꯥ ꯑꯦꯛꯁꯄꯦꯁꯀꯤ ꯄꯥꯏꯂꯣꯠꯅꯥ ꯗꯤꯜꯂꯤ ꯑꯦꯌꯔꯄꯣꯔꯇ ꯇꯔꯃꯤꯅꯦꯜꯗꯥ ꯄꯦꯁꯦꯟꯖꯔꯕꯨ ꯂꯥꯟꯗꯥꯈꯤ ꯫
--------------------------------------------------

Translating:  42%|███████████▎               | 417/1000 [05:55<07:12,  1.35it/s]

[417/1000]
EN: Mumbai airport witnesses record passenger footfall during festive week.
MNI_MTEI: ꯃꯨꯝꯕꯥꯏ ꯑꯦꯌꯔꯄꯣꯔꯇꯗꯥ ꯀꯨꯝꯍꯩꯒꯤ ꯆꯌꯣꯜꯗꯥ ꯄꯦꯁꯦꯟꯖꯔꯁꯤꯡꯒꯤ ꯃꯁꯤꯡ ꯍꯟꯊꯔꯛꯄꯒꯤ ꯈꯨꯗꯝ
--------------------------------------------------

Translating:  42%|███████████▎               | 418/1000 [05:56<07:24,  1.31it/s]

[418/1000]
EN: Dense fog disrupts IndiGo flight operations across North India.
MNI_MTEI: ꯑꯋꯥꯡ ꯚꯥꯔꯠ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯀꯨꯡꯈꯠꯂꯛꯄꯥ ꯎꯔꯨꯝꯅꯥ ꯏꯟꯗꯤꯒꯣ ꯐꯥꯏꯇ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡꯗ ꯑꯀꯥꯏꯕꯥ ꯄꯤ
--------------------------------------------------

Translating:  42%|███████████▎               | 419/1000 [05:56<07:21,  1.31it/s]

[419/1000]
EN: Go First insolvency resolution extends to third consecutive month.
MNI_MTEI: ꯒꯣ ꯐꯔꯁꯠ ꯏꯟꯁꯣꯜꯚꯦꯟꯁꯤ ꯔꯤꯖꯂꯨꯁꯟ ꯑꯁꯤ ꯃꯊꯪ ꯃꯅꯥꯎ ꯅꯥꯏꯅ ꯊꯥ ꯑꯍꯨꯝ ꯐꯥꯎꯕ ꯁꯟꯗꯣꯛ
--------------------------------------------------

Translating:  42%|███████████▎               | 420/1000 [05:57<07:30,  1.29it/s]

[420/1000]
EN: Akasa Air orders additional Boeing 737 Max aircraft for expansion.
MNI_MTEI: ꯑꯀꯥꯁꯥ ꯑꯦꯌꯔꯅꯥ ꯑꯍꯦꯟꯕ ꯕꯣꯏꯡ 737 ꯃꯦꯛꯁ ꯑꯦꯌꯔꯀꯐꯇ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯅꯕ ꯑꯣꯔꯗꯔ ꯄꯤ
--------------------------------------------------

Translating:  42%|███████████▎               | 421/1000 [05:58<07:17,  1.32it/s]

[421/1000]
EN: Air India pilots union raises concerns over rest period violations.
MNI_MTEI: ꯑꯦꯔ ꯏꯟꯗꯤꯌꯥ ꯄꯥꯏꯂꯣꯠꯁ ꯌꯨꯅꯤꯌꯟꯅ ꯔꯤꯁꯇꯥꯏꯗ ꯋꯥꯂꯥꯏꯟ ꯇꯧꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯆꯤꯡꯅꯕ ꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  42%|███████████▍               | 422/1000 [05:59<07:12,  1.34it/s]

[422/1000]
EN: EU launches Entry-Exit System campaign for non-EU travellers.
MNI_MTEI: ꯏꯌꯨ ꯅꯟ-ꯏꯌꯨ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯑꯦꯟꯇꯤ-ꯑꯦꯛꯖꯤꯠ ꯁꯤꯁꯇꯦꯝ ꯀꯦꯝꯄꯦꯅ ꯍꯧ
--------------------------------------------------

Translating:  42%|███████████▍               | 423/1000 [05:59<07:35,  1.27it/s]

[423/1000]
EN: SpiceJet secures funding to revive grounded fleet operations soon.
MNI_MTEI: ꯁꯥꯏꯖ ꯖꯦꯇꯅꯥ ꯊꯨꯅꯃꯛ ꯂꯩꯅꯨꯡꯗ ꯂꯩꯕ ꯐꯂꯤꯇ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡ ꯑꯃꯨꯛ ꯍꯟꯅ ꯍꯤꯡꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯁꯦꯜ ꯐꯪꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  42%|███████████▍               | 424/1000 [06:00<07:12,  1.33it/s]

[424/1000]
EN: Bulgaria adopts Euro as legal tender from January first 2026.
MNI_MTEI: ꯏꯪꯁꯣꯛ ꯒꯤ ꯖꯅꯨꯋꯥꯔꯤꯗꯒꯤ ꯕꯂꯒꯦꯔꯤꯌꯥꯅꯥ ꯌꯨꯔꯣꯕꯨ ꯂꯦꯖꯤꯀꯦꯜ ꯇꯦꯟꯗꯔ ꯑꯣꯏꯅ ꯂꯧ
--------------------------------------------------

Translating:  42%|███████████▍               | 425/1000 [06:01<07:12,  1.33it/s]

[425/1000]
EN: Vietnam grants forty-five day visa-free entry to twelve European nations.
MNI_MTEI: ꯚꯤꯇꯦꯝꯅꯥ ꯌꯨꯔꯣꯄꯤꯌꯟ ꯂꯩꯕꯥꯛ ꯇꯔꯥꯃꯥꯖꯗꯥ ꯅꯨꯃꯤꯠ ꯃꯔꯤ - ꯃꯉꯥꯒꯤ ꯚꯤꯖꯥ-ꯐ ꯑꯦꯟꯔꯤ ꯄꯤ
--------------------------------------------------

Translating:  43%|███████████▌               | 426/1000 [06:01<06:40,  1.43it/s]

[426/1000]
EN: Indian government reverses ban on Sikh pilgrimages to Pakistan.
MNI_MTEI: ꯚꯥꯔꯠ ꯁꯔꯀꯥꯔꯅꯥ ꯄꯥꯀꯤꯁꯇꯥꯟꯗꯥ ꯁꯤꯈ ꯂꯥꯏꯅꯤꯡꯐꯝ ꯆꯠꯄꯗꯥ ꯂꯦꯞꯈꯤꯕꯗꯨ ꯍꯟꯗꯣꯛ
--------------------------------------------------

Translating:  43%|███████████▌               | 427/1000 [06:02<06:26,  1.48it/s]

[427/1000]
EN: Pakistan High Commission issues visas to twenty-one hundred Sikh pilgrims.
MNI_MTEI: ꯄꯥꯀꯤꯁꯇꯥꯟ ꯍꯥꯏ ꯀꯝꯃꯤꯁꯟꯅꯥ ꯁꯤꯈ ꯂꯥꯏꯅꯤꯡꯐꯝ ꯆꯥꯃ ꯆꯥꯗꯥ ꯚꯤꯖꯥ ꯄꯤ
--------------------------------------------------

Translating:  43%|███████████▌               | 428/1000 [06:03<06:31,  1.46it/s]

[428/1000]
EN: TSA ends shoe removal rule at domestic United States airports.
MNI_MTEI: ꯇꯤ ꯑꯦꯁ ꯑꯦꯅꯥ ꯗꯣꯃꯦꯁꯇꯤꯛ ꯌꯨꯅꯥꯏꯇꯦꯗ ꯑꯦꯔꯄꯣꯔꯇꯗꯥ ꯁꯨ ꯔꯤꯃꯣꯕꯦꯜ ꯔꯨꯜ ꯂꯣꯏꯁꯤꯟ
--------------------------------------------------

Translating:  43%|███████████▌               | 429/1000 [06:04<06:45,  1.41it/s]

[429/1000]
EN: Real ID enforcement charges tourists forty-five dollars for domestic flights.
MNI_MTEI: ꯔꯤꯌꯦꯜ ꯑꯥꯏꯗꯤ ꯑꯦꯟꯐꯔꯁꯃꯦꯟꯇꯅꯥ ꯗꯣꯃꯦꯁꯇꯤꯛꯂꯥꯏꯇꯁꯤꯡꯒꯤꯗꯃꯛ ꯂꯝꯀꯣꯏꯕꯥꯁꯤꯡꯗꯒꯤ ꯗꯣꯂꯔ ꯃꯔꯤ - ꯃꯉꯥ ꯂꯧꯏ ꯫
--------------------------------------------------

Translating:  43%|███████████▌               | 430/1000 [06:04<06:44,  1.41it/s]

[430/1000]
EN: United States government shutdown causes forty-three day travel chaos.
MNI_MTEI: ꯌꯨꯅꯥꯏꯇꯦꯗꯁ ꯒꯕꯔꯃꯦꯟꯇ ꯁꯇꯗꯟ ꯇꯧꯕꯅꯥ ꯅꯨꯃꯤꯠ ꯃꯔꯤ - ꯑꯍꯨꯝꯒꯤ ꯂꯝꯀꯣꯏꯕꯒꯤ ꯑꯋꯥꯕ ꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  43%|███████████▋               | 431/1000 [06:05<06:54,  1.37it/s]

[431/1000]
EN: Government considers hotel industry infrastructure status for tax benefits.
MNI_MTEI: ꯁꯔꯀꯥꯔꯅꯥ ꯇꯦꯛꯁ ꯕꯦꯅꯤꯐꯤꯇꯁꯤꯡꯒꯤꯗꯃꯛ ꯍꯣꯇꯦꯜ ꯏꯟꯗꯁꯇꯒꯤ ꯏꯟꯐꯁꯇ ꯭ ꯔꯛꯆꯔꯇꯦꯁ ꯈꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  43%|███████████▋               | 432/1000 [06:06<06:57,  1.36it/s]

[432/1000]
EN: Gajendra Singh Shekhawat announces infrastructure status proposal for hotels.
MNI_MTEI: ꯒꯖꯦꯟꯗ ꯁꯤꯡ ꯁꯦꯈꯥꯋꯥꯠꯅ ꯍꯣꯇꯦꯜꯁꯤꯡꯒꯤ ꯏꯟꯐꯁꯇꯛꯆꯔꯇꯦꯁꯄꯣꯖꯦꯜ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  43%|███████████▋               | 433/1000 [06:07<06:59,  1.35it/s]

[433/1000]
EN: Tourism Ministry reboots Incredible India campaign with AI focus.
MNI_MTEI: ꯇꯨꯔꯤꯖꯝ ꯃꯟꯇꯅꯥ ꯑꯦꯑꯏ ꯃꯤꯠꯌꯦꯡ ꯊꯝꯕꯥ ꯏꯟꯀꯗꯤꯕꯜ ꯏꯟꯗꯤꯌꯥ ꯀꯦꯝꯄꯦꯟ ꯔꯤꯕꯨꯇ ꯇꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  43%|███████████▋               | 434/1000 [06:07<07:15,  1.30it/s]

[434/1000]
EN: Suman Billa confirms new digital-centric Incredible India strategy.
MNI_MTEI: ꯁꯨꯃꯟ ꯕꯤꯂꯥꯅꯥ ꯑꯅꯧꯕ ꯗꯤꯖꯤꯇꯦꯜ ꯀꯦꯟꯗ ꯑꯣꯏꯕ ꯏꯟꯀꯗꯤꯕꯜ ꯏꯟꯗꯤꯌꯥꯇꯔꯦꯖꯤ ꯑꯗꯨ ꯀꯟꯐꯥꯔꯃ ꯇꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  44%|███████████▋               | 435/1000 [06:08<06:53,  1.37it/s]

[435/1000]
EN: India targets one trillion dollar tourism economy by 2047.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯐꯥꯎꯕꯗ ꯗꯣꯂꯔ ꯇꯂꯤꯌꯟ ꯑꯃ ꯇꯨꯔꯤꯖꯝ ꯑꯦꯀꯅꯣꯃꯤꯒꯤ ꯄꯥꯟꯗꯝ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  44%|███████████▊               | 436/1000 [06:09<06:51,  1.37it/s]

[436/1000]
EN: Centre sanctions fifty destinations for challenge mode tourism development.
MNI_MTEI: ꯁꯦꯟꯅꯥ ꯆꯦꯂꯦꯟꯖ ꯃꯣꯗ ꯇꯨꯔꯤꯖꯝ ꯗꯤꯚꯂꯞꯃꯦꯟꯇꯒꯤꯗꯃꯛ ꯗꯦꯁꯇꯤꯅꯦꯁꯟ ꯃꯉꯥ ꯌꯥꯍꯟ
--------------------------------------------------

Translating:  44%|███████████▊               | 437/1000 [06:09<06:43,  1.40it/s]

[437/1000]
EN: Telangana adopts Sarathi portal for online RTA services.
MNI_MTEI: ꯇꯦꯂꯪꯒꯥꯅꯥꯅꯥ ꯑꯣꯟꯂꯥꯏꯟ ꯑꯥꯔꯇꯤꯑꯦ ꯁꯔꯕꯤꯁꯁꯤꯡꯒꯤꯗꯃꯛ ꯁꯥꯔꯥꯊꯤ ꯄꯣꯔꯇꯦꯜ ꯂꯧ
--------------------------------------------------

Translating:  44%|███████████▊               | 438/1000 [06:10<06:29,  1.44it/s]

[438/1000]
EN: Ministry announces twelve thousand crore rupees for new tourism destinations.
MNI_MTEI: ꯃꯟꯇꯅꯥ ꯑꯅꯧꯕ ꯇꯨꯔꯤꯖꯝ ꯗꯦꯁꯇꯤꯅꯦꯁꯟꯁꯤꯡꯒꯤꯗꯃꯛ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯂꯤꯁꯤꯡ ꯇꯔꯥꯃꯥꯖ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  44%|███████████▊               | 439/1000 [06:11<06:42,  1.39it/s]

[439/1000]
EN: Government allocates 1.34 billion dollars for tourism infrastructure development.
MNI_MTEI: ꯁꯔꯀꯥꯔꯅꯥ ꯇꯨꯔꯤꯖꯝ ꯏꯟꯐꯁꯇꯛꯆꯔ ꯗꯤꯚꯂꯞꯃꯦꯟꯇꯒꯤꯗꯃꯛ ꯗꯣꯂꯔ ꯕꯤꯂꯤꯌꯟ ꯊꯥꯖꯤꯟ
--------------------------------------------------

Translating:  44%|███████████▉               | 440/1000 [06:12<06:36,  1.41it/s]

[440/1000]
EN: India plans 2030 Commonwealth Games hosting to boost tourism.
MNI_MTEI: ꯇꯨꯔꯤꯖꯝ ꯍꯦꯟꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯚꯥꯔꯠꯅ 2030 ꯒꯤ ꯀꯃꯟꯋꯦꯜꯊ ꯒꯦꯝꯁ ꯄꯥꯡꯊꯣꯛꯅꯕ ꯊꯧꯔꯥꯡ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  44%|███████████▉               | 441/1000 [06:12<06:43,  1.38it/s]

[441/1000]
EN: Census self-enumeration trial begins for digital population count.
MNI_MTEI: ꯗꯤꯖꯤꯇꯦꯜ ꯄꯣꯄꯨꯂꯦꯁꯟ ꯀꯥꯎꯟꯠꯀꯤ ꯁꯦꯟꯁꯁ ꯁꯦꯜꯐ- ꯑꯦꯅꯨꯃꯦꯔꯦꯁꯟꯌꯦꯜ ꯍꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  44%|███████████▉               | 442/1000 [06:13<06:44,  1.38it/s]

[442/1000]
EN: European Commission launches biometric border system awareness campaign.
MNI_MTEI: ꯌꯨꯔꯣꯄꯤꯌꯟ ꯀꯃꯤꯁꯟꯅꯥ ꯕꯥꯏꯌꯣꯃꯦꯇ ꯕꯔꯗꯔ ꯁꯤꯁꯇꯦꯝ ꯑꯦꯚꯦꯌꯔꯦꯟꯁ ꯀꯦꯝꯄꯦꯅ ꯍꯧ
--------------------------------------------------

Translating:  44%|███████████▉               | 443/1000 [06:14<06:25,  1.44it/s]

[443/1000]
EN: Non-EU travellers face new digital border checks from October.
MNI_MTEI: ꯏꯌꯨ ꯅꯠꯇꯕꯥ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯅ ꯑꯣꯛꯇꯣꯕꯔꯗꯒꯤ ꯑꯅꯧꯕ ꯗꯤꯖꯤꯇꯦꯜ ꯕꯔꯗꯔ ꯆꯦꯛꯁꯤꯡ ꯊꯦꯡꯅꯩ ꯫
--------------------------------------------------

Translating:  44%|███████████▉               | 444/1000 [06:14<06:46,  1.37it/s]

[444/1000]
EN: Dover ferry passengers register first for EU entry-exit system.
MNI_MTEI: ꯗꯣꯚꯔ ꯐꯦꯔꯤ ꯄꯦꯁꯦꯟꯖꯔꯁꯤꯡꯅꯌꯨ ꯑꯦꯟꯇꯤ-ꯑꯦꯛꯖꯤꯠ ꯁꯤꯁꯇꯦꯝꯒꯤꯗꯃꯛ ꯑꯍꯥꯟꯕꯗꯥ ꯔꯦꯖꯤꯁꯇꯔ ꯇꯧ
--------------------------------------------------

Translating:  44%|████████████               | 445/1000 [06:15<06:52,  1.34it/s]

[445/1000]
EN: Eurostar business travellers gradually included in EES rollout.
MNI_MTEI: ꯌꯨꯔꯣꯁꯇꯥꯔ ꯕꯤꯖꯤꯅꯦꯁ ꯇꯚꯦꯂꯔꯁꯤꯡ ꯑꯁꯤ ꯏ ꯏ ꯑꯦꯁ ꯔꯣꯜꯥꯎꯇꯗꯥ ꯇꯞꯅ-ꯃꯠꯇ ꯌꯥꯎ
--------------------------------------------------

Translating:  45%|████████████               | 446/1000 [06:16<06:34,  1.40it/s]

[446/1000]
EN: India extends e-visa facility to citizens of five more nations.
MNI_MTEI: ꯚꯥꯔꯠꯇꯥ ꯏ-ꯚꯤꯖꯥ ꯐꯦꯁꯤꯂꯤꯇꯤ ꯑꯁꯤ ꯂꯩꯕꯥꯛ ꯃꯉꯥꯒꯤ ꯃꯤꯌꯣꯏꯁꯤꯡꯗ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  45%|████████████               | 447/1000 [06:17<06:36,  1.39it/s]

[447/1000]
EN: Karnataka announces tourism policy targeting fifty billion dollar investment
MNI_MTEI: ꯀꯔꯅꯥꯇꯀꯥꯅꯥ ꯗꯣꯂꯔ ꯕꯤꯂꯤꯌꯟ ꯃꯉꯥꯒꯤ ꯏꯟꯚꯦꯁꯇꯃꯦꯟꯇ ꯇꯥꯔꯀꯦꯇ ꯇꯧꯕ ꯇꯨꯔꯤꯖꯝ ꯄꯣꯂꯤꯁꯤ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  45%|████████████               | 448/1000 [06:17<06:34,  1.40it/s]

[448/1000]
EN: GST Council reduces tax on hotel rooms below seven thousand five hundred rupees.
MNI_MTEI: ꯖꯤ ꯑꯦꯁ ꯇꯤ ꯀꯥꯎꯟꯁꯜꯅꯥ ꯍꯣꯇꯦꯜ ꯀꯥꯁꯤꯡꯒꯤ ꯇꯦꯛꯁ ꯑꯁꯤ ꯂꯨꯄꯥ ꯆꯥꯗꯥ ꯂꯤꯁꯤꯡ ꯃꯉꯥꯒꯤ ꯃꯈꯥꯗ ꯍꯟꯊꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  45%|████████████               | 449/1000 [06:18<06:43,  1.37it/s]

[449/1000]
EN: Ministry of Tourism launches Swadesh Darshan 3.0 for sustainable tourism.
MNI_MTEI: ꯇꯨꯔꯤꯖꯝ ꯃꯟꯇꯅꯥ ꯁꯁꯇꯦꯕꯦꯅꯤꯌꯦꯜ ꯇꯨꯔꯤꯖꯝꯒꯤꯗꯃꯛꯋꯥꯗꯦꯁ ꯗꯔꯁꯟ ꯂꯣꯆ ꯇꯧ
--------------------------------------------------

Translating:  45%|████████████▏              | 450/1000 [06:19<06:42,  1.37it/s]

[450/1000]
EN: Civil Aviation Ministry orders probe into Delhi airport assault case.
MNI_MTEI: ꯁꯤꯚꯤꯜ ꯑꯦꯚꯤꯌꯦꯁꯟ ꯃꯟꯇꯅꯥ ꯗꯤꯜꯂꯤ ꯑꯦꯌꯔꯄꯣꯔꯇ ꯑꯦꯁꯣꯂꯇ ꯀꯦꯁ ꯊꯤꯖꯤꯟꯕꯒꯤ ꯑꯣꯔꯗꯔ ꯄꯤ
--------------------------------------------------

Translating:  45%|████████████▏              | 451/1000 [06:19<06:37,  1.38it/s]

[451/1000]
EN: Government approves UDAN 5.0 with focus on helicopter services.
MNI_MTEI: ꯍꯦꯂꯤꯀꯣꯞꯇꯔ ꯁꯔꯕꯤꯁꯁꯤꯡꯗ ꯃꯤꯠꯌꯦꯡ ꯊꯝꯗꯨꯅꯥ ꯒꯚꯔꯃꯦꯟꯇꯅꯥ ꯎꯗꯥꯅ ꯑꯌꯥꯕ ꯄꯤꯔꯦ ꯫
--------------------------------------------------

Translating:  45%|████████████▏              | 452/1000 [06:20<06:33,  1.39it/s]

[452/1000]
EN: Kerala declares tourism as industry status for hotels and resorts.
MNI_MTEI: ꯀꯦꯔꯂꯥꯅꯥ ꯇꯨꯔꯤꯖꯝ ꯑꯁꯤ ꯍꯣꯇꯦꯜ ꯑꯃꯁꯨꯡ ꯔꯤꯖꯣꯔꯇꯁꯤꯡꯒꯤ ꯏꯟꯗꯁꯇꯒꯤ ꯊꯥꯛꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  45%|████████████▏              | 453/1000 [06:21<06:20,  1.44it/s]

[453/1000]
EN: West Bengal secures second rank in foreign tourist arrivals.
MNI_MTEI: ꯋꯇ ꯕꯦꯡꯒꯣꯜꯅꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯂꯝꯀꯣꯏꯕꯥ ꯂꯥꯛꯄꯥꯁꯤꯡꯒꯤ ꯃꯅꯨꯡꯗ ꯑꯅꯤ ꯁꯨꯕꯥ ꯔꯦꯡꯀ ꯐꯪ
--------------------------------------------------

Translating:  45%|████████████▎              | 454/1000 [06:22<06:28,  1.40it/s]

[454/1000]
EN: Mamata Banerjee hails West Bengal's international tourism milestone.
MNI_MTEI: ꯃꯃꯇꯥ ꯕꯦꯅꯖꯔꯤꯅꯥ ꯋꯇ ꯕꯦꯡꯒꯜꯒꯤ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯇꯨꯔꯤꯖꯝ ꯃꯥꯏꯜꯆꯣꯠꯅꯤ ꯍꯥꯏꯅ ꯊꯥꯒꯠ
--------------------------------------------------

Translating:  46%|████████████▎              | 455/1000 [06:22<06:34,  1.38it/s]

[455/1000]
EN: Maharashtra leads foreign tourist arrivals with 3.71 million visitors.
MNI_MTEI: ꯃꯍꯥꯔꯥꯁꯇꯗꯥ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈꯒ ꯂꯣꯏꯅꯅꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯇꯒꯤ ꯂꯥꯛꯄꯥ ꯂꯝꯀꯣꯏꯕꯁꯤꯡ ꯑꯁꯤ ꯃꯥꯡꯖꯤꯜ ꯊꯥ
--------------------------------------------------

Translating:  46%|████████████▎              | 456/1000 [06:23<06:31,  1.39it/s]

[456/1000]
EN: West Bengal records 3.12 million foreign tourist visits nationwide.
MNI_MTEI: ꯋꯇ ꯕꯦꯡꯒꯜꯅꯥ ꯂꯩꯕꯥꯛ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯂꯥꯛꯄꯒꯤ ꯔꯦꯀꯣꯔ
--------------------------------------------------

Translating:  46%|████████████▎              | 457/1000 [06:24<06:36,  1.37it/s]

[457/1000]
EN: Uttar Pradesh tops domestic tourism with 646.81 million visitors.
MNI_MTEI: ꯎꯠꯇꯔꯗꯥ ꯂꯝꯀꯣꯏꯕ ꯃꯤ ꯂꯥꯈ.81 ꯄꯨꯗꯨꯅ ꯗꯣꯃꯦꯁꯇꯤꯛ ꯇꯨꯔꯤꯖꯝꯗꯥ ꯃꯥꯡꯖꯤꯜ ꯊꯥ
--------------------------------------------------

Translating:  46%|████████████▎              | 458/1000 [06:24<06:24,  1.41it/s]

[458/1000]
EN: Tamil Nadu records 306.84 million domestic tourist footfall.
MNI_MTEI: ꯇꯥꯃꯤꯜ ꯅꯥꯗꯨꯗ ꯗꯣꯃꯦꯁꯇꯤꯛ ꯇꯨꯔꯤꯁꯇ ꯀꯂꯌꯟ. ꯔꯦꯀꯣꯔ ꯇꯧ
--------------------------------------------------

Translating:  46%|████████████▍              | 459/1000 [06:25<06:33,  1.37it/s]

[459/1000]
EN: India receives 2,948.19 million domestic tourists during 2024.
MNI_MTEI: ꯏꯪꯁꯣꯛ ꯒꯤ ꯃꯅꯨꯡꯗ ꯚꯥꯔꯠꯇꯥ ꯗꯣꯃꯦꯁꯇꯤꯛ ꯇꯨꯔꯤꯁꯇ ꯃꯤꯂꯌꯟꯒꯤ ꯃꯁꯤꯡ948.19 ꯐꯪ
--------------------------------------------------

Translating:  46%|████████████▍              | 460/1000 [06:26<06:29,  1.39it/s]

[460/1000]
EN: Foreign tourist visits to India touch 20.94 million in 2024.
MNI_MTEI: ꯏꯪꯁꯣꯛ ꯗꯥ ꯚꯥꯔꯠꯇꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯅ ꯂꯥꯛꯄꯥ ꯃꯁꯤꯡ ꯑꯁꯤ. ꯌꯣꯟ
--------------------------------------------------

Translating:  46%|████████████▍              | 461/1000 [06:27<06:21,  1.41it/s]

[461/1000]
EN: Domestic tourism records 17.51 percent growth over previous year.
MNI_MTEI: ꯗꯣꯃꯦꯁꯇꯤꯛ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯍꯧꯈꯤꯕ ꯆꯍꯤꯒꯥ ꯆꯥꯡꯗꯝꯅꯕꯗ ꯆꯥꯗ. ꯍꯦꯟꯒꯠꯂꯛ
--------------------------------------------------

Translating:  46%|████████████▍              | 462/1000 [06:27<06:00,  1.49it/s]

[462/1000]
EN: International tourist arrivals grow 8.84 percent in 2024.
MNI_MTEI: ꯏꯪ 2024 ꯗꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯇꯨꯔꯤꯁꯇ ꯂꯥꯛꯄꯥ ꯑꯁꯤ ꯆꯥꯗ ꯍꯦꯟꯒꯠꯂꯛꯀꯅꯤ ꯫
--------------------------------------------------

Translating:  46%|████████████▌              | 463/1000 [06:28<05:56,  1.51it/s]

[463/1000]
EN: Maha Kumbh Mela attracts 663 million visits across forty-five days.
MNI_MTEI: ꯃꯍꯥ ꯀꯨꯝꯚ ꯃꯦꯂꯥꯗꯥ ꯅꯨꯃꯤꯠ ꯃꯔꯤ - ꯃꯉꯥꯅꯤꯒꯤ ꯃꯅꯨꯡꯗ ꯃꯤ ꯂꯥꯈ ꯂꯥꯛꯄꯥ ꯂꯥꯛꯏ ꯫
--------------------------------------------------

Translating:  46%|████████████▌              | 464/1000 [06:29<06:04,  1.47it/s]

[464/1000]
EN: Prayagraj witnesses 660 million pilgrims at Sangam confluence.
MNI_MTEI: ꯄꯌꯥꯒꯔꯥꯖꯗꯥ ꯁꯡꯒꯥꯃ ꯁꯝꯐꯝꯗꯥ ꯂꯥꯏ ꯆꯠꯄꯥ ꯃꯤꯑꯣꯏ ꯂꯥꯈ ꯌꯦꯡ
--------------------------------------------------

Translating:  46%|████████████▌              | 465/1000 [06:29<06:13,  1.43it/s]

[465/1000]
EN: Vietnam welcomes 1.73 million international visitors during October 2025.
MNI_MTEI: ꯏꯪꯁꯣꯛ 2025ꯒꯤ ꯑꯣꯛꯇꯣꯕꯔ ꯊꯥꯗꯥ ꯚꯤꯇꯦꯝꯅꯥ ꯃꯤꯌꯣꯏ ꯂꯥꯈꯕꯨ ꯑꯥꯀꯥꯁꯕꯥ ꯄꯤ
--------------------------------------------------

Translating:  47%|████████████▌              | 466/1000 [06:30<06:21,  1.40it/s]

[466/1000]
EN: Vietnam records 13.8 percent monthly growth in foreign tourist arrivals.
MNI_MTEI: ꯚꯤꯇꯦꯝꯅꯥ ꯐꯣꯔꯦꯟ ꯇꯨꯔꯤꯁꯇ ꯂꯥꯛꯄꯥꯁꯤꯡꯒꯤ ꯊꯥ ꯈꯨꯗꯤꯡꯒꯤ ꯆꯥꯗ. ꯍꯦꯟꯒꯠꯂꯛꯄꯒꯤ ꯔꯦꯀꯣꯔ ꯇꯧ
--------------------------------------------------

Translating:  47%|████████████▌              | 467/1000 [06:31<06:03,  1.47it/s]

[467/1000]
EN: India attracts only ten million international tourists annually currently.
MNI_MTEI: ꯚꯥꯔꯠꯇꯥ ꯍꯧꯖꯤꯛ ꯆꯍꯤꯗꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯇꯨꯔꯤꯁꯇ ꯀꯂꯌꯟ ꯇꯔꯥ ꯈꯛꯇꯃꯛ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  47%|████████████▋              | 468/1000 [06:31<06:16,  1.41it/s]

[468/1000]
EN: France welcomes ninety million tourists against India's ten million.
MNI_MTEI: ꯐꯟꯁꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯃꯤꯌꯣꯏ ꯀꯌꯥꯒ ꯌꯦꯡꯅꯕꯗ ꯂꯝꯀꯣꯏꯕ ꯃꯤꯌꯦꯂꯟ ꯇꯔꯥꯃꯨꯛꯄꯨ ꯍꯥꯟꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  47%|████████████▋              | 469/1000 [06:32<06:00,  1.47it/s]

[469/1000]
EN: Spain receives eighty-four million international visitors annually.
MNI_MTEI: ꯁꯄꯦꯟꯗ ꯆꯍꯤꯗꯥ ꯃꯤꯌꯣꯏ ꯂꯥꯈ ꯂꯥꯛꯄꯥ ꯂꯥꯛꯏ ꯫
--------------------------------------------------

Translating:  47%|████████████▋              | 470/1000 [06:33<05:53,  1.50it/s]

[470/1000]
EN: United States hosts eighty million foreign tourists every year.
MNI_MTEI: ꯌꯨꯅꯥꯏꯇꯦꯠꯁꯇ ꯆꯍꯤ ꯈꯨꯗꯤꯡꯒꯤ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ 80 ꯂꯥꯛꯏ ꯫
--------------------------------------------------

Translating:  47%|████████████▋              | 471/1000 [06:33<05:36,  1.57it/s]

[471/1000]
EN: India's pre-Covid tourist arrival figures remain unmatched after six years.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ-ꯀꯣꯕꯤꯗ ꯂꯝꯀꯣꯏꯕꯥ ꯂꯥꯛꯄꯥ ꯃꯁꯤꯡ ꯑꯁꯤ ꯆꯍꯤ ꯇꯔꯨꯛꯀꯤ ꯃꯇꯨꯡꯗꯁꯨ ꯃꯥꯟꯅ
--------------------------------------------------

Translating:  47%|████████████▋              | 472/1000 [06:34<05:22,  1.64it/s]

[472/1000]
EN: Tourism contributes 5.2 percent to India's current GDP.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯍꯧꯖꯤꯛ ꯂꯩꯔꯤꯕ ꯖꯤꯗꯤꯄꯤꯗꯥ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯆꯥꯗ ꯁꯔꯨꯛ ꯄꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  47%|████████████▊              | 473/1000 [06:35<05:49,  1.51it/s]

[473/1000]
EN: Tourism sector supports 84 million livelihoods across India.
MNI_MTEI: ꯇꯨꯔꯤꯖꯝ ꯁꯦꯛꯇꯔꯅ ꯚꯥꯔꯠ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯍꯤꯡꯐꯝ ꯂꯥꯈ ꯁꯧꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  47%|████████████▊              | 474/1000 [06:35<06:07,  1.43it/s]

[474/1000]
EN: FICCI predicts 250 billion dollar tourism opportunity by 2030.
MNI_MTEI: ꯐꯤꯆꯤꯑꯥꯏꯅꯥ ꯐꯥꯎꯕꯗ ꯗꯣꯂꯔ ꯕꯤꯂꯤꯌꯟ ꯇꯨꯔꯤꯖꯝꯒꯤ ꯈꯨꯗꯣꯡꯆꯥꯕꯥ ꯐꯪꯒꯅꯤ ꯍꯥꯏꯅ ꯄꯥꯅꯔꯤ ꯫
--------------------------------------------------

Translating:  48%|████████████▊              | 475/1000 [06:36<06:23,  1.37it/s]

[475/1000]
EN: ICRA reports hotel demand to exceed supply in coming years.
MNI_MTEI: ꯂꯥꯛꯀꯗꯧꯔꯤꯕ ꯆꯍꯤꯁꯤꯡ ꯑꯁꯤꯗ ꯍꯣꯇꯦꯜ ꯗꯤꯃꯥꯟꯗꯅ ꯁꯄꯂꯥꯏꯗꯒꯤ ꯍꯦꯟꯒꯅꯤ ꯍꯥꯏꯅ ꯑꯥꯏ ꯁꯤ ꯑꯥꯔ ꯑꯦꯅꯥ ꯔꯤꯄꯣꯔꯇ ꯇꯧ
--------------------------------------------------

Translating:  48%|████████████▊              | 476/1000 [06:37<06:28,  1.35it/s]

[476/1000]
EN: Global travel industry generates 10.9 trillion dollars for economies.
MNI_MTEI: ꯒ ꯭ ꯂꯣꯕꯦꯜꯚꯦꯜ ꯏꯟꯗꯁꯇꯅꯥ ꯗꯣꯂꯔ ꯇꯂꯤꯌꯟ ꯏꯀꯣꯅꯣꯃꯤꯁꯁꯤꯡ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  48%|████████████▉              | 477/1000 [06:38<06:00,  1.45it/s]

[477/1000]
EN: Travel and tourism accounts for ten percent of global GDP.
MNI_MTEI: ꯂꯝꯀꯣꯏꯕ ꯑꯃꯁꯨꯡ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯃꯥꯂꯦꯝꯒꯤ ꯖꯤꯗꯤꯄꯤꯗꯥ ꯆꯥꯗ ꯇꯔꯥ ꯑꯣꯏ
--------------------------------------------------

Translating:  48%|████████████▉              | 478/1000 [06:38<06:18,  1.38it/s]

[478/1000]
EN: Vietnam targets 22 to 26 million international visitors by 2026.
MNI_MTEI: ꯚꯤꯇꯦꯝꯅꯥ ꯏꯪꯁꯣꯛ 2026 ꯐꯥꯎꯕꯗ ꯃꯥꯂꯦꯝꯒꯤ ꯑꯣꯏꯕ ꯂꯝꯀꯣꯏꯕ ꯃꯤꯌꯣꯏꯗꯒꯤ ꯐꯥꯎꯕ ꯂꯥꯛꯀꯗꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  48%|████████████▉              | 479/1000 [06:39<06:29,  1.34it/s]

[479/1000]
EN: Belgium citizens enjoy forty-five day visa-free Vietnam travel.
MNI_MTEI: ꯕꯦꯂꯖꯤꯌꯝꯒꯤ ꯃꯤꯌꯣꯏꯁꯤꯡꯅ ꯅꯨꯃꯤꯠ ꯃꯔꯤ - ꯃꯉꯥꯅꯤꯒꯤ ꯚꯤꯖꯥ ꯌꯥꯎꯗꯕꯥ ꯚꯤꯇꯦꯝ ꯇꯚꯦꯜꯒꯤ ꯅꯨꯡꯉꯥꯏꯕꯥ ꯐꯪ
--------------------------------------------------

Translating:  48%|████████████▉              | 480/1000 [06:40<06:53,  1.26it/s]

[480/1000]
EN: Poland nationals receive visa-free entry to Vietnam under new scheme.
MNI_MTEI: ꯄꯣꯂꯦꯟꯗ ꯅꯦꯁꯇꯤꯅꯦꯁꯟꯅ ꯚꯤꯇꯦꯅꯥꯝꯗꯥ ꯑꯅꯧꯕꯀꯤꯝ ꯃꯈꯥꯗ ꯚꯤꯖꯥ-ꯐ ꯑꯦꯟꯔꯤ ꯐꯪ
--------------------------------------------------

Translating:  48%|████████████▉              | 481/1000 [06:41<06:58,  1.24it/s]

[481/1000]
EN: Swiss passport holders travel visa-free to Vietnam for forty-five days.
MNI_MTEI: ꯁ ꯄꯥꯁꯄꯣꯔꯇ ꯂꯩꯕ ꯃꯤꯑꯣꯏꯁꯤꯡꯅ ꯚꯤꯇꯦꯅꯥꯝꯗꯥ ꯅꯨꯃꯤꯠ ꯃꯔꯤ - ꯃꯉꯥꯅꯤ ꯚꯤꯖꯥ ꯌꯥꯎꯗꯅ ꯆꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  48%|█████████████              | 482/1000 [06:42<06:36,  1.31it/s]

[482/1000]
EN: Saudi Red Sea Authority issues twelve marine tourism licences.
MNI_MTEI: ꯁꯧꯗꯤ ꯔꯦꯗ ꯁꯤ ꯑꯣꯊꯣꯔꯤꯇꯤꯅꯥ ꯃꯦꯔꯤꯅ ꯇꯨꯔꯤꯖꯝ ꯂꯥꯏꯁꯦꯟꯁ ꯇꯔꯥꯃꯥꯖ ꯄꯤ
--------------------------------------------------

Translating:  48%|█████████████              | 483/1000 [06:42<06:12,  1.39it/s]

[483/1000]
EN: Red Sea Cruises receives approval under Cruise Saudi brand.
MNI_MTEI: ꯁꯥꯎꯗꯤ ꯕꯦꯟꯗꯀꯤ ꯃꯈꯥꯗ ꯔꯦꯗ ꯁꯤ ꯀꯨꯏꯖꯁꯅ ꯑꯌꯥꯕ ꯐꯪ
--------------------------------------------------

Translating:  48%|█████████████              | 484/1000 [06:43<06:20,  1.36it/s]

[484/1000]
EN: Sindalah Marina in NEOM secures Saudi marine tourism licence.
MNI_MTEI: ꯅꯤꯑꯣꯑꯦꯝꯗꯥ ꯂꯩꯕ ꯁꯤꯟꯗꯂꯥꯍ ꯃꯦꯔꯤꯅꯥꯅꯥ ꯁꯧꯗꯤ ꯃꯦꯔꯤꯅ ꯇꯨꯔꯤꯖꯝ ꯂꯥꯏꯁꯦꯟꯁ ꯐꯪ
--------------------------------------------------

Translating:  48%|█████████████              | 485/1000 [06:44<07:25,  1.16it/s]

[485/1000]
EN: Dolphin Beach Resort Marina obtains Yanbu operating approval.
MNI_MTEI: ꯗꯣꯜꯐꯤꯅ ꯕꯤꯆ ꯔꯤꯖꯣꯔꯇ ꯃꯦꯔꯤꯅꯥꯗꯥ ꯌꯥꯟꯕꯨ ꯑꯣꯄꯔꯦꯇꯤꯡ ꯑꯦꯄꯂꯨꯑꯦꯁꯟ ꯐꯪ
--------------------------------------------------

Translating:  49%|█████████████              | 486/1000 [06:45<07:36,  1.13it/s]

[486/1000]
EN: Jeddah Municipality Marina included in Saudi licensing round.
MNI_MTEI: ꯖꯦꯗꯥꯍ ꯃꯅꯤꯁꯤꯄꯥꯂꯤꯇꯤ ꯃꯦꯔꯤꯅꯥ ꯑꯁꯤ ꯁꯥꯎꯗꯤ ꯂꯥꯏꯁꯦꯟꯁꯤꯡ ꯔꯥꯎꯟꯗꯗꯥ ꯌꯥꯎ
--------------------------------------------------

Translating:  49%|█████████████▏             | 487/1000 [06:46<07:47,  1.10it/s]

[487/1000]
EN: Deep Seas Shipping Agency gains tourism shipping agent licence.
MNI_MTEI: ꯗꯤꯄ ꯁꯤꯖ ꯁꯤꯞꯄꯤꯡ ꯑꯦꯖꯦꯟꯁꯤꯅ ꯇꯨꯔꯤꯖꯝ ꯁꯤꯞꯇ ꯑꯦꯖꯦꯟꯇ ꯂꯥꯏꯁꯦꯟꯁ ꯐꯪ
--------------------------------------------------

Translating:  49%|█████████████▏             | 488/1000 [06:47<07:37,  1.12it/s]

[488/1000]
EN: Venice extends day-tripper entrance fee to sixty days.
MNI_MTEI: ꯋꯦꯅꯤꯁꯅꯥ ꯗꯦ-ꯥꯏꯄꯔ ꯑꯦꯟꯇꯔꯦꯟꯁ ꯐꯤ ꯑꯁꯤ ꯅꯨꯃꯤꯠ ꯆꯥꯗꯥ ꯍꯦꯟꯒꯠ
--------------------------------------------------

Translating:  49%|█████████████▏             | 489/1000 [06:48<08:00,  1.06it/s]

[489/1000]
EN: Venice charges day-trippers from Friday to Sunday between April and July.
MNI_MTEI: ꯚꯤꯅꯤꯁꯅꯥ ꯑꯦꯄꯜ ꯑꯃꯁꯨꯡ ꯖꯨꯂꯥꯏꯒꯤ ꯃꯔꯛꯇ ꯁꯨꯈ ꯅꯨꯃꯤꯠꯇꯗꯒꯤ ꯅꯣꯡꯃꯥꯏꯖꯤꯡ ꯐꯥꯎꯕ ꯗꯦ-ꯇꯄꯤꯄꯔꯁꯤꯡ ꯂꯧꯏ ꯫
--------------------------------------------------

Translating:  49%|█████████████▏             | 490/1000 [06:49<08:12,  1.04it/s]

[490/1000]
EN: Simone Venturini calls Venice entry fee tangible innovation tool.
MNI_MTEI: ꯁꯤꯃꯣꯟ ꯚꯦꯟꯇꯨꯔꯤꯅꯤꯅ ꯚꯦꯅꯤꯁ ꯑꯦꯟ ꯐꯤ ꯇꯦꯟꯖꯤꯕꯜ ꯏꯟꯅꯣꯚꯦꯁꯟ ꯇꯨꯜ ꯍꯥꯏꯅ ꯀꯧ
--------------------------------------------------

Translating:  49%|█████████████▎             | 491/1000 [06:50<08:05,  1.05it/s]

[491/1000]
EN: Amsterdam introduces tourist fees to fight overtourism congestion.
MNI_MTEI: ꯑꯝꯁꯇꯔꯗꯝꯅꯥ ꯑꯣꯚꯔꯇꯨꯔꯤꯖꯝ ꯀꯟꯖꯦꯁꯟ ꯊꯦꯡꯅꯅꯕ ꯇꯨꯔꯤꯁꯇ ꯐꯤ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  49%|█████████████▎             | 492/1000 [06:51<08:14,  1.03it/s]

[492/1000]
EN: Greece passes laws limiting visitor numbers to popular islands.
MNI_MTEI: ꯒꯅꯥ ꯃꯤꯌꯥꯝꯅ ꯄꯥꯝꯅꯕ ꯏꯊꯠꯁꯤꯡ ꯑꯁꯤꯗ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯃꯁꯤꯡ ꯍꯟꯊꯍꯟꯅꯕ ꯑꯥꯏꯟꯁꯤꯡ ꯆꯠꯅꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  49%|█████████████▎             | 493/1000 [06:52<07:48,  1.08it/s]

[493/1000]
EN: Japan implements tourist fees to manage overcrowding at sites.
MNI_MTEI: ꯖꯄꯥꯟꯅꯥ ꯁꯥꯏꯇꯁꯤꯡꯗ ꯃꯤ ꯌꯥꯝꯅ ꯇꯤꯟꯕ ꯂꯥꯛꯅꯕꯒꯤꯗꯃꯛ ꯇꯨꯔꯤꯁꯇ ꯐꯤꯁꯤꯡ ꯆꯠꯅꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  49%|█████████████▎             | 494/1000 [06:53<08:13,  1.02it/s]

[494/1000]
EN: Hurricane Melissa devastates Jamaica's tourism infrastructure.
MNI_MTEI: ꯍꯔꯤꯀꯦꯟ ꯃꯦꯂꯤꯁꯥꯅꯥ ꯖꯃꯥꯏꯀꯥꯒꯤ ꯇꯨꯔꯤꯖꯝ ꯏꯟꯐꯁꯇꯛꯆꯔ ꯃꯥꯡꯍꯟ ꯇꯥꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  50%|█████████████▎             | 495/1000 [06:54<08:42,  1.04s/it]

[495/1000]
EN: Jamaica opens for business after Hurricane Melissa recovery.
MNI_MTEI: ꯖꯃꯥꯏꯀꯥ ꯑꯁꯤ ꯍꯔꯤꯀꯦꯟ ꯃꯦꯂꯤꯁꯥ ꯔꯤꯀꯥꯎꯔꯤꯒꯤ ꯃꯇꯨꯡꯗ ꯂꯂꯣꯟ-ꯎꯕꯒꯤꯗꯃꯛꯇ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  50%|█████████████▍             | 496/1000 [06:55<07:46,  1.08it/s]

[496/1000]
EN: Canadian visitation to United States continues to plummet.
MNI_MTEI: ꯌꯨꯅꯥꯏꯇꯦꯗꯇꯥ ꯀꯦꯅꯥꯗꯥꯒꯤ ꯈꯣꯡꯆꯠ ꯑꯁꯤ ꯃꯈꯥ ꯇꯥꯅ ꯍꯟꯊꯔꯛ
--------------------------------------------------

Translating:  50%|█████████████▍             | 497/1000 [06:55<07:36,  1.10it/s]

[497/1000]
EN: Sean Duffy focuses on America's ailing air travel system.
MNI_MTEI: ꯁꯤꯅ ꯗꯐꯤꯅꯥ ꯑꯃꯦꯔꯤꯀꯥꯒꯤ ꯂꯥꯏꯔꯕ ꯑꯦꯔꯚꯦꯜ ꯁꯤꯁꯇꯦꯝꯗꯥ ꯃꯤꯠꯌꯦꯡ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  50%|█████████████▍             | 498/1000 [06:57<08:23,  1.00s/it]

[498/1000]
EN: Trump administration policies impact travel both positively and negatively.
MNI_MTEI: ꯇꯝꯞ ꯑꯦꯗꯃꯤꯅꯤꯁꯇꯦꯁꯟꯒꯤ ꯄꯣꯂꯤꯁꯤꯁꯤꯡꯅ ꯄꯣꯖꯤꯇꯤꯕ ꯑꯃꯁꯨꯡ ꯅꯦꯒꯦꯇꯤꯕ ꯑꯅꯤꯃꯛꯀꯤ ꯑꯣꯏꯕ ꯂꯝꯀꯣꯏꯕꯒꯤ ꯏꯊꯤꯜ ꯄꯤ ꯫
--------------------------------------------------

Translating:  50%|█████████████▍             | 499/1000 [06:58<08:25,  1.01s/it]

[499/1000]
EN: Sri Lanka regime change attributed to poor governance by Ajit Doval.
MNI_MTEI: ꯂꯡꯀꯥꯒꯤ ꯂꯩꯉꯥꯛ ꯍꯣꯡꯂꯛꯄꯥ ꯑꯁꯤ ꯑꯖꯤꯠ ꯗꯣꯚꯜꯒꯤ ꯂꯥꯏꯔꯕ ꯒꯕꯔꯅꯦꯟꯁꯅꯥ ꯃꯔꯝ ꯑꯣꯏ
--------------------------------------------------

Translating:  50%|█████████████▌             | 500/1000 [06:59<08:22,  1.00s/it]

[500/1000]
EN: Bangladesh leadership transition results from poor governance failures.
MNI_MTEI: ꯕꯪꯒꯂꯥꯗꯦꯁꯀꯤ ꯂꯨꯆꯤꯡꯕꯒꯤ ꯍꯣꯡꯗꯣꯛꯄꯒꯤ ꯃꯍꯩ ꯑꯁꯤ ꯂꯥꯏꯔꯕ ꯒꯕꯔꯅꯦꯟꯁ ꯃꯥꯏꯊꯤꯕꯥꯁꯤꯡꯗꯒꯤꯅꯤ ꯫
--------------------------------------------------

Translating:  50%|█████████████▌             | 501/1000 [07:00<08:05,  1.03it/s]

[501/1000]
EN: Nepal government change linked to governance issues says Doval.
MNI_MTEI: ꯅꯦꯄꯥꯜ ꯁꯔꯀꯥꯔꯅꯥ ꯒꯕꯔꯅꯦꯟꯁ ꯏꯁꯁꯤꯡꯒ ꯃꯔꯤ ꯂꯩꯅꯅ ꯍꯣꯡꯂꯛꯏ ꯍꯥꯏꯅ ꯗꯣꯚꯥꯂꯅꯥ ꯍꯥꯏ ꯫
--------------------------------------------------

Translating:  50%|█████████████▌             | 502/1000 [07:01<07:59,  1.04it/s]

[502/1000]
EN: Thailand launches five year multiple entry tourist visa scheme.
MNI_MTEI: ꯊꯥꯏꯂꯦꯟꯗꯅꯥ ꯆꯍꯤ ꯃꯉꯥꯒꯤ ꯃꯜꯇꯤꯄꯜ ꯑꯦꯟꯇ ꯇꯨꯔꯤꯁꯇ ꯚꯤꯖꯥꯀꯤꯝ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  50%|█████████████▌             | 503/1000 [07:01<07:14,  1.14it/s]

[503/1000]
EN: Sri Lanka grants free visa to seven countries including India.
MNI_MTEI: ꯁꯔꯤꯂꯪꯀꯥꯅꯥ ꯚꯥꯔꯠ ꯌꯥꯎꯅ ꯂꯩꯕꯥꯛ 7ꯇꯥ ꯐ ꯚꯤꯖꯥ ꯄꯤ ꯫
--------------------------------------------------

Translating:  50%|█████████████▌             | 504/1000 [07:02<07:33,  1.09it/s]

[504/1000]
EN: Maldives lifts emergency but tourism recovery remains sluggish.
MNI_MTEI: ꯃꯜꯗꯤꯚꯦꯁꯅ ꯏꯃꯔꯖꯦꯟꯁꯤ ꯂꯧꯊꯣꯛꯈꯤ ꯑꯗꯨꯕꯨ ꯇꯨꯔꯤꯖꯝ ꯔꯤꯀꯥꯎꯔꯤ ꯑꯁꯤ ꯁꯣꯠꯊ
--------------------------------------------------

Translating:  50%|█████████████▋             | 505/1000 [07:03<07:43,  1.07it/s]

[505/1000]
EN: UAE announces five year multiple entry visa for Indian nationals.
MNI_MTEI: ꯌꯨ ꯑꯦ ꯏ ꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯅꯦꯁ ꯭ ꯅꯦꯜꯁꯤꯡꯒꯤꯗꯃꯛ ꯆꯍꯤ ꯃꯉꯥꯒꯤ ꯃꯜꯇꯤꯄꯜ ꯑꯦꯟꯇꯤ ꯚꯤꯖꯥ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  51%|█████████████▋             | 506/1000 [07:04<07:26,  1.11it/s]

[506/1000]
EN: Schengen visa fees increase from eighty to ninety Euros globally.
MNI_MTEI: ꯁꯆꯦꯟꯖꯦꯟ ꯚꯤꯖꯥ ꯐꯤ ꯑꯁꯤ ꯃꯥꯂꯦꯝ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯌꯨꯔꯣ 80ꯗꯒꯤ 90 ꯐꯥꯎꯕ ꯍꯦꯟꯒꯠ
--------------------------------------------------

Translating:  51%|█████████████▋             | 507/1000 [07:05<07:36,  1.08it/s]

[507/1000]
EN: Japan resumes short term tourist visa processing for Indians.
MNI_MTEI: ꯖꯄꯥꯟꯅꯥ ꯚꯥꯔꯠ ꯃꯆꯥꯁꯤꯡꯒꯤꯗꯃꯛ ꯃꯇꯝ ꯈꯔꯒꯤ ꯑꯣꯏꯕ ꯇꯨꯔꯤꯁꯇ ꯚꯤꯖꯥꯁꯦꯁꯡ ꯑꯃꯨꯛ ꯍꯟꯅ ꯍꯧ
--------------------------------------------------

Translating:  51%|█████████████▋             | 508/1000 [07:06<07:48,  1.05it/s]

[508/1000]
EN: India operates 127 airports with ten new cruise terminals.
MNI_MTEI: ꯚꯥꯔꯠꯇꯥ ꯑꯦꯔꯄꯣꯔꯇ ꯑꯁꯤ ꯑꯅꯧꯕ ꯀꯖ ꯇꯔꯃꯤꯅꯦꯜ ꯇꯔꯥꯒꯥ ꯂꯣꯏꯅꯅ ꯑꯣꯄꯔꯦꯇ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  51%|█████████████▋             | 509/1000 [07:07<07:00,  1.17it/s]

[509/1000]
EN: Government constructs 150,000 kilometres of new national highways.
MNI_MTEI: ꯁꯔꯀꯥꯔꯅꯥ ꯑꯅꯧꯕ ꯅꯦꯁꯅꯦꯜ ꯍꯥꯏꯋꯦꯁꯤꯡꯒꯤ ꯀꯤꯂꯣꯃꯤꯇꯔ 150,000 ꯁꯦꯝꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  51%|█████████████▊             | 510/1000 [07:07<06:50,  1.19it/s]

[510/1000]
EN: India develops 38 national waterways for inland cruise tourism.
MNI_MTEI: ꯏꯟꯗꯤꯌꯥꯅꯥ ꯏꯟꯂꯦꯟꯗ ꯀꯖ ꯇꯨꯔꯤꯖꯝꯒꯤꯗꯃꯛ ꯅꯦꯁꯅꯦꯜ ꯋꯥꯇꯔꯋꯦ 38 ꯁꯦꯝꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  51%|█████████████▊             | 511/1000 [07:08<06:53,  1.18it/s]

[511/1000]
EN: Metro rail network expands 10,000 kilometres across 23 cities.
MNI_MTEI: ꯃꯦꯇ ꯔꯦꯜ ꯅꯦꯠꯋꯥꯔꯛꯅꯥ ꯁꯍꯔ 23ꯗꯥ ꯀꯤꯂꯣꯃꯤꯇꯔ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  51%|█████████████▊             | 512/1000 [07:09<06:43,  1.21it/s]

[512/1000]
EN: Swadesh Darshan 2.0 develops tourism sites to global standards.
MNI_MTEI: ꯋꯥꯗꯦꯁ ꯗꯔꯁꯟ 2.ꯅ ꯂꯝꯀꯣꯏꯕꯒꯤ ꯃꯐꯝꯁꯤꯡꯕꯨ ꯃꯥꯂꯦꯝꯒꯤ ꯊꯥꯛꯇ ꯁꯦꯝꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  51%|█████████████▊             | 513/1000 [07:10<07:27,  1.09it/s]

[513/1000]
EN: PRASHAD scheme enhances pilgrimage tourism infrastructure across India.
MNI_MTEI: ꯄꯁꯥꯗꯀꯤꯝꯅꯥ ꯚꯥꯔꯠ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯊꯔꯤꯊꯝ ꯇꯨꯔꯤꯖꯝ ꯏꯟꯐꯁꯇꯛꯆꯔ ꯍꯦꯟꯒꯠꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  51%|█████████████▉             | 514/1000 [07:11<07:53,  1.03it/s]

[514/1000]
EN: Saudi Red Sea authority enforces international safety standards for marine tourism.
MNI_MTEI: ꯁꯧꯗꯤ ꯔꯦꯗ ꯁꯤ ꯑꯣꯊꯣꯔꯤꯇꯤꯅꯥ ꯃꯦꯔꯤꯅ ꯇꯨꯔꯤꯖꯝꯒꯤꯗꯃꯛ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯁꯦꯐꯇꯤꯦꯟꯗꯗꯔꯁꯤꯡ ꯆꯠꯅꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  52%|█████████████▉             | 515/1000 [07:12<07:46,  1.04it/s]

[515/1000]
EN: Saudi marine regulations protect Red Sea coral reef ecosystems.
MNI_MTEI: ꯁꯥꯎꯗꯤ ꯃꯦꯔꯤꯅ ꯔꯦꯒꯨꯂꯦꯁꯟꯅꯥ ꯔꯦꯗ ꯁꯤ ꯀꯣꯔꯦꯜ ꯔꯤꯐ ꯏꯀꯣꯁꯇꯤꯃꯁꯤꯡꯕꯨ ꯉꯥꯛꯁꯦꯟ
--------------------------------------------------

Translating:  52%|█████████████▉             | 516/1000 [07:13<07:42,  1.05it/s]

[516/1000]
EN: Saudi Red Sea tourism to add 85 billion riyals to GDP.
MNI_MTEI: ꯁꯥꯎꯗꯤ ꯔꯦꯗ ꯁꯤ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯖꯤꯗꯤꯄꯤꯗꯥ ꯔꯤꯌꯥꯜ ꯕꯤꯂꯤꯌꯟ 85 ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  52%|█████████████▉             | 517/1000 [07:14<07:15,  1.11it/s]

[517/1000]
EN: Red Sea tourism creates 210,000 Saudi jobs by 2030.
MNI_MTEI: ꯔꯦꯗ ꯁꯤ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯏꯪ 2030 ꯐꯥꯎꯕꯗ ꯁꯧꯗꯤꯒꯤ ꯊꯕꯛ 2,00,000 ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  52%|█████████████▉             | 518/1000 [07:15<07:12,  1.11it/s]

[518/1000]
EN: Indian Railways recovers only fraction of 4,087 crore dues.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟ ꯔꯦꯜꯋꯦꯁꯅ ꯁꯦꯟꯐꯝ ꯀꯔꯣꯔꯒꯤ ꯁꯔꯨꯛ ꯈꯔꯈꯛꯇꯃꯛ ꯔꯤꯀꯣꯚꯔ ꯇꯧ
--------------------------------------------------

Translating:  52%|██████████████             | 519/1000 [07:16<07:40,  1.05it/s]

[519/1000]
EN: RLDA develops only fraction of railway land for commercial use.
MNI_MTEI: ꯑꯥꯔ. ꯑꯦꯜ. ꯗꯤ. ꯑꯦ.ꯅꯥ ꯔꯦꯜꯋꯦꯒꯤ ꯂꯝꯒꯤ ꯁꯔꯨꯛ ꯈꯔꯈꯛꯇꯃꯛ ꯂꯜꯂꯣꯟꯏꯇꯤꯛꯀꯤ ꯑꯣꯏꯅ ꯁꯤꯖꯤꯟꯅꯅꯕꯒꯤꯗꯃꯛ ꯁꯦꯝꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  52%|██████████████             | 520/1000 [07:17<07:43,  1.04it/s]

[520/1000]
EN: Central Railway announces train diversions for Dasara and Diwali.
MNI_MTEI: ꯁꯦꯟꯇꯦꯜ ꯔꯦꯜꯋꯦꯅꯥ ꯗꯥꯁꯥꯔꯥ ꯑꯃꯁꯨꯡ ꯗꯤꯋꯥꯂꯤꯒꯤꯗꯃꯛ ꯇꯔꯦꯟ ꯗꯥꯏꯚꯔꯁꯟꯁꯤꯡ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  52%|██████████████             | 521/1000 [07:18<07:34,  1.05it/s]

[521/1000]
EN: SCR cancels 69 trains due to operational requirements.
MNI_MTEI: ꯑꯣꯄꯔꯦꯁꯟꯦꯜꯒꯤ ꯃꯊꯧ ꯇꯥꯕꯒꯤ ꯃꯔꯝꯅꯥ ꯑꯦꯁ ꯁꯤ ꯑꯥꯔꯅꯥ ꯇꯦꯟ 69 ꯀꯛꯊꯠ
--------------------------------------------------

Translating:  52%|██████████████             | 522/1000 [07:19<07:56,  1.00it/s]

[522/1000]
EN: South Central Railway diverts 29 trains for festival management.
MNI_MTEI: ꯁꯥꯎꯊ ꯁꯦꯟꯇꯜ ꯔꯦꯜꯋꯦꯅꯥ ꯇꯦꯟ 29 ꯑꯁꯤ ꯐꯦꯁꯇꯤꯕꯦꯜ ꯃꯦꯟꯗꯃꯦꯟꯇꯒꯤꯗꯃꯛ ꯗꯥꯏꯚꯔꯠ ꯇꯧ
--------------------------------------------------

Translating:  52%|██████████████             | 523/1000 [07:20<07:27,  1.06it/s]

[523/1000]
EN: Indian Railways announces 18 partially cancelled train services.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟ ꯔꯦꯜꯋꯦꯁꯅ ꯁꯔꯨꯛ ꯈꯔ ꯀꯛꯊꯠꯂꯕ ꯇꯔꯦꯟ ꯁꯔꯕꯤꯁ 18 ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  52%|██████████████▏            | 524/1000 [07:21<07:32,  1.05it/s]

[524/1000]
EN: Three trains rescheduled by South Central Railway authority.
MNI_MTEI: ꯁꯥꯎꯊ ꯁꯦꯟꯦꯜ ꯔꯦꯜꯋꯦ ꯑꯣꯊꯣꯔꯤꯇꯤꯅꯥ ꯇꯦꯟ ꯑꯍꯨꯝ ꯑꯃꯨꯛ ꯍꯟꯅ ꯁꯦꯗꯜ ꯇꯧ
--------------------------------------------------

Translating:  52%|██████████████▏            | 525/1000 [07:22<07:07,  1.11it/s]

[525/1000]
EN: SCR cancels total 119 train services during peak season.
MNI_MTEI: ꯑꯦꯁ ꯁꯤ ꯑꯥꯔꯅꯥ ꯄꯤꯛ ꯁꯤꯖꯟ ꯃꯇꯝꯗ ꯑꯄꯨꯟꯕꯦꯟ ꯁꯔꯕꯤꯁ 119 ꯀꯛꯁꯤꯟ
--------------------------------------------------

Translating:  53%|██████████████▏            | 526/1000 [07:23<07:30,  1.05it/s]

[526/1000]
EN: Disney Cruise Line debuts Disney Destiny vessel in 2025.
MNI_MTEI: ꯏꯪꯁꯣꯛ 2025 ꯗꯥ ꯗꯤꯁꯅꯤ ꯀꯎꯏꯖ ꯂꯥꯏꯟꯅꯥ ꯗꯤꯖꯅꯤ ꯗꯦꯁꯇꯤꯅꯤ ꯚꯦꯁꯦꯜ ꯑꯁꯤ ꯍꯧꯒꯠꯂꯦ ꯫
--------------------------------------------------

Translating:  53%|██████████████▏            | 527/1000 [07:23<07:18,  1.08it/s]

[527/1000]
EN: Norwegian Cruise Line adds Norwegian Aqua to fleet.
MNI_MTEI: ꯅꯣꯔꯚꯦꯒꯤ ꯀꯎꯖ ꯂꯥꯏꯟꯅ ꯅꯣꯔꯕꯦꯒꯤ ꯑꯦꯀꯋꯥ ꯑꯁꯤ ꯐꯂꯤꯠꯇꯥ ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  53%|██████████████▎            | 528/1000 [07:24<06:57,  1.13it/s]

[528/1000]
EN: Royal Caribbean launches Star of the Seas cruise ship.
MNI_MTEI: ꯔꯣꯌꯦꯜ ꯀꯦꯔꯤꯕꯥꯌꯟꯅꯥ ꯁꯥꯔ ꯑꯣꯐ ꯗꯤ ꯁꯤꯖ ꯀꯖ ꯁꯤꯞ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  53%|██████████████▎            | 529/1000 [07:25<07:36,  1.03it/s]

[529/1000]
EN: Varanasi airport expands terminal to handle five million passengers.
MNI_MTEI: ꯕꯥꯔꯥꯅꯥꯁꯤ ꯑꯦꯌꯔꯄꯣꯔꯇꯅꯥ ꯇꯔꯃꯅꯦꯜ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯗꯨꯅ ꯄꯦꯁꯦꯟꯖꯔ ꯃꯤꯌꯣꯏ ꯂꯥꯈ ꯃꯉꯥ ꯍꯦꯟꯗꯜ ꯇꯧ
--------------------------------------------------

Translating:  53%|██████████████▎            | 530/1000 [07:26<07:47,  1.01it/s]

[530/1000]
EN: Kashmir Railway line reaches Baramulla for all weather connectivity.
MNI_MTEI: ꯀꯁꯃꯤꯔ ꯔꯦꯜꯋꯦ ꯂꯥꯏꯟꯅꯥ ꯕꯥꯔꯥꯃꯨꯂꯥꯗꯥ ꯑꯏꯪ-ꯑꯁꯥ ꯄꯨꯝꯅꯃꯛ ꯁꯝꯅꯕꯒꯤꯗꯃꯛ ꯌꯧꯏ ꯫
--------------------------------------------------

Translating:  53%|██████████████▎            | 531/1000 [07:28<07:54,  1.01s/it]

[531/1000]
EN: Ayodhya airport commences commercial flight operations for pilgrims.
MNI_MTEI: ꯑꯥꯌꯣꯙ ꯑꯦꯌꯔꯄꯣꯔꯇꯅꯥ ꯊꯍꯤꯠꯁꯤꯡꯒꯤꯗꯃꯛꯇ ꯀꯝꯃꯔꯁꯦꯜ ꯐꯥꯏꯇ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡ ꯍꯧ
--------------------------------------------------

Translating:  53%|██████████████▎            | 532/1000 [07:28<07:37,  1.02it/s]

[532/1000]
EN: Chennai metro phase two extension connects airport to city centre.
MNI_MTEI: ꯆꯦꯟꯅꯥꯏ ꯃꯦꯇ ꯐꯦꯖ ꯑꯅꯤꯒꯤ ꯑꯦꯛꯁꯇꯦꯟꯁꯟꯅꯥ ꯑꯦꯌꯔꯄꯣꯔꯇ ꯑꯁꯤ ꯁꯤꯇꯤ ꯁꯦꯟꯇꯔꯒꯥ ꯁꯝꯅꯩ ꯫
--------------------------------------------------

Translating:  53%|██████████████▍            | 533/1000 [07:30<07:48,  1.00s/it]

[533/1000]
EN: Mumbai Trans Harbour Link reduces travel time to Navi Mumbai airport.
MNI_MTEI: ꯃꯨꯝꯕꯥꯏ ꯇ ꯭ ꯔꯥꯟꯁ ꯍꯔꯕꯔ ꯂꯤꯡꯀꯅꯥ ꯅꯚꯤ ꯑꯦꯌꯔꯄꯣꯔꯇꯇꯥ ꯆꯠꯄꯒꯤ ꯃꯇꯝ ꯍꯟꯊꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  53%|██████████████▍            | 534/1000 [07:31<07:51,  1.01s/it]

[534/1000]
EN: Kashi Vishwanath corridor transforms pilgrimage experience in Varanasi.
MNI_MTEI: ꯀꯥꯁꯤ ꯕꯤꯁ ꯭ ꯋꯅꯥꯊ ꯀꯣꯔꯤꯗꯣꯔꯅꯥ ꯕꯥꯔꯥꯅꯁꯤꯒꯤ ꯂꯥꯏꯐꯝ ꯆꯠꯄꯒꯤ ꯃꯋꯣꯡ ꯍꯣꯡꯍꯟ
--------------------------------------------------

Translating:  54%|██████████████▍            | 535/1000 [07:31<07:35,  1.02it/s]

[535/1000]
EN: Hyatt completes acquisition of Playa Hotels and Resorts.
MNI_MTEI: ꯍꯌꯥꯇꯅꯥ ꯄꯌꯥ ꯍꯣꯇꯦꯜ ꯑꯃꯁꯨꯡ ꯔꯤꯖꯣꯔꯇꯁꯤꯡ ꯂꯧꯁꯤꯟꯕ ꯂꯣꯏꯔꯦ ꯫
--------------------------------------------------

Translating:  54%|██████████████▍            | 536/1000 [07:33<07:55,  1.03s/it]

[536/1000]
EN: Hyatt adds fifteen beachfront properties across Mexico and Jamaica.
MNI_MTEI: ꯍꯌꯥꯇꯅꯥ ꯃꯦꯛꯁꯤꯀꯣ ꯑꯃꯁꯨꯡ ꯖꯃꯥꯏꯀꯥ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯕꯤꯆ ꯐꯟꯇꯄꯥꯔꯇꯤꯁꯤꯡ ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  54%|██████████████▍            | 537/1000 [07:34<07:45,  1.01s/it]

[537/1000]
EN: Hyatt acquires Secrets La Romana in Dominican Republic.
MNI_MTEI: ꯍꯌꯥꯇꯅꯥ ꯗꯣꯃꯤꯅꯤꯀꯥꯟ ꯔꯤꯄꯕꯂꯤꯛꯀꯤ ꯁꯦꯀꯇ ꯂꯥ ꯔꯣꯃꯥꯅꯥ ꯂꯧ
--------------------------------------------------

Translating:  54%|██████████████▌            | 538/1000 [07:35<07:52,  1.02s/it]

[538/1000]
EN: Dreams La Romana joins Hyatt portfolio through Playa acquisition.
MNI_MTEI: ꯗꯃꯤꯁ ꯂꯥ ꯔꯣꯃꯥꯅꯥꯅꯥꯂꯥꯌꯥ ꯑꯦꯀꯚꯤꯖꯦꯁꯟꯒꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯍꯌꯥꯇ ꯄꯣꯔꯇꯤꯐꯣꯂꯤꯑꯣꯗꯥ ꯌꯥꯎ
--------------------------------------------------

Translating:  54%|██████████████▌            | 539/1000 [07:35<07:30,  1.02it/s]

[539/1000]
EN: Dreams Rose Hall in Montego Bay transfers to Hyatt ownership.
MNI_MTEI: ꯃꯣꯟꯇꯦꯒꯣ ꯕꯦꯗꯥ ꯂꯩꯕ ꯗꯃꯤꯁ ꯔꯣꯖ ꯍꯣꯜ ꯑꯁꯤ ꯍꯌꯥꯇ ꯑꯣꯅꯣꯔꯁꯤꯌꯦꯟꯁꯤꯇꯥ ꯍꯣꯡꯗꯣꯛ
--------------------------------------------------

Translating:  54%|██████████████▌            | 540/1000 [07:36<06:57,  1.10it/s]

[540/1000]
EN: Hyatt Vivid Playa del Carmen added to hotel collection.
MNI_MTEI: ꯍꯌꯥꯇ ꯚꯤꯚꯤꯗꯂꯥꯌ ꯗꯦꯜ ꯀꯥꯔꯃꯦꯅ ꯑꯁꯤ ꯍꯣꯇꯦꯜ ꯀꯂꯦꯀꯦꯁꯟꯗ ꯌꯥꯎꯍꯟ
--------------------------------------------------

Translating:  54%|██████████████▌            | 541/1000 [07:37<06:33,  1.17it/s]

[541/1000]
EN: Sunscape Cancun becomes Hyatt property after Playa deal.
MNI_MTEI: ꯁꯟꯁꯀꯦꯞ ꯀꯦꯟꯀꯟ ꯑꯁꯤꯌꯥ ꯗꯤꯜꯒꯤ ꯃꯇꯨꯡꯗ ꯍꯌꯥꯇꯄꯣꯔꯇꯤ ꯑꯣꯏꯔꯦ ꯫
--------------------------------------------------

Translating:  54%|██████████████▋            | 542/1000 [07:38<06:39,  1.15it/s]

[542/1000]
EN: Hotel infrastructure status unlocks private investment says Shekhawat.
MNI_MTEI: ꯁꯦꯈꯥꯋꯥꯠꯅ ꯍꯥꯏ ꯃꯗꯨꯗꯤ ꯍꯣꯇꯦꯜ ꯏꯟꯐꯁꯇꯛꯆꯔꯇꯦꯁꯁꯅꯥꯏꯚꯦꯠ ꯏꯟꯚꯦꯁꯇꯃꯦꯟꯇ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  54%|██████████████▋            | 543/1000 [07:39<06:21,  1.20it/s]

[543/1000]
EN: FICCI annual general meeting discusses tourism growth strategy.
MNI_MTEI: ꯐꯤꯆꯤꯒꯤ ꯆꯍꯤꯒꯤ ꯃꯤꯐꯝꯗꯥ ꯇꯨꯔꯤꯖꯝ ꯒꯊꯇꯦꯖꯤꯒꯤ ꯃꯇꯥꯡꯗ ꯈꯟꯅꯩ ꯫
--------------------------------------------------

Translating:  54%|██████████████▋            | 544/1000 [07:39<06:16,  1.21it/s]

[544/1000]
EN: Harsh Vardhan Agarwal highlights tourism as economic driver.
MNI_MTEI: ꯍꯔꯁ ꯕꯔꯙꯟ ꯑꯒꯔꯋꯥꯜꯅ ꯇꯨꯔꯤꯖꯝꯕꯨ ꯁꯦꯟꯊꯨꯝꯒꯤ ꯗꯥꯏꯚꯔ ꯑꯣꯏꯅ ꯃꯁꯛ ꯇꯥꯛ
--------------------------------------------------

Translating:  55%|██████████████▋            | 545/1000 [07:40<06:12,  1.22it/s]

[545/1000]
EN: Anant Goenka praises Swadesh Darshan and PRASHAD initiatives.
MNI_MTEI: ꯑꯅꯟꯇ ꯒꯣꯌꯟꯀꯥꯅꯥꯋꯥꯗꯦꯁ ꯗꯔꯁꯟ ꯑꯃꯁꯨꯡꯁꯥꯗ ꯏꯅꯤꯁꯤꯌꯦꯇꯤꯕꯁꯤꯡ ꯊꯥꯒꯠ
--------------------------------------------------

Translating:  55%|██████████████▋            | 546/1000 [07:41<06:23,  1.18it/s]

[546/1000]
EN: Indian hotel industry seeks infrastructure status for tax benefits.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯍꯣꯇꯦꯜ ꯏꯟꯗꯁꯇꯅꯥ ꯇꯦꯛꯁ ꯕꯦꯅꯤꯐꯤꯇꯁꯤꯡꯒꯤꯗꯃꯛ ꯏꯟꯐꯁꯇ ꯭ ꯔꯛꯆꯔꯇꯦꯁ ꯊꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  55%|██████████████▊            | 547/1000 [07:42<06:24,  1.18it/s]

[547/1000]
EN: Shangri-La Bengaluru hosts Chef Simone Loisi Italian culinary residency.
MNI_MTEI: ꯁꯥꯟꯒꯔꯤ-ꯂꯥ ꯕꯦꯡꯂꯨꯔꯥꯅꯥ ꯁꯦꯐ ꯁꯤꯃꯣꯅꯦ ꯂꯣꯏꯁꯤ ꯏꯇꯥꯂꯤꯌꯟꯒꯤ ꯆꯤꯛꯅꯤꯔꯤ ꯔꯦꯁꯤꯗꯦꯟꯁꯤ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  55%|██████████████▊            | 548/1000 [07:43<05:56,  1.27it/s]

[548/1000]
EN: Chef Simone Loisi brings Southern Italian cuisine to Bangalore.
MNI_MTEI: ꯁꯦꯐ ꯁꯤꯃꯣꯅꯦ ꯂꯣꯏꯁꯤꯅꯥ ꯈꯥ ꯊꯪꯕ ꯏꯇꯥꯂꯤꯒꯤ ꯆꯤꯟꯖꯥꯛꯁꯤꯡ ꯕꯦꯡꯒꯂꯣꯔꯗꯥ ꯄꯨꯔꯛ
--------------------------------------------------

Translating:  55%|██████████████▊            | 549/1000 [07:43<05:47,  1.30it/s]

[549/1000]
EN: Waterfall Ristorante Italiano chef showcases cuisine at Shangri-La.
MNI_MTEI: ꯋꯥꯇꯔꯐꯣꯜ ꯔꯤꯁꯇꯣꯔꯥꯟꯇꯦ ꯏꯇꯥꯂꯤꯌꯣ ꯁꯦꯐꯅꯥ ꯁꯥꯡ-ꯂꯥꯗꯥ ꯆꯤꯟꯖꯥꯛꯁꯤꯡ ꯎꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  55%|██████████████▊            | 550/1000 [07:44<05:56,  1.26it/s]

[550/1000]
EN: Four Seasons Bengaluru transforms for Halloween 2025 celebrations.
MNI_MTEI: ꯏꯪꯁꯣꯛ 2025 ꯒꯤ ꯍꯦꯂꯣꯋꯤꯟꯒꯤꯗꯃꯛ ꯁꯤꯖꯟꯁ ꯃꯔꯤ ꯕꯦꯡꯒꯂꯨꯔꯨ ꯇ ꯭ ꯔꯥꯟꯁꯐꯣꯔꯝ ꯇꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  55%|██████████████▉            | 551/1000 [07:45<06:02,  1.24it/s]

[551/1000]
EN: CUR8 hosts family friendly Halloween evening in Bengaluru.
MNI_MTEI: ꯁꯤꯌꯨ ꯑꯥꯔ8ꯅꯥ ꯕꯦꯡꯂꯨꯨꯔꯨꯗ ꯏꯃꯨꯡ ꯃꯅꯨꯡ ꯐꯦꯟꯗꯂꯤ ꯍꯦꯂꯣꯋꯤꯟꯒꯤ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯊꯧꯔꯝ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  55%|██████████████▉            | 552/1000 [07:46<05:36,  1.33it/s]

[552/1000]
EN: Copitas bar ranks in Asia's 50 Best Bars list.
MNI_MTEI: ꯀꯣꯄꯤꯇꯥꯁ ꯕꯥꯔ ꯑꯁꯤ ꯑꯦꯁꯤꯌꯥꯒꯤ ꯐꯕ ꯕꯥꯔꯁꯀꯤ ꯂꯤꯁꯠꯗꯥ
--------------------------------------------------

Translating:  55%|██████████████▉            | 553/1000 [07:46<05:33,  1.34it/s]

[553/1000]
EN: Four Seasons Bengaluru hosts Día de Muertos Halloween party.
MNI_MTEI: ꯁꯤꯖꯟꯁ ꯃꯔꯤ ꯕꯦꯡꯂꯨꯨꯔꯥꯅꯥ ꯗꯤꯌꯥ ꯗꯦ ꯃꯨꯔꯇꯣꯁ ꯍꯦꯂꯣꯋꯤꯅ ꯄꯥꯔꯇꯤ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  55%|██████████████▉            | 554/1000 [07:47<05:40,  1.31it/s]

[554/1000]
EN: Sheraton Hyderabad invites guests to Feast Halloween buffet.
MNI_MTEI: ꯁꯦꯔꯥꯇꯟ ꯍꯥꯏꯗꯕꯥꯗꯅ ꯃꯤꯊꯨꯡꯂꯣꯏꯁꯤꯡꯕꯨ ꯐꯦꯁꯇ ꯍꯦꯂꯣꯋꯤꯅ ꯕꯨꯐꯦꯇꯥ ꯀꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  56%|██████████████▉            | 555/1000 [07:48<05:49,  1.27it/s]

[555/1000]
EN: Chef Yugal Sharma represents North West Frontier cuisine at ITC.
MNI_MTEI: ꯁꯦꯐ ꯌꯨꯒꯜ ꯁꯔꯃꯥꯅꯥ ꯑꯥꯏ ꯇꯤ ꯁꯤ ꯗꯥ ꯅꯣꯔꯊ ꯋꯇ ꯐꯅꯇꯤꯌꯔꯒꯤ ꯆꯤꯟꯖꯥꯛꯀꯤ ꯃꯁꯛ ꯇꯥꯛ
--------------------------------------------------

Translating:  56%|███████████████            | 556/1000 [07:49<05:35,  1.32it/s]

[556/1000]
EN: Royal Afghan assistant master chef promotes rustic Indian cuisine.
MNI_MTEI: ꯔꯣꯌꯦꯜ ꯑꯐꯒꯥꯟ ꯑꯦꯁꯤꯁꯇꯦꯟꯇ ꯃꯥꯁꯇꯔ ꯁꯦꯐꯅꯥ ꯂꯩꯕꯥꯛ ꯑꯁꯤꯒꯤ ꯚꯥꯔꯠꯀꯤ ꯆꯤꯟꯖꯥꯛꯄꯨ ꯌꯣꯛꯈꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  56%|███████████████            | 557/1000 [07:50<05:45,  1.28it/s]

[557/1000]
EN: The Leela Hyderabad hosts Chef Picched three-day Thai culinary showcase.
MNI_MTEI: ꯂꯤꯂꯥ ꯍꯥꯏꯗꯕꯥꯗꯗꯥ ꯁꯦꯐ ꯄꯤꯛꯆꯇ ꯊꯥꯏꯒꯤ ꯅꯨꯃꯤꯠ ꯑꯍꯨꯝꯅꯤ ꯆꯥꯅꯅꯕ ꯆꯤꯟꯖꯥꯛꯀꯤ ꯊꯧꯔꯝ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  56%|███████████████            | 558/1000 [07:50<05:49,  1.26it/s]

[558/1000]
EN: Chef Picched Paoleng brings authentic Bangkok cuisine to Hyderabad.
MNI_MTEI: ꯁꯦꯐ ꯄꯤꯆꯗ ꯄꯥꯑꯣꯂꯦꯡꯅꯥ ꯍꯥꯏꯗꯕꯥꯗꯇꯥ ꯑꯆꯨꯝꯕ ꯕꯦꯡꯀꯣꯛꯀꯤ ꯆꯤꯟꯖꯥꯛ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  56%|███████████████            | 559/1000 [07:51<06:14,  1.18it/s]

[559/1000]
EN: Marriott Executive Apartments Bengaluru unveils Madras Kitchen restaurant.
MNI_MTEI: ꯃꯦꯔꯤꯑꯣꯇ ꯑꯦꯛꯖꯤꯀ ꯭ ꯌꯨꯇꯤꯕ ꯑꯦꯄꯥꯔꯇꯃꯦꯟꯇ ꯕꯦꯡꯂꯨꯔꯥꯅꯥ ꯃꯗꯖ ꯀꯤꯆꯟ ꯔꯦꯁꯇꯣꯔꯦꯟꯇ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  56%|███████████████            | 560/1000 [07:52<06:03,  1.21it/s]

[560/1000]
EN: Madras Kitchen pays homage to South Indian gastronomic heritage.
MNI_MTEI: ꯃꯗꯖ ꯀꯤꯆꯟꯅ ꯈꯥ ꯚꯥꯔꯠꯀꯤ ꯒꯅꯣꯃꯤꯛ ꯍꯦꯔꯤꯇꯦꯖꯗꯥ ꯏꯀꯥꯏꯈꯨꯝꯅꯕ ꯎꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  56%|███████████████▏           | 561/1000 [07:53<06:07,  1.20it/s]

[561/1000]
EN: ITC Grand Bharat chef shares Diwali festive dinner hosting tips.
MNI_MTEI: ꯑꯥꯏ ꯇꯤ ꯁꯤ ꯒꯥꯟꯗ ꯚꯥꯔꯠ ꯁꯦꯐꯅꯥ ꯗꯤꯋꯥꯂꯤ ꯐꯦꯁꯇꯤꯚ ꯗꯤꯅꯔ ꯍꯣꯁꯠ ꯇꯧꯕ ꯇꯤꯞꯁꯤꯡ ꯁꯦꯌꯔ ꯇꯧ
--------------------------------------------------

Translating:  56%|███████████████▏           | 562/1000 [07:54<06:44,  1.08it/s]

[562/1000]
EN: Marriott Executive Apartments Hyderabad celebrates Hyderabadi dessert heritage.
MNI_MTEI: ꯃꯦꯔꯤꯑꯣꯇ ꯑꯦꯛꯖꯤꯀ ꯭ ꯌꯨꯇꯤꯕ ꯑꯦꯄꯥꯔꯇꯃꯦꯟꯇ ꯍꯥꯏꯗꯕꯥꯗꯅꯥ ꯍꯦꯔꯤꯇꯦꯖ ꯑꯣꯏꯔꯕꯥ ꯍꯥꯏꯗꯦꯕꯥꯗꯤꯒꯤ ꯑꯊꯨꯝꯕꯒꯤ ꯊꯧꯔꯝ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  56%|███████████████▏           | 563/1000 [07:55<06:12,  1.17it/s]

[563/1000]
EN: 4Note culinary hot spot opens with four kitchens concept.
MNI_MTEI: 4 ꯅꯣꯇ ꯀꯨꯂꯤꯅꯔꯤ ꯍꯣꯠꯣꯠ ꯑꯁꯤ ꯀꯤꯆꯟ ꯃꯔꯤꯒꯤ ꯋꯥꯈꯜꯂꯣꯟꯒꯥ ꯂꯣꯏꯅꯅ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  56%|███████████████▏           | 564/1000 [07:56<06:06,  1.19it/s]

[564/1000]
EN: Zuma Abu Dhabi maintains global legacy restaurant standards.
MNI_MTEI: ꯖꯨꯃꯥ ꯑꯕꯨ ꯙꯥꯕꯤꯅꯥ ꯒ ꯭ ꯂꯣꯕꯦꯜ ꯂꯦꯖꯤꯁꯤ ꯔꯦꯁꯇꯣꯔꯦꯟꯇꯦꯟꯗꯗꯔꯁꯤꯡ ꯊꯝꯃꯤ ꯫
--------------------------------------------------

Translating:  56%|███████████████▎           | 565/1000 [07:56<06:00,  1.21it/s]

[565/1000]
EN: Dubai chocolate craze triggers global pistachio shortage crisis.
MNI_MTEI: ꯗꯨꯕꯥꯏ ꯆꯣꯀꯣꯂꯦꯠꯀꯤ ꯅꯨꯡꯁꯤꯠꯅ ꯃꯥꯂꯦꯝꯒꯤ ꯑꯣꯏꯅ ꯄꯤꯁꯇꯥꯆꯤꯑꯣ ꯋꯥꯠꯄꯒꯤ ꯑꯋꯥꯕ ꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  57%|███████████████▎           | 566/1000 [07:57<05:49,  1.24it/s]

[566/1000]
EN: Indian Hotels Company signs new Taj property in Lucknow.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟ ꯍꯣꯇꯦꯜꯁ ꯀꯝꯄꯅꯤꯅꯥ ꯂꯈꯅꯧꯗꯥ ꯑꯅꯧꯕ ꯇꯥꯖꯄꯣꯔꯇꯤ ꯈꯨꯠꯌꯦꯛ ꯄꯤꯁꯤꯟ
--------------------------------------------------

Translating:  57%|███████████████▎           | 567/1000 [07:58<05:51,  1.23it/s]

[567/1000]
EN: Oberoi Group announces luxury resort opening in Ranthambhore.
MNI_MTEI: ꯑꯣꯕꯦꯔꯣꯏꯨꯞꯅꯥ ꯔꯟꯊꯝꯚꯣꯔꯗꯥ ꯂꯛꯁꯔꯤ ꯔꯤꯖꯣꯔꯇ ꯍꯥꯡꯗꯣꯛꯂꯦ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  57%|███████████████▎           | 568/1000 [07:59<05:50,  1.23it/s]

[568/1000]
EN: Lemon Tree Hotels expands northeast presence with Guwahati property.
MNI_MTEI: ꯂꯤꯃꯣꯟ ꯍꯣꯇꯦꯜꯁꯤꯡ ꯑꯁꯤꯅ ꯑꯋꯥꯡ ꯅꯣꯡꯄꯣꯛꯀꯤ ꯃꯐꯝ ꯑꯁꯤ ꯒꯨꯋꯥꯍꯥꯇꯤ ꯄꯄꯔꯇꯤꯒ ꯂꯣꯏꯅꯅꯥ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  57%|███████████████▎           | 569/1000 [08:00<05:46,  1.24it/s]

[569/1000]
EN: Marriott International to open 50th property in India by 2026.
MNI_MTEI: ꯃꯦꯔꯤꯑꯣꯇ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜꯅꯥ ꯏꯪꯁꯣꯛ ꯐꯥꯎꯕꯗ ꯚꯥꯔꯠꯇꯥꯁꯨꯕꯄꯣꯔꯇꯤ ꯍꯥꯡꯗꯣꯛꯀꯅꯤ ꯫
--------------------------------------------------

Translating:  57%|███████████████▍           | 570/1000 [08:00<05:45,  1.24it/s]

[570/1000]
EN: Radisson Hotel Group targets 200 hotels across India by 2027.
MNI_MTEI: ꯔꯦꯗꯤꯁꯟ ꯍꯣꯇꯦꯜ ꯒꯨꯞꯅ ꯏꯪꯁꯣꯛ ꯐꯥꯎꯕꯗ ꯚꯥꯔꯠ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯍꯣꯇꯜꯒꯤ ꯄꯥꯟꯗꯝ ꯊꯝ
--------------------------------------------------

Translating:  57%|███████████████▍           | 571/1000 [08:01<05:45,  1.24it/s]

[571/1000]
EN: OYO announces international expansion into Vietnam and Indonesia.
MNI_MTEI: ꯑꯣꯑꯥꯏꯑꯣꯅꯥ ꯚꯤꯇꯦꯝ ꯑꯃꯁꯨꯡ ꯏꯟꯗꯣꯅꯦꯁꯤꯌꯥꯗꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜꯗ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  57%|███████████████▍           | 572/1000 [08:02<05:59,  1.19it/s]

[572/1000]
EN: MakeMyTrip partners with IHCL for exclusive holiday packages.
MNI_MTEI: ꯏꯀꯁꯤꯋꯦꯜ ꯍꯣꯂꯤꯗꯦ ꯄꯦꯀꯦꯖꯁꯤꯡꯒꯤꯗꯃꯛ ꯑꯥꯏ ꯑꯩꯆ ꯁꯤ ꯑꯦꯜꯒꯥ ꯃꯦꯛꯃꯥꯏꯞ ꯄꯥꯔꯇꯥꯅꯔꯁꯤꯡ ꯑꯣꯏ ꯫
--------------------------------------------------

Translating:  57%|███████████████▍           | 573/1000 [08:03<05:42,  1.25it/s]

[573/1000]
EN: Maha Kumbh Mela creates one million jobs for local families.
MNI_MTEI: ꯃꯍꯥ ꯀꯨꯝꯚ ꯃꯦꯂꯥꯅꯥ ꯂꯣꯀꯦꯜ ꯐꯦꯃꯤꯂꯤꯁꯤꯡꯒꯤꯗꯃꯛ ꯊꯕꯛ ꯃꯤꯌꯣꯏ ꯑꯃ ꯁꯦꯝ
--------------------------------------------------

Translating:  57%|███████████████▍           | 574/1000 [08:04<05:22,  1.32it/s]

[574/1000]
EN: Boat services at Kumbh earn families collective 30 crore rupees.
MNI_MTEI: ꯀꯨꯝꯚꯗꯥ ꯍꯤ ꯁꯔꯕꯤꯁ ꯇꯧꯕꯗꯒꯤ ꯏꯃꯨꯡ ꯃꯅꯨꯡꯅꯥ ꯑꯄꯨꯟꯕ ꯑꯣꯏꯅ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯐꯪ
--------------------------------------------------

Translating:  57%|███████████████▌           | 575/1000 [08:04<05:21,  1.32it/s]

[575/1000]
EN: The Guardian describes Prayagraj Kumbh as pop-up megacity.
MNI_MTEI: ꯗ ꯒꯥꯔꯗꯤꯌꯟꯅꯥꯌꯥꯒꯔꯥꯖ ꯀꯨꯝꯚꯕꯨ ꯄꯣꯄ-ꯑꯞ ꯃꯦꯒꯥꯁꯤꯇꯤ ꯍꯥꯏꯅ ꯇꯥꯛ
--------------------------------------------------

Translating:  58%|███████████████▌           | 576/1000 [08:05<05:04,  1.39it/s]

[576/1000]
EN: Maharashtra Economic Council reports Kumbh employment generation.
MNI_MTEI: ꯃꯍꯥꯔꯥꯁꯇ ꯑꯦꯀꯅꯣꯃꯤꯛ ꯀꯥꯎꯟꯁꯤꯜꯅ ꯀꯨꯝꯚꯒꯤ ꯊꯕꯛ ꯐꯪꯍꯟꯕꯒꯤ ꯔꯤꯄꯣꯔꯠ ꯄꯤ ꯫
--------------------------------------------------

Translating:  58%|███████████████▌           | 577/1000 [08:06<05:26,  1.30it/s]

[577/1000]
EN: FIFA Club World Cup 2025 brings global visitors to host cities.
MNI_MTEI: ꯐꯤꯐꯥ ꯀꯂꯕ ꯋꯥꯔꯂ ꯭ ꯗ ꯀꯞ 2025ꯅꯥ ꯃꯥꯂꯦꯝ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯂꯥꯛꯄꯥ ꯃꯤꯌꯣꯏꯁꯤꯡꯕꯨ ꯁꯍꯔꯁꯤꯡ ꯍꯣꯁꯠ ꯇꯧꯅꯕ ꯄꯨꯔꯛꯏ ꯫
--------------------------------------------------

Translating:  58%|███████████████▌           | 578/1000 [08:06<05:16,  1.33it/s]

[578/1000]
EN: Wimbledon 2025 witnesses global unity through international tennis.
MNI_MTEI: ꯋꯤꯝꯕꯜꯗꯟ 2025 ꯗꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯇꯦꯅꯤꯁꯀꯤ ꯈꯨꯊꯥꯡꯗꯥ ꯒ ꯭ ꯂꯣꯕꯦꯜ ꯌꯨꯅꯤꯇꯤ ꯎꯔꯦ ꯫
--------------------------------------------------

Translating:  58%|███████████████▋           | 579/1000 [08:07<05:07,  1.37it/s]

[579/1000]
EN: Sikh pilgrims receive Pakistani visas after Operation Sindoor.
MNI_MTEI: ꯁꯤꯈ ꯂꯥꯏꯅꯤꯡꯕꯁꯤꯡꯅ ꯑꯣꯄꯔꯦꯁꯟ ꯁꯤꯟꯗꯨꯔꯒꯤ ꯃꯇꯨꯡꯗ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯚꯤꯖꯥ ꯐꯪ
--------------------------------------------------

Translating:  58%|███████████████▋           | 580/1000 [08:08<05:08,  1.36it/s]

[580/1000]
EN: Harjindarpal Singh secures passport and Pakistan visa for pilgrimage.
MNI_MTEI: ꯍꯔꯖꯤꯟꯗꯔꯄꯥꯜ ꯁꯤꯡꯍꯅꯥ ꯄꯥꯁꯄꯣꯔꯇ ꯑꯃꯁꯨꯡ ꯄꯥꯀꯤꯁꯇꯥꯟꯒꯤ ꯚꯤꯖꯥ ꯐꯪ
--------------------------------------------------

Translating:  58%|███████████████▋           | 581/1000 [08:09<04:59,  1.40it/s]

[581/1000]
EN: First Sikh Jathas travel to Pakistan post visa ban reversal.
MNI_MTEI: ꯑꯍꯥꯟꯕ ꯁꯤꯈ ꯖꯥꯊꯥꯁꯤꯡꯅ ꯚꯤꯖꯥ ꯕꯦꯟ ꯔꯤꯚꯔꯁꯦꯜ ꯇꯧꯔꯕꯥ ꯃꯇꯨꯡꯗ ꯄꯥꯀꯤꯁꯇꯥꯟꯗ ꯆꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  58%|███████████████▋           | 582/1000 [08:09<05:16,  1.32it/s]

[582/1000]
EN: FIDE names World Chess Cup trophy after Viswanathan Anand.
MNI_MTEI: ꯐꯤꯗꯦꯅꯥ ꯋꯜꯗ ꯆꯦꯁ ꯀꯄ ꯇꯐꯤ ꯑꯁꯤ ꯕꯤꯁꯋꯥꯅꯥꯊꯅ ꯑꯥꯅꯟꯗꯒꯤ ꯃꯃꯤꯡ ꯂꯧꯔꯒ ꯀꯧ
--------------------------------------------------

Translating:  58%|███████████████▋           | 583/1000 [08:10<05:13,  1.33it/s]

[583/1000]
EN: Panjim hosts FIDE World Chess Cup with Anand trophy.
MNI_MTEI: ꯄꯥꯟꯖꯤꯃꯅꯥ ꯑꯥꯅꯟꯗ ꯇꯐꯤꯒꯥ ꯂꯣꯏꯅꯅ ꯐꯤꯗꯦ ꯋꯥꯔꯂ ꯭ ꯗ ꯆꯦꯁ ꯀꯄ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  58%|███████████████▊           | 584/1000 [08:11<05:05,  1.36it/s]

[584/1000]
EN: Krishna Janmashtami procession turns tragic in Ramanthapur.
MNI_MTEI: ꯀꯅꯥ ꯖꯅꯃꯁꯇꯃꯤꯒꯤ ꯈꯣꯡꯆꯠ ꯑꯁꯤ ꯔꯥꯃꯟꯊꯥꯄꯨꯔꯗꯥ ꯑꯋꯥꯕꯥ ꯑꯣꯏꯔꯦ ꯫
--------------------------------------------------

Translating:  58%|███████████████▊           | 585/1000 [08:11<04:47,  1.44it/s]

[585/1000]
EN: Ten-foot chariot touches live wire killing five devotees.
MNI_MTEI: ꯈꯣꯡꯌꯨꯡ ꯇꯔꯥꯅꯥ ꯂꯥꯏꯕ ꯋꯥꯏꯔ ꯁꯣꯛꯄꯥꯗꯥ ꯂꯥꯏꯅꯤꯡꯕꯥ ꯃꯉꯥ ꯁꯤ
--------------------------------------------------

Translating:  59%|███████████████▊           | 586/1000 [08:12<04:49,  1.43it/s]

[586/1000]
EN: Hyderabad celebrates Ganesh festival with large screen displays.
MNI_MTEI: ꯍꯥꯏꯗꯕꯥꯗꯅ ꯒꯅꯦꯁ ꯐꯦꯁꯇꯤꯕꯦꯜ ꯑꯁꯤ ꯑꯆꯧꯕꯔꯤꯅ ꯗꯤꯁꯄꯁꯤꯡꯒ ꯂꯣꯏꯅꯅ ꯄꯥꯡꯊꯣꯛꯏ ꯫
--------------------------------------------------

Translating:  59%|███████████████▊           | 587/1000 [08:13<05:00,  1.38it/s]

[587/1000]
EN: Begum Bazaar jam-packed for night long festival celebrations.
MNI_MTEI: ꯕꯦꯒꯃ ꯕꯖꯥꯔꯗꯥ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯃꯇꯝ ꯆꯨꯞꯄꯥ ꯀꯨꯝꯍꯩꯒꯤ ꯊꯧꯔꯝꯁꯤꯡ ꯄꯥꯡꯊꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯊꯥꯎ-ꯊꯣꯠꯄ
--------------------------------------------------

Translating:  59%|███████████████▉           | 588/1000 [08:14<04:48,  1.43it/s]

[588/1000]
EN: Muslim leader Sadeq Siraj organizes eye camp for community.
MNI_MTEI: ꯃꯨꯁꯂꯤꯝ ꯂꯨꯆꯤꯡꯕ ꯁꯥꯗꯦꯀ ꯁꯤꯔꯥꯖꯅ ꯀꯝꯃꯅꯤꯇꯤꯒꯤꯗꯃꯛ ꯑꯥꯏ ꯀꯦꯝꯄ ꯄꯥꯡꯊꯣꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  59%|███████████████▉           | 589/1000 [08:14<04:58,  1.38it/s]

[589/1000]
EN: Hyderabad pandals adopt traditional themes for Ganesh Chaturthi.
MNI_MTEI: ꯍꯥꯏꯗꯕꯥꯗ ꯄꯟꯗꯜꯁꯤꯡꯅꯥ ꯒꯅꯦꯁ ꯆꯇꯨꯔꯊꯤꯒꯤꯗꯃꯛ ꯆꯠꯅꯕꯤꯒꯤ ꯑꯣꯏꯕ ꯊꯤꯃꯁꯤꯡ ꯂꯧ
--------------------------------------------------

Translating:  59%|███████████████▉           | 590/1000 [08:15<04:57,  1.38it/s]

[590/1000]
EN: Shuja Ifteqari requests Chief Minister Revanth Reddy for arrangements.
MNI_MTEI: ꯁꯨꯖꯥ ꯏꯐꯇꯦꯀꯔꯤꯅꯥ ꯃꯨꯈꯌ ꯃꯟꯇ ꯔꯦꯚꯟꯊ ꯔꯦꯗꯗꯤꯗꯥ ꯊꯧꯔꯥꯡ ꯇꯧꯅꯕ ꯍꯥꯏꯖ
--------------------------------------------------

Translating:  59%|███████████████▉           | 591/1000 [08:16<04:56,  1.38it/s]

[591/1000]
EN: SOCIAL Hyderabad hosts She's a Phataka Diwali celebration bash.
MNI_MTEI: ꯁꯣꯁꯤꯌꯥꯜ ꯍꯥꯏꯗꯕꯥꯗꯅ ꯁꯦ ꯏꯖ ꯑꯦ ꯐꯥꯇꯀꯥ ꯗꯤꯋꯥꯂꯤꯒꯤ ꯊꯧꯔꯝ ꯄꯥꯡꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  59%|███████████████▉           | 592/1000 [08:16<04:47,  1.42it/s]

[592/1000]
EN: Hyderabad soaked in festival fervour with rain showers.
MNI_MTEI: ꯍꯥꯏꯗꯕꯥꯗ ꯑꯁꯤ ꯅꯣꯡ ꯆꯨꯕꯥꯒ ꯂꯣꯏꯅꯅꯥ ꯀꯨꯝꯍꯩꯒꯤ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  59%|████████████████           | 593/1000 [08:17<04:54,  1.38it/s]

[593/1000]
EN: Dasara trains diverted to manage two lakh passenger footfall.
MNI_MTEI: ꯄꯦꯁꯦꯟꯖꯔ ꯂꯥꯈ ꯑꯅꯤꯒꯤ ꯐꯨꯗꯐꯣꯜ ꯁꯤꯟꯗꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯗꯥꯁꯥꯔꯥ ꯇꯦꯟꯁꯤꯡ ꯗꯥꯏꯚꯔꯇ ꯇꯧ
--------------------------------------------------

Translating:  59%|████████████████           | 594/1000 [08:18<04:51,  1.39it/s]

[594/1000]
EN: New passenger routes planned for Dasara and Diwali travel.
MNI_MTEI: ꯗꯥꯁꯥꯔꯥ ꯑꯃꯁꯨꯡ ꯗꯤꯋꯥꯂꯤ ꯇꯚꯦꯜꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯄꯦꯁꯦꯟꯖꯔ ꯔꯨꯠꯁꯤꯡ ꯊꯧꯔꯥꯡ ꯇꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  60%|████████████████           | 595/1000 [08:19<04:55,  1.37it/s]

[595/1000]
EN: Hyderabad kiosks offer Ganesh idols across every street.
MNI_MTEI: ꯍꯥꯏꯗꯕꯥꯗꯀꯤ ꯀꯤꯑꯣꯁ ꯭ ꯛꯁꯤꯡꯗ ꯒꯅꯦꯁꯀꯤ ꯃꯨꯔꯠꯇꯤꯁꯤꯡ ꯁꯇ ꯈꯨꯗꯤꯡꯃꯛꯇ ꯄꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  60%|████████████████           | 596/1000 [08:19<04:36,  1.46it/s]

[596/1000]
EN: Indian Navy monitors every Chinese vessel in Indian Ocean.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯁꯃꯨꯗꯗꯥ ꯂꯩꯕ ꯆꯥꯏꯅꯥꯒꯤ ꯍꯤ ꯈꯨꯗꯤꯡꯃꯛ ꯏꯟꯗꯤꯌꯟ ꯅꯦꯚꯤꯅꯥ ꯌꯦꯡꯁꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  60%|████████████████           | 597/1000 [08:20<04:48,  1.40it/s]

[597/1000]
EN: Vice Admiral Sanjay Vatsayan confirms continuous maritime surveillance.
MNI_MTEI: ꯚꯥꯏꯁ ꯑꯦꯗꯃꯤꯔꯦꯜ ꯁꯟꯖꯦ ꯚꯇꯁꯥꯌꯟꯅ ꯃꯈꯥ ꯇꯥꯅ ꯁꯃꯨꯗꯗꯥ ꯌꯦꯡꯁꯤꯟꯕꯒꯤ ꯊꯕꯛ ꯆꯠꯊꯔꯤ ꯍꯥꯏꯕ ꯈꯪꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  60%|████████████████▏          | 598/1000 [08:21<04:45,  1.41it/s]

[598/1000]
EN: Goa tourism department announces calendar of winter festivals.
MNI_MTEI: ꯒꯣꯋꯥ ꯇꯨꯔꯤꯖꯝ ꯗꯤꯄꯥꯔꯇꯃꯦꯟꯇꯅꯥ ꯅꯤꯡꯊꯝꯊꯥꯒꯤ ꯀꯨꯝꯍꯩꯁꯤꯡꯒꯤ ꯀꯦꯂꯦꯟꯗꯔ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  60%|████████████████▏          | 599/1000 [08:22<04:51,  1.37it/s]

[599/1000]
EN: Jaipur Literature Festival attracts 50,000 book lovers from abroad.
MNI_MTEI: ꯖꯦꯄꯨꯔ ꯂꯤꯇꯔꯦꯆꯔ ꯐꯦꯁꯇꯤꯕꯦꯜꯅꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯇꯒꯤ ꯂꯥꯏꯔꯤꯛ ꯄꯥꯝꯖꯕ ꯃꯤꯑꯣꯏ ꯒꯤ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  60%|████████████████▏          | 600/1000 [08:22<04:50,  1.38it/s]

[600/1000]
EN: Rann Utsav begins in Kutch with tent city bookings full.
MNI_MTEI: ꯇꯦꯟꯇ ꯁꯤꯇꯤ ꯕꯨꯀꯤꯡ ꯃꯄꯨꯡ ꯐꯥꯕꯥꯒ ꯂꯣꯏꯅꯅꯥ ꯔꯟ ꯎꯇꯁꯥꯚ ꯑꯁꯤ ꯀꯨꯇꯆꯇꯥ ꯍꯧ
--------------------------------------------------

Translating:  60%|████████████████▏          | 601/1000 [08:23<04:51,  1.37it/s]

[601/1000]
EN: Hornbill Festival showcases Naga heritage in Kisama heritage village.
MNI_MTEI: ꯍꯣꯔꯟꯕꯤꯜ ꯐꯦꯁꯇꯤꯕꯦꯜꯅꯥ ꯀꯤꯁꯥꯃꯥ ꯍꯦꯔꯤꯇꯦꯖ ꯈꯨꯡꯒꯪꯗꯥ ꯅꯥꯒꯥꯒꯤ ꯍꯦꯔꯤꯇꯤꯖ ꯎꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  60%|████████████████▎          | 602/1000 [08:24<04:55,  1.35it/s]

[602/1000]
EN: Ganga Aarti at Varanasi draws record international tourist attendance.
MNI_MTEI: ꯕꯥꯔꯥꯅꯥꯁꯤꯗ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯒꯪꯒꯥ ꯑꯥꯔꯇꯤꯗꯥ ꯑꯇꯔꯖꯥꯇꯤꯒꯤ ꯂꯝꯀꯣꯏꯕꯥꯁꯤꯡꯒꯤ ꯁꯔꯨꯛ ꯌꯥꯕꯒꯤ ꯂꯥꯆꯟ
--------------------------------------------------

Translating:  60%|████████████████▎          | 603/1000 [08:24<04:47,  1.38it/s]

[603/1000]
EN: Pahalgam terror attack kills twenty-six tourists including foreigners.
MNI_MTEI: ꯄꯍꯥꯜꯒꯥꯝ ꯇꯦꯔꯣꯔꯤ ꯑꯦꯇꯦꯛ ꯇꯧꯕꯗꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯃꯤꯑꯣꯏꯁꯤꯡ ꯌꯥꯎꯅꯥ ꯂꯝꯀꯣꯏꯕꯥ 26 ꯁꯤ
--------------------------------------------------

Translating:  60%|████████████████▎          | 604/1000 [08:25<04:38,  1.42it/s]

[604/1000]
EN: Terrorists attack Baisaran meadows killing twenty-six civilian tourists.
MNI_MTEI: ꯇꯦꯔꯣꯔꯤꯁꯇꯁꯤꯡꯅ ꯕꯥꯏꯁꯥꯔꯥꯟꯒꯤ ꯂꯝꯈꯩꯁꯤꯡꯗ ꯂꯥꯟꯗꯥꯗꯨꯅ ꯃꯤꯆꯝꯒꯤ ꯂꯝꯀꯣꯏꯕ 26 ꯁꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  60%|████████████████▎          | 605/1000 [08:26<04:27,  1.48it/s]

[605/1000]
EN: Two foreign tourists among twenty-six dead in Pahalgam attack.
MNI_MTEI: ꯄꯍꯥꯜꯒꯥꯝ ꯑꯦꯇꯦꯛꯗꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯑꯅꯤꯒ ꯂꯣꯏꯅꯅꯥ ꯃꯤꯑꯣꯏ 26 ꯁꯤ
--------------------------------------------------

Translating:  61%|████████████████▎          | 606/1000 [08:27<04:40,  1.41it/s]

[606/1000]
EN: Operation Sindoor launched following deadly Pahalgam tourist attack.
MNI_MTEI: ꯄꯍꯥꯜꯒꯥꯃ ꯇꯨꯔꯤꯁꯇ ꯑꯦꯇꯦꯛꯀꯤ ꯃꯇꯨꯡꯗ ꯑꯣꯄꯔꯦꯁꯟ ꯁꯤꯟꯗꯨꯔ ꯍꯧ
--------------------------------------------------

Translating:  61%|████████████████▍          | 607/1000 [08:27<05:08,  1.28it/s]

[607/1000]
EN: Saudi Arabia minister Adel Al-Jubeir arrives in Delhi post Operation Sindoor.
MNI_MTEI: ꯁꯧꯗꯤ ꯑꯔꯕꯒꯤ ꯃꯟꯇ ꯑꯗꯦꯜ ꯑꯜ-ꯖꯨꯕꯦꯔ ꯑꯣꯄꯔꯦꯁꯟ ꯁꯤꯟꯗꯨꯔꯒꯤ ꯃꯇꯨꯡꯗ ꯗꯤꯜꯂꯤꯗꯥ ꯂꯥꯛ
--------------------------------------------------

Translating:  61%|████████████████▍          | 608/1000 [08:28<05:18,  1.23it/s]

[608/1000]
EN: Iranian Foreign Minister Araghchi visits New Delhi amid tensions.
MNI_MTEI: ꯏꯔꯥꯅꯤꯌꯟꯒꯤ ꯐꯣꯔꯦꯟ ꯃꯟꯇ ꯑꯔꯥꯘꯆꯤꯅꯥ ꯇꯦꯟꯁꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯅ ꯗꯤꯜꯂꯤꯗꯥ ꯆꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  61%|████████████████▍          | 609/1000 [08:29<05:22,  1.21it/s]

[609/1000]
EN: Delhi Red Fort blast leaves fourteen dead and several injured.
MNI_MTEI: ꯗꯤꯜꯂꯤꯒꯤ ꯔꯦꯗ ꯐꯣꯔꯇ ꯄꯣꯈꯥꯏꯕꯒꯤ ꯊꯧꯗꯣꯛꯗꯥ ꯃꯤꯑꯣꯏ 14 ꯁꯤꯈꯤ ꯑꯃꯁꯨꯡ ꯀꯌꯥ ꯑꯃꯥ ꯅꯥꯟꯊꯣꯛ
--------------------------------------------------

Translating:  61%|████████████████▍          | 610/1000 [08:30<05:16,  1.23it/s]

[610/1000]
EN: High intensity explosion outside Red Fort kills fourteen people.
MNI_MTEI: ꯔꯦꯗ ꯐꯣꯔꯇ ꯃꯄꯥꯟꯗ ꯍꯥꯏ ꯏꯟꯇꯦꯟꯁꯤꯇꯤ ꯄꯣꯈꯥꯏꯕꯅ ꯃꯤꯑꯣꯏ 14 ꯁꯤ
--------------------------------------------------

Translating:  61%|████████████████▍          | 611/1000 [08:31<05:38,  1.15it/s]

[611/1000]
EN: Supreme Court upholds Christian Army officer Samuel Kamalesan dismissal.
MNI_MTEI: ꯁꯨꯄꯝ ꯀꯣꯔꯇꯅꯥ ꯈꯌꯥꯅ ꯑꯥꯔꯃꯤ ꯑꯣꯐꯤꯁꯔ ꯁꯦꯃꯜ ꯀꯥꯃꯥꯂꯦꯁꯟꯕꯨ ꯂꯧꯊꯣꯛꯄꯥ ꯂꯦꯞꯈꯤ ꯫
--------------------------------------------------

Translating:  61%|████████████████▌          | 612/1000 [08:32<05:42,  1.13it/s]

[612/1000]
EN: Army officer refuses temple pooja entry leading to dismissal.
MNI_MTEI: ꯑꯥꯔꯃꯤ ꯑꯣꯐꯤꯁꯔꯅꯥ ꯂꯥꯏꯁꯪꯗꯥ ꯄꯨꯖꯥ ꯌꯥꯎꯕꯥ ꯌꯥꯈꯤꯗꯦ ꯃꯗꯨꯅ ꯃꯔꯝ ꯑꯣꯏꯔꯒ ꯐꯝ ꯊꯥꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  61%|████████████████▌          | 613/1000 [08:33<05:53,  1.09it/s]

[613/1000]
EN: Chief Justice Surya Kant terms refusal grossest kind of indiscipline.
MNI_MTEI: ꯆꯤꯐ ꯖꯇꯤꯁ ꯁꯨꯔꯌꯥ ꯀꯟꯇꯅꯥ ꯌꯥꯗꯕꯒꯤ ꯋꯥꯐꯝ ꯑꯁꯤ ꯈ ꯭ ꯋꯥꯏꯗꯒꯤ ꯆꯥꯎꯔꯕ ꯅꯤꯌꯝ ꯅꯥꯏꯗꯕ ꯑꯃꯅꯤ ꯍꯥꯏꯅ ꯍꯥꯏꯈꯤ ꯫
--------------------------------------------------

Translating:  61%|████████████████▌          | 614/1000 [08:34<05:30,  1.17it/s]

[614/1000]
EN: Saif Ali Khan undergoes surgery after knife attack at residence.
MNI_MTEI: ꯁꯥꯏꯐ ꯑꯂꯤ ꯈꯥꯟꯒꯤ ꯌꯨꯝꯗꯥ ꯆꯤꯊꯤꯅ ꯂꯥꯟꯗꯥꯕꯥ ꯃꯇꯨꯡꯗ ꯁꯔꯖꯔꯤ ꯇꯧ
--------------------------------------------------

Translating:  62%|████████████████▌          | 615/1000 [08:34<05:24,  1.19it/s]

[615/1000]
EN: Intruder attacks Bollywood actor Saif Ali Khan in Mumbai.
MNI_MTEI: ꯏꯟꯇꯨꯗꯔꯅ ꯕꯣꯂꯤꯋꯨꯗ ꯑꯦꯛꯇꯔ ꯁꯥꯏꯐ ꯑꯂꯤ ꯈꯥꯟꯗꯥ ꯃꯨꯝꯕꯥꯏꯗ ꯂꯥꯟꯗꯥ
--------------------------------------------------

Translating:  62%|████████████████▋          | 616/1000 [08:35<05:27,  1.17it/s]

[616/1000]
EN: Mumbai police identify accused in Saif Ali Khan attack case.
MNI_MTEI: ꯃꯨꯝꯕꯥꯏ ꯄꯨꯂꯤꯁꯅꯥ ꯁꯥꯏꯐ ꯑꯂꯤ ꯈꯥꯟ ꯑꯦꯇꯦꯛ ꯀꯦꯁꯗꯥ ꯃꯔꯥꯜ ꯂꯩꯕꯁꯤꯡ ꯃꯁꯛ ꯈꯪꯗꯣꯛ
--------------------------------------------------

Translating:  62%|████████████████▋          | 617/1000 [08:36<05:38,  1.13it/s]

[617/1000]
EN: Actor discharged five days after hospitalization following attack.
MNI_MTEI: ꯑꯦꯇꯦꯛ ꯇꯧꯔꯕ ꯃꯇꯨꯡ ꯍꯣꯁꯄꯤꯇꯥꯜ ꯑꯣꯏꯔꯛꯄꯒꯤ ꯅꯨꯃꯤꯠ ꯃꯉꯥꯅꯤꯒꯤ ꯃꯇꯨꯡꯗ ꯑꯦꯛꯇꯔ ꯑꯗꯨꯕꯨ ꯗꯤꯁꯆꯥꯔꯖ ꯇꯧ
--------------------------------------------------

Translating:  62%|████████████████▋          | 618/1000 [08:37<06:00,  1.06it/s]

[618/1000]
EN: Tihar jail probe reveals racket charging for free inmate meetings.
MNI_MTEI: ꯇꯤꯍꯥꯔ ꯖꯦꯜꯒꯤ ꯊꯤꯖꯤꯟ- ꯍꯨꯝꯖꯤꯟꯕꯒꯤ ꯊꯕꯛ ꯑꯁꯤꯅ ꯐ ꯏꯟꯃꯤꯇ ꯃꯤꯇꯤꯡꯁꯤꯡꯒꯤꯗꯃꯛ ꯔꯦꯀꯦꯇ ꯁꯦꯜ ꯂꯧꯈꯤꯕꯗꯨ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  62%|████████████████▋          | 619/1000 [08:38<05:54,  1.08it/s]

[619/1000]
EN: Undercover officials exposed illegal mulakat charges at Tihar.
MNI_MTEI: ꯑꯟꯗꯔꯀꯚꯔ ꯑꯣꯐꯤꯁꯌꯦꯜꯁꯤꯡꯅꯥ ꯇꯤꯍꯥꯔꯗꯥ ꯑꯥꯏꯟꯅ ꯌꯥꯗꯕ ꯃꯨꯂꯥꯀꯇ ꯆꯥꯔꯖꯁꯤꯡ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  62%|████████████████▋          | 620/1000 [08:39<05:46,  1.10it/s]

[620/1000]
EN: Tihar transfers twenty-five data entry operators after tout investigation.
MNI_MTEI: ꯊꯤꯍꯔꯅꯥ ꯊꯤꯖꯟ ꯍꯨꯝꯖꯟꯕ ꯂꯣꯏꯔꯕꯥ ꯗꯦꯇꯥ ꯑꯦꯟ ꯑꯣꯄꯔꯦꯇꯔ ꯃꯉꯥ ꯍꯣꯡꯗꯣꯛꯏ ꯫
--------------------------------------------------

Translating:  62%|████████████████▊          | 621/1000 [08:40<05:44,  1.10it/s]

[621/1000]
EN: Biometric authentication introduced at Tihar Jail for security.
MNI_MTEI: ꯁꯦꯀꯇꯤꯒꯤꯗꯃꯛ ꯇꯤꯍꯥꯔ ꯖꯦꯂꯗꯥ ꯕꯥꯏꯑꯣꯃꯦꯇ ꯑꯣꯊꯦꯟꯇꯤꯀꯦꯁꯟ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  62%|████████████████▊          | 622/1000 [08:41<06:03,  1.04it/s]

[622/1000]
EN: Supreme Court declines virtual appearance exemption for chief secretaries.
MNI_MTEI: ꯁꯨꯄꯝ ꯀꯣꯔꯇꯅꯥ ꯆꯤꯐ ꯁꯦꯀꯇꯔꯤꯁꯤꯡꯒꯤ ꯚꯔꯆ ꯭ ꯌꯨꯑꯦꯜ ꯑꯦꯄꯦꯔꯦꯟꯁ ꯑꯦꯛꯁꯀꯃꯦꯟꯁꯟ ꯌꯥꯗꯦ ꯫
--------------------------------------------------

Translating:  62%|████████████████▊          | 623/1000 [08:42<06:27,  1.03s/it]

[623/1000]
EN: States sleeping over stray dog sterilization orders says Supreme Court.
MNI_MTEI: ꯁꯝ ꯀꯣꯔꯇꯅꯥ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯂꯝꯕꯤ ꯅꯥꯏꯗꯕ ꯗꯣꯒꯦꯔꯤꯂꯥꯏꯖꯦꯁꯟꯒꯤ ꯑꯣꯔꯗꯔꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯔꯥꯖꯁꯤꯡ ꯁꯨꯄ
--------------------------------------------------

Translating:  62%|████████████████▊          | 624/1000 [08:43<06:10,  1.01it/s]

[624/1000]
EN: Passenger forced to write letter after Delhi airport assault.
MNI_MTEI: ꯗꯤꯜꯂꯤ ꯑꯦꯌꯔꯄꯣꯔꯇ ꯑꯦꯁꯣꯂꯇ ꯇꯧꯔꯕꯥ ꯃꯇꯨꯡꯗ ꯄꯦꯁꯦꯟꯖꯔꯅꯥ ꯆꯤꯊꯤ ꯏꯕꯥ ꯇꯥꯍꯟ
--------------------------------------------------

Translating:  62%|████████████████▉          | 625/1000 [08:44<05:56,  1.05it/s]

[625/1000]
EN: Passenger claims pressure to avoid police complaint filing.
MNI_MTEI: ꯄꯦꯁꯦꯟꯒꯔꯅꯥ ꯄꯨꯂꯤꯁ ꯀꯝꯄꯂꯦꯟꯇ ꯐꯥꯏꯂꯤꯡ ꯊꯤꯡꯅꯕꯁꯔ ꯄꯤꯅꯕ ꯍꯥꯏꯔꯤ ꯫
--------------------------------------------------

Translating:  63%|████████████████▉          | 626/1000 [08:45<06:08,  1.01it/s]

[626/1000]
EN: US forces seize oil tanker off Venezuela for narco-terrorism.
MNI_MTEI: ꯌꯨ ꯑꯦꯁ ꯐꯣꯔꯦꯁꯁꯅ ꯅꯦꯔꯀꯣ-ꯇꯦꯔꯣꯔꯤꯖꯝꯒꯤꯗꯃꯛ ꯚꯦꯅꯦꯖꯦꯂꯨꯂꯥꯗꯒꯤ ꯊꯥꯎꯒꯤ ꯇꯦꯡꯀꯔ ꯂꯧꯁꯤꯟ
--------------------------------------------------

Translating:  63%|████████████████▉          | 627/1000 [08:46<06:09,  1.01it/s]

[627/1000]
EN: US Coast Guard apprehends tanker with Department of Defense backing.
MNI_MTEI: ꯌꯨ ꯑꯦꯁ ꯀꯣꯠ ꯒꯥꯔꯗꯅ ꯗꯤꯄꯥꯔꯇꯃꯦꯟꯇ ꯑꯣꯐ ꯗꯤꯐꯦꯟꯁꯀꯤ ꯃꯇꯦꯡꯒ ꯂꯣꯏꯅꯅꯥ ꯇꯦꯡꯀꯔ ꯐꯥ
--------------------------------------------------

Translating:  63%|████████████████▉          | 628/1000 [08:47<06:14,  1.01s/it]

[628/1000]
EN: Supreme Court denies relief to mosque seeking loudspeaker permission.
MNI_MTEI: ꯂꯥꯎꯗꯄꯤꯀꯔꯒꯤ ꯑꯌꯥꯕꯥ ꯂꯧꯕ ꯃꯖꯁꯤꯗꯀꯤꯗꯃꯛ ꯁꯨꯄꯝ ꯀꯣꯔꯠꯅ ꯔꯤꯂꯥꯏꯐ ꯄꯤꯅꯕ ꯌꯥꯗꯦ ꯫
--------------------------------------------------

Translating:  63%|████████████████▉          | 629/1000 [08:48<06:20,  1.02s/it]

[629/1000]
EN: Nagpur bench rules no religion mandates prayers with amplifiers.
MNI_MTEI: ꯅꯥꯒꯄꯨꯔ ꯕꯦꯟꯆꯅꯥ ꯙꯔꯃ ꯑꯃꯠꯇꯅ ꯑꯝꯄꯂꯤꯐꯥꯏꯌꯔꯁꯤꯡꯒ ꯂꯣꯏꯅꯅ ꯂꯥꯏ ꯊꯥꯕꯒꯤ ꯑꯌꯥꯕ ꯄꯤꯗꯦ ꯍꯥꯏꯅ ꯆꯠꯅꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  63%|█████████████████          | 630/1000 [08:49<06:08,  1.00it/s]

[630/1000]
EN: Cruise Saudi brand operations commence with Red Sea licences.
MNI_MTEI: ꯁꯥꯎꯗꯤ ꯕꯥꯟꯗꯀꯤ ꯀꯌꯨꯖ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡ ꯑꯁꯤ ꯔꯦꯗ ꯁꯤ ꯂꯥꯏꯁꯦꯟꯁꯁꯤꯡꯗꯒꯤ ꯍꯧꯏ ꯫
--------------------------------------------------

Translating:  63%|█████████████████          | 631/1000 [08:50<05:55,  1.04it/s]

[631/1000]
EN: Marina services added to Saudi marine tourism portfolio.
MNI_MTEI: ꯁꯥꯎꯗꯤ ꯃꯦꯔꯤꯅ ꯇꯨꯔꯤꯖꯝ ꯄꯣꯔꯇꯐꯣꯂꯤꯑꯣꯗꯥ ꯃꯦꯔꯤꯅꯥ ꯁꯔꯕꯤꯁꯁꯤꯡ ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  63%|█████████████████          | 632/1000 [08:51<05:45,  1.06it/s]

[632/1000]
EN: Recreational marine activities licensed by Saudi Red Sea Authority.
MNI_MTEI: ꯁꯥꯎꯗꯤ ꯔꯦꯗ ꯁꯤ ꯑꯣꯊꯣꯔꯤꯇꯤꯅꯥ ꯂꯥꯏꯁꯦꯟꯁ ꯄꯤꯔꯕꯥ ꯔꯤꯀꯦꯁꯅꯦꯜ ꯃꯦꯔꯤꯅ ꯑꯦꯛꯇꯤꯚꯤꯇꯤꯁꯤꯡ
--------------------------------------------------

Translating:  63%|█████████████████          | 633/1000 [08:52<05:47,  1.06it/s]

[633/1000]
EN: Saudi Arabia enforces qualified crews for marine tourism operations.
MNI_MTEI: ꯁꯧꯗꯤ ꯑꯔꯕꯤꯌꯥꯅꯥ ꯃꯦꯔꯤꯅ ꯇꯨꯔꯤꯖꯝ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡꯒꯤꯗꯃꯛ ꯀꯂꯤꯐꯤꯀꯥꯏꯗꯎꯁꯤꯡ ꯆꯠꯅꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  63%|█████████████████          | 634/1000 [08:53<05:47,  1.05it/s]

[634/1000]
EN: Red Sea unregulated maritime activity concerns addressed by licences.
MNI_MTEI: ꯔꯦꯗ ꯁꯤ ꯑꯟꯔꯦꯒꯨꯂꯦꯇꯦꯗ ꯃꯦꯔꯤꯇꯥꯏꯃ ꯑꯦꯛꯇꯤꯚꯤꯇꯤꯒꯤ ꯋꯥꯐꯝꯁꯤꯡ ꯑꯁꯤ ꯂꯥꯏꯁꯦꯟꯁꯁꯤꯡꯅ ꯋꯥꯔꯣꯏꯁꯤꯟ ꯄꯤ
--------------------------------------------------

Translating:  64%|█████████████████▏         | 635/1000 [08:54<05:31,  1.10it/s]

[635/1000]
EN: Indian cruise tourism gets boost with ten new terminals.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟ ꯀꯖ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯑꯅꯧꯕ ꯇꯔꯃꯤꯅꯦꯜ ꯇꯔꯥꯒ ꯂꯣꯏꯅꯅꯥ ꯆꯥꯎꯈꯠꯄ ꯐꯪ
--------------------------------------------------

Translating:  64%|█████████████████▏         | 636/1000 [08:55<05:32,  1.09it/s]

[636/1000]
EN: Disney Destiny becomes marquee cruise debut of 2025.
MNI_MTEI: ꯗꯤꯁꯅꯤ ꯗꯦꯁꯇꯤꯅꯤ ꯑꯁꯤ ꯏꯪꯁꯣꯛ 2025 ꯒꯤ ꯃꯥꯔꯀꯨꯏ ꯀꯖ ꯗꯦꯕꯇ ꯑꯣꯏꯔꯦ ꯫
--------------------------------------------------

Translating:  64%|█████████████████▏         | 637/1000 [08:56<05:39,  1.07it/s]

[637/1000]
EN: Norwegian Aqua adds fleet capacity to Norwegian Cruise Line.
MNI_MTEI: ꯅꯣꯔꯋꯦꯒꯤ ꯑꯦꯀꯋꯥꯅꯥ ꯅꯣꯔꯕꯦꯒꯤ ꯀꯖ ꯂꯥꯏꯅꯗꯥ ꯐꯂꯤꯇ ꯀꯦꯄꯦꯁꯤꯇꯤ ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  64%|█████████████████▏         | 638/1000 [08:56<05:31,  1.09it/s]

[638/1000]
EN: Royal Caribbean Star of the Seas enters service in 2025.
MNI_MTEI: ꯔꯣꯌꯦꯜ ꯀꯦꯔꯤꯕꯤꯌꯟ ꯁꯥꯔ ꯑꯣꯐ ꯗꯤ ꯁꯤꯖꯅꯥ ꯏꯪ 2025 ꯗꯥ ꯊꯕꯛꯇ ꯆꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  64%|█████████████████▎         | 639/1000 [08:57<05:27,  1.10it/s]

[639/1000]
EN: Cordelia Cruises announces Lakshadweep itineraries from Kochi.
MNI_MTEI: ꯀꯣꯔꯗꯦꯂꯤꯌꯥ ꯀꯨꯏꯖꯦꯁꯅ ꯀꯣꯆꯤꯗꯒꯤ ꯂꯛꯁꯗꯞꯀꯤ ꯂꯝꯕꯤꯁꯤꯡ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  64%|█████████████████▎         | 640/1000 [08:58<05:28,  1.10it/s]

[640/1000]
EN: Water metro connectivity boosts tourism in Kochi backwaters.
MNI_MTEI: ꯋꯥꯇꯔ ꯃꯦꯇ ꯀꯣꯟꯇꯦꯛꯇꯤꯚꯤꯇꯤꯅ ꯀꯣꯆꯤꯒꯤ ꯕꯦꯀꯋꯥꯇꯔꯗꯥ ꯇꯨꯔꯤꯖꯝ ꯍꯦꯟꯒꯠꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  64%|█████████████████▎         | 641/1000 [08:59<05:32,  1.08it/s]

[641/1000]
EN: Mumbai cruise terminal handles record 100,000 passengers this year.
MNI_MTEI: ꯃꯨꯝꯕꯥꯏ ꯀꯖ ꯇꯔꯃꯤꯅꯦꯜꯅꯥ ꯆꯍꯤ ꯑꯁꯤꯗ ꯄꯦꯁꯦꯟꯖꯔ 100, 000 ꯔꯦꯀꯣꯔ ꯇꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  64%|█████████████████▎         | 642/1000 [09:00<05:31,  1.08it/s]

[642/1000]
EN: Ganga Vilas luxury cruise completes successful Brahmaputra season.
MNI_MTEI: ꯒꯪꯒꯥ ꯚꯤꯂꯥꯁ ꯂꯛꯁꯨꯔꯤ ꯀꯖꯅꯥ ꯃꯥꯏꯄꯥꯛꯄꯥ ꯕꯍꯃꯄꯨꯇ ꯁꯤꯖꯟ ꯂꯣꯏꯁꯤꯟ
--------------------------------------------------

Translating:  64%|█████████████████▎         | 643/1000 [09:01<05:24,  1.10it/s]

[643/1000]
EN: Kerala houseboat registrations cross one thousand operational vessels.
MNI_MTEI: ꯀꯦꯔꯂꯥꯒꯤ ꯍꯥꯎꯁꯕꯣꯠ ꯔꯦꯖꯤꯁꯇꯦꯁꯟꯅꯥ ꯑꯣꯄꯔꯦꯁꯅꯦꯜ ꯚꯦꯁꯦꯜ ꯂꯤꯁꯤꯡ ꯑꯃ ꯂꯣꯏꯔꯦ ꯫
--------------------------------------------------

Translating:  64%|█████████████████▍         | 644/1000 [09:02<05:25,  1.09it/s]

[644/1000]
EN: Andaman and Nicobar receive approval for international cruise tourism.
MNI_MTEI: ꯑꯟꯗꯃꯥꯟ ꯑꯃꯁꯨꯡ ꯅꯤꯀꯣꯕꯥꯔꯅꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯀꯖ ꯇꯨꯔꯤꯖꯝꯒꯤꯗꯃꯛ ꯑꯦꯄꯂꯨꯑꯦꯁꯟ ꯐꯪ
--------------------------------------------------

Translating:  64%|█████████████████▍         | 645/1000 [09:03<05:29,  1.08it/s]

[645/1000]
EN: Airbnb relaunches experiences feature for bookings and services.
MNI_MTEI: ꯑꯦꯔ ꯕꯤ ꯑꯦꯟ ꯕꯤꯅꯥ ꯕꯨꯀꯤꯡ ꯑꯃꯁꯨꯡ ꯁꯔꯕꯤꯁꯁꯤꯡꯒꯤ ꯑꯦꯛꯁꯄꯤꯌꯔꯦꯟꯁ ꯐꯤꯆꯔ ꯑꯃꯨꯛ ꯍꯟꯅ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  65%|█████████████████▍         | 646/1000 [09:04<05:50,  1.01it/s]

[646/1000]
EN: Brian Chesky announces Airbnb services complementing home rentals.
MNI_MTEI: ꯕꯌꯥꯟ ꯆꯦꯁꯀꯤꯅꯥ ꯑꯦꯔꯕꯤꯟꯕꯤ ꯁꯔꯕꯤꯁꯁ ꯑꯁꯤ ꯌꯨꯝꯒꯤ ꯔꯦꯟꯇꯦꯜꯁꯤꯡ ꯀꯝꯄꯂꯤꯃꯦꯟꯇ ꯇꯧꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  65%|█████████████████▍         | 647/1000 [09:05<05:59,  1.02s/it]

[647/1000]
EN: Olympic speed skater Arianna Fontana leads Airbnb training rides.
MNI_MTEI: ꯑꯣꯂꯤꯝꯄꯤꯛ ꯁꯄꯤꯗꯀꯦꯇꯔ ꯑꯔꯤꯌꯥꯅꯥ ꯐꯣꯟꯇꯥꯅꯥꯅꯥ ꯑꯦꯔ ꯕꯤ ꯑꯦꯟ ꯕꯤ ꯇꯅꯤꯡ ꯔꯥꯏꯗꯁꯤꯡꯒꯤ ꯂꯨꯆꯤꯡꯏ ꯫
--------------------------------------------------

Translating:  65%|█████████████████▍         | 648/1000 [09:06<06:04,  1.04s/it]

[648/1000]
EN: Airbnb offers Alpine hikes with athlete guides in Italy.
MNI_MTEI: ꯑꯦꯔ ꯕꯤ ꯑꯦꯟ ꯕꯤꯅꯥ ꯏꯇꯂꯤꯗꯥ ꯑꯦꯊꯂꯤꯇ ꯒꯤꯗꯁꯤꯡꯒ ꯂꯣꯏꯅꯅ ꯑꯜꯄꯥꯏꯅ ꯍꯥꯏꯀꯁꯤꯡꯒꯤ ꯈꯨꯗꯣꯡꯆꯥꯕꯥ ꯄꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  65%|█████████████████▌         | 649/1000 [09:07<06:04,  1.04s/it]

[649/1000]
EN: K-pop band SEVENTEEN curates music sessions for Airbnb.
MNI_MTEI: ꯑꯦꯔ ꯕꯤ ꯑꯦꯟ ꯕꯤ ꯒꯤꯗꯃꯛ ꯀꯦ-ꯄꯣꯄ ꯕꯦꯟꯗ ꯁꯦꯚꯦꯟꯇꯤꯟꯅꯥ ꯏꯁꯩꯒꯤ ꯊꯧꯔꯝꯁꯤꯡ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  65%|█████████████████▌         | 650/1000 [09:08<06:12,  1.06s/it]

[650/1000]
EN: Chance the Rapper partners with Airbnb for exclusive experiences.
MNI_MTEI: ꯑꯦꯛꯁꯁꯤꯋꯦꯜ ꯑꯦꯛꯁꯄꯤꯌꯔꯦꯟꯁꯀꯤꯗꯃꯛ ꯑꯦꯔ ꯕꯤ ꯑꯦꯟ ꯕꯤꯒꯥ ꯂꯣꯏꯅꯅ ꯔꯦꯄꯔ ꯄꯥꯔꯇꯦꯅꯔꯁꯤꯡꯒꯤ ꯇꯥꯟꯖ ꯂꯧꯕꯤꯌꯨ ꯫
--------------------------------------------------

Translating:  65%|█████████████████▌         | 651/1000 [09:09<06:09,  1.06s/it]

[651/1000]
EN: Economic uncertainty shifts traveller behaviour toward price sensitivity.
MNI_MTEI: ꯁꯦꯟꯊꯨꯝꯒꯤ ꯑꯔꯦꯞꯄ ꯂꯩꯇꯕꯥ ꯑꯁꯤꯅ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯃꯑꯣꯡ-ꯃꯇꯥꯎꯕꯨ ꯃꯃꯜꯒꯤ ꯃꯇꯥꯡꯗ ꯈꯡꯅꯕ ꯉꯝꯕꯒꯤ ꯃꯥꯏꯀꯩꯗ ꯍꯣꯡꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  65%|█████████████████▌         | 652/1000 [09:10<05:48,  1.00s/it]

[652/1000]
EN: Tourists choose off-the-beaten-path destinations influenced by social media.
MNI_MTEI: ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯅ ꯁꯣꯁꯤꯌꯦꯜ ꯃꯤꯗꯤꯌꯥꯅꯥ ꯏꯊꯤꯜ ꯄꯤꯔꯕꯥ ꯂꯝꯈꯩꯒꯤ ꯃꯄꯥꯟꯗ ꯂꯩꯕ ꯃꯐꯝꯁꯤꯡ ꯈꯟ
--------------------------------------------------

Translating:  65%|█████████████████▋         | 653/1000 [09:11<05:36,  1.03it/s]

[653/1000]
EN: Travelers turn to AI-powered tools for trip planning.
MNI_MTEI: ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯅ ꯇꯞꯂꯥꯏꯅꯤꯡꯒꯤꯗꯃꯛ ꯑꯦꯑꯏ-ꯄꯋꯥꯔ ꯇꯧꯔꯕꯥ ꯇꯨꯜꯁꯤꯡ ꯁꯤꯖꯤꯟꯅ
--------------------------------------------------

Translating:  65%|█████████████████▋         | 654/1000 [09:12<05:21,  1.07it/s]

[654/1000]
EN: Sustainable tourism gains traction among mindful travellers.
MNI_MTEI: ꯁꯁꯇꯦꯅꯦꯕꯜ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯔꯕꯥ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯟꯅꯤꯡꯉꯥꯏ ꯑꯣꯏ
--------------------------------------------------

Translating:  66%|█████████████████▋         | 655/1000 [09:13<04:59,  1.15it/s]

[655/1000]
EN: Responsible travel interest grows among conscious tourists.
MNI_MTEI: ꯈꯪꯍꯧꯔꯕꯥ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯊꯧꯗꯥꯡ ꯂꯧꯔꯕ ꯂꯝꯀꯣꯏꯕꯒꯤ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯄ ꯍꯦꯟꯒꯠꯂꯛ
--------------------------------------------------

Translating:  66%|█████████████████▋         | 656/1000 [09:14<04:57,  1.16it/s]

[656/1000]
EN: Less-crowded destinations attract visitors avoiding overtourism.
MNI_MTEI: ꯃꯤ ꯌꯥꯝꯗꯕ ꯂꯝꯈꯩꯁꯤꯡ ꯑꯁꯤꯅ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯟꯅꯤꯡꯉꯥꯏ ꯑꯣꯏ
--------------------------------------------------

Translating:  66%|█████████████████▋         | 657/1000 [09:15<05:13,  1.09it/s]

[657/1000]
EN: Business travel spending reaches 1.57 trillion dollars in 2025.
MNI_MTEI: ꯏꯪꯁꯣꯛ 2025 ꯗꯥ ꯕꯤꯖꯤꯅꯦꯁ ꯇꯚꯦꯜ ꯆꯥꯗꯤꯡ ꯑꯁꯤ ꯗꯣꯂꯔꯂꯌꯟ ꯌꯧ
--------------------------------------------------

Translating:  66%|█████████████████▊         | 658/1000 [09:16<05:33,  1.03it/s]

[658/1000]
EN: Bleisure travel surge drives business trip extensions for leisure.
MNI_MTEI: ꯏꯖꯔ ꯇꯚꯦꯜꯒꯤ ꯆꯥꯡ ꯍꯦꯟꯒꯠꯂꯛꯄꯅꯥ ꯕꯤꯖꯤꯅꯦꯁꯀꯤ ꯈꯣꯡꯆꯠꯁꯤꯡ ꯃꯇꯝ ꯂꯦꯟꯕꯒꯤꯗꯃꯛꯇ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  66%|█████████████████▊         | 659/1000 [09:17<05:40,  1.00it/s]

[659/1000]
EN: Luxury travel shifts toward immersive experience based vacations.
MNI_MTEI: ꯂꯛꯁꯔꯤ ꯇꯚꯦꯜ ꯑꯁꯤ ꯏꯃꯔꯁꯤꯚ ꯑꯦꯛꯁꯄꯤꯌꯔꯦꯟꯁꯇ ꯌꯨꯝꯐꯝ ꯑꯣꯏꯕ ꯁꯨꯇꯤꯁꯤꯡꯒꯤ ꯃꯥꯏꯀꯩꯗ ꯍꯣꯡꯂꯛꯏ ꯫
--------------------------------------------------

Translating:  66%|█████████████████▊         | 660/1000 [09:18<05:34,  1.02it/s]

[660/1000]
EN: Travvy Awards recognize top industry suppliers in November.
MNI_MTEI: ꯇꯚꯚꯤ ꯑꯦꯋꯥꯔꯗꯅ ꯅꯕꯦꯝꯕꯔꯗꯥ ꯇꯣꯞ ꯏꯟꯗꯁꯇꯒꯤ ꯁꯄꯂꯥꯏꯌꯔꯁꯤꯡꯕꯨ ꯃꯁꯛ ꯈꯪꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  66%|█████████████████▊         | 661/1000 [09:19<05:23,  1.05it/s]

[661/1000]
EN: TravelPulse announces 40 Under 40 honorees for second year.
MNI_MTEI: ꯇꯚꯦꯜꯄꯜꯁꯅꯥ ꯑꯅꯤꯁꯨꯕ ꯆꯍꯤꯒꯤꯗꯃꯛ ꯑꯟꯗꯔ ꯑꯣꯅꯣꯔꯤ 40 ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  66%|█████████████████▊         | 662/1000 [09:20<05:21,  1.05it/s]

[662/1000]
EN: Travel Executive of the Year awarded at Travvy gala.
MNI_MTEI: ꯇꯚꯚꯤ ꯒꯂꯥꯗꯥ ꯏꯌꯔꯒꯤꯚꯦꯕꯦꯜ ꯑꯦꯛꯖꯤꯀꯇꯤꯕꯀꯤ ꯃꯅꯥ ꯄꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  66%|█████████████████▉         | 663/1000 [09:20<05:04,  1.11it/s]

[663/1000]
EN: New members inducted into Travel Hall of Fame 2025.
MNI_MTEI: 2025 ꯗꯥ ꯇꯚꯦꯜ ꯍꯣꯜ ꯑꯣꯐ ꯐꯦꯝꯗꯥ ꯑꯅꯧꯕ ꯃꯤꯍꯨꯠꯁꯤꯡ ꯌꯥꯎꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  66%|█████████████████▉         | 664/1000 [09:21<04:51,  1.15it/s]

[664/1000]
EN: Young professionals recognized for innovation and leadership.
MNI_MTEI: ꯏꯟꯚꯣꯚꯦꯁꯟ ꯑꯃꯁꯨꯡ ꯂꯤꯗꯔꯁꯤꯞꯀꯤꯗꯃꯛ ꯃꯁꯛ ꯈꯪꯂꯕ ꯌꯨꯕꯥꯐꯦꯁꯅꯦꯜꯁꯤꯡ
--------------------------------------------------

Translating:  66%|█████████████████▉         | 665/1000 [09:22<04:59,  1.12it/s]

[665/1000]
EN: FIFA World Cup 2025 travel bookings exceed host city expectations.
MNI_MTEI: ꯐꯤꯐꯥ ꯋꯥꯔꯂꯗ ꯀꯞ 2025 ꯒꯤ ꯇꯚꯦꯜ ꯕꯨꯀꯤꯡꯅꯥ ꯍꯣꯁꯇ ꯁꯤꯇꯤꯗꯥ ꯄꯥꯝꯖꯕꯗꯒꯤ ꯍꯦꯟ
--------------------------------------------------

Translating:  67%|█████████████████▉         | 666/1000 [09:23<04:58,  1.12it/s]

[666/1000]
EN: Solo female travel bookings increase forty percent year on year.
MNI_MTEI: ꯁꯣꯂꯣ ꯚꯤꯃꯦꯅ ꯇꯚꯦꯜ ꯕꯨꯀꯤꯡꯁꯤꯡ ꯑꯁꯤ ꯆꯍꯤꯗꯥ ꯆꯥꯗ ꯃꯔꯤ ꯍꯦꯟꯒꯠꯂꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  67%|██████████████████         | 667/1000 [09:24<05:17,  1.05it/s]

[667/1000]
EN: Wellness tourism emerges as fastest growing travel segment globally.
MNI_MTEI: ꯋꯦꯂꯅꯦꯁ ꯇꯨꯔꯤꯖꯝ ꯑꯁꯤ ꯃꯥꯂꯦꯝ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯊꯨꯅ ꯆꯥꯎꯈꯠꯂꯛꯂꯤꯕ ꯇꯚꯦꯜ ꯁꯦꯒꯃꯦꯟꯇ ꯑꯃ ꯑꯣꯏꯔꯛ
--------------------------------------------------

Translating:  67%|██████████████████         | 668/1000 [09:25<05:05,  1.09it/s]

[668/1000]
EN: Indian millennials prefer experiential travel over shopping vacations.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯃꯤꯂꯦꯅꯤꯌꯦꯜꯁꯤꯡꯅ ꯁꯣꯄꯤꯡ ꯁꯨꯇꯤꯁꯤꯡꯒꯤ ꯃꯍꯨꯠꯇ ꯆꯥꯡꯌꯦꯡꯒꯤ ꯑꯣꯏꯕ ꯂꯝꯀꯣꯏꯕꯁꯤꯡ ꯄꯥꯝꯏ ꯫
--------------------------------------------------

Translating:  67%|██████████████████         | 669/1000 [09:26<05:07,  1.08it/s]

[669/1000]
EN: Workation packages gain popularity among remote corporate employees.
MNI_MTEI: ꯋꯥꯔꯀꯦꯁꯟ ꯄꯦꯀꯦꯖꯁꯤꯡ ꯑꯁꯤ ꯔꯤꯃꯣꯠ ꯀꯣꯔꯄꯣꯔꯦꯠ ꯑꯦꯝꯄꯂꯥꯏꯁꯤꯡꯒꯤ ꯃꯔꯛꯇꯥ ꯃꯤꯌꯥꯝꯅ ꯄꯥꯝꯅꯕ ꯑꯣꯏ ꯫
--------------------------------------------------

Translating:  67%|██████████████████         | 670/1000 [09:27<05:19,  1.03it/s]

[670/1000]
EN: Culinary tourism drives foodies to regional Indian destinations.
MNI_MTEI: ꯀꯨꯂꯤꯅꯔꯤ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯆꯤꯟꯖꯥꯛ ꯄꯥꯝꯖꯕꯁꯤꯡꯕꯨ ꯔꯤꯖꯅꯦꯜ ꯏꯟꯗꯤꯌꯟ ꯗꯦꯇꯤꯁꯟꯁꯤꯡꯗ ꯄꯨꯁꯤꯜꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  67%|██████████████████         | 671/1000 [09:28<04:58,  1.10it/s]

[671/1000]
EN: Night tourism initiatives launched by Maharashtra and Karnataka.
MNI_MTEI: ꯃꯍꯥꯔꯥꯁꯇ ꯑꯃꯁꯨꯡ ꯀꯔꯅꯥꯇꯀꯥꯅꯥ ꯅꯥꯏꯇ ꯇꯨꯔꯤꯖꯝ ꯊꯧꯔꯥꯡꯁꯤꯡ ꯍꯧꯒꯠ
--------------------------------------------------

Translating:  67%|██████████████████▏        | 672/1000 [09:29<05:06,  1.07it/s]

[672/1000]
EN: Astro tourism gains ground with dark sky parks in Ladakh.
MNI_MTEI: ꯂꯗꯥꯈꯀꯤ ꯗꯔꯀꯥꯔꯥꯏ ꯄꯥꯔꯛꯁꯤꯡ ꯂꯩꯕꯅꯥ ꯑꯦꯁꯇ ꯇꯨꯔꯤꯖꯝꯗ ꯀꯥꯟꯅꯕ ꯐꯪ
--------------------------------------------------

Translating:  67%|██████████████████▏        | 673/1000 [09:30<05:10,  1.05it/s]

[673/1000]
EN: Film induced tourism boosts Kashmir valley hotel occupancy.
MNI_MTEI: ꯐꯤꯜꯃ ꯏꯟꯗꯁ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯀꯁꯃꯤꯔ ꯚꯦꯂꯤ ꯍꯣꯇꯦꯜ ꯑꯣꯀꯦꯟꯁꯤ ꯍꯦꯟꯒꯠꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  67%|██████████████████▏        | 674/1000 [09:31<05:01,  1.08it/s]

[674/1000]
EN: Wedding tourism contributes five billion dollars to Indian economy.
MNI_MTEI: ꯋꯦꯗꯤꯡ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯑꯦꯀꯣꯅꯣꯃꯤꯗꯥ ꯗꯣꯂꯔ ꯕꯤꯂꯤꯌꯟ ꯃꯉꯥ ꯄꯤ
--------------------------------------------------

Translating:  68%|██████████████████▏        | 675/1000 [09:31<05:00,  1.08it/s]

[675/1000]
EN: India promotes MICE tourism for meetings and exhibitions.
MNI_MTEI: ꯃꯤꯇꯤꯡꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯑꯦꯛꯖꯤꯕꯤꯁꯟꯁꯤꯡꯒꯤꯗꯃꯛ ꯚꯥꯔꯠꯅ ꯃꯥꯏꯁꯤ ꯇꯨꯔꯤꯖꯝꯕꯨ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▎        | 676/1000 [09:33<05:10,  1.04it/s]

[676/1000]
EN: West Bengal develops MICE tourism segments under Mamata Banerjee.
MNI_MTEI: ꯋꯇ ꯕꯦꯡꯒꯜꯅꯥ ꯃꯃꯇꯥ ꯕꯦꯅꯖꯔꯤꯒꯤ ꯃꯈꯥꯗ ꯃꯥꯏꯁꯤ ꯇꯨꯔꯤꯖꯝ ꯁꯦꯒꯃꯦꯟꯇꯁꯤꯡ ꯁꯦꯝꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▎        | 677/1000 [09:34<05:13,  1.03it/s]

[677/1000]
EN: India positions itself as medical value travel destination.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯃꯁꯥ ꯃꯊꯟꯇ ꯃꯦꯗꯤꯀꯦꯜ ꯚꯦꯜꯌꯨ ꯇꯚꯦꯜ ꯗꯦꯁꯇꯤꯅꯦꯁꯇ ꯑꯣꯏꯔꯦ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▎        | 678/1000 [09:34<04:59,  1.07it/s]

[678/1000]
EN: Wellness tourism positions India as holistic healing leader.
MNI_MTEI: ꯋꯥꯏꯜꯅꯦꯁ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯚꯥꯔꯠꯄꯨ ꯍꯣꯂꯤꯁꯇꯤꯛ ꯍꯤꯂꯤꯡ ꯂꯤꯗꯔ ꯑꯣꯏꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▎        | 679/1000 [09:35<05:16,  1.01it/s]

[679/1000]
EN: Concert tourism attracts international visitors to Indian music festivals.
MNI_MTEI: ꯀꯟꯖꯇ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯃꯖꯤꯀ ꯐꯦꯁꯇꯤꯕꯦꯜꯗꯥ ꯂꯥꯛꯄ ꯃꯤꯌꯣꯏꯁꯤꯡꯕꯨ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▎        | 680/1000 [09:37<05:22,  1.01s/it]

[680/1000]
EN: Gajendra Shekhawat highlights India's concert tourism potential.
MNI_MTEI: ꯒꯖꯦꯟꯗ ꯁꯦꯈꯥꯋꯥꯠꯅ ꯚꯥꯔꯠꯀꯤ ꯏꯁꯩ-ꯆꯥꯔꯣꯡꯒꯤ ꯇꯨꯔꯤꯖꯝꯒꯤ ꯑꯣꯏꯊꯣꯛꯄ ꯌꯥꯕ ꯑꯗꯨ ꯃꯁꯛ ꯇꯥꯛ
--------------------------------------------------

Translating:  68%|██████████████████▍        | 681/1000 [09:38<05:35,  1.05s/it]

[681/1000]
EN: India promotes integrated rehabilitation pathways for medical tourists.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯃꯦꯗꯤꯀꯦꯜ ꯇꯨꯔꯤꯁꯇꯁꯤꯡꯒꯤꯗꯃꯛ ꯏꯟꯇꯤꯒꯇꯦꯗ ꯔꯤꯍꯦꯕꯂꯤꯇꯦꯁꯟ ꯄꯥꯊꯋꯦꯁꯤꯡ ꯌꯣꯛꯈꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▍        | 682/1000 [09:39<05:16,  1.01it/s]

[682/1000]
EN: Business travel makes significant comeback post pandemic.
MNI_MTEI: ꯄꯦꯟꯗꯃꯤꯛ ꯂꯥꯛꯂꯕ ꯃꯇꯨꯡꯗ ꯕꯤꯖꯤꯅꯦꯁ ꯇꯚꯦꯜꯅꯥ ꯃꯁꯛ ꯊꯣꯛꯄ ꯃꯑꯣꯡꯗ ꯑꯃꯨꯛ ꯍꯜꯂꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▍        | 683/1000 [09:39<05:06,  1.04it/s]

[683/1000]
EN: Companies increase trip volumes and expand travel budgets.
MNI_MTEI: ꯀꯝꯄꯅꯤꯁꯤꯡꯅ ꯇꯄꯀꯤ ꯆꯥꯡ ꯍꯦꯟꯒꯠꯍꯜꯂꯤ ꯑꯃꯁꯨꯡ ꯂꯝꯀꯣꯏꯕꯒꯤ ꯁꯦꯟꯐꯝꯁꯤꯡ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▍        | 684/1000 [09:41<05:15,  1.00it/s]

[684/1000]
EN: In-person collaboration demand drives business travel recovery.
MNI_MTEI: ꯏꯟ-ꯄꯔꯁꯟ ꯀꯣꯂꯣꯕꯥꯔꯦꯁꯟ ꯗꯤꯃꯥꯟꯗꯅ ꯕꯤꯖꯤꯅꯦꯁ ꯇꯚꯦꯜ ꯔꯤꯀꯥꯎꯔꯤ ꯊꯧꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  68%|██████████████████▍        | 685/1000 [09:42<05:21,  1.02s/it]

[685/1000]
EN: Hyderabad International Convention Centre hosts global pharmaceutical summit.
MNI_MTEI: ꯍꯥꯏꯗꯕꯥꯗ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯀꯟꯚꯦꯟꯁꯟ ꯁꯦꯟꯇꯔꯅꯥ ꯒ ꯭ ꯂꯣꯕꯦꯜ ꯐꯥꯔꯃꯥꯁꯤꯌꯨꯇꯤꯀꯦꯜ ꯁꯝꯃꯤꯠ ꯄꯥꯡꯊꯣꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  69%|██████████████████▌        | 686/1000 [09:43<05:19,  1.02s/it]

[686/1000]
EN: Bharat Mandapam witnesses record MICE bookings for fiscal year.
MNI_MTEI: ꯚꯥꯔꯠ ꯃꯟꯗꯄꯃꯗꯥ ꯁꯦꯜ-ꯊꯨꯝꯒꯤ ꯆꯍꯤꯒꯤꯗꯃꯛ ꯃꯥꯏꯁꯤ ꯕꯨꯀꯤꯡꯁꯤꯡ ꯔꯦꯀꯣꯔ ꯇꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  69%|██████████████████▌        | 687/1000 [09:44<05:20,  1.02s/it]

[687/1000]
EN: Medical tourism arrivals cross pre-Covid levels with six lakh visitors.
MNI_MTEI: ꯃꯦꯗꯤꯀꯦꯜ ꯇꯨꯔꯤꯖꯝ ꯂꯥꯛꯄꯥꯁꯤꯡꯅ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯇꯔꯨꯛ ꯄꯨꯗꯨꯅ-ꯀꯣꯕꯤꯗ ꯂꯦꯚꯦꯜꯁꯤꯡ ꯐꯥꯎ
--------------------------------------------------

Translating:  69%|██████████████████▌        | 688/1000 [09:45<05:13,  1.00s/it]

[688/1000]
EN: AYUSH wellness centres attract foreign tourists for traditional treatments.
MNI_MTEI: ꯑꯥꯌꯨꯁ ꯋꯦꯜꯅꯦꯁ ꯁꯦꯟꯇꯔꯁꯤꯡ ꯑꯁꯤꯅ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯕꯨ ꯊꯥꯏꯅꯗꯒꯤ ꯆꯠꯅꯔꯕꯥ ꯂꯥꯌꯦꯡꯁꯤꯡꯒꯤꯗꯃꯛꯇ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  69%|██████████████████▌        | 689/1000 [09:46<05:20,  1.03s/it]

[689/1000]
EN: Delhi NCR hotels report seventy percent occupancy from corporate travellers.
MNI_MTEI: ꯗꯤꯜꯂꯤ ꯑꯦꯟ ꯁꯤ ꯑꯥꯔ ꯍꯣꯇꯦꯜꯁꯤꯡꯅꯥ ꯀꯣꯔꯄꯣꯔꯦꯠ ꯇꯚꯦꯂꯔꯁꯤꯡꯗꯒꯤ ꯆꯥꯗꯥ 70 ꯑꯣꯀꯦꯟꯁꯤ ꯐꯪꯉꯤ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝ
--------------------------------------------------

Translating:  69%|██████████████████▋        | 690/1000 [09:47<05:27,  1.06s/it]

[690/1000]
EN: Maha Kumbh infrastructure delivers long-term tourism economic benefits.
MNI_MTEI: ꯃꯍꯥ ꯀꯨꯝꯚ ꯏꯟꯐꯁꯇꯛꯆꯔꯅꯥ ꯂꯥꯡ-ꯇꯔꯃ ꯇꯨꯔꯤꯖꯝ ꯏꯀꯅꯣꯃꯤꯀꯦꯜ ꯕꯦꯅꯤꯐꯤꯇꯁꯤꯡ ꯄꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  69%|██████████████████▋        | 691/1000 [09:48<05:28,  1.06s/it]

[691/1000]
EN: Venice entry fee revenues fund city upkeep and travel management.
MNI_MTEI: ꯚꯦꯅꯤꯁ ꯑꯦꯟꯇꯤ ꯐꯤ ꯔꯦꯚꯤꯅꯁ ꯐꯟꯗ ꯁꯤꯇꯤ ꯎꯄꯄꯤꯅꯦꯟꯇ ꯑꯃꯁꯨꯡ ꯇꯚꯦꯜ ꯃꯦꯅꯦꯃꯦꯅꯇ
--------------------------------------------------

Translating:  69%|██████████████████▋        | 692/1000 [09:49<05:37,  1.10s/it]

[692/1000]
EN: Critics question Venice day-tripper fee effectiveness for crowd control.
MNI_MTEI: ꯚꯤꯅꯤꯁ ꯗꯦ-ꯥꯏꯄꯔ ꯐꯤ ꯑꯦꯐꯦꯛꯇꯤꯚꯦꯟꯁꯤꯕꯨ ꯀꯥꯎꯗ ꯀꯟꯇꯣꯜ ꯇꯧꯅꯕꯒꯤꯗꯃꯛꯇꯤꯛꯁꯅꯥ ꯈꯟꯅ
--------------------------------------------------

Translating:  69%|██████████████████▋        | 693/1000 [09:50<05:20,  1.05s/it]

[693/1000]
EN: Bulgaria joins Eurozone as twenty-first member on January 1 2026.
MNI_MTEI: ꯏꯪꯁꯣꯛꯒꯤ ꯖꯅꯨꯋꯥꯔꯤꯗꯥ ꯕꯂꯒꯦꯔꯤꯌꯥꯅꯥ ꯌꯨꯔꯣꯖꯣꯅꯗꯥ ꯑꯍꯥꯟꯕ ꯃꯦꯝꯕꯔ ꯑꯣꯏꯅ ꯌꯥꯎ
--------------------------------------------------

Translating:  69%|██████████████████▋        | 694/1000 [09:51<05:01,  1.02it/s]

[694/1000]
EN: Both Lev and Euro accepted in Bulgaria during January transition.
MNI_MTEI: ꯂꯦꯚ ꯑꯃꯁꯨꯡ ꯌꯨꯔꯣ ꯑꯅꯤꯃꯛꯅ ꯖꯅꯨꯋꯥꯔꯤ ꯇꯥꯟꯖꯤꯁꯟꯒꯤ ꯃꯇꯝꯗ ꯕꯂꯒꯦꯔꯤꯌꯥꯗꯥ ꯑꯌꯥꯕ ꯄꯤ
--------------------------------------------------

Translating:  70%|██████████████████▊        | 695/1000 [09:52<05:28,  1.08s/it]

[695/1000]
EN: Lufthansa announces daily Frankfurt-Bengaluru flights starting March 2026.
MNI_MTEI: ꯂꯨꯐꯊꯥꯟꯁꯥꯅꯥ ꯏꯪꯁꯣꯛꯒꯤ ꯃꯥꯔꯗꯒꯤ ꯅꯨꯃꯤꯠ ꯈꯨꯗꯤꯡꯒꯤ ꯐꯟꯐꯔꯇ- ꯕꯦꯡꯒꯂꯨꯔꯨꯗꯥ ꯄꯥꯏꯔꯛꯀꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  70%|██████████████████▊        | 696/1000 [09:53<05:06,  1.01s/it]

[696/1000]
EN: Alliance Air introduces direct flights from Delhi to Darbhanga.
MNI_MTEI: ꯑꯦꯂꯥꯏꯟꯁ ꯑꯦꯌꯔꯅꯥ ꯗꯤꯜꯂꯤꯗꯒꯤ ꯗꯥꯔꯚꯪꯒꯥ ꯐꯥꯎꯕ ꯍꯛꯊꯦꯡꯅꯅ ꯐꯥꯏꯇꯁꯤꯡ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  70%|██████████████████▊        | 697/1000 [09:54<05:01,  1.01it/s]

[697/1000]
EN: Emirates deploys A380 on Ahmedabad-Dubai route for winter season.
MNI_MTEI: ꯑꯦꯃꯤꯔꯦꯠꯁꯅ ꯅꯤꯡꯊꯝꯊꯥꯒꯤꯗꯃꯛ ꯑꯍꯃꯗꯕꯥꯗ- ꯗꯨꯕꯥꯏ ꯂꯝꯕꯤꯗꯥ ꯑꯦ380 ꯁꯤꯖꯤꯟꯅ
--------------------------------------------------

Translating:  70%|██████████████████▊        | 698/1000 [09:55<04:43,  1.06it/s]

[698/1000]
EN: fly91 commences operations from Goa to Hyderabad and Pune.
MNI_MTEI: ꯂꯥꯏ91 ꯑꯁꯤ ꯒꯣꯋꯥꯗꯒꯤ ꯍꯥꯏꯗꯕꯥꯗ ꯑꯃꯁꯨꯡ ꯄꯨꯅꯦ ꯐꯥꯎꯕꯒꯤ ꯊꯕꯛ ꯍꯧ
--------------------------------------------------

Translating:  70%|██████████████████▊        | 699/1000 [09:56<04:39,  1.08it/s]

[699/1000]
EN: British Airways resumes London-Chennai service after four-year hiatus.
MNI_MTEI: ꯕꯇꯤꯁ ꯑꯦꯌꯔꯋꯦꯖꯅ ꯆꯍꯤ ꯃꯔꯤꯒꯤ ꯃꯇꯨꯡꯗ ꯂꯟꯗꯟ-ꯆꯦꯟꯅꯥꯏ ꯁꯔꯕꯤꯁ ꯑꯃꯨꯛ ꯍꯟꯅ ꯍꯧ
--------------------------------------------------

Translating:  70%|██████████████████▉        | 700/1000 [09:57<04:43,  1.06it/s]

[700/1000]
EN: Go First employees protest outside NCLT over unpaid salaries.
MNI_MTEI: ꯒꯣ ꯐꯔꯁꯠ ꯏꯝꯄꯂꯥꯏꯖꯅꯥ ꯑꯦꯟ.ꯁꯤ. ꯑꯦꯜ.ꯇꯤ.ꯒꯤ ꯃꯄꯥꯟꯗ ꯁꯦꯜ ꯊꯤꯗꯕꯗꯥ ꯋꯥꯀꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  70%|██████████████████▉        | 701/1000 [09:58<05:05,  1.02s/it]

[701/1000]
EN: Saudi carrier Flynas plans direct Riyadh-Lucknow operations by April.
MNI_MTEI: ꯁꯧꯗꯤ ꯀꯦꯔꯤꯌꯔ ꯐꯅꯥꯏꯅꯥꯁꯅꯥ ꯑꯦꯄꯜ ꯐꯥꯎꯕꯗ ꯔꯤꯌꯥꯗ-ꯂꯀꯅꯣ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡ ꯗꯥꯏꯔꯦꯛꯇ ꯇꯧꯅꯕ ꯊꯧꯔꯥꯡ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  70%|██████████████████▉        | 702/1000 [09:59<05:08,  1.03s/it]

[702/1000]
EN: Flybig announces daily flights from Guwahati to Imphal and Agartala.
MNI_MTEI: ꯂꯥꯏꯕꯤꯒꯅꯥ ꯒꯨꯋꯥꯍꯥꯇꯤꯗꯒꯤ ꯏꯝꯐꯣꯜ ꯑꯃꯁꯨꯡ ꯑꯒꯔꯇꯂꯥ ꯐꯥꯎꯕꯒꯤ ꯅꯨꯃꯤꯠ ꯈꯨꯗꯤꯡꯒꯤ ꯐꯥꯏꯇꯁꯤꯡ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  70%|██████████████████▉        | 703/1000 [10:00<05:29,  1.11s/it]

[703/1000]
EN: Kolkata airport wins cleanest airport award in 15-25 million category.
MNI_MTEI: ꯀꯣꯜꯀꯥꯇꯥ ꯑꯦꯌꯔꯄꯣꯔꯇꯅꯥ ꯀꯦꯇꯦꯒꯣꯔꯤ ꯃꯤꯂ ꯭ ꯌꯟ- ꯐꯥꯎꯕ ꯑꯣꯏꯔꯗꯨꯅ ꯀꯂꯦꯅꯦꯁꯇ ꯑꯦꯔꯕꯥꯣꯔꯇ ꯑꯦꯋꯥꯔ ꯐꯪ
--------------------------------------------------

Translating:  70%|███████████████████        | 704/1000 [10:01<05:15,  1.06s/it]

[704/1000]
EN: Patna airport's new terminal to handle forty lakh passengers annually.
MNI_MTEI: ꯆꯍꯤꯗꯥ ꯄꯇꯅꯥ ꯑꯦꯌꯔꯄꯣꯔꯇꯀꯤ ꯑꯅꯧꯕ ꯇꯔꯃꯤꯅꯦꯜꯅꯥ ꯄꯦꯁꯦꯟꯖꯔ ꯂꯥꯈ ꯍꯦꯟꯗꯜ ꯇꯧꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  70%|███████████████████        | 705/1000 [10:02<05:02,  1.03s/it]

[705/1000]
EN: Fog forces thirty-two flight diversions at Chandigarh airport.
MNI_MTEI: ꯆꯟꯗꯤꯒꯔ ꯑꯦꯌꯔꯄꯣꯔꯇꯇꯥ ꯐꯥꯏꯇ ꯑꯍꯨꯝꯂꯛ ꯗꯤꯚꯔꯁꯟ ꯇꯧꯍꯟꯕꯥ ꯃꯊꯧ ꯇꯥꯔꯤ ꯫
--------------------------------------------------

Translating:  71%|███████████████████        | 706/1000 [10:03<04:59,  1.02s/it]

[706/1000]
EN: Ethiopian Airlines considers Mumbai and Delhi as new African hub.
MNI_MTEI: ꯏꯊꯤꯑꯣꯄꯤꯌꯥꯟ ꯑꯦꯌꯔꯂꯥꯏꯟꯁꯅꯥ ꯃꯨꯝꯕꯥꯏ ꯑꯃꯁꯨꯡ ꯗꯤꯜꯂꯤꯕꯨ ꯑꯐꯀꯥꯒꯤ ꯑꯍꯥꯟꯕꯥ ꯃꯐꯝ ꯑꯃ ꯑꯣꯏꯅ ꯂꯧ
--------------------------------------------------

Translating:  71%|███████████████████        | 707/1000 [10:04<04:53,  1.00s/it]

[707/1000]
EN: IndiGo passenger dies aboard Delhi-Bengaluru flight mid-air.
MNI_MTEI: ꯗꯤꯜꯂꯤ- ꯕꯦꯡ ꯭ ꯒꯂꯨꯔꯨ ꯐꯥꯏꯇꯗꯥ ꯏꯟꯗꯤꯒꯣ ꯄꯦꯁꯦꯟꯖꯔ ꯁꯤꯈꯤ ꯫
--------------------------------------------------

Translating:  71%|███████████████████        | 708/1000 [10:05<04:48,  1.01it/s]

[708/1000]
EN: VietJet Air announces daily Hanoi-Ahmedabad service from December.
MNI_MTEI: ꯚꯤꯌꯦꯇꯖꯦꯠ ꯑꯦꯌꯔꯅꯥ ꯗꯤꯁꯦꯝꯕꯔꯗꯒꯤ ꯍꯅꯣꯏ-ꯍꯃꯦꯗꯥꯕꯥꯗ ꯅꯨꯃꯤꯠ ꯈꯨꯗꯤꯡꯒꯤ ꯁꯔꯕꯤꯁ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  71%|███████████████████▏       | 709/1000 [10:06<04:29,  1.08it/s]

[709/1000]
EN: Odisha government approves ten new tourism circuits for development.
MNI_MTEI: ꯑꯣꯔꯤꯁꯥ ꯁꯔꯀꯥꯔꯅꯥ ꯆꯥꯎꯈꯠꯅꯕꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯇꯨꯔꯤꯖꯝ ꯁꯔꯀꯤꯇ ꯇꯔꯥ ꯑꯌꯥꯕ ꯄꯤꯔꯦ ꯫
--------------------------------------------------

Translating:  71%|███████████████████▏       | 710/1000 [10:07<04:18,  1.12it/s]

[710/1000]
EN: Madhya Pradesh unveils film tourism policy with 25 percent subsidy.
MNI_MTEI: ꯃꯙꯅꯥ ꯁꯕꯁꯤꯗꯤ ꯆꯥꯗꯒꯥ ꯂꯣꯏꯅꯅ ꯐꯤꯜꯃ ꯇꯨꯔꯤꯖꯝ ꯄꯣꯂꯤꯁꯤ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  71%|███████████████████▏       | 711/1000 [10:07<04:14,  1.13it/s]

[711/1000]
EN: Gujarat grants industry status to homestays and farmstays.
MNI_MTEI: ꯒꯨꯖꯔꯥꯠꯅ ꯍꯣꯝꯇꯦ ꯑꯃꯁꯨꯡ ꯐꯥꯔꯃꯇꯦꯗ ꯏꯟꯗꯁꯇꯇꯤꯒꯤ ꯊꯥꯛ ꯄꯤ ꯫
--------------------------------------------------

Translating:  71%|███████████████████▏       | 712/1000 [10:08<04:13,  1.14it/s]

[712/1000]
EN: Himachal Pradesh caps tourist entry to Manali and Rohtang Pass.
MNI_MTEI: ꯍꯤꯃꯥꯁꯥꯜꯗꯒꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯅ ꯃꯅꯥꯂꯤ ꯑꯃꯁꯨꯡ ꯔꯣꯍꯇꯥꯡ ꯄꯥꯁꯇ ꯆꯪꯁꯤꯜꯂꯛ
--------------------------------------------------

Translating:  71%|███████████████████▎       | 713/1000 [10:09<04:28,  1.07it/s]

[713/1000]
EN: Kerala launches responsible tourism mission for waste-free destinations.
MNI_MTEI: ꯀꯦꯔꯂꯥꯅꯥ ꯋꯇ-ꯐ ꯗꯦꯅꯦꯁꯟꯒꯤꯗꯃꯛ ꯔꯦꯖꯤꯄꯂꯦꯇꯤꯕ ꯇꯨꯔꯤꯖꯝ ꯃꯤꯁꯟ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  71%|███████████████████▎       | 714/1000 [10:10<04:15,  1.12it/s]

[714/1000]
EN: Australia removes minimum bank balance requirement for Indian student visas.
MNI_MTEI: ꯑꯣꯁꯇꯂꯤꯌꯥꯅꯥ ꯏꯟꯗꯤꯌꯟꯗꯦꯟꯇ ꯚꯤꯖꯥꯒꯤ ꯃꯤꯅꯤꯃꯃꯜ ꯕꯦꯡꯀ ꯕꯦꯂꯦꯟꯁꯀꯤ ꯃꯊꯧ ꯇꯥꯕꯥ ꯑꯗꯨ ꯂꯧꯊꯣꯛ
--------------------------------------------------

Translating:  72%|███████████████████▎       | 715/1000 [10:11<04:07,  1.15it/s]

[715/1000]
EN: UK introduces Electronic Travel Authorisation for Indian passport holders.
MNI_MTEI: ꯌꯨꯀꯦꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯄꯥꯁꯄꯣꯔꯇ ꯍꯣꯜꯗꯔꯁꯤꯡꯒꯤꯗꯃꯛ ꯏꯂꯦꯛꯇꯅꯤꯛ ꯇꯚꯦꯜ ꯑꯣꯊꯔꯤꯖꯦꯁꯟ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  72%|███████████████████▎       | 716/1000 [10:12<03:57,  1.20it/s]

[716/1000]
EN: Saudi Arabia extends stopover visa validity from four to ninety-six hours.
MNI_MTEI: ꯁꯧꯗꯤ ꯑꯔꯦꯕꯤꯌꯥꯅꯥ ꯁꯇꯣꯞꯑꯣꯚꯔ ꯚꯤꯖꯥꯒꯤ ꯕꯦꯂꯤꯗꯤꯇꯤ ꯄꯨꯡ ꯃꯔꯤꯗꯒꯤ 95 ꯐꯥꯎꯕ ꯍꯦꯟꯒꯠ
--------------------------------------------------

Translating:  72%|███████████████████▎       | 717/1000 [10:13<03:53,  1.21it/s]

[717/1000]
EN: Malaysia grants thirty-day visa-free entry to Indian nationals till December.
MNI_MTEI: ꯃꯂꯦꯁꯤꯌꯥꯅꯥ ꯗꯤꯁꯦꯝꯕꯔ ꯐꯥꯎꯕꯗ ꯚꯥꯔꯠꯀꯤ ꯅꯦꯁ ꯭ ꯅꯦꯜꯁꯤꯡꯗ ꯅꯨꯃꯤꯠ ꯑꯍꯨꯝꯅꯤꯒꯤ ꯚꯤꯖꯥ-ꯐ ꯑꯦꯟꯔꯤ ꯄꯤ
--------------------------------------------------

Translating:  72%|███████████████████▍       | 718/1000 [10:13<03:39,  1.28it/s]

[718/1000]
EN: Thailand extends visa-free stay for Indians from thirty to sixty days.
MNI_MTEI: ꯊꯥꯏꯂꯦꯟꯗꯅꯥ ꯚꯥꯔꯠ ꯃꯆꯥꯁꯤꯡꯒꯤ ꯚꯤꯖꯥ ꯌꯥꯎꯗꯅ ꯂꯩꯕꯒꯤ ꯃꯇꯝ ꯑꯁꯤ ꯅꯨꯃꯤꯠ ꯑꯍꯨꯝꯗꯒꯤ ꯇꯔꯥꯃꯥꯇꯤ ꯐꯥꯎꯕ ꯍꯦꯟꯒꯠ
--------------------------------------------------

Translating:  72%|███████████████████▍       | 719/1000 [10:14<03:39,  1.28it/s]

[719/1000]
EN: Indonesia proposes visa-free entry for Indian tourists to boost Bali arrivals.
MNI_MTEI: ꯏꯟꯗꯣꯅꯦꯁꯤꯌꯥꯅꯥ ꯕꯥꯂꯤꯗꯒꯤ ꯂꯥꯛꯄ ꯍꯦꯟꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯚꯤꯖꯥ ꯌꯥꯎꯗꯅ ꯆꯪꯐꯝ ꯁꯦꯝꯅꯕ ꯋꯥꯐꯝ ꯊꯝ
--------------------------------------------------

Translating:  72%|███████████████████▍       | 720/1000 [10:15<03:44,  1.25it/s]

[720/1000]
EN: European Parliament approves ETIAS system launch for mid-2026.
MNI_MTEI: ꯌꯨꯔꯣꯄꯤꯌꯟ ꯄꯥꯔꯂꯤꯌꯥꯃꯦꯟꯇꯅꯥ ꯏꯪꯁꯣꯛꯒꯤ ꯃꯌꯥꯏ ꯆꯜꯂꯛꯄꯗ ꯏꯇꯤꯑꯦꯑꯦꯁ ꯁꯤꯁꯇꯦꯝ ꯂꯣꯆ ꯇꯧꯕ ꯌꯥꯔꯦ ꯫
--------------------------------------------------

Translating:  72%|███████████████████▍       | 721/1000 [10:16<03:47,  1.22it/s]

[721/1000]
EN: Sri Lanka cabinet approves visa-free entry for nationals of thirty-five countries.
MNI_MTEI: ꯂꯡꯀꯥ ꯀꯦꯕꯤꯅꯦꯠꯅꯥ ꯂꯩꯕꯥꯛ 35ꯒꯤ ꯅꯦꯁ ꯭ ꯅꯦꯜꯁꯤꯡꯒꯤꯗꯃꯛ ꯚꯤꯖꯥ-ꯐ ꯑꯦꯟꯇ ꯑꯌꯥꯕ ꯄꯤꯔꯦ ꯫
--------------------------------------------------

Translating:  72%|███████████████████▍       | 722/1000 [10:16<03:31,  1.31it/s]

[722/1000]
EN: Waives visa fees for Indian senior citizens above sixty-five years.
MNI_MTEI: ꯆꯍꯤ ꯇꯔꯨꯛ- ꯃꯉꯥꯒꯤ ꯃꯊꯛꯇ ꯂꯩꯕ ꯏꯟꯗꯤꯌꯟ ꯁꯦꯅꯤꯌꯔ ꯁꯤꯇꯤꯖꯟꯁꯤꯡꯒꯤ ꯚꯤꯖꯥ ꯐꯤꯁꯤꯡ ꯂꯧꯊꯣꯛꯏ ꯫
--------------------------------------------------

Translating:  72%|███████████████████▌       | 723/1000 [10:17<03:36,  1.28it/s]

[723/1000]
EN: Bhutan revises Sustainable Development Fee to one thousand two hundred rupees.
MNI_MTEI: ꯚꯨꯇꯥꯟꯅ ꯁꯁꯇꯦꯅꯦꯁꯇꯦꯕꯜ ꯗꯦꯚꯂꯞꯃꯦꯟꯇ ꯐꯤ ꯑꯁꯤ ꯂꯨꯄꯥ ꯆꯥꯃ ꯂꯤꯁꯤꯡ ꯑꯅꯤꯗ ꯔꯤꯚꯥꯏꯖ ꯇꯧꯔꯦ ꯫
--------------------------------------------------

Translating:  72%|███████████████████▌       | 724/1000 [10:18<03:35,  1.28it/s]

[724/1000]
EN: Nepal allows Indian tourists to pay in rupees at immigration checkpoints.
MNI_MTEI: ꯅꯦꯄꯥꯜꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯕꯨ ꯏꯃꯤꯒꯦꯁꯟ ꯆꯦꯛꯄꯣꯏꯟꯇꯁꯤꯡꯗ ꯂꯨꯄꯥꯗꯥ ꯁꯦꯜ ꯄꯤꯕꯒꯤ ꯑꯌꯥꯕ ꯄꯤ
--------------------------------------------------

Translating:  72%|███████████████████▌       | 725/1000 [10:19<03:25,  1.34it/s]

[725/1000]
EN: Myanmar junta extends e-visa facility for Indian travellers.
MNI_MTEI: ꯃ ꯭ ꯌꯥꯟꯃꯥꯔ ꯖꯟꯇꯥꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯏ-ꯚꯤꯖꯥ ꯐꯦꯁꯤꯂꯤꯇꯤ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  73%|███████████████████▌       | 726/1000 [10:19<03:29,  1.31it/s]

[726/1000]
EN: Mauritius scraps PCR test requirement for fully vaccinated Indian visitors.
MNI_MTEI: ꯃꯣꯔꯤꯁꯁꯅ ꯃꯄꯨꯡꯐꯥꯅꯥ ꯕꯦꯛꯁꯤꯅꯦꯁꯟ ꯇꯧꯔꯕꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤ ꯄꯤ ꯁꯤ ꯑꯥꯔ ꯇꯦꯁꯇ ꯃꯊꯧ ꯇꯥꯕ ꯑꯗꯨ ꯂꯧꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  73%|███████████████████▋       | 727/1000 [10:20<03:20,  1.36it/s]

[727/1000]
EN: Kenya removes visa requirement for all Indian passport holders.
MNI_MTEI: ꯀꯦꯅꯦꯌꯥꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯄꯥꯁꯄꯣꯔꯇ ꯍꯣꯜꯗꯔ ꯄꯨꯝꯅꯃꯛꯀꯤ ꯚꯤꯖꯥ ꯃꯊꯧ ꯇꯥꯕꯥ ꯂꯧꯊꯣꯛ
--------------------------------------------------

Translating:  73%|███████████████████▋       | 728/1000 [10:21<03:14,  1.40it/s]

[728/1000]
EN: Rajasthan government launches mobile app for heritage hotel bookings.
MNI_MTEI: ꯔꯥꯖꯁꯊꯥꯟ ꯁꯔꯀꯥꯔꯅꯥ ꯍꯦꯔꯤꯇꯦꯖ ꯍꯣꯇꯦꯜ ꯕꯨꯀꯤꯡꯒꯤꯗꯃꯛ ꯃꯣꯕꯥꯏꯜ ꯑꯦꯞ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  73%|███████████████████▋       | 729/1000 [10:21<03:12,  1.41it/s]

[729/1000]
EN: Assam receives fifty-five lakh domestic tourists during 2024-2025.
MNI_MTEI: ꯏꯪꯁꯣꯛ- ꯒꯤ ꯃꯅꯨꯡꯗ ꯑꯁꯥꯝꯗꯥ ꯗꯣꯃꯦꯁꯇꯤꯛ ꯇꯨꯔꯤꯁꯇ ꯂꯥꯈ ꯃꯉꯥ ꯐꯪ
--------------------------------------------------

Translating:  73%|███████████████████▋       | 730/1000 [10:22<03:13,  1.39it/s]

[730/1000]
EN: Hemanta Biswa Sarma credits improved law and order for tourism growth.
MNI_MTEI: ꯍꯦꯃꯟꯇ ꯕꯤꯁꯋꯥ ꯁꯔꯃꯥꯅꯥ ꯇꯨꯔꯤꯖꯝ ꯆꯥꯎꯈꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯂꯣ ꯑꯃꯁꯨꯡ ꯑꯣꯔꯗꯔ ꯐꯒꯠꯍꯟꯈꯤꯕꯒꯤ ꯃꯅꯥ ꯄꯤ
--------------------------------------------------

Translating:  73%|███████████████████▋       | 731/1000 [10:23<03:03,  1.46it/s]

[731/1000]
EN: Madhya Pradesh records 112.1 million tourist visits in 2024.
MNI_MTEI: ꯃꯙ ꯄꯗꯥ ꯏꯪ 2024 ꯗꯥ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯂꯥꯛꯄꯥ ꯆꯦꯖꯟ
--------------------------------------------------

Translating:  73%|███████████████████▊       | 732/1000 [10:24<03:06,  1.44it/s]

[732/1000]
EN: Meghalaya welcomes twenty-one lakh visitors crossing pre-pandemic figures.
MNI_MTEI: ꯃꯦꯘꯂꯌꯅꯥ ꯄꯦꯟꯗꯃꯤꯛ ꯃꯃꯥꯡꯗ ꯂꯥꯛꯄꯥ ꯃꯁꯤꯡ ꯂꯥꯈ 21 ꯐꯥꯎꯕꯥ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯕꯨ ꯊꯥꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  73%|███████████████████▊       | 733/1000 [10:24<03:05,  1.44it/s]

[733/1000]
EN: Jammu and Kashmir registers two crore tourist footfall in 2025.
MNI_MTEI: ꯏꯪꯁꯣꯛ 2025 ꯗꯥ ꯖꯝꯃꯨ ꯑꯃꯁꯨꯡ ꯀꯁꯃꯤꯔꯗꯥ ꯂꯝꯀꯣꯏꯕ ꯀꯔꯣꯔ ꯑꯅꯤ ꯂꯥꯛ
--------------------------------------------------

Translating:  73%|███████████████████▊       | 734/1000 [10:25<03:15,  1.36it/s]

[734/1000]
EN: LG Manoj Sinha announces highest ever tourist arrival in Kashmir Valley.
MNI_MTEI: ꯑꯦꯜ.ꯖꯤ. ꯃꯅꯣꯖ ꯁꯤꯟꯍꯥꯅꯥ ꯀꯁꯃꯤꯔ ꯋꯥꯂꯤꯗꯥ ꯍꯧꯖꯤꯛ ꯐꯥꯎꯕꯗ ꯋꯥꯡꯕꯥ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯛꯂꯦ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  74%|███████████████████▊       | 735/1000 [10:26<03:14,  1.36it/s]

[735/1000]
EN: Lakshadweep receives eighty-three thousand visitors after PM Modi visit.
MNI_MTEI: ꯙꯥꯟ ꯃꯟꯇ ꯃꯣꯗꯤꯒꯤ ꯈꯣꯡꯆꯠꯀꯤ ꯃꯇꯨꯡꯗ ꯂꯛꯁꯗꯄꯇꯥ ꯂꯝꯀꯣꯏꯕ ꯂꯤꯁꯤꯡ 80- ꯐꯪ
--------------------------------------------------

Translating:  74%|███████████████████▊       | 736/1000 [10:27<03:16,  1.34it/s]

[736/1000]
EN: Uttarakhand witnesses five crore pilgrim visits to Char Dham shrines.
MNI_MTEI: ꯎꯠꯇꯔꯥꯈꯟꯗꯗꯥ ꯆꯔ ꯙꯥꯃ ꯂꯥꯏꯁꯡꯗꯥ ꯂꯥꯏꯐꯝ ꯆꯠꯄꯒꯤ ꯃꯤꯑꯣꯏ ꯀꯔꯣꯔ ꯃꯉꯥ ꯂꯥꯛꯄꯥ ꯎ
--------------------------------------------------

Translating:  74%|███████████████████▉       | 737/1000 [10:27<03:17,  1.33it/s]

[737/1000]
EN: Pushkar fair attracts fifteen lakh tourists including thirty thousand foreigners.
MNI_MTEI: ꯄꯨꯁꯀꯔ ꯃꯦꯂꯥꯅꯥ ꯃꯄꯥꯟ ꯂꯩꯕꯥꯛꯀꯤ ꯃꯤꯑꯣꯏ ꯂꯤꯁꯤꯡ ꯑꯍꯨꯝꯃꯨꯛ ꯌꯥꯎꯅ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ 15 ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  74%|███████████████████▉       | 738/1000 [10:28<03:10,  1.38it/s]

[738/1000]
EN: Surajkund Mela records forty-eight percent increase in international participation.
MNI_MTEI: ꯁꯨꯔꯖꯀꯨꯟꯗ ꯃꯦꯂꯥꯅꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯁꯔꯨꯛ ꯌꯥꯕꯒꯤ ꯆꯥꯡ ꯆꯥꯗ 48 ꯍꯦꯟꯒꯠꯂꯛꯄꯒꯤ ꯔꯦꯀꯣꯔ
--------------------------------------------------

Translating:  74%|███████████████████▉       | 739/1000 [10:29<03:13,  1.35it/s]

[739/1000]
EN: Singapore welcomes 1.2 million Indian visitors becoming top source market.
MNI_MTEI: ꯁꯤꯡꯒꯥꯄꯨꯔꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈꯕꯨ ꯑꯍꯥꯟꯕꯥ ꯁꯣꯁꯔ ꯃꯥꯔꯀꯦꯇ ꯑꯣꯏꯔꯛꯄꯗꯥ ꯊꯥꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  74%|███████████████████▉       | 740/1000 [10:29<03:09,  1.37it/s]

[740/1000]
EN: Dubai hosts record 2.1 million Indian tourists in first half 2025.
MNI_MTEI: ꯏꯪꯁꯣꯛ 2025 ꯒꯤ ꯑꯍꯥꯟꯕ ꯁꯔꯨꯛꯗꯥ ꯗꯕꯥꯏꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯒꯤ ꯔꯦꯀꯣꯔ ꯇꯧ
--------------------------------------------------

Translating:  74%|████████████████████       | 741/1000 [10:30<02:57,  1.46it/s]

[741/1000]
EN: Thailand receives 1.8 million Indian travellers during January-October period.
MNI_MTEI: ꯊꯥꯏꯂꯦꯟꯗꯗꯥ ꯖꯅꯨꯋꯥꯔꯤꯗꯒꯤ ꯑꯣꯛꯇꯣꯕꯔ ꯐꯥꯎꯕꯒꯤ ꯃꯅꯨꯡꯗ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯐꯪ
--------------------------------------------------

Translating:  74%|████████████████████       | 742/1000 [10:31<03:04,  1.40it/s]

[742/1000]
EN: Maldives sees forty percent drop in Indian tourist arrivals amid diplomatic row.
MNI_MTEI: ꯃꯜꯗꯤꯕꯁꯇ ꯗꯤꯄꯇꯣꯃꯤꯀꯦꯜ ꯔꯥꯎꯒꯤ ꯃꯔꯛꯗꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕꯥ ꯂꯥꯛꯄꯥ ꯃꯁꯤꯡ ꯆꯥꯗ 40 ꯍꯟꯊꯔꯦ ꯫
--------------------------------------------------

Translating:  74%|████████████████████       | 743/1000 [10:31<02:54,  1.47it/s]

[743/1000]
EN: Nepal earns 110 billion rupees from Indian tourists in fiscal year.
MNI_MTEI: ꯅꯦꯄꯥꯜꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯗꯒꯤ ꯁꯦꯟꯐꯝ ꯆꯍꯤꯗꯥ ꯂꯨꯄꯥ ꯕꯤꯂꯤꯌꯟ ꯐꯪ
--------------------------------------------------

Translating:  74%|████████████████████       | 744/1000 [10:32<02:57,  1.44it/s]

[744/1000]
EN: Turkey welcomes three lakh Indian tourists targeting five lakh by year-end.
MNI_MTEI: ꯇꯔꯀꯤꯅꯥ ꯆꯍꯤ ꯂꯣꯏꯔꯛꯄꯗꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯃꯉꯥꯒꯤ ꯄꯥꯟꯗꯝ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  74%|████████████████████       | 745/1000 [10:33<02:53,  1.47it/s]

[745/1000]
EN: Egypt reports 1.5 lakh Indian arrivals aiming for three lakh target.
MNI_MTEI: ꯏꯖꯞꯇꯅꯥ ꯚꯥꯔꯠꯇꯥ ꯂꯥꯛꯄꯥ ꯃꯤꯑꯣꯏ ꯂꯥꯈ ꯒꯤ ꯄꯥꯟꯗꯝ ꯊꯝꯃꯤ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝ
--------------------------------------------------

Translating:  75%|████████████████████▏      | 746/1000 [10:34<03:02,  1.39it/s]

[746/1000]
EN: Azerbaijan attracts two lakh Indian visitors visa-free policy credited.
MNI_MTEI: ꯑꯖꯔꯕꯥꯏꯖꯥꯟꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯚꯤꯖꯤꯇꯔ ꯂꯥꯈ ꯑꯅꯤꯒꯤ ꯚꯤꯖꯥ-ꯐ ꯄꯣꯂꯤꯁꯤ ꯀꯗꯤꯇ ꯂꯧ
--------------------------------------------------

Translating:  75%|████████████████████▏      | 747/1000 [10:34<03:07,  1.35it/s]

[747/1000]
EN: Georgia registers 1.75 lakh Indian tourist arrivals between January-September.
MNI_MTEI: ꯖꯣꯔꯖꯤꯌꯥꯅꯥ ꯖꯅꯨꯋꯥꯔꯤꯗꯒꯤ ꯁꯦꯞꯇꯦꯝꯕꯔ ꯐꯥꯎꯕꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯂꯥꯛꯄꯥ ꯔꯦꯖꯤꯁꯇꯔ ꯇꯧ
--------------------------------------------------

Translating:  75%|████████████████████▏      | 748/1000 [10:35<03:06,  1.35it/s]

[748/1000]
EN: Kenya targets one lakh Indian tourists with aggressive marketing campaign.
MNI_MTEI: ꯀꯦꯅꯦꯌꯥꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯑꯃ ꯃꯥꯡꯖꯧꯅꯅ ꯃꯥꯔꯀꯦꯇꯤꯡ ꯀꯦꯝꯄꯦꯅ ꯇꯧꯅꯕ ꯄꯥꯟꯗꯝ ꯊꯝ
--------------------------------------------------

Translating:  75%|████████████████████▏      | 749/1000 [10:36<03:04,  1.36it/s]

[749/1000]
EN: Udaipur airport gets new terminal building costing five hundred crore rupees.
MNI_MTEI: ꯎꯗꯦꯄꯨꯔ ꯑꯦꯌꯔꯄꯣꯔꯇꯥ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯆꯥꯝꯃ ꯃꯉꯥ ꯆꯪꯕꯥ ꯑꯅꯧꯕ ꯇꯔꯃꯤꯅꯦꯜ ꯕꯤꯜꯗꯤꯡ ꯐꯪ
--------------------------------------------------

Translating:  75%|████████████████████▎      | 750/1000 [10:37<03:06,  1.34it/s]

[750/1000]
EN: Rajkot airport renamed after former Prime Minister Morarji Desai.
MNI_MTEI: ꯔꯥꯖꯀꯣꯠ ꯑꯦꯌꯔꯄꯣꯔꯇ ꯑꯁꯤ ꯍꯥꯟꯅꯒꯤꯙꯥꯟ ꯃꯟꯇ ꯃꯣꯔꯥꯔꯖꯤ ꯗꯦꯁꯥꯏꯒꯤ ꯃꯃꯤꯡ ꯂꯧꯔꯒ ꯑꯃꯨꯛ ꯍꯟꯅ ꯃꯤꯡꯊꯣꯟ
--------------------------------------------------

Translating:  75%|████████████████████▎      | 751/1000 [10:37<03:14,  1.28it/s]

[751/1000]
EN: Noida International Airport to begin flight operations by April 2026.
MNI_MTEI: ꯏꯪꯁꯣꯛ ꯒꯤ ꯑꯦꯄꯜ ꯐꯥꯎꯕꯗ ꯅꯣꯏꯗꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯑꯦꯌꯔꯄꯣꯔꯇꯅꯥ ꯐꯥꯏꯇ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡ ꯍꯧꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  75%|████████████████████▎      | 752/1000 [10:38<03:10,  1.30it/s]

[752/1000]
EN: Chennai airport opens dedicated lounge for transiting international passengers.
MNI_MTEI: ꯆꯦꯟꯅꯥꯏ ꯑꯦꯌꯔꯄꯣꯔꯇꯅꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯄꯦꯁꯦꯟꯖꯔꯁꯤꯡꯒꯤꯗꯃꯛꯇ ꯗꯦꯗꯤꯀꯦꯇꯦꯗ ꯂꯥꯎꯟꯖ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  75%|████████████████████▎      | 753/1000 [10:39<03:10,  1.29it/s]

[753/1000]
EN: Guwahati-Rohingya railway project completes tunneling work in Mizoram.
MNI_MTEI: ꯒꯨꯋꯥꯍꯥꯇꯤ-ꯔꯣꯍꯤꯡꯌꯥ ꯔꯦꯜꯋꯦꯖꯦꯛꯇꯅꯥ ꯃꯤꯖꯣꯔꯥꯃꯗꯥ ꯇꯅꯦꯜꯒꯤ ꯊꯕꯛ ꯂꯣꯏꯁꯤꯟ
--------------------------------------------------

Translating:  75%|████████████████████▎      | 754/1000 [10:40<03:00,  1.36it/s]

[754/1000]
EN: Katra-Delhi Vande Bharat Express reduces travel time by three hours.
MNI_MTEI: ꯀꯇ-ꯗꯦꯂꯤ ꯚꯥꯟꯗꯦ ꯚꯥꯔꯠ ꯑꯦꯛꯁꯄꯦꯁꯅ ꯂꯝꯀꯣꯏꯕꯒꯤ ꯃꯇꯝ ꯄꯨꯡ ꯑꯍꯨꯝ ꯍꯟꯊꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  76%|████████████████████▍      | 755/1000 [10:40<03:08,  1.30it/s]

[755/1000]
EN: Mumbai-Ahmedabad bullet train project completes fifty percent of viaduct work.
MNI_MTEI: ꯃꯨꯝꯕꯥꯏ-ꯑꯍꯃꯦꯗꯥꯕꯥꯗ ꯕꯨꯂꯦꯇꯦꯟꯖꯦꯛꯇꯅꯥ ꯚꯤꯌꯥꯗꯛꯇꯀꯤ ꯊꯕꯛ ꯆꯥꯗ ꯂꯣꯏ
--------------------------------------------------

Translating:  76%|████████████████████▍      | 756/1000 [10:41<03:05,  1.32it/s]

[756/1000]
EN: Indian Railways introduces 200 superfast trains for summer rush.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯔꯦꯜꯋꯦꯅꯥ ꯀꯥꯂꯦꯟꯊꯥꯒꯤ ꯃꯤ ꯌꯥꯝꯅ ꯆꯨꯡꯅꯅꯕꯒꯤꯗꯃꯛꯇ ꯁꯨꯄꯔꯐꯥꯁꯇꯦꯟ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  76%|████████████████████▍      | 757/1000 [10:42<03:04,  1.32it/s]

[757/1000]
EN: Kochi water metro adds four new routes connecting Vypin and Goshree islands.
MNI_MTEI: ꯀꯣꯆꯤ ꯋꯥꯇꯔ ꯃꯦꯇꯅꯥ ꯚꯥꯏꯄꯤꯅ ꯑꯃꯁꯨꯡ ꯒꯣꯁ ꯏꯊꯠꯁꯤꯡ ꯁꯝꯅꯕ ꯑꯅꯧꯕ ꯂꯝꯕꯤ ꯃꯔꯤ ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  76%|████████████████████▍      | 758/1000 [10:43<03:02,  1.33it/s]

[758/1000]
EN: Ayodhya's Ram Path revamp completed ahead of Pran Pratishtha anniversary.
MNI_MTEI: ꯑꯥꯌꯣꯙꯌꯥꯒꯤ ꯔꯥꯝ ꯄꯥꯊ ꯔꯤꯚꯦꯝꯄ ꯑꯁꯤꯥꯟꯇꯤꯁꯊꯥꯒꯤ ꯆꯍꯤꯒꯤ ꯃꯃꯥꯡꯗ ꯂꯣꯏꯁꯤꯟ
--------------------------------------------------

Translating:  76%|████████████████████▍      | 759/1000 [10:44<03:05,  1.30it/s]

[759/1000]
EN: Kedarnath ropeway project gets environmental clearance from ministry.
MNI_MTEI: ꯀꯦꯗꯥꯔꯅꯥꯊ ꯔꯣꯄꯋꯦꯖꯦꯛꯇꯅꯥ ꯃꯟꯇꯗꯒꯤ ꯑꯦꯟꯚꯥꯏꯔꯟꯃꯦꯟꯇꯦꯜ ꯀꯂꯤꯑꯔꯦꯟꯁ ꯐꯪ
--------------------------------------------------

Translating:  76%|████████████████████▌      | 760/1000 [10:44<03:01,  1.32it/s]

[760/1000]
EN: Hemkund Sahib helicopter service fares capped at five thousand rupees.
MNI_MTEI: ꯍꯦꯝꯀꯨꯟꯗ ꯁꯥꯍꯤꯕ ꯍꯦꯂꯤꯀꯣꯞꯇꯔ ꯁꯔꯕꯤꯁ ꯀꯤ ꯃꯃꯜ ꯑꯁꯤ ꯂꯨꯄꯥ ꯂꯤꯁꯤꯡ ꯃꯉꯥꯗꯥ ꯂꯦꯞ
--------------------------------------------------

Translating:  76%|████████████████████▌      | 761/1000 [10:45<02:52,  1.38it/s]

[761/1000]
EN: Statue of Unity adds laser show and sound and light attraction.
MNI_MTEI: ꯇꯨ ꯑꯣꯐ ꯌꯨꯅꯤꯇꯤꯅ ꯂꯦꯖꯔ ꯁꯣ ꯑꯃꯁꯨꯡ ꯁꯥꯎꯟꯗ ꯑꯃꯁꯨꯡ ꯂꯥꯏꯇ ꯑꯦꯇꯦꯁꯟ ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  76%|████████████████████▌      | 762/1000 [10:46<02:50,  1.40it/s]

[762/1000]
EN: Khajuraho airport receives international status for charter operations.
MNI_MTEI: ꯈꯥꯖꯨꯔꯥꯍꯣ ꯑꯦꯌꯔꯄꯣꯔꯇ ꯑꯁꯤ ꯆꯥꯔꯇꯔ ꯑꯣꯄꯔꯦꯁꯟꯁꯤꯡꯒꯤꯗꯃꯛ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜꯇꯦꯁ ꯐꯪ
--------------------------------------------------

Translating:  76%|████████████████████▌      | 763/1000 [10:46<03:00,  1.31it/s]

[763/1000]
EN: Puducherry tourism department renovates French War Memorial promenade.
MNI_MTEI: ꯄꯨꯗꯨꯆꯦꯔꯤ ꯇꯨꯔꯤꯖꯝ ꯗꯤꯄꯥꯇꯃꯦꯟꯇꯅꯥ ꯐꯔꯦꯟꯁ ꯋꯥꯔ ꯃꯦꯃꯣꯔꯤꯌꯦꯜ ꯄꯃꯦꯅꯦꯗ ꯁꯦꯝꯖꯤꯟꯈ
--------------------------------------------------

Translating:  76%|████████████████████▋      | 764/1000 [10:47<02:55,  1.35it/s]

[764/1000]
EN: Dal Lake restoration project includes de-weeding and island development.
MNI_MTEI: ꯗꯥꯂ ꯂꯦꯛ ꯔꯤꯁꯇꯣꯔꯦꯁꯟꯖꯦꯛꯇꯗꯥ ꯎꯅꯥ ꯃꯨꯠꯊꯠꯄ ꯑꯃꯁꯨꯡ ꯏꯊꯠꯀꯤ ꯆꯥꯎꯈꯠꯄꯥ ꯌꯥꯎꯔꯤ ꯫
--------------------------------------------------

Translating:  76%|████████████████████▋      | 765/1000 [10:48<03:00,  1.30it/s]

[765/1000]
EN: Hampi gets world-class interpretation centre showcasing Vijayanagara heritage.
MNI_MTEI: ꯍꯝꯄꯤꯗꯥ ꯕꯤꯖꯌꯥꯅꯒꯔꯒꯤ ꯍꯦꯔꯤꯇꯦꯖ ꯎꯠꯄꯥ ꯋꯥꯔꯜꯗ-ꯀꯂꯥꯁ ꯏꯟꯇꯔꯄꯦꯇꯦꯁꯟ ꯁꯦꯟꯇꯔ ꯐꯪ
--------------------------------------------------

Translating:  77%|████████████████████▋      | 766/1000 [10:49<03:02,  1.28it/s]

[766/1000]
EN: Mahabalipuram shoreline monument gets LED lighting for night viewing.
MNI_MTEI: ꯃꯍꯥꯕꯥꯂꯤꯄꯨꯔꯝ ꯁꯣꯔꯂꯥꯏꯟ ꯃꯣꯅꯨꯃꯦꯟꯇꯗꯥ ꯅꯨꯡꯊꯤꯜꯒꯤ ꯌꯦꯡꯅꯕꯒꯤꯗꯃꯛ ꯑꯦꯜ. ꯏ. ꯗꯤ. ꯂꯥꯏꯇꯤꯡ ꯐꯪ
--------------------------------------------------

Translating:  77%|████████████████████▋      | 767/1000 [10:50<02:58,  1.30it/s]

[767/1000]
EN: Ajanta-Ellora caves introduce audio guides in ten international languages.
MNI_MTEI: ꯑꯖꯥꯟꯇꯥ- ꯏꯜꯂꯣꯔꯥ ꯒꯨꯍꯥꯁꯤꯡꯅꯖꯥꯇꯤꯒꯤ ꯂꯣꯟ ꯇꯔꯥꯗꯥ ꯑꯣꯗꯤꯑꯣ ꯒꯥꯏꯗꯁꯤꯡ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  77%|████████████████████▋      | 768/1000 [10:50<02:45,  1.40it/s]

[768/1000]
EN: Kaziranga opens additional safari routes for tourists.
MNI_MTEI: ꯀꯥꯖꯤꯔꯪꯒꯥꯅꯥ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤꯗꯃꯛ ꯑꯍꯦꯟꯕ ꯁꯐꯥꯔꯤ ꯂꯝꯕꯤꯁꯤꯡ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  77%|████████████████████▊      | 769/1000 [10:51<02:52,  1.34it/s]

[769/1000]
EN: Radisson Blu opens two hundred key property in Amritsar near Golden Temple.
MNI_MTEI: ꯑꯝꯔꯤꯠꯁꯔꯗꯥ ꯒꯣꯜꯗꯦꯟ ꯇꯦꯝꯄꯜ ꯃꯅꯥꯛꯇ ꯔꯦꯗꯤꯁꯟꯂꯨꯅꯥ ꯃꯔꯨꯑꯣꯏꯕ ꯂꯝ ꯆꯥꯃ ꯑꯅꯤ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  77%|████████████████████▊      | 770/1000 [10:52<02:54,  1.32it/s]

[770/1000]
EN: IHCL launches Ginger brand hotel in Siliguri for Dooars travellers.
MNI_MTEI: ꯑꯥꯏ ꯑꯩꯆ ꯁꯤ ꯑꯦꯜꯅꯥ ꯗꯨꯌꯥꯔ ꯂꯝꯀꯣꯏꯕꯥꯁꯤꯡꯒꯤꯗꯃꯛ ꯁꯤꯂꯤꯒꯨꯔꯤꯗꯥ ꯖꯤꯟꯖꯔꯥꯟꯗ ꯍꯣꯇꯦꯜ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  77%|████████████████████▊      | 771/1000 [10:52<02:52,  1.33it/s]

[771/1000]
EN: Hyatt Regency debuts in Dehradun with mountain view rooms.
MNI_MTEI: ꯍꯥꯏꯌꯥꯇ ꯔꯤꯖꯦꯟꯁꯤ ꯑꯁꯤ ꯗꯦꯍꯔꯥꯗꯨꯟꯗꯥ ꯃꯥꯎꯟꯇꯦꯟ ꯚꯤꯎ ꯀꯥꯁꯤꯡꯒ ꯂꯣꯏꯅꯅ ꯑꯍꯥꯟꯕ ꯑꯣꯏꯔꯛ
--------------------------------------------------

Translating:  77%|████████████████████▊      | 772/1000 [10:53<02:51,  1.33it/s]

[772/1000]
EN: Taj Fort Aguada completes fifty years in Goa announces renovation.
MNI_MTEI: ꯇꯥꯖ ꯐꯣꯔꯇ ꯑꯒꯨꯋꯥꯗꯥꯅꯥ ꯒꯣꯋꯥꯒꯤ ꯆꯍꯤ ꯆꯥꯝꯈꯥꯏ ꯂꯣꯏꯔꯦ ꯑꯃꯁꯨꯡ ꯑꯃꯨꯛ ꯍꯟꯅ ꯁꯦꯝꯖꯤꯟꯈꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  77%|████████████████████▊      | 773/1000 [10:54<02:49,  1.34it/s]

[773/1000]
EN: Novotel Visakhapatnam opens with three sixty degree sea view rooms.
MNI_MTEI: ꯅꯣꯚꯣꯇꯦꯜ ꯚꯤꯁꯥꯀꯇꯥꯅꯝ ꯑꯁꯤ ꯗꯤꯒꯇꯤ ꯁꯤ ꯚꯤꯎ ꯀꯥ ꯑꯍꯨꯝꯒꯥ ꯂꯣꯏꯅꯅ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  77%|████████████████████▉      | 774/1000 [10:55<02:38,  1.42it/s]

[774/1000]
EN: Roseate House Delhi appoints Kunal Kumar as new general manager.
MNI_MTEI: ꯔꯣꯖꯦꯇ ꯍꯥꯎꯁ ꯗꯤꯜꯂꯤꯅꯥ ꯀꯨꯅꯜ ꯀꯨꯃꯥꯔꯕꯨ ꯑꯅꯧꯕ ꯖꯦꯅꯔꯦꯜ ꯃꯦꯅꯦꯖꯔ ꯑꯣꯏꯅ ꯍꯥꯞ
--------------------------------------------------

Translating:  78%|████████████████████▉      | 775/1000 [10:55<02:39,  1.41it/s]

[775/1000]
EN: ITC Hotels launches Mementoes brand with Jaipur property opening.
MNI_MTEI: ꯑꯥꯏ ꯇꯤ ꯁꯤ ꯍꯣꯇꯦꯜꯅꯥ ꯖꯦꯄꯨꯔꯄꯣꯔꯇꯤ ꯍꯥꯡꯗꯣꯛꯄꯒꯥ ꯂꯣꯏꯅꯅ ꯃꯦꯃꯦꯟꯇꯣꯁꯥꯟꯗ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  78%|████████████████████▉      | 776/1000 [10:56<02:47,  1.34it/s]

[776/1000]
EN: Marriott Kathmandu opens Indian restaurant specializing in Awadhi cuisine.
MNI_MTEI: ꯃꯦꯔꯤꯑꯣꯇ ꯀꯊꯃꯟꯗꯨꯅꯥ ꯑꯋꯥꯙꯤ ꯀꯤꯖꯟꯗꯥ ꯊꯣꯏꯗꯣꯛ ꯍꯦꯟꯗꯣꯛꯄ ꯏꯟꯗꯤꯌꯟ ꯔꯦꯁꯇꯣꯔꯦꯟꯇ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  78%|████████████████████▉      | 777/1000 [10:57<02:47,  1.33it/s]

[777/1000]
EN: Sarovar Hotels signs new property in Darjeeling with heritage status.
MNI_MTEI: ꯗꯥꯔꯖꯤꯂꯤꯡꯗꯥ ꯍꯦꯔꯤꯇꯦꯖꯇꯦꯁꯀ ꯂꯣꯏꯅꯅ ꯁꯥꯔꯣꯚꯔ ꯍꯣꯇꯦꯜꯁꯤꯡꯅ ꯑꯅꯧꯕꯄꯣꯔꯇꯤ ꯈꯨꯠꯌꯦꯛ ꯄꯤꯁꯤꯟ
--------------------------------------------------

Translating:  78%|█████████████████████      | 778/1000 [10:58<02:38,  1.40it/s]

[778/1000]
EN: The Park Kolkata celebrates seventy-fifth anniversary with heritage walks.
MNI_MTEI: ꯄꯥꯔꯛ ꯀꯣꯜꯀꯥꯇꯥꯅꯥ ꯍꯦꯔꯤꯇꯦꯖ ꯋꯥꯀꯒ ꯂꯣꯏꯅꯅꯥ ꯆꯍꯤ ꯆꯥ 75 ꯁꯨꯕꯥ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  78%|█████████████████████      | 779/1000 [10:58<02:47,  1.32it/s]

[779/1000]
EN: Ambassador Ajmera joins Indian Hotel Company board as independent director.
MNI_MTEI: ꯑꯦꯝꯕꯦꯁꯦꯗꯔ ꯑꯖꯃꯦꯔꯥꯅꯥ ꯏꯟꯗꯤꯌꯟ ꯍꯣꯇꯦꯜ ꯀꯝꯄꯅꯤꯒꯤ ꯕꯣꯔꯗꯥ ꯏꯟꯗꯄꯦꯟꯗꯦꯟꯇ ꯗꯥꯏꯔꯦꯛꯇꯔ ꯑꯣꯏꯅ ꯌꯥꯎ
--------------------------------------------------

Translating:  78%|█████████████████████      | 780/1000 [10:59<02:52,  1.27it/s]

[780/1000]
EN: Chai Sutta Bar founder Anubhav Dubey opens tourist cafe in Udaipur.
MNI_MTEI: ꯆꯥꯏ ꯁꯨꯠꯇꯥ ꯕꯥꯔ ꯂꯤꯡꯈꯠꯄꯥ ꯃꯤꯑꯣꯏ ꯑꯅꯨꯚꯕ ꯗꯨꯕꯦꯅꯥ ꯎꯗꯦꯄꯨꯔꯗꯥ ꯇꯨꯔꯤꯁꯇ ꯀꯦꯐꯦ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  78%|█████████████████████      | 781/1000 [11:00<02:41,  1.36it/s]

[781/1000]
EN: Aman Resorts to launch first Indian property in Alwar district.
MNI_MTEI: ꯑꯃꯟ ꯔꯤꯖꯣꯔꯇꯁꯅ ꯑꯥꯂꯋꯥꯔ ꯖꯤꯂꯥꯗꯥ ꯑꯍꯥꯟꯕ ꯚꯥꯔꯠꯀꯤꯄꯣꯔꯇꯤ ꯍꯥꯡꯗꯣꯛꯀꯅꯤ
--------------------------------------------------

Translating:  78%|█████████████████████      | 782/1000 [11:01<02:43,  1.33it/s]

[782/1000]
EN: Soneva Fushi Maldives introduces all-inclusive plan for Indian honeymooners.
MNI_MTEI: ꯁꯣꯅꯦꯚꯥ ꯐꯨꯁꯤ ꯃꯥꯜꯗꯤꯚꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯍꯅꯤꯃꯨꯅꯔꯁꯤꯡꯒꯤꯗꯃꯛ ꯑꯣꯜ-ꯏꯟꯀꯨꯁꯤꯕꯂꯥꯟ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 783/1000 [11:02<02:55,  1.24it/s]

[783/1000]
EN: CII tourism committee chairman K.B. Kachru calls for single window clearance.
MNI_MTEI: ꯁꯤ ꯑꯥꯏ ꯑꯥꯏ ꯇꯨꯔꯤꯖꯝ ꯀꯝꯃꯤꯇꯤꯒꯤ ꯆꯦꯌꯔꯃꯦꯟ ꯀꯦ ꯕꯤ ꯀꯥꯆꯔꯨꯅꯥ ꯁꯤꯡꯒꯜ ꯋꯤꯟꯗꯣ ꯀꯂꯥꯌꯔꯦꯟꯁ ꯄꯤꯅꯕ ꯍꯥꯏ
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 784/1000 [11:02<02:58,  1.21it/s]

[784/1000]
EN: Ladakh bans motorbike rallies to protect fragile Himalayan ecosystem.
MNI_MTEI: ꯂꯗꯥꯈꯅꯥ ꯑꯁꯣꯏꯕꯥ ꯍꯤꯃꯥꯂꯌꯟꯒꯤ ꯑꯦꯀꯣꯁꯃꯤꯇ ꯉꯥꯛꯁꯦꯟꯕꯒꯤꯗꯃꯛ ꯃꯣꯇꯣꯔꯕꯥꯏꯀ ꯔꯦꯂꯤꯁꯤꯡ ꯊꯤꯡ
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 785/1000 [11:03<02:55,  1.23it/s]

[785/1000]
EN: Meghalaya introduces living root bridge trekking festival in November.
MNI_MTEI: ꯃꯦꯘꯂꯌꯅꯥ ꯅꯕꯦꯝꯕꯔꯗꯥ ꯂꯤꯚꯤꯡ ꯔꯨꯠ ꯕꯖꯦꯛꯀꯤꯡ ꯐꯦꯁꯇꯤꯕꯦꯜ ꯍꯧꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  79%|█████████████████████▏     | 786/1000 [11:04<02:50,  1.25it/s]

[786/1000]
EN: Spiti valley opens for tourists after six-month winter closure.
MNI_MTEI: ꯊꯥ ꯇꯔꯨꯛꯀꯤ ꯅꯤꯡꯊꯝꯊꯥꯒꯤ ꯃꯇꯝꯗ ꯊꯤꯡꯖꯤꯟꯈꯕꯥ ꯃꯇꯨꯡꯗ ꯁꯄꯤꯇꯤ ꯋꯥꯂꯤ ꯑꯁꯤ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤꯗꯃꯛ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  79%|█████████████████████▏     | 787/1000 [11:05<02:43,  1.30it/s]

[787/1000]
EN: Andaman administration permits night camping on Neil Island.
MNI_MTEI: ꯅꯤꯂ ꯑꯥꯏꯂꯦꯟꯗꯗꯥ ꯑꯟꯗꯃꯥꯟ ꯑꯦꯗꯃꯤꯅꯤꯁꯇꯦꯁꯟꯅ ꯅꯥꯏꯇ ꯀꯦꯝꯄꯤꯡ ꯇꯧꯅꯕꯒꯤ ꯑꯌꯥꯕ ꯄꯤ
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 788/1000 [11:06<02:47,  1.26it/s]

[788/1000]
EN: Gujarat forest department opens Gir interpretation zone for lion safaris.
MNI_MTEI: ꯒꯨꯖꯔꯥꯇ ꯐꯣꯔꯦꯁꯇ ꯗꯤꯄꯥꯇꯃꯦꯟꯇꯅꯥ ꯂꯥꯏꯅ ꯁꯐꯔꯤꯁꯤꯡꯒꯤ ꯒꯤꯔ ꯏꯟꯇꯔꯄꯦꯇꯦꯁꯟ ꯖꯣꯟ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 789/1000 [11:06<02:46,  1.26it/s]

[789/1000]
EN: Jim Corbett tiger reserve reports 1.75 lakh tourists in peak season.
MNI_MTEI: ꯖꯤꯃ ꯀꯣꯔꯕꯦꯇ ꯇꯥꯏꯒꯔ ꯔꯤꯖꯔꯚꯅꯥ ꯄꯥꯎꯗꯝꯂꯤ ꯃꯗꯨꯗꯤ ꯄꯤꯛ ꯁꯤꯖꯟꯗꯥ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 790/1000 [11:07<02:37,  1.33it/s]

[790/1000]
EN: Periyar sanctuary introduces bamboo rafting in Thekkady lake.
MNI_MTEI: ꯄꯦꯔꯤꯌꯥꯔ ꯁꯦꯡꯆꯨꯑꯔꯤꯅꯥ ꯊꯦꯛꯀꯥꯗꯤ ꯄꯥꯠꯗꯥ ꯋꯥꯒꯤ ꯔꯥꯐꯇꯤꯡ ꯍꯧꯍꯟ
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 791/1000 [11:08<02:22,  1.47it/s]

[791/1000]
EN: Sundarbans tourism restricted during tiger breeding season.
MNI_MTEI: ꯀꯩ ꯄꯣꯛꯄꯥ ꯃꯇꯝꯗ ꯁꯨꯟꯗꯔꯕꯥꯟ ꯇꯨꯔꯤꯖꯝ ꯊꯤꯡꯉꯤ ꯫
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 792/1000 [11:08<02:22,  1.46it/s]

[792/1000]
EN: Ranthambore bans private vehicles inside core zone from December.
MNI_MTEI: ꯔꯟꯊꯝꯕꯣꯔꯅꯥ ꯗꯤꯁꯦꯝꯕꯔꯗꯒꯤ ꯀꯣꯔ ꯖꯣꯟꯒꯤ ꯃꯅꯨꯡꯗꯚꯥꯏꯇ ꯒꯥꯔꯤꯁꯤꯡ ꯊꯤꯡꯖꯜꯂꯨ ꯫
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 793/1000 [11:09<02:22,  1.45it/s]

[793/1000]
EN: Kerala tourism launches monsoon packages for Ayurveda treatments.
MNI_MTEI: ꯀꯦꯔꯂꯥ ꯇꯨꯔꯤꯖꯝꯅꯥ ꯑꯥꯌꯨꯔꯕꯦꯗ ꯂꯥꯏꯌꯦꯡꯒꯤꯗꯃꯛ ꯃꯣꯟꯁꯨꯅ ꯄꯦꯀꯦꯖꯁꯤꯡ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 794/1000 [11:10<02:24,  1.43it/s]

[794/1000]
EN: Kutch Rann Utsav extends tent city duration by forty-five days.
MNI_MTEI: ꯀꯨꯇꯆ ꯔꯟ ꯎꯇꯁꯥꯚꯅꯥ ꯇꯦꯟꯇ ꯁꯤꯇꯤꯒꯤ ꯃꯇꯝ ꯑꯁꯤ ꯅꯨꯃꯤꯠ ꯃꯔꯤ - ꯃꯉꯥꯅꯤ ꯍꯦꯟꯒꯠ
--------------------------------------------------

Translating:  80%|█████████████████████▍     | 795/1000 [11:11<02:39,  1.29it/s]

[795/1000]
EN: Telangana government promotes Yadadri temple as integrated pilgrimage hub.
MNI_MTEI: ꯇꯦꯂꯪꯒꯥꯅꯥ ꯒꯚꯔꯃꯦꯟꯇꯅꯥ ꯌꯥꯗꯔꯤ ꯂꯥꯏꯁꯪ ꯑꯁꯤ ꯏꯟꯇꯤꯒꯇꯦꯗ ꯄꯤꯔꯊꯂꯤꯖꯝ ꯍꯕꯥꯇ ꯑꯣꯏꯍꯟ
--------------------------------------------------

Translating:  80%|█████████████████████▍     | 796/1000 [11:11<02:36,  1.31it/s]

[796/1000]
EN: Mysore Dasara procession draws eight lakh visitors on Vijayadashami day.
MNI_MTEI: ꯃꯥꯏꯁꯣꯔ ꯗꯁꯥꯔꯥꯒꯤ ꯈꯣꯡꯆꯠꯅꯥ ꯚꯤꯖꯦꯗꯁꯥꯃꯤꯒꯤ ꯅꯨꯃꯤꯠꯗꯥ ꯂꯝꯀꯣꯏꯕ ꯂꯥꯈ ꯅꯤꯄꯥꯟ ꯄꯨ
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 797/1000 [11:12<02:31,  1.34it/s]

[797/1000]
EN: Konark Sun Temple to get 3D projection mapping experience.
MNI_MTEI: ꯀꯣꯅꯥꯔꯛ ꯁꯨꯅ ꯇꯦꯝꯄꯜꯅꯥ 3Dꯖꯦꯛꯁꯟ ꯃꯦꯄꯤꯡ ꯑꯦꯛꯁꯄꯤꯌꯔꯦꯟꯁ ꯐꯪꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 798/1000 [11:13<02:27,  1.36it/s]

[798/1000]
EN: Elephanta Caves introduce Portuguese audio guide for visitors.
MNI_MTEI: ꯑꯦꯂꯤꯐꯦꯟꯇꯥ ꯀꯦꯚꯁꯅꯥ ꯂꯝꯀꯣꯏꯕꯁꯤꯡꯒꯤꯗꯃꯛꯇ ꯄꯨꯔꯇꯨꯒꯤꯖꯒꯤ ꯑꯣꯗꯤꯑꯣ ꯒꯥꯏꯗ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 799/1000 [11:13<02:25,  1.38it/s]

[799/1000]
EN: Golconda Fort light and sound show revamped in Telugu and English.
MNI_MTEI: ꯇꯦꯂꯨꯒꯨ ꯑꯃꯁꯨꯡ ꯏꯪꯂꯤꯁꯇꯥ ꯒꯣꯂꯀꯣꯟꯗꯥ ꯐꯣꯔꯇ ꯂꯥꯏꯇ ꯑꯦꯟ ꯁꯥꯎꯟꯗ ꯁꯣ ꯁꯦꯝꯖꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 800/1000 [11:14<02:23,  1.40it/s]

[800/1000]
EN: Five regional medical hubs to be set up to boost medical tourism in country
MNI_MTEI: ꯂꯩꯕꯥꯛ ꯑꯁꯤꯗ ꯃꯦꯗꯤꯀꯦꯜ ꯇꯨꯔꯤꯖꯝ ꯍꯦꯟꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯔꯤꯖꯅꯦꯜ ꯃꯦꯗꯗꯤꯀꯦꯜ ꯍꯕ ꯃꯉꯥ ꯁꯦꯝꯒꯅꯤ
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 801/1000 [11:15<02:11,  1.51it/s]

[801/1000]
EN: Union Budget 2026 announces NIMHANS for north India
MNI_MTEI: ꯌꯨꯅꯤꯌꯟ ꯕꯖꯦꯇ 2026ꯅꯥ ꯑꯋꯥꯡ ꯚꯥꯔꯠꯀꯤ ꯅꯤꯝꯍꯥꯟꯁ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 802/1000 [11:15<02:12,  1.50it/s]

[802/1000]
EN: Centre forms expert panel on healthcare for transgender persons
MNI_MTEI: ꯁꯦꯟꯇꯔꯅꯥ ꯑꯦꯛꯁꯄꯥꯔꯇ ꯄꯦꯅꯦꯜ ꯑꯣꯟ ꯍꯦꯜꯊꯦꯀꯦꯌꯔ ꯐꯣꯔꯖꯦꯟꯗꯔ ꯄꯔꯁꯟꯁꯤꯡ ꯁꯦꯝꯂꯦ
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 803/1000 [11:16<02:15,  1.45it/s]

[803/1000]
EN: Stem cell therapy cannot be offered as a clinical service for autism
MNI_MTEI: ꯃꯦ ꯁꯦꯜ ꯊꯦꯔꯥꯄꯤ ꯑꯁꯤ ꯑꯣꯇꯤꯖꯝꯒꯤꯗꯃꯛ ꯀꯂꯤꯅꯤꯀꯦꯜ ꯁꯔꯕꯤꯁ ꯑꯃ ꯑꯣꯏꯅ ꯄꯤꯕ ꯌꯥꯔꯣꯏ ꯫
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 804/1000 [11:17<02:19,  1.41it/s]

[804/1000]
EN: AI helps doctors spot breast cancer in scans
MNI_MTEI: ꯑꯦꯑꯏꯅꯥ ꯗꯣꯛꯇꯔꯁꯤꯡꯕꯨ ꯁꯀꯦꯟꯗꯥ ꯕꯦꯁꯇ ꯀꯦꯟꯁꯔ ꯈꯪꯗꯣꯛꯄꯗꯥ ꯃꯇꯦꯡ ꯄꯥꯡꯉꯤ ꯫
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 805/1000 [11:18<02:37,  1.24it/s]

[805/1000]
EN: Every family today knows someone with cancer and It is no longer a disease that happens to an ageing parent or relative
MNI_MTEI: ꯉꯁꯤꯗꯤ ꯏꯃꯨꯡ ꯈꯨꯗꯤꯡꯃꯛꯅ ꯀꯦꯟꯁꯔ ꯅꯥꯔꯕ ꯃꯤꯑꯣꯏ ꯑꯃ ꯈꯪꯂꯦ ꯑꯃꯁꯨꯡ ꯃꯁꯤ ꯆꯍꯤ ꯆꯥꯎꯔꯕ ꯃꯃꯥ-ꯃꯕꯥ ꯅꯠꯇꯒꯥ ꯃꯔꯤ ꯂꯩꯅꯕ ꯑꯃꯗ ꯊꯣꯛꯄꯥ ꯂꯥꯏꯅꯥ ꯑꯃ ꯑꯣꯏꯔꯛꯇ
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 806/1000 [11:18<02:25,  1.33it/s]

[806/1000]
EN: Government imposes import curbs on three pharma ingredients for one year
MNI_MTEI: ꯁꯔꯀꯥꯔꯅꯥ ꯐꯥꯔꯃꯥꯒꯤ ꯃꯆꯥꯛ ꯑꯍꯨꯝ ꯄꯨꯁꯤꯜꯂꯛꯄꯗꯥ ꯆꯍꯤ ꯑꯃꯒꯤꯗꯃꯛ ꯊꯤꯡꯖꯜꯍꯟ
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 807/1000 [11:19<02:24,  1.34it/s]

[807/1000]
EN: Menstrual health in schools is integral to right to life, says the Supreme Court
MNI_MTEI: ꯜꯁꯤꯡꯗ ꯊꯥꯒꯤ ꯑꯣꯏꯕ ꯍꯛꯁꯦꯜ ꯑꯁꯤ ꯍꯤꯡꯕꯒꯤ ꯍꯛꯗꯥ ꯃꯄꯨꯡ ꯐꯥꯕ ꯍꯥꯏꯅ ꯁꯨꯄꯝ ꯀꯣꯔꯠꯅ ꯍꯥꯏ
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 808/1000 [11:20<02:23,  1.34it/s]

[808/1000]
EN: WHO sees low risk of Nipah virus spreading beyond India
MNI_MTEI: ꯗꯕꯂꯌꯨꯑꯍꯑꯣꯅꯥ ꯅꯤꯄꯥꯍ ꯚꯥꯏꯔꯁ ꯑꯁꯤ ꯚꯥꯔꯠꯀꯤ ꯃꯄꯥꯟꯗ ꯁꯟꯗꯣꯛꯄꯒꯤ ꯔꯤꯁꯀ ꯍꯟꯊꯔꯦ ꯍꯥꯏꯅ ꯎꯔꯦ
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 809/1000 [11:21<02:36,  1.22it/s]

[809/1000]
EN: Economic Survey calls for tackling rising digital addiction and screen-related mental health problems
MNI_MTEI: ꯏꯀꯅꯣꯃꯤꯛ ꯁꯔꯚꯦꯅꯥ ꯍꯦꯟꯒꯠꯂꯛꯂꯤꯕ ꯗꯤꯖꯤꯇꯦꯜ ꯑꯦꯗꯤꯛꯁꯟ ꯑꯃꯁꯨꯡꯅꯤꯜꯒꯥ ꯃꯔꯤ ꯂꯩꯅꯕ ꯃꯦꯟꯇꯦꯜ ꯍꯦꯜꯊꯃꯣꯜꯁꯤꯡ ꯊꯦꯡꯅꯅꯕ ꯍꯥꯏꯔꯤ
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 810/1000 [11:22<02:26,  1.30it/s]

[810/1000]
EN: 188 million children and adolescents living with obesity worldwide
MNI_MTEI: ꯃꯥꯂꯦꯝ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯑꯣꯕꯣꯁꯤꯇꯤꯒ ꯂꯣꯏꯅꯅꯥ ꯍꯤꯡꯂꯤꯕ ꯑꯉꯥꯡ ꯑꯃꯁꯨꯡ ꯑꯦꯂꯣꯖꯦꯟꯇ ꯀꯔꯣꯔ
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 811/1000 [11:22<02:24,  1.31it/s]

[811/1000]
EN: 60% of mental disorders found in patients below 35 years
MNI_MTEI: ꯃꯦꯟꯇꯥꯜ ꯗꯤꯁꯑꯣꯔꯗꯔꯁꯤꯡꯒꯤ%ꯗꯤ ꯆꯍꯤ 35ꯒꯤ ꯃꯈꯥꯗ ꯂꯩꯕ ꯑꯅꯥꯕꯥꯁꯤꯡꯗ ꯐꯪꯉꯤ ꯫
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 812/1000 [11:23<02:31,  1.24it/s]

[812/1000]
EN: Obesity impacts on brain may depend on how fat is distributed across body
MNI_MTEI: ꯕꯦꯟꯗ ꯑꯣꯕꯦꯁꯤꯇꯤꯒꯤ ꯏꯄꯦꯛꯠꯁꯤꯡ ꯑꯁꯤ ꯍꯛꯆꯥꯡ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯐꯦꯠ ꯑꯁꯤ ꯀꯔꯝꯅꯥ ꯁꯟꯗꯣꯛꯀꯗꯒꯦ ꯍꯥꯏꯕꯒꯤ ꯃꯈꯥ ꯄꯣꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 813/1000 [11:24<02:36,  1.19it/s]

[813/1000]
EN: Maharashtra, Karnataka, Tamil Nadu have highest number of vacancies under the NEET-PG 2025-26
MNI_MTEI: ꯃꯍꯥꯔꯥꯁꯇ ꯭ ꯔ, ꯀꯔꯅꯥꯇꯀꯥ, ꯇꯥꯃꯤꯜ ꯅꯥꯗꯨꯗ ꯅꯤꯑꯏꯇꯤ-ꯄꯤꯖꯤ 2025-26 ꯒꯤ ꯃꯈꯥꯗ ꯑꯍꯦꯟꯕꯥ ꯚꯦꯛꯁꯤꯅꯦꯁꯟꯁꯤꯡ ꯂꯩ ꯫
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 814/1000 [11:25<02:46,  1.12it/s]

[814/1000]
EN: Only two Nipah virus disease cases reported in West Bengal since December 2025, says Health Ministry
MNI_MTEI: ꯏꯪꯁꯣꯛ 2025 ꯒꯤ ꯗꯤꯁꯦꯝꯕꯔꯗꯒꯤ ꯋꯇ ꯕꯦꯡꯒꯣꯜꯗꯥ ꯅꯤꯄꯥꯍ ꯚꯥꯏꯔꯁ ꯂꯥꯏꯅꯥꯒꯤ ꯀꯦꯁ ꯑꯅꯤ ꯈꯛꯇꯃꯛ ꯔꯤꯄꯣꯔꯠ ꯇꯧꯔꯦ ꯍꯥꯏꯅ ꯍꯦꯜꯊ ꯃꯟꯇꯅꯥ ꯍꯥꯏ ꯫
--------------------------------------------------

Translating:  82%|██████████████████████     | 815/1000 [11:26<02:46,  1.11it/s]

[815/1000]
EN: Health impacts due to plastics worldwide may double by 2040
MNI_MTEI: ꯃꯥꯂꯦꯝ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥꯁꯇꯤꯛꯁꯤꯡ ꯑꯁꯤꯅ ꯊꯣꯛꯍꯟꯕ ꯍꯛꯁꯦꯜꯒꯤ ꯏꯚꯦꯛꯠꯁꯤꯡ ꯑꯁꯤ ꯏꯪ 2040 ꯐꯥꯎꯕꯗ ꯁꯔꯨꯛ ꯑꯅꯤ ꯍꯦꯟꯒꯠꯂꯛꯄ ꯌꯥꯏ ꯫
--------------------------------------------------

Translating:  82%|██████████████████████     | 816/1000 [11:27<02:35,  1.18it/s]

[816/1000]
EN: China halts sale of Sun Pharma drug used to treat dementia
MNI_MTEI: ꯆꯥꯏꯅꯥꯅꯥ ꯗꯤꯃꯦꯅꯁꯤꯌꯥ ꯂꯥꯏꯌꯦꯡꯕꯗ ꯁꯤꯖꯤꯟꯅꯕ ꯁꯟ ꯐꯥꯔꯃꯥꯒꯤ ꯍꯤꯗꯥꯛ ꯌꯣꯟꯕ ꯊꯤꯡ
--------------------------------------------------

Translating:  82%|██████████████████████     | 817/1000 [11:28<02:49,  1.08it/s]

[817/1000]
EN: T.N. govt. scheme improves access to diabetes, hypertension care for women as rural residents
MNI_MTEI: ꯇꯤ. ꯑꯦꯟ. ꯒꯚꯔꯃꯦꯟꯇꯀꯤꯝꯅꯥ ꯗꯥꯏꯑꯦꯕꯦꯇꯤꯁ, ꯍꯥꯏꯞꯇꯔꯦꯟꯁꯟ ꯀꯦꯌꯔ ꯐꯣꯔ ꯋꯤꯃꯦꯅꯕꯨ ꯔꯨꯔꯦꯜ ꯔꯦꯁꯤꯗꯦꯟꯇꯁꯤꯡ ꯑꯣꯏꯍꯟꯕꯗꯥ ꯐꯒꯠꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  82%|██████████████████████     | 818/1000 [11:30<03:30,  1.16s/it]

[818/1000]
EN: Karnataka farmers urge Union Government to recommend to WHO to re-classify arecanut from ‘carcinogenic’ to ‘possibly carcinogenic to humans’
MNI_MTEI: ꯀꯔꯅꯥꯇꯀꯥꯒꯤ ꯂꯧꯃꯤꯁꯤꯡꯅ ꯀꯦꯟꯗ ꯒꯕꯔꯃꯦꯟꯇꯇꯥ ꯑꯦꯔꯦꯀꯅꯨꯠꯄꯨ ꯀꯥꯔꯁꯤꯅꯣꯖꯦꯅꯤꯛꯗꯒꯤ ′′ꯑꯃꯗꯥ ꯀꯥꯔꯁꯤꯅꯣꯁꯖꯦꯟꯦꯅꯤꯛ ꯑꯣꯏꯍꯟꯕꯥ ꯔꯤ-ꯀꯁꯤꯐꯥꯏ ꯇꯧꯅꯕ ꯗꯕꯂꯌꯨꯑꯍꯣꯗꯥ ꯔꯤꯀꯃꯦꯟꯗ ꯇꯧꯅꯅꯕ ꯍꯥꯏꯔꯤ ꯫
--------------------------------------------------

Translating:  82%|██████████████████████     | 819/1000 [11:31<03:31,  1.17s/it]

[819/1000]
EN: Study discovers stress-reducing role of natural molecule in body, may help with metabolic disorders
MNI_MTEI: ꯍꯛꯆꯥꯡꯗꯥ ꯅꯦꯆꯔꯦꯜ ꯃꯂꯦꯀꯜꯒꯤ ꯁꯦꯁ-ꯔꯤꯗꯨꯀꯤꯡ ꯔꯣꯜ ꯑꯗꯨ ꯊꯤꯖꯤꯜꯂꯤ, ꯃꯦꯇꯥꯕꯂꯤꯛ ꯗꯤꯁꯑꯣꯔꯗꯔꯁꯤꯡꯗ ꯃꯇꯦꯡ ꯄꯥꯡꯕ ꯌꯥꯏ ꯫
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 820/1000 [11:32<03:02,  1.01s/it]

[820/1000]
EN: Keeping your spine healthy with small, everyday changes
MNI_MTEI: ꯑꯄꯤꯛꯄ, ꯅꯨꯃꯤꯠ ꯈꯨꯗꯤꯡꯒꯤ ꯍꯣꯡꯂꯛꯄꯁꯤꯡꯒ ꯂꯣꯏꯅꯅ ꯅꯍꯥꯛꯀꯤ ꯁꯄꯤꯟ ꯑꯗꯨ ꯍꯛꯊꯦꯡꯅꯅ ꯊꯝꯕꯥ
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 821/1000 [11:32<02:43,  1.10it/s]

[821/1000]
EN: What is behind the increasing number of heart attacks in pregnancy?
MNI_MTEI: ꯃꯤꯔꯣꯜꯂꯤꯉꯩ ꯃꯇꯝꯗ ꯍꯥꯔꯇ ꯑꯦꯇꯦꯛ ꯃꯁꯤꯡ ꯍꯦꯟꯒꯠꯂꯛꯄꯒꯤ ꯃꯔꯝ ꯀꯔꯤꯅꯣ?
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 822/1000 [11:33<02:28,  1.20it/s]

[822/1000]
EN: Can India eliminate malaria by 2030?
MNI_MTEI: ꯏꯪꯁꯣꯛ 2030 ꯐꯥꯎꯕꯗ ꯚꯥꯔꯠꯅ ꯃꯦꯂꯦꯔꯤꯌꯥ ꯃꯨꯠꯊꯠꯄ ꯌꯥꯒꯗꯔꯥ?
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 823/1000 [11:34<02:44,  1.08it/s]

[823/1000]
EN: Tamil Nadu government seeks IIT-M’s assistance to study ill effects of microplastics on human health
MNI_MTEI: ꯇꯥꯃꯤꯜ ꯅꯥꯗꯨ ꯁꯔꯀꯥꯔꯅꯥ ꯃꯤꯌꯣꯏꯒꯤ ꯍꯛꯁꯦꯜꯗꯥ ꯃꯥꯏꯀꯄꯂꯥꯁꯇꯤꯛꯁꯤꯡꯒꯤ ꯑꯁꯣꯏꯕꯥ ꯃꯍꯩꯁꯤꯡ ꯅꯩꯅꯕꯗꯥ ꯑꯥꯏ ꯑꯥꯏ ꯇꯤ-ꯑꯦꯝ ꯒꯤ ꯃꯇꯦꯡ ꯊꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 824/1000 [11:35<02:48,  1.04it/s]

[824/1000]
EN: Goa seeks to grow as a wellness and medical tourism hub in India
MNI_MTEI: ꯒꯣꯋꯥꯅꯥ ꯚꯥꯔꯠꯇꯥ ꯋꯥꯏꯜꯅꯦꯁ ꯑꯃꯁꯨꯡ ꯃꯦꯗꯤꯀꯦꯜ ꯇꯨꯔꯤꯖꯝꯒꯤ ꯃꯐꯝ ꯑꯃ ꯑꯣꯏꯅ ꯆꯥꯎꯈꯠꯄꯥ ꯄꯥꯝꯃꯤ
--------------------------------------------------

Translating:  82%|██████████████████████▎    | 825/1000 [11:37<03:22,  1.15s/it]

[825/1000]
EN: Borewell found contaminated, pipelines being probed as eight remain in hospital in Madhya Pradesh's Mhow
MNI_MTEI: ꯕꯣꯔꯦꯋꯦꯜ ꯑꯁꯤ ꯄꯠꯊꯔꯛꯄꯥ ꯐꯡꯈꯤ, ꯃꯙꯒꯤ ꯃꯍꯥꯎꯒꯤ ꯍꯣꯁꯄꯤꯇꯥꯂꯗꯥ ꯅꯤꯄꯥꯜ ꯂꯩꯔꯗꯨꯅ ꯂꯩꯕꯗꯒꯤ ꯄꯥꯏꯄꯂꯥꯏꯟꯁꯤꯡ ꯊꯤꯖꯤꯟꯕꯒꯤ ꯊꯕꯛ ꯆꯠꯊꯔꯤ ꯫
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 826/1000 [11:38<03:21,  1.16s/it]

[826/1000]
EN: Uttar Pradesh youth amputates foot to seek disability quota in admission to medical college
MNI_MTEI: ꯎꯠꯇꯔꯒꯤ ꯌꯨꯋꯟꯅꯥ ꯃꯦꯗꯤꯀꯦꯜ ꯀꯣꯂꯦꯖ ꯑꯦꯃꯁꯇꯦꯁꯟꯗꯥ ꯗꯤꯖꯤꯕꯂꯤꯇꯤ ꯀꯣꯇꯥ ꯂꯧꯅꯕꯒꯤꯗꯃꯛ ꯈꯣꯡ ꯀꯛꯊꯠꯂꯤ
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 827/1000 [11:39<03:31,  1.23s/it]

[827/1000]
EN: Police investigate software engineer’s death in Chennai lodge linked to bug repellent fumes
MNI_MTEI: ꯄꯨꯂꯤꯁꯅꯥ ꯆꯦꯟꯅꯥꯏ ꯂꯣꯖꯗꯥ ꯁꯣꯐꯇꯋꯦꯌꯔ ꯏꯟꯖꯤꯅꯤꯌꯔꯒꯤ ꯁꯤꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯊꯤꯖꯤꯜꯂꯤ ꯃꯁꯤ ꯕꯒ ꯔꯤꯄꯦꯂꯦꯟꯇ ꯃꯩꯁꯥꯒꯥ ꯃꯔꯤ ꯂꯩꯅꯩ ꯫
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 828/1000 [11:40<03:12,  1.12s/it]

[828/1000]
EN: Regularly engaging in varied physical activities could extend lifespan
MNI_MTEI: ꯆꯥꯡ ꯅꯥꯏꯅ ꯃꯈꯜ ꯀꯌꯥꯒꯤ ꯐꯤꯖꯤꯀꯦꯜ ꯑꯦꯛꯇꯤꯚꯤꯇꯤꯁꯤꯡꯗ ꯁꯔꯨꯛ ꯌꯥꯕꯅ ꯍꯤꯡꯕꯒꯤ ꯃꯇꯝ ꯍꯦꯟꯒꯠꯍꯟꯕ ꯉꯝꯃꯤ ꯫
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 829/1000 [11:41<03:24,  1.19s/it]

[829/1000]
EN: Study relates ADHD traits in childhood with physical health problems in mid-life
MNI_MTEI: ꯁꯗꯤꯅꯥ ꯑꯉꯥꯡ ꯑꯣꯏꯔꯤꯉꯩ ꯑꯦꯗꯤꯑꯍꯗꯤꯥꯏꯇꯁꯤꯡ ꯑꯁꯤ ꯃꯤꯗ-ꯂꯥꯏꯐꯗꯥ ꯐꯤꯖꯤꯀꯦꯜ ꯍꯦꯜꯊꯄꯂꯝꯁꯤꯡꯒ ꯃꯔꯤ ꯂꯩꯅꯩ ꯫
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 830/1000 [11:42<03:08,  1.11s/it]

[830/1000]
EN: U.S. completes withdrawal from World Health Organization
MNI_MTEI: ꯌꯨ. ꯑꯦꯁ.ꯅꯥ ꯋꯥꯔꯂ ꯭ ꯗ ꯍꯦꯜꯊ ꯑꯣꯔꯒꯅꯥꯏꯖꯦꯁꯟꯗꯒꯤ ꯂꯧꯊꯣꯛꯄ ꯂꯣꯏꯔꯦ
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 831/1000 [11:43<03:07,  1.11s/it]

[831/1000]
EN: Punjab health scheme offers free hospital care worth ₹10 lakh to every family
MNI_MTEI: ꯄꯟꯖꯥꯕ ꯍꯦꯜꯊꯀꯤꯝꯅꯥ ꯏꯃꯨꯡ ꯈꯨꯗꯤꯡꯗꯥ ꯂꯨꯄꯥ ꯂꯥꯈ 10ꯒꯤ ꯍꯣꯁꯄꯤꯇꯥꯜ ꯀꯦꯌꯔ ꯐ
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 832/1000 [11:44<03:02,  1.09s/it]

[832/1000]
EN: Snapchat launches new Family Center safety tools for teens and parents
MNI_MTEI: ꯁꯅꯞꯆꯦꯇꯅꯥ ꯇꯦꯟꯗꯦꯁ ꯑꯃꯁꯨꯡ ꯃꯃꯥ - ꯃꯄꯥꯁꯤꯡꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯐꯦꯃꯤꯂꯤ ꯁꯦꯟꯇꯔ ꯁꯦꯐꯇꯤ ꯇꯨꯜꯁꯤꯡ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 833/1000 [11:46<03:11,  1.15s/it]

[833/1000]
EN: 167 drug samples flagged as ‘not of standard quality’ in December 2025
MNI_MTEI: ꯏꯪꯁꯣꯛꯒꯤ ꯗꯤꯁꯦꯝꯕꯔꯗꯥ ꯗꯒ ꯁꯦꯝꯕꯦꯂ 167 ꯑꯁꯤ ꯅꯗꯔꯗ ꯀꯋꯥꯂꯤꯇꯤꯒꯤ ꯑꯣꯏꯗꯦ ꯍꯥꯏꯅ ꯐ ꯭ ꯂꯦꯒ ꯇꯧ
--------------------------------------------------

Translating:  83%|██████████████████████▌    | 834/1000 [11:47<02:57,  1.07s/it]

[834/1000]
EN: Tamil Nadu issues guidelines as chikungunya cases rise in State
MNI_MTEI: ꯇꯥꯃꯤꯜ ꯅꯥꯗꯨꯗ ꯆꯤꯀꯨꯡꯒꯨꯅꯒꯤ ꯀꯦꯁꯁꯤꯡ ꯍꯦꯟꯒꯠꯂꯛꯄꯗꯒꯤ ꯅꯤꯌꯝꯁꯤꯡ ꯐꯣꯡꯈꯤ
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 835/1000 [11:48<02:53,  1.05s/it]

[835/1000]
EN: Researchers develop tool to simplify nutritional tracking of Indian meals
MNI_MTEI: ꯊꯤꯖꯟ ꯍꯨꯝꯖꯟꯕꯁꯤꯡꯅ ꯚꯥꯔꯠꯀꯤ ꯆꯤꯟꯖꯥꯛꯁꯤꯡꯒꯤꯇꯦꯜ ꯇꯀꯤꯡ ꯂꯥꯏꯊꯣꯛꯍꯟꯅꯕ ꯇꯨꯜ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 836/1000 [11:49<02:49,  1.03s/it]

[836/1000]
EN: Shingles vaccine may also slow down biological ageing in older adults
MNI_MTEI: ꯁꯤꯡꯒꯜꯁ ꯚꯦꯛꯁꯤꯟꯅꯥ ꯃꯄꯨꯡ ꯐꯥꯔꯕꯥ ꯃꯤꯑꯣꯏꯁꯤꯡꯒꯤ बाइओलोजिकेल ꯑꯦꯖꯤꯡꯖꯀꯤ ꯆꯥꯡꯁꯨ ꯍꯟꯊꯍꯟꯕ ꯌꯥꯏ ꯫
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 837/1000 [11:50<02:49,  1.04s/it]

[837/1000]
EN: Gates and OpenAI team up for AI health push in African countries
MNI_MTEI: ꯑꯐꯀꯥꯒꯤ ꯂꯩꯕꯥꯛꯁꯤꯡꯗ ꯑꯦꯑꯏ ꯍꯛꯁꯦꯜ ꯍꯦꯟꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯒꯦꯠꯁ ꯑꯃꯁꯨꯡ ꯑꯣꯄꯟꯑꯦꯑꯥꯏ ꯇꯤꯃ ꯑꯞ ꯇꯧꯔꯦ
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 838/1000 [11:51<02:39,  1.02it/s]

[838/1000]
EN: ASHA workers protest in Kolkata for ₹15,000 monthly honorarium
MNI_MTEI: ꯀꯣꯜꯀꯥꯇꯥꯗꯥ ꯊꯥ ꯈꯨꯗꯤꯡꯒꯤ ꯑꯣꯅꯣꯔꯦꯔꯤꯌꯝꯒꯤꯗꯃꯛ ꯑꯥꯁꯥ ꯋꯥꯔꯀꯔꯁꯤꯡꯅ ꯋꯥꯀꯠ
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 839/1000 [11:52<02:46,  1.04s/it]

[839/1000]
EN: Bloodless heart surgery performed on patient with rare blood group at Kauvery Hospital
MNI_MTEI: ꯀꯥꯋꯦꯔꯤ ꯍꯣꯁꯄꯤꯇꯥꯜꯗꯥ ꯇꯥꯡꯕꯥ ꯕꯗ ꯒꯄ ꯂꯩꯕ ꯑꯅꯥꯕꯥ ꯑꯗꯨꯒꯤ ꯏ ꯌꯥꯎꯗꯕ ꯍꯥꯔꯇ ꯁꯔꯖꯔꯤ ꯄꯥꯡꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 840/1000 [11:53<02:53,  1.08s/it]

[840/1000]
EN: Centre sanctions 50-bed AYUSH hospital for Tenali, says A.P. Minister
MNI_MTEI: ꯀꯦꯟꯗꯅꯥ ꯇꯦꯅꯥꯂꯤꯒꯤꯗꯃꯛ ꯕꯦꯗ ꯂꯩꯕ ꯑꯥꯌꯨꯁ ꯍꯣꯁꯄꯤꯇꯥꯜ ꯑꯌꯥꯕ ꯄꯤꯔꯦ ꯍꯥꯏꯅ ꯑꯦ.ꯄꯤ. ꯃꯟꯇꯅ ꯍꯥꯏ
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 841/1000 [11:54<03:07,  1.18s/it]

[841/1000]
EN: NIMS Hyderabad opens Stem Cell Centre of Excellence as India battles rising burden of lifestyle diseases
MNI_MTEI: ꯅꯤꯃꯁ ꯍꯥꯏꯗꯕꯥꯗꯅ ꯁꯇꯦꯃ ꯁꯦꯜ ꯁꯦꯟꯇꯔ ꯑꯣꯐ ꯑꯦꯛꯁꯂꯦꯟꯁ ꯍꯥꯡꯗꯣꯛꯂꯦ ꯃꯔꯝꯗꯤ ꯚꯥꯔꯠꯇꯥ ꯍꯤꯡꯕꯒꯤ ꯃꯑꯣꯡꯒꯤ ꯂꯥꯏꯅꯥꯁꯤꯡ ꯍꯦꯟꯒꯠꯂꯛꯄꯒ ꯂꯥꯟꯊꯦꯡꯅꯔꯤ ꯫
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 842/1000 [11:56<03:23,  1.29s/it]

[842/1000]
EN: The Ministry of Health and Family Welfare launched a nationwide campaign to improve early detection of non-communicable diseases in rural India.
MNI_MTEI: ꯍꯛꯁꯦꯜ ꯑꯃꯁꯨꯡ ꯏꯃꯨꯡ-ꯃꯅꯥꯏꯒꯤ ꯋꯥꯜꯐꯦꯌꯔ ꯃꯟꯇꯅꯥ ꯈꯨꯡꯒꯪꯒꯤ ꯚꯥꯔꯠꯇꯥ ꯅꯟ-ꯀꯃ ꯭ ꯌꯨꯅꯤꯀꯦꯕꯜ ꯂꯥꯏꯅꯥꯁꯤꯡ ꯉꯟꯅ ꯈꯪꯗꯣꯛꯅꯕ ꯂꯩꯕꯥꯛ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯈꯣꯡꯖꯪ ꯑꯃ ꯍꯧ
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 843/1000 [11:57<03:08,  1.20s/it]

[843/1000]
EN: The Government of India announced an increase in funding for public hospitals under the National Health Mission.
MNI_MTEI: ꯚꯥꯔꯠ ꯁꯔꯀꯥꯔꯅꯥ ꯅꯦꯁꯅꯦꯜ ꯍꯦꯜꯊ ꯃꯤꯁꯟꯒꯤ ꯃꯈꯥꯗ ꯂꯩꯕ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯒꯤ ꯐꯟꯗꯤꯡ ꯍꯦꯟꯒꯠꯍꯟꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 844/1000 [11:58<03:06,  1.20s/it]

[844/1000]
EN: Indian researchers developed a low-cost diagnostic kit to detect tuberculosis with higher accuracy.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯊꯤꯖꯟ ꯍꯨꯝꯖꯟꯕꯁꯤꯡꯅ ꯍꯦꯟꯅ ꯑꯆꯨꯝꯕꯒ ꯂꯣꯏꯅꯅ ꯇꯤꯕꯔꯀꯂꯣꯁꯤꯁ ꯈꯪꯗꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯃꯃꯜ ꯌꯥꯝꯗꯕ ꯗꯥꯏꯒꯅꯣꯁꯇꯤꯛ ꯀꯤꯇ ꯑꯃ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 845/1000 [11:59<03:03,  1.19s/it]

[845/1000]
EN: The Indian Council of Medical Research issued updated guidelines for the treatment of dengue fever.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟ ꯀꯥꯎꯟꯁꯤꯜ ꯑꯣꯐ ꯃꯦꯗꯤꯀꯦꯜ ꯔꯤꯁꯔꯆꯅꯥ ꯗꯦꯡꯒꯨ ꯐꯤꯕꯔ ꯂꯥꯏꯌꯦꯡꯕꯒꯤ ꯑꯞꯗꯦꯇꯦꯗ ꯒꯥꯏꯗꯂꯥꯏꯟꯁꯤꯡ ꯏꯁꯨ ꯇꯧ
--------------------------------------------------

Translating:  85%|██████████████████████▊    | 846/1000 [12:00<03:00,  1.17s/it]

[846/1000]
EN: A new government medical college was inaugurated in Assam to strengthen healthcare education in the northeastern region.
MNI_MTEI: ꯑꯋꯥꯡ- ꯅꯣꯡꯄꯣꯛ ꯂꯝꯗꯝꯗꯥ ꯍꯦꯜꯊꯦꯀꯥꯔ ꯑꯦꯖꯨꯀꯦꯁꯟ ꯑꯗꯨ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯅꯕ ꯑꯁꯥꯝꯗ ꯑꯅꯧꯕ ꯒꯚꯔꯃꯦꯟꯇ ꯃꯦꯗꯤꯀꯦꯜ ꯀꯣꯂꯦꯖ ꯑꯃ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  85%|██████████████████████▊    | 847/1000 [12:02<03:02,  1.19s/it]

[847/1000]
EN: The Union Health Minister reviewed the progress of Ayushman Bharat services across multiple states.
MNI_MTEI: ꯀꯦꯟꯗꯒꯤ ꯍꯛꯁꯦꯜ ꯃꯟꯇꯅꯥ ꯇꯣꯉꯥꯟ-ꯇꯣꯉꯥꯟꯕꯇꯥ ꯑꯥꯌꯨꯁꯃꯟ ꯚꯥꯔꯠ ꯁꯔꯕꯤꯁꯦꯁꯀꯤ ꯄꯒꯁ ꯔꯤꯚ ꯇꯧ
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 848/1000 [12:03<03:02,  1.20s/it]

[848/1000]
EN: India reported a decline in maternal mortality rates due to improved institutional delivery services.
MNI_MTEI: ꯏꯟꯁꯇꯤꯇꯁꯅꯦꯜ ꯗꯦꯂꯤꯚꯔꯤ ꯁꯔꯕꯤꯁꯁꯤꯡ ꯐꯒꯠꯂꯛꯄꯅꯥ ꯃꯔꯝ ꯑꯣꯏꯗꯨꯅ ꯚꯥꯔꯠꯇꯥ ꯃꯦꯇꯔꯅꯦꯜ ꯃꯣꯔꯇꯥꯂꯤꯇꯤ ꯔꯦꯠ ꯍꯟꯊꯔꯛꯄꯒꯤ ꯄꯥꯎ ꯄꯤ
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 849/1000 [12:04<02:57,  1.17s/it]

[849/1000]
EN: The Drug Controller General of India approved a new vaccine for preventing cervical cancer.
MNI_MTEI: ꯗꯒ ꯀꯟꯇꯜꯂꯔ ꯖꯦꯅꯔꯦꯜ ꯑꯣꯐ ꯏꯟꯗꯤꯌꯥꯅꯥ ꯁꯔꯚꯤꯀꯦꯜ ꯀꯦꯟꯁꯔ ꯊꯤꯡꯅꯕꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯕꯦꯛꯁꯤꯟ ꯑꯃ ꯑꯌꯥꯕ ꯄꯤ
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 850/1000 [12:05<02:55,  1.17s/it]

[850/1000]
EN: Several state governments expanded free dialysis services in district hospitals.
MNI_MTEI: ꯇ ꯒꯕꯔꯅꯃꯦꯟꯇ ꯀꯌꯥꯅꯥ ꯗꯤꯁꯇꯛꯇ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯗ ꯐ ꯗꯥꯏꯂꯥꯏꯁꯤꯁ ꯁꯔꯕꯤꯁꯁꯤꯡ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 851/1000 [12:06<03:00,  1.21s/it]

[851/1000]
EN: The World Health Organization praised India’s efforts in polio eradication during a regional health summit.
MNI_MTEI: ꯋꯥꯔꯂ ꯭ ꯗ ꯍꯦꯜꯊ ꯑꯣꯔꯒꯥꯅꯥꯏꯖꯦꯁꯟꯅꯥ ꯔꯤꯖꯅꯦꯜ ꯍꯦꯂꯊ ꯁꯝꯃꯤꯠ ꯑꯃꯗ ꯄꯣꯂꯤꯑꯣ ꯃꯨꯠꯊꯠꯄꯗꯥ ꯚꯥꯔꯠꯅ ꯍꯣꯠꯅꯔꯤꯕꯁꯤꯡ ꯑꯗꯨ ꯊꯥꯒꯠ
--------------------------------------------------

Translating:  85%|███████████████████████    | 852/1000 [12:08<02:57,  1.20s/it]

[852/1000]
EN: A public health survey revealed improved vaccination coverage among children in urban slum areas.
MNI_MTEI: ꯄ ꯍꯦꯜꯊ ꯁꯔꯚꯦ ꯑꯃꯅ ꯑꯔꯕꯟ ꯁꯜꯃ ꯑꯦꯔꯤꯌꯥꯁꯤꯡꯒꯤ ꯑꯉꯥꯡꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯕꯦꯛꯁꯤꯅꯦꯁꯟ ꯀꯚꯔꯦꯖ ꯐꯒꯠꯍꯟꯕꯥ ꯐꯣꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  85%|███████████████████████    | 853/1000 [12:09<02:58,  1.22s/it]

[853/1000]
EN: The Ministry of AYUSH promoted traditional medicine research through newly funded clinical studies.
MNI_MTEI: ꯑꯥꯌꯨꯁ ꯃꯟꯇꯅꯥ ꯑꯅꯧꯕ ꯁꯦꯜ ꯊꯥꯗꯕ ꯀꯂꯤꯅꯤꯀꯦꯜꯗꯤꯖꯁꯤꯡꯒꯤ ꯈꯨꯠꯊꯥꯡꯗꯗꯤꯁꯅꯦꯜ ꯃꯦꯗꯤꯁꯤꯟ ꯔꯤꯁꯔꯆꯄꯨ ꯄ ꯭ ꯔꯣꯃꯣꯇ ꯇꯧ
--------------------------------------------------

Translating:  85%|███████████████████████    | 854/1000 [12:10<03:04,  1.27s/it]

[854/1000]
EN: Indian hospitals adopted artificial intelligence tools to assist doctors in early cancer detection.
MNI_MTEI: ꯀꯦꯟꯁꯔ ꯑꯁꯤ ꯉꯟꯅ ꯈꯪꯗꯣꯛꯄꯗꯥ ꯗꯣꯛꯇꯔꯁꯤꯡꯕꯨ ꯃꯇꯦꯡ ꯄꯥꯡꯅꯕ ꯏꯟꯗꯤꯌꯟ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯅ ꯑꯥꯔꯇꯤꯐꯤꯁꯦꯜ ꯏꯟꯇꯦꯂꯤꯖꯦꯟꯁꯀꯤ ꯇꯨꯜꯁꯤꯡ ꯁꯤꯖꯤꯟꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████    | 855/1000 [12:12<03:06,  1.29s/it]

[855/1000]
EN: The National Medical Commission introduced revised norms for undergraduate medical education.
MNI_MTEI: ꯅꯦꯁꯅꯦꯜ ꯃꯦꯗꯤꯀꯦꯜ ꯀꯃꯤꯁꯟꯅꯥ ꯑꯡꯒꯖꯨꯑꯦꯠ ꯃꯦꯗꯗꯤꯀꯦꯜ ꯑꯦꯖꯨꯀꯦꯁꯟꯒꯤꯗꯃꯛ ꯔꯤꯚꯥꯏꯖ ꯇꯧꯔꯕꯥ ꯅꯤꯌꯝꯁꯤꯡ ꯆꯠꯅꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████    | 856/1000 [12:13<03:04,  1.28s/it]

[856/1000]
EN: A shortage of specialist doctors was reported in government hospitals across rural districts.
MNI_MTEI: ꯈꯨꯡꯒꯪꯒꯤ ꯖꯤꯂꯥꯁꯤꯡ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯂꯩꯕ ꯁꯔꯀꯥꯔꯒꯤ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯗ ꯁꯄꯁꯤꯌꯦꯂꯤꯁꯇ ꯗꯣꯛꯇꯔꯁꯤꯡꯒꯤ ꯑꯋꯥꯠꯄ ꯂꯩ ꯍꯥꯏꯅ ꯄꯥꯎꯗꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 857/1000 [12:14<03:01,  1.27s/it]

[857/1000]
EN: The central government launched a digital health ID system to streamline patient medical records.
MNI_MTEI: ꯀꯦꯟꯗ ꯁꯔꯀꯥꯔꯅꯥ ꯑꯅꯥꯕꯥꯁꯤꯡꯒꯤ ꯃꯦꯗꯤꯀꯦꯜ ꯔꯦꯀꯣꯔꯗꯁꯤꯡ ꯁꯃꯂꯥꯏꯟ ꯇꯧꯅꯕꯒꯤꯗꯃꯛ ꯗꯤꯖꯤꯇꯦꯜ ꯍꯦꯜꯊ ꯑꯥꯏꯗꯤ ꯁꯤꯁꯇꯦꯝ ꯑꯃ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 858/1000 [12:15<02:56,  1.24s/it]

[858/1000]
EN: India’s pharmaceutical exports increased due to rising global demand for generic medicines.
MNI_MTEI: ꯖꯦꯅꯦꯔꯤꯛ ꯍꯤꯗꯥꯛ-ꯃꯇꯥꯏꯁꯤꯡꯒꯤ ꯒ ꯭ ꯂꯣꯕꯦꯜ ꯗꯤꯃꯥꯟꯗ ꯍꯦꯟꯒꯠꯂꯛꯄꯗꯒꯤ ꯚꯥꯔꯠꯀꯤ ꯐꯥꯔꯃꯥꯁꯤꯌꯨꯇꯤꯀꯦꯜ ꯑꯦꯛꯁꯄꯣꯔꯇꯁꯤꯡ ꯍꯦꯟꯒꯠꯂꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 859/1000 [12:16<02:53,  1.23s/it]

[859/1000]
EN: The Supreme Court of India directed states to improve healthcare infrastructure in tribal areas.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯁꯨꯄꯝ ꯀꯣꯔꯠꯅꯇꯁꯤꯡꯗ ꯇꯥꯏꯕꯦꯜ ꯑꯦꯔꯤꯌꯥꯁꯤꯡꯒꯤ ꯍꯛꯁꯦꯜꯒꯤ ꯏꯟꯐꯁꯇꯛꯆꯔ ꯐꯒꯠꯍꯟꯅꯕ ꯂꯝꯖꯤꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 860/1000 [12:18<02:50,  1.22s/it]

[860/1000]
EN: A government report highlighted gaps in mental health services in public healthcare facilities.
MNI_MTEI: ꯒꯚꯔꯃꯦꯟꯇ ꯔꯤꯄꯣꯔꯇ ꯑꯃꯅ ꯍꯦꯜꯊꯦꯌꯔ ꯐꯦꯁꯤꯂꯤꯇꯤꯁꯤꯡꯗ ꯃꯦꯟꯇꯥꯜ ꯍꯦꯜꯊ ꯁꯔꯕꯤꯁꯁꯤꯡꯒꯤ ꯑꯍꯥꯡꯕꯁꯤꯡ ꯎꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 861/1000 [12:19<02:49,  1.22s/it]

[861/1000]
EN: Several private hospitals partnered with state governments to offer affordable cardiac care.
MNI_MTEI: ꯂꯅꯥꯏꯒꯤ ꯍꯣꯁꯄꯤꯇꯥꯜ ꯀꯌꯥꯅꯥꯇ ꯒꯚꯔꯃꯦꯟꯇꯁꯤꯡꯒ ꯂꯣꯏꯅꯅꯥ ꯃꯃꯜ ꯌꯥꯝꯗꯕ ꯀꯥꯔꯗꯤꯑꯦꯛ ꯀꯦꯌꯔ ꯄꯤꯅꯕ ꯁꯔꯨꯛ ꯌꯥꯔꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 862/1000 [12:20<02:52,  1.25s/it]

[862/1000]
EN: The Indian Institute of Public Health conducted a study on air pollution-related respiratory diseases.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟ ꯏꯟꯁꯇꯤꯇꯇ ꯑꯣꯐ ꯄ ꯍꯦꯜꯊꯅꯥ ꯅꯨꯡꯁꯤꯠꯀꯤ ꯄꯨꯂꯨꯁꯟꯒ ꯃꯔꯤ ꯂꯩꯅꯕ ꯁꯄꯔꯦꯇꯔꯤ ꯗꯤꯖꯤꯖꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯊꯤꯖꯤꯟꯕꯒꯤ ꯊꯕꯛ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 863/1000 [12:21<02:49,  1.24s/it]

[863/1000]
EN: Health officials initiated a special drive to control the spread of seasonal influenza.
MNI_MTEI: ꯍꯛꯁꯦꯜꯒꯤ ꯑꯣꯐꯤꯁꯌꯦꯜꯁꯤꯡꯅ ꯁꯤꯖꯅꯦꯜ ꯏꯟꯐꯂꯨꯑꯦꯟꯖꯥ ꯁꯟꯗꯣꯛꯄꯥ ꯀꯟꯇꯣꯜ ꯇꯧꯅꯕꯒꯤꯗꯃꯛ ꯊꯣꯏꯗꯣꯛꯍꯦꯟꯗꯣꯛꯄ ꯊꯧꯁꯤꯜ ꯑꯃ ꯍꯧ
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 864/1000 [12:23<02:48,  1.24s/it]

[864/1000]
EN: The Ministry of Health strengthened surveillance systems to monitor emerging infectious diseases.
MNI_MTEI: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥ ꯍꯧꯒꯠꯂꯛꯄꯥ ꯏꯟꯐꯦꯛꯁ ꯭ ꯌꯦꯁ ꯑꯣꯏꯕ ꯂꯥꯏꯅꯥꯁꯤꯡ ꯌꯦꯡꯁꯤꯟꯅꯕ ꯌꯦꯡꯁꯤꯟꯕꯒꯤ ꯁꯤꯁꯇꯦꯝꯁꯤꯡ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 865/1000 [12:24<02:44,  1.22s/it]

[865/1000]
EN: India recorded a steady rise in organ donation registrations through national awareness campaigns.
MNI_MTEI: ꯚꯥꯔꯠꯇꯥ ꯅꯦꯁꯅꯦꯜ ꯑꯦꯚꯦꯌꯔꯅꯦꯁ ꯀꯦꯝꯄꯦꯟꯁꯤꯡꯒꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯑꯣꯒꯅꯥ ꯗꯣꯅꯦꯁꯟ ꯔꯦꯖꯤꯁꯇꯦꯁꯟꯁꯤꯡ ꯆꯥꯡ ꯅꯥꯏꯅ ꯍꯦꯟꯒꯠꯂꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 866/1000 [12:25<02:38,  1.18s/it]

[866/1000]
EN: A new telemedicine platform was introduced to improve access to healthcare in remote villages.
MNI_MTEI: ꯂꯥꯞꯊꯣꯛꯂꯕ ꯈꯨꯡꯒꯪꯁꯤꯡꯗ ꯍꯛꯁꯦꯜꯒꯤ ꯈꯨꯗꯣꯡꯆꯥꯕꯥ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯇꯦꯂꯤꯃꯦꯗꯤꯁꯤꯟꯇꯐꯣꯔꯝ ꯑꯃ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 867/1000 [12:26<02:34,  1.16s/it]

[867/1000]
EN: The National AIDS Control Organisation reported a decline in new HIV infections.
MNI_MTEI: ꯅꯦꯁꯅꯦꯜ ꯑꯦꯗꯁ ꯀꯟꯇꯣꯜ ꯑꯣꯔꯒꯥꯅꯥꯏꯖꯦꯁꯟꯅꯥ ꯑꯅꯧꯕ ꯑꯩꯆꯑꯥꯏꯚꯤ ꯏꯟꯐꯦꯛꯁꯟꯁꯤꯡ ꯍꯟꯊꯔꯛꯄꯒꯤ ꯄꯥꯎꯗꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 868/1000 [12:27<02:30,  1.14s/it]

[868/1000]
EN: Government hospitals increased the availability of free essential medicines for outpatients.
MNI_MTEI: ꯒꯚꯔꯃꯦꯟꯇ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡ ꯑꯁꯤꯅ ꯑꯥꯎꯇꯄꯦꯇꯤꯌꯦꯟꯇꯁꯤꯡꯒꯤꯗꯃꯛ ꯇꯉꯥꯏꯐꯗꯕ ꯍꯤꯗꯥꯛꯁꯤꯡ ꯐꯪꯍꯟꯕꯥ ꯍꯦꯟꯒꯠꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 869/1000 [12:28<02:31,  1.16s/it]

[869/1000]
EN: A policy review emphasized the need for more nursing staff in public healthcare institutions.
MNI_MTEI: ꯄꯣꯂꯤꯁꯤ ꯔꯤꯚꯤꯎ ꯑꯃꯥꯅꯥ ꯄ ꯍꯦꯜꯊꯦꯌꯔ ꯏꯟꯁꯇꯤꯇꯁꯟꯁꯤꯡꯗ ꯅꯔꯁꯤꯡꯐ ꯍꯦꯟꯅ ꯃꯊꯧ ꯇꯥꯕꯒꯤ ꯃꯔꯝꯗꯥ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 870/1000 [12:29<02:22,  1.09s/it]

[870/1000]
EN: The Indian government signed a health cooperation agreement with a neighboring country.
MNI_MTEI: ꯚꯥꯔꯠ ꯁꯔꯀꯥꯔꯅꯥ ꯌꯨꯝꯂꯣꯟꯅꯕ ꯂꯩꯕꯥꯛ ꯑꯃꯒ ꯍꯦꯜꯊ ꯀꯣꯑꯣꯄꯔꯦꯁꯟ ꯑꯦꯒꯃꯦꯟꯇ ꯑꯃ ꯈꯨꯠꯌꯦꯛ ꯄꯤꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 871/1000 [12:30<02:26,  1.14s/it]

[871/1000]
EN: Researchers from an Indian medical institute published findings on antibiotic resistance trends.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟ ꯃꯦꯗꯤꯀꯦꯜ ꯏꯟꯁꯇꯤꯇꯠꯇꯒꯤ ꯊꯤꯖꯟ ꯍꯨꯝꯖꯟꯕꯁꯤꯡꯅ ꯑꯦꯟꯇꯤꯕꯥꯏꯑꯣꯇꯤꯛ ꯔꯦꯖꯤꯁꯇꯦꯟꯁꯦꯟꯗꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯊꯤꯒꯠꯄꯁꯤꯡ ꯐꯣꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 872/1000 [12:32<02:24,  1.13s/it]

[872/1000]
EN: The Health Ministry issued advisories to states following a rise in heat-related illnesses.
MNI_MTEI: ꯍꯛꯁꯦꯜ ꯃꯟꯇꯅꯥ ꯃꯩꯁꯥꯒꯥ ꯃꯔꯤ ꯂꯩꯅꯕ ꯂꯥꯏꯅꯥꯁꯤꯡ ꯍꯦꯟꯒꯠꯂꯛꯄꯗꯒꯤ ꯔꯥꯖꯁꯤꯡꯗ ꯑꯦꯗꯚꯥꯏꯖꯔꯤꯁꯤꯡ ꯄꯤ
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 873/1000 [12:33<02:28,  1.17s/it]

[873/1000]
EN: India expanded its emergency ambulance network to improve response times in rural regions.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯃꯈꯣꯏꯒꯤ ꯏꯃꯔꯖꯦꯟꯁꯤ ꯑꯦꯝꯕꯂꯦꯟꯁ ꯅꯦꯠꯋꯥꯔꯛ ꯑꯗꯨ ꯈꯨꯡꯒꯪꯒꯤ ꯂꯝꯗꯝꯁꯤꯡꯗ ꯔꯤꯄꯣꯟꯁ ꯇꯥꯏꯝꯁꯤꯡ ꯐꯒꯠꯍꯟꯅꯕ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 874/1000 [12:34<02:25,  1.15s/it]

[874/1000]
EN: The National Digital Health Mission aimed to improve transparency in healthcare service delivery.
MNI_MTEI: ꯅꯦꯁꯅꯦꯜ ꯗꯤꯖꯤꯇꯦꯜ ꯍꯦꯜꯊ ꯃꯤꯁꯟ ꯑꯁꯤꯅ ꯍꯦꯜꯊꯦꯌꯔ ꯁꯔꯕꯤꯁ ꯗꯤꯂꯤꯚꯔꯤꯗꯥꯄꯔꯦꯟꯁꯤꯇꯤ ꯐꯒꯠꯍꯟꯅꯕ ꯄꯥꯟꯗꯝ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 875/1000 [12:35<02:34,  1.23s/it]

[875/1000]
EN: A public-private partnership model was introduced to upgrade district-level hospitals.
MNI_MTEI: ꯗꯤꯁꯇꯛꯇ-ꯂꯦꯚꯦꯜ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡ ꯑꯒꯗ ꯇꯧꯅꯕꯒꯤꯗꯃꯛ ꯄꯕꯀꯜ-ꯄꯥꯏꯚꯦꯇ ꯄꯔꯅꯥꯇꯔꯁꯤꯞ ꯃꯣꯗꯦꯜ ꯑꯃ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 876/1000 [12:36<02:29,  1.20s/it]

[876/1000]
EN: The government launched a mental health helpline to support individuals during medical emergencies.
MNI_MTEI: ꯁꯔꯀꯥꯔꯅꯥ ꯃꯦꯗꯤꯀꯦꯜ ꯏꯃꯔꯖꯦꯟꯁꯤꯁꯤꯡꯒꯤ ꯃꯇꯝꯗ ꯃꯤꯌꯣꯏꯁꯤꯡꯕꯨ ꯃꯇꯦꯡ ꯄꯥꯡꯅꯕ ꯃꯦꯟꯇꯦꯜ ꯍꯦꯜꯊꯂꯥꯏꯟ ꯑꯃ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 877/1000 [12:38<02:21,  1.15s/it]

[877/1000]
EN: India’s medical tourism sector showed growth due to affordable treatment options.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯃꯦꯗꯤꯀꯦꯜ ꯇꯨꯔꯤꯖꯝ ꯁꯦꯛꯇꯔꯅ ꯃꯃꯜ ꯅꯥꯏꯕꯥ ꯂꯥꯏꯌꯦꯡꯒꯤ ꯑꯣꯞꯁꯟꯁꯤꯡ ꯂꯩꯕꯅ ꯃꯔꯝ ꯑꯣꯏꯗꯨꯅ ꯆꯥꯎꯈꯠꯂꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 878/1000 [12:39<02:20,  1.16s/it]

[878/1000]
EN: A parliamentary committee reviewed the implementation of healthcare schemes in backward districts.
MNI_MTEI: ꯄꯥꯔꯂꯤꯌꯥꯃꯦꯟꯇꯀꯤ ꯀꯝꯃꯤꯇꯤ ꯑꯃꯅ ꯕꯦꯀꯋꯥꯔꯗ ꯗꯤꯁꯇꯛꯇꯁꯤꯡꯗ ꯍꯦꯜꯊꯦꯌꯔꯀꯤꯝꯁꯤꯡ ꯆꯠꯅꯍꯟꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯔꯤꯚ ꯇꯧ
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 879/1000 [12:40<02:12,  1.10s/it]

[879/1000]
EN: The Ministry of Health emphasized preventive healthcare during a national policy meeting.
MNI_MTEI: ꯅꯦꯁꯅꯦꯜ ꯄꯣꯂꯤꯁꯤ ꯃꯤꯇꯤꯡ ꯑꯃꯗ ꯍꯛꯁꯦꯜ ꯃꯟꯇꯅꯥ ꯄꯇꯤꯚꯦꯟꯇꯋꯦꯜ ꯍꯦꯜꯊꯦꯌꯔꯗꯥ ꯄꯨꯛꯅꯤꯡ ꯆꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 880/1000 [12:41<02:08,  1.07s/it]

[880/1000]
EN: Indian scientists developed a wearable device to monitor heart health in elderly patients.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯁꯥꯏꯅꯇꯤꯁꯁꯤꯡꯅ ꯆꯍꯤ ꯋꯥꯡꯕꯥ ꯑꯅꯥꯕꯥꯁꯤꯡꯒꯤ ꯍꯔꯇ ꯍꯦꯜꯊ ꯌꯦꯡꯁꯤꯟꯅꯕ ꯌꯦꯔꯦꯑꯦꯕꯜ ꯗꯤꯚꯥꯏꯁ ꯑꯃ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 881/1000 [12:42<02:02,  1.03s/it]

[881/1000]
EN: A national survey assessed nutritional deficiencies among children under five years of age.
MNI_MTEI: ꯅꯦꯁꯅꯦꯜ ꯁꯔꯚꯦ ꯑꯃꯅ ꯆꯍꯤ ꯃꯉꯥꯒꯤ ꯃꯈꯥꯗ ꯂꯩꯕ ꯑꯉꯥꯡꯁꯤꯡꯒꯤꯇꯦꯜ ꯗꯤꯐꯤꯁꯤꯟꯁꯤꯁꯤꯡ ꯌꯦꯡꯁꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 882/1000 [12:43<02:04,  1.05s/it]

[882/1000]
EN: The government increased insurance coverage limits under Ayushman Bharat for critical illnesses.
MNI_MTEI: ꯁꯔꯀꯥꯔꯅꯥ ꯀꯇꯤꯀꯦꯜ ꯏꯂꯥꯏꯟꯁꯁꯤꯡꯒꯤꯗꯃꯛ ꯑꯥꯌꯨꯁꯃꯟ ꯚꯥꯔꯠꯀꯤ ꯃꯈꯥꯗ ꯏꯟꯁꯨꯔꯦꯟꯁ ꯀꯣꯚꯔꯦꯖ ꯂꯤꯃꯤꯇꯁꯤꯡ ꯍꯦꯟꯒꯠꯍꯟ
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 883/1000 [12:44<02:00,  1.03s/it]

[883/1000]
EN: Health authorities conducted vaccination drives to prevent outbreaks of measles and rubella.
MNI_MTEI: ꯍꯛꯁꯦꯜꯒꯤ ꯊꯧꯗꯥꯡꯂꯣꯏꯁꯤꯡꯅ ꯃꯤꯖꯜꯁ ꯑꯃꯁꯨꯡ ꯔꯨꯕꯦꯂꯥ ꯁꯟꯗꯣꯛꯇꯅꯕ ꯕꯦꯛꯁꯤꯅꯦꯁꯟ ꯗꯚꯁꯤꯡ ꯄꯥꯡꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 884/1000 [12:45<02:00,  1.04s/it]

[884/1000]
EN: India strengthened laboratory capacity to improve disease surveillance and diagnosis.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯂꯥꯏꯅꯥ ꯌꯦꯡꯁꯤꯟꯕ ꯑꯃꯁꯨꯡ ꯂꯥꯏꯑꯣꯡ ꯈꯪꯗꯣꯛꯄꯒꯤ ꯐꯤꯕꯝ ꯐꯒꯠꯍꯟꯅꯕ ꯂꯦꯕꯣꯔꯦꯇꯔꯤ ꯀꯦꯄꯦꯁꯤꯇꯤ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▉   | 885/1000 [12:46<02:09,  1.13s/it]

[885/1000]
EN: A state health department launched mobile clinics to serve remote tribal communities.
MNI_MTEI: ꯔꯥꯖꯒꯤ ꯍꯛꯁꯦꯜ ꯗꯤꯄꯥꯔꯇꯃꯦꯟꯇ ꯑꯃꯅ ꯂꯥꯞꯊꯣꯛꯂꯕ ꯇꯥꯏꯕꯦꯜ ꯀꯝꯃꯅꯤꯇꯤꯁꯤꯡꯒꯤ ꯁꯦꯕꯥ ꯇꯧꯅꯕꯒꯤꯗꯃꯛ ꯃꯣꯕꯥꯏꯜ ꯀꯂꯤꯅꯤꯛꯁꯤꯡ ꯍꯥꯡꯗꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 886/1000 [12:47<02:06,  1.11s/it]

[886/1000]
EN: The National Health Authority upgraded its data systems to enhance patient safety.
MNI_MTEI: ꯅꯦꯁꯅꯦꯜ ꯍꯦꯜꯊ ꯑꯣꯊꯣꯔꯤꯇꯤꯅꯥ ꯃꯈꯣꯏꯒꯤ ꯗꯦꯇꯥ ꯁꯤꯁꯇꯦꯝꯁꯤꯡ ꯑꯁꯤ ꯑꯅꯥꯕꯥꯁꯤꯡꯒꯤ ꯁꯦꯐꯇꯤ ꯍꯦꯟꯒꯠꯍꯟꯅꯕ ꯑꯞꯒꯗ ꯇꯧ
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 887/1000 [12:48<02:03,  1.09s/it]

[887/1000]
EN: Indian doctors highlighted the need for early screening of lifestyle-related diseases.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯗꯣꯛꯇꯔꯁꯤꯡꯅ ꯍꯤꯡꯕꯒꯤ ꯃꯑꯣꯡꯒ ꯃꯔꯤ ꯂꯩꯅꯕ ꯂꯥꯏꯅꯥꯁꯤꯡ ꯉꯟꯅ ꯁꯅꯤꯡ ꯇꯧꯕꯒꯤ ꯃꯊꯧ ꯇꯥꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯍꯥꯏꯂꯥꯏꯇ ꯇꯧꯈꯤ ꯫
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 888/1000 [12:49<01:58,  1.06s/it]

[888/1000]
EN: The Ministry of Health released new guidelines for hospital waste management.
MNI_MTEI: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥ ꯍꯣꯁꯄꯤꯇꯥꯜ ꯋꯇ ꯃꯦꯅꯖꯃꯦꯟꯇꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯅꯤꯌꯝꯁꯤꯡ ꯐꯣꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  89%|████████████████████████   | 889/1000 [12:50<01:54,  1.03s/it]

[889/1000]
EN: Several states reported improvements in primary healthcare access through wellness centers.
MNI_MTEI: ꯔꯥꯖ ꯀꯌꯥꯅꯥ ꯋꯦꯜꯅꯦꯁ ꯁꯦꯟꯇꯔꯁꯤꯡꯒꯤ ꯈꯨꯠꯊꯥꯡꯗꯥꯏꯃꯔꯤ ꯍꯦꯜꯊꯀꯦꯌꯔ ꯑꯦꯛꯁꯦꯁꯇ ꯐꯒꯠꯂꯛꯄꯒꯤ ꯄꯥꯎꯗꯝ
--------------------------------------------------

Translating:  89%|████████████████████████   | 890/1000 [12:51<01:52,  1.02s/it]

[890/1000]
EN: India’s public health expenditure showed a gradual increase in the latest budget.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤꯍꯦꯜꯊ ꯆꯥꯗꯤꯡꯅꯥ ꯈ ꯭ ꯋꯥꯏꯗꯒꯤ ꯅꯧꯕ ꯕꯖꯦꯇꯗꯥ ꯃꯊꯪ-ꯃꯇꯥ ꯍꯦꯟꯒꯠꯂꯛꯄ ꯎꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  89%|████████████████████████   | 891/1000 [12:52<01:49,  1.00s/it]

[891/1000]
EN: A new online portal was launched to track the availability of hospital beds.
MNI_MTEI: ꯍꯣꯁꯄꯤꯇꯥꯜꯒꯤ ꯕꯦꯗꯁꯤꯡ ꯐꯪꯕꯥ ꯇꯦꯛ ꯇꯧꯅꯕꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯑꯣꯟꯂꯥꯏꯟ ꯄꯣꯔꯇꯦꯜ ꯑꯃ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  89%|████████████████████████   | 892/1000 [12:53<01:52,  1.04s/it]

[892/1000]
EN: Health experts in India raised concerns about rising cases of diabetes among young adults.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯍꯦꯜꯊ ꯑꯦꯛꯁꯄꯥꯔꯇꯁꯤꯡꯅꯥ ꯑꯉꯥꯡ ꯑꯣꯏꯔꯕꯥ ꯃꯤꯑꯣꯏꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯗꯥꯏꯑꯦꯕꯦꯇꯤꯁꯀꯤ ꯀꯦꯁꯁꯤꯡ ꯍꯦꯟꯒꯠꯂꯛꯄꯒꯤ ꯃꯇꯥꯡꯗ ꯋꯥꯈꯜ ꯋꯥꯊꯣꯛ ꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  89%|████████████████████████   | 893/1000 [12:54<01:55,  1.08s/it]

[893/1000]
EN: The government initiated training programs to improve emergency care skills among paramedics.
MNI_MTEI: ꯁꯔꯀꯥꯔꯅꯥ ꯄꯦꯔꯥꯃꯦꯗꯤꯛꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯏꯃꯔꯖꯦꯟꯁꯤ ꯀꯦꯌꯔꯒꯤ ꯍꯩꯁꯤꯡꯕꯁꯤꯡ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛꯅꯤꯡꯒꯔꯥꯝꯁꯤꯡ ꯍꯧꯍꯟ
--------------------------------------------------

Translating:  89%|████████████████████████▏  | 894/1000 [12:55<01:51,  1.05s/it]

[894/1000]
EN: Indian pharmaceutical companies invested in research for affordable cancer medicines.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯐꯥꯔꯃꯥꯁꯤꯌꯨꯇꯤꯀꯦꯜ ꯀꯝꯄꯅꯤꯁꯤꯡꯅꯥ ꯀꯦꯟꯁꯔꯒꯤ ꯍꯤꯗꯥꯛ-ꯃꯊꯛꯀꯤ ꯔꯤꯁꯔꯆꯗꯥ ꯁꯦꯜ ꯊꯥꯗ
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 895/1000 [12:56<01:43,  1.01it/s]

[895/1000]
EN: A national task force was formed to address antimicrobial resistance.
MNI_MTEI: ꯑꯦꯟꯇꯤꯃꯥꯏꯀꯕꯥꯏꯜ ꯔꯦꯖꯤꯁꯇꯦꯟꯁ ꯀꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯅꯦꯁꯅꯦꯜ ꯇꯛꯁ ꯐꯣꯔꯁ ꯑꯃ ꯁꯦꯝ
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 896/1000 [12:57<01:47,  1.03s/it]

[896/1000]
EN: The Health Ministry conducted audits to improve quality standards in government hospitals.
MNI_MTEI: ꯍꯛꯁꯦꯜ ꯃꯟꯇꯅꯥ ꯒꯚꯔꯃꯦꯟꯇ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯒꯤ ꯀꯋꯥꯂꯤꯇꯤꯦꯟꯗꯗꯔ ꯐꯒꯠꯍꯟꯅꯕ ꯑꯣꯗꯤꯇꯁꯤꯡ ꯄꯥꯡꯊꯣꯛ
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 897/1000 [12:59<01:52,  1.09s/it]

[897/1000]
EN: India expanded maternal nutrition programs to reduce anemia among pregnant women.
MNI_MTEI: ꯃꯤꯔꯣꯜꯂꯤꯕꯤ ꯅꯨꯄꯤꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯏꯅꯤꯃꯤꯌꯥ ꯍꯟꯊꯍꯟꯅꯕ ꯚꯥꯔꯠꯅ ꯃꯦꯇꯔꯅꯦꯜ ꯅꯇꯁꯟꯒꯔꯥꯝꯁꯤꯡ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 898/1000 [12:59<01:40,  1.01it/s]

[898/1000]
EN: A state government announced free health checkups for senior citizens.
MNI_MTEI: ꯁꯇ ꯒꯚꯔꯃꯦꯟꯇꯅꯥ ꯁꯦꯅꯤꯌꯔ ꯁꯤꯇꯤꯖꯟꯁꯤꯡꯒꯤ ꯐ ꯍꯦꯜꯊ ꯆꯦꯛꯑꯞꯁꯤꯡ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 899/1000 [13:00<01:38,  1.02it/s]

[899/1000]
EN: Indian healthcare startups focused on digital solutions for chronic disease management.
MNI_MTEI: ꯀꯅꯤꯛ ꯗꯤꯖꯤꯖ ꯃꯦꯅꯖꯃꯦꯟꯇꯒꯤꯗꯃꯛ ꯏꯟꯗꯤꯌꯟ ꯍꯦꯜꯊꯀꯦꯌꯔꯇꯥꯔꯇꯑꯞꯁꯅ ꯗꯤꯖꯦꯇꯤꯜ ꯁꯂꯨꯁꯟꯁꯤꯡꯗ ꯃꯤꯠꯌꯦꯡ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 900/1000 [13:01<01:32,  1.09it/s]

[900/1000]
EN: The National Health Policy emphasized universal access to affordable healthcare services.
MNI_MTEI: ꯅꯦꯁꯅꯦꯜ ꯍꯦꯜꯊ ꯄꯣꯂꯤꯁꯤꯅꯥ ꯃꯃꯜ ꯅꯥꯏꯕꯥ ꯍꯦꯜꯊꯦꯌꯔ ꯁꯔꯕꯤꯁꯁꯤꯡꯒꯤ ꯌꯨꯅꯤꯚꯦꯁꯜ ꯑꯦꯛꯁꯦꯁꯇ ꯄꯨꯛꯅꯤꯡ ꯆꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 901/1000 [13:02<01:29,  1.11it/s]

[901/1000]
EN: Public health officials promoted lifestyle changes to reduce cardiovascular disease risks.
MNI_MTEI: ꯍꯦꯜꯊ ꯑꯣꯐꯤꯁꯌꯦꯜꯁꯤꯡꯅ ꯀꯥꯔꯗꯤꯑꯣꯁꯀꯦꯜ ꯗꯤꯖꯤꯖ ꯔꯤꯁꯀꯁꯤꯡ ꯍꯟꯊꯍꯟꯅꯕ ꯍꯤꯡꯕꯒꯤ ꯃꯑꯣꯡ ꯍꯣꯡꯗꯣꯛꯅꯕ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 902/1000 [13:03<01:27,  1.13it/s]

[902/1000]
EN: India improved cold chain infrastructure to ensure vaccine safety and effectiveness.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯕꯦꯛꯁꯤꯟ ꯁꯦꯐꯇꯤ ꯑꯃꯁꯨꯡ ꯑꯦꯐꯦꯛꯇꯤꯚꯦꯟꯁꯤꯇꯤ ꯐꯪꯍꯟꯅꯕ ꯀꯣꯜꯗ ꯆꯦꯟ ꯏꯟꯐꯁꯇꯛꯆꯔ ꯐꯒꯠꯍꯟ
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 903/1000 [13:04<01:26,  1.12it/s]

[903/1000]
EN: A medical research institute in India studied long-term effects of COVID-19 infections.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯃꯦꯗꯤꯀꯦꯜ ꯔꯤꯁꯔꯆ ꯏꯟꯁꯇꯤꯇꯇ ꯑꯃꯅ ꯀꯣꯋꯤꯗ-19 ꯏꯟꯐꯦꯛꯁꯟꯁꯤꯡꯒꯤ ꯂꯣꯡ-ꯇꯔꯃ ꯏꯐꯦꯛꯠꯁꯤꯡ ꯇꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 904/1000 [13:05<01:23,  1.15it/s]

[904/1000]
EN: The government strengthened referral systems between primary and tertiary healthcare centers.
MNI_MTEI: ꯁꯔꯀꯥꯔꯅꯥꯃꯤꯔꯤ ꯑꯃꯁꯨꯡ ꯇꯔꯁꯤꯌꯔꯤ ꯍꯦꯜꯊꯦꯌꯔ ꯁꯦꯟꯇꯔꯁꯤꯡꯒꯤ ꯃꯔꯛꯇ ꯔꯤꯐꯔꯦꯜ ꯁꯤꯁꯇꯦꯝꯁꯤꯡ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 905/1000 [13:05<01:17,  1.23it/s]

[905/1000]
EN: Health workers received additional training to improve immunization coverage.
MNI_MTEI: ꯏꯃꯨꯅꯥꯏꯖꯦꯁꯟ ꯀꯚꯔꯦꯖ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯍꯦꯜꯊ ꯋꯥꯔꯀꯔꯁꯤꯡꯅꯥ ꯑꯍꯦꯟꯕꯅꯤꯡ ꯐꯪꯈꯤ ꯫
--------------------------------------------------

Translating:  91%|████████████████████████▍  | 906/1000 [13:06<01:12,  1.30it/s]

[906/1000]
EN: India expanded newborn care units to reduce infant mortality rates.
MNI_MTEI: ꯑꯉꯥꯡ ꯁꯤꯕꯒꯤ ꯆꯥꯡ ꯍꯟꯊꯍꯟꯅꯕ ꯚꯥꯔꯠꯅ ꯅꯕꯥꯟꯗ ꯀꯦꯌꯔ ꯌꯨꯅꯤꯇꯁꯤꯡ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  91%|████████████████████████▍  | 907/1000 [13:07<01:12,  1.29it/s]

[907/1000]
EN: The Ministry of Health collaborated with states to improve sanitation and hygiene practices.
MNI_MTEI: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥ ꯁꯦꯅꯦꯇꯦꯁꯟ ꯑꯃꯁꯨꯡ ꯍꯥꯏꯖꯦꯟꯦꯛꯇꯤꯁ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯔꯥꯖꯁꯤꯡꯒ ꯄꯨꯟꯅ ꯊꯕꯛ ꯇꯧ
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 908/1000 [13:07<01:09,  1.32it/s]

[908/1000]
EN: Indian hospitals increased investment in critical care facilities.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯅꯥꯇꯤꯀꯦꯜ ꯀꯦꯌꯔ ꯐꯦꯁꯤꯂꯤꯇꯤꯗꯥ ꯏꯟꯚꯦꯁꯇꯃꯦꯟꯠ ꯍꯦꯟꯒꯠꯍꯟ
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 909/1000 [13:08<01:12,  1.26it/s]

[909/1000]
EN: A health awareness campaign encouraged working professionals to undergo regular health screenings.
MNI_MTEI: ꯍꯦꯜꯊ ꯑꯦꯚꯦꯌꯔꯅꯦꯁ ꯀꯦꯝꯄꯦꯅ ꯑꯃꯅ ꯊꯕꯛ ꯇꯧꯔꯤꯕꯐꯦꯁꯅꯦꯜꯁꯤꯡꯕꯨ ꯔꯦꯒꯨꯂꯔ ꯍꯦꯂꯊꯅꯤꯡ ꯇꯧꯅꯕ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯂꯤ ꯫
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 910/1000 [13:09<01:09,  1.30it/s]

[910/1000]
EN: The government introduced reforms to regulate private healthcare pricing.
MNI_MTEI: ꯁꯔꯀꯥꯔꯅꯥꯚꯥꯏꯇ ꯍꯦꯜꯊꯦꯌꯔꯥꯏꯁꯤꯡ ꯔꯦꯒꯨꯂꯦꯇ ꯇꯧꯅꯕꯒꯤꯗꯃꯛ ꯔꯤꯐꯣꯔꯝꯁꯤꯡ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 911/1000 [13:10<01:09,  1.28it/s]

[911/1000]
EN: India enhanced its disease reporting systems to improve outbreak preparedness.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯃꯁꯤꯒꯤ ꯗꯤꯖꯤꯖ ꯔꯤꯄꯣꯔꯇꯤꯡ ꯁꯤꯁꯇꯦꯝꯁꯤꯡ ꯑꯁꯤ ꯂꯥꯏꯆꯠ ꯊꯣꯛꯄꯒꯤ ꯁꯦꯝ-ꯁꯥꯕꯒꯤ ꯐꯤꯕꯝ ꯐꯒꯠꯍꯟꯅꯕ ꯍꯦꯟꯒꯠꯍꯟ
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 912/1000 [13:11<01:11,  1.24it/s]

[912/1000]
EN: Health experts recommended increased funding for mental health research in India.
MNI_MTEI: ꯍꯦꯜꯊ ꯑꯦꯛꯁꯄꯥꯔꯇꯁꯤꯡꯅ ꯚꯥꯔꯠꯇ ꯃꯦꯟꯇꯥꯜ ꯍꯦꯜꯊ ꯔꯤꯁꯔꯆꯀꯤꯗꯃꯛ ꯁꯦꯜ ꯊꯥꯗꯕ ꯍꯦꯟꯒꯠꯍꯟꯕꯥ ꯔꯤꯀꯃꯦꯟꯗ ꯇꯧ
--------------------------------------------------

Translating:  91%|████████████████████████▋  | 913/1000 [13:11<01:10,  1.23it/s]

[913/1000]
EN: The National Health Authority reviewed feedback to improve beneficiary services.
MNI_MTEI: ꯅꯦꯁꯅꯦꯜ ꯍꯦꯜꯊ ꯑꯣꯊꯣꯔꯤꯇꯤꯅꯥ ꯕꯦꯅꯤꯐꯤꯁꯔꯤ ꯁꯔꯕꯤꯁ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯐꯤꯗꯕꯦꯛ ꯔꯤꯚ ꯇꯧ
--------------------------------------------------

Translating:  91%|████████████████████████▋  | 914/1000 [13:12<01:12,  1.19it/s]

[914/1000]
EN: India strengthened disaster preparedness in hospitals for medical emergencies.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯃꯦꯗꯤꯀꯦꯜ ꯏꯃꯔꯖꯦꯟꯁꯤꯁꯤꯡꯒꯤꯗꯃꯛ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯗ ꯗꯤꯖꯥꯁꯇ ꯔꯦꯄꯔꯦꯗꯤꯑꯦꯁꯟꯁꯤꯡ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  92%|████████████████████████▋  | 915/1000 [13:13<01:06,  1.27it/s]

[915/1000]
EN: A state government launched a nutrition program for school children.
MNI_MTEI: ꯇ ꯒꯚꯔꯃꯦꯟꯇ ꯑꯃꯅꯜꯒꯤ ꯑꯉꯥꯡꯁꯤꯡꯒꯤꯗꯃꯛ ꯅꯦꯁꯟꯒꯔꯥꯝ ꯑꯃ ꯍꯧ
--------------------------------------------------

Translating:  92%|████████████████████████▋  | 916/1000 [13:14<01:08,  1.22it/s]

[916/1000]
EN: The Health Ministry emphasized community participation in strengthening public healthcare systems.
MNI_MTEI: ꯍꯦꯜꯊ ꯃꯟꯇꯅꯥ ꯃꯤꯌꯥꯝꯒꯤ ꯍꯦꯜꯊꯦꯌꯔ ꯁꯤꯁꯇꯦꯝꯁꯤꯡ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯕꯗꯥ ꯀꯝꯃꯅꯤꯇꯤ ꯁꯔꯨꯛ ꯌꯥꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 917/1000 [13:15<01:13,  1.13it/s]

[917/1000]
EN: The Union Budget 2026 increased the healthcare allocation to 1,06,530 crore rupees for the Ministry of Health and Family Welfare.
MNI_MTEI: ꯌꯨꯅꯤꯌꯟ ꯕꯖꯦꯇ ꯗꯥ ꯍꯛꯁꯦꯜ ꯑꯃꯁꯨꯡ ꯏꯃꯨꯡ-ꯃꯄꯨ ꯆꯥꯎꯈꯠꯍꯟꯅꯕ ꯃꯟꯇꯒꯤꯗꯃꯛ ꯍꯛꯊꯦꯡꯅꯅ ꯁꯦꯜ ꯊꯥꯗꯕ ꯑꯁꯤ ꯂꯨꯄꯥ ꯀꯔꯣꯔ 1,06,530 ꯗꯥ ꯍꯦꯟꯒꯠꯍꯟ
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 918/1000 [13:16<01:14,  1.10it/s]

[918/1000]
EN: Finance Minister Nirmala Sitharaman announced a 10 percent hike in the health budget compared to the previous fiscal year.
MNI_MTEI: ꯐꯥꯏꯅꯥꯟꯁ ꯃꯟꯇ ꯅꯤꯔꯃꯂꯥ ꯁꯤꯔꯇꯥꯃꯟꯅꯥ ꯍꯧꯈꯤꯕ ꯁꯦꯟꯐꯝꯒꯤ ꯆꯍꯤꯒꯥ ꯆꯥꯡꯗꯝꯅꯕꯗ ꯍꯦꯜꯊ ꯕꯖꯦꯠꯇꯥ ꯆꯥꯗ ꯍꯦꯟꯒꯠꯍꯟꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 919/1000 [13:17<01:14,  1.09it/s]

[919/1000]
EN: The Government of India launched the Biopharma SHAKTI initiative with an outlay of 10,000 crore rupees over five years.
MNI_MTEI: ꯚꯥꯔꯠ ꯁꯔꯀꯥꯔꯅꯥ ꯆꯍꯤ ꯃꯉꯥꯒꯤ ꯃꯅꯨꯡꯗ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯒꯤ ꯁꯦꯜ ꯊꯥꯗꯕꯒ ꯂꯣꯏꯅꯅꯥ ꯕꯤꯑꯣꯐꯥꯔꯃꯥ ꯁꯛꯇꯤ ꯏꯅꯤꯁꯤꯌꯦꯇꯤꯕ ꯍꯧ
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 920/1000 [13:18<01:18,  1.02it/s]

[920/1000]
EN: The Biopharma SHAKTI scheme aims to strengthen the domestic production of biologics and biosimilars in India.
MNI_MTEI: ꯕꯥꯏꯑꯣꯐꯥꯔꯃꯥ ꯁꯛꯇꯤꯀꯤꯝ ꯑꯁꯤꯅ ꯚꯥꯔꯠꯇꯥ ꯕꯣꯂꯣꯖꯤꯛꯁ ꯑꯃꯁꯨꯡ ꯕꯥꯏꯌꯣꯁꯤꯃꯤꯂꯔꯁꯤꯡꯒꯤ ꯗꯣꯃꯦꯁꯇꯤꯛꯗꯛꯁꯟ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯕꯥ ꯄꯥꯟꯗꯝ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 921/1000 [13:19<01:18,  1.01it/s]

[921/1000]
EN: The Ministry of Health will support states in establishing five new regional medical hubs through private-sector partnerships.
MNI_MTEI: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥꯥꯏꯕꯦꯠ-ꯁꯦꯛꯇꯔ ꯄꯔꯅꯥꯇꯔꯁꯤꯞꯀꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯑꯅꯧꯕ ꯔꯤꯖꯅꯦꯜ ꯃꯦꯗꯤꯀꯦꯜ ꯍꯕ ꯃꯉꯥ ꯂꯤꯡꯈꯠꯄꯗ ꯔꯥꯖꯁꯤꯡꯕꯨ ꯃꯇꯦꯡ ꯄꯥꯡꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 922/1000 [13:20<01:20,  1.03s/it]

[922/1000]
EN: These five regional medical hubs will combine medical services, educational facilities, and research centers under one roof.
MNI_MTEI: ꯃꯁꯤꯒꯤ ꯔꯤꯖꯅꯦꯜ ꯃꯦꯗꯤꯀꯦꯜ ꯍꯕ ꯃꯉꯥ ꯑꯁꯤꯅ ꯍꯤꯗꯥꯛ-ꯃꯊꯛꯀꯤ ꯁꯔꯕꯤꯁꯁꯤꯡ, ꯑꯦꯖꯨꯀꯦꯁꯟ ꯐꯦꯁꯤꯂꯤꯇꯤꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯔꯤꯁꯔꯆ ꯁꯦꯟꯇꯔꯁꯤꯡ ꯑꯁꯤ ꯌꯨꯝꯕꯤ ꯑꯃꯒꯤ ꯃꯈꯥꯗ ꯄꯨꯟꯁꯤꯜꯍꯟꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 923/1000 [13:21<01:17,  1.01s/it]

[923/1000]
EN: The Union Budget 2026 proposed the establishment of NIMHANS 2.0 in North India to address mental health needs.
MNI_MTEI: ꯌꯨꯅꯤꯌꯟ ꯕꯖꯦꯇ 2026ꯅꯥ ꯑꯋꯥꯡ ꯚꯥꯔꯠꯇ ꯅꯤꯝꯍꯥꯟꯁ ꯂꯤꯡꯈꯠꯄꯥ ꯑꯁꯤ ꯃꯦꯟꯇꯥꯜ ꯍꯦꯜꯊꯀꯤ ꯃꯊꯧ ꯇꯥꯕꯁꯤꯡ ꯊꯦꯡꯅꯅꯕ ꯋꯥꯐꯝ ꯊꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 924/1000 [13:22<01:18,  1.04s/it]

[924/1000]
EN: The Government plans to upgrade the National Mental Health Institutes in Ranchi and Tezpur into regional apex institutions.
MNI_MTEI: ꯁꯔꯀꯥꯔꯅꯥ ꯔꯥꯟꯆꯤ ꯑꯃꯁꯨꯡ ꯇꯦꯖꯄꯨꯔꯗꯥ ꯂꯩꯕ ꯅꯦꯁꯅꯦꯜ ꯃꯦꯟꯇꯦꯜ ꯍꯦꯜꯊ ꯏꯟꯁꯇꯤꯇꯇꯨꯁꯤꯡꯕꯨ ꯔꯤꯖꯅꯦꯜ ꯑꯦꯄꯤꯛ ꯏꯟꯁꯇꯤꯇ ꯭ ꯌꯨꯁꯟꯁꯤꯡ ꯑꯣꯏꯍꯟꯅꯕ ꯊꯧꯔꯥꯡ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 925/1000 [13:23<01:14,  1.01it/s]

[925/1000]
EN: The Ministry of Health allocated 3,477 crore rupees to the National AIDS and STD Control Programme.
MNI_MTEI: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥ ꯅꯦꯁꯅꯦꯜ ꯑꯦꯗꯁ ꯑꯃꯁꯨꯡ ꯑꯦꯁ.ꯇꯤ.ꯗꯤ. ꯀꯟꯇꯣꯜꯒꯔꯝꯗꯥ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯊꯥꯖꯤꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  93%|█████████████████████████  | 926/1000 [13:24<01:14,  1.00s/it]

[926/1000]
EN: The Union Budget 2026 provided a full customs duty exemption on 17 essential cancer-related drugs.
MNI_MTEI: ꯌꯨꯅꯤꯌꯟ ꯕꯖꯦꯇ 2026ꯅꯥ ꯀꯦꯟꯁꯔꯒꯥ ꯃꯔꯤ ꯂꯩꯅꯕ ꯇꯉꯥꯏꯐꯗꯕ ꯗꯒ 17ꯗꯥ ꯃꯄꯨꯡꯐꯥꯅ ꯀꯁꯇꯝꯁ ꯗꯌꯨꯇꯤ ꯊꯥꯗꯣꯛꯄꯥ ꯑꯃ ꯄꯤ
--------------------------------------------------

Translating:  93%|█████████████████████████  | 927/1000 [13:25<01:10,  1.04it/s]

[927/1000]
EN: Seven additional rare diseases were added to the list for easier personal import of life-saving medicines.
MNI_MTEI: ꯂꯥꯏꯐ-ꯁꯦꯚꯤꯡ ꯃꯦꯗꯤꯁꯤꯟꯁꯤꯡ ꯂꯅꯥꯏꯗꯥ ꯄꯨꯁꯤꯜꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯂꯤꯁꯠ ꯑꯁꯤꯗ ꯑꯍꯦꯟꯕ ꯇꯥꯡꯕꯥ ꯂꯥꯏꯅꯥ 7 ꯍꯥꯞꯆꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  93%|█████████████████████████  | 928/1000 [13:26<01:09,  1.03it/s]

[928/1000]
EN: The Government announced a 50 percent expansion in emergency and trauma care capacity at district hospitals.
MNI_MTEI: ꯁꯔꯀꯥꯔꯅꯥ ꯗꯤꯁꯇꯛꯇ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯗ ꯏꯃꯔꯖꯦꯟꯁꯤ ꯑꯃꯁꯨꯡ ꯇꯃꯥ ꯀꯦꯌꯔ ꯀꯦꯄꯦꯁꯤꯇꯤ ꯆꯥꯗ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯒꯅꯤ ꯍꯥꯏꯅ ꯂꯥꯎꯊꯣꯛ
--------------------------------------------------

Translating:  93%|█████████████████████████  | 929/1000 [13:27<01:09,  1.02it/s]

[929/1000]
EN: The Ministry of Health intends to establish dedicated emergency and trauma care centers in every district hospital.
MNI_MTEI: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥ ꯗꯤꯁꯇꯛꯇ ꯍꯣꯁꯄꯤꯇꯥꯜ ꯈꯨꯗꯤꯡꯃꯛꯇ ꯗꯦꯗꯤꯀꯦꯇꯦꯗ ꯏꯃꯔꯖꯦꯟꯁꯤ ꯑꯃꯁꯨꯡ ꯇꯃꯥ ꯀꯦꯌꯔ ꯁꯦꯟꯇꯔꯁꯤꯡ ꯂꯤꯡꯈꯠꯄꯥ ꯄꯥꯝꯃꯤ ꯫
--------------------------------------------------

Translating:  93%|█████████████████████████  | 930/1000 [13:28<01:09,  1.01it/s]

[930/1000]
EN: The Pradhan Mantri Jan Arogya Yojana received an increased allocation of 9,500 crore rupees to expand coverage.
MNI_MTEI: ꯙꯥꯟ ꯃꯟꯇ ꯖꯅ ꯑꯔꯣꯒ ꯌꯣꯖꯅꯥꯅꯥ ꯀꯚꯔꯦꯖ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯍꯦꯟꯒꯠꯄꯥ ꯑꯦꯂꯣꯀꯦꯁꯟ ꯑꯃ ꯐꯪ
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 931/1000 [13:29<01:08,  1.01it/s]

[931/1000]
EN: The National Health Mission was allocated 39,390 crore rupees to enhance primary healthcare delivery across states.
MNI_MTEI: ꯅꯦꯁꯅꯦꯜ ꯍꯦꯜꯊ ꯃꯤꯁꯟ ꯑꯁꯤ ꯔꯥꯖ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥꯥꯏꯃꯔꯤ ꯍꯦꯜꯊꯦꯌꯔ ꯗꯤꯂꯤꯚꯔꯤ ꯍꯦꯟꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯂꯨꯄꯥ ꯀꯔꯣꯔ 39,390 ꯄꯤ
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 932/1000 [13:30<01:03,  1.07it/s]

[932/1000]
EN: The Government proposed a plan to add 100,000 allied health professionals over the next five years.
MNI_MTEI: ꯁꯔꯀꯥꯔꯅꯥ ꯃꯊꯪꯒꯤ ꯆꯍꯤ ꯃꯉꯥꯒꯤ ꯃꯅꯨꯡꯗ ꯑꯦꯂꯥꯏꯗ ꯍꯦꯜꯊꯐꯦꯐꯦꯁꯅꯦꯜ 100,000 ꯍꯥꯞꯆꯤꯟꯅꯕ ꯊꯧꯔꯥꯡ ꯑꯃ ꯄꯨꯊꯣꯛ
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 933/1000 [13:31<01:04,  1.03it/s]

[933/1000]
EN: The Ministry of Health will upgrade existing institutions for allied health professionals to improve training standards.
MNI_MTEI: ꯍꯛꯁꯦꯜ ꯃꯟꯇꯅꯥ ꯍꯧꯖꯤꯛ ꯂꯩꯔꯤꯕ ꯏꯟꯁꯇꯤꯇꯁꯟꯁꯤꯡ ꯑꯁꯤ ꯑꯦꯂꯥꯏꯗ ꯍꯦꯜꯊꯐꯦꯁꯅꯦꯜꯁꯤꯡꯒꯤꯗꯃꯛꯅꯤꯡꯦꯟꯗꯗꯔꯁ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯑꯒꯗ ꯇꯧꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 934/1000 [13:32<01:00,  1.09it/s]

[934/1000]
EN: The Union Budget 2026 earmarked 4,821 crore rupees specifically for the Department of Health Research.
MNI_MTEI: ꯌꯨꯅꯤꯌꯟ ꯕꯖꯦꯇ 2026 ꯗꯥ ꯍꯛꯁꯦꯜ ꯔꯤꯁꯔꯆ ꯗꯤꯄꯥꯇꯃꯦꯟꯇꯒꯤꯗꯃꯛ ꯃꯔꯨꯑꯣꯏꯅ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯊꯝ
--------------------------------------------------

Translating:  94%|█████████████████████████▏ | 935/1000 [13:33<00:59,  1.10it/s]

[935/1000]
EN: Finance Minister Nirmala Sitharaman proposed the creation of three new All India Institutes of Ayurveda.
MNI_MTEI: ꯐꯥꯏꯅꯥꯟꯁ ꯃꯟꯇ ꯅꯤꯔꯃꯂꯥ ꯁꯤꯔꯇꯥꯃꯟꯅꯥ ꯑꯥꯌꯨꯔꯕꯦꯗꯥꯒꯤ ꯑꯅꯧꯕ ꯑꯣꯜ ꯏꯟꯗꯤꯌꯥ ꯏꯟꯁꯇꯤꯇꯇ ꯑꯍꯨꯝ ꯁꯦꯝꯕꯒꯤ ꯋꯥꯐꯝ ꯊꯝꯈꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 936/1000 [13:34<01:00,  1.07it/s]

[936/1000]
EN: The Government plans to train 1.5 lakh caregivers in allied skills such as geriatric care and yoga.
MNI_MTEI: ꯒꯕꯔꯃꯦꯟꯇꯅꯥ ꯖꯦꯔꯤꯌꯥꯇ ꯀꯦꯌꯔ ꯑꯃꯁꯨꯡ ꯌꯣꯒꯥꯒꯨꯝꯕ ꯑꯦꯂꯥꯏꯗꯀꯤꯜꯁꯤꯡꯗ ꯀꯦꯌꯥꯔꯒꯤꯚꯔ ꯂꯥꯈ ꯇꯅꯤꯡ ꯄꯤꯅꯕ ꯊꯧꯔꯥꯡ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 937/1000 [13:35<01:00,  1.05it/s]

[937/1000]
EN: The Ayushman Bharat Digital Mission received 350 crore rupees to improve digital health record interoperability.
MNI_MTEI: ꯗꯤꯖꯤꯇꯦꯜ ꯍꯦꯜꯊ ꯔꯦꯀꯣꯔ ꯏꯟꯇꯔꯑꯣꯄꯔꯦꯕꯤꯂꯤꯇꯤ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯑꯥꯌꯨꯁꯃꯟ ꯚꯥꯔꯠ ꯗꯤꯖꯇꯤꯇꯦꯜ ꯃꯤꯁꯟꯅꯥ ꯂꯨꯄꯥ ꯀꯔꯣꯔ 350 ꯐꯪ
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 938/1000 [13:36<01:05,  1.05s/it]

[938/1000]
EN: The Ministry of Health aims to reduce import dependence by supporting the domestic manufacturing of high-value biopharmaceuticals.
MNI_MTEI: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥ ꯍꯥꯏ-ꯚꯂꯨ ꯕꯌꯣ ꯐꯥꯔꯃꯥꯁꯤꯌꯨꯇꯤꯀꯦꯜꯁꯤꯡꯒꯤ ꯗꯣꯃꯦꯁꯇꯤꯛ ꯃꯦꯅꯛꯄꯨꯆꯔꯗ ꯃꯇꯦꯡ ꯄꯥꯡꯗꯨꯅ ꯏꯝꯄꯣꯔꯇ ꯗꯤꯄꯦꯟꯗꯦꯟꯁ ꯍꯟꯊꯍꯟꯅꯕ ꯄꯥꯟꯗꯝ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 939/1000 [13:37<01:07,  1.10s/it]

[939/1000]
EN: The Union Budget 2026 focus shifted from a curative model to a prevention-first and holistic wellness approach.
MNI_MTEI: ꯌꯨꯅꯤꯌꯟ ꯕꯖꯦꯇ 2026 ꯒꯤ ꯃꯤꯠꯌꯦꯡ ꯑꯁꯤ ꯀ ꯭ ꯌꯨꯔꯦꯇꯤꯕ ꯃꯣꯗꯦꯜ ꯑꯃꯗꯒꯤꯚꯤꯖꯟ-ꯐꯔꯁꯠ ꯑꯃꯁꯨꯡ ꯍꯣꯂꯤꯁꯇꯤꯛ ꯋꯦꯜꯅꯦꯁ ꯑꯦꯞꯔꯣꯆ ꯑꯃꯗ ꯍꯣꯡꯈꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 940/1000 [13:38<01:06,  1.10s/it]

[940/1000]
EN: The Government will establish 1,000 accredited clinical trial sites to position India as a global research destination.
MNI_MTEI: ꯒꯚꯔꯃꯦꯟꯇꯅꯥ ꯚꯥꯔꯠꯄꯨꯋꯦꯜ ꯔꯤꯁꯔꯆ ꯗꯦꯁꯇꯤꯅꯦꯁꯟ ꯑꯃ ꯑꯣꯏꯍꯟꯅꯕ ꯑꯦꯀꯗꯤꯇꯦꯗ ꯀꯂꯤꯅꯤꯀꯦꯜꯥꯏꯂ ꯁꯥꯏꯇ 1000 ꯂꯤꯡꯈꯠꯀꯅꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 941/1000 [13:39<01:08,  1.17s/it]

[941/1000]
EN: The Central Drugs Standard Control Organisation will receive more specialized personnel to improve regulatory efficiency.
MNI_MTEI: ꯁꯦꯟꯇꯜ ꯗꯒꯁꯦꯟꯗꯗꯔꯗ ꯀꯟꯇꯣꯜ ꯑꯣꯔꯒꯥꯅꯥꯏꯖꯦꯁꯟꯅꯥ ꯔꯦꯒꯨꯂꯦꯇꯔꯤ ꯑꯦꯐꯤꯁꯤꯑꯦꯟꯁꯤ ꯐꯒꯠꯍꯟꯅꯕꯒꯤꯗꯃꯛ ꯍꯦꯟꯅ ꯁꯄꯁꯤꯌꯦꯂꯤꯁꯇ ꯄꯔꯁꯣꯅꯦꯜ ꯐꯪꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 942/1000 [13:41<01:06,  1.16s/it]

[942/1000]
EN: Artificial Intelligence is now being used by Indian radiologists to detect early signs of lung cancer from medical images.
MNI_MTEI: ꯑꯔꯇꯤꯐꯤꯁꯦꯜ ꯏꯟꯇꯤꯂꯤꯖꯦꯟꯁ ꯑꯁꯤ ꯍꯧꯖꯤꯛ ꯚꯥꯔꯠꯀꯤ ꯔꯦꯗꯤꯑꯣꯂꯣꯖꯤꯁꯇꯁꯤꯡꯅꯥ ꯃꯦꯗꯤꯀꯦꯜ ꯏꯃꯤꯖꯁꯤꯡꯗꯒꯤ ꯂꯡꯒ ꯀꯦꯟꯁꯔꯒꯤ ꯑꯍꯥꯟꯕꯥ ꯈꯨꯗꯝꯁꯤꯡ ꯈꯪꯗꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯁꯤꯖꯤꯟꯅꯔꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 943/1000 [13:42<01:09,  1.22s/it]

[943/1000]
EN: Qure.ai implemented AI-driven imaging solutions to facilitate faster diagnosis of strokes in rural Indian hospitals.
MNI_MTEI: ꯀ ꯭ ꯌꯨꯔꯦ.ꯑꯦꯏꯅꯥ ꯈꯨꯡꯒꯪꯒꯤ ꯚꯥꯔꯠꯀꯤ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯗꯣꯛꯁꯤꯡ ꯊꯨꯅ ꯂꯥꯏꯑꯣꯡ ꯈꯪꯗꯣꯛꯅꯕꯒꯤ ꯈꯨꯗꯣꯡꯆꯥꯕꯥ ꯄꯤꯅꯕ ꯑꯦꯑꯏ-ꯗꯚꯟ ꯏꯃꯦꯖꯤꯡ ꯁꯣꯂꯨꯁꯟꯁꯤꯡ ꯆꯠꯅꯍꯟꯈꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 944/1000 [13:43<01:08,  1.23s/it]

[944/1000]
EN: Indian healthcare providers are adopting "Actionable AI" to provide predictive health roadmaps instead of simple lab reports.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯍꯦꯜꯊꯦꯌꯔꯚꯥꯏꯗꯔꯁꯤꯡꯅ ꯁꯤꯝꯄꯦꯜ ꯂꯦꯕ ꯔꯤꯄꯣꯔꯠꯁꯤꯡꯒꯤ ꯃꯍꯨꯠꯇꯗꯤꯇꯤꯕ ꯍꯦꯜꯊ ꯔꯣꯗꯃꯦꯄꯁꯤꯡ ꯄꯤꯅꯕ "ꯑꯦꯛꯁꯟꯑꯦꯕꯜ ꯑꯦꯑꯏ ꯂꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  94%|█████████████████████████▌ | 945/1000 [13:44<01:06,  1.20s/it]

[945/1000]
EN: The use of wearables in India is evolving from basic fitness tracking to clinical-grade monitoring of heart rhythm.
MNI_MTEI: ꯚꯥꯔꯠꯇꯥ ꯌꯦꯔꯦꯑꯦꯕꯜꯁꯤꯡ ꯁꯤꯖꯤꯟꯅꯕꯁꯤ ꯕꯦꯁꯤꯛ ꯐꯤꯇꯅꯤꯁ ꯇꯀꯤꯡꯗꯒꯤ ꯍꯔꯇ ꯔꯤꯊꯝꯒꯤ ꯀꯂꯤꯅꯤꯀꯦꯜ-ꯒꯗ ꯃꯣꯅꯤꯇꯦꯔꯤꯡ ꯐꯥꯎꯕ ꯆꯥꯎꯈꯠꯂꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 946/1000 [13:46<01:07,  1.25s/it]

[946/1000]
EN: Medical technology startups in India are developing microfluidic devices that conduct complex tests on a single drop of blood.
MNI_MTEI: ꯚꯥꯔꯠꯇꯥ ꯃꯦꯗꯤꯀꯦꯜ ꯇꯦꯛꯅꯣꯂꯣꯖꯤ ꯁꯇꯥꯔꯇꯑꯞꯁꯤꯡ ꯑꯁꯤꯅ ꯃꯥꯏꯀꯐꯂꯨꯏꯗꯤꯛ ꯗꯤꯚꯥꯏꯁꯁꯤꯡ ꯁꯦꯝꯒꯠꯂꯤ ꯃꯗꯨꯗ ꯏꯒꯤ ꯁꯤꯡꯒꯜ ꯗꯄ ꯑꯃꯗ ꯀꯝꯄꯂ ꯭ ꯁ ꯇꯦꯁꯇꯁꯤꯡ ꯄꯥꯡꯊꯣꯛꯏ ꯫
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 947/1000 [13:47<01:02,  1.17s/it]

[947/1000]
EN: The Indian MedTech sector is projected to reach a market value of 50 billion dollars by the end of 2026.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯃꯦꯗꯇꯦꯛ ꯁꯦꯛꯇꯔ ꯑꯁꯤ ꯏꯪꯁꯣꯛ ꯂꯣꯏꯔꯛꯄꯗꯥ ꯗꯣꯂꯔ ꯕꯤꯂꯤꯌꯟꯒꯤ ꯃꯥꯔꯀꯦꯠ ꯚꯦꯜꯌꯨ ꯌꯧꯔꯛꯀꯅꯤ ꯍꯥꯏꯅ ꯄꯥꯅꯔꯤ ꯫
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 948/1000 [13:48<00:58,  1.13s/it]

[948/1000]
EN: Hospitals in Tier 2 cities are using predictive analytics to optimize patient flow and reduce waiting times.
MNI_MTEI: ꯇꯤꯌꯔ ꯁꯍꯔꯁꯤꯡꯒꯤ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡ ꯑꯁꯤꯅ ꯑꯅꯥꯕꯁꯤꯡꯒꯤ ꯏꯊꯣꯛꯑꯁꯥ ꯍꯦꯟꯒꯠꯍꯟꯅꯕ ꯑꯃꯁꯨꯡ ꯉꯥꯏꯕꯒꯤ ꯃꯇꯝ ꯍꯟꯊꯍꯟꯅꯕꯗꯤꯇꯤꯕ ꯑꯦꯅꯥꯂꯤꯇꯤꯛꯁ ꯁꯤꯖꯤꯟꯅ
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 949/1000 [13:49<00:57,  1.12s/it]

[949/1000]
EN: Telemedicine services are expanding in remote regions to connect rural patients with specialists in metropolitan cities.
MNI_MTEI: ꯇꯦꯂꯤꯃꯦꯗꯤꯁꯤꯟ ꯁꯔꯕꯤꯁꯁꯤꯡ ꯑꯁꯤ ꯃꯦꯇꯄꯣꯂꯤꯇꯥꯟ ꯁꯤꯇꯤꯁꯤꯡꯒꯤ ꯁꯄꯁꯤꯑꯦꯂꯤꯁꯇꯁꯤꯡꯒ ꯈꯨꯡꯒꯪꯒꯤ ꯑꯅꯥꯕꯁꯤꯡ ꯁꯝꯅꯕ ꯂꯥꯞꯊꯣꯛꯂꯕ ꯂꯝꯗꯝꯁꯤꯡꯗ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 950/1000 [13:50<00:57,  1.15s/it]

[950/1000]
EN: The Ayushman Bharat Health Account (ABHA) system allows patients to share digital health records securely with doctors.
MNI_MTEI: ꯑꯥꯌꯨꯁꯃꯟ ꯚꯥꯔꯠ ꯍꯦꯜꯊ ꯑꯦꯀꯥꯎꯟꯇ (ꯑꯦꯕꯤꯑꯍꯑꯦ ) ꯁꯤꯁꯇꯦꯝ ꯑꯁꯤꯅ ꯑꯅꯥꯕꯥꯁꯤꯡꯕꯨ ꯗꯤꯖꯤꯇꯦꯜ ꯍꯦꯜꯊ ꯔꯦꯀꯣꯔꯗꯁꯤꯡ ꯗꯣꯛꯇꯔꯁꯤꯡꯒ ꯁꯣꯏꯗꯅ ꯁꯦꯌꯔ ꯇꯧꯕ ꯌꯥꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 951/1000 [13:51<00:56,  1.15s/it]

[951/1000]
EN: Robotic-assisted surgery is becoming more common in private Indian hospitals for complex urological procedures.
MNI_MTEI: ꯀꯝꯄꯂꯦꯛꯁ ꯌꯨꯔꯣꯂꯣꯖꯤꯀꯦꯜꯁꯤꯖꯨꯑꯣꯔꯁꯤꯡꯒꯤꯗꯃꯛꯇꯥꯏꯚꯦꯠ ꯏꯟꯗꯤꯌꯟ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯗ ꯔꯣꯕꯣꯇꯤꯛ-ꯑꯦꯁꯦꯁꯇꯦꯗ ꯁꯔꯖꯔꯤ ꯑꯁꯤ ꯍꯦꯟꯅ ꯇꯣꯏꯅ ꯊꯣꯛꯂꯛꯂꯤ ꯫
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 952/1000 [13:52<00:52,  1.10s/it]

[952/1000]
EN: Many Indian diagnostic labs are now using genomic testing as a primary triage tool for chronic diseases.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯗꯥꯏꯒꯅꯣꯁꯇꯤꯛ ꯂꯦꯕ ꯀꯌꯥꯅꯥ ꯍꯧꯖꯤꯛ ꯖꯤꯅꯣꯃꯤꯛ ꯇꯦꯁꯇꯤꯡ ꯑꯁꯤꯅꯤꯛ ꯗꯤꯖꯤꯖꯁꯤꯡꯒꯤꯥꯏꯔꯤꯌꯦꯖ ꯇꯨꯜ ꯑꯃꯥ ꯑꯣꯏꯅ ꯁꯤꯖꯤꯟꯅ
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 953/1000 [13:53<00:54,  1.17s/it]

[953/1000]
EN: Healthcare organizations are deploying AI agents to handle administrative tasks like insurance pre-authorizations and billing.
MNI_MTEI: ꯍꯦꯜꯊꯦꯌꯔ ꯑꯣꯔꯒꯥꯅꯥꯏꯖꯦꯁꯟꯁꯤꯡꯅ ꯏꯟꯁꯨꯔꯦꯟꯁ-ꯑꯣꯊꯔꯤꯖꯦꯁꯟ ꯑꯃꯁꯨꯡ ꯕꯤꯂꯤꯡꯒꯨꯝꯕ ꯑꯦꯗꯃꯤꯅꯤꯁꯇꯇꯤꯕ ꯇꯁꯀꯁꯤꯡ ꯁꯤꯟꯗꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯑꯦꯑꯏ ꯑꯦꯖꯦꯟꯇꯁꯤꯡ ꯗꯤꯄꯂꯥꯏ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  95%|█████████████████████████▊ | 954/1000 [13:55<00:52,  1.15s/it]

[954/1000]
EN: Smart sensors in Indian ICUs are reducing unplanned admissions by providing continuous real-time monitoring of vitals.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯑꯥꯏ ꯁꯤ ꯌꯨꯁꯤꯡꯗ ꯂꯩꯕꯃꯔꯇ ꯁꯦꯟꯁꯔꯁꯤꯡꯅ ꯚꯤꯇꯥꯜꯁꯤꯡꯒꯤ ꯃꯈꯥ ꯇꯥꯅ ꯔꯤꯌꯦꯜ-ꯇꯥꯏꯃ ꯃꯣꯅꯤꯇꯦꯔꯤꯡ ꯄꯤꯗꯨꯅ ꯑꯟꯄꯂꯥꯟꯗ ꯑꯦꯗꯃꯤꯁꯟꯁꯤꯡ ꯍꯟꯊꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 955/1000 [13:56<00:50,  1.13s/it]

[955/1000]
EN: The digital transformation of clinical trials in India is enabling remote patient monitoring through mobile devices.
MNI_MTEI: ꯚꯥꯔꯠꯇ ꯀꯂꯤꯅꯤꯀꯦꯜꯌꯦꯜꯁꯤꯡꯒꯤ ꯗꯤꯖꯤꯇꯦꯜ ꯇ ꯭ ꯔꯥꯟꯁꯐꯣꯔꯃꯦꯁꯟ ꯑꯁꯤꯅ ꯃꯣꯕꯥꯏꯜ ꯗꯤꯚꯥꯏꯁꯁꯤꯡꯒꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯔꯤꯃꯣꯠ ꯄꯦꯁꯤꯗꯦꯟꯇ ꯃꯣꯅꯤꯇꯦꯔꯤꯡ ꯇꯧꯕ ꯉꯝꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 956/1000 [13:57<00:52,  1.19s/it]

[956/1000]
EN: Indian pharmaceutical companies are integrating AI into their quality control systems to ensure paperless and compliant workflows.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯐꯥꯔꯃꯥꯁꯤꯌꯨꯇꯤꯀꯦꯜ ꯀꯝꯄꯅꯤꯁꯤꯡꯅ ꯑꯦꯑꯏꯕꯨ ꯃꯈꯣꯏꯒꯤ ꯀꯋꯥꯂꯤꯇꯤ ꯀꯟꯇꯣꯜ ꯁꯤꯁꯇꯦꯝꯁꯤꯡꯗ ꯄꯦꯄꯔ ꯂꯦꯁ ꯑꯃꯁꯨꯡ ꯀꯝꯄꯂꯥꯏꯟꯇ ꯋꯥꯔꯛꯐꯂꯣꯁꯤꯡ ꯁꯣꯏꯗꯅ ꯐꯪꯍꯟꯅꯕ ꯏꯟꯇꯤꯒꯦꯠ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 957/1000 [13:58<00:51,  1.20s/it]

[957/1000]
EN: Low-cost needle-free drug delivery technologies are gaining traction for vaccine administration in pediatric clinics.
MNI_MTEI: ꯄꯦꯗꯤꯌꯦꯇ ꯀꯂꯤꯅꯤꯛꯁꯤꯡꯗ ꯕꯦꯛꯁꯤꯟ ꯑꯦꯗꯃꯤꯅꯤꯁꯇꯦꯁꯟꯒꯤꯗꯃꯛ ꯃꯃꯜ ꯌꯥꯝꯗꯕ ꯅꯤꯂꯤ-ꯐ ꯗꯒ ꯗꯤꯂꯤꯚꯔꯤ ꯇꯦꯛꯅꯣꯂꯣꯖꯤꯁꯤꯡꯅ ꯄꯨꯛꯅꯤꯡ ꯆꯤꯡꯁꯤꯟꯅꯤꯡꯉꯥꯏ ꯑꯣꯏꯔꯦ ꯫
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 958/1000 [13:59<00:51,  1.22s/it]

[958/1000]
EN: Public health experts launched India's first Public Health Monitor to track real-time health outcomes across states.
MNI_MTEI: ꯄꯍꯦꯜꯊ ꯑꯦꯛꯁꯄꯥꯔꯇꯁꯤꯡꯅ ꯔꯥꯖ ꯈꯨꯗꯤꯡꯗꯥ ꯔꯤꯌꯦꯜ-ꯇꯥꯏꯃ ꯍꯦꯜꯊ ꯑꯣꯛꯇꯀꯝꯁꯤꯡ ꯇꯦꯛ ꯇꯧꯅꯕ ꯚꯥꯔꯠꯀꯤ ꯑꯍꯥꯟꯕꯥ ꯄꯕꯂꯍꯦꯂꯊ ꯃꯣꯅꯤꯇꯔ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 959/1000 [14:01<00:48,  1.17s/it]

[959/1000]
EN: Specialized medical tourism facilitation centers will be integrated into the new regional medical hubs.
MNI_MTEI: ꯑꯍꯥꯟꯕꯥ ꯔꯤꯖꯅꯦꯜ ꯃꯦꯗꯤꯀꯦꯜ ꯍꯕꯁꯤꯡ ꯑꯁꯤꯗꯁꯤꯑꯦꯂꯥꯏꯖ ꯇꯧꯔꯕꯥ ꯃꯦꯗꯗꯤꯀꯦꯜ ꯇꯨꯔꯤꯖꯝ ꯐꯦꯁꯤꯂꯤꯇꯦꯁꯟ ꯁꯦꯟꯇꯔꯁꯤꯡ ꯏꯟꯇꯤꯒꯦꯠ ꯇꯧꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 960/1000 [14:02<00:44,  1.11s/it]

[960/1000]
EN: Indian doctors are using hyper-personalized medicine to tailor treatments based on the genetic profile of individual patients.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯗꯣꯛꯇꯔꯁꯤꯡꯅ ꯑꯅꯥꯕꯁꯤꯡꯒꯤ ꯖꯤꯅꯦꯇꯤꯛꯐꯥꯏꯜꯗ ꯌꯨꯝꯐꯝ ꯑꯣꯏꯔꯒ ꯂꯥꯏꯌꯦꯡꯁꯤꯡ ꯁꯦꯝꯅꯕ ꯍꯥꯏꯄꯔ-ꯄꯔꯁꯅꯥꯂꯥꯏꯖ ꯃꯦꯗꯤꯁꯤꯟ ꯁꯤꯖꯤꯟꯅ
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 961/1000 [14:02<00:40,  1.03s/it]

[961/1000]
EN: The adoption of 5G technology is improving the speed and reliability of remote robotic surgeries in India.
MNI_MTEI: 5G ꯇꯦꯛꯅꯣꯂꯣꯖꯤ ꯁꯤꯖꯤꯟꯅꯕꯅꯥ ꯚꯥꯔꯠꯇ ꯔꯤꯃꯣꯠ ꯔꯣꯕꯣꯇꯤꯛ ꯁꯔꯖꯔꯤꯁꯤꯡꯒꯤꯗ ꯑꯃꯁꯨꯡ ꯔꯦꯂꯤꯑꯦꯕꯂꯤꯇꯤ ꯐꯒꯠꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 962/1000 [14:03<00:39,  1.04s/it]

[962/1000]
EN: 20 All India Institutes of Medical Sciences signed a memorandum to form a pan-India research consortium.
MNI_MTEI: ꯑꯣꯜ ꯏꯟꯗꯤꯌꯥ ꯏꯟꯁꯇꯤꯇ ꯭ ꯌꯨꯇ ꯑꯣꯐ ꯃꯦꯗꯤꯀꯦꯜ ꯁꯥꯏꯟꯁꯦꯁ 20ꯅꯥ ꯄꯥꯟ- ꯏꯟꯗꯤꯌꯥ ꯔꯤꯁꯔꯆ ꯀꯟꯁꯣꯔꯇꯤꯌꯝ ꯑꯃ ꯁꯦꯝꯅꯕꯒꯤꯗꯃꯛ ꯃꯦꯃꯣꯔꯦꯟꯗꯝ ꯑꯃꯗ ꯈꯨꯠꯌꯦꯛ ꯄꯤꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  96%|██████████████████████████ | 963/1000 [14:05<00:38,  1.05s/it]

[963/1000]
EN: The AIIMS research consortium will focus on multicentric clinical trials for low-cost cancer treatments.
MNI_MTEI: ꯑꯦꯑꯥꯏꯑꯏꯑꯦꯝꯁ ꯔꯤꯁꯔꯆ ꯀꯟꯁꯣꯔꯇꯤꯌꯝꯅꯥ ꯃꯃꯜ ꯌꯥꯝꯗꯕ ꯀꯦꯟꯁꯔ ꯂꯥꯏꯌꯦꯡꯒꯤꯗꯃꯛ ꯃꯜꯇꯤꯁꯦꯟꯇ ꯀꯂꯤꯅꯤꯀꯦꯜ ꯇꯌꯦꯜꯁꯤꯡꯗ ꯃꯤꯠꯌꯦꯡ ꯊꯝꯒꯅꯤ ꯫
--------------------------------------------------

Translating:  96%|██████████████████████████ | 964/1000 [14:06<00:37,  1.04s/it]

[964/1000]
EN: A medical student at the Dharwad Institute of Mental Health unfortunately committed suicide in early February.
MNI_MTEI: ꯙꯔꯋꯥꯗ ꯏꯟꯁꯇꯤꯇꯇ ꯑꯣꯐ ꯃꯦꯟꯇꯥꯜ ꯍꯦꯜꯊꯀꯤ ꯃꯦꯗꯤꯀꯦꯜꯒꯤ ꯃꯍꯩꯔꯣꯏ ꯑꯃꯅ ꯂꯥꯏꯔꯕꯅꯥ ꯐꯦꯕꯋꯥꯔꯤꯒꯤ ꯑꯉꯟꯕꯗꯥ ꯃꯁꯥ ꯃꯊꯟꯇ ꯍꯥꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  96%|██████████████████████████ | 965/1000 [14:07<00:35,  1.02s/it]

[965/1000]
EN: The Maharashtra University of Health Sciences revoked the affiliation of Sinhgad Dental College over regulatory violations.
MNI_MTEI: ꯃꯍꯥꯔꯥꯁꯇ ꯌꯨꯅꯤꯚꯔꯁꯤꯇꯤ ꯑꯣꯐ ꯍꯦꯜꯊ ꯁꯥꯏꯟꯁꯦꯁꯅ ꯁꯤꯟꯍꯒꯗ ꯗꯦꯟꯇꯦꯜ ꯀꯣꯂꯦꯖꯒꯤ ꯑꯦꯐꯤꯂꯤꯑꯦꯁꯟ ꯑꯗꯨ ꯔꯦꯒꯨꯂꯦꯇꯔꯤ ꯋꯥꯂꯥꯏꯟꯁꯤꯡꯒꯤ ꯃꯔꯝꯗꯥ ꯂꯧꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████ | 966/1000 [14:08<00:34,  1.02s/it]

[966/1000]
EN: A 40-year-old urologist suffered a cardiac arrest while speaking at an international conference in Indore.
MNI_MTEI: ꯏꯟꯗꯣꯔꯗ ꯄꯥꯡꯊꯣꯛꯂꯤꯕꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯀꯟꯐꯔꯦꯟꯁ ꯑꯃꯗ ꯋꯥ ꯍꯥꯏꯔꯤꯕꯥ ꯃꯇꯝꯗ ꯆꯍꯤ 40 ꯁꯨꯔꯕꯥ ꯌꯨꯔꯣꯂꯣꯖꯤꯁꯇ ꯑꯃꯥꯅ ꯀꯥꯔꯗꯤꯑꯦꯛ ꯑꯦꯔꯦꯁꯇ ꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████ | 967/1000 [14:09<00:33,  1.03s/it]

[967/1000]
EN: The District Consumer Commission in Kannur held a surgeon liable for negligence in a varicose vein treatment.
MNI_MTEI: ꯀꯟꯅꯨꯔꯗꯥ ꯂꯩꯕ ꯗꯤꯁꯇꯛꯇ ꯀꯟꯖꯨꯃꯔ ꯀꯃꯤꯁꯟꯅꯥ ꯚꯦꯔꯤꯀꯣꯖ ꯚꯤꯅ ꯇꯇꯤꯃꯦꯟꯇ ꯑꯃꯗ ꯆꯦꯛꯁꯤꯟꯗꯕꯒꯤꯗꯃꯛ ꯁꯔꯖꯟ ꯑꯃꯥ ꯂꯧ
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 968/1000 [14:10<00:34,  1.06s/it]

[968/1000]
EN: Two government doctors in Bhopal were sentenced to prison for securing medical seats with fake domicile certificates.
MNI_MTEI: ꯚꯣꯄꯥꯜꯗꯥ ꯂꯩꯕ ꯒꯚꯔꯃꯦꯟꯇ ꯗꯣꯛꯇꯔ ꯑꯅꯤꯕꯨ ꯑꯔꯥꯟꯕ ꯗꯣꯃꯤꯁꯥꯏꯂ ꯁꯔꯇꯤꯐꯤꯀꯦꯠꯁꯤꯡꯒ ꯂꯣꯏꯅꯅ ꯃꯦꯗꯤꯀꯦꯜ ꯁꯤꯇꯁꯤꯡ ꯐꯪꯍꯟꯕꯒꯤꯗꯃꯛ ꯖꯦꯜꯗ ꯊꯝ
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 969/1000 [14:11<00:33,  1.07s/it]

[969/1000]
EN: Authorities in Maharashtra are seeking action against a pathologist for signing lab reports without proper registration.
MNI_MTEI: ꯃꯍꯥꯔꯥꯁꯇꯗꯥ ꯂꯩꯕ ꯑꯣꯊꯣꯔꯤꯇꯤꯁꯤꯡꯅ ꯃꯇꯤꯛ ꯆꯥꯕ ꯔꯦꯖꯤꯁꯇꯦꯁꯟ ꯌꯥꯎꯗꯅ ꯂꯦꯕ ꯔꯤꯄꯣꯔꯇꯁꯤꯡ ꯈꯨꯠꯌꯦꯛ ꯄꯤꯁꯤꯟꯕꯒꯤꯗꯃꯛ ꯄꯦꯊꯣꯂꯣꯖꯤꯁꯇ ꯑꯃꯒꯤ ꯃꯥꯌꯣꯛꯇ ꯑꯦꯛꯁꯟ ꯊꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 970/1000 [14:12<00:34,  1.16s/it]

[970/1000]
EN: The Central Council for Research in Ayurvedic Sciences signed an agreement to digitize rare Ayurveda manuscripts.
MNI_MTEI: ꯁꯦꯟꯇꯜ ꯀꯥꯎꯟꯁꯜ ꯐꯣꯔ ꯔꯤꯁꯔꯆ ꯏꯟ ꯑꯥꯌꯨꯔꯕꯦꯗꯤꯛ ꯁꯥꯏꯟꯁꯦꯁꯅ ꯇꯥꯡꯅꯥ ꯐꯪꯕ ꯑꯥꯌꯔꯕꯦꯗ ꯃꯅꯀꯄꯨꯇꯁꯤꯡ ꯗꯤꯖꯤꯇꯤꯂꯥꯏꯖ ꯇꯧꯅꯕ ꯑꯦꯒꯃꯦꯟꯇ ꯑꯃ ꯈꯨꯠꯌꯦꯛ ꯄꯤꯅꯈꯤ ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 971/1000 [14:13<00:34,  1.21s/it]

[971/1000]
EN: Apollo Hospitals Chairman Dr. Prathap Reddy stated that the 2026 budget strengthens the vision of a healthier India.
MNI_MTEI: ꯑꯦꯄꯣꯂꯣ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯀꯤ ꯆꯦꯌꯔꯃꯦꯟ ꯗꯥ.ꯊꯥꯄ ꯔꯦꯗꯤꯅꯥ ꯍꯥꯏꯈꯤ ꯃꯗꯨꯗꯤ ꯏꯪ 2026 ꯒꯤ ꯕꯖꯦꯠ ꯑꯁꯤꯅ ꯍꯛꯊꯦꯡꯅꯅ ꯍꯤꯡꯕꯥ ꯚꯥꯔꯠꯀꯤ ꯋꯥꯈꯜꯂꯣꯟ ꯑꯗꯨ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 972/1000 [14:15<00:33,  1.20s/it]

[972/1000]
EN: Max Healthcare plans to expand its robotic-assisted surgery program across its network of hospitals.
MNI_MTEI: ꯃꯦꯛꯁ ꯍꯦꯜꯊꯦꯌꯔꯅꯥ ꯃꯈꯣꯏꯒꯤ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯒꯤ ꯅꯦꯠꯋꯥꯔꯛ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯃꯁꯤꯒꯤ ꯔꯣꯕꯣꯇꯤꯛ-ꯑꯦꯁꯦꯁꯇꯦꯗ ꯁꯔꯖꯔꯤꯒꯔꯥꯝ ꯑꯗꯨ ꯄꯥꯛꯊꯣꯛ ꯆꯥꯎꯊꯣꯛꯍꯟꯅꯕ ꯊꯧꯔꯥꯡ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████▎| 973/1000 [14:16<00:33,  1.23s/it]

[973/1000]
EN: Health experts warned that the unorganized diagnostic sector in India will face consolidation due to stricter quality norms.
MNI_MTEI: ꯍꯛꯁꯦꯜꯒꯤ ꯑꯦꯛꯁꯄꯥꯔꯇꯁꯤꯡꯅꯥ ꯆꯦꯛꯁꯤꯟꯋꯥ ꯄꯤꯔꯝꯃꯤ ꯃꯗꯨꯗꯤ ꯀꯋꯥꯂꯤꯇꯤ ꯅꯤꯌꯝꯁꯤꯡ ꯀꯟꯅꯕꯒꯤ ꯃꯔꯝꯅꯥ ꯚꯥꯔꯠꯀꯤ ꯑꯟꯑꯣꯔꯒꯅꯥꯏꯖꯗ ꯗꯥꯏꯒꯅꯣꯁꯇꯤꯛ ꯁꯦꯛꯇꯔ ꯑꯁꯤ ꯀꯣꯟꯁꯣꯂꯤꯗꯤꯌꯦꯁꯟ ꯇꯧꯔꯛꯀꯅꯤ ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████▎| 974/1000 [14:17<00:29,  1.14s/it]

[974/1000]
EN: The Indian Council of Medical Research received 4,000 crore rupees to bolster indigenous medical research.
MNI_MTEI: ꯏꯟꯗꯤꯌꯟ ꯀꯥꯎꯟꯁꯤꯜ ꯑꯣꯐ ꯃꯦꯗꯤꯀꯦꯜ ꯔꯤꯁꯔꯆꯅꯥ ꯏꯗꯤꯖꯦꯟꯁꯤ ꯃꯦꯗꯗꯤꯀꯦꯜ ꯔꯤꯁꯔꯆꯄꯨ ꯃꯄꯥꯡꯒꯜ ꯀꯟꯈꯠꯍꯟꯅꯕ ꯂꯨꯄꯥ ꯀꯔꯣꯔ ꯐꯪ
--------------------------------------------------

Translating:  98%|██████████████████████████▎| 975/1000 [14:18<00:27,  1.11s/it]

[975/1000]
EN: Public health officials are drafting a new Planetary Health Policy Framework to address climate-linked diseases.
MNI_MTEI: ꯍꯦꯜꯊ ꯑꯣꯐꯤꯁꯌꯦꯜꯁꯤꯡꯅ ꯀꯂꯥꯏꯃꯦꯠ-ꯂꯤꯀꯗ ꯗꯤꯖꯤꯖꯁꯤꯡ ꯀꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯑꯅꯧꯕꯅꯦꯇꯔꯤ ꯍꯦꯜꯊ ꯄꯣꯂꯤꯁꯤ ꯐꯃꯋꯥꯔꯀ ꯑꯃ ꯁꯦꯝꯗꯣꯛ
--------------------------------------------------

Translating:  98%|██████████████████████████▎| 976/1000 [14:19<00:26,  1.10s/it]

[976/1000]
EN: The Food Safety and Standards Authority of India is working to make healthy food more affordable than unhealthy options.
MNI_MTEI: ꯐꯨꯗ ꯁꯦꯐꯇꯤ ꯑꯦꯟꯗꯔꯗꯁ ꯑꯣꯊꯣꯔꯤꯇꯤ ꯑꯣꯐ ꯏꯟꯗꯤꯌꯥꯅꯥ ꯍꯛꯆꯥꯡ ꯐꯔꯕ ꯆꯤꯟꯖꯥꯛꯁꯤꯡ ꯑꯁꯤ ꯑꯅꯥꯕꯥ ꯂꯩꯕꯒꯤ ꯑꯣꯞꯁꯟꯁꯤꯡꯗꯒꯤ ꯍꯦꯟꯅ ꯃꯃꯜ ꯌꯥꯝꯕꯥ ꯑꯣꯏꯍꯟꯅꯕ ꯊꯕꯛ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 977/1000 [14:20<00:24,  1.08s/it]

[977/1000]
EN: Researchers at AIIMS Delhi are investigating the use of AI to reduce hospital-acquired infections.
MNI_MTEI: ꯑꯦꯑꯥꯏꯑꯦꯝꯁ ꯗꯤꯜꯂꯤꯒꯤ ꯊꯤꯖꯟ ꯍꯨꯝꯖꯟꯕꯁꯤꯡꯅ ꯍꯣꯁꯄꯤꯇꯥꯜꯅ ꯐꯪꯕꯥ ꯏꯟꯐꯦꯛꯁꯟꯁꯤꯡ ꯍꯟꯊꯍꯟꯅꯕ ꯑꯦꯑꯦ ꯁꯤꯖꯤꯟꯅꯕꯒꯤ ꯃꯇꯥꯡꯗ ꯊꯤꯖꯤꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 978/1000 [14:21<00:24,  1.12s/it]

[978/1000]
EN: The National AIDS Control Organisation is upgrading blood transfusion services to ensure nationwide safety and availability.
MNI_MTEI: ꯅꯦꯁꯅꯦꯜ ꯑꯦꯗꯁ ꯀꯟꯇꯣꯜ ꯑꯣꯔꯒꯥꯅꯥꯏꯖꯦꯁꯟꯅꯥ ꯂꯩꯕꯥꯛ ꯁꯤꯟꯕ ꯊꯨꯡꯅꯥ ꯁꯦꯐꯇꯤ ꯑꯃꯁꯨꯡ ꯐꯪꯍꯟꯕꯥ ꯉꯝꯅꯕ ꯕꯗ ꯇꯥꯟꯁꯐꯨꯖꯟ ꯁꯔꯕꯤꯁ ꯑꯞꯒꯦꯠ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 979/1000 [14:22<00:24,  1.14s/it]

[979/1000]
EN: Indian pediatricians noted a rise in parental awareness regarding neurodivergence and behavioral health issues.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯄꯦꯗꯤꯌꯦꯁꯤꯌꯟꯁꯤꯡꯅ ꯅꯣꯗꯥꯏꯚꯔꯖꯦꯟꯁ ꯑꯃꯁꯨꯡ ꯕꯤꯚꯦꯌꯨꯔꯦꯜ ꯍꯦꯜꯊ ꯏꯁꯨꯖꯁꯤꯡꯒꯤ ꯃꯇꯥꯡꯗ ꯃꯄꯥ-ꯃꯅꯥꯏꯒꯤ ꯑꯦꯚꯦꯌꯔ ꯍꯦꯟꯒꯠꯂꯛꯄ ꯑꯗꯨ ꯈꯪ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 980/1000 [14:24<00:22,  1.15s/it]

[980/1000]
EN: Medical value tourism in India is expected to grow as the government streamlines visa processes for international patients.
MNI_MTEI: ꯚꯥꯔꯠꯇꯥ ꯃꯦꯗꯤꯀꯦꯜ ꯚꯦꯜꯌꯨ ꯇꯨꯔꯤꯖꯝ ꯆꯥꯎꯈꯠꯂꯛꯀꯅꯤ ꯍꯥꯏꯅ ꯄꯥꯅꯔꯤ ꯃꯔꯝꯗꯤ ꯒꯚꯔꯃꯦꯟꯇꯅꯥ ꯏꯟꯇꯔꯅꯦꯁꯅꯦꯜ ꯄꯇꯤꯇꯁꯤꯡꯒꯤ ꯚꯤꯖꯥꯁꯦꯁꯁꯤꯡ ꯁꯃꯂꯥꯏꯟ ꯇꯧ
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 981/1000 [14:25<00:22,  1.17s/it]

[981/1000]
EN: The WHO Global Traditional Medicine Centre in Jamnagar is being upgraded to improve evidence-based research.
MNI_MTEI: ꯖꯝꯅꯒꯔꯗꯥ ꯂꯩꯕ ꯗ ꯌꯨꯑꯍꯣ ꯒ ꯭ ꯂꯣꯕꯦꯜ ꯇꯗꯤꯁꯅꯦꯜ ꯃꯦꯗꯤꯁꯤꯟ ꯁꯦꯟꯇꯔ ꯑꯁꯤ ꯑꯦꯚꯥꯏꯟꯗ-ꯕꯦꯗ ꯔꯤꯁꯔꯆ ꯐꯒꯠꯍꯟꯅꯕ ꯑꯞꯒꯗ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 982/1000 [14:26<00:19,  1.10s/it]

[982/1000]
EN: Indian generic manufacturers are preparing for the patent expiry of several major global obesity medications.
MNI_MTEI: ꯚꯥꯔꯠꯀꯤ ꯖꯦꯅꯦꯔꯤꯛ ꯃꯦꯅꯛꯆꯔꯁꯤꯡꯅ ꯑꯆꯧꯕ ꯒ ꯭ ꯂꯣꯕꯦꯜ ꯑꯣꯕꯦꯁꯤꯇꯤ ꯍꯤꯗꯥꯛ ꯀꯌꯥ ꯑꯃꯒꯤ ꯄꯦꯇꯦꯅꯇ ꯂꯣꯏꯁꯤꯟꯕꯒꯤ ꯁꯦꯝ-ꯁꯥꯔꯤ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 983/1000 [14:27<00:18,  1.09s/it]

[983/1000]
EN: A new digital curriculum was introduced to train public health leaders in epidemiology and modern technology.
MNI_MTEI: ꯑꯦꯄꯤꯗꯦꯃꯤꯌꯣꯂꯣꯖꯤ ꯑꯃꯁꯨꯡ ꯃꯣꯗꯔꯟ ꯇꯦꯛꯅꯣꯂꯣꯖꯤꯗꯥ ꯄ ꯍꯦꯜꯊ ꯂꯤꯗꯔꯁꯤꯡꯕꯨꯦꯟ ꯇꯧꯅꯕꯒꯤꯗꯃꯛ ꯑꯅꯧꯕ ꯗꯤꯖꯤꯇꯦꯜ ꯀꯔꯤꯀꯂꯝ ꯑꯃ ꯄꯨꯔꯛꯈꯤ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 984/1000 [14:28<00:16,  1.05s/it]

[984/1000]
EN: The government is upgrading AYUSH pharmacies to ensure higher quality standards for traditional medicines.
MNI_MTEI: ꯁꯔꯀꯥꯔꯅꯥ ꯑꯥꯌꯨꯁ ꯐꯥꯔꯃꯥꯁꯤꯁꯤꯡꯕꯨ ꯇꯗꯤꯁꯅꯦꯜ ꯃꯦꯗꯤꯁꯤꯟꯁꯤꯡꯒꯤ ꯑꯋꯥꯡꯕ ꯊꯥꯛꯀꯤꯦꯟꯗꯗꯔꯁꯤꯡ ꯐꯪꯍꯟꯅꯕ ꯑꯒꯕꯥꯗ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 985/1000 [14:29<00:15,  1.02s/it]

[985/1000]
EN: Several district hospitals in Uttar Pradesh are now equipped with 24/7 emergency care and trauma units.
MNI_MTEI: ꯎꯠꯇꯔꯗꯥ ꯂꯩꯕ ꯗꯤꯁꯇꯛꯇ ꯍꯣꯁꯄꯤꯇꯥꯂ ꯀꯌꯥ ꯑꯁꯤ ꯍꯧꯖꯤꯛ 24/7 ꯒꯤ ꯏꯃꯔꯖꯦꯟꯁꯤ ꯀꯦꯌꯔ ꯑꯃꯁꯨꯡ ꯇꯃꯥ ꯌꯨꯅꯤꯇꯁꯤꯡ ꯐꯪ
--------------------------------------------------

Translating:  99%|██████████████████████████▌| 986/1000 [14:30<00:14,  1.02s/it]

[986/1000]
EN: Private healthcare providers are increasing investments in Tier 3 cities to capture the growing rural market.
MNI_MTEI: ꯆꯥꯎꯈꯠꯂꯛꯂꯤꯕ ꯈꯨꯡꯒꯪꯒꯤ ꯀꯩꯊꯦꯜ ꯑꯗꯨ ꯂꯧꯁꯤꯟꯅꯕ ꯇꯤꯌꯔ ꯁꯍꯔꯁꯤꯡꯗꯥꯏꯚꯦꯠ ꯍꯦꯜꯊꯀꯦꯌꯔ ꯄꯋꯦꯗꯔꯁꯤꯡꯅ ꯏꯟꯚꯦꯁꯇꯃꯦꯟꯠꯁꯤꯡ ꯍꯦꯟꯒꯠꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 987/1000 [14:31<00:13,  1.02s/it]

[987/1000]
EN: The Indian healthcare workforce is being upskilled through new digital certifications in allied health disciplines.
MNI_MTEI: ꯑꯦꯂꯥꯏꯗ ꯍꯦꯜꯊ ꯗꯤꯄꯄꯤꯂꯟꯁꯤꯡꯗ ꯚꯥꯔꯠꯀꯤ ꯍꯦꯜꯊꯦꯌꯔ ꯋꯥꯔꯛꯁꯣꯐ ꯑꯁꯤ ꯑꯅꯧꯕ ꯗꯤꯖꯤꯇꯦꯜ ꯁꯔꯇꯤꯐꯤꯀꯦꯠꯁꯤꯡꯒꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯑꯞꯁꯀꯤꯜ ꯇꯧꯔꯤ ꯫
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 988/1000 [14:32<00:12,  1.04s/it]

[988/1000]
EN: Public health summits in 2026 emphasized the importance of data-driven decision-making for epidemic prevention.
MNI_MTEI: ꯏꯪꯁꯣꯛ 2026 ꯗꯥ ꯄꯥꯡꯊꯣꯛꯄꯥ ꯍꯦꯜꯊ ꯁꯝꯃꯤꯠꯁꯤꯡ ꯑꯁꯤꯅ ꯂꯥꯏꯆꯠ ꯉꯥꯛꯊꯣꯛꯅꯕꯒꯤꯗꯃꯛ ꯗꯦꯇꯥ-ꯗꯚꯟ ꯗꯤꯁꯤꯁꯟ-ꯃꯦꯀꯤꯡꯒꯤ ꯃꯔꯨꯑꯣꯏꯕ ꯑꯗꯨꯗ ꯄꯨꯛꯅꯤꯡ ꯊꯧꯒꯠꯈꯤ ꯫
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 989/1000 [14:33<00:11,  1.00s/it]

[989/1000]
EN: Hospitals in Mumbai are reporting a shift toward integrated care models for chronic lifestyle diseases.
MNI_MTEI: ꯃꯨꯝꯕꯥꯏꯒꯤ ꯍꯣꯁꯄꯤꯇꯥꯂꯁꯤꯡꯅꯅꯤꯛ ꯂꯥꯏꯅꯥꯁꯤꯡꯒꯤ ꯏꯟꯇꯤꯒꯇꯦꯗ ꯀꯦꯌꯔ ꯃꯣꯗꯦꯜꯁꯤꯡꯗ ꯍꯣꯡꯂꯛꯄꯒꯤ ꯄꯥꯎ ꯄꯤꯔꯤ ꯫
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 990/1000 [14:34<00:10,  1.05s/it]

[990/1000]
EN: The Ministry of Health is focusing on improving the nurse-to-patient ratio in public hospitals through new recruitment drives.
MNI_MTEI: ꯍꯛꯁꯦꯜꯒꯤ ꯃꯟꯇꯅꯥ ꯑꯅꯧꯕ ꯔꯦꯀꯨꯠꯃꯦꯟꯇ ꯗꯚꯁꯤꯡꯒꯤ ꯈꯨꯠꯊꯥꯡꯗ ꯄ ꯍꯣꯁꯄꯤꯇꯥꯜꯁꯤꯡꯗ ꯅꯔꯁ-ꯇ-ꯄꯦꯇꯤꯦꯟꯇ ꯔꯦꯁꯤꯑꯣ ꯐꯒꯠꯍꯟꯕꯗꯥ ꯃꯤꯠꯌꯦꯡ ꯊꯝꯂꯤ ꯫
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 991/1000 [14:35<00:09,  1.03s/it]

[991/1000]
EN: India is positioning itself as a global hub for the manufacturing of affordable biologics and specialized therapies.
MNI_MTEI: ꯚꯥꯔꯠꯅ ꯃꯁꯥ ꯃꯊꯟꯇꯕꯨ ꯃꯃꯜ ꯅꯥꯏꯕꯥ ꯕꯥꯏꯑꯣꯂꯣꯖꯤꯛꯁꯤꯡ ꯑꯃꯁꯨꯡꯁꯤꯑꯦꯂꯤꯁꯇ ꯊꯦꯔꯥꯄꯤꯁꯤꯡ ꯄꯨꯊꯣꯛꯄꯒꯤ ꯒ ꯭ ꯂꯣꯕꯦꯜ ꯍꯕ ꯑꯃ ꯑꯣꯏꯍꯜꯂꯤ ꯫
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 992/1000 [14:36<00:07,  1.04it/s]

[992/1000]
EN: PGIMER doctors achieve major breakthrough in deadly Celphos poisoning
MNI_MTEI: ꯄꯤꯖꯤꯑꯥꯏꯑꯦꯝ ꯏ ꯑꯥꯔ ꯗꯣꯛꯇꯔꯁꯤꯡꯅ ꯁꯤꯔꯕ ꯁꯦꯜꯐꯣꯁ ꯄꯣꯏꯖꯅꯤꯡꯗꯥ ꯑꯆꯧꯕ ꯃꯥꯏ ꯄꯥꯛꯄ ꯐꯪ
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 993/1000 [14:37<00:06,  1.08it/s]

[993/1000]
EN: What a 12-hour work day can do to your metabolic, mental and reproductive health
MNI_MTEI: ꯄꯨꯡ 12ꯒꯤ ꯊꯕꯛꯀꯤ ꯅꯨꯃꯤꯠ ꯑꯃꯅ ꯅꯍꯥꯛꯀꯤ ꯃꯦꯇꯥꯕꯥꯂꯤꯛ, ꯃꯦꯟꯇꯦꯜ ꯑꯃꯁꯨꯡ ꯔꯤꯄꯗꯦꯛꯇꯤꯕ ꯍꯛꯁꯦꯜꯗꯥ ꯀꯔꯤ ꯀꯔꯤ ꯇꯧꯒꯅꯤ
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 994/1000 [14:38<00:05,  1.01it/s]

[994/1000]
EN: Healthcare services disrupted as doctors across states protest Kolkata colleague’s rape-murder
MNI_MTEI: ꯀꯣꯜꯀꯥꯇꯥꯒꯤ ꯂꯣꯏꯅꯕꯤꯕꯨ ꯃꯤꯍꯥꯠ-ꯃꯇꯥꯏꯕꯒꯤ ꯊꯧꯗꯣꯛ ꯑꯗꯨꯗ ꯔꯥꯖ ꯁꯤꯟꯕꯥ ꯊꯨꯡꯅꯥ ꯗꯣꯛꯇꯔꯁꯤꯡꯅꯥ ꯋꯥꯀꯠꯂꯛꯄꯗꯒꯤ ꯍꯦꯜꯊꯦꯌꯔ ꯁꯔꯕꯤꯁꯁꯤꯡꯗ ꯑꯀꯥꯏꯕ ꯊꯣꯛꯈꯤ ꯫
--------------------------------------------------

Translating: 100%|██████████████████████████▊| 995/1000 [14:38<00:04,  1.08it/s]

[995/1000]
EN: Manmohan Singh unveils multi-crore healthcare plan for paramilitary forces
MNI_MTEI: ꯃꯟꯃꯣꯍꯟ ꯁꯤꯡꯍꯅꯥ ꯄꯦꯔꯥꯃꯤꯂꯤꯇꯔꯤ ꯐꯣꯔꯁꯁꯤꯡꯒꯤꯗꯃꯛ ꯀꯔꯣꯔ ꯀꯌꯥꯃꯨꯛꯀꯤ ꯍꯛꯁꯦꯜꯒꯤ ꯊꯧꯔꯥꯡ ꯍꯥꯡꯗꯣꯛ
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 996/1000 [14:39<00:03,  1.05it/s]

[996/1000]
EN: US Senate Hearing Explodes After Senator Questions Indian Origin Doctor on Men’s Pregnancy
MNI_MTEI: ꯌꯨꯑꯦꯁ ꯁꯦꯅꯦꯠꯀꯤ ꯍꯤꯌꯔꯤꯡ ꯑꯁꯤ ꯁꯦꯅꯦꯇꯔꯅꯥ ꯏꯟꯗꯤꯌꯟ ꯑꯣꯔꯤꯖꯦꯟ ꯗꯣꯛꯇꯔꯗꯥ ꯅꯨꯄꯥꯒꯤ ꯄꯒꯦꯟꯁꯤꯒꯤ ꯃꯇꯥꯡꯗ ꯍꯪꯂꯛꯄꯒꯤ ꯃꯇꯨꯡꯗ ꯄꯣꯈꯥꯏꯈꯤ
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 997/1000 [14:40<00:02,  1.09it/s]

[997/1000]
EN: Dr. D N gupta addresses the lack of awareness surrounding Vitamin D deficiency.
MNI_MTEI: ꯗꯥ. ꯗꯤ ꯑꯦꯟ ꯒꯨꯞꯇꯥꯅꯥ ꯚꯤꯇꯥꯃꯤꯟ ꯗꯤ ꯋꯥꯠꯄꯒꯤ ꯑꯀꯣꯏꯕꯗ ꯂꯩꯕ ꯑꯦꯚꯥꯔꯦꯟꯁꯤ ꯋꯥꯠꯄꯗꯥ ꯋꯥꯐꯝ ꯊꯝ
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 998/1000 [14:42<00:02,  1.04s/it]

[998/1000]
EN: Oncologist shares case of non-tobacco related cancer in 21-year-old man with ‘sharp teeth,’ says ‘It could have been identified’
MNI_MTEI: ꯑꯣꯡꯀꯣꯂꯣꯖꯤꯁꯇꯅꯥ ꯆꯍꯤ 21 ꯁꯨꯔꯕꯥ ꯅꯨꯄꯥꯗꯥ "ꯄꯥꯔꯄ ꯗꯊꯁꯤꯡ ꯂꯩꯕ ꯅꯟ-ꯇꯣꯕꯦꯀꯣ ꯔꯤꯂꯦꯃꯦꯇ ꯀꯦꯟꯁꯔꯒꯤ ꯀꯦꯁ ꯁꯦꯌꯔ ꯇꯧꯔꯦ, ꯍꯥꯏꯔꯤ  ꯃꯁꯤ ꯃꯁꯛ ꯈꯪꯗꯣꯛꯄꯥ ꯉꯝꯒꯅꯤ ꯫
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 999/1000 [14:43<00:01,  1.04s/it]

[999/1000]
EN: Nutritionist says pineapple and cinnamon may help reduce period cramps naturally
MNI_MTEI: ꯅꯇꯁꯤꯁꯇꯅꯥ ꯍꯥꯏꯔꯤ ꯃꯗꯨꯗꯤ ꯑꯅꯤꯄꯂ ꯑꯃꯁꯨꯡ ꯁꯤꯅꯥꯃꯣꯅꯥ ꯃꯍꯧꯁꯥꯒꯤ ꯑꯣꯏꯕ ꯃꯑꯣꯡꯗ ꯄꯤꯔꯨꯗ ꯀ ꯭ ꯔꯦꯝꯄꯁꯤꯡ ꯍꯟꯊꯍꯟꯕꯗꯥ ꯃꯇꯦꯡ ꯄꯥꯡꯕ ꯌꯥꯏ ꯫
--------------------------------------------------

Translating: 100%|██████████████████████████| 1000/1000 [14:43<00:00,  1.13it/s]

[1000/1000]
EN: Don’t brush before bed? Your heart might pay the price
MNI_MTEI: ꯅꯨꯡꯊꯤꯜꯒꯤ ꯃꯃꯥꯡꯗ ꯕꯁ ꯇꯧꯔꯣꯏꯗꯕꯅꯤ ꯫ ꯅꯍꯥꯛꯀꯤ ꯊꯝꯃꯣꯏꯅ ꯃꯃꯜ ꯊꯤꯕꯥ ꯌꯥꯏ ꯫
--------------------------------------------------
✅ Saved to /home/dingku/Desktop/manipuri_meitei_translations.txt

============================================================
Translating brx...
============================================================

Found 1000 sentences.

Translating:   0%|                             | 1/1000 [00:00<10:19,  1.61it/s]

[1/1000]
EN: NDTV has learnt from sources that the T20 World Cup 2026 match between India and Pakistan is ON.
BRX: भारत आरो पाकिस्ताननि गेजेराव टि20 बुहुमनां काप 2026 मेचआ दावगालांगासिनो दं ।
--------------------------------------------------

Translating:   0%|                             | 2/1000 [00:01<09:08,  1.82it/s]

[2/1000]
EN: The PCB placed several demands before the ICC.
BRX: बिसिबिआ आईसीसीनि सिगाङाव गोबां दाबिफोर दोनदोंमोन.
--------------------------------------------------

Translating:   0%|                             | 3/1000 [00:01<10:26,  1.59it/s]

[3/1000]
EN: The PCB pushed for ICC intervention to facilitate a bilateral series between India and Pakistan.
BRX: भारत आरो पाकिस्ताननि गेजेराव मोन्नैआरि सिरिजखौ खाबु होनो थाखाय आईसीसीनि सायाव नारसिननाय जादों ।
--------------------------------------------------

Translating:   0%|                             | 4/1000 [00:03<14:07,  1.17it/s]

[4/1000]
EN: Virat Kohli and Rohit Sharma have been demoted to Grade B in BCCI's central contract list for 2025-26.
BRX: बि. के. सि. आइ. नि गाहाय सायख 'नायफोरनि गेजेराव मोनसेआ जादों दि क्रिकेटनि गिबि फारियाव गेलेबाय थानाय भारत आरो पाकिस्तानखौ समानथि गैयै खालामनाय ।
--------------------------------------------------

Translating:   0%|▏                            | 5/1000 [00:03<13:20,  1.24it/s]

[5/1000]
EN: Thirty senior men's cricketers have been awarded central contracts, with the BCCI doing away with the A+ grade.
BRX: बिसिसिआ ए+ ग्रेदखौ बोखारना थामजि देरसिन हौवाफोरनि क्रिकेटारफोरखौ मिरुआरि कन्ट्रेक्ट होनाय जादों |
--------------------------------------------------

Translating:   1%|▏                            | 6/1000 [00:04<14:27,  1.15it/s]

[6/1000]
EN: As per the 2024-25 BCCI contracts, any player in Grade A would receive Rs 5 crore annually.
BRX: इं 2024-25 माइथायनि थाखाय बि. सि.सि.आइ. आ ए. ग्रेडनि जायखिजाया गेलेगिरिखौ बोसोरफ्रामबो 5 कौटि रां बान्था मोनगोन.
--------------------------------------------------

Translating:   1%|▏                            | 7/1000 [00:05<13:36,  1.22it/s]

[7/1000]
EN: Grade B players would get Rs 3 crore, while
BRX: इं 2020 माइथायनि गेजेरसिम गेलेबाय थानाय प्लेइंग इलेवनफोरनि गेजेराव सासेआ गाव हारसिङैनो जाफुंसार जानो हागौ |
--------------------------------------------------

Translating:   1%|▏                            | 8/1000 [00:05<11:34,  1.43it/s]

[8/1000]
EN: Grade C players would get Rs 1 crore.
BRX: ग्रेड सीनि गेलेगिरिफोरा 1 कौटि रां मोनगोन.
--------------------------------------------------

Translating:   1%|▎                            | 9/1000 [00:06<11:53,  1.39it/s]

[9/1000]
EN: Earlier, Grade A+ players (Kohli, Rohit, Jasprit Bumrah, Ravindra Jadeja) used to receive Rs 7 crore.
BRX: इं 2020 माइथायनि गेजेरसिम क्रिकेट गेलेबाय थानाय भारतारि गेलेगिरिफोरनि गेजेराव सासेआ गाव हारसिङैनो जाफुंसारदों ।
--------------------------------------------------

Translating:   1%|▎                           | 10/1000 [00:07<12:59,  1.27it/s]

[10/1000]
EN: The BCCI has not yet officially declared whether the payment structure for 2025-26 will be any different.
BRX: बि. सि.सि.आइ.आ दासिमबो मावख 'ारियै फोसावाखै दि 2025-26 मायथाइनि थाखाय रां होनायनि दाथाया माबा गुबुन जागोन ना नङा |
--------------------------------------------------

Translating:   1%|▎                           | 11/1000 [00:08<11:59,  1.37it/s]

[11/1000]
EN: 21 women cricketers classified in Grade A, B and C.
BRX: ग्रेड ए.बि. आरो सी.आव थाखो रानजानाय 21 आइजो क्रिकेटारफोर |
--------------------------------------------------

Translating:   1%|▎                           | 12/1000 [00:08<12:08,  1.36it/s]

[12/1000]
EN: Harmanpreet Kaur, Smriti Mandhana, Deepti Sharma and Jemimah Rodrigues are the four players to be included in Grade A.
BRX: भारत क्रिकेट टीमनि गाहाय गेलेगिरिफोरनि गेजेराव सासेआ पि. एम. सि. खौ फेजेन्नो हानायाव जाफुंसारदों ।
--------------------------------------------------

Translating:   1%|▎                           | 13/1000 [00:09<12:14,  1.34it/s]

[13/1000]
EN: The cycle for new central contract is based on performance and volume of games played during the preceding season.
BRX: गोदान मिरुआरि कन्ट्रेक्टनि थाखाय साइकेलआ सिगांनि सिजननि समाव गेलेजानाय गेलेमुफोरनि दिन्थिफुंनाय आरो बिबांनि सायाव बिथा खालामनाय |
--------------------------------------------------

Translating:   1%|▍                           | 14/1000 [00:10<12:01,  1.37it/s]

[14/1000]
EN: Pakistan and Bangladesh's demands from the International Cricket Council (ICC) have just grown bigger.
BRX: पाकिस्तान आरो बांग्लादेशनि दाबिफोरा गेजेर हायुंआरि क्रिकेट आफाद (आई.सी. सी. निफ्राय बावैसो गिदिर जाबाय |
--------------------------------------------------

Translating:   2%|▍                           | 15/1000 [00:11<12:10,  1.35it/s]

[15/1000]
EN: The 2031 edition of the ODI World Cup is set to be played in India and Bangladesh.
BRX: भारत आरो बांग्लादेशआव अ.डि.आइ. मुलुग कापनि 2031 संस्करण गेलेजानांगौ ।
--------------------------------------------------

Translating:   2%|▍                           | 16/1000 [00:11<11:28,  1.43it/s]

[16/1000]
EN: At present, the hybrid model is applicable until 2027.
BRX: आथिखालाव हाइब्रिद मडेलआ 2027 मायथाइसिम बाहायजाथाव नङा.
--------------------------------------------------

Translating:   2%|▍                           | 17/1000 [00:12<11:18,  1.45it/s]

[17/1000]
EN: The extension would allow Bangladesh and Pakistan to play all their matches in Bangladesh and not India.
BRX: बांग्लादेश आरो पाकिस्तानखौ गावसोरनि गासिबो मेचफोरखौ बांग्लादेशआव गेलेनो गनायथि होगोन आरो भारतनि नङा |
--------------------------------------------------

Translating:   2%|▌                           | 18/1000 [00:13<14:03,  1.16it/s]

[18/1000]
EN: The BCB was represented by its head Aminul Islam Bulbul while PCB chairman Mohsin Naqvi was also present.
BRX: बिसिबिनि गाहाय अमीनुल इस्लाम बुलबुलआ बि.सि.बि.नि थान्दैमोन आरो बिनि उनमोनगिरि महसिन नकवीआबो लोगोसे दंमोन |
--------------------------------------------------

Translating:   2%|▌                           | 19/1000 [00:15<16:10,  1.01it/s]

[19/1000]
EN: ICC's deputy chairman Imran Khawaja was present in the meeting.
BRX: आइ. सि.सि.नि लेङाइ आफादगिर इमरान ख्वाजाया मेलाव दंमोन |
--------------------------------------------------

Translating:   2%|▌                           | 20/1000 [00:15<14:26,  1.13it/s]

[20/1000]
EN: No joint declaration was issued after the four-hour meeting.
BRX: ब्रै घन्टानि जथुमानि उनाव जेबो जथाय फोसावथाइ फोसावजायाखैमोन تمہनैयाबो ।
--------------------------------------------------

Translating:   2%|▌                           | 21/1000 [00:16<15:04,  1.08it/s]

[21/1000]
EN: The hybrid model arrangement was introduced after India refused to tour Pakistan for the 2025 Champions Trophy.
BRX: भारतआ इं 2025 माइथायनि चैंपियन्स ट्रॉफीनि थाखाय पाकिस्तान दावबायनायखौ नेवसिगारनायनि उनाव हाइब्रिद मडेलनि साजायनायखौ सिनायथि होनाय जादोंमोनपाटिया ।
--------------------------------------------------

Translating:   2%|▌                           | 22/1000 [00:17<13:56,  1.17it/s]

[22/1000]
EN: After extensive negotiations, a hybrid model was accepted by all parties, including the ICC.
BRX: गोबां सावरायनायनि उनाव, आईसीसीजों लोगोसे गासिबो हानजाया मोनसे हाइब्रिद मडेलखौ नाजावदोंमोन.
--------------------------------------------------

Translating:   2%|▋                           | 23/1000 [00:18<15:10,  1.07it/s]

[23/1000]
EN: The second part of the arrangement states that Pakistan will not travel to India for the 2026 T20 World Cup.
BRX: अस्ट्रेलियानि बि. जे. पि. नि नैथि बाहागोआ बुंदों दि भारतआ इं 2026 माइथायनि टि20 बुहुमनां कापनि थाखाय दावबायहैाखै ۔
--------------------------------------------------

Translating:   2%|▋                           | 24/1000 [00:19<14:02,  1.16it/s]

[24/1000]
EN: As a result, all of Pakistan's matches (even if they reach the final) will be played in Sri Lanka.
BRX: बेनि जाहोनाव पाकिस्ताननि गासिबो मेचफोरा ( फाइनालाव सौहैनायब्लाबो ) श्रीलंकायाव गेलेनाय जागोन.
--------------------------------------------------

Translating:   2%|▋                           | 25/1000 [00:19<12:20,  1.32it/s]

[25/1000]
EN: Bangladesh, Pakistan, and India must be treated the same.
BRX: पाकिस्तान आरो भारतखौ रोखोमसे आखु होजानांगौ |
--------------------------------------------------

Translating:   3%|▋                           | 26/1000 [00:20<11:22,  1.43it/s]

[26/1000]
EN: Now, Gavaskar has taken an indirect jibe at Hussain
BRX: गावस्करआ गावनि नख 'रखौ फेहेरदों
--------------------------------------------------

Translating:   3%|▊                           | 27/1000 [00:21<16:22,  1.01s/it]

[27/1000]
EN: He went on to give the example of the 2003 World Cup, when England refused to tour Zimbabwe in protest against Robert Mugabe's regime.
BRX: बिथाङा इं 2003 माइथायनि बुहुमनां कापनि बिदिन्थिखौ होनो थाखाय थांनायसै. जेब्ला इंलेन्डआ रबर्ट मुगाबेनि खुंथायनि बेरेखायै जिम्बाब्वे दावबायनायखौ नेवसिगारदोंमोन |
--------------------------------------------------

Translating:   3%|▊                           | 28/1000 [00:22<14:17,  1.13it/s]

[28/1000]
EN: Samson's knock was full of intent but fell short in effectiveness quotient.
BRX: सेमसननि नकआ थांखिजों बुंफबनायमोन नाथाय गोहोम गोनां बिबाङाव बाङाइ जादोंमोन.
--------------------------------------------------

Translating:   3%|▊                           | 29/1000 [00:23<12:43,  1.27it/s]

[29/1000]
EN: With this win, India overtook Pakistan at the summit of Group A courtesy of a superior net run-rate.
BRX: बे मेचआव भारतआ पाकिस्तानखौ फेजेन्नो हानायाव जाफुंसारदों ।
--------------------------------------------------

Translating:   3%|▊                           | 30/1000 [00:23<12:09,  1.33it/s]

[30/1000]
EN: India batter Abhishek Sharma will take no part in the T20 World Cup 2026 clash against Namibia in New Delhi on Thursday.
BRX: भारत आरो बांग्लादेशनि गेजेराव जानाय क्रिकेट मेचआव अभिषेक शर्माया गिबिखेब गावस्रालाङो ।
--------------------------------------------------

Translating:   3%|▊                           | 31/1000 [00:24<11:06,  1.45it/s]

[31/1000]
EN: Abhishek isn't fine still, might take one or two games.
BRX: अभिषेकआ दाबो मोजां नङा @ मोनसे एबा मोननै गेम लानो हागौ |
--------------------------------------------------

Translating:   3%|▉                           | 32/1000 [00:24<09:21,  1.72it/s]

[32/1000]
EN: Samson comes in.
BRX: सेमसनआ फैयो |
--------------------------------------------------

Translating:   3%|▉                           | 33/1000 [00:25<10:03,  1.60it/s]

[33/1000]
EN: Bumrah comes in for Siraj," said Suryakumar at the toss.
BRX: सूर्यकुमारआ गावसिनि गिबि मेचआव गेलेयो ।
--------------------------------------------------

Translating:   3%|▉                           | 34/1000 [00:26<13:54,  1.16it/s]

[34/1000]
EN: Defending with dew will build our confidence. Hope our batters entertain the crowd.
BRX: सिदोबजों डिफेन्दिं खालामनाया जोंनि फोथायथिखौ बानायगोन. मिजिंथियोदि जोंनि बेटसमेनफोरा होंगो-गोखौ रंजाहोयोꯗꯨ ।
--------------------------------------------------

Translating:   4%|▉                           | 35/1000 [00:27<11:55,  1.35it/s]

[35/1000]
EN: It's a big tournament, dew will be a big factor.
BRX: बेयो मोनसे गिदिर टुर्नामेन्ट > बरफआ मोनसे गेदेर जाहोन जागोन.
--------------------------------------------------

Translating:   4%|█                           | 36/1000 [00:27<11:15,  1.43it/s]

[36/1000]
EN: India made two changes to the side that beat the USA on the opening day of the tournament.
BRX: भारतआ टुर्नामेन्टनि जागायजेन्नायनि सानाव आमेरिकाखौ फेजेननाय हानजायाव मोन्नै सोलायनाय खालामदों |
--------------------------------------------------

Translating:   4%|█                           | 37/1000 [00:28<11:02,  1.45it/s]

[37/1000]
EN: Sanju Samson replaced Abhishek, while Jasprit Bumrah replaced Mohammed Siraj in the India XI.
BRX: भारत क्रिकेट टीमआ इंलेन्डनि प्लेइंग इलेवनखौ फेजेन्नो हागोन ।
--------------------------------------------------

Translating:   4%|█                           | 38/1000 [00:29<10:44,  1.49it/s]

[38/1000]
EN: India take on Pakistan next, with the team set to travel to Colombo for the game on February 15.
BRX: भारत आरो पाकिस्ताननि गेजेराव जानाय मेचआ इं 2020 माइथायनि 15 फेब्रुआरि खालि जानो हागौ ।
--------------------------------------------------

Translating:   4%|█                           | 39/1000 [00:29<09:52,  1.62it/s]

[39/1000]
EN: The cabinet agreed with certain conditions as per the Cunha report.
BRX: केबिनेटआ कुनहा रिपर्टनि बायदिब्ला माखासे सर्तफोरजों गोरोबदोंमोन.
--------------------------------------------------

Translating:   4%|█                           | 40/1000 [00:30<09:54,  1.61it/s]

[40/1000]
EN: He mentioned in the report a maximum of 35,000 people and other conditions.
BRX: बिथाङा फोरमायथियाव बांसिननिफ्राय बांसिन 35,000 सुबुंफोर आरो गुबुन थासारिफोरखौ मुंख 'दोंमोन.
--------------------------------------------------

Translating:   4%|█▏                          | 41/1000 [00:31<10:40,  1.50it/s]

[41/1000]
EN: India reached the 100-run mark in just 6.5 overs - the fastest team hundred in T20 World Cup history.
BRX: भारतआ खालि 6.5 अभाराव 100 रान बानायदोंमोन - जाय टि20 मुलुग काप जारिमिनाव बयनिख्रुइबो गोख्रैसिन टीम सेजौमोन.
--------------------------------------------------

Translating:   4%|█▏                          | 42/1000 [00:31<10:15,  1.56it/s]

[42/1000]
EN: After being asked to bat first, India were off to a decent start, making 8/0 in the first over.
BRX: भारतनि गिबि मेचआव भारतआ 8/0 रान बानायदों ।
--------------------------------------------------

Translating:   4%|█▏                          | 43/1000 [00:32<10:49,  1.47it/s]

[43/1000]
EN: After four overs, the defending champions reached 43/1, with Ishan Kishan finding a couple of boundaries.
BRX: बे मेचआव भारतखौ फेजेन्नो थाखाय प्लेआफआव सौहैनो गोनां जादों ।
--------------------------------------------------

Translating:   4%|█▏                          | 44/1000 [00:33<12:40,  1.26it/s]

[44/1000]
EN: On the first ball of the 11th over, spinner Bernard Scholtz dismissed captain Suryakumar Yadav for just 12.
BRX: अस्ट्रेलियानि बि. जे. पि. सि. नि गिबि मेचआव भारत आरो पाकिस्ताननि गेजेराव समानथि गैयै गेलेनायखौ नुनो मोनदों ।
--------------------------------------------------

Translating:   4%|█▎                          | 45/1000 [00:34<13:06,  1.21it/s]

[45/1000]
EN: India lost another wicket quickly when Tilak Varma was removed for 25 by Namibia skipper Erasmus in the 12th over.
BRX: भारतआ आरोबाव मोनसे विकेट खोमानाङो जेब्ला 12थि अभाराव नामिबियानि केप्तेन इरास्मासआ 25 रानआव बोनायसै.
--------------------------------------------------

Translating:   5%|█▎                          | 46/1000 [00:35<13:19,  1.19it/s]

[46/1000]
EN: Shivam Dube and Hardik Pandya then combined to hammer 24 runs off Bernard Scholtz as India raced to 168/4.
BRX: बे मेचआव भारत आरो बांग्लादेशनि सानै गेलेगिरिफोरनि गेजेराव गेलेनाया जाफुंसारदों ।
--------------------------------------------------

Translating:   5%|█▎                          | 47/1000 [00:36<13:46,  1.15it/s]

[47/1000]
EN: By the end of the 18th over, India had reached 199/4 with Pandya and Dube going strong.
BRX: बे मेचआव भारतखौ फेजेन्नो थाखाय प्लेआफआव सौहैनो गोनां जादों ।
--------------------------------------------------

Translating:   5%|█▎                          | 48/1000 [00:37<13:46,  1.15it/s]

[48/1000]
EN: On the first ball of the 19th over, Pandya completed his fifty off 27 deliveries as India crossed the 200-run mark.
BRX: इं 19 माइथायनि गिबि बलआव, पान्ड्याया 27 डेलिभारीआव गावनि बाजिखौ फोजोबदोंमोन मानोना भारतआ 200 राननि सिमा बारदोंमोन.
--------------------------------------------------

Translating:   5%|█▎                          | 49/1000 [00:38<15:10,  1.04it/s]

[49/1000]
EN: Shivam Dube was run out for 23 after a mix-up with Rinku Singh.
BRX: इंलेन्डनि बि. जे. पि. नि गिबि मेचआव भारतखौ आवगायनो थाखाय के. एम. सि. खौ सायख 'नाय जादों ।
--------------------------------------------------

Translating:   5%|█▍                          | 50/1000 [00:38<13:59,  1.13it/s]

[50/1000]
EN: India then lost Rinku Singh (1) and Arshdeep Singh (2) in the final over, finishing at 209/9.
BRX: भारतआ बे मेचआव गिबि खेब गेलेनायखौ नुनो मोनो ।
--------------------------------------------------

Translating:   5%|█▍                          | 51/1000 [00:39<14:32,  1.09it/s]

[51/1000]
EN: ICC Men’s T20 World Cup 2026 began on February 7, 2026, at Sinhalese Sports Club Ground with Pakistan playing Netherlands in the opening match.
BRX: इं 2026 माइथायनि 7 फेब्रुआरि खालि श्रीलंकानि बि. जे. पि. नि गिबि मेचआव भारतखौ फेजेन्नो थाखाय नेदारलेन्डखौ आवगायनो गोनां जादों ।
--------------------------------------------------

Translating:   5%|█▍                          | 52/1000 [00:41<15:23,  1.03it/s]

[52/1000]
EN: Bangladesh national cricket team faced the India men's national cricket team in an opening match reported ahead of the 2026 T20 tournament.
BRX: इं 2026 माइथायनि टि20 टूर्नामेन्टनि सिगां फोसावनाय मोनसे गिबि मेचआव बांग्लादेश हादोरारि क्रिकेट टीमा भारतनि हौवाफोरनि हायुंआरि क्रिकेट टीमजों मोगा-मोगि जादोंमोन.
--------------------------------------------------

Translating:   5%|█▍                          | 53/1000 [00:41<14:05,  1.12it/s]

[53/1000]
EN: Ishan Kishan struck a rapid half-century.
BRX: भारत आरो पाकिस्ताननि गेजेराव गेलेबाय थानाय मेचआव, जाय इं 2020 माइथायनि गेजेरसिम दावगालांनो हागोन नङा.
--------------------------------------------------

Translating:   5%|█▌                          | 54/1000 [00:42<13:02,  1.21it/s]

[54/1000]
EN: Faf du Plessis scored a half-century and Mitchell Starc took a five-wicket haul in the same match report.
BRX: स्टार्कआ बे मेचआव मोनसे रान बानायदोंमोन ।
--------------------------------------------------

Translating:   6%|█▌                          | 55/1000 [00:43<13:55,  1.13it/s]

[55/1000]
EN: Jasprit Bumrah and Ravindra Jadeja were reported to have been demoted in the 2025–26 central contracts discussion.
BRX: इं 2025 मायथाइआव अस्ट्रेलियानि बि. जे. पि. टीमआ भारतखौ आवगायनो हागोन ।
--------------------------------------------------

Translating:   6%|█▌                          | 56/1000 [00:43<12:17,  1.28it/s]

[56/1000]
EN: Rohit Sharma carried the men’s T20 World Cup trophy during a promotional appearance.
BRX: रोहित शर्माया भारतनि थाखाय टि20 क्रिकेटनि ट्रफी लादोंमोन.
--------------------------------------------------

Translating:   6%|█▌                          | 57/1000 [00:44<12:17,  1.28it/s]

[57/1000]
EN: The International Cricket Council update said a high-profile match involving Pakistan would go ahead on February 15, 2026, in Colombo.
BRX: अस्ट्रेलियानि क्रिकेट एसोसिएशनआ बुंदों दि इं 2026 माइथायनि 15 फेब्रुआरिआव पाकिस्तानजों लोगोसे मोनसे गोजौ थाखोनि मेच जानो गोनां ।
--------------------------------------------------

Translating:   6%|█▌                          | 58/1000 [00:45<11:34,  1.36it/s]

[58/1000]
EN: The New Zealand national cricket team lost the first ODI by four wickets to the India men's national cricket team.
BRX: भारत आरो बांग्लादेशनि गेजेराव जानाय मोन्नैबो हादोर गेजेरारि मेचफोरनि गेजेराव मोनसेआ जानो हागौ ।
--------------------------------------------------

Translating:   6%|█▋                          | 59/1000 [00:46<12:55,  1.21it/s]

[59/1000]
EN: Australia national cricket team ended day one at 67 for seven in reply to 150 by the India men's national cricket team in a Test match post.
BRX: अस्ट्रेलियानि हादोरारि क्रिकेट टीमआ मोनसे टेस्ट मेचनि उनाव भारतनि हौवाफोरनि हायुंआरि क्रिकेट हानजाजों 150 रान बानायजानायनि फिनाव गिबि सानखौ स्नि विकेटआव 67 रानजों फोजोबदोंमोन.
--------------------------------------------------

Translating:   6%|█▋                          | 60/1000 [00:47<12:45,  1.23it/s]

[60/1000]
EN: The India national under-19 cricket team won the ICC U19 World Cup final by 100 runs against the England national under-19 cricket team in Harare.
BRX: भारतनि 19 बोसोर सिङावनि क्रिकेट हानजाया इंलेन्डनि 19 बोसोरनि सिङाव थानाय क्रिकेट टीमखौ फाइनालाव 100 रानजों देरहादोंमोन.
--------------------------------------------------

Translating:   6%|█▋                          | 61/1000 [00:47<12:13,  1.28it/s]

[61/1000]
EN: Members of the India women's national cricket team were given a grand welcome after their title-winning campaign.
BRX: भारतनि आइजो हायुंआरि क्रिकेट टीमनि सोद्रोमाफोरखौ गावसिनि बिमुं देरहानायनि उनाव गिदिर बरनायनाय होनाय जादोंमोन.
--------------------------------------------------

Translating:   6%|█▋                          | 62/1000 [00:48<12:23,  1.26it/s]

[62/1000]
EN: The India women's national cricket team lifting the ICC Women’s World Cup as one of the year’s landmark moments.
BRX: भारतनि आइजो हायुंआरि क्रिकेट टीमआ आईसीसी आयजोफोरनि बुहुमनां कापखौ बोसोरनि जारिमिनारि बुब्लिफोरनि गेजेराव मोनसे महरै बोजबदों |
--------------------------------------------------

Translating:   6%|█▊                          | 63/1000 [00:49<13:48,  1.13it/s]

[63/1000]
EN: The Indian Premier League season in 2025 was reported as suspended indefinitely amid escalating India–Pakistan military tensions.
BRX: इं 2025 माइथायाव भारतारि प्रीमियर लीगनि सिजनखौ भारत आरो पाकिस्ताननि रौनियाफोरनि दावराव-दावसिनि गेजेराव अरायथा नङै समनि थाखाय दानथ 'नाय होनना खौरां मोन्नाय जादोंमोनपाइरो ।
--------------------------------------------------

Translating:   6%|█▊                          | 64/1000 [00:50<13:07,  1.19it/s]

[64/1000]
EN: The Eden Gardens hosted the opening spectacle for the 18th edition of the Indian Premier League.
BRX: ईडेन गार्डेनआ इन्डियान प्रिमियार लीगनि 18थि एडिशननि जागायजेन्नाय नायजाबखौ खुंदोंमोन |
--------------------------------------------------

Translating:   6%|█▊                          | 65/1000 [00:51<13:14,  1.18it/s]

[65/1000]
EN: Royal Challengers Bengaluru named Rajat Patidar as captain for the season starting March 21.
BRX: र 'यल चेलेन्जर्स बेंगलुरूआ 21 मार्चनिफ्राय जागायजेन्नाय सिजननि थाखाय रजत पटिदारखौ केप्तेन महरै सायख.दों |
--------------------------------------------------

Translating:   7%|█▊                          | 66/1000 [00:52<12:34,  1.24it/s]

[66/1000]
EN: Chennai Super Kings posted their lowest home total and suffered a fifth straight loss.
BRX: चेन्नाई सुपार किंग्सआ गावसिनि बयनिख्रुइ गाहायसिन नख 'रि गासैखौ पस्ट खालामदोंमोन आरो फारियै बाथि जेनदोंमोन |
--------------------------------------------------

Translating:   7%|█▉                          | 67/1000 [00:52<12:04,  1.29it/s]

[67/1000]
EN: A Dharamsala fixture involving Punjab Kings and Delhi Capitals was called off after a blackout.
BRX: पंजाब किंग्स आरो दिल्ली केपिटल्सजों लोगोसे मोनसे धर्मशाला मेचखौ ब्लेकआउटनि उनाव बोखारनाय जादोंमोन.
--------------------------------------------------

Translating:   7%|█▉                          | 68/1000 [00:53<13:04,  1.19it/s]

[68/1000]
EN: Punjab Kings defeated Mumbai Indians in Jaipur to secure a top-two league finish.
BRX: पंजाब किंग्सआ जयपुरआव गोजौसिन मोन्नै लीग जोबनायखौ रैखाथि होनो थाखाय मुम्बाइ इन्डियन्सखौ फेजेनदोंमोन/जेन्टसनखौ फेजेन्नो हानायाव जाफुंसारनाय नुनो मोनदों |
--------------------------------------------------

Translating:   7%|█▉                          | 69/1000 [00:55<15:56,  1.03s/it]

[69/1000]
EN: KL Rahul became the fastest Indian to 8,000 T20 runs after an unbeaten 112.
BRX: के.एल. राहुलआ 8,000 टि20 रान बानायनायनि उनाव बयनिख्रुइबो गोख्रैसिन भारतारि जानो हादोंमोन/09/1/2/5/6/4/7/8/3/19 रन बानायदोंमोन |
--------------------------------------------------

Translating:   7%|█▉                          | 70/1000 [00:56<14:29,  1.07it/s]

[70/1000]
EN: Virat Kohli spoke about the June 4 stampede linked to his franchise’s celebrations.
BRX: विराट कोहलीआ 4 जूननि स्टाम्पेडखौ गावनि फ्रेन्चाइजीनि फालिथाइजों सोमोन्दो गोनां फोरमायदोंमोन.
--------------------------------------------------

Translating:   7%|█▉                          | 71/1000 [00:57<14:55,  1.04it/s]

[71/1000]
EN: The uncertainty over player retention created suspense ahead of the next Indian Premier League season.
BRX: भारतारि प्रीमियर लीगनि सिजननि सिगां गेलेगिरिफोरखौ हमथाना लाखिनायनि सायाव दिदोमथि गैयैआ ससपेन्स सोमजिहोदोंमोन.
--------------------------------------------------

Translating:   7%|██                          | 72/1000 [00:57<13:52,  1.11it/s]

[72/1000]
EN: Rafael Nadal announced he would retire.
BRX: रफेल नादालआ गावनि सानस्रिनायखौ फोजोबदों ।
--------------------------------------------------

Translating:   7%|██                          | 73/1000 [00:58<13:17,  1.16it/s]

[73/1000]
EN: Carlos Alcaraz beat Novak Djokovic to win his first major title.
BRX: कारलास अलकाराजआ गावनि गिबि गाहाय बिमुंखौ देरहानो थाखाय नोवाक जकोविकखौ फेजेन्नो हादोंमोन.
--------------------------------------------------

Translating:   7%|██                          | 74/1000 [00:59<14:10,  1.09it/s]

[74/1000]
EN: Alexander Zverev lost a marathon match to Carlos Alcaraz in a five-set battle.
BRX: एलेक्जेन्डार ज्वेरेभआ बा सेटनि दावहायाव कार्लोस अलकाराजजों मोनसे मैराथन मेचखौ जेनदोंमोन.
--------------------------------------------------

Translating:   8%|██                          | 75/1000 [01:00<13:07,  1.17it/s]

[75/1000]
EN: Rohan Bopanna announced his retirement from professional tennis.
BRX: र 'हन बपन्नाआ प्रफेशनेल टेनिसनिफ्राय गावनि सानस्रिनायखौ फोसावदोंमोन.
--------------------------------------------------

Translating:   8%|██▏                         | 76/1000 [01:01<13:05,  1.18it/s]

[76/1000]
EN: A 14-place leap that signaled an upswing for India Davis Cup team in international tennis standings.
BRX: मोनसे 14थि जायगा बारलांनाया भारतनि डेविस काप टीमनि थाखाय हादोर गेजेरारि टेनिस स्टान्डिंआव गोजौ जौथायनि इंगित होदोंमोन |
--------------------------------------------------

Translating:   8%|██▏                         | 77/1000 [01:01<12:18,  1.25it/s]

[77/1000]
EN: Elena Rybakina overcame Aryna Sabalenka to win the 2026 Australian Open final.
BRX: अस्ट्रेलियानि स्टार गेलेगिरिया आरियाना साबालेन्काखौ फेजेन्नो हानायाव जाफुंसारदों ।
--------------------------------------------------

Translating:   8%|██▏                         | 78/1000 [01:02<11:58,  1.28it/s]

[78/1000]
EN: Novak Djokovic became the first player to reach 400 Grand Slam singles match wins in the Open Era.
BRX: ब्रुसेल्सआ बे मेचआव गेलेयो ।
--------------------------------------------------

Translating:   8%|██▏                         | 79/1000 [01:05<20:16,  1.32s/it]

[79/1000]
EN: The India men's national field hockey team and its Olympic bronze-medal campaign in a dedicated post.
BRX: भारतनि हौवाफोरनि हादोरारि फिल्ड हकी टीम आरो बिनि अलिम्पिक ब्रन्ज-मेदल केम्पेइनआ मोनसे बावसोमनाय पोस्टआव |
--------------------------------------------------

Translating:   8%|██▏                         | 80/1000 [01:05<16:42,  1.09s/it]

[80/1000]
EN:  The India men's national field hockey team across major tournaments.
BRX: भारतनि हौवाफोरनि हायुंआरि फिल्ड हकी हानजाया गाहाय टुर्नामेन्टफोराव ।
--------------------------------------------------

Translating:   8%|██▎                         | 81/1000 [01:06<16:02,  1.05s/it]

[81/1000]
EN: The India men's national field hockey team beat South Korea men's national field hockey team 4–1 in a match update.
BRX: भारतनि हौवाफोरनि हादोरारि फिल्ड हकी टीमा मोनसे मेच आपदेटआव खोला क 'रियानि हौवानि हायुंआरि फील्ड हकी टीमखौ 4/1 जों फेजेनदोंमोन.
--------------------------------------------------

Translating:   8%|██▎                         | 82/1000 [01:07<15:29,  1.01s/it]

[82/1000]
EN: The house of K. D. Singh Babu would be developed as a tourist attraction.
BRX: के.डी. सिंह बाबूनि न 'खौ दावबायारिफोरनि गोसो बोनो हानाय थावनि महरै जौगाहोनाय जागोनपाटों ।
--------------------------------------------------

Translating:   8%|██▎                         | 83/1000 [01:08<13:45,  1.11it/s]

[83/1000]
EN: Lakshya Sen finished fourth in a tournament.
BRX: लक्ष्य सेनआ मोनसे टूर्नामेन्टआव ब्रै बाहागोखौ फोजोबदोंमोन.
--------------------------------------------------

Translating:   8%|██▎                         | 84/1000 [01:08<12:28,  1.22it/s]

[84/1000]
EN: Saina Nehwal confirmed her retirement from competitive badminton.
BRX: साइना नेहवालआ बादायलायनाय बेडमिन्टननिफ्राय गावनि सानस्रिनायखौ रोखा खालामदों |
--------------------------------------------------

Translating:   8%|██▍                         | 85/1000 [01:09<11:54,  1.28it/s]

[85/1000]
EN: R. Vaishali won the FIDE Women’s Grand Swiss.
BRX: आर. वैशालीआ एफ.आइ.डि.इ. आयजोफोरनि ग्रेन्ड स्विसखौ देरहादोंमोन |
--------------------------------------------------

Translating:   9%|██▍                         | 86/1000 [01:10<10:54,  1.40it/s]

[86/1000]
EN: R. Praggnanandhaa came from behind to win a game.
BRX: आर. प्रागनानन्दआ मोनसे गेलेमु देरहानो उननिफ्राय फैदोंमोन |
--------------------------------------------------

Translating:   9%|██▍                         | 87/1000 [01:10<10:54,  1.40it/s]

[87/1000]
EN: D. Gukesh as the youngest world chess champion in history.
BRX: डी.गुकेशआ जारिमिनाव बयनिख्रुइ उन्दैसिन बुहुमनां दाबा चेम्पियननि महराव ।
--------------------------------------------------

Translating:   9%|██▍                         | 88/1000 [01:11<10:50,  1.40it/s]

[88/1000]
EN: D. Gukesh secured his first win at Tata Steel Chess Masters 2026.
BRX: डी. गुकेशआ टाटा स्टील चेस मास्टर्स 2026 आव गावनि गिबि देरहासारनायखौ रैखाथि होदोंमोन |
--------------------------------------------------

Translating:   9%|██▍                         | 89/1000 [01:12<11:16,  1.35it/s]

[89/1000]
EN: Avinash Sable became the first Indian man to qualify for the men’s 3000m steeplechase final at Paris Olympics 2024.
BRX: इं 2024 माइथायनि पेरिस अलिम्पिकआव भारत आरो नेपालनि गेजेराव जानाय मेचफोरनि गेजेराव ब्रै खेब फाइनालाव सौहैनो हानाय गिबि गेलेगिरि जानो हाथावना ।
--------------------------------------------------

Translating:   9%|██▌                         | 90/1000 [01:13<11:14,  1.35it/s]

[90/1000]
EN: Mirabai Chanu returned to competition as she prepared for upcoming international events.
BRX: मिराबाइ चानुआ बादायनायाव फैफिनो मानोना बियो जानो गोनां हादोर गेजेरारि गेलेनायफोरनि थाखाय थियारि जादोंमोन.
--------------------------------------------------

Translating:   9%|██▌                         | 91/1000 [01:13<11:32,  1.31it/s]

[91/1000]
EN: Manu Bhaker and Harmanpreet Singh among athletes highlighted in a sports-honours post.
BRX: भारत क्रिकेट टीमनि गाहाय सायख 'जानाय गेलेगिरिफोरनि गेजेराव सासेआ गावस्रानायखौ नोजोर होदों ।
--------------------------------------------------

Translating:   9%|██▌                         | 92/1000 [01:14<12:08,  1.25it/s]

[92/1000]
EN: At the Milan–Cortina Winter Olympics 2026, Ilia Malinin landed a backflip on one skate in an Olympics moment.
BRX: इं 2026 माइथायनि क.र्टिना गोजां बोथोरनि अलिम्पिकआव इलिया मालिनिनआ मोनसे अलम्पिकनि समाव मोनसे स्केटआव बेकफ्लिपआव सौहैदोंमोन |
--------------------------------------------------

Translating:   9%|██▌                         | 93/1000 [01:15<12:14,  1.23it/s]

[93/1000]
EN:  Anastasiia Gubanova delivered a performance featuring Indian cultural elements on the ice in Milan.
BRX: अनास्तासिया गुबानोभाया मिलानआव बरफआव भारतारि हारिमुआरि गुदिमुवाफोरखौ दिन्थिग्रा मोनसे दिन्थिफुंनायखौ होदोंमोन |
--------------------------------------------------

Translating:   9%|██▋                         | 94/1000 [01:16<13:13,  1.14it/s]

[94/1000]
EN: Formula One World Championship could return to Indian soil after a 13-year gap as policy issues are addressed.
BRX: फर्मुला वन बुहुमनां चेम्पियनशिपआ 13 बोसोरनि उनाव भारतनि हायाव फैफिनो मानोना खान्थिनि जेंनाफोरखौ नोजोर होनाय जायो →
--------------------------------------------------

Translating:  10%|██▋                         | 95/1000 [01:17<13:05,  1.15it/s]

[95/1000]
EN: Nikhat Zareen won 5–0 over Guo Yi Xuan in a bout described as a commanding victory.
BRX: बे मेचआव भारत आरो बांग्लादेशनि गेजेराव गेलेबाय थानाय मोन्नै गेलेगिरिफोरनि गेजेराव सासेआ गावनोगावखौ फेजेन्नो हादोंमोन.
--------------------------------------------------

Translating:  10%|██▋                         | 96/1000 [01:18<13:24,  1.12it/s]

[96/1000]
EN: Minakshi Hooda and Jaismine Lamboria upset Paris Olympics medallists and top seeds in a major boxing event.
BRX: भारत आरो फ्रान्सनि गेजेराव जानाय मोनसे गिदिर बादायलायनायनि उनाव, जायफ्रा गावसोरनि गिबि मेचआव बाहागो लानो हागोन ।
--------------------------------------------------

Translating:  10%|██▋                         | 97/1000 [01:19<12:11,  1.23it/s]

[97/1000]
EN: Vinesh Phogat announced a return to wrestling on December 12, 2025.
BRX: विनेश फोगाटआ 12 दिसेम्बर इं 2025 माइथायाव खमलायनायाव फैफिन्नायनि फोसावथाइ होदोंमोन |
--------------------------------------------------

Translating:  10%|██▋                         | 98/1000 [01:19<12:11,  1.23it/s]

[98/1000]
EN: Village spectators watching a kabaddi match organised at a makeshift arena.
BRX: गामिनि नायगिरिफोरा मोनसे अरायथा नङि अखाडायाव खुंजानाय कबड्डी मेचखौ नायगासिनो दंपाटांफोर |
--------------------------------------------------

Translating:  10%|██▊                         | 99/1000 [01:20<11:10,  1.34it/s]

[99/1000]
EN: The 21st Tata Mumbai Marathon took place with large-scale participation in Mumbai.
BRX: 21थि टाटा मुम्बाइ मैराथनआ मुम्बाइआव गोबां बिबांनि बाहागो लाफानायजों जादोंमोन.
--------------------------------------------------

Translating:  10%|██▋                        | 100/1000 [01:21<10:55,  1.37it/s]

[100/1000]
EN: The first-ever Formula 4 car show on Marina Beach was held on the banks of the sea in Chennai.
BRX: मेरिना बीचआव गिबिसिन फर्मुला 4 गारि दिन्थिफुंनाया चेन्नाईआव लैथो रुगुङाव खुंजादोंमोन.
--------------------------------------------------

Translating:  10%|██▋                        | 101/1000 [01:21<11:13,  1.34it/s]

[101/1000]
EN: Tilak Varma said India felt ready for the high-stakes Pakistan match in Colombo.
BRX: भारत आरो पाकिस्ताननि गेजेराव जानाय मेचआव भारतनि हाथरखिखौ बांहोनाय जादों ।
--------------------------------------------------

Translating:  10%|██▊                        | 102/1000 [01:22<11:07,  1.35it/s]

[102/1000]
EN: Tilak Varma said the India squad had entered a focused “match zone” mindset.
BRX: बे मेचनि उनाव भारतआ गावस्रानाय मेचफोरनि सायाव गोसो होदों ।
--------------------------------------------------

Translating:  10%|██▊                        | 103/1000 [01:23<10:13,  1.46it/s]

[103/1000]
EN: Tilak Varma described the India–Pakistan fixture as a major highlight of the tournament.
BRX: भारत आरो पाकिस्ताननि गेजेराव जानाय मेचखौ भारतनि गाहाय गेलेनाय होनना बुंनाय जादों ।
--------------------------------------------------

Translating:  10%|██▊                        | 104/1000 [01:23<09:45,  1.53it/s]

[104/1000]
EN: Tilak Varma emphasized preparation and intensity for India ahead of the Pakistan clash.
BRX: भारत आरो पाकिस्ताननि गेजेराव जानाय बादायलायनायखौ नोजोर होनानै बे मेचखौ जानो हागोन ।
--------------------------------------------------

Translating:  10%|██▊                        | 105/1000 [01:24<10:15,  1.46it/s]

[105/1000]
EN: Tilak Varma framed the Pakistan game as a test of temperament and execution.
BRX: भारत आरो पाकिस्ताननि गेजेराव गेलेबाय थानाय गेलेनायफोरनि गेजेराव मोनसेआ इंलेन्डखौ फेजेन्नो हादोंमोन.
--------------------------------------------------

Translating:  11%|██▊                        | 106/1000 [01:25<10:28,  1.42it/s]

[106/1000]
EN: Delhi Metro extended operating hours to support fans travelling for the India–Namibia match.
BRX: दिल्ली मेट्र 'आ भारतनि नामिबिया मेचनि थाखाय दावबायग्रा फैसाफोरखौ हेफाजाब होनो थाखाय सामलायनायनि समखौ फेहेरदों |
--------------------------------------------------

Translating:  11%|██▉                        | 107/1000 [01:26<10:50,  1.37it/s]

[107/1000]
EN: Delhi Metro added services to manage crowd flow before and after the India–Namibia game.
BRX: दिल्ली मेट्र 'आ भारतनि नामिबिया गेलेनायनि सिगां आरो उनाव होंगो-गोहोनि बोहैनायखौ सामलायनो थाखाय सिबिथाइफोरखौ दाजाबदेरदोंमोन |
--------------------------------------------------

Translating:  11%|██▉                        | 108/1000 [01:27<12:57,  1.15it/s]

[108/1000]
EN: City transport officials coordinated services to reduce congestion around the India–Namibia fixture.
BRX: नोगोर रोगाथाइ मावख 'गिरिफोरा भारतनि सोरगिदिं होंगो-गोखौ बाङाइ खालामनो थाखाय सिबिथाइफोरखौ गोरोबहोदोंमोन |
--------------------------------------------------

Translating:  11%|██▉                        | 109/1000 [01:28<16:06,  1.08s/it]

[109/1000]
EN: Extended metro services aimed to make stadium travel easier for cricket spectators in Delhi.
BRX: भारतनि गाहाय मन्थ्रिफोरनि गेजेराव सासेआ क्रिकेट गेलेग्राखौ सायख 'दोंमोन आरो बिथाङा बुंदोंमोन दि बि. जे. पि. नि गिबि बाहागोआ हादोर गेजेरारि क्रिकेटनि जौगानायखौ बांहोदोंमोन.
--------------------------------------------------

Translating:  11%|██▉                        | 110/1000 [01:29<14:22,  1.03it/s]

[110/1000]
EN: Additional trains were planned to handle the match-day rush for the India–Namibia crowd.
BRX: भारतनि थाखाय मेचनि साननि होंगो-गोखौ सामलायनो थाखाय दाजाबदेरनाय ट्रेनफोरनि बिथांखि लानाय जादोंमोन |
--------------------------------------------------

Translating:  11%|██▉                        | 111/1000 [01:30<12:57,  1.14it/s]

[111/1000]
EN: Rohit Sharma warned India that confidence alone would not win against Pakistan.
BRX: रोहित शर्माया भारतखौ सिगांग्रो खिन्थादोंमोन दि खालि फोथायनाया पाकिस्ताननि बेरेखायै देरहानो हानाय नङा.
--------------------------------------------------

Translating:  11%|███                        | 112/1000 [01:30<11:57,  1.24it/s]

[112/1000]
EN: Rohit Sharma urged India to approach Pakistan with discipline, planning, and composure.
BRX: रोहित शर्माया पाकिस्तानखौ खान्थि आरो दिदोमथिजों मोगा-मोगि खालामनो थाखाय थुलुंगा होदोंमोन |
--------------------------------------------------

Translating:  11%|███                        | 113/1000 [01:31<11:54,  1.24it/s]

[113/1000]
EN: Rohit Sharma cautioned that India–Pakistan games can ignore rankings and recent form.
BRX: भारत आरो पाकिस्ताननि गेजेराव गेलेबाय थानाय मेचफोरनि बादै रोहित शर्माआ नायदोंमोन ।
--------------------------------------------------

Translating:  11%|███                        | 114/1000 [01:32<11:25,  1.29it/s]

[114/1000]
EN: Rohit Sharma stressed mental readiness for India before the Pakistan contest.
BRX: भारत आरो पाकिस्ताननि गेजेराव गेलेबाय थानाय मेचफोरनि थाखाय रोहित शर्माखौ सायख 'नाय जादों ।
--------------------------------------------------

Translating:  12%|███                        | 115/1000 [01:33<11:45,  1.25it/s]

[115/1000]
EN: Rohit Sharma advised India to avoid underestimating Pakistan in the World Cup clash.
BRX: भारत आरो पाकिस्ताननि गेजेराव जानाय बादायलायनायखौ लानानै रोहित शर्माआ बुंदों दि बियो बे मेचखौ गेलेयो ।
--------------------------------------------------

Translating:  12%|███▏                       | 116/1000 [01:34<14:29,  1.02it/s]

[116/1000]
EN: Virat Kohli congratulated India’s Under-19 team after the World Cup final victory.
BRX: अस्ट्रेलियानि गिबि क्रिकेट मेचआव भारतखौ फेजेन्नो हानायाव मदद मोन्नायनि थाखाय बि. जे. पि. नि गाहाय फावगिरि विराट कोहलीआ भारतनि 19 बोसोर सिङावनि टीमखौ बाख्नायदोंमोन |
--------------------------------------------------

Translating:  12%|███▏                       | 117/1000 [01:35<14:05,  1.04it/s]

[117/1000]
EN: India’s Under-19 team won the ICC Under-19 Cricket World Cup final by 100 runs against England.
BRX: भारतनि 19 बोसोर सिङावनि हानजाया इंलेन्डनि बेरेखायै आईसीसी अंडर-19 क्रिकेट मुलुग काप फाइनालखौ 100 रानजों देरहादोंमोन.
--------------------------------------------------

Translating:  12%|███▏                       | 118/1000 [01:36<13:17,  1.11it/s]

[118/1000]
EN: India secured a sixth Under-19 World Cup title with a commanding final performance.
BRX: भारतआ मोनसे कमान्डिं जोबथा दिन्थिफुंनायजों द 'थि अंडर-19 मुलुग काप बिमुंखौ रैखा खालामदोंमोनपाटों ।
--------------------------------------------------

Translating:  12%|███▏                       | 119/1000 [01:36<12:02,  1.22it/s]

[119/1000]
EN: Celebrations followed India’s Under-19 World Cup triumph over England in the title match.
BRX: इंलेन्डनि बेरेखायै भारतनि 19 बोसोर सिङाव बुहुमनां काप देरहासारनायनि उनाव फोर्बोफोर खुंजादोंमोन.
--------------------------------------------------

Translating:  12%|███▏                       | 120/1000 [01:37<11:45,  1.25it/s]

[120/1000]
EN: India’s Under-19 success drew praise from senior players across Indian cricket.
BRX: भारतनि 19 बोसोर सिङावनि जाफुंसारनाया गासै भारतारि क्रिकेटआव गागि गेलेगिरिफोरनिफ्राय बाखनायनाय मोनदोंमोन.
--------------------------------------------------

Translating:  12%|███▎                       | 121/1000 [01:38<11:34,  1.27it/s]

[121/1000]
EN: Dhakshineswar Suresh sparked optimism by delivering a breakthrough stretch for Indian tennis.
BRX: गावस्रानाय गेलेगिरिफोरा गावसोरनि गिबि मेचनि थाखाय गोख्रों गोहोम खोख्लैदोंमोन.
--------------------------------------------------

Translating:  12%|███▎                       | 122/1000 [01:39<12:02,  1.22it/s]

[122/1000]
EN: Dhakshineswar Suresh’s rise has renewed ambition among Indian tennis fans and young players.
BRX: धक्षिनेश्वर सुरेशनि जौगानाया भारतारि टेनिस मोजां मोनग्राफोर आरो लाइमोन गेलेगिरिफोरनि गेजेराव मिजिंथिखौ गोदान खालामफिनदों |
--------------------------------------------------

Translating:  12%|███▎                       | 123/1000 [01:40<12:19,  1.19it/s]

[123/1000]
EN: Dhakshineswar Suresh’s recent results were described as a turning point for Indian tennis.
BRX: धक्षिनेश्वर सुरेशनि बावैसोनि फिथायफोरखौ भारतारि टेनिसनि थाखाय मोनसे सोलायनाय बिन्दो महरै बरनायनाय जादों |
--------------------------------------------------

Translating:  12%|███▎                       | 124/1000 [01:41<11:46,  1.24it/s]

[124/1000]
EN: Dhakshineswar Suresh’s performances lifted expectations for Indian tennis on bigger stages.
BRX: धक्षिनेश्वर सुरेशनि दिन्थिफुंनाया गिदिर जौसांफोराव भारतारि टेनिसनि मिजिंफोरखौ बांहोदोंमोन.
--------------------------------------------------

Translating:  12%|███▍                       | 125/1000 [01:41<11:23,  1.28it/s]

[125/1000]
EN: Dhakshineswar Suresh’s run created fresh belief about India’s potential in men’s tennis.
BRX: सुरेशनि खारनाया हौवाफोरनि टेनिसआव भारतनि गोहोनि बागै थाजिम फोथायथि सोमजिहोदोंमोन.
--------------------------------------------------

Translating:  13%|███▍                       | 126/1000 [01:42<11:03,  1.32it/s]

[126/1000]
EN: India’s men’s team exited in the quarterfinals at the Badminton Asia Team Championships.
BRX: भारतनि हौवाफोरनि हानजाया बेडमिन्टन एसिया टीम चेम्पियनशिपनि क्वार्टर फाइनालाव ओंखारलांदोंमोन.
--------------------------------------------------

Translating:  13%|███▍                       | 127/1000 [01:43<10:26,  1.39it/s]

[127/1000]
EN: India’s women’s team exited in the quarterfinals at the Badminton Asia Team Championships.
BRX: भारतनि आइजो हानजाया बेडमिन्टन एशिया टीम चेम्पियनशिपनि क्वार्टर फाइनलआव ओंखारलांदोंमोन.
--------------------------------------------------

Translating:  13%|███▍                       | 128/1000 [01:43<09:43,  1.49it/s]

[128/1000]
EN: India failed to defend titles after a double quarterfinal exit in the team championships.
BRX: भारतआ बे मेचआव जाफुंसार जानो हानायखौ नुनो मोना ।
--------------------------------------------------

Translating:  13%|███▍                       | 129/1000 [01:44<10:51,  1.34it/s]

[129/1000]
EN: Strong opposition ended India’s campaign early at the Badminton Asia Team Championships.
BRX: भारत आरो बांग्लादेशनि गेजेराव जानाय बादायलायनायफोरनि गेजेराव मोनसेआ जानो हागौ ।
--------------------------------------------------

Translating:  13%|███▌                       | 130/1000 [01:45<10:52,  1.33it/s]

[130/1000]
EN: The quarterfinal losses ended India’s hopes of a title defence at the event.
BRX: कवार्टर फाइनालाव जेननाया भारतनि टाइटेल डिफेन्सनि मिजिंखौ फोजोबदोंमोन.
--------------------------------------------------

Translating:  13%|███▌                       | 131/1000 [01:46<10:36,  1.37it/s]

[131/1000]
EN: Sumit Nagal was scheduled to open his tournament campaign against Guy Den Ouden.
BRX: भारत आरो बांग्लादेशनि गेजेराव गेलेबाय थानाय बादायलायनायफोरनि गेजेराव मोनसेआ जानो हागौ ।
--------------------------------------------------

Translating:  13%|███▌                       | 132/1000 [01:46<10:38,  1.36it/s]

[132/1000]
EN: Sumit Nagal drew Dutch player Guy Den Ouden in an opening-round matchup.
BRX: भारत आरो नेपालनि गेजेराव गेलेबाय थानाय मेचआ इंलेन्डखौ फेजेन्नो हानायाव जाफुंसारदों ।
--------------------------------------------------

Translating:  13%|███▌                       | 133/1000 [01:47<11:02,  1.31it/s]

[133/1000]
EN: Sumit Nagal’s first-round pairing set up an early test against Guy Den Ouden.
BRX: इंलेन्डनि बि. जे. पि. नि गिबि मेचआव भारतखौ फेजेन्दोंमोन ।
--------------------------------------------------

Translating:  13%|███▌                       | 134/1000 [01:48<11:36,  1.24it/s]

[134/1000]
EN: Sumit Nagal prepared for a fresh challenge against Guy Den Ouden in round one.
BRX: भारत आरो नेपालनि गेजेराव जानाय मेचफोरनि गेजेराव मोनसेआ जानो हाथावनामोन ।
--------------------------------------------------

Translating:  14%|███▋                       | 135/1000 [01:49<11:54,  1.21it/s]

[135/1000]
EN: Sumit Nagal began a new event with an opening match against Guy Den Ouden.
BRX: गाव हारसिङैनो गेलेबाय थानाय समाव बे मेचआव सासे गेलेगिरिखौ नुनो मोनो ।
--------------------------------------------------

Translating:  14%|███▋                       | 136/1000 [01:50<12:58,  1.11it/s]

[136/1000]
EN: An analysis said T20 cricket keeps evolving through new strategies and fast-changing trends.
BRX: मोनसे बिजिरसंनाया बुंदों दि टि20 क्रिकेटआ गोदान सोलोफोर आरो गोख्रैयै सोलायनाय ट्रेन्ड्सनि गेजेरजों जौगाबाय थायो |
--------------------------------------------------

Translating:  14%|███▋                       | 137/1000 [01:51<12:07,  1.19it/s]

[137/1000]
EN: A feature noted the ICC Men's T20 World Cup returned to India after a decade-long gap.
BRX: इं 2020 माइथायनि नैथि टेस्टआव भारतखौ फेजेन्नो थाखाय बे मेचआ मोनसे मोजां खाबु होदों ।
--------------------------------------------------

Translating:  14%|███▋                       | 138/1000 [01:52<13:23,  1.07it/s]

[138/1000]
EN: T20 cricket was described as a format that continually reinvents tactics and team plans.
BRX: टि20 क्रिकेटखौ ओरैबायदि मोनसे फरमेट महरै बरनायनाय जादों जाय जेब्लाबो सोलो आरो हानजानि बिथांखिफोरखौ गोदान गोदान दिहुनफिनदों |
--------------------------------------------------

Translating:  14%|███▊                       | 139/1000 [01:53<13:02,  1.10it/s]

[139/1000]
EN: A commentary highlighted how technology and data shape modern T20 decision-making.
BRX: मोनसे बुंफुरलुआ दिनथिफुंदोंमोन दि माबोरै बिरोंदामिन आरो खारिआ गोदान मुगानि टि20 थिरांथा लानायखौ महर होयो |
--------------------------------------------------

Translating:  14%|███▊                       | 140/1000 [01:53<12:02,  1.19it/s]

[140/1000]
EN: A tournament preview underlined T20 cricket’s cultural impact and mass appeal in India.
BRX: मोनसे टुर्नामेन्ट प्रिभिउआ भारताव टि20 क्रिकेटनि हारिमुआरि गोहोम आरो सुबुं गोसो बोनो हानायखौ दिन्थियो |
--------------------------------------------------

Translating:  14%|███▊                       | 141/1000 [01:54<12:08,  1.18it/s]

[141/1000]
EN: Kapil Dev was listed among participants at the PM Rungta Memorial Golf Cup in Jaipur.
BRX: कपिल देवखौ जयपुरआव पि. एम. रुंगाटा मेम 'रियेल गल्फ कापआव बाहागो लागिरिफोरनि गेजेराव फारिलाइ खालामनाय जादोंमोन |
--------------------------------------------------

Translating:  14%|███▊                       | 142/1000 [01:55<12:25,  1.15it/s]

[142/1000]
EN: Madan Lal was listed among participants at the PM Rungta Memorial Golf Cup in Jaipur.
BRX: मदन लालखौ जयपुरआव पि. एम. रुंगटा मेम 'रियेल गल्फ कापआव बाहागो लागिरिफोरनि गेजेराव फारिलाइ खालामनाय जादोंमोन |
--------------------------------------------------

Translating:  14%|███▊                       | 143/1000 [01:56<13:39,  1.05it/s]

[143/1000]
EN: The PM Rungta Memorial Golf Cup was scheduled for February 8, 2026 in Jaipur.
BRX: पि. एम. रुंगटा मेम 'रियेल गल्फ कापआ 8 फेब्रुआरि 2026 मायथाइयाव जयपुरआव थि खालाम जादोंमोन |
--------------------------------------------------

Translating:  14%|███▉                       | 144/1000 [01:57<12:04,  1.18it/s]

[144/1000]
EN: Rambagh Golf Club was named as the venue for the memorial golf tournament.
BRX: रामबाग गल्फ क्लाबखौ गोसोखांथाव गल्फ टुर्नामेन्टनि थावनि महरै मुं होनाय जादोंमोन |
--------------------------------------------------

Translating:  14%|███▉                       | 145/1000 [01:58<12:39,  1.13it/s]

[145/1000]
EN: Organisers said the golf cup used a Stableford Single Peoria format for inclusive competition.
BRX: खुंगिरिफोरा बुंदोंमोन दि गल्फ कापआ लाफादेरनाय बादायलायनायनि थाखाय स्टेबलफोर्ड सिङ्गल पिय 'रिया फरमेट बाहायदोंमोन.
--------------------------------------------------

Translating:  15%|███▉                       | 146/1000 [01:59<13:05,  1.09it/s]

[146/1000]
EN: A schedule note said United States would face Netherlands in Chennai to close February 13’s action.
BRX: मोनसे समफारि नटआव बुंनाय जादोंमोन दि जुथाइ रायजो आमेरिकाया 13 फेब्रुआरिनि एक्शनखौ फोजोबनो थाखाय चेन्नाईआव नेदारलेन्डजों मोगा-मोगि जागोन |
--------------------------------------------------

Translating:  15%|███▉                       | 147/1000 [02:00<12:48,  1.11it/s]

[147/1000]
EN: The USA–Netherlands match was presented as important for points and pride in the group.
BRX: यु. एस. ए. - नेदारलेन्डनि मेचखौ पइन्ट आरो ग्रुपआव गोग्गानायनि थाखाय गोनांथार महरै दिन्थिनाय जादोंमोन |
--------------------------------------------------

Translating:  15%|███▉                       | 148/1000 [02:01<13:43,  1.03it/s]

[148/1000]
EN: A match preview framed USA against Netherlands as a tight contest between associate nations.
BRX: मोनसे मेच प्रिभिउआ नेदारलेन्डनि बेरेखायै एसोसिएट हादोरफोरनि गेजेराव मोनसे गोब्राब बादायलायनाय महरै यु. एस. ए. खौ महर होदोंमोन |
--------------------------------------------------

Translating:  15%|████                       | 149/1000 [02:02<12:55,  1.10it/s]

[149/1000]
EN: A schedule roundup highlighted February 13 fixtures as key for shaping group standings.
BRX: मोनसे समफारि राउन्डआपआ 13 फेब्रुआरिनि फिक्सारफोरखौ ग्रुप स्टेन्दिंखौ महर होनायनि थाखाय गोनांथार महरै दिन्थिदोंमोन |
--------------------------------------------------

Translating:  15%|████                       | 150/1000 [02:02<12:24,  1.14it/s]

[150/1000]
EN: A preview said the final February 13 match would be played at MA Chidambaram Stadium.
BRX: मोनसे प्रिभिउआव बुंनाय जादोंमोन दि 13 फेब्रुआरिनि जोबथा मेचखौ एमए चिदम्बरम स्टेडियामाव गेलेनाय जागोन.
--------------------------------------------------

Translating:  15%|████                       | 151/1000 [02:03<11:38,  1.22it/s]

[151/1000]
EN: Indian Super League clubs requested a pause on relegation for three to five years.
BRX: भारतारि सुपार लीग क्लाबफोरा थामनिफ्राय बा बोसोरनि थाखाय रेलिगेशनखौ थाद 'नो थाखाय आरज गाबदोंमोन.
--------------------------------------------------

Translating:  15%|████                       | 152/1000 [02:04<14:01,  1.01it/s]

[152/1000]
EN: ISL clubs argued that pausing relegation would provide stability for long-term planning.
BRX: आइ.एस.एल. क्लाबफोरा बाथ्रा दान्थेलायदोंमोन दि रेलिगेशनखौ थाद 'नाया गोलाव समनि सानथांखिनि थाखाय दिदोमथि जगायगोनपाटिनो ।
--------------------------------------------------

Translating:  15%|████▏                      | 153/1000 [02:05<13:13,  1.07it/s]

[153/1000]
EN: Several ISL teams asked administrators to consider a temporary relegation freeze.
BRX: गोबां आई.एस.एल. टीमफोरा खुंगिरिफोरखौ अरायथा नङै रिलिगेसन फ्रीजखौ गनायनो थिनदोंमोन |
--------------------------------------------------

Translating:  15%|████▏                      | 154/1000 [02:06<12:29,  1.13it/s]

[154/1000]
EN: The request on relegation was framed as a measure to protect club investments.
BRX: क्लाब रां थिसननायखौ रैखा खालामनो थाखाय मोनसे राहा महरै रेलिगेशननि थाखाय आरज गाबनाय जादोंमोन.
--------------------------------------------------

Translating:  16%|████▏                      | 155/1000 [02:07<12:25,  1.13it/s]

[155/1000]
EN: ISL stakeholders debated relegation rules while seeking clarity for the 2025–26 season.
BRX: आइ. एस. एल. नि बाहागो लागिरिफोरा 2025/26 सिजननि थाखाय रोखाथि नागिरना रेलिगेशन नेमफोरखौ सावरायदोंमोन |
--------------------------------------------------

Translating:  16%|████▏                      | 156/1000 [02:08<11:31,  1.22it/s]

[156/1000]
EN: India produced a 3–2 win over Netherlands in Davis Cup Qualifiers Round 1.
BRX: भारतआ डेभिस काप क्वालीफायार राउन्ड 1 आव नेदारलेन्डनि सायाव 3/2 देरहादोंमोन.
--------------------------------------------------

Translating:  16%|████▏                      | 157/1000 [02:08<11:17,  1.24it/s]

[157/1000]
EN: India advanced to the second Davis Cup qualifying round after beating Netherlands 3–2.
BRX: भारतआ नेदारलेन्डखौ 3/2 जों फेजेननायनि उनाव नैथि डेविस काप क्वालीफाइं राउन्डसिम दावगालांगासिनो दं ।
--------------------------------------------------

Translating:  16%|████▎                      | 158/1000 [02:09<10:56,  1.28it/s]

[158/1000]
EN: India’s Davis Cup team was described as thriving against higher-ranked opponents recently.
BRX: भारतनि डेविस काप टीमखौ बावैसो गोजौ थाखोनि हेंथा गेलेगिरिफोरनि बेरेखायै जौगाफुनाय महरै बरनायनाय जादों |
--------------------------------------------------

Translating:  16%|████▎                      | 159/1000 [02:10<10:18,  1.36it/s]

[159/1000]
EN: The Davis Cup tie at SM Krishna Tennis Stadium went down to the wire.
BRX: एस.एम. कृष्णा टेनिस स्टेडियामाव डेविस काप टाइआ तारआव गोग्लैदोंमोन |
--------------------------------------------------

Translating:  16%|████▎                      | 160/1000 [02:10<10:08,  1.38it/s]

[160/1000]
EN: India’s Davis Cup success followed an earlier victory over Switzerland in Biel last year.
BRX: भारतनि डेविस काप जाफुंसारनाया थांनाय बोसोराव सुइजारलेन्डनि सायाव सिगांनि देरहासारनायखौ उनसंदोंमोन |
--------------------------------------------------

Translating:  16%|████▎                      | 161/1000 [02:11<09:38,  1.45it/s]

[161/1000]
EN: The India Open was kept as a Super 750 tournament for the 2027–2030 cycle.
BRX: भारत अपेनखौ 2027/2030 साइकेलनि थाखाय सुपार 750 टुर्नामेन्ट महरै दोननाय जादोंमोन |
--------------------------------------------------

Translating:  16%|████▎                      | 162/1000 [02:12<09:06,  1.53it/s]

[162/1000]
EN: Players criticised conditions, yet organisers retained the India Open’s Super 750 status.
BRX: गेलेगिरिफोरा गावसोरनि गिबि मेचआव भारतखौ आवगायनो थाखाय गोसो होदों ।
--------------------------------------------------

Translating:  16%|████▍                      | 163/1000 [02:13<10:16,  1.36it/s]

[163/1000]
EN: Badminton World Federation announced a revamped World Tour structure with six tournament levels.
BRX: बेडमिन्टन वर्ल्ड फेडारेशना द'टुर्नामेन्ट थाखोफोरजों मोनसे फोसाबनाय बुहुमनां दावबायनाय दाथायखौ फोसावदोंमोनपाटों ।
--------------------------------------------------

Translating:  16%|████▍                      | 164/1000 [02:13<10:30,  1.33it/s]

[164/1000]
EN: The BWF updated World Tour plan included 36 tournaments across multiple tiers.
BRX: बी.डब्ल्यू.एफ.आ गोदानसिन खालामनाय बुहुमनां दावबायनाय बिथांखियाव गोबां थाखोफोराव 36 टुर्नामेन्टफोर दंमोन |
--------------------------------------------------

Translating:  16%|████▍                      | 165/1000 [02:14<11:07,  1.25it/s]

[165/1000]
EN: The BWF said annual World Tour prize money would rise to about 26.9 million dollars.
BRX: बी.डब्ल्यू.एफ.आ बुंदोंमोन दि बोसोरारि बुहुमनां दावबायनाय बान्था राङा फ्राय 26.9 मिलियन डलारसिम बांगोन ꯫
--------------------------------------------------

Translating:  17%|████▍                      | 166/1000 [02:15<11:03,  1.26it/s]

[166/1000]
EN: A schedule preview listed Sri Lanka against Oman as a February 12 group-stage fixture.
BRX: श्रीलंकानि गिबि मेचआ इं 2020 माइथायनि 12 फेब्रुआरि खालि जानो हागौ ।
--------------------------------------------------

Translating:  17%|████▌                      | 167/1000 [02:16<11:07,  1.25it/s]

[167/1000]
EN: A schedule preview listed Nepal against Italy as a February 12 group-stage fixture.
BRX: मोनसे समफारि प्रिभिउआव इटालीनि बेरेखायै 12 फेब्रुआरिनि ग्रुप-स्टेज मेच महरै नेपालखौ फारिलाइ खालामनाय जादों |
--------------------------------------------------

Translating:  17%|████▌                      | 168/1000 [02:17<10:52,  1.27it/s]

[168/1000]
EN: A schedule preview listed India against Namibia as a February 12 group-stage fixture.
BRX: मोनसे समफारि प्रिभिउआव नामिबियानि बेरेखायै 12 फेब्रुआरिनि ग्रुप-स्टेज मेच महरै भारतखौ फारिलाइ खालामनाय जादों |
--------------------------------------------------

Translating:  17%|████▌                      | 169/1000 [02:17<10:43,  1.29it/s]

[169/1000]
EN: Wanindu Hasaranga was ruled out of the World Cup due to an injury setback.
BRX: भारत आरो श्रीलंका गेजेराव जानाय मेचफोरनि गेजेराव मोनसेआ जानो हाथावनामोन ।
--------------------------------------------------

Translating:  17%|████▌                      | 170/1000 [02:18<10:45,  1.29it/s]

[170/1000]
EN: Sri Lanka named Dushan Hemantha as a replacement after Wanindu Hasaranga’s injury.
BRX: श्रीलंकाया भारतखौ आवग्रिना गावस्रालांनाय लोगोफोरखौ सायख 'दों ।
--------------------------------------------------

Translating:  17%|████▌                      | 171/1000 [02:19<10:31,  1.31it/s]

[171/1000]
EN: The Indian Super League season was announced to begin on February 14, 2026.
BRX: भारतारि सुपार लीग सिजनखौ 14 फेब्रुआरि.2026 मायथाइनिफ्राय जागायजेन्नाय होनना फोसावनाय जादों |
--------------------------------------------------

Translating:  17%|████▋                      | 172/1000 [02:20<10:43,  1.29it/s]

[172/1000]
EN: Sports minister Mansukh Mandaviya announced an ISL start date of February 14.
BRX: स्पोर्ट्स मिनिस्ट्रि एमएस धोनीआ 14 फेब्रुआरिआव आइ. एस. एल. नि जागायजेन्नायनि अक्ट 'खौ फोसावनाय जादों ।
--------------------------------------------------

Translating:  17%|████▋                      | 173/1000 [02:20<11:02,  1.25it/s]

[173/1000]
EN: All 14 clubs agreed to participate in the Indian Super League season, according to reports.
BRX: भारतारि क्रिकेट एसोसिएशननि (आई.एल.एफ.आ ) गाहाय मावख 'गिरिजों रायज्लायनो थाखाय थि खालामनाय जादों ।
--------------------------------------------------

Translating:  17%|████▋                      | 174/1000 [02:21<11:35,  1.19it/s]

[174/1000]
EN: The ISL decision followed meetings between the sports ministry and the All India Football Federation.
BRX: आइ.एस.एल.नि थिरांथाआ गेलेमु मन्थ्रि बिफान आरो अल इन्डिया फुटबल फेडारेशन्नि गेजेराव जानाय जथुमफोरनि उनाव लानाय जादोंमोन |
--------------------------------------------------

Translating:  18%|████▋                      | 175/1000 [02:22<11:06,  1.24it/s]

[175/1000]
EN: Indian football’s top-tier season moved forward after clubs accepted the participation plan.
BRX: क्लाबफोरा बाहागो लानायनि बिथांखिखौ नाजावखांनायनि उनाव भारतारि फुटबलनि गोजौसिन थाखोनि सिजनआ सिगांथिं दावगालांगासिनो दंमोन.
--------------------------------------------------

Translating:  18%|████▊                      | 176/1000 [02:23<10:49,  1.27it/s]

[176/1000]
EN: India’s women lost 0–3 to China in the Badminton Asia Team Championships quarterfinals.
BRX: भारतनि आयजोफोरा बेडमिन्टन एसिया टीम चेम्पियनशिपनि क्वार्टर फाइनालाव चिनजों 0/3 जों जेनदोंमोन.
--------------------------------------------------

Translating:  18%|████▊                      | 177/1000 [02:24<11:10,  1.23it/s]

[177/1000]
EN: P. V. Sindhu missed the team quarterfinal because of a minor injury, according to reports.
BRX: भारत आरो पाकिस्ताननि गेजेराव गेलेबाय थानाय मोन्नैबो गेलेगिरिफोरनि गेजेराव सासेआ पि. भि. सिन्धुनि सायाव गोहोम खोख्लैयो ।
--------------------------------------------------

Translating:  18%|████▊                      | 178/1000 [02:25<11:08,  1.23it/s]

[178/1000]
EN: India’s women struggled to defend the 2024 title without PV Sindhu in the lineup.
BRX: भारतनि आयजोफोरा लाइनआपआव पि. भि. सिन्धु गैयालासे 2024 नि टाइटेलखौ रैखा खालामनो जुजिदोंमोन |
--------------------------------------------------

Translating:  18%|████▊                      | 179/1000 [02:25<10:27,  1.31it/s]

[179/1000]
EN: China ended India’s women’s title defence with a straight 3–0 quarterfinal win.
BRX: चीनआ भारतनि आयजोफोरनि टाइटेल डिफेन्सखौ थोंजों 3:0 क्वार्टर फाइनाल देरहाजों फोजोबदों |
--------------------------------------------------

Translating:  18%|████▊                      | 180/1000 [02:26<10:20,  1.32it/s]

[180/1000]
EN: The quarterfinal defeat closed India’s women’s campaign at the Badminton Asia Team Championships.
BRX: कवार्टर फाइनालाव जेननाया बेडमिन्टन एशिया टीम चेम्पियनशिपआव भारतनि आइजोफोरनि केम्पेनखौ फोजोबदोंमोन.
--------------------------------------------------

Translating:  18%|████▉                      | 181/1000 [02:27<10:54,  1.25it/s]

[181/1000]
EN: Devika Sihag won the Thailand Masters 2026 to claim a BWF Super 300 title.
BRX: देविका सिहागआ थाइलेन्ड मास्टर्स 2026 आव बी.डब्ल्यू.एफ. सुपार 300 बिमुं मोननो थाखाय देरहादोंमोन |
--------------------------------------------------

Translating:  18%|████▉                      | 182/1000 [02:28<11:48,  1.15it/s]

[182/1000]
EN: Devika Sihag became the youngest Indian woman to win a BWF Super 300 singles title.
BRX: देविका सिहागआ बी.डब्ल्यू.एफ. सुपार 300 सिंगल्स टाइटेल देरहानो हानाय बयनिख्रुइ उन्दैसिन भारतारि आइजो जादोंमोनपाटिया ।
--------------------------------------------------

Translating:  18%|████▉                      | 183/1000 [02:29<11:41,  1.16it/s]

[183/1000]
EN: Devika Sihag joined Saina Nehwal and PV Sindhu in an exclusive Indian milestone list.
BRX: देविका सिहागआ साइना नेहवाल आरो पि. भि. सिन्धुनि मोनसे जुनिया भारतारि माइलस्टोन लिस्टआव लोगो जादोंमोन |
--------------------------------------------------

Translating:  18%|████▉                      | 184/1000 [02:29<11:14,  1.21it/s]

[184/1000]
EN: Devika Sihag’s Bangkok celebration marked a breakthrough moment for Indian women’s singles.
BRX: देविका सिहागनि बेंकक फोरबोआ भारतारि आइजो सिंगल्सनि थाखाय मोनसे जाफुंसार बुब्लिखौ सिनायथि होदों |
--------------------------------------------------

Translating:  18%|████▉                      | 185/1000 [02:30<10:42,  1.27it/s]

[185/1000]
EN: Devika Sihag’s title was described as a quiet announcement of a new Indian badminton star.
BRX: देविका सिहागनि टाइटेलखौ गोदान भारतारि बेडमिन्टन स्टारनि सिरि फोसावनाय महरै बरनायनाय जादोंमोन |
--------------------------------------------------

Translating:  19%|█████                      | 186/1000 [02:31<10:32,  1.29it/s]

[186/1000]
EN: A matchday note listed Afghanistan against South Africa in Ahmedabad on February 11.
BRX: इं 2020 माइथायनि 11 फेब्रुआरि खालि आफगानिस्ताननि थाखाय मोनसे प्लेइंग इलेवन ।
--------------------------------------------------

Translating:  19%|█████                      | 187/1000 [02:32<10:39,  1.27it/s]

[187/1000]
EN: A matchday note listed Australia against Ireland as another February 11 group-stage fixture.
BRX: मोनसे मेचनि साननि नटआव आयरलेन्डनि बेरेखायै आरोबाव 11 फेब्रुआरिनि ग्रुप-स्टेज मेच महरै अस्ट्रेलियाखौ फारिलाइ खालामनाय जादों |
--------------------------------------------------

Translating:  19%|█████                      | 188/1000 [02:33<10:52,  1.24it/s]

[188/1000]
EN: A matchday note listed England against West Indies as a February 11 evening fixture.
BRX: मोनसे मेचनि साननि नटआव इंलेन्डखौ 11 फेब्रुआरिनि बेलासियाव वेस्टइन्डीजनि बेरेखायै गेलेनाय महरै फारिलाइ खालामनाय जादों |
--------------------------------------------------

Translating:  19%|█████                      | 189/1000 [02:33<09:59,  1.35it/s]

[189/1000]
EN: Afghanistan sought a rebound after losing their opener against New Zealand, according to reports.
BRX: आफगानिस्तानआ गावसिनि गिबि मेचआव जेन्नायजों मोगा-मोगि जादों ।
--------------------------------------------------

Translating:  19%|█████▏                     | 190/1000 [02:34<09:59,  1.35it/s]

[190/1000]
EN: The February 11 schedule mixed former champions, contenders, and dangerous underdogs in group play.
BRX: अस्ट्रेलियानि गिबि क्रिकेट मेचआ इं 2020 माइथायनि 11 फेब्रुआरि खालि जानो हागौ ।
--------------------------------------------------

Translating:  19%|█████▏                     | 191/1000 [02:37<19:38,  1.46s/it]

[191/1000]
EN: Baichung Bhutia blamed administration after Churchill Brothers were not added to ISL 2025–26.
BRX: इं 2025 माइथायनि आइ. एस. एल. आव चर्चिल ब्रादार्सखौ सोफादेरनायनि उनाव बाइचुंग भुटियाआ खुंथायखौ दाय होदोंमोन |
--------------------------------------------------

Translating:  19%|█████▏                     | 192/1000 [02:38<17:36,  1.31s/it]

[192/1000]
EN: Churchill Brothers were not included in ISL 2025–26, prompting criticism from Baichung Bhutia.
BRX: ब्रुसेल्सआ इं 2025 मायथाइआव अस्ट्रेलियानि बि. जे. पि. नि गाहाय मासि लाजेनदों ।
--------------------------------------------------

Translating:  19%|█████▏                     | 193/1000 [02:39<15:39,  1.16s/it]

[193/1000]
EN: Baichung Bhutia called the Churchill Brothers exclusion a clear administrative failure.
BRX: बाइचुंग भुटियाआ चर्चिल ब्रादार्सखौ एंगारनायखौ मोनसे रोखा खुंथायारि फेलें होन्ना बुंदोंमोनपाटों ।
--------------------------------------------------

Translating:  19%|█████▏                     | 194/1000 [02:40<14:44,  1.10s/it]

[194/1000]
EN: The Churchill Brothers decision raised questions about the league’s selection and governance.
BRX: चर्चिल ब्रादार्सनि थिरांथाआ लीगनि सायख 'नाय आरो सासन खालामनायनि बागै सोंथिफोर जौगाहोदोंमोन |
--------------------------------------------------

Translating:  20%|█████▎                     | 195/1000 [02:41<13:21,  1.00it/s]

[195/1000]
EN: The ISL debate intensified after the Churchill Brothers issue surfaced in public comments.
BRX: अस्ट्रेलियानि गिबि क्रिकेट मेचआ इं 2020 माइथायनि गेजेरसिम दावगालांनो गोनां जादोंमोन.
--------------------------------------------------

Translating:  20%|█████▎                     | 196/1000 [02:41<12:07,  1.11it/s]

[196/1000]
EN: India–Netherlands Davis Cup tie tightened after Sumit Nagal suffered a setback.
BRX: भारत आरो नेपालनि गेजेराव गेलेबाय थानाय मेचआ इंलेन्डखौ फेजेन्नो गोनां जादों ।
--------------------------------------------------

Translating:  20%|█████▎                     | 197/1000 [02:42<12:06,  1.10it/s]

[197/1000]
EN: Sumit Nagal’s result added pressure as the Davis Cup tie moved toward a tense finish.
BRX: बे मेचआव भारतखौ फेजेन्नो हानाय गेलेनायखौ नुनो मोनदों ।
--------------------------------------------------

Translating:  20%|█████▎                     | 198/1000 [02:43<11:04,  1.21it/s]

[198/1000]
EN: India and Netherlands remained locked in a close Davis Cup contest after the Nagal match.
BRX: भारत आरो नेदारलेन्डआ डेभिस काप मेचनि उनाव खाथिथाराव थाबथादोंमोन.
--------------------------------------------------

Translating:  20%|█████▎                     | 199/1000 [02:43<10:07,  1.32it/s]

[199/1000]
EN: The Davis Cup tie needed late composure after the Sumit Nagal setback, according to reports.
BRX: भारत आरो श्रीलंका गेजेराव जानाय मेचफोरनि गेजेराव गिबि खेब गावस्रानायखौ नुनो मोनदों ।
--------------------------------------------------

Translating:  20%|█████▍                     | 200/1000 [02:44<10:19,  1.29it/s]

[200/1000]
EN: The Bengaluru Davis Cup atmosphere stayed intense as India fought Netherlands in a tight tie.
BRX: बेंगलुरूनि डेविस कापनि बारहावाया गोख्रों जाना थादोंमोन मानोना भारतआ नेदारलेन्डजों गोख्रों टाइआव मोगा-मोगि जादोंमोन.
--------------------------------------------------

Translating:  20%|█████▍                     | 201/1000 [02:45<10:16,  1.30it/s]

[201/1000]
EN: International Cricket Council confirmed the 2026 Men’s T20 World Cup starts on February 7.
BRX: हादोर गेजेरारि क्रिकेट आफादआ 7 फेब्रुआरिनिफ्राय 2026 मायथाइनि हौवाफोरनि टि20 मुलुग कापखौ थि खालामदों ।
--------------------------------------------------

Translating:  20%|█████▍                     | 202/1000 [02:46<10:24,  1.28it/s]

[202/1000]
EN: India were placed in Group A alongside Pakistan, Netherlands, USA, and Namibia.
BRX: भारतखौ ग्रुप ए आव पाकिस्तान, नेदारलेन्ड, इउ. एस. ए. आरो नामिबियाजों लोगोसे दोननाय जादों ।
--------------------------------------------------

Translating:  20%|█████▍                     | 203/1000 [02:47<10:13,  1.30it/s]

[203/1000]
EN: Sri Lanka hosted several matches as the tournament ran across India and Sri Lanka venues.
BRX: श्रीलंकाया गोबां मेचफोरखौ खुंदोंमोन मानोना टुर्नामेन्टआ भारत आरो श्रीलंकानि थावनिफोराव खारदोंमोन.
--------------------------------------------------

Translating:  20%|█████▌                     | 204/1000 [02:47<09:53,  1.34it/s]

[204/1000]
EN: India played the opening match against the USA at Wankhede Stadium in Mumbai.
BRX: भारतआ मुम्बाइनि वानखेड़े स्टेडियामआव आमेरिकानि बेरेखायै गिबि मेच गेलेदोंमोन.
--------------------------------------------------

Translating:  20%|█████▌                     | 205/1000 [02:48<09:59,  1.33it/s]

[205/1000]
EN: India faced Namibia on February 12 at Arun Jaitley Stadium in New Delhi.
BRX: भारतआ 12 फेब्रुआरि खालि गोदान दिल्लीनि अरुण जेतली स्टेडियामाव नामिबियाजों मोगा-मोगि जादोंमोन.
--------------------------------------------------

Translating:  21%|█████▌                     | 206/1000 [02:49<09:30,  1.39it/s]

[206/1000]
EN: India travelled to Colombo to play Pakistan in a group-stage match.
BRX: भारतआ मोनसे ग्रुप-स्टेज मेचआव पाकिस्तानजों गेलेनो थाखाय कलम्बोसिम दावबायदोंमोन.
--------------------------------------------------

Translating:  21%|█████▌                     | 207/1000 [02:49<08:54,  1.48it/s]

[207/1000]
EN: Pakistan versus Netherlands was listed as a Group A fixture on February 7.
BRX: पाकिस्तानखौ 7 फेब्रुआरिआव ग्रुप ए नि मोनसे गेलेनाय महरै फारिलाइ खालामनाय जादोंमोन |
--------------------------------------------------

Translating:  21%|█████▌                     | 208/1000 [02:50<09:15,  1.43it/s]

[208/1000]
EN: India versus USA was scheduled as a Group A match on February 7.
BRX: भारत आरो इउ. एस. ए. नि गेजेराव जानाय मेचखौ 7 फेब्रुआरिआव थि खालामनाय जादों ।
--------------------------------------------------

Translating:  21%|█████▋                     | 209/1000 [02:51<09:24,  1.40it/s]

[209/1000]
EN: Group D fixtures began with Afghanistan playing New Zealand on February 8 in Chennai.
BRX: आफगानिस्तानआ 8 फेब्रुआरिआव चेन्नाईआव निउजिलेन्डजों गेलेनायजों ग्रुप डी फिक्सारखौ जागायदोंमोन |
--------------------------------------------------

Translating:  21%|█████▋                     | 210/1000 [02:51<09:26,  1.39it/s]

[210/1000]
EN: Canada played South Africa on February 9 at Narendra Modi Stadium in Ahmedabad.
BRX: इं 2020 माइथायनि 9 फेब्रुआरि खालि अहमदाबादनि नरेन्द्र मोदी स्टेडियामाव गेलेदोंमोन.
--------------------------------------------------

Translating:  21%|█████▋                     | 211/1000 [02:52<09:33,  1.38it/s]

[211/1000]
EN: Ishan Kishan smashed 61 off 24 balls against Namibia in New Delhi.
BRX: भारत आरो नेपालनि गेजेराव गेलेबाय थानाय मेचफोरनि गेजेराव मोनसेआ जानो हागौ ।
--------------------------------------------------

Translating:  21%|█████▋                     | 212/1000 [02:53<09:19,  1.41it/s]

[212/1000]
EN: Hardik Pandya featured prominently as India posted 209 for nine against Namibia.
BRX: भारतनि गिबि टेस्ट मेचनि जोबथा मेचआव भारतआ 9 विकेटआव 209 रान बानायदों ।
--------------------------------------------------

Translating:  21%|█████▊                     | 213/1000 [02:54<09:54,  1.32it/s]

[213/1000]
EN: Varun Chakaravarthy took three wickets as India beat Namibia by 93 runs.
BRX: भारतआ गावस्रानाय मेचआव गिबि खेब गेलेयो ।
--------------------------------------------------

Translating:  21%|█████▊                     | 214/1000 [02:54<09:24,  1.39it/s]

[214/1000]
EN: India bundled out Namibia for 116 while defending a target of 210.
BRX: भारतआ नामिबियाखौ 210 नि थांखिखौ रैखा खालामनानै 116 रानआव अलआउट खालामो →
--------------------------------------------------

Translating:  22%|█████▊                     | 215/1000 [02:55<09:24,  1.39it/s]

[215/1000]
EN: Namibia captain Gerhard Erasmus won the toss and chose to bat first.
BRX: नामिबियानि केप्टेइन गेरहार्ड इरासमसआ टस देरहादोंमोन आरो गिबियाव बेटिं खालामनो थिरांथा लादोंमोन.
--------------------------------------------------

Translating:  22%|█████▊                     | 216/1000 [02:56<09:10,  1.42it/s]

[216/1000]
EN: India versus Namibia started at 7:00 PM IST at Arun Jaitley Stadium.
BRX: भारत बनाम नामिबियाआ 7:00 रिंगानि समाव अरुण जेतली स्टेडियामआव जागायजेनो →
--------------------------------------------------

Translating:  22%|█████▊                     | 217/1000 [02:56<08:34,  1.52it/s]

[217/1000]
EN: India’s first match was a win against the USA in Mumbai.
BRX: भारतनि गिबि मेचआ अमेरिकानि बेरेखायै मुंबईआव मोनसे देरहासारनायमोन.
--------------------------------------------------

Translating:  22%|█████▉                     | 218/1000 [02:57<08:02,  1.62it/s]

[218/1000]
EN: India versus Namibia was labelled as game 18 of the tournament.
BRX: भारत बनाम नामिबियाखौ टुर्नामेन्टनि गेम 18 महरै लेबेल खालामनाय जादोंमोन.
--------------------------------------------------

Translating:  22%|█████▉                     | 219/1000 [02:57<08:00,  1.62it/s]

[219/1000]
EN: Suryakumar Yadav led India against Namibia in the ongoing T20 World Cup.
BRX: सूर्यकुमार यादवआ टि20 वर्ल्ड कपआव नामिबियानि बेरेखायै भारतखौ दैदेनदों ।
--------------------------------------------------

Translating:  22%|█████▉                     | 220/1000 [02:58<08:20,  1.56it/s]

[220/1000]
EN: India entered the Namibia match after beating the USA in their opener.
BRX: भारतआ गावसिनि गिबि मेचआव आमेरिकाखौ फेजेननायनि उनाव नामिबियानि मैचआव हाबदोंमोन.
--------------------------------------------------

Translating:  22%|█████▉                     | 221/1000 [02:59<08:06,  1.60it/s]

[221/1000]
EN: The Pakistan government allowed the Pakistan team to play India on February 15.
BRX: पाकिस्तान सोरखारा 15 फेब्रुआरिआव पाकिस्तान टीमखौ भारतजों गेलेनो गनायथि होदोंमोन |
--------------------------------------------------

Translating:  22%|█████▉                     | 222/1000 [02:59<07:53,  1.64it/s]

[222/1000]
EN: India versus Pakistan was scheduled for Colombo after weeks of uncertainty.
BRX: भारत आरो पाकिस्ताननि गेजेराव जानाय मेचआ गोबां बोसोर सिगां जानो गोनां जादोंमोन.
--------------------------------------------------

Translating:  22%|██████                     | 223/1000 [03:00<08:23,  1.54it/s]

[223/1000]
EN: India versus Pakistan was described as a group-stage match in Colombo.
BRX: कलम्बोआव भारत आरो पाकिस्ताननि गेजेराव जानाय मेचखौ मोनसे ग्रुप-स्टेज मेच महरै बरनायनाय जादों |
--------------------------------------------------

Translating:  22%|██████                     | 224/1000 [03:01<08:03,  1.60it/s]

[224/1000]
EN: The tournament was listed as featuring 55 matches across India and Sri Lanka.
BRX: भारत आरो श्रीलंकायाव 55 मेचफोरनि थाखाय बे बादायलायनायखौ फारिलाइ खालामनाय जादों ।
--------------------------------------------------

Translating:  22%|██████                     | 225/1000 [03:01<08:09,  1.58it/s]

[225/1000]
EN: The schedule included Delhi, Kolkata, Ahmedabad, Chennai, Mumbai, Colombo, and Kandy venues.
BRX: बेनि गेजेराव दिल्ली, कोलकाता, अहमदाबाद, चेन्नई, कलम्बो आरो केन्डीनि जायगाफोर दंमोन |
--------------------------------------------------

Translating:  23%|██████                     | 226/1000 [03:03<11:38,  1.11it/s]

[226/1000]
EN: Afghanistan faced New Zealand at M. A. Chidambaram Stadium with an 11:00 AM start.
BRX: आफगानिस्तानआ निउजीलेन्डखौ एम.ए. चिदम्बरम स्टेडियामआव 11:00 रिंगानि जागायजेन्नायजों मोगा-मोगि जादोंमोन |
--------------------------------------------------

Translating:  23%|██████▏                    | 227/1000 [03:04<12:03,  1.07it/s]

[227/1000]
EN: New Zealand played UAE on February 10 at M. A. Chidambaram Stadium.
BRX: यु. के.आ इं 2020 माइथायनि 10 फेब्रुआरि खालि इउ. ए. इ. आव गेलेयो ।
--------------------------------------------------

Translating:  23%|██████▏                    | 228/1000 [03:05<11:43,  1.10it/s]

[228/1000]
EN: Group D included UAE, New Zealand, South Africa, Afghanistan, and Canada in one pool.
BRX: ग्रुप डीआव यु. ए. इ., निउजिलेन्ड/जेउथ आफ्रिका आरो कानाडाया मोनसे पुलआव दंफायोमोन |
--------------------------------------------------

Translating:  23%|██████▏                    | 229/1000 [03:05<10:48,  1.19it/s]

[229/1000]
EN: India’s group-stage route moved from Mumbai to Delhi and then Colombo.
BRX: भारतनि ग्रुप-स्टेज रुटा मुम्बायनिफ्राय दिल्ली आरो बेनि उनाव कलम्बोसिम थांनायसै.
--------------------------------------------------

Translating:  23%|██████▏                    | 230/1000 [03:06<10:40,  1.20it/s]

[230/1000]
EN: The India versus Namibia match preview named Gerhard Erasmus as Namibia’s captain.
BRX: भारत आरो नामिबियानि गेजेराव जानाय मेचनि गिबि प्रिभिउआव गियार्ड इरास्मसखौ केप्टेइन महरै सायख 'नाय जादों ।
--------------------------------------------------

Translating:  23%|██████▏                    | 231/1000 [03:07<09:38,  1.33it/s]

[231/1000]
EN: A report said Abhishek Sharma underwent checks for a stomach bug in New Delhi.
BRX: अभिषेक शर्माया गोदान दिल्लीआव मोनसे उदैनि एम्फौनि थाखाय आनजाद नायजादोंमोन.
--------------------------------------------------

Translating:  23%|██████▎                    | 232/1000 [03:07<08:47,  1.46it/s]

[232/1000]
EN: The same report said Abhishek Sharma missed India’s Namibia game despite hospital discharge.
BRX: अभिषेक शर्माया भारतखौ फेजेन्नो हानायाव फेलें जादों ।
--------------------------------------------------

Translating:  23%|██████▎                    | 233/1000 [03:08<08:54,  1.44it/s]

[233/1000]
EN: Sanju Samson’s World Cup debut was described as lasting only eight deliveries.
BRX: सेमसनआ गावनि गिबि मेचआव गेलेयो ।
--------------------------------------------------

Translating:  23%|██████▎                    | 234/1000 [03:08<08:18,  1.54it/s]

[234/1000]
EN: The tournament’s Group A opened across venues in India and Sri Lanka.
BRX: भारत आरो श्रीलंकानि थावनिफोराव टुर्नामेन्टनि ग्रुप ए खौ खेवनाय जादों ।
--------------------------------------------------

Translating:  24%|██████▎                    | 235/1000 [03:09<08:07,  1.57it/s]

[235/1000]
EN: India’s match against Namibia was played on Thursday, February 12.
BRX: भारत आरो बांग्लादेशनि गेजेराव जानाय मेचआ 12 फेब्रुआरि खालि जादोंमोन.
--------------------------------------------------

Translating:  24%|██████▎                    | 236/1000 [03:10<08:47,  1.45it/s]

[236/1000]
EN: Nepal versus Italy appeared as a live-score fixture during the T20 World Cup schedule.
BRX: नेपाल आरो इटालीनि गेजेराव जानाय टि20 बुहुमनां चेम्पियनशिपनि गिबि मेचआ इं 2020 माइथायनि गेजेरसिम सौहैदोंमोन.
--------------------------------------------------

Translating:  24%|██████▍                    | 237/1000 [03:11<09:29,  1.34it/s]

[237/1000]
EN: Australia versus Zimbabwe appeared as a live-score fixture on the Indian Express cricket feed.
BRX: अस्ट्रेलियानि बि.जे.पि. नि गिबि मेचआ इंलेन्डनि क्रिकेटआव मोनसे गिदिर जाफुंसारनायमोन.
--------------------------------------------------

Translating:  24%|██████▍                    | 238/1000 [03:11<08:47,  1.44it/s]

[238/1000]
EN: The Indian Express sports section highlighted India’s 93-run win over Namibia.
BRX: भारतारि एक्सप्रेस गेलेमु खोन्दोआ नामिबियानि सायाव भारतनि 93 राननि देरहासारनायखौ दिन्थियो |
--------------------------------------------------

Translating:  24%|██████▍                    | 239/1000 [03:12<10:07,  1.25it/s]

[239/1000]
EN: The match report said India’s bowling attack dismantled Namibia during the chase.
BRX: बे मेचनि रिप 'र्टआव बुंनाय जादोंमोन दि भारतनि बलिं एटेकआ खारनायनि समाव नामिबियाखौ फोजोबस्रांदोंमोन.
--------------------------------------------------

Translating:  24%|██████▍                    | 240/1000 [03:13<09:24,  1.35it/s]

[240/1000]
EN: The India versus Namibia highlights credited Ishan Kishan’s 61 with driving India’s total.
BRX: भारत आरो नामिबियानि गेजेराव जानाय मेचआव एशियानाया गावस्रानायखौ नुनो मोनो ।
--------------------------------------------------

Translating:  24%|██████▌                    | 241/1000 [03:14<09:51,  1.28it/s]

[241/1000]
EN: ISL 2025–26 fixtures began on February 14 with a double-header format.
BRX: आइ. एस. एल. 2025/26 फिक्सारफोरा 14 फेब्रुआरिनिफ्राय दाबल-हेदार फरमेटजों जागायजेनो →
--------------------------------------------------

Translating:  24%|██████▌                    | 242/1000 [03:15<10:12,  1.24it/s]

[242/1000]
EN: Mohun Bagan Super Giant faced Kerala Blasters in the season opener in Kolkata.
BRX: म 'न बागान सुपार जायन्टआ कलकाताआव सिजननि गिबि गेलेनायाव केराला ब्लास्टर्सजों मोगा-मोगि जादोंमोन |
--------------------------------------------------

Translating:  24%|██████▌                    | 243/1000 [03:16<10:47,  1.17it/s]

[243/1000]
EN: FC Goa hosted Inter Kashi at Fatorda Stadium on February 14.
BRX: एफ.सि. गवाआ 14 फेब्रुआरि खालि फतोर्दा स्टेडियामाव इन्टार काशीखौ ह 'ट खालामो →
--------------------------------------------------

Translating:  24%|██████▌                    | 244/1000 [03:16<10:34,  1.19it/s]

[244/1000]
EN: The first match on double-header days started at 5:00 PM IST.
BRX: डाबल-हेडार सानफोरनि गिबि मेचआ 5:00 बाजिआव जागायजेनो |
--------------------------------------------------

Translating:  24%|██████▌                    | 245/1000 [03:17<10:21,  1.21it/s]

[245/1000]
EN: The second match on double-header days started at 7:30 PM IST.
BRX: डाबल-हेडार सानफोराव नैथि मेचआ 7:30 बाजिआव जागायजेनो |
--------------------------------------------------

Translating:  25%|██████▋                    | 246/1000 [03:19<12:13,  1.03it/s]

[246/1000]
EN: A report said the ISL season would use a single-leg home-and-away format.
BRX: मोनसे रिपर्टाव बुंनाय जादों दि आइ. एस. एल. सिजनआव सिंगल- लेग हम-एन्ड-अवे फरमेट बाहायगोन |
--------------------------------------------------

Translating:  25%|██████▋                    | 247/1000 [03:20<13:01,  1.04s/it]

[247/1000]
EN: The Indian Express football page reported FanCode won exclusive ISL media rights.
BRX: इन्डियान एक्सप्रेस फुटबल पेजआ फोरमायदोंमोन दि फेनक 'डआ एखुथा आई.एस.एल. मीडिया राइट्स देरहादोंमोन |
--------------------------------------------------

Translating:  25%|██████▋                    | 248/1000 [03:21<13:38,  1.09s/it]

[248/1000]
EN: The same report said ISL per-match valuation dropped by about 95 percent.
BRX: बे रिपर्टा बुङो दि आइ.एस.एल. नि मोनफ्रोम मेचनि बेसेन थि खालामनाया 95 जौखोन्दोसो गोग्लैदोंमोन/जेन्नायखौ नोजोर होनानै ।
--------------------------------------------------

Translating:  25%|██████▋                    | 249/1000 [03:22<14:25,  1.15s/it]

[249/1000]
EN: The ISL report described a truncated season with pay cuts at multiple clubs.
BRX: आइ.एस.एल. नि रिपर्टाव गोबां क्लाबफोराव होनां रां दानस्लायनायजों लोगोसे मोनसे दानस्लायजानाय बोथोरखौ बरनायनाय जादों |
--------------------------------------------------

Translating:  25%|██████▊                    | 250/1000 [03:23<12:56,  1.04s/it]

[250/1000]
EN: Real Madrid CF hoped a La Liga surge was boosted by a team dinner.
BRX: बे मेचआ इं 2020 माइथायनि गेजेरसिम दावगालांनो हागोन होनना मिजिं थिदों ।
--------------------------------------------------

Translating:  25%|██████▊                    | 251/1000 [03:24<12:54,  1.03s/it]

[251/1000]
EN: The Real Madrid dinner was reportedly paid for by Vinícius Júnior and Kylian Mbappé.
BRX: रियाल माद्रिदनि डिनारखौ मिथिजानाय बायदियै भिनिसियस जूनियर आरो काइलियन एमबाप्पेआ होदोंमोन |
--------------------------------------------------

Translating:  25%|██████▊                    | 252/1000 [03:25<11:44,  1.06it/s]

[252/1000]
EN: Barcelona aimed for a fourth straight league win against Girona in La Liga.
BRX: बार्सिलोनाया ला लिगायाव गिरनानि बेरेखायै फारियै ब्रैथि लीग देरहानायनि थांखि लादोंमोन |
--------------------------------------------------

Translating:  25%|██████▊                    | 253/1000 [03:26<13:50,  1.11s/it]

[253/1000]
EN: Barcelona visited Atlético Madrid for a Copa del Rey first-leg clash.
BRX: बार्सिलोनाया कोपा देल रेनि गिबि लेग मोगा-मोगि जानायनि थाखाय एटलेटिको माद्रिदआव दावबायहैदोंमोन.
--------------------------------------------------

Translating:  25%|██████▊                    | 254/1000 [03:27<13:01,  1.05s/it]

[254/1000]
EN: Barcelona entered the Atlético Madrid match after winning 17 of 18 matches.
BRX: बार्सिलोनाया 18 मेचफोरनि गेजेराव 17 मेच देरहानायनि उनाव एथलेटिको माद्रिद मेचआव हाबदोंमोन.
--------------------------------------------------

Translating:  26%|██████▉                    | 255/1000 [03:29<15:11,  1.22s/it]

[255/1000]
EN: Real Madrid and UEFA announced an agreement ending the Super League project.
BRX: यु. इ. एफ. ए. आरो रियाल माद्रिदआ सुपार लीग प्रजेक्तखौ फोजोबनायनि मोनसे रादाइखौ फोसावदोंमोनपाटों ।
--------------------------------------------------

Translating:  26%|██████▉                    | 256/1000 [03:30<13:38,  1.10s/it]

[256/1000]
EN: Barcelona formally pulled out of the Super League days before the agreement.
BRX: बार्सिलोनाया थि खालामनायनि माखासे सान सिगां सुपार लीगनिफ्राय ओंखारलांदोंमोन.
--------------------------------------------------

Translating:  26%|██████▉                    | 257/1000 [03:31<14:08,  1.14s/it]

[257/1000]
EN: Tottenham Hotspur reportedly sacked Thomas Frank after a 2–1 loss to Newcastle United.
BRX: इंलेन्डनि बि. जे. पि. आ बे मेचआव थमास फ्रेंकखौ फेजेन्नायनि थाखाय सायख 'दों ।
--------------------------------------------------

Translating:  26%|██████▉                    | 258/1000 [03:32<14:05,  1.14s/it]

[258/1000]
EN: The Tottenham report said the club still had no league win in 2026.
BRX: प्लेइंग इलेवननि गिबि मेचआ इं 2026 मायथाइआव जानो हागौ ।
--------------------------------------------------

Translating:  26%|██████▉                    | 259/1000 [03:33<13:26,  1.09s/it]

[259/1000]
EN: Wayne Rooney said Arsenal looked mentally stronger in the Premier League title race.
BRX: आर्सेनलआ गावस्रानाय प्लेअफआव बाहागो लानो थाखाय आर. एस. एल. नि सायाव गोसो होदों ।
--------------------------------------------------

Translating:  26%|███████                    | 260/1000 [03:34<13:06,  1.06s/it]

[260/1000]
EN: Rooney noted Arsenal last won the Premier League title in the 2003–04 season.
BRX: रुनीआ बुंदोंमोन दि आर्सेनलआ जोबनायाव इं 2003/2004 माइथायनि सिजनआव प्रीमियर लीगनि उपाधि देरहादोंमोन.
--------------------------------------------------

Translating:  26%|███████                    | 261/1000 [03:35<12:41,  1.03s/it]

[261/1000]
EN: Rooney said Arsenal led Manchester City by six points with 13 games remaining.
BRX: आर्सेनलआ गावस्रानाय गेलेमुनि सायाव नोजोर होयो ।
--------------------------------------------------

Translating:  26%|███████                    | 262/1000 [03:36<12:19,  1.00s/it]

[262/1000]
EN: Cristiano Ronaldo missed a second straight Saudi Pro League match for Al-Nassr.
BRX: क्रिस्टियानो रोनाल्ड 'आ अल-नासरनि थाखाय फारियै नैथि साउदी प्रो लीग मेचखौ नागारदोंमोन.
--------------------------------------------------

Translating:  26%|███████                    | 263/1000 [03:37<13:06,  1.07s/it]

[263/1000]
EN: Al-Nassr beat Al-Ittihad 2–0 despite Cristiano Ronaldo’s continued absence.
BRX: अल-नासरआ क्रिस्टियानो रोनाल्ड 'नि थाथ 'बाय थानाय थासेयावबो आल-इत्तिहादखौ 2/0 आव फेजेन्दोंमोन |
--------------------------------------------------

Translating:  26%|███████▏                   | 264/1000 [03:38<12:43,  1.04s/it]

[264/1000]
EN: Sadio Mané and Angelo Gabriel scored for Al-Nassr in the win over Al-Ittihad.
BRX: अल-इत्तिहादनि सायाव देरहानो थाखाय सादियो माने आरो एन्जेलो गाब्रियेलआ गल बानायदोंमोन |
--------------------------------------------------

Translating:  26%|███████▏                   | 265/1000 [03:40<14:23,  1.18s/it]

[265/1000]
EN: Sumit Nagal headlined the Delhi Open 2026 at the DLTA Complex.
BRX: इं 2026 माइथायनि गेजेरसिम गेलेबाय थानाय दिल्ली क्रिकेट एसोसिएशननि (डी.एल.टी.ए.एफ. ) गाहाय मावख 'गिरि सुमित नागला ।
--------------------------------------------------

Translating:  27%|███████▏                   | 266/1000 [03:40<13:11,  1.08s/it]

[266/1000]
EN: The Delhi Open 2026 tournament was scheduled for February 16 to 22.
BRX: दिल्ली अपेन 2026 टूर्नामेन्टखौ 16 निफ्राय 22 फेब्रुआरिसिम थि खालामनाय जादोंमोन.
--------------------------------------------------

Translating:  27%|███████▏                   | 267/1000 [03:42<13:35,  1.11s/it]

[267/1000]
EN: Britain’s Jay Clarke was named as a leading overseas entrant for Delhi Open 2026.
BRX: इं 2026 माइथायनि गेजेरसिम गेलेबाय थानाय अस्ट्रेलियानि गिबि गेलेगिरिनि मुं सायख 'नाय जादों ।
--------------------------------------------------

Translating:  27%|███████▏                   | 268/1000 [03:43<12:56,  1.06s/it]

[268/1000]
EN: The Delhi Open note said Sumit Nagal gained direct entry into the main draw.
BRX: अलम्पिकनि जोबथा मेचआव भारतखौ फेजेन्नो थाखाय सानथांखि लानाय जादों ।
--------------------------------------------------

Translating:  27%|███████▎                   | 269/1000 [03:44<13:06,  1.08s/it]

[269/1000]
EN: India beat the Netherlands 3–2 in Davis Cup competition to move closer.
BRX: भारतआ डेविस काप बादायलायनायाव नेदारलेन्डखौ 3/2 जों फेजेन्नो थाखाय खाथिसिनाव सौहैदोंमोन.
--------------------------------------------------

Translating:  27%|███████▎                   | 270/1000 [03:45<12:38,  1.04s/it]

[270/1000]
EN: Dhakshineswar Suresh featured prominently during India’s Davis Cup tie against the Netherlands.
BRX: नेदारलेन्डनि बेरेखायै भारतनि डेविस काप टाइआव धक्षिनेश्वर सुरेशा गाहाय महरै दिन्थिफुंदोंमोन |
--------------------------------------------------

Translating:  27%|███████▎                   | 271/1000 [03:46<12:22,  1.02s/it]

[271/1000]
EN: India’s doubles pair beat David Pel and Sander Arends in a tight five-setter.
BRX: भारतनि डाबल्स जराया डेविड पेल आरो सेन्डर एरेन्डसखौ मोनबा सेटआव फेजेन्नो हादोंमोन.
--------------------------------------------------

Translating:  27%|███████▎                   | 272/1000 [03:46<11:17,  1.07it/s]

[272/1000]
EN: The doubles win was described as India’s first in five playoff ties versus Europeans.
BRX: बे मेचआव भारत आरो बांग्लादेशनि गेजेराव जानाय बादायलायनायखौ नुनो मोनो ।
--------------------------------------------------

Translating:  27%|███████▎                   | 273/1000 [03:47<11:16,  1.07it/s]

[273/1000]
EN: The same report said Sumit Nagal failed to seal the tie in reverse singles.
BRX: बे रिप 'र्टआव बुंनाय जादों दि सुमित नागला रिभार्स सिंगल्सआव टाइखौ फोजोबनायाव फेलें जादोंमोन.
--------------------------------------------------

Translating:  27%|███████▍                   | 274/1000 [03:48<11:09,  1.08it/s]

[274/1000]
EN: Novak Djokovic said he still wanted to represent Serbia in Davis Cup.
BRX: नॉकक जकोविकआ बुङो दि बियो दाबो डेविस कापआव सार्बियानि थान्दै जानो लुबैदों ।
--------------------------------------------------

Translating:  28%|███████▍                   | 275/1000 [03:49<10:54,  1.11it/s]

[275/1000]
EN: Serbia captain Viktor Troicki described Novak Djokovic as a major team figure.
BRX: ब्रुसेल्सआ गावस्रानाय गेलेमुनि सायाव गोसो होदों ।
--------------------------------------------------

Translating:  28%|███████▍                   | 276/1000 [03:50<11:26,  1.06it/s]

[276/1000]
EN: Novak Djokovic withdrew from a 2025 Davis Cup qualifier due to a hamstring injury.
BRX: अस्ट्रेलियानि स्टार स्ट्राइकर डेविड वार्नरआ गावसिनि नख 'रखौ फेजेन्दोंमोन ।
--------------------------------------------------

Translating:  28%|███████▍                   | 277/1000 [03:51<12:23,  1.03s/it]

[277/1000]
EN: Carlos Alcaraz beat Alexander Zverev in a five-hour, 27-minute Australian Open semifinal.
BRX: कारलास अलकाराजआ अस्ट्रेलियान अपेन सेमि फाइनालाव एलेक्जेन्डार ज्वेरेभखौ बा घनता 27 मिनिटआव फेजेनदोंमोन.
--------------------------------------------------

Translating:  28%|███████▌                   | 278/1000 [03:52<12:37,  1.05s/it]

[278/1000]
EN: Carlos Alcaraz won the Australian Open final after facing Novak Djokovic.
BRX: कारलास अलकाराजआ अस्ट्रेलियान अपेन फाइनालाव नोवाक जकोविचजों मोगा-मोगि जानानै देरहादोंमोन.
--------------------------------------------------

Translating:  28%|███████▌                   | 279/1000 [03:53<12:46,  1.06s/it]

[279/1000]
EN: Jannik Sinner was described as holding five straight wins over Novak Djokovic.
BRX: गाव हारसिङैनो जाफुंसार जानो हानाय गेलेग्रानि गेजेराव सासेआ गावनि नख 'नखौ फेजेन्नो हादोंमोन.
--------------------------------------------------

Translating:  28%|███████▌                   | 280/1000 [03:54<11:46,  1.02it/s]

[280/1000]
EN: The Djokovic–Sinner preview said Djokovic reached semifinals aided by a walkover and retirement.
BRX: जकोविचआ गावसिनि गिबि मेचआव गेलेयो ।
--------------------------------------------------

Translating:  28%|███████▌                   | 281/1000 [03:56<12:54,  1.08s/it]

[281/1000]
EN: An Australian Open report said extreme heat forced temporary suspensions on outside courts.
BRX: अस्ट्रेलियानि अपेननि रिपर्टाव बुंनाय जादों दि जोबोद गुदुंआ बायजोआरि कर्टफोराव अरायथा नङै दानथेलायनायखौ नारसिनो गोनां खालामदोंमोनपाटों ।
--------------------------------------------------

Translating:  28%|███████▌                   | 282/1000 [03:56<12:15,  1.02s/it]

[282/1000]
EN: The same report said organisers issued heat warnings for players and spectators.
BRX: बे रिप 'र्टआव बुंनाय जादोंमोन दि खुंगिरिफोरा गेलेगिरिफोर आरो नायगिरिफोरनि थाखाय गुदुंनि सामोल होदोंमोन.
--------------------------------------------------

Translating:  28%|███████▋                   | 283/1000 [03:58<12:29,  1.05s/it]

[283/1000]
EN: Jannik Sinner beat Eliot Spizzirri 4–6, 6–3, 6–4, 6–4 in Melbourne.
BRX: इं 2007 माइथायनि मेलबर्नआव जेफ्रिचआ 4थि मेचआव 6थि आरो 5थि खेब फाइनालाव सौहैनो हानायाव जाफुंसारदों ।
--------------------------------------------------

Translating:  28%|███████▋                   | 284/1000 [04:00<17:22,  1.46s/it]

[284/1000]
EN: A tennis feature said Fangran Tian was coached by Chennai’s Mangal Sriram since age 12.
BRX: मोनसे टेनिस फिचारे बुंदोंमोन दि फेंग्रान टियानखौ 12 बोसोर बैसोनिफ्राय चेन्नाईनि मंगल श्रीरामजों फोरोंनाय जादोंमोन/09/1/2/3/5/7/6/4/8/9 आरो इं199 माइथायाव ब्रै खेब गावनोगोराव गेलेदोंमोन.
--------------------------------------------------

Translating:  28%|███████▋                   | 285/1000 [04:01<16:28,  1.38s/it]

[285/1000]
EN: Badminton World Federation demoted Syed Modi International from Super 300 to Super 100.
BRX: भारतआरि क्रिकेट एसोसिएशननि गाहाय मावख 'गिरि मन्डलीआ बुंदों दि बिथांनि नख 'नारि सायख 'नाया जाफुंसार जानो हागौ नङाबा गोहोम खोख्लैयो.
--------------------------------------------------

Translating:  29%|███████▋                   | 286/1000 [04:02<15:38,  1.31s/it]

[286/1000]
EN: The same report said India Open retained Super 750 status for the 2027–2030 cycle.
BRX: अस्ट्रेलियानि गिबि क्रिकेट मेचआ इं 2027 मायथाइसिम भारतखौ आवग्रिना दोनगोन ।
--------------------------------------------------

Translating:  29%|███████▋                   | 287/1000 [04:03<14:19,  1.20s/it]

[287/1000]
EN: A badminton reforms report said World Championships and five Super 1000s will run 11 days.
BRX: मोनसे बेडमिन्टन फोसाबनाय रिपर्टाव बुंनाय जादों दि बुहुमनां चेम्पियनशिप आरो मोनबा सुपार 1000आ 11 सान खारगोन |
--------------------------------------------------

Translating:  29%|███████▊                   | 288/1000 [04:05<14:57,  1.26s/it]

[288/1000]
EN: The Indian Express said BWF’s AGM 2026 would vote on a 3×15 scoring format.
BRX: भारतारि एक्सप्रेसआ बुंदोंमोन दि बी.डब्ल्यू.एफ. नि ए.जि.एम. 2026 आ 3/15 स्करिं फरमेटआव भ 'ट खालामगोन |
--------------------------------------------------

Translating:  29%|███████▊                   | 289/1000 [04:06<14:18,  1.21s/it]

[289/1000]
EN: A Badminton Asia Team report said India lost 3–2 to Japan in men’s ties.
BRX: भारत आरो जापाननि गेजेराव जानाय मेचफोरनि गेजेराव मोनसेआ जानो हागौ दि भारतआ जापाननि फारसे 3/2 जों जेनदोंमोन.
--------------------------------------------------

Translating:  29%|███████▊                   | 290/1000 [04:07<12:54,  1.09s/it]

[290/1000]
EN: The same report said India lost to Thailand in women’s ties at the team event.
BRX: भारत आरो थाइलेन्डनि गेजेराव जानाय मेचफोरनि गेजेराव मोनसेआ जानो हाथावनामोन ।
--------------------------------------------------

Translating:  29%|███████▊                   | 291/1000 [04:08<12:47,  1.08s/it]

[291/1000]
EN: A selection report said Tanvi Sharma would play first singles after Unnati Hooda was out.
BRX: भारत क्रिकेट टीमनि गिबि खेब सायख 'नाय रिपर्टाव बुंनाय जादोंमोन दि रनवीश शर्माआ फिन खेबसे गावस्रालाङो ।
--------------------------------------------------

Translating:  29%|███████▉                   | 292/1000 [04:09<12:13,  1.04s/it]

[292/1000]
EN: An India Open report said “nest materials” halted a women’s doubles semifinal in Delhi.
BRX: भारत ओपननि रिपर्टआ बुंदोंमोन दि नेस्ट मुवाफोरा दिल्लीयाव आयजोफोरनि डाबल्स सेमि फाइनालखौ हेंथा होदोंमोन |
--------------------------------------------------

Translating:  29%|███████▉                   | 293/1000 [04:09<11:43,  1.00it/s]

[293/1000]
EN: A feature said An Se-young won 94.8 percent of her matches in 2025.
BRX: मोनसे फिचारे बुंदोंमोन दि एन से- यंगआ इं 2025 माइथायाव गावनि मेचफोरनि 94.8 जौखोन्दो देरहादोंमोन.
--------------------------------------------------

Translating:  29%|███████▉                   | 294/1000 [04:11<12:15,  1.04s/it]

[294/1000]
EN: The same feature said An Se-young began 2026 with two titles in two weeks.
BRX: बे रोखोमसे आखुथाइआ बुंदोंमोन दि एन से-युङ्गआ नै सप्तायाव मोन्नै बिमुंजों 2026 खौ जागायदोंमोन |
--------------------------------------------------

Translating:  30%|███████▉                   | 295/1000 [04:12<11:50,  1.01s/it]

[295/1000]
EN: Lin Chun-yi beat Jonatan Christie 21–10, 21–18 in the India Open final.
BRX: अस्ट्रेलियानि सानजायारि चेम्पियनशिपनि जोबथा मेचआव क्रिस्टीया भारतखौ फेजेन्नो हानायाव जाफुंसारदों ।
--------------------------------------------------

Translating:  30%|███████▉                   | 296/1000 [04:13<11:35,  1.01it/s]

[296/1000]
EN: Devika Sihag beat Navya Kanderi 21–10, 21–13 to win in Baku.
BRX: बे मेचआव देविका सिहाकआ नाव्या कान्डेरीखौ 21,10,2113 आव फेजेन्नो हादोंमोन.
--------------------------------------------------

Translating:  30%|████████                   | 297/1000 [04:13<11:28,  1.02it/s]

[297/1000]
EN: Radhika Sharma won her first mixed doubles title partnering Sathwik Reddy.
BRX: राधिका शर्माया गावनि गिबि गलायमोनदेर डाबल्स टाइटेलखौ साथविक रेड्डीजों लोगो जानानै देरहादोंमोन.
--------------------------------------------------

Translating:  30%|████████                   | 298/1000 [04:14<11:37,  1.01it/s]

[298/1000]
EN: Ankur Bhattacharjee upset world-ranked opponent Bourrassaud 3–1 at WTT Chennai.
BRX: इं 2020 माइथायनि नैथि टेस्टआव भारतखौ फेजेन्नो हानायाव मदद मोन्नायनि मिजिं थिनाय जादों ।
--------------------------------------------------

Translating:  30%|████████                   | 299/1000 [04:16<12:37,  1.08s/it]

[299/1000]
EN: FIFA president Gianni Infantino faced criticism over high-priced tickets for the 2026 World Cup.
BRX: इं 2026 माइथायनि विश्वकपनि थाखाय गोजौ बेसेननि टिकेटनि सायाव फिफा आफादगिरि जियानी इन्फेनटिनoआ सावरायजानायखौ मोगा-मोगि जाना दंमोन |
--------------------------------------------------

Translating:  30%|████████                   | 300/1000 [04:17<13:04,  1.12s/it]

[300/1000]
EN: India lost 1-3 to Belgium in the FIH Pro League opener at Rourkela.
BRX: अस्ट्रेलियानि बि. जे. पि. नि गिबि मेचआव भारतआ बेलजियामखौ 2 - 0 जों फेजेन्नो हानायाव जाफुंसारनाय नुनो मोनदों ।
--------------------------------------------------

Translating:  30%|████████▏                  | 301/1000 [04:18<12:12,  1.05s/it]

[301/1000]
EN: Craig Fulton said India’s defensive structure did not deliver in the Pro League opener.
BRX: इं 2020 माइथायनि गिबि टेस्टआव भारतखौ फेजेन्नो थाखाय प्लेआफआव सौहैबाय ।
--------------------------------------------------

Translating:  30%|████████▏                  | 302/1000 [04:19<13:01,  1.12s/it]

[302/1000]
EN: India then suffered a 0-8 loss to Argentina in the next Pro League match.
BRX: भारतआ बेनि उनाव प्र. लीगनि मैचआव आर्जेन्टिनानि बेरेखायै 0-8 जों जेनदोंमोन |
--------------------------------------------------

Translating:  30%|████████▏                  | 303/1000 [04:20<12:07,  1.04s/it]

[303/1000]
EN: India’s 0-8 defeat was described as a systematic demolition by Argentina.
BRX: भारतनि 0-8 जेन्नायखौ आर्जेन्टिनाया मोनसे खान्थि गोनां फोजोबस्रांनाय होन्ना बुंजादोंमोन.
--------------------------------------------------

Translating:  30%|████████▏                  | 304/1000 [04:21<12:12,  1.05s/it]

[304/1000]
EN: India’s 0-8 loss matched the joint third-worst defeat in India’s hockey history.
BRX: भारतनि हकी जारिमिनाव 0-8 जेननाया जुथुमनि थामथि गाज्रिसिन जेननायजों गोरोबनायमोन.
--------------------------------------------------

Translating:  30%|████████▏                  | 305/1000 [04:22<12:00,  1.04s/it]

[305/1000]
EN: India’s other 0-8 losses came in 1985 versus Netherlands and 2010 versus Australia.
BRX: भारतनि गुबुन 0-8 जेननाया इं 1985 माइथायाव नेदारलेन्डजों आरो इं 2010 माइथायाव अस्ट्रेलियानि बेरेखायै जादोंमोन.
--------------------------------------------------

Translating:  31%|████████▎                  | 306/1000 [04:23<11:18,  1.02it/s]

[306/1000]
EN: Argentina’s Tomas Domene scored four goals in the 0-8 win over India.
BRX: अस्ट्रेलियानि बि. जे. पि. नि गिबि मेचआव भारतखौ 8 - 0 जों फेजेन्नो हानायाव जाफुंसारनाय नुनो मोनदों ।
--------------------------------------------------

Translating:  31%|████████▎                  | 307/1000 [04:24<10:10,  1.14it/s]

[307/1000]
EN: Tomas Domene scored at 15th, 20th, 26th and 60th minutes against India.
BRX: डमिसनआ भारतनि बेरेखायै 15थि, 20थि आरो 26थि मिनिटआव गल बानायदोंमोन |
--------------------------------------------------

Translating:  31%|████████▎                  | 308/1000 [04:24<09:23,  1.23it/s]

[308/1000]
EN: Tomas Ruiz, Lucio Mendez, Ignacio Ibarra, and Nicolas della Torre also scored for Argentina.
BRX: आर्जेनटाइननि थाखाय गल खालामनायफ्रा जादोंः
--------------------------------------------------

Translating:  31%|████████▎                  | 309/1000 [04:25<09:02,  1.27it/s]

[309/1000]
EN: India’s third quarter without conceding a goal looked like an anomaly in the match.
BRX: भारतनि थामथि क्वार्टरआव मोनसेबो गल दाखालामालाबानो मेचआव मोनसे गोरोबै बायदि नुजादोंमोन.
--------------------------------------------------

Translating:  31%|████████▎                  | 310/1000 [04:25<08:07,  1.42it/s]

[310/1000]
EN: Player-of-the-Match Tomas Domene said Argentina played the whole game at 100 percent.
BRX: आर्जेनटाइनआ बे मेचआव गेलेयो ।
--------------------------------------------------

Translating:  31%|████████▍                  | 311/1000 [04:26<07:55,  1.45it/s]

[311/1000]
EN: Tomas Domene said Argentina were disappointed after losing 3-5 to Belgium previously.
BRX: आर्जेनटिनाआ बेनि सिगां बेलजियामजों 3-5 जों जेननायनि उनाव गोसो बायनायसै ।
--------------------------------------------------

Translating:  31%|████████▍                  | 312/1000 [04:27<07:20,  1.56it/s]

[312/1000]
EN: Argentina scored two quick goals at the end of the first quarter.
BRX: आर्जेन्टिनाया गिबि क्वार्टरनि जोबनायाव मोन्नै गोख्रै गल बानायदोंमोन |
--------------------------------------------------

Translating:  31%|████████▍                  | 313/1000 [04:27<06:55,  1.66it/s]

[313/1000]
EN: Argentina scored five goals in 10 minutes during the second quarter.
BRX: आर्जेन्टिनाया नैथि क्वार्टरनि समाव 10 मिनिटआव मोनबा गल बानायदोंमोन |
--------------------------------------------------

Translating:  31%|████████▍                  | 314/1000 [04:28<06:50,  1.67it/s]

[314/1000]
EN: Harmanpreet Singh missed two penalty strokes in the match against Argentina.
BRX: भारत आरो बांग्लादेशनि गेजेराव गेलेबाय थानाय मेचफोरनि गेजेराव मोनसेआ जानो हागौ ।
--------------------------------------------------

Translating:  32%|████████▌                  | 315/1000 [04:28<07:11,  1.59it/s]

[315/1000]
EN: India missed three penalty corners during the 0-8 defeat against Argentina.
BRX: भारतआ आर्जेन्टिनानि बेरेखायै 0-8 जेन्नायनि समाव मोनथाम पेनाल्टि कर्नारखौ खोमाखो ।
--------------------------------------------------

Translating:  32%|████████▌                  | 316/1000 [04:29<07:16,  1.57it/s]

[316/1000]
EN: India goalkeepers Suraj Karkera and Pawan looked completely out of place.
BRX: भारतनि ग 'कीपार सूरज करकेरा आरो पवनआ आबुङै बायखोन्दा नुजादोंमोन.
--------------------------------------------------

Translating:  32%|████████▌                  | 317/1000 [04:30<07:04,  1.61it/s]

[317/1000]
EN: Argentina dominated possession and toyed with India’s midfield and defence.
BRX: आर्जेन्टिनाया भारतनि मिडफील्ड आरो डिफेन्सजों दबथायनाय आरो गेलेनाय गेलेदोंमोन.
--------------------------------------------------

Translating:  32%|████████▌                  | 318/1000 [04:30<07:01,  1.62it/s]

[318/1000]
EN: Argentina’s win catapulted them to fourth in the nine-team standings.
BRX: आर्जेन्टिनानि देरहासारनाया बिसोरखौ गु-टीम स्टान्डिंआव ब्रैथियाव सौहैहोदोंमोन.
--------------------------------------------------

Translating:  32%|████████▌                  | 319/1000 [04:31<08:30,  1.33it/s]

[319/1000]
EN: India next faced world No.2 Belgium again after the heavy Argentina loss.
BRX: भारतआ बेनि उनाव आर्जेन्टिनानि गिदिर जेननायनि उनाव बुहुमनां नं.2 बेल्जियामनि मोगा-मोगि जादोंमोन |
--------------------------------------------------

Translating:  32%|████████▋                  | 320/1000 [04:32<08:24,  1.35it/s]

[320/1000]
EN: Macklin Celebrini scored early to spark Canada’s 5-0 win over Czech Republic.
BRX: मेक्लिन सेलेब्रिनीआ चेक रिपाब्लिकनि सायाव 5-0 जों देरहासार जानो थाखाय सिगां गल बानायदोंमोन |
--------------------------------------------------

Translating:  32%|████████▋                  | 321/1000 [04:33<08:11,  1.38it/s]

[321/1000]
EN: Macklin Celebrini scored with just over five seconds left in the first period.
BRX: मेक्लिन सेलेब्रिनीआ गिबि समफारियाव बा सेकेन्डनिख्रुइ एसे बांसिन गल बानायदोंमोन |
--------------------------------------------------

Translating:  32%|████████▋                  | 322/1000 [04:33<07:43,  1.46it/s]

[322/1000]
EN: Mark Stone, Bo Horvat, Nathan MacKinnon and Nick Suzuki scored in Canada’s opener.
BRX: अस्ट्रेलियानि गलिं स्करआ इंलेन्डखौ फेजेन्नो हानायाव जाफुंसारदों ।
--------------------------------------------------

Translating:  32%|████████▋                  | 323/1000 [04:34<08:07,  1.39it/s]

[323/1000]
EN: Connor McDavid recorded three assists in Canada’s 5-0 Olympic win.
BRX: कनर मैकडेविडआ कानाडानि 5-0 अलिम्पिक देरहासारनायाव मोनथाम एसिस्ट रेबगान्थि खालामदोंमोन |
--------------------------------------------------

Translating:  32%|████████▋                  | 324/1000 [04:35<08:13,  1.37it/s]

[324/1000]
EN: Sidney Crosby said Celebrini’s first Olympic goal was huge to get Canada going.
BRX: सिडनी क्रसबीआ बुंदोंमोन दि सेलेब्रिनिनि गिबि अलिम्पिक गलआ कानाडाखौ थांनो थाखाय गिदिरमोन |
--------------------------------------------------

Translating:  32%|████████▊                  | 325/1000 [04:36<08:39,  1.30it/s]

[325/1000]
EN: Jon Cooper said Macklin Celebrini plays the game well beyond his years.
BRX: बे गेलेनाया जाफुंसार जानो हागौ दि बिथाङा गावनि नख 'रखौ साबसिन खालामनो हागोन नङा.
--------------------------------------------------

Translating:  33%|████████▊                  | 326/1000 [04:37<09:26,  1.19it/s]

[326/1000]
EN: Canada planned to face Switzerland at the Milano Arena the next day.
BRX: कानाडाया अखानायै मिलान'एरिनाआव सुइजारलेन्डजों मोगा-मोगि जानो सानथांखि बानायदोंमोन.
--------------------------------------------------

Translating:  33%|████████▊                  | 327/1000 [04:38<09:25,  1.19it/s]

[327/1000]
EN: Choi Ga-on won women’s snowboard halfpipe gold after recovering from a first-run crash.
BRX: स 'इ गा-अनआ गिबि रान क्रासनिफ्राय हामनायनि उनाव आयजोफोरनि स्नोबोर्ड हाफपाइप सना देरहादोंमोन.
--------------------------------------------------

Translating:  33%|████████▊                  | 328/1000 [04:39<09:29,  1.18it/s]

[328/1000]
EN: Chloe Kim took silver and Mitsuki Ono won bronze in the halfpipe event.
BRX: ब्रुसेल्सआ बे मेचआव गेलेदोंमोन आरो जायजों बिथाङा गावस्रादोंमोन ।
--------------------------------------------------

Translating:  33%|████████▉                  | 329/1000 [04:39<09:19,  1.20it/s]

[329/1000]
EN: Choi Ga-on scored 90.25 to beat Chloe Kim’s leading 88 score.
BRX: च 'इ गा-अनआ क्लौ किमखौ 88 स्करआव फेजेन्नायनि थाखाय 90.25 रान बानायदोंमोन.
--------------------------------------------------

Translating:  33%|████████▉                  | 330/1000 [04:40<09:02,  1.23it/s]

[330/1000]
EN: Arsenal reached the League Cup final after Kai Havertz secured a 1-0 win.
BRX: आर्सेनलआ बे मेचआव गेलेयो आरो बेनि उनाव गावनोगोरखौ फेजेन्नो हादोंमोन.
--------------------------------------------------

Translating:  33%|████████▉                  | 331/1000 [04:41<08:32,  1.31it/s]

[331/1000]
EN: Kai Havertz came off the bench to finish Arsenal’s 4-2 aggregate semi-final victory.
BRX: आर्सेनलनि सेमि-फाइनेल देरहासारनायखौ 4-2 जों फोजोबनो थाखाय बेन्चनिफ्राय ओंखारदोंमोन |
--------------------------------------------------

Translating:  33%|████████▉                  | 332/1000 [04:42<09:05,  1.22it/s]

[332/1000]
EN: Arsenal will face Manchester City or Newcastle at Wembley on March 22.
BRX: आर्सेनलआ 22 मार्चआव वेम्बलीआव मैनचेस्टर सिटी एबा न्यूकासलजों मोगा-मोगि जागोन |
--------------------------------------------------

Translating:  33%|████████▉                  | 333/1000 [04:42<09:03,  1.23it/s]

[333/1000]
EN: Manchester City held a 2-0 lead over Newcastle ahead of the second leg.
BRX: इंलेन्डनि बि. जे. पि. आ गावस्रानाय मेचआव गेलेयो ।
--------------------------------------------------

Translating:  33%|█████████                  | 334/1000 [04:43<08:03,  1.38it/s]

[334/1000]
EN: Arsenal have not won the League Cup since 1993, according to the report.
BRX: आर्सेनलआ इं 1993 माइथायनिफ्राय लीग कापखौ देरहानो हायाखै |
--------------------------------------------------

Translating:  34%|█████████                  | 335/1000 [04:44<09:04,  1.22it/s]

[335/1000]
EN: The Football Association of Ireland confirmed Ireland will fulfil Nations League fixtures against Israel.
BRX: आय़ारलेन्डनि फुटबल एसोसिएशना रोखा खालामदों दि आयारलेन्डआ इजराइलनि बेरेखायै नेशनस लीग फिक्सारफोरखौ आबुं खालामगोनपाटानाया जानो हागौ नङा.
--------------------------------------------------

Translating:  34%|█████████                  | 336/1000 [04:45<08:49,  1.25it/s]

[336/1000]
EN: Ireland and Israel were drawn with Austria and Kosovo in Nations League League B.
BRX: अस्ट्रेलियानि बि. सि. आइ. नि जोबथा मेचआ इंलेन्डखौ फेजेन्नो हानायाव जाफुंसारदों ।
--------------------------------------------------

Translating:  34%|█████████                  | 337/1000 [04:46<08:47,  1.26it/s]

[337/1000]
EN: Ireland must play Israel home and away between September and November.
BRX: आय़ारलेन्डआ सेप्तेम्बर आरो नबेम्बरनि गेजेराव इजराइलजों न'आरो बायजोयाव गेलेनांगोन |
--------------------------------------------------

Translating:  34%|█████████▏                 | 338/1000 [04:48<13:52,  1.26s/it]

[338/1000]
EN: The FAI warned refusal could mean forfeiture and possible disqualification under UEFA regulations.
BRX: एफ.ए.आइ.आ सामोल होदोंमोन दि नेवसिजानायनि ओंथिया यु.इ.एफए. नेमखान्थिफोरनि सिङाव जब्द खालामनाय आरो जानो हाथावना उदायै जानो हागौपाटिया इउ.ई.एफ. ए. नि नेमफोरजों सोमोन्दो गोनां जेंनाफोरनि सायाव गोहोम खोख्लैनो हागौांनी ।
--------------------------------------------------

Translating:  34%|█████████▏                 | 339/1000 [04:49<13:52,  1.26s/it]

[339/1000]
EN: The FAI said it requested Israel’s UEFA ban in November after an internal vote.
BRX: एफ.ए.आइ.आ बुंदोंमोन दि बेयो नबेम्बराव इसरायेलनि इउ.इ.एफए.खौ होबथानायनि थाखाय मोनसे सिंनि भ 'टनि उनाव आरज गाबदोंमोन |
--------------------------------------------------

Translating:  34%|█████████▏                 | 340/1000 [04:50<13:35,  1.24s/it]

[340/1000]
EN: Novak Djokovic beat Jannik Sinner 3-6, 6-3, 4-6, 6-4, 6-4 in Melbourne.
BRX: अस्ट्रेलियानि स्टार स्ट्राइकार डेविड ज 'कबआ गावसिनि गिबि मेचआव जेफ्रिचखौ 3 - 0,6 - 3,4 - 6,6-4 जों फेजेन्नो हानायाव जाफुंसारदों ।
--------------------------------------------------

Translating:  34%|█████████▏                 | 341/1000 [04:51<11:46,  1.07s/it]

[341/1000]
EN: Novak Djokovic’s win over Jannik Sinner set up an Australian Open final against Carlos Alcaraz.
BRX: अस्ट्रेलियानि स्टार गेलेगिरिया गावसिनि नख 'रखौ फेजेन्नो हानायाव जाफुंसारनाय नुनो मोनदों ।
--------------------------------------------------

Translating:  34%|█████████▏                 | 342/1000 [04:52<10:22,  1.06it/s]

[342/1000]
EN: Novak Djokovic reached his 11th Australian Open final after ending four straight semi-final exits.
BRX: अस्ट्रेलियानि स्टार स्ट्राइकार न 'वाक जकोविचआ गावनि गिबि मेचआव गेलेयो ।
--------------------------------------------------

Translating:  34%|█████████▎                 | 343/1000 [04:52<09:16,  1.18it/s]

[343/1000]
EN: Carlos Alcaraz reached his first Melbourne Park title match, the report said.
BRX: कार्लस अलकाराजआ गावनि गिबि मेलबर्न पार्क टाइटेल मेचआव सौहैदोंमोन |
--------------------------------------------------

Translating:  34%|█████████▎                 | 344/1000 [04:53<09:01,  1.21it/s]

[344/1000]
EN: Lorenzo Musetti retired mid-match after suffering a suspected upper leg tear.
BRX: लरेन्जो मुसेटीआ सन्देह खालाम जानाय गोजौ आथिंनि दुखु मोननायनि उनाव गेजेर मेचनिफ्राय बिबान एंगारदोंमोन.
--------------------------------------------------

Translating:  34%|█████████▎                 | 345/1000 [04:54<08:54,  1.23it/s]

[345/1000]
EN: Lorenzo Musetti withdrew after winning the first two sets against Novak Djokovic.
BRX: लरेन्जो मुसेटीआ नोवाक जकोविचनि बेरेखायै गिबि मोननै सेट देरहानायनि उनाव गावस्रादोंमोन.
--------------------------------------------------

Translating:  35%|█████████▎                 | 346/1000 [04:55<09:12,  1.18it/s]

[346/1000]
EN: Alexander Zverev rallied from losing the first set to beat Gabriel Diallo in four sets.
BRX: एलेक्जेन्डार जेभेरेभआ गिबि सेटखौ जेननायनिफ्राय ब्रै सेटआव गाब्रिएल डायेल 'खौ फेजेननो थाखाय हानजा सुरदोंमोन |
--------------------------------------------------

Translating:  35%|█████████▎                 | 347/1000 [04:56<10:09,  1.07it/s]

[347/1000]
EN: Alexander Zverev won 6-7(1), 6-1, 6-4, 6-2 against Gabriel Diallo at Rod Laver Arena.
BRX: एलेक्जेन्डार जेभेरेभआ रड लेभार एरिनाआव गाब्रियेल डायल्ल 'नि बेरेखायै 6-7,21,6-6,4,6-2 जों देरहादोंमोन.
--------------------------------------------------

Translating:  35%|█████████▍                 | 348/1000 [04:57<10:14,  1.06it/s]

[348/1000]
EN: An Australian Open report noted fans were unhappy about long queues and a ticket sales halt.
BRX: अस्ट्रेलियानि अपेननि रिपर्टाव बुंनाय जादोंमोन दि नायगिरिफोरा गोलाव सारिफोर आरो टिकेट फान्नाया थाबथानायनि बागै खुसि नङामोनपाटिया ।
--------------------------------------------------

Translating:  35%|█████████▍                 | 349/1000 [04:58<11:05,  1.02s/it]

[349/1000]
EN: A Hindustan Times column said tennis needs rivalries to elevate players and the sport.
BRX: हिन्दुस्तान टाइम्सनि मोनसे लिरबिदांआ बुंदोंमोन दि टेनिसखौ गेलेगिरिफोर आरो गेलेमुखौ जौगाहोन्नो थाखाय बादायनायनि गोनांथि दंपाइ ।
--------------------------------------------------

Translating:  35%|█████████▍                 | 350/1000 [04:59<10:54,  1.01s/it]

[350/1000]
EN: A Hindustan Times column said Jannik Sinner and Carlos Alcaraz are improving every year.
BRX: हिन्दुस्तान टाइम्सनि लिरबिदांआव बुंनाय जादों दि जानिक सिनार आरो कार्लोस अल्कराजआ बोसोरफ्रोमबो जौगाबोगासिनो दंपाटों ।
--------------------------------------------------

Translating:  35%|█████████▍                 | 351/1000 [05:00<09:36,  1.13it/s]

[351/1000]
EN: The same column said Sinner and Alcaraz already play at a level above most players.
BRX: अस्ट्रेलियानि गिबि क्रिकेट गेलेगिरिया बे मेचआव बाहागो लानो हागोन ।
--------------------------------------------------

Translating:  35%|█████████▌                 | 352/1000 [05:01<09:24,  1.15it/s]

[352/1000]
EN: The column said Federer, Nadal and Djokovic gave men’s tennis a tribal feel for two decades.
BRX: फेदेरारआ बुंदोंमोन दि नडाल आरो जकोविचआ मोन्नै जिथायसिम हौवाफोरनि टेनिसखौ मोनसे थागिबि मोनदांथि होदोंमोन |
--------------------------------------------------

Translating:  35%|█████████▌                 | 353/1000 [05:01<09:26,  1.14it/s]

[353/1000]
EN: A report said Alexander Zverev began a bid for a maiden Australian Open title.
BRX: मोनसे रिपर्टाव बुंनाय जादों दि एलेक्जेन्डार ज्वेरेभआ गिबि अस्ट्रेलियान अपेन टाइटिलनि थाखाय बिड जागायदोंमोन.
--------------------------------------------------

Translating:  35%|█████████▌                 | 354/1000 [05:02<09:46,  1.10it/s]

[354/1000]
EN: Carlos Alcaraz defeated Alexander Zverev 6-3, 3-6, 6-1, 6-2 at the Australian Open.
BRX: अस्ट्रेलियान अपेनआव कारलास अलकाराजआ एलेक्जेन्डार ज्वेरेभखौ 6-3,3-6,6-1,6-2 जों फेजेनदोंमोन.
--------------------------------------------------

Translating:  36%|█████████▌                 | 355/1000 [05:03<09:09,  1.17it/s]

[355/1000]
EN: Carlos Alcaraz won in two hours and 26 minutes, according to the match report.
BRX: कारलास अलकाराजआ मैचनि रिपर्टनि बायदिब्ला नै घन्टा आरो 26 मिनिटआव देरहादोंमोन |
--------------------------------------------------

Translating:  36%|█████████▌                 | 356/1000 [05:04<09:07,  1.18it/s]

[356/1000]
EN: The same report said Zverev received a time-violation warning during the match.
BRX: बे मेचनि गिबि मेचआव गाव हारसिङैनो गेलेयो ।
--------------------------------------------------

Translating:  36%|█████████▋                 | 357/1000 [05:05<08:29,  1.26it/s]

[357/1000]
EN: The report said Alcaraz requested a meeting with the supervisor after the time warning.
BRX: अलकाराजआ गिबि खेब नायगिरिजों लोगो हमलायदोंमोन.
--------------------------------------------------

Translating:  36%|█████████▋                 | 358/1000 [05:05<08:15,  1.30it/s]

[358/1000]
EN: The report said Alcaraz complained about the length of Zverev’s breaks between points.
BRX: अलकाराजआ गावस्रानाय मेचआव गेलेयो ।
--------------------------------------------------

Translating:  36%|█████████▋                 | 359/1000 [05:06<08:06,  1.32it/s]

[359/1000]
EN: Carlos Alcaraz said he also wanted to know the limit for the time between points.
BRX: कार्लस अलकाराजआ बुंदोंमोन दि बिथाङा पइन्टफोरनि गेजेरनि समनि सिमाखौबो मिथिनो लुगैयोमोन |
--------------------------------------------------

Translating:  36%|█████████▋                 | 360/1000 [05:07<09:14,  1.15it/s]

[360/1000]
EN: R Praggnanandhaa sealed a 2026 Candidates berth by winning the FIDE Circuit 2025.
BRX: आर.पी. डी. ए. नि गाहाय मावख 'गिरि आरो गिबि सायख 'जानाय गेलेगिरिनि गेजेराव सासेआ इं 2026 माइथायनि नैथि बोसोरसिम दावगालांनो हानायाव जाफुंसारनाय नुनो मोनदों ।
--------------------------------------------------

Translating:  36%|█████████▋                 | 361/1000 [05:08<08:58,  1.19it/s]

[361/1000]
EN: The Candidates Tournament will determine the challenger to world champion D Gukesh.
BRX: बे मेचआव गेलेग्रानि गेजेराव सासेआ गावबागावखौ फेजेन्नो हागोन ।
--------------------------------------------------

Translating:  36%|█████████▊                 | 362/1000 [05:09<09:37,  1.10it/s]

[362/1000]
EN: R Praggnanandhaa overtook Ding Liren in May to lead the FIDE Circuit race.
BRX: आर.पी.डी. ए. डी. इ. डि. आइ.डि.इ. सार्किट रेसखौ दैदेननो थाखाय मे दानाव डिं लिरेनखौ फेजेन्नो हादोंमोन.
--------------------------------------------------

Translating:  36%|█████████▊                 | 363/1000 [05:10<09:14,  1.15it/s]

[363/1000]
EN: Praggnanandhaa thanked supporters on X after earning a place in the 2026 Candidates.
BRX: प्रज्ञानंदआ इं 2026 माइथायाव मोनसे जायगा आरजिनाय उनाव एक्सआव मददगिरिफोरखौ बाख्नायदोंमोन.
--------------------------------------------------

Translating:  36%|█████████▊                 | 364/1000 [05:11<09:18,  1.14it/s]

[364/1000]
EN: A report said only Nodirbek Abdusattorov had a theoretical chance to catch Praggnanandhaa.
BRX: मोनसे रिपर्टाव बुंनाय जादोंमोन दि नडरबेक आब्दुसातरभआल 'हा प्रागनानन्दखौ हमनायनि बुंफुरलु खाबु दंमोन |
--------------------------------------------------

Translating:  36%|█████████▊                 | 365/1000 [05:12<10:20,  1.02it/s]

[365/1000]
EN: D Gukesh withdrew from Tata Steel Chess India Rapid and Blitz for personal reasons.
BRX: डी. सी. आई. नि गाहाय मावख 'गिरिजों लोगो हमलायनाया बे बाथ्राखौ रोखा खालामो दि बिथाङा बै समनि थाखाय थि खालामगौमोन जायनिफ्राय बियो जाफुंसार जानो हायोमोन |
--------------------------------------------------

Translating:  37%|█████████▉                 | 366/1000 [05:13<09:39,  1.09it/s]

[366/1000]
EN: Tata Steel Chess India Rapid and Blitz was scheduled in Kolkata from January 7 to 11.
BRX: टाटा स्टील चेस इन्डिया रेपिड आरो ब्लिट्जआ 7 निफ्राय 11 जानुवारिसिम कलकातायाव थि खालाम जादोंमोन |
--------------------------------------------------

Translating:  37%|█████████▉                 | 367/1000 [05:13<08:57,  1.18it/s]

[367/1000]
EN: Nihal Sarin replaced D Gukesh in the Tata Steel Chess India event.
BRX: टाटा स्टील चेस इन्डिया इभेन्टआव डी. गुकेशनि जायगायाव निहाल सरीनखौ लानाय जादों ।
--------------------------------------------------

Translating:  37%|█████████▉                 | 368/1000 [05:14<08:24,  1.25it/s]

[368/1000]
EN: Dibyendu Barua called D Gukesh’s withdrawal a big setback for organisers and fans.
BRX: डी.गुकेशनि ओंखारनायखौ आफादगिरिफोर आरो नायगिरिफोरनि थाखाय मोनसे गिदिर हेंथा होन्ना बुंनाय जादों |
--------------------------------------------------

Translating:  37%|█████████▉                 | 369/1000 [05:15<07:51,  1.34it/s]

[369/1000]
EN: Viswanathan Anand returned to play Tata Steel Chess India after six years away.
BRX: भारत क्रिकेट टीमनि गिबि मेचआ इं 2020 माइथायनि गेजेरसिम दावगालांनो गोनां जादोंमोन.
--------------------------------------------------

Translating:  37%|█████████▉                 | 370/1000 [05:16<08:10,  1.28it/s]

[370/1000]
EN: Viswanathan Anand said “It was exhausting not playing” while explaining his return.
BRX: भारत क्रिकेट टीमनि गाहाय सासे गेलेगिरिआ गावनि गिबि मेचआव गेलेनायखौ रोखा खालामना होदों ।
--------------------------------------------------

Translating:  37%|██████████                 | 371/1000 [05:16<07:42,  1.36it/s]

[371/1000]
EN: Viswanathan Anand was set to open against Wesley So in the seventh edition.
BRX: अस्ट्रेलियानि गिबि टेस्ट मेचआव भारतखौ फेजेन्नो थाखाय बे गेलेनाया जाफुंसार जानो हागौ.
--------------------------------------------------

Translating:  37%|██████████                 | 372/1000 [05:17<07:54,  1.32it/s]

[372/1000]
EN: The tournament director said Tata Steel Chess India will be held in January going forward.
BRX: भारत क्रिकेट एसोसिएशननि गाहाय मावख 'गिरिया बुंदों दि बे बोसोरनि सिगां इं 2020 माइथायनि गेजेरसिमाव भारतनि गिबि मेचआ जानो हागौ.
--------------------------------------------------

Translating:  37%|██████████                 | 373/1000 [05:18<07:37,  1.37it/s]

[373/1000]
EN: The Tata Steel Chess India event offered equal prize purses of $41,500 in open and women’s.
BRX: टाटा स्टील चेस इन्डिया इभेन्टआ अपेन आरो आइजोफोराव 41,500 डलारनि समान बान्था पार्स जासिदोंमोन.
--------------------------------------------------

Translating:  37%|██████████                 | 374/1000 [05:18<07:06,  1.47it/s]

[374/1000]
EN: Viswanathan Anand backed the Total Chess World Championship Tour approved by FIDE.
BRX: भारत आरो नेपालनि गेजेराव गेजेर थाखोनि क्रिकेट गेलेनाया जाफुंसारदों ।
--------------------------------------------------

Translating:  38%|██████████▏                | 375/1000 [05:19<07:04,  1.47it/s]

[375/1000]
EN: The Total Chess World Championship Tour will crown a new “FIDE World Combined” champion.
BRX: गासै दाबा बुहुमनां चेम्पियनशिप टुरआ मोनसे गोदान @FIDE मुलुग जथाय चेम्पियनखौ मुकुट गानगोन |
--------------------------------------------------

Translating:  38%|██████████▏                | 376/1000 [05:19<06:50,  1.52it/s]

[376/1000]
EN: The tour will be held across fast classic, rapid and blitz formats.
BRX: बे दावबायनाया गोख्रै क्लासिक/रेपिड आरो ब्लिटज फरमेटआव खुंनाय जागोन.
--------------------------------------------------

Translating:  38%|██████████▏                | 377/1000 [05:20<07:10,  1.45it/s]

[377/1000]
EN: Anand said Norway Chess has a serious long-term proposal for the new tour.
BRX: आनन्दआ बुंदोंमोन दि नर्वे चेसआ गोदान दावबायनायनि थाखाय मोनसे गोब्राब गोलाव समनि थांखि दंपाटों ।
--------------------------------------------------

Translating:  38%|██████████▏                | 378/1000 [05:21<07:18,  1.42it/s]

[378/1000]
EN: Anand said the sport benefits when Magnus Carlsen competes in major events.
BRX: आनन्दआ बुंदोंमोन दि गेलेमुआ मुलाम्फा जायो जेब्ला मैग्नस कार्लसनआ गाहाय आयदाफोराव बाहागो लायो |
--------------------------------------------------

Translating:  38%|██████████▏                | 379/1000 [05:22<07:23,  1.40it/s]

[379/1000]
EN: Wesley So said he proposed a draw against Praggnanandhaa, not the arbiters.
BRX: वेसलेआ बुङो दि बिथाङा प्रज्ञानन्दनि बेरेखायै ड्रनि थांखि लादोंमोन.
--------------------------------------------------

Translating:  38%|██████████▎                | 380/1000 [05:23<07:55,  1.30it/s]

[380/1000]
EN: Praggnanandhaa had one second left before stopping the clock to call the arbiter.
BRX: प्रज्ञानन्दहा रेफारिखौ लिंहरनो थाखाय घड़ीखौ बन्द खालामनायनि सिगां से सेकेन्ड दंबावोमोनपाइ ।
--------------------------------------------------

Translating:  38%|██████████▎                | 381/1000 [05:23<07:46,  1.33it/s]

[381/1000]
EN: Nihal Sarin won the 2026 Tata Steel Chess India Rapid Tournament in Kolkata.
BRX: लाहिर खानआ इं 2026 माइथायाव भारतखौ आवगायो ।
--------------------------------------------------

Translating:  38%|██████████▎                | 382/1000 [05:24<08:10,  1.26it/s]

[382/1000]
EN: Ian Nepomniachtchi criticised hotel conditions during the 2025 Chess World Cup in Goa.
BRX: इं 2025 माइथायनि चेस मुलुग कापनि समाव इयान नेपमनियाच्चीआ हटेलनि थासारिफोरखौ सावरायदोंमोनपाटों ।
--------------------------------------------------

Translating:  38%|██████████▎                | 383/1000 [05:25<08:47,  1.17it/s]

[383/1000]
EN: Ian Nepomniachtchi said organisers chose one of the worst hotels for the Goa event.
BRX: इयान नेपोमनियाच्चीआ बुंदोंमोन दि खुंगिरिफोरा गवा हाबाफारिनि थाखाय बयनिख्रुइ गाज्रिसिन हटेलफोरनि गेजेराव मोनसेखौ सायख.दोंमोन |
--------------------------------------------------

Translating:  38%|██████████▎                | 384/1000 [05:26<08:53,  1.16it/s]

[384/1000]
EN: Nepomniachtchi lost to Diptayan Ghosh after receiving a bye into round two.
BRX: नेपनियाच्चीआ नैथि राउन्डआव बाइ मोननायनि उनाव दीप्तायन घोषजों जेनदोंमोन.
--------------------------------------------------

Translating:  38%|██████████▍                | 385/1000 [05:27<09:26,  1.08it/s]

[385/1000]
EN: PGTI’s 2026 schedule was drawn up only till March-end, featuring six events.
BRX: पि. जि. टि. आइ. नि 2026 मायथाइनि समफारिखौ मार्चनि जोबनायसिमल. बानायनाय जादोंमोन |
--------------------------------------------------

Translating:  39%|██████████▍                | 386/1000 [05:28<09:55,  1.03it/s]

[386/1000]
EN: PGTI planned no more than 25 tournaments in 2026 after holding 36 events last year.
BRX: पि.जि.टि.आइ.आ थांनाय बोसोराव 36 इभेन्टफोर खुंनायनि उनाव 2026 मायथाइयाव 25 नि बांसिन टुर्नामेन्टफोरखौ बिथांखि लायाखैमोन |
--------------------------------------------------

Translating:  39%|██████████▍                | 387/1000 [05:29<10:24,  1.02s/it]

[387/1000]
EN: PGTI’s main tour offered ₹35 crore prize money in 2025, up from ₹24 crore.
BRX: पि.जि.टि.आइ. नि गाहाय दावबायनाया 2025 मायथाइयाव 24 कौटि रांनिफ्राय बांनानै 35 कौटि रांनि बान्था होदोंमोन |
--------------------------------------------------

Translating:  39%|██████████▍                | 388/1000 [05:30<10:32,  1.03s/it]

[388/1000]
EN: OWGR granted LIV Golf accreditation for the first time, awarding points to top-10 finishers.
BRX: अ.डब्लिउ.ज.आर.आ गिबि खेब एल.आइ.भि. गल्फनि गनायथि होदोंमोन |
--------------------------------------------------

Translating:  39%|██████████▌                | 389/1000 [05:31<10:07,  1.01it/s]

[389/1000]
EN: LIV Golf expanded tournaments from 54 to 72 holes in 2026, paving the approval.
BRX: एल.आइ.भि. गल्फआ इं 2026 माइथायाव 54 निफ्राय 72 ह 'लसिम टुर्नामेन्टखौ फेहेरदोंमोन |
--------------------------------------------------

Translating:  39%|██████████▌                | 390/1000 [05:33<12:04,  1.19s/it]

[390/1000]
EN: OWGR said LIV Golf did not meet all eligibility standards under its requirements.
BRX: अ.डब्लिउ.ज.आर.आ बुंदोंमोन दि एल.आइ.भि. गल्फआ बेनि गोनांथिनि सिङाव गासिबो रोंग 'थि मानथाखोफोरखौ मोनफिनाखैमोन |
--------------------------------------------------

Translating:  39%|██████████▌                | 391/1000 [05:34<11:24,  1.12s/it]

[391/1000]
EN: LIV Golf’s season-opening event in Riyadh was set to start with 57 players.
BRX: रियादआव एल. आइ. भि. गल्फनि सिजन-अपनिंग इभेन्टआ 57 गेलेगिरिफोरजों जुरिजेननो थि खालाम जादोंमोनपाटों ।
--------------------------------------------------

Translating:  39%|██████████▌                | 392/1000 [05:35<10:47,  1.06s/it]

[392/1000]
EN: International Series India was expected to move from DLF Golf and Country Club to Bengaluru.
BRX: हादोर गेजेरारि सिरिज भारतखौ डी.एल.एफ. गल्फ आरो कन्ट्री क्लाबनिफ्राय बेंगलुरूआव लांनायनि मिजिं दंमोन |
--------------------------------------------------

Translating:  39%|██████████▌                | 393/1000 [05:36<10:07,  1.00s/it]

[393/1000]
EN: Bryson DeChambeau and Joaquin Niemann were key draws at International Series India 2025.
BRX: ब्राइसन डीचेमबेउ आरो जोकिन नीमानआ इन्टारनेशनेल सिरिज इन्डिया 2025 आव गाहाय ड्रआव दंमोन |
--------------------------------------------------

Translating:  39%|██████████▋                | 394/1000 [05:37<09:24,  1.07it/s]

[394/1000]
EN: Ollie Schniederjans won International Series India 2025 by four shots in Gurugram.
BRX: भारत आरो बांग्लादेशनि गेजेराव जानाय मेचफोरनि गेजेराव मोनसेआ जानो हाथावनामोन ।
--------------------------------------------------

Translating:  40%|██████████▋                | 395/1000 [05:38<11:28,  1.14s/it]

[395/1000]
EN: Rahul Singh said International Series organisers remained committed to returning to India.
BRX: राहुल सिंहआ बुंदोंमोन दि हादोर गेजेरारि सिरिजनि खुंगिरिफोरा भारतआव फैफिन्नायनि थाखाय थि जाना दंमोनतना ।
--------------------------------------------------

Translating:  40%|██████████▋                | 396/1000 [05:41<15:31,  1.54s/it]

[396/1000]
EN: PGTI launched a league with six franchises, with each franchise buying 10 players.
BRX: पि. जि.टि.आइ.आ मोनद-2 फ्रेन्चाइजीफोरजों मोनसे लीग जागायदोंमोन | जेराव मोनफ्रोमबो फ्रेन्चाइजिआ गं 10 गेलेगिरिफोर बायदोंमोन/जि.पि. टि. आइ. आ गासै सेथिनिफ्राय नैथिसिम सौहैनो हानायखौ गनायथि होदोंमोन |
--------------------------------------------------

Translating:  40%|██████████▋                | 397/1000 [05:42<13:59,  1.39s/it]

[397/1000]
EN: The PGTI league’s first edition was planned across three courses in Delhi-NCR.
BRX: पि.जि.टि.आइ. लीगनि गिबि सुजुनायखौ दिल्ली-एन.सि.आर. आव मोनथाम फरायफारिफोराव बिथांखि लानाय जादोंमोन |
--------------------------------------------------

Translating:  40%|██████████▋                | 398/1000 [05:42<12:13,  1.22s/it]

[398/1000]
EN: Shubhankar Sharma missed cuts in 21 of 28 events in 2025, the report said.
BRX: इं 2025 माइथायाव 28 इभेन्टफोरनि गेजेराव 21आव कट गैयै जानायनि थाखाय शुभंकर शर्माखौ सायख 'नाय जादों ।
--------------------------------------------------

Translating:  40%|██████████▊                | 399/1000 [05:43<10:47,  1.08s/it]

[399/1000]
EN: Shubhankar Sharma regained playing rights for 2026 via Q-School, finishing tied-second.
BRX: इं 2026 माइथायनि थाखाय क्विन - स्कूलनि गेजेरजों गावस्रानाय राइट्सखौ मोनफिनदोंमोन |
--------------------------------------------------

Translating:  40%|██████████▊                | 400/1000 [05:44<09:58,  1.00it/s]

[400/1000]
EN: Vietnam targets 22 to 25 million international visitors by 2026.
BRX: भियेटनामआ 2026 मायथाइसिमाव 22 निफ्राय 25 मिलियन हादोर गेजेरारि दावबायारिफोरखौ थांखि लायो |
--------------------------------------------------

Translating:  40%|██████████▊                | 401/1000 [05:46<11:37,  1.16s/it]

[401/1000]
EN: Operations teams monitor weather to minimize passenger inconvenience.
BRX: सालायगिरि हानजाफोरा दावबायारिफोरनि जेंनाफोरखौ बाङाइ खालामनो थाखाय बोथोरखौ नोजोर होयोपाटोंनो हानाय नङा.
--------------------------------------------------

Translating:  40%|██████████▊                | 402/1000 [05:47<11:25,  1.15s/it]

[402/1000]
EN: IndiGo announces Amsterdam debut as first long-haul European destination.
BRX: इन्डिगोआ एम्स्टर्डामखौ गिबि गोलाव जानथाय इउरोपियान थांखि थावनि महरै फोसावनाय जादों |
--------------------------------------------------

Translating:  40%|██████████▉                | 403/1000 [05:48<10:48,  1.09s/it]

[403/1000]
EN: Air India crash committee investigates Boeing 787-8 Ahmedabad tragedy.
BRX: एयर इन्डिया क्रास कमितिआ बयिंग 787-8 आहमेदाबाद दुखुगोनां जाथायखौ नायबिजिरदों |
--------------------------------------------------

Translating:  40%|██████████▉                | 404/1000 [05:48<10:03,  1.01s/it]

[404/1000]
EN: IndiGo aims for forty percent international capacity share by 2030.
BRX: इन्डिगोआ 2030 मायथाइसिमाव ब्रैजि जौखोन्दो हादोर गेजेरारि गोहोनि बाहागो लानायनि थांखि लादोंमोन |
--------------------------------------------------

Translating:  40%|██████████▉                | 405/1000 [05:49<09:21,  1.06it/s]

[405/1000]
EN: One survivor rescued from Air India crash site in Ahmedabad.
BRX: अहमदाबादआव एयर इन्डिया क्रास साइटनिफ्राय सासे थांना थानायखौ रैखा खालामनाय जादों |
--------------------------------------------------

Translating:  41%|██████████▉                | 406/1000 [05:50<08:55,  1.11it/s]

[406/1000]
EN: Jetstar Asia closure frees five hundred million dollars for Qantas.
BRX: जेटस्टार एशिया बन्द जानाया क्वान्टासनि थाखाय बाजौ मिलियन डलार उदां खालामो.
--------------------------------------------------

Translating:  41%|██████████▉                | 407/1000 [05:51<08:54,  1.11it/s]

[407/1000]
EN: Qantas Group announces closure of Singapore-based Jetstar Asia.
BRX: क्वान्टास ग्रुपआ सिंगापुरआव थानाय जेटस्टार एशियाखौ बन्द खालामनायनि फोसावथाइ होयो.
--------------------------------------------------

Translating:  41%|███████████                | 408/1000 [05:52<09:05,  1.09it/s]

[408/1000]
EN: IndiGo launches Mumbai-Manchester flights using Norse aircraft.
BRX: इन्डियाया नर्स बिरखंफोरखौ बाहायनानै मुम्बाइ-मेनचेस्टर बिरग्रा दिङाफोरखौ जागायोपाटिनो ।
--------------------------------------------------

Translating:  41%|███████████                | 409/1000 [05:53<09:13,  1.07it/s]

[409/1000]
EN: IndiGo transitions to A350-900 aircraft for European expansion by 2027.
BRX: इं 2027 मायथाइसिमाव ए350-900 बिरखंखौ फेहेरनो थाखाय इन्डिग 'आ थांखि लायो.
--------------------------------------------------

Translating:  41%|███████████                | 410/1000 [05:54<08:47,  1.12it/s]

[410/1000]
EN: Air India Ahmedabad crash claims 242 lives including Vijay Rupani.
BRX: एयर इन्डिया आहमेदाबाद क्रासआ विजय रुपानीजों लोगोसे 242 सुबुंफोर जिउ खोमाना लायो |
--------------------------------------------------

Translating:  41%|███████████                | 411/1000 [05:55<08:35,  1.14it/s]

[411/1000]
EN: Thirteen Jetstar Asia A320s redeployed to Australia and New Zealand.
BRX: थामजिनै जेटस्टार एशिया ए320एसआ अस्ट्रेलिया आरो निउजिलेन्डआव फिन थिसनजादोंमोन.
--------------------------------------------------

Translating:  41%|███████████                | 412/1000 [05:55<08:14,  1.19it/s]

[412/1000]
EN: IndiGo issues fog advisory for Delhi and northern India passengers.
BRX: इन्डिगोआ दिल्ली आरो सा भारतनि दावबायारिफोरनि थाखाय खुवाजों बुंफबनाय बोसोन होयो |
--------------------------------------------------

Translating:  41%|███████████▏               | 413/1000 [05:56<08:51,  1.11it/s]

[413/1000]
EN: DGCA imposes ₹2 crore fine on Air India for safety lapses.
BRX: डी.जी.सी.ए.आ रैखाथि आंखालनि थाखाय एयर इन्डियानि सायाव ₹2 कौटि जरिमाना खालामदों |
--------------------------------------------------

Translating:  41%|███████████▏               | 414/1000 [05:57<09:11,  1.06it/s]

[414/1000]
EN: Sixteen intra-Asia routes lose only non-stop Changi connections.
BRX: द 'जिन इन्ट्रा-एशिया लामाफोरा खालि नान-स्टप चांगी सुंजाबनायफोरखौ खोमाना लायो.
--------------------------------------------------

Translating:  42%|███████████▏               | 415/1000 [05:58<08:55,  1.09it/s]

[415/1000]
EN: Bengaluru airport opens second runway to handle growing traffic.
BRX: बेंगालुरु बिरखं गाथोना बांलांनाय ट्रेफिकखौ सामलायनो थाखाय नैथि रानवे खुलिगोन |
--------------------------------------------------

Translating:  42%|███████████▏               | 416/1000 [05:59<08:41,  1.12it/s]

[416/1000]
EN: Air India Express pilot assaults passenger at Delhi airport terminal.
BRX: एयर इन्डिया एक्सप्रेसनि पाइलटआ दिल्ली बिरखं गाथोननि टार्मिनेलआव दावबायारिखौ गाग्लोबदोंमोन.
--------------------------------------------------

Translating:  42%|███████████▎               | 417/1000 [06:00<08:28,  1.15it/s]

[417/1000]
EN: Mumbai airport witnesses record passenger footfall during festive week.
BRX: मुम्बाइ बिरखं गाथोना फोरबोआरि सप्तानि समाव दावबायारिफोरनि आगानखौ रेबगान्थि खालामो →
--------------------------------------------------

Translating:  42%|███████████▎               | 418/1000 [06:01<08:09,  1.19it/s]

[418/1000]
EN: Dense fog disrupts IndiGo flight operations across North India.
BRX: गुदु खुवाया गासै सा भारतआव इन्डिगो बिरखं सालायनायाव हेंथा होयो →
--------------------------------------------------

Translating:  42%|███████████▎               | 419/1000 [06:01<07:56,  1.22it/s]

[419/1000]
EN: Go First insolvency resolution extends to third consecutive month.
BRX: गो फार्स्ट इनसलभेन्सि रिजोलुसनआ फारियै थामथि दानसिम गोसारदों |
--------------------------------------------------

Translating:  42%|███████████▎               | 420/1000 [06:03<08:45,  1.10it/s]

[420/1000]
EN: Akasa Air orders additional Boeing 737 Max aircraft for expansion.
BRX: अकासा एयरआ फुवारनायनि थाखाय दाजाबदेरनाय बयिंग 737 मैक्स बिरखंफोरखौ बिथोन होयोपाट्राङै ।
--------------------------------------------------

Translating:  42%|███████████▎               | 421/1000 [06:03<08:46,  1.10it/s]

[421/1000]
EN: Air India pilots union raises concerns over rest period violations.
BRX: एयर इन्डिया पाइलटफोरनि जुथाइया जिरायसमनि समखोन्दो सिफायनायफोरनि सायाव जिंगाबोदों |
--------------------------------------------------

Translating:  42%|███████████▍               | 422/1000 [06:04<08:26,  1.14it/s]

[422/1000]
EN: EU launches Entry-Exit System campaign for non-EU travellers.
BRX: इयुआ इयु नङि दावबायारिफोरनि थाखाय एन्ट्रि-इक्सिट सिस्टेम केम्पेन जागायजेनो |
--------------------------------------------------

Translating:  42%|███████████▍               | 423/1000 [06:05<08:31,  1.13it/s]

[423/1000]
EN: SpiceJet secures funding to revive grounded fleet operations soon.
BRX: स्पाइसजेटआ थाबैनो ग्राउन्डेड फ्लीट अपारेसनफोरखौ जोनोम होनो थाखाय रां बुथुमनायसैपाटों ।
--------------------------------------------------

Translating:  42%|███████████▍               | 424/1000 [06:06<08:25,  1.14it/s]

[424/1000]
EN: Bulgaria adopts Euro as legal tender from January first 2026.
BRX: बुलगेरियाया गिबि जानुवारि 2026 मायथाइनिफ्राय इउर 'खौ आयेनारि टेन्डर महरै नाजावदों |
--------------------------------------------------

Translating:  42%|███████████▍               | 425/1000 [06:07<09:00,  1.06it/s]

[425/1000]
EN: Vietnam grants forty-five day visa-free entry to twelve European nations.
BRX: भियेटनामआ जिनै इउरोपारि हादोरफोरनो ब्रैजिबा साननि भिसा-फ्री हाबनायखौ होयो |
--------------------------------------------------

Translating:  43%|███████████▌               | 426/1000 [06:08<08:38,  1.11it/s]

[426/1000]
EN: Indian government reverses ban on Sikh pilgrimages to Pakistan.
BRX: भारत सोरखारा पाकिस्तानाव सिख धोरोमदावबायारिफोरनि सायाव होबथानायनि उलथाखौ बोखारदों |
--------------------------------------------------

Translating:  43%|███████████▌               | 427/1000 [06:09<08:24,  1.14it/s]

[427/1000]
EN: Pakistan High Commission issues visas to twenty-one hundred Sikh pilgrims.
BRX: पाकिस्तान गोजौ आय.गआ नैजौ सिख धोरोमदावबायारिफोरनो भिसाखौ होयो |
--------------------------------------------------

Translating:  43%|███████████▌               | 428/1000 [06:10<08:49,  1.08it/s]

[428/1000]
EN: TSA ends shoe removal rule at domestic United States airports.
BRX: टि.एस.ए.आ नखरारि जथाइ रायजो आमेरिकानि बिरखं गाथोनफोराव जुथा बोखारनायनि खान्थिखौ फोजोबदों |
--------------------------------------------------

Translating:  43%|███████████▌               | 429/1000 [06:11<09:39,  1.02s/it]

[429/1000]
EN: Real ID enforcement charges tourists forty-five dollars for domestic flights.
BRX: नंगुबै आई.डी. बाहायनाया नखरारि बिरग्रा दिङाफोरनि थाखाय दावबायारिफोरनिफ्राय ब्रैजिबा डलार लायोांकानांगौ जायो |
--------------------------------------------------

Translating:  43%|███████████▌               | 430/1000 [06:12<09:30,  1.00s/it]

[430/1000]
EN: United States government shutdown causes forty-three day travel chaos.
BRX: जुथाइ रायजो आमेरिका सोरखारा बन्द जानाया ब्रैजि-थाम साननि दावबायनायाव दावराव-दावसि सोमजिहोयो |
--------------------------------------------------

Translating:  43%|███████████▋               | 431/1000 [06:13<09:10,  1.03it/s]

[431/1000]
EN: Government considers hotel industry infrastructure status for tax benefits.
BRX: सरकारा खाजोना मुलाम्फानि थाखाय हटेल दारिमिननि बिथायारि सानजथाइ मानथाखोखौ गनायो |
--------------------------------------------------

Translating:  43%|███████████▋               | 432/1000 [06:14<08:50,  1.07it/s]

[432/1000]
EN: Gajendra Singh Shekhawat announces infrastructure status proposal for hotels.
BRX: गजेन्द्र सिंह शेखावतआ हटेलफोरनि थाखाय बिथायारि सानजथाइयारि थाथायनि थांखिखौ फोसावदोंमोन |
--------------------------------------------------

Translating:  43%|███████████▋               | 433/1000 [06:17<14:31,  1.54s/it]

[433/1000]
EN: Tourism Ministry reboots Incredible India campaign with AI focus.
BRX: दावबायफालांगि मनत्रिआ आर्टिफिसियेल इन्टेलिजेन्सनि सायाव नोजोर होनानै इनक्रेडिबल इन्डिया केम्पेनखौ फिन जागायजेनो →
--------------------------------------------------

Translating:  43%|███████████▋               | 434/1000 [06:17<12:15,  1.30s/it]

[434/1000]
EN: Suman Billa confirms new digital-centric Incredible India strategy.
BRX: भारत आरो जापाननि गेजेराव सोमोन्दोआ जाफुंसारनायसै.
--------------------------------------------------

Translating:  44%|███████████▋               | 435/1000 [06:18<11:08,  1.18s/it]

[435/1000]
EN: India targets one trillion dollar tourism economy by 2047.
BRX: भारतआ 2047 मायथाइसिमाव से त्रिलियन डलारनि दावबायथाय रांखान्थिनि थांखि लायो →
--------------------------------------------------

Translating:  44%|███████████▊               | 436/1000 [06:19<09:57,  1.06s/it]

[436/1000]
EN: Centre sanctions fifty destinations for challenge mode tourism development.
BRX: मिरुआ चेलेन्ज मोड दावबायफालांगि जौगाथायनि थाखाय बाजि थांखि थावनिफोरखौ गनायथि होयो |
--------------------------------------------------

Translating:  44%|███████████▊               | 437/1000 [06:20<09:46,  1.04s/it]

[437/1000]
EN: Telangana adopts Sarathi portal for online RTA services.
BRX: तेलेंगानाया अनलाइन आर.टि.ए. सिबिथाइफोरनि थाखाय सारथि पर्टेलखौ नाजावदों |
--------------------------------------------------

Translating:  44%|███████████▊               | 438/1000 [06:21<09:04,  1.03it/s]

[438/1000]
EN: Ministry announces twelve thousand crore rupees for new tourism destinations.
BRX: मनत्रिआ गोदान दावबायथाय थांखि थावनिफोरनि थाखाय जिनै रोजा कौटि रां फोसावनाय जायो |
--------------------------------------------------

Translating:  44%|███████████▊               | 439/1000 [06:22<08:53,  1.05it/s]

[439/1000]
EN: Government allocates 1.34 billion dollars for tourism infrastructure development.
BRX: सोरखारा दावबायथाय बिथायारि सानजथाइ जौगाथायनि थाखाय 1.34 बिलियन डलार दानस्लायदों |
--------------------------------------------------

Translating:  44%|███████████▉               | 440/1000 [06:23<08:51,  1.05it/s]

[440/1000]
EN: India plans 2030 Commonwealth Games hosting to boost tourism.
BRX: भारतआ दावबायनायखौ बांहोनो थाखाय 2030 मायथाइनि कमनवेल्थ गेम्सनि हस्टिं खालामनो सानथांखि खालामदों |
--------------------------------------------------

Translating:  44%|███████████▉               | 441/1000 [06:24<08:35,  1.08it/s]

[441/1000]
EN: Census self-enumeration trial begins for digital population count.
BRX: डिजिटेल सुबुं अनजिमा साननायनि थाखाय सुबुं सानखो गाव-गुन्थि बिजिरनाया जागायजेनो →
--------------------------------------------------

Translating:  44%|███████████▉               | 442/1000 [06:24<08:28,  1.10it/s]

[442/1000]
EN: European Commission launches biometric border system awareness campaign.
BRX: इउ.आर.पि.आ गुबुन हादोरफोरजों सोमोन्दो लाखिनायनि थांखि लायो |
--------------------------------------------------

Translating:  44%|███████████▉               | 443/1000 [06:25<08:38,  1.07it/s]

[443/1000]
EN: Non-EU travellers face new digital border checks from October.
BRX: ई.यू. नङि दावबायारिफ्रा अक्टबरनिफ्राय गोदान डिजिटेल बर्डार चेकजों मोगा-मोगि जानो गोनां जायो ꯫
--------------------------------------------------

Translating:  44%|███████████▉               | 444/1000 [06:27<11:40,  1.26s/it]

[444/1000]
EN: Dover ferry passengers register first for EU entry-exit system.
BRX: ड 'भार फेरि दावबायारिफ्रा इयुआव हाबफैनाय- ओंखारलांनाय खान्थिनि थाखाय गिबियाव रेबथुमना लायो →
--------------------------------------------------

Translating:  44%|████████████               | 445/1000 [06:29<11:04,  1.20s/it]

[445/1000]
EN: Eurostar business travellers gradually included in EES rollout.
BRX: युर.स्टार फालांगियारि दावबायारिफोरखौ लासै-लासै इ.इ.एस. रोलआउटआव सोफादेरनाय जादों |
--------------------------------------------------

Translating:  45%|████████████               | 446/1000 [06:29<09:41,  1.05s/it]

[446/1000]
EN: India extends e-visa facility to citizens of five more nations.
BRX: भारतआ आरोबाव मोनबा हादोरनि नोगोरारिफोरनो ई-भिसा खाबु होयो.
--------------------------------------------------

Translating:  45%|████████████               | 447/1000 [06:30<08:44,  1.05it/s]

[447/1000]
EN: Karnataka announces tourism policy targeting fifty billion dollar investment
BRX: कर्नाटकआ 50 कौटि डलार रां थिसननायनि थांखि लानानै दावबायफालांगि खान्थि फोसावदों
--------------------------------------------------

Translating:  45%|████████████               | 448/1000 [06:31<08:32,  1.08it/s]

[448/1000]
EN: GST Council reduces tax on hotel rooms below seven thousand five hundred rupees.
BRX: जिएसटि काउनसिला हटेलनि खथानि खाजोनाखौ स्नि रोजा बाजौ रांनि गाहायाव लाबोयो.
--------------------------------------------------

Translating:  45%|████████████               | 449/1000 [06:32<08:20,  1.10it/s]

[449/1000]
EN: Ministry of Tourism launches Swadesh Darshan 3.0 for sustainable tourism.
BRX: दावबायफालांगि मनत्रिआ अरायथा दावबायनायनि थाखाय स्वदेश दर्शन 3.0 खौ जागायजेनो |
--------------------------------------------------

Translating:  45%|████████████▏              | 450/1000 [06:33<08:30,  1.08it/s]

[450/1000]
EN: Civil Aviation Ministry orders probe into Delhi airport assault case.
BRX: नोगोरारि बिरखं रोगानाय मनत्रिआ दिल्ली बिरखं गाथोन गाग्लोबनायनि केसखौ नायसंनो बिथोन होयो |
--------------------------------------------------

Translating:  45%|████████████▏              | 451/1000 [06:34<09:01,  1.01it/s]

[451/1000]
EN: Government approves UDAN 5.0 with focus on helicopter services.
BRX: यु.डि.ए.एन. 5.0 खौ हेलिकाफ्टार सिबिथाइफोरनि सायाव नोजोर होनानै सरकारा गनायथि होदों |
--------------------------------------------------

Translating:  45%|████████████▏              | 452/1000 [06:35<08:40,  1.05it/s]

[452/1000]
EN: Kerala declares tourism as industry status for hotels and resorts.
BRX: केरेलाया हतेल आरो रिसर्टफोरनि थाखाय दावबायनायखौ दारिमिननि थामान महरै फोसावदोंमोन |
--------------------------------------------------

Translating:  45%|████████████▏              | 453/1000 [06:35<08:18,  1.10it/s]

[453/1000]
EN: West Bengal secures second rank in foreign tourist arrivals.
BRX: सोनाब बंग 'आ गुबुन हादोरारि दावबायारिफोर फैनायाव नैथि थाखोखौ मोननो हादोंमोन.
--------------------------------------------------

Translating:  45%|████████████▎              | 454/1000 [06:36<08:04,  1.13it/s]

[454/1000]
EN: Mamata Banerjee hails West Bengal's international tourism milestone.
BRX: ममता बेनर्जीया सोनाब बंग 'नि हादोर गेजेरारि दावबायथाय माइलस्टोनखौ बाख्नायदों |
--------------------------------------------------

Translating:  46%|████████████▎              | 455/1000 [06:37<08:05,  1.12it/s]

[455/1000]
EN: Maharashtra leads foreign tourist arrivals with 3.71 million visitors.
BRX: महाराष्ट्रआ 3.71 मिलियन नायगिरिफोरजों गुबुन हादोरारि दावबायारि सफैनायाव सिगांसिन जाना दं |
--------------------------------------------------

Translating:  46%|████████████▎              | 456/1000 [06:38<08:11,  1.11it/s]

[456/1000]
EN: West Bengal records 3.12 million foreign tourist visits nationwide.
BRX: सोनाब बंग 'आ हादोरनाङै 3.12 कौटि गुबुन हादोरारि दावबायारि दावबायनायनि रेबगान्थि खालामदों |
--------------------------------------------------

Translating:  46%|████████████▎              | 457/1000 [06:39<08:30,  1.06it/s]

[457/1000]
EN: Uttar Pradesh tops domestic tourism with 646.81 million visitors.
BRX: उत्तर प्रदेशआ 646.81 मिलियन दावबायारिफोरजों नखरारि दावबायनायाव बयनिख्रुइ जौसिन जायगा आवग्रिना दंपाइ ।
--------------------------------------------------

Translating:  46%|████████████▎              | 458/1000 [06:40<07:59,  1.13it/s]

[458/1000]
EN: Tamil Nadu records 306.84 million domestic tourist footfall.
BRX: तामिलनाडुआ 30.68 कौटि नखरारि दावबायारिफोरनि आगानखौ रेबगान्थि खालामदों |
--------------------------------------------------

Translating:  46%|████████████▍              | 459/1000 [06:41<07:58,  1.13it/s]

[459/1000]
EN: India receives 2,948.19 million domestic tourists during 2024.
BRX: भारतआ इं 2024 माइथायनि गेजेराव 2,948.19 मिलियन नखरारि दावबायारिफोरखौ आजावदों |
--------------------------------------------------

Translating:  46%|████████████▍              | 460/1000 [06:43<12:13,  1.36s/it]

[460/1000]
EN: Foreign tourist visits to India touch 20.94 million in 2024.
BRX: 2024 मायथाइयाव भारतआव गुबुन हादोरारि दावबायारि दावबायनाया 20.94 मिलियनसिम सौहैदों |
--------------------------------------------------

Translating:  46%|████████████▍              | 461/1000 [06:44<10:47,  1.20s/it]

[461/1000]
EN: Domestic tourism records 17.51 percent growth over previous year.
BRX: नखरारि दावबायनाया थांनाय बोसोरनि रुजुनायाव 17.51 जौखोन्दो जौगानायखौ रेबगान्थि खालामदों |
--------------------------------------------------

Translating:  46%|████████████▍              | 462/1000 [06:45<09:27,  1.05s/it]

[462/1000]
EN: International tourist arrivals grow 8.84 percent in 2024.
BRX: 2024 मायथाइयाव हादोर गेजेरारि दावबायारि फैनाया 8.84 जौखोन्दो बांदों |
--------------------------------------------------

Translating:  46%|████████████▌              | 463/1000 [06:46<08:56,  1.00it/s]

[463/1000]
EN: Maha Kumbh Mela attracts 663 million visits across forty-five days.
BRX: महा कुम्भ मेलाया ब्रैजिबा सानाव 663 मिलियन दावबायनायखौ गोसो बोहोयो |
--------------------------------------------------

Translating:  46%|████████████▌              | 464/1000 [06:47<08:29,  1.05it/s]

[464/1000]
EN: Prayagraj witnesses 660 million pilgrims at Sangam confluence.
BRX: प्रयागराजआ संगम गोरोबथिलियाव 660 मिलियन धोरोमदावबायारिफोरखौ साखि होयो |
--------------------------------------------------

Translating:  46%|████████████▌              | 465/1000 [06:48<08:46,  1.02it/s]

[465/1000]
EN: Vietnam welcomes 1.73 million international visitors during October 2025.
BRX: भियेटनामआ अक्टबर 2025 मायथाइनि समाव 1.73 मिलियन हादोर गेजेरारि दावबायारिफोरखौ बरायनो थाखाय थांखि लायो →
--------------------------------------------------

Translating:  47%|████████████▌              | 466/1000 [06:49<08:44,  1.02it/s]

[466/1000]
EN: Vietnam records 13.8 percent monthly growth in foreign tourist arrivals.
BRX: भियेटनामआ गुबुन हादोरारि दावबायारि सफैनायाव 13.8 जौखोन्दो दानारि जौगानायखौ रेबगान्थि खालामदों |
--------------------------------------------------

Translating:  47%|████████████▌              | 467/1000 [06:49<08:24,  1.06it/s]

[467/1000]
EN: India attracts only ten million international tourists annually currently.
BRX: भारतआ आथिखालाव बोसोरफ्रामबो जि मिलियनसो हादोर गेजेरारि दावबायारिफोरखौ गोसो बोहोयो ꯫
--------------------------------------------------

Translating:  47%|████████████▋              | 468/1000 [06:50<08:00,  1.11it/s]

[468/1000]
EN: France welcomes ninety million tourists against India's ten million.
BRX: फ्रान्सआ भारतनि 10 मिलियननि बेरेखायै 90 मिलियन दावबायारिफोरखौ बरायनो थाखाय थांखि लायो →
--------------------------------------------------

Translating:  47%|████████████▋              | 469/1000 [06:51<07:21,  1.20it/s]

[469/1000]
EN: Spain receives eighty-four million international visitors annually.
BRX: स्पेनआ बोसोरफ्रामबो ब्रै कौटि हादोर गेजेरारि दावबायारिफोर फैयो |
--------------------------------------------------

Translating:  47%|████████████▋              | 470/1000 [06:52<07:01,  1.26it/s]

[470/1000]
EN: United States hosts eighty million foreign tourists every year.
BRX: जुथाइ रायजो आमेरिकाया बोसोरफ्रोमबो 80 मिलियन गुबुन हादोरारि दावबायारिफोरखौ सामलायो |
--------------------------------------------------

Translating:  47%|████████████▋              | 471/1000 [06:52<07:01,  1.25it/s]

[471/1000]
EN: India's pre-Covid tourist arrival figures remain unmatched after six years.
BRX: भारतनि आगु-कविड दावबायारि सफैनायनि अनजिमाया द'बोसोरनि उनाव रुजुजायै जाना थायो.
--------------------------------------------------

Translating:  47%|████████████▋              | 472/1000 [06:53<07:23,  1.19it/s]

[472/1000]
EN: Tourism contributes 5.2 percent to India's current GDP.
BRX: दावबायनाया भारतनि आथिखालनि जि.डि.प.आव 5.2 जौखोन्दो बिहोमा होयो |
--------------------------------------------------

Translating:  47%|████████████▊              | 473/1000 [06:54<07:24,  1.18it/s]

[473/1000]
EN: Tourism sector supports 84 million livelihoods across India.
BRX: दावबायथाय सेक्टरआ गासै भारतआव 84 मिलियन सुबुंफोरनि जिउ राहाखौ हेफाजाब होयो |
--------------------------------------------------

Translating:  47%|████████████▊              | 474/1000 [06:55<07:30,  1.17it/s]

[474/1000]
EN: FICCI predicts 250 billion dollar tourism opportunity by 2030.
BRX: एफ.आइ.सि.सिआ 2030 मायथाइसिमाव 250 बिलियन डलारनि दावबायनायनि खाबुखौ मिजिंथियो |
--------------------------------------------------

Translating:  48%|████████████▊              | 475/1000 [06:56<08:15,  1.06it/s]

[475/1000]
EN: ICRA reports hotel demand to exceed supply in coming years.
BRX: आइ.सि.आर.ए.आ फैगौ बोसोरफोराव हटेलनि गोनांथिया दैथायनायखौ बारायनो थाखाय फोरमायथि होयो →
--------------------------------------------------

Translating:  48%|████████████▊              | 476/1000 [06:57<08:54,  1.02s/it]

[476/1000]
EN: Global travel industry generates 10.9 trillion dollars for economies.
BRX: बुहुमनां दावबायथाय दारिमिना रांखान्थिनि थाखाय 10.9 त्रिलियन डलार दिहुनोपाट खालामो.
--------------------------------------------------

Translating:  48%|████████████▉              | 477/1000 [06:58<08:59,  1.03s/it]

[477/1000]
EN: Travel and tourism accounts for ten percent of global GDP.
BRX: दावबायनाय आरो दावबायनाया बुहुमनां जि.डि.पि. नि जि जौखोन्दो जायो |
--------------------------------------------------

Translating:  48%|████████████▉              | 478/1000 [06:59<08:49,  1.01s/it]

[478/1000]
EN: Vietnam targets 22 to 26 million international visitors by 2026.
BRX: भियेटनामआ 2026 मायथाइसिमाव 22 निफ्राय 26 मिलियन हादोर गेजेरारि दावबायारिफोरखौ थांखि लायो |
--------------------------------------------------

Translating:  48%|████████████▉              | 479/1000 [07:00<08:38,  1.01it/s]

[479/1000]
EN: Belgium citizens enjoy forty-five day visa-free Vietnam travel.
BRX: बेल्जियामनि नोगोरारिफोरा ब्रैजिबा साननि भिसा-फ्री भियेटनाम दावबायनायखौ रंजायो →
--------------------------------------------------

Translating:  48%|████████████▉              | 480/1000 [07:02<08:56,  1.03s/it]

[480/1000]
EN: Poland nationals receive visa-free entry to Vietnam under new scheme.
BRX: पलेन्डनि नोगोरारिफोरा गोदान स्किमनि सिङाव भियेटनामाव भिजा-फ्री हाबफैनायखौ मोनो |
--------------------------------------------------

Translating:  48%|████████████▉              | 481/1000 [07:02<08:27,  1.02it/s]

[481/1000]
EN: Swiss passport holders travel visa-free to Vietnam for forty-five days.
BRX: स्विस पासपोर्ट हमग्राया ब्रैजिबा साननि थाखाय भियेटनामाव भिसाबिगैयै दावबायदों |
--------------------------------------------------

Translating:  48%|█████████████              | 482/1000 [07:03<08:43,  1.01s/it]

[482/1000]
EN: Saudi Red Sea Authority issues twelve marine tourism licences.
BRX: साउदीनि गोजा लैथो खुंथाइआ जिनै लैथोआरि दावबायनायनि गनायथि बिलाइ होयोपाटों ।
--------------------------------------------------

Translating:  48%|█████████████              | 483/1000 [07:04<07:54,  1.09it/s]

[483/1000]
EN: Red Sea Cruises receives approval under Cruise Saudi brand.
BRX: रेड सी क्रूजआ क्रुज सउदी ब्रान्डनि सिङाव गनायथि मोनो |
--------------------------------------------------

Translating:  48%|█████████████              | 484/1000 [07:06<09:21,  1.09s/it]

[484/1000]
EN: Sindalah Marina in NEOM secures Saudi marine tourism licence.
BRX: एन.ई.अ.एम.आव सिन्दालाह मेरिनाया सउदी लैथोआरि दावबायनायनि गनायथिखौ मोन्नो हादोंमोनपाटानियेटफोर ।
--------------------------------------------------

Translating:  48%|█████████████              | 485/1000 [07:07<08:47,  1.02s/it]

[485/1000]
EN: Dolphin Beach Resort Marina obtains Yanbu operating approval.
BRX: डल्फिन बीच रिसर्ट मेरिनाआ यानबुनि सामलायनायनि गनायथि मोनो.
--------------------------------------------------

Translating:  49%|█████████████              | 486/1000 [07:07<08:07,  1.05it/s]

[486/1000]
EN: Jeddah Municipality Marina included in Saudi licensing round.
BRX: जेद्दा नोगोरखुंथाय मेरिनाखौ साउदी लाइसेन्सिं राउन्डआव सोफादेरनाय जादों |
--------------------------------------------------

Translating:  49%|█████████████▏             | 487/1000 [07:08<07:47,  1.10it/s]

[487/1000]
EN: Deep Seas Shipping Agency gains tourism shipping agent licence.
BRX: डीप सीज शिपिं एजेन्सिआ दावबायफालांगि सिपिं एजेन्टनि लाइसेन्स मोनो |
--------------------------------------------------

Translating:  49%|█████████████▏             | 488/1000 [07:09<07:34,  1.13it/s]

[488/1000]
EN: Venice extends day-tripper entrance fee to sixty days.
BRX: वेनिसआ सानसेयारि दावबायनायनि हाबग्रा मासुलखौ दजि सानसिम फुवारदों |
--------------------------------------------------

Translating:  49%|█████████████▏             | 489/1000 [07:10<07:33,  1.13it/s]

[489/1000]
EN: Venice charges day-trippers from Friday to Sunday between April and July.
BRX: वेनिसआ एप्रिल आरो जुलाइनि गेजेराव सुक्रुबारनिफ्राय रबिबारसिम सानसेयारि दावबायग्राफोरखौ बेसेन होयो |
--------------------------------------------------

Translating:  49%|█████████████▏             | 490/1000 [07:11<07:32,  1.13it/s]

[490/1000]
EN: Simone Venturini calls Venice entry fee tangible innovation tool.
BRX: सिमोन भेन्टुरिनीआ वेनिसआव हाबनायनि मासुलखौ गुबै गोदान दिहुनथाय आगजु बुङो |
--------------------------------------------------

Translating:  49%|█████████████▎             | 491/1000 [07:12<07:57,  1.07it/s]

[491/1000]
EN: Amsterdam introduces tourist fees to fight overtourism congestion.
BRX: एम्स्टर्डामआ ओभरटुरिजम होंगो-गोहोखौ होबथानो थाखाय दावबायारि मासुलफोर जागायजेनो →
--------------------------------------------------

Translating:  49%|█████████████▎             | 492/1000 [07:13<07:22,  1.15it/s]

[492/1000]
EN: Greece passes laws limiting visitor numbers to popular islands.
BRX: ग्रिसा मुंदांखा दिपफोराव दावबायारिफोरनि अनजिमाखौ सिमा होनाय आयेनफोर पास खालामो |
--------------------------------------------------

Translating:  49%|█████████████▎             | 493/1000 [07:13<07:14,  1.17it/s]

[493/1000]
EN: Japan implements tourist fees to manage overcrowding at sites.
BRX: जापाना थावनिफोराव बांद्राय होंगो-गोहोखौ सामलायनो थाखाय दावबायारिनि मासुल बाहायदों |
--------------------------------------------------

Translating:  49%|█████████████▎             | 494/1000 [07:14<07:11,  1.17it/s]

[494/1000]
EN: Hurricane Melissa devastates Jamaica's tourism infrastructure.
BRX: हारिकेन मेलिसाया जमैकानि दावबायनायनि सानजथाइखौ फोजोबस्राङो.
--------------------------------------------------

Translating:  50%|█████████████▎             | 495/1000 [07:15<07:15,  1.16it/s]

[495/1000]
EN: Jamaica opens for business after Hurricane Melissa recovery.
BRX: जमैकाआ हारिकेन मेलिसा रिकभार जानायनि उनाव फालांगिनि थाखाय खुलियो ꯫
--------------------------------------------------

Translating:  50%|█████████████▍             | 496/1000 [07:16<07:10,  1.17it/s]

[496/1000]
EN: Canadian visitation to United States continues to plummet.
BRX: जुथाइ रायजो आमेरिकायाव कानाडानि दावबायनाया लासै-लासै गोग्लैबाय थायो.
--------------------------------------------------

Translating:  50%|█████████████▍             | 497/1000 [07:17<07:46,  1.08it/s]

[497/1000]
EN: Sean Duffy focuses on America's ailing air travel system.
BRX: शन डफीआ आमेरिकानि गाज्रि बिरखं दावबायनाय खान्थिनि सायाव नोजोर होयो →
--------------------------------------------------

Translating:  50%|█████████████▍             | 498/1000 [07:18<07:16,  1.15it/s]

[498/1000]
EN: Trump administration policies impact travel both positively and negatively.
BRX: ट्राम्प खुंथायनि खान्थिफोरा दावबायनायाव मोजां आरो गाज्रि मोननैबो गोहोम खोख्लैयो ꯫
--------------------------------------------------

Translating:  50%|█████████████▍             | 499/1000 [07:19<07:08,  1.17it/s]

[499/1000]
EN: Sri Lanka regime change attributed to poor governance by Ajit Doval.
BRX: श्रीलंकानि खुंथाय सोलायनायखौ अजीत दभालनि गाज्रि सासननि थाखाय गनायनाय जायो →
--------------------------------------------------

Translating:  50%|█████████████▌             | 500/1000 [07:19<06:47,  1.23it/s]

[500/1000]
EN: Bangladesh leadership transition results from poor governance failures.
BRX: बांग्लादेशनि दैदेनगिरिया गाज्रि खुंथायारि फेलेंफोरनि फिथाइ महरै सोलायनाय जादोंपाटों ।
--------------------------------------------------

Translating:  50%|█████████████▌             | 501/1000 [07:20<06:27,  1.29it/s]

[501/1000]
EN: Nepal government change linked to governance issues says Doval.
BRX: नेपाल सोरखारा खुंथायारि जेंनाफोरजों सोमोन्दो गोनां सोलायनायखौ बुङो |
--------------------------------------------------

Translating:  50%|█████████████▌             | 502/1000 [07:21<06:12,  1.34it/s]

[502/1000]
EN: Thailand launches five year multiple entry tourist visa scheme.
BRX: थाइलेन्डआ बा बोसोरनि माल्टिपल एन्ट्रि टुरिस्ट भिसा बिथांखि जागायदों |
--------------------------------------------------

Translating:  50%|█████████████▌             | 503/1000 [07:22<06:32,  1.27it/s]

[503/1000]
EN: Sri Lanka grants free visa to seven countries including India.
BRX: श्रीलंकाया भारतजों लोगोसे मोनस्नि हादोरफोरनो बेसेन गैयै भिसाखौ होयो →
--------------------------------------------------

Translating:  50%|█████████████▌             | 504/1000 [07:22<06:36,  1.25it/s]

[504/1000]
EN: Maldives lifts emergency but tourism recovery remains sluggish.
BRX: मालदिभ्सआ खैफोदखौ बोखारदों नाथाय दावबायफालांगि रिकभारिया लासैलासै जागासिनो दं |
--------------------------------------------------

Translating:  50%|█████████████▋             | 505/1000 [07:23<06:42,  1.23it/s]

[505/1000]
EN: UAE announces five year multiple entry visa for Indian nationals.
BRX: यु. ए. इ.आ भारतारि नोगोरारिफोरनि थाखाय बा बोसोरनि माल्टिपल एन्ट्रि भिसाखौ फोसावनाय जादों |
--------------------------------------------------

Translating:  51%|█████████████▋             | 506/1000 [07:24<06:30,  1.27it/s]

[506/1000]
EN: Schengen visa fees increase from eighty to ninety Euros globally.
BRX: सेनजेन भिसानि मासुलआ बुहुमनाङै दाइनजिनिफ्राय जिगु इउर'सिम बांदों ꯫
--------------------------------------------------

Translating:  51%|█████████████▋             | 507/1000 [07:25<06:09,  1.34it/s]

[507/1000]
EN: Japan resumes short term tourist visa processing for Indians.
BRX: जापानआ भारतारिफोरनि थाखाय गुसुं समनि दावबायारि भिसा प्रसेसिंखौ जागायजेनो →
--------------------------------------------------

Translating:  51%|█████████████▋             | 508/1000 [07:25<05:53,  1.39it/s]

[508/1000]
EN: India operates 127 airports with ten new cruise terminals.
BRX: भारतआ मोनजि गोदान क्रुज टार्मिनालफोरजों 127 बिरखं गाथोनफोरखौ सामलायो |
--------------------------------------------------

Translating:  51%|█████████████▋             | 509/1000 [07:26<05:51,  1.40it/s]

[509/1000]
EN: Government constructs 150,000 kilometres of new national highways.
BRX: सरकारा 150,000 किल 'मिटार गोदान हायुंआरि राजालामाफोर लुगासिनो दंपाटों ।
--------------------------------------------------

Translating:  51%|█████████████▊             | 510/1000 [07:27<05:45,  1.42it/s]

[510/1000]
EN: India develops 38 national waterways for inland cruise tourism.
BRX: भारतआ हादोर गेजेरारि क्रुज दावबायनायनि थाखाय 38 हादोरारि दै लामाफोर जौगाहोयो |
--------------------------------------------------

Translating:  51%|█████████████▊             | 511/1000 [07:27<05:33,  1.47it/s]

[511/1000]
EN: Metro rail network expands 10,000 kilometres across 23 cities.
BRX: मेट्रोरेल नेटवार्कआ 23 नोगोरफोराव 10,000 किल 'मिटार गोसारदों |
--------------------------------------------------

Translating:  51%|█████████████▊             | 512/1000 [07:28<05:40,  1.43it/s]

[512/1000]
EN: Swadesh Darshan 2.0 develops tourism sites to global standards.
BRX: स्वदेश दर्शन 2.0 आ दावबायग्रा थावनिफोरखौ बुहुमनां मानथाखोआव जौगाहोयो |
--------------------------------------------------

Translating:  51%|█████████████▊             | 513/1000 [07:29<05:37,  1.44it/s]

[513/1000]
EN: PRASHAD scheme enhances pilgrimage tourism infrastructure across India.
BRX: प्रसाद बिथांखिया गासै भारतआव धोरोमदावबायारि दावबायथाय बिथायारि सानजथाइखौ बांहोयो |
--------------------------------------------------

Translating:  51%|█████████████▉             | 514/1000 [07:30<06:04,  1.33it/s]

[514/1000]
EN: Saudi Red Sea authority enforces international safety standards for marine tourism.
BRX: साउदी गोजा लैथोनि गोहोआ लैथोआरि दावबायनायनि थाखाय हादोरगेजेरारि रैखाथि मानथाखोफोरखौ बाहायदों |
--------------------------------------------------

Translating:  52%|█████████████▉             | 515/1000 [07:30<06:18,  1.28it/s]

[515/1000]
EN: Saudi marine regulations protect Red Sea coral reef ecosystems.
BRX: साउदी लैथोआरि नेमखान्थिफोरा गोजा लैथोनि प्रबाल रीफ सोरबिथिं बिखान्थिखौ रैखा खालामो |
--------------------------------------------------

Translating:  52%|█████████████▉             | 516/1000 [07:31<05:54,  1.37it/s]

[516/1000]
EN: Saudi Red Sea tourism to add 85 billion riyals to GDP.
BRX: साउदीनि गोजा लैथो दावबायथाया जि.डि.प.आव 85 बिलियन रियाल दाजाबदेरगोन |
--------------------------------------------------

Translating:  52%|█████████████▉             | 517/1000 [07:32<05:30,  1.46it/s]

[517/1000]
EN: Red Sea tourism creates 210,000 Saudi jobs by 2030.
BRX: गोजा लैथो दावबायथाया 2030 मायथाइसिमाव 210,000 सउदी मावसोमथाय सोरजियो |
--------------------------------------------------

Translating:  52%|█████████████▉             | 518/1000 [07:32<05:30,  1.46it/s]

[518/1000]
EN: Indian Railways recovers only fraction of 4,087 crore dues.
BRX: भारतारि रेलवेआ 4,087 कौटि रां होनां रांनि इसे बाहागोखौल'मोनफिन्दोंमोन |
--------------------------------------------------

Translating:  52%|██████████████             | 519/1000 [07:33<06:11,  1.30it/s]

[519/1000]
EN: RLDA develops only fraction of railway land for commercial use.
BRX: आर.एल.डीए.आ फालांगियारि बाहायनायनि थाखाय रेलवे हानि इसे बाहागोखौल'जौगाहोयो |
--------------------------------------------------

Translating:  52%|██████████████             | 520/1000 [07:34<05:54,  1.35it/s]

[520/1000]
EN: Central Railway announces train diversions for Dasara and Diwali.
BRX: मिरुआरि रेलवेआ दसारा आरो दिवालीनि थाखाय ट्रेनफोरनि सोलाय-सोल. खालामनायनि फोसावनाय खालामो |
--------------------------------------------------

Translating:  52%|██████████████             | 521/1000 [07:35<05:58,  1.34it/s]

[521/1000]
EN: SCR cancels 69 trains due to operational requirements.
BRX: एस.सि.आर.आ मावफुङारि गोनांथिफोरनि थाखाय 69 ट्रेनफोरखौ दानस्लायदों |
--------------------------------------------------

Translating:  52%|██████████████             | 522/1000 [07:35<05:32,  1.44it/s]

[522/1000]
EN: South Central Railway diverts 29 trains for festival management.
BRX: खोला मिरुआरि रेलवेआ फोरबो सामलायनायनि थाखाय 29 ट्रेनफोरखौ सोलायस्लु खालामो →
--------------------------------------------------

Translating:  52%|██████████████             | 523/1000 [07:36<05:07,  1.55it/s]

[523/1000]
EN: Indian Railways announces 18 partially cancelled train services.
BRX: भारतारि रेलवेआ 18 बाहागोआरि दानस्लायनाय ट्रेन सिबिथाइफोरखौ फोसावदोंमोन |
--------------------------------------------------

Translating:  52%|██████████████▏            | 524/1000 [07:36<04:57,  1.60it/s]

[524/1000]
EN: Three trains rescheduled by South Central Railway authority.
BRX: खोला मिरुआरि रेलवे आफादजों खनथाम ट्रेनफोरनि सम सोलायबायथानाय जादों |
--------------------------------------------------

Translating:  52%|██████████████▏            | 525/1000 [07:37<05:08,  1.54it/s]

[525/1000]
EN: SCR cancels total 119 train services during peak season.
BRX: एस.सि.आर.आ पीक सिजननि समाव गासै 119 ट्रेन सिबिथाइफोरखौ दानस्लायदों |
--------------------------------------------------

Translating:  53%|██████████████▏            | 526/1000 [07:38<05:12,  1.52it/s]

[526/1000]
EN: Disney Cruise Line debuts Disney Destiny vessel in 2025.
BRX: डिज्नी क्रुज लाइनआ इं 2025 माइथायाव डिजनी डेस्टिनी जाहाजखौ जागायजेनो →
--------------------------------------------------

Translating:  53%|██████████████▏            | 527/1000 [07:38<05:03,  1.56it/s]

[527/1000]
EN: Norwegian Cruise Line adds Norwegian Aqua to fleet.
BRX: नरवेनि क्रुज लाइना नरभेनि एक्वाखौ नावजावनायाव दाजाबदेरो |
--------------------------------------------------

Translating:  53%|██████████████▎            | 528/1000 [07:39<04:59,  1.58it/s]

[528/1000]
EN: Royal Caribbean launches Star of the Seas cruise ship.
BRX: रयेल केरेबियानआ स्टार अफ द सीज क्रुज जाहाजखौ लन्च खालामो |
--------------------------------------------------

Translating:  53%|██████████████▎            | 529/1000 [07:40<04:53,  1.61it/s]

[529/1000]
EN: Varanasi airport expands terminal to handle five million passengers.
BRX: वाराणसी बिरखं गाथोना 50 लाख दावबायारिफोरखौ सामलायनो थाखाय टार्मिनालखौ फुवारदों |
--------------------------------------------------

Translating:  53%|██████████████▎            | 530/1000 [07:40<04:49,  1.63it/s]

[530/1000]
EN: Kashmir Railway line reaches Baramulla for all weather connectivity.
BRX: काश्मीर रेलवे लाइनआ गासिबो बोथोरनि सुंजाबनायनि थाखाय बारामुलायाव सौहैयो →
--------------------------------------------------

Translating:  53%|██████████████▎            | 531/1000 [07:41<05:33,  1.41it/s]

[531/1000]
EN: Ayodhya airport commences commercial flight operations for pilgrims.
BRX: अयोध्या बिरखं गाथोना धोरोमदावबायारिफोरनि थाखाय फालांगियारि बिरग्रा दिङा सालायनायखौ जागायजेनो →
--------------------------------------------------

Translating:  53%|██████████████▎            | 532/1000 [07:42<05:19,  1.46it/s]

[532/1000]
EN: Chennai metro phase two extension connects airport to city centre.
BRX: चेन्नाई मेट्र 'नि नैथि फेजनि फुवारनाया बिरखं गाथोनखौ नोगोर मिरुजों फोनांजाबो ꯫
--------------------------------------------------

Translating:  53%|██████████████▍            | 533/1000 [07:42<05:09,  1.51it/s]

[533/1000]
EN: Mumbai Trans Harbour Link reduces travel time to Navi Mumbai airport.
BRX: मुम्बाइ ट्रान्स हार्बर लिंकआ नवी मुम्बाइ बिरखं गाथोनसिम दावबायनायनि समखौ खम खालामो |
--------------------------------------------------

Translating:  53%|██████████████▍            | 534/1000 [07:43<05:01,  1.55it/s]

[534/1000]
EN: Kashi Vishwanath corridor transforms pilgrimage experience in Varanasi.
BRX: काशी विश्वनाथ करिडरआ वाराणसीआव धोरोमदावबायारिनि मोन्दांथिखौ सोलायहोयो ꯫
--------------------------------------------------

Translating:  54%|██████████████▍            | 535/1000 [07:43<04:47,  1.62it/s]

[535/1000]
EN: Hyatt completes acquisition of Playa Hotels and Resorts.
BRX: हयातआ प्लाया हटेल आरो रिसर्टफोरखौ आरजिनायखौ फोजोबदों |
--------------------------------------------------

Translating:  54%|██████████████▍            | 536/1000 [07:44<05:05,  1.52it/s]

[536/1000]
EN: Hyatt adds fifteen beachfront properties across Mexico and Jamaica.
BRX: हयातआ मेक्सिको आरो जमैकाआव जिबा लैथोगाथोन मोखांनि सम्पथिफोरखौ दाजाबदेरो |
--------------------------------------------------

Translating:  54%|██████████████▍            | 537/1000 [07:45<05:15,  1.47it/s]

[537/1000]
EN: Hyatt acquires Secrets La Romana in Dominican Republic.
BRX: हायातआ डमिनिकान रिपाब्लिकआव सीक्रेट्स ला र 'मानाखौ आरजियो |
--------------------------------------------------

Translating:  54%|██████████████▌            | 538/1000 [07:46<05:08,  1.50it/s]

[538/1000]
EN: Dreams La Romana joins Hyatt portfolio through Playa acquisition.
BRX: ड्रिमस ला रुमानाया प्लाया आरजिनायजों हयात पर्टफ 'लियाव बाहागो लायो |
--------------------------------------------------

Translating:  54%|██████████████▌            | 539/1000 [07:46<05:06,  1.50it/s]

[539/1000]
EN: Dreams Rose Hall in Montego Bay transfers to Hyatt ownership.
BRX: मन्टेगो बेआव ड्रिमस रोज ह 'लआ हयात बिगोमाथिनाव सोलायजायो.
--------------------------------------------------

Translating:  54%|██████████████▌            | 540/1000 [07:47<05:03,  1.52it/s]

[540/1000]
EN: Hyatt Vivid Playa del Carmen added to hotel collection.
BRX: हयात विविड प्लाया डेल कारमेनआ हटेल बुथुमनायाव दाजाबदेरनाय जादों |
--------------------------------------------------

Translating:  54%|██████████████▌            | 541/1000 [07:48<05:11,  1.47it/s]

[541/1000]
EN: Sunscape Cancun becomes Hyatt property after Playa deal.
BRX: प्लेया डीलनि उनाव सनस्केप कानकुनआ हयात सम्पथि जायोपाट्राफाया ।
--------------------------------------------------

Translating:  54%|██████████████▋            | 542/1000 [07:48<05:06,  1.49it/s]

[542/1000]
EN: Hotel infrastructure status unlocks private investment says Shekhawat.
BRX: हतेल बिथायारि सानजथाइ मानथाखोआ गावारि रां खाथायनायखौ खुलिना होयो |
--------------------------------------------------

Translating:  54%|██████████████▋            | 543/1000 [07:49<04:54,  1.55it/s]

[543/1000]
EN: FICCI annual general meeting discusses tourism growth strategy.
BRX: फिक्कीनि बोसोरारि सरासनस्रा जथुममाया दावबायफालांगि जौगानाय सोलोखौ सावरायदों |
--------------------------------------------------

Translating:  54%|██████████████▋            | 544/1000 [07:49<04:39,  1.63it/s]

[544/1000]
EN: Harsh Vardhan Agarwal highlights tourism as economic driver.
BRX: हर्ष बर्धन अग्रवालआ दावबायनायखौ रांखान्थियारि सालायगिरि महरै दिन्थिदों |
--------------------------------------------------

Translating:  55%|██████████████▋            | 545/1000 [07:50<04:27,  1.70it/s]

[545/1000]
EN: Anant Goenka praises Swadesh Darshan and PRASHAD initiatives.
BRX: अनन्त गोयनकाया स्वदेश दर्शन आरो प्रसादनि बिथांखिफोरखौ बाखनायदों |
--------------------------------------------------

Translating:  55%|██████████████▋            | 546/1000 [07:51<04:50,  1.56it/s]

[546/1000]
EN: Indian hotel industry seeks infrastructure status for tax benefits.
BRX: भारतारि हटेल दारिमिना खाजोना मुलामफानि थाखाय सानजथाइयारि थामान नागिरो →
--------------------------------------------------

Translating:  55%|██████████████▊            | 547/1000 [07:52<05:23,  1.40it/s]

[547/1000]
EN: Shangri-La Bengaluru hosts Chef Simone Loisi Italian culinary residency.
BRX: सांग्री-ला बेंगलुरूआ सेफ सिमोन लोइसी इटालियान संनाय- खावनाय रेसिडेन्सीखौ हस्ट खालामोपाट खालामनाय जायो |
--------------------------------------------------

Translating:  55%|██████████████▊            | 548/1000 [07:52<05:24,  1.39it/s]

[548/1000]
EN: Chef Simone Loisi brings Southern Italian cuisine to Bangalore.
BRX: सेफ सिमोन लोइसीआ खोला इटालीनि जामुंखौ बेंगालराव लाबोयो |
--------------------------------------------------

Translating:  55%|██████████████▊            | 549/1000 [07:53<05:58,  1.26it/s]

[549/1000]
EN: Waterfall Ristorante Italiano chef showcases cuisine at Shangri-La.
BRX: दैबाज्रुम रिस्टोरान्टे इटालियान.अ. सेफआ शांग्रि-लायाव संनाय-रोखोम दिन्थिफुङो |
--------------------------------------------------

Translating:  55%|██████████████▊            | 550/1000 [07:54<05:36,  1.34it/s]

[550/1000]
EN: Four Seasons Bengaluru transforms for Halloween 2025 celebrations.
BRX: बेंगालुरुआ इं 2025 माइथायनि हेलोवीन फोरबोआव बाहागो लानो हागोन |
--------------------------------------------------

Translating:  55%|██████████████▉            | 551/1000 [07:55<05:39,  1.32it/s]

[551/1000]
EN: CUR8 hosts family friendly Halloween evening in Bengaluru.
BRX: सि.यु.आर.8 आ बेंगालुरुआव नखरारि लोगोआरि हेलोवीन बेलासखौ खुङो |
--------------------------------------------------

Translating:  55%|██████████████▉            | 552/1000 [07:55<05:08,  1.45it/s]

[552/1000]
EN: Copitas bar ranks in Asia's 50 Best Bars list.
BRX: कपितास बारआ एशियानि 50 साबसिन बारफोरनि फारियाव दं ꯫
--------------------------------------------------

Translating:  55%|██████████████▉            | 553/1000 [07:56<05:04,  1.47it/s]

[553/1000]
EN: Four Seasons Bengaluru hosts Día de Muertos Halloween party.
BRX: बेंगलुरूआव डिया डी मुएर्टसनि हेलोवीन पार्टीखौ खुंनाय जायो |
--------------------------------------------------

Translating:  55%|██████████████▉            | 554/1000 [07:57<04:59,  1.49it/s]

[554/1000]
EN: Sheraton Hyderabad invites guests to Feast Halloween buffet.
BRX: सेरेटन हायद्राबादआ आलासिफोरखौ हेलोवीन बुफे जानो थाखाय लिंहरहोयो |
--------------------------------------------------

Translating:  56%|██████████████▉            | 555/1000 [07:57<05:12,  1.42it/s]

[555/1000]
EN: Chef Yugal Sharma represents North West Frontier cuisine at ITC.
BRX: शेफ युगल शर्माआ आई. टी. सी. आव सा- सोनाब फ्रन्टियार संनाय-रोखोमखौ थान्दैथि खालामो |
--------------------------------------------------

Translating:  56%|███████████████            | 556/1000 [07:58<05:44,  1.29it/s]

[556/1000]
EN: Royal Afghan assistant master chef promotes rustic Indian cuisine.
BRX: रयेल आफगान एसिस्टेन्ट मास्टर शेफआ गामियारि भारतारि संनाय-रोखोमखौ दावगाहोयो |
--------------------------------------------------

Translating:  56%|███████████████            | 557/1000 [07:59<05:28,  1.35it/s]

[557/1000]
EN: The Leela Hyderabad hosts Chef Picched three-day Thai culinary showcase.
BRX: लीला हायद्राबादआ सेफ पिकडखौ सानथामारि थाइ संनाय-रोखोम दिन्थिफुंनायखौ खुङो |
--------------------------------------------------

Translating:  56%|███████████████            | 558/1000 [08:00<05:46,  1.27it/s]

[558/1000]
EN: Chef Picched Paoleng brings authentic Bangkok cuisine to Hyderabad.
BRX: सेफ पिच्ड पाओलेंआ नंगुबै बेंकक संनाय-रोखोमखौ हायद्राबादाव लाबोयोपाटांफोर ।
--------------------------------------------------

Translating:  56%|███████████████            | 559/1000 [08:01<06:17,  1.17it/s]

[559/1000]
EN: Marriott Executive Apartments Bengaluru unveils Madras Kitchen restaurant.
BRX: बेंगलुरूनि मेरियट एकजेक्युटिभ एपार्टमेन्टआ माद्रास किचन रेस्टुरेन्टखौ बेखेवदोंमोन.
--------------------------------------------------

Translating:  56%|███████████████            | 560/1000 [08:02<05:50,  1.25it/s]

[560/1000]
EN: Madras Kitchen pays homage to South Indian gastronomic heritage.
BRX: माद्रास किचनआ खोला भारतारि गेस्ट्रोनोमिक आजौसमफथिखौ मान बाउदों |
--------------------------------------------------

Translating:  56%|███████████████▏           | 561/1000 [08:02<05:55,  1.23it/s]

[561/1000]
EN: ITC Grand Bharat chef shares Diwali festive dinner hosting tips.
BRX: आई.टी.सी. ग्रान्ड भारत शेफआ दिवाली फोरबोनि जाग्रा आदारनि हस्टिं टिप्सखौ रानलायदों |
--------------------------------------------------

Translating:  56%|███████████████▏           | 562/1000 [08:03<05:44,  1.27it/s]

[562/1000]
EN: Marriott Executive Apartments Hyderabad celebrates Hyderabadi dessert heritage.
BRX: मैरियट एकजेक्युटिभ एपार्टमेन्टफोरा हायद्राबादनि गोदै आजौसमफथिखौ फालियो.
--------------------------------------------------

Translating:  56%|███████████████▏           | 563/1000 [08:04<05:45,  1.27it/s]

[563/1000]
EN: 4Note culinary hot spot opens with four kitchens concept.
BRX: 4न 'ट संनाय-लानाय हट स्पटआ मोनब्रै ओंखाम संग्रानि सानदांथिजों खुलिगोन |
--------------------------------------------------

Translating:  56%|███████████████▏           | 564/1000 [08:05<05:33,  1.31it/s]

[564/1000]
EN: Zuma Abu Dhabi maintains global legacy restaurant standards.
BRX: जुमा आबु धाबीआ बुहुमनां उनमोनथायारि रेस्टुरेन्ट मानथाखोफोरखौ सामलायो ꯫
--------------------------------------------------

Translating:  56%|███████████████▎           | 565/1000 [08:05<05:33,  1.30it/s]

[565/1000]
EN: Dubai chocolate craze triggers global pistachio shortage crisis.
BRX: दुबाइनि चकलेटनि मोजां मोननाया बुहुमनां पिस्ता आंखालनि खैफोद सोमजिहोयो |
--------------------------------------------------

Translating:  57%|███████████████▎           | 566/1000 [08:06<05:05,  1.42it/s]

[566/1000]
EN: Indian Hotels Company signs new Taj property in Lucknow.
BRX: इन्दियान हतेल कम्पानिया लखनऊआव गोदान ताज सम्पथि साइन खालामो |
--------------------------------------------------

Translating:  57%|███████████████▎           | 567/1000 [08:07<04:53,  1.47it/s]

[567/1000]
EN: Oberoi Group announces luxury resort opening in Ranthambhore.
BRX: अबेरय ग्रुपआ रणथम्भौरआव लग्जरी रिसर्ट बेखेवनायखौ फोसावदोंमोन |
--------------------------------------------------

Translating:  57%|███████████████▎           | 568/1000 [08:07<04:48,  1.50it/s]

[568/1000]
EN: Lemon Tree Hotels expands northeast presence with Guwahati property.
BRX: लेमन ट्री हतेलफोरा गुवाहाटीनि सम्पथिजों सा-सानजानि थाथायखौ फुवारदों |
--------------------------------------------------

Translating:  57%|███████████████▎           | 569/1000 [08:08<04:47,  1.50it/s]

[569/1000]
EN: Marriott International to open 50th property in India by 2026.
BRX: म 'रिअट इन्टारनेशनेलआ 2026 मायथाइसिमाव भारताव 50थि सम्पथि खुलिगोन |
--------------------------------------------------

Translating:  57%|███████████████▍           | 570/1000 [08:09<04:51,  1.47it/s]

[570/1000]
EN: Radisson Hotel Group targets 200 hotels across India by 2027.
BRX: रेडिसन हतेल ग्रुपआ 2027 मायथाइसिमाव गासै भारतआव 200 हटेलफोरखौ थांखि लायो |
--------------------------------------------------

Translating:  57%|███████████████▍           | 571/1000 [08:09<05:00,  1.43it/s]

[571/1000]
EN: OYO announces international expansion into Vietnam and Indonesia.
BRX: अ.वाई.अ.आ भियेटनाम आरो इन्डोनेशियायाव हादोर गेजेरारि फेहेरनायखौ फोसावदोंमोन |
--------------------------------------------------

Translating:  57%|███████████████▍           | 572/1000 [08:11<06:37,  1.08it/s]

[572/1000]
EN: MakeMyTrip partners with IHCL for exclusive holiday packages.
BRX: मेकमायट्रिपआ एखुथा जिरायनाय सान पेकेजफोरनि थाखाय आई.एच.सी.एल. जों बाहागो लायोंपोनाया/जेन्नो हानाय नङा |
--------------------------------------------------

Translating:  57%|███████████████▍           | 573/1000 [08:11<05:45,  1.23it/s]

[573/1000]
EN: Maha Kumbh Mela creates one million jobs for local families.
BRX: महा कुम्भ मेलाया जायगायारि नखरफोरनि थाखाय से मिलियन खामानि सोमजिहोयो |
--------------------------------------------------

Translating:  57%|███████████████▍           | 574/1000 [08:12<05:19,  1.33it/s]

[574/1000]
EN: Boat services at Kumbh earn families collective 30 crore rupees.
BRX: कुम्भआव दिङा सिबिथाइफोरा नखरफोरखौ जथाय महरै 30 कौटि रां आरजियोङ्गाङो |
--------------------------------------------------

Translating:  57%|███████████████▌           | 575/1000 [08:12<04:59,  1.42it/s]

[575/1000]
EN: The Guardian describes Prayagraj Kumbh as pop-up megacity.
BRX: गार्डियनआ प्रयागराज कुम्भखौ पप-आप मेगासिटि महरै बरनायदों |
--------------------------------------------------

Translating:  58%|███████████████▌           | 576/1000 [08:13<04:30,  1.57it/s]

[576/1000]
EN: Maharashtra Economic Council reports Kumbh employment generation.
BRX: महाराष्ट्र रांखान्थियारि आफादआ कुम्भआव मावसोमनाय दिहुनथायनि फोरमायथि होयो |
--------------------------------------------------

Translating:  58%|███████████████▌           | 577/1000 [08:14<04:33,  1.55it/s]

[577/1000]
EN: FIFA Club World Cup 2025 brings global visitors to host cities.
BRX: फिफा क्लाब मुलुग काप 2025 आ बुहुमनां दावबायारिफोरखौ हस्टिं नोगोरफोराव लाबोयोपाटों ।
--------------------------------------------------

Translating:  58%|███████████████▌           | 578/1000 [08:14<04:20,  1.62it/s]

[578/1000]
EN: Wimbledon 2025 witnesses global unity through international tennis.
BRX: विम्बलडन 2025आ हादोर गेजेरारि टेनिसनि गेजेरजों बुहुमनां जथाइखौ नुनो मोनदों |
--------------------------------------------------

Translating:  58%|███████████████▋           | 579/1000 [08:17<09:28,  1.35s/it]

[579/1000]
EN: Sikh pilgrims receive Pakistani visas after Operation Sindoor.
BRX: सिख धोरोमदावबायारिफोरा अपारेशन सिन्दूरनि उनाव पाकिस्ताननि भिसाखौ मोनो/01/8/9/7/5/2/6/4/3/16/14/15/18/13/30/22/26/24/27/25/35/23/50/40/70/21/200/000/12/20/10/90/19,40/80/60/34/11/36/100/42/32/गुबिबांफोर ।
--------------------------------------------------

Translating:  58%|███████████████▋           | 580/1000 [08:18<07:47,  1.11s/it]

[580/1000]
EN: Harjindarpal Singh secures passport and Pakistan visa for pilgrimage.
BRX: हरिश कुमारआ गावनि नख 'ारनि थाखाय पाकिस्तानखौ आवग्रिना लाखिदोंमोन |
--------------------------------------------------

Translating:  58%|███████████████▋           | 581/1000 [08:19<07:42,  1.10s/it]

[581/1000]
EN: First Sikh Jathas travel to Pakistan post visa ban reversal.
BRX: गिबि सिख जाठाफोरा भिसानि होबथानायनि उनाव पाकिस्तानसिम दावबायो/जेन्नाय जादों |
--------------------------------------------------

Translating:  58%|███████████████▋           | 582/1000 [08:20<06:59,  1.00s/it]

[582/1000]
EN: FIDE names World Chess Cup trophy after Viswanathan Anand.
BRX: एफ.आइ.डि.इ.आ बुहुमनां दाबा काप ट्रफीखौ विश्वनाथन आनन्दनि मुङै दोननाय जादों |
--------------------------------------------------

Translating:  58%|███████████████▋           | 583/1000 [08:20<06:20,  1.10it/s]

[583/1000]
EN: Panjim hosts FIDE World Chess Cup with Anand trophy.
BRX: पानजिमआ आनन्द ट्रॉफीजों एफ.आइ.डि.ई. बुहुमनां दाबा कापखौ हस्ट खालामो →
--------------------------------------------------

Translating:  58%|███████████████▊           | 584/1000 [08:21<05:31,  1.26it/s]

[584/1000]
EN: Krishna Janmashtami procession turns tragic in Ramanthapur.
BRX: कृष्ण जन्माष्टमीनि हानजा सुरनाया रामनथापुरआव दुखु गोनां जायो.
--------------------------------------------------

Translating:  58%|███████████████▊           | 585/1000 [08:22<05:18,  1.30it/s]

[585/1000]
EN: Ten-foot chariot touches live wire killing five devotees.
BRX: जि-फुतनि रथआ गोथां तारखौ दांनानै मोनबा सिबियारिफोरखौ बुथारदोंमोन.
--------------------------------------------------

Translating:  59%|███████████████▊           | 586/1000 [08:22<04:42,  1.47it/s]

[586/1000]
EN: Hyderabad celebrates Ganesh festival with large screen displays.
BRX: हैदराबादआव गणेश फोरबोखौ गिदिर फैसालि दिन्थिफुंनायजों फालिनाय जायो |
--------------------------------------------------

Translating:  59%|███████████████▊           | 587/1000 [08:23<04:44,  1.45it/s]

[587/1000]
EN: Begum Bazaar jam-packed for night long festival celebrations.
BRX: बेगम बाजारआ हरसे गोलाव फोरबो फालिथायनि थाखाय होंगो-दोबोजों बुंफबनाय |
--------------------------------------------------

Translating:  59%|███████████████▉           | 588/1000 [08:23<04:26,  1.55it/s]

[588/1000]
EN: Muslim leader Sadeq Siraj organizes eye camp for community.
BRX: मुस्लिम दैदेनगिरि सादेक सिराजआ हारिफोरनि थाखाय मेगननि केम्प खुङो →
--------------------------------------------------

Translating:  59%|███████████████▉           | 589/1000 [08:24<04:10,  1.64it/s]

[589/1000]
EN: Hyderabad pandals adopt traditional themes for Ganesh Chaturthi.
BRX: हाइद्राबादनि पेन्डेलफोरा गणेश चतुर्थीनि थाखाय दोरोङारि आयदाफोरखौ नाजावो.
--------------------------------------------------

Translating:  59%|███████████████▉           | 590/1000 [08:24<04:05,  1.67it/s]

[590/1000]
EN: Shuja Ifteqari requests Chief Minister Revanth Reddy for arrangements.
BRX: बेनि उनाव बिथाङा गिबि मन्थ्रि रेभन्थ रेड्डीखौ बिथोन होनो थाखाय आर 'ज खालामो |
--------------------------------------------------

Translating:  59%|███████████████▉           | 591/1000 [08:25<04:19,  1.57it/s]

[591/1000]
EN: SOCIAL Hyderabad hosts She's a Phataka Diwali celebration bash.
BRX: एस.अ.सि.ए.एल. हायद्राबादआ बिथांजोनि मोनसे फाटाका दिवाली फालिथायखौ खुङो |
--------------------------------------------------

Translating:  59%|███████████████▉           | 592/1000 [08:26<04:13,  1.61it/s]

[592/1000]
EN: Hyderabad soaked in festival fervour with rain showers.
BRX: हायद्राबादआ अखा हानायजों फोरबोनि थुलुंगायाव सोबखांदोंमोन |
--------------------------------------------------

Translating:  59%|████████████████           | 593/1000 [08:26<04:11,  1.62it/s]

[593/1000]
EN: Dasara trains diverted to manage two lakh passenger footfall.
BRX: दासारा ट्रेनफोरखौ नै लाख दावबायारिफोरनि आगानखौ सामलायनो थाखाय सोलायहोनाय जादों |
--------------------------------------------------

Translating:  59%|████████████████           | 594/1000 [08:27<04:05,  1.65it/s]

[594/1000]
EN: New passenger routes planned for Dasara and Diwali travel.
BRX: दसारा आरो दिवाली दावबायनायनि थाखाय गोदान दावबायारि लामाफोर बिथांखि लानाय जादों |
--------------------------------------------------

Translating:  60%|████████████████           | 595/1000 [08:27<03:58,  1.70it/s]

[595/1000]
EN: Hyderabad kiosks offer Ganesh idols across every street.
BRX: हायद्राबादनि किओस्कफोरा मोनफ्रोमबो लामायाव गणेशनि मुसुखाफोर जासियो |
--------------------------------------------------

Translating:  60%|████████████████           | 596/1000 [08:28<03:47,  1.78it/s]

[596/1000]
EN: Indian Navy monitors every Chinese vessel in Indian Ocean.
BRX: भारतारि नौसेनाआ भारत लैथोमायाव मोनफ्रोमबो चिननि जाहाजखौ नोजोर होयो |
--------------------------------------------------

Translating:  60%|████████████████           | 597/1000 [08:29<03:51,  1.74it/s]

[597/1000]
EN: Vice Admiral Sanjay Vatsayan confirms continuous maritime surveillance.
BRX: भाइस एडमिरल संजय वत्सायनआ सोलिबाय थानाय लैथोआरि नायसंनायखौ रोखा खालामो →
--------------------------------------------------

Translating:  60%|████████████████▏          | 598/1000 [08:29<04:00,  1.67it/s]

[598/1000]
EN: Goa tourism department announces calendar of winter festivals.
BRX: गवा दावबायफालांगि बिफानआ गोजां बोथोरनि फोरबोफोरनि केलेन्डारखौ फोसावनाय जायो →
--------------------------------------------------

Translating:  60%|████████████████▏          | 599/1000 [08:30<04:02,  1.66it/s]

[599/1000]
EN: Jaipur Literature Festival attracts 50,000 book lovers from abroad.
BRX: जयपुर थुनलाइ फोरबोआ गुबुन हादोरनिफ्राय 50,000 बिजाब मोजां मोनग्राफोरखौ गोसो बोहोयो |
--------------------------------------------------

Translating:  60%|████████████████▏          | 600/1000 [08:30<03:57,  1.68it/s]

[600/1000]
EN: Rann Utsav begins in Kutch with tent city bookings full.
BRX: रन उतसवआ कच्छआव टेन्ट सिटी बुकिं आबुं जानायजों जागायजेनो |
--------------------------------------------------

Translating:  60%|████████████████▏          | 601/1000 [08:31<04:02,  1.65it/s]

[601/1000]
EN: Hornbill Festival showcases Naga heritage in Kisama heritage village.
BRX: हर्नबिल फोरबोआ किसामा आजौसमफथि गामियाव नागा उनमोनथाइखौ दिन्थियो |
--------------------------------------------------

Translating:  60%|████████████████▎          | 602/1000 [08:32<03:54,  1.70it/s]

[602/1000]
EN: Ganga Aarti at Varanasi draws record international tourist attendance.
BRX: वाराणसीआव गंगा आरतीआ हादोर गेजेरारि दावबायारि नुजानायनि रेकर्ड बानायो |
--------------------------------------------------

Translating:  60%|████████████████▎          | 603/1000 [08:32<04:06,  1.61it/s]

[603/1000]
EN: Pahalgam terror attack kills twenty-six tourists including foreigners.
BRX: पहलगाम सिगांग्रो गाग्लोबनाया गुबुन हादोरारिफोरजों लोगोसे नैजि-द'दावबायारिफोरखौ बुथारदोंमोन.
--------------------------------------------------

Translating:  60%|████████████████▎          | 604/1000 [08:33<04:19,  1.53it/s]

[604/1000]
EN: Terrorists attack Baisaran meadows killing twenty-six civilian tourists.
BRX: टेररिस्टफोरा बायसरननि गांसोबारिफोराव गाग्लोबो जायजों सा नैजि नोगोरारि दावबायारिफोर थैयो →
--------------------------------------------------

Translating:  60%|████████████████▎          | 605/1000 [08:34<04:06,  1.60it/s]

[605/1000]
EN: Two foreign tourists among twenty-six dead in Pahalgam attack.
BRX: पहलगाम गाग्लोबनायाव सानै गुबुन हादोरारि दावबायारिफोरनि गेजेराव सा 26 सुबुंफोरा थैदोंमोन.
--------------------------------------------------

Translating:  61%|████████████████▎          | 606/1000 [08:34<04:35,  1.43it/s]

[606/1000]
EN: Operation Sindoor launched following deadly Pahalgam tourist attack.
BRX: पहलगाम दावबायथायारि गाग्लोबनायनि उनाव अपारेशन सिन्दूरखौ जुरिजेननाय जादोंमोनपाटों ।
--------------------------------------------------

Translating:  61%|████████████████▍          | 607/1000 [08:35<04:32,  1.44it/s]

[607/1000]
EN: Saudi Arabia minister Adel Al-Jubeir arrives in Delhi post Operation Sindoor.
BRX: साउदी अरबनि मन्थ्रि अदेल अल-जुबेरआ अपारेशन सिन्दूरनि उनाव दिल्लीआव सौफैदों |
--------------------------------------------------

Translating:  61%|████████████████▍          | 608/1000 [08:36<04:30,  1.45it/s]

[608/1000]
EN: Iranian Foreign Minister Araghchi visits New Delhi amid tensions.
BRX: ईराननि बायजोयारि मन्थ्रि आराग्चीआ दावराव-दावसिनि गेजेराव गोदान दिल्लीयाव दावबायहैदों |
--------------------------------------------------

Translating:  61%|████████████████▍          | 609/1000 [08:36<04:18,  1.51it/s]

[609/1000]
EN: Delhi Red Fort blast leaves fourteen dead and several injured.
BRX: दिल्लीनि लाल किलायाव जानाय बिस्फोटआव जिब्रै सुबुंफोर थैयो आरो गोबां सुबुंफोर दुखु मोनो.
--------------------------------------------------

Translating:  61%|████████████████▍          | 610/1000 [08:37<04:04,  1.59it/s]

[610/1000]
EN: High intensity explosion outside Red Fort kills fourteen people.
BRX: लाल किलानि बायजोआव गोबां गोख्रों बिस्प 'नाया जिब्रै सुबुंफोरखौ बुथारदोंमोन.
--------------------------------------------------

Translating:  61%|████████████████▍          | 611/1000 [08:38<04:15,  1.52it/s]

[611/1000]
EN: Supreme Court upholds Christian Army officer Samuel Kamalesan dismissal.
BRX: क्रिस्टियान आर्मीनि मावख 'गिरि सैमुएल कामालेसनखौ बोखारनायखौ सुप्रिम कर्टआ थि खालामना लाखिदोंमोन.
--------------------------------------------------

Translating:  61%|████████████████▌          | 612/1000 [08:38<04:24,  1.46it/s]

[612/1000]
EN: Army officer refuses temple pooja entry leading to dismissal.
BRX: रौनिया मावख 'गिरिया थानसालिनि फुजायाव हाबनायखौ नेवसिगारो जायनि जाहोनाव बिथांखौ बोखारनाय जायो.
--------------------------------------------------

Translating:  61%|████████████████▌          | 613/1000 [08:39<04:08,  1.56it/s]

[613/1000]
EN: Chief Justice Surya Kant terms refusal grossest kind of indiscipline.
BRX: गाहाय बिजिरगिरि सूर्य कांतआ नेवसिगारनायखौ बयनिख्रुइ बांसिन खान्थि गैयै होन्ना बुङो |
--------------------------------------------------

Translating:  61%|████████████████▌          | 614/1000 [08:40<04:02,  1.59it/s]

[614/1000]
EN: Saif Ali Khan undergoes surgery after knife attack at residence.
BRX: सैफ अली खानआ गावनि न 'आव दाब्रि गाग्लोबनायनि उनाव सार्जारि खालामजायो |
--------------------------------------------------

Translating:  62%|████████████████▌          | 615/1000 [08:40<03:55,  1.64it/s]

[615/1000]
EN: Intruder attacks Bollywood actor Saif Ali Khan in Mumbai.
BRX: बलिउदनि मुंदांखा फावखुंगुर सैफ अली खानआ गावनि सावथुनाव फैगासिनो दं ।
--------------------------------------------------

Translating:  62%|████████████████▋          | 616/1000 [08:41<03:39,  1.75it/s]

[616/1000]
EN: Mumbai police identify accused in Saif Ali Khan attack case.
BRX: मुम्बाइ पुलिसआ सैफ अली खाननि गाग्लोबनायनि केसआव दायगिरिफोरखौ सिनायथि होदों |
--------------------------------------------------

Translating:  62%|████████████████▋          | 617/1000 [08:41<04:01,  1.59it/s]

[617/1000]
EN: Actor discharged five days after hospitalization following attack.
BRX: सावथुनाव नुजानाय बे सावथुना सावथुननि थाखाय मोजांमोनो ।
--------------------------------------------------

Translating:  62%|████████████████▋          | 618/1000 [08:42<04:04,  1.56it/s]

[618/1000]
EN: Tihar jail probe reveals racket charging for free inmate meetings.
BRX: तिहार जेल नायसंनाया बेसेन गैयै खैदिफोरनि मेलफोरनि थाखाय रेकेटनि चार्जिंखौ फोरमायो |
--------------------------------------------------

Translating:  62%|████████████████▋          | 619/1000 [08:45<08:20,  1.31s/it]

[619/1000]
EN: Undercover officials exposed illegal mulakat charges at Tihar.
BRX: आनडरकभार मावख 'गिरिफोरा तिहारआव आयेन नङि मुलाकतनि दायफोरखौ बेखेवदोंमोन |
--------------------------------------------------

Translating:  62%|████████████████▋          | 620/1000 [08:46<07:06,  1.12s/it]

[620/1000]
EN: Tihar transfers twenty-five data entry operators after tout investigation.
BRX: नायसंनायनि उनाव तिहारआ नैजिबा डाटा एन्ट्रि अपारेटरफोरखौ जायगा सोलायहोयो ꯫
--------------------------------------------------

Translating:  62%|████████████████▊          | 621/1000 [08:46<06:05,  1.04it/s]

[621/1000]
EN: Biometric authentication introduced at Tihar Jail for security.
BRX: रैखाथिनि थाखाय तिहाड़ जेलाव बायोमेट्रिक थारथिनि सिनायथि होनाय जादों |
--------------------------------------------------

Translating:  62%|████████████████▊          | 622/1000 [08:47<05:29,  1.15it/s]

[622/1000]
EN: Supreme Court declines virtual appearance exemption for chief secretaries.
BRX: सुप्रीम कर्टआ गाहाय मन्थ्रिफोरनि थाखाय भार्च्युएल नुजानायनि उदांश्रीखौ नेवसिगारो |
--------------------------------------------------

Translating:  62%|████████████████▊          | 623/1000 [08:48<05:02,  1.25it/s]

[623/1000]
EN: States sleeping over stray dog sterilization orders says Supreme Court.
BRX: रायजोफ्रा लामा गैयै सैमा स्टेरिलाइजेशननि बिथोनफोरनि सायाव उन्दुगासिनो दं |
--------------------------------------------------

Translating:  62%|████████████████▊          | 624/1000 [08:48<04:47,  1.31it/s]

[624/1000]
EN: Passenger forced to write letter after Delhi airport assault.
BRX: दिल्ली बिरखं गाथोन गाग्लोबनायनि उनाव दावबायारिफोरखौ लाइसि लिरनो नारसिननाय जादों |
--------------------------------------------------

Translating:  62%|████████████████▉          | 625/1000 [08:49<04:22,  1.43it/s]

[625/1000]
EN: Passenger claims pressure to avoid police complaint filing.
BRX: दावबायग्राया पुलिस कमप्लेन दाखिल खालामनायखौ नेवसिनो नारसिननायखौ दाबि खालामो →
--------------------------------------------------

Translating:  63%|████████████████▉          | 626/1000 [08:50<04:38,  1.34it/s]

[626/1000]
EN: US forces seize oil tanker off Venezuela for narco-terrorism.
BRX: आमेरिकानि रौनियाफोरा नार्को-टेरिज्मनि थाखाय वेनेजुएलानिफ्राय थाव टेंकरखौ जब्द खालामो.
--------------------------------------------------

Translating:  63%|████████████████▉          | 627/1000 [08:51<04:58,  1.25it/s]

[627/1000]
EN: US Coast Guard apprehends tanker with Department of Defense backing.
BRX: इउ. एस. कोस्ट गार्डआ डिफेन्स डिपार्टमेन्टनि मददजों टेंकरखौ हमथाबोदों |
--------------------------------------------------

Translating:  63%|████████████████▉          | 628/1000 [08:51<04:48,  1.29it/s]

[628/1000]
EN: Supreme Court denies relief to mosque seeking loudspeaker permission.
BRX: सुप्रिम कर्टआ लाउडस्पीकारनि गनायथि मोन्नायनि थाखाय मस्जिदखौ रैखाखालामनायखौ नेवसिगारो →
--------------------------------------------------

Translating:  63%|████████████████▉          | 629/1000 [08:52<04:30,  1.37it/s]

[629/1000]
EN: Nagpur bench rules no religion mandates prayers with amplifiers.
BRX: नागपुर बेंचा नेम होयो दि जेबो धोरोमा एम्पलीफायरफोरजों आरज गाबनायखौ बिथोन होनाङा.
--------------------------------------------------

Translating:  63%|█████████████████          | 630/1000 [08:53<04:48,  1.28it/s]

[630/1000]
EN: Cruise Saudi brand operations commence with Red Sea licences.
BRX: सउदी क्रुज ब्रान्डनि हाबा मावनाया गोजा लैथोनि गनायथि बिलाइजों जागायजेनो →
--------------------------------------------------

Translating:  63%|█████████████████          | 631/1000 [08:53<04:44,  1.30it/s]

[631/1000]
EN: Marina services added to Saudi marine tourism portfolio.
BRX: साउदी अरेबियानि लैथोआरि दावबायथाय पर्टफ 'लियाव मेरिना सिबिथाइफोरखौ सोफादेरनाय जादों |
--------------------------------------------------

Translating:  63%|█████████████████          | 632/1000 [08:54<04:14,  1.45it/s]

[632/1000]
EN: Recreational marine activities licensed by Saudi Red Sea Authority.
BRX: साउदी गोजा लैथो आफादजों गनायथि होजानाय रंजानाय लैथोआरि हाबाफारिफोर |
--------------------------------------------------

Translating:  63%|█████████████████          | 633/1000 [08:55<04:31,  1.35it/s]

[633/1000]
EN: Saudi Arabia enforces qualified crews for marine tourism operations.
BRX: साउदी आरबियाआ लैथोआरि दावबायथाय हाबाफारिफोरनि थाखाय रोंग 'थिगोनां हानजाफोरखौ नारसिनो हानाय खालामो →
--------------------------------------------------

Translating:  63%|█████████████████          | 634/1000 [08:56<04:29,  1.36it/s]

[634/1000]
EN: Red Sea unregulated maritime activity concerns addressed by licences.
BRX: गोजा लैथोआ नेमखान्थि गैयै लैथोआरि मावखान्थिनि जेंनाफोरखौ गनायथि बिलाइफोरजों नोजोर होनाय जायो →
--------------------------------------------------

Translating:  64%|█████████████████▏         | 635/1000 [08:56<04:09,  1.46it/s]

[635/1000]
EN: Indian cruise tourism gets boost with ten new terminals.
BRX: भारतारि क्रुज दावबायथाया मोनजि गोदान टार्मिनालफोरजों बांदों |
--------------------------------------------------

Translating:  64%|█████████████████▏         | 636/1000 [08:57<04:06,  1.48it/s]

[636/1000]
EN: Disney Destiny becomes marquee cruise debut of 2025.
BRX: डिज्नी डेस्टिनीआ इं 2025 माइथायनि मार्की क्रुज डेब्यु जायो |
--------------------------------------------------

Translating:  64%|█████████████████▏         | 637/1000 [08:57<03:59,  1.51it/s]

[637/1000]
EN: Norwegian Aqua adds fleet capacity to Norwegian Cruise Line.
BRX: नरवेनि एक्वाआ नरओय़ेनि क्रुज लाइनआव नावजावग्रा गोहोखौ दाजाबदेरो |
--------------------------------------------------

Translating:  64%|█████████████████▏         | 638/1000 [08:58<04:02,  1.49it/s]

[638/1000]
EN: Royal Caribbean Star of the Seas enters service in 2025.
BRX: रयेल केरेबियान स्टार अफ द सीजआ 2025 मायथाइयाव सिबिथायाव हाबगोन |
--------------------------------------------------

Translating:  64%|█████████████████▎         | 639/1000 [08:59<04:05,  1.47it/s]

[639/1000]
EN: Cordelia Cruises announces Lakshadweep itineraries from Kochi.
BRX: कर्डेलिया क्रुजआ कचीनिफ्राय लाक्षादिप दावबायनायनि हाबाफारिफोरखौ फोसावनाय जायो |
--------------------------------------------------

Translating:  64%|█████████████████▎         | 640/1000 [08:59<03:49,  1.57it/s]

[640/1000]
EN: Water metro connectivity boosts tourism in Kochi backwaters.
BRX: दै मेट्र'फोनांजाबनाया कची बैकवाटारआव दावबायनायखौ बांहोयो ꯫
--------------------------------------------------

Translating:  64%|█████████████████▎         | 641/1000 [09:00<03:45,  1.59it/s]

[641/1000]
EN: Mumbai cruise terminal handles record 100,000 passengers this year.
BRX: मुम्बाइ क्रुज टार्मिनालआ बे बोसोराव 100,000 दावबायारिफोरनि रेबगान्थि सामलायो |
--------------------------------------------------

Translating:  64%|█████████████████▎         | 642/1000 [09:01<03:45,  1.59it/s]

[642/1000]
EN: Ganga Vilas luxury cruise completes successful Brahmaputra season.
BRX: गंगा विलास लग्जरी क्रुजआ जाफुंसार ब्रह्मपुत्र बोथोरखौ आबुं खालामो →
--------------------------------------------------

Translating:  64%|█████████████████▎         | 643/1000 [09:01<03:51,  1.54it/s]

[643/1000]
EN: Kerala houseboat registrations cross one thousand operational vessels.
BRX: केरेलानि हाउसबोट रेबथुमनाया से रोजा मावफुङारि जाहाजफोरखौ बारलाङो →
--------------------------------------------------

Translating:  64%|█████████████████▍         | 644/1000 [09:02<03:46,  1.57it/s]

[644/1000]
EN: Andaman and Nicobar receive approval for international cruise tourism.
BRX: आन्दामान आरो निकोबारा हादोरगेजेरारि क्रुज दावबायनायनि थाखाय गनायथि मोनो →
--------------------------------------------------

Translating:  64%|█████████████████▍         | 645/1000 [09:03<04:05,  1.45it/s]

[645/1000]
EN: Airbnb relaunches experiences feature for bookings and services.
BRX: एयरबीएनबीआ बुकिं आरो सिबिथाइफोरनि थाखाय रोंमोनदांथिफोरखौ फिन जागायजेनो →
--------------------------------------------------

Translating:  65%|█████████████████▍         | 646/1000 [09:03<04:12,  1.40it/s]

[646/1000]
EN: Brian Chesky announces Airbnb services complementing home rentals.
BRX: ब्रायन चेसकीआ एयरबीएनबी सिबिथाइफोरखौ न 'नि भाराखौ आबुं खालामनो फोसावनाय जायो |
--------------------------------------------------

Translating:  65%|█████████████████▍         | 647/1000 [09:04<04:11,  1.40it/s]

[647/1000]
EN: Olympic speed skater Arianna Fontana leads Airbnb training rides.
BRX: अलिम्पिक स्पिड स्केटार एरियाना फन्टानाया एयरबीएनबी ट्रेइनिं राइडफोरखौ दैदेनदों |
--------------------------------------------------

Translating:  65%|█████████████████▍         | 648/1000 [09:05<03:57,  1.48it/s]

[648/1000]
EN: Airbnb offers Alpine hikes with athlete guides in Italy.
BRX: एयरबीएनबीआ इटालीआव एथलीट गाइडफोरजों आल्पाइन हाइकफोरखौ जासियो |
--------------------------------------------------

Translating:  65%|█████████████████▌         | 649/1000 [09:05<04:00,  1.46it/s]

[649/1000]
EN: K-pop band SEVENTEEN curates music sessions for Airbnb.
BRX: के-पप बेन्ड सेभेनटीनआ एयरबीएनबीनि थाखाय देंखो सेसनफोरखौ क्यूरेट खालामो |
--------------------------------------------------

Translating:  65%|█████████████████▌         | 650/1000 [09:06<04:05,  1.42it/s]

[650/1000]
EN: Chance the Rapper partners with Airbnb for exclusive experiences.
BRX: खालि मोनदांथिफोरनि थाखाय एयरबीएनबीजों रेपारनि बाहागोआरिफोरखौ खाबु होफाथायो.
--------------------------------------------------

Translating:  65%|█████████████████▌         | 651/1000 [09:07<04:54,  1.19it/s]

[651/1000]
EN: Economic uncertainty shifts traveller behaviour toward price sensitivity.
BRX: रांखान्थियारि दिदोमथि गैयैआ दावबायारिफोरनि आखुखौ बेसेन मोनदांथिनि फारसे सोलायहोयो ꯫
--------------------------------------------------

Translating:  65%|█████████████████▌         | 652/1000 [09:08<04:45,  1.22it/s]

[652/1000]
EN: Tourists choose off-the-beaten-path destinations influenced by social media.
BRX: दावबायारिफ्रा समाजारि बिजोंजों गोहोम खोख्लैजानाय अफ-दि-बेटेन-पथ थांखि थावनिफोरखौ सायख.यो |
--------------------------------------------------

Translating:  65%|█████████████████▋         | 653/1000 [09:09<05:17,  1.09it/s]

[653/1000]
EN: Travelers turn to AI-powered tools for trip planning.
BRX: दावबायारिफ्रा दावबायनायनि सानथांखिनि थाखाय ए.आइ.जों सालायजानाय आगजुफोरनि फारसे गिदिंबोयोङ्गाङो →
--------------------------------------------------

Translating:  65%|█████████████████▋         | 654/1000 [09:10<04:56,  1.17it/s]

[654/1000]
EN: Sustainable tourism gains traction among mindful travellers.
BRX: अरायथा दावबायनाया गोसो गोनां दावबायारिफोरनि गेजेराव गोसो बोनो हानायखौ आरजियो ~जेन्नायफोर |
--------------------------------------------------

Translating:  66%|█████████████████▋         | 655/1000 [09:11<04:28,  1.29it/s]

[655/1000]
EN: Responsible travel interest grows among conscious tourists.
BRX: सांग्रां दावबायारिफोरनि गेजेराव बिबानगोनां दावबायनायनि गोसोआ बाङो ~जेन्नायफोर |
--------------------------------------------------

Translating:  66%|█████████████████▋         | 656/1000 [09:11<04:13,  1.36it/s]

[656/1000]
EN: Less-crowded destinations attract visitors avoiding overtourism.
BRX: बाङाइ - होंगो दोंगो गोनां थांखि थावनिफोरा बांद्राय दावबायनायखौ एंगारनानै दावबायारिफोरखौ गोसो बोहोयो |
--------------------------------------------------

Translating:  66%|█████████████████▋         | 657/1000 [09:12<04:00,  1.43it/s]

[657/1000]
EN: Business travel spending reaches 1.57 trillion dollars in 2025.
BRX: 2025 मायथाइयाव फालांगियारि दावबायनाय खरसाया 1.57 त्रिलियन डलारसिम सौहैयो →
--------------------------------------------------

Translating:  66%|█████████████████▊         | 658/1000 [09:13<04:10,  1.37it/s]

[658/1000]
EN: Bleisure travel surge drives business trip extensions for leisure.
BRX: ब्लिजार ट्रेभेलनि जौगानाया जिरायनाय समनि थाखाय फालांगियारि दावबायनायनि बारायनायखौ दैदेनो हानाय खालामो.
--------------------------------------------------

Translating:  66%|█████████████████▊         | 659/1000 [09:13<04:07,  1.38it/s]

[659/1000]
EN: Luxury travel shifts toward immersive experience based vacations.
BRX: देलायमालाय दावबायनाया गोजों रोंमोनदांथि बिथा खालामनाय जिरायनाय सानफोरनि फारसे सोलायबाय |
--------------------------------------------------

Translating:  66%|█████████████████▊         | 660/1000 [09:14<03:49,  1.48it/s]

[660/1000]
EN: Travvy Awards recognize top industry suppliers in November.
BRX: ट्रेभवी एवार्ड्सआ नबेम्बराव गोजौसिन दारिमिन जगायग्राफोरखौ सिनायथि होयो |
--------------------------------------------------

Translating:  66%|█████████████████▊         | 661/1000 [09:15<03:40,  1.54it/s]

[661/1000]
EN: TravelPulse announces 40 Under 40 honorees for second year.
BRX: ट्रेभेलपल्सआ नैथि बोसोरनि थाखाय 40 आन्डार40 होन 'रिफोरखौ फोसावदोंमोन |
--------------------------------------------------

Translating:  66%|█████████████████▊         | 662/1000 [09:15<03:34,  1.58it/s]

[662/1000]
EN: Travel Executive of the Year awarded at Travvy gala.
BRX: ट्रेभेल एक्जीक्युटिभ अफ द ईयरखौ ट्रेभवी गालाआव बान्था होनाय जादों |
--------------------------------------------------

Translating:  66%|█████████████████▉         | 663/1000 [09:16<03:26,  1.63it/s]

[663/1000]
EN: New members inducted into Travel Hall of Fame 2025.
BRX: ट्रेभेल हल अफ फेम 2025 आव गोदान सोद्रोमाफोरखौ सोफादेरनाय जादों |
--------------------------------------------------

Translating:  66%|█████████████████▉         | 664/1000 [09:16<03:17,  1.70it/s]

[664/1000]
EN: Young professionals recognized for innovation and leadership.
BRX: गोदान दिहुनथाय आरो दैदेननायनि थाखाय सिनायजानाय लाइमोन फालांगियारिफोर |
--------------------------------------------------

Translating:  66%|█████████████████▉         | 665/1000 [09:17<03:24,  1.64it/s]

[665/1000]
EN: FIFA World Cup 2025 travel bookings exceed host city expectations.
BRX: फिफा मुलुग काप 2025 दावबायनायनि बुकिंआ ह 'स्ट सिटीनि मिजिंफोरखौ बारायना होयो →
--------------------------------------------------

Translating:  67%|█████████████████▉         | 666/1000 [09:17<03:19,  1.67it/s]

[666/1000]
EN: Solo female travel bookings increase forty percent year on year.
BRX: हारसिङै आइजो दावबायनायनि बुकिंआ बोसोराव ब्रैजि जौखोन्दो बांदों |
--------------------------------------------------

Translating:  67%|██████████████████         | 667/1000 [09:18<03:23,  1.63it/s]

[667/1000]
EN: Wellness tourism emerges as fastest growing travel segment globally.
BRX: सावस्रि दावबायथाया बुहुमनाङै बयनिख्रुइबो गोख्रैसिन जौगानाय दावबायनाय खोन्दो महरै नुजाबोदों |
--------------------------------------------------

Translating:  67%|██████████████████         | 668/1000 [09:19<03:47,  1.46it/s]

[668/1000]
EN: Indian millennials prefer experiential travel over shopping vacations.
BRX: भारतारि रोजा बोसोरयारिफोरा शपिं जिरायनाय सानफोरनि अनगा रोंमोनदांथिगोनां दावबायनायखौ मोजां मोनो/जेन्नायफोर |
--------------------------------------------------

Translating:  67%|██████████████████         | 669/1000 [09:20<03:57,  1.39it/s]

[669/1000]
EN: Workation packages gain popularity among remote corporate employees.
BRX: खामानि पेकेजफोरा गोजान कर्परेट मावसाफोरनि गेजेराव मुंदांखाथि आरजियो ~जेन्नायखिमाफोर |
--------------------------------------------------

Translating:  67%|██████████████████         | 670/1000 [09:21<04:34,  1.20it/s]

[670/1000]
EN: Culinary tourism drives foodies to regional Indian destinations.
BRX: संनाय-लायनाया दावबायनाया जाग्रा आदारफोरखौ ओनसोलारि भारतारि थांखिथिलिसिम दैदेनो हानाय खालामो.
--------------------------------------------------

Translating:  67%|██████████████████         | 671/1000 [09:21<03:54,  1.40it/s]

[671/1000]
EN: Night tourism initiatives launched by Maharashtra and Karnataka.
BRX: महाराष्ट्र आरो कर्नाटकजों जागायजेन्नाय हर दावबायथाय बिथांखिफोर |
--------------------------------------------------

Translating:  67%|██████████████████▏        | 672/1000 [09:22<03:48,  1.43it/s]

[672/1000]
EN: Astro tourism gains ground with dark sky parks in Ladakh.
BRX: लाद्दाखआव गोसोम अख्राङारि पार्कफोरजों एस्ट्रो दावबायनाया जाफुंसारदों |
--------------------------------------------------

Translating:  67%|██████████████████▏        | 673/1000 [09:23<03:42,  1.47it/s]

[673/1000]
EN: Film induced tourism boosts Kashmir valley hotel occupancy.
BRX: सावथुन थुलुंगानाय दावबायथाया काश्मीर हायेनाव हटेल थानायखौ बांहोयो |
--------------------------------------------------

Translating:  67%|██████████████████▏        | 674/1000 [09:23<03:33,  1.53it/s]

[674/1000]
EN: Wedding tourism contributes five billion dollars to Indian economy.
BRX: हाबानि दावबायनाया भारतारि रांखान्थिनि थाखाय बा बिलियन डलार बिहोमा होयो.
--------------------------------------------------

Translating:  68%|██████████████████▏        | 675/1000 [09:24<03:38,  1.49it/s]

[675/1000]
EN: India promotes MICE tourism for meetings and exhibitions.
BRX: भारतआ जथुमफोर आरो दिन्थिफुंनायनि थाखाय एम.आइ.सि.इ. दावबायनायखौ थुलुंगा होयो |
--------------------------------------------------

Translating:  68%|██████████████████▎        | 676/1000 [09:25<03:41,  1.46it/s]

[676/1000]
EN: West Bengal develops MICE tourism segments under Mamata Banerjee.
BRX: सोनाब बंगआ ममता बनर्जीनि सिङाव एम.आइ.सि.इ. दावबायथाय खोन्दोफोरखौ जौगाहोयो |
--------------------------------------------------

Translating:  68%|██████████████████▎        | 677/1000 [09:25<03:29,  1.54it/s]

[677/1000]
EN: India positions itself as medical value travel destination.
BRX: भारतआ गावखौ सावस्रियारि बेसेन दावबायनाय थांखि थावनि महरै फज 'दों |
--------------------------------------------------

Translating:  68%|██████████████████▎        | 678/1000 [09:26<03:24,  1.57it/s]

[678/1000]
EN: Wellness tourism positions India as holistic healing leader.
BRX: सावस्रि दावबायथाया भारतखौ आबुं फाहामनायनि दैदेनगिरि महरै मासि होयो |
--------------------------------------------------

Translating:  68%|██████████████████▎        | 679/1000 [09:27<03:41,  1.45it/s]

[679/1000]
EN: Concert tourism attracts international visitors to Indian music festivals.
BRX: कनसार्ट दावबायनाया भारतारि देंखो फोरबोफोराव हादोरगेजेरारि दावबायारिफोरखौ गोसो बोहोयो |
--------------------------------------------------

Translating:  68%|██████████████████▎        | 680/1000 [09:27<03:29,  1.53it/s]

[680/1000]
EN: Gajendra Shekhawat highlights India's concert tourism potential.
BRX: गजेन्द्र शेखावतआ भारतनि कनसार्ट टुरिजम जाथावनाखौ दिन्थियो |
--------------------------------------------------

Translating:  68%|██████████████████▍        | 681/1000 [09:28<03:43,  1.42it/s]

[681/1000]
EN: India promotes integrated rehabilitation pathways for medical tourists.
BRX: भारतआ सावस्रियारि दावबायारिफोरनि थाखाय जथाय फिन फसंनाय लामाफोरखौ थुलुंगा होयोपाटान्थिफोर |
--------------------------------------------------

Translating:  68%|██████████████████▍        | 682/1000 [09:28<03:17,  1.61it/s]

[682/1000]
EN: Business travel makes significant comeback post pandemic.
BRX: महामारीनि उनाव फालांगियारि दावबायनाया गोनांथार फैफिनो |
--------------------------------------------------

Translating:  68%|██████████████████▍        | 683/1000 [09:29<03:08,  1.68it/s]

[683/1000]
EN: Companies increase trip volumes and expand travel budgets.
BRX: कम्पानिफोरा दावबायनायनि बिबांखौ बांहोयो आरो दावबायनाय बाजेटखौ फुवारहोयो ꯫
--------------------------------------------------

Translating:  68%|██████████████████▍        | 684/1000 [09:30<03:07,  1.68it/s]

[684/1000]
EN: In-person collaboration demand drives business travel recovery.
BRX: गावारि हेफाजाबनि दाबिआ फालांगियारि दावबायनाय रिकभारिखौ दैदेनो हानाय खालामो.
--------------------------------------------------

Translating:  68%|██████████████████▍        | 685/1000 [09:30<03:07,  1.68it/s]

[685/1000]
EN: Hyderabad International Convention Centre hosts global pharmaceutical summit.
BRX: हैदराबाद इन्टारनेशनेल कनभेनशन सेन्टारा बुहुमनां मुलियारि जथुममा खुङो |
--------------------------------------------------

Translating:  69%|██████████████████▌        | 686/1000 [09:31<03:31,  1.48it/s]

[686/1000]
EN: Bharat Mandapam witnesses record MICE bookings for fiscal year.
BRX: भारत मंडपमआ रांखान्थियारि बोसोरनि थाखाय एम.आइ.सि.इ. बुकिंफोरखौ रेबगान्थि खालामो |
--------------------------------------------------

Translating:  69%|██████████████████▌        | 687/1000 [09:32<03:54,  1.34it/s]

[687/1000]
EN: Medical tourism arrivals cross pre-Covid levels with six lakh visitors.
BRX: सावस्रियारि दावबायथाय फैनाया द'लाख नायगिरिफोरजों आगु-कविड थाखोखौ बारलाङो →
--------------------------------------------------

Translating:  69%|██████████████████▌        | 688/1000 [09:33<03:39,  1.42it/s]

[688/1000]
EN: AYUSH wellness centres attract foreign tourists for traditional treatments.
BRX: आयुश सावस्रि मिरुफोरा दोरोङारि फाहामनायनि थाखाय गुबुन हादोरारि दावबायारिफोरखौ गोसो बोहोयो.
--------------------------------------------------

Translating:  69%|██████████████████▌        | 689/1000 [09:34<04:11,  1.24it/s]

[689/1000]
EN: Delhi NCR hotels report seventy percent occupancy from corporate travellers.
BRX: दिल्ली एन.सी.आर. हतेलफोरा कर्परेट दावबायारिफोरनिफ्राय स्निजि जौखोन्दो दखल खालामनायनि फोरमायथि होयो |
--------------------------------------------------

Translating:  69%|██████████████████▋        | 690/1000 [09:34<04:03,  1.27it/s]

[690/1000]
EN: Maha Kumbh infrastructure delivers long-term tourism economic benefits.
BRX: महा कुम्भ बिथायारि सानजथाइया गोलाव समनि दावबायथाय रांखान्थियारि मुलाम्फाखौ होयो.
--------------------------------------------------

Translating:  69%|██████████████████▋        | 691/1000 [09:35<03:51,  1.34it/s]

[691/1000]
EN: Venice entry fee revenues fund city upkeep and travel management.
BRX: वेनिसआव हाबनायनि मासुलनि खाजोनाया सोहोरनि जोथोन लानाय आरो दावबायनाय सामलायनायनि थाखाय रां होयो.
--------------------------------------------------

Translating:  69%|██████████████████▋        | 692/1000 [09:36<03:52,  1.32it/s]

[692/1000]
EN: Critics question Venice day-tripper fee effectiveness for crowd control.
BRX: सावरायगिरिफोरा होंगो-गोहो दबथायनायनि थाखाय वेनिस डे-ट्रिपार मासुलनि गोहोमथिखौ सोंदोंमोन |
--------------------------------------------------

Translating:  69%|██████████████████▋        | 693/1000 [09:36<03:47,  1.35it/s]

[693/1000]
EN: Bulgaria joins Eurozone as twenty-first member on January 1 2026.
BRX: बुलगेरियाआ 1 जानुवारि 2026 मायथाइयाव नैजिथि सोद्रोमा महरै इउर 'जᱳᱱआव बाहागो लायो |
--------------------------------------------------

Translating:  69%|██████████████████▋        | 694/1000 [09:37<03:31,  1.45it/s]

[694/1000]
EN: Both Lev and Euro accepted in Bulgaria during January transition.
BRX: बुलगेरियायाव इउ.आर. आरो लेभखौ गनायनाय जादोंमोन |
--------------------------------------------------

Translating:  70%|██████████████████▊        | 695/1000 [09:38<03:44,  1.36it/s]

[695/1000]
EN: Lufthansa announces daily Frankfurt-Bengaluru flights starting March 2026.
BRX: लुफथानसाया मार्च 2026 मायथाइनिफ्राय सानफ्रोमबो फ्रेंकफर्ट-बेन्गालुर बिरग्रा दिङाफोरखौ फोसावनाय जायो ꯫
--------------------------------------------------

Translating:  70%|██████████████████▊        | 696/1000 [09:39<03:37,  1.40it/s]

[696/1000]
EN: Alliance Air introduces direct flights from Delhi to Darbhanga.
BRX: एलायन्स एयरआ दिल्लीनिफ्राय दरभंगासिम थोंजों बिरखंफोर जागायजेनो →
--------------------------------------------------

Translating:  70%|██████████████████▊        | 697/1000 [09:39<03:39,  1.38it/s]

[697/1000]
EN: Emirates deploys A380 on Ahmedabad-Dubai route for winter season.
BRX: एमिरेटसआ गोजां बोथोरनि थाखाय आहमेदाबाद-दुबाई लामायाव ए380 खौ थिसन्नो हायोपाटों ।
--------------------------------------------------

Translating:  70%|██████████████████▊        | 698/1000 [09:40<03:22,  1.49it/s]

[698/1000]
EN: fly91 commences operations from Goa to Hyderabad and Pune.
BRX: फ्लाइ91आ गवानिफ्राय हायद्राबाद आरो पुनेसिम हाबाफारि जागायजेनो →
--------------------------------------------------

Translating:  70%|██████████████████▊        | 699/1000 [09:41<03:43,  1.35it/s]

[699/1000]
EN: British Airways resumes London-Chennai service after four-year hiatus.
BRX: ब्रिटिश एयारवेजआ बोसोरब्रैनि उनाव लण्डन-चेन्नायनि मावमिनखौ जागायजेनो →
--------------------------------------------------

Translating:  70%|██████████████████▉        | 700/1000 [09:41<03:40,  1.36it/s]

[700/1000]
EN: Go First employees protest outside NCLT over unpaid salaries.
BRX: गो फर्स्टनि मावगिरिफोरा रां होजायाखै होन्ना एन.सि.एल.टि. नि बायजोआव हेंथा दिन्थिदों |
--------------------------------------------------

Translating:  70%|██████████████████▉        | 701/1000 [09:42<03:43,  1.34it/s]

[701/1000]
EN: Saudi carrier Flynas plans direct Riyadh-Lucknow operations by April.
BRX: साउदीनि केरियार फ्लाइनासआ एप्रिलसिमाव रियाद-लखनउखौ बिथोन होनो सानथांखि बानायदों |
--------------------------------------------------

Translating:  70%|██████████████████▉        | 702/1000 [09:43<03:35,  1.38it/s]

[702/1000]
EN: Flybig announces daily flights from Guwahati to Imphal and Agartala.
BRX: फ्लाइबिगआ गुवाहाटीनिफ्राय इम्फल आरो आगरतलासिम सानफ्रोमबोनि बिरखंफोरखौ फोसावदोंमोन |
--------------------------------------------------

Translating:  70%|██████████████████▉        | 703/1000 [09:44<03:27,  1.43it/s]

[703/1000]
EN: Kolkata airport wins cleanest airport award in 15-25 million category.
BRX: कलकाता बिरखं गाथोना 15-25 मिलियन थाखोआव बयनिख्रुइबो साखोन- सिखोन बिरखं गाथोन बान्था देरहादों |
--------------------------------------------------

Translating:  70%|███████████████████        | 704/1000 [09:44<03:18,  1.49it/s]

[704/1000]
EN: Patna airport's new terminal to handle forty lakh passengers annually.
BRX: पाटना बिरखं गाथोननि गोदान टार्मिनालआ बोसोराव ब्रैजि लाख दावबायारिफोरखौ सामलायगोन.
--------------------------------------------------

Translating:  70%|███████████████████        | 705/1000 [09:45<03:23,  1.45it/s]

[705/1000]
EN: Fog forces thirty-two flight diversions at Chandigarh airport.
BRX: चन्डीगढ़ बिरखं गाथोनाव खुवाया थामजि-बाइ फ्लाइथ डायवर्सनखौ नारसिनो गोनां खालामो |
--------------------------------------------------

Translating:  71%|███████████████████        | 706/1000 [09:45<03:17,  1.49it/s]

[706/1000]
EN: Ethiopian Airlines considers Mumbai and Delhi as new African hub.
BRX: इथोपियान एयारलाइन्सआ मुम्बाइ आरो दिल्लीखौ गोदान आफ्रीकानि मिरु महरै मानियो |
--------------------------------------------------

Translating:  71%|███████████████████        | 707/1000 [09:46<03:08,  1.55it/s]

[707/1000]
EN: IndiGo passenger dies aboard Delhi-Bengaluru flight mid-air.
BRX: दिल्ली-बेन्गालुरु बिरखंनि गेजेराव इन्डिगो दावबायग्राया थैदों |
--------------------------------------------------

Translating:  71%|███████████████████        | 708/1000 [09:47<03:09,  1.54it/s]

[708/1000]
EN: VietJet Air announces daily Hanoi-Ahmedabad service from December.
BRX: भियेटजेट एयरआ दिसेम्बरनिफ्राय सानफ्रोमबो हनोई- आहमेदाबाद सिबिथाइखौ फोसावनाय जायो |
--------------------------------------------------

Translating:  71%|███████████████████▏       | 709/1000 [09:47<03:09,  1.53it/s]

[709/1000]
EN: Odisha government approves ten new tourism circuits for development.
BRX: अडिशा सोरखारा जौगाथायनि थाखाय मोनजि गोदान दावबायथाय सार्किटफोरखौ गनायथि होयो |
--------------------------------------------------

Translating:  71%|███████████████████▏       | 710/1000 [09:48<03:04,  1.57it/s]

[710/1000]
EN: Madhya Pradesh unveils film tourism policy with 25 percent subsidy.
BRX: मध्य प्रदेशआ 25 जौखोन्दो साब्सिडीजों सावथुन दावबायथाय खान्थिखौ फोसावनाय जादों |
--------------------------------------------------

Translating:  71%|███████████████████▏       | 711/1000 [09:49<02:56,  1.64it/s]

[711/1000]
EN: Gujarat grants industry status to homestays and farmstays.
BRX: गुजरातआ होमस्टे आरो फार्मस्टेखौ दारिमिननि थामान होयो |
--------------------------------------------------

Translating:  71%|███████████████████▏       | 712/1000 [09:49<02:50,  1.69it/s]

[712/1000]
EN: Himachal Pradesh caps tourist entry to Manali and Rohtang Pass.
BRX: हिमाचल प्रदेशआ मनाली आरो रोहतांग पासआव दावबायारि हाबफैनायखौ थि खालामो |
--------------------------------------------------

Translating:  71%|███████████████████▎       | 713/1000 [09:50<02:54,  1.65it/s]

[713/1000]
EN: Kerala launches responsible tourism mission for waste-free destinations.
BRX: केरालाया गारनाय-गैयै थांखि थावनिफोरनि थाखाय बिबानगोनां दावबायथाय मिशन जागायदों |
--------------------------------------------------

Translating:  71%|███████████████████▎       | 714/1000 [09:50<02:56,  1.62it/s]

[714/1000]
EN: Australia removes minimum bank balance requirement for Indian student visas.
BRX: अस्ट्रेलियाया भारतारि फरायसा भिसानि थाखाय बाङाइसिन बेंक बेलेन्सनि गोनांथिखौ बोखारदों |
--------------------------------------------------

Translating:  72%|███████████████████▎       | 715/1000 [09:51<03:06,  1.53it/s]

[715/1000]
EN: UK introduces Electronic Travel Authorisation for Indian passport holders.
BRX: इउ.के.आ भारतारि पासपोर्ट हमग्राफोरनि थाखाय इलेक्ट्रनिक ट्रेभेल अथराइजेशनखौ जागायजेनो →
--------------------------------------------------

Translating:  72%|███████████████████▎       | 716/1000 [09:52<03:15,  1.45it/s]

[716/1000]
EN: Saudi Arabia extends stopover visa validity from four to ninety-six hours.
BRX: साउदी आरबनि स्टपअभार भिसानि उदांश्रीखौ ब्रैनिफ्राय गुजि-द'घन्टासिम बारायनाय जादों |
--------------------------------------------------

Translating:  72%|███████████████████▎       | 717/1000 [09:53<03:42,  1.27it/s]

[717/1000]
EN: Malaysia grants thirty-day visa-free entry to Indian nationals till December.
BRX: मलेशियाया दिसेम्बरसिम भारतारि नोगोरारिफोरनो थामजि साननि भिजा-फ्री हाबनायखौ गनायथि होयोपाटियाफोरआ गेजेर गेजेरनिफ्राय गुबुन हादोरफोराव सौहैनो थाखाय थांखि लायो.
--------------------------------------------------

Translating:  72%|███████████████████▍       | 718/1000 [09:54<03:47,  1.24it/s]

[718/1000]
EN: Thailand extends visa-free stay for Indians from thirty to sixty days.
BRX: थाइलेन्डआ भारतारिफोरनि थाखाय भिजा गैयालासे थानायनि समखौ थामजिनिफ्राय दजि सानसिम बांहोयो |
--------------------------------------------------

Translating:  72%|███████████████████▍       | 719/1000 [09:55<04:08,  1.13it/s]

[719/1000]
EN: Indonesia proposes visa-free entry for Indian tourists to boost Bali arrivals.
BRX: इन्डोनेशियाआ बालीआव फैनायफोरखौ बांहोनो थाखाय भारतारि दावबायारिफोरनि थाखाय भिजा-फ्री हाबनायनि थांखि लायोपाटियाफोर ।
--------------------------------------------------

Translating:  72%|███████████████████▍       | 720/1000 [09:56<03:59,  1.17it/s]

[720/1000]
EN: European Parliament approves ETIAS system launch for mid-2026.
BRX: इउ.आर.पि.आ जुन्थिफोरनि थाखाय मोनसे गोदान आदब दिहुनदों |
--------------------------------------------------

Translating:  72%|███████████████████▍       | 721/1000 [09:56<03:42,  1.25it/s]

[721/1000]
EN: Sri Lanka cabinet approves visa-free entry for nationals of thirty-five countries.
BRX: श्रीलंकानि केबिनेटआ थामजिबा हादोरनि नोगोरारिफोरनि थाखाय भिजा गैयै हाबनायखौ गनायथि होयो →
--------------------------------------------------

Translating:  72%|███████████████████▍       | 722/1000 [09:57<04:16,  1.08it/s]

[722/1000]
EN: Waives visa fees for Indian senior citizens above sixty-five years.
BRX: 60 बोसोरनि गोजौनि भारतारि बैसोगोरा नोगोरारिफोरनि थाखाय भिजा मासुलखौ बोखारनाय जादों |
--------------------------------------------------

Translating:  72%|███████████████████▌       | 723/1000 [09:58<03:50,  1.20it/s]

[723/1000]
EN: Bhutan revises Sustainable Development Fee to one thousand two hundred rupees.
BRX: भूटानआ अरायथा जौगाथाय मासुलखौ से रोजा नैजौ रांसिम फोसाबबाय |
--------------------------------------------------

Translating:  72%|███████████████████▌       | 724/1000 [09:59<03:41,  1.25it/s]

[724/1000]
EN: Nepal allows Indian tourists to pay in rupees at immigration checkpoints.
BRX: नेपालआ भारतारि दावबायारिफोरखौ इमीग्रेसन चेकप 'न्टफोराव रां होनो गनायथि होयोपाटिनो ।
--------------------------------------------------

Translating:  72%|███████████████████▌       | 725/1000 [09:59<03:21,  1.36it/s]

[725/1000]
EN: Myanmar junta extends e-visa facility for Indian travellers.
BRX: म्यानमार जुन्टाया भारतारि दावबायारिफोरनि थाखाय ई-भिसा खाबु फुवारदों |
--------------------------------------------------

Translating:  73%|███████████████████▌       | 726/1000 [10:00<03:23,  1.34it/s]

[726/1000]
EN: Mauritius scraps PCR test requirement for fully vaccinated Indian visitors.
BRX: मावरिसासआ आबुङै टिकाहोजानाय भारतारि दावबायारिफोरनो पि.सि.आर. आनजादनि गोनांथिखौ फोजोबदों |
--------------------------------------------------

Translating:  73%|███████████████████▋       | 727/1000 [10:01<03:12,  1.42it/s]

[727/1000]
EN: Kenya removes visa requirement for all Indian passport holders.
BRX: केन्याआ गासिबो भारतारि पासपोर्ट हमग्रानि थाखाय भिसानि गोनांथिखौ बोखारदों |
--------------------------------------------------

Translating:  73%|███████████████████▋       | 728/1000 [10:01<02:53,  1.56it/s]

[728/1000]
EN: Rajasthan government launches mobile app for heritage hotel bookings.
BRX: राजस्थान सोरखारा हेरिटेज हटेल बुकिंनि थाखाय जानबुं एप जागायदों |
--------------------------------------------------

Translating:  73%|███████████████████▋       | 729/1000 [10:02<02:51,  1.58it/s]

[729/1000]
EN: Assam receives fifty-five lakh domestic tourists during 2024-2025.
BRX: आसामा 2024-2025 मायथाइनि गेजेराव बाजि-बा लाख नखरारि दावबायारिफोरखौ मोन्नो हागोन |
--------------------------------------------------

Translating:  73%|███████████████████▋       | 730/1000 [10:03<03:03,  1.47it/s]

[730/1000]
EN: Hemanta Biswa Sarma credits improved law and order for tourism growth.
BRX: हेमन्ता बिस्बा सरमाया दावबायफालांगि जौगानायनि थाखाय साबसिन आयेन आरो बिखान्थिखौ मान होयो |
--------------------------------------------------

Translating:  73%|███████████████████▋       | 731/1000 [10:03<03:04,  1.46it/s]

[731/1000]
EN: Madhya Pradesh records 112.1 million tourist visits in 2024.
BRX: मध्य प्रदेशआ इं 2024 माइथायाव 112.1 मिलियन दावबायारि दावबायनायखौ रेबगान्थि खालामदों |
--------------------------------------------------

Translating:  73%|███████████████████▊       | 732/1000 [10:04<03:10,  1.41it/s]

[732/1000]
EN: Meghalaya welcomes twenty-one lakh visitors crossing pre-pandemic figures.
BRX: मेघालयआ महामारीनि सिगांनि अनजिमाफोरखौ बारलांनानै नैजि से लाख दावबायारिफोरखौ बरायनो थाखाय थांखि लायो →
--------------------------------------------------

Translating:  73%|███████████████████▊       | 733/1000 [10:05<02:58,  1.50it/s]

[733/1000]
EN: Jammu and Kashmir registers two crore tourist footfall in 2025.
BRX: जम्मु- काश्मीरआ इं 2025 माइथायाव नै कौटि दावबायारिफोरनि आगानखौ रेबथुमदों |
--------------------------------------------------

Translating:  73%|███████████████████▊       | 734/1000 [10:05<02:57,  1.50it/s]

[734/1000]
EN: LG Manoj Sinha announces highest ever tourist arrival in Kashmir Valley.
BRX: एल.जि. मनज सिन्हाया काश्मीर हायेनाव बयनिख्रुइ बांसिन दावबायारि सौफैनायखौ फोसावदोंमोन |
--------------------------------------------------

Translating:  74%|███████████████████▊       | 735/1000 [10:06<03:06,  1.42it/s]

[735/1000]
EN: Lakshadweep receives eighty-three thousand visitors after PM Modi visit.
BRX: लक्षद्वीपआ पि. एम. मोदीनि दावबायहैनायनि उनाव दाइनजि-थाम रोजा दावबायारिफोरखौ लोगो लायो |
--------------------------------------------------

Translating:  74%|███████████████████▊       | 736/1000 [10:07<03:03,  1.44it/s]

[736/1000]
EN: Uttarakhand witnesses five crore pilgrim visits to Char Dham shrines.
BRX: उत्तराखन्डआ चार धाम थानसालिफोराव बा कौटि धोरोमदावबायारि दावबायनायनि साखि जादों |
--------------------------------------------------

Translating:  74%|███████████████████▉       | 737/1000 [10:07<02:56,  1.49it/s]

[737/1000]
EN: Pushkar fair attracts fifteen lakh tourists including thirty thousand foreigners.
BRX: पुष्कर मेलाया थामजि रोजा गुबुन हादोरारिफोरजों लोगोसे जिबा लाख दावबायारिफोरखौ गोसो बोहोयो |
--------------------------------------------------

Translating:  74%|███████████████████▉       | 738/1000 [10:08<02:58,  1.47it/s]

[738/1000]
EN: Surajkund Mela records forty-eight percent increase in international participation.
BRX: सूरजकुंड मेलाया हादोर गेजेरारि बाहागोलायनायआव ब्रैजि- दाइन जौखोन्दो बांनाय रेबगान्थि खालामदों |
--------------------------------------------------

Translating:  74%|███████████████████▉       | 739/1000 [10:09<03:08,  1.38it/s]

[739/1000]
EN: Singapore welcomes 1.2 million Indian visitors becoming top source market.
BRX: सिंगापुरआ 12 लाख भारतारि दावबायारिफोरखौ गोजौसिन फुंखा हाथाय जानानै बरायनो थाखाय गोसो होयो →
--------------------------------------------------

Translating:  74%|███████████████████▉       | 740/1000 [10:10<02:56,  1.48it/s]

[740/1000]
EN: Dubai hosts record 2.1 million Indian tourists in first half 2025.
BRX: दुबाइआ इं 2025 माइथायनि गिबि खावसेयाव 2.1 मिलियन भारतारि दावबायारिफोरनि रेबगान्थि खालामो |
--------------------------------------------------

Translating:  74%|████████████████████       | 741/1000 [10:10<02:55,  1.48it/s]

[741/1000]
EN: Thailand receives 1.8 million Indian travellers during January-October period.
BRX: थाइलेन्डआ जानुवारि-अक्ट 'बर समनि गेजेराव 1.8 मिलियन भारतारि दावबायारिफोरखौ मोनो ꯫
--------------------------------------------------

Translating:  74%|████████████████████       | 742/1000 [10:11<02:58,  1.45it/s]

[742/1000]
EN: Maldives sees forty percent drop in Indian tourist arrivals amid diplomatic row.
BRX: मालदिभ्सआव राजखानथियारि दावराव-दावसिनि गेजेराव भारतारि दावबायारि सौफैनाया ब्रैजि जौखोन्दो खमायदों |
--------------------------------------------------

Translating:  74%|████████████████████       | 743/1000 [10:12<02:48,  1.52it/s]

[743/1000]
EN: Nepal earns 110 billion rupees from Indian tourists in fiscal year.
BRX: नेपालआ रांखान्थियारि बोसोराव भारतारि दावबायारिफोरनिफ्राय 110 बिलियन रां आरजियोङ्गाङो |
--------------------------------------------------

Translating:  74%|████████████████████       | 744/1000 [10:12<02:53,  1.48it/s]

[744/1000]
EN: Turkey welcomes three lakh Indian tourists targeting five lakh by year-end.
BRX: तुर्कीआ बोसोर जोबनायसिम बा लाखनि थांखि लानानै थाम लाख भारतारि दावबायारिफोरखौ बरायनो थाखाय थांखि लायो →
--------------------------------------------------

Translating:  74%|████████████████████       | 745/1000 [10:13<02:42,  1.57it/s]

[745/1000]
EN: Egypt reports 1.5 lakh Indian arrivals aiming for three lakh target.
BRX: इजिप्टआ थाम लाख थांखि लानानै 1.50 लाख भारतारि सफैनायनि फोरमायथि होयो |
--------------------------------------------------

Translating:  75%|████████████████████▏      | 746/1000 [10:13<02:42,  1.56it/s]

[746/1000]
EN: Azerbaijan attracts two lakh Indian visitors visa-free policy credited.
BRX: अजरबैजानआ नै लाख भारतारि दावबायारि भिसामुक्ति खान्थिखौ गोसो बोनो हायो |
--------------------------------------------------

Translating:  75%|████████████████████▏      | 747/1000 [10:14<02:40,  1.58it/s]

[747/1000]
EN: Georgia registers 1.75 lakh Indian tourist arrivals between January-September.
BRX: जर्जियाया जानुवारि- सेप्तेम्बरनि गेजेराव 1.75 लाख भारतारि दावबायारि सफैनायखौ रेबथुमदों |
--------------------------------------------------

Translating:  75%|████████████████████▏      | 748/1000 [10:15<02:41,  1.56it/s]

[748/1000]
EN: Kenya targets one lakh Indian tourists with aggressive marketing campaign.
BRX: केन्याआ गाग्लोबारि हाथाय फोसावथायजों से लाख भारतारि दावबायारिफोरखौ थांखि लायो →
--------------------------------------------------

Translating:  75%|████████████████████▏      | 749/1000 [10:15<02:49,  1.48it/s]

[749/1000]
EN: Udaipur airport gets new terminal building costing five hundred crore rupees.
BRX: उदयपुर बिरखं गाथोना बाजौ कौटि रां बेसेननि गोदान टार्मिनाल बिल्दिं बानायदों |
--------------------------------------------------

Translating:  75%|████████████████████▎      | 750/1000 [10:16<03:10,  1.31it/s]

[750/1000]
EN: Rajkot airport renamed after former Prime Minister Morarji Desai.
BRX: राजकोटा बिरखं गाथोननि मुंखौ सोलायनानै सिगांनि गाहाय मन्थ्रि मोरारजी देसाईनि मुङै दोननाय जादोंपाटिया हादोर गेजेरारि हायुं आवथाफोरनि गेजेराव मोनसे ।
--------------------------------------------------

Translating:  75%|████████████████████▎      | 751/1000 [10:17<03:13,  1.29it/s]

[751/1000]
EN: Noida International Airport to begin flight operations by April 2026.
BRX: नय़ेडा हादोरगेजेरारि बिरखं गाथोना एप्रिल 2026 मायथाइसिमाव बिरखं सालायनायखौ जागायनो हागोन →
--------------------------------------------------

Translating:  75%|████████████████████▎      | 752/1000 [10:18<03:04,  1.35it/s]

[752/1000]
EN: Chennai airport opens dedicated lounge for transiting international passengers.
BRX: चेन्नाई बिरखं गाथोना हादोर गेजेरारि दावबायारिफोरनि थाखाय बावसोमनाय लाउन्ज खुलिगोन →
--------------------------------------------------

Translating:  75%|████████████████████▎      | 753/1000 [10:19<03:08,  1.31it/s]

[753/1000]
EN: Guwahati-Rohingya railway project completes tunneling work in Mizoram.
BRX: गुवाहाटी-रहिंग्या रेलवे आसोलाया मिजडरामआव सुरंग बानायनायनि खामानिखौ फोजोबदों |
--------------------------------------------------

Translating:  75%|████████████████████▎      | 754/1000 [10:19<03:01,  1.35it/s]

[754/1000]
EN: Katra-Delhi Vande Bharat Express reduces travel time by three hours.
BRX: दिल्ली-देल्ही वंदे भारत एक्सप्रेसआ दावबायनायनि समखौ थाम घन्टासिम खम खालामोपाटों ।
--------------------------------------------------

Translating:  76%|████████████████████▍      | 755/1000 [10:20<02:58,  1.37it/s]

[755/1000]
EN: Mumbai-Ahmedabad bullet train project completes fifty percent of viaduct work.
BRX: मुम्बाइ- आहमेदाबाद बुलेट ट्रेन प्रजेक्टा वायाडक्टनि खामानिखौ बाजि जौखोन्दो आबुं खालामो.
--------------------------------------------------

Translating:  76%|████████████████████▍      | 756/1000 [10:21<02:55,  1.39it/s]

[756/1000]
EN: Indian Railways introduces 200 superfast trains for summer rush.
BRX: भारतारि रेलवेआ गोलोम बोथोरनि होंगो-गोहोनि थाखाय 200 सुपारफास्ट ट्रेनफोर जागायजेनो →
--------------------------------------------------

Translating:  76%|████████████████████▍      | 757/1000 [10:22<02:57,  1.37it/s]

[757/1000]
EN: Kochi water metro adds four new routes connecting Vypin and Goshree islands.
BRX: क.चि. वाटार मेट्र 'आ वाइपिन आरो गश्री दिपफोरखौ फोनांजाबग्रा मोनब्रै गोदान लामाफोर दाजाबदेरो ꯫
--------------------------------------------------

Translating:  76%|████████████████████▍      | 758/1000 [10:22<02:42,  1.49it/s]

[758/1000]
EN: Ayodhya's Ram Path revamp completed ahead of Pran Pratishtha anniversary.
BRX: अयोध्यानि राम पथ फोसाबनाया प्राण प्रतिष्ठा बोसोरारि फालिथायनि सिगां आबुं जादों |
--------------------------------------------------

Translating:  76%|████████████████████▍      | 759/1000 [10:23<02:45,  1.46it/s]

[759/1000]
EN: Kedarnath ropeway project gets environmental clearance from ministry.
BRX: केदारनाथ रोपवे प्रजेक्टा मनथ्रिनिफ्राय आबहावायारि गनायथि मोनो →
--------------------------------------------------

Translating:  76%|████████████████████▌      | 760/1000 [10:24<02:44,  1.46it/s]

[760/1000]
EN: Hemkund Sahib helicopter service fares capped at five thousand rupees.
BRX: हेमकुंड साहिब हेलीकप्टार सिबिथायनि भाराया बा रोजा रांसिम सिमाहोजादोंमोन.
--------------------------------------------------

Translating:  76%|████████████████████▌      | 761/1000 [10:24<02:44,  1.46it/s]

[761/1000]
EN: Statue of Unity adds laser show and sound and light attraction.
BRX: स्टेच्यु अफ यूनिटीआ लेजार दिन्थिफुंनाय आरो सोदोब आरो सोरांनि गोसो बोनो हानायखौ दाजाबदेरो →
--------------------------------------------------

Translating:  76%|████████████████████▌      | 762/1000 [10:25<02:39,  1.49it/s]

[762/1000]
EN: Khajuraho airport receives international status for charter operations.
BRX: खजुराहो बिरखं गाथोना चार्टार सामलायनायनि थाखाय हादोर गेजेरारि थामान मोनो →
--------------------------------------------------

Translating:  76%|████████████████████▌      | 763/1000 [10:25<02:37,  1.51it/s]

[763/1000]
EN: Puducherry tourism department renovates French War Memorial promenade.
BRX: पुडुचेरी दावबायफालांगि बिफानआ फ्रेन्स वार मेमरियेल प्रमनेडखौ गोदान खालामफिनदों |
--------------------------------------------------

Translating:  76%|████████████████████▋      | 764/1000 [10:26<02:39,  1.48it/s]

[764/1000]
EN: Dal Lake restoration project includes de-weeding and island development.
BRX: दाल बिलो फोसाबनाय बिथांखियाव हाग्रा दानगारनाय आरो दिप जौगाथाय दं ꯫
--------------------------------------------------

Translating:  76%|████████████████████▋      | 765/1000 [10:27<02:59,  1.31it/s]

[765/1000]
EN: Hampi gets world-class interpretation centre showcasing Vijayanagara heritage.
BRX: हम्पीआ बिजयनगरनि उनमोनथाइखौ दिन्थिग्रा मुलुग थाखोनि बुंफुरलु मिरु मोनो |
--------------------------------------------------

Translating:  77%|████████████████████▋      | 766/1000 [10:30<05:12,  1.34s/it]

[766/1000]
EN: Mahabalipuram shoreline monument gets LED lighting for night viewing.
BRX: महाबलीपुरम लैथो रुगुं गोसोखां खाम्फाया हर नायनायनि थाखाय एल.ई.डी. सोरां मोनो →
--------------------------------------------------

Translating:  77%|████████████████████▋      | 767/1000 [10:33<07:01,  1.81s/it]

[767/1000]
EN: Ajanta-Ellora caves introduce audio guides in ten international languages.
BRX: अजन्ता-एलरानि दन्दरफोरा जि हादोर गेजेरारि रावफोराव अडिय. गाइड्सखौ सिनायथि होयोपाटिया जादों/09/1/2/8/7/6/5/3/4/0/10/16/14/18/12/13/22/15/24/30/26/27/19,4000/9,000/25/35/50/70/80/90/40/60/23/20/21/11/100/2007/11/गोजानायफोरखौ सिनायथि होनाय जादोंांकियोरारि लामा दिन्थिग्राफोर ।
--------------------------------------------------

Translating:  77%|████████████████████▋      | 768/1000 [10:33<05:35,  1.45s/it]

[768/1000]
EN: Kaziranga opens additional safari routes for tourists.
BRX: काजीरंगाया दावबायारिफोरनि थाखाय दाजाबदेरनाय साफारि लामाफोर खुलिना होयो →
--------------------------------------------------

Translating:  77%|████████████████████▊      | 769/1000 [10:34<04:40,  1.21s/it]

[769/1000]
EN: Radisson Blu opens two hundred key property in Amritsar near Golden Temple.
BRX: रेडिसन ब्लुआ गल्डेन टेम्पलनि खाथियाव अमृतसरआव नैजौ गाहाय सम्पथि खुलिगोन |
--------------------------------------------------

Translating:  77%|████████████████████▊      | 770/1000 [10:35<04:15,  1.11s/it]

[770/1000]
EN: IHCL launches Ginger brand hotel in Siliguri for Dooars travellers.
BRX: आइ.एच.सि.एल.आ डुवार्स दावबायारिफोरनि थाखाय सिलीगुड़ीआव जिंजार ब्रान्ड हतेलखौ जागायजेनो →
--------------------------------------------------

Translating:  77%|████████████████████▊      | 771/1000 [10:35<03:35,  1.06it/s]

[771/1000]
EN: Hyatt Regency debuts in Dehradun with mountain view rooms.
BRX: हायेट रिजेंसीआ देहरादूनआव हाजोआरि नुथाय खथाफोरजों जागायजेनो.
--------------------------------------------------

Translating:  77%|████████████████████▊      | 772/1000 [10:36<03:39,  1.04it/s]

[772/1000]
EN: Taj Fort Aguada completes fifty years in Goa announces renovation.
BRX: गोवायाव ताज फर्ट आगुआडाया बाजि बोसोर आबुं खालामना फोसाबफिननायखौ फोसावदोंमोन |
--------------------------------------------------

Translating:  77%|████████████████████▊      | 773/1000 [10:37<03:30,  1.08it/s]

[773/1000]
EN: Novotel Visakhapatnam opens with three sixty degree sea view rooms.
BRX: नभोतेल विशाखापत्तनमआ मोनथाम दजि दिग्रि लैथो नुथाय खथाफोरजों खुलियो ꯫
--------------------------------------------------

Translating:  77%|████████████████████▉      | 774/1000 [10:39<04:15,  1.13s/it]

[774/1000]
EN: Roseate House Delhi appoints Kunal Kumar as new general manager.
BRX: 'आर.डि. ए. आइ. डि. सि. नि मावख 'गिरि आरो बि. जे. पि. एस.नि गाहाय मावखʼगिरि अनिल कुमारआ गावनि नख 'ारनि थाखाय गोदान सम सायख 'दों |
--------------------------------------------------

Translating:  78%|████████████████████▉      | 775/1000 [10:40<04:09,  1.11s/it]

[775/1000]
EN: ITC Hotels launches Mementoes brand with Jaipur property opening.
BRX: आई.टी.सी. हतेलफोरा जयपुरनि सम्पथि बेखेवनायजों लोगोसे मेमेन्टो ब्रान्डखौ जागायजेनो |
--------------------------------------------------

Translating:  78%|████████████████████▉      | 776/1000 [10:41<03:53,  1.04s/it]

[776/1000]
EN: Marriott Kathmandu opens Indian restaurant specializing in Awadhi cuisine.
BRX: मेरिअट काठमाण्डुआ अवधी संनाय-रोखोमाव जुनिया भारतारि रेस्टुरेन्ट खुलिगोन |
--------------------------------------------------

Translating:  78%|████████████████████▉      | 777/1000 [10:42<03:49,  1.03s/it]

[777/1000]
EN: Sarovar Hotels signs new property in Darjeeling with heritage status.
BRX: सरवर हतेलफोरा दार्जिलिंआव आजौसमफथि थामानजों गोदान सम्पथिनि सायाव नोजोर होयो |
--------------------------------------------------

Translating:  78%|█████████████████████      | 778/1000 [10:43<03:49,  1.03s/it]

[778/1000]
EN: The Park Kolkata celebrates seventy-fifth anniversary with heritage walks.
BRX: पार्क कलकाताया आजौसमफथि थाबायनायजों स्निजि-बाथि बोसोरारि फालिथायफोर फालिनाय जायो.
--------------------------------------------------

Translating:  78%|█████████████████████      | 779/1000 [10:44<03:37,  1.02it/s]

[779/1000]
EN: Ambassador Ajmera joins Indian Hotel Company board as independent director.
BRX: रायजोगिरिया इन्डियान हतेल कम्पानिनि बर्डआव उदां दिथागिरि महरै बाहागो लायो →
--------------------------------------------------

Translating:  78%|█████████████████████      | 780/1000 [10:44<03:20,  1.09it/s]

[780/1000]
EN: Chai Sutta Bar founder Anubhav Dubey opens tourist cafe in Udaipur.
BRX: चाय सुत्त बारनि गायसनगिरि अनुभव दुबेआ उदयपुराव दावबायारि केफे खुलिगोन |
--------------------------------------------------

Translating:  78%|█████████████████████      | 781/1000 [10:45<03:14,  1.12it/s]

[781/1000]
EN: Aman Resorts to launch first Indian property in Alwar district.
BRX: आमान रिसर्टसआ अलवर जिल्लायाव गिबिसिन भारतारि सम्पथि लन्च खालामनो थाखाय ।
--------------------------------------------------

Translating:  78%|█████████████████████      | 782/1000 [10:46<03:10,  1.14it/s]

[782/1000]
EN: Soneva Fushi Maldives introduces all-inclusive plan for Indian honeymooners.
BRX: सनीवा फुशी मालदीवआ भारतारि हनिमुन नायगिरिफोरनि थाखाय गासिबो लाफादेरनाय बिथांखि सिनायथि होयो |
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 783/1000 [10:47<03:06,  1.17it/s]

[783/1000]
EN: CII tourism committee chairman K.B. Kachru calls for single window clearance.
BRX: सीआईआई दावबायारि आफादनि आफादगिरिआ के.बी. कचरुआ मोनसेल'उइन्डो क्लियरेन्सनि थाखाय बुंफोरदों |
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 784/1000 [10:48<02:55,  1.23it/s]

[784/1000]
EN: Ladakh bans motorbike rallies to protect fragile Himalayan ecosystem.
BRX: लद्दाखआ लोरबां हिमालयारि सोरबिथिं खान्थिखौ रैखा खालामनो थाखाय मटरबाइक रेलीफोरखौ बन्द करे होयो.
--------------------------------------------------

Translating:  78%|█████████████████████▏     | 785/1000 [10:49<03:41,  1.03s/it]

[785/1000]
EN: Meghalaya introduces living root bridge trekking festival in November.
BRX: मेघालयआ नबेम्बराव जिउगोनां रोदा दालां ट्रेकिं फोरबोखौ जागायजेनो →
--------------------------------------------------

Translating:  79%|█████████████████████▏     | 786/1000 [10:50<03:16,  1.09it/s]

[786/1000]
EN: Spiti valley opens for tourists after six-month winter closure.
BRX: स्पिति हायेना द'दाननि गोजां बोथोरनि बन्दनि उनाव दावबायारिफोरनि थाखाय गेवनायसै.
--------------------------------------------------

Translating:  79%|█████████████████████▏     | 787/1000 [10:50<02:48,  1.27it/s]

[787/1000]
EN: Andaman administration permits night camping on Neil Island.
BRX: आन्दामान खुंथायआ नील दिपआव हर केम्पिंनि गनायथि होयो |
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 788/1000 [10:51<02:32,  1.39it/s]

[788/1000]
EN: Gujarat forest department opens Gir interpretation zone for lion safaris.
BRX: गुजरात अरन बिफानआ सिंह साफारिफोरनि थाखाय गिर बुंफुरलु ओनसोल खुलिगोन |
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 789/1000 [10:52<02:25,  1.46it/s]

[789/1000]
EN: Jim Corbett tiger reserve reports 1.75 lakh tourists in peak season.
BRX: जिम कर्बेट मोसा संरैखाथिलिया थि बोथोरनि समाव 1.75 लाख दावबायारिफोरनि फोरमायथि होयो |
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 790/1000 [10:52<02:29,  1.40it/s]

[790/1000]
EN: Periyar sanctuary introduces bamboo rafting in Thekkady lake.
BRX: पेरियार सेंक्सुयेरिया थेक्कडी बिलोआव औवानि राफ्टिंखौ सिनायथि होयो →
--------------------------------------------------

Translating:  79%|█████████████████████▎     | 791/1000 [10:53<02:28,  1.41it/s]

[791/1000]
EN: Sundarbans tourism restricted during tiger breeding season.
BRX: मोसा जोनोम होनायनि बोथोरनि समाव सुन्दरबन दावबायनाया हेंथा होजादोंमोनपेटियाव ।
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 792/1000 [10:54<02:24,  1.44it/s]

[792/1000]
EN: Ranthambore bans private vehicles inside core zone from December.
BRX: रनथम्बोरआ दिसेम्बरनिफ्राय कोर जननि सिङाव गावारि गारिफोरखौ होबथादों |
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 793/1000 [10:54<02:14,  1.54it/s]

[793/1000]
EN: Kerala tourism launches monsoon packages for Ayurveda treatments.
BRX: केराला दावबायथाया आयुर्बेद फाहामनायनि थाखाय मौसुमि पेकेजफोर जागायजेनो |
--------------------------------------------------

Translating:  79%|█████████████████████▍     | 794/1000 [10:55<02:12,  1.56it/s]

[794/1000]
EN: Kutch Rann Utsav extends tent city duration by forty-five days.
BRX: कच्छ रण उतसवआ तम्बु नोगोरनि समखौ ब्रैजि-बा सानसिम फेहेरदों |
--------------------------------------------------

Translating:  80%|█████████████████████▍     | 795/1000 [10:56<02:43,  1.25it/s]

[795/1000]
EN: Telangana government promotes Yadadri temple as integrated pilgrimage hub.
BRX: तेलेंगाना सोरखारा यादाद्री थानसालिखौ जथाय धोरोमदावबायारि मिरु महरै थुलुंगा होयोपाटानियाया यदाद्रि मन्दिरखौ जथाइ धोरोमारि दावबायग्रा थावनि महरै जौगाहोयो →
--------------------------------------------------

Translating:  80%|█████████████████████▍     | 796/1000 [10:57<02:30,  1.35it/s]

[796/1000]
EN: Mysore Dasara procession draws eight lakh visitors on Vijayadashami day.
BRX: विजयादशमीनि सानाव मैसूर दसारा हानजा सुरनाया दाइन लाख दावबायारिफोरखौ बोहोयो |
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 797/1000 [10:57<02:22,  1.42it/s]

[797/1000]
EN: Konark Sun Temple to get 3D projection mapping experience.
BRX: कनार्क सान थानसालिया 3डी प्रजेकसन म्यापिंनि रोंमोनदांथि मोनगोन |
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 798/1000 [10:59<02:57,  1.14it/s]

[798/1000]
EN: Elephanta Caves introduce Portuguese audio guide for visitors.
BRX: एलिफेन्टा दन्दरफोरा दावबायारिफोरनि थाखाय पर्तुगिस अडिय. गाइडखौ सिनायथि होयो →
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 799/1000 [10:59<03:01,  1.11it/s]

[799/1000]
EN: Golconda Fort light and sound show revamped in Telugu and English.
BRX: गलकोंडा खरंनि लाइट एन्ड साउन्ड श 'खौ तेलुगु आरो इंराजियाव गोदान महर होनाय जादों |
--------------------------------------------------

Translating:  80%|█████████████████████▌     | 800/1000 [11:00<02:41,  1.24it/s]

[800/1000]
EN: Five regional medical hubs to be set up to boost medical tourism in country
BRX: भारतआव देहा फाहामनाय दावबायनायखौ बांहोनो थाखाय गंबा ओनसोलारि सावस्रि मिरुफोर गायसन्नाय जादों
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 801/1000 [11:01<02:27,  1.35it/s]

[801/1000]
EN: Union Budget 2026 announces NIMHANS for north India
BRX: मिरुआरि बाजेट 2026 आ सा भारतनि थाखाय निमहान्सखौ फोसावनाय जादों
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 802/1000 [11:01<02:21,  1.40it/s]

[802/1000]
EN: Centre forms expert panel on healthcare for transgender persons
BRX: मिरुआ ट्रान्सजेन्डार सुबुंफोरनि थाखाय सावस्रि जोथोननि सायाव रोंग 'थि गोनां पैनल बानायदों
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 803/1000 [11:02<02:16,  1.45it/s]

[803/1000]
EN: Stem cell therapy cannot be offered as a clinical service for autism
BRX: स्टेम सेल थेरापीखौ अटिजमनि थाखाय क्लिनिकेल सिबिथाइ महरै होनो हाया |
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 804/1000 [11:03<02:17,  1.43it/s]

[804/1000]
EN: AI helps doctors spot breast cancer in scans
BRX: आर्टिफिसियेल इन्टेलिजेन्सआ देहा फाहामगिरिफोरखौ बिगुरनि केन्सारखौ संनायाव मदद खालामो →
--------------------------------------------------

Translating:  80%|█████████████████████▋     | 805/1000 [11:04<02:40,  1.21it/s]

[805/1000]
EN: Every family today knows someone with cancer and It is no longer a disease that happens to an ageing parent or relative
BRX: दिनै मोनफ्रोमबो नखरानो केन्सार गोनां सोरखौबा मिथियो आरो बेयो ओरैबायदि बेराम नङा जाय बैसोगोरा बिमा-माहा एबा सोमोन्दोआरिनाव जायो →
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 806/1000 [11:04<02:28,  1.31it/s]

[806/1000]
EN: Government imposes import curbs on three pharma ingredients for one year
BRX: बे बोसोरनि थाखाय पारमानबिक फार्मासिटीनि बाहायनायखौ होबथानायनि थांखि लानाय जादों
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 807/1000 [11:05<02:22,  1.35it/s]

[807/1000]
EN: Menstrual health in schools is integral to right to life, says the Supreme Court
BRX: फरायसालिफोराव दानारि सावस्रिआ जिउनि मोनथायनि गोनांथार बाथ्राफोर | सुप्रिम कर्टआ बुङो
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 808/1000 [11:06<02:18,  1.39it/s]

[808/1000]
EN: WHO sees low risk of Nipah virus spreading beyond India
BRX: डब्लिउ.एच.अ.आ भारतनि बायजोआव निपाह भायरास गोसारनायनि खैफोदखौ दिन्थियो
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 809/1000 [11:06<02:19,  1.37it/s]

[809/1000]
EN: Economic Survey calls for tackling rising digital addiction and screen-related mental health problems
BRX: रांखान्थियारि बिजिरसंनाया जौगाफुनाय डिजिटेल निसा आरो स्क्रिनजों सोमोन्दो थानाय मेलेमारि सावस्रि जेंनाफोरखौ होबथानो थाखाय बुंफोरदों
--------------------------------------------------

Translating:  81%|█████████████████████▊     | 810/1000 [11:07<02:17,  1.38it/s]

[810/1000]
EN: 188 million children and adolescents living with obesity worldwide
BRX: बुहुमनाङै 188 मिलियन खुदियाफोर आरो लायमोनफोरा लोदोबेरामजों जिउ खुंगासिनो दं |
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 811/1000 [11:08<02:11,  1.43it/s]

[811/1000]
EN: 60% of mental disorders found in patients below 35 years
BRX: 35 बोसोरनि गाहायाव थानाय बेरामिफोरनाव 60 जौखोन्दो मेलेमारि बेले-म बेजे मोननाय जादों ।
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 812/1000 [11:09<02:14,  1.40it/s]

[812/1000]
EN: Obesity impacts on brain may depend on how fat is distributed across body
BRX: मेलेमाव लोदोबेरामनि गोहोमफोरा गासै मोदोमाव मेजेमखौ माबोरै रानजायो बेनि सायाव सोनारनो हागौ ꯫
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 813/1000 [11:09<02:13,  1.40it/s]

[813/1000]
EN: Maharashtra, Karnataka, Tamil Nadu have highest number of vacancies under the NEET-PG 2025-26
BRX: कर्नाटकआव एन.ई.टी.-पि.जि. 2025-26 नि सिङाव बयनिख्रुइ बांसिन मासिफोर दं |
--------------------------------------------------

Translating:  81%|█████████████████████▉     | 814/1000 [11:10<02:09,  1.43it/s]

[814/1000]
EN: Only two Nipah virus disease cases reported in West Bengal since December 2025, says Health Ministry
BRX: सोनाब बंगआव दिसेम्बर 2025 मायथाइनिफ्राय खालि सानै निपाह भायरास बेरामनि केस मोननाय जादोंः सावस्रि मन्थ्रि आफाद
--------------------------------------------------

Translating:  82%|██████████████████████     | 815/1000 [11:11<02:10,  1.42it/s]

[815/1000]
EN: Health impacts due to plastics worldwide may double by 2040
BRX: प्लास्टिकनि जाहोनाव सावस्रियाव गोहोम गोग्लैनाया 2040 मायथाइसिमाव नैगुन जानो हागौ →
--------------------------------------------------

Translating:  82%|██████████████████████     | 816/1000 [11:11<02:08,  1.43it/s]

[816/1000]
EN: China halts sale of Sun Pharma drug used to treat dementia
BRX: चीनआ सनफार्मा मुलिखौ फान्नायखौ होबथायो जाय डिमेंशियानि फाहामनायाव बाहाय जायो |
--------------------------------------------------

Translating:  82%|██████████████████████     | 817/1000 [11:12<02:14,  1.36it/s]

[817/1000]
EN: T.N. govt. scheme improves access to diabetes, hypertension care for women as rural residents
BRX: कर्नाटकआ जुन्थिफोरनि जौगानायखौ बांहोयो & nbspi. यु. पि. ए. नि थाखाय गोदान राहाफोर दिहुनदों
--------------------------------------------------

Translating:  82%|██████████████████████     | 818/1000 [11:13<02:39,  1.14it/s]

[818/1000]
EN: Karnataka farmers urge Union Government to recommend to WHO to re-classify arecanut from ‘carcinogenic’ to ‘possibly carcinogenic to humans’
BRX: कर्नाटकनि आबादारिफोरा मिरु सोरखारा डब्लिउ.एच.अ.नो अरेकानटखौ 'कार्सिनजेनिक @ निफ्राय मानसिफोरनि थाखाय जानो हाथावना कार्सिनोजेनिकआव फिन थाखो रान्नो गनायथि होनो थाखाय नारसिनदों |
--------------------------------------------------

Translating:  82%|██████████████████████     | 819/1000 [11:14<02:39,  1.14it/s]

[819/1000]
EN: Study discovers stress-reducing role of natural molecule in body, may help with metabolic disorders
BRX: बिजिरसंनाया देहायाव मिथिंगायारि मॉलिक्युलनि नारसिननायखौ बाङाइ खालामनायनि बिफावखौ नागिरना दिहुनो आरो मेटाबलिक बेले-बेजेआव मदद होनो हागौ |
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 820/1000 [11:15<02:16,  1.31it/s]

[820/1000]
EN: Keeping your spine healthy with small, everyday changes
BRX: सानफ्रोमबोनि सोलायनायजों गावनि सिनस्रिखौ सावस्रिगोनां लाखिनो थाखाय ।
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 821/1000 [11:15<02:04,  1.43it/s]

[821/1000]
EN: What is behind the increasing number of heart attacks in pregnancy?
BRX: गोरबोआव थानाय समाव बिखानि गाग्लोबथिनि अनजिमा बांनायनि उनाव मा दं?
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 822/1000 [11:16<01:50,  1.61it/s]

[822/1000]
EN: Can India eliminate malaria by 2030?
BRX: भारतआ 2030 मायथाइसिम मेलेरियाखौ फोजोबनो हागोन नामा?
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 823/1000 [11:17<02:05,  1.41it/s]

[823/1000]
EN: Tamil Nadu government seeks IIT-M’s assistance to study ill effects of microplastics on human health
BRX: तामिलनाडु सोरखारा सुबुं सावस्रियाव माइक्रोप्लास्टिकनि गाज्रि गोहोमफोरखौ फरायसंनो थाखाय आइ.आइ.टि.-एम. नि मदद नागिरदों |
--------------------------------------------------

Translating:  82%|██████████████████████▏    | 824/1000 [11:18<02:15,  1.30it/s]

[824/1000]
EN: Goa seeks to grow as a wellness and medical tourism hub in India
BRX: गोवाया भारतआव मोनसे सावस्रि आरो मेडिकेल दावबायथाय मिरु महरै जौगानो नागिरगासिनो दं |
--------------------------------------------------

Translating:  82%|██████████████████████▎    | 825/1000 [11:19<02:35,  1.13it/s]

[825/1000]
EN: Borewell found contaminated, pipelines being probed as eight remain in hospital in Madhya Pradesh's Mhow
BRX: मध्य प्रदेशनि एम.एच.व.आव देहा फाहामगिरिफोर आरो नखरारि मावख'गिरिफोरनि गेजेराव मोगा-मोगि जानायनिफ्राय रैखा मोननो हानायखौ बांहोनाय जादों
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 826/1000 [11:20<02:32,  1.14it/s]

[826/1000]
EN: Uttar Pradesh youth amputates foot to seek disability quota in admission to medical college
BRX: उत्तर प्रदेशनि जौमोनफोरा मेडिकेल कलेजआव मुं थिसननायाव लोरबांथिनि कटाखौ नागिरना आथिंखौ दानस्लायदों |
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 827/1000 [11:20<02:29,  1.16it/s]

[827/1000]
EN: Police investigate software engineer’s death in Chennai lodge linked to bug repellent fumes
BRX: ऑस्ट्रेलियानि बि. एस. आइ. नि बिजिरसंनायनि उनाव भारतनि गाहाय मावख'गिरिफोरा गावस्रालांगासिनो दं ।
--------------------------------------------------

Translating:  83%|██████████████████████▎    | 828/1000 [11:21<02:32,  1.13it/s]

[828/1000]
EN: Regularly engaging in varied physical activities could extend lifespan
BRX: नेमबादि बायदि रोखोमनि देहायारि हाबाफोराव बाहागो लानायानो जिउ समखौ फेहेरनो हागौ |
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 829/1000 [11:23<02:47,  1.02it/s]

[829/1000]
EN: Study relates ADHD traits in childhood with physical health problems in mid-life
BRX: बिजिरसंनाया उन्दै समनि एडीएचडी आखुथाइफोरखौ गेजेर जिउनि देहायारि सावस्रि जेंनाफोरजों सोमोनदो होयो |
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 830/1000 [11:23<02:25,  1.17it/s]

[830/1000]
EN: U.S. completes withdrawal from World Health Organization
BRX: यु. एस.आ बुहुमनां सावस्रि आफादनिफ्राय बायजोआव ओंखारनायखौ फोजोबदों
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 831/1000 [11:24<02:16,  1.24it/s]

[831/1000]
EN: Punjab health scheme offers free hospital care worth ₹10 lakh to every family
BRX: पान्जाब सावस्रि बिथांखिया साफ्रोम नखरफोरनो ₹10 लाख बेसेननि बेसेन गैयै देहा फाहामसालि जोथोन जासियो |
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 832/1000 [11:25<02:13,  1.26it/s]

[832/1000]
EN: Snapchat launches new Family Center safety tools for teens and parents
BRX: स्नेपचेटआ लायमोनफोर आरो बिमा- बिफाफोरनि थाखाय गोदान फेमिलि सेन्टार सेफटि टुल्स दिहुनदों |
--------------------------------------------------

Translating:  83%|██████████████████████▍    | 833/1000 [11:25<02:11,  1.27it/s]

[833/1000]
EN: 167 drug samples flagged as ‘not of standard quality’ in December 2025
BRX: इं 2025 माइथायनि दिसेम्बर दानाव 167 मुलिनि नमुनाफोरखौ मानथाखो गोनां गुननि नङि महरै फ्लेग खालामनाय जादों
--------------------------------------------------

Translating:  83%|██████████████████████▌    | 834/1000 [11:26<02:05,  1.32it/s]

[834/1000]
EN: Tamil Nadu issues guidelines as chikungunya cases rise in State
BRX: तामिलनाडुआव सिकुनगुनियानि केसआ बांदों
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 835/1000 [11:27<02:03,  1.34it/s]

[835/1000]
EN: Researchers develop tool to simplify nutritional tracking of Indian meals
BRX: बिजिरसंगिरिफोरा भारतारि जामुंफोरनि निउत्रिसनेल ट्रेकिंखौ गोरलै खालामनो थाखाय आगजु दिहुनदों |
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 836/1000 [11:27<01:56,  1.41it/s]

[836/1000]
EN: Shingles vaccine may also slow down biological ageing in older adults
BRX: सिंगल्स टिकाया बैसोगोराफोरनाव जिबारि बैसो जानायखौ लासै खालामनो हागौ →
--------------------------------------------------

Translating:  84%|██████████████████████▌    | 837/1000 [11:29<03:01,  1.11s/it]

[837/1000]
EN: Gates and OpenAI team up for AI health push in African countries
BRX: भारत आरो आफ्रिकानि हादोरफोराव आर्टिफिसियेल इन्टेलिजेन्स (आइ.एफ.पि.ए. ) नि जौगानायखौ बांहोनाय जादों
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 838/1000 [11:30<02:40,  1.01it/s]

[838/1000]
EN: ASHA workers protest in Kolkata for ₹15,000 monthly honorarium
BRX: क.लकातायाव आशा मावगिरिफोरा 15,000 रां दानारि होनारियामनि थाखाय हेंथा दिन्थिदों →
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 839/1000 [11:31<02:28,  1.09it/s]

[839/1000]
EN: Bloodless heart surgery performed on patient with rare blood group at Kauvery Hospital
BRX: सावस्रियाव देहा फाहामनायनि सायाव नोजोर होनाय जादों
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 840/1000 [11:32<02:24,  1.11it/s]

[840/1000]
EN: Centre sanctions 50-bed AYUSH hospital for Tenali, says A.P. Minister
BRX: मिरुआ तेनालीनि थाखाय 50 बिसान गोनां आयुश देहाफामसालिखौ गनायथि होयो | A.P. मन्थ्रि
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 841/1000 [11:33<02:22,  1.12it/s]

[841/1000]
EN: NIMS Hyderabad opens Stem Cell Centre of Excellence as India battles rising burden of lifestyle diseases
BRX: हैदराबादनि एम्सआ स्टेम सेल सेन्टार अफ एक्सीलेन्सखौ खुलिदों मानोना भारतआ जिउ खांनायनि बेरामनि बारायनाय बोजाजों जुजिगासिनो दं |
--------------------------------------------------

Translating:  84%|██████████████████████▋    | 842/1000 [11:34<02:31,  1.04it/s]

[842/1000]
EN: The Ministry of Health and Family Welfare launched a nationwide campaign to improve early detection of non-communicable diseases in rural India.
BRX: सावस्रि आरो नखर वॆल्फेयार मनत्रिआ गामियारि भारतआव बारदेरग्रा नङि बेरामफोरखौ थाबनो सिनायनायखौ साबसिन खालामनो थाखाय मोनसे हादोरनाङै फोसावथाय जागायदोंमोनपाइ ।
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 843/1000 [11:35<02:20,  1.12it/s]

[843/1000]
EN: The Government of India announced an increase in funding for public hospitals under the National Health Mission.
BRX: भारत सोरखारा हायुंआरि सावस्रि मिशननि सिङाव सोरखारि देहा फाहामसालिफोरनि थाखाय रां होनायखौ बांहोनायखौ फोसावदोंमोनपाट्राङै ।
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 844/1000 [11:36<02:42,  1.04s/it]

[844/1000]
EN: Indian researchers developed a low-cost diagnostic kit to detect tuberculosis with higher accuracy.
BRX: भारतारि बिजिरसंगिरिफोरा बांसिन थारथिजों तिउबारकुलसिसखौ नागिरनो थाखाय मोनसे बाङाइ बेसेननि डायग्नोस्टिक किट जौगाहोदों ꯫
--------------------------------------------------

Translating:  84%|██████████████████████▊    | 845/1000 [11:37<02:29,  1.04it/s]

[845/1000]
EN: The Indian Council of Medical Research issued updated guidelines for the treatment of dengue fever.
BRX: इन्दियान काउन्सिल अफ मेडिकेल रिसार्चआ डेंगु लोमजानायनि सिकितसानि थाखाय गोदानसिन बिथोन होनायफोर हगारदोंमोन.
--------------------------------------------------

Translating:  85%|██████████████████████▊    | 846/1000 [11:37<02:21,  1.09it/s]

[846/1000]
EN: A new government medical college was inaugurated in Assam to strengthen healthcare education in the northeastern region.
BRX: सा-सानजायारि ओनसोलाव सावस्रि जोथोन सोलोंथायखौ गोख्रों खालामनो थाखाय आसामाव मोनसे गोदान सोरखारि मेडिकेल फरायसालिमा बेखेवनाय जादोंमोनपाइ ।
--------------------------------------------------

Translating:  85%|██████████████████████▊    | 847/1000 [11:38<02:12,  1.16it/s]

[847/1000]
EN: The Union Health Minister reviewed the progress of Ayushman Bharat services across multiple states.
BRX: मिरु सावस्रि मनथ्रिआ गोबां रायजोफोराव आयुश्मान भारत सिबिथाइफोरनि दावगानायखौ नायफिनदोंमोन |
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 848/1000 [11:39<02:06,  1.20it/s]

[848/1000]
EN: India reported a decline in maternal mortality rates due to improved institutional delivery services.
BRX: भारतआ साबसिन फसंथानारि देलिभारि सिबिथाइफोरनि जाहोनाव बिमायारि थैनायनि हारखौ बाङाइ खालामनायनि खौरां होदोंमोन |
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 849/1000 [11:40<02:01,  1.24it/s]

[849/1000]
EN: The Drug Controller General of India approved a new vaccine for preventing cervical cancer.
BRX: भारतनि ड्रग कन्ट्रलार जेनेरेलआ सर्वाइकल केन्सारखौ होबथानो थाखाय मोनसे गोदान टिकाखौ गनायथि होदोंमोन |
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 850/1000 [11:40<01:58,  1.26it/s]

[850/1000]
EN: Several state governments expanded free dialysis services in district hospitals.
BRX: गोबां रायजो सोरखारा जिल्ला देहा फाहामसालिफोराव बेसेन गैयै डायलिसिस सिबिथाइफोरखौ फुवारदोंमोनपाटों ।
--------------------------------------------------

Translating:  85%|██████████████████████▉    | 851/1000 [11:41<01:56,  1.28it/s]

[851/1000]
EN: The World Health Organization praised India’s efforts in polio eradication during a regional health summit.
BRX: बुहुमनां सावस्रि आफादआ ओनसोलारि सावस्रि जथुममानि समाव पलिअ फोजोबस्रांनायाव भारतनि नाजानायफोरखौ बाख्नायदोंमोन |
--------------------------------------------------

Translating:  85%|███████████████████████    | 852/1000 [11:42<01:56,  1.27it/s]

[852/1000]
EN: A public health survey revealed improved vaccination coverage among children in urban slum areas.
BRX: मोनसे रायजोआरि सावस्रि जरिबआ सोहोरारि स्लम ओनसोलफोराव गथ-2फोरनि गेजेराव साबसिन टिका थुजानायनि फोरमायथि होदोंमोन |
--------------------------------------------------

Translating:  85%|███████████████████████    | 853/1000 [11:43<02:04,  1.18it/s]

[853/1000]
EN: The Ministry of AYUSH promoted traditional medicine research through newly funded clinical studies.
BRX: आयुश मनत्रिआ गोदानै रां होनाय क्लिनिकेल फरायसंनायनि गेजेरजों दोरोङारि मुलि बिजिरसंनायखौ जौगाहोदोंमोन |
--------------------------------------------------

Translating:  85%|███████████████████████    | 854/1000 [11:44<02:15,  1.08it/s]

[854/1000]
EN: Indian hospitals adopted artificial intelligence tools to assist doctors in early cancer detection.
BRX: भारतारि देहा फाहामसालिफोरा आगु केन्सार सिनायनायाव डक्टरफोरखौ हेफाजाब होनो थाखाय आर्टिफिसियेल इन्टेलिजेन्स आगजुफोरखौ नाजावदोंमोन.
--------------------------------------------------

Translating:  86%|███████████████████████    | 855/1000 [11:45<02:10,  1.11it/s]

[855/1000]
EN: The National Medical Commission introduced revised norms for undergraduate medical education.
BRX: हायुंआरि सावस्रियारि आयजेंआ उनमोनथायारि सावथ्रियारि सोलोंथाइनि थाखाय फोसाबनाय नेमखान्थिफोरखौ जागायदोंमोन.
--------------------------------------------------

Translating:  86%|███████████████████████    | 856/1000 [11:46<02:03,  1.17it/s]

[856/1000]
EN: A shortage of specialist doctors was reported in government hospitals across rural districts.
BRX: गामियारि जिल्लाफोराव सोरखारि देहा फाहामसालिफोराव रोंग 'थिगोनां देहा फाहामगिरिफोरनि आंखालखौ फोरमायदोंमोनपाइ ।
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 857/1000 [11:47<02:04,  1.15it/s]

[857/1000]
EN: The central government launched a digital health ID system to streamline patient medical records.
BRX: मिरु सोरखारा बेरामि सावस्रि रेबगान्थिफोरखौ गोख्रों खालामनो थाखाय मोनसे डिजिटेल सावस्रि आई.डी. खान्थि जागायदोंमोन/जेन्नायखिजाखांथिफोर ।
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 858/1000 [11:47<01:57,  1.21it/s]

[858/1000]
EN: India’s pharmaceutical exports increased due to rising global demand for generic medicines.
BRX: जेनेरिक मुलिफोरनि थाखाय बुहुमनां गोनांथिया बांनायनि जाहोनाव भारतनि मुलियारि दैथायहरनाया बांदों ꯫
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 859/1000 [11:49<02:19,  1.01it/s]

[859/1000]
EN: The Supreme Court of India directed states to improve healthcare infrastructure in tribal areas.
BRX: भारतनि गोजौसिन बिजिरसालिनि बिथोनआ रायजोफोरखौ थागिबि ओनसोलफोराव सावस्रि जोथोन बिथायारि सानजथाइखौ साबसिन खालामनो थाखाय बिथोन होदोंमोनपाटान्थिया गाहाय मन्थ्रि आफादफोर ।
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 860/1000 [11:50<02:12,  1.05it/s]

[860/1000]
EN: A government report highlighted gaps in mental health services in public healthcare facilities.
BRX: मोनसे सोरखारि रिपर्टआ रायजोआरि सावस्रि जोथोन खाबुफोराव मेलेमारि सावस्रि सिबिथाइफोरनि फारागथिफोरखौ नोजोर होदोंमोन |
--------------------------------------------------

Translating:  86%|███████████████████████▏   | 861/1000 [11:50<02:07,  1.09it/s]

[861/1000]
EN: Several private hospitals partnered with state governments to offer affordable cardiac care.
BRX: गोबां सोरखारि नङि देहा फाहामसालिफोरा बेसेनगोसा बिखानि जोथोन होनो थाखाय रायजो सोरकारफोरजों बाहागो लादोंमोन |
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 862/1000 [11:51<02:03,  1.11it/s]

[862/1000]
EN: The Indian Institute of Public Health conducted a study on air pollution-related respiratory diseases.
BRX: इन्डियान इनस्टीट्युट अफ पाब्लिक हेल्थआ बार गाज्रि जानायजों सोमोन्दो थानाय हां लानाय बेरामनि सायाव मोनसे बिजिरसंनाय खुंदोंमोन |
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 863/1000 [11:52<02:03,  1.11it/s]

[863/1000]
EN: Health officials initiated a special drive to control the spread of seasonal influenza.
BRX: सावस्रि मावख.गिरिफ्रा बोथोरारि इनफ्लुयेनजानि गोसारनायखौ दबथायनो थाखाय मोनसे जुनिया हाबाफारि जागायदोंमोनपाइ ।
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 864/1000 [11:54<02:41,  1.19s/it]

[864/1000]
EN: The Ministry of Health strengthened surveillance systems to monitor emerging infectious diseases.
BRX: सावस्रि मनत्रिआ जौगाबोनाय बारदेरग्रा बेरामफोरखौ नोजोर होनो थाखाय नायसंनाय खान्थिखौ गोख्रों खालामदोंमोन/जेन्नायखिजादोआ रैखाथि मन्थ्रि आफादनो बिथोन होदोंमोन |
--------------------------------------------------

Translating:  86%|███████████████████████▎   | 865/1000 [11:55<02:24,  1.07s/it]

[865/1000]
EN: India recorded a steady rise in organ donation registrations through national awareness campaigns.
BRX: भारतआ हायुंआरि सांग्रांथि हाबाफारिफोरनि गेजेरजों अंग दान रेबथुमनायाव मोनसे दिदोमै बांनाय रेबगान्थि खालामदोंमोनपाटिनो ।
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 866/1000 [11:56<02:36,  1.17s/it]

[866/1000]
EN: A new telemedicine platform was introduced to improve access to healthcare in remote villages.
BRX: गोजाननि गामिफोराव सावस्रि जोथोननि खाबुखौ साबसिन खालामनो थाखाय मोनसे गोदान टेलीमेडिसिन प्लेटफर्म सिनायथि होजादोंमोन ꯫
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 867/1000 [11:57<02:18,  1.04s/it]

[867/1000]
EN: The National AIDS Control Organisation reported a decline in new HIV infections.
BRX: हादोरारि एड्स दबथायनाय आफादआ गोदान एइस.आइ.भि. सनदेरनायाव बाङाइ जानायनि फोरमायथि होदोंमोन |
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 868/1000 [11:58<02:07,  1.03it/s]

[868/1000]
EN: Government hospitals increased the availability of free essential medicines for outpatients.
BRX: सोरखारि देहा फाहामसालिफोरा बायजोआरि बेरामिफोरनि थाखाय बेसेन गैयै गोनांथार मुलिफोर मोन्नो हानाय गोहोखौ बांहोदोंमोन.
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 869/1000 [11:59<02:17,  1.05s/it]

[869/1000]
EN: A policy review emphasized the need for more nursing staff in public healthcare institutions.
BRX: मोनसे खान्थि बिजिरसंनाया रायजोआरि सावस्रि जोथोन फसंथानफोराव बांसिन नार्सिं मावगिरिनि गोनांथिनि सायाव गोसो होदोंमोनङ्गाबाखि.
--------------------------------------------------

Translating:  87%|███████████████████████▍   | 870/1000 [12:00<01:59,  1.08it/s]

[870/1000]
EN: The Indian government signed a health cooperation agreement with a neighboring country.
BRX: भारत सोरखारा नसुंसेनि हादोरजों सावस्रि हेफाजाबनि रादायाव मुंसाइ होदोंमोनपाइ ।
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 871/1000 [12:01<02:18,  1.07s/it]

[871/1000]
EN: Researchers from an Indian medical institute published findings on antibiotic resistance trends.
BRX: मोनसे भारतारि सावस्रि फसंथाननि बिजिरसंगिरिफोरा एन्टीबाय @ टिक होबथाग्रा आखुथायफोरनि सायाव बिजिरसंनायफोरखौ फोसावदोंमोन |
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 872/1000 [12:02<02:18,  1.09s/it]

[872/1000]
EN: The Health Ministry issued advisories to states following a rise in heat-related illnesses.
BRX: सावस्रि मनत्रिआ बिदुंजों सोमोन्दो थानाय बेरामफोरनि बांनायनि उनाव रायजोफोरनो बोसोनफोर हगारदोंमोन.
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 873/1000 [12:03<02:19,  1.10s/it]

[873/1000]
EN: India expanded its emergency ambulance network to improve response times in rural regions.
BRX: भारतआ गामियारि ओनसोलफोराव फिनजाथाय समखौ साबसिन खालामनो थाखाय गावनि खैफोद गोनां एम्बुलेन्स नेटवर्कखौ फेहेरदोंमोनपाटोंमोनङ्गाङै ।
--------------------------------------------------

Translating:  87%|███████████████████████▌   | 874/1000 [12:04<01:59,  1.05it/s]

[874/1000]
EN: The National Digital Health Mission aimed to improve transparency in healthcare service delivery.
BRX: हादोरारि डिजिटेल सावस्रि मिशननि थांखिया सावस्रि जोथोन सिबिथाइ दैथायनायाव रोखाथिखौ जौगाहोनाय |
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 875/1000 [12:05<02:05,  1.01s/it]

[875/1000]
EN: A public-private partnership model was introduced to upgrade district-level hospitals.
BRX: जिल्ला थाखोनि देहा फाहामसालिफोरखौ जौगा होनो थाखाय मोनसे सोरखारि-राजखानथियारि बाहागोआरि मदेल सिनायथि होनाय जादोंमोनपाइ ।
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 876/1000 [12:06<02:18,  1.12s/it]

[876/1000]
EN: The government launched a mental health helpline to support individuals during medical emergencies.
BRX: सोरखारा सावस्रियारि हरखाब थासारिफोरनि समाव सुबुंफोरखौ हेफाजाब होनो थाखाय मोनसे मेलेमारि सावस्रि हेल्प लाइन जागायदोंमोन.
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 877/1000 [12:07<02:08,  1.05s/it]

[877/1000]
EN: India’s medical tourism sector showed growth due to affordable treatment options.
BRX: भारतनि सावस्रियारि दावबायथाय सेक्टरआ बेसेनगोसा फाहामनायनि राहाफोरनि थाखाय जौगानाय दिन्थिदोंमोन.
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 878/1000 [12:08<01:58,  1.03it/s]

[878/1000]
EN: A parliamentary committee reviewed the implementation of healthcare schemes in backward districts.
BRX: मोनसे संसदारि कमितिआ उनफिनजानाय जिल्लाफोराव सावस्रि जोथोन बिथांखिफोरनि बाहायनायखौ नायबिजिरदोंमोन.
--------------------------------------------------

Translating:  88%|███████████████████████▋   | 879/1000 [12:09<01:49,  1.10it/s]

[879/1000]
EN: The Ministry of Health emphasized preventive healthcare during a national policy meeting.
BRX: सावस्रि मनत्रिआ मोनसे हायुंआरि पलिसि मिटिंनि समाव होबथाग्रा सावस्रि जोथोननि सायाव गोसो होदोंमोन |
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 880/1000 [12:10<01:48,  1.10it/s]

[880/1000]
EN: Indian scientists developed a wearable device to monitor heart health in elderly patients.
BRX: भारतारि बिगियानगिरिफोरा बैसोगोरा बेरामिफोरनि बिखानि सावस्रिखौ नोजोर होनो थाखाय मोनसे गान्नो हानाय आगजु जौगाहोदों ꯫
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 881/1000 [12:11<01:49,  1.09it/s]

[881/1000]
EN: A national survey assessed nutritional deficiencies among children under five years of age.
BRX: मोनसे हायुंआरि सारभेआ बा बोसोर बैसोनि गाहायाव थानाय खुदियाफोरनि गेजेराव नीउथ्रिसनेल आंखालफोरखौ बिजिरदोंमोन.
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 882/1000 [12:11<01:38,  1.20it/s]

[882/1000]
EN: The government increased insurance coverage limits under Ayushman Bharat for critical illnesses.
BRX: सोरखारा गोब्राब लोमजानायफोरनि थाखाय आयुश्मान भारतनि सिङाव बीमा कभारेज सिमाफोरखौ बांहोदोंमोन.
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 883/1000 [12:13<02:07,  1.09s/it]

[883/1000]
EN: Health authorities conducted vaccination drives to prevent outbreaks of measles and rubella.
BRX: सावस्रि खुंथाइफोरा सिथर बेरनाय आरो रुबेलानि गोसारनायखौ होबथानो थाखाय टिका थुग्रा हाबाफारिफोर खुंदोंमोन |
--------------------------------------------------

Translating:  88%|███████████████████████▊   | 884/1000 [12:14<02:01,  1.04s/it]

[884/1000]
EN: India strengthened laboratory capacity to improve disease surveillance and diagnosis.
BRX: भारतआ बेराम नायसंनाय आरो बेराम सिनायनायखौ साबसिन खालामनो थाखाय आनजादसालि गोहोखौ गोख्रों खालामदोंमोनपाटों ।
--------------------------------------------------

Translating:  88%|███████████████████████▉   | 885/1000 [12:15<01:50,  1.04it/s]

[885/1000]
EN: A state health department launched mobile clinics to serve remote tribal communities.
BRX: मोनसे रायजोनि सावस्रि बिफानआ गोजान-गुबुन थागिबि हारिफोरनो सिबिथाइ होनो थाखाय जानबुं क्लिनिकफोर जागायदोंमोन.
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 886/1000 [12:16<01:44,  1.10it/s]

[886/1000]
EN: The National Health Authority upgraded its data systems to enhance patient safety.
BRX: हायुंआरि सावस्रि आफादआ बेरामि रैखाथिखौ बांहोनो थाखाय गावनि खारि बिखान्थिखौ जौगा होदोंमोन |
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 887/1000 [12:17<01:52,  1.01it/s]

[887/1000]
EN: Indian doctors highlighted the need for early screening of lifestyle-related diseases.
BRX: भारतारि देहा फाहामगिरिफोरा जिउ खांनाय-लायनायजों सोमोन्दो थानाय बेरामफोरखौ थाबै स्क्रिनिं खालामनायनि गोनांथिखौ मुंख 'दोंमोन |
--------------------------------------------------

Translating:  89%|███████████████████████▉   | 888/1000 [12:17<01:41,  1.10it/s]

[888/1000]
EN: The Ministry of Health released new guidelines for hospital waste management.
BRX: सावस्रि मनत्रिआ देहा फाहामसालिनि गारनाय मुवा सामलायनायनि थाखाय गोदान बिथोनफोरखौ फोसावदोंमोन.
--------------------------------------------------

Translating:  89%|████████████████████████   | 889/1000 [12:18<01:45,  1.05it/s]

[889/1000]
EN: Several states reported improvements in primary healthcare access through wellness centers.
BRX: गोबां रायजोफोरा सावस्रि मिरुफोरनि गेजेरजों गुदि सावस्रि जोथोन मोननायाव जौगानायखौ फोरमायदोंमोनपाटों ।
--------------------------------------------------

Translating:  89%|████████████████████████   | 890/1000 [12:19<01:36,  1.14it/s]

[890/1000]
EN: India’s public health expenditure showed a gradual increase in the latest budget.
BRX: भारतनि रायजोआरि सावस्रि खरसाया बावैसोनि बाजेटआव लासै-लासै बांनाय दिन्थिदों →
--------------------------------------------------

Translating:  89%|████████████████████████   | 891/1000 [12:20<01:32,  1.18it/s]

[891/1000]
EN: A new online portal was launched to track the availability of hospital beds.
BRX: देहाफामसालि एमफोरनि मोन्नो हानायखौ ट्रेक खालामनो थाखाय मोनसे गोदान अनलाइन पर्टेल जागायजेननाय जादोंमोन.
--------------------------------------------------

Translating:  89%|████████████████████████   | 892/1000 [12:21<01:30,  1.19it/s]

[892/1000]
EN: Health experts in India raised concerns about rising cases of diabetes among young adults.
BRX: भारतनि सावस्रि रोंगसाफोरा लाइमोन बैसोगोराफोरनि गेजेराव डायबेटिसनि बांलांनाय जाथायफोरनि बागै जिंगा दिन्थिदों ꯫
--------------------------------------------------

Translating:  89%|████████████████████████   | 893/1000 [12:22<01:39,  1.08it/s]

[893/1000]
EN: The government initiated training programs to improve emergency care skills among paramedics.
BRX: सोरखारा पैरामेडिक्सनि गेजेराव हरखाब जोथोन रोंग 'थिखौ साबसिन खालामनो थाखाय फोरोंनाय हाबाफारिफोर जागायदोंमोन.
--------------------------------------------------

Translating:  89%|████████████████████████▏  | 894/1000 [12:23<01:30,  1.17it/s]

[894/1000]
EN: Indian pharmaceutical companies invested in research for affordable cancer medicines.
BRX: भारतारि मुलियारि कम्पानिफोरा बेसेनगोसा केन्सार मुलिफोरनि थाखाय बिजिरसंनायाव रां खाथायदोंमोन.
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 895/1000 [12:24<01:58,  1.13s/it]

[895/1000]
EN: A national task force was formed to address antimicrobial resistance.
BRX: एन्टिमाइक्रोबियल रेजिस्टेन्सखौ होबथानो थाखाय मोनसे हायुंआरि टास्क फोर्स दानाय जादोंमोनपाइरोबायल होबथाग्रा गोहोखौ नोजोर होनानै थांखि लानाय जादोंमोन.
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 896/1000 [12:25<01:49,  1.05s/it]

[896/1000]
EN: The Health Ministry conducted audits to improve quality standards in government hospitals.
BRX: सावस्रि मनत्रिआ सोरखारि देहा फाहामसालिफोराव गुन गोनां मानथाखोखौ साबसिन खालामनो थाखाय अडिट खालामदोंमोनङ्गाबा ।
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 897/1000 [12:26<01:42,  1.00it/s]

[897/1000]
EN: India expanded maternal nutrition programs to reduce anemia among pregnant women.
BRX: भारतआ गोरबोआव थानाय आयजोफोरनि गेजेराव एनीमियाखौ बाङाइ खालामनो थाखाय बिमायारि निउत्रिसन हाबाफारिफोरखौ फेहेरदोंमोन |
--------------------------------------------------

Translating:  90%|████████████████████████▏  | 898/1000 [12:27<01:39,  1.02it/s]

[898/1000]
EN: A state government announced free health checkups for senior citizens.
BRX: मोनसे रायजो सोरखारा बैसोगोरा नोगोरारिफोरनि थाखाय बेसेन गैयै सावस्रि नायसंनायखौ फोसावनायसै →
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 899/1000 [12:28<01:37,  1.03it/s]

[899/1000]
EN: Indian healthcare startups focused on digital solutions for chronic disease management.
BRX: भारतारि सावस्रि जोथोन स्तार्टआपफोरा गोब्राब बेराम सामलायनायनि थाखाय डिजिटेल राहाफोरनि सायाव नोजोर होदोंमोन |
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 900/1000 [12:29<01:31,  1.09it/s]

[900/1000]
EN: The National Health Policy emphasized universal access to affordable healthcare services.
BRX: हायुंआरि सावस्रि खान्थिया बेसेनगोसा सावस्रि जोथोन सिबिथाइफोरनि थाखाय मुलुगनाङै मोनहैनायनि सायाव गोसो होदोंमोन |
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 901/1000 [12:30<01:52,  1.14s/it]

[901/1000]
EN: Public health officials promoted lifestyle changes to reduce cardiovascular disease risks.
BRX: राइजोआरि सावस्रि मावख.गिरिफ्रा कार्डिय 'वास्कुलार बेरामनि खैफोदखौ बाङाइ खालामनो थाखाय जिउ खुंनाय आदब सोलायनायखौ थुलुंगा होदोंमोनपाटान्थिफोर ।
--------------------------------------------------

Translating:  90%|████████████████████████▎  | 902/1000 [12:32<01:50,  1.13s/it]

[902/1000]
EN: India improved cold chain infrastructure to ensure vaccine safety and effectiveness.
BRX: भारतआ टिका रैखाथि आरो गोहोमखोखलैनायखौ रोखा खालामनो थाखाय कल्ड चेन बिथायारि सानजथाइखौ जौगाहोदोंमोनपाटोंमोन/जेन्नायखिजायामानो ।
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 903/1000 [12:33<01:50,  1.14s/it]

[903/1000]
EN: A medical research institute in India studied long-term effects of COVID-19 infections.
BRX: भारतनि मोनसे सावस्रियारि बिजिरसं फसंथानआ क.भिड-19 सनदेरनायनि गोलाव समनि गोहोमफोरखौ फरायसंदोंमोन |
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 904/1000 [12:33<01:34,  1.02it/s]

[904/1000]
EN: The government strengthened referral systems between primary and tertiary healthcare centers.
BRX: सोरखारा गुदि आरो थामथि सावस्रि जोथोन मिरुफोरनि गेजेराव रेफारेल खान्थिखौ गोख्रों खालामफिनदोंमोन.
--------------------------------------------------

Translating:  90%|████████████████████████▍  | 905/1000 [12:34<01:35,  1.00s/it]

[905/1000]
EN: Health workers received additional training to improve immunization coverage.
BRX: सावस्रि मावगिरिफोरा इमिउनायजेसन कभारेजखौ साबसिन खालामनो थाखाय दाजाबदेरनाय फोरोंथायखौ मोन्नो हादोंमोन.
--------------------------------------------------

Translating:  91%|████████████████████████▍  | 906/1000 [12:35<01:22,  1.14it/s]

[906/1000]
EN: India expanded newborn care units to reduce infant mortality rates.
BRX: भारतआ खुदिया थैनायनि हारखौ बाङाइ खालामनो थाखाय जोनोम जागोदान जोथोन खोन्दोफोरखौ फुवारदोंमोन |
--------------------------------------------------

Translating:  91%|████████████████████████▍  | 907/1000 [12:36<01:34,  1.02s/it]

[907/1000]
EN: The Ministry of Health collaborated with states to improve sanitation and hygiene practices.
BRX: सावस्रि मनत्रिआ साखोन-सिखियानि आरो सावस्रियारि आदबफोरखौ साबसिन खालामनो थाखाय रायजोफोरजों हेफाजाब होजाबोदों मुकाबले खालामनाय जादों |
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 908/1000 [12:37<01:22,  1.11it/s]

[908/1000]
EN: Indian hospitals increased investment in critical care facilities.
BRX: भारतारि देहा फाहामसालिफोरा गोनांथार जोथोन खाबुफोराव रां थिसननायखौ बांहोदोंमोन.
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 909/1000 [12:38<01:23,  1.10it/s]

[909/1000]
EN: A health awareness campaign encouraged working professionals to undergo regular health screenings.
BRX: मोनसे सावस्रि सांग्रांथि फोसावनाया खामानि मावग्रा जिउराहायारिफोरखौ नेमबादि सावस्रि स्क्रिनिंनि गेजेरजों थांनो थाखाय थुलुंगा होदोंमोन |
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 910/1000 [12:39<01:20,  1.12it/s]

[910/1000]
EN: The government introduced reforms to regulate private healthcare pricing.
BRX: सोरखारा गावारि सावस्रि जोथोन बेसेनफोरखौ सामलायनो थाखाय फोसाबनायफोर जागायदोंमोन/जेन्नायफोर |
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 911/1000 [12:40<01:24,  1.05it/s]

[911/1000]
EN: India enhanced its disease reporting systems to improve outbreak preparedness.
BRX: भारतआ गोसारनायनि थियारिखौ साबसिन खालामनो थाखाय गावनि बेरामनि रिपर्टिं आदबफोरखौ बांहोदोंमोनपाटोंमोनपाइ ।
--------------------------------------------------

Translating:  91%|████████████████████████▌  | 912/1000 [12:41<01:19,  1.10it/s]

[912/1000]
EN: Health experts recommended increased funding for mental health research in India.
BRX: सावस्रि रोंग 'साफोरा भारतआव मेलेमारि सावस्रि बिजिरसंनायनि थाखाय रां होनायखौ बांहोनो बोसोन होदोंमोन |
--------------------------------------------------

Translating:  91%|████████████████████████▋  | 913/1000 [12:42<01:18,  1.10it/s]

[913/1000]
EN: The National Health Authority reviewed feedback to improve beneficiary services.
BRX: हादोरारि सावस्रि आफादआ मुलामफा मोनग्रानि मावमिनफोरखौ साबसिन खालामनो थाखाय फिडबेकखौ नायफिनदोंमोनपाट खालामनायसै.
--------------------------------------------------

Translating:  91%|████████████████████████▋  | 914/1000 [12:42<01:16,  1.13it/s]

[914/1000]
EN: India strengthened disaster preparedness in hospitals for medical emergencies.
BRX: भारतआ सावस्रियारि हरखाब थासारिफोरनि थाखाय देहा फाहामसालिफोराव खैफोदनि थाखाय थियारि जानायखौ गोख्रों खालामदोंमोनपाटों ।
--------------------------------------------------

Translating:  92%|████████████████████████▋  | 915/1000 [12:43<01:12,  1.17it/s]

[915/1000]
EN: A state government launched a nutrition program for school children.
BRX: मोनसे रायजो सोरखारा फरायसालिनि गथ-2फोरनि थाखाय मोनसे नीउथ्रिसन हाबाफारि जागायदोंमोन.
--------------------------------------------------

Translating:  92%|████████████████████████▋  | 916/1000 [12:44<01:14,  1.13it/s]

[916/1000]
EN: The Health Ministry emphasized community participation in strengthening public healthcare systems.
BRX: सावस्रि मनत्रिआ रायजोआरि सावस्रि जोथोन बिखान्थिखौ गोख्रों खालामनायाव हारिफोरनि बाहागो लानायनि सायाव गोसो होदोंमोनपाटों ।
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 917/1000 [12:45<01:14,  1.12it/s]

[917/1000]
EN: The Union Budget 2026 increased the healthcare allocation to 1,06,530 crore rupees for the Ministry of Health and Family Welfare.
BRX: मिरुआरि बाजेट 2026 आ सावस्रि आरो नखर वॆल्फेयार मिनिस्ट्रियानि थाखाय सावस्रि जोथोन राननायखौ 1,06,530 कौटि रांसिम बांहोदोंमोन.
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 918/1000 [12:46<01:10,  1.17it/s]

[918/1000]
EN: Finance Minister Nirmala Sitharaman announced a 10 percent hike in the health budget compared to the previous fiscal year.
BRX: रांखान्थियारि मन्थ्रि निर्मला सितारमना थांनाय रांखान्थियारि बोसोरनि रुजुनायाव सावस्रि रांबावजायाव 10 जौखोन्दो बारायनायनि फोसावनाय जादोंमोन.
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 919/1000 [12:46<01:04,  1.25it/s]

[919/1000]
EN: The Government of India launched the Biopharma SHAKTI initiative with an outlay of 10,000 crore rupees over five years.
BRX: भारत सोरखारा बा बोसोराव 10,000 कौटि रांनि रां बाहायनायजों बायोफार्मा शक्ति बिथांखि जागायदोंमोन |
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 920/1000 [12:48<01:27,  1.09s/it]

[920/1000]
EN: The Biopharma SHAKTI scheme aims to strengthen the domestic production of biologics and biosimilars in India.
BRX: बायोफार्मा शक्ति स्किमनि थांखिया भारतआव जिब बिगियान आरो बाय.सिमिलारनि नखरारि दिहुनथायखौ गोख्रों खालामनाय |
--------------------------------------------------

Translating:  92%|████████████████████████▊  | 921/1000 [12:49<01:28,  1.12s/it]

[921/1000]
EN: The Ministry of Health will support states in establishing five new regional medical hubs through private-sector partnerships.
BRX: सावस्रि मनत्रिआ सोरखारि नङि - सेक्टर बाहागोआरिनि गेजेरजों मोनबा गोदान ओनसोलारि मेडिकेल हब गायसननायाव रायजोफोरखौ हेफाजाब होगोन.
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 922/1000 [12:50<01:23,  1.08s/it]

[922/1000]
EN: These five regional medical hubs will combine medical services, educational facilities, and research centers under one roof.
BRX: बे मोनबा ओनसोलारि सावस्रि मिरुफोरा मोनसे उखुमनि सिङाव सावस्रि सिबिथाइफोर. सोलोंथायारि खाबुफोर आरो बिजिरसं मिरुफोरखौ जथायगोन |
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 923/1000 [12:51<01:15,  1.02it/s]

[923/1000]
EN: The Union Budget 2026 proposed the establishment of NIMHANS 2.0 in North India to address mental health needs.
BRX: मिरुआरि बाजेट 2026 आ मेलेमारि सावस्रि गोनांथिफोरखौ आबुं खालामनो थाखाय सा भारतआव निमहान्स 2.0 गायसन्नायनि थांखि लादोंमोन |
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 924/1000 [12:52<01:11,  1.07it/s]

[924/1000]
EN: The Government plans to upgrade the National Mental Health Institutes in Ranchi and Tezpur into regional apex institutions.
BRX: सोरकारा राँची आरो तेज़पुरनि हायुंआरि मेलेम सावस्रि फसंथानफोरखौ ओनसोलारि जौसिन फसंथानफोराव जौगा होनो सानथांखि बानायदों |
--------------------------------------------------

Translating:  92%|████████████████████████▉  | 925/1000 [12:53<01:06,  1.13it/s]

[925/1000]
EN: The Ministry of Health allocated 3,477 crore rupees to the National AIDS and STD Control Programme.
BRX: सावस्रि मनत्रिआ हादोरारि एड्स आरो एसटीडी दबथायनाय हाबाफारिनि थाखाय 3,477 कौटि रां दानस्लायदों |
--------------------------------------------------

Translating:  93%|█████████████████████████  | 926/1000 [12:54<01:02,  1.17it/s]

[926/1000]
EN: The Union Budget 2026 provided a full customs duty exemption on 17 essential cancer-related drugs.
BRX: मिरुआरि बाजेट 2026 आ केन्सारजों सोमोन्दो थानाय मोन 17 गोनांथार मुलिफोरनि सायाव आबुं कास्टम खाजोना एंगारनाय होदोंमोन |
--------------------------------------------------

Translating:  93%|█████████████████████████  | 927/1000 [12:55<01:18,  1.07s/it]

[927/1000]
EN: Seven additional rare diseases were added to the list for easier personal import of life-saving medicines.
BRX: जिउ रैखा खालामग्रा मुलिफोरखौ गोरलैयै गावारि दैथाइहरनायनि थाखाय फारिलाइयाव मोनस्नि दाजाबदेरनाय मोननो थाङै बेरामफोरखौ सोफादेरनाय जादोंमोनपाइ ।
--------------------------------------------------

Translating:  93%|█████████████████████████  | 928/1000 [12:56<01:11,  1.01it/s]

[928/1000]
EN: The Government announced a 50 percent expansion in emergency and trauma care capacity at district hospitals.
BRX: सोरखारा जिल्ला देहा फाहामसालिफोराव हरखाब गोनांथि आरो ट्रमा जोथोन गोहोखौ 50 जौखोन्दो फेहेरनायनि फोसावनाय जादोंमोन |
--------------------------------------------------

Translating:  93%|█████████████████████████  | 929/1000 [12:57<01:05,  1.09it/s]

[929/1000]
EN: The Ministry of Health intends to establish dedicated emergency and trauma care centers in every district hospital.
BRX: सावस्रि मनत्रिआ मोनफ्रोमबो जिल्ला देहा फाहामसालियाव बावनाय हरखाब गोनांथि आरो ट्रमा जोथोन मिरुफोर गायसन्नो सानदों |
--------------------------------------------------

Translating:  93%|█████████████████████████  | 930/1000 [12:57<01:00,  1.15it/s]

[930/1000]
EN: The Pradhan Mantri Jan Arogya Yojana received an increased allocation of 9,500 crore rupees to expand coverage.
BRX: गाहाय मन्थ्रि जन आरोग्य योजनाया कभारेजखौ फेहेरनो थाखाय 9,500 कौटि रांनि बारायनाय रां थिसनदोंमोन.
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 931/1000 [12:58<00:57,  1.20it/s]

[931/1000]
EN: The National Health Mission was allocated 39,390 crore rupees to enhance primary healthcare delivery across states.
BRX: हादोरारि सावस्रि मिशना रायजोफोराव गुदि सावस्रि जोथोन दैथायनायखौ बांहोनो थाखाय 39,390 कौटि रां दानस्लायदोंमोन |
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 932/1000 [12:59<00:52,  1.30it/s]

[932/1000]
EN: The Government proposed a plan to add 100,000 allied health professionals over the next five years.
BRX: सोरखारा फैगौ बा बोसोराव 100,000 लोगोआरि सावस्रि रोंग 'साफोरखौ दाजाबदेरनो मोनसे बिथांखि थांखि लादोंमोन |
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 933/1000 [13:00<01:02,  1.08it/s]

[933/1000]
EN: The Ministry of Health will upgrade existing institutions for allied health professionals to improve training standards.
BRX: सावस्रि मनत्रिआ फोरोंथायनि मानथाखोखौ साबसिन खालामनो थाखाय सोमोन्दो गोनां सावस्रि जिउराहायारिफोरनि थाखाय सोलिबाय थानाय फसंथानफोरखौ जौगाहोगोन ꯫
--------------------------------------------------

Translating:  93%|█████████████████████████▏ | 934/1000 [13:01<00:57,  1.16it/s]

[934/1000]
EN: The Union Budget 2026 earmarked 4,821 crore rupees specifically for the Department of Health Research.
BRX: मिरुआरि बावजादा 2026 मायथाइयाव गुबैयै सावस्रि बिजिरसं बिफाननि थाखाय 4,821 कौटि रां थि खालामनाय जादों |
--------------------------------------------------

Translating:  94%|█████████████████████████▏ | 935/1000 [13:02<00:55,  1.17it/s]

[935/1000]
EN: Finance Minister Nirmala Sitharaman proposed the creation of three new All India Institutes of Ayurveda.
BRX: रांखान्थियारि मन्थ्रि निर्मला सितारमना मोनथाम गोदान गासै भारतारि आयुर्बेद फसंथानफोर गायसन्नायनि थांखि लादोंमोन.
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 936/1000 [13:03<00:58,  1.09it/s]

[936/1000]
EN: The Government plans to train 1.5 lakh caregivers in allied skills such as geriatric care and yoga.
BRX: सोरखारा 1.50 लाख जोथोन होग्राफोरखौ जेरियाट्रिक जोथोन आरो योग बायदि सोमोनदो गोनां रोंगʼथिफोराव फोरोंनो सानथांखि खालामदों |
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 937/1000 [13:04<01:07,  1.07s/it]

[937/1000]
EN: The Ayushman Bharat Digital Mission received 350 crore rupees to improve digital health record interoperability.
BRX: आयुश्मान भारत डिजिटेल मिशना डिजिटेल सावस्रि रेबगान्थि गावजों गाव खामानि मावनो हानाय गोहोखौ साबसिन खालामनो थाखाय 350 कौटि रां मोन्नो हादोंमोन.
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 938/1000 [13:05<01:06,  1.08s/it]

[938/1000]
EN: The Ministry of Health aims to reduce import dependence by supporting the domestic manufacturing of high-value biopharmaceuticals.
BRX: सावस्रि मन्थ्रि बिफाननि थांखिया गोजौ बेसेननि बायोफार्मास्युटिकल्सनि नखरारि दिहुनथायखौ हेफाजाब होनानै दैथाइहरनायनि सोनारनायखौ बाङाइ खालामनाय |
--------------------------------------------------

Translating:  94%|█████████████████████████▎ | 939/1000 [13:06<01:07,  1.10s/it]

[939/1000]
EN: The Union Budget 2026 focus shifted from a curative model to a prevention-first and holistic wellness approach.
BRX: जुथाइ रांबावजा 2026नि नोजोरआ मोनसे फाहामनाय मदेलनिफ्राय होबथाग्रा-फस्र्थ आरो आबुं सावस्रि राहा फारसे सोलायदोंमोन.
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 940/1000 [13:08<01:16,  1.27s/it]

[940/1000]
EN: The Government will establish 1,000 accredited clinical trial sites to position India as a global research destination.
BRX: सरकारा भारतखौ मोनसे बुहुमनां बिजिरसं थांखि थावनि महरै गायसननो थाखाय 1,000 गनायथि होजानाय क्लिनिकेल ट्राइल साइटफोर गायसन्नो हागोन →
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 941/1000 [13:10<01:29,  1.52s/it]

[941/1000]
EN: The Central Drugs Standard Control Organisation will receive more specialized personnel to improve regulatory efficiency.
BRX: सेन्ट्रेल ड्रग्स स्टान्डार्ड कन्ट्रल अर्गानाइजेशना रेगुलेटरि आखा-फाखांथिखौ साबसिन खालामनो थाखाय बांसिन जुनिया सुबुं मोनगोन |
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 942/1000 [13:12<01:36,  1.66s/it]

[942/1000]
EN: Artificial Intelligence is now being used by Indian radiologists to detect early signs of lung cancer from medical images.
BRX: आर्टिफिसियेल इन्टेलिजेन्सखौ दा भारतारि रेडिय 'लजिस्टफोरा सावस्रियारि सावगारिफोरनिफ्राय संफ्लनि केन्सारनि आगु नेरसोनफोरखौ नागिरना नायनो थाखाय बाहायगासिनो दं।
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 943/1000 [13:14<01:43,  1.81s/it]

[943/1000]
EN: Qure.ai implemented AI-driven imaging solutions to facilitate faster diagnosis of strokes in rural Indian hospitals.
BRX: क्यूरे.एआइआ गामियारि भारतारि देहा फाहामसालिफोराव स्त्रकफोरनि गोख्रै बेराम सिनायनायखौ गोरलै खालामनो थाखाय ए.आइ.-द्रायनाय इमेजिं सल्युसनफोरखौ बाहायदोंमोन/2018 खालि बेनि सायाव बिथा खालामै बिजिरसंनाय आरो बाहायनायखौ साबसिन खालामनायनि थांखि लादोंमोन @
--------------------------------------------------

Translating:  94%|█████████████████████████▍ | 944/1000 [13:16<01:33,  1.66s/it]

[944/1000]
EN: Indian healthcare providers are adopting "Actionable AI" to provide predictive health roadmaps instead of simple lab reports.
BRX: भारतारि सावस्रि जोथोन होग्राफोरा सरासनस्रा लेब रिपर्टफोरनि बदलै इयुन खिन्थानाय सावस्रि रडमेपफोर होनो थाखाय "एकशनेबल ए.आइ. खौ आजावगासिनो दं |
--------------------------------------------------

Translating:  94%|█████████████████████████▌ | 945/1000 [13:17<01:22,  1.50s/it]

[945/1000]
EN: The use of wearables in India is evolving from basic fitness tracking to clinical-grade monitoring of heart rhythm.
BRX: भारताव गान्नाय मुवाफोरनि बाहायनाया गुदि फिटनेस ट्रेकिंनिफ्राय बिखानि तालनि क्लिनिकेल-ग्रेड मनिटरिंसिम जौगाबोगासिनो दं |
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 946/1000 [13:18<01:22,  1.52s/it]

[946/1000]
EN: Medical technology startups in India are developing microfluidic devices that conduct complex tests on a single drop of blood.
BRX: भारताव सावस्रियारि बिरोंदामिन स्तार्टआपफोरा माइक्रofluidic आगजुफोर जौगाहोगासिनो दं जाय थैनि मोनसे थरथिंआव जेथो गोनां आनजाद खालामो.
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 947/1000 [13:19<01:10,  1.34s/it]

[947/1000]
EN: The Indian MedTech sector is projected to reach a market value of 50 billion dollars by the end of 2026.
BRX: भारतारि मेडटेक सेक्टरखौ 2026 मायथाइनि जोबनायसिम 50 बिलियन डलारनि हाथाइ बेसेन सौहैनो मिजिं थिनाय जादों |
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 948/1000 [13:20<01:07,  1.30s/it]

[948/1000]
EN: Hospitals in Tier 2 cities are using predictive analytics to optimize patient flow and reduce waiting times.
BRX: टियर 2 नोगोरफोराव देहा फाहामसालिफोरा बेरामिफोरनि बोहैनायखौ साबसिन खालामनो आरो नेनायनि समखौ बाङाइ खालामनो थाखाय प्रेडिक्टिव एनालिटिक्स बाहायगासिनो दंपाटिया जादों |
--------------------------------------------------

Translating:  95%|█████████████████████████▌ | 949/1000 [13:21<01:01,  1.20s/it]

[949/1000]
EN: Telemedicine services are expanding in remote regions to connect rural patients with specialists in metropolitan cities.
BRX: टेलिमेडिसिन सिबिथाइफोरा गामियारि बेरामिफोरखौ नोगोरमाफोराव रोंग 'थिगोनांफोरजों फोनांजाबनो थाखाय गोजान ओनसोलफोराव गोसारगासिनो दं |
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 950/1000 [13:23<01:00,  1.21s/it]

[950/1000]
EN: The Ayushman Bharat Health Account (ABHA) system allows patients to share digital health records securely with doctors.
BRX: आयुश्मान भारत सावस्रि सानरिखिआ (ए.बी.एच. ए. @ खान्थिया बेरामिफोरखौ देहा फाहामगिरिफोरजों रैखाथिगोनाङै डिजिटेल सावस्रि रेबगान्थिफोरखौ रानलायनो गनायथि होयो |
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 951/1000 [13:24<01:03,  1.29s/it]

[951/1000]
EN: Robotic-assisted surgery is becoming more common in private Indian hospitals for complex urological procedures.
BRX: गोब्राब युरोलोजिकेल खान्थिफोरनि थाखाय सोरखारि नङि भारतारि देहा फाहामसालिफोराव रब @ ट-सिस्टेड सार्जारिआ बांसिन सरासनस्रा जागासिनो दं |
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 952/1000 [13:25<01:01,  1.29s/it]

[952/1000]
EN: Many Indian diagnostic labs are now using genomic testing as a primary triage tool for chronic diseases.
BRX: गोबां भारतारि बेराम सिनायनाय आनजादसालिफोरा दा गोजाम बेरामनि थाखाय मोनसे गुदि ट्राइएज आगजु महरै जेनोमिक आनजाद नायनायखौ बाहायगासिनो दं اطلاعاتफोर ।
--------------------------------------------------

Translating:  95%|█████████████████████████▋ | 953/1000 [13:28<01:13,  1.56s/it]

[953/1000]
EN: Healthcare organizations are deploying AI agents to handle administrative tasks like insurance pre-authorizations and billing.
BRX: सावस्रि जोथोन फसंथानफोरा बीमा आगु-अथोराइजेसन आरो बिलिं बायदि खुंथायारि हाबाफोरखौ सामलायनो थाखाय ए.आइ. एजेन्टफोरखौ थिसनगासिनो दं 3/2/1/9/3/6/4/7/8/5/2: इनफरमेसन आरो हेल्थकेयारजों सोमोन्दो गोनां आयदाफोर ।
--------------------------------------------------

Translating:  95%|█████████████████████████▊ | 954/1000 [13:30<01:23,  1.82s/it]

[954/1000]
EN: Smart sensors in Indian ICUs are reducing unplanned admissions by providing continuous real-time monitoring of vitals.
BRX: भारतारि आइ.सि.यु.फोराव स्मार्ट सेन्सरा गोनांथारफोरनि सोलिबाय थानाय रियेल-टाइम मनिटरिं होनानै सानथांखि गैयालासे मुं थिसननायखौ बाङाइ खालामगासिनो दंपाटान्थिफोर |
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 955/1000 [13:31<01:07,  1.50s/it]

[955/1000]
EN: The digital transformation of clinical trials in India is enabling remote patient monitoring through mobile devices.
BRX: भारताव क्लिनिकेल आनजादफोरनि डिजिटेल सोलायनाया जानबुं आगजुफोरनि गेजेरजों गोजान बेरामि नायसंनायखौ जाफुंसार खालामगासिनो दं.
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 956/1000 [13:32<01:07,  1.53s/it]

[956/1000]
EN: Indian pharmaceutical companies are integrating AI into their quality control systems to ensure paperless and compliant workflows.
BRX: भारतारि मुलियारि कम्पानिफोरा लेखा बिलाइ गैयै आरो मानिजानाय खामानि बोहैनायखौ रोखा खालामनो थाखाय गावसोरनि गुन दबथायनाय खान्थियाव आर्टिफिसियेल इन्टेलिजेन्सखौ सरजाबगासिनो दंपाटों नङा.
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 957/1000 [13:34<01:03,  1.47s/it]

[957/1000]
EN: Low-cost needle-free drug delivery technologies are gaining traction for vaccine administration in pediatric clinics.
BRX: खम बेसेननि बिजि-फ्री मुलि दैथायनाय बिरोंदामिनफोरा खुदिया क्लिनिकफोराव टिका सामलायनायनि थाखाय गोसो बोनो हादोंपाटोंफोर ।
--------------------------------------------------

Translating:  96%|█████████████████████████▊ | 958/1000 [13:35<01:00,  1.45s/it]

[958/1000]
EN: Public health experts launched India's first Public Health Monitor to track real-time health outcomes across states.
BRX: राइजोआरि सावस्रि रोंग 'साफोरा रायजोफोराव रिएल-टाइम सावस्रि फिथायफोरखौ ट्रेक खालामनो थाखाय भारतनि गिबिसिन पाब्लिक हेल्थ मनिटरखौ जुरिजेनदों |
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 959/1000 [13:37<01:11,  1.74s/it]

[959/1000]
EN: Specialized medical tourism facilitation centers will be integrated into the new regional medical hubs.
BRX: जुनिया मेडिकेल टुरिजम खाबु मिरुफोरखौ गोदान ओनसोलारि मेडिकेल हबफोराव सरजाबनाय जागोनपाटें ।
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 960/1000 [13:39<01:03,  1.59s/it]

[960/1000]
EN: Indian doctors are using hyper-personalized medicine to tailor treatments based on the genetic profile of individual patients.
BRX: भारतारि देहा फाहामगिरिफोरा गावारि बेरामिफोरनि जेनेटिक प्रफाइलनि सायाव बिथा खालामनानै फाहामनो थाखाय हाइपार-पर्सनलाइज्ड मुलि बाहायगासिनो दं اطلاعاتफोर ।
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 961/1000 [13:40<00:57,  1.46s/it]

[961/1000]
EN: The adoption of 5G technology is improving the speed and reliability of remote robotic surgeries in India.
BRX: 5G बिरोंदामिनखौ नाजावनाया भारताव रिमट रब @ टिक सार्जारिनि गोख्रैथि आरो फोथायजाथावथिखौ जौगाहोगासिनो दंपाटों नङा.
--------------------------------------------------

Translating:  96%|█████████████████████████▉ | 962/1000 [13:41<00:49,  1.30s/it]

[962/1000]
EN: 20 All India Institutes of Medical Sciences signed a memorandum to form a pan-India research consortium.
BRX: 20 अल इन्डिया इनस्टीट्युट अफ मेडिकेल साइन्सेसआ मोनसे गासै - भारतनि बिजिरसं आफाद बानायनो थाखाय मोनसे बिसावरियाव मुंसाइ होदोंमोन |
--------------------------------------------------

Translating:  96%|██████████████████████████ | 963/1000 [13:42<00:43,  1.16s/it]

[963/1000]
EN: The AIIMS research consortium will focus on multicentric clinical trials for low-cost cancer treatments.
BRX: एम्स बिजिरसं आफादआ खम बेसेननि केन्सार फाहामनायनि थाखाय गोबां मिरुआरि क्लिनिकेल आनजाद नायनायाव गोसो होगोन.
--------------------------------------------------

Translating:  96%|██████████████████████████ | 964/1000 [13:43<00:41,  1.15s/it]

[964/1000]
EN: A medical student at the Dharwad Institute of Mental Health unfortunately committed suicide in early February.
BRX: धारवाड़ इनस्टिट्यूट अफ मेंटल हेल्थनि सासे मेडिकेल फरायसाया खाफालाङै फेब्रुआरिनि जागायजेन्नायाव गावखौ बुथारदोंमोन.
--------------------------------------------------

Translating:  96%|██████████████████████████ | 965/1000 [13:44<00:38,  1.10s/it]

[965/1000]
EN: The Maharashtra University of Health Sciences revoked the affiliation of Sinhgad Dental College over regulatory violations.
BRX: महाराष्ट्र मुलुगसोलोंसालि अफ हेल्थ साइन्सेसआ नेमखान्थिफोरखौ सिफायनायनि थाखाय सिंहगढ़ डेन्टेल फरायसालिमानि गनायथिखौ बोखारदोंमोन.
--------------------------------------------------

Translating:  97%|██████████████████████████ | 966/1000 [13:45<00:39,  1.16s/it]

[966/1000]
EN: A 40-year-old urologist suffered a cardiac arrest while speaking at an international conference in Indore.
BRX: इन्दौरआव मोनसे हादोरगेजेरारि जथुमनायाव रायज्लायनायाव सासे 40 बोसोर बैसोनि युरलोजिस्टआ कार्डिएक अरेस्टजों मोगा-मोगि जादोंमोनपाटों ।
--------------------------------------------------

Translating:  97%|██████████████████████████ | 967/1000 [13:46<00:36,  1.11s/it]

[967/1000]
EN: The District Consumer Commission in Kannur held a surgeon liable for negligence in a varicose vein treatment.
BRX: कन्नूरआव जिल्ला बायग्रा आयजेंआ सासे सर्जनखौ वैरिक 'ज शिरानि फाहामनायाव नेवसिजानायनि थाखाय दाय गोनां होनना मानिनायसै.
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 968/1000 [13:47<00:37,  1.18s/it]

[968/1000]
EN: Two government doctors in Bhopal were sentenced to prison for securing medical seats with fake domicile certificates.
BRX: भुपालाव सानै सोरखारि देहा फाहामगिरिफोरखौ मोखथाङारि थाग्रा खुलिनि फोरमान बिलाइजों सावस्रियारि मासिफोर मोननो थाखाय जेलनि साजा होनाय जादोंमोनपाइ ।
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 969/1000 [13:50<00:50,  1.62s/it]

[969/1000]
EN: Authorities in Maharashtra are seeking action against a pathologist for signing lab reports without proper registration.
BRX: महाराष्ट्रआव खुंथाइगिरिफोरा थि रेबथुमनाय गैयालासे लेब रिपर्टफोराव मुंसाइ दाननायनि थाखाय सासे पेथोलोजिस्तनि बेरेखायै हाबाफारि नागिरगासिनो दं ꯫
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 970/1000 [13:51<00:45,  1.51s/it]

[970/1000]
EN: The Central Council for Research in Ayurvedic Sciences signed an agreement to digitize rare Ayurveda manuscripts.
BRX: आयुर्वेदिक बिगियानफोराव बिजिरसंनायनि मिरु आफादआ आगोमा आयुर्वेद रेबसनलाइफोरखौ डिजिटाइज खालामनो थाखाय मोनसे रादायाव मुंसाइ होदोंमोनपाइ ।
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 971/1000 [13:53<00:44,  1.54s/it]

[971/1000]
EN: Apollo Hospitals Chairman Dr. Prathap Reddy stated that the 2026 budget strengthens the vision of a healthier India.
BRX: अपोलो देहा फाहामसालिफोरनि आफादगिरि डा. प्रताप रेड्डीआ बुंदोंमोन दि 2026 मायथाइनि बावजादा मोनसे सावस्रिगोनां भारतनि नोजोरखौ गोख्रों खालामोपाटिनो ।
--------------------------------------------------

Translating:  97%|██████████████████████████▏| 972/1000 [13:54<00:38,  1.39s/it]

[972/1000]
EN: Max Healthcare plans to expand its robotic-assisted surgery program across its network of hospitals.
BRX: मेक्स हेल्थकेयारआ गावनि देहा फाहामसालिफोरनि नेटवार्कआव रब @ टिक-सिस्टेड सार्जारि हाबाफारिखौ फेहेरनो सानथांखि बानायदों |
--------------------------------------------------

Translating:  97%|██████████████████████████▎| 973/1000 [13:55<00:36,  1.35s/it]

[973/1000]
EN: Health experts warned that the unorganized diagnostic sector in India will face consolidation due to stricter quality norms.
BRX: सावस्रि रोंग 'साफोरा सामोल होदोंमोन दि भारतआव आफाद नङि बेराम सिनायनाय सेक्टरआ गोब्राब गुननि नेमखान्थिफोरनि थाखाय गोख्रोंथिजों मोगा-मोगि जागोनपाटों ।
--------------------------------------------------

Translating:  97%|██████████████████████████▎| 974/1000 [13:56<00:30,  1.16s/it]

[974/1000]
EN: The Indian Council of Medical Research received 4,000 crore rupees to bolster indigenous medical research.
BRX: इन्डियान काउन्सिल अफ मेडिकेल रिसार्चआ थागिबि सावस्रि बिजिरसंनायखौ गोख्रों खालामनो थाखाय 4,000 कौटि रां मोन्नो हादोंमोन.
--------------------------------------------------

Translating:  98%|██████████████████████████▎| 975/1000 [13:57<00:27,  1.10s/it]

[975/1000]
EN: Public health officials are drafting a new Planetary Health Policy Framework to address climate-linked diseases.
BRX: राइजोआरि सावस्रि मावखʼगिरिफोरा बोथोरजों सोमोन्दो थानाय बेरामफोरखौ होबथानो थाखाय मोनसे गोदान ग्रहारि सावस्रि खान्थि फ्रेमवर्कनि ड्राफ्ट बानायगासिनो दंपाटोंमोनपाइ ।
--------------------------------------------------

Translating:  98%|██████████████████████████▎| 976/1000 [13:58<00:27,  1.13s/it]

[976/1000]
EN: The Food Safety and Standards Authority of India is working to make healthy food more affordable than unhealthy options.
BRX: भारतनि जाग्रा आदार रैखाथि आरो मानथाखो आफादआ सावस्रिगोनां आदारखौ गाज्रि राहाफोरनि रुजुनायाव बांसिन बेसेनगोसा खालामनो थाखाय खामानि मावगासिनो दंपाटिया जादों.
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 977/1000 [13:59<00:26,  1.14s/it]

[977/1000]
EN: Researchers at AIIMS Delhi are investigating the use of AI to reduce hospital-acquired infections.
BRX: एम्स दिल्लीनि बिजिरसंगिरिफोरा देहा फाहामसालि- आरजिनाय सनदेरनायफोरखौ बाङाइ खालामनो थाखाय आर्टिफिसियेल इन्टेलिजेन्सनि बाहायनायखौ नायबिजिरगासिनो दंपाटों ।
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 978/1000 [14:00<00:23,  1.05s/it]

[978/1000]
EN: The National AIDS Control Organisation is upgrading blood transfusion services to ensure nationwide safety and availability.
BRX: हायुंआरि एड्स दबथायनाय आफादआ हादोरनाङै रैखाथि आरो मोनथावनाखौ रोखा खालामनो थाखाय थै सोलायनाय सिबिथाइफोरखौ जौगा होगासिनो दंपाटान्थिफोर ।
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 979/1000 [14:01<00:21,  1.04s/it]

[979/1000]
EN: Indian pediatricians noted a rise in parental awareness regarding neurodivergence and behavioral health issues.
BRX: भारतारि खुदिया फाहामगिरिफोरा निउरोडाइभार्जेन्स आरो आखुयारि सावस्रि जेंनाफोरनि सोमोनदै बिमा-बायारिनि सांग्रांथिखौ बांहोनायखौ मुंख 'दोंमोन |
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 980/1000 [14:02<00:20,  1.02s/it]

[980/1000]
EN: Medical value tourism in India is expected to grow as the government streamlines visa processes for international patients.
BRX: भारतआव सावस्रियारि बेसेन दावबायनाया बारायनायनि मिजिं दं मानोना सोरखारा गेजेर हायुंआरि बेरामिफोरनि थाखाय भिसा बिखान्थिफोरखौ गोख्रों खालामो वाळां खालामो.
--------------------------------------------------

Translating:  98%|██████████████████████████▍| 981/1000 [14:03<00:21,  1.11s/it]

[981/1000]
EN: The WHO Global Traditional Medicine Centre in Jamnagar is being upgraded to improve evidence-based research.
BRX: फोरमान-थायारि बिजिरसंनायखौ साबसिन खालामनो थाखाय जामनगरआव डब्लिउ.एच.अ. ग्लबेल ट्रेडिशनल मेडिसिन सेन्टारखौ जौगा होनाय जागासिनो दं |
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 982/1000 [14:04<00:19,  1.08s/it]

[982/1000]
EN: Indian generic manufacturers are preparing for the patent expiry of several major global obesity medications.
BRX: भारतारि जेनेरिक दिहुनगिरिफोरा गोबां गाहाय बुहुमनां लोदोबेराम मुलिफोरनि पेटेन्ट जोबनायनि थाखाय थियारि जागासिनो दं.
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 983/1000 [14:05<00:18,  1.07s/it]

[983/1000]
EN: A new digital curriculum was introduced to train public health leaders in epidemiology and modern technology.
BRX: महामारी बिगियान आरो गोदान मुगानि बिरोंदामिनआव राइजोआरि सावस्रि दैदेनगिरिफोरखौ फोरोंनो थाखाय मोनसे गोदान डिजिटेल फरायफारि सिनायथि होजादोंमोनपाटों ।
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 984/1000 [14:07<00:18,  1.17s/it]

[984/1000]
EN: The government is upgrading AYUSH pharmacies to ensure higher quality standards for traditional medicines.
BRX: सरकारा दोरोङारि मुलिफोरनि थाखाय गोजौ गुननि मानथाखोखौ रोखा खालामनो थाखाय आयुश फार्मेसीफोरखौ जौगा होगासिनो दंपाटोंरिङै खालामनाय जादों.
--------------------------------------------------

Translating:  98%|██████████████████████████▌| 985/1000 [14:08<00:15,  1.04s/it]

[985/1000]
EN: Several district hospitals in Uttar Pradesh are now equipped with 24/7 emergency care and trauma units.
BRX: उत्तर प्रदेशनि गोबां जिल्ला देहा फाहामसालिफोरा दा 24/7 हरखाब जोथोन आरो ट्रमा इउनिटफोरजों साजायजानाय |
--------------------------------------------------

Translating:  99%|██████████████████████████▌| 986/1000 [14:09<00:14,  1.03s/it]

[986/1000]
EN: Private healthcare providers are increasing investments in Tier 3 cities to capture the growing rural market.
BRX: गावारि सावस्रि जोथोन होग्राफोरा जौगाबोनाय गामियारि हाथाइखौ हमनो थाखाय टियर 3 सोहोरफोराव रां थिसननायखौ बारायगासिनो दं |
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 987/1000 [14:10<00:13,  1.05s/it]

[987/1000]
EN: The Indian healthcare workforce is being upskilled through new digital certifications in allied health disciplines.
BRX: भारतारि सावस्रि जोथोन मावग्राफोरखौ सोमोन्दो गोनां सावस्रि आयदाफोराव गोदान डिजिटेल फोरमानथिनि गेजेरजों आखा-फाखा खालामनाय जागासिनो दंपाटों ।
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 988/1000 [14:11<00:12,  1.08s/it]

[988/1000]
EN: Public health summits in 2026 emphasized the importance of data-driven decision-making for epidemic prevention.
BRX: 2026 मायथाइयाव रायजोआरि सावस्रि जथुममाफोरा महामारी होबथानायनि थाखाय खारि- सालायजानाय थिरांथा लानायनि गोनांथिनि सायाव गोसो होदोंमोन |
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 989/1000 [14:12<00:11,  1.01s/it]

[989/1000]
EN: Hospitals in Mumbai are reporting a shift toward integrated care models for chronic lifestyle diseases.
BRX: मुम्बाइनि देहा फाहामसालिफोरा गोब्राब जिउ खुंनाय बेरामनि थाखाय इन्टिग्रेटेड केयार मडेलनि फारसे सोलायनायखौ फोरमायगासिनो दं |
--------------------------------------------------

Translating:  99%|██████████████████████████▋| 990/1000 [14:13<00:10,  1.00s/it]

[990/1000]
EN: The Ministry of Health is focusing on improving the nurse-to-patient ratio in public hospitals through new recruitment drives.
BRX: सावस्रि मनत्रिआ गोदान थिसनथाय सालायनायनि गेजेरजों सोरखारि देहा फाहामसालिफोराव नार्स-निफ्राय-पेसिडेन्ट रुजुथायखौ जौगाहोनायाव गोसो होगासिनो दंपाटों ।
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 991/1000 [14:14<00:09,  1.08s/it]

[991/1000]
EN: India is positioning itself as a global hub for the manufacturing of affordable biologics and specialized therapies.
BRX: भारतआ गावखौ बेसेनगोसा जिब बिगियान आरो जुनिया थेरापिफोर बानायनायनि थाखाय मोनसे बुहुमनां मिरु महरै गायसनगासिनो दं |
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 992/1000 [14:15<00:08,  1.02s/it]

[992/1000]
EN: PGIMER doctors achieve major breakthrough in deadly Celphos poisoning
BRX: पि.जि.आइ.एम.आर.नि देहा फाहामगिरिफोरा जिउगोनां सेलफ 'सनि बिसआव गिदिर जाफुंसारनाय मोन्नो हादों |
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 993/1000 [14:16<00:06,  1.08it/s]

[993/1000]
EN: What a 12-hour work day can do to your metabolic, mental and reproductive health
BRX: सानसे खालि 12 घन्टानि हाबाया नोंथांनि मेटाबलिक आरो मेलेमारि आरो जोनोम होनो हानाय सावस्रिखौ मा खालामनो हागोन ؟
--------------------------------------------------

Translating:  99%|██████████████████████████▊| 994/1000 [14:16<00:04,  1.21it/s]

[994/1000]
EN: Healthcare services disrupted as doctors across states protest Kolkata colleague’s rape-murder
BRX: कोलकातानि देहा फाहामगिरिफोरा गावनि मददगिरिफोरखौ बुथारनायखौ नेवसिगारो
--------------------------------------------------

Translating: 100%|██████████████████████████▊| 995/1000 [14:17<00:03,  1.29it/s]

[995/1000]
EN: Manmohan Singh unveils multi-crore healthcare plan for paramilitary forces
BRX: म 'हन सिंहआ पारामिलिटारि रौनियाफोरनि थाखाय गोबां कौटि रांनि सावस्रि जोथोन बिथांखि फोसावदों |
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 996/1000 [14:18<00:03,  1.20it/s]

[996/1000]
EN: US Senate Hearing Explodes After Senator Questions Indian Origin Doctor on Men’s Pregnancy
BRX: यु. एस. सेनेटनि बिसावरायनाया भारतारि गुदि डक्टरखौ हौवाफोरनि गोरबोआव थानायनि सायाव सोंनाय उसुखुथुफोरखौ फेहेरदों |
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 997/1000 [14:19<00:02,  1.21it/s]

[997/1000]
EN: Dr. D N gupta addresses the lack of awareness surrounding Vitamin D deficiency.
BRX: ड. डी. एन. गुप्ताया भिटामिन डीनि आंखालजों सोमोन्दो थानाय सांग्रांथिनि आंखालखौ फोरमायो |
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 998/1000 [14:19<00:01,  1.24it/s]

[998/1000]
EN: Oncologist shares case of non-tobacco related cancer in 21-year-old man with ‘sharp teeth,’ says ‘It could have been identified’
BRX: केनसारारि फाहामगिरि आरो देहा फाहामगिरिफोरा बुङो दि बे बेरामखौ होबथानो थाखाय मुलिनि बाहायनायखौ खम खालामनाय जादों |
--------------------------------------------------

Translating: 100%|██████████████████████████▉| 999/1000 [14:21<00:00,  1.05it/s]

[999/1000]
EN: Nutritionist says pineapple and cinnamon may help reduce period cramps naturally
BRX: नीउथ्रिसनिस्टआ बुङो दि आनारस आरो दालसिनिआ माहाजोननि खिन्थिनायखौ मिथिंगायारियै बाङाइ खालामनायाव मदद होनो हागौ |
--------------------------------------------------

Translating: 100%|██████████████████████████| 1000/1000 [14:21<00:00,  1.16it/s]

[1000/1000]
EN: Don’t brush before bed? Your heart might pay the price
BRX: उन्दुनायनि सिगां ब्रास दाखालामनो नाङा > नोंथांनि बिखाया बेसेन होनो हागौ |
--------------------------------------------------
✅ Saved to /home/dingku/Desktop/bodo_translations.txt

🎉 All translations attempted.